### ISSUE TITLE
[BUG] compose up doesn't respect image tag if image has multiple tags

### ISSUE THREAD

**Issue by jaape** [docker/compose#10002]
### Description

Docker compose up doesn't respect specified image tag when multiple tags are present in the local registry

This is problematic in my work as we use the TAG-value from docker compose images -command for logging purposes. Now it shows wrong tag when multiple tags are present.

### Steps To Reproduce

1. Have an image with multiple tags. ie image:tag b4914c7c642b **and** image:another-tag  b4914c7c642b
2. Have a service defined in compose.yml file that uses image:tag as an image
3. Run docker compose up
4. See with **docker compose images** that compose outputs image:another-tag 
5. Docker desktop also shows the wrong image in IMAGE-column

Untagging image:another-tag solves the problem

### Compose Version

```Text
Docker Compose version v2.12.1
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 18
  Running: 0
  Paused: 0
  Stopped: 18
 Images: 220
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: RQ2Q:GRFD:6KMK:YTCE:6ZI4:PT5H:6SHC:BSOV:ENBN:NLN3:G5II:5DHW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
`docker compose images` displays the actual image the service is running (not the one configured in the yaml file, see `docker compose config --images` if this is what you're looking for)
The image that runs is only identified by it's ID, when it has multiple tags, there's no precedence to select one over the other. compose then displays the first in the list.

**Comment by ndeloof** [comment]
please note `docker ps` does the same: the engine API only report (on of the) image tag(s) container is based on.
