### ISSUE TITLE
[BUG] docker-compose and docker compose not working when "Use docker compose V2" is enabled

### ISSUE THREAD

**Issue by jmatom** [docker/compose#10008]
### Description

When I try to run next command it fails:

*Command 1: docker-compose*
```
docker-compose -f docker-compose.local.yml up -d
unknown shorthand flag: 'f' in -f
See 'docker --help'.
```

*Command 2: docker compose*
```
docker compose -f docker-compose.local.yml up -d
unknown shorthand flag: 'f' in -f
See 'docker --help'.
```

If I disabled the option *Use Docker Compose V2* from **Docker Desktop -> General (tab)** then command docker-compose works.
Before this change, it fails for any command, another example:
```
# Example 1
docker compose version
docker: 'compose' is not a docker command.
See 'docker --help'

# Example 2
docker-compose version
docker: 'compose' is not a docker command.
See 'docker --help'
```

### Steps To Reproduce

1. For this OS Version / Platform: Apple M1 Pro + 32GB + Ventura 13.0.1
2. And for any project, run both provided commands
3. The reported error should be visible

### Compose Version

```Text
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
WARNING: Plugin "/Users/jose/.docker/cli-plugins/docker-compose" is not valid: failed to fetch metadata: fork/exec /Users/jose/.docker/cli-plugins/docker-compose: no such file or directory

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: 3P7X:YFVY:GOLQ:GXZM:6M34:A3SN:MD4S:6YW7:FDR4:T7PL:T4BE:MUYC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by danshome** [comment]
This is a huge issue and has development completely blocked on the latest Docker Desktop, at least on MacOS it does. 

The docs state -f is still valid https://docs.docker.com/engine/reference/commandline/compose/

**Comment by Kiyo510** [comment]
@jmatom 
Hi, jmatom.

I had the exact same error the other day.
In my case there was a problem with docker-compose installation.

That is, I forgot to add a "v" in front of the version number, as shown below.

```
curl -L "https://github.com/docker/compose/releases/download/2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

Try installing it with "v" as shown below.

```
curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

ref:
https://stackoverflow.com/questions/58747879/docker-compose-usr-local-bin-docker-compose-line-1-not-command-not-found

**Comment by jmatom** [comment]
Thanks for your info @Kiyo510 I forgot to mention I installed the official dmg package (dmg) for Apple Chip (which has docker, docker compose and Docker UI). Thanks

**Comment by laurazard** [comment]
@jmatom I'm not sure what version of Docker Desktop you had installed when this was reported, but we recently had a bug where the symlinks were not properly created (and so the binary invoked when using `docker compose` would not show up where it should be, leading to those errors). With the `Use docker compose v2` flag disabled and using `docker-compose`, it'll default to `Compose v1`, which you probably have installed in your system.

Could you see if this is still an issue with the latest version of Docker Desktop?

**Comment by Anutrix** [comment]
Issue present in Docker Compose version v2.29.1.
Tested on Linux where there is no Docker Desktop installed.
Tested on Mac where there is Docker Desktop installed.
