### ISSUE TITLE
[BUG] Mandatory variables not throwing errors when not used last

### ISSUE THREAD

**Issue by th0m4s** [docker/compose#10011]
### Description

When using mandatory environment variables as described here (https://docs.docker.com/compose/environment-variables/), errors are not thrown if the absent mandatory variable is not the last variable used in the same configuration line.

For example, using a *Compose* environment variable to set a *container* environment variable like this
```
    - DATA=${MY_VARIABLE?MY_VARIABLE is required}
````
will throw an error if the variable is not defined, whereas
```
    - DATA=${MY_VARIABLE?MY_VARIABLE is required}/${OTHER_PATH}
```
will continue as if everything was ok and an empty string will be used.
It seems that only using a mandatory variable as a last variable during interpolation will throw an error.

### Steps To Reproduce

1. In an empty directory, create an `.env` file with
```
OTHER_PATH=contents
```

2. Create a `docker-compose.yaml` file containing
```
version: "3.9"
services:
  data:
    image: alpine
    environment:
      - DATA=${VARIABLE_A?required variable}/${OTHER_PATH}
```

3. Run `docker compose up`

A warning about OTHER_PATH being unset is shown, but nothing about VARIABLE_A:
```
level=warning msg="The \"OTHER_VAR\" variable is not set. Defaulting to a blank string."
```
It is worth noting that using `${OTHER_PATH:-}` to hide the unset warning doesn't resolve the issue about VARIABLE_A.

### Compose Version

```Text
Docker Compose version v2.10.2  # docker compose version
Docker Compose version v2.10.2  # docker-compose version
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 91
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog      
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Anything else?

Using Docker for Windows with WSL2 backend.

**Comment by AhmedGrati** [comment]
I tried to reproduce the issue on a macOS aarch64, but it works fine and the env variable is set correctly. I think someone with Windows and WSL2 backend, can do a better investigation of the issue.
