### ISSUE TITLE
Is ARM an officially supported plaform for docker-compose V1 now? 

### ISSUE THREAD

**Issue by jumpingliu** [docker/compose#10012]
### Description

Hi, I'm installing docker-compose V1 on arm64 now and I have gone through the related issue but still cannot install docker-compose v1 successfully. I know lots of people are using pip to install compose v1 but I havn't found the instructions on official docs yet. Tks in advance:)

```
$ sudo curl -SL https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-aarch64-debian -o /usr/local/bin/docker-compose
$ sudo chmod +x /usr/local/bin/docker-compose 
$ docker-compose
/usr/local/bin/docker-compose: line 1: Not: command not found
```

environment:
arm64
ubuntu20.04

**Comment by glours** [comment]
Thanks for taking the time to create this issue/pull request!

Unfortunately, Docker Compose V1 has reached end-of-life and we are not accepting any more changes (except for security issues). Please try and reproduce your issue with Compose V2 or rewrite your pull request to be based on the v2 branch and create a new issue or PR with the relevant Compose V2 information.
