### ISSUE TITLE
Docker compose reup command?

### ISSUE THREAD

**Issue by jrj2211** [docker/compose#10033]
### Description

Would be nice to have a command similar to restart, but for up/down: reup?

Docker compose stop && Docker compose start = docker restart
Docker compose down && docker compose up -d = Doesnt seem to exist? 

I'm often doing this several times a day when pushing small updates to my production site and need the container rebuilt.

Totally can do this with a scrip but I think this would be a nice little addition to compose.

From what I can tell this is currently not possible but my apologies if its just named something else or theres a better way.

**Comment by ndeloof** [comment]
You can use `docker compose up --force-recreate` for this purpose
