### ISSUE TITLE
Support using host pid namespace

### ISSUE THREAD

**Issue by robbiev** [docker/compose#1003]
Docker 1.5 added the ability to disable process isolation (docker run --pid=host).

**Comment by dreamcat4** [comment]
+1. This is needed for `pipework` and other system-wide docker plugins (not just networking stuff). *The required functionality necessary for new 1.5 flags was already merged into the `docker-py` library.*

Reference:

https://github.com/docker/docker-py/issues/471

**Comment by InfoSec812** [comment]
+1 - Need this for certain services (e.g. auditd) to run inside of a container.

**Comment by bobrik** [comment]
I believe #1011 introduced desired functionality and this issue could be closed.

**Comment by vdemeester** [comment]
/ping @aanand @bfirsh for closing this one :)
