### ISSUE TITLE
ERROR: for harbor-log  Cannot start service log: failed to create shim task: OCI runtime create failed: container_linux.go:318: starting container process caused "permission denied": unknown

### ISSUE THREAD

**Issue by YZPAWE** [docker/compose#10034]
When I started the harbor using docker-compose up -d , I reported an error about  ERROR: for harbor-log  Cannot start service log: failed to create shim task: OCI runtime create failed: container_linux.go:318: starting container process caused "permission denied": unknown

**Comment by YZPAWE** [comment]
docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:44:05 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.0.0-rc3
  GitCommit:        b78641cb69ee91578b4cd7503dbb734d660adaf4-dirty
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0



docker-compose -v
docker-compose version 1.29.2, build 5becea4c

**Comment by YZPAWE** [comment]
runc -v
runc version 1.0.0-rc3
commit: b78641cb69ee91578b4cd7503dbb734d660adaf4-dirty
spec: 1.0.0-rc5

**Comment by ndeloof** [comment]
Can you successfully run this container directly with `docker run ...` command ?

**Comment by YZPAWE** [comment]
I downgraded the docker and runc versions, and harbor has been installed

**Comment by YZPAWE** [comment]
I downgraded the docker and runc versions, and harbor has been installed
