### ISSUE TITLE
docker-compose with multiple files and automatic path extension

### ISSUE THREAD

**Issue by kaninaba94** [docker/compose#10043]
### Description

This is my folder structure: 

```
├── project_root
│   ├── docker-compose.yml
│   ├── volume
│   │       ├── source
│   ├── folder1
│   │   ├── docker-compose.yml
│   │   ├── volume1
│   │       ├── source

```

docker-compose.yml:
```
version: "3.4"

services:
    service:
        .
        .
        volumes: ./volume/source:/volume/destination
        .
```

folder1/docker-compose.yml:
```
version: "3.4"

services:
    service1:
        .
        volumes: ./volume1/source:/volume1/destination
        .
        .
```

At the moment, executing `docker-compose -f docker-compose.yml -f folder1/docker-compose.yml config` from the `project-root` gives me:
```
version: "3.4"

services:
    service1:
        .
        .
        volumes: /home/.../project-root/volume/source:/volume1/destination
        .
    service2:
        .
        volumes: /home/.../project-root/volume1/source:/volume1/destination
        .
        .
```

It would be nice to have an option to combine the two docker files that automically adapts the volume source location according to the host's folder structure, like this:

```
version: "3.4"

services:
    service1:
        .
        .
        volumes: /home/.../project-root/volume/source:/volume1/destination
        .
    service2:
        .
        volumes: /home/.../project-root/folder1/volume1/source:/volume1/destination
        .
        .
```
Note the changed volume source location in service2.

**Comment by kaninaba94** [comment]
I guess you could also just make use of `$pwd` instead..

**Comment by ndeloof** [comment]
The way `./` is expanded to actual path in a compose file is a mix of legacy decision, which results sometimes in weird behaviors. I agree we should add support for a "relative to compose file" path notation, but to avoid ambiguities and compatibility break, this would need to rely on a new notation, aside `./path` and `~/path` we already support. 
I'm open to suggestions :)

**Comment by kaninaba94** [comment]
My suggestion is to introduce a flag, e.g. `--relative-to-compose-file`, which would lead to the behavior. That way, we would avoid legacy issues. And perhaps it would be used in more and more systems.

**Comment by ndeloof** [comment]
The risk with a flag is that some users would rely on it on a daily basis but might forget to set the flag, still we can't make this the default behavior. An explicit syntax in the compose file would avoid this issue.

**Comment by kaninaba94** [comment]
If it is possible to have an environment variable named, e.g., `CONFIG_PATH` that is passed to each config file individually, that would be convenient and would eliminate the need for additional syntax. E.g., if you do `docker-compose -f docker-compose.yml -f folder1/docker-compose.yml -f folder2/folder21/docker-compose.yml config`, and the individual files look like this:


```
version: "3.4"

services:
    service:
.
.
        volumes:
            - ./${CONFIG_PATH}/volume_path:volume_path
.
.
```

```
version: "3.4"

services:
    service1:
.
.
        volumes:
            - ./${CONFIG_PATH}/volume1_path:volume1_path
.
.
```

```
version: "3.4"

services:
    service21:
.
.
        volumes:
            - ./${CONFIG_PATH}/volume21_path:volume21_path
.
.
```

then `CONFIG_PATH` would resolve to ` `, `folder1` and `folder2/folder21` in the resulting config.

**Comment by kaninaba94** [comment]
Working on the issue, I have posted [this question](https://stackoverflow.com/questions/74881979/how-to-debug-golang) on SO

**Comment by ndeloof** [comment]
closing this issue, please see https://github.com/compose-spec/compose-go/issues/335
