### ISSUE TITLE
Forward mount options

### ISSUE THREAD

**Issue by darkdragon-001** [docker/compose#10066]
### Description

_As stale bot closed #7878 even though there has been activity, I am re-opening this as a new issue._

## Description of the issue

When using `docker run -v p:p:opt,ions` all `opt,ions` are used as (bind) mount options. This allows mounting tmpfs as `exec` instead of `noexec`, overwriting `uid`/`gid` and so on. I think _docker-compose_ should use the same syntax as _docker_ itself.

## Context information (for bug reports)

```
docker-compose version 1.27.4, build unknown
docker-py version: 4.3.1
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g FIPS  21 Apr 2020
```

```
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.15.1
 Git commit:        4484c46
 Built:             Fri Oct  2 19:31:30 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.1
  Git commit:       4484c46
  Built:            Fri Oct  2 00:00:00 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.1
  GitCommit:        
 runc:
  Version:          1.0.0-rc92+dev
  GitCommit:        c9a9ce0286785bef3f3c3c87cd1232e535a03e15
 docker-init:
  Version:          0.18.0
  GitCommit: 
```

## Steps to reproduce the issue

1. Bind-mount a local folder inside the container, bind-mount a tmpfs into a subfolder of the previously mounted folder

### Observed result

Currently, _docker-compose_ supports only selected options for `volumes` and none for `tmpfs`. I would like to create my build directory tmpfs and run tests inside it, which is not possible because of `noexec`. Furthermore, on Fedora, when I create a mount to a non-existing mount point, it is owned by root and not my local (container) user.

### Expected result

Defaults are okay, but I would like to overwrite those in `docker-compose.yml`.

## Additional information

Fedora 33 with cgroups v1 via `moby` and `docker-compose` packages.

**Comment by ndeloof** [comment]
We are unfortunately constrained by https://github.com/moby/moby/blob/master/api/types/mount/mount.go#L117 to support this by the `mount` API. Would need to pass the raw `bind` string to the engine.

**Comment by darkdragon-001** [comment]
> We are unfortunately constrained by https://github.com/moby/moby/blob/master/api/types/mount/mount.go#L117 to support this by the `mount` API. Would need to pass the raw `bind` string to the engine.

Looks like none of the flags https://github.com/moby/sys/blob/mount/v0.1.1/mount/flags.go#L8-L45 is actually supported (only two `data=value` data flags https://github.com/moby/moby/blob/master/api/types/mount/mount.go#L122-L131). Shouldn't be too hard to forward the simple flags I guess?

**Comment by ndeloof** [comment]
Yes, not sure why the more recent "mount" API is that much behind the actual capabilities of the engine

**Comment by ndeloof** [comment]
Can you please share a concrete example using `docker run -v p:p:opt,ions` syntax to create an exec+tmpfs ?

Looking at https://docs.docker.com/engine/reference/run/#volume-shared-filesystems, the only supported options don't allow this, and a quick test with the CLI confirm this is not just a documentation issue:

```
$ docker run -v foo:/bar:exec alpine ls -al /bar
docker: Error response from daemon: invalid mode: exec.
```

**Comment by darkdragon-001** [comment]
You are right, it seems the standard volumes only allow a limited set of options. For `--tmpfs`, it seems that it will be forwarded to `mount` directly: https://docs.docker.com/engine/reference/run/#tmpfs-mount-tmpfs-filesystems

**Comment by ndeloof** [comment]
Compose hardly can do better than `docker run` does if the API doesn't allow :P

**Comment by darkdragon-001** [comment]
For me `tmpfs` is important, so this functionality is completely sufficient! `--tmpfs /tmp:rw,exec` would do.

**Comment by ndeloof** [comment]
Then, you already can do the same in compose.yaml using `tmpfs` :

```yaml
services:
  test:
    image: nginx
    tmpfs: /tmp:rw,exec
```

**Comment by ndeloof** [comment]
I just noticed support for mount options is not documented under https://github.com/compose-spec/compose-spec/blob/master/spec.md#tmpfs, should be added for clarity

**Comment by darkdragon-001** [comment]
Just tested it and can confirm this works :heart_eyes: 

Agree that documentation should be improved here. I gave it a shot in compose-spec/compose-spec#290 .
