### ISSUE TITLE
docker-compose copy file or directory to container

### ISSUE THREAD

**Issue by aGGre55or** [docker/compose#10071]
### Description

This is not a matter of convenience at all, but a matter of necessity. The developers company provides our bank with software in the form of a docker tar image. The bank needs to copy the file to a container that runs on the basis of the received image. If the file isn't copied, then the software provided to the bank cannot work. It turns out that the docker-compose isn't needed, because it is NOT ABLE to solve tasks that a regular dockerfile solves. Therefore, I believe that deprecating file copy support in docker-compose is an anti-pattern for actual operation in docker-compose.

The truth is that people just use docker-compose.yml instead of Dockerfile. The docker-compose authors' theories about how to use it are actually anti-patterns and nonsense. The user of a hammer knows better why he needs a hammer. The manufacturer should not indicate that the hammer should only be used for hammering nails and should not be used for breaking dishes. Buying a separate hammer to beat dishes is stupid.

**Comment by ndeloof** [comment]
Closing as :trollface: 
Seems you have no idea what it means to maintain an open-source software and support thousands users over years.

If you have any real issue or feature request you'd like to discuss in a constructive manner free to open another issue.

**Comment by aGGre55or** [comment]
I realize that this issue with this content is the thousandth in a row on this topic. Support by closing incoming issues looks ridiculous, but it kind of gives you pleasure. This is a real problem for many serious companies around the World including our bank. After so many issues, why not open another one?  #5523 #2105# etc

**Comment by ndeloof** [comment]
```
$ docker compose cp --help

Usage:  docker compose cp [OPTIONS] SERVICE:SRC_PATH DEST_PATH|-
	docker compose cp [OPTIONS] SRC_PATH|- SERVICE:DEST_PATH

Copy files/folders between a service container and the local filesystem

Options:
  -a, --archive       Archive mode (copy all uid/gid information)
  -L, --follow-link   Always follow symbol link in SRC_PATH
      --index int     Index of the container if there are multiple instances of a service .
```
my pleasure
