### ISSUE TITLE
[RFC] rename repository branches

### ISSUE THREAD

**Issue by thaJeztah** [docker/compose#10079]
### Description

Relates to

- https://github.com/docker/roadmap/issues/256
- https://github.com/docker/roadmap/issues/257

When development for Compose v2 (reimplementation in Go) moved to this repository, the `master` branch (in which the code for the (now in "maintenance mode") Python implementation lives, was kept, and a new `v2` branch was created and set as default branch.

Now that v2 is GA, and the default, we should consider:

- renaming the old (python) branch from `master` to `v1`
- renaming the (default) `v2` branch to `main`

Opening this, as I have to fight muscle-memory every time I want to contribute to this repository 😂, and I can expect new contributors to this repository to also run into this (and possibly get confused).

:warning: ❓ For go modules, renaming the branch should have no immediate consequences (unless someone does a `go get github.com/docker/compose/v2@v2` to explicitly include the branch name), but I don't know if renaming the branch would have consequences for Python (don't think so?)

**Comment by glours** [comment]
Hey @thaJeztah 👋

We didn't communicate publicly on this, but this exactly what we decided.
We can keep your issue open to let users know what will happen next April

**Comment by thaJeztah** [comment]
Ah, cool! Wonder if this must be done together with the deprecation, or if we could already do this (I _think_ it should be generally non-disruptive, so perhaps there's no need to wait).

**Comment by laurazard** [comment]
Agreed! Would be nice to do this sooner rather than later. At first glance, I don't think anything would happen (any system automatically getting compose should be using the release URLs such as `https://github.com/docker/compose/releases/download/v2.14.1/...` which stay the same). We can try to investigate a little bit just to make sure.

**Comment by thaJeztah** [comment]
One warning; there was (or is?) a bug on GitHub, where renaming the branch does not update PRs that were opened from the web-ui (edit-button on GitHub). That workflow is probably less common on this repository as it is for the docs repository, but something to be aware of; see https://github.com/moby/mobywebsite/pull/69#issuecomment-1303989034 and https://github.com/docker/docs/pull/14540#issuecomment-1290243551

**Comment by ndeloof** [comment]
closing as done
