### ISSUE TITLE
deploy section and old cpus option

### ISSUE THREAD

**Issue by nexcode** [docker/compose#10075]
1. `deploy` options don't map 1-to-1 to container configurations
2. v2 is not technically older (v2.3 was introduced around the same time as v3.4)
3. The two versions serve different purposes. We recommend v3 in our documentation because it is better suited to deploying distributed applications.

This is just circling back to the same points again, so I'll lock this thread. If you want to keep discussing v2/v3 disparity and Compose format design, please use the [forums](https://forums.docker.com).

_Originally posted by @shin- in https://github.com/docker/compose/issues/4513#issuecomment-377311337_

**Comment by nexcode** [comment]
Initial discussion: https://github.com/docker/compose/issues/10073

**Comment by nexcode** [comment]
This is from the official website of the docker itself:
<img width="978" alt="Снимок экрана 2022-12-13 в 16 34 56" src="https://user-images.githubusercontent.com/10132325/207340469-eaedb43d-c76c-4d8c-a1d4-22fd29b33561.png">

**Comment by nexcode** [comment]
There are many threads on the topic that the deploy section really only works in swarm mode.
Please, explain how it really works :)

**Comment by ndeloof** [comment]
compose specification (2 years old) made v2 vs v3 debate obsolete. You can now use the "legacy" attributes from v2 file format in your compose file, and _should_ omit the `version` attribute.

**Comment by ndeloof** [comment]
also have a look at https://github.com/compose-spec/compose-spec/blob/master/spec.md#cpus for this specific attribute

**Comment by ndeloof** [comment]
I'm re-opening https://github.com/docker/compose/issues/10073, as I can confirm an issue with cpu reservation
