### ISSUE TITLE
[BUG] cpu limit

### ISSUE THREAD

**Issue by nexcode** [docker/compose#10073]
### Description

https://github.com/docker/compose/issues/9268?ysclid=lbm4e4boux299377343
https://github.com/docker/compose/pull/9552

### Steps To Reproduce

compose example file:
```
version: "2.4"
services:
  service:
    image: clickhouse/clickhouse-server:22.6.9.11
    container_name: clickhouse
    network_mode: host
    restart: on-failure
    cpus: 8
```

docker inspect clickhouse | grep -i cpu:
```
            "CpuShares": 0,
            "NanoCpus": 0,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuCount": 0,
            "CpuPercent": 0,
```

But, if manual set from docker `docker update --cpus 8 clickhouse`:
```
            "CpuShares": 0,
            "NanoCpus": 8000000000,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuCount": 0,
            "CpuPercent": 0,
```

### Compose Version

```Text
Docker Compose version v2.12.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 29
  Running: 28
  Paused: 0
  Stopped: 1
 Images: 237
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.14.0-191.el9.x86_64
 Operating System: CentOS Stream 9
 OSType: linux
 Architecture: x86_64
 CPUs: 96
 Total Memory: 251GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by glours** [comment]
hello @nexcode 
The `cpus` attribute has been [deprecated](https://github.com/compose-spec/compose-spec/blob/master/spec.md#cpus), you should use [`deploy.reservations.cpus`](https://github.com/compose-spec/compose-spec/blob/master/deploy.md#cpus)  instead

**Comment by nexcode** [comment]
> hello @nexcode
> The `cpus` attribute has been [deprecated](https://github.com/compose-spec/compose-spec/blob/master/spec.md#cpus), you should use [`deploy.reservations.cpus`](https://github.com/compose-spec/compose-spec/blob/master/deploy.md#cpus) instead

Isn't this just for swarm mode?

**Comment by nexcode** [comment]
I use 2.4 compose specifically to avoid using `--compatibility` flag

**Comment by nexcode** [comment]
> hello @nexcode
> The `cpus` attribute has been [deprecated](https://github.com/compose-spec/compose-spec/blob/master/spec.md#cpus), you should use [`deploy.reservations.cpus`](https://github.com/compose-spec/compose-spec/blob/master/deploy.md#cpus) instead

<img width="978" alt="Снимок экрана 2022-12-13 в 16 34 56" src="https://user-images.githubusercontent.com/10132325/207336755-d2643ec4-5611-4528-9c53-38bf82167bc7.png">
https://github.com/docker/compose/issues/4513#issuecomment-377311337
