### ISSUE TITLE
docker-compose -p projectname ps ; lisiting services which not  even are build

### ISSUE THREAD

**Issue by aayushave** [docker/compose#10085]
OS - centos7
command should list nothing if container doesn't exist of that project, but is listing containers.

((**docker-compose -p ${DOCKER_PROJECT_NAME}   ps --services**  ) | grep "$(docker-compose -p ${DOCKER_PROJECT_NAME}   ps --services --filter 'status=running')" )

**Comment by ndeloof** [comment]
`docker compose ps` indeed lists containers just like it is ran with `--all` option.
I'll look into this today
