### ISSUE TITLE
[BUG] docker compose run and --env-file

### ISSUE THREAD

**Issue by AlexOperator** [docker/compose#10092]
### Description

I'm having trouble with `docker compose --env-file <..> run`. 

It doesn't seem to pass variables from the env file through to the run environment.

Including `env_file` to the service definition does seem to work however.

### Compose Version

```Text
Docker Compose version v2.13.0
```

**Comment by laurazard** [comment]
Hiya @AlexOperator!

When you run `compose --env-file=[file] ...`, all you're doing is telling compose to use a specific env file (without that argument, compose would still look for a `.env` file in the directory you're running the command). However, for the values specified in the `.env` file to take effect, they need to be used in the `environment` section of your service definition, such as:

`.env`:
```bash
TAG=v1.5
```

`compose.yaml`:
```yaml
services:
  web:
    image: "webapp:${TAG}"
```

Hope that helps!

**Comment by AlexOperator** [comment]
It helps, but I can't get over the fact that I am non gender binary confused.
