### ISSUE TITLE
Docker image for docker compose outdated

### ISSUE THREAD

**Issue by ivanmaximenko** [docker/compose#10119]
Hi,
Could you please publish to [dockerhub](https://hub.docker.com/r/docker/compose) a new docker image for the latest docker compose version.
Thank you.

**Comment by glours** [comment]
@ivanmaximenko the Compose image on hub was created by the Compose v1 CI, we don't replicate this as [the official docker image](https://hub.docker.com/_/docker) already embedded Compose.
  
```shell
> docker run -v /var/run/docker.sock:/var/run/docker.sock --rm -it docker compose version
Docker Compose version v2.14.2
```
