### ISSUE TITLE
docker-compose logs for a specific instance of a service

### ISSUE THREAD

**Issue by asaha123** [docker/compose#10130]
### Description

When we have multiple replicas of a service, it would be useful to be able to query the logs for a specific instance.

Similar to how we have for `docker-compose exec` via the `index` option:

```
$ docker-compose exec -ti --index 1 <service name> <command>
```

I looked at the open issues and couldn't see this.

I will be happy to work on a PR as well, if this sounds sensible to add.

Thanks.

**Comment by ndeloof** [comment]
Makes perfect sense to me, especially if you align UX with `docker compose exec` for comparable usage.

**Comment by asaha123** [comment]
Excellent, i will have a go at creating a PR then!

**Comment by asaha123** [comment]
Hi @ndeloof would you able to please approve the PR build? I am having some difficulty in getting all the tests to pass locally without my chages, so would be good to have the feedback from CI.

thanks.

**Comment by asaha123** [comment]
thanks @ndeloof
