### ISSUE TITLE
Update the 2 years old official image with compose installed?

### ISSUE THREAD

**Issue by red8888** [docker/compose#10152]
### Description

It looks like the official image hasn't been updated in 2 years? https://hub.docker.com/r/docker/compose/tags

It has `docker-compose` not `docker compose` installed and seems super outdated.

Is there a reason why this official image was abandoned?

**Comment by glours** [comment]
@red8888  the Compose image on Docker Hub was created by the Compose v1 CI, we don't replicate this as [the official docker image](https://hub.docker.com/_/docker) already embedded Compose.
  
```shell
> docker run -v /var/run/docker.sock:/var/run/docker.sock --rm -it docker compose version
Docker Compose version v2.14.2
```
