### ISSUE TITLE
[BUG] docker-compose cp db/ mongo:/     setenv: invalid argument

### ISSUE THREAD

**Issue by ayzeenm** [docker/compose#10158]
### Description

running:
docker-compose cp db/ mongo:/    
docker-compose
setenv: invalid argument

### Steps To Reproduce

Docker Compose version v2.15.1

### Compose Version

```Text
Docker Compose version v2.15.1
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.7.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.8)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 25
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: KOPP:IAHE:QOHA:THKK:XNHK:TPGW:PF3L:TMOU:OFLH:BSEN:GOSE:XHRC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Please help fix these issues!

**Comment by ayzeenm** [comment]
Also, what is the stable version for working with docker-compose? I've been having lots of similar issues regarding to versions

**Comment by ndeloof** [comment]
Tried to reproduce without success:
```
$ docker compose up -d
[+] Running 1/1
 ⠿ Container truc-test-1  Started                                          0.3s
$ mkdir db
$ touch db/test
$ docker compose cp db test:/
$ docker compose exec test ls /db
test
```

Can you please provide a minimal reproduction example?

**Comment by ndeloof** [comment]
> what is the stable version for working with docker-compose?

Latest, i.e 2.15.1 at time writing

**Comment by ayzeenm** [comment]
@ndeloof I tried re-downloading docker for mac(which includes docker-compose) for this [link](https://docs.docker.com/
https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-arm64) but still gives me same error when running `docker-compose`:
unexpected character "-" in variable name near "docker-compose up -d --build"

**Comment by ayzeenm** [comment]
@ndeloof what to use instead? and what type of env files you mean?
running `docker-compose` works outside of project directory but not inside

**Comment by ayzeenm** [comment]
One last question: what is the latest stable version I can fallback to to fix this issue?

**Comment by ndeloof** [comment]
Check `.env` file in project directory or any file referred by `env_file:` in your compose file. One of those use a variable name with a `-`  which isn't supported (we need to improve error message for such cases, as this is both cryptic and not helpful without file path).

No other compose release did support variable with dashed in name

**Comment by ayzeenm** [comment]
I had this in the `.env` file without knowing, just removed it and everything got fixed. Thank you!
<img width="421" alt="image" src="https://user-images.githubusercontent.com/110478279/211951436-edcdb8a2-a31e-4ea3-a98c-1df209f7bae3.png">

**Comment by ayzeenm** [comment]
Now I have a new error, `docker-compose.yml`has the following code:
```
mongo:
    image: mongo:4.4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: base
      DOCKER_CLIENT_TIMEOUT: 120
      COMPOSE_HTTP_TIMEOUT: 120
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
```
and when I connect to it through this url `mongodb://root:root@mongo:27017/base`in code, it gives the following auth error:
```
database couldn't connect Error: Authentication failed.
2023-01-12 06:03:04     at new MongoError (/application/node_modules/mongoose/node_modules/mongodb/lib/error.js:94:13)
2023-01-12 06:03:04     at new MongoServerError (/application/node_modules/mongoose/node_modules/mongodb/lib/error.js:130:9)
2023-01-12 06:03:04     at Connection.onMessage (/application/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:207:30)
2023-01-12 06:03:04     at MessageStream.<anonymous> (/application/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:60:60)
2023-01-12 06:03:04     at MessageStream.emit (node:events:376:20)
2023-01-12 06:03:04     at MessageStream.EventEmitter.emit (node:domain:470:12)
2023-01-12 06:03:04     at processIncomingData (/application/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
2023-01-12 06:03:04     at MessageStream._write (/application/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
2023-01-12 06:03:04     at writeOrBuffer (node:internal/streams/writable:395:12)
2023-01-12 06:03:04     at MessageStream.Writable.write (node:internal/streams/writable:340:10)
2023-01-12 06:03:04     at Socket.ondata (node:internal/streams/readable:748:22)
2023-01-12 06:03:04     at Socket.emit (node:events:376:20)
2023-01-12 06:03:04     at Socket.EventEmitter.emit (node:domain:470:12)
2023-01-12 06:03:04     at addChunk (node:internal/streams/readable:311:12)
2023-01-12 06:03:04     at readableAddChunk (node:internal/streams/readable:286:9)
2023-01-12 06:03:04     at Socket.Readable.push (node:internal/streams/readable:225:10)
2023-01-12 06:03:04     at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
2023-01-12 06:03:04   ok: 0,
2023-01-12 06:03:04   code: 18,
2023-01-12 06:03:04   codeName: 'AuthenticationFailed',
2023-01-12 06:03:04   [Symbol(errorLabels)]: Set(1) { 'HandshakeError' }
2023-01-12 06:03:04 }
```

Before this it was correctly working but now it doesn't

**Comment by ayzeenm** [comment]
It's super weird, I fixed this by adding a new user to `base` db even though I delete it very frequent(like the past 6 months deleted it many times)
Anyways,thank you @ndeloof  for the help, I really appreciate it!

**Comment by ayzeenm** [comment]
@ndeloof It is really weird,by default recreating the db was adding auth and authorzation, do you know what changed with 2.15.1 of docker-compose to prevent this?

**Comment by ayzeenm** [comment]
this command:
`docker-compose exec mongo mongorestore -u root -p root --authenticationDatabase base -d base ayzeen_new/` was creating base db if not exists and adds data to it.
But now it doesn't do that with docker-compose 2.15.1

**Comment by ndeloof** [comment]
Please try creating a new mongo container with `docker run ...` and run this same command with `docker exec` to confirm this is a compose issue, and not just normal behavior for this image (maybe updated in the meantime?)

**Comment by ayzeenm** [comment]
I am trying to re-produce locally but with no hope, on ec2 it fails with auth error and empty db
i moved compose files to docker/ folder to group them together. does this affect it somehow?

**Comment by zohaibtariq** [comment]
in my case, .env variables messed up like syntax was incorrect so I am seeing this error while executing any docker-compose (docker compose) command

**Comment by MKhasib** [comment]
exactly, thanks @zohaibtariq

**Comment by HananMehmood5** [comment]
In my case, it was .env file with following contents:
```
S3_BUCKET
```
So, i made it like:
```
S3_BUCKET=''
```
Now, it is working for me.

**Comment by nelsonfrank** [comment]
Just check your .env,  Remove any character that's not part of .env file, especially "=" solve the case

**Comment by ndeloof** [comment]
I'm closing this issue has the initial question was answered, please open a new issue if you encounter some more issues with a dedicated description

**Comment by rakesho-vel** [comment]
I also had a same issue, it worked after upgrading docker to latest version
