### ISSUE TITLE
Which Docker image should I use to run Compose in a container?

### ISSUE THREAD

**Issue by glours** [docker/compose#10156]
### Description

 The Compose image on Docker Hub was created by the Compose v1 Continus Integration, so starting a container with this image will give you a `v1.29.x` version of Compose.

As [the official docker image](https://hub.docker.com/_/docker) already embedded latest version of Compose, we won't update the Compose image anymore and we suggest you to use the official docker image instead.
  
```shell
> docker run -v /var/run/docker.sock:/var/run/docker.sock --rm -it docker compose version
Docker Compose version v2.15.1
```

**Comment by milas** [comment]
We have recently also started publishing binary-only images of Compose at https://hub.docker.com/r/docker/compose-bin.

---

You can use this image to choose use a specific version of Compose to use with the docker official image, for example if you want to use the nightly build version of Compose:

```dockerfile
# syntax=docker/dockerfile:1
FROM docker 
COPY --from=docker/compose-bin:edge /docker-compose /usr/libexec/docker/cli-plugins/docker-compose
RUN docker compose version
```

Or to embed a specific Compose version binary into your own image:
```dockerfile
# syntax=docker/dockerfile:1
FROM my-image
COPY --from=docker/compose-bin:latest /docker-compose /usr/bin/compose
RUN compose version
```
