### ISSUE TITLE
[BUG] <Docker compose pulll_policy not working>

### ISSUE THREAD

**Issue by Shubham1406220** [docker/compose#10164]
### Description

We are using docker-compose version 1.29.2 and we have pull_policy: always in our docker-compose configuration but it is not pulling the latest image of same tag.

### Compose Version

```Text
docker-compose version 1.29.2, build unknown
docker-py version: <module 'docker.version' from '/usr/local/lib/python3.7/site-packages/docker/version.py'>
CPython version: 3.7.1
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by glours** [comment]
@Shubham1406220 
Compose v1 is reaching end-of-life soon, we support it only for security fix. Please use Compose v2 instead, take a look to the [installation documentation](https://docs.docker.com/compose/install/) to use it.
