### ISSUE TITLE
[BUG] docker compose run does not preserve colored output when piped to tee

### ISSUE THREAD

**Issue by juanariastn** [docker/compose#10161]
### Description

Running a script inside a container that produces a colored output, it is displayed without colors.

I would expect to see the output preserving colors.

_Note:_ It works fine without the pipe to tee.

### docker-compose.yml
```yml
version: '3.8'

 services:
   nginx-demo:
     image: nginx
     volumes:
       - ./run.sh:/run.sh
```

### My script that produces colored output: run.sh
```bash
 #!/bin/bash

 ls --color=always
```

### Expected behaviour 
Without the pipe to tee, it works fine:
![image](https://user-images.githubusercontent.com/101118197/211419391-0058b682-4703-4f46-9da8-79172d46eb06.png)

## Output
![image](https://user-images.githubusercontent.com/101118197/211420164-11818c4b-36be-4aca-b557-f907d646956c.png)

![image](https://user-images.githubusercontent.com/101118197/211419909-b29f5477-6a84-40a8-a348-b8766ca40b6f.png)
![image](https://user-images.githubusercontent.com/101118197/211419969-8772b220-ebe2-4f58-8973-3577959eab65.png)

### Compose Version

```Text
Docker Compose version v2.13.0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.13.0)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.16)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.22.0)

Server:
 Containers: 26
  Running: 0
  Paused: 0
  Stopped: 26
 Images: 72
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 8.736GiB
 Name: docker-desktop
 ID: WZUS:J2ZC:IJDT:V7LA:XC6C:3ZB5:F2WW:7VIV:QVRM:NZTB:L6VI:7HPU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by juanariastn** [comment]
@rimelek gave me a [great hint](https://forums.docker.com/t/docker-compose-run-does-not-preserve-colored-output-when-piped-to-tee-is-this-a-bug/134004) and it works with: `-e TERM=xterm` parameter. I think its a perfect workaround

**Comment by nicks** [comment]
ya, I think this is more of a shell scripting question. The `|` operator creates a colorless pipe. You can also do something like `unbuffer docker compose ... | tee`, and `unbuffer` will preserve the color before it gets to the pipe.

**Comment by ndeloof** [comment]
Docker Compose v2 detects the stream it get connected to is a terminal, and adjust accordingly. When you pipe command, Compose miss a terminal and then switch to "POSIX stdin/out/err" logic, which avoids ansi color codes and dynamic rendering of the progress events. Depending how you use `tee` here, while this breaks the console output, not doing so would make the second output stream (in most case this one is sent to logs) unusable.

Please note `ls` command as reported in this issue just does the same: ran in a container by `docker run...` it won't automatically adopt colors:
<img width="419" alt="Capture d’écran 2023-01-11 à 13 56 00" src="https://user-images.githubusercontent.com/132757/211811933-ac37cd45-88a5-434e-8a75-30fd6e0a5c18.png">

That being said, `docker run -it nginx ls --color=always / | tee log` **does** preserve colored output, while `docker compose --ansi=always run test ls --color=always | tee log` doesn't, so there's still a divergence in behavior that we need to fix
