### ISSUE TITLE
[BUG] Error killing docker compose through Docker plugin

### ISSUE THREAD

**Issue by taorepoara** [docker/compose#10179]
### Description

When using Docker Compose plugin, the Docker compose sub-process is not be killed with the main process through SIGTERM/SIGINT.

I have got the problem at first by running a `docker compose logs -f` command as a sub-process of a custom CLI. When my CLI stops the child execution, it stops the `docker` process execution but the `docker-compose` process is still running as an orphan and the biggest problem is that it continues displaying the logs...

On another computer I tried to upgrade the CLI plugin to the 2.14.2 and 2.15.1 versions, but it did not resolved anything.

### Steps To Reproduce

In a Docker Compose app directory run the next commands:

```bash
docker compose up -d
docker compose logs -f > /dev/null &
pid=$!
```

If you list the processes using compose logs (`ps -aux | grep "compose logs -f"`) you will see three of them:

1. the grep process
2. the docker process: `docker compose logs -f`
3. the docker compose CLI plugin process: `/usr/libexec/docker/cli-plugins/docker-compose compose logs -f`

That's fine, but running the next command to kill the process, nothing happen:

```bash
kill -s SIGINT $pid
```

You have to run it two more times to really kill the process:

```bash
kill -s SIGINT $pid
kill -s SIGINT $pid
```

Then you'll have the next error message: `ERRO[0522] got 3 SIGTERM/SIGINTs, forcing shutdown`

If you list again the processes (`ps -aux | grep "compose logs -f"`) you will see that the docker compose CLI plugin process remains: `/usr/libexec/docker/cli-plugins/docker-compose compose logs -f`

### Compose Version

```Text
$ docker compose version
Docker Compose version v2.14.1
$ docker-compose version
La commande « docker-compose » n'a pas été trouvée, mais peut être installée avec :
sudo apt install docker-compose
```

### Docker Environment

```Text
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.14.1)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 8
  Running: 4
  Paused: 0
  Stopped: 4
 Images: 60
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.0.12-76060006-generic
 Operating System: Pop!_OS 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 11.68GiB
 Name: pop-os
 ID: MRC2:R5CQ:SJVQ:U5MG:3VS5:P666:AK7U:ZPCQ:RTBR:YSF2:CILN:ZAH3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Might be linked to this issue: https://github.com/docker/compose/issues/9087

I didn't know if this repo was the appropriate one. This looks like more a Docker issue ?

**Comment by glours** [comment]
Hey @taorepoara 
Can you take a look to my [comment](https://github.com/docker/compose/issues/9087#issuecomment-1387136396) in #9087 and let me know if this link to a container stack?
 Otherwise if you could provide a sample to reproduce the issue it would be great 👍

**Comment by taorepoara** [comment]
@glours No it does not seems to be linked.

Here is basic project examble: 

```yaml
services:
  test:
    image: alpine
    command: sh -c 'while true; do sleep 1; echo "coucou"; done'
```

You can try it and see that the process remains with that:

```bash
docker compose up -d
docker compose logs -f &
pid=$!
sleep 1
kill -s SIGINT $pid
kill -s SIGINT $pid
kill -s SIGINT $pid
```

You will still see the logs printing.

**Comment by taorepoara** [comment]
I have also tried to kill the sub-process directly with `kill -s INT <pid>` , but it's never killed with that. I think the problem comes from here.

**Comment by ndeloof** [comment]
I've read some docs, and better understand what's going on:

When you pressed CTRL-C, a signal is not sent only to the parent process, but to the entire process group. So both docker CLI and compose CLI-plugin receive this interruption signal

When you use `kill -SIGTERM <PID>` targeting the parent `docker` command, no signal is sent to the child docker-compose CLI-plugin process. You can use negative syntax to target a process group by his parent `kill -SIGTERM -<PID>`.

```
docker compose up -d
[+] Running 1/0
 ⠿ Container truc-test-1  Running                                          0.0s
$ docker compose logs -f &
[1] 35453
$ truc-test-1  | PING localhost (127.0.0.1): 56 data bytes
truc-test-1  | 64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.059 ms
truc-test-1  | 64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.313 ms
truc-test-1  | 64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.280 ms
truc-test-1  | 64 bytes from 127.0.0.1: seq=3 ttl=64 time=0.374 ms
truc-test-1  | 64 bytes from 127.0.0.1: seq=4 ttl=64 time=0.356 ms
truc-test-1  | 64 bytes from 127.0.0.1: seq=5 ttl=64 time=0.143 ms
truc-test-1  | 64 bytes from 127.0.0.1: seq=6 ttl=64 time=0.324 ms
truc-test-1  | 64 bytes from 127.0.0.1: seq=7 ttl=64 time=0.379 ms
truc-test-1  | 64 bytes from 127.0.0.1: seq=8 ttl=64 time=0.331 ms
truc-test-1  | 64 bytes from 127.0.0.1: seq=9 ttl=64 time=0.655 ms
truc-test-1  | 64 bytes from 127.0.0.1: seq=10 ttl=64 time=0.332 ms
kill -SIGTERM 35453
[1]+  Exit 255                docker compose logs -f
$
```

So, while this is far from being obvious, this just "works as expected"!

**Comment by glours** [comment]
As mentioned by @ndeloof (and after testing also on my side 😉 ) this is an expected behaviour and I confirmed that using `-<PID>` works well to stop the process
I close the issue
