### ISSUE TITLE
Docker Compose V2 doesn't seem to limit the number of concurrent images being pulled.

### ISSUE THREAD

**Issue by fuzzybair** [docker/compose#10190]
### Description

What I am seeing:
     When pulling a large number of images compose attempts to pull them all at the same time causing significant memory usage page swapping. The compose output has many warning and eventually fails. Network and CPU load are minimal.

What I expect:
`docker compose pull` should support the `--parallel #` and/or `COMPOSE_PARALLEL_LIMIT` to reduce system load.

### Steps To Reproduce

1. Seen in Windows and Linux so I don't think the environment matters.
2. Any compose pulling 20+ micro service images.
3. docker compose pull
4. After the pull eventually fails you get the following warning
WARNING: Some service image(s) must be built from source by running:
    docker compose build app-name-12 app-name-13 app-name-11 app-name-6 app-name-14 app-name-17 app-name-16 app-name-15 app-name-18 app-name-19 app-name-20 app-name-21 app-name-22 app-name-23 app-name-24 app-name-26 app-name-25 app-name-27 app-name-29 app-name-28 app-name-30 app-name-31 app-name-32 app-name-34 app-name-33

### Compose Version

```Text
$ docker compose version
Docker Compose version v2.15.1

$ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 39
  Running: 38
  Paused: 0
  Stopped: 1
 Images: 24
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.63GiB
 Name: docker-desktop
 ID: BOH5:MQSD:MCXN:STBH:73SR:ET7G:WP6A:SVUG:IDF6:TSRY:262E:F32H
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

I don't think it has any effect here, but we are using BuildKit as that is a common question. 

Attached the output of a `docker compose pull > docker_pull.log`
[docker_pull.log](https://github.com/docker/compose/files/10472900/docker_pull.log)

**Comment by laurazard** [comment]
Thanks for submitting an issue @fuzzybair! Using `COMPOSE_PARALLEL_LIMIT=1 docker compose pull` successfully makes it so that only 1 image is pulled at a time for me. I know you mentioned this option in your issue, but can you confirm that doesn't work for you?

**Comment by ndeloof** [comment]
according to https://github.com/docker/compose/blob/v2/pkg/compose/pull.go#L67 limit is also applied to pulls

**Comment by fuzzybair** [comment]
Thanks @laurazard  and @ndeloof That does seem to work as expected and COMPOSE_PARALLEL_LIMIT=2 worked as well. It looks like I can just handle a higher build count than image pull, probably an issue with our local registry. Also it would probably be good to document this on https://docs.docker.com/engine/reference/commandline/compose_pull/ currently it just indicates that --parallel and --no-parallel are deprecated.
