### ISSUE TITLE
Add `mode`, `uid` & `gid` for non-swarm container secrets

### ISSUE THREAD

**Issue by peterge1998** [docker/compose#10205]
### Description

I would like to set the `mode`, `uid` & `gid` for non swarm container secrets too.
As @noahehall wrote in #9648, its currently only supported in docker compose swarm service tasks.

**Comment by ndeloof** [comment]
No need to create a new issue, #9648 is already tagged as "enhancement"

**Comment by peterge1998** [comment]
Okay, I understood #9648 as issue for mode, uid & gid not working in swarm service tasks, that's why I opened an issue for the non-swarm compose. But if this is already meant by #9648, great :+1:
