### ISSUE TITLE
[Feature Request] switch to enable guessing when to allocate a TTY

### ISSUE THREAD

**Issue by jedwards1211** [docker/compose#10227]
### Description

So, I see that y'all gave up on tty detection because of some obscure bug in #9035.
But can we have switches in `docker exec/run` and `docker compose exec/run` to turn on tty detection when we want to use it?

Having to deal with `-i`, `-t`, and `-T` is driving me insane, especially since the behavior of `docker exec` and `docker compose exec` is flagrantly inconsistent in this regard (though the inconsistency is a [separate issue](https://github.com/docker/compose/issues/10228)):

```
> echo 'SELECT 1;' | docker         exec    db psql -U postgres
# (no output)

> echo 'SELECT 1;' | docker compose exec    db psql -U postgres
# (outputs "the input device is not a TTY" and exits)



> echo 'SELECT 1;' | docker         exec -i db psql -U postgres
# (operates on piped input)

> echo 'SELECT 1;' | docker compose exec -i db psql -U postgres
# (outputs "the input device is not a TTY" and exits)

> echo 'SELECT 1;' | docker compose exec -T db psql -U postgres
# (operates on piped input)
```

**Comment by ndeloof** [comment]
https://github.com/docker/compose/pull/9035 has been revisited, and we auto-disable TTY allocation if user don't use a TTY (see https://github.com/docker/compose/blob/v2/cmd/compose/exec.go#L71)

Distinct default values used by docker-compose is a legacy decision from 2015, we have to live with this.
