### ISSUE TITLE
[BUG] this error may indicate that the docker daemon is not running

### ISSUE THREAD

**Issue by daniloopinheiro** [docker/compose#10223]
### Description

docker compose ps
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%2
2label%22%3A%7B%22com.docker.compose.oneoff%3DFalse%22%3Atrue%2C%22com.docker.compose.project%3Dbackend%22%3Atrue%7D%7D": open //./pipe/ docker_engine: The system does not
o can find the specified file.

**Comment by glours** [comment]
Hello @daniloopinheiro 

Can you check that your Docker engine is running :`docker ps`? If you get the same kind of error, check if Docker Desktop (on Mac and Windows) or docker service is running (Linux)

**Comment by sureshsgith** [comment]
Hello @daniloopinheiro 

This error message suggests that the Docker daemon is not running, which is required for Docker Compose to work. To resolve the issue, start the Docker daemon and try running the **' docker-compose ps '** command again. If the issue persists, ensure that the Docker service is properly installed and configured on your system.

Suresh

**Comment by DopSkillDev** [comment]
# Hey guys, I already noticed the error that was occurring, some files were missing characters: 

![WhatsApp Image 2023-02-01 at 10 26 01 PM](https://user-images.githubusercontent.com/52793184/216208691-23e1fd3a-8685-4c2a-aa8d-574d17a86195.jpeg)
![WhatsApp Image 2023-02-01 at 10 26 30 PM](https://user-images.githubusercontent.com/52793184/216208696-c51692c1-df2f-4b8b-9520-b3673803fe68.jpeg)
![WhatsApp Image 2023-02-01 at 10 27 14 PM](https://user-images.githubusercontent.com/52793184/216208698-8005d7f4-8007-4159-8e92-0558f1cdcbba.jpeg)
![WhatsApp Image 2023-02-01 at 10 27 45 PM](https://user-images.githubusercontent.com/52793184/216208701-7789d384-18af-4263-b036-31d89fa570cf.jpeg)

**Comment by carlosgabrielmf** [comment]
if you OS is linux, you can try with: download de debian package in your pc, and install like: `sudo apt-get install ./<name the file.deb>` i hope resolve you problem.

**Comment by Flexibilit** [comment]
Good morning, I am having an issue with my wsl, what can i do?

**Comment by akhilender-bongirwar** [comment]
Hey @Flexibilit,
It seems like you've recently installed Docker Desktop and attempted to run a docker <command>. If that's the case, you can resolve the error by following these steps:

- Sign up for Docker Desktop.
- After signing up, refresh your environment.
- Retry the command that previously resulted in an error.

This approach has been effective for me in resolving similar issues.

**Comment by LeMatur** [comment]
> ### Description
> docker compose ps error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%2 2label%22%3A%7B%22com.docker.compose.oneoff%3DFalse%22%3Atrue%2C%22com.docker.compose.project%3Dbackend%22%3Atrue%7D%7D": open //./pipe/ docker_engine: The system does not o can find the specified file.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Compose Version
> _No response_
> 
> ### Docker Environment
> _No response_
> 
> ### Anything else?
> _No response_

Hey @daniloopinheiro , 

If you just installed Docker, make sure you open the Docker installed app, agree to the terms and condition first, then login to your account before you try to use it.

It just worked for me

**Comment by Tarikul-Islam-Shykat** [comment]
i turned the docker desktop on. Then ran the command to start the appwrite and it worked then. If it helps, try.

**Comment by ranafaraz** [comment]
i reinstall the wsl and the error is resolved (for windows platform)

**Comment by aeharake** [comment]
guys just end all wsl processes and you should be fine
