### ISSUE TITLE
[BUG] The up and run commands of docker-composer produce different results

### ISSUE THREAD

**Issue by wutianjun5858** [docker/compose#10234]
### Description

"dockerfile, docker-compose and entrypoint.sh remain unchange:
- dockerfile:
```dockerfile
FROM ubuntu:22.04

RUN set -x; apt-get update \
&& apt-get install gosu -y \
&& apt-get install git -y \
&& apt-get install software-properties-common -y \
&& apt-get install build-essential -y \
&& apt-get install unzip -y \
&& apt-get install python3-pip -y \
&& apt-get install python3.10-venv -y \
&& apt-get install nodejs npm -y \
&& apt-get install curl wget iputils-ping xz-utils -y \
&& add-apt-repository ppa:neovim-ppa/unstable -y \
&& apt-get update \
&& apt-get install neovim -y \
&& apt-get install golang-go -y \
&& rm -rf /var/lib/apt/lists/* \
&& useradd --create-home --no-log-init --shell /bin/bash jun \
&& adduser jun sudo \
&& echo 'jun:123456' | chpasswd \
&& gosu nobody true

WORKDIR /home/jun
COPY ./entrypoint.sh ./
RUN chmod +x /home/jun/entrypoint.sh
ENTRYPOINT ["/bin/bash","-c", "/home/jun/entrypoint.sh"]
```
- docker-compose.yml
```yml
version: 'v1'
services:
  ubuntu2204_neovim:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ~/jun_workspace:/home/jun/jun_workspace
    stdin_open: true
    tty: true
    image: tianjunwu/ubuntu2204_neovim
    container_name: ubuntu2204_neovim
```
- entrypoint.sh
```shell
#!/bin/sh

# if user is root
if [ "$(id -u)" = '0' ]; then
	find /home/jun/jun_workspace \! -user jun -exec chown jun '{}' +
	echo "test!!!" >>/home/jun/a.txt
	exec gosu jun:jun /bin/bash "$@"
	#exec gosu jun bash "$@"
fi
tail -f /dev/null
```

"

### Steps To Reproduce

1. docker-compose build
2. docker-compose run ubuntu2204_neovim. (error: do not change user as jun)
3. docker-compose up -d (correct: change user as jun)

### Compose Version

```Text
v2.15.1
```

### Docker Environment

```Text
➜ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 19
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc version: v1.1.3-0-g6724737
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-80-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.843GiB
 Name: tj
 ID: 7WHE:EGF3:XZY2:IPRS:2GFG:2RO5:VXN4:GAHM:PWY2:HZWH:OJHQ:W43U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by laurazard** [comment]
Hi @wutianjun5858, thanks for the report!

The `compose run` command overrides the command/entrypoint specified either in the Compose file or the Dockerfile.

Take for example the Dockerfile
```Dockerfile
FROM alpine:latest
CMD ["echo", "hello world"]
```
And the Compose file
```yaml
services:
    test:
        build:
            context: ./
```

Running `compose up` will output `hello world`, but running `compose run test echo bye bye` will output `bye bye`.

It seems to me the issue here is that when you're running the `compose up` command, `.../entrypoint.sh` is not being executed.

I'm closing this since it doesn't seem like an issue, but feel free to comment further if there is more information.

**Comment by wutianjun5858** [comment]
> Hi @wutianjun5858, thanks for the report!
> 
> The `compose run` command overrides the command/entrypoint specified either in the Compose file or the Dockerfile.
> 
> Take for example the Dockerfile
> 
> ```dockerfile
> FROM alpine:latest
> CMD ["echo", "hello world"]
> ```
> 
> And the Compose file
> 
> ```yaml
> services:
>     test:
>         build:
>             context: ./
> ```
> 
> Running `compose up` will output `hello world`, but running `compose run test echo bye bye` will output `bye bye`.
> 
> It seems to me the issue here is that when you're running the `compose up` command, `.../entrypoint.sh` is not being executed.
> 
> I'm closing this since it doesn't seem like an issue, but feel free to comment further if there is more information.

I can be sure that entrypoint.sh is definitely executed.
