### ISSUE TITLE
[BUG] compose v2 specification does not support docker-compose.overrides.yml or compose.overrides.yml

### ISSUE THREAD

**Issue by audiolion** [docker/compose#10237]
### Description

I saw that compose v1 support will be dropped in June 2023, and that compose v2 is supposed to be a drop-in replacement. However, there is a breaking change if you were previously relying on the behavior that `docker-compose.overrides.yml` would automatically merge with your `docker-compose.yml` file without needing to specify it explicitly e.g. `docker compose -f docker-compose.yml -f docker-compose.overrides.yml`.

This is not a "bug" per say, but an issue that I think will come up as people try to migrate to compose v2. I think its worth either:
1. adding support for `docker-compose.overrides.yml` and continuing forward by also supporting `compose.overrides.yml`
2. supporting `docker-compose.overrides.yml` still but sunsetting the behavior and offering a migration path
3. documenting that `docker-compose.overrides.yml` was removed in compose v2 and how to migrate off of it

### Steps To Reproduce

1. Make a `compose.yml` or `docker-compose.yml` file and a `compose.overrides.yml` or `docker-compose.overrides.yml` file
2. Run compose v2 and see that the config is not automatically merged `docker compose config`

### Compose Version

```Text
Docker Compose version v2.15.1
```

### Docker Environment

```Text
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 14
  Running: 1
  Paused: 0
  Stopped: 13
 Images: 80
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.765GiB
 Name: docker-desktop
 ID: DHGY:RGO3:6BZ5:SVRR:FEBY:QG6D:EVCP:GSFA:XOQ2:AV6M:S5HI:4XG2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

<img width="995" alt="image" src="https://user-images.githubusercontent.com/2430381/216619997-822b2815-98a1-4e2b-bde6-cf659fd47bc5.png">
https://docs.docker.com/compose/reference/#use--f-to-specify-name-and-path-of-one-or-more-compose-files

**Comment by Supportic** [comment]
For me it's working on Docker Compose version v2.15.1
Probably because of "yaml" instead of "yml" extension and "override" instead of "overrides"

![2023-02-06_14-41](https://user-images.githubusercontent.com/20886239/216986690-6bd9a829-d9dc-4ea1-bc1f-e3a2d9c0bcca.png)

**Comment by audiolion** [comment]
@ndeloof yep the issue was the file I had an `s` on `override`, (`compose.overrides.yml` => `compose.override.yml`).
