### ISSUE TITLE
--exit-code-from with matching (non-generic) --abort-on-container-exit

### ISSUE THREAD

**Issue by julianrutten** [docker/compose#10233]
### Description

A common use-case for docker compose is to run orchestrated tests. What I need to do is wait for the database to come up (using `depends_on`), after that I run a container that applies any migrations and sets up the database. Only after this has finished, using another `depends_on` with condition `service_completed_succesfully` on the migration container a server starts, it must happen in this order because the server loads certain values from the database on startup. Only then can I start my testing container using a condition `service_healthy` (with a curl healthcheck) on the server container. However this does not work with `--exit-code-from` because it implies `--abort-on-container-exit` and ofcourse the migration container has exited, so it just stops all containers then.

Ideas? Am I missing something that can be solved with the current specification? Or is there something fundamental that prevents this from being added.

Seems to be related to #10225 however I want to only exit on the specified `--exit-code-from` container and not any other container

**Comment by ndeloof** [comment]
Such a complex scenario hardly fit into docker compose existing flags to monitor container state and exit code.
A simple workaround is to run your test stack with `docker compose up` and explicitly inspect the testing container after completion with `docker inspect project-test-1 -f '{{.State.ExitCode}}'`
