### ISSUE TITLE
fig.sh is down

### ISSUE THREAD

**Issue by k4nar** [docker/compose#1023]
I don't know if it's linked to the repo's renaming, but I just saw that fig.sh was down.

Wouldn't it be a great idea to at least provide a redirection to a new website ? :)

**Comment by k4nar** [comment]
According to [this comment](https://github.com/docker/compose/pull/835#issuecomment-70859463) fig.sh should stay up.

**Comment by cpuguy83** [comment]
This is back up.  Thanks for the report!
