### ISSUE TITLE
[BUG] docker-compose --project-dir uses docker-compose.yaml from home dir, instead of from directory

### ISSUE THREAD

**Issue by d2a-raudenaerde** [docker/compose#10268]
### Description

I have some projects with docker-compose.yaml files, say:

* project-a/docker-compose.yaml
* project-b/docker-compose.yaml

And also a `docker-compose.yaml` in my home-dir (`~`)

When running `docker-compose  --project-dir project-a up`, it takes the `docker-compose.yaml` from my home dir instead of the one in the `project-a` dir.

As they were quite similar, it cost me some time to understand what was going on. Finally, using `--verbose` I tracked it down.

The docs indicate:

```
  --project-directory PATH    Specify an alternate working directory
                              (default: the path of the Compose file)
```

So I assumed it would take the `docker-compose.yaml` from the working directory?

### Steps To Reproduce

Make a directory with a docker-compose.yaml.
Make a docker-compose.yaml in your home directory

run 

docker-compose  --project-dir project-a up

It uses the docker-compose from the homedir.

### Compose Version

```Text
docker-compose version 1.29.2, build `5becea4c`
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 186
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-43-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 27.27GiB
 Name: robuntu
 ID: ZNTS:O7NA:RM4L:CE2X:N5JT:DXI6:JXHD:QRFI:54XS:XLTW:3ECG:PF5I
 Docker Root Dir: /var/lib/docker
```

**Comment by klutzer** [comment]
Same issue here after upgrading to the last compose version

**Comment by ndeloof** [comment]
`--project-dir` set the project directory (i.e how `.` is resolved in your compose.yaml file) but has no impact on the way compose.yaml file is loaded. Actually this is the other way: if you set a compose file path using `--file`, the project directory is set accordingly (as explain by help "default: the path of the Compose file").

I'm closing this issue as "works as expected"

**Comment by d2a-raudenaerde** [comment]
@ndeloof if this is the desired behaviour, could you at least update the helptext?

The current help-text suggests something different that you described imho. 

 ```
 --project-directory PATH    Specify an alternate working directory
                              (default: the path of the Compose file)
```
Should b,maybe read:


 ```
 --project-directory PATH    Specifies how the . is resolved in the compose.yaml file.
```
