### ISSUE TITLE
Check remote server is reachable 

### ISSUE THREAD

**Issue by showierdata9978** [docker/compose#10260]
### Description

A way to depend on a remote server being reachable

**Comment by showierdata9978** [comment]
Useful for things like discord bots, etc

**Comment by ndeloof** [comment]
IIUC you'd like docker compose to provide some way to check your application is reachable, don't you ?
Compose offers the `ps` command to check application is healthy according to configurable healthcheck command ran inside container, but for anything application-level you're best placed to know how to test it, typically running some `curl ...` command. Also "reachable" highly depends on "where do you run the command from"
