### ISSUE TITLE
[BUG] docker runs from wsl1 against docker desktop but docker-compose exits with suggestion to upgrade to wsl2

### ISSUE THREAD

**Issue by ksumit** [docker/compose#10298]
### Description

I installed docker-ce-cli on ubuntu on wsl1 and then docker desktop on windows. With following export, i'm now able to run docker commands (list images, run a container etc) after enabling "Expose daemon on tcp://localhost:2375 without TLS" option on docker desktop:
```
export DOCKER_HOST=tcp://localhost:2375
```

However running docker-compose gives the following message and exits:
```
$ docker-compose

The command 'docker-compose' could not be found in this WSL 1 distro.
We recommend to convert this distro to WSL 2 and activate
the WSL integration in Docker Desktop settings.

For details about using Docker Desktop with WSL 2, visit:

https://docs.docker.com/go/wsl2/
```

I would love to continue to use wsl1 for my work because of the flexibility in accessing data from my windows drives as mounted paths without any performance hits (wsl2 has major issues and latencies in accessing data from windows drives). I'm hoping, this is some `hardcoded` message somewhere in docker-compose that is just spitting it out on detecting wsl1 environment and there is no limitation on running `docker-compose` in wsl1 (given that i can run containers now!). I did search this project but couldn't locate it. Appreciate your help in figuring out a way to continue to use wsl1 for docker-compose too!

### Compose Version

```Text
Setting up docker-compose (1.25.0-1) ... (this is from installation output, docker-compose version command doesn't work on wsl1)
```

### Docker Environment

```Text
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.79.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.66GiB
 Name: docker-desktop
 ID: D73P:CYRR:RHHM:CPZW:7MAS:STZF:OTGS:TMMH:RGQB:7C6Q:YDSA:XQBO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```
```


### Anything else?

_No response_

**Comment by ksumit** [comment]
Looking at the `docker info` output i figured that `docker-compose` is also located at `/usr/libexec/docker/cli-plugins/docker-compose` and using that works!!! So technically i'm unblocked, should we fix the `docker-compose` script that's getting installed as `/usr/bin/docker-compose`?

**Comment by milas** [comment]
Compose v1 is EOL - I'm not going to be able to provide any support for getting it running under WSL1, sorry 🙃 

That said, you've got Compose v2 installed, which is invoked by running `docker compose` (space rather than hyphen). It's a plug-in, which as you've found is located under `/usr/libexec/docker/cli-plugins/` - it's invoked by the Docker CLI, which has its own plugin path precedence rules.
