### ISSUE TITLE
[BUG] down specific containers in a project, takes down full project

### ISSUE THREAD

**Issue by marksie1988** [docker/compose#10295]
### Description

I currently use devcontainer, with this I have a `docker-compose.workspace.yml` file that launches the container for development. I then have a 2nd `docker-compose.yml` file that has some containers required for running python tests against. 

I use nox to start the containers, run the tests and then stop the containers. However when it stops the containers it is downing the whole project rather than just the containers in the specified `docker-compose.yml`

### Steps To Reproduce

1. from devcontainer run nox which executes command:
```
docker compose --project-name pyarr_devcontainer -f .devcontainer/docker-compose.yml up -d
```
2. this brings up the containers required for testing
3. python tests are run
4. once python tests are run nox will execute command:
```
docker compose --project-name pyarr_devcontainer -f .devcontainer/docker-compose.yml down
```

This should just shutdown the test containers inside `docker-compose.yml` that are part of the project, instead it shuts the whole project down. 

### Compose Version

```Text
Docker Compose version v2.16.0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 198
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 3.10.0-1160.83.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.26GiB
 Name: devcontainer-host
 ID: Y2WE:4PHB:RX3L:TYQK:LL7N:MDIY:EUI7:R2NX:RR6W:OI4U:YIYG:KR7U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
Tested with v2.17.3 and only services defined in compose.yaml file get stopped by `docker compose -p xxx -f yyy down`
Also, command fails as some remaining services still are connected on (shared) network, I wonder this is something we should detect and skip removal accordingly.

**Comment by ndeloof** [comment]
Closing as #1055 has been merged
