### ISSUE TITLE
Inconsistent behavior between `--env-file` CLI flag and `env_file` YAML field

### ISSUE THREAD

**Issue by Legion112** [docker/compose#10296]
# step to reproduce

1. clone this repo https://github.com/Legion112/docker-compose-env-file
2. run `VARIABLE_FROM_DOT_ENV_DOCKER=somevalue docker compose run --rm app`

You would see WARNING like : `WARN[0000] The "VARIABLE_FROM_DOT_ENV" variable is not set. Defaulting to a blank string. `

## How to remove that warning:

1. run `VARIABLE_FROM_DOT_ENV_DOCKER=somevalue docker compose --env-file .env.docker run  --rm app`

Now imaging that you have a 'Makefile' like 
```
doctrine.reload:
	@docker-compose exec app php bin/console --env=test doctrine:database:drop --if-exists --force
	@docker-compose exec app php bin/console --env=test doctrine:database:create --if-not-exists
	@docker-compose exec app php bin/console --env=test doctrine:migrations:migrate --no-interaction
	@docker-compose exec app php bin/console --env=test doctrine:fixtures:load --append
```
In every call of `docker-compose exec` you have to pass `--env-file` otherwise you would see those annoying warning.

Would be nice to not pass `--env-file` on every CLI call.

**Comment by glours** [comment]
Hey @Legion112 
You can't define an `env_file` attribute as a top level element on a Compose file but you're able to do that on [the service level](https://github.com/compose-spec/compose-spec/blob/master/spec.md#env_file)
```yaml
services:
  nginx:
     env_file: .myEnvFile
    ...
  app:
    env_file: 
      - ./.myEnvFile
      - ./.anotherEnvFile
```

That way you could decide to use a common env file and/or specific ones for your different sevices

**Comment by glours** [comment]
Yes, but values defined in the files specified with the `env_file` attribute will take precedence on the `.env` file ones
https://docs.docker.com/compose/environment-variables/envvars-precedence/

**Comment by Legion112** [comment]
@glours please download this example https://github.com/Legion112/docker-compose-env-file 
And run it  you will get that I mean.

**Comment by Legion112** [comment]
My application use .env
I don't wanna this behavior from `docker-compose`

I don't wanna see those warnings.

**Comment by Legion112** [comment]
But if you run the following command you won't see warning:
```
VARIABLE_FROM_DOT_ENV_DOCKER=somevalue docker compose --env-file .env.docker run  --rm app
```

I don't wanna everywhere to put this to every command line call.
I want an the ability to set in once and for all at `docker-compose.yaml` 
On root level or something

**Comment by glours** [comment]
I don't get your issue, sorry.
In your example you defined `VARIABLE=${VARIABLE_FROM_DOT_ENV_DOCKER}` in the `.env.docker` file but you never defined the value of `VARIABLE_FROM_DOT_ENV_DOCKER` anywhere else, so Compose let you know the variable isn't set. 
You can check this behaviour by adding a default value to your `VARIABLE` declaration in the `.env.docker` file like this
```
VARIABLE=${VARIABLE_FROM_DOT_ENV_DOCKER-MyDefaultValue}
```

**Comment by Legion112** [comment]
@glours try to run that one https://github.com/docker/compose/issues/10296#issuecomment-1437144338
Do you see a warning?

**Comment by hulkthedev** [comment]
I have this problem every few months and I don't understand why it isn't finally fixed.

The whole internet is full of it. Please finally fix it.
If I specify a path for the env files in the DC file, it will NEVER be found. Never! Anything that isn't in the root OR is named something other than ".env" will result in an error message. Why?

Official documentation says I can create various env files and import them one after the other, but that doesn't work.

Why not just include the file that the user specifies? No ifs and buts...

**Comment by glours** [comment]
No there is no warning because starting your command with `VARIABLE_FROM_DOT_ENV_DOCKER=somevalue` define explicitly the value for `VARIABLE_FROM_DOT_ENV_DOCKER` so Compose is able to replace the value in the env file with that one!

**Comment by Legion112** [comment]
@glours run `VARIABLE_FROM_DOT_ENV_DOCKER=somevalue docker compose --env-file .env.docker run  --rm app`

Without `--env-file` 💣

**Comment by Legion112** [comment]
@hulkthedev you are descriving a different issue.

It's not related what I have reported here.

**Comment by glours** [comment]
@Legion112 Ok I got it, sorry, I'll check why we don't have the same behaviour between the usage of the  `--env-file` flag and the `env_file` attribute

**Comment by Legion112** [comment]
How is it going on this one?

**Comment by Legion112** [comment]
Could we make that even default location for  .env file could be configured. For example via environment variable?

**Comment by ndeloof** [comment]
`.env` file default location is current working directory. This is a common pattern for languages relying on such a file (python, ruby...)

**Comment by hahattan** [comment]
> `.env` file default location is current working directory. This is a common pattern for languages relying on such a file (python, ruby...)

Might be out of topic here, but I noticed the if you're using `-f/--file` option the `.env` needs to be in the first location:
for example I was running `docker compose -f ~/upstream/docker-compose.yml -f docker-compose-local.yml up -d`. In this case the `.env` needs to be in `~/upstream` to work correctly.

@ndeloof is this the correct behavior ?

**Comment by ndeloof** [comment]
@hahattan project directory is indeed set by the first compose file loaded, and `.env` is loaded based on this project directory (as other `./xx` paths in yaml configuration)

**Comment by hahattan** [comment]
> @hahattan project directory is indeed set by the first compose file loaded, and `.env` is loaded based on this project directory (as other `./xx` paths in yaml configuration)

@ndeloof thanks for the clarification.
So in my case I need to set `--project-directory`  to current working directory to load the local `.env` file, is it correct?

**Comment by ndeloof** [comment]
@hahattan you can but then path resolution in your compose file will be affected. Better use `--env-file .env` to explicitly load this env file and keep parsing use paths relative to first compose file
