### ISSUE TITLE
Docker-compose build not working but docker build is

### ISSUE THREAD

**Issue by kekec777** [docker/compose#10304]
### Description

Hi everyone
So i have just updated my system (OMV)
and now im facing a strange issue

So BEFORE i updated i could run "docker-compose up -d wordpress"
and my compose file looks like this:
`  wordpress:
    build: 
      context: ./dockerfiles/wordpress
      dockerfile: Dockerfile
      tags:
        - wordpress:latest
    image: wordpress:latest
    container_name: wordpress`

and the dockerfile:
`FROM wordpress:latest
RUN chmod o+r /etc/resolv.conf && apt-get update && apt-get install libvirt-clients network-manager iputils-ping sudo nano rsync grsync wget nano -y bash`

and this was working also with my watchtower that updates all my containers...

So now when i run  "docker-compose up -d wordpress" it just download wordpress , totally ignores my dockerfile
If i run "docker-compose build wordpress" its fails with chmod: changing permissions of '/etc/resolv.conf': Read-only file system

BUT if i run "docker build dockerfiles/wordpress/ -t wordpress:latest" everythings is executed without problem

What am i doing wrong? or missing? 

Thanks in advise

### Compose Version

```Text
Docker Compose version v2.16.0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 29
  Running: 29
  Paused: 0
  Stopped: 0
 Images: 44
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.0.0-0.deb11.6-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.45GiB
 Name: MYSERVER
 ID: XX
 Docker Root Dir: /srv/dev-disk-by-uuid-2d63569d-15a7-41a3-8009-e9b487095e11/docker
 Debug Mode: false
 Username: USERNAME
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by laurazard** [comment]
Hi @kekec777,

By default, when an image has an `image` field set and also a `build` section, Compose will first try to PULL the image and then try to BUILD the image if it was not found. You can read more about this in the relevant part of the [Spec](https://github.com/compose-spec/compose-spec/blob/master/build.md#consistency-with-image).

In your case, you can change the name of your `image` attribute to something that doesn't exist (you can do `[myproject]/wordpress`, or something else) or you can set the `pull_policy` [attribute](https://github.com/compose-spec/compose-spec/blob/master/spec.md#pull_policy) to `build` to ensure Compose always BUILDS the image.

**Comment by kekec777** [comment]
> Hi @kekec777,
> 
> By default, when an image has an `image` field set and also a `build` section, Compose will first try to PULL the image and then try to BUILD the image if it was not found. You can read more about this in the relevant part of the [Spec](https://github.com/compose-spec/compose-spec/blob/master/build.md#consistency-with-image).
> 
> In your case, you can change the name of your `image` attribute to something that doesn't exist (you can do `[myproject]/wordpress`, or something else) or you can set the `pull_policy` [attribute](https://github.com/compose-spec/compose-spec/blob/master/spec.md#pull_policy) to `build` to ensure Compose always BUILDS the image.

Thanks for the reply :)
But can you explain why its still fails when i run "docker-compose up -d wordpress"
`RUN chmod o+r /etc/resolv.conf && apt-get update && apt-get install libvirt-clients network-manager iputils-ping sudo nano rsync grsync wget nano -y bash:
#0 0.764 chmod: changing permissions of '/etc/resolv.conf': Read-only file system
`

but working when i run "docker build dockerfiles/wordpress/ -t wordpress:latest" everythings is executed without problem ...

**Comment by kekec777** [comment]
> Hi @kekec777,
> 
> By default, when an image has an `image` field set and also a `build` section, Compose will first try to PULL the image and then try to BUILD the image if it was not found. You can read more about this in the relevant part of the [Spec](https://github.com/compose-spec/compose-spec/blob/master/build.md#consistency-with-image).
> 
> In your case, you can change the name of your `image` attribute to something that doesn't exist (you can do `[myproject]/wordpress`, or something else) or you can set the `pull_policy` [attribute](https://github.com/compose-spec/compose-spec/blob/master/spec.md#pull_policy) to `build` to ensure Compose always BUILDS the image.

Thanks for the reply :)
But can you explain why its still fails when i run "docker-compose up -d wordpress"
`RUN chmod o+r /etc/resolv.conf && apt-get update && apt-get install libvirt-clients network-manager iputils-ping sudo nano rsync grsync wget nano -y bash:
#0 0.733 chmod: changing permissions of '/etc/resolv.conf': Read-only file system
------
failed to solve: process "/bin/sh -c chmod o+r /etc/resolv.conf && apt-get update && apt-get install libvirt-clients network-manager iputils-ping sudo nano rsync grsync wget nano -y bash" did not complete successfully: exit code: 1

`
This is permission issue?

but working when i run "docker build dockerfiles/wordpress/ -t wordpress:latest" everythings is executed without problem ...

**Comment by kekec777** [comment]
> Hi @kekec777,
> 
> By default, when an image has an `image` field set and also a `build` section, Compose will first try to PULL the image and then try to BUILD the image if it was not found. You can read more about this in the relevant part of the [Spec](https://github.com/compose-spec/compose-spec/blob/master/build.md#consistency-with-image).
> 
> In your case, you can change the name of your `image` attribute to something that doesn't exist (you can do `[myproject]/wordpress`, or something else) or you can set the `pull_policy` [attribute](https://github.com/compose-spec/compose-spec/blob/master/spec.md#pull_policy) to `build` to ensure Compose always BUILDS the image.

Thanks for the reply :)
But can you explain why its still fails when i run "docker-compose up -d wordpress"
`RUN chmod o+r /etc/resolv.conf && apt-get update && apt-get install libvirt-clients network-manager iputils-ping sudo nano rsync grsync wget nano -y bash:
#0 0.733 chmod: changing permissions of '/etc/resolv.conf': Read-only file system
failed to solve: process "/bin/sh -c chmod o+r /etc/resolv.conf && apt-get update && apt-get install libvirt-clients network-manager iputils-ping sudo nano rsync grsync wget nano -y bash" did not complete successfully: exit code: 1
`

This is permission issue?

but working when i run "docker build dockerfiles/wordpress/ -t wordpress:latest" everythings is executed without problem ...

**Comment by laurazard** [comment]
Are you asking why it still fails when you run `docker compose up` or `docker compose build`? Previously you said it only pulled the image with `up` and ignores your Dockerfile.

If you mean why it still fails with `build`, it might be a BuildKit issue (since Compose V2 uses the Buildkit builder by default). Try running `DOCKER_BUILDKIT=0 docker compose build` to build with the classic builder and check if the error still happens.

**Comment by kekec777** [comment]
Changing /etc/docker/daemon.json to:
 {
  "features": {"buildkit": true}
}

and runing DOCKER_BUILDKIT=0 docker build . seems did the trick :)
Thanks for all your help , really appreciated it ...
