### ISSUE TITLE
Docker Compose V2 & `DOCKER_HOST`

### ISSUE THREAD

**Issue by trcoelho** [docker/compose#10309]
### Description

With Compose V1 we have the ability to set a project-specific DOCKER_HOST in .env, with V2 this is no longer possible.

### Steps To Reproduce

1. Add an .env file with a custom value for DOCKER_HOST
2. docker compose commands target the default docker host

### Compose Version

```Text
Docker Compose version v2.15.1
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: SEG5:FGJP:7L4L:A7IF:FEI7:PEG7:S6NV:AJMR:AP2Y:XB4X:R5EI:TG4F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

As per https://docs.docker.com/compose/environment-variables/envvars/ looks like Docker Compose V2 should support DOCKER_HOST when its set on a .env file.

Also there is a issue opened regarding this subject https://github.com/docker/compose/issues/9210 and it looks that won`t be available on docker compose V2. If true how do we manage remote environments using docker compose V2?

Is there any available documentation regarding it?

Thank you.

**Comment by milas** [comment]
Compose v2 does not support setting `DOCKER_HOST` _within_ `.env` files, but the environment variable is still supported:
```shell
DOCKER_HOST=tcp://1.2.3.4:1234 docker compose up
```

You can also use [Docker contexts](https://docs.docker.com/engine/context/working-with-contexts/):
```shell
docker context use mycontext
docker compose up
```
OR
```shell
DOCKER_CONTEXT=mycontext docker compose up
```

Additionally, you can pass flags directly to the `docker` CLI:
```shell
docker --host=unix:///custom/docker.sock compose up
```
OR
```shell
docker --context=mycontext compose up
```

**Comment by trcoelho** [comment]
Noted! Thanks for explanation @milas !
So far we set DOCKER_HOST as environment variable using **export** for Linux **set** for Windows prompt or **$env** for Windows Powershell and works fine. We just need to take care to run Docker commands under an environment that we don't want to.

It would be nice do consider DOCKER_HOST on .env files for docker compose v2 😃 .

Anyways, thanks for explanation!

Best regards!
