### ISSUE TITLE
[BUG] `config` should not keep `extends` in output YAML

### ISSUE THREAD

**Issue by Vanav** [docker/compose#10305]
### Description

`docker compose config` follows `extends` and resolves them, but also keeps `extends` in resulting file, This looks like a bug, because `extends` are already expanded and are useless in resulting file.

Also, this breaks the Docker Swarm use case (https://github.com/moby/moby/issues/31101):
```
# docker compose config > swarm.yml
# docker stack deploy -c swarm.yml

Compose file contains unsupported options:

extends: Support for `extends` is not implemented yet.
```
This will work correctly in Compose v1, because it doesn't have this bug and in `swarm.yml` there will be no `extends`.

### Compose Version

```Text
Docker Compose version v2.16.0
```

### Docker Environment

```Text
Docker v23.0.1
```

**Comment by glours** [comment]
Hello @Vanav 

This is a swarm related bug which doesn't follow the Compose Specification and doesn't support the `extends` attribute
Please report swarm-related issues to docker/cli repository.

**Comment by Vanav** [comment]
Yes, it doesn't support `extends`. Good way to remove `extends` was to use `docker compose config`, and it works on v1. Why v2 keeps `extends` in output, after files are already included?

**Comment by Vanav** [comment]
For example, `docker compose config` doesn't leave `env_file` in resulting file, because it loads variables to config file. So, it shouldn't leave `extends` in resulting file too.
