### ISSUE TITLE
[BUG]  compose/compose/config/compose_spec.json is missing the bind option "create_host_path"

### ISSUE THREAD

**Issue by daberlin-sechub** [docker/compose#10323]
### Description

The spec file should contain the optional bind options "create_host_path" and "selinux" somewhere after line 408.

**Comment by daberlin-sechub** [comment]
See: https://docs.docker.com/compose/compose-file/#long-syntax-4

**Comment by ndeloof** [comment]
`bind` does support `create_host_path` and `selinux` as defined by https://github.com/compose-spec/compose-spec/blob/master/05-services.md#long-syntax-5

Or did I misunderstood the issue your reported ?

**Comment by daberlin-sechub** [comment]
Yep, it IS a supported feature. But the .spec-file does not specify it and thus validation of composefiles failes, even though those options are perfectly valid.

**Comment by laurazard** [comment]
Isn't it here? https://github.com/compose-spec/compose-spec/blob/b34d2b7cc23d8b0a6d54b35b17b8a85cce72150c/schema/compose-spec.json#L385

**Comment by daberlin-sechub** [comment]
That commit is from yesterday - so yes, that's probably the solution. I was just answering [ndeloof](https://github.com/ndeloof)'s question...

**Comment by ndeloof** [comment]
ok, "spec file" was ambiguous, didn't know if you refer to spec.md or the json schema

**Comment by ndeloof** [comment]
those attribute are well declared in schema (selinux was added [1 year ago](https://github.com/compose-spec/compose-spec/commit/ab58eae8d025606198f82e40efc1349cfc6996a8))
https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json#L385-L386

so I'm not sure I understand what this issue is about

**Comment by ndeloof** [comment]
I eventually understood you're referring to compose v1 branch https://github.com/docker/compose/blob/master/compose/config/compose_spec.json

Compose v1 is deprecated and didn't receive updates, and will be marked "End of Life" in a few week. If you still use v1 you should switch to v2 ASAP.
