### ISSUE TITLE
[BUG] Wrong relative path resolution for `env_file` when using `extends`

### ISSUE THREAD

**Issue by LEAFERx** [docker/compose#10326]
### Description

The relative path resolution for `env_file` under docker compose files that are being extended changed behavior in version `v2.16.0`.  In `v2.15.1` the relative path can correctly be resolved based on the file defining the `env_file`, however in `v2.16.0` it is resolved based on the compose file when running `docker compose up`. This breaks composability in extends.

## Reproduce 

```
. <path>
├── docker-compose.yml
├── envs
│   └── common.env
└── services
    └── service.yml
```
`service.yml`:
```
version: '3.8'

services:
  app:
    image: alpine
    env_file: ../envs/common.env
```

`docker-compose.yml`:
```
version: '3.8'

services:
  app:
    extends:
      file: ./services/service.yml
      service: app
```

`common.env`:
```
TEST=TEST
```

## Expected Behavior

In `v2.15.1`, command `docker compose run app sh` does not give any error, and run `echo $TEST` inside container gives correct result.

## Actual Behavior

In `v2.16.0`, it gives following error:
```
Failed to load /<path>/envs/common.env: open /<path>/envs/common.env: no such file or directory
```

### Compose Version

```Text
Docker Compose version v2.16.0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 9
  Running: 8
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-11-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.77GiB
 Name: sequencer-specular
 ID: 59afcfe8-028b-4d73-8513-8b575f160172
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
Relative paths are resolved based on project directory, not the file defining value. I'm not sure which change between 2.15 and 2.16 introduced this, but the behavior is correct (according to compose-spec). This indeed makes it harder to extend an existing compose file in a different folder, that's a known limitation. We miss some way to define a path as "relative to current file"

**Comment by LEAFERx** [comment]
As I'm reading the spec from main branch [here](https://github.com/compose-spec/compose-spec/blob/master/spec.md), the spec requires it to be resolved based on the compose file path.

> Relative path MUST be resolved from the Compose file's parent folder. As absolute paths prevent the Compose file from being portable, Compose implementations SHOULD warn users when such a path is used to set env_file.

Am I misunderstanding this or looking at the wrong spec? Thanks!

**Comment by ndeloof** [comment]
spec is a bit unclear indeed. "project directory" is by default the Compose file's parent folder - Docker Compose allows to override with a custom path, but this is the default. All relative paths in compose file and overrides, extended, etc are computed based on this project directory. Those paths are resolved AFTER the compose files get combined into a single model
