### ISSUE TITLE
Too Many docker build running at the same time causing the build never done

### ISSUE THREAD

**Issue by xenyo-tommy** [docker/compose#10332]
### Description

I have docker compose containing multiple services. Each of service need to be build and each of them have multiple build target.
When I run docker compose up for the first time and have no cache, it build all image and the same times and the build job can never be done or exit from error.
Hope there is a way to control how many paraelle image can be build at the same time when docker compose up.

**Comment by ndeloof** [comment]
you can use `docker compose --parallel=xx build` to limit the number of concurrent builds.

**Comment by xenyo-tommy** [comment]
> you can use `docker compose --parallel=xx build` to limit the number of concurrent builds.

unknown flag: --paralle

Think it is a deprecated flags.

**Comment by ndeloof** [comment]
```
$ docker compose -h
Usage:  docker compose [OPTIONS] COMMAND

Docker Compose

Options:
...
      --parallel int               Control max parallelism, -1 for unlimited (default -1)
```

the legacy `--parallel` (boolean flag) from compose v1 is indeed deprecated, but had a distinct purpose

**Comment by xenyo-tommy** [comment]
My docker compose version is v2.6.1. Didn't have this flag.

**Comment by ndeloof** [comment]
This was introduced in 2.14.1, latest is 2.16 - you should upgrade :)
