### ISSUE TITLE
Make "docker compose up" work with files named "whatever-docker-compose.yml"

### ISSUE THREAD

**Issue by DoTheEvo** [docker/compose#10346]
### Description

If there is only one file fitting the pattern of `*-docker-compose.yml` it would run it.
If there would be more it would complain.
This would make seeing 5 docker-compose.yml in a text editor, not knowing which is which not an issue anymore. Or seeing a file in a file manager and straight up knowing without eyes needing to go looking for directory name.

**The format might be even cleaner with just `whatever-compose.yml`**

Probably theres some danger to this, or some issue I dont see, but felt like idea is worth considering.

And yes,  I know I can run any file with -f flag, but it is kinda bothersome and muscle memory says no...

**Comment by DoTheEvo** [comment]
>compose.yaml.

Well, the [official tutorial](https://docs.docker.com/compose/gettingstarted/#step-2-create-a-dockerfile) and I think every single one I encountered went with `docker-compose.yml`. But interesting, tested it and it works.

>What's your reason to use foo-bar-docker-compose.yml if this is not for override reasons ?

Well ideally it would be just foobar-compose.yml, but I would gladly take the long form too, and the reason would be **to easily distinguish between docker-compose files.**

Be it in file search results, be it in text editors, file managers, file picker in browsers..  just seeing the name right away because I was allowed to name the file descriptively enough.

The only reason we name them docker-compose.yml is because all tutorials tell us to do so, and they tell to do so because `docker compose up -d` works only with specifically named files. And we people are lazy, we dont bother with file flag when writing tutorials/guides, or in actual use... cycling through history in few key presses to find up/down is just faster, easier..

But maybe its just my weird workflow where `locate docker-compose.yml | wc` spits out 57, and most people name compose files nicely and actually use the -f

**Comment by ndeloof** [comment]
Extending selection of the default compose file with support for environment variables/sub folders has been a source for many regression, so we are very reluctant to add more for a minimal benefit. Compose `-f` option is the right way to run with a non-default compose file.
