### ISSUE TITLE
allow custom more options for `tmpfs` under `volumes` long syntax, such as allow `exec`

### ISSUE THREAD

**Issue by hzqmwne** [docker/compose#10347]
### Description

Ref to https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-5 , currently `tmpfs` type under `volumes` syntax only has two options `size` and `mode`, and the tmpfs is force mounted as `nodev,nosuid,noexec` in container.

However, in some situations that need `exec,dev,suid` tmpfs, there is no way to control these options.
Although the [`tmpfs`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#tmpfs ) syntax allows do this, it is invalid in docker **swarm** mode. So it is quite necessary to allow custom mount options (include by not limited to: `tmpfs`,`volume`,`bind`,`npipe` with `(no)exec`, `(no)suid`, `(no)dev`) under `volumes` long syntax, especially for swarm.

There is an old issue #5907 which also mentions this problem. but have not been solved yet.

**Comment by ndeloof** [comment]
Changes to the compose specification should be first discussed on https://github.com/compose-spec/compose-spec, feel free to open an issue there
I wonder the docker engine let us set `(no)exec` and others while creating a tmpfs volume ?

**Comment by hzqmwne** [comment]
Ref to https://docs.docker.com/storage/tmpfs/ , docker engine provides two options for mounting tmpfs, `--tmpfs` and `--mount`.

I can use `docker run --tmpfs /tmp:exec,dev,suid --rm -it ubuntu:22.04` to get tmpfs mounted as `exec` (although the document says "The `--tmpfs` flag does not allow you to specify any configurable options"), but it is **invaild** in `swarm` mode.  
For `swarm` docker service or docker stack, the only choice is to use `--mount`, like `docker service create --mount 'type=tmpfs,dst=/tmp' ubuntu:22.04`, however, it only supports `readonly`, `tmpfs-size`, `tmpfs-mode`(only for file mode in oct number) and cannot custom options list `(no)exec`.

So, it seems the docker engine does **not** let us set `(no)exec` and others while creating a tmpfs volume under **swarm**. 

There is an issue in docker engine project https://github.com/moby/moby/issues/32131 , but sadly it is still in open since 2017 .
 
For compose spec, it is suggested to provide an option like `volume-opt` (e.g. `tmpfs-opt` ) under `mount` with `type: tmpfs`, to support **any** custom mount options, include `(no)exec, (no)suid, (no)dev``

**Comment by ndeloof** [comment]
We only can expose options that are implemented by docker engine. I'm closing this issue as "not planned" as there's no pending fix n moby. Obvioulsy, if/once engine has support for more options, we will adopt them on compose side
