### ISSUE TITLE
Do you have any documentation about downtime during `fig up`?

### ISSUE THREAD

**Issue by bitliner** [docker/compose#1035]
I want to use fig.sh on production servers.

Do you have any more information about downtime?
Does `fig up` have a builtin mechanism to avoid downtime?

**Comment by aanand** [comment]
First off: Fig is now Compose, and we don't yet recommend using it in production.

To answer your question, Compose has no built-in mechanisms for avoiding downtime. We plan to recommend a technique for zero-downtime deploys in future.

**Comment by munhitsu** [comment]
@aanand do you have any draft?
After having enough of running docker from a command line / from saltstack dockerio module, the current state of docker-composer makes me more than happy to use it for production.

What instantly brings a question on how to workaround "up" restarting containers when it's not needed? I am quite ok to hack something wrapping docker-composer or to extend docker-composer. Would you have any recommendation / what is your vision around using docker-composer in production?

Simple requirement: `docker-composer up -d` restarting container only on image version change
Medium: `docker-composer up -d` restarting container only on configuration change
Advanced: using `docker-composer scale` to scaling up and later down to perform smooth upgrade on version change

In fact a small switch "for scale down" to scale down starting from old (low suffix number) containers would solve the problem nicely.

Anyway - would be awesome to have a word on advice/guidance from you guys.

**Comment by dnephin** [comment]
There are a bunch of related tickets about deployment and production use. I've linked them all up to #1786. I'm going to close this issue so we can concentrate the discussion in that ticket.
