### ISSUE TITLE
[BUG] `restart: on-failure` fails to achieve the holy grail of don't-restart-on-reboot

### ISSUE THREAD

**Issue by rulatir** [docker/compose#10363]
### Description

I want some services to NEVER EVER be automatically restarted when I boot my computer, regardless of whether they were running at the exact moment I issued the shutdown command in my desktop environment or not. HOWEVER I still want them to restart if I started them explicitly and they fail for some reason. In other words, I want the intention "shut down the host machine and don't turn it on again until I press the power button" to automatically imply the intention "shut down all containerized services running on the machine and don't start them again until I tell you".

I understand that `restart: on-failure` is _supposed to_ achieve me exactly this, per service.

Well, it doesn't.

The services with `restart: on-failure` in `docker-compose.yml` still keep auto-restarting after reboot. I use socket activation, so they don't actually start _right_ after reboot, but whenever I issue any docker command that causes the daemon to start via socket activation, _first_ those services get restarted, and _only then_ the command I gave is even considered - which is often a command to bring up _another_ compose with services that use the same ports as the just-restarted services, causing errors.

### Steps To Reproduce

Full steps to reproduce would be rather complicated here due to several factors:

 - the scenario involves a full reboot of the host machine
 - I use the docker socket, so the symptom (i.e. the services running after reboot when I don't want them to) won't actually manifest until I do _something_ with docker, at which point the daemon will be started via the socket and will proceed to automatically restart services before even considering the actual command I issued
 

### Compose Version

```Text
Docker Compose version v2.2.3
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.10.3
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.2.3
    Path:     [REDACTED]

Server:
 Containers: 149
  Running: 10
  Paused: 0
  Stopped: 139
 Images: 550
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: f2fs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.2-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.22GiB
 Name: berbelek
 ID: [OPAQUE STRING REDACTED]
 Docker Root Dir: /mnt/fastpool/var/lib/docker
 Debug Mode: true
  File Descriptors: 98
  Goroutines: 92
  System Time: 2023-03-10T15:15:15.671262939+01:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

I have verified using `docker inspect` that the containers in question are really running with `on-failure` restart policy.

**Comment by ndeloof** [comment]
`restart: on-failure` is not managed by compose but by docker engine, see https://docs.docker.com/config/containers/start-containers-automatically/
