### ISSUE TITLE
[BUG] Jumps in Docker Build

### ISSUE THREAD

**Issue by ArsamAryandoust** [docker/compose#10365]
### Description

I have some docker container running on my machine with the following Dockerfile:
```
FROM ubuntu:latest

ENV https_proxy http://proxy.ethz.ch:3128/
ENV http_proxy http://proxy.ethz.ch:3128/

RUN apt-get update && apt-get upgrade -y
RUN apt-get install python3-pip -y

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

WORKDIR /EnergyTransitionTasks
```

Then, I create a new, similar docker file with:
```
FROM ubuntu:latest

ENV https_proxy http://proxy.ethz.ch:3128/
ENV http_proxy http://proxy.ethz.ch:3128/

RUN apt-get update && apt-get upgrade -y
RUN apt-get install python3-pip -y

RUN pip3 install py-experimenter
```

When building the new container from the latter file, everything is okay. Then, when running the new container, I suddenly see the file requirements.txt and start in the working directory EnergyTransition task, which are things only set in the similar, first container. 

If this isn't wanted and not a usage mistake on my side, I can easily see it having security issues for users on public servers.

**Comment by ndeloof** [comment]
Does this relate to docker compose ?

**Comment by ArsamAryandoust** [comment]
not specific docker compose, where should I had put this instead?

**Comment by ndeloof** [comment]
Better ask on community forum https://www.docker.com/community/ or open an issue on docker/cli for confirmed bugs
