### ISSUE TITLE
Provide com.docker.compose.* labels as annotations in the container configuration

### ISSUE THREAD

**Issue by tpreclik** [docker/compose#10389]
### Description

Docker-compose labels service containers with labels such as `com.docker.compose.project.working_dir` and `com.docker.compose.project.config_files`. Since this is happening after the containers are created the information cannot be used in docker container runtimes to e.g. locate the original docker-compose manifest and determine the service name of the container being created. The container configuration `config.json` contains no traces of such information. Use cases such as evaluating extension fields given in the compose manifest are not possible.

One potential solution would be to provide the `com.docker.compose.*` labels as annotations in the container configuration [[1]](https://github.com/opencontainers/runtime-spec/blob/main/config.md#annotations). I would like to collect some early feedback before heading in the wrong direction. What are your thoughts on this? Would it make sense to address this in a more general approach in the moby project (providing all labels as annotations) or is that something that could be implement from within compose?

[1] https://github.com/opencontainers/runtime-spec/blob/main/config.md#annotations

**Comment by laurazard** [comment]
Hiya @tpreclik, thanks for the question/suggestion.

I'm a bit curious, right now we're adding these labels just for our own (Compose's) use for managing containers created by Compose (determining where they're defined, if they need to be rebuilt, etc.), but we're not expecting that anyone else will use them. What use did you have in mind for them inside the container runtime? You mention locating the original Compose file and determining the service name, and also evaluating extension fields, but no specific end goal. What would you like to use that information for?

**Comment by ndeloof** [comment]
`com.docker.compose.project.working_dir` and `com.docker.compose.project.config_files` are legacy labels used in earlier version of Docker Desktop to interact with a running compose application. AFAICT Desktop has been updated so it now relies on `--project-name` for equivalent commands (@glours could confirm) and we _could_ remove those labels. They're not a safe way to track the compose model used to create an application, as file might have been updated in between, or some services and profiles could have been enabled by command line.

> determine the service name of the container being created

Isn't this just `com.docker.compose.service` ?
Clarification on your goal would help us offer guidance on best technical approach

**Comment by ndeloof** [comment]
> Docker-compose labels service containers with labels such as com.docker.compose.project.working_dir and com.docker.compose.project.config_files. Since this is happening after the containers are created the information cannot be used in docker container runtimes

Can you please elaborate ? Labels are fully part of the container config, those aren't set _after_  container are created.
Again, clarification on your goal would help us offer guidance on best technical approach. Please give us more details

**Comment by tpreclik** [comment]
> They're not a safe way to track the compose model used to create an application, as file might have been updated in between, or some services and profiles could have been enabled by command line.
I agree.

> Isn't this just com.docker.compose.service ?
Yes. But don't have access to docker labels in the create step of the container runtime.

> Clarification on your goal would help us offer guidance on best technical approach

We would like to map additional resources into our containers by using a runc shim as a custom docker container runtime similar to Nvidia's initial approach for mapping their gpus into containers. We would like to obtain additional information about which resources to map into the container from an extension field in the app manifest. We know of no clean way to get access to the information from extension fields from within a docker container runtime. We could evaluate environment variables specified in the `docker-compose.yml` as Nvidia did it since those end up in the container configuration (`config.json`) but they are not expressive enough for us. In the container runtime we know the containerid for which runc will create a container. We also e.g. have access to the container configuration (`config.json`) but obtaining access to extension fields is clumsy. Docker inspect e.g. at that point in time (runc create step) is not yet returning information for the container that is about to be created. So we know nothing about the container's labels.

**Comment by ndeloof** [comment]
Seems to me the original issue is about getting runtime API to bring required metadata to the container runtime, and what's requested here is just a workaround. Would be better to get this debated with the runtime maintainers.
I'm closing this issue as "not planned"
