### ISSUE TITLE
[BUG] Docker installed on mac via Docker.app does not obey --no-cache option

### ISSUE THREAD

**Issue by brr53** [docker/compose#10398]
### Description

Docker installed on mac via Docker.app does not obey --no-cache option

Another issue was made for many months now with no visibility.
https://github.com/docker/compose/issues/8285

### Steps To Reproduce

docker build with --no-cache option. It will display cache.
example: docker build --no-cache --platform linux/amd64 -t testing .  

### Anything else?

Please fix this for mac users.

**Comment by ndeloof** [comment]
If you can reproduce this with a plain `docker build ..` command, then this is not related to Docker Compose.
I'm transferring this issue to a more relevant repository
