### ISSUE TITLE
Add wait command to docker compose

### ISSUE THREAD

**Issue by chmely** [docker/compose#10395]
### Description

It would be nice to be able to start compose in detached mode and then be able to wait for a specific service(s) to finish, similar to what `docker wait` does.

Something like `docker compose [params] wait service [service] [--timeout xx]`
Return code - 0 if all awaited services completed successfully within the required time frame, error code otherwise

Why this could be useful?

We use compose in our CI pipeline where we want to start certain containers like LocalStack, Vault, etc. Then we have seeder containers that run as part of the compose and seed values or initialize infrastructure inside LocalStack.
After the seeding/initialization is done we run our integrations tests. But before we can run our integration tests we have to make sure the seeder containers have finished successfully.

So in our case it'd be great if we could do something like
```
docker compose [params] --profile infrastructure --profile localstack-seeder --profile vault-seeder up -d
docker compose [params] --profile infrastructure --profile localstack-seeder --profile vault-seeder wait localstack-seeder vault-seeder --timeout 60s

run integration tests here if $? is 0
```

**Comment by kamilpi** [comment]
It could be useful for some scenarios.

You could always do the filter based on labels generated by ```docker compose``` service.

```
docker wait $(docker ps --filter label=com.docker.compose.service=foo -q)
```

**Comment by chmely** [comment]
Yes, this is certainly one way, but not that intuitive, I didn't know that you could do it this way, so thanks for the tip, but I assume other people may also not know, so a wait command may be handy and more intuitive to use

**Comment by ndeloof** [comment]
This is already available using `docker compose up --exit-code-from SERVICE`. Compose will wait for specified service to exit, then stop the stack and report exit code

**Comment by chmely** [comment]
Well, but the documentation for `--exit-code-from` [says](https://docs.docker.com/engine/reference/commandline/compose_up/#options) that using it also implies `--abort-on-container-exit`, so in my scenario above it would not work well if waiting for multiple services to finish, as it would abort on the first of the multiple containers/services running. Also, there is no timeout option.

**Comment by chmely** [comment]
Hi guys, any update on this?

**Comment by chmely** [comment]
Hi guys, thanks for looking into this.
However, I am not sure the implementation is doing what I proposed.

It seems that `docker compose wait` waits for the first of any of the services to complete, what I proposed was something similar to what `docker container wait` does, to wait for one or more containers, in compose case one or more services.
