### ISSUE TITLE
[BUG] eror with projectname

### ISSUE THREAD

**Issue by pvklink** [docker/compose#10426]
### Description

I get an error with docker-compose with projectnamens like KAST_nodered etc.

### Steps To Reproduce

choose a projectname like KAST in a env file
COMPOSE_PROJECT_NAME=KAST

### Compose Version

```Text
v 17.2 on latest raspberry pi os (bullseye)
```

### Docker Environment

```Text
latest version of latest bullseye
```

**Comment by ndeloof** [comment]
please describe the error you encounter.

**Comment by ndeloof** [comment]
is this that compose reject configured compose project name ? 
project name MUST be lowercase, setting `COMPOSE_PROJECT_NAME=KAST` makes it invalid

**Comment by pvklink** [comment]
Yes, i decribed the projectname in capitals.... In earlier versions capitals were allowed....
Changing to lowercase is the solution...
Question is if lowercase projectname is a conscious choise or a conqequence of a new version...

**Comment by ndeloof** [comment]
earlier version used to mutate the configured project name to make it compliant, but doing so had this weird effect that compose didn't applied the expected name, which some could consider a bug - while others would suggest is a feature 😅.
Anyway, we preferred the "lowest surprise" approach
