### ISSUE TITLE
[BUG] transferring context is very long once in two times

### ISSUE THREAD

**Issue by EParisot** [docker/compose#10445]
### Description

Hi ! 
I notice Docker compose build command will take more than 10 min to transfer < 1Mo context...
If I cancel (CTRL + C) and simply re-run, then it take like 10 min to transfer 1Go of context...

This is not blocking in any way but very anoying... I sometimes just run the command then notice it did 1Mo transfer after more than 10 min... I then re run it and it goes fine...

### Steps To Reproduce

docker-compose -f docker-compose.yml build

### Compose Version

```Text
Docker Compose version v2.15.1
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false  
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.3)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.18)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.6.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.71GiB
 Name: docker-desktop
 ID: FGFI:XUM3:ECL6:FSSU:EA47:C6CF:TYPR:DNQV:DXKE:CO7T:N3HC:4QCQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by milas** [comment]
Can you try updating to the latest Docker Desktop (4.18.0)? Click "Check for Updates" in the Docker Desktop settings if it hasn't shown up automatically yet.

It's got a bunch of networking fixes that will likely resolve this

**Comment by EParisot** [comment]
Hi milas, thanks you are right my docker desktop was outdated, I did the update but it seems like this problem is still there, the first run I tried took 2 min to transfer 3Kb context..., I wonder if it is tied to my config or something else...

**Comment by EParisot** [comment]
The issue is still present in Docker desktop v4.27.1...

**Comment by ndeloof** [comment]
Can you please confirm this issue can't be reproduced by a plain `docker buildx build` or `docker buildx bake` command ?

**Comment by EParisot** [comment]
I'll have to test next week, I'm off this times... I'll update here later.
Thanks

**Comment by EParisot** [comment]
After a test, the issue is still there : 

docker buildx build -f Dockerfile .

![Image](https://github.com/user-attachments/assets/cdecccf4-2510-45bd-8ad7-c5c334af0fc5)

as you can see, the context transfer only sent some Kbytes, it goes very slowly (several minutes to transfer very few data).

If I stop and run again, without any change, few seconds later, some Mbytes have been transfered.

docker version :
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:14:20 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop  ()
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by ndeloof** [comment]
If issue can be reproduced with a plain `docker buildx build` command, then should be reported on https://github.com/docker/buildx, which compose relies on for build implementation
