### ISSUE TITLE
[ISSUE] Rich formatting does not work

### ISSUE THREAD

**Issue by FanaticExplorer** [docker/compose#10446]
### Description

I'm making a bot in Python and I added some pretty output using `rich` library. This formatting works if I start my file separately (`python bot.py`), however, when I add it to a docker-compose, the only formatted text is the name of docker in the left.
That is how it looks normally (launching file with python)

![WindowsTerminal_RQ7v5MhCVl](https://user-images.githubusercontent.com/52747818/230479685-36e388ae-1c70-479c-a422-dd9268d9eb4e.png)

And how it looks in docker-compose
![WindowsTerminal_0CJP9Cxots](https://user-images.githubusercontent.com/52747818/230479398-7480a41c-5ca0-4972-a4f7-fb9a27175ccd.png)
Rich status not working, too

### Steps To Reproduce

1. Make a python file using any of `rich` features
2. Use this Dockerfile:
```
FROM python:3.11
RUN pip install rich
ENTRYPOINT ["python", "file_with_rich.py"]
```
3. Add this Dockerfile in docker-compose and run

### Compose Version

```Text
Docker Compose version v2.15.1
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.3)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.18)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.6.0)

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 16
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.801GiB
 Name: docker-desktop
 ID: CFSP:RMBY:LVER:VKCM:XWNX:HK6Y:64PY:NCTQ:3RQS:KBP5:K7PZ:NHD3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Rich library - https://github.com/Textualize/rich

**Comment by nicks** [comment]
Usually, terminal color frameworks switch into plain text mode when they're not attached to a tty. Here's a doc on this: https://github.com/Textualize/rich/blob/master/docs/source/console.rst#terminal-detection

You can also set tty: true in your compose file to attach a tty: https://docs.docker.com/compose/compose-file/05-services/#tty

**Comment by FanaticExplorer** [comment]
> Usually, terminal color frameworks switch into plain text mode when they're not attached to a tty. Here's a doc on this: https://github.com/Textualize/rich/blob/master/docs/source/console.rst#terminal-detection
> 
> You can also set tty: true in your compose file to attach a tty: https://docs.docker.com/compose/compose-file/05-services/#tty

It worked, thanks! It would be pleasure if that was on default.
The issue is solved for me and I will close it.
