### ISSUE TITLE
Add quiet or mute_output option for only certain containers in docker-compose.yml

### ISSUE THREAD

**Issue by FanaticExplorer** [docker/compose#10452]
### Description

I would like to request the ability to mute certain containers in the output. 
For example, I might have a container called `useful_out` that I want to see output from, but another container called `spam_out` that I don't want to see any output from.

Ideally, this feature would be implemented as a new option in the docker-compose.yml file, something like “mute_output” or “quiet”. I imagine it could be as simple as adding a flag to the container definition like this:

```yaml
services:
  useful_out:
    image: useful_image
    ...
  spam_out:
    image: spam_image
    ...
    mute_output: true
```
With this option set, any output from the “spam_out” container would be suppressed in the console output.

I think this feature would be useful for applications with third-party containers, where the console output can become kind of overwhelming.

**Comment by ndeloof** [comment]
You can run `docker compose up --no-attach spam_out` to exclude output of a specific container and keep focus on the one(s) which are important for your needs.

**Comment by FanaticExplorer** [comment]
> You can run `docker compose up --no-attach spam_out` to exclude output of a specific container and keep focus on the one(s) which are important for your needs.

Thanks! However, it would be great if it was an option in .yml

**Comment by rbonatuvic** [comment]
In docker-compose this was implemented with:

    logging:
      driver: none

This makes it much easier to turn on and off logging for various containers.

**Comment by ndeloof** [comment]
> In docker-compose this was implemented ...

Actually not. This disabled logs collection by docker engine, and Docker Compose v1 relied on the logging API to get output (not the attach API, also used by `docker run`).

You can set the equivalent:
```yaml
services:
  muted:
    attach: false
```

**Comment by rbonatuvic** [comment]
Thank you @ndeloof 
that is what I was looking for.
