### ISSUE TITLE
[BUG] Container name changes on recreation using "compose up"

### ISSUE THREAD

**Issue by mrclschstr** [docker/compose#10460]
### Description

I switched from the old `docker-compose` to the new `docker compose` plugin some weeks ago. I noticed a strange behaviour with the container names during updates (recreation) of containers. My workflow with the old `docker-compose` was like this:

1. I had a `docker-compose.yml` with a service using the image `nginx:1.23`, for example
2. To update the service, I changed the image tag to `nginx:1.24`
3. `docker-compose pull`
4. `docker-compose up -d`

Using `docker-compose up -d` the container was recreated with the old name, for example `test-web-1`. Unfortunately, the new `docker compose up -d` changes the container name and prefixes it, for example `249662c60a09_test-web-1`. I have some workflows relying on predictable container names, so this is quite unfortunate.

Is this a bug or a feature?

**My current workaround:** `docker compose down && docker compose up -d`

### Steps To Reproduce

1. Create `docker-compose.yml` with the following content:
```yaml
version: "2"
services:
  web:
    image: nginx:1.23
```
2. `docker compose pull`
3. `docker compose up -d` and check the container name (for example: `test-web-1`)
4. Change image tag to `nginx:1.24` in `docker-compose.yml`
5. `docker compose pull`
6. `docker compose up -d` and check the container name again (for example: `249662c60a09_test-web-1`)

### Compose Version

```Text
docker compose: Docker Compose version v2.17.2
docker-compose: Not installed
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 20
  Running: 20
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-69-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.763GiB
 Name: servername
 ID: TCFV:HNXG:EZL4:VXTL:U3S7:RORV:45HE:EDR5:PJFI:PGAQ:JKYZ:5MRC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by milas** [comment]
I am not able to reproduce this with the Compose file you provided on either macOS w/ Docker Desktop 4.18 or Ubuntu 22.04 w/ Engine 23.0.3 and Compose v2.17.2 in both cases. 🤔

**Comment by mrclschstr** [comment]
I repeated my tests and I finally found the issue. It tracked down to a display error of the tool [ctop](https://github.com/bcicen/ctop), which I'm using to manage and monitor containers on the console. I think I'll switch to [lazydocker](https://github.com/jesseduffield/lazydocker) for now...

Sorry for the confusion! 🥲

**Comment by milas** [comment]
No problem, I'm glad you figured it out!

**Comment by ad8lmondy** [comment]
Just as an FYI for anyone who experiences this in the future, I just experienced this.

I was going from `community.docker.docker_compose` to `community.docker.docker_compose_v2`, and when Ansible got to the `docker_compose_v2` task, it marked it as needing a change.

No big deal, it just restarts the container. However, it seems like it starts the new one before killing the old one - so if you have a name specified, like `traefik`, it can't use that, since a container already has it, so it prefixes the container with the container ID, like `b3383b84b0b0_traefik`.

However, now there is no naming conflict, because the original `traefik` container has gone away. So `docker compose down && docker compose up -d` (or the Ansible equivalent) gets you back to your normal container names.
