### ISSUE TITLE
You may press Ctrl+C now to abort this script

### ISSUE THREAD

**Issue by rola0411** [docker/compose#10469]
### Description

```
# Executing docker install script, commit: a8a6b338bdfedd7ddefb96fe3e7fe7d4036d945a
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20

```

### Compose Version

```Text
v2.17.2
```

### Docker Environment

```Text
23.0.3
```

**Comment by GrinZero** [comment]
same

**Comment by thaJeztah** [comment]
I don't think this is related to Docker Compose, and not a bug. This warning comes from the install script at get.docker.com (maintained in https://github.com/docker/docker-install), and this warning is purposefully there, because running the install script on a machine that already has docker installed (which could be through other means than docker's package repository) may change configuration of those installs and/or switch to using different package repositories. So the script warns about that before continuing so that you can cancel the script and review its steps.


Closing this ticket because of the above, but feel free to continue the conversation if there's more info needed

**Comment by rola0411** [comment]
1：I installed docker，
2：I install docker-compose，
3：docker-compose -v 
```
# Executing docker install script, commit: a8a6b338bdfedd7ddefb96fe3e7fe7d4036d945a
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20

```
when I use the docker-compose command： docker-compose -v or  docker-compose up -d
it output thems， And it will install docker agin 20s later。。。and when I use the command ：docker-compose -v
it output thems agin， 。。。the operation  in circles.
My English is not good, can you understand?

**Comment by rola0411** [comment]
How should I install

**Comment by GrinZero** [comment]
> How should I install

直说了，你不要安装镜像源，下载GitHub官网的。并且要求docker和docker-compose版本对应

**Comment by 4JinHang** [comment]
I have uninstalled my docker and run docker-compose --version again, but it stil have the same problem when I run it secondly.

**Comment by 4JinHang** [comment]
> > 我应该如何安装
> 
> 直说了，你不要安装镜像源，下载GitHub官网的。并且要求docker和docker-compose版本对应

我直接在github上下载的，还把自己的docker卸载了，运行`docker-compose --version`之后，他给我安装了`docker23.0.5`的版本，但是当我再次运行`docker-compose --version`时，他仍然产生了相同的问题。

**Comment by 4JinHang** [comment]
访问这个地址进行下载：[https://github.com/docker/compose/releases](https://github.com/docker/compose/releases/)

**Comment by Orange-blue-yellow** [comment]
> > How should I install
> 
> 直说了，你不要安装镜像源，下载GitHub官网的。并且要求docker和docker-compose版本对应

Hey, bro! 我也遇到了同样的问题。接着楼主的问题补充：如果下载github源的就会出现新的问题：443拒绝访问，如果执行curl -L https://get.daocloud.io/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose 就会遇到楼主的问题：sleep 20。

于是我从主机的github官网下载对应版本压缩包再上传到centos，看上去是可行的，但是整个虚拟机都会非常卡，包括访问nacos和navicat，我不知道两者是否有关联，当我使用虚拟机快照回退到没有安装docker-compose之前就不会卡顿。你有好的主意吗？

**Comment by Orange-blue-yellow** [comment]
谢谢你特地回复我！问题解决了。应该是版本不匹配的问题，默认下载的docker全是23.0.5，无法与1.29.2的docker-compose对应。443不管什么网络我这边都不行，怀疑是被qiang 了。我会试试改hosts文件的方式。最后下的20.10.22版本的docker。至于虚拟机，确实是内存不够用。



---Original---
From: ***@***.***&gt;
Date: Thu, May 4, 2023 10:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [docker/compose] You may press Ctrl+C now to abort this script(Issue #10469)




    
我应该如何安装
  
直说了，你不要安装镜像源，下载GitHub官网的。并且要求docker和docker-compose版本对应
  
嘿，兄弟！我也遇到了同样的问题。接着楼主的问题补充：如果下载github源的就会出现新的问题：443拒绝访问，如果执行curl -L https://get.daocloud.io/docker/compose/releases/download/1.29.2/docker-compose-'uname -suname -m' &gt; /usr/local/bin/docker-compose chmod +x /usr/local/bin/docker-compose 就会遇到楼主的问题：sleep 20。-
 
于是我从主机的github官网下载对应版本压缩包再上传到centos，看上去是可行的，但是整个虚拟机都会非常卡，包括访问nacos和navicat，我不知道两者是否有关联，当我使用虚拟机快照回退到没有安装docker-compose之前就不会卡顿。你有好的主意吗？
 下载443是网络的问题，你可以通过修改hosts进行访问，官网下载的docker-compose文件是有sleep 20的问题，但是github下载的是没有的。虚拟机卡的问题不清楚，可能是你的虚拟机的处理器瓶颈。
