### ISSUE TITLE
Failed to destroy btrfs snapshot: operation not permitted

### ISSUE THREAD

**Issue by MrMMorris** [docker/compose#1046]
I am running docker-compose up and rm as part of a CI build and it gives me these errors:

`Error removing intermediate container 4f41a29459bf: Driver btrfs failed to remove root filesystem 4f41a29459bf3514e459addfb3e25d706ff6f8a85c59070bfdafe9617ffef3f2: Failed to destroy btrfs snapshot: operation not permitted`

and 
`Cannot destroy container 93110f1e7f807bea6a2d73b4bd2b4f6bde8817a0c99e7fd8d2465d6d6e1b6047: Driver btrfs failed to remove root filesystem 93110f1e7f807bea6a2d73b4bd2b4f6bde8817a0c99e7fd8d2465d6d6e1b6047: Failed to destroy btrfs snapshot: operation not permitted`

I tried running as sudo but no dice. Any ideas?

**Comment by thaJeztah** [comment]
Related to https://github.com/docker/docker/issues/9939?  Not sure, output is different ('operation not permitted')

**Comment by MrMMorris** [comment]
@thaJeztah actually, I think this is a CircleCI specific issue as they don't give permissions to delete containers. I am running into a different bug though if you want to comment:

```
docker push company/tv-client:dev-latest
The push refers to a repository [company/tv-client] (len: 1)
FATA[0000] no such id: company/tv-client   
```

Might be related to https://github.com/docker/docker/issues/4914

I tried removing the cache directory for CircleCI, but that didn't help. I might have to wait until they allow for destroying of containers to debug...

**Comment by thaJeztah** [comment]
Ahm thanks for the extra info, looks like this cannot be solved by docker-compose then.

Not sure about the other issue; I take "company" is a fictitious name? Perhaps you should search the docker issue tracker for that (I haven't yet). Also, do you have a `:latest` tag for that repo? I think I have seen some issues if no `:latest` tag existed, but again, not sure.

**Comment by MrMMorris** [comment]
@thaJeztah yea I will just comment in the docker issue. Thanks!

**Comment by thaJeztah** [comment]
@MrMMorris or at CircleCI; as you mentioned, it could be an issue with their setup

**Comment by MrMMorris** [comment]
yea they don't yet allow for container/image destruction so that's a problem in of itself

**Comment by thenikso** [comment]
had this problem as well. if you have a `docker run --rm ...` in CircleCI you will get this error. remove the `--rm` and everything should be fine.
