### ISSUE TITLE
[BUG] error message contains a litteral "%s"

### ISSUE THREAD

**Issue by lovasoa** [docker/compose#10476]
### Description

When running docker compose pull and some images need to be built, the error message says

```
 WARNING: Some service image(s) must be built from source by running:
    docker compose build %s image_a image_b image_c
```

The `%s` shouldn't be present. It comes from 

https://github.com/docker/compose/blob/65fda188217d15a349b77c5bf1dbeea20d2699c6/pkg/compose/pull.go#L142

### Steps To Reproduce

Run docker compose pull without required images

**Comment by AKARSHITJOSHI** [comment]
Hi @lovasoa I would like to contribute on this .

**Comment by lovasoa** [comment]
I am not from the docker project, but I guess you can just remove the `%s` from the line of code I mentioned above

**Comment by ndeloof** [comment]
`TailMsgf` is expected to format message with arguments, issue here is with implementation not usage
