### ISSUE TITLE
Pulling images from HTTP private registry endpoint fails

### ISSUE THREAD

**Issue by sourav82** [docker/compose#1047]
I've private docker registry hosted on a HTTP endpoint. While trying to pull image from the registry, it gives below errors -

docker.errors.DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled

Is there any way to specify insecure registry for docker-compose? 

I've set --isecure-registry in docker conf and docker CLI works well with the registry URL.

**Comment by aanand** [comment]
What `docker-compose` command are you running?

**Comment by sourav82** [comment]
Sorry, there was an issue at docker-registry deployment. It is solved now. Thanks for reply. Regret the inconvenience.
