### ISSUE TITLE
[BUG] "provided file is not a console" when running via Python subprocess

### ISSUE THREAD

**Issue by sueskind** [docker/compose#10487]
### Description

I want to use a Python script to start/stop docker-compose. In #10439 (v2.17.3+) the `--ansi always` option was fixed for this use-case. However, when using v2.17.3 it is not possible to run docker-compose this way altogether. Instead I get an error message `provided file is not a console`, but the exit code is 0. No service is started.

### Steps To Reproduce

docker-compose.yml:

```yaml
version: "3.8"

services:
  nginx:
    image: nginx
```

main.py:

```python
from subprocess import Popen, PIPE, STDOUT

args = ["docker-compose", "--ansi", "always", "up", "-d"]

with Popen(args, stdout=PIPE, stderr=STDOUT) as process:
    for line in process.stdout:
        print(line.decode("utf-8"), end="")
```

This script invokes `docker-compose --ansi always up -d`, redirects stderr to stdin and collects the result which is then printed to the console.

However, this is the output of the script:

```shell
$ python main.py
provided file is not a console

$ echo $?
0
```

I'm using Python 3.10.10.

### Compose Version

```Text
Docker Compose version v2.17.3
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.17.2
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 12
  Running: 10
  Paused: 0
  Stopped: 2
 Images: 56
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.11-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.74GiB
 Name: arch
 ID: CDAH:4JFH:SMQE:LH33:FMZW:SHFY:SPC5:4EQA:GVPD:BI2O:PIVE:TSEY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

I used the binary from the Github releases page. That's why `docker info` still shows the old version.

**Comment by ndeloof** [comment]
`stdout=PIPE` you use here does not give child process access to the terminal, it just offers a plain POSIX stream. Compose code require a terminal as it adjust output to width and height (and other attributes).

According to https://docs.python.org/3/library/subprocess.html you can pass `stdout` a file descriptor, so it seems to me ou could pass a reference to the current terminal.

**Comment by sueskind** [comment]
Was it only working before #10442 because it falsely disabled ANSI escape codes? If yes then the issue lies in how I call docker-compose via Python and this issue can be closed.

**Comment by ndeloof** [comment]
before #10442 TUI mode was indeed disabled, so plain text output was used and didn't required special handling for terminal file descriptor

**Comment by ilaidlaw** [comment]
I am seeing this on our Gitlab runners (Docker executor running a Debian bullseye container) with  docker compose `v2.17.3` (but  `v2.17.2` is working). Our runners invoke `docker compose --ansi=always up`. Is there a workaround, or downgrade to `v2.17.2` for now?

**Comment by ndeloof** [comment]
@ilaidlaw workaround is to remove `--ansi=always` which isn't supported when not running in an actual terminal

**Comment by ilaidlaw** [comment]
Ah, interesting. I was trying to find a way to capture colorized output in Gitlab, that worked in `v.2.17.2`. Is there a better method instead of `--ansi=always`?
