### ISSUE TITLE
[BUG] Install the Compose standalone is no longer supported

### ISSUE THREAD

**Issue by LZY7977** [docker/compose#10485]
### Description

It's not a bug!

By looking at the compose v2 [official doc](https://docs.docker.com/compose/install/), it says "This install scenario is no longer supported." under **Scenario three: Install the Compose standalone** section.

Could the docker compose team clarify a bit what this means? Does it mean that there wouldn't be any new compose v2 standalone binary releases?

**Comment by ndeloof** [comment]
The main reason for this change is to promote installation through Docker Desktop to enforce consistent installations and avoid user getting troubles with manual installations. Anyway I don't think there's any reason we consider other ways as "deprecated", need to debate with the team about it.

**Comment by ndeloof** [comment]
docs has been updated to clarify this is not the recommended approach, but still valid
