### ISSUE TITLE
[BUG]The conversion between long and short syntax is not equivalent.

### ISSUE THREAD

**Issue by zhanghengxin** [docker/compose#10491]
### Description

https://docs.docker.com/compose/compose-file/05-services/#long-syntax-3

The conversion between long and short syntax is not equivalent. When the short syntax 
ports:
  - "127.0.0.1:5000-5010:5000-5010"
is converted to long syntax, it is surprising that the target requirement is a numeric type.

I believe this is a bug！

**Comment by ndeloof** [comment]
long syntax for such a range will actually require 10 entries in the configuration, one for each value in the range.

short syntax makes it really shorter :)

**Comment by ndeloof** [comment]
you can use `docker compose config` to see the canonical model being used by compose, with all values using the long syntax

**Comment by zhanghengxin** [comment]
> long syntax for such a range will actually require 10 entries in the configuration, one for each value in the range.这种范围的长语法实际上需要配置中的10个条目，范围中的每个值对应一个条目。
> 
> short syntax makes it really shorter :)short syntax使它更短：）

I believe you have grasped the point I want to express. The semantics of log and short syntax should be the same, and i suggest and insist on it!

**Comment by zhanghengxin** [comment]
Because I am working on a Compose UI ,which allows me to config anything easily. However ,with this syntax,I need to edit each item separately, which is painful. it is actually easier to edit YAML directly.After all, long syntax is more compatible whit UI.I'm not sure if this scenario can convince you to fix it.

**Comment by ndeloof** [comment]
Short syntax only exists for legacy reason, based on `docker run` flags parsing. This is nice for human, but doesn't make any sense once applied to engine API calls. That's why the internal data model uses the full syntax, which is also available for user to fine-tune the config.
So, basically, we won't "fix" this, as this is the legacy we have to work with.

**Comment by zhanghengxin** [comment]
So, can I understand that you are working on resolving this situation?

**Comment by ndeloof** [comment]
Sorry if my english doesn't make it clear.
We won't make any change with short / long syntax for ports definition. Short syntax is inherited from docker CLI, and covers  multiple scenarios. Long syntax maps to actual engine APIs being used to expose ports. Both can be used, but there's no 1:1 relation between those.

I'm closing this issue as "won't fix"
