### ISSUE TITLE
how to use hostname of windows

### ISSUE THREAD

**Issue by yedajiang44** [docker/compose#10495]
hi guys~ I need some help.

I exec powershell command `hostname` and output 
```
yedajiang44
```
now, I write docker-compose.yml file, but how to tell it to the container (because need it in container), I don't want the user to do other operations, just run docker compose up -d

**Comment by glours** [comment]
Hello @yedajiang44 
Can you give us more details about what you try to achieve, sharing your compose file will also help us to get more context.

**Comment by yedajiang44** [comment]
Another application scenario with the same requirement：
> I need change 192.168.0.54 to windows hostname `yedajiang44`
```docker
version: "3.7"

networks:
  kafka:
    driver: bridge

services:
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    privileged: true
    ports:
      - 2181:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    networks:
      - kafka

  kafka:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka
    container_name: kafka
    privileged: true
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.54:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka
```

**Comment by yedajiang44** [comment]
thanks a lot, it works!
