### ISSUE TITLE
[BUG] docker-compose add -p option can cause some commands to fail, such as down, logs-f

### ISSUE THREAD

**Issue by QinJiapeng** [docker/compose#10490]
### Description

After the docker-compose add-p command is started, some commands will not respond after use, such as docker-compose down, docker-compose logs-f, docker-compose ps and so on.

### Steps To Reproduce

1、The relevant version and environment information are shown in the following figure
![image](https://user-images.githubusercontent.com/84890012/233774690-ec2322c0-00a0-4686-96b3-7f18fa937b17.png)
2、The startup command is as follows
docker-compose -f /mydata/redisCluster/docker-compose.yml  -p redis -up -d
3、After startup, some commands failed.

### Compose Version

```Text
Docker Compose version v2.16.0
```

### Docker Environment

```Text
Docker version 20.10.22, build 3a2c30b

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 38
  Running: 14
  Paused: 0
  Stopped: 24
 Images: 48
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 78f51771157abb6c9ed224c22013cdf09962315d
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.71.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.545GiB
 Name: VM-8-5-centos
 ID: W3TU:4EQM:2VRF:D22M:2U7G:RR36:CZ7K:P5HJ:3VVB:JL4H:EJVW:SI4V
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker.mirrors.ustc.edu.cn/
 Live Restore Enabled: false
```

**Comment by glours** [comment]
Hey @QinJiapeng 
Can you give us more details for example an error stack and a compose file (without any sensible data) to reproduce the issue?

**Comment by QinJiapeng** [comment]
> 嘿@QinJiapeng 您能否向我们提供更多详细信息，例如错误堆栈和撰写文件（没有任何敏感数据）以重现该问题？

1、docker-compose.yml
version: "3"
services:
  nginx-1:
    image: nginx
    networks:
      - test-network
  nginx-2:
    image: nginx
    networks:
      - test-network
  nginx-3:
    image: nginx
    networks:
      - test-network

networks:
  test-network:

2、Command
docker-compose -p mynginx up -d
3、The container is still there after executing docker-compose down

**Comment by QinJiapeng** [comment]
version: "3"
services:
  nginx-1:
    image: nginx
    networks:
      - test-network
  nginx-2:
    image: nginx
    depends_on:
      - nginx-1
    networks:
      - test-network
  nginx-3:
    image: nginx
    depends_on:
      - nginx-1
    networks:
      - test-network

networks:
  test-network:

**Comment by QinJiapeng** [comment]
`version: "3"
services:
  nginx-1:
    image: nginx
    networks:
      - test-network
  nginx-2:
    image: nginx
    depends_on:
      - nginx-1
    networks:
      - test-network
  nginx-3:
    image: nginx
    depends_on:
      - nginx-1
    networks:
      - test-network

networks:
  test-network:`

**Comment by ndeloof** [comment]
This is expected: once you us `-p` you explicitly tell compose to use a distinct project name than the one it can automagically guess, and so you'll have to use this same flag for other commands.
Or you can set a `name` attribute in your compose file to make this persistent.
