### ISSUE TITLE
Docker compose (v2) up --log-level missing

### ISSUE THREAD

**Issue by xydesa** [docker/compose#10503]
### Description

The --log-level option doesn't seem to work in compose v2.

This page has replicated help text from the command line that seems to suggest it's been deprecated: https://docs.docker.com/compose/reference/

But it's not mentioned as `not yet implemented` or `not to be implemented` in this page: https://docs.docker.com/compose/compose-v2/

It's also not mentioned in any of the release notes (except when it was added to compose v1): https://github.com/docker/compose/releases?q=log-level&expanded=true

Nor can I find any other reference to this feature being deprecated. Is it actually deprecated? Is there any other way to get the equivalent behavior? If it is deprecated and expected to not work the docs need to be updated.

```
$ docker compose version
Docker Compose version v2.17.3
$ docker version
Client: Docker Engine - Community
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:17:30 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:30 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by ndeloof** [comment]
As a CLI plugin, compose logging is configured at top level `docker` command:
`docker --log-level=debug compose xx ... `

**Comment by ndeloof** [comment]
command line output on https://docs.docker.com/compose/reference/ is obsolete, `docker compose --help` doesn't list `--log-level` flag in any recent release. Let's fix this

**Comment by ndeloof** [comment]
Closing this issue as documentation has been updated
