### ISSUE TITLE
Spike: Investigate building binaries for Windows

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1051]
We need to figure out whether building Windows binaries is feasible with a Python version of Compose. We don't need to add Windows support to Compose _yet_ (e.g. supporting Windows paths, etc)  

This will inform whether Compose will need either a different method of installation on Windows or perhaps even a rewrite in Go.

**Comment by dnephin** [comment]
http://docs.python-guide.org/en/latest/shipping/freezing/ has a nice comparison table, but omits a more recent addition https://github.com/takluyver/pynsist

**Comment by bfirsh** [comment]
See https://github.com/docker/compose/issues/1085

**Comment by aanand** [comment]
The current stumbling block is dockerpty's dependency on `fcntl` for putting the terminal into raw mode. The API for doing this on Windows is - of course - completely different.

The Docker client solves this with a [`term` module](https://github.com/docker/docker/tree/master/pkg/term) that abstracts away the [platform-specific stuff](https://github.com/docker/docker/blob/master/pkg/term/term_windows.go) behind a common API. @dnephin pointed me to [python-prompt-toolkit](https://github.com/jonathanslenders/python-prompt-toolkit), which might do something similar for us.

**Comment by aanand** [comment]
Closed by #1957.
