### ISSUE TITLE
Migrate from Fig

### ISSUE THREAD

**Issue by wernight** [docker/compose#1053]
[Home page](https://github.com/docker/compose) is missing two important things:

 1. Many people have already **Fig**, there should be a link to an upgrade documentation which also include what's new/different (possibly others come from *Crane*).
 2. `docs/index.md` should be linked from that page.

**Comment by luebken** [comment]
Agree.

Just skimmed over compose. As for the `fig.yml` to `docker-compose.yml` migration: are they compatible?

**Comment by wernight** [comment]
They seem to be identical so far as I can tell. Just rename.

**Comment by luebken** [comment]
Yes. Even `docker-compose` looks for a `fig.yml`. The available info I found on this is: https://github.com/docker/compose/releases

**Comment by dnephin** [comment]
Sorry the documentation wasn't totally clear. `docker-compose` should be a drop in replacement for fig. We haven't deprecated the `fig.yml` default yet, but that may happen at some point.

The home page now links to the docs
