### ISSUE TITLE
Add `v1` option to `docker compose ps --format`

### ISSUE THREAD

**Issue by unikitty37** [docker/compose#10537]
### Description

With the switch to Compose v2, the output from `docker compose ps` has become much more verbose than that of v1:

![image](https://user-images.githubusercontent.com/139183/236669139-0f5d96bd-dc30-41ec-9f02-7eb1d77998fe.png)

![image](https://user-images.githubusercontent.com/139183/236669154-80021ead-17ce-4ad7-8b03-42b72c4a01b3.png)

As you can see, each entry now wraps onto two lines, requiring this status window to be much larger. It's unreasonable to expect all Compose users to just go out and buy bigger displays :)

Currently, `--format` only takes two options: `table` and `json`. Ideally, it would also accept a custom format string, so the user could specify _exactly_ what output they want without having to use `--format json` and then write their own parser and formatter.

In the meantime, though, please could we have `--format v1` which outputs in _exactly_ the same format as `docker-compose ps` did?

**Comment by ndeloof** [comment]
`docker compose ps` output has been aligned with `docker ps` for homogeneity between docker commands, which sole addition of a `SERVICE` column. For this reason we don't plan to restore support for compose v1 output.

`--format json` gives you a powerful way to customize format wish and enforce a reproducible output
```
$ docker compose ps --format json | jq -r '[.[].Name, .[].State]|@tsv'
bidule-app-1	running
```

**Comment by unikitty37** [comment]
Thanks — I ended up writing a Ruby script rather than using jq (which doesn't seem to make right-padding particularly easy :)

I've added it below in case it helps anybody else

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

def format_field(contents, max_length)
  return " " * max_length unless contents.is_a?(String)

  contents[...max_length].ljust(max_length)
end

def short_status(status)
  case status
  when 'created'
    'Created'
  when 'restarting'
    'Restart'
  when 'running'
    'Up'
  when 'removing'
    'Remove'
  when 'paused'
    'Pause'
  when 'exited'
    'Stopped'
  when 'dead'
    'Dead'
  else
    status
  end
end

begin
  running_containers = JSON.parse(ARGF.read)
rescue JSON::ParserError
  puts 'The input is not valid JSON.'
  puts 'This script is intended to take the output of `docker compose ps --format json` as input.'
  exit 1
end

puts <<HEADER_END
          Name                         Command               State           Ports
-------------------------------------------------------------------------------------------
HEADER_END

running_containers.each do |container|
  name = format_field(container['Name'], 27)
  command = format_field(container['Command'], 32)
  state = format_field(short_status(container['State']), 7)
  ports = (container['Publishers'] || []).map { |e| "#{e['URL']}:#{e['PublishedPort']}->#{e['TargetPort']}/#{e['Protocol']}" }
  puts "#{name} #{command} #{state} #{ports.shift}"
  ports.each { |p| puts "#{' ' * 68} #{p}" } if ports.length
end
```
