### ISSUE TITLE
Use a .ini like file for loading environment variable

### ISSUE THREAD

**Issue by VisheshIrasus** [docker/compose#10545]
### Description

In Docker Compose, I was unable to find a way to store common environment variables across multiple services. For example, in the following Docker Compose file:

```docker-compose
version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example
  cache:
    image: redis:6
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
  worker:
    build: .
```
we want to define common environment variables using an INI-like file format, such as:

```ini
[__common__]
ENV1=78

[app, db]
ENV2 = 90

[db, cache]
ENV5= 8
```
Unfortunately, the [*, *] syntax is not valid in INI files. However, a different syntax or file format could be used to achieve the same result. Although this would require a bit more setup, it would make it simpler to set up environment variables for multiple services.

**Comment by ndeloof** [comment]
You can use `env_file` attribute with a `key=value` dot env file, see https://docs.docker.com/compose/environment-variables/env-file/
INI file format is commonly used on Windows but never was adopted on other platforms

**Comment by VisheshIrasus** [comment]
Please refer to this question asked by me on SO:
https://stackoverflow.com/questions/76212458/separating-common-environment-variables-in-docker-compose?noredirect=1#comment134404136_76212458

**Comment by ndeloof** [comment]
answered on stackoverflow

**Comment by VisheshIrasus** [comment]
Nope, that answer does not help

**Comment by ndeloof** [comment]
Why? Your question is 

> Somebody recently informed me about yaml anchors but somehow I am not being able to use them correctly. It could be great if someone can help me fix it.

Maybe you could rephrase your request so I better understand what you're expectations are :)

**Comment by ndeloof** [comment]
Maybe you just misunderstood my comment:

**I** answered on stackoverflow: https://stackoverflow.com/questions/76212458/separating-common-environment-variables-in-docker-compose/76215528#76215528

**Comment by VisheshIrasus** [comment]
I have added comments on SO. Still I would like to use an .ini file which would be much cleaner and flexible.
Instead of [app, db], I would use  [app.db]  and split on the dot. I would try pushing a pull request soon.

**Comment by VisheshIrasus** [comment]
I really don't know why you closed it. The issue isn't resolved.

**Comment by ndeloof** [comment]
right, sorry - I considered your original question on stackoverflow answered.
the proposal to support INI is still relevant. Anyway, INI probably is not the adequate file format for this, as none of the other docker commands rely on this (INI adoption is Windows-specific AFAICT)

**Comment by Teut2711** [comment]
I think we can close this issue but add more documentation possible on yaml anchors. Like I didn't knew the list syntax mentioned here.  https://stackoverflow.com/a/76215528/4213362 which solves my issue.
Please be free to close it.
Thanks!

**Comment by ndeloof** [comment]
we indeed could have some more example, and add a link to https://yaml.org/type/merge.html

**Comment by VisheshIrasus** [comment]
Yes
