### ISSUE TITLE
Can we use -H with docker-compose?

### ISSUE THREAD

**Issue by sourav82** [docker/compose#1055]
I would like to target docker-compose to docker swarm host but looks like there is no -H option to specify with docker-compose.

If I could specify the docker host with docker-compose, I do not need to change the docker config file. Docker-compose may target swarm but other tools (say docker CLI itself) can use regular local unix socket.

**Comment by aanand** [comment]
Use the DOCKER_HOST environment variable:

    $ export DOCKER_HOST=tcp://1.2.3.4:5678
    $ docker-compose up

**Comment by sourav82** [comment]
Thanks @aanand
