### ISSUE TITLE
volumes_from not working without up and then up -d

### ISSUE THREAD

**Issue by imton** [docker/compose#1056]
Hi Guys,

I have a container with nginx and other with a rails app.

Nginx uses volumes_from the rails app to server the assets. 

Every time I upgrade the app, if I do it directly with "up -d" nginx doesn't get the assets folder properly.

The only solution is to stop the app and then "up -d". Which has a higher downtime. Most of the time I need to stop and start nginx too.

Also, I was trying to get no downtime at all by using "scale" and creating new containers with the latest rails app image and later stoping and removing the old app containers. It's not working neither, nginx is not getting volumes from the new app containers, forcing me to manually stoping nginx and the apps and starting all over again.

Any ideas?

Thanks

**Comment by imton** [comment]
I am thinking now of mounting the compiled assets in the host. This way nginx and the app will share a persistent folder and I believe this problem would be solved.

**Comment by dnephin** [comment]
I think this might be explained by #1882 or #1981.

We've changed `up` to default to only recreate things that have changed, which should address these issues.

If you're still able to reproduce this issue with the latest `docker-compose` could you please re-open the  issue and provide some commands and an example that shows the volumes not working.  Thank you!
