### ISSUE TITLE
Sequential Docker Compose Execution 

### ISSUE THREAD

**Issue by Sajiyah-Salat** [docker/compose#10563]
### Description

We have a docker compose file in which we want to run jobs one after another. 

PS: depends_on don’t work here because that waits for service to start and we want to run service just after one service gets finish.

Do we have any command for that or is there any way to execute this. If not I would like to see this type of feature.

**Comment by ndeloof** [comment]
There's unfortunately no native concept in compose for a "job" that is expected to complete, only for long running "services". But you still can implement this logic using:

```yaml
depends_on:
   condition: service_completed_successfully
```

the other option would be to use `docker compose run xxxx` and have a simple script run jobs sequentially
