### ISSUE TITLE
Compose V2 Docker image

### ISSUE THREAD

**Issue by gaby** [docker/compose#10573]
### Description

Back with compose v1, the team used to publish an image on each release. That practice stopped once development of v2 started. Are there plans to bring that back?

The current `docker/compose:latest` image is over 2 years old.

**Comment by glours** [comment]
You can use official docker image for this, see https://github.com/docker/compose/issues/10156

**Comment by gaby** [comment]
@glours Thanks! That's genius! May be worth mentioning that on the readme 😁
