### ISSUE TITLE
[BUG] Overlay network not found on worker node

### ISSUE THREAD

**Issue by hibare** [docker/compose#10588]
### Description

Docker Engine is running in swarm mode. I manually created an overlay attachable network foo on the manager node.
Docker Compose services on the manager node start and attach to the network successfully.
Docker Compose services on the worker node cannot find the network.

Network on manager node

```shell
shubham@roci:~$ docker network ls
NETWORK ID     NAME                 DRIVER    SCOPE
7191e5026ba1   bridge               bridge    local
qk501ogrjzoy   db                   overlay   swarm
97cc826964ef   docker_gwbridge      bridge    local
yr5u2xom773h   external             overlay   swarm
8cfe895472d9   host                 host      local
dss0u1vu52nr   ingress              overlay   swarm
e0919cac98d3   none                 null      local
ozajdr83ello   secure               overlay   swarm
```

docker compose up on worker node

```shell
[+] Building 0.0s (0/0)                                                                                         
network secure declared as external, but could not be found

```

### Steps To Reproduce

1. Install latest version of docker & docker-compose as of today
2. create an attachable overlay network on manager node
3. on worker node, create a docker-compose yml file with definition to previously created overlay network
4. run docker compose up

### Compose Version

Docker Compose version v2.18.1

### Docker Environment
Swarm mode: 
Docker version 24.0.1, build 6802122

### Anything else?

This issue started after updating to latest version today

**Comment by ndeloof** [comment]
Thanks for reporting this issue.
This probably is a side-effect from https://github.com/docker/compose/pull/10565, I'll try to replicate and investigate tomorrow
