### ISSUE TITLE
Not returning to shell prompt after sending SIGKILL 

### ISSUE THREAD

**Issue by Mikhail2048** [docker/compose#10583]
### Description

I have researched the issues, and semes there were a lot of people complaining about it: 
https://github.com/docker/compose/issues/7622
https://github.com/docker/compose/issues/9065
https://github.com/docker/compose/issues/9518
e.t.c.

I have filed this as a bug since I do not fully understand - was it fixed, or was it not.
So, what I think is going wrong - when I send `SIGINT` form my terminal, docker-compose stops the containers (forcefully if needed), which is great. But then I want to get back to interactive tty. Why after sending `SIGINT` to `docker-compose` process and after all of the containers stopped I do not return to shell prompt?)

Discussion on [this issue](https://github.com/docker/compose/issues/9065
) seems to conclude that this should be fixed in `docker-compose` version released in Jan 2022, but I use `docker-compose` of version `2.11.2`, which was released Sep 2022. So I think this is a bug... Maybe I am wrong.

### Steps To Reproduce

1. Create any docker-compose file, literally any file that contains 1+ service
2. Then use `docker-compose up` to boot the service
3. Then press `cntrl + c` to send `SIGINT` to docker-compose process
4. And then you do not return to shell prompt even when all containers have been stopped

### Compose Version

```Text
Docker Compose version v2.11.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 25
 Server Version: 23.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-41-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.34GiB
 Name: mpolivaha-Modern-14-B11MOU
 ID: QIOH:U57T:3GNA:UAK7:IV7B:OIIL:Z4MS:CYQM:HVBZ:NVB4:4RHU:4XE7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
Docker Compose v2.11.2 is pretty old, could you try reproducing this issue with latest release (v2.18.1) ?

**Comment by Mikhail2048** [comment]
On v.2.18.1 it seems to work. After sending `SIGINT` I get back to shell prompt once all containers have been terminated. Thanks!
