### ISSUE TITLE
[BUG] Reset value do not work on lists

### ISSUE THREAD

**Issue by eriksenonline** [docker/compose#10589]
### Description

I am trying to use this feature https://docs.docker.com/compose/compose-file/13-merge/#reset-value in an docker-compose-override.yml file but get an error running docker compose config

**I get this error "validating /home/xxxxx/test/docker-compose.override.yml: services.web.ports must be a list"**

My docker-compose.yml file  
```
version: '3'
services:
  web:
    image: nginx
    volumes:
      - "./:/app"
    ports:
      - "8080:80"
```

My docker-compose-override.yml file  
```
version: '3'
services:
  web:
    ports: !reset
```

### Compose Version

```Text
Docker Compose version v2.18.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 73
 Server Version: 24.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 15.4GiB
 Name: Obi-Wan
 ID: 93923798-63dc-488e-a54a-62596ee09e13
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

It seems the !reset is not defined in https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

**Comment by ndeloof** [comment]
Thanks for reporting this bug, I'll investigate tomorrow

> It seems the !reset is not defined in [compose-spec/compose-spec@master/schema/compose-spec.json](https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json)

`!reset` is a yaml tag, this is specific to yaml syntax can't be defined in a JSON schema

**Comment by ndeloof** [comment]
`!reset` is just an annotation in the yaml syntax, still need a value to be declared (whenever it won't be used in this context).
Typically, you can use:
```yaml
services:
  web:
    ports: !reset []
```

by the way, you don't need a `version` in your compose file anymore as we adopted compose specification. While it is just ignored, better not use one to make it clear you're using modern compose file syntax
