### ISSUE TITLE
[BUG] variables not applied to config

### ISSUE THREAD

**Issue by swingbit** [docker/compose#10590]
### Description

Variables loaded via `env_file` do end up in the `environment` section, but are not applied to the compose configuration.

### Steps To Reproduce

`docker-compose.yml`:
```
services:
  project:
    env_file: ./project.env
    container_name: newname.${PROJECT}
    image: busybox
    entrypoint: "tail -f /dev/null"
```
`project.env`:
```
PROJECT=myproject
```

Result of `docker compose config`:
```
$ docker compose config
WARN[0000] The "PROJECT" variable is not set. Defaulting to a blank string. 
name: dc
services:
  project:
    container_name: newname.
    entrypoint:
    - tail
    - -f
    - /dev/null
    environment:
      PROJECT: myproject
    image: busybox
    networks:
      default: null
networks:
  default:
    name: dc_default
```

Notice that variable `PROJECT` is read correctly from the file, but is not applied to `container_name`.

If the variable is removed from `project.env` and set externally with `export PROJECT=myproject`, then it works correctly.

### Compose Version

```Text
$ docker compose version
Docker Compose version v2.18.1
$ docker-compose version
Docker Compose version v2.18.1
```

### Docker Environment

```Text
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 23
 Server Version: 23.0.6
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.14-300.fc38.x86_64
 Operating System: Fedora Linux 38 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 62.53GiB
 Name: <removed>
 ID: J2FL:O2SZ:WLDN:MTU5:R3TU:OZHL:24PC:IV7K:V5WF:UJWZ:H6Y3:VADU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ishdockerhub
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
This is the expected behavior. `env_file` is used to define container's environment, as demonstrated by `docker compose config`, but has no impact on parsing `compose.yaml`. You probably want to use `docker compose --env-file xxx` - yes, this flag name is very confusing, but this is our legacy...

**Comment by swingbit** [comment]
@ndeloof  Thanks for your reaction.

So apparently I had always interpreted the effect of `env_file` incorrectly.

What confused me is that I (thought I) always used `env_file` only and got the substitutions during parsing.

I fact, I have always used a `.env` file, and created a symlink to it, which I then loaded with `env_file` (mostly because I wanted the file with variables not to be hidden).

Probably again an effect of legacy, but I think it is very reasonable to think that having a `.env` or using `env_file: project.env` are equivalent. Now I see they are not. Having a `.env` file is equivalent to the `--env-file` cmdline argument.
