### ISSUE TITLE
Changing the IP assigned to k8s cluster container which caused stop running the container

### ISSUE THREAD

**Issue by Fatimastm** [docker/compose#10603]
### Description

I have a KinD k8s cluster running in docker. Today suddenly was stopped running and became unaccessible.  After exploring, I found out the IP that is docker assignes to kind-control-plane container has became changed and is not the same with kubeconfig.  

### Steps To Reproduce

Get the container IP:
`$ container_ip=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "kind-control-plane")
$ echo "$container_ip"
`
>172.20.0.7

While the in kubeconfig, the IP od kind cluster is different. 
`$ cat ~/.kube/config`

>172.20.0.4

### Compose Version

```Text
Docker Compose version v2.18.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 524
 Server Version: 24.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 4.15-126-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 32.78GiB
 Name: vm222
 ID: NJ2O:CVTB:XKUN:Z552:4FIZ:4TKL:SJBA:89M2:2CHG:IT7W:Q3LM:G4ZW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: vivida22
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
Can you please clarify how this relates to Docker Compose ?

**Comment by Fatimastm** [comment]
The IP addresses assigned to the containers within the K8s cluster are managed by the container runtime (e.g., Docker) and are subject to changes based on factors like container restarts, scaling, or redeployments. This is especially true when using dynamic IP assignment methods like the default bridge network in Docker Compose. I would like to know if there is a solution for this issue?

**Comment by ndeloof** [comment]
You can configure your compose services to have a fixed IP address assigned
see https://github.com/compose-spec/compose-spec/blob/master/05-services.md#ipv4_address-ipv6_address

I'm not sure about the relation with you k8s usage as you didn't described how compose is used in combination with kinD

**Comment by Fatimastm** [comment]
Thanks alot!
I am using Docker Compose to manage KinD (Kubernetes in Docker) cluster.
