### ISSUE TITLE
Swarm overlay network can't be used in docker-compose.yml (see issue 4601)

### ISSUE THREAD

**Issue by rwuthric** [docker/compose#10617]
It looks to me that issue [4601](https://github.com/docker/compose/issues/4601) is back with version v2.18.1 of Docker Compose (see [here](https://github.com/docker/compose/issues/4601#issuecomment-1562087725)).

**Comment by ndeloof** [comment]
Seems to be a duplicate for https://github.com/docker/compose/issues/10588
Would you have a chance to try building compose from source and confirm the error persists ?

**Comment by rwuthric** [comment]
Indeed it is a duplicate of #10588. Missed that one. My bad. I will setup this weekend a test machine with Docker Compose built from latest source version and let you know outcome.

**Comment by ndeloof** [comment]
closing this as duplicate, please follow-up on https://github.com/docker/compose/issues/10588

**Comment by hibare** [comment]
After waiting for weeks for a release, I just compiled the source code and tested it. It seems to have fixed that error
