### ISSUE TITLE
[BUG] docker-compose commands failing with "unknown shorthand flag" when using -p option

### ISSUE THREAD

**Issue by jb-2197** [docker/compose#10613]
### Description

I am having some weird behaviour trying to use the docker-compose standalone binary. Note that if I install docker-compose-cli using yum then docker compose commands work perfectly fine, however I'd like to use the standalone version if possible.

The issue seems to occur only when specifying a project name as part of the command e.g.
```
./docker-compose up -d # Works
./docker-compose -p compose up -d # Doesn't work - "unknown shorthand flag: 'd' in -d"
./docker-compose ps -a # Works
./docker-compose -p compose ps -a # Doesn't work - "unknown shorthand flag: 'a' in -a"
```

### Steps To Reproduce

1. Given I am using Alma Linux 8
2. Install docker-ce via yum
3. Ensure docker daemon is running
4. Download docker-compose binary from github
5. Run commands using ./docker-compose from a directory containing a docker-compose.yml file
6. See description for specific issues faced

### Compose Version

```Text
$ ./docker-compose version
Docker Compose version v2.18.1

$ docker compose version
docker: 'compose' is not a docker command.
See 'docker --help
```

### Docker Environment

```Text
$ docker info
docker info
Client: Docker Engine - Community
 Version:    24.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.1
 Storage Driver: fuse-overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-1035-azure
 Operating System: AlmaLinux 8.6 (Sky Tiger) (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.63GiB
 Name: xxxxxxxxxx
 ID: 8ae3ac6b-5ffe-4e13-beaf-b94057594f3a
 Docker Root Dir: /docker/daemon
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  xxxxxxxxxxxx
  127.0.0.0/8
 Registry Mirrors:
  xxxxxxxxxxx
 Live Restore Enabled: true
```

**Comment by glours** [comment]
Hello @jb-2197 
This is a funny one 😅 
So to explain you what happens in your case. The standalone binary of Compose embedded the plugin version. 
When you're typing `docker-compose -p compose ...`, our CLI detect `compose` as the activation of the plugin and not as your project name. 
You will see the same behavior if you do `docker compose -p up -d` (and same for all compose commands in fact)
So a simple workaround is to use an another name for your project such as `my-compose`

**Comment by jb-2197** [comment]
@glours Thank you for the explanation - this makes sense now! I'll update the project name to be something else.
