### ISSUE TITLE
[BUG] docker compose down --help prints incorrect description for the --volumes flag.

### ISSUE THREAD

**Issue by thallgren** [docker/compose#10610]
### Description

The output of `docker compose down --help` suggests that the `--volumes` flag takes an argument although it appears to be a boolean flag. Passing a volume name as an argument results in an error.

### Steps To Reproduce

Run
```console
$ docker compose down --help
```
Observe the output about the --volumes flag:
```
  -v, --volumes volumes   Remove named volumes declared in the volumes section of the Compose file and anonymous volumes attached to containers.
```
I would have expected it to be:
```
  -v, --volumes       Remove named volumes declared in the volumes section of the Compose file and anonymous volumes attached to containers.
```

### Compose Version

```Text
Docker Compose version v2.12.2
```

**Comment by ndeloof** [comment]
Pflag library [UnquoteUsage](https://github.com/spf13/pflag/blob/master/flag.go#L568-L573) is doing some voodoo magic to extract a parameter name/description from an (expected) code example set in description.
