### ISSUE TITLE
Add option to list non-running containers

### ISSUE THREAD

**Issue by hamiltont** [docker/compose#1061]
Can `docker-compose ps` have an option like `docker-compose ps -a` that shows containers which are non-running? Basically, I'd like  an easy method to see what's inside the `docker-compose.yml` file without having to cat the file and skim through it.

**Comment by hamiltont** [comment]
Hm, so I just realized that `ps` lists non-running containers if they have exited. I suppose this should be a request to also list services with a "never started" status

**Comment by aanand** [comment]
It might be good for `ps` to be more service-centric, yes.

**Comment by draghuram** [comment]
#dibs

**Comment by draghuram** [comment]
If "docker-compose ps -a" lists never started containers, wouldn't it be inconsistent with "docker ps -a" semantics?

**Comment by technolo-g** [comment]
I would like to vote that we replicate the behavior of docker with 
`docker-compose ps` not showing exited or otherwise stopped containers and
`docker-compose ps -a` showing all containers running or not

**Comment by nightscape** [comment]
:+1:

**Comment by clintam** [comment]
I see what @draghuram means: `docker-compose ps` already lists 'stopped' containers, which is what `docker ps -a` provides. What we want here is to have a flag to also capture "never started" containers. There is no way to be "consistent" with `docker ps` here as docker would have no concept of containers that may be started in the future.

I can still see the value in such a mechanism as it will allow to check if any more work needs to be done to start all of the services in an environment. But it does feel a bit off right now in the difference between docker core.

Perhaps another approach would be to add a `--dry-run` flag to `docker-compose up` that would detail all of the stuff needed to bring an environment back up?

**Comment by koooge** [comment]
It seems to be implemented by #6327

**Comment by ijc** [comment]
Issue grooming: I agree with the previous comment. Closing.
