### ISSUE TITLE
[BUG] docker compose alpha watch restart all my services

### ISSUE THREAD

**Issue by maxcleme** [docker/compose#10626]
### Description

Wanted to play with the new `docker compose alpha watch`, however it seems to restart all my services while I only added `x-watch` directive to one of them.

### Steps To Reproduce

1. Tried with the latest version installed manually
```
docker compose version
Docker Compose version v2.17.3
```

2. `compose.yaml`, `Dockerfile` & `entrypoint.sh`

```
services:
  a:
    build:
      context: .
    x-develop:
      watch:
      - action: rebuild
        path: hello.txt
  b:
    build:
      context: .
  c:
    build:
      context: .
```

```
FROM alpine:latest
WORKDIR /app
COPY entrypoint.sh .
COPY hello.txt .

STOPSIGNAL 9
ENTRYPOINT ["sh", "-c", "/app/entrypoint.sh"]
```
```
DATE=`date`
while true
do
  echo $DATE `cat hello.txt`
  sleep 1 
done
```

3. Starting up the stack & the watch

```
compose-watch-test-a-1  | Fri May 26 15:36:21 UTC 2023 hello
compose-watch-test-b-1  | Fri May 26 15:36:21 UTC 2023 hello
compose-watch-test-c-1  | Fri May 26 15:36:21 UTC 2023 hello
compose-watch-test-a-1  | Fri May 26 15:36:21 UTC 2023 hello
compose-watch-test-c-1  | Fri May 26 15:36:21 UTC 2023 hello
compose-watch-test-b-1  | Fri May 26 15:36:21 UTC 2023 hello
```

```
docker compose alpha watch
watch command is EXPERIMENTAL
watching /Users/maxcleme/workspace/maxcleme/compose-watch-test
watching /Users/maxcleme/workspace/maxcleme/compose-watch-test
watching /Users/maxcleme/workspace/maxcleme/compose-watch-test
```

4. Editing `hello.txt`

Rebuild is indeed triggered, but all my services got replaced

```
compose-watch-test-a-1  | Fri May 26 15:43:20 UTC 2023 world
compose-watch-test-c-1  | Fri May 26 15:43:20 UTC 2023 world
compose-watch-test-b-1  | Fri May 26 15:43:20 UTC 2023 world
compose-watch-test-a-1  | Fri May 26 15:43:20 UTC 2023 world
compose-watch-test-c-1  | Fri May 26 15:43:20 UTC 2023 world
```

### Compose Version

```Text
Docker Compose version v2.17.3
```

### Docker Environment

```Text
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /Users/maxcleme/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /Users/maxcleme/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/maxcleme/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/maxcleme/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/maxcleme/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/maxcleme/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/maxcleme/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     /Users/maxcleme/.docker/cli-plugins/docker-scout
```

### Anything else?

Also occurring with the latest ref here after `make install`

```
docker compose version
Docker Compose version v2.18.1-20-g6f6e1635
```

BTW, is there any way of toggling "watch" from `docker compose up` directly? Or do we have to wait until GA 😅 ?

**Comment by ndeloof** [comment]
we indeed set a default `x-develop:` config for all services with a build section, as "rebuild on change".
This seems to be too aggressively trying to do magic with user's configuration, we should remove this "feature"

**Comment by ndeloof** [comment]
>  is there any way of toggling "watch" from docker compose up directly?

nope, this has been discussed already, but is challenging as we need then to mix container logs and build output (or would need to run build without output, but then you won't get any logs on build failure)

**Comment by maxcleme** [comment]
> we indeed set a default x-develop: config for all services with a build section, as "rebuild on change".
This seems to be too aggressively trying to do magic with user's configuration, we should remove this "feature"

Makes sense then! However it is misleading I agree 😅 

> nope, this has been discussed already, but is challenging as we need then to mix container logs and build output (or would need to run build without output, but then you won't get any logs on build failure)

Isn't both already mixed when I do `docker compose up --build` anyway? But I guess it is not exactly similar since they run one after the other, it is not really mixing it indeed. Out of curiosity, why is it challenging? Because they would both share the same writer and might overlaps each others (truncate line, etc)?

**Comment by ndeloof** [comment]
> Isn't both already mixed when I do docker compose up --build anyway?

not "mixed", then ran one after the other. With watch we would have to dump container logs while build is in progress.

> Out of curiosity, why is it challenging?  

buildkit takes full control on the terminal to render it's own progress UI. I wish we can collect buildkit event for an image being built and show those as plain logs the same way we dump container logs, or maybe fully revisit our UX as an interactive TUI, something like lazydocker or such
