### ISSUE TITLE
Dockerized Pyrocms can't be installed although no problem with Native OSs

### ISSUE THREAD

**Issue by fatihalp** [docker/compose#10629]
### Description

I'm dockerizing my app and testing for weeks.  Installed hundereds of times with different configuration. Can't install my Dockerized project. What's different :(

### Steps To Reproduce

1. Installed Pyrocms on Windows & Ubuntu 22 and Mac (all native) with not problem https://github.com/pyrocms/pyrocms
2. Using Ubuntu 22 and Docker Ubuntu 22 with same project 
3. Same PHP version
4. Same PHP extensions
5. Same PHP Configuration
6. Same files and project. 
7. Checked file & user permissions.
8. I can install on native ubuntu 22 but not on Docker Ubuntu 22
9. Reported to software team and think that it's software related but I'm trying it for weeks and there is no problem at all on Native OSs.

Can you please idea what is difference? 

![image](https://github.com/docker/compose/assets/219454/2c6ab739-9966-4233-996c-6ef2fe17db2b)

### Compose Version

```Text
Docker Compose version v2.17.3
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     /usr/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 3.594GiB
 Name: docker-desktop
 ID: a46b34a9-162e-4c2a-baed-3873946e7ce4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Developers also asked before: https://github.com/pyrocms/pyrocms/issues/5106

**Comment by ndeloof** [comment]
I hardly can offer any assistance here without any knowledge about the application being ran here.
Better wait for a maintainer to answer on https://github.com/pyrocms/pyrocms/issues/5106

**Comment by fatihalp** [comment]
I really understand you hardly understand our situation. @ndeloof

But I just want to understand what can cause this kind of issue? 

https://github.com/openclassify/openclassify/blob/fatihalp/Dockerfile

https://github.com/openclassify/openclassify/blob/fatihalp/docker-compose.yml

https://github.com/openclassify/openclassify/blob/fatihalp/docker/entrypoint.sh


![image](https://github.com/docker/compose/assets/219454/e2ed4aef-6bd6-477d-b45d-81eb46ac0074)

**Comment by emrullahardc** [comment]
@fatihalp If you remove the env_file param in line 38 of the docker-compose.yml file, it will work. I'm not sure why yet, but the env_file variable is causing you to this error.

**Comment by ndeloof** [comment]
Closing this issue as initial reported didn't provided the requested confirmation same issue doesn't apply with a plain `docker run..` command
