### ISSUE TITLE
Please add support for restart policy depending on exit code

### ISSUE THREAD

**Issue by AvivAvital2** [docker/compose#10636]
### Description

As a developer I sometimes encounter a scenario where the current restart policies are not flexible enough.
An app could have multiple conditions in which it fails to load, but those conditions may be vastly different.
In example, a Java application can exit if incorrect configuration is provided, but assuming an unhandled exception is encountered the application may crash and exit anyway.

For the latter, specifying `restart: on-failure` is a no brainer. 
However, if my app is optional and the user has not configure it, exiting with a non zero status code would continuously restart and create unnecessary noise in the log.

If misconfiguration was the only scenario I could have easily specify `restart: on-failure:10` for max of 10 retries, but this means the container would be restarted up to 10 times on a failure, whether it was misconfiguration or an actual error.

Adding support to specify exactly on which exit code to trigger the restart policy would allow much greater flexibility since then you could assign specific policies to each event.
E.g.
```yaml
restart:
    - 0:no
    - 1:5
    - 2:always
```
Here we specify that:
- Exit code 0: do not restart
- Exit code 1: 5 retries (since on-failure is implied)
- Exit code 2: always restart

For your consideration

**Comment by ndeloof** [comment]
restart policy is defined by the docker engine, not by compose. See https://docs.docker.com/config/containers/start-containers-automatically/
Feel free to open a feature request on github.com/moby/moby
