### ISSUE TITLE
[BUG] Unexpected behaviour when using parameter expansion

### ISSUE THREAD

**Issue by Jappie3** [docker/compose#10635]
### Description

Consider the following compose file - note the use of parameter expansion:

```yaml
---
version: "3.9"
services:
  test:
    image: hello-world
    environment:
      FOO: ${BAR:?bar not found}
    env_file:
      - my-env.env

```

and the `my-env.env` file:

```ini
BAR=aoeu
```

When I run `docker compose config`, I'm expecting `FOO` to get the value of `BAR` - namely `aoeu` - since `BAR` is defined in the environment file specified in the `env_file` section.

However, what actually happens is the following:

```
$ docker compose config

parsing [...]/docker-compose.yml: error while interpolating services.test.environment.FOO: required variable BAR is missing a value: bar not found
```

When I replace `${BAR:?bar not found}` with just `${BAR}`, it seems like Docker still can't find BAR when trying to assign it to FOO, but it is present in the output anyway...

```
$ docker compose config

WARN[0000] The "BAR" variable is not set. Defaulting to a blank string.
name: temp
services:
  test:
    environment:
      BAR: aoeu
      FOO: ""
    image: hello-world
    networks:
      default: null
networks:
  default:
    name: temp_default
```

Upon further investigation, when I rename `my-env.env` to `.env` (meaning I don't have to explicitly specify it in the compose file anymore), I get the following output:

```
$ docker compose config

name: temp
services:
  test:
    environment:
      FOO: aoeu
    image: hello-world
    networks:
      default: null
networks:
  default:
    name: temp_default
```

This is the behaviour I was expecting from the beginning, but somehow it didn't seem to work with parameter expansion.

I am not 100% sure this is a bug, but it doesn't look like intended behaviour...

### Steps To Reproduce

- Create a docker compose file
- Paste the following:

```yaml
---
version: "3.9"
services:
  test:
    image: hello-world
    environment:
      FOO: ${BAR:?bar not found}
    env_file:
      - my-env.env
```

- Create an env file called `my-env.env`
- Paste the following:

```ini
BAR=aoeu
```

- Run `docker compose config`
- Expected output: `FOO` should have the value of `BAR`, namely `aoeu`
- Actual output: `required variable BAR is missing a value: bar not found`

### Compose Version

```Text
Docker Compose version 2.18.1
```

### Docker Environment

```Text
Client:
 Version:    24.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.18.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 24.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1677a17964311325ed1c31e2c0a3589ce6d5c30d.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.3.4-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 13.51GiB
 Name: Arch
 ID: dd6f90fc-d930-4cf6-beff-6aabf733e4ca
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
`env_file` attribute is used to define the environment set _in container_, not for variable interpolation (while the `docker compose --env-file` flag name is confusing from this point of view)
