### ISSUE TITLE
[BUG] docker compose sync doesn't create folder

### ISSUE THREAD

**Issue by turkerdev** [docker/compose#10644]
### Description

syncing doesn't create folders, creating a file in that folder crashes docker daemon.
```
Error response from daemon: Could not find the file /app/src/newfolder in container ...
```

### Steps To Reproduce

enable docker compose syncing
create folder
create file inside that folder

### Compose Version

```Text
2.18.1
```

**Comment by ndeloof** [comment]
This is indeed a limitation of the `PutContainerArchive` engine API.
I'm investigating for a workaround
