### ISSUE TITLE
[BUG] Environment variables are not configured with --env-file unless declared

### ISSUE THREAD

**Issue by alfonsomunozpomer** [docker/compose#10650]
### Description

When passing environment variables with `--env-file`, unless the variable is declared in the YAML file, it’s not added to the environment. This behaviour is different to having a `.env` file and having an `env_file` entry.

### Steps To Reproduce

`docker-compose.yml`:
```yaml
version: '3.6'

services:
  db:
    image: postgres
```

`dev.env`:
```yaml
POSTGRES_PASSWORD=foobar
```

Output of `docker compose --env-file dev.env config` (`$PWD` is `~/dc`):
```
$ docker compose --env-file dev.env config
name: dc
services:
  db:
    image: postgres
    networks:
      default: null
networks:
  default:
    name: dc_default
```

If the YAML file is changed to:
```yaml
version: '3.6'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
```

Then the variable is in the config with the right value:
```
$ docker compose --env-file dev.env config
name: dc
services:
  db:
    environment:
      POSTGRES_PASSWORD: foobar
    image: postgres
    networks:
      default: null
networks:
  default:
    name: dc_default
```

If the variable is not declared but you use `env_file` or rename the file to `.env` without `--env-file` then the output of `config` is like the last one pasted above. This isn’t problematic for most cases, but I’ve found that precisely with Postgres images, the container won’t start because it can’t find `POSTGRES_PASSWORD` in the environment.

### Compose Version

```Text
Docker Compose version v2.17.2

docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.17.2)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 661
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 66u3kw0wlyb2f55ollie3dwa1
  Is Manager: true
  ClusterID: 5dyy7kjbbd3oeoc9ug7hq3fj6
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.1.65
  Manager Addresses:
   192.168.1.65:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  userns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 30.89GiB
 Name: ubu20-n-e38f90a30d
 ID: IYIH:TYF4:DA3E:DZEB:OCBB:L7FK:GJ4S:WPYZ:7FXM:V32B:LSEL:AS3Z
 Docker Root Dir: /var/lib/docker/5309.1030
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 10.10.0.0/16, Size: 24
```

**Comment by ndeloof** [comment]
That's the expected behavior. `--env-file` flag isn't used to set container environment, but to tell compose which file to use to read variables used to parse compose.yml (defaults to `./.env`)

To make a variable required, you can use:
```yaml
environment:
  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?error message}
 ```
 if not declared in user's environment nor .env file, compose will then report invalid configuration and dump error message

**Comment by alfonsomunozpomer** [comment]
Thank you for the clarification and the suggested solution.

That means that `--env-file` on one side, and `.env` and `env_file` on the other, have slightly different behaviours. I didn’t see it documented in https://docs.docker.com/compose/environment-variables/set-environment-variables/, and from reading it I got the impression that all three methods are equivalent. I think it would be helpful to add a note to describe this.

**Comment by ndeloof** [comment]
that's the other way: `--env-file` and `.env` are used to set variables set to expand variables in compose.yaml _AND_ as values when you declare a variable without an equal sign in `environment`. `env_file` attribute in compose.yaml directly set container environment based on source env file (just like `docker run --env-file`)
