### ISSUE TITLE
Getting error while try to schedule docker container from airflow and crontab

### ISSUE THREAD

**Issue by chandrabh** [docker/compose#10651]
### Description

version : Docker Compose version v2.16.0
=======================================
What tried so far :

I have granted full permission and ownership on file :

sudo chmod 666 /run/podman/podman.sock
sudo chmod 666 /var/run/podman/podman.sock
sudo chown chbhan /run/podman/podman.sock
sudo chown chbhan /var/run/podman/podman.sock
sudo chown chbhan:podman /run/podman/podman.sock
sudo chown chbhan:podman /var/run/podman/podman.sock

I have restarted the service:
#start podman service
sudo systemctl restart podman
sudo service podman restart

#validate podman status
service podman status

#reload daemon services
sudo systemctl daemon-reload

=======================================
Host details:

I have oracle Linux 8 host
I am using podman in place of docker

Able to run images and container without issue

=======================================
Issue:
Getting error while try to schedule docker container from airflow and crontab in both getting error for missing files:
Could you suggest what I can do

=======================================
What tried so far :

I have granted full permission and ownership on file :

sudo chmod 666 /run/podman/podman.sock
sudo chmod 666 /var/run/podman/podman.sock
sudo chown chbhan /run/podman/podman.sock
sudo chown chbhan /var/run/podman/podman.sock
sudo chown chbhan:podman /run/podman/podman.sock
sudo chown chbhan:podman /var/run/podman/podman.sock

I have restarted the service:
#start podman service
sudo systemctl restart podman
sudo service podman restart

#validate podman status
service podman status

#reload daemon services
sudo systemctl daemon-reload

=======================================
Host details:

I have oracle Linux 8 host
I am using podman in place of docker

Able to run images and container without issue
But when I try to schedule getting error:

 Error message
=======================================
docker-compose getting below error:

docker-compose up
/usr/local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
from cryptography.hazmat.backends import default_backend
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 721, in urlopen
chunked=chunked,
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 415, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/lib64/python3.6/http/client.py", line 1273, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output
self.send(msg)
File "/usr/lib64/python3.6/http/client.py", line 982, in send
self.connect()
File "/usr/local/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

=======================================
Airflow getting below error:

Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 721, in urlopen
chunked=chunked,
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 415, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/lib64/python3.6/http/client.py", line 1273, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output
self.send(msg)
File "/usr/lib64/python3.6/http/client.py", line 982, in send
self.connect()
File "/usr/local/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

### Steps To Reproduce

t2 = DockerOperator(
                    task_id='docker_task',
                    image='localhost/cata_etl_final:1',
                    api_version='auto',
                    auto_remove=True,
                    #docker_conn_id='podman_default',
                    environment={
                                    "CONFIG_PATH": "/opt/ccdw/prod",
                                    "JAR_PATH": "/usr/ojdbc11/ojdbc11.jar"
                                },
                    container_name="cat-etl-container",
                    working_dir="/opt/ccdw/prod",
                    mounts=['/opt/ccdw/prod/wallet:/usr/lib/oracle/21/client64/lib/network/admin/'],
                    command="python3 etl_artifactory_load.py {process_Date}",
                    docker_url="unix://run/podman/podman.sock",
                    network_mode="bridge"
                )

### Compose Version

```Text
Docker Compose version v2.16.0
```

### Docker Environment

```Text
$ docker info
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.6-1.module+el8.8.0+21045+adcb6a64.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: 31a72124adb6095b6be85b27e3e481313a1cea96'
  cpuUtilization:
    idlePercent: 96.8
    systemPercent: 0.77
    userPercent: 2.43
  cpus: 8
  distribution:
    distribution: '"ol"'
    variant: server
    version: "8.8"
  eventLogger: file
  hostname: ccdw-flex-3
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 2147483646
      size: 1
    - container_id: 1
      host_id: 1186893
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 85945
      size: 1
    - container_id: 1
      host_id: 1186893
      size: 65536
  kernel: 5.4.17-2136.319.1.2.el8uek.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 60692148224
  memTotal: 66890891264
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.4-1.module+el8.8.0+21045+adcb6a64.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      spec: 1.0.2-dev
      go: go1.19.4
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/user/85945/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_SYS_CHROOT,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.8.0+21045+adcb6a64.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 20h 51m 6.00s (Approximately 0.83 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - container-registry.oracle.com
  - docker.io
store:
  configFile: /home/chbhan/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/chbhan/.local/share/containers/storage
  graphRootAllocated: 38069878784
  graphRootUsed: 31424286720
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/85945/containers
  transientStore: false
  volumePath: /home/chbhan/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1684543580
  BuiltTime: Sat May 20 00:46:20 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

**Comment by glours** [comment]
Hello @chandrabh 
You already opened issue https://github.com/docker/compose/issues/10649 
You're using the Python version of Compose a.k.a Compose v1 which reached end-of-life and isn't supported anymore.
Please Give a try to the Go version of Compose a.k.a Compose V2, and if you're able to reproduce with this version we'll take a look to your problem.
I close this issue as we don't support Compose V1 anymore
