### ISSUE TITLE
[BUG] For `up` command, "pulling" and "Pulled" events should respect `quietPull` flag

### ISSUE THREAD

**Issue by Songyu-Wang** [docker/compose#10686]
### Description

The function `pullServiceImage` in https://github.com/docker/compose/blob/v2/pkg/compose/pull.go has `quietPull bool` as an argument.

However, the "pulling" and "Pulled" event logger are not wrapped under the argument.
It should follow the same logic as 
```
if !quietPull {
			toPullProgressEvent(service.Name, jm, w)
		}
```

### Steps To Reproduce

N/A

### Compose Version

```Text
v2 head
```

### Docker Environment

```Text
N/A
```

### Anything else?

![image](https://github.com/docker/compose/assets/36670132/86b69c79-58fa-4fa3-bc4c-ced37fe2a8f4)

**Comment by ndeloof** [comment]
`quietPull` allows to skip individual pull progress messages to be displayed, but still we want the user to be aware about the current state of a service, which will be `Pulling` before it can become `Created` then `Started`.

**Comment by Songyu-Wang** [comment]
@ndeloof 
Thanks for replying.
I think `[+] Running 1/15` would be more than enough to indicate `current state of a service`. Pulling and pulled events are juts redundant information.


I am gonna assume most people use quiet pull because they are using docker compose with some kinda SaaS CI and the interactive logs keep getting duplicates every seconds(10th of a second?), For example, https://github.com/docker/compose/actions/runs/5220651859/jobs/9423987875 is not the exact commands, but the symptom is the same.
<img width="939" alt="image" src="https://github.com/docker/compose/assets/36670132/c213f076-688c-4753-a6c6-f818658c954a">

Only remove part of the messages but keep others wont resolve the above pain point. 

I would really hope you can re-consider it

**Comment by ndeloof** [comment]
> Only removing part of the messages but keeping others wont resolve the above pain point.

The only remaining parts are `Pulling` then `Pulled`, just 2 lines when ran in "non-TTY" mode, which are useful to understand the pull completed successfully.
```
$ docker compose --ansi=never up --quiet-pull
 test Pulling 
 test Pulled 
 Container truc-test-1  Creating
 Container truc-test-1  Created
Attaching to truc-test-1
```
I'm closing this as "not planned"

**Comment by Songyu-Wang** [comment]
<img width="939" alt="Screenshot 2023-06-11 at 12 54 11" src="https://github.com/docker/compose/assets/36670132/56bcd923-830b-4373-bc1b-cd0ce2723011">

**Comment by Songyu-Wang** [comment]
<img width="549" alt="image" src="https://github.com/docker/compose/assets/36670132/2b1dcf3b-b010-463f-9891-2a4565d9f138">

**Comment by ndeloof** [comment]
This happens because you use ANSI-based progress without an actual terminal. A new ANSI sequence will be emitted every 100ms, and obviously a pull operation can take much more. Are you forcing `--ansi` flag here ?

**Comment by Songyu-Wang** [comment]
We are not because the ci tool we are using handles ansi on the web UI. The issue is the size of exported logs from the said ui tools( which is just a plain text file)

**Comment by ndeloof** [comment]
I proposed we introduce a flag to offer better control on the progress UI, so you can switch to plain text mode and avoid huge logs, but still can benefits from ANSI-colored output for container logs.
