### ISSUE TITLE
Support autoremoval of docker-compose containers

### ISSUE THREAD

**Issue by mipo256** [docker/compose#10688]
### Description

I didn't manage to find this issue, so I create a feature request: **It would be great if you have an `--rm` flag similar to what we have in `docker`.** 

There is a [question about it on SO](https://stackoverflow.com/questions/47207616/auto-remove-container-with-docker-compose-yml) that is quite popular, and it seems that this feature concerns not only me. What I think will be great, is if I would have the ability to do smth like:

`docker-compose --rm up`

And then, once the containers (or single container) are stopped, they automatically get removed. Sometimes you need to test something, and you relaunch containers multiple times, and it is quite tedious to remove them again and again. I know we can use 

`docker-compose rm -fsv`

but it is still an additional command. Would be great if there will be a build-in option.

**Comment by ndeloof** [comment]
This flag is available on `docker compose run`. `compose up` serves a distinct purpose, and typically relies on previous container to inherit anonymous volumes, and will recreate container if needed, or will just restart container.

Can you please clarify your use-case ? "_Sometimes you need to test something, and you relaunch containers multiple times_" - right, but why would you remove the container as you relaunch, while `compose up` does manage this for you?

**Comment by Mikhail2048** [comment]
Yes, but `docker-compose` accepts only one service to run AFIAK. The `docker-compose run` is a pretty good approach, but I have 3 external components needed to perform E2E test. It seems I can work around this with `depends_on`, but that is kind of a hack seems my rabbitmq is not really somehow dependent on postgres container.

**Comment by ndeloof** [comment]
Your should indeed run e2e test using `docker compose run` and use `depends_on` to make it explicit the service being required for the test to run.

We also could expose the `AutoRemote` attribute in compose.yaml, as this is an [engine API parameter](https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerCreate)

**Comment by ndeloof** [comment]
closing as obsolete. If you encounter a comparable issue, please create a fresh new one with details on your environment
