### ISSUE TITLE
docker compose pull should respect --profile

### ISSUE THREAD

**Issue by robertlagrant** [docker/compose#10684]
### Description

The following command:
```bash
docker compose --profile my_profile pull
```

Should only pull images related to services that that profile `my_profile`.

**Comment by glours** [comment]
Hey @robertlagrant 
According to [definition of profiles](https://github.com/compose-spec/compose-spec/blob/master/spec.md#profiles) in the Compose Specification, using the `my_profile` will apply the command to services tagged with this profile and services without any profiles
>Services without a profiles attribute set MUST always be enabled

**Comment by ndeloof** [comment]
I'm closing this issue as "work as documented". 
`--profile` is used to enable _additional_  services defined by compose file, those without a profile assignment are always included

**Comment by robertlagrant** [comment]
@glours ah! Thank you. I didn't register that.
