### ISSUE TITLE
add --no-attach option to the docker-compose.yml config 

### ISSUE THREAD

**Issue by iwm911** [docker/compose#10695]
### Description

When creating a docker-compose.yml with verbose containers (like rabbitmq) the screen is swamped with verbose logging from that service.

i am now using the --no-attach to disable that logging to stdout, however it would be wonderful if it would be possible to set it at the service level in the docker-compose.yml file instead of manually write it every run.

thanks!

**Comment by CoenraadS** [comment]
Is there an example of how to use this?

**Comment by 0xMuTwo** [comment]
Hi, is there a way to do this now? Even looking at the PR it's not clear how to do this

**Comment by iwm911** [comment]
Just attach this to the compose file

attach: false

**Comment by 0xMuTwo** [comment]
This worked perfectly, thanks so much!

Sent via Superhuman ( ***@***.*** )
