### ISSUE TITLE
Provide "master" builds on master.dockerproject.com

### ISSUE THREAD

**Issue by thaJeztah** [docker/compose#1070]
This is a continuation on https://github.com/docker/compose/pull/730#issuecomment-77418324

It would be really useful if pre-build binaries of docker-compose are added to https://master.dockerproject.com. This would enable people to download a working version of the latest version for testing if they like "living on the edge".

Also useful to confirm if an issue is resolved ("could you download the latest master to check if the issue is resolved?")

**Comment by dnephin** [comment]
I'd like to do this.

**Comment by dnephin** [comment]
Master builds are now available at  https://dl.bintray.com/docker-compose/master/

**Comment by thaJeztah** [comment]
Thanks @dnephin !

**Comment by schmunk42** [comment]
@dnephin @thaJeztah These builds seem outdated, I just got `1.9.0dev` - you should remove or update them.

**Comment by dnephin** [comment]
If I remember correctly bintray has a weird thing where it doesn't let you push updated to a version after 6 months of the original publishing date. I went in an clicked "update version" on all the master versions, so maybe it will start working now after the next commit to master.

cc @shin-  next time you merge something mind pinging me and we can check to see if this worked?

**Comment by schmunk42** [comment]
@dnephin @shin- That would be great. Btw: Would it also be possible to build binaries on/from the Docker images. My Python knowledge is pretty limited, with Go it seems no problem.

**Comment by dnephin** [comment]
not sure what you mean

**Comment by schmunk42** [comment]
I would like to use these tools on a Docker image, so a static binary would be preferred.

For the Docker CLI I can use a multi-stage build, like so:

```
FROM docker:17.09-rc as docker
FROM dmstr/roj:0.4.0-rc1
COPY --from=docker /usr/local/bin/docker /opt/local/bin/docker
```

I tried this with `docker-compose` also, but there are much more dependencies (on the image which can be build from this repo).

**Comment by Iristyle** [comment]
Linux and Darwin are great... 

Windows would be even better if possible.


Thanks!
