### ISSUE TITLE
[BUG] Docker compose hangs forever on starting containers

### ISSUE THREAD

**Issue by mixmind** [docker/compose#10707]
### Description

I have a compose with number of services. If all services started as expected, then everything works fine. 
If one of services that other services depends on him failed, all process hangs forever and ctrl+c doesn't help

### Steps To Reproduce

Here is docker compose with problem..
using command:
docker compose up -d
```---
version: '3.7'

services:
  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    depends_on:
      flyway:
        condition: service_completed_successfully

  flyway:
    image: flyway/flyway
    container_name: flyway
    #command: "exit 1"`
```

### Compose Version

```Text
Docker Compose version v2.18.1
Docker Compose version v2.17.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 13
  Running: 10
  Paused: 0
  Stopped: 3
 Images: 41
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-42-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.54GiB
 Name: home-pc
 ID: e3a5bfab-9c94-45c0-a155-7e03090b7e82
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
I tried to reproduce with simplified config:
```yaml
services:
  reverse-proxy:
    image: nginx
    depends_on:
      flyway:
        condition: service_completed_successfully

  flyway:
    image: alpine
    command: /bin/false
```

and get the desired behavior:
```
$ docker compose up -d
[+] Running 2/2
 ✔ Container truc-flyway-1  Exited                                         0.7s 
 ✔ Container reverse-proxy  Created                                        0.0s 
service "flyway" didn't complete successfully: exit 1
```

**Comment by mixmind** [comment]
> flyway/flyway



> I tried to reproduce with simplified config:
> 
> ```yaml
> services:
>   reverse-proxy:
>     image: nginx
>     depends_on:
>       flyway:
>         condition: service_completed_successfully
> 
>   flyway:
>     image: alpine
>     command: /bin/false
> ```
> 
> and get the desired behavior:
> 
> ```
> $ docker compose up -d
> [+] Running 2/2
>  ✔ Container truc-flyway-1  Exited                                         0.7s 
>  ✔ Container reverse-proxy  Created                                        0.0s 
> service "flyway" didn't complete successfully: exit 1
> ```

it appears that it stucks when container name is provided, i took you example, added to it container name and it's stuck

```
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    depends_on:
      flyway:
        condition: service_completed_successfully

  flyway:
    container_name: flyway
    image: alpine
    command: /bin/false
```



![image](https://github.com/docker/compose/assets/33128809/902d23a0-b5c0-476e-9e01-123509e6bd18)

<details>
  <summary>nginx</summary>
docker inspect a30779cd8b51
[
    {
        "Id": "a30779cd8b51b5f8ae22ac17cc85808cf15fa7aa9a0b2288257c5b0763a9a9bb",
        "Created": "2023-06-14T19:59:31.268302934Z",
        "Path": "/docker-entrypoint.sh",
        "Args": [
            "nginx",
            "-g",
            "daemon off;"
        ],
        "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:7d3c40f240e18f6b440bf06b1dfd8a9c48a49c1dfe3400772c3b378739cbdc47",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "",
        "Name": "/installer-reverse-proxy-1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "installer_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/1edf0cf6f7f8feaf4ba11e449bf627ce75b14e07602c80d57538abd7f810242e-init/diff:/var/lib/docker/overlay2/ddbc0fa8dd9d2f152e384ef159e2c80c9fbacbb76cd389810ef6fffba07bb8cd/diff:/var/lib/docker/overlay2/ea93afdc8e014ecdb269f88cb49c880cd85d8c2cc785a750ecefe14fb223be97/diff:/var/lib/docker/overlay2/425b176ae69d66691b25e241185188a727eaaeaa6b45dc3898d59c592713e90c/diff:/var/lib/docker/overlay2/804763b6415b9f155802e9c8bac8941770beea1aac9114bf7cc535e468a8fc78/diff:/var/lib/docker/overlay2/4f566e7c70c4bec33c0366ae10fee23f98910f07a3e5bbd17631c546f9f37c22/diff:/var/lib/docker/overlay2/6400bd3e20ee357bbec44e66b10c3ca3f93469ba10787c85451326ab4f638cbe/diff",
                "MergedDir": "/var/lib/docker/overlay2/1edf0cf6f7f8feaf4ba11e449bf627ce75b14e07602c80d57538abd7f810242e/merged",
                "UpperDir": "/var/lib/docker/overlay2/1edf0cf6f7f8feaf4ba11e449bf627ce75b14e07602c80d57538abd7f810242e/diff",
                "WorkDir": "/var/lib/docker/overlay2/1edf0cf6f7f8feaf4ba11e449bf627ce75b14e07602c80d57538abd7f810242e/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "a30779cd8b51",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.25.0",
                "NJS_VERSION=0.7.12",
                "PKG_RELEASE=1~bullseye"
            ],
            "Cmd": [
                "nginx",
                "-g",
                "daemon off;"
            ],
            "Image": "nginx",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "3184b9cabf1bdd58a1be1fee461747ad21bb6f1e2274488b9ec60e386018bbef",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "flyway:service_completed_successfully:false",
                "com.docker.compose.image": "sha256:7d3c40f240e18f6b440bf06b1dfd8a9c48a49c1dfe3400772c3b378739cbdc47",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "installer",
                "com.docker.compose.project.config_files": "/home/reuven/work/installer/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/reuven/work/installer",
                "com.docker.compose.replace": "8618f8e678205d9d77404827c84febfeb5fcb61a8912559359782b7ce35bf6f4",
                "com.docker.compose.service": "reverse-proxy",
                "com.docker.compose.version": "2.18.1",
                "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>"
            },
            "StopSignal": "SIGQUIT"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "installer_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "installer-reverse-proxy-1",
                        "reverse-proxy",
                        "a30779cd8b51"
                    ],
                    "NetworkID": "",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
</details>


<details>
  <summary>alpine</summary>
docker inspect a30779cd8b51
[
    {
        "Id": "c1ed3af1cc72a8201422747df5b84ca20d68b313cfd682a7534c88fb14511103",
        "Created": "2023-06-14T20:00:27.528884739Z",
        "Path": "/bin/sh",
        "Args": [],
        "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:5e2b554c1c45d22c9d1aa836828828e320a26011b76c08631ac896cbc3625e3e",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "",
        "Name": "/0f949fda97d5_flyway",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "installer_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/3d460e3e45f53741082317a535cc52673de66ecec99a7b59c1dd8343e79a6bc6-init/diff:/var/lib/docker/overlay2/06f46ea36dcc9f24acceff2392c7f1525ca9aa13a8adc6dbaa52ed0ba9890f57/diff",
                "MergedDir": "/var/lib/docker/overlay2/3d460e3e45f53741082317a535cc52673de66ecec99a7b59c1dd8343e79a6bc6/merged",
                "UpperDir": "/var/lib/docker/overlay2/3d460e3e45f53741082317a535cc52673de66ecec99a7b59c1dd8343e79a6bc6/diff",
                "WorkDir": "/var/lib/docker/overlay2/3d460e3e45f53741082317a535cc52673de66ecec99a7b59c1dd8343e79a6bc6/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "c1ed3af1cc72",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh"
            ],
            "Image": "alpine",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "036379e87c289a9a89e732f484b335dbeeb0785aca33fc9d5a09e7cc2905c811",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:5e2b554c1c45d22c9d1aa836828828e320a26011b76c08631ac896cbc3625e3e",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "installer",
                "com.docker.compose.project.config_files": "/home/reuven/work/installer/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/reuven/work/installer",
                "com.docker.compose.replace": "0f949fda97d5f67ec68c7d39b8ff13957026f620b89cba7bc9e3c2c0e2594bb0",
                "com.docker.compose.service": "flyway",
                "com.docker.compose.version": "2.18.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "installer_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "flyway",
                        "flyway",
                        "c1ed3af1cc72"
                    ],
                    "NetworkID": "",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
</details>

**Comment by ndeloof** [comment]
Tried with `container_name` as suggested but still can't reproduce, either from scratch or after a previous run:
```
$ docker compose up -d
[+] Running 2/2
 ✔ Container flyway         Exited                                                                                                0.7s 
 ✔ Container reverse-proxy  Created                                                                                               0.0s 
service "flyway" didn't complete successfully: exit 1
 $ docker compose up -d
[+] Running 1/1
 ✔ Container flyway  Exited                                                                                                       0.7s 
service "flyway" didn't complete successfully: exit 1
```

There alpine container you inspected "0f949fda97d5_flyway" is not the one which exited. Seems you have some orphaned container, which might explain compose get confused here.

could you check with `docker ps -a` about obsolete container being left around ? Then please capture command output to help me diagnose this, and remove them to confirm this would fix this issue

**Comment by ndeloof** [comment]
AFAICT the issue here is that you got this replacement container created after a configuration change in your compose.yaml file, but command didn't completed and it was left with this temporary name "<random>_flyway" in `created` state. This confuses the `service_completed_successfully` logic as this container obviously will never complete as it didn't even started. Compose should better handle such a scenario

**Comment by mixmind** [comment]
Hi, you are right my examples started to work after removing dangling containers. 
I have succeeded in creating 100% sure failing compose file:

```
version: "3.7"
services:
  nginx1:
    container_name: nginx1
    depends_on:
    - nats1
    - backend1
    image: nginx
    restart: always
  nats1:
    container_name: nats1
    image: nats
    restart: always
  backend1:
    container_name: backend1
    command: tail -f /dev/null
    depends_on:
      flyway1:
        condition: service_completed_successfully
    image: alpine
    restart: always
  flyway1:
    command: /bin/false
    container_name: flyway1
    depends_on:
     db1:
       condition: service_healthy
    image: alpine
  db1:
    container_name: db1
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 10s
      test:
      - CMD-SHELL
      - pg_isready -h 127.0.0.1
      timeout: 5s
    image: postgres
    restart: always
```
![Screenshot from 2023-06-17 00-55-14](https://github.com/docker/compose/assets/33128809/658e8d47-7433-4c4b-9b90-40237b419af8)
![Screenshot from 2023-06-17 00-54-50](https://github.com/docker/compose/assets/33128809/06d028d1-7a07-449b-a6bd-922719ae69c7)

Please update me if you need additional information

**Comment by ndeloof** [comment]
I was able to reproduce with provided example, thanks !
I'll investigate this issue tomorrow
