### ISSUE TITLE
PhpStorm and Docker - Unable to configure the Remote PHP interpreter (Failed to parse script validation output)

### ISSUE THREAD

**Issue by minalsharma888** [docker/compose#10716]
### Description

I'm using Docker composer with a PHP. When trying to set the interpreter I choose Docker compose and connecting with existing container and then it fails with the error "Failed to parse script validation output".

If I execute php -v inside the container everything seems fine,

What is the expected result? An installed php version should be shown

What happens instead? Failed to parse validation script output message and PHP version: not installed label

It's working fine with docker-compose run lifecycle

PS:
OS : RHEL 8.8
PhpStorm 2023.1.2

Docker version 24.0.2, build cb74dfc

Settings > Build, Execution, Deployment > Docker > Tools and checking the box "Use Compose V2" didn't work for me.

Getting below error in ide.log

2023-06-15 11:30:07,860 [1825374] FINE - #c.j.p.c.p.PhpInfoUtil - Parsing validation output: Could not open input file: /opt/.phpstorm_helpers/phpinfo.php

2023-06-15 11:30:07,861 [1825375] INFO - STDERR - [Fatal Error] :1:1: Content is not allowed in prolog.

2023-06-15 11:30:07,861 [1825375] WARN - #c.j.p.c.p.PhpInfoUtil - Failed to parse validation output: Could not open input file: /opt/.phpstorm_helpers/phpinfo.php

2023-06-15 11:30:07,862 [1825376] FINE - #c.j.p.c.p.PhpInfoUtil -

com.intellij.execution.ExecutionException: Failed to parse validation script output

### Compose Version

```Text
Docker Compose version v2.18.1

docker-compose version 1.24.0, build 0aa59064

docker-py version: 3.7.2

CPython version: 3.6.8

OpenSSL version: OpenSSL 1.1.0j 20 Nov 2018
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 8
  Running: 7
  Paused: 0
  Stopped: 1
 Images: 20
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-477.13.1.el8_8.x86_64
 Operating System: Red Hat Enterprise Linux 8.8 (Ootpa)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.9GiB
 Name: minsharm.remote.csb
 ID: SKTX:7YZV:OE7K:NBZO:HWEF:B7IQ:5FOY:Q62R:FXID:NULH:TJSP:7XSM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

![image](https://github.com/docker/compose/assets/31561385/49da2860-34f0-4924-8514-a9aced3621a9)

**Comment by glours** [comment]
Hello @minalsharma888 
It doesn't seem to be a Compose issue but more a PHPStorm with DDev configuration one. 
Did you try to use the [DDev PHPStorm plugin](https://plugins.jetbrains.com/plugin/18813-ddev-integration) and follow [this guide](https://ddev.readthedocs.io/en/latest/users/install/phpstorm/#manual-setup)?

**Comment by rfay** [comment]
@minalsharma888 you've opened the same issue in at least 5 different places. If you're going to do that, at least cross-reference them. But it's going to be either PhpStorm or the extension, most likely PhpStorm.
