### ISSUE TITLE
[BUG] Compose hangs indefinitely when build of a dependency dies

### ISSUE THREAD

**Issue by Regrau** [docker/compose#10718]
### Description

The docker compose output is stuck and can't be closed with Ctrl+C when the build of a dependency container fails.
Killing the docker compose process from an outside shell seems to be the only workaround

### Steps To Reproduce

For convenience sake, here's a repos with both files

https://github.com/Regrau/docker-compose-bug-report

```bash
git clone https://github.com/Regrau/docker-compose-bug-report && cd docker-compose-bug-report
docker compose up -d --build
```

### docker-compose.yml
```yaml
services:
  web:
    image: busybox
    command: tail -f /dev/null
    depends_on:
      - db
  db:
    container_name: test
    build:
      dockerfile: Dockerfile
      context: .
```

### Dockerfile
```Dockerfile
FROM alpine:3.17

RUN exit 1

CMD [ "echo", "hello" ]
```

### Compose Version

```Text
Docker Compose version 2.18.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    colima
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.18.1
    Path:     /Users/regrau/.docker/cli-plugins/docker-compose

Server:
 Containers: 15
  Running: 10
  Paused: 0
  Stopped: 5
 Images: 15
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc version: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 init version: 
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 6.1.29-0-virt
 Operating System: Alpine Linux v3.18
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.754GiB
 Name: colima
 ID: 1956e4ba-3df0-4b39-bce9-a04a0473cb57
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by RealAlphabet** [comment]
It's incredible that this bug still hasn't been fixed, I've had this problem on several of my machines for several weeks now, even after a clean reinstall. It's not as if Docker isn't used by a huge number of developers and companies...

**Comment by ndeloof** [comment]
@RealAlphabet why didn't you reported this issue earlier then ?
@Regrau AFAICT this is fixed by https://github.com/docker/compose/pull/10725, can you please build binary from this PR (`make install`)  to confirm ?

**Comment by RealAlphabet** [comment]
I must have deleted part of my message before sending it. I first encountered the problem 1 week ago. Someone had already reported the problem in the Github issues at the time.

What I wanted to say is that I downgraded Docker to `v23.0` (released in February according to the Docker site) and was able to reproduce the problem on bare metal after a fresh install of Debian 11. This proves that the problem has existed for at least several months now.

**Comment by ndeloof** [comment]
That's indeed surprising nobody reported this before. Would you have a chance to confirm https://github.com/docker/compose/pull/10725 fix this ?

**Comment by fho** [comment]
> That's indeed surprising nobody reported this before. Would you have a chance to confirm #10725 fix this ?

It is the same then https://github.com/docker/compose/issues/10648

**Comment by RealAlphabet** [comment]
> That's indeed surprising nobody reported this before. Would you have a chance to confirm #10725 fix this ?

I tried to do this as soon as you replied, but unfortunately I don't have enough disk space to build at the moment. I'll try again as soon as I have access to another machine (in approximately 2-4 hours).
