### ISSUE TITLE
stop all container when stop one container

### ISSUE THREAD

**Issue by zhucegep** [docker/compose#1072]
I create a group serive containers by use docker-compose.
doker-compose will stop all container of this group when I use `docker stop onecontainer` to stop one container.
Here is two way to prevent it,run docker-compose up with `-d` or close the windows whick run docker-compose up.
Is a bug?

**Comment by dnephin** [comment]
Use `docker-compose up -d`, see #741

**Comment by dnephin** [comment]
Fixed by #1754
