### ISSUE TITLE
docker-compose sporadically complains FileNotFoundException for System.Memory

### ISSUE THREAD

**Issue by RaviNowal** [docker/compose#10732]
### Description

In our CD pipeline which is built in Azure, we are experiencing a sporadic issue where docker pull of an image followed by the docker-compose, throws a FileNotFound exception as shown below:

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Memory, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 0x80070002
File name: 'System.Memory, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.Extensions.Logging.LogValuesFormatter..ctor(String format)
   at Microsoft.Extensions.Logging.FormattedLogValues.<>c.<.ctor>b__9_0(String f)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.Logging.FormattedLogValues..ctor(String format, Object[] values)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   
  Interestingly when the DevOps pipeline step is re-executed for the same image, the step passes. The image is made from a service made out of .NET6.0 based ASP.Net project and is used as a microservice.

Mostly, the issue does not come. But it comes sporadically. We do not know why.

### Compose Version

```Text
Docker version: 3.5.2(66501)
Compose version: 1.29.2
```

**Comment by milas** [comment]
With the information you've given, there's no indication this is a bug in Compose.

If the container is running and your code is throwing an exception in .NET, that's not really something I can help with.

Additionally, Compose v1 is EOL, and Docker Desktop v3.5.2 is nearly 2 years old, so I'm unable to provide support for either of those.

If you can provide steps to reproduce this on the latest version of Compose and Docker Desktop, please create a new issue with more details.
