### ISSUE TITLE
[BUG] Parallel build deadlock when using COMPOSE_PARALLEL_LIMIT  or --parallel flag

### ISSUE THREAD

**Issue by abdalem** [docker/compose#10735]
### Description

Hi everyone !

I have a docker-compose file that describe around 20 services and I wanted to limit parallel build to avoir memory limit (using wsl and have limited it to 6Go). But when I set either COMPOSE_PARALLEL_LIMIT or --parallel flag, it stuck randomly. My only workaround was using another buildx builder but I would like to avoid other developers on the team to manipulate docker config.

### Steps To Reproduce
Perfom a `COMPOSE_PARALLEL_LIMIT=3 docker compose build` on a file having a lot of services to build

### Compose Version
2.18.1

### Docker Environment
Docker Desktop 4.20.1 with Docker at version 24.0.2 working on WSL2

```[tasklist]
### Tasks
```

**Comment by erlangparasu** [comment]
got same issue
