### ISSUE TITLE
feature request: locking when two Compose commands are run in parallel

### ISSUE THREAD

**Issue by nicks** [docker/compose#10754]
### Description

# Background

I often run tools that schedule a bunch of Compose CLI runs in the background.

Sometimes these CLI runs end up running two Compose commands at the same time. They then fail with cryptic concurrency errors, like:

```
Error response from daemon: Conflict. The container name "/avatars-nicks-cuts-api-pause-1" is already in use by container "fab823f518a38fcdda50b0d5f37f4bc64783688e3abb734cae1bc313b544f2c3". You have to remove (or rename) that container to be able to reuse that name.
```

because of the time gap between the when Compose makes a plan, and when it applies its changes.

# Proposal

Other tools that make changes to shared state use file locking to prevent this class of error. For example, Helm uses the `flock` library to prevent two CLI calls from updating the repo store at the same time. For more details on this approach, see:

https://github.com/helm/helm/blob/main/cmd/helm/repo_add.go#L125

Maybe Compose could use a similar approach, so only one Compose process is making changes to a project at a time?

**Comment by laurazard** [comment]
I'm not opposed (and I think it's a positive for resiliency regardless), but I do wonder if the need to run multiple Compose commands, concurrently, on the same project, isn't a smell that there's missing functionality within Compose that should be handled by adding support for whatever functionality is required for that usecase as opposed to just "fixing the symptom".
