### ISSUE TITLE
`compose run` port-binding semantics are confusing

### ISSUE THREAD

**Issue by milas** [docker/compose#10750]
### Description

When using `compose run`, port bindings are ignored.

It's also not clear how the `-p` flag should be used here:

> But even that doesn't seem to work the same way it does in `docker run` I assumed this is the cli option to use to publish ports
> ```
>  -p, --publish stringArray   Publish a container's port(s) to the host.
> ```
> So I tried spinning out a repos DB
> ```
> docker compose -f docker-compose.yml run repos-db -p 5433:5432
> ...
> 2023-06-28 16:18:58.485 GMT [32] FATAL:  invalid value for parameter "port": "5433:5432"
> ```
> So I figured ok maybe it automatically publishes exposed port to the specified value
> ```
>  docker compose -f docker-compose.yml run repos-db -p 5433
> ```
> Hmm
> ```
> $ telnet localhost 5433
> Trying 127.0.0.1...
> telnet: connect to address 127.0.0.1: Connection refused
> telnet: Unable to connect to remote host
> ```
> It turns out that option overrides the exposed port? 🫠
> ```
> 2023-06-28 16:19:27.076 UTC [1] LOG:  starting PostgreSQL 13.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
> 2023-06-28 16:19:27.076 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5433
> 2023-06-28 16:19:27.076 UTC [1] LOG:  listening on IPv6 address "::", port 5433
> ```
> And
> ```
> $ docker exec -it 4fb819306f47 /bin/bash
> 4fb819306f47:/# ps
> PID   USER     TIME  COMMAND
>     1 postgres  0:00 postgres -p 5433
>    54 postgres  0:00 postgres: checkpointer
>    55 postgres  0:00 postgres: background writer
>    56 postgres  0:00 postgres: walwriter
>    57 postgres  0:00 postgres: autovacuum launcher
>    58 postgres  0:00 postgres: stats collector
>    59 postgres  0:00 postgres: logical replication launcher
>    81 root      0:00 /bin/bash
>    87 root      0:00 ps
> 4fb819306f47:/#
> ```
> This isn't what I'd expect from -p :thinking_face: if run is supposed to behave the way docker run is 🤔 

We should look at:
 * What are the desired semantics here?
   * Are there more than ports that don't get used for `compose run`?
 * How can we improve the CLI help/docs?

**Comment by ndeloof** [comment]
related: https://github.com/docker/compose/pull/11227

**Comment by ndeloof** [comment]
> docker compose -f docker-compose.yml run repos-db -p 5433:5432
...
2023-06-28 16:18:58.485 GMT [32] FATAL:  invalid value for parameter "port": "5433:5432"

That's weird as this is the desired usage. `docker  compose run -p` is just the exact same as `docker run -p`:
```
$ docker compose run -d -p 8080:80 test
32e43d43adce26ec403061b92bdced18323ee5c941b0610dbb8472bdc678e1e2
$ curl localhost:8080 
<!DOCTYPE html>
...
```
```
