### ISSUE TITLE
docker compose error  when using podman secrets 

### ISSUE THREAD

**Issue by reutsit** [docker/compose#10775]
### Description

am using :

- CentOS 8
- Docker Compose v2.19.0
- yml version: 3.8
- podman version:
- Client: Podman Engine Version: 4.3.1
- API Version: 4.3.1
- Go Version: go1.19.4
- Built: Tue Jan 31 22:06:15 2023
- OS/Arch: linux/amd64

### Steps To Reproduce

First in shell script, I create the secret with **podman secret create**
then I try to use it inside the docker-compose.yml. 
when I try to run docker-compose up, I get the following error:
Error response from daemon: runc: runc create failed: unable to start container process: 
error during container init: error mounting "/var/lib/some-dir/tmp/secret_name.sec" 
to rootfs at "/run/secrets/secret_name": 
open /var/lib/containers/storage/overlay/b3eaa7599a7376c1c989bd7861859db208cbfb962d274bb640accfe62e7185a0/merged/run/secrets/secret_name: 
read-only file system: OCI runtime error

### Compose Version

```Text
Docker Compose v2.19.0
```

### Docker Environment

```Text
no docker info .
only podman 
- podman version:
- Client: Podman Engine Version: 4.3.1
- API Version: 4.3.1
- Go Version: go1.19.4
- Built: Tue Jan 31 22:06:15 2023
- OS/Arch: linux/amd64
```

**Comment by ndeloof** [comment]
This is expected: Docker compose does not support podman or swarm secrets.
Closing this issue as "won't fix"
