### ISSUE TITLE
Not able to create VM on Windows 7

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#1078]
Downloaded Virtual Box 4.3.24 and Docker Machine 0.1.1. Creating a machine on Windows 7 just hangs with the following message:

C:\Users\Arun Gupta>.\Downloads\docker-machine_windows-amd64.exe create --driver virtualbox dev
←[34mINFO←[0m[0000] Creating CA: C:\Users\Arun Gupta\.docker\machine\certs\ca.pem
←[34mINFO←[0m[0000] Creating client certificate: C:\Users\Arun Gupta\.docker\machine\certs
\cert.pem
←[34mINFO←[0m[0002] Downloading boot2docker.iso to C:\Users\Arun Gupta\.docker\machine\cac
he\boot2docker.iso...
←[34mINFO←[0m[0017] Creating SSH key...
←[34mINFO←[0m[0018] Creating VirtualBox VM...
←[34mINFO←[0m[0083] Starting VirtualBox VM...
←[34mINFO←[0m[0087] Waiting for VM to start...

Virtual Box UI shows the VM is running.

How to debug further?

**Comment by dnephin** [comment]
I think you have the wrong project. This is docker-compose  you want https://github.com/docker/machine

**Comment by arun-gupta** [comment]
Silly, filed correctly!
