### ISSUE TITLE
[BUG] Ignored `mac_address` field

### ISSUE THREAD

**Issue by davidedellagiustina** [docker/compose#10796]
### Description

I have a `macvlan` network and a Docker container (deployed through `compose`) connected to it. I recently updated to `compose` V2, and since then the `mac_address` property of my container does not get applied anymore (it used to work fine before).

Compose file:
```yaml
version: '3.7'

services:
  blocky:
    container_name: blocky
    hostname: blocky
    restart: unless-stopped
    image: spx01/blocky:latest
    mac_address: 2c:4d:54:00:00:01 # MAC address specified here
    networks:
      macvlan:
        ipv4_address: ${BLOCKY_IP} # Env variable properly instantiated
    volumes:
      - ./config/config.yml:/app/config.yml:ro
      - /certificates/blocky/:/certs:ro
    environment:
      TZ: 'Europe/Rome'

networks:
  macvlan:
    external: true
```

Output of `docker inspect blocky` (only relevant parts):
```jsonc
[
    {
        "Config": {
            "MacAddress": "2c:4d:54:00:00:01" // Apparently it gets correctly parsed from the compose file
        },
        "NetworkSettings": {
            "MacAddress": "", // But then it does not get set
            "Networks": {
                "macvlan": {
                    "IPAMConfig": {
                        "IPv4Address": "192.168.1.224"
                    },
                    "Gateway": "192.168.0.1",
                    "IPAddress": "192.168.1.224",
                    "IPPrefixLen": 22,
                    "MacAddress": "02:42:c0:a8:01:e0" // And a random one is assigned
                }
            }
        }
    }
]
```

Output of `docker inspect macvlan` (only relevant parts):
```jsonc
[
    {
        "Name": "macvlan",
        "Scope": "local",
        "Driver": "macvlan",
        "Containers": {
            "23368919c7ccd73f64f02d7db560c256fd74c528c70e721b72f1d8e8660a384b": {
                "Name": "blocky",
                "EndpointID": "e5dc69402099d43938deafef3172a288abfe26cd2f31702595600f2d2252a8a8",
                "MacAddress": "02:42:c0:a8:01:e0", // Cusom MAC address is not applied
                "IPv4Address": "192.168.1.224/22" // (Even though IP is)
            }
        },
        "Options": {
            "macvlan_mode": "bridge",
            "parent": "enp0s31f6"
        }
    }
]
```

### Docker version
```
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:55 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:50:55 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker compose version
```
Docker Compose version v2.19.1
```

**Comment by simonmcnair** [comment]
![20230805_161834](https://github.com/docker/compose/assets/101189766/3773dc28-f3ca-4d19-87c4-eb2162be6a92)
![20230805_161904](https://github.com/docker/compose/assets/101189766/4b4a37df-8c7b-46d5-a958-c0dabee65d04)
I tried this and got the following.  Is it possible it is working ?  How do you know it isn't pls ?

**Comment by davidedellagiustina** [comment]
@simonmcnair My setup differs from yours (as far as I can see) in the following:
- I am using a macvlan network, while you seem to be using the default adapter in your container;
- I am using compose file version 3.8, while you are using version 2.1 (not sure this matters, though).

In your case it seems that the mac address gets assigned properly, while in my case both running `ip a` inside the container, and inspecting the docker network using `docker inspect <network_name>` reports a randomly assigned MAC address. In addition, notice that `docker inspect <container_name>` reports the correctly partes MAC in the `Config` section, while it is not reported in the `NetworkSettings` section. This makes me suspect that something inside compose is not reading the parsed configuration correctly, perhaps.

**Comment by simonmcnair** [comment]
Have you tried exactly the same thing without macvlan ?  I wonder if it is specific to that driver ?

**Comment by simonmcnair** [comment]
It would also be worth having your macvlan terminal lines to recreate at my end

**Comment by davidedellagiustina** [comment]
> Have you tried exactly the same thing without macvlan ? I wonder if it is specific to that driver ?

I was trying this exact thing right now and I confirm that the MAC address get correctly assigned if I use the default docker network driver.

**Comment by davidedellagiustina** [comment]
> It would also be worth having your macvlan terminal lines to recreate at my end

In order to create a macvlan network within Docker you can use the following:
```
docker network create -d macvlan \
    -o parent=<physical_interface_name> \
    -o macvlan_mode=bridge \
    --subnet=<subnet_cidr> \
    --gateway=<network_gateway_ip> \
    --ip-range=<containers_ip_range> \
    <network_name>
```
where:
- `<physical_interface_name>` is the name of your hardware network interface that the macvlan will be bound to;
- `<subnet_cidr>` is the CIDR of the network you're on;
- `<network_gateway_ip>` is the IP address of the gateway for your network;
- `<containers_ip_range>` is a subrange of `<subnet_cidr>` and is the addressing space you are reserving for the Docker containers;
- `<network_name>` is the name you want to give to the Docker network.

**Comment by ndeloof** [comment]
Can you run and connect a container to this network with expected mac address assigned using a plain `docker run --mac-address <xx> ...` command ?

**Comment by davidedellagiustina** [comment]
@ndeloof Apparently yes:
```
$> docker run --mac-address 2c:4d:54:00:00:01 --network macvlan --name test -it alpine
#> ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
17: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 2c:4d:54:00:00:01 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.226/22 brd 192.168.3.255 scope global eth0
       valid_lft forever preferred_lft forever
```

**Comment by brhahlen** [comment]
I'm running into the same issue with my macvlan network. Some containers have a "random" MAC address (which confused me when going through my network).

**Comment by brhahlen** [comment]
Did some tests, found out that when running docker compose version 2.18.1, the behaviour works as intended.
Compose version 2.19.1 doesn't work as expected either.

**Comment by brhahlen** [comment]
@davidedellagiustina Are you able to test with version 2.18.1 of `docker compose` to see if the behaviour works as intended there?

@ndeloof I can reliably reproduce the behaviour with version 2.18.1 (works correctly) and higher.

```$ docker compose version
Docker Compose version v2.19.1

$ docker compose config
services:
  emulatorjs:
    container_name: emulatorjs
[...]
   mac_address: 02:42:AC:11:21:81
   networks:
      lan_net:
        ipv4_address: 192.168.2.181
[...]
```
```
$ docker inspect --format='{{range .NetworkSettings.Networks}}{{.MacAddress}}{{end}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} - {{.Name}}' $(docker ps -aq) | sort -g
[...]
02:42:c0:a8:02:b5 - 192.168.2.181 - /emulatorjs
```
MAC Address does not match.

```
$ docker compose version
Docker Compose version v2.18.1
$ docker compose config
services:
  emulatorjs:
    container_name: emulatorjs
[...]
   mac_address: 02:42:AC:11:21:81
   networks:
      lan_net:
        ipv4_address: 192.168.2.181
[...]
```
```
$ docker inspect --format='{{range .NetworkSettings.Networks}}{{.MacAddress}}{{end}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} - {{.Name}}' $(docker ps -aq) | sort -g
[...]
02:42:ac:11:21:81 - 192.168.2.181 - /emulatorjs
[...]
```

**Comment by davidedellagiustina** [comment]
@brhahlen I confirm that I am able to reproduce what you observed, i.e. expected behavior with compose 2.18.1 and broken MAC with compose 2.19.0.

**Comment by lwmacct** [comment]
```
[root@localhost ~]# 
[root@localhost ~]# cat docker-compose.yaml 

version: "3"
networks:
  ikuai-lan1:
    name: ikuai
    external: true

services:
  nginx:
    image: nginx:latest
    mac_address: 02:42:ac:11:00:02
    networks:
      ikuai-lan1:
        ipv4_address: 192.168.100.103   
    volumes:
      - /data:/data
    entrypoint: ["/docker-entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]


```
```
[root@localhost ~]# 
[root@localhost ~]# docker inspect root-nginx-1 | jq '.[0].NetworkSettings.Networks'
{
  "ikuai": {
    "IPAMConfig": {
      "IPv4Address": "192.168.100.103"
    },
    "Links": null,
    "Aliases": [
      "root-nginx-1",
      "nginx",
      "2ee33548ec53"
    ],
    "NetworkID": "9cf30dfeb4830f36dad3e3bc4fb9746f2f79aa94fcb980194b4e740b0c0ae2c4",
    "EndpointID": "28bfd1bb4d6049383f4f47f8afafa90d6e679bcb0067cf9c10f5cd1564644b1f",
    "Gateway": "192.168.100.1",
    "IPAddress": "192.168.100.103",
    "IPPrefixLen": 24,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:c0:a8:64:67",
    "DriverOpts": null
  }
}

```

```
[root@localhost ~]# docker network  inspect ikuai | jq
[
  {
    "Name": "ikuai",
    "Id": "9cf30dfeb4830f36dad3e3bc4fb9746f2f79aa94fcb980194b4e740b0c0ae2c4",
    "Created": "2023-08-28T15:00:56.946872908+08:00",
    "Scope": "local",
    "Driver": "macvlan",
    "EnableIPv6": false,
    "IPAM": {
      "Driver": "default",
      "Options": {},
      "Config": [
        {
          "Subnet": "192.168.100.0/24",
          "Gateway": "192.168.100.1"
        }
      ]
    },
    "Internal": false,
    "Attachable": false,
    "Ingress": false,
    "ConfigFrom": {
      "Network": ""
    },
    "ConfigOnly": false,
    "Containers": {
      "0621d2ccd80db9ff8d1ee57a0a0024dc52f409c57cdc53ce50c94a9b4b27811d": {
        "Name": "node-ipes-101",
        "EndpointID": "6480cff3e57150cdd0bf2b6c31786410d090213220327399e64ded8d05065191",
        "MacAddress": "02:42:c0:a8:64:65",
        "IPv4Address": "192.168.100.101/24",
        "IPv6Address": ""
      },
      "2ee33548ec531c826a45e3c7b79e00fe67aa91974d9046ec30e3d7abf50a44c9": {
        "Name": "root-nginx-1",
        "EndpointID": "28bfd1bb4d6049383f4f47f8afafa90d6e679bcb0067cf9c10f5cd1564644b1f",
        "MacAddress": "02:42:c0:a8:64:67",
        "IPv4Address": "192.168.100.103/24",
        "IPv6Address": ""
      }
    },
    "Options": {
      "macvlan_mode": "bridge",
      "parent": "enp2s0f0"
    },
    "Labels": {}
  }
]

```

```
[root@localhost ~]# 
[root@localhost ~]# docker compose version
Docker Compose version v2.20.2
[root@localhost ~]# 
```

```
[root@localhost ~]# 
[root@localhost ~]# docker-compose -v
Docker Compose version v2.18.1
[root@localhost ~]# 
```
The lower version v2.18.1 works

**Comment by ndeloof** [comment]
I was able to reproduce this issue using a plain `docker run ...` command and found the root cause:
If container is created using network ID as reference (not name) to set ip/mac_address, it seems to be ignored by engine:

```
$ docker run --network ikuai --mac-address "02:42:ac:11:00:02" --ip "192.168.100.103" -d nginx
9a526c7bbaa05f6614b42348ea7b91821e8c437be2b741cb317b4a5c40d2de92
$ docker inspect 9a | jq '.[] | .NetworkSettings.Networks | .[].MacAddress '
"02:42:ac:11:00:02"

$ docker run --network ikuai --mac-address "02:42:ac:11:00:02" --ip "192.168.100.103" -d nginx
2080db34c6703a73a8b306c1df774646fdeb6c7a3f66ca5934ccad9a7365fb8f
$ docker inspect 20 | jq '.[] | .NetworkSettings.Networks | .[].MacAddress '
"02:42:c0:a8:64:67"
 ```

The reason we use network IDs is that network name is not guaranteed to be unique (see https://github.com/docker/compose/pull/10612).

**Comment by brhahlen** [comment]
Thanks @ndeloof !

**Comment by dkrasnove** [comment]
Also wanted to report that I am experiencing the same issue. I am using https://github.com/devplayer0/docker-net-dhcp to assign IPs to my containers via DHCP and static MAC/IP mappings. After upgrading to compose v2.20.2, the mac_address option is no longer respected and consequently my containers are no longer leasing the correct IP.

**Comment by NonaSuomy** [comment]
@dkrasnove 
> Also wanted to report that I am experiencing the same issue. I am using https://github.com/devplayer0/docker-net-dhcp to assign IPs to my containers via DHCP and static MAC/IP mappings. After upgrading to compose v2.20.2, the mac_address option is no longer respected and consequently my containers are no longer leasing the correct IP.

Did you get it working? I use the same plug-in and it is now working for me after compiling moby and replacing the dockerd.

**Comment by dkrasnove** [comment]
@NonaSuomy I decided to migrate away from the plugin. I'm worried due to it's unsupported nature and lack of ongoing development that it will break in the future. I migrated away from DHCP for my containers and am now directly using macvlan with static assignment.

**Comment by NonaSuomy** [comment]
> @NonaSuomy I decided to migrate away from the plugin. I'm worried due to its unsupported nature and lack of ongoing development that it will break in the future. I migrated away from DHCP for my containers and am now directly using macvlan with static assignment.

I wish Docker took over the plugin and encompassed it in the project as the other solutions don't provide the same freedom. I currently could not function properly without it.

"Each Macvlan Bridge mode Docker network is isolated from one another and there can be only one network attached to a parent interface at a time. There is a theoretical limit of 4,094 sub-interfaces per host adapter that a Docker network could be attached to. The driver limits one network per parent interface." :(

I'm sticking with it until it explodes as there is nothing like it. I don't want to give up DNSMasq controlling all my docker's network interfaces. It is extremely convenient not to have to worry about dockers network getting in the way of communications between services.

**Comment by gymnae** [comment]
I’m also using that plugin and facing the same issue due to nightly reboots of my rolling release distribution.
There only work around I see is rebuilding there containers on every boot

**Comment by gymnae** [comment]
> @NonaSuomy I decided to migrate away from the plugin. I'm worried due to its unsupported nature and lack of ongoing development that it will break in the future. I migrated away from DHCP for my containers and am now directly using macvlan with static assignment.

How do you manage full static assignment with macvlan? As I understand docker still runs an dhcp and assigns an IP address

**Comment by dkrasnove** [comment]
> How do you manage full static assignment with macvlan? As I understand docker still runs an dhcp and assigns an IP address

IIRC, I just limited the IP range to the specific address I wanted.

**Comment by clauderobi** [comment]
I just upgraded my Rocky Linux 9.1 to docker compose v2.28.1. Previously, I think it was at v2.18.something. Before the upgrade, the mac_address defined in my compose file were honored. But not anymore.

I am not using macvlan, just the good old bridge.
