### ISSUE TITLE
Proposal on Fig and Docker Compose transition

### ISSUE THREAD

**Issue by iMerica** [docker/compose#1079]
Hey guys,

The [Fig CLI reference](http://www.fig.sh/cli.html) has a deprecation warning and points users to Docker Compose. The Docker compose repo has had a failing status on Wercker for some time. I totally get it and this isn't a problem (it's open source software and under development currently). Would it better to not declare Fig as deprecated until Docker Compose has a consistent green streak on Wercker? To the outside world (people not using Compose or Fig) both options appear unstable - which they're not. This matters because it would be a shame for people to survey Fig and Compose, see the status of both and decide to roll their own Docker abstraction when this one is so good. Or worse not use Docker for a local development environment at all because the tools appear unready. Anyway, thanks for everything. This is one of my favorite pieces of software at the moment.

Michael

**Comment by munhitsu** [comment]
:+1:

**Comment by dnephin** [comment]
I think the build is more stable now that it's running on jenkins
