### ISSUE TITLE
Any chance to get  system load based auto scaling in docker compose?

### ISSUE THREAD

**Issue by ghevge** [docker/compose#10822]
### Description

Any chance to get system load based auto scaling (similar to what kubernetes is offering ) in docker compose?

The scaling boudaries should be configurable through the docker-compose.yaml.  The scaling should be done vertically (and in the uture why not horisontally accross multiple cluster nodes) based on the system load and/or any other criterias envisioned 

IMO such a functionality will increase the docker-compose addoption as a production tool, especially for startups and small entities, as docker compose is much lighter and easier to maintain than  kubernetes .

**Comment by milas** [comment]
This would require support in the Docker Engine.

There are a couple relevant issues there:
 * https://github.com/moby/moby/issues/32054
 * https://github.com/moby/moby/issues/26259

Unfortunately, this would not be possible to add in Compose without support there.
