### ISSUE TITLE
[BUG] No module named 'websocket' on command docker-compose

### ISSUE THREAD

**Issue by nonathecoda** [docker/compose#10832]
### Description

Very similar to: https://github.com/docker/compose/issues/8574, however, this solution didn't work for me.

### Steps To Reproduce

Whenever I run docker-compose, I get the following output:

Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/main.py", line 14, in <module>
    import docker.errors
  File "/usr/local/lib/python3.8/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.8/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 8, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'

### Compose Version

```Text
docker compose version
docker: 'compose' is not a docker command.
See 'docker --help'

docker-compose version
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.8/dist-packages/compose/cli/main.py", line 14, in <module>
    import docker.errors
  File "/usr/local/lib/python3.8/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.8/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 8, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'
```

### Docker Environment

```Text
docker info
Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info



sudo docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 17
 Server Version: 20.10.24
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-73-generic
 Operating System: Ubuntu Core 22
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 31.27GiB
 Name: xxx
 ID: xxx
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by glours** [comment]
When you look at the log produce by `docker info`, you could notice the following error:
```
Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
```
It's look like you have a configuration issue with your Docker engine, maybe following [this doc](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) could help you

**Comment by milas** [comment]
The `websocket` error is from Compose v1, which we don't support anymore. I'm also not sure how you installed it, so can't really help fix it regardless.

Compose v2 comes with Docker Engine if you install via our official apt/yum repositories: https://docs.docker.com/engine/install/ (if not auto-installed, look for the `docker-compose-plugin` package).

We also have docs specifically on installing Compose v2: https://docs.docker.com/compose/install/
