### ISSUE TITLE
Make secrets available on docker-compose containers

### ISSUE THREAD

**Issue by ghevge** [docker/compose#10837]
### Description

Currently docker secrets are only available with docker swarm and there is no way to use this functionality with docker-compose containers. When you will try to do that you will get an error like:
`Service "x" uses secret "y" which is external. External secrets are not available to containers created by docker-compose`

For small deployments and/or testing user might want to use secrets with docker-compose containers, without having to set up a docker swarm

**Comment by milas** [comment]
It's possible to use a file (relative to the Compose project) or an environment variable (from the _host_, i.e. where you are running `docker compose up`) as a `secret`, which will be copied into the container in `/run/secrets`.

See https://docs.docker.com/compose/compose-file/09-secrets

Is there another secret source you are interested in?

**Comment by jhrotko** [comment]
Closing for lack of response. Please feel free to re-open this issue!
