### ISSUE TITLE
Support wildcards/glob paths in docker compose --file flag

### ISSUE THREAD

**Issue by 814k31** [docker/compose#10857]
### Description

We could like to simplify our commands in a directory that holds many docker compose files

Current
```bash
docker compose -f file1.yml -f file2.yml -f file3.yml up
```

Desired:
```bash
docker compose -f *.yml up
```

I couldn't find how to achieve this in the documentation. If it exists could you please provide a reference.

**Comment by ndeloof** [comment]
This just isn't supported, especially as file order maters in the way compose merge compose files and defines the project directory based on first file.

I'm closing this as "not planned"

**Comment by 814k31** [comment]
@ndeloof this use case is for when file order doesn't matter.

We have multiple generated docker compose files that don't relate to each other

It's more so a workspace

But we want to start them with only one command

The include option doesn't do this with docker compose up.

I'd recommend reopening this issue as it's still relevant

If someone wants to use globs where file order does matter they can do `docker compose -f glob/excluding/orderedfile -f orderedfile.yml`

**Comment by nplawes** [comment]
I have a similar use case - several seperate docker services that would be so much better served by a 'drop-in' directory, using `include docker-compose.d/*.yml`. Right now I have to build the compose file using a template that has to know about all the projects...

**Comment by brad2014** [comment]
> This just isn't supported, especially as file order maters in the way compose merge compose files and defines the project directory based on first file.

For decades, unix applications/subsystems that support drop-in directories have depended on the order of processing.  They simply process the globbed files in alphabetical order.  Examples /etc/grub.d, /etc/X11/xinit/xinitrc.d.

For applications where order matters, users will drop them as 00-myfirstcompose.yml 01-mynextcompose.yml and for applications where it doesn't the filenames can be anything.  Also, the include flag:

```
include: docker-compose.d/*.yml # include dropped in files in alphabetical order
```

**Comment by brad2014** [comment]
@ndeloof 
> This just isn't supported, especially as file order maters in the way compose merge compose files and defines the project directory based on first file.

For decades, unix applications/subsystems that support drop-in directories have depended on the order of processing.  They simply process the globbed files in alphabetical order.  Examples /etc/sysctl.d, /etc/grub.d, /etc/X11/xinit/xinitrc.d.

For applications where order matters, users will drop them as 00-myfirstcompose.yml 01-mynextcompose.yml and for applications where it doesn't the filenames can be anything.  Also, the include flag:

```
include: docker-compose.d/*.yml # include dropped in files in alphabetical order
```
