### ISSUE TITLE
`docker compose alpha watch` fails to sync files if the destination directory does not exist

### ISSUE THREAD

**Issue by kevinlinxc** [docker/compose#10862]
### Description

I am using the experimental watch feature to run Hugo, a website builder in Docker Compose. When I modify a file locally, it gets copied into the docker container, the served website at localhost:1313 gets updated, great. However, if I make a new folder (which is one way of making content on Hugo), this does not sync with the container, meaning any new files I put in there cause the whole thing to error out. Is there an option to sync folders too, and if not, can it be added?

**Comment by kevinlinxc** [comment]
Apologies, I'm mistaken, I must have just not had the watch running when I made the folder, but then it was running when I made the file in the folder. Perhaps a suggestion would be to recursively make folders if a file change is detected then?

**Comment by milas** [comment]
You're correct - right now syncing files to a path that doesn't fully exist in the container will fail currently.

There are some improvements coming to sync (#10853) which will address this as well as several other edge cases. I'll update this issue with the Compose version once released.

**Comment by milas** [comment]
Give this a try with v2.20.3, which was just released! There's various watch improvements including a fix for this.

**Comment by kevinlinxc** [comment]
I'll take your word for it! Thank you!
