### ISSUE TITLE
Allow disabling the image load into the local Docker daemon after build

### ISSUE THREAD

**Issue by tomelliff** [docker/compose#10868]
### Description

We're experimenting with remote buildkitd builders but ran into an issue where one project has a lot of configuration via build args and environment variables for a monolithic image and so uses Docker Compose to make this much easier than having to pass dozens of flags to `docker build --build-arg ...` and having to set up secrets etc by hand while also making it easy for local development.

Unfortunately, at the end of the build, Compose attempts to load the image into the local Docker daemon which then fails with this error because there isn't a local Docker daemon in this case:

```
# ...
#24 [lab] exporting to docker image format
#24 exporting layers
#24 exporting layers 246.5s done
#24 exporting manifest sha256:838c8fa807c85945fc37df4c2107be8a6ffa97c6e7feb16332f588dbd4b3cf04 0.0s done
#24 exporting config sha256:f14b1e9ab04a182f90f447e96bd1afb7d07035160fef14e24c23abedd345f548 0.0s done
#24 sending tarball 0.0s done
#24 ERROR: failed to copy to tar: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
------
 > [lab] exporting to docker image format:
------
failed to solve: failed to copy to tar: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Looking at the build command it looks [like this is hardcoded](https://github.com/docker/compose/blob/e7ed070690d82bb008de64ed8997d5b89056da02/pkg/compose/build.go#L364-L370) to happen and makes sense when you're expecting people to be building images and running them on the same machine. But in our case we want the ability to easily build and run locally and just build in CI (where we only have remote buildkitd builders and not currently a local Docker daemon).

Could we get a flag to `docker compose build` to disable the load?

**Comment by ndeloof** [comment]
Closing as a duplicate for https://github.com/docker/compose/issues/9586
