### ISSUE TITLE
docker-compose - dry-run - json output

### ISSUE THREAD

**Issue by ITJamie** [docker/compose#10872]
### Description

It would be great if the docker-compose dry-run outputs had a flag to output a json blob at the end of their run with the information about proposed changes (if any).

This would allow for easier wrapping with tooling eg ansible/salt/python-on-whales 

https://github.com/gabrieldemarmiesse/python-on-whales/issues/448

**Comment by felixfontein** [comment]
It would be great if machine-readable output (JSON streams?) could be enabled for all commands.
