### ISSUE TITLE
[BUG] mistake in dockerhub documentation

### ISSUE THREAD

**Issue by DavidBord** [docker/compose#10883]
### Description

On https://hub.docker.com/r/docker/compose
Under the embed snippet there is:
`COPY --from=docker/compose-bin:2.17.0 /docker-compose /usr/bin/compose`
Where docker/compose-bin tags have been changed to include v as prefix and it should be:
`COPY --from=docker/compose-bin:v2.17.0 /docker-compose /usr/bin/compose`

When trying to use the embed snippet as is it fails with the following error:
`failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = docker/compose-bin:2.17.0: docker.io/docker/compose-bin:2.17.0: not found
`

**Comment by glours** [comment]
Updated! Thanks @DavidBord for the report 🙏
