### ISSUE TITLE
Cannot mount remote volumes - no route to host when starting container

### ISSUE THREAD

**Issue by jefft4** [docker/compose#10886]
### Description

If I create a volume that references a remote share - e.g. CIFS - by hostname or FQDN, the create step works fine, but when I try to start a container that references the volume, it fails to start, complaining 'no route to host' for the CIFS mount.  Referencing the share by IP address works.

The container can be anything - initially discovered this with PhotoPrism but can replicate with a simple busybox with default everything (so, bridge/MASQ networking). Volume created using a compose file.

If I run the same container without the failing volume, I can ping the CIFS server by name and by FQDN perfectly well.

Something in the process that attempts to mount the volume appears not to be using the host DNS to resolve names.

### Steps To Reproduce

Run this compose file to create a CIFS share as a volume:
```
volumes:
  testvol:
    driver: local
    driver_opts:
      type: cifs
      device: "//myserver/FamilyPics"
      o: "username=photolibrary,password=*****"
```

Start a container referencing the volume:
```docker run -it --rm -v tmp_testvol:/vol busybox ls -l /vol```

Error:
```docker: Error response from daemon: error while mounting volume '/var/lib/docker/volumes/tmp_testvol/_data': failed to mount local volume: mount //myserver/FamilyPics:/var/lib/docker/volumes/tmp_testvol/_data, data: username=photolibrary,password=********: no route to host.```

Run an otherwise identical container and ping the CIFS server:
```
root@dock:/tmp# docker run -it --rm busybox ping myserver
PING myserver (192.168.11.22): 56 data bytes
64 bytes from 192.168.11.22: seq=0 ttl=63 time=0.140 ms
```

### Compose Version

```Text
root@dock:/tmp# docker compose version
Docker Compose version v2.20.2

root@dock:/tmp# docker compose version
Docker Compose version v2.20.2
root@dock:/tmp# docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.7
OpenSSL version: OpenSSL 3.0.5 5 Jul 2022
```

### Docker Environment

```Text
root@dock:/tmp# docker info
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 6
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.107-2-pve
 Operating System: Ubuntu 22.10
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 16GiB
 Name: dock
 ID: 09e14fad-905a-4027-8cfd-231e4ceb94b0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Appreciate that this might be a core docker behaviour issue rather than compose; please move it to the right product if so!

**Comment by ndeloof** [comment]
seems to be related to https://github.com/moby/moby/issues/42007

**Comment by jefft4** [comment]
Yes, command line 'docker create' has the same result, so I guess it's a docker issue.  Definitely related to that moby issue, agreed, exact same problem... but the apparent solution of adding 'addr' to the mount options parameter doesn't work, gives me 'invalid argument' when the container tries to start.

**Comment by Jcohen010** [comment]
Sorry, was a resolution to this issue ever found? I have the same use case as the OP and am experiencing the same issue.

**Comment by alexklibisz** [comment]
I found that upgrading to docker-ce 25.0.1 fixed this issue for me

**Comment by michaelkebe** [comment]
@alexklibisz which version did you use before?

It was fixed in moby
https://github.com/moby/moby/releases/tag/v25.0.0

CIFS volumes now resolves FQDN correctly

**Comment by alexklibisz** [comment]
> @alexklibisz which version did you use before?
> 
> 
> 
> It was fixed in moby
> 
> https://github.com/moby/moby/releases/tag/v25.0.0
> 
> 
> 
> CIFS volumes now resolves FQDN correctly

I was on 24 before. Not sure of the exact version.
