### ISSUE TITLE
[BUG] restore v2 branch and make it read-only

### ISSUE THREAD

**Issue by quaresmajose** [docker/compose#10896]
### Description

The renaming of the branch from `v2` to `main` break ever one CI build system.
Please keep the `v2` branch for some more time as read only and at last the people that uses the versions released on that branch will not be broken.

**Comment by glours** [comment]
Compose releases are available [here](https://github.com/docker/compose/releases/), you don't need the `v2` branch to get the previous releases of Compose

**Comment by quaresmajose** [comment]
@glours so you suggestion is changing everyone ci that is using the git to use archives!
I do not realize why a branch can not be maintained that until a few days ago it was the official one used for development branch.

There is a lot of them around at https://github.com/docker/compose/branches/stale where no one touches it for years but this `v2` you remove just because yes.

**Comment by quaresmajose** [comment]
On the browser it works but I am using the Yocto Project that uses the bitbake task manager to build the software and here it fails.

**Comment by quaresmajose** [comment]
The redirect also fails when using standard git tools used in build systems to fetch the source code.
```
git clone -b v2 https://github.com/docker/compose.git
Cloning into 'compose'...
fatal: Remote branch v2 not found in upstream origin

```
