### ISSUE TITLE
[BUG] Migrating from docker compose v1 to v2  --build error : unknown instruction: && 

### ISSUE THREAD

**Issue by uchar** [docker/compose#10899]
### Description

After updating docker-compose v1 to v2, I have some problems with :
```docker compose --file docker-compose-v2.yml --env-file .docker.env up -d --build ``` 

It works fine the first time I run it but after that, if I rerun it I get this error : 
```failed to solve: dockerfile parse error on line 19: unknown instruction: &&```

It works fine in docker-compose v1 and also works fine the first time I use it! 
I checked all docker files, and none of them have any issue in line 19 !  ( and even if they have why does it run successfully in docker-compose v1 and the first time in docker-compose v2 ?) 

### Compose Version

```Text
Docker Compose version v2.20.2
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-10-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.829GiB
 Name: rioniz-cpugen
 ID: 99e60966-c1c6-47bb-8c9c-e7f7a4616051
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by milas** [comment]
In Compose v1, does it repro if you do the following (multiple times)?

```
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
```

The failed to solve error is from BuildKit, so it's possible there's a difference here.

---

More likely though, you're missing a trailing `\` somewhere, e.g.
```dockerfile
RUN foo
  && bar
```
should be
```dockerfile
RUN foo \
  && bar
```

If you're using heredoc style multiline (`<<EOF`) strings, something might also be invalid there.

Beyond that, I'd need more of a reproduction case here; there simply is not enough to go off of.
