### ISSUE TITLE
[BUG] depends_on without the dependency, required: false, and service_completed_successfully is invalid

### ISSUE THREAD

**Issue by ShahimEssaid** [docker/compose#10901]
### Description

I was under the assumption that required: false means the dependency can be missing, and it works with other conditions, but with condition: service_completed_successfully an error `service "there" depends on undefined service hello: invalid compose project` is thrown.  Is this the intended behavior?  

In my case I was configuring one service per compose file and combining them as needed for various scenarios. I was hoping that I can use the depends_on with the condition service_completed_successfully as a way to order the services when they are mixed together.

### Steps To Reproduce

1. Ubuntu 22.04 with latest Docker installation.
2. Run this example:
```
services:
  there:
    image: ubuntu
    command: ["echo", " there!"]
    depends_on:
      hello:
        condition: service_completed_successfully
        required: false
```
3. Generates the error `service "there" depends on undefined service hello: invalid compose project`

### Compose Version

```Text
~$ docker compose version
Docker Compose version v2.20.2
```

### Docker Environment

```Text
~$ docker info
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 14
  Running: 1
  Paused: 0
  Stopped: 13
 Images: 112
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-26-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 46.88GiB
 Name: WVM4
 ID: e82f8658-d07f-477c-ab34-a5f152ef9e34
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
`required` let you ignore a missing dependency (container aren't found on platform) but this doesn't mean they can be missing in the compose application model.

For your specific usage, you should rely on an override file to add a `depends_on` condition when services get mixed together, but keep the "single-mode" model consistent.

Closing this issue as "works as expected"
