### ISSUE TITLE
[BUG] include attribute does not work in watch functionality 

### ISSUE THREAD

**Issue by Sevi7** [docker/compose#10928]
### Description

In the [documentation](https://docs.docker.com/compose/file-watch/) it says:

> Rules from .dockerignore apply
> - Use include / exclude to override

However, include attribute does not work.
Probably the same happens with exclude

### Compose Version

```Text
Docker Compose version v2.20.2-desktop.1
```

**Comment by Congee** [comment]
Nor does the doc say how to use include / exclude in the compose file. My current workaround is commenting out lines in .dockerignore

**Comment by ndeloof** [comment]
duplicates https://github.com/docker/compose/issues/11098
