### ISSUE TITLE
Container not showing up in docker desktop

### ISSUE THREAD

**Issue by BIGTIME888** [docker/compose#10940]
### Description

There's no container in my docker dashboard ill tried all the solution i saw in github but it seems nothing happen after all. can you help me

**Comment by milas** [comment]
Hi! I'm sorry you're having trouble with Docker Desktop.

This issue tracker is specifically for reporting _bugs_ in Docker Compose, and I can't offer general support with Docker Desktop, I'm afraid.

Take a look at the options available at https://www.docker.com/support/ such as the community forums.

Please also review the community guidelines and ensure you are creating high-quality posts that include sufficient detail for others to assist you.
