### ISSUE TITLE
[BUG] `docker compose ps --format json` no longer returns an array in 2.21.0

### ISSUE THREAD

**Issue by unikitty37** [docker/compose#10958]
### Description

The release notes for 2.21.0 state "Changed docker compose ps and docker compose ps --format=json output to align with Docker CLI."

However, in prior versions, the result was a valid JSON array. 2.21.0 returns individual objects, one after the other, with no `[ … ]` wrapper. This doesn't seem to be valid JSON.

Although jq can handle this, Ruby's `JSON.parse` rejects it as invalid; I've not tried other parsers.

Was this intended?

### Steps To Reproduce

1. With any Compose project, run `docker compose up -d`.
2. Run `docker-compose ps --format json`.

Versions before 2.21.0 will return an array of objects; version 2.21.0 will return sequential objects, separated only by a new line.

### Compose Version

```Text
% docker compose version
Docker Compose version v2.21.0
% docker-compose version
Docker Compose version v2.21.0
```

### Docker Environment

```Text
Client:
 Version:    24.0.5
 Context:    orbstack
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /Users/username/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /Users/username/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/username/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/username/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /Users/username/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/username/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/username/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     /Users/username/.docker/cli-plugins/docker-scout

Server:
 Containers: 22
  Running: 11
  Paused: 0
  Stopped: 11
 Images: 23
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: fe457eb99ac0e27b3ce638175ef8e68a7d2bc373
 runc version: 82f18fe0e44a59034f3e1f45e475fa5636e539aa
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.4.13-orbstack-00090-ga4cfdc88d4df
 Operating System: OrbStack
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 11.67GiB
 Name: orbstack
 ID: 437f17f3-56ac-4f55-ad12-6154b025c473
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://192.168.69.99:13588/
 Live Restore Enabled: false
 Product License: Community Engine
 Default Address Pools:
   Base: 192.168.215.0/24, Size: 24
   Base: 192.168.228.0/24, Size: 24
   Base: 192.168.247.0/24, Size: 24
   Base: 192.168.207.0/24, Size: 24
   Base: 192.168.167.0/24, Size: 24
   Base: 192.168.107.0/24, Size: 24
   Base: 192.168.237.0/24, Size: 24
   Base: 192.168.148.0/24, Size: 24
   Base: 192.168.214.0/24, Size: 24
   Base: 192.168.165.0/24, Size: 24
   Base: 192.168.227.0/24, Size: 24
   Base: 192.168.181.0/24, Size: 24
   Base: 192.168.158.0/24, Size: 24
   Base: 192.168.117.0/24, Size: 24
   Base: 192.168.155.0/24, Size: 24
   Base: 192.168.147.0/24, Size: 24
   Base: 192.168.229.0/24, Size: 24
   Base: 192.168.183.0/24, Size: 24
   Base: 192.168.156.0/24, Size: 24
   Base: 192.168.97.0/24, Size: 24
   Base: 192.168.171.0/24, Size: 24
   Base: 192.168.186.0/24, Size: 24
   Base: 192.168.216.0/24, Size: 24
   Base: 192.168.242.0/24, Size: 24
   Base: 192.168.166.0/24, Size: 24
   Base: 192.168.239.0/24, Size: 24
   Base: 192.168.223.0/24, Size: 24
   Base: 192.168.164.0/24, Size: 24
   Base: 192.168.163.0/24, Size: 24
   Base: 192.168.172.0/24, Size: 24
   Base: 172.17.0.0/16, Size: 16
   Base: 172.18.0.0/16, Size: 16
   Base: 172.19.0.0/16, Size: 16
   Base: 172.20.0.0/14, Size: 16
   Base: 172.24.0.0/14, Size: 16
   Base: 172.28.0.0/14, Size: 16
```

### Anything else?

[json_files.zip](https://github.com/docker/compose/files/12496192/json_files.zip)

This is occurring with OrbStack; Docker Desktop is still providing Docker Compose version v2.20.2-desktop.1, and is thus unaffected for now.

**Comment by glours** [comment]
Hey @unikitty37 
This is expected and mentioned in the `v2.21.0` [release notes](https://github.com/docker/compose/releases/tag/v2.21.0). We aligned the `docker compose ps` format to the `docker ps` one, for more details see https://github.com/docker/compose/pull/10918

**Comment by unikitty37** [comment]
Got it — thanks! I was reading the release notes at https://docs.docker.com/compose/release-notes/, which _don't_ have links to the underlying tickets. Would it be worth explicitly mentioning this there?

**Comment by glours** [comment]
Sure I'll open a PR to mention it there 👍

**Comment by philBrown** [comment]
Doesn't this represent a breaking change, requiring a major version bump?

**Comment by tingstad** [comment]
> Doesn't this represent a breaking change, requiring a major version bump?

It certainly broke several of our builds since GitHub recently [updated](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230903.1) its Ubuntu runner images to use 2.21.0.

**Comment by veaviticus** [comment]
The docker compose docs also still claim the output is array-formatted JSON, instead of a jsonlines-esque format.
![image](https://github.com/docker/compose/assets/492805/6f5765da-a74a-4b1c-850d-5245814c4593)

**Comment by SimonMacIntyre** [comment]
This change broke our scripts. -.-

**Comment by Rikaelus** [comment]
Not to be a prick but Docker doing something misleading and wrong doesn't seem to me to be just cause to break what worked and turn valid JSON into invalid JSON. Nor should this be considered JSON format when it isn't, in fact, valid JSON.

This definitely pressed my "principle of the thing" button. This is the kind of command people have buried in codebases that are now broken -- codebases that might now have to compensate to support _both_ to remain compatible with multiple Docker Compose versions on host machines.

**Comment by alexrosenfeld10** [comment]
I'm impacted by this as well. @unikitty37 at the very least you should reopen this until the [docs](https://docs.docker.com/engine/reference/commandline/compose_ps/) are updated to show the no json array behavior.
