### ISSUE TITLE
[BUG] Using docker-compose command line from PowerShell puts normal status messages in the Errors stream

### ISSUE THREAD

**Issue by MBleyerveld** [docker/compose#10960]
### Description

When running docker-compose from the PowerShell command line, it appears that normal status messages (e.g. "Network XXXX creating", "Network XXXX created", "Container XXXX creating", etc) are put into the Error stream not one of the other logging streams.

This makes it hard to do proper error checking when invoking docker-compose in an automated solution, i.e. the PowerShell object reports HadErrors as true when in fact it ran successfully.

### Compose Version

```Text
Docker Compose version v2.18.1
```

### Docker Environment

```Text
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 19
  Running: 17
  Paused: 0
  Stopped: 2
 Images: 24
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 7.575GiB
 Name: docker-desktop
 ID: cfea192e-732d-4868-a958-20ba2026f7e2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Anything else?

I'm currently looking into a PR for a fix

**Comment by ndeloof** [comment]
this is by intent: all informational message is printed on stderr as we use stdout to dump container logs.
You can change this behavior by setting `COMPOSE_STATUS_STDOUT=true` in your environment

**Comment by MBleyerveld** [comment]
Hi Nicholas,

This works well in the unix/linux world where stderr/stdout are the only
options; however in Windows there are several output streams available
(which get collapsed to STDERR/STDOUT in cmd but are able to be referenced
separately in PowerShell).

I realise that this is really a problem with go default logging not docker
compose per se, but there are ways to override the logging defaults. Would
you accept a PR to use more granular logging under windows?

In any case, thank you for pointing me to the env var to override the
logging output; for now that will suffice.

Thanks
Mark

**Comment by b3go** [comment]
> COMPOSE_STATUS_STDOUT=true

Hi @ndeloof
I run docker compose up -d threw a azure devops pipeline on a linux host. I set `COMPOSE_STATUS_STDOUT=true` which works for `network creating` messages etc. but I still get a final: `Container <ContainerName>  Running` message on the stderr which results in the pipeline failing. I don't really want to redirect stderr to /dev/null or just ignore errors in the pipeline step.

Any Ideas?
