### ISSUE TITLE
[BUG] --dry-run always returns 0

### ISSUE THREAD

**Issue by feld** [docker/compose#10975]
### Description

Dry run mode should return 0 if no action would be taken and non-zero if a change would happen. This would make the dry run functionality useful when orchestrated by other tools.

### Compose Version

```Text
Docker Compose version v2.20.2
```

**Comment by glours** [comment]
Hey @feld 
Can you give us an concrete case? 
The intent of the dry run feature is to let user know what will be the result of their commands without changing the state, so they need to know if the result of the command will 0 or an error code (invalid change in the compose file, container not existing...). 
Returning a different exit code sounds to be bad option as we expect the dry-run mode to behave the same way as regular commands
