### ISSUE TITLE
Support requests>2.5.0

### ISSUE THREAD

**Issue by vmalloc** [docker/compose#1098]
Currently docker-compose cannot be installed for virtualenvs containing newer requests installations

**Comment by dnephin** [comment]
This was previously being blocked by `docker-py`, but it looks like that was fixed in https://github.com/docker/docker-py/commit/9bed480c2745b06219c629dbbfd46b298c005447 (docker-py 1.1.0).

**Comment by vmalloc** [comment]
Ok, so can it be released please please pretty please?

**Comment by dnephin** [comment]
If you submit a pull request, I will do my best to get it in.

**Comment by vmalloc** [comment]
Created #1100

**Comment by aanand** [comment]
Closed by #1100.
