### ISSUE TITLE
[BUG] Error while running docker compose

### ISSUE THREAD

**Issue by pranavkumar7498** [docker/compose#10983]
### Description

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xfecb3e]

### Steps To Reproduce

1. Run docker compose yml file
2. Command- sudo docker-compose up

### Compose Version

Docker Compose version v2.21.0

### Docker Environment

```[tasklist]
### Tasks
```

**Comment by glours** [comment]
Hey @pranavkumar7498 :wave:

The current state of your issue doesn't give us enough information to figure out what could happen. I close the issue for now.
Could you please add more details (compose version ...) and a reproducible example? When your issue description updated, ping me and I'll re-open it.
