### ISSUE TITLE
[BUG] unexpected 'no such service' error when --no-deps and volumes_from used together

### ISSUE THREAD

**Issue by nicks** [docker/compose#10996]
### Description

unexpected 'no such service' error when --no-deps and volumes_from used together

### Steps To Reproduce

1. Create the following `docker-compose.yaml`:

```

services:
  app:
    image: busybox
    command:
    - "sleep"
    - "1000"
    volumes_from:
    - db

  db:
    image: mysql:5.7.37
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DOCKERDB
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

```

2. Run `docker compose up -d`
3. Run `docker compose up --no-deps app`

Expected Result:
The app service starts successfully, without restarting db.

Actual result:
```
docker compose up --no-deps app
no such service: db
```

### Compose Version

```Text
docker compose version
Docker Compose version v2.21.0-desktop.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0-cloud-driver+002
    Path:     /home/nick/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0-desktop.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  harmonia: A brief description of Harmonia (Docker Inc.)
    Version:  1014447
    Path:     /home/nick/.docker/cli-plugins/docker-harmonia
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.7
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.24.1
    Path:     /usr/lib/docker/cli-plugins/docker-scout
  sleep:  (Docker Inc.)
    Version:  0.1.0
    Path:     /home/nick/.docker/cli-plugins/docker-sleep

Server:
 Containers: 6
  Running: 4
  Paused: 0
  Stopped: 2
 Images: 5
 Server Version: master
 Storage Driver: stargz
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.3.13-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.65GiB
 Name: docker-desktop
 ID: a92cef06-564f-4766-91bd-bc9e839af9fa
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  registry:1234
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Anything else?

This repro case has been boiled down from https://github.com/tilt-dev/tilt/issues/6220

**Comment by nicks** [comment]
confirmed that this worked correctly in docker-compose-v1 :cry:

**Comment by boydingham** [comment]
The error originally reported in https://github.com/tilt-dev/tilt/issues/6220 was `no such service: db`.

Please help clear up my confusion, @ndeloof, over the `no such service: db` failure I'm seeing in [_noDeps_test.go_](https://github.com/docker/compose/blob/main/pkg/e2e/noDeps_test.go). I _read_ the Go code before I _ran_ the test.

I'm green at Go. Just reading it, I expected [_the code at line 38_](https://github.com/ndeloof/compose/blob/92637d2de8e500ecb55301b890ad431317b35f01/pkg/e2e/noDeps_test.go#L38) would succeed if it were actually run. So I went ahead and ran it&hellip;

![Shouldn't line 38 succeed without throwing an assertion error?](https://github.com/docker/compose/assets/82042696/12ce6554-4955-4704-a3c2-988c9c484051)

The failures in the recording _-suggest-_ that what was implemented in #10999 does not produce the result the test is expecting. Granted, it could be that I just suck at reading Go.

**Comment by ndeloof** [comment]
You have to run `make install` before you can run e2e test locally

**Comment by boydingham** [comment]
> _You have to run `make install` before you can run e2e test locally_

Noted 👍 

Is that `make install` step a standard step for unit testing in systems written in Go? Or is that only specific to this project?

That's a _notable_ difference from how testing is done in the language I'm most familiar with. Viva la difference!

**Comment by ndeloof** [comment]
this is required because those end to end test rely on the built binary, those are not unit tests.
