### ISSUE TITLE
[BUG] incorrect work with path to file when we use `include`

### ISSUE THREAD

**Issue by batazor** [docker/compose#11005]
### Description

```
open /User/batazor/myproject/docker-compose/grafana/docker-compose/grafana/grafana.yaml: no such file or directory
```

### Steps To Reproduce

`docker compose -f docker-compose/grafana-tempo.yaml up -d`

### Compose Version

```Text
Docker Compose version v2.21.0-desktop.1
```

### Anything else?

I have `docker-compose` file for each of my services.

**grafana.yaml**
```
services:
  grafana: ...
```

**grafana-loki.yaml**
```
include:
- docker-compose/grafana/grafana.yaml

services:
  grafana: ...
```

**grafana-tempo.yaml**
```
include:
- docker-compose/grafana/grafana-loki.yaml

services:
  grafana: ...
```

**Comment by batazor** [comment]
Everything works fine when importing 1 file, but crashes if I want to specify an import of two files or if the imported file has its own import

**Comment by ndeloof** [comment]
This is expected. As you import `grafana-tempo.yaml` which has it's own import, relative path is resolve from the importing file, not the top-level project. `grafana-tempo.yaml` should use:
```yaml
include:
- grafana-loki.yaml
```
