### ISSUE TITLE
feature request: composePsFormat in config (analog of psFormat)

### ISSUE THREAD

**Issue by id-ilych** [docker/compose#11014]
### Description

For the `docker ps` there is a possibility to define a default format in `~/.docker/config.json`
For example: `"psFormat": "table {{ .Names }}\t{{ .Image }}\t{{ .Status }}\t{{ .Ports }}"`

It would be nice to have a similar option for `docker compose ps`.

In the `docker/cli` it is implemented as
```go
func runPs(dockerCli command.Cli, options *psOptions) error {
	// ...
	if len(options.format) == 0 {
		// load custom psFormat from CLI config (if any)
		options.format = dockerCli.ConfigFile().PsFormat
	}
	// ...
}
```

I could try implementing it myself but I am not so familiar with the codebase so I am not sure how to use the same approach because this config file is [defined](https://github.com/docker/cli/blob/0e70f1b7b831565336006298b9443b015c3c87a5/cli/config/configfile/file.go#L18-L44) in the other project which should probably be agnostic of compose-specific configurations...

**Comment by ndeloof** [comment]
This has already been fixed by https://github.com/docker/compose/pull/10918

**Comment by id-ilych** [comment]
Hello @ndeloof :wave:

Do I understand correctly that introduced change applies the same `psFormat` value from `~/.docker/config.json`?
Do I understand correctly that it means I can't have `{{ .Service }}` there because that would break `docker ps`?

**Comment by ndeloof** [comment]
you indeed can't use this in your `~/.docker/config.json` as this would break `docker ps`, but you can pass a `docker ps` format to compose, it will support same options
