### ISSUE TITLE
How can we name individual containers in docker-compose?

### ISSUE THREAD

**Issue by sourav82** [docker/compose#1104]
I noticed docker-compose automatically provides name to the containers like compose_<service_name>_1. Is there any way for users to provide name to those containers as --name in docker CLI?

**Comment by dnephin** [comment]
Not yet, see #1066

**Comment by thaJeztah** [comment]
Also, I think this is a duplicate of https://github.com/docker/compose/issues/652. @sourav82 if you agree, could you close this issue, so that the discussion can be focused in a single location? Thanks!
