### ISSUE TITLE
[BUG] Can't rewatch after I exit watch

### ISSUE THREAD

**Issue by Avihais12344** [docker/compose#11069]
### Description

Hello, I have been told [here](https://github.com/compose-spec/compose-spec/pull/253#issuecomment-1747020688), I need to open an issue about the: `docker compose watch` command.

I am loving this feature, and it works pretty fine, but I have a problem. When I exit the watch command by using ctrl + c, or by using the command: `docker compose down --timeout=0 --volumes --remove-orphans`, there's still a prosess that holds some lock file. As I get the error:

```bash
cannt take exclusive lock for project "my_project": process with PID 11324 is still running
```

What can I do? The only solution I have found is to reset the computer.
The output of the: `docker-compose version` command:

```bash
Docker Compose version v2.22.0-desktop.2
```

Thanks in ahead for any help :)

### Steps To Reproduce

1. With Docker Compose version: `Docker Compose version v2.22.0-desktop.2`.
2. In a project with docker compose file.
3. Run the command: `docker compose watch`.
4. Press `ctrl + c` (to stop watching).
5. Run the command: `docker compose watch` **again!**.

### Compose Version

```Text
Docker Compose version v2.22.0-desktop.2
```

**Comment by joshh20** [comment]
I'm also getting this error, which is odd as I had been using Docker Compose Watch fine for a week or two before this.

**Comment by jmealo** [comment]
I'm having the same issue. It worked once then I turned it all off to demo for a coworker and it broke.

**Comment by wethreetrees** [comment]
You can delete the lock files manually to free the watcher up for that project. Probably safer to do if you've guaranteed that the process at the pid specified has been killed first.

They should be located in the following directory for your respective OS

windows: `%LOCALAPPDATA%`
unix: `/run/user/UID`
macos: `~/Library/Application Support`
plan 9: `/tmp`

**Comment by Avihais12344** [comment]
It have worked! Thanks.

But I would still like a long term solution for this.

**Comment by ndeloof** [comment]
Closing this issue as a duplicate for https://github.com/docker/compose/issues/11066
