### ISSUE TITLE
[BUG] standalone cannot connect to daemon

### ISSUE THREAD

**Issue by axiopaladin** [docker/compose#11065]
### Description

This is probably a stupid simple fix, but I've combed through the (somewhat sparse) [documentation on `docker-compose`](https://docs.docker.com/compose/install/standalone/) a few times now and I'm not sure what I'm missing. When I try to run *any* commands more complicated than "version" (for example, `docker-compose ps` or `docker-compose up`), it throws this error:

> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### Steps To Reproduce

1. This happens for me on both Ubuntu 22.04 LTS and under the WSL2 version of the same.
2. On a fresh OS, install `docker-compose` standalone following [the instructions in the documentation](https://docs.docker.com/compose/install/standalone/#on-linux):
  i. `curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose`
  ii. `sudo chmod 0777 /usr/local/bin/docker-compose/`
  iii. `sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose`
3. Trying `docker-compose version` outputs `Docker Compose version v2.20.3`
4. Trying any other docker-compose command, such as `docker ls`, outputs `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

### Compose Version

Standalone v2.20.3

### Anything else?

I suspect there's just some undocumented command to tell `docker-compose` to start whatever daemon it's complaining about, but after reading and re-reading the [standalone docs page](https://docs.docker.com/compose/install/standalone/) and the `docker-compose --help` output a few times, I can't figure it out.

**Comment by ndeloof** [comment]
Instructions tell you how to install docker compose, but this is only about compose and installation of docker engine is not included. See https://docs.docker.com/engine/install/

**Comment by axiopaladin** [comment]
> @ndeloof wrote:
> Instructions tell you how to install docker compose, but this is only about compose and installation of docker engine is not included. See https://docs.docker.com/engine/install/

Thank you, that seems to be what I was missing. Perhaps a note could be added to the [standalone install page](https://docs.docker.com/compose/install/standalone/) to explain this? As a naive reader, I assumed that when it said "standalone" it meant that it was fully self-contained. Should I put together a PR for that?
