### ISSUE TITLE
[BUG] Can't use Chinese in environment variables

### ISSUE THREAD

**Issue by UchihaYuki** [docker/compose#11074]
### Description

I can't use Chinese charaters in environment variables like the following:
```
    environment: 
      - BRAND=哈哈哈
```
I got the following error:
```
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2353-2355: character maps to <undefined>
```

### Steps To Reproduce

You can paste the above environment variables to any service. It just can't use Chinese characters.

### Compose Version

```Text
docker compose version:

Docker Compose version v2.15.1
```

docker-compose version
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```
```


### Docker Environment

```Text
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

C:\Data\projects\zhang-san-sui\app\projects>docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 71
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 37.56GiB
 Name: docker-desktop
 ID: Z3PU:77JX:JRSE:PIYL:JOOQ:PPAZ:WMJ5:YGIK:MYC2:HZT2:EM22:KV53
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by ndeloof** [comment]
You still have docker compose v1 installed, Docker Compose v2 doesn't have such an issue. You can confirm by using  `docker compose` command (space) vs `docker-compose`

**Comment by UchihaYuki** [comment]
> You still have docker compose v1 installed, Docker Compose v2 doesn't have such an issue. You can confirm by using `docker compose` command (space) vs `docker-compose`

I will encounter some other errors. One of them is
```
extends: Support for `extends` is not implemented yet.
```

**Comment by UchihaYuki** [comment]
I'm pretty confused while reading this doc:
https://docs.docker.com/compose/compose-file/#extends
Does Compose V1 mean version 2.x and 3.x? Then what does 1.27.0 refers to?
> Legacy versions 2.x and 3.x of the Compose file format were merged into the Compose Specification. It is implemented in versions 1.27.0 and above (also known as Compose V2) of the Docker Compose CLI.

**Comment by ndeloof** [comment]
`extends` is fully supported by compose v2. v2.15.1 you are using is obsolete, please upgrade

docker compose v1 (v1.x.y) refers to the legacy python implementation, it reached end of life, don't use it

> Shoudn't the version number of docker compose begin at v2.x

it does, current release is [v2.22.0](https://github.com/docker/compose/releases/tag/v2.22.0)

Compose **file format** 2.x and 3.x is obsolete, compose specification supersede this versioning logic and you should stop setting a `version: x` attribute in your compose files.

**Comment by UchihaYuki** [comment]
I updated to `Docker Compose version v2.22.0-desktop.2` now and encountered a new error. 

When I run `docker compose config` it not just populates the `extends` keyword, but also adds a name attribute at the root level which is not supported by `docker stack`.

**Comment by UchihaYuki** [comment]
But you can't use `extends` keyword in compose file for `docker stack`. Is there a better way to organize my compose files for `docker stack`? I have several files which share the same basic compose file.
