### ISSUE TITLE
how to speed up build time

### ISSUE THREAD

**Issue by foxnight2** [docker/compose#11087]
### Description

I only change the cmake version on the dockerfile, but the docker build will start build from cmake step.
And the opencv is also build, even the opencv step is not changed.
Do you have idead to pass opencv build? 

original
```
FROM ubuntu20.04 AS base
RUN apt-get install XXX

FROM base AS cmake
ENV cmake_version=3.26
RUN apt-get install cmake==cmake_version

FROM cmake AS opencv
ENV opencv_version=4.6
RUN apt-get install XXX
```

change the cmake version
```
FROM ubuntu20.04 AS base
RUN apt-get install XXX

FROM base AS cmake
ENV cmake_version=3.27
RUN apt-get install cmake==cmake_version

FROM cmake AS opencv
ENV opencv_version=4.6
RUN apt-get install XXX
```

**Comment by ndeloof** [comment]
closing as unrelated to docker compose, please report on user forum / community slack for assistance

**Comment by foxnight2** [comment]
Please give the entry point link.

**Comment by ndeloof** [comment]
https://www.docker.com/community/
