### ISSUE TITLE
Allow overriding `networks` with `network_mode` when extending services

### ISSUE THREAD

**Issue by smuuf** [docker/compose#11084]
### Description

When extending a service via an "override" YAML I am unable to override `networks` in the base service with additional `network_mode` setting.

```yml
# docker-compose.yml
services:
  my_frontend:
    networks:
      - my_network

# docker-compose.override.yml
services:
  my_frontend:
    extends:
      file: ./docker-compose.yml
      service: my_frontend
    network_mode: host
    networks: !reset []
```

Even though I'm resetting the `networks` key with an empty list, Docker Compose still complains that there are both `networks` and `network_mode` keys specified:

```
service my_frontend declares mutually exclusive `network_mode` and `networks`: invalid compose project
```

Which, I guess, is technically true, but then again it's maybe actually not.

I'd be happy for some guidance - or if it's something that should be implemented as new _(because I'd expect this to work)_ then this is a feature request.

## Using this Docker

```bash
$ docker compose version
Docker Compose version v2.21.0

$ docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:12 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by ndeloof** [comment]
I'm not able to reproduce, I get the expected result with your example (which miss an image)


```yaml
$ docker compose -f ... config
services:
  my_frontend:
    image: nginx
    network_mode: host
```

**Comment by smuuf** [comment]
My apologies, it seems I've been passing wrong arguments into Docker Compose. I was probably forgetting to pass the "base" Compose file in front of the "override" one the whole time.

```shell
docker compose -f docker-compose.yml -f docker-compose.override.yml up
```

This really seems to work as intended.

I'm sorry for the noise, but thank you anyway 🍀 Closing this.
