### ISSUE TITLE
Volume mount paths should be relative to YAML file

### ISSUE THREAD

**Issue by aanand** [docker/compose#1109]
#1099 makes `env_file` paths relative to the YAML file. `volume` host paths should follow the same logic.

**Comment by aanand** [comment]
Implemented in #1088.

**Comment by cameron** [comment]
How does it behave when the docker client and server are on different hosts?

**Comment by ebuildy** [comment]
I think (sometimes...) that it would be nice to have a "set current working directory" option as lot of people are using virtual machine to work with Docker (boot2docker in my situation) and path will differ from the production server for instance.

    docker-compose -f ./ops/docker-compose.yml --cwd=./shared/data/

This will be very useful.
