### ISSUE TITLE
Easier (or functioning?) network_mode: "host" in windows.

### ISSUE THREAD

**Issue by henke443** [docker/compose#11103]
### Description

I've spent a couple days of my life over the span of 2-3 years or so going insane over the exact same situation:
1. I have a nginx container (only nginx)
2. I have some backend api's and stuff in other containers
3. I need to get peoples ip address for rate limiting
4. I then need to move nginx to host instead of bridge

Step 4 NEVER works. Today I even have to give up as it's soon 3 in the morning and I have actual work tomorrow.

Here's some schizophrenic excerpts of what I've already tried that didn't work:

```
#networks:
 #   backend:
  #      driver: bridge
  #backend:
  #  driver: bridge
  #nginx:
  #  driver: host
  
   #build:
    #     context: ./infrastructure/nginx
    #     dockerfile: ./Dockerfile
    #    network: host
    #network_mode: host
    
    
  location / {
        proxy_pass http://localhost:8000;
        

  location / {
        proxy_pass http://127.0.0.1:8000;


location / {
        proxy_pass http://0.0.0.0:8000;

location / {
        proxy_pass http://host.docker.internal:8000;


upstream api-proxy {
  server localhost:8000;
}

upstream api-proxy {
  server localhost:8000;
}

.... and on and on and on and on ...
    
  ````

**Comment by ndeloof** [comment]
AFAICT this issue isn't related to Docker Compose but is a general issue using Docker containers and networking.
Please join https://www.docker.com/community/ to ask for assistance
