### ISSUE TITLE
[BUG] `watch` path key is not relative to build context

### ISSUE THREAD

**Issue by jpulec** [docker/compose#11101]
### Description

The docs suggest that when using the `watch` command, all paths are relative from the build context (including the `path`) value that is being monitored and synced to the container. However, it seems that this value is relative to the `compose.yaml` file, and not the build context, which may be specified as a different path in the service definition.

### Steps To Reproduce

Image a filesystem such as the following:

- /
- /apps/
- /apps/compose.yaml
- /apps/web/
- /apps/web/Dockerfile

Add a `compose.yaml` file like the following:
```docker-compose
  web:
    build:
      context: ../
      dockerfile: ./apps/web/Dockerfile
      target: dev
    command: yarn dev --filter=web
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - node_modules/
            - dist/
```

And note that after running watch, it will indicate that the folder being watched is `apps` instead of the parent of `apps`, which is what it should be, since the build context of the web container is given as `../`.

**Comment by ndeloof** [comment]
I also was [confused](https://github.com/compose-spec/compose-spec/pull/253#discussion_r1331048711) with this, need to be clarified on docs or fixed
cc @glours @milas

**Comment by glours** [comment]
@jpulec @ndeloof I have a couple of update to do on the watch documentation page today, I'll update this section also 👍

**Comment by ndeloof** [comment]
fixed by https://github.com/docker/docs/pull/18463
