### ISSUE TITLE
Wrong version of Docker compose in Ubuntu package

### ISSUE THREAD

**Issue by alex-mashin** [docker/compose#11100]
### Description

Under Ubuntu 23.04, `apt install docker-compose-plugin` reports that it is of the newest version `2.21.0-1~ubuntu.23.04~lunar`. However, `docker compose version` reports `Docker Compose version v2.15.1`. The used repository is `https://download.docker.com/linux/ubuntu   lunar stable`.

### Steps To Reproduce

Under Ubuntu 23.04, set up Docker repository as instructed, run `sudo apt install docker-compose-plugin`, read the version number from `apt install` output, which is `2.21.0-1~ubuntu.23.04~lunar` and compare it with output from `docker compose version`, which is `Docker Compose version v2.15.1`.

### Compose Version

`Docker Compose version v2.15.1` (and this is the problem)

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.0.5
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.17
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/lib/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-34-generic
 Operating System: Ubuntu 23.04
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.71GiB
 Name: maicube
 ID: IOXL:VMCN:KHCS:WUOM:WIJ4:EO2T:4FUK:PH5E:YKIQ:XCCE:M32I:XHNL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by glours** [comment]
Hey @alex-mashin 
Can you check you don't have an another compose binary in `~/.docker/cli-plugins` ? Maybe you have an older version installed manually here

**Comment by alex-mashin** [comment]
> Hey @alex-mashin Can you check you don't have an another compose binary in `~/.docker/cli-plugins` ? Maybe you have an older version installed manually here

I haven't even got such directory.

**Comment by alex-mashin** [comment]
> sounds like you have an older version of docker compose installed in one of the supported path (https://github.com/docker/cli/blob/8743ffda3953daa6b212c1f6a5d22803d856433f/cli-plugins/manager/manager_unix.go#L5)

I found `docker-compose` in the latter two of the path at the link above, removed it, `docker compose` stopped working, I `apt get remove`d it and `apt get installed`. After that `docker compose version` reported `Docker Compose version v2.21.0`.

Thank you for your help.

This could mean that  the Ubuntu package is not updated properly.

**Comment by floge07** [comment]
I'm currently wondering why apt get install reports the current version as 2.21 when the newest is actually 2.23. Wanted to try the new watch feature...

**Comment by ndeloof** [comment]
debian packages are built as part of the global [packaging](https://github.com/docker/docker-ce-packaging) process, which is not ran at the same cadence we release Docker Compose on this repository.
If you'd like to test `watch`, just download pre-built binaries from https://github.com/docker/compose/releases

**Comment by floge07** [comment]
Oh, I see. And yes I ended up doing exactly that.
