### ISSUE TITLE
Use docker-compose.yml offline

### ISSUE THREAD

**Issue by tugcekiziltepe** [docker/compose#11116]
I am trying to run containers using docker-compose.yml without internet connection and logging in. I've downloaded all necessary images from a computer that has internet connection and transfer the data to the this computer. When I say `docker compose us -d ` it gives `error getting credentials - err: exit status 1 , out: A specified logon session does not exists. It may already have been terminated.`. How can I pass this error? It is not possible for me to log in.

**Comment by ndeloof** [comment]
Not sure where this error message comes from, but this doesn't seem like a Docker Compose error message. Could you please attach the whole console output ?

Als (assuming you're running latest release) you can run `docker compose pull --policy  missing` to check required images are all available on local (offline) computer. This command will not require any Internet connexion if local engine has the configured image in local store

**Comment by ndeloof** [comment]
Closing as initial reporter didn't provided requested details
