### ISSUE TITLE
Write how-to guides on how to use "extends"

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1111]
- How to define different environments for your application (development, testing, production, etc). This would also be a good opportunity to explain how to use an existing image instead of building an image.

- How to split your application out into multiple files / repositories

**Comment by olalonde** [comment]
:+1:

**Comment by montells** [comment]
+1

**Comment by astropanic** [comment]
+1

**Comment by mahnunchik** [comment]
+1

**Comment by radiumx3** [comment]
:+1:

**Comment by ChrisChinchilla** [comment]
#dibs I am going to be attempting this over the next few days for my own work, so I will work on this whilst I do.

**Comment by ChrisChinchilla** [comment]
Should this be added to the current yml.md document or into a separate one?

**Comment by bfirsh** [comment]
cc @aanand

**Comment by aanand** [comment]
@ChrisChinchilla A separate doc would be best, which we can link to from the YAML guide. Thank you!

**Comment by ChrisChinchilla** [comment]
Great. I will get onto this over the Easter weekend.

**Comment by aanand** [comment]
@ChrisChinchilla Unfortunately we're doing a release very soon, so I'm writing the first version of this. However, it'd still be really good to get your take on it as a user and non-developer of the feature, so please do send it our way!
