### ISSUE TITLE
[BUG] v2.23.0 breaks if can't create cache for any reason

### ISSUE THREAD

**Issue by mritalian** [docker/compose#11126]
### Description

Starting v2.23.0 something broke and doing basic `docker-compose pull` fails when run from systemd unit, I assume this is due to lack of env var as the error seen is:

`initializing git cache: could not create any of the following paths: /.cache/docker-compose`

I can't imagine writing in root is desired but again is probably side effect of $HOME not being set.  We should no longer assume / is writeable which more and more is not, considering OS with ro root fs like coreos.  We can also not assume $HOME is set, some stronger mechanism should be used.

Rolling back to v2.22.x works fine

### Steps To Reproduce

1. create a oneshot systemd unit that runs docker-compose pull
2. start the unit
3. journalctl will show the error

Noticed on fedora coreos

### Compose Version

```Text
Docker Compose version v2.22.0

no plugin
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: default
  selinux
  cgroupns
 Kernel Version: 6.4.15-200.fc38.x86_64
 Operating System: Fedora CoreOS 38.20230902.3.0
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.907GiB
 Name: bastion01-test-5grcs-com
 ID: J7JL:ULEZ:XK6Z:APFN:4HTL:P3H3:CISE:2KTK:IVDM:P7O3:5R46:YMZY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ericbsummit
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

### Anything else?

cat /etc/os-release 

NAME="Fedora Linux"
VERSION="38.20230902.3.0 (CoreOS)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora CoreOS 38.20230902.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='38.20230902.3.0'

**Comment by ndeloof** [comment]
Docker compose uses `.cache/docker-compose` to store remote resource involved by `include`.
We rely on https://github.com/adrg/xdg to select the adequate path for this cache to be created into. On unixes this should be `$HOME/.cache` until you have `XDG_CACHE_HOME` defined. Could you please check ?

**Comment by ndeloof** [comment]
> is probably side effect of $HOME not being set

indeed. Why isn't this set ?

**Comment by ndeloof** [comment]
A possible workaround is for you to run you systemd unit with `XDG_CACHE_HOME` set to some path that would make a relevant cache folder.

**Comment by mritalian** [comment]
Setting `HOME` works too.  The main issue is twofold
1) on systems with r/o root or if run as non-root, it fails with a cryptic error instead of saying: "I can't figure out what your home directory is".  This is a good failure.
2) on systems without r/o root fs or if run as root, it will dump files into a new folder in /.  This is a very very bad failure as this could very quickly fill up / which is generally partitioned small and/or tmofs, and would break the machine 

Imo, xdg should flat out barf if no env vars are set, and not just take the dangerous assumption HOME=/ .  Or, it should be smarter in finding the home dir of the logged in user (there are mature, well-defined linux native API calls to do this).  How mature is this xdg library?

**Comment by edwardpeek-crown** [comment]
This is causing compose to fail for us as well where we are running it in a largely read-only filesystem environment.

I would expect compose to not attempt to create these dirs if the git include feature is not actively being used.

**Comment by ndeloof** [comment]
@edwardpeek-crown indeed, cache dir could be created on first use
Addressed by https://github.com/docker/compose/pull/11130/commits/c8c09c0b10d3dcb5af7b7da42874317512f24d69

**Comment by csegarragonz** [comment]
hey!
i use `docker compose` on GHA (with GH-hosted runners), and i am running into the [same error](https://github.com/faasm/faasm/actions/runs/6723898006/job/18274989888#step:12:47)

the runner image [ships](https://github.com/actions/runner-images/blob/ubuntu22/20231030.2/images/linux/Ubuntu2204-Readme.md#tools) with `docker compose` version `2.23.0`, so i'd expect this error to be much more frequent.

the error message is the same:

```bash
initializing git cache: could not create any of the following paths: /.cache/docker-compose
```

alas, setting the `XDG_CACHE_HOME` env. variable does not help neither.
