### ISSUE TITLE
Proposal to rearrange the load order of environment variables to address dependencies

### ISSUE THREAD

**Issue by danielerepici** [docker/compose#11132]
### Description

Currently, if my `.env` file looks like this

    FOO=foo${BAR}
    BAR=bar

when I do `docker compose up` I get `WARN[0000] The "BAR" variable is not set. Defaulting to a blank string.` and `FOO` is evaluated to `foo`. In other words, I need to pay attention to the order of variables.

This gets tricky when you have tooling that autogenerates the `.env` file. You have to add extra tooling to address variable dependencies.

It would be nice if Compose applied extra "intelligence" to autosort environment variable loading based on their dependencies, and also warn/error if circular dependencies are spotted.

**Comment by ndeloof** [comment]
This is consistent with the way a shell script will parse and set environment variables from your .env file. If we change this, one would then not be able to run `source .env` to replicate environment in a terminal. For this reason, I'm :-1 on this

As a side note, if you generate such .env file, you have no benefits to reference other variables in same file, you just can directly set values. While this would be considered code duplication for a human-managed file, this has no impact on a file that get generated and not intended to be edited/maintained

**Comment by danielerepici** [comment]
> This is consistent with the way a shell script will parse and set environment variables from your .env file. If we change this, one would then not be able to run `source .env` to replicate environment in a terminal. For this reason, I'm :-1 on this

Makes sense. Wasn't thinking about that. What about making it an opt-in feature to be enabled via a compose option, something like like `--auto-sort-env-file`. This would allow whoever needs it to use it at their own risk as long as they understand the implications.

> As a side note, if you generate such .env file, you have no benefits to reference other variables in same file, you just can directly set values. While this would be considered code duplication for a human-managed file, this has no impact on a file that get generated and not intended to be edited/maintained

Not if the `.env` file is autogenerated from other blueprint environment files that _are_ human-managed (e.g. using tools like [envcat](https://envcat.readthedocs.io/en/stable/)). In that case, unfortunate order in the blueprint files, or even the tooling logic itself (e.g. the aforementioned envcat just sorts the resulting variables in alphabetical order) might result in unfortunate order in the final `.env` file.

**Comment by ndeloof** [comment]
env file order is relevant, let's say I use:
```
OLD_BAR=${BAR}
BAR=baz
```
I'm using this so I can override BAR but keep the original value for another purpose. If I apply your suggestion the result would be wrong.

Also about "_use it at their own risk as long as they understand the implications_", being the one who will have to support users and give them guidance when something goes wrong, I'm :-1 with such an option

You should better open an issue on envcat project so they stop breaking env file ordering just like it has no impact.
