### ISSUE TITLE
Request: add `docker compose` to Python SDK

### ISSUE THREAD

**Issue by mvadari** [docker/compose#11138]
### Description

I'm working with Docker in a Python project, and it's a bit janky to use `docker compose` in `subprocess` instead of being able to use the SDK directly.

**Comment by glours** [comment]
Hello @mvadari 
All docker product are developed with Golang, this offers us more flexibility and speed to update internal dependencies to access new features (of docker engine or build tools) or fix CVEs for example. 
With the previous Python of Compose we had to backport all new changes from Docker dependencies, fixing CVE was slower... 
So we won't provide a Python SDK, you can still use [the v1 branch](https://github.com/docker/compose/tree/v1) but you will have to backport new features by yourself and we won't provide any assistance.
