### ISSUE TITLE
Update pyyaml on 6.0.1

### ISSUE THREAD

**Issue by ikheifets-splunk** [docker/compose#11140]
Hello, @glours !

Yeah `5.4.1` is not affected by CVE, but this version [has problem with installation ](https://github.com/yaml/pyyaml/issues/724), all the versions < `5.4.1` has this CVE.

I mean that the users which will have problem with `5.4.1`, will got version `5.3.1` that have security issue.

I understanding EOL, but security issue anyway should be fixed

_Originally posted by @ikheifets-splunk in https://github.com/docker/compose/issues/11139#issuecomment-1781778956_

**Comment by glours** [comment]
Please keep the conversation in the original issue to avoid splitting discussion

**Comment by ikheifets-splunk** [comment]
@glours you closed issue before we finished discussion, by this reason I opened new issue

**Comment by glours** [comment]
A closed issue can be re-open if needed

**Comment by ndeloof** [comment]
docker-compose (python) is End of Life after having been deprecated for 1 year, and you should just not install it. We don't offer any maintenance on this package anymore, including security updates. Like Windows 95, docker-compose python is just dead - don't use it.

**Comment by ndeloof** [comment]
@alingse why not just use the actively developed version ?

**Comment by eudaimos** [comment]
@alingse are you looking for a python package to include in a program or are you using `pip` to install and use compose as a binary shell command?

**Comment by alingse** [comment]
I have been assigned to deploy a Python project, which uses docker-compose 1.29.2 to import and export some configurations. It not only depends on the CLI, but also needs to run some Python code. However, docker-compose relies on PyYAML 5.4.1, which cannot be directly installed on Python 3.10 or above versions. So my idea is to remove the limit of 'PyYAML >= 3.10, < 6' in the setup.py file.  see https://github.com/alingse-forks/compose/pulls

@eudaimos @ndeloof
