### ISSUE TITLE
Add `docker compose attach`? (to support STDIN)

### ISSUE THREAD

**Issue by g0t4** [docker/compose#11153]
### Description

Similar to `docker container attach`, would `docker compose attach` be a reasonable thing to add? I'd like to attach to STDIN/OUT simultaneously and send input to my service container(s) and see their output. AFAICT, `docker compose up` only attaches STDOUT.

For example, I have a compose project w/ a single service that runs `dotnet watch`. If changes can't be hot reloaded then I can send `Ctrl+R` to the `dotnet watch` process to trigger a rebuild. 

I can use `docker container attach` to send `Ctrl+R` currently as a workaround with `stdin_open: true` and `tty: true` in my service definition.

Ideally this would also be combined with `docker compose up` to bring up and then attach STDIN right away.
- perhaps `docker compose up -i/--interactive`?
- and either a single service limitation
- or if multi service then broadcast to all STDIN
- I would also understand if this is too confusing to merge with `up` in which case `attach` alone would be great

**Comment by ndeloof** [comment]
I don't have any objection to a new `docker compose attach` command.
Adding `--attach` to `up` would introduce requirement to select a single service and then would break the logic of the command IMHO, better have a dedicated one (not to mention code would be easier to read then :P)

**Comment by g0t4** [comment]
I'll take a stab at the new subcommand and see where I can get with it.

**Comment by g0t4** [comment]
Hey so I noticed for `docker compose exec` you modified `docker/cli` to make `RunExec` public: https://github.com/docker/cli/commit/2d268392d1354a3cca68dac91a0cf93638a55d0d

Given that `runAttach` in `docker/cli`(https://github.com/docker/cli/blob/814f70749abd0e131da6456d8895b5695950a4af/cli/command/container/attach.go#L73-L74) is not public, what would be the best course of action to implement `docker compose attach`? How long would changes to `docker/cli` take to get through to `docker/compose`?

**Comment by g0t4** [comment]
@ndeloof got a first pass working! 

https://github.com/docker/compose/compare/main...g0t4:compose:11153-compose-attach

**Comment by ndeloof** [comment]
we for sure can make `runAttach` public for the same reason (and ideally update func to pass command context) to avoid too much code duplication. But if you have a short-term implementation that's also fine, just need to note this to be removed as long as docker/cli is updated for our needs.

**Comment by ndeloof** [comment]
see https://github.com/docker/cli/pull/4637

**Comment by g0t4** [comment]
Thanks to your comment about command context... I just realized `NewAttachCommand` is already exposed and I got a prototype working with just that. I will start a new branch with that and submit a PR if that sounds good to you? 

This can be a stop gap until we can call `RunAttach` or maybe this is preferred given it attaches to the stable contract of the `docker container attach`.

**Comment by g0t4** [comment]
@ndeloof Here we go, working great for my test cases, is this ready to start a PR and refine? 
https://github.com/docker/compose/compare/main...g0t4:compose:11153-compose-attach-override-container-attach-cmd

**Comment by Likqez** [comment]
Does this only work on swarm?

**Comment by Likqez** [comment]
Thanks for the fast reply. Yes, I agree, it should not have to do anything with swarm.

I was facing an issue where `docker compose attach` always responded with `is not running`.
**I thought about stacks when it was services.** Asked here before creating a stupid new issue.

Got it working. Thanks

**Comment by g0t4** [comment]
@ndeloof now that we have `docker compose up --watch`, which is fantastic, should attach be added to `up` too? And/or perhaps just adjust the existing `--attach` to also attach to `STDIN`?

**Comment by ndeloof** [comment]
@g0t4 no. attach to stdin require a single container being command target, which is what `compose run` should be used for
