### ISSUE TITLE
Port overriding

### ISSUE THREAD

**Issue by BaderBC** [docker/compose#11152]
### Description

Currently in yaml there is only one way to specify port mapping:
```
ports:
    - "host:container"
```
This method works great untill you want to override ports using command like:
`docker-compose -f docker-compose.yml -f docker-compose.prod.yml up`
In such situation we cannot override container port because it will only duplicate

It causes some problems e.g. with svelte which uses port `4173` for development and `5173` for production. If we override compose files in such scenario our port mapping looks like this:
```
ports:
    - "80:4173"
    - "80:5173"
```
instead of:
```
ports:
    - "80:5173"
```

I am pretty proficient in golang and would like to try implementing this feature on my own. However, I am currently facing difficulties understanding the structure of this codebase. I have been unsuccessful in finding the code responsible for unmarshalling YAML and have no idea where to look for it.

I would greatly appreciate some tips on how to get started!

**Comment by wivaku** [comment]
This can (now) be done using "replace value": 
https://github.com/compose-spec/compose-spec/blob/main/13-merge.md#replace-value

E.g.
```
services:
  app:
    ports: !override
      - "8443:443" 
```

This will replace existing ports with `8443:443`.
