### ISSUE TITLE
watch with console

### ISSUE THREAD

**Issue by Thiebosh** [docker/compose#11157]
### Description

I tried compose watch because i like the idea of hot reloading. I've through watch would works like up with a reload feature but, compared to compose up, i lose all log or print output. I've tried with working flask-like-library api server.
![up vs watch](https://github.com/docker/compose/assets/39088822/629cdd43-91e6-41af-a354-2d948df15f06)

Watch restart and take my updates with success, which is great.
![watch reloading works](https://github.com/docker/compose/assets/39088822/06fba48e-d5f0-4d71-9918-fbd0156f6aaf)

I've thinked about attaching docker to my service for getting my console outputs back, but the attach is killed with the container at every update + i've missed startup output.
![attach killed](https://github.com/docker/compose/assets/39088822/878b0aa0-c276-45f7-afc3-b1feba786bed)

My Dockerfile :
`FROM python:3.10-slim-buster

ARG arg_port
EXPOSE $arg_port
ENV HOST=0.0.0.0
ENV PORT=$arg_port

CMD ["python", "."]

COPY requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /src
COPY src .
`

My docker-compose (the tty doesn't change the behavior of watch command) :
`
services:
  rest:
    build:
      context: .
      args:
        arg_port: 5000
    ports:
      - 8001:5000
    tty: true

    develop:
      watch:
        # code
        - action: sync+restart
          path: ./src
          target: /src
          ignore:
            - test/
        # libs
        - action: rebuild
          path: ./requirements.txt
          ignore:
            - test/
`

So is it possible to add a docker attach into the watch command to be able to see what is happening into my container ?

**Comment by ndeloof** [comment]
`watch` does not replace `up`, but is a side command to be ran in a separate terminal

**Comment by Thiebosh** [comment]
well, same problem : the first modification make watch restart the container and up loose the link...
![image](https://github.com/docker/compose/assets/39088822/37ba276a-9915-4b49-b029-6f79b01fe44a)

With the restart: always command in the compose file

**Comment by glours** [comment]
Hello @Thiebosh
I'm not able to reproduce you case, I tested: 

- Staring with a `docker compose up` first and the `docker compose watch`
- Starting with `docker compose watch` then `docker compose up`

And I always succeed to get the `docker compose up` attached to the containers and displaying theirs outputs 🤔 
See part of the test when using either `sync` and `rebuild (also tested with `sync+restart`)

https://github.com/docker/compose/assets/705411/cbd3c7e5-1f05-4986-9879-80359f7a652e

Regarding your last screenshot it seems that the change you did created an error and your container exited. IHMO it sounds like you have a configuration issue, are you sure that `/src` is the right target path to copy files modified inside your container?

**Comment by Axxxx0n** [comment]
you can use single command `docker compose watch --no-up & docker compose up`, but it would be nice to have official guide.

**Comment by Thiebosh** [comment]
> you can use single command `docker compose watch --no-up & docker compose up`, but it would be nice to have official guide.

this is exactly what i needed. Thanks a lot!
