### ISSUE TITLE
''docker-compose logs'' does not show logs for new containers

### ISSUE THREAD

**Issue by aleksandr-vin** [docker/compose#1115]
How to reproduce:

shell 1> docker-compose scale xxx=1
shell 2> docker-compose logs xxx
shell 1> docker-compose scale xxx=2
shell 1> (make xxx service produce logs in second container)

expected: shell 2 must show ''xxx_2 | ..." logs as well

**Comment by dnephin** [comment]
I have a proposal in #1866 that should make this work

**Comment by dodekeract** [comment]
This still doesn’t work for containers that crashed and automatically restarted.

**Comment by burrusp** [comment]
I'm facing this same issue as well, any update?

**Comment by trollfred** [comment]
+1

**Comment by hugomarcelino-spotqa** [comment]
This has stopped working. When a container restarts, docker-compose logs don't show logs for the new container. This has worked before.
