### ISSUE TITLE
[BUG] Cannot bind same port but on different host ip address

### ISSUE THREAD

**Issue by Unnamed3** [docker/compose#11169]
## What I expected to happen
The second container binds and starts successfully.
The service (nginx) in container 1 is reachable by hosts on network 192.168.77.0/24 at address 192.168.77.113:80, and the other service (mynodeapp) in container 2 is reachable by hosts on network 192.168.76.0/24 at address 192.168.76.80:80.
The two services are working simultaneously.

## What I see
Trying to start another container that bind same port but on different IP address fails and causes error.
I'm using docker compose version v2.21.0 (without dash), with docker CE v24.0.7
(container 1)
```sh
user@debian-docker:~/docker/nginx$ docker compose up -d
[+] Running 2/2
 ✔ Network nginx_default    Created                                                                                                                                  0.1s
 ✔ Container nginx-nginx-1  Started
```
(container 2)
```sh
user@debian-docker:~/docker/mynodeapp$ docker compose up -d
[+] Running 2/2
 ✔ Network mynodeapp_default        Created                                                                                                                          0.1s
 ✔ Container mynodeapp-mynodeapp-1  Created                                                                                                                          0.0s
Attaching to mynodeapp-mynodeapp-1
Error response from daemon: driver failed programming external connectivity on endpoint mynodeapp-mynodeapp-1 (cdbbe992d1407d3468c0c1a284c09533b4c617ac655b1c91e2144cd88bf20c63): Timed out proxy starting the userland proxy
```
Bind try for container 1 : 
192.168.77.113:80:80

Bind try for container 2 : 
192.168.76.80:80:80

Cannot run the two containers simultaneously, the above error is shown when trying this.

Output of `sudo netstat -tunlp | grep 80` command before trying to run container 2 : 
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 192.168.77.113:80       0.0.0.0:*               LISTEN      1020/rootlesskit
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN      1020/rootlesskit
tcp6       0      0 :::8008                 :::*                    LISTEN      1020/rootlesskit
```

Output of `sudo netstat -tunlp | grep 80` command, run in parallel (in another terminal) after the command `docker compose up -d`, and before the timeout bind error : 
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 192.168.77.113:80       0.0.0.0:*               LISTEN      1020/rootlesskit
tcp        0      0 192.168.76.80:6580      0.0.0.0:*               LISTEN      1020/rootlesskit
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN      1020/rootlesskit
tcp        0      0 192.168.76.80:4200      0.0.0.0:*               LISTEN      1020/rootlesskit
tcp        0      0 192.168.76.80:80        0.0.0.0:*               LISTEN      1020/rootlesskit
tcp6       0      0 :::8008                 :::*                    LISTEN      1020/rootlesskit
```
We can see that the second bind is shown, and disappears after the error `Timed out proxy starting the userland proxy` shows on the terminal running command `docker compose up -d`.

### Steps To Reproduce

# Steps to reproduce
1. Machine with 2 ethernet interfaces "I1", "I2" connected on two different local networks. "N1" with IP address "A1", and network "N2" with IP address "A2".
2. Create docker compose files : 
    - "service1", port "x" listening on host address "A1"
    - "service2", port "x" listening on host address "A2"
3. Start the first container "service1" using `docker compose up -d` command : the first container starts successfully.
4. Start the second container "service2" using `docker compose up -d` command : the second container fails to start, and the error is shown.

6. Open another terminal "T2"
7. Re-run the command at step 4 in the terminal "T1" where there's the docker-compose.yml of the second container.
8. Run the command "sudo netstat -tunlp | grep <port x>" in the "T2" terminal.
9. See the two x ports binds showing properly in the output.
10. The command in terminal "T1" shows the error after a timeout.
11. Re-run the command at step 8 in any terminal, the binding of the "service2" container disappeared.

# Environment
In the specific case : 
"I1" is enp3s0, "I2" is enp2s0
"N1" is 192.168.77.0/24, "N2" is 192.168.76.0/24
"A1" is 192.168.77.113, "A2" is 192.168.76.80
"x" is 80

## OS of the host machine
Debian GNU/Linux 12 (bookworm)

## IP addresses of the host machine

(output of ip -a command)
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 192.168.76.80/24 brd 192.168.76.255 scope global dynamic enp2s0
       valid_lft 84155sec preferred_lft 84155sec
    inet6 2a01:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64 scope global dynamic mngtmpaddr
       valid_lft 85945sec preferred_lft 85945sec
    inet6 fe80::xxxx:xxxx:xxxx:xxxx/64 scope link
       valid_lft forever preferred_lft forever
3: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 192.168.77.113/24 brd 192.168.77.255 scope global dynamic enp3s0
       valid_lft 4954sec preferred_lft 4954sec
    inet6 fe80::xxxx:xxxx:xxxx:xxxx/64 scope link
       valid_lft forever preferred_lft forever
4: wlp1s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
```
## Docker compose files
Container 1 docker-compose.yml :
```yml
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      -  ./certs:/etc/ssl
      -  ./www:/var/www
      -  ./data/sites-available:/etc/nginx/sites-available
      -  ./data/sites-enabled:/etc/nginx/sites-enabled
      -  ./data/streams-enabled:/etc/nginx/streams-enabled
      -  ./data/streams-available:/etc/nginx/streams-available
      -  ${PWD}/data/nginx.conf:/etc/nginx/nginx.conf
      -  ${PWD}/data/proxy_params:/etc/nginx/proxy_params
    ports:
      - "192.168.77.113:80:80"
      - "192.168.77.113:443:443"
      - "192.168.77.113:8443:8443"
      - "192.168.77.113:10000:10000/udp"
```

Container 2 docker-compose.yml :
```yml
services:
  mynodeapp:
    image: node:18-alpine
    user: "0"
    pid: "host"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./data/mynodeapp:/home/node/app:rw
    ports:
      - "192.168.76.80:80:80"
      - "192.168.76.80:4200:4200"
      - "192.168.76.80:6580:6580"
    command: "npm run start"
    #command: "tail -f /dev/null"
```

### Compose Version

```Text
docker compose version :
Docker Compose version v2.21.0

docker-compose version :
-bash: docker-compose: command not found
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    rootless
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: xxxxxxxxxxxxxxxxxxxxxxxxx
  Is Manager: true
  ClusterID: xxxxxxxxxxxxxxxxxxxxxxxxx
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.2.100
  Manager Addresses:
   10.0.2.100:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  rootless
  cgroupns
 Kernel Version: 6.1.0-13-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.4GiB
 Name: debian-docker
 ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 Docker Root Dir: /home/user/.local/share/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Anything else?

# Related issue
Might be related, same behaviour but "port already in use" error in this case : https://github.com/moby/moby/issues/2644

# Other links
"Is it possible to run two services on the same ports with different IP but on the same machine ?" See [serverfault.com question](https://serverfault.com/questions/508324/is-it-possible-to-run-two-services-on-the-same-ports-with-different-ip-but-on-th)

Example tutorials trying something similar : 
[howtogeek.com : "How to run multiple docker containers on different IP addresses"](https://www.howtogeek.com/devops/how-to-run-multiple-docker-containers-on-different-ip-addresses/)

[blog.programster.org : "Docker - Run Containers On The Same Host and Port"](https://blog.programster.org/docker-run-with-same-host-same-port)

**Comment by ndeloof** [comment]
Can you please confirm running such containers without Docker Compose has the expected result, 
i.e. `docker run -p 192.168.76.80:80:80 nginx` then `docker run -p 192.168.76.80:80:80 nginx` ?

I wonder swarm mode being enabled could also have an impact on networking setup, can you reproduce this issue when disconnecting this node from your swarm cluster ?

**Comment by Unnamed3** [comment]
> Can you please confirm running such containers without Docker Compose has the expected result, i.e. `docker run -p 192.168.76.80:80:80 nginx` then `docker run -p 192.168.76.80:80:80 nginx` ?
> 
> I wonder swarm mode being enabled could also have an impact on networking setup, can you reproduce this issue when disconnecting this node from your swarm cluster ?

Hello, and thanks for your reply. I can confirm that when I run `docker run -p 192.168.76.80:80:80 nginx` in terminal 1 and try to run `docker run -p 192.168.76.80:80:80 nginx` in terminal 2, I see the expected error :

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint elegant_lamarr (57dc11233d050e684b81f85ca6b768ecb891c92f0b6796c6cf023c2a0cc9d7f5): Bind for 192.168.76.80:80 failed: port is already allocated.
ERRO[0000] error waiting for container:
```

And if I run `docker run -p 192.168.76.80:80:80 nginx` in terminal 1 and `docker run -p 192.168.77.113:80:80 nginx` in terminal 2, I see 
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint practical_ritchie (d27b912b10d95207b4cf9500cbfc61f734b01967450c4b46c3264409c33cce8e): Timed out proxy starting the userland proxy.
ERRO[0016] error waiting for container:
```
The errors from these commands up there are different.
But I get the same errors as if using docker compose.

**Comment by Unnamed3** [comment]
I don't use the cluster feature as I have one machine with Docker. If I run docker node ls : 
```
docker node ls
ID                            HOSTNAME        STATUS    AVAILABILITY   MANAGER STATUS   ENGINE VERSION
xxxxxxxxxxxxxxxxxxxxxxxxxxxx*   debian-docker   Ready     Active         Leader           24.0.7
```
And docker swarm leave : 
```
Error response from daemon: You are attempting to leave the swarm on a node that is participating as a manager. Removing the last manager erases all current state of the swarm. Use `--force` to ignore this message.
```
I'm afraid about losing all my current containers if I do the '--force' command. Would it be the case ?

**Comment by kewiha** [comment]
I am also having the same issue, but only for rootless docker. For rootful docker, specifying the ports as ip:host_port:container_port for the service and then setting host_binding_ipv4 for the network definition in compose works as expected (multiple composes can expose the same port # as long as they use different ip addresses). For rootless docker, the same approach only works if the host ports are different. If the host ports are not changed, I get that timeout error.

I get the same error when I take both composes down (`docker compose down` in each folder), then run the following in my rootless context as the user with the rootless daemon running:
```
docker run -p 10.0.136.86:8384:8384 syncthing/syncthing
docker run -p 10.0.136.89:8384:8384 syncthing/syncthing
```
The 2nd one gives the timeout error. Both addresses are available on my system and are no different from each other. Switching the order of these lines (after removing all docker containers in this context/daemon) doesn't change the behaviour: 1st works, 2nd does not.

My and OP's docker environments are both identical except for:

- I don't have swarm active
- I don't have any other containers active or running aside from the 2 I'm trying to create.
- My backing fs is ZFS not extfs
- My runc is v1.1.10-0-g18a0cb0
- I don't have the warnings about bridge-nfs-call-iptables/ip6tables being disabled
- I have the following warnings:
  - WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support

We're both running the same version of compose. The ip addrs I'm trying to get the containers to use are defined in `/etc/systemd/network/enp1s0.network`:
```
[Match]
Name=enp1s0

[Network]
LinkLocalAddressing=no
VLAN=enp1s0.300
DHCP=ipv4
[DHCPv4]
Label=DHCP
[Address]
Address=10.0.72.2/16
Label=STATIC_NIC0

[Address]
Address=10.0.136.80/16
Label={omitted}
[Address]
Address=10.0.136.81/16
Label={omitted}
[Address]
Address=10.0.136.89/16
Label={omitted}
[Address]
Address=10.0.136.86/16
Label={omitted}
```
The .80 and .81 ip addrs are happily in use by other 2 syncthing composes/containers running in a rootful context. I repeated the docker run test above with the rootful docker daemon not running (composes downed before stopping the daemon) and it didn't change the behaviour.

Please let me know if I can help resolve this, or if rootless docker with a different static ip for each container is not supported/recommended. This may not be a compose-specific issue, and could still be pebkac, but it has me stumped.

**Comment by kewiha** [comment]
The following works as expected when podman is installed as per [these install directions](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md). Most of this should already be done/installed if rootless docker has been configured, so the only incremental change may simply be to install podman. I rm'd all rootless docker containers, stopped the rootless docker daemon, and uninstalled rootless docker as a precaution, but this may be unnecessary. With that done, the following works as expected:
```
podman run -d -p 10.0.136.86:8384:8384 docker.io/syncthing/syncthing
podman run -d -p 10.0.136.89:8384:8384 docker.io/syncthing/syncthing
```
This yields two different syncthings running concurrently, and listening on their corresponding ip:port combo.

**Comment by ndeloof** [comment]
ok, so this isn't a compose but docker engine issue, please report on https://github.com/moby/moby
