### ISSUE TITLE
Add support external links in docker-compose.yml

### ISSUE THREAD

**Issue by cedvan** [docker/compose#1117]
#### Step 1
State containers on host : **API is ready**
```bash
CONTAINER ID        IMAGE                                 COMMAND                CREATED             STATUS              PORTS                         NAMES         
9b463eaae4a6        cedvan/nginx-php-fpm:1.4.6-5.5.9  "/bin/sh -c 'php5-fp   7 minutes ago       Up 7 minutes        80/tcp, 443/tcp              project_api_1  
```

#### Step 2
`docker-compose.yml` on **back project** :
```bash
back:
    image: huttopia/nginx-php-fpm:1.4.6-5.5.9
    ...
    links:
        - project_api_1:api
```

#### Step 3
**Result** of `fig up -d back` :
```bash
Service "back" has a link to service "project_api_1" which does not exist.
```

#### Question
Is it possible to add support external links in `docker-compose.yml` ?

**Comment by dnephin** [comment]
http://docs.docker.com/compose/yml/#external_links

**Comment by cedvan** [comment]
Oh yeah !

Thanks you :)

**Comment by ivorscott** [comment]
Yes!

**Comment by agostlg** [comment]
No more external links? I can't find documentation for it.

**Comment by dnephin** [comment]
https://docs.docker.com/compose/compose-file/#/externallinks

**Comment by techmexdev** [comment]
https://docs.docker.com/compose/compose-file/#external_links
