### ISSUE TITLE
[BUG] docker run command shows log, docker compose not

### ISSUE THREAD

**Issue by tobiasfaust** [docker/compose#11172]
### Description

Hi, 
i have found a wierd issue which i cannot explain.
If i run my container with:
`docker run --rm  --name vdr-server -it -v /media/recordings:/srv/vdr/video -v docker-compose_vdr-etc:/etc/vdr -v docker-compose_vdr-varlib:/var/lib/vdr/  vdr-server`
it produces lots of output:
<pre>
vdr: [7] VDR version 2.6.1 started
vdr: [7] codeset is 'UTF-8' - known
vdr: [7] override character table is 'ISO-8859-1' - known
vdr: [7] found 0 locales in /usr/share/locale
vdr: [7] no locale for language code 'deu,ger'
vdr: [7] loading plugin: /usr/lib/vdr/plugins/libvdr-svdrposd.so.2.6.1
vdr: [7] loading plugin: /usr/lib/vdr/plugins/libvdr-svdrpservice.so.2.6.1
vdr: [7] loading plugin: /usr/lib/vdr/plugins/libvdr-dummydevice.so.2.6.1
vdr: [7] loading plugin: /usr/lib/vdr/plugins/libvdr-epgsearch.so.2.6.1
vdr: [7] loading plugin: /usr/lib/vdr/plugins/libvdr-streamdev-server.so.2.6.1
vdr: [7] loading plugin: /usr/lib/vdr/plugins/libvdr-vnsiserver.so.2.6.1
vdr: [7] loading plugin: /usr/lib/vdr/plugins/libvdr-live.so.2.6.1
vdr: [7] [live] INFO: validating server ip '0.0.0.0'
INFO: validating live server ip '0.0.0.0'
vdr: [7] loading plugin: /usr/lib/vdr/plugins/libvdr-epgsearch.so.2.6.1
vdr: [7] loading plugin: /usr/lib/vdr/plugins/libvdr-femon.so.2.6.1
vdr: [7] loading plugin: /usr/lib/vdr/plugins/libvdr-devstatus.so.2.6.1
vdr: [7] loading /var/lib/vdr/setup.conf
vdr: [7] loading /var/lib/vdr/sources.conf
.....
</pre>

If i start the container with docker compose, all records strting with "vdr" are missing:
<pre>
docker compose up vdr-server
 ✔ Container vdr-server  Recreated                                                                                                                                                    2.8s
Attaching to vdr-server
vdr-server  | INFO: validating live server ip '0.0.0.0'
</pre>

docker-compose.yml
<pre>
  vdr-server:
    build:
      context: ../docker-vdr-server
    container_name: vdr-server
    image: vdr-server
    hostname: vdr-server
   restart: unless-stopped
    volumes:
      - vdr-recordings:/srv/vdr/video
      - vdr-etc:/etc/vdr
      - vdr-varlib:/var/lib/vdr
    ports:
      - 8008:8008
 </pre>

I have no idea where i have to looking for. 
Does anyone  a hint for me?

### Compose Version

```Text
Docker version 24.0.6, build ed223bc
Docker Compose version v2.21.0
```

### Docker Environment

```Text
# docker info
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 13
  Paused: 0
  Stopped: 4
 Images: 26
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-12-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.489GiB
 Name: server
 ID: 7b478370-4694-4a6c-91d6-87aa6b596215
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
as you receive the `INFO: validating live server ip '0.0.0.0'` log but not the other, I wonder how those differ. 
both `docker run` and `docker compose up` rely on `ContainerAttach` API to get container logs. The main difference is that `compose up` doesn't create container with stdin open and (emulated) TTY set by default, compared to `docker run -it`.

Can you try to run `docker compose run vdr-server` which _should_ be closer to a `docker run` from this point of view ?

**Comment by tobiasfaust** [comment]
Hi,
thank your for your quick response :)
with command `docker compose run vdr-server` all output appear as expected. 
with command `docker compose up vdr-server` not, like described above.

Whats the difference between `docker compose run` and `docker compose up`?

**Comment by ndeloof** [comment]
`up` does the equivalent of `docker run xx` (without -it`)
seems you code relies on stdout to be a terminal to dump additional logs

**Comment by tobiasfaust** [comment]
Do we need some code changes in „compose up„ command as a bugfix?

**Comment by ndeloof** [comment]
would need to know the root cause. Try to run your app with `docker run` (without `-it`) and check why it doesn't produce logs.

You also can try using `tty: true` in your compose file to assign a pseudo-terminal to the container

**Comment by tobiasfaust** [comment]
THATS was the right hint! By using `tty: true` in docker-compose.yml file, logs were produced.
Thanks a lot, so no BUG is present :)

**Comment by ndeloof** [comment]
You should anyway investigate on your code to understand why something as simple as debug logs require a terminal, and not just a plain POSIX stdout stream :)
