### ISSUE TITLE
[BUG] `CTRL+C` not propagated to containers on `docker compose up`

### ISSUE THREAD

**Issue by spietras** [docker/compose#11186]
### Description

When I run the stack with `docker compose up` and then hit `CTRL+C`, the signal seems to not be propagated to the containers. Instead, it waits for the graceful stop period (10 seconds by default) and then kills the containers forcefully.

However, it doesn't happen with all containers. For example, if I run a container with `nginx` image, then it quits immediately. See the `Steps To Reproduce` below for a configuration that does not work for me. I checked it already on three different systems and always get the same behaviour. I am starting to think that maybe it is supposed to work that way?

Also, I can confirm that when I run the container with `docker run` or `docker compose run` and then hit `CTRL+C`, it works correctly and quits immediately.

I can't really pinpoint a specific reason why this is happening.

### Steps To Reproduce

1. Create the following `Dockerfile`:

```dockerfile
FROM ubuntu:23.10
ENTRYPOINT ["tail"]
CMD ["-f", "/dev/null"]
```

2. Create the follwing `docker-compose.yaml`:

```yaml
services:
  app:
    build: .
```

3. Run the stack with `docker compose up --build`
4. Hit `CTRL+C`
5. Wait 10 seconds for the container to stop, when it should just quit immediately.

### Compose Version

```Text
Docker Compose version v2.23.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 18
  Running: 1
  Paused: 0
  Stopped: 17
 Images: 16
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8c087663b0233f6e6e2f4515cee61d49f14746a8
 runc version: 82f18fe0e44a59034f3e1f45e475fa5636e539aa
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.4.11-251.current
 Operating System: Solus 4.4 Harmony
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.43GiB
 Name: spietras
 ID: ABDW:XOHM:H5QX:ZBQB:D7MB:PNAK:GCQN:K66E:URZX:V7UE:XLLR:YV7F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
Same applies to `docker run --rm -it ubuntu:23.10 tail -f /dev/null` AFAICT, while
`docker run --rm -it ubuntu:23.10 sh -c 'tail -f /dev/null'` react to a SIGINT signal as expected 
can you please confirm ?

I wonder `tail` has a distinct behavior when ran with PID 1

**Comment by spietras** [comment]
Hmm, you are right, your examples behave exactly as you said. However, I'm quite sure it was working for me before with `docker run -it` or `docker compose run`, but now it's not and I can't reproduce it. Weird.

I also tried to replace `tail` with `sleep` and it's the same story.

Also, if I add `--init` to `docker run` to `init: true` to `docker-compose.yaml` then it's working as expected.

Anyway, seems that after all this is not a problem with Compose. However, for me, this behaviour is not what I would expect. Especially with `docker run --rm -it ubuntu:23.10 tail -f /dev/null`, I would expect I can easily quit this with `CTRL+C`. Do you know if this is indeed expected or some sort of a bug that can be reported in some other place?

**Comment by ndeloof** [comment]
I can't tell. At least this demonstrate docker compose does forward signal as expected, just the receiver for some reason does not manage.
