### ISSUE TITLE
when will compose-2.24 release?

### ISSUE THREAD

**Issue by colben** [docker/compose#11194]
### Description

when will compose version 2.24 release ?

**Comment by glours** [comment]
Hey @colben 
We don't know, why? 
But to let you know Compose `v2.23.1` was just released https://github.com/docker/compose/releases/tag/v2.23.1

**Comment by glours** [comment]
So you'll have to wait a little bit more 😄 
Who knows maybe the next release will be the `v2.24.0` 😂 
I close the issue as we won't do anything particular for this.
