### ISSUE TITLE
Add ability to by-pass environment configuration if value is unset

### ISSUE THREAD

**Issue by bobross-pg** [docker/compose#11196]
# Use case
Testing docker image with either assumed or non-assumed AWS roles without having to modify docker-compose.yml file or my image.

## Current setup
With code below, the container will resolve `AWS_SESSION_TOKEN` as empty string and the application will fail to validate AWS credentials, even thought `AWS_SESSION_TOKEN` is never defined on my host machine and the key id/secret is valid.
```
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
```

## Known alternative approach

I could mount the `.aws` folder in the image, but I have 2 issues with this:
- (Ease of use) people often mis-configure their .aws credential file, leading to docker image failing to parse it.
- (Security) this expose all credentials to the Docker image. 

## Feature suggestion 1: Using a default strategy
Ex.: 
```
  environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
  environment_default_strategy: SKIP_ON_UNSET
```
It could lead to having:
- EMPTY_STRING_ON_UNSET (default config)
- SKIP_ON_UNSET
- OVERRIDE_WITH_UNSET_ON_UNSET (just an idea, not really interested in this) : to remove an environment variable baked in an image.

## Suggestion 2: Using magic keyword
Ex.: 
```
  environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-MAGIC_DOCKER_COMPOSE_SKIP_ON_UNSET}
```
The keyword could be feature flagged. I am not sure of the approach to flag this, and allow configuration of magic word override..

## docker vs docker-compose

While this feature request might belong in docker or docker-compose, the ability for docker-compose to skip unset environment variable would 100% within docker-compose, and would address my use case.

## Conclusion
If there is interested, I could start looking into this.

**Comment by ndeloof** [comment]
You can use:
```yaml
environment:
      - AWS_ACCESS_KEY_ID  # no equal sign
```
this will just propagate variable to the container **IF AND ONLY IF** is is defined in your environment of `.env` file

**Comment by ndeloof** [comment]
Closing this issue as "already implemented"

**Comment by bobross-pg** [comment]
> Testing docker image with either assumed or non-assumed AWS roles without having to modify docker-compose.yml file or my image.

My use case might have been written properly, what I meant is:

> Testing docker image with either assumed or non-assumed AWS roles without modifying any file.

There is no feature to support this.

**Comment by bobross-pg** [comment]
Already implemented ✅ .

@ndeloof , your answer confused me at first, but it helped me figure out the existing functionality that would support my use case. What is the value to use a `.env` file for my use case ? (Using the snippet below is all I needed)

```
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
```

**Comment by ndeloof** [comment]
you won't need an `.env` file for your use case regarding `AWS_*` variables, but this can be useful if you have other variables to declare
