### ISSUE TITLE
Documentation Bug ... go not listed as a dependency

### ISSUE THREAD

**Issue by PopeNobody** [docker/compose#11191]
I am trying to compile compose experimentally.

Got an error that slices was not in my GOPATH

so, I thought, maybe my golang is old.  I never use it.

Looked for the go version required in BUILDING.md

Found this:

* Linux:
  * [Docker 20.10 or later](https://docs.docker.com/engine/install/)
  * make

Building compose also appears to require golang.

It occurs to me that I can probably solve my problem by reading the
Dockerfile, so Imma gon just do that.

Thanks for all the work you guys do!

**Comment by ndeloof** [comment]
required go version is implicitly declared by [go.mod](https://github.com/docker/compose/blob/main/go.mod#L3) and your go compiler should warn you .. until it is so old it doesn't support go modules!

Compose build is designed to run inside containers to avoid dependency on user's installation.
Please use `make binary`
