### ISSUE TITLE
[BUG] docker compose in apt is not up to date with docker compose releases

### ISSUE THREAD

**Issue by eoshea-cmt** [docker/compose#11202]
### Description

docker compose release history:
https://docs.docker.com/compose/release-notes/

does not match the latest in apt (v2.21.0).

### Steps To Reproduce

Following the steps in:
https://docs.docker.com/compose/install/linux/

e.g. in docker image `ubuntu:22.04`
(have to remove `sudo` from the commands)

run `docker compose version`

### Compose Version

```Text
v2.21.0
```

### Docker Environment

```Text
root@b04228d68896:/# docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```

**Comment by ndeloof** [comment]
debian package release is driven by https://github.com/docker/docker-ce-packaging, where release cycle is not aligned with our own releases, so use to offer a slightly older version. This is something we want to improve, but this is a cross-team effort we don't track here.
