### ISSUE TITLE
Is it possible to use docker-compose on offline

### ISSUE THREAD

**Issue by sebglon** [docker/compose#1122]
If i have no internet, is it possible to made "docker-compose up" on offline and use cache

**Comment by thaJeztah** [comment]
Have you tried? I think it should work if all images you're using are present on your docker host.

One case where it *won't* work, is if you try to *build* an image using a Dockerfile that uses `ADD http://......`, but that's how Docker handles remote content and out of control of compose.

**Comment by dnephin** [comment]
Thanks @thaJeztah
