### ISSUE TITLE
[BUG] Cannot turn on docker

### ISSUE THREAD

**Issue by Lantianyou** [docker/compose#11242]
### Description

![CleanShot 2023-12-02 at 14 28 26@2x](https://github.com/docker/compose/assets/37259750/513d2a3a-9c71-4c59-9067-0e72b26b6e9d)

### Docker Environment

```Text
docker info
Client:
 Version:    24.0.7
 Context:    orbstack
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /Users/lantianyou/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0
    Path:     /Users/lantianyou/.docker/cli-plugins/docker-compose

Server:
ERROR: error during connect: Get "http://%2FUsers%2Flantianyou%2F.orbstack%2Frun%2Fdocker.sock/v1.24/info": EOF
errors pretty printing info
```

**Comment by glours** [comment]
Hey @Lantianyou 

It seems you enabled Orbstack see `Context:    orbstack` in the log of your `docker info` command, so IHMO their repository is the best location to open an issue. 
Is the error printed coming from Orbstack UI or Docker Desktop UI?
Can you share your Compose file and the command which triggered the error? 
If there is no link with Docker Compose itself, I'll close the issue
