### ISSUE TITLE
docker-compose create

### ISSUE THREAD

**Issue by cy8aer** [docker/compose#1125]
Possibility to just create but not run containers. This would be a useful feature for systemd based startups.

**Comment by chantra** [comment]
Isn't this what
`docker-compose build`
would do?

**Comment by cy8aer** [comment]
No. `docker-compose build` creates an image from `Dockerfile` (like `docker build`). 

If you `docker create` then a new container is instanciated but not started. This looks like `docker run -d` and then `docker stop` without really starting it. So it is like to have a `docker-compose up` with creating the containers but not starting them.

Why should one need this? If you want to start/stop your containers by systemd (with `ExecStart` does `docker start -a` and `ExecStop` does `docker stop`) than you would like to have a stopped container after deployment to then systemctl start job (see https://docs.docker.com/articles/host_integration/ -> systemd part). Otherwise you need to stop the container after deployment and before systemd.

This is useful if you start e. g. a database container and link it to more than one container which uses it (timing and waiting for ports stuff). You can see the logging output of the container directly in the systemd journal stuff and so on.

`docker create` was introduced somewhere around docker 1.2 or 1.3. But there is no real python api stuff for this. In the python api you have some instanciation part and then a starting part. But with `docker create` you have all the parameter stuff `-t -i`... and with `docker start` you only have the starting. So there may be problems to implement it with the python api.

**Comment by schickling** [comment]
+1 for this feature

**Comment by marklu** [comment]
Another +1 for this feature

**Comment by rhettl** [comment]
:+1:

**Comment by kung-fu-tzu** [comment]
:+1:

**Comment by zimmski** [comment]
++

**Comment by mboussaa** [comment]
any advance on this feature ?

**Comment by marek-obuchowicz** [comment]
Any advance on this feature? Or maybe it is better to actually call `docker-compose` directly from systemd unit? It looks like a great candidate to do it - the "docker run" command in systemd unit file can get pretty long with a lot of forwarded ports and/or environmental variables being set. I would love to create "typical" small systemd unit files and keep all container runtime parameters in `docker-compose.yaml` file. Or, if the compose is not supposed to be used like that, let me know...
