### ISSUE TITLE
docker-compose build --push <registry>

### ISSUE THREAD

**Issue by cy8aer** [docker/compose#1126]
This would be a nice feature for creating and deploying of containers on a different (development) machine than the productive ones (which may run via image: option)

**Comment by dnephin** [comment]
Some related issues #213, #457

**Comment by jmmills** [comment]
I would give this a +1 as either an addition to docker-compose or as part of a different "build tool".
In addition it would be nice (and UNIXy) to add an "images" verb, so as to output a flat list of the images built by the tool. 
I'm thinking things like this would be possible:

    $ docker-compose build
    $ docker-compose list | while read i; do docker save $i -o $i.tgz ; done

Thoughts?

**Comment by PeterRJones** [comment]
+1 
docker-compose is the best/easiest way to build a bundle of related docker images. Being able to easily push these resulting docker images to a registry is a natural extension of this workflow. My use-case is a development use-case where a bundle of images are built by Jenkins. I'd like to be able to easily push these images somewhere for developers to pull and use/run.

**Comment by FelikZ** [comment]
:+1:

**Comment by rashtao** [comment]
+1

**Comment by binaryanomaly** [comment]
+1

**Comment by arthurbarros** [comment]
+1

**Comment by graingert** [comment]
+1

**Comment by crackmac** [comment]
+1

**Comment by clemensberndt** [comment]
+1

**Comment by tgagor** [comment]
+1

**Comment by bonclay7** [comment]
+1

**Comment by wjpbiblio** [comment]
+1

**Comment by karlatkinson** [comment]
+1

**Comment by paunin** [comment]
+1

**Comment by koudaiii** [comment]
+1

**Comment by groteck** [comment]
:+1:

**Comment by rudijs** [comment]
+1

**Comment by scic** [comment]
+1

**Comment by dieswaytoofast** [comment]
+1

**Comment by norbertmocsnik** [comment]
+1

**Comment by akshayl** [comment]
+1

**Comment by GriwMF** [comment]
+1

**Comment by zrks** [comment]
+1

**Comment by AndrisJersovs** [comment]
+1

**Comment by kolis** [comment]
+1

**Comment by bsao** [comment]
+1

**Comment by domg123** [comment]
+1

**Comment by tanmayambre** [comment]
+1

**Comment by ptylenda** [comment]
+1

**Comment by Kajvdh** [comment]
+1

**Comment by dwmkerr** [comment]
+1

**Comment by spul** [comment]
cy8aer opened this Issue on Mar 17, 2015

Any progress/updates? We have swarm today. In my opinion this is not anything someone wants. Today this is something docker-compose really needs.

Tried building images somewhere in swarm? Doesn't make fun. Having two distinct compose YAMLs, one to build the image, still not being able to push it with compose, another YAML to deploy the service (, again somewhere in swarm).

Assumption on a 100 peer swarm cluster, one would be forced to

* either build the image 100 times
* or leave the comfort of compose with different service definitions (+ some shell scripts/Make?).
* or anything else I might miss here?

**Comment by groteck** [comment]
In my opinion, people wants a solution to the problem of: build the `Dockerfile` of a service and then push the image to some registry and update the `docker-compose.yml`.

When other developers want the updated images, They don't have a solution like: pull my new docker images and start my services again, They need to update their `docker-compose.yml` or build the image on their machines.

NOTE: I don't know if compose is the best tool to do this job or if this way is not considered a "good practice".

**Comment by schmunk42** [comment]
We also need a way to do either `docker-compose push service` or `docker-compose image service`.

Since you can use a `.env` file now, it's pretty nice to define the image to be built there. But you need to manually parse it, when you want to use it with `docker push`, like so:

    # workaround for docker-compose environment variables
    export $(cat .env | grep -v ^# | xargs)
    docker push ${IMAGE_NAME}${IMAGE_TAG}

**Comment by omercnet** [comment]
+1

**Comment by joost-van-weenen** [comment]
+1

**Comment by agileinsider** [comment]
+1

**Comment by jmmills** [comment]
It seems that this feature is no-longer needed with the creation of the [captain tool](https://github.com/harbur/captain)?

**Comment by dnephin** [comment]
Compose 1.8 [currently available as RC2](https://github.com/docker/compose/releases/tag/1.8.0-rc2) has added `docker-compose push` for pushing images created by `docker-compose build`. It's not a flag on build, but it should provide the requested functionality.

**Comment by dnephin** [comment]
Since harbur/captain was mentioned above, I thought I might also mention [dobi](https://dnephin.github.io/dobi/). It's a different take on the same problem of automating build tasks with docker (build, test, push, etc).

**Comment by jmmills** [comment]
Interesting, thanks for the reference to dobi. It looks like it handles tagging and test targets better than captain, but no registry pushing. 


Thanks,
   Jason Mills

- sent from mobile.

**Comment by dnephin** [comment]
You can push to a registry with an [image:push task](https://dnephin.github.io/dobi/tasks.html#image-tasks). There's no official examples of this just yet,  but you would create an `alias` and put `<resource_name>:push` as one of the tasks, or run `dobi <resource_name>:push` from the command line to push an image.

For example, I use `DOBI_VERSION=0.4 dobi dist-img:push` to push the official dobi image to the hub.

The config is here: https://github.com/dnephin/dobi/blob/b07d8b124/dobi.yaml#L34-L37

**Comment by jmmills** [comment]
Not to derail this thread, but how does that work with private registries? Prefix the image name with the registry address?


Thanks,
   Jason Mills

- sent from mobile.

**Comment by cyberjoac** [comment]
+1

**Comment by prdonahue** [comment]
+1

**Comment by Rinkana190** [comment]
+1

**Comment by kilianc** [comment]
+1

**Comment by leonard-sxy** [comment]
+1

**Comment by leonard-sxy** [comment]
So can someone explain the status of this proposal? @aanand @Vanuan @michael-k 

And actually after this I just went through these two topics also: [Deploying a registry server](https://docs.docker.com/registry/deploying/) and [#3900 - Docker compose pull does not work with custom registry](https://github.com/docker/compose/issues/3900)

It's a bit hard to understand, since docker has both the abilities 'running a registry server' and 'docker-compose(pull)', why not integrate these two seamlessly？

But still recommend this proposal: just integrate with a well-known service providers, like Github, Bitbucket, AWS, Google Cloud, Azure etc, running own registry server the speed, security gonna be  some serious problem/bottleneck.

**Comment by valiro21** [comment]
+1

**Comment by mathroc** [comment]
you can now choose the image name & tag when building a service:

> If you specify image as well as build, then Compose names the built image with the webapp and optional tag specified in image:

– https://docs.docker.com/compose/compose-file/#build

this name is then used when using `docker-compose push`

that mean you do something like this:

```yaml
services:
  service:
    build: .
    image: registry.acme.com/acme/service:latest
```

and it works !

```
# docker-compose push
Pushing service (registry.acme.com/acme/service:latest)...
The push refers to a repository [registry.acme.com/acme/service]
```

**Comment by wayoung** [comment]
If I push 3 services to a private repository using this method and a single docker-compose.yml, can I docker-compose pull all three services with just one command, or do I need to pull them all back separately?

**Comment by omercnet** [comment]
@wayoung you can simply 'docker-compose pull' to pull all the remote images

**Comment by wayoung** [comment]
That only works if I am in the same directory as the docker-compose.yml. I'm thinking of the case where I docker-compose push to the registry, then try to pull it down on another machine without the original docker-compose.yml. Is that possible?

**Comment by ijc** [comment]
Issue grooming: According to https://github.com/docker/compose/issues/1126#issuecomment-235454500 this was fixed (by providing `docker-compose push`) in 1.8 rc2. Therefore closing.
