### ISSUE TITLE
Help with License

### ISSUE THREAD

**Issue by vchhasatia** [docker/compose#11261]
### Description

Hello docker-compose team, 
I am bit confused by presence of EULA in https://github.com/docker/compose/blob/main/packaging/LICENSE. 
The package over all is shown under Apache 2.0 --> https://github.com/docker/compose/blob/main/LICENSE.

Can you please help me understand if there are any files that are covered by EULA?

**Comment by ndeloof** [comment]
EULA is about binary packages you can download from https://github.com/docker/compose/releases
source code is licensed under Apache 2.0 license
