### ISSUE TITLE
我的docker-compose停止容器好慢好慢，最慢可能到500秒停止一个容器，我尝试过重新安装docker，但是没起作用

### ISSUE THREAD

**Issue by Handikang** [docker/compose#11278]
![image](https://github.com/docker/compose/assets/42713276/902aa8f3-483e-4252-8378-61e019fa36e9)
我的docker 版本：Docker version 20.10.10, build b485636
我的docker-compose 版本： Docker Compose version v2.6.0

**Comment by Handikang** [comment]
@freeformz

**Comment by Handikang** [comment]
麻烦各位大佬解答一下

**Comment by ndeloof** [comment]
Please describe your issue in english

according to google translate:
> My docker-compose is very slow to stop a container. It may take as slow as 500 seconds to stop a container. I tried reinstalling docker, but it didn't work.

use `docker inspect <container>` to check state of the container compose can't stop. It _should_ have a 10s timeout and then get killed, but configuration can override this default

**Comment by ndeloof** [comment]
closing for lack on feedback from user. Feel free to create a new issue if relevant with a reproduction example
