### ISSUE TITLE
[BUG] CentOS repo is out of date

### ISSUE THREAD

**Issue by benoitjpnet** [docker/compose#11284]
### Description

CentOS package miss all the releases since Octoboer 2023.
Last version is 2.21.0, it should be 2.23.3.

### Steps To Reproduce

1. On a CentOS machine, follow https://docs.docker.com/compose/install/linux/#install-using-the-repository
2. You will not get the latest release

**Comment by ndeloof** [comment]
system package release is managed by https://github.com/docker/docker-ce-packaging which is aligned with Docker Engine release cycles, and as such does not offer the latest release of compose. We are working with other Docker teams to fix this and get more frequent updates
