### ISSUE TITLE
Installation on a new system

### ISSUE THREAD

**Issue by mxm199** [docker/compose#11281]
Tell me, I'm completely confused how to install docker + docker-composer on windows server core 2019?

I installed docker using the latest method from [microsoft](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1), it is installed and working.
![image](https://github.com/docker/compose/assets/133875469/bb3d3dd5-138e-48d5-95dd-593cb3d8245d)
But when installing docker, the folder "Program FIles\Docker" is not created, it is installed somewhere deeper into the system
![image](https://github.com/docker/compose/assets/133875469/9cff6aa9-3129-4b32-afc2-051e9ee31acc)
And when installing docker-compose, it swears at the absence of this folder
`Invoke-WebRequest : Could not find part of the path 'C:\Program Files\docker\docker-compose.exe'.`

What should I do? I am very used to using docker-composer on Windows Desktop Docker.

**Comment by ndeloof** [comment]
how do you install docker-compose after using this script to install docker?

**Comment by ndeloof** [comment]
Closing as requester didn't answered
