### ISSUE TITLE
Referenced as fig in brew

### ISSUE THREAD

**Issue by psykzz** [docker/compose#1129]
When installing through Homebrew, compose is referenced as fig.

**Comment by thaJeztah** [comment]
AFAIK, the Homebrew formula is not maintained by Docker/Compose itself, so I think its best to open an issue in the Homebrew repository.

**Comment by gianpaj** [comment]
I think this is already done and yes this should be raised in the homebrew repo:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fig.rb

**Comment by tomchentw** [comment]
Also note that the homebrew formula is outdated (1.2.0)

**Comment by tomchentw** [comment]
Updated! Thanks! :+1:
