### ISSUE TITLE
[DOC improvement] Error handling changed files `Cannot open: File exists`

### ISSUE THREAD

**Issue by Alexander-Garcia** [docker/compose#11304]
### Description

This isn't a bug I guess and I apologize if this shows a "duh" moment for me or is not in the right place (never really filed an issue before), but this issue and its solution were not immediately clear to me and just in case other newer docker users encounter this maybe it will help if its mentioned somewhere in the docs for `docker compose watch` 

`docker compose watch` fails to sync when updating a file if the USER instruction is set with non-root privileges.
`docker init` choosing python automatically adds an `appuser` and switches to that user to run. I left that in the Dockerfile not realizing with `docker compose watch` I would need root (or just edit) privileges. 

`ctar: app/main.py: Cannot open: File exists
tar: Exiting with failure status due to previous errors
WARN[0011] Error handling changed files for service backend_service: 1 error occurred:
        * copying files to 87e9987ce8552a75ecf042eefcae614c35821963935a36ea219214f34cb8782a: exit code 2`
      
As I read the docs for [docker compose watch](https://docs.docker.com/compose/file-watch/#prerequisites) I noticed the prerequisites do state you will need the binaries for stat, mkdir, rmdir, and tar, but I didn't connect the dots that I would need the root permissions while actively running watch and that error message above wasn't really helpful figuring out what was going on. Removing the `USER` instruction from Dockerfile fixed this of course.

### Steps To Reproduce

1. Run `docker init` and set up a python template
2. Run `docker compose watch` and edit a file that is synced. 

### Compose Version

```Text
docker compose version v2.23.3-desktop.2
docker-compose version v2.23.3-desktop.2
```

### Docker Environment

```Text
Client:
 Version:    24.0.7
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     /Users/alexandergarcia/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     /Users/alexandergarcia/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/alexandergarcia/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/alexandergarcia/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     /Users/alexandergarcia/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     /Users/alexandergarcia/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/alexandergarcia/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/alexandergarcia/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/alexandergarcia/.docker/cli-plugins/docker-scout
Server:
 Containers: 55
  Running: 22
  Paused: 0
  Stopped: 33
 Images: 184
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.5.11-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.663GiB
 Name: docker-desktop
 ID: 3cc96430-f3ff-4dcf-a730-3def88ee85fb
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Output of `docker init` using python

![image](https://github.com/docker/compose/assets/31865557/bd8cb43e-ec33-43f3-88f5-21a2b0f7f003)

**Comment by ZeitgeberH** [comment]
Same issue. The solution provided above works!

**Comment by ndeloof** [comment]
`compose watch` indeed executes commands inside your container and requires a few standard commands available to sync files. It's not required to run as root, but the target folder created by `COPY . . ` instruction is owned by root, not the `appuser` you created (this is yet another Dockerfile weirdness). A simple workaround is to change your Dockerfile as:
```
COPY . .
RUN chown -R appuser .
USER appuser
```

**Comment by ndeloof** [comment]
Makes me wonder: why don't we rely on https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/PutContainerArchive to unpack the tar inside container, without requirement to run `tar` command inside container ? PutContainerArchive actually untar from daemon in the container's filesystem, so won't suffer such a permission issue. Maybe @milas remembers this design decision ?

**Comment by Alexander-Garcia** [comment]
> `compose watch` indeed executes commands inside your container and requires a few standard commands available to sync files. It's not required to run as root, but the target folder created by `COPY . . ` instruction is owned by root, not the `appuser` you created (this is yet another Dockerfile weirdness). A simple workaround is to change your Dockerfile as:
> 
> ```
> COPY . .
> RUN chown -R appuser .
> USER appuser
> ```

@ndeloof Thanks for a proper workaround. I'm glad it was a valid issue to raise and seemingly a couple others ran into the same issue so I wasn't the only one not realizing this would happen. Appreciated.

**Comment by glours** [comment]
I'll ping the team in charge of `docker init` to be sure they used `COPY --chown` in the generated Dockerfiles

**Comment by ktzsolt** [comment]
I don't know if related but I can run `docker compose watch` with sudo only even though my user is in the docker group, all other docker commands work without sudo, as it should. I am onn Windows 10, DD4W, running the ocmmand from ubuntu 22.04 WSL2 distro.

**Comment by ndeloof** [comment]
@ktzsolt doesn't seem to be related, can you please report this in a dedicated issue with more details on the error?
