### ISSUE TITLE
[BUG] Call to kwargs_from_env is incompatible with docker>=7

### ISSUE THREAD

**Issue by iurisilvio** [docker/compose#11309]
### Description

https://github.com/docker/compose/blob/e9f9a1e9e1edabe25f3c6494aa7f3a5a5f7db7d2/compose/cli/docker_client.py#L97

Docker 7.0 don't accept the ssl_version: https://github.com/docker/docker-py/blob/6ceb08273c157cbab7b5c77bd71e7389f1a6acc5/docker/utils/utils.py#L344

It was changed here: https://github.com/docker/docker-py/commit/db4878118b02124100c669b39249f0bdeed2aad0#diff-c40bbe508dae196428f3740f4aa8fbd143f8e3c0d80aa3e6952938cb2f90addb

### Compose Version

Main branch

**Comment by felixfontein** [comment]
You are using the Python version of docker-compose, which is EOL and no longer supported. If you want to use the old docker-compose version, you need to restrict Docker SDK for Python to version < 7. (See also https://github.com/docker/docker-py/issues/3194.)

**Comment by felixfontein** [comment]
(See also #11270)
