### ISSUE TITLE
[DNS request spamming] docker service seems to be trying to lookup "mongo" dns entry

### ISSUE THREAD

**Issue by KnutssonDevelopment** [docker/compose#11310]
### Description

I recently notices that some of my hosts was spamming my dns server with lookups for mongo.<my-internal-dns-domain> After investigating this I found that it was all my hosts running docker and docker-compose.

Even with no containers running, and all containers deleted the issues is still there.

If I stop the docker service "systemctl stop docker" the dns lookups stop.

### Steps To Reproduce

As I do not really have access to install docker anywhere else I do not know if it is enough to just install docker to see the issue, but you can check by using an iptables rule to catch the lookups.

iptables -I OUTPUT -p UDP --dport 53 -m string --algo bm --string mongo -j LOG --log-uid --log-prefix "MONGO_MATCH: "
journalctl -t kernel -f

EXAMPLE OUTPUT:
Jan 02 21:34:30 hostname kernel: MONGO_MATCH: IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.53 LEN=62 TOS=0x00 PREC=0x00 TTL=64 ID=46862 DF PROTO=UDP SPT=40725 DPT=53 LEN=42 UID=0 GID=0 
Jan 02 21:34:30 hostname kernel: MONGO_MATCH: IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.53 LEN=82 TOS=0x00 PREC=0x00 TTL=64 ID=51075 DF PROTO=UDP SPT=40453 DPT=53 LEN=62 UID=0 GID=0 
Jan 02 21:34:30 hostname kernel: MONGO_MATCH: IN= OUT=eth0 SRC=192.168.0.51 DST=<ip of dns server> LEN=82 TOS=0x00 PREC=0x00 TTL=64 ID=15031 PROTO=UDP SPT=37809 DPT=53 LEN=62 UID=101 GID=103 
Jan 02 21:34:30 hostname kernel: MONGO_MATCH: IN= OUT=eth0 SRC=192.168.0.51 DST=<ip of dns server> LEN=71 TOS=0x00 PREC=0x00 TTL=64 ID=15032 PROTO=UDP SPT=37809 DPT=53 LEN=51 UID=101 GID=103

### Compose Version
```Text
root@hostname# docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.12
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
```

### Docker Environment
```Text
root@hostname# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
root@hostname# docker version
Client:
 Version:           24.0.5
 API version:       1.41 (downgraded from 1.43)
 Go version:        go1.20.3
 Git commit:        24.0.5-0ubuntu1~22.04.1
 Built:             Mon Aug 21 19:50:14 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       5d6db84
  Built:            Wed Aug 23 20:55:00 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Anything else?

I apologize if this is not the correct place to file this bugreport. I could not find any repo for dockerd, which might be the correct project. Any help is most welcome.

**Comment by ndeloof** [comment]
docker daemon repo is https://github.com/moby/moby

**Comment by KnutssonDevelopment** [comment]
> docker daemon repo is https://github.com/moby/moby

Thank you.

**Comment by KnutssonDevelopment** [comment]
Moved the issue to dockerd. https://github.com/moby/moby
