### ISSUE TITLE
是否支持使用${com.docker.compose.container-number}插值语法

### ISSUE THREAD

**Issue by only-ns** [docker/compose#11315]
### Description

我想使用多副本的方式部署来部署我的项目,但是没有一个好的方式来挂载我的日志
尝试使用${com.docker.compose.container-number}的插值语法好像并不支持!

我的docker-compose
<pre>
    volumes:
      - /opt/data/warehouse/conf/:/opt/app/conf
      - /opt/data/warehouse/logs/${com.docker.compose.container-number}/:/opt/app/logs
    networks:
      - warehouse_network
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
</pre>

docker inspect
![image](https://github.com/docker/compose/assets/42288790/9b1dab69-ad0f-44d7-98b1-8f9931515de8)

**Comment by ndeloof** [comment]
Please report bugs and feature requests in english

**Comment by ndeloof** [comment]
highly comparable requirement as https://github.com/docker/compose/issues/9026, so closing this one as a duplicate
