### ISSUE TITLE
[BUG] Binding port on an invalid IP results in binding on any interface

### ISSUE THREAD

**Issue by thorroed** [docker/compose#11329]
### Description

Using a docker-config.yml with an invalid IP (see example below "**11127.0.0.1**") results in listening on all interfaces "**0.0.0.0**". 
This is unexpected as it makes the service available to more interfaces than specified. 
I would expect that providing an invalid IP results in a error / warning message / state.

### Steps To Reproduce

This docker-compose.yml has an invalid interface IP (e.g. first octet):
`version: '2.3'

services:
  xlenz-torchserve:
    image: "pytorch/torchserve:0.5.2-gpu"
    restart: always
    ports:
      - **11127.0.0.1**:18080:8080
      - **11127.0.0.1**:18081:8081
`

this "typo" results in binding the port to "any" interface:
`docker ps

e18b034d8bea   pytorch/torchserve:0.5.2-gpu                                                      "/usr/local/bin/dock…"   3 seconds ago   Up 2 seconds   7070-7071/tcp, 8082/tcp, **0.0.0.0**:18080->8080/tcp, :::18080->8080/tcp, **0.0.0.0**:18081->8081/tcp, :::18081->8081/tcp   xxxtorchserve_1`

### Compose Version

```Text
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.12
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
```

### Docker Environment

```Text
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx

Server:
 Containers: 140
  Running: 106
  Paused: 0
  Stopped: 34
 Images: 1085
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 nvidia
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-88-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 28
 Total Memory: 125.5GiB
 Name: leia
 ID: 8bba3a8d-606c-42bb-aba4-fb5e43dc3ab1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


docker context show
default
```

**Comment by ndeloof** [comment]
You're using Docker Compose v1 which is End of Life. Please migrate to Docker Compose v2, which detect such a mistake/typo:
```
$ docker compose up
invalid IP address: 11127.0.0.1
```
