### ISSUE TITLE
[BUG] changes to docker system prune with buildkit, now deletes downloaded base images

### ISSUE THREAD

**Issue by k1w1m8** [docker/compose#11346]
### Description

In the days pre buildkit, all base images were tagged and stored in the main docker images list.

After buildkit, this no longer happens. Base images are downloaded into the buildkit cache.

https://github.com/moby/buildkit/issues/1537
https://github.com/docker/compose/issues/10206

This is problematic if you have large images and a slow download link and you run out of diskspace. Say you have a 10GB image and a 1MB/s download speed.

Previously, if you did docker system prune, the base image would be preserved, and you have easy control over whether to delete it or not at a later time

Now, if you do docker system prune, it will delete the 10GB image and you will start swearing as you wait 3 hours to redownload it.

If you have a look into the buildkit cache, there doesn't seem to be a lot of controls over which images to keep and which to prune. I don't see a way in docker buildx du to "keep base images".

Ideally there would be an option to tell compose build to "export" base images into the main docker images list to be compatible with the previous behaviour.

If that is not possible, how can we clean the build cache while keeping downloaded base images like we did before?

### Compose Version

```Text
Docker Compose version v2.21.0
```

**Comment by k1w1m8** [comment]
Seems related to https://github.com/docker/buildx/issues/1065

**Comment by ndeloof** [comment]
This indeed is a buildkit issue, not something we can have impact on from Docker Compose. If buildx had such an option, we could expose it from compose. Please report issue on docker/buildx, and if this eventually get fixed with a new feature flag, then we can adopt it on compose side.

**Comment by k1w1m8** [comment]
Thanks, raised https://github.com/docker/buildx/issues/2195

**Comment by k1w1m8** [comment]
@ndeloof thinking further here, I am using mixture of image: tags and building some images using Dockerfile FROM. Does compose use buildx to pull image: tags?
