### ISSUE TITLE
[BUG] 2.24.0 number value for environment variable replaced with '%!s(int=1)'

### ISSUE THREAD

**Issue by vdesabou** [docker/compose#11355]
### Description

I have in my docker-compose.yml file

```
    environment:
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
```

With 2.24.0 it is automatically replaced by (`docker compose config` output)

```
    environment:
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '%!s(int=1)'
```

Which makes my application fails:

```
[2024-01-16 08:28:24,693] ERROR Stopping due to error (org.apache.kafka.connect.cli.AbstractConnectCli:107)
org.apache.kafka.common.config.ConfigException: Invalid value %!s(int=1) for configuration offset.storage.replication.factor: Not a number of type SHORT
```

This is new behaviour with 2.24.0

### Compose Version

```Text
2.24.0
```

### Docker Environment

```Text
reproducible on Mac and Linux Ubuntu
```

**Comment by jhrotko** [comment]
Hello! 
There is a fixed for this. Please check this issue https://github.com/docker/compose/issues/11353 .

Thanks for reporting!
