### ISSUE TITLE
[IDEA] docker compose up --watch

### ISSUE THREAD

**Issue by olivierdalang** [docker/compose#11376]
### Description

I love the new `watch` feature !! Thanks !!!

However I feel it could be better integrated in the docker compose workflow. 

From what I understand:
- `docker compose watch` runs `docker compose up --build -d` beforehand
- `docker compose watch --no-up` doesn't start the stack at all so it can be started separately

The first is convenient, but lacks all the flexibility of docker compose up (optional `--build`, `--remove-orphans`, `--force-recreate`, `--profiles`, etc.).
The second provides all needed flexibility but requires two distinct commands as stated in #11157 (which was closed as doable with `docker compose watch --no-up & docker compose up`)

What about adding the `--watch` flag to `docker compose up` (and maybe deprecating/dropping the whole `docker compose watch` subcommand) ? Not sure about implementation, but from an user point of view it certainly would feel more natural.

**Comment by PAXANDDOS** [comment]
I was about to post this idea too!

It's annoying that I have to build all images every time I do `docker compose watch` so I thought maybe it could have the same default functionality as `docker compose up`? This means, only build images if no images are already built, or force builds with `--build`. 
We can have that and only modify the `watch` command, or as OP said, have `docker compose up --watch` which I suppose is the same as what I've described, just for the `up` command. Or both 🙃

**Comment by anentropic** [comment]
+1

I would like to be able to auto-reload containers which use a volume mount, by defining `watch` rule in the compose file, preferably without running in a special mode

currently I get error _"can't watch service "stepfunctions" without a build context"_ when trying to use it with the `amazon/aws-stepfunctions-local` mock tool which has a config file you need to pass in via volume path

it seems that it only works for containers that have a `build` directive?  This isn't spelled out in [the docs](https://docs.docker.com/compose/file-watch/) AFAICT

also it's a bit confusing how watch + `action: sync` relates to volumes... seems like a separate new way to share files into the container?

**Comment by remcokranenburg** [comment]
This seems to have been implemented now: https://github.com/docker/compose/pull/11525
