### ISSUE TITLE
[BUG] compose with missing a target port error after 2.24.1 upgrade

### ISSUE THREAD

**Issue by mathulbrich** [docker/compose#11378]
### Description

After upgrade to `2.24.1` we are facing the following error while using another file (other than `docker-compose.yaml`) to extends a service:

```
STEP 1/1 — Building & deploying
service ports services.localstack.ports.[0] is missing a target port

got unexpected error during build/deploy: command ["docker" "compose" "--project-name" "dev-env" "--project-directory" "/home/mathaus/Workspace/dev-env" "--env-file" "/home/mathaus/Workspace/dev-env/merged.env" "-f" "/home/mathaus/Workspace/dev-env/docker-compose.new.yml" "build" "localstack"] failed.
error: exit status 15

Build Failed: command ["docker" "compose" "--project-name" "dev-env" "--project-directory" "/home/mathaus/Workspace/dev-env" "--env-file" "/home/mathaus/Workspace/dev-env/merged.env" "-f" "/home/mathaus/Workspace/dev-env/docker-compose.new.yml" "build" "localstack"] failed.
error: exit status 15
```

### Steps To Reproduce

1. Create a file with services to be extended `data-services.yml`

```yaml
services:
  any-service:
    build: .
    ports:
      - 8000:8000
```

2. Create `compose.yaml`

```yaml
services:
  any-service:
    extends: { file: data-services.yaml, service: any-service }
```

3. Run `docker compose up` command

```shell
>> docker compose up
service ports services.any-service.ports.[0] is missing a target port
```

4. Run `docker compose up` in a older version
```shell
>> docker compose up
[+] Building 0.0s (1/1) FINISHED
 => [any-service internal] load build definition from Dockerfile 0.0s
 => => transferring dockerfile: 2B     
```

5. Note the differences

* Compose is not building anymore in the new version

### Compose Version

```Text
Docker Compose version v2.24.1
```

**Comment by anapdh** [comment]
I'm facing the same issue. Do you have any idea when a new patch will be released?

**Comment by Porshe** [comment]
The same issue

**Comment by jonricha** [comment]
Same issue...also, what version can I roll back to, to avoid this issue?

**Comment by wonrax** [comment]
Downgraded to 2.21.0 on Ubuntu since it's the second latest version and it started to work again. Also wonder why the there's a gap.
```sh
$ apt-cache madison docker-compose-plugin
docker-compose-plugin | 2.24.1-1~ubuntu.22.04~jammy | https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages
docker-compose-plugin | 2.21.0-1~ubuntu.22.04~jammy | https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages
docker-compose-plugin | 2.20.2-1~ubuntu.22.04~jammy | https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages
docker-compose-plugin | 2.19.1-1~ubuntu.22.04~jammy | https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages
```

**Comment by Takerman** [comment]
I have the same issue. For me it worked version [2.23.3](https://docs.docker.com/compose/release-notes/#2233)
The coomand that I ran was:
```
curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

**Comment by lilleman-tw** [comment]
Why is this closed? Quoting ports does not seem to help.

**Comment by ndeloof** [comment]
issue has been closed as https://github.com/compose-spec/compose-go/pull/537 has been merged, next release will include the fix

**Comment by DerGary** [comment]
when is the next release scheduled? All our pipelines are erroring out due to this issue

**Comment by fwolfst** [comment]
I am still puzzled, but afaics moving the `ports` definition to the `compose.yml` file (vs in the "file to extend from) service definitions fixes the issue/is a workaround. In the OP example it would mean delete the ports definition in `data-services.yml` but define in `compose.yml`.

**Comment by jlongo-encora** [comment]
When is the next release?
