### ISSUE TITLE
Inconsistency in depends_on with service_healthy Condition Across Different Docker Versions

### ISSUE THREAD

**Issue by cubxxw** [docker/compose#11386]
https://github.com/moby/moby/issues/47134

**Comment by ndeloof** [comment]
> Is there a specific version of Docker or Docker Compose where the integration of health checks with depends_on (service_healthy condition) is known to work consistently?

Docker compose v2.x supports `service_healthy` condition (until we get some regression)

> Are there any known issues or limitations with this functionality in certain versions of Docker or Docker Compose that might explain the observed inconsistencies?

I don't think so

> Could you provide guidance or best practices on ensuring consistent behavior of depends_on with health checks across different environments?

Use same version everywhere, and use a staging environment to test upgrades and double check any potential regression/change in behavior
