### ISSUE TITLE
[BUG] `addr` option in a CIFS volume no longer works

### ISSUE THREAD

**Issue by marsara9** [docker/compose#11388]
### Description

I just recently updated the following packages:
```
docker-buildx-plugin/jammy 0.12.1-1~ubuntu.22.04~jammy amd64 [upgradable from: 0.11.2-1~ubuntu.22.04~jammy]
docker-ce-cli/jammy 5:25.0.0-1~ubuntu.22.04~jammy amd64 [upgradable from: 5:24.0.7-1~ubuntu.22.04~jammy]
docker-ce-rootless-extras/jammy 5:25.0.0-1~ubuntu.22.04~jammy amd64 [upgradable from: 5:24.0.7-1~ubuntu.22.04~jammy]
docker-ce/jammy 5:25.0.0-1~ubuntu.22.04~jammy amd64 [upgradable from: 5:24.0.7-1~ubuntu.22.04~jammy]
docker-compose-plugin/jammy 2.24.1-1~ubuntu.22.04~jammy amd64 [upgradable from: 2.21.0-1~ubuntu.22.04~jammy]
```

And now none of my CIFS volumes that are mounting via hostname are working as I get the following error upon calling `sudo docker compose up -d`:
```
Error response from daemon: failed to mount local volume: mount //<ip address>/media:/var/lib/docker/volumes/docker_media/_data, data: addr=<hostname>,username=<user>,password=********,uid=1000,gid=1000,vers=3.0: invalid argument
```
any machine that has yet to upgrade the above packages continues to work.

For now replacing the hostname in the following compose with the actual IP address, and removing the `addr` option resolves the issue:
```
  media:
    driver_opts:
      type: cifs
      o: addr=<hostname>,username=${FILES_USERNAME},password=${FILES_PASSWORD},rw,uid=1000,gid=1000,vers=3.0
      device: //<hostname>/media
```

### Steps To Reproduce

1. Upgrade to the latest version of docker
2. try and mount any CIFS volume using the `addr` option flag.
4. Docker will then fail to create the container with an `invalid argument` error.

### Compose Version

```Text
Docker Compose version v2.24.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 25.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.39GiB
 Name: ****
 ID: C2OQ:GA3B:TUG4:DSP7:A4HC:WCH7:JI54:FDRI:OHXF:BI43:PBZD:EVNA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by marsara9** [comment]
So I already tried these steps, but I'll admit by knowledge with the CLI is a bit lacking compared to just using compose:
```
docker compose down
docker volume rm docker_media
docker volume create --driver local --opt type=cifs --opt device=//files.my.domain.com/media --opt o=addr=files.my.domain.com,username=****,password=****,rw,uid=1000,gid=1000,vers=3.0 --name docker_media
docker compose up -d
```

The `docker volume create` doesn't output any errors, but I still get the `Invalid argument` error upon running `docker compose up`.

**Comment by ndeloof** [comment]
right, `docker volume create` just register a volume (configuration), but does not actually validate the arguments. Need to be used. Try running `docker run -v docker_media:/foo alpine` to check volume can be used by a container when used without compose

**Comment by marsara9** [comment]
Yep, same error, `invalid argument`.

But tried a few other tests... I also tried running
`mount -t cifs //files.my.domain.com/media /mnt/files/media -o addr=files.my.domain.com,username=****,password=****,rw,uid=1000,gid=1000,vers=3.0`
and I would get the same error.  Removing the `addr` option here allows the mount to work as expected.

Knowing that Docker should just be passing the option arguments to mount, I tried just keeping the hostname but dropping the addr option altogether so I end up with something like this:
```
sudo docker volume create --driver local --opt type=cifs --opt device=//files.my.domain.com/media --opt o=username=****,password=****,rw,uid=1000,gid=1000,vers=3.0 --name test
sudo docker run --name alpine -v test:/foo alpine
```
And it works?  So I'm guessing something in docker engine was updated to allow it work with the latest version of `mount.cifs`?

p.s. I also updated my docker compose to do the same and with also successful results.  Example section from my compose now:
```
volumes:
  media:
    driver_opts:
      type: cifs
      o: username=${FILES_USERNAME},password=${FILES_PASSWORD},rw,uid=1000,gid=1000,vers=3.0
      device: //files.my.domain.com/media
```

(Closing the issue as it looks like the docker engine, again, was updated to work with the latest version of `mount.cifs` and most of the existing documentation around how to mount CIFS volumes may be out of date)

**Comment by brandonkirsch** [comment]
To confirm:  mount.cifs removed the 'addr' option recently.  This morning I ran OS updates and found that even the plain old "mount" command no longer worked due to 'addr' being present in my options.

The solution is to simply remove 'addr' from options.

If you previously specified an IP address for "device", you can now replace it with the DNS name and it will resolve as expected.
