### ISSUE TITLE
[BUG] "failed to create network: Pool overlaps with other one on this address space" after update

### ISSUE THREAD

**Issue by rtfm98** [docker/compose#11401]
### Description

A few days ago I tried to update to the latest docker-ce, docker-compose-plugin and containerd.io versions and after that, mailcow-dockerized failed to start with docker compose:

> failed to create network mailcowdockerized_mailcow-network: Error response from daemon: Pool overlaps with other one on this address space

I checked multiple times that I don't have any other network in this range. I also changed the used ip range of mailcow, but it didn't start either.

The only solution was: downgrade to the last installed versions and put the packages "on hold". After that, mailcow started as it used to.

### Steps To Reproduce

1. Before the package update: start mailcow-dockerized via docker compose
2. Update to latest docker-ce, docker-compose-plugin and containerd.io packages
3. Try to start mailcow-dockerized again

### Compose Version

```Text
Before update:
> Docker Compose version v2.21.0

After update:
> Docker Compose version 2.24.1

After downgrade (status quo):
> Docker Compose version v2.21.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 21
  Running: 21
  Paused: 0
  Stopped: 0
 Images: 85
 Server Version: 24.0.7 (after downgrade)
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dd1e886e55dd695541fdcd67420c2888645a495
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-17-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.62GiB
 Name: HOST.DOMAIN.de
 ID: 7J6H:JJ7I:TYSA:EH3E:ZWGJ:F6M7:UR5N:HEPB:I4T3:4HP4:PMAM:ORGU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: fals
```

**Comment by aequitas** [comment]
I'm also experiencing this issue when setting up a Compose project that contains both IPv4 and IPv6 networks. Compose version v2.23.3 works fine, but v2.24.5 fails. I've not tested additional versions yet.

**Comment by rtfm98** [comment]
@aequitas In the meantime I was able to update to `2.25.0-1~debian.12~bookworm` without triggering the mentioned problem with the network
