### ISSUE TITLE
[BUG] Missing information in description of docker compose up --wait-timeout

### ISSUE THREAD

**Issue by rreich** [docker/compose#11418]
### Description

The description of `--wait-timeout` looks like this:
> timeout waiting for application to be running|healthy.

It would be really helpful if it included the default timeout and the expected time unit.

### Steps To Reproduce

1. call `docker compose up --help`
2. wonder how to use `--wait-timeout` correctly

### Compose Version

```Text
Docker Compose version 2.20.2+ds1-0ubuntu1~22.04.1
```

### Docker Environment

```Text
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
```

**Comment by ndeloof** [comment]
`--wait-timeout` is to be used with the `--wait` flag

```
      --wait                      Wait for services to be running|healthy. Implies detached mode.
      --wait-timeout int          Maximum duration to wait for the project to be running|healthy.
```
Isn't this clear enough? Feel free to open a Pull-request if you have in mind a better wording
