### ISSUE TITLE
Merge multi-value options properly when extending

### ISSUE THREAD

**Issue by aanand** [docker/compose#1143]
Currently, `environment` and `volumes` are merged when a service `extends` another. With other multi-value options, however, no merging is done - instead, the new list completely replaces the old. The following need to be fixed:

- `external_links`
- `ports`
- `expose`
- `labels` (do this in #1139)
- `dns`
- `dns_search`

**Comment by marun** [comment]
#dibs

**Comment by aanand** [comment]
Closed by #1226 - sorry @marun!

**Comment by marun** [comment]
I snooze, I lose. :)
