### ISSUE TITLE
[BUG] Inconsistency with compose behaviour since 2.24 using extends

### ISSUE THREAD

**Issue by kpearkes** [docker/compose#11439]
### Description

Running the same command results in different output and inconsistent behaviour since upgrading from docker-compose-plugin 2.21.0 to 2.24.2. This occurs when a service is extended on already extended services. Example test4 -> test3 -> test2 -> test1. Running `docker compose up test4` and `docker compose down test4` a few times and you'll notice that sometimes the configurations defined in test1 aren't included in the test4 container. 

Examples:
If the image is only defined in the test1 service. running the up and down commands a few times sometimes results in service `"test4" has neither an image nor a build context specified: invalid compose project`.

If the image is specified at the test4 level, instead of test1, the container will be created, however it will sometimes be missing the the test1 bind mounts as defined in the steps to reproduce below.

If only 3 levels of extend are defined test3 -> test2 -> test1 then I do not get this issue. I expect that I should be able to extend a service an arbitrary number of times. 

### Steps To Reproduce

create a file common-service.yaml
```
services:
  test1:
    image: ubuntu:20.04
    volumes:
      - ./test1:/test1
    
  test2:
    extends: test1
    volumes:
      - ./test2:/test2
  
  test3:
    extends: test2
    volumes:
      - ./test3:/test3
```
create another file compose.yaml

```
services:
  test4:
    extends:
      file: common-service.yaml
      service: test3
```

then run `docker compose up test4` and `docker compose down test4` a few times and you should sometimes get an error `"test4" has neither an image nor a build context specified: invalid compose project`

### Compose Version

```Text
Docker Compose version v2.24.2
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan
WARNING: Plugin "/usr/libexec/docker/cli-plugins/docker-compose_old" is not valid: plugin candidate "compose_old" did not match "^[a-z][a-z0-9]*$"

Server:
 Containers: 11
  Running: 1
  Paused: 0
  Stopped: 10
 Images: 56
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 nvidia
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.15.0-91-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 62.64GiB
 Name: kpearkes-TRX40-AORUS-MASTER
 ID: LZ54:FNTW:PA4D:V6D5:EYLU:YNR3:S2JN:N3XE:SRT4:UNCL:27RZ:O77C
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
AFAICT this is already fixed by https://github.com/compose-spec/compose-go/pull/547
