### ISSUE TITLE
[BUG] Error message is not descriptive

### ISSUE THREAD

**Issue by kiskele** [docker/compose#11445]
### Description

With the issue mentioned in https://github.com/docker/compose/issues/11444
If the file parameter of extends can be found in the project root as well, than incorrect yaml file is loaded.
If the loaded file has no service: definition, only an include: directive, than I get the following error message, which is hard to understand or debug:

`panic: interface conversion: interface {} is nil, not map[string]interface {}`

It would be good to give some information about which file has the issue, and which part is missing

### Steps To Reproduce

Create docker-compose.yaml in the project root ($COMPOSE_PROJECT_ROOT/docker-compose.yaml), with content:
```
include:
  - mysql/docker-compose.yaml
  - app/docker-compose.yaml
```

Create mysql service definition ($COMPOSE_PROJECT_ROOT/mysql/docker-compose.yaml):
```
services:
  mysql:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
```

Create common service definition ($COMPOSE_PROJECT_ROOT/app/docker-compose.common.yaml):
```
services:
  app:
    image: php:fpm
    volumes:
      - .:/var/www/html
```

Create app service definition ($COMPOSE_PROJECT_ROOT/app/docker-compose.yaml):
 ```
services:
  app:
    extends:
      file: ./docker-compose.common.yaml
      service: app
```

Create an empty $COMPOSE_PROJECT_ROOT/docker-compose.yaml file

Execute:
```
docker compose config
```

### Compose Version

```Text
Docker Compose version v2.24.3-desktop.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/kiskele/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     /Users/kiskele/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     /Users/kiskele/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/kiskele/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/kiskele/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/kiskele/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/kiskele/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/kiskele/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/kiskele/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/kiskele/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/kiskele/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 14
  Running: 7
  Paused: 0
  Stopped: 7
 Images: 34
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: fcrm633sy3thn784xw0w0u4ga
  Is Manager: true
  ClusterID: n19spn8qor5x7m7gjgsuybwjx
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 5.79GiB
 Name: docker-desktop
 ID: 44087fe9-38b9-47af-9781-aa6e91349bac
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Anything else?

See the full stack trace here:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/compose-spec/compose-go/v2/loader.ApplyExtends({0x104a306e8?, 0x1400052fd40}, 0x1400068dda0?, 0x1400029ccb0, 0x1400052bcc8?, {0x1400052be70, 0x1, 0x1029afd5c?})
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.2/loader/extends.go:96 +0xb58
github.com/compose-spec/compose-go/v2/loader.loadYamlModel.func1({0x10466da80?, 0x14000291c20?}, {0x1400052be70, 0x1, 0x1})
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.2/loader/loader.go:327 +0x10c
github.com/compose-spec/compose-go/v2/loader.loadYamlModel({0x104a30720, 0x140005404b0}, {{0x0, 0x0}, {0x14000814e00, 0x28}, {0x1400052fb30, 0x1, 0x1}, 0x1400052fb60}, ...)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.2/loader/loader.go:371 +0x604
github.com/compose-spec/compose-go/v2/loader.ApplyInclude({0x104a30720, 0x140005404b0}, {{0x0, 0x0}, {0x14000558930, 0x16}, {0x1400068c150, 0x1, 0x1}, 0x1400004f230}, ...)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.2/loader/include.go:101 +0x5a4
github.com/compose-spec/compose-go/v2/loader.loadYamlModel({0x104a30720, 0x140005404b0}, {{0x0, 0x0}, {0x14000558930, 0x16}, {0x1400068c150, 0x1, 0x1}, 0x1400004f230}, ...)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.2/loader/loader.go:389 +0x46c
github.com/compose-spec/compose-go/v2/loader.load({0x104a30720, 0x140005404b0}, {{0x0, 0x0}, {0x14000558930, 0x16}, {0x1400068c150, 0x1, 0x1}, 0x1400004f230}, ...)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.2/loader/loader.go:423 +0x2ec
github.com/compose-spec/compose-go/v2/loader.LoadWithContext({0x104a30720, 0x140005404b0}, {{0x0, 0x0}, {0x14000558930, 0x16}, {0x1400068c150, 0x1, 0x1}, 0x1400004f230}, ...)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.2/loader/loader.go:289 +0x394
github.com/compose-spec/compose-go/v2/cli.ProjectFromOptions(0x14000698980)
	github.com/compose-spec/compose-go/v2@v2.0.0-rc.2/cli/options.go:434 +0x484
github.com/docker/compose/v2/cmd/compose.(*ProjectOptions).ToProject(0x140004fc960, {0x104a43100?, 0x140006f6000?}, {0x105b7a8a0, 0x0, 0x0}, {0x1400035c380?, 0x7?, 0x8?})
	github.com/docker/compose/v2/cmd/compose/compose.go:216 +0x290
github.com/docker/compose/v2/cmd/compose.(*configOptions).ToProject(0x1400052d758, {0x104a30720?, 0x140005404b0}, {0x104a43100, 0x140006f6000}, {0x105b7a8a0, 0x0, 0x0}, {0x0, 0x0, ...})
	github.com/docker/compose/v2/cmd/compose/config.go:62 +0x2a4
github.com/docker/compose/v2/cmd/compose.runConfig({0x104a30720, 0x140005404b0}, {0x104a43100?, 0x140006f6000?}, {0x104a49130, 0x140004943c0}, {0x140004fc960, {0x1040bb516, 0x4}, {0x0, ...}, ...}, ...)
	github.com/docker/compose/v2/cmd/compose/config.go:128 +0x80
github.com/docker/compose/v2/cmd/compose.configCommand.func2({0x104a30720?, 0x140005404b0?}, {0x105b7a8a0?, 0x1400000e3f0?, 0x140000021a0?})
	github.com/docker/compose/v2/cmd/compose/config.go:103 +0xd4
github.com/docker/compose/v2/cmd/compose.configCommand.Adapt.func4({0x104a30720?, 0x140005404b0?}, 0x2?, {0x105b7a8a0?, 0x0?, 0x0?})
	github.com/docker/compose/v2/cmd/compose/compose.go:108 +0x3c
github.com/docker/compose/v2/cmd/compose.configCommand.Adapt.AdaptCmd.func7(0x0?, {0x105b7a8a0, 0x0, 0x0})
	github.com/docker/compose/v2/cmd/compose/compose.go:87 +0x114
github.com/docker/compose/v2/cmd/cmdtrace.Setup.wrapRunE.func2(0x140006f6a00?, {0x105b7a8a0?, 0x0?, 0x0?})
	github.com/docker/compose/v2/cmd/cmdtrace/cmd_span.go:84 +0x58
github.com/spf13/cobra.(*Command).execute(0x140002f0600, {0x1400047c910, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x140000d9500)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x104a43100?, 0x140004e2000, {{0x1040bc00a, 0x5}, {0x1040c5aac, 0xb}, {0x104402f80, 0x11}, {0x0, 0x0}, ...})
	github.com/docker/cli@v25.0.0+incompatible/cli-plugins/plugin/plugin.go:64 +0x124
github.com/docker/cli/cli-plugins/plugin.Run(0x104a02f30, {{0x1040bc00a, 0x5}, {0x1040c5aac, 0xb}, {0x104402f80, 0x11}, {0x0, 0x0}, {0x0, ...}})
	github.com/docker/cli@v25.0.0+incompatible/cli-plugins/plugin/plugin.go:77 +0xec
main.pluginMain()
	github.com/docker/compose/v2/cmd/main.go:37 +0x98
main.main()
	github.com/docker/compose/v2/cmd/main.go:94 +0x1a4

**Comment by ndeloof** [comment]
This `panic` has been fixed, and error reporting has been improved (you should now get some more descriptive `services FOO must be a mapping` when compose file used by `extends` is invalid)
