### ISSUE TITLE
Find a better way to test against dev Docker 

### ISSUE THREAD

**Issue by aanand** [docker/compose#1144]
Shoving the binary in the repo is really ugly, but curl'ing from https://master.dockerproject.com is unstable.

**Comment by thaJeztah** [comment]
😢 looks like something that should be solved somehow; Apart from Compose, various other projects (Swarm, Kitematic) will probably need a way to run tests against a pre-release Docker as well.

**Comment by dnephin** [comment]
Curling from `get.docker.com` has been working for us I think, right?

And #1783 will make this better.  Going to close since I think this isn't an issue anymore

**Comment by aanand** [comment]
I'd love to automate the process of watching for new releases/RCs and opening PRs to test against them, but that's a pretty hairy yak.
