### ISSUE TITLE
[BUG] <title> problema al flashear la tarjeta sd

### ISSUE THREAD

**Issue by DANILO12-CELL** [docker/compose#11458]
### Description

hola me podrian guiar tengo un problema al momento de flashear la tarjeta sd me sale este error de codigo.
Traceback (most recent call last):
    :    File "/home/danilov2/.local/lib/python3.10/site-packages/dt_shell/main.py", line 41, in cli_main
    :      cli_main_()
    :    File "/home/danilov2/.local/lib/python3.10/site-packages/dt_shell/main.py", line 183, in cli_main_
    :      shell.onecmd(cmdline)
    :    File "/usr/lib/python3.10/cmd.py", line 217, in onecmd
    :      return func(arg)
    :    File "/home/danilov2/.local/lib/python3.10/site-packages/dt_shell/cli.py", line 288, in <lambda>
    :      do_command_lam = lambda s, w: do_command(klass, s, w)
    :    File "/home/danilov2/.local/lib/python3.10/site-packages/dt_shell/dt_command_abs.py", line 48, in do_command
    :      cls.command(shell, args)
    :    File "/home/danilov2/.dt-shell/commands-multi/daffy/init_sd_card/command.py", line 349, in command
    :      data.update(step2function[step_name](shell, parsed, data))
    :    File "/home/danilov2/.dt-shell/commands-multi/daffy/init_sd_card/command.py", line 648, in step_setup
    :      with open(data["disk_metadata"], "rt") as fin:
    :  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/duckietown/dts/init_sd_card/dt-nvidia-jetpack-v1.3.0-4gb.json'

dts :  To report a bug, please also include the contents of /home/danilov2/shell-debug-info.txt

**Comment by ndeloof** [comment]
unrelated to docker compose
