### ISSUE TITLE
[BUG] Incorrect Circular Reference Detection when extending docker compose files

### ISSUE THREAD

**Issue by pinghedm** [docker/compose#11469]
### Description

I just upgraded to compose v2.24.5 from v2.24.2 and docker compose now reports a circular reference trying to run my services.  I have a a docker compose file extending one in a subdirectory which itself extends a sibling file.  

As far as I can tell there is no circular dependency, just a straight line of the 3 files extending the next one down (and it worked ok prior to the upgrade).  I tried replacing the `file` key in the extends attr with the absolute path, just in case (I saw some other issues regarding possibly confusing handling of relative paths in chained extensions), but it did not make a difference.  

I don't know how to debug this further, but I'm happy to give any additional information I can.  Thanks!

### Steps To Reproduce

Here is a minimal reproduction

```
project/
    docker-compose.yml
    backend/
        docker-compose.yml
        docker-compose.base.yml
```

The root docker compose file looks like this

```
version: '3.9'

services:
  backend:
    extends:
      file: backend/docker-compose.yml
      service: backend

```

backend/docker-compose.yml is

```
version: '3.9'

services:
  backend:
    extends:
      file: ./docker-compose.base.yml
      service: backend

```

and backend/docker-compose.base.yml file is

```
version: '3.9'

services:
  backend:
    image: hello-world

```

Running `docker compose run backend` returns

```
Circular reference:
  backend in [/path/to/root]/docker-compose.yml
  extends backend in [/path/to/root]/docker-compose.yml
```

On version 2.24.2 this succeeds.  On 2.24.1 and 2.24.0 it says 'can not read cannot read ./docker-compose.base.yml`, though I gather that 2.24.2 was fixing that.  On 2.23.3 it runs correctly (I've been using a similar pattern for a while; 2.23.3 is the earliest one I checked explicitly for this report but I don't think that's an exhaustive list of versions for which this works)

### Compose Version

```Text
$ docker compose version
Docker Compose version v2.24.5
```
```


### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 1
  Paused: 0
  Stopped: 9
 Images: 6
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: sysbox-runc io.containerd.runc.v2 runc runsc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-14-generic
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.49GiB
 Name: danny-Galago-Pro
 ID: PE4J:47TP:ND6J:P2CS:ZU6C:UGFL:DWQ4:L7GS:PWBK:WA7Z:RVEH:5435
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
```


### Anything else?

_No response_

**Comment by ndeloof** [comment]
this is actually fixed by compose-go/v2.0.0-rc.4, see https://github.com/docker/compose/pull/11470

**Comment by edurenye** [comment]
Thanks for fixing this but maybe we would need tests in place so this does not get broken again.
Also I do not see why upgrade to unstable dependencies.

**Comment by ndeloof** [comment]
@edurenye the whole purpose of v2.24 release is to rely on compose-go/v2, but as we expected the need for more refactoring and breaking changes, we didn't made a v2.0.0 release. No relation with some "unstable" status

**Comment by robertlagrant** [comment]
Just as a small additional data point, I've had the same issue. Thanks for raising this, and for the fix in advance!

**Comment by stlehmann** [comment]
I got the same issue on Docker Desktop 4.27.2. Is there a way to upgrade docker compose on Docker Desktop to fix this bug?

**Comment by rismanma1** [comment]
@pinghedm I am using Docker on RHEL. I tried pulling the (recently published) latest version today, 2.24.6, of the docker-compose-plugin package, and it worked for me. I didn't receive the "Circular reference" error that I had gotten while using 2.24.5.

**Comment by excitoon** [comment]
Funny thing, `extends` is absent in version 3.x, but still works

**Comment by ndeloof** [comment]
@excitoon `version` is obsolete attribute, and is ignored when parsing a compose file
