### ISSUE TITLE
[BUG] New scale down sorting is done in the wrong order for the logic of stopping containers that occurs afterwards

### ISSUE THREAD

**Issue by Adam-Carr** [docker/compose#11460]
### Description

Seeing this feature was added i've updated to the latest docker engine and compose versions and tried including this in our deployment scripts. I've found though if i scale up to 2 instances, then scale down to 1, the newest container is the one that's removed.

I believe from looking at the code (bare in mind i don't ever work with go so apologies if i've missed anything obvious) the issue seems to be we're sorting the list of containers in ascending date created order. After this, we loop through and if the collection index equal to or above the desired scale number, we remove the containers, so new ones are removed instead of older containers.

To resolve i'm guessing the sort could be improved to sort by date descending?

The sort logic:
```go
sort.Slice(containers, func(i, j int) bool {
    return containers[i].Created < containers[j].Created
})
```

The loop following:
```go
for i, container := range containers {
    if i >= expected {
        // Scale Down
        container := container
        traceOpts := append(tracing.ServiceOptions(service), tracing.ContainerOptions(container)...)
        eg.Go(tracing.SpanWrapFuncForErrGroup(ctx, "service/scale/down", traceOpts, func(ctx context.Context) error {
            return c.service.stopAndRemoveContainer(ctx, container, timeout, false)
        }))
        continue
    }
...
```

### Steps To Reproduce

1. Create a compose file with single service and no scale options set, then run compose up to launch the container.
2. Use `docker compose up --scale (service-name)=2` which will launch a second container for the same service.
3. Now this has been confirmed to be running, scale back down to 1 instance.
4. The newer container is removed.

### Compose Version

```Text
Docker Compose version v2.24.5
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 37
  Running: 37
  Paused: 0
  Stopped: 0
 Images: 38
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-146-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 14.64GiB
 Name: dev-03
 ID: 8b38f69f-2080-40b4-b7d8-2486ef736685
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by ndeloof** [comment]
As you run `docker compose up` all running container will be checked to be consistent with the configuration and image digest set by your compose.yaml file, so whatever container is added/removed, those _should_ be all strictly identical. What is then the benefits to remove the older vs the newest one ?

**Comment by Adam-Carr** [comment]
> As you run `docker compose up` all running container will be checked to be consistent with the configuration and image digest set by your compose.yaml file, so whatever container is added/removed, those _should_ be all strictly identical. What is then the benefits to remove the older vs the newest one ?

Partially I was flagging this as it doesn't do what the release notes say it should do. Originally though i ended up looking into this because it seems the checking of the docker image used being the correct version occurs after it's scaled down, and as it's removing the newest container first, the container that's left running is now out of date.

This is the output from my pipeline where the image used with the `latest` tag has been updated in the registry, I attmept to scale up, then scale back down afterwards expecting the newest version to be running with zero downtime.

> servicename Pulling 
 servicename Pulled 
 Container service-1  Running
 Container service-2  Creating
 Container service-2  Created
 Container service-2  Starting
 Container service-2  Started
 Container service-2  Waiting
 Container service-1  Waiting
 Container service-2  Healthy
 Container service-1  Healthy
c866909729ad
 servicename Pulling 
 servicename Pulled 
 Container service-1  Created
 Container service-1  Starting
 Container service-1  Started
 Container service-1  Waiting
 Container service-1  Healthy
Cleaning up project directory and file based variables
Job succeeded

What it seems to be doing:
- Container 1 was already running, this is the older version of the image
- It scales to two using `no-recreate` so it doesn't affect container 1
- It pulled the latest image to create container 2 and waits for it to become healthy
- It then scales down to 1 instance again
- First it removes the latest container (due to the sorting logic added in docker compose), rather than the oldest
- Then once it's scaled down, it checks if it needs to recreate the container at which point it then does because the only container left is the oldest and the docker image used is out of date.

So we end up with downtime instead of the desired scenario of a no downtime deployment.

**Comment by ndeloof** [comment]
> the checking of the docker image used being the correct version occurs after it's scaled down, and as it's removing the newest container first, the container that's left running is now out of date.

good point. That's bad, the obsolete one(s) should be selected first. Let me look into this

**Comment by milas** [comment]
This fix has been included in Compose [2.24.7+](https://github.com/docker/compose/releases/latest). If you continue to have problems after upgrading, comment here and we can re-open the issue or create a new one as appropriate. Thanks for the report!

**Comment by iC00kScripts** [comment]
Hi,

The exact scenario described is still happening.

**Comment by iC00kScripts** [comment]
@Adam-Carr How were you able to resolve the issue on your end?

**Comment by ndeloof** [comment]
@iC00kScripts tested but can't reproduce:
```
$ docker compose up --scale base=2 -d
[+] Running 2/2
 ✔ Container truc-base-1  Started                                          0.1s 
 ✔ Container truc-base-2  Started                                          0.2s 

$ docker compose up --scale base=4 -d
[+] Running 4/4
 ✔ Container truc-base-1  Running                                          0.0s 
 ✔ Container truc-base-2  Running                                          0.0s 
 ✔ Container truc-base-4  Started                                          0.2s 
 ✔ Container truc-base-3  Started                                          0.3s 

$ docker compose up --scale base=4 -d
[+] Running 4/4
 ✔ Container truc-base-1  Running                                          0.0s 
 ✔ Container truc-base-2  Running                                          0.0s 
 ✔ Container truc-base-3  Running                                          0.0s 
 ✔ Container truc-base-4  Running                                          0.0s 

$ docker compose up --scale base=2 -d
[+] Running 4/4
 ✔ Container truc-base-1  Running                                          0.0s 
 ✔ Container truc-base-2  Running                                          0.0s 
 ✔ Container truc-base-4  Removed                                          0.2s 
 ✔ Container truc-base-3  Removed                                          0.2s 
```

**Comment by iC00kScripts** [comment]
Container truc-base-1 and truc-base-2 should have been removed in the your last command instead of 3 & 4

**Comment by mbrodala** [comment]
Supposedly continued in https://github.com/docker/compose/issues/11781
