### ISSUE TITLE
Run tests against multiple versions of python

### ISSUE THREAD

**Issue by dnephin** [docker/compose#1147]
The new jenkins suite runs against multiple versions of docker, but I believe it only runs on python 2.7.

We should run the test suite (at the very least the unit test suite + flake8) against 2.6, 3.3, 3.4 and pypy.

**Comment by dnephin** [comment]
Related to #440

**Comment by funkyfuture** [comment]
i have a fix that works. should i create a pull request against the upstream's master or your Python3-branch?

while a PR against upstream would enforce people to take care of compatibility. but while the compatibility is not achieved yet, it may be better to compare against your branch.

**Comment by dnephin** [comment]
If you want to submit a new PR to upstream master that is actually easier for me. I can discard my PR.

**Comment by funkyfuture** [comment]
i meant a PR that only includes the change of the testing-setup, not the code-changes for Py3-compatibility itself.

but hey, i can open both. :-D

**Comment by dnephin** [comment]
Oh, that would be great too!

**Comment by dnephin** [comment]
This change has been included in #440, Thanks @funkyfuture !

**Comment by dnephin** [comment]
Done since #440 was merged
