### ISSUE TITLE
Use argparse for command-line parsing

### ISSUE THREAD

**Issue by wernight** [docker/compose#1150]
[argparse](https://docs.python.org/3/library/argparse.html) is very powerful, supports sub-commands, and it's built-in Python. It's would be good to use it instead of the current solution because it would also make auto-completion free for Bash/ZSH/... using:

    $ pip install argcomplete

    # After initialiazing argparser:
    import argcomplete
    argcomplete.autocomplete(parser)

    $ register-python-argcomplete docker-compose >_docker-compose

That generated script can be used in Bash and works in ZSH with `bashcompinit`.

**Comment by srinatar** [comment]
+kind/enhancement

**Summary**: docker-compose can support auto completion

**Proposed solution**: docker-compose currently does not allow for users to take advantage of SHELL provided auto completion capabilities.  docker-compose can leverage the python module - argcomplete . this will help users to more easily consume our interfaces.

**Comment by srinatar** [comment]
+exp/novice

**Comment by dnephin** [comment]
Compose has bash completion: https://github.com/docker/compose/tree/master/contrib/completion/bash

**Comment by wernight** [comment]
Yes I saw that but ZSH `bashcompinit` doesn't seem to like it. Given that I know that `argparse` works really well and supports Bash and ZSH well I'm suggesting this change.

**Comment by funkymonkeymonk** [comment]
#dibs

**Comment by nugend** [comment]
I'm working on this with @funkymonkeymonk and we think we can auto-generate completion off of the docopt string but we're hitting a bit of a wall with the auto completion generator. There might be a bug in the generator that needs to be worked out.

**Comment by wernight** [comment]
If you use `argparse` you simply do:

    $ pip install argcomplete
    $ register-python-argcomplete my_script >_my_script

Note: `my_script` should be in the PATH, else edit the generated script.

Prepend to `_my_script` for ZSH support:

````
# For ZSH
if [[ -n ${ZSH_VERSION-} ]]; then
    if ! bashcompinit >/dev/null 2>&1; then
        autoload -Uz bashcompinit
        bashcompinit
    fi
fi

…
````

Then from Bash or ZSH simply do: `source /path/to/_my_script`. Users don't need to install `argcomplete`.

**Comment by sdurrheimer** [comment]
Just in case, I have published a first version of a zsh completion's script : https://github.com/sdurrheimer/docker-compose-zsh-completion

**Comment by chkumar246** [comment]
What about using docopt?

**Comment by nugend** [comment]
I've figured out what the issue was with the docopt completion generator: The docopt that compose is using isn't completely idiomatic.

I'm working on reorganizing the docopt string and will then write a short script to generate the autocompletions for both bash and zsh.

The docopt completion generator is available here: [Infinidat/infi.docopt_completion](https://github.com/Infinidat/infi.docopt_completion)

**Comment by UserTaken** [comment]
@sdurrheimer Nice work on ZSH completion so consider creating a PR for oh-my-zsh to added that as a plugin for more people to enjoy.

**Comment by dnephin** [comment]
Compose already has both bash and zsh completion (https://docs.docker.com/compose/completion/), and we haven't really had any issues with the `docopt` option parsing, so I'm going to close this as a wont fix.
