### ISSUE TITLE
Docker-compose-plugin - 2.22* and 2.23* missing from RHEL repo "download.docker.com" 

### ISSUE THREAD

**Issue by selvasm** [docker/compose#11502]
Dears,

Currently docker-compose-plugin version 2.22.* and 2.23.* are missing from RHEL 7/8/9 repos.

Whereas other components docker-ce, docker-ce-cli all versions are available.

Is there any reason, why only for docker-compose-plugin these versions were removed.

>  docker-compose-plugin-2.23.3-1 was working without issues in our system, but had issues with docker-compose-plugin-2.24* so decided to role back, but to surprise 2.23.* version was missing in the repo itself.  

![image](https://github.com/docker/compose/assets/43107299/ccb8ff92-8106-4003-946c-4f3e42d25dfe)

**Comment by ndeloof** [comment]
This is managed by https://github.com/docker/docker-ce-packaging, I can't see any reason docker-compose-plugin would be exluced
