### ISSUE TITLE
[BUG] platform flag in compose.yaml file STILL ignored for M3 mac

### ISSUE THREAD

**Issue by scottwsides** [docker/compose#11532]
### Description

This error was supposed to have been fixed from reading other tickets... but its still not working for me. I've tried several versions of Docker Desktop, including the latest (4.27.2). This is an image that starts up fine with docker run --platform=linux/amd64. However a docker compose .yaml file (that worked on non-M3 mac) with 

services:
  - platform: linux/amd64
  - ......

does not work. I have built the image with docker build --platform=linux/amd64 ....  and this hasnt made a difference. This is a major issue for our applications that need to run/manage local images through Docker Desktop for M3 macs. I've also tried specifying DOCKER_DEFAULT_PLATFORM=linux/amd64 before the docker-compose command and no luck. Is this bug planning to be fixed... or is there a workaround for this that I havent found through naive google search?

### Steps To Reproduce

1. mac M3 machine
2. docker desktop 4.27.2
3. docker-compose -f ~/chemistream/lib/python3.10/site-packages/makalii-1.0.0-py3.10.egg/makalii/setup_files/docker-compose-slurmMaster.yaml up -d   (the yaml file is any file to start a docker image)
4. docker image specified in *.yaml is built with --platform=/linux/amd64

Output says image has started... but docker ps --all shows the container as having exiting

### Compose Version

```Text
phoenix2:chemistream-hpc-images swsides$ docker-compose version
Docker Compose version v2.24.5-desktop.1
phoenix2:chemistream-hpc-images swsides$ docker compose version
Docker Compose version v2.24.5-desktop.1
```

### Docker Environment

```Text
phoenix2:chemistream-hpc-images swsides$ docker info
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/swsides/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5-desktop.1
    Path:     /Users/swsides/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/swsides/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/swsides/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/swsides/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/swsides/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/swsides/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/swsides/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.4.1
    Path:     /Users/swsides/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/swsides/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/swsides/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.657GiB
 Name: docker-desktop
 ID: 5fc6af4e-114c-479e-914b-04ebd6e03956
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
I tried to reproduce (on a Mac M1) but don't get any issue
here is my reproduction scenario:

```
$ cat compose.yaml 
services:
  test:
    image: toto
    platform: linux/amd64
$ cat Dockerfile 
FROM alpine
CMD ping localhost
 $ docker build --platform linux/amd64 -t toto .
[+] Building 0.6s (5/5) FINISHED                                                                                  docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                              0.0s
 => => transferring dockerfile: 68B                                                                                               0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                  0.6s
 => [internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 2B                                                                                                   0.0s
 => CACHED [1/1] FROM docker.io/library/alpine:latest@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b     0.0s
 => exporting to image                                                                                                            0.0s
 => => exporting layers                                                                                                           0.0s
 => => writing image sha256:1b10476d2267bb79a5b4f924c163a6126d2691d2a1e844dd10a2995b6272e6c5                                      0.0s
 => => naming to docker.io/library/toto                                                                                           0.0s
$ docker inspect toto -f '{{.Architecture}}'
amd64
$ docker compose run test
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.126 ms
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.606 ms
```

**Comment by scottwsides** [comment]
Right... because the problem is on M3. I mentioned that in ticket

**Comment by scottwsides** [comment]
Yes... I dont understand how M3 could affect it either ;-)  I'll give your test a try... thanks

**Comment by scottwsides** [comment]
I cant really share the docker image build files. They are proprietary and complicated (multi-stage etc). However this is the docker compose file I'm using 

services: 
  spec: 
    shm_size: '5gb' 
    privileged: true 
    network_mode: host 
    image: registry.gitlab.com/txcorp/chemistream/chemistream-hpc-images/csimg-rlmolecule:latest
    volumes: 
      - /mnt/nfsshare/cluster_shared_dir:/home/hpcuser/cluster_shared_storage
    environment: 
      - ENV_SSHD_PORT=1022 
      - ENV_NOVNC_PORT=5901 
      - ENV_ORDER_NUMBER=txcorp-ctn 
      - ENV_CLUSTER_DISCOVERY=consul://10.0.1.202:8500 
      - ENV_USE_INTERFACE=eth0 
      - ENV_SCHEDULER=slurm 
      - ENV_SLURM_CONF_PATH=/etc/slurm/slurm.conf 
      - ENV_MUNGE_KEY_PATH=/etc/munge/munge.key

**Comment by scottwsides** [comment]
Your simple test does work on my M3. But as you can see from my compose yaml file above... I set tty true and some others that are different from your compose.yaml file (not sure if these are the issues). Also... here's the startup command

docker compose -f docker-compose-slurmMaster.yaml up -d 

so i'm detaching from the container as well.

**Comment by ndeloof** [comment]
Can you please run `docker inspect` on container created by compose, which has stopped ?
Please confirm platform is well set, and capture exit code / state

**Comment by scottwsides** [comment]
I just realized M3 is arm64... not amd64. However I'm still seeing the container exit immediately. So just to make sure

1. I'm running on mac M3 (arm64)
2. My image is built on linux centos7
3. I'm building the image with docker build --platform=linux/arm64 .....
4. I'm running with docker run --platform=linux/arm64

Generally this *should* be working right?

**Comment by ndeloof** [comment]
Yes this _should_ work, if requested platform is not supported `compose up` should not succeed to create container.
Can you please confirm you successfully can run this same image using a plain `docker run` command ? `inspect` output suggest container was well created, but exited with code 1 (did you checked `docker logs xxx` in case there's something reported there?)

**Comment by scottwsides** [comment]
The log only has the following info:

phoenix2:chemistream-hpc-images swsides$ docker logs e6b45848f5e9
2024/02/22 16:51:10 Cannot get container ID

As I mentioned, the docker run command is not working either. The command is

docker run \
--privileged \
--detach \
--platform=linux/arm64/v8 \
phoenix/rlmolecule

I believe linux/arm64/v8 is the right architecture... but I could be wrong. Querying the platform with python gives

import platform
platform.uname()
uname_result(system='Darwin', node='phoenix2.local', release='23.2.0', version='Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:51 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6030', machine='x86_64')

I thought linux/arm64/v8 was the correct architecture because some error messages were saying that was what docker was autodetecting, but I could be wrong

**Comment by scottwsides** [comment]
Yes... I believe this is a docker thing. Now if I add "-i" to the command... then I can detach and leave the container running. This has never been the case in the past. 

I'm still testing but what I suspect is this: only the later versions of Docker will run on M3 (i think >4.24.0). So on M3 I need new version of docker.... and this version has subtle differences in behavior with certain options.

**Comment by scottwsides** [comment]
Ok... after more testing I think these are the essential steps. The image MUST be built with --platform=linux/arm64/v8. Then all is needed is to add entrypoint: /bin/bash to the compose.yaml file. Then with simple docker-compose -f compose.yaml up -d  the same behavior is recovered. Again, I suspect that some kind of default entrypoint behavior in older versions of docker was changed in more recent versions.

**Comment by ndeloof** [comment]
can you reproduce running `docker run -it --entrypoint /bin/bash xxx`?
could you also please try to use a minimalist Dockefile (just `FROM alpine` for example) to confirm this is a runtime and not image design issue?
Please report to github.com/moby/moby with a reproduction example

**Comment by scottwsides** [comment]
Sorry, by my statement "... same behavior is recovered... " I mean the desired behavior of the image staying up. So... I believe I've fixed the problem. I dont know WHY the changes I describe above are needed... my only guess is that the behavior of certain options in docker changes subtly over time and this latest version of Docker that can install on M3 simply has sligthly different behavior.
