### ISSUE TITLE
The quick start guide results in weird code placement

### ISSUE THREAD

**Issue by crosbymichael** [docker/compose#1154]
**Problem**

On Quick Start section under Create a Docker image, the Dockerfile copies over the current directory into the image and the Docker-compose.yml file mounts the current directory inside of the container, both actions result in code being under /code directory. For beginners this example makes more complicated to understand how the data got there.

**Solution**

Break up the example into two parts, explicitly showing how to both actions end up having the /code files inside of the running container.

**Comment by jalev** [comment]
#dibs

**Comment by paulczar** [comment]
#dibs

**Comment by paulczar** [comment]
I'm not totally sure #1162 addresses the bug completely,  but it certainly makes the documentation easier to read.

Also there isn't a `make docs` for this repo, so apart from viewing it in a markdown viewer I haven't compiled it for a proper test.

**Comment by aanand** [comment]
@paulczar `script/docs` will build the docs.

**Comment by aanand** [comment]
I agree that it's confusing. I think there's a case to be made for leaving the `volumes` part out of the initial `docker-compose.yml` and adding a section afterwards along the lines of "Make your code reloadable", which explains how to mount it as a volume.

**Comment by shin-** [comment]
Re-opened on the docs repo as https://github.com/docker/docker.github.io/issues/4176
