### ISSUE TITLE
[BUG] auto create network is broken

### ISSUE THREAD

**Issue by BenjaminQuandt** [docker/compose#11553]
### Description

Hi, I updated my System(manjaro) recently and with it docker and docker compose. after the update my apps didn't work anymore. after a research i could point out the Problem to Docker Compose

I usually use compose files like that:

```
version: "3.7"

services:
  ix0:
    image: "*****"
    networks:
    - ix0

networks:
  ix0:
    external: true
```

if i run `docker compose up` it should create everything and start the container. Well since the update i get a error `Error response from daemon: network ix0 not found`

Before the update I didn't hat to create the network. Now i have to with the same compose file.

running `docker network create ix0` before `docker compose up` solves the problem. but changing it everywhere has a high impact and is annoying.
Well i can use a script to fix that, but the whole point for me to use docker compose is to avoid to have to write such scripts. I want to define that in de compose file.

### Steps To Reproduce

create a compose file that use and define a network.
clean your docker env from all networks
run docker compose up

### Compose Version

```Text
Docker Compose version 2.24.5
```

### Docker Environment

```Text
Client:
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629222
 Built:             Thu Feb  1 10:50:44 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0ca9b
  Built:            Thu Feb  1 10:50:44 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.13
  GitCommit:        7c3aca7a610df76212171d200ca3811ff6096eb8.m
 runc:
  Version:          1.1.12
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jhrotko** [comment]
Hello, @BenjaminQuandt 

according to the [documentation](https://docs.docker.com/compose/compose-file/06-networks/#external) an `external` network is never attempted to be created. This was possibly a bug that was fixed if the example you provided was working before.

**Comment by BenjaminQuandt** [comment]
Hi, @jhrotko 

I used that configuration for at least half a year. I used system prunes, and it was running in ci/cd. so I can say it worked.

Based on the documentation I found a way to get done what i want. Create a network what I can access from the host with the docker compose up. But idk if u like that.
if it is fine I am fine with it. If not I would like to get some suggestions.

```
networks:
  ix0:
    name: ix0
    internal: false
```

**Comment by ndeloof** [comment]
This indeed is the expected behavior, the question is: why did you set `external: true` in the first place?

For the proposed fix in your configuration, you don't need `internal: false` nor `name: ix0` as those are all default values in your configuration.

Just set :
```yaml
networks:
  ix0:  # empty line, or `null` or `{}` if you want to be more explicit as "intentionally left empty"
```

**Comment by BenjaminQuandt** [comment]
Hi, @ndeloof 

that worked fine. 
Tbh idk why i had the external in the 1st place. I'm using it like that for a while and never questined it, as it worked as I expected it. I think it was a copy paste from the compose file reference that i tried out.

Well, thank you for helping me to getting it done right.
