### ISSUE TITLE
[BUG] Internal DNS server randomly not working since v2.24.6

### ISSUE THREAD

**Issue by WhoAmI0501** [docker/compose#11563]
### Description

Hello,
with Docker v25.0.3 and Docker Compose v2.24.6 (Debian Bookworm, up2date), i am experiencing random issues with the internal DNS server of docker.

The problem shows up, as the applications in the containers try to resolve the DNS name of another container - they are trying to send a DNS request to 127.0.0.11:53 and are getting a connection refused. The behavior is absolutely random, so i am not able to provide a way to reproduce it.

The behavior showed up on 5 servers - so basically on all servers in my setup, that got the update to Docker Compose v2.24.6.

With Docker Compose v2.24.5, the behavior doesnt show up on all of the mentioned systems. Downgrade + down and up on all docker compose stacks helped for me.

### Compose Version

```Text
v2.24.6
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 14
  Running: 14
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-18-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 23.46GiB
 Name: docker-prod-2
 ID: 055df007-4d51-4aa4-835d-a806a8e73050
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by vitalek84** [comment]
I confirm the issue. I encountered with this issue on CentOS Stream release 8 with this configuration of packages: 

- containerd.io.x86_64                 1.6.28-3.1.el8                      @docker-ce-stable
- docker-buildx-plugin.x86_64          0.12.1-1.el8                        @docker-ce-stable
- docker-ce.x86_64                     3:25.0.3-1.el8                      @docker-ce-stable
- docker-ce-cli.x86_64                 1:25.0.3-1.el8                      @docker-ce-stable
- docker-ce-rootless-extras.x86_64     25.0.3-1.el8                        @docker-ce-stable
- docker-compose-plugin.x86_64         2.24.6-1.el8                        @docker-ce-stable

But only rollback docker-compose-plugin to 2.21.0-1.el8 version helped me.

**Comment by cayla** [comment]
It’s a long shot but I had some dns issues as well between these versions — though it presented differently for me — and what seemed to resolve it was purging the docker networks. 

Technically I just purged everything as a Hail Mary but in hindsight perhaps it was the networks being cleaned up that unjammed my dns resolution.

**Comment by kpmueller** [comment]
Seeing it here on Mac desktop 4.28.0 pretty frequently, once a day or more. Very annoying.

docker system prune does seem to clear it up but it sucks.

**Comment by alexleach** [comment]
I was having DNS issues running 2.24.6 on Arch Linux. My compose stack had separate networks connecting a frontend, backend and database. So, between these containers, there are 3 networks:

 - _`public-net`_ &rarr; `frontend` &rarr; _`backend-net`_ &rarr; `backend` &rarr; _`database-net`_ &rarr; `database`

The frontend was having issues resolving `backend`, even though it was connected to the correct network and I could connect to it by IP address.

I'm not sure if this is related to https://github.com/docker/compose/issues/11533, but the suggestion there is the same: to update compose.

As I'm on Arch Linux, I installed [`docker-compose-v2-git` from the AUR](https://aur.archlinux.org/packages/docker-compose-v2-git), rebooted and the frontend still resolve the backend container. After rebuilding my containers (`docker compose down && docker compose up -d`), my networking issues seem to have been solved now.

This was a very frustrating issue, I spent a good part of my Sunday thinking there was an issue with my `compose.yaml` file and tinkering with that (as I'd just bumped the base image versions).

**Comment by vitalek84** [comment]
> I was having DNS issues running compose 2.24.6 on Arch Linux. My compose stack had separate networks connecting a frontend, backend and database. So, between these containers, there are 3 networks:
> 
>     * _`public-net`_ → `frontend` → _`backend-net`_ → `backend` → _`database-net`_ → `database`
> 
> 
> The frontend was having issues resolving `backend`, even though it was connected to the correct network and I could connect to it by IP address.
> 
> I'm not sure if this is related to #11533, but the suggestion there is the same: to update compose.
> 
> As I'm on Arch Linux, I installed [`docker-compose-v2-git` from the AUR](https://aur.archlinux.org/packages/docker-compose-v2-git) and rebooted, but the frontend still couldn't resolve the backend container. After rebuilding my containers (`docker compose down && docker compose up -d`), my networking issues seem to have been solved now.
> 
> This was a very frustrating issue, I spent a good part of my Sunday thinking there was an issue with my `compose.yaml` file and tinkering with that (as I'd just bumped the base image versions).

Actually I also have more than one network. I have network for traefik-backend communication and internal network for backend <->redis communications. I will try to find time for gather more details.

**Comment by kpmueller** [comment]
I have gone back to 4.27.2 docker desktop for mac and haven't had this issue since

`https://desktop.docker.com/mac/main/arm64/137060/Docker.dmg` if anybody needs the download url

**Comment by mint-jar** [comment]
Same behavior here. I can see that 2.24.6 has trouble creating veth interfaces.

v2.24.6 up: 75 veht internfaces
v2.24.5 up: 89 veht internfaces

**Comment by Quiwy** [comment]
Same problem here after upgrading from 2.24.5 to 2.24.6 on debian.

Like other, we also have multiple networks. Had to downgrade to 2.24.5.

**Comment by milas** [comment]
Just released [v2.24.7](https://github.com/docker/compose/releases/tag/v2.24.7) which fixes multiple networks issues on the Compose side. Docker Engine v25.0.4 will also be released soon, which includes bugfixes in the dockerd daemon. See the [Moby v25.0.4](https://github.com/moby/moby/issues?q=is%3Aclosed+milestone%3A25.0.4) milestone for the full list.

I believe the new Compose version will resolve the problems being seen here, but I don't have a repro case to confirm this specific issue

**Comment by divStar** [comment]
So after updating, do I have to rebuild all the containers by stopping and removing my current docker-compose stacks?

**Comment by mint-jar** [comment]
> So after updating, do I have to rebuild all the containers by stopping and removing my current docker-compose stacks?

I don't know for sure. You can try using docker compose up to see if it changes things but for me it was easies to run down and up.

**Comment by divStar** [comment]
I rolled back to Docker 25 (latest 25) and my issue went away. So it wasn't docker-compose related I think.

**Comment by nicos68** [comment]
> It’s a long shot but I had some dns issues as well between these versions — though it presented differently for me — and what seemed to resolve it was purging the docker networks.
> 
> Technically I just purged everything as a Hail Mary but in hindsight perhaps it was the networks being cleaned up that unjammed my dns resolution.
> 
> EDIT: I should have said, I also use multiple networks like as mentioned by other folks below.

Thanks, I just spent my whole day wondering why I couldn’t do a `ping google.com` from my compose service on my machine. Deleting all the networks and restarting the service fixed it!

**Comment by snoopdouglas** [comment]
Leaving this here for anyone googling this: I'm on NixOS 25.05 and I get DNS failures specifically with Docker Compose if Avahi is disabled. Not entirely sure why, but re-enabling it fixed DNS for Compose services.

**Comment by dsoprea** [comment]
Similar issue in Manjaro using native Docker. Only restarting the service seems to remedy it.
https://serverfault.com/questions/1193536/docker-randomly-stops-being-able-to-resolve-hostnames
