### ISSUE TITLE
[BUG] Mix of mapping and list causes error, which is not caught

### ISSUE THREAD

**Issue by ArcticFall** [docker/compose#11567]
### Description

Using a list of mappings (dashes and colon) in docker compose causes an error, when using `docker compose config`, that is hard to read and therefore fix.

e.g. the following code mixes a list with mappings:  
```
environment:
  - MYSQL_DATABASE: nextcloud
  - MYSQL_INITDB_SKIP_TZINFO: 1
```

running `docker compose config` returns the following error message:  
```panic: interface conversion: interface {} is string, not map[string]interface {}```

It would be better, if this was caught and a meaningful error message would be displayed, the help users fix the error. e.g. a line number and more descriptive text.

see previous discussion in #11267

### Steps To Reproduce

Have this in a docker-compose file:
```
environment:
  - MYSQL_DATABASE: nextcloud
  - MYSQL_INITDB_SKIP_TZINFO: 1
```

Run: `docker compose config`
Get error: ```panic: interface conversion: interface {} is string, not map[string]interface {}```

### Compose Version

```Text
2.24.6
```

### Docker Environment

Client: Docker Engine - Community
Version:    25.0.3
Context:    default
Debug Mode: false
Plugins:
buildx: Docker Buildx (Docker Inc.)
  Version:  v0.12.1
  Path:     /usr/libexec/docker/cli-plugins/docker-buildx
compose: Docker Compose (Docker Inc.)
  Version:  v2.24.6
  Path:     /usr/libexec/docker/cli-plugins/docker-compose

**Comment by ndeloof** [comment]
> the following code mixes a list with mappings:

no, you example uses a list of nested mappings, while `environment` can be set either as list a string or a mapping:
```yaml
environment:
  - MYSQL_DATABASE=nextcloud
  - MYSQL_INITDB_SKIP_TZINFO=1
```
or
```
environment:
  MYSQL_DATABASE: nextcloud
  MYSQL_INITDB_SKIP_TZINFO: 1
```

still, the error isn't very helpful and compose should not panic, this we have to fix

**Comment by ndeloof** [comment]
Latest release avoids a panic an reports:
`failed to load project: services.toto.environment.[0]: unexpected type map[string]interface {}`
