### ISSUE TITLE
docker-compose:  No such file or directory

### ISSUE THREAD

**Issue by bergtwvd** [docker/compose#1156]
Following the intesructions on the docker site, In installed compose.
>>
curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
<<

Next,

docker@boot2docker:~$ uname -a
Linux boot2docker 3.18.5-tinycore64 #1 SMP Sun Feb 1 06:02:30 UTC 2015 x86_64 GNU/Linux

docker@boot2docker:~$ ls -l /usr/local/bin/docker-compose
-rwxr-xr-x    1 root     root       5257430 Mar 23 14:28 /usr/local/bin/docker-compose

docker@boot2docker:~$ /usr/local/bin/docker-compose --version
-sh: /usr/local/bin/docker-compose: not found

**Comment by chantra** [comment]
this is a dup of #1032

**Comment by attila123** [comment]
You need to add glibc, e.g.
```
    # Based on https://github.com/sgerrand/alpine-pkg-glibc/
    apk add ca-certificates wget
    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub
    GLIBC_VERSION='2.27-r0' && \
    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk && apk add glibc-${GLIBC_VERSION}.apk && \
    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk && apk add glibc-bin-${GLIBC_VERSION}.apk
```

**Comment by jansepke** [comment]
the key has changed you need to use
`wget -q -O /etc/apk/keys/sgerrand.rsa.pub  https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub`
see: https://github.com/sgerrand/alpine-pkg-glibc#please-note
