### ISSUE TITLE
[BUG] v2.24.7 multiple changes in `config` output

### ISSUE THREAD

**Issue by Re4zOon** [docker/compose#11589]
### Description

Hi,

Between Docker Compose version v2.24.6 and v2.24.7 some kind of change screwed up our stack build.
So far "extra_hosts" were a list separated by "=", not they are separated by ":" and labels changed from ":" to "=".
I guess its not intentional, as now our scripts (that loads the stack yaml to grab values for ansible) of course can't do that.

Also for some reason one of the services environment variables were switched to a list. I'm still trying to find the difference, why only that service gets parsed differently.

**Comment by Re4zOon** [comment]
I'll try to gather and share some simple outputs from both versions illustrating the issues (our stack yaml is about 6000 lines now).

**Comment by stasadev** [comment]
We see the same in DDEV (all our tests are failing)

- https://github.com/ddev/ddev/pull/5939

```yaml
extra_hosts:
    - host.docker.internal=host-gateway
```

became

```yaml
extra_hosts:
    - host.docker.internal:host-gateway
```

I tracked it down to:

- #11556

**Comment by rfay** [comment]
@Re4zOon could you please retitle this to something like "[BUG] v2.24.7 extra_hosts is output with colon instead of equals sign"

**Comment by Re4zOon** [comment]
Here you go:
[test.zip](https://github.com/docker/compose/files/14537065/test.zip)

What I found:
- a new default network is created, even tho nothing asked for it
- if you add an "override", the config becomes a list, instead of a dictionary
- labels are using equal sign instead of colon
- extra_hosts are using colon instead of equal sign

**Comment by luciangabor** [comment]
Well, today is a weekend day after all: https://github.com/dwmkerr/hacker-laws?tab=readme-ov-file#hyrums-law-the-law-of-implicit-interfaces

**Comment by Re4zOon** [comment]
> Well, today is a weekend day after all: https://github.com/dwmkerr/hacker-laws?tab=readme-ov-file#hyrums-law-the-law-of-implicit-interfaces

Yes, thats true. Just like: https://xkcd.com/1172/
However breaking compatibility still shouldn't result in a "patch" version according to [semver](https://semver.org/#spec-item-6).

**Comment by luciangabor** [comment]
Ok, but what compatibilit _is_ broken? If I pipe its output through itself (with varius 2.2*.* versions that I keep around) again everything seems allright: `docker compose config | docker compose -f - config -q` (using the docker-compose.yml from test.zip I get a deprecation warning, but that's all) ...

**Comment by ndeloof** [comment]
This change indeed took place to follow docker engine preferred format after https://github.com/compose-spec/compose-go/pull/499 

> services environment variables were switched to a list
this was required to allows resurrection of the `--no-interpolate` support.

in both case, this is not "breaking compatibility": `config` render a compose-spec compliant output, the fact you wrote your own parser without considering the many aspects of the spec is unfortunately an issue you have to manage on your own.

I'm closing this issue as "won't fix"

**Comment by Re4zOon** [comment]
I can understand the other point, but:
> environment variables were switched to a list

Its either a list, or a dictionary and its dependent on other things. 
Why do we have a spec, where it can be either with no clear setting as to which to use? 
`config` just decides it wants to use a list for only ONE service out of 70+, even tho the compose version did not change in our config (still on 3.5).

This means I get random behaviour and my parser will have to check if its a list, or a dictionary, as I can't anticipate which one it will be. Fun.

**Comment by luciangabor** [comment]
There's this:
> a new default network is created, even tho nothing asked for it

**Comment by luciangabor** [comment]
> even tho we still use version 3.5

maybe I'm wrong and this is not about swarm/stack, but if that's the case, why don't you just use `docker stack config` ..
(I keep seeing this and I don't get it - why pipe compose's config output, which is like an "ng" variant, to tools that expect the "classic" variant ... and expect it to keep working)

**Comment by Re4zOon** [comment]
oh. `docker stack config` didn't cross my mind...

**Comment by luciangabor** [comment]
(there's also `docker buildx bake` to build images without compose)

**Comment by ndeloof** [comment]
> Why do we have a spec, where it can be either with no clear setting as to which to use?

compose file format initially evolved organically, and offered flexibility to users. The spec defines the many ways things can be set, but there's no "single way", compared to kube.yaml which just reflect the internal API structs.

> config just decides it wants to use a list for only ONE service out of 70+, even tho the compose version did not change in our config (still on 3.5).

`version` attribute is obsolete and should be removed, it doesn't guarantee anything and is just a legacy from the time compose was implemented in python.

> This means I get random behaviour and my parser will have to check if its a list, or a dictionary, as I can't anticipate which one it will be. Fun.

Indeed, this is the price to pay with the flexibility we offer in the compose file format. You should not try to parse such a file with a shell script or naive parser expecting a fixed format. If you need to transform the config output, you should better rely on compose-go library and write your own transformation as actual code

**Comment by ndeloof** [comment]
indeed, we miss removal for unused resources - but that's a distinct issue then

**Comment by Re4zOon** [comment]
I've switched to `docker stack config`,  so from my side this issue can be closed.
We hope we can dismantle swarm in the "not-so-near" future anyways.

**Comment by luciangabor** [comment]
> indeed, we miss removal for unused resources - but that's a distinct issue then

and to take into account profiles: https://github.com/docker/compose/issues/11587

```console

$ docker compose -f - config <<-'EOF'
name: hidden
services:
  service:
    image: image
    profiles:
      - hidden
EOF
name: hidden
networks:
  default:
    name: hidden_default
services:
  service:
    image: image
    networks:
      default: null
    profiles:
      - hidden

# although --services works
$ docker compose -f - config --services <<-'EOF'
name: hidden
services:
  service:
    image: image
    profiles:
      - hidden
EOF

```

**Comment by luciangabor** [comment]
> I've switched to `docker stack config`, so from my side this issue can be closed. We hope we can dismantle swarm in the "not-so-near" future anyways.

https://github.com/search?q=repo%3Adocker%2Fcompose+mirantis&type=issues
https://lwn.net/Articles/905164/

**Comment by rfay** [comment]
Should have been noted here that the problem behavior here was reverted in v2.25.0.

DDEV's tests can now pass with v2.25.0

**Comment by luciangabor** [comment]
Well, but why rely on that?

The relevant part of the change was to restore a case where config did "more" - to inline the content of env files (when found) ... and this change is already subject to ... change: https://github.com/docker/compose/issues/11627

Who knows ... maybe config will convert all lists to maps where possible ... that's kinda' more aligned with doing "more" (plain lists are mostly for "short" forms and "long" forms, where they exist, are ... kinda' preferred and that's what I meant by doing "more" - to have config "show" you what you meant writing those files).

**Comment by ndeloof** [comment]
actually, the docker [engine API](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerCreate) uses `key=value` to set environment variables, so the mapping syntax for those only exists in compose for legacy reasons

**Comment by luciangabor** [comment]
maps also "just work":

```yaml

services:
  s1:
    image: image
    environment:
      - VAR=foo

  s2:
    extends: s1
    environment:
      - VAR=bar

```

But, being a weekend day after all, when it comes to [extra hosts](https://docs.docker.com/compose/compose-file/05-services/#extra_hosts) I find it funny that the long syntax is actually shorter that the short one :D

**Comment by arcanisgk** [comment]
How can I validate if this works or not?

```
extra_hosts:
      - "host.docker.internal:host-gateway"
```

**Comment by abirfo** [comment]
50 4b 03 04 0a 00 00 00 00 00 c9 5c 68 58 00 00  PK.........\hX..
00 00 00 00 00 00 00 00 00 00 05 00 1c 00 74 65  ..............te
73 74 2f 55 54 09 00 03 9a ea ea 65 c6 ea ea 65  st/UT......e...e
75 78 0b 00 01 04 e8 03 00 00 04 e8 03 00 00 50  ux.............P
4b 03 04 14 00 00 00 08 00 82 5c 68 58 e8 40 6e  K.........\hX.@n
43 e8 01 00 00 c9 04 00 00 17 00 1c 00 74 65 73  C............tes
74 2f 6f 75 74 70 75 74 2d 76 32 2e 32 34 2e 37  t/output-v2.24.7
2e 79 6d 6c 55 54 09 00 03 13 ea ea 65 64 ea ea  .ymlUT......ed..
65 75 78 0b 00 01 04 e8 03 00 00 04 e8 03 00 00  eux.............
ad 53 c1 72 9b 30 10 bd fb 2b f6 07 ec da 9e b4  .S.r.0...+......
31 cc 70 a0 13 25 f1 d4 d8 1e 20 cd 91 91 61 6d  1.p..%.... ...am
ab 11 12 23 09 b7 fe fb 0a b0 81 c4 4c 7b 68 c5  ...#........L{h.
45 bc 7d fb f4 56 da 15 34 47 17 0c 6a 33 12 68  E.}..V..4G..j3.h
7e 4a f5 a6 dd 11 40 86 7b 5a 72 53 6d 01 44 cb  ~J....@.{ZrSm.D.
49 2e b8 85 65 69 34 cb b0 61 e0 2f 83 4a 50 6e  I...ei4..a./.JPn
59 aa c4 5e d2 51 5a 61 8d ea c4 52 ac 85 f7 f4  Y..^.QZa...R....
0d c7 3a 37 45 93 98 61 c1 e5 b9 d9 03 14 9c a6  ..:7E..a........
98 a3 30 57 00 20 95 42 1b 45 99 30 ba 03 01 c6  ..0W. .B.E.0....
20 64 86 13 25 39 82 e7 41 e5 1b d5 25 ae ac 26   d..%9..A...%..&
4b a9 76 61 d6 22 5a 96 ea e2 a0 59 9c e5 ec bd  K.va."Z....Y....
64 8e b9 54 67 17 ee a6 ce 97 a0 c5 6d aa 75 4f  d..Tg.......m.uO
0d b3 3e 06 d9 77 8b 2b b9 2c 32 6a 30 b1 8e f7  ..>..w.+.,2j0...
ec d0 71 33 e4 d4 12 67 53 dd 42 05 55 94 73 e4  ..q3...gS.B.U.s.
4c e7 2e cc 9b 1b 14 27 a6 a4 e8 17 3f 86 47 ff  L......'....?.G.
1b 89 82 78 9b 3c 6e c2 57 3f 7c 20 81 bf 5c 45  ...x.<n.W?| ..\E
de 9e 72 8d b7 a4 ed 26 8c 3d 67 3a 5f b4 a1 c0  ..r....&.=g:_...
5f fb 4f 24 20 eb 38 89 48 f8 9d 84 2d c7 69 39  _.O$ .8.H...-.i9
1f 02 f7 5d 60 1b 2e d7 4f 49 75 64 f2 bc 89 62  ...]`...OIud...b
6f 36 bf 9f 4c ed 37 1b a4 6c fd 28 da bc 86 0f  o6..L.7..l.(....
9e 90 02 87 19 d5 11 f3 cf c3 b1 70 b3 25 61 bc  ...........p.%a.
24 51 f3 5f 17 e4 bf c4 cf 1f 8a fd 6b 4e 14 fb  $Q._........kN..
61 1c af a2 84 ac fd af 2b f2 87 f4 17 5b f9 da  a.......+....[..
0f 48 67 98 e5 f4 60 7b 76 47 35 8e eb bd fe d4  .Hg...`{vG5.....
b5 ab ad 7b 32 ad 69 9c ee 90 eb ee 95 cc b9 40  ...{2.i........@
ef 07 3d d1 16 29 a4 32 49 75 99 de d1 98 e2 06  ..=..).2Iu......
5e 78 26 bd 45 9d 8e dc 9f c4 6a 5d 67 0d 44 c9  ^x&.E.....j]g.D.
79 8d 55 49 3d 0b b9 ac a2 4c 1c 6c bb f6 da 4c  y.UI=....L.l...L
49 23 53 59 4d 65 7b 9e 45 cb 9d 6d bc 23 66 2e  I#SYMe{.E..m.#f.
f4 de 1b c0 50 75 40 f3 0e fc 17 e1 c5 90 f0 e2  ....Pu@.........
3f 08 3b 43 c2 ce e8 37 50 4b 03 04 0a 00 00 00  ?.;C...7PK......
00 00 d4 5b 68 58 92 a4 6d af 17 00 00 00 17 00  ...[hX..m.......
00 00 12 00 1c 00 74 65 73 74 2f 73 65 74 74 69  ......test/setti
6e 67 73 2e 63 6f 6e 66 55 54 09 00 03 cf e8 ea  ngs.confUT......
65 cf e8 ea 65 75 78 0b 00 01 04 e8 03 00 00 04  e...eux.........
e8 03 00 00 46 4f 52 57 41 52 44 5f 45 4d 41 49  ....FORWARD_EMAI
4c 53 3d 22 66 61 6c 73 65 22 0a 50 4b 03 04 14  LS="false".PK...
00 00 00 08 00 80 5c 68 58 fa 82 82 7f 1e 02 00  ......\hX.......
00 ba 05 00 00 17 00 1c 00 74 65 73 74 2f 64 6f  .........test/do
63 6b 65 72 2d 63 6f 6d 70 6f 73 65 2e 79 6d 6c  cker-compose.yml
55 54 09 00 03 10 ea ea 65 10 ea ea 65 75 78 0b  UT......e...eux.
00 01 04 e8 03 00 00 04 e8 03 00 00 b5 54 4d 8f  .............TM.
da 30 10 bd f3 2b 2c da 6b 28 8b b6 2d 89 c4 21  .0...+,.k(..-..!
2b bc 0b 2a 21 51 1c ca 31 32 c9 00 e9 3a 71 64  +..*!Q..12...:qd
1b 5a b4 ea 7f af f3 09 0b d9 6a a5 aa 39 c5 6f  .Z........j..9.o
de 9b 37 33 f2 58 82 38 26 11 48 ab 87 d0 96 3e  ..73.X.8&.H....>
83 21 53 95 17 07 84 92 94 ee c0 42 1b 2a c1 28  .!S........B.*.(
ff e5 a7 33 63 38 b8 1b 0c 4b 5a ce 85 92 95 02  ...3c8...KZ.....
21 03 a5 3c d6 a2 8f 2f de ea 61 31 27 b3 f9 f2  !..<.../..a1'...
29 74 dc 29 b6 8c 24 db 09 90 f2 77 cd d4 c2 c3  )t.)..$....w....
86 25 72 0f b1 85 cc e1 e8 6b 8b 2b 2a 76 a0 ae  .%r......k.+*v..
c0 5c 70 c5 23 ce 2c a4 a2 fc 9f cd c6 5d 66 e3  .\p.#.,......]f.
ff 64 66 76 99 99 7f 31 83 ec 98 08 9e a5 90 a9  .dfv...1........
66 ae 04 fb df b1 1f 7a ae 1f 54 83 41 1f d0 1a  f......z..T.A...
36 ab 79 1d 77 ec a5 fd 84 1d bc 0c c2 6b aa a9  6.y.w........k..
a9 3e 26 01 b2 bd 86 fd 68 7f c3 c4 09 bc 33 69  .>&.....h.....3i
ac 49 05 72 4d 78 74 fd b5 ed 4f b1 63 cf 17 a4  .I.rMxt...O.c...
68 be 06 c2 1a 31 94 38 40 d3 38 f1 fc 72 28 3a  h....1.8@.8..r(:
12 ce 5c 12 14 fc 1b cc 60 3c a2 6c cf a5 ea 92  ..\.....`<.l....
55 05 bd 96 95 98 31 fa dc c5 5f e9 6e 97 b6 83  U.....1..._.n...
af 35 2d 6e 64 3c eb 2c d0 b3 09 71 d7 fe f4 c6  .5-nd<.,...q....
ad c1 df 56 fa ae 87 fd 60 8e 49 75 2e 07 65 af  ...V....`.Iu..e.
82 d9 4d aa 37 89 c6 96 32 f9 fe e4 24 b0 fd 20  ..M.7...2...$.. 
58 90 10 2f ed 87 c5 4d b3 ef d2 5c 5a 32 ba 01  X../...M...\Z2..
76 b1 b3 7d 75 ca 61 f2 83 1e 69 ff 8c 15 7b 1d  v..}u.a...i...{.
16 57 6d b2 57 2a ef 08 8c 27 fa c2 76 e0 e6 85  .Wm.W*...'..v...
20 03 f5 93 8b 67 69 a1 96 c7 0f 4a 26 31 94 e7   ....gi....J&1..
18 72 c6 4f 4d 21 39 a3 11 5c de 7a 84 22 9e 49  .r.OM!9..\.z.".I
25 68 92 9d 9f 98 2a 4b a6 97 71 20 38 03 34 99  %h....*K..q 8.4.
a0 c2 02 44 1d 17 3a 67 12 51 6d 79 57 23 87 3c  ...D..:g.QmyW#.<
a6 0a 42 9d 6b 9b ec ce 69 72 2a 28 63 a0 37 35  ..B.k...ir*(c.75
b5 d0 a8 85 63 60 f4 a4 c5 43 d9 26 94 fc 20 ea  ....c`...C.&.. .
37 b2 fa 58 92 26 af 2b 4a 21 e5 42 cb ee 87 e6  7..X.&.+J!.B....
17 a7 c5 b5 54 bf af 54 25 ba 8d 4e f6 fd d8 e9  ....T..T%..N....
f5 da 21 69 46 3d 9d 8a 0c bf 14 88 8c b2 46 9a  ..!iF=........F.
d1 54 bf 40 fd 62 79 fa bd 3f 50 4b 03 04 0a 00  .T.@.by..?PK....
00 00 00 00 c0 5c 68 58 f1 ec 9c 8d 1e 00 00 00  .....\hX........
1e 00 00 00 08 00 1c 00 74 65 73 74 2f 65 6e 76  ........test/env
55 54 09 00 03 88 ea ea 65 c6 ea ea 65 75 78 0b  UT......e...eux.
00 01 04 e8 03 00 00 04 e8 03 00 00 65 78 70 6f  ............expo
72 74 20 46 4f 52 57 41 52 44 5f 45 4d 41 49 4c  rt FORWARD_EMAIL
53 3d 22 66 61 6c 73 65 22 0a 50 4b 03 04 14 00  S="false".PK....
00 00 08 00 c0 5c 68 58 62 63 72 b3 f0 01 00 00  .....\hXbcr.....
bb 04 00 00 17 00 1c 00 74 65 73 74 2f 6f 75 74  ........test/out
70 75 74 2d 76 32 2e 32 34 2e 36 2e 79 6d 6c 55  put-v2.24.6.ymlU
54 09 00 03 88 ea ea 65 9a ea ea 65 75 78 0b 00  T......e...eux..
01 04 e8 03 00 00 04 e8 03 00 00 a5 54 4d 73 da  ............TMs.
30 10 bd f3 2b 34 dc a1 e0 a1 80 3d 93 83 33 51  0...+4.....=..3Q
12 a6 7c 78 6c a7 39 7a 84 bd 80 1a 59 f2 48 32  ..|xl.9z....Y.H2
2d ff be 6b 13 8c 43 a1 cd 4c ed 8b 76 df db b7  -..k..C..L..v...
bb d2 4a 92 e5 e0 11 0b c6 76 0c e8 3d 4f c1 78  ..J......v..=O.x
1d 42 36 ec 0d 7a 26 b7 45 65 10 92 41 21 d4 e1  .B6..z&.Ee..A!..
b8 26 44 a3 c5 53 66 3c 32 7c f7 94 45 c6 2c 24  .&D..Sf<2|..E.,$
a9 92 1b be 3d d1 08 29 98 66 42 80 e0 26 f7 88  ....=..).fB..&..
d3 b8 33 10 ec 80 c1 03 d3 08 1a 55 ea f7 d4 c7  ..3........U....
4f f0 9c db 96 4d 48 0e b9 d2 18 d6 1d 39 ee c8  O....MH......9..
1d 4f 1c 77 dc 6d 60 54 c0 ea 99 e5 4a de 08 1a  .O.w.m`T....J...
bb 93 b1 33 18 4d 4f 31 85 60 29 e4 20 ed 99 8e  ...3.MO1.`). ...
e5 1b ab 19 97 1f 13 f7 88 54 19 f4 b5 12 40 ee  .........T....@.
ee c8 4f a5 df 40 d7 38 c8 3d d7 4a b6 55 1e fd  ..O..@.8.=.J.U..
6f 34 5a c4 41 f2 b8 0a 5f fd f0 81 2e fc d9 3c  o4Z.A..._......<
c2 02 36 4c 18 e8 5e b2 82 55 18 23 e8 0e 9c a6  ..6L..^..U.#....
b0 85 bf f4 9f e8 82 2e e3 24 a2 e1 77 1a b6 48  .........$..w..H
ee 89 f4 07 32 69 90 20 9c 2d 9f 92 2a 6d f2 bc  ....2i. .-..*m..
8a 10 1e 3a 93 fe 00 ff e1 15 46 e0 47 d1 ea 35  ...:......F.G..5
7c f0 b0 47 09 d7 08 c7 0c ce d7 6b fa 41 b8 0a  |..G.......k.A..
68 18 cf 68 74 b4 eb 96 fc 97 f8 f9 b2 df 7f 06  h..ht...........
45 b1 1f c6 f1 3c 4a e8 d2 bf 9f d3 bf c5 bf 60  E....<J........`
ef 4b 7f 41 5b 25 f3 9c 6d 71 8a d7 cc 40 af 5e  .K.A[%..mq...@.^
9b 2f e7 01 c6 c6 fb 83 9a 26 d8 1a 44 73 b4 85  ./.......&..Ds..
d2 36 a9 76 ce 23 3b 6b 8b 0b ef 14 2f 45 7a e9  .6.v.#;k..../Ez.
74 3f 50 ed a1 c0 a4 3f d8 9e d5 0e 09 b6 1a 8d  t?P....?........
46 5f 95 d6 f0 0c 19 b2 14 a2 73 92 69 e0 1e c9  F_........s.i...
55 85 72 b9 c5 e1 35 cd bc 59 a6 b7 60 3d 52 55  U.r...5..Y..`=RU
76 be 48 e5 1a 2f d1 0e b2 8b c3 46 44 2b ab 52  v.H../.....FD+.R
25 da e5 7e 42 7a 7a 4b 7a fa df d2 ee 2d 69 f7  %..~BzzKz....-i.
96 74 7b e7 4e bb 76 dc d2 fa 71 da 29 7c 9c 2a  .t{.N.v...q.)|.*
13 7e 59 d0 92 55 51 ba 84 ce 6f 50 4b 03 04 14  .~Y..UQ...oPK...
00 00 00 08 00 ea 5b 68 58 83 86 53 fe 48 00 00  ......[hX..S.H..
00 4e 00 00 00 12 00 1c 00 74 65 73 74 2f 6f 76  .N.......test/ov
65 72 72 69 64 65 2e 79 61 6d 6c 55 54 09 00 03  erride.yamlUT...
f8 e8 ea 65 f8 e8 ea 65 75 78 0b 00 01 04 e8 03  ...e...eux......
00 00 04 e8 03 00 00 d3 d5 d5 e5 2a 4e 2d 2a cb  ...........*N-*.
4c 4e 2d b6 e2 52 50 48 4b cc 4e d5 2d ce 2d 29  LN-..RPHK.N.-.-)
00 71 14 14 52 f3 ca 32 8b f2 f3 72 53 f3 4a 20  .q..R..2...rS.J 
02 0a 0a c1 01 41 9e 7e ee f1 be 8e 9e 3e f1 1e  .....A.~.....>..
fe c1 21 56 0a 86 46 e6 7a 06 40 68 c8 05 00 50  ..!V..F.z.@h...P
4b 03 04 14 00 00 00 08 00 5d 5c 68 58 12 4f b2  K........]\hX.O.
89 77 00 00 00 97 00 00 00 0c 00 1c 00 74 65 73  .w...........tes
74 2f 74 65 73 74 2e 73 68 55 54 09 00 03 d1 e9  t/test.shUT.....
ea 65 d1 e9 ea 65 75 78 0b 00 01 04 e8 03 00 00  .e...eux........
04 e8 03 00 00 2d cd 31 0e c3 20 0c 85 e1 3d a7  .....-.1.. ...=.
70 95 21 13 f8 06 3d 4a a4 04 1c 8a da 60 64 03  p.!...=J.....`d.
6a a4 1e be a0 76 fc 3f 59 cf f3 0d f7 98 70 df  j....v.?Y.....p.
f4 31 05 a1 0c a6 c1 3a 83 52 29 31 05 b5 8e d3  .1.....:.R)1....
01 9f de 1e 16 c5 15 e9 9d 59 0a e0 02 77 a0 d4  .........Y...w..
26 e5 2a 8e c0 e2 08 cf ee 49 02 8e cf cc 4a 60  &.*......I....J`
0e f8 89 f9 8b bd ce d7 50 6e 24 12 7d ef ad c3  ........Pn$.}...
78 11 43 df e3 5a 72 2d e3 68 fa 02 50 4b 01 02  x.C..Zr-.h..PK..
1e 03 0a 00 00 00 00 00 c9 5c 68 58 00 00 00 00  .........\hX....
00 00 00 00 00 00 00 00 05 00 18 00 00 00 00 00  ................
00 00 10 00 ed 41 00 00 00 00 74 65 73 74 2f 55  .....A....test/U
54 05 00 03 9a ea ea 65 75 78 0b 00 01 04 e8 03  T......eux......
00 00 04 e8 03 00 00 50 4b 01 02 1e 03 14 00 00  .......PK.......
00 08 00 82 5c 68 58 e8 40 6e 43 e8 01 00 00 c9  ....\hX.@nC.....
04 00 00 17 00 18 00 00 00 00 00 01 00 00 00 a4  ................
81 3f 00 00 00 74 65 73 74 2f 6f 75 74 70 75 74  .?...test/output
2d 76 32 2e 32 34 2e 37 2e 79 6d 6c 55 54 05 00  -v2.24.7.ymlUT..
03 13 ea ea 65 75 78 0b 00 01 04 e8 03 00 00 04  ....eux.........
e8 03 00 00 50 4b 01 02 1e 03 0a 00 00 00 00 00  ....PK..........
d4 5b 68 58 92 a4 6d af 17 00 00 00 17 00 00 00  .[hX..m.........
12 00 18 00 00 00 00 00 01 00 00 00 a4 81 78 02  ..............x.
00 00 74 65 73 74 2f 73 65 74 74 69 6e 67 73 2e  ..test/settings.
63 6f 6e 66 55 54 05 00 03 cf e8 ea 65 75 78 0b  confUT......eux.
00 01 04 e8 03 00 00 04 e8 03 00 00 50 4b 01 02  ............PK..
1e 03 14 00 00 00 08 00 80 5c 68 58 fa 82 82 7f  .........\hX....
1e 02 00 00 ba 05 00 00 17 00 18 00 00 00 00 00  ................
01 00 00 00 a4 81 db 02 00 00 74 65 73 74 2f 64  ..........test/d
6f 63 6b 65 72 2d 63 6f 6d 70 6f 73 65 2e 79 6d  ocker-compose.ym
6c 55 54 05 00 03 10 ea ea 65 75 78 0b 00 01 04  lUT......eux....
e8 03 00 00 04 e8 03 00 00 50 4b 01 02 1e 03 0a  .........PK.....
00 00 00 00 00 c0 5c 68 58 f1 ec 9c 8d 1e 00 00  ......\hX.......
00 1e 00 00 00 08 00 18 00 00 00 00 00 01 00 00  ................
00 a4 81 4a 05 00 00 74 65 73 74 2f 65 6e 76 55  ...J...test/envU
54 05 00 03 88 ea ea 65 75 78 0b 00 01 04 e8 03  T......eux......
00 00 04 e8 03 00 00 50 4b 01 02 1e 03 14 00 00  .......PK.......
00 08 00 c0 5c 68 58 62 63 72 b3 f0 01 00 00 bb  ....\hXbcr......
04 00 00 17 00 18 00 00 00 00 00 01 00 00 00 a4  ................
81 aa 05 00 00 74 65 73 74 2f 6f 75 74 70 75 74  .....test/output
2d 76 32 2e 32 34 2e 36 2e 79 6d 6c 55 54 05 00  -v2.24.6.ymlUT..
03 88 ea ea 65 75 78 0b 00 01 04 e8 03 00 00 04  ....eux.........
e8 03 00 00 50 4b 01 02 1e 03 14 00 00 00 08 00  ....PK..........
ea 5b 68 58 83 86 53 fe 48 00 00 00 4e 00 00 00  .[hX..S.H...N...
12 00 18 00 00 00 00 00 01 00 00 00 a4 81 eb 07  ................
00 00 74 65 73 74 2f 6f 76 65 72 72 69 64 65 2e  ..test/override.
79 61 6d 6c 55 54 05 00 03 f8 e8 ea 65 75 78 0b  yamlUT......eux.
00 01 04 e8 03 00 00 04 e8 03 00 00 50 4b 01 02  ............PK..
1e 03 14 00 00 00 08 00 5d 5c 68 58 12 4f b2 89  ........]\hX.O..
77 00 00 00 97 00 00 00 0c 00 18 00 00 00 00 00  w...............
01 00 00 00 e4 81 7f 08 00 00 74 65 73 74 2f 74  ..........test/t
65 73 74 2e 73 68 55 54 05 00 03 d1 e9 ea 65 75  est.shUT......eu
78 0b 00 01 04 e8 03 00 00 04 e8 03 00 00 50 4b  x.............PK
05 06 00 00 00 00 08 00 08 00 b2 02 00 00 3c 09  ..............<.
00 00 00 00                                      ....
