### ISSUE TITLE
[BUG] Unable to use library/* as build context and override it from compose files

### ISSUE THREAD

**Issue by luciangabor** [docker/compose#11594]
### Description

`FROM library/golang` (for example) always resolves to `docker.io/library/golang:latest` even if I set `library/golang` to something like `docker-library://library/golang:1.22`. The same applies to `--from=library/golang`

### Steps To Reproduce

1. With this `Dockerfile`

```dockerfile

FROM scratch
COPY --from=library/golang /usr/local/go /go/library
COPY --from=bitnami/golang /opt/bitnami/go /go/bintami

```

2. and this `compose.yaml`

```yaml

services:
  service:
    build:
      additional_contexts:
        library/golang: docker-image://library/golang:1.22
        bitnami/golang: docker-image://bitnami/golang:1.22


```

3. observe the output of the `build` command

```console

$ docker compose --progress plain build
#0 building with "default" instance using docker driver

#1 [service internal] load build definition from Dockerfile
#1 transferring dockerfile: 158B done
#1 DONE 0.0s

#2 [service internal] load metadata for docker.io/library/golang:latest
#2 DONE 0.6s

#3 [service context bitnami/golang] load metadata for bitnami/golang:1.22
#3 DONE 2.0s

#4 [service internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [service] FROM docker.io/library/golang:latest@sha256:34ce21a9696a017249614876638ea37ceca13cdd88f582caad06f87a8aa45bf3
#5 DONE 0.0s

#6 [service context bitnami/golang] bitnami/golang:1.22
#6 resolve docker.io/bitnami/golang:1.22
#6 resolve docker.io/bitnami/golang:1.22 0.3s done
#6 DONE 0.3s

#7 [service stage-0 1/2] COPY --from=library/golang /usr/local/go /go/library
#7 CACHED

#8 [service stage-0 2/2] COPY --from=bitnami/golang /opt/bitnami/go /go/bintami
#8 CACHED

#9 [service] exporting to image
#9 exporting layers done
#9 writing image sha256:4685273064135e08c118fd24a970567bd8d56e7b9abb6006ea33b7bd93bf9bfc done
#9 naming to docker.io/library/library-service 0.0s done
#9 DONE 0.0s

```

- despite the quasi identical bitnami/library references `library/golang` is not overrriden

### Compose Version

```Text
Docker Compose version v2.24.7
```

### Anything else?

Not sure if this is about compose since the same issue exists with buildx: https://github.com/docker/buildx/issues/2328

**Comment by ndeloof** [comment]
Same issue can be reproduced with `docker buildx bake -f compose.yaml --progress plain`
BUT it works as expected when using `docker buildx build --build-context library/golang=docker-image://library/golang:1.22 --build-context bitnami/golang=docker-image://bitnami/golang:1.22 --progress plain . `

**Comment by luciangabor** [comment]
(the buildx (bake) issue is already linked)

**Comment by ndeloof** [comment]
I guess this will be fixed by updating buildx dependency once https://github.com/docker/buildx/issues/2328 is fixed. So I'm closing this issue as not-specific to compose
