### ISSUE TITLE
[BUG] error with "docker-compose -v"

### ISSUE THREAD

**Issue by Lingbo-Huang** [docker/compose#11596]
### Description

![image](https://github.com/docker/compose/assets/59855449/53a6b2e8-0be5-469d-8bc9-ae001d211d93)
When I run "docker-compose-v", it represents:
/usr/local/bin/docker-compose: line 1: html: No such file or directory
/usr/local/bin/docker-compose: line 2: syntax error near unexpected token `<'
/usr/local/bin/docker-compose: line 2: `<head><title>503 Service Temporarily Unavailabl

### Steps To Reproduce

In centos 7, docker v25.0.4, docker-compose v2.24.7
curl -L https://get.daocloud.io/docker/compose/releases/download/2.24.7/docker-compose-'uname -s'-'uname -m' > /usr/local/bin/docker-compose
It is correct! And I run "docker-compose-v", it represents:
/usr/local/bin/docker-compose: line 1: html: No such file or directory
/usr/local/bin/docker-compose: line 2: syntax error near unexpected token `<'
/usr/local/bin/docker-compose: line 2: `<head><title>503 Service Temporarily Unavailabl

### Compose Version

```Text
2.24.7
```

### Docker Environment

```Text
25.0.4
```

**Comment by luciangabor** [comment]
Please note that there's a very very big difference between ' and ` when it comes to shells, so the content of the file you've created is not at all what you expect it to be, but, leaving that aside, docker's own documentation page for installing docker-compose is this one: https://docs.docker.com/compose/install/standalone/ (and it mentions nothing about daocloud.io)

Nevertheless, if you're just interested in alternate ways to install it, here's one I like: `docker buildx build --output . - <<< "FROM docker/compose-bin:v2.24.7"` (. can be replaced with any directory you have write access to)

**Comment by ndeloof** [comment]
`docker-compose` you installed is not a binary, but HTML error page. You should run curl with (--fail)[https://curl.se/docs/manpage.html#-f] flag to ensure URL actually resolved to a valid content

**Comment by Lingbo-Huang** [comment]
> `docker-compose` you installed is not a binary, but HTML error page. You should run curl with (--fail)[https://curl.se/docs/manpage.html#-f] flag to ensure URL actually resolved to a valid content

Thank you! I was new to golang and I love it.I'm glad to be replied, thank you
