### ISSUE TITLE
fig up should recreate multiple containers

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#116]
If a service has multiple containers and `fig up -d` is run, it stops everything and starts one container for each service. This is not very helpful.

It should probably stop, recreate and start each container individually so you can do a rolling restart.

The behaviour of `fig up` when there are multiple containers running in the background needs a bit of thought. The whole daemon/up workflow needs thinking out properly. Maybe there should be a `fig recreate` command which handles the recreation of daemonised containers and `fig up` should just attach or something.

**Comment by macobo** [comment]
Pretty sad to see that there's been no progress on this even though there's been active community interest and PRs.

**Comment by dnephin** [comment]
I think this was actually implemented a while ago. Could you describe the behaviour you're expecting?

**Comment by bfirsh** [comment]
```
$ docker-compose up -d
$ docker-compose scale web=3
$ docker-compose up -d
```

There should be 3 web containers, but there is now 1.

**Comment by dnephin** [comment]
@bfirsh can you actually reproduce that? I just tried it and I ended up with 3 containers after that set of commands.

**Comment by bfirsh** [comment]
Oh, sorry. I mean, make a change to the Compose file too:

$ docker-compose up -d
$ docker-compose scale web=3
$ # change docker-compose.yml!
$ docker-compose up -d

**Comment by bfirsh** [comment]
This probably isn't a big deal and is low priority, I guess.

**Comment by dnephin** [comment]
Yes, that's what I did! Otherwise it wouldn't have said "Recreating", it would have said "up-to-date".

@bfirsh I'm confident this is fixed. If you can provide a case where it doesn't work, feel free to re-open.

**Comment by bfirsh** [comment]
Oh. Hm. Sorry.
