### ISSUE TITLE
[BUG] Compose removes other containers with same image

### ISSUE THREAD

**Issue by lbeuke** [docker/compose#11602]
### Description

I came up on an error of the compose plugin i think.

When ever i´m starting an container wiht an base image, that is already in use by another container this conainer gets deleted and replaced with the new coantienr, despite having completly diffrent names and properties. This Behaviour is noticeable not only when the conainers come from the same compose project, but also when they are from diffent projects with diffrent names.

### Steps To Reproduce

1. run docker compose up -d on provided docker compose
2. find that only one container gets deployed

### Compose Version

```Text
Docker Compose version v2.24.5
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  compose: Docker Compose (Docker Inc., v2.24.5)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
```

### Anything else?

compose:

version: "3"

services:
  watchtower-dev:
    image: containrrr/watchtower
    command: --interval 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=dev"
      - "traefik.enable=false"

  watchtower-prod:
    image: containrrr/watchtower
    command: --schedule "0 0 4 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=prod"
      - "traefik.enable=false"

**Comment by luciangabor** [comment]
That `containrrr/watchtower` is quite an interesting tool, except it seems to be in its job description to restart other containers
