### ISSUE TITLE
[FEATURE] jinja templating support

### ISSUE THREAD

**Issue by typoworx-de** [docker/compose#11618]
### Description

It would be awesome to have jinja templating support for docker-compose.yaml which would make many things much more flexible. I know there are some python based wrappers but, I think such stuff should be supported by compose itself (at least optionally).

Is there any kind of drop-in addon support being able to make kind of plugin to provide this?

**Comment by ndeloof** [comment]
We don't plan to offer any kind of advanced templating in compose. Whenever this bring more flexibility, this also would bring mass complexity in compose: if you give developers a development language, you know what happens! (I contributed to Jenkins pipeline design, and consider relying on groovy language was a terrible mistake there)

Also jinja being a python thing would hardly be used by compose v2 implemented in Go. Up to you to create you own wrapper to dynamically produce compose.yaml using your favorite template language.

**Comment by ndeloof** [comment]
Closing this issue as "not planed"
