### ISSUE TITLE
[BUG] compose referenced multiple times in `include` causing conflicts

### ISSUE THREAD

**Issue by aboqasem** [docker/compose#11612]
### Description

The projects makes use of [`include`](https://docs.docker.com/compose/compose-file/14-include/) and [merging](https://docs.docker.com/compose/compose-file/13-merge/#unique-resources).

This is a simplified minimal reproducible example:

```yml
.
├── compose.yml # main compose that `include`s other components
├── compose.local.yml # local compose that would override main's `include` to point to components and their local
├── included.compose.yml # a component that's included in the main compose
├── included.compose.local.yml # a local version of the component that's included in the local compose
├── multi-included.compose.yml # this component is included by other component and by main
└── multi-included.compose.local.yml # same concept
```

This was working in `Docker Compose version v2.24.5`.

```sh
curl -SL https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-darwin-x86_64 -o ~/.docker/cli-plugins/docker-compose && chmod +x ~/.docker/cli-plugins/docker-compose
```

### Steps To Reproduce

Run: `docker compose -f compose.yml -f compose.local.yml config`

Expected error:
```
services.multi-included conflicts with imported resource
```

With the following files:

File: `compose.yml`
```yml
version: '3.9'

include:
  - ./included.compose.yml
  - ./multi-included.compose.yml

services: { }
```

File: `compose.local.yml`
```yml
version: '3.9'

include: !override
  - path:
      - ./included.compose.yml
      - ./included.compose.local.yml
  - path:
      - ./multi-included.compose.yml
      - ./multi-included.compose.local.yml

services: { }
```

File: `included.compose.yml`
```yml
version: '3.9'

include:
  - ./multi-included.compose.yml

services:
  included:
    image: alpine
```

File: `included.compose.local.yml`
```yml
version: '3.9'

include: !override
  - path:
      - ./multi-included.compose.yml
      - ./multi-included.compose.local.yml

services: { }
```

File: `multi-included.compose.yml`
```yml
version: '3.9'

services:
  multi-included:
    image: alpine
    environment: # removing `environment` makes it work
      FOO: bar
```

File: `multi-included.compose.local.yml`
```yml
version: '3.9'

services: { }
```

### Compose Version

```Text
Docker Compose version v2.24.6-desktop.1
```

### Docker Environment

```Text
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/user/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     /Users/user/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/user/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/user/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     /Users/user/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/user/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     /Users/user/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/user/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     /Users/user/.docker/cli-plugins/docker-scout

Server:
 Containers: 32
  Running: 0
  Paused: 0
  Stopped: 32
 Images: 51
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 4.803GiB
 Name: docker-desktop
 ID: 35097c99-adf9-415d-89ff-7f45df5dfc01
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Might be related to #11544.

**Comment by ndeloof** [comment]
use of `include: !override` is unspecified behavior in the spec. Here you expect original includes get ignored and replaced by others, but actually `include` is processed _before_ compose yaml files get merged, so this won't work anymore

**Comment by aboqasem** [comment]
while trying different versions, I got another error on latest:

```
──> curl -SL https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-darwin-x86_64 -o ~/.docker/cli-plugins/docker-compose && chmod +x ~/.docker/cli-plugins/docker-compose
──> docker compose -f app/compose.yml -f app/compose.local.yml config
services.keycloak conflicts with imported resource

─[15]─> curl -SL https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-darwin-x86_64 -o ~/.docker/cli-plugins/docker-compose && chmod +x ~/.docker/cli-plugins/docker-compose
──> docker compose -f app/compose.yml -f app/compose.local.yml app/.env.local config
open ../keycloak/compose.yml: no such file or directory
─[1]─>
```

**Comment by aboqasem** [comment]
> use of `include: !override` is unspecified behavior in the spec. Here you expect original includes get ignored and replaced by others, but actually `include` is processed _before_ compose yaml files get merged, so this won't work anymore


Does this mean [merge - replace value](https://docs.docker.com/compose/compose-file/13-merge/#replace-value) does not apply to `include`?

**Comment by ndeloof** [comment]
> Does this mean [merge - replace value](https://docs.docker.com/compose/compose-file/13-merge/#replace-value) does not apply to include?

indeed. Merge applies _after_ individual compose file has been processed

**Comment by aboqasem** [comment]
> indeed. Merge applies _after_ individual compose file has been processed

Ok thanks. May I know why it's working as expected when I'm simply not importing the same file twice?

Can I assume that `include: !override` would work on that case?

Would have to figure out another way to structure the project.

Would it be good to document this more in-depth?

**Comment by aboqasem** [comment]
By "working as expected", I mean if I want a postgres DB that in main would save to a host file, but in local, would want it to override that to store the data in a virtual volume.

It's correctly doing that.

**Comment by ndeloof** [comment]
define the canonical application model as `compose.yaml` and have a `compose.override.yaml` for local development to tweak your `db` service

**Comment by aboqasem** [comment]
> define the canonical application model as `compose.yaml` and have a `compose.override.yaml` for local development to tweak your `db` service

That defeats one of the purposes of having such structure. Which is that each component is self contained, because in our case, we would have multiple main apps (`compose.yml`s) in different repos that would use these components.

I'm not trying to say anything but that 1. I want to understand more and 2. This may be needs to be documented.

I would probably have to change this structure if `include` is processed before merging.

Also, feel free to close this if there's nothing that needs to be done.

**Comment by ndeloof** [comment]
> That defeats one of the purposes of having such structure. Which is that each component is self contained

if you want a plugable-component experience, then such component need to be flexible to configure, basically using env variables and interpolation. For example you can have:
```yaml
services:
  db:
    volumes:
       - ${DB_VOLUME:-/var/lib/db_data}:/data
```
so that a host path is used by default, but your local project (using `.env` file) can declare `DB_VOLUME=~/.data`

Parsing logic is documented here: https://github.com/compose-spec/compose-go/blob/main/parsing.md

**Comment by aboqasem** [comment]
> if you want a plugable-component experience, then such component need to be flexible to configure, basically using env variables and interpolation.

Thanks. Some things that would be configured in the local compose are not configurable by using env variables.

---

> Hmm, given the ... given example - just running `docker compose -f compose.local.yml config` should ... simply do the expected (without the need to !override anything) - in the example compose.local.yml is anyway a "superset" of compose.yml

Yup you are correct. But:
- This is a minimal example, you might have something in the main compose
- You can see why `include: !override` is needed in the structure that was planned

---

I would probably go with:
- Having profiles for every service in every component
- Remove all `<component>.compose.local.yml` and move their content to the root `compose.local.yml` (first suggestion by @ndeloof)
- All other projects would have a similar `project.compose.yml` (that includes the root `compose.yml`) `project.compose.local.yml` (that includes root `compose.yml`), and cherry-pick components by using `COMPOSE_PROFILES`

**Comment by luciangabor** [comment]
On my side I concluded that it's quite pointless to keep something in the including yaml - it's only subject to merge restrictions.

**Comment by ndeloof** [comment]
closing this issue as "answered"
