### ISSUE TITLE
[BUG] container_name validation ignores profile (regression)

### ISSUE THREAD

**Issue by wrimle** [docker/compose#11616]
### Description

In the release notes of docker compose 2.24.7 it says that it fixed "Fixed validation for non-unique container_name values". Sometimes it is useful to have identical container_names in the same docker-compose.yml, however, to enable different configurations of the container in different profiles. Because of this the container_name validation should only fail if there are non-unique container_name's inside the profile that is actually started

### Steps To Reproduce

1. Create a docker-compose with two containers that has the same container_name but different profiles.
2. Do docker compose up with one of the profiles
3. The command fails with an error message

### Compose Version

```Text
2.24.7
```

**Comment by ndeloof** [comment]
duplicates https://github.com/docker/compose/issues/11619
