### ISSUE TITLE
[BUG] `'version' is obsolete`

### ISSUE THREAD

**Issue by frepke** [docker/compose#11628]
### Description

After updating to version v2.25.0, the command `docker compose pull docker-compose.yaml` gives the error `'version' is obsolete`

### Compose Version

```Text
v2.25.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /root/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.25.0
    Path:     /root/.docker/cli-plugins/docker-compose

Server:
 Containers: 27
  Running: 27
  Paused: 0
  Stopped: 0
 Images: 24
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dd1e886e55dd695541fdcd67420c2888645a495
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.13-1-pve
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 6.723GiB
 Name: hpt630
 ID: beea869f-20a2-4a3f-a514-6ff0f77b5433
 Docker Root Dir: /srv/dev-disk-by-uuid-c1677ca2-07a1-4495-b5c3-ec3f921e2e60/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by Xeckt** [comment]
This isn't a bug, `version` is only informative since a long time ago now. You can use loose options, check the spec:

https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements

**Comment by frepke** [comment]
> As I recall, this isn't a bug, `version` is only informative since a long time ago now. You can use loose options and you don't need it, check the spec:
> 
> https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements

Thanks, didn't know that

**Comment by frepke** [comment]
@Xeckt gave the answer

**Comment by HenriWahl** [comment]
How will docker-compose.yml files for versions 2.x and 3.x be distinguished without the `version` tag?

**Comment by bkraul** [comment]
> How will docker-compose.yml files for versions 2.x and 3.x be distinguished without the `version` tag?

I have the same question. How is this going to work...there are definitely differences between 2.x and 3.x that are not compatible with one another?

**Comment by luciangabor** [comment]
The version had (and in one case still has) a very ... limited relevance. It's purpose was to ... limit what you were allowed to write in those yaml files. The only case where that's still "relevant" is for docker stack.

The current file format is more of a "descendant" of the 2.x series and the 3.x series is, again, only relevant for docker stack, where 2.x had no ... relevance.

I'm glad it's gone. It was tiring to see "3" as version

**Comment by rseymour** [comment]
Could the docs be updated?

**Comment by wojiushixiaobai** [comment]
只是警告，可以忽略。如果你不需要这个提示，可以将 compose/*.yml 里面的 
```yaml
version: '2.4'
```
给注释掉或者删除这行即可
```yaml
# version: '2.4'
```
之后重启即可解决。

**Comment by GrimalDev** [comment]
> Could the docs be updated?

Sorry to do some action on this obviously closed issue, but i have a Naive question.
From a "best practices of programming" point of view, isn't it always better to be explicit about versioning for the "Just in case" sake?

**Comment by glenjamin** [comment]
What's the reasonaing behind annoying everyone with the warning and making a few million projects update their files, as oppoosed to just ignoring the field and saying nothing?

**Comment by bkraul** [comment]
> What's the reasoning behind annoying everyone with the warning and making a few million projects update their files, as oppoosed to just ignoring the field and saying nothing?

I am going to guess ignoring it would not be proper cleanup. This is a deprecation. Deprecations carry warnings before the removal of the feature. It is saying at some point this will generate errors, so clean it up.

**Comment by glenjamin** [comment]
> > What's the reasoning behind annoying everyone with the warning and making a few million projects update their files, as oppoosed to just ignoring the field and saying nothing?
> 
> I am going to guess ignoring it would not be proper cleanup. This is a deprecation. Deprecations carry warnings before the removal of the feature. It is saying at some point this will generate errors, so clean it up.

Right, and I'm saying that this is more work for both the maintainers and every consumer in the world, when compared to simply ignoring the field.

Who benefits from this work?

**Comment by bkraul** [comment]
It's called proper SDLC. If this was not done, we would have a bloated, unmaintainable mess. So to your question, everyone benefits from it, maintainers and consumers alike. Cleaner code, accurate documentation and expected functionality. I know I sound like a snob (not trying to be one, honestly), and I understand the frustration with having to make changes, but I would say it is part of it.

**Comment by glenjamin** [comment]
> If this was not done, we would have a bloated, unmaintainable mess.

Every change has a cost and a benefit.

My proposal is that if you:
 - kept the version field in the schema
 - included a comment in the code to say it used to be used but isn't anymore
 - removed mention of version from the docs

Then that would not lead to ongoing bloat or maintainence burden.

Basically instead of doing that, you've had to implement a warning and a deprecation period, and many many thousands of people across the world either have to update their code, or live with the warning.

The APIs that people like the most are the ones that retain backwards compatibility, as that is more user friendly.

I appreciate that making breaking API changes is a common pattern that loads of projects do - but that doesn't necessarily mean they're always worth it.

There's writing on this subject out there if you go looking, eg http://blog.ezyang.com/2016/12/thoughts-about-spec-ulation-rich-hickey/

**Comment by daveisfera** [comment]
But what about when a feature from a newer version is used on older software that doesn't support it?

**Comment by hopeseekr** [comment]
> The version had (and in one case still has) a very ... limited relevance. It's purpose was to ... limit what you were allowed to write in those yaml files. The only case where that's still "relevant" is for docker stack.
> 
> The current file format is more of a "descendant" of the 2.x series and the 3.x series is, again, only relevant for docker stack, where 2.x had no ... relevance.
> 
> I'm glad it's gone. It was tiring to see "3" as version

I don't understand a single word that you said... Huh??

Are you saying that I can't write docker compose v3 "except for docker"? Well, what else is there???

Does this mean that docker-compose and "other" compose have forked so ahrd that "other compose" can't understand docker compose v3 files? That seems to be what youre saying.

**Comment by hopeseekr** [comment]
> From a "best practices of programming" point of view, isn't it always better to be explicit about versioning for the "Just in case" sake?

Yes, this change was obviously done with little thought, extremely little warning, absolutely no marketing, and by someone or some people with extremely little architecting wisdom.

It's a categorical bad move. XML still has versioning and it's only 1.0 for the last 26 years.

**Comment by hopeseekr** [comment]
> But what about when a feature from a newer version is used on older software that doesn't support it?

The new guys obviously don't think that far ahead into the future.

We can now no longer look at the first like of `docker-compose.yml` and understand implicitly how up-to-date it is.

`version 3.6` **means** something. It means "Supports v3 syntax and Docker 18+".

Removing it removes a lot of important information.

**Comment by wmorrell** [comment]
> I don't understand a single word that you said... Huh??
> 
> Are you saying that I can't write docker compose v3 "except for docker"? Well, what else is there???
> 
> Does this mean that docker-compose and "other" compose have forked so ahrd that "other compose" can't understand docker compose v3 files? That seems to be what youre saying.

Please see the documentation link from Xeckt in the first reply. The `version` top-level element has been deprecated and obsolete in `docker compose` for some time. The subcommand is now by default using the "default" running mode, where unknown attributes emit a warning, but are ignored. If running in "strict" mode, unknown attributes are an error; and if running in "loose" mode, unknown attributes are ignored and there is no warning. I'm not sure if there are flags implemented yet to run in "strict" or "loose" mode.

The file spec accepted by `docker compose` is different from the spec accepted by `docker stack`. The spec for version 2.x is for `docker compose`, and that subcommand is now removing `version` as a known attribute; because it is not used. The spec for version 3.x is for `docker stack`, and includes the additional attributes for choosing deployment targets in a Docker Swarm cluster. The two specifications are not compatible, but share some history. 

If you were trying to use the 3.x spec for `docker compose`, you were using only the parts that overlapped with the 2.x spec. So, in practice, `version: 3.6` doesn't actually mean anything at all, and hasn't for some time. Because `docker compose` has never implemented the 3.x spec additions.

**Comment by bkraul** [comment]
> > I don't understand a single word that you said... Huh??
> > Are you saying that I can't write docker compose v3 "except for docker"? Well, what else is there???
> > Does this mean that docker-compose and "other" compose have forked so ahrd that "other compose" can't understand docker compose v3 files? That seems to be what youre saying.
> 
> Please see the documentation link from Xeckt in the first reply. The `version` top-level element has been deprecated and obsolete in `docker compose` for some time. The subcommand is now by default using the "default" running mode, where unknown attributes emit a warning, but are ignored. If running in "strict" mode, unknown attributes are an error; and if running in "loose" mode, unknown attributes are ignored and there is no warning. I'm not sure if there are flags implemented yet to run in "strict" or "loose" mode.
> 
> The file spec accepted by `docker compose` is different from the spec accepted by `docker stack`. The spec for version 2.x is for `docker compose`, and that subcommand is now removing `version` as a known attribute; because it is not used. The spec for version 3.x is for `docker stack`, and includes the additional attributes for choosing deployment targets in a Docker Swarm cluster. The two specifications are not compatible, but share some history.
> 
> If you were trying to use the 3.x spec for `docker compose`, you were using only the parts that overlapped with the 2.x spec. So, in practice, `version: 3.6` doesn't actually mean anything at all, and hasn't for some time. Because `docker compose` has never implemented the 3.x spec additions.

Thank you for the explanation. It stopped from writing something that would have probably been a bit inflammatory, lol. A lot of outcry about something that has been a non-issue for quite a while. Took all of 2 seconds to sed my docker-compose files and remove the service spec.

**Comment by daveisfera** [comment]
> Thank you for the explanation. It stopped from writing something that would have probably been a bit inflammatory, lol. A lot of outcry about something that has been a non-issue for quite a while. Took all of 2 seconds to sed my docker-compose files and remove the service spec.

On my local laptop, I agree that it's a non-issue because it's relatively easy to keep things up to date, but what about on installed infrastructure that is supported for a long time? I guess that some/most of the enterprise distros have moved to podman and other options, so it's less of an issue there, but does this mean that docker is only intended for developer use and not meant for production use?

**Comment by bkraul** [comment]
No, actually, we do have docker swarm enterprise infra as well, and sed worked just as well. Really it is about the deployment implementation. We have similar deployment structures across dev/non-prod/prod (with dev being obviously docker standalone and non-prod/prod being swarm).

It's really not much of a change. Again, as explained, subcommands that have worked "with" the version before should work just fine. This is more about removing the warning (and eventual error).

The one situation where this could become a bit of a headache (which I handle some of those too) will be Portainer deployments (and the fact that you can define docker-compose in the UI), but, their team is already making changes to adjust.

**Comment by murilolivorato** [comment]
here same error .

**Comment by sbe-arg** [comment]
I bet this move is to piss off the podman compose files users and stand out from that XD (it is a joke)

Odd to warn for a version value. I would have left it optional instead of deprecating it. For some people it might have a purpose.

**Comment by twkonefal** [comment]
> As I recall, this isn't a bug, `version` is only informative since a long time ago now. You can use loose options and you don't need it, check the spec:
> 
> https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements

If it's informative, shouldn't it NOT output "WARN"? I don't expect most users interpret WARN as strictly informational.

**Comment by Xeckt** [comment]
> > As I recall, this isn't a bug, `version` is only informative since a long time ago now. You can use loose options and you don't need it, check the spec:
> > https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements
> 
> If it's informative, shouldn't it NOT output "WARN"? I don't expect most users interpret WARN as strictly informational.

That depends on how you interpret it. It ensures the user pays attention to it, because they might use `version` expecting some sort of behavioural difference.

**Comment by speller** [comment]
BTW, how to hide this message? Our environment is built from multiple docker-compose files. Sometimes we have to use docker-compose commands extensively. So it may print a few screens of the warning like this:

<img width="408" alt="image" src="https://github.com/docker/compose/assets/1829515/d4bea0e1-565f-43b4-b5d5-d71ede2ec377">

This is a light version of the output, actually.

How to hide these annoying messages except by editing many files at once?

**Comment by bkraul** [comment]
> BTW, how to hide this message? Our environment is built from multiple docker-compose files. Sometimes we have to use docker-compose commands extensively. So it may print a few screens of the warning like this:

yeah! remove the `version:` tag from your compose files! :)

**Comment by speller** [comment]
@bkraul The full question was about hiding without editing many files.

**Comment by bkraul** [comment]
@speller, OK what is the impediment to batch-modifying the many files? if in Windows, Notepad++ can instantly and safely (with preview) remove those lines. Or if you use a Mac, I am sure you can find a tool to use in that "glorious" ecosystem.

If in Linux (or mac cli), sed is your friend...one-liner. 2 if you want to play it safe. You execute them in the root path where all your files are (even if in subdirs, I am assuming all are in `/home/alex/projects`)

For finding the files (with line number of the occurrence) that will be affected:
```
grep -rn "^version:"
```

For applying the removal of the lines with `version:` tag:
```
find -iname "docker-compose.yml" | xargs sed -i '/^version:/d'
```

But again, sorry, I still don't see the issue here.

**Comment by rseymour** [comment]
Right if step 1 was set to warning, is step 2 not allow `docker-compose.yml` files with the version field to run? It seems like an INFO level item at best.  The change seemed to forget about the long tail of documentation and use cases outside of the core team.  Folks following docs like this: https://code.visualstudio.com/docs/containers/docker-compose will be seeing a warning for no good reason, other than an allergy to painless backwards compatibility.

**Comment by Xeckt** [comment]
> All of this churn and work and discussion and waste is being created... for what gain?

While there is a lot of files effected, it really doesn't change anything for the people who have it, it's just a simple warning to show it's obsolete so *it's not actually doing anything* by being there or not being there. So it's necessary to not have it, there's no major gain out of it. What is the use of it being there if it's not being used anyway? Would you rather it's there just for show?

**Comment by bkraul** [comment]
@Xeckt exactly. I see a lot of people complaining that they see a warning, and then turn around and complain that it is too much work to change it. Clearly the thought process is that the tool that is deprecating this for a reason needs to just make changes to accomodate for this preference. Sorry, I know it ruffles feathers and such, but oh well.

We are experiencing a massive situation with Chrome removing support for third-party cookies (specifically with Okta). We could sit and complain about "how much work will it be to re-implement to allow for this change", and try to get Google to back-track on the change, or we could actually do it, and have our applications be all the better for it. anyway, matter of preference.

**Comment by glenjamin** [comment]
> _t's not actually doing anything_ by being there or not being there. So it's necessary to not have it, there's no major gain out of it.

This exact argument works in reverse. If it doesn't matter, why introduce a warning at all?

Everyone who sees the warning for the first time now has to wonder if it's important, look it up, read this thread, and decide whether to take action or live with the warning.

> Clearly the thought process is that the tool that is deprecating this for a reason

No reason has ever been presented other than "it makes things a bit tidier".

> We are experiencing a massive situation with Chrome removing support for third-party cookies

Third party cookie changes are generally about trying to improve consumer privacy. If you disagree with such changes then you should definitely voice those concerns to the vendors.

Adding a warning for the presence of a field **that doesn't do anything either way** is not at all comparable.

**Comment by rseymour** [comment]
It should be INFO not a WARN if it doesn't affect anything. That's the basic issue here, a typo in the original PR that made an informative log line into a warning.

**Comment by bkraul** [comment]
> > Clearly the thought process is that the tool that is deprecating this for a reason
> 
> No reason has ever been presented other than "it makes things a bit tidier".

Last time I checked, that "is" a reason. Might  be you do not "agree" with the reason, but it was their prerogative as maintainers. Anyway. As I said, matter of preference and opinion.

**Comment by rseymour** [comment]
https://github.com/compose-spec/compose-go/pull/640

**Comment by bkraul** [comment]
Yep, and you saw the resolution of that by one of the contributors...So unless I am missing something, this was not a "typo in the original PR"

> I agree with @ndeloof, if we keep this as a simple message users will continue to use it and being confused when they will open issues about the file version v2 vs v3, and even sometimes with the Compose binary version itself. A warning message make it clear, it supposes you'll take action on your side if you don't want to be bother by the message again

**Comment by Xeckt** [comment]
> This exact argument works in reverse. If it doesn't matter, why introduce a warning at all?

Because people will use the version tag thinking it's actually doing something. The warning is there to show you it's not doing anything.

> Everyone who sees the warning for the first time now has to wonder if it's important, look it up, read this thread, and decide whether to take action or live with the warning.

This is a normal process for any software.

> No reason has ever been presented other than "it makes things a bit tidier".
https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements

**Comment by wmorrell** [comment]
A warning is appropriate. Just like a compiler emitting a warning for an unused variable. You don't *have* to do anything about the unused variable, just like you don't have to do anything about the `version` field. But it doesn't do anything, and hasn't done anything for *years*.

The only thing changing is that now `docker compose` has actual spec validation built-in. It will tell you if *any* field is there that isn't in the spec. This includes typos like `cnotext` under a `build` key.

This is a good thing! So either fix your files, using your bulk editor of choice -- including submitting a PR, going through CI, etc -- or *just ignore the warning*. It's doing literally nothing to hurt you. A warning *is* an informative message, and it doesn't matter if it's labeled "warning" or "info" or anything else.

**Comment by ndeloof** [comment]
`version` was declared obsolete as we introduced compose-specification in 2020. It's been 4 years users would have noticed "compose file format" is not defined by "_version 2 vs version 3_" antagonism.
A warning won't prevent you to use legacy compose file, will just let you know those are not up-to-date with the state of the art.

**Comment by glenjamin** [comment]
> `version` was declared obsolete as we introduced compose-specification in 2020. It's been 4 years users would have noticed "compose file format" is not defined by "_version 2 vs version 3_" antagonism.
> A warning won't prevent you to use legacy compose file, will just let you know those are not up-to-date with the state of the art.

I would suggest that the majority of users of docker compose files were not aware of these specification changes, nor would they care. Adding this warning has effectively forced a bunch of people to learn about these subtlties. For your project perhaps this is a desirable goal? But please take some time to consider the ecosystem impact from making platform-level changes like this - especially on a project that has had an excellent backwards compatibility record for many many years.

> The only thing changing is that now `docker compose` has actual spec validation built-in. It will tell you if _any_ field is there that isn't in the spec. This includes typos like `cnotext` under a `build` key.

This is great! But there is nothing about spec validation in general that _requires_ a warning about usage of the `version` key. The specification even mentions the version field used to be important but is no longer in use. Considering it obsolete was only actually documented in the specification 2 months ago in https://github.com/compose-spec/compose-spec/pull/489 - which is a whole month after this issue was opened!

**Comment by bkraul** [comment]
> I would suggest that the majority of users of docker compose files were not aware of these specification changes, nor would they care. Adding this warning has effectively forced a bunch of people to learn about these subtlties. For your project perhaps this is a desirable goal? But please take some time to consider the ecosystem impact from making platform-level changes like this - especially on a project that has had an excellent backwards compatibility record for many many years.

Help me understand somthing here. You are saying the majority of users were not aware or do not care, but all of the sudden the particular warning behavior is deemed critical and the mantainers must pull it back? If they "don't case" as you say, why should they care about the warning, which is something someone already mentioned here.

**Comment by glenjamin** [comment]
> Help me understand somthing here. You are saying the majority of users were not aware or do not care, but all of the sudden the particular warning behavior is deemed critical and the mantainers must pull it back? If they "don't care" as you say, why should they care about the warning, which is something someone already mentioned here.

They never needed to care before, their docker-compose files did what they told them to without complaint.

`docker compose up` continued to start the right containers as specified

and then one day, about 3 months ago, after docker compose automatically updated, it started emitting a warning every time they ran it

oh no! a warning, I'd better go look this up and find out what was important enough to merit adding a warning, and then take the appropriate action to make sure my containers keep starting

But then upon finding out what the warning is about (note that the warning itself isn't self-describing, it doesn't say what action should be taken), they find out that oh - nope. Nothing will ever break. The specification for docker-compose says that the version field is allowed but must be ignored. But we still have to either live with the warning, or change every compose file in the world.

A widely used configuration file like this is an API. Changing an API has a cost. I have stated repeatedly in this thread why I believe that cost is far larger than the benefit.

Every response I've seen so far has been in the vein of "well the maintainers wanted to, so you should live with it". And yes, I will live with it, and I'll change my files as I go along - but that doesn't mean I shouldn't politely voice my concerns, attempt to clearly state my reasoning, and hope that the maintainers reconsider - or at least avoid making more changes like this in future.

**Comment by bkraul** [comment]
> Every response I've seen so far has been in the vein of "well the maintainers wanted to, so you should live with it". And yes, I will live with it, and I'll change my files as I go along - but that doesn't mean I shouldn't politely voice my concerns, attempt to clearly state my reasoning, and hope that the maintainers reconsider - or at least avoid making more changes like this in future.

Even with me being on the other side of this preference. I 100% agree with this.
