### ISSUE TITLE
docker compose can not link a exists running docker container.

### ISSUE THREAD

**Issue by netroby** [docker/compose#1163]
docker compose can not link a exists running docker container.

In our production servers, we already running containers. such as redis, memcached, mysqld

But docker compose can not link exists docker container.

so Use less for production environment.

**Comment by dnephin** [comment]
You can link to an existing container with `external_links`

https://docs.docker.com/compose/yml/#external_links

**Comment by netroby** [comment]
One more question, when did this feature being added into compose? I have an very old fig installed. i wonder if i need to upgrade to compose

**Comment by ayogi** [comment]
For me it throws:
dial tcp: lookup logstash on 127.0.1.1:53: no such host

It is not able to resolve the container name, to which I want to link.
