### ISSUE TITLE
Copy from container to host too with `docker compose watch`

### ISSUE THREAD

**Issue by mihalt** [docker/compose#11658]
### Description

I found, that files just copy from my host to container

### Steps To Reproduce

After installed django and successfull command `docker compose exec web python manage.py makemigrations` I see created migrations in container but don't see them in host

### Compose Version

```Text
Docker Compose version v2.24.6-desktop.1
```

### Docker Environment

```Text
Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 9
  Running: 3
  Paused: 0
  Stopped: 6
 Images: 48
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.146.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 58.86GiB
 Name: docker-desktop
 ID: 935910c2-41e5-4698-842a-65d871025df0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
> I found, that files just copy from my host to container

Yes, this is what `sync` is about in watch mode. Can you please explain your use-case ?

**Comment by ndeloof** [comment]
I understand well what you're asking for, but I would like to better know _why_ you would rely on such bidirectional sync mechanism. Just a quick note that this would require "some way" to monitor container filesystem events, so this can't just come for free.

**Comment by mihalt** [comment]
> I understand well what you're asking for, but I would like to better know _why_ you would rely on such bidirectional sync mechanism. Just a quick note that this would require "some way" to monitor container filesystem events, so this can't just come for free.

do you know what is django migrations, that I mention earlier? https://docs.djangoproject.com/en/5.0/topics/migrations/#workflow

So, I would like not to do `venv` on my host and not to do `python manage.py makemigrations` outside docker, because I have been all dependencies installed in my docker container already. 

So, by this reason I do something like `docker compose exec app python manage.py makemigrations`. I have migrations file in docker after that, but I don't see them on my host and I can't add migrations to a git repository.

**Comment by ndeloof** [comment]
ok got it.
For such a scenario this would be simpler IMHO to rely on `docker cp` to get the files created inside container copied on host.

**Comment by mihalt** [comment]
> ok got it. For such a scenario this would be simpler IMHO to rely on `docker cp` to get the files created inside container copied on host.

no, this is not more simple. I can have decades of apps and migrations will be created individually for each folder of them. Of course I would not do all of this copies manually.

**Comment by ndeloof** [comment]
This would hardly be implemented in a portable way as this require either client to poll container for file changes, or some resident process in your container to watch files and let act as a "in container" extension for the client.

**Comment by mihalt** [comment]
> This would hardly be implemented in a portable way as this require either client to poll container for file changes, or some resident process in your container to watch files and let act as a "in container" extension for the client.

so, do you think that simple old volumes that bind my project folder with folder in container is the best way out for me?

**Comment by ndeloof** [comment]
I'm closing this issue as "not planned"

**Comment by mihalt** [comment]
> You indeed could use a bind mount, or setup an explicit rsync mechanism to get files back on host, or rely on a [mutagen](https://mutagen.io/) file share.

I think you should say in your documentation more obviously that it doesn't copy anything from container to host.

**Comment by jakajancar** [comment]
@ndeloof

I understand the logic behind not implementing bidirectional watch, both due to complexity as well as there is something "clean" in not allowing containers to modify the host.

However, I wonder if I'm missing something really obvious, as I don't get how people use Compose Watch for any practical use-case. The OP mentioned django migrations, but in any language, how do you add a dependency ("npm install", "cargo add", ...) without having a duplicate copy of the toolchain on the host too?
