### ISSUE TITLE
[BUG] docker-compose retrive path with linux format on Windows environment

### ISSUE THREAD

**Issue by arcanisgk** [docker/compose#11655]
### Description

I am trying to automate the cleaning of container logs in docker.

### Steps To Reproduce

for that I run this script from powershell:

```
docker ps --filter "name=WSDD-" --format "{{.ID}}" | ForEach-Object -Parallel { $containerId = $_.Trim(); if (-not $containerId.StartsWith("failed")) { Clear-Content -Path (docker inspect --format='{{.LogPath}}' $containerId) }  }
```

The idea is to eliminate all the logs from the containers of the projects whose name starts with "WSDD-"

The script returns this:

> Clear-Content: Cannot find path 'C:\var\lib\docker\containers\c90b46422b2feec4919f7d815018a106897de2d49d4eae4835761d7178df63a6\c90b46422b2feec4919f7d815018a106897de2d49d4eae4835761d7178df63a6-json.log' because it does not exist.
> Clear-Content: Cannot find path 'C:\var\lib\docker\containers\d5e9d96126e4969302cb3fcde1e050825e0fe80167845cf0abd106f6fe4a96d7\d5e9d96126e4969302cb3fcde1e050825e0fe80167845cf0abd106f6fe4a96d7-json.log' because it does not exist.
> Clear-Content: Cannot find path 'C:\var\lib\docker\containers\72efa0402c7f42e690f6599e135a2bbee38cf4e28cba1e2f41093180f59eaf96\72efa0402c7f42e690f6599e135a2bbee38cf4e28cba1e2f41093180f59eaf96-json.log' because it does not exist.
> 

On Windows, the Docker log path is usually located at C:\ProgramData\Docker\containers\[container_id]\[container_id]-json.log

Unless I'm wrong.

### Compose Version

```Text
Docker Compose version v2.24.5-desktop.1
```

### Docker Environment

```Text
Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.4.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.645GiB
 Name: docker-desktop
 ID: a9aa7bf2-0b92-4e9b-95a6-e8e4329091fd
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
As demonstrated by your command, Docker Compose is not involved here: it does not manage logs at all, it just creates container using Docker Engine API and let the engine collect logs and store those .. in the way it make sense depending on your installation.

Please also check running `docker inspect --format='{{.LogPath}}' $containerId` with an arbitrary docker container, I wonder the actual culript is the `Clear-Content` powershell command

**Comment by ndeloof** [comment]
running on Docker Desktop, engine is actually running on a linux VM, so logs are stored in the VM under `\var\lib\docker\containers\...`. `Clear-Content` command seem to check path exists on local (windows)  disk and obviously fails doing so

**Comment by arcanisgk** [comment]
@ndeloof 
but, `docker inspect --format='{{.LogPath}}' $containerId` 

Is it not clear to me, this command should return the path to the log file of the host Operating System or the internal path of the VM?

Example (this is the output in windows host OS):

docker inspect --format='{{.LogPath}}' $containerId


![image](https://github.com/docker/compose/assets/1207306/4236861f-c16f-4ef6-ad7e-3c0e2903d620)

**Comment by ndeloof** [comment]
`LogPath` gives you the path from docker engine process point of view, which is a Linux process. It's not aware being ran inside a VM. Same would apply if docker is running on a remote machine.
