### ISSUE TITLE
[BUG] `docker compose --env-file path up -d` hangs when `path` is a named pipe

### ISSUE THREAD

**Issue by felixfontein** [docker/compose#11656]
### Description

See https://github.com/getsops/sops/issues/1470. When `sops exec-file` is used, it by default uses a named pipe (instead of writing the decrypted file to disk). 

It seems that Compose tries to read the file three times, and two times of these happen in the call here: https://github.com/docker/compose/blob/3371227794f5f3645f4f19829c60a741635ed329/cmd/compose/compose.go#L605 I added `fmt.Printf` statements before and after that line, and I only got the second print after step 5 completed.

I'm not sure what is happening, since the code called there only seems to read the file once (https://github.com/compose-spec/compose-go/blob/main/dotenv/env.go#L51). Also I have no clue how to build Compose with modified source from other packages, so I cannot easily add more print statements there to try to get an idea :)

### Steps To Reproduce

1. Create a minimal Compose project with a single service.
2. Run `mkfifo envfile`
3. Run `docker compose --env-file envfile up --detach`
4. In a separate window, run `cat > envfile` and press CTRL+D. This stops the first read.
5. Run `cat > envfile` and press CTRL+D again. This stops the second read.
6. Run `cat > envfile` and press CTRL+D again. This stops the third read, and Compose starts doing some work.

### Compose Version

```Text
latest source version
```

**Comment by ndeloof** [comment]
env file is indeed read once early as compose command is executed (as some COMPOSE_XX variables can be declared and change the model loading logic), then again while parsing with compose-go library. I'm not sure about a 3rd time, anyway code is definitely not optimized to avoid multi-read of such a file.

**Comment by tangowithfoxtrot** [comment]
Could this be reopened please? It's still a problem for me.

**Comment by jip149** [comment]
can’t sops exec-env be used instead?
