### ISSUE TITLE
[BUG] docker compose config --format json returns YAML

### ISSUE THREAD

**Issue by StevenPaugh** [docker/compose#11669]
### Description

After upgrading past 2.24.7 we are having issues with `docker compose config --format json` returning yaml instead of json. 

I see this is supposed to be fixed according to https://github.com/docker/compose/issues/11646 but we are still having to downgrade the docker-compose-plugin package to 2.24.7 in order for the command to return json.

Is this expected? Seems to only be happening due to the docker-compose-plugin package as our current docker packages installed are:
docker-buildx-plugin/jammy,now 0.13.1-1~ubuntu.22.04~jammy amd64 [installed,automatic]
docker-ce-cli/jammy,now 5:26.0.0-1~ubuntu.22.04~jammy amd64 [installed]
docker-ce-rootless-extras/jammy,now 5:26.0.0-1~ubuntu.22.04~jammy amd64 [installed,automatic]
docker-ce/jammy,now 5:26.0.0-1~ubuntu.22.04~jammy amd64 [installed]
docker-compose-plugin/jammy,now 2.24.7-1~ubuntu.22.04~jammy amd64 [installed,upgradable to: 2.25.0-1~ubuntu.22.04~jammy]

Again to reiterate we only see this behavior while docker-compose-plugin is upgraded to v2.25.0. 

Thank you for any guidance that can be provided!

### Steps To Reproduce

docker-compose-plugin upgraded to v2.25
 Run `docker compose config --format json` 
Verify output is not in json as expected. 

### Compose Version

```Text
docker compose version
Docker Compose version v2.25.0

```

### Docker Environment

```Text
docker info
Client: Docker Engine - Community
 Version:    26.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 29
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-1015-gcp
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.61GiB
 Name: (HOSTNAME)
 ID: 179b0e92-15e4-4119-ba61-cfd790162158
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by StevenPaugh** [comment]
Realizing the docker-compose-plugin version is just behind according to the docs for installing from source.. Anyone know what the ETA is for 2.26 version of docker-compose-plugin to get pushed to ubuntu repositories with everything else?

**Comment by ndeloof** [comment]
Closing as a duplicate for #https://github.com/docker/compose/issues/11627

system package repository download.docker.com is updated according to the docker engine release cycles, so don't get immediate updates after we release compose. A simple workaround is for you to download binaries from our release page
