### ISSUE TITLE
Filter out empty DNS entries

### ISSUE THREAD

**Issue by IvanRibakov** [docker/compose#11690]
### Description

Previously this DockerCompose configuration would successfully start a container:
```
# ANOTHER_SERVICE_IP is not set and defaults to blank string
dns: ${ANOTHER_SERVICE_IP}
```

But using latest Docker+DockerCompose on Linux
```
Docker version 26.0.0, build 2ae903e
Docker Compose version v2.25.0
```
container fails to start:
```
WARN[0000] The "ANOTHER_SERVICE_IP" variable is not set. Defaulting to a blank string. 
Error response from daemon: bad nameserver address : ParseAddr(""): unable to parse IP
```
https://github.com/moby/moby/blob/d25b0bd7ea6ce17ca085c54d5965eeeb66417e52/libnetwork/sandbox_dns_unix.go#L259-L269

I can see how it makes sense from Docker perspective to be strict about supplied configuration options. I'm wondering whether it would be possible for the DockerCompose to filter out empty DNS entries before passing them to Docker and logging a warning. As far as I understand there is no other way to have a conditional behaviour that either uses external DNS service or the default host one without creating 2 different service configurations.

**Comment by enmanuelmoreira** [comment]
Same problem here

**Comment by jhrotko** [comment]
@IvanRibakov Could you provide an example?

**Comment by IvanRibakov** [comment]
I went as far as to provide a [pull request](https://github.com/docker/compose/pull/11691) which unfortunately was rejected. 
@jhrotko what exactly are you looking for from the example that is missing from the current issue description?

**Comment by IvanRibakov** [comment]
@ndeloof Than you for the https://github.com/compose-spec/compose-go/pull/700 . I see in the PR that `services.*.dns` is a hardcoded field. Am I right that this feature can be applied to any other service field using YAML tags similarly to [`!reset` ](https://docs.docker.com/reference/compose-file/merge/#reset-value)or [`!override`](https://docs.docker.com/reference/compose-file/merge/#replace-value)? Or is this not available at the moment?

**Comment by ndeloof** [comment]
@IvanRibakov this is a generic mechanims, but I only configured it for `dns` with the intent we can add more step by step

**Comment by IvanRibakov** [comment]
Ok, so no `!omitempty` YAML tag at the moment, right?

**Comment by ndeloof** [comment]
yes indeed, this is hard-coded support in compose-go
