### ISSUE TITLE
Add restart option "limited".

### ISSUE THREAD

**Issue by pier4r** [docker/compose#11788]
### Description

The documentation as today (2024-05-03) is

```
    restart: "no"
    restart: always
    restart: on-failure
    restart: on-failure:3
    restart: unless-stopped
```

the `restart: on-failure:3` _almost_ covers the request. The `on-failure:3` restarts 3 times the container if the container exits with a "bad" status code. Instead sometimes one wants to give a limited number of restarts (and then one needs to investigate) to containers that may exit with a good status code (therefore zero).

Yes I know, the application should be good enough to exit with a proper status code in case of error, but in the real world not all applications exit with proper status codes. Therefore a `restart: limited:3` could help in this case.

Hopefully it could be implemented without a major effort. Thank you!

**Comment by ndeloof** [comment]
`restart` is a docker engine feature, compose just configure the engine based on your yaml declaration. Please open a feature request on https://github.com/moby/moby
