### ISSUE TITLE
[BUG] YAML top-level name linter does not accept env variables

### ISSUE THREAD

**Issue by DeanAyalon** [docker/compose#11787]
### Description

Within the docker-compose.yml

```yml
name: ${PROJECT}
services: 
```

While any other property accepts ${VARIABLES} from .env, the name property shows the error:

`String does not match the pattern of "^[a-z0-9][a-z0-9_-]*$".yaml-schema: docker-compose.yml`
Source: [compose-spec.json](https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json)

The variable still works, and the containers do open under the project name specified in the .env file - The error is in the linting itself

### Steps To Reproduce

Create a .env file with a variable defined for the compose project name
```.env
PROJECT=project-name
```

Create a compose yml with the top-level name property set to a .env variable
```yml
name: ${PROJECT}
...
```

Run the compose
`docker compose up`

The container will open under the project defined in .env, but the YML file will show the error described above

### Compose Version

Docker Compose version v2.26.1-desktop.1

docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

(Using docker compose)

### Docker Environment

```console
Client: Docker Engine - Community
 Version:    26.1.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1-desktop.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1-desktop.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.27
    Path:     /usr/lib/docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /usr/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.6.3
    Path:     /usr/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 7
  Running: 2
  Paused: 0
  Stopped: 5
 Images: 60
 Server Version: 26.1.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-76060800daily20240311-generic
 Operating System: Pop!_OS 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.19GiB
 Name: dean-pop
 ID: abfda37a-4a3a-43c6-9e29-524ea89c51c6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: jackdeaniels
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by DeanAyalon** [comment]
My apologies, the enter key simply posted the issue....
Editing the post -_-

**Comment by ndeloof** [comment]
Quick workaround: To set project name from .env file, better use `COMPOSE_PROJECT_NAME` and don't set a `name` attribute in your yaml file

**Comment by DeanAyalon** [comment]
@ndeloof thanks!
No longer in my use case, but good to know :)

**Comment by DeanAyalon** [comment]
> `name` parsing takes place early in the compose file loading logic, before interpolation takes place

No problem with closing this issue, but the interpolation does work, the linter is the only one showing error. The project name parses correctly with the interpolated variable

**Comment by ndeloof** [comment]
Ok, I misunderstood. 
the issue then is that your IDE relies on the compose-specification json schema, which is designed to validate the compose.yaml file _after_ interpolation, so check `name` uses a valid format.

**Comment by DeanAyalon** [comment]
> Ok, I misunderstood. the issue then is that your IDE relies on the compose-specification json schema, which is designed to validate the compose.yaml file _after_ interpolation, so check `name` uses a valid format.

Exactly, I understand why it's unplanned, and that the json schema cannot really validate the interpolated variables

The solution provided, however, works great!
