### ISSUE TITLE
Assign container name to /sys/class/net//ifalias in docker compose

### ISSUE THREAD

**Issue by BuxtonCalvin** [docker/compose#11796]
### Description

Using node exporter, I'd like to be able to extract a container name from the container's virtual interface 'ifalias' data.  I use node exporter to do this for other  '/sys/class/net/' docker network metrics and a typical metric looks like this:
`node_network_info{address="02:99:00:90:03:b2",adminstate="up",broadcast="ff:ff:ff:ff:ff:ff",device="vethfe8c6f3",duplex="full",ifalias="",operstate="up"} 1`  

The ifalias field is currently empty for both the metric and the ifalias file on the host for my docker containers.  I'd like to be able to assign the container name to this field.

**Comment by BuxtonCalvin** [comment]
Because the virtual interface id changes each time you recreate a container, I can't even map prometheus labels to a given vethID as the map breaks each time the container is updated.  Setting the ifAlias at the time of container creation would solve the problem of not knowing what interface belongs to what container, and since the ifAlias would remain constant, the ifAlias metric would display consistently during metric queries.

**Comment by jhrotko** [comment]
@BuxtonCalvin this request seems to be related with the engine itself and not compose. I would propose for you to move your feature request to https://github.com/moby/moby
