### ISSUE TITLE
Add warning when use `env_file` and `environments` at the same time

### ISSUE THREAD

**Issue by fzn0x** [docker/compose#11799]
### Description

Can we add warning when we use `env_file` and `environments` at the same time? `env_file` will not work and `environments` will use default `.env` instead.

For most people, this is really waste time and I've seen so many Issues and Stackoverflow posts talking about this, I think adding a warning could solve the problem.

**Comment by ndeloof** [comment]
There's no reason to warn user about this, both are valid and there's many relevant scenario where user will use both.

> service will ignore env_file

it won't, but `environment` has precedence so same value in `env_file` will be ignored. Still other variables will be used.
See https://docs.docker.com/compose/environment-variables/set-environment-variables/#additional-information-2
