### ISSUE TITLE
[ISSUE]how to fix top-level object must be mapping

### ISSUE THREAD

**Issue by ngenBen** [docker/compose#11831]
### Description

debug: false
uuid: c9a04096-8ed7-48cf-88cb-e0a5c5ce1671
token_id: iOCAGj5xLgRwMZWQ
token: ufnjsWwngn5FdzpuWqQBUB9sb1iunGmc0f5r0uO2lnDnesqvfI8yf9wjWVTaR7sN
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/8365-4-194-65-187.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/8365-4-194-65-187.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://zany-space-happiness-g4pw4jwj4qx27p-80.app.github.dev'

I put this in nano /etc/pterodactyl/config.yml

**Comment by ndeloof** [comment]
How does this relate to Docker Compose ?
