### ISSUE TITLE
[BUG] Using force-recreate flag will result in docker still using the cached old image 

### ISSUE THREAD

**Issue by epicseven-cup** [docker/compose#11855]
### Description

When I was rebuilding my image and using the force-recreate flag, it was rebuilding the old image instead. This happen a few times when I was working with docker recently.

I always ended up cleaning all the all image with docker system prune

### Steps To Reproduce

run a docker container with force-recreate flag

### Compose Version

```Text
docker compose version : Docker Compose version v2.27.0
docker-compose version: N/A
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```

**Comment by ndeloof** [comment]
I hardly can imagine how this could happen. Please provide more details on circumstances this happened to you. If you can reproduce, please capture command output and `docker image inspect xx` about the rebuilt image + `docker inspect xx` about the (recreated) container

**Comment by epicseven-cup** [comment]
sorry... looks like I forgot to pass in build flag. I will close this issue now
