### ISSUE TITLE
May I ask if docker-compose does not support Tab completion command anymore? The previously configured command doesn't seem to work properly now

### ISSUE THREAD

**Issue by db-root** [docker/compose#11864]
### Description

May I ask if docker-compose does not support Tab completion command anymore? The previously configured command doesn't seem to work properly now

**Comment by ndeloof** [comment]
Compose do support completion, using the same built-in mechanism used by the docker CLI
Note: this is not the same as the legacy hand-written completion script, but automatic generation based on dynamic command completion, see `docker completion` command
