### ISSUE TITLE
[BUG] compose captures CTRL+C (MacOS, Iterm2, zsh)

### ISSUE THREAD

**Issue by ErjanGavalji** [docker/compose#11869]
### Description

Running `docker compose up` when the program in the container exits successfully leaves the CTRL+C combination captured and the key combination does not work anymore.

### Steps To Reproduce

On a MacOS (Sonoma 14.5), using Iterm2 (v3.5.0) and zsh (5.9),

1. Add the following two files:

*docker-compose.yml*:
```
name: simple-test
services:
  app:
    image: node:20.14.0-alpine3.20
    command:
      - node
      - /app.mjs
    volumes:
      - ./app.mjs:/app.mjs
```

and *app.mjs*:
```
console.log("Hello, world!");
```

2. Run `docker compose up`
3. Type "anything"
4. Press CTRL+C

### Compose Version

```Text
v2.27.0-desktop.2
```

### Docker Environment

```Text
Client:
 Version:    26.1.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0-desktop.1
    Path:     /Users/testuser/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0-desktop.2
    Path:     /Users/testuser/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.29
    Path:     /Users/testuser/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/testuser/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     /Users/testuser/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/testuser/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     /Users/testuser/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/testuser/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.8.0
    Path:     /Users/testuser/.docker/cli-plugins/docker-scout

Server:
 Containers: 42
  Running: 24
  Paused: 0
  Stopped: 18
 Images: 50
 Server Version: 26.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.26-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.62GiB
 Name: docker-desktop
 ID: eae3962c-2c56-427f-a81a-b4fc9fdd428d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/testuser/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  127.0.0.1:8081
  hubproxy.docker.internal:5555
  localhost:1111
  localhost:8081
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Anything else?

running `reset` in the terminal resets the key combination as per hints on [StackOverflow](https://stackoverflow.com/questions/46479641/ctrlc-not-working-in-iterm2) and [Superuser](https://superuser.com/questions/1178934/iterm2-ctrl-c-doesnt-work-sometimes/1319732#1319732)

**Comment by glours** [comment]
Hello @ErjanGavalji 
What do you mean by type anything, should we interact with the shell running the `docker compose up` command?

I tried to your reproduction case but the process exits to fast and I can't send the CTRL+C signal, so I added a sleep of 5s and I can successfully stop the process
```shell
> bat app.mjs
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: app.mjs
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ console.log("Hello, world");
   2   │ await new Promise(resolve => setTimeout(resolve, 5000));
   3   │ console.log("Goodbye");
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────
> docker compose up
[+] Running 2/0
 ✔ Synchronized File Shares                                                                                      0.0s
 ✔ Container simple-test-app-1  Created                                                                          0.0s
Attaching to app-1
app-1  | Hello, world
Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container simple-test-app-1  Stopped                                                                          3.5s
 ```
 
I'm using MacOs Sonoma 14.5, Iterm2 v3.5.0 and zsh 5.9 (x86_64-apple-darwin23.0) like you

**Comment by ErjanGavalji** [comment]
Hi @glours, sorry for not being clear. Let me elaborate:

The exit of the application is expected and that's exactly the behavior I'm experiencing.

AFTER the `docker compose up` process exists successfully, pressing CTRL+C doesn't do anything. I can type commands and execute them, but CTRL+C doesn't get "unlocked". I can type some erroneous command, e.g. the string `anything` and pressing CTRL+C does not ignore it.

**Comment by ndeloof** [comment]
`docker compose up` is not interactive, what you type on console isn't sent to container. I guess what you're looking for is  `docker compose run` which will connect your terminal to container

**Comment by ErjanGavalji** [comment]
Well, it seems like an isolated case that happens on my machine only. I will investigate further with restarting the machine and zsh configurations and will follow up if solved.

Closing the issue now.

@glours @ndeloof, thanks both!

**Comment by nobeans** [comment]
I have also reproduced the same issue. Here are the steps to reproduce and the problem description:

**Reproduction steps:**

```sh
$ mkdir -p /tmp/test-issue
$ cd /tmp/test-issue
$ cat > compose.yaml <<EOF
services:
  test:
    image: alpine
    command:
      - echo
EOF
```

Run the docker compose up -d test command:

```sh
$ docker compose up -d test
```

After returning to the prompt, press Ctrl-C to create a new line in the zsh shell expectedly.

Next, remove the -d option. Run the docker compose up test command:

```sh
$ docker compose up test
After returning to the prompt, press Ctrl-C.
```

- **Expected behavior**: Pressing Ctrl-C should create a new line in the zsh shell.
- **Actual behavior**: Pressing Ctrl-C is ignored, and nothing happens.

**Comment by ndeloof** [comment]
@nobeans confirmed there's an issue restoring the terminal after compose completed
https://asciinema.org/a/l94Evr7RxWocIXmxQX9VC2biJ

running with menu disabled doesn't suffer from this bug
https://asciinema.org/a/g2qce7asIYZ1xUN9JjgsRPW9G

cc @jhrotko
