### ISSUE TITLE
[BUG] environment variable not correctly overload when using multiple .env files

### ISSUE THREAD

**Issue by christophe-calmejane** [docker/compose#11870]
### Description

The documentation example (https://docs.docker.com/compose/environment-variables/set-environment-variables/#additional-information) for overloading environment variables using multiple .env files doesn't seem to work as expected with compose version 2.27.0.

## Use these files

 _.env_
```
MYVAR=Default
```

_.env.override_
```
MYVAR=Override
```

_docker-compose.yml_
```yml
services:
  shell:
    image: ubuntu:22.04
    env_file:
      - path: .env
        required: true
      - path: .env.override
        required: true
    environment:
      - DOCKER_EXPORTED_VAR=${MYVAR}
    entrypoint: /bin/bash
```

## Run compose config command
```
$ docker compose config
name: testdocker
services:
  shell:
    entrypoint:
      - /bin/bash
    environment:
      DOCKER_EXPORTED_VAR: Default
      MYVAR: Override
    image: ubuntu:22.04
    networks:
      default: null
networks:
  default:
    name: testdocker_default
```
See how _MYVAR_ is correctly overridden by the _.env.override_ file as it is exported in the report log.
But the _DOCKER_EXPORTED_VAR_ is not using the overload.

## Run another compose config command but forcing env files from command line
```
$ docker compose --env-file .env --env-file .env.override config
name: testdocker
services:
  shell:
    entrypoint:
      - /bin/bash
    environment:
      DOCKER_EXPORTED_VAR: Override
      MYVAR: Override
    image: ubuntu:22.04
    networks:
      default: null
networks:
  default:
    name: testdocker_default
```
This time, both variables are correctly exported.

## Not what the documentation says:
This section of the documentation clearly says that when using multiple files, they are loaded in sequence and that when the same variable is defined multiple times, the last definition wins:
![image](https://github.com/docker/compose/assets/23314088/08adba5a-2d07-4ee2-be13-1cda3831a2e6)

### Compose Version

```Text
$ docker compose version
Docker Compose version v2.27.0-desktop.2

$ docker-compose version
Docker Compose version v2.27.0-desktop.2
```

**Comment by nsaccente** [comment]
Can confirm I have the same problem. I took the time to create a script to make it easier to test. 

```sh
# Creates globalexample and globalxample/localapp.
# You can rm -r globalexample when you're done
mkdir -p globalexample/localapp

# Create env file in globalexample
cat > globalexample/env-global  << EOL
FOO="global foo!"
BAR="global bar!"
EOL

# Create env file in same dir as compose file
cat > globalexample/localapp/env-local << EOL
BAR="local bar!"
EOL

# Create .env file in same dir as compose file
cat > globalexample/localapp/.env << EOL
FOO=".env foo!"
EOL

# Create a docker-compose file in globalexample/localapp
cat > globalexample/localapp/docker-compose.yaml << EOL
services:
  echo:
    image: "alpine:3.14"
    env_file:
      - ../env-global
      - .env
      - env-local
    environment:
      - FOO=\${FOO}
      - BAR=\${BAR}
    entrypoint:
    - env
EOL

```

**Comment by ndeloof** [comment]
Docs on environment variables and interpolation is confusing, I proposed a clarification as https://github.com/docker/docs/pull/19481

here, `environment` and `env_file` in compose.yaml are **not** involved in interpolation, they just directly set container environment. But `.env` is the default file being used for interpolation, so this one is loaded without you have to tell compose, so variables being replaced based on this file but not the other.

**Comment by nsaccente** [comment]
Can we all agree that even if things are working perfectly as intended, this usage makes no sense? I'd really like to be able to establish global variables in an .env file somewhere else, and set project specific variables in a local .env

**Comment by christophe-calmejane** [comment]
I'm sorry but I wouldn't say it's working as intended. The doc says that we can use multiple .env files and if the same variable is defined multiple times in these files, the last definition takes precedence.
When looking at my example, it's not the case, except when using the command line option.

Yes of course, I'm not directly passing the variable to the environment (not the same name) but the example is doing the same thing: DEBUG=${DEBUG}
But I think this is actually how the bug was hidden since it's a special case. I actually believe in this case that 2 variables are defined, the left part first (which would not have the correct value), then the right part that overrides the left one (with the correct value this time).

**Comment by ndeloof** [comment]
@christophe-calmejane this seems to be unrelated to the reported issue (which is just about confusion between variable interpolation and use of services.environment | services.env_file. Please create a dedicated issue with an actual example.

**Comment by christophe-calmejane** [comment]
It's not unrelated. I did create that ticket for that exact issue. I also very explicitely explained the difference btw the 2 ways of using env files in my example.

**Comment by ndeloof** [comment]
ok, so please re-explain. What you initially reported is that you use `environment` and `env_file` expecting interpolation to use those, which as I explained is wrong (and docs are terrible to explain this). About https://github.com/docker/compose/issues/11870#issuecomment-2146745889 an illustration example would help me better understand your issue.

**Comment by nsaccente** [comment]
In this script, we don't create a .env file, but create two other env_files with different names, but add them to the docker-compose.

```sh
# Creates globalexample and globalxample/localapp.
# You can rm -r globalexample when you're done
mkdir -p globalexample/localapp

# Create env file in globalexample
cat > globalexample/env-global  << EOL
FOO="global foo!"
BAR="global bar!"
EOL

# Create env file in same dir as compose file
cat > globalexample/localapp/env-local << EOL
BAR="local bar!"
EOL

# Create a docker-compose file in globalexample/localapp
cat > globalexample/localapp/docker-compose.yaml << EOL
services:
  echo:
    image: "alpine:3.14"
    env_file:
      - ../env-global
      - env-local
    environment:
      - FOO=\${FOO}
      - BAR=\${BAR}
    entrypoint:
    - env
EOL
``

Neither FOO, nor BAR are populated, despite being set in `../env-global` and `env-local`

```sh
$ cd globalexample/localapp/
$ docker-compose up
WARN[0000] The "FOO" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
[+] Running 1/0
 ✔ Container localapp-echo-1  Created                                              0.0s 
Attaching to echo-1
echo-1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
echo-1  | HOSTNAME=09b5f2c3b30c
echo-1  | FOO=
echo-1  | BAR=
echo-1  | HOME=/root
echo-1 exited with code 0
```

**Comment by christophe-calmejane** [comment]
In order to be able to use the ssh-agent of the host from the container, we need to define the `SSH_AUTH_SOCK` env variable in the container, and mount the host's content of this (same) variable to the container. Unfortunately on macOS this is a unix domain socket and it is not supported by Docker. A ticket was raised many many years ago on the docker issue tracker but it was closed as "won't fix" as it involves dealing with the FS driver or something.

A workaround was found, to change content of that variable when passed to the container (but NOT changing it for the host). The ticket was closed with reason "define SSH_AUTH_SOCK in .env".

This cannot work for multiple reasons:
- first, even if you define something in the `.env` file it won't be taking into account since that variable already exist in the host system (and the doc is very clear about that, the `.env` file will only override a variable if it isn't already defined in the host)
- second, since I want to commit the `.env` file in my repo so every other users have a working repository whatever their env, I need to take into account linux and windows. I found a way to do exactly that, but it relies on being able to use a `.env.override` file to overload the variable. But this only work if explicitely passed from command line, not if we let the default mecanism work (and this part is exactly what I explained in my OP example).

I hope this makes more sense, but bottom line is I don't think it's a "non-issue" that both ways of using `.env` and `.env.override` (ie. explicit from command line, and through `env_file` attribute) yield a different behavior... but maybe I wrong, I just think it makes more sense.

**Comment by ndeloof** [comment]
Again, `env_file` attribute in your compose file is **NOT** used to interpolate variables as `FOO=\${FOO}`.
To get interpolation use `docker compose --env-file ../env-global --env-file env-local xxx`

Then, `environment` has precedence over `env_file` so `FOO` and `BAR` will be set according to value computed by interpolation, as as logged in warning "_The "FOO" variable is not set. Defaulting to a blank string. _" so you eventually get FOO="" as demonstrated by your command.

**Comment by ndeloof** [comment]
os environment variable won't be propagated to container by default, to set SSH_AUTH_SOCK in a container from a custom value, just use:
```yaml
services:
  test:
    environment:
      SSH_AUTH_SOCK=${MY_CUSTOM_ SSH_AUTH_SOCK}
```
then you can declare this variable either as os environment or inside a .env file

About using multiple env and overrides, there's no plan to have more ways to load variables (the existing combinations already are confusing and source for many issues). A simple way is to have your override use `export` and source it inside your terminal before you start a development session.

**Comment by christophe-calmejane** [comment]
> Again, `env_file` attribute in your compose file is **NOT** used to interpolate variables as `FOO=\${FOO}`. To get interpolation use `docker compose --env-file ../env-global --env-file env-local xxx`
> 
> Then, `environment` has precedence over `env_file` so `FOO` and `BAR` will be set according to value computed by interpolation, as as logged in warning "_The "FOO" variable is not set. Defaulting to a blank string. _" so you eventually get FOO="" as demonstrated by your command.

This is exactly my complain. We need to tell all our users to use this command line, even though we took the time (and committed) to create files to they can use run `docker compose`.

But I see your point.

**Comment by ndeloof** [comment]
¯\\_(ツ)_/¯

**Comment by nsaccente** [comment]
> Again, `env_file` attribute in your compose file is **NOT** used to interpolate variables as `FOO=\${FOO}`. To get interpolation use `docker compose --env-file ../env-global --env-file env-local xxx`
> 
> Then, `environment` has precedence over `env_file` so `FOO` and `BAR` will be set according to value computed by interpolation, as as logged in warning "_The "FOO" variable is not set. Defaulting to a blank string. _" so you eventually get FOO="" as demonstrated by your command.

Ahhh I see what you're saying... Dang it.

I still think env_files should be used for interpolation, but this seems like a fight I don't think I'd win.

**Comment by christophe-calmejane** [comment]
> os environment variable won't be propagated to container by default, to set SSH_AUTH_SOCK in a container from a custom value, just use:
> 
> ```yaml
> services:
>   test:
>     environment:
>       SSH_AUTH_SOCK=${MY_CUSTOM_ SSH_AUTH_SOCK}
> ```
> 
> then you can declare this variable either as os environment or inside a .env file

I don't want my users to have to define some external variable. I want them to `git clone`, then just `docker compose`. I need idiot proof procedure (the less the better).
The only option is to use `.env` file, but like I said it doesn't work as expected for all environments. I'd be happy if you can provide a solution that would work all the time:
- on macOS: `SSH_AUTH_SOCK` variable needs to be set to `/tmp/Foo`
- on macOS: We also need to mount `/tmp/Foo` to `/tmp/Foo`
- on windows/linux: We need `SSH_AUTH_SOCK` to be passed as defined by the host
- on windows/linux: We need to mount `$SSH_AUTH_SOCK` to `$SSH_AUTH_SOCK` (ie. whatever is defined in that variable)


> About using multiple env and overrides, there's no plan to have more ways to load variables (the existing combinations already are confusing and source for many issues). A simple way is to have your override use `export` and source it inside your terminal before you start a development session.

Now I see why so many people is moving to devcontainers :)

**Comment by ndeloof** [comment]
`env_file` is just the exact mapping as docker run flag `--env-file` - compose file is basically a yaml view of the docker run command line

**Comment by christophe-calmejane** [comment]
So just to be clear.
If I look at the documentation, and more specifically to this part:
![image](https://github.com/docker/compose/assets/23314088/88b4b5a2-4991-4b7b-84e8-894d2debd544)

My OP example is almost the same, the only difference is that my variable is not the same on the left and right part of the equal sign
(doc: `DEBUG=${DEBUG}`, my code: `DOCKER_EXPORTED_VAR=${MYVAR}`)

Reading the doc (**Docker Compose replaces ${DEBUG} with the value from the .env file**) I expect my `DOCKER_EXPORTED_VAR` to be defined by the value inside my `.env` file. And since I'm using multiple env files and the doc saying (**If the same variable is defined in multiple files, the last definition takes precedence**) I would expect in my example that `DOCKER_EXPORTED_VAR=Override`.

So to be 100% clear, you say it is an error in the documentation? If so, what's the point of having that `env_file` attribute if we always need to use the `--env_file` command line option?

Sorry to insist, I just want to make sure I clearly understand why this is not a bug.

**Comment by ndeloof** [comment]
> I expect my DOCKER_EXPORTED_VAR to be defined by the value inside my .env file

true. `.env` is the default path used if you don't run compose with an explicit `--env-file` flag

The second point in the doc is where things get confusing, cause then it's about the container environment, not interpolation. 

> what's the point of having that env_file attribute if we always need to use the --env_file command line option?

Those are not for the same purpose. `env_file` is an alternative to a long list of `environment` entries. This is just the same as `docker run` flags:

```
 -e, --env list                         Set environment variables
      --env-file list                    Read in a file of environment variables
```

By the way, if you don't want user to bother with a long command line using multiple `--env-file` flags, there's a common solution to this need: `make`

**Comment by christophe-calmejane** [comment]
Well that is exactly my point (and showcased in my example): using --env_file and specifying env_file attribute doesn't yield the same result regarding what is passed to the docker container.

The "make" proposal is unfortunately unacceptable by some of my users that can only afford to install the minimum in their environment (eg. docker desktop, git). That is why I'm looking for the simplest solution possible.
