### ISSUE TITLE
[BUG] Reopen: #6329 : Docker compose fails to start service that use option network_mode: service. Cannot join network of a non running container #6329

### ISSUE THREAD

**Issue by zwimer** [docker/compose#11872]
### Description

This issue was closed by stale-bot, but the issue remains as of `Docker version 26.1.3, build b72abbb`. It should be re-opened.

https://github.com/docker/compose/issues/6329

### Anything else?

I've run into this bug as well, where containers marked `restart: always` do not always restart (as in they fail to start then the daemon does not attempt to restart them) if they are marked `network_mode: service: myvpn` when the daemon restarts. I suspect that these non-restarted services are trying to use the network of the `myvpn` container that existed prior to the daemon's restart; this network might be removed and re-created by the daemon starting a new version of `myvpn`, but by this point the daemon might have already instructed the `network_mode: service:myvpn` to use the old `service: myvpn` network. Though this is just my guess after probing around for a few minutes, I'm not sure if it really the case.

**Comment by ndeloof** [comment]
You are expecting containers after an OS restart to respect the compose relationship. But compose is a client-side command, not backed in the docker engine. There's nothing compose can do to help here. This would require Docker engine to manage containers restart with dependency relations (container A require network stack from container B) which would be a significant architecture change.

If you want services to be up after an OS reboot, better configure a systemd service to execute `docker compose up` and enforce application is running/restarted

**Comment by zwimer** [comment]
Understandable and unfortunate. 

In my case, `docker compose up` would be insufficient as I'd like the daemon just to restart the running containers (i.e. if one is stopped and removed for some reason it should stay that way), yet I see no easy and clean way to do this other than basically writing a script to query the daemon about which containers should be running then `docker compose up -d`'ing each individual service to do so.

In any case, it might be worth documenting this (even if it is defined behavior, it was unexpected and confusing to figure out why the containers were not being restarted). Otherwise, if I understood you correctly, this can probably be "Closed as not planned"? Thanks for the clear explanation @ndeloof !

**Comment by ndeloof** [comment]
no need to write a script. `docker compose up` does exactly what you describe: query the daemon, compare actual state vs config, and start/create containers accordingly

**Comment by zwimer** [comment]
`docker compose up` is not exactly what I was looking for, since I want it to not start containers that were down before.

**Comment by zwimer** [comment]
A good mitigation I found for this is to add a healthcheck to the container which creates the network, then to attaching containers addd:
```yml
depends_on:
  my_network_container:
    condition: service_healthy
network_mode: "service:my_network_container"
```

**Comment by Pinkbyte** [comment]
Unfortunately(at least for me), even with 'condition: service_healthy' sometimes containers with 'network_mode: service' or 'network_mode: container' do not properly start after reboot
