### ISSUE TITLE
[BUG] Connection between both dockerized database and python cron-job cannot be stablished

### ISSUE THREAD

**Issue by brunolnetto** [docker/compose#11875]
### Description

I wrote this repository https://github.com/brunolnetto/db-cron-docker. The main goal is basically connect to database and log 'Hello world' in a log file inside the container. Despite of simplicity, it does not accomplish desired behavior. I suspect, the reason is the network accessibility.

### Steps To Reproduce

1. Clone the repository;
2. Run pip install virtualenv && virtualenv .venv;
3. Run source .venv/bin/activate;
4. Run pip install -r requirements.txt;
5. Rename .env.template for .env
6. Run docker compose up -d;
7. Run make up;
8. Run make log-cron;

### Compose Version

```Text
Docker Compose version v2.27.0
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    26.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.15.0-107-generic
 Operating System: Ubuntu Core 22
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.36GiB
 Name: falcon
 ID: ea63feef-d565-434e-a157-82ed10a640cb
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Username: brunolnetto1234
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Any help is very appreciated. Thanks!

**Comment by ndeloof** [comment]
you set `POSTGRES_HOST=localhost`, but when ran inside a container,  `localhost` is the container itself, not the actual host. Need to pass actual database IP or domain name. Many users run database in a container so that you can use container name as database host. If you run on Docker Desktop you also can use special host name `host.docker.internal`, see https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host

**Comment by brunolnetto** [comment]
Thanks, Mr Kookaburra

**Comment by ndeloof** [comment]
This is actually a baby chocobo :)

**Comment by brunolnetto** [comment]
Chocobo rush!
