### ISSUE TITLE
[BUG] docker-compose down functionality changed

### ISSUE THREAD

**Issue by mlasevich** [docker/compose#11884]
### Description

Not sure if this is a bug or an intentional change/breakage - but it seems that behavior of `docker-compose down` has changed drastically in a recent version (sometime after 1.17 - based on changelog, I suspect it was in 1.23)

Previously, `docker-compose down` would remove everything defined in the project, regardless of how it was started, new behavior is that you are required  to specify profiles explicitly to shut down anything. 

While I appreciate ability to shut down just one profile, we ofter rely on cleanup to shut down everything, which is harder if you have to track what was started and how. Would be nice to either restore `docker-compose down` to shut down everything unless a profile is provided, or at least offer an alternative command/flag that does full cleanup...

### Steps To Reproduce

test docker-compose.yaml

```yaml
version: "3"


services:
  no-profile:
    image: busybox
    command: [sleep, "120"]
  with-profile:
    image: busybox
    command: [sleep, "120"]
    profiles:
      - test
```

example:

```
test:~/dtools/compose-test $ docker-compose --profile test up -d
[+] Running 2/3
 ⠏ Network compose-test_default           Created                                                                                                                                                1.0s 
 ✔ Container compose-test-with-profile-1  Started                                                                                                                                                0.8s 
 ✔ Container compose-test-no-profile-1    Started                                                                                                                                                0.6s 
test:~/dtools/compose-test $ docker-compose down 
[+] Running 2/1
 ✔ Container compose-test-no-profile-1  Removed                                                                                                                                                 10.3s 
 ! Network compose-test_default         Resource is still in use                                                                                                                                 0.0s 
test:~/dtools/compose-test $ docker-compose ps
NAME                          IMAGE     COMMAND       SERVICE        CREATED          STATUS          PORTS
compose-test-with-profile-1   busybox   "sleep 120"   with-profile   32 seconds ago   Up 31 seconds   
test:~/dtools/compose-test $ 
```

### Compose Version

```Text
Docker Compose version v2.24.7
```

### Anything else?

I actually found a workaround - looks like you can do `docker-compose --profile '*' down`  - so if this is an intentional change, this should maybe be a feature request.... Maybe an additional command like `docker-compose clean` that would be an equivalent to `docker-compose --profile '*' down --rmi local --remove-orphans` :-)

**Comment by ndeloof** [comment]
When ran with a compose.yaml file (which is the case if present on same folder) `docker compose down` will shut down services as defined in compose file, which indeed means those set by a profile will be excluded. Users rely on this so they can split a large compose file into subset and manage them individually.

A simple workaround is to run `down` command with `--profile="*"` so that all profiles are enabled, or to just pass a project name so that compose will select actual resources and stop them all :

```shell
$ cat compose.yaml 
services:
  nginx-a:
    image: nginx
  nginx-b:
    image: nginx
    profiles: [ "b-profile" ]

$ docker compose --profile="*" up -d
[+] Running 3/3
 ✔ Network machin_default      Created                                                                                                                                                                            0.0s 
 ✔ Container machin-nginx-a-1  Started                                                                                                                                                                            0.3s 
 ✔ Container machin-nginx-b-1  Started  

$ docker compose -p machin down 
[+] Running 2/2
 ✔ Container machin-nginx-b-1  Removed                                                                                                                                                                            0.1s 
 ✔ Network machin_default      Removed       
```
