### ISSUE TITLE
[BUG] Changing both location and restart policies of a docker compose file leads to unexpected results

### ISSUE THREAD

**Issue by ldm-acn** [docker/compose#11886]
### Description

If a container created through docker compose with the restart `always` policy is stopped (so theat it is in a state of waiting for the docker service to restart), then the docker compose file is moved to a different location and the restart policy is modified (let's say to `unless stopped`), the container is still goin to restart at the restart of the docker service.

I'm not sure this is even a bug, more of an unexpected behaviour connected to how the restart `always` policy is implemented. Still, I guess **it might be worth discussing if some meaningful message could be conveyed to the user** in case this happens.

_Btw, if this happens to you just move the folder back to where docker expects it to be, modify the docker compose file and start and stop the containers once, then you can move everything to where you want it._

### Steps To Reproduce

1. set any `docker-compose.yml` configuration with a container having the restart policy `always`
2. (in my case the container also bound a volume to the local file system)
3. stop the container in the compose file with the `compose stop` command
4. move the folder containing the compose file and the mounting point of the volume to a different location in the file sytem
5. change the restart policy of the container to `unless-stopped`
6. restart the docker service
7. the container will restart along with the docker service and create new folders at the previous location

### Compose Version

```Text
Docker Compose version v2.27.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 6
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.146.1-microsoft-standard-WSL2
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.581GiB
 Name: C11-R3Y2PILZL3P
 ID: 1277223f-f790-4f75-afd8-7c2c4267e708
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by ndeloof** [comment]
Docker Compose is a client side component, it uses compose.yaml to create resources, but the docker engine doesn't know anything about your compose file, and any update made on it won't have any impact on containers until you run `compose up` again.

I assume by "restart the docker service" you mean you run `docker start xxxx`. This typically restart the container with the exact configuration it had when created. You can change or delete compose.yaml file, engine doesn't care - please note engine could run on a distinct machine, no way it can access your local file.

Closing issue as "work as designed"

**Comment by ndeloof** [comment]
ok, same applies here. As docker engine is restarted, container with `restart: always` policy is indeed restarted, as configured when created according to compose.yaml configuration. Changing the original compose.yaml file has no impact on the already created container, so this is the expected behavior
