### ISSUE TITLE
support env variable COMPOSE_TIMEOUT

### ISSUE THREAD

**Issue by hellodword** [docker/compose#11918]
### Description

`env COMPOSE_TIMEOUT=360 docker compose down` will be same with `docker compose down -t 360`

How do you think?

**Comment by ndeloof** [comment]
if we start doing so I can guess we will end having hundred COMPOSE_xx variables.
I'd be ok to support such a variable to set default stop timeout if `docker stop` has such a feature, otherwise I'm 👎  on this

**Comment by ndeloof** [comment]
`COMPOSE_PARALLEL_LIMIT` allows to control how compose will invoke the docker engine API with concurrent commands, not the API call payloads like passing a custom `timeout` to `ContainerStop` (timeout is managed by engine, not caller).
Please note you can configure your containers in compose.yaml to have a stop timeout lower than the default 10s, so you don't need to tweak the later calls: https://docs.docker.com/compose/compose-file/05-services/#stop_grace_period
