### ISSUE TITLE
[BUG] (v2.28.0) Fancy (ANSI) progress output not available

### ISSUE THREAD

**Issue by leo9800** [docker/compose#11928]
### Description

Docker compose commands, e.g. `docker compose up -d`, used to produce a fancy interactive output on terminals. But when compose is upgraded to v2.28.0, the fancy output disappears, left only a plain output.

A sample output (fancy, ANSI) of `docker compose up -d` from compose v2.27.3

![Screenshot from 2024-06-22 14-41-14](https://github.com/docker/compose/assets/13928879/239fa8a2-199b-47b1-b753-63e92d8db795)

A sample output (plain) of `docker compose up -d` from compose v2.28.0

![Screenshot from 2024-06-22 14-42-39](https://github.com/docker/compose/assets/13928879/51aa3953-5dd8-46d8-9a3c-6ef08b5ece6a)

### Steps To Reproduce

1. install docker
2. install docker-compose
3. run `docker compose up -d` on any stack directory\*

\*: stack directory: a directory contains a docker compose stack, i.e. a `docker-compose.yml` file at least

### Compose Version

```Text
Docker Compose version 2.28.0
```

### Docker Environment

```Text
Client:
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.15.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.28.0
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.9.5-zen1-1-zen
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.18GiB
 Name: HOSTNAME_REDACTED
 ID: UUID_REDACTED
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 198.18.0.0/15, Size: 26
```

**Comment by leo9800** [comment]
# Dive Deeper

I tried to investigate into this issue and got some progress to share ...

---------------

I noticed a parameter in `docker compose --help`

```
      --progress string            Set type of progress output (auto, tty, plain,
                                   quiet) (default "auto")
```

I gave it a try by invoking `docker compose --progress tty up -d` on a stack directory, and the output below pops up:

```
$ ~/projects/compose/bin/build/docker-compose --progress tty up -d
WARN[0000] Terminal is not a POSIX console              
WARN[0000] Terminal is not a POSIX console              
 blss Pulling 
 ec99f8b99825 Already exists 
 69ed43a81650 Already exists 
 82333a17c7c2 Already exists 
 c6bc217d680f Already exists 
 4d17a28ca59a Already exists 
 281242b060e0 Already exists 
 19ec29a3be40 Already exists 
 290fd3d444de Already exists 
 166bdd0a726d Already exists 
 fb9c96a8445e Pulling fs layer 
 e3d4b9725e24 Pulling fs layer 
[OMITTED]
```

Note that the first 2 lines of warning message `Terminal is not a POSIX console`.

I therefore `git grep 'Terminal is not a POSIX console'` on this git repo and found that the error message comes from line 133 of *pkg/progress/writer.go*

https://github.com/docker/compose/blob/6a000dcff1300e137bb52467d3934e9211a017ed/pkg/progress/writer.go#L117-L143

**Comment by leo9800** [comment]
I am not sure if this issue should be posted in this repo or https://github.com/docker/cli

**Comment by glours** [comment]
Hello @leo9800 
Thanks for catching this issue and for your deep dive investigation this is very useful 🙏 
We'll take a look 👍

**Comment by leo9800** [comment]
Thanks @glours @vvoland 

Confirm fixed. (v2.28.1)
