### ISSUE TITLE
ci pipeline failing for .net 

### ISSUE THREAD

**Issue by vigneshren** [docker/compose#11923]
### Description

We need a urgent help on CI pipeline Failure in AT stage for .Net repo , the error seems to in docker compose and there is no change in the yml file of docker , related to docker from our end .
suddenly it started to fail , upon checking we found the below error.
![image](https://github.com/docker/compose/assets/158045313/2a976b0b-d874-4994-ad2e-bc92e1f7a19b)

**Comment by glours** [comment]
The error message displayed the docker CLI help and not the Compose one, can you give us more details? 
What is the command run by your CI in this step? Which version of Docker Compose is used? What version of Docker engine are you using?

Next time, please, use the issue template as it's give us the minimal details we need to start helping you

**Comment by matiaswastaken** [comment]
We had the same problem, what seems to have fixed it was updating our docker CLI version from:

![image](https://github.com/docker/compose/assets/43342190/25184f3d-543b-44df-9374-a75e81ba1028)

to:

<img width="214" alt="image" src="https://github.com/docker/compose/assets/43342190/64937765-2478-4944-8640-394033f439c4">

However we have absolutely no idea what broke this and why because nothing changed on our side had changed, but seems that updating the docker version to latest has resolved this for us.

**Comment by ndeloof** [comment]
@vigneshren does the proposed workaround fix this issue for you ?
We have no idea how compose is ran from this CI service, better report issue to the provider

**Comment by vigneshren** [comment]
Hi @ndeloof , i am just deploying the suggested change in our template , will let you know once its completed

**Comment by vigneshren** [comment]
Hi @matiaswastaken good day!
i don't want fin the inputs field in our script whether i need to in the yaml and deploy? the same i did but for a good clarity i am asking

**Comment by matiaswastaken** [comment]
@vigneshren Hi! Not entirely sure if I understand what you're asking, but what I did was update the "Docker CLI task" to use the latest docker engine (version found from here: https://docs.docker.com/engine/release-notes/26.1/)

<img width="239" alt="image" src="https://github.com/docker/compose/assets/43342190/5125bd4f-d732-497b-b9e6-467fafae7b06">

The YAML for the Docker CLI Installer task now looks like this:
```

steps:
- task: DockerInstaller@0
  displayName: '[Install] Docker CLI'
  inputs:
    dockerVersion: 26.1.4
```

**Comment by vigneshren** [comment]
hi @matiaswastaken  , ok got it, we don't have this task in our current setup, I just added at the beginning and triggered the pipeline.

**Comment by vigneshren** [comment]
hi @ndeloof, i know the details of provider? how i can reach-out to them, can you please help!

**Comment by vigneshren** [comment]
Hi @matiaswastaken  
still its failing ! bad luck
![image](https://github.com/docker/compose/assets/158045313/87b99cc7-7ff3-482e-903c-4547e5be1116)

**Comment by ndeloof** [comment]
Better ask Microsoft support as I have no way to tell how compose is used inside this "azpipes docker compose" CI feature

**Comment by vigneshren** [comment]
Hi @glours 

The error message displayed the docker CLI help and not the Compose one, can you give us more details?
What is the command run by your CI in this step?
 **# Docker-compose up
      - task: DockerCompose@0
        displayName: 'Docker-compose up'
        inputs:
          dockerComposeFile: ${{ parameters.DOCKER_COMPOSE_PATH_AND_FILE }}
          dockerComposeCommand: 'up -d'**
 Which version of Docker Compose is used? 
 **3.8**
What version of Docker engine are you using?
**1.29.2**

**Comment by ndeloof** [comment]
@vigneshren "3.8" is not a Docker Compose version but "compose file" version (obsolete). @glours was asking about the compose _binary_  version you're running here

> What is the command run by your CI in this step?

logs demonstrate command is ran with `--compatibility` flag. What you give us is there parameter you pass to your CI component, not the command being ran. IMHO this is a CI component issue, nothing we can do here to help you. Please report issue to component authors

**Comment by vigneshren** [comment]
Hi @ndeloof  
we are using Docker Compose version v2.27.1
sorry dropped a comment wrongly.
can you pls provide that ci component group ?
thanks

**Comment by ndeloof** [comment]
> can you pls provide that ci component group ?

You don't get it. You are not using directly docker compose, but use some azpipeline integration, which is responsible to run the compose command .. which fails. As screenshot shows, this is a component maintainer by Microsoft, we can't help you here.

I'm closing this issue for lack of requested information
