### ISSUE TITLE
Is docker-compose pip package - dead?

### ISSUE THREAD

**Issue by f33r0** [docker/compose#11936]
### Description
Hello!
Latest version is: [May 10, 2021](https://pypi.org/project/docker-compose/1.29.2/)
Maybe we can update it? It is very convenient to use.

**Comment by glours** [comment]
Hello @f33r0 
Yes we replaced it by a Golang implementation started 4 years ago and the python implementation has been decommissioned a year ago
https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/
