### ISSUE TITLE
[BUG] compose up does not always reset terminal if menu is enabled

### ISSUE THREAD

**Issue by sebbASF** [docker/compose#11947]
### Description

If `docker compose up` fails to complete (e.g. because an external volume is not accessible), the terminal can remain in no-echo mode if the menu is enabled.

This does not happen if COMPOSE_MENU=0

### Steps To Reproduce

Create a compose.yaml file with an invalid entry under volumes:, e.g. /tmp (assuming that was not exposed)

```
compose.yaml:
services:
  test:
    image: test
    build: .
    volumes:
      - /tmp:/var/data
```

$ docker compose up

```
Error response from daemon: Mounts denied: 
The path /tmp is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
```

### Compose Version

```Text
$ docker-compose version
Docker Compose version v2.27.1-desktop.1
$ docker compose version
Docker Compose version v2.27.1-desktop.1
```

**Comment by ndeloof** [comment]
Already fixed by https://github.com/docker/compose/pull/11896 AFAICT

**Comment by ndeloof** [comment]
get latest from https://github.com/docker/compose/releases

**Comment by ndeloof** [comment]
ok then I'll close this issue, feel free to comment after Docker Desktop comes with v2.28.x if issue persists
