### ISSUE TITLE
[BUG] fatal error: limiterEvent.stop: found wrong event in p's limiter event slot

### ISSUE THREAD

**Issue by huhouhua** [docker/compose#11957]
### Description

Executing the docker-compose up -d command failed with a program error

- **output**

![image](https://github.com/docker/cli/assets/40319281/1b039a1f-b74f-445b-860a-6d1873bb731d)
![image](https://github.com/docker/cli/assets/40319281/3a8d18cb-4279-4870-a2ed-de841d412917)
![image](https://github.com/docker/cli/assets/40319281/b822fbde-ac1c-4fee-b23a-80f5dede63f2)
![image](https://github.com/docker/cli/assets/40319281/782c64a9-81fe-44f8-9dcf-be59ee675d2c)
![image](https://github.com/docker/cli/assets/40319281/20ce63bc-7242-418e-8c8b-c97ba11adb49)
![image](https://github.com/docker/cli/assets/40319281/ad783002-6c4a-42ea-83ca-d509d4fc120b)
![image](https://github.com/docker/cli/assets/40319281/f130fb6a-4847-4847-b39e-c581413c6ea2)
![image](https://github.com/docker/cli/assets/40319281/3111a716-b89c-4b74-864e-8ef1107c9b8e)
![image](https://github.com/docker/cli/assets/40319281/1dee90b7-84fa-4677-849d-68356f966a19)
![image](https://github.com/docker/cli/assets/40319281/dfb9840e-3c63-4afc-8f4d-bc3a43b1efe6)

### Steps To Reproduce

Executing docker-compose up -d

### Compose Version

```Text
Docker Compose version v2.18.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.0-60.139.0.166.oe2203.x86_64
 Operating System: openEuler 22.03 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.23GiB
 Name: docker
 ID: 68665325-d728-4f23-bc33-af25906bb0dc
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.1
  ::0
  0.0.0.0/0
  127.0.0.0/8
 Registry Mirrors:
  https://docker.mirrors.ustc.edu.cn/
  https://hub-mirror.c.163.com/
  https://registry.cn-shanghai.aliyuncs.com/
  https://registry.docker-cn.com/
  https://b9pmyelo.mirror.aliyuncs.com/
 Live Restore Enabled: false
```

### Anything else?

Operating system information:

- NAME="openEuler"
- VERSION="22.03 LTS"
- ID="openEuler"
- VERSION_ID="22.03"
- PRETTY_NAME="openEuler 22.03 LTS"
- ANSI_COLOR="0;31"

Architecture:
Linux docker 5.10.0-60.139.0.166.oe2203.x86_64 #1 SMP Thu May 30 05:17:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by glours** [comment]
Hello @huhouhua 
Can you please upgrade your version of Compose, the one you're using [`v2.18.1` is more than a year old](https://github.com/docker/compose/releases/tag/v2.18.1)?

**Comment by huhouhua** [comment]
> 您好，您能否升级您的 Compose 版本，您正在使用的[版本已经一年多了](https://github.com/docker/compose/releases/tag/v2.18.1)？

Please confirm whether this issue has been fixed in version **v2.18.1.**

**Comment by huhouhua** [comment]
> Hello @huhouhua Can you please upgrade your version of Compose, the one you're using [`v2.18.1` is more than a year old](https://github.com/docker/compose/releases/tag/v2.18.1)?

Please confirm whether this issue has been fixed in version **v2.18.1.**

**Comment by huhouhua** [comment]
> @huhouhua can you please test with [the latest version compose ](https://github.com/docker/compose/releases/tag/v2.28.1)? You didn't give us a reproduction example, I can't do anything on my side with only screenshots

I'll try this version first

**Comment by glours** [comment]
I close the issue, without any news since a month I assume Compose latest version fixed the problem
