### ISSUE TITLE
[BUG] Completion doesn't work for files

### ISSUE THREAD

**Issue by flohw** [docker/compose#11969]
### Description

When I use `docker compose exec <service> <command> <filename>` and want to autocomplete the `<filename>` part, the files are not listed or proposed by the CLI.

It works well when using `docker-compose exec ...`

I usually do it with a php container : `docker compose exec php php test.<tab>` which should be completed as `docker compose exec php php test.php` but nothing happen...

Note: The problem also exists with `docker compose run` or `docker compose cp`, the local paths are not completed, so the issue may be generalized.

### Steps To Reproduce

1. Having a container with a command to run which require a local file as parameter
2. Type `docker compose exec <service> <command> fi<tab>`

### Compose Version

```Text
; docker compose version
Docker Compose version 2.28.1
; docker-compose version
Docker Compose version 2.28.1
```

### Docker Environment

```Text
Client:
 Version:    27.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.15.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.28.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 13
  Running: 8
  Paused: 0
  Stopped: 5
 Images: 49
 Server Version: 27.0.2
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.36-1-lts
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.13GiB
 Name: arch-florian
 ID: XHRJ:XTYP:3YPV:XCA5:URUG:XPKO:UMGK:I4CT:4RDA:SVB2:T7P5:B5UK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

Thank you :slightly_smiling_face: 
Let me know if it should be reported to docker/cli repository.

Hopefully this is an easy fix. :crossed_fingers:

**Comment by ndeloof** [comment]
completion for a command that is executed by a docker `exec` would need to be evaluated by the shell inside the container, which would require... and exec. Better exec a shell then interact with it inside container to get a full shell experience for available commands.

Closing as "not planned"

**Comment by flohw** [comment]
I was looking for autocomplete of local files which are on the host (and mounted in the container with a volume), not in the container.

That was the behavior I had with `docker-compose` which may be the default for most people and expected by most people as with that legacy command it works like that.

I can understand that autocomplete for files inside the container is not possible.

**Comment by ndeloof** [comment]
autocompletion with local files is just the fallback for your shell autocompletion. While this makes sense for your usage, this is irrelevant in this context as the command to complete is the one ran inside container

**Comment by flohw** [comment]
So there might be an issue with how the autocomplete is defined or something with my (zsh) configuration as I have no fallback to my local files with `docker compose` while I have with `docker-compose`.

Any help for that would be appreciated.
