### ISSUE TITLE
CACert Path Issue

### ISSUE THREAD

**Issue by razic** [docker/compose#1196]
Hey.

Just downloaded the latest versions:

* `Docker version 1.5.0, build a8a31ef` (via homebrew)
* `docker-compose 1.2.0rc2` (via github)
* `machine version 0.2.0 (45f08d9)` (via github)

And I'm having weird cert path issues:

```bash
$ machine create -d virtualbox dev && $(machine env dev)
$ docker ps
FATA[0000] Couldn't read ca cert "/Users/razic/.docker/machine/machines/dev"/ca.pem: open "/Users/razic/.docker/machine/machines/dev"/ca.pem: no such file or directory
```

Some debugging:

```bash
$ machine env dev
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH="/Users/razic/.docker/machine/machines/dev"
export DOCKER_HOST=tcp://192.168.99.100:2376
```

But the weirdest part is:

```bash
$ DOCKER_CERT_PATH="/Users/razic/.docker/machine/machines/dev" docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by razic** [comment]
nevermind... just saw docker/docker#851

**Comment by aanand** [comment]
I think you mean https://github.com/docker/machine/issues/851, but yes - I got bit by the same thing when I upgraded to Machine RC!

I suggested an improvement to the UX in https://github.com/docker/machine/issues/877, and it looks like https://github.com/docker/machine/pull/882 implements it.

**Comment by razic** [comment]
yup, i meant docker/machine#851... sorry updated the comment
