### ISSUE TITLE
Feature Request: docker-compose stats

### ISSUE THREAD

**Issue by awsmsrc** [docker/compose#1197]
Is it too much cross over/out of scope to implement the stats option in compose

docker-compose stats service_name --index=n

??

**Comment by thaJeztah** [comment]
Nice idea, perhaps even `docker-compose stats` to show stats of all containers of the project.

Not sure if Docker allready supports filtering (ie, specifying a *list* of containers to get stats for). I'll check, otherwise will create a feature request upstream.

**Comment by thaJeztah** [comment]
Checked; the [stats API](https://docs.docker.com/reference/api/docker_remote_api_v1.17/#get-container-stats-based-on-resource-usage) actually is *per container*, so that should be possible, by making an API call for each container.

Would be nice though, if docker offered an endpoint to achieve that (e.g. `GET /stats?filter=....`)

**Comment by baptistedonaux** [comment]
+1

**Comment by mattes** [comment]
+1

**Comment by mclate** [comment]
+1

**Comment by junxy** [comment]
+1

**Comment by GeorgeTaveras1231** [comment]
+1

**Comment by mefernandez** [comment]
+1

**Comment by lindenle** [comment]
+1

**Comment by Rustem** [comment]
+ 1

**Comment by Dev-Crea** [comment]
+1

**Comment by igor-lemon** [comment]
+1

**Comment by Juananthon** [comment]
+1

**Comment by dmowcomber** [comment]
+1 
until thats implemented Im creating an alias to `docker stats` with the name in the format
```bash
docker stats --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.NetIO}}\t{{.BlockIO}}\t{{.PIDs}}"
```

**Comment by mcasimir** [comment]
```
docker stats $(docker ps --format={{.Names}} --filter "label=com.docker.compose.project=PROJECT-NAME")
```

**Comment by b17** [comment]
+1

**Comment by jason-rachio** [comment]
+1

**Comment by skavinvarnan** [comment]
+1

**Comment by ziedmahdi** [comment]
+1

**Comment by tochka** [comment]
+1

**Comment by amokrushin** [comment]
```
docker stats $(docker-compose ps -q)
```

**Comment by dinamic** [comment]
I see issues being closed a being duplicates of this one, but no progress seem to have been made so far.

I feel like `docker-compose stats` should essentially do this:

```
docker-compose ps -q | xargs docker stats
```

**Comment by AmirAlOmari** [comment]
Is it possible?

**Comment by alfaex** [comment]
to get only the names do docker stats instead of hashes.

NR>2 will ignore the 'NAME' and '------' lines

`docker stats $(docker-compose ps | awk 'NR>2 {print $1}')`

**Comment by AustinGilkison** [comment]
+1

**Comment by ndeloof** [comment]
For parity with docker CLI it would make sense to me we introduce a `compose stats` command.
Main issue I can see for this to actually happen, is that we would need to duplicate the [stats decode logic](https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/cli/command/container/stats_helpers.go#L53) - or ask for this one to be made public for reuse.
