### ISSUE TITLE
[BUG] service refers to undefined network

### ISSUE THREAD

**Issue by LikeAJohny** [docker/compose#11975]
### Description

MacBook Pro M2
Mac OS 14.5 (23F79)
Docker Desktop 4.32.0

After updating to Docker Desktop 4.32.0 I encountered errors due to a not updated `docker-compose` symlink. See here: https://github.com/docker/for-mac/issues/7345

I've manually linked `docker-compose` as recommended by @glours:
```
sudo ln -sf /Applications/Docker.app/Contents/Resources/cli-plugins/docker-compose /usr/local/bin/docker-compose
```

While this made `docker-compose` executable again I am now facing issues when trying to start up my Compose projects.
`service "<SERVICE_NAME>" refers to undefined network internal: invalid compose project`

A network called `internal` does not exist, indeed. But there's the one prefixed with the project name: `<PROJECT_NAME>_internal`. This is expected as all of our projects are being managed via `docker-compose -p`. This does not seem to work with the current release.

I also want to mention that we're running an in-house CLI to manage & run all of our Docker Compose based projects. This CLI still depends on `docker-compose` to be present which is why I can't just switch to using `docker compose` instead.

### Steps To Reproduce

1. Upgrade to Docker Desktop 4.32.0.
2. Manually link `docker-compose` as mentioned in the bug description.
3. Try starting any existing Docker Compose project with `docker-compose -p <PROJECT_NAME> [...] up [...]`

### Compose Version

```Text
docker compose: Docker Compose version v2.28.1-desktop.1
docker-compose: Docker Compose version v2.28.1-desktop.1
```

### Docker Environment

```Text
Client:
 Version:    27.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1-desktop.1
    Path:     /Users/jonas/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1-desktop.1
    Path:     /Users/jonas/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /Users/jonas/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.14
    Path:     /Users/jonas/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/jonas/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /Users/jonas/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/jonas/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/jonas/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jonas/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.10.0
    Path:     /Users/jonas/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 192
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.32-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 7.657GiB
 Name: docker-desktop
 ID: 59deb487-91c7-4b20-acea-628054f07a05
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/jonas/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

**Comment by glours** [comment]
Hey @LikeAJohny 
Can we have more information about your compose configuration? Is it possible to share, without disclosing any private information, your Compose files or a simple reproduction example? Is your `internal` network declared as external? ...

**Comment by LikeAJohny** [comment]
Hey @glours,
if I'd share my compose config you'd be spotting the error right away. And so did I...
I have a single project where the used networks were not prefixed with the project name while all other project configs had the prefixes set.
Adding them to the failing project makes everything run smoothly again. Sorry for stealing your time! I will close this bug.

I still question why it never failed before.

**Comment by glours** [comment]
@LikeAJohny no worries, I'm glad everything is working well 😉
