### ISSUE TITLE
[BUG] Cannot pause container - OCI runtime pause failed: unable to freeze: unknown" error_type="*errors.errorString" module=api

### ISSUE THREAD

**Issue by antaljanosbenjamin** [docker/compose#11991]
### Description

`docker container pause` failed to pause the container with the following error:

```
time="2024-07-18T07:59:54.311730065Z" level=debug msg="Calling POST /v1.42/containers/8e6b8831455b2c6f39536cdd588a50b9237985d2fc757adbb00ce841ae688631/pause"
time="2024-07-18T07:59:54.616423750Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: Cannot pause container 8e6b8831455b2c6f39536cdd588a50b9237985d2fc757adbb00ce841ae688631: OCI runtime pause failed: unable to freeze: unknown" error_type="*errors.errorString" module=api
time="2024-07-18T07:59:54.616462412Z" level=error msg="Handler for POST /v1.42/containers/8e6b8831455b2c6f39536cdd588a50b9237985d2fc757adbb00ce841ae688631/pause returned error: Cannot pause container 8e6b8831455b2c6f39536cdd588a50b9237985d2fc757adbb00ce841ae688631: OCI runtime pause failed: unable to freeze: unknown"
time="2024-07-18T07:59:54.616481981Z" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: Cannot pause container 8e6b8831455b2c6f39536cdd588a50b9237985d2fc757adbb00ce841ae688631: OCI runtime pause failed: unable to freeze: unknown" error_type="*errors.errorString" module=api
time="2024-07-18T07:59:54.711320169Z" level=debug msg="Name To resolve: rabbitmq1."
time="2024-07-18T07:59:54.711389656Z" level=debug msg="[resolver] lookup name rabbitmq1. present without IPv6 address"
time="2024-07-18T07:59:54.711322950Z" level=debug msg="Name To resolve: rabbitmq1."
time="2024-07-18T07:59:54.711459858Z" level=debug msg="[resolver] lookup for rabbitmq1.: IP [172.16.3.2]"
```

The issue happened during one of our [test run](https://s3.amazonaws.com/clickhouse-test-reports/66633/50836d8af7823b8efbbd6b497600c26fb713981f/integration_tests__aarch64__[4_6].html) where we pause the a RabbitMQ container (using `docker-compose ... pause rabbitmq1` bash command from a python script) and attempt to connect to it (which should fail, but it didn't).

I attached the docker logs from the whole test run. It is quite a bit, but I am not sure what information can be useful for you.
 
[parallel3_0_dockerd.log](https://github.com/user-attachments/files/16312243/parallel3_0_dockerd.log)

### Steps To Reproduce

I couldn't reproduce it, because it is not deterministic. It only failed 2 times in the past 6 months. However because the error is "unknown", we thought it might be useful to report it.

### Compose Version

```Text
1.29.2

It is quite old, I just noticed now. I will try to upgrade it as soon as possible.
```

**Comment by ndeloof** [comment]
This is obviously a docker engine error, please report to github.com/moby/moby

**Comment by antaljanosbenjamin** [comment]
Ahh, sorry, will do that.
