### ISSUE TITLE
[BUG] install failed

### ISSUE THREAD

**Issue by leonJiang1992** [docker/compose#12012]
### Description

![image](https://github.com/user-attachments/assets/2c2e8e7d-9ba7-4437-bc1e-1cdde9f88e9a)

**Comment by ndeloof** [comment]
Please try using a plain `docker pull <image>` to pull image and confirm you don't get a comparable error
Compose fully delegates the pull operation to docker engine, so nothing we can do here

**Comment by ndeloof** [comment]
Closing as requester didn't answered
