### ISSUE TITLE
docker-compose dry run

### ISSUE THREAD

**Issue by ghost** [docker/compose#1203]
Would like insight to what docker-compose generates/executes

**Comment by aanand** [comment]
Agreed - for the time being, you can use `docker-compose --verbose` to see what it's doing.

**Comment by paurullan** [comment]
This would be incredibly useful for debugging purposes.

**Comment by jmkgreen** [comment]
So `config` just said my file was fine yet `up` told me a service was linked to a service not described.

Does `config` need to be improved or is `dry-run` intended for this? Gut tells me the former...

**Comment by dnephin** [comment]
`config` should catch these errors, we don't currently for `links` (however we do for `depends_on`).

I created #2933

**Comment by ekristen** [comment]
+1 this would be a great feature

**Comment by atrauzzi** [comment]
Something like this would be extremely helpful in debugging situations like https://github.com/docker/compose/issues/3259.

Currently `--verbose` isn't showing me any information about volumes/bind-mounts.

**Comment by hervenicol** [comment]
I am also looking for a `dry-run` feature, that would not change anything but would explain whether it would perform any action in a normal run.

**Comment by xandreklein** [comment]
+1

**Comment by lwm** [comment]
+1

**Comment by yaanst** [comment]
+1

**Comment by dsaydon90** [comment]
+1

**Comment by mooperd** [comment]
+1

**Comment by emersonf** [comment]
Any news on this? It's been 3 years. At a minimum knowing which services are going to be restarted would allow automated notifications of downtime.

**Comment by sauraahu** [comment]
+1

**Comment by zethis** [comment]
+1

**Comment by kuroop** [comment]
+1

**Comment by dugajean** [comment]
This would be great to have.

**Comment by gniewomir** [comment]
+1

**Comment by ivanlmj** [comment]
+1

**Comment by ehrlichja** [comment]
+1

**Comment by tnwhitwell** [comment]
+1

**Comment by afonsosantos** [comment]
+1 for AzuraCast @ https://azuracast.com

**Comment by anhtuan84** [comment]
+1

**Comment by DanielBryars** [comment]
+1 --dry-run would enable diagnostics, and also provide a way to validate it's going to do what you expect before a production change.

**Comment by hinorashi** [comment]
I'm still here waiting for this dry run feature :D

**Comment by pravynandas** [comment]
+1 in 2020.

**Comment by wfehrnstrom** [comment]
+1

**Comment by biscaldis** [comment]
+1

**Comment by lweberru** [comment]
+1

**Comment by pablog12** [comment]
+1

**Comment by pallsopp** [comment]
+1
5 years later :)

**Comment by cntsw** [comment]
+1

**Comment by Victor-D** [comment]
Hello

For monitoring purpose I am looking for a command to check if images in a docker-compose file are all up-to-date. 

A docker-compose pull --dry-run would do the trick.

**Comment by ilyaevseev** [comment]
+1
It seems to be "must have" feature.

**Comment by lweberru** [comment]
+1
For a 5 years old feature request :(

**Comment by ForestJohnson** [comment]
I am using `docker-compose config --hash="servicename"`  to roll my own `docker-compose --plan up`  / `docker-compose --dry-run up`  per this users idea: https://stackoverflow.com/questions/47287745/how-to-check-if-container-is-up-to-date#answer-56165526

**Comment by MaximBobylev** [comment]
+1

**Comment by sshehata** [comment]
+1

**Comment by ForestJohnson** [comment]
Here is the code I wrote to implement docker compose dry run, for what its worth. https://git.sequentialread.com/forest/rootsystem/src/branch/master/automation/dockerCompose.go#L332

It's part of a system that generates diagrams based on a simplified model of a terraform plan, that's why there's a bunch of stuff called terraformxyz in there.

**Comment by MrDecisive** [comment]
+1

**Comment by XDavidT** [comment]
+1

**Comment by vamichael** [comment]
Make it so

**Comment by TyIsI** [comment]
Support for this feature

**Comment by absolunet-pleminh** [comment]
+1

**Comment by tsaiDavid** [comment]
Would love to see this!

**Comment by XaviTorello** [comment]
+1!

**Comment by jakapatb** [comment]
+1

**Comment by ITJamie** [comment]
+1

**Comment by MarioMarini** [comment]
+1

**Comment by laundmo** [comment]
I made a small python script which shows the services for which containers need to be restarted. This seems to be a common basic usecase, so i hope it will be helpful to anyone here.

https://gist.github.com/laundmo/9439f04ec16541a02174fc0b02a73b41

**Comment by faelin** [comment]
+1

Please roadmap this!

**Comment by ITJamie** [comment]
Please make this happen

**Comment by jwilsonimply** [comment]
+1

**Comment by meehr** [comment]
we wait now more than 7 years for this feature. Please roadmap this.

**Comment by ITJamie** [comment]
Wonder if we will make it to 10 years 😂

**Comment by pixlcrashr** [comment]
@binman-docker  When implemented?

**Comment by glours** [comment]
@pixlcrashr binman isn't part of the team in charge of Compose, and as you can see we just opened a [PR](https://github.com/docker/compose/pull/10173) to start the implementation of dry-run
As you may know Compose provides a lot of features so we will incrementally add the support for each command.
I'll soon comment this issue to explain how to use it at the beginning as it will work as an alpha feature first

**Comment by pixlcrashr** [comment]
> @pixlcrashr binman isn't part of the team in charge of Compose, and as you can see ☝️, we just opened a [PR](https://github.com/docker/compose/pull/10173) to start the implementation of dry-run
> As you may know Compose provides a lot of features so we will incrementally add the support for each command.
> I'll soon comment this issue to explain how to use it at the beginning as it will work as an alpha feature first

Good answer, thanks! :)

**Comment by ndeloof** [comment]
@naomatheus some commands indeed now support dry-run mode, you can give it a try using `alpha` command:
```
$ docker compose alpha dry-run -- rm --stop
[+] Running 2/0
 ✔ DRY-RUN MODE -  Container truc-toto-1  Stopped                          0.0s 
 ✔ DRY-RUN MODE -  Container truc-test-1  Stopped                          0.0s 
? Going to remove truc-test-1, truc-toto-1 Yes
[+] Running 2/0
 ✔ DRY-RUN MODE -  Container truc-toto-1  Removed                          0.0s 
 ✔ DRY-RUN MODE -  Container truc-test-1  Removed                          0.0s 
```

**Comment by glours** [comment]
Status of supported commands:

- [x] push
- [x] pull
- [x]  restart
- [x] exec
- [x] cp
- [x] pause
- [x] unpause
- [x] kill
- [x] stop
- [x] remove
- [x] run
- [ ] start
- [ ] build
- [ ] down
- [ ] create
- [ ] up


Not supported:
- `attach`

**Comment by glours** [comment]
We're almost there! A [PR](https://github.com/docker/compose/pull/10529) for supporting the `up` command was just opened, the last step will be to move `dry-run` alpha command to a global `--dry-run` flag
