### ISSUE TITLE
[BUG] <title>When a service stopped no dependants from other project stopped.

### ISSUE THREAD

**Issue by ska-la** [docker/compose#12059]
### Description

Project "A" has serviceA. Project "B" has serviceB, serviceC and so on. These services are dependants for serviceA and included into docker-compose.yml (projectA). When "docker container start serviceA" - OK (all dependants are started also), but "docker container stop serviceA" - serviceA stopped only. Is it right?

### Steps To Reproduce

include: ../b/docker-compose.yml
services:
  a:
    ...
    depends_on:
         - b
         - c
         - d

### Compose Version

```Text
v2.29.1
```

### Docker Environment

```Text
Client/Server Version: 27.1.1
Kernel Version: 6.6.0.14-generic
Operating System: Ubuntu 24.04 LTS
Architecture: x86_64
```

### Anything else?

On VirtualBox 7.0

**Comment by ndeloof** [comment]
> Is it right?

yes. A depends on B, but B can live without A so no reason to also stop it.
Typically, B can be a database, and A a webapp. Stopping the webapp should not stop database which can be used by some other services.
