### ISSUE TITLE
[BUG] warn   ，  the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

### ISSUE THREAD

**Issue by icetech233** [docker/compose#12068]
### Description

[BUG] warn   ，  the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

### Docker Environment

```Text
1
```

### Anything else?

1

**Comment by icetech233** [comment]
[v2.29.2](https://github.com/docker/compose/releases/tag/v2.29.2)

**Comment by armellin** [comment]
I need to use both 'docker compose' (version 26.1.3)  and the old python docker-compose (version 1.25.0).

Without "version: 3.8" in docker-compose.yaml , docker-compose fails: 
`
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services: 'cache'
`

Any chance to silence the warning in docker compose?

**Comment by ndeloof** [comment]
@armellin python docker-compose is EOL since 2022, time to forget about it.
Why do you still use it ?

**Comment by armellin** [comment]
@ndeloof I totally agree with you, it's time to forget about it. 
But it's an old legacy application, which the customer is not willing to keep maintained. There are some old scripts nobody wants to update (i.e. pay for) that use the old _docker-compose_ command.
For manual operations we use the "new" _docker compose_ for consistency, and we would like to have the same output as the new servers.
I was hoping for an env variable like `DOCKER_SUPPRESS_VERSION_WARNING=1`

**Comment by ndeloof** [comment]
@armellin Docker Compose v2 can also be used as `docker-compose` binary as a replacement for legacy compose v1.

**Comment by armellin** [comment]
@ndeloof True, but its commands have different outputs than v1, which would not be parsed correctly by the scripts, and it behaves differently inside symlinked directories.

I guess that we have to resign ourselves to living with that warning :-)

Thank you for your suggestions anyway, I appreciate that.

**Comment by jonenst** [comment]
I have been using ```version: 4.0``` to get a slightly better error message when someone by accident uses the python docker-compose:

```
$ docker-compose up
ERROR: Version "4.0" in "docker-compose.yaml" is invalid.
```

versus
```
$ docker-compose up
ERROR: The Compose file 'docker-compose.yaml' is invalid because:
services.foo.depends_on contains unsupported option: 'required'
```

I feel like my use case is even less important than @armellin's use case (and in my case as time goes by the risk of someone using the old docker-compose decreases to zero). So I'm guessing you are not going to allow me to keep this without a warning, so I'm just voicing my use case here for posterity

**Comment by ronikarjalainen** [comment]
Imo it seems pointless to warn about an obsolete attribute that will be ignored. Why not just ignore it silently? Warning about it also kind of means it is not ignored fully.

~~Even if it isn't meaningful for modern versions, it's still useful in not letting older versions of the program to try to run your newer compose scripts.~~ Scratch that, not awake enough just yet.

**Comment by ndeloof** [comment]
> it seems pointless to warn about an obsolete attribute that will be ignored

the point is users expect this `version` to change compose behavior and support for features, which is a wrong expectation since compose-spec was introduced in 2020.
