### ISSUE TITLE
docker-compose naming convention for containers

### ISSUE THREAD

**Issue by sourav82** [docker/compose#1206]
I would like to understand how docker-compose provide names to the containers.

I noticed it is in the form <present_directory_name>_<service_name>_1.

What is this 1 at last component? If the directory name (or the project name) is "test" and service name "web" (inside yml), it would be test_web_1. Is there any possibility for it to be "test_web_2" or "test_web_3" etc.?

**Comment by thaJeztah** [comment]
The `_1` is the "instance" number; docker-compose allows "scaling" services (see: https://docs.docker.com/compose/cli/#scale), which will start a `_2` container.

Hope this helps. If this answered your question, please close this issue to mark the issue "resolved", thanks!

**Comment by sourav82** [comment]
Thanks @thaJeztah !
