### ISSUE TITLE
Startup script command in dockerfile/docker-compose.yml

### ISSUE THREAD

**Issue by rubmz** [docker/compose#12066]
### Description

I have a number of dockers running in my docker-compose.yml.

For a few of them I had to add some startup/init script to be spawned after the docker successfully started and in others every time the docker restarts. And there starts the pain:
1. In some of them there is some kind of docker proprietary mechanism to start such an init script.
2. There is this very confusing CMD and ENTRYPOINT keywords that have two flaws:
     a. CMD does not run a command. This is very confusing.
     b. ENTRYPOINT can be defined, but it will then OVERRUN the existing ENTRYPOINT script of the "parent" image. 
3. There is this RUN keyword which runs stuff at build time. not after the build. 
4. You can investigate the OS of the docker that you spawn, you will then find that there may be some kind of trick to add such a startup script, but you will then find that you don't actually know if it will be ran with each docker startup. You sometimes need a one time script and other times a script that needs to run every startup. There are tricks for that too. Many tricks, like writing a file and checking if it is there.
5. When you lookup for a solution to this time burning headache you will find out that there are many Many people with the same problem, all trying to find a way to bypass this pain in the ass using tricks of the trade based on their specific docker.

**Why on earth is there still no unified simple startup script command for dockerfile? It's a real pain. It's repeating with almost every service that needs to be added to docker. Please add this or do enlighten me for a solution.**

Excuses will not be accepted. You can run the docker and spawn stuff on the OS, you can add a simple mean of starting a **startup script** for god sake this is basic! We don't need to waste our good time on such nonsense.

Thank you.

**Comment by 0-BuTaJIuK-0** [comment]
+

**Comment by ndeloof** [comment]
closing as user request relates to Dockerfile syntax (and control over the container process by ENTRYPOINT+CMD) and is unrelated to docker compose
