### ISSUE TITLE
[BUG] docker compose looking for envs when it should not

### ISSUE THREAD

**Issue by typkrft** [docker/compose#12070]
### Description

Preface: I could be missing something. 

I inject shell variables into my compose up commands with envconsul. This works as expected, but for a while I assumed that it did not because if you run a subsequent `docker compose logs` or other docker commands, they will prepend their output with a message like `WARN[0000] The "SOME_VAR" variable is not set. Defaulting to a blank string`.  This led to a confusing late night session of trying to get working environment variables to work. It was not my best moment.

Should compose be looking for variables when printing logs or bringing a project down. Can docker protect me from myself? I've also issued a bug report for myself in my head.

### Steps To Reproduce

```yaml
services:
  test:
    image: test
    environment:
      TEST: ${SOME_VAR}
```

`envconsul ... docker compose up -d` works.

```shell
> docker compose logs
WARN[0000] The "SOME_VAR" variable is not set. Defaulting to a blank string
test | some logs 
test | some more logs 
test | more logs ???
test | oh hey. here's some logs
test | did you get that thing I sent you
```

### Compose Version

```Text
Docker Compose version v2.29.1
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    27.1.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 27.1.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-23-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.823GiB
 Name: critical
 ID: 7c7037c0-1cbd-4a26-8d04-29b7a84797a3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
As long as `docker compose` is ran with a compose file (defaults to a `compose.yaml` file in current folder) it will parse and report parsing error, like a missing variable - even this isn't required by the actual command being ran. This is caused by the current architecture to first load and fully resolve compose model from file, then execute command.

As a workaround, you can run `docker compose -p <project_name>` so Compose will look for running ressources for project, and not try to parse a compose file.

**Comment by typkrft** [comment]
That's more than reasonable. Thank you for the explanation.
