### ISSUE TITLE
[BUG] Can't add argon2 hash to jupyter notebook command because of trouble with parsing $

### ISSUE THREAD

**Issue by rcepeda95** [docker/compose#12074]
### Description

I'm trying to add a password to Jupyter Notebook 7 in docker compose, but using the `jupyter_server.auth.passwd()` to generate a hash, makes an argon2 hash. Argon2 hashes have a lot of `$` and that wreaks havoc in the docker compose. Adding `$$` just makes the `docker compose config` command to show the `$$` and not just `$`. I've tried putting the hash in the `.env` file but that doesn't fix it. How should I go about adding it?
```
    jupyter notebook
      --ip 0.0.0.0
      --allow-root
      --no-browser
      --PasswordIdentityProvider.hashed_password="$argon2id$v=19$m=32768,t=16,p=2$Rfy6J41W9idBU+n/8sZc6Q$i3QYYPtoogIAw78I2qqlUQ8vjzUXGG1V6QsBOq2NIp4"
```
This was an example hash taken from https://cryptobook.nakov.com/mac-and-key-derivation/argon2

### Compose Version

```Text
Docker Compose version v2.29.1
```

**Comment by ndeloof** [comment]
`$$` is the right way. 
`docker compose config` does not remove this double dollar, as it output a valid compose file

I wonder: can't you pass this secret as a file in container? So you can declare a `secret` in compose file and don't have to worry about `$` in command line ?

**Comment by ndeloof** [comment]
closing as requested didn't provided feedback
