### ISSUE TITLE
[Docker Engine stopped] after installed,how to fix it? 

### ISSUE THREAD

**Issue by gopherhiro** [docker/compose#12077]
### Description

MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
mac OS Monterey 12.2.1
process: 2GHz  四核 Intel Core i5

### Steps To Reproduce

[Docker Engine stopped]

**Comment by gopherhiro** [comment]
Docker Desktop encountered an unexpected error and needs to close.

Search our [troubleshooting documentation⁠](https://docs.docker.com/desktop/troubleshoot/overview/?utm_source=docker_desktop_error_dialog) to find a solution or workaround. Alternatively, you can gather a diagnostics report and submit a support request or GitHub issue.

running engine: waiting for the Docker API: engine linux/hyperkit failed to run: running VM: hyperkit: process terminated unexpectedly: exit status 1

**Comment by gopherhiro** [comment]
I fixed it by: https://stackoverflow.com/questions/69552636/cannot-launch-docker-desktop-for-mac

**Comment by ndeloof** [comment]
This repo is for Docker Compose, not Docker Desktop 
see https://github.com/docker/for-mac
