### ISSUE TITLE
[BUG] What's the real reason docker can't be used in China? docker在中国不能用的真正原因到底是什么？

### ISSUE THREAD

**Issue by travisbikkle** [docker/compose#12086]
### Description

我在中国看到的消息是docker官方不允许美国列入实体清单的公司使用，但是没有一个官方发文出来。所以这个说法是真的吗？

另外ce版本的docker为什么会受到影响？开源有国界？

是docker维护人员就是不想让中国人用？如果是这样我可以接受。

还是中国公司和政府希望摆脱控制，就是希望自己弄一套全新的东西出来？

大家放开成见，说说看原因真正是什么？

What I've read in China is that docker is officially not allowed to be used by companies on the entity list, but none of the official releases have come out. So is this statement true?

Also why would the ce version of docker be affected? Does open source have national boundaries?

Is it that docker maintainers just don't want Chinese people to use it? If that's the case I can live with it.

Or are Chinese companies and governments looking to get out of control and just want to get a whole new set out on their own?

Let's all let go of our preconceived notions and tell us what the reason really is?

**Comment by Nichebiche** [comment]
That sounds right one point!

**Comment by linghengqian** [comment]
- @thaJeztah Just a question, should this kind of issue about not being able to access Docker Hub be moved to https://github.com/docker/roadmap ? Because this involves websites like Docker Hub that have little to do with the open source community.
- I proved that once the offline installation of Docker and Docker Compose is completed, there is no way to prevent users from downloading Docker Images from third-party Docker Registries. For example, https://quay.io/ and https://github.com/features/packages .

**Comment by travisbikkle** [comment]
> * https://quay.io/

如果我这个issue放错地方了，深表歉意，你们可以关闭或者挪到合适的位置。

感谢你指路。另外我自己又找到了一些方法，虽然费时间，但是目前看对于个人开发者来说 docker 的路没有堵死。

不过我还是想知道原因，是docker，gfw，还是不可调和的意识冲突 😃 。

Apologies if I've misplaced this issue, feel free to close it or move it to the right place.

Thanks for pointing me a way. I also found some work arounds, although time wasting, but so far it looks like the road is not blocked entirely for individual developers.

I'd still like to know why though.

**Comment by thaJeztah** [comment]
> @thaJeztah Just a question, should this kind of issue about not being able to access Docker Hub be moved to https://github.com/docker/roadmap ? Because this involves websites like Docker Hub that have little to do with the open source community.

Yes, this definitely doesn't belong in the compose repository; more likely for https://github.com/docker/hub-feedback or the roadmap, but there's an existing issue (more below);

- https://github.com/docker/hub-feedback/issues/2388


That said, I'm not sure if there's much that can be done; I know there's been cases where specific political regions were blocked for legal reasons (Docker being a USA company, but I'm not a lawyer) but, at least to my knowledge, Docker itself does not deny access from China. I know sometimes access has been blocked by the GFW ([Great Firewall](https://en.wikipedia.org/wiki/Great_Firewall)), and there are some (unofficial) mirrors of Docker Hub in China for that reason (I think AliCloud still has a mirror, possibly others). There's also been some incidents where DNS was involved; see https://github.com/docker/hub-feedback/issues/2402#issuecomment-2243452691 and (more details);  https://github.com/docker/hub-feedback/issues/2388

> Docker has no intention of blocking access to Docker Hub from China. We have found that many users in China have incorrect DNS records for our servers, or that they are encountering some other sort of network issue between their systems and our servers.

**Comment by Creammilky** [comment]
EVERYONE SHARE TECHNIQUES EQUALLY!! FUCK GOVERMENTS!

**Comment by UjuiUjuMandan** [comment]
See my reply here,

* https://github.com/docker/cli/issues/5373#issuecomment-2967383229

Wow, a comment was deleted. I hope that was not related to CCP censorship.
