### ISSUE TITLE
Add support for pointing to tarball contexts in the 'build' parameter.

### ISSUE THREAD

**Issue by moysesb** [docker/compose#1209]
Since the docker client used by compose (docker-py) supports receiving externally generated tarballs as a parameter for its build() method, this alternative should be available in the project configuration file. i.e.:

> service:
> 
> > build: path/to/tarball.tar.gz

The  contents within the compressed file should pass the same level of validation as the currently supported directory paths (for example, 'there must be a Dockerfile at the root inside the tar archive'). Aside from that, the general idea is that the archive is some kind of externally validated artifact, auto-generated by a continuous integration stack, so there should be no need for parsing .dockerignore. 

If this sounds like a good idea I can start working on a PR (I already have an working prototype).

**Comment by dnephin** [comment]
It seems reasonable to me that `build:` would support tarballs as well

**Comment by aanand** [comment]
Seems like this change belongs in docker-py.

**Comment by moysesb** [comment]
@aanand docker-py already has this feature implemented, the issue is that compose does not use it. As it's currently implemented, compose assumes the value of `build:` to be a directory path, the value is passed "as is" to docker-py. The feature being requested is that compose should call docker-py's build method with the right combination of arguments when the `build:` parameter points to a tarball. In services.py:
```python
def build(self, no_cache=False):
   log.info('Building %s...' % self.name)
"""
 - Here it should be determined what kind of resource self.options['build'] points to.
  - If it's a tarball, the call to self.client.build should look something like:
    build_output = self.client.build(
        fileobj=open(self.options['build'], 'rb'),
        custom_context=True,
        encoding='gzip',
        tag=self.full_name,
        stream=True,
        rm=True,
        nocache=no_cache,
    )
  - If it's a directory, use the already existing call:
"""
build_output = self.client.build(
    self.options['build'],
    tag=self.full_name,
    stream=True,
    rm=True,
    nocache=no_cache,
)
```
The point is that the actual context that docker-py transmits over to the docker daemon is a tarball, whether the caller passes a directory path, a tarball or a `Dockerfile` directly. As it is now, compose only knows how to pass a directory, so if I generate a tarball externally as part of some build process that has nothing to do with compose, I have to gratuitously decompress it and then have docker-py compress it again (in python!) before sending it to docker.

**Comment by moysesb** [comment]
@aanand It would certainly be possible to change docker-py so that it automatically detects when the context being passed is already compressed (instead of relying on the combination-of-parameters logic that it uses today). 
My grip with this approach is that it involves moving validation and conditional behavior too far down to the library level. In principle there's always value in keeping validation and detection of user intention as close as possible to "surface code" and not deep in libraries - it makes it easier both to "fail early" and to optimize for efficiency where relevant.

**Comment by aanand** [comment]
OK, I'd mistakenly believed the docker client would smartly determine whether the argument passed to it was a directory or a tarball, but it looks like they go different routes (stdin for tarball or single Dockerfile vs. argument for directory).

In that case, I think it's fine for that logic to live in Compose: we should check whether the path passed to `build` is a directory or a regular file, and in the latter case pass `fileobj=open(self.options['build'], 'rb')`, as you say.

**Comment by dreamcat4** [comment]
@aanand If build command could accept tarball as a regular arg, then it would benefit other compose tools too. When I look in the source code of `docker build` and it already has the necessary checking functions etc.

We just have to peek the input file, and check if `if archive.IsArchive(magic)` then set the variable `context` to be `context = ioutil.NopCloser(but)`. *IMHO It does not seem to be too difficult.*

Existing tarball handling (the stdin):

https://github.com/docker/docker/blob/master/api/client/build.go#L74-90

Where to add new tarball handling (as regular argument):

https://github.com/docker/docker/blob/master/api/client/build.go#L94-95

Where the `context` variable gets sent to docker daemon:

https://github.com/docker/docker/blob/master/api/client/build.go#L206-214

**Comment by dreamcat4** [comment]
Oh right… I also seem to have forgotten that compose actually doesn't use the CLI client, but directly calls the API instead. (where in the API, tarball is always sent across the same way).

**Comment by moysesb** [comment]
Would it be ok to add backports.lzma as a requirement? Python2's tarfile module doesn't support lzma compression natively. Since the docker daemon accepts xz I think compose should support it too.

**Comment by smebberson** [comment]
In two different projects, we have a custom build scripts to achieve a couple of things...

In one project we use `tar` to build a tarball (concatenating a few directories, and removing a few others) and pass this to `docker build`. In another project, we remove a directory from the context in which `docker build` is run so that we don't have to remove this directory as part of the build process (it's a `node_modules` directory), then run `docker build` and then move the directory back for development purposes. Having written that, we could use `tar` in both instances which would be better.

I was going to open a new ticket to discuss support for pre and post build scripts, so that you could alter the build directory as required before and after a build. But I thought I'd chime in here instead... having the ability to point to a tarball would suffice I suppose. The ability to run a pre-build script would be fantastic to generate the tarball, but you could get around this by a custom script that generates a tarball and then executes `docker-compose build`.

**Comment by moysesb** [comment]
@smebberson I have a working implementation of this feature in the PR referenced above.

My scenario is more or less the same as yours. We have a staging directory with a bunch of maven generated tar archives with Dockerfiles inside them. When someone finishes a project build, the archive is shipped to this staging area. New uploads are detected by an `inotify-wait` script of some contraption, which calls `docker-compose` to rebuild and restart the correspoding image.

**Comment by milesrichardson** [comment]
Please don't close

Would love to be able to do something similar to this:

```bash
tar -czf - ./srcDirOne ./srcDirTwo ./srcDirThree \
    | docker build -t acme/widget -f widget/Dockerfile -
```

**Comment by MichaelKim0407** [comment]
Is this feature getting anywhere? It looks to me that [docker-py already supports building from tar](https://docker-py.readthedocs.io/en/1.2.3/api/#build):

> If you have a tar file for the Docker build context (including a Dockerfile) already, pass a readable file-like object to fileobj and also pass custom_context=True.

**Comment by MichaelKim0407** [comment]
Relatively easy implementation (unless I'm missing something). Submitted PR.

**Comment by meeseekz** [comment]
can #7283 be merged? this would be very useful.

**Comment by milesrichardson** [comment]
Looks like a small and easy PR, can it be merged?

**Comment by bevin0708** [comment]
Looking for the same feature.
