### ISSUE TITLE
[BUG] cant get tor or nftables

### ISSUE THREAD

**Issue by blade10101** [docker/compose#12097]
### Description

 => ERROR [tor_proxy 2/4] RUN apk add --no-cache         nftables=1.0.9  10.3s
------
 > [tor_proxy 2/4] RUN apk add --no-cache         nftables=1.0.9-r2         tor=0.4.8.12-r0:
0.203 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
5.209 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
5.209 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)
10.21 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)
10.22 ERROR: unable to select packages:
10.22   nftables (no such package):
10.22     required by: world[nftables=1.0.9-r2]
10.22   tor (no such package):
10.22     required by: world[tor=0.4.8.12-r0]
------
failed to solve: process "/bin/sh -c apk add --no-cache         nftables=$NFTABLES_PACKAGE_VERSION         tor=$TOR_PACKAGE_VERSION" did not complete successfully: exit code: 2

### Steps To Reproduce

docker-compose up

### Compose Version

```Text
docker compose version
Docker Compose version v2.29.2
docker-compose version
Docker Compose version v2.28.1
```

### Docker Environment

```Text
docker info
Client: Docker Engine - Community
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 16
  Running: 15
  Paused: 0
  Stopped: 1
 Images: 55
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-41-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 188.8GiB
 Name: d420
 ID: 533be926-7f9f-4f1a-85a8-65a38c0e713f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
does a plain `docker build` succeed to build your Dockerfile ?

**Comment by ndeloof** [comment]
Closing as user didn't provided requested feedback.
Please open a new issue with a reproduction example if the issue persists.
