### ISSUE TITLE
Request: Make -d --no-recreate the default behavior on `up`

### ISSUE THREAD

**Issue by iMerica** [docker/compose#1210]
Hey guys!

I think the current default behavior works fine for small applications that might have one runtime and one database, but as these environments continue to grow (because docker makes it easy to grow) both A) aggregating the stdout of all containers and B) recreating all on `fig up` (or `docker compose up`) seems almost never useful. 

For example, my environment has more than 15-30 redis containers, rabbit MQ, lua, node, nginx, elastic search, postgres, dynamo etc. In most cases, the commands I need are:

(fig or docker compose)
- `fig up -d` to bootstrap the entire environment.
- `fig stop <container>` to make some changes and and see the difference.
- `fig up -d --no-recreate` to start the container and set up port forwarding to the host OS/boot2Docker.

It could also be that I'm in the minority for the number of running containers my local dev contains :smiley_cat:. If that's the case I understand the current defaults.

**Comment by dnephin** [comment]
This sounds pretty similar to #741

**Comment by dnephin** [comment]
#1754 was merged (will be in 1.5.0) which handles the `-d` case.

Part of the 1.4.0 release was also to make `--smart-recreate` the default, which means that containers are only re-created if they have changed.  

I think we're pretty happy with this behaviour and I don't see us changing the defaults at this time.

Thanks for the ideas! I hope our new setup works well enough for you, and that adding `-d` in the case where you have many images isn't too much of a bother (I know I do that myself for basically every `up` I run!)
