### ISSUE TITLE
[BUG] (maybe) missing "[container] exited with code [code]" messages during attach

### ISSUE THREAD

**Issue by laurazard** [docker/compose#12111]
### Description

I'm not sure whether this is intended, but there was a behavior change introduced in ea4ccf639de34987fa7cfac01f991a37e04dd8fa where I no longer see the `[container] exited with code [code]` every time the container restarts. Instead, I only see it once, for the first time:

### Steps To Reproduce

With this Dockerfile:
```Dockerfile
FROM alpine:latest AS occupied

CMD ["sleep", "3600"]

FROM alpine:latest AS surplus

CMD ["sleep", "10"]
```

And the following Compose file:
```yaml
services:
  occupied:
    image: container-used:latest
  
  surplus:
    restart: unless-stopped
    image: container-surplus:latest
```

Run `docker compose up --scale occupied=8 --scale surplus=2`.

Pre ea4ccf639de34987fa7cfac01f991a37e04dd8fa I see:
```console
[...]
Attaching to occupied-1, occupied-2, occupied-3, occupied-4, occupied-5, occupied-6, occupied-7, occupied-8, surplus-1, surplus-2
surplus-1 exited with code 0
surplus-2 exited with code 0
surplus-1 exited with code 0
surplus-2 exited with code 0
surplus-1 exited with code 0
surplus-2 exited with code 0
[...]
```

But afterwards, I only see the first `...exited with code...` message for each container, and never again:
```console
Attaching to occupied-1, occupied-2, occupied-3, occupied-4, occupied-5, occupied-6, occupied-7, occupied-8, surplus-1, surplus-2
surplus-2 exited with code 0
surplus-1 exited with code 0
[nothing else]
```

### Compose Version

```Text
-
```

### Docker Environment

```Text
-
```

**Comment by jhrotko** [comment]
@laurazard I cannot reproduce this with the latest version of compose
