### ISSUE TITLE
How to parse multiple values for a particular environment key 

### ISSUE THREAD

**Issue by tomav** [docker/compose#1211]
Hi guys,

Example of a part of my `docker-compose.yml`:

	environment:
  	  my_var:
	  - "foo"
	  - "bar"

When I `echo $my_var` I have `['foo', 'bar']`
Is that a bash array?

I can't find the best way to parse this result using bash.
Any input?

Thanks!

**Comment by envygeeks** [comment]
No, a Bash array is

```sh
hello=(world you)
echo ${hello[1]}
```

Since it's not normally save to eval just do this:

```yml
environment:
  my_var: "foo bar"
```

And then in your Bash script:

```sh
read -a my_var <<< "${my_var}"
echo ${my_var[0]}
```

**Comment by itsravinder** [comment]
+kind/question

**Comment by tomav** [comment]
@envygeeks: yes, it's the workaround I use, but this does not provide a clear information about how to do when values are listed as separate entries.

@itsravinder: Yep. And perhaps documentation improvement.

**Comment by aanand** [comment]
It shouldn't be possible to specify environment variables as a list - this therefore falls under #129.

**Comment by dnephin** [comment]
I don't this the new validation is handling this case yet. This will validate as an "object" and pass validation. We need to be more strict about the structure of the object.

**Comment by dnephin** [comment]
This is fixed in 1.5.0. We now validate that an object only has scalar keys for values.

**Comment by tomav** [comment]
Thank you.

**Comment by envygeeks** [comment]
:heart:
