### ISSUE TITLE
[BUG] unexpected character "-" in variable name since v2.29.3

### ISSUE THREAD

**Issue by bwaldvogel** [docker/compose#12123]
### Description

Environment variables defined via an env_file that have "-" characters in their name get refused after updating docker-compose from `v2.29.2` to `v2.29.3`

### Steps To Reproduce

```yaml
services:
  env_runner:
    image: alpine
    command: env
    env_file:
      - ./myenv.env
```

`myenv.env`
```properties
foo-bar=test
```

## Expected behaviour (`v2.29.2`)
```
$ docker compose up
[+] Running 1/1
 ✔ Container env_runner-1      Created
Attaching to env_runner-1
[…]
env_runner-1  | foo-bar=test
env_runner-1 exited with code 0
```

## Actual behaviour (`v2.29.3`)

```
$ docker compose up
failed to read myenv.env: line 1: unexpected character "-" in variable name "foo-bar=test"
```

### Compose Version

```Text
Docker Compose version 2.29.3
```

### Docker Environment

```Text
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.23.0
 Git commit:        3ab4256958
 Built:             Thu Aug 29 16:44:26 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.23.0
  Git commit:       3ab5c7d003
  Built:            Thu Aug 29 16:44:26 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c.m
 runc:
  Version:          1.1.14
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by thaJeztah** [comment]
While _technically_ Linux can use env-vars with hyphens as name (any character except `nul` terminators), it's generally recommended to only use characters from the portable character set; https://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html

<img width="1320" alt="Screenshot 2024-09-13 at 14 27 14" src="https://github.com/user-attachments/assets/425f7a94-4647-431b-8123-da5816575771">



What I suspect happened here is that the libary used by compose possibly considers them as invalid formatted substitution character, and the part after the hyphen as `default`; https://tldp.org/LDP/abs/html/parameter-substitution.html

<img width="1260" alt="Screenshot 2024-09-13 at 14 24 52" src="https://github.com/user-attachments/assets/257597dc-952b-41dc-88fe-f22e76b7de17">

That said, `env_file` for services _should_ follow the same rules as `--env-file` on `docker run` (which only considers `=` as separator, and performs no substitution/validation otherwise 🤔

**Comment by thaJeztah** [comment]
This looks related to this PR;

- https://github.com/compose-spec/compose-go/pull/680

However the `env_file` (`docker run --env-file`) should not do interpolation; is there a way to make that conditional, @ndeloof ?

```bash
docker run --rm --env "hello-world=hello-value" alpine printenv hello-world
hello-value
```

**Comment by ndeloof** [comment]
env-file when used in compose **does** support interpolation.

**Comment by thaJeztah** [comment]
Right, but the reverse also looks to be true; it's rejecting env-vars that should be considered valid 🤔

**Comment by ndeloof** [comment]
> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in [Portable Character Set](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap06.html#tagtcjh_3) and do not begin with a digit. Other characters may be permitted by an implementation;

So `-` _MAY_ be permitted, and I can guess some will rely on it. To get actual support of this, we will have to make the dotenv parser way more flexible that it is 😓

**Comment by thaJeztah** [comment]
Yeah, I recall we once added validation for environment-variables, but then had to revert, for similar reasons;

- https://github.com/moby/moby/pull/16608

**Comment by bwaldvogel** [comment]
When will the fix be published? I’ve tested docker compose `v2.29.7` and I still get the same error.

**Comment by bwaldvogel** [comment]
It seems to work now with docker compose `v2.29.7`. Not sure which other library update did the trick?

**Comment by ndeloof** [comment]
fix took place in compose-go library

**Comment by jamessan85** [comment]
I'm still facing this issue, compose version is 2.29.7, is there something else I should update?

**Comment by ndeloof** [comment]
character `-` is **not** supported in variable names, as this collides with default value syntax (`${FOO-default_value}`) and makes parsing non-deterministic

**Comment by jamessan85** [comment]
I'm confused, I thought earlier comments said this was fixed, it's been working before the update.

**Comment by ndeloof** [comment]
yes, we tried to propose a fix for this issue, but this triggered more issues as variables with a `-` in name can't be used: they get parsed as `name-default` and there's no possible workaround.

**Comment by ndeloof** [comment]
see https://github.com/compose-spec/compose-go/issues/663

**Comment by eschrewe** [comment]
For those affected by this issue:  

A possible workaround is to remove the respective variables from the .env file and instead apply them via the "environment"

```
services:
  env_runner:
    image: alpine
    command: env
    environment: 
      foo-bar: test
    env_file:
      - ./myenv.env
```

**Comment by masatana** [comment]
Is it correct to say that it was fixed by #683 (released in v2.30.0)?

**Comment by achinaou** [comment]
I just upgraded to Docker Compose 2.31.0, and it works.

**Comment by jakeaturner** [comment]
Can confirm upgrading Docker Compose solves this. (docker-compose-plugin 2.32.1-1~ubuntu.24.04~noble)
