### ISSUE TITLE
[BUG] Compose v2.29.3 breaks bind-mounts on in WSL2 using Docker Desktop "mounted on / but it is not a shared mount"

### ISSUE THREAD

**Issue by rfay** [docker/compose#12129]
### Description

We tried upgrading DDEV's use of docker-compose to v2.29.3, and it worked everywhere except in WSL2 using Docker Desktop (v4.34.2).

There it gets fundamental failures like
> Error response from daemon: path /var/lib/buildkite-agent/tmp/ddevtest/TestGetLocalHTTPResponse2320491494/.ddev is mounted on / but it is not a shared mount.'

Sometimes it complains about a different mount

I don't even know why "shared mount" is a thing on WSL2 Docker Desktop. Isn't that a macOS-only thing? I thought this was probably a DD problem but reverting docker-compose to v2.29.1 fixed it, so I assume it might have to do with the new mount api-first approach in v2.29.3?

### Steps To Reproduce

This shows up easily in DDEV's tests, see the complaint in https://github.com/ddev/ddev/pull/6545 - but the failed mount may sometimes be different

### Compose Version

```Text
v2.29.3
```

### Docker Environment

```Text
DD v4.34.2, Docker Desktop, WSL2
```

### Anything else?

Thanks for maintaining! We haven't had breakage in quite a while.

I tested with compose v2.29.4 and saw the same failure.

**Comment by glours** [comment]
Should have been fixed by https://github.com/docker/compose/releases/tag/v2.29.5

**Comment by rfay** [comment]
Thanks and congratulations, seems to be sorted:
* https://github.com/ddev/ddev/pull/6548

Sure appreciate the quick response!
