### ISSUE TITLE
Is the PyYAML requirement <6 on a modern system (OS: Ubuntu 24.04 noble) creating an impossible set of conditions? 

### ISSUE THREAD

**Issue by tlh45342** [docker/compose#12147]
### Description

For: OS: Ubuntu 24.04 noble

Collecting docker-compose
Downloading docker_compose-1.29.2-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting PyYAML<6,>=3.10 (from docker-compose)
Using cached PyYAML-5.4.1.tar.gz (175 kB)

There isn't a precompiled version of PyYAML for python. 3.12 for something that old (duh) so the system takes to downloading the actual source. Also because there is such a difference in age etc... it doesn't look like the modern system can successfully install from source something that old.

File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])

I don't think I am imagining this? Is this solvable?

### Compose Version

```Text
docker_compose-1.29.2-py2.py3-none-any.whl
```

**Comment by ndeloof** [comment]
docker-compose 1.x (python) is EoL and should not be used. We don't maintain it anymore
Please migrate to Docker Compose v2

**Comment by cataggar** [comment]
https://docs.docker.com/compose/releases/migrate/
