### ISSUE TITLE
[BUG] --env-file with absolute path ignores part of the path

### ISSUE THREAD

**Issue by SarenT** [docker/compose#12173]
### Description

When I try to provide a specific env file with 
`$ docker compose --env-file /path/to/project/apps/server/.db.build.production.env config`
I get the following error:
`env file /path/to/project/.db.build.production.env not found: stat /path/to/project/.db.build.production.env: no such file or directory`

the part of the path `apps/server/`  is completely ignored. I am using absolute path because of this issue:  #8076 
When I duplicate (`apps/server/apps/server/`) the error does not ignore any part of the path:
`env file /path/to/project/apps/server/apps/server/.db.build.production.env not found: stat /path/to/project/apps/server/apps/server/.db.build.production.env: no such file or directory`

Here is my folder structure:
```
.
├── apps
│   ├── server
│   │   ├── .db.build.production.env
│   │   ├── Dockerfile
├── .db.build.production.env
├── docker-compose.yml
```

Referencing the file in the root works fine, but I would rather move it to the apps/server/ directory.
`$ docker compose --env-file .db.build.production.env config`

### Compose Version

```Text
Docker Compose version 2.24.6+ds1-0ubuntu1~22.04.1
```

**Comment by bncmajor** [comment]
@jhrotko this seems to be abandoned by the OP, but I have also give it a try and with the latest (Docker Compose version v2.29.7) it worked perfectly fine with the parameters given by OP.

I'd guess this can be closed imo

**Comment by SarenT** [comment]
My apologies for not replying earlier. I was not keen on downloading binaries and run them on my system. It would also take some effort to put together a test environment. If the current version works, then it should be fine. I will bookmark this issue after it is closed to give it a try in the future with a more recent version to find out what may went wrong.
