### ISSUE TITLE
Support `network_mode: container:[container-name]`

### ISSUE THREAD

**Issue by chirino** [docker/compose#12185]
### Description

Would be nice if there was a way to get something similar to:
`network_mode: service:[service-name]`
But to which work with containers defined externally (similar to how you can have external networks):
`network_mode: container:[container-name]`

**Comment by ndeloof** [comment]
You already can !

**Comment by chirino** [comment]
Would be nice if it was documented at https://docs.docker.com/reference/compose-file/services/#network_mode
