### ISSUE TITLE
'docker-compose up' stops showing logs after 'docker-compose restart xxx'

### ISSUE THREAD

**Issue by aleksandr-vin** [docker/compose#1219]
When you run 'docker-compose up' in terminal A, there is a 'followed' logs from all of them. Then, you call 'docker-compose restart xxx' in termnal B and see the 'xxx_1'-shutdown logs in terminal A. Then there is a couple logs of the 'xxx_1'-startup in terminal A and then nothing else added. You can call 'docker-compose logs xxx' in terminal C and will see the missed logs there.

**Comment by dnephin** [comment]
Thanks for the bug report

This issue is basically the same problem as #1115 we don't track new containers.  I'm going to close this issue and track the fix in #1115
