### ISSUE TITLE
when service fails, abort and show stderr/stdout

### ISSUE THREAD

**Issue by kvz** [docker/compose#122]
If one of my services can't execute their `command:`, the only error I get is from a depending service saying it `Cannot link to a non running container`. Example:

```bash
$ fig up
Recreating syzygy_sabnzbd_1...
Recreating syzygy_sickbeard_1...
Attaching to syzygy_sabnzbd_1, syzygy_sickbeard_1
start: Cannot start container 156b95ed57fddf8c4a504d63d07b6a2e0281c09f765a066f64da7fee99731b2e: Cannot link to a non running container: /syzygy_sabnzbd_1 AS /syzygy_sickbeard_1/sabnzbd_1
```

I think it would be very helpful while still setting up a cluster if the first service whose `fig.yml`'s `command:` exits with something non-zero, would fail hard & fast, and preferably showing it's stderr.

**Comment by dnephin** [comment]
This should be fixed in recent versions.  We've addressed some race conditions that would have prevented logs from showing, and we now wait for all containers to exit before shutting down.
