### ISSUE TITLE
[BUG] A zombie-process left when docker-compose down command

### ISSUE THREAD

**Issue by dohyunKim12** [docker/compose#12205]
### Description

A zombie-process left when using docker-compose down command. Must be cleaned up neatly when container removed.
Other process can't occupate the port by un removed zombie process

### Compose Version

1.27.4

**Comment by ndeloof** [comment]
Please let us know compose version you're using

**Comment by glours** [comment]
Hello @dohyunKim12 

Can you provide us a reproducible example please? We won't we be able to merge PR https://github.com/docker/compose/pull/12206 if we aren't able t reproduce the issue

**Comment by ndeloof** [comment]
Please also attach as much details you can about zombie process to better understand what wrong here.

**Comment by ndeloof** [comment]
closing as requested information were not provided and not a compose issue
