### ISSUE TITLE
Docker Compose v2.29.7  'unexpected character "-" in variable name' when passing .env

### ISSUE THREAD

**Issue by daraccrafter** [docker/compose#12216]
When passing .env file (in which a variable name contains '-') to the " env_file:" (in compose.yml)  the above error occurs. This works normally on v2.24.5

**Comment by jhrotko** [comment]
@daraccrafter could you give more details on how to reproduce your issue? Such as a compose.yml, how you ran the command and compose version?

**Comment by jhrotko** [comment]
@426Mopar @daraccrafter this issue has been addressed in [#12123](https://github.com/docker/compose/issues/12123). In the next release this should be fixed! I will close this issue has duplicated
