### ISSUE TITLE
[BUG] Docker claims I don't have enough space.

### ISSUE THREAD

**Issue by Welved** [docker/compose#12222]
### Description

Man... I really shouldn't have wiped my Pi4 and started up fresh. Docker claims I don't have enough space, in a 2TB SSD. I have my containers saved and running off of a 2TB SSD.

To attempt to resolve this issue, I completely wiped that SSD and even tried to restart the docker service on my Pi4. Neither of those ill fated solutions worked.

How I installed docker:
**sudo curl -sSL https://get.docker.com | sh
sudo usermod -aG docker pi**

### Steps To Reproduce

1. Attempt at installing linuxserver/nextcloud
2. Get met with this at the second to last container pull: **docker: failed to register layer: write /usr/lib/php83/modules/pdo.so: no space left on device.**

### Compose Version

docker compose version: v2.29.7
docker-compose version: -bash: docker-compose: command not found

### Docker Environment

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.51+rpt-rpi-v8
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.627GiB
 Name: raspberrypi
 ID: 5d0f3b5c-9124-4fb0-b97e-c54b31738c0a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

### Anything else?

The only other container that I have installed is portainer, that has no issues at all. What is going on?

**Comment by jhrotko** [comment]
Hey, @Welved! 

I am not sure what is going on on your side, so let's start from the beggining :) Did you try to follow the recommended way to install Docker on linux from the [documentation](https://docs.docker.com/desktop/install/linux/)?

**Comment by ndeloof** [comment]
Doesn't seem to me this is a Docker Compose issue, but a general docker installation one. Can you run equivalent container with a plain `docker run ...` while using `docker compose up` fails ?

**Comment by Welved** [comment]
It was a issue of... not having enough space in the MicroSD card, even though I had ample space on my SSD. Is there a way to have docker write EVERYTHING container related to my SSD, instead of the microSD?

**Comment by ndeloof** [comment]
see https://docs.docker.com/engine/daemon/#daemon-data-directory

**Comment by Welved** [comment]
> see https://docs.docker.com/engine/daemon/#daemon-data-directory

Yes, thank you. I can now write everything related to my containers onto my SSD. Now there is a issue with my nextcloud, I am unable to login.

I am able to setup nextcloud as normal, I went ahead and created my admin account and all that. It successfully writes data to my SSD, but I am unable to login. After I click to enter my credentials and hit the login button, it doesn't let me turn over to the actual admin portal. I am stuck on the login page.

**Comment by Welved** [comment]
> > see https://docs.docker.com/engine/daemon/#daemon-data-directory
> 
> Yes, thank you. I can now write everything related to my containers onto my SSD. Now there is a issue with my nextcloud, I am unable to login.
> 
> I am able to setup nextcloud as normal, I went ahead and created my admin account and all that.
> 
> It successfully writes data to my SSD, but I am unable to login. After I click to enter my credentials and hit the login button, it doesn't let me turn over to the actual admin portal. I am stuck on the login page.
> 
> Edit: I don't know if this will help, here is the logs from my nextcloud container:
> 
> Initializing nextcloud 30.0.1.2 (this can take a while) ...
> 
> Setting permissions
> 
> New nextcloud instance
> 
> Please run the web-based installer on first connect!
> 
> Initializing finished
> 
> After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
> 
> Alternatively, you can apply your own configurations by editing /config/www/nextcloud/config/config.php following the documentation:
> 
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
> 
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
> 
> [custom-init] No custom files found, skipping...
> 
> [ls.io-init] done.
> 
> {"reqId":"03QVdF69hQakK0oF6JBv","level":3,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"POST","url":"/login","message":"session_start(): open(/tmp/sess_kq5i6fucpic8nob03e01h3jprr, O_RDWR) failed: Permission denied (13) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"03QVdF69hQakK0oF6JBv","level":3,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"POST","url":"/login","message":"session_start(): Failed to read session data: files (path: ) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"03QVdF69hQakK0oF6JBv","level":2,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"no app in context","method":"POST","url":"/login","message":"Temporary directory /tmp is not present or writable","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":[]} {"reqId":"03QVdF69hQakK0oF6JBv","level":3,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"POST","url":"/login","message":"session_start(): open(/tmp/sess_kq5i6fucpic8nob03e01h3jprr, O_RDWR) failed: Permission denied (13) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"03QVdF69hQakK0oF6JBv","level":3,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"POST","url":"/login","message":"session_start(): Failed to read session data: files (path: ) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"03QVdF69hQakK0oF6JBv","level":3,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"POST","url":"/login","message":"session_start(): open(/tmp/sess_kq5i6fucpic8nob03e01h3jprr, O_RDWR) failed: Permission denied (13) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"03QVdF69hQakK0oF6JBv","level":3,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"POST","url":"/login","message":"session_start(): Failed to read session data: files (path: ) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"IC1Xkn5xOHZY6AY2DmlA","level":3,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"GET","url":"/login?user=VWLUGNVBRTCHWLPTUVVQTLZOTBVEMPQW&direct=1","message":"session_start(): open(/tmp/sess_kq5i6fucpic8nob03e01h3jprr, O_RDWR) failed: Permission denied (13) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"IC1Xkn5xOHZY6AY2DmlA","level":3,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"GET","url":"/login?user=VWLUGNVBRTCHWLPTUVVQTLZOTBVEMPQW&direct=1","message":"session_start(): Failed to read session data: files (path: ) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"IC1Xkn5xOHZY6AY2DmlA","level":2,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"no app in context","method":"GET","url":"/login?user=VWLUGNVBRTCHWLPTUVVQTLZOTBVEMPQW&direct=1","message":"Temporary directory /tmp is not present or writable","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":[]} {"reqId":"IC1Xkn5xOHZY6AY2DmlA","level":3,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"GET","url":"/login?user=VWLUGNVBRTCHWLPTUVVQTLZOTBVEMPQW&direct=1","message":"session_start(): open(/tmp/sess_kq5i6fucpic8nob03e01h3jprr, O_RDWR) failed: Permission denied (13) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"IC1Xkn5xOHZY6AY2DmlA","level":3,"time":"2024-10-22T05:05:12+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"GET","url":"/login?user=VWLUGNVBRTCHWLPTUVVQTLZOTBVEMPQW&direct=1","message":"session_start(): Failed to read session data: files (path: ) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"IC1Xkn5xOHZY6AY2DmlA","level":3,"time":"2024-10-22T05:05:13+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"GET","url":"/login?user=VWLUGNVBRTCHWLPTUVVQTLZOTBVEMPQW&direct=1","message":"session_start(): open(/tmp/sess_kq5i6fucpic8nob03e01h3jprr, O_RDWR) failed: Permission denied (13) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}} {"reqId":"IC1Xkn5xOHZY6AY2DmlA","level":3,"time":"2024-10-22T05:05:13+00:00","remoteAddr":"192.168.8.121","user":"--","app":"PHP","method":"GET","url":"/login?user=VWLUGNVBRTCHWLPTUVVQTLZOTBVEMPQW&direct=1","message":"session_start(): Failed to read session data: files (path: ) at /app/www/public/lib/private/Session/Internal.php#198","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"30.0.1.2","data":{"app":"PHP"}}



Ok, solved it. It was a directory permission issue.

**Comment by Welved** [comment]
> see https://docs.docker.com/engine/daemon/#daemon-data-directory

This actually fixed the directory duplication issue I was having. Talk about two birds with one stone :P
