### ISSUE TITLE
[BUG] Docker network id changes after device restart

### ISSUE THREAD

**Issue by TheExample67** [docker/compose#12227]
### Description

Every time I restart my Laptop the docker networks get a new Id.
The result is that my Development Container is no longer able to start up.
This issue startet with after I updated Docker Desktop to 4.x

Is there any way to switch the existing container to the new network id?, 
I'd like to be able to restart my laptop without having to recreate the whole container. 

### Steps To Reproduce

1. In this environment...
Windows 11, Docker Desktop 4.33.1
3. With this config...
I'm running a Business Central Container using BCContainerHelper
6. See error...
	"State": {
		"Status": "exited",
		"Running": false,
		"Paused": false,
		"Restarting": false,
		"OOMKilled": false,
		"Dead": false,
		"Pid": 0,
		"ExitCode": 3221225786,
		"Error": "could not find a network matching network mode 8be2f66ffc25391d4076d428cd5eb7f3a5c28aad64d699d52e9ab276e7e15e07: network 8be2f66ffc25391d4076d428cd5eb7f3a5c28aad64d699d52e9ab276e7e15e07 not found",
		"StartedAt": "2024-10-17T12:14:07.8792415Z",
		"FinishedAt": "2024-10-17T17:15:03.0581912+02:00",
		"Health": {
			"Status": "unhealthy",
			"FailingStreak": 333,
			"Log": [
				{
					"Start": "2024-10-17T17:12:35.7468939+02:00",
					"End": "2024-10-17T17:12:38.2085681+02:00",
					"ExitCode": 1,
					"Output": ""
				},

**Comment by glours** [comment]
Hello @TheExample67 
Can you give us more details as asked by the issue template, like your compose version? Can you also share with us the Compose file your using, without sensitive data please?

**Comment by ndeloof** [comment]
IIUC you have `network_mode:  <ID>` in your compose.yaml file ?
Can't you use network name, which is stable ?

**Comment by KristofKlein** [comment]
I think it is the same as: https://github.com/docker/compose/issues/11524

**Comment by ndeloof** [comment]
Closing as a duplicate for https://github.com/docker/compose/issues/11524
