### ISSUE TITLE
[BUG] 256 checksum of docker-compose-windows-x86_64.exe mistach

### ISSUE THREAD

**Issue by Jasonlhy** [docker/compose#12230]
### Description

The checksum.txt state

```
a87a6464ef717ff193ac01211f0de8893866e53c01ef7514f2f9fc54addd2abd *docker-compose-windows-x86_64.exe
```

But I run the checksum on the computer, the result is `E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855` which mistach the checksum.txt value

### Steps To Reproduce

1. Using windows machine, download the exe from https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-windows-x86_64.exe
2. Run command: `Get-FileHash -Algorithm SHA256 "docker-compose-windows-x86_64.exe"`
3. See result 

```powershell
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855       
```

Steps on Linux

```
@Jasonlhy ➜ /workspaces/codespaces-blank $ curl "https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-windows-x86_64.exe" -o docker-compose.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
@Jasonlhy ➜ /workspaces/codespaces-blank $ sha256sum docker-compose.exe
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  docker-compose.exe
```

### Compose Version

v2.29.7

**Comment by ndeloof** [comment]
I just tested downloaded binary, and checksum is ok:
```
sha256sum docker-compose-windows-x86_64.exe 
a87a6464ef717ff193ac01211f0de8893866e53c01ef7514f2f9fc54addd2abd  docker-compose-windows-x86_64.exe
```

Please test the binary you downloaded using https://emn178.github.io/online-tools/sha256_checksum.html

**Comment by VLEU** [comment]
The value you are looking at is the hash value for an empty file (E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855). Did your exe file fully download?

The .exe has the correct hash of a87a6464ef717ff193ac01211f0de8893866e53c01ef7514f2f9fc54addd2abd, just checked this myself.

**Comment by ndeloof** [comment]
Closing as PEBKAC 😄
