### ISSUE TITLE
[BUG] When the specified `platform` isn't available, there is no error and no warning, and the build is run with the wrong platform

### ISSUE THREAD

**Issue by ell1e** [docker/compose#12241]
### Description

When the specified `platform` isn't available, there doesn't seem to be any error or warning, and the build is just run with the wrong platform. It should probably fail and report an error instead. This can be easily tested with a `docker-compose.yml` like this:
```
version: '2.4'

services:
  build-x64:
    platform: mynonsensearch
    build:
      context: ./
      dockerfile: Dockerfile.mynonsensearch
```
I tested this with docker-compose v2.29.7 on postmarketOS.

### Steps To Reproduce

1. Use above `docker-compose.yml` combined with any arbitrary dockerfile as `Dockerfile.mynonsensearch`
2. Run `docker-compose up`. The expected result is an error, since the given `platform` doesn't exist.

### Compose Version

Docker Compose version v2.29.7

### Docker Environment

Client:
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 57f17b0a6295a39009d861b89e3b3b87b005ca27
 runc version: bc20cb4497af9af01bea4a8044f1678ffca2745c
 init version: 
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.5-1-edge
 Operating System: postmarketOS edge
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 20.46GiB
 Name: <redacted>
 ID: <redacted>
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by idsulik** [comment]
Couldn't reproduce it on `Docker Compose version v2.29.2-desktop.2`

```
docker compose up

[+] Building 0.0s (0/0)                                                                                                                                                                                         docker:desktop-linux
"mynonsensearch": unknown operating system or architecture: invalid argument
```

**Comment by jhrotko** [comment]
Hello @ell1e ,

Running your confirguration on my machine I get the error during the build
```
[+] Building 0.0s (0/0)                                                                        docker:desktop-linux
"mynonsensearch": unknown operating system or architecture: invalid argument                                 exit:1 
```

on compose side, we set the build platform as the service platform when there are no platforms defined in build
https://github.com/docker/compose/blob/51ebeb544119f03ea0701e8f9f7b041bbc3c524f/cmd/compose/options.go#L48-L52

I believe you should report this issue to [buildx](https://github.com/docker/buildx/issues) team.
