### ISSUE TITLE
[BUG] `docker compose up foo` does not bring up other services within the same profile

### ISSUE THREAD

**Issue by zwimer** [docker/compose#12244]
### Description

I am moving this bug https://github.com/docker/docs/issues/21258 from the `docs` repo to the `compose` repo. According to https://docs.docker.com/compose/how-tos/profiles/
> When a service with assigned profiles is explicitly targeted on the command line its profiles are started automatically so you don't need to start them manually. This can be used for one-off services and debugging tools. As an example consider the following configuration:

This promise is not honored by docker compose currently

### Steps To Reproduce

Given `docker-compose.yml` file:
```yml
services:

  foo:
    container_name: foo_c
    profiles: [ test ]
    image: alpine
    command: [ "sleep", "10000" ]

  bar:
    container_name: bar_c
    profiles: [ test ]
    image: alpine
    command: [ "sleep", "10000" ]
```

Running `docker compose up -d foo` gives:
```bash
$ docker compose up -d foo
[+] Running 2/2
 ✔ Network foo_default  Created                                                                                      0.3s
 ✔ Container foo_c      Started
```

As you can see, `bar` is not started, as it would be via `docker compose --profile test up -d`:
```bash
$ docker compose --profile test up -d
[+] Running 3/3
 ✔ Network foo_default  Created                                                                                      0.3s
 ✔ Container bar_c      Started                                                                                      0.6s
 ✔ Container foo_c      Started
```

### Compose Version

Docker Compose version v2.29.7

### Docker Environment

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 52
  Running: 51
  Paused: 0
  Stopped: 1
 Images: 65
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.3-200.fc40.x86_64
 Operating System: Fedora Linux 40 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.64GiB
 Name: Redacted
 ID: ed88d9cb-bb99-42bd-9131-566f815d7a6c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: redacted
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by jhrotko** [comment]
Hello, @zwimer!

As you run `docker compose up -d foo` you are running only `foo` service. As `foo` is not dependent on `bar` it will only start `foo` as requested. In the provided examples, most services have `depends_on` to show more use cases for profiles.

**Comment by zwimer** [comment]
> Hello, [@zwimer](https://github.com/zwimer)!
> 
> As you run `docker compose up -d foo` you are running only `foo` service. As `foo` is not dependent on `bar` it will only start `foo` as requested. In the provided examples, most services have `depends_on` to show more use cases for profiles.

Hi, this makes complete sense to me and is why I opened this issue originally in the docs repo, however I was told to this behavior was indeed a bug and to move this to the compose repo instead: https://github.com/docker/docs/issues/21258#issuecomment-2443660822

Specifically, the documentation explicitly states:
> When a service with assigned profiles is explicitly targeted on the command line its profiles are started automatically so you don't need to start them manually. This can be used for one-off services and debugging tools. As an example consider the following configuration:

My interpretation of this is that: Running docker `compose up -d foo` (a service with assigned profiles explicitly targeted on the command line) should parse `profiles: [ test ]` (its profiles) and start them automatically (so you don't need to start them manually). I.e. this command should start the profile `test` and thus the services within `test`, which includes `bar`.

If the behavior demonstrated above is indeed correct and the documentation is incorrect (or just poorly worded), I can move this back to the `docs` repo and link this issue.

**Comment by zwimer** [comment]
I'll note that the docs also state:
```bash
# This runs db-migrations (and,if necessary, start db)
# by implicitly enabling the profiles `tools`
$ docker compose run db-migrations
```

I do see the `depends_on`, but the docs do not state that this command implicitly runs `db`; it says it implicitly enables the "profile `tools`, which does align with my reading of the docs above and imply the behavior demonstrated in this issue (not auto-starting the profile `test`) is indeed a bug.

**Comment by jhrotko** [comment]
@zwimer I understand completely your point. However, running `docker compose up foo` in this case should not start `bar` for the example you presented. I believe this is a documentation issue. 

When specifying the service, compose will only try to create and run that specific service and any dependency if it makes sense (`depends_on`). You still might just want to `up` a single service regardless of the profile (in this case, you might not want to up `bar` although they have the same profile). 

Or else it would be redundant to specify the service in the up command, which the user might want to do so.

All in all, the current behaviour is expected. Thanks for finding this!
