### ISSUE TITLE
docker compose watch – restart without sync

### ISSUE THREAD

**Issue by s-valent** [docker/compose#12243]
### Description

Hi! `docker compose --watch` seems like a very useful feature to restart the container on change (maybe `--watch` should even be on by default), but it looks like `sync+restart` does not work on volumes, and there is no option to just `restart` if it is a volume.

Is it possible to add it?

**Comment by jhrotko** [comment]
Hello @s-valent ,

yes, the `sync+restart` is meant to restart the containers and not the volumes. As a workaround you could handle this in your Dockerfile to cleanup the contents of a volume before starting by adding something like `RUN rm -rf /VOLUMEPATH/*` and add a 

```
watch:
...
    - action: rebuild
       path: SOME/PATH
```
which would trigger the cleanup. It is not a good solution but a workaround for now.

What could be really interesting to you is a new feature we will very soon release! It's called lifecycle hooks. There is one in particular that will be interesting for your use case the - `post_start` hook - this will run after the container starts and this could be useful to you to add a cleanup in this hook :) stay tuned!
