### ISSUE TITLE
Support for multiple .env files

### ISSUE THREAD

**Issue by gitshelmi** [docker/compose#12255]
### Description

I would like to request a feature enhancement for Docker Compose. In our large project, we've broken down the architecture into multiple docker-compose.yml files located in different directories. We've encountered an issue where we cannot have multiple .env files to provide parameters using the ${} syntax within these docker-compose.yml files.

Currently, Docker Compose looks for a single .env file in the directory where the command is executed, which limits our ability to manage environment variables for each compose file separately when they are in different paths. It would be highly beneficial if Docker Compose could support multiple .env files located in different directories, allowing each docker-compose.yml file to access its corresponding .env file regardless of the execution path.

This feature would greatly enhance the modularity and scalability of large projects by enabling better organization of environment variables across multiple compose files and directories.

Thank you for considering this request.

**Comment by jhrotko** [comment]
Hello @gitshelmi !

I was wondering why using [env_file](https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/#additional-information-1) does not support your current use case

**Comment by ndeloof** [comment]
You should use `include` so that a compose file can refer to resources declared in another one, but let the later run with a dedicated env file to load variables

see https://docs.docker.com/reference/compose-file/include/
