### ISSUE TITLE
Support `--no-interpolate` in `up` command.

### ISSUE THREAD

**Issue by stavros-k** [docker/compose#12257]
### Description

Similar to how `docker compose config` has a `--no-interpolate` flag. The same should be available in `up` command as well.

**Comment by stavros-k** [comment]
I would expect a failure in this case, for invalid port.

eg: You have a CI job that auto deploys a docker compose file on PR, but you want to make sure that a developer will not try to gain access of secrets in the CI runner.

Right now someone could add an entrypoint to the docker compose like so:
["echo", "${SOME_SECRET}"] and it will print that secret happily.

I want this feature disabled completely.

**Comment by ndeloof** [comment]
you should **never** let untrusted developers run arbitrary changes on CI with access to global secrets.
There's MANY ways a malicious user could extract secret, with or without Compose to run interpolation

**Comment by stavros-k** [comment]
It is very strict on what fields devs can change.
entrypoint was just an example.
They dont have direct access to compose, eg even if they had access to set 1 env variable.
They can still interpolate an env.

I work around that currently with sed replacing all `$` with `$$`.
