### ISSUE TITLE
Support builds that fetch a secret dynamically from environment or filesystem

### ISSUE THREAD

**Issue by spencerwilson** [docker/compose#12259]
### Description

My Dockerfile contains a `RUN` instruction which runs a script that configures a package manager to access a private registry. On the host where the build is running, the needed secret is available either from environment variables (in CI) or file (on developer workstations). I don't believe there's a Compose file I could write that would successfully build the image in both CI and locally. This is because Compose currently requires a static specification of the secret's source: `file` _or_ `environment` (see [here](https://docs.docker.com/reference/compose-file/secrets/#:~:text=The%20source%20of,environment)).

Buildx, in contrast: When providing secret values to BuildKit, Buildx can dynamically check both the environment and filesystem (see [here](https://docs.docker.com/reference/cli/docker/buildx/build/#secret:~:text=Buildx%20attempts%20to,automatically%20if%20unset)).

## Addendum: Support optional secrets

While working on this, I also found that Compose image building fails if it can't resolve a value for a declared secret (e.g., a `file` secret but the file doesn't exist), even if the secret reference in the Dockerfile—`RUN --mount=type=secret`—has attribute `required=false` (which is the default). Feels like it could make sense for Compose to "inherit" the optionality and not fail if a value for the secret can't be resolved. But that's a separate feature request.

**Comment by spencerwilson** [comment]
A teammate just pointed me to https://docs.docker.com/reference/compose-file/merge/. It might be possible to achieve what I want by having two sets of compose files:
- for CI: compose.yaml and compose.ci.yaml
- for local: compose.yaml and compose.dev.yaml

Where the latter in each pair overlays the appropriate secret declarations onto the base compose.yaml.

**Comment by ndeloof** [comment]
You don't need a compose.dev.yaml file AFAICT as your compose.ci.yaml file can fully redefine the secret using `!override`:
```yaml
secrets:
  foo: !override
    environment: ${SECRET}
```

While I understand the benefit you get by buildx to be flexible with secret type identification, we have no plan to mimic this mechanism in Docker Compose as the compose file model is designed to be way more predictable, and changing this behavior would impact existing users.

Closing this issue as "not planned"
