### ISSUE TITLE
[BUG] sudo apt-get install docker-compose-plugin OR sudo apt update does not pull latest compose version. Want 2.30.2 Installed via APT

### ISSUE THREAD

**Issue by XBadFellaX** [docker/compose#12269]
### Description

badfella@ubuntu:~$ sudo apt-get install docker-compose-plugin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
docker-compose-plugin is already the newest version (2.29.7-1~ubuntu.24.04~noble).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

I want to have the version 2.30.2 and to be able to update via sudo apt update.

I tried the manual install and that works for 2,30.2 but then I have to update it manually everytime.

thanks for looking into this.

### Steps To Reproduce

badfella@ubuntu:~$ sudo apt-get install docker-compose-plugin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
docker-compose-plugin is already the newest version (2.29.7-1~ubuntu.24.04~noble).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

Tried the instructions here
https://docs.docker.com/compose/install/linux/

And completely removed and installed docker compose but no success.

### Compose Version

2.29.7

### Docker Environment

##@ubuntu:~$ sudo docker info
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 48
  Running: 47
  Paused: 0
  Stopped: 1
 Images: 47
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.12-3-pve
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 24GiB
 Name: ubuntu
 ID: 6355ee5f-1913-44fc-8841-c64a7f074eca
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false

**Comment by glours** [comment]
Hello @XBadFellaX 
There release process of Compose to our Linux packages repository is coupled to Docker engine releases (see [moby/moby](https://github.com/moby/moby) repo), you'll have to wait a little bit to have it available via apt-get
