### ISSUE TITLE
[BUG] Cannot override env_file attribute with --env-file

### ISSUE THREAD

**Issue by rkimball-ankored** [docker/compose#12264]
### Description

I have a Docker Compose file that specifies an env_file attribute.  If I run `docker compose` specifying a different env file with --env-file, the resulting environment contains the values from the first file.

### Steps To Reproduce

**Files**

compose.yaml:
```
services:
  test:
    env_file: one.env
    image: scratch
```

one.env:
```
VAR=one
ONE=1
```

two.env:
```
VAR=two
TWO=2
```

**Behavior**

Run `docker compose --env-file two.env config`

Expected result:
```
name: tmp
services:
  test:
    environment:
      TWO: "2"
      VAR: two
    image: scratch
```

Actual result:
```
name: tmp
services:
  test:
    environment:
      ONE: "1"
      VAR: one
    image: scratch
```

### Compose Version

Docker Compose version v2.29.7-desktop.1

### Docker Environment

Client:
 Version:    27.3.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1-desktop.1
    Path:     /Users/ronald.kimball/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7-desktop.1
    Path:     /Users/ronald.kimball/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     /Users/ronald.kimball/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /Users/ronald.kimball/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/ronald.kimball/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     /Users/ronald.kimball/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/ronald.kimball/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/ronald.kimball/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/ronald.kimball/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.14.0
    Path:     /Users/ronald.kimball/.docker/cli-plugins/docker-scout

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 83
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.11-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.653GiB
 Name: docker-desktop
 ID: fc286467-f610-4533-bd83-61932be95876
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/ronald.kimball/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile

### Anything else?

Reading the documentation, I would expect this to work.

https://docs.docker.com/compose/how-tos/environment-variables/envvars-precedence/
> 2. Set with either the environment or env_file attribute but with the value interpolated from your [shell](https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#substitute-from-the-shell) or an environment file. (either your default [.env file](https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#env-file), or with the [--env-file argument](https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#substitute-with---env-file) in the CLI).

https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#substitute-with---env-file
> [Substitute with --env-file](https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#substitute-with---env-file)
> ...
> This method is useful if you want to temporarily override an .env file that is already referenced in your compose.yml file.

I am using --env-file to override an .env file that is already referenced in my compose.yaml file, as stated in the documentation, but Docker Compose is still using the values from the file referenced in compose.yaml.

**Comment by ndeloof** [comment]
`--env-file` flag is used to set variables used by compose for interpolation of `${FOO}` values in yaml, it is unrelated to `env_file` attribute which defines container's environment. This is a common confusion.

**Comment by rkimball-ankored** [comment]
I'm trying to think of a quick change to clarify the documentation.  How about adding a sentence like "Note that the --env-file argument does not directly affect the container's environment.  Instead, it is used by compose for interpolation of ${FOO} values in yaml, including under the `environment` attribute." 

---

Given the behavior, is there a way to do what I want, which is to have the default environment variables in an env file specified with the env_file attribute, but be able to override those values with an env file specified on the command line?

I tried this:

```
services:
  test:
    env_file: one.env
    environment:
      - VAR=$VAR
      - ONE=$ONE
      - TWO=$TWO
    image: scratch
```

```
docker compose config
```

But the result is:

```
WARN[0000] The "VAR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ONE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TWO" variable is not set. Defaulting to a blank string. 
name: tmp
services:
  test:
    environment:
      ONE: ""
      TWO: ""
      VAR: ""
    image: scratch
    networks:
      default: null
```

From a careful reading of the documentation, I see that this is the expected behavior.

Although renaming "one.env" to ".env" and removing the env_file attribute would work, I am trying to avoid the use of a hidden file.

**Comment by rkimball-ankored** [comment]
I never would have thought I could use interpolation in the env file!  Thanks!
