### ISSUE TITLE
command output interpolation in docker-compose.yml

### ISSUE THREAD

**Issue by rino1** [docker/compose#12275]
### Description

Hello everyone, here is my scenario

```
+ lsb_release -a
Description:	Ubuntu 24.04.1 LTS

+ bash --version
GNU bash, versione 5.2.21(1)-release (x86_64-pc-linux-gnu)

+ cat docker-compose.yml
services:
    composer:
        image: bash/bash
        environment:
            # INTERPOLATED: NO
            NEW_DATE: $(date)
            # INTERPOLATED: YES
            NEW_PATH: $PATH
```

Let's do some tests

```
# echo command output
+ echo $(date)
ven 8 nov 2024, 07:31:58, CET
```

OK, but...

```
+ docker compose config | grep NEW
      NEW_DATE: $$(date)
      NEW_PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin...etc...etc...
```

As you can see, $(date) is not interpolated (evaluated).

Is it a bug?
Is it a feature not implemented?
Or am I doing something wrong?

**Comment by ndeloof** [comment]
Docker Compose interpolates variables set by environment (or .env file) using a bash-like `${VAR}` syntax, but this is definitely not just a full bash implementation and it does not support sub-command execution (`$(command)`) - and never will, as this would just break portability (how can you guarantee all system will have this command installed, with a consistent version and output?)

see https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/

What's your actual use-case ? To access current date your container can just run `date` on its own, or equivalent syscall from application code.

**Comment by rino1** [comment]
thanks
