### ISSUE TITLE
How to run containers in privileged mode

### ISSUE THREAD

**Issue by kvz** [docker/compose#123]
From my docker container I would like to mount a network share. I've tried samba, afs, and nfs, but I keep getting Operation not permitted.

Googling has led me to believe that my container would need to run in `privileged` mode (http://www.gluster.org/2014/02/running-glusterfs-inside-docker-container/)

With Docker one can do `--privileged=true` but I don't think I can pass this along from my `fig.yml` via a:

``` yaml
sabnzbd:
  build: ./sabnzbd
  command: /syzygy/run.sh
  privileged: true
```

As that throws a `Unsupported config option for sabnzbd service: 'privileged'`. It also isn't documented in the fig documentation. Any way to go around this? I would be happy with any solution that allows me to mount a network drive, right now I just think that requires priviledged but I might be wrong. 

Might be worth mentioning that I'm using the 0.8.0 boot2docker osx install.

**Comment by bitliner** [comment]
I am using fig 1.0.1

If I try to set privileged up, it is like it does not work.

In other words:
* my Dockerfile print to a file a string
* normally, it throws `read-only filesystem`
* so I add `privileged:true` to fig.yml
* but then same error happens while building the container

**Comment by lucaspottersky** [comment]
I'm facing the same issue as @bitliner 

`docker-compose version: 1.4.1`
`Docker version 1.7.0, build 0baf609`

**Comment by dnephin** [comment]
`privileged` doesn't apply to the `build` phase. It's only applied to a running container. This is a restriction applied by docker, but it's not obvious from the docker-compose.yaml.

**Comment by tenager** [comment]
I am experiencing similar issue with `docker-compose.yml`.  I am getting "`Ignoring unsupported options: privileged`" message. Any idea how to apply --privileged: true in docker-compose file??

**Comment by Sispheor** [comment]
@tenager same for me.
I'm on `Docker version 17.12.1-ce, build 7390fc6`

**Comment by rakshak-t** [comment]
> `privileged` doesn't apply to the `build` phase. It's only applied to a running container. This is a restriction applied by docker, but it's not obvious from the docker-compose.yaml.

Yep this ended up being the solution. Had to call from within the container and not the Dockerfile
