### ISSUE TITLE
[BUG] dashes not supported in environment variable names in .env files

### ISSUE THREAD

**Issue by vvuk** [docker/compose#12302]
### Description

This was seemingly fixed in #9570 last year, and looking at the code it doesn't look like the code regressed, but I can't seem to include environment variables with a `-` in them via `env_file` in a compose file. 

### Steps To Reproduce

`foo.env` contains (hello ASP.NET config env vars):
```
services__storage-service__http__0=http://storage:2227
```

`docker-compose.yaml` contains:
```
services:
  storage:
    image: ..
    env_file: foo.env
```

trying to do `up` errors out with:

```
failed to read ...foo.env: line 1: unexpected character "-" in variable name "services__storage-service__http__0=http://storage:2227"
```
(I'm also a little confused why it prints the entire line as "variable name" but I think that's just a printing issue?)

I can define variables with a - in them fine directly in `environment:` entries in the compose file.

### Compose Version

```Text
Docker Compose version v2.29.7, Ubuntu 22.04.
```

### Docker Environment

```Text
lient: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```

**Comment by vvuk** [comment]
Actually, wait. #9570 claims it was fixed in https://github.com/compose-spec/compose-go/pull/336 but the source change (which is the same that remains today):

https://github.com/ndeloof/compose-go/blob/33ef4a1bc762fc99acd5d485a2346e0662a1a237/dotenv/parser.go#L122-L132

the patch added `'-'` to the case statement, but it would have fallen through default anyway -- and the following lines are still checking `IsNumber` or `IsLetter` exactly like before. So I'm not sure if this actually did anything to allow `-`?

**Comment by andrasballai-guidance** [comment]
I think this should be reconsidered. Either require an explicit second character, like `:-` to refer to default value if more than one `-` is in an expression, or allow a way to escape a dash
