### ISSUE TITLE
[BUG] mark python package as unmaintained/legacy

### ISSUE THREAD

**Issue by Finkregh** [docker/compose#12326]
### Description

The python package at https://pypi.org/project/docker-compose/ should be marked as legacy/unmaintained or possibly even deleted.

### Steps To Reproduce

compare https://pypi.org/project/docker-compose/ with https://github.com/docker/compose/blob/main/README.md?plain=1#L86

**Comment by ndeloof** [comment]
💯 the main question is "how to"? Without having a new release

**Comment by ndeloof** [comment]
that's typically what we'd like to avoid.
python package manager unfortunately doesn't offer any way to mark a package as deprecated

**Comment by remcokranenburg** [comment]
Assuming this is to avoid people unintentionally installing a very old version, another method might be to actually publish the Go versions on PyPI as new versions. But not sure if that's worth it, because it would complicate the release process of Compose.

**Comment by ndeloof** [comment]
Closing as "not planned" - until pypi offers a mechanism so we can deprecate/remove the legacy docker-compose package
