### ISSUE TITLE
sort output of `docker compose up -d` by name

### ISSUE THREAD

**Issue by trim21** [docker/compose#12333]
### Description

currently the output of `up -d` is unstable, proposal to add sort by services name (when possible)

**Comment by trim21** [comment]
after reading the code I fine that they are already sorted, by label `com.docker.compose.container-number` or by creation date

https://github.com/docker/compose/blob/6b3e57503ef2e1bfe21cab9c3f15e1a92868b34f/pkg/compose/convergence.go#L127-L147

**Comment by glours** [comment]
Hello @trim21 

What do you mean by unstable? 
`docker up -d` only display build and containers creation steps.
`docker up` will also display container logs but as containers are running in parallel logs can be mixed in the output, that why logs are prefixed by the container service name like:
```shell
api-1  |  * Debugger PIN: 703-580-771
web-1  | yarn run v1.22.22
```

If you want to focus on a specific service log you can use `docker compose logs your-service-name`

**Comment by trim21** [comment]
I mean `docker compose up -d` (do docker also have a `up` command? i'm sorry for the confusion)

for example, the first run:
```text
[+] Running 3/0
 ✔ Container chii-backup-1    Running                                                                                                             0.0s
 ✔ Container chii-pg-patch-1  Running                                                                                                             0.0s
 ✔ Container chii-pg-1        Running 
```

the second run:
```text
[+] Running 3/0
 ✔ Container chii-pg-patch-1  Running                                                                                                             0.0s
 ✔ Container chii-pg-1        Running                                                                                                             0.0s
 ✔ Container chii-backup-1    Running
```

**Comment by trim21** [comment]
Looks this is currently not very doable...

The services without dependency relation will startup in parallel, add such feature will slowdown the startup process or need to change the output
