### ISSUE TITLE
Proposal: Support for affinity filter in Docker Swarm

### ISSUE THREAD

**Issue by denverdino** [docker/compose#1234]
Swarm provide the container affinity to control the placement of container with the environment variables as following

E.g. 

```
affinity:container==[<container_name>|<regexp>]
affinity:container!=[<container_name>|<regexp>]
affinity:container==~[<container_name>|<regexp>]
affinity:container!=~[<container_name>|<regexp>]
```

The challenge to use the affinity in the Compose template are
1. The container name is generated with service name and project name. It is not easy to write above filter easily. 

Propose to use bellow way to describe the container affinity for specific service. And it will be converted to the "affinity:container" when create/recreate the container

```
affinity:service==<service_name>
affinity:service!=<service_name>
affinity:service==~<service_name>
affinity:service!=~<service_name>
```

E.g. the following compose template to deploy the containers of "web" and "test" service in different hosts.

```
web:
  image: nginx
  ports:
    - 80
test:
  image: nginx
  ports:
    - 80
  environment:
    - affinity:service!=~web
```
1. The implied affinity relationship between service should be considered.

E.g. for above sample, if we recreate the container for "web" service. It will be better to consider the affinity filer of "test". Otherwise, the new container may break the expectation for the placement.

So if service "A" has the affinity condition with "B", the "B" should have the same affinity condition with "A"

**Comment by dnephin** [comment]
Instead of rewriting `service` to `container`, we should use http://docs.docker.com/swarm/scheduler/filter/#label-affinity

Every service has a label, so we can set an affinity based on the service label.  That way it will work with scale (setting container affinity would not work with scale because some containers would be created after others).

**Comment by denverdino** [comment]
@dnephin Daniel, using the label filter will be good from the implementation point of view. The challenge is the docker-compose

**Comment by ndeloof** [comment]
closing as obsolete. 
Feel free to contribute to the compose-specification if you wish to extend compose file format
