### ISSUE TITLE
Embed dockerfiles in docker-compose.yml?

### ISSUE THREAD

**Issue by lucafabbian** [docker/compose#12374]
### Description

I know that an old issue already exists #7095 but it was closed due to inactivity, I just want to remind that this would be very very valuable to some people.

I think it will be very trivial to implement, and very game-changing in some scenarios, as explained in the past issue.
I can implement that and make a pull request if you wish.

**Comment by glours** [comment]
Hello @lucafabbian 
It's already possible with `dockerfile_inline` [attribute](https://github.com/compose-spec/compose-spec/blob/main/build.md#dockerfile_inline)
