### ISSUE TITLE
Production ready vs fig?

### ISSUE THREAD

**Issue by mmartinson** [docker/compose#1239]
I'm just looking into fig/compose for a newish project that I'm hoping will be reaching early production fairly soon. Would it be recommended to start by using fig despite it being deprecated or does this project  seem to be reaching maturity quickly?

I appreciate any feedback, I'm new to using docker.

**Comment by cpuguy83** [comment]
@mmartinson fig and compose are quite litterally the same thing.
Compose is Fig 1.1.

**Comment by mmartinson** [comment]
@cpuguy83. ah thanks, that simplifies things

**Comment by thaJeztah** [comment]
@mmartinson did that sufficiently answer your question? If it did, could you close this issue? Thanks!
