### ISSUE TITLE
Getting /bin/bash: /usr/src/app/run.sh: No such file or directory

### ISSUE THREAD

**Issue by jaewie** [docker/compose#1254]
Hello, my current directory looks like:

	.
	├── app.js
	├── docker-compose.yml
	├── package.json
	└── run.sh

And my docker-compose.yml is:

	nodeapp:
	  image: node:0.12
	  command: /bin/bash /usr/src/app/run.sh
	  volumes:
	    - .:/usr/src/app
	  ports:
	    - 80:8000

But wIth `docker-compose up` I'm getting the fllowing. How can I fix this issue?

	Attaching to ebdockermultipleports_nodeapp_1
	nodeapp_1 | /bin/bash: /usr/src/app/run.sh: No such file or directory
	ebdockermultipleports_nodeapp_1 exited with code 127
	Gracefully stopping... (press Ctrl+C again to force)

**Comment by jaewie** [comment]
Just as a follow up, it started working again after removing the containers, and I have no idea how to reproduce it again.

**Comment by thaJeztah** [comment]
Glad to hear you got it working.

If you are no longer able to reproduce, could you close this issue? Feel free to re-open at a later stage, if you have some way to reproduce. Thanks!

**Comment by dnephin** [comment]
If removing the container fixed it, it's very likely you're hitting the problem that is fixed by #858

**Comment by thaJeztah** [comment]
@dnephin did that also affect bind-mounted volumes?

**Comment by dnephin** [comment]
I believe the `volumes_from` used by the intermediate container could actually mask the contents of a bind-mounted volume as well. There have been a few issues where a container started with a data volume, then tried to change to a host volume, but the earlier data-volume was being overriding it.

**Comment by thaJeztah** [comment]
@dnephin ah, that makes sense. Thanks for adding that
