### ISSUE TITLE
Support build containers

### ISSUE THREAD

**Issue by fabiokung** [docker/compose#1257]
As specified here: [jamiemccrindle/dockerception](https://github.com/jamiemccrindle/dockerception).

Currently `build` in a `docker-compose.yml` file does not allow custom build pipelines (other than `docker build -t <tag> <path>`) to be specified. Either extend what can be done with the `build` property, or introduce something else to make it possible to build runtime containers using an intermediate build container that outputs the build context as a tar stream.

**Comment by dnephin** [comment]
I've used shipwright myself as an alternative to `docker-compose build`, but this feels (to me at least) like something that should remain external to compose itself.  There is the potential to add a lot of complexity to compose, when it's not really necessary. It's just as easy to do:

```
run-my-fancy-build-tool
docker-compose up -d --no-build
```

And have all the services in the `docker-compose.yml` just use `image:`.

Related #693

**Comment by fabiokung** [comment]
I'd be OK with that too, but it seems like on those cases when compose is useful (multiple containers being run) there will be multiple container to be built. It's OK to leave it outside compose completely, but soon we may end up with another build-compose tool.
