### ISSUE TITLE
Unable to run tests with latest sources

### ISSUE THREAD

**Issue by draghuram** [docker/compose#1263]
When I run `./script/test`, I get the following error:

<pre>
...
...
docker run --rm --volume=/var/run/docker.sock:/var/run/docker.sock --volume=/mywork/compose:/code -e DOCKER_VERSIONS -e TAG=docker-compose:4f95e81 --entrypoint=script/test-versions docker-compose:4f95e81
Running lint checks
Running tests against Docker default
Unable to find image 'docker-compose:4f95e81' locally
time="2015-04-07T19:38:13Z" level=fatal msg="Error response from daemon: client and server don't have same version (client : 1.18, server: 1.17)" 
</pre>

Any help in getting past this problem is appreciated. 

Thanks,
Raghu

**Comment by aanand** [comment]
We're developing against Docker 1.6, so you need to run the tests against a 1.6 RC. If you're using Docker Machine on a Mac, you can run:

    curl https://test.docker.com/builds/Darwin/x86_64/docker-1.6.0-rc4 > /usr/local/bin/docker
    docker-machine create -d virtualbox --virtualbox-boot2docker-url=https://github.com/tianon/boot2docker/releases/download/v1.6.0-rc4/boot2docker.iso dev-1.6.0-rc4
    eval "$(docker-machine env)"
    docker version

The output of `docker version` should say `1.6.0-rc4` for both the client and server version.

**Comment by draghuram** [comment]
Thanks for response. I am developing on Ubuntu inside a container. I couldn't run `python setup.py develop` on my Ubuntu 14.04 host because of some conflict (related to `requests` dependency) so I use a Ubuntu container that is started with `--privileged` option. I can try building Docker from source but is there a way to get 1.6 on Ubuntu like you showed above for Mac?

**Comment by draghuram** [comment]
Never mind. I got 1.6 .0-rc5 using:

<pre>
curl -sSL -O https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc5 && chmod +x docker-1.6.0-rc5 && sudo mv docker-1.6.0-rc5 /usr/local/bin/docker
</pre>

**Comment by draghuram** [comment]
Once the new version of Docker is installed, the tests run fine. Thanks.
