### ISSUE TITLE
[Proposal] include directive

### ISSUE THREAD

**Issue by miko** [docker/compose#1267]
Hello,
I was looking to write an yml file for complex application configuration. I wanted to split it to smaller files, so I was looking for include command, so I could use:
```
include webserver.yml
include db.yml
```
Proposed extend command does not work, as I do not really want to "extend" anything, but to combine services from many files. Whould the include directive make sense?

**Comment by dnephin** [comment]
I believe this is a similar idea to #318, which I would still like to see happen.

**Comment by dnephin** [comment]
We've implemented a very similar idea in #2051

Otherwise I think this is a duplicate of #318
