### ISSUE TITLE
Uninstall docker compose

### ISSUE THREAD

**Issue by callmekatootie** [docker/compose#1273]
Hello,

I went through the documentation and I could not find how I can uninstall docker-compose.

I installed docker and docker-compose to know more about it. Now I am done and I wish to remove them. However, I could not find any info about how to carry that out.

I installed them through the instructions in the website.

OS: Ubuntu 14.04

**Comment by macobo** [comment]
This is probably the wrong place to ask this. However, you can uninstall compose with the same tool you installed it with - `pip uninstall docker-compose`

**Comment by thaJeztah** [comment]
The [instructions in the documentation](http://docs.master.dockerproject.com/compose/install/#install-compose) don't use pip. I think it's reasonable to explain how to uninstall docker-compose.

> This is probably the wrong place to ask this.

@macobo the docs are part of this repository. While I agree that the question could be interpreted as a "support" question, I think it points to an omission in the docs.

**Comment by AndyWendt** [comment]
It definitely is an omission in the docs

**Comment by thaJeztah** [comment]
@AndyWendt are you interested in creating a pull-request, explaining how to uninstall (both for "pip" installations and the "curl" install)? (Similar to, for example, https://docs.docker.com/installation/ubuntulinux/#uninstallation)

**Comment by AndyWendt** [comment]
@thaJeztah definitely!  I was just looking for the exact repo to send the modifications.  I will send it right over.

**Comment by thaJeztah** [comment]
Awesome! :+1:

**Comment by dnephin** [comment]
This is now in the docs https://github.com/docker/compose/blob/master/docs/install.md#uninstallation. It'll be published in the next release I guess?

**Comment by lifenautjoe** [comment]
@dnephin the docs link is gone, is this available elsewhere?

**Comment by dnephin** [comment]
https://docs.docker.com/compose/install/#uninstallation

**Comment by jaguilarte** [comment]
sudo apt remove docker-compose 
sudo apt autoremove

**Comment by alexratiu** [comment]
> sudo apt autoremove

Thanks man, that's works for me
