### ISSUE TITLE
docker-compose pull should also pull images from FROM in Dockerfile

### ISSUE THREAD

**Issue by schmunk42** [docker/compose#1274]
docker-compose pull downloads the latest version of an image tag, if the service has an `image` attribute.

But for services which are `build` you have to `docker pull` manually. Would be nice if docker-compose could check these images also, maybe with `--pull-build-from-images` or another option.

**Comment by dnephin** [comment]
I believe this is a duplicate of #726

**Comment by schmunk42** [comment]
Yepp, thx.
