### ISSUE TITLE
Feature request: using variables in the docker-compose files

### ISSUE THREAD

**Issue by ripcurld00d** [docker/compose#1282]
Hi all,

I am not sure whether this request is duplicated. Nevertheless, I find the usage of variables in the docker-compose files necessary. In other words, in addition to the docker-compose.yml file, there is a vars-compose.yml file, where those variables are assigned.

BR

**Comment by thaJeztah** [comment]
I think this duplicates some existing issues, see https://github.com/docker/compose/issues/495#issuecomment-69085278, https://github.com/docker/compose/pull/845 and https://github.com/docker/compose/issues/846

**Comment by ripcurld00d** [comment]
ta! :+1:  closing
