### ISSUE TITLE
Using the latest version of requests

### ISSUE THREAD

**Issue by linlinlinlin** [docker/compose#1285]
Is it possible to using the latest version of requests package? (2.6)

Here is the release note for requests 2.6.
http://docs.python-requests.org/en/latest/

Cuz I saw the setup.py restrict it under 2.6.

**Comment by thaJeztah** [comment]
IIRC, there have been some incompatibilities in the past with more recent versions,
for that reason, requests was "pinned" to < 2.6. See https://github.com/docker/compose/pull/1100#issuecomment-78940214.

Not sure if that still is the case, possibly that 2.6 is safe

**Comment by funkyfuture** [comment]
are there tests that check for these incompatibilies? (the post you linked doesn't reveal much about the actual issues.)

**Comment by thaJeztah** [comment]
@funkyfuture not sure; just mentioning what I remembered, but I'll leave it to @aanand, he will probably know :)

**Comment by dnephin** [comment]
I believe the issue is an incompatibility with pyinstaller which is used to build the binary distribution. I think running `scripts/build-osx` or `scripts/build-linux` and trying to use the binary should reproduce the issue.

**Comment by thaJeztah** [comment]
Thanks, @dnephin I think that was it, yes. Perhaps a global tracker issue should be created to periodically check if the version can be raised?

**Comment by dnephin** [comment]
We're now on requests 2.7
