### ISSUE TITLE
Validate Compose file and produce better error messages

### ISSUE THREAD

**Issue by aanand** [docker/compose#129]
There are a lot of ways to confuse Compose with a badly-formed `docker-compose.yml`. This file should be checked when it is read and good error messages should be produced to help users fix the problem.

This could be done by producing a schema for the file, like was done in https://github.com/docker/compose/pull/1348.

These sorts of things should be checked:

- [x] Top-level object is a dict
- [x] Each key (a service name) maps to a dict (https://github.com/orchardup/fig/pull/128)
- [ ] String config options (e.g. `image`) - are numbers allowed? When? Don't accept YAML's eager interpretation of values (e.g. `true`) which should be quoted (#1788)
- [x] List config options (e.g. `volumes`) either *must* be a list, or we helpfully wrap single values in a list for you
- [x] String-or-list config options (e.g. `command`, `entrypoint`)
- [x] Dictionary config options (e.g. `environment`)
- [x] Format of various options (e.g. `volumes` - see #260)

References: #117 #127

**Comment by draghuram** [comment]
@aanand, Is there any consensus on the best way to implement the validation? I wanted to check first before I give it a shot.

**Comment by dnephin** [comment]
Not at all consensus, but I have been thinking that `jsonschema` would be a good option. It's language agnostic (so other tools interested in supporting the compose format can do so), and it should support validation for all the cases here.

**Comment by draghuram** [comment]
@dnephin, I will try to come up with schema using "JSON schema" and we can take it from there.

**Comment by funkyfuture** [comment]
@draghuram what's your status on this? *maybe* i will have the time to take care of this within the next days.

**Comment by draghuram** [comment]
@funkyfuture As you can see, I created a PR with all the work that I have done. Basically, there is a JSON schema file and code to validate the configuration against that. At some point, I was able to run all the tests successfully but that was some time back. I think there are two more things that need to be done:

- Write tests covering invalid configurations
- Make sure that Schema covers everything that we need.

Please feel free to build on top of this PR as I may not be able to spend time on this issue.

**Comment by kumavis** [comment]
+1 to keeping yaml
+1 to validating the schema

**Comment by mnowster** [comment]
I majority of these concerns should now be covered/addressed by https://github.com/docker/compose/pull/1808

**Comment by KamilKopaczyk** [comment]
Could it be more strict? Perhaps allowed values for keys such as _restart_?

Lately i was investigating why one of my containers isn't restarting, when others do. I looked at my yaml file and everything was ok. Except for a typo i didn't see ;)
```
restart: unless-stopeed
```

You can type whatever you want as a value and nothing stops you from running containers this way.

**Comment by dnephin** [comment]
Accepted values for `restart` should be validated by the server. If we were to validate them on the client side then we'd have to constantly be updating the list as the server changed.  I think this bug should be reported at docker/docker. It should fail with an error if the restart value is not correct, I guess currently it's just ignoring the value.

**Comment by jamshid** [comment]
Doesn't sound like I'll be able to put `SERVICE_IS_PRIVILEGED=true` in an .env file and build a docker-compose.yml like:
```
  myservice:
    privileged: ${SERVICE_IS_PRIVILEGED}
    ...
```
Maybe this env variable limitation could be mentioned in:
https://docs.docker.com/compose/environment-variables/

**Comment by lmurali89** [comment]
I continue to get this error message on windows.

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

docker-compose.yaml/yml file is in the directory mentioned. docker and docker compose versions are shown below. someone please help me at the earliest

docker --version
Docker version 19.03.5, build 633a0ea

docker-compose --version
docker-compose version 1.25.4, build 8d51620a
