### ISSUE TITLE
Docker-compose doesn't start, complains about missing urllib.parse

### ISSUE THREAD

**Issue by JonasT** [docker/compose#1290]
I installed docker-compose through pip, but it doesn't run:

```
jonas@cyberman#18: docker-compose 
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.1.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 348, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2311, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2025, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/compose/__init__.py", line 2, in <module>
    from .service import Service  # noqa:flake8
  File "/usr/lib/python2.7/site-packages/compose/service.py", line 10, in <module>
    from docker.errors import APIError
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 20, in <module>
    from .client import Client # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 34, in <module>
    import websocket
  File "/usr/lib/python2.7/site-packages/websocket/__init__.py", line 22, in <module>
    from ._core import *
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 41, in <module>
    from ._url import *
  File "/usr/lib/python2.7/site-packages/websocket/_url.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ImportError: No module named urllib.parse
jonas@cyberman#18:
```

I suppose some dependency is missing here? I just installed docker-compose from the latest pip package:
```
pip install -U docker-compose
```
(There's a separate pip3, so I know this used the python2 pip, just in case that's important)

Edit: /usr/bin/python defaults to python2.7 unlike previously stated.

**Comment by JonasT** [comment]
jonas@cyberman#26: /usr/bin/python2 --version
Python 2.7.8
jonas@cyberman#26: /usr/bin/python --version
Python 2.7.8
jonas@cyberman#27: pip show docker-compose
---
Name: docker-compose
Version: 1.1.0
Location: /usr/lib/python2.7/site-packages
Requires: docopt, PyYAML, requests, texttable, websocket-client, docker-py, dockerpty, six
jonas@cyberman#27: pip show six
---
Name: six
Version: 1.9.0
Location: /usr/lib/python2.7/site-packages
Requires: 
jonas@cyberman#27:

**Comment by JonasT** [comment]
```
jonas@cyberman#28: pip freeze | grep six
Warning: cannot find svn location for apsw==3.8.4.3-r1
six==1.9.0
jonas@cyberman#26: pip freeze | grep docker
Warning: cannot find svn location for apsw==3.8.4.3-r1
docker-compose==1.1.0
docker-py==0.7.2
dockerpty==0.3.2
jonas@cyberman#26:
```

**Comment by JonasT** [comment]
There seems to be some conflict with fedora's python-urllib3 and/or python-requests package. I solved it by now by removing docker-compose entirely, reinstalling the fedora packages, and reinstalling docker compose again.

Since another fedora user just got this same issue, maybe you should look into this. Seems to be too much of a coincidence that someone else got it independently for this to be just a random hiccup.

**Comment by SlimKac** [comment]
I'm using fedora 21, I had same issue and I just fixed it by using your solution (removing python3-requests and python3-urllib3).

Thank you.

**Comment by sanpingz** [comment]
I updated websocket to solve my problem, `pip install -U websocket`

**Comment by 4dn** [comment]
As @sanpingz pointed out, updating websocket solved it in my Fedora 21 machine.

**Comment by mojavelinux** [comment]
I can confirm that upgrading websocket solved it on my Fedora 21 machine as well.

```
sudo pip install -U websocket
```

I didn't have to reinstall docker-compose afterwards, so it works in either order.

**Comment by aanand** [comment]
Sounds like https://github.com/docker/docker-py/pull/645 might fix this - docker-py has updated its dependency from 0.11 to 0.32.

**Comment by dnephin** [comment]
This issue was likely resolved by the upgrade to docker-py. Please re-open if you're still experiencing it.

**Comment by JonasT** [comment]
Still happens. Try for yourself (100% reproducability):

**Step 1:** Make a new empty folder and put this in a ```Dockerfile```:
```
FROM fedora:22

RUN dnf update -y
RUN dnf install -y python python-pip python-requests
RUN pip install docker-compose

CMD docker-compose
```
**Step 2:** Build the container
**Step 3:** Run the container

Have fun with the full backtrace!
