### ISSUE TITLE
How to mount inner path to the host

### ISSUE THREAD

**Issue by PositiveAlex** [docker/compose#1291]
I've tried to add volumes into an yml file, but it creates new empty dir on the host and replaces directory inside of a container. I need to get container's /usr/local dir to be mounted on the host machine in ~/container/usr/local, but insteard of it i get empty /usr/local dir inside of container without installed programs in it.

My goal is to deploy jar file into the talend esb from outside of container not modifying an image.

**Comment by cpuguy83** [comment]
@PositiveAlex This is not possible.

You can just specify a plain old volume to `/usr/local` in the container, and Docker will create a host path for you in `/var/lib/docker/vfs/<volume id>`, and copy the contents of the container's `/usr/local` into there, then bind-mount that new dir into the container's `/usr/local`.
So you'd have to go in and add your files to this new path on the host after the container is created.

**Comment by PositiveAlex** [comment]
@cpuguy83 
thank you, Brian.
