### ISSUE TITLE
Alphabetize Commands

### ISSUE THREAD

**Issue by UserTaken** [docker/compose#1301]
`Docker` commands are organized alphabetically while `Docker Compose` commands are not. Also `Docker` and `Docker Machine` have the option to print version with `-v` while `Docker Compose` does not. Related to version is that it is listed as the last option in the aforementioned. Sorry if this sounds like extreme OCD, but I thought it would be good to have all the help output be as uniform as possible.

```
Fast, isolated development environments using Docker.

Usage:
  docker-compose [options] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE           Specify an alternate compose file (default: docker-compose.yml)
  -p, --project-name NAME   Specify an alternate project name (default: directory name)
  --verbose                 Show more output
  -v, --version=false       Print version information and quit

Commands:
  build						Build or rebuild services
  help						Get help on a command
  kill						Kill containers
  logs						View output from containers
  port						Print the public port for a port binding
  ps						List containers
  pull						Pulls service images
  restart					Restart services
  rm						Remove stopped containers
  run						Run a one-off command
  scale						Set number of containers for a service
  start						Start services
  stop						Stop services
  up						Create and start containers
```

**Comment by thaJeztah** [comment]
+1 for consistency (edging on OCD myself :))

**Comment by mchasal** [comment]
#dibs Fixing now

**Comment by UserTaken** [comment]
I also have an open issue with `Docker-machine`'s help output to be more consistent with `Docker` and `Docker-compose` https://github.com/docker/machine/issues/1014.

**Comment by dnephin** [comment]
This was done in 9a44708081406304325c45571026c1ca3ba1f944
