### ISSUE TITLE
Support `--log-driver`

### ISSUE THREAD

**Issue by colinrymer** [docker/compose#1303]
Docker 1.6 adds support for the `--log-driver` option. It'd be great to be able to set this in the `docker-compose.yml` file.

**Comment by chernjie** [comment]
+1

just bump into this problem

**Comment by doomrobo** [comment]
+1
Looks like compose and docker-py will have to be updated to support the --log-driver

**Comment by pavlo** [comment]
+1

**Comment by cmoro-deusto** [comment]
Just upgraded to docker v1.6 and happily migrated all my oldishe bash start/stop scripts to compose only to find that ```--log-driver``` is not yet supported. This would be great. 

If you need help beta testing this just let me know. 

Thanks a lot for you awesome work!

**Comment by StyleEX** [comment]
+1

**Comment by chernjie** [comment]
keep a watch out for https://github.com/docker/docker-py/issues/547

**Comment by cmoro-deusto** [comment]
thanks @chernjie

**Comment by lwcolton** [comment]
It looks like https://github.com/docker/docker-py/issues/547 has been resolved.  +1 to adding log driver support to docker compose.

**Comment by cyppan** [comment]
+1

**Comment by strootman** [comment]
+1

**Comment by saschaarthur** [comment]
well im ultra bad at python i tried to start with:

--- a/compose/config.py
+++ b/compose/config.py
@@ -21,6 +21,7 @@ DOCKER_CONFIG_KEYS = [
     'image',
     'labels',
     'links',
+    'log-driver',
     'mem_limit',
     'net',
     'pid',

--- a/compose/service.py
+++ b/compose/service.py
@@ -25,6 +25,7 @@ DOCKER_START_KEYS = [
     'env_file',
     'extra_hosts',
     'net',
+    'log-driver',
     'pid',
     'privileged',
     'restart',

now compose accepts "log-driver" argument in *.yml but it seems its not passing it, can anybody verify / help out? :)

**Comment by vdemeester** [comment]
@saschaarthur This would look like this : https://github.com/vdemeester/compose/commit/e324022980fb0ce927fc7b22c63cfaab1e6ac762

I'm looking at how to test it (unit & integration tests)

**Comment by vdemeester** [comment]
The other questions is : With ``-log-driver`` it's possible to pass out config (with a set of *key/value*). How would it translate in a ``docker-compose.yml`` file. Something like that would do ?

```yaml
web:
    image: busybox
    log_config: 
        type: json-file
        configs:
            - key1: val1
```

**Comment by doomrobo** [comment]
That looks almost right. I think it should be `config` instead of `configs`. I'm basing this on a cursory look at the source for [LogConfig](https://github.com/docker/docker-py/blob/185fceda7b32b28aed27eae86a3a4bc2a457ba44/docker/utils/types.py#L19). Good job!

```yaml
web;
  image: busybox
  log_config:
    type: json-file
    config:
      - key1: val1
      - key2: val2
````

**Comment by vdemeester** [comment]
@doomrobo ah yeah, agree.

Something is weird, I don't see an option in the ``docker run`` command for the config. I know ``--logging-opt`` for the daemon but I don't see it for the ``run``. You definitely can set it via the API but not via the CLI.. I'm gonna take a look at the docker source code to see how it is used.

Also, the flag is ``--log-driver``, we might want to use the same term instead of ``log_config`` ?

**Comment by doomrobo** [comment]
I believe it should be available in `docker run`. Maybe you're running an old version? And yes, I agree for consistency's sake that it should be `log_driver:`. Hopefully your changes will get pulled soon! I kinda need this and it'd be a pain to install a custom docker on multiple machines

**Comment by vdemeester** [comment]
Well I was looking at this : https://docs.docker.com/reference/commandline/cli/#run ; there is just ``--log-driver=""``.

**Comment by doomrobo** [comment]
Right. I genuinely don't know what the `config` flags are for. I haven't seen any docs on it. Maybe just support `log_driver:` and pass `LogConfig` and empty dictionary for the `config` key? I'm out of my league already. Where da docker devs at?

**Comment by vdemeester** [comment]
@doomrobo Yeah, for now I'm just gonna support the following config in my PR to come. It'll keep things simple and will be coherent with the current ``docker run`` command.

```yaml
web:
    image: busybox
    log_driver: syslog
```

Don't know if it's like on the docker repo, but #dibs then :P

**Comment by saschaarthur** [comment]
@vdemeester thank you very much ! now i dont need to run rsyslog in each docker container :)

**Comment by florentb** [comment]
Is `--log-opt` also supported ?

**Comment by lxe** [comment]
I started receiving the following error message when setting `log_driver` to `none` in docker-compose.yml (docker-compose 1.4.0):

```
Failed to get logging factory: logger: no log driver named 'none' is registered
```

Is this a regression or am I doing something wrong?

**Comment by colinrymer** [comment]
I would imagine that you are doing something wrong, @lxe. The default driver is `json`, so if you don't want to explicitly set the log driver, you shouldn't include that config setting.

**Comment by florentb** [comment]
@lxe @colinrymer according to the doc, `log_driver: "none"` is valid. It could be useful in order to prevent Docker to write logs to file (and so preserve disk space) @lxe I think this is an informal message only. If for example you do `docker-compose up`, the `logs` command seems to be implicitly called and as you have no logs anymore you see this message. Nothing bad *a priori*. But I agree with you, this is not the same behavior as in the previous version.

**Comment by aanand** [comment]
@lxe Your Docker version might be out of date. I'm not entirely sure when the `none` driver was added - it might have been Docker 1.7 or 1.8.

**Comment by lxe** [comment]
@colinrymer @florentb @aanand I'm using the following versions of docker client and docker-compose:

```
$ docker -v
Docker version 1.8.1, build d12ea79
```

```
$ docker-compose --version
docker-compose version: 1.4.0
```

The docker daemon version is:

```
$ boot2docker ssh docker -v 
Docker version 1.8.0, build 0d03096
```

I'm specifying my `log_driver` in the `docker-compose.yml` file as per https://docs.docker.com/compose/yml/#log-driver

The weird thing is this worked in lower versions of docker-compose and docker.

**Comment by lxe** [comment]
I'm guessing this has something to do with https://github.com/docker/docker/commit/c0391bf5545afef5e675138556c39e4c0e9bf91b
