### ISSUE TITLE
Extends does not use correct data when doing "docker-compose restart service"

### ISSUE THREAD

**Issue by kevinsimper** [docker/compose#1309]
If i have a docker-compose.yml file where i extend a service with another from a file for an example called `config/development.yml`.

It works fine after the first `docker-compose up`, if i then change a value, an enviroment variable in this case 
```
common:
  environment:
    - DB_HOST=docker.dev:27017
```
to
```
common:
  environment:
    - DB_HOST=docker.dev:9000
```

and do a `docker-compose restart backend`, then `DB_HOST` will still be the old value before the edit, but if I do a `docker-compose stop` - `docker-compose start`, then `DB_HOST` is the correct value.

**Comment by aanand** [comment]
That's correct behaviour for `restart`, which is analogous to `docker restart`. `docker-compose up` will create a new container with the updated environment.

I'm surprised that you're seeing that happen with `stop` and `start` - they should just be stopping/starting existing containers. Are you sure those are the commands you used?

**Comment by kevinsimper** [comment]
Yes, it was those commands that i used :) Hence the confusion.

But what is then the right way to restart the containers?

**Comment by aanand** [comment]
The right way to restart containers, *without creating new ones*, is to use `restart` or `stop` followed by `start`. Those should behave identically and should not pick up changes from any YAML files - if you see something different, please let us know!

The right way to *stop and re-create your containers* to pick up any changes in any YAML file is `up`.

**Comment by kevinsimper** [comment]
I don't think that is really that useful, that you have to use `compose up` for them to pick up new changes from the YAML files, since `compose up` is a active process and if you do `Ctrl-C`, compose will exit the containers.

Why can't `docker-compose restart` not read from the yaml files?

**Comment by jrgensen** [comment]
`compose up -d` is your friend

**Comment by kevinsimper** [comment]
@jrgensen Yes, i have learned that, thanks :smile: he
