### ISSUE TITLE
Server start/restart using nodemon takes too long(3mins) using v1.2.0

### ISSUE THREAD

**Issue by yamii** [docker/compose#1321]
- use docker-compose v1.2.0
- docker-compose up <image>
- it takes 2/3 mins to start the server while running other 7 containers( 1 min if running alone)
   - same goes when nodemon fires up to restart server
- downgraded to v1.1.0 issue didn't occur.

**Comment by dnephin** [comment]
It sounds like the performance issue you're experiencing is the actual running on the application, not the startup time of compose, is that right?

That's very unexpected. Any more details you can provide? Maybe the `docker-compose.yml` ?

**Comment by yamii** [comment]
it's working fine now in my end. just recently update to docker-compose v1.2.0. @dnephin Thanks for the reply. 
Closing this issue.
