### ISSUE TITLE
Support ulimit options

### ISSUE THREAD

**Issue by divideby0** [docker/compose#1322]
Now that Docker 1.6 supports ulimit options, it would be nice to have this as an option for containers managed by compose, similar to `mem_limit`, `cpu_shares`, etc.

**Comment by janober** [comment]
+1

**Comment by aanand** [comment]
Both are already supported: http://docs.docker.com/compose/yml/#working95dir-entrypoint-user-hostname-domainname-mem95limit-privileged-restart-stdin95open-tty-cpu95shares

**Comment by divideby0** [comment]
To clarify, `mem_limit` and `cpu_shares` are supported but it doesn't appear that `ulimit` is supported yet.  Ulimit options were only recently added in the Docker 1.6 engine:

https://blog.docker.com/2015/04/docker-release-1-6/

**Comment by aanand** [comment]
Sorry, I misread. Yes, `ulimit` support would be good. Looks like docker-py added support in https://github.com/docker/docker-py/pull/554, so it should be simple to do.

**Comment by corbinu** [comment]
+1 need for couchbase/server image

**Comment by thaJeztah** [comment]
Also worth noting that docker recently added support for ulimit to `docker build` as well. I wonder if compose should apply the limits both for build and run?

**Comment by tpires** [comment]
+1

**Comment by lu4nm3** [comment]
+1

**Comment by kfox1111** [comment]
+1

**Comment by adrienkohlbecker** [comment]
+1

**Comment by crquan** [comment]
+1

**Comment by indigodp** [comment]
+1

**Comment by trukhinyuri** [comment]
+1

**Comment by Bondza** [comment]
+1

**Comment by crquan** [comment]
+1

**Comment by shanielh** [comment]
+1

**Comment by rschmukler** [comment]
+1

**Comment by KevinGreene** [comment]
Working on this now. The ulimits argument in docker-py takes a list of dictionaries, with the key "name", optional keys "soft" and "hard", e.g. `{'name': 'nofile', 'soft': 8096, 'hard': 16192}`

The expected YAML entry in a Docker compose file for this would be:

```yaml
ulimits:
  nofile:
    soft: 8096
    hard: 16192
```

Correct?

**Comment by divideby0** [comment]
That sounds good to me, though I'm not certain if the existing YAML parse supports deeply nested values. If no, I think the alternative would also be acceptable:

```yaml
ulimits:
  nofile: "8096:16912"
```

Note that the latter syntax more closely matches what's actually provided to the Docker daemon, for example:

```bash
docker -d --default-ulimit nofile=8096:16912
```

So that might be the path of least resistance.

**Comment by dnephin** [comment]
@KevinGreene that sounds good to me

Thanks for picking this up! Let me know if I can be of any help

**Comment by KevinGreene** [comment]
Working locally - Should have a PR ready tonight after some documentation fixes
