### ISSUE TITLE
Should docker-compose be installed under /usr/local/bin?

### ISSUE THREAD

**Issue by liubin** [docker/compose#1323]
I'm using CentOS 7, If I install `docker-compose` under `/usr/local/bin`(the manual way), my `sudo docker-compose up` will fail.

How about install it under a more common folder like `/usr/bin`?

Thanks,
Bin Liu

**Comment by funkyfuture** [comment]
it's common (i guess for decades now) that distribution managed binaries/scripst are installed ro `/usr/bin` while manual installations and those by managers like `pip` go to `/usr/local/bin/`.

propably you should rather look for a solution that seems specific to CentOS. you could also create a link or configure sudo in regards to your needs.

**Comment by kojiromike** [comment]
This probably falls under sudo's `env_reset` feature – you can whitelist `PATH` using `env_keep` so that sudo will keep your path when executing, then it will see /usr/local/bin.

**Comment by liubin** [comment]
Thanks all, I think modify sudo's config will resolve this issue, close it.

**Comment by jdmarshall** [comment]
I know on OS X the docker binary ends up in /usr/local/bin, but if we could all agree on where every file should go we'd only need about half as many linux distributions as we have...  

I feel like the best answer is 'figure out where docker is and put it in the same spot'

**Comment by kojiromike** [comment]
@jdmarshall [FHS](http://www.linuxfoundation.org/collaborate/workgroups/lsb/fhs) is intended to solve that problem, but even it allows for the distro to have one place for official packages and a second place for unofficial ones. In this case, `docker-compose` should go in /usr/bin if it's official, and /usr/local/bin if it's locally installed/unofficial.

**Comment by sgarwang** [comment]
I tried below and get both docker and docker-compose updated:
Docker version 1.8.2, build 0a8c2e3
docker-compose version: 1.4.0
https://media-glass.es/2015/06/28/update-to-centos7-docker-install-one-liner/
