### ISSUE TITLE
Size of Docker directories keeps on growing

### ISSUE THREAD

**Issue by epintos** [docker/compose#1327]
Im trying docker compose for Rails projects with the following script to run rspec tests:

```bash
> docker-compose build
> docker-compose run web rake db:test:prepare
> docker-compose run web rspec

> docker-compose stop
> docker-compose rm --force
> docker stop `docker ps -a -q -f status=exited`
> docker rm -v `docker ps -a -q -f status=exited`
> docker rmi `docker images --filter 'dangling=true' -q --no-trunc`
```

I'm executing the last commands so I remove every container and dangling image to free space. After some builds I notice that the `/var/lib/docker/aufs`, `/var/lib/docker/volumes` and `/var/lib/docker/devicemapper` directories keeps on growing. I'm running this for a few different projects. What am I doing wrong?

**Comment by dnephin** [comment]
Might be related to https://github.com/docker/docker/issues/6354#issuecomment-114688663

**Comment by dnephin** [comment]
Some things to try out: 
* use `--rm` with `docker-compose run` to make sure one-off containers are removed
* try the new `docker-compose down` in 1.6 to remove images

**Comment by dnephin** [comment]
No response from OP, and #53 should cover this, so closing.
