### ISSUE TITLE
docker-compose.yml should support the --pid option

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1328]
https://docs.docker.com/reference/run/#pid-settings-pid

This would make it possible to run mesos-slave with Compose: http://mail-archives.apache.org/mod_mbox/mesos-user/201504.mbox/%3CA0B336D2-387E-4E86-BB7B-7B7B3E5FC10C@adobe.com%3E

Ref #754

**Comment by aanand** [comment]
Is this covered by https://github.com/docker/compose/pull/1011?

**Comment by bfirsh** [comment]
oh yay
