### ISSUE TITLE
How do I do cluster management with compose?

### ISSUE THREAD

**Issue by lvh** [docker/compose#1330]
All of the examples I have found of compose use simple databases operating with a single node, e.g. redis or postgres. If I want to use something clustered like Riak or Cassandra, and I want a "realistic" setup (single physical node, but still), I would be scaling up to 5 or so nodes. Those nodes should be informed of each other's existence to form a cluster. [docker-riak](https://github.com/hectcastro/docker-riak), for example, has a Makefile exposing some of those cluster operations. How does that work in compose's world? Am I supposed to create a different Docker image that uses a well-known service discovery endpoint, or something?

**Comment by dnephin** [comment]
It doesn't work yet.  The new docker networking support will handle it. You can follow the compose side of it here #1676.
