### ISSUE TITLE
No Docker Compose in Wheezy

### ISSUE THREAD

**Issue by adminrezo** [docker/compose#1342]
I use docker under Debian Wheezy.
My Debian is up to date and I don't know why I don't have docker-compose available.

uname -a :
Linux hypvm2 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt4-3~bpo70+1 (2015-02-12) x86_64 GNU/Linux

docker --version :
Docker version 1.6.0, build 4749651

Thanks in advance

**Comment by vdemeester** [comment]
I could be wrong but, docker-compose is not distributed in the same package as docker and is probably not packaged for debian. You would have to install it manually.

**Comment by adminrezo** [comment]
Yes you're right, I did it with pip last time.
Thx!

**Comment by dnephin** [comment]
Great! Sounds like you've resolved your issue, I'm going to close it.  Feel free to re-open if you feel this is still an issue.
