### ISSUE TITLE
Only recreate containers whose configuration needs updating

### ISSUE THREAD

**Issue by aanand** [docker/compose#1345]
Currently, `docker-compose up` deletes and recreates every container, so as to make sure any changes to `docker-compose.yml` have been picked up. Instead, it should inspect container configuration to see if they *need* recreating, and do the minimum necessary.

**Comment by dnephin** [comment]
Would this mean that if a container had changed state in some way (ex: wrote any files to a non-volume directory), the old container would be started instead? For testing/CI this wouldn't be ideal, so a way to preserve the existing behaviour might be nice.  Best practice in those situations would be to `docker-compose rm` before running the test suite anyway, but maybe still worth calling out that this isn't backwards compatible in some situations.

**Comment by viranch** [comment]
This would be a problem if I am binding a config directory in the container and I just want to recreate the container due to config updates. There will be essentially no changes in container config but the bound volume will have changed content.

**Comment by aanand** [comment]
@viranch In that case - where you don't actually need a new container, you just want to restart the process - `docker-compose restart` would be the appropriate command.

**Comment by viranch** [comment]
Right - fair enough.

**Comment by TomasTomecek** [comment]
How do you inspect that configuration for particular container has changed?

**Comment by aanand** [comment]
@TomasTomecek It's implemented in #1399 - we [add a label to each container](https://github.com/aanand/fig/blob/e5d8447f063498164f12567554a2eec16b4a3c88/compose/service.py#L506-L511) with a hash of the image and service config and [compare hashes](https://github.com/aanand/fig/blob/e5d8447f063498164f12567554a2eec16b4a3c88/compose/service.py#L326-L339) when checking for staleness.
