### ISSUE TITLE
Unstable output from querying containter environment variables 

### ISSUE THREAD

**Issue by jianghaitao** [docker/compose#1364]
According to http://docs.docker.com/compose/env/, one can query the environment variables available to a given service by doing docker-compse run <service> env. I noticed that it is, however, not stable, as one can see from examples below:

    $ docker-compose run redis env | grep redis_1
    $ docker-compose run redis env | grep redis_1
    REDIS_1_NAME=/composepythonwebserver_redis_run_41/redis_1
    COMPOSEPYTHONWEBSERVER_REDIS_1_NAME=/composepythonwebserver_redis_run_41/composepythonwebserver_redis_1
    $ docker-compose run redis env | grep redis_1
    REDIS_1_NAME=/composepythonwebserver_redis_run_42/redis_1
    COMPOSEPYTHONWEBSERVER_REDIS_1_NAME=/composepythonwebserver_redis_run_42/composepythonwebserver_redis_1

Notice that 1st execution resulted no output. The test example was based on http://docs.docker.com/compose/

**Comment by jianghaitao** [comment]
I found that following command behave the the way, i.e. occasionally no result.
    docker-compose run redis cat /etc/hosts | grep redis

**Comment by aanand** [comment]
See #658 - hopefully fixed by https://github.com/d11wtq/dockerpty/pull/36, which will go in the next release.

**Comment by aanand** [comment]
Closing as it's a duplicate.
