### ISSUE TITLE
Support docker-py 1.2.1

### ISSUE THREAD

**Issue by linlinlinlin** [docker/compose#1366]
docker-py 1.2.1 have been released yesterday. 

How could we help to test it is work with compose 1.2 ?

**Comment by aanand** [comment]
1.2.0 and 1.2.1 seem to be missing from PyPi, but I'm already confident that Compose will work with them - several PRs (such as #1269) are using them via Git URL.

**Comment by dnephin** [comment]
We're on 1.3.1 now, so we can close this
