### ISSUE TITLE
Document how to set Swarm constraints and affinity in SWARM.md

### ISSUE THREAD

**Issue by aanand** [docker/compose#1379]
As of https://github.com/docker/swarm/pull/673, this is done with labels, not environment variables.

**Comment by thaJeztah** [comment]
You may need to check this; if docker-compose talks to the Swarm API, not the Docker API, see the description of the PR;

> With this PR, *you still use -e to pass constraints or affinities*, but swarm store those inside a labels

Must admit, this is a bit confusing :)

**Comment by aanand** [comment]
Oh goodness, that *is* confusing. Well spotted. @vieux - are environment variables still the "proper" way to set constraints and affinity?

**Comment by vieux** [comment]
@aanand yes, the cli is too restrictive on the `--label`, `-e` is more flexible so we keep using this.

**Comment by thaJeztah** [comment]
@vieux please open an issue in Docker if you have suggestions on improving the CLI to make it more useful :)
