### ISSUE TITLE
recreate container when image or dockerfile is updated

### ISSUE THREAD

**Issue by TomasTomecek** [docker/compose#1383]
I'm using `compose` during development and I find it _super_ useful. The only thing is that it takes so long to rebuild my environment (app, db, redis, worker, worker management). My workflow is, that I update one of the services and want to do `up` right away. Unfortunately `compose` recreates all containers, not just the one I updated.

Do you think it would make sense, if:
 * compose would recreate containers which have updates images
 * compose would rebuild images which have updates dockerfiles

I'll gladly provide patch for this.

**Comment by aanm** [comment]
@TomasTomecek I had the same idea a while back... See this https://github.com/docker/docker/issues/11024

**Comment by TomasTomecek** [comment]
@aanm you're right, idea is the same; except that I would like to have this implemented in compose, not engine.

**Comment by aanand** [comment]
I agree this would be good; for now, you can explicitly name which services you want to recreate:

    # recreate only 2 services
    $ docker-compose up -d --no-deps SERVICE1 SERVICE2

    # stream logs for all of them
    $ docker-compose logs

**Comment by TomasTomecek** [comment]
Aha, `--no-deps`, that's what I missed.

@aanand so if I created patch for this, would you merge it? (I would probably create new option for `up`)

**Comment by aanand** [comment]
Let me make sure I understand what you're proposing.

> compose would recreate containers which have updates images

This part I think I understand: if `db` has `image: postgres:latest`, then we ask the Docker API what the current image ID is for `postgres:latest`. If there are `db` containers with a different image ID, we recreate them.

This is sensible, but I'm basically already working on this as part of #1345. It'll eventually be the default behaviour of `docker-compose up`, although to begin with will probably be behind an experimental command-line flag.

> compose would rebuild images which have updates dockerfiles

This is the part that needs better specifying. How will you detect that the Dockerfile has changed? Are any of the concerns raised about @aanm's proposal in https://github.com/docker/docker/issues/11024 addressed?

**Comment by TomasTomecek** [comment]
Compose would `stat` the dockerfile and if last modification is newer than creation time of the image, it would be recreated.

**Comment by dnephin** [comment]
You would need to get the modified time of every file in the build context as well.

**Comment by TomasTomecek** [comment]
That's true. Maybe it could be configurable.

**Comment by FelikZ** [comment]
Currently when I am do `docker-compose -f dev.yml -p project up -d` it said that containers `recreated`. I am expecting them to be recreated from NEW images but is just recreate them from old one.

Is there efficient way to achieve that without doing `stop` and then `rm -f -v` and then `up`?

Thanks.

**Comment by prologic** [comment]
Hmm can't re just rebuild the image anyway and let the Docker cache take care of things? If nothing changed all instructions will hit the cache and the image will be unchanged.

**Comment by manojlds** [comment]
+1 to @prologic

**Comment by sharhalakis** [comment]
I'd suggest keeping the dockerfile, or a hash of it, somewhere, and comparing against that instead of using a plain stat()... if possible.

**Comment by dnephin** [comment]
Issue #12 or #693 should allow for a way to build on `up`.

Any improvements to the build need to be implemented in the engine (or possible the proposed builder that is being extracted from the engine).  Once there is upstream support we can use it to conditionally build when the context has changed.

**Comment by shanewow** [comment]
+1

**Comment by plavreshin** [comment]
+1 would be very useful

**Comment by dnephin** [comment]
Does `up --build` (#2601) solve this?

**Comment by TomasTomecek** [comment]
@dnephin I think so. Let's close this. I have to say that UX when respinning services improved greatly in last year.
