### ISSUE TITLE
Clarify extends-documentation

### ISSUE THREAD

**Issue by funkyfuture** [docker/compose#1385]
i think it'd be a good idea to define what *local* and *original* refer to in the [paragraph](https://docs.docker.com/compose/extends/#adding-and-overriding-configuration) related to the paragraph above. or use that same terminology there. though i can think of clearer distinctions than *local* vs. *original*. what about *extended* and *extending*? with a code-style-definition:

```yaml
extending:
  extends: extended
```

also, there's a sentence that may be good in a brochure, but rather disturbing in a technical documentation:

> You can extend indefinitely.

i mean, that would need unlimted storage for configuration. or we have that yet? :rocket:

**Comment by funkyfuture** [comment]
oh, and it's not noted that `net` is not allowed in an extended service.

**Comment by aanand** [comment]
I deliberately avoided "extending" and "extended" because they sound so similar, which to me just adds to the confusion. @moxiegirl?

While I'm not at all worried about that sentence "disturbing" people, it's not really necessary. All we need to do is make it clear that we don't place a limit on how many times you can extend. Perhaps:

> You can extend a service which itself extends another service, and so on. Circular references are not supported, though, and `docker-compose` will return an error if it encounters one.

Good point about `net` - we should add that.

**Comment by funkyfuture** [comment]
since i tend to visualize things i perceive, reading that part made me upset because imagining something running endlessly that matches the concept of a Turing-machine is, well, distrubing to me. so, for some neurological configurations that sentence may need a spoiler warning. ;-) or pragmatically with a subordinate clause (is there a nicer term for that in english?) like "supposed you have endless computing capacities".

i see the point of extend*-similarity. next proposals:

    derived:
       extends: base

    inherited:
       extends: parent

    inherited:
       extends: super  # nah

**Comment by moxiegirl** [comment]
@aanand I think this page is bit awkward.  The example is right in the middle of the reference material which is an awkward placement.  You might want to consider splitting this into two pages:

* Extend compose services
* Basic extends tutorial

Looking at the tutorial, I think it can be improved structurally to make it more usable.  

Earlier in the page you use "locally" and then down the page "local" is used.  Typically, I'm used to seeing _local_ vs. _remote_ in networked app situations.  You also seem to use "local" vs. "production"...yet later down the page is the first reference to "original".

**Summary:**
It appears there is  core concept behind extens  of the _local_ configuration versus the _xxx_ configuration; where xxx is some opposing term to TBD.  If that is true, the concept should be explained in the first paragraph of this article. Then, use the terms consistently throughout the document.

Ping me back if this needs further clarification. I'm afraid I've got a priority project or I'd do a rewrite for you and in testing probably come up with better suggestions.

**Comment by dnephin** [comment]
We reworked this a bit with the 1.5.0 release, is this still an issue?

**Comment by funkyfuture** [comment]
maybe it's because my mothertongue isn't english and i'm used to a dichotomy of `local` / `remote` and still sense irritation with `local` / `original`. anyhow, the current elaboration is comprehensible.
