### ISSUE TITLE
Perform actions in parallel

### ISSUE THREAD

**Issue by iMerica** [docker/compose#1395]
Hey guys,

I just want to gauge interest in this before I start working on it. Is this something others would find useful?

My project's yml file has grown so big that `docker-compose up -d` and `docker-compose stop` take about a minute so this would be super awesome if once the parent containers are started/stopped, the child containers would start/stop asynchronously.

**Comment by aanand** [comment]
This makes a lot of sense, yes. A lot of stuff Compose does could be parallelised. Off the top of my head:

1. Container creation is order-dependent, but chunks of it could still be done in parallel - e.g. if both `web` and `worker` depend on `db`, then once `db` is created, `web` and `worker` can be created in parallel.

2. Container starting is also order-dependent in the same way.

3. Container stopping/killing should be completely order-independent - if it's all going down, it doesn't matter what order we do it in.

4. Container deletion should also be completely order-independent.

**Comment by cmoro-deusto** [comment]
+1

**Comment by bfirsh** [comment]
Replaced by https://github.com/docker/compose/issues/1652
