### ISSUE TITLE
Dockerfile ADD relative path when initiated from docker-compose build

### ISSUE THREAD

**Issue by jjoubert** [docker/compose#1398]
Please consider the example where I have a Dockerfile in a specific directory including an ADD operation with a relative path to the target.  
Something like this:  /a/b/c/Dockerfile:

    FROM base
    ADD ../b/file.txt

This image builds correctly if I just run docker build in the same directory as the Dockerfile (/a/b/c/).

Now, let's say I have a docker-compose.yml file in a higher-level with a relative path to the Dockerfile:  /a/docker-compose.yml:

    myimage:
      build: ./b/c/

It seems to me that if I run (up) on this docker-compose.yml, the build context path for the Dockerfile is the path of the docker-compose.yml, in other words, the relative path to "file.txt" in my Dockerfile does not resolve correctly.
Is this expected?  Is there a way for me to override this behaviour without re-arranging the structure?  In other words, force the build context path to be the path of the Dockerfile regardless of where the docker-compose.yml file is?

My current situation is that the top-level docker-compose actually reference a number of lower-level Dockerfiles.

**Comment by aanand** [comment]
Paths in the Dockerfile should always be relative to the Dockerfile. I'm very surprised to hear that you're seeing different behaviour, because given how it works I didn't think that was possible.

Could you post a minimal failing case?

**Comment by jjoubert** [comment]
I did some more testing.  The problem seems to be in fact with the docker image building, not necessarily docker-compose.  It looks like docker has a problem including files with ADD using a relative path outside the current Dockerfile directory (parent):

This is the Dockerfile:

    /b/c$ cat Dockerfile
    FROM busybox:latest
    ADD ../file.txt /tmp/

The file exists from the current relative path:

    /b/c$ ls ../file.txt
    ../file.txt

But the build fails:

    /b/c$ sudo docker build -t issue1398 .
    Sending build context to Docker daemon 2.048 kB
    Sending build context to Docker daemon 
    Step 0 : FROM busybox:latest
     ---> a9eb17255234
    Step 1 : ADD ../file.txt /tmp/
    INFO[0000] ../file.txt: no such file or directory

**Comment by Kosta-Github** [comment]
See docker documentation (https://docs.docker.com/reference/builder/):
```
Warning Avoid using your root directory, /, as the root of the source repository. The docker build command will use whatever directory contains the Dockerfile as the build context (including all of its subdirectories). The build context will be sent to the Docker daemon before building the image, which means if you use / as the source repository, the entire contents of your hard drive will get sent to the daemon (and thus to the machine running the daemon). You probably don't want that.
```
and
```
The <src> path must be inside the context of the build; you cannot ADD ../something /something, because the first step of a docker build is to send the context directory (and subdirectories) to the docker daemon.
```

**Comment by jjoubert** [comment]
Yeah, thanks.. I missed that.  Sorry about posting this issue here under docker-compose.  My mistake.

**Comment by marcellodesales** [comment]
# Dir Structure

Suppose you have the following dir structure
```
    ./docker-compose.yaml
    ./all-runners/
            /start.sh
            /runner-A/Dockerfile
            /runner-B/Dockerfile
            /runner-C/Dockerfile
```
* I  had a requirement where all Dockerfiles share the same file
* The top-level docker-compose is the driver of all the builds

# Dockerfile

It `ALWAYS` will load from its relative path, having the current dir of itself as the `local` reference to the paths you specify.

```dockerfile
    COPY start.sh /runtime/start.sh
```
# Docker-compose

*  The real trick is here. The context you want to set is the directory where your main content is located.
* In this example, your `shared` context dir is the `runtime` dir.
  * Imagine all the files under this dir being copied over to a dir called `context`. 
  * Now imaging you can just specify the Dockerfile that you want to copy to  that same dir. You can specify that using `dockerfile`.

The `docker-compose.yml` is as follows

```docker-compose
    version: "3.3"
    services:
      
      runner-A
        build:
          context: ./all-runners
          dockerfile: ./runner-A/Dockerfile
    
      runner-B
        build:
          context: ./all-runners
          dockerfile: ./runner-B/Dockerfile
    
      runner-C
        build:
          context: ./all-runners
          dockerfile: ./runner-C/Dockerfile
```
* Since the context is set to `all-runners`, the file `start.sh` will be reuse by each individual Dockerfile specified by the path in `dockerfile`.
* You get the same effect as in the parent dir, in a more organized way

**Now your build works with files outside the dir of your `Dockerfile`.** The result is just the same when you do the proper mapping!

Happy Dockering 🐳!

**Comment by aatmmr** [comment]
Thanks @marcellodesales - This a neat solution that works like charm and solved my issue 👍

**Comment by cropse** [comment]
That's a pretty nice solution for my years inconvenient, thanks @marcellodesales, just remind here, don't forget to add `.dockerignore` for the unnecessary file to avoid increasing build time.

**Comment by dyapasrikanth** [comment]
> # Dir Structure
> Suppose you have the following dir structure
> 
> ```
>     ./docker-compose.yaml
>     ./all-runners/
>             /start.sh
>             /runner-A/Dockerfile
>             /runner-B/Dockerfile
>             /runner-C/Dockerfile
> ```
> 
> * I  had a requirement where all Dockerfiles share the same file
> * The top-level docker-compose is the driver of all the builds
> 
> # Dockerfile
> It `ALWAYS` will load from its relative path, having the current dir of itself as the `local` reference to the paths you specify.
> 
> ```dockerfile
>     COPY start.sh /runtime/start.sh
> ```
> 
> # Docker-compose
> * The real trick is here. The context you want to set is the directory where your main content is located.
> * In this example, your `shared` context dir is the `runtime` dir.
>   
>   * Imagine all the files under this dir being copied over to a dir called `context`.
>   * Now imaging you can just specify the Dockerfile that you want to copy to  that same dir. You can specify that using `dockerfile`.
> 
> The `docker-compose.yml` is as follows
> 
> ```yaml
>     version: "3.3"
>     services:
>       
>       runner-A
>         build:
>           context: ./all-runners
>           dockerfile: ./runner-A/Dockerfile
>     
>       runner-B
>         build:
>           context: ./all-runners
>           dockerfile: ./runner-B/Dockerfile
>     
>       runner-C
>         build:
>           context: ./all-runners
>           dockerfile: ./runner-C/Dockerfile
> ```
> 
> * Since the context is set to `all-runners`, the file `start.sh` will be reuse by each individual Dockerfile specified by the path in `dockerfile`.
> * You get the same effect as in the parent dir, in a more organized way
> 
> **Now your build works with files outside the dir of your `Dockerfile`.** The result is just the same when you do the proper mapping!
> 
> Happy Dockering 🐳!

How we can access current directory files in runner-A/Dockerfile ?

`runner-A/Dockerfile`
```
COPY start.sh /opt
COPY runner-A/other.sh /opt
```
