### ISSUE TITLE
Use labels to identify images instead of name convention

### ISSUE THREAD

**Issue by dnephin** [docker/compose#1403]
Similar to #1356 and #1066 but for image names.

I've looked over the docker api reference, and the docker-py docs and neither include details about how to add labels to images (other than `LABEL` in the Dockerfile , which doesn't help us here). 

It's possible the API already supports this, and the docs are just missing. I haven't had a chance to look through the docker source yet. Does anyone know offhand if this is already supported?

**Comment by aanand** [comment]
I was thinking this today. I don't know that there's a way to do it, which is annoying.

**Comment by thaJeztah** [comment]
Hm good point changes for labels are here https://github.com/docker/docker/pull/9882/files. I know the initial implementation was deliberately kept simple to try and (finally) get the feature in, with the intent to add features in a later stage when needed.

I don't think (not sure) it's implemented, haven't taken a proper look at the code, (@ibuildthecloud ?), but it would be nice to get it in before the docker 1.7 release so that compose can benefit from that.

Feel free to open an issue if this feature is not there, don't think there will be much discussion around it, it seems quite trivial to have it :)

**Comment by vdemeester** [comment]
Well, according to this : https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L502 and this https://github.com/docker/docker-py/blob/master/docker/client.py#L468, it is already supported by docker-py (although not well documented and such).

So it's definitely possible to work on this :).

**Comment by thaJeztah** [comment]
@vdemeester but that's on *containers*, iiuc? The issue here is building an *image* and adding labels to the image without modifying the Dockerfile

**Comment by vdemeester** [comment]
@thaJeztah yeah.. read and answered too quickly :cry:

**Comment by thaJeztah** [comment]
@vdemeester np!

**Comment by vdemeester** [comment]
I've create an Issue in docker docker/docker#13178 that would help with that I think.

**Comment by thaJeztah** [comment]
@vdemeester thanks! I meant to do so, but didn't come to it :)

**Comment by dnephin** [comment]
After reading over https://github.com/docker/docker/pull/13412 I realize this is actually a much larger change than I expected. Having to add layers that aren't part of the `Dockerfile` is likely to require a lot of discussion first.

I'm starting to think that maybe building images shouldn't be part of the `compose` domain. We could support the existing naming convention for now, but maybe we don't worry about this at all, and instead  document other tools that can be used to build images for compose.

**Comment by thaJeztah** [comment]
I saw your thinking on some other issues, and (like you) never actually given that much thought.

In a way, it makes sense that building images is not part of orchestration, especially if Swarm is taken into account, where it's undetermined at which node the built image ends up.

docker-compose **does** make it easy to build an image and specify all required parameters, basically acting as a Makefile. Given the discussion around moving the builder "client side" in Docker, perhaps some tooling around that could be taken into account there, but that's getting off-topic.

**Comment by dnephin** [comment]
I created #1455 for further discussion

**Comment by vdemeester** [comment]
@dnephin note that adding a layer it is the naive path I choose to handle this, but yeah I think it will need a *lot* of discussion to say the least on that one. The other path, may more clean, would be the add the label on the last commit (and thus no additionnal layer).

**Comment by dnephin** [comment]
I think we're going to go with #2092 instead. This isn't possible with labels anyway (at least at this time).

**Comment by bfirsh** [comment]
Could always do labels too ;)

**Comment by dnephin** [comment]
Unless docker is planning on adding support for labels external to a `Dockerfile`, we can't really.  That's the roadblock we hit when we looked into implementing this previously.  We need some way to attach metadata to the image from outside of the `Dockerfile`, but that is incompatible with the design of `Dockerfile`.
