### ISSUE TITLE
Container stops immediately with docker-compose but runs fine with Docker

### ISSUE THREAD

**Issue by AlexZeitler** [docker/compose#1409]
I'm using the following `Dockerfile`

```
FROM microsoft/aspnet
ADD . /app
WORKDIR /app
RUN ["dnu", "restore"]

EXPOSE 5004
```

And this `docker-compose.yml` with Docker 1.6.0 and docker-compose 1.2.0

```
web:
  build: .
  command: dnx . kestrel
  ports:
   - "80:5004"
```

When running `docker-compose up -d` I get the following output:
```
Recreating aspnet5_web_1...
```
As said, the container is started but also stopped immediately.

`docker ps -a` results in

```
CONTAINER ID        IMAGE                       COMMAND                CREATED              STATUS                          PORTS               NAMES
16f2c49a9871        aspnet5_web:latest   "dnx . kestrel"        About a minute ago   Exited (0) About a minute ago                       aspnet5_web_1   

```

`docker logs 16f2` shows normal output without errors.

As said, the container works fine running it using plain Docker.

On the other hand, the official MongoDb image also works fine with docker-compose and running a container based on it, it doesn't stop.

**Comment by AlexZeitler** [comment]
Just noticed an interesting difference: when running the container using plain Docker, when running `docker ps`, in the "column" `PORTS` there's an entry `0.0.0.0:80->5004/tcp` while (as you can see above) when using docker-compose this column is empty.

**Comment by irony** [comment]
I had the same error - it is because docker compose (and other automation services like tutum) sends an extra CR/LF which will close down the docker container. This should be fixed in Microsoft/Hosting (it will require ctrl-c) soon. Until then - use this hack in your dockerfile:

ENTRYPOINT sleep 10000000 | dnx . kestrel

**Comment by AlexZeitler** [comment]
Thanks, this did the trick! :+1:

**Comment by b-pos465** [comment]
I got the same problem in the project, Im currently working on. I will now try to check against a certain input, not just CR/LF. Why does docker-comopose sends this CR/LF?
