### ISSUE TITLE
Invalid repository name (compose2_MongoConnector), only [a-z0-9-_.] are allowed

### ISSUE THREAD

**Issue by Garito** [docker/compose#1412]
Hi!
Could someone explain why I'm getting this error?

The compose section for the container:
MongoConnector:
  build: ./conf/mongoconnector/
  links:
    - es
    - MongoDB
  command: mongo-connector -m MongoDB:27017 -t es:9200 -d elastic_doc_manager

The Dockerfile at ./conf/mongoconnector/
FROM ubuntu
MAINTAINER Garito garito@gmail.com

RUN apt-get -y update
RUN apt-get -y install python
RUN apt-get -y install python-pip

RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/

RUN pip install -r requirements.txt

The requirements.txt file at ./conf/mongoconnector:
mongo-connector

It seems to try to use image instead of build?

**Comment by aanand** [comment]
Uppercase letters aren't allowed in service names. Try renaming it to `mongoconnector`.

**Comment by Garito** [comment]
Yeah, it worked but
I have a compose file with 7 containers, 4 of them are up and running with uppercase letters in their names
So seems that the issue is only with builded containers not those who run official images

is this true?

**Comment by aanand** [comment]
Yes, looks like it. We allow uppercase letters in service names, but Docker doesn't allow them in image names. Because the image name is based on the service name, it contains uppercase letters, and Docker refuses to create it.

We shouldn't allow uppercase letters in service names.

**Comment by Garito** [comment]
If it have a pattern is good enought to me

Thanks a lot!!!
