### ISSUE TITLE
docker-compose ps suggestions

### ISSUE THREAD

**Issue by botchagalupe** [docker/compose#1414]
Currently the docker-compose ps command is limiting from a trouble shooting perspective.  Here are a few suggestions...

1) There should be a --no-wrap option or move to the ps model using --no-trunc.  IMHO the ascetics of the wrapping column output are not much better than a full line wrap output.  The former makes it hard for a debugger where they need to cut and paste parts of the output.  

2) The short CID should be in the default ps output. 

3) Some additional meta might be nice (e.g., up time and image name).  Otherwise the user's might be straddling between the docker ps and the docker-compose ps commands... 

3) Some more meta

**Comment by djmaze** [comment]
+1 Maybe have a look at [what fleetctl allows](https://github.com/coreos/fleet/blob/master/fleetctl/list_units.go#L38-L45) in order to make the output configurable. Also, it would often be helpful to see the container IPs in the list.

**Comment by djmaze** [comment]
+1 Maybe have a look at [how fleetctl allows to make the output configurable](https://github.com/coreos/fleet/blob/master/fleetctl/list_units.go#L38-L45) . Also, it would often be helpful to see the container IPs in the list.

**Comment by Andersmholmgren** [comment]
Yeah this is very annoying when you are screen scraping the output

**Comment by dnephin** [comment]
Thanks for the feature request.  We've had a bunch of different requests for ps, so I'm going to aggregate them all into #2369 so it'll be easier to design a solution that works for most of them.

I think we'd like to support a json output so that there's less of a need to screen scrape the output.

**Comment by Andersmholmgren** [comment]
Love the JSON idea
