### ISSUE TITLE
Add upgrading instructions to install docs

### ISSUE THREAD

**Issue by aanand** [docker/compose#1425]
Following @moxiegirl's recommendations in https://github.com/docker/compose/pull/1356#issuecomment-102820776:

* include an Upgrade Compose section in the compose release notes with instructions
* add an Upgrade Compose section to the installation docs

**Comment by fredlf** [comment]
I agree with this approach, though I would suggest just a link in the release notes to a complete "Upgrade" section in the Install doc.

**Comment by aanand** [comment]
Sounds good.
