### ISSUE TITLE
migrate_to_labels or --migrate-to-labels?

### ISSUE THREAD

**Issue by albers** [docker/compose#1426]
#1356 introduced some uncertainty about how to convert containers to the new format.
The help message says

> `migrate_to_labels`  Recreate containers to add labels

The error message is

> If you'd like compose to use this container, please run `docker-compose --migrate-to-labels`

**Comment by albers** [comment]
I was also unsuccessful testing this feature. I could build and successfully run the tests, but executing the command failed:

    root@docker2:~/james# docker-compose --version
    docker-compose 1.3.0dev
    root@docker2:~/james# docker-compose migrate_to_labels
    No such command: migrate_to_labels

    Commands:
      build              Build or rebuild services
      [...]
      migrate_to_labels  Recreate containers to add labels

I'm new to python development, so this might be due to an error on my side.

**Comment by gomex** [comment]
I confirm this bug.

# docker-compose migrate_to_labels
No such command: migrate_to_labels

# docker-compose --migrate-to-labels
Fast, isolated development environments using Docker.

Usage:
  docker-compose [options] [COMMAND] [ARGS...]

**Comment by albers** [comment]
@dnephin The `migrate_to_labels` command is not recognized as such because in https://github.com/docker/compose/blob/master/compose/cli/main.py#L492 the help message is missing.

**Comment by albers** [comment]
@dnephin created #1430
