### ISSUE TITLE
Why --rm may not work ?

### ISSUE THREAD

**Issue by Agasper** [docker/compose#1429]
docker-compose 1.2.0
Docker version 1.6.2, build 7c8fca2

docker-compose.yml
>service:
>  build: .
>  command: echo "Test"

Command: **sudo docker-compose run --rm service**

After that i did: **sudo docker ps -a**
And...

CONTAINER ID | IMAGE | COMMAND | CREATED | STATUS | PORTS | NAMES
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
39c586829ab1 | mega_service:latest | "echo Test" | 4 seconds ago | Exited (0) 3 seconds ago | mega_service_run_2

No `log.info("Removing %s..." % container.name)` was in the console. It fell into 
dockerpty.start(project.client, container.id, interactive=not options['-T'])
and didn't reach next line.

**Comment by heidarxvpn** [comment]
Probably same as this https://github.com/docker/compose/issues/1424

**Comment by josephpage** [comment]
Since issue is probably fixed since docker-compose 1.3.0.
