### ISSUE TITLE
docker-compose logs - timezone problem

### ISSUE THREAD

**Issue by FoxKyong** [docker/compose#1431]
I found a problem with timezone when viewing logs with 'docker-compose logs'. I have added
`
 volumes:
    - /etc/localtime:/etc/localtime:ro
`
into docker-composy.yml as I found as best solution. This works. Date and time is right on both host and in the container. It's bad only when I am viewing logs with docker-compose logs and I didn't find anything to it on google. Just for timezone inside of containers which works fine for me.

**Comment by dnephin** [comment]
The time reported by the logs is the time according to the docker daemon, so I don't think fixing the container timezone matters.

Are you running boot2docker (or `docker-machine`) ? Maybe the virtualbox host has the wrong timezone?
