### ISSUE TITLE
Unable to show logs from just a single service

### ISSUE THREAD

**Issue by stephenlawrence** [docker/compose#1434]
Running the latest build from master branch:

When I try to `docker-compose logs MYSERVICE` I get the entire stack of services log output.

**Comment by dnephin** [comment]
Oops, I think this a bug with the implementation of `Project.containers()` when using labels. `service_names` is ignored.  I don't think the filter supports `OR` operations, so I think we'll need to filter the list of containers by service_names (and add a test for it).
