### ISSUE TITLE
BUILD leaves old untagged image

### ISSUE THREAD

**Issue by Agasper** [docker/compose#1435]
How to prevent BUILD command to leave old untagged image for service ?

>REPOSITORY                 TAG                 IMAGE ID
>service_image   latest              b91d042e6279

**sudo docker-compose build image**

>REPOSITORY                 TAG                 IMAGE ID
>service_image   latest              9ea7fae84122
>\<none\>                     \<none\>              b91d042e6279

Is it expected behavior ?

**Comment by dnephin** [comment]
These are just intermediate layers for your image, it is expected. `docker build` does the same thing.  They will be cleaned up when the tagged images are removed.

**Comment by pgcalixto** [comment]
Everytime I execute `docker-compose up --build`, it creates a new `<none>`-tagged image, with exactly the same size as the container I'm running with the tag I need.
I need to run with the `--build` parameter, since I'm modifying the Dockerfile or files I need in my container all the time, but for N times I run it with `--build`, it creates 1 image with the tag I defined, and N `<none>`-tagged images. Since this takes a lot of storage when running Docker Compose, I guess it's an issue, right?

**Comment by dnephin** [comment]
This is not different than running `docker build` and overriding a tag. 

I would recommend using either https://github.com/yelp/docker-custodian or https://github.com/spotify/docker-gc to cleanup old untagged images.  It is not really safe for Compose to go deleting the image.

**Comment by soneji** [comment]
@dnephin While I understand it is not safe, in a development environment, it can prove extremely useful. I often end up with 10s of untagged images after many builds of an image. A `docker image prune` would remove other useful images that I have and do not wish to redownload later.

Would it be possible to add a flag to compose to allow compose to delete the old images when running `docker-compose up -d --build` such as `docker-compose up -d --build --remove-old`? 

The documentation can explain to the user this is an unsafe flag.

**Comment by sharpvik** [comment]
This issue is closed unnecessarily. The `--remove-old` flag proposed by @Soneji is a great idea! I think you should seriously consider implementing it, especially considering that it won't be hard anyways.

**Comment by gabus** [comment]
We need this flag. Leaving dead images behind is not a way to go. Is there a ticket for this feature?

**Comment by caneman** [comment]
really need this flag, hope to see it soon.

**Comment by HumptyHans** [comment]
Would be a very useful addition to `docker compose up --build`.

**Comment by marcoautiero** [comment]
I support the --remove-old option, it would be a nice solution

**Comment by yarally** [comment]
+1

**Comment by dfyz011** [comment]
❔

**Comment by SahilPatel650** [comment]
+1

**Comment by Sladamos** [comment]
plz give --remove-old

**Comment by LokkiDog** [comment]
+1

**Comment by kwinso** [comment]
+1

**Comment by salmanhaider14** [comment]
+1 . Pls provide a flag or do this automatically that while running `docker compose up --build` it first removes the previous image (that's currently left as untagged or as <none>) and then make a new one.

**Comment by erikcik** [comment]
Wait why havent no one did this already?
