### ISSUE TITLE
Removing a container shows message that its removing all containers

### ISSUE THREAD

**Issue by stephenlawrence** [docker/compose#1436]
When I typed `docker-compose rm SERVICE`, I got a response back that said:

`Going to remove SERVICE1, SERVICE2, SERVICE3, etc...`

When I answered Yes to the prompt, it only deleted the original service I had requested to be removed. The message is mis-leading.

**Comment by dnephin** [comment]
This is with master? I think this is the same bug as #1434. They both call the function.

I'm going to close this issue since we can track the fix with #1434
