### ISSUE TITLE
Mark container not to start by default

### ISSUE THREAD

**Issue by robwithhair** [docker/compose#1439]
When you run `docker-compose up -d` by default all containers start.  It would be really handy to be able to mark one type of container not to start by default but only to start when named, such as `docker-compose up -d unit_test_runner` for example.  

This would mean a team of devs could use the `docker-compose up -d` command to start a development environment but without starting containers which are used for unit or functional testing unless they have dependencies to other containers.  Don't know if this could be tied into the `docker-compose scale` command so you specify an ideal number of containers to start and if you specify 0 then none get started by default unless they are depended on by another container or they are specified in the `up` command.

Thanks all, loving compose.  Keep up the good work.  Can't wait until swarm has automatic failover and inter-machine networking.  Gonna be awesome.

Rob

**Comment by robwithhair** [comment]
I get around this now by using several docker-compose files but it gets kinda long adding all the -f args to compose.

**Comment by kojiromike** [comment]
Is this proposal different from #697?

**Comment by robwithhair** [comment]
Similar. Perhaps different in the way that I propose the use of the scale number in order to specify which containers do not start up as default. For example, specifying five front and web containers to start up could be handy and specifying zero unit test runners, which would mean they only started when specified in the up command. 

I can append this to the other issue if you wish now I know there is already something similar to this.

Sent from my iPhone

> On 25 May 2015, at 23:02, Michael A. Smith <notifications@github.com> wrote:
> 
> Is this proposal different from #697?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--

**Comment by bfirsh** [comment]
Thanks for the suggestion! I've created an issue here to aggregate many similar suggestions: https://github.com/docker/compose/issues/1896
