### ISSUE TITLE
Better error reporting if no memory available

### ISSUE THREAD

**Issue by nickcodefresh** [docker/compose#1449]
Hi,

I tried running my container via docker-composer with a ```mem_limit: 2024m``` setting 

```
[tomcat@app-02 11:09:12 0 int PlaylistServiceBuild]$ docker-compose up
Recreating playlistservicebuild_configServer_1...
Cannot start container b91d396ae3c3ec49934be7e52716f0cddf317e917feec108dcd13e49b47cfeb1:  (exit status 1)
```

It turns out that the box didn't have enough free memory, but there's nothing to indicate this in the error code (and no logs). Would be better to throw a more descriptive error.

Nick

**Comment by dnephin** [comment]
This doesn't sound like a compose issue. I'd suggest looking up similar issues on the docker issue tracker.

**Comment by dnephin** [comment]
This is something that needs to be handled on the docker side, there are lots of things that could cause this error
