### ISSUE TITLE
Build only option?

### ISSUE THREAD

**Issue by ofir-petrushka** [docker/compose#1451]
We can either build or run the containers defined in docker-compose.
But can we have some images which are only for build since others relay on them but we don't want to actually run them?

Example: 

Base container (docker hub)
  - language container
    - service container 

So I want ```docker-compose build``` to build the "language container" to it will later be able to build the "service container" but I only want "service container" to run. I don't want ```docker-compose run``` to run "language container".

**Comment by villlem** [comment]
The section in yml file does not refer to container but service. So it makes no sence to have build-only services.
But compose can be more useful for development if I can point service to my image build system to provide image for it. Or if there was a way to include one to compose it self.

For now I recommend use image tag and build them by your self.

**Comment by dnephin** [comment]
There are a bunch of issues related to this (#942, #1284, etc). Going to close as a duplicate.

Also keep an eye on #1417 which should provide a better definition for what is "in scope" for compose.
