### ISSUE TITLE
Path handling is wrong

### ISSUE THREAD

**Issue by skorokithakis** [docker/compose#1453]
Running a docker file with the -f option does the right thing, namely, it considers ADD to be relative to the directory you're in. Docker-compose switches to the docker file directory, which is completely inflexible, and violates good UX by not letting me place files wherever I want. I don't want my code to be in a subdirectory of the docker configuration, since the docker configuration isn't more important than my code.

Docker-compose should allow you to build images relative to any path you want, so you can place all the configuration and Dockerfiles in any subdirectory you want.

**Comment by dnephin** [comment]
`ADD` is always relative to the build context directory. If you run `docker build .` that would be the current directory, but if you use a different path, it would be relative to a different path.

`docker-compose` does not change this. You tell it the build context directory, and everything in the `Dockerfile` will be relative to that directory.

**Comment by dnephin** [comment]
If I've misunderstood the issue, please provide an example of the bug.

**Comment by skorokithakis** [comment]
The behavior is not the same when you specify a Dockerfile, docker runs ADD relative to the directory where you run docker in, whereas docker-compose runs it relative to the Dockerfile.

I suspect that it's a Docker bug, because I'm under the impression that the docs mention otherwise, but clearly the more user-friendly implementation should win. This is either a bug report or a feature request, ie to add a way to have the Dockerfile builds run relative to some other directory than the one they're in, because that is extremely restrictive for the end user.

**Comment by aanand** [comment]
Can you provide a minimal failing case, please?

**Comment by skorokithakis** [comment]
Hmm, I just tried, and I can't reproduce it on this PC (don't you just love that)?

In any case, would it be possible to have docker-compose run Dockerfiles relative to some path different from where the Dockerfile is? I want my docker-compose config to live in a subdirectory of my code, and it's currently impossible for me to add my code to the container with this setup, which seems unnecessarily restrictive.

**Comment by aanand** [comment]
Regardless of what tool is used to invoke the build, paths in `ADD` are always relative to the *build context* (i.e. the path passed to `docker build` or the `build` key in `docker-compose.yml`). This is enforced by the daemon, and as far as I'm aware there's no way to change it.

**Comment by skorokithakis** [comment]
Hmm, it's odd that I saw different behaviour on the laptop, but it's too bad docker-compose can't work around this braindead decision. Please feel free to close this ticket, I'll take it up with docker itself. Thank you!

**Comment by aanand** [comment]
FYI, it's a decision with pretty thorough reasoning behind it (making builds guaranteed repeatable) - I recommend doing a search on the docker repo for pre-existing discussions before opening an issue.
