### ISSUE TITLE
Docs say OS X build doesn't work in Mavericks: Still true/relevant?

### ISSUE THREAD

**Issue by kojiromike** [docker/compose#1457]
The [contribution documentation](https://github.com/docker/compose/blob/master/CONTRIBUTING.md) says that there's a bug in PyInstaller that affects Mavericks, but not Mountain Lion. The linked issue (http://www.pyinstaller.org/ticket/807) is gone now. PyInstaller seems to have [moved to github](https://github.com/pyinstaller/pyinstaller). Is it still an issue? (Perhaps it has been resolved in Mavericks by this point.)

I have Yosemite and I have not had an issue using that build script on it. Would it be more relevant to compare Mavericks to Yosemite now?

**Comment by kojiromike** [comment]
It's possible, but not obvious to me, that they kept the issue numbers the same. Otherwise it'd be an interesting coincidence that https://github.com/pyinstaller/pyinstaller/issues/807 has to do with Mavericks as well.

**Comment by dnephin** [comment]
We've updated to the new pyinstaller, so hopefully this is fixed.
