### ISSUE TITLE
Up does not honor timeout

### ISSUE THREAD

**Issue by thieman** [docker/compose#1458]
`docker-compose up --help` promises a `timeout` option that appears to do absolutely nothing. Compose takes the standard 10 seconds to stop the running containers when I run the `up` command with my containers already started, regardless of what I pass here.

```
> docker-compose up --help
    -t, --timeout TIMEOUT  When attached, use this timeout in seconds
                           for the shutdown. (default: 10)
```

The timeout is also broken for `restart` in 1.2, though this has since been fixed: https://github.com/docker/compose/issues/1311. There seems to be a larger systemic issue of the docstrings not actually being tied to CLI functionality, which results in showing misleading information to end users and is extremely frustrating. Would be great to see this addressed.

**Comment by thieman** [comment]
Unless I'm misunderstanding and this only applies to when you run `up` without the `-d` flag and then throw a keyboard interrupt at it? If that is what it's actually doing, then I can close this and add a feature request along the lines of "if the containers are currently running, use this timeout to shut them down before restarting" which IMO would be much more useful.

**Comment by aanand** [comment]
Yes, that's where the timeout applies. Feel free to open a feature request as you describe.

> There seems to be a larger systemic issue of the docstrings not actually being tied to CLI functionality, which results in showing misleading information to end users and is extremely frustrating.

Because we use [docopt](http://docopt.org/), the CLI functionality is derived directly *from* the docstrings, so there's little chance of that.
