### ISSUE TITLE
Unexpected behavior for volume extends

### ISSUE THREAD

**Issue by skelethan** [docker/compose#1473]
I am observing behavior that may be by design but is unexpected & not clear from documentation.

Scenario:
```
base-compose.yml in /run
volumes:
- app_logs/:/app/logs

extends-compose.yml in /run/release-ab
volumes:
- other-volume/:/container/volumes
```
Results:
/run/app_logs/
/run/release-ab/other-volume/

Since compose up is performed from the context of the extends-compose.yml, I would expect merged relative file paths to start from there i.e.
/run/release-ab/app_logs/
/run/release-ab/other-volume/

Volume extension with relative file paths doesn't work for our use case in this behavior.

Thanks for clarifying

**Comment by dnephin** [comment]
Could you provide the full `docker-compose.yml` with extends?

I think the volumes should be relative to the `docker-compose.yml` that is being run.

**Comment by skelethan** [comment]
Hi, thanks for following up.

I am doubt I still have the docker-compose.yml in question.  I have since stopped using extends.  But as of submission (Compose 1.2?) - this was behaving as described.  

If this is by design then I would suggest adding a blurb in the docs that relative paths are relative to the location of the .yml they originate from (both extends and child).

https://docs.docker.com/compose/yml/#volumes

**Comment by dnephin** [comment]
This is now documented
