### ISSUE TITLE
docker-compose up doesn't rebuild image although Dockerfile has changed

### ISSUE THREAD

**Issue by JonasT** [docker/compose#1487]
Very often, docker-compose up doesn't rebuild image specified as "build:" in the docker-compose.yml although the respective Dockerfile has changed. Instead, I need to run docker build -t servicename_foldername . manually for the affected service which will actually update the image accordingly.

Is this intended? Because it's rather annoying, I can never be sure the image is actually up-to-date and need to run docker build manually before using docker-compose up.

**Comment by dnephin** [comment]
True, `docker-compose up` never rebuilds an image. This is "intended", but it's something I think we should change: #693

You can run `docker-compose build` to build the images.

Duplicate of #614

**Comment by wting** [comment]
Hey @dnephin, what a small world!

I'm running an issue where `docker-compose build` is not properly rebuilding containers. It's causing issues with preventing a Varnish container from starting due to stale lock files.

Based on what I've read elsewhere (e.g. #1195), it seems like `docker-compose build` is the recommended way to rebuild containers and should prevent problems like these.

```bash
╭─wting@nuc ~/code/reddit-mobile ‹python-2.7.12› ‹wting_chan-159_add_varnish_to_2X×ad20b6d›
╰─➤  docker ps                                                                                                              2016.09.15 12:20:46 PDT 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
╭─wting@nuc ~/code/reddit-mobile ‹python-2.7.12› ‹wting_chan-159_add_varnish_to_2X×ad20b6d›
╰─➤  docker-compose --version                                                                                               2016.09.15 12:20:48 PDT 
docker-compose version 1.8.0, build f3628c7
╭─wting@nuc ~/code/reddit-mobile ‹python-2.7.12› ‹wting_chan-159_add_varnish_to_2X×ad20b6d›
╰─➤  docker --version                                                                                                       2016.09.15 12:20:51 PDT 
Docker version 1.12.1, build 23cf638
╭─wting@nuc ~/code/reddit-mobile ‹python-2.7.12› ‹wting_chan-159_add_varnish_to_2X×ad20b6d›
╰─➤  docker-compose build && docker-compose up                                                                          2 ↵ 2016.09.15 12:23:35 PDT 
Building web
Step 1 : FROM reddit/reddit-nodejs:latest
 ---> ee57c186eb35
Step 2 : VOLUME /src
 ---> Using cache
 ---> 3720601d98c8
Step 3 : WORKDIR /src
 ---> Using cache
 ---> d4b9b360ef4e
Step 4 : EXPOSE 4444
 ---> Using cache
 ---> 5e232be73781
Step 5 : ENTRYPOINT npm start
 ---> Using cache
 ---> 1094fc9857bb
Successfully built 1094fc9857bb
Building varnish
Step 1 : FROM quay.io/reddit/varnish-fastly
# Executing 1 build trigger...
Step 1 : COPY default.vcl /etc/varnish/default.vcl
 ---> Using cache
 ---> ac9dadb35674
Step 2 : ENV VARNISH_PORTS 8080
 ---> Using cache
 ---> 3c43e0226f5f
Step 3 : EXPOSE 8080
 ---> Using cache
 ---> c88093c2ff32
Successfully built c88093c2ff32
Starting redditmobile_web_1
Starting redditmobile_varnish_1
Attaching to redditmobile_web_1, redditmobile_varnish_1
varnish_1  | storage_malloc: max size 100 MB.
varnish_1  | SHMFILE owned by running varnishd master (pid=1)  # STALE LOCK FILE
varnish_1  | (Use unique -n arguments if you want multiple instances.)
web_1      | 
web_1      | > r-project-blackbird@0.0.1 start /src
web_1      | > NODE_ENV=production npm run server
web_1      | 
redditmobile_varnish_1 exited with code 2
web_1      | 
web_1      | > r-project-blackbird@0.0.1 server /src
web_1      | > NODE_ENV=production node ./bin/ProductionServer.js
web_1      | 
web_1      | Started cluster with 4 processes.
web_1      | Started server at PID 31
web_1      | Started server at PID 46
[..]
```

**Comment by dnephin** [comment]
hey @wting 

I think what might be happening is that the lock file is in a volume (https://docs.docker.com/compose/overview/#/preserve-volume-data-when-containers-are-created).

You can try `docker-compose down` to remove the old containers, which will remove the volume reference. The next `up` should start with fresh volumes.

**Comment by wting** [comment]
Thanks! `docker-compose down` worked, as well as `docker-compose up --force-recreate` (but not `docker-compose --build`). I suppose it's not intuitive because there's a volume mounted for the web container but not the Varnish container; yet Varnish files stick around. Here's the `docker-compose.yml` file:

```yaml
version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
     - "4444:4444"
    volumes:
     - .:/src
  varnish:
    build:
      context: .
      dockerfile: Dockerfile.varnish
    ports:
    - "4301:80"
    depends_on:
    - web
```

For context:
- [`Dockerfile.dev`](https://github.com/reddit/reddit-mobile/blob/master/Dockerfile.dev) (`VOLUME` present)
- [`Dockerfile.varnish`](https://github.com/reddit/reddit-mobile/blob/master/Dockerfile.varnish) (no `VOLUME`)
- [`reddit/varnish-fastly/Dockerfile`](https://github.com/reddit/varnish-fastly/blob/master/Dockerfile) (no `VOLUME`)

**Comment by LudLaf** [comment]
Thanks wting, and all the ones who wrote on this issue, I've been "saved" by your comment =>  "docker-compose up --force-recreate (but not docker-compose --build)."

**Comment by Perados** [comment]
`docker-compose up --build`

**Comment by shams-ali** [comment]
use: `docker-compose build`

**Comment by xavierbaez** [comment]
> True, `docker-compose up` never rebuilds an image. This is "intended", but it's something I think we should change: #693
> 
> You can run `docker-compose build` to build the images.
> 
> Duplicate of #614

Thanks that really helped me assign a new Dockerfile and rebuild the container with the latest changes

**Comment by jouellnyc** [comment]
FYI - had the same issue and the same fixed as discussed. The interwebs led me here. Thanks for the good discussions!

**Comment by reyx** [comment]
`docker-compose up --build -V`

**Comment by rafaeldev** [comment]
For clarify what is `-V` parameter:
`-V, --renew-anon-volumes   Recreate anonymous volumes instead of retrieving data from the previous containers.`

**Comment by davidwhthomas** [comment]
To rebuild a single image inside `docker-compose`:

`docker-compose up -d --force-recreate --no-deps --build $service`

e.g:

`docker-compose up -d --force-recreate --no-deps --build varnish`

**Comment by rodoabad** [comment]
I was having similar challenges as of late because I switched from using...

```
docker-compose build FOO
docker-compose up --abort-on-container-exit FOO
```

To just...

```
docker-compose up --build --force-recreate --abort-on-container-exit FOO
```

But it never did rebuild so I was wondering if `docker-compose build` is the same as `docker-compose up --build`.

Looks like I was missing `-V`?

**Comment by bf** [comment]
I expected --force-recreate to build the container, but it is not doing that. So I ended up using `docker-compose up --build $app`.

**Comment by AIGeneratedUsername** [comment]
> True, `docker-compose up` never rebuilds an image. This is "intended", but it's something I think we should change: #693
> 
> You can run `docker-compose build` to build the images.
> 
> Duplicate of #614

This is not true for Docker version 20.10.21. The `docker-compose build` command does not see Dockerfile changes and uses a previous version. 

The valid answer is to use `docker-compose build --no-cache` after every Dockerfile modification.

**Comment by alfonsrv** [comment]
No way to use the caching of `Dockerfile` layers when using `docker-compose up --build`? Rebuilding it completely from scratch seems like quite a heavy-handed operation.

**Comment by naraomur** [comment]
> hey @wting
> 
> I think what might be happening is that the lock file is in a volume (https://docs.docker.com/compose/overview/#/preserve-volume-data-when-containers-are-created).
> 
> You can try `docker-compose down` to remove the old containers, which will remove the volume reference. The next `up` should start with fresh volumes.
> 
> If it's not in a volume, I guess it could just be that the lock was never removed. Compose will try to start a container if it exists and the config hasn't changed, so running `down` should fix that as well.

I had containers from different projects and I was having this issue on a new project where the MsSql container was created but not the Dev-Env container. Was getting a 'There is no Dev-Env container found' msg. So just ran again `docker-compose up` after I ran first `docker-compose down`. Thank you!

**Comment by micheljung** [comment]
`docker compose up` should either build, or it shouldn't.

Right now, it builds if the image doesn't exist, but it doesn't build if it exists, even if the inputs have changed. This is unexpected and frustrating.

`docker build` already determines if someting needs to be done or not, why not just rely on that?

At least let us configure it in the compose file's `build` option, please.

**Comment by glours** [comment]
@micheljung how you start an application if your image isn't there? That's why Compose pull or build the missing image when starting.
if you want to have the same behaviour as `docker build` you can use `docker compose up --build` and you should take a look at [pull_policy](https://github.com/compose-spec/compose-spec/blob/main/05-services.md#pull_policy) service configuration if you only want certain services to be rebuild

**Comment by micheljung** [comment]
@glours fair enough, I'll correct my statement to "`docker compose up` should always call `docker build`".
`docker compose up --build` isn't an option if, for instance, you load your compose file into IntelliJ and click the "Deploy" button (which calls `docker compose up` and there's nothing you can do about it).

What speaks against an option in the `build:` config? 

Btw. our use case is that we start our stack via Docker Compose for development, so whenever the source files change and I start up the service, the build should run again.

**Comment by micheljung** [comment]
> What speaks against an option in the `build:` config?

I just found out that this is already possible, just not in `build` but in `pull_policy` (because, why wouldn't you expect it there :P)

> build: Compose builds the image. Compose rebuilds the image if it's already present.

https://docs.docker.com/reference/compose-file/services/#pull_policy

```yaml
services:
  my-service:
    build: my-service
    pull_policy: build
```
