### ISSUE TITLE
docker-compose won't start a container if --iptables=false is set

### ISSUE THREAD

**Issue by xinity** [docker/compose#1496]
hi,

i had a strange behavior lately regarding docker-compose, at first i though of a mistake i've made, but after digging in, i found that some containers (i haven't found something deterministic) won't start using docker-compose if docker option --iptables=false is set.

a very strange thing is in my case the container involved has no port forwarded, only using linked containers.

digging more i found a exit status 128 regarding the involved container.

any clues maybe ?

**Comment by lostsnow** [comment]
try `iptables -N DOCKER` ?

**Comment by dnephin** [comment]
No response from OP
