### ISSUE TITLE
ps is sensitive to terminal width

### ISSUE THREAD

**Issue by jonocodes** [docker/compose#1513]
When piping "docker-compose ps" to anything, the terminal size effects the output. For example, lets say my terminal is maximized and if I run "docker-compose up"

> docker-compose up
> docker ps | wc -l
8
> docker-compose ps | wc -l
9

Now I shrink my terminal to half the width

> docker ps | wc -l
8
> docker-compose ps | wc -l
16

I need to be able to pipe the output because I am grepping it as a way to determine what a container is named after compose starts it. So I presumed it would output one container per line, but it does not.

As you can see 'docker ps' does not exhibit this behavior. It produces the same line count regardless of the terminal size.

To be clear about what I am looking for, look at 'ls'. It is terminal aware. 'ls' in a terminal show files side by side. But if you pipe it to something else, it presents files line by line which allows for further processing.

**Comment by iafilatov** [comment]
In the meantime, would something like ``docker inspect -f '{{.Name}}'  $(docker-compose ps -q)` work for you?

**Comment by jonocodes** [comment]
iafilatov, I like where you are going with that workaround, but that line does not work.

It looks like inspect can only take one container at a time. Since I have multiple containers running $(docker-compose ps -q) produces a lot of output.

And then I get a bunch of errors, like:

Error: No such image or container: Name
Error: No such image or container: Command
Error: No such image or container: State
Error: No such image or container: Ports
Error: No such image or container: -----------------------------------------------------------------------------------------------
Error: No such image or container: /docker-entrypoint.sh
Error: No such image or container: mysqld
Error: No such image or container: Up
Error: No such image or container: 3306/tcp
Error: No such image or container: /bin/sh
Error: No such image or container: -c
Error: No such image or container: bash
...

**Comment by iafilatov** [comment]
@jonocodes Well, I tried it before writing the reply, and it did work for me. Those errors look as if you're doing `docker-compose ps` instead of `docker-compose ps -q` (could you show the part of your script that fails?).  The latter prints only the ids of the containers, and there you have it printing table headers, CMDs, ports etc. As for `inspect`, it absolutely can accept multiple containers (like many other docker commands):

    $ docker help inspect

    Usage: docker inspect [OPTIONS] CONTAINER|IMAGE [CONTAINER|IMAGE...]

**Comment by jonocodes** [comment]
@iafilatov, thanks. I think you were right that I was not using '-q'. Now I am getting sane output and I will be using your workaround for now.

**Comment by dnephin** [comment]
Fixed in #1693

**Comment by jonocodes** [comment]
thanks

**Comment by dhazeghi** [comment]
Either the fix is not complete, or this has been broken again.  If I run:

```
CONTAINER_NAME=`docker-compose -f docker-compose.yml -p mycontainer ps | awk '/mycontainer/ { print $1 }'`
```

The results depend on the width of my terminal.  In general for an 80 character terminal, if the container name is more than 22 characters, it will be split across multiple lines and results will be truncated.

**Comment by mpragliola** [comment]
Having same problem here, when I pipe the output it gets truncated to many lines

**Comment by BingoDeeVee** [comment]
Getting the same issue
![image](https://user-images.githubusercontent.com/36706846/147247624-aa2166f9-f70e-49ee-86d9-3ef973840667.png)
![image](https://user-images.githubusercontent.com/36706846/147247844-49e44083-5b24-4009-ae13-ace4155045f5.png)
```
$ sudo docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```
