### ISSUE TITLE
Add a --clear-cache flag to docker compose build

### ISSUE THREAD

**Issue by nicodmf** [docker/compose#1523]
Same problem than #152 

Recently, I have encountered problems when using fig build due to my build relying on cached, outdated Docker images. In order to get the build to work, I'm forced to alter the Dockerfile trivially in some way to invalidate the cache. This seems like an annoying workaround.

Since the importance of this tool is to allow agnostic deployment, it's pretty crucial to be able to follow exactly the same build steps on different machines. If two machines have different caches, they will no longer build in the same way (to my limited understanding) and the value is lost somewhat.

Adding a --clear-cache flag that causes a container to be built from scratch, ignoring the cache, would be useful to avoid this problem. I don't know how easy/difficult it would be to implement, however.

@cameronmaske can probably add more to this discussion.

@bfirsh very important in my situation and a solution : https://github.com/docker/compose/commit/47bbc35b749e48f233f6354bd26de134205f914a but not save in the last compose

**Comment by dnephin** [comment]
This sounds like `docker-compose build --no-cache`. Why does't that work?

**Comment by nicodmf** [comment]
@dnephin Thanks, this is really that i search. I close this issue.

**Comment by vagner-nascimento** [comment]
@dnephin Thats not good man, in this way we can't call up directly.... there's any way to permanently REMOVE de %$*#& cache??
