### ISSUE TITLE
Flush log buffer when printing logs

### ISSUE THREAD

**Issue by chiefy** [docker/compose#1549]
```bash
 $ docker-compose up -d && docker-compose logs &> composer.log
```
Someone correct me if I am wrong here, but what happens in the above is that nothing gets written to `composer.log` until `docker-compose logs` is killed, at which time stdout/stderr are unbuffered and written to `composer.log`?

**Comment by chiefy** [comment]
I think I just figured this out, I did:
```bash
$ export PYTHONUNBUFFERED=1
```
And things seem to be working as expected. It'd be nice to note this somewhere in the docs.

**Comment by aanand** [comment]
Perhaps we should explicitly flush output in `up`/`logs`.

**Comment by chiefy** [comment]
Actually it looks like this is fixed w/ docker 1.6, but still occurs w/ docker 1.5 & compose 1.2

**Comment by AndersKOlsson** [comment]
The nature of `docker-compose logs` is that it hangs until the service(s) are stopped. Hence, I think the way to do this would be to do `docker logs` for each service (since that command behaves differently, and returns even when the container is still running).

**Comment by chiefy** [comment]
@AndersKOlsson if you use the non-binary install of compose (`pip install docker-compose`) and set `PYTHONUNBUFFERED=1` in your env, `docker-compose logs` will unbuffer output properly.

**Comment by AndersKOlsson** [comment]
@chiefy Thanks for the suggestion. Unfortunately, this will be used in a script that's used by all our developers. So we cannot really control the environment reliably. At least it looks like this a candidate feature for compose 1.6.0.

**Comment by jbarbuto** [comment]
FWIW, I'm still noticing this issue without `PYTHONUNBUFFERED=1` on docker-compose 1.8.0.

**Comment by cameron** [comment]
I'm seeing a similar issue with and without `PYTHONUNBUFFERED=1` on docker-compose 1.11.2.

Issue seems to be that following works for some period of time, and then stops. I can't tell if it stops and resumes intermittently, b/c as soon as I suspect that it's stopped, I restart the command, which usually reveals some lines that hadn't been printed. 

Note that this is only happening for sure with `docker-compose logs <service>`. `docker-compose up` is fine.

Fortunately, the workaround is easy `docker-compose up | grep <container_name>`.

**Comment by tobia** [comment]
Can this be reopened? It's still broken in the latest 1.26.0 release. To witness:

    docker-compose up -d; docker-compose logs -f | grep "myString"

or even:

    docker-compose up | grep "myString"

They are both silent until you kill the process, at which point they output all the logs.

**Comment by mcallaghan-bsm** [comment]
happens with `dotnet` commands as well  :(

**Comment by theAkito** [comment]
Happens in my scenario as well, with `docker-compose up` and `export PYTHONUNBUFFERED=1`.

**Comment by cmcc13** [comment]
running with unbuffered works for me, but if I try printing without newline in python3.9 `print('some text\r', end='', flush=True)` it buffers till the next newline prints.
Python3.9
Docker-compose 1.27.4
macos 10.15.6
