### ISSUE TITLE
`build` fails on component non-zero exit code when `docker build` does not

### ISSUE THREAD

**Issue by timfallmk** [docker/compose#1554]
Running `docker-compose build --no-cache` will fail if one of the Dockerfile commands returns a non-zero exit code. However running `docker build --no-cache` will return successfully in the same condition.

Example:
Dockerfile has command `RUN npm install libxmljs`:

`npm` will return `code 137` (a warning) from this command

`docker-compose` will exit at this stage while `docker` does not.

I can provide more details of the builds if necessary.

**Comment by dnephin** [comment]
I believe you are mistaken:

**Dockerfile**
```
FROM busybox:latest
RUN exit 137
RUN echo "ok"
```

```
$ docker build .
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM busybox:latest
 ---> 8c2e06607696
Step 1 : RUN exit 137
 ---> Running in 804b53a341ac
INFO[0000] The command [/bin/sh -c exit 137] returned a non-zero code: 137

$ echo $?
1
```

Looks like docker build also exits as soon as it hits a failure.

**Comment by timfallmk** [comment]
Hmm, I can't get this to re-occur now after doing an upgrade to 1.3.0 RC3. It could have been an edge case between versions.

I'll reopen if it pops up again.

**Comment by timfallmk** [comment]
For anyone encounter this, it appears to be a race condition when running out of memory on the host.

**Comment by particle4dev** [comment]
@timfallmk Ah, thanks !!!

**Comment by chruit** [comment]
This error can also be recreated by removing a container from the Kitematic interface.

**Comment by infl3x** [comment]
Thank you, @timfallmk! That solved the problem for me :smile:

**Comment by dm-wyncode** [comment]
+1 when low on memory

**Comment by darthmarku** [comment]
This also happens when renaming a container within Kitematic during a build.

**Comment by lizter** [comment]
I got the same error while running out of disk space during a build.

**Comment by faviouz** [comment]
Bumping up my droplet's RAM from 512MB to 2GB fixed it as well.

**Comment by harkiratsinghdevgan** [comment]
Clear your Cache, it helped me.

https://net2.com/how-to-clean-up-unused-docker-containers-images-and-volumes/

**Comment by shahabnft200** [comment]
hello i faced this problem during install xraygen on my vps ubuntu 20.04 lxd  how i can fix it ?
Command 'docker-compose -f docker-compose.yml up -d' returned non-zero exit status 1.
