### ISSUE TITLE
Internal host address looks not update

### ISSUE THREAD

**Issue by sunadm** [docker/compose#1556]
When I stop and rm a container (for example, mysql), and use "up --no-recreate -d" parameter to recreate it. 

Sometimes other containers (for example tomcat) link to this service may lost connection to it.

When this happened, from the bash of tomcat cannot ping the mysql container by hostname.

I checked the internal IP address of mysql, when container recreated, it's IP usually changed too.
But in this case, the tomcat's /etc/hosts file looks not updated, so...

**Comment by dnephin** [comment]
This is a limitation of docker links, dependent containers need to be recreated to pickup the change in address.

**Comment by sunadm** [comment]
that is not make sense.

if so, why docker-compose supply the function to enable recreate an individual container?
but in fact, this function is very useful.

**Comment by josephpage** [comment]
If you use `docker-compose up -d` without `--no-recreate` all your containers will be recreated and associated links will be updated.

But with `--no-recreate`, only your mysql will be created and links from tomcat will become outdated. As @dnephin said, it's a limitation of docker links. You can use a discovery service to escape this limitation.

On the contrary, `--no-recreate` option is very useful when we want to relaunch the tomcat service but not the mysql.

**Comment by sunadm** [comment]
@josephpage thanks!

This explanation clear enough.
