### ISSUE TITLE
Duplicate container is left over when recreate fails

### ISSUE THREAD

**Issue by lieryan** [docker/compose#1573]
This is related to #1045. After hitting the issue mentioned in #1045, subsequent `docker-compose up` fails with:

```
$ sudo docker-compose up -d
Recreating foo_bar_1...
Traceback (most recent call last):
...
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
$ sudo DOCKER_CLIENT_TIMEOUT=300 docker-compose up
Recreating foo_bar_1...
Recreating 9c1b31a841_foo_bar_1...
Conflict. The name "foo_bar_1" is already in use by container 4af37fe03b76. You have to delete (or rename) that container to be able to reuse that name.
```

**Comment by szuliq** [comment]
I also see a lot of these.

I'm not sure if those are caused by #1045 

Ubuntu 15.04; Docker 1.7

**Comment by aanand** [comment]
Looks related to #1349 - Compose has somehow gotten into a situation where there are two containers with the suffix `_1`, one of which has been renamed but then failed to recreate (perhaps because there was an HTTP timeout).

**Comment by dnephin** [comment]
I think after the failure, `9c1b31a841_foo_bar_1` still has the correct labels, so it's still considered an instance of the service. So there are two instances with the id of 1.

compose would need to only recreate once per instance id.  In many ways this is related to #1516.

**Comment by aanand** [comment]
OK yeah, looks like this happens if we successfully create the new container but fail to start it. I can reproduce by sticking a `sys.exit()` in `recreate_container`:

```python
new_container = self.create_container(...)
sys.exit(1)
self.start_container(new_container)
```

This results in a renamed old container, plus an unstarted new container, both with `container-number=1`.

> In many ways this is related to #1516.

Random container numbers would solve the immediate error, yeah, but we'd still be left with two containers where we only wanted one.

**Comment by DavidBruant** [comment]
> I also see a lot of these.

> Ubuntu 15.04; Docker 1.7

Same combination, same problem. I also doubt it's #1045

I could get back to work by coming back to Docker 1.4.1 and docker-compose 1.2.0.

**Comment by lieryan** [comment]
This bug seems to show up if there is an exception (e.g. with #1045) or if you Ctrl+C in the middle of a `docker-compose up`. Essentially, docker-compose fails to clean up the temporary containers.

**Comment by iMerica** [comment]
Which version can I downgrade to so that I can get around this issue?

**Comment by aanand** [comment]
@iMerica Run `docker-compose rm -f` to clear everything out, then downgrade to 1.2.0.
