### ISSUE TITLE
Daemon vs detached terms in docker-compose

### ISSUE THREAD

**Issue by moxiegirl** [docker/compose#1582]
Port https://github.com/docker/docs-base/issues/43 to here.

Here: http://docs.docker.com/compose/
![image](https://cloud.githubusercontent.com/assets/1347209/8268478/0e13cca0-173c-11e5-8cc9-3ceb7f9aacf4.png)

it says "daemon mode" to the -d flag.

in the cli reference it refers to it as "detached mode":

![image](https://cloud.githubusercontent.com/assets/1347209/8268474/048bf202-173c-11e5-95e8-47182542ae11.png)

image
I believe the correct and accurate one is "detached mode".

 ping @ahmetalpbalkan original reporter

**Comment by thaJeztah** [comment]
> I believe the correct and accurate one is "detached mode".

Correct
