### ISSUE TITLE
Run `docker-compose build` without checking dependencies

### ISSUE THREAD

**Issue by peter-leonov** [docker/compose#1585]
At times it might be needed to build images first, then run some `docker …` commands creating the whole picture, and only then run `docker-compose up/run`. This is impossible with current implementation to just build and incomplete setup.

What do you think of not checking dependencies on `docker build`?

**Comment by WadeLovell** [comment]
Would this allow an incomplete image in those cases where dependencies:wait errors out?

**Comment by kung-fu-tzu** [comment]
Could you please clarify what an incomplete image is?

**Comment by WadeLovell** [comment]
The build must complete every layer in order. As it runs now, it doesn't complete so I don't see any intermediate images. I would at least like to see the results of the layers through the last successfully completed image before the failure.

**Comment by aanand** [comment]
@kung-fu-tzu If I've understood you, you're asking that we build all the images we need before starting any containers. I think that would be sensible - the same should go for pulling.

@WadeLovell To debug the steps of a build, do it manually with `docker build` and pass `--rm=false` to stop it removing intermediate containers.

**Comment by ijc** [comment]
Issue grooming: Closing this as stale.
