### ISSUE TITLE
Are there plans to make a Docker Hub for docker-compose.yml files?

### ISSUE THREAD

**Issue by Jacobingalls** [docker/compose#1597]
I am currently putting together a docker-compose backed app, and in order to ship the config to another team member, they would have to pull the whole git project, seems to me that there should be a way to share various clusters with people, so in the same way that docker hub shares images, it would be neat to share compose files.

Is this in the road map, or does this exist an i am just blind?

Thanks.

**Comment by dnephin** [comment]
Yes, I totally agree this is something necessary, and would be really valuable for #318 as well.

I don't know of any plans, but I don't think it needs to be anything special. It's basically just sharing static yaml files, so really any web server would do.

**Comment by dborzov** [comment]
It seems everyone just uses Github for this purpose. Creating a separate repo just for the docker-compose file and share images on Docker's Hub should be good enough for pretty much all use cases.

**Comment by Jacobingalls** [comment]
@dborzov that is true, the mechanism for storage could be Github. But to me, it should be a mechanism for sharing, linking, searching, and most important for me: discovery.

**Comment by patcito** [comment]
I wrote a hub to share docker-compose files @Jacobingalls @dnephin @dborzov you can check it here https://github.com/composehub/cli or check the web site https://composehub.com/. It re-uses github to store the docker-compose.yml files, you just need to describe your package name and github url. Let me know what you think.

**Comment by pensiero** [comment]
What happened to composehub.com and stackfiles.io?

**Comment by BRUNNEL6** [comment]
Any update on this?

**Comment by arifulhb** [comment]
Both `Composehub` and `stackfiles` are down :(
