### ISSUE TITLE
Compose 1.3 has disabled TTY in some cases

### ISSUE THREAD

**Issue by aidanlister** [docker/compose#1604]
We used to be able to run something like:
    `docker-compose -p aesg run web python manage.py test --keepdb abas.apps.properties`

And whenever there was a import pdb; pdb.set_trace() it would drop to console .. now it doesn't.

OSError: [Errno 32] Broken pipe

**Comment by aidanlister** [comment]
Cancel that ... it's all cases.

```docker-compose -p foo run web bash``` gives OSError: [Errno 32] Broken pipe

**Comment by aidanlister** [comment]
```
docker-compose version: 1.3.1
CPython version: 2.7.6
OpenSSL version: OpenSSL 0.9.8zd 8 Jan 2015
```

**Comment by aidanlister** [comment]
```pip uninstall ndg-httpsclient``` fixes the issue

**Comment by timmygee** [comment]
This also happened to me. Seems at the moment we have the choice between the InsecurePlatformWarning on startup or TTY access

**Comment by aanand** [comment]
You've installed via Pip, yes? What happens if you use the binary?

**Comment by appden** [comment]
This is somewhat a duplicate of #1509. Thanks @aidanlister for the quick fix!

**Comment by edwinlunando** [comment]
Is this solved? How about the main binary?

**Comment by aidanlister** [comment]
It's not solved but it's also primarily a documentation bug - need to explicitly say not use use the ndg library and provide an alternative to get rid of the warnings

**Comment by voidlily** [comment]
I ran into this issue today and found I had the same problem that `ndg-httpsclient` was installed. Like @aidanlister , uninstalling that package fixed it for me as well.

**Comment by justinanastos** [comment]
I am still struggling with this issue. Where exactly would I find `ndg-httpsclient` installed?

**Comment by shin-** [comment]
Closing as a duplicate of #1509
