### ISSUE TITLE
env_file should support ~ and environment variables

### ISSUE THREAD

**Issue by abridgett** [docker/compose#1606]
(running v1.3.1). In particular this could be useful for pulling in per-user settings:

root@ip-10-0-0-141:/home/ubuntu/central# docker-compose ps
Couldn't find env file: /home/ubuntu/central/~/.docker/secrets.env
root@ip-10-0-0-141:/home/ubuntu/central# docker-compose ps
Couldn't find env file: /home/ubuntu/central/$HOME/docker/secrets.env

(couldn't see any pre-existing issue for this).

**Comment by jbenoit2011** [comment]
+1

**Comment by aanand** [comment]
See #1377 for environment variables.

Supporting `~` is an interesting one. Arguably we should do that for all paths.

**Comment by dghubble** [comment]
+1

**Comment by vladgh** [comment]
+1 and might I add that it would be nice if it would only warn instead of fail if the file is not found.

**Comment by stigchristian** [comment]
+1

**Comment by amfleming** [comment]
+1

**Comment by estevaoam** [comment]
+1

**Comment by traxair** [comment]
+1

**Comment by hanej** [comment]
+1

**Comment by dnephin** [comment]
This is supported in docker-compose 1.5
