### ISSUE TITLE
improve error message for invalid cap_add

### ISSUE THREAD

**Issue by juliantaylor** [docker/compose#1611]
my docker-compose contained:

```
someimage:
    image: ubuntu:trusty
    cap_add: NET_ADMIN
```

this worked fine in docker-compose 1.1.0, though with 1.3.1 (and docker 1.7.0) it now fails with a cryptic error message:

    json: cannot unmarshal string into Go value of type []string

it took me a while to figure out cap_add now has to be a list. I think the non-list form was also an example in the docs at some point in the past.
It would be good to improve the error message here to simplify finding the error in the yml.
Or alternatively accepting the non-list form for backward compat would also be good.

**Comment by aanand** [comment]
Thanks for reporting. This is actually a Docker 1.7.0 bug - I've filed https://github.com/docker/docker/issues/14318.
