### ISSUE TITLE
"connection reset by peer" becaused of linked rabbitmq

### ISSUE THREAD

**Issue by zimmski** [docker/compose#1612]
I am using compose 1.3.1 and docker 1.7.0 in an up to date ubuntu/trusty64 Vagrant box. Before I used compose 1.2 and docker 1.6.x which did not have this problem.

I am starting a few containers using "compose up". Among them are a rabbitmq:3.5.3-management container, exposing the ports 5672 and 15672, as well as google/debian:wheezy which is consuming the rabbitmq container via a link defined in the compose file.

When I remove all containers and do a compose up. This one container will fail starting up with the error "System error: read parent: connection reset by peer". By removing the link to the rabbitmq container the same container will start just fine. Also when the rabbitmq container is already running, the said container does also start up fine. So I guess there is a race because of rabbitmq which needs some time to start up.

Since this problem did not occur with the older versions I am wondering if this can be avoided using some option of compose I do not know of, like waiting for a container to be ready, or if this is a general problem and needs to be debugged. Anyway, please let me know how I can help.

**Comment by lphuberdeau** [comment]
I've had a similar issue:

```
Cannot start container f4ef436a4b113c363611fbbab0f0bcb47bba4d378e566b2aabcf67069f7ac733: [8]
```

Docker 1.8.1, Docker-compose 1.4.0

I started having this issue after removing a link between two containers in our architecture. The container that started failing is unrelated to the change.

Restarting dockerd allows the system to go back up, but any attempt to restart causes the error again.

Thinking this may be related to the config hash or some sort of collision, I added a dummy environment variable on the broken container and everything started working again.

**Comment by dnephin** [comment]
@lphuberdeau I think the issue you reported is #1757.  I'm working on a fix for it as we speak.

**Comment by dnephin** [comment]
@zimmski the error you described is not something that I've seen before. I'm not sure if it's a failure in compose or if it's coming from the application. If you're still able to reproduce this problem with the lastest version of compose and docker, please provide a minimal reproduction of the issue. Thanks!

**Comment by lphuberdeau** [comment]
Updated the error message, seems like part of it had gone missing during the copy. It does not appear to be the same as #1757.

Any additional information that would help, specific log files?

**Comment by dnephin** [comment]
I found this issue https://github.com/docker/docker/issues/14203 (and https://github.com/docker/docker/issues/15030) which seems to be the source of the failure. I don't think it can be fixed in compose directly.

**Comment by lphuberdeau** [comment]
This does seem to match the issue. Our restart process does use a combination of stop, kill and rm.

**Comment by zimmski** [comment]
I cannot reproduce it right now. At the moment I am using docker-compose 1.3.3 and docker 1.7.1, and the system has changed a lot. We also put some workarounds in it to get the initialization "just right". We have it on our plan for the coming months to remove workarounds. I will try again during that phase.

**Comment by dnephin** [comment]
Are you still able to reproduce this with the latest version of Compose?

**Comment by zimmski** [comment]
Unfortunately I cannot reproduce it with our current setup. I will close this issue for now, maybe I will hit the problem after refactoring out the workarounds.
