### ISSUE TITLE
Snappy Package For Ubuntu Core

### ISSUE THREAD

**Issue by ibnesayeed** [docker/compose#1625]
Now that Compose is slowly getting ready for production and there has been some interest on using Snappy Ubuntu on production servers, I think it is the right time to provide Snappy package of Compose. People trying to install it in a traditional way are facing [read only file system error](http://askubuntu.com/questions/626893/read-only-file-system-error-while-trying-to-install-docker-compose-on-snappy-ubu). And here is a quick guide on  [how to package snappy apps](https://developer.ubuntu.com/en/snappy/tutorials/build-snaps/).

**Comment by ijc** [comment]
Issue grooming: If this is still relevant (from https://forum.snapcraft.io/t/alias-for-docker-compose-as-docker-compose/7481 I wonder if it is fixed) it should be raised as an issue with the snappy project I think.
