### ISSUE TITLE
"fig run" should support port forwarding

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#163]

**Comment by tebanep** [comment]
+1

**Comment by ColCh** [comment]
+1

**Comment by thaJeztah** [comment]
Anyone +1-ing now, this has been implemented in https://github.com/docker/fig/pull/485 and is scheduled for the next (1.1) release.

**Comment by ColCh** [comment]
@thaJeztah Thanks. Yep but any ETA for release?

**Comment by thaJeztah** [comment]
Don't know, perhaps one of the maintainers can give an eta, otherwise just be patient :)

**Comment by dnephin** [comment]
@ColCh see #729

**Comment by ColCh** [comment]
@dnephin ver bump will be great :+1:

**Comment by javierbq** [comment]
+1

**Comment by thaJeztah** [comment]
A release candidate for fig (now *docker-compose*) was just released;

https://github.com/docker/fig/releases/tag/1.1.0-rc1

Make sure to read the release-notes and README for the changes involved in the rebranding to `compose`

**Comment by aanand** [comment]
The syntax is:

    $ docker run --service-ports SERVICE

**Comment by iMerica** [comment]
@aanand Do you mean `docker-compose run --service-ports SERVICE` ?

**Comment by aanand** [comment]
@iMerica Oops, yes.
