### ISSUE TITLE
How do you print to the stdout of a container from any process?

### ISSUE THREAD

**Issue by iMerica** [docker/compose#1634]
In one terminal session I'm tailing a container:

    $ docker-compose logs myapp
    myapp_1 | starting app ..
    myapp_1 | listenging on port 8080

On a separate session, I would like to do:

    docker exec -d myapp_1 sh -c 'echo "foo" >>/dev/stdout'

and have it print `foo` to stdout on the running container above. Does anyone know of a way to do this? I've tried the solution in http://serverfault.com/a/634296, but it didn't work for me.

**Comment by dnephin** [comment]
What you did should work.  Since this isn't directly related to Compose, and it seems like there hasn't been any suggestions from the community, I'm going to close this issue.
