### ISSUE TITLE
Keep getting: json: cannot unmarshal string into Go value of type []string

### ISSUE THREAD

**Issue by tuanmh** [docker/compose#1638]
Hi guys, after I upgraded to boot2docker 1.7.2, ``docker-compose up`` keeps throwing this error: ``json: cannot unmarshal string into Go value of type []string``. 

Could you please help me in this case. Thanks!

**Comment by tuanmh** [comment]
Here is my system information: boot2docker 1.7.2, Virtualbox 4.3.28, OSX 10.4.4, thanks again.

**Comment by aanand** [comment]
This is a Docker 1.7.0 bug. If you like you can try the 1.7.1 release candidate, which contains a fix:

    $ boot2docker init --iso-url="https://github.com/tianon/boot2docker/releases/download/v1.7.1-rc1/boot2docker.iso"

**Comment by mboussaa** [comment]
I am getting the same error. However, I am not using b2d

**Comment by aanand** [comment]
@mboussaa It's a Docker bug, not a Boot2Docker bug.

**Comment by mboussaa** [comment]
ok. In fact, it works now. I set the cpu share to 0. That is why I was getting this error.
Thank you anyway

**Comment by shabbychef** [comment]
I am having this issue under 1.7.1-rc3 on Ubuntu 14.04:
```
$ docker --version
Docker version 1.7.1-rc3, build c2e658d
$ docker info
Containers: 16
Images: 676
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 708
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 31.41 GiB
Name: piane
ID: XRYW:UJTU:3ZZU:KFHG:GI5W:ZEEL:MRLM:C7JB:T4Z7:SR7J:RPX5:LHJQ
WARNING: No swap limit support
$ docker-compose up
Creating svn_svndisk_1...
json: cannot unmarshal bool into Go value of type string
```
My MWE: 
```
$ cat docker-compose.yml 
foodisk:
  image: ubuntu
  entrypoint: true
  volumes:
  - /var/opt/foo:/var/foo:rw
$ ls -al /var/opt/foo
total 8
drwxr-xr-x 2 root root 4096 Jul 13 10:08 .
drwxr-xr-x 4 root root 4096 Jul 13 10:08 ..
```

**Comment by shabbychef** [comment]
Maybe I am dumb. I changed `true` in my `docker-compose.yml` file to `/bin/true`, and now this runs.  
```$ cat docker-compose.yml 
foodisk:
  image: ubuntu
  entrypoint: /bin/true
  volumes:
  - /var/opt/foo:/var/foo:rw

$ docker-compose up
Recreating fooz_foodisk_1...
Attaching to 
```

The moral of the story, perhaps, is to fully qualify your `entrypoint` otherwise `docker-compose` may eagerly interpret it as a Boolean!

**Comment by aanand** [comment]
The perils of YAML. We should check or auto-convert it as part of #129.

**Comment by bastiao** [comment]
I'm also have this bug. If you use 1.6.2 and it works.

**Comment by bastiao** [comment]
other version of compose does not seems to fix the issue with docker 1.7.1. Any ideas?

**Comment by aanand** [comment]
@bastiao what does your `docker-compose.yml` look like?

**Comment by bastiao** [comment]
https://github.com/bioinformatics-ua/catalogue-docker/blob/master/dev/docker-compose.yml

**Comment by aanand** [comment]
@bastiao Change `command: true` to `command: "true"`.

**Comment by shabbychef** [comment]
@bastiao @aanand or `command: /bin/true`, since maybe in the future an automagic conversion process will take "true" to true and then bonk.
