### ISSUE TITLE
Scale in parallel

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1653]
Adding and removing containers in "scale" can be done in parallel. This would be particularly useful when using Compose in combination with a Swarm, because you will scale to larger sizes and things generally run a bit slower on a Swarm.

@aanand has started work on this here: https://github.com/aanand/fig/tree/parallel-scale

**Comment by mnowster** [comment]
https://github.com/docker/compose/pull/1734

**Comment by aanand** [comment]
Closed by #1734.
