### ISSUE TITLE
allow ignoring unsupported config options

### ISSUE THREAD

**Issue by brancz** [docker/compose#1655]
There are tools and services popping up that orient themselves on the `docker-compose.yml` specification. However for some use-cases it is necessary to extend this reference, but when trying to use the same `docker-compose.yml` in `dev`, `test` and `prod` it causes docker-compose to exit and say `unsupported config options ...`. I propose a flag such as `--ignore-unsupported` which only skips an option and prints that compose skipped that option since it is unknown. Any thoughts?

**Comment by raohuaming** [comment]
I like the idea +1

**Comment by aanand** [comment]
A flag would be one way to do it; another would be a way to allow unsupported options as long as they're explicitly demarcated as such. For example, CSS has [vendor prefixes](http://www.sitepoint.com/web-foundations/vendor-specific-properties/); perhaps we could do something with a similar structure.

Or we could allow reverse-DNS notation, e.g. `com.example.new-option`.

**Comment by dnephin** [comment]
I like the idea of vendor prefixes. We should allow field starting with `x-` to be ignored by our validation.

**Comment by fentas** [comment]
Any progress on this? +1

**Comment by marcosnils** [comment]
:+1:

**Comment by wallyqs** [comment]
+1

**Comment by ProTip** [comment]
This would help me out a ton too. Any direction on this?

**Comment by gionn** [comment]
@dnephin what are the chances that a submitted PR with vendor prefix support will get merged for the next release?

**Comment by dnephin** [comment]
Closing as duplicate of #2942

**Comment by vzuevsky** [comment]
Sorry can docker(conpose) ignore unsupported options or not? If former, what option does it? If latter, why not?
