### ISSUE TITLE
how can we define --memory-swap in docker-compose.yml?

### ISSUE THREAD

**Issue by mboussaa** [docker/compose#1667]
Hello

How can we define --memory-swap in docker-compose.yml?
I am getting this error Unsupported config option for "" service: 'memory-swap'

I have to define all these options also:
-m, --memory="": Memory limit (format: <number><optional unit>, where unit = b, k, m or g)
-memory-swap="": Total memory limit (memory + swap, format: <number><optional unit>, where unit = b, k, m or g)
-c, --cpu-shares=0: CPU shares (relative weight)
--cpu-period=0: Limit the CPU CFS (Completely Fair Scheduler) period
--cpuset-cpus="": CPUs in which to allow execution (0-3, 0,1)
--cpuset-mems="": Memory nodes (MEMs) in which to allow execution (0-3, 0,1). Only effective on NUMA systems.
--cpu-quota=0: Limit the CPU CFS (Completely Fair Scheduler) quota
--blkio-weight=0: Block IO weight (relative weight) accepts a weight value between 10 and 1000.
--oom-kill-disable=true|false: Whether to disable OOM Killer for the container or not.

Thanks in advance.

**Comment by mnowster** [comment]
Hi there,

The ability to set the memory swap limit isn't supported yet. The good news is it will be available in the upcoming release of 1.4. 

This PR shows how to set the limit. https://github.com/docker/compose/pull/1660/files

Hope this helps :palm_tree:

**Comment by mboussaa** [comment]
Thank you for the list of ressources management what is already supported ? 
I can see that cpuset, cpu_shares and mem_limit but what else? 
Another question: When will the version 1.4 be released ? 

Thank you

**Comment by mnowster** [comment]
This reference should help you with what's supported: https://docs.docker.com/compose/yml/

I believe the target date is 4th of August. https://github.com/docker/compose/wiki

**Comment by mboussaa** [comment]
Yes in fact, only 3 ressource management options are supported : 
cpuset, cpu_shares and mem_limit
it will be good to see more supported options in compose.

I have another question: in docker-compose.yml, I am trying to build an image from a dockerfile however when executing the file it still search for the image from HUB. What should I do ?

**Comment by mnowster** [comment]
Please open that as a separate issue and include more details of what you're doing and the .yml file. Thank you!
