### ISSUE TITLE
Restarting service `docker-compose restart my_service` takes longer then the actual restart.

### ISSUE THREAD

**Issue by Neppord** [docker/compose#1675]
I have a command that restarts the service whenever my source files changes. After a while the restart command don't exit (in any reasonable time). But if I take a look at the logs then I can see that the service have indeed restarted long before compose exits.

**Comment by dnephin** [comment]
You're running `docker-compose restart` ? 

Please include the output of `docker-compose version` and `docker-compose --verbose restart`

**Comment by Neppord** [comment]
@dnephin im closing this issue, it is to old, it might not be a issue anymore.
