### ISSUE TITLE
zsh completion: parse error near `)'

### ISSUE THREAD

**Issue by k0377** [docker/compose#1681]
I get an error, when I run the command from https://docs.docker.com/compose/completion/ to install completion for zsh:

```
manu:~/ $ mkdir -p ~/.zsh/completion
manu:~/ $ curl -L https://raw.githubusercontent.com/docker/compose/
$\(docker-compose --version | awk 'NR==1{print $NF}')/contrib/compl
etion/zsh/_docker-compose > ~/.zsh/completion/_docker-compose
zsh: parse error near `)'
```

**Comment by LeoCavaille** [comment]
The command you typed is different from the command in the docs:
```
curl -L https://raw.githubusercontent.com/docker/compose/$\(docker-compose --version | awk 'NR==1{print $NF}')/contrib/completion/zsh/_docker-compose > ~/.zsh/completion/_docker-compose
# vs. the correct one
curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose --version | awk 'NR==1{print $NF}')/contrib/completion/zsh/_docker-compose > ~/.zsh/completion/_docker-compose
```

See the backslash that was added, might be because of some auto-escaping going on in your terminal. This issue should be closed?

**Comment by k0377** [comment]
You're right! I didn't notice the backslash, happens the first time to me. I also tried to copy paste into different terminal emulators: urxvt, xfce4-terminal, lxterminal. Everywhere the same behaviour. The backslash was added from the terminal. Maybe this should be mentioned in the documentation. Thank's for the quick solution!

**Comment by chikamichi** [comment]
Thx for the insignt @LeoCavaille, I didn't notice the backslack either.

**Comment by leggomuhgreggo** [comment]
For anyone else encountering this issue, it is in fact an issue with zsh adding backslashes to URLs

https://stackoverflow.com/questions/25614613/how-to-disable-zsh-substitution-autocomplete-with-url-and-backslashes

**Comment by Esslamb** [comment]
Thanks, @leggomuhgreggo .  For anybody else running into this remove the backslash from ` $\(uname -s)` when pasting the command in ZSH.

**Comment by soyab-mostofa** [comment]
> The command you typed is different from the command in the docs:
> 
> ```
> curl -L https://raw.githubusercontent.com/docker/compose/$\(docker-compose --version | awk 'NR==1{print $NF}')/contrib/completion/zsh/_docker-compose > ~/.zsh/completion/_docker-compose
> # vs. the correct one
> curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose --version | awk 'NR==1{print $NF}')/contrib/completion/zsh/_docker-compose > ~/.zsh/completion/_docker-compose
> ```
> 
> See the backslash that was added, might be because of some auto-escaping going on in your terminal. This issue should be closed?

this helped me installing vlc in fedora.
