### ISSUE TITLE
docker-compose run without mounting volume

### ISSUE THREAD

**Issue by kevinsimper** [docker/compose#1682]
I run tests with docker-compose, but because it mounts the volume inside when you do it, I have to install dependencies again.

What i do to run test locally: 
`docker-compose run backend npm test`

But on CicleCi I build my containers first with `docker-compose build` and they are completly runable, but docker-compose makes it easier because it starts `links` at the same time.

So on circleci i have to do
`docker-compose run backend /bin/bash -c "npm installl && npm test"``

which takes longer because i have to do npm install twice.

I want to do

`docker-compose run --no-volumes backend npm test`

**Comment by aanand** [comment]
I don't have much experience with Node, but I believe npm will climb through parent directories until it finds a `node_modules` directory, so in your Dockerfile, after running `npm install`, you could move `node_modules` to the parent directory.

**Comment by kevinsimper** [comment]
@aanand Node.js was just an example, there could be cases where you want to run a `one-off` container and not have any side-effects.

**Comment by iandyh** [comment]
@kevinsimper Isn't the opposite case? You want the volume to be mounted inside container and after first run you will have the dependencies there and no need to install again. 

So what I am finding now is that after first `docker-compose run web mvn test`, the mounted directory `/root/.m2/repository` is empty so the next run still requires to download all the dependencies.

Of course, `mvn`(maven) and `npm` are similar here.

**Comment by dnephin** [comment]
This can now be solved with #2051 (in the 1.5.0 release).

You can override `volumes` to add them or remove them for different environments.

**Comment by callumgare** [comment]
I believe this issue should be reopened since despite the name it is not actually possible to override values like volumes <https://github.com/docker/compose/issues/3729>. You can add new volumes but not cancel out existing ones.
