### ISSUE TITLE
Move docker_client.py into docker-py

### ISSUE THREAD

**Issue by delfick** [docker/compose#1683]
Hello,

Are we able to get https://github.com/docker/compose/blob/master/compose/cli/docker_client.py put into docker-py itself so other libraries don't have to replicate this logic?

i.e. I expect docker.Client() to search for DOCKER_HOST and related tls environment variables.

Thanks.

**Comment by linlinlinlin** [comment]
By the way, docker-py released 1.3.0 and requests released 2.7.0. :grin:

**Comment by aanand** [comment]
It actually is there, under `docker.utils.kwargs_from_env`. I believe the only difference is that we set `assert_hostname` to `False`. We should get rid of our duplicated logic.

**Comment by delfick** [comment]
ah, there is too. Awesome. Thanks for pointing that out.

**Comment by bfirsh** [comment]
https://github.com/docker/compose/issues/644

Thanks for the reminder @delfick :)

**Comment by aanand** [comment]
https://github.com/docker/compose/pull/1744
