### ISSUE TITLE
Misleading message upon ports parse error

### ISSUE THREAD

**Issue by spacediver** [docker/compose#1684]
Hi folks,

Consider the following docker-compose.yml

    test:
        image: spacediver/python
        ports:
          - "127.0.0.180:80"

Notice the error in ports, originally I meant  to say "127.0.0.1:80:80"

Trying to start it we may see (with docker 1.7.0, docker-compose 1.3.0) this:

    root@17934123d4d1:~# docker-compose up                 
    Creating root_test_1...
    Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
    
Why would this happen? 

Running docker with -D reveals (http://pastebin.com/caDWGW8Q) that there's an exception in daemon that happens at parsing invalid ports directive ("127.0.0.180:80")

Trying to run the same with docker CLI would validate ports directive well before sending to daemon:

    root@17934123d4d1:~# docker run --rm -ti -p 127.0.0.180:80 spacediver/python 
    docker: Invalid hostPort: 127.0.0.180.
    See 'docker run --help'.
             
I'm not pretty sure how to properly fix this, but it seems that docker-compose could probably validate ports directive not worse than docker CLI does?

**Comment by aanand** [comment]
This is most definitely a bug in the daemon - it should not crash if you send it bad data. Have you opened an issue on docker/docker?

**Comment by spacediver** [comment]
Thanks for pointing out, opened it: https://github.com/docker/docker/issues/14621

**Comment by dnephin** [comment]
Looks like this was fixed in the daemon

**Comment by spacediver** [comment]
awesome!
