### ISSUE TITLE
Readline errors when running binary on arch linux

### ISSUE THREAD

**Issue by renato-zannon** [docker/compose#170]
Hi!

If I get the binary from `https://github.com/orchardup/fig/releases/download/0.3.2/linux` and run on my Arch Linux, I get a few errors on startup:

```
$ /usr/local/bin/fig --version
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
fig 0.3.2
```

However, if I install directly from pip, these errors don't appear.

From a bit of googling it seems to me they are related to the readline version... Might be some incompatibility with a bundled library in the binary version.

I haven't had any issues apart from the annoying messages though (console apps work fine).

**Comment by yawnt** [comment]
+1

**Comment by fantattitude** [comment]
Still a thing :(

Any idea how we can fix this (installing readline or something) ?

**Comment by jghibiki** [comment]
+1

**Comment by jpanganiban** [comment]
I'm having the same issue as well. Running on Arch and installed fig from the shell script posted in the website.

**Comment by cosmicnag** [comment]
+1

**Comment by lapubell** [comment]
+1

**Comment by diegomvh** [comment]
+1

    $ fig --version
    sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
    sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
    sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
    sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
    fig 1.0.1

Running on Arch and installed fig using the shell script

**Comment by atmoz** [comment]
+1

**Comment by aanand** [comment]
We should investigate whether building the binary on Arch Linux solves this problem. This basically means changing the `FROM` line at the top of the Dockerfile to an Arch image (sadly, there doesn't seem to be an official one) and then getting the rest of the build to work.

**Comment by bketelsen** [comment]
./docker-compose-Linux-x86_64
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
Fast, isolated development environments using Docker.

Still an issue.

**Comment by toddpi314** [comment]
+1 still an issue

**Comment by Ovski4** [comment]
+1

**Comment by mariorez** [comment]
:+1: . I'm using "docker-compose".
```
$ docker-compose --version
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
docker-compose 1.1.0
```

**Comment by k2s** [comment]
+1

**Comment by nerro** [comment]
:+1:  same problem

    $ docker-compose --version
    sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
    sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
    sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
    sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
    docker-compose 1.1.0

**Comment by jvanveen** [comment]
pip2 install docker-compose worked for me...

**Comment by mariorez** [comment]
:+1: @jvanveen - For installation with PIP*2* (docker-compose not works with "pip" version 1)
```pip2 install docker-compose```

**Comment by nerro** [comment]
@jvanveen, you're right, it works with `python2-pip` package, but this package has `python2` and `python2-setuptools` as dependencies :worried:. As crazy minimalist I try to keep my system clean and with minimal package count (currently 220 :wink:)

**Comment by skarekrow** [comment]
You could also just use a container for this. Like : https://registry.hub.docker.com/u/dduportal/docker-compose and set up an alias. That works everywhere you use docker.

**Comment by toddpi314** [comment]
Lolz @skarekrow

**Comment by skarekrow** [comment]
I was serious ;) It works great for me.

**Comment by hardbyte** [comment]
BTW Install seems to work with `pip3`, but then `docker-compose` breaks when you run it.

**Comment by nerro** [comment]
@toddpi314 thanks for motivational kick :smile:.
I will release version `1.2.0` for archlinux today.

**Comment by NicolasCARPi** [comment]
@nerro, same error on Archlinux with 1.2.0.

**Comment by nerro** [comment]
@NicolasCARPi, error with my custom release?
I see no errors on my developer machine. If errors exists, send me please `pacman -Q` output.

**Comment by NicolasCARPi** [comment]
@nerro, nope sorry I was speaking of the official release. I just tried with yours and it's fine (thank you for providing it :)).

Cheers.
~Nico

**Comment by psftw** [comment]
I'm not sure there is a good solution here.  The users with this issue are executing the binary release on a system with libreadline > 6.2 (in my case Gentoo *and* Arch) and the binary is not expecting this newer version.  I see where we switched from ubuntu:14.04 down to debian:wheezy to accommodate users with older glibc, in the opposite scenario.  I confirmed that by switching the build environment to Jessie, I can produce a binary that can interop with my local libreadline 6.3, but then it introduces the `version 'GLIBC_2.14' not found` issue (for other older systems with < 2.14 such as centos6).  So we have glibc which requires us to compile against on an older version to be forwards-compatible, and libreadline which requires us to compile against a newer version to be backwards-compatible.  Sorry, don't have a good solution in mind, but I think I understand the problem better now.

**Comment by dnephin** [comment]
One solution would be to fix how this is packaged. A single dynamically linked binary is always going to cause problems.

**Comment by nerro** [comment]
@psftw @dnephin,
Can we make it with Debian dockerfile?
I thought the project will be rewritten in Go or I misunderstood something?

**Comment by eggman64** [comment]
+ 1

**Comment by urquilla** [comment]
+1

**Comment by UserTaken** [comment]
Version 1.3.0 has fixed the `sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook` error on my Arch systems.

**Comment by nlamirault** [comment]
+1. FIX in version 1.3.0

**Comment by nerro** [comment]
LGTM :+1: confirm, version `1.3.0` works without this error.

@renato-zannon I think the issue can be closed.

**Comment by psftw** [comment]
1.3.0 on Gentoo also confirmed working. Good stuff!
