### ISSUE TITLE
Add a --timeout parameter to `docker-compose scale`

### ISSUE THREAD

**Issue by pataquets** [docker/compose#1707]
AFAIK, when you scale down a service, the excess containers get an stop command.
However, they can get killed prematurely if the stop is not quick enough.
Allowing for a stop timeout as it's done in 'docker stop' would solve this.

**Comment by aanand** [comment]
This is actually a bug - we do send a timeout, but it's badly formatted. See #1704.

**Comment by pataquets** [comment]
Will this timeout be customizable?

**Comment by aanand** [comment]
Hm, the timeout isn't customisable on `scale` - that should be a flag.

**Comment by aanand** [comment]
See #1714.

**Comment by pataquets** [comment]
Thanks!
