### ISSUE TITLE
Support mapping specific ports in "docker-compose run"

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1709]
It should be possible to pass the `-p` option to expose ports when doing `docker-compose run`. It should probably be not be possible to use this option in combination with the `--service-ports` option.

This is part of #363.

**Comment by mrfuxi** [comment]
I started looking into this and I think I have it working. Have to write tests and docs.
Can I be assigned to this ticket, please?

**Comment by aanand** [comment]
@mrfuxi Great! I don't think non-staff can be assigned, but feel free to submit the PR in an unfinished state if you want early feedback.

**Comment by mrfuxi** [comment]
I did as you suggested, thanks @aanand
