### ISSUE TITLE
A manual page for docker compose

### ISSUE THREAD

**Issue by chaica** [docker/compose#1727]
Hi,

For the Debian package of Docker Compose in Stretch (Debian Testing), a manual page was written by Dariusz Dwornikowski <dariusz.dwornikowski@cs.put.poznan.pl>. You can get it at:
https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=31;filename=docker-compose.1;att=1;bug=792518

It would be great if you could include it upstream.

Regards,
--
Carl Chenet <chaica@debian.org>

**Comment by dnephin** [comment]
I'd rather not maintain another copy of this help text.  We'd like to remove the copy from our docs and have it auto-generated from the help text (#2043).

I think we should do the same for the man page using [help2man](https://www.gnu.org/software/help2man/).

If we do #2235 we can look to include them as part of the packaging.
