### ISSUE TITLE
Couldn't connect to Docker daemon at http://127.0.0.1:2376 - is it running?

### ISSUE THREAD

**Issue by kadishmal** [docker/compose#1733]
I'm having issues with docker-compose connecting to a swarm cluster.

I have a docker engine running locally on port 2375 and swarm running on port 2376. There are 3 physical machines in the cluster. The docker clients points to the swarm so, doing the following returns the cluster information.

	$ docker info
	Containers: 7
	Images: 28
	Role: primary
	Strategy: spread
	Filters: affinity, health, constraint, port, dependency
	Nodes: 3
	 swarm-1: 192.168.116.98:2375
	  ?? Containers: 2
	  ?? Reserved CPUs: 0 / 25
	  ?? Reserved Memory: 0 B / 132.3 GiB
	  ?? Labels: executiondriver=native-0.2, kernelversion=2.6.32-504.3.3.el6.x86_64, operatingsystem=<unknown>, storagedriver=devicemapper
	 swarm-2: 192.168.116.99:2375
	  ?? Containers: 2
	  ?? Reserved CPUs: 0 / 25
	  ?? Reserved Memory: 0 B / 132.3 GiB
	  ?? Labels: executiondriver=native-0.2, kernelversion=2.6.32-504.3.3.el6.x86_64, operatingsystem=<unknown>, storagedriver=devicemapper
	 swarm-3: 192.168.116.100:2375
	  ?? Containers: 3
	  ?? Reserved CPUs: 0 / 25
	  ?? Reserved Memory: 0 B / 132.3 GiB
	  ?? Labels: executiondriver=native-0.2, kernelversion=2.6.32-504.3.3.el6.x86_64, operatingsystem=<unknown>, storagedriver=devicemapper
	CPUs: 75
	Total Memory: 396.9 GiB

My `DOCKER_HOST=tcp://127.0.0.1:2376` points to swarm now.

I can do `docker ps` and `docker info` to see the cluster status, however `docker-compose up` complains saying:

	$ docker-compose --verbose up -d
	Compose version 1.3.3
	Docker base_url: http://127.0.0.1:2376
	Docker version: KernelVersion=, Arch=amd64, ApiVersion=1.16, Version=swarm/0.3.0, GitCommit=28cd51b, Os=linux, GoVersion=go1.3.3
	docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=dockerengine', u'com.docker.compose.service=redis', u'com.docker.compose.oneoff=False']})
	Couldn't connect to Docker daemon at http://127.0.0.1:2376 - is it running?

	If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

What could be the problem?

I can even do `docker run --rm -it centos bash` and Swarm will start the container and put me into the bash session.

So Swarm is working fine, but `docker-compose` version 1.3.3 cannot connect to Swarm

Can anybody suggest any ideas?

My `docker-compose.yml` is simple for testing purpose:

	mongo:
	  image: mongo:3.0.4
	  ports:
	   - "27017:27017"
	redis:
	  image: redis:2.8
	  ports:
	   - "6379:6379"

	$ docker version
	Client version: 1.7.1
	Client API version: 1.19
	Go version (client): go1.4.2
	Git commit (client): 786b29d
	OS/Arch (client): linux/amd64
	Server version: swarm/0.3.0
	Server API version: 1.16
	Go version (server): go1.3.3
	Git commit (server): 28cd51b
	OS/Arch (server): linux/amd64

	$ cat /etc/redhat-release
	CentOS release 6.6 (Final)
	
	$ uname -a
	Linux xseed120.kdev 2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aanand** [comment]
Is Swarm using TLS? Are your Docker environment variables configured to enable/disable TLS accordingly (`DOCKER_TLS_VERIFY` and `DOCKER_CERT_PATH`)?

They probably are if the docker client works, but it'd be good to narrow it down. If you *are* using TLS, try disabling it.

**Comment by kadishmal** [comment]
No, TLS is not enabled. The nodes are running in a secured internal network. I plan to to enable them when the nodes go public, but for now even without TLS `docker-compose` doesn't work.

**Comment by aanand** [comment]
> Where does Swarm log connection and other information?

Not sure - ping @vieux 

Can you `curl --verbose http://127.0.0.1:2376/version`?

**Comment by AndrewGrachov** [comment]
Having same problems - curl returns empty response

**Comment by AndrewGrachov** [comment]
@kadishmal , please let me know if you found teh way to fix that - blocking me right now

**Comment by AndrewGrachov** [comment]
Figured this out - wrong ports directive inside docker-compose.yml
```
  ports:
   - 0.0.0.0:10500
```
docker panics, and returns no response
logs from */var/log/docker.log* (Ubuntu)
```
2015/08/26 15:41:43 http: panic serving 127.0.0.1:51455: strconv.ParseUint: parsing "0.0.0.0": invalid syntax
goroutine 811 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/nat.Port.Int(0xc20867b1c0, 0x7, 0x141ce08)
	/go/src/github.com/docker/docker/nat/nat.go:60 +0x99
github.com/docker/docker/daemon.(*Container).buildCreateEndpointOptions(0xc208622000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_linux.go:720 +0xb2a
github.com/docker/docker/daemon.(*Container).AllocateNetwork(0xc208622000, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_linux.go:768 +0x377
github.com/docker/docker/daemon.(*Container).initializeNetworking(0xc208622000, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container_linux.go:839 +0x503
github.com/docker/docker/daemon.(*Container).Start(0xc208622000, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:255 +0x1cf
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc2080be2a0, 0xc208143047, 0x40, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/start.go:35 +0x243
github.com/docker/docker/api/server.(*Server).postContainersStart(0xc2080d7080, 0xc208143037, 0x4, 0x7f155efe5620, 0xc2087d2e60, 0xc20884f040, 0xc20844a360, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:1028 +0x162
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersStart)·fm(0xc208143037, 0x4, 0x7f155efe5620, 0xc2087d2e60, 0xc20884f040, 0xc20844a360, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:1550 +0x7b
github.com/docker/docker/api/server.func·008(0x7f155efe5620, 0xc2087d2e60, 0xc20884f040)
	/go/src/github.com/docker/docker/api/server/server.go:1501 +0xacd
net/http.HandlerFunc.ServeHTTP(0xc208036580, 0x7f155efe5620, 0xc2087d2e60, 0xc20884f040)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080dd220, 0x7f155efe5620, 0xc2087d2e60, 0xc20884f040)
	/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc2081981e0, 0x7f155efe5620, 0xc2087d2e60, 0xc20884f040)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20850c8c0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

Changed to
```
  ports:
   - 0.0.0.0:10500:8181
```
And all ok.

Hope it will help somebody :)

**Comment by dnephin** [comment]
Glad you got this fixed. We've improved the config validation since this happened.

Since this is a bug in docker, and not actionable from compose, I'm going to close this issue.
