### ISSUE TITLE
Memory limit and CPU for the whole docker compisition

### ISSUE THREAD

**Issue by tarlabs** [docker/compose#1735]
Hello,

I have a situation where we need to create multiple environments on the same machine. For each environment I have docker-compose.yml file. The host machine is 32 GB + 8 cores. We want to be able to associated 2 cores + 8 GB to each composition. A composition is having around 8 containers in total. Now I know we can limit memory per container, which doesn't work for me as I want the whole limit to be applied on the composition. 

Is there a possible way to do this?

Regards,
Tarun

**Comment by aanand** [comment]
Unfortunately not - Docker only lets you set resource usage constraints per-container.

**Comment by tarlabs** [comment]
@aanand, possible to run a parent container and run the whole composition inside that container?

**Comment by aanand** [comment]
You can use [docker-in-docker](https://github.com/docker/docker/blob/master/hack/dind) to run containers inside a container, but I don't know if resource limitations will apply.

**Comment by tarlabs** [comment]
Thanks @aanand, I will try it out soon and post if I have any feedback
