### ISSUE TITLE
docker-compose run cannot find the mounted volume

### ISSUE THREAD

**Issue by iandyh** [docker/compose#1740]
Hi

I am using `docker-compose web mvn test` to run the tests. To avoid downloading dependencies multiple times, I've added `/root/.m2/repository` as data volume.

However, after the first `docker-compose web mvn test`, the data in `/root/.m2/repository` was not persisted therefore the next run will need to download all the dependencies again.

On the other hand, `docker-compose up` is able to persist all the data after restarting the containers.

I am using Boot2docker on a MacBook. The boot2docker version is `v1.7.0` while Docker client and server version is `v1.7.0` as well.

Thanks for your help.

**Comment by aanand** [comment]
I presume you mean `docker-compose run web mvn test`.

Could you paste the output of `docker inspect` on one of the working containers created by `docker-compose up`, and on one of the non-working containers created by `docker-compose run`?

**Comment by iandyh** [comment]
@aanand Yes. Sorry for the typo.

Interestingly, the `docker inspect` to the working container gives me am empty dict:

`Volumes": {
            "/code": {},
            "/root/.m2/repository": {}
}`

So does the non-working container.

Also I change the default vboxfs to NFS for mounting volumes from host to boot2docker for performance reason. But I doubt it will have effect on this.

Thanks for the reply!

**Comment by iafilatov** [comment]
Could you paste the output of `docker inspect -f '{{.HostConfig.Binds}}' <container>` for both?

**Comment by dnephin** [comment]
No response to request for more details, so closing the issue.

**Comment by vimalprakashts** [comment]
I am also facing the same issue.
