### ISSUE TITLE
env_file should take precedence on environment variables

### ISSUE THREAD

**Issue by docteurklein** [docker/compose#1741]
I don't understand why it's the other way around.
Changing it means you could have some default values hardcoded in yml, but still allow for custom values per install.

**Comment by aanand** [comment]
It was done that way for symmetry with `docker run` (where `--env` takes precedence over `--env-file`), but I agree it's not the most useful.

Changing it would break backwards compatibility, so it'd probably need to be a two-step process of releasing a version that warns about the change if you have variables that conflict, and then making the change in the next version.

**Comment by thaJeztah** [comment]
if we want this, I think both docker and compose should change (to keep the same behavior)

**Comment by dnephin** [comment]
Closing this since it needs to happen in docker engine first, and it's unlikely we'll be breaking backwards compatibility.
