### ISSUE TITLE
`docker-compose pull SERVICE` pulls dependencies

### ISSUE THREAD

**Issue by aanand** [docker/compose#1752]
If a service `web` depends on a service `db`, and both services specify an image, then `docker-compose pull web` will pull the images for both db and web, rather than just web. There's no `--no-deps` workaround either.

**Comment by gilclark** [comment]
I changed include_links to include_deps.  So it was generalizing the notion of a working with a dependency.  In the past if one was pulling an image and it had links to another image that dependency would be pulled too.  Now it's the same idea just more generalized (links, volumes, net).

**Comment by aanand** [comment]
I've just realised it was always passing `True` as the argument name. Apologies for not actually reading the diff. I've deleted that part of the issue description so people don't get confused by it.

**Comment by cweagans** [comment]
Just opened a PR for this: #2199
