### ISSUE TITLE
Docker-compose libz.so.1 file too short

### ISSUE THREAD

**Issue by melaleuca5** [docker/compose#1761]
When running docker-compose on ubuntu I get 
docker-compose: error while loading shared libraries: /tmp/_MEIE6DGW6/libz.so.1: file too short

**Comment by melaleuca5** [comment]
Fixed it seems when I moved the docker /var/lib/docker to a new drive it caused it

**Comment by aanand** [comment]
Glad you got it sorted!

**Comment by marksteve** [comment]
@melaleuca5 how did you fix it?

**Comment by julienvincent** [comment]
@melaleuca5 Same problem. How was this solved?

**Comment by tuhrig** [comment]
Same problem here. I need to destroy and create my Vagrant VM every couple of days to come around this problem. Would be great if you could have another look at this.

**Comment by julienvincent** [comment]
I solved it by doing a `apt-get install --reinstall docker.io` and then restarting my VM. Not sure if that will solve yours too.

**Comment by shrikrishnaholla** [comment]
@aanand  Can you reopen this? Seems like a few people are still getting it. For me, I had to resize my VM because of docker bloat and now docker-compose is complaining

> docker-compose-1.4.0: error while loading shared libraries: /tmp/_MEI0qlFSu/libz.so.1: file too short

Since I've just resized and booted into my new volume, /tmp is empty. Seems like docker-compose is storing this reference somewhere. How do I clear it?

**Comment by shrikrishnaholla** [comment]
I kinda figured out what had happened in my case. Somehow `/tmp` had gotten mounted to a block device with a 1M size limit. So when `docker-compose` tried to create files, it couldn't and the next stage (or whatever) expected those files to be present and panicked when they weren't found. In my case, unmounting `/tmp` worked, but the solution may be different for others. As for the fix, I haven't looked into the source code yet, but maybe some kind of exception handling when trying to create the files in the temp directory might help.

**Comment by aanand** [comment]
Unfortunately, the "creating files in `/tmp`" step is out of our control - it's [how PyInstaller's binaries work](http://pythonhosted.org/PyInstaller/#how-the-one-file-program-works).

**Comment by shrikrishnaholla** [comment]
Raised the issue upstream

**Comment by htgoebel** [comment]
Why are you using a frozen app at all? Simply install `compose` like any other python program and you do not have this problem - you are ion Linux, you have the power.

**Comment by htgoebel** [comment]
Fixed upstream, see https://github.com/pyinstaller/pyinstaller/issues/1429

**Comment by aanand** [comment]
Nice. Marking this as a bug to remind us to update our PyInstaller version.

**Comment by codewarrior0** [comment]
I think the underlying problem is that `/tmp` isn't cleaned out often enough. The default setting on most systems is to clean it out on reboot, and servers are not frequently rebooted nowadays. Maybe the real fix is to clean out `/tmp` more frequently using a cron job or something like `tmpreaper`.

**Comment by dnephin** [comment]
We've upgraded to pyinstaller 3 (#2245). You can try out the new binary by downloading a master build here: https://dl.bintray.com/docker-compose/master/

The fix should also be in the 1.5.0 release.

Let us know if you continue to experience this problem, and we can re-open the issue.

**Comment by shrikrishnaholla** [comment]
Thanks! I've begun using `pip` builds instead of the binary, but this will probably be useful for others. :+1:

**Comment by dnephin** [comment]
There's been another report in #1339 that this is stil an issue. Since this seems like a duplicate I think we can track it in #1339
