### ISSUE TITLE
container creation fails if there is a single-file volume mount over existing file

### ISSUE THREAD

**Issue by codl** [docker/compose#1771]
If my docker-compose.yml contains a volume that is a single file being mounted over a file that already exists in the image, it fails with the error "cannot mount volume over existing file, file exists"

However I can do the same thing from `docker run` and it starts up just fine

Also this used to work fine a few months ago

**Comment by shuron** [comment]
how to bypass that?

**Comment by ydplondoner** [comment]
I see the same issue with Docker version 1.9.1 and docker-compose 1.5.1

**Comment by lrkwz** [comment]
What does your docker.compose.yml look like?
