### ISSUE TITLE
I'd like to have something like "docker-compose login <container_name>"

### ISSUE THREAD

**Issue by victorliun** [docker/compose#1772]
Hi

Is there something like "docker-compose login <container_name>", so I don't have to run "docker exec -it container_name bash" manually?

Thanks
Victor Liu

**Comment by josephpage** [comment]
Probably duplicate of docker/compose#593

docker-compose will supports `docker-compose exec -it service_name bash` in the future.
Contributions are accepted ! :wink:

**Comment by dnephin** [comment]
Closing as duplicate of #593
