### ISSUE TITLE
Feature Request: docker-compose ls

### ISSUE THREAD

**Issue by stephanbuys** [docker/compose#1773]
When wrapping docker-compose into automation I've got a couple of scripts that run a series of docker-compose files in a row. If I just wanted to run a file that contains a specific server it would be super handy to have a 'docker-compose ls' option that spits the name of the containers it would create out to the command line. Inspired by docker-machine ls 

Anyone else think this would be useful?

My other option is to grep the files for 'service:\n' lines, this works ok but can be much better, especially if --filter functionality gets implemented too.

**Comment by dnephin** [comment]
You can get the container ids after the containers are started using `docker-compose ps -q`

**Comment by stephanbuys** [comment]
@dnephin ah, this is specifically aimed at the manifest and not the running containers. I would like to determine if I'm looking at the appropriate `docker-manifest.yml` without a round-trip to the docker daemon.

**Comment by dnephin** [comment]
I can think of at least one use case for this (described here https://github.com/docker/compose/issues/374#issuecomment-126401655).

**Comment by dnephin** [comment]
I believe this was actually already implemented in PR #1077

**Comment by dnephin** [comment]
I believe this is handled by `docker-compose config --services` added in 1.6.0 (RC1 was just released).

It will list the service names without needing any docker daemon.
