### ISSUE TITLE
Document the -v flag for docker-compose rm

### ISSUE THREAD

**Issue by faceleg** [docker/compose#1782]
It was not until I read this https://github.com/docker-library/mysql/issues/51#issuecomment-85115112 that I realised `rm` did not delete the volumes.

Please update the [documentation](https://docs.docker.com/compose/cli/#rm) to note the `-v` flag for `docker-compose rm`?

**Comment by aanand** [comment]
Good find. The docs have been overhauled, and [the new page for rm](https://github.com/docker/compose/blob/master/docs/reference/rm.md) documents the flag, so it'll be fixed in the next release.

**Comment by faceleg** [comment]
:dancers: this will save fools like me hours, thanks!
