### ISSUE TITLE
Pass port to docker-compose?

### ISSUE THREAD

**Issue by nottrobin** [docker/compose#1791]
I need to be able to let the individual developer decide which port to map to to the service. I could do this within Docker like:

``` bash
docker -p 8012:5000 run my-image
```

And of course I can set the local port in `docker-compose.yml`:

``` yaml
service:
  ports: ["8012:5000"]
```

But the developer who runs `docker-compose up` has no control over this port mapping. Given that it is the dev who really knows which ports are available and which port they want to use for development, it would make sense for them to be able to pass through the host port from the command-line.

There's one way I can think of to do this, with the bleeding edge `1.4.0rc2`:

``` bash
echo "new-service: {extends: {file: 'docker-compose.yml', service: 'old-service'}, ports: ['8015:5000']}" | docker-compose --file - up
```

But that's pretty ugly.

Given this is surely such a useful feature, is there any simpler way to do it? It seems to me there are three possibilities:

- Allow overriding of *all* the directives in `docker-compose.yml` through the CLI, making the interface to `docker-compose up` similar to that of `docker run`
- Support variables inside `docker-compose.yml` (currently [being worked on](https://github.com/docker/compose/issues/1377))
- Add a specific option to `docker-compose up` like `--local-port=8012`

Am I missing an obvious option here?

**Comment by aanand** [comment]
No, you're not missing an obvious option. Environment variable interpolation is the way to do it.

**Comment by nottrobin** [comment]
@aanand and that's not implemented yet right?

**Comment by aanand** [comment]
Correct.

**Comment by funkyfuture** [comment]
see #1377.

**Comment by pwaller** [comment]
#1765 was merged, so this can be closed.
