### ISSUE TITLE
Docker Compose exitable or One time containers

### ISSUE THREAD

**Issue by tarlabs** [docker/compose#1792]
Hello,

I am in this situation where I want to run one of the image as a part of docker-compose, but that image should do it work and then exit. But as soon as that container exits the whole composition is taken down.

Is there a way to allow running containers which are allowed to exit from a composition once the work is done?

Regards,
Tarun

**Comment by aanand** [comment]
Fixed in #1754.

**Comment by tarlabs** [comment]
Is this released or will be in next version?

**Comment by aanand** [comment]
It will be in Compose 1.5.0, so not for a while. For now, you can work around it by using `docker-compose up -d && docker-compose logs` instead of `docker-compose up`.

**Comment by tarlabs** [comment]
Thanks @aanand, I didn't earlier realise this problem is not faced when using -d. I thought even -d would work the same way.
