### ISSUE TITLE
Feature Request. New Docker Log Driver "fluentd"

### ISSUE THREAD

**Issue by sunadm** [docker/compose#1801]
in New coming version 1.8.0 of Docker, it support new log driver "fluentd"

Can compose support it in 1.4.0 version?

**Comment by aanand** [comment]
Yep, but we'll need to get https://github.com/docker/docker-py/pull/699 merged and a docker-py release out first.

**Comment by athieriot** [comment]
Docker 1.8.0 also adds a "Gelf" log driver, should it be a separate issue?

**Comment by bedwards** [comment]
single-commit docker-py PR adding gelf and fluentd - https://github.com/docker/docker-py/pull/724

**Comment by miketonks** [comment]
We could really use this, please can someone action?

**Comment by dnephin** [comment]
It should be in the 1.5.0 release, we just have to upgrade docker-py to 1.4.0
