### ISSUE TITLE
docker-compose reports wrong image when yml image is changed

### ISSUE THREAD

**Issue by CbrandVendini** [docker/compose#1807]
When you update and image:tag in a docker-compose yml file, then stop and up -d docker-compose will reuse the previously built container but will record the new image:tag combination as the source image. The result is that "docker ps" produces an output with a version mismatch that lists the new image:tag combination as the source of a container that is still running the previous image:tag combination.

**Comment by aanand** [comment]
I'm not sure I fully understand. Could you post some steps to reproduce, along with the command output, explaining what's incorrect?

**Comment by CbrandVendini** [comment]
Certainly.

Lets say you docker-compose up -d a yml with the following contents:

web:
  image: internet_server:1
  volumes:
    - /var/log:/var/log/httpd/

docker ps will report an image "internet_server:1" for the web service.

Now we have updated the internet_server image so we run a docker-compose stop. Edit the file so it now looks like this:

web:
  image: internet_server:2
  volumes:
    - /var/log:/var/log/httpd/

Then run a docker-compose up -d against this file.

docker ps will report an image of internet_server:2 for the web service HOWEVER the running container will still actually have a source image of internet_server:1

So essentially there is a image version mismatch between what is reported as the source container and what is actually running.

I'm unsure what the proper behavior is. The options I see are:
1) Docker-compose isn't supposed to explicitly replace the image of a previously run container unless you run docker-compose rm in which case the source image name is being replaced when its not supposed to be.
2) Docker-compose IS supposed to replace the image of a previously run container if it has changed in the yml in which case the image source name is replaced properly but the container itself wasn't updated to reflect the new image.

**Comment by funkyfuture** [comment]
this is also true when you have say a `dev.yml` with a `build`, but a container was already created from another config with an `image`.

you may have a look if `Service.config_hash()` is considered when `up` is run.

**Comment by aanand** [comment]
> docker ps will report an image of internet_server:2 for the web service HOWEVER the running container will still actually have a source image of internet_server:1

If the output of `docker ps` is wrong, that's a serious bug with Docker. How are you determining what image the container "actually" has?

Here's my attempt to reproduce the behaviour:

```
$ docker-compose --version
docker-compose version: 1.4.0rc3

$ cat docker-compose.yml
redis:
  image: redis:2.6

$ docker-compose up -d
Pulling redis (redis:2.6)...
2.6: Pulling from redis

9355a0006ebc: Pull complete
d6dd6eda3519: Pull complete
3b1092a263eb: Pull complete
f9297e2ed9f5: Pull complete
2d09cc3216c4: Pull complete
0db99d2570c2: Pull complete
f805e49fca69: Pull complete
54767d4e03f8: Pull complete
cb2834e893d9: Pull complete
720859ee1bfa: Pull complete
3239f5e87bf7: Already exists
4c8cbfd2973e: Already exists
60c52dbe9d91: Already exists
a81e536d75d2: Already exists
b5385b7b49ae: Already exists
5eced7370894: Already exists
9b5f6b31f2b8: Already exists
redis:2.6: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:db15706e93d3097e4f473a172f830c2a46631414d20d6a80bd38a9923944ebc8
Status: Downloaded newer image for redis:2.6
Creating 1807_redis_1...

$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
f391e1771c58        redis:2.6           "/entrypoint.sh redi   30 seconds ago      Up 16 seconds       6379/tcp            1807_redis_1
```

Then, after changing the image tag in `docker-compose.yml`:

```
$ cat docker-compose.yml
redis:
  image: redis:2.8

$ docker-compose up -d
Recreating 1807_redis_1...
Pulling redis (redis:2.8)...
2.8: Pulling from redis
ccd483713658: Pull complete
2214f9d464dd: Pull complete
c231af3d4fbe: Pull complete
a055745f1b6d: Pull complete
7b6598fb9b79: Pull complete
f393252a4979: Pull complete
04252c65d6ed: Pull complete
cb5b2977ebc4: Pull complete
cd896e1f93cc: Pull complete
2026b511e758: Pull complete
8d79c535f2e4: Already exists
4c8cbfd2973e: Already exists
60c52dbe9d91: Already exists
a81e536d75d2: Already exists
b5385b7b49ae: Already exists
5eced7370894: Already exists
9b5f6b31f2b8: Already exists
redis:2.8: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:a40b07ae3c9555fdff6d0d2e526a3ea63aeed4df1b9ac812f161f2a2c0cde49a
Status: Downloaded newer image for redis:2.8

$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
221557de9e1b        redis:2.8           "/entrypoint.sh redi   16 seconds ago      Up 2 seconds        6379/tcp            1807_redis_1
```

As you can see, the image tag has updated.

**Comment by dnephin** [comment]
No response from original author in 3 months. closing
