### ISSUE TITLE
`docker-compose restart` doesn't restart stopped containers

### ISSUE THREAD

**Issue by tarlabs** [docker/compose#1814]
I have a very simple `docker-compose.yml` file in `docker-restart` folder

```yaml
mysql:
  image: mysql
  environment:
    - "MYSQL_ROOT_PASSWORD=root"
ubuntu:
  image: ubuntu:14.04
  command: date
```

Now if I run the below set of commands
```bash
$ docker-compose up -d
$ sleep 10
$ docker-compose restart dockerrestart_ubuntu_1
$ docker restart dockerrestart_ubuntu_1
$ docker-compose restart dockerrestart_ubuntu_1
$ docker restart dockerrestart_ubuntu_1
```

If I check the logs, I would expect 5 date times, but only 3 appears, docker restart does restart and execute the container but docker-compose doesn't

```bash
$ docker logs dockerrestart_ubuntu_1
Thu Aug  6 07:01:12 UTC 2015
Thu Aug  6 07:02:32 UTC 2015
Thu Aug  6 07:03:14 UTC 2015
```

**Comment by aanand** [comment]
`docker-compose restart dockerrestart_ubuntu_1` is an incorrect invocation - you should use `docker-compose restart ubuntu`.

The former should have returned an error - if it didn't, that's a bug.

**Comment by tarlabs** [comment]
No it didn't give an error

**Comment by tarlabs** [comment]
tarun@linux:~$ docker-compose --version
docker-compose version: 1.3.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

**Comment by aanand** [comment]
I can't reproduce - I get an error as expected:

```
$ docker-compose --version
docker-compose version: 1.3.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014

$ cat docker-compose.yml
mysql:
  image: mysql
  environment:
    - "MYSQL_ROOT_PASSWORD=root"
ubuntu:
  image: ubuntu:14.04
  command: date

$ docker-compose up -d
Creating dockerrestart_mysql_1...
Creating dockerrestart_ubuntu_1...

$ docker-compose restart dockerrestart_ubuntu_1
No such service: dockerrestart_ubuntu_1
```

However, if I use the service name, I do see that the container isn't restarted:

```
$ docker-compose up -d
Recreating dockerrestart_mysql_1...
Recreating dockerrestart_ubuntu_1...

$ docker logs dockerrestart_ubuntu_1
Thu Aug  6 09:55:53 UTC 2015

$ docker-compose restart ubuntu

$ docker logs dockerrestart_ubuntu_1
Thu Aug  6 09:55:53 UTC 2015
```

This is because `docker-compose restart` ignores containers which aren't still running, and `date` has already exited.

Arguably this is a bug, since it deviates from `docker restart`.

**Comment by tarlabs** [comment]
Yes, that is the issue as well. Because there may be some containers which does config and exit and when we restart them they should re-run and exit again. So docker-compose restart should work the way docker restart would work and that what the original bug i opened for.
