### ISSUE TITLE
Bug in Docker Compose 1.3.3 crashes Docker daemon, trashes /var/lib/docker and won't restart

### ISSUE THREAD

**Issue by ricardobranco777** [docker/compose#1822]
1- To reproduce this bug it's convenient to save /var/lib/docker and start with a fresh one:

```
sudo service docker stop
sudo mv /var/lib/docker /var/lib/docker.bak
```

2- Then create a docker-compose.yml file with these contents:

```
test:
  restart: always
  image: busybox
  ports:
   - "0.0.0.0.1234:1234"
```

Notice the typo at ".1234".

3- Now run:

```
docker-compose -f docker-compose.yml up -d

Pulling test (busybox:latest)...
latest: Pulling from busybox
cf2616975b4a: Pull complete
6ce2e90b0bc7: Pull complete
8c2e06607696: Already exists
busybox:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:38a203e1986cf79639cfb9b2e1d6e773de84002feea2d4eb006b52004ee8502d
Status: Downloaded newer image for busybox:latest
Creating tmp_test_1...
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

4- Restart Docker:

```
sudo service docker stop
sudo service docker start
```

5- Try to run docker:

```
sudo docker ps

Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

6- Try to remove /var/lib/docker:

```
sudo rm -rf /var/lib/docker/

rm: cannot remove ‘/var/lib/docker/aufs/mnt/99b76f4d6842ab6f23e3da5221f6cb2812d818b0cec596153adfeeca3e1e7d4c’: Device or resource busy
```

7- Check file:

```
sudo ls -l /var/lib/docker/aufs/mnt/99b76f4d6842ab6f23e3da5221f6cb2812d818b0cec596153adfeeca3e1e7d4c

ls: cannot access /var/lib/docker/aufs/mnt/99b76f4d6842ab6f23e3da5221f6cb2812d818b0cec596153adfeeca3e1e7d4c: Stale file handle
```

8- Check /var/log/syslog:

Multiple lines like these:

```
Aug  6 18:28:14 ricardox kernel: [600440.626929] audit: type=1400 audit(1438903694.849:118): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="docker-default" pid=8114 comm="apparmor_parser"
Aug  6 18:28:14 ricardox kernel: [600440.636323] init: docker main process (8076) terminated with status 2
Aug  6 18:28:14 ricardox kernel: [600440.636335] init: docker main process ended, respawning
Aug  6 18:28:15 ricardox kernel: [600441.011280] init: docker main process (8144) terminated with status 2
Aug  6 18:28:15 ricardox kernel: [600441.011292] init: docker respawning too fast, stopped
Aug  6 18:31:54 ricardox kernel: [600660.125766] audit_printk_skb: 3 callbacks suppressed
```

------

$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

$ docker info
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 15.55 GiB
Name: ricardox
ID: WLPD:IT5D:KF2Q:7GPM:5ICH:4MOH:5CWF:XK5Y:EIR7:3GNF:C7VY:BHOK

**Comment by dnephin** [comment]
I've had similar problems before. The cause is not docker-compose at all, it's caused by moving or removing `/var/lib/docker` while  it is running.  You may need to restart the host to fix the issue. I  believe it has to do with cgroup mounts.

**Comment by ricardobranco777** [comment]
@dnephin I forgot to add "sudo service docker stop" before "mv".  Moving the directory is just used here to reproduce the problem in a clean environment.  The bug hit me without removing /var/lib/docker at all.

**Comment by dnephin** [comment]
I think removing those files is still an issue, even if the daemon is stopped, if it happens when the cgroup mounts are active. 

I'm pretty confident this isn't related to compose because in your example it never even hits the daemon. Compose doesn't operate on any of the files directly, it only communicates with the docker api.

**Comment by ricardobranco777** [comment]
@dnephin The daemon crashed and it doesn't restart unless I re-create /var/lib/docker.  Maybe the bug isn't at all related to Docker Compose, but no checking is done on the ports string.  The docker binary does this check and outputs:

docker: Invalid hostPort: 0.0.0.0.1234.

**Comment by ricardobranco777** [comment]
I updated the bug comment when trying to run "docker ps".

**Comment by aanand** [comment]
This is a Docker bug. It seems to have been fixed in https://github.com/docker/docker/pull/14682.

We could validate the port client-side in Compose to avoid making the daemon crash, but that'd saddle us with one more thing (i.e. port validation logic) to have to keep in sync with the official client.

**Comment by ricardobranco777** [comment]
So we should close this bug for now.
