### ISSUE TITLE
Proposal: Check if Container Exists in docker-compose.yml

### ISSUE THREAD

**Issue by coderlol** [docker/compose#1831]
Could we add a flag that compose checks to see if a container exists in docker-compose?  I have containers in multiple docker-compose and would like to check where a container is defined.

**Comment by dnephin** [comment]
Could you provide an example command and output that you would  expect? And maybe provide some more detail about the use case?

Every container created by compose (after version 1.3) has a label `com.docker.compose.project` which identifies the project it is part of. If I understand this feature request correctly, I think you would be able to use that label.

**Comment by coderlol** [comment]
I have, say, 10 docker-compose ymls: services-1.yml, services-2.yml, etc.

There is no convenient way (prior to starting any containers) to check whether a container A is defined in services-1.yml or services-2.yml.  

Well, if users wanted to start container A, my script currently has to go through all the yml and grep for "A" to find the right yml to pass to docker-compose.

**Comment by aanm** [comment]
@coderlol You can do this:
`$ cat services-* | docker-compose --file - up service_you_want`

**Comment by coderlol** [comment]
Interesting ... thx

**Comment by dnephin** [comment]
`docker-compose config` is now available in Compose 1.6 (RC release are out now). This provides a way to check what services are defined without starting any containers.

**Comment by jehon** [comment]
docker-compose config accept a parameter:

`docker-compose config <service>`

will throw an error in case the service is not defined
