### ISSUE TITLE
Problem with buffering when piping docker-compose logs

### ISSUE THREAD

**Issue by wader** [docker/compose#1838]
Hi, i'm trying to use `docker-compose logs` in a git hook script but got no log lines. After some fiddling i figured out that the output seems to be buffered. If i run python with `-u` or `PYTHONUNBUFFERED=1` it works fine.

How to reproduce:

    docker-compose logs | cat

This works:

    PYTHONUNBUFFERED=1 docker-compose logs | cat

Not really sure how it should behave. Maybe configure line buffering for stdout somehow when not a tty?

**Comment by abesto** [comment]
In my experience `PYTHONUNBUFFERED` doesn't help when the other end of the pipe is something like `tail` instead of `cat` :(

**Comment by carsonoid** [comment]
:thumbsup: Helped me get my python app to show in docker-compose 1.2.0

**Comment by dnephin** [comment]
We've added `flush()` after every line in compose 1.6.0 (RC1 was just released), so you shouldn't need to force disable buffering anymore.

**Comment by wader** [comment]
@dnephin Ok, thanks!

**Comment by stigok** [comment]
I have an image deriving from `python:3.6` which runs a simple script.

    environment:
      PYTHONUNBUFFERED: 1

But this happens with `docker run` too, so not specific to `docker-compose`

**Comment by glowka** [comment]
I had the same issues on `python:3.6` and `docker-compose 1.21`.
Setting `PYTHONUNBUFFERED=1` still helps.
