### ISSUE TITLE
docker-compose up with volumes_from without recreate

### ISSUE THREAD

**Issue by heycalmdown** [docker/compose#1841]
I have a `service A` which refers another `service B` to use `volumes_from`. If I use the service without recreate which as using --x-smart-recreate or default of 1.4.0-dev then I can't get changes from `service B`. So I need to use the option --force-recreate.

Is this behavior expected by design?

**Comment by aanand** [comment]
Not sure what you mean. If A depends on B via `volumes_from`, then changes to B will result in both A and B being recreated when you run `docker-compose up`. For example:

```
$ docker-compose --version
docker-compose version: 1.4.0rc3

$ cat docker-compose.yml
a:
  image: busybox
  command: top
  volumes_from: ["b"]
b:
  image: busybox
  command: top
  volumes: ["/data"]
  # environment:
  #   foo: 1

$ docker-compose up -d
Creating 1841_b_1...
Creating 1841_a_1...

$ docker-compose up -d
1841_b_1 is up-to-date
1841_a_1 is up-to-date

# ...uncomment the last two lines...

$ docker-compose up -d
Recreating 1841_b_1...
Recreating 1841_a_1...

$ docker-compose up -d
1841_b_1 is up-to-date
1841_a_1 is up-to-date
```

**Comment by dnephin** [comment]
No response, closing this issue.
