### ISSUE TITLE
Since 1.4, `docker-compose up container` logs all containers, not just those passed as argument

### ISSUE THREAD

**Issue by yanndinendal** [docker/compose#1856]
`docker-compose up lb wsgi` now also logs other containers, not just those explicitly passed in argument ("lb" and "wsgi" in this example).
So instead of having just the logs I'm interested in like before, I'm now flooded with logs of verbose containers like varnish.

**Comment by aanand** [comment]
Thanks for reporting. This was probably caused by #1645. I'm working on a fix.

**Comment by yanndinendal** [comment]
Thanks! Is a 1.4.1 release scheduled soon?

**Comment by aanand** [comment]
@yanndinendal Yes - it would be good to get #1851 fixed first though.
