### ISSUE TITLE
Option to not print color

### ISSUE THREAD

**Issue by alunduil** [docker/compose#1865]
I don't see any option in the usage to disable printing of color codes.  Can we have color disabled if not run from an interactive tty and if an option is passed?

**Comment by aanand** [comment]
$ docker-compose up --no-color

**Comment by invernizzie** [comment]
This should be properly documented. Neither the CLI usage nor the CLI reference page in the docs make reference to it. It was pretty hard to found by googling.

**Comment by mjrk** [comment]
When I do 

     docker-compose up --no-color

it prints `... done` with color. Furthermore, down etc. don't seem to accept this option. Do I miss something?

**Comment by mafrosis** [comment]
I have seen the same. "done" still prints in green.

**Comment by marcelloromani** [comment]
```
$ docker-compose --version
docker-compose version 1.11.2, build dfed245
```
```docoker-compose logs --no-color``` works.

Note: the ```--no-color``` options must be specified *after* ```logs```

**Comment by 27Bslash6** [comment]
The solution for prevent color code output in most docker-compose operations is `docker-compose --no-ansi`

See: https://docs.docker.com/compose/reference/overview/

Note this won't stop `docker-compose logs` from producing colour codes if the logs contain them, and from what I can tell `docker-compose logs --no-color` has no effect on the log content itself.

**Comment by pzelnip** [comment]
`--no-ansi` appears to be deprecated, from a `docker-compose --help`

```
  --no-ansi                   Do not print ANSI control characters (DEPRECATED)
```

Apparently `--ansi never` is the new suggested option?

**Comment by JC5** [comment]
When using docker compose commands colors will always be printed. There is no option to disable this and simply catting the logs through a filter may work, but other commands (start, stop, pull) will keep using colors no matter what you do.

- `--no-ansi` doesn't work
- `--no-color` doesn't work
- `--ansi never` doesn't work
- Environment variable`NO_COLOR` doesn't work

About half of the commands don't recognize the flags, the other half doesn't care. 

I suggest you reply or vote or whatever for this issue, which is what I could find, but the lack of activity makes me skeptical of an impending changes.

https://github.com/docker/compose/issues/8513

**Comment by pasuder** [comment]
Doing `docker-compose --no-ansi up -d` works fine

**Comment by JC5** [comment]
`docker-compose down --ansi never` does not.

**Comment by guss77** [comment]
> `docker-compose down --ansi never` does not.

`docker compose --ansi never <command>` works in Docker 24.0.7 in the since that it does not complain about the flag being illegal - but it also doesn't prevent Docker from outputting color and other screen manipulation ANSI commands. `--no-color` is also accepted - albeit with  deprecation warning - but also does not prevent output of color.
