### ISSUE TITLE
Feature Request. New Docker Log Driver "gelf"

### ISSUE THREAD

**Issue by snouhaud** [docker/compose#1869]
Docker 1.8 support GELF log driver. But actual docker-compose (1.4) don't support this option

**Comment by mnowster** [comment]
Intertwined with https://github.com/docker/compose/issues/1863 

If we can remove the hardcoded nature of supported drivers in docker-py then it'll speed up our ability to support new/more log drivers.

**Comment by sboily** [comment]
+1, there is the same problem for fluentd.

**Comment by shin-** [comment]
FIxed by docker/docker-py#724

**Comment by chiefy** [comment]
:+1: just ran into this trying to use fluentd w/ docker-compose.

**Comment by dnephin** [comment]
Opened https://github.com/docker/docker-py/issues/759

This issue is just blocked on releasing  new docker-py (and requiring that version in compose).

**Comment by miketonks** [comment]
+1 we could really use this for fluentd

docker-py 1.4.0 is released (thanks @shin- ), so now it just needs to be updated in requirements

**Comment by chiefy** [comment]
:clap: thanks! will this drop in compose 1.4.1?

**Comment by dnephin** [comment]
It's in the 1.5.0 release
