### ISSUE TITLE
Combined command to kill and remove containers

### ISSUE THREAD

**Issue by screwgoth** [docker/compose#1874]
Most of the times, during development of a docker-compose.yml file, I found myself killing services and then removing the stopped containers immediately. To do this, I had to execute 2 docker-compose commands , first to kill the services and then to remove the containers and associated volumes. 
I think It would be very convenient if one command did the complete clean-up , viz., killing AND removing the stopped containers. 
So, I think it would be a great convenience option to have --rm in the kill command.

**Comment by aanand** [comment]
Agree on the problem, but I'm not sure about the CLI design. The Docker client uses `rm -f` to mean "kill and remove"; ideally, `docker-compose rm -f` would also do that, rather than inventing another flag for `kill` that doesn't exist on its Docker client counterpart.

This is complicated, though, because Compose and the Docker client define `rm` and `-f` differently.

-   `docker rm CONTAINER`
    - removes CONTAINER if it's not running
    - if it is running, raises an error
-   `docker rm -f CONTAINER`
    - as above, but kills CONTAINER first (so it always gets removed)
- `docker-compose rm [SERVICE ...]`
    - removes all containers (optionally filtered by service) which are not running
    - prompts for confirmation before doing so
- `docker-compose rm -f [SERVICE ...]`
    - as above, but doesn't prompt for confirmation

If we change `docker-compose rm` to be more in line with `docker rm`, it'll break people's scripts in alarming ways that'll delete more containers than they were expecting. We'd have to go through a careful deprecation period.

**Comment by albers** [comment]
I fully agree with @screwgoth that there should be a way to `docker-compose rm` running containers as `docker rm -f` does.
In addition, I'd like to get rid of `docker-compose rm` asking for confirmation at all. This is not how Unix commands should behave. They should either succeed or fail.

**Comment by aanand** [comment]
@albers On my Mac, `rm` asks for confirmation when a file is read-only. I have to pass `-f` to stop it doing so.

Whether or not we drop confirmation entirely, we should still go through a period of deprecation before changing the behaviour. I propose a "hard deprecation" strategy as follows:

1. Add a `--kill` flag to `rm`, which means "remove all containers, killing them first if necessary".
2. Add a `--no-confirm` flag to `rm`, which means "don't ask for confirmation".
3. Remove the `--force` flag. If a user passes it in, exit immediately with an error explaining that the meaning of `--force` is going to change, and they should use `--no-confirm` instead to get the old behaviour.
4. Release a stable version of Compose.
5. Add the `--force` flag back, as an alias for `--kill --no-confirm`.
6. Release a stable version of Compose.

While this strategy will break backwards compatibility for people using `rm -f` today, it should ensure that - as long as people don't skip a Compose version - they won't accidentally start removing more containers than they expect to.

**Comment by albers** [comment]
@aanand 
> On my Mac, rm asks for confirmation when a file is read-only. I have to pass -f to stop it doing so.

That's right. I see your point.

**Comment by albers** [comment]
The proposed transition strategy is great.
I propose to extend step 4 to two releases, though. This would cover the case where a user skips one update cycle.

**Comment by screwgoth** [comment]
@aanand Absolutely agree to your argument. I have revered the code and sent pull request for point 1. above i.e., docker-compose rm --kill.
It works great with docker-compose rm --kill -f as well

**Comment by albers** [comment]
Cross-linking to #1875

**Comment by aanm** [comment]
Will `docker-compose -kf` also be valid? (`--kill` is to verbose)

**Comment by dnephin** [comment]
We've also received a couple requests for a `docker-compose down` command to be the opposite of `up` (#2277).  I think the feature that this issue is requesting would be the behaviour I'd expect from a `down` command (it's the opposite of up).  

Instead of adding new flags to `rm` and `kill`, maybe we can move this to `down` ?

**Comment by simonvanderveldt** [comment]
> The Docker client uses rm -f to mean "kill and remove"; ideally, docker-compose rm -f would also do that, rather than inventing another flag for kill that doesn't exist on its Docker client counterpart.

Yes please! I'm noticing around me that all those different commands with different flags behaving differently is really getting in the way of adoption of Docker and the surrounding ecosystem.
Please don't add a new command but simply follow docker's behaviour.

@aanand The proposed migration path though very safe seems to be a bit complex. I.e. introducing new arguments and removing and re-adding an existing argument.
Wouldn't it be better to simply issue an error/alert during 1 or 2 releases about the behaviour changing?

**Comment by aanand** [comment]
@simonvanderveldt I'm inclined to err on the side of safety, given that the `rm -f` command is going to become strictly *more destructive* than before.

If we're changing the meaning of `rm -f`, I want to be as sure as possible that people aren't already using it expecting it to do something else. Showing a warning won't cut it - we must assume that in many cases (e.g. scripts, automated CI etc) the output won't ever be seen unless something actually breaks.

@dnephin Yes, this might well overlap with the `down` command, though there's still a case to be made for amending `kill` and `rm` purely for the sake of consistency.

**Comment by dnephin** [comment]
#2646 should resolve this issue without overloading the meaning of `rm`, adding new flags, or worrying about the backwards compatibility of `rm`.
