### ISSUE TITLE
dockerfile location context issues

### ISSUE THREAD

**Issue by terion-name** [docker/compose#1890]
Ok, trying to get a workaround of other issue (#1883) I've faced another.
New file structure:
```
project
|-environments
|-|-production-compose.yml
|-production.docker
``` 

production-compose.yml:
```
web:
  build: ../../
  dockerfile: production.docker
```
results in:
```
Cannot locate specified Dockerfile: production.docker
```

other variant:
```
web:
  build: ../../
  dockerfile: ../../production.docker
```
results in:
```
The Dockerfile (../../production.docker) must be within the build context
```

So, it looks for dockerfile relative to compose.yml, but it ignores specified build context. I understand that it will work if place all in root, but such polution of project root is not good. And it kills all advantages of -f option

**Comment by dnephin** [comment]
The `dockerfile` path is relative to the build context path. That's not clearly documented in http://docs.docker.com/compose/yml/#dockerfile, and I guess it probably should be.

To get your example working, use:

```yaml

web:
  build: ../
  dockerfile: production.docker

```

**Comment by terion-name** [comment]
Ah, sorry, indeed this works, didn't update the path in yml, sorry

**Comment by sampsyo** [comment]
FWIW, this just burned me—it's still not documented.

**Comment by DvdGiessen** [comment]
Apart from this behaviour not being documented, why is it like this? It just ran into it as well, and it seems to be a limitation of Docker Compose, not Docker itself:
```
$ cat docker-compose.yml
version: "3"
services:
  miner:
    build:
      context: ext/submodule
      dockerfile: docker/submodule.Dockerfile
$ docker-compose build
ERROR: Cannot locate specified Dockerfile: docker/submodule.Dockerfile
$ docker build -f docker/submodule.Dockerfile ext/submodule
Sending build context to Docker daemon  126.5kB
Step 1/3 : FROM node:latest
latest: Pulling from library/node
...
```
In my case, I have a submodule in my Git project which doesn't have a Dockerfile in it, so I keep one in my own repository, outside the submodule (which is outside my control). Docker is just fine with being supplied a Dockerfile to build just this submodule, however Docker Compose requires me to put the Dockerfile inside the build context.

I know I can work around it by expanding the build context and modifying all COPY statements in my Dockerfile, but that also means I have to pull in a (in my case) huge and largely unused build context which is rather inefficient, while it doesn't seem to be required for any technical reason. So I was wondering, why is Docker Compose strict about the Dockerfile being in the build context?
