### ISSUE TITLE
Force Dockerfile service to pull latest image

### ISSUE THREAD

**Issue by dmp1ce** [docker/compose#1891]
How do I force `docker-compose` to pull the latest image for Dockerfile services? The only way I could figure out how to get the latest image was with `docker pull <image>`. `docker-compose pull` only pulls images for services that reference an image, not a Dockerfile. `docker-compose build --no-cache` doesn't pull the latest image for me either.

**Comment by dnephin** [comment]
See #726 and #731, we need to add that support

**Comment by dnephin** [comment]
This was added in #2041. It will be in 1.5.0 now available as an rc (https://github.com/docker/compose/releases/tag/1.5.0rc1)
