### ISSUE TITLE
Add self upgrade feature

### ISSUE THREAD

**Issue by nazar-pc** [docker/compose#1893]
Would be nice to have two more commands:
```
docker-compose self-upgrade
docker-compose self-remove
```

For instance, PHP packages manager Composer has `composer self-upgrade` and it is way more convenient that going to documentation and copy-pasting installation command or doing something else manually.

**Comment by prologic** [comment]
This *would* largely depend on how you install ``docker-compose`` in the first place. I normally install this with [pip](https://pypi.python.org/pypi/pip) via ``pip install -U docker-compose``; but most others probably install the "packaged" bundle.

**Comment by nazar-pc** [comment]
What do you mean under "packaged bundle"?
I'd prefer install regular package from repository like Docker itself, but Compose, Swarm and Machine are not in repository yet:(

**Comment by prologic** [comment]
``docker-compose`` is shipped and released as a binary executable with all dependencies shipped normally; whilst some of us (*maybe more Python devs/users*) use a pip installed version.

**Comment by prologic** [comment]
I'm pretty sure we use [pyinstaller](https://github.com/pyinstaller/pyinstaller) to package/bundle up ``docker-compose`` in a portable way for our users :)

**Comment by nazar-pc** [comment]
I meant regular deb/rmp repository to get everything upgraded together.

**Comment by prologic** [comment]
This would be all but useless for anyone else that isn't on Debian/Ubuntu. What about RHEL/CentOS? What about CRUX? What about OS X? What about manually installed, pip installed? I think supporting ``self-upgrade`` command is very much "platform/OS" specific IHMO. -- What about Windows?

**Comment by nazar-pc** [comment]
I was talking about both deb and rpm, others can use it as they use it now. Moreover, repositories already exists and used to install Docker itself.

I have it installed as specified in documentation, namely:
> curl -L https://github.com/docker/compose/releases/download/VERSION_NUM/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

Now uninstallation:
> rm /usr/local/bin/docker-compose

Just look into documentation: https://docs.docker.com/compose/install/

This is just single static binary, I do not see any single reason why it might be difficult for Compose to override itself with new binary or just remove itself.
This will likely work on any OS. (BTW, Docker is not working on Windows yet).

**Comment by prologic** [comment]
I'm just saying there are platform/OS things to consider; and FYI Docker is available (*Docker Engine*) on Windows as a preview :) See Sven's blog posts about  him testing it out! Docker Client itself on Windows has been available since bot2docker and friends :)

**Comment by nazar-pc** [comment]
I do not have Windows, can't try it, LOL)
Well, this is all offtopic, waiting for answer from developers...

**Comment by aanand** [comment]
I doubt we would add a self-upgrade feature to Compose in isolation. Most people are going to install via the Toolbox, and it makes sense to upgrade components together, since newer versions of the tools often drop compatibility for older versions of the other tools.

I can see a future where the Toolbox can upgrade all components at once, but that's not (directly) a Compose concern.

**Comment by prologic** [comment]
As long as Compose can still be shipped and installed either as a binary bundle or via pip I'm happy!

**Comment by dnephin** [comment]
Closing this. It will either be handled by toolbox, or with #2235 (allowing the distro to upgrade as it would normally).
