### ISSUE TITLE
The version 1.4.0 aren't working with docker 1.6.2

### ISSUE THREAD

**Issue by robsonpeixoto** [docker/compose#1895]
```
$ ../docker-compose build
mail uses an image, skipping
mysql uses an image, skipping
Building cusca...
client and server don't have same version (client : 1.19, server: 1.18)

$ sudo ../docker-compose version
docker-compose version: 1.4.0
docker-py version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

$ docker --version
Docker version 1.6.2, build 7c8fca2
```

**Comment by dnephin** [comment]
You can use the environment variable `COMPOSE_API_VERSION=auto` to have compose auto-detect the right server version, or `COMPOSE_API_VERSION=1.18` to set it to a specific api version.

I can't find any reference to it in the docs, we should add that.

**Comment by aanand** [comment]
Agreed.

@robsonpeixoto Please note that Compose 1.4.0 only officially works with Docker 1.7.1 and up, as stated in the [release notes](https://github.com/docker/compose/releases/tag/1.4.0).

**Comment by robsonpeixoto** [comment]
Sorry @aanand. Thanks for the attention.

**Comment by dnephin** [comment]
This was added to the docs (https://github.com/docker/compose/blob/master/docs/reference/overview.md#compose_api_version)

**Comment by tsoenen** [comment]
@dnephin : Where specifically can I set an environment variable?

**Comment by dnephin** [comment]
You can set an environment variable from the shell you use to run `docker-compose`.
