### ISSUE TITLE
Document that fig rm removes volumes

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#190]
It's not immediately clear that you will lose all of your data when running `fig rm`. This should be really clear.

**Comment by ChrisChinchilla** [comment]
#dibs

**Comment by albers** [comment]
Does compose really remove volumes? Docker does not, see https://github.com/docker/docker/commit/00f2fd1dd5dee53919cda7ed9f5c70ba8558edb5

**Comment by bfirsh** [comment]
Hm. Good point. I guess the data is _difficult_ to recover because you have to figure out what directory it was in. :)

**Comment by thaJeztah** [comment]
`docker rm -v` will also remove the volume, I think `docker-compose rm -v` does the same?

Note that there is discussion in Docker to make `-v` a requirement; ie, Docker will refuse to delete a container with volumes if `rm` is called without `-v`
