### ISSUE TITLE
is there some ways to make services in external-links optional?

### ISSUE THREAD

**Issue by hanks** [docker/compose#1902]
I set some services in the external-links, but they are not always need to be launched.  Now I need to run they firstly, then I can start my needed service.   
I just want to skip them when I run my needed service, but if I run them later, it will still work.

**Comment by bohai** [comment]
I feel it's impossible for current compose.
Because the link is implemented by adding info to the /etc/hosts.
If the dependency service is not launched, the info can't be got and  added.

**Comment by hanks** [comment]
thx
