### ISSUE TITLE
Run jenkins builds in parallel

### ISSUE THREAD

**Issue by dnephin** [docker/compose#1919]
Now that we run the test suite on python3, we have to run it 2 x (num of docker versions we support).

It would be nice to run all (or some) of these permutations in parallel (possibly as separate jenkins jobs?) so that we can get feedback about PRs much faster.

**Comment by aanand** [comment]
Yep. The same also applies to Docker versions.

@jfrazelle - what would be involved in getting this working? Does docker/docker already do this?

**Comment by jfrazelle** [comment]
Ya I can turn it on, weird it's not






On Wed, Aug 26, 2015 at 3:22 AM -0700, "Aanand Prasad" <notifications@github.com> wrote:












Yep. The same also applies to Docker versions.



@jfrazelle - what would be involved in getting this working? Does docker/docker already do this?

**Comment by jfrazelle** [comment]
Hmm it is on, can you tell me what you saw? Maybe there was a queue backed up at the time?






On Wed, Aug 26, 2015 at 3:22 AM -0700, "Aanand Prasad" <notifications@github.com> wrote:












Yep. The same also applies to Docker versions.



@jfrazelle - what would be involved in getting this working? Does docker/docker already do this?

**Comment by jfrazelle** [comment]
If it's a matter of running your bash script at the same time can you do it in the container ;) w parallel

**Comment by dnephin** [comment]
@jfrazelle I was thinking something like (what I assume) https://jenkins.dockerproject.org/job/Docker%20Master/ does, where one jenkins job triggers other jobs for each version we want to test against.

I think doing the runs in parallel in the same job would make the test output impossible to read.

**Comment by jfrazelle** [comment]
ya that would take some changing as to how we automate prs we can work on
it when i get some free time :)
