### ISSUE TITLE
pause and unpause commands missing from command help

### ISSUE THREAD

**Issue by dnephin** [docker/compose#1921]
In #1766 we missed adding `pause` and `unpause` to the `compose/cli/main.py:TopLevelCommand` docstring, so it's missing from completion (and help text).

cc @funkyfuture since you worked on the original issue

**Comment by funkyfuture** [comment]
shit yeah, that's because I used it in a tool with an own TLC.

will fix, or someone else is faster.

**Comment by dnephin** [comment]
Fixed by #1944
