### ISSUE TITLE
Error message when image and container has same name is confusing

### ISSUE THREAD

**Issue by jelmstrom** [docker/compose#1925]
I accidentally gave my container the exact same name as the image used, and the error message that resulted was quite confusing..

```[8] System error: not a directory```
The config looks like this

```
godata:
  image: godata
  privileged: true

```

If this is not a valid option it would be helpful if it is caught while parsing the yml file rather than at run-time

Changing either the image pr container name solves the problem...

**Comment by aanand** [comment]
You're definitely allowed to use the same image and service name - we do exactly that with `redis` in the [quick start guide](http://docs.docker.com/compose/#define-services), for example.

**Comment by jelmstrom** [comment]
That is very odd - that particular compose-file, on that particular node is the only one that had that behaviour.  I can't reproduce it anymore though, extremely odd that changing the name of the container altered the behaviour. File system or disk issue perhaps.

Dropping this, thanks..
