### ISSUE TITLE
Accept a "default location" and compose.yml

### ISSUE THREAD

**Issue by envygeeks** [docker/compose#1943]
- I am proposing that something like /etc/<<compose_file>>.yml be searched for (if no -f is provided and no relative compose file is found) so that systems can drop a default compose file and docker-compose quickly.
- I am proposing that on-top of the current files being accepted that `compose.yml` also be added to that list, we have a preference for that short name because it doesn't overtake our apps root folders with a long file (docker-compose.yml) is overly noticeable to the point where it's a focus.

**Comment by thaJeztah** [comment]
I'm -1 on searching a default location (e.g. `/etc/`); the yaml file is usually tightly coupled to the (source) files of a project. I think it's better to error-out if no yaml file is found (or specified), than to automatically use a standard yaml file. Running `docker-compose up` in a *random* location, should not automatically attempt to create containers from that location (possibly sending sensitive data to the docker daemon)

I'm not really opposed to having `compose.yml` as an alternative name, but it's only a cosmetic change (so low priority imo)

Just my 0.02c, I'm not a maintainer in this repo :+1:

**Comment by envygeeks** [comment]
Yeah the `/etc` thing was a wild shot in the dark but not really important since we have `docker-wrapper

**Comment by envygeeks** [comment]
Awesome. I like it when tickets are closed without reason.

**Comment by shin-** [comment]
Sorry - the issue has been open for two and a half years without any feedback from other users, which indicates this is a niche feature at best ; on top of this, those changes would be breaking changes. In other words, it's not going to happen.

**Comment by envygeeks** [comment]
That logic is faulty at best.  When you've 600+ open tickets, and people generally only look in a ticket system when they have a problem, and there is no method to see feature requests to vote on them, of course a ticket will sit for 2 and a half years without people noticing it.

On top of that I hardly think accepting "compose.yml" would break anything, considering it didn't recommend removing "docker-compose.yml" so onto of not saying "we don't want to do it, so it's never gonna happen" you're inserting falsehoods.

**Comment by shin-** [comment]
k

**Comment by mmuehlbauer** [comment]
This is still broken.
