### ISSUE TITLE
TTY support for up command

### ISSUE THREAD

**Issue by edwinlunando** [docker/compose#1949]
I need TTY support for up command make make byebug working for my Rails application.

**Comment by dnephin** [comment]
See [tty](http://docs.docker.com/compose/yml/#working-dir-entrypoint-user-hostname-domainname-mac-address-mem-limit-memswap-limit-privileged-restart-stdin-open-tty-cpu-shares-cpuset-read-only-volume-driver)

Or maybe what you want is http://docs.docker.com/compose/reference/run/
