### ISSUE TITLE
"Featured Examples" doc

### ISSUE THREAD

**Issue by dnephin** [docker/compose#1951]
(from https://github.com/docker/compose/pull/1627#issuecomment-134685571)
Related to #1936

We can't maintain an example for every setup, but we can link to repos and blog posts that contain examples of compose uses.  Let's add a page to the docs where we can include these links.

**Comment by dnephin** [comment]
https://github.com/rtfd/readthedocs.org/pull/1133 is one example I worked on
https://github.com/ImaginationForPeople/assembl/pull/4 is another

They both might need some updating

**Comment by wernight** [comment]
I have two main patterns that are sadly mutually exclusive:

1. Use `COPY` or `ADD` in a `Dockerfile` to build an image that can be run with your source code, which works really well for production deployment, but during development it's extremely slow.
2. Use volumes in `docker-compose.yml` on top of a built image, which allows to test source file changes instantly but doesn't work so well for deployment.

Both method can be used for source code (which should be considered static) and for *data-only containers* like databases data. **Backup** of data-only containers is slightly harder that just local files, and should be done more frequently IMO, but they have also less risk of working differently once restored (for example the user/group for access level and file systems are pretty much guaranteed to be the same when using data-only containers).

So my solution so far, is to use method (1) and uncomment some lines for (2) during development.

**Comment by dnephin** [comment]
From #56: https://github.com/kaiquewdev/fig-nodejs, https://github.com/kevinsimper/node-js-fig-docker-example

**Comment by dnephin** [comment]
#669 has examples for node.js and express https://github.com/b00giZm/fig-nodejs-examples

**Comment by ijc** [comment]
Issue grooming:

https://docs.docker.com/compose/gettingstarted/ has links (at the end) to Django, Wordpress & rails quickstart examples and in general I think the docs/examples story around `docker-compose` is very different to how it was in 2015. I think we can close this one.
