### ISSUE TITLE
[DOC] Outdated release notes for 1.2.0 on https://docs.docker.com/compose/

### ISSUE THREAD

**Issue by charleswhchan** [docker/compose#1958]
I was going through the website and noticed the release notes section is outdated:
https://docs.docker.com/compose/ - v1.2.0

The latest release:
https://github.com/docker/compose/releases - v1.4.0

Should we remove the information from the website and link to the "releases" page on GitHub directly?

**Comment by thaJeztah** [comment]
Sounds good to me. (or, alternatively https://github.com/docker/compose/blob/master/CHANGELOG.md)

**Comment by charleswhchan** [comment]
Thanks for the suggestion @thaJeztah, I will go with CHANGLOG.

#dibs
