### ISSUE TITLE
up should not add 3 dots after container name. Makes slow to copy/paste

### ISSUE THREAD

**Issue by d2xdt2** [docker/compose#1975]
There are added 3 dots after the container name when doing `up`

```
# docker-compose up
Starting dockercomposetest_helloworld_1...
Attaching to dockercomposetest_helloworld_1
```
which makes copy/pasing the name on Linux slow, as you can't just double  click on the name without also getting the 3 dots. So one would have to drag the mouse cursor over the name and make sure not to get any of the dots included.

**Proposal**

Don't add the 3 dots.

**Comment by aanand** [comment]
+1

**Comment by thaJeztah** [comment]
Oh! So true, run into this all the time :+1:
