### ISSUE TITLE
`up` could start some services in parallel

### ISSUE THREAD

**Issue by dnephin** [docker/compose#1984]
We can't fully paralleled it, but we can do it in stages as dependencies are fulfilled.

**Comment by aanand** [comment]
Yeah - @bfirsh mentioned this in https://github.com/docker/compose/issues/1652. I have no idea how complicated it is to go from a DAG to a sequence of sets of parallelisable actions, but I'm sure there's an algorithm for it.

**Comment by Multiply** [comment]
Any traction on this?

**Comment by scomma** [comment]
Hi, we have a production cluster where we manage over 50 containers/host with docker-compose. The addition of this would speed up deployment greatly.

**Comment by IlyaSkriblovsky** [comment]
Starting phase of `up` made parallel in #2679 (and also `start` and `stop`)

**Comment by Multiply** [comment]
Oh yes @IlyaSkriblovsky :D
