### ISSUE TITLE
Set swarm port filter to support scaling with public ports

### ISSUE THREAD

**Issue by dnephin** [docker/compose#1986]
http://docs.docker.com/swarm/scheduler/filter/#port-filter

Maybe we should be setting this filter on containers that have external ports, so that they scale properly on swarm?

**Comment by aanand** [comment]
The Swarm docs are a little misleading there - the "port filter" is not a manual operation, but is automatically applied when you map a host port.

**Comment by dnephin** [comment]
Ah, in that case, I guess there's nothing for us to do
