### ISSUE TITLE
"service" key in extending should be optional

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1989]
This is unnecessarily verbose:

```
base:
  ...
web:
  extends:
    service: base
  ...
```

You should be able to just do this:

```
base:
  ...
web:
  extends: base
  ...
```

**Comment by mrfuxi** [comment]
Wouldn't this allow to extend service only from current file? Is that the intention?

**Comment by aanand** [comment]
@mrfuxi Both syntaxes would work - the new one would just be a shorthand.

**Comment by mrfuxi** [comment]
@aanand how file would be specified?

I tried that:
```
web: 
  extends: base
    file: common.yml
```

But it's invalid yaml

**Comment by aanand** [comment]
@mrfuxi You would use either a string *or* a mapping.

String:

```yaml
web:
  extends: base
```

Mapping:

```yaml
web:
  extends:
    file: file.yml
    service: base
```
