### ISSUE TITLE
"net" parameter problem

### ISSUE THREAD

**Issue by Glueon** [docker/compose#1991]
There is a selenium container and a django one where I run functional tests connecting to selenium.
I need a bidirectional link so selenium should be reachable from django container and django's liveserver from selenium. 

As far as I understand one way to solve this is to use `net:container_name`, so all exposed ports from both containers will be accessible on their loopback devices. Reduced `docker-compose.yml`:

    web:
        build: .
        ....
    selenium:
        image: selenium/standalone-firefox
        net: "container:web"

And this does not work. `selenium` container exposes 4444 port but it's not reachable from a `web`. If I use `--link selenium:selenium` for a `web` container then 4444 port is reachable, but selenium can't reach django.
I could only make it work with `net: ...` by replacing `web` parameter with it's auto-generated name, like:

    net: "container:folder_web_run_1"

Then with this:

    docker-compose run --rm web py.test functional_tests

Everything worked fine.

So as far as I understand docker-compose automatically figures out the real container's name when used in `links: one_name:another_name` and other parameters but it does not work with `net` parameter?

**Comment by dnephin** [comment]
What's the output of `docker inspect` for the selenium container when you use `net: 'container:web'`? It should be the id of the web container

**Comment by Glueon** [comment]
Should I run it for a currently running selenium container? I noticed that docker-compose outputs an error:

    docker-compose up --no-deps selenium
    Warning: Service web_test is trying to use reuse the network stack of another service that is not running.
    Creating code_selenium_1...
    Attaching to code_selenium_1
    ....

`docker inspect code_selenium_1` outputs a lot of data. Which should I pay attention to?

**Comment by Glueon** [comment]
So I realized this does not work only if start container `web` using `docker run`. And maybe that is an expected behavior. So I moved `net` to the web container.
 
web:
    build: .
    net: "container:selenium"
    ....
selenium:
    image: selenium/standalone-firefox

**Comment by dnephin** [comment]
Yup, that sounds right. `run` containers are not considered as part of the composition, so they wont be used for `net`.

**Comment by ruchitgandhi** [comment]
@Glueon Could you please post your latest docker-compose.yml after this fix? I am facing exactly same issue where my angular container is able to find selenium at 4444 but selenium container is not able to communicate with angular.
