### ISSUE TITLE
Installing docker-compose through pip will sometimes(?) not upgrade websocket to required version

### ISSUE THREAD

**Issue by JonasT** [docker/compose#1996]
Installing docker-compose through pip will sometimes(?) not upgrade websocket to required version. This means:

1. User uses ```pip install docker-compose```.

2. User tries to use it. This error appears:
```
[root@localhost Server]# docker-compose
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.4.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 10, in <module>
    from docker.errors import APIError
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 20, in <module>
    from .client import Client, AutoVersionClient # flake8: noqa
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 23, in <module>
    from . import clientbase
  File "/usr/lib/python2.7/site-packages/docker/clientbase.py", line 7, in <module>
    import websocket
  File "/usr/lib/python2.7/site-packages/websocket/__init__.py", line 22, in <module>
    from ._core import *
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 41, in <module>
    from ._url import *
  File "/usr/lib/python2.7/site-packages/websocket/_url.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ImportError: No module named urllib.parse
[root@localhost Server]#
```

3 . User needs to google around and dig for this error to find out that this is required to make things work: ```sudo pip install -U websocket```

This is not exactly how the install experience is supposed to be. Why does this not work properly per default? Also check out https://github.com/docker/compose/issues/1288 to see that it's a quite a large amount of people affected.

Please figure out why pip isn't properly installing the required websocket dependency, and make it work per default for all users.

**Comment by dnephin** [comment]
The problem is described here: https://github.com/docker/compose/issues/1288#issuecomment-106936459

It's not a pip bug, and it's not a compose bug, it's an issue with requests and the libs it has vendored. We recently upgraded to requests 2.7.0 in master. What version is being installed for you?

**Comment by JonasT** [comment]
The bug can be easily reproduced like this:

**Step 1:** Make a new empty folder and put this in a ```Dockerfile```:
```
FROM fedora:22

RUN dnf update -y
RUN dnf install -y python python-pip python-requests
RUN pip install docker-compose

CMD docker-compose
```
**Step 2:** Build the container
**Step 3:** Run the container

Have fun with the full backtrace!

If that's not a bug, then I don't know what it is. If it's a requests bug, maybe there's a workaround?

**Comment by dnephin** [comment]
I was able to get it working by removing `python-requests` from the example above. 

If you're having issues with conflicting python versions, it's always a good idea to use a [virtualenv](https://virtualenv.pypa.io/en/latest/). ` dnf install python-virtualenv `

**Comment by JonasT** [comment]
But isn't there a way to make this work out of the box or at least provide a more helpful error info here? I have introduced friends to docker, and about half(!) of them ran into this problem.

Sure there's virtualenv and all, but who uses that to install a seemingly simple system administration tool that's meant to be used system-wide.

**Comment by dnephin** [comment]
You can use a virtualenv to install stuff system wide.  There's actually a great debian packaging helper that does just that (https://github.com/spotify/dh-virtualenv). 

The "recommended" way to install compose is by downloading the binary (http://docs.docker.com/compose/install/). `pip` is more involved because of issues like this (you need to understand the nuances of python packaging).

**Comment by JonasT** [comment]
Alright, but if you don't expect the pip package to work, why provide it at all?

If you want to imply that it's normal for pip packages to not work properly if installed system-wide instead of using a virtualenv, I would concur. I use pip a lot and this sort of thing is more on the rare side.

Of course you can use a virtualenv, but again who does that by default for all things they install? I understand downloading is a nice way to work around this and what a normal user should be doing, but still the pip package is resulting in a bad user experience where I'm really wondering if there isn't a way to make this work better?? (for the average user who comes up with the idea of using pip instead of wget'ing some file from the web that won't update itself properly)

Judging by the other bug reports popping up frequently about this, I'm not the only one who is stumped by this problem.

**Comment by JonasT** [comment]
I made a more detailed feature request here suggesting some ways to improve the current situation: #2101

**Comment by dnephin** [comment]
We've added instructions to the docs about using a virtualenv.
