### ISSUE TITLE
Add the ability to create multi-image(container) infrastructures

### ISSUE THREAD

**Issue by opreaadrian** [docker/compose#2006]
Hi,

I often found myself in a situation where I would need, a test environment, for example, and that test environment is made up of [selenium/hub](https://hub.docker.com/r/selenium/hub/) and [selenium/standalone-chrome](https://hub.docker.com/r/selenium/standalone-chrome/). 
I think it would be helpful to have some sort of functionality, custom YAML filenames, besides `docker-compose.yml`, or sections within `docker-compose.yml` denoting that we're launching a multi-container structure.
Currently, in order to "replicate" this use-case, I use `docker-machine`, I create a separate VM, and instantiate the images I need, but I think that this would be helpful if it would be baked into `compose`.

Thanks,
Adrian.

**Comment by dnephin** [comment]
I don't really understand this request.  You can use different filenames with `-f`.

Can you tell me more about the problem?

**Comment by opreaadrian** [comment]
Oh, crap! It's another RTFM case! Nevermind, I will close this issue as the functionality I need was right in front of me. Sorry for this.
