### ISSUE TITLE
Expose config-hash checking

### ISSUE THREAD

**Issue by kjr** [docker/compose#2013]
I'm writing a tool that uses docker-compose and it needs to tell the user whether they need to 'up' a service. To do this, I have reproduced the config-hash so I can check if the config has been changed, but the method of doing this changes between docker-compose versions, so it would be handy to be able to ask docker-compose whether it thinks the config has changed directly, without performing any other actions.

**Comment by dnephin** [comment]
Exposing this as a command would probably be a good idea. It could be part of #1953

`docker-compose config --hash <service>`

**Comment by cwolfinger** [comment]
This would be a great addition since it would allow the use of more sophisticated rolling update / rolling restart algorithms then what we have right now with compose up.

**Comment by schmunk42** [comment]
Ping...
