### ISSUE TITLE
Private registry password issue

### ISSUE THREAD

**Issue by stevenewey** [docker/compose#2015]
I had a private registry user with a password containing the characters > and }

On the registry side I could see authentication failing when using docker-compose pull, but not when using docker pull.

Removing these characters from the password and trying again, and docker-compose pull works. So I suspect there's an issue with reading the password from the docker config.

**Comment by aanand** [comment]
ping @shin- - could this be a docker-py bug?

**Comment by thaJeztah** [comment]
ping @shin- :innocent:

**Comment by shin-** [comment]
I'm going to assume this we fixed that, otherwise we would have seen a lot more reports of this, but please feel free to comment if that isn't the case.
