### ISSUE TITLE
bump to 1.4.1

### ISSUE THREAD

**Issue by gregory** [docker/compose#2022]
There has been a [lots of commits to master since the 1.4.1](https://github.com/docker/compose/compare/1.4.0...master) 
Can we bump to 1.4.1 or 1.4.1-rc1 ?

**Comment by dnephin** [comment]
There's a good chance this will happen soon

**Comment by linlinlinlin** [comment]
I am also suggest bump docker-py version to 1.4.0.

**Comment by dnephin** [comment]
We've done a couple bug fix releases (1.4.1, 1.4.2) but there's still lots of stuff in master.  There should be a new RC release in the next couple of weeks, and we're also looking at doing #1070
