### ISSUE TITLE
create a logo for compose

### ISSUE THREAD

**Issue by TomasTomecek** [docker/compose#2024]
Fig used to have a such a nice logo! Why doesn't compose have one?

![fig](http://www.fig.sh/img/logo.png)

**Comment by dnephin** [comment]
We have a logo! 
<img width="329" alt="_octopus_720" src="https://cloud.githubusercontent.com/assets/442180/9820748/dd73c6ca-5883-11e5-8705-f5f8cb5d515e.png">

**Comment by TomasTomecek** [comment]
So why is it not displayed anywhere? :/

Put it to readme and docs please, b/c it looks really cool!

**Comment by thaJeztah** [comment]
@TomasTomecek good idea! Are you interested in contributing, and opening a pull-request?

**Comment by TomasTomecek** [comment]
@thaJeztah there you go
