### ISSUE TITLE
Meaningful error message if string value instead of boolean is used

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#2025]
If `docker-compose.yml` specifies the value as `privileged: "true"` instead of `privileged: true`, then `docker-compose up -d` gives the following error:

```
json: cannot unmarshal string into Go value of type bool
```

A more meaningful error should be provided.

**Comment by dnephin** [comment]
This is fixed in master. The error will be:
`Service 'web' configuration key 'privileged' contains an invalid type, it should be a boolean`.

This fix will be in the 1.5.0 release
