### ISSUE TITLE
Generate command help from real output

### ISSUE THREAD

**Issue by dnephin** [docker/compose#2043]
Right now `docs/reference/docker-compose.md` is a copy of `docker-compose --help` and all  the `docs/reference/*.md` files that have the same issue.

We should be able to generate this output instead of copy-paste it into the docs. Trying to keep them sycned will result in the docs always being out of date (they are currently), and a lot of unnecessary work to attempt to keep them up-to-date.

I don't know much about https://gohugo.io/ but it's definitely something it should support. An example of this feature for `sphinx` can be found here: https://pythonhosted.org/sphinxcontrib-programoutput/

**Comment by albers** [comment]
Docker used to have a python tool `docs-update.py` for that purpose.
It was [removed](https://github.com/docker/docker/commit/ab545aed4c90134b33c9aab600ab2d18b6eafd73#diff-7285f62db3ecc41f03b11282df5eaf18), though. Don't know the current solution.

See also https://github.com/docker/docker/issues/9478.

**Comment by dnephin** [comment]
It looks like either https://github.com/spf13/hugo/issues/796 or https://github.com/spf13/hugo/issues/247 would make this possible.

Putting the content into an environment variable might also work until those are implemented.

I think another blocker is that the docs build only has access to the `docs/` subdirectory, which means that it will need to change in some way.
