### ISSUE TITLE
1.4.1 Mac OS X Attaching Issue

### ISSUE THREAD

**Issue by carsongee** [docker/compose#2085]
Between 1.4.0 and 1.4.1 the stdout/stderr streaming appears to have been broken for Mac.  Tried with docker-machine latest release, I'm seeing:
```shell
Starting project_redis_1...
Starting project_mongo_1...
Starting project_api_1...
Attaching to 
```
Downgrading to 1.4.0 resolved the issue.

**Comment by dnephin** [comment]
We just released 1.4.2 today which fixes the issue!

https://github.com/docker/compose/releases/tag/1.4.2

**Comment by carsongee** [comment]
Great, thanks, the new version is working well.  @facultymatt did notice that it looks like the [CHANGLOG](https://github.com/docker/compose/blob/master/CHANGELOG.md) is missing an entry for 1.4.2 btw.

**Comment by dnephin** [comment]
Yup, I haven't merged it into master yet. It's still in the release branch https://github.com/docker/compose/blob/release/CHANGES.md
