### ISSUE TITLE
Pass local environment variable to docker

### ISSUE THREAD

**Issue by 208rishabh** [docker/compose#2091]
Hi,

This might be a general docker problem but since my use-case is docker-compose, I am posting it here:

I need to pass my machine's hostname as an environment variable to a container which would be created through docker-compose. That particular container uses a Dockerfile and uses "cmd" flag in it. The command in "cmd" uses this environment variable. Can someone please help?

**Comment by dnephin** [comment]
`environment` or `env_file` should both work http://docs.docker.com/compose/yml/#environment

You can leave the value blank, and it will take the value from the current environment:

```yaml

 environment:
     HOST_HOSTNAME:
```

`HOST_HOSTNAME=$(hostname)  docker-compose up`

**Comment by 208rishabh** [comment]
Thanks a lot, it works perfectly fine :)

Small edit:

I had to make a small change, though:

  environment:
    -HOST_HOSTNAME

HOST_HOSTNAME=$HOSTNAME docker-compose up
