### ISSUE TITLE
Specify both image name and build path

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#2092]
It should be possible to specify the name of an image, and the path it can be built from. Like so:

```
web:
  image: hyperglobalmegacorp/web
  build: .
```

This lets you do various things:

1. Bootstrap an environment by pulling pre-built master images from the Hub so you don't have to build them locally when setting up an initial environment (`docker-compose pull; docker-compose up`)
2. Lets you easily push images that you have built
3. Lets you customise the name of the built image
4. Makes it easier to use the same Compose file in development and production (production can pull images in advance or ignore `build`)

Related: #213

**Comment by aanand** [comment]
Use cases 2, 3, and 4 are compelling. The first one makes me nervous - means that at any given time, `web`'s image could have come from either a registry or a local build. Still, it might not be an issue in practice.

@dnephin implemented a `tag` key in https://github.com/docker/compose/pull/457, which was eventually closed for possibly-obsolete reasons:

> After using this branch for a bit, I realized that doing the tagging implicitly during `build` is probably not ideal. On a shared host which builds and tests many images (jenkins), you probably don't want to tag things until after the tests have completed.

As discussed in the following comments, this could be worked around by adding a git SHA to the tag, which is possible now that we have environment variable expansion:

```yaml
web:
  image: hyperglobalmegacorp/web:$SHA
  build: .
```

**Comment by bfirsh** [comment]
Many users have specifically asked for this to fix use case 1. Their builds take a long time and they want to on board users quickly. They get round it by having shell scripts to pull and tag the images.

I've heard fewer people ask for 2 and 3, and nobody's asked for 4.

**Comment by aanand** [comment]
To be honest I'm not that worried about it, and it's a situation with pretty clear semantics - after running `docker pull SERVICE` or `docker build SERVICE`, you can always be sure of where the current image came from. So I think it's fine.

**Comment by dnephin** [comment]
This issue was originally raised quite a while ago (#627)

I'm +1 on being able to specify both

At a previous gig I worked on a tool to handle the problem in (1). Unfortunately we didn't get a chance to open-source it, but it was basically what you describe (pull before a build). That way you use `pull` as a way to replicate the build cache.

> 1) Lets you pull pre-built images from the Hub so you don't have to build them locally (docker-compose pull; docker-compose up). Their builds take a long time and they want to on board users quickly. They get round it by having shell scripts to pull and tag the images.

I think we need to decide on the correct default (#693 vs #12). We have a `--no-build` flag already, so if we to go with #12 we can always turn it off (or we could add `--build` and go with #693), but I think the current behaviour is wrong and confusing. Having both an `image` and `build` will just make it even more confusing.


> 2) Lets you easily push images that you have built

So we'd want to add at least `docker-compose push` ?

**Comment by romqin** [comment]
:+1: for the use case 3 !

**Comment by schmunk42** [comment]
I'd have a question about use case 1, if the users don't need to build the image, why do they specify build at all? Are they customizing the container only with host volumes?

**Comment by dnephin** [comment]
I believe use case 1 is more about bootstrapping. When you first get started, pulling an existing master image is often faster than building everything locally.  After that, you get to re-use the cached layers that haven't changed.

I've updated the description to reflect this.

**Comment by mebinum** [comment]
(y) for this issue

**Comment by StalkAlex** [comment]
As I understand now there is possibility to push to own registries, but couldn't understand in what place of compose.yml file I should specify my own url.
