### ISSUE TITLE
ANSI escape sequences showing when pulling on Windows

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#2095]
![unnamed](https://cloud.githubusercontent.com/assets/40906/10099344/a43b72ce-6380-11e5-811b-4ccf238e5ed4.png)

Reported by @ahmetalpbalkan (thanks!):

"We solved this issue in both docker-cli and docker-machine by using the https://github.com/Azure/go-ansiterm package that does ANSI terminal emulation in Windows consoles. Python may have something similar."

**Comment by dnephin** [comment]
Maybe https://liftoff.github.io/GateOne/Developer/terminal.html or http://pyte.readthedocs.org/en/latest/

**Comment by ahmetalpbalkan** [comment]
Ofc I should note that this is cmd.exe/PowerShell behaviour. Git Bash probably would work just fine.

**Comment by mikkotikkanen** [comment]
@ahmetalpbalkan Colors work just fine on cmd/PowerShell, fe. just running a container directly with docker, colors display correctly (as with any other console application), it's just docker-compose that borks them up.

**Comment by dnephin** [comment]
Related docker-cli PR https://github.com/docker/docker/pull/11566

**Comment by shin-** [comment]
Fixed by #4070
