### ISSUE TITLE
Only show multiple port clash warning if multiple containers are about to be started

### ISSUE THREAD

**Issue by ulope** [docker/compose#2096]
Currently when using `docker-compose scale ...` a warning about potentially clashing ports is emitted for every container that defines ports even when the requested scale number is zero or one.

I'd suggest to only show this warning when a scale number > 1 is requested.

**Comment by dnephin** [comment]
This was fixed at some point. There is now a check for `desired_num > 1` before warning.

**Comment by dnephin** [comment]
Oops, that's only for the container_name, not the host port

**Comment by dannyprout** [comment]
#dibs
