### ISSUE TITLE
[Usability/Feature Request] Do something better than failing with a cryptic ImportError backtrace when websocket package conflicts with distribution package

### ISSUE THREAD

**Issue by JonasT** [docker/compose#2101]
When installing docker-compose through pip, the installation can conflict with existing websockets package (already provided by the distribution/not installed through pip) as described here: #1996 

While this can be worked around by the user and I understand this is somewhat expected given the limitations of pip and the inherent problem of installing something system-wide with distribution python packages around and no use of virtualenv, I believe there are ways to improve the handling of this:

---

*Idea 1:* Catch the ImportError of the websocket package and display a *helpful message* which describes the problem, and suggests to the user to either wget docker-compose as a finished working package or remove the distribution's websocket package and try reinstalling it with pip to get a compatible version.

*Idea 2:* Figure out how to change the pip package so it somehow installs the correct websockets thing right away even with distribution packages around. (I have no idea of pip so I guess this might be impossible, I'm just adding it here in case there are ways to do this and nobody has bothered to try it)

---

At least the first one should be easily doable and would be a vast improvement for people running into this issue. If other approaches are despite being possible too much effort, please at least consider the first idea of a simple more descriptive helpful error message.

**Comment by dnephin** [comment]
We've updated the instructions to include details about virtualenv. 

We shouldn't be hacking around poorly packaged distro packages.
