### ISSUE TITLE
Docker Compose download URL incorrect

### ISSUE THREAD

**Issue by coldib** [docker/compose#2107]
Hi,

I just discovered, that the URL stated in many installation instructions (https://github.com/docker/compose/releases/download/) is not available, a 404 Page not Found Error is returned.

This URL is mentioned on the following pages:
- https://docs.docker.com/compose/install/
- https://github.com/docker/compose/releases

Regards
coldib

**Comment by dnephin** [comment]
I guess it should be https://github.com/docker/compose/releases/latest

**Comment by coldib** [comment]
The issue is, you can't download compose using 

curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

**Comment by dnephin** [comment]
Oh, that works fine for me. I copied the url from the docs and it downloaded fine.  Maybe the issue is we don't have a binary for your system.

What does `uname -s` and `uname -m` return for you ?

**Comment by coldib** [comment]
It's working now when I add execute the commands manually and download by https://github.com/docker/compose/releases/download/1.4.2/docker-compose-Linux-2.4

Thanks for your help :)
