### ISSUE TITLE
unable to find a node with port 443 available

### ISSUE THREAD

**Issue by buster** [docker/compose#2117]
I have a setup with "docker machine" and 3 VirtualBox docker hosts.
When i run "docker-compose up" on my YML file which starts a web server in port 443 everything works as expected. BUT when i stop the containers and run "docker-compose up" again i get the mentioned error message.
The only fix seems to be to remove the container. But i actually want to restart just that container and not remove it...

**Comment by dnephin** [comment]
It sounds like you're using swarm, is that right?

This may be a bug with swarm, or it may be on the compose side.  Could you provide the commands you ran and the output?  Doing a `docker-compose stop` might free up the resources

**Comment by buster** [comment]
Hi,

i think this is a misunderstanding then. I was always just using "up" but i should have used "start".
So.. the usual workflow is "docker-compose up", "docker-compose stop" and if i want to restart my containers i use "docker-compose start" and not "docker-compose up" which would try to create new containers...
