### ISSUE TITLE
Error when running docker-compose build/up on Windows

### ISSUE THREAD

**Issue by atrauzzi** [docker/compose#2133]
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\docker-compose-script.py", line 9, in <module>
    load_entry_point('docker-compose==1.5.0.dev0', 'console_scripts', 'docker-compose')()
  File "C:\Python27\lib\site-packages\compose\cli\main.py", line 51, in main
    command.sys_dispatch()
  File "C:\Python27\lib\site-packages\compose\cli\docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "C:\Python27\lib\site-packages\compose\cli\command.py", line 46, in dispatch
    raise errors.ConnectionErrorGeneric(self.get_client().base_url)
AttributeError: 'TopLevelCommand' object has no attribute 'get_client'
```

Just trying things out on Windows, but getting this error.  Builds work on OSX instances of docker-compose.

**Comment by alexandrev** [comment]
Hi @atrauzzi, I want to reproduce the issue. Could you give me more detail of the task you were performing when you face this error? And any details about your own enviroment (OS version, docker-compose version..) Thanks!

**Comment by atrauzzi** [comment]
@alexandrev - Sure, I was just trying to do a `docker-compose up` on a project of mine.  Very simple, boots up a web server container, data container and a mariadb container.

I'm running whatever version of docker compose that was just recently announced as being available for Windows.  I installed it via a `git+git://....` pip command.

Windows 10.  Nothing too fancy otherwise.

**Comment by alexandrev** [comment]
Could you share your docker-compose.yml (with the changes you need to
preserve any confidentiality issue)?

**Comment by atrauzzi** [comment]
Sure!  It's nothing proprietary at all.  We're using Google App Engine for a project and the local development server has a lot of quirks on OSX.  So we containerized it with the following:

```
data:
  container_name: project_dev_data
  image: busybox
  volumes:
    - /var/lib/mysql
    - ./storage:/var/www/storage

mysql:
  container_name: project_dev_mysql
  image: mariadb

  ports:
    - "3306:3306"

  volumes_from:
    - data

  environment:
    MYSQL_ROOT_PASSWORD:
    MYSQL_DATABASE: project
    MYSQL_ALLOW_EMPTY_PASSWORD: yes

web:

  container_name: project_dev_web
  build: .

  volumes_from:
    - data

  links:
    - mysql:mysql

  ports:
    - "8000:8000"
    - "8080:8080"

  volumes:
    - .:/var/www
    - ~/.ssh:/root/.ssh

  volumes_from:
    - data
```

**Comment by dnephin** [comment]
I think I see what's wrong. I missed an instance of `self.get_client()` when I remove `get_client()` from command class.

This error only triggers if compose fails to connect to the docker engine API (which is why it's hard to reproduce).  I'll work on fixing this error branch, but you'll still need to figure out why it can't connect to engine?  Are you running docker toolbox?

**Comment by atrauzzi** [comment]
@dnephin Yeah, I am.  I run the bundled bash terminal.

**Comment by atrauzzi** [comment]
I wanted to note that I've been getting this error quite a fair bit lately.  It seems like the Docker tools running Windows-side keep losing the ability to connect to my VM.

The strange thing is that my VM is running fine and the IP isn't changing.
