### ISSUE TITLE
Containers should not run if link dependancies fail

### ISSUE THREAD

**Issue by jberkus** [docker/compose#2137]
Setup:

serviceA:
       image: serviceA:1.0.1
       command: --switch-that-fails=1

serviceB:
       image: serviceB:1.0.2
       links:
             - serviceA:serviceA

The way it is now (docker compose 1.4.2):
1. docker_compose up
2. the entrypoint script for serviceA image fails
3. serviceB container starts up anyway
4. the link hostname inside serviceB for "serviceA" is not set: "serviceA hostname not known"
5. serviceB container is up, but producing confusing errors

The way it should be:
1. docker_compose up
2. the entrypoint script for serviceA image fails
3. serviceB does not start, or immediately shuts down

**Comment by dnephin** [comment]
This is not really possible. The script running in serviceA could fail at any time. There is no event to block on and say "ok serviceA is now running successfully".

I think this needs to be handled by healthchecks/monitoring, with is external to compose.

**Comment by jberkus** [comment]
Looking for you on IRC so that I can understand this.

**Comment by jberkus** [comment]
Per discussion on IRC, the puzzling part about this bug is that the --link hostname is not assigned in the circumstances described.

**Comment by jberkus** [comment]
Per further discussion on IRC: I will test with the next release of Compose which includes "network" support, and see if the issue goes away.

**Comment by thaJeztah** [comment]
@jberkus have you been able to test with the new networking?

**Comment by jberkus** [comment]
Not yet.  What release do I need to be running?

**Comment by thaJeztah** [comment]
docker 1.9.1 adds the new networking (no aliases yet for containers though, that's being worked on for docker 1.10; https://github.com/docker/docker/issues/18699). The current version of docker compose (1.5.2) brings support for the new networking (currently as "experimental" feature; see the 1.5.0 release notes; https://github.com/docker/compose/releases/tag/1.5.0)

**Comment by dnephin** [comment]
Compose 1.6.0 RC1 was just released, which will use networking by default with a v2 compose file.

**Comment by jberkus** [comment]
OK, will try.

**Comment by ijc** [comment]
Issue grooming: closing as stale.
