### ISSUE TITLE
Send foreground process to background

### ISSUE THREAD

**Issue by JoyceBabu** [docker/compose#2138]
Is it possible to send a foreground process (started without the `-d` flag) to run as a background daemon later on?

**Comment by dnephin** [comment]
`-d` isn't actually "background" it's "detached". The `docker-compose` process stops.  There isn't any way to  detach the the "attached" mode without shutting down containers.  I would recommend just using detached and `docker-compose logs`

**Comment by JoyceBabu** [comment]
Thank you for the clarification @dnephin.

**Comment by aanand** [comment]
You *can* actually detach from a `docker run -it` [with Ctrl-p Ctrl-q](https://docs.docker.com/articles/basics/#running-an-interactive-shell). We should arguably support that with `docker-compose run`.

**Comment by JoyceBabu** [comment]
It would be a useful feature. On dev environment I sometimes forget to add the `-d` flag. When there are multiple linked containers with scaling, it takes some time to stop all the containers and restart with the `-d` flag.

**Comment by csaftoiu** [comment]
+1 for supporting it from `docker-compose up` and `docker-compose run`

**Comment by emmerich** [comment]
Otherwise, is it possible to set detached mode to be the default mode? So if I run `docker-compose up` it'll run in detached mode by default?

**Comment by phongiswindy** [comment]
`ctrl-z `works for me. I am with docker-compose version 1.15.0.

**Comment by sroycode** [comment]
nohup worked for me across several versions :)
