### ISSUE TITLE
Port range doc got lost

### ISSUE THREAD

**Issue by adrienbrault** [docker/compose#2151]
https://github.com/docker/compose/pull/2066#commitcomment-13624269

**Comment by dnephin** [comment]
I'm a little worried we might have lost of things in the merge. I'm not sure what else changed between the original PR and the rebase.

**Comment by mnowster** [comment]
@dnephin I was very careful when rebasing to ensure the volumes and volumes_from work didn't get lost which was previous big change that happened between the two. I'm not as worried, this is a small mistake.
