### ISSUE TITLE
[Feature Request][run] add option to start additional containers

### ISSUE THREAD

**Issue by greg0ire** [docker/compose#2167]
I have a complex problem I'm trying to solve. I have an appserver containers, on which I want to run tests (on Gitlab CI). I can run most of the tests like this : 

> docker-compose run --rm appserver /bin/su greg -c "make -f /srv/Makefile test"

My problem is that amongst this test suites, there is one that uses an http client that tests my application "from the outside", and that to do that, the `webserver` container that runs nginx needs to be booted. It would be if `appserver` was linked to `webserver`, but I cannot do that because `webserver` is itself linked to `appserver`, which means it would create a circular reference. I need to link `webserver` to `appserver`, because `appserver` runs an upstream service needed for the nginx instanced run inside `webserver` to boot properly.

My problem would be solved if I had the option to start other containers (with an option maybe), after the container I want to run. A workaround is to use `up`, run the tests, and then use `stop`, but if the tests fail, `stop` is simply not run by gitlab-ci, so I am left with dangling containers. Not cool.

Any ideas?

**Comment by dnephin** [comment]
Using `up` and `stop` seems fine to me, that's what I run.  The problem seems to be that gitlab ci doesn't provide a way to cleanup? I'm not sure what the interface is, but if you're just running a bash script, you can `trap "docker-compose stop" EXIT` (see http://redsymbol.net/articles/bash-exit-traps/ for more examples).

**Comment by greg0ire** [comment]
I tried using it, but I ended up doing dirty tricks like "sleep 1" to make sure the entrypoint for my container had completely done his job before running the tests with `exec`. Plus, if I can avoid booting (and pulling) containers that are not needed for the tests, it is better for me.

But thanks for the `trap` tip, it should work around the Gitlab lack of cleanup task quite well :)

**Comment by greg0ire** [comment]
I just realized I will be forced to do that anyway, since I need to have `php-fpm` running on app server and what I run instead of it is my test suite… thanks again.
