### ISSUE TITLE
Docker compose django example dont work

### ISSUE THREAD

**Issue by marioidival** [docker/compose#2173]
Specifically this command, the project is not created on the host
`docker-compose run web django-admin.py startproject composeexample.`

```
docker-compose --version
docker-compose version: 1.4.2
OSX El Capitan
```

**Comment by charleswhchan** [comment]
Hello @marioidival,

Looking at the [django docs](https://github.com/docker/compose/blob/0409b287ad3ede39282c199d611456aab15dca71/docs/django.md), there is a space between "compose" and "example" and "."

ie.
```
$ docker-compose run web django-admin.py startproject compose example .
```

Could you try copy and paste the command above?

**Comment by marioidival** [comment]
Hello @charleswhchan That is it... I forgot to go back and close the issue, it was this issue and another in the `docker-compose.yml`, beginner thing ..

Thank you

**Comment by charleswhchan** [comment]
Excellent. :relaxed:

**Comment by ssyberg** [comment]
Has this actually been fixed in the docs? I'm still seeing the same issue and there are still people posting about this on stackexchange, etc
