### ISSUE TITLE
Connecting to a TLS protected Docker server

### ISSUE THREAD

**Issue by kennu** [docker/compose#218]
I have a private Docker server protected by a TLS certificate. I use these options to connect:

    docker --tls --tlscert=$HOME/.docker/client.crt --tlskey=$HOME/.docker/client.key

Is this possible with Fig? I couldn't find any option to do it.

**Comment by mosquito** [comment]
https://github.com/docker/fig/pull/977

**Comment by dnephin** [comment]
This has been supported for a while http://docs.docker.com/compose/reference/overview/#environment-variables
