### ISSUE TITLE
[Mac] docker-compose won't run due to "Couldn't connect to Docker daemon" error

### ISSUE THREAD

**Issue by globexdesigns** [docker/compose#2180]
I'm very confused about how docker-compose is supposed to work on my Mac. Here are the steps I took:

1) Installed Docker Toolbox (Docker version 1.8.2)
2) Tried to run `docker-compose up` but got `Illegal instruction: 4` error as per #1885
3) To fix the issue, I installed `docker-compose` with pip via `sudo pip install -U docker-compose`
4) Now when I run `docker-compose up` I get `Couldn't connect to Docker daemon - you might need to run `boot2docker up`.`

Which is very confusing because all the documentation says that `boot2docker` is deprecated. And trying to install boot2docker isn't working for me either.

I'm not sure what else to try. Currently have docker-compose v1.4.2 installed.

**Comment by dnephin** [comment]
We recently fixed this error message (the fix will be in the next release).

It should say "you might need to run `docker-machine start default`".

If you still can't connect, and the `docker-machine` is running, you can configure compose to use the machine with `eval "$(docker-machine env default)"`

**Comment by globexdesigns** [comment]
Ok thanks. Looks like my issue is with the Docker VM. It's giving me all sorts of TLS errors even when running regular docker commands like `docker images`.

```
Get http:///var/run/docker.sock/v1.20/images/json: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

I'll take it up with the docker team.

**Comment by dzlab** [comment]
I getting the same error, but I don't want to use the default machine but rather another machine created with the `amazonec2` driver, is it possible?

**Comment by dnephin** [comment]
Yes. Compose will use whatever engine is set in the `DOCKER_HOST` environment variable (which is what gets set by `eval $(docker-machine env ....)`.

**Comment by dzlab** [comment]
ah thanks, I didn't know about `DOCKER_HOST`!!

**Comment by shankiesan** [comment]
I'd just like to add something for anyone who visits this in the future... I keep having this issue every time I open a new shell, so I added `eval $(docker-machine env default)` to my `~/.bash_profile`. Works a treat. Of course, someone here may tell me that this is a Very Bad Idea (TM) :smile:

**Comment by koushikckm** [comment]
Yes it works. But why eval $(docker-machine env default)  suddenly. It was working fine before

**Comment by shankiesan** [comment]
Yeah, I'm not sure either. Was working for me earlier as well.

**Comment by Boulboulouboule** [comment]
`eval $(docker-machine env default)` works for me ! thanks :)

**Comment by michahell** [comment]
Eval "$(docker-machine env default)" worked, thanks!

**Comment by shankiesan** [comment]
I'm still not totally happy with the solution of adding `eval $(docker-machine env default)` to `~/.bash_profile` (even though I proposed it) as it adds about a 2s delay onto opening a new terminal window. Anyone have any better ideas?

**Comment by michahell** [comment]
@shankiesan ```alias eval_evil_docker="eval $(docker-machine env default)"```

**Comment by shankiesan** [comment]
Hah yes I guess that wouldwork @michahell . Still have to do something before every time you use docker. Not ideal, but not bad!

**Comment by lewistaylor** [comment]
@shankiesan The only other option I can see is to export the variables produced from `docker-machine env default` in .bash_profile. Yes the IP could theoretically change, but in reality this is far less likely to occur that the delay in opening a new shell on a daily basis :-)

**Comment by shankiesan** [comment]
That's a good idea @lewistaylor . I tried that before it didn't work, but it has this time so it must have been operator error. Nice one, that's a great suggestion :+1:

**Comment by michahell** [comment]
@shankiesan @lewistaylor wow, can't understand I didn't come up with that. even better solution :+1:

**Comment by RyanCCollins** [comment]
I am having this same issue close to everyday and it's a bit of a pain.  The suggested fix to run `docker-machine env default` and then `eval "$(docker-machine env default)"` do fix it, but I am hoping to understand the issue a bit better so that I could implement a permanent fix.

Am using El Capitan.  Would love if someone knows of a fix that'll fix this for good.  Thanks!

**Comment by ctf0** [comment]
this issue still persist , the only solution is to use 

$ eval $(docker-machine env laravel-app-host) // which doesnt give any output & without it we get the error
$ docker-compose up

**Comment by KonstantinKolodnitsky** [comment]
Sometimes I have the same issue BUT it comes up ONLY when I close my macbook. If I restart the system it may start fine, may not. If not I restart again and it's usually working. My guess is that probably the problem in the IP/ports, only guess, cause if I restart my laptop with unclosed programs (like PHPStorm) it usually won't work. If I close all the running programs and restart it, it's working.

**Comment by syzer** [comment]
+1

**Comment by nwshane** [comment]
@lewistaylor @shankiesan @michahell How do you export the variables from `docker-machine env default` in .bash_profile? I'm not so good with bash, so I'd appreciate help on implementing this fix.

**Comment by lewistaylor** [comment]
Drop docker-machine/dinghy/boot2docker and use docker for mac, it's set to
become the official runtime

**Comment by shankiesan** [comment]
@nwshane Just edit `.bash_profile` in your favourite text editor. For instance:

`nano ~/.bash_profile` and add the lines that you got from `docker-machine env default`. Then  you have to `source` that file – you can do this by either opening and closing your terminal session, or better, `source ~/.bash_profile`

That should do it.

**Comment by nwshane** [comment]
@shankiesan Great, thanks! That did the trick. I was confusing myself by thinking that I had to run `docker-machine env default` and get the variables from there—but of course that's what `eval "$(docker-machine env default)" does.

**Comment by nosources** [comment]
`$  wordpress-compose eval $(docker-machine env wordpress)`
`$  wordpress-compose docker ps`
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
443c7386f4ef        wordpress           "/entrypoint.sh apach"   7 minutes ago       Up 7 minutes        0.0.0.0:80->80/tcp       wordpress_app
a790fdc3ca70        mysql               "docker-entrypoint.sh"   14 minutes ago      Up 14 minutes       0.0.0.0:3360->3306/tcp   wordpress_db
$  `wordpress-compose docker-compose up`
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.`


`$ wordpress-compose docker-compose --version`
docker-compose version 1.8.0-rc1, build 9bf6bc6

`$  wordpress-compose docker --version`
Docker version 1.12.0-rc2, build 906eacd, experimental

Here is my information, everything works fine if I use `docker run .......mysql.....` and `docker run ....link....wordpress`, and I can access the blog in browser. When I want to try `docker-compose`, It doesn't work. I have deleted the default machine, Now wordpress is in use.

Could help me find out what is wrong?

**Comment by lang100** [comment]
i am having the same issue 
but i am not using docker-machine only docker-compose
any idea ??

**Comment by gauravjeet** [comment]
`eval "$(docker-machine env default)"` solves the issue

**Comment by Rots** [comment]
Had the same problem with one specific service in docker-compose.

Was a permissions issue... the files to be uploaded to docker were not owned by the current user.

**Comment by marioluan** [comment]
Same as @Rots here =/

**Comment by jtaylor1989** [comment]
paste the command: 
eval "$(docker-machine env default)" 
on your mac terminal

**Comment by shapeofarchitect** [comment]
{ "Error checking TLS connection: machine does not exist" `}` , now getting this issue whenever i try to use docker-machine env default , tried loading from the bash_profile too , need help !
