### ISSUE TITLE
Update docs to say "environment" in `docker-compose.yml` has no effect during the build phase

### ISSUE THREAD

**Issue by nhooey** [docker/compose#2183]
The environment variables in `docker-compose.yml` are not set during the build phase of a container's life, but only during the "run phase" (that might be the wrong name for it).

Until this is possible, the [documentation](https://docs.docker.com/compose/yml/#environment) should be updated to be unambiguous by stating that the environment will only get set during the run phase.

**Comment by uzzer** [comment]
It would be nice to cover topic about using variables in `docker-compose.yml`. In example it is not clear how to pass existing environment variables to `command:`.

**Comment by dnephin** [comment]
Using variables is covered here: https://docs.docker.com/compose/compose-file/#variable-substitution

Compose 1.6.0 comes with a v2 format which  separates build-time options from run-time options, so anything outside of `build` should be clearly identified as not build related (https://github.com/docker/compose/blob/master/docs/compose-file.md#build)

That build section also supports `args` which act like environment variables for build.

**Comment by jimzucker** [comment]
Is there already a ticket to support evaluation so i can do something like

URL=http://'docker-machine ip sonar'/sonar




Sent from my iPhone

On Feb 3, 2016, at 15:16, Daniel Nephin <notifications@github.com<mailto:notifications@github.com>> wrote:


Using variables is covered here: https://docs.docker.com/compose/compose-file/#variable-substitution

Compose 1.6.0 comes with a v2 format which separates build-time options from run-time options, so anything outside of build should be clearly identified as not build related (https://github.com/docker/compose/blob/master/docs/compose-file.md#build)

That build section also supports args which act like environment variables for build.

-

**Comment by dnephin** [comment]
I think your example got cut off, I'm not sure what you're asking.

**Comment by jimzucker** [comment]
Often you find that there are setting that can be derived from the ENV vs hardcoded in the yml file especially in development.  I am working on the containers for test and deployment of an open source project and I realized if I could set things in the yml file such as VARIABLE=`docker-machine ip sonar` or VARIABLE2=`docker-machine ip machine2` or UID=`id|cut -c5-7` could be very powerful to make yml lets static/env dependent (I saw another ticket about UID a few minutes ago).  If we took this approach it would solve alot env issues...

**Comment by nhooey** [comment]
@dnephin None of the documentation you referenced, including the [Variable Substitution](https://docs.docker.com/compose/compose-file/#variable-substitution) section and the [Build](https://github.com/docker/compose/blob/master/docs/compose-file.md#build) section mention that the environment is not set during the build phase.

Although `args` are mentioned in the [Build](https://github.com/docker/compose/blob/master/docs/compose-file.md#build) section, it's still misleading for the [docker-compose.yml documentation about the environment](https://docs.docker.com/compose/compose-file/#environment) to avoid mentioning that the variables won't be set during the build phase.

Could you update it to be more clear? It would really help avoid confusing new users.

**Comment by dnephin** [comment]
None of the options outside the build section are available to build. I don't think it makes sense to call out `environment` explicitly, because that would imply that other options are supported.

I think it might make more sense to document it in the `build` command reference.

**Comment by nhooey** [comment]
Good point, some documentation in `build` makes sense.

Perhaps now that the build phase has `args` now, where it didn't when I initially wrote this issue, someone new won't be trying to use `environment` to pass in values.
