### ISSUE TITLE
docker-compose [stop | kill | rm] does not cleanup docker-compose run <service>

### ISSUE THREAD

**Issue by vvitayau** [docker/compose#2184]
``docker-compose [stop | kill | rm]`` will properly cleanup ``docker-compose up``.
But it does not appear to have worked for ``docker-compose run <SERVICE>``

For example

Cleanup will remove __cibackbeatbackbeatserver274_ci_1__  but not __cibackbeatbackbeatserver274_ci_run_1__
```
$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 run -T ci
Creating cibackbeatbackbeatserver274_redis_1...
Creating cibackbeatbackbeatserver274_database_1...

$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 ps
                 Name                               Command               State    Ports
------------------------------------------------------------------------------------------
cibackbeatbackbeatserver274_ci_run_1     bin/run-tests.sh                 Up
cibackbeatbackbeatserver274_database_1   /docker-entrypoint.sh postgres   Up      5432/tcp
cibackbeatbackbeatserver274_redis_1      /entrypoint.sh redis-server      Up      6379/tcp
```

where 
```
$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 kill 
$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 rm -v --force
```

Does not properly cleanup ``docker-compose run <SERVICE>``
```
$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 ps
Name   Command   State   Ports
------------------------------
cibackbeatbackbeatserver274_ci_run_1     bin/run-tests.sh                 Up
```

So I ended up having to bash trap
```
$ for i in `docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 ps -q`; do docker kill $i; docker rm -v --force $i; done
```

To ensure a complete cleanup per
```
$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 ps
Name   Command   State   Ports
------------------------------
```

**Comment by dnephin** [comment]
I forget why it is we do this, but I think we should at least provide a flag to `--rm` to remove them, if not remove them by default.

You can use `docker-compose run --rm` for now to remove them automatically when they exit.

**Comment by vvitayau** [comment]
I'll give that a try ... Ty

**Comment by vvitayau** [comment]
Turns out ``docker-compose run --rm`` is not an option of DotCi otherwise jenkins is unable to retrieve artifacts from the build result.

**Comment by kevingelion** [comment]
Still experiencing this issue where I'll call `docker-compose up -d <service>` and then `docker-compose stop` and only my Postgres service will stop. Not my main. All of this talk seems to be about removing/killing one-offs but I can't just stop all of my containers successfully. Any ideas?

**Comment by bigbassroller** [comment]
@kevingelion Have you tried ```docker-compose down --volumes```. I use that stop docker-compose processes on my mac client.
https://docs.docker.com/compose/reference/down/
