### ISSUE TITLE
`docker-compose logs` behavior is different from `docker logs`

### ISSUE THREAD

**Issue by AndersKOlsson** [docker/compose#2187]
`docker-compose logs` only returns when the service(s) exit. `docker logs` returns directly. This is confusing, and makes it hard to get logs in a automation environment.

I suggest the default behavior of `docker-compose logs` should be to return, just like docker does. Then the '-f, --follow' flag could be introduced, which would mimic the behavior that we have today.

Related: https://github.com/docker/compose/issues/1549

**Comment by schmunk42** [comment]
Would also be nice if compose could support `--tail=`.

**Comment by matthughes** [comment]
Not ideal, but a workaround for this is:

`docker-compose  ps -q | xargs -n 1 docker logs`

**Comment by simonvanderveldt** [comment]
@dnephin @aanand Do you have an idea how you want to address this? Asking because it will be a backwards incompatible change.

@seguins Do you plan on creating a PR for your changes? Else I'll start working on it.

**Comment by dnephin** [comment]
The PR is #2720

I think it might be ok to change the behaviour of `logs` as long as `up` stays the same.

**Comment by simonvanderveldt** [comment]
> The PR is #2720

Thanks, totally missed that.

> I think it might be ok to change the behaviour of logs as long as up stays the same.

That makes sense, it should probably still be in bold in the release notes ;)
