### ISSUE TITLE
Cannot run docker-compose 1.5.0 RC1 on OSX Yosemite

### ISSUE THREAD

**Issue by pointcom** [docker/compose#2222]
I have just upgraded my version of docker-compose from `1.4.2` to `1.5.0rc1` but now I get the following error everytime I use the `docker-compose` command : 

```
$ docker-compose --help
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2793, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: functools32
```

I followed the instructions from the `1.5.0 RC1` release page to install it and use the command below : 

```
$ pip install -U docker-compose==1.5.0rc1
```

My config : 

OS : OSX Yosemite 10.10.3
Docker version : Docker version 1.6.2, build 7c8fca2
Python version : Python 2.7.6

If there's anything I can do to get better insights, let me know and I'll paste the output here.
Thanks

**Comment by dnephin** [comment]
I'm not sure why pip didn't install this module, it's a dependency of `jsonschema` I believe.

Could you try installing the binary, or using a virtualenv with pip?  We've updated our "install with pip" instructions (https://github.com/docker/compose/blob/master/docs/install.md#install-using-pip) to mention virtualenv.

**Comment by pointcom** [comment]
I've just installed the binary from Master builds and it seems to work, thanks!

https://dl.bintray.com/docker-compose/master/:docker-compose-Darwin-x86_64


```
$ /usr/local/bin/docker-compose --version
docker-compose version: 1.5.0dev
```

**Comment by pointcom** [comment]
BTW, when I try to install the binary via the URL from the release page, I've got the following error : 
```
$ docker-compose --version
Illegal instruction: 4
```

Here is the link to the binary : 
https://github.com/docker/compose/releases/download/1.5.0rc1/docker-compose-Darwin-x86_64

Thanks

**Comment by dnephin** [comment]
@pointcom Ya, we've had that problem for a while (see #271).  The master builds are run using 10.10, so it seems to work better for the new OSX releases, but it doesn't work at all for the 10.8 release apparently.

It might be time to consider dropping support for 10.8.

Since we have #271 to track the illegal instruction error, going to close this issue.

**Comment by dnephin** [comment]
There's more details about the original error here Julian/jsonschema#233

The short version is that a newer version of pip is required

**Comment by pointcom** [comment]
@dnephin Great.
Actually, I've installed docker-compose `1.5.1` version and the issue has gone away.

Thanks!
