### ISSUE TITLE
Improvements to `docker-compose logs`

### ISSUE THREAD

**Issue by dnephin** [docker/compose#2227]
This epic covers a bunch of improvements we'd like to make to the `logs` command.
- ~~default to not following (similar to `docker logs`) (#2187, #1549)~~ in 1.7.0
- ~~support `-f, --follow` (the current behaviour) to keep following log output~~ in 1.7.0
- ~~support `--tail=<num>` to only show a number of lines from the end of the log (#1083, #265)~~ in 1.7.0
- ~~`-t, --timestamp` to add timestamps to the logs (https://github.com/docker/compose/issues/2227#issuecomment-171815635)~~ in 1.7.0
- ~~if a new container is started while `logs` is running, logs for that container should start to show up in the log stream (#1115)~~ in 1.7.0
- ~~if the log stream is done (the containers have stopped) logs should exit (#1866)~~ in 1.7.0
- ~~flush the buffer more frequently to deal with buffered output (#1060, #1549)~~ Fixed in 1.5.1
- continue printing logs after the first SIGINT until all containers exit (or we get another SIGINT) (#592)
- `--json` output the raw json lines (#2156)
#1866 includes a proposal for how to support many of these features

**Comment by bkmeneguello** [comment]
My suggestion is to add to the --since= option the keyword "boot" to log only since boot time

**Comment by simonvanderveldt** [comment]
@dnephin Thanks for putting this on the radar. We've run into all of the listed issues except for the buffered output (though we might've missed it).
Especially the disparity between how `docker logs` and `docker-compose logs` work should be fixed.

**Comment by blah238** [comment]
I couldn't find it anywhere else, but can we also add a `-t` option for displaying timestamps (like docker's logs command)?

**Comment by dnephin** [comment]
Added it to the list

**Comment by gggeek** [comment]
+1 (I just finished adding "echo 'date'" lines to all my entrypoint scripts because of the lack of this feature!)

**Comment by ibizaman** [comment]
Clearly a +1 for me :) thanks for this awesome tool!

**Comment by lidio601** [comment]
+1

**Comment by egyptianbman** [comment]
Thank you for all the improvements to `docker-compose logs`. One request -- can you show just one timestamp? I'm seeing the following:

```
app_1         | 2017-07-21T04:08:09.604324214Z INFO [2017-07-21 04:08:09] done: 1/1 100%, 0 vtoday, 1 wtoday, 1 wperiods, 5 req, 27498 ms, no error
app_1         | 2017-07-21T04:08:09.604468226Z INFO [2017-07-21 04:08:09] Time elapsed: 27.498s
app_1         | 2017-07-21T04:08:09.604618517Z INFO [2017-07-21 04:08:09] ---------------------------
app_1         | 2017-07-21T04:08:09.604743622Z INFO [2017-07-21 04:08:09] SCHEDULED TASKS
app_1         | 2017-07-21T04:08:09.614401422Z INFO [2017-07-21 04:08:09] Starting Scheduled tasks... 
```

As you can see, there is a timestamp on the left **and** the right of the message type. Personally, I think most people will only care to see the timestamp on the right.

**Comment by dnephin** [comment]
The second timestamp is from your application, not from docker-compose.

**Comment by augnustin** [comment]
I'd like to suggest making the option `--tail=100` default (or whichever reasonable number), because when forgotten, if the container has been running for quite some time, terminal keeps printing logs for quite a while which is a pain when the point was for instance simply to check that the server correctly restarted.

This may be a bad comparison for some, but this is `heroku logs` default behavior.

Thanks for your consideration

**Comment by patrickdepinguin** [comment]
When using 'docker-compose logs -f' on a container, the complete logs seem to be output again when the container is restarted (and the logs command is kept alive). This does not seem logical to me: I'd expect that 'logs' remembers which logs were already printed and only outputs new messages.

**Comment by NoICE** [comment]
@patrickdepinguin just came here for exactly this issue. I have one terminal running with docker-compose logs -f during development and I restart the container frequently. I have to tear down the thing using docker-compose down for it to forget the logs, otherwise I'm just watching walls of text fly by each restart. Using --tail=100 works, but it would be nice if the docker-compose logs -f didn't reread the whole file just because the container starts.

**Comment by petr-ujezdsky** [comment]
The `--since` option is missing in `docker-compose logs`. The `boot` value suggested by @bkmeneguello would be an awesome addition (for both docker and docker-compose).

And definitely +1 for @simonvanderveldt

> Especially the disparity between how docker logs and docker-compose logs work should be fixed.

**Comment by ijc** [comment]
Issue grooming: From the items on the original list which are not struct through #2156 and #1866 appear to be closed. #592 isn't but I think we no longer need this (stale) tracking issue. Please raise (after checking for existing issues) new issues for other enhancements if they are still relevant.
