### ISSUE TITLE
docker-compose overwrites LABEL statements in Dockerfiles for running containers

### ISSUE THREAD

**Issue by aismail** [docker/compose#2229]
```bash
aismail@hax:~$ docker --version
Docker version 1.8.3, build f4bf5c7
aismail@hax:~$ docker-compose --version
docker-compose version: 1.4.2
aismail@hax:~$ cat /etc/issue
Ubuntu 14.04.2 LTS \n \l
```

I have some Dockerfiles with the new LABEL statement in them. I've built some images out of those Dockerfiles. When I start the containers using docker-compose, the labels are completely replaced with docker-compose specific ones.

Is this intentional? Am I wrong to expect the image labels to still be there, without copy-pasting them in the "labels" section of docker-compose.yml?

**Comment by dnephin** [comment]
There was a change made in docker 1.8.x to not copy image labels to the container. I believe that's been reverted for 1.9.0, so you should see the labels copied over when you upgrade docker.

docker-compose always adds labels to a container to track the containers, but it doesn't remove any labels.

**Comment by aismail** [comment]
@dnephin thank you! Wasn't aware of that, should have done better testing on my side.

Here's the Docker-related PR, for future reference: https://github.com/docker/docker/pull/15503
