### ISSUE TITLE
No colorized output

### ISSUE THREAD

**Issue by Yajo** [docker/compose#2231]
When using `docker-compose logs`, it adds colors by container, but if the container's logs were colorized, they appear all in the same color.

Colorized logs are very useful, so it should be respected by docker-compose.

**Comment by hadim** [comment]
I confirm the bug. `docker run` outputs the correct colorized logs if they exist.

**Comment by aanand** [comment]
Can you provide a minimal failing case? I've got `logs` producing correctly coloured output with a small `docker-compose.yml`:

```yaml
test:
  image: ubuntu:14.04
  command: ['sh', '-c', 'echo \\033[31mhello; echo \\033[32mworld']
```

<img width="462" alt="screen shot 2015-12-07 at 14 58 47" src="https://cloud.githubusercontent.com/assets/1062/11629992/24193f2a-9cf3-11e5-9286-6ea9597af14e.png">

**Comment by hadim** [comment]
I don't remember what I did but I can't reproduce the bug anymore... I tried using `forego` which was the initial thing for what I needed colorized output, but I can't reproduce it anymore.

Wait for @Yajo and see if it still se the bug before closing it maybe.

**Comment by Yajo** [comment]
Weird, your test case works, but I'm using Odoo from `yajo/odoo` image and it does not show colors in docker-compose but does in plain docker. See: 

![captura de pantalla de 2015-12-15 20-31-39](https://cloud.githubusercontent.com/assets/973709/11821658/f0206c42-a36a-11e5-9966-aec1df446e9e.png)

```
docker-compose version
docker-compose version 1.5.2, build 7240ff3
docker-py version: 1.6.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.1k-fips 8 Jan 2015
```

Is it possible that Odoo (Python) is doing anything to check the type of terminal and it gets different in docker-compose and docker?

**Comment by aanand** [comment]
Yes, very possible. Try adding `tty: true` to the service config.

**Comment by Yajo** [comment]
Amazing, it works, thanks!

**Comment by Elindorath** [comment]
I don't think adding `tty: true` is a suitable solution since #3106 ...

**Comment by inquire** [comment]
The tty:true doesn't work anymore :(

**Comment by psychowico** [comment]
confirm. this problem is back. @shin-  maybe you can open it?

**Comment by ikasty** [comment]
You can use ['cat' solution](https://gist.github.com/ikasty/ae76beb34be3d12b66947ebf0872602b).

**Comment by psychowico** [comment]
this is a diffrent problem, but I realized that my output color problem can be result of my app specific setup.

**Comment by mindscratch** [comment]
The `tty: true` works for me with docker-compose 1.9.0

**Comment by pmgouveia** [comment]
when I activated this... my docker-compose does not terminate anymore.. stays hanging...

**Comment by Cyral** [comment]
Most Node packages use a coloring library like chalk which checks for certain things such as the `--color` flag or if it is a terminal to enable color support.

So just add `--color` when you start your app, in my case webpack didn't have color output:

```
"scripts": {
  "start": "./node_modules/.bin/webpack-dev-server --color",
},
```

**Comment by j0hnm4r5** [comment]
Adding `tty: true` did work for me as of Engine v18.06.1-ce & Compose v1.22.0.

**Comment by IAMtheIAM** [comment]
None of these solutions worked. How do we get color when "attaching" to an existing docker container?

**Comment by danvdumitriu** [comment]
A simple workaround which consists in starting docker-compose in the background, writing the output to a logfile and then tailing the logfile.
```
docker-compose up --build | tee /tmp/docker.log > /dev/null &
tail -f /tmp/docker.log | while IFS= read -r line; do printf '%b\n' "$line"; done
```

**Comment by cerino-ligutom** [comment]
Adding `tty: true` worked for me.

Windows 10 Pro 64 bit

![image](https://user-images.githubusercontent.com/6721822/74245891-b3da3080-4d1e-11ea-8205-647c9f3d3d58.png)

**Comment by bertho-zero** [comment]
This works for me __without__ `tty: true`:

```yml
    environment:
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
```
