### ISSUE TITLE
Variable substitution by stdin

### ISSUE THREAD

**Issue by linlinlinlin** [docker/compose#2241]
EX: ```docker-compose up -var POSTGRES_VERSION=9.3```

Because many people using docker-compose to setup many applications at the same server.

If there are two applications I have to using the same image with different tag. But variable only can read from shell environment. I cannot set POSTGRES_VERSION=9.3 and POSTGRES_VERSION=9.4 at the same time. If it can read from stdin will be more flexible. 

Variable priority:
 1. From stdin
 2. From shell environment
 3. Default value inside yaml file.
 4. Default empty string value (empty string)

**Comment by dnephin** [comment]
Why not just do `POSTGRES_VERSION=9.3 docker-compose up` it's shorter than the proposed solution.
