### ISSUE TITLE
Suggest upgrade requests package to 2.9.1

### ISSUE THREAD

**Issue by linlinlinlin** [docker/compose#2242]
For the compatible with docker-py. I hope it can upgrade reqeusts to 2.8.1.

Because in docker-py 1.5 is `requests >= 2.5.2` It will install the latest version of requests(2.8.1).

**Comment by linlinlinlin** [comment]
right now, latest version is 2.9.1. Hope it can change as same as docker-py's rule.

**Comment by ColinHuang** [comment]
+1

**Comment by mgasner** [comment]
+1 consistency with docker-py would be great, it's obviously very common to want to install these in the same environment
