### ISSUE TITLE
Environment option doesn't seem to work in Windows

### ISSUE THREAD

**Issue by dracan** [docker/compose#2243]
Docker Compose seems to fail getting environment variables in Windows. I'm testing on Windows 10 (not tried on any other versions of Windows). Here's a simple YML file:

    test:
      image: centos:centos6
      environment:
        MY_ENVIRONMENT_VARIABLE:

Regardless of whether MY_ENVIRONMENT_VARIABLE has been set, I get the following error:

    Validation failed, reason(s):
    Service 'test' configuration key 'environment' 'MY_ENVIRONMENT_VARIABLE' contains None, which is an invalid type, it should be a stringnumber or a boolean

This is with Docker Compose 1.5.0rc1.

**Comment by GraemeF** [comment]
Specifically, this feature (from the docs) isn't working on Windows:

> Environment variables with only a key are resolved to their values on the machine Compose is running on

**Comment by dnephin** [comment]
This was actually a bug for everyone (not just windows), and was fixed in #2225.
You can try it out with a build of master: https://dl.bintray.com/docker-compose/master/

The fix will be in rc2 (and the final release). If it's not working with master, please do re-open this issue.
