### ISSUE TITLE
Update "ports" docs to mention that ports are forwarded to $(boot2docker ip) in Mac OS instead of `localhost` as in Linux

### ISSUE THREAD

**Issue by nhooey** [docker/compose#2246]
The [ports documentation](https://docs.docker.com/compose/yml/#ports) makes no mention of the fact that the `boot2docker` VM is the node that forwards ports to the Docker container, instead of `localhost` as it does in Linux.

So if you have a container that runs `python -m SimpleHTTPServer 8000` with a `docker-compose.yml` file like this:

``` yaml
mycontainer:
    build: ./
    ports:
      - "8000:8000"
```

On a Linux host, you could connect like this:

``` bash
curl 0.0.0.0:8000
```

But on Mac OS, you have to connect like this:

``` bash
curl $(boot2docker ip):8000
```

It would be helpful if this was mentioned in the documentation.

**Comment by dnephin** [comment]
That's not really relevant in the context of compose. It should be in the boot2docker or docker-machine (which replaces boot2docker) docs.

**Comment by nhooey** [comment]
I understand that these are all separate components, but when someone is trying to get this working, it would help to have a note about what the actual host machine is and how that affects this particular config file directive.

Think about what's likely to happen when any Mac OS user is trying this for the first time, and how we can help them avoid getting misled.

**Comment by dnephin** [comment]
I guess it doesn't hurt to remind people in the reference.  But I think it should be just that, a reminder and a link to the correct documentation for docker-machine.

If we do it for ports, we should do it for volumes as well, because they have a similar relationship with the VM.

**Comment by nhooey** [comment]
Yeah a link to the documentation would be great.

After finding that ports aren't working as the user expects, it's probably the first place they would go if they hadn't read it already.

**Comment by gasgas4** [comment]
Yes... I failed to work with this document http://0.0.0.0:5000/,  until I find this.
I strongly recommend add it for MacOS users.  

thanks
