### ISSUE TITLE
Network aliases created with full container name & not short name

### ISSUE THREAD

**Issue by skelethan** [docker/compose#2248]
Per https://github.com/docker/compose/blob/0409b287ad3ede39282c199d611456aab15dca71/docs/networking.md

![image](https://cloud.githubusercontent.com/assets/9012349/10705720/92822f6a-79a5-11e5-8b02-813db4097ffe.png)

However, what I am seeing is that the aliases are created with the full container name from compose e.g. context_web_1

This eliminates the benefit of consistent aliases, as compose will dynamically assign network alias depending on number of containers & where they are run from.

My simple test below.
![image](https://cloud.githubusercontent.com/assets/9012349/10705780/2d89ddf0-79a6-11e5-81e8-9e335507ed3f.png)

![image](https://cloud.githubusercontent.com/assets/9012349/10705807/71bceea4-79a6-11e5-86d0-f54f05f3a9cd.png)

![image](https://cloud.githubusercontent.com/assets/9012349/10705776/21e4a638-79a6-11e5-9207-552c4df5df1a.png)

**Comment by dnephin** [comment]
I'm able to reproduce this.

cc @aanand, @mavenugo

According to https://github.com/docker/compose/pull/1676#issuecomment-145562152 the container is supposed to join the network using the hostname, but that is not what's happening with docker engine 1.9.0-rc2.

The hostname is correctly set to the service name (ex: "web"), but it's joining the network as "project_web_1" (according to the /etc/hosts in other containers on the network). This is what I see:

```
172.18.0.2      networking_other_1
172.18.0.2      networking_other_1.networking
172.18.0.3      networking_web_1
172.18.0.3      networking_web_1.networking
```

Did this change? Do we need to change something on the compose side?

**Comment by dnephin** [comment]
@skelethan thanks for reporting this. Unfortunately we weren't able to fix this for the current release so we've updated our documentation to match what is supported right now (the container joins the networking using the container name).

In the next release we'll have support for aliases which should support a much nicer short names.

**Comment by Teudimundo** [comment]
Is there any workaround that could be used? Since addresses with `_` are not valid FQDN this bug can cause some pain.

**Comment by dnephin** [comment]
@Teudimundo yup, [the docs](https://github.com/docker/compose/blob/master/docs/networking.md#configure-how-services-are-published) mention that you can set a custom container name with `container_name:`.

**Comment by Teudimundo** [comment]
Thank you, i missed that.

**Comment by pwaller** [comment]
Is there a workaround which doesn't involve setting the container name? I need to run multiple copies of the project at once with different project names, in a CI runner.

**Comment by pwaller** [comment]
@dnephin is there an issue tracking the lack of these hostname aliases I can watch and contribute to? I searched but couldn't find one. I can't use the new networking feature until this is resolved, so I'd like to subscribe to an issue, come back and try again when this is fixed.

Alternatively, it might be useful to reopen this one until containers are accessible via their name without the project.

**Comment by dnephin** [comment]
The workaround is setting the project name in the host environment and using it in the `docker-compose.yml` as described in #2294.

The lack of aliases is a a docker/docker or libnetwork issue, I'm not aware of an issue tracking it, but there maybe one.
