### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xce in position 0: unexpected end of data

### ISSUE THREAD

**Issue by wicope** [docker/compose#2255]
Hi

```
$ docker --version
Docker version 1.9.0-rc2, build 60d36f7
```

```
$ docker-compose --version
docker-compose version: 1.5.0rc1
```

```
$ docker-compose up -d feTestsWatch
$ docker-compose logs feTestsWatch
(...)
feTestsWatch | chrome 43 (2/0/0)                     
feTestsWatch | [15:23:29] Finished 'wct:local' after 32 s
feTestsWatch | [15:23:29] Starting 'test:local'...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 53, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 23, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 26, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 165, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 221, in logs
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.log_printer", line 27, in run
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.multiplexer", line 35, in loop
UnicodeDecodeError: 'utf8' codec can't decode byte 0xce in position 0: unexpected end of data
```

It worked with docker 1.7 and docker-compose 1.4:

```
$ docker-compose up -d feTestsWatch
$ docker-compose logs feTestsWatch
(...)
feTestsWatch_1 | chrome 43 (1/0/0) 
feTestsWatch_1 | [16:26:33] Finished 'wct:local' after 29 s
feTestsWatch_1 | [16:26:33] Starting 'test:local'...
feTestsWatch_1 | [16:26:33] Finished 'test:local' after 36 μs
```

I think the problem is in the character μ:
```
feTestsWatch_1 | [16:26:33] Finished 'test:local' after 36 μs
```
 Thanks

**Comment by dnephin** [comment]
I'm able to reproduce this with docker-compose 1.4.2 as well if the container is created new. If the container already has logs, it doesn't fail in either version.

Looking for a fix

**Comment by dnephin** [comment]
I found https://github.com/docker/docker-py/pull/824 but I don't think it's related to your error.

I'm not able to reproduce any unicode errors with docker-compose 1.5.0-rc1 and docker 1.9.0-rc2.

The error message is not the typical unicode error we see with python 2: "'utf8' codec can't decode byte 0xce in position 0: unexpected end of data".  Normally it's something about trying to encode to ascii, but in this case it's correctly using utf8, and it seems like it can't read the first byte (position 0). Since that character is the first byte in the mu symbol, I wonder if the issue is that the buffer flushed before reading the second byte.

Are you able to reproduce this reliably? What happens if you run `docker logs <container name>` ?  Could you provide more of the Dockerfile or a minimal reproduction of the error?

I was trying with this Dockerfile and compsoe file:

```
FROM alpine:edge
CMD ["echo", "what μ"]
```

```
web:
  build: .
```

**Comment by wicope** [comment]
Hi.
[Dockerfile](https://github.com/vfarcic/books-service/blob/master/Dockerfile.test)

I try it with 
```
feTestsWatch:
  image: vfarcic/books-service-tests
  container_name: feTestsWatch
  stdin_open: true
  tty: true
  volumes:
    - ./client/components:/source/client/components
    - ./client/test:/source/client/test
    - ./src:/source/src
    - ./target:/source/target
    - /data/tests/db:/data/db
  ports:
    - 8080:8080
  environment:
    - TEST_TYPE=watch-front
```

```
elif [ "$TEST_TYPE" = "watch-front" ]
then
  mongod &
  sbt run &
  cd /source/client
  Xvfb :1 -screen 0 1024x768x16 &> xvfb.log  &
  gulp watch
```

I think the problem may be:
* gulp. I don't believe, the same code previously worked with previous versions of docker and docker-compose). Perhaps a solution is put gulp with utf8 but without it worked before.
* python. I try with python2.7 and python3.4 and failure.
* docker 
* docker-compose

Yes with the previous Dockerfile, you can see another possible bug related:

```
$ docker-compose up -d feTestsWatch
Creating feTestsWatch
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

**Comment by FDiskas** [comment]
I have the same problem. 
`docker-compose version: 1.5.0`
`Docker version 1.9.0, build 76d6bc9`

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/compose/cli/main.py", line 54, in main
  File "/code/compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "/code/compose/cli/docopt_command.py", line 26, in dispatch
  File "/code/compose/cli/main.py", line 170, in perform_command
  File "/code/compose/cli/main.py", line 588, in up
  File "/code/compose/cli/main.py", line 658, in attach_to_logs
  File "/code/compose/cli/log_printer.py", line 27, in run
  File "/code/compose/cli/multiplexer.py", line 35, in loop
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 0: unexpected end of data
docker-compose returned -1
```

**Comment by mnp** [comment]
We are still seeing this on one guy's OSX:

- Docker 1.10.3
- python 3.5.1
- pip 7.1.2
- osx 10.10.4
- docker-machine 0.6.0
- docker-compose 1.6.2
- VirtualBox -5.0.16

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
docker-compose returned -1
```

**Comment by wicope** [comment]
Hi mnp. Try update docker and docker-compose.

```
$ docker --version
Docker version 1.11.0, build 4dc5990
```
```
$ docker-compose --version
docker-compose version 1.7.0, build 0d7bf73
```

Regards

**Comment by mnp** [comment]
I think that resolved it, thanks.  Also, this guy had a several extra brew-managed  Python versions floating around, including 3.5  Backing out to a single 2.7 also helped.
