### ISSUE TITLE
Environment variables in env_file: parameter not recognized in dockerfile

### ISSUE THREAD

**Issue by hyperfocus1337** [docker/compose#2256]
Wrote my question/bug here on SO: http://stackoverflow.com/questions/33350985/docker-compose-environment-variables-specified-with-env-file-parameter-not-worki

Is it okay to post SO links here or should I move the question?

**Comment by dnephin** [comment]
I've responded to the SO question. 


> Environment variables are not available to the build step.  See [this proposal](https://github.com/docker/compose/issues/2163) for making that more obvious in compose and [this feature request](https://github.com/docker/compose/issues/2111) to support the new build args added to docker 1.9.

> The build args will do what you need.

**Comment by hyperfocus1337** [comment]
But if the env_file parameter is not for the build, how and where is it useful?

**Comment by dnephin** [comment]
It's used when running containers. It's the equivalent of `--env-file` parameter to run: http://docs.docker.com/reference/commandline/run/
