### ISSUE TITLE
Unicode error in volume paths

### ISSUE THREAD

**Issue by dnephin** [docker/compose#2259]
Reported here: https://github.com/docker/compose/issues/2234#issuecomment-151007248

**Comment by kuailedubage** [comment]
So sorry to reply so late due to the time zone problem:-).It occurs `UnicodeEncodeError` if the `host_path` of volume contains non-ascii characters.But it works OK when I replace "{}:{}" with u"{}:{}" in line 508 of config.py.

**Comment by mnowster** [comment]
@kuailedubage ah no worries, thank you for reporting it :) I've submitted a fix in #2264
