### ISSUE TITLE
docker-compose at pypi is missing some information

### ISSUE THREAD

**Issue by michael-k** [docker/compose#2270]
When looking at https://pypi.python.org/pypi/docker-compose, I'm missing at least the following information:

- link to the github repo
- list of supported python versions

**Comment by mnowster** [comment]
Supported python versions have already been recently added https://github.com/docker/compose/pull/2257

There is already a link to github about contributing to Compose, I've added an extra bullet point in installation and documentation to help make that more visible.

**Comment by michael-k** [comment]
> Supported python versions have already been recently added #2257

:+1:

> There is already a link to github about contributing to Compose, I've added an extra bullet point in installation and documentation to help make that more visible.

The readme is kinda unreadable on pypi, so I'd prefer a link to the github (repo, issues, or similar) in the buttom section (like the supported languages.

But I regard it as good enough, because the links exist.

**Comment by dnephin** [comment]
I'm working on fixing the readme on pypi. I just did a release and converted the README to rst , so it looks better now: https://pypi.python.org/pypi/docker-compose/1.5.0rc2

I'm working on automating that process so it won't break on the next release

**Comment by michael-k** [comment]
Wow, great work @dnephin! :+1:

Btw. the `classifiers` section of `setup.py` is still missing in the bottom section of the pypi page.

**Comment by mnowster** [comment]
@michael-k I think the extra classifiers were merged after @dnephin had done the release candidate so they should show up on pypi page when we do the next release. 

Thanks for letting us know that page needed some attention :+1:
