### ISSUE TITLE
Proposal: docker-compose down (opposite of up)

### ISSUE THREAD

**Issue by justinabrahms** [docker/compose#2277]
I ran `docker-compose up` to start my instance. It'd be nice (and a consistent API) if I could also use `docker-compose down` to turn it off. It could even be a silent alias for the relevant command.

**Comment by dnephin** [comment]
We've already got a PR open for this (#1390), but it needs more work.  I can't find an associated ticket for it, so keeping this open.

**Comment by dnephin** [comment]
from https://github.com/docker/compose/pull/1390#issuecomment-151982760

> I've been thinking about `stop` vs `down`, and I think `down` and `stop` are actually different. 

What we have right now is `stop`. It just stops containers.

The opposite of `up` would also need to remove containers, which sounds a lot like #1874 (#1875).

**Comment by dnephin** [comment]
`up` may create the following resources:
* images
* containers
* volumes (currently only as a side-effect of containers, but soon named volumes as well)
* a network

`down` should cleanup all of these, but maybe not all of them by default. Some only when a flag is added.

By default it should:
* stop containers
* remove containers
* remove the network

With a `-v` flag, also remove volumes with a prompt for confirmation. With `-f` don't prompt.
With a `--rmi` flag also remove images.

**Comment by aanm** [comment]
@dnephin What about `-a` for all?

**Comment by dnephin** [comment]
I think it's worth considering. I prefer to keep the number of permutations to a minimum, and it feels like `down --rmi -v` isn't overly verbose, so I'm not sure we gain a lot by adding `-a`.

**Comment by aanand** [comment]
Should `--rmi` result in the removal of images that would've been pulled from the Hub or a registry as a result of an `image` option? If so, there may be other containers running that are using those images (especially in the case of common things like `postgres`).

Should Compose continue if the Engine returns an error to that effect? I'm inclined to say it should.

**Comment by dnephin** [comment]
Ya, there are a lot of complicated scenarios with image removal, which is why I don't think it should remove them by default.  I'd like to avoid doing different things for services that have only `image` vs services that only `build`, vs services that have both `image` and `build` (since we'll be adding that with #2092).

> Should Compose continue if the Engine returns an error to that effect? I'm inclined to say it should.

Maybe `--rmi` should be `--rmi=strategy`, where `strategy` could be one of `best-effort` or `all`.  Using `best-effort` it will continue if something else is using the image, and using `all` it will fail in that case. I guess there could also be a `local` strategy that only removes images that used the default name (any service that doesn't have an `image` option).

**Comment by aanand** [comment]
Just having `--rmi=local` and `--rmi=all` might do the job.

Not sure `local` is the right name, but I'm not sure what would be better either. `--rmi=built`? `--rmi=safe`?

**Comment by dnephin** [comment]
Ya, something like that should cover the common case. Does `safe` imply only services without an `image` ? So if a service has both build and image, or just image, it won't be removed during `safe`.

**Comment by aanand** [comment]
Exactly, yes. `safe` is probably a bad term, though. I'm still not happy with any of the options. `untagged`?

**Comment by dnephin** [comment]
I like `untagged` better than our other options so far

**Comment by aanm** [comment]
There's a filter in docker to show images that are `untagged`, `docker images --filter=dangling=true`. So `dangling` would be ideal, no?

**Comment by dnephin** [comment]
We're talking about something different, so I think we want to use a different word. Although I see how `untagged` could be confused for dangling.

We'd like to refer to images with tags, but they are default tags created by compose, instead of user-defined tags from the `image` field.
