### ISSUE TITLE
1.5.0-rc2: Duplicate networks created when using Compose/Swarm/Networking 

### ISSUE THREAD

**Issue by dave-tucker** [docker/compose#2280]
Running through the same example in #2279 on Docker Swarm with `--x-network-driver overlay`
I have big problems after `up -d && stop && rm`

When I bring `up` my compose file again...
Instead of re-using the network (as happens in the single host use case), Compose creates a new network with the same name!

```
$ docker network ls
NETWORK ID          NAME                        DRIVER
bf7b620324cd        swl-demo0/bridge            bridge
c95de382559f        swl-demo0/none              null
6969ca97b168        swl-demo1/host              host
088077f4f115        counter                     overlay
1da7cb004cc3        swl-demo0/host              host
80b98c58f67d        swl-demo1/none              null
ad8432162868        swl-demo1/docker_gwbridge   bridge
1d63fedd167f        swl-demo1/bridge            bridge
2f0520ac885e        counter                     overlay
f8702a176805        swl-demo0/docker_gwbridge   bridge
```

I cannot do this manually with Swarm on the CLI as I get an error

```
$ docker network create -d overlay counter
Error response from daemon: 500 Internal Server Error: network with name counter already exists
```

Not sure if this is a Swarm issue, or a Compose one... but hoping we can figure it out soon!

/cc @dnephin @aanand @vieux @mavenugo

**Comment by dnephin** [comment]
I'm pretty sure this is a bug in either swarm or engine. Compose is just the client, the constraint of one-network-per-name needs to be enforced by the server.

I'll take a look at this tomorrow.

**Comment by dnephin** [comment]
500 also seems like the wrong error to be raising when the network already exists. I think it should be either a 409 Conflict or possibly a 202 Accepted (if the driver is the same)

**Comment by dave-tucker** [comment]
@dnephin had a chat with the libnetwork team and a suggested workaround was for Compose to use the [CheckDuplicates flag](https://github.com/docker/docker/blob/34439f3ecb5cbde2f733e162179dfbe57dbaabff/api/types/types.go#L337) in the create request. 

I think the longer term fix would be for Swarm to ensure that all network names are unique. AFAIK, libnetwork assumes that it was the responsibility of the orchestration system to ensure uniqueness of names.

**Comment by dnephin** [comment]
We're already checking if the network exists before creating it, so I think swarm must be failing to return the network?  I can do some more tests.

**Comment by dnephin** [comment]
This is being tracked on the swarm side in https://github.com/docker/swarm/issues/1356
