### ISSUE TITLE
Link to install on Docker is broken

### ISSUE THREAD

**Issue by sebglon** [docker/compose#2281]
If i run Curl command that i found on https://docs.docker.com/compose/install/

I have this error: /usr/local/bin/docker-compose: ligne 1: {error:Not Found} : commande introuvable

the URL on CURL command have "VERSION_NUM' but not real version number like 1.4.2

**Comment by dnephin** [comment]
The steps are:

 3 Go to the [repository release page](https://github.com/docker/compose/releases).

 4 Enter the curl command in your terminal.

The curl on that page is just an example, the real URL is on the release page
