### ISSUE TITLE
Runtime Error Using Docker Compse on Windows

### ISSUE THREAD

**Issue by divyakumarjain** [docker/compose#2296]
When using RC version of Docker Compose on Windows i am getting following error 

![2015-10-30_23-39-47](https://cloud.githubusercontent.com/assets/2039134/10854083/97244e4e-7f5f-11e5-8a3e-58a7c877bb4f.jpg)

docker-compose.exe version output

```
docker-compose version: 1.5.0rc1
docker-py version: 1.5.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014

```

**Comment by dnephin** [comment]
I'm pretty sure we fixed this in rc2. Please give it a try: https://github.com/docker/compose/releases/tag/1.5.0rc2

**Comment by dnephin** [comment]
#2216 was the previous ticket
