### ISSUE TITLE
docker-compose logs shuts down if 1 container is shut down

### ISSUE THREAD

**Issue by jberkus** [docker/compose#2297]
josh@test:~$ docker-compose --version
docker-compose version: 1.4.2
josh@test:~$ docker --version
Docker version 1.8.2, build 0a8c2e3

Steps to reproduce:

1. start a docker-compose up -d which runs 3 containers
2. tail the logs using docker-compose logs
3. in another terminal, use docker stop to shut down one of the containers
4. docker-compose logs will exit, even though 2 containers are still running

A minor annoyance, to be sure, but worth fixing when someone gets around to it.

**Comment by jberkus** [comment]
Note that docker-compose logs can be restarted after that

**Comment by dnephin** [comment]
This is fixed in 1.5.0 by #1754, just tested it out with rc2.

There will be further improvements to logs coming in the next release with #2227
