### ISSUE TITLE
simple names in /etc/hosts when using the experimental networking feature

### ISSUE THREAD

**Issue by brianbolt** [docker/compose#2312]
When using the `--x-networking` feature in docker-compose 1.5 (docker-engine 1.9), is it possible to get a "simple name" added to /etc/hosts without knowing the container name beforehand and without using the `container_name` directive?

For example, the following compose file in a directory called dockercompose might produce the /etc/hosts entries below:

```
web:
  image: firstapp
web2:
  image: secondapp
```

/etc/hosts entries in the auto generated "dockercompose_web_1" container looks like:
```
172.18.0.2	dockercompose_web2_1
172.18.0.2	dockercompose_web2_1.dockercompose
```

I was hoping I would see the following entry as well:
```
172.18.0.2	web2
```

Let's say the image `firstapp` is hardcoded to communicate with a host named `web2` and `secondapp` is harcoded to communicate with a host named `web`. Is it possible to get this circular communication working and maintain the ability to startup multiple instances of the overall app?

**Comment by dnephin** [comment]
Nope, the docker/libnetworking support isn't in yet to provided aliases. As soon as it is, we'll be adding support to compose. The only way to do it right now is with the `container_name`.

**Comment by brianbolt** [comment]
Is there an issue for docker/libnetworking that I should subscribe to to track this?

**Comment by dnephin** [comment]
I just created https://github.com/docker/libnetwork/issues/737

**Comment by brianbolt** [comment]
Follow up question.  Using the 1.5.0 release, how is one supposed to use the experiment networking feature without alias'?  I have config files for my webapp that tell it that the hostname of the database is "db".  I can use the container_name feature but that breaks that ability to startup multiple instances.  I just don't get how people are using this feature. Are there any examples in the documentation that could help me? I haven't been able to find any.

**Comment by dnephin** [comment]
There is one example in #2294, where you can set the project name using `COMPOSE_PROJECT_NAME` and pass it as an environment variable to the containers.

**Comment by dnephin** [comment]
As part of this, we might want to consider adding aliases that use dashes (or some other character) as well as underscores for each container. That way we could transition away from underscores in hostnames (which is technically invalid).

**Comment by dnephin** [comment]
This is now done in 1.6.0 (RC1 is out)
