### ISSUE TITLE
Add an argument to specify docker-compose using URL

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#2313]
Currently `docker-compose` only takes `docker-compose.yml` that has to be on the local file system. Just like `docker build`, it'll be good to provide a context for `docker-compose up -d`. This will allow to run an application from a github project.

**Comment by dnephin** [comment]
I like this idea, I proposed the same thing here: https://github.com/docker/compose/issues/1818#issuecomment-128416833

There are still things to work out though. Should the file that is downloaded be saved locally?

**Comment by arun-gupta** [comment]
@dnephin The file can be cached, and downloaded again based upon timestamp.

**Comment by astewart-twist** [comment]
This is a great idea, and feels like a very natural way to deploy.

**Comment by zysimplelife** [comment]
I would like to say I am facing same problem.  If docker-compose support external URL I can release internal tools by only one command rather than a complex config

**Comment by astewart-twist** [comment]
I think a nice model for github url based docker-compose deployments could that used by next flow (http://www.nextflow.io/blog/2014/share-nextflow-pipelines-with-github.html).

**Comment by summergirl21** [comment]
It seems like this could be very useful for deploying docker-compose apps. I'm interested in implementing this. Adding an option for `docker-compose up --url <url>`, that would cache the yml file at the provided url and run the application. Would this be useful? Are there any specific design concerns related to this?

**Comment by summergirl21** [comment]
After looking at implementation of yml parsing, it seems like this would be better as an option on docker-compose itself. `docker-compose --url <url> [COMMAND]`. Would this make sense and be a reasonable solution?

**Comment by shin-** [comment]
I don't think this will make it into Compose for the reasons I outlined in #5441, but you should take a look at [app packages](https://github.com/docker/app) which should answer most of the use cases mentioned in this thread.

**Comment by docktermj** [comment]
This would be very useful.   I'm trying to make demonstrations using `docker-compose` for folks that don't have the savvy to do `git clone` to clone a repository to get the `docker-compose.yaml` file.

**Comment by psychemedia** [comment]
I thin this would be really useful: one advantage of `docker run` is that you don't need to share any files, just the run command.

`docker app` doesn't seem to have received any attention in recent months, and from the README looks like it requires its own laboured install.

My use case is trying to share teaching environments to students via containers. Every download, every extra step causes a chance of failing to engage that student.

(Given docker's recent re-emphasis on "the developer", for "developer" read "not very confident newly qualified developer who has never used docker before".)

**Comment by GD-HCK** [comment]
I tried to work out a way to achieve this today and then soon realised it was on a roadmap but not yet finalised.

Would be very useful to pull info from github rather than cloning a repository as many have said.

Cheers.
