### ISSUE TITLE
Add cli option to turn on only specific container

### ISSUE THREAD

**Issue by dieend** [docker/compose#2315]
In my local docker-compose configuration, I have 4 container that need to be run. But sometime I don't need all of them. For example when I am using staging database configuration and I don't want mysql container going up. Or when we are migrating and there are two mysql database and I want to select only one of them turned on.

It would be awesome if this feature implemented.

**Comment by dnephin** [comment]
You can do this with `docker-compose up <service name 1> <service name 2>`

**Comment by dieend** [comment]
I never knew it could be done that way. Thanks!

**Comment by dieend** [comment]
@dnephin is it possible to not turn on other linked container? I just realized the container actually still turned on, it's just the logs that being silenced.

**Comment by dnephin** [comment]
`up --no-deps` will prevent starting dependencies
