### ISSUE TITLE
hostname and domainname ignored when using the host=net option

### ISSUE THREAD

**Issue by vipconsult** [docker/compose#2318]
When I am deploying a machine I don't care about the host's hostname and domainname , but inside the containers I need to set custom values.

the problem is that for any service with the host=net option configured it ignores any values for the hostname and domainname in the yaml file istelf.

**Comment by dnephin** [comment]
This is documented here: http://docs.docker.com/engine/reference/run/#network-settings

These options are incompatible. If you use `net=host`, then you're using the hosts network, so you can't set a custom hostname.
