### ISSUE TITLE
docker-compose shell

### ISSUE THREAD

**Issue by peter-leonov** [docker/compose#2320]
Would be nice to get a replacement for `capistrano shell` with `docker-compose shell`.

Use cases:
1. check if a host is reachable from all the boxes: `docker-compose shell frontend ping -c 1 8.8.8.8`
2. calculate a size of distributed cache: `docker-compose shell nginx sudo du -sh /var/cache/nginx/`
3. emergency kill all the unicorns `docker-compose shell app pkill ruby`

As far as all the containers started with `docker-compose up foo` should have the same binaries no conflicts would happen in terms of commands.

**Comment by dnephin** [comment]
This sounds similar to `docker-compose run`, except it runs a command on all the containers, is that right?

Which might be the same request as `docker-compose exec` #593

**Comment by peter-leonov** [comment]
Mostly the same now as the ticket you mentioned has evolved a lot in the last year.
Here I want all-in-wonder from the very start of a discussion:
* `docker-compose exec container_class command`
* interactive REPL shell like `capistrano shell`
* and a multiplexed stdin so one could run `echo backup | docker-compose shell at midnight`.

Do I ask for too much? ;)

**Comment by dnephin** [comment]
yes, I think this overlaps with #593

**Comment by dnephin** [comment]
Closing since we've merged `exec` support
