### ISSUE TITLE
Volumes on windows

### ISSUE THREAD

**Issue by MartinsThiago** [docker/compose#2328]
What do you think about checking if we're running on windows system? and if so... automatically config virtual box for sharing folder

I don't know python very well, but I am forking this project for trying to implement this feature... at least for me would be really really useful

**Comment by dnephin** [comment]
@MartinsThiago That is the responsibility of http://docs.docker.com/machine/

If you're on windows, I would recommend checking out https://www.docker.com/docker-toolbox, which includes compose and machine

**Comment by MartinsThiago** [comment]
If I am on windows, then I start up some containers with `docker-compose up`... how would I map my local folder (aka `C:/folder` -> `/my/folder/on/linux`) ?

By manually opening Virtual Box configurations? Too painful

**Comment by dnephin** [comment]
@MartinsThiago compose is not aware of virtualbox and it shouldn't be.

Have you looked into the projects I linked (machine and toolbox) ?

docker-machine already does this for you when you create a new VM.

**Comment by MartinsThiago** [comment]
Yup, I thought little better about this... but on Windows (...dont know about Mac)

There's no easy way to control shared folders... since boot2docker, the maximum we can do is to share folders under C:/users... and only

It´s affecting usability... also... why to put all these nice tools on a toolbox for Windows/Mac if we the usage between them is not the same?

I really agree that these tools are supposed *only* to talk to daemon itself... Maybe creating some version of docker-compose only for windows could be the way to go?

**Comment by Michstumpf** [comment]
+1

**Comment by rvmatos** [comment]
I need this too

+2

;)

**Comment by dnephin** [comment]
If you need this feature, please look at using http://docs.docker.com/machine/

**Comment by MartinsThiago** [comment]
Opening issue on `docker-machine`

https://github.com/docker/machine/issues/2188
