### ISSUE TITLE
Django project does not work when I try to put it into a Docker-Compose container

### ISSUE THREAD

**Issue by Valten1992** [docker/compose#2340]
I am attempting to setup a Django project I made in eclipse in Docker-Compose for deployment purposes.

I copied my project into a directory just for Docker and followed a variety of tutorials online and from my understanding, the only services my App requires in Docker are Django and Postgres. Here is my docker-compose.yml file:

```
db:
  image: postgres:latest
  ports:
    - "5432"
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
web:
  build: .
  ports:
   - "8000:8000"
  volumes:
   - .:/code
  links:
   - db
  command: python3 manage.py runserver 0.0.0.0:8000
```
and my DockerFile:

```
FROM python:3

#ENV LANG C.UTF-8
#RUN export LC_ALL="en_US.UTF-8"

RUN mkdir /code

WORKDIR /code

#Add requirements.txt to code
ADD requirements.txt /code/

RUN pip install -r requirements.txt

ADD . /code/
```

I have tested the python command locally in my virtualenv and the server starts, however, when I run 'docker-compose up' in the folder the application is located in, I get this output:

```
Creating hpr_db_1
Creating hpr_web_1
Attaching to hpr_db_1, hpr_web_1
db_1  | The files belonging to this database system will be owned by user "postgres".
db_1  | This user must also own the server process.
db_1  | 
db_1  | The database cluster will be initialized with locale "en_US.utf8".
db_1  | The default database encoding has accordingly been set to "UTF8".
db_1  | The default text search configuration will be set to "english".
db_1  | 
db_1  | Data page checksums are disabled.
db_1  | 
db_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1  | creating subdirectories ... ok
db_1  | selecting default max_connections ... 100
db_1  | selecting default shared_buffers ... 128MB
db_1  | selecting dynamic shared memory implementation ... posix
db_1  | creating configuration files ... ok
db_1  | creating template1 database in /var/lib/postgresql/data/base/1 ... ok
db_1  | initializing pg_authid ... ok
db_1  | initializing dependencies ... ok
web_1 | /usr/local/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
web_1 |   return f(*args, **kwds)
web_1 | 
db_1  | creating system views ... ok
db_1  | loading system objects' descriptions ... ok
db_1  | creating collations ... ok
db_1  | creating conversions ... ok
db_1  | creating dictionaries ... ok
db_1  | setting privileges on built-in objects ... ok
db_1  | creating information schema ... ok
db_1  | loading PL/pgSQL server-side language ... ok
web_1 | /usr/local/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
web_1 |   return f(*args, **kwds)
web_1 | 
db_1  | vacuuming database template1 ... ok
db_1  | copying template1 to template0 ... ok
db_1  | copying template1 to postgres ... ok
db_1  | syncing data to disk ... ok
db_1  | 
db_1  | Success. You can now start the database server using:
db_1  | 
db_1  |     postgres -D /var/lib/postgresql/data
db_1  | or
db_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1  | 
db_1  | 
db_1  | WARNING: enabling "trust" authentication for local connections
db_1  | You can change this by editing pg_hba.conf or using the option -A, or
db_1  | --auth-local and --auth-host, the next time you run initdb.
db_1  | waiting for server to start....LOG:  database system was shut down at 2015-11-06 15:18:39 UTC
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  autovacuum launcher started
db_1  | LOG:  database system is ready to accept connections
db_1  |  done
db_1  | server started
db_1  | ALTER ROLE
db_1  | 
db_1  | 
db_1  | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1  | 
db_1  | LOG:  received fast shutdown request
db_1  | LOG:  aborting any active transactions
db_1  | LOG:  autovacuum launcher shutting down
db_1  | waiting for server to shut down....LOG:  shutting down
db_1  | LOG:  database system is shut down
db_1  |  done
db_1  | server stopped
db_1  | 
db_1  | PostgreSQL init process complete; ready for start up.
db_1  | 
db_1  | LOG:  database system was shut down at 2015-11-06 15:18:41 UTC
db_1  | LOG:  MultiXact member wraparound protections are now enabled
db_1  | LOG:  database system is ready to accept connections
db_1  | LOG:  autovacuum launcher started
```
No message about the server starting or anything like that, I thunk its compiling my code due to the warning messages about deprecation I get when I run the application locally but I am quite stumped here. Can anyone see my error?

Upon closer inspection and changing the port for the Django server, I find that accessing the webpage returns a "Connection to the Server was reset while the page was loading" error. This indicates that something is being set up on that page. But I still cannot access it. I know Docker-Compose is working as simple Django applications from tutorials work just fine.

**Comment by dnephin** [comment]
It's possible that some of the logs aren't being flushed. We have a fix for that coming in 1.5.1. For now you can try running `docker logs hpr_web_1` to see if there extra lines missing from that output.

**Comment by Valten1992** [comment]
Thanks for the prompt reply dnephin. I just ran that command and the only logs returned for web_1 were the ones only listed above. Very odd. In the morning, I shall try downgrading to a previous version to see if the problem still occurs.

**Comment by Valten1992** [comment]
Downgrading did not work so I assume its a problem with how I am doing it. I realised that even though I have started the Django server, I did not run the migrate command to properly setup the database. Could this be the issue?

Following this train of thought I actually found this stack-overflow question http://stackoverflow.com/questions/33309121/using-docker-compose-to-create-tables-in-postgresql-database, that dnephin posted in. I followed your answer in the thread as I want to import an SQL file into my database anyway, but I am having the same problem the OP is having that he mentions in the comments:

    No PostgreSQL clusters exist; see "man pg_createcluster" ... (warning).
    psql: could not connect to server: No such file or directory
	    Is the server running locally and accepting
	    connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

I have been stumped on this point for 3 hours now. I have tried adding a sleep command to the setup file but that does not work, tried setting locale like some other posts on the net suggest but no dice there either.

**Comment by jayfk** [comment]
You can't talk to the postgres socket this way, because the official postgres image isn't configured to listen there. You have to use the psqls `-h` flag from another container to access the database. 

You basically run your stack with `docker-compose up` and then launch another container with `docker-compose run postgres psql -h postges` and then paste your sql file there.

We have a working docker-compose configuration with a lot of goodies for dev (and experimental prod) at  [cookiecutter-django](https://github.com/pydanny/cookiecutter-django). If you want to try it out, make sure to use `dev.yml` for development. You do that by running your commands with `docker-compose -f dev.yml up`, or you set the environment variable to point to it by running `export COMPOSE_FILE=dev.yml` once.

**Comment by dnephin** [comment]
Sounds like this question was answered.

Thanks for sorting it out!
