### ISSUE TITLE
Order of containers starting up?

### ISSUE THREAD

**Issue by prologic** [docker/compose#235]
Does fig starts containers in the order as
written in the ``fig.yml``? If not is it meant to?

I've run into an issue where I need one or two
containers to start before others.

Related but different Issue: https://github.com/orchardup/fig/pull/74

**Comment by vgoldin** [comment]
+1 for explicit dependencies not related to any docker specifics. In addition, startup waiting time would be very much appreciated among with dependencies.

**Comment by cboettig** [comment]
Adding an extraneous `volumes_from` seems enough to workaround the `net container:name` issue, but a proper fix would be great.

**Comment by dnephin** [comment]
This would be addressed by #686

**Comment by aanand** [comment]
@mbdas If I have it right, you're asking for a different kind of dependency ordering.

`links` and `volumes_from` express dependencies between long-running containers that determine the order in which each is created and started. Whatever happens once they're running is irrelevant.

You're asking for the ability to express dependencies between long-running and ephemeral containers, where an ephemeral container needs to be created, started *and finish running* before a long-running container is created.

Is that right?

**Comment by mbdas** [comment]
Both actually. So, you got it right on the ephemeral containers which is a common patter for data volume update containers for example. So, looking for generic on-exit keyword where a target container can start on successful exit of a list of containers.

The second use case is a dependency between long running containers where the target container starts on successful health check condition (user supplied say with basic defaults) of the other long running containers. Link does not help in ensuring health checks and workarounds are not clean.

**Comment by aanand** [comment]
My reluctance regarding the second use case boils down to: I don't think health checks should be Compose's job. In a robust distributed system, the services *themselves* are responsible for checking their dependencies, retrying, backing off etc.

You wouldn't deploy a web app to production that refused to start if the database wasn't ready yet, and since half of the point of Compose is to close (or narrow) the gap between development and production, I don't think it's good to add complexity for the sake of enabling bad practices.

I'd prefer if Compose did *no* ordering at all, but the way Docker is set up (container config being immutable) it's unfortunately necessary to force an ordering just so we can actually create the containers.

**Comment by defunctzombie** [comment]
There is a difference between deploying and using something in dev. One
might have to preconfigured dbs or other tasks and it is just easier to do
that if you can put in a simple delay or ordering. I don't use something
like compose for deployment but I do use it in dev where workflows are
sometimes different for simplicity.

**Comment by aanand** [comment]
Fair enough, but we're planning to take Compose beyond just development environments - see the [roadmap](https://github.com/docker/compose/blob/master/ROADMAP.md).

Can you show me a use case where putting the logic in the container is significantly more hassle than getting Compose to do it?

**Comment by defunctzombie** [comment]
Most of that roadmap is dev oriented which is awesome. Helping people dev
micro services is already good enough.

I'll think about it more, maybe will just write scripts to wait as you say.

My feedback: keeping compose dev oriented seems great to me. Vagrant had
this idea that you could do dev and then turn that into production. This is
not so simple and ends up being useless for any real production setup so
people just use vagrant for dev and testing and that is perfectly alright.

**Comment by roytruelove** [comment]
+1

Check out this quote from the ['mysql' repo](https://registry.hub.docker.com/_/mysql/):
> If there is no database initialized when the container starts, then a default database will be created. While this is the expected behavior, this means that it will not accept incoming connections until such initialization completes. This may cause issues when using automation tools, such as docker-compose, which start several containers simultaneously.

This is a showstopper for me for docker-compose, unf

**Comment by dnephin** [comment]
I regularly use docker-compose with mysql, but I don't use that image. You probably want to extend that image, and create your database and tables as part of the "build" step. That way the work is cached, and you don't have to repeat it every time you start up your container.

Any other container using the mysql image just needs to retry until the container is available. It needs to do that to be resilient to network failures anyway.

https://github.com/dnephin/readthedocs.org/blob/docker_compose/dockerfiles/database/Dockerfile is an approximate example of that setup using postgresql, it should be similar for mysql.

**Comment by gtmtech** [comment]
+1 for depends_on.

**Comment by rafaeltuelho** [comment]
When possible I'm using some kind of 'test/retry connection test' with the service I depend on. To workaround this limitation (service startup ordering/dependency), in my container's service startup script (eg: run.sh) I use this snippet of code to wait for: https://gist.github.com/rafaeltuelho/aff24eefe8c6e48a6b49

**Comment by MikeMichel** [comment]
is the startorder with "links" just an order or is compose really checking if the linked container (db) is in status "running" and only then starts the other one (web)?

something like

```
dependencies:
    - db
    - redis
```
would be nice

as a user of marathon i like how dependencies was solved https://mesosphere.github.io/marathon/docs/deployments.html 
in combination with health checks https://mesosphere.github.io/marathon/docs/health-checks.html this makes sure db is "really" ready before web starts.

**Comment by dnephin** [comment]
There's a bunch of interesting discussion in this ticket, but it's unfortunately not terribly related to the original question.

Service ordering is currently based on links and volumes_from because that's a hard requirement for docker, but I don't think "order" fully describes the concern. The concern is more about availability, which is covered by #374.

I'm going to close this ticket, as I think it overlaps with  #374.
There is also #686 for discussion about `depends_on`

If you feel there are issues unrelated to those ticket, please feel free to open a new issue.
