### ISSUE TITLE
Substitute variables from env_file in configuration file

### ISSUE THREAD

**Issue by djmaze** [docker/compose#2352]
The new environment variable substitution is really handy. But as using a `.env` file is a common pattern for many projects, it should be possible to use `env_file` in combination with `$VARIABLE` substitution in the docker-compose.yml. 

Often this is much more useful then just using variables from the current shell environment. This way, local configuration and credentials can stay out of version control (e.g. container hostnames, ports or database passwords).

**Comment by glenngillen** [comment]
I've been taking this approach with either a bash alias, [forego](https://github.com/ddollar/forego), [foreman](https://github.com/ddollar/foreman), or [shoreman](https://github.com/chrismytton/shoreman) as a process wrapper for `docker-compose`.

I'm aware all of these are addressing the symptoms though. Would be great if `docker-compose` could itself read in and export the values for the current command.

FWIW my shell alias is just:
```bash
alias hkenv='export $(cat .env)'
```

**Comment by dnephin** [comment]
I don't think we want to re-use `env_file`, that would be overloading the concept. However there is a related proposal in #2636 to use a different file.  I'm going to close this issue for that one, I believe they are requesting the same feature.
