### ISSUE TITLE
Inconsistency in how compose handles empty environment variables

### ISSUE THREAD

**Issue by pirelenito** [docker/compose#2359]
If you want to use the value of an environment variable that is available in the host you can:

```bash
$ HOST_ENV=value docker run -e HOST_ENV ubuntu:14.04 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=acb280b6edd9
HOST_ENV=value
HOME=/root
```

But, if the variable is not defined in the host, then it also doesn't get created in the container:

```bash
$ docker run -e HOST_ENV ubuntu:14.04 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=29a464f43ecb
HOME=/root
```

But, given the following `docker-compose.yml`:

```yaml
banana:
  image: ubuntu:14.04
  command: env
  environment:
    HOST_ENV:
```

We get an empty variable:

```bash
$ docker-compose run banana
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=9841adaf229b
TERM=xterm
HOST_ENV=
HOME=/root
```

Should this be considered a bug? I would expect the same behavior from both tools.

**Comment by nathanleclaire** [comment]
It says in https://docs.docker.com/compose/compose-file/#environment that populating it from host is the expected behavior (and it's been that way as long as I can remember).

However, I can't reproduce @pirelenito behavior.

```console
$ docker-compose --version
docker-compose version: 1.5.0
$ cat docker-compose.yml
foo:
  image: busybox
  command: env
  environment:
    FOO:
$ export FOO=BAR
$ docker-compose run foo
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=76daaf22db8d
TERM=xterm
FOO=BAR
HOME=/root
$ FOO=QUUX docker-compose run foo
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=d7dd703c5ed2
TERM=xterm
FOO=QUUX
HOME=/root
```

@pirelenito Are you 100% positive you're setting the environment variable correctly?

**Comment by pirelenito** [comment]
Hi @nathanleclaire, thanks for the reply.

I think you misunderstood the problem. What I am describing is that when you **don't have the variable set in your environment** it shouldn't even be defined inside the container.

So, given the your docker-compose.yml file:

```yaml
foo:
  image: busybox
  command: env
  environment:
    FOO:
```

If `FOO` is not defined, it shouldn't be defined as well in the container, but it is:

```
$ docker-compose run foo
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=34dd899cc8d3
TERM=xterm
FOO=
HOME=/root
```

You can see that using the `docker` cli the behavior is different:

```bash
$ docker run -e FOO busybox env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=4b1196b7a82f
HOME=/root
```

**Comment by nathanleclaire** [comment]
Ah OK, I misunderstood.  Thanks for clarifying.

**Comment by jrabbit** [comment]
This is pretty frustrating with a common django/python idiom of `os.getenv('VARIABLE', defaultvalue)` which will return '' with an empty variable set which is not the expected behavior

**Comment by dnephin** [comment]
`os.getenv('VARIABLE') or defaultvalue` is always safer, but yes, a patch to have the behaviour match the behaviour of docker would be great.

**Comment by jrabbit** [comment]
https://github.com/jrabbit/compose/commit/6540efb3d380e7ae50dd94493a43382f31e1e004 Here's what I'm starting with, off to fix the tests next
