### ISSUE TITLE
[Feature Request] docker-compose ps should show swarm node name

### ISSUE THREAD

**Issue by nathanleclaire** [docker/compose#2366]
`docker ps` returning from Swarm shows the name of the node in the "NAMES" column as part of the container name. It's really nice to quickly see where your containers have been scheduled.  It would be really great to see the node names in `docker-compose ps` output as well.

**Comment by dnephin** [comment]
Thanks for the feature request.  We've had a bunch of different requests for ps, so I'm going to aggregate them all into #2369 so it'll be easier to design a solution that works for most of them.
