### ISSUE TITLE
Issues communicating with swarm

### ISSUE THREAD

**Issue by Farjad** [docker/compose#2374]
Hi,

So I am running Docker 1.9, swarm (swarm:latest), docker-compose 1.5

I am able to create networks/run containers without docker-compose.

As soon as I try to do it using docker-compose I get issues:

no networking enabled:

```
compose.service.create_container: Creating test_web_1
compose.cli.verbose_proxy.proxy_callable: docker create_container <- (name=u'test_web_1', image='centos', labels={u'com.docker.compose.service': u'web', u'com.docker.compose.project': u'test', 'com.docker.compose.config-hash': '3b7b598f89eef07df2019f3efc89eed7057e5b708c3d921e49cdcfe59a2fd232', 'com.docker.compose.version': u'1.5.0', u'com.docker.compose.oneoff': u'False', 'com.docker.compose.container-number': '1'}, host_config={'NetworkMode': 'default', 'Links': [], 'PortBindings': {'5000/tcp': [{'HostPort': '80', 'HostIp': ''}]}, 'Binds': [], 'ExtraHosts': [], 'LogConfig': {'Type': u'', 'Config': {}}, 'VolumesFrom': []}, environment={u'MONGO_HOST': u'counter_mongo_1'}, detach=True, ports=['5000'])
ERROR: compose.cli.main.main: 404 page not found
```

with networking:

```
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- (u'test')
compose.project.ensure_network_exists: Creating network "test" with driver "overlay"
compose.cli.verbose_proxy.proxy_callable: docker create_network <- (u'test', driver='overlay')
ERROR: compose.cli.main.main: No such network: create
```

However, if I point the docker client/compose to local docker instead of swarm docker-compose works. When I point it to swarm, docker client works, compose does not.

Any help would be appreciated.

**Comment by dnephin** [comment]
Please include the contents of your `docker-compose.yml`, and if possible the relevant logs from the swarm slave.

**Comment by Farjad** [comment]
It's a pretty simple docker-compose as I wanted to test if my set up is working:

```
web:
  image: tutum/apache-php
  ports
    - 5555:80
mongo:
  image: mongo
```

If i do the same thing:

docker network create swarm overlay
docker run -d --net=swarm -p 5555:80 --name=web tutum/apache-php
docker run -d --net=swarm --name=mongo mongo

it works. 

Also I'm not sure what logs you are looking for as the swarm slave only shows registering in its logs. Please let me know!

**Comment by Farjad** [comment]
So I seem to have run into more issues: I no longer can create an overlay network using docker client.

For some reason my docker client is hitting v1.15 API:

```
Nov 12 20:58:11 spv07vcs9.vail docker[5332]: time="2015-11-12T20:58:11.405463220-05:00" level=info msg="POST /v1.15/networks/create"
Nov 12 20:58:11 spv07vcs9.vail docker[5332]: time="2015-11-12T20:58:11.409962851-05:00" level=error msg="Handler for POST /v1.15/networks/create returned error: pool configuration failed because of Unexpected response code: 301 ()"
Nov 12 20:58:11 spv07vcs9.vail docker[5332]: time="2015-11-12T20:58:11.410002863-05:00" level=error msg="HTTP Error" err="pool configuration failed because of Unexpected response code: 301 ()" statusCode=500
Nov 12 20:58:11 spv07vcs9.vail docker[5332]: time="2015-11-12T20:58:11.410337886-05:00" level=info msg="GET /v1.15/networks"
Nov 12 20:58:11 spv07vcs9.vail docker[5332]: time="2015-11-12T20:58:11.423216390-05:00" level=info msg="GET /v1.15/networks"
```
```
[root@spv07vcs9 docker]# docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by Farjad** [comment]
So it seems like:

When using consul, I cannot create a network whether I use docker client or docker compose.

When using etcd, I can create a network using docker client, but I cannot do anything using docker compose (similar to consul).

**Comment by dnephin** [comment]
It's strange the API version is 1.15 , that is pretty old. Which version of swarm are you running?

**Comment by Farjad** [comment]
I am running swarm:latest from the dockerhub. Latest as of 3 days ago.

**Comment by pporada-gl** [comment]
I am affected by this.

Docker-compose version
```
docker-compose version 1.5.2, build 7240ff3
docker-py version: 1.5.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014
```

Docker version
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64
```

**Comment by lendico-seong** [comment]
Try to remove the trailing slash in the discovery URL e.g.:
```consul://10.0.0.1:8443``` not ```consul://10.0.0.1:8443/```

**Comment by ijc** [comment]
Issue grooming: I'm closing this as stale, please reraise if this is happening on modern versions of the stack.
