### ISSUE TITLE
`docker-compose` on Windows Server 2016 [TP4] requires `net: default` or `net: none`

### ISSUE THREAD

**Issue by powersplay** [docker/compose#2375]
`docker-compose up` gives `ERROR: invalid --net` and aborts on Windows Server 2016 Technical Preview 4 Build 10575 unless `net: default` or `net: none` is specified in `docker-compose.yml`

    PS C:\Users\Administrator\compose> ..\docker-compose-Windows-x86_64.exe up -d
    Recreating 7780fb51c7_7780fb51c7_7780fb51c7_7780fb51c7_compose_Wocker_1
    ERROR: invalid --net:

Inserting `net: default` or `net: none` in `docker-compose.yml` is required to avoid this error.

**Comment by dnephin** [comment]
I think this might actually be a bug in the windows Docker engine.  Since other API backends (docker on linux, and swarm) don't require this.

**Comment by powersplay** [comment]
I'm new at writing issues.   Do I just open it also in engine and then link over to here?

**Comment by dnephin** [comment]
Yup, I think that sounds appropriate. If you can cc @dnephin as well, I'll follow along in case they need anything from us

**Comment by dnephin** [comment]
Closing this, since it's an issue with the daemon, not compose.
