### ISSUE TITLE
rm -f not removing running containers on master

### ISSUE THREAD

**Issue by nathanleclaire** [docker/compose#2376]
Is it normal behavior?  I thought it would remove them anyway.  Using `--x-networking` FWIW.

![screen shot 2015-11-11 at 2 48 32 pm](https://cloud.githubusercontent.com/assets/1476820/11105408/76503264-8883-11e5-9923-ab73764bac23.png)

**Comment by villlem** [comment]
This is normal. But for development purposes it makes little sense.

**Comment by dnephin** [comment]
Yup, this is the expected behaviour.  Related issues: #1875, #2277

**Comment by nathanleclaire** [comment]
OK cool just checking in
