### ISSUE TITLE
docker-compose is not updating /etc/hosts in containers

### ISSUE THREAD

**Issue by igorspasic** [docker/compose#2382]
On docker 1.9.0c and compose 1.5.0.

I have linked containers. Docker compose DOES NOT update etc hosts. The very same configuration on 1.8.0 worked.

**Comment by dnephin** [comment]
Please include the output of a `docker inspect <container>` `docker exec -ti <container> cat /etc/hosts`, and the commands you ran with the output you're seeing.

**Comment by igorspasic** [comment]
Sorry, its because:
> network docs will be updated soon; updating /etc/hosts (service discovery) will not be done on the default "bridge" network, only with other networks 

When I use networking instead of linking, my hosts get updated.
