### ISSUE TITLE
support --memory-swappiness

### ISSUE THREAD

**Issue by devinrsmith** [docker/compose#2383]
Would be good to support `docker run` property --memory-swappiness https://docs.docker.com/engine/reference/run/#swappiness-constraint. Is there any way to give docker-compose a raw string to be passed to the given `docker run` command in the meantime?

**Comment by dnephin** [comment]
There is no `docker run` command. Compose uses the docker API to run a container, not the CLI.

**Comment by shin-** [comment]
Closing via #3542
