### ISSUE TITLE
Cannot do interactive debugging (without recreating the container)

### ISSUE THREAD

**Issue by CrimsonGlory** [docker/compose#2386]
Currently I can do interactive debugging with
```sh
docker-compose run --service-ports web
```
This is as described in issue #359 . But over time I end up with many containers, as run creates a new one each time.
I would like something like: 
```sh
docker-compose start --bind web
```
Something to start all the containers, but be able to do interactive debugging of a specific one.
I'm using [pry](https://github.com/pry/pry)

**Comment by dnephin** [comment]
You can use `docker-compose run --service-ports --rm` to remove the container once it exits.

**Comment by CrimsonGlory** [comment]
Thanks!

**Comment by qtheuret** [comment]
+1

**Comment by CrimsonGlory** [comment]
For those reaching this issue from google (docker compose + interactive debugging).
I'm currently debugging using ```stdin_open: true``` in ```docker-compose.yml``` and when the program reaches ```binding.pry``` or ```embed()``` or your favorite debugger, I do ```docker attach containername``` and get to the debugger.
