### ISSUE TITLE
Suggestion to use an env variable for -f file selection

### ISSUE THREAD

**Issue by vipconsult** [docker/compose#2395]
The current option -f is great but error prone when deploying in production.

how about using a environment variable - something like 

$DOCKER-COMPOSER-ENV=prod

if not set  use docker-compose.yml and  show a warning no env set so using only the main file .....
if set use docker-compose.yml and extend using a file  based on the env 
docker-compose-$DOCKER-COMPOSER-ENV.yml 

$DOCKER-COMPOSER-ENV=prod
will run:
docker-compose -f docker-compose.yml -f docker-compose-prod.yml

**Comment by dnephin** [comment]
You can use `$COMPOSE_FILE`, however it only supports one file right now. I think it might be good to allow for multiple files, maybe with a common separate list.

**Comment by schmunk42** [comment]
@dnephin, @vipconsult 

> You can use $COMPOSE_FILE, however it only supports one file right now. I think it might be good to allow for multiple files, maybe with a common separate list.

Is this already implemented or is there another issue to track?
I would have this as a feature request.

**Comment by vipconsult** [comment]
I have been thinking about this a lot
It gets boring with the additional typing for example just to get the logs
cd /path/to/project/
docker-compose -f first-server.yml logs

what if we have a config file 
$COMPOSE_FOLDER=/User/username/projects/compose
$COMPOSE_FILE=first-prod.yml 
$COMPOSE_DAEMON=1
$x-networking=1
$project-name=second

another config
$COMPOSE_FOLDER=/User/username/projects/compose
$COMPOSE_FILE=second-prod.yml 
$COMPOSE_DAEMON=1
$x-networking=1
$x-network-driver=overlay 


than we can use the docker-machine approach with envs

$(docker-compose  env project/dir/config)

then we can run from any directory

docker-compose logs  
is converted to 
docker-compose -f /User/username/projects/compose/serverOne/config.yml logs

a real life example to set 2 servers that work in sync with load balancing looks like

eval $(docker-machine env fm-first)
cd /Users/krasimir/projects/fm/compose/
docker-compose -f first-prod.yml build
docker-compose --x-networking --x-network-driver overlay -f first-prod.yml up -d
    
docker-compose -f first-always-on-prod.yml build
docker-compose --x-networking --x-network-driver overlay -f first-always-on-prod.yml   up -d

eval $(docker-machine env fm-second)
docker-compose -f second-prod.yml --project-name second build
docker-compose --x-networking --x-network-driver overlay -f second-prod.yml --project-name second  up -d

docker-compose -f second-always-on-prod.yml --project-name second build
docker-compose --x-networking --x-network-driver overlay -f second-always-on-prod.yml --project-name second  up -d


this becomes

eval $(docker-machine env fm-first)
eval $(cat /Users/krasimir/projects/fm/compose/first/configFirst)
docker-compose build
docker-compose up
docker-compose logs

eval $(cat /Users/krasimir/projects/fm/compose/first/configFirstAnotherConfig)
docker-compose build
docker-compose up
docker-compose logs

eval $(docker-machine env fm-second)
eval $(cat /Users/krasimir/projects/fm/compose/first/configSecond)
docker-compose build
docker-compose up
docker-compose logs

**Comment by dnephin** [comment]
I don't know about adding an `env` command, I think we should address the first issue, being able to set multiple compose file names from `COMPOSE_FILE`.

I think we can support this using the standard "path list separator" 

In linux/osx (`:`):
```
COMPOSE_FILE=docker-compose.yml:docker-compose.prod.yml
```

In windows (`;`):
```
COMPOSE_FILE=docker-compose.yml;docker-compose.prod.yml
```

If anyone is interested in submitting a PR, I think this would be a small change here: https://github.com/docker/compose/blob/1.6.0-rc2/compose/cli/command.py#L61-L62
