### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by alexpdp7** [docker/compose#2397]
pip install docker-compose
    
    ...
    Downloading/unpacking texttable>=0.8.1,<0.9 (from docker-compose)
    Could not find a version that satisfies the requirement texttable>=0.8.1,<0.9 (from docker-compose) (from versions: v0.8.3)
    Some externally hosted files were ignored (use --allow-external to allow).

I've filed https://github.com/foutaise/texttable/issues/1 too, just filing a ticket here so the issue is visible...

**Comment by sttts** [comment]
Seems to be fixed.

**Comment by alexpdp7** [comment]
Yes indeed, the underlying issue has been fixed

**Comment by Sabya1981** [comment]
getting same error on Ubuntu
