### ISSUE TITLE
Update the installation guide

### ISSUE THREAD

**Issue by moxiegirl** [docker/compose#2399]
Can you check if this is correct?
https://docs.docker.com/compose/install/
the statement "Install Docker Engine version 1.7.1 or greater:"

If I go here
https://github.com/docker/compose/releases
then I see
another statement "Note that Compose 1.5.1 requires Docker 1.8.0 or later."

**Comment by dnephin** [comment]
I think 1.7.x is actually correct, that's the version of the API we use.

**Comment by moxiegirl** [comment]
@dnephin I think the user's concern is that the statement in the install conflicts with the statement on the release page.  Do we require Engine 1.7.1 or 1.8.0 or later?

**Comment by dnephin** [comment]
1.7.1, I've updated the release notes

**Comment by moxiegirl** [comment]
Nifty. Thanks @dnephin
