### ISSUE TITLE
Wrong counting in scale command

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/compose#2403]
Printed service names are inaccurate. It goes like 2,3,2... Very similar to docker/libcompose#35. 

From dockercon keynote:

![image](https://cloud.githubusercontent.com/assets/159209/11207119/83688df4-8d13-11e5-9449-b043158e24dc.jpeg)

**Comment by dnephin** [comment]
I'm pretty sure this is already fixed by #2348

@ehazlett which version of compose were you using?

**Comment by ahmetalpbalkan** [comment]
hehe this one was fun
