### ISSUE TITLE
Disabling clients 1.5 and earlier 

### ISSUE THREAD

**Issue by iMerica** [docker/compose#2422]
Just got this email:
> On December 7, 2015, pulls via clients 1.5 and earlier will be disabled. Only version 1.6 or later will be supported.

Which version of Compose does this correspond to? What is the minimum version of Compose that will now be supported for pulls/pushes on Docker Hub?

**Comment by dnephin** [comment]
"client" in that statement is actually "registry client", which is the docker engine. So as long as you have docker engine 1.6+ you'll be fine.

Docker Compose 1.3 was the first version to required 1.6+

**Comment by iMerica** [comment]
Thanks @dnephin !
