### ISSUE TITLE
Data loss in data volume container with --x-networking flag

### ISSUE THREAD

**Issue by soedar** [docker/compose#2423]
I'm facing an issue with data volume containers under --x-networking flag. After re-building the image, the data in the volume container seems to have disappeared. This behavior does not exist without the --x-networking flag

```
$ docker -v
Docker version 1.9.0, build 76d6bc9
$ docker-compose -v
docker-compose version: 1.5.1
```

**docker-compose.yml**
```
app:
  build: .
  command: sleep infinity
  volumes_from:
    - data

data:
  build: .
  volumes:
    - /data
```

**Dockerfile**
```
FROM debian:jessie
RUN mkdir /app
ADD . /app
```

**Steps to reproduce**
```
# Without --x-networking
$ docker-compose build
$ docker-compose up -d
$ docker exec -it tmp_app_1 touch /data/my_file
$ docker exec -it tmp_app_1 ls /data
my_file
$ touch changes_local_directory
$ docker-compose build
$ docker-compose up -d
$ docker exec -it tmp_app_1 ls /data
my_file

$ docker-compose stop -t 0
$ docker-compose rm -f

# With --x-networking
$ docker-compose --x-networking build
$ docker-compose --x-networking up -d
$ docker exec -it tmp_app_1 touch /data/my_file2
$ docker exec -it tmp_app_1 ls /data
my_file2
$ touch changes_local_directory2
$ docker-compose --x-networking build
$ docker-compose --x-networking up -d
$ docker exec -it tmp_app_1 ls /data

```

**Comment by dnephin** [comment]
Ahh, I bet this is because we have to change the API version to 1.21 to use networking. This upgrade in the API version causes the API to return a different response format for volumes (`Mounts` instead of `Volumes`).  So the API doesn't return anything for Volumes, and Compose things there are no volumes to copy over.

This will be fixed automatically when we upgrade the API version in the next release. Until then we might be able to handle both response formats.

**Comment by soedar** [comment]
I see, thanks!

I've noticed that this issue only arises when the container is being recreated, (ie the `docker-compose up -d` line shows 'Recreating containers ...' as compared to 'Starting containers'). If you don't mind, I'll like to just understand what is happening in either cases.

In the case when the image has not changed, compose will simply re-start the stopped containers. In that case the data is already present in that container, so there is no issue there.

In the case when the image has changed, compose will recreate the container from the new image. The new container does not have the data, so compose will go to the old container and copy the data to the new container.

The bug exist because of the changes in the docker api when querying for the volumes of the old container, which is why compose did not realize there are existing data to be copied to the new container?

**Comment by dnephin** [comment]
Yes, that is correct. The only thing I would add is that a change to the image is not the only thing which can cause a recreate. If you change any configuration about a service it will be recreated.

**Comment by dnephin** [comment]
Compose 1.6 is out now and this should be fixed. `--x-networking` is gone. To enabled networking use the v2 compose file format, which will work with volumes.
