### ISSUE TITLE
Compose file element to be triggered by crontab

### ISSUE THREAD

**Issue by lucj** [docker/compose#2424]
Hi,

I have an application composed of www / api / db parts in docker-compose.yml file.
On a regular basis (once a day), I need to have an additional container that needs to run, perform a single task and then goes down.
What about having some kind of configuration in the docker-compose file, like the following one to have a container based on myimage run (with -rm command) every day at 00:00 ?

    project:
      image: myimage
      crontab: 0 0 * * *

**Comment by dnephin** [comment]
That is not really possible. There is no daemon to schedule these tasks, and it's somewhat outside the scope of Compose. You could however run a `crond` container that stays running and does the work of scheduling tasks.

**Comment by lucj** [comment]
hum, ok I see.
What do you think could be the best way to have the "link" between this crond container and the containers it need to ran ? Through env var ? 
In the compose file, can containers be defined (so the image are downloaded whit docker-compose up) without been launched ?

My idea was to have something like the following.

    www:
      image: www-app
    api:
       image: api-app
    db:
      image: mongo
    cron:
       image: mycron
       environment:
         - task1: "0 0 * * *"
         - task2: "0 0 * * *"
    task1:
        image: task1-app
        not_run_at_startup
    task2:
        image: task2-app
        not_run_at_startup

Well, that might be too related to my needs.

**Comment by dnephin** [comment]
I think there are a few ways to implement it. 

Option 1 is to have the crond image contain all the dependencies needed for task1 or task2. That might work fine if they have similar dependencies. Then you can just run the tasks in the crond container directly.

Option 2 would be to implement the tasks as part of the api (or maybe a separate api service).  Then the crond would just execute something like `curl` to trigger the API endpoint, and the task itself would run in the api container.  I think this is smiilar to how [scheduled tasks on google app engine](https://cloud.google.com/appengine/docs/python/config/cron?hl=en) work. You just tell it to hit a url at the schedule time, and the task runs somewhere else.

A third option might be to expose `/var/run/docker.sock` as a volume to the crond service. Then the cron service can take care of starting the container it needs directly. You could include the link name as part of the arguments so the containers that get started are linked correctly.

**Comment by lucj** [comment]
Thanks Daniel for the detailed answer, interesting ways to implement this.
I'll try option 1 and option 3 as the tasks I need to run are external to the api.
When running compose on a swarm, can the images needed for my task be downloaded without being ran so they are already present when triggered by the crond image ?

**Comment by dnephin** [comment]
I believe that a `pull` on swarm will pull the image to all nodes. So if you issue a pull with either the docker client or add them to the docker-compose (maybe with a command of `true`) and run `pull`, they should be available.

**Comment by lucj** [comment]
Thanks a lot, I'll test this approach.
