### ISSUE TITLE
Where is pulled image, how can i customize it with docker-compose ?

### ISSUE THREAD

**Issue by reyman** [docker/compose#2426]
Hi,
I'm new on docker, and docker-compose.

After pull on some image, i search the way to configure it with docker-compose.
Where are located the image pulled on the local disk (i'm using ubuntu) ? How can i run docker-compose on an existing `docker-compose.yml` into this pulled image ? I don't find this information in docker manual. Can you enlight me ?

Thanks

**Comment by dnephin** [comment]
You can find more information here: http://docs.docker.com/compose/gettingstarted/

You don't customize an image directly, you would do it by creating a new `Dockerfile` and using `FROM <the image name>`.

**Comment by reyman** [comment]
Hum, so @dnephin , when the image [zulip](https://github.com/Galexrt/docker-zulip) say that i need to pull then configure my docker-compose.yml ?

a) i pull using `docker pull quay.io/galexrt/zulip:v1.3.9`
b) I create a new `DockerFile` and a `docker-compose.yml` in a project folder in my home directory
c) I run `build from quay.io/galexrt/zulip:v1.3.9`
d) then i run `docker-compose up`

Something like this ?

**Comment by dnephin** [comment]
I may have misunderstand your question. If you only need to apply runtime configuration you can use `image: quay.io/galexrt/zulip:v1.3.9`.

If you need to make changes to the image, you would use `FROM`, and `build: .`

but all of this is covered by the docs

**Comment by dnephin** [comment]
Sounds like this was sorted out, so going to close the issue.
