### ISSUE TITLE
Creating Data Named Volume in docker-compose.yml

### ISSUE THREAD

**Issue by juliengarcia** [docker/compose#2434]
Hello, 
with the docker 1.9 version, we can create volume like that `docker volume create --name myvolume`

There is a way to manage that in the docker-compose.yml?

I know we can use the named volume directly in the docker-compose file, but i would like to create it also.

Thanks in advance

**Comment by dnephin** [comment]
It's being worked on for the next release.

Issue is #2110

**Comment by juliengarcia** [comment]
Glad to read that ;)

Le ven. 20 nov. 2015 17:13, Daniel Nephin <notifications@github.com> a
écrit :
