### ISSUE TITLE
monitor or keep the suppose amount of desired containers running

### ISSUE THREAD

**Issue by bitgandtter** [docker/compose#2435]
This suppose to be a question, debate and maybe a feature.

I have been using k8s for a while and i really want to migrate over all docker tools, i mean use compose to manage my topology and use swarm for my cluster. 

My question is: There is some proposal, discussion or WIP about monitor and keep running the desired amount of containers for a service?

Explain, on k8s you have replication controllers that always keep runnig the desired amount of containers for a service, if for some reason one of those containers stop it will create a fresh one.

This will be a great feature for compose since help you protect against disasters, its not all but will help.

**Comment by dnephin** [comment]
I believe that would be part of swarm.  Compose doesn't run a daemon, so there's nothing that would be around to handle failures. I think this might be covered by issue https://github.com/docker/swarm/issues/599

**Comment by cpuguy83** [comment]
Yep, not compose itself, though the format could be used.
Note there is an effort to extract some of compose's functionality into a go lib: github.com/docker/libcompose -- this would lend itself quite well to either embedding the parser+executer  into an existing product or into something new (like a compose daemon).

**Comment by dnephin** [comment]
Is the compose format really necessary for this feature?  If I tell swarm: run containers x, y, z (either with compose or the docker cli), and the containers all have a restart policy of 'always', it should have all the information it needs to ensure that those containers always stay running (or at least are restarted when they fail).

**Comment by cpuguy83** [comment]
@dnephin Not really, other than having a declarative API rather than imperative.

**Comment by bitgandtter** [comment]
@dnephin Could be, but imagine this edge case:

You have a service app scaled to 3 instances and you use the restart police to --always, then you try to scale it to 10 instances but at that moment one of your previously running instances stops for some reason, compose will bring up only the missing 7 instances or will include the one that its already stopped  so it can reach the expected number (10).

If the answer is no compose will only bring up the missing 7 then it could work
If the answer is yes compose will bring up the missing 7 and the 1 that is stopped then we finally end with 11 after the restart police for the stopped one bring it back.

sorry if i dont test that scenario before with compose

**Comment by dnephin** [comment]
@bitgandtter yes, that is a good point. Scale can result in incorrect counts because of a race condition, even without swarm (on a single engine).

**Comment by bitgandtter** [comment]
@dnephin so the question remains, where this should be implemented on compose or on swarm, from my perspective this is more a compose use case, swarm should take care only about cluster configuration and maintenance, and that in fact is under the scope of the issue you point me on the previous comment. I know compose its only a cli tool and does not have a daemon or API, but i also think   that creating a whole new tool to add this use cases only not to implement compose as a daemon is a little extreme.

What do you guys think?

**Comment by aanand** [comment]
I think that the responsibility of keeping the number of containers at N should lie exactly as far down the stack as N does. That is to say: whatever the lowest-level component is that has a concept of "there should be N containers running", *that component* should be the one that monitors, creates, starts, destroys &c as necessary.

Right now that's Compose, but in my opinion we should move the concept of the "scale number" down the stack, whether into Swarm or Engine or something else.

That's a significant design undertaking, as you'd have to move the whole concept of a "service" along with it, but I think it's the right thing to do - Compose feels too smart for a client-side tool.

**Comment by nathanleclaire** [comment]
Just happened to wonder in to this thread but, +1 to the feature (being added to Swarm/Docker instead of here) and to @aanand argument.

**Comment by bitgandtter** [comment]
Agree with the idea @aanand 

Compose definitely holds right now the concept of service, but If compose suppose to be as simple as possible CLI to help orchestrate services and for a whole and more complex app, then you are 100% right compose its to smart.

Now i think the please should not be swarm either, i see on swarm another simple tool/service that allow to communicate between nodes/machines on different providers and discover each other, it definitely needs to know which container is running on what node but the concept of a service is not on swarm.

Engine as the lowest level its on my perspective on the same scenario of swarm, engine should only care about how to handle containers, the concept of service its too abstract and too complex for engine.

So compose is the right place right now but if it should be kept just as a simple helper CLI then its just one way out, a new tool needs to born, maybe using some of the concepts from compose but with a more complex vision of service orchestration, been more than a cli and as a daemon with its own API been able to handle the concept of a service, replication of services, interconnection of if and exposition to the public network, one example of this is JUJU.

If that suppose to be correct, and i think it is; then some questions come to me:

1. What should be the domain and concepts on this new tool
2. What concepts from the existing tools should be moved into this one

**Comment by aluzzardi** [comment]
Hey @bitgandtter, this is indeed in our long term plan, but there are many dependencies we need to solve before we can achieve that.

In the meantime, we just spec'ed the first building block for that: Have Swarm automatically reschedule containers upon node failure: docker/swarm#1488

While the concept of service is not in Swarm, it will keep the containers created by compose (through scale) up and running.

**Comment by aluzzardi** [comment]
I agree with @aanand and @bitgandtter - those concepts shouldn't live in compose as it's a client-side tool, although I'm still debating whether they should live in Swarm or another daemon running between Swarm and Compose.

**Comment by ablock84** [comment]
Just a thought: Can't compose start a "compose daemon container" on the engine/swarm that keeps maintaining the desired amount of instances? The (future) rescheduling part of swarm would then ensure that the "daemon container" keeps running in the swarm.

**Comment by bitgandtter** [comment]
@ablock84 that will be the same as compose as a daemon with its own API, a compose daemon container as you propose does not do much if it does not have any API to communicate with it and build an API into that container service will something like create a new service tool
