### ISSUE TITLE
Build cache issue when Dockerfile is listed in .dockerignore.

### ISSUE THREAD

**Issue by 0x4d4c** [docker/compose#2443]
When the Dockerfile contains a `COPY` of a directory and the Dockerfile is listed in the .dockerignore then `docker-compose build` doesn't pick up on changes of files in this directory and uses the build cache instead. Building the same image with `docker build` works as expected. Removing the Dockerfile from the .dockerignore also leads to the expected behaviour.
I created some [example files](https://github.com/0x4d4c/docker-compose-dockerignore-issue.git) to illustrate and reproduce the issue.

Tested with:
```
docker-compose version: 1.4.0
```
```
docker-compose version: 1.5.1
```
```
docker-compose version 1.6.0dev, build unknown
```
and
```
Docker version 1.9.0, build 76d6bc9
```

**Comment by dnephin** [comment]
This is really strange. From what I can see `docker-py` (which is responsible for building the tarball context and sending it to the docker engine) is doing the right thing. 

The changes are in the context that gets sent to the API.  From there, docker engine seems to think the context is the same.  Maybe the docker client is doing something special in the case where `Dockerfile` is in the dockerignore list.

**Comment by danielpanteleit** [comment]
Seems to be fixed with Docker version 1.9.1

```
...
[*] Adding Dockerfile to .dockerignore.

[*] Rebuilding with compose.
Building testcase...
Step 1 : FROM library/debian:latest
 ---> 91bac885982d
Step 2 : COPY src /usr/src
 ---> Using cache
 ---> f40ed943b86e
Successfully built f40ed943b86e

[*] Rebuilding with docker build.
Sending build context to Docker daemon 5.632 kB
Step 1 : FROM library/debian:latest
 ---> 91bac885982d
Step 2 : COPY src /usr/src
 ---> Using cache
 ---> ae20615cc0eb
Successfully built ae20615cc0eb

[*] Changing some file.

[*] Rebuilding with compose.
Building testcase...
Step 1 : FROM library/debian:latest
 ---> 91bac885982d
Step 2 : COPY src /usr/src
 ---> 83c59849842e
Removing intermediate container 231e4567c668
Successfully built 83c59849842e

[*] Rebuilding with docker build.
Sending build context to Docker daemon 5.632 kB
Step 1 : FROM library/debian:latest
 ---> 91bac885982d
Step 2 : COPY src /usr/src
 ---> 0976db200e8e
Removing intermediate container 15d971326450
Successfully built 0976db200e8e
```

**Comment by 0x4d4c** [comment]
@danielpanteleit is right -- with Docker 1.9.1 everything behaves as expected.

I think I'll close this issue then. @dnephin: Feel free to re-open it, if you want to investigate the reason for the behaviour with Docker 1.9.0, but as for my part everything is okay now...

**Comment by danielalves** [comment]
Well, I just wanted to leave this documented: as @0x4d4c said, using `Docker version 1.9.0, build 76d6bc9` and `docker-compose version: 1.5.1`, on OSX, leads to this `COPY` cache problem. However, the solution I found was to remove the `.dockerignore` itself from the .dockerignore file, not the `Dockerfile`. `Docker version 1.9.1, build a34a1d5` really seems to fix everything, though.
