### ISSUE TITLE
Should set MemorySwappiness default value -1

### ISSUE THREAD

**Issue by jimmyxian** [docker/compose#2459]
When create container, compose should set MemorySwappiness default value -1.
Related issue: https://github.com/docker/swarm/issues/1411

**Comment by jimmyxian** [comment]
ping @aanand @dnephin

**Comment by dnephin** [comment]
We don't set `MemorySwappiness` at all. I think that swarm and engine should both treat null as `-1`.

**Comment by jimmyxian** [comment]
@dnephin Got it. Agree with you.
