### ISSUE TITLE
ERROR:  Conflicting options: -h and the network mode (--net)

### ISSUE THREAD

**Issue by bmtechlab** [docker/compose#2460]
after last docker update, when I try make `docker-compose up` I get:

```
Creating bridge
ERROR:  Conflicting options: -h and the network mode (--net)
```
compose file is:
```
bridge:
    build:          ./some-bridge
    container_name: bridge
    hostname:       bridge
    restart:        always
    net: "container:openvpn"
    env_file:
        - /home/someuser/environment/environment.sh
```

`openvpn` is an external container with the following  running options
```
docker run -p 32323:32323 -d -v /etc/openvpn:/etc/openvpn --cap-add=NET_ADMIN -v /dev/net/tun:/dev/net/tun --name openvpn openvpn
```

I use `Docker version 1.9.1, build a34a1d5` and `docker-compose version: 1.5.1`

**Comment by dnephin** [comment]
Please include the full output of `docker info`. We've had a report of this on the windows version of docker, but I'm not sure if that's the case here.

**Comment by bmtechlab** [comment]
Containers: 19
Images: 1156
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1194
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: SOME-dockers
ID: 3EZK:GU43:HETB:BDSB:CB64:DPFP:CH2T:ZK4Q:LZM7:FYGI:ZPBC:JHCF
WARNING: No swap limit support

**Comment by mrfuxi** [comment]
Related docker issue: https://github.com/docker/docker/issues/17147

**Comment by dnephin** [comment]
Good find, I think this is actually a bug with the Docker error message. `hostname` and `net: container` are incompatible, so it's correct to error out, but the message is really bad.

It's also not ideal to error out on the compose side because since this is an api constraint, not really a config constraint.  I'd like to try and get this fixed in the API.

**Comment by abd2561024** [comment]
+1

**Comment by mrfuxi** [comment]
Changes to error message done in Docker engine: https://github.com/docker/docker/pull/18349

**Comment by dnephin** [comment]
Nice, thanks for the fix!

Since this will be fixed on the engine side in the next release I think we can close this.

**Comment by Killertjuh** [comment]
I have the same problem:

docker info

```
Containers: 97
 Running: 1
 Paused: 0
 Stopped: 96
Images: 46
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 648
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.9 MiB
Name: DockerServer
ID: 7ZQA:RLEA:FI4X:E7SO:YQKO:D6D2:BK6W:J6C2:PO7S:SFXV:Z2KF:KNX3
WARNING: No swap limit support
```

docker-compose file:
```
sshclient:
 image: sshclient
 hostname: sshclient
 restart: always
 ports:
  - "23:22"
 net: container:openvpnclientdockerfile_openvpnclient_1
 command: "/usr/sbin/sshd -D"
````

Error message:

```
Recreating a7ac7f7aac_a7ac7f7aac_sshdockerfile_sshclient_1...
Conflicting options: hostname and the network mode
```

Workaround remove the hostname
