### ISSUE TITLE
When scaling, also scale links

### ISSUE THREAD

**Issue by atrauzzi** [docker/compose#2472]
I currently have an nginx and php-fpm container pair configured under a haproxy container.  Everything seems to work, but I'd really like it if I could have the links back to haproxy automatically duplicated as well whenever I scale the containers.

Also, the links between the two containers will obviously need to be scaled as well as they travel in pairs.

**Comment by dnephin** [comment]
Links are unidirectional, but the new user defined networks (enabled with  `--x-networking`) should do what you want. http://docs.docker.com/compose/networking/

**Comment by atrauzzi** [comment]
Going over that page, I don't see anything that speaks specifically to automatically duplicating groups of containers, attaching them to each other and then attaching one of them to a container outside of the group.

**Comment by aanand** [comment]
The interaction of scaling with networking (as with links) is unsatisfactory at the moment - you'll basically get a bunch of entries in `/etc/hosts` along these lines:

```
172.16.0.1 myapp_php_1
172.16.0.2 myapp_php_2
172.16.0.3 myapp_php_3
```

In a future version of Compose (enabled by changes to Engine), the name under which each container joins the network is going to change to just the service name, `php`. So you'll get multiple entries with the same name:

```
172.16.0.1 php
172.16.0.2 php
172.16.0.3 php
```

This isn't a real solution either, of course - we're still working towards one - but in both cases, if you have a load balancer container that needs to keep up-to-date with what's currently on the network, for the time being it'll need to periodically read `/etc/hosts` and parse the entries to determine the IPs of the backends.

**Comment by dnephin** [comment]
With user defined networks in Compose 1.6 you will have connectivity between all containers on a network by default, without the need to create 1-to-1 links between each. I believe this solves the issue.

**Comment by kamushin** [comment]
@aanand Any update yet?
