### ISSUE TITLE
Preserve previous exit semantics and behavior

### ISSUE THREAD

**Issue by pandeiro** [docker/compose#2474]
Prior to docker-compose 1.5.x, if a single container exited, the entire set of compose's running containers exited as well. (This is actually a rather major semantic change for 1.4.2 -> 1.5.x IMO.)

There are still cases where the previous behavior is more desirable. For one example: running an integration test suite using [dockerized Selenium container(s)](https://github.com/SeleniumHQ/docker-selenium) -- ideally when the integration tests exit, the entire docker compose process would exit as well.

Is there any way to enable this prior behavior through a flag or other mechanism?

**Comment by dnephin** [comment]
I've outlined some options in https://github.com/docker/compose/pull/1754#issuecomment-154218084

Do either of those work in your case?

**Comment by pandeiro** [comment]
@dnephin Both of those suggestions would involve non-trivial adjustments to the way we were using compose with our stack.

We can work around it in a number of ways, but I think #2130 would provide the easiest path by far to making our workflow compatible with 1.5.x.

**Comment by dnephin** [comment]
Could you tell me more about how you're using compose?  The changes I proposed should be pretty straightforward (adding a couple extra commands to a script).

**Comment by pandeiro** [comment]
Yeah, I guess "straightforward" is pretty subjective so I won't argue that.

Essentially it was very nice to be able to consume the upstream selenium image directly without building a derivative image as a workaround, and be able to have a simple, one-configuration-file setup for running the tests.

I'd been doing that practically since fig/compose was initially released, prior to this change, on a large number of projects.

**Comment by dnephin** [comment]
I'm trying to figure out if using `docker-compose run` is not a workable solution for some reason. The stop can be done using `trap ... EXIT` in bash, if it's being run from a bash script.

**Comment by pandeiro** [comment]
"Workable" is also very subjective. In my case, if I'm needing to write an additional Dockerfile, compose configuration files, or bash scripts and run several commands instead of one, the value proposition of using compose vs. just using Docker itself (and maybe bash) is diminished.

If however you think that the difference between the two is negligible, let's close this and move on. :)

**Comment by dnephin** [comment]
I don't understand why an additional Dockerfile or compose configuration would be required. At this point I'm really just trying to understand the use case. An example of the workflow , or some pseudo code might help.

**Comment by pandeiro** [comment]
Ah, sure. I have a project (slightly simplifying) that executes a series of automated web browser tasks. The entire Docker-related configuration consists of one file, docker-compose.yml, and one command, `docker-compose up`. I find the simplicity of that wonderful and worth the trouble needed to install compose on remote machines (significant since my distro does not package it).

Here's the compose file:

```
frontend:
  image: pandeiro/boot:2.3.0
  command: collect
  net: "host"
  volumes_from:
    - selenium # just used for establishing startup order
  volumes:
    - ~/.boot:/.boot
    - ~/.m2/repository:/m2
    - .:/app

selenium:
  image: selenium/standalone-chrome-debug:2.48.2
  volumes:
    - /dev/shm:/dev/shm
  net: "host"
```

**Comment by ahromis** [comment]
I agree with this, previously I had some unit tests that ran nicely with just a `docker-compose up`.  With the new behavior the database container just hangs after the tests have completed.  

This means I basically need to strip that out and put it in an external script with this new behavior.  While I agree that the proper behavior for this is to keep running as containers have exited - I think that we should still be given an option to have the other containers exit on a container stop.
