### ISSUE TITLE
Problem with connect network at docker-compose.yml.

### ISSUE THREAD

**Issue by ceasbz** [docker/compose#2475]
Hello,

I'm having some problems to connect with network at docker-compose.yml

`Docker version 1.9.1, build a34a1d5`
`docker-compose version: 1.5.1`
`docker-machine version 0.5.1 (7e8e38e)`

For install some dependencies, inside of entrypoint I has the following command: `composer install`. And received the following message:

`SlowTimer [54662ms] at curl`
`Fatal error: Maximum execution time of 180 seconds exceeded`

When I try to run apt-get update command the same thing happens. Could anyone help me?

**Comment by aanand** [comment]
First off, just so we're clear, I presume `composer install` is an invocation of the [Composer dependency manager for PHP](https://getcomposer.org/), and nothing to do with Docker Compose?

Now, if you're having trouble reaching the outside world from inside a container, and your containers are running inside a VirtualBox VM (e.g. if you installed Docker via boot2docker or the Docker Toolbox), it could well be a transient problem that's fixable by restarting or destroying/recreating your VM - try `docker-machine restart default`.

**Comment by cauealves** [comment]
Hello @aanand,

Yes, is an invocation of the composer manager for php.

I already run the command `docker-machine restart default` and it seems that it communicates with network now.

But I'm having a very large latency... Its normal?

**Comment by sermanes** [comment]
How do you increase the timeout in docker ? You change something in docker-compose.yml? @cauealves

**Comment by cauealves** [comment]
Hello @sermanes,

For some reason, I had to restart several times my `docker-machine` to solve the problem.

I haven't made any changes to the `docker-compose.yml`.
