### ISSUE TITLE
Join service/containers to multiple networks

### ISSUE THREAD

**Issue by schmunk42** [docker/compose#2476]
With docker 1.9 you can connect a container to multiple networks, see [docs](http://docs.docker.com/engine/reference/commandline/network_connect/), but how can I do this with compose?

I read through the [networking](https://github.com/docker/compose/blob/master/docs/networking.md) section of compose, but haven't found a description about my issue.

I saw several issues and discussions, where the following syntax was mentioned:

```
networks:
   - myvxlan1
   - myvxlan2
```

What's the current way, how to join to multiple networks with compose?

**Comment by aanand** [comment]
It's not currently supported. I've created https://github.com/docker/compose/issues/2478 for discussion of this and wider topics.
