### ISSUE TITLE
use env in the compose file from  the env_file

### ISSUE THREAD

**Issue by vipconsult** [docker/compose#2482]
I use the same compose file to deploy 2 servers the only difference between the two servers are the envs set in the env file so that I can use and maintain only one compose file
env_file:
        - env

the env file has 
INTERNAL_IP=............

I use 2x lsyncd containers to keep some files synced between 2 hosts so I use the INTERNAL_IP to set them to listen only on the internal ip

instead I am hoping that docker-compose can parse the env file first so that I can use something like
ports:
        - "${INTERNAL_IP}:11211:11211"

**Comment by dnephin** [comment]
We don't want to diverge from docker-engine support for these kind of feature. Since docker cli doesn't support this, I don't think we'll be able to implement it.

Why not do:

```yaml

environment:
    INTERNAL_IP:
```

**Comment by vipconsult** [comment]
I use the same compose file on more than one host and the difference is in the env_file which is loaded with the compose file.

the compose file is in git and the env_file is not so that I can have different configurations with the same compose file.

so I should submit the issue to docker then.

**Comment by thaJeztah** [comment]
Would a `docker-compose.override.yml` file be a solution for your use case? https://docs.docker.com/compose/extends/#understanding-multiple-compose-files

You could add the `docker-compose.yml` to git, and put the override file with settings specific to each host on each server.

**Comment by vipconsult** [comment]
Thanks for the suggestion.

I have changed my setup a bit.
Now I use docker machine with docker compose to run all compose file from my dev laptop. 
Lets put it on hold for now. I still find some difficulties with the ip bindings, but when I decide what would be the best solution might reopen this.
