### ISSUE TITLE
building from git:// url

### ISSUE THREAD

**Issue by paulwellnerbou** [docker/compose#2488]
Hi,

with docker I can build images directly from any git url (e.g. docker build -t wellnerbou/tomcat7 git://github.com/paulwellnerbou/docker-tomcat.git).
I tried to to this with docker-compose as well, without success until now.
Is this possible?

Thanks and Regards
Paul.

**Comment by dnephin** [comment]
Support for this was added in #2430 which is in master, and will be in the 1.5.2 release.

You can try out a master build https://dl.bintray.com/docker-compose/master/ until 1.5.2 is released (which should be soon).

**Comment by paulwellnerbou** [comment]
Thank you, thats great.
