### ISSUE TITLE
ports yaml option does not resolve hostnames (i.e. "localhost")

### ISSUE THREAD

**Issue by ivan-kolmychek** [docker/compose#2493]
For instance, if you specify `ports` in `docker-compose.yml` as

``` yaml
ports:
  - "localhost:5432:5432"
```

the container will bind to `0.0.0.0:5432` on the host machine, instead of `127.0.0.1:5432`.

Docker version 1.9.1, build a34a1d5-dirty
docker-compose version: 1.5.1

**Comment by dnephin** [comment]
I tried this out. If you inspect the container, the `HostConfig.PortBindings` has  `"HostIp": "localhost"`, which is correct, but the `NetworkSettings` has `0.0.0.0`.  So I'm not sure if this is a docker bug, or just a reporting problem, but I think Compose is doing the right thing here because the `HostConfig` is correct.

**Comment by ivan-kolmychek** [comment]
@dnephin so, should I post a report to Docker's issues instead?

**Comment by dnephin** [comment]
I think it needs more investigation.  I'm not sure what the expected behaviour should be, or why it's being reported this way.

**Comment by aanand** [comment]
The Docker CLI doesn't seem to permit this:

```console
$ docker run -d -p localhost:1234:1234 busybox top
docker: Invalid ip address: localhost.
See 'docker run --help'.
```

**Comment by dnephin** [comment]
Ah, so I guess this is a bug in the docker API. It needs to properly validate the HostIP (instead of that validation being done in the cli).

**Comment by richard-delorenzi** [comment]
```
ports:
  - "127.0.0.1:5432:5432"
```
Also results in binding to 0.0.0.0 and `docker run -d -p 127.0.0.1:1234:1234 busybox top` is allowed.

**Comment by ijc** [comment]
Issue grooming: Closing as stale, if this is still happening then I think the consensus from the above is that it is an engine issue so please refile there.
