### ISSUE TITLE
docker-compose build stuck on auth

### ISSUE THREAD

**Issue by blackxored** [docker/compose#2497]
Compose locally works flawlessly, but as soon as you switch it to point to a remote host, it takes ages (>2h) to complete a build command. Running it verbosely shows nothing else that being stuck on sending auth info, and then the rest of the process completes in <1 min. I wonder if I'm doing something wrong, or if it wasn't supposed to be used that way (as opposed to docker pushin' to a private registry or something), but it's really hindering my deployments.

**Comment by dnephin** [comment]
Do you have a `.dockerignore` for any large data you don't need in your build context?  I suspect it's uploading `.git` or some other large data files that aren't being used.

**Comment by blackxored** [comment]
I do have a docker ignore,
ignores everything but the dist folder.

**Comment by aanand** [comment]
It would be worth trying the equivalent `docker build` and seeing if it behaves any differently - if not, perhaps try building with a really minimal build context (e.g. just a Dockerfile, nothing else to upload) and seeing if you still get a delay. That should at least narrow down what's taking so long.

**Comment by dnephin** [comment]
No response from OP, so going to close this issue.

We pulled in a couple `.dockerignore` related fixes from `docker-py` in the Compose 1.6 release, so it's very likely resolved with one of those.

**Comment by blackxored** [comment]
That's more likely the case. Thanks @dnephin
