### ISSUE TITLE
$ at the end of environment variable causes "Invalid Interpolation" error

### ISSUE THREAD

**Issue by darkmane** [docker/compose#2507]
Repro Steps:
- Create a new directory
- Use the attached docker-compose.yml file
- docker-compose up 

Expected Results:
A redis container is created.

Actual results:
ERROR: Invalid interpolation format for "environment" option in service "contentMysql": "B!naree80reF0rG3taway$"

[docker-compose.yml.txt](https://github.com/docker/compose/files/52397/docker-compose.yml.txt)

**Comment by dnephin** [comment]
Does it work if you escape the `$` using `$$` ?

I'm not sure there is anything we can do about this. `$` is now a special character, and needs to be escaped.

**Comment by darkmane** [comment]
It does work with the escaping. These docker-compose.yml files worked before and then stopped after I upgraded, I missed the variable substitution section of the documentation.

Closing.
