### ISSUE TITLE
Suggested documentation clarification for "Extending services and Compose files"

### ISSUE THREAD

**Issue by pydolan** [docker/compose#2514]
I recently [described on Stackoverflow](https://stackoverflow.com/questions/34147939/when-using-multiple-docker-compose-config-files-in-cli-do-they-need-specifying/) some confusion I have/had regarding the extending services feature of Docker Compose.  As I note there, I was confused on whether all configuration files need to be added to all CLI commands.  From what I can tell, they are needed. While this may seem obvious to some, I think it would be useful to explicitly state this in the documentation.

 In the setup I describe on that Stackoverflow post, I was using _docker-compose.yml_ to define my "base" setup and then override this with files like _docker-compose.test.yml_ and _docker-compose.dev.yml_. It's easy to forget to specify the `-f docker-compose.yml -f docker-compose.test.yml` on each command I run, thus getting potentially problematic commands run.

In the documentation, it might also be helpful to suggest an optional renaming of _docker-compose.yml_ to _docker-compose.base.yml_ if users want to avoid accidentally running Compose commands with the wrong configuration.

Let me know if I'm misunderstanding standing how things work or if I'm misunderstanding the intention of this feature.

Thanks!

**Comment by dnephin** [comment]
That sounds right
