### ISSUE TITLE
Using docker-compose with cygwin and a private registry

### ISSUE THREAD

**Issue by nickcodefresh** [docker/compose#2517]
Using using docker-compose v1.5.2 under Windows and cygwin, when I run docker-compose pull I get the error:

```
{ MioEvents }  » docker-compose pull
Pulling mongodb (mongo:latest)...
latest: Pulling from library/mongo
Digest: sha256:9693218db42f58992744fe566ea6e67f149b7757ab43df597d270c7daf25b5cf
Status: Image is up to date for mongo:latest
Pulling consul (registry.nativ-systems.com/nativ/consuld:latest)...
Pulling repository registry.nativ-systems.com/nativ/consuld
Authentication is required.
```

I've registered with my private registry and it works fine under CMD. I've tried making a symlink ```~/.docker``` to ```C:\Users\nick.smith\.docker``` but it still doesn't work.

Any ideas?

Thanks

Nick

**Comment by aanand** [comment]
Could you rerun with `docker-compose --verbose`? It should print some debug information about where it's looking for authentication data.

**Comment by nickcodefresh** [comment]
When running with --verbose I can see it's trying to get the auth data from ```C:\Users\nick.smith\.babun\cygwin\home\nick.smith\.docker\config.json``` which although exists as a symlink, doesn't seem to be able to be loaded. If I don't use a symlink then it works (i.e. I copy ````/cygdrive/c/Users/nick.smith/.docker/config.json```` to ```~/.docker/config.json```.

**Comment by aanand** [comment]
That suggests that it's using one of the following paths, going off [the relevant code in docker-py](https://github.com/docker/docker-py/blob/6d0e2d6/docker/auth/auth.py#L131-L143):

```python
environment_path = os.path.join(
    os.environ.get('DOCKER_CONFIG'),
    os.path.basename(DOCKER_CONFIG_FILENAME)
)
```

```python
os.path.join(os.path.expanduser('~'), DOCKER_CONFIG_FILENAME)
```

Is the DOCKER_CONFIG environment variable set in your shell?

**Comment by nickcodefresh** [comment]
I tried setting DOCKER_CONFIG for the Cygwin shell to ```/cygdrive/c/Users/nick.smith/.docker/config.json``` but I still get the "Authentication is required" issue

**Comment by aanand** [comment]
Reading the code above, it looks like you should be setting DOCKER_CONFIG to `/cygdrive/c/Users/nick.smith/.docker`.

If that still doesn't work, can you please paste the actual output of `docker-compose --verbose pull`, as well as the keys of the `auths` object defined in your `config.json` (with any sensitive data removed)?

**Comment by nickcodefresh** [comment]
I tried the following but Docker Compose seems to completely ignore the DOCKER_CONFIG env variable
```
{ MioWorkflowParent }  » DOCKER_CONFIG=/cygdrive/c/Users/nick.smith/.docker                                                            ~/workspace/trunk/MioWorkflowParent 1
{ MioWorkflowParent }  » docker-compose --verbose pull                                                                                   ~/workspace/trunk/MioWorkflowParent
compose.config.config.find: Using configuration files: .\docker-compose.yml
docker.auth.auth.load_config: Trying C:\Users\nick.smith\.babun\cygwin\home\nick.smith\.docker\config.json
docker.auth.auth.load_config: File doesn't exist
docker.auth.auth.load_config: Trying C:\Users\nick.smith\.babun\cygwin\home\nick.smith\.dockercfg
docker.auth.auth.load_config: File doesn't exist - returning empty config
compose.cli.command.get_client: docker-compose version 1.5.2, build e5cf49d
docker-py version: 1.5.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.2a 19 Mar 2015
compose.cli.command.get_client: Docker base_url: https://192.168.99.100:2376
compose.cli.command.get_client: Docker version: KernelVersion=4.1.13-boot2docker, Os=linux, BuildTime=Fri Nov 20 17:56:04 UTC 2015, ApiVersion=1.21, Version=1.9.1, GitCommit=a34a1d5, Arch=amd64, GoVersion=go1.4.3
compose.service.pull: Pulling mio-auth-service (registry.nativ-systems.com/nativ/mio-auth-service:latest)...
compose.cli.verbose_proxy.proxy_callable: docker pull <- ('registry.nativ-systems.com/nativ/mio-auth-service', tag=u'latest', stream=True)
docker.api.image.pull: Looking for auth config
docker.api.image.pull: No auth config in memory - loading from filesystem
docker.auth.auth.load_config: Trying C:\Users\nick.smith\.babun\cygwin\home\nick.smith\.docker\config.json
docker.auth.auth.load_config: File doesn't exist
docker.auth.auth.load_config: Trying C:\Users\nick.smith\.babun\cygwin\home\nick.smith\.dockercfg
docker.auth.auth.load_config: File doesn't exist - returning empty config
docker.auth.auth.resolve_authconfig: Looking for auth entry for 'registry.nativ-systems.com'
docker.auth.auth.resolve_authconfig: No entry found
docker.api.image.pull: No auth config found
compose.cli.verbose_proxy.proxy_callable: docker pull -> <generator object _stream_helper at 0x000000000363F1B0>
Pulling repository registry.nativ-systems.com/nativ/mio-auth-service
compose.cli.main.main: Authentication is required.
{ MioWorkflowParent }  »        
```

I'd already created a symlink in Cygwin from ```/home/nick.smith/.docker``` to ```C:\Users\nick.smith\.docker``` but this didn't help.

To solve the issue I deleted the Cygwin symlink and created a Windows one instead

```
mklink /D C:\Users\nick.smith\.babun\cygwin\home\nick.smith\.docker C:\Users\nick.smith\.docker
```
