### ISSUE TITLE
Feature Request: 'list' command

### ISSUE THREAD

**Issue by citec** [docker/compose#2531]
It would be very useful to have a 'list' command to list all containers defined in the docker-compose.yml file.
Ex: docker-compose list
Output:
&nbsp;&nbsp;&nbsp;&nbsp;apache
&nbsp;&nbsp;&nbsp;&nbsp;mysql

It could have some options, for example:

-i (show images)
&nbsp;&nbsp;&nbsp;&nbsp;output: apache (repo/apacheimg:latest)

-d (show dependencies)
-s (show status: up|exit)

**Comment by dnephin** [comment]
Do you want to list containers or services? we have both:

```
# list containers
docker-compose ps -q

# list services
docker-compose config --services
```

`docker-compose config` is in master, but is not yet in a release. It will be in 1.6.0. You can try it out with a master build from https://dl.bintray.com/docker-compose/master/

`docker-compose ps` shows status by default. There is also #2369 for tracking feature requests for the `ps` subcommand.
