### ISSUE TITLE
DNS is now an array?

### ISSUE THREAD

**Issue by johnjelinek** [docker/compose#2532]
I guess in my docker-compose.yml, dns is expected to be `[]string` now instead of `string`. My existing `docker-compose.yml` had:

`dns: 172.17.0.1`

and now it has to be:

```
dns:
    - 172.17.0.1
```

otherwise I get this error message: `ERROR: json: cannot unmarshal string into Go value of type []string`.

**Comment by dnephin** [comment]
This was a regression in 1.5.2, it's fixed in master by #2527 ( #2515)

https://dl.bintray.com/docker-compose/master/
