### ISSUE TITLE
volumes_from with swarm not working

### ISSUE THREAD

**Issue by ekristen** [docker/compose#2534]
I have a container that already exists on **every** node in the swarm, call "certs" but when I run docker compose against my swarm master, it tells me it does not exist.

The container is not running it has just been created.

Compose complains that certs is not a service or container name, yet it exists on every server.

Compose: 1.5.2
Swarm: Master Branch

**Comment by ekristen** [comment]
Ok the problem is that while I want it to use the `certs` because it is going through swarm, it doesn't find a match because the container is returned as `node/certs`

**Comment by aanand** [comment]
You can't have multiple containers with the same name, even across a swarm. What you're trying to do is not really possible with Compose at present, but to implement it properly, we would first need Swarm to add some kind of "pod" concept for co-scheduled groups of containers.

**Comment by ekristen** [comment]
I'm not sure we need pods. I think that it should look for the container name, minus the host and essentially use that as a constraint of where to deploy.

I would be ok with container volume support in compose too, where it just creates the container instead of trying to run it for data only containers.

**Comment by ijc** [comment]
Issue grooming: Closing as stale, sorry this was never really addressed.
