### ISSUE TITLE
Support environment variable substitution in the value of `privileged:`

### ISSUE THREAD

**Issue by jamshid** [docker/compose#2539]
Is there a reason environment variable substitution doesn't work in the value of `privileged`?
```
$ env SOCAT_PRIVILEGED=true docker-compose up -d
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Service 'socat' configuration key 'privileged' contains an invalid type, it should be a boolean
```
```
socat:
  image: bobrik/socat
  privileged: ${SOCAT_PRIVILEGED}
...
```
Maybe this is related to https://github.com/docker/compose/issues/2025. I guess an env variable is always treated as a string, can't specify a boolean value?

**Comment by dnephin** [comment]
That is correct, environment variables are always strings, and we have to apply them after the json is already converted to python types.  I'm not sure how we can handle something like that.

**Comment by dnephin** [comment]
I'm going to close this issue for #2730. It's the same problem, and I think #2730 addresses the more general case.
