### ISSUE TITLE
How I can install from the latest release?

### ISSUE THREAD

**Issue by DJviolin** [docker/compose#2555]
I have this script which is installing docker-compose on my CoreOS: https://github.com/DJviolin/LEMP/blob/master/install.sh

How I can curl the latest version? I use the command from here the release page.

**Comment by dnephin** [comment]
By latest do you mean `master` or "the last release" ?

We publish a master build to https://dl.bintray.com/docker-compose/master/ which you can download. This is documented here: https://docs.docker.com/compose/install/#master-builds

If you want the last release, there is unfortunately no latest tag on github, but you should be able to use the github api to query for the list of releases and just take the most recent.

**Comment by DJviolin** [comment]
Thank you the explanation! Yes, I wanted to get the latest release. I look after this api.

**Comment by shin-** [comment]
If you want the latest release, I would say hit `https://github.com/docker/compose/releases/latest`, which should redirect you to a URL containing the latest release number (currently `https://github.com/docker/compose/releases/tag/1.5.2`) - after that, you can simply curl `https://github.com/docker/compose/releases/download/$LATEST_TAG/docker-compose-Linux-x86_64` to get the binary you need.

HTH.

**Comment by DJviolin** [comment]
@shin- This is good idea. Can you help me in regex how to copy out `1.5.2` from the url?

**Comment by shin-** [comment]
This works for me: `sed -r 's/.*compose\/releases\/tag\/(([0-9]\.){2}[0-9])/\1/'`

**Comment by dnephin** [comment]
The bintray url is misleading, it's actually https://dl.bintray.com/docker-compose/master/docker-compose-Linux-x86_64 (without the colon).

**Comment by DJviolin** [comment]
@shin- Thank You!

**Comment by DJviolin** [comment]
@dnephin Is this the actual executible which I need to copy in place and rename it to `docker-compose`?

**Comment by dnephin** [comment]
Yes

**Comment by DJviolin** [comment]
Thank You for your help guys! Here is my final bash script which is setting up my LEMP stack: https://github.com/DJviolin/LEMP/blob/master/install.sh
