### ISSUE TITLE
Add parameter to docker-compose.yml to require a minimum version

### ISSUE THREAD

**Issue by schmunk42** [docker/compose#2557]
We have an application template with `docker-compose.override.yml` files. 
If a user with `docker-compose < 1.5.0` tries to start it, it breaks.

The stack basically starts, but volumes settings for local development are missing and the user gets unrelated errors, see https://github.com/phundament/app/issues/191 for an example.

This may be also very useful for all the new features like networking and volumes, which are also planned for compose.

**Comment by aanand** [comment]
Yep, we're planning exactly that. See #2421 for a start on implementation.

**Comment by kleijnweb** [comment]
+1 Ran into this with variable expansion. Looking forward to PR being merged :)

**Comment by tkruse** [comment]
+1

**Comment by aanand** [comment]
Closing as we've now added a [`version` key](https://docs.docker.com/compose/compose-file/#versioning) to the Compose file format.

**Comment by schmunk42** [comment]
@aanand I had trouble with networking aliases, when I was using `1.6.0`, with `1.6.2` everything works fine.
My feature request was more about `docker-compose` itself not the YAML file.

**Comment by aanand** [comment]
I see the use case, but I don't think we should couple the Compose file format to the `docker-compose` tool.

The Compose file format is a de facto standard - there are already multiple tools out there which support it - so it doesn't make sense to make assertions about what implementation a given file should be run on.

**Comment by schmunk42** [comment]
I see your point. But what's about something like a label or extra data section?

Just a rough draft:

```
version: "2"
services:
   [...]
labels:
   com.docker.compose.min_version: 1.6.2
```

Because ... to reduce errors, like described above, I need to use rather [unhandy bash scripts](https://github.com/phundament/app/blob/a66d683a6eac96abf9bdd1d6b65a5cc272832d08/build/scripts/requirements.sh#L44-L61).
