### ISSUE TITLE
the use of the -p flag should set COMPOSE_PROJECT_NAME value

### ISSUE THREAD

**Issue by CircleCode** [docker/compose#2565]
as I understand it, `-p` overwrite the project name, but if you use `${COMPOSE_PROJECT_NAME}` in your `docker-compose.yml`, it won't use the `-p` value

**Comment by dnephin** [comment]
Duplicate of #2565

**Comment by CircleCode** [comment]
duplicate of which? (#2565 is this one)

**Comment by dnephin** [comment]
Oops, I copied the wrong number! #2294
