### ISSUE TITLE
could not find jsonschema dependency

### ISSUE THREAD

**Issue by zinking** [docker/compose#2573]
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: jsonschema>=2.5.1,<3

[]$ pip list | grep json
jsonschema (2.5.1)

using python 2.6 on centos

**Comment by shin-** [comment]
Looks like your dependencies might be installed for a different version of python. What does the `pip --version` output look like?

**Comment by zinking** [comment]
d/ $ pip --version                                                                                                                                          [22:29:50]
pip 7.1.2 from /anaconda/lib/python2.7/site-packages (python 2.7)
d/ $ python                                                                                                                                                 [22:29:56]
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, Sep 15 2015, 14:29:08) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin

**Comment by anujmehra** [comment]
I am getting the same issue..

[root@Nagarro-temP openchain]# docker-compose up -d
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: jsonschema>=2.5.1,<3


Output for command: pip --version is
pip 7.1.0 from /usr/lib/python2.6/site-packages (python 2.6)

**Comment by thinhduckhoi** [comment]
Did anyone solve this problem?

**Comment by dnephin** [comment]
Make sure you're using  `pip > 6.0` and that pip is installing to the correct version of python (python2.x or python3.x) that you're trying to use. I believe those are the most common source of this problem.

**Comment by aecolley** [comment]
The fix is "sudo pip install --upgrade setuptools". Centos's setuptools provides a pkg_resources which cannot understand the dist-info files that pip installs from wheel files. A different fix is to use "pip install --no-binary :all:" for everything, to cause pip to install egg-info instead of dist-info.

However, it's somewhat moot as Compose seems to use Python2.7-specific syntax (specifically, dictionary comprehensions).
