### ISSUE TITLE
same error with all docker-compose commands 

### ISSUE THREAD

**Issue by handa-nishant** [docker/compose#2574]
$ docker-compose.exe up
←[31mERROR←[0m: A service can not link to itself: registration-service

$ docker-compose.exe --version
docker-compose version: 1.5.1

Here is what happened: 
I executed 'stop' and 'rm' to remove the services which were running however I got the same error.
Then I thought my docker compose might have gone to some unstable state and hence removed the containers by docker rm command. Even after doing this I'm not able to execute any of the compose commands and it keeps on throwing the same error with minimal info. registration-service is one of the services which was running earlier. Any ideas on how I can reset the compose?

**Comment by dnephin** [comment]
The problem is with your docker-compose.yml, not the containers. If you could paste the compose file here I can tell you what the problem  is.

**Comment by handa-nishant** [comment]
thanks @dnephin ... my ignorance, found the issue in my compose file as suggested.
