### ISSUE TITLE
DNS and DNS_SEARCH causes compose to error 

### ISSUE THREAD

**Issue by RafPe** [docker/compose#2581]
I have been trying to run simple container with adding dns servers like 

```shell
     dns: 172.17.0.1
```

and also 
```shell
     dns: 
       - 172.17.0.1
       - 8.8.8.8
```

In both cases I get the output from compose like 

```shell
ERROR: json: cannot unmarshal string into Go value of type []string
```

Docker engine is 

```shell
Containers: 6
Images: 180
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 192
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-30-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 3.36 GiB
```

and compose is just downloaded. 

Has anyone seen this before ?

**Comment by dnephin** [comment]
This is a bug in 1.5.2. It's fixed in master by #2527, however the second form you mention should work in 1.5.2 as well.

**Comment by RafPe** [comment]
@dnephin Hey you are right .. I dont know If I have messed with compose files but in deed the second way works now.

**Comment by dnephin** [comment]
Great, since this is fixed in master already, I'm going to close this issue.
