### ISSUE TITLE
Allow to specify subnet with docker-compose --x-networking

### ISSUE THREAD

**Issue by ashatrov** [docker/compose#2582]
When i use docker-compose --x-networking up it create subnet for each containers group (for each folder with docker-compose.yml) with 172.18.0.0/16, 172.19.0.0/16 .... etc.

In our office network we already have 172.18.. and I can not connect to these machines from containers.

I want to specify subnet when I start containers group with docker-compose --x-networking

**Comment by dnephin** [comment]
This is not something that is controlled by compose. It's up to the docker engine to decide on the subnet.

**Comment by ashatrov-lazada** [comment]
how can i use specify subnet if i use docker-compose?
Or I should not use it?

**Comment by dnephin** [comment]
I think specifying a subnet might already be supported by docker network create.

It will be supported by compose with the changes in #2478

**Comment by SimplicityGuy** [comment]
@dnephin Can you provide examples on how to use this in docker-compose? When I try the following with docker-compose v2 files:
```
networks:
  front-tier:
    subnet: 192.170.0.0/16
    gateway: 192.170.0.1
  back-tier:
    subnet: 192.171.0.0/16
    gateway: 192.171.0.1
```

I get an error:
```
ERROR: Validation failed in file './docker-compose.yml', reason(s):
networks.back-tier value Additional properties are not allowed ('subnet', 'gateway' were unexpected)
networks.front-tier value Additional properties are not allowed ('subnet', 'gateway' were unexpected)
```

**Comment by dnephin** [comment]
It's under ipam config: https://docs.docker.com/compose/compose-file/#ipam

**Comment by SimplicityGuy** [comment]
Excellent, this works perfectly. Thank you for pointing that out!

**Comment by nhatfield** [comment]
Hate to kick a dead horse here but any assist would be appreciated...what am i doing wrong?

    version: '2'


    ipam:
      driver: overlay
      config:
        - subnet: 192.160.0.0/16
          ip_range: 192.160.1.0/24
          gateway: 192.160.0.254

results in

    ERROR: The Compose file './management.yml' is invalid because:
    Additional properties are not allowed ('ipam' was unexpected)
    You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
    For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

docker and docker-compose version

    Client:
    Version:      1.9.0
    API version:  1.21
    Go version:   go1.4.3
    Git commit:   76d6bc9
    Built:        Tue Nov  3 19:20:09 UTC 2015
    OS/Arch:      darwin/amd64

    docker-compose version 1.8.0-rc1, build 9bf6bc6
    docker-py version: 1.8.1

**Comment by josefsabl** [comment]
Does not work in version 3.
