### ISSUE TITLE
Simple Cron-type scheduler 

### ISSUE THREAD

**Issue by patrick-bark** [docker/compose#2583]
I am trying to wrap my head around using Compose with containers that need to be routinely ran. In my application I have long running containers linked to routinely ran ones. There doesn't seem to be a simple way of doing this. I feel it would be very beneficial if Compose had a very minimal Cron-type scheduler for this purpose.

**Comment by dnephin** [comment]
This has come up before (#2424).

https://github.com/docker/compose/issues/2424#issuecomment-158134342 has some options about how you could accomplish this.

Unfortunately it's not really in-scope for compose.

**Comment by patrick-bark** [comment]
Those options all seem messy and against the grain of docker ideology. A long running container managing several cron tasks with their dependencies would be large and not "doing only one task". The other options are complex for something that should be simple. Lucj's suggestion of how that could look is a great idea, and a feature that would definitely be highly used. Compose is brings a serene level of simplicity to managing multiple containers, and should continue that approach to routine scheduling.

**Comment by dnephin** [comment]
I agree it would be nice to have an easier solution for scheduling, however it is out of scope for Compose. A service can easily be implemented external to Compsoe to provide this functionality.

**Comment by patrick-bark** [comment]
I understand your scope and your reasons for closing this, but there really isn't a simple solution to scheduling a single container while having it within the compose ecosystem. The scope of compose should be reconsidered with this regard. Not trying to be disrespectful, but this has honestly pushed me to looking into other solutions. Thanks

**Comment by andrewebdev** [comment]
Have a look at this project, it might just fit into your needs: https://github.com/mcuadros/ofelia

**Comment by nikeee** [comment]
Is this something that could be re-considered? I'm currently trying to avoid both k8s and putting scripts in Cron tab.
With k8s it is possible to define pods that will be started based on a cron-like schedule:
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

It would be awesome to have some kind of lightweight version of this in compose. It would simplify a lot for me, since I don't have to rely on other solutions on the same host for that. Maybe that would even be something to consider for swarm mode.

**Comment by andrewebdev** [comment]
The extra overhead for ofelia is very little, it's a small container that connects to your existing docker socket. It's really nice and scheduling your tasks directly in compose is wonderful. Ofelia is a wonderful project. I've been using it for years now, and it just works.
