### ISSUE TITLE
Volume path parsed as name

### ISSUE THREAD

**Issue by pcfreak30** [docker/compose#2587]
If you do

```
volumes:
- web/:/var/www/html
```
Then it will parse it as `web:/var/www/html` and create volume "web". The web folder does not exist beforehand. This was working in 1.7.

If you do

```
volumes:
- ./web/:/var/www/html
```
It works as expected.

**Comment by boombatower** [comment]
s|web/|web| problem solved.

See https://docs.docker.com/engine/userguide/dockervolumes/ for a page full of examples.

Even internally to your usage it's inconsistent since you do not have a trailing slash on /var/www/html

**Comment by dnephin** [comment]
This is by design: https://docs.docker.com/compose/compose-file/#volumes-volume-driver

**Comment by dmishh** [comment]
In my case in Mac OS X I needed to start volume directory name with `/Users/...`

> If you are using Docker Machine on Mac or Windows, your Docker Engine daemon has only limited access to your macOS or Windows filesystem. Docker Machine tries to auto-share your /Users (macOS) or C:\Users (Windows) directory. So, you can mount files or directories on macOS using `docker run -v /Users/<path>:/<container path> ...`

https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume
