### ISSUE TITLE
Running one-off container not working with --x-networking

### ISSUE THREAD

**Issue by kevinsimper** [docker/compose#2597]
It does not seem like it is possible to use `docker-compose run backend bash` when you have create your project with `docker-compose --x-networking up`

The error
```
ERROR: Cannot start container b65824c461a75d4cd7ced08b893ba521147eb1b60e64765933c0280654c7cd4f: Cannot link to /xx_xxx_1, as it does not belong to the default network
```

**Comment by dnephin** [comment]
You need `docker-compose --x-networking run backend bash`

**Comment by kevinsimper** [comment]
Yes, of course, did not think that you have to continue to use that command. Thank you!
