### ISSUE TITLE
Switch to boot2docker as recommended way to run Docker on OS X

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#26]
Probably blocked by https://github.com/steeve/boot2docker/issues/63, https://github.com/steeve/boot2docker/issues/84 and https://github.com/steeve/boot2docker/issues/85.

See https://github.com/noplay/docker-osx/issues/17 and https://github.com/noplay/docker-osx/issues/29 for more background.

**Comment by Gasol** [comment]
@ybrs Thank you, You have saved my life.

**Comment by nasht00** [comment]
I know this is a very old issue.
Are there any plans for Docker to work "out-of-the-box" on OSX? 
Without boot2docker or similar workaround?

**Comment by thaJeztah** [comment]
@nasht00 unfortunately at this point, I don't see that happening. OS X is not a Linux based distribution and simply doesn't have the kernel features that Docker relies on.

I know some maintainers looked into using the "Sandbox API" in OS X, but that didn't look sufficient

So, unless we see some major effort from Apple's side (like Microsoft is currently doing for porting to Windows), don't hold your breath.
