### ISSUE TITLE
Compose should use LF line break instead of CRLF on Windows

### ISSUE THREAD

**Issue by lmakarov** [docker/compose#2648]
## Issue

The following fails in Cygwin/Babun on Windows

```
$ docker inspect $(docker-compose ps -q cli)
Error: No such image or container: 605e85cc3dd1d6312760411e1719000c26255e2f27047508aec05c3c48314972
[]
```

If the id is copied and manually passed to the docker command then everything works:

```
$ docker inspect 605e85cc3dd1d6312760411e1719000c26255e2f27047508aec05c3c48314972
[
{
    "Id": "605e85cc3dd1d6312760411e1719000c26255e2f27047508aec05c3c48314972",
...
```
## Cause

On Windows `docker-compose` spits out `CRLF` for line breaks.
Unfortunately the Windows docker binary won't understand `CRLF`.

It's worth noting that when used in Powershell, the output from `docker-compose` still has the `CRLF` line ending, but is UTF-8 encoded. The docker binary reads the input correctly in this case.
## Workaround

Trim the `CR(\r)` character:

```
$ docker inspect $(docker-compose ps -q cli | tr -d '\r')
[
{
    "Id": "605e85cc3dd1d6312760411e1719000c26255e2f27047508aec05c3c48314972",
...
```

**Comment by ChristianUlbrich** [comment]
I suspect the issue is even worse, namely building images from docker-compose.yml seem to be broken, even though the Dockerfiles themselves have proper LF endings they somehow get converted to CRLF and that in turn breaks building them with docker on windows. But as I have said, I need to have deeper look at it...

**Comment by StefanScherer** [comment]
I assume that PowerShell cuts off the CR from the output before adding that the the commandline of the docker call. And the unixish shells Cygwin/Babun doesn't do that, so docker gets this character at the end of the container ID.

So who to "blame"?
* Does Cygwin/Babun something incorrectly in the Windows world not cutting of that char from Windows commands?
* Cutting off CR from any argument given in argv in docker doesn't seem to be a clean approach.
* Removing CR from the output of compose makes it "incompatible" with other windows tools. But I don't know if that would be a real issue as I don't know with other tool I should use with that output.

**Comment by awrgold** [comment]
In the .eslintrc file, under "rules", copy/paste the following (assuming your IDE is configured for windows line breaks:
```
"linebreak-style": ["error", "windows"]
```
