### ISSUE TITLE
limit fig log

### ISSUE THREAD

**Issue by pmlopes** [docker/compose#265]
if i create a container with fig and let it run and produce lots and lots of logs, when i execute:

    fig logs

for the first time it can take minutes to print all the logs (this is because I am running some development application in debug mode). I would like to have a feature like with tail, where I can specify the initial amount of lines say for example:

    fig logs -n 1000

which would print the last 1000 lines of the logs it could be either the last for each container or the total 1000, as long i can avoid the initial print of thousands of logs... that I am not interested in...

**Comment by imton** [comment]
Please?

**Comment by imton** [comment]
Bump :)

**Comment by clifton** [comment]
Bump

**Comment by thaJeztah** [comment]
There currently work in progress upstream in Docker to add support for limiting logs; https://github.com/docker/docker/pull/11485

**Comment by mnuessler** [comment]
+1 Really need it

**Comment by trsouz** [comment]
+1

**Comment by isuvorov** [comment]
+1

**Comment by abesto** [comment]
FWIW: +1

**Comment by ahmadnazir** [comment]
+1

**Comment by twistsm** [comment]
```
docker-compose rm
docker-compose up
```
that's will do the trick for you, guys

**Comment by aanand** [comment]
This would involve using the [logs endpoint](http://docs.docker.com/reference/api/docker_remote_api_v1.19/#get-container-logs) in `docker-compose logs`, as opposed to the [attach endpoint](http://docs.docker.com/reference/api/docker_remote_api_v1.19/#attach-to-a-container), but I think that's fine.

It would also only work for containers using the `json-file` logging driver, according to the API docs.

**Comment by abesto** [comment]
@twistsm `docker-compose rm && docker-compose up` drops volumes (including volumes for data containers), limiting the utility of this workaround :(

**Comment by hSATAC** [comment]
:+1:  for this.

**Comment by kevinsimper** [comment]
It can solved easy with a bash script like this

```
docker-compose ps | \
  awk '{print $1}' | \
  grep APPNAME!! | \
  xargs -I{} docker logs --tail=10 -f {}
```

**Comment by quantverse** [comment]
+1 for this

**Comment by lillesvin** [comment]
+1

**Comment by ezeql** [comment]
+1

**Comment by kolis** [comment]
+1

**Comment by snario** [comment]
+1

**Comment by gtron** [comment]
+1

**Comment by krasinski** [comment]
+1

**Comment by sukrit007** [comment]
+1

**Comment by erkie** [comment]
This issue makes `docker-compose logs` useless if you have to wait through 30 minutes of old logs to see what's actually going wrong. Is there a way to clear the logs daemon (or however it is implemented)? Without having to stop all services, rm and the up...

**Comment by Joshfindit** [comment]
Suggestion:

if `-f` is specified, automatically default to the last 10 lines.
Follows the usage of the `tail` command.

**Comment by jaequery** [comment]
if i wanted to just tail from end of the log, is it this? 

docker-compose logs -f --tail=1
