### ISSUE TITLE
Update docs on Swarm integration.

### ISSUE THREAD

**Issue by esmail** [docker/compose#2656]
The documentation on integration with Docker Swarm needs to be updated to reflect the new multi-host networking capabilities. The current page on [Docker Compose/Swarm integration](https://github.com/docker/compose/blob/master/SWARM.md) just states:
> ... links between containers do not work across hosts.

On the other hand, we see a basic example on the [Get started with multi-host networking](https://docs.docker.com/engine/userguide/networking/get-started-overlay/) page of the website.

**Comment by esmail** [comment]
The link at https://github.com/docker/compose/blob/master/SWARM.md goes to a 404.

**Comment by dnephin** [comment]
We haven't published the docs yet, they should be published in the next couple of days when the release goes out.
