### ISSUE TITLE
broken IPv6 port binding

### ISSUE THREAD

**Issue by DanielDent** [docker/compose#2663]
The documentation says ip:port:port. The following does not work:
    ports:
      - "2000:0000:60:1244::2:80:80"

The syntax may require clarification for IPv6 addresses, the colon operator has many meanings in this string.

**Comment by DanielDent** [comment]
Note: the [2000:0000:60:1244::2]:80:80 convention for dealing with this problem does not appear to be implemented.

**Comment by niieani** [comment]
Related docker issue: https://github.com/docker/docker/issues/11518 
And pull request: https://github.com/docker/docker/pull/20315

**Comment by sneak** [comment]
Currently compose uses docker-py to do the port specification splitting and the docker-py code for this also doesn't support IPv6 addresses yet: 

https://github.com/docker/docker-py/blob/master/docker/utils/ports/ports.py#L59

**Comment by lenovouser** [comment]
Any progress?

**Comment by niieani** [comment]
@lenovouser ask in the docker issue or the closed pull request I cited above.

**Comment by lenovouser** [comment]
@niieani did, but it seems like nobody is responding.

**Comment by niieani** [comment]
Not sure what else we can do. I'm not in charge here, I'm also waiting for an implementation ;)

**Comment by lenovouser** [comment]
@niieani yeah, same here. I was thinking about resubmitting it myself since @stapelberg doesn't seem to notice the comments but I am not a Go programmer so in case they want something to be changed after the review I won't be able to do it properly.

**Comment by niieani** [comment]
Now that the related features were merged to Docker Engine, can this move forward as well?

**Comment by LennardWesterveld** [comment]
Same issue here!

**Comment by chrisv2** [comment]
For anyone needing a solution right now without waiting for the PR to be merged, this can be fixed by patching docker/utils/ports.py:

```diff
--- a/docker/utils/ports.py
+++ b/docker/utils/ports.py
@@ -57,7 +58,7 @@ def _raise_invalid_port(port):
 

 def split_port(port):
-    parts = str(port).split(':')
+    parts = str(port).rsplit(':',2)
 
     if not 1 <= len(parts) <= 3:
         _raise_invalid_port(port)
```

**Comment by shin-** [comment]
Soft dependency on https://github.com/docker/docker-py/pull/1404

**Comment by kaiyou** [comment]
I believe the soft dependency was fixed a couple days ago, is there any other piece missing for this to move forward?

**Comment by shin-** [comment]
With the `docker-py` dependency updated, it'll be in the next release.

**Comment by niieani** [comment]
@shin- does that mean it's in [1.15.0-rc1](https://github.com/docker/compose/releases/tag/1.15.0-rc1)?

**Comment by JJ1LFC** [comment]
@shin- in which release is this supported?
