### ISSUE TITLE
Not able to run "docker-compose" command on CentOS

### ISSUE THREAD

**Issue by ghost** [docker/compose#2666]
I am getting following error when trying to run "docker-compose up -d": 

[root@N-temP openchain]# docker-compose up -d
Traceback (most recent call last):
File "/usr/bin/docker-compose", line 5, in 
from pkg_resources import load_entry_point
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in 
working_set.require(requires)
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: jsonschema>=2.5.1,<3

Output for command: pip --version is
pip 7.1.0 from /usr/lib/python2.6/site-packages (python 2.6)

Operating System: CentOS release 6.5 (Final)

**Comment by funkytaco** [comment]
I think it's saying you need jsonschema>=2.5.1

pip list | grep json

**Comment by dnephin** [comment]
Yes, the output of `pip list| grep json` should help debug this issue.

I'd also recommend using a virtualenv if you're installing with pip.

I don't think docker-compose supports python 2.6 anymore either. We only test against python 2.7.

**Comment by anujmehra** [comment]
Output of 'pip list| grep json' is as below:

[admin@N-temP ~]$ pip list| grep json
jsonschema (2.5.1)
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configu
ring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by dnephin** [comment]
Hmm, what about `pip list | grep functools32`, there's an issue where older versions of pip don't install it properly (Julian/jsonschema#233).

Also please note that the pip install is an "alternative" install method. The suggested install is the linux binary, and if you use pip install a virtualenv is suggested.  Compose is also not tested against python2.6 anymore, so it may not work at all. 

A python 2.7+ virtualenv is probably a good idea if you really need to install it with pip.

**Comment by anujmehra** [comment]
pip list | grep functools32 doesn't return any response.

**Comment by anujmehra** [comment]
Also, please share the link for deployment using linux binaries.

I am deploying by following the steps mentioned  in below URL:
https://docs.openchain.org/en/latest/general/docker-deployment.html

**Comment by dnephin** [comment]
https://docs.docker.com/compose/install/

functools32 missing is the problem, see Julian/jsonschema#233`, you need an upgraded version of pip

**Comment by hackeys** [comment]
below command should help you run with no issues :+1: 
pip install backports.ssl_match_hostname --upgrade
