### ISSUE TITLE
add command to list service names

### ISSUE THREAD

**Issue by TomasTomecek** [docker/compose#2683]
I've realized that `docker-compose ps` shows container names, instead of service names. Would it possible to provide a command which would show service names instead of container names? (I know I can open my compose file, but why would I do that? `docker-compose` is the interface for managing my project)

**Comment by aanand** [comment]
The new `docker-compose config` command does this if you pass `--services`.

**Comment by TomasTomecek** [comment]
```
No such command: config
```

Looks like I need to update :<

Thanks @aanand!

**Comment by aanand** [comment]
Yep, sorry - 1.6 RC will be out soon with the `config` command :+1:

**Comment by MorphyHu** [comment]
docker-compose config  --services

**Comment by skironDotNet** [comment]
`docker-compose service ls` would be easier to remember, would also follow docker convention like `docker network ls`
