### ISSUE TITLE
"ERROR: name is reserved" with docker 1.10rc1

### ISSUE THREAD

**Issue by jamshid** [docker/compose#2685]
Any idea why I keep getting this error trying to bring up a service? Had to upgrade to docker 1.10rc1 to try to workaround a bug. Did clean builds on a new 1.10rc1 server.
```
docker-compose version 1.5.2, build 7240ff3
Server Version: 1.10.0-rc1
```
```
socat_foo_console:
  image: bobrik/socat
  mem_limit: 50m
  links:
     - foo:foo1
  command: TCP-LISTEN:80,fork,reuseaddr TCP:foo1:90
  ports:
    - "7190:80"
```
```
docker-compose up -d
...
Creating example71_socat_foo_console_1
ERROR: name is reserved
```

```
systemctl status docker

Jan 18 10:30:23 docker110 docker[17741]: time="2016-01-18T10:30:23.228078648-05:00" level=warning msg="Your kernel does not support swap limit capabilities, memory limited without swap."
Jan 18 10:30:23 docker110 docker[17741]: time="2016-01-18T10:30:23.270394958-05:00" level=error msg="Handler for POST /v1.19/containers/create returned error: name is reserved"
```

**Comment by dnephin** [comment]
It looks like this might be a new error for "container name is already in use".

Could you include the output of `docker ps -a` and `docker-compose --verbose up -d`

**Comment by jamshid** [comment]
Thanks, let me know if this helps or if you need more info.

[verbose.txt](https://github.com/docker/compose/files/94714/verbose.txt)
[dps.txt](https://github.com/docker/compose/files/94715/dps.txt)

**Comment by dnephin** [comment]
hmm, it really is  failing on the create container call, but I don't see the name in use, so I'm not sure why it would fail. I think it's worth opening an issue on docker/docker, it looks like a bug in 1.10.

Please prefix the issue title with `[1.10]`

**Comment by mavenugo** [comment]
@cpuguy83 should have some details. This is originating from the new registratar.

**Comment by cpuguy83** [comment]
Can you paste your whole compose file?

**Comment by cpuguy83** [comment]
Also daemon logs (with debug) would be super helpful too!
Thanks!

**Comment by aanand** [comment]
This is an Engine bug, but also a Compose bug. I've filed an issue in https://github.com/docker/docker/issues/19444.

**Comment by aanand** [comment]
Fixed on the Compose side in https://github.com/docker/compose/pull/2698
