### ISSUE TITLE
[DX] Better error message when image for a service is not found

### ISSUE THREAD

**Issue by joelwurtz** [docker/compose#2691]
I feel very stupid but i just loose an entire hour trying to know why my docker wasn't working because i mix up `image` with `build` in my docker compose :/

In this case docker compose only say : `ERROR: 404 page not found` which is not very hepful.

Maybe catching this error and showing something like : `Image %s not found on any registry, did you mispell something ?`

**Comment by dnephin** [comment]
Could you include the commands you ran and the output you saw? I'm not sure when this error is happening.

**Comment by joelwurtz** [comment]
It's happening when running the `up` command:

```
$ docker-compose -p project -f projects/compose.yml up -d
Starting project_databasedata_1
project_database_1 is up-to-date
project_redis_1 is up-to-date
project_rabbitmq_1 is up-to-date
project_elasticsearch_1 is up-to-date
ERROR: 404 page not found
```

**Comment by cinemast** [comment]
+1 on this.

**Comment by shin-** [comment]
Should be fixed
