### ISSUE TITLE
Install command on releases page is missing -rc1 on release and may confuse users

### ISSUE THREAD

**Issue by luizgama** [docker/compose#2705]
curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

should be

curl -L https://github.com/docker/compose/releases/download/1.6.0-rc1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

**Comment by dnephin** [comment]
Oops, thanks for letting us know!  Just fixed it.
