### ISSUE TITLE
Recreating containers with different constraints fails

### ISSUE THREAD

**Issue by mustafaakin** [docker/compose#2711]
test.yml

``` yml
web:
  image: bfirsh/compose-mongodb-demo
  environment:
    - "MONGO_HOST=counter_mongo_1"
    - "constraint:node==pc3"
  ports:
    - "80:5000"

mongo:
  image: mongo
```

``` bash
$ DOCKER_HOST=pc0:2376 docker-compose -p counter -f test.yml --x-networking --x-network-driver overlay up 
```

Works fine first time. However, when I change contraint:node==pc3 to some other node, it fails:

``` bash
$ DOCKER_HOST=pc0:2376 docker-compose -p counter -f test.yml --x-networking --x-network-driver overlay up
Recreating counter_web_1
ERROR: unable to find a node that satisfies container==36fddea9aa8601763b4c1e42ea8db924e4444c185e4d0b3bbd63e4e698fb300b
```

I need to delete the container  on my own since I changed the host constraint, docker-compose rm does not delete the web container gracefully.

**Comment by brettdh** [comment]
I have the same issue, but changing constraints is not the trigger for me. Rebuilding the image triggers the same sort of failure on `up`. `docker-compose rm` followed by `docker-compose up` for that service works for me.

Thought I remembered seeing an issue resolved in 1.10 that sounded like this, but it still occurs.
