### ISSUE TITLE
scale and build do not work well together

### ISSUE THREAD

**Issue by schmunk42** [docker/compose#2721]
I have this `Dockerfile`

```
mrb:
  build: .
  environment:
    - affinity:container!=/mrb/
```

I run this against as swarm. The container should spread across nodes and should be built - not a common use-case, I know. But I tried to overcome issues with host-volumes.

I was able to get two containers up and running, but nonetheless building on a swarm and scale should at least trigger a warning, since you can't really ensure that all nodes have the same version of a built image.

```
docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:50:31 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   087e245
 Built:        
 OS/Arch:      linux/amd64
```

```
docker-compose version 1.5.2, build 7240ff3
```

**Comment by aanand** [comment]
Yes, this is a known issue with Swarm. For the time being, best practice is:

1. Build your image out-of-band with `docker build`
2. Push it somewhere with `docker push`
3. Use `image` to reference it in `docker-compose.yml`, instead of `build`

In Compose 1.6.0, you'll be able to use `image` and `build` together if you upgrade to the new file format, so it'll be a little better - you'll be able to write your services like this:

```yaml
foo:
  build: .
  image: username/imagename
```

You can still let Compose auto-build it for you when developing, and when deploying to a Swarm you can run:

```console
$ docker-compose pull # pull username/imagename onto all nodes
$ docker-compose up -d
```

**Comment by schmunk42** [comment]
I still don't get the use-case of using build and image together (there's another issue I can't find at the moment).

But to add my 2 cents here, isn't it totally confusing to use both, since it's very likely you won't end up with the same image when either pulling or building it?

About my use-case with building and scaling: We run reverse-proxies with SSL certs, which are deployed in a swarm. Rather than pushing it "somewhere" (private registry would be required) I'd prefer to rebuild them on all nodes, if I need to - but I want to make sure, that all nodes have an identical image. Using host-volumes is very hard in swarm and only considered as a workaround at the moment.

Maybe a cluster file-system would be the better option here, but that's another piece to the puzzle. The trade-off to re-building images would be OK for, since it's very fast and a well-tested native feature.

Another related issue https://github.com/docker/compose/issues/2305
