### ISSUE TITLE
docker-compose --version inconsistent

### ISSUE THREAD

**Issue by schmunk42** [docker/compose#2733]
I created a shell script to detect the minimum version of `docker-compose`.

I noticed that in 1.5.1 it looks like

```
docker-compose --version
docker-compose version: 1.5.1
```

while in 1.5.2...

```
docker-compose --version
docker-compose version 1.5.2, build 7240ff3
```

Which leads to a regex like

```
if [[ $(docker-compose --version) =~ version[:]?\ (.*)[,]? ]]; then
```

Is this platform dependent? Will the string format stay like in 1.5.2 future versions?

**Comment by dnephin** [comment]
`docker-compose version --short` will give you just `1.5.2`. That probably works better?

Future versions will continue to have the build sha in `--version`.

**Comment by schmunk42** [comment]
Sounds good, thank you!
