### ISSUE TITLE
Conflicting documentation for "links" in compose 1.6.0rc1

### ISSUE THREAD

**Issue by rajasaur** [docker/compose#2736]
Environment:
   Docker compose : 1.6.0rc1
   Docker client: 1.10.0-rc1
   OSX

Im trying to use the networking feature along with providing an alias to one of the services defined in the compose.yml file. The links section in  https://github.com/docker/compose/blob/master/docs/networking.md indicates that you could do this with the following snippet
```
version: 2
services:
  web:
    build: .
    links:
      - "db:database"
  db:
    image: postgres
```
however, this errors out with 
emerald:docker-symfony raja$ docker-compose -f test1.yml config
ERROR: Validation failed in file './test1.yml', reason(s):
Unsupported config option for 'services' service: 'links'

The documentation at https://github.com/docker/compose/blob/master/docs/compose-file.md#version-2 also indicates that links are not allowed but we should be using networking for communication between containers but the first link contains an example of using it (And I do need that feature since my code contains the alias for connecting to another container). 

Can you please clarify which one is correct and if there is a way to use alias names in links as before ?

**Comment by rajasaur** [comment]
It looks like the links related code got pushed only 3days ago (013c5ea3f99bfa64ce5f2dd1a67c0c746ef1598b) and I was using the pre-release docker toolbox (v1.10.0-rc1). 

Cloning docker compose repo and building it locally made the configuration pass. Now the docker-compose file is validated properly with links containing aliases. 

Im now stumped at another issue. When I try to docker-compose build or docker-compose up, I get this error:
ERROR: client is newer than server (client API version: 1.22, server API version: 1.21)

Are there any instructions to build docker-compose and its related tools (I suppose docker needs to be updated as well?) so that I can get past this error.

**Comment by dnephin** [comment]
Yup, the new links support was merged after RC1, it should be in RC2 if nothing changes.  You can also try a build of master from https://dl.bintray.com/docker-compose/master/

Compose file version 2 requires docker 1.10 (RC1 is out now). https://github.com/docker/docker/releases/tag/v1.10.0-rc1

**Comment by sikhote** [comment]
@rajasaur see this: https://github.com/docker/compose/issues/2111#issuecomment-174244657

**Comment by rajasaur** [comment]
Thanks @dnephin  and @sikhote . Building a boot2docker-legacy from source (to get over https://github.com/docker/docker/issues/19282) instead of the boot2docker.iso image mentioned in #2111 solved all my problems so far.. Closing this.
