### ISSUE TITLE
Proposal: Support `docker-compose push`

### ISSUE THREAD

**Issue by emilebosch** [docker/compose#2749]
I am running currently 1.6rc. I'm happy with the added build and image feature. But to be honest
its not of much because it doesn't fulfill the complete workflow with swarm.
- You can't push the images and therefore running them after building fails in a docker-swarm scenario. (they simply can't find the image) allowing a push would work.
- You have no control over on which server the images get build (i.e. one server can have much more ram for building than others).

Is there anywhere a roadmap i can see?

**Comment by dnephin** [comment]
Adding `docker-compose push` might be a good idea.

I think #2305 may cover the second point, we've added support for build args in 1.6.

**Comment by dnephin** [comment]
I'm going to rename this issue so that it addresses the first point. I don't think we have an issue open for it yet.

**Comment by emilebosch** [comment]
Well it seems that you guys added it <3 good jerb https://docs.docker.com/compose/reference/push/
