### ISSUE TITLE
feature request: high availability mode

### ISSUE THREAD

**Issue by pmlopes** [docker/compose#275]
Sometimes I would like to have a simple HA container, that in case it terminates with a status code other than 0 would relaunch with the same args it used before.

Imagine that you have a python/nodejs app and there was an exception, the node/python process dies and if the flag ```ha``` is true then fig would issue again a ```up``` command.

This would be a very simple HA feature but good enough for most of deployment scenarios...

**Comment by dnephin** [comment]
restart is now an option http://docs.docker.com/compose/yml/#working-dir-entrypoint-user-hostname-domainname-mac-address-mem-limit-memswap-limit-privileged-restart-stdin-open-tty-cpu-shares-cpuset-read-only-volume-driver
