### ISSUE TITLE
Compose support flow sequence written as a comma separated list within square brackets?

### ISSUE THREAD

**Issue by ruffsl** [docker/compose#2750]
I'm just testing a simple foo bar example using [variable substitution](https://docs.docker.com/compose/compose-file/#variable-substitution):

``` yaml
test:
  image: ubuntu
  volumes: ${FOO_BAR}
  command: ping 127.0.0.1
```

but am encountering this:

``` command
$ mkdir /tmp/foo
$ mkdir /tmp/bar
$ export FOO_BAR="['/tmp/bar:/bar', '/tmp/foo:/foo']"
$ docker-compose up
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Service 'test' configuration key 'volumes' contains an invalid type, it should be an array
```

Does compose support this YAML spec, or am I doing something improper?
http://yaml.org/spec/1.2/spec.html#id2759963
relevant context: https://github.com/NVIDIA/nvidia-docker/issues/39

**Comment by dnephin** [comment]
This is the same idea as #2730, only scalar strings are supported. You could set a single value, or have a variable for each, but you can't set an array in a variable.

**Comment by tiry** [comment]
This is indeed the same issue.
Looks like based on the `service_schema` jsonschema we could try an "automatic cast" after the interpolation.
