### ISSUE TITLE
Show a better error when handling an unsupported file format version

### ISSUE THREAD

**Issue by aanand** [docker/compose#2767]
1.  If the user specifies `version: 1`, they've misunderstood how versioning works and we should show a helpful error. Right now, we show this:

        ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

2.  When the user specifies a version that we don't support (e.g. `2.1`), we should perhaps show an error along the lines of "version 2.1 of the file format isn't supported by this version of Compose", so that we're a little more future-proof. The downside is that old code can't know if the version the user has specified is an actual version that exists or is just mistyped. Thoughts?

**Comment by dnephin** [comment]
I would omit "by this version of Compose", since that implies that it may be supported by some other version.

Something like "Unsupported compose file version: 2.1" 

Otherwise sounds good.

**Comment by aanand** [comment]
Closed by #2783

**Comment by plaindocs** [comment]
I'm getting this error, and don't fully understand it. 

I'm running a downloaded Dockerfile (https://github.com/danielquinn/paperless) on a Hypriot Raspberry PI (http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device). 

Docker file contains:
    
    version: '2'

Docker version: 

    $ docker info
    Containers: 1
    Images: 12
    Server Version: 1.9.0

I'm not sure if that image runs on ARM, but that is what I'm trying to find out. Any clues?
