### ISSUE TITLE
Build on top of or extend another service

### ISSUE THREAD

**Issue by CWSpear** [docker/compose#2773]
Is there a way to build an image based on another service, i.e. extend their `Dockerfile`?

For example, I have a PHP app that installs a bunch of deps on `build` and starts `php-fpm` on `up` called **php**, then a I have a separate container that runs migrations and clears caches, etc, called **app**. The thought is I can re-run **app** and keep **php** running to minimize downtime when I need to redeploy.

Currently, both images need all those deps, so I have to make sure those `RUN` directives in their Dockerfiles are mirrored, but ideally, I could build **app** on top of **php** and not have to do that. Is that currently possible or anything that others have interest in?

**Comment by dnephin** [comment]
The features has been discussed a few times (#295) also related is #1896

For your use case, I think you can use `docker-compose run` instead. `run` is designed to handle these adhoc tasks. For example: `docker-compose run php ./some/migration/script`

`up` is for running `services` which are long-lived, not for adhoc tasks.

**Comment by CWSpear** [comment]
Thanks for the response, but neither of those address the issue I'm trying to bring up. Maybe I'm not wording it right.

I basically want in my `Dockerfile` to `FROM` another service to extend the `Dockerfile`. The tickets you linked and the use-case you mention are for run-time dependencies. I'm talking about the build-time.

Basically a way to do `docker build -t my-php ./php/` then I could `FROM my-php` in my app's Dockerfile. Is there a way to do that sort of thing in a more clean, elegant way in `docker-compose`? (I mean, I'm thinking not at this point, but would it be something people might be interested in?)

**Comment by dnephin** [comment]
Sorry, my understanding was that the reason you wanted the ordering was to solve another problem, so I addressed what I understood was the original problem.

For build ordering see: #295 (I did link this one), #1455 (for context on why we probably wont support it), #610, and #583 for related requests.

The rest of my comment was in response to:
> For example, I have a PHP app that installs a bunch of deps on build and starts php-fpm on up called php, then a I have a separate container that runs migrations and clears caches, etc, called app. The thought is I can re-run app and keep php running to minimize downtime when I need to redeploy.

> Currently, both images need all those deps, so I have to make sure those RUN directives in their Dockerfiles are mirrored, but ideally, I could build app on top of php and not have to do that

I'm suggesting that build ordering might not be the best way to solve it. You could instead have just a single service (not two services), and use run to run the adhoc tasks (migrate, cache clean), since it uses the same code, and presumably the same service dependencies.

**Comment by CWSpear** [comment]
Heh, it was my turn to not read carefully. #295 is indeed relevant.

Ok, so yeah, I understand. In thinking about this more, I did try breaking it out to two services and sharing files via volumes. I think we can close the issue as duplicate. I think the one that drives home what I was looking for is [`image_from`](https://github.com/docker/compose/issues/610#issuecomment-61807456) (but still being able to adding to it with a Dockerfile... basically just prepending a `FROM this-newly-build-image` to the top).

Anyway, thanks for the replies. I'm going to go ahead and close as a duplicate.
