### ISSUE TITLE
Add support for tmpfs

### ISSUE THREAD

**Issue by cwolfinger** [docker/compose#2778]
In the latest release candidate for 1.6.0 the --tmpfs options is not available.  Is it possible to add this to the service definition via some other mechanism.

**Comment by Deshke** [comment]
and it is missing in the latest release and in the docs...

**Comment by 4alldigital** [comment]
would also like this as it was my main reason for updating to 1.10. To utilise better readonly environments and not have to expose /tmp directories to the host via volumes.  Any workarounds?

**Comment by ct-clearhaus** [comment]
@4alldigital 
> Any workarounds?

We have been running read only for quite some time and have `/tmp` as a volume when necessary. This is fine since we can accept a "fresh" `/tmp` (and we set the sticky bit in the start script of the app).
