### ISSUE TITLE
dns doesn't work on building

### ISSUE THREAD

**Issue by holymonson** [docker/compose#2788]
Hi, I set my DNS in compose file, and it works well when running containers. 
However, when using `docker-compose build` it won't set the dns, and in the building container dns is inherited from host machine. Is it an issue or expected behaviour?

**Comment by dnephin** [comment]
Expected behaviour. In the Compose file format v2 (coming with Compose 1.6) the `build` section will contain all the options that work for build (dockerfile, args, context), everything else only applies to `run`.

**Comment by holymonson** [comment]
Cool, thanks for your efforts!!
