### ISSUE TITLE
1.6.0rc2 can't find local images 

### ISSUE THREAD

**Issue by navinSing** [docker/compose#2793]
$ docker-compose up -d
ERROR: Error: image **library**/abc:3.0 not found

Why is it looking library tag?  

while the image was available on that machine.
running it with swarm and docker engine 1.9.1

**Comment by dnephin** [comment]
`library/` is the default namesapce for images. The error is saying that `abc:3.0` wasn't found. 

Please include the output of `docker-compose version`, `docker version`, `docker images abc`, `cat docker-compose.yml`

**Comment by navinSing** [comment]
$ docker-compose -version
docker-compose version 1.6.0rc2, build 695c692

$ docker -v
Docker version 1.9.1, build a34a1d5

$ docker -H=$SWARM_IP:2375    images abc:3.0

$ cat docker-compose.yml
cabc:
 image: abc:3.0
 volumes:
    - /mo/data/prod/db:/data/db
 ports:
   - 2314:2314
 command: "--start"
 labels:
  - "constraint:machine.name==v34"

NOTE : this is running on swarm:latest

on the nodes i can see the error message 
ERROR: Error: image library/abc:3.0 not found


where as on the host i can  
$ docker    images abc:3.0
INFO[0151] GET /v1.21/images/json?filter=abc%3A3.0      
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
abc                 3.0                 b11eedbc330f        2 days ago          317.4 MB


Tried with both docker-compose v 1.5.2 and 1.6.0rc2. With docker-engine 1.9.1. 
Since compose 1.6.0rc2 is compatible with 1.9.1, hence did not try 1.10.rc2; saw few thread but not working in my case :(

**Comment by dnephin** [comment]
You've created `abc:3.0` locally I guess, right? There's no way for that image to get onto the swarm cluster. You need to either push it to a registry (recommended), or you have to run the build on all the swarm nodes. 

This is a known issue with swarm, there is no way to propagate an image to the cluster after a build, the only way to do it is to `docker pull` which causes the pull to run on all nodes.

**Comment by navinSing** [comment]
will this get resolved with docker swarm v1.1.0-rc1
https://github.com/docker/swarm/releases/tag/v1.1.0-rc1

looks like it will support private repos
can we get it tested with docker engine 1.10 and swarm v1.1.0 and compose 1.6.0

thanks

**Comment by navinSing** [comment]
hi, quick q,, have we test'd registry on swarm with compose.. docker engine 1.10 and swarm v1.1.0 and **compose** 1.6.0. Is this tested ?

**Comment by navinSing** [comment]
Any updates?

**Comment by dnephin** [comment]
The short answer is yes.

**Comment by itzg** [comment]
FYI, I was able to resolve a variant of this scenario by applying the same Swarm constraint to both the build.args and the service's environment.

Given a Swarm cluster of three nodes, where only one has the daemon label `proxy_head=true`, this `docker-compose.yml` consistently worked for me, whereas before I was getting the "not found" error.

```yaml
version: '2'

services:
  app:
    build:
      context: .
      args:
        - "constraint:proxy_head==true"
    environment:
      - "constraint:proxy_head==true"
```

and my `Dockerfile` is:

```
FROM alpine

CMD tail -f /dev/null
```

**Comment by dnephin** [comment]
Ah yes, good point. #2305 was opened to see if we could do this automatically.

You can use build args and environment constraints to force the build and run to happen on the same node.
