### ISSUE TITLE
docker-compose with docker-swarm under docker-machine not mounting volumes

### ISSUE THREAD

**Issue by jlupox** [docker/compose#2799]
I have a working `docker-compose` example running a static html with `nginx`.

The directory tree:

    ├── docker-compose.yml
    ├── nginx
    │   ├── app
    │   │   └── index.html
    │   └── Dockerfile

The `docker-compose.yml`:

    nginx:
      build: ./nginx
      volumes:
        - ./nginx/app:/usr/share/nginx/html
      ports:
        - 8080:80

The `nginx` directory has the `Dockerfile`:

    FROM nginx

Everything is working right.

The problem is that I build a `Docker-Swarm` infrastructure with `docker-machine` following the Docker documentation: The `Local`, the `swarm-master` and `two nodes`.

Everything seems to work fine too.

    $ eval $(docker-machine env --swarm swarm-master)
    $[swarm-master]$ docker ps
    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                  NAMES
    d8afafeb9f05        few_nginx           "nginx -g 'daemon off"   20 minutes ago      Up 3 seconds        443/tcp, 192.168.99.102:8080->80/tcp   swarm-host-00/few_nginx_1

But `nginx` is returning a `Forbidden`

    $[swarm-master]$ curl http://192.168.99.102:8080/
    <html>
    <head><title>403 Forbidden</title></head>
    <body bgcolor="white">
    <center><h1>403 Forbidden</h1></center>
    <hr><center>nginx/1.9.10</center>
    </body>
    </html>

I enter into the `virtualbox` and into the `container`:

    $[swarm-master]$ docker-machine ssh swarm-host-00
    docker@swarm-host-00:~$ docker exec -ti d8afafeb9f05 bash

and nothing inside the `nginx/html` directory:

    root@d8afafeb9f05:/# ls /usr/share/nginx/html/

Version:

    $[swarm-master]$ docker version
    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 13:12:04 UTC 2015
     OS/Arch:      linux/amd64
    
    Server:
     Version:      swarm/1.0.1
     API version:  1.21
     Go version:   go1.5.2
     Git commit:   744e3a3
     Built:        
     OS/Arch:      linux/amd64

Is it necessary to do something different in `compose`/`swarm` for the `volumes`? Am I doing something wrong?

**Comment by schmunk42** [comment]
That's because only your local machine has the files, but not the **hosts** in the swarm. You would need to copy the files to your host(s) or build the image.

Starting from `v2` you can also define `volumes` in the compose file. Also, have a look at `docker volume`.

**Comment by dnephin** [comment]
I believe there will be a fix in docker 1.11 that will error when the host directory doesn't exist (instead of just creating it). That should make this problem more obvious to the user (since the error message will be clear about the problem).

**Comment by jlupox** [comment]
thanks @schmunk42 . But I'm building it. Do you refer to ADD the `index.html` into the `Dockerfile` directly?

**Comment by schmunk42** [comment]
Yes, I refer to `COPY` ;) https://docs.docker.com/engine/articles/dockerfile_best-practices/

About the configs ... I just played around with this, so please use it at your own risk. But I have a similar problem, where I need to move the config for several nginx proxies to the corresponding hosts.

At the moment I am copying the files over to the hosts, mainly because of https://github.com/docker/compose/issues/2721 - but that's also error-prone. If you have a single service, with a small build context (looks like you have that) - building the image for every config change should be fine.

**Comment by jlupox** [comment]
thanks a lot @schmunk42 . I will close the issue.
