### ISSUE TITLE
Docker-Compose terminal position commands may not work in PowerShell windows

### ISSUE THREAD

**Issue by PatrickLang** [docker/compose#2800]
If you run a command that uses cursor position commands - it works from a default CMD window but not if you launch a new PowerShell window.

Example command:

```
docker-compose.exe scale web=4
```

From CMD window:

![right](https://cloud.githubusercontent.com/assets/11345431/12727696/eb20f8dc-c8d2-11e5-8eb6-3b404bc9ce81.png)

From PowerShell window:
![wrong](https://cloud.githubusercontent.com/assets/11345431/12727699/ee8956ae-c8d2-11e5-81d4-303838eb7e3b.png)
Notice the control characters at the far left of the last line

**Comment by PatrickLang** [comment]
A few more notes on my setup:
* I'm running Windows Server 2016 TP4 - Server Core install
* All commands were run locally on that server

**Comment by shin-** [comment]
Closing to consolidate: #2095
