### ISSUE TITLE
Completion not properly installed with pip

### ISSUE THREAD

**Issue by wikier** [docker/compose#2810]
Even if the source contains [completion capabilities](https://github.com/docker/compose/tree/master/contrib/completion) for both `bash` and `zsh`, completion does not work when installing compose.

Debugging the issue I say the scripts are properly bundled via `MANIFEST.in`, but not moved to where expected (`/etc/bash_completion.d/docker-compose` in the vase of bash) during setup.

**Comment by dnephin** [comment]
https://docs.docker.com/compose/completion/

How are you installing compose? If you just curl the binary it's not expected that the completion scripts would be installed. You have to install them separately.

**Comment by wikier** [comment]
Ummm... I've installed it with `pip` (issue title updated). 

So checking the [documentation](https://docs.docker.com/compose/install/) I think from the pip section there is not step linking to the optional [completion instructions](https://docs.docker.com/compose/completion/). 

Then my fault, but could be linked for the alternative methods too.

Thanks!
