### ISSUE TITLE
Evaluate expressions in Shell

### ISSUE THREAD

**Issue by jimzucker** [docker/compose#2818]
Often you find that there are setting that can be derived from the ENV vs hardcoded in the yml file especially in development.  I am working on the containers for test and deployment of an open source project and I realized if I could set things in the yml file such as VARIABLE=`docker-machine ip sonar` or VARIABLE2=`docker-machine ip machine2` or UID=`id|cut -c5-7` could be very powerful to make yml lets static/env dependent (I saw another ticket about UID a few minutes ago).  If we took this approach it would solve alot env issues...

**Comment by dnephin** [comment]
I think we'd really like to avoid having to exec anything on the host. 

Configuration should be static, reading a config file shouldn't trigger a bunch of processes to run.  For one it needs to be executed on every single `docker-compose` command, which can greatly slow down every operation. 

You can always generate values ahead of time, and put them into environment variables, allowing them to be used in the Compose file.

If we do #2636 it would enable you to do something like this:

```
# Whenever you want to change your environment you run your script
./script/setup-env > docker-compose.env

# Now every docker-compose command can use the environment variables
docker-compose ...
```

This allows you to detach the two operations, which keeps things faster, and it removes the need for compose to exec anything on the host.

Even without #2636 you could do the same thing by having `./script/setup-env` export all the variables.

**Comment by jimzucker** [comment]
Today we can include an env file but it creates a lot of moving parts/files.  I had a setup like this but it feels like I would l just like to create a docker-compose.override.yml and have one file to maintain, adding  the script means I have 2 parts. Technically that works but it would be a nice user experience to have a single file that gets exec on the host anyway when you run compose, so adding the pre-processing is just a connivence...
