### ISSUE TITLE
Missing support for --shm-size

### ISSUE THREAD

**Issue by nubs** [docker/compose#2823]
Support for a configurable /dev/shm size was added in docker/docker#16168 as part of Docker 1.10 (API version 1.22).  I am currently running into an issue where I need a larger /dev/shm size in a project that is managed by docker-compose and I am unable to configure it when running containers via docker-compose.

It should be similar to fields like `mem_limit` for actual implementation.

**Comment by nubs** [comment]
I was attempting to knock this out myself, but ran into some roadblocks when trying to figure out how to get docker-compose to use my local development version of docker-py.  Is there some good documentation for making an update like this that has to be made in the docker-py library first?

**Comment by dnephin** [comment]
Here's what I do:

```
# If you don't have a virtualenv setup yet, create one
tox --notest
# activate the vritualenv, you can also use py34
source .tox/py27/bin/activate
# Install a dev version of something
pip install -e ./path/to/docker-py/checkout
```

Now any tests you run in that virtualenv will use your local `docker-py` checkout. `-e` means "editable" so you can make file changes to docker-py and see them immediately in the virtualenv.

**Comment by nubs** [comment]
Okay, I got a bit of an environment working.  I don't know python development tools well enough to feel super comfortable, but I was able to get some passing tests and things working locally for my problematic project.  I opened docker/docker-py#923 for the first part of this.

**Comment by sorrentinov** [comment]
Hi 
I've created a docker compose file to start oracle container using option shm_size: 2G
When exec docker-compose up to run container I receive "Unsupported config option for services.oracle: 'shm_size'"
This is my stack:
```
docker-compose version 1.6.2, build e80fc83
docker-py version: 1.7.2
CPython version: 2.7.11
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
```
I've not understand if this option already supported from docker-compose or not

Thanks in advance
Vincenzo

**Comment by nubs** [comment]
This is not in version 1.6.2.  You can try 1.7.0-rc.1 or wait for the final 1.7.0 to be released.

**Comment by sorrentinov** [comment]
Okay thanks.
