### ISSUE TITLE
False sharing between projects

### ISSUE THREAD

**Issue by jdmarshall** [docker/compose#2828]
I'm seeing false sharing of Docker layers while using Docker-compose that I can't reproduce by using Docker itself.  

Scenario: I have two projects, foo, and bar.  Both have a website served from an nginx container.  Since they work similarly, they have essentially the same project structure.  The only difference between them is the nginx root (/usr/share/nginx/foo vs /usr/share/nginx/bar) and the contents of /etc/nginx

Dockerfiles therefore look very similar.  In fact they're identical up until line 5 and this is the problem.

```
FROM nginx:1.9.9

RUN rm /etc/nginx/nginx.conf
COPY nginx /etc/nginx

COPY dist /usr/share/nginx/foo
```

and the second one: 

```
FROM nginx:1.9.9

RUN rm /etc/nginx/nginx.conf
COPY nginx /etc/nginx

COPY dist /usr/share/nginx/bar
```

If I build them via docker-compose, both images contain the sites-available for the first project I built, apparently because it erroneously assumes that the layer can be pulled from the cache of a different Dockerfile.

If I build them from docker, I see the expected behavior (ie, no sharing between the builds). I don't understand why this is different behavior from Docker, but this is clearly not what people would expect.

**Comment by aanand** [comment]
That's very strange. Compose currently has no caching logic: it simply makes a tarball of the build context and sends it to Engine, which decides whether or not to re-use layers based on the contents of the Dockerfile and any files that are to be copied in.

It sounds like the layer that's erroneously being shared is the one created by the `COPY nging /etc/nginx` command, yes?

It's conceivable that a bug in how Compose constructs the tarball could cause this to happen - for example, if we're not parsing `.dockerignore` correctly, then an important file that's different between the two projects could get omitted from both, causing an incorrect cache hit.

Given your project setup, is that a possible cause?

Also, what versions of Compose and Engine are you using?

**Comment by dnephin** [comment]
I really doubt this is a bug in Compose.

@jdmarshall do both projects have the `docker-compose.yml` in a directory with the same name?

I suspect what is happening is that the default project name (generated from `basename $project_dir`) is colliding for both projects. So it's not that the layers are being shared, it's that you're replacing the image from one project with the image from another project (because the image names are the same).

To fix this problem using Compose format v2 (available in Compose 1.6) you can use `image: ...` to name the image that is created by `build`, however you'll still run into problems when trying to run both projects at once. You'll see containers for one project replacing containers from the other (for the same reason).

I would suggest exporting `COMPOSE_PROJECT_NAME` environment variable to set it to something else.  #745 should make it easier to set a project name.

**Comment by jdmarshall** [comment]
Let me see if I can pull together a small repro case and post it up. 

Each project has a separate project name, so that's not it, but they do share the same suffix.  And yes, I'm thinking I'm seeing the directory copy operation being cached across projects.

**Comment by jdmarshall** [comment]
I was finally able to reproduce this scenario.  I'm afraid I may have left a few red herrings in the example, I can try to winnow it down for you if this is too many moving parts to identify the issue.

https://github.com/jdmarshall/docker-compose-issue-2828

**Comment by dnephin** [comment]
Thanks for the example. I tried it out, but I'm not seeing the behaviour you describe (it still just says one).

What do you mean by "'update' project one" ? I just added a new line to the Dockerfile, is that what you mean?

Could you include a paste with the output you get, and the output of `docker inspect` for the images and containers used by both projects?

**Comment by jdmarshall** [comment]
That was probably badly timed editorialization on my part.  In my repro I didn't even change anything.  

Not long after I posted this I found another manifestation of the problem but it was late and I was deep in trying to learn a new library so I didn't stop to document it. 

It is possible this is a driver problem?  I've always been fuzzy on how the file copy phase works, and maybe that's the issue.  I'm on boot2docker.  I can try another machine.

**Comment by dnephin** [comment]
Ok, I believe I tried without doing any updates either and couldn't reproduce it that way.

It's certainly possible that it's related to virtualbox shared folders.

**Comment by jdmarshall** [comment]
Newest info:  I haven't been able to reproduce this with the DO driver.  I'm guessing if I try it out on linux directly I won't be able to repro it either.  I am however finding all new sorts of ways this is breaking on boot2docker (in fact I got false sharing between this repo and my real one a few minutes ago.  argh).

At this point I would be happy to say "I should take this over to docker/docker" except for that nagging detail that the docker command line doesn't exhibit this behavior, only docker-compose.  Something must be different between the two.

**Comment by LaurentGoderre** [comment]
I am encountering the sane problem for two projects that have a Dockerfile that is identical but the content of the files to copy are different.
