### ISSUE TITLE
links hostname not being set after upgrading to 1.6

### ISSUE THREAD

**Issue by timothysu** [docker/compose#2834]
When an `app` has a link to `db`, `app` cannot reach `db` via the "db" hostname.  `ping db` fails from the `app` container, while `ping foldername_db_1` works.

**Comment by dnephin** [comment]
Please provide some more information about your setup:
* `docker version`, `docker-compose version`
* the commands you ran, and the output of the commands
* `docker inspect foldername_app_1`

**Comment by timothysu** [comment]
Resolved by upgrading the VM `boot2docker.iso` image from `v1.10.0-rc3` to `v1.10.0`
