### ISSUE TITLE
`rm` unable remove networks

### ISSUE THREAD

**Issue by crepererum** [docker/compose#2835]
# Abstract
`docker-compose rm` has a `-v` parameter to remove volumes associated with containers, but no `-n`(?) parameter to remove the network created by compose.

# Steps to reproduce
1. `docker network ls` to list current networks
2. `docker-compose up` on a version 2 compose.yml
3. press CTRL-C to kill the containers
4. `docker rm -rf`
5. `docker network ls`
6. the created network is still there (compare to step 1)

# Versions
Docker: 1.10.0
Compose: 1.6.0
Docker-Py: 1.7.0

**Comment by dnephin** [comment]
The `-v` on `rm` is actually "container volumes" which are a much older thing, it doesn't refer to "named volumes" which  are the things you can define in your compose file.

`rm` is only for removing containers. The command you're looking for is [down](https://docs.docker.com/compose/reference/down/). 

It supports removing the network, containers, and optionally volumes and images as well.
