### ISSUE TITLE
Running commands on services with Windows.

### ISSUE THREAD

**Issue by Mattnmoore** [docker/compose#2836]
Since interactive mode is not yet supported on Windows, is there any easy workaround for running commands on services the way you would with Linux?

For example: 
`docker-compose run web php -v` 

Thanks!

**Comment by smudge** [comment]
I just run something like this and use bash from within the container:

```bash
docker exec -it MY_CONTAINER bash
```

**Comment by 4gekkman** [comment]
I need this feature too.
All windows users a wating =)

**Comment by atrauzzi** [comment]
Yeah, would definitely like to see this working.

Would it be easy to enable this functionality if the person is running bash via msys2/msys on Windows?

**Comment by rodrigobaron** [comment]
I tried find one solution for this issue but unfortunately did not get results then i build one script. Check https://gist.github.com/rodrigobaron/64ea67f374b36db70542e6e3636c98b1

**Comment by colthreepv** [comment]
What are the drawbacks of this script, versus the *real* `docker-compose run` ?

**Comment by atrauzzi** [comment]
I have a different approach when doing "interactive" commands on Windows:

https://github.com/atrauzzi/laravel-drydock/blob/master/run.ps1

It doesn't make them interactive.  It just ensures that everything runs nice and cleanly.
