### ISSUE TITLE
Inconsistent `rm -v` `down -v` behaviour

### ISSUE THREAD

**Issue by kuhnroyal** [docker/compose#2838]
`rm -v` leaves data volumes in place and removes unnamed volumes (declared volumes from docker file).
`down -v` removes data volumes but leaves unnamed volumes, thus after `down -v` there are left over  volumes.
Docker: 1.10
Docker-Compose: 1.6.0

```
foo@bar: docker-compose up -d
foo@bar:$ docker volume ls -f dangling=false
DRIVER              VOLUME NAME
local               dcd2cd833c2336174e43550e9e43d77a47fcd4633a0b131cc99a511a72d1ee58
local               project_volume

foo@bar: docker-compose stop
foo@bar: docker-compose rm -vf
foo@bar:$ docker volume ls -f dangling=true
DRIVER              VOLUME NAME
local               project_volume
```

```
foo@bar: docker-compose up -d
foo@bar:$ docker volume ls -f dangling=false
DRIVER              VOLUME NAME
local               dcd2cd833c2336174e43550e9e43d77a47fcd4633a0b131cc99a511a72d1ee58
local               project_volume

foo@bar: docker-compose down -v
foo@bar:$ docker volume ls -f dangling=true
DRIVER              VOLUME NAME
local               dcd2cd833c2336174e43550e9e43d77a47fcd4633a0b131cc99a511a72d1ee58
```

So from what I understand the `down` command is supposed to cleanup everything, it should not leave the unnamed volumes.
Besides that, I think it is not intuitive for the `-v` switch to have different behavior on these commands.
I think `-v` should behave as it does now for `rm -v` and there should be an extra switch to remove data volumes.

**Comment by dnephin** [comment]
`down -v` should remove unnamed volumes. I just looked at the code and we're passing the exact same flag to remove them, I'm not sure why it's not working.  I'll see if I can reproduce.

**Comment by jgsqware** [comment]
I experience it today also. The `down -v`is not removing the unamed volume

**Comment by dnephin** [comment]
I'm unable to reproduce this issue. I'm seeing the unnamed volume is removed.

Could someone please provide a sample `docker-compose.yml` that exhibits the behaviour.  A sample output which includes the `docker inspect <container>` to show the volume id, and the `docker volume inspect <volume id>` showing it's still there , would also be great.

`docker volume ls` without an inspect showing the volume id could be misleading.

**Comment by dnephin** [comment]
The only way I'm able to reproduce anything like this is if I do this:

```
docker-compose down # or docker-compose rm
docker-compose down -v
```

Once the containers are removed (by the first `down` or `rm`) there's no way to track the volumes, so running `down -v` after that has no way to know about which volumes to remove.

Any chance this is what you experienced?

**Comment by kuhnroyal** [comment]
Could be, have to try tomorrow.

Besides that, what's your opinion about the second part? `down -v` removes named data volumes while `rm -v` doesn't.

**Comment by dnephin** [comment]
I think that's the expected behaviour. `rm` is only for removing containers, we added `down` to cleanup other resources (ex: named volumes).

There's some legacy there from when volumes only existed as part of a container, but I don't think we should carry it forward.

**Comment by kuhnroyal** [comment]
I think it's a bit dangerous to delete named data volumes without asking confirmation.

**Comment by kuhnroyal** [comment]
@dnephin You are right, I probably ran `rm` first.
What do you think about asking for confirmation on `down -v`?

**Comment by dnephin** [comment]
I'm generally not really a fan of asking for confirmation

**Comment by kuhnroyal** [comment]
Me neither but named data volumes will probably be used like data-only-container and sometimes contain valuable data. It would be easy to override the dialog with a `-f` switch.

**Comment by triccardi-systran** [comment]
If the behavior is what's expected, then the `docker-compose rm -v` documentation should explicitly say it will only remove unnamed volumes, and thus keep named volumes (created by compose or externally).

Currently it only says `Remove volumes associated with containers` and the documentation of `docker-compose rm` says `By default, volumes attached to containers will not be removed.`.

Are `attached` and `associated` the same thing ? if yes, then we should use only one word. If not, then the difference should probably be explained.

**Comment by holgerreif** [comment]
One problem we run into is the following:
1. create a named volume with `docker volume create` 
2. run `docker-compose up -d` with the same volume listed in compose file
3. run `docker-compose down -v`
Now the volume created in step 1 is removed. This might not what you want.

However, if you do
1. run `docker-compose up -d`
2. run `docker-compose down`
3. run `docker-compose up -d`
4. run `docker-compose down -v`
Then the removal is probably what you want.

For `docker-compose down -v` there is no way to distinguish between the two cases.
I'm not sure what is the correct behaviour. 

At least a warning about the existance of the volume should be printed by `docker-compose up`.

Maybe even a flag for `docker-compose up -d` or an option to the volume declaration should allow to fail if the volume preexists as an indication the we have some unclean, possibly unwanted situation. 
(I'd even prefer the other way round -- a flag allowing the use of a prexisting volume -- however this would break the current behaviour)

**Comment by kuhnroyal** [comment]
Just define the volumes with`external: true` in the file.

**Comment by aanand** [comment]
I've opened a PR to clarify the behaviour of `rm` and `down`. Feedback from anyone here who's found them confusing is very welcome: https://github.com/docker/compose/pull/3303

**Comment by danieldram** [comment]
I can't seem to remove my mongo volumes either..

**Comment by jkryanchou** [comment]
I recommend u to read about this guide which may help u figure it out. 
ref: https://gist.github.com/bastman/5b57ddb3c11942094f8d0a97d461b430
