### ISSUE TITLE
Using docker-compose with multiple configuration files disables network_mode: "host" for services

### ISSUE THREAD

**Issue by pjorquera** [docker/compose#2840]
When using docker-compose (v1.6) with multiple configuration files with "-f" like the following:

docker-compose -f docker-compose.yml -f preproduction.yml build
docker-compose -f docker-compose.yml -f preproduction.yml up -d

If services are using network_mode: "host" then this configuration is disabled (dropping to "bridge" mode)

**Comment by dnephin** [comment]
I think it's unlikely that using two files causes it. It's more likely that there's a conflict with another option in the compose files.  Please include the contents of those two files or a minimal reproduction we can use to try it out.

**Comment by dnephin** [comment]
Thanks for the bug report!
