### ISSUE TITLE
Add a way to reuse containers when using run

### ISSUE THREAD

**Issue by atrauzzi** [docker/compose#2864]
Right now when I specify a service when doing `docker-compose run`, it creates a new container based off the original. 

I feel like there's a missing flag to run a process in the existing service's container.  If I'm doing one-off commands that require setup steps, sequential runs of `docker-compose run` are effectively run in fresh copies of the service.

**Comment by dnephin** [comment]
Containers are meant to be ephemeral so using a new container for each makes sense.

#2023 (#593) is being worked on for `exec`
