### ISSUE TITLE
Log stream breaks on container restart for service

### ISSUE THREAD

**Issue by jmreicha** [docker/compose#2865]
I was experimenting with the `restart: always` option and noticed that if a container exists unexpected and restart if you are tailing all of the logs `docker-compose logs` that the log stream breaks for the container that has has issues.  Other log streams continue working.

**Comment by dnephin** [comment]
Thanks for the bug report!

This is indeed an issue, we're tracking it in #1115 (you can see another related issue in #2700).

**Comment by dnephin** [comment]
@bfirsh @aanand any chance this is the source of the "missing logs" you've heard about?

**Comment by jmreicha** [comment]
@dnephin Thanks, I'll track it there.
