### ISSUE TITLE
Possible docker-compose config issue?

### ISSUE THREAD

**Issue by jmreicha** [docker/compose#2867]
Would it make sense to have `docker-compose config` return a warn or error if the hostname is set to the same name as the service?

**Comment by dnephin** [comment]
I'm not sure what you mean.  The default hostname is actually the container id, so setting the `hostname:` to the service name should be fine. Why would it warn?

**Comment by jmreicha** [comment]
I was thinking would be unnecessary to set the hostname if it is the same as the service name?

I didn't realize that the container ID gets used by default.  Nevermind, nothing to see here...
