### ISSUE TITLE
Clarify how 'depends_on' considers a service 'ready'

### ISSUE THREAD

**Issue by brunoborges** [docker/compose#2868]
The documentation is very unclear about how `depends_on` will work. Currently, it does not say when a service is considered "up and running" to proceed with startup of its dependees.

**Comment by dnephin** [comment]
That's not really how `depends_on` works. It does exactly what the docs say, it defines an order, but does not perform any kind of healthcheck.

**Comment by brunoborges** [comment]
So we are back at using process startup delay?

**Comment by dnephin** [comment]
Yes, `depends_on` was never meant to implement health checks, apologizes if there was something that implied it would.

In #374 I've commented a few times (https://github.com/docker/compose/issues/374#issuecomment-157822991 is a good summary) that application health checks are application specific and don't need to be coupled to compose. I'm going to be working on some more documentation to show how to use existing tools along with Compose to solve the problem.

**Comment by chamerling** [comment]
Hi @dnephin,

While waiting for your documentation, can you give some links to these 'existing tools'
Thanks a lot

**Comment by dnephin** [comment]
* https://github.com/jwilder/dockerize#waiting-for-other-dependencies
* https://github.com/vishnubob/wait-for-it
* https://github.com/aanand/docker-wait/blob/master/wait
* (another example using `bash` and `timeout`) https://github.com/dnephin/docker-swarm-slave/blob/master/srv/swarm-slave/run#L17
