### ISSUE TITLE
docker-compose logs does not re-follow logs for restarted containers

### ISSUE THREAD

**Issue by dunk** [docker/compose#2870]
If you follow the logs in one window, and then kill and restart a container in another, then the first window will no longer get the logs of the (now running again) container. This is only an issue recently, since the addition of the (very useful) behaviour of not terminating the ```docker-compose logs``` command on termination of a single container. However, not re-following restarted containers means that a large number of people using this feature will run into the same thing that I did and be stumped for a while - probably blaming their own code. I think that this is the other half of that new behaviour, because without it you just have to kill and restart the ```docker-compose logs``` command anyways.

**Comment by dnephin** [comment]
Thanks for the bug report!

This is indeed an issue, we're tracking it in #1115

**Comment by curry684** [comment]
I don't think #1115 fixed this - I've just added some debug facilities to a container that makes it 'terminate' with an error when it detects code changes, but I have to restart the log tail still in Docker Compose 1.8.0 to see the logs of the restarted container.

**Comment by trollfred** [comment]
+1

**Comment by hadim** [comment]
Indeed I confirm this is not working on:

```
docker-compose version 1.25.5, build unknown
docker-py version: 4.2.2
CPython version: 3.7.6
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by ComfyDust** [comment]
Still seeing this in v2.15.1

**Comment by ComfyDust** [comment]
In v2.15.1 this still happens if there's only one service running.

**Comment by laurazard** [comment]
> In v2.15.1 this still happens if there's only one service running.

This is (for now) the expected behavior, and https://github.com/docker/compose/pull/10181 was done to align the V2 behavior with V1 (which also exits in this case). There can be a discussion about whether it makes sense to introduce a flag to keep following/never exit until the user stops the logs, but that shouldn't be the default behavior otherwise `compose logs -f` will get stuck forever and that would be a breaking change from V1.

**Comment by ComfyDust** [comment]
Makes sense. I'll open a feature request. Thanks for clarifying!
