### ISSUE TITLE
config option needs support -f

### ISSUE THREAD

**Issue by jianbin-netskope** [docker/compose#2873]
In docker-compose, it supports -f, --file option to use alternate compose file.  In the `config` option we would need that feature too.

```
docker-compose config 
ERROR: 
        Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?
        Supported filenames: docker-compose.yml, docker-compose.yam
```

**Comment by dnephin** [comment]
`-f` if a flag on the `docker-compose` command, not the subcommand.

https://docs.docker.com/compose/reference/overview/

```
docker-compose -f filename config
```
