### ISSUE TITLE
docker-compose up ignoring container_name

### ISSUE THREAD

**Issue by OferE** [docker/compose#2885]
Hi,

This seems like a bug.
The docker-compose up ignores the container name enry in the yml file.
the docker-compose build doesn't ignore it...

Thanks

**Comment by dnephin** [comment]
I can't reproduce this issue. `container_name` works correctly with `up`.

Also `build` never uses the container name.

Please provide an example of the problem you're having.

**Comment by OferE** [comment]
They both should use it... It makes no sense that only one does.
בתאריך 11 בפבר׳ 2016 20:04,‏ "Daniel Nephin" <notifications@github.com> כתב:

**Comment by dnephin** [comment]
How would you expect `build` to use a container name?

**Comment by OferE** [comment]
I see your point. I will get back with answer on Sunday. My env is not in
front of me.
Thanks for the replies!

On Fri, Feb 12, 2016 at 12:11 AM, Daniel Nephin <notifications@github.com>
wrote:

> How would you expect build to use a container name?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/compose/issues/2885#issuecomment-183080609>.
>



-- 
Regards,
Ofer Eliassaf

**Comment by OferE** [comment]
Hi,
This all issue is a mistake of mine. Sorry for the noise.

On Fri, Feb 12, 2016 at 1:37 AM, Ofer Eliassaf <ofer.eliassaf@gmail.com>
wrote:

> I see your point. I will get back with answer on Sunday. My env is not in
> front of me.
> Thanks for the replies!
>
> On Fri, Feb 12, 2016 at 12:11 AM, Daniel Nephin <notifications@github.com>
> wrote:
>
>> How would you expect build to use a container name?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/docker/compose/issues/2885#issuecomment-183080609>.
>>
>
>
>
> --
> Regards,
> Ofer Eliassaf
>



-- 
Regards,
Ofer Eliassaf

**Comment by rugk** [comment]
Sorry to wake this old issue up, but I do have the same issue. I have a service that uses both `build` and `container_name`.

> How would you expect build to use a container name?

@dnephin 
Well... I expect it to build the image, tag it with the content of the `image` (which it does) and then start the container with `container_name`.

My use case is to start two docker compose files (dev and environment) on the same machine.

All services do have the same name in both YML files.

---

What it instead does is somehow confusing. It uses the previously built container when I started the othe YAML file.

**Comment by rugk** [comment]
Okay, changing the service name fixes this. Or even better: Use [project names](https://docs.docker.com/compose/reference/envvars/#compose_project_name) to seperate everything.
