### ISSUE TITLE
Dealing with noexec /tmp

### ISSUE THREAD

**Issue by MikeH-Halo** [docker/compose#2886]
When running docker-compose with a /tmp filesystem that is set to noexec in fstab docker-compose fails with error message similar to: "error while loading shared libraries: libz.so.1".
In earlier versions of docker-compose we have worked-around this by setting TMP environment-variable to point to some other directory where noexec is not set, but this doesn't work anymore in 1.6.0.
Is there a suggested workaround for this?

**Comment by dnephin** [comment]
According to https://github.com/pyinstaller/pyinstaller/issues/1429 the libz.so.1 issue should have been fixed, and I can't find any record of it ignoring `TMPDIR` as described here: https://github.com/pyinstaller/pyinstaller/issues/1428#issuecomment-133414067 ?

We can try upgrading to pyinstaller 3.1.1 for the next bug fix release, to see if that fixes it.

**Comment by dnephin** [comment]
This upgrade is in master, you can try a build from https://dl.bintray.com/docker-compose/master/ to see if it works better.
