### ISSUE TITLE
No such file or directory on build (Windows 10)

### ISSUE THREAD

**Issue by adamiprinciples** [docker/compose#2895]
When I try to run docker-compose build for my api project, everytime without fail I get

`Step 6 : COPY dist/api.js dist/api.js`
`ERROR: Service 'api' failed to build: lstat dist/api.js: no such file or directory`

The file definitely exists. I've tried renaming it, moving it, almost everything and cannot get it to work. Everything works fine under OSX.

Any ideas?

EDIT: here is the relevant part of my dockerfile
```
WORKDIR /src
COPY package.json package.json
RUN npm install

COPY dist/api.js dist/api.js

Expose port
EXPOSE 3000

CMD ["npm", "run", "api"]
```

**Comment by dnephin** [comment]
It could be a problem with virtualbox shared folders. Try ssh'ing into the VM and checking to see if the path on the machine has that file.

Otherwise please include the relevant part of `docker-compose.yml` and the output of `tree` to show the files.

**Comment by shin-** [comment]
Gonna close this as it's been 3 months without activity. Feel free to open a new issue if you're still having problems.
