### ISSUE TITLE
`docker-compose rm` does not remove networks and images

### ISSUE THREAD

**Issue by omercnet** [docker/compose#2896]
When running `docker-compose up` for the first time it creates custom networks
When running `docker-compose rm` containers are removed but custom networks remain
app specific images are also left behind but that may be a separate issue

**Comment by dnephin** [comment]
That's right, it doesn't! That's why there is `docker-compose down`.

`rm` -> only containers
`down` -> containers, and networks by default, volumes and image optionally

**Comment by omercnet** [comment]
![](https://media4.giphy.com/media/xTiTno1ju4OXEUL5Sg/giphy.gif)
