### ISSUE TITLE
`docker-compose rm` on windows waits for y/N answer before the question is shown.

### ISSUE THREAD

**Issue by kmpm** [docker/compose#2897]
When I do a __docker-compose rm__ it just shows a new empty line and then nothing.
By trial and error I found out that the "Are you sure?" question doesn't display but it waits for input.
Look at the flow below...
```
$ docker-compose rm
y
Removing afdriftmysql_phpmyadmin_1 ... done
Removing afdriftmysql_db_1 ... done
Going to remove afdriftmysql_phpmyadmin_1, afdriftmysql_db_1
Are you sure? [yN]
```

I would expect the question to be asked before having to answer it.

* Windows 7 Pro x64
* docker-toolbox 1.10.0
* git 2.6.2 x64 from git-scm.com

**Comment by aanand** [comment]
Fixed in #3482. Thanks for reporting!
