### ISSUE TITLE
oom-kill-disable option not available

### ISSUE THREAD

**Issue by clkao** [docker/compose#2901]
(Follow up to #754)

This might be somewhat awkward option in docker-compose.yml, but perhaps a pass-through argument for `docker-compose run`?

**Comment by vultron81** [comment]
+1

**Comment by wlan0** [comment]
+1

**Comment by joshwget** [comment]
This would probably be a good option to include in a Compose file. I think there are use cases here for commands other than `docker-compose run`.

**Comment by s17t** [comment]
+1

**Comment by acefreakz** [comment]
+1

**Comment by yunlzheng** [comment]
+1

**Comment by gyscos** [comment]
Rergarding `docker-compose.yml` vs CLI arguments, the configuration file allows to only apply this setting to *some* containers, which can be desirable.

**Comment by jonesbusy** [comment]
+1

**Comment by lockie** [comment]
+1

**Comment by andyzasl** [comment]
+1

**Comment by jamshid** [comment]
Before anyone goes crazy trying to get oom_kill_disable to work, note that it is not supported by Compose 3.7 (3.x?) format yml's! You'll get an error like `Unsupported config option for services.myservice: 'oom_kill_disable'`.
The removal of this config option doesn't seem to be documented in:
https://docs.docker.com/compose/compose-file/compose-versioning/

**Comment by Shinoby92** [comment]
+1

**Comment by aiordache** [comment]
Hi! It should work with the latest version of docker-compose v1.27.x. Can you give it a try?

**Comment by Shinoby92** [comment]
seems like the error is that it doesn't work on docker stack deploy in swarm mode, could run it in compose

**Comment by limdingwen** [comment]
It works for me now. I'm using Docker Compose version 5.1.0.
