### ISSUE TITLE
docker-compose config should keep escaped variable

### ISSUE THREAD

**Issue by clkao** [docker/compose#2909]
`docker-compose config` prints processed yml with extend and variables resolved, however it is not keeping the literal dollar sign, making the output yml semantically different when feeding to `docker-compose` again.

```
web:
  build: .
  command: "$$VAR_NOT_INTERPOLATED_BY_COMPOSE"
```

becomes

```
web:
  build: .
  command: $VAR_NOT_INTERPOLATED_BY_COMPOSE
```

**Comment by teohhanhui** [comment]
This is important for a `docker stack deploy` workflow (as described in https://github.com/docker/compose/issues/4517#issue-209198870). Currently I have to fix the generated file manually.

**Comment by shin-** [comment]
#5054
