### ISSUE TITLE
BUG: C-p C-q should 'detach' from the container

### ISSUE THREAD

**Issue by d11wtq** [docker/compose#291]
Docker handles the key sequence C-p C-q as a way of detaching from the running container if you're inside a PTY. This means it closes the PTY, but leaves the container running, so you can re-attach later.

Currently if you do that in fig, you'll appear to have 'locked' your terminal until you press Ctrl-C. This is because fig includes a call to `client.wait(container)`, which will wait indefinitely on a detached session.

I'm not 100% what the correct approach is to fix this. I'm just documenting the issue and pointing to where the problem is.

**Comment by dnephin** [comment]
This has been open for a while and there's been very little interest in this feature, so I think we can close this.

I think the detach from `logs` or `up` is more compelling. Might be worth opening a new issue for that. I'd personally like to make that behaviour the default.
