### ISSUE TITLE
docker-compose 1.6 on ubuntu 14.04

### ISSUE THREAD

**Issue by kimptoc** [docker/compose#2914]
Hi,

I've upgraded the docker-engine package via apt-get and its using 1.10 now (had to a full remove/re-install to get that working - seemed to be spinning processing the old images/containers).

However docker compose is still v1.5.2 - is that to be expected?

Any thoughts on when 1.6 will be available for ubuntu 14.04

Thanks,
Chris

**Comment by dnephin** [comment]
> had to a full remove/re-install to get that working - seemed to be spinning processing the old images/containers

There is a migration required for the upgrade from 1.9 -> 1.10, see the top section of the release notes:  https://github.com/docker/docker/releases/tag/v1.10.0

> However docker compose is still v1.5.2 - is that to be expected?

Yes, that's expected. Compose is not included in the docker-engine deb.

See https://docs.docker.com/compose/install/

and #2235

**Comment by kimptoc** [comment]
Doh - couldn't find the previous install in my history, so assumed it was in the engine.

When I switched to root, I now see the previous manual install :+1: 

Many thanks!
