### ISSUE TITLE
Broken Link between Compose and Docker Docs

### ISSUE THREAD

**Issue by kojiromike** [docker/compose#2919]
https://docs.docker.com/compose/compose-file/#volume-configuration-reference says

    > See the docker volume subcommand documentation for more information.

The link https://docs.docker.com/engine/reference/commandline/volume/ is incorrect. In fact, there is no single "volume" command to reference, so I'm not sure what to suggest.

- https://docs.docker.com/engine/reference/commandline/volume_create/
- https://docs.docker.com/engine/userguide/containers/dockervolumes/ ?

**Comment by dnephin** [comment]
Thanks for the report. We have link validation for our docs, I'm not sure why this isn't caught.

cc @SvenDowideit

**Comment by dnephin** [comment]
Oh, maybe because the url is absolute, so it's not checked as part of link checking.

**Comment by dnephin** [comment]
Fixed by #2936
