### ISSUE TITLE
docker-compose logging shutdowns the service

### ISSUE THREAD

**Issue by navinSing** [docker/compose#2926]
the logger service (logstash) is running as part of compose, suddenly the web service dies, if configured with   

```
    logging:
     driver: gelf
     options:
      gelf-address: "udp://aa_ls-log_1:5514"
```

here is the logtrace at log service.

```
at [Source: [B@6133ced3; line: 1, column: 2]>, :level=>:warn}
{:timestamp=>"2016-02-16T00:54:23.716000+0000", :message=>"Error parsing json", :source=>"message", :raw=>"\\u001F\\x8B\\b\\u0000\\u0000\\tn\\x88\\u0004\\xFFT\\x91Oo\\xD4@\\fſ\\xCA*\\xE2\\u0000\\xA2Ɏ\\xE7\\u007Fr\\xA5=p@HUO\\\\\\\"\\x8FgҤM2K2\\xBB\\u0012B|w\\u001C\\u0015\\t\\xF0%\\xB2\\xE3\\xDF\\xF3ӛ\\x9F\\xD5-m\\xFB\\x94ת\\xAB\\xA0\\x81\\xEA\\xAE\\u001A\\xF3^\\xB8\\xB9ݾs\\xB3\\x8Fy+\\xFD\\x92\\xF6\\u001D\\x9F\\u0013OO\\\\XN\\x97-\\u0013Ϛ\\xBEL\\xF4\\xFA\\t\\xE79 \\xBD\\x9Eޯ9\\xA6\\xE6e\\xEF\\xB4\\xF6\\u001D\\xA8\\u000F\\xCC\\u000F\\xD7y\\xFE\\a\\xE7I\\x99X\\xAD\\xE0r\\xA9:h\\xB41\\xC6ka\\x8D\\u0002\\x9F>\\x8A\\xF6\\xAE\\x9A\\xD3-\\xCDU\\xA7\\u0018E\\x9A\\xE6\\xA9\\xFCૌ\\xF5\\x94\\x97\\u0005\\xD7\\xC8\\xDD9L\\xEBy\\u001FO5\\x9D\\u0002\\xF2\\xF7ݗ\\x87\\xA7\\x87\\xAF\\x8F\\xF7\\xFD\\xFD\\xE7\\xC7\\xF3v]{\\xBC\\\\\\x9A}|\\x83ւӚ\\xB6~:H\\u0003! @\\x8B\\xA1\\r\\xC2\\xCA6\\u0011E\\u0019\\x85\\x8BR\\v\\u001DT k]h\\u001D\\n7\\b \\xA9\\\"i\\xFE\\x97b\\u0014\\xA25I\\xD8\\xFF%W\\\\\\x8EH\\x96|}\\xE9\\x97\\\\S.5\\b.\\xE8\\x8F\\u0018{\\xDA\\u0012\\x96t\\x9C\\x95\\u0002l-d\\r\\xF6I\\x88N\\xBBN\\xF9\\xC68m\\u0004\\xE8o\\xC7\\xE6\\xB4p\\xB8o\\u000E\\xF7\\u0011\\xA5\\xB1\\x9D\\x8C.\\f\\xD6\\u0019aې\\u0006\\xF2\\xC6y\\x8F6\\u000EdH\\xA3\\xD51\\u001A\\xE9\\x94\\u0012\\xC1x\\t\\xD6j\\x92\\x9A\\u0000\\x82\\xF6\\xC4\\xEA\\xAF\\xEA\\u001F\\x93\\xD0\\xCA\\u0006\\xACo\\xA0Q\\xAA3l\\xF2L\\xB9^\\xF2\\xC6o \\xFD\\xB1]\\xF0\\x99\\x9DV\\xBF~\\a\\u0000\\u0000\\xFF\\xFFCu\\xC2u\\u0010\\u0002\\u0000\\u0000", :exception=>#<LogStash::Json::ParserError: Unexpected character ('\' (code 92)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@764305fa; line: 1, column: 2]>, :level=>:warn}
{:timestamp=>"2016-02-16T01:00:14.364000+0000", :message=>"SIGTERM received. Shutting down the pipeline.", :level=>:warn}
{:timestamp=>"2016-02-16T01:00:14.779000+0000", :message=>"UDP listener died", :exception=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:3682:in `select'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:77:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:50:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.0-java/lib/logstash/pipeline.rb:316:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.0-java/lib/logstash/pipeline.rb:310:in `start_input'"], :level=>:warn}
```

`{"message":"\\u001F\\x8B\\b\\u0000\\u0000\\tn\\x88\\u0004\\xFFT\\x90\\xCFn\\xD5<\\u0010\\xC5_%\\x8A\\xBEŇ\\xE8͵\\xC7\\u007F\\xE2dK\\xBB`\x81\x90\xAA\xAE\xD8Dc\xC7n\xDC\xC6\xF1%\xF6\xBD\b!ޝ\x89\x8A\u0004d\u0013\xCDh~\xE7\u001C\x9F\u001F\xED\xCD\xEF%\xE6\xAD\u001D[\xDE\xF1\xF6\xAE]r\xA94\xDCn_i(K\xDE\xEB\x94|)\xF8\xECi\xDBЇ\xB5\xB9\xEC\xD9Ѯ\x9Bjt\xAF\u001Fp]-\xBA\xD7\xE6\xFF-Ͼ{)\xA3\x94f\xE4\xE2\u001D\xF1Ắ\u007Fᴩ\x91\xD4_\xA6K;\xF2N_\xA5\x8C\u001E\fh>\xF8\xF7l\xB8kW\u007F\xF3k;\nB\xD1\xC55\xD6\xEF\xE4J\xD8\xE4rJ\xB8\xCD4\x9Dm\xDC\xCEeiN\xAE\xB1H\xFF\xFF>=<=|~\xBC\x9F\xEE?>\x9E\xF7\xEB6\xE1\xE5ҕ\xE5\r\xDA*\xC6\xCD\xEFS<H\\xC6\\xD8\\f\\xC1\\eo\\xDC\\xEC\\x91\\u0001p\\u001DX@\\u0013\\x84\\u000F\\f$\\xF4N:)B\\xE0腕\\x9A\\x99Ѓ\\u000F\\x80C\\u0018\\x9Cr\\u001A\\xFF\\x95\\xDC0\\u001D\\x95\\xA4|}\\x99R\\xCA\\xF5[\\x9E\\x8E\\xFE&\\xB7{\\xAC\\xFE\\xF0\\u0003\\xC6\\xF5\\x89\\xC1\\x89\\xEB'\\xC6G\\t#7\\u001D?\\u001E\\vB\\x99/\\xC7mL\\xD4\\xEB[\\xB8\\xB2 (=\\xC2\\xDC۠{\\xC5\\xF4`}pF\\xF5Ơ\\x9E\\u0003\\u0005\\x90\\xA8\\xE5<+\\xE8\\x85`V\\u0019J\\xAF\\xA5\\u0003\\xE98\\xB7\\xD28;\\xF4F\\x83\\xF8\\xA3\\xFA;\\u001F\\u001F\\xA0㚌;!FE\\u0015\\x9C]>\xA5\xBCS\xFD`\\x8E\\xEB\\x8Aϔ\\xB5\\xFD\\xF9+\\u0000\\u0000\\xFF\\xFF\\xB9\\v\\xFCh\\v\\u0002\\u0000\\u0000","tags":["_jsonparsefailure"],"@version":"1","@timestamp":"2016-02-16T01:43:00.326Z","type":"syslog","host":"192.168.1.34"}`

NOTE : `"tags":["_jsonparsefailure"]` 
looks like after this the service exits 

Is it the issue with docker-compose, where the logging is configured ? The web service suddenly dies. But it runs without any issue if no logging is provided. Node the log service did not restart.

> Why should the service stop ? , shouldn't there be a config to say ignore/ cache until up ?

Using docker-compose 1.6.0 and engine 1.10.0

// also the message is some encoded format, not sure if this is related to compose

**Comment by navinSing** [comment]
just confirmed 

by sending message from another non-docker source .. the source was able to send message correctly 

hence the message format below has got something todo with v2 compose logging.. pls fix asap .. 

`{"message":"\\u001F\\x8B\\b\\u0000\\u0000\\tn\\x88\\u0004\\xFFT\\x90\\xCFn\\xD5<\\u0010\\xC5_%\\x8A\\xBEŇ\\xE8͵\\xC7\\u007F\\xE2dK\\xBB\x81\x90\xAA\xAE\xD8Dc\xC7n\xDC\xC6\xF1%\xF6\xBD\b!ޝ\x89\x8A\u0004d\u0013\xCDh~\xE7\u001C\x9F\u001F\xED\xCD\xEF%\xE6\xAD\u001D[\xDE\xF1\xF6\xAE]r\xA94\xDCn_i(K\xDE\xEB\x94|)\xF8\xECi\xDBЇ\xB5\xB9\xEC\xD9Ѯ\x9Bjt\xAF\u001Fp]-\xBA\xD7\xE6\xFF-Ͼ{)\xA3\x94f\xE4\xE2\u001D\xF1Ắ\u007Fᴩ\x91\xD4\xA6K;\xF2N\xA5\x8C\u001E\fh>\xF8\xF7l\xB8kW\u007F\xF3k;\nB\xD1\xC55\xD6\xEF\xE4J\xD8\xE4rJ\xB8\xCD4\x9Dm\xDC\xCEeiN\xAE\xB1H\xFF\xFF>=<=|~\xBC\x9F\xEE?>\x9E\xF7\xEB6\xE1\xE5ҕ\xE5\r\xDA*\xC6\xCD\xEFS\xA5\xBCS\xFD\\x8E\\xEB\\x8Aϔ\\xB5\\xFD\\xF9+\\u0000\\u0000\\xFF\\xFF\\xB9\\v\\xFCh\\v\\u0002\\u0000\\u0000","tags":["_jsonparsefailure"],"@version":"1","@timestamp":"2016-02-16T01:43:00.326Z","type":"syslog","host":"192.168.1.34"}`

**Comment by dnephin** [comment]
I don't understand the issue here. If you're using `logging` your service is never actually connecting to logstash directly. It would just write to stdout.

Also from the logs you pasted it looks like it received SIGTERM, so it's not surprising that it shutdown.

Please include more information about your setup (`docker-compose.yml`, the commands you ran, etc).
