### ISSUE TITLE
Arguments are unquoted when provided with run.

### ISSUE THREAD

**Issue by matthewborden** [docker/compose#2937]
The `run` command when run with an executable and passed options with arguments (eg, `rspec -e 'closing all discussions'`, unquotes string arguments provided as options. Thus, when the command is interpolated by docker-compose `rspec -e 'closing all discussions'` is transformed to `rspec -e 'closing' all discussions`. It appears the docker-compose is unquoting the string and providing more arguments to the process than intended.

An example of this can be seen on docker-compose version 1.6.0, when running: `vagrant@dev:/vagrant$ docker-compose run superapi bash -c 'echo a b c'`. Nothing is printed.
Running `docker-compose run superapi bash` and proceeding to run 'echo a b c', works as expected.
When preforming the same command on earlier versions of docker-compose, the command prints 'a b c' as expected.

```
vagrant@stiledev:/vagrant$ docker-compose run publicapitest bash -c 'echo a b c'

vagrant@stiledev:/vagrant$ docker-compose run publicapitest bash
[root@b48e8159b9f3 app]# echo a b c
a b c
```

**Comment by jake-low** [comment]
Your example works for me.

```
$ docker-compose run runner bash -c 'echo a b c'
a b c
```

I thought it might be an issue with your shell (the host's shell, not necessarily bash), but I tried it under several shells and it worked as expected.

I'm running compose 1.6.0 (with docker-py 1.7.0) under python 2.7.

Can you provide more information about your environment?

**Comment by dnephin** [comment]
Closing since there was no response from OP
