### ISSUE TITLE
compose checks that the build context folders exist even when not needed

### ISSUE THREAD

**Issue by chaseajen** [docker/compose#2945]
In a docker-compose file where both `build` and `image` are specified, running `docker-compose up` will check that the build `context` folders exist, even if `docker-compose pull` is run first and the build contexts are not needed to run the services.

This seems like an unnecessary validation step, requiring empty build context folders that are not actually used.

**Comment by dnephin** [comment]
This is heavily related to #1973, I think we could just include it there.

**Comment by afirth** [comment]
It appears this also affects cases where only one service is required. e.g `docker-compose up service1` checks that all build targets for all defined services are available, even if service1 is standalone.

**Comment by MartinMuzatko** [comment]
I have the same problem with when I want to build or pull just **one** service. It requires me to create empty folders for **all the services**.

**Comment by MartinMuzatko** [comment]
No this is not stale. Still happening

**Comment by afirth** [comment]
somebody gives me a compose file. I want to use just one service. `docker-compose up service1` checks that all build targets for all defined services are available, even if service1 is standalone. Doesn't work. Just from memory since nobody has actioned this in 4 years. On the K8s :train2: now so /unsubscribe but thanks for all the fish.

**Comment by MartinMuzatko** [comment]
This is still an issue for us.
We have to maintain at least two compose files. One for building, one for starting. unifying that would be great.

**Comment by MartinMuzatko** [comment]
Damn. I'm learning python now to implement this. Hold my beer and un-stale this stale bot.
