### ISSUE TITLE
volume_driver in service config is unnecessary in v2 format

### ISSUE THREAD

**Issue by dnephin** [docker/compose#2960]
I believe `volume_driver` is only relevant for named volumes, so the driver would need to be specified in the `volumes` section, not the config section.

I think we can remove `volume_driver` from the service config for v2.

**Comment by dnephin** [comment]
Also need to update the docs here: https://docs.docker.com/compose/compose-file/#volumes-volume-driver

**Comment by aanand** [comment]
Makes sense.
