### ISSUE TITLE
docker-compose 1.6.0: Error:  Invalid Compose file version: 2

### ISSUE THREAD

**Issue by o1lo01ol1o** [docker/compose#2961]
Is there a configuration variable that could be causing a conflict?  Versions are all up to spec and related yml is minimal. 

```
$ docker --version
Docker version 1.10.1, build 9e83765


$ docker-compose --version
docker-compose version 1.6.0rc2, build 695c692
```

docker-compose.yml

```
version: '2'
services:
  rabbitmq:
      image: rabbitmq
```

**Comment by dnephin** [comment]
rc2 used integers for the version instead of strings. Upgrade to 1.6.0 (official release), and it should work.

**Comment by o1lo01ol1o** [comment]
Excellent, Thanks!
