### ISSUE TITLE
Some applications requires the container ip and the server name for (embedded DNS server) does not work

### ISSUE THREAD

**Issue by marceloamaral** [docker/compose#2968]
Hi,  I am trying to create a load balancer where tutum/haproxy will configure a nginx to do load balancing over some flask servers.

I am using multi-host network, thus instead of use links I need to define the environment variable by myself. Before, docker link was creating this env variable 
$SERVICENAME_PORT_$PORT_TCP=tcp://$CONTAINERIP

So, basically I need to provide this variable with the IP of the container running the service to container that requires that.

Via the example of multi-host cluster, they providing the service name to configure a webserver.
However, many applications, as tutum/haproxy relies on ips and does not accept the server name.

Does someone knows a easy solution for that?

**Comment by dnephin** [comment]
See https://github.com/tutumcloud/haproxy/issues/157#issuecomment-186142075

**Comment by shin-** [comment]
https://github.com/tutumcloud/haproxy/issues/157#issuecomment-195314876
