### ISSUE TITLE
copying files out of a container via stdout may corrupt them

### ISSUE THREAD

**Issue by justincormack** [docker/compose#2972]
Copying files from stdout out of a container using compose may corrupt the files, apparently only when combining build and run.

This basically does `docker-compose run -T default cat debian.iso > debian2.iso` ie copies the file out of the container via stdout, which should leave it unchanged. With `-T` it should not allocate a tty which I know may modify output (`docker run -it` does have issues doing this but without a tty it is fine.

To replicate, clone this repo `https://github.com/justincormack/composebug` and do `run.sh`. On my Linux machine I get the following output:

```
compose 1
Building default
-rw-rw-r-- 1 justin justin 389869735 Feb 19 19:10 debian2.iso
-rw-rw-r-- 1 justin justin 389869568 Feb 19 18:41 debian.iso
compose 2
-rw-rw-r-- 1 justin justin 389869568 Feb 19 19:11 debian2.iso
-rw-rw-r-- 1 justin justin 389869568 Feb 19 18:41 debian.iso
docker
Sending build context to Docker daemon 780.2 MB
Step 1 : FROM alpine:3.3
 ---> 14f89d0e6257
Step 2 : COPY debian.iso .
 ---> Using cache
 ---> b71467706501
Successfully built b71467706501
-rw-rw-r-- 1 justin justin 389869568 Feb 19 19:12 debian2.iso
-rw-rw-r-- 1 justin justin 389869568 Feb 19 18:41 debian.iso
```

The first copy of the debian iso has been corrupted.

This is on Linux:

```
justin@zander:~/composebug$ uname -a
Linux zander.myriabit.eu 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
justin@zander:~/composebug$ docker-compose version
docker-compose version 1.6.0, build d99cad6
docker-py version: 1.7.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
justin@zander:~/composebug$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
```

**Comment by dnephin** [comment]
The output of `build` is being sent to stdout, which is why you end up with extra bytes. In the docker example you are building separately, so it's not really an accurate comparison.`docker build` also uses stdout for the build messages, so I'm not really sure this is a bug.

I think an argument could be made that the build output should be sent to stderr, but not really a strong one.

 
```
docker-compose build
docker-compose run -T ...
```

works fine.

**Comment by aanand** [comment]
It is a bit annoying that `run` might arbitrarily decide to produce extra output on stdout. Maybe there should be a `--no-build` flag to guarantee that it won't?

**Comment by justincormack** [comment]
@dnephin ah ok that makes sense. My explanations were much more convoluted

@aanand no please no! build plus run is great, I don't want to split it!

I think the best option would be to add `-q` options to `docker-compose build` and (especially, maybe only?) `docker-compose run` that were like `docker-build -q` except redirected `stdout` of build to `/dev/null` rather than printing the sha which is not much use (maybe there should be a `docker build -qq`?)

**Comment by dnephin** [comment]
I think I'd prefer using `stderr` over any new flags, we'd have to add it to `build`, `run`, and `up`, and having a flag that only has meaning on `run` and `up` for a rare case when a build needs to happen is kind of weird.

**Comment by justincormack** [comment]
@dnephin yes, thats true, that would work too. So all build output on `stdout` would be redirected to `stderr` for `run` and `up`? (and `build`? or not as thats a bit different from `docker`)

**Comment by dnephin** [comment]
Yup, I think that should work, we could keep `build` using stdout

**Comment by justincormack** [comment]
Actually I have had a change of heart, and I am going to stop using `run` with implied `build`, as it doesnt rebuild containers even when they need rebuilding, which has caused much head scratching and annoyance. So makes this very low priority...

**Comment by extemporalgenome** [comment]
How does compose decide when to build and when not to? Is it race-y to run `build`, and then hope nothing triggers another build when `run` is immediately invoked afterward (in other words, are there any guarantees that a build won't immediately retrigger with run)?
