### ISSUE TITLE
Multiple v1 config files breaks logging

### ISSUE THREAD

**Issue by mhfrantz** [docker/compose#2974]
I don't think this is specific to AWS, but this is where I was able to repro.  Of the following scenarios, only "Two v1 config files" fails to generate the AWS logs output.  It does, however, run the command and produce no error messages.

The fact that it works with the "v2" config files means that it is probably either user error on my part or a Docker Compose bug.

```gherkin
Feature: Docker Compose awslogs driver

Background:
Given Docker v1.10.1
And Docker Compose v1.6.0
And the Docker daemon is configured correctly for the `awslogs` driver
And config file "a-v1.yml" like so:
"""
a:
  image: alpine
  log_driver: awslogs
  log_opt:
    awslogs-region: us-west-2
    awslogs-group: docker
  command: date
"""
And config file "b-v1.yml" like so:
"""
b:
  image: alpine
  command: date
"""
And config file "a-v2.yml" like so:
"""
version: '2'
services:
  a:
    image: alpine
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: docker
    command: date
"""
And config file "b-v2.yml" like so:
"""
version: '2'
services:
  b:
    image: alpine
    command: date
"""

Scenario: Single v1 config file
  When I run `docker-compose -f a-v1.yml run --rm a`
  Then I see the output in the AWS logs

Scenario: Two v1 config files
  When I run `docker-compose -f a-v1.yml -f b-v1.yml run --rm a`
  Then I see the output in the AWS logs

Scenario: Single v2 config file
  When I run `docker-compose -f a-v2.yml run --rm a`
  Then I see the output in the AWS logs

Scenario: Two v2 config files
  When I run `docker-compose -f a-v2.yml -f b-v2.yml run --rm a`
  Then I see the output in the AWS logs
```

**Comment by dnephin** [comment]
Thanks for the detailed bug report.  I'm not sure why only that one case would fail, it seems like it should be fine.  Where you able to run these cases multiple times to confirm that it's always the same case, and it;s not some race condition?

You can run the command `docker-compose -f ... -f ... config` to have it print out the merged config files, to confirm that is working as you expect. 

As far as the logging, I'm not sure what Compose would be doing to cause this.

**Comment by mhfrantz** [comment]
Thanks for the suggestion of using `docker-compose config`. It shows the problem.  Here is the v1 case, and you can see the logging information is missing:
```
$ docker-compose -f a-v1.yml -f b-v1.yml config
networks: {}
services:
  a:
    command: date
    image: alpine
  b:
    command: date
    image: alpine
version: '1'
volumes: {}
```
For reference, here is the v2 case:
```
$ docker-compose -f a-v2.yml -f b-v2.yml config
networks: {}
services:
  a:
    command: date
    image: alpine
    logging:
      driver: awslogs
      options:
        awslogs-group: docker
        awslogs-region: us-west-2
  b:
    command: date
    image: alpine
version: '2.0'
volumes: {}
```

**Comment by dnephin** [comment]
Ok, sounds like the bug is that `log_opts` and `log_driver` are not merged in v1 config.

**Comment by francisbesset** [comment]
I have the same problem.
A quick fix is possible?

**Comment by dnephin** [comment]
The workaround is to use v2 compose file format.

**Comment by francisbesset** [comment]
Thank you for your answer.
It is not better solution because the v2 format required the docker engine v1.10 and the changes in v1.10 are very important to adapt quickly my infrastructure.

**Comment by winggundamth** [comment]
+1 I have this problem too

**Comment by nickdgriffin** [comment]
+1

**Comment by benzhou** [comment]
+1, got the same issue with v1 format.

**Comment by iniweb** [comment]
@dnephin we need to spend a lot of time to rewrite and test v2 compose in our project, we have about 15 services with separate configs for volumes and logs...
