### ISSUE TITLE
Docker Compose within Docker container

### ISSUE THREAD

**Issue by devotox** [docker/compose#2989]
```
        volumes:
            - /usr/local/bin/docker:/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
```

This is possible and works very well but this below is not and creates an empty folder

```
        volumes:
            - /usr/local/bin/docker:/bin/docker
            - /usr/local/bin/docker-compose:/bin/docker-compose
            - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by dnephin** [comment]
It should work. `which docker-compose` ?

**Comment by devotox** [comment]
```
~/D/platform >> which docker-compose
/usr/local/bin/docker-compose
```

**Comment by devotox** [comment]
I have this same issue with docker-machine.

I am on OSX btw and installed with docker-toolbox if that matters

**Comment by dnephin** [comment]
I suspect it is because docker machine doesn't have `/usr/local` as a shared folder. The other files and directories are available from the linux VM, but the docker-compose binary is not because docker-machine only mounts your users home directory.

Your options are to either install docker-compose in the VM created by docker-machine, or to add another shared folder to the VM.

**Comment by aanand** [comment]
Even if you share the folder, the Mac binary isn't going to work inside a Linux container. So if you want to mount it in, the only viable option is to install docker-compose on the VM first.

But why mount it when you can just install it in the image for the container? It'd be as simple as:

```dockerfile
RUN curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
```

**Comment by devotox** [comment]
ok thank you i mean the Users home directory thing makes sense it just then seemed quite fortunate that docker itself could be run in the VM by being mounted ... wondered if docker compose could be.

but @aanand's way sounds perfect. so this is more than adequate
