### ISSUE TITLE
Handle booleans in environment/labels/extra_hosts

### ISSUE THREAD

**Issue by dnephin** [docker/compose#2993]
We've been warning when a boolean value is used in these fields because things like `y`, `yes`, `on`, `off`, are all converted to `True`, which is often not the intent of the user.

The warning says we're going to make it an error in the next release, so we should do that.

I think our options are:
1. make it an error
2. violate the yaml spec, and only accept `True`, and `False` as booleans, and treat everything else as a string.

**Comment by dnephin** [comment]
I think (1) is more correct here, deviating too far from the yaml spec is going to be very confusing.

@aanand , @shin- what do you think?

I'd like to pick this up tomorrow.

**Comment by aanand** [comment]
I agree that we should go with (1). It's very simple and clear to just say "this value should be a string".
