### ISSUE TITLE
depends_on services not started with "docker-compose run <service>"

### ISSUE THREAD

**Issue by conradkleinespel** [docker/compose#3000]
Hello,

With the recent Docker Compose release (1.6 I think), dependencies between services are defined with the `depends_on` configuration option. This is great !

However, in 1.5, you could `docker-compose run <service>` and all dependencies (links) would be started. This seems like it is no longer the case. Now I have to to `docker-compose up` and then `docker-compose run <service>` so that all dependencies are started properly for `<service>`.

The use case is to have one service that starts a shell with access to all other running services, without putting an SSH server into each separate service. Then I run `docker-compose run shell` and I instantly have a shell with access to all services.

Is there a specific reason for this? Am I doing something wrong?

Thanks for taking the time to read this.

Best regards, Conrad

**Comment by zwily** [comment]
I'm running into the same thing. If this is intentional, it seems to make `depends_on` not very useful.

Luckily, using `links` still forces the dependent services to run when doing `docker-compose run`.

**Comment by conradkleinespel** [comment]
@zwily Agreed ! In my case though, I'm using `network_mode: host`, which means I can't use `links`, because the two options seem to be incompatible.

**Comment by aanand** [comment]
I believe this is a duplicate of https://github.com/docker/compose/issues/2833 - there's a fix in https://github.com/docker/compose/pull/2893, which is already merged and will be out soon in Compose 1.6.1.

**Comment by conradkleinespel** [comment]
@aanand Ah yes ! Well, awesome. I might as well close this issue than. Thanks for your help !

**Comment by clkao** [comment]
It seems 367fabd wasn't in 1.6.2 so the fix is still not released.
