### ISSUE TITLE
Swarm documentation broken link

### ISSUE THREAD

**Issue by jeffkile** [docker/compose#3004]
The swarm documentation here: https://github.com/docker/compose/blob/master/SWARM.md was recently changed to point to this link: https://docs.docker.com/compose/swarm/ Which gives a 404 not found error

**Comment by jeffkile** [comment]
I think it should be linking to here instead: https://github.com/docker/compose/blob/master/docs/swarm.md

**Comment by dnephin** [comment]
We're going to publish the documentation today which will fix this link. The url is correct, we just need to publish the latest docs for Compose.

**Comment by aanand** [comment]
https://docs.docker.com/compose/swarm/ is now live.
