### ISSUE TITLE
docker-compose rm -f should kill and remove running containers?

### ISSUE THREAD

**Issue by marcosnils** [docker/compose#3007]
Sorry if this is a duplicate, tried a quick search and couldn't find anything. 

The default behavior of the docker daemon when forcing container removal is to kill and remove running containers as well. Compose doesn't seem to handle this and expects containers to be stopped/killed before removing. 

It'd be nice to do `docker-compose rm -f` instead of `docker-compose kill && docker-compose rm -f`

**Comment by dnephin** [comment]
```
docker-compose down
```
