### ISSUE TITLE
How to add a service to existing container without stopping current services

### ISSUE THREAD

**Issue by hcervantes** [docker/compose#3014]
I have one question regarding adding service to existing container.  How can I add a new service to my existing container without having to kill the currently running services?  Here is what I have in my yaml:
<pre>
postgis_native:
  image: mdillon/postgis:9.4
  container_name: postgis_native
  restart: always
  environment:
    - POSTGRES_PASSWORD=1FMp0stg1s
  ports:
    - "5432:5432"
  volumes:
    - /srv/postgis_native/data:/var/lib/postgresql/data

postgis_eGDB_100:
  image: mdillon/postgis:9.4
  container_name: postgis_eGDB_100
  restart: always
  environment:
    - POSTGRES_PASSWORD=1FMp0stg1s
  ports:
    - "5433:5432"
  volumes:
    - /srv/postgis_eGDB_100/data:/var/lib/postgresql/data
</pre>
and I want to add a different service to this file and start up that service.  When I issue the docker-compose up, I get an error saying 
> ERROR: Conflict. The name "postgis_native" is already in use by container 19c82d5ecbf7. 
> You have to delete (or rename) that container to be able to reuse 

My problem is that I cannot stop any of my current services.

Thank you!

**Comment by dnephin** [comment]
Do you mean "add a service to the Compose file" ?

Compose will take care of recreating containers for you, but I think your problem is that you created a container called `postgis_native` outside of Compose, and it doesn't have the labels Compose uses to find the correct container.  You'll need to either remove that container, or use a different name.

**Comment by hcervantes** [comment]
I just realized I goofed. The error says it all, 'The name "postgis_native" is already in use by container'
It was a copy and paste error, I did not change the container_name, just the service name.
docker-compose up takes care of it after fixing the error.
Thanks for responding.
