### ISSUE TITLE
exceptions while handling of exceptions

### ISSUE THREAD

**Issue by AvdN** [docker/compose#3015]
it is difficult to trace/debug what is wrong with one service not willing to be brought up because during handling of exceptions other exceptions occured. The latter one can be traced to the first line
of[ `log_api_error()`](https://github.com/docker/compose/blob/master/compose/cli/main.py#L89)
there `client is newer than server` (str) is not of the same type as `e.explanation` (bytes). 

I am not sure where the bytestring come from but probably from the failed http request results which IIRC are bytestreams. At least on 3.5.1 (what I am running docker-compose in) you need to do::

```
def log_api_error(e):
    expl = e.explanation
    try:
        if isinstance(e.explanation, bytes):
            expl = e.explanation.decode('utf-8')
    except:
        pass
    if 'client is newer than server' in expl:

``` 
After changing that, I was able to see and address the real problem

If you are running under Python 2.7 you will not see this problem and utf-8 encoding should not be necessary. In any case a failed decoding leads to the `in` test to be as good as the original

**Comment by AvdN** [comment]
This is the offending commit https://github.com/docker/compose/commit/79f993f52c9c2a358c48a9d0aea46fe832e7b167

new code introduced without any kind of unit test...

**Comment by AvdN** [comment]
And the actual command and stack-trace

[docker-compose-fail.txt](https://github.com/docker/compose/files/146040/docker-compose-fail.txt)

**Comment by dnephin** [comment]
@AvdN thanks for tracking this down. Can you reproduce this with 2.7, or is it just a 3.x issue?

**Comment by AvdN** [comment]
I cannot reproduce this any more, I am glad I got my server back up and running after 2 hours ( had to do `docker-compose rm` after seeing the real error properly.
AFAIK the html error message on 2.7 gives you a string (not unicode or bytes), just like subprocess.check_output() gives you a string on 2.7 and bytes() on 3.5.
Because it might not be easy to reproduce I suggest to write a fix in a defensive way, as I did. If 
you have to handle an API-error you should not be worrying about an extra test or two.

**Comment by dnephin** [comment]
I think we should address this by doing this TODO: https://github.com/docker/compose/blob/master/compose/cli/main.py#L91-L92 which will remove the need to parse the API error message

**Comment by AvdN** [comment]
I followed that link before, but I don't know know enough of compose to understand how it is related, or whether it would push the assumption that the false APIError .explanation attribute is a string to some other place where there is no unit test coverage for it.

Please consider doing something soon, even quick and dirty that is rewritten later on, as **any** APIError will trigger this bug if you are running compose on Py3.
I'm probably not representative but although I do have a bit of experience in using Python, I still completely missed that the original stacktrace that I attached did have the real cause displayed: not at the bottom or the top, but hidden in the middle where I had failed to look. That is why it took so long to get my container back up and running.
