### ISSUE TITLE
Make use of volumes created by docker volume

### ISSUE THREAD

**Issue by peperunas** [docker/compose#3017]
Is there any way to use data containers created through `docker volume create datacontainer`?

I'm quite afraid to use a "standard" data container since I just updated the image it was based upon and I lost my data.

[Docker volume documentation](https://docs.docker.com/engine/reference/commandline/volume_create/)

**Comment by dnephin** [comment]
Yes, use `external` https://docs.docker.com/compose/compose-file/#volume-configuration-reference
