### ISSUE TITLE
`extends` with both `image` and `build` now work: update `extends` doc

### ISSUE THREAD

**Issue by triccardi-systran** [docker/compose#3018]
[`extends` doc](https://docs.docker.com/compose/extends/) explains specific merge rules that apply to `image` and `build`:

> In the case of build and image, using one in the local service causes Compose to discard the other, if it was defined in the original service.

Since compose 1.6.0 and Compose File format v2 this limitation is not needed anymore because both `image` and `build` may be defined at the same time.
After testing it appears that `extends` has already relaxed this and merges with usual rules.

The documentation should be updated to reflect this.

**Comment by dnephin** [comment]
Thanks, yes we need to update the docs around this.

**Comment by aanand** [comment]
Updated in https://github.com/docker/compose/pull/3022
