### ISSUE TITLE
Late Binding Support

### ISSUE THREAD

**Issue by aleemb** [docker/compose#3043]
I have a `base.yml` and a `server.yml` which extends `base.yml`. If I define a network in `base.yml` and use it in `server.yml`, I get an error undefined network since it cannot find the network. The same thing happens with `args` and possibly others.

**Comment by dnephin** [comment]
Which version of Compose are you using?

Are you using the service `extends` keyword, or are you using multiple Compose files. `extends` does **not** extend an entire file, it only extends a single service, so it's not expected that these networks would exist.

If you're using multiple Compose files, there were some bug fixes in 1.6.2 that may have fixed it.

**Comment by aleemb** [comment]
Okay upgraded to 1.6.2 and thanks for clarification on network, makes sense.
