### ISSUE TITLE
Output logs then exit

### ISSUE THREAD

**Issue by breerly** [docker/compose#3058]
I'd like to be able to do something like:

```
docker-compose logs --exit
```

where the all the logs are displayed, and then the program exits w a 0.

Currently, the `logs` command blocks, which makes it difficult to use from CI.

Thoughts?

**Comment by dnephin** [comment]
This was just implemented in #2720 it is now the default.

You can check it out from a master build https://dl.bintray.com/docker-compose/master/

**Comment by breerly** [comment]
Has this made it's way into a release yet?

**Comment by dnephin** [comment]
Nope, it will be in 1.7
