### ISSUE TITLE
Add support for the --no-build concept to the run command

### ISSUE THREAD

**Issue by ebmeierj** [docker/compose#3085]
We currently have our docker images being built on commit and downloaded to a staging server where we run tests/qa them. When running tests it would be ideal if we could specify --no-build to ensure that all relevant dependencies have been built and retrieved successfully and to ensure that none are built locally.

Is there a reason this option does not already exist?

**Comment by ijc** [comment]
Issue grooming: Sorry nobody got to this at the time. It appears this was fixed at some point in the intervening years:
```
$ docker-compose up --help |& grep build
    --no-build                 Don't build an image, even if it's missing.
    --build                    Build images before starting containers.
```
