### ISSUE TITLE
How to install docker-compose

### ISSUE THREAD

**Issue by khoi-thinh** [docker/compose#3090]
Hi guys!
I'm working on CentOS 6.7 and want to install docker-engine and docker-compose just for some small tests. I installed docker-engine 1.7.1 and the version of docker-compose is 1.6.2
The point is after installing docker-compose using pip, i couln't check the version or using it.
Here's the output:
`[root@ip-10-0-7-77 ~]# docker-compose --version
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: jsonschema>=2.5.1,<3`

**Comment by villlem** [comment]
It looks like you dont have required version od jsonschema installed. It may happen if its installed via pip. The are corner cases where pip use wrong version if you already have some version installed.
Did you install docker-compose through distro respository or pip? 
Anyhow I strongly recommend to use "binary" install via (https://github.com/docker/compose/releases/tag/1.6.2).

**Comment by dnephin** [comment]
https://docs.docker.com/compose/install/

If you want to use `pip`, using `virtualenv` is highly recommended, but the binary install is the suggested method.

**Comment by thinhduckhoi** [comment]
When i installed docker-compose using binary, i still got error.
It said: Not found in usr/local/bin even though there was docker-compose in that folder.

**Comment by irfancode** [comment]
Issue still persist...

$ uname -a
Linux centoslocal.irfan.com 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: backports.ssl-match-hostname>=3.5
