### ISSUE TITLE
Improve this check for Windows users to allow interactive mode?

### ISSUE THREAD

**Issue by atrauzzi** [docker/compose#3096]
Take a look here: https://github.com/docker/compose/blob/1655be6c5bcbc35d2a34bd4c464b8a91981aaa42/compose/cli/main.py#L550

Is there any chance the check performed here could be refined so that if the user is running via cmder/conemu or another Windows terminal, interactive mode `run` isn't blocked?

I'm actually calling `docker-compose` from an msys2 bash terminal run via cmder.  Perhaps that's enough to satisfy what's needed for interactive mode?

**Comment by sergeyklay** [comment]
Yes, as far as I remember msys2 exports to global environment their own variables, eg version, color support, etc

**Comment by atrauzzi** [comment]
Related: https://github.com/docker/compose/issues/2836

**Comment by dnephin** [comment]
For anyone following this issue, there is a proposed fix in #3274. If you could test it out it would be much appreciated. Thanks!

**Comment by aanand** [comment]
Since #3274 didn't work, I'm closing this in favour of #3194.
