### ISSUE TITLE
Running multiple compose instances in Jenkins

### ISSUE THREAD

**Issue by formerlyKurt** [docker/compose#3100]
If I have a Jenkins job that runs `docker-compose up` to build an environment for testing, do I need to ensure that this job is run sequentially?  I'm wondering how to handle the fact that running compose up twice on the same compose file will result in port conflicts (if the second container even starts up).

Has anyone run into this before and how did you solve it?

Thanks!

**Comment by dnephin** [comment]
The environment can be isolated using the project name: https://docs.docker.com/compose/overview/#multiple-isolated-environments-on-a-single-host

Host ports are one exception. I would suggest not using host ports. If you need to use host ports for some other environment, you can apply them using a second compose file. In CI you shouldn't need host port at all. You can either have the tests run from a container, or query the docker API for the container ip address.

**Comment by formerlyKurt** [comment]
It all sounds lovely -- but not seeing it working @dnephin. :-/

I have used the COMPOSE_PROJECT_NAME in the environment section of the compose file:

    links:
      - postgresdb:db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - COMPOSE_PROJECT_NAME=app-${BUILD_NUMBER}

Even though I have the compose project name set, when the build number changes, I still see `docker-compose up --force-recreate` shutting down the previously running container instance.

I'm also not sure how to not assign ports.  It seems that I would need to tell my Postgres db which port to use and also put that port in the app's JDBC connection string for connection.  Because I have the db container linked, I don't think that I need to do anything special to get the IP address.

What am I missing here?

**Comment by formerlyKurt** [comment]
Okay, so the `COMPOSE_PROJECT_NAME` is an environment variable on the host not in the compose file.  So for each Jenkins project, I'd have to do something like:

`export COMPOSE_PROJECT_NAME=app-$BUILD-NUMBER`

in a shell script. Correct?

Now just need to figure out the multiple port issue.

**Comment by dnephin** [comment]
That's correct, setting the project name to the build number is a good idea.

You don't actually need to expose ports to have one container communicate with the other. If you just remove any `ports` section from the Compose file I think it should work.

**Comment by formerlyKurt** [comment]
Did you mean `container_id` as an environment variable?  How do you know the container id before running `docker-compose up`?

**Comment by formerlyKurt** [comment]
Looks like what I really need is to specify ports as `"8080"` then I can see the mappings when running `docker ps` and `docker port <container_id>`

It works...but is this the approved solution for scaling etc.?

**Comment by formerlyKurt** [comment]
Not sure that I'd want to use the IP address since if the host is restarted (as it could be at any point in time), then I'd have to go back and edit the compose file with the new IP address. That's not really going to scale in our CI environment.  Especially since the next step is to start up a swarm and run multiple containers on that swarm for testing purposes.

Thanks for talking me through this though @dnephin!  Much appreciated.

Now, I'm on to `swarm`...

**Comment by dnephin** [comment]
Yup, that's true. The lookup ip strategy only works if you don't plan on restarting containers.

Glad we could get this sorted.
