### ISSUE TITLE
Allow removing variables in child config

### ISSUE THREAD

**Issue by aleemb** [docker/compose#3111]
In my parent config I have,

```
- networks:
  - foobar
```

...but in my child config I don't want to use this network. I presumed I could pass an empty array in my child config but it threw an error:

```
- networks: []
```

**Comment by dnephin** [comment]
Right, values can be added or updated, but not removed.

To handle this case, you can restructure your config so that the base file has only things that are always used. Then you can have multiple override files for customizing the environment.

**Comment by aleemb** [comment]
Yeah, I have taken that route for now though I have multiple sites which already share a base and this means having to create a per-site base config then extending that for my dev and production variations.

No biggie though. I suppose overriding values would mangle the merging behavior which is just as desirable in other use-cases.
