### ISSUE TITLE
Deployment strategy : on every nodes

### ISSUE THREAD

**Issue by mfilotto** [docker/compose#3116]
Hi,
Would be nice to have the ability to give a container a deployment strategy of type : on every nodes.

**Comment by dnephin** [comment]
This is not something that Compose would be able to implement. It needs to be handled by the server, which is docker/swarm. 

There is an issue for this open already: https://github.com/docker/swarm/issues/1708

**Comment by schickling** [comment]
@mfilotto here are some interesting workarounds: https://www.reddit.com/r/docker/comments/40jo6s/docker_compose_swarm_have_same_containers_on_all/

**Comment by Typz** [comment]
This can be implemented with existing container constraints:

```
service:
    environment:
      - "affinity:container!=*service*"
```

This works well when starting the app (with `docker-compose up` or `docker-compose scale service=N`), but compose will fail when trying to use `docker-compose up` after images have been updated:

```
$ docker-compose up
creating app_service_1
$ docker-compose scale service=2
creating app_service_2
$ docker-compose build
Sending build context to Docker daemon
[...]
Successfully built a8b6ca53ce
$ docker-compose up
Recreating app_service_1

ERROR: for service  unable to find a node that satisfies container!=*service*
```
