### ISSUE TITLE
The docker-compose link, for linking containers, does not work.

### ISSUE THREAD

**Issue by kvramana** [docker/compose#3120]
### # My Environment: 

- Mac OS X 10.11.3, 
- Docker version 1.10.3, build 20f81dd 
- docker-compose version 1.6.2, build 4d72027

### Problem Description:
The docker-compose linking does not work whereas the command-line equivalent works. 

### Reproducible Testcase:
I am producing a reproducible test case using linuxconfig/apache image that acts as a docker daemon or as a simple "web" container service listening on port 5000. This "web" service is fronted or linked into from a "haproxy" container service listening on port 80. I start both images through a docker-compose-hello.yml file, and the linking does not work. Whereas, if I start each docker image separately on command-line, then, the container linking works as expected. I'd rather use a compose YML file than go back to docker command line at this stage. Please fix.

### Steps to reproduce:
1. Run attached docker-compose-hello.yml file after copying index.html file. (please use attachments index.html and docker-compose-hello.yml files).
2. Access the image from http://192.168.99.100/ and it does not work.
3. Down the services.
4. Now run, from command-line: 
- docker  run --name web -d -p 5000:5000 -v $PWD/html:/var/www/html/ linuxconfig/apache
- docker  run --name haproxy -d -p 80:80 --link web  tutum/haproxy 
5. Access the image from http://192.168.99.100/ and it works !!

### Expectation: 
The docker-compose started services should have worked as their command-line equivalents. 

[testcase.zip](https://github.com/docker/compose/files/171276/testcase.zip)

**Comment by dnephin** [comment]
Please include the output of `docker-compose logs`.

I believe the issue is that nginx is starting up before apache is ready. When you run it from the command line there is a delay that allows the apache instance to start fully. See https://github.com/docker/compose/blob/master/docs/startup-order.md for more information.

The output of `docker-compose logs` should confirm if this is the issue or not.

**Comment by kvramana** [comment]
I re-ran with starting web first, waited few minutes, and then started haproxy and still same result. I am attaching output of "docker-compose logs"
[docker-compose.log.zip](https://github.com/docker/compose/files/172585/docker-compose.log.zip)

 command to this ticket.

**Comment by kvramana** [comment]
This issue is a bug, but its labeled as "kind/question", please change it to bug, you'd see if you run my reproducible test case with my attachments.

**Comment by kvramana** [comment]
Or please assign this issue to a tester/developer.

**Comment by dnephin** [comment]
From the output of `logs` I don't see any errors, so it's not clear to me what the issue is here.

Please include the output of `docker inspect <nginx container name>` to verify what link settings it has.

**Comment by kvramana** [comment]
I have two containers, first called "web" running linuxconfig/apache image and second called "haproxy" running tutum/haproxy image. The "haproxy" container is setup to link to "web" container. The issue is when i startup both containers through compose script the "haproxy" container does **NOT** forward httprequests to "web" container. 

But if i start up both containers from command line (using docker run command), then "haproxy" container does  forward httprequests to "web" container. 

Attached are inspect logs for my "web" container when it is launched from command-line (log file called as web-command-line.log) as well as compose script (log file called as web-compose.log).

Effectively, the inter-container linking is broken when you spin up containers from docker-compose script.
[Archive.zip](https://github.com/docker/compose/files/176565/Archive.zip)

**Comment by aanand** [comment]
The `tutum/haproxy` image relies on link environment variables to determine the set of backend containers to load balance over.

However, link environment variables have gone away with the new Docker networking system. Version 2 of the Compose file format instructs Compose to use the new networking system, so there are no environment variables, and so the haproxy container can't find the web container.

The reason it works with `docker run` is that you're still using the `bridge` network.

You have a few options:

1. Add `network_mode: bridge` to both services, which will force them to use the bridge network and therefore old-style links. This is the simplest option by far, but it's not very future-proof: old-style links will go away eventually.
2. Use v1 of the Compose file format: delete the `version` and `services` lines and un-indent your services. Also not very future-proof.
3. You might be able to fake the environment variables by adding a bunch of `<name>_PORT_<num>_<protocol>` vars to the haproxy service. This is a bad idea.
4. Use a different image. You could use the official `haproxy` image, which requires you to supply an `haproxy.cfg`, or there might be one that just lets you pass in a hostname/port.

**Comment by dnephin** [comment]
I believe tutum may be working on updating their image to work with overlay networks, but I'm not sure when that will happen or how exactly it will work.

**Comment by kvramana** [comment]
I liked 4th option from above options from Aanand, and pulled dockercloud/haproxy image. I am using dockercloud/haproxy image as documented at https://hub.docker.com/r/dockercloud/haproxy/ site (running on my Mac OS). 

Here's my docker-compose.yml snippet:
```
haproxy:
    image: dockercloud/haproxy
    container_name: haproxy
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    depends_on:
      - web
    links:
      - web
    ports:
      - "80:80"
```

Even "dockercloud/haproxy" container, does NOT forward http requests to "web" container. And i do see this line printed to STDOUT:
`haproxy | INFO:haproxy:Legacy link mode, loading HAProxy definition from environment variables: unable to connect to docker daemon TLS configuration is invalid - make sure your DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are set correctly.
` 

Please let me know if this is a yet another bug, but in dockercloud\haproxy container, with a possible workaround in configuration setting.

**Comment by aanand** [comment]
Is your DOCKER_CERT_PATH accessible from within the container? You might need to mount it as a volume.

This might work:

```yaml
volumes:
  - ${DOCKER_CERT_PATH}:${DOCKER_CERT_PATH}
```

**Comment by aanand** [comment]
This is actually explicitly mentioned in https://hub.docker.com/r/dockercloud/haproxy/ under "example of docker-compose.yml running in Mac OS"

**Comment by kvramana** [comment]
My bad, i missed that one single most important volume mount line, and after adding volume mount, it works!

**Comment by kvramana** [comment]
I closed it too soon without thanking **aanand** and **dnephin**, thank you!
