### ISSUE TITLE
Mount container directory on host

### ISSUE THREAD

**Issue by mccrodp** [docker/compose#3130]
Docker compose seems to mount a host directory on the container. Is it possible to mount a container directory on the host.

For example, the official drupal image I am using in the below `docker-compose.yml` already downloads a version of the Drupal CMS to `/var/www/html` and when I try to mount the volume using `./drupal:/var/www/html` it wipes the drupal install on the container. What is the recommended approach for this?

``` web:
  # Drupal official image => drupal:version
  image: drupal:7.43-apache
  ports:
    # Host machine's port 8000 will map to Drupal's port 80
    - "8000:80"
  volumes:
    # Drupal should live in the "drupal" directory
    - ./drupal:/var/www/html:rw
    - ./docker-compose.sh:/docker-compose.sh
  links:
    - mysql:mysql
    - solr:solr
  working_dir: /var/www/html
```

**Comment by dnephin** [comment]
If you're making changes to those files, they should be on the host. I would ignore whatever files are in the image and use the host volume as you have.

If you need to build a new image with those files, you can create a new `Dockerfile` that does:

```
FROM drupal:7.43-apache
COPY /drupal /var/www/html
```

**Comment by mccrodp** [comment]
Thanks for your reply. That's good to know.

However, I have an issue working like this, the application wants the file ownership to be ````www-data```` user which only resides on the server. I cannot perform a ````chown```` command on the files to ````www-data```` either if they originated on the host.

My work around for the moment is running bash on the docker container and cloning the files directly on the container. This is not ideal, but I'm all ears for a better working method. Thanks again!
