### ISSUE TITLE
support --blkio-weight docker flag

### ISSUE THREAD

**Issue by Silex** [docker/compose#3131]
Hello,

As far as I know, `--blkio-weight` is the way to limit I/O for a container. It'd be great if it was supported in docker-compose.

My use case is that I have "maintenance" containers that do database backups and similar, it'd be nice if they used very low CPU and I/O.

CPU limitation is supported through `cpu_shares`, but I/O has no support.

**Comment by AliMD** [comment]
@Silex 
I don't understand why this feature not support yet!
Maybe we don't follow the best practices!
Maybe change blkio-weight is not recommended

**Comment by Silex** [comment]
@AliMD: generally speaking limiting I/O does not work very well, thus I think it's not used very much and there's no real intencive to support it quickly. I'll be supported sooner or later tho, as long as `docker` supports it.

**Comment by burtsevyg** [comment]
+1

**Comment by sztwiorok** [comment]
+1
