### ISSUE TITLE
Question: docker-compose on Docker virtual host

### ISSUE THREAD

**Issue by iamKurt** [docker/compose#3134]
Any reason not to install docker-compose on the `docker-machine` created virtual host?  Since docker is installed by default to install the Docker daemon, I'm wondering whether it's ok to also install docker-compose.  If there's no reason not to install compose on the virtual host, then is there a best practice way to install it?

Thanks!

**Comment by dnephin** [comment]
https://docs.docker.com/compose/install/ should work. I don't know of any reason not to.

**Comment by formerlyKurt** [comment]
Thanks @dnephin! Just tried installing it on the host and got an error:

      curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
      -sh: can't create /usr/local/bin/docker-compose: Is a directory

Can compose run on boot2docker? I just found issue #1032 and wonder if this is related to that issue.

Thanks again!

**Comment by formerlyKurt** [comment]
Also @dnephin, since changes usually do not persist on this virtual host, any advice on getting around that aspect?

**Comment by formerlyKurt** [comment]
Ok, so compose can be installed on the docker virtual host manually using:

`tce-load -wi python && curl https://bootstrap.pypa.io/get-pip.py | \
  sudo python - && sudo pip install -U docker-compose`

But, if one wanted to install it from a Dockerfile, say, to ensure that it was installed prior to starting up a Jenkins container on that virtual host then, 

`RUN tce-load -wi python && curl https://bootstrap.pypa.io/get-pip.py | \
  sudo python - && sudo pip install -U docker-compose`

doesn't seem to do the job. Error message is:

      RUN mkdir -p /usr/share/jenkins/ref/ssh-keys /var/log/jenkins &&   tce-load -wi python && curl https://bootstrap.pypa.io/get-pip.py |   sudo python - && sudo pip install -U docker-compose
      ---> Running in 45444c6e59da
      /bin/sh: 1: tce-load: not found

The idea here is that the Jenkins container will be able to run compose on the host to spin up new containers for testing.

Any ideas on getting around this issue @dnephin?

Thanks!

**Comment by dnephin** [comment]
If your base `FROM` isn't tiny core, then tce-load isn't going to exist. What's the base image?

**Comment by formerlyKurt** [comment]
Ahh...that makes sense!  The `FROM` is from `jenkins:1.642.2` which is based on `java:8`.

Is it generally a bad idea to run Docker compose inside a container? The reason I'm asking is that compose would spin up containers inside containers.  Bad practice?

**Comment by dnephin** [comment]
Not at all, that's totally fine if it works for you.
