### ISSUE TITLE
docker-compose pull downloads images on all nodes in a swarm

### ISSUE THREAD

**Issue by schmunk42** [docker/compose#3138]
_In advance, sorry if this topic is already discussed somewhere else, I remember some comments here and there._

When I run `docker-compose pull` on against a swarm all images are pulled on all nodes - also if you have defined constraints.

It would be really helpful, if `docker-compose` would pull only on those node(s), which match the constraints, eg `app==1`.

**docker version**

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.1.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   a0fd82b
 Built:        Thu Feb  4 08:55:18 UTC 2016
 OS/Arch:      linux/amd64
```

**docker-compose version**

```
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by dnephin** [comment]
I think this is just how swarm works. It doesn't provide any way to say "only pull on this node".

**Comment by schmunk42** [comment]
Should I open a corresponding issue at `docker/swarm`?

**Comment by dnephin** [comment]
Yes, I think that's the best way to proceed.

**Comment by schmunk42** [comment]
Found some related issues on docker and swarm:
- https://github.com/docker/docker/issues/19785
- https://github.com/docker/swarm/issues/1922

**Comment by mattgiles** [comment]
One idea might be for the `docker pull` cli/api to support something like node constraint arguments.

In compose, for example, it may well make sense for `docker-compose up` to pull all images to all *eligible* nodes, but it doesn't make as much sense for that pull to offend node constraints defined in the `docker-compose.yml`.

Believe this would also solve the more specific problem of "how to ask swarm to pull to a specific node".
