### ISSUE TITLE
Specify what host to use?

### ISSUE THREAD

**Issue by cdrage** [docker/compose#3142]
Stupid question.

But is there a way to use both docker machine and compose to specify what particular host to deploy on?

I know I can do this for multi-host networking. But how can I specify which hosts deploy what with docker-machine? For example. Redis on foobar-server-1, mysql on foobar-server-2, etc.

**Comment by dnephin** [comment]
There is no way to do that. You can target all services at a machine by using `DOCKER_HOST=` environment variable, or you can use swarm and node name constraints.
