### ISSUE TITLE
compose doesn't create an unused network in swarm

### ISSUE THREAD

**Issue by gittycat** [docker/compose#3143]
I have multiple compose files that rely on a common overlay network within a swarm cluster. I planned to define the common network using a compose file but it doesn't create it unless it is used within the compose file itself.

This is simple to duplicate:
docker-compose.ml

```
version "2"
networks:
  backbone:
    driver: overlay
```

`docker compose up -d` then gives this warning:

```
WARNING: Some networks were defined but are not used by any service: backbone
```

and the network isn't shown by `docker network ls`

On the other hand, using `docker network create -d overlay backbone` does create the network as expected.

```
docker 1.10.3
docker-compose 1.6.2
docker-swarm 1.1.3 (42b1620)    <- built from the latest master
```

**Comment by dnephin** [comment]
That warning could probably be a little more clear, but yes, the network is not created unless it's used by at least one service.

**Comment by gittycat** [comment]
@dnephin I don't understand the reason for this limitation.
I'm trying hard to define everything in compose files. In my case, I have an "infrastructure.yml" file that I call first and that defines system wide networks. Other compose files can be called which assume "external" networks defined in the infrastructure compose file. We can't define the same network twice so unless infrastructure.yml creates the network, it becomes harder to manage using the other compose files.

**Comment by dnephin** [comment]
There isn't really a strong reason for it to be this way. When we added networks we were thinking that a network that isn't used by any containers doesn't need to be created.

I think your use case is an interesting one. It's definitely not a documented case, but maybe we can support it.

**Comment by gittycat** [comment]
Ok, I'll leave this open to see what others think.

**Comment by ijc** [comment]
Issue grooming: Seems like there has not been much other interest so I'm going to close now.
