### ISSUE TITLE
Docker compose's ports doesn't map host range mapping to single container port

### ISSUE THREAD

**Issue by farhadkzm** [docker/compose#3150]
To map a container's port within a range of host's ports, **Docker run** acceps `-p x-y:cPort`, however it seems the option is not supported by **Docker compose**'s yml file.

**Comment by aanand** [comment]
Yes, we should support this.

**Comment by farhadkzm** [comment]
Is there any workaround to do the same with docker compose?

**Comment by aanand** [comment]
Not at current - you'll have to use `docker run` for the time being.

**Comment by jantoniucci** [comment]
At docker cli also is failing because at https://github.com/docker/docker-py/blob/master/docker/utils/ports/ports.py#L77 is a check: 

```
        if len(internal_range) != len(external_range):
            raise ValueError('Port ranges don\'t match in length')
```

Is this fix in the near term roadmap?

**Comment by farhadkzm** [comment]
For those who need to have that feature with Docker compose, I found a workaround which might help you:
Docker uses ephemeral port range, so if you change that range you can actually define a range of port but remember that it's a global config and it might affect other tools running on the machine as well.
To change the range you just need to run the following command as root:
echo MIN_PORT MAX_PORT > /proc/sys/net/ipv4/ip_local_port_range

where MIN_PORT and MAX_PORT define the port range.

**Comment by tbodt** [comment]
@farhadkzm What if I'm using Docker for Mac?

**Comment by farhadkzm** [comment]
From what I saw in the docker compose source code, I think it doesn't
support the feature on Mac neither.

Regards,

Farhad Kazemi

**Comment by gabrieltakacs** [comment]
Any news about this? I really need that...

**Comment by shin-** [comment]
Recent releases now support the p1-p2:p syntax (via #4649)
