### ISSUE TITLE
Should "run" command ignore restart policy?

### ISSUE THREAD

**Issue by stefcl** [docker/compose#3155]
Hello,
I am using docker-compose 1.6.2 along with docker 1.10.3.
I often run short-lived containers in interactive mode using `docker-compose run` with `--rm` option and an argument line for debugging purpose before running them in background. 

Sometimes, it takes many attempts to get the command line of my dockerized apps right. Recently, I found a lot of dangling containers with suffixes like "run_3" "run_4" while running `docker ps -a`, these seemed to correspond to failed "run" attempts that the docker engine was permanently trying to "resurrect". It comes from my yml file which sets the restart policy to "unless-stopped" for all my containers.

While I understand why it happens, I am wondering if the `docker-compose run` command should not ignore the restart policy defined in the yml file. The `run` command seems to be designed primarily for interactive testing and ephemeral containers, while restart policies make most sense with long-lived services.
Kind regards

**Comment by aanand** [comment]
The restart policy should be ignored if you pass `--rm`. If it's not, could you provide the exact commands you ran to reproduce the problem?

**Comment by stefcl** [comment]
I am probably the one at fault for omitting the `--rm` flag since the docker daemon could not attempt to restart a container which has been removed.
However,  when you don't pass `--rm`, docker applies the restart policy, altough the terminal is no longer attached. I can't think of any use case in which one would use `run` non-interactively and still want auto-restart, but the current behavior is quite reasonable. I guess you can close this issue.

**Comment by aanand** [comment]
I'm also not sure there's any valid use case for `run` with a restart policy. The reason we went with only ignoring it for `--rm` was parity with `docker run`.

I can imagine there are people out there using `docker-compose run -d web` to start their app, who'll be surprised if the restart policy isn't honoured... but they should be using `docker-compose up -d web`.

**Comment by stefcl** [comment]
Given that there are already some exceptions, especially port mappings, that do not make `run` a really good choice for production containers, I suppose it would not hurt that much to add a special rule with the restart directive, but I'd understand if you prefer to leave the current state unchanged to avoid introducing too many special implicit rules.
If you don't use `--rm`, you are probably interested in the resulting container, so you'll probably notice that it's stuck in a restart loop.
