### ISSUE TITLE
python: can't open file 'app.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by pavanadepu2** [docker/compose#3157]
I am trying to deploy the python app which is specified in docker-compose getting started guild.
When I ran the command, docker-compose up am hitting the error, "python: can't open file 'app.py': [Errno 2] No such file or directory".

Here is the complete output:

```
Creating composetests_redis_1
Creating composetests_web_1
Attaching to composetests_redis_1, composetests_web_1
redis_1 | 1:C 17 Mar 17:08:04.883 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1 | 1:M 17 Mar 17:08:04.885 * Increased maximum number of open files to 10032 (it was originally set to 1024).
redis_1 |                 _._
redis_1 |            _.-``__ ''-._
redis_1 |       _.-``    `.  `_.  ''-._           Redis 3.0.7 (00000000/0) 64 bit
redis_1 |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1 |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1 |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1 |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1 |   `-._    `-._  `-./  _.-'    _.-'
redis_1 |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1 |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1 |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1 |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1 |  |    `-._`-._        _.-'_.-'    |
redis_1 |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1 |       `-._    `-.__.-'    _.-'
redis_1 |           `-._        _.-'
redis_1 |               `-.__.-'
redis_1 |
redis_1 | 1:M 17 Mar 17:08:04.886 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1 | 1:M 17 Mar 17:08:04.886 # Server started, Redis version 3.0.7
redis_1 | 1:M 17 Mar 17:08:04.886 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1 | 1:M 17 Mar 17:08:04.886 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1 | 1:M 17 Mar 17:08:04.886 * The server is now ready to accept connections on port 6379
web_1   | python: can't open file 'app.py': [Errno 2] No such file or directory
composetests_web_1 exited with code 2
```

My image built properly, an even when I ran the below command I am able to see the files inside the image:
```
:$ docker run 5dfe73a1337e ls /code
Dockerfile
app.py
docker-compose.yml
requirements.txt
```

Please let me know is there any workaround for this issue.

My Topology is as follows:
=====================
Docker Client: WindowsMachine(from Docker Tool Box)
Docker Host : Ubuntu VM in Azure cloud.

**Comment by aanand** [comment]
(I was sure we had a note in the docs for this, but maybe not.)

It's most likely a volume mounting issue. If your app directory is outside your home directory (`C:\Users\whatever`), then volumes won't mount from your host machine. Is that the case?

**Comment by pavanadepu2** [comment]
My App Directory in Windows Machine which is my docker client machine is, C:\Users\myname\compose-tests. Still I am hitting this issue.

And my Docker Host is an ubuntu VM. I am seeing that the folder structure C/users/myname/composetests is created in my Docker Host machine. But no files are copied to it.

Yes, it seems something related to mounting as things are working if I copy the file onto the target machine on to the above created folder.

**Comment by pavanadepu2** [comment]
I even tried placing the app folder directly under users folder, like C:\Users\compose-tests

**Comment by pavanadepu2** [comment]
Is there any update on the above issue?

**Comment by aanand** [comment]
OK, this isn't a Compose issue then. Sadly, VirtualBox and its shared folders are quite buggy. Restarting or re-creating your VM might work. Failing that, best to report an issue on [docker/machine](https://github.com/docker/machine).

**Comment by bfirsh** [comment]
Sorry @pavanadepu2, this does indeed look to be an issue with VirtualBox. Opening an issue on docker/machine may help, but we are working on some improvements to file sharing generally, so stay tuned for future releases. :)

**Comment by pythoncontrol** [comment]
Any news on this? I am running beta Windows + Hyper-V.

**Comment by emin63** [comment]
I had a similar issue in following the tutorial at https://docs.docker.com/compose/gettingstarted/#step-2-create-a-dockerfile and got ` "python: can't open file 'app.py': [Errno 2] No such file or directory"`. Moving everything into my home directory solved the problem.

I'd suggest putting a note about this in the tutorial at https://docs.docker.com/compose/gettingstarted/#step-2-create-a-dockerfile. It's pretty frustrating to follow the tutorial and get something strange like this error.

Thanks.

**Comment by altimmons** [comment]
I got the same error by creating App.py (note case) on Windows/ Hyper V.  If you see this- check your case.

To fix youll have to delete the image because docker will not see the case change as a change, and will just used the cached version. 
```
docker container ls --all
#get Container ID for all instances
docker rm ############## -f
```

![image](https://user-images.githubusercontent.com/15314341/45935623-bfcf2200-bf72-11e8-82e0-0fb43ea8def1.png)
