### ISSUE TITLE
Enforcing container (& app) start order in compose

### ISSUE THREAD

**Issue by formerlyKurt** [docker/compose#3166]
Is there a way to enforce the container and app startup sequence using compose?  Specifically, I want to ensure that an app is completely started prior to another app trying to consume it. The `depends_on` attribute seems to enforce container sequence but doesn't wait for the app to complete its startup.

**Comment by aanand** [comment]
See [Controlling startup order in Compose](https://docs.docker.com/compose/startup-order/).

**Comment by formerlyKurt** [comment]
Thanks @aanand!  This was the info that I needed.
