### ISSUE TITLE
Compose filter ipadress

### ISSUE THREAD

**Issue by victorock** [docker/compose#3171]
It would be great in dynamic environment with multiple networks and connectivity to have the ability to define filters based on the ip address of the nodes.
# If the node has the specific IP

service1:
  environment:
    - "affinity:ipaddress==10.10.10.10"
# If the node is part of the network

service2:
  environment:
    - "affinity:ipaddress=~10.10.10"

...etc

**Comment by aanand** [comment]
This would need to be a feature of Swarm, not Compose. Have you tried asking there?
