### ISSUE TITLE
Question about compose and container IDs

### ISSUE THREAD

**Issue by formerlyKurt** [docker/compose#3172]
Is there a way for compose to store (as an environment variable) the container ID of a running container? It would also be nice if there is a way for compose to store in an env var the image ID that a container was made from.  If this is something that compose can already do, how would I go about doing this?

Here's the background on what I'm trying to solve for: 

If Jenkins is creating images and spinning up containers for testing, I need a way to uniquely identify the logs from each container so that when I copy them out of the Jenkins workspace I know which image/container generated which log.  If specifying the container ID as an env var is possible, then I can add this as the name of the logging file by specifying this in the compose file:

`log.file=${CONTAINER_ID}-${COMPOSE_PROJECT_NAME}.log`

Thanks...any thoughts about this are greatly appreciated!

**Comment by formerlyKurt** [comment]
I think this `docker-compose run SERVICE env` gives me all the info that I need. :)

**Comment by formerlyKurt** [comment]
Actually, I take that back.  Each time this command is run, it creates a new container, which updates the `HOSTNAME` environment variable.

**Comment by dnephin** [comment]
`docker inspect <container name>` gives you everything

**Comment by formerlyKurt** [comment]
Thanks @dnephin! Now, I'm trying to understand how `docker inspect` works. When I start up my services using `docker-compose -p <basename> up` I can see two different container IDs.  The first container ID shows up when I mistype the name:

    docker inspect --format='{{.Config.Hostname}}' <basename>_app

I get **eb5360903655**.

`<basename>_app` is not the actual name of the container started by Docker.  This was me fat-fingering the name/forgetting to put in the actual container name, which ends in an `_1` -- the actual container started by Docker is `<basename>_app_1`.

When I use that name in the `inspect` command, I get a different hostname.

    docker inspect --format='{{.Config.Hostname}}' <basename>_app_1

returns **c6663e4b7357**.

The first container ID is nowhere to be found:

`docker ps -a | grep eb5360903655`

returns nothing. What gives here?

**Comment by dnephin** [comment]
The first one is an image id. `inspect` will accept both image ids/names and container ids/names.

**Comment by formerlyKurt** [comment]
`docker images | grep eb5360903655` also returns nothing.

**Comment by formerlyKurt** [comment]
Any other thoughts on this @dnephin?

**Comment by soyarma** [comment]
ubuntu@box177:~/website$ docker inspect --format='{{.Id}}' containername
8013fb4c3cc636ce1ed61aed3bf8cf57e4772c8004593f1d626e1824b9f5469d

That gets you your full ID
