### ISSUE TITLE
Add option to omit project prefix from container names

### ISSUE THREAD

**Issue by dunk** [docker/compose#3176]
I currently use a container_name directive in every one of my services in order to prevent them from being named "project_container", which sucks for tab-completion. I only tend to have one set of these containers up on my development machine, and spend far more time tab-completing commands than I expect I ever will running N different container sets. I'm sure others are in the same boat.

**Comment by aanand** [comment]
Tab-completion of what commands, exactly? If you're using [Compose's tab completion](https://docs.docker.com/compose/completion/), the project name isn't involved - you can e.g. type `docker-compose stop w[tab]` and it'll complete to `web`.

**Comment by dunk** [comment]
I see. I actually have another command on top of docker-compose which proxies a subset on to docker-compose directly, but also has commands specific to my application. Some of these subcommands interact with specific containers. I wasn't aware that the compose tab-completion excluded the prefix. I'd still find this useful in dev myself, but you'll know better whether it's more generally applicable.
