### ISSUE TITLE
Making container-wide settings in compose

### ISSUE THREAD

**Issue by iamKurt** [docker/compose#3177]
Is there a way to specify container-wide settings for all containers that apply to all containers started by a compose file?  Specifically, I'd like to be able to enable TLS, set memory and CPU limits, etc. but don't want to have to put those settings under the `environment` section of every container. Is there another way to do this?

Thanks!

**Comment by formerlyKurt** [comment]
So, looking into this in more depth, one could put all the common settings/configurations into a `common.yml` and utilize the `extends` attribute in the main `docker-compose.yml` file to make use of those configurations. This reduces the copy/pasting in the `docker-compose.yml` file (especially when you have many services) but each service inside that `docker-compose.yml` file would still have to extend the same common file. 

Is there a better way to do this?

**Comment by shin-** [comment]
[Extension fields](https://docs.docker.com/compose/compose-file/compose-file-v2/#extension-fields) are now the recommended approach to solving this.
