### ISSUE TITLE
Env variable override not possible from host if default value present

### ISSUE THREAD

**Issue by aleemb** [docker/compose#3183]
1. As expected:
    ```
environment:
  - FOO

FOO=external docker-compose run test env
# shows "external"
```

2. As expected:
    ```
environment:
  - FOO=internal

docker-compose run test env
# shows "internal"
```

3. Weirdness:
    ```
environment:
  - FOO=internal

FOO=external docker-compose run test env
# shows "internal"
```

The output should be external since the host overrode the default value.

Is there any way right now (1.6.2) to achieve 3? That is, to allow for an environment variable from host but fallback to a default value if absent?

Also referenced by @fazy in https://github.com/docker/compose/issues/1377#issuecomment-128137124

**Comment by dnephin** [comment]
This is working as intended. Environment variables with values should not be overridden from the host values.

**Comment by aleemb** [comment]
Tripped me up since args are allowed overrides. There are a other issues open for variable interpolation so I suppose that may allow a workaround as well.
