### ISSUE TITLE
Upgrading app containers and apps running on containers

### ISSUE THREAD

**Issue by iamKurt** [docker/compose#3186]
So, I've read the best practices approach for [linking containers](https://docs.docker.com/v1.8/userguide/dockerlinks/) and agree with this recommendation. However, am wondering what the recommendation would be to upgrade a dependent container. For example, let's say that I need to upgrade my Postgres database. Better yet, I need to update the schema on a running database container, then update the dependent app `A` all while the app is still available. My current thinking is that I can bring up a new database container, run some upgrade scripts against the schema, then startup a new dependent app `A'`. However, if the database data is a mounted volume, then that will affect both `A` and `A'`

I'm pretty sure that this has already been solved so I'm curious to hear how and/or any recommendations on how to handle these scenarios.

Thanks!

**Comment by jayfk** [comment]
I think the best way to solve problems like this is on the application layer. When it comes to database migrations, I always make sure to create one that runs with both `A` and `A'`.

For example, renaming a column from `foo` to `bar`:
  - Create a new column `bar`
  - Copy `foo` into `bar`
  - deploy
  - make sure that everything works and you don't need to jump back
  - delete `foo`

**Comment by formerlyKurt** [comment]
That's a good strategy @jayfk. Isn't it possible though that you could get data in `foo` that isn't in `bar` or vice versa if your shooting for zero downtime? How would you solve that synchronization issue?
