### ISSUE TITLE
Allow interactive mode on Windows

### ISSUE THREAD

**Issue by friism** [docker/compose#3194]
Sort-of related to:

 * https://github.com/docker/compose/issues/3096
 * https://github.com/docker/compose/issues/2836

**Comment by atrauzzi** [comment]
It's my understanding that the current preview build of Windows 10 as well as all the various alternative shells (conemu and whatever ships with msys, msys2 and cygwin) support VT100.

Would this just simply be a matter of eliminating any checks that punt on interactive mode and letting the ecosystem catch up?

**Comment by friism** [comment]
@atrauzzi where can I read more about VT100 support in Windows? Either way, the check will have to be removed from compose.

**Comment by friism** [comment]
This is probably the equivalent effort in `docker/docker`

**Comment by atrauzzi** [comment]
@friism - Briefly asked Rich Turner about it: https://twitter.com/Omega_/status/717682291040849920

**Comment by aanand** [comment]
Here are the blockers to getting interactive run/exec working on Windows:

- I/O multiplexing
  - done with `select`
- Setting streams to blocking/non-blocking
  - done with `fcntl`
- Managing TTY raw state
  - previous state saved/restored with `termios`
  - set to raw with `tty`
- Managing terminal size
  - monitored with `signal.SIGWINCH`
  - determined with `fcntl` and `termios`

As for _why_ those are problematic:

- `SIGWINCH`, `fcntl`, `tty` and `termios` are unavailable on Windows
- Python's `select` can only operate on actual sockets on Windows, not socket-like objects (e.g. stdin)

So we'd need to abstract over the jobs done by the various stlib modules. If there's a library out there, great (bonus points if there's an alternative to SIGWINCH for monitoring terminal size). As for `select`, we might be able to use threading and `Queue`.

This is already looking extremely hairy.

The alternative plan: shell out to `docker`.

- `docker-compose exec <service> ...` becomes a dead-simple `docker exec <container id> ...`

- `docker-compose run <service> ...` is more complicated - we still have to manage creating the container with all the right configuration etc (I don't think we want to go down the road of generating CLI arguments for `docker run` - that's going to be a breeding ground for up/run disparity bugs).

    I've spiked out shelling out to `docker attach` after creating the container, but the problem there is the classic start/attach race condition: if we attach after starting the container, we risk losing output or attaching after it's already exited. However, `docker attach` refuses (using [client-side logic](https://github.com/docker/docker/blob/b9c94b7/api/client/attach.go#L35-L37)) to attach to a non-running container.

- Finally, we've introduced a new dependency on having the docker CLI installed (which, in fairness, it probably will be 99% of the time, but we should warn people who might have it installed in a stripped-down environment, e.g. CI). There could potentially also be issues when Engine/Compose versions drift out of sync and behaviour changes.

**Comment by friism** [comment]
@aanand should this be updated to reflect 1.8 status?

**Comment by aanand** [comment]
Removed from the 1.8 milestone.

**Comment by jamespacileo** [comment]
Is it not even planned for 1.9? Was really looking forward to this 😞

**Comment by atrauzzi** [comment]
Yeah, likewise.  This really should be getting some priority.

**Comment by lypanov** [comment]
Also hope very much this is coming some time soon!

**Comment by rwilliams** [comment]
There is a decent workaround for this now. My current setup is using the latest Docker Toolbox without docker compose and then installing docker-compose with babun see here http://blog.eisele.net/2015/06/docker-compose-on-windows-with-python.html. Note, you'll probably have to upgrade the python version in babun. The only thing that doesn't seem to work is relative volume mappings but that's not a huge deal. 

A 2nd work around and maybe long term solution for Windows users might be the Ubuntu Bash Shell that's being added in the Windows 10 summer update. Now that the docker-client and server have been separated you can run docker and docker-compose in the bash environment. You might have to use the Windows version of docker-machine though as bash can't call windows executables, ie virtualbox etc. I think this is probably the best long term solution as we can agree on one windows shell that's supported for interactive mode instead of trying to support powershell, cmd, babun, etc, etc.

I'm currently testing the Ubuntu Bash setup right now and it's working well so far.

**Comment by friism** [comment]
@rwilliams interactive mode works fine with the raw `docker` cli in almost all windows shells. Are there any fundamental reasons why we'd have to restrict shell choice when using Compose on Windows?

**Comment by rwilliams** [comment]
@friism Isn't the point that docker-compose doesn't support interactive mode on Windows? The shell choice restriction would be that we'd be using the linux version of docker-compose not the windows version so in that case your choices are babun/cygwin/Bash for Windows

**Comment by jamespacileo** [comment]
@rwilliams thanks for sharing! Please let us know how you get on with Bash on Windows :smile:  From my last attempt Bash on Windows solution works well as well, but shares the relative path problem too for now and maybe a few minor issues. 

Unfortunately me and colleagues are trying to use Docker for development, and relative paths are very important. It's a shame that we need to still claw our way out this hole with workarounds.

I appreciate Docker's difficulties in addressing this, but it's a bit disheartening that this issue and full OS-parity is being delayed further.

**Comment by rwilliams** [comment]
@jamespacileo I'm not having the relative path issue using Bash for Windows. Maybe there have been some fixes since you last tried it. One other thing i did was update the python version for Bash for Windows the bundled version is 2.7.5 i think.

**Comment by jamespacileo** [comment]
@rwilliams thanks that's great news! :)

**Comment by atrauzzi** [comment]
I do believe this issue is more about getting interactive mode working on Windows without having to employ workarounds.  Despite the upcoming release and relative usefulness of the Ubuntu on Windows, there are still users who will prefer not to have to resort to this.

I still think there is a strong use case for ensuring that compose works in cmd and PowerShell.

(and trust me, I prefer bash to either, but that's also not what this is about)  ;)

**Comment by rwilliams** [comment]
@atrauzzi I completely agree. What I propose is a work around. I think there is a large mountain to climb before this just works for Windows and I was merely trying to give us some comfort as we wait.

**Comment by atrauzzi** [comment]
Workarounds -- at least in this ticket system -- only serve to distract from the main issue.  Probably better made as blog posts.

**Comment by aanand** [comment]
@atrauzzi I wouldn't entirely agree. It's useful for people searching, and landing on this issue page, to have workarounds described (or at least linked to) here.

It sucks that we didn't get interactive run working on Windows for 1.8 - I'm as disappointed as everyone else here - but there just wasn't time.

**Comment by jamespacileo** [comment]
@aanand @atrauzzi @rwilliams For me the main issue with this situation is sharing Docker-based Development workflows with other developers who may not even be familiar with Docker. 

Right now writing raw docker cli commands is not feasible for our complex bundles of images/containers, we have front end developers who can survive with a simple "docker-compose run app bash" but not with a raw command with all the options attached.

**What if compose echoed the raw commands to create, exec and destroy the container with all the optional commands?**

That would at least reduce the burden and make it easier to replace Vagrant and other dev workflow environments.

Similar to what `docker-machine env machine_name` does.

**Comment by carrete** [comment]
> What if compose echoed the raw commands to create, exec and destroy the container with all the optional commands?

This would work for us. Or just to know how docker-compose creates hostnames for use within containers between linked services.

**Comment by aanand** [comment]
Next steps on this:

1. Open a PR to Engine to address the attach-before-start issue I described in https://github.com/docker/compose/issues/3194#issuecomment-220292194. Either remove the check that stops you from attaching to a non-running container, or add a flag to skip it.

2. Working on the assumption that that PR will make it into Engine 1.13, add logic to Compose to attempt to shell out to `docker attach`/`docker exec` if (and only if) we're on Windows.

    - We'll have to check the version of the client binary (i.e. shell out to `docker --version`) and show an error if it's older than 1.13.
    - Leave in the current dockerpty behaviour on Linux and OSX, because it works.

3. A version or two down the line, once shelling out is confirmed to be working well for Windows users, we can switch over to using it on Linux and OSX too, and remove our dependency on dockerpty.

**Comment by indcoder** [comment]
@aanand  Do we know for which milestone is this issue targetted to be solved for?

**Comment by princemaple** [comment]
@aanand I see that no.1

> Open a PR to Engine to address the attach-before-start issue I described in #3194 (comment). Either remove the check that stops you from attaching to a non-running container, or add a flag to skip it.

is no longer a problem, since https://github.com/docker/docker/issues/26705

do you think this current issue can be resolved soon-ish? (next version or something)

**Comment by aanand** [comment]
@princemaple Good timing - I was just opening the PR: https://github.com/docker/compose/pull/3980

We hope to have this change out in Compose 1.9.0.

**Comment by aanand** [comment]
If anyone in this thread is interested in trying out the new interactive support, here's a Windows binary you can test:

https://ci.appveyor.com/api/buildjobs/2htih7jy6cukrwtv/artifacts/dist%2Fdocker-compose-Windows-x86_64.exe

**Comment by sambernet** [comment]
@aanand tested above build on my current environment:

- Win 10 Redstone 1607 (Build 14393.187)
- Docker for Windows 1.12.1-beta26

Tested with those consoles (all 64-bit):
- cmd
- powershell (5.1.14393.187)
- Powershell via Cmder (based on ConEmu 160914)
- cmd via Cmder

Works well enough from what I can tell after these quick tests. Only thing I observed was that a few times exiting the attached console didn't work very well. docker echoed my `exit` command to the console then seemed to hang. I didn't wait longer than about a minute, and could always terminate with Ctrl+C, so this might be an actual issue or some peculiarity of my setup.

Single test case was `docker-compose exec <service> bash` (no `-d` as in 1.8.x). Is there some other case you'd like me to test?

**Comment by claycephas** [comment]
How about git bash? I'll try it if I get a chance.

**Comment by princemaple** [comment]
Just gave it a go in ConEmu, works nicely!

**Comment by aanand** [comment]
A good test case is vim, which stresses out terminal escape sequence handling + resizing quite well.

**Comment by PsychoThinker** [comment]
docker-compose version

```
docker-compose version 1.9.0dev, build 9db7acd
docker-py version: 1.10.3
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

docker-compose --verbose up

```
...
compose.parallel.feed_queue: Pending: set([<Service: api>])
compose.parallel.feed_queue: Pending: set([<Service: api>])
compose.parallel.feed_queue: Pending: set([<Service: api>])
compose.parallel.parallel_execute_iter: Failed: <Service: mongodb>
compose.parallel.feed_queue: Pending: set([<Service: api>])
compose.parallel.feed_queue: <Service: api> has upstream errors - not processing
compose.parallel.parallel_execute_iter: Failed: <Service: api>
compose.parallel.feed_queue: Pending: set([])

ERROR: for mongodb  HTTPConnectionPool(host='127.0.0.1', port=2375): Read timed out. (read timeout=60)
ERROR: compose.cli.errors.log_timeout_error: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

cmd and powershell has the same behavior :(

**Comment by aanand** [comment]
@PsychoThinker does this happen with the latest [master build](https://dl.bintray.com/docker-compose/master/)? If so, it's not related to #3980. If you can reproduce it with a master build but not with [1.8.1](https://github.com/docker/compose/releases/tag/1.8.1), it's a regression - please open a new issue.

In any case, it looks like a network problem, or perhaps your Docker daemon isn't running. It's unlikely to be a Compose issue.

**Comment by PsychoThinker** [comment]
@aanand according to what @shin wrote, my orginal issue (#3984) is related to this issue. 

That's why I wanted to see if build 9db7acd of docker-composer also solves my problem - unfortunately this is not true at this moment.

For sure it is not network or Docker deamon not running problem.

**Comment by rwilliams** [comment]
@PsychoThinker The `up` command is non interactive by design and it wasn't changed for this issue. Something else is going on with your setup but it's not related to interactive mode.

**Comment by PsychoThinker** [comment]
Ok, thank you, then I will ask for reopen #3984

**Comment by atrauzzi** [comment]
@aanand Do you know when the version with this fix will be getting bundled with a docker for windows update?
