### ISSUE TITLE
docker-compose exec should support -u like docker-compose run does

### ISSUE THREAD

**Issue by albers** [docker/compose#3205]
From the output of `docker-compose help run`

```
   -u, --user=""         Run as specified username or uid
```

From the output of `docker-compose help exec`

```
 --user USER       Run the command as this user.
```

For symmetry reasons, `exec` should also support `-u`. The help messages should be identical, too.

**Comment by kklepper** [comment]
Sorry, I don't get this output:


    $ docker-compose help exec
    ERROR: No such command: exec
    
    Commands:
      build              Build or rebuild services
      config             Validate and view the compose file
      create             Create services
      down               Stop and remove containers, networks, images, and volumes
      events             Receive real time events from containers
      help               Get help on a command
      kill               Kill containers
      logs               View output from containers
      pause              Pause services
      port               Print the public port for a port binding
      ps                 List containers
      pull               Pulls service images
      restart            Restart services
      rm                 Remove stopped containers
      run                Run a one-off command
      scale              Set number of containers for a service
      start              Start services
      stop               Stop services
      unpause            Unpause services
      up                 Create and start containers
      version            Show the Docker-Compose version information
    

    $ docker version
    Client:
     Version:      1.10.3
     API version:  1.22
     Go version:   go1.5.3
     Git commit:   20f81dd
     Built:        Thu Mar 10 15:54:52 2016
     OS/Arch:      linux/amd64
    
    Server:
     Version:      1.10.3
     API version:  1.22
     Go version:   go1.5.3
     Git commit:   20f81dd
     Built:        Thu Mar 10 15:54:52 2016
     OS/Arch:      linux/amd64

**Comment by albers** [comment]
@kklepper `docker-compose exec` will be available in the next version of Compose, 1.7.0.

**Comment by kklepper** [comment]
@albers  Thanks for the information.

**Comment by albers** [comment]
@kklepper Sorry for the confusion. I should have added the version above.

**Comment by kklepper** [comment]
@albers It is my part to be sorry, too. I should have added the docker-compose version...
