### ISSUE TITLE
NFR: docker-compose -H option

### ISSUE THREAD

**Issue by nejtr0n** [docker/compose#3212]
It would be greate to use -H flag similar to docker, but not only environment variable DOCKER_HOST.
For exmaple 
docker-compose -H ${CLUSTER_IP}:4000 -f cluster.yml up -d

**Comment by aanand** [comment]
Support for `-H` was added in https://github.com/docker/compose/pull/3139 and is out in [1.7.0 RC1](https://github.com/docker/compose/releases/tag/1.7.0-rc1).
