### ISSUE TITLE
how to use `extra_hosts` to add like hundreds of hosts? any way to reference a file?

### ISSUE THREAD

**Issue by babatundebusari** [docker/compose#3213]
I will like to add several hundreds of hosts to the docker container /etc/hosts file but using the `extra_hosts` that comes with docker-compose will require adding all hosts on the docker-compose file.

Any way to reference a file or template instead? for adding several hundred hosts?

Thanks

**Comment by dnephin** [comment]
There is currently no support for that.  What's your use case that requires adding so many hosts?

**Comment by babatundebusari** [comment]
I am using jenkins with fabric to manage several remote execution on remote hosts and i have several remote hosts to add to the jenkins local hosts file, so adding them in docker-compose file will make things more complicated and make the file look so long. SO if i can reference a file with all hosts, that will make things cleaner.

Thanks

**Comment by babatundebusari** [comment]
@dnephin got it?

**Comment by ebuildy** [comment]
I think extra_hosts is here to quickly add a few hosts, what you need is more like a DNS, you can use dnsmasq which is very easy to configure and use with Docker.

**Comment by dnephin** [comment]
Yes, I think that's correct. If you need to manage more hostnames, you should use DNS.
