### ISSUE TITLE
Support for docker-compose down [service...]

### ISSUE THREAD

**Issue by aschrijver** [docker/compose#3228]
I know this can be done with `docker` command, but I find it strange that you can do `docker-compose up -d [service...]` and specify one or more services defined in compose config, but you cannot in a similar way specify specific services to stop.

**Comment by aanand** [comment]
`down` operates on more than just services: it also removes networks and - optionally - volumes and images. I'm not sure it would make much sense to scope it, when its purpose is to remove the whole app.

You can, however, pass service names to `stop`, `kill` and `rm`.

**Comment by aschrijver** [comment]
Ah, that makes sense, then. Thank you!
