### ISSUE TITLE
client and server don't have same version (client : 1.12, server: 1.10)

### ISSUE THREAD

**Issue by trungtuan** [docker/compose#323]
Hi there, 

I am having problem running fig/docker on Ubuntu 14.04 desktop 64 bit VM. Docker is running very well without any error. However, # fig up or # fig ps all yield the error

client and server don't have same version (client : 1.12, server: 1.10)
Not sure what went wrong because all Google result point to boot2docker, which is not quite relevant is it?

Thanks

**Comment by bitliner** [comment]
running `docker-compose up` throws 

```
client and server don't have same version (client : 1.14, server: 1.12)
```

and I am using `Docker version 1.0.1, build 990021a`.

docker info's output
```
Containers: 1
Images: 16
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 18
Execution Driver: native-0.2
Kernel Version: 3.13.0-37-generic
WARNING: No swap limit support
```

**Comment by decoomanj** [comment]
Same here, but it seems only to happen during the installation. 

    + sudo -E sh -c docker version
    Client version: 1.5.0
    Client API version: 1.17
    Go version (client): go1.4.1
    Git commit (client): a8a31ef
    OS/Arch (client): linux/amd64
    FATA[0000] Error response from daemon: client and server don't have same version (client : 1.17, server: 1.15) 


When you restart the docker service and then run "sudo docker version", all seems to be installed fine.

    Client version: 1.5.0
    Client API version: 1.17
    Server version: 1.5.0
    Server API version: 1.17

**Comment by bitliner** [comment]
Well, maybe version 1.0.1 is not supported. I will try updating docker to latest versions

**Comment by aanand** [comment]
Compose requires Docker 1.3 or later.
