### ISSUE TITLE
Allow logging to be set as top level configuration

### ISSUE THREAD

**Issue by rafaelsierra** [docker/compose#3231]
When creating multiple services in a docker-compose.yml, it would be useful to set the same logging system for all services without having to set a `logging` for each service.

My suggestion would be to allow `logging` to be a top-level configuration that can be overwrite by per-service logging configuration

**Comment by omercnet** [comment]
+1

**Comment by mahnunchik** [comment]
Any news?

**Comment by shin-** [comment]
Closing via #5140

**Comment by blop** [comment]
@shin- I don't see how #5140 and custom extended fields helps with configuring logging for services at the top level of the yaml project configuration file.

Can you please reopen this issue?

**Comment by shin-** [comment]
It's literally the example we give in the docs. https://docs.docker.com/compose/compose-file/#extension-fields

**Comment by blop** [comment]
Indeed ;) Thanks
