### ISSUE TITLE
document that `run -T` is needed to preserve stdout / stderr streams

### ISSUE THREAD

**Issue by cjerdonek** [docker/compose#3239]
In Docker Compose 1.5.1, I'm noticing that `docker-compose run` sends stderr from the running process to stdout of the process calling `run`. Is this intended?

[This comment](https://github.com/docker/compose/issues/2115#issuecomment-193420167) states that--

> docker-compose prints informational messages to stderr, and container output to the same stream as it was written to in the container (stdout or stderr).

but this isn't what I'm observing.

**Comment by aanand** [comment]
Yeah, that's not quite accurate - we should document this.

By default, `run` creates a container with a pseudo-tty attached. This necessarily means that all output goes to stdout. You can disable this with the `-T` option, which will get you stdout/stderr mapping.

```console
$ docker-compose run web sh -c "echo stdout; >&2 echo stderr" 2> /dev/null
stdout
stderr

$ docker-compose run -T web sh -c "echo stdout; >&2 echo stderr" 2> /dev/null
stdout

$ docker-compose run -T web sh -c "echo stdout; >&2 echo stderr" > /dev/null
stderr
```

**Comment by cjerdonek** [comment]
Great. Thanks so much for the explanation, @aanand. Should this issue be relabeled / left open as a documentation issue?

**Comment by aanand** [comment]
Yeah, I've reclassified it as a docs issue.

**Comment by cjerdonek** [comment]
@aanand Hmm, so I tried the `-T` option with `docker-compose run`, and I'm seeing non-deterministic behavior. Sometimes stdout is captured, and other times it isn't.

Is this a known issue? Is there known flakiness when capturing stdout with `-T`? Thanks a lot.

**Comment by aanand** [comment]
That's not a known issue, no. We've had flakes of that kind in the past though. If you can produce a minimal failing case, please open a new issue for it.

**Comment by cjerdonek** [comment]
Okay, thanks, @aanand. I'll open a separate issue, but I was able to reproduce with the following:

    $ docker-compose run -T web python3 -c "import sys; print(\"err\\n\", file=sys.stderr); print(\"foo\\nfoo\\nfoo\\nfoo\\n\")"

Half the time "err" doesn't  print, and 1 out of 8 times or so, the "foo" lines don't print.

**Comment by ijc** [comment]
Issue grooming: Docs now say:
```
    -T                    Disable pseudo-tty allocation. By default `docker-compose run`
                          allocates a TTY.
```
which I think is what was being discussed. Closing.
