### ISSUE TITLE
env_file not able to parse spaces

### ISSUE THREAD

**Issue by altsalt** [docker/compose#3240]
Currently, there appears to be no way to add a space character to an env_file entry.

Here are some of the combinations I have tried:

```
VAR=foo bar
VAR=foo\ bar
VAR='foo bar'
VAR="foo bar"
VAR='foo\ bar'
VAR={foo bar}
"VAR='foo bar'"
'VAR="foo bar"'
VAR=foo%20bar
VAR=foo&nbsp;bar
etc ...
```

I am using Docker 1.10.3 and Compose 1.7.0

This issue seems to be directly related to https://github.com/docker/docker/issues/12997 which looked to be closed unsatisfactorily.

Another related issue may be: https://github.com/docker/compose/issues/2854

Any fix or work-around would be appreciated.

Thanks!

**Comment by dnephin** [comment]
My understanding is that the first one should work. The quotes will be taken literally, so nothing with quotes will be correct.

**Comment by altsalt** [comment]
Unfortunately it just ends up as VAR=foo

**Comment by dnephin** [comment]
```
$ docker run -ti --env-file envs alpine:3.3 env
WITH_SPACE=foo bar
WITH_ESCAPE=foo\ bar

$ docker-compose up
Creating network "envfile_default" with the default driver
Creating envfile_web_1
Attaching to envfile_web_1
web_1  | WITH_ESCAPE=foo\ bar
web_1  | WITH_SPACE=foo bar
envfile_web_1 exited with code 0
```

Seems to work for me with both space and backslash.  I suspect the issue is in the script you're using to consume the variable.

**Comment by junneyang** [comment]
so, what's the solution?

**Comment by takano32** [comment]
@junneyang 
this issue may be duped with https://github.com/docker/compose/issues/2854 .
