### ISSUE TITLE
Document that scaled services can be load balanced with DNS round robin in Docker 1.11

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#3251]
If you scale a service in Docker 1.11, the service name will resolve to all of the containers in that service with DNS round robin, so you can do rudimentary load balancing.

i think this is really cool and it should probably be documented so other people can also think this is really cool. :cake:

More detail: https://github.com/docker/libnetwork/pull/974

**Comment by jpetazzo** [comment]
Extra note: while the DNS resolver in Engine 1.11 will randomize records (i.e. return them in a different order at each request), most DNS resolvers will sort the records; so a "naive" client will end up always connecting to the same backend.

FWIW, I'm successfully using `jpetazzo/hamba` and `jpetazzo/watchdns` to automatically reconfigure a HAProxy load balancer with the DNS records sent by the Engine.

**Comment by marcosnils** [comment]
@jpetazzo if your app uses the embedded DNS round robin and you configure a proper DNS refresh interval is still ambassador necessary?. This way you don't need to restart your consumer each time your service changes.

**Comment by jpetazzo** [comment]
Yes, the ambassador pattern still applies. Round robin DNS is great for discovery, but doesn't provide fair balancing with most client resolvers out there.

**Comment by marcosnils** [comment]
@jpetazzo fair enough!
