### ISSUE TITLE
scaling with load balancer requires --force-recreate (at least in version 1) -- it shouldn't

### ISSUE THREAD

**Issue by kklepper** [docker/compose#3255]
I use `dockercloud-haproxy` to load balance web (and db) and docker-compose version 1 as version 2 does not work. 

Scaling is fine but does not work unless `--force-recreate` is used which recreates **every** service. 

Recreation is not necessary **except** for the load balancer and wastes time, especially in the case of databases shutting down and restarting, linearly related to the number of scaled services.

Using `docker-compose restart --force-recreate lb` results in an error (unerstandably), while `docker-compose restart lb`pretends to restart the service but does not achieve the desired result. Why? It should resolve the problem hands down.

Of course, manipulating the `dockercloud-haproxy`-mechanisms (python code) will fix this, but the resolution should not be left to user code. docker-compose should resolve this issue.

Or am I overlooking something here?

**Comment by jpetazzo** [comment]
Thanks for the report! Would you be able to provide a minimal Compose file allowing to reproduce the issue?

**Comment by kklepper** [comment]
Take `helloworld` and `dockercloud/haproxy`:

    #docker-compose.yml

    #version: '2'
    #services:
    #does not work yet
    
      helloworld:
        build: .
        expose:
          - 5000
    #    ports:
    #      - "80:80"
      lb:
        image: dockercloud/haproxy
        links:
          - helloworld
        ports:
          - "80:80"
          - "1936:1936"                              # for stats
        expose:
          - 80
        environment:
          - BACKEND_PORT=5000
          - BALANCE=roundrobin
          - STATS_AUTH=admin:admin
    
Start services:

    $ docker-compose up -d && docker-compose ps && sudo docker-compose ps
    Creating dockercloudhelloworld_helloworld_1
    Creating dockercloudhelloworld_lb_1
                   Name                             Command               State                          Ports
    ---------------------------------------------------------------------------------------------------------------------------------
    dockercloudhelloworld_helloworld_1   /bin/sh -c php-fpm -d vari ...   Up      5000/tcp, 80/tcp
    dockercloudhelloworld_lb_1           dockercloud-haproxy              Up      0.0.0.0:1936->1936/tcp, 443/tcp, 0.0.0.0:80->80/tcp
                        
Test it:

    curl localhost

You should see the `HOSTNAME` variable. Now scale up:

    $ docker-compose scale helloworld=5 && docker-compose up -d 
    Creating and starting 2 ... done
    Creating and starting 3 ... done
    Creating and starting 4 ... done
    Creating and starting 5 ... done
    dockercloudhelloworld_helloworld_5 is up-to-date
    dockercloudhelloworld_helloworld_4 is up-to-date
    dockercloudhelloworld_helloworld_3 is up-to-date
    dockercloudhelloworld_helloworld_2 is up-to-date
    dockercloudhelloworld_helloworld_1 is up-to-date
    dockercloudhelloworld_lb_1 is up-to-date    

Test again. You will see the same `HOSTNAME` variable no matter what. Test failed. No load balancing.

Now apply `--force-recreate`:

    $ docker-compose scale helloworld=5 && docker-compose up --force-recreate -d 
    Desired container number already achieved
    Recreating dockercloudhelloworld_helloworld_5
    Recreating dockercloudhelloworld_helloworld_4
    Recreating dockercloudhelloworld_helloworld_3
    Recreating dockercloudhelloworld_helloworld_2
    Recreating dockercloudhelloworld_helloworld_1
    Recreating dockercloudhelloworld_lb_1        

Test again. You will see 5 different `HOSTNAME` variables as is to be expected. Test succeeded.

If we had applied this parameter to begin with, load balancing would have worked out of the box.

If you uncomment `version: '2'` and `services:` you get:

    $ docker-compose down && docker-compose up -d && docker-compose ps
    Stopping dockercloudhelloworld_lb_1 ... done
    Stopping dockercloudhelloworld_helloworld_1 ... done
    Stopping dockercloudhelloworld_helloworld_2 ... done
    Stopping dockercloudhelloworld_helloworld_3 ... done
    Stopping dockercloudhelloworld_helloworld_4 ... done
    Stopping dockercloudhelloworld_helloworld_5 ... done
    Removing dockercloudhelloworld_lb_1 ... done
    Removing dockercloudhelloworld_helloworld_1 ... done
    Removing dockercloudhelloworld_helloworld_2 ... done
    Removing dockercloudhelloworld_helloworld_3 ... done
    Removing dockercloudhelloworld_helloworld_4 ... done
    Removing dockercloudhelloworld_helloworld_5 ... done
    Removing network dockercloudhelloworld_default
    Creating network "dockercloudhelloworld_default" with the default driver
    Creating dockercloudhelloworld_helloworld_1
    Creating dockercloudhelloworld_lb_1
               Name                             Command               State                          Ports
    ---------------------------------------------------------------------------------------------------------------------------------
    dockercloudhelloworld_helloworld_1   /bin/sh -c php-fpm -d vari ...   Up      5000/tcp, 80/tcp
    dockercloudhelloworld_lb_1           dockercloud-haproxy              Up      0.0.0.0:1936->1936/tcp, 443/tcp, 0.0.0.0:80->80/tcp
    $ curl localhost
    curl: (52) Empty reply from server

**Comment by dnephin** [comment]
You can use 

```
docker-compose up -d --force-recreate lb
```

That will only recreate the load balancer. This is going to be necessary for any load balancer that only reads its configuration once. I'm not that familiar with the `dockercloud/haproxy` image, maybe it will pick up the new containers if you send it `SIGHUP` ?

**Comment by kklepper** [comment]
@dnephin Thank you, I tried your advice -- but no, the last parameter is not used, all containers are recreated:

    $ docker-compose up -d --force-recreate lb
    Recreating mariadb_data_1
    Recreating mariadb_db_2
    Recreating mariadb_db_1
    Recreating mariadb_lb_1

If it worked, it would be the functionality needed here.

But you are definitely right, the wider question should not beconsidered a problem of docker or docker-compose but of haproxy. This tutum-haproxy implementation does not monitor container instances which is what you want -- for example if one container is killed.

That's apparently not that easy which is probably the reason why complex solutions like kubernetes, rancher, consul have been developed. 

Anyway, in normal situations when changes only appear during scaling, it would be fine to be able to just restart the haproxy container. Of course, surplus or superfluous containers have to be started or killed, but why must running containers be recreated?

Apart from this, it should be possible to ramp haproxy up with the capabilities needed - maybe with xinetd.

**Comment by kklepper** [comment]
@dnephin How do I send SIGHUP to a container?

**Comment by dnephin** [comment]
`docker-compose kill -s SIGHUP lb`

**Comment by kklepper** [comment]
@dnephin Thank you. Did not work. I should inspect the python scripts of haproxy to get mmore insight into the mechanisms at work here.

**Comment by kklepper** [comment]
@jpetazzo With respect to my answer I should add that `build: .` refers to `https://github.com/docker/dockercloud-hello-world`

**Comment by kklepper** [comment]
@jpetazzo Another detail: I'm using AWS EC2 Ubuntu t2.micro

**Comment by kklepper** [comment]
dockercloud/haproxy obviously isn't fit for the job as it isn't aware of starting and stopping containers. I was able to construct a scheme with consul and registrator which are especially constructed for this kind of service.
