### ISSUE TITLE
Compose breaks when using new client credentials store

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#3265]
[Docker 1.11 has a new client credentials store.](https://github.com/docker/docker/pull/20107) This results in `~/.docker/config.json` files which look a bit like this:

```
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"credsStore": "osxkeychain"
}
```

This breaks Compose:

```
$ docker-compose up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 57, in main
  File "compose/cli/main.py", line 105, in perform_command
  File "compose/cli/command.py", line 31, in project_from_options
  File "compose/cli/command.py", line 76, in get_project
  File "compose/cli/command.py", line 49, in get_client
  File "compose/cli/docker_client.py", line 75, in docker_client
  File "site-packages/docker/client.py", line 60, in __init__
  File "site-packages/docker/auth/auth.py", line 188, in load_config
  File "site-packages/docker/auth/auth.py", line 130, in parse_auth
docker.errors.InvalidConfigFile: Invalid configuration for registry https://index.docker.io/v1/
docker-compose returned -1
```

Ideally, we should support the new client credentials store. As an intermediate step, we should probably not throw traceback and instead display a helpful error saying that it isn't supported yet.

**Comment by dnephin** [comment]
This fix needs to happen in docker-py

**Comment by shin-** [comment]
So I guess an empty dictionary is now a valid value in the `auths` dictionary. That kinda weakens our validation but that should be fine.

As an aside, is there a way we could have known about this new feature sooner (and those like it when they affect us) ? What can we do better to find out about those, and is there some process that would let information like that trickle down better (ideally as soon as they merge instead of two weeks into code freeze)? > @bfirsh @dmp42

**Comment by dnephin** [comment]
Fixed by #3276

**Comment by EugenMayer** [comment]
Is this already released? I cannot use `docker-compose pull` still, having:

```
```

**Comment by grosskur** [comment]
@EugenMayer See #3622. I think this issue being closed simply means docker-compose no longer crashes when it encounters the `credsStore` key in `~/.docker/config.json`. Now it just ignores the key and fails later on when pulling or pushing images (due to lack of credentials).

**Comment by 453907336** [comment]
Delete content in auths
