### ISSUE TITLE
Tls flags with 1.7.0 RC1 gives errors

### ISSUE THREAD

**Issue by datacarl** [docker/compose#3272]
```
./run.sh --tlsverify --tlscacert=/path/ca.pem --tlscert=/path/client-cert.pem --tlskey=/path/client-key.pem up
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.0rc1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 57, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 105, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 30, in project_from_options
    tls_config=tls_config_from_options(options),
  File "/usr/lib/python2.7/site-packages/compose/cli/docker_client.py", line 37, in tls_config_from_options
    hostname or not options.get('--skip-hostname-check', False)
  File "/usr/lib/python2.7/site-packages/docker/tls.py", line 47, in __init__
    'Path to a certificate and key files must be provided'
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
```

```
./run.sh -v
docker-compose version 1.7.0rc1, build 1ad8866
```

Running on CentOS 7.

Happy to provide more info as necessary.

**Comment by shin-** [comment]
do `/path/client-cert.pem` and `/path/client-key.pem` both exist on the filesystem?

**Comment by datacarl** [comment]
> do /path/client-cert.pem and /path/client-key.pem both exist on the filesystem?

They exist on the host from which I run this command. Thinking of it, I was experimenting with Swarm. If the container ran on another host the files would not have been available to the container. Not sure if it's relevant.

**Comment by shin-** [comment]
Just to make sure I understand: does your `run.sh` script start docker-compose inside a container? If so, it is definitely relevant since the test that triggers that exception looks like 
```python
if not (tls_cert and tls_key) or (not os.path.isfile(tls_cert) or not os.path.isfile(tls_key)):
```

I'm fairly confident you're either running into a file existence or a permissions issue.

**Comment by datacarl** [comment]
It's the `run.sh` from [the release page](https://github.com/docker/compose/releases) (sorry, should have clarified that). It does start it in a container.

**Comment by shin-** [comment]
Ah, that makes sense. That script mounts a few folders for you to have the necessary configuration accessible to `docker-compose`, but `/` is obviously not included in those mounts, which is why the certificate / key can't be found. If you want to use `run.sh` as is, you could move your TLS config into a subfolder of your `$HOME`.

**Comment by datacarl** [comment]
Makes sense, thanks @shin-

**Comment by dnephin** [comment]
Removing it from the 1.7.0 milestone, but going to keep it open, so we can track all the issues related to running Compose in a container.
