### ISSUE TITLE
Enhance the pull command to honor the depends_on configuration

### ISSUE THREAD

**Issue by vultron81** [docker/compose#3282]
When you use the "up" command docker-compose uses the depends_on configuration defined in the yaml file for a given service.  However, if you "pull" a given service only its image will be pulled from the repo and not its dependencies.  It would be very helpful if the "pull" command also honored the depends_on configuration.

**Comment by mrwonko** [comment]
Interesting, because I have dependencies implicitly defined using `link` and those get pulled as well (and I actually don't want that, which is what led me here). I wonder if the behaviour differs between `link`and `depends_on`, or if different docker-compose versions behave differently...

**Comment by aanand** [comment]
@mrwonko I can't reproduce the behaviour you're seeing - neither `depends_on` nor `links` result in dependencies being pulled. What version are you using?

**Comment by mrwonko** [comment]
Weird, neither can I using 1.5.1... I'll check with my colleague later, I saw that behaviour on his machine.

**Comment by mrwonko** [comment]
Actually I did some experiments and it's actually the `docker-compose up` which will pull the dependencies if they're unavailable locally (or possible even update them? that's difficult to verify).

**Comment by aanand** [comment]
Yes, `up` pulls dependencies if they don't exist locally. It doesn't do anything if they already exist. It also honours `depends_on`.
