### ISSUE TITLE
Duplicate runs with `docker-compose run`

### ISSUE THREAD

**Issue by nathanleclaire** [docker/compose#3283]
Using: 1.7.0-rc1

(Docker 1.11.0-rc3 via boot2docker)

To duplicate:

```yaml
version: '2'

volumes:
  myvol:
    driver: local

services:
  foo:
    image: alpine
    volumes:
      - myvol:/opt/foo
    command: sh -c 'echo hi from foo >>/opt/foo/out'

  bar:
    image: alpine
    volumes:
      - myvol:/opt/bar
    command: sh -c 'echo hi from bar >>/opt/bar/out'

  quux:
    image: alpine
    volumes:
      - myvol:/some/arbitrary/dir
    command: sh -c 'cat /some/arbitrary/dir/out'
```

Running from a fairly clean daemon state (no volumes or containers):

```console
$ docker-compose run foo
Creating volume "demo_myvol" with local driver
$ docker-compose run bar
$ docker-compose run quux
hi from foo
hi from bar
hi from bar
```

Seems there was an extra `run` of `bar` that wasn't asked for.

If I clean up and try again, it seems there is an equal chance that `foo`, `bar`, or both, have been accidentally run more times than requested.

```console
$ docker rm -f $(docker ps -aq) && docker volume rm demo_myvol
...

$ docker-compose run foo && docker-compose run bar && docker-compose run quux
Creating volume "demo_myvol" with local driver
hi from foo
hi from foo
hi from bar

$ docker rm -f $(docker ps -aq) && docker volume rm demo_myvol
...

$ docker-compose run foo && docker-compose run bar && docker-compose run quux
Creating volume "demo_myvol" with local driver
hi from foo
hi from foo
hi from bar
hi from bar

$ docker rm -f $(docker ps -aq) && docker volume rm demo_myvol
...

$ docker-compose run foo && docker-compose run bar && docker-compose run quux
Creating volume "demo_myvol" with local driver
hi from foo
hi from foo
hi from bar
hi from bar
```

**Comment by nathanleclaire** [comment]
cc @dnephin @aanand @shin-

**Comment by nathanleclaire** [comment]
Let me know if you'd like verbose output as well.

**Comment by shin-** [comment]
My intuition is that this is the same issue as #3271 . Can you test #3278
and check it fixes your issue as well?

**Comment by dnephin** [comment]
I don't think we use that parallel code for `run`

**Comment by dnephin** [comment]
I was able to reproduce this once, and now I can't get it to happen again in 30+ attempts...

I'm running `docker-compose down -v` to perform the cleanup. If you run that, does the problem go away by chance?

**Comment by nathanleclaire** [comment]
> I'm running docker-compose down -v to perform the cleanup. If you run that, does the problem go away by chance?

I'll try it using the same RCs.

**Comment by nathanleclaire** [comment]
Welp, I'm having a hard time reproducing on a brand new VM using those RCs (Engine latest and Compose latest).  So, I guess we can close this, although it may have been due to some kind of state I had in the VM previously.  I'll let you all know if I see any similar issues, I'm also running a script to see if I can dupe again, but after a lot of iterations so far I haven't seen it again.
