### ISSUE TITLE
Customize the IP of bridge in docker-compose v2 template

### ISSUE THREAD

**Issue by reasonerjt** [docker/compose#3287]
After running docker-compose up, a new bridge will be created.

\# docker network ls
NETWORK ID          NAME                DRIVER
f4f2af093035        bridge              bridge
**65b0cf530cec        deploy_default      bridge**
0e2eb3cf1040        none                null
b9d3550256af        host                host

Is it possible to customize the IP of the new bridge?  I went through the docs and didn't find any information about this question.

**Comment by dnephin** [comment]
You can set an ip address by using ipam config: https://docs.docker.com/compose/compose-file/#ipam

The name of the default network is `default`, so something like this should work:

```yaml
networks:
  default:
    ipam:
      config:
        ...

```

**Comment by reasonerjt** [comment]
Thanks
