### ISSUE TITLE
disabled: true (feature request)

### ISSUE THREAD

**Issue by mwarren2** [docker/compose#3289]
In development I often fiddle with my docker compose .yml files, disabling and reenabling entire sections.

The only way to do this in a .yml file appears to be to add a gate (#) at the begin of each line, which is fairly laborious.
I'd love to be able to just put **disabled: true** at the top of the section instead.

**Comment by dnephin** [comment]
I believe this is covered by #1896

**Comment by mwarren2** [comment]
You're right. Massive debate. That's great.
Didn't find it because it's in the main docker bit, and I was looking for it here.

Will close.
