### ISSUE TITLE
log_opt, log_driver ignored in compose 1.6.2

### ISSUE THREAD

**Issue by addedsparkle** [docker/compose#3307]
I use two docker-compose.yml files to use JSON logging in development but syslog in production environment.

With 1.5.1 everything worked fine, using --verbose I can see the LogConfig setting the type to syslog with the correct options. When I upgrade to 1.6.2 though the LogConfig is no longer changed to syslog and instead stays on json and docker logs will output the logs instead of returning the error that you can only do this for json and journald.

Example config:

Service in base docker-compose.yml:

`feature:
    image: xxxxxx/feature:1.1.0-m.1
    hostname: feature
    dns: 127.0.0.1
    restart: always
    links:
     - consul:consul
    volumes:
     - /data/feature:/data`

and the output of docker-compose --verbose up

`compose.cli.verbose_proxy.proxy_callable: docker create_container <- (hostname='feature', name=u'xxxxx_feature_1', image='xxxxxx/feature:1.1.0-m.1', labels={u'com.docker.compose.service': u'feature', u'com.docker.compose.project': u'xxxxx', 'com.docker.compose.config-hash': 'afec4ce383dbbc335a09a18a5391805b38d1a6a8d0e30db577f3731f7cde330b', 'com.docker.compose.version': u'1.5.1', u'com.docker.compose.oneoff': u'False', 'com.docker.compose.container-number': '1'}, host_config={'Links': ['xxxxx_consul_1:consul', 'xxxxx_consul_1:consul_1', 'xxxxx_consul_1:xxxxx_consul_1', 'xxxxx_kibana_1:xxxxx_kibana_1', 'xxxxx_kibana_1:kibana', 'xxxxx_kibana_1:kibana_1'], 'PortBindings': {}, 'Binds': [u'/data/feature:/data:rw'], 'RestartPolicy': {u'MaximumRetryCount': 0, u'Name': u'always'}, 'Dns': ['127.0.0.1'], 'ExtraHosts': [], 'LogConfig': {'Type': 'syslog', 'Config': {'syslog-tag': '{{.Name}}', 'syslog-address': 'tcp://localhost:5000'}}, 'VolumesFrom': []}, environment={}, volumes={u'/data': {}}, detach=True)`

Service in override docker-compose.yml:

`feature:
    log_driver: syslog
    log_opt: 
      syslog-address: "tcp://localhost:5000"
      syslog-tag: "{{.Name}}"
    links:
     - consul:consul
     - kibana:kibana`

and the output of docker-compose --verbose up

`compose.cli.verbose_proxy.proxy_callable: docker create_container <- (hostname='feature', name=u'xxxxx_feature_1', image='xxxxxx/feature:1.1.0-m.1', labels={u'com.docker.compose.service': u'feature', u'com.docker.compose.project': u'xxxxx', u'com.docker.compose.config-hash': '6eee21dc4b7cbef1b410ca92840d9d8ae60c5c27aea63168aba353fd04903616', u'com.docker.compose.version': u'1.6.2', u'com.docker.compose.oneoff': u'False', u'com.docker.compose.container-number': '1'}, host_config={'NetworkMode': 'default', 'Links': ['xxxxx_consul_1:consul', 'xxxxx_consul_1:consul_1', 'xxxxx_consul_1:xxxxx_consul_1', 'xxxxx_kibana_1:xxxxx_kibana_1', 'xxxxx_kibana_1:kibana', 'xxxxx_kibana_1:kibana_1'], 'PortBindings': {}, 'Binds': [u'/data/feature:/data:rw'], 'RestartPolicy': {u'MaximumRetryCount': 0, u'Name': u'always'}, 'Dns': ['127.0.0.1'], 'LogConfig': {'Type': u'', 'Config': {}}, 'VolumesFrom': []}, environment=[], volumes={u'/data': {}}, detach=True)`

I've looked in the Changelog and can't see any indication that support for the Version 1 logging options has been dropped.

**Comment by dnephin** [comment]
This is fixed in master and in 1.7.0-rc1 , by #3052
