### ISSUE TITLE
docker-compose returns not found on Alpine Linux 3.3 64 bits

### ISSUE THREAD

**Issue by nsteinmetz** [docker/compose#3309]
Hi,

On Alpine Linux 3.3 64 bits, I have an issue with docker-compose:

```
curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose 
/usr/local/bin/docker-compose --version
-ash: /usr/local/bin/docker-compose: not found
docker-compose --version
-ash: docker-compose: not found
```

Using ``bash`` instead of default shell returns the same answer.

I have:

```
ls -al /usr/local/bin/docker-compose 
-rwxr-xr-x    1 root     root       7929597 Apr 11 21:12 /usr/local/bin/docker-compose
```

Regarding docker by itself, I use alpine package in community repo.

```
which docker
/usr/bin/docker
cvsq:~# docker -v
Docker version 1.10.3, build a5815f5
```

Using binary docker instead of alpine package does not change anything.

Any idea on the proper way to use docker-compose in an Alpine box ?

Thanks,
Nicolas

**Comment by dnephin** [comment]
The Compose binary is dynamically linked against glibc which is not available on alpine. I believe that's why you get a `not found`.

You can install it from source using `pip`: https://docs.docker.com/compose/install/#install-using-pip

**Comment by nsteinmetz** [comment]
Hi @dnephin 

Indeed, it works this way.

Thanks for the precision regarding glibc.

Have a nice day,
Nicolas

**Comment by silencej** [comment]
Use docker compose.

```bash
apk add docker-cli-compose
```

https://stackoverflow.com/a/71231139/6191913
