### ISSUE TITLE
Pass --detach-keys to docker-compose

### ISSUE THREAD

**Issue by Gijsjan** [docker/compose#3311]
`docker run` has the option to pass an alternative sequence to detach. Currently it is mapped to `ctrl-p ctrl-q`, but I heavily use `ctrl-p` in the cli and Vim, so I would like to remap. Is that possible with Compose? If not, this is a feature request. :)

**Comment by crhan** [comment]
while docker cli supports detach-keys. I do want the same feature applied in docker-compose too.

**Comment by vladimir-mencl-eresearch** [comment]
+1 - this would be a very useful feature

**Comment by qinix** [comment]
+1

**Comment by ihucos** [comment]
+1

**Comment by 110y** [comment]
+1

**Comment by ihucos** [comment]
+1

**Comment by schasse** [comment]
:+1:

**Comment by jaywhy13** [comment]
+1 Question though... it's possible to save detachKeys in ~/.docker/config.json. When Compose runs Docker, why doesn't it use these configs?

**Comment by chhabrakadabra** [comment]
+1

**Comment by 110y** [comment]
My workaround
```
docker container exec -it $(docker-compose ps -q mycontainer) bash
```

**Comment by scmx** [comment]
I'm experiencing the same issue. (using Docker for Mac)

I've remapped my `~/.docker/config.json` like this:
```json
{
  "detachKeys": "ctrl-q,ctrl-q"
}
```
and it's working fine for normal `docker run` but not for `docker-compose`.

Would be awesome if the config file was read when using `docker-compose`. 🎉  Keep up the good work with this tool.

**Comment by kelly-apollo** [comment]
+1

**Comment by amosbird** [comment]
Hi, is there a pr for this?

**Comment by geezhawk** [comment]
+1

**Comment by scrooloose** [comment]
+1

**Comment by ihucos** [comment]
+1 again

**Comment by 0xBADDCAFE** [comment]
+1

**Comment by kdeloach** [comment]
+1

**Comment by Nondv** [comment]
Is there any movement?

+1

**Comment by summergirl21** [comment]
Is this something that would be useful? If so I would be interested in tackling it.

**Comment by jaywhy13** [comment]
Yes! Exceptionally so

**Comment by Nondv** [comment]
@summergirl21 for example, it's not really comfy to use bash history via `C-p` because docker treats it as  prefix and waits for next key. This is kinda frustrating:)

**Comment by mtsmfm** [comment]
I sent a PR to fix this problem.
https://github.com/docker/docker-py/pull/1826

I guess it takes a while to get merged and released so I built patched docker-compose:
https://bintray.com/mtsmfm/docker/compose#files

It respects [our `detachKeys` setting](https://github.com/docker/compose/issues/3311#issuecomment-293512041) as well as docker does.

Please let me know if you find any bugs 🐛

**Comment by hongliang5316** [comment]
Nice Job 👍 .

**Comment by jaywhy13** [comment]
Awesome

**Comment by lusitania** [comment]
AFAICS docker/docker-py#1826 was merged 2018-01-31 for milestone 3.0.0. Can this issue be closed @Gijsjan, @mtsmfm?

**Comment by mtsmfm** [comment]
> In which version of docker-compose will this feature become available?

It's available from docker-compose 1.20.0

https://github.com/docker/compose/commit/d8d484e0e19db5326afeb4cdf56864eceb81566c#diff-b4ef698db8ca845e5845c4618278f29a

**Comment by nroose** [comment]
This is again an issue for me. It was fixed for a long time with the .docker/config.json change, but now it's back.

**Comment by Jakob-Koschel** [comment]
same issue here

**Comment by balazs14** [comment]
I had docker.app running on an M1 mac, the detachKey (Ctrl-P remapped to something else) used to work. Now I am on an intel mac, probably has a later version of docker.app, and indeed it no longer works.

**Comment by georgexsh** [comment]
This problem has returned, at least for me.

**Comment by scmx** [comment]
> This problem has returned, at least for me.

Did you try https://github.com/docker/compose/issues/3311#issuecomment-293512041 ? It worked for me again just now (with docker compose).

**Comment by georgexsh** [comment]
> Did you try [#3311 (comment)](https://github.com/docker/compose/issues/3311#issuecomment-293512041) ? It worked for me again just now (with docker compose).

I didn't notice that configuration, it’s been my machine for a while, and I just confirmed it works on Docker Desktop 4.67.0, thanks for pointing it out.
What I meant was that `docker compose exec --detach-keys 'ctrl-_,d' ...` doesn't work.
