### ISSUE TITLE
Running a container impossible if `NetworkSettings.Networks` is None

### ISSUE THREAD

**Issue by lukasjuhrich** [docker/compose#3315]
If `NetworkSettings.Networks` is None when trying to run a container, this fails because in [compose/service.py:453](https://github.com/docker/compose/blob/master/compose/service.py#L453), `connected_network` may be `None`(or does it?) when assigned. Because `connected_network` is used in an `__contains__` check later on, a `TypeError` is raised.

This happens using `docker-compose v. 1.6.2dev` as well as a cloned version using commit:f10bc8072ed9e2b043cf3dae602a03143858b712

Used `.yml`: https://github.com/lukasjuhrich/sipa/blob/docker_compose_failure/testing.yml
Used `Dockerfile`: https://github.com/lukasjuhrich/sipa/blob/docker_compose_failure/Dockerfile

It seems suspicious to me that there don't exist any `Networks` in the `NetworkSettings`.  If I can debug things further, please guide me concerning how to debug this, since I do not know a lot about docker{,compose} internals (I know some things about python though).

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.6.2', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 56, in main
    command.sys_dispatch()
  File "/usr/lib/python3.5/site-packages/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python3.5/site-packages/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 191, in perform_command
    handler(project, command_options)
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 524, in run
    run_one_off_container(container_options, project, service, options)
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 744, in run_one_off_container
    service.start_container(container)
  File "/usr/lib/python3.5/site-packages/compose/service.py", line 427, in start_container
    self.connect_container_to_networks(container)
  File "/usr/lib/python3.5/site-packages/compose/service.py", line 435, in connect_container_to_networks
    if network in connected_networks:
TypeError: argument of type 'NoneType' is not iterable
```

I hope I did provide enough information.  I could open up a PR with an if-none-return check once it is confirmed this is a bug.  For including a test I might need some guidance.

**Comment by dnephin** [comment]
This could be a python 3.5 issue. Are you able to try it out with python 2.7 to see if you still have the problem?

**Comment by lukasjuhrich** [comment]
@dnephin I set up two virtualenvs:
- `Python 3.5.1`
- `Python 2.7.11`
Testing on commit f10bc8072ed9e2b043cf3dae602a03143858b712 with _py2_, I get a different stacktrace:

```
ERROR: for sipa_testing  argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "compose/cli/main.py", line 57, in main
    command()
  File "compose/cli/main.py", line 108, in perform_command
    handler(command, command_options)
  File "compose/cli/main.py", line 739, in up
    remove_orphans=remove_orphans)
  File "compose/project.py", line 395, in up
    get_deps
  File "compose/parallel.py", line 60, in parallel_execute
    raise error_to_reraise
TypeError: argument of type 'NoneType' is not iterable
```
Which seems to be some exception wrapping (whyever this parallelization doesn't affect the py3 version) not giving the original stacktrace, unfortunately – but it seems obvious that this is effectively the same error.

I could try out different commits, but I'm a bit confused about which to test – there seem to be some changes in 1.7.x not included in the master. Any recommendations on how to get more information?

**Comment by dnephin** [comment]
Thanks for confirming this isn't a Py3 issue.

What's the output of `docker info` ? The NetworkSettings section should really be populated. This may be a bug with the engine you're running against. I've never seen that section empty before.

**Comment by lukasjuhrich** [comment]
`docker info`:
```
Containers: 173
Images: 1349
Server Version: 1.10.0-dev
Storage Driver: devicemapper
 Pool Name: docker-254:3-262145-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 33.39 GB
 Data Space Total: 107.4 GB
 Data Space Available: 26.28 GB
 Metadata Space Used: 79.33 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.068 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.121 (2016-03-26)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.5-1-ARCH
Operating System: Arch Linux (containerized)
CPUs: 4
Total Memory: 7.5 GiB
Name: juhrilaptop
ID: UUIA:BL3M:GWUG:T7HZ:W2LH:GTUH:RQLT:F5VU:K3JT:LKZN:EQEU:6URR
Username: lukasjuhrich
Registry: https://index.docker.io/v1/
```

The irony here is that the container cannot be inspected to provide some further details, because running it in `docker-compose` fails and the container thus doesn't exist.

**Comment by dnephin** [comment]
It looks like you're running a dev release. Can you try running the official 1.10.3 release? Or even the recently released 1.11.

**Comment by lukasjuhrich** [comment]
I just used the official 1.10.3 release, and could _not_ reproduce this behavior.

I didn't have the time to download 1.11, though. I don't know where to look for releases not packaged yet to be honest.

**Comment by dnephin** [comment]
Cool, so I think the bug was have just been in the dev version and was fixed for the release.

Going to close this issue since it looks to be fixed.
