### ISSUE TITLE
Using default env variables in compose

### ISSUE THREAD

**Issue by formerlyKurt** [docker/compose#3321]
Hi folks,

I'm wondering whether there is support for default values in Compose v1.6.2.  I've been trying to do the following:

`image: postgres:${VERSION:-latest}`

This results in an error.  Is this the correct format?

**Comment by dnephin** [comment]
Not yet, see #2441

**Comment by FreedomBen** [comment]
"see #2441 " is not terribly helpful.  Maybe it's there and I missed it, but I don't see anything other than people asking if this will be implemented (with nobody confirming or denying).  Also those are all months old.   

tl;dr for other people that land here:  this may or may not have already been implemented but docs have not been updated if it has been implemented.  if not implemented, it may or may not be implemented in the future.
