### ISSUE TITLE
Mounting into a copied folder results in broken files?

### ISSUE THREAD

**Issue by tspecht** [docker/compose#3324]
I think this is machine related, but I'm not sure. I'm using the most current docker toolbox with docker 1.10.3 on OSX
I have a project using a Dockerfile, which copies code into the container like this:
```
COPY . /code
VOLUME /code
WORKDIR /code
```
For faster local development (test execution), we mount the current directory in the compose file

```
volumes:
      - .:/code
```
and execute

docker-compose -f docker-compose.yml -f docker-compose.testing.yml run web py.test
Now, it looks like I have two different folders/files:
when running the container and looking inside a file with vi, everything looks like on the host. Changing files and executing our tests (pytest, specifically) lets the python interpreter read garbage so it can't execute the tests.

Example

the end of a file looks like this (which got copied in the Dockerfile into the container):

`post_save.connect(backup_something, sender=SomeSender, dispatch_uid='backup_something') foobar`
this obviously raises an error when executing, so I change it to

`post_save.connect(backup_something, sender=SomeSender, dispatch_uid='backup_something')`
the file looks fine now, both from the host and inside the container.
Executing pytest, it still reads the content of the copied code, breaking the tests locally for me.

If I change even more, it's neither the copied nor the mounted file, so stuff breaks at random positions:
```
File "/code/some_code.py", line 69
    dispatch_uid='backup_
                        ^
SyntaxError: EOL while scanning string literal
(tail shows correct syntax etc, there is definitely nothing broken with the code)
```
Is there something wrong with our setup or is it just my machine being broken somehow? I tried restarting and recreating the docker machine but this doesn't help.
Anybody got a clue what's going on here?

**Comment by dnephin** [comment]
I think you're right, this is a bug with virtualbox (used by docker-machine) file shares.

You might want to try recreating the machine, instead of just restarting it.

**Comment by tspecht** [comment]
Unfortunately this is not an option for the team since we are having this issue far too often to recreate the machine every time :/ Any ETA on the fix?

**Comment by dnephin** [comment]
I would look for a related issue on https://github.com/docker/machine

I think the "fix" will be to use [Docker for Mac](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/) instead of virtualbox, when it's available.

**Comment by tspecht** [comment]
I tried to get into the beta but I'm still waiting for the invite ... any chance you could help me out on that? :P I also already opened an issue on docker machine but didn't really get a response there

**Comment by shin-** [comment]
In case you missed it, Docker for Mac is available for the general public now. Since this is not really a Compose issue, I'm going to close the ticket, but feel free to comment or re-open if there's more we can do to help.
