### ISSUE TITLE
docker-compose.yml missing some docker run options

### ISSUE THREAD

**Issue by lmmarsano** [docker/compose#3338]
Specifically the [UTS namespace mode](//docs.docker.com/engine/reference/run/#uts-settings-uts) option and probably some others.
I suggest reviewing the [current options](//docs.docker.com/engine/reference/run/) to ensure nothing's missed.

**Comment by referup-tarantegui** [comment]
Any updates on this issue?

**Comment by Bardioc1977** [comment]
Somehow this is still not working am I right? The issue is simply closed for being stale, not implemented. With docker-compose version 1.26.2 and a docker-compose.yml file set to version 3.8 you still get:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.app-server: 'uts_mode'
```

Is this correct or am I using it wrong?
