### ISSUE TITLE
Support for `docker create --userns=host`

### ISSUE THREAD

**Issue by squeaky-pl** [docker/compose#3349]
Docker 1.11 has landed new feature to disable user namespaces per container when the daemon is running with global user namespace enabled.

https://github.com/docker/docker/pull/20111

**Comment by fragpit** [comment]
Hello, 
very important issue.
I converted all docker-compose files to systemd units.

**Comment by sanmai-NL** [comment]
Off topic:
@fragpit: would be keen to see examples experiences with that! Feel free to contact me (see my website for details). :smiley:

**Comment by zh99998** [comment]
+1 for this request
