### ISSUE TITLE
"docker-compose run" should support "-v" for volumes

### ISSUE THREAD

**Issue by jamshid** [docker/compose#3350]
I'm surprised docker-compose 1.7.0 does not support the "docker run -v ..." option. I expect to be able to create and use volumes, e.g. `docker-compose run -v ./Pictures:/var/source <service> ...`. Is this planned or not a supported use case?

**Comment by sanmai-NL** [comment]
What about defining them in your `docker-compose.yml`? Why should `docker-compose` facilitate such CLI params, why then not use `docker run` directly?

**Comment by ijc** [comment]
Seems this now exists:
```
$ docker-compose run --help|& grep volume
    -v, --volume=[]       Bind mount a volume (default [])
```

**Comment by sinback** [comment]
I think it's pretty unclear how to do this from the CLI instructions, anyone got an example?
