### ISSUE TITLE
why am I getting security warning message during pull?

### ISSUE THREAD

**Issue by natarajanv** [docker/compose#3357]
In my script, I have this line

docker-compose -f "${COMPOSE_FILE}"  pull 

The warnings started one we upgraded compose to 1.2.0

Pulling cadvisor (docker-registry.mitre.org:8443/autobuild/cadvisor:master-177)... 
20-Apr-2016 08:32:46 /tmp/_MEIoXe8sl/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)

**Comment by natarajanv** [comment]
Just wanted to add some more details.

the subject alternative names are in fact defined in the certificate in question.

**Comment by dnephin** [comment]
docker-compose 1.2.0 is now 5 versions behind. I would suggest trying to upgrade to 1.7.0

**Comment by natarajanv** [comment]
Sorry, I meant to say 1.7.0 version

I was working on new swarm, and did a wrong copy and paste. So, it is happening on new version of compose 1.7.0. Sorry for the confusion

**Comment by dnephin** [comment]
Ok, please include the output of `docker-compose version`, the OS you're using, as well as details about how you installed Compose. If you used pip, please include the output of `pip freeze`.

**Comment by natarajanv** [comment]
[root@r10a-dockersb3 ~]# docker-compose version
docker-compose version 1.7.0, build 0d7bf73
docker-py version: 1.8.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

OS version :
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.2 (Maipo)
Release:        7.2
Codename:       Maipo

compose was installed by this curl command
curl -L https://github.com/docker/compose/releases/download/1.7.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

**Comment by jfchevrette** [comment]
I have the same error. I connect to a swarm cluster on a secure (TLS-enabled) port.

I guess the error means that I need to configure my certificates to have a subjectAltName?

**Comment by shin-** [comment]
This is just a warning. As observed by @jfchevrette , it is advised for your certificate to provide its DNS name as a `subjectAltName` field. As explained in [RFC 2818](https://tools.ietf.org/html/rfc2818#section-3.1):

> If a subjectAltName extension of type dNSName is present, that MUST  be used as the identity. Otherwise, the (most specific) Common Name field in the Subject field of the certificate MUST be used. Although the use of the Common Name is existing practice, it is deprecated and Certification Authorities are encouraged to use the dNSName instead.

The warning itself is raised by `urllib3` / `requests` which handles the connection to the server.
@dnephin I see you added this issue to the 1.7.1 milestone, but I don't think there is any action for us to take here. What do you suggest?

**Comment by pniederlag** [comment]
struck by the very same problem here

     usr/lib/python2.7/dist-packages/urllib3/connection.py:303: SubjectAltNameWarning

docker-compose version 1.7.1, build 6c29830 
Docker version 1.12.0-rc4, build e4a0dbc

**Comment by fitz123** [comment]
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.6
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014

```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py:303: SubjectAltNameWarning: Certificate for stream-poller-n1 has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
```
