### ISSUE TITLE
Compose getting started guide tells you to go to http://0.0.0.0:5000

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#3362]
https://docs.docker.com/compose/gettingstarted/

facepalm

**Comment by dnephin** [comment]
What's wrong with that? Those instructions are correct for linux (it's equivalent to localhost), and immediately after that we talk about how to get the ip for the VM.

**Comment by bfirsh** [comment]
Could it just mention localhost?

It might be worth putting the Machine instructions first, because most devs will be doing that. We should also need to mention `docker.local` for Docker for Mac/Windows.

I'll close this and we figure out something better here when we need to rewrite for Docker for Mac/Windows anyway.
