### ISSUE TITLE
Using a service name with 'extends'

### ISSUE THREAD

**Issue by joshwget** [docker/compose#3363]
According to the docs, the `extends` value must be a dictionary. Docker Compose also seems to support using a service name directly in `extends`, however. Is the idea to deprecate this functionality and only support dictionaries in the future? I'm curious about this mostly because I'm trying to decide whether or not this feature should be added to libcompose.

**Comment by ijc** [comment]
Issue grooming: Sorry noone ever replied. Looks like this is moot since https://github.com/docker/libcompose/commit/748d6a386a13ebc174f7e382e0fe6d04a353e8ab so I'll close.
