### ISSUE TITLE
Getting Started guide does not successfully get me started w/ docker-compose 1.7.0 / docker client+server 1.11.0, darwin/amd64

### ISSUE THREAD

**Issue by lsb** [docker/compose#3368]
Hello, thank you for your time.

I have recently installed docker-machine on my Macbook (the non-beta, via VirtualBox), and I was interested in trying docker-compose.

I went through the Getting Started documentation, and I encountered a few snags, and wanted to share them with you.

1) The built container has no code.

When running `docker-compose up`, I had gotten the error message `web_1    | python: can't open file 'app.py': [Errno 2] No such file or directory`.

When I change the CMD in https://github.com/docker/compose/blame/ac82597ac10c9a0dbd3bf25ebde792e9cc71efc4/docs/gettingstarted.md#L70 to `CMD pwd && ls -al && python app.py` the output from the web container in `docker-compose up` becomes

```
web_1    | /code
web_1    | total 4
web_1    | drwxr-xr-x  2 root root   40 Apr 21 21:52 .
web_1    | drwxr-xr-x 58 root root 4096 Apr 22 00:48 ..
web_1    | python: can't open file 'app.py': [Errno 2] No such file or directory
```

I am not immediately aware of how to fix this.

2) The redis client's hostname for redis is "redis".

See https://github.com/docker/compose/blame/ac82597ac10c9a0dbd3bf25ebde792e9cc71efc4/docs/gettingstarted.md#L40

This looks very elegant; however, I could not find the network setup to support this (versus Python blowing up when it can't resolve the name "redis"). To enable Python to connect to a Redis, I changed "redis" to localhost.

All in all, I was able to run `docker run --net host redis & docker run --net host web`, after building the `web` container as specified in the Getting Started tutorial, but that did not use docker-compose.

Thank you for your time.

Lee

```
$ docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

$ docker-compose version
docker-compose version 1.7.0, build 0d7bf73
docker-py version: 1.8.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014

$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 65
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.11.0 (TCL 7.0); HEAD : 32ee7e9 - Wed Apr 13 20:06:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: WXHD:5SSZ:UQJQ:NJVM:HSMC:UOQW:E5TD:WIUP:HP23:PMG2:VBP4:YUUK
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 30
 System Time: 2016-04-22T00:58:32.190560374Z
 EventsListeners: 0
Username: lsb857
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

```

**Comment by shin-** [comment]
Hi Lee,

Thank you for your feedback!

Regarding your first point, can you share what your directory structure inside `composetest/` looks like? (using the `tree` command for example). 
As for number two, this should definitely work if you start your application via `docker-compose up`. I'd be interested in seeing what steps brought you to experience that issue, as it is possible there could be an issue with the tutorial or a bug in the code.

**Comment by lsb** [comment]
I started with a stock install of the docker machine a few weeks ago on my Mac, with the above versions. 

I have a Dockerfile,
```
FROM python:2.7
ADD . /code
WORKDIR /code
RUN pip install -r requirements.txt
CMD pwd && ls -al && python app.py
```
and an app.py
```
from flask import Flask
from redis import Redis

app = Flask(__name__)
redis = Redis(host='redis', port=6379)

@app.route('/')
def hello():
    redis.incr('hits')
    return 'Hello world, I have been seen %s times.' % redis.get('hits')

if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True)
```
and a docker-compose.yml
```
version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redis
```
and a requirements.txt
```
flask
redis
```
and all of that is, as far as I can tell, what was recommended in the doc (which is the most current version right now).

Thanks very much for the prompt reply!

Lee


Also, when I tar up my composetest directory, gzip it, and base64 it, I get

```
$ tar -c * | gzip -c9 | base64 -b 80
H4sIAJ26GlcCA+2W32+bMBDH8+y/4hSpJZESSoCAhoS0aVG1auoqRZv2iEi4FKvmx2xIlv++NiRVlYfu
KdlW3QcJc8dhn7G/HItq/YRywwUOzobjOIHvg2nDYN61mmPrOLNgBjM3dIK5N3c9DxxthO4AnMEFaFWT
Sp2KUKs343Y5onh7kq8mBYP/hNvlwz3U+yavysi1Q/ZpsQAbbtZVhuznw/Lr4m55sJY/vkHNa+ClfmNC
wFSCxF8tl1hg2Si7+d2wz/cLqHcZXF+DUDBNhbnqe4e0ru16zwbEv0S/Kucd40/69wPnVP8zzyf9X4KN
rArYiFQ9AS/qSjZwawzW+SVmXB39S2MwpjcMxH3QKEnKtMAkGbM+Mu6DRnmlmtjqfNYEzNNx4IUfxox9
NPtNVm2DI+vGGrMMN5CjENVoHDHQdA/ZvFzLkZXzRumY3t20sgTri4mFXSVFNoE7yNMtwgqxBGVOVwoa
XqCyLbg69PSIzUtHjG/gmDLEMQyTpEh5mSTDfuwut7bs0x86dncMJ5Dhqn2Mv8sWx+/u85V19X+6rvQi
K7T3hbi8/l0vPNG/7/sz0v8l2KJUXNd+sFyLKZRbvkZl5LDDVa+KVctFFoHdGUbLqvcDTGE413ONzGnY
+baVaAt8FWBH/c+DsTKsscxUokd7ud+JlB1k37t5kT5idLhDBfrMnP7C/Y36r/V+qn83IP1fpv531Z7E
RhAEQRAEQRAEQRAEQRAEQRAE8V54Bg0+WNgAKAAA
```

**Comment by ricardogsilva** [comment]
Any news on this? I'm facing the same issue on ubuntu 15.10. Followed the [getting started](https://docs.docker.com/compose/gettingstarted/) guide step by step too.

**Comment by vukvukovich** [comment]
+1

**Comment by greg2git** [comment]
definitely a bug on this page: https://docs.docker.com/compose/gettingstarted/#step-2-create-a-dockerfile
