### ISSUE TITLE
Add helper accessor to get useful values

### ISSUE THREAD

**Issue by metal3d** [docker/compose#3369]
It could be nice to get some useful value without to have the need to create environment variables as:
- the current user id, owner of the compose processus
- same for the group id
- used docker version
- used compose version
- running compose platform

I've made a PR #3367 to be able to get them with a special syntax. Vote or comment to let me know if you are interessed or if I'm wasting my time ;)

Thanks

**Comment by ijc** [comment]
Sorry that this never got responded to by a maintainer. I closed the PR a little while ago as part of a grooming session, there doesn't seem to be have much clamour for this particular feature either here or there so I think we should close this too. Thanks for your contribution nonetheless.
