### ISSUE TITLE
[Request] - Implement -t | --timeout option for `docker-compose down

### ISSUE THREAD

**Issue by nschoe** [docker/compose#3370]
There is the `-t | --timeout` option that can be passed to `docker-compose stop`, it would be nice to add this option to `docker-compose down`.

As `down` destroys a containers, it means we won't be using it again, so we should be allowed "not to care if it exits correctly. Alternatively it could be a `-k | --kill` flag so that instead of "stopping and removing container" it would "kill and remove container".

I understand that it should not be the default behavior because some linked containers can still prefer if the present container is stopped correctly, but there are such cases where it could speed things up.

For instance, I do a lot of debugging on an application that _unfortunately_ doesn't handle `SIGTERM` signal, and it is a pain to wait 10 seconds after running `down`, so I usually `kill` it first, then `down` it.

It's just a suggestion, what do you think?

**Comment by pataquets** [comment]
+1 to ```--timeout``` option, with support of matching Docker Engine -1 value to wait undefinitely until container stops.

**Comment by tarantegui** [comment]
+1 it would be interesting add the `down` option for specific services, like `docker-compose stop apache`

**Comment by dforrest88** [comment]
+1 for this. It would be good to be able to gracefully shut down a container via compose, rather than killing it automatically after 10 seconds.

**Comment by ilinum** [comment]
I would be interested in tackling this issue :)
Is this something that would be useful?
