### ISSUE TITLE
Borked python lib?

### ISSUE THREAD

**Issue by giftig** [docker/compose#3380]
I'm trying to use docker-compose on Mac OSX (Mountain Lion) but I get an error I don't seem to be able to find any information about when I run the binary (with any arguments, or none)

```
Error loading Python lib '/var/folders/3n/s02xvfqx03bf8hp21tp_tktr0000gp/T/_MEIoO5xBX/.Python': dlopen(/var/folders/3n/s02xvfqx03bf8hp21tp_tktr0000gp/T/_MEIoO5xBX/.Python, 10): Symbol not found: ___sincos_stret
  Referenced from: /var/folders/3n/s02xvfqx03bf8hp21tp_tktr0000gp/T/_MEIoO5xBX/.Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/3n/s02xvfqx03bf8hp21tp_tktr0000gp/T/_MEIoO5xBX/.Python
```

I'm guessing this is more a problem with my environment than with compose, but I'm not sure what's causing this lib issue as I couldn't find anything for ``___sincos_stret`` related to docker on google.

**Comment by dnephin** [comment]
OSX Mountain Lion is no longer supported by the binary install. We build on a newer version of OSX.

You can use one of the alternative install options: https://docs.docker.com/compose/install/#alternative-install-options

**Comment by giftig** [comment]
Thanks. Meta-option, of course...
![screen shot 2016-04-29 at 17 56 13](https://cloud.githubusercontent.com/assets/2862039/14923198/ba37457c-0e33-11e6-834a-665d8ea08c72.png)

**Comment by werleo** [comment]
@dnephin This information is missing on installation guide.

https://docs.docker.com/toolbox/toolbox_install_mac/#/step-1-check-your-version

I have the same problem with Python on osx 10.8 and fresh installation going step by step with guide above.
