### ISSUE TITLE
SSL error '<ip>' doesn't match 'localhost'

### ISSUE THREAD

**Issue by kazagistar** [docker/compose#3393]
```
$ docker-compose ps
ERROR: SSL error: hostname '192.168.99.101' doesn't match 'localhost'
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

```
$ env | grep DOCKER
DOCKER_HOST=tcp://192.168.99.101:2376
DOCKER_MACHINE_NAME=companyname
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/username/.docker/machine/machines/companyname
```

Versions:
- docker-compose version 1.7.0, build unknown
- Docker version 1.11.0, build 4dc5990
- docker-machine version 0.7.0, build a650a40
- OSX 10.10.5

I checked to make sure I didn't have any proxies in my network preferences (not that I ever set any).

**Comment by itdxer** [comment]
I got the same issue in the OSX after docker-compose update. I downgrade docker-compose from the 1.7.0 version to the 1.6.1 and now it's working fine.

**Comment by dnephin** [comment]
ping @shin- 

I couldn't find the issue for this. Is this fixed in 1.7.1 (or docker-py 1.8.1) ?

**Comment by kazagistar** [comment]
Rolling back to docker-compose 1.6.2 fixed the problem.
I'll get back to you when I have the chance to try out docker-compose 1.7.1.

**Comment by shin-** [comment]
Does the same certificate work with docker?

You might be running into https://github.com/docker/docker-py/issues/1037 - Do you have pyopenssl installed in the same environment (`PYTHONPATH`) as docker-compose?

**Comment by kazagistar** [comment]
I'm not entirely sure, I have it installed through brew. But installing the 1.7.0 version through pip inside a virtualenv works.

**Comment by shin-** [comment]
When you say "works", do you mean you're not experiencing the issue running in that virtual environment? (Sorry if this is a stupid/redundant question, I just want to make sure I understand correctly)

**Comment by kazagistar** [comment]
Yes, correct.

I am unsure how to check what packages are available to docker-compose=1.7.0 installed by brew.

**Comment by shin-** [comment]
Not sure about Mac OS, what's the output of `cd /usr/lib && find . -iname 'pyopenssl*'` ?

**Comment by itaifrenkel** [comment]
I just ran `pip install docker-py` and it worked (using docker-compose v1.8.0)
