### ISSUE TITLE
Use requirements.txt from setup.py for install_requires

### ISSUE THREAD

**Issue by kanzure** [docker/compose#3401]
Recently there was a discrepancy between the version of docker-py specified in setup.py `install_requires` and the version specified in `requirements.txt`. This was fixed by manually updating at least one of the files. Perhaps it would be better to directly read `requirements.txt` in setup.py and use those as the `install_requires` values? This would mean one less place to update when bumping a dependency in the future, a task that I am sure some developers will forget to do, or forget to check for during code review.....

**Comment by shin-** [comment]
They are intentionally different. `setup.py` requirements are flexible and try to "play nice" with other versions of the library present in the developer's environment, while the ones in `requirements.txt` are set to fixed versions as to provide the best experience for end-users.

The issue you mention was exceptional as it only affected the CentOS/Fedora platform where python libraries are repackaged differently. I don't think it is cause for concern going forward.

**Comment by kanzure** [comment]
FWIW, wasn't occurring on CentOS/Fedora, it was Ubuntu 14.04 in my case.
