### ISSUE TITLE
Docker compose ignores.env file when working directory is not where yml file resides

### ISSUE THREAD

**Issue by farhadkzm** [docker/compose#3405]
.env file would be ignored if the working directory is different than that docker-compose.yml resides.

 

|-directory1
|--docker-compose.yml
|--.env
|-directory2

if you run the following command inside directory2 it won't work:
`docker-compose path/to/directory1/docker-compose up -d`
It shows an error saying **The VARIABLE_NAME variable is not set. Defaulting to a blank string.**

However if you run the same command inside directory1 it works fine.

**Comment by shin-** [comment]
Thanks for the call-out. This is a docs problem and is fixed by #3388 :)

**Comment by farhadkzm** [comment]
I think it makes more sense to have an option (e.g. **--env**) to get the path to the **.env** file rather than just looking for it in the current directory.
