### ISSUE TITLE
Docker compose on Docker cloud

### ISSUE THREAD

**Issue by anaibol** [docker/compose#3407]
Hi! I am currently working with Docker cloud to build my images and deploy my services.
The images  are beeing built based on the Dockerfiles. I would like to know if it's possible to user docker-compose.yml files on Docker cloud instead.
Thanks!

**Comment by shin-** [comment]
I believe [stack files](https://docs.docker.com/docker-cloud/feature-reference/stack-yaml-reference/) are what you're looking for. Feel free to reach out to the Docker Cloud support team or [the forums](https://forums.docker.com/c/docker-cloud) for questions related to Docker Cloud.

**Comment by anaibol** [comment]
Great! Many thanks
