### ISSUE TITLE
deploy containers on swarm cluster using compose file without using docker machine

### ISSUE THREAD

**Issue by shujamughal** [docker/compose#3409]
Hi All,

I have build a swarm cluster without using docker machine. if we use docker machine then we can deploy using following

eval "$(docker-machine env --swarm )"
$ docker-compose up

but without docker-machine how to access swarm master to deploy containers using compose file?

Regards
Shuja

**Comment by shin-** [comment]
You have 2 solutions, either 

1. Using the Docker [environment variables](https://docs.docker.com/engine/reference/commandline/cli/#environment-variables) (`DOCKER_HOST`, `DOCKER_CERT_PATH`, `DOCKER_TLS_VERIFY`)
2. Using the [command-line options](https://docs.docker.com/compose/reference/overview/)

```
  -H, --host HOST             Daemon socket to connect to

  --tls                       Use TLS; implied by --tlsverify
  --tlscacert CA_PATH         Trust certs signed only by this CA
  --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
  --tlskey TLS_KEY_PATH       Path to TLS key file
  --tlsverify                 Use TLS and verify the remote
  --skip-hostname-check       Don't check the daemon's hostname against the name specified
                              in the client certificate (for example if your docker host
                              is an IP address)
```

**Comment by shujamughal** [comment]
Hi Shin,
the links you provided explain the docker compose only but not with swarm integration. Can you please provide the example command which I can use for swarm cluster?

**Comment by shin-** [comment]
Swarm integration works the same way - just make sure the docker_host value
points to your swarm manager.
