### ISSUE TITLE
fig-lock

### ISSUE THREAD

**Issue by sheax0r** [docker/compose#341]
I have created a ruby project that parses fig.yml files that use "latest" tags in order to produce fig.yml files that use specific version tags. The idea here is to do something similar to Gemfile.lock for fig. I have found this very useful in a development environment where we use several docker images that need to interact with each other, but we want fig files that reference specific versions when we deploy to production.

Fig could support this functionality natively. Here is a link to the project: https://github.com/sheax0r/fig-lock

**Comment by dnephin** [comment]
Probably related to #1818

**Comment by dnephin** [comment]
I think this will be covered by #1818
