### ISSUE TITLE
.env file ignored 

### ISSUE THREAD

**Issue by ujovlado** [docker/compose#3413]
Hi, I'm running `docker-compose` and `.env` file is ignored.

Location of the files:
```
$ ls -la | grep -e ".env" -e "docker-compose.yml"
-rw-rw-r--  1 vlado vlado   2878 May  4 17:17 docker-compose.yml
-rw-rw-r--  1 vlado vlado    171 May  4 16:42 .env
```

Environment:
- engine: `1.11.1, build 5604cbe` (`1.11.1-0~xenial`)
- compose: `1.7.0, build 0d7bf73`

Docker compose located in `~/bin/docker-compose`.

Thanks!

**Comment by ujovlado** [comment]
This build should output:
```
testing
testing
```
https://travis-ci.org/ujovlado/docker-compose-test/builds/127832493

**Comment by shin-** [comment]
The `.env` file has to be present in the working directory. Could that be the issue you're seeing?

**Comment by rafaelsierra** [comment]
https://gist.github.com/rafaelsierra/1b27afbea0a992a7518807c6e6079167

The `.env` file is on the same folder as everything else

**Comment by rafaelsierra** [comment]
> Those environment variables will be used for variable substitution in your Compose file, but can also be used to define the following CLI variables:
From https://docs.docker.com/compose/env-file/

If that means that the `.env` file is used **only** for variable substitution then it is safe to ignore my comments

**Comment by aanand** [comment]
If you want the environment variables to turn up inside the container, you have to explicitly pass them through in `docker-compose.yml`:

```yaml
version: "2"

services:
  nothing:
    image: debian:jessie
    command: /bin/false
    environment:
      - FOO
```

**Comment by ujovlado** [comment]
Comment by @aanand solved my problem. Thanks :+1:

**Comment by rmetzler** [comment]
I just want to comment on this, because I keep forgetting it.

Not only do you need to set the env names in `docker-compose.yml` like this:

```
services:
  my_service:
    environment:
      - FOO
```

You also need to write the value in the `.env` file *without* quotes:

```
# this works
FOO=bar

# this doesn't work
FOO="bar"
```

**Comment by philip-nicholls** [comment]
I know this question is old, but I just wanted to say that I have always found it easier to mount a local `.env` file (which is .gitignored and .dockerignored) as a volume and make sure your application looks for it and loads it over the top of the current environment when it starts up.  In node there is a npm package called dotenv to help with this.  

Then for development purposes use this in docker-compose:

```
volumes:
      - .env:/app/.env
```

Now there is no need to tell docker-compose about every single environment variable that you want to load.

**Comment by Hoofinite** [comment]
> I just want to comment on this, because I keep forgetting it.
> 
> Not only do you need to set the env names in `docker-compose.yml` like this:
> 
> ```yaml
> services:
>   my_service:
>     environment:
>       - FOO
> ```
> 
> You also need to write the value in the `.env` file _without_ quotes:
> 
> ```shell
> # this works
> FOO=bar
> 
> # this doesn't work
> FOO="bar"
> ```

How to manage this in situation like below:
i have following secret to store in `.env` and it looks like:
SECRET_KEY = dfjdfnbk2325#fsdun5#dsd

What happens is this `` .env`` file interprets #  sign that key contains as comment, so whole key is not being passed to variable. How to manage it? I've found help in wrapping whole string in quotes, however i'm not 100% sure if it's right option?

**Comment by ibc-brad** [comment]
> What happens is this ` .env` file interprets # sign that key contains as comment, so whole key is not being passed to variable. How to manage it?

You could base64 encode the value before storing it in the file. Then you would just need to base64 decode the value before using it in your application.
