### ISSUE TITLE
Only prefix container name once during recreate

### ISSUE THREAD

**Issue by dnephin** [docker/compose#3415]
When we recreate a container we start by renaming the old container by adding the container short id as a prefix. If the start or create fails, the container is left with that prefixed name. On each subsequent recreate we prefix it again.  If the container keeps failing we end up with some very ugly container names.

We actually only need to prefix it once. We could check the container name before adding the prefix, and if it already has its own short id as a prefix we can skip the rename.

This is a very low priority issue.

**Comment by dvusboy** [comment]
Do you mean if the _start_ fails?

**Comment by dnephin** [comment]
Updated to say "start or create", it could be either.

**Comment by bclermont** [comment]
this bug is annoying.

#5316 look good, can someone merge it?

**Comment by shin-** [comment]
Fixed in 9ba9016cbc66bf2473fa62b1e831ae2c70408509
