### ISSUE TITLE
"Unable to find a node that satisfies the following conditions" when recreating a service

### ISSUE THREAD

**Issue by niieani** [docker/compose#3420]
I have a service that has affinity set so that it can only be created on a specific node in the swarm.
That same service binds to a port on that node, meaning the service shouldn't scale to more than 1 container (by design).

An error appears however when `docker-compose up -d` tries to recreate the container, when the underlying image has changed. It checks for whether the conditions are met BEFORE stopping the previous container. Because the port is still in use by the old version of the same container, it spits out an error:

```shell
Recreating driver-singleton

ERROR: for driver-singleton  Unable to find a node that satisfies the following conditions
[port 443 (Bridge mode) port 80 (Bridge mode)]
[container!=*driver* (soft=false)]
```

docker-compose should ignore the container(s) it's about to recreate when deciding on which nodes to put the containers. Or even simpler, when it's recreating the container(s) it shouldn't even "think" about the nodes, just do it in place.

The workaround is to first manually stop and remove the service and then run `up -d` again.

**Comment by nejtr0n** [comment]
Same issue, but there is no runnig node.

`version: '2'
services:
 # Точка входа для nginx. Балансировка по контейнерам с fronted
 haproxy2:
  container_name: haproxy1
  image: nejtr0n/haproxy
  volumes:
   - /root/compose/cloud/haproxy/haproxy.ctmpl:/templates/haproxy.ctmpl
  ports:
   - "80:80"
   - "443:443"
  networks:
   ferma:
    aliases: 
     - gw_front
   gw: {}
  environment:
    - "constraint:cluster_id==1"
    - "CONSUL_URL=sd:8500"


networks:
  ferma:
    external:
      true
  gw:
    driver: bridge`

I have error:
`Creating haproxy1

ERROR: for haproxy2  Unable to find a node that satisfies the following conditions 
[port 443 (Bridge mode) port 80 (Bridge mode)]
Attaching to`

**Comment by shin-** [comment]
See @aanand 's answer [here](https://github.com/docker/compose/issues/3469#issuecomment-220328570), which I believe applies.
I'm going to close this ticket, but you can track the status of the issue by following #3469
