### ISSUE TITLE
Suggesting escaping environment variables with double-dollar sign in error message

### ISSUE THREAD

**Issue by nhooey** [docker/compose#3427]
Pull request #2204 documented the double-dollar sign (`$$VARIABLE`) escaping in the _documentation_, how about putting the same suggestion in the _error message_:

Change this:

```
WARNING: The VARIABLE variable is not set. Defaulting to a blank string.
```

To this:

```
WARNING: The VARIALBE variable is not set. Defaulting to a blank string.
         Did you forget to escape VARIABLE with two dollar signs like this: `$$VARIABLE`
         in your docker-compose.yml file?
```

Would make the error message much more useful and less misleading.

**Comment by shin-** [comment]
To me that seems very specific. There's many reasons why a variable might be unset. IMO that would be making too many assumptions.

**Comment by nhooey** [comment]
How about providing a list of possible reasons?

How many reasons can you think of where the user would be expecting the variables to be set, but they're actually not?

**Comment by max-vogler** [comment]
This is a great idea and would've saved me a lot of experiments with backslashes and a Google search.

**Comment by alancnet** [comment]
So uh... this is built-in now, right? I landed on this issue trying to figure out how to do it, and it works.
