### ISSUE TITLE
Docker API v1.23 has broke IPv6 in docker-compose defined networks

### ISSUE THREAD

**Issue by maloddon** [docker/compose#3430]
As @gaertner-mike noticed in #2804, and due to this change in Docker API v1.23 :

> POST /networks/create now supports enabling ipv6 on the network by setting the EnableIPv6 field (doing this with a label will no longer work).

IPv6 custom networks doesn't work anymore with docker-compose, which uses a label so far to enable IPv6 (`com.docker.network.enable_ipv6: "true"`)

**Comment by duxet** [comment]
any progress?

**Comment by joernheissler** [comment]
Looks related to my issue. My global IPv6 addresses weren't added to bridge interface nor container's eth0.
I patched docker-py as a workaround:
docker/api/network.py function create_network. Added 'EnableIPv6': True.

Obviously, a proper fix needs a change in docker-py first. There is an open issue: https://github.com/docker/docker-py/issues/1105

**Comment by peterthomassen** [comment]
How come this is tagged as an enhancement? IPv6 assignment to custom network does not work as documented, so it's a bug, isn't it?
