### ISSUE TITLE
Network alias was not filled when start container with run

### ISSUE THREAD

**Issue by artemkaint** [docker/compose#3437]
Version 1.7.1

**Comment by ashb** [comment]
Duplicate of #2908

**Comment by artemkaint** [comment]
I suppose this bug isn't duplicate issue 2908, because that is the old bug, but this one arose after upgrade to the version 1.7.1

**Comment by ashb** [comment]
Ah right sorry - I was guessing from the description it was similar.

**Comment by Ryanb58** [comment]
I am also having issues with this. Watching this Issue.

**Comment by NdubisiOnuora** [comment]
@shin-: any update on this issue?

**Comment by NdubisiOnuora** [comment]
Have people tried the using the `--use-aliases` parameter? It uses the service's network alias. See `https://docs.docker.com/compose/reference/run/` for more information.

**Comment by shin-** [comment]
Fixed by #5725
