### ISSUE TITLE
Pull, when compose file contains local images

### ISSUE THREAD

**Issue by terracott** [docker/compose#3445]
I'm using compose file, which contains several services.
Some images should be pulled from docker hub, some images should be built local.

When I run `docker-compose pull`, docker-compose trying to pull local images. Now my local images have unique names, therefore no conflict. 

How I can distinguish local from non-local images?

**Comment by shin-** [comment]
`--ignore-pull-failures` ? Or just call `pull` with the list of services that need to be gotten from the hub (`docker pull foo bar baz`)

**Comment by terracott** [comment]
Ok. Thanks
