### ISSUE TITLE
Add `--build` and `--no-build` options to `run` analogous to `up` command.

### ISSUE THREAD

**Issue by nhooey** [docker/compose#3448]
`docker-compose up --help` outputs:

```
    --no-build                 Don't build an image, even if it's missing.
    --build                    Build images before starting containers.
```

But these options are missing from `docker-compose run --help`.

As of `docker-compose version 1.7.1, build unknown` from Pip.

**Comment by shin-** [comment]
Can't you just run `docker-compose build` first?

**Comment by nhooey** [comment]
No, because it will build every single thing in the `docker-compose.yml` file, and even when cached, this process is very slow. `docker-compose run --build` should detect what needs to be built and only build those.

**Comment by shin-** [comment]
`build` takes a service argument, i.e. `docker-compose build foo` will only build the `foo` service.

**Comment by nhooey** [comment]
I know how it works.

But I want `docker-compose` to do the most intelligent thing, and rebuild whatever services and dependencies are involved.

If `docker-compose up --build` exists, then `docker-compose run --build` should also exist.

**Comment by christianbundy** [comment]
> If docker-compose up --build exists, then docker-compose run --build should also exist.

Exactly, the "run `docker-compose build` first" argument is equally valid with respect to `docker-compose up --build` too. It's confusing that I can run `docker-compose up --build django` to start my server, but I have to run `docker-compose build && docker-compose run django test` to run my tests. Is there any reason to reject this functionality that wouldn't apply equally to `docker-compose up --build`?

I'm open to either requiring `docker-compose build` everywhere or allowing `--build` everywhere, but we should have consistency throughout the command-line API. Thanks for you work in maintaining this project.

**Comment by daaain** [comment]
Why was this issue closed without a comment?

I would find `--no-build` especially helpful to prevent build triggered by a `run` as that won't have the necessary build `ARG` values passed and fail.

**Comment by jaysonsantos** [comment]
Hey there, I also came looking for something like this for builds with `ARG`.
In my case, the first build injects some sutff into the image which is actually needed but on `run` there would be no need to inject/build it as the image is with the right data otherwise I would have to export the used variables on every usage of `docker-compose run`

**Comment by nhooey** [comment]
@ulyssessouza Could you re-open this?

**Comment by ZimbiX** [comment]
Please reopen

**Comment by muellermichel** [comment]
> I would find `--no-build` especially helpful to prevent build triggered by a `run` as that won't have the necessary build `ARG` values passed and fail.

This is *exactly* what bugs me at the moment too.

**Comment by superlevure** [comment]
Can we please re-open this ?

**Comment by fzieris** [comment]
> > I would find `--no-build` especially helpful to prevent build triggered by a `run` as that won't have the necessary build `ARG` values passed and fail.
> 
> This is _exactly_ what bugs me at the moment too.

Same here. My workaround: Check for an existing docker image and, if necessary, build it with the right arguments before calling `run`:

```bash
# Assuming project 'my_project' and service 'app'

if ! docker inspect --type=image my_project_app:latest > /dev/null 2>&1
then
    echo "Couldn't find image for 'app'. Going to build it first."
    docker-compose build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -u) app

    # Or put any other logic you would execute in the --no-build case here.
fi

# Now we can call `run` with a properly built image
docker-compose run --no-deps --rm app run-tests-or-whatever.sh
```

**Comment by adaamz** [comment]
Also it is usefull when you have image in registry but don't have locally - it rather builds than pull image, which is not what I want.

**Comment by ginjo** [comment]
> Also it is usefull when you have image in registry but don't have locally - it rather builds than pull image, which is not what I want.

This is exactly what's tripping me up too. Really need a ```--no-build``` for ```docker-compose run```, or even more generally for ```docker-compose```.

**Comment by victorm1710** [comment]
As a workaround you can use _docker compose pull_ before _docker compose run_, as soon as necessary images are present locally, compose doesn't build images.
