### ISSUE TITLE
docker-compose run ignores the hostname directive

### ISSUE THREAD

**Issue by galan** [docker/compose#3450]
When using a `hostname` directive for a service, it is only recognized using `docker-compose up`. If a single service is started using `docker-compose run` it is not.

This leads to services that can't discover other services within the same network.

This issue might be relatd to #2061

**Comment by shin-** [comment]
Similar to #3437 . Thanks for reporting it.

**Comment by NdubisiOnuora** [comment]
@shin-: any updates on this issue?
