### ISSUE TITLE
docker-compose "rolling deploy" (restart containers one after another instead of all at once)

### ISSUE THREAD

**Issue by duraiz** [docker/compose#3454]
I am running a redis cluster on 200 containers which are placed on different nodes using docker-compose and docker and docker-swarm.

Now if i want to restart service on some containers instead of restarting all 200 containers at once how can i do it ? or how can i stop the service on some containers instead on stoping whole service?

**Comment by aronahl** [comment]
It may not be ideal, but you can directly use a docker command to stop select services and then use docker-compose to bring them back up.  For a project named **updown** containing a service named **redis** that I've scaled to 20, I can stop the first 10 (I'm using bash, and I assume there is something similar in windows syntax) using:

```bash
docker stop updown_redis_{1..10}
```

Then, I can bring back up any stopped services with:

```bash
docker-compose up -d
```

**Comment by duraiz** [comment]
ok thanks everything works fine
