### ISSUE TITLE
COMPOSE_FILE OS agnostic file separator support

### ISSUE THREAD

**Issue by andrerom** [docker/compose#3462]
Given `COMPOSE_FILE` can be defined in `.evn` file which people would distrobute with applications, it should be supported to use a separator that works across all platforms.

Right now both 1.7.0 release notes and online doc says it supports `:` on nix, and `;` on Windows, it implies neither is supported on the opposite platforms, meaning you won't be able to distrobute your application with `.env` and doc instructions that works the same across all.

Suggestion: ~~_Add support for `:` on Windows._~~ Find something that works on both, at least in `.env`

**Comment by shin-** [comment]
There's an obvious issue with using `:` as a **path** separator on Windows though...

**Comment by andrerom** [comment]
True, long time since I used windows, point is just to pick something that works everywhere.

**Comment by rasodu** [comment]
Team members working on the same project on different OS should be able to run the code without modifying it.

May be we don't need path separator. We can assume that if see '.yml' in the string then that is the end of filename.

COMPOSE_FILE=docker-compose.ymldocker-compose.prod.yml

**Comment by hholst80** [comment]
@andrerom maybe you can grab my PR (see https://github.com/docker/compose/issues/4099). I don't understand why it was not accepted by the build system it works fine on my system and I have no time to investigate it further. 

The windows users would specify an environment variable that overrides the `;` separator with `:`

**Comment by andrerom** [comment]
Fixed in #4588
