### ISSUE TITLE
Releases, code should be digitally signed

### ISSUE THREAD

**Issue by sanmai-NL** [docker/compose#3480]
Apparently the releases, e.g. the latest [1.7.1](/docker/compose/releases/tag/1.7.1), are not being signed, neither the Git tags nor the artifacts (executables). This reduces the confidence users can have in the integrity of your release process.

**Comment by TotallyPro** [comment]
This issue clearly deserves a higher significance, not feature but requirement!
Anyone security conscious will, and should, have serious questions about credibility when missing...

**Comment by damianb** [comment]
Having no way to verify a binary as being official via a cryptographic signature (e.g. GPG) and then having instructions for users to install by using sudo, curl altogether blindly is a blatant disregard for best practices for software distribution.

At minimum, please start signing *release binaries*.  No way can I or many others pull in docker-compose from a random URI (HTTPS or not) without some way of verifying who built the binary in the first place.

**Comment by sanmai-NL** [comment]
Activity.

**Comment by damianb** [comment]
Issue still persists - please disable stale bot suspense of issue until issue is remediated.

**Comment by QuantumGhost** [comment]
No it's not stale.

**Comment by sanmai-NL** [comment]
The only lack of activity is on the part of Docker, Inc.

**Comment by janoking** [comment]
hello ?

**Comment by sanmai-NL** [comment]
Activity.

**Comment by sanmai-NL** [comment]
Activity.

**Comment by sanmai-NL** [comment]
Not stale.

**Comment by stekern** [comment]
It's a bit contradicting that Docker strongly recommends integrity and authenticity verification of binaries as a best practice, but make it hard to do so for some of the key binaries they ship...

@ndeloof Do you have any updates on the internally tracked issue you mentioned?
