### ISSUE TITLE
After restart, existing volumes report "invalid characters" error

### ISSUE THREAD

**Issue by mc0e** [docker/compose#3496]
Any pointers on what's going on here would be most welcome.

After upgrading a few system components (deliberately not including docker, because of #2106), I'm getting the following error:

    xxx@xxx:xxx$ docker-compose up
    Creating xxx_dspamspool_1
    ERROR: volumes/dspamspool includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

There's no change to the name of the volume from what has worked previously.

    dspamspool:
        image: busybox
        volumes:
            - volumes/dspamspool:/var/spool/dspam

The list of updated packages is as follows:

    Will install 23 packages, and remove 0 packages.
    56.3 kB of disk space will be used
    ===============================================================================
    [HOLD, DEPENDENCIES] lxc-docker:amd64
    [UPGRADE] apache2-utils:amd64 2.4.7-1ubuntu4.8 -> 2.4.7-1ubuntu4.9
    [UPGRADE] apport:amd64 2.14.1-0ubuntu3.19 -> 2.14.1-0ubuntu3.20
    [UPGRADE] biosdevname:amd64 0.4.1-0ubuntu6.2 -> 0.4.1-0ubuntu6.3
    [UPGRADE] cloud-guest-utils:amd64 0.27-0ubuntu9.1 -> 0.27-0ubuntu9.2
    [UPGRADE] klibc-utils:amd64 2.0.3-0ubuntu1 -> 2.0.3-0ubuntu1.14.04.1
    [UPGRADE] libdrm-intel1:amd64 2.4.60-2~ubuntu14.04.1 -> 2.4.64-1~ubuntu14.04.1
    [UPGRADE] libdrm-nouveau2:amd64 2.4.60-2~ubuntu14.04.1 -> 2.4.64-1~ubuntu14.04.1
    [UPGRADE] libdrm-radeon1:amd64 2.4.60-2~ubuntu14.04.1 -> 2.4.64-1~ubuntu14.04.1
    [UPGRADE] libdrm2:amd64 2.4.60-2~ubuntu14.04.1 -> 2.4.64-1~ubuntu14.04.1
    [UPGRADE] libklibc:amd64 2.0.3-0ubuntu1 -> 2.0.3-0ubuntu1.14.04.1
    [UPGRADE] libnl-3-200:amd64 3.2.21-1 -> 3.2.21-1ubuntu1.1
    [UPGRADE] libnl-genl-3-200:amd64 3.2.21-1 -> 3.2.21-1ubuntu1.1
    [UPGRADE] libnuma1:amd64 2.0.9~rc5-1ubuntu3.14.04.1 -> 2.0.9~rc5-1ubuntu3.14.04.2
    [UPGRADE] libpolkit-agent-1-0:amd64 0.105-4ubuntu2.14.04.1 -> 0.105-4ubuntu3.14.04.1
    [UPGRADE] libpolkit-backend-1-0:amd64 0.105-4ubuntu2.14.04.1 -> 0.105-4ubuntu3.14.04.1
    [UPGRADE] libpolkit-gobject-1-0:amd64 0.105-4ubuntu2.14.04.1 -> 0.105-4ubuntu3.14.04.1
    [UPGRADE] libpq5:amd64 9.3.11-0ubuntu0.14.04 -> 9.3.12-0ubuntu0.14.04
    [UPGRADE] libsystemd-login0:amd64 204-5ubuntu20.15 -> 204-5ubuntu20.19
    [UPGRADE] os-prober:amd64 1.63ubuntu1 -> 1.63ubuntu1.1
    [UPGRADE] postgresql-9.3:amd64 9.3.11-0ubuntu0.14.04 -> 9.3.12-0ubuntu0.14.04
    [UPGRADE] postgresql-client-9.3:amd64 9.3.11-0ubuntu0.14.04 -> 9.3.12-0ubuntu0.14.04
    [UPGRADE] postgresql-contrib-9.3:amd64 9.3.11-0ubuntu0.14.04 -> 9.3.12-0ubuntu0.14.04
    [UPGRADE] usbutils:amd64 1:007-2ubuntu1 -> 1:007-2ubuntu1.1
    ===============================================================================

docker-compose version 1.6.0, build d99cad6
Docker version 1.9.0, build 76d6bc9

**Comment by mc0e** [comment]
Actually, the fact that docker-compose was trying to 'create' the dspamspool volume likely means that #2106 has been trigered again, but the failure to do so is new.

**Comment by mc0e** [comment]
prepending the volume path with `./` seems to have worked.

**Comment by shin-** [comment]
Relative paths need to be explicited (append `./` at the beginning), otherwise Docker / Compose will interpret them as named volumes (see https://docs.docker.com/engine/reference/commandline/volume_create/ )

**Comment by shin-** [comment]
This is called out in the [Compose docs](https://docs.docker.com/compose/compose-file/#volumes-volume-driver) as well.
I will close this issue as a result, but feel free to reach out if you're having further issues.
