### ISSUE TITLE
[Request] Refactor docker-compose to be a "CLI tool over python-docker-compose library"

### ISSUE THREAD

**Issue by denismakogon** [docker/compose#3499]
It seems like nothing much has been done within past year in the direction of making docker-compose a framework with CLI tool instead of just a CLI tool. Related issues were summarized in https://github.com/docker/compose/issues/230 but it is irrelevant to build RESTful framework within D-compose since there are too many frameworks to do that and there would be too large discussion with no consensus.

Here's plan to make docker-compose a library:
1. Define contract between compose core components and CLI.
2. Implement abstraction layer between compose core and CLI.
3. Refactor compose core code into its own module (compose/core).
4. Refactor compose CLI code into its own module (compose/cli).
5. Provide compose core API tests.
6. Provide compose core API reference documentation.

**Comment by denismakogon** [comment]
As for hidden complexity, first commit in the row will contain defining single entry point for dockerclient that is meant to be a dependency for compose/core (that is a dependency for compose/cli).

1. Define single entry point module for docker client.

**Comment by denismakogon** [comment]
As step 2 it is necessary to move shared files (between CLI and CORE) to compose/common package in order to see how modules are tightly integrated between each other.

**Comment by joshwget** [comment]
Have you seen [libcompose](https://github.com/docker/libcompose)? It's definitely not as complete as Docker Compose, but it may suite your needs.

**Comment by denismakogon** [comment]
@joshwget no, it doesn't work for me, since i (as part of OpenStack Higgins team) want to consume Python API inside our service that is completely written on Python.

**Comment by denismakogon** [comment]
@dnephin would you be kind to review this idea. Are you okay with plan for python-libcompose (or whatever it would be named) library development (current compose refactoring) that i've proposed?

**Comment by dnephin** [comment]
My initial impression is:
* this is a major undertaking and one that we don't really have the resources to support right now
* a lot of this factoring already exists in the current codebase. The cli is already in `compose/cli`, and everything outside of that package can be considered "core"
* we already have a bunch of tests at the `Project` and `Service` level

We might be able to accept some smaller PRs that improve the interface, but I don't think we'll be able to merge any major refactoring.

**Comment by denismakogon** [comment]
@dnephin actually, it is not true, some "core" modules are depending on code from CLI and vise versa.
So, the general idea is to extract library similar to libcompose and store it as separate lib that would become a dependency for docker-compose CLI.

If you don't have enough resources than i can commit myself as maintainer of future lib code.

**Comment by denismakogon** [comment]
@aanand Hello, would you mind to bring your thoughts to this topic please.

**Comment by denismakogon** [comment]
@shin-  Hello, would you mind to bring your thoughts to this topic please.

**Comment by dnephin** [comment]
>  some "core" modules are depending on code from CLI and vise versa

I see only one place this is the case: 

```
compose/parallel.py:from compose.cli.signals import ShutdownException
```

That's my fault, but seems like an easy enough fix to move this exception out of the cli package.

**Comment by iBobik** [comment]
[libcompose already has 6 live projects](https://github.com/docker/libcompose#libcompose) depending on it. How about to find a way how to bind this GO library in Python than maintaining the same library in different language?
