### ISSUE TITLE
Docker-compose scale container placements

### ISSUE THREAD

**Issue by igrcic** [docker/compose#3500]
Hi everyone,

i am trying to start multiple containers on a 3 node docker swarm  (bug1, bug2, bug3) 

Issuing "docker run" 3 times always places containers on three different nodes. 
`docker run -d -p 3333:3333 --net swarm_network  --restart=always  image_name` 

4th time I receive an error, which is logical while we cannot  use the same ports twice:

```
docker: Error response from daemon: Unable to find a node that satisfies the following conditions 
[port 3333 (Bridge mode)].
See 'docker run --help'.
```

But docker-compose scale always tries to place 2 containers on the same node (always using just two nodes, and are always bug2 and bug3 nodes - bug1 is  primary)

```
Creating and starting app_app_1 ... done
Creating and starting app_app_2 ... done
Creating and starting app_app_3 ... error

ERROR: for app_app_3  Error response from daemon: container 8ca37...976d: endpoint join on GW Network failed: driver failed programming external connectivity on endpoint gateway_8ca37ae08d32 (01b19...52974): Bind for 0.0.0.0:3333 failed: port is already allocated
```

I still havent checked swarm filters and playing with affinites, but I have a feeling that docker run always does the right thing (spreading the containers over all nodes), while docker-compose scale always chooses the slave nodes. 

Is there a way one can influence container affinities relative to nodes?

Thank you,
Ivan

**Comment by jamshid** [comment]
IDK, seems compose should handle this automatically with swarm. 
Maybe you can specify a "port filter" via environment. It's tricky syntax, affinity:port==3333 ?
https://docs.docker.com/swarm/scheduler/filter/#use-a-port-filter
Or, maybe the port filter just needs to be activated (?) on the network created by compose.

**Comment by igrcic** [comment]
Hi @jamshid 

As I've understood from the docs there is no such affinity:port flag. 

In swarm, port filter is achieved by setting  -p 80:80 in bridge mode or --expose 80 for host mode.

From the docs:

> Docker Swarm selects a node where a particular port is available and unoccupied by another container or process. Required ports may be specified by mapping a host port, or using the host networking and exposing a port using the container configuration.

Indeed, such behavior is desired and there is no problem when using swarm. Docker-compose doesnt play well with swarm somewhere.

How does docker-compose picks up which is current swarm master? I do it by 
`export DOCKER_HOST=master:4000`
or direct with 
`docker -H :4000 ...`

**Comment by OferE** [comment]
+1.
I encounter the same problem.
I have the port filter enabled in swarm (verified it using docker info command) - yet the scheduler tries to schedule 2 services with the same port on the same host.
This is a real bug IMHO.

**Comment by nhatfield** [comment]
+1 
Same problem here... is there anything in the works for this? Quite frustrating.... I have to literally restart all of my docker hosts, and remove all images & containers, then re-docker-compose everything all over again... and even then, sometimes it will fail again. 

I have 3 hosts and am only scaling flume=2

**Comment by dongluochen** [comment]
This issue is tracked by https://github.com/docker/swarm/issues/2499.
