### ISSUE TITLE
docker-compose -f <file> unexpectedly changes the workdir

### ISSUE THREAD

**Issue by nottrobin** [docker/compose#3506]
When specifying a config file outside the current directory, `docker-compose` treats the directory containing the config file as the workdir, rather than the directory you're in:

``` bash
$ tree
├── Dockerfile  # Contents: "CMD echo 'local'"
└── nested
    └── docker-compose.yml  # Contents: "echoer: {build: .}"
    └── Dockerfile  # Contents: "CMD echo 'nested'"
$ docker-compose -f nested/docker-compose.yml run echoer
nested  # I expected "local"
```

 I think this is unintuitive and probably unintended behaviour. The location from which you're running `docker-compose` is almost certainly the intended work directory, rather than the directory containing the config file (it certainly is in my case).

**Comment by ijc** [comment]
Issue grooming: sorry noone ever replied. I think this is the intended behaviour, the references in `docker-compose.yml` are relative to that file.
