### ISSUE TITLE
Compose UP in Docker Swarm Node Added Problem

### ISSUE THREAD

**Issue by yank1** [docker/compose#3509]
When I use a one node. 
I can use `compose up` to up a image like `jenkins`.
And then I `compose down`

But when I add a node to swarm, And `compose up`  again.
There would be a error `can not find image`.

**Comment by denismakogon** [comment]
@yank1 compose uses regular docker API, is it possible that you are asking for something that may not appear at swarm? Can you start the same image without compose?
