### ISSUE TITLE
[Request] Support TOSCA for compose files

### ISSUE THREAD

**Issue by denismakogon** [docker/compose#3511]
The idea here is to enable TOSCA features and functions within compose files. Example of TOSCA orchestration can be seen [here](https://github.com/aria-tosca/aria-examples/blob/master/nodejs-application-local-blueprint.yaml) or [here](https://github.com/openstack/tacker/blob/master/samples/tosca-templates/vnfd/tosca-vnfd-flavor.yaml).
The idea is to give an ability to use container attributes in setup of another container.
For example if i setting up DB i want to get its public IP and pass it directly to setup process to another container.

For now compose YAML looks approximately close to what TOSCA simple profile offers, but remain to be a simple YAML standard.

TOSCA parser - https://pypi.python.org/pypi/tosca-parser

**Comment by shin-** [comment]
Thank you for the suggestion, but I don't think we'd have much to gain doing this.
