### ISSUE TITLE
Start multiple containers  for  service with docker-compose up

### ISSUE THREAD

**Issue by xwang2713** [docker/compose#3514]
Is there a way to set number of containers per service to start in configure file

**Comment by shin-** [comment]
Are you looking for [`depends_on`](https://docs.docker.com/compose/compose-file/#depends-on)?

**Comment by xwang2713** [comment]
No. I use 'links". But I rely on /etc/hosts to find each linked host  and configure the cluster. Now it is not available I wonder if there are other way to find all linked hosts on this master container.
