### ISSUE TITLE
Naming issue: 'internal' vs 'external'

### ISSUE THREAD

**Issue by aanand** [docker/compose#3515]
#3488 introduces an `internal` keyword for network definitions, mirroring `docker network create --internal`, for disallowing external access to a network.

Unfortunately, we have an `external` keyword on network and volume definitions, which relates to something else entirely - specifying that the network/volume is not managed by Compose, but created externally.

It's going to be really confusing to have two antonyms which relate to completely different things (even if, fortunately, they can't be used at the same time). So we should probably deprecate `external` and introduce a new alias. Any ideas?

**Comment by johnharris85** [comment]
`extrinsic` - Little bit out there but appropriate definition: 'coming or operating from outside'.
`independent` ?

**Comment by peterthomassen** [comment]
`predefined`, `unmanaged`, `custom`, `decomposed`

**Comment by gg7** [comment]
:+1: for `predefined`.

**Comment by peterthomassen** [comment]
Just for reference - nothing came out of this, right?
