### ISSUE TITLE
[Request] Support Python 3.5

### ISSUE THREAD

**Issue by denismakogon** [docker/compose#3518]
Since Debian's and Ubuntu's latest LTS releases are having Python 3.5 as default it is necessary to support Python 3.5.

**Comment by jundl77** [comment]
Would be cool if this were implemented indeed!

**Comment by nazmulhasan85** [comment]
Yeah! really need to fix it for python 3.5

**Comment by shin-** [comment]
should work on Python 3.4-3.6 now.
