### ISSUE TITLE
docker-compose $(docker-machine config default) up Fails.

### ISSUE THREAD

**Issue by jduhamel** [docker/compose#3534]
docker and docker-compose handle arguments differently. 

```docker-compose $(docker-machine config default) up ```causes an error. (see below) 
and 
```docker-compose $(docker-machine config default | xargs) up ``` works. 

joe@jsd-mbp ~ $ docker-compose $(docker-machine config default) -f docker-compose.yml up                                                        [2.2.3]
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 58, in main
  File "compose/cli/main.py", line 106, in perform_command
  File "compose/cli/command.py", line 33, in project_from_options
  File "compose/cli/docker_client.py", line 36, in tls_config_from_options
  File "site-packages/docker/tls.py", line 47, in __init__
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
docker-compose returned -1
joe@jsd-mbp ~ $

**Comment by jduhamel** [comment]
this issus is that tls.py is calling os.path.isfile(cert) where cert is a quoted path. so in python ```tls_cert=' "/Users/joe/.docker/machine/cert.pem" '

**Comment by shin-** [comment]
Makes sense. Thanks for the report!

**Comment by mattupstate** [comment]
Compose doesn't like it, even if you strip the quotes

```
$ docker-compose $(docker-machine config default | sed 's/\"//g') ps
ERROR: TLS configuration is invalid - make sure your DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are set correctly.
You might need to run `eval "$(docker-machine env default)"`
```

**Comment by jduhamel** [comment]
Try docker-compose $(docker-machine config default | xargs ) ps

**Comment by mattupstate** [comment]
@jduhamel ah, that does work, thanks
