### ISSUE TITLE
Show only new logs

### ISSUE THREAD

**Issue by Yajo** [docker/compose#3537]
It would be very nice to have an option in `docker-compose logs` that only displays new logs, since the last time you showed them up, since the last time images were restarted, or just with a `--lines` option that displays from the last X lines, just like `tail`.

**Comment by Joshfindit** [comment]
See https://github.com/docker/compose/issues/2227
As of 1.7.0 you can use `docker-compose logs --tail=X` to start with the last `X` lines

**Comment by Yajo** [comment]
Yes, I'm using that since it landed.
