### ISSUE TITLE
Be able to set IP address of generated containers in fig.yml

### ISSUE THREAD

**Issue by rightaway** [docker/compose#354]
For some services I'm running from containers I need to set a listen-address to something other than localhost. Unfortunately it doesn't let me set a wildcard IP address to listen on all interfaces. And it's in a configuration plaintext file, so environment variables won't help me here.

There should be some way to set the IP address of the generated container, either from the command line or from fig.yml.

**Comment by dnephin** [comment]
If your application can't read environment variable or use `0.0.0.0` that's an issue with the application.

Docker doesn't allow you to choose your IP, so there is nothing fig can do to support this.  There are likely already open issues on the docker project to support this.
