### ISSUE TITLE
Recreating containers with graceful stopping

### ISSUE THREAD

**Issue by mvdstam** [docker/compose#3554]
When recreating containers with `docker-compose up`, it seems that docker-compose runs the `docker stop` command prior to re-creating the new containers if there already were existing containers. This means that first a `SIGTERM` signal is sent to shutdown the container.

I would like the option to specify which signal is sent when containers are being stopped prior to being recreated, such as a `SIGQUIT`, so containers running `php-fpm` and `nginx` can be stopped gracefully.

Example:

`docker-compose up -d -s SIGQUIT`

Thoughts?

**Comment by ijc** [comment]
Issue grooming: I think we now have `stop_signal` which sounds like it resolves this.
