### ISSUE TITLE
VERY SLOW network connections to localhost container when not connected to Internet

### ISSUE THREAD

**Issue by liamzebedee** [docker/compose#356]
Firstly, Fig is a wonderful piece of software, thanks so much for designing something so simple yet powerful to use. Now onto my problem:

I have an issue where my Rails app (as based off of your tutorial) is receiving connections to the Rack server very long after the browser initiates them (20 seconds), and is very slow in transmitting data (another 10 seconds on top of that). The interesting thing is this only happens **when Ubuntu is not connected to the Internet**. I've tested this without Internet and it runs slowly, yet when I'm connected to the home wifi it loads fine.

I've also tried this out again with the vanilla Rails app, restarted, turned off the firewall etc. Nothing seems to work.

I think it's something to do with the docker0 interface.

**Comment by awen190418** [comment]
> Okay, I tested it, and it was because of DNS resolution. When you "disable" typical Google DNS and instead use localhost, the latency goes away. This is probably because without doing this Docker assumes that 127.0.0.1 is some address that needs to be looked up via a NS, and spends a lot of time waiting for a response (presumably because it sent it via UDP, it waits longer because of lost/dropped packets). This is also why the request wasn't recorded immediately, as DNS is at a lower-level on the net stack.
> 
> Nonetheless, it didn't help the binaries being out of sync with docs haha (#325)

Could you please let me know how can I disable Google DNS and use the localhost instead? I am facing the exact same problem with mysql database running on the container. When I connect it without an internet connection from the host machine it takes almost around 10 seconds.

**Comment by awen190418** [comment]
> Okay, I tested it, and it was because of DNS resolution. When you "disable" typical Google DNS and instead use localhost, the latency goes away. This is probably because without doing this Docker assumes that 127.0.0.1 is some address that needs to be looked up via a NS, and spends a lot of time waiting for a response (presumably because it sent it via UDP, it waits longer because of lost/dropped packets). This is also why the request wasn't recorded immediately, as DNS is at a lower-level on the net stack.
> 
> Nonetheless, it didn't help the binaries being out of sync with docs haha (#325)

@liamzebedee Could you please let me know how can I disable Google DNS and use the localhost instead? I am facing the exact same problem with mysql database running on the container. When I connect it without an internet connection from the host machine it takes almost around 10 seconds.
