### ISSUE TITLE
Optional environment file (env_file)

### ISSUE THREAD

**Issue by dorianamouroux** [docker/compose#3560]
Hi !

I'm using docker compose for my project.
All my api keys are stored in a local file (ignored by git) and I inject it into my project with `env_file` in my `docker-compose.yml`.
Most of those variables are only for production, you can run the project with the file empty.
The problem is, I can't start my container if the file doesn't exist.
It could be a good idea to add a parameter to env_file to make it optional.

Cheers !
Dorian

**Comment by sanmai-NL** [comment]
What about creating an empty file? A lot less surprising than accepting non-existing environment variable files.

**Comment by dorianamouroux** [comment]
That's what we do indeed, but I think an empty file is worse than a non-existent file (with a warning)

**Comment by eric-tucker** [comment]
I too would like support for letting the execution through when an env_file doesn't exist.  Some of the tasks in docker-compose are not executed and if the env_file of those non-executed tasks don't exist, who cares?  It should not prevent me from moving forward.

It's a pain in the arse!

**Comment by akalipetis** [comment]
I would also agree on this one, I would propose creating a warning, in a similar way we do if an environment `$variable` exists in a `docker-compose.yaml` file, but is not included in the current environment.

I could draft a PR if this is a behaviour we agree upon.

The upsides I see on such an implementation are:

* the actual file is not necessary, meaning that you don't have to create it each time you clone (given that usually `.env` files are ignored)
* you still get a warning if the file doesn't exist, so you can be aware of times where a file should have been loaded but eventually didn't, for example due to a typo

**Comment by Ghazgkull** [comment]
Yes please! This would greatly improve the process of adding new env_files. The song-and-dance necessary to create dummy env files is annoying (getting a file into the Git repo but then making sure changes aren't tracked).

**Comment by nilbus** [comment]
@akalipetis That implementation you described sounds perfect to me.

**Comment by shin-** [comment]
Closing, see https://github.com/docker/compose/pull/3955#issuecomment-341231156 for rationale.

**Comment by collinbarrett** [comment]
Can this be reconsidered? Having to `touch` dummy `.env` files in a ton of release pipelines adds a ton of overhead.

**Comment by idubinets** [comment]
I faced the same issues as well and I have to create the dedicated docker compose for the local dev. This is not convenient at all. It found be nice if env_files be optional as @akalipetis suggested

**Comment by ppershing** [comment]
For me, I am OK with failing if you want to start the service. However, we have many services in one docker-compose and we dont' launch all of them on all of our machines. And this makes it extremely painful because you need to create empty envs everywhere.

**Comment by 5ay3h** [comment]
IMHO there is no reason why `env_file` of a not used/initiated service will be evaluated - can we make this operation lazy(er)?

Currently all other service's params (`image`, `build`'s context, `volumes`, etc) are also treated as suggested (not being evaluated unless used) - why `env_file` should be different?


@ulyssessouza 🙏?

**Comment by chrisdlangton** [comment]
Support :+1: 
Why? Go read how the rationale of the opposed is ignorant to the issue
https://github.com/docker/compose/pull/3955#issuecomment-870198643

**Comment by nick-lavrik** [comment]
found this thread with same "issue / idea"

we don't need "optional env_file", we always can split our `docker-compose.yml` into several parts (core + local/alter/ci/etc.) and combine them with any `-f` options e.g. `docker-compose -f docker-compose.core.yml -f docker-compose.ci.yml up` (and setup our CI env_file from `docker-compose.ci.yml` - works like a magic

**Comment by LudovicTOURMAN** [comment]
As a workaround, I'm using that syntax (pointing by default on `/dev/null` file):
```yaml
  my-service:
    image: my-service:1.2.3
    env_file:
      - ${MY_SERVICE_ENV_FILE:-/dev/null}
```

You can then either use: `docker compose up`
or `MY_SERVICE_ENV_FILE=my-service.env docker compose up`

**Comment by BuriedStPatrick** [comment]
Came across this issue while googling for a solution for my highly specific use case. To anyone else coming across this issue, this IS actually implemented and no longer requires any hacks as of Docker Compose `v2.24.0`:

```yaml
version: 3.9
services:
  my-service:
    env_file:
      - path: /path/to/optional/.env
        required: false # Makes the file optional. Default value is 'true'
```

Docs: https://docs.docker.com/compose/environment-variables/set-environment-variables/#additional-information

**Comment by mihow** [comment]
Wow! Thank you for the follow up. I guess if you just wait long enough
sometimes.

**Comment by sinux-l5d** [comment]
> Came across this issue while googling for a solution for my highly specific use case. To anyone else coming across this issue, this IS actually implemented and no longer requires any hacks as of Docker Compose `v2.24.0`:
> 
> ```yaml
> version: 3.9
> services:
>   my-service:
>     env_file:
>       - path: /path/to/optional/.env
>         required: false # Makes the file optional. Default value is 'true'
> ```
> 
> Docs: https://docs.docker.com/compose/environment-variables/set-environment-variables/#additional-information

Is it possible to do the same from the CLI with `--env-file` flag or COMPOSE_ENV_FILES variable ? 

Seems like docker compose won't complain if `.env` doesn't exist, but use it if it exists. But if I supply a env file that doesn't exist, it will just fail

**Comment by sinux-l5d** [comment]
Thanks for your answer, I didn't think of a wrapper script. I'm using a systemd service with a `%i` parameter to managed my docker-compose projects, and wanted to use a additional .passwords if it exists (some services don't require any password).
I guess I'll be writing a little script then, thanks again.
