### ISSUE TITLE
Relative build paths are broken for compose files in multiple directories

### ISSUE THREAD

**Issue by csaftoiu** [docker/compose#3568]
## The Use Case

I have a project with two docker-compose files in different directories. The use case is to have a common set of containers in a subdirectory which I can include in other projects.
## The Bug

Each `docker-compose.yml` uses build paths relative to the compose file. They work individually. However, when combining both files, the relative paths are all based off the location of the **first** compose file, instead of relative to the compose file that contains the specification. This basically makes this unworkable.
## How to Reproduce

See the following project structure (zip file: [relative-path.zip](https://github.com/docker/compose/files/306037/relative-path.zip))

```
MacBook-Pro:relative-path csaftoiu$ ls
build1             docker-compose.yml subdir
MacBook-Pro:relative-path csaftoiu$ ls subdir
build2             docker-compose.yml
MacBook-Pro:relative-path csaftoiu$ cat build1/Dockerfile
FROM ubuntu:14.04

MacBook-Pro:relative-path csaftoiu$ cat subdir/build2/Dockerfile
FROM ubuntu:14.04

MacBook-Pro:relative-path csaftoiu$ cat docker-compose.yml
version: '2'

services:
  _build1:
    build:
      context: ./build1
    command: "true"

MacBook-Pro:relative-path csaftoiu$ cat subdir/docker-compose.yml
version: '2'

services:
  _build2:
    build:
      context: ./build2
    command: "true"
```

The compose files are uncombinable:

```
MacBook-Pro:relative-path csaftoiu$ docker-compose -f docker-compose.yml -f subdir/docker-compose.yml run --rm _build1
ERROR: build path /Users/csaftoiu/tmp/relative-path/build2 either does not exist, is not accessible, or is not a valid URL.
MacBook-Pro:relative-path csaftoiu$ docker-compose -f docker-compose.yml -f subdir/docker-compose.yml run --rm _build2
ERROR: build path /Users/csaftoiu/tmp/relative-path/build2 either does not exist, is not accessible, or is not a valid URL.
MacBook-Pro:relative-path csaftoiu$ docker-compose -f subdir/docker-compose.yml -f docker-compose.yml run --rm _build1
ERROR: build path /Users/csaftoiu/tmp/relative-path/subdir/build1 either does not exist, is not accessible, or is not a valid URL.
MacBook-Pro:relative-path csaftoiu$ docker-compose -f subdir/docker-compose.yml -f docker-compose.yml run --rm _build2
ERROR: build path /Users/csaftoiu/tmp/relative-path/subdir/build1 either does not exist, is not accessible, or is not a valid URL.
```
## How to Fix

Consider the build paths relative **to the compose file they were defined in**, instead of the first compose file on the command line.

**Comment by xificurC** [comment]
I just hit into this. This is a pretty serious bug that should be relatively easy to fix, any dev to comment?

**Comment by soulmachine** [comment]
I just bump into this issue too, this is not convenient,  hope it be fixed soon

**Comment by Rhathe** [comment]
I also have this issue. I have a repo that has multiple other repos as submodules, and the main parent repo is used to bring them all up as one system. The workaround is to have one compose file in the parent repo, which is inconvenient and requires the parent repo to know the inner workings of the other repos and be kept in sync with them.

**Comment by tbal** [comment]
For the sake of completeness, this is documented[ here](https://docs.docker.com/compose/extends/#/understanding-multiple-compose-files):

> When you use multiple configuration files, you must make sure all paths in the files are relative to the base Compose file (the first Compose file specified with -f). This is required because override files need not be valid Compose files.
