### ISSUE TITLE
  -

### ISSUE THREAD

**Issue by foklepoint** [docker/compose#3571]

**Comment by johnharris85** [comment]
I disagree with your expected result. Compose is meant to model a set of containers in a specific state. That is it's level of granularity. If it's unable to start up that set of containers in that state, it should fail. 

It is not just a 'run list' of independent events / containers.

**Comment by foklepoint** [comment]
I agree that compose is meant to model a set of services in a certain state. However, when running a service, it's odd to be expecting failures on services independent of it. 

I also believe the use-case here speaks for itself. I should be able to have one central docker-compose but if I need to only run a few select services, I shouldn't need to write a new docker-compose with only those select services. It would suck to have to maintain two different compose files.

**Comment by johnharris85** [comment]
My argument is that they may be 'technically' independent, but putting them in a compose project means they are not 'functionally' independent, hence it should fail if one piece can't start. Does this compose project model a functional unit? Are the other services useful if one doesn't come up?

**Comment by foklepoint** [comment]
Hmm interesting. What do you define as functionally independent?
