### ISSUE TITLE
Option to disable check for orphans with docker-compose

### ISSUE THREAD

**Issue by rreinurm** [docker/compose#3573]
`docker-compose version 1.7.1, build 0a9ab35`

I am using docker-compose option -p to group containers which belong to same environment so I have visually easy naming convention in place like _test_service_1_. For example I have **test** environment where I run 50 projects meaning there can 50+ containers. Every project provides own container via docker-compose.yml file. If I execute `docker-compose -p **test** up -d` then docker-compose is busy to compare all those containers which were created from other 50 projects.

**Comment by johnharris85** [comment]
I don't think I really understand the issue here? Is the title related to the content in some way? Are you able to give any more information?

**Comment by rreinurm** [comment]
My issue is that I spread deployment of containers to multiple independent docker-compose files. Project A has own docker-compose.yml and project B, C ... etc have their own corresponding docker-compose yml. Every time I have to make redeploy in one of those project, docker-compose discovers all those other non-defined projects and reports them as orphans. I have quite long list of those reported orphans and I expect my number of services will grow. 

Although at the moment it's only warning message, it causes confusion and I would like to avoid that (plus performance benefit would be nice as well, but it's not so significant atm). My current options are either to concatenate existing docker-compose.yml files as one or stop using `--project` to group containers together by common naming convention.

**Comment by rreinurm** [comment]
Maybe better approach is to define additional filter via labels in docker-compose.yml file or parameters so it would be still possible to find orphans, but they don't report orphans from other projects. In my case example would be `docker-compose --project-name test-environment --label projectA up -d` (although I would prefer to switch project-name and label values). In the end I would like to have naming convention place for easier filtering from web-ui like _test-environment_projectA_1_ What do you think about the approach in general?

**Comment by lukem512** [comment]
:+1:

I too am facing an issue where the orphaned containers is expected, desired behaviour and I would like to suppress this warning. Perhaps a `--suppress-orphan-warning` switch could be added?

**Comment by Carighan** [comment]
Same problem here. We have 12 docker-compose files, each using the same docker file to build different versions (which we want to control separately as they're not updated in sync) of the same system for different environments.

Each up-command, we get a slew of orphan-warnings for actually wanted containers.

**Comment by johnharris85** [comment]
So this would just be a flag to up? Like `docker-compose -p test up -d --suppress-orphan-warning` ?

**Comment by rreinurm** [comment]
I would still prefer to use additional label inside docker-compose.yml file or in command to filter out containers. As I've seen you use your project field as a label then creating docker container already. Why not to give possibility to add additional filter capability, so we still have possibility to detect orphans?

**Comment by emk** [comment]
This could also be implemented as `--no-orphan-warning` or `--ignore-orphans`.

The use case for this feature is a project with two or more `docker-compose.yml` files. Perhaps one file is the main project, and the other file contains a one-shot task that is started separately, as strongly recommended in https://github.com/docker/compose/issues/1896. For example:

- `docker-compose.yml`: The main project, with multiple services.
- `migrate.yml`: A second file specifying how to run database migration tasks.

These could be used as:

```sh
docker-compose -p myapp -f docker-compose.yml up -d
docker-compose -p myapp -f migrate.yml up
```

If you use the same `-p` argument for two different `docker-compose.yml` files, they'll share the same underlying networks.

This actually works quite nicely, except that the orphan detector warns about it. We have some pretty interesting use cases which could make use of this.

**Comment by jnacier** [comment]
+1

**Comment by copernico** [comment]
+1

**Comment by obfuscode** [comment]
+1 For this as well.

My use case: When we stand-up a project, we generate multiple docker-compose yml files for different PHP/MySQL versions like so:
```
php5.6mysql5.5.yml
php5.6mysql5.6.yml
php5.6mysql5.7.yml
php7.0mysql5.5.yml
php7.0mysql5.6.yml
php7.0mysql5.7.yml
php7.1mysql5.5.yml
php7.1mysql5.6.yml
php7.1mysql5.7.yml
```
This allows us to commit these files into a source branch for a project and another developer can pull it down and run the corresponding docker-compose without having to rewrite the file or create a complex docker-compose command.

The project paths, ports, and VIRTUAL_HOST params are also built into these so any dev can stand-up a project environment without any collision between projects. We don't want to get rid of the "orphaned" containers because they're actually other running projects.

I've also written a shell script that prompts for which PHP and MySQL version they want to run, handles a DB dump and import between MySQL versions and runs the docker-compose command with the corresponding yml file for them.

The orphan warning is the crack in this otherwise seamless system.

**Comment by DmitryRomanenko** [comment]
+8

**Comment by copernico** [comment]
I was trying to use docker-compose in a Makefile but that is impossible if there are orphans because make will treat the target as failed in that case (the exit code of docker-compose is not 0) and so I cannot meaningfully chain target dependencies as one would normally do with make (while, I suppose that's why one uses make in the first place, right?).

**Comment by htkoca** [comment]
I just ran into this issue, I only have about 5 containers though. One of the beauties of docker is container variants of the same image, would be nice to bypass this error message.

**Comment by cen1** [comment]
If I run docker compose with two different compose files, the orphan containers reported are not actually orphan containers. Orphan containers should only come from the same compose file, not across all compose files, it doesn't make any sense to me.

**Comment by liyaka** [comment]
Any updates on implementing this feature?

**Comment by Izhaki** [comment]
Same issue as @cen1

**Comment by johnharris85** [comment]
@copernico the exit code is still 0 for me, even with the warning. Are you experiencing another error?

**Comment by avoidik** [comment]
also this flag could be useful for incremental building of an environment with multiple compose-files

**Comment by chrispaynter** [comment]
Having the same issue. I have a postgres container (Based on standard postgres image) running at all times. My integration tests spin up a disposable postgres container and then immediately pulls it down after the tests run. I can't use "--remove-orphans" or I'll lose my main development postgres container which is running from the same image.

**Comment by OnkelTem** [comment]
So what is the status?

**Comment by Hronom** [comment]
What the status of this?

**Comment by simonezampinistud** [comment]
+1

**Comment by shin-** [comment]
Closing via #4992

**Comment by danger89** [comment]
Usage:
`export COMPOSE_IGNORE_ORPHANS=True`

**Comment by alexandernst** [comment]
Please reopen this until https://github.com/docker/compose/pull/4992#issuecomment-657208957 is addressed. @shin-
