### ISSUE TITLE
Option to configure/disable seccomp during build

### ISSUE THREAD

**Issue by Fedcomp** [docker/compose#3583]
I use steamcmd to build dedicated-server docker image. Steamcmd is appear to be wine application and it doesn't work properly with default seccomp rules.

Would it be possible to add a way to configure/disable seccomp also during building of image?

**Comment by shin-** [comment]
Sounds like a request for [docker/docker](http://github.com/docker/docker), unless the feature already exists in the engine and I missed it.

**Comment by Fedcomp** [comment]
Thanks, i though it's already supported. I will close until feature will be in docker/docker.
