### ISSUE TITLE
Overlay network + custom IP

### ISSUE THREAD

**Issue by vingrad** [docker/compose#3587]
How can I define the custom IP for containers in compose-file? I use overlay network with network_mode: my-net

So I cannot specify the IP via networks, because I get the following error:
ERROR: 'network_mode' and 'networks' cannot be combined

**Comment by ijc** [comment]
Sorry this was never answered. I suppose that after so long you are no longer interested in an answer (and I don't know the answer off hand), nonetheless apologies for closing without an answer after so long.
