### ISSUE TITLE
COMPOSE_HTTP_TIMEOUT is set but incorrect value is print when timeout is reached

### ISSUE THREAD

**Issue by rmmcnulty9** [docker/compose#3596]
I set COMPOSE_HTTP_TIMEOUT to 300, but when it times out the error message says:
```
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

I looked at the source on master and it appears to still be using the const HTTP_TIMEOUT in the message.

This is:
Docker version 1.11.2, build b9f10c9
docker-compose version 1.7.1, build 0a9ab35

**Comment by johnharris85** [comment]
It takes either the value of DOCKER_`CLIENT_TIMEOUT` or 60, if the former is not set.

`HTTP_TIMEOUT = int(os.environ.get('DOCKER_CLIENT_TIMEOUT', 60))`

Maybe the docs / CLI error is wrong if it's telling you to specify `COMPOSE_HTTP_TIMEOUT`?

Not sure whether we should change docs or add the COMPOSE variable.

**Comment by rmmcnulty9** [comment]
I am referencing this function in `cli/error.py`

```
def log_timeout_error():
    log.error(
        "An HTTP request took too long to complete. Retry with --verbose to "
        "obtain debug information.\n"
        "If you encounter this issue regularly because of slow network "
        "conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher "
        "value (current value: %s)." % HTTP_TIMEOUT)
```

This is logging `HTTP_TIMEOUT` (from const) instead of what whatever is set for `COMPOSE_HTTP_TIMEOUT` (if it is set).

**Comment by danielnoom** [comment]
Only the error message is wrong.

In compose/compose/cli/docker_client.py first COMPOSE_HTTP_TIMEOUT is used, then HTTP_TIMEOUT which first checks DOCKER_CLIENT_TIMEOUT and then uses the default value of 60.

In  compose/compose/cli/errors.py , HTTP_TIMEOUT is used immediately without first checking COMPOSE_HTTP_TIMEOUT.

**Comment by aanand** [comment]
@rmmcnulty9 is correct - `HTTP_TIMEOUT` does not contain the correct value for the timeout if `COMPOSE_HTTP_TIMEOUT` is set, either in the shell environment or in `.env`. This is a bug.

Incidentally, we can probably stop reading `DOCKER_CLIENT_TIMEOUT` - it's now been deprecated for 8 months.
