### ISSUE TITLE
Containerised docker-compose ignores shell environment

### ISSUE THREAD

**Issue by zioc** [docker/compose#3606]
[Documentation](https://docs.docker.com/compose/compose-file/#variable-substitution) stands that docker-compose should substitute shell variables. For now it doesn't seems to be the case for containerised docker-compose, as env is not passed to docker-compose container.

Appending "--env-file <(env)" to [containerised compose entry point](https://github.com/docker/compose/blob/master/script/run/run.sh#L56) makes the job, anyway, not sure if it should be sanitized or not - eg. "--env-file <(env | grep -i _proxy)"

**Comment by dmc2015** [comment]
@zioc is this still an issue? depending on the language you may be able to use a plugin/libary to handle variables that you want to use inside of your container.

Also, the documentation has changed a bit and there are a couple of ways to handle env variables.
https://docs.docker.com/compose/environment-variables/

**Comment by ijc** [comment]
Issue grooming: When running containerised the environment from which things are substituted will be the one from inside the container, not the one on the host, you can use `COMPOSE_OPTIONS` envvar (on the host) to cause the entry point to add `-e` options to the `docker run` and propagate specific variables into the container.
