### ISSUE TITLE
windows7 x64 Garbled

### ISSUE THREAD

**Issue by xdxiaodong** [docker/compose#3610]
![2016-06-16_23-03-44](https://cloud.githubusercontent.com/assets/7643447/16121645/9e71f55e-3416-11e6-8914-ed18afbeafc0.png)
![2016-06-16_23-05-11](https://cloud.githubusercontent.com/assets/7643447/16121699/d5b4ab60-3416-11e6-86a4-358ed7012bc9.png)

**Comment by shin-** [comment]
Thanks for the report. Same issue as #2095 and #2800 !

**Comment by shin-** [comment]
Closing to consolidate: #2095
