### ISSUE TITLE
Duplicated documentation?

### ISSUE THREAD

**Issue by brettgoulder** [docker/compose#3614]
Hey,

It seems these two articles are duplicated:

https://docs.docker.com/compose/compose-file/
https://docs.docker.com/v1.8/compose/yml/

One thing I noticed is that the compose-file docs have documentation around depends_on, while the yml file does not.

Should we just redirect to the compose-file docs and keep that as the canonical reference for what goes into docker-compose.yml?

**Comment by shin-** [comment]
https://docs.docker.com/v1.8/compose/yml/ is documentation for an older version of compose (the one that was released simultaneously with Docker Engine 1.8, which would be Compose 1.4 presumably). I believe it is kept available for people running older versions of the project. 

Sorry about any confusion this might have caused!
