### ISSUE TITLE
docker-compose down should not error on network with active containers

### ISSUE THREAD

**Issue by teohhanhui** [docker/compose#3618]
When a network cannot be removed due to active containers (connected from another Docker Compose project in my case), `docker-compose down` just exits.

This means when I do `docker-compose down --volumes` the volumes are not removed, as those are only processed after the networks.

**Comment by shin-** [comment]
Closing - Looks like this has been fixed since!

**Comment by floydwch** [comment]
@shin-  It still occurred...
