### ISSUE TITLE
CRLF line terminators in Compose output

### ISSUE THREAD

**Issue by michelesr** [docker/compose#3623]
When the output of the container process contains stderr messages, and Compose stdout is redirected to a file, it appears to contain CRLF line terminator (`^M`).
#### Steps to reproduce

Create a simple `docker-compose.yml`:

``` yaml
app:
  image: debian:8
```

Now run:

``` bash
$ docker-compose run app bash -c '>&2 echo stderr_msg; echo stdout_msg' > out

$ file out
out: ASCII text, with CRLF line terminators

$ cat -A out
stderr_msg^M$
stdout_msg^M$
```

As you can see there's a unwanted `^M`.

This issue isn't related to Docker:

``` bash
$ docker run debian:8 bash -c '>&2 echo stderr_msg; echo stdout_msg' > out
stderr_msg

$ cat -A out
stdout_msg$

$ file out
out: ASCII text
```
#### Version

```
$ docker-compose version
docker-compose version 1.7.1, build 6c29830
docker-py version: 1.8.1
CPython version: 2.7.11
OpenSSL version: OpenSSL 1.0.2h  3 May 2016

$ uname -a
Linux user 4.6.2-1-ARCH #1 SMP PREEMPT Wed Jun 8 08:40:59 CEST 2016 x86_64 GNU/Linux
```

**Comment by jalessio** [comment]
I'm seeing this same behavior with docker-compose v1.8.1 that ships with Docker for Mac:
```
$ docker-compose version
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.3
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

**Comment by thaJeztah** [comment]
This is due to a TTY being present. When running a container with a TTY, newlines are automatically converted to CRLF. See https://github.com/docker/docker/issues/8513#issuecomment-216191236, which also shows how to [disable this functionality](https://linux.die.net/man/1/stty).
