### ISSUE TITLE
Runtime constraints such as memory, cpu, etc in docker-compose file

### ISSUE THREAD

**Issue by styfle** [docker/compose#3624]
The [docker run](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources) command has settings for runtime constraints such as memory, cpu, etc.

I think these settings should be available to use in the [docker-compose.yml](https://docs.docker.com/compose/compose-file/) file.

**Comment by jbwinters** [comment]
You can set them through environment variables:
https://docs.docker.com/compose/swarm/#manual-scheduling
https://docs.docker.com/swarm/scheduler/filter/

**Comment by shin-** [comment]
They are available and documented in [this section](https://docs.docker.com/compose/compose-file/#cpu-shares-cpu-quota-cpuset-domainname-hostname-ipc-mac-address-mem-limit-memswap-limit-privileged-read-only-restart-shm-size-stdin-open-tty-user-working-dir) of the docs page you linked in your post.
