### ISSUE TITLE
environment variables in yml file ignored while building containers

### ISSUE THREAD

**Issue by laggingreflex** [docker/compose#3632]
I have a `./docker-compose.yml`

    version: '2'
    services:
      client:
        build:
          context: ./client
        environment:
          NODE_ENV: development

and `./client/dockerfile` 

    FROM ...
    RUN echo $NODE_ENV

the output of which is blank, meaning the environment variable set in compose yml file are being ignored in dockerfile while building container. 

Incidentally it works while actually running the container:

    CMD echo $NODE_ENV

The problem is only during build

**Comment by friism** [comment]
These have to be specified under `build`: https://docs.docker.com/compose/compose-file/#args

Also see https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg

**Comment by laggingreflex** [comment]
Did not know about (or understood) the [args feature](https://docs.docker.com/engine/reference/builder/#arg) till now. Thanks!
