### ISSUE TITLE
docker-compose bundle should work with 'build: .'

### ISSUE THREAD

**Issue by nathanleclaire** [docker/compose#3640]
The [getting started example](https://docs.docker.com/compose/gettingstarted/) of Compose doesn't work with `docker-compose bundle` when I tried it (Docker for Mac on a pretty new Macbook at DockerCon), due to the `build: .`.

To get a DAB from with content-addressable image SHAs would be fantastic.  Maybe this could also have built-in support for `push` to ensure image availability?

**Comment by nathanleclaire** [comment]
Example output:

```
WARNING: Compose needs to pull the image for 'redis' in order to create a bundle. This may result in a more recent image being used. It is recommended that you use an image tagged with a specific version to minimize the potential differences.
Pulling redis (redis:latest)...
latest: Pulling from library/redis
Digest: sha256:b50f15d427aea5b579f9bf972ab82ff8c1c47bffc0481b225c6a714095a9ec34
Status: Image is up to date for redis:latest
ERROR: Service 'web' doesn't define an image tag. An image name is required to generate a proper image digest for the bundle. Specify an image repo and tag with the 'image' option.
```

**Comment by friism** [comment]
@nathanleclaire the problem is that the image sha can only be know after pushing to a registry. Also see: https://github.com/docker/compose/issues/3639

**Comment by hantuzun** [comment]
We've created a docker-compose project which has a few subdirectories for docker builds. 

Due to this issue, we need to publish all of these sub docker builds and that will make development noticeably harder.
