### ISSUE TITLE
`docker tag -f` deprecated in v.1.12.x

### ISSUE THREAD

**Issue by breezykermo** [docker/compose#3651]
It looks like `docker tag -f image/name newImage/name` has changed to `docker tag image/name newImage/name` in the beta version of Docker 1.12.x. Just raising this as an issue because it prevented me from running any docker-compose.yml files, as it automatically overwrites the tag with the name of the current directory.

**Comment by shin-** [comment]
Closing - after a quick look through the code, it doesn't seem like we call `tag` anywhere in the Compose codebase (but maybe we used to?)
