### ISSUE TITLE
Need a command to get container name of service

### ISSUE THREAD

**Issue by netroby** [docker/compose#3663]
While create service using docker-compose. the real container name will be a bit longer.
So can we add a command to get container name for a service?

for example : the real name of redis service will be `ahugelongproject_redis_1`

while we exec

```
docker-compose svc redis
```

 it will display the real redis service name 

```
ahugelongproject_redis_1
```

We have to find out the container name by ourself, it is hard and a ugly way

```
docker-compose ps | grep redis | awk '{ print $1 }'
```

**Comment by christoph-daehne** [comment]
though this helps me already, #1262

> docker-compose ps -q data

**Comment by dazraf** [comment]
Why is this closed? 
docker-compose recently changed it's container naming convention. broke some scripts. The approach with using grep and awk work well on *nix, but aren't portable! 
We should have a clean function available in `docker-compose` to return the container name for a service.

**Comment by reitzig** [comment]
Unfortunately, the `awk` workaround breaks if container names are wrapped -- which can't currently be prevented.
--> #2369
