### ISSUE TITLE
"http: Hijack is incompatible with use of CloseNotifier in same ServeHTTP call" errors

### ISSUE THREAD

**Issue by justincormack** [docker/compose#3685]
Using 1.8-rc1 and docker 1.12-rc3 with the following compose file:
```
version: '2'
services:
  test:
    build:
      context: .
```
and Dockerfile:
```
FROM alpine
```

If I do:
```
whale:comprun justin$ docker-compose build test
Building test
Step 1 : FROM alpine
 ---> f70c828098f5
Successfully built f70c828098f5
whale:comprun justin$ docker-compose run test ls
http: Hijack is incompatible with use of CloseNotifier in same ServeHTTP call
                                                                             http: Hijack is incompatible with use of CloseNotifier in same ServeHTTP call
                                                                                                                                                          whale:comprun justin$ 
```

Looks like a missed case in https://github.com/docker/compose/pull/1374

cc @dnephin

**Comment by SantoDE** [comment]
I now have the same issue. Just upgraded and my compose setup refuses to start :(

**Comment by jonniedarko** [comment]
@SantoDE I was able to restart after I removed all containers , I still get the log `jack is incompatible with use of CloseNotifier in same ServeHTTP call` and no other log outs but everything seems to be running

**Comment by SantoDE** [comment]
@jonniedarko oh you are right. The containers are up, but I dont have any more logs. Still an issue then I guess :/ cc: @justincormack

**Comment by DejaAugustine** [comment]
`Docker version 1.12.0-rc3, build 91e29e8, experimental` is pretty much non-functional for me due to this bug.

I was lucky in that I still had an old `Docker.dmg` from May with `Docker version 1.11.0, build 4dc5990` on it, but this change is seriously breaking.

**Comment by PatrickDRusk** [comment]
Busted in Boston, too.

**Comment by SantoDE** [comment]
Hopefully the docker team can fix that fast :/

**Comment by javawolfpack** [comment]
Fingers crossed... was having no issues until I just installed the update. Had this one after fixing another that required me to rebuild my containers...

**Comment by JonathanTech** [comment]
Well, I get that error, but if I run docker-compose in daemon mode everything seems to be working fine.

**Comment by JonathanTech** [comment]
I can still attach using docker exec -it <container_name> bash and everything is working as expected. docker attach also works as expected.

**Comment by javawolfpack** [comment]
I need to run one of my containers in bash currently... so this is causing a significant headache :(

**Comment by dnephin** [comment]
Did this just start happening with RC3? It was fine with RC2?

**Comment by emgeee** [comment]
+1 for this issue. Just upgraded to Docker for Mac Version 1.12.0-rc3-beta18 (build: 9969) and I'm running into this issue

**Comment by javawolfpack** [comment]
@JonathanTech that's interesting... maybe I can run it manually but fails when I try interactive bash from compose.

**Comment by SantoDE** [comment]
@dnephin Yep, RC2 was fine. Just right after I upgraded to RC3 the madness started.

**Comment by milehimikey** [comment]
+1 on this issue as of RC3

**Comment by javawolfpack** [comment]
+1 only happened when I upgraded to Version 1.12.0-rc3-beta18 (build: 9969) minutes ago

**Comment by antipin** [comment]
+1 for Version 1.12.0-rc3-beta18 (build: 9969)

**Comment by antipin** [comment]
Anybody knows how to downgrade to RC2?

**Comment by praveenperera** [comment]
+1 for Version 1.12.0-rc3-beta18 (build: 9969)

**Comment by PatrickDRusk** [comment]
@antipin, I can't find a back-rev to download.

I am able to docker exec into a container that is apparently hung when I do the docker-compose run.

**Comment by jzimmek** [comment]
+1 for Version 1.12.0-rc3-beta18 (build: 9969)

**Comment by eko** [comment]
I also have this issue with same version (1.12.0-rc3-beta18 (build: 9969)) just after the upgrade.

**Comment by imnotquitejack** [comment]
+1 for Version 1.12.0-rc3-beta18 (build: 9969)

**Comment by erinnichols** [comment]
+1, Version 1.12.0-rc3-beta18 (build: 9969)

**Comment by JonathanTech** [comment]
FYI - for the devs - Diagnostic ID : 705F4449-0DA5-43A4-9BC3-2AD6F1FF15F3

**Comment by praveenperera** [comment]
Found the old build in the Trash (9779) works again

**Comment by javawolfpack** [comment]
I have the docker.dmg on another computer for Version 1.12.0-rc2-beta17 (build: 9779), hoping I can install it over the new one.

**Comment by mathportillo** [comment]
+1, Version 1.12.0-rc3-beta18 (build: 9969)

**Comment by visokoo** [comment]
Running into the same problem after updating, now reverting back to rc2 for the time being...

**Comment by javawolfpack** [comment]
So old installer allowed me to roll back and now working... I'd share the dmg, but not really good to trust links from strangers on the net.

**Comment by antipin** [comment]
Yay! pevious version in fact can be found in trash (on OSX)

**Comment by mckn** [comment]
+1

**Comment by gvc** [comment]
Thank god for the Thrash

**Comment by EugenMayer** [comment]
How can such a thing slip through QA, beta, alpha or whatever.

Coming from docker, you kind expected to see a CI, right.

**Comment by ograycode** [comment]
Can confirm that this happens on python:2.7 and node:6.2 containers when running docker compose commands. Reverted back to 9779 and told my team not to upgrade because the next build is broken.

**Comment by PatrickDRusk** [comment]
And I will never empty my trash again...

**Comment by aethant** [comment]
Happened to me with node:6.1 and mongo:latest. Reverted to 9779 and rebuilt containers, working for now.

**Comment by skwp** [comment]
same problem, 1.12-rc3 sinatra app

**Comment by FrenchBen** [comment]
@EugenMayer https://github.com/docker/docker/issues/24343#issuecomment-230599107

**Comment by ajardin** [comment]
As @icecrime said in https://github.com/docker/docker/issues/24343#issuecomment-230599107,
recreating your containers will solve your issue. Even if it's a little bit annoying. ;-)

**Comment by iwaffles** [comment]
Seeing the same issue here with 1.12-rc3 using the redis container image: `redis:2.8.23`

**Comment by iwaffles** [comment]
For what it's worth, downloading the old version and replacing it with the new version worked flawlessly for me on Mac: https://github.com/docker/docker/issues/24343#issuecomment-230605770

**Comment by Chekote** [comment]
Roll back to Beta17 until this is fixed: https://download.docker.com/mac/beta/1.12.0.9779/Docker.dmg

**Comment by sonnyvan** [comment]
Thanks everyone for the rollback idea. I found beta 17 in my Trash and `docker-compose run` works again.

**Comment by justincormack** [comment]
Apologies for this. This does not appear to be a compose bug, it is a Docker for Mac specific issue, and we will be rolling out a fix as soon as possible. In the mean time please see the download links for old versions https://github.com/docker/docker/issues/24343#issuecomment-230599107 if you updated.

**Comment by vkrol** [comment]
I see this message on Windows too.

**Comment by justincormack** [comment]
A hotfix has been released, so it should be fine to update, apologies for the issue.

**Comment by justincormack** [comment]
Apologies for this, a hotfix has been released and it should be safe to update.

**Comment by Manoj-nathwani** [comment]
Updated to latest version of docker which fixed the issue 😄

**Comment by jonniedarko** [comment]
+1

**Comment by cap10morgan** [comment]
Running the latest Docker for Mac that mine says is available, I still get this error trying to bring up docker-compose stacks.

**Comment by jamshid** [comment]
@justincormack where is the hotfix? "Check for updates" says my rc3 Beta 18 is the latest but I still get the `[Hi]jack is incompatible with use of CloseNotifier in same ServeHTTP call` error.
```
$ docker version
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:09:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   876f3a7
 Built:        Tue Jul  5 02:20:13 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by gitnickgit** [comment]
current master should be rolled back and a hot-fix build.  This way new users don't get something that is broken right off the bat.

**Comment by antipin** [comment]
Docker version 1.12.0-rc3, build 91e29e8, experimental
Still has this error:
```
Creating api_data_1
Creating api_db_1
Creating api_api_1
Attaching to api_data_1, api_db_1, api_api_1
db_1    | jack is incompatible with use of CloseNotifier in same ServeHTTP call
api_1   | jack is incompatible with use of CloseNotifier in same ServeHTTP call
data_1  | jack is incompatible with use of CloseNotifier in same ServeHTTP call
api_data_1 exited with code 0
```

**Comment by antipin** [comment]
Uninstall docker and download beta-17 from site seems to be a solution: https://download.docker.com/mac/beta/Docker.dmg

**Comment by purrcat259** [comment]
I just started getting this issue this morning and I'm on windows. I did check for updates at it says I am up to date.

`docker version`

![image](https://cloud.githubusercontent.com/assets/8162974/16645504/a6c92100-4424-11e6-863f-e250bf4dbf8c.png)

**Comment by justincormack** [comment]
Sorry, we pulled the update temporarily for other reasons. If you still have the issue, you can reinstall the previous version or wait a few hours.

**Comment by tejasmanohar** [comment]
@antipin I'm getting beta-18 when I use that link. know if there's an archive somewhere?

**Comment by antipin** [comment]
@tejasmanohar if you for some reason can't recreate your containers, the only solution I saw is here https://github.com/docker/docker/issues/24343#issuecomment-230887236

If you are using docker in a right way and don't persist your data inside containers, I guess you have no reason not to update to the latest version, recreate containers and it will be ok ;)

**Comment by FrenchBen** [comment]
@tejasmanohar @antipin we also documented it here:
https://docs.docker.com/docker-for-mac/troubleshoot/#/recreate-or-update-your-containers-after-beta-18-upgrade
