### ISSUE TITLE
Bundle may inadvertently release source code

### ISSUE THREAD

**Issue by withinboredom** [docker/compose#3686]
Docker Compose shouldn't auto-push to non-existent repos. Instead it should prompt.

Many users use Docker and Docker Compose to provision development environments. This can cause someone running `docker-compose bundle` to accidentally push new repos that could contain source code. Most people never change their default in Docker Hub from "auto public" to "auto private" for new repos. This can cause people to inadvertently release source code from their development environment if they have permission to create new repos.

**Comment by thaJeztah** [comment]
thanks for opening this issue! we were actually discussing already (following your tweet), and there's some changes that were already made, but not in a release yet.

I think @dnephin knows the details on that.

**Comment by dnephin** [comment]
Already fixed in #3601
