### ISSUE TITLE
Compose should send connection upgrade headers

### ISSUE THREAD

**Issue by dgageot** [docker/compose#3700]
To hint proxies about connection hijacking, Compose should send connection upgrade headers like the docker cli does.

From https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/4-2-hijacking:

> In this version of the API, /attach, uses hijacking to transport stdin, stdout, and stderr on the same socket.
>
> To hint potential proxies about connection hijacking, Docker client sends connection upgrade headers similarly to websocket.

```
Upgrade: tcp
Connection: Upgrade
```

On Docker for Desktop, the proxy that sits between Docker Compose and the daemon will not be aware that the connection will be hijacked. This can lead to an issue where the proxy will install a CloseNotifier and just after that will hijack the connection, which is know to be incompatible. See https://github.com/docker/compose/issues/3685

**Comment by justincormack** [comment]
We have a hacky workaround now in docker 4 mac/win, but it would be nice to fix this.

**Comment by aanand** [comment]
Makes sense. I think the fix needs to go in docker-py.

**Comment by justincormack** [comment]
@aanand do you think there is a chance of fixing this for 1.8? It is proving very hard to work around for docker for mac.

**Comment by dgageot** [comment]
Just submitted a patch to docker-py. Not sure I've got it all right, though https://github.com/docker/docker-py/pull/1124

**Comment by aanand** [comment]
Support has gone in with https://github.com/docker/docker-py/pull/1130, so we just need to do a docker-py release and update the version in `requirements.txt`.

**Comment by aanand** [comment]
OK, this should now be closed by #3769

**Comment by shin-** [comment]
Those changes unfortunately did not make it in docker-py 1.9
