### ISSUE TITLE
On Windows, the cli should connect to a named pipe by default

### ISSUE THREAD

**Issue by dgageot** [docker/compose#3701]
Since Docker 1.11, the docker CLI has been connecting to the daemon on `npipe:////./pipe/docker_engine` named pipe on Windows. Before 1.11, the default behaviour was to connect to `localhost:2375`

Compose 1.8RC1 still defaults to `localhost:2375`.

I believe we should have the same behaviour.

**Comment by aanand** [comment]
Implemented in https://github.com/docker/docker-py/pull/1137.

**Comment by dgageot** [comment]
Neat!

**Comment by aanand** [comment]
We've decided that the npipe code is too immature to be the default. Instead, let's call out the new npipe support in the release notes so people have a chance to play with it. Once it's more stable, we can make it the default in Compose 1.9.
