### ISSUE TITLE
Docker-compose build hanging

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [docker/compose#3719]
Hello,

For some reason I have a service I'm not able to build. when I run `docker-compose --verbose build service-name` it hangs on the following line:

`docker.api.build._set_auth_headers: Sending auth config ('https://index.docker.io/v1/')` 

Any Idea ? 

Thanks !

**Comment by GuillaumeLeclerc** [comment]
On some computers it work, and on some other it hangs at a different place:

```
docker.api.build._set_auth_headers: Looking for auth config
docker.api.build._set_auth_headers: No auth config in memory - loading from filesystem
docker.auth.auth.load_config: File doesn't exist
docker.api.build._set_auth_headers: No auth config found
```

**Comment by aanand** [comment]
Does `docker build <directory>` work fine?

It's possible that the build context is huge and is taking ages to tar up and send to the daemon.

**Comment by GuillaumeLeclerc** [comment]
Internet was particularly slow that day and cloning the repo was slow. It's working again.

Thanks

**Comment by raptor235** [comment]
I'm having same issue but my internet speed is fine getting 60mb

http://i.imgur.com/OxWzIWN.png

**Comment by featherbelly** [comment]
Try adding any large files/folders to [.dockerignore](https://docs.docker.com/engine/reference/builder/#dockerignore-file).
