### ISSUE TITLE
docker-compose bundle --fetch-digests isn't a communicative name

### ISSUE THREAD

**Issue by aanand** [docker/compose#3720]
According to one rather alarmed test user, the name of the `--fetch-digests` flag didn't make it clear that images were going to be pushed. We should perhaps come up with a better one.

**Comment by johnharris85** [comment]
Haha ye I hit this too. The flag name makes perfect sense, but perhaps a warning explaining what it's going to do (and why?).

**Comment by aanand** [comment]
Here's the ambiguity at the root of the problem: a service has both `build` and `image` specified. There is an image available locally with the specified tag, but it doesn't have a digest. What should `docker-compose bundle` do?

Right now, it complains at you and suggests that you rerun with `--fetch-digests`. If you do so, it'll push images for services with a `build` key and no image digest (thereby making the registry calculate one), and pull them for services without a `build` key and no image digest (thereby fetching the existing digest from the registry). 

If you don't want that to happen, you can `docker-compose pull` the image for the service. That'll clobber the image you've got locally - so if you built it, you've lost the result of that build - but now you have a digest (assuming you're on Engine 1.12, which always stores the digest after a push or pull).

Perhaps there should be no `--fetch-digests` flag at all, and `docker-compose bundle` should simply prompt you to `docker-compose push` or `docker-compose pull` for each service. That way you know exactly what's going to happen.

**Comment by johnharris85** [comment]
+1 for removing it and just prompting push or pull. This is also cleaner with a view to the future if the build stuff gets ripped out of compose entirely.

**Comment by aanand** [comment]
ping @dnephin @shykes 

Thoughts? I'm imagining an error message like this:

```console
$ docker-compose bundle
ERROR: Some images are missing digests.

The following images can be either pushed or pulled:

    myusername/web-app
    myusername/worker

Use `docker-compose push web worker` or `docker-compose pull web worker` to fetch their digests.

The following images need to be pulled:

    redis:alpine
    postgres:9.4

Use `docker-compose pull redis db` to fetch their digests.
```

**Comment by dnephin** [comment]
With the changes in docker 1.12 to always populate `RepoDigests` it should be pretty rare that users will need to pull to get a digest. Pushing is still going to be pretty common (for anything built locally), so maybe we can rename the flag to `--push-images` or something like?

Requiring a separate pull sounds fine, since it should be a rare.

**Comment by aanand** [comment]
OK, that makes sense. Perhaps we could add a hint to the error message:

```diff
$ docker-compose bundle
ERROR: Some images are missing digests.

The following images can be either pushed or pulled:

    myusername/web-app
    myusername/worker

Use `docker-compose push web worker` or `docker-compose pull web worker` to fetch their digests.
+ You can automatically push when bundling with `docker-compose bundle --push-images`.

The following images need to be pulled:

    redis:alpine
    postgres:9.4

Use `docker-compose pull redis db` to fetch their digests.
```

**Comment by dnephin** [comment]
That sounds better. " can be either pushed or pulled" seems like it's maybe not as helpful as it could be. I think it's safe to say `push` if the service has `build`.

**Comment by aanand** [comment]
OK, implemented in https://github.com/docker/compose/pull/3762.

I'd still like to try and avoid misleading people into thinking services with a `build` option *must* be pushed, so in the error message I went with "can be pushed" and "need to be pulled". Sound alright?
