### ISSUE TITLE
use context with git repo, specifying branch

### ISSUE THREAD

**Issue by dangrl** [docker/compose#3721]
Is there a way to use the docker-compose build, with git repo as context specifying a single branch that is not master?

**Comment by johnharris85** [comment]
Not checked the code, but assuming compose just passes the build context straight through to the daemon, in which case yes, different branches / commits (whole range of options) are supported. 

See here: https://docs.docker.com/engine/reference/commandline/build/

**Comment by mukhtarkv** [comment]
Finally found the proper reference for writing docker compose file with build context including remote git branch.

See here: https://docs.docker.com/reference/compose-file/build/#attributes
