### ISSUE TITLE
Pull image with docker-compose run

### ISSUE THREAD

**Issue by yakhyadabo** [docker/compose#3724]
Hello, 

Here's a typical docker-compose file. I use is it both for building image (**docker-compose build**) and to run my tests (**docker-compose run test** ). 

         version: '2'
         services:

           test : 
             links: 
               - web 

             cmd : "mvn clean verify"

          web: 
             image: my_repo/my_image:tag
             build: .

When I use the **run** command docker-compose try to build the image before running the test. 

Is there anyway to force it to pull existing image instead of trying to build new one ?

**Comment by aanand** [comment]
`docker-compose run` will only attempt to build the image if there isn't already an image with the specified tag. So if you `docker-compose pull` first, it won't attempt to build.

**Comment by yakhyadabo** [comment]
Ok thanks
