### ISSUE TITLE
Truncated output with 'docker-compose run' in jenkins jobs

### ISSUE THREAD

**Issue by bhuisgen** [docker/compose#3727]
I'm affected by this old bug #199 / #658 with the last version 1.7.1. My jenkins jobs are based on docker-compose run (to be exact: jenkins => ssh => docker-machine => docker-compose run => build container) and my logs are truncated and/or garbled.

From console execution it's working fine so I was thinking about line buffering. The solution to append all run commands with stdbuf resolves it.

```
stdbuf -i0 -e0 -o0 docker-compose run ...
```

This bug is very boring. Can you disable line buffering for run commands ?

**Comment by sambernet** [comment]
Affected from same issue. Was using workaround of using named containers in `docker-compose run` commands, redirecting output to `> dev/null`, then getting the logs with `docker logs` and finally deleting the named container again.

Thanks for the workaround above, at least it allows me to use one-off containers with `--rm` now.

Still an ugly hack, though.

**Comment by tnguyen14** [comment]
Not sure if my issue is the same, but I see absolutely no output from `docker-compose run` on Jenkins.

**Comment by sambernet** [comment]
> 
> 
> Not sure if my issue is the same, but I see absolutely no output from `docker-compose run` on Jenkins.

Quite likely.

I just gave it a shot and tried removing my current workaround - to no avail. Behavior is still unchanged.

Tested with docker-compose v1.22.0, running on a current jenkins LTS 2.138.3 version versus a remote docker v18.09.00 daemon.
