### ISSUE TITLE
Bundle should support logging key

### ISSUE THREAD

**Issue by beverts312** [docker/compose#3734]
Bundle should support the `logging` key.
With bundles currently being the only way to leverage compose files (indirectly) with the new swarm mode, it is important that we can leverage settings configured under the `logging` key

```
docker-compose bundle
WARNING: Unsupported key 'logging' in services.app - ignoring
```

**Comment by beverts312** [comment]
This is dependent on [https://github.com/docker/docker/pull/24476](Docker PR24476)

**Comment by aanand** [comment]
I disagree. Bundles should only contain config which is portable across environments, and logging configuration definitely isn't.

**Comment by beverts312** [comment]
In what sense is logging configuration not portable across environments?

Additionally, if the logging key was not supported, there would be no way to leverage logging drivers and dab's, this would make dab's useless to a large number of people.

**Comment by aanand** [comment]
> In what sense is logging configuration not portable across environments?

In that the logging infrastructure in different environments can be wildly different, and a bundle should not be dependent on e.g. a particular logging driver or service being available.

> Additionally, if the logging key was not supported, there would be no way to leverage logging drivers and dab's, this would make dab's useless to a large number of people.

You can still set logging configuration on a service using `docker service update` (or, you _will_ be able to, once https://github.com/docker/docker/pull/24476 makes it into an RC).

Until there's a less fiddly way to manage it, this is how all non-portable config (e.g. port mapping, volume mounts) has to be specified on services created with `docker deploy`.

**Comment by beverts312** [comment]
> In that the logging infrastructure in different environments can be wildly different, and a bundle should not be dependent on e.g. a particular logging driver or service being available.

It is fair to say that is some people's use case, but I dont think it neccessarily applies to the majority.

> You can still set logging configuration on a service using docker service update (or, you will be able to, once docker/docker#24476 makes it into an RC).   

This is good to know, thanks

**Comment by aanand** [comment]
I would speculate that it's very normal for e.g. a syslog server to be set up in a team's production system, but not on their development laptops.

Regardless, a bundle should not contain any configuration that restricts the environments in which it can be deployed. Logging configuration definitely falls under that category, so it can't go into the bundle.
