### ISSUE TITLE
Bundle should support the volumes key

### ISSUE THREAD

**Issue by beverts312** [docker/compose#3735]
Bundle should support the `volumes` key (as `mounts`).
With bundles currently being the only way to leverage compose files (indirectly) with the new swarm mode, it is important that we can leverage settings configured under the `volumes` key.

```
docker-compose bundle
WARNING: Unsupported key 'volumes' in services.app - ignoring
```

**Comment by llonchj** [comment]
+1

**Comment by sylvainmouquet** [comment]
+1

**Comment by byrnedo** [comment]
Is there currently any way to use compose/bundle and swarm mode fully (with volumes) on 1.13? Any workaround?
