### ISSUE TITLE
please update the requirement on python-requests

### ISSUE THREAD

**Issue by jordimassaguerpla** [docker/compose#3740]
Hi,

docker-compose requires an old version of python-requests. This is a problem when using docker-compose on latest versions of linux distributions because they don't provide with such and old version.

http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=python-requests&searchon=names
https://packages.debian.org/search?keywords=python-requests
https://apps.fedoraproject.org/packages/python-requests
http://software.opensuse.org/package/python-requests

Would it be possible to update this requirement so that it can be used with python-request-2.10.0 ?

**Comment by aanand** [comment]
Yeah, we can give it a try. (Incidentally, the reason we keep the requests version tightly scoped is that minor releases have broken backwards compatibility in the past.)

You can always install using the Linux binary, though, which doesn't depend on any system Python interpreter or packages.

**Comment by tboerger** [comment]
> You can always install using the Linux binary, though, which doesn't depend on any system Python interpreter or packages.

That won't work if you have to properly package it as a Linux distribution ;)

**Comment by allardhoeve** [comment]
Hey there, any news on this?

**Comment by neilsh** [comment]
Looks like it was pending docker/docker-py#1242, which has since been merged

https://github.com/docker/compose/pull/4023#issuecomment-261357296

**Comment by dragetd** [comment]
If I understand the other issue correctly, an update had been merged.

Latest docker-compose is still packaged on gentoo with <requests-2.12 (according to the requirements https://github.com/docker/compose/blob/2506b725084bff559eb97267f964b1e621edc987/requirements.txt ). I have not tried forcing it to build with 2.12… is this problem still present or could the requirements.txt be updated / packaged with a more recent requests?

**Comment by shin-** [comment]
See my comment here: https://github.com/docker/compose/issues/4431#issuecomment-277846958

2.11.1 is the version we're comfortable supporting as the default right now.
