### ISSUE TITLE
Getting statically linked releases

### ISSUE THREAD

**Issue by np** [docker/compose#3741]
Would it be possible to make statically linked binaries for docker-compose. I've looked at some of the existing issues about this topic but couldn't get a definitive answer.

**Comment by dnephin** [comment]
According to https://github.com/pyinstaller/pyinstaller/wiki/FAQ it doesn't seem possible.

**Comment by sanmai-NL** [comment]
@dnephin. About the tags: from a question this turned out to become a feature request.

**Comment by nunofernandes** [comment]
+1

**Comment by ijc** [comment]
The FAQ Daniel pointed to still seems to be valid so I'm afraid this won't be possible.
