### ISSUE TITLE
 Docker 1.12 and Compose 1.8 - Mount not work 

### ISSUE THREAD

**Issue by RotemEmergi** [docker/compose#3742]
I am using Docker 1.12 and Compose 1.8. I am trying to understand how to mount the volumes for an image to global volumes.

The purpose is to use Docker services and Docker bundle for deploying clusters.

This is the error that I got :
WARNING: Unsupported top level key 'volumes' - ignoring

WARNING: Unsupported key 'volumes' in services.momgodb - ignoring

Best regarsd

**Comment by aanand** [comment]
Bundles don't yet support volume mounting - you'll have to do it manually after deploying, with `docker service update --mount`.

**Comment by CaptainHypertext** [comment]
@aanand  Elaborate for us lesser newbs?  I'm having this problem too.  None of the volumes in my dockerfile is getting picked up.

**Comment by aanand** [comment]
Say you're deploying a bundle with a mongodb service. Here's what you'd do:

1. Create a volume for mongodb.

        $ docker volume create mongo-data

2. Generate a bundle from your Compose app.

        $ docker-compose bundle
        Wrote bundle to myapp.dab

3. Deploy the bundle.

        $ docker deploy myapp
        Loading bundle from myapp.dab
        Creating network myapp_default
        Creating service myapp_mongodb
        Creating service myapp_web

4. Update the mongodb service to add a volume mount.

        $ docker service update myapp_mongodb --mount-add type=volume,source=mongo-data,target=/usr/local/mongodb/data

**Comment by homotopycolimit** [comment]
Does this not mean that we are changing the storage *after* the service has already started?

**Comment by drajen** [comment]
Do we have a sense for when volumes will be part of bundling dab files? I'm having difficulties managing change control in this post-deployment workaround.

**Comment by byrnedo** [comment]
Any word when mount will be part of compose files?

**Comment by coodoo** [comment]
bump!

**Comment by shin-** [comment]
Compose v3 files, which replace the DAB files, support those options. I'll close this issue as a result.
