### ISSUE TITLE
networking behaviour of compose changed in latest update

### ISSUE THREAD

**Issue by jatins** [docker/compose#3745]
I am using Docker for Mac beta.
Let's say my compose.yml file has two services `frontend`, and `backend`.

Previously, with `docker-compose up` the services could **not** talk to each other over `localhost`. You had to use service name. So, in my frontend code I would make a call to `http://backend:3000` 

Seems like with the latest update, the I have to make a call to `http://localhost:3000` to accomplish the same behaviour.

Although, when I try to access `backend` service from _inside_ the `frontend` container, I have to use the service name (i.e. "backend"), and not localhost.

Is this the expected behaviour?

**Comment by jatins** [comment]
**docker version**
```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**docker-compose version**
```
docker-compose version 1.8.0-rc2, build c72c966
docker-py version: 1.9.0-rc2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

**Comment by jatins** [comment]
So, in some places I have to use service name as defined in `docker-compose.yml` file, and in other I have to use `localhost`.

I am not sure what's the exact behaviour here.

**Comment by aanand** [comment]
You should always use the service name. In what context are you finding that you have to use localhost?

**Comment by jatins** [comment]
@aanand So, I have two services defined `frontend` and `backend`. Something like this:
```
version: "2"
services:
  frontend:
    image: <image-name>
    ports:
      - "8080:8080"
  backend:
    image: <image-name>
    ports:
      - "3000:3000"
```

Then in my `frontend` service, which I access in browser at `localhost:8080`, I have to use `localhost:3000` when interacting with backend service, instead of `backend:3000`

**Comment by aanand** [comment]
What happens when you try and connect to `backend`? e.g. what's the output of `docker-compose exec frontend ping backend`?

**Comment by jatins** [comment]
@aanand It gives the expected output. So, I ran `docker-compose exec frontend curl backend:3000/ping` and I get back the expected output from `/ping` .

While calling the backend service from browser, however, I have to use localhost.

**Comment by aanand** [comment]
> While calling the backend service from browser, however, I have to use localhost.

OK, that's correct behaviour.

Accessing services from your host machine is different than accessing them from other services. This has been the case ever since Compose started using networks (before that, it was more complicated).

With Docker Toolbox, the VirtualBox VM had an IP address which you had to use in your browser (so you'd access your backend service via `x.x.x.x:3000`). With Docker for Mac, ports are now published to your Mac's network interface (so you go to `localhost:3000` instead).
