### ISSUE TITLE
Option to "lock" certain subcommands (like "down") in production environments

### ISSUE THREAD

**Issue by dsifford** [docker/compose#3746]
Hi there. 

I vaguely recall reading that this is possible somewhere, but I can't seem to find it now that I'm looking for it again.

The gist is: How do I prevent myself and others on my team from accidentally running `docker-compose down`? We use a cloud provider with Docker Machine and it's not uncommon for any of us to simply forget we're still connected to our production machine.

Thanks in advance. 👍

**Comment by ArtistsTechGuy** [comment]
I am looking for this too for the same reasons.

**Comment by ijc** [comment]
I don't believe there is any such functionality in compose today. You could implement this locally by ensuring that a local `/usr/local/bin/docker-compose` wrapper script to do sanity check (e.g. a molly-guard style "enter the name of the computer you think you are talking to" prompt) came first in `$PATH` I suppose.
