### ISSUE TITLE
Docker-Compose on redhet7 

### ISSUE THREAD

**Issue by RotemEmergi** [docker/compose#3759]
Hello ,

I have  installed docker on red het 7 and it's succeeded.
I tried to install the compose with this command: +1: 
curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

When I run the command 
docker-compose --version

And got :+1: 
bash: docker-compose: command not found

How can I fix it?

**Comment by johnharris85** [comment]
Were there any errors when you ran the script? Is `docker-compose` in your /usr/local/bin folder?

**Comment by Laxman-SM** [comment]
@RotemEmergi, you docker-compose command not executed properly that why you getting that error. try to execute command manually.
docker@flockerm:$  sudo curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` >  /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0    423      0 --:--:--  0:00:01 --:--:--   423
100 7776k  100 7776k    0     0  94840      0  0:01:23  0:01:23 --:--:-- 91334
 
after download of compose binary docker-compose --version will work fine.

**Comment by RotemEmergi** [comment]
thanks you can close
