### ISSUE TITLE
Add 'sysctl' option support

### ISSUE THREAD

**Issue by jtakkala** [docker/compose#3765]
PR https://github.com/docker/docker/pull/19265 merged 'sysctl' support into docker, but there seems to be no way to use this feature with docker-compose. Has anyone started work on such a feature? If not, I will attempt to patch docker-compose and create a PR. Are there any suggestions on how to implement it? I was thinking of starting with something similar to how the environment or cap_add options work.

**Comment by NoamB** [comment]
+1

**Comment by jtakkala** [comment]
I've submitted a PR for this to docker-py in docker/docker-py#1145. I have a patch in my tree at 87ea3c40f71c4b87e2292244a276a53765f484e6. Will submit my patch here once docker-py support is accepted.

**Comment by ebr** [comment]
+1

**Comment by alexandrebini** [comment]
+1

**Comment by timgriffiths** [comment]
+1

**Comment by Christian-Schmid** [comment]
+1

**Comment by vingrad** [comment]
+1

**Comment by bmicha4** [comment]
+1

**Comment by gonsfx** [comment]
Anything happening here?

**Comment by jtakkala** [comment]
#3798 closes this. docker-py version 1.10.0 added support for sysctls, so I hope we can get this merged soon.

**Comment by yingdi11** [comment]
I followed instruction https://docs.docker.com/compose/gettingstarted/ . but it does not work ......

Has anyone got the instruction working?

**Comment by Hronom** [comment]
Guys any progress? Need this feature to run latest version of Elasticsearch from docker-compose...

**Comment by GuillaumeMartial** [comment]
+1

**Comment by jonathas** [comment]
Also waiting for this to make our lives easier :)

**Comment by Aimsam** [comment]
+1

**Comment by lambrojos** [comment]
+1

**Comment by Hronom** [comment]
Guys sorry for annoying, when it becomes available in release?

**Comment by AnatolyRugalev** [comment]
FYI

There is `sysctls` option starting from docker-compose 2.1

**Comment by agiUnderground** [comment]
Docker-compose 3.0+ support this feature (sysctls)?

**Comment by AnatolyRugalev** [comment]
@agiUnderground, yes

**Comment by agiUnderground** [comment]
@AnatolyRugalev can you give me a link or some example please? I trying to start redis as docker service in docker stack and i wanna change /proc/sys/net/core/somaxconn option.

**Comment by marzlarz** [comment]
+1

**Comment by farwish** [comment]
How to fix error below.

Error Message:
```
ubuntu@VM-0-10-ubuntu:~/dk$ docker-compose up redis
Starting redis-con ... error

ERROR: for redis-con  Cannot start service redis: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"open /proc/sys/net/core/somaxcomm: no such file or directory\"": unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"open /proc/sys/net/core/somaxcomm: no such file or directory\"": unknown
ERROR: Encountered errors while bringing up the project.
```

docker-compose.yml:
```
version: '3'
services:
  redis:
    image: redis:3.2.12
    container_name: redis-con
    privileged: true
    sysctls:
      net.core.somaxcomm: '511'
```

**Comment by realyukii** [comment]
nvm, foudn it on https://docs.docker.com/reference/compose-file/services/
