### ISSUE TITLE
Running docker-compose with invalid argument exits with 0

### ISSUE THREAD

**Issue by cyrusmg** [docker/compose#3766]
```
$ docker-compose -v
docker-compose version 1.7.0, build 0d7bf73
$ docker-compose build -no-cache
Build or rebuild services.

Services are built once and then tagged as `project_service`,
e.g. `composetest_db`. If you change a service's `Dockerfile` or the
contents of its build directory, you can run `docker-compose build` to rebuild it.

Usage: build [options] [SERVICE...]

Options:
    --force-rm  Always remove intermediate containers.
    --no-cache  Do not use cache when building the image.
    --pull      Always attempt to pull a newer version of the image.
$ echo $?
0
```

See last line - the return value should be non-zero as the current state does not work correctly with `set -e`.

PS: I am sorry if this is fixed in newer version, I can't test it now.

**Comment by aanand** [comment]
This is a bug, but not the one it looks like.

We do actually exit with code 1 in almost all cases of unparseable options. However, _sometimes_, when you pass an option with a single dash instead of two, it results in an incorrect parse.

Here `-no-cache` is being parsed as `-n -o -c -a -c -h -e`, and the `-h` is causing the help text to be printed.

**Comment by ijc** [comment]
I agree the behaviour is surprising but I don't think compose is unusual in behaving this way in general.

$ ls -nocach ; echo $?
total 60M
drwxrwxr-x 20 1000  32K May 21 16:09 ./
drwxrwxr-x  7 1000 4.0K Mar 26 15:08 ../
[...snip...]
0
```

(it happens that `-e` on ls requires an argument:
```
$ ls -nocache ; echo $?
ls: invalid option -- 'e'
Try 'ls --help' for more information.
2
```
but I think this illustrates the general point)
