### ISSUE TITLE
No auth config found

### ISSUE THREAD

**Issue by benjyz** [docker/compose#3767]
In a docker machine, docker compose up has some auth config error, but its unclear what this error exactly is. Would nice to know which file this is looking for e.g.

```
$ docker-compose --verbose -p webapp up 
compose.config.config.find: Using configuration files: ./docker-compose.yml
```

```
docker.api.build._set_auth_headers: Looking for auth config
docker.api.build._set_auth_headers: No auth config in memory - loading from filesystem
docker.auth.auth.load_config: File doesn't exist
docker.api.build._set_auth_headers: No auth config found
```

**Comment by aanand** [comment]
That's not really an error, just a debug message. Are you encountering an authentication issue?

(The default location for auth config is `~/.docker/config.json`, by the way.)

**Comment by Swetad90** [comment]
I got the same error. And my SSL verification is failing.
Even if I have config.json under C:\Users\user\.docker\machine\machines\office and that already has all the cert paths set.
But docker compose is not taking the file. Any idea which certs is it referring here?


$ docker-compose --verbose up
compose.config.config.find: Using configuration files: .\docker-compose.yml
docker.auth.find_config_file: Trying paths: ['C:\\Users\\user\\.docker\\config.json', 'C:\\Users\\user\\.dockercfg']
docker.auth.find_config_file: No config file found
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 88, in main
  File "compose\cli\main.py", line 137, in perform_command
  File "compose\cli\command.py", line 36, in project_from_options
  File "compose\cli\command.py", line 111, in get_project
  File "compose\cli\command.py", line 86, in get_client
  File "site-packages\docker\api\daemon.py", line 159, in version
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\api\client.py", line 179, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 497, in send
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
Failed to execute script docker-compose

**Comment by bjholmes23** [comment]
I had a similar error. Turned out i had some very large files in the docker-compose directory, not being included in the build or as volumes, but for some reason were causing it to hang. Once I removed the big files from the directory I was good to go.

**Comment by bldrvnlw** [comment]
@Swetad90 Are you sure that your user is in the docker group?  I had the same issue when I forgot to 'adduser <myuser> docker'

**Comment by campreb** [comment]
@bjholmes23 I had the exact same problem, fixed it with `.dockerignore` file 👍

**Comment by zipzit** [comment]
I had this issue on a vultr deployment.  The fix was to add my login id as a superuser
$ `su - username`  Note: root login access was removed per security recommendations.

**Comment by bobsaget4lyfe** [comment]
I had this issue and it was resolved by reseting docker (turning it off and on again eh?)

Just open a terminal and enter this:

`sudo service docker stop`

Then just `docker-compose like usually`

* I am commenting as this is the top google result for my error.

**Comment by robertpro** [comment]
> (The default location for auth config is `~/.docker/config.json`, by the way.)

How can I tell docker-compose to use a different location for this file?

I am using `docker --config .docker` inside my project, so docker-compose pull can't find authentication for the registry :(

**Comment by robertpro** [comment]
I fixed the issue by using `DOCKER_CONFIG` env var :)

`DOCKER_CONFIG=.docker`

**Comment by parasjain1** [comment]
I had a similar issue. Removing existing docker installation under all package names such as docker.io, docker, docker-engine and then reinstalling via apt-get docker.io solved it for me. I encountered a snap installation too, removed that one too.

In case anyone finds these helpful.

Removing existing installations
`sudo apt-get remove docker docker-engine docker.io && apt-get purge docker docker-engine docker.io
snap remove docker
`

Installing
`sudo apt-get install docker.io`
