### ISSUE TITLE
Option to suppress progress

### ISSUE THREAD

**Issue by elliotchance** [docker/compose#3770]
There should be an option that still shows the build steps, but not the actual progress bars which spray a huge amount of output on CI servers since the docker commands expect that your using a terminal that has the control codes to write over previous lines.

**Comment by ludofleury** [comment]
Agree, very annoying in CI env for example :)

**Comment by markvl** [comment]
+1 

I've got the same request, but in my case for the "pull" command. I don't care about the progress bar in my logs, but I do want to see what was pulled exactly.

**Comment by ceesvanegmond** [comment]
@ludofleury Exactly, really like to not see al that output there

**Comment by tocsa** [comment]
any progress on this?
maybe log level also:
-all
-warn
-error
-none

**Comment by memory** [comment]
This actually seems somewhat similar to https://github.com/docker/compose/issues/363 -- "compose build" should support every applicable option that "docker build" supports, including passing along `--quiet`

**Comment by perlun** [comment]
In case anyone finds this wanting to suppress the progress bar when pulling images on `docker compose up`, `docker compose up --quiet-pull` is the parameter you might be looking for. :+1: Tested on Docker 23.0.6.

**Comment by ro0NL** [comment]
ideally docker compose doesnt clutter like this in CI

![image](https://github.com/user-attachments/assets/c61efa89-c73a-440a-b8d9-4e98b34d13c6)

![image](https://github.com/user-attachments/assets/897536c2-13b5-4a74-9e3d-29862d70ccdb)
