### ISSUE TITLE
docker-compose up with options are printing the version when the version option is not specified

### ISSUE THREAD

**Issue by 5f6b3fb8** [docker/compose#3781]
docker-compose version 1.8.0, build f3628c7
RHEL 7.2

I'm trying to run docker-compose to bring up a couple of services, and docker-compose prints the version and then exits. Here's my command line being executed:

`docker-compose --host tcp://192.168.47.189:2376 -tlsverify -tlscacert /jenkins_slave/workspace/sonar/5.6-release@tmp/secretFiles/c6b0ddbc-998a-436f-bd01-85e5c2095298/ca.pem -tlskey /jenkins_slave/workspace/sonar/5.6-release@tmp/secretFiles/87bbe5b3-8843-4b9f-9c6b-a128ca50a678/key.pem -tlscert /jenkins_slave/workspace/sonar/5.6-release@tmp/secretFiles/a76521ac-cadf-4380-8c75-70ebd6b66fa9/cert.pem up -d
`

The result of the command
`docker-compose version 1.8.0, build f3628c7`

I'm following the docs [here ](https://docs.docker.com/compose/reference/overview/) and I don't see a single -v or --version in the command line.

**Comment by aanand** [comment]
Looks like a bug with option parsing. You're passing the TLS args incorrectly (one dash instead of two) and so it's parsing `-tlsverify` as `-t -l -s -v -e -r -i -f -y`.

```console
$ docker-compose -tlsverify
docker-compose version 1.8.0-rc2, build c72c966
```

It should be complaining about the unrecognised flags, but instead all it sees is the `v`.

**Comment by 5f6b3fb8** [comment]
Ah ok. Thanks for that explanation, that makes a lot of sense. I got so hung up on the fact that compose was not complaining about my options and just printing the version, that I didn't even consider the dashes.
