### ISSUE TITLE
compose 1.8.2. TypeError: log_timeout_error() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by gggeek** [docker/compose#3783]
I have a set of containers where the mysql one has a 'weird' shell script as entrypoint.
I can start mysql after starting the container via 'docker exec ... /etc/init.d/mysql start', but when I do so, the command line hangs (I can ctrl+c to exit the docker command, and the mysql service does indeed run).

I just updated to docker 1.12 and docker-compose 1.8.0, and it seems that now handling of the 'rogue' container is getting worse: after executing the above steps, I tried 'docker-compose ps' and I get:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose/cli/errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1
```

the same happens if I run `docker-compose kill -s SIGKILL`

**Comment by aanand** [comment]
Thanks for reporting. I've confirmed that we've got a bug in the code that handles timeouts - the fix is in https://github.com/docker/compose/pull/3784.

As for your timeout problem, it certainly sounds like you've got a weird script. I'd recommend making it so that it execs out to the mysqld process after performing whatever setup is necessary.

**Comment by vikas8** [comment]
i too face same issue 
<snip>
apporbit-chef       | ==> /var/log/chef-server/erchef/erchef.log <==
apporbit-chef       | 2016-08-24 09:15:35.582 [info] Application pooler started on node 'erchef@127.0.0.1'
apporbit-chef       | 2016-08-24 09:15:35.582 [info] Application sqerl started on node 'erchef@127.0.0.1'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose/cli/errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1
</snip>

also how to pass -h / hostname to docker-compose

**Comment by fgirardey** [comment]
I noticed that i have the exact same error when i use `docker-compose logs -f mycontainer` when it is configured with the `tty: true` in the `docker-compose.yml` file. It happens after a few minutes.
When i don't use `tty: true` i don't get this error.

```
$ docker -v
Docker version 1.12.1, build 6f9534c

$ docker-compose version
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

**Comment by gvilarino** [comment]
Same here, and not using `tty: true` anywhere; just a plain old `node.js` app with one very large layer (deps).

**Comment by WillGibson** [comment]
Also experiencing the same issue when something times out...

```
➜ docker -v
Docker version 1.12.1, build 6f9534c, experimental
➜ docker-compose version 
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

I'm using the Mac app if that makes any difference.

**Comment by soundsgoodsofar** [comment]
Seeing the same thing as OP

$ docker -v
Docker version 1.12.1, build 6f9534c
$ docker-compose version
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2h  3 May 2016

**Comment by caneraydinbey** [comment]
`Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose/cli/errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1
vegan@vegan:~/hb-productupload/docker/dev$ docker -v
Docker version 1.12.5, build 7392c3b
vegan@vegan:~/hb-productupload/docker/dev$ docker-compose version
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
vegan@vegan:~/hb-productupload/docker/dev$ `

**Comment by aug-riedinger** [comment]
The issue just occured to me. Using:
```
▶ docker-compose --version
docker-compose version 1.8.0, build f3628c7
▶ docker --version        
Docker version 1.12.3, build 6b644ec
```
