### ISSUE TITLE
Print helpful message when passing invalid options/args

### ISSUE THREAD

**Issue by 5f6b3fb8** [docker/compose#3785]
I recently opened issue #3781 which ended up being my own mistake. I think my mistake would be easier to identify if a helpful message was printed, calling out the unrecognized option.

Repro:
docker-compose -tv

Expected:
Unrecognized option '-t'
--Help Text--

Actual:
--Version String--

**Comment by optimisticanshul** [comment]
@aanand Here we need something like this https://github.com/docopt/docopt/blob/master/examples/validation_example.py for docopt to verfiy this https://github.com/docker/compose/blob/master/compose/cli/docopt_command.py#L12 or any other way to do ? I can implement it if it's the way to do it.

**Comment by aanand** [comment]
I don't think we need anything as heavyweight as a schema validation library. It looks to me like a docopt bug. Unfortunately, docopt hasn't been updated in a long time (though we are a patch version behind), so I don't know offhand if they've fixed it - but that would be where to look first.

**Comment by optimisticanshul** [comment]
@aanand I will have a look whether in it's latest version it's fixed or not and update it here. Btw any other suggestions if it's not fixed in latest release of docopt.

**Comment by aanand** [comment]
We can't easily fix it outside of docopt, so a fix will need to be submitted.

**Comment by optimisticanshul** [comment]
I looked into it it's easy to do it but i am not sure docopt will allow or not. This https://github.com/docopt/docopt/blob/master/docopt.py#L569
```
argv = parse_argv(Tokens(argv), list(options), options_first)
```
This contains list of all the parameters passed in following format
```
Option(o.short, o.long, o.argcount)
```
In argv for input like -tlsverify output will be like
```
[Option('-t', None, 0, True), Option('-l', None, 0, True), Option('-s', None, 0, True), Option('-v', u'--version', 0, True), Option('-e', None, 0, True), Option('-r', None, 0, True), Option('-i', None, 0, True), Option('-f', u'--file', 1, 'y')]
```
So we can iterate and check if long is None than it's not a valid option but it may break things if long is not provided.

**Comment by aanand** [comment]
Probably best to open an issue on the docopt repository with your findings, and provide a failing case that doesn't involve Compose at all.
