### ISSUE TITLE
Add environment variables to aggregate service containers

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#38]
E.g. an environment variable for all redis hosts, comma separated.

**Comment by dnephin** [comment]
Not sure what this is about, @bfirsh got more context, or should we close this?

**Comment by bfirsh** [comment]
The idea was that if you scaled up a host, you'd get an environment variable with something like `REDIS_HOSTS=10.0.0.1,10.0.0.2,10.0.0.3`. I think this is probably a bit ancient though, and we can come up with better ways of doing this in context of new networking etc.
