### ISSUE TITLE
Docker for Mac - docker-compose not setting compose env 

### ISSUE THREAD

**Issue by blacktop** [docker/compose#3803]
I am expecting to see https://docs.docker.com/v1.8/compose/env/ when I link two containers together, but they are not getting set in gliderlabs/alpine images, but if I do it manually with docker-engine it does get set?

**Comment by aanand** [comment]
That documentation is for an old version of Compose. It's confusing, but the `v1.8` in the URL refers to the version of the whole Docker platform (which is the same as the Engine version), not the version of Compose.

As noted in the [current version of that page](https://docs.docker.com/compose/link-env-deprecated/), you will only see link environment variables if you're using a v1 Compose file.
