### ISSUE TITLE
[Ubuntu/Debian] Provide `docker-compose` as deb-package, please.

### ISSUE THREAD

**Issue by sprd-bena** [docker/compose#3810]
Hi *,

Is there a reason why `docker-compose` is not provided as a deb-package via `apt.dockerproject.org`?

My request is that `docker-compose` is provided as a deb-package with its version and dependency. There are many good reasons do so (, and personally I do not consider `pip` as an alternative for deployments in development nor even production). Currently I package it myself with [`fpm`](https://github.com/jordansissel/fpm/), but it would be nice to have it directly from upstream, without the need of various scripts I have to trigger manually or even write a rss-parser just to get a new version of it... You have the infrastructure, so why do you not use it?

Thanks.

**Comment by jrabbit** [comment]
dupe of #2235

**Comment by josegonzalez** [comment]
*bump* this can probably be closed :)
