### ISSUE TITLE
compose may create two networks with the same name

### ISSUE THREAD

**Issue by furiousOyster** [docker/compose#3822]
I am not sure how to make this happen, but on my machine, I observe that somehow, "docker-compose up" had made two networks of exactly the same name.

Now when I try to build containers, and specify the compose network name, it randomly picks between the two.  This sounds simple but took a while to notice.

I think that compose should either refuse to create a network with the same name, or should remove the old network before making the new one.

**Comment by shin-** [comment]
#5271
