### ISSUE TITLE
Please make `docker-compose exec` an alias to `docker-compose run`

### ISSUE THREAD

**Issue by netbrain** [docker/compose#3824]
Because it's driving me crazy!

**Comment by vdemeester** [comment]
Those 2 commands do not the same functionnality though.. 

What drives you crazy about those ?

**Comment by netbrain** [comment]
```
$ docker-compose exec
No such command: exec
```

Are you telling me docker-compose exec now exists? (maybe i should update..)

**Comment by vdemeester** [comment]
@netbrain yes : https://docs.docker.com/compose/reference/exec/
