### ISSUE TITLE
Running integration tests fail on Docker For Mac

### ISSUE THREAD

**Issue by dave-tucker** [docker/compose#3831]
Only one test fails:

https://github.com/docker/compose/blob/28120148f4e1380096407626f846eda8f6970f36/tests/unit/cli/errors_test.py#L35

This is probably a side effect of #3689

**Comment by dave-tucker** [comment]
Ignore me, it's nothing to do with 3689, but it still fails for me...

**Comment by aanand** [comment]
Fixed in https://github.com/docker/compose/pull/3943
