### ISSUE TITLE
docker-compose: command not found

### ISSUE THREAD

**Issue by MichaelLSmith** [docker/compose#3832]
I have docker installed and have run containers build from images using full-length commands. But after writing a docker-compose.yml file, the docker-compose command is not found in my terminal. What should I trouble shoot?

**Comment by dattran-vn01** [comment]
Did you install docker-compose ? 
https://docs.docker.com/compose/install/

**Comment by MichaelLSmith** [comment]
That was the problem. So simple. I thought I had installed it.
