### ISSUE TITLE
Avoid cluttering the root directory

### ISSUE THREAD

**Issue by greg0ire** [docker/compose#3847]
I'm using compose on a new project, and instead of using it only in development, we also want to use it in production now.

I ended up with : 

- `docker-compose.yml`
- `docker-compose.override.yml` (for development)
- `docker-compose.prod.yml` (for production)
- `Dockerfile.dev`
- `Dockerfile.prod`

My reviewer (@Arnch) asked if I could put these file in a `docker` directory, because docker related files are starting to clutter the root directory (I also have a `Dockerfile`, and might have env files in the future). Now I could cd into this directory before running any `docker`, or use `-f` options, but I feel this could be made a bit handier.

What if after looking for files in the root directory, docker-compose looked in another directory, named `docker` or `docker-compose`, or even `docker/compose`?

**Comment by chris13524** [comment]
You can specify the `-f <docker-compose-file.yml>` argument, maybe you could make an alias?

**Comment by greg0ire** [comment]
At the moment I'm using an alias to make things easier, it's a good workaround, but it means I have to get my team to set it up too, and docker is here to reduce this kind of manual setup, right?

**Comment by greg0ire** [comment]
I needed to override some things in development (install make), and in production (copy the code inside the image instead of mounting it), so now I have one dockerfile for dev and one for production. I am also going to add an entrypoint that will `usermod www-data` to give it my local uid and gid so that I can develop without any permissions problem. That's 6 files. I think there should be an improved support for a separate `docker` directory

**Comment by greg0ire** [comment]
Ok so it seems that all this can be solved with a nice `.env` : 

```
COMPOSE_PROJECT_NAME=dashboard
COMPOSE_FILE=docker/docker-compose.yml:docker/docker-compose.override.yml
```

Closing.
