### ISSUE TITLE
docker-compose .env file not support dynamic values

### ISSUE THREAD

**Issue by nevergone** [docker/compose#3849]
It's work:
CURRENT_UID=1000

It's not work:
(other command result)
CURRENT_UID=$(id -u)

(previous defined environment variable)
CURRENT_UID=$UID

**Comment by ilinum** [comment]
I would be interested in tackling this issue :)
Is this something that would be useful?

**Comment by adiabuk** [comment]
Has there been any progress with this?  I would definitely find it useful

**Comment by dmitry** [comment]
As I know it's still not possible in the latest compose versions.

**Comment by SvenDowideit** [comment]
I'm interested in this for use with vault - but at some point, this would mean it needs to be able to have an interactive "enter username and password"

**Comment by ulyssessouza** [comment]
Hmmm... The idea of executing things coming from a default hidden file is quite scary.
This is how it looks like in my mind:

```.env
NO_GO=$(rm -rf ~)
```
