### ISSUE TITLE
When using multiple docker-compose.yml files from different directories, local paths are not followed correctly.

### ISSUE THREAD

**Issue by brocoli** [docker/compose#3874]
Consider the following command, working from `~/myproj/`:

`docker-compose -f docker-compose.yml -f somesubmodule/docker-compose.yml up`

Suppose `somesubmodule/docker-compose.yml` contains the following

```
services:
  myservice:
    build:
      context: ./myservice
```

`docker-compose up` fails because it will try to build `myservice` from `~/myproj/myservice/docker-compose.yml` instead of `~/myproj/myservice/somesubmodule/docker-compose.yml`.

The error message is something like: `ERROR: build path ~/myproj/myservice/ either does not exist, is not accessible, or is not a valid URL.`

This happened with docker-compose version 1.8.0-rc1, build 9bf6bc6, installed from Homebrew on my Mac OS X Yosemite version 10.10.5

Note that simply running `docker-compose -f somesubmodule/docker-compose.yml up` works fine, it's probably a glitch due to merging yml files and losing locality. Relative paths should be expanded before merging instead.

**Comment by lhm** [comment]
I'm having the same problem. It makes pulling together the docker-compose configs from multiple projects somewhat difficult. It appears as if only the first context is being used when combining multiple files:

```
$ pwd
/tmp/dc

$ tree
.
├── p1
│   ├── Dockerfile
│   └── docker-compose.yml
└── p2
    ├── Dockerfile
    └── docker-compose.yml

2 directories, 4 files

$ cat p1/docker-compose.yml 
version: '2'
services:
  p1:
    build:
      context: .
    command: echo 'hello from p1'

$ cat p2/docker-compose.yml 
version: '2'
services:
  p2:
    build:
      context: .
    command: echo 'hello from p2'

$ docker-compose -f p1/docker-compose.yml -f p2/docker-compose.yml config
networks: {}
services:
  p1:
    build:
      context: /private/tmp/dc/p1
    command: echo 'hello from p1'
  p2:
    build:
      context: /private/tmp/dc/p1
    command: echo 'hello from p2'
version: '2.0'
volumes: {}

$ docker-compose -v
docker-compose version 1.10.0, build 4bd6f1a
```

In the example above I'd expect that the build context of p2 be `/private/tmp/dc/p2`

I made a repo for it here: https://github.com/lhm/docker-compose-contexts-issue

**Comment by MrHash** [comment]
Is there any workaround for this problem?

**Comment by dpnova** [comment]
FWIW I have created an empty compose config at the root of my project:
```
version: "3"
```
Then make sure it's included all the time:

`docker-compose -f ./docker-compose.yml -f ./somewhereelse/docker-compose.yml -f ./1/2/3/docker-compose.yml up`

In doing this, you then use the same relative path for volumes and context in all the other compose configs through the project.

I'm going to create a command line wrapper for my team so they don't have to think about it too much.

**Comment by bgiorgini** [comment]
It didn't work for me adding the emtpy docker-compose.yml file in the root. Still the other 2 compose files get mixed up with the paths, taking the first relative path for all the other images to build.
Anyone else found another solution for this?

With the same sample files I got this:
```➜  /tmp docker-compose -f docker-compose.yml -f ./p1/docker-compose.yml -f ./p2/docker-compose.yml config
services:
  p1:
    build:
      context: /private/tmp/p1
    command: echo 'hello from p1'
  p2:
    build:
      context: /private/tmp/p1
    command: echo 'hello from p2'
version: '2.0'

➜  /tmp docker-compose version
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
➜  /tmp docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: true```

**Comment by joeyhub** [comment]
I think there is a lot of confusion here with people wanting different things.

I want the behaviour described in the original ticket which should be possible to fix with a stub docker-compose file. I have lots of compose files in subdirectory where I want the path to always be treated as from the root path for the project directory. There are limits on volume (not supporting relative) and I have some limits on symlink usage.

However with version 2 at least this doesn't appear to work (docker-compose.yml in base directory). It seems that the path is now enforced as being relative to the specific file loaded at least for build paths.

This is something where it would be great to give the user more control. It's currently inconsistent and hard to find appropriate documentation on.

For example with version 2, including a base configuration works for setting a new base path for extends.file but not for build.context. Except on investigation it turns out that it is working except that extends doesn't take the path from the first configuration file used.

I'm really pulling my hair out with this because it does all kinds of strange things automatically taking control over the user rather than giving the user control and visibility. It's not only this but things like not being able to extend VOLUME in the Dockerfiles and finding myself doing things like putting in dummy services just to build and tag an image. I find myself working around these tools more than working with them.

At least with extends gone I suppose that inconsistency is not an issue any more, however it would be nice to be able to specify the base directory rather via argument rather than having a dummy file for it.

**Comment by fabriziocucci** [comment]
I've found [this](https://docs.docker.com/compose/extends/#understanding-multiple-compose-files) link particularly clear when it comes to using multiple compose files.

I'm not sure whether the page has been published recently or whether the behavior described matches the current implementation but it _kind of_ makes sense.

Specifically:

> Understanding multiple Compose files
> ...
> When you use multiple configuration files, you must make sure all paths in the files are relative to the base Compose file (the first Compose file specified with -f). This is required because override files need not be valid Compose files. Override files can contain small fragments of configuration. Tracking which fragment of a service is relative to which path is difficult and confusing, so to keep paths easier to understand, all paths must be defined relative to the base file.

Although, I don't particularly agree that this should be _the only way_ of handling relative paths and I can try to elaborate a little bit more by providing a simple example.

Suppose you have the following:
```
my-project
|
|----> service-a (git submodule)
|          |
|          -----> docker-compose.yml
|
|----> service-b (git submodule)
|          |
|          -----> docker-compose.yml
|
 -----> docker-compose.yml
```
where:
1. `service-a` requires MongoDB to be stand up by itself, so its `docker-compose.yaml` should be a valid compose file, i.e. I should be able to `cd service-a && docker-compose up`, so paths should be relative to the `service-a` folder;
2. `service-b` requires Neo4j to be stand up by itself, so its `docker-compose.yaml` should be a valid compose file, i.e. I should be able to `cd service-b && docker-compose up`, so paths should be relative to the `service-b` folder;
3. the `docker-compose.yml` in `my-project` adds other services that should be used in combination with the docker compose files of `service-a` and `service-b`, i.e. I should be able to `cd my-project && docker-compose -f docker-compose.yml -f service-a/docker-compose.yml -f service-b/docker-compose.yml up`. In order for this to work, paths in the `docker-compose.yml` of `service-a` and `service-b` should be relative to `my-project`.

So it appears that you need to either settle for 1 and 2 **or** 3, but not all of them (unless you introduce some duplication of course).

Is there a "nice" workaround to handle this scenario?

**Comment by dpnova** [comment]
You need to keep in mind that when you do a `build` compose sends stuff to the docker daemon, it's then outside of the context of compose. You should run compose with the verbose flag to see what the paths in your `build` section are being translated to when being sent to the docker daemon.

**Comment by gucki** [comment]
I just encountered the same problem. Why not introduce some prefixes with special meanings?

    ./bla -> uses ./bla relative to the current docker-compose.yml
    !/bla -> uses ./bla relative to the current first docker-compose.yml
    ~/bla -> uses ./bla relative to the project folder

**Comment by ZimbiX** [comment]
I ended up creating a `docker-compose-wrapper` that loads the `docker-compose.yml` files, using `sed` to make the context paths absolute.

This currently creates temporary files in `dc/`, but I'm wondering if I can use the `-f -` option to provide the files via STDIN using YAML's `---` to separate the files.

```bash
#!/bin/bash

set -e

current_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$current_dir"

# docker-compose doesn't support preserving a compose file's relative context when you include it from another directory
# Workaround this by creating copies of the compose files with their contexts made absolute, and prepare the argument list of these files
docker_compose_files=(
  "$GOPATH/src/github.com/greensync/dex-services/docker-compose.yml"
  "$PROJECTS/dex-docs/docker-compose.yml"
  "$PROJECTS/dex-demo-ui/docker-compose.yml"
  "../docker-compose.yml"
)
docker_compose_command_args=(-p dex)
mkdir -p dc
rm -f dc/*
for i in "${!docker_compose_files[@]}"; do
  compose_file="${docker_compose_files[$i]}"
  compose_file_dir="$(dirname "$(readlink -f "$compose_file")")"
  sed "s|  context: |  context: $compose_file_dir/|g" "$compose_file" > "dc/${i}.yml"
  docker_compose_command_args+=(-f "dc/${i}.yml")
done

# Run the given docker-compose command, inserting the argument list of our modified compose files
set -x
docker-compose "${docker_compose_command_args[@]}" "$@"
```

You can see the resulting config using:

```bash
./docker-compose-wrapper config
```

**Comment by joeyhub** [comment]
ZimbiX, docker compose I believe just wraps docker and some of those strings in the configuration will go all the way down through to the shell command.

That means that for volume you might be able to get away with something like:

    volume:  "${STANDARD_ENVVAR}/path:/container/mountpoint"

**Comment by ferrastas** [comment]
Having a project with multiple services 
```
my-project
|
|----> service-a
|          |
|          -----> docker-compose.yml
|
|----> service-b
|          |
|          -----> docker-compose.yml
```
Modify the corresponding `docker-compose.yml` file replacing relative paths with an environmnent variable + default value something like `${SERVICE_A:-.}` and `${SERVICE_B:-.}` then in the root path an `.env` file with:
````
SERVICE_A=../service-a
SERVICE_B=../service-b
````
And voilá, starting containers from root path will read the `.env` file and will replace it on-the-fly.
````
$ docker-compose -f service-a/docker-compose.yml -f service-b/docker-compose.yml config
services:
  service-a:
    image: foo/bar
    volumes:
    - /Users/ferranvidal/dev/sandbox/service-a:/code:rw
  service-b:
    image: foo/bar
    volumes:
    - /Users/ferranvidal/dev/sandbox/service-b:/code:rw
version: '3.0'
````

**Comment by captain-kark** [comment]
@GregYeo I was able to get around the temporary files with this:

```
docker-compose -f submodules/A_SUB_PROJECT/docker-compose.yml docker-compose -f submodules/B_SUB_PROJECT/docker-compose.yml config | docker-compose -f - up
```

You'll want to alias that command or put it make because you have to re-create that same docker-compose file and pass it in for commands like `ps`, `down`, or `stop`.

```
docker-compose -f submodules/A_SUB_PROJECT/docker-compose.yml docker-compose -f submodules/B_SUB_PROJECT/docker-compose.yml config | docker-compose -f - ps
```

**Comment by dlgoodchild** [comment]
Using @captain-kark suggestion, I personally found that I still had path issues being inherited from the first sub project. I've solved this using a slight variation:

```
(docker-compose -f ./submodule-a/docker-compose.yml config; docker-compose -f ./submodule-b/docker-compose.yml config) | cat | docker-compose -p project01 -f - up
```
This is based on the idea of `( command1; command2) | cat` combined with the suggestions above. With this I've got the desired result.

**Comment by dlgoodchild** [comment]
I've tried many of the solutions mentioned here, and I found that most did not work for me. The problem always seems to be that the path of the first docker-compose.yml files seems to be used in the other files, even though the path is clearly different.

I managed to get @ferrastas version working with a modification. I had to create a top level `docker-compose.yml` which contained on `version: "3.7"`. I then applied a top level `.env` as follows:

```
FRONTEND=./frontend/docker
BACKEND=./backend/docker
PROXY=./proxy/docker
```
In each of the directories listed in the `.env` file, I have a local `docker-compose.yml` which uses the variable syntax `${PROXY:-.}` as part of a volume, a sample, `./proxy/docker/docker-compose.yml`, being:

```
version: "3.7"

services:
  haproxy:
    image: haproxy:1.8.14-alpine
    volumes:
      - ${PROXY:-.}/haproxy/conf:/usr/local/etc/haproxy
      - ${PROXY:-.}/ssl:/usr/local/etc/ssl
    ...
```

I then execute this with:
```
docker-compose -f docker-compose.yml -f ./frontend/docker/docker-compose.yml -f ./proxy/docker/docker-compose.yml -p proj up
```
This answer is mostly a repeat of @ferrastas but with a minor tweak and with examples (thanks!).

**Comment by GanymedeIndustries** [comment]
I ended up using a bash script wrapper for building the config, but I do think that what @ferrastas and @dlgoodchild did with setting the environment is a more cleaner approach. My project was basically the same setup, where I have a frontend, a backend, a DB and a proxy wrapper for it all. To make my life easier, each "service" has their Dockerfile and docker-compose.yml files in their respected `/docker/dev/` directories, and each relative path in docker-compose config is `../../` (`context`, `volumes`, etc). Here is an example of the `backend` config:

```
version: "3"
services:
  backend:
    image: backend:dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../:/usr/src/app
```

Project setup is:

```
my-project
|
|--> /proxy
|---------> /dev/docker/Dockerfile and docker-compose.yml
|
|--> /backend
|---------> /dev/docker/Dockerfile and docker-compose.yml
|
```

You get the picture. Here is my script that lives in the root path:

```bash
#!/bin/bash

DOCKER_ROOT="${PWD}"
DOCKER_PATHS=(proxy frontend backend db)
DOCKER_CONFIG=""

for i in "${DOCKER_PATHS[@]}"; do
  CONFIG_ROOT="${DOCKER_ROOT}/${i}"

  CONFIG_TXT=$(cat "${i}/docker/dev/docker-compose.yml");
  CONFIG_TXT="${CONFIG_TXT//\.\.\/\.\.\//$CONFIG_ROOT}"

  # Need to remove the "version" and "services" lines on the non-first one
  if [ "$i" != "proxy" ]; then
    CONFIG_TXT="$(echo "$CONFIG_TXT" | sed /version\:/d | sed /services\:/d)"
  fi

  DOCKER_CONFIG=$(echo "${DOCKER_CONFIG}" && echo "${CONFIG_TXT}")
done

echo "${DOCKER_CONFIG}" | docker-compose -f - config
```

Notice that I remove the `version` and `services` lines from the config on the non-first config, this is because in the end I pipe it all the `docker-compose config` as one file instead of multiple `-f` files. As people have mentioned, the order of `-f` (in this case the array `$DOCKER_PATHS`) is very important, as the first config is your "base" and the rest are overrides. You could even do what @dpnova mentioned and just create an empty config as your base (or just hard code it here in the script) to make it more uniform.

**Comment by GanymedeIndustries** [comment]
**For WSL users**

If you are using WSL, then you need to specify all `volumes` as WSL paths, whereas all `context` paths should stay the same linux format. Below is a quick fix for the above script (plus a tweak using @dpnova advice):

```bash
#!/bin/bash

DOCKER_ROOT="${PWD}"
DOCKER_PATHS=(proxy frontend backend db)
DOCKER_CONFIG="version: \"3\"\nservices:"

for i in "${DOCKER_PATHS[@]}"; do
  CONFIG_ROOT="${DOCKER_ROOT}/${i}"
  WSL_CONFIG_ROOT=$(wslpath -au "${i}")

  CONFIG_TXT=$(cat "${i}/docker/dev/docker-compose.yml");
  CONFIG_TXT="${CONFIG_TXT/context\:\ \.\.\/\.\.\//context: $CONFIG_ROOT}"
  CONFIG_TXT="${CONFIG_TXT//\.\.\/\.\.\//$WSL_CONFIG_ROOT}"

  # Need to remove the "version" and "services" lines
  CONFIG_TXT="$(echo "$CONFIG_TXT" | sed /version\:/d | sed /services\:/d)"

  DOCKER_CONFIG="${DOCKER_CONFIG}\n${CONFIG_TXT}"
done

echo -e "${DOCKER_CONFIG}" | docker-compose -f - config
```

I'm only using `context` and `volumes`, so I can just replace `context` with one and the rest as the WSL path

**Comment by Gems** [comment]
I believe that `docker-compose` **has a bug** not respecting well the following part of the documentation:
> **CONTEXT** - When the value supplied is a relative path, it is interpreted as _relative to the location of the Compose file_. This directory is also the build context that is sent to the Docker daemon.

**Comment by ferrastas** [comment]
It's not a bug, it's clearly explained in https://docs.docker.com/compose/extends/
> When you use multiple configuration files, you must make sure all paths in the files are relative to the base Compose file (the first Compose file specified with -f). This is required because override files need not be valid Compose files. Override files can contain small fragments of configuration. Tracking which fragment of a service is relative to which path is difficult and confusing, so to keep paths easier to understand, all paths must be defined relative to the base file.

**Comment by Gems** [comment]
Thanks a lot for pointing out to the corresponding documentation section.

**Comment by Gems** [comment]
I've created [a `docker-compose` wrapper](https://gist.github.com/Gems/a40d7eb45f46c82f990aa7e8845d7e7a) that changes the behavior in case of multiple files specified and makes each configuration file consider its own working directory.

**Comment by dlgoodchild** [comment]
For those interested, I've just tested @Gems `docker-compose` wrapper script (after changing the version from 3 to 3.7 within the script), and I have to say it has so far worked very well!

As a quick test, my command was:
```
$ chmod +x docker-compose.sh
$ ./docker-compose.sh \
    -f ./frontend/docker/docker-compose.yml \
    -f ./proxy/docker/docker-compose.yml \
    -p 016 up
```
I added in a project "name" (in this case a project number) as a test that it was recognised. My `docker ps` then looked like:

```
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                                      NAMES
d657452408b7        haproxy:1.8.14-alpine   "/docker-entrypoint.…"   2 minutes ago       Up 2 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   016_haproxy_1
cefc6fd95bf4        nginx:1.13.6-alpine     "/bin/sh -c 'envsubs…"   12 minutes ago      Up 2 minutes        0.0.0.0:8881->80/tcp                       016_nginx_1
```
Thought this might be useful for some folk who were maybe a bit unsure on how to use the wrapper.

A noteworthy mention is that if there is a `.env` file in the directory from where you run the `docker-compose.sh` file this will be picked up and used by docker-compose.

Thanks @Gems, it works a treat! I might move over to using that in favour of having to define and maintain env variables.

**Comment by leonklingele** [comment]
No

**Comment by katsar0v** [comment]
Is there update on this matter? The documentation seems to be poor as well, nobody knows exactly how docker-compose behaves with multiple files

**Comment by hangyan** [comment]
It should be working correctly by now. @katsar0v Could you provide a example to show the errors?
I will dig into it

**Comment by katsar0v** [comment]
Well the solution says:
> When you use multiple configuration files, you must make sure all paths in the files are relative to the base Compose file (the first Compose file specified with -f). This is required because override files need not be valid Compose files.

Why should all files be relative to the base file and not the corresponding docker-compose file? There are no variables supported, nor $(pwd) is possible. Hardcoding paths is not a good solution

**Comment by hangyan** [comment]
@katsar0v Sorry , i thought this is a project of mine..

**Comment by katsar0v** [comment]
It is currently working, so "technically" the issue might be closed. But IMO it could be done way better. I am not a docker developer, can just help with testing and documentation.

**Comment by ndeloof** [comment]
Support for multiple compose files was introduced to support overrides, which mean the 2nd and next files set by `--file` options _should_ be designed as complimentary configuration for the main compose file, not independent content with their own relative paths and resources. 

Documentation need to clarify this behaviour indeed.

**Comment by myitcv** [comment]
> Support for multiple compose files was introduced to support overrides, which mean the 2nd and next files set by `--file` options _should_ be designed as complimentary configuration for the main compose file, not independent content with their own relative paths and resources.

I think the point that many are raising here is that the semantics you describe are not (necessarily) exclusive with an approach that allows compose files from multiple projects to be composed.

For my own purposes, I've [created a wrapper around `docker-compose`](https://github.com/myitcv/docker-compose) to address this issue and #7546.

**Comment by kmturley** [comment]
This an **essential feature** for a multiple-repo microservice architecture...

Using meta to pull in the code from multiple git repositories:
https://github.com/mateodelnorte/meta

Then using docker-compose to run them all together.

Any idea on when we can get a fix? or official workaround?

**Comment by jdsalaro** [comment]
Keep in mind that if you're using the `.env` work-around with the `SERVICE_*` and `COMPOSE_FILE` definitions your local volumes still will not be mapped correctly.

Assuming you have `COMPOSE_FILE=./1/docker-compose.yml:./2/docker-compose.yml:./3/docker-compose.yml` and 

```
SERVICE_1=../1
SERVICE_2=../2
SERVICE_3=../3
```
You'll probably have to change all your local volume definitions to start at `../`. In `./1/docker-compose.yml` that would be as follows:

```
volumes:
      - ../1/volume
``` 

Also, by virtue of having `.env` in your root directory your `.env` files in the respective subfolders will be ignored [1].

[1] https://stackoverflow.com/questions/62728192/how-to-specify-multiple-env-files-for-a-docker-compose-service

**Comment by ndeloof** [comment]
The way multiple compose file get merged together is now defined by the Compose Specification:
https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file

> Relative paths MUST be resolved based on the first Compose file's parent folder, whenever complimentary files being merged are hosted in other folders.

This approach was adopted to enforce backward compatibility. _Maybe_ we could introduce an alternate relative path syntax to refer to path relative to the yaml file being read? Then this should be debated on the Compose Specification.

**Comment by bnjmnbrmn-work** [comment]
I think you can make @GregYeo 's solution a little more elegant by using process substitution (if you are using bash).  Something like 
```
docker-compose -p combined_project_name \
  -f <(docker-compose -f submodules/A_SUB_PROJECT/docker-compose.yml config) \
  -f <(docker-compose -f submodules/B_SUB_PROJECT/docker-compose.yml config) \
  up
```

**Comment by ndeloof** [comment]
As we provide ability to merge compose files with overrides, relative paths are always challenging to manage. By the [Compose Specification](https://compose-spec.io/) they MUST be relative to the first project file ("project directory") but this obviously still can be confusing.

IMHO we miss an option to declare a path "relative to current file", so that one can write
```yaml
services:
   foo:
     build: <CURRENT_FILE>/foo
```
.. and use such a file as an override or extend it from another compose file.
The challenge then is to find a notation for such a FILE_RELATIVE_PATH that would be readable and NOT be confusing with project directory (which is already confusing with command working directory due to the `.` notation 😞)

We could make this explicit with an implicit environment variable `build: ${COMPOSE_FILE_DIR}/foo` but that would be a heavy notation. Or we could adopt some custom, compact notation comparable to `~/` for user's home, let's say for illustration `build: +/foo`

I don't know any other configuration format that has this challenge and we could mimic for such a custom notation. Any suggestion is welcome

**Comment by zhao-li** [comment]
@ndeloof some projects use `@` as an alias for the project root.  
https://developpaper.com/question/what-does-the-sign-in-the-import-path-in-the-vuejs-webpack-template-mean/

It's a bit flipped in this Docker Compose scenario.

Currently for Docker Compose:
* `.` is relative to the first project file which is sort of like the project root.

If `@` is used for Docker Compose:
* `.` is relative to the first project file which is sort of like the project root.
* `@` is relative to the current file.

The opposite is typical for most other projects:
* `@` is the project root.
* `.` is relative to the current file.

The `Custom rootPathPrefix` section in this Vue/Babel documentation suggests `#`, `\`, and `~` (as you've listed).  
https://vuejscomponent.com/package?name=babel-plugin-root-import

Hope that helps 🤞

**Comment by ndeloof** [comment]
`@/` brings risk for confusion with versions in packaging systems. Not sure this matters here, just saying
`#/` being yaml comment symbol would require such paths to be quoted, so not best option we have
`~/` is expanded to user's HOME (unlike Babel)
`./` is our legacy for "project dir" 😓  which we obviously can't suddenly adopt for "compose file relative"
`!/` could be another option...

my preference goes to `@/` for reasons I hardly can explain, just it "looks" right to me for this purpose 😅

cc @thaJeztah as we discussed this topic the other day

**Comment by thaJeztah** [comment]
Thanks for the ping; I had a proposal that I was writing; it's not fully finished, but I dusted it off a bit, and just posted it in https://github.com/compose-spec/compose-spec/issues/248)

**Comment by shymega** [comment]
This should probably be re-opened, no? Looks like the bot acted a little too hastily 🤣

**Comment by mortifia** [comment]
-f './' rule like actual for multilpe docker-compose
-fr './' rule as actual file relative 

shouldn't break anything, and theoretically doesn't seem too complicated to add.

it just requires adding a rule that modifies no other rule

**Comment by thenick775** [comment]
Bumping, I found this really confusing, and its almost prompting me to ditch docker compose for my personal projects in monorepos altogether in favor of another solution.

This seems like something that would be easy to solve with a variation on the file flag as shown above.

**Comment by thenick775** [comment]
I'm a fan of `@/` myself, or `!/` as shown above if a flag like `--file-relative` is unfeasible

**Comment by rca** [comment]
Is it possible to make this ”right” by introducing the desired semantics by bumping a major version (v4, right?) so it indicates backwards incompatibility and add deprecation warnings in a v3 minor bump?  And by “right” I mean something along the lines of below:

- if you specify the path with a `./` prefix, the path will be relative to the current directory (this follows the convention volume mounts use)
- if there is no prefix, the current behavior is followed
- there may be something clever to be done if the `/` prefix is used
