### ISSUE TITLE
docker-compose -f /my/path/docker-compose.yml - No such file or directory

### ISSUE THREAD

**Issue by samber** [docker/compose#3875]
Hi guys !

When doing a `docker-compose -f /a/b/c/docker-compose.yml pull` from `/a` -> it works.
When doing a `docker-compose -f /a/b/c/docker-compose.yml pull` from `/a/foo/bar` -> it does not work:

```
ERROR: .IOError: [Errno 2] No such file or directory: '/a/b/c/docker-compose.yml'
```

Didn't investigate more on this problem.

```
$ docker-compose  version
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

**Comment by mikygit** [comment]
Having the same probleme here.
Any news on this?

**Comment by jraduget** [comment]
+1, met same issue on 1.8.0 version

**Comment by coolcow** [comment]
Same issue.

Docker version: 1.12.5
docker-compose version: 1.9.0

How to reproduce:

```sh
cd /home/userBBB/
docker-compose -f /home/userAAA/subdir/test.yml up -d
# ERROR: .IOError: [Errno 2] No such file or directory: '/home/userAAA/subdir/test.yml'

cd /home/userAAA/
docker-compose -f /home/userAAA/subdir/test.yml up -d
# it works
```

It is NOT a premissions problem on ```/home/userAAA/subdir/test.yml``` or any part of the path (i checked this).

**Comment by yaroslav-shabalin** [comment]
Same problem here, v1.8.0 build f3628c7.

**Comment by chrisvel** [comment]
Same problem here, I saw it when I added a systemctl service and it fails to run in system boot with this message.

**Comment by amansilla** [comment]
Same problem, it's really weird. I've no clue why that's not working.

**Comment by rafadpedrosa** [comment]
Same problem here... Someone solved this? Pliz share :(

i'm on windows and that's my docker version:

```
$ docker-compose version
docker-compose version 1.16.1, build 6d1ac219
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by rafadpedrosa** [comment]
it seems to be an [issue](https://github.com/garethr/garethr-docker/issues/492)  using many files...

i'm not that good in docker and i really don't know how to solve this. Even because i'm using [laradock](http://laradock.io) and it has a lot of things on it that i don't understand. 

Any way, when i remove the bold text, it runs.

`COMPOSE_FILE=docker-compose.yml:`**docker-compose.dev.yml**

But it feels wrong. I'm going to downgrade docker version tomorrow and see how it works.

**Comment by stevebauman** [comment]
Getting the same thing as @rafadpedrosa, thanks for the solution!

Don't really know docker yet though so not sure if this is an issue.

**Comment by Mat001** [comment]
This works on 
Ubuntu linux, 
docker-compose version 1.21.0-rc1, build 1d32980
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

`m@m:~/userBBB$ docker-compose -f /home/m/userAAA/subdir/docker-compose.yml up -d
Starting subdir_web_1   ... done
Starting subdir_redis_1 ... done
`

**Comment by Mat001** [comment]
@samber  Hey, could we close this issue? It seems it has been resolved. Works for me. Can you try again and then close it?

**Comment by samber** [comment]
@Mat001 Cannot reproduce this bug.

Thanks to whoever fixed that ;)

**Comment by simonloveslife** [comment]
I have the same problem 

docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

(18-10-05 0:56:06) <0> [/]
ocker-compose -f /tmp/tmpfRtJlW/docker-compose.yaml up --build --abort-on-container-exit
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpfRtJlW/docker-compose.yaml'

(18-10-05 1:03:58) <0> [/tmp]
docker-compose -f /tmp/tmpfRtJlW/docker-compose.yaml up --build --abort-on-container-exit
Working!

**Comment by samber** [comment]
It works for me (OSX, 1.22).

**Comment by simonloveslife** [comment]
@samber 
Thanks for confirming, do you think that's because I use an old docker?
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Thu Jan 26 09:26:48 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Thu Jan 26 09:26:48 2017
 OS/Arch:      linux/amd64

**Comment by samber** [comment]
Yes, maybe...

But I think this issue was for docker-compose, not docker engine.

Anyway, using an old docker-compose version with a recent docker engine does not guaranty that everything is working well! At that time Docker retro-compatibility was not very nice :-(.

**Comment by mallikarjunasai995** [comment]
My pc docker compose current versionis 1.22.0 how can i downgrade it to 1.20.0 where i wont reproduce that error?

**Comment by kamalhappysanz** [comment]
Hi guys I'm getting this error while giving command  can someone help in this... 
![docker error](https://user-images.githubusercontent.com/26597676/47895440-4f2ef580-de8e-11e8-8d85-517f11c95b9e.JPG)


THanks in advance

**Comment by wtgee** [comment]
Any follow up on this? I've spend a lot of time with this lately, but it seems like the `-f` option to docker-compose is rather useless, or at least misleading. As is the error message.  

It seems natural to have one docker-compose file in a central location that starts multiple containers from multiple directories (each in different repositories).

Not sure if my problem is actually related to this Issue or not because the error is extremely unhelpful.

**Comment by wtgee** [comment]
What I've found is that you should just absolutely always be starting from some common root directory. The trick with multiple overrides is then apparently they *cannot* be specified by absolute path but instead must be relative. 

From [Understanding multiple Compose files](https://docs.docker.com/compose/extends/#understanding-multiple-compose-files).

> When you use multiple configuration files, you must make sure all paths in the files are relative to the base Compose file (the first Compose file specified with -f). This is required because override files need not be valid Compose files. Override files can contain small fragments of configuration. Tracking which fragment of a service is relative to which path is difficult and confusing, so to keep paths easier to understand, all paths must be defined relative to the base file.

Which seems like a weak argument to me. Far more confusing is the fact that an absolute path will not work and will through a completely misleading error message.

**Comment by chuongtrh** [comment]
Same issue. Any solution to fix :-?

```
docker-compose version 1.25.0-rc2, build 661ac20
docker-py version: 4.0.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019

```

**Comment by direstrepo24** [comment]
For me , work this : docker-compose -f ./a/b/c/docker-compose.yml

**Comment by proton72** [comment]
Have been reproduced on docker installation only

**Comment by qiluge** [comment]
docker-compose version 1.25.5, build unknown
Docker version 19.03.11, build dd360c7
Ubuntu 18.04
same error for me.

**Comment by HynekS** [comment]
I was facing the same issue. My solution was changing the extension of `docker-compose` file from `yaml` to just `yml`.

**Comment by alextoader** [comment]
I had to fix 2 issues
- I had docker installed twice - once with snap and once without. It created 2 configuration files. So I had to hard delete and purge docker with config files and reinstall it fresh
- I had to install Docker Compose (it is smth else than the engine) https://docs.docker.com/compose/install/ 
After that it all worked.

Hope it helps.

**Comment by romannik007** [comment]
docker-compose --project-directory ${PROJECT_PATH}/ up -d its working!!!

**Comment by hulyak** [comment]
I'm getting the same error with the Docker Compose version v2.1.1 on Mac with Apple chip. I have installed  Rosetta 2.

**Comment by diraneyya** [comment]
I am facing the same quite bizarre error. I am writing a "docker compose" wrapper tool that stores transformed yaml files in the "tmp" directory. The tool usually works but seem not to work with docker compose version 2.20.3 on Ubuntu Server 24LTS
