### ISSUE TITLE
Inconsistent port behavior between start a service using up and run

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#3882]
`docker-compose up -d` exposes all the ports mentioned in `ports`. `docker-compose run -d <service-name>` requires `--service-ports` to be specified.

This is inconsistent behavior. Why?

**Comment by friism** [comment]
I believe this is by design: https://github.com/docker/compose/issues/1259#issuecomment-90878095

> The second difference is the docker-compose run command does not create any of the ports specified in the service configuration. This prevents the port collisions with already open ports.

 - https://docs.docker.com/compose/reference/run/

**Comment by arun-gupta** [comment]
This help explains, will close the issue.

**Comment by reypm** [comment]
@arun-gupta from a `docker-compose.yml` I can see the ports exposed as per the following output:
```
            Name                           Command               State         Ports       
------------------------------------------------------------------------------------------
php55devwork_php-apache_1       /bin/sh -c bash -C '/usr/l ...   Up       80/tcp, 9001/tcp
```

But I can't access to the container using `http://localhost`, should I? How do I map the 80 port from the container with the host 80 port? All of this using `docker-compose`

**Comment by arun-gupta** [comment]
@reypm please open a new bug with your complete `docker-compose.yml` and steps to reproduce the error.
