### ISSUE TITLE
Support docker-compose login

### ISSUE THREAD

**Issue by jonaskello** [docker/compose#3883]
I have a CI build in GitLab that uses docker-compose to deploy on a remote docker host. The CI build can do everything using only the docker-compose binary, except for one thing. The images are coming from a private registry which requires authentication (the registry in GitLab). So I need to run  `docker login` before I do `docker-compose pull`. This means I have to install the full docker package in the CI build just to execute the `docker login` command. I propose that login in is added directly to docker-compose and work the same way as in docker. So I can run something like `docker-compose login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY`.

**Comment by sambernet** [comment]
This should fix the root cause of issue #3782 as well. From the bug report and the logs in #3782 it looks like compose tries to reuse the `~/.docker/config.json` auth config file created by the docker client on `docker login`. 

This is a dependency on an external file created by another binary on the system - something we should probably avoid.

Pre-existing auth config from the docker client can still be considered if no explicit `docker-compose login` has been performed beforehand.

**Comment by blackholegalaxy** [comment]
any update on that?

**Comment by andrewnazarov** [comment]
Ant news?

**Comment by shin-** [comment]
Because of the intricacies of authentication in Docker, we have no plans to add a `login` subcommand at this time, as it would duplicate functionality with the Docker CLI and create a lot of additional complexity and potential for issues in Compose.

Thank you for your understanding.

**Comment by buffcode** [comment]
This also renders the [docker/compose image](https://hub.docker.com/r/docker/compose/) useless for private registries.

I understand the duplication reason, but then the login/logout functionality should probably be de-duped into a third component which can then be used by both `docker` and `docker-compose`.

**Comment by lucasbasquerotto** [comment]
@buffcode You can use the compose image and share credentials with the user in the host if you run through the script in https://github.com/docker/compose/blob/master/script/run/run.sh

You can see that it uses the volume in the `$HOME` directory of the user who runs it:

https://github.com/docker/compose/blob/90185117501861558f265f5ac83bddb1aca0bad2/script/run/run.sh#L46

**Comment by yuyasong** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ]
