### ISSUE TITLE
Wrong suggestion message

### ISSUE THREAD

**Issue by Vanuan** [docker/compose#3890]
Version
```
docker-compose -v
docker-compose version 1.8.0, build f3628c7
docker -v
Docker version 1.12.1, build 23cf638
```
docker-compose.yml
```
version: '2'
services:
  nginx:
    image: 'nginx:1.10-alpine'
```
command
```
$ docker-compose bundle
ERROR: Some images are missing digests.

The following images need to be pulled:

    nginx:1.10-alpine

Use `docker-compose pull nginx:1.10-alpine` to pull them.
```

Clearly, the message should've been `docker pull nginx:1.10-alpine`, without compose.

**Comment by Vanuan** [comment]
Another bad example is that when there are multiple messages, it reads

`docker-compose pull image1 image2 image3`

while docker-compose pull accepts exactly one argument

**Comment by shin-** [comment]
While `docker-compose pull` does exist, it does indeed take services as arguments instead of image names. `docker-compose pull` can however take multiple services as arguments. All in all, I think this should be fixed by replacing the image names by service names in the error nessage,

cc @dnephin

**Comment by dnephin** [comment]
That sounds right to me

**Comment by Vanuan** [comment]
I suspect this error (`Some images are missing digests.`) only happens after upgrade, when images already downloaded.
That's why so few people seem to have it.

**Comment by Vanuan** [comment]
Be aware that this error is different from this:

```
docker-compose bundle
ERROR: Image not found for service 'nginx'. You might need to run `docker-compose pull nginx`.
```
