### ISSUE TITLE
Proposal: Support for creating volume and network with label options

### ISSUE THREAD

**Issue by dbdd4us** [docker/compose#3892]
I have ran into a situation where I need to get networks and volumes created by a given compose project. I think it could be done by adding a label to the networks and volumes defined in the compose file and then I could query the networks and volumes by a label filter through docker api. 

But when  I check the schema definition at **compose/config/config_schema_v2.0.json**, I found it's not supported by compose.

Would it be better if creating volume and network with label options is supported? I could do this if this feature is reasonable.

**Comment by dbdd4us** [comment]
@shin- @vsaraswat 
I was wondering if releated development is in progress, or could  I start implementing this feature?

**Comment by shin-** [comment]
@dbdd4us It's partly dependent on https://github.com/docker/docker-py/pull/1178, but I haven't started working on the compose side yet - if you wish to contribute, that would be more than welcome!

**Comment by dbdd4us** [comment]
@shin- 
Thanks for your feedback. I'm starting implementing this feature and I will submit a pull request ASAP.

#dibs
