### ISSUE TITLE
docker run --isolation parameter not available

### ISSUE THREAD

**Issue by PatrickLang** [docker/compose#3906]
`docker run` has a parameter [--isolation](https://docs.docker.com/engine/reference/commandline/run/#/specify-isolation-technology-for-container-isolation) that can be used to set additional isolation modes when running Docker containers. For example, `docker run --isolation=hyperv` is commonly used on Windows with Hyper-V. Given that most of the other run options are already supported such as `security_opt` and `privileged`, I think it makes sense that `isolation` should be there too.

Here's an example of how I would like to use it in docker-compose.yml:
```none
version: '2'
services:
  sql:
    image: windowsservercore
    tty: true
    stdin_open: true
#    isolation: 'hyperv'
  
  web:
    image: windowsservercore
    tty: true
    stdin_open: true
#    isolation: 'hyperv'
 
networks:
  default:
    external:
      name: nat
```

**Comment by PatrickLang** [comment]
ping @friism - can you tag this for Windows?

**Comment by friism** [comment]
@PatrickLang what's the behavior when `hyperv` is not available? It would be sad if adding this option caused some docker-compose.yml files to only work on some systems.

**Comment by friism** [comment]
@PatrickLang (I'm not an admin here, so can't label)

**Comment by PatrickLang** [comment]
re: `hyperv` not available - I think that's ok. I view Dockerfiles as code that should have no dependency on environment. I expect to customize docker-compose files for my environment. For example, `ipam`, `volume_driver`, `ipv4_address`, `logging` can all contain data that will only work right in a specific deployment

**Comment by uday31in** [comment]
What is the correct way to specify isolation setting with compose? I have a Front end that can use process isolation however back end service needs to on server core due to .Net 3.5 dependency and hosts are Nano.

**Comment by friism** [comment]
@PatrickLang 

> For example, ipam, volume_driver, ipv4_address, logging can all contain data that will only work right in a specific deployment

Agree, it makes sense to include
