### ISSUE TITLE
Question: How to use "old networking" in v2 (swarm)?

### ISSUE THREAD

**Issue by schmunk42** [docker/compose#3911]
Is there a way to tell `docker-compose` not to create any networks for a stack?
Basically handle networking like in `v1`. What's about network aliases then?

**Comment by shin-** [comment]
Hi,

I'm sorry to say this is not something we support at this point. Is there a particular reason you're unable to use the newer network features?

**Comment by schmunk42** [comment]
It's mainly to support existing configurations with newer swarms, but we also had issues with network stability depending on an external kv-store such as consul.

It looks to me that also information about the local networks (host, bridge) is stored in the kv - and when this service runs into problems the whole swarm deployment is much more affected than with v1.

What about `network_mode`, looks to me like this is pretty much doing the job - but it's cumbersome to set it everywhere, I also need to check it more in detail.

**Comment by schmunk42** [comment]
Related:
- https://github.com/docker/docker/issues/23302
- https://github.com/docker/docker/issues/25215
