### ISSUE TITLE
Run Windows 32 bits

### ISSUE THREAD

**Issue by pedro151** [docker/compose#3914]
I wanted to know if it is possible to run on 32-bit OS?

**Comment by shin-** [comment]
Hi Pedro,

We don't offer a packaged version of compose for 32 bit architectures, but if you have a Python environment already installed, you can install it via `pip`. Refer to our [install docs](https://docs.docker.com/compose/install/#/install-using-pip) for more info!

**Comment by pedro151** [comment]
I installed by pip and continues with the same error "System.ComponentModel.Win32Exception"

**Comment by shin-** [comment]
Hm, that doesn't look like a Python error. Without more details, the best I can do is ask you to seek help from Microsoft support channels, who can make better sense of this error than I ever could.

**Comment by shin-** [comment]
Ah, sorry I missed your edit. Glad you were able to figure it out, cheers!
