### ISSUE TITLE
On native Windows, paths should not be "UNIXized"

### ISSUE THREAD

**Issue by shin-** [docker/compose#3923]
See: https://github.com/docker/docker/pull/26294
Also pointed out by @PatrickLang in https://github.com/docker/compose/issues/3897#issuecomment-244260851

1. We can try and detect the type of daemon compose is connected to and normalize paths accordingly. I don't know if this is even possible, and it creates additional network roundtrips that will make Compose feel slower in some environments.
1. We do not normalize by default, and create additional documentation to inform non-native users of the format they should employ. This would be a breaking change, but is much simpler to implement.

cc @aanand @dnephin @friism WDYT?

Relevant: https://github.com/docker/docker/pull/23569#issuecomment-226615771

**Comment by friism** [comment]
ping @dgageot since I think docker for windows already attempts some of this re-writing.

**Comment by dgageot** [comment]
@shin- @friism I think option 1 would have to be done on every Api clients, including Docker cli. Option 2 would work but on environments like Docker for Windows, it would make it more difficult to get rid of our intermediate Api proxy that currently has to do mount rewriting to support a windows host talking to a linux guest mounting a windows fs.

cc @justincormack

**Comment by thaJeztah** [comment]
I would prefer 2.; automatically converting the target path (inside the container) looks odd to me, and it should just preserve what the user specified.

Perhaps the engine already takes Windows paths into account (I'm not running on Windows), so `/` may already be converted to `C:\` on a Windows container?

ping @jhowardmsft any ideas?

**Comment by jhowardmsft** [comment]
The Windows daemon expects Windows style paths for volumes such as -v on docker run. It will reject Unix style paths such as /c/Windows/system32 etc.There are some situations where / will be treated as c:\ though in a dockerfile. What is the context of the question?

**Comment by thaJeztah** [comment]
@jhowardmsft mainly, if docker-compose should try to automatically detect the type of daemon, and if Unix paths are specified as target, but the daemon is Windows, to magically try to convert `/foo/bar` into `C:\foo\bar`

**Comment by jhowardmsft** [comment]
I think it would need evaluating api by api. Unfortunately the engine isn't consistent and many can accept unix style paths assuming the drive is c if omitted, as mentioned above. Volume is somewhat more restrictive, at least from the CLI. Almost all APIs filepath.fromslash the input so / or \ can be used interchangeably by and large. I don't really have enough compose experience to provide more guidance.

**Comment by friism** [comment]
I don't understand all the constraints, but I favor option 2 too: we should try to reduce the amount of guessing, mangling and special-casing, not add more layers.

It seems like the main constituency we would break is Docker Toolbox (since there's not proxy there, like there is on Docker for Windows). So maybe we could have the current behavior as an backwards-compat option, and somehow turn it on by default in Toolbox...

**Comment by PatrickLang** [comment]
I'm pretty sure that docker-compose accepts relative paths eg `./foo` and converts them to absolute paths `/home/Patrick/foo` before passing them to the engine. Would that be possible in both options?

**Comment by thaJeztah** [comment]
@PatrickLang this is about the _target_ path inside the container; the container can have a completely different directory structure than the system, so I really don't think we should add more magic there.

**Comment by PatrickLang** [comment]
@thaJeztah true, good point. Just calling it out since source paths were broken (and fixed) previously.

**Comment by friism** [comment]
I just spoke with @shin-, his proposal was to:

 * Change the default compose behavior to _not_ attempt path fixing on Windows
 * Move the path fixing behind an environment variable toggle
 * Docker Toolbox can set this environment variable to get the current behavior
 * Docker for Windows won't need the path-fixing because it can do it itself in the proxy

This seems good to me. The only problem I can think of is for Toolbox users that somehow end up also wanting to run Windows Containers: they'll have the environment variable set and get paths unhelpfully fixed, but I don't that will be common at all.

I'd love to get @dgageot's fine mind to form an opinion on this too, since he's messed with this a lot.

**Comment by thaJeztah** [comment]
Wouldn't the author of a docker-compose file know if the image that's used for a service is Windows or Linux based? Trying to understand the use case

**Comment by shin-** [comment]
@thaJeztah This concerns host paths as well - in fact I'd argue it's the main issue here.

**Comment by friism** [comment]
@thaJeztah you're right, but right now there's probably a set of Toolbox users that are having paths rewritten and they don't know that this is happening. We should be mindful about that breakage...

**Comment by aanand** [comment]
Relatedly, is there _ever_ a good reason to convert the internal path? I can't think of one. It should be the same regardless of host OS, since you always know whether you're running a Linux or a Windows container.

**Comment by shin-** [comment]
@aanand I agree that it's unnecessary / doesn't make sense. I'll remove it as part of #4026 .

**Comment by dgageot** [comment]
@friism I'm clearly +1 on NOT trying to normalize the paths in any CLI tool. On Docker for Windows, we currently do it in the Api proxy because it knows which daemon it points at.

At some point, we'd want to get rid of our Api proxy but that's another story...

**Comment by friism** [comment]
@dgageot thanks! What's your estimate of the fate of toolbox users that depend on this rewriting behavior?

**Comment by friism** [comment]
Instead of environment variable (which @dgageot doesn't like), we could maybe use the .config file: https://docs.docker.com/engine/reference/commandline/cli/#/configuration-files

**Comment by shin-** [comment]
Using values in the `config.json` file would set a weird precedent, since all compose-specific configuration so far has been provided through the environment (see [here](https://docs.docker.com/compose/reference/envvars/)). 
We would need a compelling reason to do things differently this time around.

**Comment by friism** [comment]
Understood, thx.

**Comment by dgageot** [comment]
@friism @shin- FWIW [This PR](https://github.com/docker/docker/pull/26780) from @justincormack on docker/docker tried to go that direction.

**Comment by shin-** [comment]
Closing via #4026. See also: https://github.com/docker/machine/pull/3830
