### ISSUE TITLE
Relative paths for host mounted volumes not working on Windows

### ISSUE THREAD

**Issue by laggingreflex** [docker/compose#3925]
### Description

It seems mounting a host directory as a data volume with relative path to current host dir using docker-compose no longer works in Windows. 

```yml
version: '2'
services:
  test:
    build:
      context: ./
    volumes:
      - .:/test
```

I've tested it with Windows 10, Docker version 1.12.1,  docker-compose version 1.8.0, which didn't work. And on Ubuntu 14, Docker version 1.12.0, docker-compose version 1.9.0dev, which works as usual. 

### Steps to reproduce:

1. Clone https://github.com/laggingreflex/docker-test

2. Run it on windows, and for comparison run it on Linux

#### Expected result:

The current dir which is mounted should be `ls`-ed and its contents output. 
```
CMD ls /test
```

#### Actual result:

On windows it outputs nothing (ls of an empty dir, means it didn't actually mount). Works on Linux, shows the two files of the test project. 

Absolute paths still work as usual, like 
 ```yml
   volumes:
      - /c:/test
```

**Comment by shin-** [comment]
Thank you for your report!

I believe #3922 would solve your issue. If you don't mind trying the branch in your windows environment and reporting with results, that would be a great help.
Another possible workaround would be to add a `/` in your local path, as such:
```yaml
volumes:
  - ./:/test
```

Let me know if that helps.

**Comment by laggingreflex** [comment]
It was actually an error on my part. I needed to enable the Shared Drives option. x_x
