### ISSUE TITLE
Send docker-compose to daemon mode without restart

### ISSUE THREAD

**Issue by aug-riedinger** [docker/compose#3936]
As from this [SO question](http://stackoverflow.com/questions/39439689/docker-compose-send-to-daemon-mode-without-restart?noredirect=1#comment66202483_39439689):

I like to `docker-compose up` first to check that everything started correctly.

Once everything's fine, I'd like to being able to send the command to daemon mode, without having to `docker-compose stop` and `docker-compose -d up` (two steps + service interruption).

**Comment by shin-** [comment]
Maybe you could run `docker-compose -d up`, then `docker-compose logs` to check the status of your app. `logs` can then be exited at any time without affecting your application.

**Comment by aug-riedinger** [comment]
Indeed, but since the `-d` option is not default, I tend to forget about it in the first place and then find myself *stuck*.

It is not so bad, but I reckon the feature would make sense, wouldn't it?

There are reasons for Unix's Ctrl-Z to have been created

**Comment by shin-** [comment]
What about `Ctrl-Z`, `bg` and maybe `disown`, then? It seems to me UNIX already gives you all the tools you need in that case.

**Comment by aug-riedinger** [comment]
I tried `Ctrl-z`, `bg` but could not exit the ssh session, receiving `There are stopped jobs.` I don't know about `disown` though, I'll try it out.

**Comment by TristanCP** [comment]
So, can you confirm `disown` does the trick without side effects ?
