### ISSUE TITLE
docker-compose complains about invalid TLS configuration

### ISSUE THREAD

**Issue by goloroden** [docker/compose#3937]
I am running Docker 1.11.2, and so far, everything is fine. The Docker engine is exposed via TCP, TLS is enabled. The certificate is a self-signed one, but so far it has always been working. E.g., if you run

```
$ docker ps
```

everything is fine and the running processes are shown. Now I tried to use docker-compose to start an application. This failed with the following error message:

> TLS configuration is invalid - make sure your DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are set correctly

The same error happens if you provide the parameters `--tlscert` and `--tlskey` manually. The certificate contains the host name, so it should not be related to #3365. I have read multiple times that setting `CURL_CA_BUNDLE` to an empty value should help, but it didn't.

I have experienced this behavior with docker-compose 1.7.0 and 1.8.0.

Any ideas?

**Comment by shin-** [comment]
This error would typically be raised if any of your paths to certificate files (Client cert, key or CA cert) was invalid for some reason. We test that with [`os.path.isfile`](https://docs.python.org/2/library/os.path.html#os.path.isfile) [here](https://github.com/docker/docker-py/blob/master/docker/tls.py#L44-L45). Do you see any reason why that wouldn't work? 
* Does the user running compose have access to those files? 
* When passing those arguments through the command line, did you use quotes? If so, maybe #3534 is the issue (will be fixed in the next release)

**Comment by StefanScherer** [comment]
@goloroden I don't know if docker-compose works without a ca.pem. I've used docker-compose only with docker-machine and that provides it. E.g.

```
$ docker-machine config dev
--tlsverify
--tlscacert="/Users/stefan/.docker/machine/certs/ca.pem"
--tlscert="/Users/stefan/.docker/machine/certs/cert.pem"
--tlskey="/Users/stefan/.docker/machine/certs/key.pem"
-H=tcp://192.168.99.100:2376
```

So skipping `--tlscacert` might be a problem.

The error message `TLS configuration is invalid ...` appears [here](https://github.com/docker/compose/blob/3dec600d8218833de11279e1dac6af048222dbc6/compose/cli/docker_client.py#L51-L56) in the code calling [`kwargs_from_env`](https://github.com/docker/docker-py/blob/c5a81002c6af649ed5deef44b154b05627559e1b/docker/utils/utils.py#L488)

**Comment by goloroden** [comment]
@shin- Thanks for your answer. Unfortunately, I don't see a reason why this shouldn't work. To address your questions:

> Does the user running compose have access to those files?

Yes, this is the same user as the one that is running docker itself (with the exact same files).

> When passing those arguments through the command line, did you use quotes?

No, but I'm going to try this.

@StefanScherer Thanks for your answer as well :-). The CA certificate may also be a valid point, I am going to double-check this…

**Comment by goloroden** [comment]
Okay, we have tried it, and both approaches didn't work: Neither using double-quotes nor specifying the CA certificate additionally. We still get the error message :-(

**Comment by lawrentiy** [comment]
A had such issue.
docker-compose 1.8
docker-machine 

Step 1 - Doesn`t work
`eval $(docker-machine env machinename)
docker-composer up -d
`
Step 2 - Deployed successfully
`docker-composer $(docker-machine config machinename | xargs ) up -d`

That is bug, 99% of my certain

**Comment by jitekuma** [comment]
I debugged docker-compose and docker-py and figured out that you should either use environment variables or options in command. You should not mix these . If you even specify --tls in command then you will have to specify all the options as the TLSConfig object, as  now  TLSConfig object is created completely from the command options and operide the TFSConfig object created from the environment variable.

**Comment by fradeve** [comment]
@jitekuma Just experienced this issue with compose 1.14, tried your suggestion and it worked!

FYI, this _worked_:

```
docker-compose -H my.host.com:2376 --tlsverify --tlscacert ca.pem --tlscert cert.pem --tlskey key.pem  -f docker-compose.yml build
```

while this _didn't_:

```
DOCKER_HOST=my.host.com:2376 DOCKER_TLS_VERIFY=True DOCKER_CERT_PATH=application_docker_client_certs  docker-compose -f docker-compose.yml build
```

**Comment by kennyhyun** [comment]
I had a similar issue like `docker ps` is working but `docker-compose up` is comlaining

```js
ERROR: TLS configuration is invalid - make sure your DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are set correctly.
You might need to run `eval "$(docker-machine env default)"`
```

with Mac docker-compose 1.26.2 and I had env vars like

```js
DOCKER_HOST=tcp://192.168.x.y:2376
DOCKER_CERT_PATH=/Users/kenny/xxx/certs/
DOCKER_TLS_VERIFY=1
```

and I was missing `key.pem` (had only cert.pem and ca.pem; I had created those as per https://docs.docker.com/engine/security/https/#create-a-ca-server-and-client-keys-with-openssl)

After copying key.pem, it started working.

**Comment by LiamKarlMitchell** [comment]
How to fix it on windows?

**Comment by javaHelper** [comment]
Any fixes for windows please?

**Comment by AlexeiScherbakov** [comment]
@LiamKarlMitchell , @javaHelper for Windows try to set user env variables and restart docker

```
COMPOSE_TLS_VERSION=TLSv1_2
DOCKER_TLS_VERIFY=0
```
