### ISSUE TITLE
Documentation: Subsequent -f files can not override their successors

### ISSUE THREAD

**Issue by DominicCronin** [docker/compose#3944]
In https://github.com/docker/compose/blob/master/docs/reference/overview.md it says: "Compose builds the configuration in the order you supply the files. Subsequent files override and add to their successors."

If the meaning is that they override the files that come before them, then 'successors' is incorrect. A better word would be 'predecessors'.

**Comment by aanand** [comment]
Agreed - good catch.

**Comment by ijc** [comment]
https://github.com/docker/docker.github.io/blob/master/compose/reference/overview.md (which I think is the current home of that file) now says:

>  You can supply multiple -f configuration files. When you supply multiple files, Compose combines them into a single configuration. Compose builds the configuration in the order you supply the files. Subsequent files override and add to their predecessors.

So I think this has been corrected somewhere along the way. Thanks for your report though!
