### ISSUE TITLE
Docker compose does not remove properly networks

### ISSUE THREAD

**Issue by Fattaf** [docker/compose#3945]
Hey guys, didn't find similar issue, so sorry if duplicating.
But it seems like docker-compose down does not clean networks...
It would be pretty helpfull stuff in my case.
Thanks.

Docker version 1.12.1, build 23cf638
docker-compose version 1.8.0, build 94f7016

**Comment by aanand** [comment]
`docker-compose down` should remove networks. If it doesn't, that's a bug. Can you post a failing case?

**Comment by Fattaf** [comment]
OMG sorry.
My bad. 
I just was doing:
`docker-compose stop`
`docker-compose rm`
Thanks a lot.)
