### ISSUE TITLE
Container already exist

### ISSUE THREAD

**Issue by pcastrotigre** [docker/compose#3946]
Hi... I am trying to run a container 

![image](https://cloud.githubusercontent.com/assets/2748936/18482823/5446bd30-79a7-11e6-803e-fa6b3ac4a6c6.png)

However I receive an error that it already exist even when I list all of the containers with docker ps and there is no container listed. 

The line inside the script is 

`docker run --name ldap-service --hostname ldap-service --detach osixia/openldap:1.1.1`

**Comment by shin-** [comment]
Hi @pcastrotigre 

`docker ps` only shows running containers. To see a list of all your containers, you should use `docker ps -a` - I'm quite confident the `ldap-service` will show up among them.

The simple solution here is of course to run `docker rm -f ldap-service` to remove the old container, and run your script again.

HTH!

**Comment by pcastrotigre** [comment]
It worked great... Thanks
