### ISSUE TITLE
docker compose & health check

### ISSUE THREAD

**Issue by a1exus** [docker/compose#3948]
I'm looking and I can't find anything in order to implement [HEALTHCHECK](https://docs.docker.com/engine/reference/run/#/healthcheck) using docker-compose.

```
$ docker-compose --version
docker-compose version 1.8.0, build f3628c7
$ 
```

Please advise.

**Comment by shin-** [comment]
Please see #3754 - I'm going to close this issue as a duplicate, but feel free to contribute to the discussion in that other ticket.

**Comment by a1exus** [comment]
I'm not looking into _dependencies_ and/or _readiness_ of container. I'm looking how to implement following into _docker-compose.yaml_:

```
# docker run --help | grep health
      --health-cmd string           Command to run to check health
      --health-interval duration    Time between running the check
      --health-retries int          Consecutive failures needed to report unhealthy
      --health-timeout duration     Maximum time to allow one check to run
      --no-healthcheck              Disable any container-specified HEALTHCHECK
# docker --version
Docker version 1.12.0, build 8eab29e
#
```

**Comment by shin-** [comment]
#3854 is mentioned in that ticket and is an implementation proposal for exactly this.

**Comment by a1exus** [comment]
> "AttributeError: 'ProjectError' object has no attribute 'msg'" with no such file or directory #3854

really?

**Comment by shin-** [comment]
Sorry, mistyped. I meant #3815
