### ISSUE TITLE
Feature Request: Add --file parameter to docker-compose up

### ISSUE THREAD

**Issue by pcgeek86** [docker/compose#3952]
In the `docker build` command, you can specify an alternate Docker file name using the `--file` parameter. It would be great if `docker-compose up` supported the same concept. 

Docker Compose Version: 1.8.0

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by shin-** [comment]
Hi @pcgeek86 - I may be misunderstanding the request, but I believe that's exactly what the `-f` option does. Please clarify if that's not the case!

**Comment by pcgeek86** [comment]
@shin- Thanks, sorry I realized this after the fact. There's just some inconsistency because this is a global parameter on Docker Compose. On `docker`, it's specific to a child context. 

I was confused, because when you type `docker-compose build -h`, or any other child command besides `build`, these global parameters are not emitted in the help. Can you have context-specific help also show globally applicable parameters? 

Hope this all makes sense. :)
