### ISSUE TITLE
DCO/NO label not getting removed

### ISSUE THREAD

**Issue by CarstenHoyer** [docker/compose#3958]
https://github.com/docker/compose/pull/3939

I created a pull request. It git the label dco/no because it wasn´t signed.
I then got it signed and forced push an amend.
The dco/no label was removed by the nice turtle.

I then switched to a different computer, made some changes and forced pushed another amend.
This time the commit was not signed, so the turtle reapplied the dco/no label.

I then fixed my key issues and forced pushed yet another amend.
This time the dco/no seems to not go away again.

**Comment by shin-** [comment]
Yeah, the bot is quirky like that sometimes. I wouldn't worry too much about it. I removed the label manually.
