### ISSUE TITLE
On docker1.12,How to use compose on swarm mode,without docker-machine

### ISSUE THREAD

**Issue by xiaoxuan220** [docker/compose#3965]
*************************************************
[root@NODE01 ~]# docker -v
Docker version 1.12.1, build 23cf638
*************************************************
[root@NODE01 ~]# docker-compose -v
docker-compose version 1.8.0, build f3628c7
*************************************************
centos 7
[root@NODE01 ~]# uname -a
Linux NODE01 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
**************************************************

I don`t want to use docker-machine,but I want to use compose on swarm mode,I mean let container run on swam node.How to realize?Tks

**Comment by shin-** [comment]
Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.
To deploy your application across the swarm, use the bundle feature of the Docker experimental build.
More info: https://docs.docker.com/compose/bundles

**Comment by xiaoxuan220** [comment]
@shin- Thanks,but in my environment docker is not 'deploy' parameter.I have to do something?
-----------------------------------------------------------------------------------------------------------
[root@swarmmaster ~]# docker -v
Docker version 1.12.1, build 23cf638
------------------------------------------------------------------------------------------------------------
[root@swarmmaster ~]# docker --help
Usage: docker [OPTIONS] COMMAND [arg...]
       docker [ --help | -v | --version ]

A self-sufficient runtime for containers.

Options:

  --config=~/.docker              Location of client config files
  -D, --debug                     Enable debug mode
  -H, --host=[]                   Daemon socket(s) to connect to
  -h, --help                      Print usage
  -l, --log-level=info            Set the logging level
  --tls                           Use TLS; implied by --tlsverify
  --tlscacert=~/.docker/ca.pem    Trust certs signed only by this CA
  --tlscert=~/.docker/cert.pem    Path to TLS certificate file
  --tlskey=~/.docker/key.pem      Path to TLS key file
  --tlsverify=true                Use TLS and verify the remote
  -v, --version                   Print version information and quit

Commands:
    attach    Attach to a running container
    build     Build an image from a Dockerfile
    commit    Create a new image from a container's changes
    cp        Copy files/folders between a container and the local filesystem
    create    Create a new container
    diff      Inspect changes on a container's filesystem
    events    Get real time events from the server
    exec      Run a command in a running container
    export    Export a container's filesystem as a tar archive
    history   Show the history of an image
    images    List images
    import    Import the contents from a tarball to create a filesystem image
    info      Display system-wide information
    inspect   Return low-level information on a container, image or task
    kill      Kill one or more running containers
    load      Load an image from a tar archive or STDIN
    login     Log in to a Docker registry.
    logout    Log out from a Docker registry.
    logs      Fetch the logs of a container
    network   Manage Docker networks
    node      Manage Docker Swarm nodes
    pause     Pause all processes within one or more containers
    port      List port mappings or a specific mapping for the container
    ps        List containers
    pull      Pull an image or a repository from a registry
    push      Push an image or a repository to a registry
    rename    Rename a container
    restart   Restart a container
    rm        Remove one or more containers
    rmi       Remove one or more images
    run       Run a command in a new container
    save      Save one or more images to a tar archive (streamed to STDOUT by default)
    search    Search the Docker Hub for images
    service   Manage Docker services
    start     Start one or more stopped containers
    stats     Display a live stream of container(s) resource usage statistics
    stop      Stop one or more running containers
    swarm     Manage Docker Swarm
    tag       Tag an image into a repository
    top       Display the running processes of a container
    unpause   Unpause all processes within one or more containers
    update    Update configuration of one or more containers
    version   Show the Docker version information
    volume    Manage Docker volumes
    wait      Block until a container stops, then print its exit code

Run 'docker COMMAND --help' for more information on a command.

**Comment by shin-** [comment]
You're going to need the experimental build that can be obtained from
https://experimental.docker.com

**Comment by xiaoxuan220** [comment]
@shin- I has try this,as you suggest.but they prompt I has installed docker.
information such as:
*****************************************************************************************
[root@NODE03 ~]# sh docker11.sh 
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
+ sh -c 'sleep 3; yum -y -q install docker-engine'
https://yum.dockerproject.org/repo/experimental/centos/7/repodata/repomd.xml: [Errno 12] Timeout on https://yum.dockerproject.org/repo/experimental/centos/7/repodata/r
epomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')Trying other mirror.
https://yum.dockerproject.org/repo/experimental/centos/7/repodata/repomd.xml: [Errno 12] Timeout on https://yum.dockerproject.org/repo/experimental/centos/7/repodata/r
epomd.xml: (28, 'Connection timed out after 30001 milliseconds')Trying other mirror.
https://yum.dockerproject.org/repo/experimental/centos/7/repodata/repomd.xml: [Errno 12] Timeout on https://yum.dockerproject.org/repo/experimental/centos/7/repodata/r
epomd.xml: (28, 'Connection timed out after 30000 milliseconds')Trying other mirror.
https://yum.dockerproject.org/repo/experimental/centos/7/repodata/repomd.xml: [Errno 12] Timeout on https://yum.dockerproject.org/repo/experimental/centos/7/repodata/r
epomd.xml: (28, 'Connection timed out after 30002 milliseconds')Trying other mirror.
https://yum.dockerproject.org/repo/experimental/centos/7/repodata/repomd.xml: [Errno 12] Timeout on https://yum.dockerproject.org/repo/experimental/centos/7/repodata/r
epomd.xml: (28, 'Connection timed out after 30002 milliseconds')Trying other mirror.
https://yum.dockerproject.org/repo/experimental/centos/7/repodata/repomd.xml: [Errno 12] Timeout on https://yum.dockerproject.org/repo/experimental/centos/7/repodata/r
epomd.xml: (28, 'Connection timed out after 30000 milliseconds')Trying other mirror.
https://yum.dockerproject.org/repo/experimental/centos/7/repodata/repomd.xml: [Errno 12] Timeout on https://yum.dockerproject.org/repo/experimental/centos/7/repodata/r
epomd.xml: (28, 'Operation timed out after 30000 milliseconds with 0 out of 0 bytes received')Trying other mirror.
https://yum.dockerproject.org/repo/experimental/centos/7/repodata/repomd.xml: [Errno 12] Timeout on https://yum.dockerproject.org/repo/experimental/centos/7/repodata/r
epomd.xml: (28, 'Connection timed out after 30001 milliseconds')Trying other mirror.
https://yum.dockerproject.org/repo/experimental/centos/7/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: yum.dockerproject.org; Unknown error"
Trying other mirror.
Package docker-engine-1.12.1-1.el7.centos.x86_64 already installed and latest version
+ sh -c 'docker version'
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!
********************************************************************************************
[root@NODE03 ~]# docker --help
Usage: docker [OPTIONS] COMMAND [arg...]
       docker [ --help | -v | --version ]

A self-sufficient runtime for containers.

Options:

  --config=~/.docker              Location of client config files
  -D, --debug                     Enable debug mode
  -H, --host=[]                   Daemon socket(s) to connect to
  -h, --help                      Print usage
  -l, --log-level=info            Set the logging level
  --tls                           Use TLS; implied by --tlsverify
  --tlscacert=~/.docker/ca.pem    Trust certs signed only by this CA
  --tlscert=~/.docker/cert.pem    Path to TLS certificate file
  --tlskey=~/.docker/key.pem      Path to TLS key file
  --tlsverify                     Use TLS and verify the remote
  -v, --version                   Print version information and quit

Commands:
    attach    Attach to a running container
    build     Build an image from a Dockerfile
    commit    Create a new image from a container's changes
    cp        Copy files/folders between a container and the local filesystem
    create    Create a new container
    diff      Inspect changes on a container's filesystem
    events    Get real time events from the server
    exec      Run a command in a running container
    export    Export a container's filesystem as a tar archive
    history   Show the history of an image
    images    List images
    import    Import the contents from a tarball to create a filesystem image
    info      Display system-wide information
    inspect   Return low-level information on a container, image or task
    kill      Kill one or more running containers
    load      Load an image from a tar archive or STDIN
    login     Log in to a Docker registry.
    logout    Log out from a Docker registry.
    logs      Fetch the logs of a container
    network   Manage Docker networks
    node      Manage Docker Swarm nodes
    pause     Pause all processes within one or more containers
    port      List port mappings or a specific mapping for the container
    ps        List containers
    pull      Pull an image or a repository from a registry
    push      Push an image or a repository to a registry
    rename    Rename a container
    restart   Restart a container
    rm        Remove one or more containers
    rmi       Remove one or more images
    run       Run a command in a new container
    save      Save one or more images to a tar archive (streamed to STDOUT by default)
    search    Search the Docker Hub for images
    service   Manage Docker services
    start     Start one or more stopped containers
    stats     Display a live stream of container(s) resource usage statistics
    stop      Stop one or more running containers
    swarm     Manage Docker Swarm
    tag       Tag an image into a repository
    top       Display the running processes of a container
    unpause   Unpause all processes within one or more containers
    update    Update configuration of one or more containers
    version   Show the Docker version information
    volume    Manage Docker volumes
    wait      Block until a container stops, then print its exit code

Run 'docker COMMAND --help' for more information on a command.
