### ISSUE TITLE
got an unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by mkungla** [docker/compose#3973]
on Fedora 25 `4.8.0-0.rc7.git0.1.fc25.x86_64` I get following error with 
`docker-compose up -d`

```bash
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 61, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 110, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 35, in project_from_options
    environment=environment
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 110, in get_project
    host=host, environment=environment
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 82, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/lib/python2.7/site-packages/compose/cli/docker_client.py", line 73, in docker_client
    return Client(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'user_agent'
```

**Comment by gelin** [comment]
Got the same with the simplest docker-compose.yml.
```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 62, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 111, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 35, in project_from_options
    environment=environment
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 110, in get_project
    host=host, environment=environment
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/command.py", line 82, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/docker_client.py", line 80, in docker_client
    return Client(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'user_agent'
```
```
sudo docker-compose --version
docker-compose version 1.8.1, build 878cff1
```
```
sudo docker --version
Docker version 1.12.1, build 23cf638
```
```
version: '2'
services:
  consul:
    image: progrium/consul
    command: "-server -advertise 192.168.200.221 -join 192.168.200.221"
    restart: unless-stopped
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8302:8302'
      - '8302:8302/udp'
      - '8400:8400'
      - '8500:8500'
```

**Comment by mkungla** [comment]
here
```
docker-compose version 1.8.0, build 94f7016
Docker version 1.12.1, build 9a3752d/1.12.1
```

**Comment by shin-** [comment]
Hi!
I'm not sure how you ended up in that situation, but it looks like you need to upgrade the `docker-py` library to 1.9.0+ (ideally, use the latest 1.10.3).

Our `requirements.txt` and `setup.py` spell those minimum requirements clearly but `pip` or something else might have missed them during the upgrade. Just `pip install --upgrade 'docker-py>=1.9.0'` and you'll be set.

**Comment by mkungla** [comment]
> Just pip install --upgrade 'docker-py>=1.9.0' and you'll be set.

That worked thanks.

> I'm not sure how you ended up in that situation

I installed docker and docker-compose with dnf on f25

**Comment by shin-** [comment]
@mkungla Did you have a previous version installed on the same machine?

cc @lsm5 Do you have an idea what could have caused this?

**Comment by mkungla** [comment]
@shin- no I just installed both docker and  docker-compose with `dnf`, but since f25 is still in Alpha and I'm messing around with py and kernel-headers a lot so therefore I may have caused that issue by my self... therefore I can't confirm that this is reproducible on fresh install of f25.

**Comment by lsm5** [comment]
I emailed Michael Hampton (rpm maintainer) about this. Can't seem to find his github id

**Comment by error10** [comment]
F25 is prerelease, `dnf update` your system.

**Comment by mkungla** [comment]
@error10 first of the update command is deprecated in favor of upgrade and I installed and been using f25 about month now and of course I did `dnf upgrade` before installing docker and docker-compose

**Comment by error10** [comment]
@mkungla OK, I was able to reproduce the issue. But I don't maintain python-docker-py in Fedora. It probably needs to be the release rather than a release candidate. Or better yet just brought current.

**Comment by lsm5** [comment]
On Sat, Sep 24, 2016 at 11:46:09AM -0700, error10 wrote:
> @mkungla OK, I was able to reproduce the issue. But I don't maintain python-docker-py in Fedora. It probably needs to be the release rather than a release candidate. Or better yet just brought current.
> 

ping @TomasTomecek

-- 
Lokesh
Freenode: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by TomasTomecek** [comment]
This is the reason we don't have docker-py-1.10 in Fedora, yet: https://bugzilla.redhat.com/show_bug.cgi?id=1373386 I'll try to package https://github.com/shin-/dockerpy-creds this week so we can have newest docker-py & docker-compose in F25.

Regarding the weird rc release of 1.9 in F25, I likely expected that F25 inherits final 1.9 from rawhide (but apparently F25 already branched from rawhide), here's a final 1.9 build: http://koji.fedoraproject.org/koji/taskinfo?taskID=15804903

**Comment by mkungla** [comment]
@TomasTomecek nice, if you need help or testing let me know [FAS](https://admin.fedoraproject.org/accounts/user/view/kungla)

**Comment by TomasTomecek** [comment]
@mkungla I've just provided updates for Fedora 25 so feel free to test those:
https://bodhi.fedoraproject.org/updates/FEDORA-2016-9a3a8e9dd8
https://bodhi.fedoraproject.org/updates/FEDORA-2016-d88935f336

These should fix the issue as they provide latest docker-py and docker-pycreds. Hence I believe we can close this.

**Comment by mkungla** [comment]
@TomasTomecek nice one indeed this issue can be closed
