### ISSUE TITLE
Possibility to use --no-cache for a single service  

### ISSUE THREAD

**Issue by bwnyasse** [docker/compose#3976]
Actually , we can use the instruction **docker-compose build --no-cache** to avoid using the cache.

For instance , if we have the following docker-compose file 

<pre>
version: '2'
services:
  service1:
    build:
      context: .
    container_name: service1_cont_name
  service2:
    build:
      context: .
    container_name: service2_cont_name
</pre>

If we need to apply --no-cache only for service1 , it will be usefull to have an option in the **build** instruction to define this kind of action.

**Comment by shin-** [comment]
Hi!

You can already do this through `docker-compose build --no-cache service1`. I'm not sure I agree that `no-cache` should be part of the configuration.

**Comment by bwnyasse** [comment]
Hi @shin-  , <pre>docker-compose build --no-cache service1</pre> will only build service1 .
But assuming that I have a lot of services defined in my docker-compose file , this command won't be enough. 
So the workaround would be to identify the service that required the **no-cache** option and rebuild all the services ? 

<pre>docker-compose build --no-cache service1 && docker-compose build</pre> ?

**Comment by shin-** [comment]
Yes, that would be the way to go about it.

**Comment by bwnyasse** [comment]
So , I think It wouldbe more understandable to avoid running two commands for this kind of purpose. Why not adding a specific option in the **build** instruction, something like

<pre>
version: '2'
services:
  service1:
    build:
      context: .
      cache: false
    container_name: service1_cont_name
  service2:
    build:
      context: .
    container_name: service2_cont_name
</pre>

Assuming the default value of **cache** is **true** . I think it would make more sense for the docker-compose file.
