### ISSUE TITLE
Docker-compose stops all running containers

### ISSUE THREAD

**Issue by shoegazerwithak** [docker/compose#3981]
Expected behavior: `docker-compose stop` stops containers defined in docker-compose.yml
Unexpected behavior: `docker-compose stop` stops all running containers

System information
Docker-compose:

```
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

Kernel

`Linux 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Ubuntu Release

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

**Comment by samuzzal** [comment]
Would you provide your docker-compose version and Operating System's name and version? I could not reproduce that on my Fedora 23 system.

**Comment by shoegazerwithak** [comment]
@samuzzal I updated my post.

**Comment by shin-** [comment]
Can you clarify what you mean by "all running containers"? Do you have a reproducible case you can share?

**Comment by samuzzal** [comment]
Unfortunately, I could not replicate your scenario with the same setup.
