### ISSUE TITLE
Interpolate variables in environment variables definition with docker-compose.yml

### ISSUE THREAD

**Issue by bwnyasse** [docker/compose#3993]
It would be usefull if you add the capability to interpolate env vars when using docker-compose . if I have a following **vars.env** file :

<pre>
VAR_1=value_1
VAR_2=value_1/value2
VAR_3=value_1/value3
</pre>

It would be more maintainable to interpolate **VAR_1 value** like this 

<pre>
VAR_1=value_1
VAR_2=${VAR_1}/value2
VAR_3=${VAR_1}/value3
</pre>

What do you think ?

**Comment by aanand** [comment]
I can see the utility, but this would add a fair bit of complexity to the env file parser. More importantly, it's not supported by `docker run --env-file`, and we should maintain parity with Engine first and foremost.
