### ISSUE TITLE
Allow hyphens (dashes) in COMPOSE_PROJECT_NAME

### ISSUE THREAD

**Issue by kachkaev** [docker/compose#4002]
The services defined in `docker-compose.yml` allow hyphens in their name, which means that the resulting containers can obtain the following names:

```
myproject_some-service_1
myproject_some-other-service_1
```

However, when it is attempted to use `COMPOSE_PROJECT_NAME=my-project` instead of `myproject`, the names of the services do not change to the following:

```
my-project_some-service_1
my-project_some-other-service_1
```

The cause is [this line in `command.py`](https://github.com/docker/compose/blob/267a243f80817025d2fe0cebc603939f78841736/compose/cli/command.py#L120):

``` py
 return re.sub(r'[^a-z0-9]', '', name.lower())
```

I might be wrong, but there seems to be no reason for having inconsistent naming restrictions in different parts of the resulting container name. Could be go for this?

``` py
 return re.sub(r'[^a-z0-9-]', '', name.lower())
```

Some of my projects `haveprettylongnamesanditbecomeshardtoreadthemwithouthyphens`. `this-could-be-improved`.

**Comment by kachkaev** [comment]
Exactly the same problem applies to underscores at the moment:
```
#possible
myproject_some_service_1
myproject_some_other_service_1

#not possible
my_project_some_service_1
my_project_some_other_service_1
```

Although I'm a supporter of using hyphens and underscores for different purposes, I still don't see why different rules should be applied to different parts of the name. A complete fix would look like this:
```py
 return re.sub(r'[^a-z0-9_-]', '', name.lower())
```

**Comment by shin-** [comment]
@aanand Do you remember if there was a specific reason for stripping out those characters in project names?

**Comment by villlem** [comment]
There is closed PR #572 for this. But since a project is tracked via label this reason is out.

**Comment by kachkaev** [comment]
Could a little patch that resolves this issue be included in the next minor release then please?

**Comment by hopeseekr** [comment]
This is super annoying as a distributor.

What if the user already has a "lamp_1" container?? I try to prefix it with my project name and it comes out "phpexpertslamp_1", which is far from ideal.

Yet there's no recourse ATM, going on a year and half.

**Comment by shin-** [comment]
Fixed by #5788

**Comment by ajmueller** [comment]
I, like many others (I assume), had named volumes they were using with Docker Compose.  I tried going through a lengthy process of renaming the volume using [this script](https://codegists.com/snippet/shell/docker-rename-volume_danhawkes_shell) and [this forum post](https://forums.docker.com/t/host-path-of-volume/12277) to figure out how to move my data from one volume to another.  Somehow running the command to move the data directories resulted in a complete loss of all of my volume's data and I don't know why.

Is there an official recommended means of renaming volumes?  This seems like something that should be relatively straightforward to accomplish, but the last hour and a half of my searching and testing shows that's not the case.

**Comment by shin-** [comment]
@ajmueller I can't speak to third party scripts, but the upcoming 1.21.1 should handle the migration correctly. See #5874 for more information

**Comment by ajmueller** [comment]
Thanks, @shin-.  It looks like `docker cp` would have been an option then.

If anyone happens across this and needs another option, [this script](https://github.com/loomchild/volume-backup) might do the trick.  **DISCLAIMER** I didn't try it personally, but it looks like it should do the trick.

**Comment by mmiszy** [comment]
This is actually a HUGE breaking change 😱
I think you should revert it in 1.21.2 and rerelease as 1.22 or even 2.0.0 (if you follow semver).

**Comment by catmeme** [comment]
Any build system that makes the assumption that an underscore is the delimiter between projectname, and container will be broken by this change.
