### ISSUE TITLE
Install Docker Engine links are broken

### ISSUE THREAD

**Issue by bayboraoren** [docker/compose#4003]
in https://github.com/docker/compose/blob/master/docs/install.md
....
Mac OS X installation
Windows installation
Ubuntu installation
other system installations

**Comment by shin-** [comment]
Sorry about that! It's meant to be read from [here](https://docs.docker.com/compose/install/).

**Comment by shin-** [comment]
With the documentation moving to the new [docs repo](https://github.com/docker/docker.github.io) I believe this can be closed.
