### ISSUE TITLE
force-recreate doesn't respect service dependencies

### ISSUE THREAD

**Issue by EvgenyOrekhov** [docker/compose#4017]
`docker-compose stop` and `docker-compose down` stop the services in the order defined by the "depends_on" property in the `docker-compose.yml`, but `docker-compose up --force-recreate` stops the services in the wrong order.

Docker version: 1.12.1, build 23cf638
Docker Compose version: 1.8.1, build 878cff1

**Comment by whitebyte** [comment]
2019, still actual

**Comment by whitebyte** [comment]
Umm, ping, I guess?.. The fact it's not fixed is not a reason to just close the issue

**Comment by mirceaulinic** [comment]
This issue still happens, it seems.
