### ISSUE TITLE
Compose does not allow `build` to be supplied as an object

### ISSUE THREAD

**Issue by brentsmyth** [docker/compose#4018]
Hey!

[According to the docs](https://docs.docker.com/compose/compose-file/#/build) `build` should be able to be supplied as an object where `context` defines the path.  Though I get the following error with the latest version of compose...

```
$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
web.build contains an invalid type, it should be a string

$ docker-compose --version
docker-compose version 1.8.0, build f3628c7
```

My `docker-compose.yml` file looks like this...

```
web:
  build:
    context: .
    dockerfile: Dockerfile-dev
  ports:
    - "8000:8000"
  environment:
    ENV: dev
```

It seems like I am doing this correctly... Is this feature not in 1.8.0 by chance?

**Comment by shin-** [comment]
Hi!
You're using the version 1 file format, which doesn't support this structure. You should convert your `docker-compose.yml` to version 2 (you're almost there already). You can see our docs on versioning [here](https://docs.docker.com/compose/compose-file/#versioning)

**Comment by brentsmyth** [comment]
Ah yes... that was it thanks!  I sort of got my feet wet with an outdated tutorial and then dived straight into the reference manual for build here ... https://docs.docker.com/compose/compose-file/#/build  Missed any point that would let me know to specify that :P

**Comment by brentsmyth** [comment]
I'll close this up because the page does point this out... I just never read it :P
