### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by suliangxd** [docker/compose#4022]
## Daemon socket to connect to a swarm master node, Sometimes an error occurs！But, sometimes it's success!

---
### my command

`docker-compose -H 10.99.226.22:8100 --skip-hostname-check --tlsverify --tlscacert /home/work/client/ca.pem --tlscert /home/work/client/localCRT.pem --tlskey /home/work/client/localKEY.pem -f /home/work/compose/yaml/yueguangbin/49.yaml -p 097651e1110c4e4788f2e4001a5a7b600000000049 up -d --remove-orphans`  

---
### the error message

Creating network "fc5ac3ef75e241968054db25f0d2ea5a0000000049_default" with the default driver

ERROR: for tomcat  No JSON object could be decoded
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 400, in up
  File "compose/parallel.py", line 64, in parallel_execute
ValueError: No JSON object could be decoded
docker-compose returned -1

**Comment by shin-** [comment]
Hi! Which version of docker-compose are you using? Try upgrading to docker-compose 1.8.1 if you aren't already.

**Comment by suliangxd** [comment]
@shin-This is what I am using, version 1.8.0

**Comment by aanand** [comment]
@suliangxd You're not on the latest version, then - try [1.8.1](https://github.com/docker/compose/releases/tag/1.8.1), which contains a fix which might be what you need ("Fixed an issue where Compose would crash when encountering an API error while streaming container logs").
