### ISSUE TITLE
Apparmor "no such file or directory"

### ISSUE THREAD

**Issue by dsyer** [docker/compose#403]
```
$ fig up
Recreating <xxx>...
Cannot start container a3e4fd060d01a12ab7f810a91a341a44a5f9414fb814a3d29d8229bbb4dd3004: set apparmor profile docker-default: no such file or directory
```

This change to docker claims to have fixed the problem: https://github.com/docker/docker/pull/6180, but it's still failing for me.

```
$ docker -v
Docker version 1.1.2, build d84a070
$ fig --version
fig 0.5.2
```

**Comment by k2xl** [comment]
Note that I had this same issue and it turned out to be that fig will complain with that message if volumes are not listed as an array. Might be a good idea if fig explained that it was an error in the fig syntax.

volumes: blah

bad.

volumes:
  - blah

good

**Comment by kidphys** [comment]
I have the save issue on a very simple yml:
```
redis:
  image: redis
```
on
```
docker-compose 1.1.0
Docker version 1.4.1, build 5bc2ff8
```
Error message:
```
Recreating <xxx>...
Cannot start container d924a8cab330fde589a63a5982bf9bd099ff464b1999640dc48ee4e0e289b926: set apparmor profile docker-default: no such file or directory
```
My host is Ubuntu precise inside a Vagrant box:
```
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:        12.04
Codename:       precise
```
Any idea?

**Comment by groteck** [comment]
Same here:
``` yml
cfg2:
  build: .
  ports:
    - "3000:3000"
    - "2222:22"
```

In ubuntu 14.04

**Comment by groteck** [comment]
My problem was solved with the next steps:

1. Update docker from 1.4 to 1.5.
2. Add my user to docker user group for run docker without sudo.
3. Destroy all the images.
4. Rebuild.

I think the problem was than I used a image generated with docker 1.4.
