### ISSUE TITLE
compose bundle cannot support volume？

### ISSUE THREAD

**Issue by fsword** [docker/compose#4033]
When I use docker compose to define my services, I can set up volume mapping. But bundle command does not support the feature, is there another way to do the same thing?

**Comment by fsword** [comment]
If the things is what I understand, DAB is a tool for lock version for production. So it should be used by compose/swarm online ?

**Comment by shin-** [comment]
Please note that bundles are still an experimental feature - using it for production is inherently risky.

That said, I don't think there is currently a way to specify volumes with DAB files. Please follow issue #3735 for more information as it becomes available.
