### ISSUE TITLE
Failed to kill docker-compose process

### ISSUE THREAD

**Issue by garveen** [docker/compose#4046]
I am writing a plugin which can manage docker-compose in a software. All non-interactive docker-compose commands are working good, except `up` and `logs -f`: they have a continuous output.

In my computer, docker-compose uses two process to do all the jobs. If I kill the first which I can get the pid from APIs, the second one will not exit and became a dummy process. This also happened with Windows Task Manager.

Environment:
Windows 10 Pro 14393
Docker 1.12.2-beta28(7813)
docker-compose 1.8.1, build 004ddae

**Comment by yaroslav-shabalin** [comment]
+1 for this issue. 

Also seems to be the same for Linux. What is the proper way to terminate "docker-compose logs -f" process that is running in background? Killing the process by PID still leaves container active:

docker-compose logs -f &
kill $!            #this doesn't work

**Comment by pashist** [comment]
Same issue on Windows. Spawned `docker-compose logs -f` using node `child_process.spawn` method. Created 2 docker-compose processes. After calling `ps.kill()` closed only one. When i do same from console, 2 processes also created, but 2 stopped after terminating.
`docker-compose version 1.11.2, build f963d76f`
`Docker version 17.03.1-ce, build c6d412e`

**Comment by GregorioDiStefano** [comment]
Experiencing the same here. 
2 processes are created, and under some circumstances, the process don't quit.
