### ISSUE TITLE
Support for `--device-read/write-bps/iops` and `blkio_weight_device` flags

### ISSUE THREAD

**Issue by joshwget** [docker/compose#4056]
Docker Compose doesn't currently have fields for the following Docker flags:
- `--device-read-bps`
- `--device-read-iops`
- `--device-write-bps`
- `--device-write-iops`
- `--blkio_weight_device`

**Comment by shin-** [comment]
Thanks for the report!
(For reference, https://github.com/docker/docker-py/blob/1.10.4/docker/utils/utils.py#L828-L879)

**Comment by joshwget** [comment]
I know there's an issue open for `blkio_weight`, but I haven't seen anything for `blkio_weight_device` so far. I can add that to this issue or create a new one.

**Comment by shin-** [comment]
I consider them part of the same set, so feel free to add it to the list. (Link to the docker-py code is mostly for self-reference).

**Comment by joshwget** [comment]
Okay, updated the issue. Thanks @shin-.

**Comment by sztwiorok** [comment]
+1
any update on this?

**Comment by heikobornholdt** [comment]
another +1
any update on this? 😀
