### ISSUE TITLE
I am trying to scale a selenium/node-chrome-debug using the docker-compose. How do I expose host ports for the containers on the fly or some way to expose the host ports? 

### ISSUE THREAD

**Issue by yashassai** [docker/compose#4074]
version: '2'
services :
  hub:
    image: selenium/hub
    hostname: hub
    ports:
    - "4446:4444"
    environment:
    - no_proxy=localhost

  chrome:
    image: selenium/node-chrome-debug
    hostname: chrome
    links:
      - hub
    ports:
    - "5901:5900"
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

**Comment by yashassai** [comment]
Above is my docker-compose file

**Comment by shin-** [comment]
Why do you want to expose host ports between containers? With version 2, services are part of the same network by default, so they can access each other using their open ports and service names as hostnames. Please refer to the networking docs here: https://docs.docker.com/compose/networking/
