### ISSUE TITLE
docker swarm does not update images when it is a mode global

### ISSUE THREAD

**Issue by fuentecilla86** [docker/compose#4077]
docker version

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
afuentes@chimera-swarm-dev-db-01:~$ sudo docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64
```

I have declared a service with mode global and with a constraint to run it only in two servers (my cluster runs in 3 servers). When I try to update as following:

```
sudo docker service update --image $IMAGE:$TAG $SERVICE
```

**The service is not updated.**

If I do it with in "replicas" mode it works perfectly.

Thank you in advance.

**Comment by shin-** [comment]
Did you mean to create this on [docker/docker](https://github.com/docker/docker/issues) ?

**Comment by fuentecilla86** [comment]
Yes, I'm so sorry because of that! I am going to create it there!

Thank you!

**Comment by shin-** [comment]
No harm done! :)

I'll close this for the time being.
