### ISSUE TITLE
Cannot link to a non running container: /41b06ab0d5ce_blockai_minio_1 AS /blockaiapi_createbucket_1/minio

### ISSUE THREAD

**Issue by olalonde** [docker/compose#4079]
I am getting the following error after running `docker-compose up createbucket`:

``` bash
$ docker-compose up createbucket
Starting blockaiapi_createbucket_1

ERROR: for createbucket  Cannot start service createbucket: Cannot link to a non running container: /41b06ab0d5ce_blockai_minio_1 AS /blockaiapi_createbucket_1/minio
ERROR: Encountered errors while bringing up the project.
```

My docker-compose.yml:

``` yaml
createbucket:
  image: garland/aws-cli-docker
  external_links:
    - blockai_minio_1:minio
  command: >
    /bin/sh -c "
      while ! wget -q -s http://minio:9000/minio/login; do sleep 1; done;
      aws configure set default.s3.signature_version s3v4;
      aws configure set default.region us-east-1;
      aws s3api create-bucket \
        --bucket filepunk-test \
        --endpoint-url=http://minio:9000;
      exit 0;
    "
  environment:
    - "AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE"
    - "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
```

I verified that `blockai_minio_1` is running. It was started from a separate docker-compose.yml file.

```
$ docker ps | grep blockai_minio_1
5fbb57067b9e        minio/minio          "go-wrapper run serve"   6 minutes ago    Up 6 minutes        0.0.0.0:9000->9000/tcp   blockai_minio_1
```

Why does it try to link to `/41b06ab0d5ce_blockai_minio_1` instead of `/blockai_minio_1`?

**Comment by olalonde** [comment]
Fixed by running `docker-compose rm createbucket` and trying again. I still think this is a bug.

**Comment by asimmanzoor** [comment]
I am getting same issue. 
My docker-compose.yml has below config: I follow below link to implement docker-compose

http://g00glen00b.be/docker-spring-boot/
"Introduction to Docker compose"


demo-mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_DATABASE=recservice
    - MYSQL_USER=demo_user
    - MYSQL_PASSWORD=demo_pass

rec-service:
  image: iqballone/recmicroserviceimage
  links:
    - demo-mysql:mysql
  ports:
    - 8081:8081



[ec2-user@ip-172-31-56-146 docker]$ docker-compose up
Starting docker_demo-mysql_1
Creating docker_rec-service_1

ERROR: for rec-service  Cannot start service rec-service: Cannot link to a non running container: /docker_demo-mysql_1 AS /docker_rec-service_1/demo-mysql_1
ERROR: Encountered errors while bringing up the project.

Here i am getting to container service as well.
[ec2-user@ip-172-31-56-146 docker]$ docker-compose ps
        Name                      Command                State     Ports
------------------------------------------------------------------------
docker_demo-mysql_1    docker-entrypoint.sh mysqld      Exit 1
docker_rec-service_1   java -jar /rec-service-0.0 ...   Exit 128

Note: I didn't found any output for "docker ps"

[ec2-user@ip-172-31-56-146 docker]$ docker ps
WARNING: Error loading config file:/home/ec2-user/.docker/config.json - EOF
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[ec2-user@ip-172-31-56-146 docker]$

**Comment by shin-** [comment]
@asimmanzoor It looks like the demo-mysql exited with code 1 (usually means something went wrong). I would try to diagnose by calling `docker-compose logs demo-mysql` to maybe identify what happened.

@olalonde Thanks for the report. You're right, it's worth looking into why Compose misidentified the container it was supposed to link to.

**Comment by johnny-human** [comment]
I had the same kind of error: for apache  Cannot start service apache: Cannot link to a non running container.

This worked for me.
I changed the docker-compose.yml file to version 2 and put the services under "services:" like this
```bash
version "2"

services:
   php: ...

   web: ...

   mysql: ...
```
