### ISSUE TITLE
Compose "Read time out" in swarm mode 

### ISSUE THREAD

**Issue by viveky4d4v** [docker/compose#4087]
I am using compose in swarm with overlay network , I use to get below error almost every ~4 commands - 

```
ERROR: for wsgi_2  HTTPSConnectionPool(host='192.168.99.91', port=3376):       Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting      COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

What's the reason for this & how we can get rid of this ?

**Comment by shin-** [comment]
Compose is apparently timing out when trying to contact the engine at `192.168.99.91` - Is this the correct address? Is the network stable? What command are you typically running when you get this error?

**Comment by viveky4d4v** [comment]
@shin- It occurred with "docker-compose up|down "  . 

I switched from docker compose in swarm to docker engine in swarm mode recently . Couldn't reproduce it anymore , i believe it happened due to wrong setup or network was unstable .

Thanks for your help !

**Comment by shin-** [comment]
Good to hear! Feel free to comment here if it pops up again - I'll close the ticket in the meantime.
