### ISSUE TITLE
Can I define a service in docker-compose.yml, which just need be extended, but not be started?

### ISSUE THREAD

**Issue by pinewong** [docker/compose#4093]
I want define a base service in `docker-compose.yml`, which need to be extended by other services.

But there is a question, when I run the command `docker-compose up`, I must to give all the services except it.

I know there is a solution by extends another file, but in a file, can it be solved?

**Comment by shin-** [comment]
The only way to do this currently is to use the [`extends` property](https://docs.docker.com/compose/extends/#/extending-services) for each of your services. You can put the base service in a file called `template.yml` or similar to make sure it won't be started by accident.

**Comment by pinewong** [comment]
OK, thx.
