### ISSUE TITLE
Windows + TLS + JetBrains

### ISSUE THREAD

**Issue by flamusdiu** [docker/compose#4094]
From what I can tell, is there seems to be zero way to disable TLS verification in Windows 10. If I set the options from the Docker for Windows GUI by adding: "tlsverify": false, the whole processes freezes then there is ZERO ways for me to fix that without a complete reinstall. I have some small projects that I am testing in docker due to not having Linux on a laptop that I am currently using.

**Comment by StefanScherer** [comment]
Docker for Windows does not use TLS. There is just a `com.docker.proxy.exe` listening on the Windows named pipe `//./pipe/docker_engine` that talks to the Docker socket `/var/run/docker.sock` in the MobyVM. There is no `127.0.0.1:2375` port. I don't know if JetBrains can handle the Windows named pipe (yet).

**Comment by flamusdiu** [comment]
So, the error in JetBrains is erroneous?

**Comment by shin-** [comment]
We can't really speak for JetBrains - have you contacted their support? In any case, I don't believe this issue is related to Compose in any way.
