### ISSUE TITLE
COMPOSE_FILE environment variable in Windows

### ISSUE THREAD

**Issue by hholst80** [docker/compose#4099]
The environment variable `COMPOSE_FILE` should allow me to use

`env COMPOSE_FILE=docker-compose.yml:docker-compose.admin.yml docker-compose pull`

but this fails on Windows with the error message: 

```
+ env COMPOSE_FILE=docker-compose.yml:docker-compose.admin.yml docker-compose pull
[31mERROR[0m: .IOError: [Errno 2] No such file or directory: u'.\\docker-compose.yml:docker-compose.admin.yml'
```

**Comment by shin-** [comment]
Isn't the semi-colon the proper path separator on Windows? I believe you would have to write `env COMPOSE_FILE=docker-compose.yml;docker-compose.admin.yml docker-compose pull` instead.

**Comment by hholst80** [comment]
I guess we are in for a surprise here then ;-)
```
 env COMPOSE_FILE=docker-compose.yml;docker-compose.admin.yml docker-compose
```

**Comment by hholst80** [comment]
tl,dr; Is it possible to support both colon and semicolon as file-path separator?

If we are using Bash in Windows and we type
```
echo $PATH
```
we don't see a a single colon either. Fair game if docker-compose is called from cmd.exe then I agree that semicolon would be warrented. But in bash scripts I expect the same scripts that work in Linux to work in Windows.

**Comment by shin-** [comment]
It's not possible because the colon in Windows environments has a different meaning (drive separator). Hope that makes sense!

**Comment by hholst80** [comment]
The suggested option `COMPOSE_FILE_SEPARATOR` should probably also be documented somewhere? Like here https://docs.docker.com/compose/reference/envvars/
