### ISSUE TITLE
UP behaviour >= 1.5.0

### ISSUE THREAD

**Issue by spaivaras** [docker/compose#4107]
Before docker-compose version 1.5.0 whenever running docker-compose up if a single container exited with non zero exit status all containers where stopped. This was a very useful feature for us. From v1.5.0 and up after container exits with non zero code, all other containers are still left alone.

Is there any option in later versions to restore the behavior of terminating all containers on a non zero exit code from a single container?

**Comment by shin-** [comment]
There is: `--abort-on-container-exit` ! See `docker-compose up --help` for more info.

**Comment by spaivaras** [comment]
Well yes, but abort on exit doesn't check the exit code. So exit code 0 also causes all containers to go down. for example if you have volumes only container. I am looking for a workaround or some tips on the old behaviour wich only aborts on non zero exit code

**Comment by johnharris85** [comment]
+1 for something like `--abort-on-container-failure` which seems like it would be much more useful.
