### ISSUE TITLE
--no-color does not disable colors on ERROR and WARNING logs

### ISSUE THREAD

**Issue by wsong** [docker/compose#4116]
`docker-compose up -d --no-color` still displays ERROR messages with the word "ERROR" in red and the word "WARNING" in yellow.

It would also be nice if compose respected the `CLICOLOR=0` env variable as a synonym for `--no-color`.

**Comment by glours** [comment]
Hi @wsong 
`--no-color` flag is used to remove coloration of container's logs, if you want to remove the CLI coloration, you can use the `--no-ansi` flag which will remove both the CLI & containers logs coloration
Btw I did a PR to match the CLICOLOR value if set 😉
