### ISSUE TITLE
How to manually install a Ruby gem using `fig run`

### ISSUE THREAD

**Issue by adelevie** [docker/compose#412]
Is this possible with the setup described in the Rails guide?

This is especially useful to debug any issues that pop up during a `bundle install`.

I'd like to run something like:

```sh
$ fig run ruby gem install some_gem -v '1.1.1'
```

**Comment by timdorr** [comment]
I believe I've solved this via [docker commit command to "cache" the image](https://github.com/docker/fig/issues/222#issuecomment-74607224) (#222)
