### ISSUE TITLE
apply by default custom.override.yml for `-f custom.yml`

### ISSUE THREAD

**Issue by whitecolor** [docker/compose#4121]
Out of the box compose tries to find and apply `docker-compose.override.yml`, why not make such feature for convinience for other files passed in `-f` option

So that `docker-compose -f docker-compose-dev.yml` would also try to lookup and apply `docker-compose-dev.override.yml`

**Comment by FernandoMiguel** [comment]
I came here for the same reason

I have the following
`$ docker-compose -f docker-compose.yml  -f docker-compose.local-services.yml -f docker-compose.local-services.override.yml config`

my understanding of override is that i would not need that last one
but if i dont had it, it doesn't work

could this feature be added to a future version of compose?

**Comment by ijc** [comment]
Thanks for the suggestion, however I think this would be a (potentially surprising) breaking change. I also think that once you are using `-f` to explicitly specify what you want it is better to be completely explicit rather than to have further implicit behaviours.
