### ISSUE TITLE
ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint ltg_db_1

### ISSUE THREAD

**Issue by jpca999** [docker/compose#4126]
when i do the following :   

± docker-compose up
Starting ltg_db_1

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint ltg_db_1 (ecc3bf3036508fade24ffa4d6bc3e5fee0180073c5351667c471922a10fad60f): Error starting userland proxy: Bind for 0.0.0.0:27017 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

![image](https://cloud.githubusercontent.com/assets/1026325/20086070/7f21508c-a53b-11e6-849a-98747a4d2b71.png)

![image](https://cloud.githubusercontent.com/assets/1026325/20086107/c5f84312-a53b-11e6-83d0-89a63f8b9646.png)

![image](https://cloud.githubusercontent.com/assets/1026325/20086116/d61688f8-a53b-11e6-8ddf-fca143d45e50.png)

± sudo docker inspect mongo
[
    {
        "Id": "sha256:135883d5d0b960b498e4c6c2009444b243b322d3fcb8fc4aa0cc741542dd6528",
        "RepoTags": [
            "mongo:latest"
        ],
        "RepoDigests": [
            "mongo@sha256:89ad0ed6321f48107356db1e11984e56614bdee64c3ad8a05484187f276ff705"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2016-11-01T23:31:04.120003872Z",
        "Container": "3e20e01de569b06a9cb43787870428254c585a56c2497835db2a616871db6f09",
        "ContainerConfig": {
            "Hostname": "397f80c505a4",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "27017/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "GPG_KEYS=DFFA3DCF326E302C4787673A01C4E7FAAAB2461C \t42F3E95A2C4F08279C4960ADD68FA50FEA312927",
                "MONGO_MAJOR=3.2",
                "MONGO_VERSION=3.2.10",
                "MONGO_PACKAGE=mongodb-org"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"mongod\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:389bcb7270fe1b576cabbf8c087b3400c5cde2f3da89be0620a42d9a5ab977fe",
            "Volumes": {
                "/data/configdb": {},
                "/data/db": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.12.2",
        "Author": "",
        "Config": {
            "Hostname": "397f80c505a4",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "27017/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "GPG_KEYS=DFFA3DCF326E302C4787673A01C4E7FAAAB2461C \t42F3E95A2C4F08279C4960ADD68FA50FEA312927",
                "MONGO_MAJOR=3.2",
                "MONGO_VERSION=3.2.10",
                "MONGO_PACKAGE=mongodb-org"
            ],
            "Cmd": [
                "mongod"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:389bcb7270fe1b576cabbf8c087b3400c5cde2f3da89be0620a42d9a5ab977fe",
            "Volumes": {
                "/data/configdb": {},
                "/data/db": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 342458197,
        "VirtualSize": 342458197,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:f96222d75c5563900bc4dd852179b720a0885de8f7a0619ba0ac76e92542bbc8",
                "sha256:38e11f990b2e156924ac65dca751984df46e2ee08e910f3d5022b2cf719347ca",
                "sha256:eafeecfceabdb3a4e1ca1102187836933e3ccc961739491a09e0363cf70b2f2e",
                "sha256:70c36fdd993b7f4a91e6917b321c20511b12df2e0bf83942ff462a5f0a28a466",
                "sha256:a03828149464bad8b594b6a08afb1f7203dc06da0b455cb12c50edd46ef668a5",
                "sha256:b54cfe80c0ff24ce4144c7d4b902020c582a261f214349093b8f19bd9a5d8673",
                "sha256:ec498496ec5310d8dec1e7d350da6d915b9f1cb27509892e6e6f18b7855303c0",
                "sha256:5031b34889a540514acc2cf9182cda58fef892f359086cb7d05004da033a53c8",
                "sha256:bde90abdc1c007d780ce1b34a692f9305b908cc7c0de3511d1d53f536e535570"
            ]
        }

**Comment by shin-** [comment]
` Bind for 0.0.0.0:27017 failed: port is already allocated`

You already have a container or application listening on the 27017 port on your machine, which prevents your service from allocating that port.

**Comment by jpca999** [comment]
i stopped all teh containers but still no solution. 
then i tried to delete al the containers and still no solution.

**Comment by AustinJuliusKim** [comment]
Bump! Having the same issue

**Comment by Donluigimx** [comment]
Same issue since I moved the project to another folder.

**Comment by jpca999** [comment]
@AustinJuliusKim   ive lost faith in Docker way of doing stuff.

**Comment by V-Tom** [comment]
Having the same issue

**Comment by onuryavuz** [comment]
Having the same issue. I've tried everything from removing all the containers, images to restarting docker and resetting to factory defaults. Nothing works.  When I try `docker-compose up` I'm getting the following error:
`ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint djangocelerypsql_db_1 (47ff2801a196bcd458bc2bc44af66797552dc82c06b7122ab04b3c4d7cb25261): Error starting userland proxy: Bind for 0.0.0.0:5432 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.`

`sudo netstat -p -nlp | grep 5432` returns nothing.

**Comment by surfertas** [comment]
Similar issue.

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint iotdemo_db_1 (7c482cab86489eb21c6884b1af49865a6b1760f0e53c20df1996824bc39af01e): Error starting userland proxy: listen tcp 0.0.0.0:8083: bind: address already in use

**Comment by aromasko** [comment]
I was getting the same error but was able to successfully continue after:
`service mongodb stop`

I'm a little confused (and new to docker & compose, to be quite honest) but shouldn't a db service running on the host not have a conflict with a db service running within a container?

**Comment by shin-** [comment]
@aromasko Not if you're trying to expose it on the same port on the host.

**Comment by liusining** [comment]
when I `docker network inspect MY_NETWORK`, I found an old container which was allocated with that port had not been removed. I guess that why the port could not be used for my new container.

Therefore, I removed the network with `docker network rm MY_NETWORK` and `docker-compose up -d` to recreate a network and restart all containers. Finally, it got fine.

**Comment by MaximusDesign** [comment]
Does anyone have a solution for this!?

**Comment by bfagundez** [comment]
Exact same issue, with redis. 
All other port mappings seem to work well, using db or redis fails on mac os.

**Comment by WesJones127** [comment]
I was getting this issue on Docker for Windows, both ports 5432 and 80.  I had a local instance of Postgres blocking 5432 and IIS was blocking port 80.  Stopping both of those services fixed the issue for me.

**Comment by katson95** [comment]
service mongodb stop worked for me

**Comment by knowdigital** [comment]
service mongodb stop worked for me - we had a mongodb running on the server which conflicted with the one running in the docker....

**Comment by raininja** [comment]
Yea I'm wondering as well, I can't open the darn ting

**Comment by pawelrudnicki** [comment]
I just used port mapping and problem has been solved. For example set mongo port 27018:27017 in docker-compose file.

**Comment by raininja** [comment]
I actually was using an older git version.  Updated and it worked just fine!

**Comment by samhstn** [comment]
For me doing the following worked

```bash
# find container id running on the desired port from the following output
docker container ls
# stop the container running on the desired port
docker stop <container-id>
```

**Comment by gingin77** [comment]
Similar to what is suggested here in the linked article, turning off MySQL in System Preferences is what worked for me. https://medium.com/code-wave/error-starting-userland-proxy-bind-for-0-0-0-0-3306-failed-port-is-already-allocated-docker-f2e430f68346

**Comment by i01107** [comment]
@samhstn You save my day

**Comment by Clipso** [comment]
i used service mongodb stop and it worked for me perfectly :)

**Comment by ShreyasDeshpande** [comment]
I was also facing the same issue. here are the steps I did to resolve the problem:
1) List all container :  docker ps -a
2) Stop all if not stopped : docker stop [containerid]
3) Remove containers : docker rm [containerid]
4) Now try to launch services with docker compose:  docker-compose up
Hope this will help  :)

**Comment by aayushagrawal135** [comment]
@ShreyasDeshpande, after the 4th step, i get the same error, but with a different container id

**Comment by ShreyasDeshpande** [comment]
@aayushagrawal135  can you try to stop that container and remove it and again try with launching the service.
docker ps -a
docker stop [container ids]
docker rm [container ids]
docker-compose up

**Comment by aayushagrawal135** [comment]
I tried,
docker-compose down
docker-compose up

It worked. What happened when docker-compose down was executed?

**Comment by vikash2017** [comment]
Just restart docker. It will fix the issue.

**Comment by mroliveira7** [comment]
What happened to me was that i was specifying unnecessarily the ports trying to fix another error
```
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
```
So i just removed the ports and it well went well

**Comment by Shardj** [comment]
lsof -i | grep '3306' doesn't get me anything and a complete stop, reload, up -d of docker-compose doesn't fix it.

**Comment by Shardj** [comment]
Somehow even though I couldn't find it with lsof -i | grep '3306' running sudo kill $(sudo lsof -t -i:8080) did fix the issue for me

**Comment by hackthievist** [comment]
> Just restart docker. It will fix the issue.

Worked...like a charm.

**Comment by thedeepak** [comment]
If nothing works, just restart Docker and do 

docker-compose up --build

**Comment by Shardj** [comment]
> If nothing works, just restart Docker and do
> 
> docker-compose up --build

That isn't going to help people much if it's an external program causing the issue

**Comment by sanymochi** [comment]
Having the same issue.
I have tried:
- docker rm 
-  docker rmi 
-  docker stop 
-  docker start 

 
But still not working.
![image](https://user-images.githubusercontent.com/40659606/62216489-7804fc80-b3c6-11e9-9b98-46395e52f6e7.png)

**Comment by Shardj** [comment]
@sanymochi try this `sudo kill $(sudo lsof -t -i:8761)`

**Comment by Labohkip81** [comment]
This works as charm. replace the port number with one that raises the issue.

**Comment by hemantshekhawat** [comment]
> The following worked for me
> 
> ```shell
> # find container id running on the desired port from the following output
> docker container ls
> # stop the container running on the desired port
> docker stop <container-id>
> ```

For people still looking out for a solution, this works. And kinda gives you an insight on the issue as well.

**Comment by juanjosegutierrez** [comment]
To fix this find the process pid with:

lsof -i :3000

Then kill the process with:

kill -9 <pid>

**Comment by michelefalconi** [comment]
With Docker on Windows 10, I listen before used ports with:
`netstat -ano | grep 3306` (using cmder, or some bash terminal)

I had this result:
`TCP     0.0.0.0:3306     0.0.0.0:0     LISTENING     18076`
`TCP     [::]:3306            [::]:0            LISTENING     18076`

after that, opened Windows Command Shell with 'cmd' and killed that process with:

`taskkill /pid 18076 /f`

After that, I restarted Docker and re-up the docker-compose app.

**Comment by renan-arrieiro** [comment]
Thank you @michelefalconi,
it`s wirk for me in windows 10,

1. Open PowerShell like Administrator 
2.`netstat -ano | Select-String 3306`
3. `taskkill /pid 6108 /f`
4. Restart my docker
5. docker-compose up

it`s a biring work always happen buts it`s work fine

**Comment by phavor** [comment]
> I just used port mapping and problem has been solved. For example set mongo port 27018:27017 in docker-compose file.

This was my remedy.

**Comment by imhassane** [comment]
> 
> 
> Just restart docker. It will fix the issue.

This works :) :)

**Comment by imhassane** [comment]
> 
> 
> I just used port mapping and problem has been solved. For example set mongo port 27018:27017 in docker-compose file.

This works fine :) :)

**Comment by nlevasseur-ix** [comment]
you can run this command to see port application used 
`ss -tulpn`

**Comment by james-cathcart** [comment]
> I was getting the same error but was able to successfully continue after:
> `service mongodb stop`
> 
> I'm a little confused (and new to docker & compose, to be quite honest) but shouldn't a db service running on the host not have a conflict with a db service running within a container?

It depends on how the port was mapped.

**Comment by samacker77** [comment]
Here's a solution. Remove untagged images.
Save the below code as docker_cleaner.sh
sudo ./docker_cleaner.sh

Problem will be solved.

```
#!/usr/bin/env bash
# options:
# remove stopped containers and untagged images
#   $ dkcleanup
# remove all stopped|running containers and untagged images
#   $ dkcleanup --reset
# remove containers|images|tags matching {repository|image|repository\image|tag|image:tag}
# pattern and untagged images
#   $ dkcleanup --purge {image}
# everything
#   $ dkcleanup --nuclear

if [ "$1" == "--reset" ]; then
    # Remove all containers regardless of state
    docker rm -vf $(docker ps -a -q) 2>/dev/null || echo "No more containers to remove."
elif [ "$1" == "--purge" ]; then
    # Attempt to remove running containers that are using the images we're trying to purge first.
    (docker rm -vf $(docker ps -a | grep "$2/\|/$2 \| $2 \|:$2\|$2-\|$2:\|$2_" | awk '{print $1}') 2>/dev/null || echo "No containers using the \"$2\" image, continuing purge.") &&\
    # Remove all images matching arg given after "--purge"
    docker rmi $(docker images | grep "$2/\|/$2 \| $2 \|$2 \|$2-\|$2_" | awk '{print $3}') 2>/dev/null || echo "No images matching \"$2\" to purge."
else
    # This alternate only removes "stopped" containers
    docker rm -vf $(docker ps -a | grep "Exited" | awk '{print $1}') 2>/dev/null || echo "No stopped containers to remove."
fi

if [ "$1" == "--nuclear" ]; then
    docker rm -vf $(docker ps -a -q) 2>/dev/null || echo "No more containers to remove."
    docker rmi $(docker images -q) 2>/dev/null || echo "No more images to remove."
else
    # Always remove untagged images
    docker rmi $(docker images | grep "<none>" | awk '{print $3}') 2>/dev/null || echo "No untagged images to delete."
fi

exit 0

```

**Comment by IagoTheophilo** [comment]
> Tendo o mesmo problema. Eu tentei de tudo, desde remover todos os contêineres, imagens até reiniciar a janela de encaixe e redefinir os padrões de fábrica. Nada funciona. Quando tento `docker-compose up`, estou recebendo o seguinte erro:
> `ERROR: for db Cannot start service db: driver failed programming external connectivity on endpoint djangocelerypsql_db_1 (47ff2801a196bcd458bc2bc44af66797552dc82c06b7122ab04b3c4d7cb25261): Error starting userland proxy: Bind for 0.0.0.0:5432 failed: port is already allocated ERROR: Encountered errors while bringing up the project.`
> 
> e curiosamente `sudo netstat -p -nlp | grep 5432`nada retorna.

Isso Aqui funcionou para mim: service postgresql stop

**Comment by praveendhawan** [comment]
started happening after the updating the docker for windows 10 to version - 2.3.0.4 - 46911. Restarting the Docker is not working. 
`sudo lsof -t -i:5432` returns nothing. I checked all the above commands and nothing is working.

**Comment by Linux4Life531** [comment]
Hey everyone.
I had the same issue, however solved it by making sure no ports were clashing.
Hope this works for you! :+1:

**Comment by sanaullahAhmad** [comment]
sudo lsof -i:3306
kill -9 <docker-pr-[PID]> i-e sudo kill -9 2310

**Comment by lapavalgas** [comment]
bad time for this, :(

**Comment by devangrajarora** [comment]
> I just used port mapping and problem has been solved. For example set mongo port 27018:27017 in docker-compose file.

This worked perfectly !!

**Comment by JupaOlivares** [comment]
Restart everything, this worked for me

**Comment by masashi49** [comment]
I solved it with this procedure

1 . docker stop $(docker ps -q)
2 . docker-compose up -d

**Comment by rubenigas** [comment]
Having the same issue.
Solved with `sudo netstat -p -nlp` and looking for the process that is using port 5432 an killing it with `kill {pid}`

**Comment by asgaralipq** [comment]
> I just used port mapping and problem has been solved. For example set mongo port 27018:27017 in docker-compose file.

Thanks for this solution. Was stuck for hours on this.

**Comment by Ednavan** [comment]
> O seguinte funcionou para mim
> 
> ```shell
> # encontre o ID do contêiner em execução na porta desejada a partir da seguinte saída
> docker container ls
> # parar o contêiner em execução na porta 
> docker stop < container-id > desejada
> ```

Serviu e resolveu meu problema!

**Comment by gidmak** [comment]
Had the same issue I resolved it by:
`docker-compose down`
then restarted docker
`docker-compose up -d`

**Comment by El-Santooo** [comment]
Workaround from **sanaullahAhmad**  worked for me, I had running mysql in the host PC, many thanks.

**Comment by nomo3919** [comment]
I found several options to solve this in different cases. But the problem is exactly what the error is warning about.

1. Try docker-compose down
2. Check running processes with docker ps (-a). Try to stop the docker process at the specified id:
    docker ps -a
    docker stop <container--id>
    docker rm <container--id> (--force)
3. Try 
    docker-container ls
    docker stop <container--id>
4. Restart docker 
5. Find the unwanted processes in linux on port  - kill em
____
Simple bonus solution: 
burn out
rm -rf / 
get out from IT

**Comment by AmshenShanu07** [comment]
I found there command is fine, Plese note the spelling of mongod its "mongod" not "mongo" or "mongodb" 

 
```sudo service mongod stop```
```sudo mongod```
```docker-compose up```

**Comment by SerRichard** [comment]
I had the same issue, with neither lsof or netstat showing anything listening to the port. The folowing commands worked.

`docker network prune`
`docker-compose down`
`docker-compose up`

**Comment by raphaelcosta1** [comment]
> when i do the following :
> 
> ± docker-compose up
> Starting ltg_db_1
> 
> ERROR: for db Cannot start service db: driver failed programming external connectivity on endpoint ltg_db_1 (ecc3bf3036508fade24ffa4d6bc3e5fee0180073c5351667c471922a10fad60f): Error starting userland proxy: Bind for 0.0.0.0:27017 failed: port is already allocated
> ERROR: Encountered errors while bringing up the project.
> 
> ![image](https://cloud.githubusercontent.com/assets/1026325/20086070/7f21508c-a53b-11e6-849a-98747a4d2b71.png)
> 
> ![image](https://cloud.githubusercontent.com/assets/1026325/20086107/c5f84312-a53b-11e6-83d0-89a63f8b9646.png)
> 
> ![image](https://cloud.githubusercontent.com/assets/1026325/20086116/d61688f8-a53b-11e6-8ddf-fca143d45e50.png)
> 
> ± sudo docker inspect mongo
> [
> {
_________________

Hi, everyone.
I had a similar issue, but I wasn't able to identify if something was using the port 5432.
That was the way that I solved the issue:

1) I used sudo ss -tulwn | grep LISTEN
`➜  xxxx-xxxx-xxxxxx git:(master) sudo ss -tulwn | grep LISTEN
tcp     LISTEN   0        244                                 127.0.0.1:5432                            0.0.0.0:*                                               
tcp     LISTEN   0        511                                 127.0.0.1:35613                           0.0.0.0:*                                               
tcp     LISTEN   0        100                                 127.0.0.1:49152                           0.0.0.0:*                                               
tcp     LISTEN   0        128                                 127.0.0.1:30800                           0.0.0.0:*                                               
tcp     LISTEN   0        128                                 127.0.0.1:30900                           0.0.0.0:*                                               
tcp     LISTEN   0        4096                            127.0.0.53%lo:53                              0.0.0.0:*                                               
tcp     LISTEN   0        5                                   127.0.0.1:631                             0.0.0.0:*                                               
tcp     LISTEN   0        5                                       [::1]:631                                [::]:*                                               
` 
2) Just checking
`➜ xxxx-xxxx-xxxxxx git:(master) docker container ls
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
`
3) Just checking
`➜  xxxx-xxxx-xxxxxx  git:(master) docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
`
4) `➜  xxxx-xxxx-xxxxxx git:(master) docker network prune
WARNING! This will remove all custom networks not used by at least one container.
`
**After that, docker-compose down and docker-compose up --build works**

And I was happy using docker... until now.

My next steps:
    Configure container's environment for the first time
5) Run docker-compose run —rm web bash in a separate terminal pane/window. You should now be inside container, which is 
    indicated by showing you a hashtag before commands.
6) Run rails db:create within container.
7) Run rails db:migrate within container.
    Run the environment seeds (if you want to)
8) Run rails db:seed.

**Comment by Rahul-raj-dev** [comment]
> I just used port mapping and problem has been solved. For example set mongo port 27018:27017 in docker-compose file.

it helped me and solved the issue

**Comment by rwagatenga** [comment]
I used `sudo service postgresql stop` and it worked for me

**Comment by Marl27** [comment]
docker-compose down
docker container ls -a

stop the corresponding container_id with the problematic port 
docker stop [Container_id]
docker rm [Container_id]

**Comment by alfmorais** [comment]
> The following worked for me
> 
> ```shell
> # find container id running on the desired port from the following output
> docker container ls
> # stop the container running on the desired port
> docker stop <container-id>
> ```

FROM 2022, I'd like to say really thank you for that information.

**Comment by FLGUTIERREZN** [comment]
A mí me funcionó deteniendo el servicio mysql con:
sudo service mysql stop

**Comment by Jandsonn** [comment]
Defini uma nova porta para o mysql service adminer para 3307:3307 e resolveu meu problema!

**Comment by rruenroeng** [comment]
I had to switch the port my docker container was running on and "docker compose up" (with the different port) and then switch it back. Something was wonky, but now I can run docker up however I want after downloading and installing the container and it's working much better.

**Comment by AtmegaBuzz** [comment]
> 3\. docker rm [

Removed all docker containers using this command , It worked

**Comment by Liz2222** [comment]
> service mongodb stop

This helped, Thanks

**Comment by ZainabImad94** [comment]
> Hey everyone. I had the same issue, however solved it by making sure no ports were clashing. Hope this works for you! +1

thanx in advance, but how to know which port is in conflict with other?

**Comment by SerRichard** [comment]
> thanx in advance, but how to know which port is in conflict with other?

Check if the port number you want to allocate is already in use with something like:
`sudo netstat -tnlp | grep :27017`

Ref: [Check if port is in use](https://linuxize.com/post/check-listening-ports-linux/)

**Comment by hunghaitu** [comment]
i get the same error and i use:
sudo systemctl stop postgresql

**Comment by krkarel** [comment]
To resolve on Linux Mint 21.1 Cinnamon:

`sudo systemctl stop mysql.service`

**Comment by hamzasial1911** [comment]
I was facing the same problem due to my postgres db running on the same port I just kill the db process or close the db by running this command 'sudo service postgresql stop' or systemctl stop postgresql depending on your system.
this worked for me.

**Comment by vallesluiggi** [comment]
This worked for me:

`sudo service postgresql stop`

and try the command again

regards

**Comment by Victory-charts** [comment]
> i stopped all the containers but still no solution. then i tried to delete al the containers and still no solution.





https://stackdev.space/questions/combining-an-apache-spark-cluster-with-various-databases
