### ISSUE TITLE
Output, colors and tty:true errors

### ISSUE THREAD

**Issue by YouriT** [docker/compose#4129]
I was not getting any colorized output as you can see here:
<img width="1440" alt="screen shot 2016-11-08 at 13 19 49" src="https://cloud.githubusercontent.com/assets/1449797/20099333/45104664-a5b8-11e6-9b8f-735b1667db6a.png">

So as per #2231 I tried using `tty: true` in service configuration, which did the trick and gave me colors but not like when using `run -t ...` as you can see I've some char encoding issues;
<img width="515" alt="screen shot 2016-11-08 at 13 37 28" src="https://cloud.githubusercontent.com/assets/1449797/20099384/8570b2d4-a5b8-11e6-8a4a-fae6d31429cc.png">

What could be the issue about the encoding of the chars as `docker run -t...` gives me the correct output?

**Kinda improvement on version update**
`1.8.0` => `1.8.1, build 878cff1`

So I updated to 1.8.1 as this might solve the issue and now I'm getting utf8 chars with a messy output (not using `tty: true` makes it non-messy but not colorized)
<img width="786" alt="screen shot 2016-11-08 at 13 43 28" src="https://cloud.githubusercontent.com/assets/1449797/20099545/5aa51de6-a5b9-11e6-8200-5253b8bd0a4d.png">

Any ideas, hints? I've the feeling there is a small bug behind this.

**Comment by shin-** [comment]
This seems to be the same issue as #4027 , can you confirm?

**Comment by YouriT** [comment]
@shin- seems to be related yes. But the issue doesn't mention whether TTY is involved or not as in my case, when there is no `tty: true` it works but there is no colorization.

**Comment by YouriT** [comment]
@shin- #3106 seems also to go in the same way

**Comment by shin-** [comment]
Should be fixed in recent versions!
