### ISSUE TITLE
ensure all containers are started

### ISSUE THREAD

**Issue by josh-devops-center** [docker/compose#413]
Hi,

When running fig up -d, I notice that if there is an error starting a dependent container, the error is silent. For example, if a postgres container fails to startup, the state in fig ps is 'Exit 1'. Since the container didn't start, and other containers depend on this container thru links, would it be possible for better alerts and/or messaging if a dependent container has errors starting?

Thanks

**Comment by dnephin** [comment]
If you need immediate feedback from a command, either `docker-compose up` (without -d) or `docker-compose run` would give that to you.  Detached is specifically designed to "run in the background".

You can always use the docker API to query for the status of services.
