### ISSUE TITLE
Add --exclude to docker-compose up

### ISSUE THREAD

**Issue by philtay** [docker/compose#4133]
I have a Compose file with 10 services. I want to start only 8 of them. I can do `docker-compose up srv1 srv2 srv3 srv4 srv5 srv6 srv7 srv8` but it would be better to do `docker-compose up --exclude srv9 srv10`. Useful syntactic sugar IMO.

**Comment by johnharris85** [comment]
Is it common that you'd want to start a regular subset? If so then perhaps using `extends` would help the use case. Compose is meant to model an application / common set of container deployments. Not sure how common wanting to start a project that is missing a couple of containers would be (although happy to be enlightened!).

**Comment by philtay** [comment]
Judging by the fact that Compose already supports starting a subset, I would say that it's common enough. Many other commands, not only `up`, also allow to specify the services by name. The current syntax makes it easy to specify a limited subset of the services (2 or 3) as opposed to a larger one.

**Comment by pmzajaczkowski** [comment]
For my team it's very common to start all services apart of particular one. That's the case where you are developing some microservices and want to run all of them on your machine (using docker-compose) apart of that single one that you are currently developing and running from your IDE (for example in the debug mode). So that's :+1: from me for --exclude. But that --exclude should also override dependencies - if I don't want to start something it should never start :)

**Comment by yohanliyanage** [comment]
I'm facing the same situation as @pmzajaczkowski. Having this feature is quite useful when testing microservices locally.

**Comment by DemianTinkiel** [comment]
+1 on suggestion. Definitely useful for my team

**Comment by echo-xu** [comment]
+1

**Comment by DutchKevv** [comment]
+1

**Comment by rangerscience** [comment]
+1

My use case is that we have a handful of microservices, and I'm developing one of them. I want to `docker-compose up --exclude <service under development>`, which I then start myself; for clearer logging, custom environment, under hot-reload modes, etc.

**Comment by er1z** [comment]
Second that.

**Comment by cassiocardoso** [comment]
This would be super helpful.

Would appreciate if you guys consider this for a future release.

**Comment by TVictor** [comment]
+1

**Comment by serbaut** [comment]
Workaround:

     docker-compose up --scale foo=0

**Comment by Flaque** [comment]
+1

**Comment by evilosa** [comment]
+1

**Comment by adithepnarula** [comment]
+1

**Comment by sbz** [comment]
+1

**Comment by ArcanjoQueiroz** [comment]
+1

**Comment by stidiovip** [comment]
+1

**Comment by Lynaj** [comment]
+1

**Comment by aleksandrmetik** [comment]
+1

**Comment by jpyzio** [comment]
+1

**Comment by dustinlacewell** [comment]
+1

**Comment by scramados** [comment]
+1

**Comment by mahaffey** [comment]
pls

**Comment by mahaffey** [comment]
+1

**Comment by rachelthecodesmith** [comment]
+1

This would be super useful!

**Comment by hervenicol** [comment]
Workaround #2:
```
docker-compose config --services | magic_grep | xargs docker-compose up
```
the advantage is that you can have a fancy grep pattern, like exclude frontend-* or keep only *db.

**Comment by ishpartko** [comment]
+1

**Comment by Rohaq** [comment]
While this can be deployed using
```
docker-compose up -d scale=0 <service>
```
it would be far more useful to be able to specify a service that needs to be specified explicitly through a `docker-compose` command - or only brought up by a `depends_on` reference in another service - in the `docker-compose.yaml` file.

**Comment by Rohaq** [comment]
> For my team it's very common to start all services apart of particular one. That's the case where you are developing some microservices and want to run all of them on your machine (using docker-compose) apart of that single one that you are currently developing and running from your IDE (for example in the debug mode). So that's 👍 from me for --exclude. But that --exclude should also override dependencies - if I don't want to start something it should never start :)

I'd prefer to see an option for both cases: e.g. I have a site in a container dependent on a running nginx service, but both are "disabled" from running through a standard `docker-compose up` (e.g. for a local dev environment) - but if I run `docker-compose up <my site service>`, I'd want it to still bring up the nginx service with it.

**Comment by stidiovip** [comment]
+1

**Comment by toymachiner62** [comment]
+1 This would be very useful for me too. 

My use case is most of the time I want to run all services in my `docker-compose.yml` file except one b/c it's a service that is a resource hog and is only need when i'm testing pieces of my app locally.

Only sometimes do I want to run literally everything in my `docker-compose.yml` file.

**Comment by toymachiner62** [comment]
> While this can be deployed using
> 
> ```
> docker-compose up -d scale=0 <service>
> ```
> 
> it would be far more useful to be able to specify a service that needs to be specified explicitly through a `docker-compose` command - or only brought up by a `depends_on` reference in another service - in the `docker-compose.yaml` file.

@Rohaq I believe you meant `docker-compose up --scale <service>=0`

**Comment by FernandoMiguel** [comment]
You can split your yml into two, moving the often offending service there.
When you need, you combine both yml.

--
Fernando 🐼

**Comment by sylwestergryzio** [comment]
Run into similar need today. +1

**Comment by michalf-kainos** [comment]
+1

**Comment by jmakr0** [comment]
+1

**Comment by banjoh** [comment]
+1

**Comment by mahaffey** [comment]
+1 is not helpful and is only email spam for those who are following this issue...

**Comment by eliam** [comment]
my use case is similar but different enough to mention.  I'd like to --exclude from docker-compose log.  There's one chatty service I'm not interested in seeing but rather than listing all services, it'd be useful to --exclude the one.

**Comment by mahaffey** [comment]
@eliam `docker-compose log | grep -v <service_name>`

inverse grep will filter for you

**Comment by eliam** [comment]
> @eliam `docker-compose logs | grep -v <service_name>`
> 
> inverse grep will filter for you

Yes, thanks, I'm familiar.  I'd normally be following these logs, i.e."docker-compose -f --tail=5" but irrespective, I'm not sure producing output to ignore is how I'd go, *if* --exclude functionality existed.

**Comment by EricHripko** [comment]
There's a proposal for profiles in Compose that potentially can fill this gap. Feel free to check it out and contribute to the discussion here: https://github.com/compose-spec/compose-spec/issues/97

**Comment by ndeloof** [comment]
You should rely on profile to group services by usage scenario, so that you can easily enable/disable those

**Comment by ulyssessouza** [comment]
As @ndeloof just mentioned, profiles is the way to go. Documentation can be found [here](https://github.com/compose-spec/compose-spec/blob/master/spec.md#profiles)

**Comment by felipekunzler** [comment]
Sorry, but I believe profiles (e.g. test, debug) has a different use case than what was described in the thread.

> For my team it's very common to start all services apart of particular one. That's the case where you are developing some microservices and want to run all of them on your machine (using docker-compose) apart of that single one that you are currently developing and running from your IDE (for example in the debug mode). So that's 👍 from me for --exclude. But that --exclude should also override dependencies - if I don't want to start something it should never start :)

What do you recommend? A different profile for each possible exclusion? Not sure if that makes sense.

**Comment by ndeloof** [comment]
> That's the case where you are developing some microservices and want to run all of them on your machine (using docker-compose) apart of that single one that you are currently developing and running from your IDE (for example in the debug mode)

This indeed is a pretty common scenario, and most users enable remote debugger port in their service definition to cover this need, so they don't have to tweak the compose file.
