### ISSUE TITLE
docker-compose 1.9.0-rc4 gets SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by jamshid** [docker/compose#4141]
docker-compose 1.9.0-rc4 seems to require SSL now. Previously it honored DOCKER_TLS_VERIFY and, like the docker client itself, talked to a non-SSL docker server, e.g. one created with
```
$ docker run -d --restart always -p 2375:2375 --volume=/var/run/docker.sock:/var/run/docker.sock --name=docker-http sequenceiq/socat
```
```
$ export DOCKER_HOST=tcp://docker.example.com:2375
$ export DOCKER_TLS_VERIFY=
$ docker ps 
(...works fine...)

$ docker-compose --version
docker-compose version 1.9.0-rc4, build 181a4e9
$ docker-compose ps
ERROR: SSL error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)

$ docker-compose.backup --version
docker-compose version 1.8.0, build f3628c7
$ docker-compose.backup ps
(...works fine...)
```

**Comment by shin-** [comment]
What's the output of `docker-compose version` (without the dashes)? What OS are you running on?

**Comment by jamshid** [comment]
Using Docker for Mac, latest beta30.
```
$ docker-compose version
docker-compose version 1.9.0-rc4, build 181a4e9
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by dorons** [comment]
Ran into the same issue. Apparently now both `DOCKER_TLS_VERIFY` and  `DOCKER_CERT_PATH` must be set and empty. Unsetting any of them won't work. Therefore:

```
export DOCKER_TLS_VERIFY=
export DOCKER_CERT_PATH=
```

That worked for me...

**Comment by shin-** [comment]
@jamshid Does the solution suggested by @dorons fix the issue for you as well?

**Comment by shin-** [comment]
One other solution you could try would be to set `COMPOSE_TLS_VERSION=TLSv1_2` in your [environment](https://docs.docker.com/compose/reference/envvars/#/composetlsversion).

**Comment by jamshid** [comment]
Yes, `export DOCKER_CERT_PATH=` fixed it for me too, thanks.
Would be good if docker and docker-compose behaved had the same env variable requirements but feel free to close this.
