### ISSUE TITLE
env vars in volume section: "no declaration was found in the volumes section"

### ISSUE THREAD

**Issue by maltefiala** [docker/compose#4142]
### Foreword
Tested with 1.8.1 and 1.9.0-rc4

### Not Working
```json
volumes:
  - "$MYSQL_DIRECTORY:/var/lib/mysql"
```
and
```json
volumes:
  - "${MYSQL_DIRECTORY}:/var/lib/mysql"
```
either produce:
```bash
ERROR: compose.cli.main.main: Named volume ""/foo":/var/lib/mysql:rw" is used in service "mysql" but no declaration was found in the volumes section.`
```

### Working

```json
volumes:
  - "/foo:/var/lib/mysql"
```

**Comment by shin-** [comment]
use `MYSQL_DIRECTORY=/foo` instead of `MYSQL_DIRECTORY="foo"`

**Comment by maltefiala** [comment]
Already the case, unfortunately not working:

```bash
MYSQL_DIRECTORY="/foo"
```
The path was the same in both cases. However, variable substitution is not working.

The name / absolute path switch seems to be bearer of problems. I ran into several problems there myself. I guess it needs refining but have not found time to read through the code so far …

**Comment by maltefiala** [comment]
docker-compose does not handle quoted paths. Closed this issue, opened another one: https://github.com/docker/compose/issues/4154
