### ISSUE TITLE
docker-compose inspect

### ISSUE THREAD

**Issue by pmihalcin** [docker/compose#4155]
Hi all,
Are there any plans for **docker-compose inspect** command?
One could get e.g. exposed ports of given service

Thanks

**Comment by shin-** [comment]
`docker-compose ps` already lets you see exposed ports.

**Comment by jsrun** [comment]
Hello friend, I made a module to solve this https://github.com/jsrun/docker-compose-remote-api

**Comment by ahilsend** [comment]
I agree! It would be very useful to have the commands available to docker itself also available to docker-compose.

**Comment by awalterschulze** [comment]
Why was this closed?

**Comment by shin-** [comment]
It won't be implemented. For the rare cases where it would be useful, people can use `docker inspect` instead.

**Comment by awalterschulze** [comment]
docker inspect only works if you setup your --project_name correctly.
But then I am also happy with docker inspect.

**Comment by elboletaire** [comment]
I don't get it... why is then `docker-compose exec` implemented? or `docker-compose logs`?

**Comment by RyanEwen** [comment]
+1

I would like to be able to write a script to check if a container is running but if the containers were started using compose and not named, then I don't know the name.

**Comment by dsaborg-igm** [comment]
It would be great to be able to inspect docker-compose containers so one does not need to know the project name beforehand.

**Comment by deeky666** [comment]
For what it's worth: You can do something like (assuming the service to check is named `foo`)

```
docker inspect $(docker-compose ps -q foo)
```

Hope that helps.

**Comment by mihow** [comment]
Is there a way to get the docker-compose project name programmatically? `docker inspect` isn't an option if a script can't determine the project name that compose generated. 

For example, there is no consistent way to remove named volumes programmatically.

**Comment by larssb** [comment]
@deeky666 

I tried your suggestion and it works well for docker-compose.yml service definitions where one **did not** use `--project-name`. However, if that is what one did, it does not work as `docker-compose ps -q _servicename_` returns nothing.

Is there anything one can do in the case described above?

Thank you

**Comment by deeky666** [comment]
@larssb I'm not sure if I get you right but maybe this helps?

```
docker inspect $(docker-compose --project-name PROJECT_NAME ps -q SERVICE_NAME)
```

**Comment by larssb** [comment]
Hi @deeky666 

Sure ... I might not have explained myself properly. If I for some reason, forgot, lost or for whatever reason, do not have the project name used. So I can't use the `--project-name` parameter to `docker-compose ps` ... is there then a way by which I can determine the project name that was used.

Thank you.

**Comment by rafipiccolo** [comment]
If I do
docker-compose --project-name project up -d service

I get a container named : project_service_1

Then this will return data 
Docker inspect $(docker ps -aq | grep _service_ )

Ez but shame.

**Comment by thenewguy** [comment]
I just happened across this issue trying to debug an odd problem with a container where I need to inspect one of the compose containers from inside a CI script.  It seems bizarre not to include an easy to use `docker-compose inspect` option

**Comment by quant61** [comment]
You can inspect docker-compose containers like this:
```bash
docker inspect $(docker ps -f label=com.docker.compose.project.working_dir="$PWD" -f label=com.docker.compose.service=service_name --format '{{.ID}}')
```
If you want to use container id in scripts, you can do this:
```bash
CONTAINER_ID=$(docker ps -f label=com.docker.compose.project.working_dir="$PWD" -f label=com.docker.compose.service=service_name --format '{{.ID}}')
```

**Comment by thenewguy** [comment]
> You can inspect docker-compose containers like this:
> 
> ```shell
> docker inspect $(docker ps -f label=com.docker.compose.project.working_dir="$PWD" -f label=com.docker.compose.service=service_name --format '{{.ID}}')
> ```
> 
> If you want to use container id in scripts, you can do this:
> 
> ```shell
> CONTAINER_ID=$(docker ps -f label=com.docker.compose.project.working_dir="$PWD" -f label=com.docker.compose.service=service_name --format '{{.ID}}')
> ```

Thank you for putting that together.  I will make use of it.

It is still rather obscure and complicated for interacting with the cli by hand.  It isn't viewable without scrolling on a 3000px wide monitor =P

`docker-compose inspect db` would be much easier to use
