### ISSUE TITLE
docker compose completion

### ISSUE THREAD

**Issue by a1exus** [docker/compose#4158]
I'm using `macOS 10.12.1 (16B2555)` and trying to follow [Command-line completion - Docker](https://docs.docker.com/compose/completion/#/installing-command-completion):

```
$ curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose > /usr/local/etc/bash_completion.d/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10552  100 10552    0     0  96288      0 --:--:-- --:--:-- --:--:--  119k
$ ls -la /usr/local/etc/bash_completion.d/docker-compose 
-rw-r--r--  1 alexus  admin  10552 Nov 15 22:13 /usr/local/etc/bash_completion.d/docker-compose
$ 
```
yet, completion still unavailable( I also would like to get completion going for `docker` as well.

Please advise.

**Comment by shin-** [comment]
You may need to re-login

**Comment by a1exus** [comment]
@shin- My apologies for not including that information to my issue initially, however I did try re-login and that did not help me at all.

**Comment by ijc** [comment]
I've just tried this on my mac and completion appears to be working fine. I suspect this was a transient bug back in 2016 which has been resolved in the meantime so I'm going to close.

(If you still are having problems, did you remember to add the `source` of the top-level bash completion to your dotfiles?)
