### ISSUE TITLE
Audit logs for docker-compose CLI

### ISSUE THREAD

**Issue by robbinalexander** [docker/compose#4159]
Is there a plan to redirect some of the CLI logs to a logfile? Currently, docker-compose start, stop, up, run, build etc can potentially do multiple things - create volume, build image, start dependent service. All these information is only available in the CLI console? It would be nice to redirect this to a log.
We are currently using docker-compose installed as a container.

**Comment by shin-** [comment]
There's no plan to do that at the moment. If it somehow becomes a common ask we may consider it, but UNIX environments give you the tools to do it yourself so I don't expect it to be high priority.
