### ISSUE TITLE
Get docker command line used by docker-compose?

### ISSUE THREAD

**Issue by ankon** [docker/compose#4160]
For debugging it would be helpful to be able to directly invoke `docker run ...`, providing the same arguments that docker-compose would use.

**Comment by shin-** [comment]
docker-compose does not use the docker CLI. As a result, that seems like a completely different project to me.

**Comment by ankon** [comment]
Hmmm. Fair point, @shin-. I'm not familiar with the docker API that compose uses, but given that it seems to mirror the options used for docker, I guess what could be possible (and already would help a lot) would be to log the complete parameters for that specific API call?

**Comment by ijc** [comment]
`docker-compose --verbose up` includes all or the URLs hit in full.
