### ISSUE TITLE
Document differences between default networking setup used with v1 and v2 file formats

### ISSUE THREAD

**Issue by turtlemonvh** [docker/compose#4177]
I've noticed a lot of issues related to the behavior of docker-compose wrt dns settings on this project while I was having issues myself.    Here are some example issues that center on confusion about v1 vs v2 networks:

* https://github.com/docker/compose/issues/2847
    * https://github.com/docker/compose/issues/2847#issuecomment-231158186: answer saying to read the docker docs
* https://github.com/docker/compose/issues/3703
    * https://github.com/docker/compose/issues/3703#issuecomment-231158477: answer saying to read the docker docs
* https://github.com/docker/compose/issues/3877
* https://github.com/docker/compose/issues/3412

These are the links to the docker documentation that are sometimes provided:

https://github.com/docker/docker/blob/docs/docs/userguide/networking/dockernetworks.md
https://github.com/docker/docker/blob/docs/docs/userguide/networking/configure-dns.md

These links do not really answer the main question the users have: What changed in the behavior of docker-compose between v1 and v2?  This would be a good thing to put here:
https://docs.docker.com/compose/compose-file/#/upgrading

I would love to contribute this myself, but I am still kind of fuzzy on what is going on.

## Details of my problem that caused me to notice these tickets

> This section is not strictly necessary to solve the issue reported. It just reinforces the issue.

I was seeing that, after switching to the v2 file format, my dns services were no longer handling recursive resolves as expected.

I read all the linked docker docs, but I am still am not clear on why some addresses that resolve when `dig`ing against my dns server directly do not work when setting that dns server as my primary resolver in the `dns` section of the v2 config.

I'm running a consul container on a bridge network and listing the bridge ip as the resolver that docker should use.  I *did* notice that when targeting that ip when `dig`ing from inside the container I would get this error:

```bash
$ docker exec -it worker dig svca.node.us-west-2.deveng.com @172.17.42.1
;; reply from unexpected source: 172.18.0.1#53, expected 172.17.42.1#53
;; reply from unexpected source: 172.18.0.1#53, expected 172.17.42.1#53
;; reply from unexpected source: 172.18.0.1#53, expected 172.17.42.1#53
```

I think that error may have been causing docker's build in resolver to fall back to by secondary resolver `8.8.8.8`, which would explain why I got a negative response.

I was able to solve my problem my setting every container to `network_mode: bridge`, which stopped docker from using the `127.0.0.11` dns proxy mentioned in the docs.  My dns server then showed up in `/etc/resolv.conf` as expected and all local and recursive resolves worked as expected.

**Comment by shin-** [comment]
cc @londoncalling as this is a docs issue.

This has less to do with v1 versus v2 and more to do with old networking vs new networking in Engine, but we did tie one to the other so I don't know what's the best approach to inform users.

**Comment by turtlemonvh** [comment]
@shin- What you just said re: tying v1 to old networking and v2 to engine networking is pretty helpful in itself.  Could we add that to the docs with some links to relevant docker docs?

**Comment by JonasT** [comment]
It should also be documented that V2 will mean per default, each docker-compose.yml group is isolated with its own user-defined network and it cannot talk to others without extra settings (even with an external link present), while with V1 every container could talk to every other if it somehow got the ip (through an external link or some other means).

This was a change that surprised me, and it would certainly have been useful to know before actually attempting the migration.

Also, the upgrading docs are currently focused purely on a tutorial-like style which I think is a problem.

What it needs (IMHO) is an additional section that is titled something like "important changes you may encounter beyond syntax", which lists:

a.) v2 uses different networking with the new engine networking
b.) what I just described (isolation of groups per default)
c.) pre-migrated container groups can also not easily talk to migrated ones - this was also something I missed.

(and what others still come up with)

**Comment by aanand** [comment]
The difference between v1 and v2 regarding networks is addressed at the top of the [Networking in Compose](https://docs.docker.com/compose/networking/) document, which - by the sound of it - isn't discoverable enough. I agree that the differences in networking should also be called out in the migration document.

**Comment by JonasT** [comment]
The article you linked is also IMHO not clear enough;

## Proposed change 1
https://docs.docker.com/compose/networking/

I would suggest changing the following paragraph:

> By default Compose sets up a single network for your app. Each container for a service joins the default network and is both reachable by other containers on that network, and discoverable by them at a hostname identical to the container name.

to something like

> By default Compose sets up a single network for your !!<LINK=/definition/of/word>app</LINK>!!. Each container for a service joins the default network and is both reachable by other containers on that network, and discoverable by them at a hostname identical to the container name. Other apps will be isolated unless you set up an explicit shared network.

## Proposed change 2
https://docs.docker.com/compose/overview/
I suggest this article should be expanded by explaining what an "app" is supposed to be, e.g. by changing

> Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration. To learn more about all the features of Compose see the list of features.

to

> Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration. To learn more about all the features of Compose see the list of features.
> Each such application (we also call it "app" for short) is described by a single docker-compose.yml that lists all the containers that logically belong together to form the complete application (it can also just be one container).

(and this should be linked from the place I mentioned above with the !!<LINK>..</LINK>!!)

Before you ask whether this is obvious - no it isn't, because "app" sometimes refers to mobile only while "application" refers to desktop application, and in general the scope of what an "app" is, is not immediately clear - however, in terms of docker-compose it is super clearly defined, so it is worth writing down. There was a similar problem where a folder with all files required to launch a container was suddenly called "repository" with no proper explanation and without that being a source code repository, so it's much better to be super explicit with the words used in the documentation.
