### ISSUE TITLE
docker-compose is lacking pids-limit 

### ISSUE THREAD

**Issue by onorua** [docker/compose#4178]
Apparently pids-limit is not implemented at all, it is not mentioned neither in config_schema nor in source code. 
I've expected it to be on the same level as `shm_size` , is there a way to make it work or we need to create PR for it?

**Comment by shin-** [comment]
Hi!

This would indeed require a PR.

**Comment by disconnect3d** [comment]
Just for other people who would get here - the `pids_limit: X` in `docker-compose.yml` doesn't work for compose version 3. It works for 2.1, see https://github.com/docker/compose/issues/4792 for more info.
