### ISSUE TITLE
WARNING: The X variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by a1exus** [docker/compose#4189]
My environment:

```
# docker-compose version
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.3
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
# 
```

I'm seeing following _WARNING_ message:

```
# docker-compose ps
WARNING: The ELK variable is not set. Defaulting to a blank string.
    Name              Command          State                    Ports                   
---------------------------------------------------------------------------------------
nginx_nginx_1   nginx -g daemon off;   Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp 
#
```

Per [Environment variables in Compose - Docker](https://docs.docker.com/compose/environment-variables/):

 * [Substituting environment variables in Compose files](https://docs.docker.com/compose/environment-variables/#/substituting-environment-variables-in-compose-files)

```
# grep ELK docker-compose.yaml 
        gelf-address: "udp://${ELK}:12201"
# 
```

 * [The “env_file” configuration option](https://docs.docker.com/compose/environment-variables/#/the-envfile-configuration-option)

```
# grep -A1 env_file docker-compose.yaml 
    env_file:
      - docker-compose.env
# grep ELK docker-compose.env 
ELK=172.17.0.2
# 
```

Please advise.

**Comment by shin-** [comment]
You need to escape the variable if you want it to be expanded inside the container, using a double-dollar sign (`$${ELK}`).
Ig however, you want it to be interpreted on your host, the $ELK needs to be defined in your environment or in the `.env` file. The `env_file` option defines environment variables that will be available inside the container only.

**Comment by a1exus** [comment]
@shin-

I'm trying to implement following:

* [Substituting environment variables in Compose files](https://docs.docker.com/compose/environment-variables/#/substituting-environment-variables-in-compose-files).
* [The “env_file” configuration option](https://docs.docker.com/compose/environment-variables/#/the-envfile-configuration-option).

**Comment by rloth** [comment]
It's not intuitive to me that the file specified by the "env_file" directive acts differently than the ".env" file...

However @shin- 's comment made it clear to me... the ".env" file's vars are available at docker-compose stage whereas all other env vars set via env_file or env directive are only available within the container... ok

**Comment by imaia** [comment]
> However @shin- 's comment made it clear to me... the ".env" file's vars are available at docker-compose stage whereas all other env vars set via env_file or env directive are only available within the container... ok

That feels a lot like a bug. There shouldn't be "too specific" behavior. It only confuses people.

**Comment by Joshfindit** [comment]
Found this issue first in the search for a resolution, and ended up understanding then solving it with the info here: http://staxmanade.com/2016/05/how-to-get-environment-variables-passed-through-docker-compose-to-the-containers/

Specifically;
set the variable in `.env`, which makes it available to substitute in `docker-compose.yml`

```
EXTERNAL_PORT=8000
```

**then** in `docker-compose.yml`, **pass it through** to the container with:
```
environment:
      - EXTERNAL_PORT=${EXTERNAL_PORT}
```

**Comment by a1exus** [comment]
@Joshfindit that is *EXACTLY* like in my comment and yet this isn't working for me, hence new issue..

**Comment by Joshfindit** [comment]
@a1exus I don't see where you're mentioning `./.env` in your comments.
What is the content of your `./.env` file?

**Comment by a1exus** [comment]
@Joshfindit at the very end of my comment:

```
# grep ELK docker-compose.env 
ELK=172.17.0.2
# 
```

**Comment by Joshfindit** [comment]
@a1exus `./docker-compose.env` != `./.env`

**Comment by shin-** [comment]
To reiterate what I wrote earlier in this thread:

- The `environment` and `env_file` sections of the Compose file declare variables that will be available inside the container.
- Variables written using the `$VAR` or `${VAR}` syntax inside the Compose file are replaced by the value found on the host machine (i.e. the machine you're executing `docker-compose` from) at the time of execution. They're found either in the OS's environment or the statically named `.env` file.
- If variable substitution is not desired, one should use the double-dollar-sign notation (`$$VAR` or `$${VAR}`) to escape the sequence.

**Comment by a1exus** [comment]
Per @Joshfindit I've tried with `.env` and everything works like a charm! Thank you!

**Comment by oojacoboo** [comment]
`Variables written using the $VAR or ${VAR} syntax inside the Compose file are replaced by the value found on the host machine (i.e. the machine you're executing docker-compose from) at the time of execution.`

I get this:  `WARNING: The UID variable is not set. Defaulting to a blank string.`

However:
```bash
[jacob:.../foo]$ echo $UID
501
```

**Comment by shin-** [comment]
@oojacoboo $UID is not an environment variable, it's a shell variable:
```
$ echo $UID
1000
$ printenv | grep UID  # no output
$
```

See #2380

**Comment by oojacoboo** [comment]
@shin- was just actually about to update my comment as I noticed the same thing - thanks.  And thanks for the issue link - perfect.

**Comment by jibusayone** [comment]
I managed to find a solution! I used the `env_file` setting itself, and defined the `variables.env` within the same line. And it worked like a charm!

Here is how my docker-compose.yml looks like:
```
services:
  web:
    env_file: variables.env
```

**Comment by a1exus** [comment]
you can also use _.env_ in root of your project it does same...

**Comment by sodik82** [comment]
just for future googlers. my problem was with environment variables not being passed through `sudo` (e.g. on Ubuntu). Working solution:

```
sudo -E docker-compose up -d
```

**Comment by alexei-developer** [comment]
Hello, I am problem with set variable in yaml file:
**docker-compose build master
WARNING: The CI_ARTEFACTS_HOSTPATH variable is not set. Defaulting to a blank string.
Building master
...** (cut log)

I am use:
```
      CI_ARTEFACTS_HOSTPATH: '/ci'
      CI_ARTEFACTS_HOSTPATH: "/ci"
      - CI_ARTEFACTS_HOSTPATH=/ci
```

docker-compose --version
docker-compose version 1.24.0-rc1, build 0f3d4dda

docker-compose.yaml:
```
version: "3.4"
services:
  master:
    environment:
      CI_ARTEFACTS_HOSTPATH: '/ci'
    build:
      context: master
      network: host
    image: buildbot-master
    command: buildbot start --nodaemon master
    ports:
      - 8010:8010
      - 9989:9989
    volumes:
      - ${CI_ARTEFACTS_HOSTPATH}:/ci/artefacts
```

**Comment by agolaszewski** [comment]
@alexei-developer 
Have you solved this issue? I have the same problem

**Comment by Tymek** [comment]
This example may help if you would like to provide default value in docker-compose env:

Use `"${ENV_VAR:-defaultValue}`
```
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL:-postgres://postgres:@postgres:5432/postgres}"
```
Using `.env` can override default url.

**Comment by joelnbl** [comment]
`sudo service redis-server stop` -> `sudo systemctl stop docker` ->` sudo systemctl start docker`

**Comment by zlydenko** [comment]
Still have this issue, passing variables like this `docker-compose --env-file /etc/.env up -d` and receiving `Error while attempting to convert service.dev.ports.published to appropriate type`

**Comment by webdev522** [comment]
My problem is that I am using white space in .env file
You should remove all spaces
```
VAR = VALUE
```

->

```
VAR=VALUE
```

**Comment by smilesrg** [comment]
My problem was that I tried to execute `docker compose` from a subdirectory, not a root directory where `.env` file exists

**Comment by f3ndot** [comment]
For those who can't/don't want to use a `./.env` file you can pass in the same `env_file:` entry as a command line argument and it will work:

```
docker-compose --env-file my/own/specific.env build
```

```
docker-compose --env-file my/own/specific.env up
```

```
# my/own/specific.env
FOO=bar
```

```
# docker-compose.yml

# ...
    build:
      args:
        - FOO=${FOO}
    env_file: my/own/specific.env
# ...
```

**Comment by kmturley** [comment]
Using double dollar signs fixed it for me:
```
web:
  build: .
  environment:
      FOLDER: test
  command: cmake -S ./src -B ./build/$${FOLDER}
```

It is mentioned in the official documentation here:

> You can use a $$ (double-dollar sign) when your configuration needs a literal dollar sign. This also prevents Compose from interpolating a value, so a $$ allows you to refer to environment variables that you don’t want processed by Compose.

```
web:
  build: .
  command: "$$VAR_NOT_INTERPOLATED_BY_COMPOSE"
```

> If you forget and use a single dollar sign ($), Compose interprets the value as an environment variable and warns you:

`The X variable is not set. Defaulting to a blank string.`

https://docs.docker.com/compose/environment-variables/

**Comment by mentamarindos** [comment]
If anyone struggles with it, this is how I solved it

✨
dev.env
```sh
PATH=/etc/nginx/conf.d
```
docker-compose.yml
```bash
env_file: /fullpath/dev.env
volumes:
   - myvolume:\$${PATH}
```
🚩 Important to use `\` and double `$$` to access the variables. At least it works for me :+1:

**Comment by rezan21** [comment]
for me, the issue was running docker-compose with `sudo`. doing the following and running docker-compose WITHOUT sudo helped. https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
