### ISSUE TITLE
introduce docker-compose logs --plain

### ISSUE THREAD

**Issue by pocesar** [docker/compose#4190]
I'm using [bunyan](https://github.com/trentm/node-bunyan) as a stdout / stderr logger, and it outputs the log as JSON, although it can read directly when using `docker logs myserver`, it doesn't work for `docker-compose logs myserver` because it uses colors (although you can disable it with `--no-color`), and put the name of the service name in front as 

![compose](https://cloud.githubusercontent.com/assets/461084/20644961/bbe09762-b431-11e6-898d-b8187d527fd9.png)

this makes the JSON parsing not possible. in practice, I want all the logs from all services, and I can filter them using bunyan command line, and per severity.

**Comment by yicone** [comment]
You can do this:
`docker-compose logs --no-color | grep -o "\{.*" | bunyan`
