### ISSUE TITLE
Allow to take config file content from stdin

### ISSUE THREAD

**Issue by whitecolor** [docker/compose#4198]
Many googd cli tools allows to have something like this:
```bash
cat docker-compose.custom.yml | docker-compose up -f -
```

So that file data would be taken from stdin of previous command in pipe.

**Comment by shin-** [comment]
See https://docs.docker.com/compose/reference/overview/

> Use a `-f` with `-` (dash) as the filename to read the configuration from stdin. When stdin is used all paths in the configuration are relative to the current working directory.

**Comment by whitecolor** [comment]
@shin- 
Hm it seem not to work for me, is my command correct in OP?

**Comment by aanand** [comment]
@whitecolor Put the `-f -` before the `up`:

    $ cat docker-compose.custom.yml | docker-compose -f - up

**Comment by whitecolor** [comment]
thanks)
