### ISSUE TITLE
stopping tail -f with ctrl-c says "error: aborting"

### ISSUE THREAD

**Issue by jeffallen** [docker/compose#4200]
When I use "docker-compose logs -f" to see the logs for a set of containers started with "up -d", and then use "ctrl-c" to stop tailing, I get this:

  ^CERROR: Aborting.

It is not an error that I stopped using tail. The containers are still running, not "aborted". Please do not freak me out. :)

**Comment by stedwick** [comment]
+1

**Comment by Greek64** [comment]
+1

**Comment by jwinnie** [comment]
This is still an issue.

Relevant code: https://github.com/docker/compose/blob/854c14a5bcf566792ee8a972325c37590521656b/compose/cli/main.py#L69-L71

**Comment by tobiasmuecksch** [comment]
I can confirm this issue still remains (on `macOS` in my case)

`docker-compose version 1.27.4, build 40524192`

**Comment by kell18** [comment]
Hello! Any news on this one? The problem persists for `docker-compose version 1.29.2, build 5becea4c`

**Comment by nicolaevladescu** [comment]
We have been sacked by stale bot. Issues still persists, maybe a new issue should be created.

**Comment by jeffallen** [comment]
of course, by the time I got around to submitting a PR for this in the Python version, there's already a Go version. Which undoubtedly has a different bug like this. Sigh.

**Comment by UP2022742** [comment]
Still an issue.
