### ISSUE TITLE
How to render the effective docker-compose.yml 

### ISSUE THREAD

**Issue by JensPiegsa** [docker/compose#4202]
I wonder whether there is a way to render the "effective" `docker-compose.yml` file. The one that results from merging all declarations in `docker-compose.yml` and `docker-compose.override.yml `.

**Comment by aanand** [comment]
Yep, this is what the `config` command is for:

    $ docker-compose config

**Comment by JensPiegsa** [comment]
Ah, thanks. Great to see what's going on. :-)
