### ISSUE TITLE
Option to skip port binding

### ISSUE THREAD

**Issue by jaschweder** [docker/compose#4204]
Sometimes is important to not bind the port's specified in ``docker-compose.yml`` file or skipping it, like when running in CI environment, single run with multi nodes, etc.

Is there any option to skip the port binding in compose or docker ?

Thanks.

**Comment by paunin** [comment]
I got a script for that ;) As there is no option like you need... neither me.
https://github.com/paunin/docker-compose-v2-ports-remover

**Comment by jaschweder** [comment]
thanks @paunin
