### ISSUE TITLE
Support of storage driver options per container

### ISSUE THREAD

**Issue by lutskanu** [docker/compose#4210]
It wolud be perfect to add "--storage-opt" flag to docker-compose service parameters:
https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md#set-storage-driver-options-per-container

It will be very useful for constraining storage size for specific containers.

**Comment by jemc** [comment]
I'm running a rather poorly-behaved container in `docker-compose` that tries to fill up available disk space with a cache, and need to limit the disk space that the particular container can use. To do this, I need to specify storage options in `docker-compose`.

**Comment by shin-** [comment]
Fixed by #4956
