### ISSUE TITLE
docker-compose empty volumes when specifying a host

### ISSUE THREAD

**Issue by MatthewMiele** [docker/compose#4215]
Im not to sure where this issue lies or if its even an issue (might be something thats not supported?) but as I could not find any documentation on this I am opening this ticket.

I have Docker installed on Windows 10 (using HyperV) and I have docker-compose installed in Bash for Windows. docker-compose is installed via pip and is the Linux version.

The problem is that when I run my container using ` docker-compose -H tcp://0.0.0.0:2375` the volumes that are defined in my compose file are not mounted properly. It only seems to make the folders that appear in that directory, but when looking inside the mounts, in the container, they are empty.

When running the exact same command directly from Windows (not in Bash for Windows), the mounts work.

Im thinking maybe volumes are generally not supported when specifying a host? even though technically its the same machine in this case.

I hope that makes sense :)

**Comment by shin-** [comment]
I'm thinking it might rather be an issue of `Bash for Windows` confusing Compose about the underlying OS and/or filesystem.

**Comment by MatthewMiele** [comment]
Confusing in which way? To Compose it sees it's as it would on Ubuntu. It
doesn't see or know anything about there being Windows running Ubuntu.

**Comment by shin-** [comment]
Do you mind sharing your `docker-compose.yml` file?

Compose makes some assumptions on how to parse the paths / volume bindings depending on the OS it's detecting, so WIndows paths might be misinterpreted in that environment.

**Comment by MatthewMiele** [comment]
I have tried with several combinations.

This is the current version which works when using docker-compose in Windows
```
    volumes:
     - ./app:/app
```
This is trying using the full path that the Linux system can access the files on. This result in an empty /app directory
```
    volumes:
     - /mnt/d/Projects/Test/Backend/app:/app
```
This also results in an empty /app directory (The wouldn't match the first case, but its just as a test)
```
    volumes:
     - .:/app
```

My Docker for Windows client has my D:\ drive set as shared.

**Comment by MatthewMiele** [comment]
I have just tested it using the docker client, installed on the Linux side, and using the host of my Windows docker daemon, specifying the options manually and the volume (not using docker compose), and its the same effect.
So I am thinking this is not a compose issue but rather docker itself?

**Comment by shin-** [comment]
Looks like it. You should open an issue on the [docker/for-win](https://github.com/docker/for-win/issues) repo. Feel free to link back to this ticket so we can keep track!
