### ISSUE TITLE
Strange env parsing in the environment variables when passing an url

### ISSUE THREAD

**Issue by cgarnier** [docker/compose#4218]
`- RUST_SERVER_DESCRIPTION="Rust in peace - ts: ts.xxxxxxxxx.com"`
give me this error:
`services.rust.environment contains {"RUST_SERVER_DESCRIPTION=\"Rust in peace - ts": "ts.xxxxxxxxxxxx.com\""}, which is an invalid type, it should be a string`

**Comment by shin-** [comment]
Either
```yaml
environment:
  RUST_SERVER_DESCRIPTION: "Rust in peace - ts: ts.xxxxxxxxx.com"
```
or
```yaml
environment:
  - "RUST_SERVER_DESCRIPTION=\"Rust in peace - ts: ts.xxxxxxxxx.com\""

**Comment by marcelmfs** [comment]
I think it's not only limited to URLs, I'm also trying to trace this error, I believe it happens with any env vars where the value has spaces.

**Comment by shin-** [comment]
It's completely normal behavior due to the presence of an (unquoted) colon in the line, which is interpreted as a key-value separator, so 
```yaml
environment:
  - FOO=bar : baz
```
is translated to (JSON form)
```json
{ "environment": [ { "FOO=bar" : "baz" } ]}
```

which is obviously invalid.

This is not a bug.

**Comment by cgarnier** [comment]
hello,
thanks for the reply. 
But i think something doesnt works well there. Some yaml to json lib parse it correctly.
