### ISSUE TITLE
Connect host network and also custom network

### ISSUE THREAD

**Issue by k2xl** [docker/compose#4227]
I have two containers. App and Database.

I have them both join a network via ```networks```
```
networks:                                                                                                                                    
  custom_network:                                                                                                                           
    driver: bridge                                                                                                                               
```

I also want to have "App" join the host network. The App has some features where it runs `ifconfig` things and needs to have access to the hosts network information.

How can I do this?

**Comment by shin-** [comment]
There's no straightforward way to do that at the moment. See the discussion here for workarounds: https://github.com/docker/compose/issues/3012#issuecomment-216918520

**Comment by ervinb** [comment]
@k2xl By an off change you're on AWS, you can use their [metadata API](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-retrieval) to get information about the host.

For example, running the following line inside a container will get the IPv4 address of the host:
```sh
curl http://169.254.169.254/latest/meta-data/local-ipv4
```
