### ISSUE TITLE
Add support for the --squash flag

### ISSUE THREAD

**Issue by adi1133** [docker/compose#4235]
See https://github.com/docker/docker/pull/22641

**Comment by henryptung** [comment]
Probably relevant: https://github.com/docker/compose/issues/4114

**Comment by MichaelPereira** [comment]
I think that the scope of this ticket could be widened to all `docker build` options as described in [this comment of #4114](https://github.com/docker/compose/issues/4114#issuecomment-260007357) to make it future-proof by automatically supporting all options of `docker-build`

**Comment by ibaralf** [comment]
Is this feature in docker-compose yet? I see that docker build --squash is already available on my docker for mac.

If not yet implemented - is there a workaround? I'm trying to avoid having secrets or access keys in the intermediate images when doing a build.

**Comment by dnephin** [comment]
Multi-stage builds were releases in 17.06 which provide similar functionality to squash but covers a lot more use cases. I think squash may be removed since it never left experimental.

Do multi-stage builds work for your use case?

**Comment by joeyhub** [comment]
Multi-stage builds squash intermediate images together don't they?

That's not the same as what --squash is meant to do which is to squash the layers within an image.

Each command you run in build creates a layer. If you:

     COPY huge.file
     RUN script huge_file && rm huge.file

That'll create a layer that adds huge file and another layer that removes it again!

You can see this if you look at the history for an image.

The idea of squash is to have only one layer in your image, that represents the difference between it and the image it is created from.

I'm new to docker (few days) and have traditionally been creating build images from hand using things such as unionfs, so I might have some misconceptions about what docker is doing. However in this case, it's definitely leaking. I temporarily put a file into the container during build, then remove it once it's processed. I still see it in the history and find it in the auf diff folder however.

At the moment the only way around that I know of is to do things such as wget or nc your resource and pipe it into a processor.

There are other cases where diffs appear to be around which is plain inexplicable. In some cases it appears as if it stores a copy on removal as well.

**Comment by dnephin** [comment]
Here's the issue for removing squash: https://github.com/moby/moby/issues/34565, I forgot to link it earlier.

> Multi-stage builds squash intermediate images together don't they?

No, they don't do any squash, but they do allow for you to build an image that only has the layers you want.

In multi-stage builds the image that gets tagged is just the last "stage", so anything that happens in previous stages will not  be part of the layers of the final image. This lets you perform all the intermediate operations in one or more stages, and in the final stage you have something like this:

```
FROM scratch # or alpine
COPY --from=intermediate file /file
```

which will give you a 1 or 2 layer image, the same as squash.

**Comment by isanych** [comment]
Multi staged builds have nothing in common with squash. Multi stages builds could replace multiple Dockerfiles, squash replaces multiple commands. This code
```
FROM ubuntu

RUN apt-get update -qq \
 && apt-get install -y -qq squid3 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
COPY run.sh /
COPY squid.conf /etc/squid/
EXPOSE 3128
CMD ["/run.sh"]
```
Produces 5 images and it's harder to read and maintain because of tricks lowering number of images .
Below code looks better and easier to maintain and produces only 1 image with --squash
```
FROM ubuntu

RUN apt-get update -qq
RUN apt-get install -y -qq squid3
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
COPY run.sh /
COPY squid.conf /etc/squid/
EXPOSE 3128
CMD ["/run.sh"]
```

**Comment by adi1133** [comment]
@dnephin multi-stage builds fixed my issue, I no longer need squash.
Thanks !

**Comment by johnthagen** [comment]
There is still interest in moving `--squash` out of experimental, as explained here. As squash is still useful to use in combination with multi-stage builds: https://github.com/moby/moby/issues/38657

**Comment by mskoenz** [comment]
The issue with just multistage build (via COPY --from) is that it does not preserver parent settings like USER, ENTRYPOINT or WORKDIR. Is there a way to get USER --from parent?

**Comment by svoop** [comment]
Also, `COPY --from` is tricky when Docker runs with `userns-remap` enabled. I haven't found any solution to prevent the following so far:

> Service 'web' failed to build : failed to copy files: failed to copy directory: Error processing tar file(exit status 1): Container ID 100042 cannot be mapped to a host ID
