### ISSUE TITLE
Feature request: add support for starting container from checkpoint

### ISSUE THREAD

**Issue by tswift242** [docker/compose#4241]
Checkpoint/restore support was merged into Docker in https://github.com/docker/docker/pull/22049, and will be released in Docker 1.13. Thus, add support for starting a container from a checkpoint in a compose file.

**Comment by ImVexed** [comment]
Suppose it's time for a bump! Any work being done on this?

**Comment by edurenye** [comment]
I guess it will not happen until the feature does not leave the state of 'experimental' so we should put some pressure there. https://docs.docker.com/engine/reference/commandline/checkpoint

**Comment by ndeloof** [comment]
Internally tracked as https://docker.atlassian.net/browse/COMPOSE-93

**Comment by edurenye** [comment]
Any progress on this?
Another related resource: https://criu.org/Docker

**Comment by unixfox** [comment]
Still interested

**Comment by edurenye** [comment]
This would be great for Docker compose, still interested.
