### ISSUE TITLE
Running compose on remote host error

### ISSUE THREAD

**Issue by mightyuser** [docker/compose#4242]
I have been running docker commands on remote host (swarm cluster in cloud) using host parameter as shown below.

`docker -H 10.10.10.10:2375 version`

Similarly, docker-compose also has -H parameter, as mentioned [here](https://docs.docker.com/compose/reference/overview/)

I am running docker-compose version 1.6.2, which throws error when -H parameter is provided. It seems that host parameter is not supported in this version. 

How can I can point docker-compose to remote host on this machine.

**Comment by shin-** [comment]
docker-compose 1.6.2 is too old and doesn't support the `-H` parameter. You're going to need to upgrade to a more recent version. If that's not an option for some reason, you should be able to use the `DOCKER_HOST` environment variable instead.
