### ISSUE TITLE
Docker for Mac not keeping `docker-compose` up to date

### ISSUE THREAD

**Issue by avindra** [docker/compose#4244]
1. DFM version:

![screen shot 2016-12-13 at 4 58 42 pm](https://cloud.githubusercontent.com/assets/126848/21161227/b480d528-c155-11e6-882b-b84b56388301.png)

2. Checking for updates:

![screen shot 2016-12-13 at 5 01 03 pm](https://cloud.githubusercontent.com/assets/126848/21161243/c63ecc8e-c155-11e6-948a-c28b248218b5.png)

3. 
```
$ docker-compose --version
docker-compose version 1.8.1, build 878cff1
```

**Comment by shin-** [comment]
Hi,

This should be reported at https://github.com/docker/for-mac !
