### ISSUE TITLE
`docker-compose throws Traceback error

### ISSUE THREAD

**Issue by mightyuser** [docker/compose#4251]
I am trying to run `docker-compose -f abc.yml up –d`  command, which throws below error.

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 56, in main
  File "compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "compose/cli/docopt_command.py", line 26, in dispatch
  File "compose/cli/main.py", line 191, in perform_command
  File "compose/cli/main.py", line 657, in up
  File "compose/project.py", line 308, in up
  File "compose/project.py", line 156, in get_services_without_duplicate
  File "compose/project.py", line 144, in get_services
  File "compose/project.py", line 115, in get_service
  File "compose/project.py", line 416, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

Initially I thought this may be due to Unicode characters in the compose files. However, all of them use the ASCII charset and could not find the â character (0xe2) specified in the error message above.

I did find similar issues already reported but in some threads users suggested to upgrade docker compose to 1.1, etc. while in other threads they mentioned Unicode characters in filenames as the culprit, which doesn't seem to be the issue in this case.

I have docker-compose **1.6.2** and both 2.x (**2.7.6**) and 3.x (**3.4.3**) versions of Python on machine.

Python 2.x uses ascii encoding by default whereas Python 3.x uses the utf-8 encoding. I changed the default ascii encoding in Python 2.x by updating sitecustomize.py and now both are using utf-8 encoding but that didn't resolve the issue either.

It may be noteworthy that I am running this via SSH.

**Comment by shin-** [comment]
I believe this was fixed in Compose 1.9.0 - I highly recommend upgrading.

**Comment by mightyuser** [comment]
As I am having a big Swarm cluster in cloud, this is not an easy option for me. I just want to be sure that is the only solution and will fix the issue. Can somebody confirm this.

Also, can I upgrade just master where I am running the docker-compose or I have to upgrade all the nodes.

If I upgrade Compose, what are the other related components that I need to upgrade. Is there any page / documentation available for the upgrade.

**Comment by shin-** [comment]
You only have to upgrade Compose on the machine you run it from, as it is client-only software that interfaces directly with the Docker Engine. Your cluster is fine as it is.

Upgrading should be seamless, but there are a few changes in behavior for some commands that you should note. Please see the "Breaking Changes" sections in the [Changelog](https://github.com/docker/compose/blob/master/CHANGELOG.md) for those.

**Comment by mightyuser** [comment]
This is very disturbing and there seems to be something fundamentally wrong here.

Here is what I am have done,

- I have created a Swarm cluster in Azure
- Connected to master node using SSH
- Pointed to cluster endpoint
- Now I running the docker-compose command to run a service/container

This is the most basic scenario that I can try in Azure Swarm cluster, which has docker-compose 1.6.2 installed by default. If this basic scenario does not work then how I am supposed to work with Azure cluster.

There may be updates, new versions, etc. that may have released in the meantime but I want to only try the basic setup of Azure cluster and for that why do I need to upgrade the master node that was created by Azure. It should work with what is already installed on it.

I don't want to uninstall/install stuff on the master node and disturb the Azure cluster itself. Also, many people have issues in upgrade as well, so that also doesn't seem to be very straight forward solution.

**Comment by shin-** [comment]
I'm sorry - I am not responsible for what version of our software the Azure team decides to make available to their users. 

Compose is continuously being improved and bugfixes are implemented as needed. We strive to address issues and provide support, but if you're not willing to install a version that *has* these bugfixes, I am not exactly sure how you expect me to help.

**Comment by mightyuser** [comment]
Thanks @shin- , there are two things here:

1.  For upgrade, I need your help, can you please point me to documentation about how to upgrade from 1.6 to 1.9. As mentioned, people follow some guides and end up in a bad state. 
2. What exactly is the issue, does it mean we cannot run yml files in docker-compose 1.6 version?
