### ISSUE TITLE
Feature Request: Please provide checksum in the download section on the release page

### ISSUE THREAD

**Issue by twang2218** [docker/compose#4264]
Currently, there is no checksum in the download section on the release page:

It would be great if there is a checksum file for those binaries, so we can verify the downloaded file's integrity. Thanks.

**Comment by shin-** [comment]
Thank you - we'll take it into consideration.

**Comment by soulne4ny** [comment]
***It would be excellent to gpg-signed checksum.***

As well it would be wonder to have binary-release of docker-compose installable in the way the docker engine itself via .deb and .rpm.

**Comment by sanmai-NL** [comment]
@shin-: Could you please inform us what the outcome is?

**Comment by sanmai-NL** [comment]
Duplicate of #3480.

**Comment by shin-** [comment]
Added checksums on the release page for the newest release https://github.com/docker/compose/releases/tag/1.17.0

I know there's more we could do (#5235 #3480), but hopefully that's a reasonable start.
