### ISSUE TITLE
JSON schema validator: schemas v2.0 and 2.1 are not valid

### ISSUE THREAD

**Issue by gulien** [docker/compose#4271]
Hi guys,

It seems that [config_schema_v2.0.json](https://github.com/docker/compose/blob/master/compose/config/config_schema_v2.0.json) and [config_schema_v2.1.json](https://github.com/docker/compose/blob/master/compose/config/config_schema_v2.1.json) are not valid schemas.

The online validator [JSON Schema Validator](http://www.jsonschemavalidator.net/) throws the following errors:

[config_schema_v2.0.json](https://github.com/docker/compose/blob/master/compose/config/config_schema_v2.0.json):
> Unexpected token encountered when reading value for 'additionalProperties'. Expected StartObject, got Boolean. Path 'definitions.volume.properties.additionalProperties', line 280, position 37.

[config_schema_v2.1.json](https://github.com/docker/compose/blob/master/compose/config/config_schema_v2.1.json):
> Unexpected token encountered when reading value for 'additionalProperties'. Expected StartObject, got Boolean. Path 'definitions.volume.properties.additionalProperties', line 287, position 37.

I also tried to validate them using [avj](https://github.com/epoberezkin/ajv) library but the result was the same for both files.

My first guess is that `"additionalProperties": false` should be removed as it does not appear anymore in [config_schema_v3.0.json](https://github.com/docker/compose/blob/master/compose/config/config_schema_v3.0.json#L316).

**Comment by shin-** [comment]
Thank you for the report! Fix is in #4297
