### ISSUE TITLE
Make https://hub.docker.com/r/docker/compose/ more usable

### ISSUE THREAD

**Issue by tmaier** [docker/compose#4287]
https://hub.docker.com/r/docker/compose/
Common use case for this repo: Run docker-compose within a CI pipeline, which is based on docker-in-docker.

As MVP, please do the following:
- [ ] Add a reference to the `Dockerfile` which is being used here
- [ ] Add automated build from repo
- [ ] Add automated build when the dependent image `alpine` has been updated
- [ ] Add a `latest` tag

On top of this, please consider
- [ ] Add explanation how to use this together with `docker:dind`

**Comment by tmaier** [comment]
This might get obsolete if https://github.com/docker-library/docker/pull/30 gets merged.

**Comment by mathroc** [comment]
I would also suggest to follow [Dockerfile best practices about entrypoint](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/entrypoint)

right now I can't use it in gitlab CI because it tries to run sh in the image but it results in trying to run `docker-compose sh`

**Comment by tianon** [comment]
I'd be curious to know the opinion of Compose maintainers on https://github.com/docker-library/docker/pull/30 -- should `docker:compose` be created?  Should we instead continue to punt users asking for it to the officially-upstream-maintained `docker/compose` image?  Should we look to create a new `docker-compose` official image?

(Happy to help with or implement any of these, but I'd rather not move forward on any of this without the support and/or blessing of the Compose maintainers. :smile:)

**Comment by yxliang01** [comment]
+1 for making docker-compose image as an official image @tianon

**Comment by tianon** [comment]
My comment at https://github.com/docker/compose/issues/4287#issuecomment-305615695 is still pretty much verbatim the same set of questions I'd have for maintainers here (although I'd probably be less keen on the `docker:compose` variant now).

I'm happy to do the legwork to make/maintain an image for this, but I don't want to step on any toes or go against maintainer's wishes.
