### ISSUE TITLE
[feature] fig.yml support multy command

### ISSUE THREAD

**Issue by pahaz** [docker/compose#429]
sometimes I want doing somthing like this

     command:
       - "python manage.py collectstatic --noinput"
       - "python manage.py syncdb --noinput"
       - "echo 'Hi'"
       - "gunicorn -b 0.0.0.0:8000 _project_.wsgi --log-level debug --log-file -"

What the problem.
I can't add `manage.py collectstatic` to `Dockerfile` because I use volume `.:/code` wich is not supported for `Dockerfile`.

Now I should usr `fig run` command but I want use simpe `fig up`.

Other solution may be something like this:

     hook_after_build:
       - "python manage.py collectstatic --noinput"
       - "python manage.py syncdb --noinput"
       - "echo 'Hi'"
     command:
       - "gunicorn -b 0.0.0.0:8000 _project_.wsgi --log-level debug --log-file -"

what do you think about this?

**Comment by dnephin** [comment]
Thanks for the feature suggestion!

Unfortunately this is not really possible with docker. There is only one run command. You could add a bash script to the image that runs these commands for you, but that's the only way I see this working.
