### ISSUE TITLE
docker-compose exec issue

### ISSUE THREAD

**Issue by joemewes** [docker/compose#4290]
Im not sure why/what is going wrong with this, but Im trying to refactor some docker exec commands I use to docker-compose exec so I don't have to rely on grep name workaround for dynamic container names.

example OLD docker exec command I use is -
```
docker exec -i $(docker ps --format {{.Names}} | grep db) mysql -u dev -pDEVPASSWORD dev_db < latest.sql
```

An example docker-compose exec command that IS working is - 
```
docker-compose exec -T db mysql -u dev -pDEVPASSWORD -Bse "create database dev_db;"
```

But when I try to execute the standard mysql import nothing happens -  
```
docker-compose exec -T db mysql -u dev -pDEVPASSWORD dev_db < latest.sql
```

It just hangs. thing only things that show in the mysql.log for the last command is the rolling - 
```
170104 19:50:37	   82 Connect	dev@localhost as anonymous on dev_db
		   82 Query	select @@version_comment limit 1
```

thoughts? ideas?

Am I missing something?

Happy to provide any more info or run any tests that may help diagnose if this even is an issue.

thanks

**Comment by hubo1016** [comment]
It seems that -T not only remove the tty, it also set OpenStdIn=False. There should be a separated -I option.

**Comment by hubo1016** [comment]
Also, remove -T does not work on stdin redirection, seems that docker-compose tried to set some ioctl options on the stdin file which raises exceptions when the stdin is NOT a console.

**Comment by fuzzy76** [comment]
+1 – is there really no way to pipe output from the host to a container using docker-compose?

**Comment by fuzzy76** [comment]
A seemingly similar issue was solved for docker-compose run in #1313

**Comment by joemewes** [comment]
Its been a while since this was reported.  I'll test again this week and come back with feedback of my original issue.  thanks

**Comment by hubo1016** [comment]
@joemewes currently my work around is parsing the container id with docker-compose ps and using docker exec instead.

**Comment by z4c** [comment]
Doesnt seem to work for me.

docker-compose version 1.10.1, build b252738

Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 88, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 140, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 485, in exec_command
    pty.start()
  File "/usr/local/lib/python2.7/dist-packages/dockerpty/pty.py", line 338, in start
    io.set_blocking(pump, flag)
  File "/usr/local/lib/python2.7/dist-packages/dockerpty/io.py", line 32, in set_blocking
    old_flag = fcntl.fcntl(fd, fcntl.F_GETFL)
ValueError: file descriptor cannot be a negative integer (-1)

**Comment by vshih** [comment]
The mismatch between `docker-compose exec`'s sole -T option and `docker exec`'s -i and -t options is discussed in https://github.com/docker/compose/issues/3352.

**Comment by joemewes** [comment]
I'm using the same workaround solution mentioned at the end of that thread 
```
docker exec -i $(docker-compose ps -q mysql) mysql -u <MYSQL_USER> -p<MYSQL_PASS> db_name < /path/to/import/mysqldump.sql
```
Is this actually an issue then? or just 'the way it works' ??

**Comment by pscheit** [comment]
does not work on windows, though .. ;)

**Comment by jasonrhaas** [comment]
Normally when I run `docker-compose exec` in my regular shell it works fine.  However I was running into issues when trying to run `docker-compose exec` in a crontab.

Adding the `-T` fixed this.

Heres an  example crontab that works:

```
APPDIR="/opt/foobar"
DOCKER_COMPOSE="/usr/local/bin/docker-compose"

cd $APPDIR && $DOCKER_COMPOSE exec -T myapp bash -c 'python helloworld.py'
```
