### ISSUE TITLE
Bug: Ignored file *does* exist, but is ignored.

### ISSUE THREAD

**Issue by stampycode** [docker/compose#4296]
When using the `.dockerignore` file, the warning when trying to use a file that matches this list is output as if the file doesn't exist at all, whereas it is actually just being ignored.
This took me some time to figure out, and should be made clearer.

The file *does* exist, it is just being ignored - the error message should say so.

`.dockerignore`
```
bbb
```

`Dockerfile`
```
FROM busybox:latest
ADD aaa bbb
```

`docker build .` output:
```
Sending build context to Docker daemon  8.08 MB
Step 1 : FROM busybox:latest
 ---> 1efc1d465fd6
Step 2 : ADD aaa bbb
lstat bbb: no such file or directory
```

**Comment by stampycode** [comment]
Hey @vdemeester, fair points, I will re-open this in `docker/docker` if you think it worthwhile.

Isn't there a way the `.dockerignore` file could be bundled into the tar, so that at least when the 'file not found' error happens the file path could be checked in the ignore files list? Seems to me the internal workings are irrelevant, the problem is Docker is saying the file doesn't exist, when the user can clearly see that it does. The context (tar file) is hidden from the user, so actually the error is taken "out of context" so to speak.

**Comment by shin-** [comment]
I'm going to close this issue - as @vdemeester pointed out it is not a Compose issue.

Feel free to x-post to the docker/docker issue tracker!
