### ISSUE TITLE
1.10.0-rc1 docker compose doesn't work with slashes in .dockerignore file.

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [docker/compose#4302]
With latest 1.10.0-rc1 docker compose, slash in .dockerignore cannot be recognized. It will have **below** errors with this .dockerginore file.
```
*
!obj/Docker/publish/*
!obj/Docker/empty/
```
**Building webapplication1
Service 'webapplication1' failed to build: GetFileAttributesEx obj\Docker\empty\: The system cannot find the path specified..**

Note: slash works well in 1.9.0.

**Comment by shin-** [comment]
Thanks for the report!

Caused by docker/docker-py#1277

Current workaround: use backslashes in `.dockerignore` instead.
