### ISSUE TITLE
Resolve all passed files before throwing the "env variable not set" warning

### ISSUE THREAD

**Issue by dkarlovi** [docker/compose#4335]
[I have a setup](https://github.com/dkarlovi/docker-nginx-node-sample) where I setup the "main" `docker-compose.yml` and then override per environment with `docker-compose.dev.yml`, `docker-compose.prod.yml`, etc. There's a warning which gets cast, but it's not valid so please consider fixing it.

Say I have

    # f1.yml
    version: '2.1'
    services:
      test:
        image: hello-world
        environment:
        - MY_VAR="${MY_VAR}"

and

    # f2.yml
    version: '2.1'
    services:
      test:
        environment:
        - MY_VAR="specified"

If I run `docker-compose -f f1.yml -f f2.yml up`, I get `WARNING: The MY_VAR variable is not set. Defaulting to a blank string.` which is not true as the container indeed gets the value specified in `f2.yml`.

As this is currently the only way (I know of) to have env-specific configuration, it would be great if the warning was not cast improperly as it needlessly confuses.

**Comment by Umkus** [comment]
You should probably set your `MY_VAR` to a default static value in the main compose file for additional compose files to override.

**Comment by dkarlovi** [comment]
@Umkus it's more flexible to leave it as is, this way you can do `MY_VAR=abc123 docker-compose up` without specifying the files, load it from an `.env` file or even use the same env var for two (predefined) container vars, for example

    services:
      app:
        image: php:latest
        environment:
          # expected name = DATABASE_USER
          DATABASE_USER=${DATABASE_USER}
      db:
        image: mysql:latest
        environment:
          # expected name = MYSQL_USER
          MYSQ_USER=${DATABASE_USER}

**Comment by Umkus** [comment]
I might be wrong, but this
```yaml
  environment:
    DATABASE_USER=${DATABASE_USER}
```
reads: _use value of `DATABASE_USER` if `DATABASE_USER` doesn't exist._ Which is mutually exclusive.

If you plan to pass in these env vars from shell/.env anyway, why not drop the default variable value altogether?

```yaml
  environment:
    - DATABASE_USER
```

**Comment by dkarlovi** [comment]
@Umkus I have two sets of variables: environment-specific "static" variables and runtime variables.

For example, when setting up a Node container, you'd have

    # docker-compose.yml
    services:
      app:
        environment:
          - NODE_ENV=${NODE_ENV}
          - DATABASE_USER=${DATABASE_USER}

    # docker-compose.dev.yml
    services:
      app:
        environment:
          - NODE_ENV=dev

    # docker-compose.prod.yml
    services:
      app:
        environment:
          - NODE_ENV=prod

    # .env
    DATABASE_USER=someuser

This way you can ship configurations for your container per environment, but still override any of it during execution.

The reason why I'm repeating the variable name is to make it explicit it's the same variable as `MYSQL_USER` one [in my previous example](https://github.com/docker/compose/issues/4335#issuecomment-279411887).

**Comment by Umkus** [comment]
From what I could read in the python code - indeed compose interpolates env vars for every service first before it merges them together.

But, again, you can already fix this by restructuring your configs properly.

**Comment by dkarlovi** [comment]
> properly

is quite a loaded term. :)
