### ISSUE TITLE
deploy.replicas doesn't work with environment variables

### ISSUE THREAD

**Issue by kinghuang** [docker/compose#4347]
**Description**

`services.service.deploy.replicas` in Compose file version 3 with Docker Compose 1.10-rc2 doesn't seem to work with environment variables. If a variable instead of a literal integer is used, then Docker Compose says it contains an invalid type

**Steps to reproduce the issue:**

1. Create a compose file where the value for replicas is a variable instead of a literal integer, like the following.

```yaml
version: '3'
services:
  node-chrome:
    image: selenium/node-chrome:3.0.1
    deploy:
      replicas: $NUM_NODES_CHROME
```

2. Define a value for NUM_NODES_CHROME. In my case, I declared NUM_NODES_CHROME=2 in a `.env` file.

**Describe the results you received:**

Docker Compose says that replicas contains an invalid type.

```
ERROR: The Compose file './selenium.yml' is invalid because:
services.node-chrome.deploy.replicas contains an invalid type, it should be an integer
```

**Describe the results you expected:**

Docker Compose should substitute `$NUM_NODES_CHROME` with `2`, treating the value as an integer.

**Output of `docker-compose --version`:**

docker-compose version 1.10.0-rc2, build fb241d0

**Comment by shin-** [comment]
This is complex, as environment variables are always expanded to string values. Even if unintuitive, Compose is behaving according to the rules here.

cc @dnephin : You might have more thoughts on the issue. We could allow string values and parse them for integers potentially.

**Comment by dnephin** [comment]
This has been an issue for a while, see #2730. 

There's an old proposal PR to address this and cast to the type in the schema. It is indeed a difficult problem, but I think using the schema type and casting is a reasonable approach.

If we had a different variable syntax we might be able to include type hints with the variable, but it's too late for that I think.

**Comment by GabKlein** [comment]
Do you guys have a workaround for this issue?

**Comment by hutchic** [comment]
Yeah it's not pretty though. Make a docker-compose.yml template using language / library of your choosing (Python / Jinja). Have it substitute the values then run docker-compose

**Comment by rca** [comment]
This just bit me, I'm sad.  Solved the issue in a similar manner to hutchic above.  I felt like throwing out this suggestion just in case it makes sense:  why not perform a pre-pass, replacing variables with the environment values, then letting whatever YAML parser do what it does.  This, more or less, sums up what I ended up doing to resolve my problem.

**Comment by bradmccormack** [comment]
This just bit me too. Hopefully, this gets implemented.

**Comment by slopokeit** [comment]
+1

**Comment by magrossi** [comment]
+1

**Comment by shin-** [comment]
#5291

**Comment by bitsofinfo** [comment]
+1

**Comment by timansky** [comment]
+1

**Comment by YoussefOuirini** [comment]
With the most recent version 1.23.1 (also with version 1.18.0) I am still having this problem when trying to make replica's in docker-compose file a environment variable integer:

> Docker version 17.09.0-ce, build afdb6d4
> docker-compose version 1.23.1, build b02f1306
> services.feedback-service.deploy.replicas must be a integer

**Comment by shin-** [comment]
You might want to create a proper bug report then.

**Comment by rca** [comment]
@YoussefOuirini a bit of a shameless plug for [Compose Flow](https://github.com/openslate/compose-flow); a tool I wrote to manage deployment workflows on Docker and Swarm.  Among other things, it addresses placing settings like replicas in environment variables.

**Comment by GuillaumePoignon** [comment]
With docker-compose 2.6.0 I can't set `deploy.replicas` with env var
`services.mqtt_receiver.display.deploy.replicas must be a integer`

```
services:
  myservice:
  ...
  deploy:
    replicas: ${MY_SERVICE_REPLICAS:-1}
```

**Comment by gpoignon** [comment]
if it helps some people I noticed that the problem came from the name of the service

this file generates the error because it has the character `.` in service name

```
services:
  my.service:
    image: nginx
    deploy:
      replicas: ${REPLICAS:-1}
```

but not this one because I replaced the `.` by `-`

```
services:
  my-service:
    image: nginx
    deploy:
      replicas: ${REPLICAS:-1}
```

But I do not know why
