### ISSUE TITLE
env variables ordering

### ISSUE THREAD

**Issue by k2xl** [docker/compose#4354]
I'm trying to figure out the hierarchy of how docker compose does environment variables

If I have a compose file that uses a `env_file`, does that override anything defined in the docker-compose?

What about environment variables defined in the compose file that inherit from the host (without the equal sign)? And what about environment variables defined in another `extend`ed file? I couldn't find documentation related to the ordering.

A more clear example:
```
env_file: .env
environment:
  - MYVAR=123
  - MYVAR2
```
.env:
```
MYVAR=321
MYVAR2=hello
```
The docs say that the shell values take precedent, but let's assume MYVAR2 is NOT defined on the host, will that get overridden by values in the .env?

**Comment by shin-** [comment]
Asked and answered, I believe: #4331

**Comment by k2xl** [comment]
Hi shin,

Sort of answered - what happens if the variable is not defined on host but specified in the docker compose? Should it be a blank value?

**Comment by shin-** [comment]
The behavior is equivalent to that of the CLI when `docker run` is invoked with `--environment`.

> When no `=` is provided and that variable is not defined in the client’s environment then that variable will be removed from the container’s list of environment variables.

HTH!
