### ISSUE TITLE
Cannot open self /usr/local/bin/docker-compose or archive /usr/local/bin/docker-compose.pkg. (in ubuntu14.04 amd64)

### ISSUE THREAD

**Issue by liujunjiun** [docker/compose#4362]
I install it by pip, and code as follow:
pip install docker-compose
chmod a+rx /usr/local/bin/docker-compose 

so, please tell me how can I do?

**Comment by lynn-long** [comment]
same error

**Comment by doubimike** [comment]
same error

**Comment by zhaixue** [comment]
how to do?

**Comment by m1m6** [comment]
Same ere

**Comment by yuezhongxin** [comment]
same error

**Comment by AnthonyMastrean** [comment]
Related to #1135?

**Comment by sochi** [comment]
Note that the same error occurs if the docker-compose is corrupted (e.g., a network error when downloading via curl).
Cross-check that the sha265sum of the file is matching the ones listed: https://github.com/docker/compose/releases. If not, redownload the corrupted file.

**Comment by armoour** [comment]
i met this problem too and i finally solved this by downloading docker-compose with the 
[docker-compose-Linux-x86_64](https://github.com/docker/compose/releases/download/1.23.0-rc1/docker-compose-Linux-x86_64) rather than by curl command.

**Comment by vectorsigma** [comment]
I ran into this problem with a completely different project (MIT App Inventor).  The TL;DR is that they way PyInstaller builds its executables makes them break if they're `strip`ped or if `prelink` runs against them.  This was supposed to be addressed [here](https://github.com/pyinstaller/pyinstaller/issues/1812), but in the mean time, you can drop a file in `/etc/prelink.conf.d/` with the contents of `-b /path/to/docker-compose` and that should keep prelink from mangling it.

**Comment by csrftoken** [comment]
same error

**Comment by Bhanuchander210** [comment]
Same error. Download using curl not working. So I just followed as @armoour commented. Now it is working fine.
[docker-compose](https://github.com/docker/compose/releases/download/1.23.0-rc1/docker-compose-Linux-x86_64)

**Comment by ijc** [comment]
I see this is an ancient issue, but since it doesn't follow the template there is not enough information in either the original post or all the "same" posts to make progress, therefore I am closing, if you are still have problems then please open a new issue and provide all of the information requested by the "Bug Report" template you will be presented with.

**Comment by deepak6446** [comment]
download from https://github.com/docker/compose/releases don't use curl
rename file as docker-compose and place in /usr/local/bin/
provide rx permission to file
and check docker verison

**Comment by Enigma228322** [comment]
Solved with this: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

**Comment by davidshare** [comment]
> i met this problem too and i finally solved this by downloading docker-compose with the
> [docker-compose-Linux-x86_64](https://github.com/docker/compose/releases/download/1.23.0-rc1/docker-compose-Linux-x86_64) rather than by curl command.

This did not work for me either.

**Comment by davidshare** [comment]
> Solved with this: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

This doesn't work for me on ubuntu

**Comment by davidshare** [comment]
> download from https://github.com/docker/compose/releases don't use curl
> rename file as docker-compose and place in /usr/local/bin/
> provide rx permission to file
> and check docker verison

doesn't work for me

**Comment by RusmanCool** [comment]
I had a similar error message. Here is how I have resolved it:

1. Check the file's permission flags: `ls -al /usr/local/bin/docker-compose` It should show something like: `-rwxr-x--- 1 root root 17586312 May 18 08:02 /usr/local/bin/docker-compose`
2. Make sure your user(like root or any other) is either is **root** or is in **root** group based on the above returned result.
If your user is NOT in either of above in step#2, then:
1. Add read and execute permissions to 'other' groups: chmod o+rx /usr/local/bin/docker-compose
2. And be a happy camper now :) 

P.S. make sure you are changing or checking permissions of the actual file and not a link to it!

**Comment by 17797751615** [comment]
> download from https://github.com/docker/compose/releases don't use curl
> rename file as docker-compose and place in /usr/local/bin/
> provide rx permission to file
> and check docker verison

useful，problem fix.

**Comment by StefanRickli** [comment]
This is a documentation issue.

Followed the installation procedure according to https://docs.docker.com/compose/install/#install-compose-on-linux-systems.
(debian/buster here)

Ran into the same problem today while setting up Gitlab-Runner.
Solved it by setting file permissions for `docker-compose` to 755.

The installation manual should be updated accordingly.
