### ISSUE TITLE
Path with forward slash in DOCKER_CERT_PATH not handled on Windows

### ISSUE THREAD

**Issue by dessant** [docker/compose#4364]
Setting `/d/certs/cluster1` for `DOCKER_CERT_PATH` results in this error:
```
$ winpty docker-compose exec nginx bash
ERROR: TLS configuration is invalid - make sure your DOCKER_TLS_VERIFY and DOCKE
R_CERT_PATH are set correctly.
You might need to run `eval "$(docker-machine env default)"`
```

While using `D:\\certs\\cluster1` works as expected:
```
$ winpty docker-compose exec nginx bash
bash-4.3# 
```

Tested with compose 1.10.

**Comment by shin-** [comment]
That seems correct to me?

**Comment by dessant** [comment]
Docker supports paths with forward slashes on Windows. The same is true for declaring host volumes in compose files. It makes sense to handle it for this env var too.

**Comment by shin-** [comment]
Thanks. We'll have to take a closer look.

**Comment by chrsoo** [comment]
I have a problem logging in to DTR for a UCP 2.2.5 deployment. The terminal is GitBash/Mintty on Windows 10.

**There is no problem problem with building, tagging etc.** Logging in to DTR using username/password works fine but I would like to use the client bundle.
````
$ docker -v
Docker version 17.12.0-ce, build c97c6d6

$ env | grep -i docker
DOCKER_CERT_PATH=/c/dev/.docker/admin
DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://10.0.0.10:443

$ winpty docker login 10.0.0.11
could not read CA certificate "\\c\\dev\\.docker\\admin\\ca.pem": open \c\dev\.docker\admin\ca.pem: The system cannot find the path specified.
````

If I leave out the `winpty` part I get the error 
````
$ docker login 10.0.0.11
Error: Cannot perform an interactive login from a non TTY device
````
