### ISSUE TITLE
Allow providing base version as argument

### ISSUE THREAD

**Issue by OlivierDupre** [docker/compose#4365]
As shown on in the official doc: https://docs.docker.com/compose/compose-file/#args you can pass arguments from docker-compose to the build process. 
But, the Dockerfile must start with directive `FROM`, and an argument is available only after calling `ARG your-arg-name`.
So one cannot provide base version through build argument.

Could it be possible to make this working? So we can call something like this: `FROM ubuntu:$UBUNTU_VERSION`?

**Comment by shin-** [comment]
This would be a question for [docker/docker](https://github.com/docker/docker).
