### ISSUE TITLE
TTY/text editors broken behavior (OSX)

### ISSUE THREAD

**Issue by suan** [docker/compose#437]
I understand this issue is probably 1) not a fig bug and 2) very complex and has a lot of environmental factors, but would appreciate if someone could point to to the right direction.

When I use any text editor via fig, e.g. `fig run vim <foo>`, I get the following issues:
- The first time, the cursor is missing, and hitting direction keys does nothing.
- After I `:q` and `fig run vim <foo>` again, the cursor is present and responsive, but the screen is cutoff, like so:
![screen shot 2014-08-23 at 1 19 57 pm](https://cloud.githubusercontent.com/assets/192727/4021461/4b389c6c-2af4-11e4-87c9-3394a22d9bb6.png)
- After continually paging down, then slowly scrolling up, then screen does finally get filled.

Is the complexities of interactive file editing just too much for fig+Docker+boot2docker to handle, and best left to NFS-mount-local-editing-type solutions? (I have tried both vim-box, vim-gtk, and nano)

**Comment by dnephin** [comment]
Are you still able to reproduce this?  The issue a year old, and we've made lots of improvements since then.

**Comment by dnephin** [comment]
No recent reports of this

**Comment by piotr-s-brainhub** [comment]
I have the same bug.
