### ISSUE TITLE
Any chance to use secrets for SwarmMode services?

### ISSUE THREAD

**Issue by anfinil** [docker/compose#4373]
Didn't find the ability to use secrets for SwarmMode services creation. Any chance to add such feature? Or how I can use docker-compose file for creating swarm and use secret keys?

**Comment by vdemeester** [comment]
@anfinil for `docker-compose` the proposal is here https://github.com/docker/compose/pull/4368 and for `docker stack deploy`, it's here https://github.com/docker/docker/pull/30144 👼

**Comment by shin-** [comment]
Added in 1.11
