### ISSUE TITLE
Add equivalent to docker `-P` option equivalent

### ISSUE THREAD

**Issue by nschoe** [docker/compose#4374]
Currently, there is no way in compose to replicate `docker run -P` option (_i.e._ randomly bind all `EXPOSE`ed ports from the Docker Image).

We can randomly bind a port just by specifying it: `ports:/n- <port>`. But that could be useful to have a way to randomly bind all ports that are `EXPOSE` in the Dockerfiles.

**Comment by t3chn0m4g3** [comment]
@nschoe `-P` is implicit when using `docker-compse` as long you `EXPOSE` the ports in the `Dockerfile`.
