### ISSUE TITLE
depends_on condition does not work with multiple docker-compose files

### ISSUE THREAD

**Issue by stefanopaganucci** [docker/compose#4380]
**depends_on condition** directive is not working while using multiple docker-compose configuration files.
Executing **docker-compose config** prints **service_started** instead of **service_healthy**.

**Comment by shin-** [comment]
Duplicate: #4350 #4355

**Comment by Friday13th87** [comment]
sorry for bringing this issue from 2017 up again, but that issue was not a duplicate on the linked one.
my question would be: how can i make anything like depends_on if i have 2 yml files.
so service1.yml and service2.yml abd service2 should wait to start till service1 health check is correct?

**Comment by mgale** [comment]
See comments in:https://github.com/docker/roadmap/issues/182#issuecomment-1208515414 It would be nice to re-open this issue.
