### ISSUE TITLE
Reattach docker containers given different compose files w/ same project name

### ISSUE THREAD

**Issue by andykais** [docker/compose#4382]
With docker it is possible to run
```bash
bash$ docker run -it --name "add_yarn" node:7.4 bash
container$ npm install -g yarn
bash$ docker start "add_yarn"
bash$ docker attach "add_yarn"
container$ yarn --version # still persists
```

however if I run something similar in docker-compose (but with different files)

```bash
docker-compose -f docker-compose.yml -f docker-compose.init.yml -p "project1" up
# docker-compose.init.yml has command: npm install -g yarn
docker-compose -f docker-compose.yml -f docker-compose.dev.yml -p "project1" up
# docker-compose.dev.yml has command: yarn --version
# outputs unknown command yarn
```

**Comment by shin-** [comment]
Hi,

That looks like an anti-pattern - Installing dependencies like yarn should be part of your `Dockerfile`.

That aside, when Compose detects a change in the service's configuration (e.g. a different command), it will recreate the container from scratch using the new configuration. If you want to execute a command inside a running container/service, use [exec](https://docs.docker.com/compose/reference/exec/)
