### ISSUE TITLE
Support multiple arguments for the --file and -f options

### ISSUE THREAD

**Issue by utkuzih** [docker/compose#4384]
### Issue
Currently we can support multiple compose files using `-f` switch in the following way:
`docker-compose -f docker-compose.stack1.yml -f docker-compose.stack2.yml <command>`

In case a service requires many other stacks, each command may get very long.

### Suggestion
Instead of accepting a single filename per `-f` switch, allow passing multiple filenames. This will allow us to use `*` matches. Example:

`docker-compose -f docker-compose.*.yml <command>`

**Comment by dainiuss** [comment]
Very good suggestion! I'm surprised that this is still not implemented.

**Comment by ksb2go** [comment]
Sounds like very useful improvement.

**Comment by ijc** [comment]
Thanks for the suggestion however I don't think this is compatible with the way arguments are handled and would add ambiguity if the glob matched a filename which was the same as a command. So I think we won't implement this, sorry.
