### ISSUE TITLE
piping data out of Docker crash

### ISSUE THREAD

**Issue by CrimsonGlory** [docker/compose#4394]
I have a log file inside a container
```
$ sudo docker-compose exec syslog ls -lh /var/log/messages           
-rw-r--r--    1 root     root       80.8M Jan 26 18:49 /var/log/messages
```
its about 600k lines

```
$ sudo docker-compose exec syslog wc -l /var/log/messages
639629 /var/log/messages
```

The following command works:
```
sudo docker-compose exec syslog cat /var/log/messages
```

Also the following (there are few results for this command):
```
sudo docker-compose exec syslog cat /var/log/messages | grep "asdfasdf"
```

But greping for http (almost all the lines), crash after printing a few hundred lines
```
sudo docker-compose exec syslog cat /var/log/messages | grep "http"
```

```
Traceback (most recent call last):.1 <redacted. just a random line from messages file>
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 64, in main
  File "compose/cli/main.py", line 116, in perform_command
  File "compose/cli/main.py", line 461, in exec_command
  File "site-packages/dockerpty/pty.py", line 334, in start
  File "site-packages/dockerpty/pty.py", line 370, in _hijack_tty
  File "site-packages/dockerpty/io.py", line 164, in do_write
OSError: [Errno 32] Broken pipe
docker-compose returned -1
```

- I can reproduce the bug everytime.
- Yes, I can avoid the bug using grep http messages instead of the useless use of cat. But this is just for the sake of reporting the bug.
- Seems related to #1509 #3352 

# Info
```
$ sudo docker-compose --version
docker-compose version 1.10.0, build 4bd6f1a
```

```
$ sudo docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```

```
$ uname -a
Linux codexServer 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ grep -i desc /etc/lsb-release 
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

**Comment by shin-** [comment]
I'm not able to reproduce this locally with a similar setup (I don't have a 600k lines syslog file, so I wrote a quick python script that continuously output random message lines). 

Do you have `ndg-httpsclient` installed? Can you reproduce with `docker-compose 1.11.2`?

**Comment by CrimsonGlory** [comment]
```ndg-httpsclient``` not installed.

I just found out a way to reproduce this 100% of the time, instantly. Tested with latest docker-engine and docker-compose across 3 different environments.

```
docker-compose exec alpine sh -c "cat /dev/urandom | tr -dc "[:alnum:][:punct:]" | tr '[:digits:]' '\n' | head -c 10000000" | xargs -0
```

```
# cat docker-compose.yml 
version: '2'
services:
  alpine:
    image: alpine:latest
    command: sleep 3600
```

With the container running: ```docker-compose up -d```.

Some thoughts:
If instead of ```head -c 10000000``` I execute it with ```head -c 1000``` it never crashes.
With 120925 it crash about 50% of the time. The other 50% either prints lots of chars, or prints:
```
xargs: argument line too long
```

It seems to me that xargs it exiting or crashing and that makes the docker command crash. So in my original post, its probably grep that is crashing and not docker.
The strange thing is that if I place the ```xargs``` inside the command, it does not crash, like this:
docker-compose exec alpine sh -c "cat /dev/urandom | tr -dc "[:alnum:][:punct:]" | tr '[:digits:]' '\n' | head -c 1000000 | xargs -0"

So piping out of docker large amounts of data makes some gnu utils crash.

**Comment by shin-** [comment]
Ok - I can indeed reproduce consistently with that command. I'm not 100% sure what we can do about it though. Just catch the OSError and print out a nice message I guess?

**Comment by CrimsonGlory** [comment]
I'm not sure either. But a good start would be find out why this command never crash:
```
docker exec -ti composetest_alpine_1 sh -c "cat /dev/urandom | tr -dc "[:alnum:][:punct:]" | tr '[:digits:]' '\n' | head -c 100000000" | grep -E -e "^."
```

while this one crashes in about 10-20 seconds (in my setup):
```
docker-compose exec alpine sh -c "cat /dev/urandom | tr -dc "[:alnum:][:punct:]" | tr '[:digits:]' '\n' | head -c 100000000" | grep -E -e "^." 
```
