### ISSUE TITLE
network_alias without explicit dependency

### ISSUE THREAD

**Issue by ericychoi** [docker/compose#4398]
Would it be possible to specify network_alias without explicit dependency?  For instance:

```
serviceA: 
  links:
    - B:serviceB
serviceB:
```

This will make `docker-compose up A` bring up B automatically.    But what if you don't want that and merely want it available (and addressable by its alias: B) whenever it is up?

**Comment by shin-** [comment]
Use `networks` and `aliases`: 
- https://docs.docker.com/compose/compose-file/#networks
- https://docs.docker.com/compose/compose-file/#/aliases

**Comment by ericychoi** [comment]
I was hoping to just use `default` network for this, but this works as well.  Thanks!
