### ISSUE TITLE
Docker-compose does not start containers

### ISSUE THREAD

**Issue by gabriel30** [docker/compose#4403]
Hi, I'm having problems with docker-compose and a docker-compose.yml that i created. The thing is when I use the command "docker-compose up -d" the containers looks like they are starting but a few seconds the state of the instances is "Exit", I'm not sure what is wrong, it looks that when the startup script that I define in the docker-compose.yml in "command" label, end, the instances just stop.

This is my docker-compose.yml

> version: '3'
> 
> services:
>   catalogHost:
>      build: .
>      image: ciscatalog
>      hostname: dsi_catalogHost
>      command: sh startup.sh
>      stdin_open: true
>      volumes:
>        - /home/docker:/opt/host
>      ports:
>        - 6600
>        - 6601
> 
>   containerHost:
>     image: dis/ciscontainer
>     hostname: dsi_containerHost
>     command: sh startup.sh
>     tty: true
>     volumes:
>       - /home/docker:/opt/host
>     ports:
>       - 2809
> 
>   inboundHost:
>     image: dsi/cisinbound
>     hostname: dsi_inboundHost
>     depends_on:
>       - catalogHost
>     links:
>       - catalogHost
>     command: sh startup.sh
>     tty: true
>     volumes:
>       - /home/docker:/opt/host
> 
> 
>   outboundHost:
>     image: dsi/cisoutbound
>     hostname: dsi_outboundHost
>     depends_on:
>       - catalogHost
>     links:
>       - catalogHost
>     command: sh startup.sh
>     tty: true
>     volumes:
>       - /home/docker:/opt/host
> 
 
example run:

 

> root@docker1:/home/docker/DSI# docker-compose scale catalog=3 container=4  inbound=1   outbound=1
>     Creating and starting dsi_catalog_1 ... done
>     Creating and starting dsi_catalog_2 ... done
>     Creating and starting dsi_catalog_3 ... done
>     Creating and starting dsi_container_1 ... done
>     Creating and starting dsi_container_2 ... done
>     Creating and starting dsi_container_3 ... done
>     Creating and starting dsi_container_4 ... done
>     Creating and starting dsi_inbound_1 ... done
>     Creating and starting dsi_outbound_1 ... done
> root@docker1:/home/docker/DSI# docker-compose up -d
> Starting dsi_container_4
> Starting dsi_catalog_3
> Starting dsi_catalog_1
> Starting dsi_container_3
> Starting dsi_catalog_2
> Starting dsi_container_1
> Starting dsi_outbound_1
> Starting dsi_inbound_1
> Starting dsi_container_2
>    root@docker1:/home/docker/DSI# docker-compose ps
>          Name         Command    State    Ports
>     -------------------------------------------
>     dsi_catalog_1     hostname   Exit 0
>     dsi_catalog_2     hostname   Exit 0
>     dsi_catalog_3     hostname   Exit 0
>     dsi_container_1   hostname   Exit 0
>     dsi_container_2   hostname   Exit 0
>     dsi_container_3   hostname   Exit 0
>     dsi_container_4   hostname   Exit 0
>     dsi_inbound_1     hostname   Exit 0
>     dsi_outbound_1    hostname   Exit 0

**Comment by shin-** [comment]
Hi,

If your `command` script exits, the container running it will exit as well. This is expected behavior.

**Comment by gabriel30** [comment]
OK. They both exist but why the state change to "Exist" if in the instance are an server running.

```
root@docker1:/home/docker/DSI# docker-compose scale catalogHost=3
Creating and starting dsi_catalogHost_1 ... done
Creating and starting dsi_catalogHost_2 ... done
Creating and starting dsi_catalogHost_3 ... done
root@docker1:/home/docker/DSI# docker-compose up
catalogHost_3  | Starting server cisCatalog1.
catalogHost_2  | Starting server cisCatalog1.
catalogHost_1  | Starting server cisCatalog1.
catalogHost_1  | Server cisCatalog1 started with process ID 111.
catalogHost_2  | Server cisCatalog1 started with process ID 114.
catalogHost_3  | Server cisCatalog1 started with process ID 111.
dsi_catalogHost_2 exited with code 0
dsi_catalogHost_3 exited with code 0
dsi_catalogHost_1 exited with code 0
```
I expected that the instance keep up to serve the requests and that I can attach to instances. Maybe I'm doing something wrong or I don't know something, I'm new with docker-compose

**Comment by gabriel30** [comment]
One more question. Why, if I define the hostname and use "docker-compose scale" to create N instances of the same container, the hostname of all instances are de same? I read that name are incremental but I see in instance hostname the same for all instances.

**Comment by gabriel30** [comment]
Now, I remove the "command" and using "docker-compose --verbose up" I'm getting some kind of infinite loop during the starting process:
```
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'3e232abfd1a34367605a7561d2499f0ebd76188ec7b50e62975ad2fd8eed424e')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/bash'],
             u'Domainname': u'',
             u'Entrypoint': None,
             u'Env': [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'],
             u'ExposedPorts': {u'6600/tcp': {}, u'6601/tcp': {}},
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'3e232abfd1a34367605a7561d2499f0ebd76188ec7b50e62975ad2fd8eed424e')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/bash'],
             u'Domainname': u'',
             u'Entrypoint': None,
             u'Env': [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'],
             u'ExposedPorts': {u'6600/tcp': {}, u'6601/tcp': {}},
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'3e232abfd1a34367605a7561d2499f0ebd76188ec7b50e62975ad2fd8eed424e')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'/bin/bash'],
             u'Domainname': u'',
             u'Entrypoint': None,
             u'Env': [u'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'],
             u'ExposedPorts': {u'6600/tcp': {}, u'6601/tcp': {}},

```
and this is repeting over and over again.

**Comment by gabriel30** [comment]
Now, I saw this issue https://github.com/docker/compose/issues/3896 where you recommended to use tty: true ... if I set this in my docker-compose.ylm, then the "COMPOSE_HTTP_TIMEOUT=8000 docker-compose --verbose up" stuck here:

```
Attaching to dsi_catalogHost_3, dsi_catalogHost_2, dsi_catalogHost_1
compose.cli.verbose_proxy.proxy_callable: docker logs <- (u'4aba535d06fb9058ff45d1d452829c0e7880c8bf667d473ab847300f45e9a50d', follow=True, stderr=True, stream=True, stdout=True)
compose.cli.verbose_proxy.proxy_callable: docker logs <- (u'bb233edea83a926a1185fd29e738d158953f8ba9d9b17a68de586c9015ae1f3a', follow=True, stderr=True, stream=True, stdout=True)
compose.cli.verbose_proxy.proxy_callable: docker logs <- (u'4e5ab34fd608d23d36c286585501684b88a7999f4336f1483e2331d75c665f52', follow=True, stderr=True, stream=True, stdout=True)
compose.cli.verbose_proxy.proxy_callable: docker logs -> <generator object _stream_raw_result at 0x7fc8d0f05af0>
compose.cli.verbose_proxy.proxy_callable: docker events <- (decode=True, filters={u'label': [u'com.docker.compose.project=dsi', u'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker logs -> <generator object _stream_raw_result at 0x7fc8d0ec61e0>
compose.cli.verbose_proxy.proxy_callable: docker events -> <generator object _stream_helper at 0x7fc8d0f05dc0>
compose.cli.verbose_proxy.proxy_callable: docker logs -> <generator object _stream_raw_result at 0x7fc8d0ec65f0>

```
Docker version 1.13.0, build 49bf474

**Comment by gabriel30** [comment]
OK. I can execute commands using "docker-compose exec" ... but ... now I realize that the hostname is the same for all machines ... I don't know is there a preatty way to connect to containers and execute commands.

**Comment by shin-** [comment]
Containers that are given a command will live for the duration of that command. Some containers just want to execute a simple task (run a build or test script for example) then exit. Others (like in your case) are servers that need to live "forever". In that case, their command needs to be a long-running process, like `python -m SimpleHTTPServer` or `mysqld`.
In your case if you use a startup script, you want your last command to "block" and keep the process alive. If it starts a daemonized process, the container will recognize the command it was supposed to run (`sh startup.sh`) is over and exit as a result.

Scaled containers will have the same hostname - internally, requests to that hostname will be redirected to available containers.

**Comment by gabriel30** [comment]
OK. I realize how is the communication between the containers but there is one more thing.
I'm creating a cluster of server and I need to define in the server config file the hostname of the container and of the others contaniners aswell. There is any way get the container name (service) into the container? I mean, I'm using linux and I just can access to original hostname.

The question is because if I can't change the OS hostname how can I find the container name to update the server config file.

This are the properties:

hostname: OShostname_1
cluster: OShostname_1, OShostname_2, OShostname_3

**Comment by shin-** [comment]
Sorry, I'm having trouble understanding your question - could you reformulate?

**Comment by gabriel30** [comment]
Yes. I'm creating a cluster of servers and to configure the servers they needs to have their hostname in a config file and the reference for the other servers aswell. So, I'm looking the way to do this automatly when the container is created, one option could be passing an enviroment variable but with this the question is how to get the container name when scale create it. Now I'm doing this mannually, chaging the hostname in the config file.

An example of the configuration file of one of the servers:

hostname: OShostname_1
cluster: OShostname_1, OShostname_2, OShostname_3

Other thing. Now I'm having another issue. At the moment when the server begin to communicate between them I'm experiment a buffer size problem and I need to increase the value of settings net.ipv4.tcp_rmem and net.ipv4.tcp_wmem (I'm working with debian OS). I have a couple of options two update this settings but the container does not let me to create a file in the "/proc/sys/net/ipv4/" folder.
