### ISSUE TITLE
docker-compose using --no-recreate --no-build still requires the build directories to be present

### ISSUE THREAD

**Issue by karlmutch** [docker/compose#4411]
During a testing phase for our CI/CD pipeline we wish to be able to run docker-compose with just the existing docker-compose.yml file, and the pulled docker images.

However if the 'build:' yml blocks are left in the compose file then the tool tries to read the build directories and fails, even if the --no-recreate --no-build options are specified.

For example:

ubuntu@ip-xxx-xx-xx-x:$ docker-compose -f docker-compose.yml up --no-recreate --no-build
ERROR: build path /home/ubuntu/db_populate either does not exist, is not accessible, or is not a valid URL.
ubuntu@ip-xxx-xx-xx-x:$

**Comment by shin-** [comment]
Hi!

This is a duplicate of #4047 - I will close this one but feel free to follow and comment on the other.
