### ISSUE TITLE
`docker-compose bundle` doesn't work with locally built images

### ISSUE THREAD

**Issue by suhirotaka** [docker/compose#4412]
I have following images on local:
```
$ docker images
REPOSITORY                     TAG                 IMAGE ID               CREATED             SIZE
my_image_1                     latest              1c0884e42164           6 days ago          1.71 GB
my_image_2                     latest              6cec1ff6d070           3 weeks ago         914 MB
```

And docker-compose.yml as below:
```
back:
  image: 1c0884e42164
# ...
front:
  image: 6cec1ff6d070
# ...
```

After I run `docker-compose bundle`, compose failed to use the images saying the images are missing digests.
```
$ docker-compose bundle
ERROR: Some images are missing digests.

The following images need to be pulled:

    back
    front

Use `docker-compose pull back front` to pull them.
```

The problem occurs only with locally built images.

**Comment by shin-** [comment]
I think you need to provide the full sha256 ID for each image, which you can retrieve using `docker inspect my_image_1 | grep Id`

cc @dnephin in case I'm mistaken

**Comment by dnephin** [comment]
Bundles require the image digest, which is generated when you `docker push` or `docker pull` an image. It looks like you're using image ids in the Compose file, but you can't pull using those ids.

Instead of the image id, use the image name  (you'll have to change it to `hub-username/my_image`), and push the images to a registry (`docker-compose push`).

The push will store the image digest and you'll be able to run `docker bundle`.

**Comment by dnephin** [comment]
There is ongoing work to make it possible to run bundles without these extra steps however it requires significant changes to the bundle and image format.

If you're trying to run a Compose file on swarm mode you can also use `docker stack deploy`, which might be easier than trying to use the bundle.

**Comment by suhirotaka** [comment]
@dnephin @shin- I'm trying `docker stack deploy -c docker-compose.yml foo`. I got another problem (`docker stack depooy` says "version version is required" and fails to launch stack), but anyway it's not compose issue. Many thanks :)
