### ISSUE TITLE
Docker v1.13 init feature to use in docker compose 

### ISSUE THREAD

**Issue by borntorock** [docker/compose#4415]
It would be great to have the docker v1.13 init feature in Compose v3 so as to provision the containers with docker compose with an init process running as PID 1 inside the containers.

**Comment by borntorock** [comment]
@shin- Are we going to have this feature soon, probably in next release?

**Comment by shin-** [comment]
All I can say for now is it will not be in Compose 1.11. I'll update here when I know more.

**Comment by borntorock** [comment]
@shin- Any update on this.

**Comment by OnkelTem** [comment]
It's odd.

If I use docker compose for running containers then I don't really get any chance to use `docker`'s option until it's not implemented by docker-compose. In other words - I'd expect them to be in sync and currently adding any new feature to docker without having them in docker-compose is just waste of time.

**Comment by borntorock** [comment]
@OnkelTem Totally agree with you, but I don't think that's the case currently. Every new feature invented in docker engine needs to be re-implemented in docker compose source code.

@shin- can provide more details on why the features invented in docker engine are not synced directly to docker compose.

**Comment by deiga** [comment]
@shin- I know this is closed, but in light of this, should `docker-compose run` support some way of passing through flags to `docker run`? This way one could use flags from upstream before `docker-compose` is updated

**Comment by quinn** [comment]
is there a reason this was removed in v3 of the config? I want to use this but don't want to depend on something that is deprecated.

**Comment by zrml** [comment]
Hi, this is critical for me. I'd like to keep the compose yml format for readability and compatibility but if this feature is not supported I'll be forced to switch to a bash script.
What is the rationale for deprecating it?
Thanks
