### ISSUE TITLE
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by BYK** [docker/compose#4416]
`docker-compose build <name>` command throws the following exception (with stracktrace) when the context directory includes a filename with a unicode character in it:
```
docker-compose build web
Building web
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 64, in main
  File "compose\cli\main.py", line 116, in perform_command
  File "compose\cli\main.py", line 222, in build
  File "compose\project.py", line 307, in build
  File "compose\service.py", line 786, in build
  File "site-packages\docker\api\build.py", line 139, in build
  File "site-packages\docker\utils\utils.py", line 91, in tar
  File "tarfile.py", line 1881, in gettarinfo
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\<redacted>\\files\\?.jpg'
```

The file name in question is: `∆.jpg`

Original mention of the issue: https://github.com/docker/compose/pull/4370#discussion_r98434304

I am using the latest docker-compose and docker-py installed from master (like `pip install git+https://github.com/docker/docker-py.git#egg-info`) and Python 3.5.2 on Windows 10.1
```
$ docker-compose --version
docker-compose version 1.11.0dev, build unknown
```

**Comment by shin-** [comment]
Thank you for the report! This is indeed a different issue than the one fixed by #4370 (happens in a completely different part of the code).

**Comment by BYK** [comment]
@shin- glad I could help! Please LMK if there's anything more I can provide or things you want me to try on my system.

**Comment by shin-** [comment]
Are you still seeing this issue with Compose 1.12.0? I've attempted to reproduce with unit tests in https://github.com/docker/docker-py/pull/1559 - but this passes without a hitch on AppVeyor.

**Comment by BYK** [comment]
@shin- sorry for the late response. Using 1.12-dev and haven't been experiencing the issue for some time now. I guess it is resolved :)

Thanks!
