### ISSUE TITLE
Refine config package to a single tool

### ISSUE THREAD

**Issue by max8899** [docker/compose#4422]
Hello,
     I am working on a project that getting json data from compose yaml file.  Finally I found it is not that easy and there are codes in compose project just do the same thing. So I'm wondering why not abstract this logic to a standard python package. Since there is a lot of validations out of the compose file's json schema and there are constrains which need to know the docker's limit well. And the upgrade of docker and docker compose makes it more harder to maintain such codes. It will helped a lot with a single python package to this.

Thanks

**Comment by shin-** [comment]
Thank you for your suggestion - unfortunately it's unlikely we'll be able to allocate the time and work necessary to implement an overhaul of that magnitude.

Thank you for your understanding.

**Comment by max8899** [comment]
Any suggestions for other community members who want to do this? If someone want to do this, is there steps to follow for such kind of big pr?
