### ISSUE TITLE
Add support for build volumes

### ISSUE THREAD

**Issue by Yajo** [docker/compose#4423]
`docker build` supports the `--volume` option to add volumes at build time.

`docker-compose` does not have such support (or it is not docummented).

```
$ docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j-fips  26 Sep 2016

$ docker info
Containers: 128
 Running: 0
 Paused: 0
 Stopped: 128
Images: 592
Server Version: 1.12.6
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Security Options: seccomp
Kernel Version: 4.9.5-200.fc25.x86_64
Operating System: Fedora 25 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 6.761 GiB
Name: yajolap.yajodomain
ID: KUBN:F7JL:URX6:HO55:R3L2:SCUU:IWVY:EZ2O:F53G:WHTO:3G4D:R4YU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Comment by flx42** [comment]
AFAIK, only Red Hat's fork of Docker Engine support it:
https://github.com/projectatomic/docker/tree/docker-17.03.1-ce#add-volume-support-to-docker-buildpatch
https://github.com/moby/moby/issues/14080

So I doubt @shin- will add it.

**Comment by ymc-dabe** [comment]
Note that besides moby (see: moby/moby#14080), docker-py is lacking support for this as well (see: docker/docker-py#1498).

I suggest to no accept my above PR #5736 till docker-py (e.g. via PR docker/docker-py#1937) has support for build time volumes.

**Comment by ijc** [comment]
Closing alongside https://github.com/docker/compose/pull/5736 https://github.com/docker/docker-py/pull/1937 etc. Per https://github.com/docker/docker-py/pull/1937#issuecomment-398198819 this is supported differently in buildkit and I don't believe that approach needs tools level changes to support. Building with buildkit from compose is already tracked elsewhere I believe.
