### ISSUE TITLE
Ubuntu Core 16 (GNU/Linux 4.4.0-1030-raspi2 armv7l) permission denied 

### ISSUE THREAD

**Issue by flyingbuddha** [docker/compose#4433]
Running `sudo docker.compose -f docker-compose.yml up` fails with the following error:
> ERROR: .IOError: [Errno 13] Permission denied: u'./docker-compose.yml'

I've seen a similar problem raised in #3305 but I'm unsure if it's connected.
I'm a little unsure if I'm doing something unexpected.

**docker version:**
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   v1.11.2-snap-38fd0d3
 Built:        Tue Nov 15 13:39:13 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   v1.11.2-snap-38fd0d3
 Built:        Tue Nov 15 13:39:13 2016
 OS/Arch:      linux/arm
```

**docker.compose version**
```
docker-compose version 1.7.1, build unknown
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by shin-** [comment]
Looks like a permissions problem - I'm not sure it has anything to do with Compose.

Incidentally, you seem to be several versions behind (most recent stable is 1.10.1) and I'd highly encourage upgrading before we investigate the matter further.

**Comment by flyingbuddha** [comment]
Thanks @shin, on further inspection I was using https://github.com/docker-snap/docker (`snap find docker`) and you're right, it was out of date.

I couldn't resolve the problem so I've moved away from Ubuntu Core now and onto Hypriot OS, where everything seems to be working as expected.
