### ISSUE TITLE
Cannot modify TCP buffer size in Docker image

### ISSUE THREAD

**Issue by gabriel30** [docker/compose#4435]
I have a problem with a debian container in a cluster model. I'm starting a process in 3 containers that needs to communicate each other over a specific port,  but during the process of initial communication an exception associated to the TCP buffer size its generated.

Following this post https://developer.ibm.com/answers/questions/236787/getting-warning-message-dcsv9413w-failed-to-set-bu/ I tried to change the settings net.ipv4.tcp_rmem and net.ipv4.tcp_wmem but the file with the definition does not exist in the container ("ex. /proc/sys/net/ipv4/tcp_rmem"), I tried to create it but It's not posible and reading another posts, it looks like docker does not allow to change this kind of setting. Anyone can help?

**Comment by shin-** [comment]
This doesn't seem to be related to Docker Compose. I encourage you to take your question to [the forums](https://forums.docker.com/) where you'll get more visibility by people more qualified to help.

Cheers,
