### ISSUE TITLE
Bug: docker-compose scale returns exit code 0 on errors

### ISSUE THREAD

**Issue by EvgenyOrekhov** [docker/compose#4465]
```sh
$ docker-compose scale app=2
Starting app_2 ... error

ERROR: for app_2  Container is marked for removal and cannot be started.
$ echo $?
0
```

`docker-compose scale` should return a non-zero exit code when an error happens.

Docker version 1.13.1, build 092cba3
docker-compose version 1.11.1, build 7c5d5e4

**Comment by shin-** [comment]
Thank you for the report.

**Comment by EvgenyOrekhov** [comment]
What a way to fight bugs! Good job!
