### ISSUE TITLE
Can not specify named volume flags (f.e. propagation)

### ISSUE THREAD

**Issue by zim32** [docker/compose#4467]
Given such configuration

```
version: "2"
services:
  foo:
    ....
    volumes:
      - test:/test:shared
volumes:
  test:
```
Gives error:
```
ERROR: for foo  Invalid bind mount spec "foo:/test:shared": Invalid volume specification: 'foo:/test:shared'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
```

Is it possible to specify propagation using compose file somehow?

**docker-compose  version**
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

**docker version**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

**docker info**
Containers: 28
 Running: 8
 Paused: 0
 Stopped: 20
Images: 81
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 174
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.62 GiB
Name: ***-MS-7818
ID: O47Q:5EJD:2QVL:ASMY:EGZD:RGGB:UR5G:BELW:TTZR:7YL6:QD6O:7FHM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Comment by shin-** [comment]
It won't work with version 2, but it's being worked on: https://github.com/docker/docker/pull/30597
