### ISSUE TITLE
Fig should write informational output to stdout and only errors to stderr

### ISSUE THREAD

**Issue by kennu** [docker/compose#448]
Currently the fig command writes unnecessary informational output (e.g. "Stopping container..." and "Recreating container..." to stderr. This makes it difficult to redirect output so that errors in e.g. cron jobs would be noticed and unnecessary output would be discarded to /dev/null.

**Comment by dnephin** [comment]
Ref:
* http://pubs.opengroup.org/onlinepubs/009695399/functions/stdin.html
* http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

stderr is for diagnostic information as well as errors
stdout is only for "normal program output" (ex: what the user is requesting)

So logs from containers would be stdout, but messages like "Starting x..." would be stderr.

I believe this is working as expected, so closing this issue.
