### ISSUE TITLE
Error creating default network: HNS failed with error : The parameter is incorrect. 

### ISSUE THREAD

**Issue by andyliddle** [docker/compose#4482]
HI,

Trying to switch docker to use windows containers causes error to occur

Any thoughts?  

Version 1.13.1 (10072)
Channel: Stable
94675c5

Docker daemon failed with message:
time="2017-02-14T09:06:07Z" level=warning msg="Running experimental build" 
time="2017-02-14T09:06:07.082671000Z" level=debug msg="Listener created for HTTP on npipe (//./pipe/docker_engine_windows)" 
time="2017-02-14T09:06:07.084668000Z" level=info msg="Windows default isolation mode: hyperv" 
time="2017-02-14T09:06:07.084668000Z" level=debug msg="Using default logging driver json-file" 
time="2017-02-14T09:06:07.085669500Z" level=debug msg="WindowsGraphDriver InitFilter at C:\\ProgramData\\Docker\\windowsfilter" 
time="2017-02-14T09:06:07.085669500Z" level=debug msg="Using graph driver windowsfilter" 
time="2017-02-14T09:06:07.085669500Z" level=debug msg="Max Concurrent Downloads: 3" 
time="2017-02-14T09:06:07.085669500Z" level=debug msg="Max Concurrent Uploads: 5" 
time="2017-02-14T09:06:07.097672500Z" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2017-02-14T09:06:07.097672500Z" level=info msg="Loading containers: start." 
time="2017-02-14T09:06:07.097672500Z" level=debug msg="Option Experimental: true" 
time="2017-02-14T09:06:07.097672500Z" level=debug msg="Option DefaultDriver: nat" 
time="2017-02-14T09:06:07.097672500Z" level=debug msg="Option DefaultNetwork: nat" 
time="2017-02-14T09:06:07.114668100Z" level=debug msg="Network Response : [  ]" 
time="2017-02-14T09:06:07.114668100Z" level=debug msg="Launching DNS server for network%!(EXTRA string=none)" 
time="2017-02-14T09:06:07.115668800Z" level=debug msg="Allocating IPv4 pools for network nat (efae0dc11bb30cf1cfe001964ec19efb29dfff9784e336d5639a0bb4199bde7f)" 
time="2017-02-14T09:06:07.116670300Z" level=debug msg="RequestPool(LocalDefault, , , map[], false)" 
time="2017-02-14T09:06:07.116670300Z" level=debug msg="RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.docker.network.gateway])" 
time="2017-02-14T09:06:07.116670300Z" level=debug msg="HNSNetwork Request ={\"Name\":\"nat\",\"Type\":\"nat\",\"Subnets\":[{\"AddressPrefix\":\"0.0.0.0/0\",\"GatewayAddress\":\"0.0.0.0\"}]} Address Space=[{0.0.0.0/0 0.0.0.0 []}]" 
time="2017-02-14T09:06:07.150687900Z" level=debug msg="releasing IPv4 pools from network nat (efae0dc11bb30cf1cfe001964ec19efb29dfff9784e336d5639a0bb4199bde7f)" 
time="2017-02-14T09:06:07.150687900Z" level=debug msg="ReleaseAddress(0.0.0.0/0, 0.0.0.0)" 
time="2017-02-14T09:06:07.150687900Z" level=debug msg="ReleasePool(0.0.0.0/0)" 
time="2017-02-14T09:06:07.150687900Z" level=debug msg="start clean shutdown of all containers with a 15 seconds timeout..." 
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : The parameter is incorrect. 

   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by shin-** [comment]
Check out #4024 and #4149, maybe those can yield some answers.

cc @friism

**Comment by friism** [comment]
@andyliddle this is not a compose issue.

Does the musicstore sample work for you? https://github.com/friism/MusicStore/blob/master/docker-compose.windows.yml

If so, please follow that model (using the external NAT network).

**Comment by andyliddle** [comment]
Not really gotten to grips with docker yet,  this was just setting up an environment to investigate.

Looks like it was an issue with my laptop i was using.

Tested on another and works ok,  Will be rebuilding laptop in a few days so will fix it,.

**Comment by JanneRantala** [comment]
@friism I'm facing this same issue which occurs very randomly. I've tried running MusicStore sample as well and that was working ok but then again, so is my own Docker compose for most of the time.

**Comment by dermeister0** [comment]
I got the issue today after fresh install of Docker Enterprise Edition to Windows Server 2016. The service failed to start. I started it manually and Docker seems to work.

    Docker version 17.03.1-ee-3, build 3fcee33

**Comment by nikoo56** [comment]
Any update on this issue? I still have same problem.

**Comment by allencharp** [comment]
I am facing exactly the same issue, any updates about this issue ? thanks

**Comment by friism** [comment]
@allencharp @nikoo56 can you please open separate issues with details on what you're trying to do and what errors you see?

**Comment by prisar** [comment]
I removed nat for windows server 2016 standard and it stoped showing this error.
