### ISSUE TITLE
docker-machine ssh worker /home/docker - Permission denied

### ISSUE THREAD

**Issue by kmlsh04** [docker/compose#4492]
I am new to docker and not have much experience with windows commands too.
I tried to access the directory of my new created VM(worker) but it gives me permission error.

C:\Windows\system32>docker-machine ssh worker /home/docker
sh: /home/docker: Permission denied

Could anyone please suggest why I am getting this error ? 

Docker installed details:
Version 1.13.1 (10072)
Channel: Stable
94675c5
Windows 10 Pro

**Comment by shin-** [comment]
Maybe try the [docker/machine](https://github.com/docker/machine) repo, or the [forums](https://forums.docker.com/). As this is not a Compose issue, I'm going to close this ticket.
