### ISSUE TITLE
how can I stop a container if it is paused

### ISSUE THREAD

**Issue by lusinking** [docker/compose#4494]
I have a container monitor to monitor the traffic of application container, and have two timeouts, one is small, if this timeout reached, I will pause the container, and the other one is lager, if this timeout reached, I will stop the container, but actually, when the second timeout reached, the stop invokation gives an error as follows:
Cannot kill container 70086d37f90d: Container 70086d37f90df119d09b7d663bb46029999aeab711b9650b9f43c23958da1d5d is paused. Unpause the container before stopping

so is there any way to stop the paused container ignore the status of running or paused, or it will generate more work to do, and more work means more scene to consider, and also may cause some prolems if the operations is not atomic

**Comment by shin-** [comment]
Please report this on the [docker/docker](https://github.com/docker/docker) repo. This is not a Compose issue.
