### ISSUE TITLE
Double output

### ISSUE THREAD

**Issue by felixrabe** [docker/compose#450]
Using the following `fig.yml` file:

    web:
      image: busybox:latest
      command: echo hello world

leads to this output:

    $ fig run web
    hello world
    hello world

Why?

**Comment by dnephin** [comment]
This issue is over a year old, are you still able to reproduce it?

**Comment by felixrabe** [comment]
No, it seems to be fixed:

    $ cat docker-compose.yml 
    web:
      image: busybox:latest
      command: echo hello world

    $ docker-compose run web
    hello world

    $ docker-compose -v
    docker-compose version: 1.3.3
    CPython version: 2.7.9
    OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014

    $ docker -v
    Docker version 1.8.1, build d12ea79

    $ boot2docker version
    Boot2Docker-cli version: v1.8.0
    Git commit: 9a26066

**Comment by thaJeztah** [comment]
Thanks for confirming, @felixrabe
