### ISSUE TITLE
Warn user before doing 'docker-compose down'

### ISSUE THREAD

**Issue by thomas15v** [docker/compose#4501]
For people that just are getting started with compose, the command `docker-compose down` can be confusing at first. We had an encounter where we did `docker-compose down` to stop the service. Which ended catastrophically. It would be nice if the command gave us a warning like:
```
$ docker-compose down
Warning this action will delete the following containers and volumes:
 - production_odoo
 - production_db
 - production_nginx
Are you sure you want to continue (Yes/No): N
$ docker-compose down -y
Stopping production_odoo
Stopping production_db
Stopping production_nginx
Removing production_odoo
Removing production_db
Removing production_nginx
Removing network production_default
```

And yes I know that our containers should be stateless, but sadly enough we had to learn that the hard way. It would be nice that we could warn those poor souls out that encountered the same thing we did.

**Comment by shin-** [comment]
Thank you for your feedback - and sorry you got bitten by this! 

Unfortunately, this would be a breaking change for a feature that has existed for a long time, for only marginal benefits, and I don't think it would be reasonable for us to do this at that point.
