### ISSUE TITLE
Installation on OSX with boot2docker

### ISSUE THREAD

**Issue by bwiklund** [docker/compose#451]
FIY, if you're using boot2docker and follow the OSX setup instructions on the site, fig doesn't work (any command just exits siliently)

It does however work if installed via brew. I don't know the reason behind it but hopefully this helps you guys.

**Comment by HintikkaKimmo** [comment]
Hi, I am also experiencing the same with brew install, but not on Ubuntu VM running docker natively. For me its exits with ether error 1 or error 0. Where can I find what these errors actually mean anyway? 

First I was thinking there must be something wrong with my fig.yml file as it seem to work perfectly on the first boot but not after but this seems only to be issue if I run those containers in my mac not on top of native linux (only tested Ubuntu)

**Comment by aanand** [comment]
@HintikkaKimmo Installation via Homebrew is not officially supported. Have you tried [downloading the binary](http://www.fig.sh/install.html)?

**Comment by panta** [comment]
I tried, on OSX, both with the Homebrew versions and the official binary ones, and the results is the same for me, with the problem persisting.
I've just commented the problem here https://github.com/docker/fig/issues/300#issuecomment-70364044

Any suggestions?
