### ISSUE TITLE
missing file-parameter "-f" for "docker-compose create"

### ISSUE THREAD

**Issue by t-hofmann** [docker/compose#4512]
with this it is not possible to use a custom-file and just create service-containers without starting them

using: docker-compose version 1.11.1, build 7c5d5e4

**Comment by t-hofmann** [comment]
the global parameters are kind of positional, meaning: they have to be placed before the command, e. g.:
docker-compse -f docker-compose.custom.yml create

Would be nice to make the parameter parser more flexible in regard of positioning.

**Comment by shin-** [comment]
See #4464
