### ISSUE TITLE
wordpress can't not connect mysql with WORDPRESS_DB_HOST: db:3306

### ISSUE THREAD

**Issue by wythend** [docker/compose#4520]
In ubuntu 16.04
Docker version 1.12.6, build 78d1802
Docker-compose version 1.11.1

I use the compose.yml file from [https://docs.docker.com/compose/wordpress/](https://docs.docker.com/compose/wordpress/)

$ docker exec -ti wordpress_wordpress_1 /bin/bash
$ ping db 
It seems the wordpress can't not ping db.

But when I change the docker-compose version to 1.8, it works.

**Comment by DRAKUN** [comment]
Please someone can help us

185.10.68.228 - - [05/Jun/2018:20:35:34 +0000] "GET / HTTP/1.0" 301 244 "-" "-"                                                                           
[Tue Jun 05 20:36:25.861602 2018] [mpm_prefork:notice] [pid 1] AH00169: caught SIGTERM, shutting down                                                     
                                                                                                                                                          
Warning: mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 22                                                        
                                                                                                                                                          
MySQL Connection Error: (2002) Connection refused                                                                                                         
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to supp
ress this message                                                                                                                                         
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to supp
ress this message                                                                                                                                         
[Wed Jun 06 01:06:39.917313 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.6 configured -- resuming normal operations         
[Wed Jun 06 01:06:39.920194 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'                                                    
154.124.193.53 - - [06/Jun/2018:01:09:29 +0000] "GET / HTTP/1.1" 200 3675 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0" 
154.124.193.53 - - [06/Jun/2018:01:11:37 +0000] "GET /wp-login.php HTTP/1.1" 200 1531 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Fi
refox/60.0"                                                                                                                                               
154.124.193.53 - - [06/Jun/2018:01:11:38 +0000] "GET /favicon.ico HTTP/1.1" 200 227 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Fire
fox/60.0"                                                                                                                                                 
154.124.193.53 - - [06/Jun/2018:01:11:39 +0000] "GET /favicon.ico HTTP/1.1" 200 227 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Fire
fox/60.0"                                                                                                                                                 
154.124.193.53 - - [06/Jun/2018:01:12:23 +0000] "GET /wp-login.php HTTP/1.1" 200 1531 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Fi
refox/60.0"                                                                                                                                               
[Wed Jun 06 03:10:22.481085 2018] [mpm_prefork:notice] [pid 1] AH00169: caught SIGTERM, shutting down                                                     
                                                                                                                                                          
Warning: mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 22                                                        
                                                                                                                                                          
MySQL Connection Error: (2002) Connection refused                                                                                                         
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to supp
ress this message                                                                                                                                         
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to supp
ress this message                                                                                                                                         
[Wed Jun 06 13:06:42.882304 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.6 configured -- resuming normal operations         
[Wed Jun 06 13:06:42.884771 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'                                                    
41.219.11.29 - - [06/Jun/2018:13:06:45 +0000] "GET / HTTP/1.1" 200 3675 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0"   
54.87.47.128 - - [06/Jun/2018:13:08:43 +0000] "GET / HTTP/1.1" 200 3675 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gec
ko) Chrome/66.0.3359.181 Safari/537.36"                                                                                                                   
54.87.47.128 - - [06/Jun/2018:13:09:35 +0000] "-" 408 0 "-" "-"                                                                                           
54.87.47.128 - - [06/Jun/2018:13:10:01 +0000] "GET / HTTP/1.1" 200 3675 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gec
ko) Chrome/66.0.3359.181 Safari/537.36"                                                                                                                   
41.219.11.29 - - [06/Jun/2018:13:10:13 +0000] "GET / HTTP/1.1" 200 3675 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0"   
54.87.47.128 - - [06/Jun/2018:13:11:33 +0000] "GET /favicon.ico HTTP/1.1" 200 228 "http://34.245.104.128:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)
 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"                                                                               
41.219.11.29 - - [06/Jun/2018:13:13:12 +0000] "GET /favicon.ico HTTP/1.1" 200 228 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefo
x/60.0"                                                                                                                                                   
41.219.11.29 - - [06/Jun/2018:13:13:12 +0000] "GET /favicon.ico HTTP/1.1" 200 228 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefo
x/60.0"
