### ISSUE TITLE
Add CLI option to ignore docker-compose.override.yml

### ISSUE THREAD

**Issue by philtay** [docker/compose#4522]
`docker-compose up` and friends automatically read the `docker-compose.override.yml` file if present. Sometimes it would come handy to disable this behavior. Something like `docker-compose --ignore-override up`.

**Comment by schmunk42** [comment]
What you can do already is: `docker-compose -f docker-compose.yml config`

**Comment by shin-** [comment]
Closing, see https://github.com/docker/compose/pull/4543#issuecomment-285148647 for rationale.
