### ISSUE TITLE
Cant set Container MAC addresses

### ISSUE THREAD

**Issue by kladkogex** [docker/compose#4526]
docker network connect needs to accept --mac-address as parameter.

This causes lots of issues for us.

**Comment by shin-** [comment]
https://docs.docker.com/compose/compose-file/#/domainname-hostname-ipc-macaddress-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir

**Comment by LuisPiedra** [comment]
Although it's is possible to set a single mac-address for a container if there is only one network defined, it's not possible to set a mac address for each interface if several networks are defined.

This is also not possible with Docker CLI (--mac-address is an option for docker run, but not for docker connect), but it seems it supported in Docker Engine, at least from API v1.25 (https://docs.docker.com/engine/api/v1.25/#operation/NetworkConnect)

I will open issues also to docker CLI and docker-py. Should I open one new issue here or is ok to keep it in this same issue?

**Comment by LuisPiedra** [comment]
Related issues in Docker CLI and docker-py:

- https://github.com/moby/moby/issues/33715
- https://github.com/docker/docker-py/issues/1654
