### ISSUE TITLE
Add support for load balancing modes

### ISSUE THREAD

**Issue by ahromis** [docker/compose#4534]
Currently all services created with the latest compose format default to VIP load balancing mode. Is there plans to add support to compose for that to be configurable? 

Right now the only way to change to round-robin mode is to update the service after it's been created.

**Comment by shin-** [comment]
Sorry, you'll need to recreate this on [docker/docker](https://github.com/docker/docker) - this repo deals with issues with `docker-compose` but not `docker stack`
