### ISSUE TITLE
curl: Failed to connect to github-cloud.s3.amazonaws.com port 443: Connection timed out

### ISSUE THREAD

**Issue by jodumont** [docker/compose#4545]
On 3 Debian in 3 differents location (but all in Switzerland)
I always receive a Connection timed Out

**Comment by shin-** [comment]
http://www.usatoday.com/story/tech/news/2017/02/28/amazons-cloud-service-goes-down-sites-scramble/98530914/

**Comment by jodumont** [comment]
thank! the usatoday is probably hosted on amazon because it's very slow ;)
