### ISSUE TITLE
Make --parallel the default for pull

### ISSUE THREAD

**Issue by edsrzf** [docker/compose#4556]
#4428 added the `--parallel` flag to the `pull` command. What needs to be done to get that to the point where it's the default? Off the top of my head:

- [ ] Some experience with `--parallel` to gather feedback.
- [ ] Better, more detailed output. I have some ideas here.

Do we need anything else? Is there any reason that parallel pulling should *never* become the default?

**Comment by jmreicha** [comment]
Has there been any progress on this?  I have been using `--parallel` for awhile, and it has been working well. 
 The only thing I think it is missing is some sort of progress indicator.

**Comment by edsrzf** [comment]
I haven't made any steps towards this yet, no, aside from thinking about it. I agree some sort of progress feedback is necessary. At the very least I want to know which images are currently being pulled as the command is working.

**Comment by tejasmanohar** [comment]
+100. I've been wanting parallel downloads for a while and never knew it was an option (because who checks flags for commands that already work :P)

**Comment by kingbuzzman** [comment]
Any news on this? A `.dockerglobalsettings` or something like that we can set it would also work...
