### ISSUE TITLE
unexpected behavior with interactive tty and command history

### ISSUE THREAD

**Issue by jeffrom** [docker/compose#4574]
When I `docker-compose exec service` bash, psql, and other interactive programs, i've noticed that `control-P` and `control-N` do not have the same behavior as the up and down arrows when navigating history. Up and down work as expected, but ctrl-P doesn't show the previous command. When that happens, if i use a left or right arrow to move the cursor, the command will show up. But it's pretty annoying. Am I the only one with this problem? :)

**Comment by nodakai** [comment]
Take a look at moby/moby#1446 & moby/moby#3405
