### ISSUE TITLE
Install issue on Fedora 25

### ISSUE THREAD

**Issue by burningTyger** [docker/compose#4578]
docker-compose installs just fine according to the docs but it doesn't run with sudo because - and now I'm rather guessing whether this is the root cause - `/usr/local/bin` is not in root's path. It however is in my user's path. So `docker-compose --version` works but not `sudo docker-compose --version`. I'm getting a `command not found` error. I moved the file to `/usr/bin` and now it works. This is probably not very smart because once I update I'll have forgotten about this issue...

OS: current Fedora 25

**Comment by shin-** [comment]
I'm not sure I understand what the issue is. Why do you want to run `docker-compose` using `sudo`?

**Comment by burningTyger** [comment]
I always just assumed I had to `sudo docker-compose`. Just like `sudo docker`. That was the most natural thing to do for me. I can't even see anything about `sudo` in the docs.
