### ISSUE TITLE
MacOS Homebrew installation won't display build for --version

### ISSUE THREAD

**Issue by SrihariThalla** [docker/compose#4595]
Homebrew formula - [docker-compose on Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-compose.rb)

When `docker-compose --version` command has been executed, the build will be returned `unknown`!

```bash
$ docker-compose --version
docker-compose version 1.11.2, build unknown
```

I'm not sure why.

**Comment by shin-** [comment]
We don't recommend using homebrew to install `docker-compose`. Please refer to the official install docs for supported install methods: https://docs.docker.com/compose/install/
