### ISSUE TITLE
Docker-compose via container doesn't connect pipes correctly

### ISSUE THREAD

**Issue by jebw** [docker/compose#4599]
This can be tested with something like the following

`cat db.sql | docker-compose run --rm myimage mysql --host=mysql --user=root --password=foobar my_database`

If docker-compose is installed using the instructions on githubs release page

https://github.com/docker/compose/release

then the above will work

If docker-compose is installed as a container, the above line will just give a mysql prompt - implying pipes aren't getting hooked up correctly?

**Comment by shin-** [comment]
Does it work if you set `DOCKER_RUN_OPTIONS="-i -t"` in your environment before running that command?
