### ISSUE TITLE
Docker-compose doesn't download remote image if build context is specified

### ISSUE THREAD

**Issue by shikhovmy** [docker/compose#4602]
Here is a simple docker-compose.yml
```
version: '2.1'
services:
  example:
    build:
      context: ./dir
    image: hello-world
```
``` 
$ docker-compose up
Building example
ERROR: Cannot locate specified Dockerfile: Dockerfile
```
It happens when hello-world image cannot be found locally. After I pull it manually _docker-compose up_ works as expected

My system's info: 
`OS Mac OS Sierra 10.12.3 (16D32)`
```
$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
```
$ docker-compose version
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by shin-** [comment]
This is the expected behavior. https://docs.docker.com/compose/compose-file/compose-file-v2/#build

**Comment by shikhovmy** [comment]
Let me provide more detail about my case.
I have a project with a following structure:
```
/
- src/
- docker-files/
- - docker-compose.yml
```
I execute docker-compose from the root so I need to specify a path to _.yml_ file. In addition I need to share a source code with a container. However with -f parameter provided context is changed to a directory with _.yml_ file. This is why I need to set _build/context_ parameter in docker-compose.yml

**Comment by shin-** [comment]
The path to your build context has to be relative to the directory where the `docker-compose.yml` file is located.
