### ISSUE TITLE
Scale + links: how routing works? Mesh network? Other types of network?

### ISSUE THREAD

**Issue by bitliner** [docker/compose#4609]
Imagine the following scenario

* docker-compose file, with a `client` and a `server` service.
* There is a link between `client` and `server`.
* I apply scale=10

Questions:
* By default, every `server` will be linked to each client, correct?
* How the routing works? Is there any policy? How `client-i-th` knows which is the `server-i-th` to send request to?
* Is there a way to link `client-1` with only `server-1`,  `client-2` with only `server-2` etc?

If it is already explained in the documentation, where can I find this information?

**Comment by shin-** [comment]
This is a question for docker/swarm (or whichever orchestration manager you happen to use) - that behavior is not controlled by Compose.
Note that it's advisable to use `networks` (and aliases) instead of `links` if possible. https://docs.docker.com/compose/compose-file/compose-file-v2/#links
