### ISSUE TITLE
Unsupported config option: 'healthcheck'

### ISSUE THREAD

**Issue by nitinprakash96** [docker/compose#4610]
Hi, I edited a compose file for my app and added a healthcheck option. But whenever I try running `docker-compose up` I get the following error.

>ERROR: The Compose file './docker-compose.yml' is invalid because:
>Unsupported config option for balrogadmin: 'healthcheck'

My docker configurations are:

```
docker-compose --version
docker-compose version 1.11.2, build dfed245

```
```
docker --version
Docker version 17.03.0-ce, build 3a232c8
```

**Comment by glookie1** [comment]
I had the same issue - I was able to fix it by changing the version in the docker-compose.yml file to `version: '2.1'`.

**Comment by nitinprakash96** [comment]
Yeah, Changing the version worked. Thanks @glookie1
