### ISSUE TITLE
Enable output of `depends_on` services

### ISSUE THREAD

**Issue by whitecolor** [docker/compose#4611]
When `docker-compose up my-service` is run it will also start services that `my-service` `depends_on`, but it won't show output of those services.

It would be useful to have option for `docker-compose` that would also turn on output for dependencies.

**Comment by shin-** [comment]
You can use `docker-compose logs` to do exactly that, I think.

**Comment by whitecolor** [comment]
you mean start for example detached `docker-compose up -d my-service` and then `docker-compose logs here i still need to enumerate all the services by name`

**Comment by rawkode** [comment]
@whitecolor `docker-compose logs -f` will show logs of all services

For me, when I do `docker-compose up app` - I only want to see app logs, not dependant services.

I guess this is a pretty subjective issue :+1:

**Comment by whitecolor** [comment]
well actually really `docker-compose logs -f service1 service2` may do the trick I need, I believe this request/question maybe closed.

**Comment by gnarea** [comment]
I would've loved to see this feature, and the proposed workaround is a bit of a hassle.

I've just implemented this functionality in [docker-dev](https://github.com/2degrees/docker-dev#docker-dev-up2-services). So, @whitecolor's example becomes: `docker-dev up2 my-service`.

**Comment by whitecolor** [comment]
I think any decent developer/team should have (or already has) their own meta-framework on top of used infrastructure tools like a docker/compose. It is hard to invent one-fit-all-solution to automate everyone's workflows.

**Comment by sarink** [comment]
How would you add the necessary `docker-compose logs` command to something like this? `docker-compose -f ci.config.yml up --exit-code-from test-runner test-runner`
