### ISSUE TITLE
ERROR: client and server don't have same version (client : 1.21, server: 1.18)

### ISSUE THREAD

**Issue by a1exus** [docker/compose#4614]
I followed [Install as a container](https://docs.docker.com/compose/install/#install-as-a-container) and while running `docker-compose ps`, I'm getting following error:

```
# docker-compose ps
ERROR: client and server don't have same version (client : 1.21, server: 1.18)
# docker-compose version
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
# 
```
Please advise.

**Comment by shashidesai** [comment]
You can use this link to resolve your issue. hope that helps.
https://docs.docker.com/compose/reference/envvars/

"The Docker API only supports requests from clients which report a specific version. If you receive a client and server don't have same version error using docker-compose, you can workaround this error by setting this environment variable. Set the version value to match the server version."

**Comment by shin-** [comment]
@shashidesai 's answer is correct, although there might be unexpected compatibility issues - Docker 1.6 is a really old version and you should **really** consider upgrading.

**Comment by bouazizihsan** [comment]
Hello,
my:Docker version 1.6.2, build 7c8fca2 
docker-compose version 1.11.2, build dfed245 erreur: 
ERROR: client and server don't have same version (client : 1.21, server: 1.18)

How i can solve this problem Thank you
