### ISSUE TITLE
Fig output not visible in Sublime Text

### ISSUE THREAD

**Issue by zedtux** [docker/compose#462]
Hello,

I would like to execute my tests from Sublime Text within a container. When I run the command `fig run web bundle exec cucumber feature/my_feature.feature` manually from a console it's working perfectly.

Now I'm using the RubyTest plugin in Sublime Text (I tried both versions: 2 and 3) and the command is correctly executed but I don't see anything in the Sublime Text console window excepted the elapsed time.

I'm not very strong with Python but as far as I believe to have understood from the code, fig is logging in a stream and not in the stdout. Am I right ?

If I'm right, can you please explain me why is it like this and if it's possible to change it (maybe with an option when running fig ?)

Thank you a lot.

**Comment by evgenyneu** [comment]
The output only has one line for me. Following zedroot blogpost mentioned above.

    [Finished in 6.9s]

**Comment by zedtux** [comment]
Since the latest version I have the same behaviour than you @evgenyneu. I will try again my script in order to see if it fix it or not.

**Comment by zedtux** [comment]
@evgenyneu I think the issue is not really with Fig but with RubyTest. I have referred this issue in a old RubyTest issue I have opened in the past.

You can join me :)

**Comment by evgenyneu** [comment]
thanks for looking into it, @zedtux. One strange thing I also notice, is that if I run the script in the console it still does not show any output
    
    ./scripts/fig-to-sublime.rb rspec

**Comment by zedtux** [comment]
> Probably not many people using docker/fig/sublime text/rubytest combination at the moment - hence such low activity on this topic.

Yep I think too...
