### ISSUE TITLE
`docker-compose rm -f` doesn't always work

### ISSUE THREAD

**Issue by mcandre** [docker/compose#4631]
Sometimes, `docker-compose rm -f` reports `No stopped containers`, instead of deleting the actually still running containers.

For example, this can happen with https://github.com/zoidbergwill/docker-compose-kafka

**Comment by shin-** [comment]
That's by design. As of now, `rm` never removes running containers. In the next release, we're adding a `--stop` option to `rm` to stop containers before removing them.
