### ISSUE TITLE
Restore support for other log drivers

### ISSUE THREAD

**Issue by mstenta** [docker/compose#4647]
I couldn't find an existing issue for this, so here goes...

I updated from Compose 1.8.0 to 1.11.2 yesterday <strike>and I could no longer start my containers</strike>. The following warning was displayed:

`WARNING: no logs are available with the 'awslogs' log driver`

My `docker-compose.yml file` is using the `awslogs` log driver like this:

    services:
    www:
      logging:
        driver: awslogs
        options:
          awslogs-group: 'Production'
          awslogs-stream: 'www'

After some debugging and tracing through the code that creates that warning, I came across the following issue and pull request which was part of the Docker Compose 1.8.1 release:

https://github.com/docker/compose/issues/3873

https://github.com/docker/compose/pull/3942

This appears to be the cause of my issue. It sounds like support for log drivers was dropped except for 'json-file' and 'journald'.

I see that the original issue (#3873) points to this as the rationale: https://docs.docker.com/engine/admin/logging/overview/#limitations-of-logging-drivers

I'm not sure I understand this... could someone provide more context on this decision? Docker itself supports logging to many different logging drivers. Docker Compose should too.

Does Docker Compose rely on the `docker logs` command for its log streaming? Can someone point me to some code so I can understand this better? Is there any other way? Not being able to use the full features of Docker's logging drivers is a big missing piece from Docker Compose right now.

**Comment by mstenta** [comment]
Cross-posting my commend from the other issue (#3873)...

In that issue, @shin- said:

> Maybe we should exclude anything that doesn't use the default driver.

My comment:

> This seems like a big step backwards, considering that Docker itself supports many other log drivers. If the issue is in the docker-compose logs command, shouldn't it be fixed there? Rather than removing the ability to use all the other log drivers entirely?

**Comment by shin-** [comment]
Hi!

This is due to a limitation of the engine: https://docs.docker.com/engine/admin/logging/overview/#limitations-of-logging-drivers

The change I made in #3942 prevents the Engine from "hanging up" when we request logs for a service with an unsupported driver. It does not affect your ability to run those services, and it is not a regression compared to the previous behavior, since we were never able to stream logs for those drivers.

**Comment by mstenta** [comment]
@shin- Ah ok... I guess I misinterpreted what was happening before...

I just tested it again, and my containers do indeed start up - and the logging to AWS is working.

So I guess the only thing that DID stop working is that I used to be able to see the log output when I ran `docker-compose up` without the `-d` flag. Now I only see the warning message.

Is there any way we can restore that functionality?

**Comment by aikoven** [comment]
The section on limitations [here](https://docs.docker.com/config/containers/logging/configure/#limitations-of-logging-drivers) says that `docker logs` command is only available for `json-file` and `journald` drivers, and that's true for built-in drivers. 

But for custom drivers it's not true, they can implement that logic, see https://docs.docker.com/engine/extend/plugins_logging/#logdriverreadlogs.

There's also a way to detect whether a driver supports reading or not:
https://docs.docker.com/engine/extend/plugins_logging/#logdrivercapabilities

When trying to get logs from a driver that doesn't support reading, nothing hangs for me, `docker logs` prints this:
```
Error response from daemon: configured logging driver does not support reading
```

Should we probably switch from whitelisting to blacklisting?
