### ISSUE TITLE
Version 2.1 not supported on docker 17.03.0-ce, build 60ccb22

### ISSUE THREAD

**Issue by toby-griffiths** [docker/compose#4648]
I've just tried running `docker-compose` on my remote server, to build containers that I can build on my local machine, however I'm seeing the following error when run on the remote server...

```
Version in "./docker/docker-compose.dev.yml" is unsupported. You might be seeing this error 
because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and 
place your service definitions under the `services` key, or omit the `version` key and place your 
service definitions at the root of the file to use version 1.
```

**Local machine (Docker for Mac)**
```
$ docker --version
Docker version 17.03.0-ce, build 60ccb22
```

**Remote machine (Docker on Ubuntu)**
```
$ docker --version
Docker version 17.03.0-ce, build 60ccb22
```

Can anyone help me with whatever it is I'm missing here?

**Comment by shin-** [comment]
What does `docker-compose version` show? Your server probably has an outdated version of `docker-compose` installed.

**Comment by toby-griffiths** [comment]
Ah.  That'll be it...

**Local machine**
```
$ docker-compose --version
docker-compose version 1.8.1, build 878cff1
```

** Remote machine**
```
$docker-compose --version
docker-compose version 1.11.2, build dfed245
```

I thought docker-compose would update with docker.  My bad.

**Comment by toby-griffiths** [comment]
Updated!
