### ISSUE TITLE
Build-only flag

### ISSUE THREAD

**Issue by ekkis** [docker/compose#4650]
I've read through https://github.com/docker/compose/issues/942 but I think that thread primarily focuses on the automatic running of a container.  I think there are more states, actually, and for my use case, being able to build an image without creating and/or running a container would be very useful.

I think what makes the most sense is to have 3 flags (defaulted to `true`):

```
build: true
create: true
start: true
```

or perhaps an array of options could open up the choices for later distinctions:

```
process:
  - build
  - create
  - start
```

as context, I want to be able to build an image along with all my other stuff, but the creation of containers is delegated to a user-driven process and thus docker-compose should not create the container for me

**Comment by shin-** [comment]
Hi!

This is essentially the same ask as #1896 - please refer to the discussion there.

**Comment by ekkis** [comment]
yes, I had read that post before but it doesn't address specifically the issue of being able to build only
