### ISSUE TITLE
docker-compose config is always generating absolutes paths when converting v2 compose files to v3

### ISSUE THREAD

**Issue by mdelapenya** [docker/compose#4656]
Having a `docker-compose.yml` file with volumes in it, when executing:

```shell
docker-compose config > updated-compose.yml
```
Then:
```yaml
    volumes:
    - ./host_volume:/container_volume:rw
```
is converted into:
```yaml
    volumes:
    - /Users/myuser/path/to/project/host_volume:/container_volume:rw
```
I'd expect preserving the relative paths in that case.

I believe the problem is here: https://github.com/docker/compose/blob/master/compose/config/config.py#L1032

Thanks!

**Comment by shin-** [comment]
Unfortunately that is not possible. We need to convert to absolute paths because the Engine will not accept relative paths (it obviously wouldn't be able to know about your current directory), and converting back is not possible in a manner that would ensure idempotence.

**Comment by mdelapenya** [comment]
Yes, but when I execute `docker service create` from a compose file with relative paths... It worked!

Maybe my supposition is wrong...

**Comment by shin-** [comment]
`docker service create` from a Compose file? Do you mean `docker stack deploy`? If so, that command does the same work client-side of converting paths before sending the specification to be processed by the engine (daemon).

**Comment by mdelapenya** [comment]
Sorry, that's correct. Deploying a stack of the use case.

**Comment by mdelapenya** [comment]
Sorry for the typo (*is, not of), I'm typing from my phone
