### ISSUE TITLE
Can't set build --no-cache option as "--no-cache=true"

### ISSUE THREAD

**Issue by dirkschneemann** [docker/compose#4667]
With regular Docker commands, I can do:
`docker build --no-cache .`
or
`docker build --no-cache=true .`

In docker-compose, however, this one works
`docker-compose build --no-cache`
while this one 
`docker-compose build --no-cache=true`
fails with
```
Build or rebuild services.

Services are built once and then tagged as `project_service`,
e.g. `composetest_db`. If you change a service's `Dockerfile` or the
contents of its build directory, you can run `docker-compose build` to rebuild it.

Usage: build [options] [SERVICE...]

Options:
    --force-rm  Always remove intermediate containers.
    --no-cache  Do not use cache when building the image.
    --pull      Always attempt to pull a newer version of the image.
```

Is there a specific reason for this inconsistency? Using the more explicit form would be useful for me in the context of a Jenkins job with a "boolean parameter" which is a checkbox, setting a bash variable to "true" or "false".

**Comment by MichaelPereira** [comment]
This inconsistency comes from the current implementation of the command which doesn't take those cases into account: https://github.com/docker/compose/blob/962ba5b9379c46e54d3f8a31d3e61930b90ccbfa/compose/cli/main.py#L235

I'm not sure how to properly change it to support the following supported version by the docker command:
- `--no-cache=true`
- `--no-cache=false`
- `--no-cache=1`
- `--no-cache=0`

**Comment by shin-** [comment]
We use a different command-line parser because `docker-compose` is written in a different language (Python versus Go).

**Comment by dirkschneemann** [comment]
That makes sense, thank you for the clarification. Would it be possible to align `docker-compose`'s behaviour to that of the `docker` command? Or is this not possible with `docopt` (which is used in `docker-compose` as far as I understand).

**Comment by shin-** [comment]
I don't believe `docopt` supports it. If they release a new version that does, we'll be happy to include it, but I don't really see us spending any time on this otherwise.

**Comment by dirkschneemann** [comment]
Alright, don't worry, this is certainly not the most important issue and one can easily work around it. Cheers
