### ISSUE TITLE
Containers not properly linking

### ISSUE THREAD

**Issue by aemino** [docker/compose#4686]
I'm trying to set up a Docker Compose network for Sentry, but despite trying for a few days, I've been largely unsuccessful. The containers seem to fail to link.

When doing `docker-compose up` I get this error from Sentry:
![image](https://cloud.githubusercontent.com/assets/13167687/24534795/058eb146-1585-11e7-9ad0-87f9db24640b.png)

Taking a look at my syslog, this is appearing:
![image](https://cloud.githubusercontent.com/assets/13167687/24534811/235a76ba-1585-11e7-83e3-6e4ebb9311e6.png)

So, apparently Compose can't find the network, even though it exists.

This is my Compose config file:
![image](https://cloud.githubusercontent.com/assets/13167687/24534867/73d37538-1585-11e7-984e-0ba178f8dfef.png)

Currently using Ubuntu 16.04.2, linux kernel v4.8.0-41-generic. I've tried many different kernel versions without much success.

**Comment by shin-** [comment]
Your sentry is trying to use [legacy container links](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/), which are not used by Compose with a version 3 file. You'll need to provide the environment variables `SENTRY_REDIS_HOST, SENTRY_REDIS_PORT, SENTRY_REDIS_DB` as outlined here: https://hub.docker.com/r/_/sentry/

That error in your syslog is normal - Compose checks for existence of the network, then creates it if necessary.

**Comment by aemino** [comment]
I adjusted my config and this worked! Apologies for the confusion and thank you for helping me out.
