### ISSUE TITLE
Commit 66f4a79 breaks docker-py detection if inside virtualenv

### ISSUE THREAD

**Issue by ulope** [docker/compose#4692]
Commit 66f4a795a2ded1a26b6cf8474edb423727dd585d changed the way an existing left over installation of `docker-py` is detected by now no longer importing pip but rather executing it as a subcommand. 

In principle this is fine however the implementation assumes that the `pip` on the system `PATH` is the "correct" one. This might very well not be the case if docker-compose is installed inside a virtualenv.

The fix is to use `[sys.executable, '-m', 'pip', 'freeze']` instead of `['pip', 'freeze']` as the command to execute in [`compose/cli/__init__.py#L16`](https://github.com/docker/compose/blob/master/compose/cli/__init__.py#L16).
This will ensure that always the pip associated with the current environment will be used.

**Comment by shin-** [comment]
That straight-up will not work with the binary distribution of Compose though.

In my experience, `virtualenv` actually modifies the `PATH` so that `pip` resolves to the binary relevant to the current environment, so that should be an issue in a very small minority of cases. Have you personally experienced a scenario where that wasn't the case?

**Comment by ulope** [comment]
> That straight-up will not work with the binary distribution of Compose though.

Hm, how is that binary distribution created?

> In my experience, virtualenv actually modifies the PATH

That only happens if you `activate` the virtualenv. However that's not necessarily always the case. Setuptools generated entrypoint scripts automatically contain the correct shebang to point to the venvs Python interpreter.

This is for example used by [pipsi](https://pypi.python.org/pypi/pipsi/0.9) (a tool to install "global" tools in their own isolated venvs).

Also when running commands on remote servers via some sort of configuration management or remote execution tool it's often not easy or even possible to `activate` a virtualenv since may of those tools wrap commands in separate `bash` calls.

**Comment by shin-** [comment]
Fixed by #5639
