### ISSUE TITLE
Improve error message when running without permissions

### ISSUE THREAD

**Issue by jleaders** [docker/compose#4705]
This stackoverflow has 13,000 views. I think the error message when running without permissions should state that when it can't connect, it may be a permissions issue.

http://stackoverflow.com/questions/34532696/docker-compose-cant-connect-to-docker-daemon

**Comment by shin-** [comment]
What do you suggest? The reason the connection to the daemon can not be established is fairly opaque to the client.

**Comment by jleaders** [comment]
Well, seeing as 13,000 people can't figure out the reason to the error, I would suggest the following (fairly obvious) change:

If the error message reads as such:

`ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?`

Change it to read as such:

`ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running? Do you have permissions?`

**Comment by jedie** [comment]
The error `Couldn't connect to Docker daemon at http+docker://localunixsocket` is also wrong, if there are some old created files with wrong permissions, see: https://github.com/docker/compose/issues/4437#issuecomment-300109923

So it would be great to enhanced this error messages generally ;)
