### ISSUE TITLE
Documentation - networks are always attachable 2.1 +

### ISSUE THREAD

**Issue by mxlan** [docker/compose#4711]
(If there are priorities, this issue could be set to low)
I don't believe that this: 

https://github.com/docker/compose/pull/4232
networks being attachable are enabled version 2.1+

is mentioned in the documentation.

See:
https://docs.docker.com/compose/networking/
https://docs.docker.com/compose/compose-file/compose-file-v2/#network-configuration-reference
https://docs.docker.com/compose/faq/

Could this be added, or is it expected to search for features within the changelogs?
I'd say a blurb / footnote under https://docs.docker.com/compose/compose-file/compose-file-v2/#network-configuration-reference is good enough

From changelog: Networks created by Compose are now always made attachable (Compose files v2.1 and up).

**Comment by shin-** [comment]
Thanks @mxlan - You're right that this is probably not mentioned in the docs currently. Could you report this over at [our docs repo](https://github.com/docker/docker.github.io) so it can be amended?
