### ISSUE TITLE
invalid port specification with 1.12.0

### ISSUE THREAD

**Issue by avdv** [docker/compose#4722]
I was using docker-compose 1.11.1 and have now upgraded to 1.12.0.

My docker-compose file is version `'2'`.

The new version exits with an error:

```
ERROR: for elastic5  Cannot create container for service elastic5: invalid port specification: "127.0.0.1"
```

The port specification of elastic5 is:

```
    ports:
      - '127.0.0.1::9200'
```

AFAICS, this should work fine (as it did before upgrading) since it uses the `ip::containerPort` format of the publish option to `docker run`.

**Comment by shin-** [comment]
Thank you for the report!

**Comment by avdv** [comment]
Thanks for the fix, but would a regression like this not call for a bugfix release instead of waiting for milestone 1.13.0?

**Comment by xarem** [comment]
yes - should be released as a bugfix instead with v1.13.0 - really bad decision. docker-compose v1.12 is useless for us because of this bug.

**Comment by shin-** [comment]
You can use [1.13.0 RC1](https://github.com/docker/compose/releases/tag/1.13.0-rc1) which includes the fix.

**Comment by cesarjorgemartinez** [comment]
Its failing using (version 1):
    ports:
      - ':port1:port2'
We test with 1.11.2, 1.13.0 RC1, 1.14.0

**Comment by shin-** [comment]
That notation is invalid. You can't have a leading colon.

**Comment by cesarjorgemartinez** [comment]
Yes, is invalid, but is a bad specification.
Example:
I have containers with different configurations depending on link to 127.0.0.1 or all. Then I have a variable indicating this:
VAR=""
or
VAR="127.0.0.1"

Then:
- '${VAR}:port1:port2'
Fail.

I need to do a bad syntax:
VAR=""
or
VAR="127.0.0.1:"

Then:
- '${VAR}port1:port2'
Good. But is a very bad form to do.
