### ISSUE TITLE
Host files not appearing in Docker in Docker container on Ubuntu

### ISSUE THREAD

**Issue by iainfogg** [docker/compose#4726]
I'm experimenting with using TeamCity's Docker agent image to add an extra agent to our build server (the build server itself has TeamCity installed normally, it's not using Docker for the main TeamCity server).

The Docker agent image downloads a copy of my application, but when it runs docker-compose to run a command in the container defined in docker-compose.yml, the files from the folder where docker-compose.yml is do not appear inside the container - a folder exists, but it's empty.

The docker-compose.yml file currently is:
```
version: '2'
services:
  php:
    build: docker/build/php/.
    volumes:
     - .:/var/test/folder
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
```

The networks stuff is in there because there's going to be another service containing a database, but I've commented that out until I can resolve this issue.

The Dockerfile that's in the build folder specified above is:
```
FROM php:5.6
RUN apt-get update && apt-get install -y \
        php5-intl php5-mongo \
        && echo "extension=/usr/lib/php5/20131226/mongo.so" | tee /usr/local/etc/php/conf.d/ext-mongo.ini
WORKDIR /var/test/folder
```

If I run it on my Mac, I go into /var/test/folder and see the files from the host. However, if I exec into the Docker TeamCity agent, and from there, exec into the php container, I have a folder /var/test/folder but it is empty. Because it's empty, obviously I am unable to do any of the build steps which were the point of using the TeamCity agent!

**Docker version on the Ubuntu host:**
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Docker version inside the TeamCity agent:**
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**Docker compose version inside the TeamCity agent:**
```
docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```
**Docker version on my Mac, which is working:**
```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 06:06:36 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Tue Apr  4 00:37:25 2017
 OS/Arch:      linux/amd64
 Experimental: true

```
**Docker compose version on my Mac:**
```
docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by shin-** [comment]
Can you outline the commands you are running when encountering this issue? It's important to be accurate so we can diagnose the problem.

**Comment by iainfogg** [comment]
Sure @shin- - sorry for missing that useful info off first time.

From my TeamCity host, I run this command to get into the already running Docker TeamCity agent:
`docker exec -it elastic_kare /bin/bash`

On the agent, there's a folder which contains the source for my project, including the docker-compose.yml file. In that folder, I type this command:
`docker-compose run php /bin/bash`

That takes me into the php container, which has a folder /var/test/folder in it, but that folder is empty, rather than showing the contents of the folder that I was in with my application in on the agent.

Running exactly the same command (`docker-compose run php /bin/bash`) on my Mac, in the folder with that application in it, takes me into the php container, and when I run `ls`, it shows me the files from my application.

Thanks!

**Comment by shin-** [comment]
Sorry for the delay - thank you for the additional info.

[Reading about the TeamCity builder agent](https://hub.docker.com/r/jetbrains/teamcity-agent/), there seems to be 2 ways to make Docker accessible from inside the agent.

> 1) Docker from the host (in this case you will benefit from the caches shared between the host and all your containers, but drawback is the security issue - your build actually can harm your host Docker, so it is on your own risk)
> ```
> docker run -it -e SERVER_URL="<url to TeamCity server>"  \
>     -v <path to agent config folder>:/data/teamcity_agent/conf \
>     -v /var/run/docker.sock:/var/run/docker.sock  \
>     jetbrains/teamcity-agent
> ```
> 2) New Docker daemon running within your container (please note that in this case the container should be run with —privileged flag)
> ```
> docker run -it -e SERVER_URL="<url to TeamCity server>"  \
>     -v <path to agent config folder>:/data/teamcity_agent/conf \
>     --privileged -e DOCKER_IN_DOCKER="start" \
>     jetbrains/teamcity-agent
> ```

Are you using method 1? If so, your volume mount needs to reflect the path of the project folder on your host, which is where the Engine will try to mount from. An arguably better solution would be to switch to using the second method instead.

Hope that helps - if anything's unclear, let me know and I'll do my best to explain.

**Comment by iainfogg** [comment]
Hi @shin- - thanks, that was really helpful!

So, I have been using method 1 so far, which was not working (i.e. showing an empty folder inside my 'inner' container). I have tried method 2, which works as expected, with my project files available - thanks so much for pointing that out.

What I am still unclear of, however, is how to get method 1 working (which is reliant on knowing where the folder is on the host), to get the advantage of the caches. If I am calling docker-compose from inside the agent container to fire up the actual test container, I'm not manually providing a folder to the test container that's being started - I'm relying on the docker-compose.yml file with this inside it:
```
    volumes:
     - .:/var/test/folder
```
That works, as I understand, by looking at the current folder and passing that folder in to the new container as a volume. The yml file has no idea of where that folder would be on the actual host server, so I'm not sure how I would run docker-compose from inside the agent to fire up a test container with knowledge of where that folder would be on the host?

Thanks, Iain

**Comment by shin-** [comment]
The issue with method 1 is that `Compose` considers its filesystem to be the container's, and determines absolute paths based on that filesystem. But the engine you're communicating with is not inside this container - it's on the host, and uses the host's filesystem.

You could work around this by using the absolute path of the folder you want to mount on the host inside your Compose file (you can use the output of `docker-compose config` on your host, that will expand paths automatically)

**Comment by iainfogg** [comment]
Thanks @shin- - I'm not sure putting the absolute path of the folder in the host location in my compose file feels a nice solution, as that will affect anyone using docker-compose e.g. devs who could have the application anywhere on their laptop, hence using the current folder in the compose file.

I'm afraid I didn't understand what you meant about using `docker-compose config` either, sorry! Could you clarify?

**Comment by shin-** [comment]
> I'm afraid I didn't understand what you meant about using docker-compose config either, sorry! Could you clarify?

Sorry, I meant if you run `docker-compose config`, the output will be a valid Compose file with absolute paths substituted for relative paths. You could use that output inside the agent container to work around the issue.

**Comment by iainfogg** [comment]
@shin- got you, that makes sense, thanks for all your help with this, it's now much clearer!
