### ISSUE TITLE
Building on Raspberry armhf requires patch of Dockerfile

### ISSUE THREAD

**Issue by daccle** [docker/compose#4733]
Hi folks!

I am very sorry, I am not deep down into docker development and I am just learning about the whole docker world. Maybe I am just missing an obvious option. But in order to build on Raspbian on a Raspberry Pi 3 I need the following patch to `Dockerfile`
```patch
diff --git Dockerfile Dockerfile
index a03e151..028277a 100644
--- Dockerfile
+++ Dockerfile
@@ -1,4 +1,4 @@
-FROM debian:wheezy
+FROM armhf/debian:latest

 RUN set -ex; \
     apt-get update -qq; \
```

If there is an option I am missing here please point me to that option and close the issue.

Best, Daniel

**Comment by shin-** [comment]
We already have a Dockerfile to build for ARM: https://github.com/docker/compose/blob/master/Dockerfile.armhf

You can build the image using the following command (from the repo's root): `docker build -t compose:armhf -f Dockerfile.armhf .`

**Comment by daccle** [comment]
Okay, great. I just didn't found that option in the documentation. I will close this issue here.

Thank you very much!
