### ISSUE TITLE
docker-compose validation failed

### ISSUE THREAD

**Issue by drrtuy** [docker/compose#4739]
Docker-compose has a peculiar syntax check feature that states: no duplicate arguments in the entrypoint configuration key. There are many situations when there are duplicate args in a command string.  Here is an example output which drives me crazy:

root@cs81649:~/bottledwater-pg# docker-compose up -d kafka schema-registry postgres
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Service 'psql' configuration key 'entrypoint' contains non unique items, please remove duplicates from ['psql', '-h', 'postgres', '-U', 'postgres']

Is it possible to change the syntax check behavior?

**Comment by andreyev** [comment]
Hmmm... Similiar with https://github.com/adobe-apiplatform/api-gateway-request-validation/commit/f05c8aed13c08239742c7562f694dc2f1fda7803, did you tried change it to `['psql', '-h postgres', '-U postgres']`?

**Comment by shin-** [comment]
I agree that testing for this probably doesn't make much sense. Can I ask which version of the Compose file you're using, and what is the output of `docker-compose version` in your environment?
