### ISSUE TITLE
Feature request: make it possible to manage external services

### ISSUE THREAD

**Issue by rivaros** [docker/compose#4745]
Let's say I would like to update one of the external services during compose build.
For example map one more volume to rsync container. Is it possible to restart external adding some options to it?

**Comment by shin-** [comment]
That seems contradictory to me - if you declare a service as external, `docker-compose` should absolutely be hands off and **not** try to manage it. If you want it to be managed, just include it as a regular service in your Compose file.

**Comment by rivaros** [comment]
Let me ask another way - I'd like to have a "post-build/pre-build hook" possibility, so I can restart/modify some commonly used containers like my web-proxy container or dns container which are shared among multiple projects.

**Comment by shin-** [comment]
A container should be stateless though. I'm not sure we want to encourage this with a feature that's essentially an anti-pattern.

**Comment by rivaros** [comment]
@shin- Agree on that. Have just read the article from Mike Coleman explanining the idea https://blog.docker.com/2016/03/containers-are-not-vms/

But before closing, just one more clarification:
What about possibility of mapping subpathes of named volumes like ```named_volume/some_path:/smth_in_container/some_path``` ??

Doe sit break any rulres?

**Comment by ijc** [comment]
Seems this conversation has run its course, so I'll close.

This sort of mixed system (some docker-composee, some cloud, some 3rd thing) is something which [CNAB](https://github.com/deislabs/cnab-spec) is looking to address I think.
