### ISSUE TITLE
Disable docker-compose logs linebuffer

### ISSUE THREAD

**Issue by WillemMali** [docker/compose#4753]
I have a few setup scripts that output information like so:

    Setting up this thingy... done.
    Setting up that thingy... OK.
    Finalizing... ERROR! Everything is bad.

Some of these steps can take a long time, but because `docker-compose` seems to buffer lines when calling `docker-compose logs -f` I only see the previous statement, and not what's currently happening because the line isn't finished.

What I want to see:

    Setting up things... done.
    Setting up more things...

What I see:

    Setting up things... done.
    <nothing here until the 'done' pops in and finishes the line>

This would be more functional, and also less unexpected as it would follow the behavior of `tail -f` which many programmers are familiar with.

**Comment by dalbertom** [comment]
If I remember correctly, this used to work in `v1.8.0` but stopped working afterwards. We have a container that starts JBoss and the last line would say something like `started in 148119ms - Started 1734 of 1766 services (80 services are lazy, passive or on-demand)` but that doesn't show up anymore until a new statement is logged.

**Comment by Ghazgkull** [comment]
Using `docker-compose up --force-recreate` to bring up our containers, I consistently see that the last line of console output isn't printed to the terminal. I have to manually run `docker logs -f <container-id>` in order to see the most recent output. Is what I'm seeing the same problem reported here?

**Comment by WillemMali** [comment]
Probably, yeah. I'm looking at switching to `rkt` myself, I'm running a few
K8s clusters with Docker containers and it's supposed to be quite easy to
switch.

**Comment by rocketmonkeys** [comment]
Please re-open this one.  It still happens, and makes development much harder (often the last line is the error/exception that just happened, and you don't know until the next line is logged).
