### ISSUE TITLE
Container Linking not working in docker-compose 

### ISSUE THREAD

**Issue by abhishek246** [docker/compose#4769]
`
      version: '2'

     services:
        redis:
            image: redis:alpine
            hostname: redis
            container_name: redis
            ports:
                - "6379:6379"
            networks:
                vpcbr:
                    ipv4_address: 10.5.0.5
            restart: on-failure

    backend:
        build: ./myapp
        hostname: myapp
        container_name: myapp
        depends_on:
            - redis
        links:
            - redis:redis
        ports:
            - 9003:8082
        volumes:
            - /Users/abhishek/Myapp/:/home/
        networks:
            vpcbr:
                ipv4_address: 10.5.0.6
        restart: on-failure

    networks:
       vpcbr:
         driver: bridge
       ipam:
          config:
              - subnet: 10.5.0.0/16
                 gateway: 10.5.0.1`

The above is my docker-compose file. I'm unable to make a connection between Redis and backend.I have found a workaround by assigning static IP for both of them and adding it to host of backend via an EntryPoint script in DockerFile. Please let me what is the issue.

my /etc/hosts file
`
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.5.0.6        myapp`

**Comment by shin-** [comment]
You should remove `links` - they're not necessary when you use networks. Unless you need to connect to your `redis` service manually, you can also remove the `hostname` entry, and change `ports` to remove the external mapping.
It's also better not to use `container_name` unless you absolutely need to.

After you've made all those changes, you should be able to connect from your backend to `redis:6379` without issue.

**Comment by abhishek246** [comment]
Hello Shin,

Thanks for the input. It worked.
If you don't mind can you tell me why it failed in the previous config?

Thanks a lot and I'm closing this issue
