### ISSUE TITLE
.yaml extention does not work with override file.

### ISSUE THREAD

**Issue by gorzell** [docker/compose#4771]
The [current documentation](https://docs.docker.com/compose/compose-file/#service-configuration-reference) states that you can use either the `.yml` or `.yaml` extension for your compose file, however this does not appear to hold true for the `docker-compose.override` file.  In that case only `.yml` seems to work.  It would be really nice if the behavior here was consistent.

**Comment by eliat123** [comment]
#dibs

**Comment by shin-** [comment]
Fixed-by: #4859
