### ISSUE TITLE
Can't recreate containers using updated image - Failed to remove root filesystem

### ISSUE THREAD

**Issue by dylanrhysscott** [docker/compose#4781]
Hi,

I'm encountering this issue more and more with Docker Compose - It seems that when there is an updated image for a container in `docker-compose.yml` the engine fails to remove the old version and recreate the container. This leaves the old container in a dead state and causes a consistent error bringing up the project. Interestingly the new container is also created. Here is an example error:

`ERROR: for dylanscott  Driver aufs failed to remove root filesystem fe229c7af0b28f273f20ce1c15710f5787d4142adee07f3737db86b99c05862f: rename /var/lib/docker/aufs/mnt/7bed86d5620a57cbf1bdc4d41ed5d2eb5341fb65001add92de0dbbac990cbebe /var/lib/docker/aufs/mnt/7bed86d5620a57cbf1bdc4d41ed5d2eb5341fb65001add92de0dbbac990cbebe-removing: device or resource busy`

I can get around this error by manually removing the dead container using `--force`. It does throw the error again but running `docker ps -a` does show Docker removed the dead container

OS: Debian 8
Docker Version: 17.04.0-ce build 4845c56
Docker Compose Version: 1.12.0 build b31ff33

Output from `docker info`

```
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 111
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 494.4MiB
Name: dylanscott.me
ID: U6KQ:RADY:BJFY:C4QR:AHYI:2HOU:3VA2:CLY7:5VB2:Q2N7:SKS2:H7LW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dylanrhysscott
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

Any ideas?

Thanks

Dylan

**Comment by shin-** [comment]
`aufs` errors happen at the engine level and are unrelated to Compose. I see you've already posted on `moby/moby` as well, so I'll let the people there follow up on this specific issue.
