### ISSUE TITLE
Support for --env-file

### ISSUE THREAD

**Issue by benlangfeld** [docker/compose#479]
Some of the containers in my project require sensitive data (such as 3rd party API tokens) to be passed as environment variables. I understand that I can enumerate these without values in my `fig.yml` to be picked up from the host environment, but then I still need some way to get them there, meaning one of:
- Passing these on every fig invocation (unacceptable due to the repetition), or
- Yet another script to wrap fig and load these environment variables from disk.

Docker already provides support for loading a container environment from disk in the `--env-file` option to `docker run`. It would be nice if fig exposed this as `environment_file` as a parallel to the current `environment` option.

I'd be happy to submit a PR for this, but in order to do so I would need pointing in the right direction by someone who actually knows Python. I figure the implementation would likely be as easy as extending [this constant](https://github.com/docker/fig/blob/master/fig/service.py#L15) and that I'd probably need a test similar to [this one](https://github.com/docker/fig/blob/master/tests/integration/service_test.py#L371-L375). Am I on the right track so far?

**Comment by bobcolner** [comment]
+1

**Comment by benlangfeld** [comment]
That won't help, @bobcolner. See my last comment.
