### ISSUE TITLE
docker-compose logs strip colors when outputting to a pipe

### ISSUE THREAD

**Issue by mildred** [docker/compose#4795]
`docker-compose logs` do not keep colored output when writing through a pipe. It's easy to see. Just run `docker-compose logs | cat` and the colors are gone.

This is generally a good default, however sometimes you want to keep the colors, including the prefix generated by docker-compose and the colors within the applicative logs themselves. It would be nice to have a `--colors` option to force keeping the colors in that case.

**Comment by mnottale** [comment]
This no longuer seem to be the case, I tested with `docker-compose logs|cat` and `docker-compose logs >somefile` and both output are colored.
