### ISSUE TITLE
Allow opt-ing into override file behavior

### ISSUE THREAD

**Issue by taiidani** [docker/compose#4802]
## Feature Proposal

A `COMPOSE_OVERRIDE_FILENAME` [CLI environment variable](https://docs.docker.com/compose/reference/envvars/) that allows customization of which file Compose looks for when searching for the `docker-compose.override.yml` file in the system.

Specifying this would have the effect of force-enabling this functionality even when `-f` or COMPOSE_FILE is specified.

## Use case

Great Docker Community Slack conversation here that describes multiple use cases: https://dockercommunity.slack.com/archives/C2X82D9PA/p1494171567481639

To summarize -- our current implementation has a 2-tier YML setup where:
```
docker-compose.yml == Developer environment
[docker-compose.override.yml] == gitignored override
```

We currently put "#STUB OUT" comments in the base file that we `sed` away to remove, making it into a production configuration. I would like to see a 3-tier YML setup where:
```
docker-compose.yml == Production environment
docker-compose.dev.yml == Developer environment
[docker-compose.override.yml] == gitignored override
```

So that we can rid ourselves of the custom `sed` line-stripping solution and start using that `docker-compose.yml` file as the base for our other `.stage` and `.live` YML files.

The override file itself has numerous scenarios causing us to need to gitignore it. It is also not needed by all our developers so placing it in the COMPOSE_FILE env var would be an inconvenience (and a little hacky).

### Why not make it override all the time?

The override file can't be applied by default when using `-f`/COMPOSE_FILE to preserve backwards compatible behavior and when using it with a `.prod.yml` file for production deployments. However if we added a new env var such as COMPOSE_OVERRIDE_FILENAME we could allow users to opt-in to that behavior, and get customization of which filename to look for at the same time.

**Comment by taiidani** [comment]
I'm having a hard time getting Compose to compile on macOS so I can't test my chicken scratch, but here's the gist:

```diff
---
 compose/config/config.py | 20 +++++++++++++++++---
 1 file changed, 17 insertions(+), 3 deletions(-)

diff --git a/compose/config/config.py b/compose/config/config.py
index f1195c8..45ec711 100644
--- a/compose/config/config.py
+++ b/compose/config/config.py
@@ -244,7 +244,7 @@ def find(base_dir, filenames, environment, override_dir=None):
         )
 
     if filenames:
-        filenames = [os.path.join(base_dir, f) for f in filenames]
+        filenames = get_specified_config_files(base_dir, filenames)
     else:
         filenames = get_default_config_files(base_dir)
 
@@ -271,7 +271,6 @@ def validate_config_version(config_files):
                     next_file.filename,
                     next_file.version))
 
-
 def get_default_config_files(base_dir):
     (candidates, path) = find_candidates_in_parent_dirs(SUPPORTED_FILENAMES, base_dir)
 
@@ -286,9 +285,24 @@ def get_default_config_files(base_dir):
 
     return [os.path.join(path, winner)] + get_default_override_file(path)
 
+def get_specified_config_files(base_dir, filenames):
+    """
+    Takes a base directory and list of specified filenames. Returns the
+    absolute paths to the config files. If COMPOSE_OVERRIDE_FILE is specified
+    will also return path to override file.
+    """
+    filenames = [os.path.join(base_dir, f) for f in filenames]
+
+    if "COMPOSE_OVERRIDE_FILE" in environment:
+        (candidates, path) = find_candidates_in_parent_dirs([environment.get("COMPOSE_OVERRIDE_FILE")], base_dir)
+
+        if candidates:
+            filenames = filenames + [os.path.join(path, candidates[0])]
+
+    return filenames
 
 def get_default_override_file(path):
-    override_filename = os.path.join(path, DEFAULT_OVERRIDE_FILENAME)
+    override_filename = os.path.join(path, environment.get("COMPOSE_OVERRIDE_FILE", DEFAULT_OVERRIDE_FILENAME))
     return [override_filename] if os.path.exists(override_filename) else []
 
 
-- 
```

**Comment by taiidani** [comment]
Considering this being technically a contribution and my compilation problems with macOS I have provided an appropriate cute animal picture as a sacrifice to the Moby gods.

![funny-pictures-bomb-squad-cat-chooses-the-blue-wire](https://cloud.githubusercontent.com/assets/902500/25787260/dadcae60-3354-11e7-9e19-e7a2d0bcd115.jpg)

**Comment by shin-** [comment]
Thank you for your suggestions and contribution!
After giving this some thought over the past few days, I have decided against pursuing the implementation of this feature. See my comment in #5100 .
