### ISSUE TITLE
"docker-compose run" stops (deletes!) other scaled services

### ISSUE THREAD

**Issue by jamshid** [docker/compose#4803]
I see the "breaking change" about `up` resetting a service back down to its "default" value (the last scale'd value?)  https://github.com/docker/compose/releases/tag/1.13.0.

But it seems even doing a `docker-compose run other-service /script.sh` causes *other* services to be re-scaled. What's weird is my other services are being scaled back down to 1, so I'm losing volumes! I use `depends_on`, maybe that's contributing factor. 

Sorry I haven't made a simple repro but hoping someone knows more this seems like a serious regression.

**Comment by shin-** [comment]
Thanks, I will look into this.

**Comment by jamshid** [comment]
I'm surprised this isn't considered serious enough for a quick 1.13.1, or is 1.14 imminent?

Any non-trivial users of compose (yml uses dependencies, scale) will be bitten by this bug.

Scenario: Docker for Mac hasn't released on Stable since early March, so they seem due for a release. If they release with compose 1.13.0 (currently on their Edge), this bug will reach a lot of users.

**Comment by shin-** [comment]
1.14.0 will come out early June and will be included with the next Docker
for Mac stable.

**Comment by jamshid** [comment]
@shin, a related problem...
Using `docker-compose version 1.14.0-rc2, build 24dae73` I see that `docker-compose up -d foo` also stops and removes containers for another (dependent) `bar` services that had been scaled with `docker-compose up -d --scale bar=3`. That's not intentional behavior is it?

**Comment by shin-** [comment]
I'm not sure there's a straight answer to that question. It could be argued either way, but I see where you're coming from. Do you mind opening a new issue?
