### ISSUE TITLE
New "scale" field in service definition should allow use of env variables

### ISSUE THREAD

**Issue by jamshid** [docker/compose#4804]
Do I really have to hard-code the scale value in docker-compose.yml? Why not allow it to be specified by an env variable like:

```
  elasticsearch:
    scale: ${ELASTICSEARCH_SCALE}
```
With docker-compose 1.13.0 I get this error when attempting that:
```
$ export ELASTICSEARCH_SCALE=3
$ docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.elasticsearch.scale contains an invalid type, it should be an integer
```

**Comment by shin-** [comment]
Yes - this is part of a bigger issue that we want to tackle. See #2730 and #2759

**Comment by shin-** [comment]
#5291
