### ISSUE TITLE
v2.2 service init option not supported in v3

### ISSUE THREAD

**Issue by LukeusMaximus** [docker/compose#4805]
PR #4716 added init to docker-compose services in v2.2 compose files, but not v3. Please can v3 be made to support the init option as well.

**Comment by shin-** [comment]
v3 format requests should be created on [moby/moby](https://github.com/moby/moby)

**Comment by ionelmc** [comment]
@shin- Umm wat? What's special about the v3? I don't get it. Why wasn't v3 support added in #4716?

**Comment by shin-** [comment]
@ionelmc v3 is the format for Swarm stacks. It is (partially) compatible with `docker-compose`, but updates to it are driven at the engine level, not here.
