### ISSUE TITLE
Context path relative to cwd

### ISSUE THREAD

**Issue by kmalakoff** [docker/compose#4806]
I have been writing build scripts in Node.js that include docker-compose.yml files and would like to install them globally (eg. `npm install -g`) so that they can be available to multiple clusters of servers.

I would like to pass an option to docker-compose that provides the cwd for `context` entries to not make them relative to the compose file (https://docs.docker.com/compose/compose-file/#context), but instead to the current cwd.

`docker-compose build -f {absolute_path} -cwd {cwd}`

Is this something that you would be interested in supporting?

**Comment by shin-** [comment]
You can use `--project-directory` to the same effect, I think.

**Comment by kmalakoff** [comment]
@shin- thank you for the suggestion. Unfortunately, I do not have the `--project-directory` option in docker-compose.

```
 → docker-compose --help
Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE             Specify an alternate compose file (default: docker-compose.yml)
  -p, --project-name NAME     Specify an alternate project name (default: directory name)
  --verbose                   Show more output
  -v, --version               Print version and exit
  -H, --host HOST             Daemon socket to connect to

  --tls                       Use TLS; implied by --tlsverify
  --tlscacert CA_PATH         Trust certs signed only by this CA
  --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
  --tlskey TLS_KEY_PATH       Path to TLS key file
  --tlsverify                 Use TLS and verify the remote
  --skip-hostname-check       Don't check the daemon's hostname against the name specified
                              in the client certificate (for example if your docker host
                              is an IP address)
```

There's `--project-name`, but after trying it, it looks like it only sets the name prefix for the running containers, but does not affect the directory.

**Comment by shin-** [comment]
It's been introduced in 1.12.0, check that your version is up to date!

**Comment by kmalakoff** [comment]
Cool. Thank you for the clarification.

I use docker-for-mac and it's latest docker-compose version is "docker-compose version 1.11.2, build dfed245". When they release 1.12.0, I'll give it a shot and will report back here.
