### ISSUE TITLE
Improve the error message when the daemon is not running

### ISSUE THREAD

**Issue by tomasaschan** [docker/compose#4814]
### Expected behavior
When I run e.g. `docker-compose up hello` (see `docker-compose.yml` below) and the Docker daemon is not running, I expect an error message to that effect (much like `docker ps` gives me).

### Actual behavior
Instead, I get a Python stack trace, ultimately complaining that "The system cannot find the file specified."

> PS C:\Work\SBAB\sbab-klirra-2017-01-19\backend> docker-compose up -d server
> Traceback (most recent call last):
>   File "docker-compose", line 3, in <module>
>   File "compose\cli\main.py", line 64, in main
>   File "compose\cli\main.py", line 116, in perform_command
>   File "compose\cli\main.py", line 876, in up
>   File "compose\project.py", line 385, in up
>   File "compose\project.py", line 590, in warn_for_swarm_mode
>   File "site-packages\docker\api\daemon.py", line 73, in info
>   File "site-packages\docker\utils\decorators.py", line 47, in inner
>   File "site-packages\docker\api\client.py", line 183, in _get
>   File "site-packages\requests\sessions.py", line 488, in get
>   File "site-packages\requests\sessions.py", line 475, in request
>   File "site-packages\requests\sessions.py", line 596, in send
>   File "site-packages\requests\adapters.py", line 423, in send
>   File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
>   File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
>   File "httplib.py", line 1042, in request
>   File "httplib.py", line 1082, in _send_request
>   File "httplib.py", line 1038, in endheaders
>   File "httplib.py", line 882, in _send_output
>   File "httplib.py", line 844, in send
>   File "site-packages\docker\transport\npipeconn.py", line 31, in connect
>   File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
>   File "site-packages\docker\transport\npipesocket.py", line 50, in connect
> pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
> Failed to execute script docker-compose

### Steps to reproduce

With the following `docker-compose.yml` as the only file in the directory, and the Docker daemon stopped, run `docker-compose up hello`:

```
version: '3'
services:
  hello:
    image: hello-world
```
### Host distribution and version
```
PS C:\hello> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      15063  0
PS C:\hello> docker --version
Docker version 17.03.1-ce, build c6d412e
PS C:\hello> docker-compose --version
docker-compose version 1.11.2, build f963d76f
```

**Comment by gdbjohnson** [comment]
Just came here to post the same thing.  I'm on Win7, and forgot to run my docker in the `Docker Quickstart Terminal`.  Docker's been around for too long for this kind of unfriendly error.

**Comment by ijc** [comment]
Behaviour today seems to be:
```console
$ sudo service docker stop
$ docker-compose up
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
```

Closing accordingly.

**Comment by tomasaschan** [comment]
@ijc I think you need to test it on Windows to test the appropriate behavior.

Current behavior with Docker for Desktop (18.09.2, build 6247962) on Windows 10 (build 1809) is
```
PS> docker-compose up -d
ERROR: Windows named pipe error: The system cannot find the file specified. (code: 2)
```
which is slightly better than the python stack trace, but still not as user-friendly as it could/should be.

**Comment by ijc** [comment]
Thanks for the update, reopening.

**Comment by tomasaschan** [comment]
@ijc I think this merits re-opening, unless you've decided you're not going to bother with this.
