### ISSUE TITLE
Declare default environment variables in (CUSTOM) file 

### ISSUE THREAD

**Issue by deanmraz** [docker/compose#4815]
# Goal
The ability to declare default environment variables in custom env file. 

## Current 
- ability to define in .env file
- defined here https://docs.docker.com/compose/env-file/ 

## Request
- ability to define custom file

## Issue
- .env should not be committed to the repository 
- developers are frustrated when docker-compose up doesn't work out of the box, first have to figure out which environment variables are required, then decided what values to use. 

## Use case
- We define the port in the .env file and would like that to persist between developer machines without the requirement of creating or knowing what environment values to use. 

Open for suggestions and alternatives. Thanks for your time!

**Comment by eliat123** [comment]
@deanmraz You can use env_file, see https://docs.docker.com/compose/compose-file/#envfile

**Comment by shin-** [comment]
@eliat123 I'm sorry but that's incorrect. `.env` and `env_file` have completely different roles. Please read https://docs.docker.com/compose/environment-variables/ carefully.

@deanmraz Maybe commit a `.env_sample` to your repository that people can `cp` into `.env` when first cloning the project?

**Comment by shin-** [comment]
You could also use the extended syntax to define a default port in your `docker-compose.yml`, like `${PORT:-8080}`: https://docs.docker.com/compose/compose-file/#variable-substitution

**Comment by deanmraz** [comment]
@shin- 
- Committing a `.env_sample ` is basically what we do today, but just ended up committing the `.env` file and putting the private info in another ignored env file. 
- Env variable substitution maybe a good alternative

That being said, I question the intent on using .env. Typically, thats used for the application's private data, which I found the container env (eliat123 mentioned) is perfect for. 

I wonder if the private data use cases apply to docker-compose `env vars`. Seems like this feature benefits docker-compose host / container setups, like ports, image tags, etc. 

In any case, having this is great! I've been able to simplify the various deployments that in the past required extending multiple docker-compose files to change these values. 

My intent was just to make sure the feature didn't exist, since I'm going against best practices and committing the .env file.

**Comment by deanmraz** [comment]
@shin- no comment on the previous message?

**Comment by shin-** [comment]
@deanmraz Sorry! I mistakenly assumed this was resolved. The reason I suggested committing a file with a different name (and adding the actual .env to dockerignore) is so that you don't accidentally commit private values which belong there. 

I'm not sure adding another special meaning file for default env values is really worth it, especially considering the feature already exists in another form.

I hope that clarifies things.

**Comment by deanmraz** [comment]
@shin- okay, thanks!

**Comment by ein-shved** [comment]
Hi! Sorry for necro-bump, but I faced with the situation, In which such option should be (or another solution for situation). Say I have a basic service which do some basic task:

```Yaml
basic:
  command: some_basic_task
```
And say, I have another service, based on the first, which requires extra path, which will be mounted and passed to task:

```Yaml
not_so_basic:
  extends: basic
  volumes:
    - "${ARG:?This is required}:/guest_path"
  command: some_basic_task --not-so-basic-path=/guest_path
```

This produced an "This is required" error when trying to launch the basic task. With different .env files in the tasks I could to mask the ARG in `basic` with some dummy value and unmask it in `not_so_basic`. This is a hack but the only way to solve the problem when there no alternatives.
