### ISSUE TITLE
Stack deploy for docker-compose.yml doesn't pick node

### ISSUE THREAD

**Issue by adityacs** [docker/compose#4828]
When trying to deploy service with docker stack deploy, docker is not able to pick node. 
![image](https://cloud.githubusercontent.com/assets/7681197/26105171/8f9c084a-3a5e-11e7-9d14-fb96137ebb10.png)

When I try to create the service manually it works correctly.
![image](https://cloud.githubusercontent.com/assets/7681197/26105199/ae32c456-3a5e-11e7-9620-54aa2bdefa2b.png)

Kindly help me with this.

**Comment by shin-** [comment]
As this is a Swarm mode issue, it should be reported there: https://github.com/docker/swarmkit
