### ISSUE TITLE
docker-compose not showing logs for all containers

### ISSUE THREAD

**Issue by bibiteix** [docker/compose#4837]
I'm using docker-compose for two containers and I run it using `docker-compose up -d`
But when I try to see its logs with `docker-compose logs -f` it shows me only the logs of one of the containers. I tried running the other container individually and it shows the logs just fine. I appreciate any help.

**Comment by shin-** [comment]
- Are you using a different log driver from `json-file` (default) or `journald`?
- What is the output of the `docker-compose version` command?
- Can you share your `docker-compose.yml` file?

**Comment by bibiteix** [comment]
`journald`
```
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

```version: '2'
services:
    service-whose-logs-are-not-showing:
        ports:
            - "5553:5554"
        image: image-name
        command: python3.4 /path/pythonfile.py
        volumes:
           - /path1:/path2
           - /path3:/path4
        user: "username"
        extra_hosts:
           - "mxgateway:172.16.1.1"
        restart: always
    service-whose-logs-are-showing:
        image: image-2-name
        command: <command>
        restart: always
```

Note that if I run `image-name` by itself, the logs appear just fine.
Thanks.

**Comment by bibiteix** [comment]
Hi, I just realized it was an issue with Python not flushing its stdout. I ended up adding the following code to my `docker-compose.yml` 
```        environment:
            - PYTHONUNBUFFERED=1```

Do you know if this is a common thing to happen with Docker?

**Comment by docwhite** [comment]
Oh god I spent good time chasing this up :) It happened to me while using Flask, I had to hit save on the python code so the server would restart and flush the accumulated error tracebacks.

Thanks a lot @bibiteix

**Comment by MCTRACO** [comment]
this issue was also happening to me with python.

**Comment by brean** [comment]
I figured out that for some error output in Python (in my case Tracebacks and "rospy.logerr")  are not printed when you set `tty: true`. So in combination with setting "PYTHONUNBUFFERED=1" make sure you are NOT using `tty: true`

**Comment by Dav3whit3** [comment]
@brean Thank you very much my man...I can stop headbutting my keyboard now. :3

**Comment by arshadnzr** [comment]
> environment:
>      - PYTHONUNBUFFERED=1


Man , i knew it was an stdout issue. cause there was an error and i got the error.

Explanation on what happend 
Linux outputs two types of log , which is stdout  and stderr . for some reason docker is only printing stdout when run with compose . I guess its a good thing . Compose is used for multiple container managing stuff . and we dont want all the logs to clog up .

**Comment by sorenwacker** [comment]
So, what did this have to do with `PYTHONUNBUFFERED=1`?

**Comment by arshadnzr** [comment]
i think setting PYTHONUNBUFFERED to a non-empty value different from 0 will ensure that the python output i.e. the stdout and stderr streams are sent straight to terminal (e.g. your container log) without being first buffered so that you can see the output of your application (e.g. django logs) in real time.

This also ensures that no partial output is held in a buffer somewhere and never written in case the python application crashes.

note that PYTHONUNBUFFERED has absolutely no influence on the input (i.e. the stdin stream).
