### ISSUE TITLE
compose tell all nodes to pull image work with swarm.

### ISSUE THREAD

**Issue by fanux** [docker/compose#4866]
When I want to run a container on one node in my cluster when cluster doesn't have the image, compose tell swarm to create image result in all nodes to pull image.  Using docker run command don't have this problem.
```
DEBU[1561] HTTP request received                         method=GET uri=/v1.22/containers/json?all=0&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtest%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
DEBU[1561] HTTP request received                         method=GET uri=/v1.22/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtest%22%2C+%22com.docker.compose.service%3Dservice_iat%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
DEBU[1561] HTTP request received                         method=GET uri=/v1.22/images/dev.reg.iflytek.com/test/signal:latest/json
ERRO[1561] HTTP error: No such image: dev.reg.iflytek.com/test/signal:latest  status=404
DEBU[1561] HTTP request received                         method=POST uri=/v1.22/images/create?tag=latest&fromImage=dev.reg.iflytek.com%2Ftest%2Fsignal
```

**Comment by shin-** [comment]
Thank you for the report. I believe this is behaving as expected, as there would otherwise be no way to ensure the container is run on the same node the image was just pulled to.

**Comment by fanux** [comment]
Swarm tell the engine to create container if the engine don't have image, the engine will pull the image.
```
	createResp, err = e.apiClient.ContainerCreate(context.Background(), &dockerConfig.Config, &dockerConfig.HostConfig, &dockerConfig.NetworkingConfig, name)
	e.CheckConnectionErr(err)
	if err != nil {
		// If the error is other than not found, abort immediately.
		if (err != dockerclient.ErrImageNotFound && !engineapi.IsErrImageNotFound(err)) || !pullImage {
			return nil, err
		}
		// Otherwise, try to pull the image...
		if err = e.Pull(config.Image, authConfig); err != nil {
			return nil, err
		}
		// ...And try again.
		createResp, err = e.apiClient.ContainerCreate(context.Background(), &dockerConfig.Config, &dockerConfig.HostConfig, &dockerConfig.NetworkingConfig, name)
		e.CheckConnectionErr(err)
		if err != nil {
			return nil, err
		}
```
The engine will have the image...

**Comment by shin-** [comment]
I believe this is a recent addition to Swarm that we couldn't rely on in earlier versions. I'll need to check exactly when this was added and who might be affected by a potential change here. I'll update when I have more info.

**Comment by smallfish** [comment]
Inside a cluster, pull all nodes (more than 100+), causing the network bandwidth to be filled, some image is very big...

Temporarily modified file `compose/service.py`, annotated two lines:

1. create container don't to pull image, by scheduling to decide which machine to run [compose/service.py#L281](https://github.com/docker/compose/blob/master/compose/service.py#L281)

```
# self.ensure_image_exists()
```

2. hash config remove image id [compose/service.py#L600](https://github.com/docker/compose/blob/master/compose/service.py#L600)

```
# 'image_id': self.image()['Id'],
```

It works ok in single node and swarm mode.
