### ISSUE TITLE
Document ulimits option for Docker Compose

### ISSUE THREAD

**Issue by gasparch** [docker/compose#4867]
Documentation of Docker Compose about ulimits section is very terse. In other hand turns out Docker-Compose/Docker pass any option specified in that section to [setrlimit](https://linux.die.net/man/2/setrlimit) and any of `RLIMIT_*` options can be used.

Please include at least two use case examples which are commonly asked on stackoverflow or similar sites: 

- maximum number of open file descriptors per process (`nofile`)
- maximum limit on memory used by single process inside container (`as`)

**Comment by shin-** [comment]
Thanks! Please suggest those additions or submit a PR on our [docs repo](https://github.com/docker/docker.github.io).
