### ISSUE TITLE
Wrong Image build with Option -f

### ISSUE THREAD

**Issue by BorntraegerMarc** [docker/compose#4868]
When I define multiple `docker-compose` files with the `-f` option then the last container gets build from the wrong Image.

I have the file `Frontend/docker-compose.yml` and `Backend/.docker/docker-compose.yml`

How to reproduce:
1. cd into ./Frontend
2. execute `docker-compose -f ..\Backend\.docker\docker-compose.yml -f docker-compose.yml up --build`

See output:

```
PS D:\projects\upwork-nginx\Frontend> docker-compose -f ..\Backend\.docker\docker-compose.yml -f docker-compose.yml up --build
Building komed-app
Step 1/9 : FROM node:6.9.2-alpine
 ---> e1f21a19c1b5
Step 2/9 : RUN addgroup -g 997 -S app && adduser -G app -u 998 -D -S app
 ---> Using cache
 ---> 46fef21e2a7d
Step 3/9 : ENV HOME /home/app
 ---> Using cache
 ---> 46a46cbe621e
Step 4/9 : RUN mkdir -p $HOME
 ---> Using cache
 ---> 5d718a3b719e
Step 5/9 : RUN chown -R app:app $HOME
 ---> Using cache
 ---> 7dbd6f97f33c
Step 6/9 : WORKDIR $HOME/
 ---> Using cache
 ---> 7cec6bcf2d97
Step 7/9 : VOLUME /home/app/uploads
 ---> Using cache
 ---> ac01f9b4ce97
Step 8/9 : EXPOSE 8000
 ---> Using cache
 ---> ac588bca9b5e
Step 9/9 : CMD node app.js
 ---> Using cache
 ---> 7adf44d29515
Successfully built 7adf44d29515
Building komed-nginx
Step 1/2 : FROM jwilder/nginx-proxy:alpine
 ---> f742875b8ffb
Step 2/2 : COPY proxy.conf /etc/nginx/proxy.conf
 ---> Using cache
 ---> 41ec29715054
Successfully built 41ec29715054
Building komed-web-nginx
Step 1/9 : FROM node:6.9.2-alpine
```

Most important is the last line: `Step 1/9 : FROM node:6.9.2-alpine`. This one should be actually `Step 1/9 : FROM nginx:1.13.0-alpine`

**Comment by BorntraegerMarc** [comment]
See whole source code here: https://drive.google.com/open?id=0BzNZcEjcOdSiTVhnd2EwaUwyc2s

Or for reference
Frontend/docker-compose.yml:
```
version: '2.0'

services:
  komed-web-nginx:
    image: borntraegermarc/komed-web-nginx
    container_name: komed-web-nginx
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "5002:80"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
```

Backend/.docker/docker-compose.yml:
```
version: '2.0'

services:
  komed-nginx:
    image: borntraegermarc/komed-nginx
    container_name: komed-nginx
    build:
      context: ../
      dockerfile: Dockerfile.nginx
    ports:
      - "5001:80"
      - "443:443"
    depends_on:
      - komed-app
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000

  komed-app:
    image: borntraegermarc/komed-app
    container_name: komed-app
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - komed-mongo
    volumes:
      - ../:/home/app
      - ../uploads:/home/app/uploads
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PROTO=http   # should be http even if you use https to the proxy, because node.js uses http!
      - APP_ENV=dev # dev / demo / production
      - MONGO_HOST=komed-mongo
      - MONGO_DATABASE=komed-health
      - PORT=8000
      - BASE_URL=http://localhost:5001
      #PATIENT ROOM RELATED CONFIG
      - TEAM_NAME=Komed Health DEVTEAM
      - ADMIN_EMAIL=
      - NEW_PATIENT_ROOM_CREATES_USER=true #true if new patient room should create also a new user
      - NEW_PATIENT_ROOM_IS_PRIVATE=true #true/false if patient room is private/public by default
      - MAILGUN_DOMAIN=mg.komed-health.com
      - MAILGUN_SEC_KEY=key-6aa29aa2e95b16ca69b09ee4bc787496
      - MAILGUN_SENDER_NAME=komed
      #IOS Push notification config (from Apple developer account)
      - KOMED_IOS_APN_PROD_CERT=misc/ssl/APNsAuthKey_29JYZHG652.p8
      - KOMED_IOS_APN_KID=29JYZHG652
      - KOMED_IOS_TEAM_ID=6UV97C79YF
      - LOG_LEVEL=silly # error: 0, warn: 1, info: 2, verbose: 3, debug: 4, silly: 5

  komed-mongo:
    container_name: komed-mongo
    image: mongo:3.4.2
    ports:
      - "27017:27017"
```

**Comment by shin-** [comment]
Thanks for the thorough report. I'm a bit swamped at the moment but I'll take a closer look ASAP.

**Comment by shin-** [comment]
Okay, taking a closer look at this now, seems like you're the victim of a common Compose pitfall. When merging multiple Compose files, the first file in the list becomes the point of reference for all relative paths in the resulting configuration. This is something we explain (albeit tersely) [in the documentation here](https://docs.docker.com/compose/extends/#understanding-multiple-compose-files)

> When you use multiple configuration files, you must make sure all paths in the files are relative to the base Compose file (the first Compose file specified with -f). This is required because override files need not be valid Compose files. Override files can contain small fragments of configuration. Tracking which fragment of a service is relative to which path is difficult and confusing, so to keep paths easier to understand, all paths must be defined relative to the base file.

HTH

**Comment by BorntraegerMarc** [comment]
Ah OK, I understand. Maybe this could be a new feature?

**Comment by shin-** [comment]
To be honest, there's multiple issues with changing this behavior.

1. It's pretty crucial to the way Compose processes configuration as a whole
2. It would be a breaking change for people relying on the current behavior
3. As pointed out in the doc snippet above, working with multiple base folders would probably make things exponentially confusing when dealing with several files.

Unless we end up rewriting the whole project from scratch, that's not something I think we'll be working on in the foreseeable future.

**Comment by BorntraegerMarc** [comment]
Alright, thanks for the answer :)

**Comment by BorntraegerMarc** [comment]
Just one more question: how come the relative path charges the image that is being build? Seems to be that the volumes, etc. should be wrong (which makes sense) but the image should stay the same as defined in the docker compose file. No?
