### ISSUE TITLE
##[error]Version in "./docker-compose.yml" is unsupported. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

### ISSUE THREAD

**Issue by milla** [docker/compose#4872]
I have a docker related issue raised in [vsts-docker repo](https://github.com/Microsoft/vsts-docker/issues/46), as it's happened in VSTS-Release. Here I'm duplicating it to see if this's an issue related to docker, not vsts.

**Comment by shin-** [comment]
This has been answered on the other thread already, but for people who run into this issue in the future: if you see this message, your version of Compose is most likely too old and you need to upgrade it.
