### ISSUE TITLE
Docker-compose up DOCKER-ISOLATION problem

### ISSUE THREAD

**Issue by giper45** [docker/compose#4873]
Hello, from the last docker update I cannot start my compose files more... when I give docker-compose up it gives the following error: 

``` 
unable to insert jump to DOCKER-ISOLATION rule in FORWARD chain: 
 (iptables failed: iptables --wait -I FORWARD -j DOCKER-ISOLATION: iptables v1.6.0: 
Couldn't load target `DOCKER-ISOLATION':No such file or directory
```
docker-compose version 1.11.2, build dfed245
Docker version 17.03.1-ce, build c6d412e
MacOS Sierra 
Is there some configuration to do? Docker run-cli works correctly, only docker-compose gives this, but I often use this....
Thanks in advance

**Comment by giper45** [comment]
Sorry, Now I just discover that also the following cli command doesn't work: 
```
 docker network create --driver bridge mynet1
Error response from daemon: unable to insert jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -I FORWARD -j DOCKER-ISOLATION: iptables v1.6.0: Couldn't load target `DOCKER-ISOLATION':No such file or directory

```
So it is a docker configuration problem, I think ... Do you have some advices anyway?

**Comment by giper45** [comment]
I reinstall all docker and the problem is resolved! Sorry for my question but I was in panic :)!

**Comment by n-a-t-e** [comment]
I had the same issue on Ubuntu and was able to fix by restarting Docker-
`sudo systemctl restart docker`

Ubuntu 18.04.5 LTS / Docker version 19.03.12, build 48a66213fe

**Comment by mnlx** [comment]
> `sudo systemctl restart docker`

Thank you. This worked for me.

**Comment by unsalkorkmaz** [comment]
Any solution for this?
restarting whole docker for this doesnt make sense

**Comment by kanazir** [comment]
> Any solution for this? restarting whole docker for this doesnt make sense

Yes, but it worked for me, too.

**Comment by DoctorDinosaur** [comment]
> Any solution for this? restarting whole docker for this doesnt make sense

++

Restarting docker works but it's far from ideal. I'm using CSF, maybe thats the issue.
