### ISSUE TITLE
requests minimum version

### ISSUE THREAD

**Issue by carlwgeorge** [docker/compose#4884]
I'm working on packaging docker-compose 1.9 for RHEL/CentOS 7 (via EPEL).  The system version of python-requests is 2.6.0, but docker-compose has a [minimum version of 2.6.1](https://github.com/docker/compose/blob/1.9.0/setup.py#L34).  The [commit setting that version](https://github.com/docker/compose/commit/d17c4d27fa5259fb8d853ccedc82d28fd199ff8f) doesn't make specific mention of why that exact version was necessary.  Can anyone shed any light on specific features and/or bug fixes that exist in 2.6.1 that are missing from 2.6.0?  Perhaps 2.6.0 will work, and if a specific feature/bug fix is known then I can request Red Hat backport it to their package.

**Comment by shin-** [comment]
Digging through the PRs, https://github.com/requests/requests/issues/2465 is the issue that prevents us from using `requests < 2.6.1`, since we package the binaries using pyinstaller.

**Comment by carlwgeorge** [comment]
Thanks for the info @shin-.  It sounds like that bug won't be relevant for my use case since [Red Hat un-bundles requests' vendored dependencies](https://git.centos.org/blob/rpms!python-requests.git/211cd5d89a96810d54cd8a070c8c6f9e53ad5a98/SPECS!python-requests.spec#L77) into their own packages.  For my purposes of a docker-compose 1.9 RPM, I'll locally patch the setup.py file to accept the system copy of requests 2.6.0.

**Comment by carlwgeorge** [comment]
Thanks for the assist on this.  docker-compose 1.9 is now available in the EPEL repository for easy installation for RHEL/CentOS 7 users.  If at some point in the future Red Hat updates to SDK 2 then I'll take care of updating docker-compose to a newer version.
