### ISSUE TITLE
docker-compose down only removes one of the default networks

### ISSUE THREAD

**Issue by larsnystrom** [docker/compose#4890]
Due to a race condition when creating networks (see https://github.com/moby/moby/issues/20648) running `docker-compose up` in parallell sometimes creates two default networks with the same name. Running `docker-compose down` only removes one of them.

**Comment by shin-** [comment]
I believe that bug is at the engine/API level - all we do is issue a DELETE for `net_name`. That operation should arguably remove all networks with that name.

**Comment by larsnystrom** [comment]
So should I create an issue somewhere else (where?) or could you forward the issue to wherever it belongs? 😊

**Comment by shin-** [comment]
Yes, if you don't mind, can you create an issue on `moby/moby` with a link to this ticket?

**Comment by shin-** [comment]
I believe this has been addressed at the engine level. Feel free to update if you find that's not the case.
