### ISSUE TITLE
Each output line for `run` is preppended with spaces

### ISSUE THREAD

**Issue by budnik** [docker/compose#4901]
I had recently reinstalled Ubuntu 17.04, and having issues with `docker-compose run`:
![selection_001](https://user-images.githubusercontent.com/1160699/26875384-3ba36cf0-4b8a-11e7-9b8b-93b92be25fa0.png)

I have tried different versions of compose from 1.10 to 1.14-rc1
Here's output of `docker info`:

> Containers: 44
 Running: 4
 Paused: 0
 Stopped: 40
Images: 16
Server Version: 17.06.0-ce-rc1
Storage Driver: btrfs
 Build Version: Btrfs v4.9.1
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 992a5be178a62e026f4069f443c6164912adbf09
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-22-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.702GiB
Name: dmytro-XPS-13-9343
ID: HFVZ:FMAO:RFPH:QYN3:JI5Z:H6NK:MICA:5SHS:D2QP:FSW7:T7HX:NTI5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by budnik** [comment]
I acknowledge that problem is probably caused not by `docker-compose` itself but my environment. But I have no idea how can I debug it and find root cause. And this issue may benefit other users as well.

**Comment by shin-** [comment]
Same issue if you use the `-T` flag? And conversely, do you see the issue with `docker run` if you use the `-t` flag?

**Comment by budnik** [comment]
No issues with `docker-compose run -T` and `docker run -t` :+1:

For me it's still mysterious why.

**Comment by shin-** [comment]
See #4910 - it'll be fixed in the upcoming Engine RC3 :)
