### ISSUE TITLE
Output the equivalent docker command in verbose/debug mode

### ISSUE THREAD

**Issue by aug-riedinger** [docker/compose#4903]
I am an extended user of `docker-compose` but I really suck at `docker`-only.

Correct me if I'm wrong, but from the usage I have had, all the `docker-compose` commands correspond to one/several `docker` commands, don't they?

Eg. `docker-compose run web /bin/bash` => `docker exec project_name_web /bin/bash -it`

Wouldn't it make sense to have in the verbose/debug mode the possibility to output the equivalent docker command to increase user awareness of how the `docker` cli works?

Cheers

**Comment by shin-** [comment]
Actually, the `docker-compose` sub-commands are usually related to the `docker` sub-command of the same name, so `run` is `run`, `ps` is `ps`, etc. Other commands with no equivalent in `docker` are a more complex combination of operations (`up` and `down` are in this category), or do not interact with the engine at all (`config`)

Note that compose never calls the `docker` CLI, and instead interacts with the engine using the [engine API](https://docs.docker.com/engine/api/)

**Comment by aug-riedinger** [comment]
Thanks for your answer.

I expected `docker-compose` to call the `docker` CLI indeed.

So I guess what I'm suggesting here could be done as an exercice to master docker CLI. :smile:

**Comment by aaronbeall** [comment]
Is there any documentation on what all the `--verbose` output means? In particular I'm interested if I can make use of this: `compose.cli.verbose_proxy.proxy_callable: docker pull -> <generator object _stream_helper at 0x10b7a1820>` to track the download progress programmatically?
