### ISSUE TITLE
Unable to fig build a github repo / works with docker build

### ISSUE THREAD

**Issue by techniq** [docker/compose#491]
Using `docker build` I can pull and build an image directly from Github, for example: 
```docker build -t java https://github.com/StrictlyBusiness/docker-java8.git```

When I try to do the same using `fig build` and the following `fig.yml`:
```
webapp:
  build: https://github.com/StrictlyBusiness/docker-java8.git
```

it shows `Building webapp...` then after ~40 seconds, it shows just a single closing bracket `)`.  For example:
```
$ fig build
Building webapp...
)
```

I haven't found a way to get any more details on what's happening behind the scenes in fig to know why it's failing.

**Comment by dnephin** [comment]
This is fixed by #1372 (which is still open)
