### ISSUE TITLE
Mention SHA 256 sum in compose/releases

### ISSUE THREAD

**Issue by shatil** [docker/compose#4911]
Currently, the download link is provided but the document doesn't mention any SHA sum. Could you please mention what the hash ought to be, going forward, so I have a frame of reference?

E.g., for https://github.com/docker/compose/releases/download/1.13.0/docker-compose-Linux-x86_64 I get `0d8af4d3336b0b41361c06ff213be5c42e2247beb746dbc597803e862af127e8`, which appears to run.

**Comment by shin-** [comment]
I started doing this with 1.17.0 RC1 (this particular release uses SHA-1 sums, but I'll move forward with SHA-256 for future releases)
