### ISSUE TITLE
docker-compose process constantly takes ~15% CPU

### ISSUE THREAD

**Issue by vmalloc** [docker/compose#4919]
I'm running my project (Backslash, docker-compose file here: https://github.com/getslash/backslash/blob/develop/docker/docker-compose.yml) using `docker-compose up`. Apart from the actual processes running within docker, which should be taking actual CPU, I see the docker-compose process itself constantly taking around 15% of CPU (![example screenshot](https://i.imgur.com/W3gr7Pz.png)). Is that the expected behavior?

Running docker-compose 1.13.0 with:
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by shin-** [comment]
15% of how much? Processing and displaying logs while maintaining concurrent connections to the Docker Engine can be somewhat consuming depending on the volume of data you're dealing with.

If it's a concern, you could use `docker-compose up -d` which will exit after starting the containers.

**Comment by vmalloc** [comment]
@shin- sounds reasonable. Thanks! I'll try it

**Comment by shin-** [comment]
I'm closing the issue, but let me know if there's still questions or concerns on this.
