### ISSUE TITLE
"docker-compose up" stops (deletes!) other scaled services

### ISSUE THREAD

**Issue by jamshid** [docker/compose#4923]
This is a followup to https://github.com/docker/compose/issues/4803.

Using `docker-compose version 1.14.0-rc2, build 24dae73` I see that `docker-compose up -d foo` also stops and removes containers for another (dependent) `bar` services that had been scaled with `docker-compose up -d --scale bar=3`. 

Even using `--no-deps` does not help.

That seems undesirable, and more importantly, it is a *breaking* change in behavior.

**Comment by shin-** [comment]
The breaking change [was announced](https://github.com/docker/compose/blob/master/CHANGELOG.md#breaking-changes) in the 1.13.0 changelog.

Dependent services being reset when calling `up` again I think makes sense in terms of behavior now that `scale` is (implicitly or explicitly) part of a service's configuration.

I agree that it shouldn't happen if `--no-deps` is used.

**Comment by shin-** [comment]
`--no-deps` works as advertised for me though:

```
$ docker-compose up -d --scale bar=3 --scale baz=2
Creating network "repro4923_default" with the default driver
Creating repro4923_baz_1 ... 
Creating repro4923_baz_2 ... 
Creating repro4923_baz_1 ... done
Creating repro4923_baz_2 ... done
Creating repro4923_bar_1 ... 
Creating repro4923_bar_2 ... 
Creating repro4923_bar_3 ... 
Creating repro4923_bar_1 ... done
Creating repro4923_bar_2 ... done
Creating repro4923_bar_3 ... done
Creating repro4923_foo_1 ... 
Creating repro4923_foo_1 ... done

$ docker-compose ps
     Name         Command    State   Ports 
------------------------------------------
repro4923_bar_1   sleep 33   Up            
repro4923_bar_2   sleep 33   Up            
repro4923_bar_3   sleep 33   Up            
repro4923_baz_1   sleep 66   Up            
repro4923_baz_2   sleep 66   Up            
repro4923_foo_1   sleep 99   Up            

$ docker-compose up --no-deps -d foo
repro4923_foo_1 is up-to-date

$ nano docker-compose.yml # edit foo config 
$ docker-compose up --no-deps -d foo
Recreating repro4923_foo_1 ... 
Recreating repro4923_foo_1 ... done

$ docker-compose ps
     Name         Command    State    Ports 
-------------------------------------------
repro4923_bar_1   sleep 33   Exit 0         
repro4923_bar_2   sleep 33   Exit 0         
repro4923_bar_3   sleep 33   Exit 0         
repro4923_baz_1   sleep 66   Up             
repro4923_baz_2   sleep 66   Up             
repro4923_foo_1   sleep 98   Up             
```

**Comment by jamshid** [comment]
Sorry, closing. Yes, `--no-deps` seems to work. I forgot that was an intended change in 1.13.

- `scale` is no longer a `docker-compose.yml` parameter
- when scaling a service from command-line you must scale all (dependent?) services at the same time
   `docker-compose up -d --scale foo=3 --scale bar=2`
- Use `--no-deps` to avoid that
- this all changes with Swarm -- Services and Replicas
https://docs.docker.com/glossary/?term=scale

**Comment by jamshid** [comment]
I still can't believe you can no longer run `docker-compose up -d` to start a project that had scaled services. Docker knows what a service was last scaled to, why do I have to pass all that back in?

**Comment by jamshid** [comment]
I thought `--no-deps` caused compose to only affect the explicitly mentioned service, but I saw this command kill/recreate all other services. Sorry didn't try to repro, I'll see if see it next time I'm running all-latest docker.
```
$ docker-compose up --no-deps --scale foo=3
```
```
$ docker-compose --version
docker-compose version 1.20.0-rc2, build 8c4af54

$ docker version
Client:
 Version:	18.03.0-ce-rc4
 API version:	1.35 (downgraded from 1.37)
 Go version:	go1.9.4
 Git commit:	fbedb97
 Built:	Thu Mar 15 07:33:28 2018
 OS/Arch:	darwin/amd64
 Experimental:	true
 Orchestrator:	swarm

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:16:13 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by shin-** [comment]
@jamshid The proper command to do what you're trying to do would be `docker-compose up --no-deps --scale foo=3 foo`.
