### ISSUE TITLE
Want a way to specify a dockerfile outside the context in the docker-compose dockerfile directive

### ISSUE THREAD

**Issue by bitdancer** [docker/compose#4926]
I've read several discussions about the security reasons why paths outside the context are not permitted.  OK, but it seems to me that that should not apply to the dockerfile directive.  After all, you can specify a dockerfile outside the context when using the docker build command itself, using -f.  I'd like to be able to do the same thing in docker-compose, either relative to the context or relative to the dockerfile-compose.yml file.  My goal is to put all the dockerfile-specific config in a subdirectory next to my context directory.  I can do that with everything except the dockerfile itself.

**Comment by shin-** [comment]
It already works?
```
$ cat docker-compose.yml 
version: '2.2'
services:
  foo:
    build:
      context: .
      dockerfile: /opt/Dockerfile
    command: sleep 3

$ cat /opt/Dockerfile 
FROM alpine:3.5
RUN mkdir /test

$ docker-compose build --no-cache
Building foo
Step 1/2 : FROM alpine:3.5
 ---> 02674b9cb179
Step 2/2 : RUN mkdir /test
 ---> Running in d5601b4cad02
 ---> dd9cf82ed85a
Removing intermediate container d5601b4cad02
Successfully built dd9cf82ed85a
Successfully tagged repro4926_foo:latest
```

**Comment by bitdancer** [comment]
That's an absolute path.  Given that this is checked in to a repo and I don't know where it will be checked out, I can't practically use an absolute path.  How would I specify it using a relative path (as I said, I don't care if it is relative to the context or relative to the docker-compose.yml file)?

**Comment by shin-** [comment]
```
$ docker build -f ../../../../../../opt/Dockerfile .
unable to prepare context: the Dockerfile (/opt/Dockerfile) must be within the build context
```

Not a Compose issue I'm afraid.

**Comment by bitdancer** [comment]
You are right.  I could have sworn that I tested that, but obviously whatever I thought I did wasn't a proper test, because I see that error myself trying it again.

**Comment by theimpostor** [comment]
FWIW it is possible to use a Dockerfile outside the of the build context:

`docker build -f - . < ../Dockerfile`

It would be great if docker-compose could support this as well.

**Comment by tinchou** [comment]
It seems that you can use `$PWD`, but it would be best to be able to use a relative path:

```yml
version: '2'
services:
  service:
    build:
      context: ../path/to/service
      dockerfile: $PWD/Dockerfile-for-service
```

**Comment by thaJeztah** [comment]
Docker 18.03 will add support for Dockerfile outside of the context directory; https://github.com/docker/cli/pull/886

@shin- not sure if changes are needed in Docker Compose for that?

**Comment by shin-** [comment]
@thaJeztah Thanks! This will require some changes to support it both in the SDK and in Compose, but I'll put it on the list.

**Comment by jbdhacf** [comment]
cd ./.. wont work?

**Comment by masaeedu** [comment]
@shin- How is this supposed to work? I'm trying to use:

```
version: '3'
services:
  xyz:
    image: xyz
    build:
      context: .
      dockerfile: dockerfiles/api.Dockerfile
```

with the files `docker-compose.yml` and `dockerfiles/api.Dockerfile`, but I get:

```
ERROR: Cannot locate specified Dockerfile: dockerfiles\api.Dockerfile
```

Trying to build directly from the docker CLI using `docker build -t test -f .\dockerfiles\api.Dockerfile` works fine.

**Comment by kferrone** [comment]
yo yo I have it working as you want, check it out below. I put Dockerfile and docker-compose.yml in a dir called `builder` then changed the context for docker-compose. 

At top level of project make a file called `.env` and add the following:

```
COMPOSE_FILE=./builder/docker-compose.yml
```

Don't change anything in the Dockerfile, it's good to go. 

Now make your compose file like so:

```
version: "3"
services:
  myapp:
    build: 
      context: ../
      dockerfile: ./builder/Dockerfile
```

Now at the root of the project, simply run:
```
docker-compose build
```

Voila!

**Comment by jmoz** [comment]
Why is a relative path ok for `context` yet fails for `dockerfile`?

**Comment by kferrone** [comment]
@jmoz 

The Dockerfile is relative to the context. Dockerfile path does not need to be a relative simply because the relative part of the path is defined in the context.

**Comment by armdev** [comment]
This is working
version: '2'
services:   
  eurekanode:
    mem_limit: 256m
    image: eurekanode    
    build:
     context: .
     dockerfile: eurekanode/docker/Dockerfile     
    container_name: eurekanode

[FROM openjdk:11-jdk-slim
VOLUME /tmp
ADD  eurekanode/target/eurekanode.jar /app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Xmx128m", "-Xss256m", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
EXPOSE 8761](url)

**Comment by KalanaDananjaya** [comment]
> It seems that you can use `$PWD`, but it would be best to be able to use a relative path:
> 
> ```yaml
> version: '2'
> services:
>   service:
>     build:
>       context: ../path/to/service
>       dockerfile: $PWD/Dockerfile-for-service
> ```

I recently came across this issue and your solution was a life saver  @colltoaction

**Comment by dimadeveatii** [comment]
The `$PWD` works great on linux, but fails on Windows (as `$PWD` is just empty in Windows).  
For those looking for a cross-platform solution, use a default value:
```yml
version: '2'
services:
  service:
    build:
      context: ../path/to/service
      dockerfile: ${PWD:-.}/Dockerfile-for-service
```

**Comment by calebickler** [comment]
`$PWD` works, does a path relative to your docker-compose.yml file work yet? Is there an issue for that?
