### ISSUE TITLE
Need an official docker container that supports docker-compose v3

### ISSUE THREAD

**Issue by psankar** [docker/compose#4936]
We currently do not have a working docker-compose container image that supports docker-compose v3 API. 

The latest docker-compose build on the dockerhub is failing: 
https://hub.docker.com/r/docker/compose/
https://jenkins.dockerproject.org/job/Compose%20Master/

**Comment by shin-** [comment]
`docker/compose:1.14.0-rc2` isn't working?

**Comment by psankar** [comment]
Okay. This works fine. I was deceived by the failed build status on the dockerhub page. Also there was a build failure in my gitlab ci, due to a docker-compose issue and I confused both of them.
