### ISSUE TITLE
Add labels in docker-compose run

### ISSUE THREAD

**Issue by Yajo** [docker/compose#4937]
Currently `docker-compose run` has a bunch of flags you can use to override some configurations from the ones defined in the corresponding `docker-compose.yaml` file.

There's still the lack of a `-l` or `--label` parameter. This is way useful, I have a use case:

You have a host where there is a [traefik](http://traefik.io/) inverse proxy and your production app is running. You boot a sidekick container that needs to keep on doing things in the background, so you run `docker-compose run --rm app backgroundjob`. At some point, you need to restart the production app, so you `docker-compose restart app`, and then suddenly the proxy returns a 404 status. That's because Traefik lost notion of your production container for a second, and then it routed things to the `myproject_app_run_1` container instead. When the old production container is restarted, it has no longer routing.

If we were able to `docker-compose run --rm -l traefik.enable=false app backgroundjob`, this would never happen.

I guess there could be other possible similar scenarios out there.

**Comment by smiller123** [comment]
Hello. I'm currently an undergraduate student taking a course on virtualization. For our final project, my group of three is required to find an open-source issue to work on in our last three weeks. This issue sounded manageable for the time frame and our skill level. Is anybody already working on this and does this sound reasonable?
Thank you

**Comment by ahmedaljazzar** [comment]
Hello, is this still available? I ran `docker-compose up --label` but it doesn't seem that `docker-compose==1.21.2` still has this option

**Comment by smiller123** [comment]
This is for `docker-compose run`, not `docker-compose up`. Try that?
