### ISSUE TITLE
"fig run" blocks stdin when attaching through charles proxy

### ISSUE THREAD

**Issue by stephenemslie** [docker/compose#494]
1. Start [Charles Proxy](www.charlesproxy.com)
2. Try to attach to a container

 ```
$ cat fig.yml
busybox:
    image: busybox
$ fig run busybox /bin/sh
```

Fig then appears to freeze up, but attaching to the container with `docker attach` works fine, and any output generated as a result will appear in the fig output too. It looks like having Charles open is somehow causing fig to block stdin.

Here is a gist with the `POST /containers/.../attach` requests: https://gist.github.com/anonymous/acd7aa634ce668f1f93b

**Comment by dnephin** [comment]
Not sure what to do about this issue. Were you able to get it working?

**Comment by dnephin** [comment]
No response from OP, so closing this issue.

It's possible that Charles Proxy assumes HTTP, but `attach` streams bytes after the initial HTTP request starts.
