### ISSUE TITLE
Add support for --health-start-period

### ISSUE THREAD

**Issue by electrofelix** [docker/compose#4946]
Docker CE 17.06 will contain support for --health-start-period, compose should add a matching capability and updates to the corresponding v3.x & v2.x compose formats to support this option.

Originally mentioned in docker/cli#116

**Comment by shin-** [comment]
Depends on https://github.com/docker/docker-py/pull/1620

**Comment by vfreex** [comment]
Hello. Since docker/docker-py#1620 has been merged, what is the plan for this feature?
