### ISSUE TITLE
Change default subnet from 172.16.0.0?

### ISSUE THREAD

**Issue by ultrakamish** [docker/compose#4947]
The problem is: even if i added {"bip": "192.168.100.1/24"} in /etc/docker/daemon.json and it changes docker network "bridge", _docker-compose up_ still creates networks in **172.27.0.0/16**!

I thought, there was some global config file for docker-compose, but i couldn't find it. 

Is there any way to change this behavior? Except describing custom networks in docker-compose.yml or attaching containers to external network "bridge" (previously i used this way, but _network_mode: bridge_ doen't work with _networks: default: aliases: ..._ for the same service)

**Comment by ultrakamish** [comment]
OK, i'm not the first who faced this problem, so there is no need in this post.

**Comment by dvarum12** [comment]
I am facing the same problem right now and would like to know if you ever found a solution
