### ISSUE TITLE
Docs: volumes_from has no direct replacement in v3

### ISSUE THREAD

**Issue by borekb** [docker/compose#4959]
From https://docs.docker.com/compose/compose-file/#volumes:

> Note: The top-level volumes option defines a named volume and references it from each service’s volumes list. This replaces volumes_from in earlier versions of the Compose file format.

This is not true, named volumes are not a replacement of `volumes_from` in v2. Maybe some subset of use cases but it's there are scenarios which v3 does not support and it would be good to be upfront about it in the docs.

Examples: https://github.com/docker/compose/issues/4675, https://stackoverflow.com/a/44744861/21728.

**Comment by shin-** [comment]
Thank you! Please report docs issues on the [docs repo](https://github.com/docker/docker.github.io/)
