### ISSUE TITLE
docker-compose pull output

### ISSUE THREAD

**Issue by Niondir** [docker/compose#4963]
I'm confused every time I do `docker-compose up -d`

```
postgres is up-to-date
nginx is up-to-date
Recreating backend
dashboard is up-to-date
```

The container name is always in front, just for "recreating" it's at the end. I wish you could unify this to make spotting what was recreated and what is up-to-date a bit easier.

**Comment by nashley** [comment]
[service.py](https://github.com/docker/compose/blob/5c5a40c3375693cadaab6d1449e13f4a4bda6047/compose/service.py#L510) looks like the relevant file.

How does `%s is out-of-date. Recreating...` sound?

**Comment by nashley** [comment]
Or perhaps `%s is being recreated`:
```
postgres is up-to-date
nginx is up-to-date
backend is being recreated
dashboard is up-to-date
```

**Comment by Niondir** [comment]
I like all of them. Maybe the first proposal is best, since the line gets a bit longer. You usually want to focus on the recreated stuff I guess.

**Comment by nashley** [comment]
@shin- I made a (very simple) PR. Let me know if you think the message should be changed or if I missed a part of the PR process.

**Comment by ijc** [comment]
Closing as discussed in #5002. Thanks.
