### ISSUE TITLE
Support for symbolic link to the docker-compose YAML file (on Windows)

### ISSUE THREAD

**Issue by YannRobert** [docker/compose#4979]
On GNU/Linux, docker-compose does support when the ```docker-compose.yml``` file is a symbolic link to some other regular file.

Suppose we have a regular (and valid) YAML file ```docker-compose-something.yml``` and want to have a symbolic link on it. Then use the symbolic link.

```
# ln -s docker-compose-something.yml docker-compose.yml
# docker-compose pull
```

But on Windows 10, docker-compose does not support this case.

```
# ln -s docker-compose-something.yml docker-compose.yml
# docker-compose pull
yaml.reader.ReaderError: 'utf8' codec can't decode byte #xff: invalid start byte
  in ".\docker-compose.yml", position 10
```

It would help to have the same behavior on Windows than on Linux.
So that a team with developers on Linux and developers on Windows can work the same way.

Out of context : I know we can use ```docker-compose -f docker-compose-something.yml``` as a workaround, but when a project has multiple docker-compose YAML files, and one of them is proposed as a default in source control, symbolic link is handy so that we don't have to use "-f" when we want the default.

**Comment by aronahl** [comment]
Using docker-compose 1.16.0-rc2 on windows with Git BASH, the symbolic links appear to be accepted the same way as with Linux or MacOS.

**Comment by ijc** [comment]
Support or not for symbolic links is an OS level issue, not something which each application should need to deal with or be aware of. I appreciate that the support for symlinks under Windows has been something which is inconsistent and dependent on the specific environment in use (cmd.exe vs wsl vs bash.exe etc etc) and that this can lead to confusing behaviours such as seen here but this is not something we are going to address in compose.
