### ISSUE TITLE
Add --json option and send progress for non-TTY

### ISSUE THREAD

**Issue by aaronbeall** [docker/compose#4980]
I've been working on a NodeJS project that invokes `docker-compose` as a child process. The issue I ran into is that progress events [are only output if `isatty=true`](https://github.com/docker/compose/blob/master/compose/progress_stream.py#L12). I might be able to get the output using `pty.js` but the output will be hard to read... what I really want is the event as JSON.

So this request is to add a `--json` option that will format `stdout` as JSON, and include the download progress events.

**Comment by xxxtonixxx** [comment]
I'm interested too! 👍

**Comment by jnovack** [comment]
Do you mean you would like the following events printed to the stdout so you can parse them? (I'm making up a structure without coffee, forgive me.)

```
{ event: { type: download, hash: 019300c8a437, completion: 100, status: "Already exists" } }
{ event: { type: download, hash: 52a47bc43268, completion: 0, status: "Pulling fs layer" } }
{ event: { type: download, hash: 52a47bc43268, completion: 3, status: "Downloading", detail: { downloaded: 4.523, total: 14.82 } } }
{ event: { type: download, hash: 52a47bc43268, completion: 100, status: "Download complete" } }
```

**Comment by xxxtonixxx** [comment]
Yeah, I think something like that would be awesome! 😄

**Comment by aaronbeall** [comment]
Yes, exactly!On Jul 20, 2017 8:43 AM, "Justin J. Novack" <notifications@github.com> wrote:Do you mean you would like the following events printed to the stdout so you can parse them? (I'm making up a structure without coffee, forgive me.)
{ event: { type: download, hash: 019300c8a437, completion: 100, status: "Already exists" } }
{ event: { type: download, hash: 52a47bc43268, completion: 0, status: "Pulling fs layer" } }
{ event: { type: download, hash: 52a47bc43268, completion: 3, status: "Downloading", detail: { downloaded: 4.523, total: 14.82 } } }
{ event: { type: download, hash: 52a47bc43268, completion: 100, status: "Download complete" } }
