### ISSUE TITLE
support file name with 'docker-compose ps'

### ISSUE THREAD

**Issue by diamantn** [docker/compose#4981]
I've been searching to see if this was already opened and didn't find anything.

you cannot type:
`docker-compose -f docker-compose.someName.yml ps`

So you can't use `docker-compose ps` with those containers even though you've used docker-compose to run them.

What am I missing here?

**Comment by shin-** [comment]
What's preventing you from typing it?

**Comment by diamantn** [comment]
nothing. The command is not supported.

**Comment by shin-** [comment]
Works for me. Perhaps you'd like to share the output you're seeing, as well as the version of `docker-compose` you're using.

**Comment by diamantn** [comment]
I've been using version 1.11.1.
Following your response I've tried with 1.14.0.
It worked.
Thank you for your assistance.
