### ISSUE TITLE
ERROR: client version 1.22 is too old

### ISSUE THREAD

**Issue by nikoo56** [docker/compose#4996]
I am getting this errro when I create a new project with Docker support in VS2017. I am using vs2017, Windows container, Windows 10. by the https://github.com/docker/compose/issues/4024 post I have changed the version of Compose file to 2.1 but now I am getting new error as : Creating network with default driver HNS failed with error: The parameter is incorrect.

**Comment by shin-** [comment]
This is a known issue on Docker on Windows, see https://github.com/docker/compose/issues/4482 for more info.

**Comment by nikoo56** [comment]
I already checked this page no help.

**Comment by shin-** [comment]
I see. Unfortunately, as previously stated, this is not a Compose issue and ultimately out of our hands. You might want to follow [this moby/moby issue](https://github.com/moby/moby/issues/30280), and maybe write a post that describes your problem for the Windows engine maintainers.

**Comment by riverar** [comment]
Can you explain why this error is so unhelpful and incorrectly detects/reports client version numbers? Suggest a re-open.
