### ISSUE TITLE
Implement dns_opt in version 3

### ISSUE THREAD

**Issue by ylavoie** [docker/compose#5010]
Even with version 3, dns_opt is still required to pass specific options like `ndots` and get around dns problems

**Comment by shin-** [comment]
Please submit v3 feature requests on the [docker/cli](https://github.com/docker/cli) repo.

**Comment by maciejmatuszak** [comment]
Hi @shin- the docker cli already implements the --dns-opt or --dns-option. The docker-compose dns-opt is in V2 https://docs.docker.com/compose/compose-file/compose-file-v2/#dns_opt but is not V3. What would it take to implement/port it from V2 to V3?

**Comment by shin-** [comment]
The v3 format is controlled and updated on the `docker/cli` repo (as the primary intention of the v3 format is to work with `docker stack deploy`), so it needs to be proposed there first before we can port the change back into the `docker-compose` codebase. For the change to be accepted in `docker/cli`, it would probably require an implementation of the feature for Swarm services (which [seems to exist at the API level](https://docs.docker.com/engine/api/v1.39/#operation/ServiceCreate), so shouldn't be too daunting to add).

**Comment by ps-jay** [comment]
Hi @shin-,

I'm trying to understand what you mean by the "v3 format is controlled and updated on the `docker/cli` repo".

What file(s), should I look at in `docker/cli` to see what is (or should be) supported by compose?

From what I can see, `--dns-option` is already in the `docker run` CLI (see: https://github.com/docker/cli/commit/ebacbb50aec7281467daf59980ccb6d81724c050), but it's not available in compose.

Should we raise an issue in `docker/cli` that `dns_option` is not also available in the v3 format?

**Comment by shin-** [comment]
> Hi @shin-,
> 
> I'm trying to understand what you mean by the "v3 format is controlled and updated on the `docker/cli` repo".
> 
> What file(s), should I look at in `docker/cli` to see what is (or should be) supported by compose?

https://github.com/docker/cli/tree/master/cli/compose/schema/data

> 
> From what I can see, `--dns-option` is already in the `docker run` CLI (see: [docker/cli@ebacbb5](https://github.com/docker/cli/commit/ebacbb50aec7281467daf59980ccb6d81724c050)), but it's not available in compose.
> 
> Should we raise an issue in `docker/cli` that `dns_option` is not also available in the v3 format?

Yes.

**Comment by ps-jay** [comment]
Thanks @shin-,
I've opened an issue in [docker/cli](https://github.com/docker/cli).

**Comment by phyrwork** [comment]
Looks like this has been implemented since 1.27.0

**Comment by ilayarajamurugesan-alation** [comment]
> Looks like this has been implemented since 1.27.0

@phyrwork Don't think this is related to the docker-compose version. The compose file version 3 still doesn't support `dns_opt`: https://docs.docker.com/compose/compose-file/compose-file-v3/
