### ISSUE TITLE
--update-order support in docker-compose

### ISSUE THREAD

**Issue by djalal** [docker/compose#5013]
Hello, 

can't find how to specify the equivalent of `--update-order=start-first` in my docker-compose.yml ? 

Any help appreciated, thanks

**Comment by shin-** [comment]
Can you create an issue on https://github.com/docker/cli/issues ? Since this is a Swarm service option.

**Comment by djalal** [comment]
@shin- could it be a duplicate of https://github.com/moby/moby/issues/32586 ? if not, just tell me and I will open the issue

**Comment by shin-** [comment]
Yeah, looks like it :)
