### ISSUE TITLE
docker -compose up -d mysql displays errors  with laradock 

### ISSUE THREAD

**Issue by digits21** [docker/compose#5015]
Hi Folks ,
I'm new with laradock and after installing i'm having an  error after running this command 
`sudo docker-compose up -d mysql `
and the error is 
`Service 'mysql' failed to build: The command '/bin/sh -c ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone' returned a non-zero code: 1`

What could the problem with the Time zone setting ?
I have checked everywhere and changed the TZ to my Time zone but still having the same issue

**Comment by shin-** [comment]
https://github.com/laradock/laradock
