### ISSUE TITLE
docker-compose scale ignores .env variables set in shell

### ISSUE THREAD

**Issue by rrrrroman** [docker/compose#5017]
I have a `.env` file that defines all my variables and when I run `docker-compose scale thing=X` the container is scaled, but it's not using the correct environment variables. It just reads the `.env` file and ignores any variables I have set in my shell.

```
$ docker-compose -v
docker-compose version 1.11.1, build 7c5d5e4
```

So if I have a `.env` file that looks like this:
```
FOO=BAR
```
and then in my shell I set it to:
```
FOO=BAZ
```
and run the scale command - the containers receive `FOO=BAR` instead of `FOO=BAZ`.

**Comment by shin-** [comment]
Thanks for the report! Do you happen to have a minimal repro case for this?

**Comment by uLan08** [comment]
Happened to stumble upon this bug also.
But actually the main problem is docker .env file not reading new lines properly. 
So I decided to pass the environment variables through the shell instead and remove the `.env` file. I have now a file with contents `export FOO=bar` then I `source file-with-export && docker-compose config` but the values were not passed, they all defaulted to the default empty string.

```
$ docker-compose -v
$ docker-compose version 1.13.0, build 1719ceb
```

**Comment by rrrrroman** [comment]
Sorry, apparently this was a [PEBKAC](https://en.wikipedia.org/wiki/User_error). Everything works as expected.

By default bash variables are not exported to the children of current process, `export` command does that. So instead of:
```
FOO=BAZ
```

I should've used:
```
export FOO=BAZ
```
