### ISSUE TITLE
ipv6 in port mapping?

### ISSUE THREAD

**Issue by c0b** [docker/compose#5020]
https://github.com/moby/moby/issues/34019#issuecomment-314992623

docker run support ipv6 port mapping in the notation of `-p [::1]:3000:3000/tcp`; however docker-compose (version 1.14.0, build c7bdf9e) does not recognize that:

```console
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.my-service.ports is invalid: Invalid port "[::1]:3000:3000/tcp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

**Comment by shin-** [comment]
Support for IPv6 hosts will be in the next release. See #2663

**Comment by christianbur** [comment]
Is the bug still not fixed, because I still get the following error message?
I run powerdns (dns server) in a Container, since port 53 (127.0.0.53:53) is already occupied by systemd-resolve, I only want to bind powerdns to the public ipv4 and ipv6 address.  

ERROR:

> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.pdns-server.ports is invalid: Invalid port "[2a01:4f8:440c:5e94::1]:53:53/tcp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
> services.pdns-server.ports is invalid: Invalid port "[2a01:4f8:440c:5e94::1]:53:53/upd", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

docker-compose.yml

> version: '2.4'
> services:
>     pdns-server:
>       image: cb/pdns-server
>       build: ./Dockerfiles/pdns
>       volumes:
>         - ./conf/pdns/pdns.conf:/etc/powerdns/pdns.conf:ro
>       ports:
>         - "195.201.44.145:53:53/tcp"
>         - "195.201.44.145:53:53/udp"
>         - "[2a01:4f8:440c:5e94::1]:53:53/tcp"
>         - "[2a01:4f8:440c:5e94::1]:53:53/upd"
>         - 127.0.0.1:8053:8053
>       restart: always
>       depends_on:
>         - pdns-db
>       cap_add:
>         - NET_BIND_SERVICE
>       sysctls:
>         - net.ipv6.conf.all.disable_ipv6=0
>       networks:
>         network-pdns:
>           aliases:
>            - pdns-server

**Comment by christianbur** [comment]
cool, it works :-)
