### ISSUE TITLE
Docker compose 3.0 does not tag images pulled from Docker Trusted Registry

### ISSUE THREAD

**Issue by sneibar** [docker/compose#5021]
Docker compose 3.0 does not tag images pulled from Docker Trusted Registry even though [the documentation](https://docs.docker.com/compose/compose-file/#image) states "If the image does not exist, Compose attempts to pull it, unless you have also specified build, in which case it builds it using the specified options and tags it with the specified tag." 

If you deploy a stack, and the image replicates to a swarm worker node that doesn't have the image, it's pulled, deployed, and then the local repository has &lt;none&gt; for the tag as shown below. I recreated this problem with engine 17.03.2-ee-4, and Docker Trusted Registry 2.1.4.

192.168.1.14/ucpadmin/httpd &lt;none&gt; 42302c1a5e9b About an hour ago 251 MB

**Comment by shin-** [comment]
Please report the issue on the [moby/moby](https://github.com/moby/moby) repo.
