### ISSUE TITLE
Option to don't show logs date and time when tailing (for development)

### ISSUE THREAD

**Issue by HosseinAgha** [docker/compose#5023]
When developing on multiple services, date and time strings added to beginning of each line in logs is a bit annoying. Is there a way to disable the date and time when docker tails the logs? I couldn't find this in any of the log drivers documentations. The only option is to add a timestamp to logs.
I opened the issue here because I think it may be a more compose specific problem.

**Comment by edsonmedina** [comment]
Aren't those logs generated by the apps inside the containers?

**Comment by HosseinAgha** [comment]
Yes but the apps don't generate the timestamp attached to the beginning of each log

**Comment by shin-** [comment]
I'm not sure what you're talking about. `docker-compose logs` doesn't attach logs timestamps by default.
```
$ cat docker-compose.yml 
version: '2'
services:
  app:
    image: alpine
    command: sh -c 'while true; do echo 'Hello'; sleep 0.4; done'
$ docker-compose logs -f app
Attaching to testlogs_app_1
app_1  | Hello
app_1  | Hello
app_1  | Hello
app_1  | Hello
app_1  | Hello
app_1  | Hello
app_1  | Hello
app_1  | Hello
app_1  | Hello
app_1  | Hello
...
```

**Comment by HosseinAgha** [comment]
It's strange because using `docker-compose up` I have the following output. but when I run my service outside docker It does not include date and time. I use a ubuntu image as base.

**Comment by HosseinAgha** [comment]
Sorry that was my mistake
