### ISSUE TITLE
Compose V3 supports network=host

### ISSUE THREAD

**Issue by cheyang** [docker/compose#5039]
According to issue [swarm mode + (--net=host)](https://github.com/moby/moby/issues/33896), `docker service create --network=host` is ready in 17.06.
Now we are waiting for the compose v3 to support network: host. Thanks.

**Comment by shin-** [comment]
https://docs.docker.com/compose/compose-file/#network_mode

**Comment by cheyang** [comment]
Before docker 17-06, Network:host is ignored when deploying a stack in swarm mode with a (version 3) Compose file. But after 17-06, the host network is supported in `docker service`. How can we use network host in compose V3?

**Comment by shin-** [comment]
Please redirect `docker stack` related questions or requests to the https://github.com/docker/cli repo :)

**Comment by cheyang** [comment]
I think it should be supported in compose V3 parser.

**Comment by rauschb** [comment]
@shin- why is a question regarding "docker stack" & "compose v3" a docker cli related question? i don't understand that...
@cheyang i also think that the compose v3 parser should support the new "docker service" ability!

**Comment by shin-** [comment]
@rauschb The `docker/cli` repo is literally where the code for `docker stack` lives.

**Comment by rauschb** [comment]
@shin- thx for the info! i haven't known that, learning never stops... :)

**Comment by cheyang** [comment]
@shin- I'm wondering if I run docker-compose with compose V3, can `network: host` work? I thought it does nothing with `docker stack` .

**Comment by mmariani** [comment]
You're supposed to use network_mode, which works ok under compose but not with docker stack: "is ignored when deploying a stack in swarm mode with a (version 3) Compose file."
