### ISSUE TITLE
Cannot determine which port mapping should apply to which network

### ISSUE THREAD

**Issue by corrieb** [docker/compose#5042]
I've been struggling with an issue while trying to document Compose support for a three tier app using two networks in vSphere Integrated Containers. Our documentation really needed improving and as part of that work, I'm putting together guidelines on how to get the best out of both technologies.

The issue I have is that for a container that uses multiple networks, the order in which they're brought up matters. For example, when using a docker client, I would do the following:

```
docker network create internal
docker create -d --name web --net external -p 80 myImage
docker network connect internal web
docker start web
```
In the above example, I'm asking for port 80 to be exposed on the external network. If I flip it around, instead I get a port mapping on the bridge network.

```
docker network create internal
docker create -d --name web --net internal -p 80 myImage
docker network connect external web
docker start web
```
docker-compose seems to always use the same order, regardless of how the compose file is written - creating the container with the internal network and then adding the external network before starting it.

My question is: Is there any way to influence this ordering? The current compose file format leave it somewhat ambiguous - it allows you to expose ports and specify multiple networks, but there's no way to determine which ports are exposed on which networks. 

Any help in resolving this would be appreciated. Thanks!

**Comment by shin-** [comment]
There's currently no way to configure that.

I suppose there's a potential feature here where we can add an  `priority` parameter to the network dicts, i.e.

```yaml
services:
  foo:
    networks:
      bar:
        priority: 1000
      baz:
        priority: 100
...
```

and connect to each in descending order of priority. Would that answer your use-case?

**Comment by corrieb** [comment]
Thanks for responding @shin-. I guess whether or not this is the right answer for docker-compose as a whole is whether or not network order matters in other use-cases. 

I focused in on the network ordering because it's the most obvious current workaround to our problem. The real problem though is the lack of ability to express _which_ network an exposed port is intended for, if that makes sense. If that could be expressed in the compose file format, then compose itself might be able to infer network ordering from that. I think from the docker API standpoint, you can only explicitly expose a port on the first network added.

So does it sort the networks in some way when it decides which one to connect first? I'd be curious to know how it makes that decision.

A more detailed description on our side is here: https://github.com/vmware/vic/issues/5776.

The most obvious workaround would be for us to use `driver_opts` as a means to express what we need. Ours is a clear use-case for an external network and the opacity that comes with that.

**Comment by corrieb** [comment]
I've updated the issue title to more clearly describe the root of the problem

**Comment by rayjohnson** [comment]
With respect to #5261 order only matters for mac_address because network connect does not take mac_address - but it very much should.  So in compose it would seem order matters for mac_address but really compose needs to support mac_address for all networks not just the first one.

**Comment by shin-** [comment]
@rayjohnson https://github.com/moby/moby/issues/34720 would need to happen first

**Comment by zaldaroga** [comment]
Hi, I'm currently an undergraduate student taking a course on virtualization. For our final project, my group of two is required to find open-source issues to work on in our last few weeks. This issue sounded manageable for the time frame and our skill level. Is anybody already working on this and does this sound reasonable?
Thank you

**Comment by zaldaroga** [comment]
I think I've implemented functionality for having a service connect to networks in descending priority, but I'm a little unsure how I should go about adding a test to check it. If anyone has any advice or guidance, I'd really appreciate it. 
Regards,
Zal
