### ISSUE TITLE
Support for specifiy compose file for docker-compose config command.

### ISSUE THREAD

**Issue by AlicanAkkus** [docker/compose#5045]
We could't specifiy compose file for **docker-compose config** command. We will use the more than one compose file in project. When we typing **docker-compose config**, it's use the default docker-compose.yml file.

May be more useful when add the -c options this command for specifiy compose file. Such as below;

> docker-compose config -c docker-stack.yml

**Comment by shin-** [comment]
https://docs.docker.com/compose/reference/overview/

**Comment by AlicanAkkus** [comment]
hi @shin- , why you are closed this issue? At the address you gave, could't answer the above question.

**Comment by shin-** [comment]
`docker-compose -f docker-stack.yml config`

**Comment by AlicanAkkus** [comment]
thank you @shin-
