### ISSUE TITLE
Specify compose file when building via Docker Compose

### ISSUE THREAD

**Issue by isuftin** [docker/compose#5046]
Currently when issuing docker-compose build, there is no way to specify via `-c` or `--compose-file` to have Docker use a specific configuration to build the image. It always uses docker-compose.yml

It would be very nice if we were able to use an alternate compose configuration to perform the build.

**Comment by shin-** [comment]
https://docs.docker.com/compose/reference/overview/

**Comment by alelb22** [comment]
> Currently when issuing docker-compose build, there is no way to specify via `-c` or `--compose-file` to have Docker use a specific configuration to build the image. It always uses docker-compose.yml
> 
> It would be very nice if we were able to use an alternate compose configuration to perform the build.

This is one of the top links that Google shows when searching for this "issue"
The way to do it is:
`docker-compose -f <compose-yaml-file.yml> build` (without the Angle brackets <>)

**Comment by iagarcia** [comment]
Hello, according to manual, the usage is
```
Usage:  docker compose [OPTIONS] COMMAND
```
The **Options** are `-f` to specify the compose file, and `-p` to set the project name
If you only want to compose a specific file such as `1_mycustomdockercompose.yml`, you can use the following command
```
docker compose -f 1_docker-compose.yml up
```
Where `[OPTION]` is `-f 1_docker-compose.yml`, and the `COMMAND` is `up`

Saludos!
