### ISSUE TITLE
Limit stdout tail of `docker-compose up`

### ISSUE THREAD

**Issue by whitecolor** [docker/compose#5047]
When executing `docker-compose up` for some already running services `docker-compose` displays all stdout that was produced by running services from start time. I think it would be useful to add flag that that doesn't show previous output or limits its tail.

**Comment by shin-** [comment]
`docker-compose up -d && docker-compose logs --tail=20`

**Comment by whitecolor** [comment]
Thanks, I think that would work for me with `--follow`.
