### ISSUE TITLE
Download => TLS error

### ISSUE THREAD

**Issue by psilva261** [docker/compose#5048]
Since today, curl (and Firefox) report TLS error/a deceptive site when loading https://github.com/docker/compose/releases/download/1.11.1/docker-compose-Linux-x86_64

It seems that - at a minimum - there is a problem with the TLS configuration (no certificate).

**Comment by shin-** [comment]
That's Github's problem though?

**Comment by psilva261** [comment]
Yeah definitely it was a Github thing, anyways, happy that it works again! :)
