### ISSUE TITLE
when mounting file and it doesn't exist or permission denied an empty directory with the same name is mounted instead

### ISSUE THREAD

**Issue by amineparis** [docker/compose#5066]
Errors should never pass silently.

I have spent hours to figure out that the problem was the fact that permissions are missed to mount the file. If I have had an error explaining that I would correct the problem in secondes

**Comment by shin-** [comment]
This is behaving according to spec: https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v-read-only

> `$ docker run -v /doesnt/exist:/foo -w /foo -i -t ubuntu bash`
> When the host directory of a bind-mounted volume doesn’t exist, Docker will automatically create this directory on the host for you. In the example above, Docker will create the `/doesnt/exist` folder before starting your container.

**Comment by amineparis** [comment]
I am writing the issue to suggest spec improvement
