### ISSUE TITLE
it is more dry to have compose file directives exactly the same as docker run argument

### ISSUE THREAD

**Issue by amineparis** [docker/compose#5068]
I think we can do better than remembring that `stdin_open: true` is is equivalent to `-i` docker run argument

**Comment by shin-** [comment]
Uhhh, are you making an argument that having `i: true` in a service's definition is somehow better than `stdin_open: true`? Because I strongly disagree.

**Comment by amineparis** [comment]
Yes I think it's better to have the same arguments as for docker run command, this way users don't need to have in minde two commands one for docker run and one for composer file
