### ISSUE TITLE
Issue with installing docker-compose via pip

### ISSUE THREAD

**Issue by Sabya1981** [docker/compose#5071]
pip install docker-compose throws : 
 Could not find a version that satisfies the requirement docker-compose (from versions: )
No matching distribution found for docker-compose

OS :  Ubuntu 16.04.2 LTS

**Comment by scriptonist** [comment]
I'm using the same OS. But didn't encounter any issue doing the same

**Comment by shin-** [comment]
Make sure pip and python are up to date. Python 2.6 and 3.2 are not supported.
