### ISSUE TITLE
Containers run with `--rm` option have 'AutoRemove: false' and they are not auto-removed when connection lost

### ISSUE THREAD

**Issue by 907th** [docker/compose#5072]
Containers run with `docker-compose run --rm` option are not auto-removed when connection losts. They are still running on the server. They also have `"AutoRemove": false` setting.

Example:

```
$ docker-compose run --rm --name multi_unicorn_222 unicorn  bash -i &

$ docker inspect multi_unicorn_222 | grep AutoRemove
            "AutoRemove": false,
```

Versions:

```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ docker-compose version
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by shin-** [comment]
`AutoRemove` is actually a very recent addition (1.13.0) to the API. We could/should use it for recent (2.2+) compose file versions, but we'll have to keep using the client-side implementation of `--rm` for compatibility reasons.

**Comment by mne1991** [comment]
Is not there any plans to add this `--rm` to be functional in `compose` file as well? It will be pretty to be able to have a container (part of a service) which is run once, and then it gets deleted. for example adding something like: `AutoRemove: true` parameter in compose file to that container of interest?

For instance, hat makes sense if we have any container which changes some files in other container.

**Comment by foxx** [comment]
+1. The feature disparity between Docker and Docker-Compose is quite frustrating.
