### ISSUE TITLE
"compose up" exits with status 0 when terminated with a signal

### ISSUE THREAD

**Issue by cjerdonek** [docker/compose#5082]
If you run `docker-compose up` and terminate it with a signal (e.g. SIGTERM or SIGINT / Control-C), the exit status is 0 instead of non-zero.

When terminating with a signal, the convention is to exit with status code `128 + n`, where n is the signal number. See [here](http://tldp.org/LDP/abs/html/exitcodes.html), for example.

I'm observing this in docker-compose version 1.10.1, build b252738, but looking at the code it seems to be like this in master as well.

**Comment by shin-** [comment]
That convention doesn't make sense in the context of `docker-compose up`, where the signal is caught and the shutdown is handled gracefully. Moreover, this behavior is documented in [our docs](https://docs.docker.com/compose/reference/up/) - though I agree the accuracy of this paragraph is somewhat lacking, and I submitted a docs PR to improve it: https://github.com/docker/docker.github.io/pull/4100

**Comment by shin-** [comment]
Closing via docker/docker.github.io#4100
