### ISSUE TITLE
Running multiple containers in CI - conflicting container names.

### ISSUE THREAD

**Issue by povils** [docker/compose#5083]
Hi, I think this question is more from design point of view. 
I know that you can isolate containers with -p or COMPOSE_PROJECT_NAME environment variable. But in my case, I have many containers defined in docker-compose file which are all linked. And when I run docker and tests inside the container I could access another container by its container name, which I set it in docker-compose file. So now, of course, I can't run two simultaneous builds with same docker-compose definitions because container names are conflicting. I can't use container IP because containers are restarting. So I'm left with removing container_name setting from config? But when how the application which is in one of the containers can access another container if name is dynamic?

**Comment by shin-** [comment]
If you use a v2 or above Compose file, services are addressable using the service name, which should allow you to get rid of the hardcoded container name.
