### ISSUE TITLE
Generated files not updating between builds

### ISSUE THREAD

**Issue by alewaros** [docker/compose#5084]
Hello

I'm having an issue in which my project generates a bundled file during buildtime with a RUN command in the Dockerfile but at the moment of running the project, a volume was inserted over all the project which hid the bundled file.

The solution to allow the container to see the image's bundled file was adding a volume in the /dist directory and it worked when running the container. The problem is that when I change my code and rebuild the image so webpack can bundle the new changes, the bundled file remains the same as in the first try. In other words, this only works the first time I use it.

Is this a bug or normal behavior?

**Comment by shin-** [comment]
[Compose preserves volumes](https://docs.docker.com/compose/overview/#preserve-volume-data-when-containers-are-created) when you recreate a container, so the volume containing the old files might still be hiding the updated files from your new build.

You may run `docker-compose down -v` to remove containers and associated volumes.
