### ISSUE TITLE
Volume must be a mapping, not an array

### ISSUE THREAD

**Issue by noamcore** [docker/compose#5092]
The problem is when I try to use the long syntax present in version 3.2.

I've searched but not found anything related to this in the open issues.

Using the **same** code as in [file reference](https://docs.docker.com/compose/compose-file/#long-syntax-3), but getting this error message.

Here is a screenshot with more information about the versions on my machine.

**docker**: `17.06.0-ce, build 3dfb8343`
**docker-compose**: `version 1.15.0, build e12f3b9`

![screenshot_20170809_132255](https://user-images.githubusercontent.com/1195251/29132799-be9e58aa-7d07-11e7-90fc-f6010de12c63.png)

**Comment by londoncalling** [comment]
@shin- I think when I tried to update Compose reference file examples for context / structure of the Compose file, I didn't get it right some/all of the time :-( 

This probably needed a more thorough review: https://github.com/docker/docker.github.io/pull/3967/files. Can you take a look through these changed samples when you get a chance? 

Then, I can fix anything else that is wrong there, as a part of the PR I'm about to open for this issue?

**Comment by shin-** [comment]
Closing via docker/docker.github.io#4142

Thanks @londoncalling !

**Comment by Kitanotori** [comment]
How am I supposed to mount directory from the host as a read-only volume with that syntax?

**Comment by diveyez** [comment]
GET RID OF THE INDENTATION RULES ON A SIMPLE "WHO I AM " FILE!

**Comment by mansourofski** [comment]
try this :
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
