### ISSUE TITLE
Couldn't connect to Docker daemon at http+unix://var/run/docker.sock

### ISSUE THREAD

**Issue by kharandziuk** [docker/compose#510]
I have the message below on `fig up` command:
>Couldn't connect to Docker daemon at http+unix://var/run/docker.sock - is it running?
>
>If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

# Additional information:
`uname -a`:
>Linux khami-RV418-RV518-RV718 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

`fig --version`:
>fig 0.5.2

`sudo docker version`:
>Client version: 1.0.1
>Client API version: 1.12
>Go version (client): go1.2.1
>Git commit (client): 990021a
>Server version: 1.0.1
>Server API version: 1.12
>Go version (server): go1.2.1
>Git commit (server): 990021a

**Comment by icotix** [comment]
This error message might indicate insufficient permissions. You might have to add your user to the group 'docker' or run docker (fig) with sudo.

**Comment by dnephin** [comment]
No response from OP
