### ISSUE TITLE
Configure merge behavior for configuration keys

### ISSUE THREAD

**Issue by shin-** [docker/compose#5102]
Some use cases require extends / overrides to completely overwrite the base config for a given key instead of merging both together.

### Issues requesting or requiring this feature: 
- #3648 (build)
- #4973 (ports)
- #4019
- ...

### Steps

- Figure out universal, non-breaking syntax for this feature
- Figure out desirable behaviors (current default behavior, overwrite are the current requested ones. Is there a use-case for giving priority to keys defined in base vs override?)
- Figure out implementation - currently merging behavior is done somewhat differently for each key, according to what makes the most sense as a default. This might make implementation of a generic solution challenging.

**Comment by nicmr** [comment]
If you find arrive here from your Search Engine and are disappointed this seems to have gone nowhere: it's actually implemented: https://docs.docker.com/reference/compose-file/merge/#replace-value
