### ISSUE TITLE
Mount relative path does not work with volumes in Docker compose file

### ISSUE THREAD

**Issue by ducnguyenhuy** [docker/compose#5108]
I want to create a data volume`src` to map to a directory `/home/app` in my container. The directory `/home/app` has data already and I should get a data volume `src` with same data as '/home/app'. But I was not lucky and I got an empty folder `/home/app` in my container. Below is volumes section in my docker-compose file:
`volumes:
    - ./src:/home/app`

Docker host is on MacOS and Docker version shows:

`Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true`

And I'm creating a Docker compose version 1

**Comment by shin-** [comment]
This is behaving as expected.

**Comment by ducnguyenhuy** [comment]
@shin- Thanks for your replying. However, I still misunderstand about volumes in Compose. Could you tell me which document for that? Seem there is a difference between `volumes` section in Compose and `-v` option in `docker run` subcommand.

**Comment by shin-** [comment]
I am sorry but you are mistaken &ndash; host mounts work the same way whether they are created by Compose or by the CLI. Folder contents inside the container are overridden by content from the host, never the other way around.

**Comment by shin-** [comment]
Here is the documentation for this behavior: https://docs.docker.com/engine/admin/volumes/bind-mounts/#mounting-into-a-non-empty-directory-on-the-container

**Comment by ducnguyenhuy** [comment]
@shin- I got it. Thanks
