### ISSUE TITLE
Pipe docker-compose.yml

### ISSUE THREAD

**Issue by jamrizzi** [docker/compose#5120]
It would be nice to be able to pipe a docker-compose.yml file into docker-compose. Yes, I know, it would not be good practice to run your production environments using this. However, it would be super useful for quickly testing different docker stack setups.

```sh
curl https://raw.githubusercontent.com/liberapay/liberapay.com/master/docker-compose.yml | docker-compose up
```

**Comment by shin-** [comment]
> Use a `-f` with `-` (dash) as the filename to read the configuration from `stdin`. When `stdin` is used all paths in the configuration are relative to the current working directory.

[source](https://docs.docker.com/compose/reference/overview/#use--f-to-specify-name-and-path-of-one-or-more-compose-files)

**Comment by jamrizzi** [comment]
Ah, thanks so much

**Comment by rangerscience** [comment]
`-f` is no longer a docker-compose option, it seems?

**Comment by jamrizzi** [comment]
Maybe they actually added piping ???

**Comment by shin-** [comment]
Nothing has changed guys.

**Comment by felixhammerl** [comment]
Seeing the same error as @towc

**Comment by rot26** [comment]
@towc @felixhammerl 

You are seeing the help screen because you must give a command to `docker-compose`

Try:

```sh
some-command | docker-compose -f - config
```

or 

```sh
some-command | docker-compose -f - up
```
