### ISSUE TITLE
Proposal: Add option to specify a port for depends_on

### ISSUE THREAD

**Issue by garvincasimir** [docker/compose#5121]
When using Docker compose I find myself having to create a custom shell script for the sole purpose of waiting on services. Is the compose team willing to consider adding a tcp/udp port option to the depends_on config? This would mostly eliminate the need for a shell in a container that is only intended to ship a compiled binary. It would certainly make my compose based integration tests less complicated.

**Comment by shin-** [comment]
I'm not really sure I understand what it is you're asking for and how it would work - could you elaborate?

**Comment by garvincasimir** [comment]
In my own containers and others I have seen that rely on a db/backend container, we specify **depends_on** to wait till that container is started before our app container starts. As is stated in the documentation, docker does not wait for the container to initialize to move to the next dependency. My suggestion is to take it one step further and wait for a specified port to be open on the db/backend service before starting the app container which specifies **depends_on**.

Take my compose file for example: https://github.com/garvincasimir/csharp-datatables-parser/blob/master/docker-compose-test.yaml.

I would add ports 1433 and 3306 to the depends_on config so docker can do what this file is doing:
https://github.com/garvincasimir/csharp-datatables-parser/blob/master/test/DatatablesParser.Tests/test-runner.sh

If this functionality existed my Entrypoint would be _dotnet test_ and there would be no need for a shell script.
https://github.com/garvincasimir/csharp-datatables-parser/blob/master/Dockerfile-test

Sorry for not providing sufficient information in my initial post. I hope this clarifies what I am proposing.

**Comment by shin-** [comment]
Thanks - I get what you're saying. Unfortunately, that's not a feature we can implement at the `docker-compose` level, which is just a client. You'd need to request it on the [moby](https://github.com/moby/moby) project first.
