### ISSUE TITLE
config command does not honor --no-ansi

### ISSUE THREAD

**Issue by sgammill** [docker/compose#5123]
When running `docker-compose` with the `--no-ansi` flag and the `config` command with a yml file that has Docker stack-only elements, docker-compose displays the warning message with ANSI color sequences.

Affects:  docker-compose 1.16.0-rc1

Example invocation:
``./docker-compose --file stackfile.yml --no-ansi config``

Output:
``WARNING: Some services (docker-api-http, eieio-esb, eieio-management-api, eieio-management-ui) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.``
(then the yml output)

However, the word WARNING in the warning message is colored using ANSI escape sequences, despite the fact that `--no-ansi` has been specified on the command line.  I've tried placing "--no-ansi" before "--file", to no avail.  (Also, the warning should print to stderr instead of stdout.)

**Comment by shin-** [comment]
Thank you for the report!

**Comment by shin-** [comment]
Fixed in #5133
