### ISSUE TITLE
Sequential restart when using `docker-compose up` with scale

### ISSUE THREAD

**Issue by corradio** [docker/compose#5124]
Hello,

It seems to me that when scale is > 1, and a new image is being pulled, using `docker-compose up` restarts all containers in parallel rather than sequentially.
Doing a cascading restart would ensure zero downtime.

Am I correct in my analysis?

Thank you,

Olivier

**Comment by shin-** [comment]
Both are valid strategies depending on your use-case, but you're right that we don't currently offer an automated way to do zero-downtime deployments. In the meantime, you may want to take a look at https://github.com/docker/compose/issues/1786#issuecomment-294434786 which outlines how to do so manually.

**Comment by corradio** [comment]
Hi @shin- , 
Unfortunately your method won't work as I have more than 1 container in production.
With previous versions of docker/docker-compose, it seems like containers were restarted sequentially. Did anything change?
It would be nice to be able to control the start strategy in docker-compose (sequential vs parallel)

**Comment by shin-** [comment]
> With previous versions of docker/docker-compose, it seems like containers were restarted sequentially. Did anything change?

Unless you're looking at versions from 2 years ago, that wasn't the case.

**Comment by corradio** [comment]
I was indeed working with a very old version (due to CI constraints).
Any idea if it's possible to add the feature I'm requesting? I'm up for contributing if needed.

**Comment by domq** [comment]
Replying to the [original question](https://github.com/docker/compose/issues/5124#issue-251914680), it is still not possible to do sequential restarts. *However*, you can prevent `docker-compose up --scale` from restarting existing containers using [the `--no-recreate` flag](https://docs.docker.com/compose/reference/up/). This is enough to do zero-downtime restarts if you only run one serving instance (by momentarily scaling to two, then deleting the oldest container).
