### ISSUE TITLE
Errors running docker compose on AWS

### ISSUE THREAD

**Issue by taffyb** [docker/compose#5126]
What version of docker-compose should be used?
I am using docker-compose version: 1.5.1 and getting '--file' is an invalid option. with this removed and replaced with '-d' I get 
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Unsupported config option for 'services' service: 'bimserver'

**Comment by shin-** [comment]
https://github.com/docker/compose/releases

1.5.1 is almost 2 years old at this point, you should definitely upgrade.
