### ISSUE TITLE
The Docker Engine you're using is running in swarm mode. Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

### ISSUE THREAD

**Issue by nikoo56** [docker/compose#5146]
My application was working fine but suddenly I start to get this message:  

The Docker Engine you're using is running in swarm mode.
Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

I am not using swarm in my application but I worked with it before this app.

**Comment by shin-** [comment]
It's just a warning that will show up if you ran `docker swarm init` or `docker swarm join`. If you don't intend to use Swarm mode on this instance of the Docker engine, you may run `docker swarm leave --force` to get rid of the warning. Either way, this will not affect your application.

**Comment by nikoo56** [comment]
I am not even running swarm commands. I only Run the project inside Visual Studio 2017 that previously was running, but now I am getting this error.

**Comment by shin-** [comment]
Okay. It's not an error, it's a warning. You can safely ignore it. :+1:
