### ISSUE TITLE
Setting order of build

### ISSUE THREAD

**Issue by umrashrf** [docker/compose#5160]
I would like to set order/priority of services to be built. depends_on is not solving my problem because some services do not run but their build order matters.

**Comment by shin-** [comment]
Hi @umrashrf,

This is outside the scope of what Compose sets out to do. The best approach would be to write an external script calling `build` on services in the order you want them.

**Comment by schmunk42** [comment]
@shin- I'd have the same request, since I'd like to define builds where `b` uses `FROM a:latest`, but `b` gets build before `a`.

General question: How is the build order decided?
