### ISSUE TITLE
Docker Compose does't allow to use local images

### ISSUE THREAD

**Issue by victordombrovskiy** [docker/compose#5166]
The following command fails, trying to pull image from the Docker Hub:

    $ docker-compose up -d
    Pulling web-server (web-server:staging)...
    ERROR: repository web-server not found: does not exist or no pull access

But I just want to use a local version of the image, which exists:

    $ docker images
    REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
    web-server           staging             b94573990687        7 hours ago         365MB

Why Docker doesn't search among locally stored images?

**Comment by shin-** [comment]
It works fine as far as I can tell:

```
$ cat docker-compose.yml version: '2.1'
services:
  foo:
    image: my/foo-bar:baz
    command: ls
(compose)joffrey@yuna:~/work/tests/compose/repro5166$ docker tag busybox my/foo-bar:baz
(compose)joffrey@yuna:~/work/tests/compose/repro5166$ docker-compose up
Recreating repro5166_foo_1 ... 
Recreating repro5166_foo_1 ... done
Attaching to repro5166_foo_1
foo_1  | bin
foo_1  | dev
foo_1  | etc
foo_1  | home
foo_1  | proc
foo_1  | root
foo_1  | sys
foo_1  | tmp
foo_1  | usr
foo_1  | var
repro5166_foo_1 exited with code 0
```

Make sure you're using the exact same name, and that Compose isn't connecting to a remote server through your `.env` file.

**Comment by NdagiStanley** [comment]
I concur with @shin- It works fine.
@victordombrovskiy you figured it out?
