### ISSUE TITLE
The download URL of 1.16.1 in release note is incorrect. It is pointed to the 1.16.0 version. 

### ISSUE THREAD

**Issue by denverdino** [docker/compose#5167]

**Comment by albers** [comment]
Confirmed. Ping @shin- @andrewhsu

**Comment by albers** [comment]
Related: the [install docs](https://docs.docker.com/compose/install/) still point to 1.15.0. I opened a PR for that: https://github.com/docker/docker.github.io/pull/4502.

**Comment by albers** [comment]
@denverdino Thanks for reporting!

**Comment by shin-** [comment]
Thanks! Updated.
