### ISSUE TITLE
docker-compose falsely complaining for API Version mismatch

### ISSUE THREAD

**Issue by kumarprd** [docker/compose#5187]
I am using docker-engine 1.7 in El6.

```
# docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```
Installed docker-compose with

```
curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

compose details:
```
# docker-compose version
docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```
docker-engine details
```
# rpm -qa |grep -i docker
docker-engine-1.7.0-1.el6.x86_64
```

Getting this error while using docker-compose:

```
# docker-compose up
ERROR: client and server don't have same version (client API version: 1.22, server API version: 1.19)
```

When I tried to use the workaround:
```
export COMPOSE_API_VERSION=1.19
```

Getting the error 
```
# docker-compose up
/tmp/_MEIWqVCub/docker/api/client.py:161: UserWarning: The minimum API version supported is 1.21, but you are using version 1.19. It is recommended you either upgrade Docker Engine or use an older version of Docker SDK for Python.
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 121, in perform_command
  File "compose/cli/main.py", line 938, in up
  File "compose/project.py", line 419, in up
  File "compose/project.py", line 468, in initialize
  File "compose/network.py", line 257, in initialize
  File "compose/network.py", line 61, in ensure
  File "compose/network.py", line 93, in inspect
  File "site-packages/docker/utils/decorators.py", line 31, in wrapper
docker.errors.InvalidVersion: inspect_network is not available for version < 1.21
Failed to execute script docker-compose

```

No idea how to proceed further as this is the latest version available for el6.

**Comment by kumarprd** [comment]
docker compose  output is misleading.
both Client API version and Server API version are same, but its complaining both are different , why is it so ?

**Comment by shin-** [comment]
The "client" in this situation is Compose itself. Unfortunately, the version of Docker you are using is too old to be compatible with recent versions of the software (see the [compatibility matrix](https://docs.docker.com/compose/compose-file/compose-file-v2/#compose-and-docker-compatibility-matrix)). You may be able to make it work with [Compose 1.4.2](https://github.com/docker/compose/releases/tag/1.4.2), but please keep in mind that using software that is over 2 years old is unsupported, and potentially unsafe.

**Comment by algupta** [comment]
I am facing the similar issue.
Installed on Ubuntu 14.04 using: apt-get -y install docker.io

$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

$ docker-compose -v
docker-compose version 1.22.0, build f46880fe

$ export COMPOSE_API_VERSION=1.18
$ docker-compose up -d
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 41, in project_from_options
  File "compose/cli/command.py", line 121, in get_project
  File "compose/cli/command.py", line 92, in get_client
  File "compose/cli/docker_client.py", line 127, in docker_client
  File "site-packages/docker/api/client.py", line 170, in __init__
docker.errors.InvalidVersion: API versions below 1.21 are no longer supported by this library.
[5327] Failed to execute script docker-compose

**Comment by thaJeztah** [comment]
@algupta  it looks like you installed the docker package that's maintained by the Ubuntu packagers; unfortunately, that package hasn't been updated for [more than three years](https://github.com/moby/moby/releases/tag/v1.6.0); Docker 1.6 reached end of life in June 2015, and has not been maintained since; I *highly* recommend updating to a current version of Docker, because version 1.6 has known vulnerabilities, including a possible container escape.

To install a current version of the official Docker packages, follow the installation instructions in the documentation; https://docs.docker.com/install/linux/docker-ce/ubuntu/ (if possible, also update your Ubuntu kernel to a 4.x kernel so that you can take advantage of the overlay2 storage driver, or better even; upgrade to Ubuntu 18.04 or 16.04 LTS, because 14.04 is getting a bit old)

**Comment by algupta** [comment]
Thank you @thaJeztah 
It is resolved after updating docker as per the document provided.
Thanks
Alok

**Comment by thaJeztah** [comment]
Great!
