### ISSUE TITLE
Container_Name - Would be nice to have a $count variable

### ISSUE THREAD

**Issue by richraid21** [docker/compose#5189]
Currently according to the documentation, you cannot use `container_name` when you scale using `docker-compose` -- It will throw an error. 

It would be nice if you could add a count property to ensure this name is unique when scaling.

For example:
```
container_name: 'my-service-$count`
```

Launching it with `my-service=2` would result in a container named `my-service-0` and `my-service-1`

**Comment by shin-** [comment]
This has been discussed before: https://github.com/docker/compose/pull/1131 

Why do you need to set `container_name` in the first place? It's an obsolete parameter for most use-cases in modern docker app development. If you are relying on it for networking, please consider using [`aliases`](https://docs.docker.com/compose/compose-file/compose-file-v2/#aliases) instead
