### ISSUE TITLE
Can't write data to redis from docker container using docker-compose.yml. 

### ISSUE THREAD

**Issue by KathiresanRamkumar95** [docker/compose#5190]
I am using Linux.
I am trying to add data to Redis from my web application running on Tomcat container.
But I can't store any more data to Redis.When I restart Redis container, the temporarily added data lost.
I configure the docker from using docker-compose.yml
Redis-bitnami/redis:latest

Please update ASAP.
Thanks

**Comment by KathiresanRamkumar95** [comment]
version: "2.0"

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./src:/bitnami/redis/data
    networks:
      - app-tier
  tomcat:
    image: 'bitnami/tomcat:latest'
    ports:
      - '8080:8080'
    volumes:
      - ./app:/bitnami/tomcat/data
    networks:
      - app-tier
  hub:
    image : selenium/hub
    volumes:
      - /home:/home
    networks:
      - app-tier
  chrome1:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    depends_on:
      - hub
    volumes:
      - /home:/home
    networks:
      - app-tier
  firefox:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    depends_on:
      - chrome1
    volumes:
      - /home:/home
    networks:
      - `app-tier```

**Comment by KathiresanRamkumar95** [comment]
This is my docker-compose.yml. 


Thanks in advance!

**Comment by shin-** [comment]
Please see the [forums](https://forums.docker.com) for general support.

**Comment by KathiresanRamkumar95** [comment]
Forums have no discussion about this issue. Please update the proper idea or solution for that in this place. Thanks
@shin-

**Comment by shin-** [comment]
Sorry, I can't help you. You will have to create a new thread on the forums or contact our support team if you are an Enterprise Edition subscriber.
