### ISSUE TITLE
docker-compose domainname doesn't work as advertised

### ISSUE THREAD

**Issue by matclab** [docker/compose#5199]
```
$ docker --version                                     
Docker version 17.07.0-ce, build 87847530f7
$ docker-compose --version
docker-compose version 1.16.1, build unknown
$ uname -a
Linux machine 4.12.12-1-ARCH #1 SMP PREEMPT Sun Sep 10 09:41:14 CEST 2017 x86_64 GNU/Linux
```

With the docker-compose.yml file:
```
version: '2'
services:
   test:
      build: .
      domainname: rendre.fr
```

and the Dockerfile:
```
From alpine

RUN apk update && apk add net-tools

CMD ["/bin/sh", "-c", "hostname;domainname; nisdomainname"]
```

Doing `docker-compose up --build` I get the following output:
```
test_1  | 88c5aee837f5.rendre.fr
test_1  | (none)
test_1  | (none)
```

Whereas I would have expected to see `rendre.fr` instead of `(none)` for the two last one.
This problem prevent NIS from working inside the container.

The problem was initially observed in an ubuntu based image.

**Comment by matclab** [comment]
Note that I've already used NIS on a docker image (with a previous docker version), and the domainname configuration item worked.

I wonder if https://github.com/docker/docker-ce/commit/709b902d706798343937633d78b1fe64361d2f41#diff-892b7a5bd9a2e2badf146b08a85f8ce6R354 may not be the culprit as `config.domainname` is not set anymore… (very quick and vague guess as I do not know the code base at all).

**Comment by dbjpanda** [comment]
I don't find any documentation on how to use domainname and what it exactly does?

**Comment by matclab** [comment]
Strange. Docker compose says `domainname` option is analogous to its docker run couterparts : https://docs.docker.com/compose/compose-file/#restart, but it looks like there is no more mention of domainname in *docker run* documentation !

However there is a Domainname configuration item in the source code : https://github.com/docker/docker-ce/blob/4db928a87dfbff4f97f30e31f3178f99147c2163/components/engine/api/types/container/config.go#L45

**Comment by matclab** [comment]
Testing with the following version (current on ArchLinux)
```
$ docker-compose --version 
docker-compose version 1.24.1, build unknown
$ docker --version
Docker version 19.03.2-ce, build 6a30dfca03
```
It works :
```
test_1  | d66cf21e1588
test_1  | rendre.fr
test_1  | rendre.fr
```
