### ISSUE TITLE
docker-compose ignores /etc/docker/daemon.js ?

### ISSUE THREAD

**Issue by kitingChris** [docker/compose#5204]
I am currently in trouble with IP ranges that docker uses. Due to public wifi using 172.18.0.1 for login purpose I wanted to restrict docker using IP Range starting at 172.20.0.0

So I set up the **/etc/docker/daemon.js**
```
{
  "bip": "172.20.0.1/15",
  "fixed-cidr": "172.20.0.0/14",
  "fixed-cidr-v6": "2001:db8::/64",
  "mtu": 1500,
  "default-gateway": "172.20.1.1",
  "default-gateway-v6": "2001:db8:abcd::89",
  "dns": ["172.20.1.2","172.20.1.3"]
}
```
It works very well for the docker0 bridge but every docker-compose project starts again using 172.17... and then 172.18.... 
Why does it ignore my config or am I missing something?

How to prevent docker in general to use those IPs?

**Comment by imaia** [comment]
I have the exact same problem. Containers created with docker-compose do not respect daemon.json and conflict with my network. I'm having to set ipam manually as a workaround.

**Comment by johnharris85** [comment]
Don't believe this is a compose issue. Compose just uses `docker-py` which calls the daemon under the hood, Compose doesn't interact with that file at all. Currently there isn't inbuilt functionality to do what you want, although there is a proposal and some workarounds here - https://github.com/moby/moby/issues/21776.

**Comment by shin-** [comment]
@johnharris85 is right, this is the same issue as #4336 and there's unfortunately nothing we can do at the Compose level. The corresponding issue on the Moby repo is https://github.com/moby/moby/pull/29376
