### ISSUE TITLE
Can't find image till it does

### ISSUE THREAD

**Issue by andy9775** [docker/compose#5205]
I'm having an issue launching a compose based stack. Using `docker stack deploy...` I'm starting a stack running on docker swarm in AWS. When executing `docker stack ps <name>` I see multiple attempts to launch each service with each failing to find the image. This happens for a few minutes until the services start working at random. The image comes from a private repo hosted on docker hub and I'm using `--with-registry-auth` to start the service. The same thing happens when updating a service via `docker service update ...` - it fails and retries for 1-2 minutes then it starts working randomly.

**Comment by shin-** [comment]
Please report `docker stack` issues on the [moby/moby](https://github.com/moby/moby) repo.
