### ISSUE TITLE
a typo in docker-compose [1.16.1] installation for linux

### ISSUE THREAD

**Issue by seralf** [docker/compose#5208]
Hi there seems to be a small typo on the instructions for installing docker-compose version 1.16.1 on linux machine.

Instructions provided for the installation of [release 1.16.1](https://github.com/docker/compose/releases/tag/1.16.1) are 

```
curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
``` 

while on the [guide](https://docs.docker.com/compose/install/#install-compose) it is:

```
sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
```

**Comment by shin-** [comment]
They're equivalent (bar the `sudo` part, which is a matter of preference / audience)
