### ISSUE TITLE
run docker command in compose-service

### ISSUE THREAD

**Issue by jmarcos-cano** [docker/compose#5219]
hello guys I have a question regarding running docker commands inside a docker-compose service, here's my docker-compose snippet:

```version: '3'
services:

  logger:
    image: docker:17.06.0-ce
    volumes:
      - /tmp:/var/log
      - /var/run/docker.sock:/var/run/docker.sock:ro

    command:
      - docker service ls


    deploy:
      placement:
        constraints: [node.role == manager]
```

but I get the following error:

```Recreating logger_logger_1 ... 
Recreating logger_logger_1 ... done
Attaching to logger_logger_1
logger_1  | /usr/local/bin/docker-entrypoint.sh: exec: line 35: docker service ls: not found
logger_logger_1 exited with code 127
```

what am I missing ?

**Comment by jmarcos-cano** [comment]
So to anyone experiencing this issue please use exec format

  `  command: ["docker" ,"service", "ls" ]`

**Comment by shin-** [comment]
In YAML, the following assigns a one-item list to the `command` field.
```yaml
command:
  - docker service ls
```

which is equivalent to `command: ["docker service ls"]`, which is obviously invalid. The proper notation is the one you suggested, or in a simpler manner: `command: "docker service ls"`
