### ISSUE TITLE
Does userns_mode: "host" work?

### ISSUE THREAD

**Issue by adam0z** [docker/compose#5226]
I had added `userns_mode: "host"` to a service definition, but after container starts I noticed that it still creates files at `/var/lib/docker/500000.500000/containers` instead of `/var/lib/docker/containers`.
As you can see I use `docker:500000:65536` mappind set in the docker daemon.

**Comment by shin-** [comment]
If you do `docker inspect <container_id> | grep 'UsernsMode'`, what do you see?

**Comment by shin-** [comment]
Feel free to reopen if you're still having issues.
