### ISSUE TITLE
Semantics of volumes specified in docker-compose from within a container are unclear.

### ISSUE THREAD

**Issue by cstorey** [docker/compose#5232]
We're running:

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.2-ce
 Built:        Wed Aug  9 22:45:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

As part of our integration test setup, we use `docker-compose` to start an integration-test container, that in turn depends on a database. For the integration-test container, we specify:

```
    volumes:
      - .:/app
```

To ensure that the application build directory is available to the test process. This is all fine and dandy when running directly on a docker host; but our CI workers themselves run inside docker containers, and we bind-mount the docker socket into the ci worker container so we can make use of docker compose.

So, when we start docker compose from inside of the CI container from working directory `/workspace/widget`; it quite reasonably runs the equivalent of: `docker run -v /workspace/widget:/app my-image my-lovely-tests`. However, because `/workspace/widget` means something different on the host as compared to the container, and docker-compose doesn't seem to take this into account; the docker demon tries to bind mount `/workspace/widget` from the _host_ into the test container, resulting in an empty directory under `/app`.

A confounding factor is that `dockerd` seems to auto-magically create the source path `/workspace/widget` on the host, where I'd expect it to fail because it doesn't exist on the host. 

Based on a quick skim of [mount_namespaces.7](http://man7.org/linux/man-pages/man7/mount_namespaces.7.html), it would appear that the required information would be available to docker-compose itself via `/proc/self/mountinfo`; alternatively, it might well ask dockerd directly (although that requires more work).

For now, I should be able to mitigate this by avoiding the need for the `volumes` specifier.

Thanks,

**Comment by shin-** [comment]
Hi @cstorey ,

As it stands, Compose has no way of knowing whether your Docker daemon runs locally, inside a container, or on a remote host. Therefore the burden is on the user to make sure bind-mounts are valid in the context the daemon is running in.

You have the right idea I think ; in cases that don't involve local development, mounting host folders is best avoided, in part for the reasons you highlight here. Adding application files into your test image is recommended practice.

HTH!

**Comment by cstorey** [comment]
Well, it'd be good if this was in the documentation; and even better, a warning if `docker-compose` isn't in the default filesystem namespace.

**Comment by shin-** [comment]
> Well, it'd be good if this was in the documentation; 

Feel free to suggest changes that you feel would be helpful on the [docs repo](https://github.com/docker/docker.github.io)

> and even better, a warning if docker-compose isn't in the default filesystem namespace.

As I pointed out above, Compose has no reliable way to detect that.
