### ISSUE TITLE
alternative location for downloading docker compose

### ISSUE THREAD

**Issue by JasonDuquain** [docker/compose#5235]
Our company is wanting to download the latest version of docker compose for linus. However the install team is hesitant to run a file that is sourced from a public repository and is not digitally signed. The software they are aurhorized to install typically comes from verified locations, software vendor sites and are digitally signed. Is there an alternative location or a digitally signed binary that can be used to download this file?

**Comment by shin-** [comment]
Sorry, not at this time. https://github.com/docker/compose/issues/4264
