### ISSUE TITLE
Acceptance tests failing only in Jenkins

### ISSUE THREAD

**Issue by garribas** [docker/compose#5242]
The following two acceptance test cases are failing for all new PRs, no matter what the source code changes are:
- CLITestCase.test_build_failed (`assert len(containers) == 1` fails with `AssertionError: assert 3 == 1`)
- CLITestCase.test_build_failed_forcerm (`assert not containers` fails with `AssertionError: assert not [<Container: affectionate_dijkstra (349f9a)>]`)

Both tests pass locally, is the Jenkins server keeping some state of previous builds?

Affected PRs: #5237 , #5238, #5241

Jenkins logs:
https://jenkins.dockerproject.org/job/docker/job/compose/job/PR-5237/1/consoleFull
https://jenkins.dockerproject.org/job/docker/job/compose/job/PR-5238/2/consoleFull
https://jenkins.dockerproject.org/job/docker/job/compose/job/PR-5241/1/consoleFull

**Comment by shin-** [comment]
It's probably due to a bug in the new Engine RC (17.10.0-ce-rc1). I'll take a closer look. Thank you for reporting it.

**Comment by shin-** [comment]
@garribas I flagged the failing tests so the CI should be in an okay state again until the engine fix gets released. Do you mind rebasing your recent PRs against `master` to make sure everything else is good to go? Thank you!

**Comment by garribas** [comment]
@shin- Thanks, I've rebased all of my PRs.
