### ISSUE TITLE
docker-compose invalid bind mount spec when colon in path

### ISSUE THREAD

**Issue by axiix** [docker/compose#5244]
When trying to use the following bind mount within a docker-compose file version 3.3:
    _volumes:
      - type: bind
        source: e:/dev/docker_shared/cache
        target: /projects/install/server/jboss/bin/C:/var/local/arc/fs1_

I get the following error when using docker-compose up

> ERROR: for ei  Cannot create container for service ei: invalid bind mount spec "/e/dev/docker_shared/cache:/projects/install/server/jboss/bin/C:/var/local/arc/fs1": invalid mode: /var/local/arc/fs1

The service installed on the container creates the directory with a colon and for now, I won't be able to change that.
Tried to escape the colon but with no success. 
docker version:
> Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64
Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by shin-** [comment]
Thanks for the report!
