### ISSUE TITLE
Assigning IP address in Docker Compose 3

### ISSUE THREAD

**Issue by infosec-alchemist** [docker/compose#5259]
I'm using Docker Compose, and I'm unclear how to setup a multi container architecture where one of those containers needs to be available OUTSIDE of Docker.

In my scenario, I'm setting up an Elasticsearch, Logstash, Kibana stack in Docker.  However, I need to send logs to Logstash from a Windows VM. So, that Windows VM needs to know the IP of logstash.

In Docker Compose 3, the ability to assign IP addresses appears to be removed.  So, what is the option?

**Comment by shin-** [comment]
If you're using `docker stack deploy`, please create an issue on the [moby/moby](https://github.com/moby/moby) repo instead.

If you're using `docker-compose`, please use v2 compose files if the features you need aren't yet available in the v3 format.
