### ISSUE TITLE
Translate docker-compose to equivalent list of docker commands

### ISSUE THREAD

**Issue by imaia** [docker/compose#5264]
Is there a way to translate a docker-compose to a list of docker commands? I know docker-compose manages that behind the scenes, but I would like some flexibility over the what is done.

**Comment by shin-** [comment]
The `--debug` output prints which [SDK](https://github.com/docker/docker-py) methods are being called with what parameters, so you can work it out from there.

**Comment by leimao** [comment]
> The `--verbose` output prints which [SDK](https://github.com/docker/docker-py) methods are being called with what parameters, so you can work it out from there.

It is still too messy. I wish we could have an exact translator.
