### ISSUE TITLE
Entrypoint/CMD behavior changed or documented wrong

### ISSUE THREAD

**Issue by Brian-Williams** [docker/compose#5272]
## Problem
In the [docs](https://docs.docker.com/compose/compose-file/#entrypoint) it is stated that:

> Setting entrypoint will both override any default entrypoint set on the service’s image with the ENTRYPOINT Dockerfile instruction, and clear out any default command on the image - meaning that if there’s a CMD instruction in the Dockerfile, it will be ignored.

However this doesn't seem true in practice.

Edit: This isn't true only if the input to entrypoint is empty (`[]`, `""`).

## Bug setup

Make the following dockerfile tag with echo and make the following docker-compose.yml file.

Dockerfile
```
From python:3

ENTRYPOINT [ "echo", "garbage" ]
CMD [ "echo", "hi" ]
```

Build the image with tag echo `docker build -t echo .`.

docker-compose.yml
```
version: '3'
services:
  echo:
    image: echo
    entrypoint: ""
```

## Expected results

That both the ENTRYPOINT and CMD are wiped when bringing up the docker-compose.yml.

## Actual result

The CMD is still used.

## Execution with actual result

```
$ docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "testcompose_default" with the default driver
Creating testcompose_echo_1 ... 
Creating testcompose_echo_1 ... done
Attaching to testcompose_echo_1
echo_1  | hi
testcompose_echo_1 exited with code 0
```

The entrypoint is being removed, but the CMD of `echo hi` is still being run on this line `echo_1  | hi`.

If we comment out the entrypoint in the docker-compose.yml we get the expected result of entrypoint(`echo garbage`) cmd(`echo hi`) -> `garbage echo hi`
```
Creating network "testcompose_default" with the default driver
Creating testcompose_echo_1 ... 
Creating testcompose_echo_1 ... done
Attaching to testcompose_echo_1
echo_1  | garbage echo hi
testcompose_echo_1 exited with code 0
```

The expected result of `garbage echo hi` is shown on this line `echo_1  | garbage echo hi`.

## Version info
```
Brians-MacBook-Pro:test_compose brianwilliams$ docker-compose --version
docker-compose version 1.16.1, build 6d1ac21
Brians-MacBook-Pro:test_compose brianwilliams$ docker --version
Docker version 17.09.0-ce-rc3, build 2357fb2
```

**Comment by Brian-Williams** [comment]
It looks like when entrypoint is given a non-empty value then it overrides both entrypoint and cmd.

If given an empty value (`[]`, `""`) then it only overrides the entrypoint. Is this working as intended? If so it should be documented with the existing Note as from reading it it would seem impossible.

Also, if this is intended how would I remove the cmd and the entrypoint as cmd isn't a valid docker-compose input and if I put in an emtpy value for entrypoint the cmd will remain.

**Comment by shin-** [comment]
I can confirm that that's the intended behavior as it matches the remote API's. Feel free to create an issue on the docs repo: https://github.com/docker/docker.github.io/issues

As for the `CMD` entry, it corresponds to the `command` field in the service's definition.

HTH

**Comment by Brian-Williams** [comment]
Thanks @shin- I didn't know command corresponded to cmd. That closes any functionality hole I thought there was.

Ill close this issue as there are already plenty discussing how some believe entrypoint is unintuitive.
