### ISSUE TITLE
I am having this "Encountered errors while bringing up the project." error

### ISSUE THREAD

**Issue by amjadharri** [docker/compose#5286]
when `$ docker-compose up` it returns 

```
Starting df33a29fc6ee_df33a29fc6ee_adaptive-admin_mariadb ...
Starting df33a29fc6ee_df33a29fc6ee_adaptive-admin_mariadb ... error
```

Docker Version 
```
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:05 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

on $ docker-compose --verbose up

```
compose.parallel.feed_queue: Pending: set([])
Starting df33a29fc6ee_df33a29fc6ee_adaptive-admin_mariadb ... error
compose.parallel.feed_queue: Pending: set([])

ERROR: compose.cli.main.main: Encountered errors while bringing up the project.
```

**Comment by shin-** [comment]
Does running `docker-compose down` solve the issue?

**Comment by amjadharri** [comment]
No, I figured out I have to install composer to solve the issue.

**Comment by dwaynewei** [comment]
@shin-  that command line you wrote there solved my issue!!    man..  I searched so many places couldn't get my issue solved, I got say THANK YOU bro!!   thanks so much.

**Comment by chinmay90kulkarni** [comment]
docker-compose down --> worked for me..
Thanks

**Comment by javiersantossanchez** [comment]
That works for me. Thank you

**Comment by jemliF** [comment]
None of the above worked for me.
Environment: 
- Ubuntu 16.04
- Docker version 18.09.0, build 4d60db4
- docker-compose version 1.18.0, build 8dd22a9

**Comment by myselfdesai** [comment]
some of the time if you forgot to include any package in requirement.txt gives u package oriented failure error.

**Comment by ningjiabing** [comment]
That works for me. Thank you

**Comment by ningjiabing** [comment]
That works for me Thinks!

**Comment by TaufiqurRahman45** [comment]
try with it:

sudo pkill mysql
sudo pkill mysqld
docker-compose down
docker-compose up

**Comment by aayushgupta97** [comment]
> Does running `docker-compose down` solve the issue?

Thank you this worked for me as well. My dev and prod environments were running correctly but local was giving the error. 
Running docker-compose -f local.yml down solved the error for me.

**Comment by kamalne** [comment]
I encountered an installation issue I don't know how to solve a problem


Creating azuracast_nginx_proxy_1 ... error

ERROR: for azuracast_nginx_proxy_1  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint azuracast_nginx_proxy_1 (1252b820c80ae8a6f188978baf4f99155feb9430d4330db28c991dfd1f8e96ab): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use

ERROR: for nginx_proxy  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint azuracast_nginx_proxy_1 (1252b820c80ae8a6f188978baf4f99155feb9430d4330db28c991dfd1f8e96ab): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use
ERROR: Encountered errors while bringing up the project.
root@radio:/var/azuracast#

**Comment by tmtron** [comment]
In my case I tried to start a webserver (nginx for let's encrypt) and got the error:  
```Bind for 0.0.0.0:80 failed: port is already allocated```

The reason was, that another docker project was running nginx (thus the port was really already in use)

Solution was to use `docker ps` to find the running container/s and stop it/them: `docker stop CONTAINER_ID`

**Comment by atul-gautam-au6** [comment]
$ make start
Pulling postgres      ... done
Pulling hydra-migrate ... done
Pulling hydra         ... done
Starting reaction-hydra_postgres_1 ... done
Starting reaction-hydra_hydra-migrate_1 ... done
Starting reaction-hydra_hydra_1         ... done
Pulling mongo ... done
Pulling api   ... done
Starting reaction_mongo_1 ... 
Starting reaction_mongo_1 ... error

ERROR: for reaction_mongo_1  Cannot start service mongo: driver failed programming external connectivity on endpoint reaction_mongo_1 (5b5f99016cba3d432aab21eb5119446e6b6c47755f36deb371ea579e72a1968d): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use

ERROR: for mongo  Cannot start service mongo: driver failed programming external connectivity on endpoint reaction_mongo_1 (5b5f99016cba3d432aab21eb5119446e6b6c47755f36deb371ea579e72a1968d): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:348: start-reaction] Error 1

**Comment by alvarosena** [comment]
> try with it:
> 
> sudo pkill mysql
> sudo pkill mysqld
> docker-compose down
> docker-compose up

I LOVE SO MUCH!

**Comment by alvarosena** [comment]
I love YOU so much bro thanks! I was having a problem with postgres and I try sudo pkill postgres and docker-compose down and works

**Comment by sathishkurichy** [comment]
Hello !,

I got the error like blelow one

```
Digest: sha256:58132ff3162cf9ecc8e2042c77b2ec46f6024c35e83bda3cabde76437406f8ac
Status: Downloaded newer image for redis:alpine
Creating getground_workspace_1 ... 
Creating getground_workspace_1 ... error
Creating getground_mysql_1     ... 
Creating getground_php-fpm_1   ... 
Creating getground_redis_1     ... 
Creating getground_web_1       ... done
Creating getground_mysql_1     ... done
Creating getground_php-fpm_1   ... done
Creating getground_redis_1     ... done

ERROR: for workspace  Cannot start service workspace: driver failed programming external connectivity on endpoint getground_workspace_1 (e033dd78aefe4217b11055f1ebf424df8f2428c87a14f8a459911eb611c34285): Error starting userland proxy: listen tcp4 0.0.0.0:3000: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```
I'm using ubuntu 18.04 and docker Version:  20.10.10. can you please suuggest for this issue?

**Comment by kamalne** [comment]
مرحبا بك بي ما أسعدك

Le sam. 30 oct. 2021 à 14:18, sathishkurichy ***@***.***> a
écrit :

**Comment by noamzilo** [comment]
> Does running `docker-compose down` solve the issue?

it **avoids** the issue.

The point with automatic tests is, well... automation.

I have to run docker-compose down after every time I run my test . Clearly I am missing something.

**Comment by camilabmc** [comment]
> try with it:
> 
> sudo pkill mysql sudo pkill mysqld docker-compose down docker-compose up

This worked for me

**Comment by kamalne** [comment]
مرحبا
