### ISSUE TITLE
Documentation: missing scale parameter

### ISSUE THREAD

**Issue by gustavopaes** [docker/compose#5289]
There is no documentation about the new "scale" parameter at compose file doc page:
https://docs.docker.com/compose/compose-file/compose-file-v2/

And the link to "scale" parameter at changelog is broken:
https://docs.docker.com/compose/compose-file/compose-versioning/#version-22

**Comment by shin-** [comment]
Hi @gustavopaes 

Please report documentation issues on the [docs repo](https://github.com/docker/docker.github.io)!
