### ISSUE TITLE
Error grabbing logs: EOF

### ISSUE THREAD

**Issue by whitecolor** [docker/compose#5293]
compose `1.17.0-rc1` / `1.16.1`
docker 17.09.0-ce
OS: Windows 10 WSL (Ubuntu)

When starting containers **periodically** get the error `Error grabbing logs: EOF`
![image](https://user-images.githubusercontent.com/736697/31863834-1a03b5f2-b708-11e7-912b-97b0c1bc381c.png)

Any suggestions what may be the problem?

**Comment by shin-** [comment]
This error message is produced by the application inside your container, not Compose. I'd recommend asking on the [forums](https://forums.docker.com) with additional details on what `emails-render_1` is running.

**Comment by whitecolor** [comment]
> This error message is produced by the application inside your container, not Compose. 

I'm don't think so, email-render is just my `nodejs` application, there is no any messages like this inside and it happens on many of my node containers (actually i'm running only node based containers).

See, https://github.com/docker/for-mac/issues/1984 maybe this is the problem of docker for windows?

**Comment by shin-** [comment]
Oh, my bad - because of the way it is displayed, it looked like an application log, but it seems like the message is actually generated by [the engine](https://github.com/moby/moby/blob/147443a42665419d8b3c2047a7d345440bfb63c0/api/server/httputils/write_log_stream.go#L43). I would report the issue on moby/moby.

**Comment by whitecolor** [comment]
I've reported to docker-for-win https://github.com/docker/for-win/issues/1235
Maybe the problem is specific to the platform here, will see how it will go. I didn't see this message before, on older versions

**Comment by shin-** [comment]
Closing in favor of https://github.com/moby/moby/issues/35370

**Comment by zloyded** [comment]
I have same issue! In My flask application while serialize json from time to time i`ve see this message. 
Code is simple, nothing incredible. Simple loop for k, v in d.items(): log.info(k)....
