### ISSUE TITLE
flake8 error on master branch, file compose/bundle.py

### ISSUE THREAD

**Issue by garribas** [docker/compose#5298]
When trying to run the test suite on master branch the pre-commit hook fails with an flake8 error:

```
$ script/test/default 
Flake8...................................................................Failed
hookid: flake8

compose/bundle.py:124:5: E722 do not use bare except'
```

**Comment by shin-** [comment]
I feel like this is not the first time a Flake8 update adds new errors ; we should probably pin the version to avoid this going forward.

**Comment by garribas** [comment]
@shin- the root cause of this is that the "pre-commit-hooks" doesn't pin any of its dependencies:
https://github.com/pre-commit/pre-commit-hooks/blob/master/requirements-dev.txt
