### ISSUE TITLE
docker network rm NETWORK fails HNS failed with eerror: The parameter is incorrect

### ISSUE THREAD

**Issue by jcolebrand** [docker/compose#5302]
docker network create -d transparent --gateway 10.31.0.01 --subnet=10.31.0.0/16 -o com.docker.network.windowsshim.interface="Ethernet" backend

    docker network ls

see it is there

    docker network rm backend

fails with `HSN failed with error : The parameter is incorrect.`

    docker network ls 

only see nat, null

restart docker service

    docker network ls

see a new random network with just the hash for the name (ex: b3631004b54cb3e6c36f004eee21d7a239357e23b84141f6085d37ae048c491d)

try to re-add with the same above command and get that the network already exists

Remove the network now by ID.

can re-add

**Comment by jcolebrand** [comment]
This is on Docker for Windows 
Version 17.09.0-ce-win33 (13620)
Channel: stable
8c56a3b

**Comment by shin-** [comment]
I don't see anything related to `docker-compose` here. Did you mean to post this on https://github.com/docker/for-win ?

**Comment by jcolebrand** [comment]
Crap. Yes. I thought I hit the right link.
