### ISSUE TITLE
How to make a service in a docker-compose file depend on the health status of another service started outside

### ISSUE THREAD

**Issue by rchadalawada** [docker/compose#5307]
I was trying to use depends_on: on a service started outside  the docker-compose file
depends_on:
  mydb:
   condition: service_healthy

It would be nice to specify something like

services:
  mydb:
     external: true

I see that this option is available for volumes and network but not for services.

**Comment by shin-** [comment]
Thank you for your suggestion! Unfortunately, that's not something we intend to support.
