### ISSUE TITLE
Remove docker-compose package from pypi

### ISSUE THREAD

**Issue by stestagg** [docker/compose#5308]
Hi,

The docker-compose package on pypi gives a false implication that there is a python client library for docker-compose.

#4542 makes it clear that this isn't the case, and that the python library is just an internal piece of tooling.

Given this, it would be nicer from a community perspective if you remove this library from pypi, and just ship the code as part of your own distribution directly.

**Comment by stestagg** [comment]
At the very least, it would be nice if the package metadata were updated to indicate that this isn't a supported client library, and the production status changed to 'Development Status :: 3 - Alpha'

:)

**Comment by stestagg** [comment]
OK, please disregard this, I've come to my senses..

**Comment by retr0h** [comment]
@stestagg what were your senses?  I am looking to use compose as a python project and see compose on pypi, however, I cannot find docs on how to properly use it.  Can you shed some light on this?

**Comment by retr0h** [comment]
@stestagg I was looking for the same thing, and just realized this isn't a pip project meant to be used as a library.  Duh, me.
