### ISSUE TITLE
Network aliases for default network is throwing an error

### ISSUE THREAD

**Issue by aboosoyeed** [docker/compose#5311]
`
version: '3.4'
services:
 ...
 ...
networks:
  default:
    aliases:
      - usb.staging.com
      - hub.staging.com
      - heart.staging.com
      - mongo
      - minio              

`

The above looking docker compose is throwing me the following error 
"networks.default value Additional properties are not allowed ('aliases' was unexpected)"

However the closed issue https://github.com/docker/compose/issues/3426 suggests that we can do the same. Am I missing something here
Ps:- i have not listed the services as I thought its relevant but if required i can share

**Comment by shin-** [comment]
That's not section where aliases should be used. Please refer to the docs: https://docs.docker.com/compose/compose-file/compose-file-v2/#aliases

**Comment by sastorsl** [comment]
Ended here in search of the same.
Leaving this in the hope that it helps somebody else.

    version: '2'
    services:
      mycontainer:
        networks:
            default:
                aliases:
                    - myalias
