### ISSUE TITLE
Wait for another service to be healthy instead of build failure.

### ISSUE THREAD

**Issue by rajeshdalai** [docker/compose#5317]
We are using docker compose for our microservices.There is a dependency hierarchy among them.Suppose there are 2 services A and B and A depends on B to be healthy.It would be great if docker can wait for service B to be healthy before building service A.We are using version 2.2.

**Comment by shin-** [comment]
Unfortunately, that is not a feature that we are looking to support as we consider it to be out of scope for Compose. Take a look at [dobi](https://dnephin.github.io/dobi/) for build automation.
