### ISSUE TITLE
Support other file names for docker-compose pull

### ISSUE THREAD

**Issue by douglampe** [docker/compose#5321]
Currently docker-compose pull does not support specifying a docker-compose file. We often have multiple yml files for different purposes so none are "docker-compose.yml" or not necessarily the one that has all the images we want to pull. It would be nice to have an option such as:

`docker-compose pull --file docker-compose-with-suffix.yml`

**Comment by vingrad** [comment]
+1

**Comment by shin-** [comment]
Just move the --file option before the subcommand (`pull`)

**Comment by kaleelahamed** [comment]
`docker-compose --file docker-compose-with-suffix.yml pull `
