### ISSUE TITLE
Multi-stage build target support in Compose file version 3.x

### ISSUE THREAD

**Issue by ibnesayeed** [docker/compose#5322]
Support for the `target` option is missing in `3.x` version of Compose file format. It is supported in `2.3` though #5043. Looking at the compatibility matrix, it should be added in `3.3+` versions as well because they support Docker version `17.06.0+`.

**Comment by VolCh** [comment]
It supports in 3.4 version, started from 1.17

**Comment by ibnesayeed** [comment]
Thanks @VolCh. Since `1.17` is still in RC phase, I will wait until it reaches to masses, meanwhile I will continue using `2.3`.

**Comment by Jokero** [comment]
But documentation https://docs.docker.com/compose/compose-file/#build does not say anything about this options :smile:

**Comment by jeeyoungk** [comment]
any update on this?

**Comment by shin-** [comment]
@jeeyoungk The feature has been implemented and available in main releases for several months.

**Comment by awsmsrc** [comment]
@shin- could you point me to the docs? It seems to be undocumented. https://docs.docker.com/compose/reference/build/

**Comment by shin-** [comment]
https://docs.docker.com/compose/compose-file/compose-file-v2/#target

**Comment by ibnesayeed** [comment]
> https://docs.docker.com/compose/compose-file/compose-file-v2/#target

That is the documentation of version 2 of compose file, not version 3.

**Comment by shin-** [comment]
Yeah. The option works the same, but obviously it's missing from the v3 docs. Feel free to create an issue for this on the docs repo: https://github.com/docker.github.io

**Comment by ibnesayeed** [comment]
Created a ticket at https://github.com/docker/docker.github.io/issues/6036.
