### ISSUE TITLE
Docker error: ERROR: for balrogui  Container "912cb21d513d" is unhealthy. ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by akve17** [docker/compose#5324]
Helo Everyone,

I am getting an error as follows
ruby@ruby-HP-15-Notebook-PC:~/balrog$ cd ..
ruby@ruby-HP-15-Notebook-PC:~$ cd Desktop
ruby@ruby-HP-15-Notebook-PC:~/Desktop$ cd balrog
ruby@ruby-HP-15-Notebook-PC:~/Desktop/balrog$ docker-compose up
Starting balrog_balrogdb_1
Starting balrog_balrogadmin_1
Starting balrog_balrogpub_1
Starting balrog_balrogagent_1

**ERROR: for balrogui  Container "912cb21d513d" is unhealthy.
ERROR: Encountered errors while bringing up the project.**

I have searched a lot about the above error but dont seem to find anything
related to this.Can somebody please help me out here

**Comment by shin-** [comment]
Please check out the [forums](https://forums.docker.com) for general support!
