### ISSUE TITLE
Feature Request: mount volumes from remote github repo.

### ISSUE THREAD

**Issue by abousselmi** [docker/compose#5327]
Hello,

The idea is to be able to mount a remote github repo just like mounting a local host path. Example:

```
volumes:
      - "github.com/repo/volume:/app/volume"
```

Thanks.

**Comment by shin-** [comment]
This wouldn't be handled at the `docker-compose` level. I believe you'll want to look into a [custom volume plugin](https://docs.docker.com/engine/extend/), and quite possibly will have to build your own.

HTH!
