### ISSUE TITLE
Installation instructions in release notes different from docs

### ISSUE THREAD

**Issue by Tmarty** [docker/compose#5334]
I just installed docker-compose today and found that the command on the release page did not work for me, but the commands in the Linux section in [https://docs.docker.com/compose/install/](https://docs.docker.com/compose/install/) did.

Output of the command from the release page:
```
$ sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose

An error occurred while redirecting file '/usr/local/bin/docker-compose'
open: Permission denied
```

**Comment by shin-** [comment]
Thanks for the report, updated.
