### ISSUE TITLE
-bash: /usr/bin/docker-compose: No such file or directory

### ISSUE THREAD

**Issue by qiulang** [docker/compose#5337]
I installed docker-compose at /usr/local/bin/docker-compose (according to https://github.com/docker/compose/releases)

But when I tried to run it I got error "-bash: /usr/bin/docker-compose: No such file or directory" and I believe the path was set correctly. So how do I  fix it ?

```
root@iZ2zeecbyds24gwmuvqekgZ:/usr# /usr/local/bin/docker-compose --version
docker-compose version 1.17.0, build ac53b73
root@iZ2zeecbyds24gwmuvqekgZ:/usr# docker-compose --version
-bash: /usr/bin/docker-compose: No such file or directory
root@iZ2zeecbyds24gwmuvqekgZ:/usr# echo  $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

**Comment by IamMashed** [comment]
what was the work around? having the same issue.

**Comment by harshitraghav** [comment]
@IamMashed try this
ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose

**Comment by zak905** [comment]
that was helpful @harshitraghav, thanks. Here is what worked for me:
```
pip3 install --upgrade --force-reinstall --no-cache-dir docker-compose && ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
```

**Comment by jabhcl** [comment]
it seems like when snapd removes the docker/docker-compose snap, some clean up is still missing in current shell. at least for executables path resolution logic. pretty boring and annoying issue. respectfully, the symblink solution looks some dirty to me. so i just prefer restart the shell (less dirty)  and bye problem. 

in mi opinion this is a issue with snap. i hope this can help

**Comment by marcusziade** [comment]
Restarting the terminal post-install fixed it for me. Thanks
