### ISSUE TITLE
Install as container for aarch64

### ISSUE THREAD

**Issue by douglasmiranda** [docker/compose#5342]
So, if I'm not wrong, just by executing:

```bash
sudo curl -L --fail https://github.com/docker/compose/releases/download/1.17.0/run.sh -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```
(https://docs.docker.com/compose/install/#install-as-a-container)

It doesn't work on aarch64. So I've created a `Dockerfile.aarch64`, which is almost a copy of `Dockerfile.armhf`, only I'm using "debian:jessie", since 'debian:wheezy' doesn't have a _aarch64_ official image.

That way I was able to run Docker Compose properly on my Rock64 aarch64 / Debian Stretch.

<details>
 <summary>Docker version:</summary>

docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.5
 Git commit:   f4ffd2511c
 Built:        Fri Nov  3 19:26:50 2017
 OS/Arch:      linux/arm64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   f4ffd2511c
 Built:        Fri Nov  3 19:24:59 2017
 OS/Arch:      linux/arm64
 Experimental: false

</details>

<details>
 <summary>Docker Compose version:</summary>

docker-compose version
docker-compose version 1.18.0dev, build unknown
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

</details>

I could make a pull request, if that's ok.

And in this case, I just need to add the file `Dockerfile.aarch64`? Or should I change other files to make the build happen properly?

**Comment by RyanRamchandar** [comment]
Came across your issue while trying to run compose on a Pine64. It would be great to have arm64v8 supported.

**Comment by RyanRamchandar** [comment]
Bump

**Comment by ndeloof** [comment]
ARM architecture is not yet a supported target of the compose release script, but with https://github.com/docker/compose/pull/6908 I guess this is on his way 
@StefanScherer is this something you plan to be working on ?

**Comment by ndeloof** [comment]
Would be nice to have https://hub.docker.com/r/docker/compose being a multi-architecture image, like we do for https://hub.docker.com/_/docker?tab=tags

**Comment by nemchik** [comment]
#6831
