### ISSUE TITLE
Extension Fields Documentation Format Flaw

### ISSUE THREAD

**Issue by qoomon** [docker/compose#5343]
Hi there,

I just noticed a tiny flaw on the Docker compose documentation side in the Extension fields section:

https://docs.docker.com/compose/compose-file/compose-file-v2/#extension-fields

Markdown seems broken in for 3rd code block.
And the indention of 4th code block is wrong.

Kind regards

**Comment by shin-** [comment]
Hi @qoomon 

Thank you for the report - do you mind moving this issue to our [docs repo](https://github.com/docker/docker.github.io)? Thanks!

**Comment by qoomon** [comment]
Didn't know of the existence.so sure

**Comment by shin-** [comment]
Thanks! I'll close this one and follow up there.

https://github.com/docker/docker.github.io/issues/5226
