### ISSUE TITLE
Docker-compose Install: No module named docker.errors

### ISSUE THREAD

**Issue by bainim** [docker/compose#5346]
Hello every one , 
I'm facing this issue when i'm installing docker-compose

OS: ubuntu 14.04

docker --version
 Docker version **17.05.0-ce**, build 89658be
pip freeze | grep docker
**docker==2.5.1**
**docker-pycreds==0.2.1**
**dockerpty==0.4.1**

pip install docker-compose
Installing collected packages: docker-compose
Successfully installed docker-compose-1.17.0

docker-compose --version

Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/errors.py", line 11, in <module>
    from docker.errors import APIError
**ImportError: No module named docker.errors**

Any solution for this error , thank you for your help.

**Comment by bainim** [comment]
As a solution I followed this link:
 https://macay.webhostbug.com/discussion/542/docker-compose-conflict-with-docker-py

**Comment by lsclovecode** [comment]
thanks it works for me!!

**Comment by peterbecich** [comment]
I'm not using pip to install docker-compose.  In my case, installing the Debian package `python-docker` solved a similar problem.  Thanks!

**Comment by cicuz** [comment]
@bainim well the link is dead and nor google nor the internet archive seem to have a copy.. got any tips about how to solve the issue? :)

**Comment by martinnaughton** [comment]
`python-docker` worked for me. I think it might have been to do with me upgrade my default python from python2 to to python 3 that caused this issue. `python-docker` solved it

**Comment by hieudang9** [comment]
> @bainim well the link is dead and nor google nor the internet archive seem to have a copy.. got any tips about how to solve the issue? :)

Just google and found solution, work for me
```
pip3 uninstall docker-py
pip3 uninstall docker-compose
pip3 install --upgrade --force-reinstall --no-cache-dir docker-compose
```
Source: https://hacklove.net/discussion/542/docker-compose-conflict-with-docker-py

**Comment by jimbo8098** [comment]
> > @bainim well the link is dead and nor google nor the internet archive seem to have a copy.. got any tips about how to solve the issue? :)
> 
> Just google and found solution, work for me
> 
> ```
> pip3 uninstall docker-py
> pip3 uninstall docker-compose
> pip3 install --upgrade --force-reinstall --no-cache-dir docker-compose
> ```
> 
> Source: https://hacklove.net/discussion/542/docker-compose-conflict-with-docker-py

Whilst this might resolve the problem, it actually causes a problem with ansible when you use the docker-compose functions. I know this because I build my agent runners through Ansible which spawns the agent runners as a replicated service. The spawn fails if you have docker-compose AND docker-py installed on Python > 2.7.

One could argue that isn't anything we should be worrying about here but I have a feeling the same would be said on Ansible's end.
