### ISSUE TITLE
Provide SHA256 sums for integrity check as downloadable files

### ISSUE THREAD

**Issue by cschol** [docker/compose#5348]
Currently, the SHA256 sums are provided as text on the Releases page.

Would it be possible to provide the checksums as downloadable files for integration in an automated packaging process?

Thanks.

**Comment by shin-** [comment]
Yeah, that's something we can look into.

**Comment by shin-** [comment]
Hi @cschol ,

Is the way we're providing SHA files in the latest RC working for you? https://github.com/docker/compose/releases/tag/1.18.0-rc2

**Comment by cschol** [comment]
Perfect! Thank you very much.
