### ISSUE TITLE
Please provide docker-compose alternative for docker run --runtime=some-runtime argument

### ISSUE THREAD

**Issue by dmitriyse** [docker/compose#5360]
I inspected docker-compose reference and did not find any means to provide "--runtime=some-runtime" argument for starting containers.
Please provide some documentation or add a new feature if it's currently impossible.
Main motivation:
nvidia-docker 2.0 default usage is:
```bash
docker run --runtime=nvidia ...
```

**Comment by flx42** [comment]
@shin- I can help test this.

**Comment by shin-** [comment]
@flx42 Thanks! I'll make sure to ping you on the PR.

**Comment by cuckoohello** [comment]
@shin- @flx42 I have just achived this function, please have a look at my pull request #5405

**Comment by andyneff** [comment]
@cuckoohello @shin- Is there any reason not to do this for the version 3 format too? I've been using the 3.x format on my projects. I just tried this and added this to the 3.5 json schema from docker-compose 1.18.0, and it seems to work as expected for me.

I vote for adding to to version 3 too.

**Comment by shin-** [comment]
@andyneff There's two things about v3. First off, its spec is driven by the [docker/cli](https://github.com/docker/cli) project, so changes need to happen there first before they are backported into Compose. Secondly, we don't want to introduce new parameters in v3 that aren't applicable to [Swarm services](https://docs.docker.com/engine/swarm/how-swarm-mode-works/services/), as this is what the format is specifically designed to do. I don't think this particular option is available yet, hence why we're going to keep it to v2 for the time being.

If you're not transitioning or looking to transition to Swarm mode in the near future, I'd recommend as a general rule to stick to v2 for the time being.

**Comment by andyneff** [comment]
@shin- Ah, thanks for the clarification. I just realized the first point and moved my comment to 5405.

I was naively trying to be "swarm" ready, but without an immediate need to, I think I will take you up on your advice and return to v2.
