### ISSUE TITLE
Feature request docker-compose up to check if build's Dockerfile is newer than image

### ISSUE THREAD

**Issue by pabx06** [docker/compose#5373]
Hello i made some tweaks into my docker file and was surprised that docker up did not build the image of on of my services:

`
version: "3"
services:
  datapoll:
    build:
      context: .
      dockerfile: Dockerfile.datapoll
      args:
        buildno: 1
    image: datapoll
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on:
      - graphite
    links:
      - graphite
`

**Comment by shin-** [comment]
Behaves as advertised. See https://docs.docker.com/compose/reference/build/

**Comment by pabx06** [comment]
Yup docker compose not as smart as a Makefile...
