### ISSUE TITLE
Please how I can limit memory in docker-compose build

### ISSUE THREAD

**Issue by Rikhart** [docker/compose#5374]
¿How I can limit memory in "docker-compose build" command?
I need to setup a limit for building because my tiny droplet is out of memory when run the building process.

Thanks for your answers

**Comment by shin-** [comment]
It's not currently possible with the `docker-compose build` command. Consider building with `docker build` using the `-m` option for the time being.

**Comment by n0tel** [comment]
The same question. Any possibility to limit `docker-compose build` ?
