### ISSUE TITLE
Support docker options cpu-rt-runtime and cpu-rt-period

### ISSUE THREAD

**Issue by waldbaer** [docker/compose#5380]
Hello docker-compose team,

I would be happy to have the docker run options "[cpu-rt-period](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources)" and "[cpu-rt-runtime](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources)" also available in docker-compose.
These options allow modification of the scheduling policy inside containers.

Based on my research these options are available in [docker-py](https://github.com/tz70s/docker-py/commit/d74f1bc3805176af229ae3d2e9e5dbe1f0b40a15), but are not released yet.

Best regards
Sebastian

**Comment by devkid** [comment]
This is in docker-py as of [Dec 14th](https://github.com/docker/docker-py/blame/82e57a4c158c4ff13340a29319c6445d81ddc208/docker/types/containers.py#L122).

Would also like to have this feature.

**Comment by shin-** [comment]
Implemented in #5798

**Comment by rjmccabe3701** [comment]
is there a reason these aren't implemented in the 3.x schemas?
