### ISSUE TITLE
Docker compose does not set MTU while RUN commands are being executed in a Dockerfile

### ISSUE THREAD

**Issue by mctwynne** [docker/compose#5383]
Docker version 17.10.0-ce, build f4ffd25
docker-compose version 1.17.0, build ac53b73
Ubuntu 16.04

If my docker file only contains "FROM ubuntu:16.04" and no RUN commands that require network access everything is OK. If I add a `RUN apt-get update`, or anything that requires network access, it fails. This is because the MTU is not being set during this process. I can watch the MTU of the bridge and veth interface change once I get to the command line of the container, but it doesn't change while the Dockerfile is running. Is this a bug? Is there a way around this?

EDIT: I should include that this issue is with an Ubuntu cloud image that I'm running in a VM. This also fails with:

Docker version 17.09.0-ce, build afdb6d4
docker-compose version 1.16.1, build 6d1ac21
Linux ubuntu 4.4.0-87-generic

**Comment by shin-** [comment]
Does it work if you use the Docker CLI to build instead?

**Comment by mctwynne** [comment]
@shin- Using the docker CLI wouldn't configure my network, though, would it? It looks like the fundamental issue here is that the network I'm creating is not being used until the building of the image is complete.

**Comment by shin-** [comment]
Yes - builds don't take on the parameters of the service they're associated to. If you want to use a custom network for your build's containers, see the [`build.network`](https://docs.docker.com/compose/compose-file/compose-file-v2/#network) option.

**Comment by mctwynne** [comment]
@shin- That explains it. Thank you very much. I will take a look at that option.

**Comment by mctwynne** [comment]
@shin- It doesn't seem to want to use the network I'm creating in my docker compose file. I have to create it with `docker network create`, and use that. Is that right, or am I doing something wrong?

**Comment by shin-** [comment]
Yeah, the build network has to be created first. Compose only creates networks with the `up` command, as the assumption is that the declared networks are required at runtime. With the recent addition of the build network, there's now a possibility for user-created networks to be required at build time as well. We are hesitant to add more features to support this however, as Compose's purpose is not to be a build tool.

**Comment by mctwynne** [comment]
@shin- Is it not reasonable to assume that if a container requires a user-created network for run time it might also require it during build time?

**Comment by shin-** [comment]
99% of the time, that's not the case.
