### ISSUE TITLE
Docker-compose release docs and compose file spec docs inconsistent

### ISSUE THREAD

**Issue by skylerbunny** [docker/compose#5389]
https://docs.docker.com/compose/compose-file/
https://docs.docker.com/compose/compose-file/compose-versioning/
https://docs.docker.com/compose/compose-file/compose-versioning/#version-34

All of the above indicate that the minimum version for docker-compose file format version 3.4 is docker-compose 17.09.0+.

However, references in this repository, at
https://github.com/docker/compose/blob/master/CHANGELOG.md
https://github.com/docker/compose/releases

(Possibly others, I didn't look) say that the minimum Docker Engine version for compose file version 3.4 is 17.06.0+. One or the other is wrong. Please correct this to be consistent one way or the other.

**Comment by shin-** [comment]
Both are correct.

If you are using `docker stack deploy`, support for the 3.4 format was introduced in 17.09. That fact is reflected in the official docs.

However,  when using `docker-compose`, all of the options present in the 3.4 format are available from 17.06, and compatibility can thus be expanded. That is what the `docker-compose` changelogs reflect.

HTH
