### ISSUE TITLE
Question: How to share a Volume between docker and docker-compose

### ISSUE THREAD

**Issue by bhaidar** [docker/compose#5390]
Hi,
I have an shell script that would create a volume using `docker volume create --name volumeName`. 

Then, I am referencing the volume inside a `docker run` container. At this stage I am generating some code and placing it in the mapped directory to the volume.

After that, inside a docker-compose file, I need to reference that volume so that I can use those files generated previously.

Is that doable?

What happens now is that, after the container runs (via docker-compose) the volume is available and the data is there, but while Dockerfile is being run, there is no data in that mapped directory to volume.

I am facing some issues if you can have a look here: https://stackoverflow.com/questions/47414253/cannot-run-script-sh-with-entrypoint-docker?noredirect=1#comment81787374_47414253

Thanks

**Comment by shin-** [comment]
https://docs.docker.com/compose/compose-file/#external

**Comment by bhaidar** [comment]
Thanks @shin- 
The problem is, I cannot access the content of the volume during the build of Dockerfile. I need to run "java Main" inside the Tomcat7 container, however, when I try to do so, the Main.class file is not found in the mapped volume.

**Comment by shin-** [comment]
Hm, I'm not sure I understand what the issue is. You can not mount volumes during a build, if that is what you're trying to do.

**Comment by bhaidar** [comment]
@shin- 
Hummm that could be the problem.

If you check my files, I am trying to compile a Java file inside the Java container. Then copy the .class file into the mounted volume, and then run the java class inside another container created through docker-compose.

How would I solve that? Any idea

Thanks

**Comment by shin-** [comment]
@bhaidar It sounds like multi-stage builds is the feature you're looking for. Check out the docs here: https://docs.docker.com/engine/userguide/eng-image/multistage-build/

Let me know if that helps.

**Comment by bhaidar** [comment]
@shin- 
Thanks for proposing the multistage-build. That's what I needed in fact. It works now.

Regards
Bilal

**Comment by shin-** [comment]
Glad I could be of assistance :+1:
