### ISSUE TITLE
Docker compose up issue "networks have overlapping IPv6"

### ISSUE THREAD

**Issue by smadapathi** [docker/compose#5401]
We are using IPV6 feature for our containers & when we try to upgrade our containers it gives the error
 `networks have overlapping IPv6`

We tried deleting the `/var/lib/docker/network/` but of no use. Can anyone please let us how to fix this?

**Comment by shin-** [comment]
What do you mean by "upgrading your containers"? Can you outline which commands you're running? Also please share the contents of your Compose file

**Comment by shin-** [comment]
Closing this, but feel free to update with the requested info if this is still an issue.

**Comment by bor8** [comment]
I had the same problem after I renamed quite a lot.

```
docker network ls
docker network rm <OLD_NETWORK_NAME>
docker-compose up --force-recreate
```

has helped.
