### ISSUE TITLE
Windows in LCOW can't use `docker-compose pull` linux container

### ISSUE THREAD

**Issue by khs1994** [docker/compose#5402]
`docker-compose.test.yml`

```yaml
version: "3"

services:
  php:
    image: php:7.1.11-fpm-alpine3.4
```

`docker-compose -f docker-compose.test.yml pull`

```bash
Pulling php (php:7.1.11-fpm-alpine3.4)...
7.1.11-fpm-alpine3.4: Pulling from library/php
7.1.11-fpm-alpine3.4: Pulling from library/php
ERROR: no matching manifest for windows/amd64 in the manifest list entries
```

**Comment by khs1994** [comment]
`docker info`

```bash
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.11.0-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.87GiB
Name: DESKTOP-BL71JLU
ID: 3UWM:D4TB:3VEL:NIC5:DPQQ:MHA2:UCVT:SV2C:7AW3:XA7P:DQ3G:YVTV
Docker Root Dir: C:\ProgramData\Docker\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 32
 System Time: 2017-11-26T12:21:10.236342+08:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
Live Restore Enabled: false
```

**Comment by shin-** [comment]
Does it work if you do `docker pull php:7.1.11-fpm-alpine3.4` instead?

**Comment by khs1994** [comment]
Do you have windows 10 Docker run in LCOW?

Can you test it?

**Comment by shin-** [comment]
No, I can't.

Do you have access to two engines, one running Windows containers and the other running Linux containers? Is it possible Compose is hitting the wrong daemon somehow?

**Comment by shin-** [comment]
This seems to be related: https://github.com/docker/for-win/issues/1219

**Comment by khs1994** [comment]
Do you know LCOW?

Maybe LCOW bug!

**Comment by shin-** [comment]
cc @rn Do you have any idea on that one?

**Comment by rn** [comment]
I haven't tried compose yet, but I've started writing tests for LCOW and will add compose tests as well.

LCOW is experimental at the moment and is not yet feature complete (nor fully stable)

**Comment by rn** [comment]
@shin- it might also be a compose issue. LCOW requires/required some docker CLI changes and IIRC compose talks directly docker API. I believe there may be additional CLI changes in the pipeline, so might not be worth chasing that one yet

**Comment by shin-** [comment]
Yeah, we are hitting the API directly. I'll wait until things are more stable then. Thanks.

**Comment by leilei8814** [comment]
I think for many people it's because you are typing 'docker pull ....' directly, the fix is to give the path of .\docker.exe directly, it works for me

**Comment by MarcAurel** [comment]
LCOW seems to be featured in the next Docker for Windows release (17.12). It would be nice to play with LCOW along with docker-compose in this release, isn't it ?
I can help if needed.
