### ISSUE TITLE
compose rename directory

### ISSUE THREAD

**Issue by artemkamolodets** [docker/compose#5406]
Hello, i was renamed the directory that contains the compose yml file (/opt/someproject => /opt/myproject). Now i've got an error on container restart: 

Cannot create container for service <name>: Conflict. The container name "<name>" is already in use by container "f8009f80b97fe12f0e82fdbcef5dd83921f1ed6a406cbaadd361c97c81875c9f". You have to remove (or rename) that container to be able to reuse that name.

Is the docker-compose down\up the one way to apply changes to the project?
Please help.

**Comment by shin-** [comment]
Use `--project-name someproject` to tell Compose you are still working on the same project as before the rename.

**Comment by milgner** [comment]
Might be helpful for others coming here via search engine: one can alternatively set the environment variable `COMPOSE_PROJECT_NAME` instead of passing it via CLI.
