### ISSUE TITLE
Stacktrace / traceback on `sudo docker-compose images`

### ISSUE THREAD

**Issue by chrissound** [docker/compose#5414]
sudo docker-compose images
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 517, in images
    repo_tags = image_config['RepoTags'][0].rsplit(':', 1)
IndexError: list index out of range

**Comment by shin-** [comment]
Thanks for the report! Could you share your Compose file as well?

**Comment by jrabbit** [comment]
I've got this too, going to see if I can make a minimal compose file that'll trigger it

**Comment by jrabbit** [comment]
ok the offending container has a RepoTags entry in its dict that's empty. I don't know if thats out of spec or?
`u'RepoTags': []`

**Comment by shin-** [comment]
Yeah, that makes sense given the error, but I'm curious because pulled images should be tagged, and Compose automatically tags images it builds. So there's a scenario I must be missing. Are you using a sha ID as the `image` value?

**Comment by jrabbit** [comment]
I'm not using a sha as the image value. it's built by compose I'm pretty sure though I'm having some difficulties locating the container outside of inspect

https://gist.github.com/jrabbit/dab888257a06656f0f6e0fd7d4e8327e
