### ISSUE TITLE
compose don't remove old network when recreating images

### ISSUE THREAD

**Issue by jeffguorg** [docker/compose#5416]
expected: old network removed after recreating images
issue: compose don't remove old network when recreating images

reproduction: 
1. ```up``` a swarm with some networks
2. modify network name in docker-compose.yml
3. ```docker-compose up``` again
3.1. (optional) ```docker-compose down```
4. ```docker network ls``` and you will find old networks lays in the corner waiting for you to remove it

version:
```bash
$ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.9.2
 Git commit:   f4ffd2511c
 Built:        Sun Nov 19 18:46:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   f4ffd2511c
 Built:        Sun Nov 19 18:46:37 2017
 OS/Arch:      linux/amd64
 Experimental: false
$ docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.6.1
CPython version: 3.6.3
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
$ uname -a
Linux archlinux 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
$ pacman -Ss docker
community/docker 1:17.10.0-2 [已安装|installed]
    Pack, ship and run any application as a lightweight container
community/docker-compose 1.17.1-1 [已安装|installed]
    Fast, isolated development environments using Docker
```

**Comment by shin-** [comment]
Thanks for the report!

**Comment by mhank** [comment]
Hi, I'm currently an undergraduate student taking a course on virtualization. For our final project, my group of two is required to find open-source issues to work on in our last few weeks. This issue sounded manageable for the time frame and our skill level. Is anybody already working on this and does this sound reasonable?
Thank you

**Comment by gggeek** [comment]
Hello. I have a somewhat similar problem/situation. I am wondering if I should create a separate ticket for that... sorry if this one is the wrong place.

Workflow:
- define network w. specific subnet in a composer v2 file (taken from var in .env file)
- run containers => the network gets built
- stop containers
- change .env file, so that subnet mask is different
- start containers again => the network does not get altered as desired
- stop containers
- `docker network rm` to remove network
- `docker-compose up` => network gets rebuilt with correct netmask, but containers fail attaching to it
- quickest way I found to run containers without rebuilding them: `docker network connect $net $cont` on each one

What bothers me is that this is a long, manual process. I would expect docker-compose to be smarter and fix everything automagically so that I do not have to execute the 2 last steps.
Or maybe I am doing it wrong and there exists already a better sequence of commands to achieve this?

**Comment by ssipos90** [comment]
I'm encountering this as well (Docker version 18.03.0-ce, build 0520e24 / Ubuntu 16)

I wanted to change the docker network IP because it was conflicting with some VPN config, so I added this to the config
```yml
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/22
```
then I ran the following
```
sgc@sgcfil:~/app$ docker-compose up -d
sgc_redis_1 is up-to-date
sgc_sgc-nginx_1 is up-to-date
sgc_sgc-php_1 is up-to-date
sgc_mysql_1 is up-to-date

sgc@sgcfil:~/app$ docker-compose down
Stopping sgc_mysql_1     ... done
Stopping sgc_sgc-php_1   ... done
Stopping sgc_sgc-nginx_1 ... done
Stopping sgc_redis_1     ... done
Removing sgc_mysql_1     ... done
Removing sgc_sgc-php_1   ... done
Removing sgc_sgc-nginx_1 ... done
Removing sgc_redis_1     ... done
Removing network sgc_default

sgc@sgcfil:~/app$ docker-compose up -d
Creating network "sgc_default" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-7486cba995f7 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
sgc@sgcfil:~/app$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
0e5c0164d3c6        bridge              bridge              local
ec7e2ebb7447        host                host                local
7fa98fe1042a        none                null                local

sgc@sgcfil:~/app$ docker-compose up -d
Creating network "sgc_default" with the default driver
ERROR: cannot create network d0bc921b3a131f990e132db6508fcfc0608f378107d0efc4a2bf65a7559edd09 (br-d0bc921b3a13): conflicts with network 7486cba995f70ad35b823aea09e79b911ff1477f1d38aebc181e8890c5519d2c (br-7486cba995f7): networks have overlapping IPv4

sgc@sgcfil:~/app$ sudo service docker stop
[sudo] password for sgc: 
sgc@sgcfil:~/app$ sudo service docker start
sgc@sgcfil:~/app$ docker network prune
WARNING! This will remove all networks not used by at least one container.
Are you sure you want to continue? [y/N] y

sgc@sgcfil:~/app$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
e93fea9ee5a4        bridge              bridge              local
ec7e2ebb7447        host                host                local
7fa98fe1042a        none                null                local

sgc@sgcfil:~/app$ docker-compose up -d
Creating network "sgc_default" with the default driver
Creating sgc_sgc-nginx_1 ... done
Creating sgc_redis_1     ... done
Creating sgc_sgc-php_1   ... done
Creating sgc_mysql_1     ... done

sgc@sgcfil:~/app$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
e93fea9ee5a4        bridge              bridge              local
ec7e2ebb7447        host                host                local
7fa98fe1042a        none                null                local
89eef8ca4bf1        sgc_default         bridge              local
```
And now the IPs are fine but it created downtime...

**Comment by jcalfee** [comment]
How about an option to `--keep-networks` .. The default makes since for non-swarms at least.  But due to my network configuration (VPN) I would like to keep the networks when I'm doing simple upgrades and full restarts.
