### ISSUE TITLE
Add service option to docker-compose down

### ISSUE THREAD

**Issue by summergirl21** [docker/compose#5420]
I saw discussion in other issues of adding an option to docker-compose down to specify a service, similar to `docker-compose stop [SERVICE_NAME]`. Is this something that would be useful?

**Comment by shin-** [comment]
No, that doesn't make any sense for down.

**Comment by shin-** [comment]
To expand:
`down` is a project-level operation. It removes containers, but also networks and (potentially) volumes. How would these additional resources be handled in a single service scenario? There is no good, intuitive answer. 
If people want to remove a single service, `rm -f -s service` already does that.

**Comment by summergirl21** [comment]
Thanks for the explanation!
