### ISSUE TITLE
Staggered container startup

### ISSUE THREAD

**Issue by prdoyle** [docker/compose#5422]
When I start my 30+ containers on my laptop, they all compete with each other for resources.  I don't care what order they start (I'm not asking to be able to control startup ordering, or delay until dependencies are healthy); I just don't want them to all start at once.

Would you consider adding an option to the `scale` command that would make it ramp up gradually, rather than start all containers at once?

**Comment by shin-** [comment]
I believe this is a duplicate of #1828.

**Comment by prdoyle** [comment]
@shin- Agreed.  We can close this.  I'll add a comment there.
