### ISSUE TITLE
PLEASE disable http:// and https:// links to flat text on build: docker-compose.yml

### ISSUE THREAD

**Issue by Gr1dd** [docker/compose#5423]
They arent parsing quotes right at all.....
Spend two hours trying to point the build: to http:// (flat text file) on github but they do some strange parsing to the quotes.

Needs to be EOL for sure.

I just straight up switched to a .git and it worked fine..

**Comment by shin-** [comment]
This is not supported nor has it ever been. I'm not sure what you're asking us to disable?
