### ISSUE TITLE
Version: "3.2" not supported by docker-compose 1.8.0 and docker 17.09.0-ce

### ISSUE THREAD

**Issue by ToniIltanen** [docker/compose#5424]
When running docker-compose -f [filename] config, the following error is returned:

```
ERROR: Version in "./composefile.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
Version is set on the compose file by
Version: "3.2"

Also tried '3.2', but the error remains the same.

```
docker-compose -version
* docker-compose version 1.8.0, build unknown
docker -v
* Docker version 17.09.0-ce, build afdb6d4
```

When deploying the swarm, all services are created normally.
```
docker stack deploy --compose-file composefile.yml --with-registry-auth my-swarm
```

**Comment by albers** [comment]
This is not a bug.
In `docker-compose config`, the composefile is processed solely by `docker-compose`. Docker is not involved at all. You are using a rather outdated version of Compose that does not understand the `3.2` format.

`docker stack deploy --compose-file` is a different thing: Docker parses the compose file and compose is not involved. As your Docker version is current, it supports the `3.2` format.

I suggest you update Compose.

**Comment by ToniIltanen** [comment]
at least in debian, this is the latest version apt returns from the source: 
```deb [arch=amd64] https://download.docker.com/linux/debian stretch stable````
```docker-compose is already the newest version (1.8.0-2).```

**Comment by albers** [comment]
> docker-compose is already the newest version (1.8.0-2).

Linux distributions often package older versions of software. The current version is `1.17.1`.
As Compose is easy to install, I recommend not to use the OS package and install as described in https://docs.docker.com/compose/install/

>  is there another way to validate compose file for the swarm, outside using docker-compose -f file config?

An online service for validation? Don't know. You could use [Play with Docker](https://play-with-docker.com). It has Compose 1.17.0 installed.

**Comment by ToniIltanen** [comment]
or a separate package, for validating the config file. We used the docker-compose config in CD pipeline to validate changes in the compose file, which was installed with ansible from apt. I changed the apt installation to the curl download, and now things work just fine with the docker-compose config.

**Comment by shin-** [comment]
Thank you for taking that one, @albers 

Ideally, we would have an official debian package (and other supported Docker distros as well). Unfortunately that is not something we have been able to dedicate resources to yet, but it's on our radar.

**Comment by soerendip** [comment]
How to install the newest version on Ubuntu??

**Comment by shin-** [comment]
https://docs.docker.com/compose/install/#install-compose
