### ISSUE TITLE
Is there any way to "watch" or "follow" the output of docker-compose ps?

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/compose#5427]
I've a manifest with a lot of services. They have various start up times. They have simple and health-conditional dependencies on one another. I'd like to watch the output of `docker-compose ps` (obviously, following an `up -d`) until they reach some steady state (like Up, Healthy, or Exited)?

I can run the command in a loop or `watch`, but that's pretty nasty. Is there a process/template for a feature request?

**Comment by shin-** [comment]
> but that's pretty nasty.

Why? That's exactly what `watch` is designed to do.

**Comment by AnthonyMastrean** [comment]
You’re right. I looked closer at what watch does and how (clear screen, show diffs, etc.) and it’s perfect. I was under the wrong impression of watch (that it was a dumb loop). 

My mistake!

**Comment by shin-** [comment]
No worries!
