### ISSUE TITLE
Docker SSL: SSLV3_ALERT_BAD_RECORD_MAC

### ISSUE THREAD

**Issue by usamaSaddiq** [docker/compose#5429]
Hey, I am very new to docker and trying to run locally an already set up docker machine.
I am using the docker quickstart terminal since I run Windows Home version.

Here is the output for docker version:
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:39:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
Docker Info: 
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.11.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.100-boot2docker
Operating System: Boot2Docker 17.11.0-ce (TCL 7.2); HEAD : e620608 - Tue Nov 21 18:11:40 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.7MiB
Name: default
ID: JEDH:QQAL:KGIH:NZ5V:WNB6:BZK5:L6YJ:AWML:TOJI:NPUE:THAJ:24MB
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 34
 System Time: 2017-12-02T04:33:05.283740434Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

When I cd into the root of my project and run the following command to setup a machine locally:
```
docker-compose -f docker-compose.build.yml up -d
```

I get the following error:
```
ERROR: SSL error: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:1864)
```

I am a total newbie hence no idea what this means, I tried googling around but no help as far as I am concerned.

Any help would be appreciated.

Cheers

**Comment by shin-** [comment]
What version of Compose are you using? Does it work if you set [`COMPOSE_TLS_VERSION`](https://docs.docker.com/compose/reference/envvars/#compose_tls_version) to `TLSv1_2`?

**Comment by usamaSaddiq** [comment]
docker-compose version 1.16.1, build 6d1ac219

Not sure how to set it.

**Comment by usamaSaddiq** [comment]
Doesn't work after doing:

COMPOSE_TLS_VERSION=TLSv1_2
 This is where my dockerfile resides.

Getting the same error.

**Comment by shin-** [comment]
Sounds like an issue with your openSSL configuration somewhere - Compose should never use SSLv3 in the first place. Try installing a newer version of openSSL and see if that changes anything.

**Comment by usamaSaddiq** [comment]
Updated my ssl but still no luck.

**Comment by usamaSaddiq** [comment]
What do you think might be another cause?

Is it frequent to get such errors?

**Comment by usamaSaddiq** [comment]
I ended up solving the issue by setting 
COMPOSE_TLS_VERSION=TLSv1_2  in my .env file.

The .env file had the same scope as the Dockerfile.
