### ISSUE TITLE
[Bug] Fig is not using `.dockerignore`

### ISSUE THREAD

**Issue by sirwolfgang** [docker/compose#543]
I have tested using `docker build` both within target(`docker build .`) and parallel to my fig location(`docker build web/`). When I use the direct `docker` command, my context builds normally about <8 MBs. When I invoke `fig build` the `web` container building process seems to not use the `.dockerignore` located in my web folder. Leading to `Service 'web' failed to build: write /mnt/sda1/var/lib/docker/aufs/mnt/.../app/log/development.log: no space left on device`

**Comment by davisford** [comment]
Any chance this broke with 1.1.0 release?  I am having an issue with it.

```
$docker-compose --version
docker-compose 1.1.0
```

`docker build -t foo/name .` works fine for me with this `Dockerfile`:

```
FROM mybaseimage/nodejs:latest

RUN mkdir /app
WORKDIR /app

RUN npm install -g gulp pm2 bower

ADD package.json npm-shrinkwrap.json /tmp/
RUN cd /tmp && npm install
RUN cp -a /tmp/node_modules /app/

# copy after building
COPY . /app

# etc.
```

With `.dockerignore`:

```
node_modules/
```

First time images builds `npm install` into `/tmp` dir then copies it into the app, then I add the source, but `.dockerignore` should skip `node_modules` as there are architecture-specific bindings.

This works fine with Docker, but not so much with compose, like this:

```yaml
myapp:
  build: .
  working_dir: /app
  command: node /app/path/to/run
```

`docker-compose up` ends in, e.g. 

```
Error: jsdom/node_modules/contextify/build/Release/contextify.node: invalid ELF header
```

lots of invalid ELF header problems seemingly b/c docker-compose is ignoring `.dockerignore` and copying my whole `node_modules/` from the host to the container -- which are all compile for Mac OS.

Any ideas, or should I open a new issue?

**Comment by maxfi** [comment]
I am having the same issue as @davisford.

```
$docker-compose --version
docker-compose 1.2.0

$docker --version
Docker version 1.5.0, build a8a31ef
```
I'm running boot2docker on Mac OS X.

**Comment by mikexstudios** [comment]
@davisford Try removing the trailing slash from `node_modules/` to `node_modules`. From the source of https://github.com/docker/docker-py/blob/0b78d7a841f123b61a1e03cec7dfc29c92dde0fe/docker/utils/utils.py#L67-L68, it seems like fnmatch does not account for the trailing slash.
