### ISSUE TITLE
Add a compress option to docker-compose build

### ISSUE THREAD

**Issue by pinguinjkeke** [docker/compose#5433]

**Comment by shin-** [comment]
Can you expand on what you mean by that?

**Comment by oppianmatt** [comment]
On docker build there is a `compress` operation which compresses the context sent to the docker daemon.

How do we do the same in compose?

> 

--compress |   | Compress the build context using gzip
-- | -- | --

https://docs.docker.com/engine/reference/commandline/build/#usage

**Comment by proinsias** [comment]
Can we reopen this?
