### ISSUE TITLE
cache_from ignores local cached layers

### ISSUE THREAD

**Issue by kilianc** [docker/compose#5458]
I have compose file with the following:

```yaml
      cache_from:
        - ${IMAGE_NAME}:development
        - ${IMAGE_NAME}:${REVISION}
```
This works great for CI because I pull the development version of that image (which is the most recent) and optionally one tagged with the commit hash. CI uses the layers and builds are fast.

When building locally, I don't have an image tagged as `:development` and every time the commit hash changes (HEAD changes) it does not reuse the layers. Even if I bite the bullet and pull every time (it could take 30+s on a slow connection) I lose all the caching on the layers I changed until next CI run (will tag :development).

Is there a way to tell compose to use the local layers + cache_from? If not is there a smart workaround for this use case?

**Comment by shin-** [comment]
After running some tests, I believe the behavior in Compose matches the behavior from the Docker CLI [1], which indicates to me that if there is an issue, the cause most likely lies at the [buildkit](https://github.com/moby/buildkit) level.

[1]
```
$ export REVISION=asfsgesg
$ docker build -t myimage:$REVISION --cache-from myimage:$REVISION --cache-from myimage:development .
Sending build context to Docker daemon  4.096kB
Step 1/3 : FROM busybox
 ---> 6ad733544a63
Step 2/3 : RUN echo "CACHE MISS"
 ---> Running in bbc1e574020c
CACHE MISS
Removing intermediate container bbc1e574020c
 ---> 1ef175fdabff
Step 3/3 : ADD . /src
 ---> 1fc1a6475482
Successfully built 1fc1a6475482
Successfully tagged myimage:asfsgesg

$ docker build -t myimage:$REVISION --cache-from myimage:$REVISION --cache-from myimage:development .
Sending build context to Docker daemon  4.096kB
Step 1/3 : FROM busybox
 ---> 6ad733544a63
Step 2/3 : RUN echo "CACHE MISS"
 ---> Using cache
 ---> 1ef175fdabff
Step 3/3 : ADD . /src
 ---> Using cache
 ---> 1fc1a6475482
Successfully built 1fc1a6475482
Successfully tagged myimage:asfsgesg

$ export REVISION=aagfdfgsdfsgeee
$ docker build -t myimage:$REVISION --cache-from myimage:$REVISION --cache-from myimage:development .
Sending build context to Docker daemon  4.096kB
Step 1/3 : FROM busybox
 ---> 6ad733544a63
Step 2/3 : RUN echo "CACHE MISS"
 ---> Running in 622cfacd0c8d
CACHE MISS
Removing intermediate container 622cfacd0c8d
 ---> efd8d8d70d82
Step 3/3 : ADD . /src
 ---> 50d4afe6456f
Successfully built 50d4afe6456f
Successfully tagged myimage:aagfdfgsdfsgeee
```

**Comment by kilianc** [comment]
@shin- has this been fixed / addressed?

**Comment by mauricios** [comment]
@kilianc Did you find a workaround for this issue or any other place I can find more info?

**Comment by kilianc** [comment]
@mauricios no, there is no fix other than not using `--cache-from` locally and pulling the `:latest` in ci. At least that's what we're doing
