### ISSUE TITLE
Running server.py and docker-compose up return different enviroments

### ISSUE THREAD

**Issue by jarvisjarb** [docker/compose#5461]
I probably have missed something important but I would kindly appreciate you help. 
After playing with running ` "python server.py"`, I have installed docker-compose, and ran `"docker-compose up"`.
 All of the configuration of CTFD I have previously made (challenges for example) are not showing. Starting the `"server.py"` makes them appear again. 

How can I make this work ? 
(I have already tried using the export and import features, but with no success. What am I missing ?)

**Comment by shin-** [comment]
Not sure what `server.py` refers to, but you'll probably want to ask those questions there if the people responsible for that project set up an expectation that your configuration would translate to `docker-compose`. I'm not personally aware of that project.
