### ISSUE TITLE
Docker-compose start strange behviour when containers are not available

### ISSUE THREAD

**Issue by robininfo-edsx** [docker/compose#5469]
When I use `docker-compose start ` before a `docker-compose up` I obtain the following result:
```
Starting mongo         ... done
Starting elasticsearch ... done
Starting transporter   ... done
Starting pdf           ... done
Starting back          ... done
Starting front         ... done
ERROR: No containers to start
```
This behaviour is pretty strange as the output is contradictory it says that it start all containers but the errors say the opposite.

**Comment by shin-** [comment]
Yes - technically, Compose is reporting that it successfully started the 0 containers (since you haven't run `up`, no containers have been created yet) for that service. I agree that it's confusing.
