### ISSUE TITLE
standard_init_linux.go:187: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by vamsi248** [docker/compose#5473]
can anyone please help me in this error....

i mentioned bin/bash in my sh file also...
still getting format error where i did mistake..
my format for the entrypoint.sh is correct can anyone help me....

#!/bin/bash
set -e

sed -i "s/-Xms512m/$MIN_HEAP_SIZE/g" /opt/artifactory/bin/artifactory.default
sed -i "s/-Xmx2g/$MAX_HEAP_SIZE/g" /opt/artifactory/bin/artifactory.default

echo -e "Starting artifactory..."
./opt/artifactory/bin/artifactory.sh

thanks

**Comment by shin-** [comment]
Not a Compose issue.

**Comment by vamsi248** [comment]
@shin-  can u help me why its not running..  do u have any idea on this error... instead of closing can tell me the reason.
