### ISSUE TITLE
docker  Error response from daemon: pull access denied for portiacrawl, repository does not exist or may require 'docker login'.

### ISSUE THREAD

**Issue by guankin** [docker/compose#5483]
Hi,everyone
I have tried to check all the online resource but I still cant get any solution on this.Hope somebody can help me on this.
I trying on portia and scrapy, I have successfully running portia locally, but then when I try to extract the data,It pop out the error. 
`Error response from daemon: pull access denied for portiacrawl, repository does not exist or may require 'docker login'.`
I want to extract the data into json format.

This is the code that I used and try to extract the data

`docker run -i -t --rm -v aD:/silverlakething/portia/portia/data/projects:rw -v aD:/silverlakething/output:rw -p 9001:900
1 portiacrawl /silverlakething/portia/portia/data/projects/BigData www.lazada.com.my -o /silverlakethin
g/output/www.lazada.com.my.json`

This is the Error 
```
Unable to find image 'portiacrawl:latest' locally
D:\silverlakething\Docker Toolbox\docker.exe: Error response from daemon: pull access denied for portiacrawl, repository does not exist or may require 'docker login'.
See 'D:\silverlakething\Docker Toolbox\docker.exe run --help'.
```

docker images the repository is running. 
Login is successful.

When I run docker images
```
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
scrapinghub/portia   latest              f453caf755d4        4 weeks ago         1.12GB
```
My laptop is Window 10 home, currently using docker toolbox.
Here is my docker version
```
Client:
 Version:      17.10.0-ce
 API version:  1.32 (downgraded from 1.33)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:00:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

So how can I solve this?Please help

**Comment by shin-** [comment]
This is not a Compose issue - please consider using the [forums](https://forums.docker.com) for support in the future.

Your problem is that your command is missing the image name before the command. https://docs.docker.com/engine/reference/run/

**Comment by sixjac** [comment]
Docker blows

**Comment by shin-** [comment]
@sixjac You okay there mate? Show us on the doll where the big bad container hurt you.

**Comment by sanketmore86** [comment]
Thank you for help @joffrey your comment helped.

**Comment by zubiks10** [comment]
Can anyone shade some light on this 
Error response from daemon: pull access denied for postgresql, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ndf14685** [comment]
sudo service docker start

**Comment by josser** [comment]
@zubiks10 the error message is really confusing because the reason is in image name. 
I see you are trying to run postgres but correct image name for it is 'postgres' not 'postgresql'

**Comment by sjindal94** [comment]
Should add, "Reconfirm the image name in the error log"

**Comment by mjunaid192846** [comment]
Error response from daemon: pull access denied for redis-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'




can anyone help me in this

**Comment by thaJeztah** [comment]
@mjunaid192846 If you don't have an image with that name locally, docker will try to pull it from docker hub, but there's no such image on docker hub (https://hub.docker.com/_/redis-server), which is causing the error.

**Comment by fokosun** [comment]
Its funny the things that can lead to this error. In my case I didn't provide any env variable even though I had the -e flag

**Comment by Swapnnil** [comment]
I just started learning docker and was following docker-curriculum.com tutorials for beginners and when run the command to run the container on the desired port, the command gave me this error. I removed the name flag and tried using it with "p" instead of "P". If someone is looking because of the same tutorial, then this should help.

**Comment by leegee** [comment]
> @sixjac You okay there mate? Show us on the doll where the big bad container hurt you.

Why so toxic? Is this the 'docker-compose' community spirit? What a business.
