### ISSUE TITLE
Compose isn't supposed to support 'credential_spec' key in V3.3

### ISSUE THREAD

**Issue by pluque** [docker/compose#5488]
Hi guys,

I'm using `docker run security-opt "credentialspec...` without any issues but when I try to use it in docker-compose yaml file, I get the following warning: `WARNING: Some services (wcm) use the 'credential_spec' key, which will be ignored. Compose does not support 'credential_spec' configuration - use `docker stack deploy` to deploy to a swarm.`

Did I miss something in the [documentation](https://docs.docker.com/compose/compose-file/#credential_spec)?

```
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:46:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:55:16 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Comment by pluque** [comment]
Nevermind

As per [release notes](https://docs.docker.com/release-notes/docker-compose/):

`COMPOSE FILE VERSION 3.3
Introduced version 3.3 of the docker-compose.yml specification. This version requires to be used with Docker Engine 17.06.0 or above. Note: the credential_spec and configs keys only apply to Swarm services and will be ignored by Compose`

**Comment by artisticcheese** [comment]
Why is this closed and why is it not supported? It shall be supported when running locally as well as running in swarm mode.

**Comment by pluque** [comment]
Well I closed it because it was specified in release notes. That said, you are right to ask why is it not supported.

**Comment by artisticcheese** [comment]
Well I'd rather not to create a new case and just let this one escalate as a feature missing. Can you reopen it.

**Comment by pluque** [comment]
Sure np!

**Comment by shin-** [comment]
One should be able to specify credentialspec through the `security_opt` configuration option, e.g.
```yaml
security_opt:
  - credentialspec=file://path/to/file
```

But yeah, looks like we should be able to convert data inside the `credential_spec` field to something that the container API will support.

**Comment by abriel** [comment]
Hi,
the same questions is about `configs`.
Notes per documentation don't say that it is not supported by `docker-compose`: https://docs.docker.com/compose/compose-file/#configs . 
Only after updating configuration, validation (`docker-compose config -q`) says it cannot be used. Frustrating a bit.
And if we can use `--config` during service creation with pure docker (per docs):
```
docker service create \
     --name nginx \
     --secret site.key \
     --secret site.crt \
     --config source=site.conf,target=/etc/nginx/conf.d/site.conf,mode=0440 \
     --publish published=3000,target=443 \
     nginx:latest \
     sh -c "exec nginx -g 'daemon off;'"
```
why we cannot support it in compose file for `docker-compose`?
Thanks!
