### ISSUE TITLE
Network Alias Name Won't Change

### ISSUE THREAD

**Issue by dmc2015** [docker/compose#5492]
I am aliasing a service that worked. I named it es.dev. However because of decisions made by Google it isn't a good idea.
 - https://iyware.com/dont-use-dev-for-development/
- https://tech.slashdot.org/story/17/09/18/192227/chrome-to-force-domains-ending-with-dev-and-foo-to-https-via-preloaded-hsts
- https://github.com/basecamp/pow/issues/545

The issue is that the alias won't change now from es.dev now.

I tried re-pulling the image, that didn't seem to work and it didn't look like it really got rid of all the images. Regardless I think it should still be able to pick up the new information in the composition file.

http://es.devx:9200 should load, but doesn't.
http://es.dev:9200 still loads (I am now testing it in Firefox), I also changed the cluster_name to see if that would update.
It didn't.

```dockerfile
es:
    container_name: es
    hostname: es.devx
    networks:
      new_net:
        aliases:
          - es.devx
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    environment:
      - cluster.name=docker-clusterx
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    command: elasticsearch
    ports:
      - "9200:9200"
```

**Comment by shin-** [comment]
@dmc2015 Did you run `docker-compose up` after updating the configuration?

**Comment by dmc2015** [comment]
I have been doing ```docker-compose up es```

**Comment by shin-** [comment]
Okay - you probably also need to update the `/etc/hosts` file on your host. `aliases` only affect DNS on the internal network, so it won't affect what Firefox sees.

**Comment by dmc2015** [comment]
While this gets my domain to return the end point, it still looks like it is running on a fixed (older version) of my compose file because the cluster_name should be "docker-clusterx"

FYI, the entry I added to /etc/hosts was
```
127.0.0.1       es.devx
```

The endpoint returns, notice the cluster_name
```
{
  "name" : "ldMK7kq",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "q4l4C_nZQTSfUCT5649Ckw",
  "version" : {
    "number" : "6.1.0",
    "build_hash" : "c0c1ba0",
    "build_date" : "2017-12-12T12:32:54.550Z",
    "build_snapshot" : false,
    "lucene_version" : "7.1.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by shin-** [comment]
What do you see if you run `docker-compose exec es env`?

**Comment by dmc2015** [comment]
@shin- 
```
PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=es
TERM=xterm
cluster.name=docker-clusterx
ES_JAVA_OPTS=-Xms512m -Xmx512m
bootstrap.memory_lock=true
ELASTIC_CONTAINER=true
JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
HOME=/root
```

**Comment by shin-** [comment]
As you can see, `cluster.name=docker-clusterx` matches what is present in your Compose file, so the container has successfully been recreated with the new configuration. If you expected those changes to be reflected in ElasticSearch instantaneously, I'd contend that that is an ES issue and has nothing to do with Compose per se.

HTH!
