### ISSUE TITLE
parsing env_file inconsistencies compared to sh

### ISSUE THREAD

**Issue by abernier** [docker/compose#5494]
Considering that `toto.env` file:

```sh
toto_foo0=foo
toto_foo1=fo o
toto_foo2=fo\ o
toto_foo3="fo o"
toto_foo4='fo o'
```

Let's verify we can `source` that file and retrieve values from `set`:

```sh
$ sh -c '. toto.env && set |grep ^toto_'
toto.env: line 2: o: command not found
toto_foo0=foo
toto_foo2='fo o'
toto_foo3='fo o'
toto_foo4='fo o'
```

Everything is ok, except for the first line `toto_foo1` where `source` does not accept value containing space without being `"`quoted`"`

---

Let's now try with `docker-compose-toto.yml` loading that same `toto.env` file using `env_file` and display them using `env`:

```yaml
version: '3'
services:
  toto:
    image: alpine
    env_file: toto.env
    command: sh -c 'env |grep ^toto_'
```

```sh
$ docker-compose -f docker-compose-toto.yml up toto
toto_1  | toto_foo0='foo'
toto_1  | toto_foo1='fo o'
toto_1  | toto_foo2='fo\ o'
toto_1  | toto_foo3='"fo o"'
toto_1  | toto_foo4=''"'"'fo o'"'"
```

- No complain about `toto_foo1` here
- `toto_foo2` value is here `'fo\ o'` rather than `fo o` previously
- `toto_foo3` and `toto_foo4` are kinda "overescaped"

If we check using `docker-compose config`, it even different:

```sh
$ docker-compose -f docker-compose-toto.yml config
services:
  toto:
    command: sh -c 'env |grep ^toto_'
    environment:
      toto_foo0: foo
      toto_foo1: fo o
      toto_foo2: fo\ o
      toto_foo3: '"fo o"'
      toto_foo4: '''fo o'''
    image: alpine
version: '3.0'
```

---

My system environment:
```sh
$ docker --version
Docker version 17.06.2-ce, build cec0b72

$ docker-compose --version
docker-compose version 1.14.0, build c7bdf9e

$ uname -a
Darwin Antoines-MacBook-Air.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by shin-** [comment]
Hi!

This matches the behavior of `--env-file` in Docker engine, which is what `env_file` is trying to emulate. 
```
$ docker run --env-file toto.env busybox sh -c 'set | grep ^toto_'
toto_foo0='foo'
toto_foo1='fo o'
toto_foo2='fo\ o'
toto_foo3='"fo o"'
toto_foo4=''"'"'fo o'"'"
```

**Comment by abernier** [comment]
Hi @shin, thanks for your quick answer.

I understand this behavior is the same as `docker run` but is it expected even though ?

So many '"'"'"'quotes"'"'"' seem weird to me and lead to unexpected results.

Thank you

**Comment by shin-** [comment]
@abernier Whether this is the correct behavior for Docker is a question you'll want to ask on the [engine](https://github.com/moby/moby) repo. As far as the Compose project is concerned, we're mostly interested in providing a consistent behavior.

HTH!
