### ISSUE TITLE
compose -d and --timeout cannot be combined.

### ISSUE THREAD

**Issue by josephjoice** [docker/compose#5501]
I am using pip distribution. This started after the release of 1.18.0

**Comment by shin-** [comment]
[Changelog](https://github.com/docker/compose/releases/tag/1.18.0)
> The CLI now explicit prevents using `-d` and `--timeout` together
> in `docker-compose up`

Those flags were never compatible, `--timeout` was simply being ignored up until now.

**Comment by josephjoice** [comment]
oh my bad @shin- Thanks for the information. I am closing this.

**Comment by shin-** [comment]
No worries!

**Comment by NicolasDorier** [comment]
@shin- question: How does `--timeout` was ignored? When I do `docker-compose up` I expect that modified contianers get restarted. Who says restarted says that it need to be shutdown (with timeout).

**Comment by NicolasDorier** [comment]
Oh I think it has been reverted in new versions.
