### ISSUE TITLE
Make docker-compose fail when an undefined environment variable used in a compose file.

### ISSUE THREAD

**Issue by aschatten** [docker/compose#5505]
Right now, if a compose file references an undefined environment variable, `docker-compose` prints a warning and defaults it's value to an empty string, as described [here](https://docs.docker.com/compose/compose-file/#variable-substitution). 
This may not always be the desired approach and can mask a failure in continuous deployment environment. 

I think there are 2 backward compatible ways to address this:
1. Add a option to enable strict config validation. E.g. `docker-compose config --strict`
2. Add support for `${VARIABLE?err_msg}` and `${VARIABLE:?err_msg}` substitution syntax.

**Comment by washtubs** [comment]
+1, but why does there need to be customizable error messages? What's wrong with "VARIABLE is undefined"?

**Comment by aschatten** [comment]
@washtubs there does not need to be a customizable error message, but if 2nd option is chosen then it is consistent with the existing syntax for defaults and allows to have a custom error message.

**Comment by thaJeztah** [comment]
Wouldn't this be better handled by the application/service itself? The same container could also be started outside of compose, in which case it would also have to deal with the missing environment variables

**Comment by aschatten** [comment]
@thaJeztah
> Wouldn't this be better handled by the application/service itself?
A variable is not necessarily passed to the application. For example a variable can be a name of an image or a tag.

**Comment by shin-** [comment]
I've got a potential implementation in #5531 - let me know what you think!

**Comment by thaJeztah** [comment]
Docs for this were added in https://github.com/docker/docker.github.io/pull/5826

**Comment by carolinux** [comment]
Thanks for implementing this, having the option to fail fast in this case is very useful.
