### ISSUE TITLE
Docker-compose fail 

### ISSUE THREAD

**Issue by Diinova** [docker/compose#5515]
Hello,

When I enter the command docker-compose up I'm getting this error:
`Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 121, in perform_command
  File "compose\cli\main.py", line 954, in up
  File "compose\cli\log_printer.py", line 105, in run
  File "compose\cli\log_printer.py", line 109, in write
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose`

![image](https://user-images.githubusercontent.com/31722074/34398302-c33d34c4-ebb8-11e7-84f4-40e327cb8b8c.png)

**My compose.yml is:**

```version: '2'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: pspdfkit
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pspdfkit
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  pspdfkit:
    image: docker.pspdfkit.com/pspdfkit:latest
    environment:
      PGUSER: pspdfkit
      PGPASSWORD: password
      PGDATABASE: pspdfkit
      PGHOST: db
      PGPORT: 5432

      # Activation key for your PSPDFKit Server installation
      ACTIVATION_KEY: yyyyyyyyyyyyyyyyyyyy

      # Secret token used for authenticating API requests.
      API_AUTH_TOKEN: secret

      # Base key used for deriving secret keys for the purposes of authentication.
      SECRET_KEY_BASE: secret-key-base

      # Public key used for verification of JWTs from web clients. It has to be in the PEM format.
      JWT_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        yyyyyyyyyyyyyyyyyyyyyyyyyy
        -----END PUBLIC KEY-----
      JWT_ALGORITHM: RS256

      # Credentials to access the admin dashboard
      DASHBOARD_USERNAME: dashboard
      DASHBOARD_PASSWORD: secret
    depends_on:
    - db
    restart: always
    ports:
      - "5000:5000"
    volumes:
    - asset_storage:/srv/asset_storage

volumes:
  pgdata:
  asset_storage:
```

This is the versions I am using:
![image](https://user-images.githubusercontent.com/31722074/34398758-5cae83ee-ebbc-11e7-8306-9baf48d29659.png)

**I already try:**
- Disable Win32 Long Paths in Windows 10

But still is working, any idea?

**Comment by shin-** [comment]
https://github.com/docker/compose/issues/5019#issuecomment-351495225

**Comment by Diinova** [comment]
I forget say I tried the command in Git-Bash: MINGW64, CMD terminal, Powershell terminal.

I also tried different versions of phyton, and docker-compose

Receiving the same error 

![image](https://user-images.githubusercontent.com/31722074/34428066-e1cafc66-ec83-11e7-90e4-e4a7869c1cd0.png)
