### ISSUE TITLE
mount volumes at the same path in the container that in the host

### ISSUE THREAD

**Issue by mathroc** [docker/compose#5517]
I’d like to to something like that:

```json
services:
  tool:
    volumes:
      - ./app:./app
    working_dir: $PWD
```

so that I can use the tool from any directory and :
* the tool will print paths that are valid on the host
* I can pass relative path to the `docker-compose run tool` and it’ll work automatically

this is not an option: 

```json
services:
  tool:
    volumes:
      - $PWD/app:$PWD/app
    working_dir: $PWD
```

because it would mount only the current directory lots of tools needs the whole project (eg: to read configuration file at the project root)

**Comment by shin-** [comment]
I don't think that's something we're interested in supporting. It's very clear that it's an antipattern that will only cause you more problems in the long run.
