### ISSUE TITLE
Strange caching bug manifests itself when building image from remote git repo

### ISSUE THREAD

**Issue by pulkitsinghal** [docker/compose#5520]
### Problem
An image which I had built the day before ... failed to build while complaining about not being able to `COPY` some content because the target directory already existed.

### My Guess
I think this is a bug that occurs because the cache or something is messed up and is reusing a version of the `intermediate container hash` from the previous day which means the directory which should not yet exist when building the image ... already does exist and the build fails.

I suspect that this may be limited to the scenario when someone runs a second build from a remote git repo.

### Workaround
After I pruned the previous images and intermediate hashes, the image was built fine.

### Versions of docker used
```
$ docker -v
Docker version 17.05.0-ce, build 89658be
$ docker-compose -v
docker-compose version 1.16.1, build 6d1ac21
```

### Steps to Reproduce

1. Clone a repo (for example in my case https://github.com/ShoppinPal/node-worker)
1. Let it auto build when you run `docker-compose up`
1. Switch to another directory
1. Here create a docker-compose.yml that builds from **same** repo but remotely (without cloning)

    ```
    version: '2'
    services:
      worker-framework:
        build: https://github.com/ShoppinPal/node-worker.git
    ```
1. Run `docker-compose up` and the build will fail this time because of the bug I described above

**Comment by shin-** [comment]
Hi @pulkitsinghal,

Unfortunately, we don't support building from remote git repos. Thank you for your understanding.
