### ISSUE TITLE
docker-compose -f sawtooth-default.yaml up not completing

### ISSUE THREAD

**Issue by malkani-kamal** [docker/compose#5522]
Hi 
I have installed cURL, Node.js, docker toolbox on windows 7 and now i am trying to build the hyperledger sawtooth image using 

docker-compose -f sawtooth-default.yaml up

This command is not at all completing. It is stuck at the last stage 
sawtooth-validator-default : Now building on top of block ........

I tried waiting till long long hours but still not completing.

I tried using
docker-compose -f sawtooth-default.yaml down
docker-compose -f sawtooth-default.yaml up --force-recreate

Can anyone let me know why not able to build the sawtooth image.

**Comment by shin-** [comment]
Not a Compose issue. Please contact the maintainer of sawtooth instead.
