### ISSUE TITLE
Can docker-compose ps show health status?

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/compose#5525]
The Docker CLI can show health status

```
$ docker container ls --filter name=example_example_1
CONTAINER ID        IMAGE            COMMAND                  CREATED             STATUS                 PORTS                                     NAMES
6e9eef9909f7        example:latest   "nginx -g 'daemon ..."   5 hours ago         Up 5 hours (healthy)   80/tcp, 443/tcp, 0.0.0.0:8080->8080/tcp   example_example_1
```

But, the Docker Compose CLI does not

```
$ docker-compose ps example
         Name            Command          State                       Ports
------------------------------------------------------------------------------------------------
example_example_1   nginx -g daemon off;   Up      443/tcp, 80/tcp, 0.0.0.0:8080->8080/tcp
```

It might be nice to display the same health status, especially for those of us using Compose 2.1 and the depends_on / condition / service_healthy feature.

**Comment by AnthonyMastrean** [comment]
It looks like this method, [`human_readable_state`](https://github.com/docker/compose/blob/master/compose/container.py#L123), would need to be enhanced to display health status if this service has a HEALTHCHECK defined. As [stated](https://github.com/docker/compose/blob/master/compose/container.py#L16) at the beginning of the class, the dictionary of internal state is coming from the Docker engine API ([Inspect a container](https://docs.docker.com/engine/api/v1.35/#operation/ContainerInspect)).

```
GET /containers/{id}/json
```

But, I'm not quite sure that API endpoint returns the current health status. I don't see any "health" properties, even on the `State` (although, maybe the example is incomplete).

```json
  "State": {
    "Error": "",
    "ExitCode": 9,
    "FinishedAt": "2015-01-06T15:47:32.080254511Z",
    "OOMKilled": false,
    "Dead": false,
    "Paused": false,
    "Pid": 0,
    "Restarting": false,
    "Running": true,
    "StartedAt": "2015-01-06T15:47:32.072697474Z",
    "Status": "running"
  },
```

Perhaps, we can use the same call as the [`service_healthy`](https://github.com/docker/compose/blob/ddbc9e30b0608ebdacb333f56f2519a4e26d4db6/compose/service.py#L1117) feature,  to get the container's health status directly from `inspect` and construct the new status string?

**Comment by dihmuzikien** [comment]
Hi, can I try tacking this issue?

**Comment by dihmuzikien** [comment]
@AnthonyMastrean Looks like `inspect` API endpoint does return Health status if "healthcheck" is specified for the container.

```
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 6997,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2018-01-29T00:08:00.1885465Z",
        "FinishedAt": "0001-01-01T00:00:00Z",
        "Health": {
            "Status": "starting",
            "FailingStreak": 0,
            "Log": []
        }
    }
```
I could try adding `health` property for container object and construct new status string from there.

**Comment by dihmuzikien** [comment]
Should I also add `time` portion of the status string as well? Like `Up for ......... (health)`, or just `Up (health)` is fine?

**Comment by AnthonyMastrean** [comment]
I think adding _just_ the health status is OK for now. I don't know if it's Compose's intent to mirror the _entire_ status string.

Note that the Docker CLI shows a bit of a custom message if the healthcheck is still inside of the "starting" period. The health status is technically just `starting`, but it shows `health: starting`. You _might_ replicate this behavior, at least.

```
STATUS
Up Less than a second (health: starting)
```

**Comment by dihmuzikien** [comment]
I created a [Pull Request](https://github.com/docker/compose/pull/5643) for this change. Decided to go with similar behavior as @AnthonyMastrean mentioned above regarding the `health: starting`. Did not add the `Up for ....`.
