### ISSUE TITLE
Long Syntax example does not work with 2.3

### ISSUE THREAD

**Issue by egee-irl** [docker/compose#5529]
https://docs.docker.com/compose/compose-file/compose-file-v2/#long-syntax

Before anybody says that the long-syntax only works with 3.2, the documentation also clearly states:

> Added in version 2.3 file format.

I am using the 2.3 file format because I need to control the resource usage without deploying via Swarm (which is not possible with 3.x).

This example does **not** work with Compose 2.3:

version: "2.3"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: mydata
        target: /data

The following error is returned

``services.web.volumes contains an invalid type, it should be a string``

If the long syntax does not work with 2.3, the documentation should be updated to reflect this.

**Comment by shin-** [comment]
What version of Compose are you using? You'll need 1.18.0 for this to work (the documentation assumes you're always using the latest release)

**Comment by egee-irl** [comment]
I am running 1.17. however the documentation claims that version 1.16.0+ is required - https://docs.docker.com/compose/compose-file/compose-versioning/#version-23

**Comment by egee-irl** [comment]
I can confirm that upgrading to 1.18.0 fixed it. The documentation still needs to be changed but, 2.3 does work with the correct docker-compose version.

**Comment by shin-** [comment]
We constantly add new fields to previous Compose schemas. Version 2.3 was first introduced in 1.16.0, then updated in 1.17.0 and 1.18.0. Said changes can be found in the [release notes](https://docs.docker.com/release-notes/docker-compose/).

As stated, the [Compose file reference](https://docs.docker.com/compose/compose-file/compose-file-v2/) applies exclusively to the latest version of Compose (in this case, 1.18.0).
