### ISSUE TITLE
Pre-commit hook failing 

### ISSUE THREAD

**Issue by johnharris85** [docker/compose#5536]
Trying to submit a PR (as have done a couple times before) and now I'm getting pre-commit hook failures:

    usage: pre-commit [-h] [-V] {install,uninstall,clean,autoupdate,run,help} ...
    pre-commit: error: unrecognized arguments: --config

Anyone else seeing anything similar?

**Comment by shin-** [comment]
Your pre-commit might be out of date. Try removing the `.tox` directory and committing again. You can also use the `--no-verify` flag.

**Comment by johnharris85** [comment]
Thanks @shin-, removing `.tox` didn't work so using `--no-verify` for now. Will update the PR then try to fix this later.
