### ISSUE TITLE
Question about 1.10.1 release notes

### ISSUE THREAD

**Issue by sanjaysiddhanti** [docker/compose#5539]
From the [v1.10.1 release notes](https://github.com/docker/compose/releases/tag/1.10.1), one of the notes is "Fixed a bug where Compose would occasionally crash while streaming logs when containers would stop or restart". 

Can you please post the initial issue that has more details about this bug, or elaborate on it here? Sorry if this is discoverable somewhere - I searched the past issues in this repo and looked at the code diff for that version before posting here.

I'm running `docker-compose` 1.9.0 and think that I may be seeing this issue. I get an exception with the below traceback unpredictably about once per day:

```
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 150, in tail_container_logs
  File "compose/cli/log_printer.py", line 181, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 455, in wait
  File "site-packages/docker/utils/decorators.py", line 47, in inner
  File "site-packages/docker/client.py", line 135, in _post
  File "site-packages/requests/sessions.py", line 522, in post
  File "site-packages/requests/sessions.py", line 475, in request
  File "site-packages/requests/sessions.py", line 596, in send
  File "site-packages/requests/adapters.py", line 473, in send
ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))
```

Thank you!

**Comment by johnharris85** [comment]
Maybe this one? - #4090

**Comment by shin-** [comment]
@johnharris85 is correct. docker/docker-py#1389 is the related code change. Your error seems different - It looks like the Docker Engine gets restarted and the UNIX socket removed, causing the connection to be interrupted. I'd check the logs of the docker daemon to see if this is due to a periodic failure. Alternatively, you might have a cron job that restarts the engine for some reason?

**Comment by sanjaysiddhanti** [comment]
Thanks @shin-. I checked the docker daemon logs and see no evidence of the docker engine restarting. To sanity check that I'm looking at the right logs, I manually restarted the docker engine (using `sudo service docker restart`) and do see this in the log.

If the Docker engine isn't restarting, do you have any other ideas as to what might be causing the `ConnectionError` mentioned above?

**Comment by shin-** [comment]
> I manually restarted the docker engine (using `sudo service docker restart`) and do see this in the log.

To me this indicates that something (or someone?) is probably doing that on your host on a regular basis.

To be clear, it's normal for Compose to error out if the connection with the engine is severed while it's streaming logs - there's no reasonable way at the client level to maintain functionality if the connection is aborted.

From there however, there's different paths you can take:

1. Find out the script or action that is causing the daemon restarts, and stop it. This should ensure that Compose will continue to stream the logs as long as the connection is maintained. You might still have crashes, in which case having a script that recovers and restarts logging is probably a good idea.
2. If you're not necessarily interested in streaming logs 24/7 and just want your containers to be up and running, you can just start your application with `docker-compose up -d` and not worry about abruptly exiting. I highly recommend having a [restart policy](https://docs.docker.com/compose/compose-file/compose-file-v2/#restart) set for your containers so they can recover if the engine gets restarted (or the application running inside the container errors out)
You can still access the full logs for your application at any point using `docker-compose logs`.
