### ISSUE TITLE
client is newer than server

### ISSUE THREAD

**Issue by srinivasankrish** [docker/compose#5543]
### Client:
```
Version:      1.11.0
API version:  1.23
Go version:   go1.5.4
Git commit:   4dc5990
Built:        Wed Apr 13 18:34:23 2016
OS/Arch:      linux/amd64
```
 
### Server:
```
Version:      1.11.0
API version:  1.23
Go version:   go1.5.4
Git commit:   4dc5990
Built:        Wed Apr 13 18:34:23 2016
OS/Arch:      linux/amd64
```

## Docker Compose Version

```
docker-compose version 1.17.0, build ac53b73
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

I have tried setting 
`DOCKER_API_VERSION=1.23`

I use the command 
`docker-compose pull --parallel`

I use version 3 in compose.yaml

I get the error
`client is newer than server (client API version: 1.25, server API version: 1.23)`.

The docker compose pull command does not give any way to set the client version internally. Also setting the DOCKER_API_VERSION environment variable is not helping. Can anybody please help?

**Comment by thaJeztah** [comment]
Does it work if you use the 2 format? 

The 3 format may use API features that are only available in recent versions of Docker


I'd highly recommend updating your Docker. Docker 1.11 has reached end of life in July 2016, and hasn't been maintained since then; that version has known vulnerabilities (one of which a vulnerability in runc that allows processes to escape containers)

**Comment by srinivasankrish** [comment]
@thaJeztah I tried it with Version 2 and it worked. I take your feedback on Docker Version. Will take action on this. Thanks for your suggestion.

**Comment by shin-** [comment]
The only thing I'll add is that you can set [`COMPOSE_API_VERSION`](https://docs.docker.com/compose/reference/envvars/#compose_api_version) to use a specific API version. As @thaJeztah points out though, this will still fail if you're using features that aren't available for your version of the Docker Engine.
