### ISSUE TITLE
Interpolate env variables in env_file

### ISSUE THREAD

**Issue by BjornMelgaard** [docker/compose#5544]
Example:

PWD is interpolated when I'm using `environment`
```
# docker-compose
  tests_runner:
    environment:
      STORAGE_DIR: ${PWD}/storage-tmp
      UPLOADS_DIR: ${PWD}/public/uploads-tmp
      CARRIERWAVE_CACHE_DIR: ${PWD}/tmp/uploads-tmp
```

I expect that it would interpolate variables when I'm using `env_file` too

```
# docker-compose
  tests_runner:
    env_file:
      - ./some.env

# some.env
STORAGE_DIR=${PWD}/storage-tmp
UPLOADS_DIR=${PWD}/public/uploads-tmp
CARRIERWAVE_CACHE_DIR=${PWD}/tmp/uploads-tmp
```

**Comment by shin-** [comment]
Unfortunately, that would create a discrepancy with how the `--env-file` option works in the [docker CLI](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e-env-env-file), which we're trying to avoid.

HTH!
