### ISSUE TITLE
Erroneous denial of tmpfs mounts on MacOS

### ISSUE THREAD

**Issue by smarschner** [docker/compose#5554]
We use docker-compose to run an app consisting of several services for testing and development.  The mount setup we have been using for some time involves a bind mount to bring source code into the container, with `tmpfs` mounts over certain subdirectories of that mount to bring in files from the docker build process that should not be shared with the host or persist across builds (for example `node_modules` and complied executables).

When we upgraded to Docker 17.12 and docker-compose 1.18, this started failing with the error `The path [...] is not shared from OS X and is not known to Docker.` naming the path to the `tmpfs` mount in the container's filesystem.  This seems wrong and disagrees with Docker's behavior.

A minimal reproduction is:

```
$ cat docker-compose.yml 
version: "3.2"
services:
  tmpfstest:
    image: ubuntu:latest
    volumes:
    - type: tmpfs
      target: /foo/bar
    command: sleep 600
```

which fails with these errors:

```
[~/tmp] $ docker-compose up
Creating tmp_tmpfstest_1 ... error

ERROR: for tmp_tmpfstest_1  Cannot start service tmpfstest: Mounts denied: 
The path /foo/bar
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.

ERROR: for tmpfstest  Cannot start service tmpfstest: Mounts denied: 
The path /foo/bar
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERROR: Encountered errors while bringing up the project.
```

The Docker invocation 

```
docker run -it --rm --mount type=tmpfs,target=/foo/bar ubuntu bash
```

works as expected (inside the container you can see `/foo/bar` and write into it but the contents do not appear in the host filesystem).

A workaround is to actually create the directory `/foo` on the host and add it to the whitelist using the Docker Preferences UI, but this is clunky and has to become part of the procedure for all developers to get the system up an running on a fresh Docker installation.

Version info attached.

**Comment by smarschner** [comment]
[version-info.txt](https://github.com/docker/compose/files/1619306/version-info.txt)

**Comment by shin-** [comment]
@smarschner Thanks for the report! Does it work if you set the Compose file version to `3.3` instead?

**Comment by smarschner** [comment]
Aha!  It does work with the version changed.  That's not something it had occurred to me to try; I didn't realize the file version could affect the behavior of features that existed in the earlier version already.  For the moment that appears to fix the problem entirely.  Thanks!

**Comment by smarschner** [comment]
Actually, it seems the behavior is different under file version 3.3.  From poking around with `docker inspect` under 3.3 it actually creates a `tmpfs` mount whereas under 3.2 it was creating a `volume` mount to a volume that was then abandoned after the container exited.  I imagine this is better for performance, but unfortunately it defeats our current setup because we were relying on the pre-population of these mounts from the container image, which I now realize does not happen with tmpfs mounts. Using a `volume` mount does pull the data from the image, but it is error-prone because even when the image is rebuilt the volume persists until it's explicitly removed, leaving our app looking at stale data from an earlier build. The `volume` mount that is always populated afresh was a useful feature.

Is there a better way to achieve the effect of mounting a directory from the container image over a bind mount, such that the data in that directory will not persist after the container exits?

Thanks!

**Comment by shin-** [comment]
Looks like you're entering the territory discussed in this issue: https://github.com/docker/compose/issues/4337#issuecomment-356480788

Can I ask what the reasoning is for having a volume at that location? Since you don't want the data to persist (new builds should replace), it might not be the right tool for the job (but then again, it might be).

**Comment by smarschner** [comment]
I actually was motivated originally by the same `jdlm.info` post.  The (rather common, I think) idea is to build a docker container that is the same as the one we will use for deployment, but then run it locally with the app directory overlaid by a bind mount, to have a short edit-{recompile,reload}-test cycle and everything visible via the local filesystem during development.  However, certain directories under the app directory need to come from the docker build process, notably `node-modules`, which contains the results of `npm install` operations that should exactly match what will be in the deployed container, and compiled C++ executables, which should also be the same ones that are built during the container build.  Building all this stuff every time the container starts would be too slow in deployment, and doing that only in development would introduce a parallel build process that creates an opportunity for mismatches between development and deployment.

So the goal, really, is to create a bind mount with "holes" in it — certain directories where the container filesystem effectively shows through. What's proposed in that article doesn't quite achieve this, because the contents of the anonymous volume will persist across rebuilds (this caused huge confusion among our developers before we figured this out!). The feature you propose in the other thread is exactly the behavior of the 3.2 "legacy tmpfs" mount: a volume that got populated every time the container started but then thrown away (or abandoned) and not reused when it finished.  A `tmpfs` filesystem might be even better, because it wouldn't leave volumes behind, but would likely need a new pre-population mechanism, since the existing one is part of the volume system.

A simpler solution would be to use several bind mounts to mount only the directories whose contents I want to be able to live-edit, and not what I don't, after ensuring these categories are separated in my directory structure. The trouble is creating that separation of directories when some tools, such as `npm`, insist on writing build results into a subdirectory rather than allowing some other directory to be configured as the destination.

**Comment by shin-** [comment]
@smarschner It sounds like you would be happy with the proposition I outlined here? https://github.com/docker/compose/issues/4337#issuecomment-356770457 

I consider `tmpfs` versus anonymous volume to be an implementation detail for the most part. Especially in a dev scenario, performance shouldn't really be a major concern.

**Comment by smarschner** [comment]
Yes, that feature would be ideal for our use case.
