### ISSUE TITLE
Update the EPEL package

### ISSUE THREAD

**Issue by ailjushkin** [docker/compose#5555]
Hi, I found that there is no newer versions in EPEL above docker-compose 1.9. I think that that would be very cool if you update this version in the EPEL repo.  Thanks.

**Comment by shin-** [comment]
Sorry @ailjushkin , we don't control the contents of the EPEL repo. Maybe @carlwgeorge can help.

**Comment by carlwgeorge** [comment]
Thanks for tagging me @shin-!  Yes @ailjushkin, I am the EPEL package maintainer.  [This comment](https://github.com/docker/compose/issues/2235#issuecomment-313231094) explains why it's still at that version number.  However, I have been working on getting all the docker-compose dependencies packaged for EPEL's python34 stack.  That means that despite RHEL shipping python-docker-py-1.10.6 (SDK 1 built for stock Python 2.7), I'll have python34-docker-2.7.0 (SDK 2 built for EPEL's Python 3.4) available, and can switch docker-compose to use python34.  I can update this issue once that is complete.

**Comment by ailjushkin** [comment]
@carlwgeorge @shin- Thank you for the detailed response, guys, that is very good news. I'd be very grateful to you if you'd keep me posted.

**Comment by VRShiva** [comment]
@carlwgeorge Any update on this? I would like to be able to use scaling in docker-compose, in config and from commandline.

**Comment by carlwgeorge** [comment]
Sorry for the delay.  While working through the dependencies, I discovered that EPEL's python34 stack only has [requests 2.12.5](https://src.fedoraproject.org/rpms/python3-requests/blob/epel7/f/python3-requests.spec#_4), so I'm [limited to docker-py 2.6.1](https://github.com/docker/docker-py/commit/ff86324c4f51495b0f0395e4cb28c83a37d4d3e0), which means I'm limited to [compose 1.18.0](https://github.com/docker/compose/commit/ebf1a658a6f48fd96849ed518609a6dd379350d8).  Still a good bump over 1.9.0, and I believe it gets @VRShiva the `--scale` flag.  I have submitted [docker-compose-1.18.0-1.el7](https://bodhi.fedoraproject.org/updates/docker-compose-1.18.0-1.el7) as an update.  Once that changes status to "testing", you can install it by running `yum --enablerepo epel-testing update docker-compose`.  Make sure the run `yum autoremove` afterwards to remove the leftover python 2 dependencies.

@shin- Reviewing the changelog from 1.9.0 to 1.18.0, I noticed that [1.13.0 includes a breaking change](https://github.com/docker/compose/blob/1.18.0/CHANGELOG.md#1130-2017-05-02).  Just how bad is that?  Depending on the severity I may need to take some [additional steps](https://fedoraproject.org/wiki/EPEL_incompatible_upgrades_policy) to comply with [EPEL policy](https://fedoraproject.org/wiki/EPEL_Updates_Policy).

**Comment by shin-** [comment]
@carlwgeorge Not sure how to answer the question - it's definitely breaking for people using `scale` and `up` successively with the old version (see #5663). I don't have much data indicating whether that's a common use-case however (most of the data I get on the tracker is from people using recent-ish versions).

Let me know if I can help in any way.

**Comment by tsabirgaliev** [comment]
@carlwgeorge even if not latest, 1.18.0 is much better that 1.9.0

**Comment by carlwgeorge** [comment]
[docker-compose-1.18.0-1.el7](https://bodhi.fedoraproject.org/updates/docker-compose-1.18.0-1.el7) has been in testing for over three months now (only two weeks is required).  It's gotten +1 karma in that time, and no one has complained of problems with it.  I'll go ahead and promote it to stable.

I'd love to continue updating EPEL's docker-compose in the future, but I'm blocked until python34-requests gets updated past 2.12.5.

Any future issues related to the EPEL package can be submitted on [Red Hat's bugzilla tracker, using the 'Fedora EPEL' product and 'docker-compose' component](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL&component=docker-compose&version=epel7).

@shin- Feel free to close this issue.
