### ISSUE TITLE
docker-compose with two volumes create one empty folder

### ISSUE THREAD

**Issue by DmitryVengerov** [docker/compose#5564]
Hello there! In my docker-compose file i have many images and i want make two host folder named db and public with css and js files.
in first image with db: 

>         volumes:
>             - './db/:/usr/local/var/lib/db'

Its ok! Create folder with name db with all files inside from image! 

But second image dont do that. I do:

>         volumes:
>             - './public/:/app/public'

Folder creates but all files dont input on host and delete all files in image.

I use version: "2". What iam doing wrong?

**Comment by shin-** [comment]
Hi @DmitryVengerov,

Please use the [forums](https://forums.docker.com) for support.

**Comment by DmitryVengerov** [comment]
hello @shin- 
Yep but on forum this problem not solved.

**Comment by shin-** [comment]
Sorry, this is an issue tracker, not a support channel. You'll need to create a new thread on the forums.
