### ISSUE TITLE
Variable substitution in YAML keys

### ISSUE THREAD

**Issue by mvasin** [docker/compose#5567]
Variable substitution works for YAML's array elements and hash values, but does not work for hash **keys** (see the last line):

```
version: "3"

services:
  ubuntu:
    image: ubuntu
    volumes:
      - $VOL

volumes:
  ${VOL}:
```

=>

```
$ VOL=some_vol docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
volumes value '${VOL}' does not match any of the regexes: u'^[a-zA-Z0-9._-]+$'
```

I'm running docker-compose version 1.17.1, build 6d101fb.

**Comment by shin-** [comment]
That's by design - you can use the search function to see prior discussion of the same issue.

You can use `version: '3.4'` and the `name` key for parametrized volume names.

**Comment by mvasin** [comment]
I've found https://github.com/docker/compose/issues/3858, sorry for duplicating.

And thanks for the hint with `name` in `version: "3.4"`! It worked perfectly.

**Comment by samskiter** [comment]
Paging @shin- I think I need this feature *or* a fix for external EFS volumes (see https://github.com/docker/compose-cli/issues/2164#issuecomment-1551419638)
