### ISSUE TITLE
NanoServer docker-compose : Error loading Python DLL

### ISSUE THREAD

**Issue by sflins** [docker/compose#5573]
Compose throws error just checking version with Microsoft NanoServer

docker-compose version

docker-compose.exe : Error loading Python DLL: C:\Users\Administrator\AppData\Local\Temp\_MEI20282\python27.dll (error code 1114)
    + CategoryInfo          : NotSpecified: (Error loading P...rror code 1114):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    
Os version:

[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

$PSVersionTable

Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
CLRVersion
PSVersion                      5.1.14393.1000
PSEdition                      Core
BuildVersion                   10.0.14393.1000
WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
SerializationVersion           1.1.0.1

docker version
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:46:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:55:16 2017
 OS/Arch:      windows/amd64
 Experimental: false

Install docker-compose

Invoke-WebRequest "https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Windows-x86_64.exe" -UseBasicParsing -OutFile $Env:ProgramFiles\docker\docker-compose.exe

Any ideas ?

Sergio

**Comment by shin-** [comment]
Looks like this is due to a limitation in nanoserver: https://social.technet.microsoft.com/Forums/Azure/en-US/90b8b203-3a3f-48bf-bd8b-2c452b8f5b2e/python-builtcompiled-using-dlls-supported-by-nanoserver?forum=NanoServer

Specifically, it seems that compiling the binary with Python 3 instead of Python 2 may resolve the problem. (ref: #5063)

**Comment by sflins** [comment]
I am facing some problems working with NanoServer.

This is just one of them.

I started using the MS2016 and the large images.

I will try again with this solution in the future.

Thank 's in advance.

**Comment by shin-** [comment]
This specific Python DLL issue should be fixed in the next release. I don't know if that means things will work smoothly with NanoServer, but if it doesn't, please open a new issue!

Cheers,
