### ISSUE TITLE
docker-compose run should allow unsetting an entrypoint

### ISSUE THREAD

**Issue by pbecotte** [docker/compose#5582]
`docker-compose run --entrypoint='' blah`
The above command should allow you to unset the entrypoint for the container, but has no effect. The corresponding behavior was added to the docker client in

https://github.com/moby/moby/pull/23718

**Comment by ghsatpute** [comment]
@shin-  I've created a [Pull Request](https://github.com/docker/compose/pull/5619) for this. Please have a look at it.
