### ISSUE TITLE
scale not available in version 3.X compose file

### ISSUE THREAD

**Issue by taichunmin** [docker/compose#5589]
Dear All,

When I change my `docker-compose.yml` to version 3.X, I got following error:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.ngrok: 'scale'
```

But I didn't know why the scale option is missing. I can't find `scale` in [Compose file version 3 reference](https://docs.docker.com/compose/compose-file/). And the [upgrade guide of version 3](https://docs.docker.com/compose/compose-file/compose-versioning/#version-3) didn't say the removal of `scale`.

**Comment by dotchev** [comment]
@shin-  What's the reason to close this issue?
