### ISSUE TITLE
Docker-compose build writes by default "Building ..." to STDERR.

### ISSUE THREAD

**Issue by paulvanbladel** [docker/compose#5590]
Docker-compose build writes by default "Building _MyImage_" to STDERR where MyImage is the image I'm building.

That makes integration with a build process quite difficult, since I want to capture real errors.
Any workaround possible ?

**Comment by shin-** [comment]
You should use exit codes to detect errors.

**Comment by paulvanbladel** [comment]
Yes but why is something written to STDERR when exit code = 0 ?
When integrating with build and release tooling, StdErr is sometimes interpreted by the tooling.

**Comment by shin-** [comment]
We use `stderr` to separate Compose status output from application (or in this case, build) output.
It certainly seems unintuitive for said tooling to assume an error is occurring based solely on message presence on `stderr` . Maybe it's configurable?

**Comment by paulvanbladel** [comment]
Joffrey,
Thanks a lot for your continuous support.
Indeed it's configurable, but since a build/release process should always stop on first error it's quite convenient to just rely on error output and you can just call the docker commands without any further error exit ceremony.
So, in your scenario, presuming that your run a bash script, are you for each docker command that's involved doing something like:
```
docker this or that
OUT=$?
if [ $OUT -eq 0 ];then
echo "ok"
else
exit $OUT
fi
```
For me it sounds really irrational that something is dropped in error output when there is no error. 
I would use standard output for that, no?

**Comment by shin-** [comment]
@paulvanbladel Would being able to configure the log level of the `docker-compose` CLI using a flag or environment variable be a satisfactory solution?

**Comment by paulvanbladel** [comment]
Joffrey,
Not sure. I just noticed that also docker login writes to STDERR just for providing a warning:
```
WARNING! Using --password via the CLI is insecure******** Use --password-stdin********
```
Not sure if the introduction of a log level would change anything.

**Comment by sladg** [comment]
I have come across this as well.
I'm using CI to deploy automatically. Problem is: If I turn off ,,Error on STDERR" I can't detect errors from other application. If I leave it ON, Docker-compose fails.

I genuinely think that using STDERR for warnings or separation of application and composer is a bad solution.

Warning is not error and information message is not an error as well, so why are we using STDERR?

**Comment by sonuame** [comment]
Please fix this. Its making all my pipelines to fail
