### ISSUE TITLE
Add support --device-cgroup-rule option

### ISSUE THREAD

**Issue by th3mis** [docker/compose#5622]
Hello everyone!

Almost one year ago `--device-cgroup-rule` was merged into main branch (https://github.com/moby/moby/pull/22563), but I cannot find any support for this option in latest docker-compose.

1. When will this option be added?
2. How can I use it now? Maybe some workaround for it?

**Comment by shin-** [comment]
Unfortunately, there's no way to do this currently, but it should be possible to include it in the next (1.20) release.

**Comment by th3mis** [comment]
But I guess that `--cgroup-parent` can help in this situation? No workaround here?
