### ISSUE TITLE
Build context is wrong when COMPOSE_FILE is being used

### ISSUE THREAD

**Issue by achekulaev** [docker/compose#5624]
When `COMPOSE_FILE` directive is being used, `docker-compose` uses wrong relative path/build context for `build` instructions.

Demonstration.
Directory `/Users/alexei.chekulaev/tmp/bug_demo`

Structure:

```
bug_demo/
  conf/
    docker-compose.yml
  build/
    Dockerfile
```

`docker-compose.yml` contents:

```
version: "2.1"

services:
  test:
    build: build
```

**Actual result** when building in `/Users/alexei.chekulaev/tmp/bug_demo`:
```
$ pwd
/Users/alexei.chekulaev/tmp/bug_demo

$ COMPOSE_FILE="conf/docker-compose.yml" docker-compose config
ERROR: build path /Users/alexei.chekulaev/tmp/bug_demo/conf/build either does not exist, is not accessible, or is not a valid URL.
```

So `docker-compose` was looking for `build` dir in `/Users/alexei.chekulaev/tmp/bug_demo/conf` which is wrong.

**Expected result**: `docker-compose` should use CWD as current path, not the path where first config file was found.

**Comment by achekulaev** [comment]
Relates to: https://github.com/docker/compose/issues/4857

**Comment by shin-** [comment]
This works as documented: https://docs.docker.com/compose/compose-file/#context
> When the value supplied is a relative path, it is interpreted as relative to the location of the Compose file.

**Comment by achekulaev** [comment]
@shin- thanks for a quick reply. Is there a way to set context to current working dir without providing the full path?

**Comment by shin-** [comment]
In your case, I believe simply changing `build` to `../build` will do the trick.

**Comment by achekulaev** [comment]
The case in the ticket is just an artificial example. The real case is much more complex. I have central `yml` files. And I have per-project `yml` files that override some values of those central `yml` files, and also per-project `Dockerfile`. 

```
/base.yml
/volumes.yml

/arbitrary/path/projectA/project.overrides.yml
/arbitrary/path/projectA/Dockerfile

/other/arbitrary/path/projectB/project.overrides.yml
/other/arbitrary/path/projectB/Dockerfile
```

My `COMPOSE_FILE` has all of them:

```
COMPOSE_FILE="/base.yml;/volumes.yml;/arbitrary/path/projectA/project.overrides.yml"
```

And what I actually need is to build images in the context of a **project**, not in the context of the `base.yml`. 

To do that right now, in `project.yml` my developers have to write _exact_ project path:

```
...
  build: /other/arbitrary/path/projectB
```

Base files won't move, but projects can. When project files move (or when used on other OS), above will stop working.
Would be great to be able to write something pointing to the current directory instead.

```
...
  # this is current working directory, not the path of the central.base.yml
  build: ./
```

**Comment by shin-** [comment]
You can do

```yaml
  build: $PWD/projectB
```

**Comment by achekulaev** [comment]
@shin- got it, thank you. Just for reference: is that a special variable or just an environment variable and I can actually use any environment variable there?
