### ISSUE TITLE
Containers recreating due to _depends_on_ feature

### ISSUE THREAD

**Issue by tshepitko** [docker/compose#5636]
If you specify strict order (like a chain) of containers launching via _depends_on_ feature and would like to change something in the middle container then all containers below will be recreated (even if their config were not changed).

What scenario is possible to have strict order of containers launching and avoid behavior above?

**Comment by shin-** [comment]
Previously reported in #3397 
Fixed by #5541 in the upcoming release.

**Comment by johanneswuerbach** [comment]
@shin- was this upcoming release 1.19.0-rc3?

1.19.0-rc3 includes in the release notes

> Dependent services no longer get recreated along with the dependency owner
if their configuration hasn't changed

but the recreate behaviour still seems to be broken for me.

**Comment by shin-** [comment]
Can you clarify what seems to be broken / missing ?

**Comment by johanneswuerbach** [comment]
With 1.19.0-rc3, I still see various more services being recreated without any changes then with 1.18.0. If this was supposed to be fixed with rc3, then I'll try to find a minimal config and create a new issue.

Just wanted to clarify whether the fix was shipped or not.

**Comment by shin-** [comment]
Yes, the fix in https://github.com/docker/compose/pull/5541 is included in 1.19.0 RC3.
You definitely shouldn't see *more* recreates compared to 1.18 :/

**Comment by johanneswuerbach** [comment]
@shin- created https://github.com/docker/compose/issues/5651
