### ISSUE TITLE
Dockerfile.run Question

### ISSUE THREAD

**Issue by harmon** [docker/compose#5638]
Hi,

I'm trying to use the "docker/compose:1.19.0-rc3" docker image to run "docker-compose build":

```
$ docker run -it --net=host -v $(pwd):/tmp/server -w /tmp/server docker/compose:1.19.0-rc3 build myapp
Building myapp
ERROR: Couldn't connect to Docker daemon. You might need to install Docker:

https://docs.docker.com/engine/installation/
```

I can run it locally, and the dockerd is definitely running. Any ideas? I'm not really sure how to use this docker image successfully, there aren't any guides that I've seen...

**Comment by shin-** [comment]
It's recommended to use the image through the `run.sh` script, which populates the container's environment with the things you need to run successfully: https://github.com/docker/compose/blob/1.19.0-rc3/script/run/run.sh

Please also note that there are [some known issues](https://github.com/docker/compose/issues?q=is%3Aopen+is%3Aissue+label%3Acompose-in-a-container) with running Compose in a container.

**Comment by harmon** [comment]
Ahh! Gotcha, thanks for point it out. Are there any instructions pointing to this? I wasn't able to find any via the README.md or https://hub.docker.com/r/docker/compose/

Thanks @shin- !

**Comment by shin-** [comment]
It's (briefly) mentioned in our [install docs](https://docs.docker.com/compose/install/#install-as-a-container) under the "alternative install options" tab.

**Comment by harmon** [comment]
Ok, might be good to make a reference to that on the dockerhub page, just so there's some guidance on how to use it.

**Comment by shin-** [comment]
Thank you for your suggestion - I added a short paragraph that links to the install docs and the `script.sh` file in this repo in the description on Docker Hub.

**Comment by harmon** [comment]
@shin- Thanks! I see it now, much better!
