### ISSUE TITLE
volumes does not override the container file in docker-compose

### ISSUE THREAD

**Issue by hantsy** [docker/compose#5648]
I am using Docker Toolbox 18.01 under Windows 10 64bit. 

And I have set  `COMPOSE_CONVERT_WINDOWS_PATHS=1` in the .env file.

But docker-compose does work if I try to override a container file in volumes.

volumes:
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro

**Comment by shin-** [comment]
Please use the [forums](https://forums.docker.com) for support.
