### ISSUE TITLE
volumes does not create the container folder in docker-compose

### ISSUE THREAD

**Issue by hantsy** [docker/compose#5649]
I am using Docker Toolbox 18.01 under Windows 10 64bit.

And I have set COMPOSE_CONVERT_WINDOWS_PATHS=1 in the .env file.

But docker-compose does not create the folder if it does not exist in the container in  `volumes` section.

volumes:
- ./ssl:/etc/nginx/targetssl

**Comment by shin-** [comment]
Please use the [forums](https://forums.docker.com) for support.
