### ISSUE TITLE
bash completions fail with macOS's bash 3.2.57

### ISSUE THREAD

**Issue by ilovezfs** [docker/compose#5658]
```
==> bash -c 'source /usr/local/Cellar/docker-compose-completion/1.19.0/etc/bash_completion.d/docker-compose && complete -p docker-compose'
/usr/local/Cellar/docker-compose-completion/1.19.0/etc/bash_completion.d/docker-compose: line 73: syntax error in conditional expression: unexpected token `('
/usr/local/Cellar/docker-compose-completion/1.19.0/etc/bash_completion.d/docker-compose: line 73: syntax error near `@($'
/usr/local/Cellar/docker-compose-completion/1.19.0/etc/bash_completion.d/docker-compose: line 73: `        [[ ${words[$glob_pos]} == @($glob) ]] && echo "$key"'
```

```
bash-3.2$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
bash-3.2$ 
```

**Comment by shin-** [comment]
cc @albers 

I'm guessing it might be due to bash v3 being significantly outdated?

**Comment by albers** [comment]
#5579 introduced code that relies on the `extglob` option being set. 
@ilovezfs For some strange reason, your machine (or maybe Macs in general with their ancient bash version) don't have this option set. Can you please check two things:

- run `bash -c 'shopt -s extglob ; source /usr/local/Cellar/docker-compose-completion/1.19.0/etc/bash_completion.d/docker-compose && complete -p docker-compose'`. Does this work?
- Perform the original check with Docker's completion script. It has a fix against `extglob` not being set. Does this work?

**Comment by briandealwis** [comment]
Requires the same fix as https://github.com/docker/cli/commit/7fa96238a6c78e6b35a8e9a0758bef0c07a96b15
