### ISSUE TITLE
"Couldn't find `docker` binary" when using run.sh 1.19.0

### ISSUE THREAD

**Issue by EvgenyOrekhov** [docker/compose#5659]
I have always used Docker Compose as a container, as described here: https://docs.docker.com/compose/install/#install-as-a-container.

But it became unusable since 1.19.0.

When I run `docker-compose exec` I get the following error:

```text
ERROR: Couldn't find `docker` binary. You might need to install Docker:

https://docs.docker.com/engine/installation/
```

I have the `docker` binary on my host system.

**Comment by shin-** [comment]
@EvgenyOrekhov Thank you for the report! I updated the `docker/compose:1.19.0` image on the Docker Hub to fix that issue. Just make sure you have the latest version by running `docker pull docker/compose:1.19.0` first.

**Comment by Sajjadhosn** [comment]
@shin- This issue still persists when I want to use `docker-compose` binary with docker-compose `yml` files. 

This is the command I have defined in my CI to run some linting for me, which fails with the same exact error mentioned above:

`docker-compose -f docker-compose.yml -f docker-compose.gitlab-ci.yml run cms_service flake8`

I was using `pip install docker-compose` which naturally was installing the latest version. I then locked the version by using `pip install docker-compose==1.18.0` and the tests succeeded without errors. So this is related to `1.19.0`.

**Comment by EvgenyOrekhov** [comment]
@Sajjadhosn This issue is related to running Docker Compose as a container (using the [run.sh](https://github.com/docker/compose/blob/master/script/run/run.sh) script).

You are describing a different way of installing and running Docker Compose.

The [1.19.0 release notes](https://github.com/docker/compose/releases/tag/1.19.0) say:

> On UNIX platforms, interactive run and exec commands now require
the docker CLI to be installed on the client by default.

So you should make sure that the Docker CLI is installed on your system.

**Comment by shin-** [comment]
@Sajjadhosn As Evgeny said, you'll either have to install the Docker CLI or set [`COMPOSE_INTERACTIVE_NO_CLI`](https://docs.docker.com/compose/reference/envvars/#compose_interactive_no_cli) to restore the previous behavior.

**Comment by Sajjadhosn** [comment]
@EvgenyOrekhov @shin- I had the docker engine installed ( which means the docker CLI was accessible ) on the CI runner that was executing the job ( gitlab terminology ). But since this issue is irrelevant to the problem I have, I'll drop my case since it's also not nice that I'm not giving you a reproducable case where you can verify it by yourself, unfortunately due to lack of time.

**Comment by EvgenyOrekhov** [comment]
@Sajjadhosn We use Docker Compose on GitLab too. We use [our own image](https://hub.docker.com/r/twinscom/docker/) which is based on the official Docker image and currently comes with Docker Compose 1.19.0 installed with `pip install docker-compose`, and, as you can see [here](https://gitlab.com/twinscom/php-boilerplate/-/jobs/52635862), `docker-compose run` works fine for us.
