### ISSUE TITLE
docker-compose run kills the container while docker run does not

### ISSUE THREAD

**Issue by KevinSjoberg** [docker/compose#5661]
If I run `docker run -td --rm --name mycontainer myimage bash` it boots up, daemonizes the container and return the container id. No problem.

Running `docker ps` confirms it's up and running.

If I run `docker-compose run -d --rm --name mycontainer myservice bash` it boots up, daemonizes the container and returns the container name. No problem.

Running `docker ps` confirms it's not up and running at all, but exited immediately.

Why is this?

**Comment by shin-** [comment]
`docker-compose run` doesn't allocate a TTY if running in detached mode, which makes it different from your `docker run` command.
