### ISSUE TITLE
docker-compose file doesn't handle YAML in flow mode (where tabs are valid)

### ISSUE THREAD

**Issue by Curtis-Fletcher** [docker/compose#5662]
According to the YAML spec, when in flow style, leading whitespace (tabs or spaces) is "neither content nor indentation." whereas in a docker compose file specified as *.json or *.yml a trivial case of valid flow style cosmetically indented with tabs

<pre>
{
	"version": "3",
	"services": {
		"test": {}
	}
}
</pre>

results in a YAML parse error:

> ERROR: yaml.scanner.ScannerError: while scanning for the next token
> found character '\t' that cannot start any token

Which is incorrect for tokens in flow mode.

This is for docker-compose version 1.18.0, build 8dd22a9 on MacOS

**Comment by shin-** [comment]
I believe you are misreading the spec - The only occurrence of the "neither content nor indentation" phrase you mention was related to whitespace appearing before comment lines. That [same section](http://www.yaml.org/spec/current.html#id2519916) also includes the following mention:

> Note that indentation **must not** contain any tab characters

In the [section on tabs](http://www.yaml.org/spec/current.html#tab/), the following mention can be found:

>  Tabs **may** appear inside comments and quoted or block scalar content. Tabs **must not** appear elsewhere, such as in indentation and separation spaces.

The section describing flow styles doesn't make any mention of tabs being allowed, so this particular rule doesn't seem to be overridden like you suggest.

**Comment by Curtis-Fletcher** [comment]
None of that contradict the line quoted, "indentation" which is the determination of block scoping via whitespace does not apply to flow styling. So "indentation" correctly can't contain tabs, but when using flow styling, it is sigils and not "indentation" that determines scope. whitespace (including tabs) prior to keys and other content is not considered indentation.

**Comment by shin-** [comment]
> indentation and separation spaces.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^

**Comment by Curtis-Fletcher** [comment]
Separation spaces are between keys not prior. The fact is that well behaving YAML parsers correctly handle tabs preceding flow statement lines.

**Comment by TomaszChrosniak** [comment]
The case presented by @Curtis-Fletcher seems to be a special case where flow style is used in the entirety of the document, so technically there is no indentation going on, just presentation detail.

The spec actually shows a similar example of a flow-style used within a block-style parent element [here](http://yaml.org/spec/1.2/spec.html#id2777865). You can see it the second-to-last line that tabs are also ignored in flow context, which would make the example valid.

**Comment by Curtis-Fletcher** [comment]
Here is an example of flow style bing validated with tab indentation:

http://ben-kiki.org/ypaste/data/272/index.html

**Comment by shin-** [comment]
Thanks for the links ; looks like I overlooked some of the details.

Unfortunately, neither `pyyaml` nor `ruamel.yaml` seem to support tabs in the given examples, and I don't know of any other viable YAML parser in Python that we could substitute. I'm also hesitant to rewrite a YAML scanner just to support this specific edge-case.

**Comment by Curtis-Fletcher** [comment]
Perfectly reasonable, if I happen to find a simple solution for python I assume I can post it here?

**Comment by shin-** [comment]
Sure, I'd be happy to look at it ; Moving off `pyyaml` has been a recurrent consideration given the lack of support it has received in recent years, so if there's a library out there that does it better that'd be an additional motivator.

**Comment by Curtis-Fletcher** [comment]
Seems like using the libYAML bindings in PyYAML rather than the pure python implimentation parses correctly:

>  python -c "import yaml;from yaml import load,  CLoader as Loader; print yaml.dump(load(\"{\n\t\\\"test\\\":\\\"fish\\\"}\", Loader=Loader))"

**Comment by shin-** [comment]
Hmm, that requires libyaml to be installed, and `pyyaml` to be installed explicitly with libyaml support. I'm also not sure about Windows support, but maybe we can attempt parsing with libyaml and if absent, default to the python implementation. I'll look into it.
