### ISSUE TITLE
Issue with 2+ containers sharing ip address on ubuntu 16.04

### ISSUE THREAD

**Issue by rizowski** [docker/compose#5664]
### Summary

I am having issues trying to connect to a container that is sharing the the same IP as another container. I have an example project that can recreate the issue I am going to describe located here [https://github.com/rizowski/docker-tunnel](https://github.com/rizowski/docker-tunnel).

### Quick details

I cannot reproduce this issue on a mac for some reason. It has to be done on a linux server. I am testing this with Ubuntu 16.04. I am also using docker-compose to construct the platform. @openam constructed the platform using regular docker commands and is able to replicate the issue as well. These tests are also performed externally of the host. The server that docker is running on does not have any custom iptable rules and should be vanilla. I have been able to hit any other container in the same docker network and externally. Just not any container sharing the same docker IP address as the tunneling container.

### The problem

When I try to spin up the services and try to access the container exposing the 8080 port, I am able to hit the container just fine. Whereas if I try to connect to the container with the 9090 port exposed through the tunnel I am unable to make a connection. 

This seems like a bug since I am able to hit the containers if it is running on my mac but not when it is running on Ubuntu 16.04.

**Comment by shin-** [comment]
I'm not sure what I'm supposed to see, but the example repo you linked to works fine on my Ubuntu machine:
```
$ docker-compose up -d
Starting tunnel ... 
Starting tunnel ... done
Starting http-vpn ... done
$ curl http://localhost:8080
Your IP is xx.xxx.xx.xxx
$ curl http://localhost:9090
Your IP is xx.xxx.xx.xxx
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by rizowski** [comment]
@shin Sorry. I wasn't very clear. I have an ubuntu server with `192.168.1.2` on my network and it hosts docker with the example project. If I were to curl `192.168.1.2:9090` I get a timeout error. If I curl 192.168.1.2:8080 I get my IP address back. If the request is made in ubuntu I am able to hit both ports.

**Comment by shin-** [comment]
It must be your server's firewall - I get identical results with using my network-assigned IP:
```
$ curl 192.168.100.222:8080
Your IP is xx.xxx.xx.xxx
$ curl 192.168.100.222:9090
Your IP is xx.xxx.xx.xxx
```

**Comment by openam** [comment]
On my Ubuntu 16.04 instance, it's working for me on the second commit @rizowski made in his demo repo. However, on the first commit, using the PIA image, it's not working unless I do the localhost `curl localhost:9090` instead of the machines ip address `curl 192.168.x.x`.

**Comment by shin-** [comment]
@openam sounds like an issue with the image rather than anything to do with Compose then?

**Comment by openam** [comment]
Yeah, it seems like the pia image is blocking access from anything outside of localhost. I don't think it has anything to do with compose.

**Comment by rizowski** [comment]
I ended up having to do a reverse proxy to be able to communicate with the container externally to the server it is hosted on. I tried explicitly exposing the port for all destinations but it still did not allow communication with the container.
