### ISSUE TITLE
Inconsistent restart behaviour

### ISSUE THREAD

**Issue by acdha** [docker/compose#5675]
While working on a larger project, I noticed that the restart behaviour is unreliable. According to the documentation restart seems pretty simple:

> no is the default restart policy, and it does not restart a container under any circumstance. When always is specified, the container always restarts. The on-failure policy restarts a container if the exit code indicates an on-failure error.
>
> restart: "no"
> restart: always
> restart: on-failure
> restart: unless-stopped

https://docs.docker.com/compose/compose-file/#restart

Unfortunately, using Docker for Mac (version: 17.12.0-ce-mac49) that behaviour was unreliable. The example below uses this `docker-compose.yml` file:

```docker-compose.yml
version: '3'

services:
    restart_on_failure:
        container_name: restart_on_failure
        image: alpine:latest
        restart: on-failure
        command: /bin/sh -c "date; exit 1"
```

It appears that the restart policy is ignored on the first launch:

```bash
cadams@jupiter:~/Desktop $ docker-compose up
Creating restart_on_failure ... done
Attaching to restart_on_failure
restart_on_failure    | Mon Feb 12 20:13:20 UTC 2018
restart_on_failure exited with code 1
cadams@jupiter:~/Desktop $ docker-compose up
restart_on_failure is up-to-date
Attaching to restart_on_failure
restart_on_failure    | Mon Feb 12 20:13:20 UTC 2018
restart_on_failure    | Mon Feb 12 20:13:24 UTC 2018
restart_on_failure    | Mon Feb 12 20:13:25 UTC 2018
restart_on_failure    | Mon Feb 12 20:13:26 UTC 2018
restart_on_failure    | Mon Feb 12 20:13:27 UTC 2018
restart_on_failure    | Mon Feb 12 20:13:29 UTC 2018
restart_on_failure    | Mon Feb 12 20:13:36 UTC 2018
restart_on_failure exited with code 1
```

This means that using `--force-recreate` will prevent it from ever being restarted, with no indication for why:

```bash
cadams@jupiter:~/Desktop $ docker-compose up --force-recreate
Recreating restart_on_failure ... done
Attaching to restart_on_failure
restart_on_failure    | Mon Feb 12 20:15:47 UTC 2018
restart_on_failure exited with code 1
cadams@jupiter:~/Desktop $ docker-compose up --force-recreate
Recreating restart_on_failure ... done
Attaching to restart_on_failure
restart_on_failure    | Mon Feb 12 20:15:56 UTC 2018
restart_on_failure exited with code 1
```

Curiously, this is not consistent with multiple containers - using this Dockerfile, it usually but not always will restart as expected:

```docker-compose.yml
version: '3'

services:
    restart_on_failure:
        container_name: restart_on_failure
        image: alpine:latest
        restart: on-failure
        command: /bin/sh -c "date; exit 1"
    restart_unless_stopped:
        container_name: restart_unless_stopped
        image: alpine:latest
        restart: unless-stopped
        command: /bin/sh -c "date; exit 1"
    restart_always:
        container_name: restart_always
        image: alpine:latest
        restart: always
        command: /bin/sh -c "date; exit 1"
```

**Comment by shin-** [comment]
There might be a misunderstanding here, but that configuration you shared is working as intended:

```
$ docker-compose up
Creating network "repro5675_default" with the default driver
Creating restart_on_failure ... done
Attaching to restart_on_failure
restart_on_failure    | Mon Feb 12 21:34:57 UTC 2018
restart_on_failure exited with code 1
$ docker-compose ps
       Name                  Command             State      Ports
-----------------------------------------------------------------
restart_on_failure   /bin/sh -c date; exit 1   Restarting        
$ docker-compose logs
Attaching to restart_on_failure
restart_on_failure    | Mon Feb 12 21:34:57 UTC 2018
restart_on_failure    | Mon Feb 12 21:34:58 UTC 2018
restart_on_failure    | Mon Feb 12 21:34:59 UTC 2018
restart_on_failure    | Mon Feb 12 21:34:59 UTC 2018
restart_on_failure    | Mon Feb 12 21:35:01 UTC 2018
restart_on_failure    | Mon Feb 12 21:35:02 UTC 2018
restart_on_failure    | Mon Feb 12 21:35:06 UTC 2018
restart_on_failure    | Mon Feb 12 21:35:13 UTC 2018
restart_on_failure    | Mon Feb 12 21:35:26 UTC 2018
restart_on_failure    | Mon Feb 12 21:35:52 UTC 2018
$
```

As you can see, the `docker-compose` process will detach when the container exits (that's because the API will close the connection when the container stops, so we can't keep streaming), but the container is still being restarted (with exponential backoffs that are managed at the engine level) as configured. The same thing applies if you use the `--force-recreate` flag.

**Comment by acdha** [comment]
Doesn't it seem inconsistent to have to hit logs for the output only when the container is newly created? If the second or later run can reconnect after the container restarts, it seems like the first run should as well.

**Comment by shin-** [comment]
I agree that attempting to re-attach to the container after it exited would be a nice feature to have. It's more complex than it might seem at first glance, though.

**Comment by acdha** [comment]
If it's not easy to adopt the logic which is used on the second and greater runs to automatically reattach, perhaps it shouldn't do that ever and should instead just encourage the user to run `docker-compose logs --follow` for discoverability? It's not a huge problem but since it usually only shows up while debugging it's annoying to have to distract away from the problem to regain access to the console output.

**Comment by shin-** [comment]
Consolidating: #6060
