### ISSUE TITLE
"run" command doesn't seem to recreate dependencies on config changes

### ISSUE THREAD

**Issue by immerrr** [docker/compose#5691]
I have a compose file that looks like this:
```yml
version: "2"

services:
  dep:
    image: rwgrim/docker-noop
    cpu_shares: 1

  runnable:
    image: rwgrim/docker-noop
    depends_on:
      - dep

```

A trained eye would notice that `cpu_shares: 1` is an invalid value, and indeed if you try to run the `runnable` service: `docker-compose run runnable`, it'll complain about it:
```
$ docker-compose run runnable
Creating network "test_default" with the default driver
Creating test_dep_1 ... error

ERROR: for test_dep_1  Cannot start service dep: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:365: setting cgroup config for procHooks process caused \\\"The minimum allowed cpu-shares is 2\\\"\"": unknown

ERROR: for dep  Cannot start service dep: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:365: setting cgroup config for procHooks process caused \\\"The minimum allowed cpu-shares is 2\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
```

Ok, I fix the problem by setting cpu-shares to 2 and re-run the command, but I see the same error:
```
$ sed 's/cpu_shares: 1/cpu_shares: 2/' -i docker-compose.yml 
$ docker-compose run runnable
Starting test_dep_1 ... error

ERROR: for test_dep_1  Cannot start service dep: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:365: setting cgroup config for procHooks process caused \\\"The minimum allowed cpu-shares is 2\\\"\"": unknown

ERROR: for dep  Cannot start service dep: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:365: setting cgroup config for procHooks process caused \\\"The minimum allowed cpu-shares is 2\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
```

It seems to be specific for `run` only, because `up` recreates the container as expected:
```
$ docker-compose up runnable
Recreating test_dep_1 ... done
Creating test_runnable_1 ... done
Attaching to test_runnable_1
test_runnable_1 exited with code 0
```

**Comment by shin-** [comment]
As far as I can tell, this is working according to spec [1]:

> If you start a service configured with links, the run command first checks to see if the linked service is running and starts the service if it is stopped. Once all the linked services are running, the run executes the command you passed it.

[source](https://docs.docker.com/compose/reference/run/)

You've found an edge case where the Docker Engine lets you create a container that can not actually be started, which obviously makes the experience awkward in this case, but I don't think it invalidates the behavior of `run` in the general case.

[1] `links` should probably be updated to say `dependencies` instead, but in that instance both work the same way.

**Comment by immerrr** [comment]
Ok, docker allows to create a container that cannot be started, and it's a corner case that not worth deeper inspection, it's fine. But here's the thing.

I'm not entirely sure I conveyed the message clearly. In my case the `dep` service is never started with `run`:
- When I invoke it for the first time, docker-compose creates a container to start, but docker fails to start it, thus `test_dep_1` remains stopped
- I fix the configuration, invoke it for the second time, but docker-compose sees that there's already a container for that service, presumably, no longer checks the configuration and proceeds right to starting it and, naturally, fails

Compare it to `docker up` behaviour, that would fail starting the faulty container when the configuration is wrong, *but* then it would pick up the change in the config file and re-create the container. Does it look like a spec-adhering behaviour to you?

**Comment by shin-** [comment]
Yes, I understand what you're saying. I still think the behavior you're observing is correct. To put it in other words:
- The role of `up` is to bring up your application's services, including recreating containers for which the configuration is found to be outdated.
- The role of `run` is to create and start a container for a declared service. Making sure the dependee services are running is part of making sure this works "as expected". Whether they are up to date isn't.

In 99% of cases, it doesn't matter to the `run` operation whether dependencies are up to date or not. The reason it matters here is because the service was allowed to be created with an incorrect configuration.

If in your case, dependencies *must* be up to date for your `run` process to behave as expected, the correct usage is to run `docker-compose up -d runnable && docker-compose run runnable <command>`

**Comment by immerrr** [comment]
It doesn't make much sense to me. You do a decent job of hiding the intermediate link in the 
```
compose-file -> container -> service
```
only to let the abstraction stick out just enough to trip over it every once in a while. There is a command (`up`) that already does the right thing, so the fact that `run` is a second-class citizen in that regard at least breaks the principle of least surprise.

I mean, let's check the documentation, or as you refer to it, "the spec". Here's what it has to say about `up`:

> Builds, (re)creates, starts, and attaches to containers for a service.

Builds and recreates the service itself, what about the linked services?

> Unless they are already running, this command also starts any linked services.

Then it reiterates how it picks up changes in the 

> service’s configuration or image was changed after the container’s creation

but notice how it says no such thing about linked containers.


`run` documentation says that 

> Commands you use with run start in new containers with configuration defined by that of the service

implying that the changes will be picked up on container creation, and then it goes with the phrase you've posted, no guarantees otherwise.


So in the end, there are two commands, for which the documentation (the spec) says that 

a) the service itself will pick up the changes
b) linked services are not guaranteed to pick up the changes

Yet one command picks up changes for linked services and the other does not. Do you still not see how this is a user-experience problem?

**Comment by shin-** [comment]
Thank you for your thoughts - we'll take it into consideration.
