### ISSUE TITLE
SSL error with remote host

### ISSUE THREAD

**Issue by armpogart** [docker/compose#5692]
I have CI running docker-compose and my configuration was working until recently. Not sure on which version of docker-compose my image was before (I've updated the image), but now I have following:

Image is base on `docker:latest`, docker-compose is installed through:
```
RUN apk add --no-cache py-pip
RUN pip install docker-compose
```

```sh
$ docker version
Client:
 Version:	18.02.0-ce
 API version:	1.32 (downgraded from 1.36)
 Go version:	go1.9.3
 Git commit:	fc4de44
 Built:	Wed Feb  7 21:12:37 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	17.09.0-ce
  API version:	1.32 (minimum version 1.12)
  Go version:	go1.8.3
  Git commit:	afdb6d4
  Built:	Tue Sep 26 22:42:49 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```
```sh
$ docker-compose version
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.14
OpenSSL version: LibreSSL 2.6.3
```

Following environment variables are populated: `DOCKER_HOST`, `DOCKER_TLS_VERIFY="1"` and `ca.pem`, `cert.pem` and `key.pem` are copied to `~/.docker` folder. (P.S. tried also `DOCKER_TLS_VERIFY=1` and `DOCKER_TLS_VERIFY="True"`)

On any docker-compose command (ps, pull) I get following error (some values are replaced with `xxxxxx`):
```sh
$ docker-compose --verbose pull
compose.config.config.find: Using configuration files: xxxxxx
docker.auth.find_config_file: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.auth.find_config_file: Found file at path: /root/.docker/config.json
docker.auth.load_config: Found 'auths' section
docker.auth.parse_auth: Found entry (registry=u'xxxxxx', username=u'xxxxxx')
docker.auth.load_config: Found 'HttpHeaders' section
urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): xxxxxx
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 121, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 40, in project_from_options
    override_dir=options.get('--project-directory'),
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 118, in get_project
    host=host, environment=environment
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 93, in get_client
    version_info = six.iteritems(client.version())
  File "/usr/lib/python2.7/site-packages/docker/api/daemon.py", line 177, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 191, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='xxxxxx', port=2376): Max retries exceeded with url: /v1.25/version (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
```

As you see `docker` connects to host as it shows daemon version and the same configuration was working until updating the image (and as a result docker-compose).
The workaround now is to use all the flags with docker-compose directly (as if I understand it correctly, it just ignore environment variables):
```sh
$ docker-compose -H xxxxxx --tlsverify --tlscacert ~/.docker/ca.pem --tlscert ~/.docker/cert.pem --tlskey ~/.docker/key.pem ps
```
It may be related to following issues/PRs: #5632, #5593, #5634  
I'm almost sure that this is some kind of regression that was introduced in `1.19.0`

P.S. Not sure if it is important but the CI is docker in docker setup.

**Comment by armpogart** [comment]
The workaround I've mentioned (to use docker-compose with all tls arguments specified) has one downside though. Now `docker-compose [args] pull` and `docker-compose [args] up -d` are working fine (where `[args]` is `-H xxxxxx --tlsverify --tlscacert ~/.docker/ca.pem --tlscert ~/.docker/cert.pem --tlskey ~/.docker/key.pem`), but `docker-compose [args] exec service sh -c 'somecommand'` is not working and gives following error:
```sh
docker-compose -H xxxxxx --tlsverify --tlscacert ~/.docker/ca.pem --tlscert ~/.docker/cert.pem --tlskey ~/.docker/key.pem exec service sh -c 'command_here'
the input device is not a TTY
```
and I need to also pass `-T` flag to docker-compose to disable pseudo-tty allocation. Not sure what's the problem here either, as previously it was working fine without that flag.

**Comment by shin-** [comment]
Are you setting `DOCKER_CERT_PATH` as well?

**Comment by shin-** [comment]
There's a chance we're not honoring the default. Does it work if you set it?

**Comment by armpogart** [comment]
@shin- I can confirm that setting `DOCKER_CERT_PATH` helps, and all other env vars are taken into the consideration in that case, so the changed behaviour is only that you've started to not honor the default value for it.

It's maybe another issue, but I still don't get, why
```sh
docker-compose exec service sh -c 'somecommand'
```
works, but:
```sh
docker-compose -H xxxxxx --tlsverify --tlscacert ~/.docker/ca.pem --tlscert ~/.docker/cert.pem --tlskey ~/.docker/key.pem exec service sh -c 'somecommand'
```
doesn't work, and I need to specify `-T` flag like:
```sh
docker-compose -H xxxxxx --tlsverify --tlscacert ~/.docker/ca.pem --tlscert ~/.docker/cert.pem --tlskey ~/.docker/key.pem exec -T service sh -c 'somecommand'
```

**Comment by armpogart** [comment]
@shin- Nope, sorry, for the second issue I mentioned, it's still not working, so it is also some kind of regression I think. `exec` command used to work without `-T` flag on my CI builds and are not working now with docker-compose 1.19.0.

Can I somehow install previous version of docker-compose with `pip install` method to confirm also that.

**Comment by shin-** [comment]
Thank you for confirming. I'll make sure we honor the default cert path in the next release.

You can install any version of Compose using `pip install -U docker-compose==<VERSION>`

**Comment by armpogart** [comment]
@shin- Can confirm also the second issue, see #5696
