### ISSUE TITLE
The input device is not a TTY

### ISSUE THREAD

**Issue by armpogart** [docker/compose#5696]
Following #5692 discussion, there is also some regression/bug concerning `-T` flag:
```sh
docker-compose exec service sh -c 'command`
```
works on:
```sh
$ docker-compose version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.7.0
CPython version: 2.7.14
OpenSSL version: LibreSSL 2.6.3
```
and older version (tested on 1.17.0, 1.17.1 and 1.18.0), but doesn't work on:
```sh
$ docker-compose version
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.14
OpenSSL version: LibreSSL 2.6.3
```

and gives following error:
```sh
$ docker-compose exec service sh -c 'command`
the input device is not a TTY
```
adding `-T` flag resolves the error.

**Comment by shin-** [comment]
You can probably work around this issue setting [`COMPOSE_INTERACTIVE_NO_CLI`](https://docs.docker.com/compose/reference/envvars/#compose_interactive_no_cli) for the time being

Is `command` a specific command, or are you able to reproduce with simple commands as well (`true`, `ls`, etc)?

**Comment by armpogart** [comment]
@shin- It doesn't work with simple commands either (tried with `ls`).
Also `COMPOSE_INTERACTIVE_NO_CLI` doesn't help (see excerpt from my build):
```sh
$ env | grep COMPOSE_INTERACTIVE_NO_CLI
COMPOSE_INTERACTIVE_NO_CLI=0
$ docker-compose exec service sh -c 'ls'
the input device is not a TTY
```
But on second thought I don't even fully understand whether the previous behavior was right or not, because of this excerpt from docker-compose documentation (https://docs.docker.com/compose/reference/exec/):
```
Commands are by default allocating a TTY, so you can use a command such as docker-compose exec web sh to get an interactive prompt.
```
On the other hand, this is from `man sh` for `-c` flag:
```
Read commands from the command_string operand instead of from the standard input. Special parameter 0 will be set from the command_name operand and the positional parameters ($1, $2, etc.) set from the remaining argument operands.
```
So as far as I understand with `-c` flag I'm forcing to it not to use standard input and there is no need to allocate pseudo-tty (it must spawn non-login, non-interactive session of `sh`).
Anyways this is regression, it used to work, though I'm not sure again which behavior is the correct one.

P.S. As a reminder everything mentioned runs on CI, so there is no input device there.

**Comment by shin-** [comment]
@armpogart The workaround involves setting the variable to 1, not 0.

**Comment by armpogart** [comment]
@shin- oops, sorry)
Yeah, `COMPOSE_INTERACTIVE_NO_CLI` workaround is working.

**Comment by EugenMayer** [comment]
Same issue, solved the same way. Seems like this has been introduced in more recent docker-compose versions.

```
# this fixes the input device is not a TTY .. see https://github.com/docker/compose/issues/5696
export COMPOSE_INTERACTIVE_NO_CLI=1
```

What is the background here - is this actually a workaround or "by design"? Thanks

**Comment by devuo** [comment]
Is this ever going to be fixed?

**Comment by bscheshirwork** [comment]
for `cron` try to add environment from command line `crontab -e` like
```
COMPOSE_INTERACTIVE_NO_CLI=1
# Edit this file to introduce tasks to be run by cron.
```
https://stackoverflow.com/a/10657111/7670492

**Comment by tnguyen14** [comment]
I tried setting `COMPOSE_INTERACTIVE_NO_CLI=1`, and then I am getting this error instead:

```
16:07:56 [25291] Failed to execute script docker-compose
16:07:56 Traceback (most recent call last):
16:07:56   File "site-packages/dockerpty/pty.py", line 334, in start
16:07:56   File "site-packages/dockerpty/pty.py", line 367, in _hijack_tty
16:07:56   File "site-packages/dockerpty/io.py", line 59, in select
16:07:56   File "site-packages/dockerpty/io.py", line 351, in fileno
16:07:56   File "site-packages/dockerpty/io.py", line 103, in fileno
16:07:56   File "socket.py", line 635, in fileno
16:07:56 ValueError: I/O operation on closed file.
16:07:56 
16:07:56 During handling of the above exception, another exception occurred:
16:07:56 
16:07:56 Traceback (most recent call last):
16:07:56   File "bin/docker-compose", line 6, in <module>
16:07:56   File "compose/cli/main.py", line 71, in main
16:07:56   File "compose/cli/main.py", line 127, in perform_command
16:07:56   File "compose/cli/main.py", line 519, in exec_command
16:07:56   File "site-packages/dockerpty/pty.py", line 338, in start
16:07:56   File "site-packages/dockerpty/io.py", line 32, in set_blocking
16:07:56   File "site-packages/dockerpty/io.py", line 351, in fileno
16:07:56   File "site-packages/dockerpty/io.py", line 103, in fileno
16:07:56   File "socket.py", line 635, in fileno
16:07:56 ValueError: I/O operation on closed file.
```

**Comment by speto** [comment]
@mhverbakel solution with `-T` flag (`docker-compose exec -T`) is a part of the [first comment](https://github.com/docker/compose/issues/5696#issue-299103105) itself but I also in hurry hadn't read it carefully and messed with `COMPOSE_INTERACTIVE_NO_CLI` at first 😄
I use it in shell script executed from ant.

**Comment by itcrowd72** [comment]
Thanks!

**Comment by armpogart** [comment]
@shin- Is this issue going to be closed without any fix by stale bot?
Maybe it is now the default behavior and you need documentation change?

**Comment by ndeloof** [comment]
I tried to reproduce this issue :

```
#docker-compose.yaml
version: '3'
services:
    test:
        image: alpine
        command: sleep 1000
```

```
➜  docker-compose up -d
Creating foo_test_1 ... done
➜  docker-compose exec test sh 
/ # 
```

Tested on compose 1.24.1

**Comment by armpogart** [comment]
Do I understand correctly that TTY is now allocated by default (https://docs.docker.com/compose/reference/exec/) and with need the flag or environment variable to disable pseudo-tty allocation. If I recall correctly the issue was opened as previously the default was the contrary behavior.

@ndeloof Where did you try to reproduce the issue? The issue was reproducible in CI environment where TTY can't be allocated usually (the details you can find in related issue from the original issue description).

**Comment by tnguyen14** [comment]
I think this should be kept open, as I haven't seen any resolution.

**Comment by hvaandres** [comment]
I'm getting the same issue through bitbucket. In my case, I run the following command:

```
docker run -it -v $PWD:/e2e -w /e2e cypress/included:6.2.1
```

If I run this command through my command line on Mac, it will work. If I run it on Windows, I have to change $PWD for %cd%. However, at the time that I added to my YAML file for my bitbucket pipeline, it will send me as output the following message:

```
docker run -it -v $PWD:/e2e -w /e2e cypress/included:6.2.1
the input device is not a TTY
```
What could be the issue here?

**Comment by iamtodor** [comment]
Hello people,
Could somebody please shed some light on `-T` vs `--no-TTY` and its usage?

According to the doc https://docs.docker.com/engine/reference/commandline/compose_exec/ it should act the same
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/12586108/202413280-d45a1501-4db2-449f-b4f9-08bc8339a1e6.png">

And code itself tells the same https://github.com/docker/compose/blob/v2/cmd/compose/exec.go#L72

But, this command works as it should:
```shell
docker-compose exec \
 --env ENV_VAR \
 -T ${service_name} bash
```
but these two do not:
```shell
docker-compose exec \
 --env ENV_VAR \
 --no-TTY \
 ${service_name} bash

docker-compose exec \
 --env ENV_VAR \
 --no-TTY true \
 ${service_name} bash
```

What am I missing here?

**Comment by larsnystrom** [comment]
The solution to this problem is to (whenever you're using `docker-compose exec` in a script) check if stdin is a TTY and if not, use the `-T` flag. Like this:

    docker-compose exec $(if ! [ -t 0 ]; then echo -n "-T"; fi) <servicename> ...

This allows you to use the same command whether you're running it interactively or piping to it.

**Comment by ndeloof** [comment]
@larsnystrom compose will automatically enable `-T` by default when you run without an actual terminal
see https://github.com/docker/compose/blob/v2/cmd/compose/exec.go#L71

**Comment by iamtodor** [comment]
> @larsnystrom compose will automatically enable `-T` by default when you run without an actual terminal see https://github.com/docker/compose/blob/v2/cmd/compose/exec.go#L71

Unfortunately, it does behave differently when you pass `-T` or `-no-TTY`

Please, take a look on my report https://github.com/docker/compose/issues/5696#issuecomment-1318369014 that is still being unresolved

**Comment by larsnystrom** [comment]
> @larsnystrom compose will automatically enable `-T` by default when you run without an actual terminal see https://github.com/docker/compose/blob/v2/cmd/compose/exec.go#L71

I'm still on docker-compose v1, so I don't think that's implemented there? Either that, or the problem is that docker-compose checks if stdout is a terminal, but the problem is that stdin is not a terminal.

**Comment by laurazard** [comment]
FYI, Compose V1 is EOL, hasn't been worked on in a while, and should be migrated away from.

**Comment by mehuled** [comment]
worked for me by using `-T` flag in the run command

**Comment by stevenh** [comment]
Got caught out here by miss ordered command line parameters, so capturing for others if `-T` or `--no-TTY` isn't working for you have the same.
If you have:
```shell
docker compose run myimage --no-TTY
```

It should be:
```shell
docker compose run --no-TTY myimage 
```

**Comment by rdjhurtado** [comment]
hola, una consulta, estoy intentando hacer un despliegue  ci/cd y estoy usando mwaa-local-runner pero al ejecutarlo tengo este error:  

Run cd aws-mwaa-local-runner
  cd aws-mwaa-local-runner
  ./mwaa-local-env test-startup-script ../airflow/startup/startup.sh
  shell: /usr/bin/bash -e {0}
the input device is not a TTY

cuando lo ejecuto desde un terminal en local me funciona pero desde mi pipeline no, me podrias ayudar ?
