### ISSUE TITLE
kubernetes support

### ISSUE THREAD

**Issue by pierreozoux** [docker/compose#5704]
As docker will support kubernetes, will there be support in compose too?

**Comment by shin-** [comment]
Hi @pierreozoux 

You can already use the Compose format to deploy on Kubernetes using `docker stack deploy`, as highlighted in [our blog post](https://blog.docker.com/2018/02/docker-compose-kubernetes-docker-desktop/)!
As far as `docker-compose` is concerned, we're evaluating our options, but aren't able to make any sort of commitment for the time being.

HTH!
