### ISSUE TITLE
Mac /usr/local/bin/docker-compose: line 39: realpath: command not found

### ISSUE THREAD

**Issue by HariSekhon** [docker/compose#5708]
The docker-compose shell wrapper from 'run as a container' installation does not work on Mac as it is looking for the `realpath` command:

https://docs.docker.com/compose/install/#install-compose

```
sudo curl -L --fail https://github.com/docker/compose/releases/download/1.19.0/run.sh -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

COMPOSE_FILE=docker/rancher-docker-compose.yml /usr/local/bin/docker-compose up
```

Docker for Mac's native binary version of docker-compose works normally.

**Comment by HariSekhon** [comment]
I used to use readlink a lot as a linux guy but it runs in to problems on Mac:

```
readlink -f
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by mefyl** [comment]
Ah, I guess that only stands for Linux then :/

**Comment by shin-** [comment]
You should be able to install the GNU version of `realpath` using `brew install coreutils` (you might have to declare a `realpath=grealpath` alias).
