### ISSUE TITLE
invalid service name

### ISSUE THREAD

**Issue by japrescott** [docker/compose#571]
I've updated docker to 1.3 and fig to 1.0 and suddently am getting strange "invalid service name" and "invalid repository name" errors and I am going apeshit finding a suitable approach. I like to camelCase things (e.g nodeWorker, or master_nodeWorker -> master is the folder name).
After getting the error that only [a-z0-9-_.] are supported, I changed to node.worker. Then it (I think its fig) says that it only accepts [a-zA-Z0-9]. After I changed that to node4worker, it complained about the _ in master_node4worker.
As these names were considered constants and are spread over many files, changing them is a real pain. Thus, I would be soooo greatful if you could please tell me HOW I should name my service/tag from 1.0< so that 1) fig doesnt blow 2) docker doesnt blow and 3) I can return to sanity
thanks for any tipps

**Comment by oblop** [comment]
Hello,
Could someone still add support for dots in service name before the docker-compose stable release?
Or even more like [a-zA-Z0-9-_.]
Thanks.

**Comment by thaJeztah** [comment]
@oblop currently, compose needs to use a naming convention to be able to "find" the containers belonging to a project, so unfortunately that won't be possible until some features in docker are implemented. Also see https://github.com/docker/fig/issues/652#issuecomment-70484191 for more information on this.

**Comment by oblop** [comment]
Hum.
I get why you can't allow the _ due to your <project>_<service>_<suffix> convention.

But why would the - and . be an issue ?
Or is it working differently, where is that documented ?

**Comment by oblop** [comment]
Make sense. Let's vote for a quick merge of https://github.com/docker/docker/pull/9882 then ;)

**Comment by lox5773** [comment]
+1..  
I also want service name to allow at least underscore and/or hyphen

**Comment by aanand** [comment]
@lox5773 it'll be allowed in Compose 1.4 - see #1181

**Comment by dnephin** [comment]
The service name now allows for `_`, `-`, and `.`

**Comment by okgemaltoprg** [comment]
Hey guys, it looks like bug to me related to this topic, however feel free to correct me:
`container_name: myapp-dev-cluster1-1519`

Works with docker run but it's refused by docker-compose with error:
`ERROR: for myapp  Invalid container name ("myapp-dev-cluster1-1519"), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed`

docker-compose v.: 1.7.0-rc1

**Comment by dnephin** [comment]
That error is coming from the daemon.  I just tried that name with docker 1.10.3 and it worked for me.

**Comment by okgemaltoprg** [comment]
I don't get it. If I do (with the same Docker daemon version) docker run --name=myapp-dev-cluster1-1519 ... it works. If it's in a compose file as mentioned in my comment #issuecomment-206406414 I get the error.

How can one docker daemon have two different responses on the same request? From my point of view: docker client = works, docker-compose = validation errror.

Docker version is 1.9.1, this one is automatically installed by docker-machine on AWS Ubuntu AMI (default AMI).
