### ISSUE TITLE
Loading docker compose without error checking

### ISSUE THREAD

**Issue by bendikro** [docker/compose#5710]
Currently [compose/config/config.py](https://github.com/docker/compose/blob/2fa201660c8c327336bbed3624ac0b33f9de5878/compose/config/config.py#L444) will always call [`validate_service()`](https://github.com/docker/compose/blob/2fa201660c8c327336bbed3624ac0b33f9de5878/compose/config/config.py#L457) which rasises a `ConfigurationError` e.g. if a service depends on a service that is missing.

The result is that it's not possible to read a config if there is a error.

Having error checking optional would be useful.

**Comment by shin-** [comment]
> Having error checking optional would be useful

Can you expand on that? What do you expect to be able to do with an invalid configuration?
