### ISSUE TITLE
Build target doesn't work in compose 1.19

### ISSUE THREAD

**Issue by lig** [docker/compose#5714]
I have the following in `docker-compose.yml`:

```yaml
version: '3'
services:
  app:
    build:
      context: .
      target: app
```

I'm using `docker-compose version 1.19.0, build 9e633ef` installed via `pip3`.

After running `docker-compose build` the expected result is to have the container for `app` service build with `--target` docker argument set to `app`.

The actual result is
```
ERROR: The Compose file './docker-compose.yml' is invalidbecause:
services.app.build contains unsupported option: 'target'
```

### Related issues

I've found this issue https://github.com/docker/compose/issues/5322 which states in comments that the build target is supported since 1.17.

Also, I've found this issue https://github.com/docker/docker.github.io/issues/6036 which states that the syntax is the same as for `2.x` compose file version.

**Comment by lig** [comment]
The issue was I've used version `3` which is not the latest from `3.x` series as I thought. One needs to use at least version `3.4` for build target to work.

**Comment by bossjones** [comment]
Just wanted to say thanks for this, for some reason I assumed if you put '3' as the version type, it would default to the latest supported version of '3' your docker client supports, but I was wrong. Doing the steps above, in my case, `3 -> 3.7` worked. ^^

**Comment by patricknelson** [comment]
Also pretty confusing for me, since this is also [documented in version 2](https://docs.docker.com/compose/compose-file/compose-file-v2/#target) as well. I assumed that if it was available in 2.3 then naturally it'd also automatically be available in 3. Turns out that's not the case, for some reason.

**Comment by patricknelson** [comment]
@akopchinskiy in this case the version is in reference to the version of the YAML content not necessarily the version of `docker-compose` that you have instead. 

Specifically: Did you try editing `docker-compose.yml` so that the *first line* `version: '3'` reads `version: '3.7'` instead?

**Comment by akopchinskiy** [comment]
@patricknelson 
> Did you try editing docker-compose.yml so that the first line version: '3' reads version: '3.7' instead?

I did try and it's working. Thank you!
