### ISSUE TITLE
docker add downloading page html instead of a cert.

### ISSUE THREAD

**Issue by Kiran-N** [docker/compose#5717]
I am adding the cert as below, It instead adding a html
ADD https://symwisedownload.symantec.com//resources/sites/SYMWISE/content/live/GENERAL_INFORMATION/2000/INFO2550/en_US/Symc_Cross_Root.txt?__gda__=1519572790_704e4d88e061ab9ef4785310453d25f4 /tmp/app/aws/sqs

**Comment by shin-** [comment]
You're on the wrong issue tracker, but the most likely explanation is that ADD doesn't follow redirects.
