### ISSUE TITLE
Can the regex be relaxed to allow "/" in volume names?

### ISSUE THREAD

**Issue by dvusboy** [docker/compose#5719]
The context is a plugin creating [Ceph RBDs](http://docs.ceph.com/docs/master/rbd/) as Docker volumes. But there is the ability to allocate the devices from different pools, and one way to specify the device is by the format of `<pool>/<name>`.

Currently, all of the current compose config schemas restrict the name of the volume with the regular expression: `"^[a-zA-Z0-9._-]+$"`. This precludes the use of `"/"` in the volume name. I understand that the pool can be supplied by way of a driver option, but that is only available in `VolumeDriver.Create` and all other plugin operations use just the name. Obviously, we don't want to treat `prod/volume` the same as `test/volume`, but with just the name of `volume`, there isn't much leeway to workaround the problem.

**Comment by dvusboy** [comment]
I just noticed the [name attribute](https://docs.docker.com/compose/compose-file/compose-file-v2/#name) to `volume`. Is this the way around the regular expression?

**Comment by shin-** [comment]
Yes, use `name`.  👍

**Comment by dvusboy** [comment]
Thanks a bunch for the quick response.
