### ISSUE TITLE
Install url missing for linux armfh

### ISSUE THREAD

**Issue by neutralvibes** [docker/compose#5723]
Hi,

Getting a 'not found' using the method mentioned in the docs for installing docker-compose. I have established the url being accessed is as follows: 

> https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Linux-armv7l

This url is not available on github, sorry if I have missed something.

**Comment by shin-** [comment]
@neutralvibes Sorry, we do not currently distribute a binary version of Compose for ARM architectures.
However, you should be able to [install Compose using `pip`](https://docs.docker.com/compose/install/#install-using-pip)

**Comment by neutralvibes** [comment]
Thanks
