### ISSUE TITLE
"pull" output is still present when using > /dev/null

### ISSUE THREAD

**Issue by kill0rz** [docker/compose#5738]
I have the following commands in my crontable:

```
/usr/local/bin/docker-compose pull > /dev/null
/usr/local/bin/docker-compose build --pull > /dev/null
/usr/local/bin/docker-compose up --no-deps -d > /dev/null
```
I want to supress the outputs and only get error messages, but these still give me the complete output.
Is this a bug? How can I do this?

Thank you!

**Comment by shin-** [comment]
https://github.com/docker/compose/pull/5703

**Comment by tmerten** [comment]
I think this issue still persists: what should be in standard output seems to be written to standard error instead:

**with `> /dev/null` I still see non-errors**
```
$ docker-compose --log-level CRITICAL --no-ansi pull >/dev/null
Pulling postgres      ...
[...]
Pulling postgres      ... digest: sha256:9625c2fb34986a49cb...
Pulling postgres      ... status: image is up to date for p...
Pulling postgres      ... done
```

**only with `2>/dev/null` everything is hidden** (which I would not want because I would hide the errors, too).
```
$ docker-compose --log-level CRITICAL --no-ansi pull 2>/dev/null
$ 
```

```
$ docker-compose --version
docker-compose version 1.23.0, build unknown
```
