### ISSUE TITLE
TTY mode broken

### ISSUE THREAD

**Issue by JonasT** [docker/compose#5741]
```shell
jonas@cyberman:~/test$ cat docker-compose.yml 

test:
  tty: true
  image: ubuntu
  command: bash

jonas@cyberman:~/test$ sudo docker-compose up
Starting test_test_1 ... done
Attaching to test_test_1
ls
ls
```
I tried to use `tty: true` for an interactive container, but it simply doesn't work: it hangs. The `ls` is me trying to interact with the bash, but there's no reaction / response. I tried specifying `stdin_open` with both `true` and `false` in addition, neither changes anything.

docker-compose version:
```
1.19.0, build 9e633ef
```

docker version:
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-44.git584d391.fc27.x86_64
 Go version:      go1.9.1
 Git commit:      caba767-unsupported
 Built:           Thu Nov 23 21:17:26 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-44.git584d391.fc27.x86_64
 Go version:      go1.9.1
 Git commit:      caba767-unsupported
 Built:           Thu Nov 23 21:17:26 2017
 OS/Arch:         linux/amd64
 Experimental:    false
```
I tried it on another machine with docker `17.12.0` (CE) and the same thing happens, it just gets stuck forever.

**Comment by shin-** [comment]
`docker-compose up` is not interactive. You want to use `docker-compose run` for this.

**Comment by JonasT** [comment]
Why is there no switch on `docker-compose up` for interactive mode? `docker-compose run` isn't a good replacement for this: when I make a sort of toolchain image it might launch some sort of shell the user might not know / care about in detail, and for `run` the user will need to know which shell to specify on launch - why, when it's already in `command`/`CMD`? Seems a bit like an oversight to me.

**Comment by shin-** [comment]
`run` will use the command you defined inside the Compose file:

```
$ cat docker-compose.yml 
version: '2'
services:
  foo:
    image: python:2
    command: python

$ docker-compose run foo
Python 2.7.14 (default, Feb 17 2018, 09:47:19) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

It's not an oversight, by design `up` operates at the application level, whereas `run` operates at the container level. `stdin` doesn't make sense as a concept at the application level.

**Comment by JonasT** [comment]
Ah, the `run` argument can be omitted, that makes more sense then :-) thanks for the explanation. I thought specifying the command for `run` is mandatory.

**Comment by augnustin** [comment]
Not sure I understood @etc0de last message but

```
test:
  tty: true
```

If the `tty` option is only used for `docker-compose run` and since `docker-compose run` *does* open a tty without it, what is the point of this key in `docker-compose.yml`? What are the use cases?
