### ISSUE TITLE
Add ability to use isolation with build

### ISSUE THREAD

**Issue by KnicKnic** [docker/compose#5744]
In Windows there is no way to build a container that requires specification of the isolation option. 
If the default isolation is process(which is the default for docker), and I want to build an image based on a downlevel container then the build needs to get passed isolation=hyperv .

I see two options.
1.  Have build inherit the isolation setting from the service.
2. Add isolation into the build args.

**Comment by shin-** [comment]
You'll have to request this as an engine feature first, which is usually done on the [moby/moby](https://github.com/moby/moby) repo.

**Comment by KnicKnic** [comment]
I am confused. It is already supported in the engine build. https://docs.docker.com/engine/reference/commandline/build/#options what would I have to request from the engine?

**Comment by shin-** [comment]
My bad, I didn't realize it was.

**Comment by artisticcheese** [comment]
Why is not reflected in docs?

https://docs.docker.com/compose/reference/build/
