### ISSUE TITLE
Cannot substitute environmental variables when their name contains a space

### ISSUE THREAD

**Issue by KnicKnic** [docker/compose#5749]
I tried to reference a environmental variable with a space in it. I also tried with parens "()"
Here is the repro steps in windows.

C:\tmp>set some arg=hello

C:\tmp>docker-compose up
ERROR: Invalid interpolation format for "command" option in service "space": "${some arg}"

C:\tmp>type docker-compose.yaml

    version: '2.1'
    services:
      space:
        image: microsoft/nanoserver
        command: ["c:\\windows\\system32\\cmd.exe", "/c", "echo", "${some arg}"]

**Comment by shin-** [comment]
Environment variable names can't contain spaces. When you do `set some arg=hello`, you define a `$some` variable with the value `"arg=hello"`.

**Comment by KnicKnic** [comment]
In windows environment variables can contain spaces. Here is some powershell to be more clear.
PS c:\tmp> [System.Environment]::SetEnvironmentVariable("some arg", "hello")
PS c:\tmp> [System.Environment]::GetEnvironmentVariable("some arg")
hello

**Comment by shin-** [comment]
Thank you for this precision.

For the moment, we're only interested in supporting UNIX-compliant variable names as to maximize the format's portability. Supporting all the characters that are valid in Windows environment variables would also preclude us from supporting advanced substitution syntax such as `${var?err}` and `${var-default}`.
