### ISSUE TITLE
takes more than 1 minute do just interpret a compose file on raspberry pi 

### ISSUE THREAD

**Issue by lucaszanella** [docker/compose#5759]
I tested on both raspberry pi zero w and raspberry pi 2, and the docker-compose utility takes a lot of time (more than 1 minute) to start building or running things. Not the first time, but every time.

ps: instructions on docker for linux do not work for raspberry
ps2: I'd love to get compose installed together with docker

**Comment by shin-** [comment]
What version are you using? Can you try the latest RC and see if it helps?

**Comment by lucaszanella** [comment]
docker-compose version 1.19.0, build 9e633ef

even to see the version it takes 1 minute

after trying

docker-compose version 1.20.0dev, build unknown

the problem persists

**Comment by ijc** [comment]
I wonder if your rpi has very low entropy and is therefore suffering from #6678?
