### ISSUE TITLE
[Question] Service lifecycle event hooks

### ISSUE THREAD

**Issue by pedro93** [docker/compose#5764]
I've been digging across the docker-compose documentation and found the following [page](https://docs.docker.com/compose/reference/events/) regarding container event streaming.

My question is, given that it is possible to be alerted about a container hitting lifecycle stages (created, started, restarts, stops etc ...), full list [here](https://docs.docker.com/engine/reference/commandline/events/#extended-description), it is possible with docker-compose to listen for such service events and perform an arbitrary script at each stage, such that, that hook pauses the docker-compose process?

As an example, let's say I have an orchestration between two services A, B where B depends on A being healthy. Additionally, service A needs to know some information about B which is dynamically generated on service bootup. 

The solution I am looking is some form of **before entry point** on service B, halt the docker-compose up process so that I can, in the host retrieve the dynamic information from A, generate a bash script with that information, execute the script on service B and then proceed with the docker-compose process.

Thank you for maintaining this project, it is extremely useful :)

_Edit_: Updated last paragraph, mixed up the service order, my apologies

**Comment by shin-** [comment]
See our recommendation here: https://github.com/docker/compose/pull/2392
And the wider discussion on this feature here: https://github.com/docker/compose/issues/1341

**Comment by pedro93** [comment]
Thank you, I have commented on the linked issue.

**Comment by shin-** [comment]
Out of curiosity, why can't that provisioning be part of your entrypoint script?

**Comment by pedro93** [comment]
Because the entrypoint script is defined in the host and executed in the container (this case service B) but the information I would need to add to the entrypoint script is generated in the runtime of service A.

Does that make it clearer?

**Comment by shin-** [comment]
It seems like B's entrypoint could make a request to A for that information. Not only would that work with the current tool, it would ensure that if B crashes and needs to restart, it's able to retrieve the information again without any intervention by the Compose process.

**Comment by pedro93** [comment]
Thank you @shin- for the assistance, I agree with you that that particular approach would work, but you are assuming one key thing, that the information from A is accessible from an endpoint. Unfortunatly this is not the case and it is not in my power to change it.

**Comment by pedro93** [comment]
About https://github.com/docker/compose/pull/2392 correct me if I am wrong but the event listening does not actually pause the docker-compose process right?

**Comment by shin-** [comment]
I see. Sorry I couldn't be of help.

And no, `docker-compose events` doesn't pause the process.

**Comment by pedro93** [comment]
Thank you regardless :smile:  you may close the issue. I will have to find some other tool for my particular needs.

+1 on the project.
