### ISSUE TITLE
Little consistency in validation messages makes tooling difficult

### ISSUE THREAD

**Issue by joewreschnig** [docker/compose#5773]
[The compose file validator](https://github.com/docker/compose/blob/badd4d764a1ada326604f7bea3d806cb4eb3558e/compose/config/validation.py) has very little consistency in how it formats errors. Some messages include filename and some do not, some use "Bad thing X in service Y" and others "Service X has invalid Y", some provide a full YAML path and others a separate service and subkey.

This makes it difficult to integrate its output with other programs for e.g. inline editor support.

Ideally, the format would be the de facto standard `filename:line:column: message`. But probably the line number information is too difficult to route all the way through the YAML load + jsonschema + post validation functions, so an alternate form might be:

```
<filename>: in service <service>: <subpath>: <message>
<filename>: service <service>: <message> # if the problem is service-level

<filename>: in volume <volume>: <subpath>: <message>
<filename>: volume <volume>: <message> # if the problem is volume-level

# And so on for other top-level objects

<filename>: <key>: <message> # if the problem isn't in a service / volume / etc
```

**Comment by shin-** [comment]
I think it's safe to say we're going for user readable over machine parseable, considering `docker-compose` is mainly intended to be used by humans. That said, if you think the latter can be improved without compromising the former, feel free to submit a PR!
