### ISSUE TITLE
It's possible to have "extra_hosts" in a file like environment does with .env?

### ISSUE THREAD

**Issue by reypm** [docker/compose#5783]
I am working in a stack using Docker Compose and it defines like 6 web services  where I need to specify a lot of `extra_hosts` on each of them. This hosts are the same. It's possible to have a file for this that can be re-used in all the services definition? Otherwise the file will have a lot of lines to repeat the same thing per service. 

What do you think about this?

**Comment by reypm** [comment]
@shin- closing this as you give me the solution, thanks

**Comment by AuspeXeu** [comment]
How does this work, the link is dead unfortunately...
