### ISSUE TITLE
Healthcheck hangs console

### ISSUE THREAD

**Issue by ctrahhuk** [docker/compose#5791]
Consider that i have service with maven container

>     container_name: mvn
>     image: maven:3.3-jdk-8
>     #services will wait for mvn container to complete build
>     healthcheck:
>       test: "exit 1"
>       interval: 2s
>       timeout: 10s
>       retries: 30
>   ...

Now  when I do 'up' or 'up -d', console hangs until maven container completes, and only then logs are attached
I can run 'docker-compose logs  - f -t', but in new console instance. I wonder how can I avoid this ?

**Comment by shin-** [comment]
This is working as intended - `docker-compose up` will wait for all required services to be up before streaming app logs.

**Comment by ctrahhuk** [comment]
Is there any option to start containers and get logs at the same time in the same console session while healthcheck phase is being perfromed ? sorry, probably it sounds creepy :)

**Comment by shin-** [comment]
No option to do so exists ; I'd recommend avoiding relying on healthcheck dependencies for this altogether. You'll be much better served by running this container independently first, and bringing up the rest of stack once the process's done. For example:
`docker-compose run -f docker-compose.yml -f docker-compose.mvn.yml mvn && docker-compose up`
(with `docker-compose.mvn.yml` containing the definition of your `mvn` service and `docker-compose.yml` defining all the long-running services)

**Comment by ctrahhuk** [comment]
ok, thx.I appreciate!
I thought about it too, but was curious if my question has a solution
