### ISSUE TITLE
Better error message when docker isn't running

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [docker/compose#5801]
I restarted and forgot to launch Docker for Windows before running `docker-compose`:

```shell
C:\Code\kuma>docker-compose pull
Pulling redis (redis:latest)...
ERROR: Windows named pipe error: The system cannot find the file specified. (code: 2)
```

It'd be nice to have a more informative error message about what file can't be found.

**Comment by shin-** [comment]
We'll look into it, thanks!

**Comment by alltej** [comment]
I have docker running but I got the same error message on `docker-compose pull`
