### ISSUE TITLE
libtinfo.so.5

### ISSUE THREAD

**Issue by stlouisn** [docker/compose#5808]
getting the following error messages:

docker-compose -v
/bin/sh: /tmp/_MEI1e1GVG/libtinfo.so.5: no version information available (required by /bin/sh)
docker-compose version 1.20.0, build ca8d3c6

uname -a
Linux ******.*** 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

**Comment by shin-** [comment]
Your OS may have a newer version of that shared library than the one Compose was built with. You should be fine ignoring this message.

see also: https://stackoverflow.com/questions/137773/what-does-the-no-version-information-available-error-from-linux-dynamic-linker

**Comment by niQo** [comment]
same here on debian stretch:

$ docker-compose version
/bin/sh: /tmp/_MEIXKc1wz/libtinfo.so.5: no version information available (required by /bin/sh)
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

$ uname -a
Linux std-qa-01 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

**Comment by quentinburley** [comment]
a workaround for this problem is to run docker-compose as a container:
https://docs.docker.com/compose/install/#install-as-a-container

>>>
$ sudo curl -L --fail https://github.com/docker/compose/releases/download/1.21.0/run.sh -o /usr/local/bin/docker-compose
$ sudo chmod +x /usr/local/bin/docker-compose
<<<

**Comment by zealotds** [comment]
For those who may be interested: Release 1.19 works fine without this warning -- Ubuntu  16.04 4.4.0-128
