### ISSUE TITLE
compose 1.20 with rancher os not working

### ISSUE THREAD

**Issue by luxferresum** [docker/compose#5815]
Hello

I'm not 100% sure that this is an issue. However I just tried to use compose 1.20 (inside docker with the `run.sh` script) on rancher os which leads to this error:

> libgcc_s.so.1 must be installed for pthread_cancel to work

Everything works fine with compose 1.19.

**Comment by shin-** [comment]
Thanks for the report! #5817 will fix the problem, and I'll push an updated version of the 1.20.1 image ; just make sure you pull the new version!
