### ISSUE TITLE
possible to have Dockerfile FROM point to another fig-defined service?

### ISSUE THREAD

**Issue by jokeyrhyme** [docker/compose#583]
I have a use case where the images should not be pushed to a registry, but there is a high amount of duplication between the Dockerfiles for 2 or more services in my fig.yml.

Is it possible to have fig pre-parse the Dockerfiles it is about to use so that it can fix up references between images created for fig-defined services as in the below example?

> fig.yml

```
a:
    build: ./a/

b:
    build ./b/
```

> b/Dockerfile

```
FROM a
# OR
FROM fig://a
# OR
FROM project_a

# ...
```

**Comment by dnephin** [comment]
I believe this is very similar to #295 and #610, going to close as a duplicate.

I've also linked this up from #1455
