### ISSUE TITLE
Win Docker update to 18.03.0 broke docker-compose

### ISSUE THREAD

**Issue by davidhund** [docker/compose#5834]
## Updating D4W to 18.03.0 broke docker-compose

The Docker for Windows application notified me of an update: 18.03.0-ce-win59 (16762)
After installing this update any `docker-compose` command errors out with:

> `Error loading Python DLL 'C:\Users\XYZ\AppData\Local\Temp\_MEI238842\python36.dll'. LoadLibrary:`

I've since completely removed Docker for Windows and reinstalled 18.03.0-ce-win59 (16762). 
The issue persists: docker-compose.exe will not run.

## Context information (for bug reports)

- Docker Engine Version: 18.03.0-ce-win59 (16762) Stable (670d80d)
- Compose 1.20.1
- Machine 0.14.0
- Credential Helpers: 0.6.0
- Notary: 0.6.0

None of the `docker-compose` commands work. They all exit with a popup and the error:

![image](https://user-images.githubusercontent.com/260518/38041984-6bd5d12c-32b3-11e8-8db9-26a169a0ab15.png)

> `Error loading Python DLL 'C:\Users\XYZ\AppData\Local\Temp\_MEI238842\python36.dll'. LoadLibrary:`

## Steps to reproduce the issue

1. Update D4W
2. Try to run `docker-compose`

## Additional information

- **Windows 10** 1703 build 15063.540

**Comment by davidhund** [comment]
@shin- Thank you for your quick reply!
It's my work machine, so I cannot check a.t.m. (will double-check tomorrow morning) but I'm pretty sure it's _not_ (or not on my PATH at least: I remember trying `python -V` on the command line).

**Comment by MatiasManevi** [comment]
Same issue here. Windows 7 64bits

Docker version
`Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:54 2018
  OS/Arch:      linux/amd64
  Experimental: false
`

**Comment by omereis** [comment]
I had similar problem.
Somehow, the TMP environment variable was set to "...\Local\TEMP;", with the semicolon.
Once I've removed it, the problem disappeared.

**Comment by vietplayfuri** [comment]
Hi guys,
Do we have any other update on this one ? Today I got the same issue like this
Below are my information:
Docker version
`Client:
Version 18.06.1-ce-win73 (19507)
Channel: stable
b0f14f1

Windows:
Windows 10 Enterprise N 2016 LTSB
Processor: i7 7820HQ 
Ram: 32 gb
System: 64 bits

----
And I got problem when trying use docker-compose

![image](https://user-images.githubusercontent.com/12247193/44942199-c7b5ff00-add6-11e8-8a9f-f54570de9307.png)

---- Anyone has any idea ?
Thank you

**Comment by mrinalnandi** [comment]
Had Same issue. Figure out, In my office laptop, I do not have access to execute any program in temp folder. Once redirected the temp folder location to another path where I have full access using windows environment variable, I was able to execute the docker-compose command without any issue.
