### ISSUE TITLE
docker-compose fails with invalid volume specification

### ISSUE THREAD

**Issue by uglydawg** [docker/compose#5842]
## Description of the issue
docker-compose fails with invalid volume specification

## Context information (for bug reports)
Output of "docker-compose version"
PS C:\temp> docker-compose --version
docker-compose version 1.20.1, build 5d8c71b2

Output of "docker version"
PS C:\temp> docker --version
Docker version 18.03.0-ce, build 0520e24

Output of "docker-compose config"
PS C:\temp> docker-compose config
networks:
  default:
    external: true
    name: nat
services:
  test:
    image: microsoft/windowsservercore
    volumes:
    - /c/temp:/data:rw
version: '3.6'

## Steps to reproduce the issue
PS C:\temp> docker-compose -f c:\temp\docker-compose.yml up --build
Creating temp_test_1 ... error

ERROR: for temp_test_1 Cannot create container for service test: invalid volume specification: '/c/temp:/data:rw'

ERROR: for test Cannot create container for service test: invalid volume specification: '/c/temp:/data:rw'
ERROR: Encountered errors while bringing up the project.

### Observed result
Expected to build image with volume mapped.

### Expected result
Error: invalid volume specification

### Stacktrace / full error message
[18:26:01.536][WindowsDaemon  ][Info   ] debug: FIXME: Got an API for which error does not match any expected type!!!: invalid volume specification: '/c/temp:/data:rw'
github.com/docker/docker/volume.errInvalidSpec
	/go/src/github.com/docker/docker/volume/volume.go:230
github.com/docker/docker/volume.windowsSplitRawSpec
	/go/src/github.com/docker/docker/volume/windows_parser.go:87
github.com/docker/docker/volume.(*windowsParser).parseMountRaw
	/go/src/github.com/docker/docker/volume/windows_parser.go:305
github.com/docker/docker/volume.(*windowsParser).ParseMountRaw
	/go/src/github.com/docker/docker/volume/windows_parser.go:301
github.com/docker/docker/daemon.(*Daemon).registerMountPoints
	/go/src/github.com/docker/docker/daemon/volumes.go:146
github.com/docker/docker/daemon.(*Daemon).setHostConfig
	/go/src/github.com/docker/docker/daemon/container.go:215
github.com/docker/docker/daemon.(*Daemon).create
	/go/src/github.com/docker/docker/daemon/create.go:173
github.com/docker/docker/daemon.(*Daemon).containerCreate
	/go/src/github.com/docker/docker/daemon/create.go:75
github.com/docker/docker/daemon.(*Daemon).ContainerCreate
	/go/src/github.com/docker/docker/daemon/create.go:34
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersCreate
	/go/src/github.com/docker/docker/api/server/router/container/container_routes.go:468
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersCreate)-fm
	/go/src/github.com/docker/docker/api/server/router/container/container.go:47
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1
	/go/src/github.com/docker/docker/api/server/middleware/experimental.go:27
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1
	/go/src/github.com/docker/docker/api/server/middleware/version.go:62
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1
	/go/src/github.com/docker/docker/pkg/authorization/middleware.go:59
github.com/docker/docker/api/server/middleware.DebugRequestMiddleware.func1
	/go/src/github.com/docker/docker/api/server/middleware/debug.go:53
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1
	/go/src/github.com/docker/docker/api/server/server.go:137
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1918
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP
	/go/src/github.com/docker/docker/api/server/router_swapper.go:29
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2619
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1801
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337 [module=api error_type=*errors.fundamental](if applicable)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Windows 10 Pro
Installed with Docker for Windows

**Comment by shin-** [comment]
You probably need to unset COMPOSE_CONVERT_WINDOWS_PATHS in your environment

**Comment by uglydawg** [comment]
I don't see COMPOSE_CONVERT_WINDOWS_PATHS set anywhere. I manually set it to 0 and it still fails.

**Comment by shin-** [comment]
Oh, sorry, did you actually write your mount like this? `/c/temp:/data:rw`
If so, you need to rewrite it correctly: `C:\temp:/data:rw`

**Comment by uglydawg** [comment]
I have tried just about every possible combination. The volume mapping works correctly when using just docker.

**Comment by keskarshreesh** [comment]
I'm facing the same issue for docker-compose up

**Comment by kaushikdasroy** [comment]
any solution to this, facing same issue

**Comment by talamus** [comment]
Same problem here, OS is Win10 and software is the newest version.

I think this is something that used to work when Docker for Windows had the "Shared Drives" setup screen: ![d4w-shared-drives](https://user-images.githubusercontent.com/1710153/42376731-ee8e441e-8128-11e8-996b-4c3ba0cd3f49.png)
That setup screen does not exist anymore.

Anyhow, "docker run" works fine with volumes. It is the "docker-compose up" that breaks down with "invalid volume specification" error.

**Comment by talamus** [comment]
Okay, so it seems to work after all, kind of.
I am using Windows containers, and they are bit different in every possible way...

If I create a volume in Dockerfile:
```
FROM microsoft/nanoserver
SHELL ["powershell.exe", "-Command"]
VOLUME C:/volume
```

And then use it in docker-compose.yaml:
```
version: "3"
services:
  localnano:
    build: .
    volumes:
      - testvolume:C:/volume
volumes:
  testvolume:
```

The files do start to appear in here:
```
PS> ls (docker volume inspect composer_testvolume --format '{{.Mountpoint}}')
```
BUT I cannot change the location freely, because of this:
https://github.com/sixeyed/docker-windows-kb/blob/master/1.13/limitations/volumes/driver-opts-not-supported.md

(I think it would really help if someone would re-write the docker-compose tutorial to be Windows compliant, or create a separate "Windows Errata" to list all the tiny differences...)

**Comment by usbook** [comment]
today I encountered the same problem today and it took a long time to solve him.I am loading Docker for Windows.First convert docker to switch to linux containers, then set the volume in the settings, then vs re-add docker support, it will be solved

**Comment by eduherminio** [comment]
@usbook That also worked for me, but I have to do it now in a virtual machine (no possibility to switch to Linux containers).
Any ideas?

**Comment by hamzam1995** [comment]
I'm also facing the same issue. I've written a docker-compose file for wordpress and mysql and this error appears. I only want to use docker as windows containers. Has anybody got some solution for me and wants to share it. Thanks :)

**Comment by JoseFMP** [comment]
Same problem over here.

**Comment by voidzcy** [comment]
Even linux user get the same issue...

**Comment by rnrneverdies** [comment]
I'm also facing the same issue running Windows Containers with experimental features enabled. I switched back to use Linux Containers and started working. Hope that helps

**Comment by FloatingShuYin** [comment]
+1

**Comment by imkhairulikhwan** [comment]
I'm using the latest version of Docker Desktop 2.1.0.6 and it seems if we specify the volume as following:
.\src\Health.Website:C:\src, we need to ensure the environment variable COMPOSE_CONVERT_WINDOWS_PATHS is set to false/0. It works fine for me.

**Comment by ewdwitkowski** [comment]
My observation made on mongo:windowsservercore is, that if you use windows container, you need to pass volume sign of container OS

```
services:
  mongo:
    image: mongo
    hostname: mongo-server
    ports:
      - 27017:27017
    volumes:
      - d:/data:c:/data/db
```

missing **c:** was the reason I had invalid volume specification.

**Comment by yujieyzjh** [comment]
Path is probably not converted to unix style. Since 1.9.0, Windows paths are not automatically converted (eg. C:\Users to /c/Users).

Solution: Set COMPOSE_CONVERT_WINDOWS_PATHS environment variable to “true” or “1”.

**Comment by vbose007** [comment]
Had the same issue trying to create linux container on windows machine using docker compose. I am using Docker Desktop.  
Realized that my Docker Desktop was set to use Windows containers. Switching it to Linux containers fixed the issue. (Just right click on the Docker Desktop icon on the taskbar).

Hope this helps

**Comment by lmcghee** [comment]
Just to throw my hat into the ring -- I came across error and was able to fix it by updating docker to the latest version. Not sure if this is related to the original question but it fixed the error for me and hopefully can for others as well.

**Comment by bvrulez** [comment]
I have the same or a similar problem. I run an Ubuntu 20.04 in a Virtualbox on Windows 10 and I was able to successfully run `docker-compose up` yesterday several times and accessing `http://127.0.0.1:8005/`. I even ran `docker exec docker-moloch_moloch_1 moloch-parse-pcap-folder.s`. 

I changed the `MOLOCH_PASSWORD` but was still able to connect to `8005`. After shuting my OS down and bringing it up again I am not able to run it:

```
$ docker-compose up
Starting docker-moloch_elasticsearch_1 ... done
Recreating dc3e21ddd650_docker-moloch_moloch_1 ... error


ERROR: for dc3e21ddd650_docker-moloch_moloch_1  Cannot create container for service moloch: invalid volume specification: '405693aafba87168169f58d510ebbfa3759c65c012ecf595129dbe3b7538dc32:data/moloch/logs:rw': invalid mount config for type "volume": invalid mount path: 'data/moloch/logs' mount path must be absolute

ERROR: for moloch  Cannot create container for service moloch: invalid volume specification: '405693aafba87168169f58d510ebbfa3759c65c012ecf595129dbe3b7538dc32:data/moloch/logs:rw': invalid mount config for type "volume": invalid mount path: 'data/moloch/logs' mount path must be absolute

```

**Comment by davclark** [comment]
It looks like folks are still using this issue as documentation, since Windows paths are somewhat unloved here. I can try to track it down if needed, but the core Docker for Windows team has settled on `C:` style paths as the canonical path format when you're mounting things from Windows. Of course, ideally, you should run docker from WSL2 and mount from there - it'll be way faster.

**Comment by JasonFoglia** [comment]
I ran into this same issue. 

This works for me: MacOS Docker 3.0.0

docker run -d --name myname -v "$PWD/Users/myusername/Documents":/docs myimage

docker commit to fix broken images.

**Comment by sjetha** [comment]
I was able to solve this by changing

```
volumes:
  - .:\code
```

to
```
volumes:
  - .:c:\code
```

It's easy to forget how the file systems different if you don't switch between them often.

**Comment by arakakiv** [comment]
I get this error when I try to change the ports, in docker compose file.

**Comment by pjpepperneck** [comment]
I had this error when deploying a Directus extension "invalid volume specification: ':/directus/extensions'" to a Directus instance on a Linux Docker Container on an Azure App Service. Turns out Azure App Services now sets the app setting WEBSITES_ENABLE_APP_SERVICE_STORAGE to false by default, changing this to true fixed the issue for me. Hope this can help someone else!

**Comment by karan182020** [comment]
By setting this command, it works for me. I was running the docker commands within IntelliJ terminal. 
![image](https://github.com/docker/compose/assets/26721357/cd2c8e6d-76dc-45a8-8c9a-85fb070df769)

**Comment by IssacKramer** [comment]
Now , at 01.2024 I also had this problem for whole 2 days on Docker Desktop for windows ver 4.27.0 (135262) 
The problem as you @karan182020 said. Just to emphasize YOU NEED TO PUT QUOTES over "true", that is :
COMPOSE_CONVERT_WINDOWS_PATHS=**"true"** (with quotes) . **NOT 1 , NOT true, but => "true"**

**Comment by daoudasylla** [comment]
Adding COMPOSE_CONVERT_WINDOWS_PATHS="true" works for me too.
Thanks
