### ISSUE TITLE
docker-compose should reflect changes to source code

### ISSUE THREAD

**Issue by sukhbir-singh** [docker/compose#5847]
Each time, I change even a single line in source code i need to close the current docker-compose run by pressing ctrl+c then start a new one using command `docker-compose up`.

Is their exist any command for docker-compose so that I donot need to restart docker-compose everytime and it automatically rebuilds using the changed and latest source code.

Thank you

**Comment by shin-** [comment]
https://docs.docker.com/compose/gettingstarted/#step-7-update-the-application

Please use the forums for additional support
