### ISSUE TITLE
`GLIBC_2.14' not found

### ISSUE THREAD

**Issue by michaelknurr** [docker/compose#5849]
## Description of the issue
When upgrading docker compose to a version later than 1.19.0 i get an error

```
$ sudo curl -L https://github.com/docker/compose/releases/download/1.20.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
```
```
$ docker-compose --version
docker-compose: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIb0wktP/libz.so.1)
```

Whereas the version 1.19.0 still runs fine 
```
$ sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
```
```
$ docker-compose --version
docker-compose version 1.19.0, build 9e633ef
```

## Context information (for bug reports)
OS release: CentOS release 6.9 (Final)
```
Output of "docker-compose version"
```

```
Output of "docker version"
```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64

```
Output of "docker-compose config"
```

## Additional information
it seems like there is a possible relation to #102 https://github.com/docker/compose/issues/102

OS version / distribution, `docker-compose` install method, etc.

**Comment by shin-** [comment]
This probably means you need a more recent version of glibc. Related: https://unix.stackexchange.com/questions/176489/how-to-update-glibc-to-2-14-in-centos-6-5

Alternatively, you can install the newer versions using `pip`.

**Comment by rainabba** [comment]
I just hit this and after investigating, realized that my docker-compose.override.yml had a volume that effectively caused my containers node_modules folder to reflect my local (not the built one) and so my container was trying to execute a binary built off different dependencies that didn't play well.

Insidious :)

**Comment by alexandervlpl** [comment]
@rainabba So what was the solution for you? I don't have a `docker-compose.override.yml`.
