### ISSUE TITLE
build complains "Volume foo declared as external but specifies additional attributes (driver)."

### ISSUE THREAD

**Issue by deas** [docker/compose#5859]
## Description of the issue

`docker-compose build` aborts when there is an external volume declared.

## Context information (for bug reports)

```
docker-compose version 1.20.1, build 5d8c71b
```

```
Docker version 18.03.0-ce, build 0520e24
```

## Steps to reproduce the issue

Make sure to have an external volume such as
```
volumes:
  foo:
    external: true
    driver: rancher-nfs
```
in `docker-compose.yml`.

and run
                        
`docker-compose build`

### Observed result
I end up:
```
ERROR: Volume foo declared as external but specifies additional attributes (driver).
```
### Expected result
The build should work, the external nature of the volume should not matter.

**Comment by shin-** [comment]
The behavior is correct. Your Compose file is invalid and no operation can be performed with an invalid file.

**Comment by deas** [comment]
Still, volumes don't matter in a build context, right?

How are you supposed to deal with the situation? Maintain two different compose files?

**Comment by deas** [comment]
I am trying to use a single `docker-compose.yml` file in `docker-compose build` and `rancher up` context. Seems at this time, there is no way around two files. Unfortunately, simply providing `docker-compose` a second  `docker-compose-build.yml`  file just overriding the volumes does not work.
