### ISSUE TITLE
Update documentation to indicate that build / cache_from is available in 2.x

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/compose#5860]
The `cache_from` option, mapping to `docker build --cache-from <image>`, was introduced into Compose version [1.12](https://github.com/docker/compose/blob/master/CHANGELOG.md#1120-2017-04-04) or [1.17](https://github.com/docker/compose/blob/master/CHANGELOG.md#1170-2017-11-02), depending on which release note is correct, but only in the Compose file format 3.x.

Folks are still using 2.x and expect this version to be maintained with respect to Docker updates!

**Comment by shin-** [comment]
Looks like an omission in the docs - please create an issue on the [docs repo](https://github.com/docker/docker.github.io/). 

As for the 2.4 format, it hasn't been released yet, hence why it's not currently in the documentation.

**Comment by AnthonyMastrean** [comment]
Is it possible to update the relevant Release Notes on this site, in the meantime?
