### ISSUE TITLE
Changelogs are outdated and inconsistent

### ISSUE THREAD

**Issue by funkyfuture** [docker/compose#5871]
The [github release page for 1.21.0](https://github.com/docker/compose/releases/1.21.0) Changes section lists changes that are from some release in the past.

The [`CHANGES.md`](https://github.com/docker/compose/blob/master/CHANGELOG.md) doesn't include any information about the 1.21.0 release at all.

**Comment by shin-** [comment]
The notes on the release page are accurate for 1.21.0.

I just updated CHANGELOG.md with the latest - my bad for lagging behind on that one.

**Comment by funkyfuture** [comment]
thanks for addign the info.

the release page has 'Compose file version 2.4' as first item of new features. that was a while ago, wasn't it?

**Comment by shin-** [comment]
No - 2.4 was just added!

**Comment by funkyfuture** [comment]
oh, sorry. my mistake.
