### ISSUE TITLE
docker-compose pip install fails with pip 10.0.0

### ISSUE THREAD

**Issue by soundsgoodsofar** [docker/compose#5883]
## Description of the issue

We're running docker-compose on CentOS.  The pip version when installed with --upgrade changed to 10.0.0 in the last couple days and our docker install (pip install docker-compose) began failing with the following message.  It appears that pip 10.0.0 has increased the version dependency of package `requests` to 2.6.0, which is incompatible with the default docker-compose installation.

## Context information (for bug reports)

```
Output of "docker-compose version"
N/A
```

```
Output of "docker version"
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:09:15 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:13:03 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

```
Output of "docker-compose config"
N/A
```

## Steps to reproduce the issue

1. Install CentOS 7
2. yum install -y epel-release
3. yum install -y python-pip
4. pip install --upgrade pip
5. pip install docker-compose

### Observed result

Install fails

### Expected result

Install succeeds

### Stacktrace / full error message

```
$ pip install docker-compose
...
  Found existing installation: requests 2.6.0
Cannot uninstall 'requests'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by ningthoujam-lokhendro** [comment]
I have the same issue. Workaround for now would be not to upgrade the pip to 10.x.

**Comment by hermesian** [comment]
:+1:

**Comment by jamiejackson** [comment]
Also an issue on RHEL 7.4. Temporarily working around the problem by doing the same as @hermesian, using:

`sudo pip install --upgrade --force-reinstall pip==9.0.3`

**Comment by shin-** [comment]
After looking at this more closely, it looks like this is mostly a `pip` / Linux distribution issue:
- https://github.com/pypa/pip/issues/4805
- https://github.com/pypa/pip/issues/5247

My takeaway here is that it's not Compose's responsibility to fix, nor would we be able to even if we wanted to. 

Downgrading `pip` is probably a reasonable course of action for the short term (other reasonable options: `virtualenv`, Compose binaries). In the long term, the way `yum` installs some Python packages probably needs to change.

**Comment by qxp99999** [comment]
The same question

**Comment by Sabya1981** [comment]
And the issue still persists....

**Comment by princebillyGK** [comment]
I have solved this issue using python3.
At first I checked if python3 is installed
<img width="277" alt="image" src="https://user-images.githubusercontent.com/42868891/154114789-47899654-7127-469c-b956-b66e9976498d.png">
Then I find all the available python paths:
<img width="718" alt="image" src="https://user-images.githubusercontent.com/42868891/154114947-7c79b262-7805-48a0-83ff-4bbd62f3bba8.png">
And finally, I used `update-alternatives` to make python3 default
<img width="692" alt="image" src="https://user-images.githubusercontent.com/42868891/154115132-28e51b68-d6e7-411f-abc4-f36005832849.png">

**Comment by naomatheus** [comment]
@ghost 
This solution worked for me as well on EC2. 

```
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
```

Followed by:
```
python --version 
>> 3.9.xx

pip install docker-compose
```
Success.

**Comment by pkilpo** [comment]
Did not work for me even python3.
```
[ec2-user@ip-10-232-145-56 ~]$ python --version
Python 3.9.16
[ec2-user@ip-10-232-145-56 ~]$

 sudo pip3 install docker-compose
...

 Found existing installation: requests 2.25.1
ERROR: Cannot uninstall requests 2.25.1, RECORD file not found. Hint: The package was installed by rpm.

```
