### ISSUE TITLE
How to disable binding to localhost?

### ISSUE THREAD

**Issue by POD666** [docker/compose#5887]
I'm trying to run few projects that have services that expose same ports.

I have found the same unanswered question [here](https://stackoverflow.com/questions/45109398/how-can-i-make-docker-compose-bind-the-containers-only-on-defined-network-instea).

When I try to run second project I get 
`Bind for 0.0.0.0:8000 failed: port is already allocated` 

First project is available at localhost and its subnet. I don't want it to be available on localhost.
How to do that?
```
$ docker -v
Docker version 18.03.0-ce, build 0520e24
$ docker-compose -v
docker-compose version 1.17.0, build ac53b73
```

**Comment by shin-** [comment]
Please use the [forums](https://forums.docker.com) for support!
