### ISSUE TITLE
Variable number of volumes

### ISSUE THREAD

**Issue by aalexgabi** [docker/compose#5902]
## Description of the issue
I need a dynamic list of volumes in docker-compose.yml:
```
services:
  my-app:
    volumes:
      {{
        MODULES=($(ls modules))
        for MODULE in ${MODULES[@]} ; do
          echo "- ./lib:/opt/my-app/modules/$MODULE/lib"
        done
      }}
```

Here is a more generic question: how do you substitute variables that contain arrays or objects of yml values? Is there a way to have dynamic number of entries for any docker-compose.yml array entry?

**Comment by shin-** [comment]
Compose files do not support templating ; that feature is out of scope for Compose.

The recommended approach if you need to do this is to write a template and generate the Compose file upstream before feeding it to `docker-compose`.

HTH
