### ISSUE TITLE
Enable proxy import from from config.json to be disabled

### ISSUE THREAD

**Issue by jon-m-c** [docker/compose#5903]
## Description of the issue
In Release 1.20.0 an new feature was added 

"Proxy configuration found in the ~/.docker/config.json file now populates environment and build args for containers created by Compose"

It should be possible to disable this feature at runtime, for example, with a flag

docker-compose up --no-proxy-import ......

The reason for this is that you may wish to use the proxy for docker builds, but not for all run time containers. Currently, if there is a proxy set in the config.json, it is always set in the running containers.

**Comment by shin-** [comment]
Hi @jon-m-c 

If you only need the setting for builds, then `config.json` is definitely the wrong place to set these in the first place. Use [build args](https://docs.docker.com/engine/reference/builder/#predefined-args) instead.
As it stands, the feature is on par with the Docker CLI equivalent. I don't think such a flag is warranted, or a good idea.
