### ISSUE TITLE
Don't use red for CLI output unless there's an error

### ISSUE THREAD

**Issue by tedivm** [docker/compose#5905]
## Description of the issue

I'll admit this is kind of a silly request, but I think it would be nice if docker-compose avoided using the "red" cli text during normal operations. For most tools red means something bad happened, so I (and at least [eighteen other people](https://github.com/docker/compose/issues/4269#issuecomment-310674410)) think the CLI would be much better if it didn't use red.

**Comment by shin-** [comment]
Running `git diff` must be an adventure for all 19 of you. :wink: 

Feel free to make a PR for it.

**Comment by tedivm** [comment]
I'll definitely make a PR, I just wanted to make sure it would be appreciated first :-)
