### ISSUE TITLE
Missing secret error message could be clearer

### ISSUE THREAD

**Issue by jsharpe** [docker/compose#5920]
## Description of the issue

If running in non swarm mode with compose file v3 the following is an example of an error you get when a secret is missing:

ERROR: for app  Cannot create container for service app: invalid mount config for type "bind": bind source path does not exist

docker-compose should check for existence of the source path and provide a user friendly error if it doesn't exist.

**Comment by tonyzhoujingtao** [comment]
I am not exactly sure what this means.

If this error occurs when a secret if missing, what does it have to do with the existence of source path?

Can you please elaborate?

**Comment by jsharpe** [comment]
Note that this doesn't relate to docker secrets as in the core secret functionality - it refers to docker-compose's fallback path if it has a secret definition and it's being deployed by docker-compose up rather than via docker stack deploy. In this case any secrets referred to in the compose file are mounted as volume mounts rather than real secrets, so the error occurs if the source path for the secret does not exist.

**Comment by craigbarrau** [comment]
Yes! Wasted a lot of time on this one :)
Would love to fix it

**Comment by konstunn** [comment]
Is the issue resolved?

**Comment by ulyssessouza** [comment]
@konstunn Yep
