### ISSUE TITLE
ip range causes compose file to fail validation

### ISSUE THREAD

**Issue by cstaabenKoch** [docker/compose#5923]
## Description of the issue

When running `docker-compose up`, the Compose file is falsely flagged as invalid when using `ip_range` in `ipam.config` with this error:

```
networks.default.ipam.config value Additional properties are not allowed ('ip_range' was unexpected)
```

Despite being documented as a valid option: https://docs.docker.com/compose/compose-file/compose-file-v2/#ipam

### Versions

```
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

### Config

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default.ipam.config value Additional properties are not allowed ('ip_range' was unexpected)
```

## Steps to reproduce the issue

1. Create a Compose file that specifies an `ip_range` in `ipam.config`
2. Attempt to use the Compose file

### Observed result

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default.ipam.config value Additional properties are not allowed ('ip_range' was unexpected)
```

### Expected result

The command should succeed with a valid Compose file.

## Additional information

Running High Sierra v10.13.4.

**Comment by Gobd** [comment]
Looks like it was changed to `iprange`, should probably be put back to `ip_range` to match docs. https://github.com/docker/compose/commit/398b13d345dbd013eb92234a90134bc3b4572a43

**Comment by shin-** [comment]
Thanks for the report!

**Comment by proswdev** [comment]
Doesn't appear just a name change. Renaming to iprange in docker-file avoids error but iprange: 172.16.1.0/24 still allocates container ip's from 172.16.0.x.

**Comment by rsteppac** [comment]
And unless @shin- made a typo the parameter went from "ip-range" to "iprange" to "ip_range".

**Comment by Gobd** [comment]
Until you can auto-update to this release you can download and use a build [here](https://github.com/docker/compose/releases/tag/1.21.2) for a temporary fix. Just download the file, `chmod +x ~/Downloads/docker-compose-Darwin-x86_64`, then `~/Downloads/docker-compose-Darwin-x86_64 up` in the the dir with your docker-compose file. Just replace with your path & filename.

**Comment by proswdev** [comment]
Thanks. That worked.
