### ISSUE TITLE
[Minor] Obsolete release notes from https://docs.docker.com/release-notes/docker-compose/

### ISSUE THREAD

**Issue by fodger** [docker/compose#5951]
Hi,
it's minor but release notes from https://docs.docker.com/release-notes/docker-compose/ concerns 1.21.0 version, not the 1.21.2.

I guess it is about fixes, but it is always good to know.

Thanks all team for your incredible work !

**Comment by shin-** [comment]
- For documentation issues, use https://github.com/docker/docker.github.io
