### ISSUE TITLE
ERROR when: "docker-compose up connainer" from INSIDE container

### ISSUE THREAD

**Issue by FractalMind** [docker/compose#5956]
For our app we try to restart the nginx-gen with docker-compose so it can reload a .envfile into the container. We can easily do that in the host with 
```
#docker-compose up -d nginx-gen
nginx-gen is up-to-date
```

When I share _docker.sock_ I can **docker-compose ps** with no problem
## BUT I cannot reload nginx-gen FROM inside my other container where my code is.

```
root@796fbb6c59ce:/mnt/Docker# docker-compose up -d nginx-gen
Creating nginx-gen ... error

ERROR: for nginx-gen  Cannot create container for service nginx-gen: Conflict. The container name "/nginx-gen" is already in use by container "0459ac04cad31e2fe6e4e6266608ee74d0f02b172e5fb12e260a00a0bcc27a27". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for nginx-gen  Cannot create container for service nginx-gen: Conflict. The container name "/nginx-gen" is already in use by container "0459ac04cad31e2fe6e4e6266608ee74d0f02b172e5fb12e260a00a0bcc27a27". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
```
## How can I reload the config of nginx-gen from my other container!?
Thank you for your time :)

**Comment by ebuildy** [comment]
Can you try to force the ``COMPOSER_PROJECT`` to be the same in the 2 environments?

And if you run ``docker-compose ps`` inside the container ?

**Comment by FractalMind** [comment]
Thx @ebuildy for your answer. I actually mounted the project folder inside the container... So they are virtually identical.
If I run `docker-compose ps`... It will list all my containers as if I was in the host. I can restart(won't load new config), stop, kill, rm... but I can't "up" any of them... I get the error you saw

**Comment by shin-** [comment]
What @ebuildy wrote is correct, your issue most likely comes from a mismatch between your project name inside and outside the container. That can be remediated using the `COMPOSE_PROJECT_NAME` env variable.

In the future, please use the provided issue template.
