### ISSUE TITLE
docker-compose pull does not show progress anymore

### ISSUE THREAD

**Issue by snkshukla** [docker/compose#5960]
## Description of the issue
Recently, `docker-compose pull` has stopped showing the progress. For big images, it just takes forever to download, the progress is really helpful.

I remember that this should only happen when you use `--quiet` flag with the command.

## Context information (for bug reports)

```
Output of "docker-compose version"
```
docker-compose version 1.21.0, build 5920eb0
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```
Output of "docker version"
```
Client:
 Version:      18.05.0-ce-rc1
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   33f00ce
 Built:        Thu Apr 26 00:58:56 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce-rc1
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   33f00ce
  Built:        Thu Apr 26 01:06:49 2018
  OS/Arch:      linux/amd64
  Experimental: true

## Steps to reproduce the issue

1. run `docker-compose pull`

### Observed result
![screen shot 2018-05-14 at 11 21 12 am](https://user-images.githubusercontent.com/16763730/39980535-0e847114-576a-11e8-8c53-444a211a8012.png)

### Expected result
It should show the progress, something like this:
<img width="496" alt="screen shot 2018-05-14 at 11 31 26 am" src="https://user-images.githubusercontent.com/16763730/39980602-671c1606-576a-11e8-8406-5a09a3033435.png">

## Additional information

OS version / distribution, `docker-compose` install method, etc.
macOS High Seirra version 10.13.4, docker-compose install method brew

**Comment by pschirch** [comment]
Yes, please revert to the progress feature.

**Comment by ebakke** [comment]
agreed. it'd sure be nice to know what I was downloading, and how much more I have to go.

**Comment by dpenev** [comment]
Same issue here but I am more interested in the Status that is also missing not only the progress. 

docker-compose -v
docker-compose version 1.21.2, build a133471
Installed from binary on CentOS 7

In my case I am expecting docker-compose pull to get latest image 
The default output of pull is reporting "done" even if there is no new image downloaded 
# docker-compose pull 
Pulling mydockerimage ... done

With the parallel mode off the output includes Status 

 docker-compose pull --no-parallel
 ...
 Status: Downloaded newer image for ...

or 

 docker-compose pull --no-parallel
 ...
 Status: Image is up to date for  ...

So I at the moment I am not able to enjoy the benefits of parallel mode :) as I need to status to trigger following events in my automated deployment workflow.

**Comment by shin-** [comment]
This is a result of parallel pull becoming the default, which requires a simpler output in order to keep things readable by humans. As @dpenev points out, if you wish to revert to the old behavior, use the `--no-parallel` flag.

As it is however, this is working as intended.

**Comment by dpenev** [comment]
Progress or no progress when in parallel, the lack of Status makes impossible to detect a change has been made to local  as result of **docker-compose pull** 
Also makes the docs False https://docs.docker.com/compose/reference/pull/ , as the example at the end is incorrect. 
Without the status, when new latest image is pulled the command returns done exit code 0. 
When no new image is downloaded, again done exit code 0. 
So in order to use the default mode of **docker-compose pull** I need to:
1.  call docker images capture sha of latest
2.  execute docker-compose pull 
3.  call docker images capture sha again and compare 
Making this highly unpractical to include **docker-compose pull** in it's default behavior, as trigger in automated deployment.

**Comment by chrisharrisonkiwi** [comment]
Agreed, while this is not a bug, the feature of the progress bar was really useful.
At least an updating percent or time estimate would be fantastic.

**Comment by shin-** [comment]
For people following this issue - is #6100 helpful? Feedback would be appreciated.

**Comment by benyanke** [comment]
I'd also love to see progress on pulls. My daily driver is a laptop, connections are sometimes spotty.
