### ISSUE TITLE
Escaping Dollar Sign for strings in docker compose

### ISSUE THREAD

**Issue by rhuanbarreto** [docker/compose#5965]
Just for the start. This is not an issue about environment variable expansion.

I have a definition for a MariaDB:

image: mariadb:10.2
    restart: always
    environment:
      - MYSQL_USER=blabla
      - MYSQL_PASSSWORD=123$abc

This raises the warning: Variable abc is not set. Defaulting to a blank string.

There is lots of topic talking about environment variable expansion. But none of them talk about $ escaping.

Can you help?

**Comment by philiporlando** [comment]
The `$$` workaround doesn't help for projects that share a single `.env` between Docker Compose and local development via python-dotenv. python-dotenv doesn't recognize `$$` as an escape sequence, so a value like `MY_VAR=foo$$bar` is read correctly by Compose (as `foo$bar`) but incorrectly by python-dotenv locally (as `foo$$bar`). 

Is there a recommended way to handle this without maintaining separate `.env` files for each context?
