### ISSUE TITLE
Change command name from down to clear, clean or purge

### ISSUE THREAD

**Issue by lgcosta** [docker/compose#5971]
The name `down` is very confusing to specify the stop and removing of the containers and the environment. Generates confusion with the `stop` command, being namesake to leave an environment down, without cleaning.

I think it's more consistent to use a `clean`, `clear` or `purge` variant command name, example:

```
clean               Stop and remove containers, networks, images, and volumes
```

Thanks

**Comment by Greek64** [comment]
I'm by now used to the "down" command, but I totally agree with this request.
The "down" name does not at all reflect the effect of the command.

**Comment by shin-** [comment]
Thanks for the feedback. `down` is intended to mirror `up`. We're happy with the name and don't intend to change or alias it at this point in time.
