### ISSUE TITLE
Windows 7 with boot2docker support for fig

### ISSUE THREAD

**Issue by longieirl** [docker/compose#598]
Great experience on a mac running boot2docker and fig, managing my project docker containers! Experience on windows hasn't been great...can load boot2docker, run the different docker containers individually but havent found a solution to getting fig installed! Our project supports different OS and it would be nice to a nice windows experience for developers.

Any links or custom ISO's with fig installed would be great.

J

**Comment by rjoxford** [comment]
Amateur question... Where do I add this in? Using Windows 8.1, no idea where to put this. Can't find any bottlocal.sh file... And what would the next steps be? Thanks

**Comment by blaggacao** [comment]
@rjoxford I added this within the boot2docker image at the described position, so it's within your VM. As boot2docker is largely a non-persisten file system, changes would get lost over a reboot of your VM, but bootlocal.sh resides on a persisten part of the filesystem and like this can write the entry into the aliases every time boot2docker botsup (it is called automaticaly for that purpose).

**Comment by dduportal** [comment]
Related to https://github.com/docker/fig/issues/599.

 colleague of mine is currently woking on 64-izing boot2docker (network purpose), see https://forums.docker.com/t/32-bits-64-bits-and-tiny-core-linux-6-0-as-a-base-for-boot2docker-iso/722.
Maybe it'll help to run fig inside b2d ?

Otherwise i propose to run fig inside a container : https://registry.hub.docker.com/u/dduportal/fig/ (but it's not the easiest way, see https://github.com/dduportal/dockerfiles/issues/4 for example)

**Comment by mikehaertl** [comment]
@blaggacao Thanks for the hint on how to install fig. It seems to (almost) work fine. But I have a pretty weird problem now: I try to run a Dockerfile / fig.yml from my repo here:

https://github.com/codemix/yii2-dockerized

This exactly same file works great under Linux und Mac OS X. But if I run this from boot2docker on windows I get this error on `fig up`:

```
web_1 | AH00526: Syntax error on line 38 of /etc/apache2/apache2.conf:
web_1 | DocumentRoot must be a directory
yii2_web_1 exited with code 1
```

Even though the DocumentRoot definitely exists. And the container even starts if I use `docker run ...` directly. 

Any idea, what could go wrong here?

**Comment by mikehaertl** [comment]
Ok, I found it out. With the dockerized `fig` you have to use absolute host paths for shared volumes.

This won't work:

```
    volumes:
        - ./:/var/www/html/
```

Whereas this will work:

```
    volumes:
        - /c/Users/Mike/Documents/yii2:/var/www/html/
```

**Comment by bfirsh** [comment]
I have created an issue to keep track of this: #1085. Thanks for reporting!
