### ISSUE TITLE
Logs stopping abruptly when starting services without -d flag

### ISSUE THREAD

**Issue by rajeshyogeshwar** [docker/compose#5983]
Previous to upgrading my Ubuntu installation to 18.04 whenever I started my services with `docker-compose -f file up` all the output from containers was streamed consistently. But ever since the upgrade, the output from containers stops somewhere in between. I know a workaround is do start services with -d flag and then use logs -f to monitor them. But what might have gone wrong. For me starting services with -d and following it up with logs -f works fine but I would like to do it without it. 

**OS - Ubuntu 18.04 LTS
Docker - Docker version 18.05.0-ce, build f150324
Compose - docker-compose version 1.21.2, build a133471**

**Comment by JBertaux** [comment]
I had the same issue on :
Windows 10 and Ubuntu 16.04 LTS
Docker : 

- Windows : Docker version 18.03.1-ce, build 9ee9f40
- Ubuntu : Docker 18.03.0-ce

Compose : 

- 1.21 on all

I downgrade my docker-compose version to 1.19 and all it's fine but with 1.20 and 1.21 version I have the bug.

**Comment by shin-** [comment]
Closing - not only has this been asked before, but you didn't even bother to use the provided issue template.

**Comment by JBertaux** [comment]
We will stay on 1.19 for ever so, thanks for the quick reply 😄

**Comment by JBertaux** [comment]
For other people that have the similar issue, the problem comes when you install docker-compose by pip. With the binary's download there is not problem.
