### ISSUE TITLE
Instead of version number why don't use 'latest' it will help writing scripts to install docker-compose with the latest version.

### ISSUE THREAD

**Issue by Kuchiriel** [docker/compose#5987]
Instead of version number why don't use 'latest' it will help writing scripts to install docker-compose with the latest version.

**Comment by shin-** [comment]
If you're talking about the `docker/compose` image on Hub, it's meant to be exclusively used through the `run.sh` script, which is versioned.

We currently have no plans to add a `latest` tag.

**Comment by Kuchiriel** [comment]
I am talking about the releases tab.

**Comment by nvllsvm** [comment]
@shin- The run.sh cannot be used as a base image in, for example, a GitLab CI pipeline.
