### ISSUE TITLE
Not compatible with boot2docker's Tiny Core Linux

### ISSUE THREAD

**Issue by girvo** [docker/compose#599]
As per an issue report over on the `boot2docker` repository, Tiny Core Linux for boot2docker is running a 32-bit user-space on a 64-bit kernel, thus causing problems.

https://github.com/boot2docker/boot2docker/issues/603

Now, the releases show that there is only a 64-bit version, is that a hard requirement? Is it possible to recompile it for 32-bit user-space on TCL? 

The reason this is a big deal is that Windows users (half of my team!) need to run `fig` inside the `boot2docker` VM, as `docker` and `boot2docker` don't run on Windows in the same way as OS X.

If there's anything I can do to help, let me know!

**Comment by dduportal** [comment]
A colleague of mine is currently woking on 64-izing boot2docker (network purpose), see https://forums.docker.com/t/32-bits-64-bits-and-tiny-core-linux-6-0-as-a-base-for-boot2docker-iso/722.
Maybe it'll help to run fig inside b2d ?

**Comment by edmorley** [comment]
For people looking for a workaround in the meantime - the docker-compose Python package seems to work fine in boot2docker, even if the native binary doesn't.

See: https://github.com/boot2docker/boot2docker/issues/603#issuecomment-110033929

**Comment by tianon** [comment]
You can also give v1.7.0-rc2 a try (https://github.com/tianon/boot2docker/releases/tag/v1.7.0-rc2); it's finally got a 64bit userspace, so docker-compose's official binaries _should_ work as-is now. :+1:

**Comment by edmorley** [comment]
> You can also give v1.7.0-rc2 a try

Ah I totally missed that an RC had been released - thank you :-)

**Comment by dduportal** [comment]
Just added a PR for that : https://github.com/boot2docker/boot2docker/pull/932

**Comment by wharsojo** [comment]
incase window users want an easy installation docker-compose + tmux + zsh ( prezto - OMZ): 
https://github.com/boot2docker/boot2docker/issues/603#issuecomment-111883106

**Comment by lmakarov** [comment]
This issues can be closed.

Docker Compose can be installed in boot2docker starting v1.7.0 following the standard install process (only add `sudo`)
https://docs.docker.com/compose/install/

```
sudo curl -L https://github.com/docker/compose/releases/download/1.3.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

**Comment by josephpage** [comment]
:+1: @lmakarov

**Comment by aaronsturm** [comment]
@lmakarov - Pardon my ignorance, but can you expand on that?

Do you mean first running `boot2docker ssh` and then running `curl` & `chmod`? Is there a way to run docker-compose from the Windows command line like the docker command can? Thanks!

**Comment by lmakarov** [comment]
@aaronsturm,  Short-term - here's a quick shell script for you to install docker-compose into boot2docker (you can run from Git Bash on Windows).

https://gist.github.com/lmakarov/54302df8ecfc87b36320

See instructions in the gist comments.
I'm using `docker-machine` in the instructions. The same should work with the `boot2docker` cli, though I recommend switching to `docker-machine` anyway :)

You will be running docker-compose in the VM, it's still not available on Windows.

    docker-machine ssh <machine>  -- docker-compose --version

It should be possible to create a shell alias (Git Bash again) and use it as just `docker-compose`. I do not have a Windows box currently in my hands to try that.

Long-term - would be nice to have docker-compose pre-installed in boot2docker.
See the PR from @dduportal : https://github.com/boot2docker/boot2docker/pull/932
