### ISSUE TITLE
Interconnect Vagrant Virtual box to Docker Container on MAC

### ISSUE THREAD

**Issue by obenziane2** [docker/compose#5993]
## Description of the issue
1. I'm trying to  have vagrant (virtualbox) machine to be able to connect to Docker container. The bridge network is not an option here.. can someone please suggest a solution ?

Anyway i can assign an IP to a container reachable/pingable from vagrant or at least a host ?
## Context information (for bug reports)

```
Output of "docker-compose version"
```
docker-compose version 1.21.1, build 5a3f1a3
```
Output of "docker version"
```
18.03.1-ce
```
Output of "docker-compose config"
```

## Steps to reproduce the issue

1. I'm trying to  have vagrant (virtualbox) machine to be able to connect to Docker container. The bridge network is not an option here.. can someone please suggest a solution ?

Anyway i can assign an IP to a container reachable/pingable from vagrant or at least a host ?

### Stacktrace / full error message

```
(if applicable)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by shin-** [comment]
Not a Compose issue.
