### ISSUE TITLE
Can't pull docker compose image from dockerhub

### ISSUE THREAD

**Issue by egel** [docker/compose#6006]
## Description of the issue

This issue is directly related to images on docker hub (https://hub.docker.com/r/docker/compose/)

Users can't pull the image from docker. Missing the image with tag `latest` 

## Context information (for bug reports)
-

## Steps to reproduce the issue

1. `docker pull docker/compose`
2. Observe the error in terminal

### Observed result
The error in terminal
    
    → docker pull docker/compose
    Using default tag: latest
    Error response from daemon: manifest for docker/compose:latest not found

### Expected result

    → docker pull docker/compose:latest
    latest: Pulling from docker/compose
    605ce1bd3f31: Already exists
    ed764f565fce: Pull complete
    988404a576a5: Pull complete
    d69030722a7d: Pull complete
    2d6379878250: Pull complete
    d14800f53520: Pull complete
    Digest: sha256:97f49d34b6897df9cf023489075eb4dca15760c6e40b553313af8e760614a2e5
    Status: Downloaded newer image for docker/compose:latest

## Suggested solution
In each stable relase push container with the `latest` tag.

## Additional information

OS: Mac OSX 10.13.4
docker version: 

    → docker info
    Containers: 12
     Running: 6
     Paused: 0
     Stopped: 6
    Images: 229
    Server Version: 18.03.1-ce
    Storage Driver: overlay2
     Backing Filesystem: extfs
     Supports d_type: true
     Native Overlay Diff: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
     Volume: local
     Network: bridge host ipvlan macvlan null overlay
     Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
    Swarm: inactive
    Runtimes: runc
    Default Runtime: runc
    Init Binary: docker-init
    containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
    runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
    init version: 949e6fa
    Security Options:
     seccomp
      Profile: default
    Kernel Version: 4.9.87-linuxkit-aufs
    Operating System: Docker for Mac
    OSType: linux
    Architecture: x86_64
    CPUs: 4
    Total Memory: 1.952GiB
    Name: linuxkit-025000000001
    ID: K3MK:U3FY:AQ5G:QZ6N:IYWY:EXAV:7SCR:5SBX:O7HX:KHKD:BI2Q:OT3C
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): false
    Debug Mode (server): true
     File Descriptors: 78
     Goroutines: 111
     System Time: 2018-06-06T09:35:14.3751499Z
     EventsListeners: 3
    HTTP Proxy: docker.for.mac.http.internal:3128
    HTTPS Proxy: docker.for.mac.http.internal:3129
    Registry: https://index.docker.io/v1/
    Labels:
    Experimental: true
    Insecure Registries:
     127.0.0.0/8
    Live Restore Enabled: false

**Comment by whiteShtef** [comment]
bump

**Comment by mjgruta** [comment]
I can confirm this issue. Also using MAC 10.13.6
Will try edge version later.


docker pull docker/compose
> Using default tag: latest
> Error response from daemon: manifest for docker/compose:latest not found

docker info
> Containers: 0
>  Running: 0
>  Paused: 0
>  Stopped: 0
> Images: 0
> Server Version: 18.03.1-ce
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host ipvlan macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
> runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
> init version: 949e6fa
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 4.9.87-linuxkit-aufs
> Operating System: Docker for Mac
> OSType: linux
> Architecture: x86_64
> CPUs: 4
> Total Memory: 1.952GiB
> Name: linuxkit-025000000001
> ID: ZDMM:4WVH:XQ43:ATTM:UPTW:HAON:CMN4:64EU:YK5F:IONH:QJ7E:IN2O
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): true
>  File Descriptors: 21
>  Goroutines: 39
>  System Time: 2018-09-15T06:02:42.4414511Z
>  EventsListeners: 2
> HTTP Proxy: docker.for.mac.http.internal:3128
> HTTPS Proxy: docker.for.mac.http.internal:3129
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: true
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

**Comment by nvllsvm** [comment]
There is no `latest` tag uploaded for Docker Compose.  https://hub.docker.com/r/docker/compose/tags/

**Comment by KEINOS** [comment]
Here's a PHP one-liner command that gets the latest  version (greatest number) from the tags.

```php
php -r '$latest = ""; $items=json_decode(file_get_contents("https://registry.hub.docker.com/v1/repositories/docker/compose/tags")); foreach( $items as $item ){ $latest = version_compare($item->name, $latest, "gt") ? $item->name : $latest;} echo $latest, PHP_EOL;'
```

```shellsession
$ # Sample usage
$ php --version | head -1
PHP 7.2.12 (cli) (built: Nov 29 2018 01:59:12) ( NTS )
$ 
$ php -r '$latest = ""; $items=json_decode(file_get_contents("https://registry.hub.docker.com/v1/repositories/docker/compose/tags")); foreach( $items as $item ){ $latest = version_compare($item->name, $latest, "gt") ? $item->name : $latest;} echo $latest, PHP_EOL;'
1.23.2
```
