### ISSUE TITLE
docker login fails while docker-compose is installed on Ubuntu 18.04

### ISSUE THREAD

**Issue by jessehallam** [docker/compose#6023]
## Description of the issue

> docker login
> error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`

This error appears on a fresh Ubuntu Server 18.04 install. It has virtually nothing installed except docker and docker-compose. This error only occurs when docker-compose is installed.

Typing `sudo apt remove docker-compose` clears the error. Login now occurs using the normal docker prompt.

## Context information (for bug reports)

```
Output of "docker-compose version"
```

docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017

```
Output of "docker version"
```

Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.10.1
 Git commit:    7390fc6
 Built: Wed Apr 18 01:23:11 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   7390fc6
  Built:        Wed Feb 28 17:46:05 2018
  OS/Arch:      linux/amd64
  Experimental: false

```
Output of "docker-compose config"
```

ubuntu@:~$ docker-compose config
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

## Steps to reproduce the issue

1. `sudo apt install docker`
2. `sudo apt install docker-compose`
3. `docker login`

### Observed result

> error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`

### Expected result

The normal docker login prompt.

### Stacktrace / full error message

```
(if applicable)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

> Welcome to Ubuntu 18.04 LTS (GNU/Linux 4.15.0-1010-aws x86_64)

This machine was built using Amazon AWS's Canonical Ubuntu 18.04 AMI. It has virtually nothing installed on it, except for docker, docker-compose and sshd.

**Comment by shin-** [comment]
Looks like a bug with the Ubuntu package, which is not owned by us. Additionally, the version the package installs (1.17.1) is no longer supported. 

Please follow the official install instructions instead: https://docs.docker.com/compose/install/

**Comment by tuddman** [comment]
adding that: following the official install instructions does not work when working on ARM platform (RPi)

```
uname -m
> aarch64
```

which can't find anything when it's apart of the cURL command to download the latest :/

any word on if/when ARM boards might be supported directly?

**Comment by lucafallabrino** [comment]
I'm having the same issue woth Ubuntu18.04 server. I have tried with

- docker-compose not present
- docker-compose installed  using the link provided by @shin- 

but I keep getting
`Cannot autolaunch D-Bus without X11 $DISPLAY`

Installed packages version:


$ docker --version
Docker version 18.03.1-ce, build 9ee9f40
$ docker-compose --version
docker-compose version 1.21.2, build a133471

**Comment by shin-** [comment]
@tuddman We don't provide a build for arm architectures, but you can install the latest version using `pip`.

@lucafallabrino That's a completely unrelated issue. You're trying to use the secretservice credential helper on a server without X11, which isn't going to work. Use `docker-credentials-pass` on servers instead.

**Comment by kiliankoe** [comment]
I'm having the same (or a similar) issue, running `docker login` failing with the error message `Cannot autolaunch D-Bus without X11 $DISPLAY`. Having stumbled across https://github.com/docker/docker-credential-helpers/issues/60 it seems as if `golang-docker-credential-helpers` causes the issue here. Temporarily uninstalling docker-compose including the package above allowed me to run `docker login` to authenticate with my docker registry.

**Comment by kinkerl** [comment]
hi, why is the issue closed? the workaround from @kiliankoe works but it is still a problem on a new ubuntu 18.04 installation.

**Comment by shin-** [comment]
Closed because not a Compose issue: https://github.com/docker/compose/issues/6023#issuecomment-398136466

**Comment by mullenba** [comment]
It's very much an issue.  Fresh install of 18.04, installed docker-compose through pip.  Exact same issue.

**Comment by prg3** [comment]
I found that if you remove the golang-docker-credential-helpers package after switching to docker-ce and not the bundled docker package in ubuntu 18.04, this problem is resolved.

**Comment by chriswue** [comment]
Since this is a bug in the Ubuntu packaging for server it needs to be fixed there but in the meantime a work-around with having to uninstall docker-compose temporarily or having to switch to the docker repos instead you can make it use `pass` instead. This is what  I did:

    sudo apt install gnupg2 pass 
    gpg2 --full-generate-key

This generates a you a gpg2 key, After that's done you can list it with

    gpg2 -k

Copy the key id (from the line labelled `[uid]`) and do

    pass init "whatever key id you have"

After that `docker login` worked fine since it defaults to use `pass` and only tries to fallback to `secretservice` if it can't find it. `secretservice` seems to have an X11 dependency which isn't present on a basic server install.

Side effect is that you get a somewhat more secure credentials store or on your server instead of a base64 encoded json file.

**Comment by spaszek** [comment]
This happened to me on freshly installed `Docker version 18.06.1-ce, build e68fc7a` on Ubuntu 18.04 provided by Azure VM.

@prg3 solution (which is running `apt-get purge docker-credential-pass`) solved the issue - I can now `az acr login --name <registry>` successfully.

**Comment by fredbcode** [comment]
I added a bug report here, https://bugs.launchpad.net/ubuntu/+source/golang-github-docker-docker-credential-helpers/+bug/1794307

**Comment by CalvinHartwell** [comment]
@jessehallam can you please try this package instead? 

```
sudo apt-get install install docker.io
calvin@calvinh-ws:~$ sudo docker --version
Docker version 17.12.1-ce, build 7390fc6
```

This is version we ship and support with Canonical Kubernetes and I've never had any issue logging into registries with this agent (From the kubernetes 1.11 release notes): 

> The validated docker versions are the same as for v1.10: 1.11.2 to 1.13.1 and 17.03.x (ref)

**Comment by caiges** [comment]
@CalvinHartwell We've run into this with both the official Ubuntu `docker.io` package as well as the upstream Docker repo. In one case we installed `docker-ce`, ran into this issue, uninstalled it, installed `docker.io` and are still encountering this particular problem. It should be noted we do not have compose installed at all.

**Comment by fredbcode** [comment]
Seems related with user profile : 
sudo docker login ko
sudo su and docker login ko
But sudo su -s and docker login ok

**Comment by fredbcode** [comment]
Hi, @CalvinHartwell same issue with docker.io

**Comment by fredbcode** [comment]
@afalko you can use sudo su - and docker login

**Comment by fredbcode** [comment]
Of course this is just a workaround, use a full root access is not a good idea
But for now ...

**Comment by afalko** [comment]
Thanks @fredbcode ! 

I wound up automating this with the following workaround:
```
cat >gpg2.tmp <<EOF
     %echo Generating a basic OpenPGP key
     Key-Type: default
     Subkey-Type: default
     Name-Real: asdf asdf
     Name-Comment: asdf
     Name-Email: adsf@asdf.adsf
     Expire-Date: 0
     Passphrase: asdfasdf
     # Do a commit here, so that we can later print "done" :-)
     %commit
     %echo done
EOF
gpg2 --batch --generate-key gpg2.tmp
HOME=/home/docker-user pass init `gpg2 --list-secret-keys | grep uid -B 1 | head -n 1`
```

**Comment by trebonius0** [comment]
I have the issue as well
Even with full root access, the workaround does not work for me

**Comment by artempronevskiy** [comment]
Deleting docker-compose (apt-get autoremove) is the workaround

**Comment by fredbcode** [comment]
@trebonius0 you made exactly `sudo su -` ,not just sudo su ?
Weird, works well here

**Comment by nyetwurk** [comment]
https://bugs.launchpad.net/ubuntu/+source/docker-compose/+bug/1796119

**Comment by fatdrag0n** [comment]
removing golang will remove bunch of python stuff and  docker-compose.
I do use docker-compose. Do i have to do the gpg workaround?

**Comment by fatdrag0n** [comment]
I think I followed chriswue's advice and did gpg2 generating the key and then used the pass to set the credentials and was able to docker login

**Comment by claude-leveille** [comment]
If all else fails (@shin-'s advice didn't help me), you can always generated a ~/.docker/config.json with the creds baked in.

**Comment by claude-leveille** [comment]
Another tip for those who use Ansible in their CI, the [docker_login](https://docs.ansible.com/ansible/latest/modules/docker_login_module.html) module helped me out too.

**Comment by FabienPaitry** [comment]
This https://github.com/docker/docker-credential-helpers/issues/105#issuecomment-420480401 worked for me

**Comment by PabTorre** [comment]
At the very least a better error message from docker login will be usefull... just wasted half an hour on a goose chase around X11 Display... where a better message could've pointed straight towards using gnupg2 pass

**Comment by fredbcode** [comment]
I disagree, not a better message, when x11 is not installed we should use docker login without any error.

**Comment by nyetwurk** [comment]
Exactly this. This behavior makes zero sense.

**Comment by nyetwurk** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910822
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910823
Please work with the debian/ubuntu maintainers, or consider building your own debian packager or providing debian control files.

**Comment by wedi** [comment]
`golang-docker-credential-helpers` does also get installed alongside `python-docker`. 😑 
I decided to go with [this solution](https://github.com/docker/docker-credential-helpers/issues/60#issuecomment-431784438).

**Comment by nyetwurk** [comment]
Again, this is a very poor solution. It is a workaround at best, and not a good one. I wish there was more involvement by maintainers.

**Comment by nyetwurk** [comment]
Please, for those of you participating in this thread, go vote for the above bugs and mark them as affecting you, or they will never get fixed.

**Comment by richstokes** [comment]
I'm seeing this issue even when following the official instructions to install docker-compose (https://docs.docker.com/compose/install/#install-compose)

```
Ubuntu 18 LTS:
`cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

docker-compose --version
docker-compose version 1.23.0-rc3, build ea3d406e

docker --version
Docker version 17.12.1-ce, build 7390fc6

docker login -u abc -p 123
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY
```

**Comment by nyetwurk** [comment]
Honestly, I have no idea what docker devs are thinking.

**Comment by shin-** [comment]
Bug reports have been filed on the Ubuntu and Debian trackers. As explained throughout the thread, this issue is unrelated to Compose. You can uninstall the problematic package (`golang-docker-credential-helpers`) manually, or avoid installing Compose through `apt` in the first place and use the [official instructions](https://docs.docker.com/compose/install/) instead.
