### ISSUE TITLE
Feature Request: Provide --quiet option to 'up' command

### ISSUE THREAD

**Issue by ulope** [docker/compose#6026]
## Description of the issue

There is currently no way to prevent the `up` command from producing extraneous (i.e. 'meta' messages, not produced by the service being run) output.
Supposedly `--log-level` can be used to suppress unwanted output but unfortunately, this has no effect on `up` (it looks like there are quite a few uses of `print()` in the cli layer which of course isn't affected by log levels). 

Example:

```
~$ docker-compose --log-level CRITICAL up service
Starting someproject_service_1 ... done
Attaching to someproject_service_1
someproject_service_1 exited with code 0
```

### Observed result

`up` always produces 'meta'-output.

### Expected result

To have an option of preventing `up` from generating meta output.

## Additional information

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

**Comment by BEllis** [comment]
With this PR, you can to do,
```bash
docker-compose --log-level ERROR up -q -d
```

**Comment by bibendi** [comment]
What is the state of this issue?

**Comment by bibendi** [comment]
Looks like the Parallel "logger" doesn't respect logging level
https://github.com/docker/compose/blob/40b0ce3e5d196dd8cbc8b692be45d2a761e867b1/compose/cli/main.py#L130-L142

**Comment by wsw70** [comment]
using `--log-level ERROR` disables actual output from the command:

```
root@srv ~# docker-compose -f /etc/docker/docker-compose.yaml  --compatibility up -d jackett
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

WARNING: Found orphan containers (hass, lightswitch) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
jackett is up-to-date

root@srv ~# docker-compose -f /etc/docker/docker-compose.yaml --log-level ERROR --compatibility up -d jackett
root@srv ~#
```

The warnings were correctly silenced but the output (`jackett is up-to-date`) was also discarded.

**Comment by bemeyert** [comment]
My `docker-compose` is not silenced:
```
$ docker-compose --version
docker-compose version 1.24.1, build unknown

$ docker-compose --log-level ERROR up --detach --quiet-pull 1>/dev/null
Creating curl_es_1     ... done
Creating curl_api_1    ... done
Creating curl_netcat_1 ... done

$ docker-compose --log-level ERROR down -v 1>/dev/null
Stopping curl_netcat_1 ... done
Stopping curl_es_1     ... done
Stopping curl_api_1    ... done
Removing curl_netcat_1 ... done
Removing curl_es_1     ... done
Removing curl_api_1    ... done
```
This makes the output of tests hard to handle and read. Is there any way this can be fixed? That would be great. Thx

**Comment by Vanav** [comment]
`restart` command can't output only errors too:
```
# docker-compose --log-level CRITICAL --no-ansi -f test-compose.yml restart test-service > /dev/null
Restarting compose_test-service_1 ... 
Restarting compose_test-service_1 ... done
```

**Comment by lifenautjoe** [comment]
Any update on this? :-(

**Comment by pypt** [comment]
Hi there, shameless plug if I may: while Docker is working out how to best solve this issue, I came up with a wrapper for `docker-compose` script that monkey-patches parallel logger for it to respect `--log-level`. Not great, but immediately usable! Check it out:

https://github.com/berkmancenter/mediacloud-docker-compose-just-quieter

**Comment by taylor-cedar** [comment]
Has there been any movement on this issue? This would be very helpful. I need it for `docker-compose run`

**Comment by DarkMikey** [comment]
As I find this quite essential: Is there any workaround for this problem? This is really annoying when I run e2e tests...

**Comment by miltonlaufer** [comment]
Just a suggestion (if I am understanding this thread right). Are you sure you are not looking for:

```
docker-compose up -d
```

? This only shows the starting messages and errors.

**Comment by DarkMikey** [comment]
> Just a suggestion (if I am understanding this thread right). Are you sure you are not looking for:
> 
> ```
> docker-compose up -d
> ```
> 
> ? This only shows the starting messages and errors.

I actually found out that I can pass `LOG_LEVEL=error` to the container as environment variable which stops the pollution from the server & db while e2e tests are running (in my situation). 
I also cannot use `-d` use because I need `--abort-on-container-exit`, but in general this would work.

**Comment by xZero707** [comment]
> > Just a suggestion (if I am understanding this thread right). Are you sure you are not looking for:
> > ```
> > docker-compose up -d
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ? This only shows the starting messages and errors.
> 
> I actually found out that I can pass `LOG_LEVEL=error` to the container as environment variable which stops the pollution from the server & db while e2e tests are running (in my situation).
> I also cannot use `-d` use because I need `--abort-on-container-exit`, but in general this would work.

It only means that your internal app is for an instance respecting log level, while docker-compose parallel logger doesn't.

**Comment by neodon** [comment]
I'm surprised there is no way to suppress docker-compose messages.  It really limits the usefulness of `docker-compose run`.  It's been 3 years.

**Comment by iamfj** [comment]
Any updates?

**Comment by nathandaly** [comment]
`--quiet` Can this be implemented now?

**Comment by pankajthekush** [comment]
Is there any work on this ? I am deploying my compose on ec2 , the scripts keeps killing/creating containers this fills my /var/log/cloud-init-output.log with all the noise about containers getting killed/updated/created.

**Comment by markshep** [comment]
The solution (if it _ever_ gets implemented!) should apply to the "start" command too.

**Comment by 0x0elliot** [comment]
hey, i want to implement this issue.

**Comment by 0x0elliot** [comment]
so i was looking at the code, for all of you waiting, there does seem to be a quiet flag that i spotted in `docker compose config`

**Comment by jpmckinney** [comment]
That `--quiet` flag seems to only be relevant to the `config` command. https://docs.docker.com/engine/reference/commandline/compose_config/

**Comment by tomav** [comment]
Any updater to this? The PR has been closed to fix the issue in the log-level flag.
Could you advise on any other solution? Thanks.

**Comment by BEllis** [comment]
I think the feedback is that this isn't an issue in docker-compose 3 so they aren't going to fix it?

**Comment by paralin** [comment]
Is this still an issue?

**Comment by ndeloof** [comment]
You can use `docker compose --progress=quiet up` to remove all the progress events running `up` command.
Just initial `Attaching to ...` status message will remain

**Comment by ryanhestin** [comment]
`--progress=quiet` is working after an `apt-get upgrade` to latest `docker` as for me at least as of today.

Cleans up all the docker-compose status checks and makes it really clean :)

**Comment by KevinTurnbull** [comment]
This has become relevant again in the context of LLMs that read terminal results to determine next steps.

If there are scripts that are going to feed console results back through a tokenizer and filling the context window - I'd prefer to skip them. In particular - updating the line text creates a new line as seen by cline. This floods the command output box and slows everything down. That's a bug with Cline; but it exposes a need for a "quieting" command alternative. Every 1/10th of a second another line is written. Even if that frequency could be controlled. 

Quiet build processes in particular are what I want help with; but not ones which completely remove writing to stdout.
