### ISSUE TITLE
PyPI missing sdist for 1.21.2

### ISSUE THREAD

**Issue by ilovezfs** [docker/compose#6033]
https://pypi.org/project/docker-compose/ does not have an sdist download for 1.21.2

This makes it impossible to do for example

```
pip2 install --no-binary :all: awsebcli
```

as it will error out

```
No matching distribution found for docker-compose<1.22.0,>=1.21.2 (from awsebcli)
```

Please post an sdist for the latest version. Thanks!

**Comment by shin-** [comment]
Thanks for the report! 

I'm not sure how that happened, but I went ahead and uploaded it manually. Future releases should be fine as well.

**Comment by ilovezfs** [comment]
>Thanks for the report!

You're welcome!

>I'm not sure how that happened, but I went ahead and uploaded it manually. Future releases should be fine as well.

Thanks for the fix @shin-!
