### ISSUE TITLE
freeze while docker-compose up running

### ISSUE THREAD

**Issue by gabyfulchic** [docker/compose#6039]
I did that following commands in my debian stretch vm : 

#git clone https://github.com/sipcapture/homer-docker
#cd heplify-server/hom5-hep-influx
#docker-compose --verbose up

I'm having a freeze after bootstrap-mysql exited with code 0. (while docker-compose --verbose up is running)
Any ideas ? Maybe that's a bug :)

**Comment by shin-** [comment]
Works fine as far as I can tell.

In the future, please use the provided issue template.
