### ISSUE TITLE
compose should support `docker run` option `--init`

### ISSUE THREAD

**Issue by jamshid** [docker/compose#6044]
## Description of the issue

I run `docker-compose run myservice long-running-job.sh` to start a container for my service. I would like to use `tini` (https://github.com/krallin/tini/) as pid 1 to avoid zombie problems.

That now has built-in support in `docker run` with the `--init` option.
https://docs.docker.com/engine/reference/run/#specify-an-init-process

Compose should also support this feature (and all other "docker run" options like `--volume` please).

```
# Run a subprocess reaper as pid 1 that starts long-running-jobs.sh
docker-compose run --init myservice long-running-job.sh
```

## Context information (for bug reports)

```
docker-compose version 1.21.1, build 5a3f1a3
```

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.04.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   3d479c0
  Built:        Tue Apr 10 18:18:40 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by shin-** [comment]
Hi @jamshid,

The feature already exists and was added to the 2.2 format sometime last year: https://docs.docker.com/compose/compose-file/compose-file-v2/#init

HTH!

**Comment by thaJeztah** [comment]
@shin- support for the 3.x format was _just_ added in the docker cli (think compose 3.7); one of the last PR's merged (sorry; typing on my phone, but I can dig up a link if needed)

**Comment by shin-** [comment]
https://github.com/docker/compose/pull/6025

**Comment by jamshid** [comment]
Thanks @shin- and @thaJeztah I didn't realize it's in the yml. I'll close this.

Btw any reason _not_ to always use `init: true` even when the service normally runs a real init daemon like systemd or supervisord?

**Comment by thaJeztah** [comment]
having the extra init itself should likely not be an issue (you can configure the daemon to enable it by default), but some processes may act different depending on if they run as PID1 or not; not sure if systemd likes not being run as PID1
