### ISSUE TITLE
Can not use locally-built image

### ISSUE THREAD

**Issue by benyanke** [docker/compose#6048]
## Description of the issue
Docker compose doesn't seem to support locally built images, instead, assuming they are docker hub images, and prompting that they are not found there, and might require `docker login`.

## Context information (for bug reports)

```
Output of "docker-compose version"
```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```
Output of "docker version"
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

## Steps to reproduce the issue

1. Build an image outside the current working dir (`docker build -t testimg1 .`)
2. Reference this image in the `image` field of a docker-compose file
3. Instead of pulling it, it attempts and fails to pull from dockerhub.

### Observed result
Tries to use dockerhub despite needed image existing locally.

### Expected result
Use local image if available before pulling from DH

### Stacktrace / full error message

```
ERROR: pull access denied for testimg1, repository does not exist or may require 'docker login'
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
KDE Neon (based on Ubuntu 16.04).

**Comment by shin-** [comment]
I followed the steps you indicated but wasn't able to reproduce:
```
$ docker build -f - -t testimg1 .
FROM busybox
RUN mkdir /hello.world
##EOF##
Sending build context to Docker daemon  2.607kB
Step 1/2 : FROM busybox
 ---> f6e427c148a7
Step 2/2 : RUN mkdir /hello.world
 ---> Running in 17dc36452f9c
Removing intermediate container 17dc36452f9c
 ---> 87c10d2b8ec8
Successfully built 87c10d2b8ec8
Successfully tagged testimg1:latest
$ docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "repro6048_default" with the default driver
Creating repro6048_hello_1 ... done
Attaching to repro6048_hello_1
hello_1  | bin
hello_1  | dev
hello_1  | etc
hello_1  | hello.world
hello_1  | home
hello_1  | proc
hello_1  | root
hello_1  | sys
hello_1  | tmp
hello_1  | usr
hello_1  | var
repro6048_hello_1 exited with code 0
```
```yaml
$ cat docker-compose.yml 
version: '2.3'
services:
  hello:
    image: testimg1
    command: ls
```

Make sure your image name matches the one you specify inside your Compose file.

**Comment by benyanke** [comment]
Darn - this is what I get for forgetting to write down more specifics as it was occurring.

This must be a deeper, more nuanced issue, since your simple test case didn't replicate (I also tested your example and came to the same result).

I'll close this ticket and reopen if it happens again, and I'll post the additional details.
