### ISSUE TITLE
Feature request: docker-compose.yml linter for syntax and coding style

### ISSUE THREAD

**Issue by harobed** [docker/compose#6052]
I post this issue here but this linter can be an independent project.

I would like a linter for:

* check `docker-compose.yml` syntax
* check `docker-compose.yml` coding style, example:

use this syntax:

```
    environment:
      LISTEN: =0.0.0.0:8081
      CLIENT_URL: http://foobar:8080
```

instead this syntax:

```
    environment:
      - LISTEN=0.0.0.0:8081
      - CLIENT_URL=http://foobar:8080
```

Best regards,
Stéphane

**Comment by shin-** [comment]
Hi Stephane,

Thank you for the suggestion! Unfortunately, this is out of scope for the Compose project in general and this repo in particular. The `docker-compose config` provides some of this, but that's as far as we're looking to go for that specific feature. 

That said, if you feel strongly about this, generic tooling exists that may be of interest to you, like [`yamllint`](http://yamllint.readthedocs.io/en/stable/), which you can use in your workflow.

**Comment by m0j0hn** [comment]
Also `hadolint`, for Dockerfile files - highly recommended, we run it as a part of CI

**Comment by zavoloklom** [comment]
Hi @harobed!
I know it's been a while, but I was also looking for the same functionality recently and ended up with creating this utility https://github.com/zavoloklom/docker-compose-linter/
Maybe it would help you also.
