### ISSUE TITLE
storage_opt for Compose version 3

### ISSUE THREAD

**Issue by Gabology** [docker/compose#6054]
Currently it looks like only version 2 Compose files support `storage_opt`. It would be a very useful addition if support for `storage_opt` was extended to version 3 as well.

**Comment by shin-** [comment]
1. This tracker should only be used to report bugs and request features / enhancements to docker-compose
    - For questions and general support, use https://forums.docker.com
    - For documentation issues, use https://github.com/docker/docker.github.io
    - **For issues with the `docker stack` commands and the version 3 of the Compose file, use
      https://github.com/docker/cli**

**Comment by olljanat** [comment]
Link to issue on correct tracker docker/cli/issues/1177
