### ISSUE TITLE
compose stop -f is missing --no-color option

### ISSUE THREAD

**Issue by FabianTe** [docker/compose#6056]
## Description of the issue

Currently the option `--no-color` does not seem to be usable with `docker-compose stop`
Assuming there is a file `docker-compose.test.yml`, none of these commands work:

```powershell
docker-compose --no-color -f ".\docker-compose.test.yml" stop
docker-compose -f ".\docker-compose.test.yml" --no-color stop
docker-compose -f ".\docker-compose.test.yml" stop --no-color
```

## Context information (for bug reports)
docker-compose:
```
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```
docker:
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd6
```
Output of "docker-compose config"
```
None, since there is no option to validate my custom docker-compose.test.yml without renaming it, which I can not do.
```

## Steps to reproduce the issue

1. Try any of the commands above with a docker-compose file named like mine.

Running docker on a windows server 2016 instance using the linux VM. Tested only in Powershell

**Comment by shin-** [comment]
Yes, `--no-color` is only an option for `docker-compose up`.  For other commands, you can use `--no-ansi` instead, which is a global flag.

**Comment by FabianTe** [comment]
So this is by design I guess?
________________________________
