### ISSUE TITLE
Use docker apt-get repository for installation

### ISSUE THREAD

**Issue by christhomas** [docker/compose#6057]
Why don't you use the apt-get repository that docker already provides in order to release this? Why do I have to use a fragile, difficult, and manual curl+chmod process when docker already has a perfectly working apt-get repository to use?

This makes absolutely no sense.

**Comment by shin-** [comment]
(Mostly) Duplicate of #2235
Among other things:
- Low priority task with no bandwidth to address it
- Bundling with Docker Desktop means the only people likely to care are the minority who develop on Linux (that's not a critique, I'm part of that minority too, but this is the reality we're dealing with)

Cheers!

**Comment by christhomas** [comment]
Are you saying that in almost three years, you haven't had the resources necessary to add a package to a package manager? A task that takes 30 minutes?

Docker is a multi billion dollar company? Yet has no spare resources, or interns sitting around who can do something that should have been done from the get go?

Thats quite depressing.
