### ISSUE TITLE
"SSL certificate verify failed" can be issued by secure program?

### ISSUE THREAD

**Issue by gymnopedies7** [docker/compose#6062]
I just want to install numpy, but there is issue for that.
I think that it's because of security in my company.
How can I fix it?

C:\Users\ff>pip install numpy
Collecting numpy
  Could not fetch URL https://pypi.python.org/simple/numpy/: There was a problem
 confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed (_ssl.c:749) - skipping
  Could not find a version that satisfies the requirement numpy (from versions:
)
No matching distribution found for numpy

**Comment by thaJeztah** [comment]
Is this question related to docker compose? Looks like you're installing on the host, so, I'm not sure how this relates to docker compose.

Such errors can indeed be cause by a man-in-the-middle proxy, but it's likely out of scope for this issue tracker, and may be better to ask support inside your company (as they know how the network is configured)
