### ISSUE TITLE
SELinux/Fedora/CentOS - autolabel if path is under current repository tree

### ISSUE THREAD

**Issue by abitrolly** [docker/compose#6067]
## Description of the issue

Running `docker-compose` with mounted volumes on Fedora/CentOS gives `permission denied` errors, because `docker-compose` doesn't set SELinux permissions unless explicit `:z :Z` flags are given from the command line.

Also https://github.com/moby/moby/issues/30934 states that `:z :Z` are not default, because using it outside of project directory will relabel files and directories, breaking permissions if somebody mounts some home or system directory as container volume.

## Steps to reproduce the issue

1.  Run `docker-compose` on Fedora with SELinux

### Observed result

Permission denied errors from apps inside container.

## Proposal

For development `docker-compose` never leaves the scope of single directory with project sources. I believe that 80% of cases can be covered if `docker-compose` automatically labels files in project directory and gives warnings with no action for all mounts outside.

**Comment by shin-** [comment]
Hi @abitrolly 

Thanks for your suggestion. However, this would be a major behavior change that would break expectations and create potential security issues for users, which would be unacceptable to us. There's also no precedent for any other part of the Docker toolset where these labels are automatically set.

**Comment by abitrolly** [comment]
@shin- that sounds too abstract - could you describe exactly what are expectations and potential security issues.

**Comment by abitrolly** [comment]
Because my expectation is for `docker-compose` is to just work without me caring about the labels in my project directory.
