### ISSUE TITLE
Issue management not done right

### ISSUE THREAD

**Issue by luislobo** [docker/compose#6074]
## Description of the issue

In https://github.com/docker/compose/issues/4675#issuecomment-397773267, @shin- comments that the issue is locked by spam, saying `+1s just serve to aggravate people subscribed to the issue. If you've got nothing constructive to add, just use the thumbs up button.`
Thing is, after locking the issue, the thumbs-up button is disabled.

## How to address/solve it?

I don't have a solution, but enabling comments, even if I receive the ocassional +1, it allows me (at least) to be notified that the issue is still required.

May be if you want to handle "issue voting" but not commenting, a new Issue tracker needs to be implemented? And what about people coming in with possible solutions to a still unresolved issue?

Finally, there is no status update of whether the issue is being considered or planned for the future, as it was kept open.

**Comment by shin-** [comment]
Please don't create meta-issues as they create an additonal maintenance burden and clutter the tracker. If you have an issue with how the tracker is managed, please contact me or a community manager directly.

I've unlocked the thread in question.
