### ISSUE TITLE
Proposal: Enable services to use different Docker Hosts

### ISSUE THREAD

**Issue by waitingkuo** [docker/compose#608]
It's inspired by #527 
The pull request for this proposal is #607 

The main idea is to allow servie to use different Docker Hosts. To do so, I add three new parameters:
* docker_host
* docker_cert_path
* docker_verify_tls

So we can modify our fig.yml to deploy to more than one docker host in the same time. For example, 

### fig.yaml:

    web1:
      build: .
      command: python app.py
      docker_host: tcp://192.168.0.101:2376
      docker_cert_path: /path/to/your/cert1/directory
      docker_tls_verify: 1
      ports:
       - "8000:8000"

    web2:
      build: .
      command: python app.py
      docker_host: tcp://192.168.0.102:2376
      docker_cert_path: /path/to/your/cert2/directory
      docker_tls_verify: 1
      ports:
       - "8000:8000"

We can use this fig config to deploy to both `192.168.0.101` and `192.168.0.102`. For generating docker cert over SSL, please reference [here](https://docs.docker.com/articles/https/)

**Comment by dnephin** [comment]
Multi-host networking is on the way (#1676)!

Thanks for this proposal!

swarm has become the way to run across multiple hosts, and machine has become the way to target individual remote hosts, so we won't be adding support to compose directly.

**Comment by waitingkuo** [comment]
Glad to see swarm become more and more mature!
