### ISSUE TITLE
docker-compose up command hangs on Windows CMD

### ISSUE THREAD

**Issue by Bigbhardwaj** [docker/compose#6081]
I am following Essential Angular for ASP.Net Core MVC book and, chapter 4,
My .yml file

services:
  database:
    image: "microsoft/mssql-server-linux:latest"
    ports:
      - 5100:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mySecret123

when I try to run command docker-compose up
The CMD window hangs with below messages

![image](https://user-images.githubusercontent.com/9026778/42653967-aa105e9c-8634-11e8-870d-4d08805c3421.png)

I Couldn't figure out the issue .

**Comment by shin-** [comment]
`docker-compose up` stays in the foreground as long as your container are running - is this what you mean by "hang"? If so, that is the intended behavior. If you want, you can use the `-d` flag to tell Compose to exit instead of streaming the container's logs after the stack is started.

**Comment by Bigbhardwaj** [comment]
@shin : Thanks..! I will try with the flag too.. but running docker and its commands leaves my touch pad pointer lagging and it's more often not in sync  with the motions performed on the touchpad and it happens only while runnnig docker. Not sure it's just for me or an existing issue.
