### ISSUE TITLE
Macos high sierra docker-compose.yml and .env

### ISSUE THREAD

**Issue by FarYoung** [docker/compose#6089]
While I upgrade to Macos high sierra, the `docker-compose -up -d` and `docker-compose -down` comes not work, get following ERROR from the zsh terminal：

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
:3306", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
:6379", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

But it can comes up by the Docker APP from the MacOS stock banner while stop the Docker client and restart.

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
8142df6b34b8        redis:alpine        "redis-server --appe…"   13 days ago         Up About an hour    0.0.0.0:6379->6379/tcp   redis
b175d381b6e9        mysql:latest        "/entrypoint.sh --de…"   13 days ago         Up About an hour    0.0.0.0:3306->3306/tcp   mysql1000
```

it worked well before i sure, the docker-compose.yml looks like here:

```
ports:
  - ${REDIS_PORT}:6379
```

and the ./.env likes:

```
 # REDIS
REDIS_HOST=redis
REDIS_IP=172.18.0.3
REDIS_PORT=6379
```

Now,  I find back all the containers and database, after remove all the `${*}` from the docker-compose.yml instead of its real name, without the .env function.

**Comment by shin-** [comment]
Make sure the .env file is in the same folder as the one you're executing `docker-compose` from.

**Comment by FarYoung** [comment]
I make sure it again~:

>  /Developments/xiark   master ●  ls -al
total 48
drwxrwxrwx  12 faryoung  staff   384  7 19 23:43 .
drwxr-xr-x   6 faryoung  wheel   192  7 19 23:43 ..
-rw-r--r--@  1 faryoung  staff  6148  7 19 23:43 .DS_Store
-rwxrwxrwx@  1 faryoung  staff   479  7 16 12:24 .env
drwxr-xr-x  15 faryoung  wheel   480  7 19 23:43 .git
-rwxrwxrwx   1 faryoung  staff    35  6 26 02:02 .gitignore
drwxrwxrwx  15 faryoung  staff   480  7 16 19:24 docker
-rwxrwxrwx@  1 faryoung  staff  3956  7 16 13:59 docker-compose-product.yml
-rwxrwxrwx@  1 faryoung  staff  2164  7 19 19:27 docker-compose.yml

**Comment by mouhamed** [comment]
Hello, why do you use a dash before command `-up` and `-down` ?
