### ISSUE TITLE
The error "ERROR: network network_main_net id ... has active endpoints" isn't particularly useful and blocks `docker-compose down`

### ISSUE THREAD

**Issue by JonasT** [docker/compose#6096]
## Description of the issue

The error "ERROR: network network_main_net id ... has active endpoints" isn't particularly useful and blocks `docker-compose down`.

### Details

I have multiple docker-compose.yml files that look like this:

```yaml

version: '2.3'
services:
  someservice:
    networks:
    - networks_main_net
    ...

networks:
  network_main_net:
    name: network_main_net
```

So far, this is the only way to have a shared network over multiple docker-compose.yml groups which doesn't involve some hackery with a special network-owning folder that needs to be `up`ed first.

However, for all of those containers, `docker-compose down && docker-compose up -d` is broken:

```
# docker-compose down && docker-compose up -d
Stopping mail ... done
Removing mail ... done
Removing network network_main_net
ERROR: network network_main_net id 6aaf7ec207e435452261aa3f408813c1197d5a5080288d70e4886373427c9fe7 has active endpoints
```
Since the error isn't actually useful to me and certainly not something I would want it to abort over (of course there are still active endpoints - that's the point of sharing the network!) I suggest that it is converted into a warning.

## Context information (for bug reports)

```
# docker-compose version
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

```
# docker version
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.10.1
 Git commit:	7390fc6
 Built:	Wed Apr 18 01:23:11 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.10.1
  Git commit:	7390fc6
  Built:	Wed Feb 28 17:46:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

## Steps to reproduce the issue

1. Use shared network alike to `networks.some_name.name: some_name` (used by a container as `services.myservice.networks: ["some_name"]` as shown above)
2. Set up 2+ `docker-compose.yml` groups that all share this same network name
2. Do `docker-compose up -d` for all the groups sharing this network
3. Do `docker-compose down` on one of them

### Observed result

error message that isn't particularly surprising or relevant, and exit code non-zero

### Expected result

warning (or no network-related output at all) and exit code 0

### Stacktrace / full error message

```
Removing network network_main_net
ERROR: network network_main_net id 6aaf7ec207e435452261aa3f408813c1197d5a5080288d70e4886373427c9fe7 has active endpoints
```

## Additional information

Ubuntu 18.04 LTS

**Comment by shin-** [comment]
Hi @JonasT 

Thanks for the feedback ; however, this is working as intended. If you don't intend for this network to be managed (i.e. for Compose to attempt removal when using `down`, and error out when it's unable to do so), you should declare it as external. Note that the use-case you mention is possible but not officially supported, and we've actually recommended against doing this in the past.

Moreover, if all you're only looking to do is to stop / remove containers, `docker-compose stop && docker-compose rm` is a more appropriate command.

HTH!

**Comment by JonasT** [comment]
@shin- marking as external doesn't work because then the network won't be created if it's not there, which leads to fatal errors on deployment (see #4179 ). Can you please write a `docker-compose.yml` example that actually provides this functionality, where `docker-compose down` still works? Because I don't know how to write one, the only reason I am suggesting this change.

**Comment by JonasT** [comment]
Does what I write make sense? Basically I'm stuck between "`docker-compose down` doesn't work" and "need special startup script or nothing will launch after container cleanup" and both kind of suck...

**Comment by JonasT** [comment]
You're just reiterating the flawed concept. The problem is that `docker-compose` has no proper notion to define a resource used by multiple stacks. Your "advantage" simply means that start order suddenly matters in a frustratingly opaque way that breaks deployments if the administrator is not deeply aware of hidden dependencies, IMHO that's a major flaw and design issue.

What I did was simply use the best solution available - *suggest to me, by the way, I didn't make it up myself* - to try to define a shared resource properly. I made this ticket because it doesn't work nicely. That should change.

The whole concept of "one folder needs to own the resource" is simply bad in some scenarios. I understand that is where all this nonsense comes from, but that doesn't mean it's a good concept. It is for *some* use cases, but it simply isn't for others. Is that so hard to understand? Why can't docker-compose support those other use cases better as well? Why does this need to be discussed over an over, when it's *obvious* that those use cases aren't well supported, and people have them?
 
It's just frustrating to *constantly* get into concept discussions. The use case is super simple, why people need it is also super simple. I suggested one way, there are also others of course. Quite frankly, I don't care *how* this is done, this was just one way of suggesting it. I'm open to all others - but your post of "but it needs to be that way because that's our concept" is simply not very useful as a final answer. (Sorry, I don't mean to attack personally - just explaining why I'm getting frustrated over here!) Your post helps explains things I was already aware of, but it doesn't advance us to any solution.

**Comment by JonasT** [comment]
> which can be slightly inconvenient

This is the core of the problem by the way. Breaking fully automated startup is not a slight inconvenience, but a major problem. I shouldn't need a  custom shell script to hard code certain dependencies to make stuff create & launch properly, this is what the docker tools are already for. It's their entire purpose not to require me to do this just to get my deployment to work!

**Comment by shin-** [comment]
@JonasT I definitely understand that some use cases call for several independent Compose files sharing a single network. It's obviously not the use case Compose is maximally designed to support, but we agree that it should work at least to a reasonable degree. That said, there's definitely a few things we seem to be missing about your use-case, namely

1. If you don't intend to remove networks with `docker-compose down`, why not simply use `docker-compose rm --force --stop` ? It's the exact same thing except it ignores networks, which seems to be exactly what you want to begin with.
2. What is so odious about having some amount of scripting to supplement `docker-compose`? This is a recurring theme for issues on this tracker, but anything slightly complex will need it at one point or another anyway. And in your case, all you really need is a one liner: `docker network inspect network_main_net || docker network create network_main_net`.

Any of these two feel more reasonable to me than to expect Compose to not report legitimate errors, i.e. ignoring a failure to remove a network when running a command specifically designed to remove networks.  If there are legitimate issues with the solutions I proposed, I'm happy to iterate more on this.

**Comment by JonasT** [comment]
> why not simply use docker-compose rm --force --stop ? 

I know 3 servers of 3 different admins (excluding mine) who use docker-compose for everything. *All of them use such a shared network.* *All of them use startup order hacks to work around this*, and *all of those admins use `docker-compose down && docker-compose up -d` as an idiom*. Requiring them to learn this differently to get rid of the hackish start scripts just because of docker-compose being too stupid (sorry) to understand the proper notion of a shared resource, I just don't think it's a good idea.

> but anything slightly complex will need it at one point or another anyway

I can again only speak for myself and the three servers I am vaguely involved in run by others. None of them have any custom scripting for anything *except for this issue*. Maybe it's just my environment, but I do think this issue is much more prevalent than you think - or at least that's the only impression I can get from my perspective.

Of course things work right now for everyone. But I'm the only admin who tried this workaround that breaks `docker-compose down` and I can already tell you none of the others would follow through if I made them aware of the caveat. So they'll just stay with those custom scripts just for this issue forever. And I guess that's fine in a way, but since at least to me it seems to be impacting a lot of people, why can't be something done about it?

**Comment by JonasT** [comment]
Just to add some more detail on the unfortunate human politics side of `dc down && dc up -d`:

One of those setups I'm vaguely involved in is a smaller non-profit association with lots of independent groups, and multiple people working on the server. This works fine until you add in really odd changes like "we've changed things so `docker-compose down` doesn't work to improve the startup script  a little" - nobody understands this, so this is simply not going to fly. It's just such an impractical reason too, in the end a startup script hack is less pain for all the assisting voluntary admins that don't need to touch it in their daily work. But that is why it all circles back to #4179 not being solved, and this error message being a problem - unless you don't want to support this use case at all, and force people to continue with hackish startup scripts.

**Comment by shin-** [comment]
I'm not sure what to say ; there is a solution, but your answer seems to be "I don't want that solution, it forces people I work with to learn a new thing, I want you to break the thing we use currently so that it works for our setup." I want to engage with this honestly, but it seems to me you've placed this artificial roadblock of "human politics" that's probably not that hard to solve. If we can get monkeys to learn sign language, getting a handful of educated individuals to learn a new subcommand should be doable. Or, you know, just write a script that does the thing for them.

> The main issue remains that all of the proposed solution are ugly hacks around the underlying problem that docker-compose doesn't have a proper notion of a shared network

The concept of a shared network exists, but it involves using the `external` keyword and recognizing that one part of the stack has to own that resource. In the typical example you cite, that's probably the Compose file that declares the proxy, since it's the one that always needs to be present for the system to function. It makes sense in practice too ; you won't be able to `docker-compose up` anything else until the proxy is up and running (creating the network), and you'll be able to `docker-compose down` any part of the stack without getting error messages. That's not hackish, it's just good ops hygiene.

**Comment by JonasT** [comment]
> your answer seems to be "I don't want that solution, it forces people I work with to learn a new thing

Not really, but if you feel like that, I don't think I am able to get my point across clearly. As far as your design explanations go, I can't help but feel like you're just reiterating obvious flaws / inconsistencies that would be worth fixing, but I feel like I'm doing a really bad job here explaining this and we're not really getting anywhere. And after all I have to admit it's a bit of a nitpick, albeit still one I'd consider worth fixing (especially since I don't know a single deployment in practice *not* impacted by this) - but it's not worth discussing 10 pages over.

**Comment by JonasT** [comment]
For what it's worth, I was curious & bored and actually implemented this for the `2.4 schema`to see how much work it is: https://github.com/JonasT/compose/commit/f2be29f2c859367ee1935ffe56ba143044a84249 I know the hard-coded docker.errors.APIError `.explanation` string message check is ugly, there is probably a better way to do that

**Comment by JonasT** [comment]
I've spent some more thoughts on this and how to avoid the hard-coded error check above. However, from how this discussion ended, I'm not sure whether there's any interest in improving the situation regarding this right now, even if I provided a pull request. (which I find a bit sad) If there is, let me know, I'd be happy to share more ideas and attempts to implement them if there's actual interest in them :+1: 

(the underlying issue certainly hasn't magically disappeared for me, or any of the other admins I know have ugly workarounds in place to avoid it)

**Comment by JonasT** [comment]
Is there really no interest in this even if I'm interested in implementing it myself?

**Comment by Tockra** [comment]
> 
> 
> @JonasT I definitely understand that some use cases call for several independent Compose files sharing a single network. It's obviously not the use case Compose is maximally designed to support, but we agree that it should work at least to a reasonable degree. That said, there's definitely a few things we seem to be missing about your use-case, namely
> 
>     1. If you don't intend to remove networks with `docker-compose down`, why not simply use `docker-compose rm --force --stop` ? It's the exact same thing except it ignores networks, which seems to be exactly what you want to begin with.
> 
>     2. What is so odious about having some amount of scripting to supplement `docker-compose`? This is a recurring theme for issues on this tracker, but anything slightly complex will need it at one point or another anyway. And in your case, all you really need is a one liner: `docker network inspect network_main_net || docker network create network_main_net`.
> 
> 
> Any of these two feel more reasonable to me than to expect Compose to not report legitimate errors, i.e. ignoring a failure to remove a network when running a command specifically designed to remove networks. If there are legitimate issues with the solutions I proposed, I'm happy to iterate more on this.

Both of you suggestions aren't real solutions of the problem. The first one doesn't remove the networks anymore, but that is a nice feature which nobody want to lose. Your second suggestion is a solution, but no a docker-compose like solution. If I need to create my own networks then I can even create my docker-containers myself ...

**Comment by etc0de** [comment]
Just to re-explain my reasoning, since this problem hasn't gone away:

> I'm not sure what to say ; there is a solution, but your answer seems to be "I don't want that solution, it forces people I work with to learn a new thing, I want you to break the thing we use currently so that it works for our setup." I want to engage with this honestly, but it seems to me you've placed this artificial roadblock of "human politics" that's probably not that hard to solve.

No, my argument is that the solution is a really bad fit for anyone I have asked. And the "artificial roadblock" is I can't make anybody reasonably use it when they consider it really bad.

> The concept of a shared network exists, but it involves using the external keyword and recognizing that one part of the stack has to own that resource

The ownership is not the problem, but the implicit startup order this suddenly requires which is 1. not how docker-compose usually ever works, 2. leading to random failures when just attempting to start all in any order or alphabetically (which is how many people launch things), 3. easily solvable if docker just understood shared concepts properly. If this ownership means that suddenly startup becomes brittle due to an introduction of order causing anyone I have seen try this workaround cause notable issues, then maybe it is worth fixing...?

I am still very interested in implementing this if somebody just lets me.

**Comment by JurgenCruz** [comment]
Just a thought. just how we have the concept of dependencies between containers, why not add the concept of dependencies between stacks? no need to mark a network as shared, but if we are able to mark a dependency between stacks, we can have a shared network in a separate stack, and when we try to `up` a child stack, if the parent stack is not running, it will run it first. If you `down` a child stack, it will not down the parent. If you `down` a parent stack, either give error if there is a child stack, or `down` the children stacks too.
