### ISSUE TITLE
Don't limit parallelism by dependencies

### ISSUE THREAD

**Issue by pauldraper** [docker/compose#6098]
https://docs.docker.com/compose/startup-order/

> Compose always starts containers in dependency order

Insofar as I can tell, this doesn't mean anything useful.

And I've noticed that depends_on still introduces some delay between dependent containers.

Given that "start in order" doesn't dependably mean anything, there should be no waiting or delay in starting dependent containers. There's no point to the delay.

All containers should be started as fast as possible without waiting for dependencies.

**Comment by shin-** [comment]
Thanks for the feedback. I agree with you in theory, however ;
1. A lot of people depend on (hah) this feature.
2. This would be a major breaking change, which we're not really ready to consider at this point in Compose's lifecycle.

**Comment by pauldraper** [comment]
Other option: Relevant, good, but incompatible features are candidates for flags.

**Comment by pauldraper** [comment]
Basically... there's sleep() in the code for the reason that otherwise code breaks. :(

**Comment by pauldraper** [comment]
I continue running into this, where docker-compose is unnecessary slow, both for starting and shutting down. (Though a container being "shut down" actually means something. A container being "started" means very little in the case where you are communicating over the network.)

It would be nice to have an opt-in ability to not have docker-compose be artificially slow.

**Comment by chris-crone** [comment]
@pauldraper I understand how this is frustrating. I agree that we could possibly implement this as an opt-in feature for `docker-compose up` so I've retagged this as an enhancement.
