### ISSUE TITLE
Fig got weird after removing Docker images

### ISSUE THREAD

**Issue by pedroborges** [docker/compose#61]
I started playing with Fig yesterday and when I wanted to start fresh today on project, I cleaned all Docker images (using `docker rmi $(docker images -a -q)`). I thought Fig would rebuild as it did yesterday, but no. After that, Fig was looking for an image that didn't exist.

Then I uninstalled Fig, Docker and even cleaned Docker folder inside `/var/lib/Docker`. But without success... Now web and db services build but don't work. Is there any place Fig store this info?

See: https://gist.github.com/pedroborges/0efe5f5e125bbddcdf07

**Comment by kulbida** [comment]
any resolution on this issue?

**Comment by dnephin** [comment]
This issue is over a year old. There have been a bunch of docker bugs fixed in this time.

I'm going to close this issue. If someone can reproduce with a recent version of docker and compose, I'm happy to re-open it.
