### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by ssadok** [docker/compose#6106]
Hi,
Can you tag stable and latest please for your releases ?

Thanks.

**Comment by shin-** [comment]
Unless I'm missing something, you can just use GitHub's permalink for that: https://github.com/docker/compose/releases/latest

**Comment by nvllsvm** [comment]
@shin- Is there any reason why there is no `latest` tag for the Docker image of Docker Compose?

**Comment by shin-** [comment]
@nvllsvm There is: https://github.com/docker/compose/issues/5987#issuecomment-392113124
