### ISSUE TITLE
Service stops responding after ~14700 req during stress test

### ISSUE THREAD

**Issue by whyvez** [docker/compose#6107]
## Context information
I am running a stress test on one of our application and seeing some service degradation during stress testing. I've been able to replicate this behavior with a very simple configuration using a community image. I'm using https://github.com/wg/wrk to run my stress test. I've observed that when using docker-compose after about 14,700 requests, the containers stops responding. I've done the same test outside of docker compose spinning up a container with `docker run` and the same problem doesn't manifest.

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.4.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:08:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:10:42 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
services:
  one:
    container_name: one
    image: nginxdemos/hello
    ports:
    - 80:80/tcp
version: '3.0'
```

## Steps to reproduce the issue

big test
1. `docker compose up`
2. `wrk -t2 -c2 -d30s http://localhost` => total requests will be ~ 14,700
3. `wrk -t2 -c2 -d30s http://localhost` => total requests will be 0

many small test
1. `docker compose up`
2. `wrk -t2 -c2 -d1s http://localhost` => total requests will be ~ 5000
3. `wrk -t2 -c2 -d1s http://localhost` => total requests will be ~ 5000
3. `wrk -t2 -c2 -d1s http://localhost` => total requests will be ~ 4000

without docker compose
1. `docker run -d -p 80:80 nginxdemos/hello`
2. `wrk -t2 -c2 -d60s http://localhost` => will run fine not hitting the ~14,700 limit

### Observed result
Using docker compose 14,700 seems to be the number where a container stops responding to requests when ran as a docker compose service.

### Expected result
A container in a docker compose configuration should not stop responding to requests after 14,700 requests. Although these are bigger numbers, I've also observed this behavior using another one of our stress testing tool which replays two 500 request nginx access log concurrently. I cannot say yet if these two issues are related but solving this 14,700 issue might help shed some light on what might be happening for our replay load test.

## Additional information

CentOS 7 / `pip install docker-compose`

**Comment by shin-** [comment]
I see some methodology issues here ; 
- Your `docker run` equivalent will not create the same container configuration, as some parameters are implicit (off the top of my head, you're not creating and connecting to a custom network). 
- You use `docker-compose up` attached (no `-d` option) but use docker run detached, which can have a large impact on I/O and network usage if there is a large amount of logs (which I suspect there is)

Tweaking around these parameters will allow you to better identify the issue. FWIW, I just ran some quick tests on my laptop with the setup you describe and have had no issue pushing way past 14k requests:
```
## No -d flag
$ wrk -t2 -c2 -d30s http://localhost
Running 30s test @ http://localhost
  2 threads and 2 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   422.95us  356.63us  18.17ms   97.33%
    Req/Sec     2.51k   178.48     2.91k    68.67%
  149919 requests in 30.01s, 1.04GB read
Requests/sec:   4996.16
Transfer/sec:     35.50MB
```
```
## With -d flag
$ wrk -t2 -c2 -d30s http://localhost
Running 30s test @ http://localhost
  2 threads and 2 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   316.00us  212.91us  11.45ms   98.78%
    Req/Sec     3.27k   183.32     3.61k    77.41%
  195637 requests in 30.10s, 1.36GB read
Requests/sec:   6499.72
Transfer/sec:     46.19MB
```

This to me indicates that the issue you're seeing might be related to your environment in major part. HTH!

**Comment by whyvez** [comment]
@shin- Thank you for these explanations. Apologies, I neglected to mention that I am not seeing this issue manifest on my Macbook Pro (Sierra). So far I've been able to replicate this issue on both CentOS 7 and Ubuntu 16.04.

**Comment by whyvez** [comment]
@shin- Wow! Just tried `docker-compose` with the `-d` flag and all my problems went away!

- Could you go into more details about why passing in the `-d` flag makes such a big difference?
- Can you explain why I am not hitting this 14,700 limit on OSX even without the `-d` flag.
- Is it recommended practice to run `docker-compose` with the `-d` flag for production?

**Comment by shin-** [comment]
1. Without `-d`, you're maintaining an active connection for each container you're running, streaming the logs and writing on stdout as well as another watching for events (like the container stopping, or receiving a kill signal, etc.). In a stress test situation this is likely to strain I/O and network on your machine, which I suspect is the cause of the issues you've been seeing.
2. No idea, sorry. My tests mentioned above were performed on a (Desktop) Ubuntu 16.04, FWIW, so it's not dependent on OSX or Hypervisor magic. If you were testing on small cloud instances, maybe you just hit a resources bottleneck that your more powerful local machine didn't.
3. I don't know about "recommended practice", but I personally would likely run in detached mode for the reasons explained in [1]. The only thing you're really "losing" is aggregated logs, which should be handled by specialized tools in a production environment anyway (graylog is a common choice)
