### ISSUE TITLE
Secrets using bind mounts in version 2

### ISSUE THREAD

**Issue by Silex** [docker/compose#6109]
Hello,

Why not support secrets using bind mount in version 2 like for version 3?

**Comment by shin-** [comment]
Hi @Silex 

Secrets are a Swarm concept and are not applicable to the Compose v2 model, hence why it wouldn't make sense to emulate them there.

Hope that answers your question.

**Comment by Silex** [comment]
Well it'd allow people to get used to secrets without using a swarm. But ok I understand, thanks for the rationale.
