### ISSUE TITLE
Backgrounded 'docker-compose up ...' and piped 'docker-compose logs ...' still listen to CTRL+C

### ISSUE THREAD

**Issue by petr-ujezdsky** [docker/compose#6118]
## Description of the issue
When running `docker-compose up tester &` this command still listens to CTRL+C in subsequent programs (eg. `less`).
The same applies to `docker-compose logs -f tester | less -R +F` (`-R` for colors, `+F` for follow). When I hit CTRL+C in the `less` to stop following the input and do some searching, the `logs` command aborts and stops giving the `less` new data.

I am reading the logs using this approach because there is no way to show only logs after the boot time. But even when the #2227 (`-since=boot` option I am desperately waiting for) will be implemented, the `less` could not be used to easy navigate the logs due to this bug.

## Context information (for bug reports)

```
Output of "docker-compose version"
$ docker-compose version
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

```
Output of "docker version"
$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

```
Output of "docker-compose config"
$ docker-compose config
services:
  tester:
    command: ping localhost
    image: alpine:3.6
version: '3.0'
```

## Steps to reproduce the issue

1. create the `docker-compose.yml` file with content defined above
2. create simple start-up shell script `test.sh`
```
#!/bin/bash

docker-compose up tester 2>&1 >> "temp.log" &
less -R +F "temp.log"
```
3. run the script `test.sh`, in window A
4. see the expected pinging and the following feature of `less` command
5. in another window, B,  run command `tail -f temp.log`
6. see the expected pinging and the following feature of `tail -f` command
7. back to window A, hit CTRL+C to stop following, allows to navigate the log using arrow keys (`less` features)
8. hit SHIFT+F to continue following

### Observed result
The service was stopped (window B shows no more pinging). It somehow catched the signal.
### Expected result
The service continue to work independently on the actions done in `less` command.

## Additional information

The `docker-compose logs` command has same bug:
1. run `docker-compose logs -f tester | less -R +F`
2. hit CTRL+C to stop following, allows to navigate the log using arrow keys
3. hit SHIFT+F to continue following
4. the `docker-compose logs` command ended giving no data from now on

OS version / distribution, `docker-compose` install method, etc.
macOS High Sierra 10.13.6 (17G65)
Docker installed via homebrew.

**Comment by Dimrok** [comment]
Hi @petr-ujezdsky.

I tried with `ping` and it behaves the same so I don't think the issue is related to `docker-compose`.

If you change `test.sh` to:
```bash
#!/bin/bash

ping 8.8.8.8 2>&1 >> "temp.log" &
less -R +F "temp.log"
```

you'll get the exact same behavior.

**Comment by petr-ujezdsky** [comment]
After quite some time of investigation I have found the proper way to do this.

## The proper way to do it

### Prerequisites
Each container within the compose has to be "stateless". This means that it has to have all it's data stored on some mounted storage.

### Using ```docker-compose up``` and ```docker-compose down```
Start the compose using standard ```docker-compose up```. This will create all necessary containers and volumes and start them:
```
#!/bin/bash

# do not send ctrl+c interruption to the background jobs
set -m

# create everything if missing and start it, detached
docker-compose up -d tester

# watch logs
docker-compose logs -f tester | less -R +F

# stop everything and DELETE containers, networks etc. (this does NOT delete 
volumes)
docker-compose down
```

### Explanation
The main difference is using ```docker-compose down``` instead of ```docker-compose stop```. This will delete (among other things) all containers **and their logs**. So it is safe to use ```docker-compose logs``` because it will not output old logs anymore.

But since the containers are deleted and recreated each time you run the service, the data has to be outsourced to mounted volumes (hence the Prerequisites). These volumes are NOT deleted using the ```docker-compose down```. (_but they can if you want to, using the [```-v``` or ```--volumes``` option](https://docs.docker.com/compose/reference/down/)_)
