### ISSUE TITLE
Unable to find image 'autoware-kinetic:latest' locally docker: Error response from daemon: pull access denied for autoware-kinetic, repository does not exist or may require'docker login'. See 'docker run --help'.

### ISSUE THREAD

**Issue by VManikantaraju** [docker/compose#6123]
I'm new to this. Im using Ubuntu 16.04

When i run this command 'sudo sh run.sh kinetic' in  /Autoware/docker/generic, after asking password  Iam getting output like this

Use kinetic
Shared directory: /home/root/shared_dir
Unable to find image 'autoware-kinetic:latest' locally
docker: Error response from daemon: pull access denied for autoware-kinetic, repository does not exist or may require 'docker login'.
See 'docker run --help'.

What can be the possible reasons for this error and how can it be avoided? plz help me with this
![screenshot from 2018-08-07 13-02-12](https://user-images.githubusercontent.com/42167759/43761256-31afe824-9a42-11e8-818f-41fb06be59af.png)

**Comment by shin-** [comment]
Welcome to the docker-compose issue tracker! Before creating an issue, please heed the following:

1. This tracker should only be used to report bugs and request features / enhancements to docker-compose
    - For questions and general support, use https://forums.docker.com
    - For documentation issues, use https://github.com/docker/docker.github.io
    - For issues with the `docker stack` commands and the version 3 of the Compose file, use
      https://github.com/docker/cli
2. Use the search function before creating a new issue. Duplicates will be closed and directed to
   the original discussion.
3. When making a bug report, make sure you provide all required information. The easier it is for
   maintainers to reproduce, the faster it'll be fixed.
