### ISSUE TITLE
restart command doesn't respect order and healthchecks

### ISSUE THREAD

**Issue by ulope** [docker/compose#6129]
## Context information (for bug reports)

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

```
services:
  one:
    command: python -c 'import time; time.sleep(5); from http import server; server.test(server.SimpleHTTPRequestHandler,
      bind="0.0.0.0")'
    healthcheck:
      test: curl -s --fail -o /dev/null http://localhost:8000 || exit 1
    image: python:3.6
  two:
    command: python -c 'import time; import urllib.request; [print(urllib.request.urlopen("http://one:8000/").read().decode(),
      time.sleep(1)) for _ in range(100)]'
    depends_on:
      one:
        condition: service_healthy
    image: python:3.6
version: '2.3'
```

## Steps to reproduce the issue

1. Start with `docker-compose up -d`
2. After services are started inspect logs, see that requests from `two` to `one` are successfull
3. Restart with `docker-compose restart`
4. After restart inspect logs

### Observed result
After the restart the services aren't brought up in the correct order. In `two`'s log you will see errors since `one` wasn't finished starting.

### Expected result
For the `restart` command to behave the same way as `up` in regards to respecting startup order and healthchecks.

**Comment by shin-** [comment]
Hi @ulope 

Thank you for your report. However, this is working as intended.

Cheers,

**Comment by ulope** [comment]
Could you expand on how exactly that’s intended behavior?

**Comment by shin-** [comment]
Gladly: `restart` doesn't behave as `up` because it's not `up`. The [documentation for `depends_on`](https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on) specifically states:
> * `docker-compose up` starts services in dependency order. In the following example, db and redis are started before web.
> * `docker-compose up SERVICE` automatically include `SERVICE`’s dependencies. In the following example, `docker-compose up web` also create and start db and redis.

**Comment by ulope** [comment]
That's a pretty lame reason. 
Then why not rename the option to `depends_on_but_only_when_using_up`.

This active neglect you're (and I'm using this collectively here) showing towards compose is really discouraging.

**Comment by embray** [comment]
I agree with @ulope.  Just because the current behavior is as-documented doesn't mean extending the behavior of `depends_on` to consider restarts isn't a valid discussion to be had.

**Comment by nathanweeks** [comment]
> Gladly: `restart` doesn't behave as `up` because it's not `up`. The [documentation for `depends_on`](https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on) specifically states:
> 
> > * `docker-compose up` starts services in dependency order. In the following example, db and redis are started before web.
> > * `docker-compose up SERVICE` automatically include `SERVICE`’s dependencies. In the following example, `docker-compose up web` also create and start db and redis.

Is this interpretation still accurate in 2020 w.r.t. the Compose Specification? The [current wording](https://github.com/compose-spec/compose-spec/blob/bce4ccbe324de210f7e89287a92997f2c69b2597/spec.md) for `depends_on` includes the statements:
> Compose implementations MUST guarantee dependency services have been started before starting a dependent service. Compose implementations MUST guarantee dependency services marked with service_healthy are "healthy" before starting a dependent service.

**Comment by akaouris** [comment]
And it is still the same in 2024. Weird a restart has not been taken into account for the dependencies.

**Comment by der-schick96** [comment]
I have to strongly agree with @ulope @embray and @akaouris. The current behavior seems counter-intuitive. To restart all services without breaking the cluster i must use docker compose stop follwed by a docker compose up. This means that, as soon as healtchecks are implemented, the restart command is rendered useless. Should this really be the intended behaviour?
