### ISSUE TITLE
cap_add - SYS_ADMIN security risk on host VM

### ISSUE THREAD

**Issue by sam0104** [docker/compose#6132]
## Description of the issue
I am using below config in docker-compose . Just want to understand if it is safe to use SYS_ADMIN and /dev/fuse . I need it for running few applications which are only working on SYS_ADMIN , /dev/fuse.
Is there any risk to the host Linux VM ? Can someone inside Docker container attack or modify host VM /dev/fuse or other file systems ? What type of risk is there if I am using SYS_ADMIN and /dev/fuse 
    - SYS_ADMIN
  devices:
    - "/dev/fuse"

## Context information (for bug reports)

```
Output of "docker-compose version"
```

```
Output of "docker version"
```

```
Output of "docker-compose config"
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(if applicable)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by shin-** [comment]
Welcome to the docker-compose issue tracker! Before creating an issue, please heed the following:

1. This tracker should only be used to report bugs and request features / enhancements to docker-compose
    - For questions and general support, use https://forums.docker.com
    - For documentation issues, use https://github.com/docker/docker.github.io
    - For issues with the `docker stack` commands and the version 3 of the Compose file, use
      https://github.com/docker/cli
2. Use the search function before creating a new issue. Duplicates will be closed and directed to
   the original discussion.
3. When making a bug report, make sure you provide all required information. The easier it is for
   maintainers to reproduce, the faster it'll be fixed.
