### ISSUE TITLE
Running docker Gravitee AM setup Config Issue

### ISSUE THREAD

**Issue by posterboyamazon** [docker/compose#6137]
I am following the steps outlined at:
https://docs.gravitee.io/am/2.x/am_installguide_docker.html#running_am_manually

There are 3 config file that need to be edited docker-compose.yml, constants.json and nginx.conf

What are the minimal changes that have to be made for the setup to run correctly.

**Comment by shin-** [comment]
https://github.com/gravitee-io/issues/issues
