### ISSUE TITLE
Add support for build-time extra_hosts for Version 3

### ISSUE THREAD

**Issue by kinnalru** [docker/compose#6138]
It work well for Version 2.3 since #5361 but invalid for Version 3

**Comment by shin-** [comment]
Welcome to the docker-compose issue tracker! Before creating an issue, please heed the following:

1. This tracker should only be used to report bugs and request features / enhancements to docker-compose
    - For questions and general support, use https://forums.docker.com
    - For documentation issues, use https://github.com/docker/docker.github.io
    - For issues with the `docker stack` commands and the version 3 of the Compose file, use
      https://github.com/docker/cli
2. Use the search function before creating a new issue. Duplicates will be closed and directed to
   the original discussion.
3. When making a bug report, make sure you provide all required information. The easier it is for
   maintainers to reproduce, the faster it'll be fixed.

**Comment by nlapshin** [comment]
Hello. Does this feature work in 3.x version?

I use docker-compose version 3.7 and the extra host doesn't work at the build stage.

**Comment by DrPyser** [comment]
@shin- Why was this issue closed? I don't see any issue open for this, and it has been requested multiple times for at least 3 years.

**Comment by burka** [comment]
For anyone searching like me: It's solved in Version 3.9 https://github.com/docker/cli/pull/2517 - you can add `extra_hosts:` in `build:` now.

**Comment by burka** [comment]
For anyone searching like me: It's solved in Version 3.9 https://github.com/docker/cli/pull/2517 - you can add `extra_hosts:` in `build:` now.
