### ISSUE TITLE
Docker compose format shall support `-isolation` parameter for `build` option

### ISSUE THREAD

**Issue by artisticcheese** [docker/compose#6142]
## Description of the issue
Docker compose format needs to suppport `-isolation` parameter for `build` option

## Context information (for bug reports)

As per documentation (https://docs.docker.com/compose/compose-file/#build) there is no supported version like that.

**Comment by shin-** [comment]
v2 only: https://docs.docker.com/compose/compose-file/compose-file-v2/#isolation

**Comment by artisticcheese** [comment]
This was specifically for build not for service. `Build` option does not support `isolation` only service level does

**Comment by shin-** [comment]
I understood that. Please refer to the documentation I shared above ; `isolation` is a supported parameter inside a build definition for the v2 format (specifically 2.1 and above).

**Comment by shin-** [comment]
So far, nobody has requested the addition of this option to the v3 format, hence its absence. v3 format changes are handled separately on the [docker/cli](https://github.com/docker/cli) repo, as pointed out in the issue template:

> This tracker should only be used to report bugs and request features / enhancements to docker-compose
>    - For questions and general support, use https://forums.docker.com
>    - For documentation issues, use https://github.com/docker/docker.github.io
>    - For issues with the `docker stack` commands **and the version 3 of the Compose file, use https://github.com/docker/cli**
