### ISSUE TITLE
Add license information in the Readme 

### ISSUE THREAD

**Issue by Mikerr1111** [docker/compose#6146]
I noticed at the bottom of the Readme there was no section for the software license information. I bring this small issue up because license information is one of the areas I look for in the Readme to let me know how this software can be used.
![doc](https://user-images.githubusercontent.com/18353476/44303098-d4255c80-a2ec-11e8-89ac-20042bc1c33f.png)

[Apache License 2.0](https://github.com/docker/compose/blob/master/LICENSE)

**Comment by shin-** [comment]
https://github.com/docker/compose/blob/master/LICENSE
