### ISSUE TITLE
Default build network should be the default compose network

### ISSUE THREAD

**Issue by superseed** [docker/compose#6148]
This is more of a enhancement request than a bug report, but the current behavior was unexpected to me.

## Description of the issue

I'm using `docker-compose build` on a project with:
- a customized `default` compose network
- a number of services bound to the default network (no `services.<name>.network` key)

During build, the transient containers are bound to the daemon global default network instead of the customized compose `default` network. This was a bit unexpected to me, because it means that if the default compose network embeds config/behavior that is important in the context of the build, it won't be available to the build containers.

I'm able to work around it by using the new-ish `services.<name>.build.network` key, but I feel like I shouldn't have to in this is case, hence the report: it is a small papercut.

## Context information
```
> docker-compose version
docker-compose version 1.22.0, build unknown
docker-py version: 3.5.0
CPython version: 3.7.0
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

```
> docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa8257ec
 Built:             Sun Aug 19 09:47:50 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa8257ec
  Built:            Sun Aug 19 09:47:31 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

To be really precise about the context, I need to use a network other than the daemon's global default bridge because I need the behavior of the embedded Docker DNS which is not provided in this specific one. The default compose network works for me.

As to why I need a network with the embedded Docker DNS (but I don't know if you want to read through that, the baseline is that I need to use the compose default network): my host is a Linux system using systemd-resolved. As such, my `/etc/resolv.conf` contains *only* `127.0.0.53`. Using the daemon default network means that each of my container's `resolv.conf` will contain `8.8.8.8` (since localhost nameservers are stripped). This fails flat for me because I need to resolve names, in my containers, on domains that aren't provided by 8.8.8.8. Rather than going through very complicated steps to make that name resolution work in my containers, using any other bridge network *just works* because the behavior for non-default bridges is that all containers will use the embedded DNS of Docker which delegates this task to native host-side DNS resolution, and through that, my localhost resolver. i.e. when Docker delegates name resolution to the host side, I don't have to pull my hair or go through any config options.

## Steps to reproduce the issue

1. Have a `docker-compose.yml` containing a `networks.default` with specific behavior
2. `docker-compose build`

### Observed result

The specific behavior of the docker-compose `default` network is applied

### Expected result

The specific behavior of the docker-compose `default` network is lost

## Additional information

Archlinux (current) with distribution-provided Docker and Docker Compose, see versions above.

**Comment by shin-** [comment]
As stated before a few times (see e.g. [here](https://github.com/docker/compose/issues/6093#issuecomment-406375210)), builds depending on running services is out of scope for Compose, and it's encouraged to use other tools that are better suited to the task. In that light, I think it would be misguided and confusing for us to change the behavior of `docker-compose build` to match your request.

**Comment by superseed** [comment]
Sorry if I misunderstand your answer, but how is this related to depending on running services?

This request is only about the network to which build containers are bound, and my rationale is that given you can use `services.<name>.build.network` to specify one explicitly, this behavior is supported. I'm only requesting that the default one be the default compose one. It's a matter of not having to sprinkle the `build.network` key everywhere in the file, in a sense :)

**Comment by chrisawad** [comment]
I'm on superseed's side here. It doesn't make sense that `docker compose build` doesnt have an option to use the default network created by compose. At the very least, specifying 'default' should be supported, much like 'host' is. Take this very common use case where the Dockerfile for app would have a RUN command that requires 'db' to be accessible, like in the case of db supported code generation:

```
services:
  app:
    build: .
    network: default
  db:
    ...
```

Without having default networking capability for builds, we would have to expose db ports to the host, set network: host here, and use the bridge IP instead of 'db' in the RUN command. Such an ugly solution.

**Comment by chrisawad** [comment]
In case anyone is reading this, here's how I hacked this so you don't have to put the bridge IP instead of 'db' everywhere:
```
services:
  app:
    build: 
      context: .
      network: host
      extra_hosts:
        - db:172.17.0.1            # the docker bridge ip
  db:
    image: postgres
    ports:
       - 5432:5432/tcp
