### ISSUE TITLE
naming error inconsistency

### ISSUE THREAD

**Issue by fxdgear** [docker/compose#615]
I noticed an inconsistency when when trying to build containers with invalid names. 

if the name includes a hyphen, the error is: 
```bash
$ fig build
Invalid service name "foo-bar" - only [a-zA-Z0-9] are allowed
```
Notice the uppercase letters in the regex. 

If renamed to be camel case:

```bash
... 
build output
...
Building FooBar...
Invalid repository name (hub_FooBar), only [a-z0-9-_.] are allowed
```

Now notice that Uppercase is not allowed, but also notice that hyphens and underscores and periods are allowed.

**Comment by burabure** [comment]
this is really annoying =(

**Comment by deepj** [comment]
This is really WTF moment from trying to use `docker-compose`. I don't understand why I can't use hyphens or underscores at least in a name of service. I really need to distinguish containers by a suffix. I.e. `fluentd` and `fluentd-ui`. What solution is for these situations?

**Comment by dnephin** [comment]
This will be fixed by #1066

**Comment by deepj** [comment]
Thank you

**Comment by dnephin** [comment]
Service names now support uppercase, `_`, `-`, and `.`

**Comment by dreamcat4** [comment]
Thanks. :)
