### ISSUE TITLE
Not able to install the latest version

### ISSUE THREAD

**Issue by caldarolad** [docker/compose#6150]
I'm trying to get the latest version of compose.  What am I doing wrong here?

[root@cua43118doc402 docker]# sudo rm /usr/local/bin/docker-compose
[root@cua43118doc402 docker]# cd /usr/local/bin
[root@cua43118doc402 bin]# ls -l
total 0
[root@cua43118doc402 bin]# sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   1202      0 --:--:-- --:--:-- --:--:--  1205
100 11.2M  100 11.2M    0     0  13.5M      0 --:--:-- --:--:-- --:--:--  103M
[root@cua43118doc402 bin]# docker-compose --version
docker-compose version 1.9.0, build 2585387

[root@cua43118doc402 etc]# cat system-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by shin-** [comment]
> What am I doing wrong here?

- Failing to use the issue template
- Failing to check or include the output of `which docker-compose`
- Expecting recent things on RHEL

**Comment by srinivasreddy** [comment]
that is kinda harsh @shin-

**Comment by shin-** [comment]
Sorry! I admit I was being somewhat facetious, but that partly stems from the fact that the issue hardly provides any information, which would have been somewhat remedied if OP had followed the issue template. 

@caldarolad - you most likely need to configure your `PATH` variable to prioritize /usr/local/bin over the path where RHEL's default Compose is situated.

**Comment by caldarolad** [comment]
That was it.  Had a rhel version of docker-compose being used over what I was installing.  Thanks.
