### ISSUE TITLE
Proposal: SERVICE argument optional when only one defined

### ISSUE THREAD

**Issue by rafacouto** [docker/compose#6156]
It's a bit annoying to specify the service name **when the _docker-compose.yml_ contains just one service**.  It's redundant information and sometimes people have to review the file to remember the service name. Beginners who start defining _docker-compose.yml_ with only one service don't understand the need to put a service name (obviously, they get aware the importance after when defining more services).

As an **usability feature**, _docker-compose_ could allow a service pseudo-name like ``` _default_```  definition in order to allow command execution without service name and take that service as the only one to process with the command. Definition example:

    version: '3'
    services:
      _default_:
        image: 'certbot/certbot'

Presumably, it should be easy to implement since _docker-compose_ produces this error:

    $ docker-compose run
    Run a one-off command on a service.

Before exiting with error, ```_default_``` service name can be scanned from _docker-compose.yml_ and get it as the service name to execute.

If default service is not found, the error message becomes something like _Run a one-off command on a service or define a service with \_default\_ servicename._

**Comment by janmyszkier** [comment]
I'm voting down and here's why:
When there is only one node, to correctly decide what to do, you have to analyze if the node is type A or type B. Because that analysis requires additional validation I wouldn't recommend adding this additional step just for the sake of `docker-compose.yml having one line (and indentation) less.

**Comment by shin-** [comment]
Thank you for your submission.

I'm willing to keep an open mind, but I don't see how this is useful or desirable. It'll just create more weird use cases and potential for confusion. Moreover, the "natural" command and starting point for beginners should be `docker-compose up`, not `docker-compose run` ; and that one doesn't need a service name to work as advertised.

**Comment by rafacouto** [comment]
@shin-, you are right with the _up command_ and have convinced me with that argument :smiley: Please, dismiss this proposal. Thank you for your answers!
