### ISSUE TITLE
use --detach and --abort-on-container-exit in conjunction

### ISSUE THREAD

**Issue by Billy-** [docker/compose#6160]
## Description of the issue
`--detach` and `--abort-on-contatiner-exit` cannot be used in conjunction
## Context information (for bug reports)
This is the expected and documented behaviour, however I cannot see why this would be the case, I don't see any technical or semantic limitation. Should be able to run a stack detached and still abort if a container exits..

Skipping the rest of the issue template as this is not a bug (feature req) so versions etc. are irrelevant.

**Comment by shin-** [comment]
When you use `--detach`, the Compose process exits as soon as services are running. On the other hand, `--abort-on-container-exit` relies on the Compose process watching for container events indicating an exit, hence the limitation.

**Comment by cowwoc** [comment]
@shin- Can't you fork a Compose process running in the background to do the watching?

**Comment by NathanielRN** [comment]
I was also hoping for a feature like this, to be able to run the `docker-compose up` process in the background by having it end automatically when a container exits. (Because I want to be running a script at the same time as the `docker-compose` and want it to end when `docker-compose` ends).
