### ISSUE TITLE
Ask boot2docker for ip?

### ISSUE THREAD

**Issue by icambron** [docker/compose#617]
The way to set up fig + boot2docker seems to be:

 1. Run boot2docker
 2. Take its IP:port, cert path, and a TLS flag and put them in your shell init file
 3. run fig

It would be nice, though, if Fig fails to find DOCKER_HOST and boot2docker is both on the path and has a "running" status, to have Fig just ask boot2docker for the relevant details and use those instead.

**Comment by dnephin** [comment]
docker-machine is now the way to handle this. It's not the job of compose to query for the host.

I believe the [toolbox](https://www.docker.com/toolbox) may take care of this type of configuration for you on  osx/windows.
