### ISSUE TITLE
Network priority not implemented in version 3.0

### ISSUE THREAD

**Issue by combin** [docker/compose#6182]
I have docker-compose.yml v3.0 and i have issue from #4645. [Acording by documentations](https://docs.docker.com/compose/compose-file/#networks) it is not implemented in 3.0. Is it planned to implement it? Or is there any reason why this feature was removed?

```
# docker-compose --version
docker-compose version 1.22.0, build f46880f
```

**Comment by shin-** [comment]
> For issues with the `docker stack` commands and the version 3 of the Compose file, use https://github.com/docker/cli
