### ISSUE TITLE
"docker-compose up" print "docker run" command

### ISSUE THREAD

**Issue by melissachang** [docker/compose#6183]
I would like there to be a way for `docker-compose up` to print a `docker run` command for each service.

I'm debugging an app issue. It would be useful for me to run "docker run" for one of my docker-compose services. For example, my service has two volumes in docker-compose.yml. I want to try running `docker run` with one volume removed.

I tried running `docker-compose up` with `--log-level DEBUG` and `--verbose`, and didn't see this.

**Comment by shin-** [comment]
See previous threads on the same topic: #5264, #4903

**Comment by melissachang** [comment]
To add some context, I have the following docker-compose.yml:
```
  ui:
    build:
      context: ui
      dockerfile: Dockerfile.local
    volumes:
      - ./ui:/ui
      - /ui/node_modules
```

For debugging a bug, I am trying to figure out the corresponding `docker run` command. I tried `docker run -it -v /ui/node_modules -v /Users/melchang/data-explorer/ui:/ui ffcc44b8a679 bash`, but I'm not able to reproduce the bug, so that is not correct.

I've spent at least an hour trying to figure out the right `-v` flags, and I haven't figured it out yet.

Even if `docker-compose up` doesn't run `docker run`, it would be nice if it could print the corresponding `docker run` commands.

**Comment by shin-** [comment]
I see you're declaring an anonymous volume ; try running `docker-compose up` with the `-V` flag and see if that fixes your bug. ([more info here](https://docs.docker.com/compose/overview/#preserve-volume-data-when-containers-are-created) and in #5400 )

**Comment by melissachang** [comment]
Thanks, `-V` worked. There's a bug in docker or npm somewhere, but unfortunately I don't have time to diagnose.
