### ISSUE TITLE
docker-compose for armhf?

### ISSUE THREAD

**Issue by CaptainSkywave** [docker/compose#6188]
..will there be a docker-compose version for armhf SDBs (eg. Odroid XU3/4)?

**Comment by shin-** [comment]
Hi @CaptainSkywave 

We currently don't have any plans to distribute an official `docker-compose` binary for ARM architectures. However, any system with a version of Python installed can run Compose when [installed using `pip`](https://docs.docker.com/compose/install/#install-using-pip)

**Comment by CaptainSkywave** [comment]
thank you
