### ISSUE TITLE
env file required at build time

### ISSUE THREAD

**Issue by GodefroyClair** [docker/compose#6200]
## Description of the issue
When I build images with docker-compose build. For exemple:
`docker-compose -f docker-compose.prod.yml build`
if I have filenames in my env_file key and those files don't exist, I have an error:
`"ERROR: Couldn't find env file: /Users/godot/flylab/ipsum/cuvee/bdd.env"`
But, correct me if I am wrong, those files are used at instantiation time when you do:
`docker-compose -f docker-compose.prod.yml up -d`
So why are they required at build time?

In development, it doesn't matter much but, in production, I build my images without a need for a environment context, push them on a repo and then pull them at my client and _only then_ I will add my environment files.
It's no big deal but I hope I am not missing a deeper reason...

## Context information (for bug reports)

docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

docker-version:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

```
Output of "docker-compose config"
```
ERROR: Couldn't find env file: /Users/godot/flylab/ipsum/cuvee/bdd.env

**Comment by shin-** [comment]
See previous thread on this issue: #5375
