### ISSUE TITLE
Env Vars Interpolation Snags with Custom Env File

### ISSUE THREAD

**Issue by Tensho** [docker/compose#6210]
## Description

When I use env vars from the default `.env` file any **interpolation** works as expected. But everything not so nice if I'd like to use a custom env file, e.g. `.env.mizu` or `.env.test`.

## Context

```
$ docker-compose version
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```
```
$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
```
$ cat .env.mizu
PATH_TO_SHARED_DATA=~/projects/alpha/data
HOST=example.com
```
```
$ cat docker-compose.yml
version: '3'

services:
  one:
    image: ruby
    volumes:
      - ${PATH_TO_SHARED_DATA}:/app
    env_file:
      - .env.mizu
    networks:
      default:
        aliases:
          - ${HOST}
```
```
$ docker-compose config
WARNING: The PATH_TO_SHARED_DATA variable is not set. Defaulting to a blank string.
WARNING: The HOST variable is not set. Defaulting to a blank string.
services:
  one:
    environment:
      HOST: example.com
      PATH_TO_SHARED_DATA: ~/projects/alpha/data
    image: ruby
    networks:
      default:
        aliases:
        - ''
    volumes:
    - .:/app:rw
version: '3.0'
```

### Observed Result

1. There are **warnings** about unset (blank) env vars, despite they are declared in the custom env file and can be observed in config output.
2. Nor `PATH_TO_SHARED_DATA` neither `HOST` env var interpolation **doesn't work**.

### Expected Result

The same as env vars would be declared in the default `.env` file:
```
services:
  one:
    image: ruby
    networks:
      default:
        aliases:
        - example.com
    volumes:
    - /Users/tensho/projects/alpha/data:/app:rw
version: '3.0'
```

## Additional Information

Docker for Mac
```
$ system_profiler SPSoftwareDataType | grep Version
      System Version: macOS 10.13.6 (17G65)
      Kernel Version: Darwin 17.7.0
```

**Comment by shin-** [comment]
Hi @Tensho 

This has been asked and answered several times before. Please refer to [the docs](https://docs.docker.com/compose/environment-variables/) regarding how environment variables work in Compose.

**Comment by shin-** [comment]
Here's a previous comment of mine on a similar issue: https://github.com/docker/compose/issues/4189#issuecomment-274915631

**Comment by Tensho** [comment]
@shin- Thank you for the quick reply. TBH, I've read env vars official documentation several times and haven't felt that specific difference between `.env` file and `env_file` configuration option. Now it looks obvious after you reference to the GitHub comment of course. But if I'm not the only one who has been confused, maybe it's worth to add a special note about this trait to the official documentation.
