### ISSUE TITLE
Dockerfile: where are the Dockerfiles for https://hub.docker.com/r/docker/compose/tags/

### ISSUE THREAD

**Issue by mbana** [docker/compose#6218]
Hi,

Where are the `Dockerfile`s for the images available at: https://hub.docker.com/r/docker/compose/tags/

I now it's Alpine by running it but It would be nice if this was documented somewhere.

```sh
docker run --rm -it --entrypoint=sh docker/compose:1.22.0           

/ # cat /etc/issue 
Welcome to Alpine Linux 3.6
Kernel \r on an \m (\l)

/ # 
```

**Comment by shin-** [comment]
https://github.com/docker/compose/blob/master/Dockerfile.run

**Comment by mbana** [comment]
Thanks. This should be better documented-even a reference to the file in the Dockerhub page would be great.
