### ISSUE TITLE
docker-compose is detected by Clamav as "Unix.Trojan.XbashPython"

### ISSUE THREAD

**Issue by florian-hartmann** [docker/compose#6220]
## Description of the issue
Clamav on Unix is detecting the docker-compose binary as Unix.Trojan.XbashPython-6690212-0.

See also:
https://www.virustotal.com/#/file/f679a24b93f291c3bffaff340467494f388c0c251649d640e661d509db9d57e9/detection

## Context information (for bug reports)
OS: Ubuntu 16.04.5 LTS
Clamav: ClamAV 0.100.1/24981/Mon Sep 24 15:50:40 2018

```
Output of "docker-compose version"

docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

## Steps to reproduce the issue
```
curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
clamscan /usr/local/bin/docker-compose
```

### Observed result
```
/usr/local/bin/docker-compose: Unix.Trojan.XbashPython-6690212-0 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 6658562
Engine version: 0.100.1
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 0.12 MB
Data read: 11.20 MB (ratio 0.01:1)
Time: 9.141 sec (0 m 9 s)
```

### Expected result
Not being detected as trojan.

**Comment by JGalego** [comment]
I filed a false positive report with the ClamAV team.
Let's see what they have to say!

**Comment by shin-** [comment]
Thanks @JGalego - I'm interested in the answer as well if you can share once you hear back.

Our release process is entirely automated and relies on isolated systems on CI providers (CircleCI and AppVeyor) for building binaries. While the risk of infection is never non-zero, chances that this is a legitimate threat are very slim.

**Comment by redmop** [comment]
The same thing popped up this weekend for borgbackup. It's getting a false positive there too. (I know it's not directly related, I'm just reinforcing the false positive thought)

**Comment by Xavious** [comment]
`"/usr/local/bin/docker-compose" "Unix.Trojan.XbashPython-6690212-0 FOUND"`

I too ran into this malware alert on 2018-09-22 and by 2018-09-26 it was no longer showing up in the ClamAV scan log, even though it was never actioned on.

@JGalego did you ever receive confirmation for your false positive report?

**Comment by JGalego** [comment]
Still waiting for an answer.

**Comment by JGalego** [comment]
It's not an official answer, but I received an email from the clamav-virusdb mailing list that shows the **Unix.Trojan.XbashPython-6690212-0** in the dropped detection signatures section.

**Comment by Xavious** [comment]
@JGalego good to know. I'll just take that as confirmation that they must have actioned on your report and conclude that this signature, in relation to docker-compose, is benign. Thanks for the update!

**Comment by florian-hartmann** [comment]
My Clamav now also shows docker-compose as clean. I think we can close the issue then.

@JGalego thx for reporting to Clamav.
