### ISSUE TITLE
how use tty.Bluetooth* or /dev/tty.* and /dev/cu.* in mac os

### ISSUE THREAD

**Issue by hktalent** [docker/compose#6228]
how use tty.Bluetooth* or /dev/tty.* and /dev/cu.* in mac os
```
docker run -it --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --cap-add=ALL  --net=host --expose 80-65530 -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/cu.Bluetooth-Incoming-Port --device /dev/tty.Bluetooth-Incoming-Port --privileged  --name='kali-linux2018091d' m.t.x_kali-linux20180926_2332 /bin/bash
```

**Comment by shin-** [comment]
Hi @hktalent ! We strive to be welcoming to newcomers, so here's a few things to keep in mind for the future as I close this:
- **GitHub is generally not for support**: as the issue template states, "This tracker should only be used to report bugs and request features / enhancements". Docker in particular uses their [forums](https://forums.docker.com) for community support.
- **Bug reports should be substantial**: if you believe what you're seeing is a bug, a good approach to getting the issue solved is to submit a report that has all the information required for the maintainer to reproduce the problem. That includes, but isn't limited to, the fields of the issue report you failed to fill out.
- **Make sure you're making your report in the right place**: In this case, you're reporting an issue with `docker` commands, but reporting it on the repository for the `docker-compose` tool.

Please go through these steps in the future. Open-source maintainers, many of whom are volunteers, will feel like you're respecting their time and be more willing to help you.
