### ISSUE TITLE
docker container can not be started when I have CMD: "npm start " in last line of dockerfile

### ISSUE THREAD

**Issue by vm31** [docker/compose#6232]
## Context information (for bug reports)

```
Output of "docker-compose version"
```

```
Output of "docker version"
```

```
Output of "docker-compose config"
```

## Steps to reproduce the issue

1.docker build
2.docker run 
3.docker ps

### Observed result
no container is shown
### Expected result
container hsould start and status should be up and running
### Stacktrace / full error message

```
(if applicable)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by shin-** [comment]
Hi @vm31 ! We strive to be welcoming to newcomers, so here's a few things to keep in mind for the future as I close this:
- **GitHub is generally not for support**: as the issue template states, "This tracker should only be used to report bugs and request features / enhancements". Docker in particular uses their [forums](https://forums.docker.com) for community support.
- **Bug reports should be substantial**: if you believe what you're seeing is a bug, a good approach to getting the issue solved is to submit a report that has all the information required for the maintainer to reproduce the problem. That includes, but isn't limited to, the fields of the issue report you failed to fill out.
- **Make sure you're making your report in the right place**: In this case, you're reporting an issue with `docker` commands, but reporting it on the repository for the `docker-compose` tool.

Please go through these steps in the future. Open-source maintainers, many of whom are volunteers, will feel like you're respecting their time and be more willing to help you.
