### ISSUE TITLE
Support specifying runc's config.json when building images

### ISSUE THREAD

**Issue by mathstuf** [docker/compose#6238]
## Description of the issue
I'd like to utilize runc's config.json support for hooks in order to leverage the oci-register-machine and oci-systemd-hook hooks for better management of logs and such.

Not sure if being able to specify `config.json` is the proper way of doing it, but it seems like it'd be able to work.

### Expected result

Containers and logs should be available via `machinectl` and `journalctl -M`.

**Comment by mathstuf** [comment]
Seems that this issue would likely help: https://github.com/moby/moby/issues/36987

**Comment by shin-** [comment]
Thanks for the suggestion! However, I don't think there's much we can do at the Compose level at the moment. It would need to be a feature in moby/moby first.
