### ISSUE TITLE
docker-compose broken on Docker Toolbox 18.06.1-ce

### ISSUE THREAD

**Issue by leolimajr** [docker/compose#6249]
## Description of the issue

docker-compose is not working with Docker Toolbox on Windows 7. Docker works, but compose simply quit without presenting any output.

## Context information (for bug reports)
```
$ docker-compose version
no output
```
```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215
 Built:             Thu Aug 23 22:47:05 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
```
$ docker-compose config
no output

```
## Steps to reproduce the issue

1. Install latest [18.06.1-ce](https://github.com/docker/toolbox/releases/tag/v18.06.1-ce) Docker Toolbox on Windows 7
2. Run docker-compose version

### Observed result

docker-compose exists without presenting output for any argument/combination of arguments. 

### Expected result

docker-compose would print the version

## Additional information
I have python 3.6.5 installed
Windows 7 [Version 6.1.7601]
Docker Toolbox 18.06.1-ce
- docker 18.06.1-ce
- docker-machine 0.15.0
- docker-compose 1.22.0
- Kitematic 0.17.3
- Boot2Docker ISO 18.06.1-ce
- VirtualBox 5.2.16

**Comment by batiati** [comment]
+1, on Windows 10 after Windows Update

**Comment by leolimajr** [comment]
I did some tests  with old versions and discovered that the last version to work in my setup is 1.19.0:

```
$ docker-compose.exe version
docker-compose version 1.19.0, build 9e633ef3
docker-py version: 2.7.0
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

**Comment by batiati** [comment]
Thank you @leolimajr ! Version 1.19.0 works for me too!

**Comment by shin-** [comment]
Consolidating with #6254 - thanks for reporting it!
