### ISSUE TITLE
Client+version+1.22+is+too+old+when+trying+to+build+a+docker+image

### ISSUE THREAD

**Issue by abhi0017** [docker/compose#6250]
## Context information (for bug reports)

```
Output of "docker-compose version"
```

```
Output of "docker version"
```

```
Output of "docker-compose config"
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(if applicable)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by abhi0017** [comment]
It is still showing after I changed manually the version of docker-compose to 2.1 too. now not getting how to resolve it.

**Comment by leolimajr** [comment]
@abhi0017 Unfortunately all crystal balls are offline. Have you read the template for filling bugs? Please edit to include information required for contextualization of your problem (steps to reproduce, versions, etc).
