### ISSUE TITLE
Use official Docker image as docker/compose base image

### ISSUE THREAD

**Issue by nvllsvm** [docker/compose#6252]
## Description of the issue
The official Docker image can be used to simplify the Docker Compose image (`docker/compose`). The official image is also based on Alpine Linux.

### Observed result
Building `Dockerfile.run` inherits from `alpine:3.6` and downloads the Docker binary from `https://download.docker.com/linux/static/stable/x86_64/docker-17.12.1-ce.tgz`.

### Expected result
Building `Dockerfile.run` inherits from `docker:17.12.1` and uses the inherited Docker binary

**Comment by shin-** [comment]
The `docker` image includes a lot of things we don't need (basically the whole daemon / moby part of Docker). `docker/compose:1.23.0-rc1` is 25 MB including the `docker-compose` executable, whereas `docker:17.12.1` is already 37MB by itself (and newer versions have grown another ~10).

Based on that, I don't think the change is warranted.

**Comment by nvllsvm** [comment]
@shin- Good call. Updated to use the binary from the official image via multi-stage.
