### ISSUE TITLE
Windows docker-compose gives no output

### ISSUE THREAD

**Issue by alexvingg** [docker/compose#6254]
## Description of the issue

docker-compose is not working with Docker Windows 10 PRO. Docker works, but compose simply quit without presenting any output.

## Context information (for bug reports)

```
Output of "docker-compose version"
no output

```

```
Output of "docker version"

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

## Steps to reproduce the issue

1. Install latest 18.06.1-ce Docker
2. Run docker-compose version

### Observed result

docker-compose exists without presenting output for any argument/combination of arguments.

[Powershell](https://imgur.com/a/dYbySSy)

### Expected result

docker-compose would print the version

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Windows 10 Pro.
docker 18.06.1-ce
docker-machine 0.15.0
docker-compose 1.22.0

**Comment by eskivelevolution** [comment]
Hi,

I have the same issue.

**Comment by alexvingg** [comment]
I solved the problem by downloading the version of compose 1.19

**Comment by studiocuboweb** [comment]
Same issue... how to install the verison 1.19 for windows? 
I have 1.20.0? thanks

**Comment by alexvingg** [comment]
@studiocuboweb replace docker-compose.exe in C:\Program Files\Docker\Docker\Resources\bin\ by https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Windows-x86_64.exe

**Comment by lealcalhau** [comment]
Same here, i solved  the problem by replace the version of compose 1.19 as @alexvingg comment above.

Thanks

**Comment by shin-** [comment]
Thanks for the report. I'm surprised this took this long to surface if it's been an issue since 1.20.0. Could this be due in part to a recent Windows update?

What's the value of `%errorlevel%` after one of these commands? Do you get anything if you run the command with the `--verbose` flag?

**Comment by leolimajr** [comment]
Same issue as #6249 I suppose?

**Comment by leolimajr** [comment]
> Thanks for the report. I'm surprised this took this long to surface if it's been an issue since 1.20.0. Could this be due in part to a recent Windows update?
> 
> If anyone encountering this error could answer the following questions, it'd be very helpful:
> 
> 1. What's the value of `%errorlevel%` after one of these commands?
> 2. Do you get anything if you run the command with the `--verbose` flag?
> 3. If you install Compose via `pip` instead, does the same problem occur?

1. 0
2. no output
3. same

**Comment by alexvingg** [comment]
> Thanks for the report. I'm surprised this took this long to surface if it's been an issue since 1.20.0. Could this be due in part to a recent Windows update?
> 
> If anyone encountering this error could answer the following questions, it'd be very helpful:
> 
> 1. What's the value of `%errorlevel%` after one of these commands?
> 2. Do you get anything if you run the command with the `--verbose` flag?
> 3. If you install Compose via `pip` instead, does the same problem occur?

0
no output
same

**Comment by shin-** [comment]
@alexvingg @leolimajr Thanks! We've tried to reproduce on a few different setups but things seem to be working fine on our end. It's interesting that the `pip` installed version doesn't work either. Are you able to run python at all otherwise (e.g. what happens if you do `python -c "print('hello world')"`)?

Additionally, can you share some of the information that's present in Window's `System Information` panel - specifically `OS name`, `Version`, `System type` and `Processor`? Here's what it looks like on mine for reference:
![image](https://user-images.githubusercontent.com/1086876/46612009-3f590700-cac4-11e8-93af-7c4598a644c8.png)

**Comment by vitormarcal** [comment]
After the windows were updated automatically, the docker-compose no longer worked and had no output on the console. Replacing version 1.22.0 to 1.19 resolved the problem immediately.

**Comment by leolimajr** [comment]
@shin- I have a colleague in a similar setup  which cannot reproduce the issue in the latest version of docker-compose.

Python output:
```
$ python -c "print('hello world')"
hello world

$python --version
Python 3.6.6
```

My system information **which does not work** with latest docker-compose:
```
OS Name	Microsoft Windows 7 Professional
Version	6.1.7601 Service Pack 1 Build 7601
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	RESTRICTED
System Manufacturer	LENOVO
System Model	20ENS02M00
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz, 2701 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	LENOVO N1EET79W (1.52 ), 13/07/2018
SMBIOS Version	2.8
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "6.1.7601.24214"
User Name	RESTRICTED
Time Zone	W. Europe Daylight Time
Installed Physical Memory (RAM)	16,0 GB
Total Physical Memory	15,5 GB
Available Physical Memory	3,31 GB
Total Virtual Memory	31,4 GB
Available Virtual Memory	15,9 GB
Page File Space	16,0 GB
Page File	C:\pagefile.sys
```
System information of a colleague **that does work** with latest docker-compose
```
OS Name  Microsoft Windows 7 Professional
Version  6.1.7601 Service Pack 1 Build 7601
Other OS Description   Not Available
OS Manufacturer  Microsoft Corporation
System Name  RESTRICTED
System Manufacturer  LENOVO
System Model  20EF000SGE
System Type  x64-based PC
Processor  Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz, 2901 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date  LENOVO GNET72WW (2.20 ), 26-02-2015
SMBIOS Version  2.7
Windows Directory  C:\Windows
System Directory  C:\Windows\system32
Boot Device  \Device\HarddiskVolume1
Locale  United States
Hardware Abstraction Layer  Version = "6.1.7601.24168"
User Name  RESTRICTED
Time Zone  W. Europe Daylight Time
Installed Physical Memory (RAM)  16.0 GB
Total Physical Memory  15.6 GB
Available Physical Memory  2.80 GB
Total Virtual Memory  31.3 GB
Available Virtual Memory  15.8 GB
Page File Space  15.6 GB
Page File  C:\pagefile.sys
```

**Comment by douglasgsouza** [comment]
I have the same problem here.
After rebooting my desktop and windows have automatically installed an update docker-compose 1.22.0 has stopped working.

I tried to uninstall and install Docker for Windows but the problem continues.

`docker-compose -v`
`Exited with No output`

`docker -v`
`Docker version 18.06.1-ce, build e68fc7a`

Notary: 0.6.1
Compose: 1.22.0
Credential Helpers: 0.6.0
Machine: 0.15.0
Kubernetes: v1,10,3

`python --version`
`Python 3.6.6

`pip --version`
pip 18.0

`docker info`
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d0067f2
ID: M4XP:Q56U:CYOV:JTPN:GY22:5IFD:SAHS:KWPL:SP2K:KLJZ:CZQZ:UQFG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 47
 System Time: 2018-10-08T14:32:12.6567377Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

`systeminfo`
_Some information has been omitted for security_

```
Operating system name:               Microsoft Windows 10 Pro
Operating system version:             10.0.17134 N/A compilação 17134
Operating system manufacturer:         Microsoft Corporation
OS configuration:                        Standalone workstation
Operating system build type: Multiprocessor Free
System Manufacturer:                     Dell Inc.
System Model:                         XPS 8900
Type of system:                           x64-based PC
Processor (s):                           1 processador(es) instalado(s).
                                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~3408 Mhz
BIOS Version:                            Dell Inc. 2.1.3, 20/01/2016
Windows Folder:                          C:\WINDOWS
System Folder:                          C:\WINDOWS\system32
Initialize device:                   \Device\HarddiskVolume1
Location of the system:                     pt-br;Português (Brasil)
Fuso horário:                              (UTC-03:00) Brasília
Total physical memory:                      16.323 MB
Available physical memory:                 7.209 MB
Virtual Memory: Maximum Size:           22.979 MB
Virtual Memory: Available:               12.657 MB
Paging file location (s):         C:\pagefile.sys
Hotfix(es):                                7 hotfix(es) installed(s).
                                           [01]: KB4100347
                                           [02]: KB4343669
                                           [03]: KB4343902
                                           [04]: KB4456655
                                           [05]: KB4457146
                                           [06]: KB4457128
                                           [07]: KB4458469
Requirements for Hyper-V:                     Hypervisor detected. Resources required for Hyper-V will not be displayed.
```

**Comment by mjpirez** [comment]
Same behaviour here. Check out sys info;

Nome do host:                              xxxx
Nome do sistema operacional:               Microsoft Windows 10 Enterprise
Versão do sistema operacional:             10.0.14393 N/A compilação 14393
Fabricante do sistema operacional:         Microsoft Corporation
Configuração do SO:                        Estação de trabalho membro
Tipo de compilação do sistema operacional: Multiprocessor Free
Proprietário registrado:                   Everis
Organização registrada:                    Everis
Identificação do produto:                  00329-00000-00003-AA690
Data da instalação original:               21/03/2018, 10:43:19
Tempo de Inicialização do Sistema:         08/10/2018, 09:42:51
Fabricante do sistema:                     Dell Inc.
Modelo do sistema:                         Latitude 5480
Tipo de sistema:                           x64-based PC
Processador(es):                           1 processador(es) instalado(s).
                                           [01]: Intel64 Family 6 Model 142 Stepping 9 GenuineIntel ~2701 Mhz
Versão do BIOS:                            Dell Inc. 1.5.3, 07/08/2017
Pasta do Windows:                          C:\WINDOWS
Pasta do sistema:                          C:\WINDOWS\system32
Inicializar dispositivo:                   \Device\HarddiskVolume2
Localidade do sistema:                     pt-br;Português (Brasil)
Localidade de entrada:                     pt-br;Português (Brasil)
Fuso horário:                              (UTC-03:00) Brasília
Memória física total:                      16.266 MB
Memória física disponível:                 7.392 MB
Memória Virtual: Tamanho Máximo:           18.698 MB
Memória Virtual: Disponível:               9.315 MB
Memória Virtual: Em Uso:                   9.383 MB
Local(is) de arquivo de paginação:         C:\pagefile.sys
Domínio:                                   usersad.everis.int
Servidor de Logon:                         \\[]
Hotfix(es):                                7 hotfix(es) instalado(s).
                                           [01]: KB4033393
                                           [02]: KB4033631
                                           [03]: KB4049065
                                           [04]: KB4049411
                                           [05]: KB4054855
                                           [06]: KB4103729
                                           [07]: KB4103723

**Comment by clezioalves** [comment]
I have the same problem.

Nome do host:                              DESKTOP-SFL4N6B
Nome do sistema operacional:               Microsoft Windows 10 Pro
Versão do sistema operacional:             10.0.17134 N/A compilação 17134
Fabricante do sistema operacional:         Microsoft Corporation
Configuração do SO:                        Estação de trabalho autônoma
Tipo de compilação do sistema operacional: Multiprocessor Free
Proprietário registrado:                   N/A
Organização registrada:                    N/A
Identificação do produto:                  00330-80192-66770-AA411
Data da instalação original:               02/06/2018, 06:46:19
Tempo de Inicialização do Sistema:         18/10/2018, 12:18:28
Fabricante do sistema:                     To Be Filled By O.E.M.
Modelo do sistema:                         To Be Filled By O.E.M.
Tipo de sistema:                           x64-based PC
Processador(es):                           1 processador(es) instalado(s).
                                           [01]: Intel64 Family 6 Model 58 Stepping 9 GenuineIntel ~3000 Mhz
Versão do BIOS:                            American Megatrends Inc. P1.10, 11/07/2013
Pasta do Windows:                          C:\WINDOWS
Pasta do sistema:                          C:\WINDOWS\system32
Inicializar dispositivo:                   \Device\HarddiskVolume1
Localidade do sistema:                     pt-br;Português (Brasil)
Localidade de entrada:                     pt-br;Português (Brasil)
Fuso horário:                              (UTC-03:00) Brasília
Memória física total:                      5.843 MB
Memória física disponível:                 470 MB
Memória Virtual: Tamanho Máximo:           12.499 MB
Memória Virtual: Disponível:               4.701 MB
Memória Virtual: Em Uso:                   7.798 MB
Local(is) de arquivo de paginação:         D:\pagefile.sys
Domínio:                                   WORKGROUP
Servidor de Logon:                         \\DESKTOP-SFL4N6B
Hotfix(es):                                7 hotfix(es) instalado(s).
                                           [01]: KB4100347
                                           [02]: KB4343669
                                           [03]: KB4343902
                                           [04]: KB4456655
                                           [05]: KB4457146
                                           [06]: KB4462930
                                           [07]: KB4462919

**Comment by shin-** [comment]
Looks like the majority of you are using a Portguese/Brazilian localized version of Windows. Maybe that has something to do with the issue? Does changing the system's language help in any way?

**Comment by Cleomir** [comment]
> Looks like the majority of you are using a Portguese/Brazilian localized version of Windows. Maybe that has something to do with the issue? Does changing the system's language help in any way?

Although my keyboard is Brazilian, I'm also have the same problem.

Host Name:                 DESKTOP-M4E1828
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                00330-80000-00000-AA239
Original Install Date:     5/14/2018, 10:53:48 AM
System Boot Time:          10/21/2018, 11:46:11 PM
System Manufacturer:       System manufacturer
System Model:              System Product Name
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 58 Stepping 9 GenuineIntel ~3501 Mhz
BIOS Version:              American Megatrends Inc. 1707, 3/15/2013
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             en-us;English (United States)
Input Locale:              pt-br;Portuguese (Brazil)
Time Zone:                 (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius
Total Physical Memory:     16,323 MB
Available Physical Memory: 9,402 MB
Virtual Memory: Max Size:  18,755 MB
Virtual Memory: Available: 7,613 MB
Virtual Memory: In Use:    11,142 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-M4E1828
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB4100347
                           [02]: KB4343669
                           [03]: KB4456655
                           [04]: KB4457146
                           [05]: KB4462930
                           [06]: KB4462919

**Comment by brunosite** [comment]
My settings are in English and the same problem happens. I temporarily put the summer 1.19, but I look forward to an ideal solution for this.

**Comment by pierotofy** [comment]
+1 :+1:

**Comment by jbrasileiro** [comment]
it's working now. :\

I changed **`Language preferences`**:
1 - open **`Regional Settings - Language, Date/Time format, keyboard locale`**.
```
intl.cpl
```
2 - Changed **`Format`** from **`Poruguese (Brazil)`** to **`English (United States)`**.
3 - Run docker-compose from version **`1.23.1`** to **`1.19.0`**, until `docker-compose --version` got to work.
4 - Changed back **`Format`** to **`Poruguese (Brazil)`**
5- Restarted Windows.

```
docker info   & systeminfo   & docker-compose --version                                                                          
```

docker info:

```
Containers: 1                                                                                                                    
 Running: 0                                                                                                                      
 Paused: 0                                                                                                                       
 Stopped: 1                                                                                                                      
Images: 1                                                                                                                        
Server Version: 18.06.1-ce                                                                                                       
Storage Driver: overlay2                                                                                                         
 Backing Filesystem: extfs                                                                                                       
 Supports d_type: true                                                                                                           
 Native Overlay Diff: true                                                                                                       
Logging Driver: json-file                                                                                                        
Cgroup Driver: cgroupfs                                                                                                          
Plugins:                                                                                                                         
 Volume: local                                                                                                                   
 Network: bridge host macvlan null overlay                                                                                       
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog                                                   
Swarm: inactive                                                                                                                  
Runtimes: runc                                                                                                                   
Default Runtime: runc                                                                                                            
Init Binary: docker-init                                                                                                         
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e                                                                     
runc version: 69663f0bd4b60df09991c08812a60108003fa340                                                                           
init version: fec3683                                                                                                            
Security Options:                                                                                                                
 seccomp                                                                                                                         
  Profile: default                                                                                                               
Kernel Version: 4.9.93-linuxkit-aufs                                                                                             
Operating System: Docker for Windows                                                                                             
OSType: linux                                                                                                                    
Architecture: x86_64                                                                                                             
CPUs: 2                                                                                                                          
Total Memory: 1.934GiB                                                                                                           
Name: linuxkit-00155d64ee13                                                                                                      
ID: KONG:TF4A:QR6H:Z3RV:JZBT:KAIB:RPSF:G6CW:OUB6:WHJW:NQL6:H6BY                                                                  
Docker Root Dir: /var/lib/docker                                                                                                 
Debug Mode (client): false                                                                                                       
Debug Mode (server): true                                                                                                        
 File Descriptors: 22                                                                                                            
 Goroutines: 46                                                                                                                  
 System Time: 2018-11-07T21:20:10.3548106Z                                                                                       
 EventsListeners: 1                                                                                                              
Registry: https://index.docker.io/v1/                                                                                            
Labels:                                                                                                                          
Experimental: false                                                                                                              
Insecure Registries:                                                                                                             
 127.0.0.0/8                                                                                                                     
Live Restore Enabled: false                                                                                                      
```

systeminfo:
	 
```
Host Name:                 -------------                                                                                         
OS Name:                   Microsoft Windows 10 Enterprise                                                                       
OS Version:                10.0.17134 N/A Build 17134                                                                            
OS Manufacturer:           Microsoft Corporation                                                                                 
OS Configuration:          Member Workstation                                                                                    
OS Build Type:             Multiprocessor Free                                                                                   
Product ID:                00329-00000-00003-AA856                                                                               
Original Install Date:     27/09/2018, 16:50:32                                                                                  
System Boot Time:          07/11/2018, 19:11:51                                                                                  
System Manufacturer:       LENOVO                                                                                                
System Model:              20HES4KF02                                                                                            
System Type:               x64-based PC                                                                                          
Processor(s):              1 Processor(s) Installed.                                                                             
                           [01]: Intel64 Family 6 Model 142 Stepping 9 GenuineIntel ~2611 Mhz                                    
BIOS Version:              LENOVO N1QET76W (1.51 ), 18/05/2018                                                                   
Windows Directory:         C:\WINDOWS                                                                                            
System Directory:          C:\WINDOWS\system32                                                                                   
Boot Device:               \Device\HarddiskVolume2                                                                               
System Locale:             pt-br;Portuguese (Brazil)                                                                             
Input Locale:              pt-br;Portuguese (Brazil)                                                                             
Time Zone:                 (UTC-03:00) Brasilia                                                                                  
Hotfix(s):                 3 Hotfix(s) Installed.                                                                                
                           [01]: KB4456655                                                                                       
                           [02]: KB4462930                                                                                       
                           [03]: KB4462919                                                                                                                                                      
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.                  
```

docker-compose --version: 

```
docker-compose version 1.23.1, build b02f1306
```
