### ISSUE TITLE
Support to override COMPOSE_PROJECT_NAME variable of running containers 

### ISSUE THREAD

**Issue by dbjpanda** [docker/compose#6256]
I have some setup where the project dir and container names changes frequently. But I don't want to down those containers at all.  I want to persist the containers and volumes as it is throughout the continuous  refactoring of the names.  e.g 

```
dir_a  > docker-compose up -d 
mv dir_a dir_b 
dir_b  > docker-compose -p dir_a up -d 
mv dir_b dir_c 
dir_c  > docker-compose -p dir_a up -d 
```

Everytime I rename a dir I need to provide the project name of the first dir name from where I had started the containers. But I want to provide the last dir name from which it recently renamed i.e dir_b . How can I override the project name of running containers. 

Infact how to change the com.docker.compose.project label of already started containers

**Comment by shin-** [comment]
Hi @dbjpanda 
Part of the idea of having containers is that they are immutable constructs. As a result, mutable labels is not a feature, nor should it be. If you find yourself changing your directory name frequently, maybe add a `COMPOSE_PROJECT_NAME` variable inside your `.env` file?
