### ISSUE TITLE
Nginx not redirecting?

### ISSUE THREAD

**Issue by oleersoy** [docker/compose#6258]
Hi,
I've [written up the issue on SO](https://stackoverflow.com/questions/52683662/nginx-reverse-proxy-not-redirecting).

## Summary 

The setup works when I'm not using docker compose.  In other words I create the network, build the nginx image manually, and run the containers manually.  When I try to automate everything with docker compose, it works, but it will not pass through a domain name that I can configured in `/etc/hosts`.  I provided curl examples in the SO post.

I also [filed in an issue with Nginx/docker](https://github.com/nginxinc/docker-nginx/issues/281)

**Comment by shin-** [comment]
Hi @oleersoy 

Please use the provided issue template. A StackOverflow question, no matter how detailed, is not a good substitute.
