### ISSUE TITLE
Env variable defaulting to blank string although I can see those variables already set in Docker inspect 

### ISSUE THREAD

**Issue by dbjpanda** [docker/compose#6259]
I executed command ` DOMAIN=example.com docker-compose up --no-start` . The container is created and **when I inspect the container I could see the env variable already set there**. Then later on when I executed `docker-compose start` it provided me the error that " defaulting to blank string" . When I executed `docker start container_name` the container started. Is it an intentional behaviour or any bug or I am doing something wrong ?

**Comment by shin-** [comment]
https://docs.docker.com/compose/environment-variables/

**Comment by dbjpanda** [comment]
@shin-  I can google that also. But I think you didn't read the issue carefully. I have .env file already.

**Comment by dbjpanda** [comment]
@shin-  I have mentioned it " when I inspect the container I could see the env variable already set there " . It means somehow the env variables are passed to container either from env file or by directly setting in docker-compose.yml. You should understand that. Sorry if I was not clear. By the way my question is if the env variable values are already set then why I need to pass the variable values again when I execute `docker-compose start` . Don't you think it should use the previously set variable values and if any new value is passed it should override only same behavior as `docker start container`

docker-compose inspect container_name
```
"Env": [
                "PROJECT_NAME=test",
                "DOMAIN=example.com",
                "DRUPAL_VERSION=8",
                "MYSQL_HOSTNAME=test.mariadb",
                "MYSQL_DATABASE=drupal",
                "MYSQL_USER=test",
                "MYSQL_PASSWORD=pass",
                "MYSQL_PORT=3306",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.14.0"
            ],

```

**Comment by shin-** [comment]
Variable interpolation is done every time the file is parsed and reads the environment on the host (as well as the `.env` file, if present). At that stage, Compose doesn't know that a container already exists, and is certainly not attempting to match that container's environment with the values it's trying to parse. 

As these messages are warnings, they're completely safe to ignore in your case, as the service definition is mostly irrelevant to the `start` subcommand.
