### ISSUE TITLE
docker-compose error.

### ISSUE THREAD

**Issue by pandyamarut** [docker/compose#6260]
when i'm Giving this cmd = docker-compose run web /bin/bash 
I'm getting the below mentioned error. 

ERROR: Cannot start service web: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

**Comment by shin-** [comment]
> `stat /bin/bash: no such file or directory`

It's pretty self-explanatory.
