### ISSUE TITLE
Top-level/standalone image build specification

### ISSUE THREAD

**Issue by DrPyser** [docker/compose#6264]
## Description of the issue

Is there any plan for/existing discussions around the idea of supporting a top-level `build` or `images` section to declare images to be built, independently of their use in any service?

Use cases might include:
* Specifying build options and ensuring the build of base images required by services
* Avoiding redundancy in service definitions when multiple services use the same image. This can currently be addressed by using a separate service block(with a dummy command override) to define the image build, and having other services using that image require that "build" service and specify only the image name. This is a non-ideal workaround.
* Using docker-compose simply as a tool for defining and orchestrating the build of docker images.

On that last use case, considering that `docker stack` seems to be going to replace docker-compose for the deployment and management of "services", but leaves out the problem of building the necessary images(specifying all options through a declarative configuration, along with build orchestration) to other tools, docker-compose could stay very useful as such a tool. In that optic, the orchestration and configuration of image builds would be done separately and independently from the orchestration and configuration of services, so it makes sense that they could be also specified separately and independently.

Thanks for your consideration.

**Comment by shin-** [comment]
Thanks for the suggestion @DrPyser ! Please note that our stance has generally been to keep image/build management out of Compose, and focus primarily on running applications. See e.g. https://github.com/docker/compose/issues/6148#issuecomment-414469013 , https://github.com/docker/compose/issues/6093#issuecomment-406375210

As a result, it's unlikely such a feature would make it into the Compose format as currently designed. It may however be implemented in an external tool that supports a Compose-based workflow. In particular, using [extension fields](https://docs.docker.com/compose/compose-file/#extension-fields) would allow such top-level declarations to exist in a way that would allow these files to still be compatible with `docker-compose` and `docker stack` if desired.

**Comment by DrPyser** [comment]
I see, thanks for the info. Do you have any suggestion for a (production-ready) tool that would be well suited for the use case of build management?
