### ISSUE TITLE
not able to setup docker.compose ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by nurrazamanjoy** [docker/compose#6266]
I was trying to install setup docker-compose 2.0 version but fail ubuntu 16.04 LTS 64 bit. is any one help to solve my problem?

**Comment by shin-** [comment]
Hi @nurrazamanjoy  ! We strive to be welcoming to newcomers, so here's a few things to keep in mind for the future as I close this:
- **GitHub is generally not for support**: as the issue template states, "This tracker should only be used to report bugs and request features / enhancements". Docker in particular uses their [forums](https://forums.docker.com) for community support.
- **Bug reports should be substantial**: if you believe what you're seeing is a bug, a good approach to getting the issue solved is to submit a report that has all the information required for the maintainer to reproduce the problem. That includes, but isn't limited to, the fields of the issue report you failed to fill out.
- **Make sure you're making your report in the right place**: In this case, you're reporting an issue with `apt-get` commands, but reporting it on the repository for the `docker-compose` tool.

Please go through these steps in the future. Open-source maintainers, many of whom are volunteers, will feel like you're respecting their time and be more willing to help you.
