### ISSUE TITLE
Files cannot be received on my Windows machine through docker

### ISSUE THREAD

**Issue by wangjiyu92** [docker/compose#6267]
## Description of the issue
I am using docker on windows and trying to copy the results to my machine. However, when I input 'make run' command in windows cmd, there is no error report but the files I expected to have does not appear in the target folder as well. The code is attached, I planned to get the file in C:\\Result. Thanks!
## Context information (for bug reports)
IMG_NAME=test

COMMAND_RUN=docker run \\
	  --name test \\
	  --detach=false \\
	  -e DISPLAY=${DISPLAY} \\
	  -v /tmp/.X11-unix:/tmp/.X11-unix \\
	  --rm \\
	  -v "/c/Result":/mnt/shared/ \\
	  -i \\
          -t \\
	  ${IMG_NAME} /bin/bash -c

build:
	docker build --network host --no-cache --rm -t ${IMG_NAME} .
 
remove-image:
	docker rmi ${IMG_NAME}

run:
	$(COMMAND_RUN) \\
            "cd /mnt/shared/testcase && python run.py && exit"

**Comment by shin-** [comment]
Hi @wangjiyu92 ! We strive to be welcoming to newcomers, so here's a few things to keep in mind for the future as I close this:
- **GitHub is generally not for support**: as the issue template states, "This tracker should only be used to report bugs and request features / enhancements". Docker in particular uses their [forums](https://forums.docker.com) for community support.
- **Bug reports should be substantial**: if you believe what you're seeing is a bug, a good approach to getting the issue solved is to submit a report that has all the information required for the maintainer to reproduce the problem. That includes, but isn't limited to, the fields of the issue report you failed to fill out.
- **Make sure you're making your report in the right place**: In this case, you're reporting an issue with `docker` commands, but reporting it on the repository for the `docker-compose` tool.

Please go through these steps in the future. Open-source maintainers, many of whom are volunteers, will feel like you're respecting their time and be more willing to help you.
