### ISSUE TITLE
Docker's container with --net=host is not reachable from the network

### ISSUE THREAD

**Issue by mksoi** [docker/compose#6272]
I am working on a project hosted on **Docker for Windows** using the following configuration:  
Host (**PC1**) Physical IP: **145.118.70.40** on **LAN**  
Host Virtual IP: **10.0.75.1** on **DockerNAT**

I got the following **issue**:  
A container X (**docker run --name X -it --net=host webserver 8080**) is able to access the host using the domain name **host.docker.internal**. If X pings this domain name, it gets the reply from **192.168.65.2**. However, in the host, there is no such network! The host cannot even ping X using any of this IP range. X is accessible from the host using **DockerNAT** network and particularly by IP: **10.0.75.2**. It seems there is a bridge or NAT rule that maps **192.168.65.0** to **10.0.75.0**. Using this bridge, X can access the host (via **192.168.65.2**) and host can access X (via **10.0.75.2**). So far no issue. The issue appears when we try to access X from another physical machine (**PC2**) whose IP= **145.118.70.41** on the host's LAN. A link such as http://145.118.70.40:8080 is supposed to work on **PC2**, but it does not. If there is another container Y (**docker run -it -p 7000:8080 webserver 8080**) running on the same host (**PC1**) along with X (notice that there is no **--net=host** option used for Y), Y is accessible from **PC2** using http://145.118.70.40:7000. My question is: How to make X also accessible from **PC2** using the host's IP address (just like Y) while keeping the **--net=host** option?  

Thank you.

**Comment by shin-** [comment]
Hi @mksoi  ! We strive to be welcoming to newcomers, so here's a few things to keep in mind for the future as I close this:
- **GitHub is generally not for support**: as the issue template states, "This tracker should only be used to report bugs and request features / enhancements". Docker in particular uses their [forums](https://forums.docker.com) for community support.
- **Bug reports should be substantial**: if you believe what you're seeing is a bug, a good approach to getting the issue solved is to submit a report that has all the information required for the maintainer to reproduce the problem. That includes, but isn't limited to, the fields of the issue report you failed to fill out.
- **Make sure you're making your report in the right place**: In this case, you're reporting an issue with `docker` commands, but reporting it on the repository for the `docker-compose` tool.

Please go through these steps in the future. Open-source maintainers, many of whom are volunteers, will feel like you're respecting their time and be more willing to help you.
