### ISSUE TITLE
Way to restrict access from internet to containers ports on remote linux server?

### ISSUE THREAD

**Issue by triesa** [docker/compose#6274]
I use docker-compose on ubuntu 18 on remote server. How, with iptables, can i block access from the internet to the docker port and only allow access to it from the localhost of this server?

For instance, i want to block 4150 port for internet. Trying this: iptables -A DOCKER-USER -p tcp --dport 4150 -j DROP does not block the port - still can access to it from the internet (not from server machine).

How can i block access from internet to all ports that are on the server, but allow only 22,80 ? And keep that ports available from localhost of the server (eg from the server itself) ?

Is there any flag to docker-compose, that i can set for hide that ports from internet?

**Comment by shin-** [comment]
Hi @triesa ! We strive to be welcoming to newcomers, so here's a few things to keep in mind for the future as I close this:
- **GitHub is generally not for support**: as the issue template states, "This tracker should only be used to report bugs and request features / enhancements". Docker in particular uses their [forums](https://forums.docker.com) for community support.
- **Bug reports should be substantial**: if you believe what you're seeing is a bug, a good approach to getting the issue solved is to submit a report that has all the information required for the maintainer to reproduce the problem. That includes, but isn't limited to, the fields of the issue report you failed to fill out.

Please go through these steps in the future. Open-source maintainers, many of whom are volunteers, will feel like you're respecting their time and be more willing to help you.
