### ISSUE TITLE
Error relocating /usr/lib/libpython3.6m.so.1.0

### ISSUE THREAD

**Issue by babonet13** [docker/compose#6292]
Hi Team,

I have installed docker 
dev-box:/HelloWorld$ docker --version
Docker version 18.06.1-ce, build d72f525745

under a fresh Alpine 3.8.1. install

and then I have installed docker-compose ...
... but when I want to use it I got this error 👍 

dev-box:/HelloWorld$ docker-compose                                                                                                      
**Error relocating /usr/lib/libpython3.6m.so.1.0: getrandom: symbol not found**

What does it mean ? And how to solve it ?

Best Regards

Bernard

**Comment by jrabbit** [comment]
do you have python installed?

**Comment by babonet13** [comment]
I have this : 
dev-box:/HelloWorld$ python --version
Python 2.7.15

And when I'm trying to install python3, I got that : 
dev-box:/HelloWorld$ sudo apk add python3                                                                                                
OK: 827 MiB in 188 packages    

>> I'm not sure to have the good version

**Comment by jrabbit** [comment]
Is there an alpine utility to check if you have a package installing libpython3.6m.so.1.0?

**Comment by babonet13** [comment]
If I use the "whereis" command, this librairie seems to be already installed !!!

dev-box:~$ whereis libpython
libpython: /usr/lib/libpython3.so

**Comment by babonet13** [comment]
dev-box:~$ whereis libpython3.6m.so.1.0                                                                                                  
libpython3.6m.so.1: /usr/lib/libpython3.6m.so.1.0

**Comment by jrabbit** [comment]
ok maybe you have a stripped down version of that python can you get a full install maybe? i'm not positive that's it tho

**Comment by babonet13** [comment]
I could solve this error by removing python and re-installing python3 on my VM ... I will try to reproduce this on my "real" machine. 
Thanks for help

**Comment by sphrak** [comment]
@nicbou I found myself with the same issue. Did you manage to solve it?

**Comment by babonet13** [comment]
Yes, but only by a whole fresh new installation of Docker (using the manual mode) : 
https://github.com/babonet13/HelloWorld/tree/master/App/docker

**Comment by stieg** [comment]
So what happened here is that the `getrandom` symbol has been moved into /lib/libc.musl-x86_64.so.1 which /usr/lib/libpython3.6m.so.1.0 depends on.  You are getting this because you have a newer version of libpython3.6 that no longer implements this symbol and expects libc.musl to implement it, but the version of libc.musl does not have it implemented.  Solution is to simply upgrade libc.musl to latest version and the symbol is implemented there.  HTH
