### ISSUE TITLE
docker compose tries to load non existing python36.dll from %temp% + related applocker issues

### ISSUE THREAD

**Issue by tprasadtp** [docker/compose#6323]
docker-compose tries to load python36.dll from %temp%. It causes issues.
running `docker-compose` returns,
```
Error loading Python DLL 'C:\Users\<USER>\AppData\Local\Temp\_MEI19762\python36.dll'.
LoadLibrary: This program is blocked by group policy. For more information, contact your system administrator.
```
- There is no such file at %temp%\<folder/>\
- I already have python installed and is available in the path.
- If applocker policies are enforced it fails as %temp% is not white-listed.

Possibly related to #5834

## Context information 

docker-compose version 1.22.0 (I have also tried with 1.20, 1.21 and 1.19 issue is the same. Only difference is in case of 1.19 it fails to load python27.dll. It still tries to load from temp.) 
docker 18.06.1-ce

## Steps to reproduce the issue

1. Run docker-compose
Every command fails.

### Observed result
Fails to run with error.

OS version 
Windows 10 1803 64 Bit

**Comment by shin-** [comment]
Hi @tprasadtp 

The `docker-compose` binary is a self-extracting archive, as described [here](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#how-the-one-file-program-works). It is normal and expected that it would attempt to create files in your temporary directory which will disappear when the program exits (this explains why you won't see this file if you go look for it afterwards). If your security policies are written in such a way that prevent access to the temp directory, then `docker-compose` will not be able to function properly.

We do not consider this to be a bug. You'll need to configure Applocker appropriately to allow `docker-compose.exe` access to your temp directory.

**Comment by shin-** [comment]
No, the `python36.dll` library isn't signed by Docker. `pip` might indeed work better for your usecase!
