### ISSUE TITLE
Update jsonschema dependency

### ISSUE THREAD

**Issue by goodspark** [docker/compose#6347]
**Is your feature request related to a problem? Please describe.**
I'm trying to install [poetry](https://github.com/sdispater/poetry) and `docker-compose` in a virtualenv but since they depend on different [jsonschema](https://github.com/Julian/jsonschema/blob/master/CHANGELOG.rst) major versions they become incompatible when running together in the venv.

- `poetry`: [`>=3, <4`](https://github.com/sdispater/poetry/blob/master/pyproject.toml#L30)
- `docker-compose`: [`>=2.5.1, <3`](https://github.com/docker/compose/blob/master/setup.py#L42)

**Describe the solution you'd like**
`docker-compose` to update its `jsonschema` dependency to `>=3, <4`.

**Describe alternatives you've considered**
I could just put the two in different venvs. I'm lazy and just want all my tools available in a single venv so I don't have to hop around so much.

**Comment by shin-** [comment]
Looks like version 3.0.0 of `jsonschema` is still in alpha. We'll definitely want to wait for a stable release before we consider this change, and measure what changes are required in our codebase to work with the new version.
I'm happy to put this on my radar, but I don't expect this to be resolved for some time still. As an alternative, you may want to try using the [Compose binary](https://github.com/docker/compose/releases) instead.

**Comment by goodspark** [comment]
Cool. Thanks! Defer to you what you want to do with this specific issue until then.

**Comment by chrislan815** [comment]
Version 3.0.0 of jsonschema is not in alpha anymore -- do we have plan on moving to v3.0.0?

**Comment by lsterk** [comment]
@shin- any updates on this? According to https://github.com/Julian/jsonschema , {{jsonschema==3.0.1}} is a stable release (since March 1).

This issue makes it difficult to bundle {{docker-compose}} in a library due to the strict pin on a package that is now starting to be adopted in other libraries.

**Comment by shin-** [comment]
@lsterk I'm no longer a maintainer, but the best way to get the ball rolling on this is probably to make a PR for it.
