### ISSUE TITLE
Github repo builds not working on windows

### ISSUE THREAD

**Issue by oysteiae** [docker/compose#6354]
## Description of the issue
https://github.com/docker/compose/commit/96a49a02534d5bd58f8adcbd4148076d463afea9#r31367442

This breaks url builds. Eg. if you want to build from a github repo in docker compose on windows.
A fix would be to change the if check to check for urls:
```
if IS_WINDOWS_PLATFORM and not path.startswith(WINDOWS_LONGPATH_PREFIX) and not "://" in path:
     path = WINDOWS_LONGPATH_PREFIX + os.path.normpath(path)
```

A more sophisticated way of checking for urls would perhaps be needed.

**Comment by shin-** [comment]
Thanks for the report!
