### ISSUE TITLE
Volumes lost if container fails to start

### ISSUE THREAD

**Issue by buckett** [docker/compose#637]
If you have a container using volumes persisted between restarts (eg a MySQL container and /var/lib/mysql) if the container fails to restart the volumes get wiped out when the container does start up.

To reproduce this, create a `fig.yml` containing:
```
app:
  image: ubuntu
  ports:
   - "6543:6543"
  volumes:
   - /opt
  command: ["/bin/bash",  "-c",  "/bin/cat </opt/last ; /bin/date > /opt/last"]
```

When this container runs it attempts to read the date when container was last run and and the write todays date back to the file. I have a mapped port as it's an easy way to stop the container from starting. The first time this is run you see:
```
$ fig up
Creating bug_app_1...
Attaching to bug_app_1
app_1 | /bin/bash: /opt/last: No such file or directory
bug_app_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
```
which is expected, if you then run it again you see the date when it was last run (as the /opt volume is persisted:
```
$ fig up
Recreating bug_app_1...
Attaching to bug_app_1
app_1 | Sat Nov  8 07:20:03 UTC 2014
bug_app_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
```
If you now start another container with also wants port 6543 and leave it running in another terminal:
```
docker run -p 6543:6543 --rm -it ubuntu
```
and attempt to startup the fig managed container again it fails:
```
$ fig up
Recreating bug_app_1...
Cannot start container fabfd220db3d728213ad6bc410f737ccccbf8414284aad5e27ebdc8cc97f91fe: Bind for 0.0.0.0:6543 failed: port is already allocated
```
If you now stop the docker container (to release the port) and restart the fig managed container the /opt volume is empty:
```
$ fig up
Recreating bug_app_1...
Attaching to bug_app_1
app_1 | /bin/bash: /opt/last: No such file or directory
bug_app_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
```
I would have expected it to still have the /opt volume from the previous runs.

**Comment by SamMorrowDrums** [comment]
I  had a datavolume for postgress and mongo, and after this failure:

```
Starting BrainsApp_DATAVOLUME_1...
Cannot start container 5c721dbb615b5f52afc6f99bbbd5ef2d9c019269f3ce9d385f8df2c2417eeee1: fork/exec /var/lib/docker/init/dockerinit-1.0.1: cannot allocate memory
```

When I restarted the machine `fig start` wouldn't work, so I ran `fig build` and lost everything. Tried re-attaching old containers, but nothing seemed to work.

It strikes me that whatever failure handling is needed, this situation is incredibly high risk, and made me question using Fig with Docker at all for persistent data.

Failure recovery, where data has not actually been corrupted, should not lose, or allow you to destroy your data without warning or prompt. That's too dangerous for production apps to accept as a risk. I know backup is necessary, but this is different, this should not be an emergency run the backup recovery script situation.

Let me know if anyone knows how to handle this please.

**Comment by aanand** [comment]
@SamMorrowDrums What do you mean you "lost everything"? `fig build` doesn't touch containers, it just builds images.

**Comment by SamMorrowDrums** [comment]
Sorry, I ran fig up -d after fig build.

After that I was unable to find the orphaned container. I couldn't find an existing data volume that contained the database files.

**Comment by aanand** [comment]
We definitely need a container recreate process that's resilient to machine failure at every step. The weakness right now is that we don't keep track of the intermediate container except in memory, so if we fail between deleting the old container and creating the new one, we'll lose data.

We'll need to keep this in mind alongside plans to switch to using renaming (#874) or labels (https://github.com/docker/docker/pull/9882).

**Comment by Starefossen** [comment]
Yes, please. I too have had volumes disappear when Docker fails to build.

**Comment by ohord** [comment]
We also ran into this problem. After power-off application failed to load, everything was lost.... It seems that docker is still not production ready!

**Comment by funkyfuture** [comment]
@aanand Is someone already working on that? Respectively on #874?
Otherwise i might give it a try.

This behaviour can really be a p.i.t.a. and should be fixed with the next release, me thinks.

**Comment by aanand** [comment]
@funkyfuture It's not currently being worked on, no. #874 is one approach, but an even better one would be to stop relying on names entirely and use container metadata - see docker/docker#9882, which is coming along nicely.

**Comment by dnephin** [comment]
This issue is really old, and we've implemented renaming and a significant change to volume re-use since then. I'm pretty sure we've fixed this issue, so I'm going to close it.
