### ISSUE TITLE
overlay network , can i specified fix-ip in docker-compose.yml  

### ISSUE THREAD

**Issue by Mrchenli** [docker/compose#6383]
here is my compose file , task up but it's ip not what i specified  ( '10.0.10.11{{.Task.Slot}}')
version: '3.3'
services:
  redis-cluster:
    hostname: 'redis-{{.Task.Slot}}'
    deploy:
      mode: replicated
      replicas: 6
      restart_policy:
        condition: on-failure
    image:  kiibos/redis-cls:1.0.0
    volumes:
      - redisVol:/data
    container_name: redis-cluster
    networks:
      demo:
        ipv4_address: '10.0.10.11{{.Task.Slot}}'
volumes:
  redisVol:
    external:
      name: '{{index .Service.Labels "com.docker.stack.namespace"}}_redisVol-{{.Task.Slot}}'
networks:
  demo:
    external:
      name: redis-cluster

**Comment by shin-** [comment]
Hi @Mrchenli 

Unfortunately, your report isn't properly formatted and missing key information. Please use the [issue template](https://raw.githubusercontent.com/docker/compose/master/.github/ISSUE_TEMPLATE/bug_report.md) provided to update your report or we won't be able to help.
