### ISSUE TITLE
docker-compose restart 

### ISSUE THREAD

**Issue by jithinpjames** [docker/compose#6384]
I have 9 containers defined inside a docker-compose file. While coding, i need to bring 1 container down and restart it. 
docker-compose restart works for me, but the port is not exposed. 
I mean, the container gets restarted and we can see that its up and running and we can get inside the container too. However the API calls to the container doesn't work because the port is not exposed/up.

**Comment by shin-** [comment]
Hi @jithinpjames 

Unfortunately, your report isn't properly formatted and missing key information. Please use the [issue template](https://raw.githubusercontent.com/docker/compose/master/.github/ISSUE_TEMPLATE/bug_report.md) provided to update your report or we won't be able to help.
