### ISSUE TITLE
Missing changelog entries

### ISSUE THREAD

**Issue by adamchainz** [docker/compose#6386]
## Description of the issue

This seems to be a repeat of #5871 . There's a version 1.23.2 on PyPI but the changelog was last updated for 1.23.0: https://github.com/docker/compose/blob/master/CHANGELOG.md

This is not reassuring - both from an upgrade perspective (I want to be sure the new version won't need changes on my codebase) and security (is the new version legitimate?).

## Context information (for bug reports)

N/A

## Steps to reproduce the issue

1. See new version on PyPI
2. Not see changelog entry

### Observed result

Missing versions in changelog

### Expected result

Every version in changelog

### Stacktrace / full error message

N/A

## Additional information

N/A

**Comment by shin-** [comment]
The Changelog on master is a bit behind sometimes, but the one on the `release` branch will always be up to date: https://github.com/docker/compose/blob/release/CHANGELOG.md

You can also refer to the official releases page: https://github.com/docker/compose/releases

**Comment by adamchainz** [comment]
Ah okay, different branching strategy. It would be nice to have an obvious link in the README and even on PyPI (through `project_urls` - https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls ). I read the changelog on every package upgrade I do, and I'm sure others do too :)

**Comment by shin-** [comment]
Yup, that's fair - our `setup.py` could absolutely use a overhaul.

**Comment by adamchainz** [comment]
🚅 Thanks! 💨
