### ISSUE TITLE
Environment Variable Resolution?

### ISSUE THREAD

**Issue by sherzberg** [docker/compose#64]
I'd like to not change any of my env variable code in my app and be able to do something like this:

``` bash
web:
  build: .
  ports:
   - 8000:8000
  links:
   - db
  environment:
   DATABASE_URL: mysql://user:password@${DB_1_PORT_3306_TCP_ADDR}/db
db:
  image: orchardup/mysql
```

Is there a way to do this currently with the linked ports? If not, is there any interest in this? I'd like to implement it there is a second person that would find it useful.

**Comment by pnegahdar** [comment]
@aanand I don't think this was actually close by #297, the issue in question here is reassigning autoassigned env vars to another env var (like one the codebase already expects).

**Comment by jamestenglish** [comment]
@aanand I agree with @pnegahdar the original use case:

    web:
      build: .
      ports:
       - 8000:8000
      links:
       - db
      environment:
       DATABASE_URL: mysql://user:password@${DB_1_PORT_3306_TCP_ADDR}/db
    db:
      image: orchardup/mysql

Does not seem to be supported by #297

specifically how would one be able to set an environment variable based on other environment variables like this line: `DATABASE_URL: mysql://user:password@${DB_1_PORT_3306_TCP_ADDR}/db`

I think this is an important use case as apps should not have to be burdened with changing code to support esoteric environment variable names like: `DB_1_PORT_3306_TCP_ADDR`

**Comment by aanand** [comment]
@jamestenglish That would be cool, but the environment variables added by links are pretty unnecessary anyway, since:

1. An entry is added to `/etc/hosts` with the name of the link (in this case, `db`)
2. The port given to `web` will always be the one exposed by `db`, (in this case, 3306).

(This is why we no longer recommend [using the environment variables provided by links](http://docs.docker.com/compose/env/).)

You can therefore just write:

```yaml
environment:
  DATABASE_URL: mysql://user:password@db:3306/db
```

**Comment by jamestenglish** [comment]
@aanand Ah thanks, I had been out of the docker world for a little bit and didn't realize they added that feature

**Comment by dimroc** [comment]
Thanks a lot @aanand, your approach is perfect.

**Comment by kelvv** [comment]
@aanand Thank you , perfect
