### ISSUE TITLE
Getting an Error when try to expose ports: 

### ISSUE THREAD

**Issue by muedd** [docker/compose#6402]
```
PS D:\source\Learning-repo> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS D:\source\Learning-repo> docker run --detach --publish 80:80 nginx:alpine
cc70c06980aa7ec3b77dede971e91f57e8b896d08768445a79a1e05cba4c1b71
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint sad_tu (f56eb2406bce1a2dab2b4014459e26db001c8c0c004f34a7e9b76aafa1f16fb1): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:80:tcp:172.17.0.2:80: input/output error.
PS D:\source\Learning-repo>
```
## Description of the issue
I am using docker for windows and did not have this problem of connectivity driver, until I updated to 👍 I have tried changing the ports to different ports and even kill all other containers. I am 100% sure that the port are not in use by the host machine but the problem don't got away. 

Output of "docker version"
```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by shin-** [comment]
Hi @muedd ! We strive to be welcoming to newcomers, so here's a few things to keep in mind for the future as I close this:
- **GitHub is generally not for support**: as the issue template states, "This tracker should only be used to report bugs and request features / enhancements". Docker in particular uses their [forums](https://forums.docker.com) for community support.
- **Bug reports should be substantial**: if you believe what you're seeing is a bug, a good approach to getting the issue solved is to submit a report that has all the information required for the maintainer to reproduce the problem. That includes, but isn't limited to, the fields of the issue report you failed to fill out.
- **Make sure you're making your report in the right place**: In this case, you're reporting an issue with `docker` commands, but reporting it on the repository for the `docker-compose` tool.

Please go through these steps in the future. Open-source maintainers, many of whom are volunteers, will feel like you're respecting their time and be more willing to help you.
