### ISSUE TITLE
Add `verify` command

### ISSUE THREAD

**Issue by trajano** [docker/compose#6408]
**Is your feature request related to a problem? Please describe.**

For CI, it would be good to verify that the docker-compose would work correctly.

**Describe the solution you'd like**

When I do `docker-compose verify` it does the same thing as `docker-compose up` and waits for the `healthcheck` to pass for all the services.  Once it passes, it runs `docker-compose down` to tear down the app.

Some other parameters to consider are:

* `--build` force a build even if it is not needed
* `--limit=60s` time limit before giving up on health checks to pass
* `--keep-up` keeps the services up after verifying.  This allows more complex integration tests to be executed after the healthchecks are up.

**Describe alternatives you've considered**

We create a separate test application that waits for the stack to come up and run our tests.

**Comment by shin-** [comment]
Thanks for the suggestion @trajano !

The way I look at it, this seems like a very specific scenario you want to introduce as a mainline command. I'd assume users would have wildly differing expectations of what a `verify` command would do and how it should behave, and as a result, I don't think it would be wise for us to attempt to introduce a solution to "application checking" that would only ever satisfy a small portion of our users. It also seems a bit out of scope for Compose. 

Note that the [`docker-compose events`](https://docs.docker.com/compose/reference/events/) command will inform you once a service becomes healthy, which can help you write a script or a program to do what you describe.

**Comment by trajano** [comment]
NP we already have the "tests" for the Java apps using testcontainers.  However, for something simple I'd rather avoid all the harness that is needed.

But I'd rather see if there's any interest on this from other members before we just close it much like https://github.com/json-schema-org/json-schema-spec/issues/396 generated a lot of interest.
