### ISSUE TITLE
--tlsverify=false does not work

### ISSUE THREAD

**Issue by kutschkem** [docker/compose#6412]
## Description of the issue
`docker-compose --tlsverify=false build` returns the help text. I also tried `docker-compose --tlsverify false build` but this only tried to parse `false` as option.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.20.1, build 5d8c71b2
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

**Output of `docker version`**
```
Client:         18.03.0-ce
 API version:   go1.9.4
 Git comFri Mar 23 08:31:36 2018
 OS/Arch:       falsews/amd64
 Orchestrator:  swarm

Server: Docker Engine - Community
 Engine:        18.09.0
  API version:  go1.10.4nimum version 1.12)
  Git commit:   Wed Nov  7 00:52:55 2018
  OS/Arch:      false/amd64
  Experimental:
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
irrelevant
```

## Steps to reproduce the issue

1. call `docker-compose --tlsverify=false build`
2. ???
3. Profit

### Observed result

Help text is displayed

### Expected result
same as `docker --tlsverify=false <command>`

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Windows 7, Docker Tooling for Windows

**Comment by shin-** [comment]
Hi @kutschkem 

Thanks for the report! This is behaving as expected. The command-line parser we've chosen to use doesn't accept the `--flag=value` format for boolean flags (which is more of a Go-world idiom, hence why it is accepted by the Docker CLI for example). 
If you wish to disable `tlsverify`, you may simply omit the flag altogether.

**Comment by kutschkem** [comment]
That is not helpful, as just calling `docker-compose build` without the flag does, in fact, do the verification. No amount of changing or unsetting the DOCKER_TLS_VERIFY environment variable changed anything about that.

**Comment by shin-** [comment]
> That is not helpful, 

Sorry to hear.

> as just calling `docker-compose build` without the flag does, in fact, do the verification. 

What indicates to you that the verification is done? What error message do you see?

> No amount of changing or unsetting the DOCKER_TLS_VERIFY environment variable changed anything about that.

What values for `DOCKER_TLS_VERIFY` did you try setting?

**Comment by kutschkem** [comment]
I tried with DOCKER_TLS_VERIFY = 1, = 0, and unset.

**Comment by nfacciolo** [comment]
`DOCKER_TLS_CERTDIR=""` worked for me
