### ISSUE TITLE
Add --net to docker-compose run

### ISSUE THREAD

**Issue by yajo** [docker/compose#6414]
**Is your feature request related to a problem? Please describe.**
I use private networks for test and devel environments, where I want to inhibit external network connections except for some specific whitelisted hosts, by using the technique and image explained [here](https://github.com/Tecnativa/docker-whitelist#example).

It works safely and pretty well for those environments, but sometimes I still need to run some network-enabled commands, and there's no straight-forward solution.

**Describe the solution you'd like**
I'd love to be able to bind the container to networks when booting a new one with `run`, something like:

```bash
docker-compose run --rm --net public service command-that-requires-network-access
```

**Describe alternatives you've considered**
One is to define a specific `docker-compose.yml` file that is used only for those purposes, where the specific service is attached to the public network, although it is uncomfortable to maintain all of that code for such a specific and unusual task.

I end up doing:

1. `docker-compose down` to destroy networks
1. Edit `docker-compose.yml` and add the container I'm going to run to the public network.
1. `docker-compose run --rm service command-that-requires-network-access`
1. When finished, repeat step 1 and undo step 2

**Comment by shin-** [comment]
Thanks for the suggestion @Yajo 

I think this has merit. There's some technical wrinkles we'd need to iron, e.g. does it add to the list of networks in the service definition or replace them entirely? Should you be able to specify options like aliases or IP address, and what would that look like on the CLI? 

FWIW, the way I'd work around this with current Compose would be to write a `public-networks.yml` file with just the additional network definition for each service, and run with `-f docker-compose.yml -f public-networks.yml` when needed. It's minimal maintenance and probably less tedious than the process you describe.

**Comment by Yajo** [comment]
Usually those kind of flags append to the current defined list. For instance, `-v /host:/guest` adds a new volume to the list of already-defined volumes, so I guess that for consistency, it should be an added network. You could name the flag `--net-add`, just in case you want to be explicit and leave room for possible future enhancements.

Maybe that flag can support either just a name, or a json/yaml input with all details. Example:

```sh
# Just add container to network, with defaults
docker-compose run --net-add public service command-that-requires-network-access
# Allow extra configuration
docker-compose run --net-add '{"name": "public", "aliases": ["a","b"]}' service command-that-requires-network-access
```

Just some ideas :blush:

**Comment by Yajo** [comment]
I'm thinking in annother idea: Just `--net public`.

It should add `public` to the list of networks, and in such case, a public network should exist in the `docker-compose.yml` file, so you can define it there with all of its configurations, and the `run` command only attaches the container to that additional network.
