### ISSUE TITLE
How to control startup order in Compose?

### ISSUE THREAD

**Issue by whd-mtt** [docker/compose#6420]
Recently, I was leveraged spring boot and spring cloud to create  those micro services including eureka server,config server  and other applications  in our company, and each of  micro service built a stand docker image, In the process of container startup, It took about 10 minutes or even more for all the applications to fully launch, I think it is a much uncontrollable thing for project deployment team when deploying the project in a new environment, since I don't know what happened in the startup process, so I hope some of them to start in a certain order, It can effectively reduce startup time (ps : via  docker swarm to manage our containers) , for example, the config server can only be started if  the eureka server  started fully and its service is available, and [ the official tutorial](https://docs.docker.com/compose/startup-order/) provide an approach to resolve it, However, after my verification,it not working in docker version 3, Can you please tell me what should I do or some valuable advice?

**Comment by shin-** [comment]
Hi @whd-mtt 

This is a bug tracker. You will want to use our [forums](https://forums.docker.com) instead for questions such as this one.

**Comment by whd-mtt** [comment]
@shin- got it
