### ISSUE TITLE
Add support for :z and :Z to change SELinux labels on the fly

### ISSUE THREAD

**Issue by Yajo** [docker/compose#643]
When I first run a fig with a volume mounted, it usually fails because of SELinux context.

The fix is to run this:

    chcon -Rt svirt_sandbox_file_t ./something

Would be nice to have that automated in `fig.yml`, to ensure SELinux never disturbs development:

    app:
        build: .
        volumes:
            - ./something:/mountpoint
            - other:/other:ro
        chcon:
            - ./something: svirt_sandbox_file_t

**Comment by Yajo** [comment]
Maybe just adding [support for :z and :Z](https://github.com/docker/docker/pull/5910) should be enough.

**Comment by Yajo** [comment]
This happens because of this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1230098

**Comment by thaJeztah** [comment]
As of Docker 1.7, the `:Z` and `:z` options are implemented (see pull-request https://github.com/docker/docker/pull/12572), so it would make sense to add support for this in docker-compose as well.

@aanand @bfirsh should this be added to https://github.com/docker/compose/issues/363 ?

**Comment by aanand** [comment]
Support for volume modes other than `rw` and `ro` is tracked in #1493 and implemented in #1515 (which had fallen behind, but I've just rebased it).

**Comment by thaJeztah** [comment]
Thanks @aanand. Think this can be closed now that #1515 is merged

**Comment by x-yuri** [comment]
This doesn't seem to be [documented][a].

[a]: https://www.quora.com/As-a-software-developer-engineer-what-technologies-do-you-feel-are-a-waste-of-time-learning-Why/answer/Fred-Mitchell-5
