### ISSUE TITLE
"docker-compose --verbose exec app buffalo test" exited with 137

### ISSUE THREAD

**Issue by pzhao5** [docker/compose#6432]
Background: I am using golang with Buffalo framework to build Http service.

Try to run this in Travis-CI with 7GB while only 5GB of Memory was used. (Which 1GB allocated for the system and 4 GB for Docker in my investigation).

I was trying to 1) Pump up the Docker memory from 4GB to 5GB if that help, I searched for a while. I can't figure out a way to bump it up. Maybe anyone can help on here.
I am using docker-composer.yml version 3. Try with deploy flag on my service, and it won't work as expected since it was not run with swarm?

2) Try to understand why it would exit as 137 error code. Which currently, I have put --verbose, but it does not have enough information for me to understand why.

Anyone who can help, I will be greatly appreciated.

**Comment by pzhao5** [comment]
Running locally, this seems fine without any 137 error code.

**Comment by shin-** [comment]
Hi @pzhao5 

As stated in the issue template,

> 1. This tracker should only be used to report bugs and request features / enhancements to docker-compose
>    - **For questions and general support, use https://forums.docker.com**
>    - For documentation issues, use https://github.com/docker/docker.github.io
>    - For issues with the `docker stack` commands and the version 3 of the Compose file, use
      https://github.com/docker/cli

Please observe the aforementioned.
