### ISSUE TITLE
Logs are inconsistent about container names

### ISSUE THREAD

**Issue by pauldraper** [docker/compose#6442]
## Description of the issue

docker-compose log output shows the name of the container. This is helpful for debugging.

However, docker-compose is not consistent about this.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

**Output of `docker version`**
```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```yml
version: '2.4'
services:
  foo:
    command: ['sleep', 'infinity']
    container_name: baz_foo
    image: ubuntu:18.04
    init: true
```

## Steps to reproduce the issue

1. Run `docker-compose up` when the current directory's name is bar.
2. Run `docker-compose up` when the current directory's name is baz.

### Observed result

In the first case, the logs show `baz_foo`.

In the second case, the logs show `foo_1`.

### Expected result

In both cases, the logs show the container's name: `baz_foo`.

### Stacktrace / full error message

N/A

## Additional information

N/A

**Comment by thaJeztah** [comment]
Are you seeing the same issue on the current docker-compose release (1.23.2 https://github.com/docker/compose/releases/tag/1.23.2) ?

**Comment by pauldraper** [comment]
Yes.

```
docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by shin-** [comment]
Yeah, our algorithm naively assumes that any name that starts with `<projectname>_` is generated and thus elides it in the logs. We probably need a better way of detecting if a container has a custom name.

**Comment by thaJeztah** [comment]
oh! I see it now, yes, got it 👍
