### ISSUE TITLE
Allow running up without binding on ports.

### ISSUE THREAD

**Issue by pauldraper** [docker/compose#6443]
**Is your feature request related to a problem? Please describe.**

Sometimes, I need to run multiple stacks for testing in parallel.

However, containers fail to launch if published ports conflict.

**Describe the solution you'd like**

I'd like `docker-compose up` to be able to run without publish ports. A `--service-ports=false` option.

**Describe alternatives you've considered**

I've considered using docker run, however it has other differences that make it not work, like not giving it a hostname on the network.

I've considered using `extends`, but that doesn't work with `depends_on` (https://github.com/docker/compose/issues/3220).

I've considered using YAML anchors but that still more verbose that I'd prefer for something as simple as choosing whether to publish ports or not.

I've considered removing ports with a override file, but that can't be done https://github.com/docker/compose/issues/3729

I've considered adding ports with a `docker-compose.override.yml` but I prefer that to be reserved for per-user edits, and I prefer to keep vanilla docker-compose working well.

**Additional context**

`docker-compose run` already has the `--service-ports` flag.

**Comment by ulyssessouza** [comment]
I would consider using [docker-app](https://github.com/docker/app).
More specifically, `docker-app render --set` option so you can replace fixed port by a variable, then you just have to run each of your stacks with different values.
