### ISSUE TITLE
v3 without volumes_from no longer possible to access all volumes from an external container

### ISSUE THREAD

**Issue by simonvanderveldt** [docker/compose#6465]
We have a container running which is not started with compose which uses/defines several volumes.
With compose v2 we are able to easily use these volumes without knowing (or duplicating) information about these volumes every time by using:

```
volumes_from:
    container: <name of container>
```
It seems like this use-case is no longer possible with the compose v3 format.

Was this a deliberate choice? Or could support for this use-case be added to the compose v3 format.

**Comment by chris-crone** [comment]
Hi @simonvanderveldt, thanks for the question.

This was removed in v3 by choice (see: [v2.x to v3.x](https://docs.docker.com/compose/compose-file/compose-versioning/#version-2x-to-3x)). This was done because v3 of Compose is designed to work with Swarm which handles volumes differently.

**Comment by simonvanderveldt** [comment]
@chris-crone Thanks for the info. It seems like v3 is more of sidegrade than an upgrade compared to v2 with a different focus. Maybe a different name would be better?

We'll stick with v2 for now, hope it'll still be supported in the future.

Depending on if there's a chance or not that `volumes_from` can get added to v3 (and if v2 stays supported or not) it might make sense to keep this issue open?

**Comment by chris-crone** [comment]
The focus of Compose v3 is to make the format work in orchestrated (i.e.: Swarm and Kubernetes) environments. This meant that we had to make some breaking changes as one doesn't have the same guarantees when there are multiple nodes. That said, we do have some reconciliation that we need to do between v2 and v3 as some use cases that worked in v2 do not work with v3.

As it is unlikely that we will add `volumes_from` to v3, I will close this issue.
