### ISSUE TITLE
Inconsistency on container network when using `--no-start` and `network_mode`

### ISSUE THREAD

**Issue by divoxx** [docker/compose#6467]
## Description of the issue

The symptom of the problem is containers not being able to resolve internal DNS when specifying a `network_mode` and creating the container with `--no-start`. The root cause seems to be some discrepancy on how the network is setup.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.15
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Output of `docker version`**
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.11.2
 Git commit:        e68fc7a
 Built:             Wed Dec 12 18:03:23 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       e68fc7a
  Built:            Wed Dec 12 18:02:57 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    command: ping dependency
    depends_on:
    - dependency
    image: alpine:latest
    network_mode: service:network
  dependency:
    command: tail -f /dev/null
    image: alpine:latest
  network:
    command: tail -f /dev/null
    image: alpine:latest
version: '3.0'
```

## Steps to reproduce the issue

1. `docker-compose up --no-start app`
2. `docker-compose up app` or `docker-compose start app`

### Observed result

```
$ docker-compose up app
Starting doxcomposebug_network_1 ...
Starting doxcomposebug_network_1 ... done
Starting doxcomposebug_app_1 ... done
Attaching to doxcomposebug_app_1
app_1         | ping: bad address 'dependency'
doxcomposebug_app_1 exited with code 1
```

### Expected result

```
$ docker-compose up app
Creating doxcomposebug_dependency_1 ... done
Creating doxcomposebug_network_1    ... done
Creating doxcomposebug_dependency_1 ...
Creating doxcomposebug_app_1        ... done
Attaching to doxcomposebug_app_1
app_1         | PING dependency (172.27.0.3): 56 data bytes
app_1         | 64 bytes from 172.27.0.3: seq=0 ttl=64 time=0.055 ms
app_1         | 64 bytes from 172.27.0.3: seq=1 ttl=64 time=0.046 ms
^CGracefully stopping... (press Ctrl+C again to force)
Stopping doxcomposebug_app_1 ... done
```

## Additional information

Here is a relevant part of a diff between `docker inspect` for both containers, one created by `up` and another by `up --no-start`:

```diff
--- app.json	2019-01-16 13:22:19.889049988 -0800
+++ app_no-start.json	2019-01-16 13:20:47.990382374 -0800
@@ -166,12 +166,12 @@
         },
         "NetworkSettings": {
             "Bridge": "",
-            "SandboxID": "",
+            "SandboxID": "3608118588a4bc44c69bb780360ad5b2b2de453b3d17c0c16811583a87449c13",
             "HairpinMode": false,
             "LinkLocalIPv6Address": "",
             "LinkLocalIPv6PrefixLen": 0,
             "Ports": {},
-            "SandboxKey": "",
+            "SandboxKey": "/var/run/docker/netns/3608118588a4",
             "SecondaryIPAddresses": null,
             "SecondaryIPv6Addresses": null,
             "EndpointID": "",
@@ -182,7 +182,23 @@
             "IPPrefixLen": 0,
             "IPv6Gateway": "",
             "MacAddress": "",
-            "Networks": {}
+            "Networks": {
+                "bridge": {
+                    "IPAMConfig": null,
+                    "Links": null,
+                    "Aliases": null,
+                    "NetworkID": "661243aef64a1477b4db60d545ac6037ad5393ed7e27d453a2b588564b4504bb",
+                    "EndpointID": "",
+                    "Gateway": "",
+                    "IPAddress": "",
+                    "IPPrefixLen": 0,
+                    "IPv6Gateway": "",
+                    "GlobalIPv6Address": "",
+                    "GlobalIPv6PrefixLen": 0,
+                    "MacAddress": "",
+                    "DriverOpts": null
+                }
+            }
         }
     }
 ]
``` 

EDIT: typo

**Comment by ulyssessouza** [comment]
Thanks for the report @divoxx !

**Comment by ulyssessouza** [comment]
What happens is that with the single `docker-compose up`, the other services are started, by that, we can join the same network.
To have the same behavior the second command should be `docker-compose up --no-deps` that avoids the start of `dependency` and `network` services.
In some tests, I saw that only the running services are taken in account https://github.com/docker/compose/blob/9de1f569f3593ab7cbbe2354046f13f940b89acd/compose/service.py#L1384.
By changing this line to:
```python
containers = self.service.containers(stopped=False) 
```
Actually the `stopped` here means `all`, so that the ones with status `created` are also in the list.
This fixes the problem, but maybe that can be a problem, as mentioned in:
https://github.com/docker/compose/blob/9de1f569f3593ab7cbbe2354046f13f940b89acd/compose/service.py#L1388

My feeling is that this comment refers just to `exited` services/containers in this case, I'm not that sure by now which kind of problems this can create.
Maybe just by discerning between `created` and `exited` can be enough to avoid any problems.

**Comment by ulyssessouza** [comment]
Could please provide a use case for that issue?

**Comment by thaJeztah** [comment]
containers that are not started don't get an IP address (or DNS entry) assigned; I don't think this is specific to docker compose, but the same as doing `docker container create` (the container won't get the networking into until `docker container start`)

**Comment by divoxx** [comment]
@thaJeztah that makes sense but I would still expect the container to get the correct network data after it's started. Currently, the container can't really talk to any other container that would be within the same defined network.

@ulyssessouza Our use case is somewhat specific, but at our company we are working on a internal tool that wraps docker-compose and performs some additional tasks before the containers are started. The ability to create the containers without starting would allow us to inspect the containers and it's dependencies to parameterize those tasks with container information.

In general, though, since `--no-start` is a part of the toolchain, I'm assuming that it's a supported general use case, and that the behavior should be consistent.

**Comment by dchandekstark** [comment]
My use case: I have a compose file for the test environment of a Rails project. There are three services - app, db, and solr.  The app service runs the test suite as the default command. I would like, however, to bring up the stack with --no-start, then start the app container with a shell. We have observed that although the linked services start, the networking is not set up completely or properly as reported here.

**Comment by PrplHaz4** [comment]
it looks like this is still a problem with docker 20.10.5 and docker-compose v1.28.6

For me it appears when using static IPs for a container - I recreate the container with `--no-start` and it gets an ip from the ipam config range, instead of the static IP that is set for the container.
