### ISSUE TITLE
Add a warning when using docker-compose down -v

### ISSUE THREAD

**Issue by HRK44** [docker/compose#6468]
**Is your feature request related to a problem? Please describe.**
When using ``docker-compose down -v``, it removes the volumes which most of the time can contain some critical data (like a DB or something else).

**Describe the solution you'd like**
I think it would be wise to add a warning, something like "Are you sure you want to delete the volumes associated with this services? You might lose data etc... [y/N] : ".

**Describe alternatives you've considered**
Maybe hide this warning when the command is used with ``--force``.

**Comment by ulyssessouza** [comment]
Thanks for the report @HRK44 !

**Comment by shin-** [comment]
I'm not sure I agree with this; the whole point of `-v` is to remove volumes. Adding prompts for each volume would make the command a lot more cumbersome to use, and virtually useless in scripts, especially for applications using a large number of volumes. Anyone who is worried about losing critical data can just refrain from using the `-v` flag in the first place.

**Comment by HRK44** [comment]
Lot of (most?) CLI apps warn you when you are about to erase data, especially higher level commands like ``docker-compose down`` where just one option ``-v`` might wipe you entire sets of data... For the scripting side, that's why I also mention a silent/force mode to remove the warning.

I understand that this change is a breaking change, but I think it's worth exploring the pros/cons.

**Comment by ulyssessouza** [comment]
I tend to agree with @shin-. 
The "safe-mode" is just not to use the option. So since it's used, I see as an imperative action so no need to re-ask.

WDYT @chris-crone ?

**Comment by chris-crone** [comment]
Thanks for the suggestion @HRK44!

I see the `-v` option as the user saying explicitly that they want to remove the volume so I don't think a prompt is necessary.

As you noted, adding this now would also be a breaking change. The impact of that can be seen with a quick [GitHub search](https://github.com/search?q=%22docker-compose+down+-v%22&type=Code). There are literally thousands of public scripts and CIs that rely on the flag not having a prompt.

**Comment by HRK44** [comment]
I guess a softer alternative would be to emphasize this warning in the docs of [``docker-compose down``](https://docs.docker.com/compose/reference/down/), makes it more clear for new comers and other people that this command will erase data ?
