### ISSUE TITLE
fig run service tag

### ISSUE THREAD

**Issue by florentvaldelievre** [docker/compose#647]
Is there a way to specify a tag when running fig up / run ?

````
zookeeper:
 image: registry:5000/zookeeper
````
exemple:
````
fig run zookeeper:0.21
````

it will pull & run registry:5000/zookeeper:0.21

**Comment by dnephin** [comment]
Right, the answer is basically no, this isn't really compatible with running a service.

Now (in 1.5.0) that we support variables you could do something like 

```yaml
zookeeper:
    image: reistry:5000/zookeeper${ZOOKEEPER_TAG}
```

`ZOOKEEPER_TAG=:0.21 docker-compose run zookeeper`
