### ISSUE TITLE
not using cached layers

### ISSUE THREAD

**Issue by timini** [docker/compose#6475]
running docker-compose build does not use cached image layers with docker version 18.09.1 on OSX

8BFFB0AD-D0C1-43EC-9C80-838A7AD36677/20190118203737

**Comment by timini** [comment]
Seems that because i had 
```
build:
  context: .
```
the cache wasn't being used

seems this is intended behaviour please see:

https://github.com/docker/compose/issues/5439

**Comment by deniztoprak** [comment]
How did you solved the problem? If I removed the `context` and `cache_from ` directives like in #5439 mentioned but it didn't work.

**Comment by timini** [comment]
Sorry I never found a resolution to this and switched to using docker commands
