### ISSUE TITLE
`docker-compose build` does not output "Sending build context to Docker daemon ..."

### ISSUE THREAD

**Issue by krtx** [docker/compose#6484]
**Is your feature request related to a problem? Please describe.**
`docker-compose build` does not output the first line of `docker build` output, which is "Sending build context to Docker daemon ... kB". This part sometimes takes too much time since `.dockerignore` is not well-configured.

In the case of me, I could not know why `docker-compose build` took so much time (in fact, there were huge files in the context directory) until I tried to `docker build` manually.

**Describe the solution you'd like**
Output "Sending build context to Docker daemon" would help to diagnose the problem of `.dockerignore`.

Thank you.

my docker version:
```
$ docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by ulyssessouza** [comment]
Thank you for the report @krtx !

`docker-compose` uses `docker-py` to comunicate with the `docker daemon` and not the `docker cli` do that's normal that they don't have the same output.
About having any output to differentiate internal steps, `docker-compose` prints `Building <service-name>`.

For more information, you can run `docker-compose --verbose --log-level DEBUG build`

**Comment by krtx** [comment]
Thank you @ulyssessouza for your kind response !

> docker-compose uses docker-py to comunicate with the docker daemon and not the docker cli do that's normal that they don't have the same output.

Oh that's natural not to use docker cli... I had a very basic mistake.

> For more information, you can run docker-compose --verbose --log-level DEBUG build

I'll try this for the next time I get stuck.
