### ISSUE TITLE
zsh: exec format error: docker-compose

### ISSUE THREAD

**Issue by thomasfaller** [docker/compose#6486]
Hey folks,

I just installed docker-compose on my Elementary OS 5 machine (Ubuntu-based) and I'm getting the following output when typing `docker-compose`:
```
zsh: exec format error: docker-compose
```

If I type `which docker-compose` I do get the correct path I believe:
```
/usr/local/bin/docker-compose
```
And I simlinked that just in case to `/usr/bin/docker-compose` which is where docker is kept (as suggested by the docs).

Strangely enough if I run `sudo docker-compose` I get 
```
/usr/local/bin/docker-compose: 1: /usr/local/bin/docker-compose: Syntax error: "(" unexpected
```
Any thoughts on what could be happening ?

**Comment by shin-** [comment]
It would be a good idea to indicate how you installed Compose. At a glance, it seems like you downloaded a text file of some sort which your OS is trying (and failing) to execute as if it were a script. Looking at the contents of `/usr/local/bin/docker-compose` may give you a better idea of what's happening too.

**Comment by thomasfaller** [comment]
I reinstalled it and it works now.
