### ISSUE TITLE
Start command reports "done" but also ERROR

### ISSUE THREAD

**Issue by geertschuring** [docker/compose#6487]
## Description of the issue
Starting from a clean situation with no running or stopped containers the `docker-compose start` command (instead of `up`) reports having started my containers but also reports a (correct) error that there are no containers to start.

Output:
```
>docker-compose start
Starting server   ... done
Starting frontend ... done
ERROR: No containers to start
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker-compose config`**
```
services:
  frontend:
    image: example-web-vaadin-rest
    ports:
    - 8081:8080/tcp
  server:
    image: example-rest-spring
version: '3.0'
```

## Steps to reproduce the issue
1. Stop and remove all existing containers
2. Run `docker-compose start`
3. Notice contradicting output.

### Expected result
I would expect docker to tell me that there are no containers to start. I should run the up command first.

**Comment by shin-** [comment]
Same as #5469 ?

**Comment by geertschuring** [comment]
Yeah looks like it. I didn't find that one earlier.Op 30 jan. 2019 01:49 schreef Joffrey F <notifications@github.com>:Same as #5469 ?
