### ISSUE TITLE
Why not provide a :latest tag on DockerHub docker/compose?

### ISSUE THREAD

**Issue by DannyBen** [docker/compose#6488]
Is there a reason that the [docker/compose][1] image on DockerHub does not have a `latest` tag?

I would love to be able to just do this:

```
$ docker run --rm -it docker/compose --version
Unable to find image 'docker/compose:latest' locally
docker: Error response from daemon: manifest for docker/compose:latest not found.
See 'docker run --help'.
```

[1]: https://hub.docker.com/r/docker/compose/tags

**Comment by simonferquel** [comment]
@shin- is there a rational for that ? sounds like a good suggestion

**Comment by DannyBen** [comment]
I can't help but feel that Its a bit of a [shoemaker's children go barefoot](https://en.wiktionary.org/wiki/the_shoemaker%27s_children_go_barefoot) situation... 😄

**Comment by F21** [comment]
Was wondering the same myself. Unfortunately, I don't think they will add a latest tag to the docker image: https://github.com/docker/compose/issues/5987#issuecomment-392113124

**Comment by mattayes** [comment]
We use Docker Compose for testing and always want the latest stable release. Having a `latest` tag would be very handy.

I believe this will require changes to [images.py](https://github.com/docker/compose/blob/master/script/release/release/images.py).
