### ISSUE TITLE
`fig run` cuts off long lines at 1024 characters

### ISSUE THREAD

**Issue by inklesspen** [docker/compose#649]
If I run `fig run --rm web bash`, then run a command which produces a very long line, that line is cut off at 1024 characters. (Fig 1.0.1)
If I run `docker run -i -t --rm mimir_web:latest bash` (where mimir_web is the image Fig generated for web), and run the command which produces the very long line, that line is not cut off.

Any ideas?

**Comment by sylvinus** [comment]
Any news on this?

**Comment by dnephin** [comment]
Are you still able to reproduce this issue with newer version of Compose?

**Comment by dnephin** [comment]
I just tried it out with master, and I can't reproduce this issue anymore:

```
$ cat > /what
<2k characterS>
$ wc -c /what
2327
$ cat /what
<all the characters>
```
