### ISSUE TITLE
Release for Linux-ppc64le?

### ISSUE THREAD

**Issue by docwhat** [docker/compose#6492]
It would be nice to have a release binary for `ppc64le` so that the [installation instructions](https://docs.docker.com/compose/install/) would work correctly on Ubuntu 18.04 on ppc64le.

Otherwise, maybe the instructions should be changed from:

``` sh
sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

to

``` sh
sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-x86_64" -o /usr/local/bin/docker-compose
```

with extra instructions for non-x86_64 systems.

**Comment by simonferquel** [comment]
@ulyssessouza would it be a big effort to add ppc64le arch to the release matrix ?
If not, we should update the install documentation for non amd64 archs (with instructions to build from sources)

**Comment by chris-crone** [comment]
@docwhat You can install `docker-compose` using `pip` as described here: https://docs.docker.com/compose/install/ under "Alternative Install Options".

We should likely update that documentation to specify the architecture.
