### ISSUE TITLE
pull progress makes no sense

### ISSUE THREAD

**Issue by yarons** [docker/compose#6495]
## Description of the issue
The progress percentage is going crazy, the numbers are increasing and nulled with absolutely no relation to the actual status, they are somehow also linked to one another.

## Symptoms

(I could possibly attach a video that will show what happens, the download and extraction are working great, the progress display is the problematic part)

This is what happened several seconds after running the command:

```
Pulling basic_nfc          ... 
Pulling basic_hw           ... downloading (57.9%)
Pulling basic_bridge       ... downloading (57.9%)
Pulling basic_relays       ... 
Pulling basic_counters     ... waiting
Pulling basic_rfid         ... downloading (57.9%)
Pulling basic_zabbix-agent ... done
Pulling basic_mr           ... 
Pulling basic_ui           ... waiting
```

This was the status several minutes later:
```
Pulling basic_nfc          ... 
Pulling basic_hw           ... extracting (1.8%)
Pulling basic_bridge       ... extracting (1.8%)
Pulling basic_relays       ... 
Pulling basic_counters     ... done
Pulling basic_rfid         ... extracting (1.8%)
Pulling basic_zabbix-agent ... done
Pulling basic_mr           ... extracting (1.8%)
Pulling basic_ui           ... extracting (8.0%)
```

The numbers are just increasing and decreasing randomly and there's no progress bar.
Previously (Last time I remember) the numbers were meaningful and always increasing as it should be.

Compose Version:
```
docker-compose version 1.23.2, build 1110ad0
```

**Docker Version**
```
Docker version 18.09.1-ce, build 4c52b901c6cb019f7552cd93055f9688c6538be4
```

## Additional information

Alpine 3.9.0

**Comment by simonferquel** [comment]
The progress displayed there is actually `per-layer`. I don't know if we should clarify that - might break existing tools relying on this output format - and if we have the info from the json message streams. Ping @shin-

**Comment by yarons** [comment]
@simonferquel I also remembered it more verbose but now there's no layer related information so it just looks like the total completion percentage just rises and drops randomly as shown in the attached pasted text.

I remembered it looked differently.

**Comment by shin-** [comment]
We had to adapt the output when we added support for parallel pulling a few versions ago. If output format is important, the previous output can be obtained using the `--no-parallel` option.

**Comment by yarons** [comment]
Actually, @shin- I don't care about the format :smile: 

All I care about is that the displayed output would be informative to the user.

Luckily I understand how docker works so I figured it might be something like what you described but think about a new user, I'm seeing several lines, each one pulling a different docker image, the percentage displayed is growing in numbers but it's the same number across the lines and there's no info displayed on whether it's layer related or image related so as a new user I'm seeing the names of the downloaded images and percentage going up and resetting every couple of seconds, I'm not sure whether it's actually progressing or stuck and most importantly: when is this progress going to end which is what the percentage are supposed to represent in the first place.

It's not "buggy" in terms of technical description it's just less informative than it used to be, I wouldn't care if it would be more informative but not the other way around…

If it's still unclear I can have a screencast of what I'm experiencing, maybe it'll be more meaningful to the discussion.

**Comment by kmalfroid** [comment]
Can we reopen this? As a relatively new user of docker-compose, the current behavior has been extremely confusing to me.

**Comment by billytetrud** [comment]
This behavior still exists. Please reopen this. Also please consider getting rid of stale bot. Stale bots close so many actual issues like this one. I mean, unless you want your project to be the kind of project that has many longstanding bugs for 5+ years..

@[maxcleme](https://github.com/maxcleme) pinging you just cause I saw you active recently.

**Comment by alinabel** [comment]
I'm just new at docker 
this behavior  got me to redownload the file fucking 4 times because I think its a bug,
the problem its not just a percentage going up and down, no the hall terminal turns into a total mess with numbers flyes anywhere everywhere, so annoying.

**Comment by nicksieger** [comment]
Does this still happen with Compose v2? The original report targeted v1, which is obsolete and we're only making security fixes for.

**Comment by billytetrud** [comment]
Looks like the new compose doesn't use percentages at all, but instead a download progress bar. The progress bar seems to work properly.
