### ISSUE TITLE
fig append existing env variable

### ISSUE THREAD

**Issue by andizzle** [docker/compose#650]
In Dockerfile I can append ENV like this:
`ENV PATH /code/.python/bin:$PATH`

Is it possible to do something similar in fig.yml:
```yml
environment:
  - PATH=/code/.python/bin:$PATH
```
Any hints are appreciated.

**Comment by schickling** [comment]
+1

**Comment by arruda** [comment]
+1

**Comment by pwaller** [comment]
Is this resolved now that #1765 is merged?

**Comment by dnephin** [comment]
I don't think the scenario described in the original issue will work. If you were to use that config you're get the `$PATH` from the host, which is probably not what you want.

That said, I don't think we can actually do what you're suggesting (query the path from the container and append to it), so I'm going to assume that these +1s were for #1765 and close this issue.

If that assumption is wrong, please feel free to comment, or open a new ticket with more details about how you see it working.

Thanks!

**Comment by brondsem** [comment]
I am interested in doing something like the original comment shows.  That is, using compose to extend the PATH var.

**Comment by arruda** [comment]
since new version I think it's possible to do it like this:
```yaml
    environment:
      - PATH=/code/.python/bin:${PATH}
```
docs: https://docs.docker.com/compose/compose-file/#variable-substitution

**Comment by dnephin** [comment]
That would set to path to the **host** path, which is probably not what you want.
