### ISSUE TITLE
Add project name to the custom name of a one-off container

### ISSUE THREAD

**Issue by tnguyen14** [docker/compose#6512]
When I do
```
docker-compose run service ...
```

the one off container has the name `${project-name}_service_run_1`, but if I do 

```
docker-compose run --name custom-name service ...
```

then the name is just `custom-name`.

I understand that this is the expected behavior, but I was wondering if there's a way to also have the `project-name` applied as a prefix to the custom name?

Or perhaps I'm trying to solve the problem with the wrong approach. The problem I have is, if I run the `docker-compose run` command twice in parallel, one of them will fail because the they will try and spin off containers with the same name. Is there a way to get around that issue?

**Comment by ulyssessouza** [comment]
Hello @tnguyen14 , as you mentioned in your question, this is the expected behavior.

If you want to prefix the name with the project name you should use the option as `--name myprefix_custom-name`.

Note that it can be an environment variable too.

**Comment by tnguyen14** [comment]
Yeah I'm aware of the `COMPOSE_PROJECT_NAME` environment variable. However, docker-compose does some light processing on the project name before applying it as a prefix. So I want a mechanism that would have the `myprefix` to be as close of a match to what docker-compose would use as possible.

**Comment by ulyssessouza** [comment]
You can also use `--project-name` to impose it even with 2 different projects that have the same folder name

**Comment by tnguyen14** [comment]
So from your perspective, my original request isn't valid?

**Comment by ulyssessouza** [comment]
Yes. In the sense that it breaks the imperativeness of `--name` and you can use other strategies to reach your goal.
