### ISSUE TITLE
Compose schema version 3.8 support

### ISSUE THREAD

**Issue by chris-crone** [docker/compose#6530]
Add support for Compose schema version 3.8 to bring in line with Docker CLI.

See: https://github.com/docker/cli/pull/1410

**Comment by sirlatrom** [comment]
Also see https://github.com/docker/cli/pull/1746 (another new field in 3.8)

**Comment by sirlatrom** [comment]
I'm hoping this one will make it in: #1783, so in case it looks like it will, I'll be happy to contribute its counterpart in docker-compose.

**Comment by chris-crone** [comment]
@sirlatrom that'd be great, thanks!

**Comment by sirlatrom** [comment]
> @sirlatrom that'd be great, thanks!

As soon as I get an LGTM from @thaJeztah on docker/cli#1783, I'll push a PR for Compose 3.8. AFAICT it's just a bit of admin-like work by copying over the spec JSON file and adding references to it in a few places.

**Comment by aldoborrero** [comment]
Any news on this issue? Is somebody working on it?

**Comment by sirlatrom** [comment]
I believe #6823 resolves this issue.

**Comment by ndeloof** [comment]
Don't forget to document changed introduced in 3.8 on https://docs.docker.com/compose/compose-file/compose-versioning/
