### ISSUE TITLE
Context with combination of hyphen and underscore fails with: ERROR: invalid reference format

### ISSUE THREAD

**Issue by heron182** [docker/compose#6531]
## Description of the issue
If compose context folder name contains some kind of combination between `-` and `_` then `docker-compose build` will fail with `ERROR: invalid reference format`

## Context information (for bug reports)
Similar to #5929.

**Output of `docker-compose version`**
```
docker-compose version 1.24.0-rc1, build 0f3d4dda
docker-py version: 3.7.0
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
```
services:
  app:
    build:
      context: /home/heron/dev/pp_-_test
    ports:
    - 8080:8080/tcp
    volumes:
    - /home/heron/dev/pp_-_test:/app:rw
version: '3.0'
```

## Steps to reproduce the issue

1. `docker-compose build` with above config and any Docker image

### Observed result
Compose fails with `ERROR: invalid reference format`

### Expected result
Compose build the image

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Compose installed directly via curl 
**OS**
``` 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by developer-hatch** [comment]
I have the same issue   Task :composeBuild FAILED
invalid tag "560eda500d1b1b09e97d19c8d93cdc80_jobsity_-jobsity"
