### ISSUE TITLE
docker-compose deploy not working

### ISSUE THREAD

**Issue by arrow2012** [docker/compose#6539]
docker-compose version 1.22.0, build f46880fe
Docker Engine  18.09.2

docker-compose.yml

```version: '3.4'
services:
  hello:
    image: nginx
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: on-failure
```

WARNING: Some services (hello) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.

deploy not work

**Comment by jcsirot** [comment]
@arrow2012 Thank you for your report.

It seems that use are using `docker-compose` to run the `hello` service. However the `deploy` keyword in a compose file is reserved for the deployment of stacks in a swarm cluster (https://docs.docker.com/compose/compose-file/#deploy) and this section of the compose file is ignored when deployed with `docker-compose`.
Did you encounter any other error message?

**Comment by DanielJoyce** [comment]
Same issue here, it causes deployment to tail though docs say its just a warning and deploy should still work....

**Comment by khalsajing** [comment]
Yes. yml version 3.7. docker-compose version 1.24.1, build 4667896b.
"WARNING: Some services (service_name) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm."
  ---------
  deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '0.25'
          memory: 512M

**Comment by wazirsoft** [comment]
That is just a warning telling that `docker-compose` does not provide any functionality we are expecting under the `deploy`

Means, if you want use the deploy option you cannot just use `docker-compose up -d` you need to initiate the docker swarm `docker init swarm` and then do `docker stack deploy --compose-file="docker-compose.yml" stack` to start containers under docker swarm.

**Comment by QFP-ZJT** [comment]
when use `docker-compose` add a parameter `--compatibility`,like `docker-compose --compatibility up -d` maybe help you!
