### ISSUE TITLE
Improve/cleanup Dockerfile ADD statements

### ISSUE THREAD

**Issue by joakimr-axis** [docker/compose#6557]
Using one ADD command for each file to be copied is sub-optimal. Furthermore, Docker best practice is to use COPY if possible ([https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy)).

I will provide a pull request for this.

**Comment by ulyssessouza** [comment]
Solved by https://github.com/docker/compose/pull/6641
