### ISSUE TITLE
Support IPAM gateway

### ISSUE THREAD

**Issue by rvernica** [docker/compose#6569]
**Is your feature request related to a problem? Please describe.**

See #6555 

**Describe the solution you'd like**

The [documentation](https://docs.docker.com/compose/compose-file/#ipam) page sis it all:

> Note: Additional IPAM configurations, such as gateway, are only honored for version 2 at the moment.

I would be nice to have a more complete support of IPAM/network in the compose file for version `3.x`.

**Describe alternatives you've considered**

I've considered downgrading to version `2.x` but it seems a step backward.

**Comment by cjsimon** [comment]
Also see https://github.com/docker/compose/issues/4474

**Comment by bastiao** [comment]
Any possible alternatives?

**Comment by unixfox** [comment]
don't close it

**Comment by kewur** [comment]
just stumbled upon this. official ecs documentation were using gateway so I had to revert back to version 2. 

https://aws.amazon.com/blogs/compute/a-guide-to-locally-testing-containers-with-amazon-ecs-local-endpoints-and-docker-compose/

**Comment by smgoller** [comment]
Would definitely like to be using version 3 files. What needs to be done to make this supported?

**Comment by EricHripko** [comment]
Releases [1.27.0+](https://github.com/docker/compose/releases) have merged v2/v3 file formats, so you should be able to use `ipam` anywhere now.

**Comment by roelvanduijnhoven** [comment]
@EricHripko That would be great! However the docs still tell me the following:

> Additional IPAM configurations, such as `gateway`, are only honored for version 2 at the moment.
> -- https://docs.docker.com/compose/compose-file/#ipam

Do you think the docs are outdated in this regards?

**Comment by EricHripko** [comment]
Yep - I don't think the docs have been updated to reflect the changes introduced by _1.27.0+_ yet.

**Comment by PrplHaz4** [comment]
> 
> 
> Yep - I don't think the docs have been updated to reflect the changes introduced by _1.27.0+_ yet.

What is the minimum 3.x docker-compose file version this will be supported in?  Will anything 3.0+ be valid (in addition to 2.0+) as it's just a docker-compose update, not a spec bump?

**Comment by EricHripko** [comment]
_1.27.0+_ drops the requirement for `version` attribute (so you don't even have to specify it any more). This indeed means that you can mix any 3.0+ features with any 2.0+ features 🙂

**Comment by Nothing4You** [comment]
unstale

**Comment by mulder999** [comment]
When could we expect to have a working gateway option ?

**Comment by ndeloof** [comment]
compose-spec has merged v2 and v3, so all attributes are now valid in a compose file.

**Comment by mulder999** [comment]
Attribute is valid but ignored. Was rather expecting a working solution.

**Comment by ndeloof** [comment]
ah ok, so we need to fix this obviously :P

**Comment by anthraxn8b** [comment]
I guess adding label "Docker Compose V3" would fit better...

**Comment by ndeloof** [comment]
@anthraxn8b you should better use your energy to contribute

**Comment by javiortizmol** [comment]
Hi, any updates?, I'm trying to have this approach working (ECS locally) but with the v 3.4 is not working :(

**Comment by flyingbarbarian** [comment]
IPAM gateway is working with v3.8.

My environment is below.
OS:Ubuntu 20.04
Docker:20.10.12
docker comose 1.29.2

Is the doccument incorrect?

> Additional IPAM configurations, such as gateway, are only honored for version 2 at the moment.
> -- https://docs.docker.com/compose/compose-file/#ipam

**Comment by flyingbarbarian** [comment]
@ndeloof 

thank you!!
I can use also ipam config of "ip_range" and "auxx_address" as you say.
I made [pull request](https://github.com/docker/docker.github.io/pull/14391) about compose file reference v3.

**Comment by StevenCoburn** [comment]
I can't seem to get this working.

OS: Debian 11.3
Docker: 20.10.14
Docker Compose 2.4.1
Compose file version: Tried 2.0, 3.7, and 3.8

Seems like everything under ipam > config gets ignored except for subnet. I'm trying to set an ip_range and gateway and it simply ignores those options. Below is the config I'm trying to use:

 ```
 MyNet:
    name: MyNet
    driver: macvlan
    driver_opts:
      parent: ens18.30
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/24
          ip_range: 10.3.0.192/26
          gateway: 10.3.0.1
```

**Comment by pagdot** [comment]
@StevenCoburn Right now, this only works with docker-compose 1.x and compose file version 2.x until this bug gets fixed!

**Comment by mulder999** [comment]
No stale

**Comment by ndeloof** [comment]
gateway attribute is well set on `NetworkCreate` API cal (https://github.com/docker/compose/blob/v2/pkg/compose/create.go#L1097)

compose.yaml
```yml
services:
  web:
    image: nginx
    networks:
      - MyNet

networks:
  MyNet:
   name: MyNet
   ipam:
     config:
       - subnet: 10.3.0.0/24
         ip_range: 10.3.0.192/26
         gateway: 10.3.0.1
```

```
$ docker compose up -d 
...
$ docker network inspect MyNet
[
    {
        "Name": "MyNet",
        "Id": "e3a50a3939a932386b7b2666b8bef64cace3e36fd843867173e94930fb83c65e",
        "Created": "2022-12-07T16:31:30.39375117Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.3.0.0/24",
                    "IPRange": "10.3.0.192/26",
                    "Gateway": "10.3.0.1"
                }
            ]
        },
$ docker inspect foo-web-1 -f '{{.NetworkSettings.Networks.MyNet.Gateway}}'
10.3.0.1
```

What am I missing here to reproduce this issue ?

**Comment by ndeloof** [comment]
Also checked inside container:
```
$ ip route
default via 10.3.0.1 dev eth0 
```

I'm closing this issue as "fixed". Please open a follow-up issue if I missed something here and this requires further investigations

**Comment by vorishirne** [comment]
@ndeloof the docs still say that gateway is not supported in V3. What is the moral of the issue.....in v3 and unspecified version...will gateway work?

**Comment by ndeloof** [comment]
@vorishirne "_v2 vs v3_" is obsolete with the compose specification: just don't set a `version` attribute in your compose file. All v2 or v3 attribute will then be supported

**Comment by ndeloof** [comment]
https://docs.docker.com/compose/compose-v2/

**Comment by vorishirne** [comment]
I read the doc, but it doesn't mentions the fact that, not specifying any version will pick all the fields

**Comment by ndeloof** [comment]
by the compose specification, version is just ignored: https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-top-level-element
