### ISSUE TITLE
Human readable sizes in `docker-compose images` differ from ones in `docker images`

### ISSUE THREAD

**Issue by uu1t** [docker/compose#6590]
## Description of the issue

Image sizes in `docker images` output are formatted as decimal (KB, MB, GB). But image sizes in `docker-compose images` output are formatted as binary (KiB, MiB, GiB).

source where formatting sizes in `docker images`:
https://github.com/docker/go-units/blob/2fb04c6466a548a03cb009c5569ee1ab1e35398e/size.go#L59-L61

source where formatting sizes in `docker-compose images`:
https://github.com/docker/compose/blob/8f8678987b4496384452143b6eeec88d51b14510/compose/cli/utils.py#L141-L143

I'm not sure this issue is for docker/compose or docker/cli but output image sizes should be consistent.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Steps to reproduce the issue

1. Run `docker images`
2. Run `docker-compose images`

### Observed result

Output image sizes are different in format (decimal and binary). 

### Expected result

Output image sizes are consistent.

**Comment by jcsirot** [comment]
@uu1t Thank you for your report

**Comment by Buffer0x7cd** [comment]
@jcsirot  I would like to work on this enhancement. I am new to the docker-compose codebase so I might need a bit of help initially.

**Comment by ulyssessouza** [comment]
@Buffer0x7cd nice initiative! You can start by submitting a PR to solve the problem and we will review the work so that it can be improved
