### ISSUE TITLE
Proposal: add Docker save and load commands

### ISSUE THREAD

**Issue by ebuildy** [docker/compose#6611]
**Is your feature request related to a problem? Please describe.**
Docker can save and load image as tar archive, docker-compose not.

**Describe the solution you'd like**
a simple ``docker-compose save > compose.tar``.

**Describe alternatives you've considered**
Parsing ``docker-compose.yml`` file to get image list, then run manually ``docker save``:

```
docker save -o docker-images.tar $(docker-compose config | awk '{if ($1 == "image:") print $2;}' ORS=" ")
```

**Comment by ijc** [comment]
Thanks for the suggestion, this sounds like a reasonable enhancement, I think we'd be happy to take a look at a PR implementing this.

**Comment by ebuildy** [comment]
Thanks you, do you thing this is an easy one? I could spend some time on it if yes.

**Comment by ijc** [comment]
I woudn't say completely trivial, but at the easier end of the spectrum I reckon.

**Comment by Ryllau** [comment]
I was wondering if this has been implemented yet?
