### ISSUE TITLE
shell variable not available in docker-compose.yml when using stack deploy

### ISSUE THREAD

**Issue by eduarddrenth** [docker/compose#6613]
## Description of the issue

in shell
```VERSION=1.3```
in compose file
```image: oat:${VERSION}```

the version remains empty when doing stack deploy

## Context information (for bug reports)

docker version: 18.06.0-ce

compose version: 1.22.0-rc1

ubuntu 18.04

**Comment by ijc** [comment]
Stack deploy is not part of compose, it is a Docker cli thing so you should report against `github.com/docker/cli`.

Apart from that this report is lacking in the detail requested by the template. In the future please included that. Closing.

**Comment by eduarddrenth** [comment]
ok, thanks, sorry for the short (but clear) issue, I'll reconsider using stack
