### ISSUE TITLE
Change Docker image entrypoint to shell

### ISSUE THREAD

**Issue by ebuildy** [docker/compose#6614]
**Is your feature request related to a problem? Please describe.**

Using the image ``docker/compose``, the entrypoint is ``docker-compose`` bin, this makes the image difficult to use inside CI tools such as GitlabCI that require a shell.

Also, as an official Docker® image, this image should work like image ``docker`` (see https://github.com/docker-library/docker/blob/6e5ccf3c71e86b98bb75600b4309ccf1bc87775e/18.06/docker-entrypoint.sh), they can execute ``docker`` command or default shell command.

**Describe the solution you'd like**

The entrypoint of ``docker/compose`` image should have the same logic than ``docker`` image. Or you could create a new flavor ``docker/compose:sh`` that have default shell entrypoint.

**Describe alternatives you've considered**
I can override the entrypoint or create a new public Docker image, extending ``docker/compose`` with the same entrypoint logic than ``docker`` image. 

**Additional context**
* gitlabCI Docker executor

**Comment by ebuildy** [comment]
I have done this image > https://github.com/ebuildy/compose/blob/docker-image-entrypoint-shell/docker-image/entrypoint.sh work pretty well!

**Comment by ijc** [comment]
> use inside CI tools such as GitlabCI that require a shell.

Please can you expand upon this requirement, what exactly does it mean that GitlabCI requires a shell? Do you have a reference for that? (You can assume I know ~0 about gitlabci)

Why would you need to run the shell within the `compose` image, instead of using e.g. `alpine` or something which needs a shell?

Why can you not use `--entrypoint` to override in cases where the default is not what you want?

**Comment by ebuildy** [comment]
Ho you are right, I should explain first what gitlabCI does, according https://docs.gitlab.com/runner/executors/docker.html#the-entrypoint

> The Docker executor doesn’t overwrite the ENTRYPOINT of a Docker image.
> 
> That means that if your image defines the ENTRYPOINT and doesn’t allow to run scripts with CMD, the image will not work with the Docker executor.

As such, to use the ``docker/compose`` image, we need to override the entrypoint. This is not a big problem, but as the official image ``docker`` have another logic of the entrypoint, smarter, I found too bad that ``docker/compose`` do not. This is not consistent, and Docker® should propose official images with same logic.

**Comment by ijc** [comment]
Please can you give an example of what you are trying to do and show why it doesn't work?

The example given at https://docs.gitlab.com/runner/executors/docker.html#the-entrypoint with the `entrypoint.sh` running `docker build` and passing `Dummy Script` as the `CMD` etc suggests to me that it is not required to be able to run literal shell commands and that it is acceptable that images do use `entrypoint` such that they interpret `CMD` as something other than a shell script, specifically arguments to the command in `ENTRYPOINT`.

So from my reading given `ENTRYPOINT ["/code/.tox/py37/bin/docker-compose"]` or similar things like:
```
 build:
   image: docker/compose:version
   script:
   - up
   - down
   - ps
```
should work just fine.

I'm afraid I don't put much stock in the argument that all images `docker/*` should behave the same way, so the fact of `docker/docker`s behaviour does not seem relevant how `docker/compose` behaves.

**Comment by ebuildy** [comment]
gitlabCI Docker executor must execute shell commands to setup the container, as such, we must override the default ``docker/compose`` entrypoint, this is not a big deal because it's possible.

I suggest a technique, that you use in official ``docker`` image (and plenty another images, I am pretty sure this is a good practice), this entrypoint logic make the image works exactly like before, and add the possibility to execute other commands such as ``sh -c`` without dirty hack.

I see plenty of Docker images implementing this entrypoint logic:

- https://github.com/docker-library/php/blob/master/docker-php-entrypoint
- https://github.com/docker-library/mysql/blob/696fc899126ae00771b5d87bdadae836e704ae7d/5.5/docker-entrypoint.sh#L6

As an entreprise, we love when things are "standard" and seamless :-)

**Comment by ijc** [comment]
I'd still love to see an example of what you are actually doing and how it is failing.

**Comment by AnthonyMastrean** [comment]
@ijc I show GitLab CI build scripts and runner output over on https://github.com/docker/compose/issues/6617#issuecomment-478028445

**Comment by ijc** [comment]
Thanks @AnthonyMastrean the need to do a `docker login` was the bit of info I was missing to justify this requirement.

Looks like `docker login` really wants a working docker socket, I'm not sure if gitlab will provide you with one though, but I guess it must be possible since you were planning to use `docker-compose` which will want it. I guess you need some bind mounts or to set `$DOCKER_HOST` or something, but as I said at the top I no essentially 0 about gitlab..

**Comment by ebuildy** [comment]
Thanks you @AnthonyMastrean for the example, like I said, the image ``docker`` is perfect, and the way they wrote the entrypoint.sh **will not change the behavior** of ``docker/compose``.

I can do a PR from my fork (https://github.com/ebuildy/compose/blob/docker-image-entrypoint-shell/docker-image/entrypoint.sh) to see changes, maybe this will help?

**Comment by ulyssessouza** [comment]
Solved by https://github.com/docker/compose/pull/6641
That will be included in the next release.

**Comment by ulyssessouza** [comment]
@AnthonyMastrean @ebuildy A new RC of docker-compose is available with the solution to this issue. WDYT about having a try? It's the 1.25.0-rc1

**Comment by ebuildy** [comment]
Finally! Thanks you
