### ISSUE TITLE
New apply command

### ISSUE THREAD

**Issue by jpic** [docker/compose#6627]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to run a bunch of docker-compose commands manually because it's long to type (i would prefer dockerctl but that's another story):

- pull
- build
- down
- up -d
- logs
- ps

Especially when automating docker-compose deployments from CI, calling logs and ps in the job do save the systematic action i would take on the server that is running these commands before debugging any kind of problem -> automating them saves from typing them later.

**Describe the solution you'd like**

I would like `docker-compose apply` to run the deploy chain of automation and post deployment logs commands. 

**Describe alternatives you've considered**

Currently, I have implemented this in my docker-compose wrapper I use for experimental commands (other notable ones are backup and restore, planned for submission one day). 

**Additional context**

I'm submitting the apply command idea here, because I'm so happy with it i want to share it with the community ;)

**Comment by ulyssessouza** [comment]
Hello @jpic. Thank you for the interest, but the problem I see here is that it goes against the atomicity of the commands. 
Ex: return codes

**Comment by jpic** [comment]
Thanks for your kind reply.

The way I do it in compoctl is that it checks the return code for each
command and breaks the process on non-zero, exiting with the return code of
the last command. As such, there is no problem with return codes which I
also value as an automation person.

If anybody is interested I will keep on maintaining it in the compoctl
package because it's extremely useful.

Best regards
