### ISSUE TITLE
Can fig build an image with no service/container associated ?

### ISSUE THREAD

**Issue by Dridi** [docker/compose#663]
I'm just starting with fig so it may just be a case of not reading properly the docs, but I haven't found out how to just build an image with fig. I'm trying to replace a make-based approach after someone told me a couple months ago that I was basically doing what fig does. I was also waiting for fig 1.0 to land in Fedora, which is almost there.

But I have a base image, which is basically based on `centos:centos6`, installs and enables EPEL, and a private YUM repository. I use this image as a base for all the containers, and incidentally benefit from caching and DRY.

Conceptually, it looks a bit like this:
```
find . -name Dockerfile
./base/Dockerfile
./db/Dockerfile
./front/Dockerfile
```

Now I can create and run `db` and `front` containers, and link them together, but I have built the `base` image separately. There is no `base` container.

Did I miss something?

**Comment by darkermatter** [comment]
I use the following pattern in project/docker-compose.yml. It seems to be working.
```yaml
mariadb:
  build: mariadb/
  volumes:
    - /etc/mysql
    - /var/lib/mysql
  ports:
    - "3306:3306"

django:
  build: django/
  command: /bin/true

app1:
  image: project_django
  links:
    - mariadb
    - django
  ports:
    - "8000"
```

**Comment by fruch** [comment]
@darkermatter 
+1 for the hack of using /bin/true
(but why does the app1 links django ?, it's a mistake ?)

**Comment by fruch** [comment]
@aanand 
look at: 
https://github.com/michaelsauter/crane
the provision command, can do that
I've seen people build up complex hierarchy of dockerfiles like that.

Yes using a private docker-registry might be more advisable solution, but I think this kind of pattern can have it's place
For it's lighter cases, or as a preparation stage to get the feeling of how the structure should look like before setting up registry with version and tags, and the whole shebang.

**Comment by darkermatter** [comment]
@fruch app1 is just an example of using the django image created. For instance app2 could have different volumes/db/ports, etc.

**Comment by darkermatter** [comment]
@fruch also, as fig/compose works out the dependencies, it makes sure that the django image is built before app1 in a fresh installation

**Comment by dnephin** [comment]
Related to #295, #610, #583

**Comment by dminkovsky** [comment]
@Dridi did you ever solve [this](https://github.com/docker/compose/issues/663#issuecomment-63995611), specifically:

> I build the base image using: docker build -t stuff/base base.

> The other images' Dockerfiles start with FROM stuff/base.

**Comment by Dridi** [comment]
From what I can remember from two-ish years ago, I tried to hack on fig to add a way to express dependencies between images but didn't manage to reliably do it because there were too many moving parts. Building the dependency graph by reading the FROM clause of the Dockerfiles was also feeling somewhat wrong.

Then my use case retired. By the time I was done with it my Makefile had been good-enough and I moved on to other work.

Looking at @darkermatter's workaround, it could work and help create the base image at the expense of creating a throwaway container. I'm not sure it would guarantee the image creation order. I haven't tried.

Sorry

**Comment by dminkovsky** [comment]
@Dridi I figured this was long ago, far away for you at this point :). Yeah, I just have a shell script that builds these base images. Definitely good enough.

Thank you!

**Comment by Luc45** [comment]
The newly added `--wait` flag in Docker Compose v2 is the way to go, but if you are stuck with docker-compose v1, this bogus service will achieve a similar result:

```
wait:
  image: hello-world:latest
  depends_on:
      some-container:
          condition: service_healthy
```
