### ISSUE TITLE
Prompt for missing variables interactively

### ISSUE THREAD

**Issue by Dzhuneyt** [docker/compose#6646]
While skimming through the documentation of [Terraform](https://learn.hashicorp.com/terraform/getting-started/variables), I observed a very interesting implementation to how they handle passing in variables (secret keys, passwords, whatever) which are NOT versioned into the terraform config which IS versioned.

Basically, you define a list of variables in a config file, similar to .env. An important difference here is that you can leave any of these variable's values EMPTY.

Whenever you run the actual `terraform apply` command (equivalent to `docker-compose up`), the CLI will ask you to fill any empty variables right inside the shell, in an interactive manner.

In contrast to Terraform, the `docker-compose up` command currently just fails if there are variables defined inside docker-compose.yml, without them being defined inside .env or passed inline to the "up" command (e.g. `$ BRANCH=develop docker-compose up`). I thought such interactivity like Terraform provides, would certainly make the Docker Compose CLI a bit more user-friendly.

**Comment by ulyssessouza** [comment]
Hello @Dzhuneyt.

I'm not that sure if this request would be a good thing to implement.
Keeping CI folk in mind, instead of failing and alerting the user immediately, that would hang asking for a variable.

WDYT @thaJeztah @rumpl @chris-crone ?

**Comment by thaJeztah** [comment]
At least, I think  the current behaviour should not change (to prevent breaking those use-cases)

**Comment by chris-crone** [comment]
Thanks for the suggestion @Dzhuneyt!

As @thaJeztah said, this would be a breaking change so we will not be able to implement it.
