### ISSUE TITLE
ERROR: Encountered errors while bringing up the project

### ISSUE THREAD

**Issue by dineshlt** [docker/compose#6648]
I'm getting the following error while trying to run docker-compose up:

`ERROR: Encountered errors while bringing up the project`

**Comment by jcsirot** [comment]
Hello @dineshlt Please could you give us more details on the errors (docker-compose and docker versions, minimum docker-compose.yaml triggering this error...). Do not hesitate the use the bug report template, it guides you through the process of submitting relevant information about the issue and help us to find the cause of the defect.
Thank you in advance.
