### ISSUE TITLE
can't open file [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by alshamari** [docker/compose#6651]
please help I deploying a small job in Jenkins and I got this error ??

+ python -u /Users/alshamari/re/application/api.py
python: can't open file '/Users/alshamari/re/application/api.py': [Errno 2] No such file or directory

here's my Jenkins file content >>

pipeline {
    agent any
    stages{
        stage ('clone'){
        steps{
            checkout scm
        }
    }
    stage ('bulid'){
        steps{

        sh "python -u /Users/alshamari/re/application/api.py"
        }
    }

}}

**Comment by ulyssessouza** [comment]
Hello @alshamari 
I will have to close this issue since I just don't see any relation with `docker-compose` in this.
