### ISSUE TITLE
Failed to build docker image on orc8r

### ISSUE THREAD

**Issue by mubashertnss** [docker/compose#6652]
Hi, when I am tring to build docker image using command # ./build.py. it ends up with below pasted error:

ERROR: Service 'test' failed to build: The command '/bin/sh -c for module in `find /gomod/src/modules -maxdepth 2 -mindepth 2 -type d` do cd ${module}/cloud/go && go mod download; done' returned a non-zero code: 2

**Comment by ulyssessouza** [comment]
Hello @mubashertnss ! 
Can you fill a proper [issue template](https://github.com/docker/compose/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) for this?

We need more information to figure out what is going on.

**Comment by ndeloof** [comment]
Closing as irrelevant. Compose doesn't provide any `build.py` file
