### ISSUE TITLE
Bug report: Docker volume bind fails on reboot

### ISSUE THREAD

**Issue by BenoitRanque** [docker/compose#6653]
### Background

I use nodemon and a folder binding to facilitate develoment of my nodejs server container.
I have confirmed the same problem when using just node.

### Bug description

Container crashes after docker reboot. Works fine first time `docker-compose up -d` is run.
Aparently this is due to docker not mounting a bind volume properly.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  docker-application:
    build:
      args:
        NODE_ENV: development
      context: C:\Users\BENOIT\Dev\docker-bug-test\docker-application
    command:
    - nodemon
    - -L
    environment:
      NODE_ENV: development
    restart: always
    volumes:
    - C:\Users\BENOIT\Dev\docker-bug-test\docker-application\src:/usr/app/src:ro
version: '3.6'
```

## Steps to reproduce the issue

1. Clone the bug report repo [here](https://github.com/BenoitRanque/docker-bug-test)
2. Run `docker-compose up -d` (docker will ask for permission to share drive if not granted already)
3. Run `docker ps` to get the container id
4. Run `docker logs -f <container id>` to view logs
5. Logs should look like this:
   ```
   [nodemon] 1.18.11
   [nodemon] to restart at any time, enter `rs`
   [nodemon] watching: *.*
   [nodemon] starting `node src/index.js`
   Listening on port 3000
   ```
6. Restart docker
7. Run `docker logs -f <container id>` to view logs
8. Logs now look like this:
   ```
   [nodemon] 1.18.11
   [nodemon] to restart at any time, enter `rs`
   [nodemon] watching: *.*
   [nodemon] starting `node src/index.js`
   Listening on port 3000
   [nodemon] 1.18.11
   [nodemon] to restart at any time, enter `rs`
   [nodemon] watching: *.*
   [nodemon] starting `node src/index.js`
   internal/modules/cjs/loader.js:584
       throw err;
       ^

   Error: Cannot find module '/usr/app/src/index.js'
       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
       at Function.Module._load (internal/modules/cjs/loader.js:508:25)
       at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
       at startup (internal/bootstrap/node.js:283:19)
       at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
   [nodemon] app crashed - waiting for file changes before starting...
   ```

### Observed result
   Aparently the bind is not mounting properly, causing the server to crash.
   Nodemon does not react to file changes like it should.
   And quite obviously the server does not start because node cannot find the file.

   Note we can confirm the package.json is begin read properly, as that is where we specify the entrypoint `src/index.js` that node cannot access.

   We also can confirm that docker is mounting _something_ at this point.
   If not, the local copy of the code would be used (the image copies the code locally when built).

### Expected result
   Server starts

#### Removing the bind

Solves the problem. Also defeats the purpose. Not a solution

#### Using an absolute path

I tried using an absolute path for the host folder
No change

#### Node versions

So far, I have tried the folowing nodejs versions: node:8-alpine, node:10-alpine, node:10
No change

### Stacktrace / full error message
   See reproduction steps above

## Additional information
   OS: Windows 10

**Comment by BenoitRanque** [comment]
Closing as this seems to be a docker for windows issue. Opening and [issue](https://github.com/docker/for-win/issues/3766) there

**Comment by CakozorusRex** [comment]
Hello, are you sure this is really a Windows related issue?
My colleague just ran into the same issue but on Mac OS Mojave, with the exact same version for both docker and docker-compose:
`docker-compose version 1.23.2, build 1110ad01`
`Docker version 18.09.2, build 6247962`

He was trying to start a MySQL container through docker-compose, with the exact same configuration we all run for month (at least 10 people).

The fix you gave above solved the issue.
We replaced: 
```
ports:
      - "3306:3306"
```
with:
```
ports:
      - "3306"
```
And it now works again, but it kinda breaks the purpose of binding.
Did you find another way to fix this permanently?

**Comment by alexislefebvre** [comment]
I think I had a similar issue: after rebooting the host, some containers failed to restart. It looks like Docker was started too son and the network stack was not available, so the container crashed.

I added this to the Docker service (in `/etc/systemd/system/multi-user.target.wants/docker.service` on Debian 11) and it worked again:

```
[Service]
ExecStartPre=/bin/sleep 30
```

[Source](https://stackoverflow.com/questions/43001223/how-to-ensure-that-there-is-a-delay-before-a-service-is-started-in-systemd/44737570#44737570).

This is strange since Docker should start only once the network is up:

```
[Unit]
[…]
After=network-online.target docker.socket firewalld.service containerd.service
Wants=network-online.target
```
