### ISSUE TITLE
[Feature Request] Use variables within env file

### ISSUE THREAD

**Issue by lonix1** [docker/compose#6658]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Use of variables within env file

**Additional context**
Often it's useful to be able to combine multiple variables in the env file. This makes the compose file much simpler and neater.

An example (from [here](https://github.com/docker/compose/issues/4878)) is:

````
HOME_DIR=/home/user
DOCKER_DIR="${HOME_DIR}/docker"
FOO_DIR="${HOME_DIR}/foo"
````

or

````
SERVICE=connection-foo-bar-baz-somehash
CONNECTION_FOO=http://${SERVICE}.foo.com/80/api/v1/service/
CONNECTION_BAR=http://${SERVICE}.bar.com/80/api/v1/service/
````

**Comment by funkyfuture** [comment]
but your titles says "environment variable" which `HOME_DIR` is not in the context of the host. so, the issue title is misleading.

**Comment by lonix1** [comment]
@funkyfuture Please edit the title as you think. I'm unsure how best to describe it - variables / variable expansion / nested expansion?

**Comment by Alfro** [comment]
+1 to this feature. :)

**Comment by razielanarki** [comment]
+1 for feature request

**Comment by snowmoonsoftware** [comment]
This would be useful for teams that develop on both Windows, Mac / Linux.

Here is what I'd like to be able to do to support my teams

`# Set the name of your aws profile. If you haven't named your profile, use Default.
# though you really should name the profile for the enviroment its used with.
AWS_PROFILE=waters-saas

# use these lines for linux/macos
MSFT_USERSECRETS=~/.microsoft/usersecrets
ASPNET_HTTPS_CERTS=~/.aspnet/https
AWS_CREDENTIALS=~/.aws/credentials

# use these lines for Windows
#MSFT_USERSECRETS=${APPDATA}/Microsoft/UserSecrets
#ASPNET_HTTPS_CERTS=${APPDATA}/ASP.NET/Https
#AWS_CREDENTIALS=${UserProfile}/.aws/credentials`

These variables are used in a docker-compose file to add volumes:
   volumes:
      - ${MSFT_USERSECRETS}:/root/.microsoft/usersecrets:ro
      - ${ASPNET_HTTPS_CERTS}:/root/.aspnet/https:ro
      - ${AWS_CREDENTIALS}:/root/.aws/credentials:ro

**Comment by roanosullivan** [comment]
+1 for feature request

**Comment by bersace** [comment]
[python-dotenv](https://pypi.org/project/python-dotenv/) implements this behaviour. Thus, pytest-dotenv and other projet relying on `python-dotenv` have this feature. So, a big :+1: for this feature.

**Comment by lonix1** [comment]
Not stale

**Comment by ulyssessouza** [comment]
Works on Docker Compose v1 and v2
