### ISSUE TITLE
A way to specifying optional containers

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [docker/compose#6660]
## Is your feature request related to a problem? Please describe.

We use `docker-compose` with PostgreSQL and Elasticsearch containers during the development process. On our `docker-compose.yml` file has 3 services: `postgres`, `elasticsearch` and `kibana`. The application uses only PostgreSQL and Elasticsearch. Kibana is used for debugging purpose and we need to use

```bash
docker-compose up -d postgres elasticsearch
```

every time if we don't want to run Kibana.

## Describe the solution you'd like

A key, which defines the container as optional in the `docker-compose.yml`, would be awesome. 

## Describe alternatives you've considered

Also, I didn't spend a great deal of time on this to search for a way to define optional containers; therefore, there is maybe a way to define it.

## Additional context

Here is the [`docker-compose.yml`](https://github.com/magara/magara/blob/master/docker-compose.yml) file that we use.

**Comment by ulyssessouza** [comment]
Hello @BerkhanBerkdemir.

From your own feature request you already provided one solution to your problem. Which is specifying the services you want and excluding the ones you don't.

Another possibility would be to extract `kibana` to another file and use like...
When running just PostgreSQL and Elasticsearch
```sh
$ docker-compose up -d
```

Then to bring up `Kibana`:
```sh
$ docker-compose -f docker-compose-kibana.yml up
```

And for running the 3 at the same time since the beginning:
```sh
$ docker-compose -f docker-compose.yml -f docker-compose-kibana.yml up
```

**Comment by montanaflynn** [comment]
When you have many services it's cumbersome to include them all just to exclude a single optional service.

**Comment by BerkhanBerkdemir** [comment]
I prefer `up -d postgres elasticsearch` over  `up -d -f docker-compose.yml -f docker-compose-kibana.yml`. Anyway. That was an idea that would be awesome if we can set an **optional** key.

Thank you for explanation, @ulyssessouza.
