### ISSUE TITLE
How to use compose file to run multiple applications in Jenkins ? 

### ISSUE THREAD

**Issue by manojmsrit** [docker/compose#6675]
I am just trying to create a single container for multiple applications. Currently my setup has multiple Docker files ( NUnit, MsBuild and SonarQube ) where i am using these docker files under Jenkins ( which is also running in a docker container ). Is it possible to build all these applications using Docker compose and run the applications such as ( NUnit, MSBuild and Sonarqube ) through Jenkins and if it is possible how the docker compose file looks alike ? Can you please suggest me regarding this

**Comment by jcsirot** [comment]
Hello @manojmsrit Thank you for your message. I am not sure to understand what you are trying to do. Can you give us more details about what you are building and what you want to run exactly.

**Comment by manojmsrit** [comment]
Hello @jcsirot Thank you for your response. Below is kind of my requirements, where my Docker file looks like as shown below.

(base) MANOJs-MacBook-Air:Projects manojdeshpande$ cat Dockerfile1 
FROM rschmitz/nunit3-console
COPY NewLibrary NewLibrary
COPY NewLibrary.sln NewLibrary.sln
RUN nuget restore NewLibrary.sln
RUN msbuild NewLibrary/NewLibrary.csproj
RUN nunit3-console  NewLibrary/NewLibrary.csproj

And I just want to build this Dockerfile in Jenkins using Docker-compose file , in other words, i want to see the results of the Tests run under Dockerfile in Jenkins . Is it possible to do ? If it is possible how will be the structure of docker-compose.yml file should looks like. ( Below is my current docker-compose.yml ) file and it is not working fine for me. Please suggest me regarding this.

version: '3'
services:
  jenkins_jobs:
    build: .
    ports:
     - "8080:8080"
     - "50000:50000"

  jenkins:
    image: "jenkins:latest"


My current design for this problem is , I have setup jenkins docker using official Jenkins image and inside Jenkins i have created jenkins job and multiple Dockerfiles ( as shown below ) and building them inside jenkins jobs.

Dockerfile.nunit1 
 
```docker
FROM rschmitz/nunit3-console
COPY NewLibrary NewLibrary
COPY NewLibrary.sln NewLibrary.sln
RUN nuget restore NewLibrary.sln
RUN msbuild NewLibrary/NewLibrary.csproj
RUN nunit3-console  NewLibrary/NewLibrary.csproj

```

Dockerfile

```docker
FROM mono:latest

RUN mono --version
ADD . /
RUN msbuild /t:restore kommmit.Offers/kommmit.Offers.Android/kommmit.Offers.Android.csproj

```

Below is the command which i am executing inside Jenkins job

docker build -t Dockerfile .
docker build -t Dockerfile.nunit1 .

Please suggest me regarding this. Hope i clearly mentioned the problem, please let me know if anything else details needed.

Regards,
Manoj
