### ISSUE TITLE
Feature Request: present environment variable COMPOSER_OPTS

### ISSUE THREAD

**Issue by sgohl** [docker/compose#6684]
Sometimes we're in the need for multiple docker-compose.yml files, while trying to simplify the daily usage of less experienced users, which leads me to the wish of being able to define multiple docker-compose.yml just like `COMPOSE_FILE`, but as an extension to that, append more command-line options to an environment variable, which docker-compose will read and inject at the `[options]` position (see usage):

```Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
```
.env
```
COMPOSE_OPTS="-f docker-compose.yml -f service-override.yml"
```

So every user can adjust the optional used compose.ymls where we can extend predeclared services, besides other options which are available on the cli.

This feature request comes as a workaround for not being able to extend nor include whole compose.ymls (considering network configuration), because just extending services is not enough. 

As an alternative, converting `COMPOSE_FILE` what is a string, to being a list, we just could simply define multiple files this way and it would not break any existing users, because the list just would 
 hold one entry:

```
COMPOSE_FILE="/www/docker-compose.yml /www/another-compose.yml"
```

This would (in terms of a workaround) satisfy also the requirements to being able to really override services, as far as I've experienced in my test. Because, docker-compose.override.yml 1) not really works as expected and 2) you can not have multiple.

**Comment by jcsirot** [comment]
Hello @port22 Thank you for the feature suggestion. We are going to evaluate it but note that any Pull Request implementing this feature would also be greatly appreciated.

**Comment by port22** [comment]
thanks for hearing! If I'd be capable of only half of what you're able to, believe me I'd write it straight and made a PR. But I'd pay if someone would do this.
I think this would "solve" multiple problems by just being able to set any options in the env file.
