### ISSUE TITLE
docker-compose build continue when errors shows even though I set -e in my bash environment

### ISSUE THREAD

**Issue by zffocussss** [docker/compose#6693]
Hi Team:
             I am using bitbucket+docker-compose+shell script to deploy services.
my work way is  docker-compose build && docker-compose up -d.
what I expect :
the above process is exited once some errors(abnormal) show s.

what it is actually:
I have some bad configuration to cause image built with error.I can see the errors explicit there.but the build show itself successful and continue to docker-compose up -d.

I hope it exited as actually errors are present.as it is a part of my deploying service on prod environment.I hope everything goes well and exit once any errors are born.

please help me.thanks.

**Comment by jcsirot** [comment]
Hello @zffocussss Thank you for your report. Please could you post a minimal Dockerfile and docker-compose.yml file which triggers the errors.

**Comment by zffocussss** [comment]
> Hello @zffocussss Thank you for your report. Please could you post a minimal Dockerfile and docker-compose.yml file which triggers the errors.

hi @jcsirot it is not about Dockerfile.I want to know how can I control the errors during docker-compose build.

**Comment by jcsirot** [comment]
So far I wasn't able to reproduce the issue. If the `docker-compose build` fails the return value is not 0 and the script should stop (of course it may depend on a lot of things in your script). Could you post the output of your script or the relevant part where the docker-compose is invoked?
