### ISSUE TITLE
Add --since and --until options to 'logs'

### ISSUE THREAD

**Issue by blah238** [docker/compose#6702]
For feature parity with the [`docker logs`](https://docs.docker.com/engine/reference/commandline/logs/) command, I'd like to be able to use the `--since` and `--until` options in [`docker-compose logs`](https://docs.docker.com/compose/reference/logs/).

I believe at least `--since` was [mentioned](https://github.com/docker/compose/issues/2227#issuecomment-410234649) in the now-closed #2227 but it apparently never made it into the checklist.

There is also a `--details` option in `docker logs` but I am not familiar with it and it may not be applicable to `docker-compose`. If someone wants it perhaps chime in here or open another issue?

**Comment by jcsirot** [comment]
Thank you @blah238 for opening the ticket. Indeed it would make the `logs` command more consistent with the `docker logs` options. We are going to evaluate this request but please do not hesitate to post a Pull Request if you want, we will ne happy to help you.

**Comment by theycallmemac** [comment]
@jcsirot if this is still open I'd be happy to take it on

**Comment by theycallmemac** [comment]
Hi @jcsirot just checking in - should this covertimestamps (e.g 2019-07-12T13:49:37) _and_ relative time (e.g. 37m)? Or should it just follow one format?

**Comment by aleon1220** [comment]
referred in this PR https://github.com/docker/compose/pull/7240
