### ISSUE TITLE
Docker Compose Hangs when launching > ~100 containers

### ISSUE THREAD

**Issue by tntpsu** [docker/compose#6705]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.0-rc1, build 0f3d4dda
docker-py version: 3.7.0
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client:
 Version:	18.03.0
 API version:	1.37
 Go version:	go1.9.7
 Git commit:	0f1bb35
 Built:	Wed Mar 20 14:21:52 2019
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.7
  Git commit:	708b068d3095c6a6be939eb2da78c921d2e945e2
  Built:	Wed Mar 20 14:21:02 2019
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
ersion: "2"
services:
  Application1:
    image: redis
    container_name: Ttestcontainer1
  Application2:
    image: redis
    container_name: Ttestcontainer2
  Application3:
    image: redis
    container_name: Ttestcontainer3
  Application4:
    image: redis
    container_name: Ttestcontainer4
  Application5:
    image: redis
    container_name: Ttestcontainer5
... this repeats to 100 container launches
```

## Steps to reproduce the issue

1. docker-compose up
2. You will see a couple containers with "done", then nothing else happens

### Observed result

# docker-compose up
Recreating Ttestcontainer17 ... 
Creating Ttestcontainer32    ... done
Creating Ttestcontainer121   ... done
Recreating Ttestcontainer12 ... 
Creating Ttestcontainer141   ... done
Recreating Ttestcontainer116 ... 
Creating Ttestcontainer19    ... done
Creating Ttestcontainer10    ... done
Creating Ttestcontainer101   ... done
Creating Ttestcontainer40    ... done
Recreating Ttestcontainer117 ... 
Creating Ttestcontainer34    ... done
Recreating Ttestcontainer118 ... 
Creating Ttestcontainer31    ... 
Recreating Ttestcontainer30  ... 
Recreating Ttestcontainer119 ... 
Recreating Ttestcontainer44  ... 
Creating Ttestcontainer31    ... done
Creating Ttestcontainer16    ... done
Creating Ttestcontainer35    ... done
Recreating Ttestcontainer17  ... done
Recreating Ttestcontainer27  ... 
Recreating Ttestcontainer117 ... done
Recreating Ttestcontainer46  ... 
Recreating Ttestcontainer12  ... done
Recreating Ttestcontainer119 ... done
Creating Ttestcontainer37    ... done
Recreating Ttestcontainer30  ... done
Creating Ttestcontainer33    ... done
Recreating Ttestcontainer99  ... 
Recreating Ttestcontainer27  ... done
Creating Ttestcontainer150   ... done
Recreating Ttestcontainer116 ... done
Creating Ttestcontainer140   ... 
Creating Ttestcontainer123   ... 
Recreating Ttestcontainer44  ... done
Recreating Ttestcontainer29  ... 
Recreating Ttestcontainer118 ... done
Creating Ttestcontainer54    ... 
Recreating Ttestcontainer59  ... done
Recreating Ttestcontainer1   ... 
Creating Ttestcontainer126   ... 
Creating Ttestcontainer50    ... 
Creating Ttestcontainer15    ... 
Creating Ttestcontainer8     ... 
Creating Ttestcontainer13    ... 
Creating Ttestcontainer28    ... 
Creating Ttestcontainer39    ... done
Creating Ttestcontainer128   ... 
Recreating Ttestcontainer43  ... 
Recreating Ttestcontainer20  ... 
Creating Ttestcontainer57    ... 
Creating Ttestcontainer41    ... 
Recreating Ttestcontainer47  ... 
Creating Ttestcontainer149   ... 
Ttestcontainer49 is up-to-date
Creating Ttestcontainer42    ... 
Creating Ttestcontainer14    ... 
Creating Ttestcontainer9     ... 
Creating Ttestcontainer148   ... 
Creating Ttestcontainer147   ... 
Creating Ttestcontainer139   ... 
Creating Ttestcontainer36    ... 
Creating Ttestcontainer11    ... 
Recreating Ttestcontainer18  ... 
Creating Ttestcontainer38    ... 
Creating Ttestcontainer51    ... 
Creating Ttestcontainer146   ... 
Creating Ttestcontainer56    ... 
Creating Ttestcontainer2     ... 
Creating Ttestcontainer55    ... 
Creating Ttestcontainer143   ... 
Recreating Ttestcontainer58  ... 
Creating Ttestcontainer145   ... done
Creating Ttestcontainer7     ... 
Creating Ttestcontainer145   ... 
Creating Ttestcontainer78    ... 
Creating Ttestcontainer104   ... 
Recreating Ttestcontainer23  ... 
Creating Ttestcontainer76    ... done
Creating Ttestcontainer102   ... 
Creating Ttestcontainer67    ... 
Creating Ttestcontainer112   ... 
Creating Ttestcontainer3     ... 
Creating Ttestcontainer138   ... 
Recreating Ttestcontainer95  ... 
Creating Ttestcontainer71    ... 
Recreating Ttestcontainer62  ... 
Creating Ttestcontainer142   ... 
Creating Ttestcontainer24    ... 
Creating Ttestcontainer21    ... 
Creating Ttestcontainer103   ... 
Creating Ttestcontainer88    ... 
Recreating Ttestcontainer113 ... 
Creating Ttestcontainer109   ... 
Creating Ttestcontainer73    ... 
Creating Ttestcontainer72    ... 

### Expected result
If i run on OSX, when i run over ~75 containers it hangs, on my linux box it is ~100... so the below example is running a small amount of containers to show what an expected result is

docker-compose -f 50containers.yml up -d
Creating network "root_default" with the default driver
Creating Ttestcontainer13 ... done
Creating Ttestcontainer41 ... done
Creating Ttestcontainer28 ... done
Creating Ttestcontainer26 ... done
Creating Ttestcontainer46 ... done
Creating Ttestcontainer33 ... done
Creating Ttestcontainer35 ... done
Creating Ttestcontainer18 ... done
Creating Ttestcontainer39 ... done
Creating Ttestcontainer9  ... done
Creating Ttestcontainer34 ... done
Creating Ttestcontainer24 ... done
Creating Ttestcontainer44 ... done
Creating Ttestcontainer17 ... done
Creating Ttestcontainer8  ... done
Creating Ttestcontainer38 ... done
Creating Ttestcontainer22 ... done
Creating Ttestcontainer31 ... done
Creating Ttestcontainer12 ... done
Creating Ttestcontainer2  ... done
Creating Ttestcontainer40 ... done
Creating Ttestcontainer21 ... done
Creating Ttestcontainer6  ... done
Creating Ttestcontainer32 ... done
Creating Ttestcontainer19 ... done
Creating Ttestcontainer25 ... done
Creating Ttestcontainer43 ... done
Creating Ttestcontainer3  ... done
Creating Ttestcontainer42 ... done
Creating Ttestcontainer10 ... done
Creating Ttestcontainer36 ... done
Creating Ttestcontainer37 ... done
Creating Ttestcontainer23 ... done
Creating Ttestcontainer49 ... done
Creating Ttestcontainer1  ... done
Creating Ttestcontainer15 ... done
Creating Ttestcontainer30 ... done
Creating Ttestcontainer14 ... done
Creating Ttestcontainer45 ... done
Creating Ttestcontainer27 ... done
Creating Ttestcontainer47 ... done
Creating Ttestcontainer4  ... done
Creating Ttestcontainer29 ... done
Creating Ttestcontainer5  ... done
Creating Ttestcontainer16 ... done
Creating Ttestcontainer48 ... done
Creating Ttestcontainer11 ... done
Creating Ttestcontainer50 ... done
Creating Ttestcontainer7  ... done
Creating Ttestcontainer20 ... done

### Stacktrace / full error message

```
There are no error messages, it just hangs
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

This happens on both my MAC and linux box

ID="poky"
NAME="Poky (Yocto Project Reference Distro)"
VERSION="2.5.2 (sumo)"
VERSION_ID="2.5.2"
PRETTY_NAME="Poky (Yocto Project Reference Distro) 2.5.2 (sumo)"

macOS

High Sierra - Version 10.13.6
docker-compose version
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016

**Comment by jcsirot** [comment]
Hello @tntpsu thank you for the report. We are going to investigate this issue.

**Comment by tntpsu** [comment]
Thank you, please let me know if you need more info.

In interim i just attached the docker-compose file used so you don't have to copy/paste to launch the same container multiple times (i had to rename the file to .txt as github doesn't support yml)

[150containers_test.txt](https://github.com/docker/compose/files/3178618/150containers_test.txt)

**Comment by DrGkill** [comment]
Can we reopen this ? I observe the same behavior.

**Comment by julianbrost** [comment]
Please reopen this, I also just ran into the same issue.

**Comment by Al2Klimov** [comment]
I seem to have this one as well.

**Comment by thearchitector** [comment]
I've also consistently run into this problem, and it's not CPU or OS related as I've tried on different bare-metal EC2 100+ vCPU EC2 instances, as well as physical machines. Would appreciate something -- it appears to spin up some, then get stuck

**Comment by bo-er** [comment]
I am having the same problem...
