### ISSUE TITLE
Docker \"restart policy\" --- 'order' parameter to start new and then stop old

### ISSUE THREAD

**Issue by AsaBeavers** [docker/compose#6709]
Looking at docker-compose reference for roll-back config and update config (https://docs.docker.com/compose/compose-file/#rollback_config), there is an argument called "order" using which can decide whether to start new container first or stop old container first. 

Looking for a similar feature for RESTART POLICY (https://docs.docker.com/compose/compose-file/#restart_policy) so that a new container can start first before stopping/exiting the old container.

**Comment by jcsirot** [comment]
Hello @AsaBeavers the RESTART_POLICY specifies how the container should restart _after_ it has been stopped (for any reason). Therefore there's no _order_ of restarting. Maybe the UPDATE_POLICY, which has the `order` option, is what you're looking for but it depends on your usecase.
