### ISSUE TITLE
docker-compose run/exec produces no output if stdin is closed

### ISSUE THREAD

**Issue by dms-cat** [docker/compose#6714]
## Description of the issue

Looks like a regression to #1092. I found that when running a `docker-compose` command in a Git pre-commit hook the command would output nothing, but running the command in an interactive shell I would receive the expected output.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.0, build 0aa5906
docker-py version: 3.7.2
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

**Output of `docker version`**
```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.6-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       481bc77156
  Built:            Sat May 11 06:10:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
Irrelevant, proprietary.

## Steps to reproduce the issue

1. Set up any Linux container
2. Run `docker-compose run --entrypoint=ls -T service-name <&-` or `docker-compose exec -T service-name ls <&-`

### Observed result

No output whatsoever.

### Expected result

The output should list the files.

## Additional information

Workaround: Make sure there is a TTY. In case of the Git hook, simply add `exec < /dev/tty` before the relevant command.

**Comment by ijc** [comment]
Thank you for your report, unfortunately I cannot reproduce this. I used:
```
$ cat docker-compose.yml
version: "2"
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./data:/docker-entrypoint-initdb.d
```
and after `docker-compose up -d` I find:
```console
$ docker-compose run --entrypoint=ls -T db <&-
bin
[...]
var
$ docker-compose run --entrypoint=ls -T db </dev/null
bin
[...]
var
$ docker-compose exec -T db ls <&-
bin
[...]
var
$ docker-compose exec -T db ls </dev/null
bin
[...]
var
$
```
This is with:
```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```
on
```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:59 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

Are you able to reproduce with any public images or only with your proprietary image?

**Comment by dms-cat** [comment]
Hm, turns out there's more complexity involved than I thought. It turns out closing stdin is only a problem *within an LXD container.* If I run the exact same command outside LXD it prints the `ls` output. I'll investigate a bit more and get back to you.

**Comment by ijc** [comment]
Thanks, my guess is that the issue is somewhere in that chain other than `docker-compose` itself but lets leave this open for now while you investigate.

Comparing `strace` traces for a good and bad case might be one way to gain some insight (i.e. change `lint-python.sh` to run `docker-compose` with a `strace -fff -tt -o /some/path/docker-compose.strace` prefix?

**Comment by souhaiebtar** [comment]
@dms-cat i run into same problem, i added  `-T` option to the command and now the file output contain data
```bash
docker-compose exec -T mysqldump -u root --password=asd1234& DB_cs > ../public/csDatabase.sql
```
