### ISSUE TITLE
COPY fails to persist on Windows

### ISSUE THREAD

**Issue by philastrophist** [docker/compose#6729]
## Description of the issue
Quite simple: the docker-compose configuration below does not allow any files to persist after running. So when I do docker exec -i -t aas-job-hunter_web_1 ls /app -alt, I see nothing.

Here is the (non-)working minimal example: https://github.com/philastrophist/test-docker

I'm on Windows 10, I've allowed mounted drives and enabled the TLS connection. I'm not sure what else to do. The thing that most confuses me is that requirements.txt is clearly copied over (since it installs it all) but it isn't there when I have a look docker exec.
https://stackoverflow.com/questions/56305187/docker-compose-is-not-copying-any-files

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:41:08 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  db:
    environment:
      POSTGRES_PASSWORD: hunter2
    image: postgres:9.6
    ports:
    - 5432:5432/tcp
  web:
    build:
      context: G:\PARENT_FOLDER
    links:
    - db
    ports:
    - 8000:8000/tcp
    volumes:
    - /g/PARENT_FOLDER:/app:rw
version: '2.0'
```

## Steps to reproduce the issue

1. `git clone https://github.com/philastrophist/test-docker`
2. `cd test-docker`
3. `docker-compose -f docker-compose.yml up --build --force-recreate`

### Observed result
No files copied to container 

### Expected result
Files copied to container

### Stacktrace / full error message

```
Building web
Step 1/6 : FROM python:3.6
 ---> 0668df180a32
Step 2/6 : COPY requirements.txt /app/requirements.txt
 ---> Using cache
 ---> 3073d0bef876
Step 3/6 : RUN pip install -r /app/requirements.txt
 ---> Using cache
 ---> 8ad63bbb3de5
Step 4/6 : COPY . /app
 ---> 16390cdd6c2c
Step 5/6 : EXPOSE 8000
 ---> Running in f628000e8961
Removing intermediate container f628000e8961
 ---> 80e6994cfbd2
Step 6/6 : CMD python website/manage.py runserver 0.0.0.0:8000
 ---> Running in acb6b25eb558
Removing intermediate container acb6b25eb558
 ---> da8876d78103
Successfully built da8876d78103
Successfully tagged aas-job-hunter_web:latest
Starting aas-job-hunter_db_1 ... done
Recreating aas-job-hunter_web_1 ... done
Attaching to aas-job-hunter_db_1, aas-job-hunter_web_1
db_1   | LOG:  database system was shut down at 2019-05-24 21:23:31 UTC
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
web_1  | python: can't open file 'website/manage.py': [Errno 2] No such file or directory
aas-job-hunter_web_1 exited with code 2
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Windows 10 - install CE edition

**Comment by thaJeztah** [comment]
You seem to be bind-mounting a directory from the host over the `app` directory in the container, so the directory you're bind-mounting is masking the files that you copied into the image;

```yaml
    volumes:
    - /g/PARENT_FOLDER:/app:rw
```

If you remove those lines, do you see the expected files?

**Comment by philastrophist** [comment]
Yes! I do! 

However, I'm following this guide; https://blog.jetbrains.com/pycharm/2017/08/using-docker-compose-on-windows-in-pycharm/ , where they use the volume mounting. This is so I can edit and then changes appear in the container. If I don't have this then I'll have to rebuild the image each time.

Is there a way to link my local disk to the container in this way?

**Comment by thaJeztah** [comment]
Bind-mounting should work (note that performance might not be ideal, because file sharing between the host and the VM in which docker runs adds some overhead, also, permissions/ownership between Linux and Windows doesn't translate well; so there are some limitations).

Did you check if your `G` drive is shared in the configuration panel? (see https://docs.docker.com/docker-for-windows/#shared-drives)

By default, only the `C` drive is shared between the Windows host and the VM. Based on your output, I suspect you are working from your `G` drive, which isn't shared by default. As a result, docker will create an empty `/g/` directory inside the VM and bind-mount that.

**Comment by ndeloof** [comment]
I tried to reproduce from your sample project and it just "works for me"
Please note I'm using latest Docker Desktop, maybe you should just try to upgrade

Also note Docker Desktop will ask you to authorize this bind mount, if you don't empty folder is to be expected.
