### ISSUE TITLE
how to make docker image

### ISSUE THREAD

**Issue by rishavjaiswal** [docker/compose#6731]
i have docker-compose.yml file with 3 node kafka cluster.Now how to make an image of that

**Comment by Jamie-** [comment]
You can't create an image containing multiple docker images. That's not how docker works.

Read the docs https://docs.docker.com/compose/overview/
> Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a YAML file to configure your application’s services. Then, with a single command, you create and start all the services from your configuration. To learn more about all the features of Compose, see the list of features.
