### ISSUE TITLE
how to install Docker Compose offline in SuSe 15 without internet 

### ISSUE THREAD

**Issue by milangt** [docker/compose#6734]
We are trying to install docker compose in a system SuSe 15 which dose not have internet connection. I want to download all packages and dependencies , push to the server and install they locally. can you please share the download links and install procedure.

**Comment by Jamie-** [comment]
https://docs.docker.com/compose/install/

Just download the file it tells you to on a different system which has internet.
```
wget https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
```

Copy it to your offline system, then rename it and make it executable.
```
mv docker-compose-Linux-x86_64 docker-compose
chmod +s docker-compose
```

**Comment by gbllopes** [comment]
After make executable, how i can execute it ?

**Comment by Jamie-** [comment]
`./docker-compose`

Or if you move the file to `/usr/local/bin` you can just use `docker-compose`
