### ISSUE TITLE
Is it possible to let env_file config supports load from url ?

### ISSUE THREAD

**Issue by lff0305** [docker/compose#6748]
For example,
```
web:
  env_file:
    - http://my-config-center/docker/web.env
```
I know there is some way to make it possible now (For example, map a local file to a remote file by some utility), but I think it would be great if it is supported by docker-compose.

**Comment by chris-crone** [comment]
Hi @lff0305,

Thanks for your request. Could you please expand on a use case for how you'd use this feature? That will help us think about how to handle the case and prioritise the work.

**Comment by lff0305** [comment]
Hi
The case is here: we have a few docker-compose instances. Now the .env file is put on each server / directory. When there is something to be update, the dev-ops must update each .env file on the servers separately.

So we would like to put the .env files on a web server (GitLab, or SpringCloud Config Server), and then docker-compose can load them from http://git-lab/.../web.env.

More over, with some server (Spring Could Config) for example, the hierarchy is supported. We can extract some common properties to a base env file, and then extend it to create each sub env files for each docker-compose instance.

Thanks.
