### ISSUE TITLE
want ports long syntax support species IP address like short syntax

### ISSUE THREAD

**Issue by Sherlock-Holo** [docker/compose#6753]
I write a docker-compose.yml and use ports with long syntax to expose services, like
```docker-compose
ports:
      - target: 53
        published: 127.0.0.1:53
        protocol: udp

      - target: 9253
        published: 127.0.0.1:9253
        protocol: tcp
```

when I run `docker-compose config` it will report **Error while attempting to convert service.dns.ports.published to appropriate type: "127.0.0.1:53" is not a valid integer**

If long syntax support sepices IP address, it will be great

**Comment by chris-crone** [comment]
Hi @Sherlock-Holo,

Thanks for the report. You are right that you currently cannot do this with the long port format. A couple of things raised by @thaJeztah about this:
- It would not work in orchestrated environments (i.e.: Swarm or Kubernetes)
- It would require a new field in the port spec

**Comment by imfms** [comment]
@chris-crone 

The long syntax can use [extension-fields](https://docs.docker.com/compose/compose-file/#extension-fields) directly. 
If long syntax support sepices IP address, it will be great.

```yaml
x-config:
- &publish-port "127.0.0.1:80"

...
ports:
  - target: 80
    published: *publish-port
```


Although Swarm or Kubernetes don't support, but short syntax was also. It's not a problem~

**Comment by thaJeztah** [comment]
> It would not work in orchestrated environments (i.e.: Swarm or Kubernetes)

There's a tracking issue for features that are not currently supported for swarm-mode / orchestrated environments here: https://github.com/moby/moby/issues/25303

And two issues about supporting `ip-address` when publishing ports (https://github.com/moby/moby/issues/26696, https://github.com/moby/moby/issues/32299)

> It would require a new field in the port spec

Yes, so apart from the above, this would also need some design choices, with things to consider about:

- would it only support ip-addresses, or also (e.g.) interface name (`eth0`) ?
- If both IPv6 and IPv4 is to be supported; a single field or multiple?
- (related to the previous); can it hold a single address, or multiple? (or should the format "keep it simple") and require multiple _ports_ to be specified - one for each ip-address for a port-mapping?

Using an extension field (`x-something`) that's only supported by docker compose, and marking it "experimental" _could_ be used to explore what works best.
