### ISSUE TITLE
Add new label com.docker.compose.projectfolder

### ISSUE THREAD

**Issue by thwr** [docker/compose#6757]
**Is your feature request related to a problem? Please describe.**
I'm planning a project that requires to know the folder of (or complete path to) the `docker-compose.yml` for any compose-controlled container on a host. 

**Describe the solution you'd like**
Ask you guys to add a new built-in label, e.g. `com.docker.compose.projectfolder`

**Describe alternatives you've considered**
This could also be archived by adding a label to every container, e.g. `my_fancy_label=$PWD`. But this is prone to (human) error if not using some orchestration / config management tool like puppet, chef, ansible, salt etc. 

**Additional context**
none, sorry

**Comment by thwr** [comment]
On a second (and third) thought, it makes more sense to me to provide the full path to the compose file itself or a second label  - one for the path, one for the file.

This should help if someone uses an alternate compose file name, like `docker-compose.yaml` or `compose.yml` or whatever else.

**Comment by chris-crone** [comment]
Hi @thwr,

Thank you for the suggestion. You can use environment variables in labels so if you are running `docker-compose up` from your project directory, the following would give you a label with the project directory:

```yaml
version: "3.7"
services:
        one:
                image: nginx
                labels:
                        - "com.example.project-dir=${PWD}"
```

```console
$ docker inspect sandbox_one_1
...
            "Labels": {
                "com.example.project-dir": "/tmp/sandbox",
...
```

I believe that would solve your issue?

**Comment by ndeloof** [comment]
docker-compose do set `com.docker.compose.project.working_dir` label for this exact purpose
