### ISSUE TITLE
Feature: Detach after blocking for minimum delay until assumed stable

### ISSUE THREAD

**Issue by nhooey** [docker/compose#6762]
One of the most common problems I encounter when bringing up containers in detached mode is that one of my containers encounters and error and quits, without me knowing about it until I realize much later, and manually check to find a stopped container.

An feature that would help with this problem would be a detached mode that behaves like undetached for a minimum delay until the container is assumed to be stable and continue running indefinitely.

So if you brought up a series of containers with this new option, you would see:
```
$ docker-compose up --detach --attach-for-n-seconds 10 c1 c2 c3
Starting c1 ... done
Starting c2 ... done
Starting c3 ... done
c1        | (Log output showing whatever c1 does...)
c2        | (Log output showing whatever c2 does...)
c3        | (Log output showing whatever c3 does...)
*** Detaching from c1 because it has been running without exit for 10 seconds ***
*** Detaching from c2 because it has been running without exit for 10 seconds ***
*** Detaching from c3 because it has been running without exit for 10 seconds ***
```
And if every container survived the specified timeout, the return code would be zero.

This could also be configured per-container in `docker-compose.yaml`.

What do you think?

**Comment by chris-crone** [comment]
Hi @nhooey,

Thanks for the idea. I can see how this would make debugging easier in some cases but I'm not sure this is the best way to solve the problem. We'll mull this over as a team and try to come back with something.

**Comment by mlanett** [comment]
I'd like to see this sort of feature, but have it be in the foreground until health check returns true, then detach.
