### ISSUE TITLE
Append a scale number at the tail of hostname

### ISSUE THREAD

**Issue by yukaary** [docker/compose#677]
It may be related to [626](https://github.com/docker/fig/issues/626).

Currently it looks that `fig` attach a hostname written in fig.yml when user specified a `hostname` attribute. So when I use `fig scale service=3` for some service(actually it's a rabbitMq), fig creates 2 new services, then these 3(1+2) services has a same hostname.

This becomes a bit problem in my case,
when service is a kind of building a cluster, I doubt same hostname may disturb a joining new node into the cluster.

In addition, I've noticed same hostname makes hard to resolve a name by DNS.
(I tried to run DNS with hostname-container's IP pair.)

From these reason, I rewrote some codes in fig like this.
[service.py](https://github.com/yukaary/fig/commit/6fceb92ebc3491b49350e3148b06ea6099ba3f08)

Is there any reason fig does not attach a scale number into a hostname, but an item name in `fig ps` list holds it?

**Comment by ioggstream** [comment]
This patch allows using  an %%id%% placeholder in hostname and command https://github.com/docker/compose/pull/1006

**Comment by jdmarshall** [comment]
We really need to get this fixed.  Every time you restart it increments the machine names by one.

If the argument is that you shouldn't count on the names (which I believe can by amply demonstrated to be a reasonable expectation) then why on earth does it overlap machine names between runs?  If you don't want people to use them then use random host names every time.  

As it stands now, every restart all but one of the cluster nodes come back up but I have to go reconfigure the whole thing to fix the off by one error.

**Comment by ioggstream** [comment]
@jdmarshall on #1131 there's a patch and a discussion about customizing hostnames with scale. We're trying to reach a consensus about the format for supporting the patch.

**Comment by Garito** [comment]
Hi!
Need this feature. Is it ready?

Thanks!

**Comment by aanand** [comment]
As I said in https://github.com/docker/compose/pull/1131#issuecomment-100299538, I don't think this is a good idea. I think the original problem of duplicate hostnames can be solved without introducing a dependency on scale numbers.

**Comment by Garito** [comment]
Then: how we need to solve this?
Is scale a good solution at all?

**Comment by aanand** [comment]
Looks like I misread this issue. I think @bfirsh's suggestion - switch to using hyphens in container names, and then set the hostname to the same value as the container name - is nice and simple, and will work fine even if we stop using sequential scale numbers.

However, if we ever let people set custom container names, we'll have to think once again about the disparity between what's allowed in a hostname and what's allowed in a container name (e.g. underscores, uppercase letters(?)), and how to deal with the case where the container name isn't a valid hostname.

Perhaps, if the user wants to set a custom container name that isn't a valid hostname, we should make them set a hostname as well.

**Comment by aanand** [comment]
Thinking about it - what's wrong with just not specifying the hostname, if you don't want duplicates? You'll get a generated one based on the ID of the container, which is more or less guaranteed to be unique.

**Comment by Garito** [comment]
Yeah but, for instance, a MongoDB replica set needs to register the servers that are part of the set
We have two options here: register the container id everytime that the container starts or fix the name of the node

So, how to solve this?

**Comment by aanand** [comment]
Sorry, could you explain that in more detail? How does the registration process work, and what exactly is wrong with using the container ID?

**Comment by Garito** [comment]
Check this out:
http://docs.mongodb.org/manual/tutorial/deploy-replica-set/

**Comment by jdmarshall** [comment]
Many load balancing solutions need to know the connection information for all of the machines they work with, such as nginx.  As do a number of Continuous Integration servers (to talk to their slaves).  I'm having problems with both.  The latter in 'production', the former in dev and test environments where I'm using docker to simulate configurations that look like staging and production.

**Comment by dnephin** [comment]
You normally wouldn't use the internal host name for those situations. As far as I know, those hostnames aren't available to anything outside of the host anyway. It sounds like what is needed here is more likely some form of service discovery.  There are already many options out there that work with docker.
Using links may work if you set it up correctly, and the new docker networking will make it even easier.

It's pretty likely that we'll actually be removing the scale numbers entirely, see #1516, so I'm going to close this issue.

**Comment by teodorescuserban** [comment]
> You normally wouldn't use the internal host name for those situations. As far as I know, those hostnames aren't available to anything outside of the host anyway. It sounds like what is needed here is more likely some form of service discovery. There are already many options out there that work with docker. Using links may work if you set it up correctly, and the new docker networking will make it even easier.
> 
> It's pretty likely that we'll actually be removing the scale numbers entirely, see #1516, so I'm going to close this issue.

famous last words 😁
