### ISSUE TITLE
Feature: Attach to an already running container via service.

### ISSUE THREAD

**Issue by collin5** [docker/compose#6775]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to attach to an already running container using compose.
At the moment, we have to list the running containers with `docker ps` then `docker attach` using the container id.

**Describe the solution you'd like**
To have something like
```bash
$ docker-compose attach <service_name>
```

**Comment by jamescostian** [comment]
Adding a comment to make this issue not go stale

**Comment by collin5** [comment]
Not stale

**Comment by collin5** [comment]
not stale 🙁
