### ISSUE TITLE
Python multithreading process not working

### ISSUE THREAD

**Issue by b00lpy** [docker/compose#6783]
## Description of the issue

I've built an image with and entrypoint `.sh` file. This file cd into a path and calls a python script which is basically a process split in two parallel threads. One is a rest api and the other is a script which interacts with another API.

## Context information (for bug reports)
Running the image with `docker run -it imagename:tag` I've got the right behaviour of the script, 
And the terminal shows up the outputs of these 2 threads.

Running this image inside a docker-compose only one of these threads starts, in particular the rest api.
If I try to interact with that in order to activate the features of the second one i can't see any output or interactions.

How can I fix this behavior?

**Comment by hholst80** [comment]
That sounds like a buffering issue between the two ways of invoking your script. Try spawning the python with `python -u script.py` and see if your output is consistent between the two invocations. 

Do you have an exact repro we could look into?

**Comment by lolwat97** [comment]
I'm having the exact same issue right now.
I have a process that spawns a Flask server via waitress, and one additional process (let's say that it refreshes tokens etc.).
Launched with docker run - works as expected, with both processes' stdout visible.
With docker-compose it does not behave that way, only the main process is visible.
Launching with -u does not affect this.

**Comment by LenaTevar** [comment]
Similar issue here. 
Running a Flask api, using Threads. When using docker-compose, it only runs the API, not the threads.

**Comment by TonGarcia** [comment]
> Similar issue here. Running a Flask api, using Threads. When using docker-compose, it only runs the API, not the threads.

Did you guess any solution?

**Comment by ch-hristov** [comment]
> > Similar issue here. Running a Flask api, using Threads. When using docker-compose, it only runs the API, not the threads.
> 
> Did you guess any solution?

Did you guys get any solutions :)

**Comment by TonGarcia** [comment]
> > > Similar issue here. Running a Flask api, using Threads. When using docker-compose, it only runs the API, not the threads.
> > 
> > 
> > Did you guess any solution?
> 
> Did you guys get any solutions :)

Yes. I fixed it on my end. Just like that:
```python
if __name__ == "__main__":
    FLASK_PORT = os.environ.get('FLASK_PORT')
    port = FLASK_PORT if FLASK_PORT is not None else 5000
    threading.Thread(target=lambda: app.run(port=port, debug=False, use_reloader=False, host='0.0.0.0')).start()
```
