### ISSUE TITLE
Classifier for Python 3.5 missing in setup.py

### ISSUE THREAD

**Issue by CMeza99** [docker/compose#6787]
## Description of the issue
Classifier for Python 3.5 missing in setup.py

## Context information (for bug reports)
Python 3.5 seems to satisfy the `python_requires` line in `setup.py`

**Output of `docker-compose version`**
Commit `3d693f3`

**Comment by ulyssessouza** [comment]
The point here is that `docker-compose` was never tested with Python 3.5
So based in this fact, adding this line would assure that it works but we've never tested against it.
