### ISSUE TITLE
Misleading error content.

### ISSUE THREAD

**Issue by gothrek22** [docker/compose#6794]
# Description of the issue

Misleading error is thrown when invalid value is set for the image field of a service. In my case I've cobbled up the value of DOCKER_IMAGE env var from different places automagically in jenkins, but due to input error it was in prefixed with the protocol (https://). This causes failure to build, which is ok. But the error even on debug levels thrown is that it couldn't connect to docker. 

## Context information (for bug reports)

**Output of `docker-compose version`**
docker-compose version 1.24.1, build 4667896
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

**Output of `docker version`**
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:26:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false

## Steps to reproduce the issue

1. Set image field in docker-compose.yml to a variable f.e. "${DOCKER_IMAGE}"
2. Set DOCKER_IMAGE env var to an url f.e. http://totally.legit.repository/image:latest
3. Try to run `docker-compose build`

### Observed result

You will get the following error:
`Couldn't connect to Docker daemon at http+docker://localhost - is it running?`

### Expected result
You should get a validation error

## Additional information

Fedora 30, fresh install, used pip3 to install docker-compose.

**Comment by gothrek22** [comment]
Found another case of misleading error. Not sure if this should be another bug. If in any case the image name has upper case values, docker-compose fails with the same result as the above. It seems that any fail in validation of this field ends with the wrong error.

**Comment by gothrek22** [comment]
Seems any validation error in the image field ends up with the wrong error. Probably due to no client side validation (my guess).

**Comment by GregYeo** [comment]
I has had similar problem with you. By the message, i did a lot meaningless tries.

# Reproduce

## Files
```yaml
# Filename: docker-compose.test.yml
version: "3.4"
services:
  app_build:
    image: com.test:${APPLICATION_VERSION}-build
    # No problem with below line
    # image: com.test:${APPLICATION_VERSION}build
    # But If tag starts with special character(The hyphen is here), it occurs
    build: 
      context: .
      dockerfile: DockerfileTest
```
```Dockerfile
# Filename: DockerfileTest
FROM ubuntu:18.04
```

## Command - situation of problem
```bash
unset APPLICATION_VERSION
docker-compose -f docker-compose.test.yml build app_build  

WARNING: The APPLICATION_VERSION variable is not set. Defaulting to a blank string.
Building app_build
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

## Command - situation of no problem
```bash
export APPLICATION_VERSION=1234
docker-compose -f docker-compose.test.yml build app_build  

Building app_build
Step 1/1 : FROM ubuntu:18.04
18.04: Pulling from library/ubuntu
2746a4a261c9: Pull complete
4c1d20cdee96: Pull complete
0d3160e1d0de: Pull complete
c8e37668deea: Pull complete
Digest: sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
Status: Downloaded newer image for ubuntu:18.04
 ---> 549b9b86cb8d

Successfully built 549b9b86cb8d
Successfully tagged com.test:1234-build
```

When docker-compose can not parse image name properly, It does not provide proper validation but it downs with critical message.

I am not handling it now but i think validator or parser of docker-compose has the problem.

**Comment by GregYeo** [comment]
## Test environment
```
docker-compose -v
docker-compose version 1.24.1, build 4667896b

docker -v
Docker version 18.09.9-ce, build 039a7df

uname -a
Linux ip-172-31-20-89.ap-northeast-1.compute.internal 4.14.158-129.185.amzn2.x86_64 #1 SMP Tue Dec 24 03:15:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ndeloof** [comment]
I tried to reproduce this error running latest docker-compose (1.25.1) and engine (19.03.3) :


```
➜  docker-compose build app_build
WARNING: The APPLICATION_VERSION variable is not set. Defaulting to a blank string.
Building app_build
ERROR: invalid reference format
```

Not sure when this has been fixed, but I assume this issue is not relevant anymore

**Comment by maksym-bordun-ynd** [comment]
Originally described issue with e.g. `http://totally.legit.repository/image:latest` image can still be reproduced with docker-compose 1.27.4.
