### ISSUE TITLE
Don't require the presence of docker-compose.yml while specifing project name

### ISSUE THREAD

**Issue by ProteanCode** [docker/compose#6801]
There is a command that serves to put a project down

> docker-compose down

There is a case when I removed the whole project directory but docker containers are still up and running so I would rather type

> docker-compose --project-name dev down -v

but I still need a docker-compose.yml file to do that, literally any docker-compose.yml file works even from other projects.

This is half-a-bug half-a-feature to support 
> docker-compose --project-name dev down -v

without using docker-compose.yml file

**Comment by ndeloof** [comment]
Sounds legitimate to me. Unfortunaltey not trivial from a codebase architecture point of view, but to be considered.
