### ISSUE TITLE
docker-compose build --parallel doesn't seem to respect depends_on

### ISSUE THREAD

**Issue by giorgiosironi** [docker/compose#6802]
## Description of the issue

`docker-compose build --parallel` seems not to fully respect `depends_on` as `docker-compose build` does, hence services that extend another service cannot rely on the parent image to be available in a `FROM`.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**

(see linked gist)

## Steps to reproduce the issue

Execute the commands in https://gist.github.com/giorgiosironi/e7ecfbaa30d8117902fc4abb7004da86

This is not totally deterministic as it's a race condition, so may need multiple runs passing in a new value of `IMAGE_TAG` to avoid reusing older images.

### Observed result

`FROM` in service `b` doesn't find the image to extend produce by the build of service `a`.

### Expected result

`b` should wait building until the image from `a` is available.

### Stacktrace / full error message

(see linked gist)

**Comment by ndeloof** [comment]
`depends_on` is designed for service execution, not build process.
if you have multiple services relying on a common docker base image, better use a multi-stage Dockerfile and invoke distinct [target](https://docs.docker.com/compose/compose-file/#target)s per service, doing so engine will mutualize the shared image build. This is especially efficient if you use BuildKit by setting `COMPOSE_DOCKER_CLI_BUILD=1`.
