### ISSUE TITLE
should we add autocomplete? 

### ISSUE THREAD

**Issue by zgfh** [docker/compose#6809]
**Is your feature request related to a problem? Please describe.**
should we add autocomplete for compose? it will be easy to use
eg: if we want exec some service, it can tab all service

**Comment by shin-** [comment]
Tab completion for `zsh` and `bash` is available [here](https://github.com/docker/compose/tree/master/contrib/completion).

**Comment by zgfh** [comment]
@shin- thanks a lot.
 is there have a docs or command `docker-compose completion -h`?

**Comment by ulyssessouza** [comment]
No, because it's just the completion on `docker-compose` options, which are already documented

**Comment by zgfh** [comment]
sorry , my fault , find docs :https://docs.docker.com/compose/completion/
