### ISSUE TITLE
curl doesn't work - File not found.

### ISSUE THREAD

**Issue by DarylGraves** [docker/compose#6810]
I am trying to install Docker-Compomse on Raspbian but the below doesn't work but is in all the documentation (sometimes with a `, othertimes with a $)

> curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

All I get is a file with "Not Found "as the contents. I've also tried going directly to that site in a browser but just get a "404 page not found" style error. 

I was wondering if I'm meant to replace the "$uname" with something my github username but everywhere I've seen this documented, this is never clarified.

Edit: Github is breaking the URL a bit but the full unedited link can be found [here](https://docs.docker.com/compose/install/)

**Comment by ulyssessouza** [comment]
This is due to your arch `docker-compose` is not released for ARM. For now you can use and alternative installation or build it yourself
