### ISSUE TITLE
ERROR: invalid volume specification:

### ISSUE THREAD

**Issue by justusongera2** [docker/compose#6811]
PS C:\Users\justus.ongera\Desktop\Docker Exercises\backend> docker-compose up
Creating mongo ... error

ERROR: for mongo  Cannot create container for service mongo: b'invalid volume specification: \'/host_mnt/c/Users/justus.ongera/Desktop/Docker Exercises/backend/data:-/data/db:rw\': invalid mount config for type "bind": invalid mount path: \'-/data/db\' mount path must be absolute'

ERROR: for mongo  Cannot create container for service mongo: b'invalid volume specification: \'/host_mnt/c/Users/justus.ongera/Desktop/Docker Exercises/backend/data:-/data/db:rw\': invalid mount config for type "bind": invalid mount path: \'-/data/db\' mount path must be absolute'
ERROR: Encountered errors while bringing up the project.

**Comment by ulyssessouza** [comment]
Could you please provide more information by filling out the questions of the [issue template](https://github.com/docker/compose/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?
