### ISSUE TITLE
Tags :alpine, :debian and :latest

### ISSUE THREAD

**Issue by LuisEnMarroquin** [docker/compose#6820]
Would be great to have these tags to get the last image of each distro.
```shell
docker pull docker/compose:latest
docker pull docker/compose:alpine
docker pull docker/compose:debian
```

**Comment by jcsirot** [comment]
Hello @LuisEnMarroquin Thank you for your ticket. Please could you be more precise about the issue you encountered? Please could you also use the issue templates; it helps us a lot to quickly handle and reply to tickets.

**Comment by clemenspeters** [comment]
if you just run `docker pull docker/compose` it is _Using default tag: latest_ and then gives you the error _Error response from daemon: manifest for docker/compose:latest not found: manifest unknown: manifest unknown_. This is why I agree with @LuisEnMarroquin that it would be great to have a **latest** tag.

**Comment by LuisEnMarroquin** [comment]
With other images you can just pull `mongo:latest` and it gets the latest version.

**Comment by DmitriySafronov** [comment]
we still need tag "latest"

**Comment by LuisEnMarroquin** [comment]
Now `latest` tag exists. Thank you, great and very light weight image
