### ISSUE TITLE
Is there a way to redirect docker-compose output to a log file

### ISSUE THREAD

**Issue by rom-stratoscale** [docker/compose#6821]
I'm interested in docker-compose output (log.info, log.warning) and not in containers output.
We're executing docker-compose commands via systemd and since the output is missing, we cannot use -d flag and have to keep the compose process up.

**Comment by jcsirot** [comment]
Hello @rom-stratoscale For any questions regarding docker compose usage please could you post your question in the dedicated forum here: https://forums.docker.com/c/open-source-projects/compose

**Comment by dhpalan** [comment]
@romfreiman I am exactly looking for the same. Did you find out how?
