### ISSUE TITLE
Cannot execute by pasting multiple lines

### ISSUE THREAD

**Issue by yutakatay** [docker/compose#6824]
## Description of the issue

I want to create a script containing docker-compose exec. And I want to use by copying and pasting multiple lines. But the paste is only one line.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 0aa5906
docker-py version: 4.0.2
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client:
 Version:           19.03.1-ce
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Sat Jul 27 21:08:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.1-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.7
  Git commit:       74b1e89e8a
  Built:            Sat Jul 27 21:08:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.7.m
  GitCommit:        85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  db:
    environment:
      POSTGRES_PASSWORD: example
    image: postgres
    restart: always
version: '3.1'
```

## Steps to reproduce the issue

1. touch /tmp/test.sh && chmod +x /tmp/test.sh && vi /tmp/test.sh
```
#!/bin/bash

docker-compose exec -T db $1                 ### 1 ###
#docker exec downloads_db_1 $1               ### 2 ###
```

2. copy & paste multiple lines to terminal
```
/tmp/test.sh ls
/tmp/test.sh pwd
```

### Observed result

It only executes `/tmp/test.sh ls`.

### Expected result

I want two lines to execute
docker exec(Above script  `### 2 ###`) executes two lines.

## Additional information

OS: ArchLinux
Install method: pacman -S docker-compose

**Comment by jcsirot** [comment]
Hello @yutakatay Could you provide us more details. How do you invoke test.sh ls and test.sh pwd? From another shell script? 
You can also post your questions on the docker compose forum https://forums.docker.com/c/open-source-projects/compose

**Comment by yutakatay** [comment]
I created gif animes

### docker-compose 

![not-execute-by-paste](https://user-images.githubusercontent.com/8683947/62182731-acf75c00-b392-11e9-861b-e27316f2a1f4.gif)

### docker 

![execute-by-paste-using-docker](https://user-images.githubusercontent.com/8683947/62182764-cc8e8480-b392-11e9-8a93-d08d7c522887.gif)

**Comment by ulyssessouza** [comment]
That works by running:
```shell
./test.sh ls && ./test.sh pwd
```
Or in 2 lines:
```shell
./test.sh ls && \
./test.sh pwd
```

**Comment by yutakatay** [comment]
Yes, But I want to use it as a shellscript. 
This sample is a simple case. There are still more lines after that. So I cannot write in one line.

**Comment by ulyssessouza** [comment]
So if you write a file, let's say `all.sh` containing:
```sh
/tmp/test.sh ls
/tmp/test.sh pwd
```

Then
```sh
chmod +x all.sh
./all.sh
```

That works just fine.

**Comment by yutakatay** [comment]
It looks fine. But I don't want to write a file. I want to use a clipboard.
Because I want to record the command history in `bash_history` or `script command`.
If I make a shellscript, I will not immediately know what parameters were executed.

Why does input from the clipboard stop? If it doesn't stop like when using Docker, my problem will be closed.
