### ISSUE TITLE
An iterator available in docker-compose?

### ISSUE THREAD

**Issue by chrislombardo** [docker/compose#6829]
I am using docker-compose 3.4 healthcheck to test network connectivity between two network segments. I have iperf running in server mode within containers on one host and iperf in client mode within containers on a different host. Here is sample docker-compose healthcheck configuration on the client side:
```
healthcheck:
    test: iperf3 -V --logfile iperf3_client_log -c 172.29.128.8 -p 5200
    interval: 60s
    timeout: 40s
    start_period: 5s
    retries: 1
```
Each client container starts and connects to a different iperf server port (i.e. 5200-5209). This is easy enough if I create each container as a separate service within my compose file and hard code the port, however, that isn’t very scalable. I’d like to be able to pass healthcheck something like:
```
iterator: 5200-5209
test: iperf3 -V --logfile iperf3_client_log -c 172.29.128.8 -p $iterator
```
and have docker-compose iterate through the port numbers exactly like it does if I specify a port range using the “ports” configuration option when issuing --scale with my “up” command.  Please understand that the "ports" config option will NOT work for this usecase as I am not mapping external port numbers to a container ... simply choosing the port which iperf will use during it's run.

Same question posted by me in forums.docker: https://forums.docker.com/t/an-iterator-available-in-docker-compose-3-4/79049
Another example of user desire for an iterator:
https://forums.docker.com/t/pass-incremental-variable-to-cmd-for-each-scaled-service-in-docker-compose/16371
I am aware that a similar [request](https://github.com/docker/compose/issues/5189) was turned down in reference to container_name, but I believe I've proven the need for an iterator/incrementor outside of naming a container.

**Comment by jeremyhamm** [comment]
@chrislombardo Did you ever find a solution for this?  I need the same functionality.

**Comment by chrislombardo** [comment]
@jeremyhamm Sorry, I did not.  I ended up going a different route where the iterator wasn't necessary.

**Comment by jeremyhamm** [comment]
@chrislombardo No worries thanks for the response.  I think I will need an out of the box solution to my issue as well

**Comment by ndeloof** [comment]
Can't you just design a healthcheck script which will implement iterator as a shell script loop?
```yaml
healthcheck:
    test: healthcheck.sh 5200 5209
``` 

```bash
#!/bin/bash
for port in $0..$1
do
  iperf3 .....
done
```
