### ISSUE TITLE
Release docker/compose image for armv7 / arm64v8

### ISSUE THREAD

**Issue by maruel** [docker/compose#6831]
**Is your feature request related to a problem? Please describe.**

Using `curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" > docker-compose`
fails on Raspbian as described in issue #6810.

The root causes are:

- https://github.com/docker/compose/releases only contain releases for amd64 / x64-64.
- https://hub.docker.com/r/docker/compose is not multi-arch enabled.

While issue #6810 was closed, I think this is a genuine feature request since instructions at https://docs.docker.com/compose/install/#install-as-a-container are not clear about which platforms are _officially_ supported to run docker-compose as a container.

Two recent events may now make this worth:

- The new RPi4 has real 1Gbit ethernet. It becomes a real platform for hobbyist with limited linux experience using Raspbian to host images. 
- Docker Hub has real native support for multi-arch images via [manifest v2](https://docs.docker.com/registry/spec/manifest-v2-2/).

Combined with the fact that docker-compose is a *core building block for orchestrating images*, the lack of support on arm v7 (32 bits) and v8 (64 bits) makes the bootstrapping process options more limited than on x86 equivalent and the documentation is not clear about which options work where.

As stated at https://github.com/docker/compose/issues/4733#issuecomment-294021065, there _used_ to be a Dockerfile.armhf. This file was deleted in #6666 by @joakimr-axis since the current one works just fine.

**Describe the solution you'd like**

Officially create armv7 and arm64v8 docker images to https://hub.docker.com/r/docker/compose as part of the release process.

This is essentially a process change, not a code change, since the Dockerfile is known to work on arm already. This would involve at the very least updating [.circleci/config.yml](https://github.com/docker/compose/blob/master/.circleci/config.yml).

**Describe alternatives you've considered**

Installing via `pip` works in the meantime but is trickier to run this process successfully for new comers with limited linux experience, especially that the documentation is misleading about what is supported and what is not. This leads to a poor user experience (UX).

**Comment by webash** [comment]
As a new user to Docker, hoping to make my Raspberry Pi 4 the test ground for learning Docker, this stumbling block has been impossible to get past. Every tutorial uses docker-compose and the fact that it seems impossible to obtain easily has wasted hours of my time.

There is no clear reason why this isn't the case. It should at least be called out in the installation documentation in the meantime.

**Comment by nemchik** [comment]
@webash I'm sorry to hear you've had troubles installing compose. You should be able to do it pretty easily by installing `python3` and `python3-pip` first and then running `python3 -m pip install -IU docker-compose`.

If you have further issues feel free to reach out via my contact info on my GitHub profile since this isn't really a support thread.

That being said I'm subscribed here hoping to see any kind of movement in this happening. I'd love to he able to run compose from docker on ARM. It works great on x86_64.

**Comment by webash** [comment]
Python dependencies and the share number of them for `docker-compose` is a crime to install directly on a machine where containers will be used; so I ended up following [these instructions](https://www.berthon.eu/2019/revisiting-getting-docker-compose-on-raspberry-pi-arm-the-easy-way/) for getting a `docker-compose` container spun up on the Raspberry Pi.

**Comment by nemchik** [comment]
Interestingly those instructions use a Dockerfile from this very repo. I'm pretty sure all we're asking for is an `armhf` tag on docker hub. Maybe a multiarch manifest if the devs are feeling fresh 😉

**Comment by joakimr-axis** [comment]
Yes, multiarch would surely be the contemporary way.

**Comment by Ivan61** [comment]
I try to build it on my Raspberry Pi 3 Model B Rev 1.2 with Raspbian10 (buster).

```
pi@raspberrypi:~ $ git clone https://github.com/docker/compose.git
pi@raspberrypi:~ $ cd compose/
pi@raspberrypi:~/compose $ git checkout -f 1.25.0
pi@raspberrypi:~/compose $ sudo docker build -t dockercompose:1.25.0 .
pi@raspberrypi:~ $ sudo curl -L --fail https://github.com/docker/compose/releases/download/1.25.0/run.sh -o /usr/local/bin/docker-compose
pi@raspberrypi:~ $ sudo chmod +x /usr/local/bin/docker-compose
pi@raspberrypi:~ $ sudo sed -i 's/docker\/compose:$VERSION"/dockercompose:$VERSION"/g' /usr/local/bin/docker-compose

```

**Comment by Ivan61** [comment]
@webash 

I had built it on my Raspberry Pi 3 Model B Rev 1.2 with Raspbian10 (buster) [arm/v7].
You can try to do it on your Raspberry Pi 4.
```
pi@raspberrypi:~ $ git clone https://github.com/docker/compose.git
pi@raspberrypi:~ $ cd compose/
pi@raspberrypi:~/compose $ git checkout -f 1.25.0
pi@raspberrypi:~/compose $ sudo docker build -t dockercompose:1.25.0 .
pi@raspberrypi:~ $ sudo curl -L --fail https://github.com/docker/compose/releases/download/1.25.0/run.sh -o /usr/local/bin/docker-compose
pi@raspberrypi:~ $ sudo chmod +x /usr/local/bin/docker-compose
pi@raspberrypi:~ $ sudo sed -i 's/docker\/compose:$VERSION"/dockercompose:$VERSION"/g' /usr/local/bin/docker-compose
pi@raspberrypi:~ $ sudo docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

I have the following images after `docker build`.
```
pi@raspberrypi:~ $ sudo docker images
REPOSITORY          TAG                     IMAGE ID            CREATED              SIZE
dockercompose       1.25.0                  9272a0512c9e        16 seconds ago       56.6MB
<none>              <none>                  d4b17be57ec2        About a minute ago   470MB
<none>              <none>                  a164b2c19a32        31 minutes ago       306MB
python              3.7.4-slim-stretch      c8a29540aa80        2 months ago         112MB
python              3.7.4-alpine3.10        6fcdf3f2e43b        2 months ago         76.6MB
debian              stretch-20190812-slim   9e643d1c5544        4 months ago         41.5MB
docker              18.09.7                 1661b80f3a8a        5 months ago         140MB
alpine              3.10.1                  962e8b19ad7b        5 months ago         3.74MB
```

The executable docker-compose binary file is inside `dockercompose:1.25.0` and `alpine:3.10.1` is the base image of `dockercompose:1.25.0`. The other images are useless anymore. You can delete them.

And Don't try to copy it to Raspberry Pi and use it directly. Because it depends on other shared library inside `dockercompose:1.25.0`. 

It takes 40mins to build it on my Raspberry Pi 3. I had uploaded it to my docker-hub. If anyone want to use it on Raspberry Pi 3(arm/v7),  please refer [here](https://github.com/AppTower/docker-compose).

**Comment by nemchik** [comment]
https://hub.docker.com/r/linuxserver/docker-compose

Hopefully this helps anyone waiting for an official response.

**Comment by JonahGroendal** [comment]
`sudo apt install docker-compose` works but it installs an older version (currently 1.25.0)

**Comment by Ghada-Ch** [comment]
@Ivan61 
> sudo docker-compose version

Unable to find image 'dockercompose:1.25.0' locally
docker: Error response from daemon: pull access denied for dockercompose, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by apiraino** [comment]
@JonahGroendal @Ghada-Ch please also have a look at [this comment](https://github.com/docker/compose/issues/7370#issue-600778437) (I could build Compose from sources for a Raspi4 on Ubuntu server ARM64)

**Comment by shukriadams** [comment]
There are official, up-to-date raspian builds for docker core ... 

    https://download.docker.com/linux/raspbian/dists/buster/pool/stable/armhf

but not for compose? Why is that?

**Comment by nemchik** [comment]
> There are official, up-to-date raspbian builds for docker core ...
> 
> ```
> https://download.docker.com/linux/raspbian/dists/buster/pool/stable/armhf
> ```
> 
> but not for compose? Why is that?

Compose installs via pip, which works fine on arm. This issue it's specifically about the lack of an official docker image built for arm.

**Comment by shukriadams** [comment]
Last time I checked compose wants python 3, while raspbian's global python is still 2. `apt-get install docker-compose` is still the cleanest compromise, but then we end up with an older version of it. Look, it's not the end of the world, I just can't help feeling the general docker experience on ARM/Raspbian still lags behind what I'm used to on mainstream cpus/distros.

**Comment by shainert-israel** [comment]
What are the instructions for installing docker-compose on Yocto?

**Comment by nemchik** [comment]
> Last time I checked compose wants python 3, while raspbian's global python is still 2. `apt-get install docker-compose` is still the cleanest compromise, but then we end up with an older version of it. Look, it's not the end of the world, I just can't help feeling the general docker experience on ARM/Raspbian still lags behind what I'm used to on mainstream cpus/distros.

Echoing the Recommended method from https://hub.docker.com/r/linuxserver/docker-compose
```bash
sudo curl -L --fail https://raw.githubusercontent.com/linuxserver/docker-docker-compose/master/run.sh -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```
Should work on any linux distro and should work on `x86_64`, `armv7l`/`armhf`, and `aarch64`/`armv8`/`arm64` if you already have docker installed.

**Comment by grbd** [comment]
I've been using docker and docker-compose on gentoo-on-rpi-64bit on a pi4.
Although I'd recommend also using hard disks and not just an sd card in that scenario. (I'm using a X829 geekworm board as part of that)
Since gentoo tends to build stuff from source sometimes 

  * https://github.com/sakaki-/gentoo-on-rpi-64bit/wiki

Although gentoo-on-rpi-64bit is setup to use binary / precompiled ebuilds in most cases.
So far they have 1.27.0 of docker-compose available in the ebuilds although setting up the OS is more technical / not as pre-packaged as raspian. but it is ARM64

**Comment by tlex** [comment]
I've been building a multi-arch image for quite some time now - only running `docker buildx` against the Dockerfile in this repository.

If anyone wants to give it a spin: [gitlab.com/ix.ai/docker-compose](https://gitlab.com/ix.ai/docker-compose/) or [ixdotai/docker-compose](https://hub.docker.com/r/ixdotai/docker-compose)

**Comment by shainert-israel** [comment]
For Yocto Thud I managed to use docker-compose, but I needed to cheat it, so I guess some features might not work (reviewing the change log, it looks OK to me). Any one can print out what will not work?
My Environment:
BB_VERSION           = "1.40.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-fslc-linux-gnueabi"
MACHINE              = "imx6ul-var-dart"
DISTRO               = "fslc-framebuffer"
DISTRO_VERSION       = "2.6"
TUNE_FEATURES        = "arm armv7a vfp thumb neon callconvention-hard"
TARGET_FPU           = "hard"
In conf/local.conf:
`IMAGE_INSTALL_append += " python3-docker-compose"
`
In sources/meta-xxx/recipes-containers/docker-compose/python3-docker-compose_%.bbappend:
`do_install_append() {
    sed -e 's/docker<3.0,>=2.5.1/docker<3.5,>=2.5.1/g' ${D}${libdir}/python3.5/site-packages/docker_compose-1.16.1-py3.5.egg-info/requires.txt > mod_req.txt
    install -d ${D}${libdir}/python3.5/site-packages/docker_compose-1.16.1-py3.5.egg-info
    install -m 0644 mod_req.txt ${D}${libdir}/python3.5/site-packages/docker_compose-1.16.1-py3.5.egg-info/requires.txt
}`

**Comment by samip5** [comment]
> I've been using docker and docker-compose on gentoo-on-rpi-64bit on a pi4.
> Although I'd recommend also using hard disks and not just an sd card in that scenario. (I'm using a X829 geekworm board as part of that)
> Since gentoo tends to build stuff from source sometimes
> 
> * https://github.com/sakaki-/gentoo-on-rpi-64bit/wiki
> 
> Although gentoo-on-rpi-64bit is setup to use binary / precompiled ebuilds in most cases.
> So far they have 1.27.0 of docker-compose available in the ebuilds although setting up the OS is more technical / not as pre-packaged as raspian. but it is ARM64

Unfortunately, if you run the Sakaki's version of Gentoo, you'll find it hard to find support from Gentoo's normal support channels.

**Comment by logoff** [comment]
In this case I prefer to have the binary, so my sollution is using LinuxServer release:

```

**Comment by neodon** [comment]
I just ran into this issue again after a few months, and was surprised again that I can't get the latest version of docker-compose in the same way for x86_64 and aarm64.

**Comment by pcgeek86** [comment]
I'm running 64-bit Ubuntu 20.04 LTS Focal Fossa on a Raspberry Pi 3 B+. Is there an official ARM 64-bit binary for Docker Compose?

**Comment by nemchik** [comment]
> I'm running 64-bit Ubuntu 20.04 LTS Focal Fossa on a Raspberry Pi 3 B+. Is there an official ARM 64-bit binary for Docker Compose?

Unfortunately no, there isn't an official one, but linuxserver.io has one that is a near identical clone of the x86 official with added support for armhf and aarch64 https://github.com/docker/compose/issues/6831#issuecomment-683797087

**Comment by javierguzman** [comment]
Does anyone know if they plan to release this for arm or is it directly a no no?

I wanted to port my Gitlab CI to Raspberry PI and stumbled upon this problem.

Thank you in advance and regards.

**Comment by darkguy2008** [comment]
2021 yet no progress on this. What's the status? How do we install it then?

**Comment by darkguy2008** [comment]
> @webash I'm sorry to hear you've had troubles installing compose. You should be able to do it pretty easily by installing `python3` and `python3-pip` first and then running `python3 -m pip install -IU docker-compose`.
> 
> If you have further issues feel free to reach out via my contact info on my GitHub profile since this isn't really a support thread.
> 
> That being said I'm subscribed here hoping to see any kind of movement in this happening. I'd love to he able to run compose from docker on ARM. It works great on x86_64.

This is cool and it works to install it, but it doesn't work if you use sudo to run it. Anybody knows how to? Thanks!

**Comment by VennieSo** [comment]
> 2021 yet no progress on this. What's the status? How do we install it then?


Check out https://github.com/docker/compose/issues/6831#issuecomment-683797087 to run compose in a container or https://github.com/docker/compose/issues/6831#issuecomment-756045464 to download the binary, both solutions by [LinuxServer](https://docs.linuxserver.io/general/docker-compose).

**Comment by williamdes** [comment]
> 2021 yet no progress on this. What's the status? How do we install it then?

Source: https://withblue.ink/2020/06/24/docker-and-docker-compose-on-raspberry-pi-os.html


```sh
# Install required packages
sudo apt update
sudo apt install -y python3-pip libffi-dev

# Install Docker Compose from pip (using Python3)
# This might take a while
sudo pip3 install docker-compose
```

**Comment by boonya** [comment]
> > 2021 yet no progress on this. What's the status? How do we install it then?
> 
> Source: https://withblue.ink/2020/06/24/docker-and-docker-compose-on-raspberry-pi-os.html
> 
> ```shell
> # Install required packages
> sudo apt update
> sudo apt install -y python3-pip libffi-dev
> 
> # Install Docker Compose from pip (using Python3)
> # This might take a while
> sudo pip3 install docker-compose
> ```

This is what exactly I use for my pet project. And this has been working for a long time with no issues.

**Comment by nemchik** [comment]
To be clear, installing compose via pip does work, but it is not running compose itself from within a docker container, which is the topic of this issue. Options exist from 3rd parties to accomplish running compose from within docker, and comments above have outlined these options. One such posted by me: https://github.com/docker/compose/issues/6831#issuecomment-683797087

**Comment by jamshid** [comment]
I guess we should be switching from `docker-compose` to `docker compose` but fwiw here's what I had to do to build an ARM64-compatible image based on centos:7.9.2009 that includes a working docker-compose. 

```
# Can test with: docker run -ti --platform linux/arm64 centos:7.9.2009 bash
FROM centos:7.9.2009
RUN yum install python3-pip
...
# Install docker-compose client
ENV DOCKER_COMPOSE_VERSION 1.29.0
RUN test "$(uname -m)" = "aarch64" && echo INSTALL LATER VIA PIP UNTIL ARM64 BINARIES AVAILABLE OR SWITCH TO docker compose && exit 0 ; curl -sSLf -o /bin/docker-compose https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` && chmod +x /bin/docker-compose
# Temporary arm64 support, remove after switching to "docker compose"
RUN if test "$(uname -m)" = "aarch64" ; then pip3 install --upgrade pip && yum install -y make gcc python3-devel && pip3 install pynacl && pip3 install docker-compose==${DOCKER_COMPOSE_VERSION} && yum remove -y make gcc python3-devel ; fi
```

**Comment by ndeloof** [comment]
Please note compose v2 has arm7 and arm64 binaries: https://github.com/docker/compose-cli/releases/tag/v2.0.0-beta.3

**Comment by rafaelmaeuer** [comment]
> > 2021 yet no progress on this. What's the status? How do we install it then?
> 
> Source: https://withblue.ink/2020/06/24/docker-and-docker-compose-on-raspberry-pi-os.html
> 
> ```shell
> # Install required packages
> sudo apt update
> sudo apt install -y python3-pip libffi-dev
> 
> # Install Docker Compose from pip (using Python3)
> # This might take a while
> sudo pip3 install docker-compose
> ```

Is there a benefit in means of performance and stability compared to the solution of @nemchik: https://github.com/docker/compose/issues/6831#issuecomment-683797087?

**Comment by nemchik** [comment]
> > > 2021 yet no progress on this. What's the status? How do we install it then?
> > 
> > 
> > Source: https://withblue.ink/2020/06/24/docker-and-docker-compose-on-raspberry-pi-os.html
> > ```shell
> > # Install required packages
> > sudo apt update
> > sudo apt install -y python3-pip libffi-dev
> > 
> > # Install Docker Compose from pip (using Python3)
> > # This might take a while
> > sudo pip3 install docker-compose
> > ```
> 
> Is there a benefit in means of performance and stability compared to the solution of @nemchik: [#6831 (comment)](https://github.com/docker/compose/issues/6831#issuecomment-683797087)?

Currently the options to run `docker-compose` on any system are:

* Install python and then install `docker-compose`
* On x86_64, use the official `docker/compose` image with the official helper script
* On x86_64, armv7, or armv8, use the `linuxserver/docker-compose` image (based on the official `docker/compose image, but built for multiple architectures) with the linuxserver helper script (based on the official helper script, but using the linuxserver image).

In the future https://github.com/docker/compose-cli may replace the need for most of this, but it seems like the application in this repo is currently recommended for general use.

**Comment by JohnnyLin-a** [comment]
An easy way to get Docker compose running:
Download Docker on your arm device. (Latest stable pref)
Download v2.x.x (currently in beta6) `docker-compose-linux-armv7` from [here](https://github.com/docker/compose-cli/releases) (or the one that matches your device's architecture)
Rename that file to just `docker-compose`
Move `docker-compose` to `~/.docker/cli-plugins/` and `chmod +x ~/.docker/cli-plugins/docker-compose`
Then the command `docker compose` will work on your device.

**Comment by l3043Y** [comment]
arm64 or aarch64 
```
mkdir -p ~/.docker/cli-plugins/
curl -SL https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-linux-aarch64 -o ~/.docker/cli-plugins/docker-compose
chmod +x ~/.docker/cli-plugins/docker-compose
docker compose version
```

**Comment by ASFLY61** [comment]
> arm64 or aarch64
> 
> ```
> mkdir -p ~/.docker/cli-plugins/
> curl -SL https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-linux-aarch64 -o ~/.docker/cli-plugins/docker-compose
> chmod +x ~/.docker/cli-plugins/docker-compose
> docker compose version
> ```

Thank you very much
