### ISSUE TITLE
How to downlad a correct matched version docker-compose?

### ISSUE THREAD

**Issue by Remember2018** [docker/compose#6834]
Hi, the used docker version is `Docker version 18.06.2-ce, build 6d37f41`,  and the system is `ubuntu 18.04`. When I'm using the `apt install docker-compose`, the software manager will update the docker to `docker 19.03` version. But to use the `kubernetes`, the Docker of 18.06.2-ce is needed. Could you please give some advice on how to install a matched version of `docker-compose` with docker 18.06.2-ce? If convenient, could you please provide a list of these matching relations between them? Thanks.

**Comment by ulyssessouza** [comment]
Hello @Remember2018 
The distribution packages are not maintained by the project. Please refer to the official documentation https://docs.docker.com/compose/install/

**Comment by Remember2018** [comment]
Hi @ulyssessouza , thank you for comment.
