### ISSUE TITLE
docker-compose not found

### ISSUE THREAD

**Issue by BeyondEvil** [docker/compose#6836]
I've tried installing docker-compose and I've tried copying the binary, both render the same result:

```
/bin/sh: docker-compose: not found
```

Here's the `Dockerfile` I'm using:
```
FROM python:3.7.4-alpine3.9
COPY --from=docker/compose:1.24.1 /usr/local/bin/docker-compose /usr/local/bin/docker-compose
CMD ["sh"]
```

It's there (good permissions and size):
```
/ # ls -la /usr/local/bin | grep docker-compose
-rwxr-xr-x    1 root     root      16168192 Jun 24 10:12 docker-compose
```

But when I try to run it:
```
/ # docker-compose
/bin/sh: docker-compose: not found
```

Not even from `/usr/local/bin`:
```
/usr/local/bin # docker-compose
/bin/sh: docker-compose: not found
```

What am I doing wrong?

**Comment by ulyssessouza** [comment]
Please check your PATH variable to know if the executable is in any of the entries.
Also please, try `file /path/to/docker-compose`. By the way, what is your OS?

**Comment by BeyondEvil** [comment]
> Please check your PATH variable to know if the executable is in any of the entries.

```
/ # which docker-compose
/usr/local/bin/docker-compose
/ # echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

> Also please, try `file /path/to/docker-compose`. 

```
/ # file /usr/local/bin/docker-compose 
/usr/local/bin/docker-compose: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=fdb92fd0de3892fc2176220c6694f8eee61d4fa3, stripped
```

> By the way, what is your OS?

```
/ # uname -a
Linux bd88730956ce 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 Linux
```

**Comment by ulyssessouza** [comment]
Just got it.
You are copying from `docker/compose:1.24.1` which has a binary linked with `glibc` inside an alpine container, which has `libmusl`. This feature is to be introduced in `docker-compose-1.25.0`. If you want to test it, you can try copying from `docker/compose:1.25.0-rc2-alpine` for now. 

*Note that this is a release candidate version.

**Comment by BeyondEvil** [comment]
Heh, check my second edit from the top @ulyssessouza  😊 

<img width="488" alt="Screenshot 2019-08-09 at 16 16 47" src="https://user-images.githubusercontent.com/15611634/62785558-2e509c00-bac1-11e9-9f96-927c94128b8f.png">

I'll try the RC and report back. 👍

**Comment by ulyssessouza** [comment]
Any news @BeyondEvil ?

**Comment by BeyondEvil** [comment]
> Any news @BeyondEvil ?

Sorry for late reply!

Using the RC version worked! Thanks!

**Comment by itsnotvalid** [comment]
@ulyssessouza I tried this with directly downloading inside `docker:stable-git` get the follow however:

```
apk add py-pip python-dev libffi-dev openssl-dev gcc libc-dev make curl
curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
and then run with simply `docker-compose` I still get this:
```
/bin/sh: docker-compose: not found
```

Thanks!

**Comment by ulyssessouza** [comment]
@itsnotvalid Same problem/answer as in the last  comment.
The github relase binary is a `glibc` binary and `docker:stable-git` is alpine based, so `libmusl`.

For this, please copy the binary from `docker/compose:1.25.0-alpine` like in:
```dockerfile
COPY --from=docker/compose:1.25.0-alpine /usr/local/bin/docker-compose /usr/local/bin/
```
