### ISSUE TITLE
Update setup.py to be pipenv compatible.

### ISSUE THREAD

**Issue by andyneff** [docker/compose#6839]
## Feature Request

When using pipenv, [these lines](https://github.com/docker/compose/blob/f9d1075a5da575cf7fd58d058fd4f4b402aff688/setup.py#L63-L73) in `setup.py` don't have the appropriate markers after installing. E.g.: if I use `pipenv` in Linux and try to sync on Windows, colorama is not installed.

The [recommended](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies) way to declare platform specific dependencies has a set of markers different in `install_requires` from the ones in `extra_requires`.

## Related Problems

https://github.com/pypa/pipenv/issues/1229, specifically mentions [here](https://github.com/pypa/pipenv/issues/1279#issuecomment-363305721) that using `extra_requires` is an old (and unsupported) way 

## Desired Solution

If instead of just adding the dependencies to the `install_requires` list when that particular systems meets the requirements, instead add to the list using the appropriate `install_requires` markers.

Current:

```
extras_require = {
    ':python_version < "3.4"': ['enum34 >= 1.0.4, < 2'],
    ':python_version < "3.5"': ['backports.ssl_match_hostname >= 3.5, < 4'],
    ':python_version < "3.3"': ['ipaddress >= 1.0.16, < 2'],
    ':sys_platform == "win32"': ['colorama >= 0.4, < 1'],
}
```

Instead adds this to `install_requires`

```
[
    'enum34;python_version<"3.4"',
    'backports.ssl_match_hostname >= 3.5, < 4;python_version<"3.5"
    'ipaddress >= 1.0.16, < 2;python_version<"3.3"',
    'colorama >= 1.0;sys_platform=="win32"'
]
```

socks would stay in extra_requires, because it's an "extra" package. 

## Workaround

For now, I have to manually duplicate the dependencies colorama in my `Pipfile` for windows, adding

```
colorama = {version = ">=0.4, <1", markers = "sys_platform == 'win32'"}
```

## References

[PEP 0496](https://www.python.org/dev/peps/pep-0496/)

**Comment by ulyssessouza** [comment]
Hello @andyneff ! Thank you for the report!
If you want to make a PR on it that would be great!

**Comment by Patil2099** [comment]
@ulyssessouza Can I Make A PR?

**Comment by andyneff** [comment]
@Patil2099 @ulyssessouza I already made PR #6848, and it's just waiting. Is there something wrong with it/do I need to do something else?
