### ISSUE TITLE
Invalid URL when installing on RPi using pip3 

### ISSUE THREAD

**Issue by clauderobi** [docker/compose#6845]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
(paste here)
```

**Output of `docker version`**
```
(paste here)
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by ulyssessouza** [comment]
Looks like your issue is empty
