### ISSUE TITLE
docker-compose ps should show uptime

### ISSUE THREAD

**Issue by bertjwregeer** [docker/compose#6867]
**Is your feature request related to a problem? Please describe.**

I would like to be able to see when the last time was that a docker container was restarted/updated. Similar to #4577, but my main concern is seeing the uptime of the container.

**Describe the solution you'd like**

```
docker-compose ps
```

shows the time since the container was launched.

**Describe alternatives you've considered**

Right now I use:

```
docker ps -a
``` 

instead, which means I get a sea of output that may not be relevant, especially if I am running multiple docker-compose setups locally.

**Comment by bertjwregeer** [comment]
There's an open pull request for this... but so far no movement on it. It is not a stale request.

**Comment by mjraadi** [comment]
Would love to see this.

**Comment by bertjwregeer** [comment]
Still not stale, still a good feature required.

**Comment by bertjwregeer** [comment]
Would still love for this feature to be implemented, there is still an outstanding pull request for it.

**Comment by elboletaire** [comment]
bump it

**Comment by caioricciuti** [comment]
bump it

**Comment by elboletaire** [comment]
hhhmmm... I do now realize the PR is python, and the latest docker compose versions (since v2) work with golang, so I guess this PR won't ever be accepted, unless it's also (?) done for the golang version.

**Comment by bigntallmike** [comment]
omg someone just patch it already
