### ISSUE TITLE
docker-compose up --build, get stuck while installing the pip package in alpine container

### ISSUE THREAD

**Issue by Bhanwar0607** [docker/compose#6868]
Installing the package in alpine get stuck

it stuck at 
(6/12) Installing ncurses-terminfo (6.1_p20190105-r0) OR
(10/12) Installing python2 (2.7.16-r1)

Sometimes it works properly.

Command: sudo docker-compose build

Tried proxy but didn't work

        # Docker Upstart and SysVinit configuration file

        #
        # THIS FILE DOES NOT APPLY TO SYSTEMD
        #
        #   Please see the documentation for "systemd drop-ins":
        #   https://docs.docker.com/engine/admin/systemd/
        #

        # Customize location of Docker binary (especially for development testing).
        #DOCKERD="/usr/local/bin/dockerd"

        # Use DOCKER_OPTS to modify the daemon startup options.
        DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"

        # If you need Docker to use an HTTP proxy, it can also be specified here.
        export http_proxy="http://127.0.0.1:3128/"

        # This is also a handy place to tweak where Docker's temporary files go.
        #export DOCKER_TMPDIR="/mnt/bigdrive/docker-tmp"

Also tried by increating the MTU
docker-compose.yml

      version: '3.7'

      services:

        admin-api:
          container_name: admin-api
          build:
            context: .
            dockerfile: Dockerfile
          
          environment:
            - HOME=/home
            - NODE_ENV=dev
            - DB_1=mongodb://mongo:27017/DB_1
            - DB_2=mongodb://mongo:27017/DB_2
          volumes:
            - '.:/app'
            - '/app/node_modules'
            - '$HOME/.aws:/home/.aws'
          ports:
            - '4004:4004'
          networks:
            - backend
          links:
            - mongo

        mongo:
          container_name: mongo
          image: mongo:4.2.0-bionic
          ports:
            - "27018:27017"
          networks:
            - backend

      networks:
          backend:
            driver: bridge
            driver_opts:
              com.docker.network.driver.mtu: 1500

Dockerfile

        # base image
        FROM node:8.16.1-alpine

        # set working directory
        WORKDIR /app

        # add `/app/node_modules/.bin` to $PATH
        ENV PATH /app/node_modules/.bin:$PATH

        # install and cache app dependencies
        COPY package.json /app/package.json

        RUN apk add --update-cache py-pip && \
            pip install awscli && \
            apk --purge -v del py-pip && \
            rm -rf /var/cache/apk/*

        RUN npm install --silent
        RUN npm install -g nodemon

        # start app
        CMD  nodemon

        EXPOSE 4004

My is dependent on AWS and it required aws credential, install the aws on using pip, and mounted the /home/.aws (local) with /home/.aws container but when I am creating or building the container it get stuck and not even showing the error. while building the container also check the network monitor it shows receiving packets 0dytes/s 

Tried --verbose but it didn't got any useful information

**Comment by funkyfuture** [comment]
i don't think that your problem is specific to Compose as your build is failing, an my guess is that your problem doesn't belong to one of the bug trackers of the technology you employ, but rather on a platform like StackOverflow or similar.
