### ISSUE TITLE
proposal : A `.dockervolumeignore` ?

### ISSUE THREAD

**Issue by AnatoleLucet** [docker/compose#6872]
**Is your feature request related to a problem? Please describe.**
Yes it is. When I have a volume for (exemple) a developpement environnement, I need this volume to keep my host's files changes on the container. But it seems to be a bad practice to share (again for example) a `node_modules` folder (on a `node` project) to the container from the host, especially if the image is being shared between different OS.

There is this hack : 
```yml
volumes:
  - ./:/app
  - /app/node_modules
```

But it can easily create more problems than the first one because it will create an empty `node_modules` folder on the host that have `root:root` access and probably a different `uid` & `gid` than yours.

Also this hack, is not really viable if you have multiples `node_modules` folder in one project, because you will need to list all of them in your `docker-compose.yml`.

**Describe the solution you'd like**
Maybe I am dreaming but something like a `.dockervolumeignore` would be perfect.

I could just add `**/node_modules` in it and it should works perfectly.

**Comment by funkyfuture** [comment]
have you read the documentation on using `extends` to provide configuration for different environments?

**Comment by AnatoleLucet** [comment]
@funkyfuture Yes I do, but how can different configuration can solve that ?
