### ISSUE TITLE
Regression: compose ignores signals unless sent to process group

### ISSUE THREAD

**Issue by sgentle** [docker/compose#6874]
Hi! I've found a bug introduced by #6578. `bootloader_ignore_signals` causes compose to... well, ignore all signals. This isn't as much of an issue if you're just running it in a tty because ctrl-c etc will be sent to the entire process group, but the top-level compose process can no longer be gracefully stopped via `kill` or `docker stop` etc.

Here's a test file that I have saved as `docker-compose.yml`:
```
version: '3'
services:
  cat:
    image: alpine
    entrypoint: 'sleep 999999'
```

This works fine:
```
$ sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)"/docker-compose.yml:/docker-compose.yml docker/compose:1.24.1 up
Starting default_cat_1 ... done
^CStopping default_cat_1 ... done
Attaching to default_cat_1
Gracefully stopping... (press Ctrl+C again to force)
$
```

This hangs forever:
```
$ sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)"/docker-compose.yml:/docker-compose.yml docker/compose:1.25.0-rc2 up
Starting default_cat_1 ... done
^C^C^C^C^C^C^C^C^C^C
```

Here's some pretty pstree output, showing the pyinstaller bootloader process, the inner compose process, and two threads:
```
$ pgrep docker-compose | head -1 | xargs pstree -p
docker-compose(26756)───docker-compose(26827)─┬─{docker-compose}(26961)
                                              └─{docker-compose}(26962)
```

`sudo kill 26756` does nothing. `sudo kill 26827` brings down compose gracefully. `sudo docker stop` waits a while and then sends a SIGKILL. Currently it seems like the best workaround is to use something like `docker --init -e "TINI_KILL_PROCESS_GROUP=1"`.

I can tell this signal handling stuff has been a huge pain, but I'm not sure that having the bootloader swallow signals is the right answer. Maybe a better approach would be to move the compose (sub)process into a new process group and set it as the foreground via `tcsetpgrp`?

**Comment by grugnog** [comment]
This affects scripted use also - for example we have a script that backgrounds a logs -f process (so the startup logs can be monitored by the developer and captured by CI) then after it detects the application has started correctly kills the background logging job.
This used to work everywhere, but since the recent docker-compose update it no longer works on binary/pyinstaller installs and we have had to update our script to look up and kill the PGID instead.
