### ISSUE TITLE
Unable to build for arm32 and arm64 (1.24.1)

### ISSUE THREAD

**Issue by NicolasDorier** [docker/compose#6879]
The SSH dependency via paramiko broke the build for arm32 and arm64 (for 1.24.1)

You can try to build my repo on https://github.com/btcpayserver/docker-compose-builder :

Dependency:
```bash
docker run --rm --privileged multiarch/qemu-user-static:register --reset
apt install -y qemu qemu-user-static qemu-user binfmt-support
```

Build:
```bash
docker build -t temp -f .\linuxarm32v7.Dockerfile --build-arg DOCKER_COMPOSE_VER=1.24.1 .
```

Error on libsodium tests:
https://circleci.com/gh/btcpayserver/docker-compose-builder/89

**Comment by NicolasDorier** [comment]
Posted on PynACL https://github.com/docker/compose/issues/6879

**Comment by chainfrost** [comment]
I am getting same problem while using  `pip install docker-compose==1.25.1rc1` command
 on bananapi armbian 19.11.3.  Here is the error log (I did not include python errors between last 2 line):

```
Collecting pynacl>=1.0.1 (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<5,>=3.7.0->docker-compose==1.25.1rc1)
  Using cached https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    WARNING: The wheel package is not available.
    ERROR: Failed to build one or more wheels
>
>
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k_s25f/pynacl/
```

I tried to follow temporary workaround but I am a bit confused how to do. Any suggestions?

**Comment by NicolasDorier** [comment]
unsolved

**Comment by dvonessen** [comment]
I have the same issue here.

**Comment by NicolasDorier** [comment]
bump

**Comment by zhangguanzhang** [comment]
did you resolve this?

**Comment by NicolasDorier** [comment]
no idea, we use our hack to workaround it.

**Comment by zhangguanzhang** [comment]
https://github.com/zhangguanzhang/docker-compose-aarch64/releases

**Comment by NicolasDorier** [comment]
It works without the hack for me now see https://github.com/btcpayserver/dockerfile-deps/blob/master/docker-compose/1.28.5/linuxarm64v8.Dockerfile
