### ISSUE TITLE
Multiple bash commands with "source"

### ISSUE THREAD

**Issue by DarioTurchi** [docker/compose#6881]
I have a problem similar to that described in issue #2033 (multiple commands for a compose service), with the difference that the first command to be executed is a "source"

Assuming to have the script `script.sh` where the command alias `myAlias` is defined, the following (solution proposed in issue #2033 )
```
command: bash -c "source script.sh && myAlias"
```
generates the following error
`bash: myAlias: command not found`

**Comment by ulyssessouza** [comment]
@DarioTurchi Could you please, add information asked in the bug's issue template so we can reproduce the problem?

**Comment by DarioTurchi** [comment]
Hi, don't know where to find the template but the problem is pretty straightforward.

* create a folder `test` and `cd` in it
* create the two following files in there:
    *  `test.sh`:
    ```
    alias myalias='ls'
   ```

    * `docker-compose.yml`:
```
version: '3.4'
services:
  test:
    image: "ubuntu"
    volumes:
      - ./:/home
    command: >
      bash -c "source /home/test.sh && myalias"
```

* from the folder execute the command `docker-compose up`. You will get :
```
Creating network "compose-test_default" with the default driver
Creating compose-test_test_1 ... done
Attaching to compose-test_test_1
test_1  | bash: myalias: command not found
compose-test_test_1 exited with code 127
```
if instead I would execute:
`docker run --rm -v $(pwd):/home -it ubuntu bash`
and from inside the container:
`source /home/test.sh && myalias`
everything works fine.

Am I doing something wrong or is it an actual issue ?

**Comment by glance-** [comment]
man bash
> Aliases allow a string to be substituted for a word when it is used as the first word of a simple command.

This has nothing to do with docker-compose, and all with how bash handles aliases:
```$ bash -c 'alias myalias=ls && myalias'
bash: myalias: command not found
```
Aliases are inferior to functions in all scripted contexts, so use a function instead:
```$ bash -c 'function myalias { ls; } && myalias'
docker-compose.yaml  test.sh
```

**Comment by ulyssessouza** [comment]
As explained by @glance- , it's not a `docker-compose` issue
