### ISSUE TITLE
[Regression?] 'ascii' codec can't decode byte 0xc3 in position 306: ordinal not in range(128)

### ISSUE THREAD

**Issue by strarsis** [docker/compose#6883]
# Description of the issue
`docker-compose` command fails with some specific ports, e.g. `"2239:22"`.
(Following best practices, the port pair is quoted to prevent issues with YAML parsing.)

`docker-compose` emits errors when being used on that `docker-compose.yml` file, 
with the container failing to start up (`Exit 128`):
````
[...]
'ascii' codec can't decode byte 0xc3 in position 306: ordinal not in range(128)
[...]
````
This error only occurs with specific port pairs like `"2239:22"`, 
using an example pair from the docker-compose documentation, e.g. `"8080:80"` works.

## Context information (for bug reports)

This bug seems to be a regression because it happened right after the update of `docker-compose` today and multiple closed issues in this repository are describing the same or similar symptoms.

**Output of `docker-compose version`**
```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  php:
    image: test/php-wp:7.3-fpm
    ports:
    - 2239:22/tcp
    volumes:
    - [...]/site:/srv/www:rw
version: '2.0'
```

## Steps to reproduce the issue

1. Create `docker-compose.yml` with a specific port pair that is known to cause the issue:
```yml
version: '2'

services:
  php:
    image: php:7.3-fpm
    ports:
      - "2239:22"
````
2. Let `docker-compose` interact on that `docker-compose.yml` file, e.g. using `docker-compose up -d`.

### Observed result
Error message `'ascii' codec can't decode byte 0xc3 in position 306: ordinal not in range(128)`
with failure bringing the container up.

### Expected result
Normal usage of `docker-compose` as before its update.

### Stacktrace / full error message

```
Creating network "containertest_default" with the default driver
Creating containertest_php_1 ...

ERROR: for containertest_php_1  'ascii' codec can't decode byte 0xc3 in position 306: ordinal not in range(128)

ERROR: for php  'ascii' codec can't decode byte 0xc3 in position 306: ordinal not in range(128)
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/main.py", line 959, in up
  File "compose/project.py", line 479, in up
  File "compose/parallel.py", line 80, in parallel_execute
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 306: ordinal not in range(128)
Failed to execute script docker-compose
```

## Additional information

WSL (Bash on Windows) with `docker` client + `docker-compose` on WSL and 
Docker Desktop as native Windows service (using Hyper-V).

**Comment by ulyssessouza** [comment]
Hello @strarsis could you please, try with a more recent version of `docker-compose`. The current stable is `1.24.1`. Release candidates of `1.25.0` are also available.

**Comment by strarsis** [comment]
@ulyssessouza: Thanks for the response.
First updated to `1.24.1, build 4667896`, 
then updated to `1.25.0-rc2, build 661ac20`, 
but the issue still persists.

**Comment by strarsis** [comment]
@ulyssessouza: Are you able to reproduce this issue using this `docker-compose` release and the port pair?

**Comment by strarsis** [comment]
In recent `docker-compose` (`1.25.0-rc2, build 661ac20`) it seems to work - at least for port mapping `2239:22`.
