### ISSUE TITLE
Allow --target option in docker-compose build

### ISSUE THREAD

**Issue by samueljsb** [docker/compose#6886]
**Is your feature request related to a problem? Please describe.**
I have some multi-stage builds in my project and I would like to be able to run some containers at a particular stage for testing. Currently, I can't use Compose for these - I have to run the tests for one of my services using plain docker.

**Describe the solution you'd like**
The `docker build` option `--target` can be used with Compose.

**Describe alternatives you've considered**
I could use separate `docker-compose.yaml` files for testing, development, and production, but multi-stage builds are supposed to help with the problem of coordinating multiple files with the same information in them, so this isn't ideal.

**Comment by Enola-guy** [comment]
Hello why did you close it ?

**Comment by isapir** [comment]
This was closed as completed?  I'm getting an error: `unknown flag: --target`

**Comment by laurazard** [comment]
You can check the comments on the linked PR [here](https://github.com/docker/compose/pull/6887#issuecomment-551736307), but it ended up not being merged after discussion. `--target` is not currently a valid argument for `compose build`
