### ISSUE TITLE
fig start should attach containers to stdout

### ISSUE THREAD

**Issue by sge-babrams** [docker/compose#689]
Following the same behavior as `fig up` which recreates containers and attaches docker logs to stdout. `fig start` should start the stopped containers and attach their docker logs to stdout.

**Comment by parshap** [comment]
@aanand should `compose attach` be an alias for this behavior to parallel `docker attach`?

**Comment by parshap** [comment]
On second thought, I notice that `compose up --no-recreate` is not exactly like `docker attach`. `CTRL+c` does not send a `SIGKILL` to the container.

What I'm looking for is a `compose attach [SERVICE]` command that is essentially `docker attach $(compose ps -q SERVICE)` but also works with multiple containers like just running `compose up`.

**Comment by aanand** [comment]
@parshap Ctrl-C during `docker-compose up` first tries to stop containers. The second Ctrl-C sends `SIGKILL`. If you're not seeing that behaviour, please open an issue!
