### ISSUE TITLE
nexus as a docker registry when nexus has a different root

### ISSUE THREAD

**Issue by DemianTinkiel** [docker/compose#6894]
I have a nexus server that acts as a repo for NPM, Maven and Docker artifacts.
The problem is that for NPM and Maven, for legacy reasons I had to serve all nexus from a different root i.e
```
[npm]
http://ip:port/nexus/repository/npm/
[maven]
http://ip:port/nexus/repository/maven/
```
and obviously by extension docker is `http://ip:port/nexus/repository/docker/`

but when docker tries to do anything it automatically goes as `https://ip:port/v2/` which of course results in a 404

I would like a way to specify the full url of the repo in the daemon.json rather than just host + port

if I have anything else after port I cant start the daemon: `parsing "8081/nexus/repository/docker": invalid syntax`

**Comment by ulyssessouza** [comment]
Hello @DemianTinkiel . 
Looks like your issue is not related to `docker-compose`, please address your question to the proper project.

**Comment by DemianTinkiel** [comment]
Hi @ulyssessouza which project should I use?

**Comment by ulyssessouza** [comment]
From what you reported, looks like `Nexus`, since they should know how to access their repository

**Comment by DemianTinkiel** [comment]
@ulyssessouza my issue is that docker-compose is very "opinionated" as to what the URL should be. This would be the same case of having a proxy in front of it that redirects traffic based on the resource part of the URL. Imagine my proxy is `10.160.155:8080`so I'd use `10.160.155:8080/nexus`  to distinguish from `10.160.155:8080/other-service`. Essentially nexus is NOT on `10.160.155:8080` but on `10.160.155:8080/nexus`

If docker compose would allow me to set the URL including resource part instead of only allowing me to set IP + port, this would be fine

Do you understand what I mean?
