### ISSUE TITLE
docker-compose fails on Linux Manjaro

### ISSUE THREAD

**Issue by roipoussiere** [docker/compose#6915]
## Description of the issue

The docker-compose is not working.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dockerpty>=0.4.1' distribution was not found and is required by docker-compose
```

**Output of `docker version`**
```
Client:
 Version:           19.03.1-ce
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Sat Jul 27 21:08:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.1-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.7
  Git commit:       74b1e89e8a
  Built:            Sat Jul 27 21:08:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.7.m
  GitCommit:        85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**

Same stacktrace as above.

## Steps to reproduce the issue

1. `sudo pacman -S docker-compose`
2. `docker-compose --version`

### Observed result

`docker-compose --version` command fails after installed docker-compose.

### Expected result

`docker-compose --version` should print the version of docker-compose.

### Stacktrace / full error message

See above.

## Additional information

**lsb_release -a**

```
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        18.0.4
Codename:       Illyria
```

Docker-compose has been installed with pacman, [from the community repository](https://www.archlinux.org/packages/community/any/docker-compose/).

Note that I did not added docker group to sudoers and I use the docker command with `sudo docker`, but I get the same result with `sudo docker-compose --version`.

**Comment by jhabdas** [comment]
Please consider following the [official installation instructions](https://docs.docker.com/compose/install/) for Compose. I'm running `5.2.11-1-MANJARO` and compose works perfectly. Otherwise, if `sudo systemctl status docker` is working and you did a `sudo pamac build docker-compose-bin` to install and its still not working consider taking up the issue with the maintainer of the package in the AUR.

**Comment by roipoussiere** [comment]
Indeed it works when using the curl command as explained in the installation instruction, thank you.

Do you know how to create an issue on a package from Arch's community repository? [Their git repo](https://gitlab.manjaro.org/arch-packages/community/docker-compose) doesn't provide a issue tracker...

**Comment by roipoussiere** [comment]
Reported here: https://bugs.archlinux.org/task/66493

**Comment by nonetrix** [comment]
Exact same issue here still, seems to not be finding some file? I will investigate best to my ability

**Comment by nonetrix** [comment]
Running with sudo fixed it for me at least but seem OP already tried this
