### ISSUE TITLE
Support restart unless-stopped in compose file version 2

### ISSUE THREAD

**Issue by cdalexndr** [docker/compose#6940]
Using compose file version 3, "restart: unless-stopped" works fine with docker-compose, but this version is dedicated to docker swarm (as stated in https://github.com/docker/compose/issues/4513#issuecomment-281478365).
Please add this option to version 2, that is maintained in parallel for normal docker compose.

**Comment by ndeloof** [comment]
`restart` option is supported by both version 2 and version 3, and `unless-stopped` is also supported by both of them.

Please open a more specific issue if you get any trouble with this option.

**Comment by cdalexndr** [comment]
Was missing in documentation and thought that it is not supported.
Opened https://github.com/docker/compose/issues/6941
