### ISSUE TITLE
Document restart unless-stopped for file version 2

### ISSUE THREAD

**Issue by cdalexndr** [docker/compose#6941]
[Documentation](https://docs.docker.com/compose/compose-file/compose-file-v2/#restart) doesn't mention the **unless-stopped** option in **restart** section.

**Comment by ndeloof** [comment]
https://github.com/docker/docs-private/pull/1366

**Comment by ndeloof** [comment]
Documentation has been updated
https://docs.docker.com/compose/compose-file/#restart
