### ISSUE TITLE
Docker Compose with SSH DOCKER_HOST runs awfully slow on macOS 

### ISSUE THREAD

**Issue by jayfk** [docker/compose#6942]
## Description of the issue
Docker Compose with SSH DOCKER_HOST runs awfully slow on macOS, using Docker for mac. Running `docker-compose up` on a testfile with a single service takes more than 5 minutes. Running the same file on a Linux machine with the same remote host takes just a couple of seconds. 

Other Docker operations, using the `docker` cli run without a problem. I tried to debug the underlying `paramiko` library but wasn't able to find anything useful. The code seems to hang somewhere between initializing a new `docker.transport.SSHConnection`.

I tried the partial fix in https://github.com/docker/docker-py/pull/2360 without success

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896
docker-py version: 3.7.3
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  redis:
    image: redis:alpine
version: '3.0'
```

## Steps to reproduce the issue

1. run `export DOCKER_HOST=ssh://user@host` on a mac
2. run `docker-compose up`, using the testfile from above
3. watch docker-compose struggling badly

### Observed result
Watching docker-compose struggling badly

### Expected result
Finish docker-compose commands in a timely manner.

**Comment by glours** [comment]
Hi @jayfk 
I can't reproduce the issue
I try with 
```
docker-compose version 1.24.1
docker-py version: 3.7.3
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
``` 
And 
```
docker-compose version 1.25.0dev, build unknown
docker-py version: 4.1.0-dev
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

Can you try with the last release https://github.com/docker/compose/releases/tag/1.25.0-rc2

**Comment by guillaumesmo** [comment]
Just stumbled upon this issue as well, and it turned out the ssh client was trying to connect with IPv6, which causes a delay of 30 seconds. 

Quick fix is to use the IPv4 address explicitly instead of the hostname. Or add the following in the .ssh/config entry: AddressFamily inet
