### ISSUE TITLE
Inefficient docker-compose bahavior 

### ISSUE THREAD

**Issue by rom-stratoscale** [docker/compose#6946]
During debugging docker performance, I noticed that docker-compose add extra unnecessary load on docker while running docker-compose down.
Seems that instead of filtering the containers that are specified in the compose file, docker compose inspects each and every container on the host and only then performs the filtering.
In a scenarios where are many containers and many docker-compose instances are executing, it adds very high api load on docker daemon.
This is the code that does this flow: https://github.com/docker/compose/blob/master/compose/project.py#L702
 when executed in the following flow: https://github.com/docker/compose/blob/master/compose/project.py#L324

Any specific reason for this implementation?

Thanks

**Comment by ndeloof** [comment]
You seem to be actually more comfortable with compose codebase than me ;) but afaict `_labeled_containers` is used to retrieve containers, and it already uses docker API with adequate filter to only get those associated with current compose instance:
```python
self.client.containers(
                all=stopped,
                filters={'label': self.labels(one_off=one_off)})
```
Did I missed something ?

**Comment by rom-stratoscale** [comment]
@ndeloof apparently, I experienced such behavior on my host, since all my compose files (~150) are placed in the same directory (aka, single project for all according to the documentation). Was not aware of such separation on the compose level. 
RTFM is usually the solution, correct? :) Probably easier than strace and ipdb.

Will give it a try and update accordingly.
Thanks

**Comment by ndeloof** [comment]
Alternatively (as your usage is not such an uncommon thing) you can run your distinct installations with `--project-name` to distinguish them. Also usefull to run the exact same one multiple times concurrently

**Comment by rom-stratoscale** [comment]
Yep. Or env variable. Thanks.
