### ISSUE TITLE
Docker-compose: Warning about how libcrypto is loaded in Catalina (OSX 10.15)

### ISSUE THREAD

**Issue by jontro** [docker/compose#6947]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 892F50CB-B58A-4113-B9A0-71C20EE9B0FE/20191008162149

### Expected behavior
No warning when launching docker-compose
### Actual behavior
Launching docker-compose gives the following warning
docker-compose
WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.

### Information
  - macOS Version: 10.15

### Diagnostic logs

```
Docker for Mac: version...
➜  ~ docker-compose --version
WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.
docker-compose version 1.21.2, build a133471
```

### Steps to reproduce the behavior

  1. Type docker-compose in a terminal window

**Comment by thaJeztah** [comment]
I see some reports here about the same warning https://github.com/autopkg/autopkg/issues/550, https://github.com/autopkg/autopkg/issues/551

**Comment by ndeloof** [comment]
Internaly tracked as https://docker.atlassian.net/browse/COMPOSE-87

**Comment by ndeloof** [comment]
I tested on OSX Catalina with docker-compose installed by Docker Desktop and a remote DOCKER_HOST over ssh :

```
➜  ~ ls -al /usr/local/bin/docker-compose 
lrwxr-xr-x  1 root  admin  62 29 jul 12:06 /usr/local/bin/docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose
➜  ~ export DOCKER_HOST=ssh://192.168.8.102
➜  ~ docker-compose --version
docker-compose version 1.24.1, build 4667896b
```

So it seems this issue is fixed with recent docker-compose release (1.21.2 you're using is pretty old!)

**Comment by ndeloof** [comment]
Closing this issue to cleanup GH issue tracker, please comment if you get any additional info

**Comment by jontro** [comment]
Thanks. Can confirm it was a duplicate executable on the path. Sorry for the noise
