### ISSUE TITLE
$HOST environment variable not set in docker-compose

### ISSUE THREAD

**Issue by EnoahNetzach** [docker/compose#6962]
## Description of the issue
The `HOST` environment variable is not set when running `docker-compose` commands. It is, however, when running the relative `docker` commands.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
WARNING: The HOST variable is not set. Defaulting to a blank string.
services:
  test:
    command: sh -c 'echo $${SSH_HOST}'
    environment:
      SSH_HOST: ''
    image: alpine
version: '3.7'
```

**Docker Desktop**
Version 2.1.0.3 (38240)
Channel stable

## Steps to reproduce the issue

1. create a `docker-compose.yml` with this content:
```yaml
version: "3.7"
services:
  test:
    image: alpine
    environment:
      - SSH_HOST=${HOST}
    command: sh -c 'echo $${SSH_HOST}'
```
2. run `docker-compose run test`
3. run `docker run -e SSH_HOST=${HOST} alpine sh -c 'echo ${SSH_HOST}'`
4. run `HOST=${HOST} docker-compose run test`

### Observed result
step 2. doesn't print anything, the other steps print my host correctly

### Expected result
step 2. should print my host

## Additional information
I'm using a MacBook Pro running macOS 10.14.6.

**Comment by glours** [comment]
Which shell are you using?
Can you check that `printenv` doesn't print `HOST` env var too.

**Comment by EnoahNetzach** [comment]
I'm using `zsh`, while `printenv` doesn't show it.

**Comment by EnoahNetzach** [comment]
I think I get it, steps 3. and 4. are able to print it just because the substitution is done at shell level.

I wonder why it's not exposed as a "true" environment variable by **zsh**, or even if `docker-compose` should be able to catch it (probably not)..

**Comment by glours** [comment]
Zsh add some "parameters" and `HOST` is one of them 
https://github.com/zsh-users/zsh/blob/master/Src/params.c#L831
docker-compose can't catch it, like `printenv`, just because it's not env variable at all but a zsh "parameters"

You can fix that by adding `export HOST=${HOST}` in your `.zshrc` config file
Then `HOST` will behave like a env variable, and you'll be able to see it in `printenv` output & use it directly in docker-compose like it `docker-compose run test`

I close this issue, it's due to the os + shell config rather than docker-compose CLI behavior
