### ISSUE TITLE
docker-compose down --rmi all doesn't remove base images

### ISSUE THREAD

**Issue by terryvdgriend** [docker/compose#6971]
## Description of the issue
We use _docker-compose up_ in our CI environment to build and deploy a stack of services, on which we then perform some tests. After the tests are ran we use _docker-compose down --rmi all -v_ to clean up the deployed stack of services. 

What we have noticed that after we use _docker-compose down --rmi all -v_ the base images that are used by the services aren't cleaned up. While looking at the documentation of --rmi all it states: 

> Remove all images used by any service

With this I would assume that when we use _docker_compose down --rmi all_ that there should be no images left behind. 

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  custom:
    build:
      context: .\docker-issue
    ports:
    - 9100:8080/tcp
version: '3.0'
```

## Steps to reproduce the issue
[docker-issue.zip](https://github.com/docker/compose/files/3742907/docker-issue.zip)
1. Unpack zip file
2. run docker-compose up -d
3. run docker-compose down --rmi all -v
4. run docker images

### Observed result
Nginx image is still there.

### Expected result
No images are listed.

**Comment by Mihai-B** [comment]
I am having the same issue

**Comment by glours** [comment]
The behavior is the same as the Docker CLI
<img width="676" alt="Screen Shot 2019-10-18 at 2 51 16 PM" src="https://user-images.githubusercontent.com/705411/67095709-e6cc4780-f1b6-11e9-9754-097d56b63e92.png">

Maybe you can use `docker image prune` command to clean unused images
```sh
docker image prune --help

Usage:	docker image prune [OPTIONS]

Remove unused images

Options:
  -a, --all             Remove all unused images, not just dangling ones
      --filter filter   Provide filter values (e.g. 'until=<timestamp>')
  -f, --force           Do not prompt for confirmation
```

**Comment by terryvdgriend** [comment]
@glours could you explain, what the documentation means with the command ```docker-compose down --rmi all```? Since it states the following:
`'all': Remove all images used by any service.`
With this i would expect it to remove all images, used by any service, including the base images. 

I would expect the ```docker rmi``` functionality, not to work the same as the ```docker-compose down --rmi all```, since it the ```docker rmi``` functionality doesn't provide the option to set 'local' or 'all'. If it is expected to work the same i would suggest updating the``` docker-compose down --rmi``` documentation

**Comment by glours** [comment]
Yeah, and you can do the test by yourself, imagine your `docker-compose.yml` rely directly on the nginx image instead of a image build
```
services:
  custom:
    image: nginx:latest
    ports:
    - 9100:8080/tcp
version: '3.0'
```
If you follow the same steps, you will see that the nginx image will be remove. 
Why? It's because your compose service container is effectively using nginx image.

But when your service is started with a build-in image, it doesn't have any direct relation at the runtime level with the nginx one , it depends on your build-in image, so when you do the `docker-compose down --rmi` compose delete the build-in image as expected because the image was effectively used by your service and not nginx image which is link to your service

**Comment by terryvdgriend** [comment]
So if I have understood it correclty, when you create a service by directly referencing the nginx image. Then the ```docker-compose down --rmi all``` command has the effect I would except it to have. 

But when building a service which uses a Dockerfile. Then the ```docker-compose down --rmi all``` command only removes the image which is build using the Dockerfile, and not the images are references in the Dockerfile.

So i can conclude that the ```docker-compose down --rmi all``` only has the effect of removing all the images when directly referencing images in the docker-compose.yml, and not when using a Dockerfile to build services

**Comment by glours** [comment]
`docker-compose down --rmi all` remove all images directly used to create containers needed to run the application
In your case, it's not the nginx image which is used to create your container but the one which build from your dockerfile, so `--rmi all` remove it as expected

**Comment by terryvdgriend** [comment]
@glours thx for clarifying the workings! 
I guess we'll need to use docker image prune after our docker-compose down to retrieve our excepted result.
