### ISSUE TITLE
CTRL+C is not receiving by containers during docker-compse up..

### ISSUE THREAD

**Issue by Nitin286roxs** [docker/compose#6980]
I am running multiple modules [container] using docker-compose.
when I press [CTRL+C] , i got following logs ...

```perimeter-monitoring-engine | [2019-10-24 10:36:51.040] [error] Failed to find portCntxt for port 'Metric'
^CGracefully stopping... (press Ctrl+C again to force)
Stopping perimeter-monitoring-engine   ... done
Stopping perimeter-input-1             ... done
Stopping perimeter-rule-engine         ... done
Stopping perimeter-sink                ... done
Stopping perimeter-per_detector        ... done
Stopping perimeter-orchestrator        ... done
##########################################################################
```

But when i check docker ps-a, I get following log..

```
uncanny@uncanny-H310M-H-2-0:~/Desktop/atm_project$ sudo docker ps -a

CONTAINER ID                         IMAGE                 COMMAND                CREATED                STATUS                  PORTS                    NAMES

3fd832518efe        perimeter_monitoring_engine:latest             "./run_monitoring.sh"    34 seconds ago      Exited (137) 9 seconds ago                       perimeter-monitoring-engine

6aef9a55a37d        perimeter_input:latest                         "./run_inputEngine.sh"   34 seconds ago      Exited (137) 9 seconds ago                       perimeter-input-1

ec7dc06b6a1c        perimeter_rules_engine:latest                  "./run_rules-engine.…"   34 seconds ago      Exited (137) 9 seconds ago                       perimeter-rule-engine

d6cda1172b58        uvdeployment/node-common:sink_v1.0.3           "pm2-docker /uncanny…"   47 hours ago        Exited (0) 19 seconds ago                        perimeter-sink

49580dc29824        perimeter_person_head_detector:latest          "./run_openvino_dete…"   47 hours ago        Exited (137) 9 seconds ago                       perimeter-per_detector

b459f3f00bc9        perimeter_orchestrator:latest                  "./run_orchestrator.…"   47 hours ago        Exited (137) 9 seconds ago     perimeter-orchestrator
```

Mean all the containers are crashing except "perimeter-sink" because this is handled by javascipt and other containers handling SINGINT by shell-scipt....

One of Shell script is given blow..

> ##################### run_rules-engine.sh #########################
>#!/bin/bash
>function trapCtrlC() 
>{
   >echo "perimeter_rules_engine safely exited"
   >exit 0
>}
>trap trapCtrlC 2
>#echo "1111"
>python3 ./rules-engine.py -externalconfig=config/externalconfig/externalconfig.yaml &
>wait $!
>ret=$?
>if [ $ret -ne 0 ]; then
  >#echo "not zero"
  >exit $ret
>fi
>echo "done"`
>######################################################################

I have no idea why all the *.sh is not receiving CTRL+C singnal, All the .*sh running with PID 1...

`UID        PID  PPID  C STIME TTY          TIME CMD`
`root         1     0  0 10:49 ?        00:00:00 /bin/bash ./run_rules-engine.sh`
`root         6     1  0 10:49 ?        00:00:01 python3 ./rules-engine.py -exter`
`root        28     0  0 10:57 pts/0    00:00:00 ps -ef`
#######################################################################

If anyone have any idea, help me, Thanks in advance.

**Comment by ndeloof** [comment]
You can track signal sent to containers using `docker events`

I created a minimal compose file with a single container running `sleep 100`
on Ctrl+C I can see those events sent to container :

```
2019-11-21T17:03:34.672981976+01:00 container kill 5a22926718befdfbe4cb8e3d52b962b9a1814ad5ecb6f697287fd1b0cd30f272 (com.docker.compose.config-hash=31cf5e5aa45dab41419afbfa5be6c2413a5b86028ab1855e95a39ae4e026cef8, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=turc, com.docker.compose.service=test, com.docker.compose.version=1.24.1, image=alpine, name=turc_test_1, signal=15)
2019-11-21T17:03:44.741821111+01:00 container kill 5a22926718befdfbe4cb8e3d52b962b9a1814ad5ecb6f697287fd1b0cd30f272 (com.docker.compose.config-hash=31cf5e5aa45dab41419afbfa5be6c2413a5b86028ab1855e95a39ae4e026cef8, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=turc, com.docker.compose.service=test, com.docker.compose.version=1.24.1, image=alpine, name=turc_test_1, signal=9)
```

As you can see, `docker stop` command (used here) do first send SIGTERM (15) then after 10s timeout SIGKILL (9), but it won't use SIGINT (2). You should amend your script so it handle both.

**Comment by Nitin286roxs** [comment]
> You can track signal sent to containers using `docker events`
> 
> I created a minimal compose file with a single container running `sleep 100`
> on Ctrl+C I can see those events sent to container :
> 
> ```
> 2019-11-21T17:03:34.672981976+01:00 container kill 5a22926718befdfbe4cb8e3d52b962b9a1814ad5ecb6f697287fd1b0cd30f272 (com.docker.compose.config-hash=31cf5e5aa45dab41419afbfa5be6c2413a5b86028ab1855e95a39ae4e026cef8, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=turc, com.docker.compose.service=test, com.docker.compose.version=1.24.1, image=alpine, name=turc_test_1, signal=15)
> 2019-11-21T17:03:44.741821111+01:00 container kill 5a22926718befdfbe4cb8e3d52b962b9a1814ad5ecb6f697287fd1b0cd30f272 (com.docker.compose.config-hash=31cf5e5aa45dab41419afbfa5be6c2413a5b86028ab1855e95a39ae4e026cef8, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=turc, com.docker.compose.service=test, com.docker.compose.version=1.24.1, image=alpine, name=turc_test_1, signal=9)
> ```
> 
> As you can see, `docker stop` command (used here) do first send SIGTERM (15) then after 10s timeout SIGKILL (9), but it won't use SIGINT (2). You should amend your script so it handle both.

thanks @ndeloof
