### ISSUE TITLE
Do not autostart specific services

### ISSUE THREAD

**Issue by samrocketman** [docker/compose#6995]
# Use case

I have container services I use for troubleshooting inside of a docker network.  I like to use, for example,

```
docker-compose run dns-troubleshoot /bin/bash
```
Which starts an interactive container for me inside the network of my service stack for deeper troubleshooting.  Normally, the `dns-troubleshoot` service does not need to be started.

# Recommended implementation

docker-compose already supports `scale`.  Why not auto-skip services which have `scale: 0` defined.  No need for additional options.

Here's [an example](https://github.com/samrocketman/docker-compose-ha-consul-vault-ui/blob/ddb0ff66b0a8658a754f1d8279f5bd371ce88913/docker-compose.yml#L61-L71) of what it could look like in the context of other services.

# Duplicates

https://github.com/docker/compose/issues/1896 but I couldn't comment in there.  I think I have something useful to add so I created an additional issue to share my thoughts.  Unfortunately, I'm not a "docker collaborator" so I am excluded from participating in the discussion.

**Comment by jcsirot** [comment]
Hello @samrocketman Thank you for opening this ticket. We are going to evaluate the possibility to add this feature in a future Compose release

**Comment by samrocketman** [comment]
Neat, thanks for letting me know.

**Comment by jasonkenneth** [comment]
We have a one-time-setup service that runs some config on the host in the context of a developer downloading the project for the first time. We only want it to run when explicitly requested.

**Comment by ndeloof** [comment]
We could introduce a `disabled` boolean attribute on services, that would be ignored when explicit service name is part of the command. Just my 2 cents
