### ISSUE TITLE
Ability to exlude certain files and subfolders from being mounted/synced.

### ISSUE THREAD

**Issue by zigi05** [docker/compose#6997]
My app folder on host machine is synced to my docker container in docker compose volumes. I do development inside a docker container and would like to exclude certain files and subfolders from being synced from the container back to the host folder.

For example, inside the app folder in the container I run `npm install` and I don't want *node_modules* folder with millions of files in it to be mapped backed to my host folder from the container folder.

As of today, I have not found a way to exclude certain files and subfolders from the volumes. There's a hacky way to prevent a subfolder from being synced from host to container, but no way to prevent a subfolder from being synced from container to host.

**Comment by jcsirot** [comment]
Hello @dmxd5 
Thank you for opening this ticket. We are going to evaluate the possibility to add this feature in a future Compose release.

**Comment by kindermax** [comment]
That would be super cool!

**Comment by jdiegosierra** [comment]
I'm working with AWS Lambdas and have more than 100. Every Lambda has it's own node_modules. Of course I don't want to add every node_modules path to the docker-compose.yml file.
