### ISSUE TITLE
Doing build on a mac

### ISSUE THREAD

**Issue by dragonpiper** [docker/compose#7000]
When docker-compose build on a mac and specifying a folder that is a golang git repository. It never uses a cache for the add line which is 

ADD --chown=jenkins:user . /home/user/myapp.

when using the os version of tar which is bsdtar 2.8.3 - libarchive 2.8.3 

I get different hash doing the following command

tar cf - ~/build-context-path | shasum && sleep 3 && tar cf - ~/build-context-path | shasum

However if i use gnu tar which is at the version 

tar (GNU tar) 1.32

gtar cf - ~/build-context-path | shasum && sleep 3 && gtar cf - ~/build-context-path | shasum

the checksums are the same. I'm wondering what is causing the . docker buildkit to not detect the checksum is the same and if its related to the version of tar it's using

**Comment by jcsirot** [comment]
Hello @dragonpiper 
Thank you for using docker Compose. Please could you ask your question in the docker [Compose forum](https://forums.docker.com/c/open-source-projects/compose). The github issues page is reserved for bug reports. Thank you in advance.
