### ISSUE TITLE
Docker compose ignore or override some mount options for volume

### ISSUE THREAD

**Issue by AngryGami** [docker/compose#7002]
Here is my docker-compose.yaml file
```
version: '3.7'
volumes:
  server-vol:
    driver: local
    driver_opts:
      type: "none"
      o: "bind,X-mount.mkdir"
      device: "/mnt/my-volumes/server-vol"
services:
  server:
    image: "alpine:3.8"
    volumes:
      - type: volume
        source: server-vol
        target: /server-data
```
I expect it to create `/mnt/my-volumes/server-vol` upon first run of `docker-compose up` because I've used `X-mount.mkdir` option. Path `/mnt/my-volumes` does exists on host (i.e. it only need to create "server-vol")
Instead I got this:
```
Creating volume "test_server-vol" with local driver
Creating test_server_1 ... error                                                                                                                                                                                                
ERROR: for test_server_1  Cannot start service server: error while mounting volume '/mnt/docker-data/volumes/test_server-vol/_data': failed to mount local volume: mount /mnt/my-volumes/server-vol:/mnt/docker-data/volumes/test_server-vol/_data, flags: 0x1000, data: X-mount.mkdir: no such file or directory

ERROR: for server  Cannot start service server: error while mounting volume '/mnt/docker-data/volumes/test_server-vol/_data': failed to mount local volume: mount /mnt/my-volumes/server-vol:/mnt/docker-data/volumes/test_server-vol/_data, flags: 0x1000, data: X-mount.mkdir: no such file or directory
ERROR: Encountered errors while bringing up the project.
```
I know this works fine in command line:
```
someuser@test:~$ ls
someuser@test:~$ mkdir aaa
someuser@test:~$ touch aaa/test.aaa
someuser@test:~$ sudo mount -o bind,X-mount.mkdir aaa bbb
someuser@test:~$ ls
aaa  bbb
someuser@test:~$ ls bbb/
test.aaa
```
So why docker-compose is trying to be too smart here? 
It looks to me that it pre-validate existence of the directory and fails before even trying to call mount.

**Comment by bukowa** [comment]
Why?

````bash
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
````
````yaml
version: '2.4'

services:

  web:
    build:
      context: ./web
      target: tests
    networks:
      - gitwordpress
    volumes:
      - docker_volume1:/tmp/docker.sock:ro

networks:
  gitwordpress:
    name: gitwordpress

volumes:
  docker_volume1:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/run/docker.sock'
````
````bash
Successfully built 710352b97aaa
Successfully tagged gitwordpress_web:latest
Creating gitwordpress_web_1 ... error

ERROR: for gitwordpress_web_1  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/gitwordpress_docker_volume1/_data': failed to mount local volume: mount /var/run/docker.sock:/var/lib/docker/volumes/gitwordpress_docker_volume1/_data, flags: 0
x1000: not a directory

ERROR: for web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/gitwordpress_docker_volume1/_data': failed to mount local volume: mount /var/run/docker.sock:/var/lib/docker/volumes/gitwordpress_docker_volume1/_data, flags: 0x1000: not a di
rectory
ERROR: Encountered errors while bringing up the project.

````

**Comment by AngryGami** [comment]
@bukowa Is this anyhow related to what I've asked?

**Comment by bukowa** [comment]
@AngryGami sorry, i have similiar problem (same flag)

**Comment by ndeloof** [comment]
@bukowa daemon error is pretty explicit: "not a directory". Local driver "device" attribute is for actual devices, not unix domain sockets. You can't wrap docker.sock as a named volume.

@AngryGami I was able to reproduce your issue, will investigate

**Comment by ndeloof** [comment]
@AngryGami Stop me if I'm wrong, but with your compose configuration, you expect `server-vol` to be cretaed inside `mnt/my-volumes/`, but if I read correclty http://man7.org/linux/man-pages/man8/mount.8.html , `X-mount.mkdir` option will automatically create the target, mountpoint directory (i.e. `/server-data` inside container filesystem). 

Can you maybe explain what you're trying to achieve with this configuration ? If the plan was "just" to bind mount `/mnt/my-volumes/server-vol` inside container as  `server-data` there's a simpler way :)

**Comment by AngryGami** [comment]
@ndeloof The end goal is to not bother creating directories on the docker host (for easier automation). Same way -v key works for `docker run` command (i.e. if directory doesn't exists it will be created for me).

https://docs.docker.com/engine/reference/commandline/run/

> When the host directory of a bind-mounted volume doesn’t exist, Docker will automatically create this directory on the host for you. In the example above, Docker will create the /doesnt/exist folder before starting your container.

Though after your message I see that my expectations are not valid because as you've noticed `X-mount.mkdir` flag will be used for mount inside container and therefore it can't create directory on the host.

I, though, still would like to have a way to tell docker-compose to behave same as `docker run -v ...`.

**Comment by ndeloof** [comment]
Then just remember docker-compose mostly mimic docker run commands!

```
services:
  test:
    image: alpine
    command: sleep 100
    volumes:
      - /mnt/my-volumes/server-vol:/server-data
```

Whenever `server-vol` doesn't exist, running `docker-compose up` will create this folder on host

**Comment by AngryGami** [comment]
Nope, this is not what I want. I want to use named volume AND get directory created for me :)

**Comment by ndeloof** [comment]
Then I'm sorry you'll need a custom volume driver

**Comment by AngryGami** [comment]
Ok, I see. Thanks anyway.
