### ISSUE TITLE
MAC 10.15 implements the docker-compose entirely with errors

### ISSUE THREAD

**Issue by ronald6818** [docker/compose#7007]
![image](https://user-images.githubusercontent.com/26920063/68319584-836c7000-00f9-11ea-895c-1ec843b42638.png)
Does anyone have the same problem

**Comment by ronald6818** [comment]
Any docker-compose command will report this error

**Comment by rumpl** [comment]
Hey @ronald6818 

Is this on mac? linux? How did you install docker-compose?

**Comment by ronald6818** [comment]
> 嘿@ ronald6818
> 
> 您如何安装docker-compose？

在mac上使用brew安装的。问题已经解决，github上的版本下载覆盖brew的安装就可以使用了

**Comment by ronald6818** [comment]
> Hey @ronald6818
> 
> How did you install docker-compose?

Brew installed on a MAC. The issue has been resolved, and the version on github is now available over the brew installation
