### ISSUE TITLE
Avoid use of __file__

### ISSUE THREAD

**Issue by jayvdb** [docker/compose#7011]
It appears the use of `__file__` here is mostly unnecessary, and can easily be  replaced with `importlib.resources`/`pkgutil`. See indygreg/PyOxidizer#69 for more info about why, but the tl;dr version is `__file__` is an optional attribute and should not be relied upon.

Loading of resources from the runtime package should ideally be done using `importlib.resources` and backport `importlib_resources`, however `pkgutil` could be used to avoid the need for the backport.  Using `pkgutil` doesn't work under PyOxidizer 0.4, however I expect that will be fixed soon.

**Comment by jayvdb** [comment]
This is still valid:

The first two are runtime use of `__file__`.
```
git grep __file__
compose/cli/utils.py:    filename = os.path.join(os.path.dirname(compose.__file__), 'GITSHA')
compose/config/validation.py:    return os.path.dirname(os.path.abspath(__file__))
script/release/const.py:REPO_ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
setup.py:    path = os.path.join(os.path.dirname(__file__), *parts)
```

**Comment by jayvdb** [comment]
ping @ndeloof , can you re-open

**Comment by thaJeztah** [comment]
Let me reopen.

Looks like you have a fair understanding of what changes need to be made; were you considering opening a pull request with those changes?

**Comment by jayvdb** [comment]
Still a problem

```
git grep __file__
compose/cli/utils.py:    filename = os.path.join(os.path.dirname(compose.__file__), 'GITSHA')
compose/config/validation.py:    return os.path.dirname(os.path.abspath(__file__))
script/release/const.py:REPO_ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
setup.py:    path = os.path.join(os.path.dirname(__file__), *parts)
```

However PyOxidizer now supports pkgutil, so that is now an easy and backwards compatible way to solve these

https://github.com/indygreg/PyOxidizer/blob/f5aecad5bf5123e5910a9ebb552815c6fa524edd/pyembed/docs/oxidized_importer_behavior_and_compliance.rst#pkgutil-compatibility

**Comment by jayvdb** [comment]
Issue now redundant.
