### ISSUE TITLE
invalid unicode characters in mounted volume names

### ISSUE THREAD

**Issue by ratermir** [docker/compose#7013]
In all files and directories in volumes, that are mounted into container, national characters (the ones with unicode > 127) are shown as a question mark "?". The numver of question marks corresponds to  count of byte of each character (for example czech "é" is shown as "??"). 

The filesystem is local ext4. Characters are dislayed correctly in local tools, also the same paths mounted into container started directly by docker (**not** through  docker-composer but by docker itself), all characters are correct.
The same is observer on remote filesystem mounted via SMBFS.

Observed with docker-compose 1.23, still persists in 1.25.0-rc4
Operation system / docker:
- Debian 9, docker 19.03.4, 
- Opensuse 15, dockr 19.03.1

**Comment by jcsirot** [comment]
Hello @ratermir Thank you for opening this issue. Please could you post a minimal Composefile triggering this issue?

**Comment by ratermir** [comment]
Here is the whole compose directory (it is rather simple) that I use.  

[ums.zip](https://github.com/docker/compose/files/3843565/ums.zip)

The docker image itself is publicly available on dockerhub.

**Comment by rumpl** [comment]
Hey @ratermir,

I was able to reproduce. I made another docker-compose file:
```yaml
version: "3.7"
services:
  ums:
    build:
      context: .
    ports:
      - 5001:80
    network_mode: host
    volumes:
      - ./Všichni/Filmy:/etc/filmy
    restart: unless-stopped
```

The Dockerfile:
```
FROM nginx

ENV LANG C.UTF-8

CMD ["nginx", "-g", "daemon off;"]
```

The important line is `ENV LANG C.UTF-8`, with this setup the directories/files have the right name.

Is this the problem?

Note: I tried to run with docker and had an error :
```
$ docker run -v Všichni/Filmy:/etc/filmy test_ums 
docker: Error response from daemon: create Všichni/Filmy: "Všichni/Filmy" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

Am I doing something wrong? When you say `also the same paths mounted into container started directly by docker (not through docker-composer but by docker itself), all characters are correct.`, how do you execute it?

**Comment by ratermir** [comment]
No, this is not that issue. All volumes (that are listed in docker-compose.yaml file) are mounted succesfully, but when I navigat INTO the container, the paths and files with names that contain natinal unicode characters are shown incorrectly. 

The same action made directly through docker command results to CORRECT files/path names.

I will prepare fully working sample (including some localized paths / files and also docker command) in the evening and post them here.

**Comment by rumpl** [comment]
Hm odd, that's what I did with my example, with the LANG in the Dockerfile, the paths are good inside the container but are weird without. I just don't understand how you run it directly with docker.

A nice repo with a minimal example would be great yes! 

Thank you

**Comment by sgatade** [comment]
@rumpl I used your compose and dfile to recreate the issue. I did not get any error while upping the dcompose!

My path's look good inside the container too!

![image](https://user-images.githubusercontent.com/13362030/68873124-75bd7880-06ff-11ea-8b22-42639b7fa95d.png)

My setup is...

CentOS
Docker version 18.09.7, build 2d0083d
docker-compose version 1.23.1, build b02f1306

Regards,
SG

**Comment by rumpl** [comment]
Thanks for testing this out @sgatade 

Let's wait for @ratermir to give us a minimal example, I'm sure I misunderstood something

**Comment by ratermir** [comment]
I tried this with different image (pure alpine) and founf that the compose is OK -  this is an issue of particular image (in this case bitnami/java:1.8, which was base for my app image).
So sorry for that my mistake.

**Comment by rumpl** [comment]
Great, glad you found the fix
