### ISSUE TITLE
Container consumes external services.

### ISSUE THREAD

**Issue by Pankajdtrainer** [docker/compose#7022]
Hi there - Can you please share an example(with sample code) where a container consumes external services and execute that via web?

**Comment by ndeloof** [comment]
"execute that via web" is very unclear to me.
Also, please consider using https://forums.docker.com/c/open-source-projects/compose or https://stackoverflow.com/questions/tagged/docker-compose for generic questions

**Comment by Pankajdtrainer** [comment]
> 
> 
> "execute that via web" is very unclear to me.
> Also, please consider using https://forums.docker.com/c/open-source-projects/compose or https://stackoverflow.com/questions/tagged/docker-compose for generic questions

I mean lets say a container is running a web-service or web-page and that needs to access database that is not in containers.  How that can be achieved. Or If database is been created via container and a web service which is not running in container, how that can access that database?

**Comment by Pankajdtrainer** [comment]
I mean lets say a container is running a web-service or web-page and that needs to access database that is not in containers. How that can be achieved. Or If database is been created via container and a web service which is not running in container, how that can access that database

**Comment by ndeloof** [comment]
Just like you would do for a non-containerized application, access this external service/database by it's connexion URL. The other way, if database is created in a container you can use docker "publish" options to expose it's port for external connnectivity.

You should look for a Docker introduction course/online video as this is basic docker usage, also check https://docs.docker.com/
