### ISSUE TITLE
Piped compose files failing in 1.25.0 release

### ISSUE THREAD

**Issue by NAlexPear** [docker/compose#7032]
## Description of the issue

Similar to the bug reported in #6981 during pre-release, it appears that all piping of compose files into `docker-compose` is resulting in an error. 

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.0, build unknown
```

**Output of `docker version`**
```
Client:
 Version:           19.03.5-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        633a0ea838
 Built:             Fri Nov 15 03:19:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.4-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.1
  Git commit:       9013bf583a
  Built:            Sat Oct 19 04:39:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.0.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  foo:
    image: busybox
version: '3.3'
```

## Steps to reproduce the issue

`cat docker-compose.yaml | docker-compose -f - up` (which works in 1.24.x when `docker-compose.yaml` is a valid compose file)

### Observed result

The compose process fails (trace included below)

### Expected result

The compose process should be the same as `docker-compose -f docker-compose.yaml up` (which still works as expected)

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 53, in project_from_options
    return get_project(
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 156, in get_project
    execution_context_labels(config_details, environment_file),
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 163, in execution_context_labels
    '{0}={1}'.format(LABEL_CONFIG_FILES, config_files_label(config_details)),
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 172, in config_files_label
    return ",".join(
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 173, in <genexpr>
    map(str, (os.path.normpath(c.filename) for c in config_details.config_files)))
  File "/usr/lib/python3.8/posixpath.py", line 336, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Additional information

**OS version**: Arch Linux
**install method**: `community/docker-compose` package (installed via `pacman`)

**Comment by ndeloof** [comment]
I was able to reproduce this issue, will investigate tomorrow

**Comment by ndeloof** [comment]
(bug was introduced by https://github.com/docker/compose/commit/dbe4d7323eb8d38c98cec2810469bcd65266edb0)

**Comment by NAlexPear** [comment]
@ndeloof this was a pressing enough issue for my team that I went ahead and pushed up PR #7035. This is a large enough regression, IMO, that it warrants a patch-level release as soon as possible, so let me know if there's anything that I can do to help!

**Comment by ndeloof** [comment]
@NAlexPear thanks a lot, I was working on a fix on my own and unfortunately didn't read your comment before... 

I indeed think this is a serious regression, but can't guarantee a short terms release, such a pitty we didn't cought this with RC :'(

**Comment by guillaumerose** [comment]
Outch! Sorry for the regression. Remove the annotation is probably the best thing to do (and add a e2e test for piped compose file :)).

**Comment by ndeloof** [comment]
I've added a testcase in https://github.com/docker/compose/pull/7037 
If I can't get a fix in a reasonable time that would not break current work on Desktop, I'll eventually remove the label so we have a fix for this issue.
