### ISSUE TITLE
Wildcard Secrets Grant

### ISSUE THREAD

**Issue by psytron** [docker/compose#7043]
It would be cool if one could specify  secrets:*  to grant a certain container access to all available secrets in the swarm.

**Comment by psytron** [comment]
Or maybe even fuzzy match like  secrets:  *.org_group

**Comment by ndeloof** [comment]
I'm pretty sure all security folks will veto such a thing.
Also, docker-compose secret support is unrelated to docker stack/swarm. This feature request should take place on github.com/moby/moby
