### ISSUE TITLE
Port empty when started with compose

### ISSUE THREAD

**Issue by LegatusLarvae** [docker/compose#7064]
Hello,

I want to start a Gitea container on my Windows machine. I used the official image from [Docker Hub](https://hub.docker.com/r/gitea/gitea) and the docker-compose file they published as quick start. However, when I try to open Gitea in my browser (localhost:3000) there is simply nothing, as if I never started the service. The terminal says everything started correctly, no error messages.

I tried starting jenkins and a local docker repositiory with compose, both work fine. Starting Gitea using run instead of compose works as well. Changing the compose and image version or port number does not make a difference. Restarting the services/docker/os didn't change anything.

 `docker ps` lists the services as running and ports mapped.

Since I'm new to docker I don't know what to do.

# Context information

```
Output of "docker version"

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
Output of "docker-compose version"

docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Comment by ndeloof** [comment]
Would make better sense to report this issue to Gitea project as you used the their quick start docker-compose file.

Would also help if you describe how you run gitea as a container, and compare with the docker-compose service definition
