### ISSUE TITLE
Firewall problem when run docker-compose up

### ISSUE THREAD

**Issue by amirhamdy** [docker/compose#7065]
I have a problem running this command `docker-compose up` 

error msg:
> Cannot create container for service react-app: b'Drive sharing seems blocked by a firewall

I tried to disable the firewall but no luck!

I tried too many solutions from docker documentation and Github submitted issues but also with no luck to fix the problem!

**Comment by ndeloof** [comment]
Please try to run a container with equivalent bind mount to confirm this is a docker-compose issue, or just a docker Desktop / docker engine one
