### ISSUE TITLE
docker-compose does nothing - even 'docker-compose version'

### ISSUE THREAD

**Issue by buerobuettner** [docker/compose#7080]
## Description of the issue
Installed Docker for Desktop and Docker Tools.
docker-compose does nothing - even 'docker-compose version' hangs in the command and never
returns.
Downloaded and installed DockerToolbox-19.03.1.exe

## Context information (for bug reports)

**Output of `docker-compose version`**
```
NOTHING happens
```

**Output of `docker version`**
```
Docker version 19.03.5, build 633a0ea
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
NOTHING happens
```

## Steps to reproduce the issue

1. open powershell
2. call 'docker-compose version'

### Observed result
nothing happens. does not return out of command

### Expected result
show version

### Stacktrace / full error message

```
don't know - nothing returns
```

## Additional information

I started and uploaded diagnose & feedback with id: 
26C7D6AB-B06E-43A8-8FB4-6249B9582AD3/20191204142634

**Comment by ndeloof** [comment]
Can you please clarify why you install both Docker for Desktop *and* Docker Toobox ? The later is obsolete and only provided for users who don't get a recent OS to meet minimal system requirements for the Docker Desktop

(https://docs.docker.com/toolbox/overview/)
