### ISSUE TITLE
Docker-compose pull  selectively ignores some services

### ISSUE THREAD

**Issue by jessesimpson36** [docker/compose#7081]
## Description of the issue
version 1.25.0  docker-compose pull only pulls 3 out of the 5 images in my docker-compose file. Version 1.24.0 does not have this issue.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.0, build b42d419
docker-py version: 4.1.0
CPython version: 2.7.15+
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Output of `docker version`**
```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:29:24 2019
 OS/Arch:           linux/ppc64le
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:27:31 2019
  OS/Arch:          linux/ppc64le
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
Cannot provide this. This includes private repositories, passwords, environment variables, and lists of exposed ports.
```

## Steps to reproduce the issue

1. write a docker-compose file of 5 images
2. run docker-compose pull
3. the `Pulling  <service>...` dialogue may ignore images. If it does, this error is successfully reproduced.

### Observed result
3 out of 5 images are pulled

### Expected result
All images are pulled

### Stacktrace / full error message

```
None,  docker-compose pull does not pull all of the images I need.
```

## Additional information
When I  run `docker-compose pull <ignored-service-name>`, the image is pulled successfully. without that argument, it is not.

`docker-compose config --services`  prints all of the service names, and  `docker-compose config` does not produce any errors, and v1.24.0 does not have this issue, so my docker-compose file should still be valid.

OS version / distribution, `docker-compose` install method, etc.
`apt install docker-compose`

**Comment by ndeloof** [comment]
Is this a duplicate for https://github.com/docker/compose/issues/6934 ?

**Comment by jessesimpson36** [comment]
Yeah. sorry about that, but I had no reason to think that the build context had anything to do with it's pull behavior. If I may make a suggestion, I would include something like
```
...
#  docker-compose pull
nobuild_image... done
image...   skipped
```

So I at least know this was intended behavior. 

or possibly allow
```
# docker-compose pull --all
```
for pulling all images regardless of the build context.

Maybe `image` should be decoupled from building vs pulling. the build argument could have a `tag` attribute that names the image after it's built, and `image` could just be used for pulling.

Whatever change you guys think would improve the system. I'm willing to make the change myself, and open a PR if you'd like.  The current behavior, which broke all of my deployment systems that run on ubuntu, is not acceptable without at least an alternative that allows for the old behavior of `docker-compose pull`.

**Comment by ndeloof** [comment]
not intended, this has been reverted in 1.25.1-rc1

**Comment by jessesimpson36** [comment]
Thank you
