### ISSUE TITLE
Make `--env-file` a repeatable option

### ISSUE THREAD

**Issue by khs1994** [docker/compose#7083]
**Is your feature request related to a problem? Please describe.**
`--env-file` support list (like `-f` do)，so one can use many env files, example `docker-compose --env-file a.env --env-file b.env`

**Describe the solution you'd like**
like `-f`, i want to use many `env file`.

**Describe alternatives you've considered**
we can exec `docker-compose --env-file a.env --env-file b.env`,use many env file

**Comment by ndeloof** [comment]
Sounds a reasonable enhancement.

Implementation is not even complex, I just noticed due to https://github.com/docopt/docopt/issues/275 we can't declare `--env-file` as a repeatable option without changing the top-level Usage sample, which would highlight this option over others in a weird way.

**Comment by hholst80** [comment]
Workaround for bash,
```
docker-compose --env-file <(cat a.env b.env)
```
