### ISSUE TITLE
Docker compose very slow on mac catalina

### ISSUE THREAD

**Issue by rizplate** [docker/compose#7087]
`docker-compose status` hangs when making any http call to docker daemon. It was fine using macOS Mojave, I upgraded to Catalina and not it is very slow

I tried all the solutions mentioned above, new `docker-compose` , using mac binaries etc.
docker compose is very slow on mac catalina, please provide fix

I have installed latest version of docker on mac, and also checked other fixes and bug reports i.e. https://github.com/docker/compose/pull/7010 and #6956

No fixes are working, it is still very slow

**Comment by ndeloof** [comment]
Please give 1.25.1-rc1 a try, relying on the tar.gz installation

**Comment by fxn** [comment]
I fetched the RC1 and it is still really slow, see

```
% time docker-compose --version
docker-compose version 1.25.1-rc1, build d92e9bee
docker-compose --version  0.51s user 0.15s system 4% cpu 14.944 total
```

Docker Desktop is 2.1.0.5.

**Comment by fxn** [comment]
My mistake, I overlooked the tarball bit.

With the tarball, and after allowing the execution of a bunch of files manually, it now runs normally. Thanks for the fix!

**Comment by rumpl** [comment]
@fxn what do you mean by `after allowing the execution of a bunch of files manually`?

**Comment by fxn** [comment]
I ran `docker-compose --version` and had to manually accept in System Preferences the following files:

```
docker-compose
_bcrypt.abi3.so
_cffi_backend.cpython-37m-darwin.so
_sodium.abi3.so
_constant_time.abi3.so
_openssl.abi3.so
```

You have to do this one by one. Try, aborts with messsage, approve, repeat.

**Comment by ndeloof** [comment]
Ok, so approval for software from a non approved apple developer.
Will disappear once compose get notarized within docker desktop distribution

**Comment by benlumia007** [comment]
I'm still having issues with this, macOS Catalina 10.15.2 is acting up.

**Comment by ndeloof** [comment]
@benlumia007 please report docker-copose version in use and packaging you're using (single binary vs tar.gz folder)

**Comment by benlumia007** [comment]
I have always used the Docker for Mac installation instead of installing them separately. 

docker-compose version 1.24.1, build 4667896b

**Comment by benlumia007** [comment]
i just also tested 1.25 and 1.25.1-rc1, is the same thing. am i doing something wrong.

**Comment by benlumia007** [comment]
I eventually added 127.0.0.1 api.apple-cloudkit.com to the hosts file and now is fine. when i use 1.24 by default.

**Comment by ndeloof** [comment]
By using 1.25.* you need to select the tar.gz installation, not the single 'darwin' binary, to get rid of this issue. Etc/hosts hack can only be considered a temporary workaround

**Comment by benlumia007** [comment]
hye, so im little confused. I download the docker-compose-Darwin-x86_64.tgz and unzip it, what else do i need to do. i  never done this way.

**Comment by ndeloof** [comment]
setup PATH (or symlink) so that the `docker-compose` command you execute run the binary within this folder.
Please note Docker Desktop Edge channel do include this 1.25.1-rc1 "tar-gz" packaging

**Comment by benlumia007** [comment]
ok, I will try that, but in the meantime, do you know when the latest docker-compose will be available as part of the docker desktop for mac installation.

**Comment by chetzof** [comment]
> I eventually added 127.0.0.1 api.apple-cloudkit.com to the hosts file and now is fine. when i use 1.24 by default.

Thanks, that's the only thing that worked. Suggestions about adding localunixsocket to host no longer relevant

**Comment by SteffenAnders** [comment]
We have solved the problem by installing docker-compose as a container. 
See https://docs.docker.com/compose/install/ → "Alternative Install Options".

```
sudo curl -L --fail https://github.com/docker/compose/releases/download/1.26.0/run.sh -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

docker-compose --version
```
