### ISSUE TITLE
check if docker daemon is working

### ISSUE THREAD

**Issue by Anuren** [docker/compose#7088]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
(paste here)
```

**Output of `docker version`**
```
(paste here)
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by Anuren** [comment]
![Screenshot (44)](https://user-images.githubusercontent.com/54096141/70433083-c2019b80-1aa6-11ea-81aa-62bffb9af8cd.png)

**Comment by Anuren** [comment]
![Screenshot (46)](https://user-images.githubusercontent.com/54096141/70433266-3f2d1080-1aa7-11ea-85a4-30b42f06d9cc.png)

**Comment by ndeloof** [comment]
This repository is about docker-compose, not plain docker.
If you can't get docker to run, please first ask on docker forums
