### ISSUE TITLE
Run tmux command

### ISSUE THREAD

**Issue by karellm** [docker/compose#710]
Hi,

I'm trying to setup a development environment for a project using fig. My web container has `tmux` installed and I want to be able to `fig up` or `fig run` into this tmux session.

The problems I see are that `fig run` doesn't forward ports (#163) and that `fig up` doesn't attach a tty and thus throw an `open terminal failed: not a terminal` error.

Any suggestion on how I am supposed to get this running?

**Comment by Neppord** [comment]
@dnephin I try to use fig with `tmux`, from within the container.

I have a problem where `tmux` panes sometimes can start to paint into another one. Also i can get multiple status bars painted. Seams like there is some positioning or size data that gets corrupted. 

I don't have the same problem logging into boot2docker and running the image from in there.

what consistently trigger this is running gulp task (that i cant share) and splitting and un-splitting the window.

Any clues to why? and what part of the pipeline fig adds?
