### ISSUE TITLE
Support ${parameter:+word} style variable substitution

### ISSUE THREAD

**Issue by andrewodri** [docker/compose#7102]
Most continuous integration systems have a `$CI` variable to that acts as a flag that lets you know when you're in a CI environment. While `docker-compose.yml` allows for substitution when a variable **is not** defined/set (e.g. [`${parameter:-word}`](https://docs.docker.com/compose/compose-file/#variable-substitution)), it would be great to allow for substitution when a variable **is** defined/set.

Bash allows you to define this with [the following syntax](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html):

> `${parameter:+word}`
> 
> If _parameter_ is null or unset, nothing is substituted, otherwise the expansion of _word_ is substituted.

Here are some examples of some CI systems/services that support the `$CI` flag:

* https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
* https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
* https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference

**Comment by thaJeztah** [comment]
I think the official specs (non-bash) can be found here; https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html

**Comment by ndeloof** [comment]
Sounds reasonable to me, both because this would enable interesting use-cases like the one you describe, and also because this would make the syntax consistent with what any shell script author would expect.

**Comment by ndeloof** [comment]
We probably could support most or all [bash parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html).
I wonder we could use `os.Expand` directly ?

**Comment by thaJeztah** [comment]
I'd generally prefer sticking to the POSIX set of options, otherwise we'd end up implementing regex matching and the whole shebang

**Comment by bradynpoulsen** [comment]
Following POSIX, would the substitution value also be evaluated for values?

 My use-case is I'm wanting to conditionally pass a value in my `command` when a value is set
```yaml
services:
  my-service:
    command: |
      -abc
      --do-something
      ${MY_DEFAULT_PASSWORD+--with-default-credentials "${MY_DEFAULT_USERNAME:-user}:${MY_DEFAULT_PASSWORD}"}
```

My workarounds are currently limited to:
1. throw a substitution error
    ```
    --with-default-credenitals "${MY_DEFAULT_USERNAME:-user}:${MY_DEFAULT_PASSWORD?Password is required!}"
    ```
2. inject a custom bash script that I can override the `entrypoint` to run the original entry point, with the command arguments, and run the same substitution I specified above
