### ISSUE TITLE
Isn't there a python API like docker-py? PiPy has a listing for a docker-compose one but it seems to just install this CLI

### ISSUE THREAD

**Issue by StingyJack** [docker/compose#7105]
> Please post on our forums: https://forums.docker.com for questions about using `docker-compose`.

No, you have this here, and I dont want to go creating another account. 

> Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker.

Then Why Do You Have A Choice On Here For Questions?  And why does docker act so jerky to those who need help with their programs?

**Comment by ndeloof** [comment]
posting questions on forums let you benefit for community contributors who can assist you. This issue tracker is for project development, and as you can easily imagine maintainers prefer invest time in fixing bug and not spend a whole day answering usage questions. As many still use it for this purpose, we prefered to include a "question" option to offer basic triage.

I'm not sure I understand your question. Isn't https://github.com/docker/docker-py what you're looking for ?

**Comment by StingyJack** [comment]
@ndeloof - if that doesnt let me manage a multicontainer app, then no, its not what I'm looking for. I got around the immediate problem by just shelling out the docker compose commands. It would be nice to not have to parse STDOUT/ERR though, hence the question in the title.

**Comment by ndeloof** [comment]
ok got it.
docker-compose is publised on https://pypi.org/project/docker-compose/
that being said, docker-compose has not been designed as a python library to be used by thrid party tools, so we don't guarantee code-level backward compatibility, and  refactoring we might apply in future release could break your usage.

so, to answer your question "Isn't there a python API", official answer is "No", pragmatic asnwer is "Yes, at your own risks"
