### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by 2063113624** [docker/compose#7109]
I install docker-compose with run.sh,but when I run docker-compose --version it appear error "/usr/local/bin/docker-compose: exec: line 63: docker: not found

**Comment by saeed667** [comment]
With which docker-compose command check your installation status . 
It can be because of version difference , you can install docker compose with
sudo apt-get install docker-compose

**Comment by ndeloof** [comment]
`run.sh` do not install docker-compose, it run it inside a container so you don't have to install it. But to run a container you obivously need docker available on your computer.

Prefer standard installation by standalone binary
