### ISSUE TITLE
docker-compose needs to rebuild after "bundle install"

### ISSUE THREAD

**Issue by gaddevarunteja** [docker/compose#7117]
**Is your feature request related to a problem? Please describe.**
After doing "docker-compose run app bundle install" it adds gems in cached way, but if I need to run the app it does not work. I need to rebuild the image, which installs gems in non-cached way. can you figure out an alternative solution for this, to fasten the build process.

**Describe the solution you'd like**
Reduce bundle install process time by not rebuilding the image again.

**Describe alternatives you've considered**
docker-compose run app bundle install
docker-compose build

**Comment by gaddevarunteja** [comment]
Is there a way to fasten bundle install process(by using cache i.e without rebuilding image) or Is it the case that everyone is using the time taking bundle install process?

**Comment by ndeloof** [comment]
`docker-compose run` only execute configured container, it's not aware of the intent for command being executed, and not responsible for image lifecycle. Your question afaict is about best practices for (imutable) container image management, and dependency caches. compose issue tracker is not the right place to ask for this, please check docker-related forums, or maybe better ruby forums where many more people probably have good tips for you on this topic.
