### ISSUE TITLE
compose should detect engine is remote and can't support bind-mount from local files

### ISSUE THREAD

**Issue by ndeloof** [docker/compose#7125]
# Description of the issue

docker-compose do support local bind-mounts for volumes, as well as mock implementation for secrets and config (not natively supported by docker engine without swarm). As a result, user can shoot into their own foot when using an (actual) remote Docker host

## Steps to reproduce the issue

1. create a docker-compose file with a relative path volume | secret | config
2. connect to a remote docker engine
3. run docker-compose up

### Observed result

compose run containers with bind mounts for paths which do not make any sense on host (make it worse when client in Windows)

### Expected result

compose do warn such bind-mount is not supported with a remote engine

## Additional information
see https://github.com/docker/compose/issues/7110

**Comment by ndeloof** [comment]
A possible way to detect engine is "local" is to check DOCKER_HOST protocol is 
`unix` or `npipe` but not `tcp`

**Comment by per-bohlin** [comment]
I personally making use of the current behavior on purpose. So if the warning is implemented, please make sure that the check can be turned off.
Also, it is a common setup to use TCP when running Docker Desktop + WSL on Windows, hence the bind-mount is valid despite TCP. Therefor, the check can not be as simple as looking at the protocol.
