### ISSUE TITLE
Fund PyInstaller development

### ISSUE THREAD

**Issue by htgoebel** [docker/compose#7129]
Docker compose uses PyInstaller for distributing installable packages.

PyInstaller is in urgent need of funding:

**If reasonable funding is not achieved for PyInstaller until end of January 2020, @htgoebel will retire as an maintainer.** This basically means: Unless somebody else steps in, there will be nobody reviewing any pull-request, there will be not improvement and sooner or later you will not be able to use PyInstaller any more - and open issues in Docker Compose related to PyInstaller might not be solved.

For details see https://github.com/pyinstaller/pyinstaller/issues/4404.

**Comment by chris-crone** [comment]
Thank you for the work that you've done on PyInstaller and for letting us know. This is not the right forum to discuss this so I'm closing this issue and [have reached out via email](http://www.pyinstaller.org/funding.html#funding-by-companies).
