### ISSUE TITLE
CPU pinning not possible with v3 compose

### ISSUE THREAD

**Issue by qlyoung** [docker/compose#7130]
## Description of the issue

Compose v3 does not support CPU pinning.

## Context information (for bug reports)

Based on the config schema there is no extant option for specifying core pinning on a service, which I'd expect to be under the `deploy` section. This seems like a bug. CPU pinning is essential for some workloads.

**Comment by qlyoung** [comment]
no

**Comment by qlyoung** [comment]
no

**Comment by ndeloof** [comment]
Isn't https://github.com/compose-spec/compose-spec/blob/master/spec.md#cpuset what you're looking for ?

**Comment by qlyoung** [comment]
Yes. Looks like that was added in June 2020; I opened this issue in January 2020.

Fixed by: https://github.com/compose-spec/compose-spec/pull/78

Thank you!
