### ISSUE TITLE
Extract progress stream logic into a separate library

### ISSUE THREAD

**Issue by delfick** [docker/compose#714]
Hello,

I was wondering if the progress stream logic could be extracted out into a separate library similar to the situation with dockerpty.

I'd love to be able to use it in the docker client I've built, but don't want to just copy paste it.

Thanks.

Stephen.

**Comment by dnephin** [comment]
I'd suggest opening a PR against `docker-py`. This issue is not really actionable on the compose issue tracker.

Or even just copy it out into a new library!
