### ISSUE TITLE
Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found

### ISSUE THREAD

**Issue by MikeAlhayek** [docker/compose#7146]
I am trying to run an ASP.NET Core 3.1 framework based app on an Ubuntu (18.04.3 LTS) server using Docker container.

First I created run the `nginx-proxy` image using the following docker-compose.yml` file

    version: '3.4'
    services:
      nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
    
    networks:
      default:
        external:
          name: nginx-proxy
    secrets:
      server.cert:
        file: ./server.cert
      server.key:
        file: ./server.key

Both `server.cert` and `server.key` files are stored next to the `docker-compose.yml` file and were created using the following command

    sudo openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj "/C=US/ST=CA/L=SF/O=Docker-demo/CN=nginx-proxy.example.com" -keyout server.key -out server.cert

I ran that image using `docker-composer up -d` command.

Now that my nginx proxy is running, I created my first app using the following `docker-composer.yml` file

    version: '3.4'
    
    services:
      private_image:
        image: private_image:latest
        environment:
          - VIRTUAL_HOST=sub.domainsname.com
          - ASPNETCORE_ENVIRONMENT=Production
          - ASPNETCORE_URLS=https://+:443;http://+:80
        expose:
          - 80
          - 443
        ports:
          - 51736:80
          - 44344:443
        volumes:
          - storage:/storage
          - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        container_name: realestatestorage
    volumes:
      storage:
    networks:
      default:
        external:
          name: nginx-proxy
    secrets:
      sub.domainsname.com.cert:
        file: ./sub.domainsname.com.cert
      sub.domainsname.com.key:
        file: ./sub.domainsname.com.key

Both `sub.domainsname.com.cert` and `sub.domainsname.com.key` files are stored next to the `docker-compose.yml` file and were created using the following command

    sudo openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj "/C=US/ST=CA/L=SF/O=PrivateImage/CN=sub.domainsname.com" -keyout sub.domainsname.com.key -out sub.domainsname.com.cert

When I run my private image using `docker-compose up` I get the following

    WARNING: The APPDATA variable is not set. Defaulting to a blank string.
    Recreating private_image ... done
    Attaching to private_image
    private_image    | crit: Microsoft.AspNetCore.Server.Kestrel[0]
    private_image    |       Unable to start Kestrel.
    private_image    | System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
    private_image    | To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
    private_image    | For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
    private_image    |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
    private_image    |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
    private_image    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
    private_image    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
    private_image    |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
    private_image    | Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
    private_image    | To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
    private_image    | For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
    private_image    |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
    private_image    |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
    private_image    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
    private_image    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
    private_image    |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
    private_image    |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
    private_image    |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
    private_image    |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
    private_image    |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
    private_image    |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
    private_image    |    at private_image.Program.Main(String[] args) in /src/private_image/Program.cs:line 17
    private_image exited with code 139

The command `dotnet dev-certs https --trust` works on Windows and macOS only. But how can I fix this issue on Ubuntu?

**Comment by caiocsgomes** [comment]
Have you found a solution? I'm facing the same issue

**Comment by CSharp-WebDev** [comment]
I'm experiencing the same issue here. Ubuntu's service with "dotnet myapp.dll" would not work. It's displaying the same exact error message.

**Comment by profjordanov** [comment]
Me too :(

**Comment by jforward5** [comment]
Any idea on the fix?

**Comment by tomaszek92** [comment]
Same problem

**Comment by HitchBmv** [comment]
same issue for me...

the command `dotnet dev-certs https --trust` doesn't exist for me (using sdk 2.2)

**Comment by HitchBmv** [comment]
@CrestApps 
Did you try to use pfx file instead of cert files?

**Comment by omidnasiri** [comment]
Same issue here...

**Comment by sujan-c2** [comment]
hello guys 
any update on this?

**Comment by JordanWestern** [comment]
I am also facing this issue so any help would be appreciated.

**Comment by AaronYll** [comment]
hello guys
any update on this?

**Comment by joaquinferroni** [comment]
Hi guys, I had the same issue and I add two main things into my project configuration:
in appsettings.json, add a new key for Kestrel:
"Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://+:5000"
      },
      "HttpsInlineCertAndKeyFile": {
        "Url": "https://+:8443",
        "Certificate": {
          "Path": "path to your .crt",
          "KeyPath": "path to your.key"
        }
      },
      "HttpsDefaultCert": {
        "Url": "https://+:5004"
      }
    }
  }

Then in the dockerfile you should add the paths also 
ENV ASPNETCORE_Kestrel__Certificates__Default__Path="path to .crt"
ENV ASPNETCORE_Kestrel__Certificates__Default__KeyPath="path to .key"

Of course you need to expose the 8443 in my case (but you define the port or use the default 443)
Hope this help someone

**Comment by adbakhram** [comment]
hello guys
any update on this?

**Comment by ndeloof** [comment]
In the initially reported compose.yaml file, none of the secrets (`server.cert`, `server.key`) is referred to by a service, so they are just ignored. A service has to explicitly request access to a secret, see [secrets](https://github.com/compose-spec/compose-spec/blob/master/05-services.md#secrets)
