### ISSUE TITLE
docker-compose up brings up extra containers which docker-compose down doesn't remove

### ISSUE THREAD

**Issue by fnatiq** [docker/compose#7147]
## Description of the issue
docker-compose up brings up extra containers which docker-compose down doesn't remove

I can't show much information as this is a company-classified project, but I'm using CentOS7 and docker 3. There are containers that are brought up by "docker-compose up", that do not go down when I type "docker-compose down", and that are causing port locking issues (these are dockerised APIs). These containers also do not disappear when I kill these ports using "kill -9 $(lsof -t -i:PORT_NUM)".

These extra containers also have a different name shown (e.g. I am in folder XYZ and my expected services have names XYZ_.... while these extra ones are named ABC_...), so I was wondering if Compose is somehow using multiple yml files in its "up", but there aren't any others in my current working directory.

Am trying to write a crontab that stops and starts my Docker services. Any help is appreciated, thank you!

**Comment by ndeloof** [comment]
We hardly can diagnose this issue without a reproduction scenario.

Please `docker inspect` such ABC_* container and check for labels, to confirm those are created by docker-compose

Does by chance any of your services bind mount `docker.sock`, which would mean your application do create additional containers outside control from docker-compose ?

**Comment by jyjyj** [comment]
Hi, I have used inspect and found that I had Swarm enabled, which was creating extra containers based on its defined namespace. I still deployed using docker-compose up; do you know why doing so with Swarm enabled would create double containers for each of my services? Thanks for the tip!
