### ISSUE TITLE
ERROR: Couldn’t connect to Docker daemon at http+docker://localhost - is it running?

### ISSUE THREAD

**Issue by basilin** [docker/compose#7149]
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

I am getting the above error on Ubuntu 18 machine when running docker compose on jenkins workspace `/var/lib/jenkins/workspace`

```
docker-compose version 1.25.1, build a82fef07
```
```
Docker version 19.03.5, build 633a0ea838
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```
```
systemctl status docker.service

Jan 16 06:57:53 Wdsys dockerd[19160]: time="2020-01-16T06:57:53.569004581Z" level=error msg="Handler for POST /v1.30/build returned error: invalid reference format"
```

**Comment by ndeloof** [comment]
Can you please clarify which docker-compose command produce this error ?
Can you also please try to reduce your dokcer-compose.yml file to a minimalist sample to reproduce this error ?

**Comment by qalinn** [comment]
@basilin  did you find a solution ?

**Comment by drkstr101** [comment]
I was getting the same error. Needed `sudo`, or `docker`group assignment to the user running the command.

**Comment by j-sal** [comment]
> I was getting the same error. Needed `sudo`, or `docker` group assignment to the user running the command.
Using `sudo` worked for me as well
