### ISSUE TITLE
Executing docker-compose from an parent directory from docker-compose with .env is not working.

### ISSUE THREAD

**Issue by JohanSpannare** [docker/compose#7153]
Here is an simple docker-compose.yml and a .env file. The idea is to use .env to set the TAG to use in the image for service.

**docker-compose.yml**

`version: "3.7"
services:
  service:
    image: seb/service:${MY_TAG:-latest}
`

**.env**

`MY_TAG=v1.0
MY_FULL_TAG=v1.0-12345`

If i run docker-compose -f docker-compose.yml from within the same directory as the docker-compose.yml and .env file. Everything works as expected.

But if i run the docker-compose from an parent directory, it will not respect the .env file.

Example1 (**works**):
`docker-compose -f .\docker-compose.yml config`

`services:
  service:
    image: seb/service:v1.0
version: '3.7'
`

Example2 (**not working**):
`docker-compose -f .\dockerfiles\docker-compose.yml config`

`services:
  service:
    image: seb/service:latest
version: '3.7'`

If i try to declare the .env file inside the docker-compose like 
`env_file: ./dockerfiles/.env`
i get an error message
**ERROR: Couldn't find env file: C:\temp\dockerfiles\dockerfiles\dockerfiles\.env**

So my conclusion is that docker-compose is not working correctly when it comes to using -f and having the .env in the same directory as the docker-compose.yml file. And if i specify the path inside the docker-compose file, it is clearly already using it due to the error message.

Workaround is to have the .env file in the same directory as the command is executing, not using relative paths to docker-compose.yml files.

**Comment by sadnub** [comment]
I am having a similar issue but with the `docker-compose -f <custom-file.yml> up` command. It seems that variable interpolation isn't working with the .env file. I even tried 
`docker-compose --env-file .env -f <custom-file.yml> up`

Here is the directory structure:
-docker
  --docker-compose.yml  <-- for prod
  --docker-compose.dev.yml  <-- for dev
  --.env

If I run `docker-compose up` for the prod env it works. If I rename the dev file to docker-compose.yml it also works.

It seems the -f option isn't correctly reading the .env file with the up command. If I use -f with the config command it actually works as expected.

Running `docker-compose -f docker-compose.dev.yml up` produces with a default postgres image.
![image](https://user-images.githubusercontent.com/20450757/76146847-6f635b80-6064-11ea-8088-f6bf60e2c43d.png)

docker-compose snippet
```
  # Postgres Database for API service
  db:
    image: "postgres"
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
```

.env snippet
```
POSTGRES_USER=postgres
POSTGRES_PASS=pass
POSTGRES_DB=db_name
```
Is this potentially a bug with the up command? Seems to be something with the -f argument for the up command.

Thanks!
