### ISSUE TITLE
compose ignoring IPv6 docker settings

### ISSUE THREAD

**Issue by hadmut** [docker/compose#7154]
Hi, 
on several machines with Ubuntu 18.04 (docker compose 1.17) and 19.10 (compose 1.21) I've experienced the problem, that docker-compose-created networks ignore IPv6 settings or at least do not assign IPv6 addresses to containers. I'm aware that the current version is 1.25, but I didn't see any entries about that in the Changelog, so I guess the problem is still there. 

I've configured docker to use IPv6 in /etc/docker/daemon.json and given a default network, and containers started with regular docker automatically get an IPv6 address assigned. 

This does not work with docker-compose, not even when defining networks with IPv6 in the docker-compose file. 

When googleing the problem, you'll find some workarounds which solve the problems by manually deleting the docker networks created by docker-compose and manually recreating them with IPv6 settings, telling that once the network is created in a proper way, IPv6 works even with docker-compose. However, such workarounds are annoying and error prone. 

Docker compose should treat IPv6 in the same way as IPv4, i.e. automatically assign network addresses and ranges, if not given in the docker-compose.yaml, and obey the settings if given. 

Nowadays it is becoming production-critical to be able to talk IPv6. 

regards

**Comment by jackadam1981** [comment]
I also encountered this problem.

Trying V2
