### ISSUE TITLE
Release 1.25.2-rc1

### ISSUE THREAD

**Issue by ulyssessouza** [docker/compose#7156]
PR -> https://github.com/docker/compose/pull/7155

**Comment by bastianeicher** [comment]
Something seems to have gone wrong with the automatic release process:

[docker-compose-Linux-x86_64](https://github.com/docker/compose/releases/download/1.25.2-rc1/) and [docker-compose-Darwin-x86_64](https://github.com/docker/compose/releases/download/1.25.2-rc1/docker-compose-Darwin-x86_64) are both 33 bytes small and contain only the string `The requested path was not found.`.  
[docker-compose-Windows-x86_64.exe](https://github.com/docker/compose/releases/download/1.25.2-rc1/docker-compose-Windows-x86_64.exe) is 47 bytes and contains the string `{"message":"Build not found or access denied."}`.

**Comment by ulyssessouza** [comment]
@bastianeicher We are investigating. Looks like a CI issue, but not sure yet.

**Comment by ulyssessouza** [comment]
[1.25.2](https://github.com/docker/compose/releases/tag/v1.25.2) is released
