### ISSUE TITLE
Latest release tagged with 'v'

### ISSUE THREAD

**Issue by lsanders** [docker/compose#7168]
## Description of the issue

The tagging naming scheme changed with 1.24.2. Was this intended? This may break some automation (it did for me).

## Context information (for bug reports)

This isn't a bug, but I thought I'd report it since it seems that bootstraping via curl is fairly common. We had startup scripts like this:

```
export latest_stable_compose=`git ls-remote https://github.com/docker/compose | grep refs/tags | grep -oP "[0-9]+\.[0-9][0-9]+\.[0-9]+$" | tail -n 1`
sudo curl -L https://github.com/docker/compose/releases/download/${latest_stable_compose}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compos
```

That we probably snagged from some other example. In order to fix for our purposes, it was just a small change to the regex to optional consider leading `v` (`v*`):

```
export latest_stable_compose=`git ls-remote https://github.com/docker/compose | grep refs/tags | grep -oP "v*[0-9]+\.[0-9][0-9]+\.[0-9]+$" | tail -n 1`
```

**Output of `docker-compose version`**
```
docker-compose version 1.25.2, build 698e2846
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
n/a
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
n/a
```

## Steps to reproduce the issue

1. Automate docker-compose download with semver like regex, not considering `v` prefix

### Observed result

Automation fails - docker-compose not downloaded

### Expected result

docker-compose downloaded

**Comment by albers** [comment]
It definitively breaks the download instructions on https://docs.docker.com/compose/install/

> Run this command to download the current stable release of Docker Compose:
>
> sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
>
>To install a different version of Compose, substitute 1.25.0 with the version of Compose you want to use.

**Comment by esetnik** [comment]
It also broke the link in the release notes https://docs.docker.com/docker-for-mac/release-notes/.

https://github.com/docker/compose/releases/tag/1.25.2

**Comment by x-jokay** [comment]
@ulyssessouza can you enlight us, if tagging the version including `v` will be the new default?

**Comment by ndeloof** [comment]
We indeed switched to a new release process since 1.25 (https://github.com/docker/compose/pull/7133)

There's no technical reason tags should be named `vx.y.z` (was just alligned with other docker projects and relase process) so we for sure can just use `x.y.z` to maintain compatibility

**Comment by bryanpedini** [comment]
> We indeed switched to a new release process since 1.25 (#7133)

Sure, but take a look at [1.25.1](https://github.com/docker/compose/releases/tag/1.25.1) and prior releases (as stated in docker-compose [install documentation](https://docs.docker.com/compose/install/)): those versions don't have any prepending `'v'`, so the automation script might have worked for a little while without any `v` and inserted it only in last version ([1.25.2](https://github.com/docker/compose/releases/tag/v1.25.2)), which is the only one broken (based on the [install documentation](https://docs.docker.com/compose/install/)) as of now.

**Comment by albers** [comment]
I think the release tag should be identical to the output of `docker-compose version --short` and consistent with the output of `docker-compose --version` (i.e. no leading "v").

**Comment by lsanders** [comment]
If it's a contentious topic, you could opt to add both tags, no?

**Comment by thaJeztah** [comment]
I think we should at least have the non-prefixed tag (same commit, just a new tag pushed).

Having a `v` prefix _is_ commonly used, but not strictly needed (in fact, for repositories that use SemVer, it's actually non-compliant; unfortunately for repositories using Golang, `go mod` enforces the `v` prefix, so for those, the prefix is needed).

**Comment by ndeloof** [comment]
1.25.1 and prior releases didn't used this new release script. 1.25.2 was the first one. And documentation made this mistake to use v prefix - not because we want or need it for docker-compose, just because I used to.
Next patch release will remove this
