### ISSUE TITLE
v1.25.2 Windows x86_64 checksum file looks busted

### ISSUE THREAD

**Issue by andrewrothstein** [docker/compose#7174]
curl -sSL https://github.com/docker/compose/releases/download/v1.25.2/docker-compose-Windows-x86_64.exe.sha256

produces some non printable characters which throws off the terminal.

**Comment by laurin1** [comment]
I'm assuming the same issue is causing the file to be detected by virus scanners as infected.

https://www.virustotal.com/gui/file/d48da6103d164d13604105a3057f59869fd454f40907068ec7848772f6c1930c/detection

**Comment by thaJeztah** [comment]
ping @ndeloof @ulyssessouza PTAL

**Comment by thaJeztah** [comment]
Comparing the current one with an older release;

Compose: 1.25.0 (https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Windows-x86_64.exe.sha256):

```
a5dde54d360de1972758bcde20f7eeee5a8d13a9a6b1921198c17616eee51f3e  docker-compose-Windows-x86_64.exe
```

Compose 1.25.2:

```
D48DA6103D164D13604105A3057F59869FD454F40907068EC7848772F6C1930C *docker-compose-Windows-x86_64.exe
```

Looks like the current one;

- is in all-caps (probably not an issue?)
- has an asterisk (`*`) in front of the binary name 



There's indeed some non-printable characters at the start (BOM header perhaps?), and the file looks to be in UTF-8/UTF-16? (twice the size of the old one)

```bash
hexdump -C docker-compose-Windows-x86_64.exe.sha256
00000000  ff fe 44 00 34 00 38 00  44 00 41 00 36 00 31 00  |..D.4.8.D.A.6.1.|
00000010  30 00 33 00 44 00 31 00  36 00 34 00 44 00 31 00  |0.3.D.1.6.4.D.1.|
00000020  33 00 36 00 30 00 34 00  31 00 30 00 35 00 41 00  |3.6.0.4.1.0.5.A.|
00000030  33 00 30 00 35 00 37 00  46 00 35 00 39 00 38 00  |3.0.5.7.F.5.9.8.|
00000040  36 00 39 00 46 00 44 00  34 00 35 00 34 00 46 00  |6.9.F.D.4.5.4.F.|
00000050  34 00 30 00 39 00 30 00  37 00 30 00 36 00 38 00  |4.0.9.0.7.0.6.8.|
00000060  45 00 43 00 37 00 38 00  34 00 38 00 37 00 37 00  |E.C.7.8.4.8.7.7.|
00000070  32 00 46 00 36 00 43 00  31 00 39 00 33 00 30 00  |2.F.6.C.1.9.3.0.|
00000080  43 00 20 00 2a 00 64 00  6f 00 63 00 6b 00 65 00  |C. .*.d.o.c.k.e.|
00000090  72 00 2d 00 63 00 6f 00  6d 00 70 00 6f 00 73 00  |r.-.c.o.m.p.o.s.|
000000a0  65 00 2d 00 57 00 69 00  6e 00 64 00 6f 00 77 00  |e.-.W.i.n.d.o.w.|
000000b0  73 00 2d 00 78 00 38 00  36 00 5f 00 36 00 34 00  |s.-.x.8.6._.6.4.|
000000c0  2e 00 65 00 78 00 65 00  0d 00 0a 00              |..e.x.e.....|
000000cc
```


Which is not in the old one;

```bash
hexdump -C docker-compose-Windows-x86_64.exe.sha256

00000000  61 35 64 64 65 35 34 64  33 36 30 64 65 31 39 37  |a5dde54d360de197|
00000010  32 37 35 38 62 63 64 65  32 30 66 37 65 65 65 65  |2758bcde20f7eeee|
00000020  35 61 38 64 31 33 61 39  61 36 62 31 39 32 31 31  |5a8d13a9a6b19211|
00000030  39 38 63 31 37 36 31 36  65 65 65 35 31 66 33 65  |98c17616eee51f3e|
00000040  20 20 64 6f 63 6b 65 72  2d 63 6f 6d 70 6f 73 65  |  docker-compose|
00000050  2d 57 69 6e 64 6f 77 73  2d 78 38 36 5f 36 34 2e  |-Windows-x86_64.|
00000060  65 78 65 0a                                       |exe.|
00000064
```

**Comment by ndeloof** [comment]
this one is produced by 
`powershell "(Get-FileHash -Path ${filepath} -Algorithm SHA256 | % hash) + ' *${filepath}' > ${filepath}.sha256"`

**Comment by ndeloof** [comment]
so powershell defaults to producing UTF-8 files, and we need to force ASII output here. (Thanks @thaJeztah for the catch)

**Comment by ndeloof** [comment]
> has an asterisk (*) in front of the binary name

This is the output of `openssl sha256` using `-r` option: coreutils syntax, which is expected to be the same used by programs sha1sum. I'm looking for a way to get rid of this

**Comment by ndeloof** [comment]
reading coresutils man:

> For each file, ‘md5sum’ outputs by default, the MD5 checksum, a space, a flag indicating binary or text input mode, and the file name. Binary mode is indicated with ‘*’, text mode with ‘ ’ (space).

sha256sum uses text mode by default, while openssl uses binary by default. To create checksum for compose releases, binary is more relevant imho. wdyt ?

**Comment by thaJeztah** [comment]
TIL; but yes that sounds good
