### ISSUE TITLE
UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed. On compose build

### ISSUE THREAD

**Issue by hostmit** [docker/compose#7179]
I'm hitting this error while building in parallel 12 services (6 concurrent, IO intensive build  on SSD compute instance). Happens occasionally but it does.
```
ERROR: for Dashbrd  UnixHTTPConnectionPool(host='localhost', port=None): Pool is closed.
Couldn't connect to Docker daemon at http+docker://localhost - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```
Retrying same build helps. I looked through the daemon log - no visible errors found.

```
Docker version 19.03.5, build 633a0ea838
docker-compose version 1.24.1, build 4667896b
```

I've increased `COMPOSE_HTTP_TIMEOUT`, but I dont think that's the problem.

The strange thing is I get the same behavior while building under `DIND`.

Any solution known in 2020?

**Comment by isushilksharma** [comment]
Same error - ERROR: for robo-nsecom-jacoco_kafka_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=120)

Though I've used below - 

export DOCKER_CLIENT_TIMEOUT=120
export COMPOSE_HTTP_TIMEOUT=120

But it didn't worked at all - 
Restarted docker/ docker daemon but nothing positive happened, let here know if there's any possible solution.

**Comment by isushilksharma** [comment]
It got resolved, after restarting docker.
Sometimes, you;ve to restart services - seems it's a docker-compose issue.

**Comment by karniemi** [comment]
This "Pool is closed." is still an issue, at least on RHEL7 ie. docker-compose.noarch:1.18.0-4.el7 from the epel-repository.
( @isushilksharma's "Read timed out."  issue is different )
