### ISSUE TITLE
docker-compose 1.25.1 buildkit support and --ssh option

### ISSUE THREAD

**Issue by hecbuma** [docker/compose#7184]
Hi 

it's great being available to use the buildkit options with the latest docker-compose version thanks for the amazing work around this.

Now, I'm trying to use `--ssh` which is described here https://docs.docker.com/develop/develop-images/build_enhancements/#using-ssh-to-access-private-data-in-builds I'm able to do it with docker CLI but I don't know how to pass the --ssh option while building with docker-compose
```
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
```

is it possible?

**Comment by Maks3w** [comment]
Duplicated of https://github.com/docker/compose/issues/7025

**Comment by sajusat** [comment]
@hecbuma @Maks3w Please implement this as soon as possible. It is a really pain to do the docker build separately with --ssh option. I have been waiting for a while now...

**Comment by sajusat** [comment]
It has been more than a year. Unfortunately at job I have used this feature to build a lot of docker images referring the ssh keys. Now I am stuck... I have to build separately and use those images with docker-compose. Whenever there is a change in the dockerfile l have to build separately. 
Please state clearly about the state of the this feature. Will it be implemented or not.

**Comment by ArcticSnowman** [comment]
bump...

**Comment by thegass** [comment]
anyone working on this?

**Comment by AdemUstaReminiz** [comment]
Any update on this ?

**Comment by itsjef** [comment]
I don't know why it is extremely quiet on this issue :joy:

**Comment by shawnwall** [comment]
I'm needing this also. bump.

**Comment by ferm10n** [comment]
This is a duplicate of https://github.com/docker/compose/issues/7025, focus should be directed there and this issue should be closed
