### ISSUE TITLE
docker-compose and docker-machine not working after installing Docker Desktop for Mac

### ISSUE THREAD

**Issue by rahman-mahfuz** [docker/compose#7185]
Hi,

I have installed Docker Desktop for Mac on my Mac with macOS Sierra version 10.12.6

Docker is working fine but when I run "docker-compose --version" to check whether docker-compose is installed properly, it shows the following error:

[8807] Error loading Python lib '/Applications/Docker.app/Contents/Resources/bin/docker-compose/.Python': dlopen: dlopen(/Applications/Docker.app/Contents/Resources/bin/docker-compose/.Python, 10): Symbol not found: _futimens
  Referenced from: /Applications/Docker.app/Contents/Resources/bin/docker-compose/.Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Docker.app/Contents/Resources/bin/docker-compose/.Python

And when I run the command "docker-machine --version", it says command not found.

If you need more information, please let me know. I would appreciate if someone can help me on this as I am trying to use docker for my developments for the first time.

Thanks,

Mahfuz

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C2A4874B-6D77-45B2-80E3-F3D0FACDA238/20200123220957

### Expected behavior
docker-compose and docker-machine should be installed when Docker Desktop for Mac is installed.

### Actual behavior
docker-compose and docker-machine commands are not running

### Information

  - macOS Version: macOS Sierra version 10.12.6

### Diagnostic logs

```
Docker for Mac: version 12.2.0.0 (42247)

```

**Comment by timothyallan** [comment]
> docker-machine is not included with Docker Desktop any more: it's now a separate download. (Also, why would you want it if you have Docker Desktop? Is there some use case we haven't understood?)

I nearly had a heart attack when I upgraded and was no longer able to access any of the dozen production servers I have spun up around the world. We needed to push an emergency update to a swarm cluster manager, and none of the bash docker machine shell commands we had set up would work anymore. Immediately had to roll back.

**Comment by alexbussan** [comment]
I am also having this issue, same error shown for me after updating docker desktop and running "docker-compose --version"

**Comment by CoderBrandon** [comment]
I have also ran into this issue with `docker-compose` when I upgraded to Docker Desktop `2.2.0.0`. I am also running macOS Sierra 10.12.6. 

I suspect this might have something to do with the python version as I had `3.7.4` installed at the time of the upgrade but based on recent changes it appears to be looking for `3.7.5` or above: https://github.com/docker/compose/commit/a259c48ae9755e292dab9ca11cf0307feab8007b#diff-d9b420ea94d74e16533fa61cb4900e47R20 . The script attempts to install python3 if it doesn't exist, but I don't see anything that attempts to enforce the minor version number if it was already installed.

**Comment by CoderBrandon** [comment]
The actual issue here might be in how the Docker Desktop is checking for and validating if there is a pending update. Docker Desktop `2.2.0.0` dropped support for macOS `10.12` (Sierra) but at no point does it notify for that for *existing* installs (at least it didn't for me). When I performed a reinstall, the "check for updates" process properly showed the warning that the next version was not supported: 
![image](https://user-images.githubusercontent.com/593643/73203246-ae6bcc00-410a-11ea-84cf-66100f106722.png)

**Comment by vadimkuragkovskiy** [comment]
hey Guys, 

Perhaps it helps someone. I got the same issue. I ran upgrade docker desktop client on my mac and everything went down. I use docker + dinghy and dinghy won't start:

```bash
vadim@mbp:~/workspace/webdevops/$ dinghy start
'docker-machine' command could not be found, please install.
Brew [brew install docker; brew install docker-machine] or The Docker Toolbox [https://www.docker.com/docker-toolbox] are two great options!
```

I installed docker-machine using brew and everything starts working again:

```bash
vadim@mbp:~/workspace/webdevops/$ brew install docker-machine
```

**Comment by chris-crone** [comment]
@CoderBrandon 

>I suspect this might have something to do with the python version as I had 3.7.4 installed at the time of the upgrade but based on recent changes it appears to be looking for 3.7.5 or above: a259c48#diff-d9b420ea94d74e16533fa61cb4900e47R20 . The script attempts to install python3 if it doesn't exist, but I don't see anything that attempts to enforce the minor version number if it was already installed.

That script is used by our CI to fetch the version of Python that is used for building `docker-compose` as a standalone package that doesn't depend on the system Python. The fix that @ulyssessouza proposed (#7197) should fix the issue and make `docker-compose` work on 10.11 or later.

**Comment by rahman-mahfuz** [comment]
@chris-crone What should I do to resolve the error I am getting? I have uninstalled Docker Desktop and installed again but it shows the same error. Please give some instructions to follow so that I can resolve the issue in my computer.

**Comment by chris-crone** [comment]
@rahman-mahfuz for Docker Compose, you can download the latest release (freshly baked by @ulyssessouza!) from here: https://github.com/docker/compose/releases/tag/1.25.4-rc2

You can find Docker Machine releases here: https://github.com/docker/machine/releases

**Comment by rahman-mahfuz** [comment]
@chris-crone Thanks for the information. Just for information to anyone that comes across this issue. If you have installed Docker Desktop for Mac and facing this issue with docker-compose, you can just run the following commands to upgrade docker-compose to the latest release:

curl -L https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

**Comment by gregohardy** [comment]
curl -L https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

**Comment by gregohardy** [comment]
> @chris-crone Thanks for the information. Just for information to anyone that comes across this issue. If you have installed Docker Desktop for Mac and facing this issue with docker-compose, you can just run the following commands to upgrade docker-compose to the latest release:
> 
> curl -L [https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-`uname](https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-%60uname) -s`-`uname -m` -o /usr/local/bin/docker-compose
> chmod +x /usr/local/bin/docker-compose

curl -L https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

**Comment by Tomcaa** [comment]
> I am also having this issue, same error shown for me after updating docker desktop and running "docker-compose --version"
> I installed the previous version here: https://docs.docker.com/docker-for-mac/release-notes/ and everything is working again.

Works for me, thank you. Installed version 2.1.0.5.

**Comment by marcelovani** [comment]
> @chris-crone Thanks for the information. Just for information to anyone that comes across this issue. If you have installed Docker Desktop for Mac and facing this issue with docker-compose, you can just run the following commands to upgrade docker-compose to the latest release:
> 
> curl -L [https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-`uname](https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-%60uname) -s`-`uname -m` -o /usr/local/bin/docker-compose
> chmod +x /usr/local/bin/docker-compose

This worked, but I had to put the actual file name found in the repo i.e. `curl -L https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-Darwin-x86_64 -o /usr/local/bin/docker-compose`

**Comment by qoalu** [comment]
https://docs.docker.com/compose/install/ still mentions that docker compose comes with docker desktop and offer the only path to install it by downloading desktop.
> On desktop systems like Docker Desktop for Mac and Windows, Docker Compose is included as part of those desktop installs.

**Comment by chris-crone** [comment]
Hi @qoalu!

The preferred method of getting Compose is through Desktop and this version. I just wanted to help unblock people who had issues. The next version of Desktop stable will have the 1.25.4 release.

**Comment by luckydonald** [comment]
Running `brew unlink docker-machine && brew link docker-machine` fixed running the already installed machine executable.

**Comment by BubuPalmer** [comment]
After doing all this, I get  Killed: 9 when I run docker-compose.  I am using docker 2.2.0.0 with Mac OS Sierra 10.12.6

**Comment by celiajmd** [comment]
> > @chris-crone Thanks for the information. Just for information to anyone that comes across this issue. If you have installed Docker Desktop for Mac and facing this issue with docker-compose, you can just run the following commands to upgrade docker-compose to the latest release:
> > curl -L [https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-`uname](https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-%60uname) -s`-`uname -m` -o /usr/local/bin/docker-compose
> > chmod +x /usr/local/bin/docker-compose
> 
> This worked, but I had to put the actual file name found in the repo i.e. `curl -L https://github.com/docker/compose/releases/download/1.25.4-rc2/docker-compose-Darwin-x86_64 -o /usr/local/bin/docker-compose`

Hi， Thanks for the hint! 
I run the command line but seems not working. 
Could you please explain where is the actual file in the repo? 
Does it mean that in a repo, a file name should replace curl -L ?


![image](https://user-images.githubusercontent.com/55033756/87503051-39953b80-c631-11ea-9307-9766b694e6c4.png)
