### ISSUE TITLE
flag provided but not defined: -console

### ISSUE THREAD

**Issue by SavostinVladimir** [docker/compose#7195]
**Description**

Hi there, I run my containers with docker-compose. It worked fine for a long time, but today I am not able to start my containers. I get the message for all my containers such as below: 

> ERROR: for redis  Cannot start service redis: oci runtime error: flag provided but not defined: -console

my docker-compose.yml (I show the few services to simplify):
```yaml
postgres:
  image: unit.chat:5043/pg
  volumes:
    - ./data/pg:/var/lib/postgresql/data

rabbit:
  image: rabbitmq:3-management

redis:
  image: redis
```

there is the logs of docker daemon on my last attempt:

> Jan 28 17:09:36 test dockerd[32474]: time="2020-01-28T17:09:36.438148323+03:00" level=warning msg="failed to retrieve runc version: unknown output format: runc version spec: 1.0.1-dev\n"
Jan 28 17:09:36 test dockerd[32474]: time="2020-01-28T17:09:36.440523159+03:00" level=warning msg="failed to retrieve docker-init version: unknown output format: tini version 0.13.0\n"
Jan 28 17:09:36 test dockerd[32474]: time="2020-01-28T17:09:36.795385081+03:00" level=error msg="containerd: start container" error="oci runtime error: flag provided but not defined: -console" id=a1b5aab129f9ad3c7d755a5bb62f225da90fee927c8b1d3b9b323b9fb8b5e873
Jan 28 17:09:36 test dockerd[32474]: time="2020-01-28T17:09:36.797572068+03:00" level=error msg="Create container failed with error: oci runtime error: flag provided but not defined: -console"
Jan 28 17:09:36 test dockerd[32474]: time="2020-01-28T17:09:36.798167541+03:00" level=error msg="containerd: start container" error="oci runtime error: flag provided but not defined: -console" id=b5617ba6beda63677e78215e354042113109ef3dea404a031be87f1e95f3e11c
Jan 28 17:09:36 test dockerd[32474]: time="2020-01-28T17:09:36.798891371+03:00" level=error msg="Create container failed with error: oci runtime error: flag provided but not defined: -console"
Jan 28 17:09:36 test dockerd[32474]: time="2020-01-28T17:09:36.984948225+03:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/36fd6cc39d4d09ad52db2f092270c394cf3018f558b5d41fbc70d884a80a8fc7: exec: \"auplink\": executable file not found in $PATH"
Jan 28 17:09:37 test dockerd[32474]: time="2020-01-28T17:09:37.002713495+03:00" level=error msg="Handler for POST /v1.21/containers/a1b5aab129f9ad3c7d755a5bb62f225da90fee927c8b1d3b9b323b9fb8b5e873/start returned error: oci runtime error: flag provided but not defined: -console"
Jan 28 17:09:37 test dockerd[32474]: time="2020-01-28T17:09:37.064933610+03:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/99004783b84525e84c4819e12a9efa749e953c9fc11f546a49d6b27994e04b3e: exec: \"auplink\": executable file not found in $PATH"
Jan 28 17:09:37 test dockerd[32474]: time="2020-01-28T17:09:37.082153701+03:00" level=error msg="Handler for POST /v1.21/containers/b5617ba6beda63677e78215e354042113109ef3dea404a031be87f1e95f3e11c/start returned error: oci runtime error: flag provided but not defined: -console"

**Steps to reproduce the issue:**
1.`docker-compose up -d`

**Describe the results you received:**
as shown above

**Describe the results you expected:**
I expect the all my services will be start as before

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 29
 Running: 0
 Paused: 0
 Stopped: 29
Images: 49
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 225
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: test
ID: CA5L:GJ67:ZUS4:MBGH:BRA4:CQE2:AG7N:G7F3:IGWT:Q632:7EEV:4IA2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 unit.chat:5043
 188.120.225.196:5043
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

16.04.6 LTS (Xenial Xerus) x86_64

**Comment by silvin-lubecki** [comment]
Hello @SavostinVladimir  and thank you for filling this issue. I transferred it to the `docker/compose` as it looks like it is an issue related to the `docker-compose`tool and not the `docker CLI`.

**Comment by SavostinVladimir** [comment]
Hello, @silvin-lubecki! I've tried to run my images with docker too. But got the same results.

**Comment by ulyssessouza** [comment]
Hello @SavostinVladimir. Could you please provide a minimal `docker-compose.yml`, `Dockerfile` and `.env` (if existent) that reproduces the problem? What happens when do a simple `docker run` on the failing examples?

But at first, try to update your docker engine, from what I see in the logs `Built:        Thu Nov  2 20:40:23 2017` looks quite old. Could be an already fixed problem.
