### ISSUE TITLE
how to work with  docker-compose in windows sever i ma unable to use docker-compose up

### ISSUE THREAD

**Issue by naidukr** [docker/compose#7198]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
(paste here)
```

**Output of `docker version`**
```
(paste here)
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by ulyssessouza** [comment]
Empty issue....
