### ISSUE TITLE
Dockerized tests failing without touching the code

### ISSUE THREAD

**Issue by GabrielBB** [docker/compose#7212]
I ran `bash script/test/default tests/acceptance/cli_test.py::CLITestCase::test_up` after cloning. Lint tests pass but then the test fails with this error:

![image](https://user-images.githubusercontent.com/8752823/73692461-390f7680-4689-11ea-8fe0-c4e690d73e39.png)

This is the last commit at the time of this issue:

![image](https://user-images.githubusercontent.com/8752823/73692603-7aa02180-4689-11ea-8473-0e2ba6554c40.png)

My OS is Ubuntu

**Comment by ndeloof** [comment]
as CI is passing successfully I assume this is a local environment issue. Please double check https://github.com/docker/compose/blob/master/CONTRIBUTING.md#development-environment

**Comment by GabrielBB** [comment]
@ndeloof Does the development environment outside the container affects the container tests?
