### ISSUE TITLE
Volumes for other service fail service to start

### ISSUE THREAD

**Issue by ilons** [docker/compose#7215]
## Description of the issue
When starting a service in a compose file with multiple services, volumes for services not affected by the current invocation are resolved and fails the command if not resolved correctly.
This was discovered when running docker-compose logs on a service, and it failed when it could not resolve the volume for another service in the file.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896
docker-py version: 3.7.3
CPython version: 2.7.16
OpenSSL version: OpenSSL 1.1.1d FIPS  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:58:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:57:04 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
$ docker-compose -f compose-logs.yml config
ERROR: Named volume "test:/test:rw" is used in service "unused-service" but no declaration was found in the volumes section.
```
The actual configuration file:
```
version: "3.7"
services:
  test-service:
    image: busybox
  unused-service:
    image: busybox
    volumes:
      - ${MY_PATH_VAR:-}test:/test
```

## Steps to reproduce the issue

1. Create a compose-file with two services: 
```
services:
  test-service:
    image: busybox
  unused-service:
    image: busybox
    volumes:
      - ${MY_PATH_VAR:-}test:/test
```
2. Try to run any docker-compose command involving only `test-service`, such as `docker-compose up test-service`

### Observed result
Docker-Compose tries to resolve volumes for the `unused-service` service, which fails. Even if this service is not affected by the command being run.
```
ERROR: Named volume "test:/test:rw" is used in service "unused-service" but no declaration was found in the volumes section.
```

### Expected result
The `test-service` should start

### Stacktrace / full error message
```
ERROR: Named volume "test:/test:rw" is used in service "unused-service" but no declaration was found in the volumes section.
```

## Additional information
The use-case for using this config are that we run docker-compose with the help of `make`, which then calculates and feeds in the `MY_PATH_VAR` value to be used.
This works as expected, the problem occurs when we try to run `docker-compose` directly, such as checking logs for a dependency service, or when doing `docker-compose down`.

I understand that this is probably due to the whole configuration file being parsed when running docker-compose, regardless of what command is being used.
That being said, I think this should not fail, as for example, if you instead specify a mount-point which does not exist (setting the `MY_PATH_VAR` to any value), it works just fine, as the volume is never actually mounted.

OS version / distribution, `docker-compose` install method, etc.
Probably not relevant;
OS: Fedora 30
Kernel: 5.2.18-200.fc30.x86_64
Installation method: yum

**Comment by ndeloof** [comment]
We could indeed consider implementing sort of "lazy-validation" of service configuration so that unused services just get ignored.

**Comment by bartier** [comment]
@ilons Is this issue still relevant? I'm new here and I could not reproduce following the steps:

Docker-compose: 1.26.0dev
Docker version 19.03.9, build 9d988398e7


```
$ docker-compose -f compose-logs.yml config # this should be an error instead of the current output
services:
  test-service:
    image: busybox
  unused-service:
    image: busybox
    volumes:
    - /test:/test:rw
version: '3.7'

$ cat compose-logs.yml 
version: "3.7"
services:
  test-service:
    image: busybox
  unused-service:
    image: busybox
    volumes:
      - ${MY_PATH_VAR:-}test:/test
```

If I were able to reproduce this, I'd try to fix this if possible

**Comment by ilons** [comment]
Sorry about the late reply.

This is indeed still relevant  (version details at bottom).
Smaller `docker-compose.yml` to reproduce, `cat docker-compose.yml`:
```
version: "3"
services:
  test-service:
    image: busybox
  unused-service:
    image: busybox
    volumes:
      - test:/test
```
`docker-compose -f docker-compose.yml config`, (or specifically: `docker-compose -f docker-compose.yml up test-service`):
```
ERROR: Named volume "test:/test:rw" is used in service "unused-service" but no declaration was found in the volumes section.
```

## Version info
`docker-compose version`
```
docker-compose version 1.25.4, build unknown
docker-py version: 4.2.0
CPython version: 3.8.3
OpenSSL version: OpenSSL 1.1.1g FIPS  21 Apr 2020
```
`docker version`
```
Client:
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.14.3
 Git commit:        42e35e6
 Built:             Sun Jun  7 21:16:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.3
  Git commit:       42e35e6
  Built:            Sun Jun  7 00:00:00 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3
  GitCommit:        
 runc:
  Version:          1.0.0-rc10+dev
  GitCommit:        fbdbaf85ecbc0e077f336c03062710435607dbf1
 docker-init:
  Version:          0.18.0
  GitCommit:    
```

**Comment by ilons** [comment]
> @ilons Is this issue still relevant? I'm new here and I could not reproduce following the steps:
> 
> Docker-compose: 1.26.0dev
> Docker version 19.03.9, build 9d988398e7
> 
> ```
> $ docker-compose -f compose-logs.yml config # this should be an error instead of the current output
> services:
>   test-service:
>     image: busybox
>   unused-service:
>     image: busybox
>     volumes:
>     - /test:/test:rw
> version: '3.7'
> 
> $ cat compose-logs.yml 
> version: "3.7"
> services:
>   test-service:
>     image: busybox
>   unused-service:
>     image: busybox
>     volumes:
>       - ${MY_PATH_VAR:-}test:/test
> ```
> 
> If I were able to reproduce this, I'd try to fix this if possible

@ndeloof response above.

**Comment by ilons** [comment]
Still relevant it seems:
> cat docker-compose.yml 
```yaml
version: "3.7"
services:
  test-service:
    image: busybox
  unused-service:
    image: busybox
    volumes:
      - ${MY_PATH_VAR:-}test:/test
```
> docker-compose up test-service
```
ERROR: Named volume "test:/test:rw" is used in service "unused-service" but no declaration was found in the volumes section.
```
Seems that the check (and error) have changed slightly over the versions tho.
---
> docker-compose version
```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.0
CPython version: 3.9.5
OpenSSL version: OpenSSL 1.1.1j  16 Feb 2021
```
> docker version
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:58:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
> cat /etc/issue
```
Pop!_OS 21.04 \n \l
```
> uname -a 
```
Linux Flexie 5.11.0-7620-generic #21~1624379747~21.04~3abeff8-Ubuntu SMP Wed Jun 23 02:34:03 UTC  x86_64 x86_64 x86_64 GNU/Linux
```
