### ISSUE TITLE
`up` does not build dependent image provided by other service

### ISSUE THREAD

**Issue by dms-cat** [docker/compose#7222]
## Description of the issue

I can't start a service which depends on the image of another service without manually building the other service first.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.0, build 0aa5906
docker-py version: 3.7.3
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
services:
  child:
    image: test_parent:latest
  parent:
    build:
      context: /home/username/test
version: '3.5'
```

## Steps to reproduce the issue

1. `docker-compose up child`

### Observed result

```text
Creating network "test_default" with the default driver
Pulling child (test_parent:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]
ERROR: pull access denied for test_parent, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

### Expected result

It should build test_parent:latest and then start successfully.

## Additional information

Ubuntu 18.04.

**Comment by VigneshSP94** [comment]
Not an expert, but why not build your image first?

```
version: '3.5'
services:
  child:
      build: /path/to/dir/Dockerfile
      image: test_parent:latest
```
This way, `docker-compose up` will create an image for your service and tag it with the image parameter, then this image will be used for child service.

**Comment by dms-cat** [comment]
@VigneshSP94 That means we would have to duplicate (and keep in sync) the parent and child build directives or use the frankly ugly YAML anchor syntax.

**Comment by VigneshSP94** [comment]
Would this help?

https://docs.docker.com/compose/startup-order/

You can add `depends_on: parent` parameter in child, this will make compose to focus on building the parent first as child depends on it.

Also, did you miss to tag the image in build section of parent?

**Comment by ndeloof** [comment]
Works as documented: image for a service without build directive get pulled from registry.

If you don't want to repeat yourself, yaml anchors can indeed be used. Don't blame compose for the yaml syntax :P

**Comment by dms-cat** [comment]
@VigneshSP94 Adding `depends_on: parent` would result in a circular dependency in my case.

I don't know what you mean by tagging the image in the build section - the [reference](https://docs.docker.com/compose/compose-file/#build) doesn't seem to have a way to specify the tag at build time.

**Comment by dms-cat** [comment]
@ndeloof "[I]mage for a service without build directive get pulled from registry" except if I build the dependent image manually, in which case it uses the local image. That's confusing.
