### ISSUE TITLE
Abort on non-zero exit code

### ISSUE THREAD

**Issue by mangas** [docker/compose#7230]
**Is your feature request related to a problem? Please describe.**
When using docker-compose to run finite tasks, like tests, is hard to detect a failure from the exit code as there is no way of cascading just non-zero errors

**Describe the solution you'd like**
An option very similar to --abort-on-container-exit that will only abort of failure i.e non-zero exit code 

**Describe alternatives you've considered**
Using bash scripts and docker inspect to figure out the exit code for each container 

Happy to submit a PR if this is something you'd be happy to accept as an additional docker-compose up option

**Comment by ricmzn** [comment]
Have you tried using `docker-compose run` instead of `docker-compose up` for running tests and scripts? That will give you the exit code when the container finishes, but you will need to run each script/test separately.

**Comment by ndeloof** [comment]
Running "finite tasks" with compose is indeed better implemented using `docker-compose run`, which will return exit code.
