### ISSUE TITLE
Being able to override `build` with `image`

### ISSUE THREAD

**Issue by augnustin** [docker/compose#7231]
**Is your feature request related to a problem? Please describe.**

Say I have this `docker-compose.yml`:

```
services:
  app:
    build: .
```

And I want to override the `build` value with an image. 

With `docker-compose.override.yml` having:

```
services:
  app:
    image: my_repo/my_app:my_tag
```

The merge results:

```
services:
  app:
    build: .
    image: my_repo/my_app:my_tag
```

And it is the `image` entry which is ignored. 

**Describe the solution you'd like**

If a value like `build: NONE` was allowed in the override it would work, without having to change priorities. Just like for the `healthcheck CMD` entry.

**Describe alternatives you've considered**

One can work around by having separated `docker-compose.environment.yml` but then behavior is not default and doesn't work out-of-box.

**Additional context**

In general, it could make sense that `docker-compose` ignores all `NONE` values in its config to make sure any value can be removed by overriding.

Besides, this is pretty much backward compatible so it should not be a big issue for current users.

Thanks

**Comment by ndeloof** [comment]
compose file merge support is indeed implemented as "append-only". I'm not sure this is intentional, would need to look into issues/code history.

When `image` is set, compose will always try to pull first, then run a build if image can't be found. You also can use `--no-build` option to disable build support.

**Comment by augnustin** [comment]
Thanks for getting back @ndeloof 

Doesn't my query make sense? Why having such limitations? The good thing is that this simply has to do with file config handling, so nothing at the execution level. Shouldn't be too hard, should, it?

**Comment by Perdjesk** [comment]
This will be resolved if https://github.com/docker/compose/issues/3729 is resolved. 
@augnustin I would suggest to close this issue as a duplicate of https://github.com/docker/compose/issues/3729

**Comment by augnustin** [comment]
Cool, though it doesn't seem like the #3729 is going to be resolved soon. :disappointed:

**Comment by piksel** [comment]
Just a note for anyone else finding this... if you add a `image: alpine:latest` override and then do `docker-compose up --build`, it will tag the image built from your build dockerfile as `alpine:latest`. Fun debugging ensues!😅

**Comment by jeetparte** [comment]
> ```
> services:
>   backend:
>     image: my/dev/image:0.9
>     build: !reset null
> ```

The official docs for the reset feature: https://docs.docker.com/reference/compose-file/merge/#reset-value.

It works in the reverse direction as well (override `image` with `build`)!
