### ISSUE TITLE
Plesae provide SHA-256 sum for compose releases. 1.25.3 and 1.25.4 have no SHA-256 sum on the release notes pages anymore.

### ISSUE THREAD

**Issue by svenlange** [docker/compose#7234]
Plesae provide SHA-256 sum for compose releases. 1.25.3 and 1.25.4 have no SHA-256 sum on the release notes pages anymore.

**Comment by ndeloof** [comment]
Release page do offer .sha256 checksum files for all published artifacts, can't you rely on them ?

**Comment by svenlange** [comment]
Could you please provide a link to the release page you mentions for release 1.25.4 showing the sha256?

**Comment by ndeloof** [comment]
see https://github.com/docker/compose/releases/tag/1.25.4
"Assets" section
every downloadable binary comes with it's sha256 checksum file

**Comment by svenlange** [comment]
Thanks!
