### ISSUE TITLE
Virus Detected - v1.25.4

### ISSUE THREAD

**Issue by laurin1** [docker/compose#7241]
https://www.virustotal.com/gui/file/941705af6c3676ef17f1fa6726019c09efa0ad785174afda439eed8b794c36db/detection

![image](https://user-images.githubusercontent.com/75857/74856664-19728200-5308-11ea-9b39-33be564ff295.png)

**Comment by chris-crone** [comment]
Hi @laurin1, Thanks for the report.

I believe that this is a false positive from some of the scanners:
```console
root@2e4d9bd8cf52:/compose# shasum -a 256 docker-compose-Windows-x86_64.exe 
941705af6c3676ef17f1fa6726019c09efa0ad785174afda439eed8b794c36db  docker-compose-Windows-x86_64.exe
root@2e4d9bd8cf52:/compose# clamscan docker-compose-Windows-x86_64.exe 
docker-compose-Windows-x86_64.exe: OK

----------- SCAN SUMMARY -----------
Known viruses: 6744978
Engine version: 0.102.2
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 9.75 MB
Data read: 9.34 MB (ratio 1.04:1)
Time: 19.557 sec (0 m 19 s)
```

I would recommend contacting the antivirus vendors and informing them.

**Comment by laurin1** [comment]
False or not, I know I'm not the only one that this is affecting and something is causing several antivirus products to flag this version, but that was not the case for previous versions.
