### ISSUE TITLE
Environment variable expansion: environment variable in default fails

### ISSUE THREAD

**Issue by vitaly-krugl** [docker/compose#7256]
## Description of the issue
When I use an environment variable in the default value of an environment variable as follows:
```
version: '3'
services:
  dev:
    image: image_name
    build: .
    volumes:
      "${SETTINGS_LOCAL-${PWD}/config/dummy_settings.json}:/a/etc/app/settings.json:ro"
```

`docker-compose config` and other sub-commands fail with "ERROR: Named volume "${PWD/config/dummy_settings.json}:/a/etc/app/settings.json:ro" is used in service "dev" but no declaration was found in the volumes section."

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
ERROR: Named volume "${PWD/config/dummy_settings.json}:/a/etc/app/settings.json:ro" is used in service "dev" but no declaration was found in the volumes section.
```

## Steps to reproduce the issue

1. In the volumes section of a service, use an environment variable inside the default value of an environment variable.
2. Run `docker-compose config` or `docker-compose build`
3.

### Observed result
```
ERROR: Named volume "${PWD/config/dummy_settings.json}:/a/etc/app/settings.json:ro" is used in service "dev" but no declaration was found in the volumes section.
```

### Expected result
Expected `${PWD}` to be substituted correctly within the default value of `SETTINGS_LOCAL` environment variable.

## Additional information

```
macOS Catalina. v 10.15.3
```

**Comment by caringco** [comment]
Hi All,
Unsure if this is related to this bug - but below is my issue:

**docker-compose.yml**
```
version: '3'

services:
  test:
    build: 
      context: .    
    environment:
      - NODE_ENV=production
      - DATABASE_MASTER=master
    command: echo $DATABASE_MASTER + $NODE_ENV
```
**Dockerfile**
```
FROM alpine
```
**docker version**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
**docker-compose version**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**docker-compose config**
```
WARNING: The DATABASE_MASTER variable is not set. Defaulting to a blank string.
WARNING: The NODE_ENV variable is not set. Defaulting to a blank string.
services:
  test:
    build:
      context: /Users/***/workspace/test
    command: 'echo  + '
    environment:
      DATABASE_MASTER: master
      NODE_ENV: production
version: '3.0'
```
Mac OS Catalina 10.15.3

Expected result should be that the environment variables should be getting picked up.
Please can anyone help me solve this? I do not want to use .env files etc.

**Comment by Mahima-ai** [comment]
@caringco  You can visit [my comment on the same issue](https://github.com/docker/compose/issues/7423#issuecomment-667059548) 

I solved the issue by taking the below two steps.

1. I uninstalled the older docker-compose and installed the latest by following [](https://docs.docker.com/compose/install/)
2. I renamed the service for which the environment variables were defined in the docker-compose.yml.

Later on, I rechecked with the old service name and found that the issue reappeared. Then I removed the older container and again did docker-compose up. This solved the issue. So I think, it might be the old container which does not let us see the new changes.

Hope this helps.

**Comment by vitaly-krugl** [comment]
Could the maintainer please state whether this issue has been fixed?
