### ISSUE TITLE
`docker-compose pull` NOT failing if a service image is not found (and includes both image and build)

### ISSUE THREAD

**Issue by erks** [docker/compose#7258]
## Description of the issue

https://github.com/docker/compose/issues/6464 described the behavior where `docker-compose pull` failing if a service includes both image and build as a bug. This was "fixed" in [1.25.1](https://github.com/docker/compose/pull/6494). We actually rely on this behavior to decide whether we need to build and push the image and don't think the pre-1.25.1 behavior was a bug.

The `pull` command should do as it says, which is to try to pull all the images specified in `docker-compose.yml`, and reports error appropriately regardless of whether `build` is specified.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.2, build 698e2846
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  build:
    build:
      context: /private/tmp/test
    command: echo "from build"
    image: example
  test:
    command: echo "from test"
    image: example
version: '3.0'
```

## Steps to reproduce the issue

1. Same as https://github.com/docker/compose/issues/6464

### Observed result

The service with both image and build didn't throw an error and was reported "done" 

```
$ docker-compose pull
Pulling build ... done
Pulling test  ... error

ERROR: for test  pull access denied for example, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for example, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

### Expected result

The service with both image and build does the "pull" as instructed and reports appropriate errors if it fails to do so.

### Stacktrace / full error message

```
$ docker-compose pull
Pulling build ... done
Pulling test  ... error

ERROR: for test  pull access denied for example, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for example, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

## Additional information

Darwin, downloaded docker from docker.com/get-started

**Comment by fabienrenaud** [comment]
@collin5 Can we get the original behavior re-introduced? `pull` should just pull. Building on pull failure (issue #6464) should be an option (e.g: `docker-compose pull --build`), otherwise the change is not backward-compatible (docker-compose v1.x) and pull starts having new/undesirable side effects.

**Comment by seanmorris** [comment]
> @collin5 Can we get the original behavior re-introduced? `pull` should just pull. Building on pull failure (issue #6464) should be an option (e.g: `docker-compose pull --build`), otherwise the change is not backward-compatible (docker-compose v1.x) and pull starts having new/undesirable side effects.

I second this. I already have separate compose files for dev, test and two for production (frontend/backend). I've also got a base file. I don't want development instrumentation in my test/prod container (ie xdebug) and I don't want testing instrumentation in my prod images (ie phpunit).

I've already got a makefile to manage this complexity and I don't want to add another layer of complication here. A flag would be very elegant.

**Comment by fabienrenaud** [comment]
Still needed.

**Comment by fabienrenaud** [comment]
@collin5 Can we get the original behavior re-introduced?

**Comment by seanmorris** [comment]
@collin5 Can we get the original behavior re-introduced?
