### ISSUE TITLE
docker build --pull

### ISSUE THREAD

**Issue by tianon** [docker/compose#726]
Now that https://github.com/docker/docker/pull/9281 is in Docker 1.4.0, it'd be great to have either `pull: true` in `fig.yml` next to `build:` or have a `fig build --pull`!

**Comment by pospispa** [comment]
+1 for docker-compose build --pull
I don't need it inside .yml file.

**Comment by schmunk42** [comment]
:+1:

**Comment by t128** [comment]
+1 :+1:

**Comment by t128** [comment]
+2

**Comment by Starefossen** [comment]
Need this! :+1:

**Comment by dnephin** [comment]
Done in #2041
