### ISSUE TITLE
I cannot connect to a PostgreSQL database in a docker container

### ISSUE THREAD

**Issue by masterarrow** [docker/compose#7272]
My docker-compose.yml:

version: '3.4'

services:
  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data
    restart: on-failurein
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: gunicorn app.wsgi -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure

volumes:
  data:
    name: data
    driver_opts:
      type: none
      device: $PWD/data
      o: bind

After running `docker-compose up` in my terminal I got no errors and everything seems to work, but when I'm trying to connect to the database using a port 5432 I can't.
Running `docker ps` I figured out that Postgres container keeps continuous restart.

The result of the command `docker volume inspect data`:

[
    {
        "CreatedAt": "2020-03-07T14:11:23+02:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "blog",
            "com.docker.compose.version": "1.23.1",
            "com.docker.compose.volume": "data"
        },
        "Mountpoint": "/var/lib/docker/volumes/web/_data",
        "Name": "data",
        "Options": {
            "device": "/home/user/web/data",
            "o": "bind",
            "type": "none"
        },
        "Scope": "local"
    }
]

Is it some error in my compose file or what? Thanks for the answer in advance :)

**Comment by BrainABar** [comment]
I was able to solve a similar problem to yours. When you run docker-compose, it will put everything within its own docker network by default. This will then map the names given such as postgres and web. So your web container would be able to use postgres:5432 to connect to it.

[Found in the docker docs under networking/specify custom networks](https://docs.docker.com/compose/networking/#specify-custom-networks)

For example, suppose your app is in a directory called myapp, and your docker-compose.yml looks like this:

```version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres
    ports:
      - "8001:5432"
```
When you run ```docker-compose up```, the following happens:

    1. A network called myapp_default is created.
    2. A container is created using web’s configuration. It joins the network myapp_default under the name web.
    3. A container is created using db’s configuration. It joins the network myapp_default under the name db
