### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by cosminonnet** [docker/compose#729]
Hi,
I would like to use the newly added "restart_policy" parameter (see https://github.com/docker/fig/pull/712#issuecomment-66755754). When is the next release of Fig scheduled? (I suppose version 1.0.2 is next).
Thanks

**Comment by Starefossen** [comment]
I really think there should have been a minor version bump by now. 2 months and 60 commits since v1.0.1 – a few bugs has been fixed too.
