### ISSUE TITLE
Passing secret into environment variable

### ISSUE THREAD

**Issue by sesameguy** [docker/compose#7318]
hi, i am using "docker stack deploy" to run the application.
I try to assign the environment variable "password" by secret.
however, it doesn't work.

Is there any solution to pass the sensitive information into the environment variable?
Thx.

**Comment by decentral1se** [comment]
> https://blog.sunekeller.dk/2018/04/docker-18-03-config-and-secret-templating/

**Comment by sesameguy** [comment]
thx much
