### ISSUE TITLE
Support `extra_hosts` in `_CLIBuilder`

### ISSUE THREAD

**Issue by tomaszzielinski** [docker/compose#7323]
**Is your feature request related to a problem? Please describe.**

I'm using v2.4 yml as I need to pass `extra_hosts` to the builder and v3 doesn't seem to support that (yet). I'm evaluating using `docker-compose` with BuildKit but it seems that `extra_hosts` are not propagated all the way to the Docker CLI [1].

[1] https://github.com/docker/compose/blob/1.26.0-rc3/compose/service.py#L1790-L1802 

**Describe the solution you'd like**

It would be great if `_CLIBuilder` made use of `extra_hosts`, as they seem to be properly passed down to it [2].

[2] https://github.com/docker/compose/blob/1.26.0-rc3/compose/service.py#L1085-L1100

**Describe alternatives you've considered**

I tried mounting my own hosts file on top of `/etc/hosts` but it doesn't seem to be possible inside a "normal" (i.e. unpriviledged, etc.) container.

I also thought about patching `docker-compose` locally & maintaining a fork, but it doesn't really make sense given that the default (non-CLI) builder works correctly and that I don't stricly need BuildKit (it was meant to be a nice bonus).

**Comment by skokhanovskiy** [comment]
Faced with same bug. I think that person who added `extra_hosts` support just forgot about existence of cli builder.

So, now I can't use buildkit because in my dockerfile there are images from intranet registry. The hostname of this registry are not resolving by google public dns.

**Comment by skokhanovskiy** [comment]
So, i fixed issue with unavailable intranet DNS servers by using dnsmasq on the docker0 interface as dedicated DNS server for docker daemon.

Any way, I found that there are another unrealized command-line parameters:
* `labels` (fixed in #7269)
* `quiet`
* `rm`
*  `gzip` (`compress`) 
* `shmsize` (`shm-size`)
* `network_mode` (`network`)
* `extra_hosts` (`add-host`) 
* `isolation`

This options above are not working if they are specified in a docker-conpose file and `docker-compose build` start with the `COMPOSE_DOCKER_CLI_BUILD=1` environment variable.

**Comment by thaJeztah** [comment]
Yes, not all options were added in the first implementation of the "cli" based build (also see https://github.com/docker/compose/pull/6584#issuecomment-513210065). I think it makes sense to add this though, so contributions welcome.

That said, I think this option can be added to the `v3` schema as well, to bring parity with `v2`. This option is already supported by both the "classic" and BuildKit builders, so I don't see a reason for not adding it.

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/2517 - if that's accepted, this can be implemented in compose when support for the 3.9 schema is added

**Comment by syabro** [comment]
@thaJeztah it's merged. What's next here? :)

**Comment by syabro** [comment]
@thaJeztah any news?

**Comment by thaJeztah** [comment]
Not sure; there's changes merged in this repository to support the "unified" schema (https://github.com/compose-spec/compose-spec), so perhaps it's supported own the latest version

@aiordache do you know?

**Comment by dzieciou** [comment]
It's been a year and half since last update. Any news on that?

**Comment by ndeloof** [comment]
`extra_host` is supported by the Compose Specification: https://github.com/compose-spec/compose-spec/blob/master/build.md#extra_hosts
implemented in compose-go: https://github.com/compose-spec/compose-go/blob/master/types/types.go#L299
and supported by Compose V2: https://github.com/docker/compose/blob/v2/pkg/compose/build.go#L259
