### ISSUE TITLE
docker-compose up hangs if a service has logging configuration

### ISSUE THREAD

**Issue by vlad-nica** [docker/compose#7324]
## Description of the issue
If in `docker-compose.yml`, a service has configurations related to logging, running `docker-compose up` will hang. Removing logging configuration from the service lets the container spin off properly.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)

## Steps to reproduce the issue

1. `docker-compose.yml`
```
services:
  subscriptions:
    build:
      context: E:\Work\services\subscriptions
    environment:
      DEBUG: 1
      PORT: 8091
      SERVICE_NAME: subscriptions
    logging: # removing it will solve the problem
      driver: json-file
      options:
        max-file: 10
        max-size: 10m
    ports:
    - 8091:8091/tcp
    - 9209:9209/tcp
    restart: unless-stopped
version: '3.0'
```
2. Run `docker-compose --verbose up`

### Observed result
Looking at the output of `docker-compose --verbose up`, for when logging is configured, the console is continuously printing `compose.parallel.feed_queue: Pending: set()`

**Comment by aapris** [comment]
I've this same issue on M1 Macbook (Big Sur). I'll create a new issue, if I don't find way to re-open this one.
