### ISSUE TITLE
Cannot start docker image

### ISSUE THREAD

**Issue by patrickave** [docker/compose#7325]
Starting codimd_database_1 ... error

ERROR: for codimd_database_1  Cannot start service database: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/overlay2/42554dd132a2de5c3494ffa82b73e7eb3db28d153b9052b2c2330209df169aef/merged\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown

ERROR: for database  Cannot start service database: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/overlay2/42554dd132a2de5c3494ffa82b73e7eb3db28d153b9052b2c2330209df169aef/merged\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by GamerBene19** [comment]
Just wondering, did you end up resolving the issue @patrickave? I am running into the same one (see [here](https://github.com/lancachenet/docker-compose/issues/21)).

**Comment by GamerBene19** [comment]
My issue was because of something different. See my issues for my solution.
