### ISSUE TITLE
command in compose file doesn't override CMD in built image

### ISSUE THREAD

**Issue by zlk89** [docker/compose#7331]
## Description of the issue
command in compose file doesn't override CMD in built image

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    build:
      context: /Users/xx
    command: yarn start:local
    environment:
      NODE_ENV: development
    image: local-dev-image:latest
version: '3.0'
```

## Steps to reproduce the issue

1. First build the image: `docker-compose -f docker-compose.local.yml build app`
2. Then just run the image: `docker run local-dev-image`

### Observed result
It is using the CMD in Dockerfile

### Expected result
It should be using the overrided command specified in compose file

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by thaJeztah** [comment]
This is expected; the `command:` is used at runtime, when running the compose project (`docker-compose up`) or when using `docker-compose run <service>`, but does not set the default command of the image that's built. If you want to set a different command in the image, you need to update the Dockerfile.

**Comment by zlk89** [comment]
@thaJeztah What's recommended way to have different CMD depends on stage (local/production)?
I tried to use --build-arg during docker build, but apparently it doesn't work for CMD.

**Comment by zlk89** [comment]
After doing some researches, I found multi-stage Dockerfile might be the best solution for this use case.
```
FROM node:12.14-alpine AS builder
xxx

## Local stage
FROM builder AS local
CMD yarn start:local

## Prod stage
FROM builder AS prod
CMD yarn start:prod
```

**Comment by thaJeztah** [comment]
Yes, multi stage builds are a good solution (there's not a "single" solution, as "what works best" depends on your situation/use case).

A combination of multi-stage builds and build-args is also something that can be used; with that, it's possible to have "if-else"-like constructs.

```Dockerfile
ARG ENVIRONMENT=prod

FROM builder AS builder-dev
CMD yarn start:local

FROM builder AS builder-prod
CMD yarn start:prod

# the final stage will either build the "prod" or "dev" variant, depending
# on the value of the ENVIRONMENT build-arg
FROM builder-${ENVIRONMENT} AS final
```

Now, you can build different versions, based on a build-arg that's set, for example:

```bash
# default: builds production image
docker build -t foo .

# same, but explicitly set the ENVIRONMENT build-arg:
docker build -t foo --build-arg ENVIRONMENT=prod .

# build the "dev" variant:
docker build -t foo --build-arg ENVIRONMENT=dev .
```

Build args can take their value from an environment variable with the same name set in your shell, for example:

```bash
# this could be in your `.profile`, or `.env` for docker-compose
export ENVIRONMENT=dev

# don't pass a value for ENVIRONMENT: it will now take it's value from
# the environment variable (if set), or otherwise use the default:
docker build -t foo --build-arg ENVIRONMENT .
```
