### ISSUE TITLE
a

### ISSUE THREAD

**Issue by 19125064** [docker/compose#7332]
how to solve this question
when install 1.25.0 version
root@ybb:~# docker-compose --version
[24279] Cannot open self /usr/local/bin/docker-compose or archive /usr/local/bin/docker-compose.pkg

thank you!

**Comment by regzon** [comment]
Check out this issue #1135

**Comment by 19125064** [comment]
> Check out this issue #1135

thank you very much!
i had reinstalled it again! the question is solved.
