### ISSUE TITLE
Should not log a warning when environment variable value is specified in override file

### ISSUE THREAD

**Issue by bburtin** [docker/compose#7339]
## Description of the issue
When a **docker-compose.yml** property is set to an environment variable and **docker-compose.override.yml** specifies a fixed value, **docker-compose** incorrectly logs a warning.  This is misleading, and affects developer productivity.

This was reported in issue #4335.  I'm confused about why that issue was closed.  It sure looks like a bug to me.  Just because there's a workaround doesn't mean that the bug shouldn't be fixed.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
$ docker-compose --version
docker-compose version 1.25.4, build 8d51620a
```

**Output of `docker version`**
```
$ docker --version                             
Docker version 19.03.8, build afacb8b7f0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
$ docker-compose config   
WARNING: The MYVAR_DEFAULT variable is not set. Defaulting to a blank string.
services:
  test:
    environment:
      MYVAR: my_value
    image: hello-world
version: '3.3'
```

## Steps to reproduce the issue

```
$ cat docker-compose.yml         
version: '3.3'
services:
  test:
    image: hello-world
    environment:
      MYVAR: ${MYVAR_DEFAULT}

$ cat docker-compose.override.yml 
version: '3.3'
services:
  test:
    environment:
      MYVAR: my_value
```

### Observed result
See **docker-compose config** output above.

### Expected result
Same result, but without the warning.

### Stacktrace / full error message

```
WARNING: The MYVAR_DEFAULT variable is not set. Defaulting to a blank string.
```

## Additional information

Ubuntu 18.04

**Comment by valtbarbos** [comment]
Use --log-level ERROR (Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL))

**Comment by zoombinis** [comment]
I also get this error with the following directory setup:
```
docker/base/.my.env
docker/base/.docker-compose.yml     <- This contains my services that use the .env vars
docker/child/docker-compose.yml     <- This contains services that extend from base' services
```

When I run from `docker/child` directory: `docker-compose --env-file ../install/.my.env up`

It works great, no errors or warnings. But when I run `docker-compose down` I get the `WARNING` described in this issue.

Something to do with loading an env file in a directory separate from my context?


My use of `extends` in `docker/child/docker-compose.yml` is pretty basic:

```yml
  base:
    extends:
      file: "../base/docker-compose.yml"
      service: "extend-from-base"
```
