### ISSUE TITLE
How start a service‘s instances into different machines?

### ISSUE THREAD

**Issue by ctlove0523** [docker/compose#7367]
In kubernetes we can use affinity and anti-affinity feature to deploy a service’s instances into different nodes，how to do in docker compose？

**Comment by oshmyrko** [comment]
@ctlove0523, you should probably look in Docker Swarm direction.

**Comment by ctlove0523** [comment]
@oshmyrko yes,Docker Swarm can solve this problem,but how to deploy Docker Swarm has three manager node?

**Comment by oshmyrko** [comment]
@ctlove0523,
Simply install docker to three hosts, and on the first one run:
```
# Initialize Docker Swarm cluster
docker swarm init

# Get token for joining other managers
docker swarm join-token manager
```
It will output something like this:
```
To add a manager to this swarm, run the following command:
    docker swarm join --token SWMTKN-1-3reu3oawdptx714m5v3jrxbeb92frhu2lgl32h75hx8ohp8gsd-bicj716fgd0s879ps5g9n4vh9 192.168.1.5:2377
```
Run obtained command on two other hosts to join the cluster.
To check cluster status run:
```
docker info
docker node ls

**Comment by ctlove0523** [comment]
@oshmyrko Thanks
