### ISSUE TITLE
Docker compose is not compatible with Python 3.8 under Ubuntu

### ISSUE THREAD

**Issue by jlowin** [docker/compose#7369]
## Description of the issue

Attempting to use the docker-compose CLI fails under Ubuntu with Python 3.8 due to accessing a deprecated attribute.

[This line](https://github.com/docker/compose/blob/4be2fa010aa8f1ea3853698ac5407eb4421e7847/compose/cli/utils.py#L76) in the `is_ubuntu()` function attempts to access `platform.linux_distribution` but that attribute was deprecated in Python 3.5 and removed in 3.8 (see issue [here](https://bugs.python.org/issue28167)).

**Comment by thaJeztah** [comment]
ping @ulyssessouza @ndeloof PTAL
