### ISSUE TITLE
Pre-built binary for aarch64?

### ISSUE THREAD

**Issue by uberhacker** [docker/compose#7370]
I was able to install from source on Debian 10 with Docker installed.
```bash
$ wget https://github.com/docker/compose/archive/1.25.5.tar.gz
$ tar xvf 1.25.5.tar.gz
$ cd compose-1.25.5
$ sudo apt install python3-pip libffi-dev
$ sudo python3 setup.py install
```

**Comment by samip5** [comment]
This really needs to be done. :)

**Comment by ecv** [comment]
All of my upvotes.

**Comment by Doom4535** [comment]
@samip5 or at least update the [install instructions](https://docs.docker.com/compose/install/) to document the build steps (or even just update the [README.md](https://github.com/docker/compose/blob/master/README.md) or add an INSTALL.txt file) to reference this if they don't want to post it yet on the site.
