### ISSUE TITLE
docker-compose just hangs, no response

### ISSUE THREAD

**Issue by opaessens** [docker/compose#7373]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0AB4FD43-EB28-4D5A-B37A-43423D0057B6/20200416125337

### Expected behavior

Start docker-compose

### Actual behavior

Command just hangs - no response, high CPU load. Even when running docker-compose --help .

### Information
  - macOS Version: 10.15.4 (19E287)

Issue started today after rebooting. Installed docker yesterday and it worked until then.
Did some reinstalls already.
Tried all of the troubleshooting tips or other docker-compose issues on Github. Issue's still there.
Other commands like docker ps or docker info are running fine.

When hitting control+c some Python related errors are printed:
e.g. (Errors are varying, but all seem to be related to PyInstaller)
`ImportError: Loader FrozenImporter cannot handle module contextlibImportError: Loader FrozenImporter cannot handle module contextlib`

**Comment by quinnicious** [comment]
I'm also experiencing this issue on Ubuntu 18.04.4. Installed Docker and Compose around a week ago, but Compose has started to hang since yesterday.

**Comment by SteffenAnders** [comment]
same issue for mer too. any updates here?

**Comment by massardc** [comment]
Hello, same here. 
It always takes about 7 minutes before I get any output and the command actually runs when doing anything using docker-compose.

**Comment by massardc** [comment]
I am not sure if that can be helpful for you guys but I figured it was because of Kaspersky on my laptop. Disabling it before running docker-compose would make the command run as fast as expected.

**Comment by SteffenAnders** [comment]
We have solved the problem by installing docker-compose as a container. 
See https://docs.docker.com/compose/install/ → "Alternative Install Options".

```
sudo curl -L --fail https://github.com/docker/compose/releases/download/1.26.0/run.sh -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

docker-compose --version
```

**Comment by giaosudau** [comment]
> We have solved the problem by installing docker-compose as a container.
> See https://docs.docker.com/compose/install/ → "Alternative Install Options".
> 
> ```
> sudo curl -L --fail https://github.com/docker/compose/releases/download/1.26.0/run.sh -o /usr/local/bin/docker-compose
> sudo chmod +x /usr/local/bin/docker-compose
> 
> docker-compose --version
> ```

This work for me.  On Mac 10.15.6. Edge version.

**Comment by giaosudau** [comment]
For my case it dues to the Antivirus - KAV specifically so I need to stop the KAV and it works.
If you have this case please check your Antivirus and whitelist the docker-compose.

**Comment by ldeluigi** [comment]
Same for me on windows:
![image](https://user-images.githubusercontent.com/44567586/152304577-da731771-7cbe-4d32-9b53-9e2d8164ae22.png)
Diagnostics ID: A31C72BE-A4EB-4D91-81F3-6EB4722D296F/20220203080937

**Comment by ldeluigi** [comment]
.
