### ISSUE TITLE
Docker-Compose run does not follow restart policy.

### ISSUE THREAD

**Issue by dillu24** [docker/compose#7375]
# Description of the issue

I have a service named `alerter` with restart policy `always`. However when I type the following command `docker-compose run --service-ports -d alerter` the restart policy is not observed when the service finishes.

**Comment by gurubobnz** [comment]
Hi, I am not a docker-compose expert but can you post your `docker-compose.yml` file so we can have a closer look? Also the output (with sensitive information redacted) of `docker-compose logs` would be helpful.
