### ISSUE TITLE
/usr/local/bin/docker-compose: line 1: Not: command not found

### ISSUE THREAD

**Issue by paul-8235d9** [docker/compose#7378]
## Description of the issue
System - Fresh install of Raspbian Buster Lite (Feb 2020) on a Pi 3B. 
I've tried to instal docker-compose several ways;

1) sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

and

2) sudo apt-get install docker-compose

But I'm not able to get docker-compose to respond.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
paul@Pi3B-2:/ $ docker-compose --version
/usr/local/bin/docker-compose: line 1: Not: command not found

However;

paul@Pi3B-2:/ $ sudo apt-get install docker-compose
Reading package lists... Done
Building dependency tree
Reading state information... Done
docker-compose is already the newest version (1.21.0-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```

**Output of `docker version`**
```

paul@Pi3B-2:/ $ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:35:24 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:22 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
paul@Pi3B-2:/ $ docker-compose config
/usr/local/bin/docker-compose: line 1: Not: command not found

```
## Steps to reproduce the issue

1. sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
 appears to fail. It returns; 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     31      0 --:--:-- --:--:-- --:--:--    31

2. sudo apt-get install docker-compose
Appears to install but docker-compose --version does not respond.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by paul-8235d9** [comment]
I see the issue is Docker-Compose does not support armv7 / v8 (yet) This is a duplicate of [#6831](https://github.com/docker/compose/issues/6831)

**Comment by jtdoank** [comment]
> 

this working on Debian 10.2

**Comment by jtdoank** [comment]
> Can you use this command?
> 
> ```
> sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
> ```
> 
> I'm using this version it ok

yes, also working on Debian 10.2

**Comment by audioscavenger** [comment]
why did you guys renamed the releases from 'Linux' to 'linux' ?
because of that, calling the url via `$(uname -s)` does not work anymore. the case matter
