### ISSUE TITLE
Doesn't checks at ~/.ssh/config when i try to use --context for ssh connection

### ISSUE THREAD

**Issue by utrumo** [docker/compose#7381]
## Description of the issue
docker-compose doesn't check ~/.ssh/config file for information about how to connect by ssh to remote host, specified in context
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.0-rc3, build unknown
docker-py version: 4.2.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  nginx:
    hostname: nginx
    image: nginx
    ports:
    - published: 8080
      target: 80
version: '3.8'
```

## Steps to reproduce the issue
1. Add to docker-compose.yml:
```
version: "3.8"
services:
  nginx:
    image: nginx 
    hostname: nginx
    ports:
      - "8080:80"
```
2. Add to ~/.ssh/config:
```
Host my-server
Hostname 192.168.1.10
  User admin
  IdentityFile ~/.ssh/my-server
```
3. Add my-server to docker context:
`docker context create my-server --docker host=ssh://my-server --default-stack-orchestrator swarm` (--default-stack-orchestrator key in order to avoid this error: https://github.com/docker/compose/issues/7319)
4. Check that it works correct:
```
➜  test docker --context my-server ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
5. Try to start service from docker-compose.yml on my-server:
`docker-compose -c my-server up`

### Observed result
docker-compose tries to connect using each available ssh key from ssh-agent in turn until the server closes connection.
### Expected result
docker-compose looks at `IdentityFile` parameter from `Host my-server` section of ~/.ssh/config file and use value from it `~/.ssh/my-server` for ask specified key from ssh-agent and use it for connecting to remote host.
### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/command.py", line 76, in project_from_options
    environment_file=environment_file
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/command.py", line 142, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/docker_client.py", line 47, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/docker_client.py", line 169, in docker_client
    client = APIClient(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 166, in __init__
    base_url, timeout, pool_connections=num_pools
  File "/usr/local/lib/python3.7/dist-packages/docker/transport/sshconn.py", line 111, in __init__
    self._connect()
  File "/usr/local/lib/python3.7/dist-packages/docker/transport/sshconn.py", line 119, in _connect
    self.ssh_client.connect(**self.ssh_params)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 700, in _auth
    self._transport.auth_publickey(username, key)
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1570, in auth_publickey
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
19.10 / Ubuntu, sudo apt install python3-pip && sudo pip3 install docker-compose==1.26.0rc3

**Comment by 0az** [comment]
I managed to get it to work on rc4, though I had to double check that the ssh-agent was running.

Some visibility into this would be helpful: I had to patch Paramiko to print the agent's keys before I realized that the agent wasn't running. A warning along the lines of "No keys found in agent, or agent not found. Double check your SSH_AUTH_SOCK!" would be great.

This needs to be done on the docker/docker-py end, though.

**Comment by simonsd** [comment]
Issue still present, docker-compose completely ignores ssh options set in ssh_config

$ docker-compose version
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
