### ISSUE TITLE
Add --quiet-pull to docker-compose run

### ISSUE THREAD

**Issue by alanbccoe** [docker/compose#7391]
**Is your feature request related to a problem? Please describe.**
`docker-compose run` prints info on images it pulls which makes it difficult to grab the output when used in shell scripts. 

**Describe the solution you'd like**
`docker-compose up` has a flag `--quiet-pull` to disable printing that information. I'd like the same flag on `run` please.

**Describe alternatives you've considered**
Pulling then running, but it's easy to forget if you've already pulled the image but are using this on e.g. a CD system that hasn't pulled it yet. Then extra garbage gets added to your captured stdout (e.g. when doing `name=$(docker-compose run bash print-name.sh)`)

Also, it seems to print to stdout, so redirecting 2>/dev/null doesn't seem to work.

**Comment by jonaskello** [comment]
I have the same request. I use `docker compose run` to run a test service with many dependent services and all the pull output is really messy. Why was this abandoned?

**Comment by joshua-bn** [comment]
Same `docker-compose run --quiet-pull wdio npm run wdio` shows all of the pull info

**Comment by tolgaatam** [comment]
Same for me, quiet-pull flag is accepted but it does not work.
