### ISSUE TITLE
Support `runtime` parameter in 3.x schema

### ISSUE THREAD

**Issue by khimaros** [docker/compose#7392]
**Is your feature request related to a problem? Please describe.**
I am trying to upgrade my configs from 2.3 to 3.x configuration version. However, I currently use the `runtime` parameter to selectively enable `runsc` for some containers.

**Describe the solution you'd like**
Provide a way to specify `runtime` in the 3.x schema.

**Describe alternatives you've considered**
The only alternatives I see is remaining on 2.3 or migrating off of docker-compose for managing my runsc containers.

**Additional context**
It appears that some work was done on this here https://github.com/docker/compose/pull/6240 but it does not appear to have made its way into [the 3.8 schema](https://github.com/docker/compose/blob/master/compose/config/config_schema_v3.8.json).

**Comment by ndeloof** [comment]
docker-compose since 1.28 adopted the Compose specification and as such supports all v2 and v3 attributes in a compose.yaml file
