### ISSUE TITLE
run container with docker-compose up, then another one container disapeared

### ISSUE THREAD

**Issue by JackZhai2018** [docker/compose#7399]
step1) up 3 containers(A, B, C) with "docker-compose up" command.  
           -> run  ”docker ps -a“ to check status,  A, B, C all UP
step2) up container A for new version image  
           -> run  ”docker ps -a“ to check status,  then found A UP， B disappeared
step3) up container B  
           -> run  ”docker ps -a“ to check status,  then found B UP， A disappeared

Dose anyone have the same case.  any idea about how to resolve it.

**Comment by dinyadin** [comment]
@JackZhai2018 : Can you let me know what proper command you use in step 2 and 3 for new version image?

**Comment by JackZhai2018** [comment]
@

> @JackZhai2018 : Can you let me know what proper command you use in step 2 and 3 for new version image?

step2)   run "docker-compose up" with compose file of A (new version image)
step3)   run "docker-compose up" with compose file of B (new version image)

**Comment by dinyadin** [comment]
@JackZhai2018 : I will check and get back to you on this
