### ISSUE TITLE
impossible to download

### ISSUE THREAD

**Issue by JOduMonT** [docker/compose#7401]
it is possible to offer another way to download docker-compose
other than amazon s3 which is the github backend
because since 2weeks now this backend is very slow from bangkok and singaporse
such as 

```
curl -L https://github.com/docker/compose/releases/download/$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   638  100   638    0     0   4557      0 --:--:-- --:--:-- --:--:--  4557
  0 16.7M    0  152k    0     0   1267      0  3:51:20  0:02:03  3:49:17     0
```
end it end by simply stop
I download, such as a torrent link, webtorrent and/or a repository in amazon asia
or even by mail
what ever it's very painfull

**Comment by JOduMonT** [comment]
`now we talk about  1 16.7M    1  186k    0     0    505      0  9:40:24  0:06:17  9:34:07     0    `                      
while my speedtest is totally representative of my internet connection (200/200)
![image](https://user-images.githubusercontent.com/5204724/80357568-5f6a3a00-88a5-11ea-93a5-63f5a3c1badf.png)

**Comment by JOduMonT** [comment]
on it's way
 26 16.7M   26 4572k    0     0    487      0 10:01:51  2:40:06  7:21:45     0

**Comment by hholst80** [comment]
This is not a bug of docker compose but a bug related to github.com infrastructure?

**Comment by JOduMonT** [comment]
it's a bug on the internet, but support@internet.com don't exist
my request is if it's possible to have mirror outside of us or amazon s3
or better to have a torrent version
