### ISSUE TITLE
If you have multiple docker-compose.yml files in the same directory with the same service names in them, the file that runs second will recreate the first file's container.

### ISSUE THREAD

**Issue by jerrac** [docker/compose#7403]
## Description of the issue
docker-compose recreates containers when it shouldn't. If you have multiple docker-compose.yml files in the same directory with the same service names in them, the file that runs second will recreate the first file's container.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
$ docker-compose --version        
docker-compose version 1.25.5, build unknown
```

**Output of `docker version`**
```
$ docker --version
Docker version 19.03.8, build afacb8b7f0

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
$ docker-compose -f test01.docker-compose.yml config
services:
  httpd:
    container_name: test01_httpd
    image: httpd:latest
version: '2.0'

$ docker-compose -f test02.docker-compose.yml config
services:
  httpd:
    container_name: test02_httpd
    image: httpd:latest
version: '2.0'

```

## Steps to reproduce the issue

1. Run `docker-compose -f test01.docker-compose.yml up -d`
2. Run `docker-compose -f test02.docker-compose.yml up -d`

### Observed result
docker-compose recreates `test01.docker-compose.yml`'s service. 

Only the second file's container is running.

### Expected result
Two containers should be running. 

## Additional information
I have no idea how much of an edge case this might be, I wasn't able to find anything in my searches when diagnosing the issue.

So I'll report this and let it be.

When you use multiple docker-compose.yml files in your project (in my case I was simulating something) and the services in them have the same name, docker-compose will override the first file's container with the second file's. Even when the containers have different `container_name` values.

My example:

test01.docker-compose.yml
```yaml
version: '2'

services:
  # test01_httpd:
  httpd:
    image: httpd:latest
    container_name: test01_httpd
```

test02.docker-compose.yml
```yaml
version: '2'

services:
  # test02_httpd:
  httpd:
    image: httpd:latest
    container_name: test02_httpd
```

If you run both files, you'd expect that you'd end up with two running containers. Instead, the second file kills the first file's container and replaces it with its own.

```bash
$ docker-compose -f test01.docker-compose.yml up -d  
Creating network "composeorphans_default" with the default driver
Creating test01_httpd ... done

$ docker ps | grep test
4260a91c4a64        httpd:latest          "httpd-foreground"       10 seconds ago      Up 9 seconds        80/tcp                                 test01_httpd

$ docker-compose -f test02.docker-compose.yml up -d
Recreating test01_httpd ... done

$ docker ps | grep test                            
515d4a82d969        httpd:latest          "httpd-foreground"       3 seconds ago       Up 2 seconds        80/tcp                                 test02_httpd

```

If you modify the compose files to name the services with different names, you end up with this output:

```bash
$ docker-compose -f test01.docker-compose.yml up -d 
Creating network "composeorphans_default" with the default driver
Creating test01_httpd ... done

$ docker ps | grep test                             
d4178d30ae75        httpd:latest          "httpd-foreground"       15 seconds ago      Up 14 seconds       80/tcp                                 test01_httpd

$ docker-compose -f test02.docker-compose.yml up -d
WARNING: Found orphan containers (test01_httpd) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating test02_httpd ... done

$ docker ps | grep test                            
3472eb07078f        httpd:latest          "httpd-foreground"       3 seconds ago       Up 2 seconds        80/tcp                                 test02_httpd
d4178d30ae75        httpd:latest          "httpd-foreground"       24 seconds ago      Up 23 seconds       80/tcp                                 test01_httpd

```

I could sort of understand this behavior if I wasn't setting `container_name`, since compose names the containers based on the directory they are in, and the service name. But I set `container_name` specifically to avoid that. So it is very weird to me that compose would recreate the service this way.

But, I wouldn't think it's ever a good idea to do a recreate unless the --force-recreate flag is set. So, even if `container_name` is supposed to be ignored, I'd expect an error message. Not for compose to recreate the container.

This is using docker-compose installed via pip on an Ubuntu 18.04 machine.

**Comment by hholst80** [comment]
This is not a bug. You need to create two separate stacks if you want them deployed at the same time. Consult the COMPOSE_PROJECT environment variable and the command line arguments:

```
  -p, --project-name NAME     Specify an alternate project name
                              (default: directory name)
```

**Comment by hholst80** [comment]
If your intention was to *extend* the other service, you must specify *both* yaml configuration files. https://docs.docker.com/compose/extends/

**Comment by jerrac** [comment]
Thanks for the replies. :) I had not come across the `--project-name` flag, or the ability to use multiple compose files until now. So, yes, not a bug. 

Actually, how did I add that label? I know I didn't do so on purpose, I leave labels to the project maintainers....

**Comment by ShahanMirza** [comment]
These comment made my day. Thanks a lot all of them, Cheers

**Comment by kissme666** [comment]
Had the same problem. 

diff dir, but in the same stack .... 🤦‍♂️
```
├── A-project
│   └── dev
│       ├── Dockerfile-dev
│       ├── entrypoint.sh
│       └── docker-compose.yml
├── B-project
│   └── dev
│       ├── Dockerfile-dev
│       └── docker-compose.yml

```
