### ISSUE TITLE
Proposal: don't stop containers when `fig up` exits

### ISSUE THREAD

**Issue by dnephin** [docker/compose#741]
With the current behaviour of `fig up` all container are stopped when a single container exits. This has caused some confusion.

* if a `fig.yml` contains any data volume containers (anything that would exit immediately) `fig up` is entirely useless, a `-d` must be specified every time
* if someone does a `fig stop <some service>` in a different terminal, it causes all containers to stop (which is not intuitive).

I propose the default for `fig up` change. Some ideas:

* default to `-d`, and provide a flag to allow the old behaviour
* default to tailing logs, but don't stop containers on <ctrl-c> or when any container stops, leave everything running.
* show a `fig ps` as the output after starting containers, to show that all containers have started properly (or not) (credit @thaJeztah)

I only ever use `fig up` with `-d`, and I wonder if others are using it this way.  It seems like for CI you would have to, and for a development environment you may want to start/stop containers independently, so you'd still need `-d`.

**Comment by Starefossen** [comment]
Yes, please! `docker-compose up` should have the same behaviour as `docker-compose up -d`.

**Comment by pikeas** [comment]
+1 for `-d` by default and auto-attaching logs.

**Comment by dnephin** [comment]
Fixed #1754, will be in the 1.5 release, we went with the second option

**Comment by vanquangthanhhao** [comment]
You can't add "-ti" if you run docker by "docker run" command.
Or You add "tty: true "if you can by "docker compose" file
Reference :https://docs.docker.com/compose/compose-file/
