### ISSUE TITLE
Ability to disable log prefixes

### ISSUE THREAD

**Issue by flolu** [docker/compose#7416]
**Describe the solution you'd like**
A flag like `--disable-log-prefix` to remove the log prefixes.

![Screenshot from 2020-04-30 11-57-08](https://user-images.githubusercontent.com/34191949/80697969-10f1b100-8ada-11ea-88dd-95304bd928cc.png)

I have implemented my own log prefixes into the services I am running. Thus the log prefixes by docker compose are redundant.

**Describe alternatives you've considered**
For now I am using [this](https://stackoverflow.com/a/58467189/8586803) workaround, which works surprisingly good.
```
docker-compose up --no-color 2>&1 | sed 's/^[^ ]*  *| //' 
```

But it has one problem: `CTRL + C` will not stop the containers. (any ideas why?)

**Additional context**
I am not familiar with the docker compose source code, but it seems as if this is a relatively simple change around here: https://github.com/docker/compose/blob/9c5351cf27d10a7b8078496fb21a37929b6687cb/compose/cli/log_printer.py#L29

**Comment by rohitkg98** [comment]
Seems pretty straight forward. I'll add and create a PR.

**Comment by rohitkg98** [comment]
Made the PR. As for your question, `CTRL + C` sends `SIGINT` to all processes in the pipe, so both `docker-compose up` and `sed` get a `SIGINT`. but the former tries to write to the pipe of the latter before shutting down. This pipe is now broken, so it sends `SIGPIPE` which is not handled I think. I got the explanation from [here](https://unix.stackexchange.com/questions/407233/how-to-pipe-a-bash-command-and-keep-ctrlc-working).

**Comment by rohitkg98** [comment]
Should I make a PR to [Docker Docs](https://github.com/docker/docker.github.io) too?

**Comment by flolu** [comment]
@rohitkg98 Awesome! I think a PR to docs is necessary when the code is actually merged.

And for the `CTRL + C` part, I just hope that your pr is merged :laughing: But good to know what causes the problem!

**Comment by simonhir** [comment]
Just for reference.
Docs merge request: https://github.com/docker/docker.github.io/pull/12174
Auto completion merge request: https://github.com/docker/compose/pull/8067

**Comment by rubensayshi** [comment]
hey @flolu this is really nice, did you consider also adding some env var support?

I wouldn't mind doing a PR to add support for toggling this with an env var (seems like a nice first-issue), but wondering if there was a reason you chose not to do this ;) ?
