### ISSUE TITLE
docker-compose does not set environment variables

### ISSUE THREAD

**Issue by Kytech** [docker/compose#7423]
# Description of the issue

When using `docker-compose up` or `docker-compose run -e ENVIRONMENT_VAR=value`, environment variables are not being applied either through the `-e` command line parameters or from the docker-compose.yml file.

The docker-compose.yml file I am using is as follows:
```YML
version: '3'
services:
    nginx-reverse-proxy:
        image: nginx
        volumes:
         - C:/Users/<Username>/nginx-reverse-proxy/configdir:/etc/nginx/conf.d/
        ports:
         - "80:80"
        environment:
            NGINX_SERVER_NAME: "test.mysite.org"
            NGINX_REMOTE_URL: "http://remote.mysiteengine.somehost.com:13345"
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build 8a1c60f6
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
WARNING: The NGINX_SERVER_NAME variable is not set. Defaulting to a blank string.
WARNING: The NGINX_REMOTE_URL variable is not set. Defaulting to a blank string.
services:
  nginx-reverse-proxy:
    environment:
      NGINX_SERVER_NAME: "test.mysite.org"
      NGINX_REMOTE_URL: "http://remote.mysiteengine.somehost.com:13345"
    image: nginx
    ports:
    - 80:80/tcp
    volumes:
    - C:\Users\<Username>\nginx-reverse-proxy\configdir:/etc/nginx/conf.d/:rw
version: '3.0'
```

## Steps to reproduce the issue

1. Create a docker-compose.yml file that sets environment variables
2. Run docker-compose up

### Observed result

Environment Variables are not applied

### Expected result

Environment variables should be applied to containers started by docker-compose

### Stacktrace / full error message

```
WARNING: The NGINX_SERVER_NAME variable is not set. Defaulting to a blank string.
WARNING: The NGINX_REMOTE_URL variable is not set. Defaulting to a blank string.
Creating network "nginx-reverse-proxy_default" with the default driver
```

## Additional information

OS Version: Windows 10 Pro v1909,
`docker-compose` install method: Docker Desktop for Windows Installer, followed by manual upgrade of docker-compose (Issue occurred on docker-compose version 1.25.4 which was included with Docker Desktop and with manual upgrade to 1.25.5)

**Comment by hholst80** [comment]
???
This yaml is broken. Please post the actual yaml you are deploying with.
```
        volumes:
         - C:/Users/<Username>/nginx-reverse-proxy/configdir:/etc/nginx/conf.d/
```

**Comment by Kytech** [comment]
This is the yaml I am using. It works exactly as expected when I don't have environment variables included. I am using docker for Windows, so the file path format is different than with linux. I have not included my PC username for privacy purposes.

**Comment by Kytech** [comment]
> ???
> This yaml is broken. Please post the actual yaml you are deploying with.
> ```
>         volumes:
>          - C:/Users/<Username>/nginx-reverse-proxy/configdir:/etc/nginx/conf.d/
> ```

This is the yaml I am using. It works exactly as expected on my local machine when I don't have environment variables included. I am using docker for Windows, so the file path format is different than with linux. I have not included my PC username for privacy purposes.

**Comment by kravchenkoloznia** [comment]
Facing the same issue.

And I found that environment variables are working only from `.env` file placed in the folder where the docker-compose command is executed (current working directory).

Providing environment variables from command line giving the same warnings as @Kytech mentioned.

```shell
$ docker-compose run -e PRODUCT=1 all
WARNING: The PRODUCT variable is not set. Defaulting to a blank string.
```

Providing environment variables from user-specific `docker-compose.env` file still resulting with the same warnings

```shell
$ cat docker-compose.env 
PRODUCT=1
RELEASE=0
FLASH=0
DEBUG=3

$ cat docker-compose.yml 
version: '3'
services:
  all:
    image: 82100_src:latest
    env_file: ./docker-compose.env
    volumes:
      - .:/home/user
    command: make PRODUCT=${PRODUCT} all RELEASE=${RELEASE} FLASH=${FLASH} DEBUG=${DEBUG}

$ docker-compose run all
WARNING: The PRODUCT variable is not set. Defaulting to a blank string.
WARNING: The RELEASE variable is not set. Defaulting to a blank string.
WARNING: The FLASH variable is not set. Defaulting to a blank string.
WARNING: The DEBUG variable is not set. Defaulting to a blank string.
```

I'm using Linux Debian 10 with next versions of Docker and Docker-compose:

```shell
$ docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

$ docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:25 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:23:57 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by hholst80** [comment]
.env file and env_file have different semantics. If you want to use variable interpolation in your compose file you have to use the .env file.

**Comment by hholst80** [comment]
My conclusion here is that the -e environment variables are treated with the same semantics as env_file. Consistent with docker cli run cmd.

**Comment by kravchenkoloznia** [comment]
@hholst80 indeed, my mistake.

After reading docker documentation one more time and few additional articles, it's now obvious for me that for substitution in docker-compose file itself used environment variables of my current shell, and to send environment variables inside docker container I may use either docker run CLI or env_file. 

Thanks!

**Comment by Kytech** [comment]
@kravchenkoloznia that should be a good workaround in the meantime.

I hope the docker team fixes this since it's broken just about every docker-compose file I've been using that specifies environment variables in the docker-compose.yml

**Comment by azryelryvel** [comment]
Nothing is working for me, I can't use any environment variable :
```
/tmp/test$ curl -SsL "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
/tmp/test$ ls -a
.  ..  docker-compose  docker-compose.yml
/tmp/test$ cat docker-compose.yml
version: '3'
services:
  test:
    image: 'busybox'
    command: env
    environment:
      - HELLO=WORLD
/tmp/test$ sudo ./docker-compose down
Removing network test_default
WARNING: Network test_default not found.
/tmp/test$ sudo ./docker-compose up -d
Creating network "test_default" with the default driver
Creating test_test_1 ... done
/tmp/test$ sudo docker logs test_test_1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=b68e605e609d
HOME=/root
```

**Comment by Mahima-ai** [comment]
Hey,  While working on docker with Celery and Rabbitmq integration, I also faced the issue where the environment variables were not used up (set) though they can be seen using the env command in the container. I solved the issue by taking the below two steps.

1. I uninstalled the older docker-compose and installed the latest by following [https://docs.docker.com/compose/install/](url)
2. I renamed the service for which the environment variables were defined in the docker-compose.yml.

Later on, I rechecked with the old service name and found that the issue reappeared. Then I removed the older container and again did `docker-compose up`. This solved the issue. So I think, it might be the old container which does not let us see the new changes.

I am using Docker Engine v19.03.12 and docker-compose v 1.26.2

The contents (related to the issue) of my docker-compose.yml are:
`version: "3.8"

services:  
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=user1
      - RABBITMQ_DEFAULT_PASS=password1
    ports:
      - "5672:5672"
      - "15672:15672"`

**Comment by agovindaraju** [comment]
I am on the latest version of docker compose 1.27.4. I still the same issue as other users have describe above.

**Comment by michaelpburt** [comment]
I am also experiencing the same problem on the latest version of Docker (2.4.0.0).

**Comment by kerolos-sss** [comment]
I have encountered the same issue, 
My issue was caused by running docker-compose in a different python virtual environment.

I hope this could help.

It seems that by running on a different python virtual env, I ruined the docker-compose dependency pythondotenv

**Comment by zachsa** [comment]
I ran into this problem trying to use `docker-compose` to recreate a Mongo container.

```
MONGO_USER=me MONGO_PSWD=somepswd docker-compose up -d --force-recreate --build
```

This works, providing volumes associated with the resultant container are recreated (delete the volumes that the container will use and recreate)

**Comment by MatteoGioioso** [comment]
I have the same exact bug with the latest version of Docker 20.10 and Docker-compose 1.27 on Mac OS

**Comment by kovan** [comment]
Same happening here

**Comment by namighajiyev** [comment]
In my case only newly added one environment variable is not set in running container others get set normally.

  ```
       environment:
             Api__ConnectionString: ${Api_Docker__ConnectionString}
             Api__Recaptcha__Secret: ${Api_Docker__Recaptcha__Secret}
             ASPNETCORE_URLS: 'https://+;http://+'
             ASPNETCORE_HTTPS_PORT: 10081
             ASPNETCORE_Kestrel__Certificates__Default__Password: ${Api__Kestrel__Certificates__Default__Password}
             ASPNETCORE_Kestrel__Certificates__Default__Path: /https/Api/api.pfx
```
 I run **_printenv_** command inside  running Linux container and verified that the **Api__Recaptcha__Secret** variable   doesn't get set.

**Comment by kavatari** [comment]
Facing the same issue with newly added env variables, they are not created.

**Comment by JonnyWaffles** [comment]
This same incredibly confusing issue is occurring to me. Some of my environmental variables set in my yaml file are respected during the runtime execution, and others are missing and my runtime script validation functions terminate the container. Awkwardly, I can see all of the variables properly set in the PyCharm Environmental Variables Docker inspection. Like @namighajiyev reports above, it appears my more recent environmental variables are not being respected during runtime.

I tried `docker-compose build --no-cache` but that doesn't resolve the issue either.

**Comment by hehejiuhuizhe** [comment]
I just meet the same bug. I use `docker stack deploy`  to start a set of services. Then I add some environment variables and public ports to the compose yml. Then I use  `docker stack rm` to remove the stack and use `docker stack deploy`  to restart the services. But the  environment variables and public ports are not added. 

I find I need to use `docker service rm` to remove the service and then when I use  `docker stack deploy`  , the environment variables and public ports are added.  Or I can use `docker service  update` to add the  environment variables and public ports by command line.

**Comment by joma74** [comment]
Had some luck by starting docker-compose in non daemon mode after a change to environment setting(via environment section in docker-compose.yml). Then stop that and start in daemon mode again, environment settings are kept.

**Comment by franklinchou** [comment]
Any update on this? Seems that docker-compose is still not picking up .env files?

**Comment by ndeloof** [comment]
Please give Compose v2 a try and let me know if this issue persists with the new codebase

**Comment by ubiuser** [comment]
`docker compose up --build <your-container>` fixed the issue for me.

**Comment by Lhamide00** [comment]
Any update on this?

I have the exact same bug with Docker version 20.10.11 and Docker-compose 1.29.2 on Mac OS. 

Removing and re-building the containers did not help. Doesn't matter whether I `docker-compose up` with or without `-d` flag either; bug remains!

**Comment by qalinn** [comment]
Hello!
I have the same issue.  Any update on this?

**Comment by ubiuser** [comment]
@Lhamide00 @qalinn As earlier said by @ndeloof, please try using v2, so call `docker compose` instead of `docker-compose`.

**Comment by qalinn** [comment]
Hello @ubiuser, I tried how you suggested but it didn't work. I don't have any clue what should I try.
Do you have another suggestion?

**Comment by JonnyWaffles** [comment]
Hi friends, we once again encountered this mysterious error even when using `docker compose` instead of `docker-compose`. Random environmental variables vanish.

**Comment by nguyenhoai890** [comment]
I  got this issue too:
`docker version`

> Client:
>  Cloud integration: v1.0.22
>  Version:           20.10.13
>  API version:       1.41
>  Go version:        go1.16.15
>  Git commit:        a224086
>  Built:             Thu Mar 10 14:08:43 2022
>  OS/Arch:           darwin/arm64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Desktop 4.6.1 (76265)
>  Engine:
>   Version:          20.10.13
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.16.15
>   Git commit:       906f57f
>   Built:            Thu Mar 10 14:05:37 2022
>   OS/Arch:          linux/arm64
>   Experimental:     false
>  containerd:
>   Version:          1.5.10
>   GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
>  runc:
>   Version:          1.0.3
>   GitCommit:        v1.0.3-0-gf46b6ba
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

The error message I got:

> WARN[0000] The "XXX" variable is not set. Defaulting to a blank string. 

docker-compose.yaml:

> version: "3.6"
> services:
>   abc:
>     image:abc
>     container_name: abc
>     hostname: abc
>     restart: always
>     expose:
>       - "8080"
>     environment:
>       - XXX=abc
>     volumes:
>       - ../../hasura:/bdjuno/hasura

**Comment by palunel** [comment]
Same here.

I have the following `docker-compose.yml`:

```
version: "3.9"

services:
  compute:
    build: .
    ports:
      - "27030:27030"
    environment:
      - COMPUTE_HOST=$COMPUTE_HOST
      - COMPUTE_PORT=$COMPUTE_PORT
```

In my `.env` file I have the following:

```
COMPUTE_HOST="0.0.0.0"
COMPUTE_PORT=27030
```

This is to start up a flask api, but what I get when I run the container with:

`docker compose --env-file .env up --build
`

or 

`docker-compose --env-file .env up --build`

is this:
 

```
apv_compute-compute-1  | APV server starting on port None ...
apv_compute-compute-1  |  * Serving Flask app 'api' (lazy loading)
apv_compute-compute-1  |  * Environment: production
apv_compute-compute-1  |    WARNING: This is a development server. Do not use it in a production deployment.
apv_compute-compute-1  |    Use a production WSGI server instead.
apv_compute-compute-1  |  * Debug mode: on
apv_compute-compute-1  |  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
apv_compute-compute-1  |  * Restarting with stat
apv_compute-compute-1  |  * Debugger is active!
apv_compute-compute-1  |  * Debugger PIN: 483-995-326
```
The api insists on starting on `127.0.0.1:5000` suggesting that the environment variables are not set at all.

When running the app outside of docker it works perfectly fine.
 Does anyone have a sensible workaround?

`Docker version 20.10.14, build a224086`

**Comment by ndeloof** [comment]
@palunel can you check `docker-compose exec <service> env` ?

**Comment by palunel** [comment]
Interesting:

```
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=42a08ea9f254
COMPUTE_HOST="0.0.0.0"
COMPUTE_PORT=27036
GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568
PYTHON_VERSION=3.9.12
PYTHON_PIP_VERSION=22.0.4
PYTHON_SETUPTOOLS_VERSION=58.1.0
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/38e54e5de07c66e875c11a1ebbdb938854625dd8/public/get-pip.py
PYTHON_GET_PIP_SHA256=e235c437e5c7d7524fbce3880ca39b917a73dc565e0c813465b7a7a329bb279a
HOME=/home/app

```

**Comment by ndeloof** [comment]
ok, so this is an application issue then :P

**Comment by Kytech** [comment]
Just to add my two cents as the original author if this issue, I've been able to successfully set env variables in docker compose for a little while now. Not sure what fixed it, but it seems newer versions resolved the issues I was having.

**Comment by Bakanych** [comment]
Having similar issue right now
Docker version 20.10.14, build a224086

**Comment by Azbesciak** [comment]
Same as me, casual docker-compose, after update on windows to 4.8.1 (docker for windows) env variables are not passed to the container, even if in inspect mode these are visible...
but `printenv` does not print anything like this.

**Comment by michael-gates-techngs** [comment]
Experiencing this issue on Docker 20.10.17 build 100c701 on an M1 Mac.

**Comment by unRARed** [comment]
> Experiencing this issue on Docker 20.10.17 build 100c701 on an M1 Mac.

same build, same issue on an Intel Mac this afternoon.

**Comment by andremarcondesteixeira** [comment]
I have the same problem, using docker compose v2
extremely frustrated! :(

**Comment by glours** [comment]
@andremarcondesteixeira feel free to open a new issue with an example that allows us to reproduce the problem (compose file, dockerfile, try to use official images...)

**Comment by gopar** [comment]
Any updates on this? Running into this today as well.
Tried re-installing and did not work.

Extremely unfortunate

**Comment by glours** [comment]
Hello @gopar 
Can you open a new issue with a reproducible example?

**Comment by HansBambel** [comment]
I had a similar issue, but substituting `RUN` with `CMD` for the last command made the environment variables discoverable. This [Stackoverflow post](https://stackoverflow.com/questions/33107164/docker-compose-not-setting-environment-variables) helped me with this.

**Comment by phutaneVinayak** [comment]
Any update on this ?

**Comment by Lucas-Delacroix** [comment]
any update?

**Comment by ndeloof** [comment]
@phutaneVinayak :

> Can you open a new issue with a reproducible example?

**Comment by ihass** [comment]
Please also note environment variables concatenation in docker-compose is not working. Expl below, KC_HOSTPORT and KC_DUMMY can never be reused in the following environment variables (KC_COLON_HOSTPORT, KC_DUMMY2, KC_DUMMY3, ...). I tried a lot of combination. (My tech environment : Windows 11, Spring Boot, Gradle/Kotlin, Docker Desktop, IntelliJ)

`version: "3.8"

x-common-variables:
  &common-variables
  KC_HOSTNAME: localhost
  KC_HOSTPORT: 8080

services:
  dxcv-backend:
    environment:
      <<: *common-variables
      KC_PROTOCOL: http
      KC_DUMMY: dummy
      KC_DUMMY2: "$KC_DUMMY" #KO
      KC_DUMMY3: "${KC_DUMMY}" #KO
      KC_DUMMY3: "$${KC_DUMMY}" #KO
      KC_COLON_HOSTPORT: ":${KC_HOSTPORT}" #KO`

**Comment by ndeloof** [comment]
@ihass you expect compose to replace `${XX}` with other variables set by `environment`. Variable interpolation does not relies on this, but _only_  uses variables set in your local environment (os.Env) and local `.env` file.

**Comment by phutaneVinayak** [comment]
Sure I will give it a try.

vinayak Phutane

**Comment by mmngreco** [comment]
This worked for me:

```yaml
services:
  test:
    image: alpine
    # command: echo MYVAR=$MYVAR  # Not working
    # command: echo MYVAR=$$MYVAR  # Not working
    command: sh -c "echo MYVAR=$$MYVAR"
    environment:
      MYVAR: "asfd"

```

**Comment by justinabrahms** [comment]
Just noting for others, `docker-compose restart $mycontainer` isn't adequate to have it pick up envvars. `docker-compose up --force-recreate --build $mycontainer` does appear to be adequate.
