### ISSUE TITLE
Docker-compose up existed with 0

### ISSUE THREAD

**Issue by vishnutm** [docker/compose#7424]
## Description of the issue

when I run docker-compose up it existed with zero.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```

**Output of `docker version`**
```
 Version:           19.03.8

```

## Steps to reproduce the issue

1.docker-compose up

### Observed result

Starting frontend_web_1 ... done
![Screenshot from 2020-05-04 11-19-53](https://user-images.githubusercontent.com/30982642/80939174-545d5f80-8df9-11ea-8ecc-82476bef5281.png)

### Expected result
running on localhost port 3000

# Docker-compose yml file attached below
![Screenshot from 2020-05-04 11-18-22](https://user-images.githubusercontent.com/30982642/80939316-e4030e00-8df9-11ea-8ca6-453de9cd3157.png)

## Additional information about docker file
![Screenshot from 2020-05-04 11-25-48](https://user-images.githubusercontent.com/30982642/80939350-07c65400-8dfa-11ea-987c-4700553fa41e.png)

**Comment by ulyssessouza** [comment]
Have you tried with the latest version of `docker-compose`? 

Anyways, looks like your process is quitting
