### ISSUE TITLE
Docker compose doesn't use current `docker context` settings.

### ISSUE THREAD

**Issue by kmrozek-shareablee** [docker/compose#7427]
## Description of the issue
Docker compose doesn't use current `docker context` settings.

## Context information (for bug reports)
I've tried to use `docker context` feature with docker-compose. It failed to start services because it didn't use settings from docker context I set. I don't use Docker for Windows and only docker machine with docker toolbox.

** Output of `docker-compose version`**
```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client:
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Wed Jul 31 15:18:18 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
    - 5672:5672/tcp
    - 15672:15672/tcp
version: '2.1'
```

## Steps to reproduce the issue

1. Turn off docker daemon if running.
2. Create docker-machine with `docker-machine create test1`
3. Set env to this machine with `docker-machine env`.
4. Create docker context with `docker context create test1`.
5. Switch to this docker context with `docker-machine use test1`.
6. Check if `docker ps` works and is valid (nothing appears).
7. Try to run `docker-compose up`.

### Observed result
```
ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Windows.
```

### Expected result
It should start everything using settings from current `docker context`.

### Stacktrace / full error message
```
```

## Additional information

Windows 10

**Comment by andoks** [comment]
I had the same problem with 1.25.5, but upgrading to 1.26.2 fixed the issue for me (on linux mind you)
```
docker-compose version
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

```
docker-compose version
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
