### ISSUE TITLE
Docker-compose push skips second service if first has same image but no build section

### ISSUE THREAD

**Issue by musikov** [docker/compose#7429]
## Description of the issue
When you have multiple services with same image, but only one (not first) has `build` field, `docker-compose push` ignores it.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
```
services:
  first:
    image: my_app
  second:
    build:
      context: /Users/musikov/docker_push_issue
    image: my_app
version: '3.7'
```

## Steps to reproduce the issue

1. Create dummy dir `mkdir ~/docker_push_issue`
2. Go to it `cd ~/docker_push_issue`
3. Create dummy Dockerfile `echo 'from python' > Dockerfile`
4. Create docker-compose.yml file as in issue:
```
echo "services:
  first:
    image: my_app
  second:
    build: .
    image: my_app
version: '3.7'
" > docker-compose.yml
```
5. Build project `docker-compose build`
6. Push project `docker-compose push`

### Observed result
Command runs, but nothing happened.
### Expected result
Image is pushed. (for current example we must receive `no permission` error)
### Stacktrace / full error message
```
# docker-compose -verbose push
docker-compose version 1.25.4, build 8d51620a
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
macOS 10.15.4 (19E287), docker desktop

**Comment by samizdam** [comment]
Same problem with `docker-compose version 1.25.5, build 8a1c60f6`.

**Comment by stan-sz** [comment]
This seems to be due to condition in https://github.com/docker/compose/blob/854c003359bd07d0d3ca137d7a08509cfeab0436/compose/service.py#L1273-L1274

whereas earlier in the file 
https://github.com/docker/compose/blob/854c003359bd07d0d3ca137d7a08509cfeab0436/compose/service.py#L1161-L1162

Is `build` really needed to do push?

**Comment by musikov** [comment]
> Is `build` really needed to do push?

Yes. Build section means we can have some changes we want to push sometime. If no build phrase in compose file - than we have nothing new to push

**Comment by pmssantos** [comment]
Hi. Using argument **--force-recreate** seems to have helped.
`docker-compose up --force-recreate`

**Comment by padcom** [comment]
Well, the problem still persists in November 2022. Using docker compose push as well as docker-compose push

**Comment by armando-fandango** [comment]
it works if you have a build section, without build section it wont push.
