### ISSUE TITLE
Download Releases broken

### ISSUE THREAD

**Issue by jenswachtel** [docker/compose#7433]
When trying to download e.g.
https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64
https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64
results in 
```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>
```

Tools like ansible galaxy `geerlingguy.docker` seem to be broken because of it. I am unfortunately not able to use it either.

e.g. https://github.com/docker/compose/releases/tag/1.25.5 Also not possible to download anyting

Thanks,
Jens

**Comment by anupam128** [comment]
Seems like a GitHub wide (at least many repos) outage.
I cannot download artifacts from many repositories.

**Comment by jenswachtel** [comment]
This was a temporary issue with Github
Sorry!
Works again
