### ISSUE TITLE
Source secret file needs world readable permission

### ISSUE THREAD

**Issue by raratiru** [docker/compose#7436]
## Description of the issue

When using [secrets in compose](https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose), the secret file `/var/secrets/secret_file` (in the container) is not accessible unless the source file (in the host) is world readable.

This stands true even if the user in the container has the same `UID` or `GID` with the `user:group` assigned to the `secret_file` (which is `nobody:nogroup`).

## Context information (for bug reports)

**Output of `docker-compose version`**
```bash
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Output of `docker version`**
```bash
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```yaml
secrets:
  pass:
    file: /home/flyer/bug/pass.txt
services:
  test:
    build:
      context: /home/flyer/bug
    command: 'bash -c "ls -la /run/secrets && id && cat /run/secrets/pass"'
    container_name: test
    environment:
      PASSWORD_FILE: /run/secrets/pass
    secrets:
    - source: pass
version: '3.7'

```
**Dockerfile**
```bash
$ cat /home/flyer/bug/Dockerfile
FROM debian
USER nobody
```

**pass.txt permissions**
```bash
$ ls -la pass.txt
-rw-r----- 1 flyer flyer 8 May  9 00:31 pass.txt

```

**id nobody on the host**
```bash
$ id nobody
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)
```

## Steps to reproduce the issue

1. docker-compose up

### Observed result
```bash
$ docker-compose up
Creating test ... done
Attaching to test
test    | total 12

test    | drwxr-xr-x 2 root   root    4096 May  8 21:52 .
test    | drwxr-xr-x 1 root   root    4096 May  8 21:52 ..
test    | -rw-r----- 1 nobody nogroup    8 May  8 21:31 pass

test    | uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)

test    | cat: /run/secrets/pass: Permission denied
test exited with code 1
```

### Expected result

* I would expect that the source file on the host should not be world readable. 
* Otherwise, I would expect the secret file to be accessible without world readable permissions if the `uid` or `gid` match.

## Additional information

Running on `Debian 10, Buster`

```
$ uname -a
Linux House 5.4.0-0.bpo.4-amd64 #1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux

```

OS version / distribution, `docker-compose` install method, etc.

**Comment by sanmai-NL** [comment]
Not stale.

**Comment by mattpepin** [comment]
I have the same problem. Surely, there must be a way!

**Comment by sdavids** [comment]
https://github.com/moby/moby/issues/40046

**Comment by sanmai-NL** [comment]
Not stale.

**Comment by ndeloof** [comment]
as docker engine (without swarm) has no support for secrets, compose just implements secrets as a hack-ish bind mount, and doing so does no magic with file permissions for this file.

**Comment by raratiru** [comment]
CLosing this as it is balancing in a gray line of Docker Compose V1.
