### ISSUE TITLE
Add --compress option to docker-compose up

### ISSUE THREAD

**Issue by csbenjamin** [docker/compose#7439]
I know that `docker-compose build` already has the `--compress` option. But I would like to request that option to `docker-compose up` too. Right now I have to issue two commands: `docker-compose build --compress` and then `docker-compose up` instead a single command like `docker-compose up --build --compress`.

**Comment by ndeloof** [comment]
BuildKit is now the default builder for both docker-compose and Compose v2, so is using compressed streams by design
