### ISSUE TITLE
Installation Process on Linux/Ubuntu

### ISSUE THREAD

**Issue by Globegitter** [docker/compose#744]
Just testing out fig on Ubuntu and the installation instruction could imo be much better for that. Ran into a few issues and still have some not completely resolved.

First, if I install docker as mentioned in the ubuntu instructions `fig` only works if I run it as sudo via `sudo fig up` and I had to use follow instructions: https://gist.github.com/RuslanHamidullin/94d95328a7360d843e52
Next issue, I could not run
```
curl -L https://github.com/docker/fig/releases/download/1.0.1/fig-`uname -s`-`uname -m` > /usr/local/bin/fig; chmod +x /usr/local/bin/fig
```
without sudo. Which I suppose would be alright, but now when I run for example `fig run server sails new .` all the files are owned by root which causes other issues.

So what is the best practice to setup docker and fig that I can run `fig` without `sudo` and that when fig creates new files (through commands that are run in a container) these are not owned by root?

This has not been at all an issue on my Mac and I would be more than happy to add these additional instructions to the 'Installing' section.

**Comment by aanand** [comment]
I agree that we should ensure that Linux users have a less surprising first experience with Fig. Allowing non-root access to Docker may or may not be an acceptable solution - anyone else have strong feelings on that?

**Comment by Globegitter** [comment]
Seems like some more people ran into this, or similar issues so here are the steps that I took to resolve my issues:

After installing make sure you
 - have followed https://docs.docker.com/installation/ubuntulinux/#giving-non-root-access
 - then `sudo vim /etc/default/docker` and change `DOCKER_OPTS` to `DOCKER_OPTS="-H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock”`
 - `sudo restart docker`
 - Set a DOCKER_HOST environment variable: `export DOCKER_HOST=tcp://localhost:4243` (best to put it into your .bashrc/.zshrc/fish.config file so you have it always available)

@aanand @dnephin This also ensures a relatively consistent setup between Mac and Linux, since now both have a DOCKER_HOST set. Depending on what your opinion on these extra steps are I could make a documentation PR out of it.

**Comment by vire** [comment]
I've have the same problem (I'm trying to use sane - sails-cli) and I've granted non-root acces for the docker group, I've curl-ed fig into /home/$USER/bin (instead of /usr/local/bin which is owned by root) and still if I run `sane new testProject -d disk --docker` the directories in that project created by fig i thing are owned by root:root, so i don't know ho to force use fig use  the non-root user...

**Comment by dnephin** [comment]
We now mention `sudo` in the install docs: https://docs.docker.com/compose/install/

The "files owned by root" is a separate issue which needs to be addressed by docker. The workaround is to create a user in the image, and use `USER` to change the active user.
