### ISSUE TITLE
Support of Kompose to be able to deploy to virtually any orchestration engine

### ISSUE THREAD

**Issue by PavelSosin-320** [docker/compose#7443]
**Is your feature request related to a problem? Please describe.**
Docker-compose is able to deploy application only to Docker-swarm. It's hard to find today Clusters managed by swarm in the enterprise or Global cloud environment. There is Kubernetes kompose utility which converts docker-compose file into Kubernetes resource file and deploys docker-compose stack either to Kubernetes or OpenShift. It takes 5 minutes to install kompose for Windows and Linux.  
**Describe the solution you'd like**
Select the target engine as project properties or user's preference and deploy application stack to the desired engine with service publishing by one or two clicks.
1. Select the target engine in user or project preferences.
2. Create volumes ...
3. Create placeholders for secrets 
4. Deploy to the engine using a suitable deployment mechanism in one click
**Describe alternatives you've considered**
Everything can be done using bash script after learning to compose and resource file formats,i.e 1  months efforts.

**Additional context**
Very little additional code if the proper **design pattern provider** is used
Deployment mechanism for dockerized applications evolved from Swarm to OpenShist, i.e. highly compatible

**Comment by ndeloof** [comment]
What you describe is basically the topic of docker/compose-cli "Cloud Integration" project
