### ISSUE TITLE
`up` does not re-use anonymous volume even without `--renew-anon-volumes` given

### ISSUE THREAD

**Issue by FallenWarrior2k** [docker/compose#7444]
## Description of the issue
Using an anonymous volume like `volumes: [ '/data' ]` in docker-compose.yml will result in any data written to that directory and its descendants not being visible after a `docker-compose down` followed by another `docker-compose up`.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
λ docker-compose version
docker-compose version 1.25.5, build unknown
docker-py version: 4.2.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
λ docker version
Client:
 Version:           19.03.8-ce
 API version:       1.40
 Go version:        go1.14.1
 Git commit:        afacb8b7f0
 Built:             Thu Apr  2 00:04:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.1
  Git commit:       afacb8b7f0
  Built:            Thu Apr  2 00:04:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.4.m
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
λ docker-compose config
services:
  test:
    command: sh -c 'while true; do sleep 60; done'
    image: alpine
    restart: always
    volumes:
    - /data
version: '3.0'
```

## Steps to reproduce the issue

1. Go to the directory with the sample `docker-compose.yml` above.
2. `docker-compose up -d`
3. `docker-compose exec test sh -c 'echo "hello there" > /data/test.txt'`
4. `docker-compose down`
5. Verify the file still exists with `find /var/lib/docker/volumes -type f -name 'test.txt'` (or optionally view its contents with `find /var/lib/docker/volumes/ -type f -name 'test.txt' -exec cat {} \;`)
6. `docker-compose up -d`
7. `docker-compose exec test ls /data`

### Observed result
The `ls` command prints nothing.

### Expected result
The `ls` command should have shown one file named `test.txt`

## Additional information
OS: Arch Linux
Both Docker and Compose installed from official repos via pacman.

Also tested (and initially noticed) on both Ubuntu 16.04 and 18.04 with Docker installed from repos, but a significantly older Compose:
```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by hholst80** [comment]
Try doing a `docker-compose stop` instead of `docker-compose down`. Does that work?

**Comment by FallenWarrior2k** [comment]
I don't have my machine right now, but I'm assuming that would work.

If this is intended for `down`/`up`, however, I believe I'm misunderstanding the explanation for `--renew-anon-volumes`. The way it talks "previous containers" implies, to me, that not passing it will cause anonymous volumes from previously deleted containers to be re-used, which is not the case here.

**Comment by lognaturel** [comment]
@hholst80 Yes, using `docker-compose stop`, anonymous volumes are reused on `up`. From the documentation, I would expect the same to be true for `docker-compose down`.

From https://docs.docker.com/compose/reference/down/:

> By default, the only things removed are:
> * Containers for services defined in the Compose file
> * Networks defined in the networks section of the Compose file
> * The default network, if one is used

If it is intentional that anonymous volumes are orphaned on `down`, could that please be explicit in the documentation? I do agree with @FallenWarrior2k's assessment that this feels like a bug, though.

**Comment by lognaturel** [comment]
I've come across this looking at how to upgrade deployments and had the nasty surprise of finding out anonymous volume bindings are lost after a `down`. I've found the discussion starting at https://github.com/moby/moby/issues/30647#issuecomment-276882545 helpful.

And specifically: "When not naming your volume you generally mean: I don't "care" about its data, it's ok to remove after the container is removed."

Here is my proposed documentation change: https://github.com/docker/docker.github.io/pull/11601

**Comment by lognaturel** [comment]
I think this issue can be closed. https://docs.docker.com/compose/reference/down/ now says:

> Anonymous volumes are not removed by default. However, as they don’t have a stable name, they will not be automatically mounted by a subsequent up. For data that needs to persist between updates, use host or named volumes.

I have posted a related [Stackoverflow question](https://stackoverflow.com/questions/64885337/how-can-a-docker-compose-configuration-transition-from-using-anonymous-volumes-t) about how to migrate a docker-compose configuration that uses anonymous volumes to using named volumes without (perceived) data loss.
