### ISSUE TITLE
Suddenly getting "Cannot open self" errors while using the Compose Docker image

### ISSUE THREAD

**Issue by Southclaws** [docker/compose#7445]
## Description of the issue

I'm using [Pico](https://github.com/picostack/pico) which bases an image off Docker Compose in order to automatically run Docker Compose commands from a container.

Just today, after a new staging release, I've noticed the Docker Compose binary in both the `latest` (2751502a800a) and `1.25.5` (2751502a800a) images don't actually work any more. They spit out the following error when invoked by Pico (which is using Golang's cmd/exec package, the code between these versions that's responsible for invoking commands hasn't changed)

```
[14] Cannot open self /data/targets/project/docker-compose or archive /data/targets/project/docker-compose.pkg
```

However, the stable v1 tag of Pico works fine, it was built about a month ago using whatever `latest` Docker Compose image was available at the time (I realise now I should have specified a version to prevent these issues)

The working image is here: https://hub.docker.com/layers/picostack/pico/v1/images/sha256-f3a1a2105f6f893faa2c8df2f8f6c4eb2e726a3b49c0e09a36845bfb284c06e6?context=explore

And the broken one is here: https://hub.docker.com/layers/picostack/pico/staging/images/sha256-db5dde19b69c7cd812150f9cc84b565dd43e288ea0193041605cf5b1b22203e9?context=explore

I'm not sure how to see information about the parent image (the one that is used in `FROM`) but that would probably be useful.

## Context information (for bug reports)

I'll drop the versions for both the working and broken images below.

### Broken (1.25.5, latest)

**Output of `docker-compose version`**

```
docker-compose version 1.25.5, build 8a1c60f
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### Working (1 month ago `latest` build)

**Output of `docker-compose version`**

```
docker-compose version 1.25.1, build a82fef0
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**

```
Client: Docker Engine - Community
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:54:15 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Steps to reproduce the issue

Either build an image using `FROM docker/compose:1.25.5` or run Pico's staging image with a `docker-compose` target.

**Comment by hholst80** [comment]
docker/compose:1.25.5 works just fine, so there is a problem with Pico. Docker compose might have introduced a breaking change (as far as how Pico is using it). Share the Dockerfile of pico build so we can see?

**Comment by Southclaws** [comment]
It's super simple: https://github.com/picostack/pico/blob/master/Dockerfile

And the diff between master/staging doesn't really touch execution of commands: https://github.com/picostack/pico/pull/65/files

So it's a mystery so far...

**Comment by hholst80** [comment]
Mm. Nothing helping us there. Wild guess maybe the upstream container changed their default user ID or something like that. Try exec into your Pico container and run an strace to see if there are any syscalls failing. Is the pico program execv docker-compose through a shell or directly?

**Comment by Southclaws** [comment]
It's executing directly with Go's cmd/exec package. For now I've backdated to a working version. I'll check with strace when I next get around to it.

**Comment by Southclaws** [comment]
I fixed this months ago. I have no idea how, sorry to anyone finding this.
