### ISSUE TITLE
"Conflict. The container name is already in use by container" - running on host vs inside container

### ISSUE THREAD

**Issue by fsproru** [docker/compose#7454]
## Description of the issue
Running docker-compose up on the host or inside a docker container causes a name mismatch.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  redis:
    container_name: my-redis
    image: redis:alpine3.11
version: '3.0'
```

## Steps to reproduce the issue

1. Up the Redis service from a container mounting the host socket

```
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /path/to/test:/project-root --workdir=/project-root docker/compose:alpine-1.26.0-rc4  --file '/project-root/docker-compose.yml' up -d redis
Starting my-redis ... done
```

2. Up the Redis service from the host

```
$ cd /path/to/test; docker-compose  --file '/path/to/test/docker-compose.yml' up -d redis

ERROR: for my-redis  Cannot create container for service redis: Conflict. The container name "/my-redis" is already in use by container "***". You have to remove (or rename) that container to be able to reuse that name.
```

### Observed result

Docker Compose fails with the error on the host system:

```
ERROR: for my-redis  Cannot create container for service redis: Conflict. The container name "/my-redis" is already in use by container "***". You have to remove (or rename) that container to be able to reuse that name.
```

### Expected result
Since `/var/run/docker.sock` is mounted inside the docker container from step 1, I expected docker-compose to say that `my-redis` container is already started.

### Stacktrace / full error message

```
ERROR: for my-redis  Cannot create container for service redis: Conflict. The container name "/my-redis" is already in use by container "***". You have to remove (or rename) that container to be able to reuse that name.
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Host: macOS Catalina
docker-compose is installed using [Homebrew](https://brew.sh/)

**Comment by adrianlubitz** [comment]
Any insights by now?
Having a similar issue where I start some containers with docker-compose from the host system.
I have another container(`from docker/compose`), that does some backups and runs `docker-compose pull && docker-compose up -d` to spawn the newest version after the backup.
I get 

```
ERROR: for <CONTAINERNAME>  Cannot create container for service <CONTAINERNAME>: Conflict. The container name "/<CONTAINERNAME>" is already in use by container "9d739a5422ebd99357efd8a67b998ea626befbf025e25dc73752f14477eaad06". You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by xpader** [comment]
This failed because we use docker-compose and docker-compose-plugin together, remove docker-compose resolve this problem.

Another reason may because you have used buildkit features, but you don't have docker-buildkit-plugin installed.
