### ISSUE TITLE
fig not able to connect to docker , mac osx 10.9.5 and boot2docker

### ISSUE THREAD

**Issue by yashk** [docker/compose#746]
$ docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
$ fig --version
fig 1.0.1
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ echo $DOCKER_HOST
tcp://192.168.59.103:2376
$ boot2docker status
running
$ fig up
Couldn't connect to Docker daemon - you might need to run `boot2docker up`.

**Comment by sjevs** [comment]
@masom I had same issue. The answer is `$(boot2docker shellinit)`

Then
```
docker-compose up
```

Works perfectly. Please close the issue

**Comment by mikeatlas** [comment]
Hi, I had this problem.

```
% docker-compose build
Building myapp...
Couldn't connect to Docker daemon - you might need to run `boot2docker up`.

% boot2docker init
WARNING: The 'boot2docker' command line interface is officially deprecated.
 blah blah upgrade to Docker Toolbox https://www.docker.com/toolbox
Initialization of virtual machine "boot2docker-vm" complete.
Use `boot2docker up` to start it.

[OKAY - I INSTALLED DOCKER TOOLBOX]

% boot2docker up
Waiting for VM and Docker daemon to start...
.........................ooooooooooo
Started.
Your environment variables are already set correctly.

% boot2docker ip
192.168.59.103

% boot2docker status
running

% boot2docker version
Boot2Docker-cli version: v1.8.0
Git commit: 9a26066

% docker-compose version
docker-compose version: 1.4.0
docker-py version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014

% docker-compose restart
% docker-compose build
[ A lot of stuff rebuilt finally!) ]
% docker-compose up
[ My app finally started! ]
```

**Comment by sjevs** [comment]
can we close this issue already?

**Comment by dnephin** [comment]
Yes, I think so, looks like it has been solved, and the original author hasn't replied.
