### ISSUE TITLE
Please support ARM64 binary downloads

### ISSUE THREAD

**Issue by CorruptComputer** [docker/compose#7472]
## Description of the issue
Docker Compose fails to run with the following error: 
```
user@hostname:~$ sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     38      0 --:--:-- --:--:-- --:--:--    38
user@hostname:~$ sudo chmod +x /usr/local/bin/docker-compose
user@hostname:~$ docker-compose
/usr/local/bin/docker-compose: line 1: Not: command not found
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
Unable to run docker-compose
```

**Output of `docker version`**
```
user@hostname:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d98839
 Built:             Fri May 15 00:25:48 2020
 OS/Arch:           linux/arm64
 Experimental:      false
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: dial unix /var/run/docker.sock: connect: permission denied
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
Unable to run docker-compose
```

## Steps to reproduce the issue

1. Install docker-compose using Linux instructions from docs: https://docs.docker.com/compose/install/
2. Try to run it
3. CRASH

### Observed result
The software crashes when trying to run it.

### Expected result
The software would run successfully.

### Stacktrace / full error message

```
/usr/local/bin/docker-compose: line 1: Not: command not found
```

## Additional information
Running OS: Ubuntu Server 20.04 LTS

**Comment by CorruptComputer** [comment]
Also before someone says "it says the command isn't found, you need to download and install the binary" that error is from RUNNING the file.  This is the output if the file doesn't exist:
```
user@hostname:~$ sudo rm /usr/local/bin/docker-compose 
user@hostname:~$ docker-compose

Command 'docker-compose' not found, but can be installed with:

sudo apt install docker-compose
```

**Comment by syntapy** [comment]
This is not a bug in docker-compose

Check your `PATH` variable and make sure `/usr/local/bin` is in there

`sudo echo $PATH`

If not, add it to /root/.bashrc or something

Also I've always had to use `sudo docker-compose` which probably makes sense if you need sudo permissions to access docker itself

**Comment by CorruptComputer** [comment]
I KNEW someone would say that, which is why I made the above comment. It is finding the downloaded file, **the error is with running it, not with not finding it**. Please read what I previously said.

**Comment by syntapy** [comment]
Hahaha! My bad

Yeah I misread that 

Right, it says `line 1: Not: Command not found` so its happening in the code

What OS and architecture are you on? On my machine it works on a fresh debian VM without docker. 

Its not [this issue](https://stackoverflow.com/questions/58747879/docker-compose-usr-local-bin-docker-compose-line-1-not-command-not-found)?

**Comment by CorruptComputer** [comment]
Ah, that does seem to be the same issue. Let me try the steps in the answer to see if that fixes it.

Thanks!

**Comment by CorruptComputer** [comment]
The OS is Ubuntu Server 20.04 and architecture is ARM64.

**Comment by syntapy** [comment]
Yeah, unfortunately doesnt seem like they post binaries for arm.

I have no idea how hard it would be to compile for source, but seems like they do [support at least arm32](https://github.com/ubiquiti/docker-compose-aarch64), although someone [had trouble](https://github.com/docker/compose/issues/6879) doing so

I did find [this](https://github.com/ubiquiti/docker-compose-aarch64). Its kind of old though

Also, may I suggest you change the title to "Please support ARM64 binary downloads" or something?

**Comment by CorruptComputer** [comment]
Changed the name, thanks! I had no idea it wasn't supported since there wasn't a note for compatibility on the documentation.

**Comment by el-vishal** [comment]
Same issue, I am trying to install it on my Raspberry Pi

**Comment by MaximeAubanel** [comment]
Hey guys, same issue here. If you want to make sure it's the same issue just run `cat /usr/local/bin/docker-compose` you must see "Not Found".

@CorruptComputer Did you solve this issue ?

**Comment by chenxushuo** [comment]
I installed docker-compose on centos7-arm64,
CMD
```
sudo yum install -y libffi libffi-devel openssl-devel python3 python3-pip python3-devel
sudo pip3 install docker-compose
``` 
If have some error,run it twice!

**Comment by justincormack** [comment]
Hi, yes we currently recommend the pip install method for Arm64. I will see if we can get arm64 binaries built as well.

**Comment by vdo** [comment]
> Hi, yes we currently recommend the pip install method for Arm64. I will see if we can get arm64 binaries built as well.

This would be great, as it takes long time to build with the pip install on some boards. We are currently maintaining a fork to get such binaries in https://github.com/dappnode/compose/releases/tag/1.25.5

**Comment by CorruptComputer** [comment]
@MaximeAubanel I did not, I ended up giving up on Docker and just installing the applications I was trying to run manually. Hopefully they support this someday, but for now its just not possible for me. Since one of the apps I use specifically says not to use the pip package for docker-compose, as it does not work.

**Comment by MaximeAubanel** [comment]
@CorruptComputer I made it works installing it with apt-get:

`sudo apt-get install docker-compose`

**Comment by rfay** [comment]
Note that `apt-get install docker-compose` may get a very, very old version of docker-compose. On all Ubuntu before 20.04 and all Debian even with Buster you get old versions. Debian Buster gets 1.21.0

The `sudo pip3 install docker-compose` technique  works on Debian Buster arm64 (Raspberry Pi OS 64-bit).

The pip technique isn't mentioned in https://docs.docker.com/compose/install/#install-compose-on-linux-systems and only way below the fold on that page, discussing "pre-release" versions.

**Comment by fanlix** [comment]
We know this can be done by pip.
but offering an Arm-Release by official will be very helpful.

**Comment by alshdavid** [comment]
I have tried the following commands to get `docker-compose` installed on Amazon's a.1 AMI instances using the Gravitron ARM 
```
sudo yum install \
  python3 python3-devel gcc \
   libffi-devel openssl-devel 

sudo pip3 install --user docker-compose
```

and it fails with:
![image](https://user-images.githubusercontent.com/12656294/102973026-2b3c3b80-4550-11eb-8aad-f5a51022bc78.png)

**Comment by pda** [comment]
This is even more important now that `cryptography`, a transitive dependency of `docker-compose` via `paramiko`, [requires a rust toolchain to compile as of v3.4](https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#34---2021-02-07). It's becoming very difficult to install docker-compose onto arm64 machines.

**Comment by ajeetraina** [comment]
For anyone who want to get Docker Compose 1.28.2 up and running on ARM(Tested it on Jetson Nano), this might be useful:

```
#!/bin/bash
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install curl python3-pip libffi-dev python-openssl libssl-dev zlib1g-dev gcc g++ make -y
curl -sSL https://get.docker.com/ | sh
sudo snap install rustup --classic
sudo apt install rustc
sudo pip3 install docker-compose
sudo docker-compose --version
```

**Comment by Rar9** [comment]
@ajeetraina thanks for this

All seams ok in a vim3 with ubuntu 20.04

Only the sudo snap install rustup --classic line didnt work for me.
Anything to wory about as this is not really recommended https://snapcraft.io/install/rustup/ubuntu

**Comment by ulyssessouza** [comment]
This issue is meant to be solved by compose version 2 which is the Golang implementation available in https://github.com/docker/compose-cli for now.
In the release page you will find various ARM binaries.

**Comment by rfay** [comment]
I'm glad that compose-cli is going to mature and have a new golang implementation... but it's not going to be a safe drop-in replacement for docker-compose some time right? So ... We'd love to have arm binaries here. Not hard I don't think.

**Comment by ulyssessouza** [comment]
The problem of having `docker-compose` binaries is that `pyinstaller` doesn't support that for now.

About `compose-cli` (AKA v2), the idea is definitely to have it as a drop-in. Early adopters would help a lot in this process.
The more we have a people using the more we can identify differences and work on it to evolve.

For now, we are maintaining a documentation page with the compatibility matrix. At least in the UX https://docs.docker.com/compose/cli-command-compatibility/

**Comment by rfay** [comment]
Unfortunately it will be a couple of years before ddev can easily start using `docker compose` over docker-compose  since it's spread out across so many different platforms with different availability of docker versions, etc.

**Comment by ndeloof** [comment]
we also provide a translation tool so that scripts/tools relying on docker-compose will be able to transparently use `docker compose` - and `ddev` has been tested for this

**Comment by rfay** [comment]
Thanks @ndeloof - could you say more about "translation tool", maybe a link? I understand that docker-compose is being retired, but I'm not understanding what you're saying. 

As noted above, I've had success with `sudo pip3 install docker-compose` on arm64 platforms as well.

**Comment by vdo** [comment]
whether pip based installations work or not, I think it would be highly convenient to have an ARM(64) binary, non dependent on all the python packages. That's what this issue was all about!

**Comment by ndeloof** [comment]
@rfay this is not public yet, but bundled in latest Docker Desktop - we will make this open-source soon
We made a tiny wrapper tool to translate a `docker-compose ...` command into `docker compose ...` including re-ordering flags as required. This allows to adopt Compose v2 without impact on existing tools/script relying on `docker-compose`.

@vdo Compose v2 is a Go project, so we can build static ARM binaries without any runtime dependencies

**Comment by vdo** [comment]
> @vdo Compose v2 is a Go project, so we can build static ARM binaries without any runtime dependencies

Nice, I missed that part. I will give it a try.

**Comment by TimHeckel** [comment]
@alshdavid 
> I'm not very good with permissions, so if someone can adjust these steps so they work without `sudo` or being root.

I was able run the last command without sudo: `/usr/local/bin/pip install --user docker-compose`

And it put docker-compose inside `/home/ec2-user/.local/bin`

When I restarted my ssh, `docker-compose` works for ec2-user without sudo.

**Comment by enthusiasticgeek** [comment]
My set of commands look like 

`sudo apt remove docker-compose -y
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install curl python3-pip libffi-dev python-openssl libssl-dev zlib1g-dev gcc g++ make -y
sudo snap install rustup --classic
sudo apt install rustc
sudo pip3 install setuptools_rust
sudo pip3 install docker-compose
sudo docker-compose --version`

**Comment by MrWormHole** [comment]
@sshmaxime I can confirm this issue still exists and no warning on the docker-compose page whatsoever. arm64 users should be warned on this page https://docs.docker.com/compose/install/

Thank you tho, it helped me without pip3/pip which is a horrible package manager by far
