### ISSUE TITLE
[compose-in-a-container] Setup volume mounts based on -f, --file argument for compose in a container.

### ISSUE THREAD

**Issue by EricsonMacedo** [docker/compose#7489]
When running docker-compose through compose in a container values given to -f, --file argument aren't evaluated, as such, sharing volumes in this situation doesn't work.

Evaluate values given to -f, --file argument when running compose in a container and setup volume mounts in order to make sharing volumes to work as expected in this situation.

**Comment by FlyingOnion** [comment]
I'm having similar question when I use drone (docker runner) to build CI/CD pipelines. How do I update the cluster (not a real one but I know no more other words) using compose in a container?

**Comment by EricsonMacedo** [comment]
> I'm having similar question when I use drone (docker runner) to build CI/CD pipelines. How do I update the cluster (not a real one but I know no more other words) using compose in a container?

@FlyingOnion, sorry for no previous reply.
After #7490 was merged, you can use `run.sh -f <value>`, `run.sh --file <value>` or `docker-compose -f <value>` or `docker-compose --file <value>` depending on how you "installed" and named `run.sh`

**Comment by EricsonMacedo** [comment]
Merged in #7490
