### ISSUE TITLE
Allow using wildcards in Docker-Compose network > aliases

### ISSUE THREAD

**Issue by KevinGhadyani-minted** [docker/compose#7493]
**Is your feature request related to a problem? Please describe.**
When setting up a Proxy service in Docker-Compose, I need to always define hostnames both in my hosts file and in `networks > [NETWORK_NAME] > aliases`.

For instance:
- `frontend.myapp.localhost`
- `api.myapp.localhost`

I would like both domains to point at the proxy at whichever port I defined. This way, I can have multiple services running on the same port.

If my host machine targets `frontend.myapp.localhost` or `api.myapp.localhost`, because I have those domains setup in my hosts file, everything works fine.

The problem occurs when everything is behind the proxy. For instance, I'm doing server-side rendering and `frontend.myapp.localhost` now tries to call out to `api.myapp.localhost` before sending me some HTML. All of a sudden, I need to be using the docker-compose container name of `api` instead.

The way I fix this is by assigning aliases on the docker-compose `proxy` app network:
```yml
services:
  proxy:
    networks:
      proxy:
        aliases:
          - api.myapp.localhost
          - frontend.myapp.localhost
```

**Describe the solution you'd like**
1. It'd be a lot easier for me to do `*.myapp.localhost` instead of having to define each and every one.
2. If my proxy application could look into the directories of other apps, pull in their proxy configs, and create an alias file for docker-compose which generates the `aliases` property.

Either solution fits my needs, but #1 is far easier to implement. A combination of the two would be ideal because then anyone could use this proxy image and only need to ensure they're passing in a list of directories to check for configs.

**Describe alternatives you've considered**
Right now, I'm manually putting in every alias, but because my proxy app needs to be an independent repository, I have to manually add every possible alias by hand. In my case, that's 70+ applications to manage. If they change their URL, that's time I have to spend updating these local aliases.

Good luck to any dev that has to bisect older code in a different repo. It won't work if they changed the URL alias passed into the proxy.

**Comment by sbleon** [comment]
Our app would also really benefit from the wildcard solution you described as option 1.

**Comment by codestub** [comment]
anyone aware of a workaround for this?

**Comment by KevinGhadyani-minted** [comment]
The way I'm doing it right now is manually putting each app's URL in there.

**Comment by NAR8789** [comment]
Workaround: set up a dnsmasq container for hosting the wildcard entries, then point other containers' dns at that container.

Caveats:
- The dnsmasq container needs a static IP, to make it easy to point other containers' dns at it.
- Whatever service you're assigning wildcard names to probably also wants a static IP, to make the dnsmasq config easy to write.
- In order to avoid IP conflicts, you probably want to manually set your docker-compose network's `subnet` and `ip_range`, so that you can guaranteeably assign non-conflicting static IPs.
- You'll need to use composefile v2, because `ip_range` is only supported in composefile v2. As far as I know though, the only reason to use composefile v3 is if you want to use swarm mode. Maybe there's a more elegant way to use static ips that I'm missing, that doesn't require the `ip_range` config for safety?

Example config: https://gist.github.com/NAR8789/92da076d0c35b434107fb4f4f198fd12

**Comment by boomshadow** [comment]
Bump! (I didn't want this issue to get auto-closed). This feature would be extremely helpful due to the fact that our dockerized app requires knowing the domain, _and_ it uses sub-domain based multi-tenant routing. Our work around was to put all the common URL's in the network aliases. It works but its not ideal because we have many dozens of subdomains we'd like to actually include.

Example of what we have:
```yml
networks:
  my_network:
    aliases:
      - demo.local.ourdomain.com
      - foo.local.ourdomain.com
      - bar.local.ourdomain.com
      - buzz.local.ourdomain.com
```

**Comment by microerror** [comment]
> Bump! (I didn't want this issue to get auto-closed). This feature would be extremely helpful due to the fact that our dockerized app requires knowing the domain, _and_ it uses sub-domain based multi-tenant routing. Our work around was to put all the common URL's in the network aliases. It works but its not ideal because we have many dozens of subdomains we'd like to actually include.
> 
> Example of what we have:
> 
> ```yaml
> networks:
>   my_network:
>     aliases:
>       - demo.local.ourdomain.com
>       - foo.local.ourdomain.com
>       - bar.local.ourdomain.com
>       - buzz.local.ourdomain.com
> ```

The solution posted with `dnsmasq` works

If you follow the steps posted by @NAR8789 then all you need to do is add the `dns: ip-of-container-running-dnsmasq`  in docker-compose.yml 

I use `*.localhost` tld for local development. Any container that needs to `curl` or `ping` anything that ends with `.localhost` correctly resolves the IP of `nginx` container which in turn correctly routes the request to http-processing container(s).

**Comment by boomshadow** [comment]
The `dnsmasq` solution is a good work-around. I'm thankful for the information as I was able to use it. As its written, it only supports docker compose v2. With a tiny modification, it can work for v3, which is a requirement for my use case.

https://gist.github.com/NAR8789/92da076d0c35b434107fb4f4f198fd12?permalink_comment_id=4137904#gistcomment-4137904

It would still be great of compose natively supported wildcard aliases though. It would alleviate this extra complexity in the compose.

**Comment by MFAshby** [comment]
I think it's not docker-compose's but rather docker (or libnetwork). You can't achieve this kind of wildcard alias with plain docker CLI either.

Opened https://github.com/moby/moby/issues/43442 about this same problem.

**Comment by nphmuller** [comment]
Commenting to make sure the issue won't be closed.

**Comment by nphmuller** [comment]
:(

**Comment by outdooracorn** [comment]
Please reopen this issue. It's still a requested feature and isn't stale.

Pinging @Docker staff for visibility @glours @nicksieger @ndeloof @StefanScherer @ulyssessouza @laurazard

**Comment by pawmaster** [comment]
I need this feature too. However, I think it must be a feature of docker internal dns not docker compose. https://github.com/moby/moby/pull/43444

**Comment by ndeloof** [comment]
Compose just passes the `aliases` configuration to engine, and Compose can't offer something that the docker engine doesn't support.
Until https://github.com/moby/moby/issues/43442 we won't be able to provide this feature, and if/once fixed this will be available to compose users without any extra effort.

**Comment by ndeloof** [comment]
Closing this issue as "not planned". Obviously, if https://github.com/moby/moby/issues/43442 get eventually fixed, we would add support in docker compose to support this usage.
