### ISSUE TITLE
docker-compose down only partially brings down stack and then stalls

### ISSUE THREAD

**Issue by asampal** [docker/compose#7500]
After around docker-desktop 2.0.0.3 (Windows) or so, when I try to bring down a stack (with "docker-compose down") of 12 services started up with docker-compose, some of the containers stop, but most don't (e.g. out of 12 services only 3 are stopped) . Docker-Desktop seems to be hanging and the only thing I can do is restart it.
I usually start the services defined in docker-compose.yml individually or in smaller groups, with "docker-compose up -d <service>"

  - [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 5A90F905-5564-495B-BA91-1E55BFD40961/20200603153640

### Expected behavior
Expect complete stack of running services to stop

### Actual behavior
Docker-desktop brings down a few services only then seems to hang

### Information
This problem happens every time I try to bring down a larger number of services defined in my docker-compose.yml. 
The problem started happening after version 2.0.0.3 of Docker-for-Windows/Docker-Desktop.

  - Windows Version: Windows 10 Pro Version	10.0.19041 Build 19041
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by ulyssessouza** [comment]
Hello @asampal 
Could you please, provide the output of the following commands:
```
$ docker version
```
```
$ docker-compose version
```
```
$ docker-compose config
```

**Comment by asampal** [comment]
As I mentioned, the complete stack defined in docker-compose.yml is quite big, but the problem manifests itself even with a small subset of services running. I've anonymized the YAML file for inclusion here.

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

[docker_config_output.txt](https://github.com/docker/compose/files/4748279/docker_config_output.txt)

**Comment by asampal** [comment]
I've noticed that the same three services seem to stall and now I'm not sure how to go about determining the cause.

**Comment by ndeloof** [comment]
I'm closing this issue as obsolete: Docker Compose V1 has reached end-of-life and we are not accepting any more changes. Please try and reproduce your issue with Compose V2 and create a new issue or PR with the relevant Compose V2 information.
