### ISSUE TITLE
Please add "docker-compose config --images" to list the images in the docker-compose.yml file.

### ISSUE THREAD

**Issue by JesseChisholm** [docker/compose#7517]
**Is your feature request related to a problem? Please describe.**
I want to be able to list the images from the docker-comose.yml file.

**Describe the solution you'd like**
I would like to be able to say:
``` docker-compose config --images ```
Similarly to how I can say:
``` docker-compose config --services ```
to get a list of the container by name.

**Describe alternatives you've considered**
I have tested a modification of the docker-compose-backup script
> https://gist.github.com/pirate/265e19a8a768a48cf12834ec87fb0eed
But this only lists images if your containers are running.
I have also tested various bash scripts that scan the file and extract this list. But they are fragile.

**Additional context**
My goal is to be able to include this list in a report.  I do not need to know whether the images are correct or pull-able or in my local cache.

**Comment by ndeloof** [comment]
`docker-compose images` already support this use-case
(admittedly compose UX is a bit heterogeneous)

**Comment by JesseChisholm** [comment]
`docker-compose images` only lists the images if my containers are running.

I wish to list the images that **would be requested** if I did a `docker-compose build`.

**Comment by docktermj** [comment]
Yes, this would be helpful for a project I'm working on.

**Comment by ndeloof** [comment]
> I wish to list the images that would be requested if I did a docker-compose build
Listing configured images would be easy, but what you are asking for require we also parse the (possibly multi-stage) `Dockerfile`, which might require on extended builkit syntax we can't read

**Comment by JesseChisholm** [comment]
I had not envisioned chasing the `build` entry, just listing the `image` entries.

But I see your point. What if a service entry has no image entry, only a build entry?

Does the `build` entry normally give a name and tag to the built image, even if you don't specify an `image` entry?

I think for my request's needs, it would be sufficient for a build entry, without an image entry, to list as if the image were called 
`build:folder/file` for whatever it was told to build from. (or something like that)

I don't see any need to parse each docker file's internals to satisfy my enhancement request. Just as I don't see any need to list the images an image depends on to satisfy my request.

I'm just asking a question about this `docker-compose.yml` file, not about the total end product of running it.

Now, if you added an option `--recursive` or `--depth 100` or some such, then I see it needing to look at incidental images pulled to build a dockerfile.

But if you assume `--no-recursive` or `--depth 1` then there is no need to chase any deeper than the docker-compose file itself.

I personally have no need for the recursive concept of a `docker-compose config images` command.

-Jesse

**Comment by ndeloof** [comment]
compose indeed give a name to services without an `image` attribute (`<project_service>`)

`docker-compose config --images` would make perfect sense, listing `image` attributes set by services.

**Comment by JesseChisholm** [comment]
The PR I linked up at the top, is my attempt to follow standard coding style and implement this feature.
I tested this in my environment on my docker-compose.yml file.
I have not tested it on more general docker-compose.yml files.
And I likely didn't get the auto-named-images from the `build` entries at all, as I never thought of that use case.

**Comment by ndeloof** [comment]
@JesseChisholm better submit a PR on the `v2` branch, which will replace docker-compose V1 in near future

**Comment by JesseChisholm** [comment]
OK. I'll work on that.

**Comment by docktermj** [comment]
Please re-open.
