### ISSUE TITLE
ERROR: Duplicate mount points: [.:.:rw, .:.:rw, .:.:rw, .:.:rw, .:.:rw, .:.:rw, .:.:rw, .:.:rw, .:.:rw, .:.:rw]

### ISSUE THREAD

**Issue by rameshar16** [docker/compose#7536]
## Description of the issue
docker-compose not reading the customer env file name.
## Context information (for bug reports)
docker-compose not reading the customer env file name.
**Output of `docker-compose version`**
```
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
WARNING: The XXXX variable is not set. Defaulting to a blank string.
WARNING: The XXXX variable is not set. Defaulting to a blank string.
ERROR: Duplicate mount points: [.:.:rw, .:.:rw]
```
## Steps to reproduce the issue

1. Create a Docker-compose file
2. Pass the env vairisble,via "env_file"
   env_file:
      - .env_dev
3.

### Observed result
WARNING: The XXXX variable is not set. Defaulting to a blank string.
WARNING: The XXXX variable is not set. Defaulting to a blank string.
ERROR: Duplicate mount points: [.:.:rw, .:.:rw]
### Expected result
dockr-compose config command should run without issues
### Stacktrace / full error message

```
WARNING: The XXXX variable is not set. Defaulting to a blank string.
WARNING: The XXXX variable is not set. Defaulting to a blank string.
ERROR: Duplicate mount points: [.:.:rw, .:.:rw]
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by thaJeztah** [comment]
The `env_file` option is used to pass environment-variables to the container, but is not used to expand variables in the compose-file itself. For those, you need to either set those environment variables in your current environment (`export ...`), or us a `.env` file.

**Comment by rameshar16** [comment]
Thank you @thaJeztah for your quick response.

I have exported the env file, but I am still getting the same issue.

**export env_file=.env_file**

Please let me know if I missed anything here.
Thanks and Regards,
Ramesh AR

**Comment by thaJeztah** [comment]
You need to export the environment variables that are declared in the `env_file`. Docker Compose also supports a `.env` file (in the same directory as the compose-file) which will be read when running docker-compose commands. https://docs.docker.com/compose/env-file/
