### ISSUE TITLE
ADD layer computes different hash everytime

### ISSUE THREAD

**Issue by pitrou** [docker/compose#7541]
## Description of the issue

My Dockerfile looks like this:
```
FROM quay.io/pypa/manylinux2010_x86_64:2020-03-07-1825e8f

RUN yum install -y xz bison ccache flex wget
RUN yum clean all

ADD scripts/install_cmake.sh /
RUN /install_cmake.sh
```

Everytime I build that file using docker-compose, the ADD layer gets a different hash:
```
$ docker-compose build centos-python-manylinux2010
Building centos-python-manylinux2010
Step 1/5 : FROM quay.io/pypa/manylinux2010_x86_64:2020-03-07-1825e8f
 ---> 715ccb8e8c49
Step 2/5 : RUN yum install -y xz bison ccache flex wget
 ---> Using cache
 ---> b376fecde6bd
Step 3/5 : RUN yum clean all
 ---> Using cache
 ---> 6c2151cfaccb
Step 4/5 : ADD scripts/install_cmake.sh /
 ---> 7d11a6278fb1
Step 5/5 : RUN /install_cmake.sh
 ---> Running in b6a6ae2da96c
[...]
```

```
$ docker-compose build centos-python-manylinux2010
Building centos-python-manylinux2010
Step 1/5 : FROM quay.io/pypa/manylinux2010_x86_64:2020-03-07-1825e8f
 ---> 715ccb8e8c49
Step 2/5 : RUN yum install -y xz bison ccache flex wget
 ---> Using cache
 ---> b376fecde6bd
Step 3/5 : RUN yum clean all
 ---> Using cache
 ---> 6c2151cfaccb
Step 4/5 : ADD scripts/install_cmake.sh /
 ---> bf264a5b6fa1
Step 5/5 : RUN /install_cmake.sh
 ---> Running in 554cad6a2d57
[...]
```

Even though the ADDed file didn't change at all:
```
$ LANG=C stat manylinux201x/scripts/install_cmake.sh 
  File: manylinux201x/scripts/install_cmake.sh
  Size: 1050      	Blocks: 8          IO Block: 4096   regular file
Device: 802h/2050d	Inode: 27134784    Links: 1
Access: (0775/-rwxrwxr-x)  Uid: ( 1000/ antoine)   Gid: ( 1000/ antoine)
Access: 2020-06-17 15:36:47.731644861 +0200
Modify: 2020-01-28 17:04:20.152467051 +0100
Change: 2020-01-28 17:04:20.152467051 +0100
 Birth: -
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.0, build unknown
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 nvidia:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Output of `docker-compose config`**
https://gist.github.com/pitrou/7b605b802155bf44bc983bf48bcaa2c8

## Additional information

On Ubuntu 18.04, with docker-compose installed inside a conda environment (shouldn't matter).

**Comment by pitrou** [comment]
It seems that part of the problem is an in-between call to `docker-compose pull --ignore-pull-failures`. Even though the image is up-to-date, it seems to wreck subsequent computation of layer hashes (why??).

**Comment by thaJeztah** [comment]
Are you seeing the same problem if you use the cli and buildkit to perform the build? You can enable that feature using the `COMPOSE_DOCKER_CLI_BUILD=1` and `DOCKER_BUILDKIT=1` environment variables;


```bash
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build centos-python-manylinux2010
```

I _do_ notice you are probably running a version of docker that was built and packaged by Ubuntu. Not sure if related, but we've seen issues with this packages, and docker behave different than the official packages (https://docs.docker.com/engine/install/ubuntu/)

**Comment by pitrou** [comment]
@thaJeztah Thanks for the suggestion. Things seem to work better with those environment variables. Are there any pitfalls? Can I enable them on my development machine without any worries?

**Comment by thaJeztah** [comment]
They should be fine to use, but some obscure/advanced build options may not (yet) be available.

the BuildKit options itself is definitely ok to use as your default builder
