### ISSUE TITLE
RUN sudo passwd alice  without key any word

### ISSUE THREAD

**Issue by alicera** [docker/compose#7544]
Please post on our forums: https://forums.docker.com for questions about using `docker-compose`.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker.

in the dokerfile 
RUN sudo passwd alice

it will happen
"""
Enter new UNIX password: Retype new UNIX password: passwd: Authentication token manipulation error
passwd: password unchanged
"""

how can I set the passwd  in the dockerfile

**Comment by GenaANTG** [comment]
You no need to using **sudo** in your container. You can set **USER** directive instead.

**Comment by alicera** [comment]
I want to enter the container with user alice, so I dont have the root.

**Comment by alicera** [comment]
solved?

**Comment by alicera** [comment]
why

**Comment by alicera** [comment]
Hi @stale
