### ISSUE TITLE
COMPOSE_FILE and -f flags do not compose

### ISSUE THREAD

**Issue by myitcv** [docker/compose#7546]
## Description of the issue

I expected the use of `COMPOSE_FILE` and the `-f` flag to compose.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:23 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:55 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**

n/a - see below for repro steps

## Steps to reproduce the issue

Create the following two files:

```
# docker-compose-1.yml
services:
  service1:
    image: busybox:1.31.1-musl
version: '3.2'
```

```
# docker-compose-2.yml
services:
  service2:
    image: busybox:1.31.1-musl
version: '3.2'
```

Then run:

```
COMPOSE_FILE=docker-compose-1.yml docker-compose config
```

The output should be:

```
services:
  service1:
    image: busybox:1.31.1-musl
version: '3.2'
```

If you then run:

```
COMPOSE_FILE=docker-compose-1.yml docker-compose -f docker-compose-2.yml config
```

the output is:

```
services:
  service2:
    image: busybox:1.31.1-musl
version: '3.2'
```

Much like the [`GOFLAGS`](https://golang.org/cmd/go/#hdr-Environment_variables) environment variable, I expected `COMPOSE_FILE` to be additive with respect to the `-f` flag. i.e. I expected:

```
COMPOSE_FILE=docker-compose-1.yml docker-compose -f docker-compose-2.yml config
```

to be equivalent to:

```
COMPOSE_FILE=docker-compose-1.yml:docker-compose-2.yml docker-compose config
```

or:

```
docker-compose -f docker-compose-1.yml -f docker-compose-2.yml config
```

### Observed result

As above.

### Expected result

As above.

### Stacktrace / full error message

n/a

## Additional information

```
Ubuntu 20.04 LTS
```

Installed via https://docs.docker.com/compose/install/#install-compose-on-linux-systems

**Comment by myitcv** [comment]
There is, I think, a further (documentation) issue. The `-f`/`--file` flag is documented as follows:

```
  -f, --file FILE             Specify an alternate compose file
                              (default: docker-compose.yml)
```

In the case of the command:

```
COMPOSE_FILE=docker-compose-1.yml docker-compose config
``` 

no `-f` flag is provided, hence the config file consulted should (according to the flag documentation) be `docker-compose.yml`.

**Comment by GenaANTG** [comment]
> This variable supports multiple Compose files separated by a path separator (on Linux and macOS the path separator is :, on Windows it is ;). For example: COMPOSE_FILE=docker-compose.yml:docker-compose.prod.yml. The path separator can also be customized using COMPOSE_PATH_SEPARATOR

Should be: COMPOSE_FILE=docker-compose-1.yml;docker-compose-2.yml

**Comment by myitcv** [comment]
Setting `COMPOSE_FILE` instead of using the `-f` flag is indeed one option to allow this sort of composition:

```
COMPOSE_FILE=docker-compose-1.yml:$COMPOSE_FILE docker-compose config
```

It's just that as demonstrated above, there is already _some_ composition between `COMPOSE_FILE` and `-f`, and I'm proposing that be made complete and explicit.

**Comment by GenaANTG** [comment]
I think we no need this feature. You can simple use `-f` flag or environment variables. 2 ways at least.
Keep it simple. Guys should work on most important things, they have a lot of things to do.

**Comment by myitcv** [comment]
> I think that we no need this feature

Thanks

I think we should focus on whether the use case I'm advocating/using is valid or not:

* I'm using this approach to compose the `docker-compose.yml` files from multiple projects
* Let' assume I'm working on project1, which uses project2 and project3. All projects have `docker-compose.yml`. The composition of `project1/docker-compose.yml`, `project2/docker-compose.yml` and `project3/docker-compose.yml`represents the Docker setup we need for project1
* I set the `COMPOSE_FILE` environment variable to be the array of `/path/to/project1/docker-compose.yml:/path/to/project2/docker-compose.yml:/path/to/project3/docker-compose.yml`
* This way, any `docker-compose` commands see the unified, composed setup
* If I then run a setup script from project3 in the context of project1, it uses a `-f` flag to compose an additional, setup-only service. Running `docker-compose -f project3/setup.yml` therefore needs to compose with the `COMPOSE_FILE` value in order for the result to be complete

For my own purposes, I've [created a wrapper around `docker-compose`](https://github.com/myitcv/docker-compose) to address this issue and #3874. i.e. it composes `COMPOSE_FILE` and `-f` flags, as well as resolving relative directory paths relative to the compose file's containing directory
