### ISSUE TITLE
Nginx container doesn’t copy files to my host

### ISSUE THREAD

**Issue by leandrosk2** [docker/compose#7547]
I am trying to copy a set of files (etc/nginx/*) from Nginx container to myhost (./nginx) but don't work.
Every time I run my docker-compose, the folder on the host (/ usr / development / nginx) is empty. How can I do this?

**Environment**
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"`

**Docker Compose**
`docker-compose version 1.25.5, build 8a1c60f6`

**Docker**
`Docker version 19.03.6, build 369ce74a3c`

**My docker-compose.yml**
`version: '3.7'

    services:
      nginx:
        container_name: 'nginx'
        hostname: nginx
        image: nginx
        ports:
          - "80:80"
          - "443:443"
        restart: unless-stopped
        command: /bin/sh -c "while :; do sleep 6h & wait ${!}; nginx -s reload; done & nginx -g 'daemon off;'"
        volumes:
          - ./nginx:/etc/nginx
          - ./certbot/conf:/etc/letsencrypt
          - ./certbot/www:/var/www/certbot
        networks:
          - docker-network
      portainer:
        image: portainer/portainer
        container_name: portainer
        hostname: portainer
        ports:
         - 9000:9000
        volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - ./portainer/data:/data
        networks:
          - docker-network

      certbot:
        container_name: 'certbot'
        hostname: certbot
        image: certbot/certbot
        volumes:
          - ./certbot/conf:/etc/letsencrypt
          - ./certbot/www:/var/www/certbot
        restart: unless-stopped
        entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait ${!}; done;"
        depends_on:
          - nginx
        networks:
          - docker-network
    networks:
      docker-network:
        name: docker-network
        driver: bridge`

**Comment by GenaANTG** [comment]
You should copy your files in a Dockerfile, if you want build an image to delivery for: AWS, 
Docker Hub, etc. Here you are using binding for your volumes:
```
volumes:
      - ./nginx:/etc/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
```
When you build your images then you have no files in your builded images, because you haven't copied them. For copying them, you need to add your own Dockerfile for building nginx service and you should add a context to building.

**You need to create some files for building and running images!**
Look at my docker-compose-staging.yaml for nginx image building:

**./docker-compose-staging.yaml**
```
nginx:
    build: 
      context: ./  <-- [Relative path from your docker-compose.yaml]
      dockerfile: ./docker/configs/staging/nginx/Dockerfile <-- [Directory with a Dockerfile to build image]
    image: company/company_nginx:staging
    container_name: "company_nginx"
```
**./docker/configs/staging/nginx/Dockerfile**
```
FROM nginx:stable-alpine

WORKDIR /project

RUN apk update && apk upgrade

COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx /etc/nginx  <-- [Here is your copying instruction to image]

EXPOSE 80 443
STOPSIGNAL SIGTERM
CMD ["nginx", "-g", "daemon off;"]  <-- [You can use this command instead of /bin/sh -c "while :; do sleep 6h...'" in you docker-compose.yaml]
```

**Comment by leandrosk2** [comment]
@GenaANTG  Thanks!! Got it!!
