### ISSUE TITLE
Your kernel or machine may not be supported

### ISSUE THREAD

**Issue by gvasquez95** [docker/compose#7562]
Seems like docker-compose does not support the newest [AWS Graviton2](https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-ec2-m6g-instances-powered-by-aws-graviton2-processors-generally-available/?nc1=h_ls) processor as trying to run it on an [r6g.xlarge](https://aws.amazon.com/ec2/instance-types/r6/) AWS [EC2](https://aws.amazon.com/ec2/) instance yields the following message: `Your kernel or machine may not be supported.`

Not sure what else should I provide for this feature request, but support for this new hardware is desired.

cc: @milo-ft

**Comment by gvasquez95** [comment]
Failure scenario:

Amazon Linux 2 LTS Arm64 AMI 2.0.20200520.1 arm64 HVM gp2
AMI: ami-02b5d851009884e20
Kernel: 4.14.177-139.254.amzn2.aarch64
Docker-compose: 1.26.0

**Comment by samip5** [comment]
Basically a duplicate of #6831, #7051, #7472 and #7370.

**Comment by moper248** [comment]
Hello,

just FYI.

i am able to compile successfully  docker-compose (compose-1.27.4) on `Graviton2 (4.14.209-160.339.amzn2.aarch64 #1 SMP Wed Dec 16 22:44:17 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux)` AWS server. 

```
yum install docker git python3 python3-pip python3-devel gcc libffi-devel  openssl11-devel
service docker start
chkconfig docker on
pip3 install wheel
wget https://github.com/docker/compose/archive/1.27.4.tar.gz  
tar xzvf 1.27.4.tar.gz 
cd compose-1.27.4/
python3 -m pip install -IU docker-compose
```
