### ISSUE TITLE
[1.26.1] AttributeError: 'Context' object has no attribute 'is_docker_host' with PyPI docker 4.2.1 

### ISSUE THREAD

**Issue by hartwork** [docker/compose#7576]
Hi!

docker-compose 1.26.1 (and Git `master`) use method `Context.is_docker_host` of PyPI docker at https://github.com/docker/compose/blob/15c1cabdadac535e9ed2fb2052b9a04dc08badb5/compose/cli/docker_client.py#L143 . That method was introduced in PyPI docker 4.2.2 but `setup.py` requires PyPI docker >=4.2.1 only (i.e. is too shy about it) at
https://github.com/docker/compose/blob/15c1cabdadac535e9ed2fb2052b9a04dc08badb5/setup.py#L36 . The fact that `requirements.txt` pulls in 4.2.2 at https://github.com/docker/compose/blob/15c1cabdadac535e9ed2fb2052b9a04dc08badb5/requirements.txt#L7 may have kept the shortcoming in `setup.py` in the shadows, I guess.

To reproduce easily:
```console
# cd "$(mktemp -d)"
# git clone --depth 1 https://github.com/docker/compose
# cd compose/
# virtualenv --python=python3.7 py37
# source py37/bin/activate
# pip install -r requirements.txt -r requirements-dev.txt 
# pip install docker==4.2.1  # downgrade to that of setup.py
# python -m pytest -v tests/unit/cli_test.py::CLITestCase::test_get_project
=============================================================== test session starts ===============================================================
platform linux -- Python 3.7.7, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /tmp/tmp.MvuXQMKm3u/compose/py37/bin/python
cachedir: .pytest_cache
rootdir: /tmp/tmp.MvuXQMKm3u/compose, inifile: tox.ini
plugins: cov-2.10.0
collected 1 item                                                                                                                                  

tests/unit/cli_test.py::CLITestCase::test_get_project FAILED                                                                                [100%]

==================================================================== FAILURES =====================================================================
__________________________________________________________ CLITestCase.test_get_project ___________________________________________________________
tests/unit/cli_test.py:79: in test_get_project
    project = get_project(base_dir)
compose/cli/command.py:137: in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
compose/cli/docker_client.py:43: in get_client
    environment=environment, tls_version=get_tls_version(environment)
compose/cli/docker_client.py:143: in docker_client
    if not context.is_docker_host():
E   AttributeError: 'Context' object has no attribute 'is_docker_host'
================================================================ 1 failed in 0.14s ================================================================
```

Should I provide a pull request putting `docker[ssh] >=4.2.2, <5` into `setup.py`?

Thanks and best, Sebastian

**Comment by pietrinoatzenimfm** [comment]
I confirm I have the same issue when trying to use a fresh install of docker-compose (in Gitlab CI)

**Comment by sunmilee** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/local/lib/python3.7/site-packages/compose/cli/main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.7/site-packages/compose/cli/command.py", line 76, in project_from_options
    environment_file=environment_file
  File "/usr/local/lib/python3.7/site-packages/compose/cli/command.py", line 142, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/usr/local/lib/python3.7/site-packages/compose/cli/docker_client.py", line 47, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/local/lib/python3.7/site-packages/compose/cli/docker_client.py", line 147, in docker_client
    if not context.is_docker_host():
AttributeError: 'Context' object has no attribute 'is_docker_host'

**docker-compose version 1.26.1, build 634eb50v**

**Comment by fti-pchincholikar** [comment]
**I am facing same issue in docker-compose 1.26.1, build 634eb50**
```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/command.py", line 76, in project_from_options
    environment_file=environment_file
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/command.py", line 142, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/docker_client.py", line 47, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/usr/local/lib/python3.7/dist-packages/compose/cli/docker_client.py", line 147, in docker_client
    if not context.is_docker_host():
AttributeError: 'Context' object has no attribute 'is_docker_host'
```

**Comment by ulyssessouza** [comment]
For a quick workaround you can run
```
$ pip install docker==4.2.2
```

That should install the last version of docker-py that has fix.
A new release with the permanent fix is coming ASAP

**Comment by thaJeztah** [comment]
PR with a fix (for master); https://github.com/docker/compose/pull/7579 (needs to be cherry-picked to the v1.26.x release branch once merged)
