### ISSUE TITLE
fig kill integration tests fail locally on master

### ISSUE THREAD

**Issue by dnephin** [docker/compose#759]
I'm seeing two test failures on master locally:

```
test_kill_interrupted_service (tests.integration.cli_test.CLITestCase)
test_kill_signal_sigint (tests.integration.cli_test.CLITestCase)
```

These were added recently #611 (9abdd337b5146643084205ad949c017b6ab843a4). For some reason they aren't failing in wercker.

I'm not sure how these tests pass. From what I can see the SIGINT should actually shutdown the container, but the tests expect the container to be running after a SIGINT.

Am I missing something?

**Comment by funkyfuture** [comment]
that's odd. i ran dozens of tests since this issue was opened. but just recently that behaviour happens on  one of three test environments. at first i thought it was caused by recent commits.

**Comment by dnephin** [comment]
Ya, I see them fail pretty inconsistently as well. One of my desktops never has the failure, the other one does pretty consistently on most branches.

**Comment by funkyfuture** [comment]
let me guess, they're all Ubuntus? (i discarded using boot2docker, so i can't test 'natively' on OS X)

**Comment by bfirsh** [comment]
It's a race condition... It works reliably locally, but fails reliably on a remote Docker host. Presumably this is because when there is low latency, `top` doesn't actually quit until after the check that the container is running.

**Comment by dnephin** [comment]
These tests are still failing when I run them locally.

**Comment by dnephin** [comment]
I'm not sure what's going on, but SIGSTOP is causing top to exit, not suspend, when I run the suite on my laptop.

**Comment by bfirsh** [comment]
Did this get fixed in the end?

**Comment by dnephin** [comment]
I'm still getting the same failures on one host

**Comment by dnephin** [comment]
Ok, I figured out what caused these to fail. I had set `-e lxc` in my `/etc/defaults/docker` a long time ago, and I guess I forgot about it. After removing that config the tests are passing again.
