### ISSUE TITLE
Disable interactivity of up command

### ISSUE THREAD

**Issue by tomers** [docker/compose#7591]
I use custom script which executes `docker-compose up`. In case some docker image in the `docker-compose.yml` is missing, the `yesno` method is called, prompting the user for action.

Since I execute the `docker-compose up` command in the context of a script, I would like to disable interactivity, and instead specify `--yes` or `--no`, or any other kind of solution, so the my script could overcome such case.

BTW in my case I run `subprocess.run(['docker-compose', '-f', 'docker-compose.yml', 'up', '-d'], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True).stdout`, and the script stalls forever, not prompting the user with anything...

```
foo.exceptions.CalledProcessError: Exec failed: rc=1 cmd=docker-compose -f docker-compose.yml up -d
stdout=
Continue with the new image? [yN]
stderr=
Pulling some.image.name (some/repo)...
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

pull access denied for some/repo, repository does not exist or may require 'docker login': denied: requested access to the resource is denied


```

- Docker compose version:
```
$ docker-compose -v
docker-compose version 1.8.1, build 878cff1
```

Relevant location in the code: https://github.com/docker/compose/blob/master/compose/cli/main.py#L1081

**Comment by Drowze** [comment]
Would like to reopen this as well. My GitHub Codespaces (which are configure to use devcontainers with docker-compose) are hanging during creation because of docker-compose interactivity 😢 (see https://github.com/microsoft/vscode-remote-release/issues/4677)

**Comment by oscarhermoso** [comment]
@tomers  Could you please re-open this ticket? I'm having the same trouble as @Drowze with docker-compose devcontainers

**Comment by kohtala** [comment]
@ps-george, @Drowze, @oscarhermoso, please tell which version you are using. docker-compose v1 is not accepting any new features anymore as can be seen in PR #7614.

Quickly tried docker compose up with v2.20.2 and it seems to be returning with exit code 18 instead of prompting user.

**Comment by angularsen** [comment]
Docker compose v2 allows enabling/disabling interactivity, which is enabled by default when installing Docker Desktop. 

To disable the interactive menu:
```
COMPOSE_MENU=0 docker compose up
```
```
docker compose up --menu=0
```

https://docs.docker.com/reference/cli/docker/compose/up/#options
