### ISSUE TITLE
Implement Docker isolation for multiple users

### ISSUE THREAD

**Issue by godomainz** [docker/compose#7593]
I’ve been asked to configure a ubuntu 18.04 server with docker for multiple users.

Purpose:
We have multiple testers who write test cases. But our laptops aren’t fast enough to build the project and run tescases in docker environment. But we need to build/test our code BEFORE push to git.

I’ve been given a high end ubuntu 18.04 server.
I have to configure the server where all our testers can run/debug our testcases on isolated environments.

When testers push there changes to remote servers project should build and run on isolated environments. Multiple users can work on same project but one testers builds must NOT affect another one.

I already installed Docker and tried with only changing docker-compose.yml and adding different networks (using multiple accounts of course). But it was very painful.

I need to have multiple selenoid servers(for different users),different allure reports with docker , Need the ability to build and run tests using our docker-compose files and need the ability to run the actual project on different ports so we can go through the system while writing test cases.

Is it possible to configure an environment without changing project docker-compose.yml ?
Whats the approach I should take ?

**Comment by nsbk** [comment]
I think you can achieve isolation in your scenario by using existing compose features:

You could rely on the `--project` command line argument to isolate running containers among users. By default, compose uses the parent directory name. See [docker-compose CLI](https://docs.docker.com/compose/reference/overview/)

Regarding serving different ports, you could use a _git ignored_ [env_file](https://docs.docker.com/compose/compose-file/#env_file) for each user and define there the `PORT` you want to expose for each user (internally it can remain the same)
