### ISSUE TITLE
Add memory-swap and memory-swappiness support to v3 since it was available in v2

### ISSUE THREAD

**Issue by jamshid** [docker/compose#7594]
**Is your feature request related to a problem? Please describe.**

You can configure `memswap_limit` and `mem_swappiness` in v2 compose files. 
Docs (https://docs.docker.com/compose/compose-file/#resources) claim v3 replaces these settings with `deploy: resources:`.
These docs are very misleading, these **swap settings simply cannot be configured in v3 format**.

**Describe the solution you'd like**
First, please make the current situation clear in the docs. These docs cause so much unnecessary confusion like:
https://forums.docker.com/t/memory-swap-vs-memory-swappiness-and-using-in-docker-compose/54889
https://stackoverflow.com/questions/44325949/how-to-replace-memswap-limit-in-docker-compose-3

If the answer as @shin- seemed to indicate is to keep using v2, then make it clear that v3 format is not needed and should not be used if you (very reasonably) want to configure swap settings for your services.

But really I'd like docker-compose to make the v3 format a complete replacement of v2, anything you could configure in v2  (or with `docker run`) should be available in v3. Also `--compatibility` should be default behavior. 

**Describe alternatives you've considered**
Switch back to v2 format? I'm not using docker swarm so I guess I could try but I'd like to deploy to k8s eventually.

**Additional context**
The problem I'm running into is that some services are using a lot of swap. I know I should probably disable swap on the host server but not always possible/easy.
This is mostly the same issue as https://github.com/docker/compose/issues/4513 but hopefully you will reconsider now that you're taking a fresh look at compose.

**Comment by arteeh** [comment]
I will never understand people adding the stale bot. Just because there's no replies, doesn't mean the problem has magically gone away.

**Comment by crowley666x** [comment]
This is important. Do it!

**Comment by glours** [comment]
@crowley666x 
Since Compose v2, you don't need to use the `version` anymore as the Compose Specification merged the 2 file formats (v2.x and v3.x). So you should be now able to define memory resource usages on the `deploy` section and the memory swapiness directly on the service.

**Comment by maxiwheat** [comment]
> @crowley666x Since Compose v2, you don't need to use the `version` anymore as the Compose Specification merged the 2 file formats (v2.x and v3.x). So you should be now able to define memory resource usages on the `deploy` section and the memory swapiness directly on the service.

I guess you are referering to this part in the doc : https://docs.docker.com/compose/compose-file/05-services/#mem_swappiness

I find it a little odd that the other resources options are under the `deploy` section, and that this one remains at the service level. Also, for `memswap_limit`, the doc says :

>  This is a modifier attribute that only has meaning if `memory` is also set

And it is not clear where this `memory` option comes from, maybe it should added that it's in the deploy section

I also think that [a note could be added in here](https://docs.docker.com/compose/compose-file/deploy/) to specify that swap options are not at the deploy level, but at the service level

**Comment by TheExDeus** [comment]
So memswap_limit isn't deprecated as the docs say because v2 and v3 was merged?
Would still be good if it was configurable in deploy section for consistency though.

**Comment by Aposhian** [comment]
Just noting that this is still confusing and underdocumented.

**Comment by Mart-Bogdan** [comment]
It doestn't work.

If I specify it under service level:
> ```
> Compose file contains unsupported options:
> 
> memswap_limit: Set resource limits using deploy.resources
> ```

And if I put it there:

> ```
>services.my_srv.deploy.resources.limits Additional property memswap is not allowed
>```

memswap_limit is not allowed as well.

also :  services.my_srv.deploy.resources Additional property memswap_limit is not allowed

**Comment by macedd** [comment]
Currently using the `memswap_limit` has no effect.
