### ISSUE TITLE
docker-compose .env variable substitution doesn't ignore single quotes

### ISSUE THREAD

**Issue by ImDevinC** [docker/compose#7601]
## Description of the issue

`env_file` is not loaded properly in docker-compose 1.26.2

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build unknown
docker-py version: 4.2.2
CPython version: 3.8.3
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client:
 Version:           19.03.12-ce
 API version:       1.40
 Go version:        go1.14.4
 Git commit:        48a66213fe
 Built:             Wed Jul  1 17:05:50 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.12-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.4
  Git commit:       48a66213fe
  Built:            Wed Jul  1 17:05:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.4.m
  GitCommit:        d76c121f76a5fc8a462dc64594aea72fe18e1178.m
 runc:
  Version:          1.0.0-rc91
  GitCommit:        24a3cf88a7ae5f4995f6750654c0e2ca61ef4bb2
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  web:
    command: echo Sample values
    environment:
      ANOTHER_TEST: ''
      TEST: Sample values
    image: bash
version: '3.0'
```

## Steps to reproduce the issue

1. Create .env file with following values:
```
TEST=Sample values
ANOTHER_TEST='${ANOTHER_TEST}'
```
2. Pass `env_file: .env` to `docker-compose.yml`
3. Run `docker-compose config`

### Observed result
Value of `ANOTHER_TEST` is equal to `''`

### Expected result
Value of `ANOTHER_TEST` should be equal to `'''$${ANOTHER_TEST}'''`

## Additional information

`lsb_release -a`
```
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

Issue is not present in 1.25.x and older versions of docker-compose.

Changing `'${ANOTHER_TEST}` to `$ANOTHER_TEST` results in `docker-compose config` outputting `$$ANOTHER_TEST` so that seems to work, but the original implementation looks to be broken.

**Comment by ImDevinC** [comment]
Is there any other information I need to provide for this?

**Comment by Ovyerus** [comment]
This is still a problem in 2023 and I am experiencing it on compose 2.16.0
