### ISSUE TITLE
Cannot kill container

### ISSUE THREAD

**Issue by fkromer** [docker/compose#7625]
## Description of the issue

If I stop running containers which have been started with `docker-compose up` I'm getting this error for every container which is run as part of the compose file:

```
ERROR: for c_redis  Cannot kill container: b64a037ab2836a0fbdab2bba1fd93d0d4a05817ee3f2c3b439aac3c3fd0922d5: Cannot kill container b64a037ab2836a0fbdab2bba1fd93d0d4a05817ee3f2c3b439aac3c3fd0922d5: unknown error after kill: runc did not terminate sucessfully: container_linux.go:392: signaling init process caused "permission denied"
: unknown
```

**I've disabled AppArmor temporarily with `sudo aa-teardown` and the bug is gone.** I've changed something w.r.t. the docker network recently. Unfortunately I cannot remember what exactly. Before the change I had no issues.

EDIT: After re-enabling AppArmor again with `sudo aa-enabled` the issue is gone as well. Seems like AppArmor had to be restarted due to some reason. The bug was not reproducible after the first occurrence.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build 8a1c60f6
```

**Output of `docker version`**
```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.12
  Git commit:       77e06fd
  Built:            Mon Jun  8 20:24:59 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
PRIVATE
```

## Steps to reproduce the issue

?

### Observed result

Refer to description of the issue.

### Expected result

The containers are stopped as usual.

### Stacktrace / full error message

```
N.A.
```

## Additional information

Ubuntu 20.04 LTS, docker-compose installed via docker snap

**Comment by BLasan** [comment]
Is this still a valid issue?
