### ISSUE TITLE
Embed config in docker-compose.yaml file

### ISSUE THREAD

**Issue by yegle** [docker/compose#7636]
**Is your feature request related to a problem? Please describe.**

One common way of using a container image built by some other people is by mounting a config file into the container.

E.g. if I want to run `coredns`, I will grab `coredns/coredns` image, mount my own config to `/Corefile`, and run the container.

But doing this means after I edit my `Corefile`, I'll need to remember run `docker restart coredns` or `docker-compose restart coredns`, instead of simply running `docker-compose up -d`.

**Describe the solution you'd like**
The easiest way is to be able to embed the Corefile inside the `docker-compose.yaml` file, something like this:

```
services:
  coredns:
    image: coredns/coredns
    config:
      - path: /Corefile
        content:|
          # Embedded Corefile
          . {
              whoami
          }
```

This way I can either just embed the config, or use tools like `jsonnet` to generate a `docker-compose.yaml` with embedded config.

**Describe alternatives you've considered**

Alternatively we can support `src_file` like this, and use the change of file hash to signal the need to restart the container:

```
services:
  coredns:
    image: coredns/coredns
    config:
      - path: /Corefile
        src_file: ./Corefile
```

Without adding this as a new feature I don't see a simple way to support what I need (edit config file A result in `docker-compose up -d` to restart container B).

**Additional context**
Add any other context or screenshots about the feature request here

**Comment by LtChae** [comment]
I'm interested in this as well

**Comment by yegle** [comment]
It looks like Docker Swarm does have this feature: https://docs.docker.com/engine/swarm/configs/

**Comment by vlcinsky** [comment]
@yegle Are you sure, the requested feature - configuration file embedded into docker-compose.yml file - really exists?

In the link you have provided see only config files defined by means of referenced files.

**Comment by futuretech6** [comment]
you can use the [configs top-level elements](https://docs.docker.com/compose/compose-file/08-configs/) for your config file
