### ISSUE TITLE
DNS entries are not working inside the containers

### ISSUE THREAD

**Issue by bhanukumar22** [docker/compose#7638]
Hello All,

Im trying to build an image with Centos as base image. I have exposed all the ports and communication to host is working fine.
Container also coming up fine. 
But DNS is not resolving the FQDN. I have added DNS entries in dns in docker-compose. Using bridge network.

# docker -v
Docker version 1.13.1, build 4ef4b30/1.13.1

docker-compose.yml -> (Im using the below)
network_mode: bridge

```
    dns:
     - x.x.x.x               -> Though I have provided IP here, inside my container, FQDN is not getting resolved
```
I can see the entry in docker inpect <container-name>

            "Dns": [
                "10.57.178.2"
            ],

I tried changing the network_mode to "host" as well. Host /etc/resolv.conf is also not being considered in this case. So, I tried adding DNS entry in docker-compose, even that dint work.

Please help. Am I missing something here

**Comment by MorgothSauron** [comment]
I have the same problem. I noticed that `/etc/resolv.conf` in the container will be set to `127.0.0.1` when using `docker-compose` to start it. But if I start the container with `docker run ...`, the content of `/etc/resolv.conf` contains valid IPs.
