### ISSUE TITLE
how to use docker images start service?

### ISSUE THREAD

**Issue by yankeeguyu** [docker/compose#7640]
I build images by myself, Now I want to start it, but it showed me this.
![image](https://user-images.githubusercontent.com/46274612/88997003-2ff22000-d321-11ea-808f-2fa5597069d1.png)

How to fix it? Thank you!

**Comment by BLasan** [comment]
try `docker container start <container_name>`

**Comment by yankeeguyu** [comment]
> try `docker container start <container_name>`

I solved it, thanks.
