### ISSUE TITLE
disable env variable substitution in docker compose env files

### ISSUE THREAD

**Issue by simonm11** [docker/compose#7648]
I updated docker and notice a significant change of behavior when using my env files in docker-compose

I have the following:

```
env_file:
      - ./file.env
```
and, in file.env
```
property=${something}
```
Before updating, doing `echo $property` in my running container would produce the string `${something}`. Which was what I wanted.

Now (docker 19.03.12), `$property` is empty because docker is trying to find `$something` from my system env variables.

What caused this change of behavior? Is there a way to disable it or work around it?

**Comment by ImDevinC** [comment]
This looks similar to the issue I reported awhile ago, unfortunately no response yet: #7601

**Comment by simonm11** [comment]
did you find some kind of work around in the meanwhile?

**Comment by dominikbraun** [comment]
> What caused this change of behavior?

Possibly https://github.com/docker/compose/pull/7150.

**Comment by simonm11** [comment]
Is it a bug or an intended feature ?

**Comment by ImDevinC** [comment]
@simonm11 I found that removing the `{}` from my variable seemed to help. IE: Changing `${SAMPLE_ARG}` to `$SAMPLE_ARG`. I'm sure there are some situations where the brackets will be needed, but I lucked out in my case where they weren't needed

**Comment by nikasioMel** [comment]
Hi @ImDevinC, we are having same issue.

We update docker-compose from **1.25.4** to **1.27.4** and start trying to subtitute `${xxx}` variables. Unfortunatly we can't remove brackets as you mentioned in previous comment.
Is there any way to tell compose to not to replace variables?

**Comment by ImDevinC** [comment]
It's been awhile since I've visited this, but I've been using the workaround above for my solution, just remove the `{}` from your variable so instead of `${xxx}` you can use `$xxx`

**Comment by nikasioMel** [comment]
Unfortunately **Spring** needs brackets to replace the variables when it starts the application, as docker replacement occurred before the variable is erased at the moment Spring needs it. We will continue using **1.25.5**
It would be great if it could be disabled in docker-compose
Thanks anyway.

**Comment by saschabrockel** [comment]
The bug still exists. We just had the bug with BookStack where also a property with a dollar sign is used.
