### ISSUE TITLE
unable to trap signal when containers are shut down with --abort-on-container-exit

### ISSUE THREAD

**Issue by marten-seemann** [docker/compose#7652]
## Description of the issue

It looks like it's not possible to trap the SIGTERM signal when a container is shut down when another container exits and `--abort-on-container-exit` is used.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**

This is the `docker-compose.yml`:
```yaml
version: "3.5"
services:
  short:
    build: .
    environment: 
    - DURATION=2
  long:
    build: .
    container_name: long
    environment: 
    - DURATION=100
```

## Steps to reproduce the issue

The containers are built using the following `Dockerfile`:
```Dockerfile
FROM ubuntu:latest

COPY run.sh .
RUN chmod +x run.sh
ENTRYPOINT [ "./run.sh" ]
```

with the following `run.sh`:
```bash
#!/bin/bash

trap "echo EXIT" EXIT
trap "echo SIGNIT" SIGINT
trap "echo SIGTERM" SIGTERM
trap "echo SIGKILL" SIGKILL
trap "echo SIGQUIT" SIGQUIT

echo "Sleeping $DURATION seconds."
sleep $DURATION & wait
```

### Observed result

When starting the containers with `docker-compose up`, and then shutting down container `long` using `docker stop long`, it receives both a SIGTERM and an EXIT signal.
When starting the containers with `docker-compose up --abort-on-container-exit`, container `long` is stopped, but doesn't receive any signal.

### Expected result

I expected container `long` to trap the same signals as when using `docker stop long`.

**Comment by marten-seemann** [comment]
This issue is not stale. It’s just that nobody has bothered to even look at it, as far as I can tell.

**Comment by sahilabro** [comment]
Did anyone ever look at this? I am unable to capture `SIGINT` for any containers when aborted via this method.

**Comment by marten-seemann** [comment]
I've never found a fix this issue, and apparently the Docker team doesn't care.

@sahilabro Maybe you want to open a new issue, maybe you'll be more lucky than me.

**Comment by sahilabro** [comment]
Thanks @marten-seemann 

I am able to catch `SIGTERM` now, which does the job for me. I also had to make sure I was using the entrypoint as an array, not a command-line string.
