### ISSUE TITLE
docker-compose never runs on Mac Catalina

### ISSUE THREAD

**Issue by deepakSense** [docker/compose#7667]
## Description of the issue
I am using Docker App on mac and when I hit docker-compose command it does this

`docker-compose version
Killed: 9`

## Context information (for bug reports)

**Output of `docker-compose version`**
```
Killed: 9
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
Killed: 9
```

## Steps to reproduce the issue

1. I installed Docker App for Mac.
2. Created a Yaml file for Compose
3. Tried running docker-compose
4. Enabled "Experimental Features" in the Command Line preferences of the App and tried again.

### Observed result
docker-compose doesn't run

### Expected result
docker-compose should run

### Stacktrace / full error message

```
Killed: 9
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by kuklyy** [comment]
Could you please attach your compose file?
