### ISSUE TITLE
Logging docker commands generated from compose files

### ISSUE THREAD

**Issue by ozkanonur** [docker/compose#7672]
Wouldn't it be perfect if docker-compose can log the docker commands in a log file? This can work tremendously for many projects and helps us to reduce time in the development process. Compose already runs everything as a docker commands right ? I think it shouldn't be hard to do this feature. Tell me if this request is reasonable so I can start creating this feature and PR it to main repository.

**Comment by m3Yilmaz** [comment]
The feature that mentioned above will be great if it become alive.

**Comment by ftahirops** [comment]
@ozkanonur Can you please further elaborate with some example? what do you mean by docker compose commands?

**Comment by ozkanonur** [comment]
> @ozkanonur Can you please further elaborate with some example? what do you mean by docker compose commands?

An example, I will use docker-compose for only development purpose and docker commands with kubernetes on production. Since every service in compose file has its counterpart in the docker command, it would be fantastic if we can get that instead of writing manually for each container.
