### ISSUE TITLE
`docker-compose up --no-build` should not require the existence of the build context directories

### ISSUE THREAD

**Issue by zeehio** [docker/compose#7674]
**Is your feature request related to a problem? Please describe.**
In a production system, I would like to use `docker-compose up --no-build` but I can't when the build context directory does not exist, even though it is not used:

    ERROR: build path my/build/context either does not exist, is not accessible, or is not a valid URL.

**Describe the solution you'd like**
`docker-compose up --no-build` should not require the existence of build context directories.

**Describe alternatives you've considered**
I can run `mkdir -p my/build/context` before `docker-compose up --no-build`, but it's kind of annoying to have to do that.

**Additional context**

Discussion at: https://stackoverflow.com/q/53389151/446149

**Comment by woo2** [comment]
Looks like this was fixed in [1.27.0](https://github.com/docker/compose/releases/tag/1.27.0)!

**Comment by emranbm** [comment]
That's nice. Thanks.  
But it still errors on `docker-compose down`:  
```
ERROR: build path /some/where either does not exist, is not accessible, or is not a valid URL.
```
However, why does it need to have build context when `down`ing at all?!

**Comment by emranbm** [comment]
This issue seems to be a subset of #4047.
