### ISSUE TITLE
proposal :: Orchestrate DNS-Services

### ISSUE THREAD

**Issue by blaggacao** [docker/compose#768]
problem
---
when wanting to deploy dedicated app clusters to clients through templating the orchestration yaml-files, the question is, how do i easly setup the dns for this.

proposal
---
there are great services such as [dnssimple](http://support.dnsimple.com/articles/dnsimple-services/) with an [api](http://support.dnsimple.com/categories/api/). hashicorp's competing tool [terraform](https://www.terraform.io/) has got some additionals "outside world" providers like said [dnssimple](https://www.terraform.io/docs/providers/dnsimple/index.html)

rational
---
If I might decide to go with fig/composer, and decide against beeing system agnostic, because I just know I want to do all I do the docker way - for some whatever reason - I might also want to be able to set up adjacent services such as DNS and probably mailchimp or similar...

**Comment by david-guenault** [comment]
well there are allready solutions for that "problem". 
Easy (and basic) => docker links (but does not support circular linking)
A little bit more tricky (but work well in container) => skydock/skydns(2)

**Comment by blaggacao** [comment]
I got probably misunderstood:
Is skyshock/skydns the solution to expose individual services to the outer world? Let's say I want to automatically spin up 1000 dedicated client-instances a day, as soon as those 1000 clients checked out successfully on the webshob. Maybe I understand too little about the pitfalls of DNS setup and skydns is indeed the solution, but I might eventually claim none-the-less: I want a simpler one like dnassimple-api. Deploy and forget.

**Comment by david-guenault** [comment]
You are right i misunderstood your need ! ;-). Fig is just an orchestration tool you need to dig into service discovery and service publishing (take a look at progrium blog http://progrium.com/blog/)

**Comment by blaggacao** [comment]
Thanks for the link, I might with some additional resarch be able to figure it out, my suggestion however was to include external services such as Amazone Route53 or dnssimple directly into the composer cli, so you can specify it in your composer files, instead of accessing their api through external coding.

**Comment by funkyfuture** [comment]
@blaggacao can this issue be closed?
