### ISSUE TITLE
docker-compose doesn't properly set network: host.

### ISSUE THREAD

**Issue by whitleykeith** [docker/compose#7682]
## Description of the issue

X-Post of [this issue](https://github.com/moby/buildkit/issues/1642) per @ulyssessouza request. 

Docker-compose doesn't seem to be able to leverage buildkit when running inside EKS, which does not have the default bridge network. This happens even if all images are set to use the host network in the docker-compose file.  

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       369ce74
  Built:            Fri May 29 04:01:57 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**

Note: There are about 20+ images with the same format. Some of them depend on other images in the compose, but there are no circular dependencies. 

(Make sure to add the relevant `-f` and other flags)
```yaml
  pre-flight-debian:
    build:
      context: REDACTED
      network: host
    image: REDACTED
    network_mode: host
```

## Steps to reproduce the issue

1. Run the `docker-compose build` with buildKit enabled (DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1)

### Observed result

Get an error about the network bridge not being found, even though I'm running on host for *all* images

### Expected result

The build to run successfully

### Stacktrace / full error message

```
ERROR: executor failed running [$DOCKER_STAGE_FROM_IMAGE]: network bridge not found
```

## Additional information

Environment:

Kubernetes/EKS: v1.16.8-eks-e16311
docker-compose: 1.26
Docker version 19.03.12, build 48a66213fe

Essentially I have a docker-compose file with multiple images that I want to build inside a CI Container hosted in Kubernetes. EKS has disabled the default bridge network in Kubernetes AMIs. This means docker builds in this environment require the --network=host flag, and this is true for our images as well.

We log the docker-compose file and can confirm the build.network and network_mode are set to host.

We've been able to run BuildKit on single images like

DOCKER_BUILDKIT=1 docker --network=host build . -t image:latest

with no problems, but when we try to build the entire compose like this:

DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 NETWORK=host docker-compose -f docker-compose.yaml build

we get this error:

failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [REDACTED]: network bridge not found

The command has been relatively random, but usually the first filesystem or network call (i.e. COPY/ADD or RUN).

Does anyone know why this is?

**Comment by ulyssessouza** [comment]
What happens is that the network mode wasn't parsed in the native build. https://github.com/docker/compose/pull/7689 Should fix that

**Comment by whitleykeith** [comment]
Awesome, thanks! Any idea what release this fix will go out with?

**Comment by ulyssessouza** [comment]
Probably `1.27.0-rc2` if it's merged tomorrow before the release.
