### ISSUE TITLE
docker-compose exec fails with No such container when using contexts

### ISSUE THREAD

**Issue by charles-cooper** [docker/compose#7685]
# Description of the issue
No such container is thrown when using a context referencing a remote host. The same command using docker, or docker-compose explicitly using the `-H` flag works fine.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build unknown
```

**Output of `docker version`**
```
(local) Docker version 19.03.8, build afacb8b7f0
(remote) Docker version 19.03.8, build afacb8b7f0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  postgres:
...
```

## Steps to reproduce the issue
```
1. docker context create remote --docker "host=tcp://<host>:<port>"
2. docker-compose --context remote up -d
3. docker-compose --context remote exec postgres echo 1
```
### Observed result
```
Error: No such container: <container_hash>
```

### Expected result
```
1
```

## Additional information

The same thing works in the following scenarios:
- `docker --context ask exec -it <container_id> echo 1`
- `docker-compose -H "<host>:<port>" exec postgres echo 1`

**Comment by abronin** [comment]
I have the same issue. This make docker-compose with context completely useless for me.

**Comment by vdroznik** [comment]
just ran into the same issue
