### ISSUE TITLE
[1.27.0_rc2] Version bump missing in setup.py (but advertised as a bugfix in change log)

### ISSUE THREAD

**Issue by hartwork** [docker/compose#7699]
Hi!

I noticed that the change log of 1.27.0_rc2 advertises `Fix float to bytes conversion via docker-py bump to 4.3.1` (see 
45c6730e6464cb6e22439c558d3036647b301610) yet `setup.py` does not depend on that new version, see https://github.com/docker/compose/blob/45c6730e6464cb6e22439c558d3036647b301610/setup.py#L35

Is the bump missing in `setup.py`?

Best, Sebastian

**Comment by ulyssessouza** [comment]
Thank you @hartwork !

You are right! We missed this part. Here is the PR to fix it https://github.com/docker/compose/pull/7713
