### ISSUE TITLE
Docker-compose build error after specifying context to user's home directory

### ISSUE THREAD

**Issue by diomondus** [docker/compose#7711]
## Description of the issue
I try to build mysql image using specific context in build section of docker-compose.yml. Repeated on macos and centos. 
I have the following structure:
```
docker
├── dock
│   └── Dockerfile
└── docker-compose.yml
```
'docker' folder is in user's home directory (~/docker)
Then i run 'docker-compose build'
After 10-20 minuets of waiting I had errors

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
```

**Output of `docker version`**
```
Docker version 19.03.1, build 74b1e89
```

**docker-compose.yml**
```
version: '3.3'
services:
  db:
    build: 
      context: ..
      dockerfile: docker/dock/Dockerfile 
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
```

## Steps to reproduce the issue

1. put docker folder to ~/
2. docker-compose build

### Observed result
Failed to execute script docker-compose

### Expected result
build success as if 'docker' folder would be in ~/some_folder/docker

### Stacktrace / full error message

```
MacBookPro:docker user$ docker-compose build
Building db
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 287, in build
  File "compose/project.py", line 386, in build
  File "compose/project.py", line 368, in build_service
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 159, in build
  File "site-packages/docker/utils/build.py", line 31, in tar
  File "site-packages/docker/utils/build.py", line 79, in create_archive
  File "tarfile.py", line 1805, in gettarinfo
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/Library/Caches/Google/Chrome/Default/Cache/7279598491babd49_0'
[3177] Failed to execute script docker-compose
```

## Additional information
macOS Mojave, CentOS 7.5

**Comment by aiordache** [comment]
Hi @diomondus! 
I would avoid setting the build context  to your homedir. This causes the build to transfer the entire contents of your homedir to the Docker daemon. From the trace, my guess is the archiving process breaks due to the temporary files from your browser's cache that may be deleted during that process. 

Did you get a similar trace on centos?

**Comment by diomondus** [comment]
Anyone can't avoid setting the context to homedir, because it's a relative path in docker-compose.yml. I see that the problem begins when build context directory is too large and there are some read/write processes. May be it would be better not to change context higher than yml dir? For example as the best practice. Or generate error message when dir content is too large. 

On centos there was a delay but the reason is different.
