### ISSUE TITLE
Installation - "Releases" folder missing

### ISSUE THREAD

**Issue by iot49** [docker/compose#7721]
## Description of the issue

The installation instructions at https://docs.docker.com/compose/install/ (for Linux) refer to  this repo:

```
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

The download fails since there is no `releases` folder. What's the preferred way to install `compose` on Linux?

**Comment by ulyssessouza** [comment]
Hello @iot49, works fine for me.

**Comment by iot49** [comment]
I ran the command on a raspberry pi:

```
$ uname -s
Linux
$ uname -m
armv7l
```

**Comment by ulyssessouza** [comment]
We don't support release any `arm` based binaries. Please use an alternative installation in this case.
