### ISSUE TITLE
"No such container" error when using docker-compose run or exec with SSH context

### ISSUE THREAD

**Issue by ipsingh06** [docker/compose#7724]
## Description of the issue
When using 'docker-compose run' or 'docker-compose exec' with an SSH context, I always get the error:
```
Error: No such container
```
`docker-compose up' works fine.
'docker run' also works fine with this SSH context.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  test:
    command: echo hello
    image: alpine:latest
version: '3.4'
```

## Steps to reproduce the issue

This is my output of `docker context ls`:
```
NAME                DESCRIPTION                               DOCKER ENDPOINT                     KUBERNETES ENDPOINT   ORCHESTRATOR
default *           Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                               swarm
remote                                                        ssh://<user>@<ip>                         

```

1. `docker-compose --context remote run --rm test echo hello`
   Fails with: `Error: No such container`.

All of the following work:
1. `docker-compose --context remote up`
2. `docker --context remote run --rm alpine:latest echo hello`
3. `docker-compose run --rm test echo hello`

### Observed result

Fails with: `Error: No such container`.

### Expected result

Should run container.

### Stacktrace / full error message
N/A

## Additional information

Local: Ubuntu 18.04. Remote: Ubuntu 20.04.

**Comment by aiordache** [comment]
Hi @ipsingh06! Could you try this with the latest release 1.27.0 please?

**Comment by ipsingh06** [comment]
It now produces the same issue as described here: https://github.com/docker/compose/issues/7686
