### ISSUE TITLE
1.27.0 deploy.replicas: 0 behavior change

### ISSUE THREAD

**Issue by Leland-Takamine** [docker/compose#7735]
## Description of the issue

Version 1.27.0 behaves differently than 1.26.2 for `deploy.replicas: 0` when run with `docker-compose --compatibility up`:

`1.27.0`: Launches one instance of the service
`1.26.2`: Does not launch any instances of the service

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.0, build 980ec85b
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**

```
services:
  hello:
    deploy:
      replicas: 0
    image: hello-world
version: '3'
```

## Steps to reproduce the issue

1. With version 1.26.2 installed, run `docker-compose --compatibility up`
1. With version 1.27.0 installed, run `docker-compose --compatibility up`

### Observed result

**1.26.2**

With version 1.26.2, `deploy.replicas: 0` resulted in the container not being launch.

```
$ docker-compose --compatibility up
Attaching to
```

**1.27.0**

With version 1.27.0, `deploy.replicas: 0` results in a single instance of the container being launched.

```
$ docker-compose --compatibility up
Starting tmp_hello_1 ... done
Attaching to tmp_hello_1
...
```

### Expected result

I would have expected 1.27.0 to behave in the same way as 1.26.2 though I'm not sure which is the expected behavior.

## Additional information

I'm currently using `deploy.replicas: 0` to enable building containers via a compose file without running them. With 1.27.0 it seems this strategy no longer works. I'd also appreciate any alternative ways to achieve this if the 1.27.0 behavior is correct.

**Comment by aiordache** [comment]
Thank you for reporting this regression @Leland-Takamine. We will fix it for 1.27.1
