### ISSUE TITLE
1.27.0 : compose config subcommand show a bad compose file version number (truncated)

### ISSUE THREAD

**Issue by Naewis** [docker/compose#7748]
## Description of the issue

When a config file with version: '3.8' is used, the config command return version '3'.
We're currently using config output to concatenate multiple config files and the result is unusable as 3 doesn't mean 3.8 version and thus incompatible with recent options.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.0, build unknown
docker-py version: 4.3.1
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Source of compose file**

```
version: '3.8'
```

**Output of `docker-compose config`**

```
services: {}
version: '3'
```

## Steps to reproduce the issue

1. Create a file with single line
```
version: '3.8'
```
2. Install docker-compose version 1.26.0
```
# sudo pip3 install docker-compose==1.26.0
```
3.Executing docker-compose -f <filename> config returns this
```
services: {}
version: '3.8'
```
4. Install docker-compose version 1.27.0
```
# sudo pip3 install docker-compose==1.27.0
```
5.Executing docker-compose -f <filename> config returns this
```
services: {}
version: '3'
```

### Observed result

version: '3'

### Expected result

version: '3.8'

## Additional information

Bug seen in debian (container and host reproduced)
Docker-compose pip3 install

**Comment by aiordache** [comment]
Hi @Naewis Can you give it a try with the latest version please?

**Comment by milenvoutchev** [comment]
Happens to us as well.

Github Actions' virtual environment (runner) "Ubuntu 18.04.5 LTS" with:

```
Docker Compose (docker-compose version 1.27.0, build 980ec85b)
Docker-Moby (Docker version 19.03.12+azure, build 0ed913b885c8919944a2e4c8d0b80a318a8dd48b)
Docker-Buildx (0.4.2+azure)
```

**Comment by Naewis** [comment]
Hello.

A try with version 1.27.1 seems to be correct. I've been tricked with the bad version I got from the apt store.

Sorry for the time wasted.
