### ISSUE TITLE
docker-compose up --scale work wrong

### ISSUE THREAD

**Issue by WhattaSkilL** [docker/compose#7749]
## Description of the issue
docker-compose up --scale work wrong
Screenshot console: https://ibb.co/9GS6wn9

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  service:
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    image: mysql:5
version: '3.3'
```

## Steps to reproduce the issue

1. docker-compose up --scale service=4 -d
2. docker stop <some container from scale>
3. docker-compose up --scale service=4 -d

### Observed result
I got 7 containers with status UP

### Expected result
Must be 4 containers with status UP

**Comment by aiordache** [comment]
Hi @WhattaSkilL Please update your docker-compose to the latest release.

**Comment by WhattaSkilL** [comment]
> Hi @WhattaSkilL Please update your docker-compose to the latest release.

Thanks for answer! 
After update i still have this
Screenshot: https://ibb.co/QptJ1K2

**Comment by aiordache** [comment]
Thank you for reporting the issue @WhattaSkilL. We should have this fixed in the next release.
