### ISSUE TITLE
Passed through environment variables have newlines stripped

### ISSUE THREAD

**Issue by frankh** [docker/compose#7763]
## Description of the issue
When passing through an environment variable (either through `-e` command line flag or in the `environment:` key) newlines are stripped from the value

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.2, build eefe0d31
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  web:
    command: sleep infinity
    image: ubuntu
version: '3.5'
```

## Steps to reproduce the issue

```
$ export VAR="1
2
3"
$ echo $VAR
1
2
3
$ docker-compose run -e VAR web bash -c 'echo $VAR'
1 2 3
```

### Observed result
with docker-compose -e VAR it prints "1 2 3" with no newlines

### Expected result
should print the same result as `echo $VAR` without docker-compose

### Stacktrace / full error message
n/a

## Additional information
both MacOS + linux

**Comment by jarulsamy** [comment]
One more piece of information that may be helpful, I notice this happens with `docker run` as well:
```
$ export VAR="1
2
3"

$ echo $VAR
1
2
3

$ docker run -e VAR -it busybox:latest /bin/sh -c 'echo $VAR'
```

Looking briefly through the source indicates that `compose` handles environment variables pretty transparently. That is, it does not actually edit them in any way. Dumping the output of the command line options of confirms this:

```yml
simple:
    image: busybox:1.27.2
    command: echo "Hello, World!"
```

```
$ docker-compose run -e VAR simple /bin/sh -c 'echo $VAR'
{'--': False,
 '--detach': False,
 '--entrypoint': None,
 '--label': [],
 '--name': None,
 '--no-deps': False,
 '--publish': [],
 '--rm': False,
 '--service-ports': False,
 '--use-aliases': False,
 '--user': None,
 '--volume': [],
 '--workdir': None,
 '-T': False,
 '-e': ['VAR'], # Compose never sees the contents of VAR
 'ARGS': ['-c', 'echo $VAR'],
 'COMMAND': '/bin/sh',
 'SERVICE': 'simple'}
1 2 3
```

**Comment by frankh** [comment]
good find @jarulsamy, I guess it's a `docker` bug then
