### ISSUE TITLE
Add command line option to disable connection to stdin

### ISSUE THREAD

**Issue by skrech** [docker/compose#7776]
Hello,

Using shell's heredoc feature I wanted to automate some test environment setup today. I had a situation similar to the following:
```
$ ssh user@some.domain.com << EOF
> docker-compose run --rm container sh -c 'echo aaa'
> echo bbb
> EOF
```

Unfortunately, "bbb" was never printed on my screen but the script exited with success status of 0. 

It turned out that docker-compose is **always** connecting container's stdin to shell's stdin. Since heredoc is form of shell redirection, the commands following `docker-compose run` are supplied to the container's stdin and when `docker-compose run` finishes, there is nothing left in the stdin anymore and the script exits successfully.

The same would happen if one uses `docker run -i` in place of `docker-compose run` command above. However, with `docker` the user can specify whether to use this option or not, while with `docker-compose` it's not possible.

So, is it possible to add `-I` option to `docker-compose`, similar to the `-T` option to support use-cases like this? I think that using small multi-line scripts over ssh is quite common use-case.

docker-compose version 1.26.2, build eefe0d31
Docker version 19.03.10, build 9424aea
OS is PhotonOS 3.

**Comment by x-yuri** [comment]
In my case it was:

```sh
echo $'line1\nline2\nline3' | while IFS= read -r; do
    docker-compose exec -T app sh -c 'echo test'
done
```

But since `docker-compose` consumes all the input, "test" is outputted only once. Workaround:

```sh
echo $'line1\nline2\nline3' | while IFS= read -r; do
    echo | docker-compose exec -T app sh -c 'echo test'
done
```

**Comment by nbelakovski** [comment]
I just ran into this same issue and it was very difficult to debug. I'd support adding a `-I` flag, or maybe `--no-input` to distinguish and disambiguate it from the `-i` flag of docker exec.
