### ISSUE TITLE
Changelog only goes up to 1.25.2

### ISSUE THREAD

**Issue by mcamou** [docker/compose#7781]
## Description of the issue

The Changelog in this repository only goes up to 1.25.2, which gives no information as to the changes afterwards

## Context information (for bug reports)

**Output of `docker-compose version`**
```
(paste here)
```

**Output of `docker version`**
```
(paste here)
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by EricHripko** [comment]
I can see 1.26 and 1.27 changes in the [CHANGELOG](https://github.com/docker/compose/blob/master/CHANGELOG.md) of main branch

**Comment by mcamou** [comment]
I see now, I followed the `Changelog` link from https://pypi.org/project/docker-compose/1.27.3/ and it took me to the `release` branch instead of the `1.27.3` branch.

**Comment by ulyssessouza** [comment]
Fixed by https://github.com/docker/compose/pull/7769
