### ISSUE TITLE
logs of docker-compose up not real time

### ISSUE THREAD

**Issue by anhtu812** [docker/compose#7788]
if I use "docker run" or "docker-compose run", logs is real time. When I use "docker-compose up", some logs lost and some logs showed after about 15 minutes. I use docker-compose 1.17.1 and my processes in container use c++ code and python code. Please fix this issue, I can not debug with lost logs and delay logs.

**Comment by ulyssessouza** [comment]
Could you please test it with the latest version?

**Comment by anhtu812** [comment]
I installed 1.27.4, no change.
