### ISSUE TITLE
ANSI support for when no-tty option is used (-t)

### ISSUE THREAD

**Issue by gapipro** [docker/compose#7789]
**Is your feature request related to a problem? Please describe.**
When using docker-compose with -t option (no-tty) there isn't any ANSI color output.  
My use-case is for example when running docker-compose in Intellij Idea as external tool. Output is generated in non-tty enabled console that results in plain colors.

**Describe the solution you'd like**
I would with that there is an option to force --ansi even when no-tty is used.

**Describe alternatives you've considered**
It works ok if output console supports tty, but in other cases there isn't a clear alternative to this, except piping output to temp file and displaying that in output via some other command that supports ansi

**Comment by ndeloof** [comment]
ANSI support is by definition tied to a text terminal, as opposed to Posix stdin/stdout
Itellij Idea fully emulates a TTY (I'm using this on a daily basis), you should not have to run with `-T` option.
