### ISSUE TITLE
Validation before evaluate

### ISSUE THREAD

**Issue by lagden** [docker/compose#7790]
### System Info

```
OSX 10.15.6 (19G2021)
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.27.2, build 18f557f9

Installed via https://www.docker.com/products/docker-desktop
```

### Problem

I always use `.env` file to setup `docker-compose.yml`
and now an error occurred specifically in this property: `deploy.resources.reservations.cpus`

The example is here:
https://github.com/lagden/compose-issue

See below what happens:

![simple](https://user-images.githubusercontent.com/130963/94104346-2bbc1d80-fe0d-11ea-955c-0f8787cf190d.gif)

#### Steps

1. Run `docker-compose up`
2. **Problem:** Error caused by `deploy.resources.reservations.cpus` validation
3. Comment property `deploy.resources.reservations.cpus` in `docker-compose.yml` (line 15)
3. Run again `docker-compose up`
4. OK

**Comment by ulyssessouza** [comment]
Fixed in https://github.com/docker/compose/pull/7768
