### ISSUE TITLE
Cannot install Docker-Compose over curl

### ISSUE THREAD

**Issue by TheDuckMann** [docker/compose#7830]
## Description of the issue
Hello everyone,

as described on the [docker webpage](https://docs.docker.com/compose/install/):
I tried to install docker compose on my Linux Machine (Ubuntu 20.04 LTS) via CURL today.
Unfortunately it didn't work well. This is because I am getting an [web-error 404](https://github.com/docker/compose/releases/download/1.27.4/docker-compose)

## Context information (for bug reports)

**Output of `docker-compose version`**
```
----------
```

**Output of `docker version`**
```
Docker version 19.03.13, build 4484c46
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
----------
```

## Steps to reproduce the issue
**As described above:**
**1. Run:** sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
**2. Run:** sudo chmod +x /usr/local/bin/docker-compose
**3. Run:** sudo docker-compose --version

### Observed result
/usr/local/bin/docker-compose: 1: Not: not found

### Expected result
docker-compose version 1.27.4, build 1110ad01

### Stacktrace / full error message

```
----------
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by jarulsamy** [comment]
Please post the output of these two commands:
```
$ uname -s
$ uname -m
```

**Comment by TheDuckMann** [comment]
Thanks for your reply!
The output of "uname -s" gives me: Linux
The output of "uname -m" gives me: aarch64

**Comment by TheDuckMann** [comment]
I think I now understand the problem.
DockerCompose is not meant to be installed on a raspberry-pi via curl....am I right?!
Because this is what I was trying to do.

But I think I can install it over PIP..?!

**Comment by jarulsamy** [comment]
Yes, the cURL command grabs a release from the Compose GitHub page which only supports `x86_64`. You should be able to install through pip.

**Comment by TheDuckMann** [comment]
Thank you for your help, especially to show me what I have done wrong. I'll try it over pip.
