### ISSUE TITLE
Environment variable validation not handling ambiguous duplicate entries (array style)

### ISSUE THREAD

**Issue by burl** [docker/compose#7832]
## Description of the issue

when in a service, the 'environment' (of the "list" form) contains duplicate variables, the apparent validation does not seem to do what it should.  It seems that if there is validation of the names and values that duplicate names should not be allowed.  However, if an entry is listed twice with the same value, then that is not flagged as an error.  However, if the same variable name is listed twice with different values, then that does result in an error.  It seems that both should be errors.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.2, build 18f557f9
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.foo.environment contains non-unique items, please remove duplicates from ['FOO=bar', 'BAR=baz', 'FOO=bar']
```

## Steps to reproduce the issue

This will result in an error because 'FOO' is listed twice with a differnt value:

```yaml
version: '3.5'
  services:
    foo:
      image: alpine
      environment:
       - FOO=bar
       - BAR=baz
       - FOO=hork
```

But, this will not result in an error.  Foo is listed twice with the same value:

```yaml
version: '3.5'
  services:
    foo:
      image: alpine
      environment:
       - FOO=bar
       - BAR=baz
       - FOO=bar
```

### Observed result

Duplicate named variables are allowed when the values are the same in each instance.  But not allowed when the values are different. 

### Expected result

I expect validation on the variables to consider only the names of the variables and when there are duplicate names listed in the same 'environment:' object (in "list mode") of the same yaml document, then that should at least be a warning, if not an error.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by phayaran** [comment]
Could you please assign this to me.
