### ISSUE TITLE
docker-compose up with multiple file does not include all container as service

### ISSUE THREAD

**Issue by dintifla** [docker/compose#7870]
## Description of the issue

I have a setup with two docker-compose files (both version 3):
1. `docker-compose.yml` with my production setup
2. `docker-compose.test.yml` which extends the first file with some other container names, env. variables and also **adds** new containers (e.g. a database)

`docker-compose -f docker-compose.yml -f docker-compose.test.yml -p my-proj up --force-recreate --build --detach`
creates and starts all containers.
now `docker-compose -p my-proj logs -f my-container-from-2nd-file` does not work.

All the containers are up and running, but the ones from the 2nd file do not seem to be added to the composition.
`docker-compose config --services` does not list any container defined in the 2nd file.

Same if `-p` is omitted.

I deploy production and test system from this script:

```bash
docker-compose -p $prodProjectName stop
docker-compose -f docker-compose.yml -f docker-compose.test.yml -p $testProjectName up --force-recreate --build --detach
docker-compose -p $projectName logs -f cypress
docker-compose -p $testProjectName stop
# some other non-docker stuff goes here
docker-compose -p $prodProjectName -f docker-compose.yml up --force-recreate --build --detach
```

## Context information (for bug reports)

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Steps to reproduce the issue

1. Write your main docker-compose.yml
2. Write a 2nd docker-compose.xyz.yml which adds more container
3. Run docker compose up with both files (2x -f flag) in detach mode
4. Run `docker-compose -p <your-project> logs -f <a-container-from-2nd-file>

### Observed result

`docker-compose config --services` lists only containers from first yml-file

### Expected result

`docker-compose config --services` lists containers from first *and second* yml-file

## Additional information
OS: Windows 10 2004 build 10.0.19041
WSL2

**Comment by danielsetreus** [comment]
I am experiencing the same issue, trying to view logs from two different sets of services defined in two different compose files. @dintifla  Did you ever get around it?

**Comment by laurazard** [comment]
I can't replicate this. My setup:

compose.yaml
```yaml
services:
 a:
  image: alpine
  command: /bin/sh -c "while true ; do echo a ; sleep 1 ; done"
```

compose.b.yaml
```yaml
services:
 b:
  image: alpine
  command: /bin/sh -c "while true ; do echo b ; sleep 1 ; done"
```

Running:
1. `compose -f compose.yaml -f compose.b.yaml -p test up -d`
2. `compose -p test logs`

I get:
```console
test-a-1  | a
test-b-1  | b
test-a-1  | a
test-b-1  | b
test-a-1  | a
test-b-1  | b
test-a-1  | a
test-b-1  | b
test-a-1  | a
test-b-1  | b
^Ccanceled
```

It's important to realize that Compose will only keep track of your services based on the files passed to it. If you run `compose up`, only `compose.yaml` is taken into account. If you run `compose -f [a file] -f [another file] -p test up -d`, then do other commands making sure to use `compose -p test [command like logs]`, then all the services associated with that project (`test` in this case) will be taken into account. However, if the `-p` flag is omitted, Compose will only take the `compose.yaml` into account, and only show logs from that service.

Please comment if there is additional information/something I missed.
