### ISSUE TITLE
docker-compose down don't remove volumes

### ISSUE THREAD

**Issue by TheEhsanSarshar** [docker/compose#7885]
as the doc said the `docker-compose down` only persist volumes that are `external`. but I normally make volumes and it still persist even after `docker-compose down`

**Comment by InteNs** [comment]
named volumes are also persisted, only anonymous volumes will we deleted by `docker-compose down` by default, if you want to also remove named volumes that are not external you can add `-v`:

> '-v, --volumes' Remove named volumes declared in the `volumes`
> section of the Compose file and anonymous volumes
> attached to containers.

**Comment by EhsanSarshar** [comment]
@InteNs do it mentioned in docs ?

**Comment by InteNs** [comment]
i quoted the command options part of the docs from here:
https://docs.docker.com/compose/reference/down/
