### ISSUE TITLE
Docs on docker/compose at Docker Hub is not up-to-date

### ISSUE THREAD

**Issue by tnir** [docker/compose#7891]
**Is your feature request related to a problem? Please describe.**
README.md available at https://hub.docker.com/r/docker/compose is obsolete and far away from https://github.com/docker/compose/blob/master/README.md.

**Describe the solution you'd like**
README.md at https://hub.docker.com/r/docker/compose should be the same as https://github.com/docker/compose/blob/master/README.md. Automated process is preferred.

**Describe alternatives you've considered**
One-off manual sync operation from https://github.com/docker/compose/blob/master/README.md to README.md at https://hub.docker.com/r/docker/compose.

**Additional context**

**Comment by tnir** [comment]
This problem still exists on Docker Hub, which someone from `@docker` can resolve.

**Comment by williamdes** [comment]
The image is not up to date and seems to use v1. What should we do ?

**Comment by glours** [comment]
@williamdes you can use the `docker` image which contains the latest version of Compose
```shell
> docker run -it docker compose version
Unable to find image 'docker:latest' locally
latest: Pulling from library/docker
9b18e9b68314: Already exists
5abd6445c68b: Pull complete
7b6c1cdde492: Pull complete
7917cc27eb40: Pull complete
3f2fb837c2a9: Pull complete
7c3545e58210: Pull complete
b0bf72b266be: Pull complete
b78a328d3398: Pull complete
0a45e30110dd: Pull complete
Digest: sha256:a7984be85b34c64a2073622b6287de0ad28799a82c1d7256174a486cc8a2ecbe
Status: Downloaded newer image for docker:latest
Docker Compose version v2.11.1
```

**Comment by tnir** [comment]
@glours How about adding it to https://hub.docker.com/r/docker/compose?

**Comment by williamdes** [comment]
> @glours How about adding it to https://hub.docker.com/r/docker/compose?

That would be cool because the GitHub action I made uses it: https://github.com/sudo-bot/action-docker-compose

Hi @glours 
Can I just copy the binary from the docker layer while I wait for [docker/compose](https://hub.docker.com/r/docker/compose) to be updated ?

**Comment by glours** [comment]
@williamdes did you try to replace `docker/compose` by `docker/docker` in your Dockerfile?

**Comment by williamdes** [comment]
> @williamdes did you try to replace `docker/compose` by `docker/docker` in your Dockerfile?

Nevermind, I copied the binary from the docker image into mine using `COPY --from=docker /usr/libexec/docker/cli-plugins/docker-compose /usr/bin/docker-compose` :)
See: https://github.com/sudo-bot/action-docker-compose/commit/2609b8603e7279529015b640f6bf979ca0a97461#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcR9

**Comment by ndeloof** [comment]
closing this issue as answered by https://github.com/docker/compose/issues/7891#issuecomment-1254549401

**Comment by williamdes** [comment]
> closing this issue as answered by [#7891 (comment)](https://github.com/docker/compose/issues/7891#issuecomment-1254549401)

So the other image is deprecated and will be left?
Can an official statement be made?

**Comment by ndeloof** [comment]
@williamdes 
see https://hub.docker.com/r/docker/compose

> Important
📣 Docker Compose is now included as part of the [Docker official image](https://hub.docker.com/_/docker) 🎉
...

**Comment by williamdes** [comment]
Thank you 🎉
