### ISSUE TITLE
Docker compose version 1.27.3 changed docker-compose config behavior

### ISSUE THREAD

**Issue by dragonpiper** [docker/compose#7893]
Previously, docker compose would only mutate volume opts at runtime for bind mounts. After version 1.27.3 This happens when using the docker-compose config command.

This is an issue because previously, I had a docker-compose.yml file which I used for local dev testing. This used the same storage volume name, but used the local drive with bind mounts.

I used a second file called deploy.docker-compose.yml which included the changes needed for running in prod environment which include volume.driver_opt changes and environment changes.  After the latest changes, the docker-compose config tool becomes useless for generating platform agnostic compose files. 

This is a gist that reproduces the issue.
https://gist.github.com/dragonpiper/0f81ce16c9da18715c2d5ebb6a4cf845

**Comment by LaXiS96** [comment]
I believe I stumbled upon this same bug when I last updated Docker Desktop from 2.3.0.5 (which included compose 1.27.2) to 2.4.0.0 (compose 1.27.4) and I couldn't deploy anymore from a Windows client to a Linux Docker host.

My configuration includes a bind mount with Linux paths for the specific Linux Docker host I am deploying to: the reported error showed that compose prepended a random (?) Windows partition identifier (like "C:") and converted path separators to Windows.

I had to revert to 2.3.0.5, and haven't upgraded yet. I'm quite surprised very few people noticed this problem.
@dragonpiper any news?
