### ISSUE TITLE
'docker-compose up' read deploy command.

### ISSUE THREAD

**Issue by Sangtong** [docker/compose#7897]
## Description of the issue
`docker-compose up` read **deploy** command which it should not be like that following the documentation, see the picture below.

![image](https://user-images.githubusercontent.com/44196831/97420969-8bdb3d80-193e-11eb-9692-5b3818d749fb.png)

## Context information

**Output of `docker-compose version`**

![image](https://user-images.githubusercontent.com/44196831/97419486-b3c9a180-193c-11eb-80ba-b8a90d7d13e0.png)

**Output of `docker version`**

![image](https://user-images.githubusercontent.com/44196831/97419653-e2e01300-193c-11eb-8e15-58b0ff52c3ec.png)

**Output of `docker-compose config`**

![image](https://user-images.githubusercontent.com/44196831/97420001-54b85c80-193d-11eb-8331-37c52f845295.png)

## Steps to reproduce the issue
1. Set deploy.replicas more than 1 in your docker-compose file.
1. Run `docker-compose up -d` command.

### Observed result
![image](https://user-images.githubusercontent.com/44196831/97420437-e88a2880-193d-11eb-9acf-aa5dbbb19ffc.png)

### Expected result
There are no errors when deploys with `docker-compose up -d` command.

**Comment by cbows** [comment]
#7770 seems related.

**Comment by Sangtong** [comment]
@cbows Thank you for your reply.
