### ISSUE TITLE
Unnecessary warning that flag '--parallel' is ignored when building with COMPOSE_DOCKER_CLI_BUILD=1"

### ISSUE THREAD

**Issue by ptrk8** [docker/compose#7901]
### Actual behavior

When I run the below command, I receive a warning in the shell that "Flag '--parallel' is ignored when building with COMPOSE_DOCKER_CLI_BUILD=1". However, it appears that `docker-compose build` is running in parallel when I'm using the `--parallel` flag so I'm not sure the warning message is correct or required.

```
$ COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.dev.yml build --parallel

WARNING: Native build is an experimental feature and could change at any time
WARNING: Flag '--parallel' is ignored when building with COMPOSE_DOCKER_CLI_BUILD=1
Building db      ...
Building server  ...
Building client  ...
Building cypress ...
Building db
Building client
Building cypress
Building server
Sending build context to Docker daemon  1.392MB
```

### Expected behavior

No warning message about the `--parallel` flag should be present when used in conjunction with `COMPOSE_DOCKER_CLI_BUILD=1`.

### Information
  - macOS Version: 10.15.6

### Diagnostic logs

```
Docker for Mac: 2.4.0.0
```

**Comment by bartenra** [comment]
Same issue.

```
Docker version 20.10.4
```

on Arch Linux

**Comment by johnthagen** [comment]
On macOS, the latest Docker Desktop pushed up to 1.28.5.

I found it confusing that `docker-compose build --help` still lists `--parallel`, but then if you use it:

```
WARNING: Flag '--parallel' is ignored when building with COMPOSE_DOCKER_CLI_BUILD=1
```

That indicated to me that somehow this `COMPOSE_DOCKER_CLI_BUILD` environment variable I had never heard of had gotten set, but `echo $COMPOSE_DOCKER_CLI_BUILD` yielded nothing. It wasn't until digging through release notes that I realized that the default had changed and this is implicitly set to `1` now. I wouldn't be surprised if others are confused by this.

Also, if by default `--parallel` does not work, how do you build images in parallel with the default set up? It wasn't clear to me if it was being built in parallel by default, or if this option is gone with the new default build process.

**Comment by mtham8** [comment]
Starting docker v1.28.0 release, the cli command is used by default, so `COMPOSE_DOCKER_CLI_BUILD=1`. 

According to the release notes, https://docs.docker.com/compose/release-notes/#1280
>  Set the `COMPOSE_DOCKER_CLI_BUILD=0` environment variable to disable this feature.

I tried `COMPOSE_DOCKER_CLI_BUILD=0 docker-compose build --parallel` and that worked for me. 

Then I added `export COMPOSE_DOCKER_CLI_BUILD=0` to my .zshrc and now I can run `docker-compose build --parallel` again without the warning.

**Comment by johnthagen** [comment]
From testing I was doing (Docker Compose 1.28.5/macOS), it does seem like `--parallel` does have an effect still in the default situation, even though the warning says that the it's being ignored. If I have a Compose project with multiple services, if I don't set `--parallel` only one image is built at a time. If I do set `--parallel`, it builds them in parallel with the warning.

Some official response here would be helpful.

**Comment by vedraan** [comment]
+1 on OSX/Big Sur and `docker-compose version 1.29.1, build c34c88b2` I get the warning but `--parallel` is still used it's clearly visible from the output (building multiple images at the same time).

**Comment by buraktabn** [comment]
Same issue on Ubuntu 20.04.2 LTS 

```bash
Docker version 20.10.7, build f0df350
docker-compose version 1.29.2, build 5becea4c
```

**Comment by StashOfCode** [comment]
This is really misleading. Moreover, without setting this flag, compose randomly chooses to build either one by one or in parallel

**Comment by johnthagen** [comment]
It appears as though `docker-compose` is all but frozen and the effort is being put into it's replacement:[`compose-cli`](https://github.com/docker/compose-cli)

**Comment by johnthagen** [comment]
This PR seems to indicate that Compose v1 indeed will be deprecated soon: https://github.com/docker/compose/pull/8589

**Comment by ndeloof** [comment]
`--parallel` was indeed introduced to get the "classic" builder build service images concurrently.
The introduction of buildkit, which is now used by default by `docker-compose build` (until explicitly disabled by `COMPOSE_DOCKER_CLI_BUILD=0`) makes this obsolete, as buildkit builds are BY DESIGN parallel. Pain point is that this relies on executing the docker CLI in the background (so the environment variable name).

Compose V2 also uses buildkit, being fully integrated in the Docker CLI.

**Comment by DaleyKD** [comment]
Maybe I haven't had enough coffee this morning, but I'm confused.

``` ps1
$env:COMPOSE_DOCKER_CLI_BUILD=1
$env:DOCKER_BUILDKIT=1
docker-compose build
```
This is DEFINITELY not building in parallel.

Is it because I'm using `docker-compose` instead of `docker compose` ?

``` cmd
PS C:\src> docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
PS C:\src> docker compose version
Docker Compose version v2.0.0-beta.6
```

**Comment by johnthagen** [comment]
@DaleyKD Yes this issue only affects `docker-compose` 1.X: https://github.com/docker/compose/issues/7901#issuecomment-811119974

It's a bug in `docker-compose` 1.X that this warning is shown even though `--parallel` is in fact needed. It doesn't look like `docker-compose` 1.X will be maintained any more, so the only solution will be to upgrade to `docker compose` 2.x, but then that isn't "Generally Available" yet, so if you need it on Linux there isn't a complete story yet: https://docs.docker.com/compose/cli-command/#transitioning-to-ga-for-compose-v2

**Comment by xanderdunn** [comment]
Yep in my testing docker compose v2 `docker compose` (no hyphen) defaulted to parallel build. Install with [these](https://docs.docker.com/compose/cli-command/#install-on-linux) instructions.
