### ISSUE TITLE
Cannot start service redis: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"sethostname: invalid argument\

### ISSUE THREAD

**Issue by hgySandy** [docker/compose#7904]
Cannot start service redis: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"sethostname: invalid argument\

**Comment by shentonfreude** [comment]
@hgySandy  I just encountered this. It turns out my hostname was 65 characters. Shortening to 64 or less fixed it.

It would be helpful if the error msg were improved to say this. I don't see any mention of size limits in the docs.
