### ISSUE TITLE
Cannot override the specified file on volumes

### ISSUE THREAD

**Issue by midoridge** [docker/compose#7908]
I updated docker to 19.03.13 a few days ago.
After that, cannot override the specified file on volumes.

Summary of docker-compose.yml is the following
```
version: '3'

services:
  app:
    volumes:
      - ./app/html:/var/www/html
      - ./app/env.dev:/var/www/html/.env
```

./app/html has .env file. 
Before updating docker, it was override .env file by ./app/env.dev. But now cannot override it.
Docker or docker-compose are change specification or have some bugs?

My environment is the following.

docker version
```
Client: Docker Engine - Community
 Cloud integration: 1.0.1
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

docker-compose version
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by midoridge** [comment]
Additional information.

https://docs.docker.com/docker-for-mac/release-notes/
Docker Desktop Community 2.5.0.0 => Don't work (cannot override file on directory)
Docker Desktop Community 2.4.0.0 => work (can override file on directory)

**Comment by andryyy** [comment]
Can confirm that this stopped working for me, too.

**Comment by midoridge** [comment]
I posted the same issue to docker-for-mac https://github.com/docker/for-mac/issues/5053
Because Both Docker Desktop 2.4.0.0 and 2.5.0.0 has the same docker-compose version 1.27.4, build 40524192 but 2.5.0.0 does not work. I think Docker Desktop (docker-for-mac) has some bugs about it.
