### ISSUE TITLE
Networking During Build Time?

### ISSUE THREAD

**Issue by dm17** [docker/compose#7911]
Docker's build has "--network" which seems to allow networking during build time:
https://docs.docker.com/engine/reference/commandline/build/

Is there a way to get networking (in my case between already running containers) during another container's build time?
Thanks!

**Comment by dm17** [comment]
Nowhere to be found in docker-compose documentation, it seems :(

**Comment by dm17** [comment]
@delvalle Considering your "dockerize NextJS" articles, maybe you have some idea how to dockerize after using this feature, which requires networking between services during build time: 
https://nextjs.org/docs/advanced-features/automatic-static-optimization

**Comment by thaJeztah** [comment]
@dm17 it's in the compose-file documentation; https://docs.docker.com/compose/compose-file/#network

<img width="562" alt="Screenshot 2020-11-06 at 16 53 11" src="https://user-images.githubusercontent.com/1804568/98386526-94bfc380-2050-11eb-87d7-5e6e26ab0700.png">

**Comment by dm17** [comment]
> @dm17 it's in the compose-file documentation; https://docs.docker.com/compose/compose-file/#network
> 
> <img alt="Screenshot 2020-11-06 at 16 53 11" width="562" src="https://user-images.githubusercontent.com/1804568/98386526-94bfc380-2050-11eb-87d7-5e6e26ab0700.png">

So that network is available *at* build time? @thaJeztah - I've not been able to get it to work. Can I give it access to the network from the primary docker-compose network section that way?
```
networks:
  default:
   external:
      name: traefik
```

**Comment by dm17** [comment]
Seems the answer to my question is yes :) That worked! Thanks :)

**Comment by dm17** [comment]
@thaJeztah I guess one sort of related question: is there a way to use depends_on such that some services are running @ another service's build time?
If not, then I suppose the best way is:
```
docker-compose build some_services
docker-compose up -d some_services
docker-compose build the_rest
```
Thoughts?

**Comment by dm17** [comment]
For anyone wondering... the network name during build time in docker-compose is not ```network1``` from the session below, but actually ${NETWORK}.

```
networks:
  network1:
    external:
      name: "${NETWORK}"
```

**Comment by thaJeztah** [comment]
> For anyone wondering... the network name during build time in docker-compose is not network1 from the network section below, but actually ${NETWORK}.

Hmmm... good one; might be good to open a bug-report for that in https;//github.com/docker/compose/ or in https://github.com/docker/compose-cli. For consistency, I think it should _first_ try to find a network defined in the stack (and _possibly_ fall back to using the network-name as a literal name)

**Comment by thaJeztah** [comment]
LOL, just realise this is the compose repository

**Comment by dm17** [comment]
> LOL, just realise this is the compose repository

Ah, so if people discussing here think it should be a bug, then we can re-open or make a new bug report? To me 50% of all software is a bug because it doesn't behave like my intuition says it should - and I'm not a docker-compose expert yet ;)

**Comment by dm17** [comment]
> > For anyone wondering... the network name during build time in docker-compose is not network1 from the network section below, but actually ${NETWORK}.
> 
> Hmmm... good one; might be good to open a bug-report for that in https;//github.com/docker/compose/ or in https://github.com/docker/compose-cli. For consistency, I think it should _first_ try to find a network defined in the stack (and _possibly_ fall back to using the network-name as a literal name)

When I add -labels to docker-compose build context, then they seem to create layers... I was hoping to pass labels that inform networking in docker-compose, like I do outside of the build context. Is that possible?
Thanks.

**Comment by tribals** [comment]
> @dm17 it's in the compose-file documentation; https://docs.docker.com/compose/compose-file/#network

Probably now it is https://docs.docker.com/compose/compose-file/compose-file-v3/#network

**Comment by dm17** [comment]
> > @dm17 it's in the compose-file documentation; https://docs.docker.com/compose/compose-file/#network
> 
> Probably now it is https://docs.docker.com/compose/compose-file/compose-file-v3/#network

Ya, it has been working for me for a while - just wasn't clear how to do it at first. Also, frameworks like nextjs really don't jive with Docker for this reason ( https://github.com/vercel/next.js/discussions/16995 ).

**Comment by brianhenryhf** [comment]
I found this thread useful. Just to note - the compose build-time network setting documentation is currently here: https://docs.docker.com/reference/compose-file/build/#network 

(FWIW, I was only able to get a value of 'host' working, rather than any pre-existing compose-provided network name, or a custom one provided at the top level 'networks' key in the compose file, with a buildx-backed build. But that happened to work well enough for me to let one building service access other running services, by routing requests from inside the builder to `localhost` on the host, with the running services ports mapped on the host. So, a wacky "from guest, to host, to guest" convoluted path.)

**Comment by kiler129** [comment]
I believe the documentation may be wrong with this one:

<img width="647" height="512" alt="Image" src="https://github.com/user-attachments/assets/67ab174b-16de-445f-b9e6-fa01fbec3a74" />

Attempting to use externally-defined network results in:
```
% docker compose -f docker-compose.yaml.ngcfg up
Compose can now delegate builds to bake for better performance.
 To do so, set COMPOSE_BAKE=true.
[+] Building 0.0s (0/0)                                                                                                                                                                          docker:default
network mode "net-ingress-wan" not supported by buildkit - you can define a custom network for your builder using the network driver-opt in buildx create
```
