### ISSUE TITLE
Implement service profiles in Compose 

### ISSUE THREAD

**Issue by chris-crone** [docker/compose#7919]
Now that [service profiles are part of the Compose spec](https://github.com/compose-spec/compose-spec/pull/110), we should implement them here.

**Comment by tablatronix** [comment]
Are there docker specific docs for this, or should we just reference compose-spec ?

**Comment by chris-crone** [comment]
At the moment I think we only have the spec that describes this. We do need docs so I'll add that to our backlog. Thanks for calling this out @tablatronix !

**Comment by acran** [comment]
@tablatronix @chris-crone in https://github.com/docker/docker.github.io/pull/11844 I already created a draft to add this with some examples to the `docker-compose` docs, waiting for feedback.

**Comment by chris-crone** [comment]
@acran Thanks, not sure how I missed that. I gave it a quick review.
