### ISSUE TITLE
docker-compose build fails in rootless environment

### ISSUE THREAD

**Issue by gertvanantwerpentno** [docker/compose#7922]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           master-dockerproject-2020-11-06
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        b07e921289
 Built:             Fri Nov  6 23:52:51 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          master-dockerproject-2020-11-06
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b5ea9ab
  Built:            Fri Nov  6 23:56:47 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.1
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  test:
    build:
      context: /home/gert/dockertest/testje
      dockerfile: Dockerfile
    image: testjegva
    user: 0:0
version: '3.8'
```

## Steps to reproduce the issue

1. In "testje" is only a Dockerfile, containing: FROM busybox
2. I am running rootless-docker with userid 81525 (which is > 65536, which maybe caused the error)
3. docker-compose build

### Observed result
ERROR: Error processing tar file(exit status 1): lchown /Dockerfile: invalid argument
When I trace the dockerd, I see it doing a fchown("/Dockerfile",81525,1250,AT_SYMLINK_NOFOLLOW) -> -1
Why is it doing a fchown of this file? The dockerd is already running with the right user, so the file will already have the right owner. Note, I am running in rootless mode, so outside docker 81525 is inside docker 0.
### Expected result
I expect a normal build.
### Stacktrace / full error message

```
ERROR: Error processing tar file(exit status 1): lchown /Dockerfile: invalid argument
```

## Additional information
Running Ubuntu-18.04

**Comment by oToToT** [comment]
I found that if we run docker-compose with rootlesskit (like `docker-compose build`), then it works perfectly.

**Comment by gertvanantwerpentno** [comment]
What is your uid? On my system it also works perfectly, but on systems where my uid > 65536 I had this problem.

**Comment by oToToT** [comment]
@gertvanantwerpentno my real uid is 69031 on my system. It is greater than 65536, though.

**Comment by gertvanantwerpentno** [comment]
What is the range you have in the /etc/subuid file? I had the problem when the uid not fits in that range

**Comment by oToToT** [comment]
@gertvanantwerpentno  
Sorry, I'm not familiar to subuid mechanism, but I guess this is my /etc/subuid `ototot:1106509824:65536` about my account.  
What does uid not fits in that range means?

Thanks.

**Comment by gertvanantwerpentno** [comment]
The middle number is the start of the user-id range you get inside the docker namespace.
The 65536 is the number of user-id’s you can use.
I had the problem in cases where my outside UID was larger than the last number.
But I am not sure docker-compose is the source of the problem.

**Comment by oToToT** [comment]
According to your statement, it seems like I have my outside UID be 69031 which is larger than the last number (65536), but it works great for me.  
Maybe this is helpful for those who wants to solve this problem.

**Comment by gertvanantwerpentno** [comment]
I will see what I can do to find a more precise condition why it happens to me.

**Comment by gertvanantwerpentno** [comment]
I can still reproduce the problem, using newest rootless docker and docker-compose:

docker-compose 1.27.4
docker 20.10.1
debian-10
username: test (uid=80000)
/etc/subuid: test:10655536:65536

docker-compose build
Building test
ERROR: Error processing tar file(exit status 1): lchown /Dockerfile: invalid argument

**Comment by ZeePal** [comment]
I was having this error as well (uid=66644 gid=66049). I changed /etc/subuid & /etc/subgid from:
`USERNAME:100000:65535` to `USERNAME:100000:99999`

I then restarted the rootless docker service and it working now :D

Is it just adding your UID/GID onto the starting range (100000) so its overflowing perhaps?
