### ISSUE TITLE
"The image for the service you're trying to recreate has been removed"

### ISSUE THREAD

**Issue by CrimsonGlory** [docker/compose#7933]
The following error happens when the user is trying to up a service using an image from a private docker hub repo without being logged into docker hub:

> "ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing."

Maybe we could change that description to indicate that the user is not logged into docker hub:

> "ERROR: The image for the service you're trying to recreate has been removed (or the image is private and you may require 'docker login'). If you continue, volume data could be lost. Consider backing up your data before continuing."

I don't know if it is easy for compose to check weather the user is logged in in docker hub. If so, compose could show the second message only when the user is not logged in.

This was tested with the latest docker compose.

```
user@host:~/foldername$ sudo docker-compose --version
docker-compose version 1.27.4, build 40524192
user@host:~/foldername$ sudo docker-compose -f distributed.yml up -d --no-recreate worker_no_vt
WARNING: Found orphan containers (foldername_db1_1, foldername_syslog_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Pulling worker_no_vt (dockerhubuser123/foldername:worker_cg_3344)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]N
ERROR: pull access denied for dockerhubuser123/foldername, repository does not exist or may require 'docker login'
user@host:~/foldername$ sudo docker pull dockerhubuser123/foldername:worker_cg_3344
Error response from daemon: pull access denied for dockerhubuser123/foldername, repository does not exist or may require 'docker login'
user@host:~/foldername$ sudo docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: dockerhubuser123
Password:
WARNING! Your password will be stored unencrypted in /home/user/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
user@host:~/foldername$ sudo docker-compose -f distributed.yml up -d --no-recreate worker_no_vt
WARNING: Found orphan containers (foldername_syslog_1, foldername_db1_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Pulling worker_no_vt (dockerhubuser123/foldername:worker_cg_3344)...
worker_cg_3344: Pulling from dockerhubuser123/foldername
7568c21980bd: Pulling fs layer
4a9f2207c812: Downloading [>                                                  ]  110.1kB/10.8MB
6fe350d2b140: Download complete
d95a2fdc8b3d: Waiting
760eb225f9e8: Waiting
4acc342562b4: Waiting
a7903e427e3f: Waiting
44360edd3f02: Waiting
d7721ae168a3: Waiting
962c432e3e38: Waiting
8154812ac1d3: Waiting
0847dee02492: Waiting
2cbbcbace93f: Waiting
5c99f8c61911: Waiting
780a1b721474: Waiting
e6ab304bcd20: Waiting
1d7e5014f82a: Waiting
09a76902b260: Waiting
9bf84b26ef17: Waiting
166a889cbc4d: Waiting
5408056a1243: Waiting
c0f6a3cae015: Waiting
9debf7360ef6: Waiting
7235beb4b483: Waiting
9aa29cafb800: Waiting
dc8fc45e195c: Waiting
```

https://github.com/docker/compose/blob/8633939080095bc81f03b8a6a517d5c83d0dee93/compose/cli/main.py#L1077

**Comment by Anuradha4dm** [comment]
same kind of problem with me

**Comment by Mootassame** [comment]
and me

**Comment by jdsalaro** [comment]
Ditto 🤚🏼 !

**Comment by makamane** [comment]
same here

**Comment by KimJinsu66** [comment]
and me! helllpppppp

**Comment by Prateekarora1998** [comment]
This error happens when the image name (image repo name) of the dockerfile is different from the image name that you have provided in the yaml file. Change the image name to the name that you provided in your yaml file. My issue got solved by doing this. Hope it helps you too.

**Comment by ag-TJNII** [comment]
Agreed on this being a bad error message.  I've spent about an hour angrily trying to figure our how to force bypass this for use in a CE pipeline because the error lead me to believe that Compose was keeping some sort of state squirreled away after a rm that let it detect if the image changed and warn if volume data might be altered.

What was really happening was my source image just didn't exist and couldn't be pulled.  This error message should be "source image does not exist", not "If you continue, volume data could be lost."

**Comment by rongzuoliu** [comment]
Same here!

**Comment by gokul656** [comment]
Same issue with me!

**Comment by ongteckwu** [comment]
Use https://github.com/awslabs/amazon-ecr-credential-helper
Do
`brew install docker-credential-helper-ecr`
then
Place the docker-credential-ecr-login binary on your PATH and set the contents of your ~/.docker/config.json file to be:
{
	"credsStore": "ecr-login"
}
