### ISSUE TITLE
Docker-compose looks for local file when using context

### ISSUE THREAD

**Issue by zaifox** [docker/compose#7940]
## Context information (for bug reports)

```
Output of "docker-compose version"
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
Output of "docker version"
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Output of "docker-compose config"
```

## Steps to reproduce the issue

1. Create a context to a remote server, for example "docker context create remote --docker "host=ssh://user@ip" "
2. Execute a command on the remote server: "docker-compose -c remote -f /path/to/docker-compose.yml ps

### Observed result

Docker-compose looks at the local server for the docker-compose file

### Expected result

Docker-compose should look at the remote server for the docker-compose file

### Stacktrace / full error message

```
.FileNotFoundError: [Errno 2] No such file or directory: '/path/to/docker-compose.yml'
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by ulyssessouza** [comment]
Hello @zaifox!

The `docker-compose.yml` is expected to be found in the local machine, then it will be executed having the daemon targeted by the context.
