### ISSUE TITLE
Ability to list all Compose projects

### ISSUE THREAD

**Issue by danielwinter83** [docker/compose#795]
Hi, with fig I want to run multiple instances of my application which consists of two containers. To achieve that I would use the --project-name to create multiple linked containers. 
I didn't seem to find a command which would show me a list of all running fig projects. As far as I understand I would have to remember them. 
Is there any option to list all containers sorted by projects?

**Comment by thaJeztah** [comment]
No, currently there isn't such option. Fig doesn't keep a list of projects and (at this moment) only is able to find containers belonging to a project via the "naming convention"; `[project-name]_[service-name]_[instance-number]`.

However, a discussion is currently going on upstream in docker to add "meta-data" to images and containers: https://github.com/docker/docker/pull/9882

If this feature will be implemented, this would give Fig more options to identify which containers are managed/created by Fig and which "project" they belong to. I think that would also give the opportunity to list all those containers, grouped by project.

So I suggest to keep track of that issue (https://github.com/docker/docker/pull/9882) to see what happens.

**Comment by jhirn** [comment]
+1 for this. My development workflow would greatly benefit from this.

**Comment by dnephin** [comment]
Now that we have labels for projects, I think this would be possible.

**Comment by daveisfera** [comment]
This would be a nice feature to have so can the `stale` label be removed?

**Comment by daveisfera** [comment]
It looks like the info is available so this should be a relatively simple addition:
https://gist.github.com/mortenson/538027ef218a52e190be7b9b2c17a3ca

**Comment by daveisfera** [comment]
This is still an issue

**Comment by selurvedu** [comment]
I currently use the following command to list all Compose projects:
```
alias compose-ps="docker ps --format 'table {{ .Names }}\t{{ .Status }}\t{{ .Label \"com.docker.compose.project\" }}\t{{ .Label \"com.docker.compose.service\" }}\t{{ .Label \"com.docker.compose.project.working_dir\" }}'"
```
But I still would like to see this feature properly implemented in Docker-Compose itself.

**Comment by BeatLink** [comment]
Can this issue be reopened please?

**Comment by pirate** [comment]
bump
