### ISSUE TITLE
Why is docker compose such a pile of wank?

### ISSUE THREAD

**Issue by Cally99** [docker/compose#7950]
I've worked with docker compose for over a year. 
I've never worked with such a buggy piece of shit software in all my life.
I built a multi container app using separated frontend, backend, database background tasks and other services.
I've spent about that time watching shitty dependancies install. 
The  documentation sucks ass. This is great if our a dev in a job and  want a  career in fixing shitty issues over and over again and hampering feature driven development. This whole program is why devops is important. What a load of wank. 

On my app I have read timeouts and 1.9gb of software built and probably cached in images and containers.
the use case for web development doesn't exist. Stay away. Pile of abandonware. Only useful for Enterprise companies managing blue chip stacks.

**Comment by Cally99** [comment]
All your like you'll spend doing this
docker system prune
docker volume prune
docker image prune   --- wait why the fuck is does your shitty software get mixed up with images and volumes when most projects use the same fucking name? docker compse best practices don't exist. 
You spend your whole life running 
docker-compose up --build --force-recreate to get file changes. 

Documentation on your site is total shite and it takes a month to build a fucking project.
Anyone seeing this if you want to spend your whole life waiting to see your own file changes take this solution up.

**Comment by Cally99** [comment]
401 issues open speaks for itself. Docker is abandonware.

**Comment by lmmattr** [comment]
If you want to whinge, go to Reddit. If you want to use something else, you are welcome to. But don't raise pointless issues on a platform where the rest of us are here to help make software better.

**Comment by devZer0** [comment]
i have to confirm that @Cally99 is right what he says. imho, this is severly broken software. it really sucks.

debuggging for half of the day now to find a solution for docker-compose not working correctly via ssh,  to help one of our developers to get things running in jenkins....

getting compose.parallel.feed_queue: Pending: set() in a loop ,  COMPOSE_PARALLEL_LIMIT not working,  paramiko transport layer using ssh mulitplexing by default and no way to influence it's behaviour,   tons of unresolved bugreports , closed by stale-bot.....

sorry, but this is no fun, will have a look if we can replace this....

**Comment by Ethorbit** [comment]
At times this can be the hardest, buggiest and most frustrating software to deal with especially when complex multi-container projects are involved.
