### ISSUE TITLE
the docker-compose arm based releases are missing

### ISSUE THREAD

**Issue by hillbilly-mark** [docker/compose#7954]
I can't seem to find the arm based docker-compose files.   i can only find x86 files.   Can you, please, point me to where they are hidden?  Thanks!

**Comment by rofrano** [comment]
Those of us who are developing with virtual machines on Apple M1 Silicon Macs need a `Linux-aarch64` build. I run my development environments using vagrant and docker on arm base Linux on my M1 Mac mini and I desperately need a docker-compose build for arm64 Linux machines.

**Comment by draeath** [comment]
This is also needed for users on platforms such as the Raspberry Pi 4.

Trying to be clever and use [run.sh](/docker/compose/blob/master/script/run/run.sh) fails with such:

    rp4test:~$ docker-compose -h
    WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
    standard_init_linux.go:219: exec user process caused: exec format error
    failed to resize tty, using default size

Adding the `--platform` argument still fails, just differently:

    rp4test:~$ DOCKER_RUN_OPTIONS='--platform linux/arm64/v8' docker-compose -h
    Unable to find image 'docker/compose:1.29.1' locally
    1.29.1: Pulling from docker/compose
    Digest: sha256:0c7eb11756b6f13577fa4424335f3d7209cfbb06c36d62174ad1ab8048d4e68a
    Status: Image is up to date for docker/compose:1.29.1
    docker: Error response from daemon: image with reference docker/compose:1.29.1 was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd64.
    See 'docker run --help'.

**Comment by rofrano** [comment]
I posted this question on the docker-compose Slack channel and was told that I can `pip install docker-compose` which I was completely unaware of. This worked perfectly for my arm64 Linux environments on Apple M1 Silicon so I actually have a solution now. @hillbilly-mark Hope this might help you out too.

**Comment by ndeloof** [comment]
Compose v2 includes binaries for ARM https://github.com/docker/compose-cli/releases/tag/v2.0.0-beta.3
