### ISSUE TITLE
Environment variables with blank values are omitted

### ISSUE THREAD

**Issue by avdi** [docker/compose#7955]
Occasionally, it is significant for an environment variable to be explicitly set-to-blank, as opposed to unset. docker-compose appears not to support this case.

### Description of the issue

**Expected**

Given a docker-compose.yml containing:

```yaml
services:
  app:
    environment:
      HONEYCOMB_WRITE_KEY: ""
```
or

```yaml
...
HONEYCOMB_WRITE_KEY: 
```

Then in the app container, `HONEYCOMB_WRITE_KEY` should be set to the blank string. Equivalent to executing:

```shell
$ export HONEYCOMB_WRITE_KEY=""
```

**Actual**

`HONEYCOMB_WRITE_KEY` is omitted from the container environment.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by UlrichEckhardt** [comment]
According to https://github.com/compose-spec/compose-spec/blob/master/spec.md#environment, the second of your examples seems not a bug. It says

> Environment variables MAY be declared by a single key (no value to equals sign). In such a case Compose implementations SHOULD rely on some user interaction to resolve the value. If they do not, the variable is unset and will be removed from the service container environment.

Note that the "user interaction" which this refers to probably means "take from the calling environment". In any case, it would be interesting whether a similarly named variable is set in your environment and what it's value is.

**Comment by avdi** [comment]
> According to https://github.com/compose-spec/compose-spec/blob/master/spec.md#environment, the second of your examples seems not a bug. 

I'm OK with this. I still think the first example resulting in environment variable removal is both quite surprising and problematic for the (occasional) case where some tool or library considers set-to-blank to be significant.

**Comment by UlrichEckhardt** [comment]
Using docker-compose 1.29.2 now with
```
environment:
    FOO: ""
    BAR:
```
I get `FOO` set to an empty string and `BAR` set to whatever is in the environment of `docker-compose up`.

In other words, this bug seems to have been fixen in some version in between 1.27.4 ad 1.29.2.
