### ISSUE TITLE
How to start on reboot on Ubuntu?

### ISSUE THREAD

**Issue by evgenyneu** [docker/compose#796]
I tried putting the following script into `/etc/rc.local`, but it did not start docker when I rebooted the system.

```
FIG_FILE=/my_app/fig.yml fig start
```

Thanks

**Comment by thaJeztah** [comment]
Is docker *itself* not starting upon reboot, or are your *containers* not started?

To have Docker automatically restart your containers, I think you'll be looking for docker restart policies (https://docs.docker.com/reference/commandline/cli/#restart-policies). The *current* release of Fig doesn't support that yet, but it has been merged into master (see https://github.com/docker/fig/pull/594) and is scheduled for Fig 1.1

**Comment by dnephin** [comment]
No response from OP, and this issue is really outside the scope of compose (it's up to docker or the init system to start things on boot/reboot.
