### ISSUE TITLE
Document passing project from stdin

### ISSUE THREAD

**Issue by metametadata** [docker/compose#7966]
**Is your feature request related to a problem? Please describe.**
Even though it's a common convention, it's not obvious that stdin can be used instead of the physical file. I.e. that `--file -` works.

**Describe the solution you'd like**
`--file` option description in `docker-compose help` should mention that `-` means `stdin`.

Maybe update the official documentation too.

**Describe alternatives you've considered**
There're none.

**Additional context**
docker-compose version 1.27.4

**Comment by rodrigoaguilera** [comment]
You can also use `--file /dev/stdin`. I think that will look more illustrative for the help

**Comment by metametadata** [comment]
up

**Comment by ndeloof** [comment]
support for `-` is documented on https://docs.docker.com/engine/reference/commandline/compose/
