### ISSUE TITLE
The same directory names conflict

### ISSUE THREAD

**Issue by sandweel** [docker/compose#7969]
## Description of the issue
Bug with duplicate container labels which created by docker-compose.

## Context information (for bug reports)
Example:
I have 2 docker-compose projects (test1 and test2)

docker-compose.yaml has different container_name, image. Example:
**test1**

version: '3'
services:
    php:
        image: company/test1-phpfpm7.2
        container_name: test1_master_php

**test2**
version: '3'
services:
    php:
        image: company/test2-phpfpm7.2
        container_name: test2_master_php

Docker-compose.yaml files placed:
**test1** - /root/test1/master
**test2** - /root/test2/master

I'm creating docker container inside /root/test1/master (test1 project). Then when I'm trying to docker-compose up I'm getting **WARNING: Found orphan containers (test1_master_php) for this project.**

Also when I destroying  containers for test2 it will destroy containers for test1. For test1 the same situation. Docker-compose will destroy containers for test2.
So docker-compose think that test1 and test2 the same projects.

I found that labels which created by docker-compose has: 
            "Labels": {
                "com.docker.compose.config-hash": "feb4aa9caa54aca1c2e7dd316134daa9aee120c09ff86914ff2e84b53bf0be4b",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "master",  =====> this label the same for the both projects 
                "com.docker.compose.service": "php",
                "com.docker.compose.version": "1.23.2"
            }
When test1 container is created and when I'm trying to create test2 container, docker-compose found than container with label key **com.docker.compose.project** and label value **master** already exist and think that it is the same container.
When I rename directory from **master** to **something else** everything is works fine because label above has unique value.

How I can create containers for 2 project which has endpoint directory named **master**?

Software:
Docker-compose - **docker-compose version 1.23.2, build 1110ad01**
Docker Engine - **Docker version 19.03.3, build a872fc2**
OS - **Ubuntu 16.04.6 LTS**

**Comment by rumpl** [comment]
By default the project name is the current directory name, you can change that with the `--project-name` flag.

```
  -p, --project-name NAME     Specify an alternate project name
                              (default: directory name)
```

**Comment by your-diary** [comment]
possible duplicate of

- https://github.com/docker/compose/issues/5104
