### ISSUE TITLE
fig build: no logs are progress indication

### ISSUE THREAD

**Issue by olalonde** [docker/compose#798]
When running `fig build web`, I am not getting any logs from docker even with the `--verbose` flag.

The expected behaviour would be to see the normal output of `docker build`.

**Comment by aanand** [comment]
You should definitely be seeing output. Can you paste your fig and docker versions and a minimal failing `fig.yml` and `Dockerfile`?

**Comment by dnephin** [comment]
We don't have enough information to triage this issue, and it hasn't been reported again, so closing it.
