### ISSUE TITLE
Integrate compose into docker repositories

### ISSUE THREAD

**Issue by tarfeef101** [docker/compose#8011]
## Problem
`docker-compose` is updated fairly regularly, but since the method of distribution (especially in mainstream distros like ubuntu/debian, rhel) is just "download it from github and put it into your path", it's difficult to keep up to date.

## Proposed Solution
Docker already maintains repos at `https://download.docker.com/linux/` for distributing the core components of Docker. It'd be fantastic if compose was included in there, so we can use our package managers to keep up to date.

## Alternatives
Efforts could be made to keep packages in distro's main repos (e.g. I believe AUR for arch has someone maintaining a compose package), or users could be expected to script their own methods to keep things up to date in the current setup. These are not as ideal though, in my opinion.

**Comment by ndeloof** [comment]
With Compose v2 implemented as a CLI plugin, we should be able to get compose included in the docker-ce system packaging, like we do for other official CLI plugins

**Comment by MAFLO321** [comment]
@ndeloof any updates on this?

**Comment by ndeloof** [comment]
I'm only maintainer on docker/compose, I'm not involved in docker-ce packaging.
Maybe @thaJeztah can give us an update?

**Comment by MAFLO321** [comment]
I think this can be closed:
- https://docs.docker.com/engine/release-notes/#201013
- https://github.com/docker/docker-ce-packaging/pull/638
