### ISSUE TITLE
Add build:cli_args to spec to remove strict coupling with CLI builds

### ISSUE THREAD

**Issue by ppg** [docker/compose#8015]
**Is your feature request related to a problem? Please describe.**
Features and options are added to the CLI for `docker build` and then support must be manually added to `docker-compose` to allow configuring those new features and options. This minimally leads to some delay, but can also lead to very long delays; in addition some items might never make it into the compose spec since they are not popular enough, or don't have clear compatibility with the docker client build mode. As a concrete example `docker build` via buildkit has supported the `--ssh` flag for a while, which is extremely useful for anyone using private repositories for go, python, node, etc. packages. However, support for that has yet to make it into `docker-compose` multiple years later. See https://github.com/docker/compose/issues/7025 and the various other issues linked or related to that to get an appreciation for how much pain that causes and how long it has been an issue.

**Describe the solution you'd like**
While it is nice to add first-class support for new features, especially ones that can be supported on docker client builds, those will always suffer from  playing catch up with `docker build`. Instead it seems like it would be very useful to have an option in the compose file to pass in arbitrary CLI options for `docker build` so a person could take advantage of new functionality as soon as it is added. The exact names and schema of that configuration seem like they could be tweaked, but I made a prototype implementation to prove to myself that it would work:
https://github.com/docker/compose/compare/master...TheJumpCloud:cli-args

This isn't handling non-CLI builds yet as I'm not sure the best way to split that given how the client vs. CLI build is handled as essentially an interface: https://github.com/docker/compose/blob/master/compose/service.py#L1106. However, as it is now I can simply add this snippet to a docker-compose file and solve the litany of woes people have had around build-time secrets, including `--ssh default`:
```
build:
  cli_args:
    - --ssh
    - default
```

This avoids, or perhaps rather allows, debate about how to add in first-class configuration for new options to progress at an appropriate speed, but still let's uses adopt the new features when they are read. I think this pattern would mean that anyone could adopt _any_ new `docker build` functionality on day 0 going forward.

**Describe alternatives you've considered**
There are various PRs that try to solve for a particular configuration shortcoming; for example the SSH issue already referenced has various approaches in  https://github.com/docker/compose/pull/7997, https://github.com/docker/compose/pull/7046 and https://github.com/docker/compose/pull/7296. I don't think this proposal is mutually exclusive from any of those: the compose spec can still have well defined configuration for things that are broadly adopted, but `build:cli_args` can act as an early adoption as well as escape valve for those that aren't useful or standardized enough to be promoted to a first class `build` configuration option, or are taking a while to get there.

**Additional context**
In terms of the impact, I'm not sure what other people have done, but we've essentially been forced to introduce a pre-build step that runs `docker build` directly with options such as `--ssh default` and then run `docker-compose build` after that. It breaks and confuses a bunch of stuff like multi-staged builds, as well as introduces a custom pattern outside the normal docker/docker-compose workflows. With something like `build:cli_args` we could have decided as an org to move to buildkit + that SSH option whenever we wanted, instead of having to construct this brittle workaround.

**Comment by zoonage** [comment]
Implementing this would be a lot easier to test in #7997 currently I have no idea how to test SSHing

**Comment by zoonage** [comment]
py-docker doesn't let you pass through arbitrary args, so I think this is only possible using the CLI builder

**Comment by ppg** [comment]
> py-docker doesn't let you pass through arbitrary args, so I think this is only possible using the CLI builder

I believe this is true; to clarify, the issue with my branch is that the way the code picks the CLIBuilder or client builder means that you can't easily passe a kwarg that is supported by one but not the other. That's definitely solvable, I just didn't want to go ripping apart code without some advice on how the maintainers would like to handle that situation.

**Comment by ppg** [comment]
Found https://github.com/docker/compose/pull/7835 which is similar branch to the one I have listed in the description.
