### ISSUE TITLE
Cannot get docker-compose up to work like a docker equivalent

### ISSUE THREAD

**Issue by zstadler** [docker/compose#8022]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E720FBB9-5C17-47BB-9B7A-41418087857F/20210104063434

### Expected behavior
With this `docker-compose.yml` file
```
version: "2"
services:
  tileserver-gl:
    image: "maptiler/tileserver-gl"
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
```

`docker-compose run --rm tileserver-gl`
should behave the same as
`docker run --rm -v $(pwd)/data:/data -p 8080:80 maptiler/tileserver-gl`

### Actual behavior
- The `docker` command runs as expected and responds to `http://localhost:8080/` requests.
- There is no such response when using above `docker-compose` command.

This difference does not exist when running the two commands on Ubuntu 20.04

### Information

  - Windows Version: Windows 10 Pro 19042.685
  - Docker Desktop Version: 3.0.0 with WSL integration and Ubunto-20.02 distro
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - WSL Version: 4.19.128

### Steps to reproduce the behavior

  1. Upen a Ubuntu 20.04 image with WSL 2
  2. Download [issue.zip](https://github.com/docker/for-win/files/5764790/issue.zip)
  3. Unzip the abobe issue.zip in a temporary folder
  4. Run `docker run --rm --name tileserver-gl -v $(pwd)/data:/data -p 8080:80 klokantech/tileserver-gl --verbose`
  5. Wait for the `Startup complete` message
  5. Open `http://localhost:8080/` and view something like this:    
     <img width="50%" src="https://user-images.githubusercontent.com/1304610/103538684-5bb09d80-4e9f-11eb-9144-70b9bef73339.png"/>
  6. Type `Ctrl-C` to stop the docker command
  7. Run `docker-compose run --rm tileserver-gl`
  5. Wait for the `Startup complete` message
  8. Refresh the `http://localhost:8080/` page in the browser and view an "Unable to connect" error

**Comment by thaJeztah** [comment]
Does it work if you use the `--service-ports` option? By default `docker-compose run` does not publish ports (to prevent conflicts with a running compose application), so to enable port-publishing, you need to use the `--service-ports` option.

**Comment by zstadler** [comment]
It works with the `--service-ports`. Thanks @thaJeztah!

I'm still puzzled about the incompatibility with Linux where the `docker-compose run` works well without the `--service-ports` option:
> This difference does not exist when running the two commands on Ubuntu 20.04

**Comment by thaJeztah** [comment]
Glad it's resolved! You're not the first one running into this; it's by design, but I can see it could be confusing.

Perhaps `docker-compose run` should print a warning/info message if the service has ports configured 🤔 

e.g. with the following compose file;

```yaml
version: "3.8"
services:
  web:
    image: "nginx:alpine"
    ports:
      - "8080:80"
```

Doing a `docker-compose run` shows;

```console
$ docker-compose run --rm web

Creating network "repro-8022_default" with the default driver
Creating repro-8022_web_run ... done
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

Some warning log before the existing log messages could be useful, something like;

```
WARNING: Omitting published ports for service "web". Use --service-ports to publish service ports.

Creating network "repro-8022_default" with the default driver
Creating repro-8022_web_run ... done
```

That warning should only be printed if the service does map ports of course

@ndeloof @ulyssessouza WDYT?
