### ISSUE TITLE
docker-compose "up" works but "run" fails 

### ISSUE THREAD

**Issue by scrandall** [docker/compose#8024]
## Description of the issue
Trying to run a script through docker-compose fails with `Cannot connect to the Docker daemon at unix://tmp/docker.sock. Is the docker daemon running?`

## Context information (for bug reports)
This worked with docker 17, upgrading to the latest versions and I have an issue with docker run now.

**Output of `docker-compose version`**
```
docker-compose --version
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**
```
docker --version
Docker version 19.03.13, build 4484c46d9d
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
docker-compose config -f docker-compose-api.yml
Validate and view the Compose file.

Usage: config [options]

Options:
    --resolve-image-digests  Pin image tags to digests.
    --no-interpolate         Don't interpolate environment variables.
    -q, --quiet              Only validate the configuration, don't print
                             anything.
    --services               Print the service names, one per line.
    --volumes                Print the volume names, one per line.
    --hash="*"               Print the service config hash, one per line.
                             Set "service1,service2" for a list of specified services
                             or use the wildcard symbol to display all services.
```

## Steps to reproduce the issue
docker-compose

```
version: "3.8"
services:
  api:
    container_name: my_container_name
    restart: always
    image: my-registry:latest-my-image
    ports:
      - 80:8080
 ```

This works

```

ssh -M -S my-ctrl-socket -fN -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes -L /tmp/docker.sock:/var/run/docker.sock -J jumphost.mysite.com $HOST

docker-compose --host unix://tmp/docker.sock -f $docker_compose_api stop
docker-compose --host unix://tmp/docker.sock -f $docker_compose_api pull 
COMPOSE_HTTP_TIMEOUT=200 docker-compose --host unix://tmp/docker.sock -f $docker_compose_api up -d 
rm -v /tmp/docker.sock

ssh -S my-ctrl-socket -O check $HOST
ssh -S my-ctrl-socket -O exit $HOST

```

This fails with `Cannot connect to the Docker daemon at unix://tmp/docker.sock. Is the docker daemon running?`

```
ssh -M -S my-ctrl-socket -fN -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes -L /tmp/docker.sock:/var/run/docker.sock -J jumphost.mysite.com $HOST

docker-compose --host unix://tmp/docker.sock -f $docker_compose_api stop
docker-compose --host unix://tmp/docker.sock -f $docker_compose_api pull 
COMPOSE_HTTP_TIMEOUT=200 docker-compose --host unix://tmp/docker.sock -f $docker_compose_api run --rm api ./bin/script upgrade
# Get rid of the last tunnel to clean up after myself
rm -v /tmp/docker.sock

ssh -S my-ctrl-socket -O check $HOST
ssh -S my-ctrl-socket -O exit $HOST

```

### Observed result
`Cannot connect to the Docker daemon at unix://tmp/docker.sock. Is the docker daemon running?`

### Expected result
Script to run an exit

## Additional information

OS version / distribution, `docker-compose` install method, etc.

  - macOS Version: `10.15.7`

**Comment by kerbrose** [comment]
this is probably due to docker service (daemon) is not running in the background. you could resolve it from https://stackoverflow.com/q/44678725/7045119,

**Comment by scrandall** [comment]
Thank you @kerbrose, that answer is related to linux when I'm running on a mac, the daemon doesn't run on mac I believe https://github.com/docker/for-mac/issues/2267

The part that has me so confused is that "up" works but "run" wont.

**Comment by BDL70** [comment]
@scrandall did you get a fix to your problem. I'm having the same error message(curiously, immediately after upgrading to Catalina using dosdude1's Catalina patch on a 2011(late) MacBook Pro
