### ISSUE TITLE
docker-compose randomly drops SSH connection from remote host raising paramiko.ssh_exception.NoValidConnectionsError

### ISSUE THREAD

**Issue by bluesurfer** [docker/compose#8039]
## Description of the issue

Sometimes the build of `docker-compose` fails due to a random `paramiko.ssh_exception.NoValidConnectionsError` or sometimes with a classic `SSH connection refused` 

This happens only when building to a remote host using SSH and only with `docker-compose`. I am not experiencing any network issues - I tried on three different machines on three different network by setting both the `DOCKER_HOST` variable or using `docker context` with properly configured ssh keys.. nothing changed!

I noticed an odd pattern; the exception occurs :
- more frequently when many builds are subsequently made in a short period of time (like 5 seconds between two builds);
- when there is a relatively big stack (with 8 services the error occurs when building the sixth service). 

It almost looks like that there exists some sort of limit in the SSH sessions - Yes.. I have already changed the `MaxSessions` option inside `/etc/ssh/sshd_config` and `service ssh restart` on the remote host but that does not solve this error and the most annoying fact is that it seems to be absolutely **random**.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 164, in __init__
  File "site-packages/docker/transport/sshconn.py", line 113, in __init__
  File "site-packages/docker/transport/sshconn.py", line 121, in _connect
  File "site-packages/paramiko/client.py", line 368, in connect
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 1.2.3.4
```
or more rarely:

```
failed to dial gRPC: command [ssh -l root -- 1.2.3.4 docker system dial-stdio] has exited please make sure the URL is valid,
and Docker 18.09 or later is installed on the remote host: stderr=ssh: connect to host 1.2.3.4 port 22: Connection refused
```

## Additional information

Local host: Mac OS X Big Sur - docker-compose 1.27.4
Remote host: Digitalocean "One click Docker" droplet running Ubuntu 20.04.1 LTS and docker-compose: 1.27.4

**Comment by mauryquijada** [comment]
+1, also experiencing this

**Comment by mauryquijada** [comment]
For anyone interested, I ended up using a workaround. Instead of connecting to the Droplet using SSH, I connected using the HTTP API. This involves the following (adapted from [this source](https://blog.usejournal.com/how-to-enable-docker-remote-api-on-docker-host-7b73bd3278c6)):
- `vi /lib/systemd/system/docker.service`
- Adding `-H=tcp://0.0.0.0:2375` to the `ExecStart` command
- `systemctl daemon-reload && service docker restart`

Then, on your local computer, you can add a new context with `docker context create --docker="host=tcp://[your hostname]:2375" remote`. Finally, you can build with `docker-compose --context remote up --build`.

**Comment by bluesurfer** [comment]
@mauryquijada **maybe** I fix this by following:

https://www.digitalocean.com/community/questions/ssh-connection-drops-too-frequently

https://github.com/docker/compose/issues/7542#issuecomment-743138898

**Comment by brain2dump** [comment]
In my case this problem has been resolved by moving privet key from ssh-agent (keepass2 plugin) to ~/.ssh directory.  It is possible that the ssh-agent does not adequately respond to a large number of requests.
