### ISSUE TITLE
docker-compose 1.28.0 fails on Ubuntu 18.04: "version `GLIBC_2.28' not found"

### ISSUE THREAD

**Issue by albers** [docker/compose#8048]
## Description of the issue
On Ubuntu 18.04, docker-compose fails with 

>  docker-compose --version
[13] Error loading Python lib '/tmp/_MEIn9gFoA/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIn9gFoA/libpython3.9.so.1.0)

On the same machine, docker-compose 1.27.4 works as expected.

## Steps to reproduce the issue

Build an image with both versions of docker-compose installed:

```Dockerfile
FROM ubuntu:18.04
RUN apt update
RUN apt install curl -y
RUN curl -L -o /usr/local/bin/docker-compose-1.28.0 \
    https://github.com/docker/compose/releases/download/1.28.0/docker-compose-Linux-x86_64
RUN curl -L -o /usr/local/bin/docker-compose-1.27.4 \
    https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
RUN chmod +x /usr/local/bin/docker-compose-*
```

```bash
docker build --tag ubuntu:18.04-compose .
docker run --rm -it ubuntu:18.04-compose
```

Then, run both versions of docker-compose inside the image:
```bash
root@115848dbd647:/# docker-compose-1.27.4 --version
docker-compose version 1.27.4, build 40524192
root@115848dbd647:/# docker-compose-1.28.0 --version
[13] Error loading Python lib '/tmp/_MEIn9gFoA/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIn9gFoA/libpython3.9.so.1.0)
```
## Additional information

This issue was demonstrated in a Docker image for easier reproducability.
It also exists on a full desktop edition of Ubuntu 18.04 that was created with

```bash
vagrant init fasmat/ubuntu1804-desktop
vagrant up
```

**Comment by chris-crone** [comment]
Thanks for reporting this @albers

The issue comes from our Python bump. The official images only provide Debian Buster for 3.9 and not Jessie. The former has glibc 2.28 while Ubuntu 18.04 only has 2.27.

I guess the fix is to build with Jessie and get Python elsewhere or build it as part of the process

**Comment by andryyy** [comment]
It's also broken in CentOS 7 and Stretch.

**Comment by chris-crone** [comment]
We historically haven't shipped CentOS 7 builds because it uses an ancient glibc. There is the ability to build for it in the Dockerfile though.

Debian [Stretch is EOL](https://wiki.debian.org/DebianReleases).

**Comment by andryyy** [comment]
Stretch is LTS from July 6, 2020 to June 30, 2022. C7 is also in support, but I understand it's rather old. :)

**Comment by vvucetic** [comment]
It doesn't work on Amazon LInux 2 either. `1.27.4` works fine.

**Comment by rikostave1234** [comment]
I am experiencing the same problem on Amazon Linux 2. I understand that older CentOS versions and apparently also Amazon Linux ship with an outdated version of glibc. Can we still expect some sort of fix for this, or are these OS's considered unsupported?

**Comment by skaven81** [comment]
+1, we noticed this at my Fortune 500 company.  Rolled back to 1.27.4 and we're good.  But this is really disappointing for Docker to be so cavalier about changing the build dependencies.

**Comment by jonghwanhyeon** [comment]
I think we can use the container version of `docker-compose` until this issue is resolved. 
```bash
sudo curl -L --fail https://github.com/docker/compose/releases/download/1.28.0/run.sh -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

**Comment by matebook14** [comment]
> 它也在 Centos 7 和拉伸中损坏了。

Has it been resolved?

**Comment by chris-crone** [comment]
I've put up #8058 to resolve this. The decision was to drop back to Python 3.7 so that we can continue using the official Python images for the build. The other option would've been to build Python 3.9 on one of these older distros but that feels more risky.

@andryyy It is indeed LTS but Debian LTS is not the same as Ubuntu LTS, see some discussion here: https://github.com/docker/docker-ce-packaging/pull/476

**Comment by andryyy** [comment]
Yes, you are correct. :) Thanks for the change!

**Comment by EricHripko** [comment]
Seeing the same in my environment 👍

**Comment by chris-crone** [comment]
If you're really impatient, you can build from source using:
```
docker buildx build --build-arg DISTRO=centos --output . --target bin https://github.com/docker/compose.git\#1.28.0
```

That will output a `docker-compose-linux-amd64` to your current working directory.

I haven't tested it except doing a `docker-compose --version` in a CentOS 7 container.

**Comment by BretFisher** [comment]
On Ubuntu 18.04, I removed the binary and installed via pip and it worked (assuming you have python3 installed):

`sudo pip3 install docker-compose`

**Comment by BretFisher** [comment]
@nickjj has a great post on the difference with what's happening when you use the binary vs. pip versions https://nickjanetakis.com/blog/docker-tip-74-curl-vs-pip-for-installing-docker-compose

**Comment by dsteinkopf** [comment]
@BretFisher Thank you very much - that helped me quickly. As ansible is mentioned in your link here is my playbook - just to show it is really easy and straightforward (last lines optional):
```
    - name: fetch and install docker-compose via pip
      pip:
        name: docker-compose
        executable: pip3
      when: docker_install|default(true)
      tags: docker-install-docker-compose
```

**Comment by CaiWenlie** [comment]
> I think we can use the container version of `docker-compose` until this issue is resolved.
> 
> ```shell
> sudo curl -L --fail https://github.com/docker/compose/releases/download/1.28.0/run.sh -o /usr/local/bin/docker-compose
> sudo chmod +x /usr/local/bin/docker-compose
> ```

@jonghwanhyeon Thx! this works well!

**Comment by cuongnd-scs** [comment]
Got same issue on amz linux 2, while version 1.27.0 worked well.

```
sudo curl -L "https://github.com/docker/compose/releases/download/1.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

**Comment by albers** [comment]
I confirm that the issue is fixed in 1.28.2. Thank you!

**Comment by andryyy** [comment]
Yes, thank you!

I promise to update those old servers soon anyway... 😄

**Comment by johnthagen** [comment]
This is related to https://github.com/docker-library/python/issues/428. One thing that would help for situations like this is if the official Python Docker images provided newer Python releases for older Debian releases: https://github.com/docker-library/python/issues/428

**Comment by chris-crone** [comment]
@johnthagen yes, that would've helped in this case. We aren't using any Python 3.8 (or later) features in `docker-compose` though.

The other route is to use the `docker<space>compose` support that we're adding to the Docker CLI (see: https://github.com/docker/compose-cli). On Windows and macOS this is included in Docker Desktop. We are still working on a good way to get this to Linux users.

**Comment by johnthagen** [comment]
@chris-crone Thanks for the update. Out of curiosity, is the long term plan that `compose-cli` (written in Go) will replace `docker-compose`?

**Comment by chris-crone** [comment]
> Out of curiosity, is the long term plan that compose-cli (written in Go) will replace docker-compose?

We haven't 100 % decided yet (as we need more feedback to check if we're solving all the same use cases there) but once we have the compose-cli easily available on Linux, we'd like people to give it a try!

**Comment by andryyy** [comment]
I will definitely check it out! You guys really do an amazing job, thanks!
