### ISSUE TITLE
--no-log-prefix KeyError in 1.28.0

### ISSUE THREAD

**Issue by rerpha** [docker/compose#8053]
## Description of the issue
I am getting this error when running `up()` on windows 10: 

```
Traceback (most recent call last):
  File "C:\Instrument\Dev\system_tests\test_datastreaming.py", line 167, in setUpClass
    start_kafka()
  File "C:\Instrument\Dev\system_tests\test_datastreaming.py", line 125, in start_kafka
    cmd.up(docker_options)
  File "C:\Instrument\Dev\system_tests\my_venv\lib\site-packages\compose\metrics\decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "C:\Instrument\Dev\system_tests\my_venv\lib\site-packages\compose\cli\main.py", line 1124, in up
    keep_prefix = not options['--no-log-prefix']
KeyError: '--no-log-prefix'
```
`cmd` is
```python
    project = project_from_options(os.path.dirname(__file__), docker_options)
    return TopLevelCommand(project)
```

`docker_options` is set to:

```python
    docker_options = docker_default_options
    docker_options["--project-name"] = "kafka"
    docker_options["--file"] = [r"docker_images\docker-compose-kafka.yml"]
```

and `docker_default_options`:

```python
{
    "--no-deps": False,
    "--always-recreate-deps": False,
    "--scale": "",
    "--abort-on-container-exit": False,
    "SERVICE": "",
    "--remove-orphans": False,
    "--no-recreate": True,
    "--force-recreate": False,
    "--no-build": False,
    "--no-color": False,
    "--rmi": "none",
    "--volumes": True,
    "--follow": False,
    "--timestamps": False,
    "--tail": "all",
    "--detach": True,
    "--build": False,
}

```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
C:\Instrument\Dev\system_tests\my_venv\Scripts>docker-compose.exe version
docker-compose version 1.28.0, build unknown
docker-py version: 4.4.1
CPython version: 3.8.6
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```
**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

The compose file it's trying to run is this: 
```docker-compose
version: '3.7'

services:
  kafka:
    image: wurstmeister/kafka:1.0.0
    depends_on:
      - zookeeper
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "TEST_runInfo:1:1,TEST_events:1:1,TEST_forwarderConfig:1:1,TEST_forwarderData:1:1,TEST_monitorHistograms:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: zookeeper:3.4
```

## Steps to reproduce the issue

1. Run with above config
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information
Windows 10, pip install (latest)

**Comment by sarimak** [comment]
We observed the same issue both on latest Ubuntu and on Windows, while running any Docker image (e.g. postgres). Downgrading to 1.27.4 fixes the issue. Any version since 1.28.0-rc1 has this issue.
Suspected change: new feature "Add flag to disable log prefix" - https://github.com/docker/compose/commit/cddaa77fea2e53d7e825c2cbbb4f03f9bef58203#diff-452576c2a6c1b1db7fd4844a6b166dd37fd349c431c9bd7c941d87a6dfaffca3R1034 line 1034.

**Comment by sarimak** [comment]
We are using docker-compose from our management utility by importing compose.cli.main.
When we added ```"--no-log-prefix": False``` to options that we feed into command.up() the issue was fixed even on docker-compose 1.28.2.

**Comment by simonhir** [comment]
@sarimak do you pass `--no-deps` in your use case?

At [it is passed the same way](https://github.com/docker/compose/blob/master/compose/cli/main.py#L1114) as `--no-log-prefix` and then probably the `not` will cause this problem.

**Comment by sarimak** [comment]
Yes, we set `--no-deps` to False explicitly in the options we pass to the command. We created our tooling not that long time ago - by trial and error so we added everything that was needed at that time. Then we kept docker-compose in our requirements.txt not pinned so we upgraded to a version with a new option that "broke" our existing setup.

**Comment by sarimak** [comment]
I'm not claiming this needs to be fixed because the workaround I described works for us. But maybe it would be worth of considering to make newly added options optional with a default so existing setups won't break when they are not setting them.
