### ISSUE TITLE
Any chance of making this decent software?

### ISSUE THREAD

**Issue by Cally99** [docker/compose#8055]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JamesTheAwesomeDude** [comment]
Ah, yes—

> A clear and concise description of what the problem is.

**Comment by Motophan** [comment]
He has a point, the entire internet is using 2.x compose because no one understands GPU stanza.

**Comment by ndeloof** [comment]
closing as :trollface:
