### ISSUE TITLE
Please do not unpublish published releases/tags again (as seen with 1.28.1 today)

### ISSUE THREAD

**Issue by hartwork** [docker/compose#8074]
Hi!

I'm a big fan of docker-compose and I propagate most version bumps to Gentoo package `app-emulation/docker-compose` , often including release candidates, often within the same day of the upstream release, sometimes within hours.

What happened yesterday and today is this:
- Someone pushed a Git tag 1.28.1
- I got a notification by mail about new release 1.28.1
- I started packaging 1.28.1 for gentoo and pushed [the related commit](https://github.com/gentoo/gentoo/commit/5cdf67db3a0942dc9c5492c2991ff9308b5d0688)
- Gentoo users started installing 1.28.1
- Because so-called "distfile mirrors" take more than just a second to learn about new files to cache and obtain a copy of the upstream releases archives, distfile mirrors did not have a copy of file `docker-compose-1.28.1.tar.gz` yet so that the package manager had to pull the archive from GitHub directly, for these users
- Someone removed Git tag 1.28.1 upstream
- As a result URL https://github.com/docker/compose/archive/docker-compose-1.28.1.tar.gz started serving 404 errors rather than the original content
- Due to that everyone trying to install package `app-emulation/docker-compose` would now get errors that need manual intervention.
- Furthermore, security aware users started to get rightful shivers about what was going on because they didn't see a Git tag up here and that should trigger alarm with security minded people. See bug report https://bugs.gentoo.org/767250 for what that looks like.

So I would like to remind you that there is no thing like unpublishing releases without damage and that someone pays the price. Please make sure that everyone with permissions to push Git tags up here gets a chance to see this text. I would also ask you to not re-publish new content under the same name 1.28.1 in the future but to use say 1.28.2 for that instead, because re-using version numbers is another can of worms again (and not considered good practice).
With that said, I hope that I we can both be critical with each other and continue great mutual collaboration.

Thanks for your attention and understanding

Sebastian

**Comment by chris-crone** [comment]
Hi @hartwork!

Thanks for your feedback and thanks for building the Gentoo packages!

I completely agree that we should not be deleting tags. If we have an issue with a release, we should be doing another release with another tag. I'll make sure that we update our release process to ensure that we don't delete tags going forward!

**Comment by hartwork** [comment]
Thank you!
