### ISSUE TITLE
Behavior of relative paths for --env-file changed in v1.28.2

### ISSUE THREAD

**Issue by chapa** [docker/compose#8076]
## Description of the issue

Following up https://github.com/docker/compose/issues/8068#issuecomment-767340402.

In v1.27.4 relative paths for `--env-file` are computed from the current directory, in v1.28.2 they are computed from the `docker-compose.yaml` file location.

## Steps to reproduce the issue

Create these folder and files structure:

```
.
└── subfolder
    ├── docker-compose.yml
    └── .env
```

docker-compose.yml
```yaml
version: '3.4'
services:
    nginx:
        image: nginx:latest
        ports:
            - "${NGINX_PORT}:80"
```

.env
```
NGINX_PORT=8080
```

### Observed result

Version 1.27.4:
```
$ docker-compose -v && docker-compose -f subfolder/docker-compose.yml --env-file ./subfolder/.env config
docker-compose version 1.27.4, build unknown
services:
  nginx:
    image: nginx:latest
    ports:
    - published: 8080
      target: 80
version: '3.4'
```

Version 1.28.2:
```
$ docker-compose -v && docker-compose -f subfolder/docker-compose.yml --env-file ./subfolder/.env config
docker-compose version 1.28.2, build unknown
WARNING: The NGINX_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './subfolder/docker-compose.yml' is invalid because:
services.nginx.ports contains an invalid type, it should be a number, or an object

$ docker-compose -f subfolder/docker-compose.yml --env-file ./.env config         
services:
  nginx:
    image: nginx:latest
    ports:
    - published: 8080
      target: 80
version: '3.4'
```

### Expected result

That `--env-file` behave the same between 1.27 and 1.28 (i.e. relative paths are computed from the current directory)

## Additional information

I'm running Arch Linux with docker and docker-compose installed with pacman

**Comment by GliderGeek** [comment]
I have the same problem on arch linux. took quite a while to find that this was the source of the problem. even explicitly checked the changelog to see if changed behavior was written down.

**Comment by pjezusek** [comment]
I have the same problem on arch but with default `.env` location. Now it searches the file in the directory where `docker-compose.yml` is located and not where `docker-compose` was called.

**Comment by chapa** [comment]
I don't think the problem is related to Arch Linux, it behaves the same with the [docker/compose](https://hub.docker.com/r/docker/compose) docker image:

```
$ docker run --rm -v $(pwd)/docker-compose.yml:/subfolder/docker-compose.yml -v $(pwd)/.env:/subfolder/.env docker/compose:1.27.4 -f ./subfolder/docker-compose.yml --env-file ./subfolder/.env config
services:
  nginx:
    image: nginx:latest
    ports:
    - published: 8080
      target: 80
version: '3.4'
```

```
$ docker run --rm -v $(pwd)/docker-compose.yml:/subfolder/docker-compose.yml -v $(pwd)/.env:/subfolder/.env docker/compose:1.28.2 -f ./subfolder/docker-compose.yml --env-file ./subfolder/.env config
WARNING: The NGINX_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file '././subfolder/docker-compose.yml' is invalid because:
services.nginx.ports contains an invalid type, it should be a number, or an object
```

**Comment by ndeloof** [comment]
Hi.
The behaviour indeed changed but this is by intent. 
See https://github.com/docker/compose/issues/7928 for details

tl;fr: before this change, .env file was loaded from current dir **but** if user set `--project-directory`. On the other hand, project_directory defaults to compose file's parent directory, but env file path was not updated by use of `--file`. We fixed this inconsistency. Had to be set one way or the other, which in both case would have impacts.

If you want to use an .env file that doesn't use this convention, just run `docker-compose up --env-file /path/to/.env`

We also updated documentation for clarification https://github.com/docker/docker.github.io/pull/12142

**Comment by ndeloof** [comment]
Closing this issue as "work as designed/won't fix"

**Comment by GliderGeek** [comment]
thanks for the clarification

**Comment by chapa** [comment]
Thank you @ndeloof for the explanations, indeed using absolute paths is the solution to be compatible with all versions in my case :+1:
