### ISSUE TITLE
It would be nice a TODO in README, in order to understand supported and no supported  features 

### ISSUE THREAD

**Issue by bitliner** [docker/compose#808]
It would be nice a TODO in README, in order to understand supported and no supported  features.

I would like to start to use fig.sh, but I want to avoid the situation in which I cannot use it because my architecture needs a feature that is no supported yet. This would mean to spend time in order to setup my actual setup alternative to  fig.sh's yaml file.

**Comment by dnephin** [comment]
Done in #2165
