### ISSUE TITLE
Use Transparent Network (or other) on Docker for Windows by default instead of NAT

### ISSUE THREAD

**Issue by tiger5226** [docker/compose#8116]
## Description of the issue

Windows along with Docker have made the decision to no longer persist NAT networks on Docker Hosts after restarts. This decision adversely affects users of docker-compose. This makes it necessary to ALWAYS define the **default** network. Alternatively a docker-compose user can just always define a custom network in EVERY compose they use with docker-compose. Otherwise the adverse affect, is that after a restart of the host, the docker-compose launched services will lose their default NAT network, cease to work without scripting to re-create those networks on startup. 

Usability is critical, defaults should be intelligent, and I think an alternative default network is in order. It doesn't have to be Transparent, but something other than NAT for persistence. 

## Context information (for bug reports)

![Screen Shot 2021-02-11 at 1 55 53 PM](https://user-images.githubusercontent.com/3402064/107684506-e3dd4c00-6c70-11eb-9a28-4427ed9d2a4b.png)

Below are links to the related information around this issue:

https://github.com/docker/for-win/issues/3076
https://stackoverflow.com/questions/51242398/docker-compose-can-not-start-service-network-not-found-after-restart-docker
https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-drivers-topologies#nat-network-driver

**Comment by yangxinyun** [comment]
Looks like nobody is working on this issue yet :(

**Comment by viceice** [comment]
pretty bad to have this closed 😢

**Comment by iiq374** [comment]
👿
