### ISSUE TITLE
Compose fails `stop` and `rm` commands when environment variables not set

### ISSUE THREAD

**Issue by zwass** [docker/compose#8117]
## Description of the issue

When using the `${env_var_name:?fatal with this error message}` syntax, not supplying the environment variable prevents running the `stop` or `rm` commands. Maybe I'm missing something, but I'm not sure why we would require setting these environment variables when stopping containers.

This also manifests in the Docker UI (which I assume is shelling out to `docker-compose`?) when using the stop or delete buttons. It appears a stack with this syntax cannot be stopped from the docker UI.

<img width="1231" alt="Screen Shot 2021-02-11 at 5 53 42 PM" src="https://user-images.githubusercontent.com/575602/107721707-21060600-6c92-11eb-9351-691eedbd50e3.png">

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
```
ERROR: Missing mandatory value for "environment" option interpolating {'ENROLL_SECRET': '${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}'} in service "ubuntu20-osquery": ENROLL_SECRET must be set for server authentication
```

## Steps to reproduce the issue
1. Start a docker-compose stack using this syntax (eg. https://github.com/fleetdm/osquery-in-a-box/blob/master/osquery/docker-compose.yml#L15 `ENROLL_SECRET=foobar docker-compose up -d`).
2. Try to stop the stack (`docker-compose stop`).

### Observed result
```
ERROR: Missing mandatory value for "environment" option interpolating {'ENROLL_SECRET': '${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}'} in service "ubuntu20-osquery": ENROLL_SECRET must be set for server authentication
```

### Expected result
Stack is stopped.

**Comment by ulyssessouza** [comment]
Hello @zwass. For now, `docker-compose` needs to evaluate the config file before executing any commands

**Comment by zwass** [comment]
It's clear that is true, but it leads to bugs/bad user experience. Is there a chance of fixing it?
