### ISSUE TITLE
Ctrl-C during build doesn't shut down the container instance

### ISSUE THREAD

**Issue by bencevans** [docker/compose#813]
Canceling a build part way through just seems to close the fig command process without shutting down the docker build running behind it. If there's issues when building so the user cancels the build, changes something then expects to rebuild the the previous docker build process is still running it can sometimes get in the way and confuse the user.

**Comment by aanand** [comment]
This is an issue with the Docker daemon (and, by extension, the CLI) - you can't cancel a build in progress. See https://github.com/docker/docker/pull/9774

**Comment by dnephin** [comment]
Looks like this was fixed in the daemon
