### ISSUE TITLE
enable running containerized docker-compose in a remote host

### ISSUE THREAD

**Issue by imme-emosol** [docker/compose#8149]
Running containerized docker-compose with a DOCKER_HOST environment variable that is set to a remote host that is local only (an entry in /etc/hosts) *does not work*.

I would like for the docker-compose shell script to actually work.

To test:
1. use a machine (machineA) that runs docker daemon, with enabled TCP-socket
2. use another machine (machineB) that will use that external DOCKER_HOST for docker by:
 - setting the DOCKER_HOST ENV-variable to a name that you will use to reach the docker host
 - making sure the name resolves to an ip locally, for instance by mapping that name to an ip in /etc/hosts
3. now install the containerized docker-compose on machineB
4. use docker-compose and notice that it will not work because the docker-compose running inside the container on the remote cannot resolve the DOCKER_HOST that was transferred from machineB to the container running on machineA

**Comment by imme-emosol** [comment]
Apparently using newlines in environment variables also became problematic.

**Comment by ndeloof** [comment]
a container doesn't inherit hosts' `/etc/hosts`. This obviously also applies to containerized docker-compose. 

If you want to define a custom host, run container with `--add-host`

**Comment by imme-emosol** [comment]
Is the idea of the containerized docker-compose to be able to run it as if it would be executing docker-compose locally? (Regardless of where the container actually runs.)

Currently it is not working in that manner. Running docker-compose locally would resolve an entry in `/etc/hosts`, `script/run/run.sh` does not support such a use case.

Is the suggestion to resolve this in `script/run/run.sh` to add all entries in `/etc/hosts` to the container for docker-compose, by adding `--add-host` in that shell-script?

**Comment by imme-emosol** [comment]
ah, probably through the COMPOSE_OPTIONS=' --add-host host:ip ' or something.. okay well whatever. The run.sh was a nice base for a shell script for my own solution.. Should I close #8151 ?

**Comment by ndeloof** [comment]
I can't tell about the "_idea of the containerized docker-compose_". This has been introduced in Compose project by a time I was not a contributor. But whatever the reason is, compose in a container will never inherit all your host machine tweaks, but design of containers isolation!
