### ISSUE TITLE
'docker-compose up -d' stalls on creating and starting 200 containers

### ISSUE THREAD

**Issue by DigiDr** [docker/compose#8161]
## Description of the issue

I've generated a docker-compose.yaml that runs approx 200 services, pairs of _alice_ and _bob_ - where _bob_ 'depends' on _alice_. Each copy of _alice_ and _bob_ has it's own volume, and uses it's own ports. They all read from the same .env

Running `docker-compose up`, the docker service appears to stall on creation of about 20 containers with a looping`compose.parallel.feed_queue pending set() `message if i go --verbose.

However, if i restrict myself to only 60 copies of _alice_ and _bob_, i can bring them up.
I've also written a bash script to bring all 100 pairs up gradually, and have confirmed this also works. 

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker version`**
```
Docker version 20.10.4, build d3cb89e
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
too large to paste
```

**Comment by wesselvdv** [comment]
I have a similar issue, but with much fewer containers. I downgraded docker to `Docker version 20.10.3, build 48d30b5b32` and that seems to fix the problem.
