### ISSUE TITLE
docker-compose 1.28.5 build image 

### ISSUE THREAD

**Issue by GeorgeAnson** [docker/compose#8194]
Please post on our forums: https://forums.docker.com for questions about using `docker-compose`.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker.

when i use docker-compose 1.28.5 to build docker image by using env file ,Docker come to run error like this:
ERRO[0005] Can't add file XXX to tar: io: read/write on closed pipe
ERRO[0005] Can't close tar writer: io: read/write on closed pipe
error during connect: Post http:XXX/build?buildargs=XXX&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=registry-vpc.cn-hangzhou.aliyuncs.com%2Fgerlun-dev%2Fsmarterfin-eureka&target=&ulimits=null&version=1: unable to reach trust server at this time: 500.
Sending build context to Docker daemon

ERROR: Service 'XXX' failed to build

But when i use docker-compose of 1.26.0 version to build the same image,the error is disappeared

**Comment by gempain** [comment]
Same as #8218

**Comment by GeorgeAnson** [comment]
您好，已收到您的邮件，我将尽快给您回复。
