### ISSUE TITLE
ontains an invalid type, it should be a string, or an object

### ISSUE THREAD

**Issue by quentinfabrie** [docker/compose#8199]
when I try to run this I get a strange error what can is do 
`this is the error`
<img width="990" alt="Schermafbeelding 2021-03-14 om 00 27 08" src="https://user-images.githubusercontent.com/53113474/111052549-03c48300-845c-11eb-89af-6b59967f64b4.png">
`and this is my code`
<img width="1789" alt="Schermafbeelding 2021-03-14 om 00 28 15" src="https://user-images.githubusercontent.com/53113474/111052564-2ce51380-845c-11eb-9ca9-9d41bdbb1e3b.png">

**Comment by aiordache** [comment]
@quentinfabrie The error output tells you the build field of your wordpress service is invalid. It's an empty field. Either remove it and set an image name or set it to a context directory.
