### ISSUE TITLE
Add Support for hosts in the port bindings section

### ISSUE THREAD

**Issue by frank-dspeed** [docker/compose#820]
ports:
 - host.box:10090:80

don't works because docker only accepts ips fig could dns request ports befor that and then supply the dns result to docker that would enable the users to deploy one fig.yml that will always bind to the right ip on the host.

**Comment by dnephin** [comment]
I think this is outside the scope of what compose should handle, however with environment variable interpolation (coming in 1.5.0), you'll be able to use a variable:

```yaml

ports:
  - $HOST_IP:10090:80
```

That way you can do whatever you need to on the host to query for the correct ip, and have it injected into the `docker-compose.yml` using an environment variable.

```
HOST_IP=$(...) docker-compose up
```
