### ISSUE TITLE
docker-compose exec reports ERROR for non-zero exit code

### ISSUE THREAD

**Issue by DrVanScott** [docker/compose#8201]
Using compose:1.28.0-rc2 or prior running something like

    docker-compose exec some_service false

just silently returns the exit code, which is not zero.
Using compose:1.28.0-rc3 or later the same command returns the exit code still correctly, but additionally print out a line

    ERROR: 1

Returning a non-zero exit code should not be considered as error. This is often used to e.g. return different information.

Please return to the old behaviour at least for the "exec" command, as this is often used e.g. in CI pipelines. It shouldn't be necessary to workaround this false-positive ERROR messages.

**Comment by ulyssessouza** [comment]
Closed by  https://github.com/docker/compose/pull/8213
