### ISSUE TITLE
COMPOSE_IGNORE_ORPHANS is ignored from .env file

### ISSUE THREAD

**Issue by gregatcode** [docker/compose#8203]
## Description of the issue

COMPOSE_IGNORE_ORPHANS env var is not read from `.env` file. Other vars from that file are read.
Noticed that after recent update to 1.28.5 (not sure what the previous version was).

Orphan warning is shown:
```
$ cat .env
COMPOSE_IGNORE_ORPHANS=1
$ docker-compose up -d mailhog
WARNING: Found orphan containers (***, ***) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
mailhog is up-to-date
```
Tried setting it to `1`, `true` and `True` without success.

It is disabled when i set it through real env var though:
```
$ COMPOSE_IGNORE_ORPHANS=True docker-compose up -d mailhog
mailhog is up-to-date
```
(no orphan warning shown)

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. add `COMPOSE_IGNORE_ORPHANS=1` to the `.env` file
2. run any `docker-compose up` command

### Observed result

"WARNING: Found orphan containers ..." warning is shown.

### Expected result

No warning is shown.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

macOS, docker-compose installed via auto-updating Docker for Mac to the recent version

**Comment by theswordsmahin** [comment]
I see these now on Windows as well after an update

**Comment by chmely** [comment]
It seems that the new docker compose (without dash) command ignores this setting completely (Docker Desktop 3.3.3)

**Comment by jgeth** [comment]
Verified same behavior with `Docker Compose version 2.0.0-beta.1`
Unable to suppress orphan check with .env file, actual ENV variable or passing in command line before `docker compose`.

**Comment by bernardwiesner** [comment]
Is there any progress on this?

**Comment by ndeloof** [comment]
I've proposed support for this feature (I didn't know about it) in Compose v2 as of https://github.com/docker/compose/pull/8668
