### ISSUE TITLE
1.28.5 docker-compose to remote linux over SSH -> Can't add file XX to tar: io: read/write on closed pipe

### ISSUE THREAD

**Issue by pnutshellmenace** [docker/compose#8218]
## Description of the issue
Running docker-compose from Windows WSL2 (Ubuntu) to remote linux host:
```
DOCKER_HOST="ssh://user@remotehost" docker-compose -f "docker-compose.yml" up --build -d
```
produces the following error:
```
ERRO[0002] Can't add file XX to tar: io: read/write on closed pipe 
error during connect: Post http://docker/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=XXXX&target=&ulimits=null&version=1: write |1: broken pipe
ERRO[0002] Can't close tar writer: io: read/write on closed pipe 
ERROR: Service 'XXXX' failed to build
```
The reported file is always the first file in the build that it is trying to tar, so it appears the command bombs right at the beginning of the build.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. DOCKER_HOST="ssh://user@remotehost" docker-compose -f "docker-compose.yml" up --build -d

### Observed result
```
ERRO[0002] Can't add file XX to tar: io: read/write on closed pipe 
error during connect: Post http://docker/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=XXXX&target=&ulimits=null&version=1: write |1: broken pipe
ERRO[0002] Can't close tar writer: io: read/write on closed pipe 
ERROR: Service 'XXXX' failed to build
```

### Expected result
Build should work without error

## Additional information
This worked correctly with docker-compose 1.27.4

**Comment by dometec** [comment]
Same with 1.29.1

**Comment by raphaelvigee** [comment]
This is indeed still happening on 1.29.2, setting `DOCKER_HOST` to `ssh://user@ip` leads to this error while i can ssh to the target machine no problem

**Comment by raphaelvigee** [comment]
It seems like setting `COMPOSE_DOCKER_CLI_BUILD=0` gets it to work

**Comment by adamevince** [comment]
> It seems like setting `COMPOSE_DOCKER_CLI_BUILD=0` gets it to work

I'm having this issue using docker context to deploy remotely from jenkins build server. Do you mean setting compose_docker_cli_build=0 on the remote?

**Comment by briancaffey** [comment]
I'm having this issue as well. Trying to deploy containers to a raspberry pi from a mac over SSH, setting `DOCKER_HOST` to `shh://root@192.168.1.11`. I'm not using docker-compose, I'm using docker cli in a shell script. 

```
docker --version
Docker version 20.10.6, build 370c289
```

Error: 

```
ERRO[0000] Can't add file <file> to tar: io: read/write on closed pipe 
ERRO[0000] Can't close tar writer: io: read/write on closed pipe 
error during connect: Post "http://docker/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=localhost%3A5000%2Fbackend%3Ae150d93&target=&ulimits=null&version=1": write |1: broken pipe
```

**Comment by adamevince** [comment]
> > It seems like setting `COMPOSE_DOCKER_CLI_BUILD=0` gets it to work
> 
> I'm having this issue using docker context to deploy remotely from jenkins build server. Do you mean setting compose_docker_cli_build=0 on the remote?

My issue was caused by improper permissions. Using sudo fixed it for me.

**Comment by SonnyAD** [comment]
> erver. Do you mean setting compose_docker_cli_build=0 on the remote?

Nope, on the machine you run docker-compose. On my end I do something like `COMPOSE_DOCKER_CLI_BUILD=0 docker-compose up -d`

**Comment by BigTarr** [comment]
> I'm having this issue as well. Trying to deploy containers to a raspberry pi from a mac over SSH, setting `DOCKER_HOST` to `shh://root@192.168.1.11`. I'm not using docker-compose, I'm using docker cli in a shell script.
> 
> ```
> docker --version
> Docker version 20.10.6, build 370c289
> ```
> 
> Error:
> 
> ```
> ERRO[0000] Can't add file <file> to tar: io: read/write on closed pipe 
> ERRO[0000] Can't close tar writer: io: read/write on closed pipe 
> error during connect: Post "http://docker/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=localhost%3A5000%2Fbackend%3Ae150d93&target=&ulimits=null&version=1": write |1: broken pipe
> ```

Did you get a fix?

**Comment by tanzislam** [comment]
> > > It seems like setting `COMPOSE_DOCKER_CLI_BUILD=0` gets it to work
> > 
> > I'm having this issue using docker context to deploy remotely from jenkins build server. Do you mean setting compose_docker_cli_build=0 on the remote?
> 
> My issue was caused by improper permissions. Using sudo fixed it for me.

For me `sudo` fixed it as well, but for a completely different reason. 😅 Apparently the remote-daemon protocol is sensitive to the `HTTP_PROXY`/`HTTPS_PROXY`/`http_proxy`/`https_proxy` environment variables, and those are what got cleared using `sudo`. (`sudo -E` would still reproduce the problem.)

My fix was to enlist the daemon address in `NO_PROXY`/`no_proxy`.

**Comment by erlangparasu** [comment]
Got same issue

**Comment by DrunkenBeetle** [comment]
If running compose within a container (docker-in-a-docker setup) then you need to supply COMPOSE_DOCKER_CLI_BUILD=0` as an env variable when running the container (`docker run -e COMPOSE_DOCKER_CLI_BUILD=0 ...`)
