### ISSUE TITLE
Environment variable warnings/errors need more informative messages

### ISSUE THREAD

**Issue by samlaf** [docker/compose#8231]
The way warning messages in docker-compose are written has made me lose a few hours this morning thinking I had a fundamental issue with my Dockerfile. Here is a toy docker-compose.yml file to describe the issue:
```
# docker-compose.yml
version: "3.8"
services:
  main-service:
    image: some-image
    command: bash
  buggy-service:
    image: some-image
    command: echo $SOME_ENV_VAR
```
On the command-line, I run `main-service` as
```
docker-compose run main-service
```
and the output I receive is
```
WARNING: The SOME_ENV_VAR variable is not set. Defaulting to a blank string.
Creating ###_main-service_run ... done
```

The issue is that `$SOME_ENV_VAR` should be `$$SOME_ENV_VAR` in order to reference the env variable inside the docker as opposed to that on the host. It took me extremely long to figure this out, and due to the uninformative warning, I thought for the longest while that this was happening inside the docker container, and I couldn't figure out where SOME_ENV_VAR was being used inside the docker container, since I didn't call buggy-service.

POSSIBLE IMPROVEMENTS / SUGGESTIONS:

1. The WARNING should be contextualized in order to let the user know that its a warning coming from docker-compose, and not the image, or inside the container, etc. Maybe something like "docker-compose WARNING: The ..."
2. Would it be possible to add a suggestion to the user that he might be missing a "$"? Something like "The SOME_ENV_VAR variable is not set on the host. Did you mean to use $$SOME_ENV_VAR?"
3. Since the environment variable is only being referenced in the buggy-service which I am not even calling.... why is docker-compose giving me that warning in the first place? Perhaps this warning should only be given when I directly call `docker-compose run buggy-service`?

Please let me know if something in my use-case/message is confusing. I'm sure this can save a lot of frustration to others in the future if implemented properly. Thanks :)

**Comment by mellester** [comment]
To answer point 3 it is related to #1973
It always validates the full config config
