### ISSUE TITLE
Containerized installation : script failing with multi-line env variables

### ISSUE THREAD

**Issue by shavounet** [docker/compose#8245]
## Description of the issue

On my CI, I use docker:dind and docker-compose installed in a container, but the later is failing on the most simple usage.

## Context information (for bug reports)

**Output of `docker-compose version`** : failing, but it should be 1.28.6

**Output of `docker version`**
```
Docker version 19.03.15, build 99e3ed8
```

**Output of `docker-compose config`** : failing but non-relevant

## Steps to reproduce the issue

1. Inside image `docker:19.03.15`, run
  - `apk add make bash git curl ncurses`
  - `curl -L --fail https://github.com/docker/compose/releases/download/1.28.6/run.sh -o /usr/local/bin/docker-compose`
  - `chmod +x /usr/local/bin/docker-compose`
2. Be sure to have a multi-line environment variable, especially with special characters on second line (my test used a SSH private key, populated by Gitlab CI)
3. Run `docker-compose -v`

### Observed result

```
docker: invalid reference format: repository name must be lowercase.
```

### Expected result

The docker-compose version

## Additional information

I think the issue is in the `run.sh` script, line 74
```bash
ENV_OPTIONS=$(printenv | sed -E "/^PATH=.*/d; s/^/-e /g; s/=.*//g; s/\n/ /g")
```

It assume there is one line by env variable, but it's not my case... As a consequence it pass `-e` flags to docker containing parts of the value (containing invalid characters).

**Comment by shavounet** [comment]
A small (imperfect) workaround that worked for me is using this 
```bash
ENV_OPTIONS=$(printenv | grep -E "[A-Z_]+=.*" | sed -E "/^PATH=.*/d; s/^/-e /g; s/=.*//g; s/\n/ /g")
```

But it do not solve the case of multi-line variables containing `=`

**Comment by roganartu** [comment]
I also hit this today and got a slightly different (but equally confusing) error:
```
docker: invalid reference format.
See 'docker run --help'.
```
I added `set -x` to `run.sh` to find that the final `docker run` call was:
```
+ exec docker run --rm -t -i -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST -e PYENV_VIRTUALENV_INIT -e TMUX -e SSH_CLIENT -e USER -e FZF_DEFAULT_OPTS -e --color fg:-1,bg:-1,hl:33,fg+:254,bg+:235,hl+:33 -e --color info:136,prompt:136,pointer:230,marker:230,spinner:136 -e -e XDG_SESSION_TYPE -e SHLVL -e HOME -e LESS -e MOTD_SHOWN -e OLDPWD -e SSH_TTY -e NVM_BIN -e LSCOLORS -e PYENV_SHELL -e ZSH -e NVM_INC -e BORG_PASSCOMMAND -e PAGER -e DBUS_SESSION_BUS_ADDRESS -e VISUAL -e ANSIBLE_NOCOWS -e NVM_DIR -e LOGNAME -e _ -e XDG_SESSION_CLASS -e PROMPT_EOL_MARK -e TERM -e XDG_SESSION_ID -e XDG_RUNTIME_DIR -e LANG -e LS_COLORS -e SSH_AUTH_SOCK -e is_vim -e GOPATH -e SHELL -e LC_ALL -e PWD -e KEYTIMEOUT -e SSH_CONNECTION -e VIRTUAL_ENV_DISABLE_PROMPT -e NVM_CD_FLAGS -e TMUX_PLUGIN_MANAGER_PATH -e TMUX_PANE -e EDITOR -v /home/tl:/home/tl -v '/home/tl:/home/tl' -e HOME -w /home/tl docker/compose:1.28.6 --help
```
Inside which we can see that this section is malformed:

```
-e FZF_DEFAULT_OPTS -e --color fg:-1,bg:-1,hl:33,fg+:254,bg+:235,hl+:33 -e --color info:136,prompt:136,pointer:230,marker:230,spinner:136 -e -e XDG_SESSION_TYPE
```

Caused by this env var:

```
$ echo $FZF_DEFAULT_OPTS
    --color fg:-1,bg:-1,hl:33,fg+:254,bg+:235,hl+:33
    --color info:136,prompt:136,pointer:230,marker:230,spinner:136
```

Since the `sed` just drops everything after `=` on each line, `docker run` doesn't seem to mind if it gets `-e NON_EXISTENT_ENV`, and that the spec for environment var names is technically "anything but NUL and =", I think the following should do the trick pretty robustly:
```
ENV_OPTIONS=$(printenv | grep -E "^[^=^\s]+=.*" | sed -E "/^PATH=.*/d; s/^/-e /g; s/=.*//g; s/\n/ /g")
```

You could make the `grep` more restrictive as required (I got my info re valid env vars from https://stackoverflow.com/a/2821183). I tried to get the same behaviour as part of the `sed` command but found it more difficult to both get working and understand at a glance.

**Comment by redRolf** [comment]
@roganartu 🙏  Thank you, this fixed the issue for me :) 
It would be awsome if this issue was addressed with the issue: https://github.com/docker/compose/issues/8335
as currently there is no `run.sh` release for 1.29.2
