### ISSUE TITLE
 The Compose file './docker-compose.yml' is invalid because: services.db.volumes contains an invalid type, it should be an array services.app.depends_on contains an invalid type, it should be an array

### ISSUE THREAD

**Issue by tanujnaik91** [docker/compose#8248]
## Context information (for bug reports)

**Output of `docker-compose version`**
```
(paste here)
```

**Output of `docker version`**
```
(paste here)
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.##
- [
![Screenshot from 2021-04-01 18-25-29](https://user-images.githubusercontent.com/79827189/113297313-15d96900-9318-11eb-893a-24323a5783e7.png)
](url)

**Comment by hinorashi** [comment]
Hey bro, pls learn `yml` first before jump into `docker-compose` 🤙🏻 

Quick answer: add a space:
`-db` -> `- db`
`-/var/...` -> `- /var`
