### ISSUE TITLE
Cannot find .env file in current directory

### ISSUE THREAD

**Issue by stecog** [docker/compose#8254]
## Description of the issue
docker-compose cannot find .env file into current directory (where the command is executed), like explained [here](https://docs.docker.com/compose/env-file/) 
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.6, build 5db8d86f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. Make a folder named ```test``` and inside create a docker-compose.yml with this content:
```
version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
```
2. Create a ```.env``` file with this content:
```MYSQL_ROOT_PASSWORD=password```
3. In this directory, now we have ```test/docker-compose.yml``` and ```.env``` file. Now launch ```docker-compose -f test/docker-compose.yml up -d```

### Observed result
WARNING: The MYSQL_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
Creating test_mysql_1 ... done
### Expected result
Creating test_mysql_1 ... done (without WARNING)

I expect docker-compose to look for the .env file in the current directory, i.e. where I run the command.

**Comment by machadodev** [comment]
Hey, what's up?

You should run docker-compose on the same compose file folder.
-f is to specify an alternate compose file. As your file has the default name, it can be omitted.

![Screenshot from 2021-04-06 11-33-44](https://user-images.githubusercontent.com/15857625/113728308-606a3500-96cc-11eb-91af-71386e5d041a.png)

**Comment by stecog** [comment]
I have many projects that have several compose files divided into folders and I launch docker-compose from outside, for each environment, I use -f to select the compose file and the .env file is in the same directory from where I launch the command. [Here](https://docs.docker.com/compose/env-file/) it clearly talks about current directory, why doesn't it work?

**Comment by Mithenks** [comment]
As @stecog said, it's very common to have `docker-compose.yml` file a directory other than project root. 
I've also experienced this bug, here is a further test.

```
$ cat .env 
COMPOSE_FILE=.config/docker-compose.yml
PRJ=test

$ cat .config/docker-compose.yml 
version: '3.4'
services:
  app:
    image: alpine
    environment:
      - VAR=${PRJ}

$ ./docker-compose-1.27.4 -f .config/docker-compose.yml up -d
Starting config_app_1 ... done

$ ./docker-compose-1.28.0 -f .config/docker-compose.yml up -d
WARNING: The PRJ variable is not set. Defaulting to a blank string.
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Recreating config_app_1 ... done

$ ./docker-compose-1.28.6 -f .config/docker-compose.yml up -d
WARNING: The PRJ variable is not set. Defaulting to a blank string.
Starting config_app_1 ... done

$ ./docker-compose-1.27.4 up -d
Recreating config_app_1 ... done

$ ./docker-compose-1.28.0 up -d
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Recreating config_app_1 ... done

$ ./docker-compose-1.28.6 up -d
Starting config_app_1 ... done
```

The bug is only present when the `-f` switch is used. If the `COMPOSE_FILE` variable in `.env` file is used instead of the `-f` switch, everything works fine.
`docker-compose` works fine up to version `1.27.4`.

**Comment by Mithenks** [comment]
As @jean-louis pointed out to me, this behaviour has changed starting with v1.28+.

As explained in the docs https://docs.docker.com/compose/env-file/, if we use the `-f` switch the `.env` file is expected to be in the same directory as the docker-compose file. 

@stecog so you have to else remove the `-f` switch and use the `COMPOSE_FILE` variabile in your `.env` file instead, or you can move your `.env` file in the same directory as the `docker-compose.yml` file.

**Comment by stecog** [comment]
I would like to avoid modifying dozens of projects already distributed to dozens of developers ..... I would like to understand if it is a bug or not.  In that case I should add --env-file

**Comment by kerryj89** [comment]
> As @jean-louis pointed out to me, this behaviour has changed starting with v1.28+.
> 
> As explained in the docs https://docs.docker.com/compose/env-file/, if we use the `-f` switch the `.env` file is expected to be in the same directory as the docker-compose file.
> 
> @stecog so you have to else remove the `-f` switch and use the `COMPOSE_FILE` variabile in your `.env` file instead, or you can move your `.env` file in the same directory as the `docker-compose.yml` file.

Do you know what the motive is behind this change?  In my case my `docker-compose.yml` is in the project root but my env files are in `.docker/web/env/*`.

**Comment by cnlzxin** [comment]
My temporary solution:

**Comment by cnlzxin** [comment]
My temporary solution:
```
# ~/.zshrc
alias docker-compose='docker-compose --env-file .env'
```

**Comment by backbone87** [comment]
this situation is very unsatisfying if you have the compose file and the env file in different directories. all approaches have side effects or change others behaviors:
- moving the env file breaks existing projects big time
- using --env-file option requires the env file to exist
- using --project-directory causes all paths inside all compose files to be relative to the project directory, while it's learned from basically any web technology that relative paths are relative to the path/url of the file containing the reference. could be that this behavior is different for stuff that is "closer to the OS", but then I imagine the "web dev" audience is a big part of compose users.
