### ISSUE TITLE
Log reason why cache is not used

### ISSUE THREAD

**Issue by karlismelderis** [docker/compose#8268]
**Is your feature request related to a problem? Please describe.**
We're using docker-compose in CI pipelines a lot and codebase is reasonably big.
We're rebuilding same Dockerfile in CI multiple times where most of the layers should be static and come from cache.

Quite often I find that copying folders `COPY . ./` (from to path is just an illustration) is not using cache and thus slows us down.

With current debug  (--log-level DEBUG) and `--verbose` log output I'm failing so detect why cache was ignored.
So having hard time to detect what it the cause and if we should add just another file to .dockerignore

**Describe the solution you'd like**
Would be nice to log - skipping cache because file X has changed

**Describe alternatives you've considered**
it's a pure guessing game at the moment

**Additional context**
I'm sorry if it's possible already and I didn't find the right CLI switch.

**Comment by kevin-lindsay-1** [comment]
I think that this is a very good idea; tilt.dev does this and it's very helpful, but it would be really nice if pure docker did this so that I would know in the context of CI why my cache is considered a mismatch.
