### ISSUE TITLE
Compose does not do recursive variable substitution in docker-compose.yaml file like bash

### ISSUE THREAD

**Issue by technorabilia** [docker/compose#8286]
## Description of the issue
Compose does not do recursive variable substitution in docker-compose.yaml file like bash.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.11.11
 Git commit:        bfed4f5
 Built:             Wed Oct 28 03:17:41 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.11
  Git commit:       64d9155
  Built:            Wed Oct 28 03:16:36 2020
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
ERROR: Named volume "${BASE_DIR:-/volume1/docker/darktable/config}:/config" is used in service "darktable" but no declaration was found in the volumes section.
```

## Steps to reproduce the issue

The following command runs without problems.

Where
`${DARKTABLE_CONFIG_DIR:-${BASE_DIR:-/volume1/docker}/darktable/config}`
resolves to:
`/volume1/docker/darktable/config`

```
docker run -d \
  --name=darktable \
  -e PUID=${PUID:-1024} `# for GroupID` \
  -e PGID=${PGID:-100} `# for UserID` \
  -e TZ=${TZ:-Europe/Amsterdam} `# Specify a timezone to use for example Europe/Amsterdam` \
  -p 3000:3000 `# Darktable desktop gui.` \
  -v ${DARKTABLE_CONFIG_DIR:-${BASE_DIR:-/volume1/docker}/darktable/config}:/config `# Users home directory in the container, stores program settings and images` \
  --restart unless-stopped \
  ghcr.io/linuxserver/darktable
```

If you use the same definition in docker-compose.yaml and try to start with docker-compose up -d you get the following error:
`ERROR: Named volume "${BASE_DIR:-/volume1/docker/darktable/config}:/config" is used in service "darktable" but no declaration was found in the volumes section.
`
This is because only the outer variable is expanded.

```
---
version: "2.1"
services:
  darktable:
    image: ghcr.io/linuxserver/darktable
    container_name: darktable
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Users home directory in the container, stores program settings and images
      - ${DARKTABLE_CONFIG_DIR:-${BASE_DIR:-/volume1/docker}/darktable/config}:/config
    ports:
      # Darktable desktop gui.
      - 3000:3000
    restart: unless-stopped
```

### Observed result

```
    volumes:
      # Users home directory in the container, stores program settings and images
      - ${DARKTABLE_CONFIG_DIR:-${BASE_DIR:-/volume1/docker}/darktable/config}:/config
```
expands to:
```
    volumes:
      # Users home directory in the container, stores program settings and images
      - ${BASE_DIR:-/volume1/docker}/darktable/config}:/config
```

### Expected result

```
    volumes:
      # Users home directory in the container, stores program settings and images
      - ${DARKTABLE_CONFIG_DIR:-${BASE_DIR:-/volume1/docker}/darktable/config}:/config
```
should expand to:
```
    volumes:
      # Users home directory in the container, stores program settings and images
      - /volume1/docker/darktable/config:/config
```

Just like:
````
root@DiskStation:~/lsio/darktable# grep config docker-compose.yaml
      - ${DARKTABLE_CONFIG_DIR:-${BASE_DIR:-/volume1/docker}/darktable/config}:/config
root@DiskStation:~/lsio/darktable# . .env && eval "echo \"$(cat docker-compose.yaml)\"" | grep config
      - /volume1/docker/darktable/config:/config
root@DiskStation:~/lsio/darktable#
````

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

This is on a Synology NAS on an older version, but I am almost certain this will also be the case on other OS's and latest versions.

**Comment by tekumara** [comment]
[Interpolation can be nested](https://github.com/compose-spec/compose-spec/blob/master/spec.md#interpolation) according to the compose spec. But this doesn't seem to work in compose v2.1.1:
```
    environment:
      - DEFAULT_PASSWORD=secret
      - PASSWORD=${PASSWORD:-${DEFAULT_PASSWORD}}
```

Instead, when PASSWORD isn't set, this sets PASSWORD to the literal `${DEFAULT_PASSWORD}`

**Comment by thePanz** [comment]
The same happens with BASH variables expansion in volumes.
Example:

```yaml
volumes:
      - "${SSH_AUTH_SOCK:?variable SSH_AUTH_SOCK not defined, is ssh-agent running?}:/.ssh-agent/local-socket"
```

Leads to weird errors like `volume "ssh-agent running?" not defined` in the CLI

**Comment by oj-lappi** [comment]
Can confirm this bug is present for me as well:

> docker-compose version 1.27.4, build unknown
> docker-py version: 5.0.3
> CPython version: 3.9.9
> OpenSSL version: OpenSSL 1.1.1m  14 Dec 2021

e.g. I can't do:
```
       ...
        volumes:
            - /home/${SUDO_USER:-$LOGNAME}/.gitconfig:/home/developer/.gitconfig
       ...
```

this becomes:
```
       ...
        volumes:
            - /home/${LOGNAME}/.gitconfig:/home/cxx-developer/.gitconfig:rw
       ...
```

A work-around for a simple substitution like this is to set the value in your .env file instead:
.env
```
SUDO_USER=${LOGNAME}
```

But this not the cleanest of solutions, it only works because the users environment will be checked before the .env file, and in this case it writes the default to the environment variable in the container, which may be used by some tools.
If you're already using variables defined in .env this won't help you.

**Comment by sBouzols** [comment]
Hi,

Same problem here with version 
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```
I was trying nested interpolation -> [interpolation doc](https://github.com/compose-spec/compose-spec/blob/master/spec.md#interpolation)
and got the same error as above.

Even tried to set .env file with 
```
PATH_VARIABLE=${HOME}
```
and compose file with
```
volume:
  - ${PATH_VARIABLE}/data:/foo/data:Z
```
and it didn't work either (I have no $PATH_VARIABLE exported in my terminal but I have $HOME)
I get :
```cmd
ERROR: Named volume "${HOME}/data:/foo/data:Z" is used in service "foo_service" but no declaration was found in the volumes section.
```

Could you give a feedback ?

**Comment by ndeloof** [comment]
@ogtega tested with latest release (v2.18.1):

```yaml
services:
  app:
    image: nginx
    environment:
      - GUNICORN_CMD_ARGS=${DEVELOPMENT:+--log-level debug --reload}
```

```
$ docker compose config | grep GUNICORN_CMD_ARGS
      GUNICORN_CMD_ARGS: --log-level debug --reload
$ DEVELOPMENT=true docker compose config | grep GUNICORN_CMD_ARGS
      GUNICORN_CMD_ARGS: ""
```
can you please confirm this issue is fixed ?
