### ISSUE TITLE
How can I check compose version in scripts.

### ISSUE THREAD

**Issue by PMExtra** [docker/compose#8299]
I have a non-interactive script that using docker-compose with `--no-ansi` argument.

I noticed that `--no-ansi` was deprecated #6858.

I will replace it with `--ansi=never`. But I can't ensure which version of docker-compose that the user uses.

So I want to do something like:
```shell
if [ ??? ]; then
  dc='docker-compose --ansi=never'
else
  dc='docker-compose --no-ansi'
fi
```

What should be replaced with `???`

**Comment by Jammicus** [comment]
If a flag doesn't exist, it looks like docker-compose will return a 1 exit code. You can check to see if the new flag exists, if it doesn't, expect a exit code 1 which will  so you can do:

```

newflag=$(docker-compose  --ansi=never)
if [ $? -eq 0 ] ; then
  dc='docker-compose --ansi=never'
else
  dc='docker-compose --no-ansi'
fi


```
