### ISSUE TITLE
secrets: allow providing secrets with env

### ISSUE THREAD

**Issue by quasis** [docker/compose#8302]
Now that buildkit supports the feature (https://github.com/moby/buildkit/pull/1534) will be awesome to have it in compose as well.

Possible syntax:

```
secrets:
    some_secret_name:
        env: SOME_ENV_VARIABLE
```

**Comment by lsorber** [comment]
May I request to reopen this issue?

This feature would be a great complement to the recently added build time secrets feature.

**Comment by rmcclaincf** [comment]
I would also like to see this reopened.   We are migrating our Jenkins to build images using secrets from env vars.  Not having this feature is going to require us to make extensive workarounds to make our images build both locally and in our pipelines.

**Comment by glours** [comment]
@rmcclaincf [this feature has been added](https://github.com/docker/compose/pull/9553) a couple of month ago.
