### ISSUE TITLE
Flag to set custom docker executable

### ISSUE THREAD

**Issue by imgx64** [docker/compose#8304]
**Is your feature request related to a problem? Please describe.**
I'm trying to use docker-compose with podman. Most things work fine, but if docker-compose attempts to build an image, it fails because it has hardcoded `docker build` command (see [here](https://github.com/docker/compose/blob/0bea52b18dda3de8c28fcfb0c80cc08b8950645e/compose/service.py#L1958)), and is unable to run `podman build` instead.

I modified the source code to change it to podman, and it worked fine.

**Describe the solution you'd like**
I'd like docker-compose to add a flag to manually select a path to a different docker executable. For example: `docker-compose --docker-bin /usr/bin/podman up`

**Describe alternatives you've considered**
Building the images manually before running `docker-compose up` is a workaround for this.

**Additional context**

**Comment by ndeloof** [comment]
docker-compose is not a script delegating docker commands to another tool, it's a plain standalone tool which uses the Docker Engine API, just like `docker` command does.

**Comment by imgx64** [comment]
In my original post, I linked to the part where docker-compose calls the `docker` binary to build the image.

https://github.com/docker/compose/blob/0bea52b18dda3de8c28fcfb0c80cc08b8950645e/compose/service.py#L1958

**Comment by gotmax23** [comment]
@ndeloof Can you please reopen the issue? As @imgx64 said, the docker-compose build function notably does not use the Docker api and instead calls the Docker binary directly.

**Comment by ndeloof** [comment]
Re-opened as requested, but with Compose v2 being released soon, docker-compose will most probably not get such new features approved.

**Comment by gotmax23** [comment]
Thanks!
