### ISSUE TITLE
not able to execute docker compose file 

### ISSUE THREAD

**Issue by MohsinKhan-QALead** [docker/compose#8307]
it is throwing error and when I looked at docker it says stopped can you please help

![image](https://user-images.githubusercontent.com/66518200/116808653-a396b700-ab57-11eb-9770-112ccb67537c.png)

![image](https://user-images.githubusercontent.com/66518200/116808690-de98ea80-ab57-11eb-94d2-3b6b5f5beb98.png)

**Comment by floriandorre** [comment]
It seems that your docker is not running (the bottom left part of the docker desktop interface should be green to gray 

You might want to have a look at your docker engine settings to see if something is wrong and could lead to docker not starting
