### ISSUE TITLE
docker-compose build issue building remote Dockerfile

### ISSUE THREAD

**Issue by p-fruck** [docker/compose#8309]
## Description of the issue

Using docker-compose 1.29.1, I am not able to directly build a container image from a remote git repository over https. Downgrading to 1.27.1 resolves this issue. This has been tested on two different Ubuntu systems, one using the built-in Ubuntu docker release and one using the official docker repo.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Output of `docker version`**
```
Client:
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.2-0ubuntu1~20.04.2
 Built:             Tue Mar 30 21:24:57 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.2-0ubuntu1~20.04.2
  Built:            Mon Mar 29 19:10:09 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.3
  GitCommit:        
 runc:
  Version:          spec: 1.0.2-dev
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    build:
      context: https://github.com/piuswalter/studyoffline.git#main
version: '3'
```

## Steps to reproduce the issue

1. Use docker-compose v1.29.1
2. Create a compose file with the above content
3. Run `docker-compose up --force-recreate` or `docker-compose up --build`

### Observed result

Build fails giving some openssl error (see 'stacktrace'). This shouldn't happen, because

* OpenSSL 1.1.1f  31 Mar 2020 is installed
* I'm cloning via https, but somehow libssh.so is referenced

### Expected result

Build should succeed, because building via `docker build -t studyoffline https://github.com/piuswalter/studyoffline.git#main` works just fine.

### Stacktrace / full error message

```
Building app
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /usr/lib/git-core/git-remote-https: /tmp/_MEImbwXUE/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib/x86_64-linux-gnu/libssh.so.4)
: exit status 128
```

## Additional information
OS: Ubuntu 20.04.1 LTS
Installed docker via built in ubuntu repos, but tested on another machine with official docker repos
Installed docker-compose via official installation instructions

**Comment by knilink** [comment]
got the same issue,
tested with different binary versions from releases, it worked until 1.28.0 and the issue happened from 2.28.2 to current latest 2.29.2

**Comment by ben-z** [comment]
Possibly related to https://github.com/docker/compose/issues/7686

**Comment by AndreaDiPietro-ADP** [comment]
Same on

```
Ubuntu 20.04.2 LTS
OpenSSL 1.1.1f  31 Mar 2020
docker-compose version 1.29.2, build 5becea4c
Docker version 20.10.7, build f0df350
```

docker-compose fails git cloning a Dockerfile repo 
```yml
build: https://github.com/.....git#main
```
return
```cli
openssL_1_1_1' not found (required by /lib/x86_64-linux-gnu/libssh.so.4)
```

I have tried all the versions backwards and the newest release working, in this scenario, is docker-compose v. 1.25.5
```
docker-compose version 1.25.5, build 8a1c60f6
```

**Comment by fuuman** [comment]
I have the exact same error. Ubuntu 20. docker-compose v1.29.2.
```
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /usr/lib/git-core/git-remote-https: /tmp/_MEI8t4lnO/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib/x86_64-linux-gnu/libssh.so.4)
```

**Comment by daniloinacio** [comment]
I have the same error here. Ubuntu 20.04 and docker-compose version 1.29.2, build 5becea4c.

**Comment by laurazard** [comment]
Hi all, thanks for the report.

This provided Compose file works fine for me on Compose V2, so I'm closing this issue. Compose V1 is EOL and hasn't been worked on in a while, so you should try to migrate over to using it.
