### ISSUE TITLE
Update latest tag

### ISSUE THREAD

**Issue by ravshansbox** [docker/compose#8312]
## Steps to reproduce the issue

1. `docker pull docker/compose:latest`
2. `docker pull docker/compose:1.29.1`
3. `docker image ls`

### Observed result
Image ids should be the same

### Expected result
Image ids are different

**Comment by nonylene** [comment]
+1 for this. [`lastest` tag](https://hub.docker.com/layers/docker/compose/latest/images/sha256-b60a020c0f68047b353a4a747f27f5e5ddb17116b7b018762edfb6f7a6439a82?context=explore) for docker/compose on Docker Hub is still staying on [1.26.2](https://hub.docker.com/layers/docker/compose/1.26.2/images/sha256-b60a020c0f68047b353a4a747f27f5e5ddb17116b7b018762edfb6f7a6439a82?context=explore).

**Comment by GarrisonD** [comment]
+1

**Comment by ravshansbox** [comment]
Unfortunately, still reproducible, what it costs to publish already published image with `:latest` tag?

**Comment by mmdl** [comment]
+1

**Comment by glours** [comment]
Questions: 
* Why are you using this image specifically? 
* What are you use cases and can't you achieve those ones with the `docker` image?

Just to let you know that if we republished this image on the Hub, the `latest` tag will be associated to the last v2 release and not link to compose v1 anymore

**Comment by GarrisonD** [comment]
I was describing my workflow and understood that the latest Compose is shipped with Docker. Is this what you mean?

**Comment by glours** [comment]
Yep compose is now part of the `docker` image
```console
> docker pull docker
Using default tag: latest
latest: Pulling from library/docker
9981e73032c8: Already exists
77b8a1a2bc33: Pull complete
fa25d67de920: Pull complete
65ab1135c7b7: Pull complete
b0b01c7da2e2: Pull complete
3a612f6045b8: Pull complete
1a41c283750c: Pull complete
dc9c06fd30af: Pull complete
2c0e27cc953e: Pull complete
Digest: sha256:c24538b2a7a081efc81185772bd8066d33cbf1f3e1a8249657395bdad4d5f844
Status: Downloaded newer image for docker:latest
docker.io/library/docker:latest
> docker run -v /var/run/docker.sock:/var/run/docker.sock --rm -it docker compose version
Docker Compose version v2.5.1
```

**Comment by glours** [comment]
I think the `docker` image can be used for most of the use cases.
I'll close this issue, feel free to open a new one if the `docker` image don't do the job
