### ISSUE TITLE
Insert initial content to new volume

### ISSUE THREAD

**Issue by ikeji** [docker/compose#8324]
**Is your feature request related to a problem? Please describe.**
When we use docker-compose for setup dev stack on local machine,
I always insert sample data to RDB on the mysql data volume.
Currently we did this separately from docker-compose command.
I want to some automated way to do this.

**Describe the solution you'd like**
Extend a docker-compose.yml to include default contents like this:
```
volumes:
- mysql-data:
  initial_data: sampledata.tgz
```
When docker-compose create the volume, insert the file to the new volume.

**Describe alternatives you've considered**
Other option is resolve this problem on volume driver layer.
But we want to insert the data for other existing driver,
so I think resolving in docker-compose layer is better choice.

**Additional context**
issue #7158 is not directory related to this FR, but this FR is one choice for restoring data.

**Comment by ndeloof** [comment]
Unfortunately `VolumeCreate` API doesn't have this feature, so we would need to create a temporary container for this purpose which would be hack-ish. Preferred approach is for you to declare an init-container, and have your actual service to `depend_on` this init container with condition `service_completed`
