### ISSUE TITLE
Installation via container misses run.sh asset in 1.29.2

### ISSUE THREAD

**Issue by alterphp** [docker/compose#8335]
## Description of the issue

Installation via container (https://docs.docker.com/compose/install/#install-as-a-container) requires `run.sh` in the assets of the release. It does not exist in the 1.29.2 release.

**Comment by ilpianista** [comment]
It looks like @ulyssessouza did that release. Maybe he can help here?

**Comment by orensbruli** [comment]
@ulyssessouza could you help with this? Thank you!

**Comment by ulyssessouza** [comment]
Thank you all for the issue! 

My bad! 
It should be fixed now.
