### ISSUE TITLE
Segfaults on `docker compose logs`

### ISSUE THREAD

**Issue by tuxiqae** [docker/compose#8336]
## Description of the issue
Segmentation fault when running the command `docker compose logs`, on the other hand, `docker-compose logs` works perfectly well.

```
❯ docker compose logs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c369a8]

goroutine 18 [running]:
github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1(0x0, 0x0)
	github.com/docker/compose-cli/local/compose/logs.go:54 +0x188
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000342b40, 0xc0003a6000)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

## Context information (for bug reports)
**Output of `docker compose version`**
```
 ❯ docker compose version
Docker Compose version 2.0.0-beta.1⏎
```

**Output of `docker-compose version`**
```
 ❯ docker-compose version
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
Sorry, not allowed to send.

## Steps to reproduce the issue

1. Run the command `docker compose logs`
2. ???
3. PROFIT

### Observed result
Segfault

### Expected result
Logs

### Stacktrace / full error message

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c369a8]

goroutine 50 [running]:
github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1(0x0, 0x0)
	github.com/docker/compose-cli/local/compose/logs.go:54 +0x188
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00033cb10, 0xc0000d21e0)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by jirayupiwon1** [comment]
> ## คำอธิบายปัญหา
> ความผิดพลาดในการแบ่งกลุ่มเมื่อเรียกใช้คำสั่ง`docker compose logs`ในทางกลับกัน`docker-compose logs`ทำงานได้ดีอย่างสมบูรณ์
> 
> ```
> ❯ docker compose logs
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c369a8]
> 
> goroutine 18 [running]:
> github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1(0x0, 0x0)
> 	github.com/docker/compose-cli/local/compose/logs.go:54 +0x188
> golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000342b40, 0xc0003a6000)
> 	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
> created by golang.org/x/sync/errgroup.(*Group).Go
> 	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
> ```
> 
> ## ข้อมูลบริบท (สำหรับรายงานข้อบกพร่อง)
> **ผลลัพธ์ของ `docker compose version`**
> 
> ```
>  ❯ docker compose version
> Docker Compose version 2.0.0-beta.1⏎
> ```
> 
> **ผลลัพธ์ของ `docker-compose version`**
> 
> ```
>  ❯ docker-compose version
> docker-compose version 1.29.1, build c34c88b2
> docker-py version: 5.0.0
> CPython version: 3.9.0
> OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
> ```
> 
> **ผลลัพธ์ของ `docker version`**
> 
> ```
> Client:
>  Cloud integration: 1.0.14
>  Version:           20.10.6
>  API version:       1.41
>  Go version:        go1.16.3
>  Git commit:        370c289
>  Built:             Fri Apr  9 22:46:57 2021
>  OS/Arch:           darwin/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.6
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       8728dd2
>   Built:            Fri Apr  9 22:44:56 2021
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.4.4
>   GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
>  runc:
>   Version:          1.0.0-rc93
>   GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ```
> 
> **ผลลัพธ์ของ`docker-compose config`**
> (ตรวจสอบให้แน่ใจว่าได้เพิ่ม`-f`ธงที่เกี่ยวข้องและอื่น ๆ )
> ขออภัยไม่อนุญาตให้ส่ง
> 
> ## ขั้นตอนในการทำให้เกิดปัญหาอีกครั้ง
> 1. เรียกใช้คำสั่ง `docker compose logs`
> 2. ???
> 3. กำไร
> 
> ### ผลลัพธ์ที่สังเกตได้
> Segfault
> 
> ### ผลลัพธ์ที่คาดหวัง
> บันทึก
> 
> ### Stacktrace / ข้อความแสดงข้อผิดพลาดแบบเต็ม
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c369a8]
> 
> goroutine 50 [running]:
> github.com/docker/compose-cli/local/compose.(*composeService).Logs.func1(0x0, 0x0)
> 	github.com/docker/compose-cli/local/compose/logs.go:54 +0x188
> golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00033cb10, 0xc0000d21e0)
> 	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
> created by golang.org/x/sync/errgroup.(*Group).Go
> 	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
> ```
> 
> ## ข้อมูลเพิ่มเติม
> เวอร์ชันของระบบปฏิบัติการ / การแจกจ่าย`docker-compose`วิธีการติดตั้ง ฯลฯ
