### ISSUE TITLE
Debian-1.29.0 uses older version of Debian than previous versions

### ISSUE THREAD

**Issue by KevinAtSesam** [docker/compose#8349]
## Description of the issue
This issue is directly related to the official docker-compose images hosted on hub.docker.com:
https://hub.docker.com/r/docker/compose

## Context information

**compose:/debian-1.28.0**
```
STEP 1: FROM docker/compose:debian-1.28.0 AS compose
Getting image source signatures
[...]
Writing manifest to image destination
Storing signatures
STEP 2: RUN cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**compose:/debian-1.29.0**
```
STEP 1: FROM docker/compose:debian-1.29.0 AS compose
Resolved "docker/compose" as an alias (/home/kevin/.cache/containers/short-name-aliases.conf)
Getting image source signatures
[...]
Writing manifest to image destination
Storing signatures
STEP 2: RUN cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

## Steps to reproduce the issue
- Clone the images locally and use a simple `cat /etc/*release*`
- Check the manifests

## Expected result
I think it's reasonable to assume that newer versions of images, don't use older versions of Debian to run on. To make matters worse, debian-1.28.1 also uses Debian 9 as a base distribution, breaking a lot of compatibility even with just small patches.

I'm not sure how your backend is arranged, and this is likely just a small configuration issue, but its certainly something that should be avoided in the future.

**Comment by KevinAtSesam** [comment]
Issue reproduced with `compose:debian-1.29.2`, which is also still based on Debian 9

**Comment by thaJeztah** [comment]
I guess this is related to https://github.com/docker/compose/pull/8058 (which was done to resolve https://github.com/docker/compose/issues/8048)

**Comment by KevinAtSesam** [comment]
Issue is still very relevant and very much a blocker for some workflows.
