### ISSUE TITLE
Still slow AF

### ISSUE THREAD

**Issue by Jurek-Raben** [docker/compose#8363]
Docker is a nice software, and free, thanks for that. But honestly, the startup time even on a fast ssd and overall performance is quite horrible, also with the recent version. I am using it on macos, can't tell about other systems. Can you please improve the performance drastically? Just doing optimizations for a whole month with the whole team?

**Comment by mik-laj** [comment]
It is on the roadmap. https://github.com/docker/roadmap/issues/7
