### ISSUE TITLE
Unable to build container over Amazon Linux (unable to prepare context: unable to find 'git': exec: "git": executable file not found in $PATH)

### ISSUE THREAD

**Issue by AyaanRanosys** [docker/compose#8368]
## Unable to build container over Amazon Linux (unable to prepare context: unable to find 'git': exec: "git": executable file not found in $PATH)
```
docker-compose build
Building pr-server
unable to prepare context: unable to find 'git': exec: "git": executable file not found in $PATH
ERROR: Service 'pr-server' failed to build : Build failed
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
```

**Output of `docker version`**
```
Client:
 Version:           20.10.4
 API version:       1.41
 Go version:        go1.15.8
 Git commit:        d3cb89e
 Built:             Mon Mar 29 18:54:36 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.4
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.8
  Git commit:       363e9a8
  Built:            Mon Mar 29 18:55:03 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
docker-compose config
services:
  pr-server:
    build:
      context: https://<username>:<password>@<git-repo>.git#develop
      dockerfile: ./Dockerfile
    container_name: pr-server-container
    environment:
      COMPOSE_PROJECT_NAME: pr-sr-gd
    image: pr-server-image:gd
    ports:
    - published: 80
      target: 3000
version: '3.9'
```

## Steps to reproduce the issue

1. Run `docker-compose build` or `docker-compose up`

### Observed result
Following error:
```
Building pr-server
unable to prepare context: unable to find 'git': exec: "git": executable file not found in $PATH
ERROR: Service 'pr-server' failed to build : Build failed
```

### Expected result
Container should build successfully.

### Stacktrace / full error message
```
Building pr-server
unable to prepare context: unable to find 'git': exec: "git": executable file not found in $PATH
ERROR: Service 'pr-server' failed to build : Build failed
```

## Additional information
**cat /etc/system-release - output **
```
cat /etc/system-release
Amazon Linux release 2 (Karoo)
```

**cat /etc/os-release - output **
```
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Steps followed to install docker and docker compose**
```
 sudo yum -y install docker
 sudo service docker start
 sudo usermod -a -G docker $USER
 sudo chkconfig docker on
 sudo curl -L --fail https://raw.githubusercontent.com/linuxserver/docker-docker-compose/master/run.sh -o /usr/local/bin/docker-compose
 sudo chmod +x /usr/local/bin/docker-compose
 sudo groupadd docker
 sudo usermod -aG docker $USER
 newgrp docker
 docker run hello-world
```
(Tried `reboot `as well)

**Git version**
```
git --version
git version 2.23.4
```

I have my local development setup where I am using Docker desktop. With it everything is working fine but not with EC2 Amazon linux setup.

**Comment by kedbirhan** [comment]
experiencing a similar problem here as well when trying to setup filebeat  (docker-compose -f setup_certs_and_filebeat.yml run --rm setup_filebeat). It pulls the image and composes hangs after outputting the below message. works fine when i manually run the compose file. but it won't finish when run in user data.
compose.cli.main.call_docker: /usr/bin/docker start --attach --interactive 81235e2d12ee3e26e139731a714aeaaa5ec5e57ada3ce5889cce7d6a4059ad4d

**Comment by akilarandil** [comment]
any update on this?

**Comment by chimera-rep** [comment]
Same problem

**Comment by RadekKpc** [comment]
Same problem

**Comment by j-don** [comment]
To the next poor soul who finds themselves here, remember the machine building your image may not be the machine you entered the `docker build` or `compose build` command on. What matters is if the machine that is doing the actual image build has git installed. Check your $DOCKER_HOST environment variable.

My specific case was using the gitlab suggested method of running `docker:dind` as a service container on a kubernetes runner. The solution to that is either your own custom image derived from `docker:dind` that includes git as the service container, or running `docker:dind` as your build container and manually running `dockerd-entrypoint.sh &` since gitlab will override the entrypoint for the build container.
