### ISSUE TITLE
Show confirmation message on `docker-compose down`

### ISSUE THREAD

**Issue by ShockwaveNN** [docker/compose#8374]
**Is your feature request related to a problem? Please describe.**

I think a lot of us had situation in which you've called `docker-compose down` instead of `docker-compose stop` and removed all containers with data

**Describe the solution you'd like**
Add a simple warning message 
```
# docker-compose down
This will stop and remove all your containers. Are you sure [y/N]
```

**Additional context**
check on Ubuntu 20.04 with `docker-compose version 1.29.2, build 5becea4c`

**Comment by Madpeterz** [comment]
maybe with support for "-y" flag to bypass the check

**Comment by ShockwaveNN** [comment]
Hi bot, please do not close that issue

**Comment by ShockwaveNN** [comment]
This idea is actual for v2.6.0 of `docker compose`. Still no any kind of warning (

**Comment by davemsh** [comment]
I'd like to see this feature added as well.

**Comment by ndeloof** [comment]
`docker-compose down` does not remove volumes, so if you use those, data won't get lost.

Introducing a confirmation to `compose down` would be a significant compatibility break which will have impact on thousands users having scripts to manage compose applications, that's not an option we can adopt.
