### ISSUE TITLE
List containers in order they are requested from `docker-compose ps ...`

### ISSUE THREAD

**Issue by arnegroskurth** [docker/compose#8384]
**Is your feature request related to a problem? Please describe.**

The output of `docker-compose ps [-q] ...` is currently sorted by service-name (see: https://github.com/docker/compose/blob/master/compose/cli/main.py#L796) rather then by the order the services might have been given as arguments. This makes it harder to parse the output to build a name-to-container-id map in scripts invoking docker-compose.

**Describe the solution you'd like**

Match service-order given as arguments in output order if given specific service names.

This would be a small change but might have to be considered a BC.

**Describe alternatives you've considered**

Add a `--format` capability similar to `docker ps --format ...` to be able to retrieve both the service name and the container id in a single line.

This would not be a BC but would obviously require more work.

See:
- https://github.com/docker/compose/pull/6391
- https://github.com/docker/compose/issues/2369

**Comment by ndeloof** [comment]
You should consider adopting Compose v2 (https://github.com/docker/compose-cli#compose-v2-aka-local-docker-compose) as this one allows to use json output, and make it easier to post-process `ps` output by scripts:

```
 docker compose ps --format json |jq 'sort_by(.ID) | .[] | {id:.ID, name:.Name}'
{
  "id": "4e61e3d0023d2aec421761371d0778abf2e338f7d1b12950041f5a787024f1a4",
  "name": "truc_myservice_1"
}
```
