### ISSUE TITLE
Feature request: update v3 with all of v2's features and deprecate v2.

### ISSUE THREAD

**Issue by ibex-are-goats** [docker/compose#8386]
In 2017 it was suggested that v2 is preferred over v3 and would not be deprecated. https://github.com/docker/compose/issues/4513#issuecomment-281478365

**Comment by ndeloof** [comment]
v2 and v3 are both obsolete, docker-compose has adopted compose-spec (https://compose-spec.io/) since 1.28 and does not require a `version` in compose files anymore. All attributes are now supported
