### ISSUE TITLE
No UTS namespace option

### ISSUE THREAD

**Issue by kooyunmo** [docker/compose#8408]
Hi, to my best knowledge, it seems that docker-compose does not support UTS setting as docker (https://docs.docker.com/engine/reference/run/#uts-settings---uts).

There already exist some reported issues related to this (https://github.com/docker/compose/issues/3338), but I still cannot use the option by specifying `uts_mode: host` or `ust: host` in `docker-compose.yml`.

I think this is the important feature for the users who have to use GPU collective communication libraries like NCCL, since it requires to set `--uts=host`.

**Comment by ndeloof** [comment]
There's no reason this isn't supported, just nobody did so far :D
Please open an issue on https://github.com/compose-spec/compose-spec so this is added to the compose format

**Comment by man4red** [comment]
Could we reopen this?
