### ISSUE TITLE
docker-compose v2 missing shorthand flag -v

### ISSUE THREAD

**Issue by marvinGitHub** [docker/compose#8418]
With the new docker-compose version (v2) there is a missing shorthand flag in order to show the current version. With docker-compose v1 the shorthand flag -v still works. 

Is there a possibility that this will be fixed with future releases?

**Comment by tianon** [comment]
It's also missing the long form `--version` flag (although it does have the `version` subcommand).

**Comment by ndeloof** [comment]
Compose V2 indeed has an explicit command to show version, it does not rely on a flag/pseudo-command
For backward compatibility, compose-switch translates docker-compose command line into the adequate docker compose command, I've created https://github.com/docker/compose-switch/pull/2 to add support for missing `-v`

**Comment by thaJeztah** [comment]
Should we have a (hidden) `-v` / `--version` flag also on the `docker compose` command, to ease transition? (otherwise setups may be "stuck" on using `compose-switch`?

**Comment by ndeloof** [comment]
@thaJeztah would make sense indeed
