### ISSUE TITLE
Add `security-opt` option for fig.yml

### ISSUE THREAD

**Issue by sigelinde** [docker/compose#842]
Docker 1.3+ support `--security-opt` option for `docker run`, but fig is not.
http://blog.docker.com/2014/10/docker-1-3-signed-images-process-injection-security-options-mac-shared-directories/

**Comment by lsowen** [comment]
Does anyone know if there are any plans to support this?

**Comment by lsowen** [comment]
Looks like most of the heavy lifting was already completed in docker-py (docker/docker-py@1845d3b13fd7d964dea448fb82a29bde085c5d0f).  I've implemented the few changes in docker-compose required to support it in my fork: https://github.com/lsowen/compose

**Comment by thaJeztah** [comment]
@lsowen if you have implemented this, perhaps you can create a pull-request?

**Comment by lsowen** [comment]
@thaJeztah It currently relies on a development version of docker-py, so my plan was to wait until it had been released on pypi.  Should I go ahead and create a pull request before then?

**Comment by thaJeztah** [comment]
@lsowen I'm not a maintainer here, but you can create a PR with the changes, mentioning that it relies on a newer version of `docker-py`, that hasn't been released yet. (Or something similar :))

**Comment by lsowen** [comment]
Looks like docker-py v1.2.0 was just released, so I'm planning on updating/squashing and creating a PR.

**Comment by lsowen** [comment]
Just created #1382.

**Comment by lsowen** [comment]
This can be closed now because #1382 has been merged.
