### ISSUE TITLE
docker-compose exec dose not print any error message when an invalid service is provided

### ISSUE THREAD

**Issue by ylockerman** [docker/compose#8420]
## Description of the issue
docker-compose exec will not print any error messages when an invalid service is provided. This makes it very hard to detect and diagnose errors.

## Context information (for bug reports)
It seems like PR #8213 blocked printing any error messages for the exec command. While I understand that error messages is unwanted in the case a program runs. In the case that the user provided a valid input, it would be very helpful to see what the error is.

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```
/!\ If `docker-compose version` reports v2.0...` you're using the wrong repository, please report issues on [Compose-CLI](https://github.com/docker/compose-cli/issues/new)

**Output of `docker version`**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. Run `docker-compose exec foo bash` in a directory with a compose file
2. Note the lack of error
3.

### Observed result
no message

### Expected result
An error message

**Comment by stevelacey** [comment]
Yep, ran into this after upgrading, this message became nothing more than an exit 1.

Before:

```
docker-compose exec backend something
**ERROR:** No container found for backend_1
```

After:

```
docker-compose exec backend something
```
