### ISSUE TITLE
dns: is not adding nameservers to /etc/resolv.conf, dns_search: still does

### ISSUE THREAD

**Issue by jonfen** [docker/compose#8441]
## Description of the issue

- dns: is not adding nameservers to /etc/resolv.conf, dns_search: still does
- full running example below

Reference: https://docs.docker.com/config/containers/container-networking/#dns-services

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
Also tried with:
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
/!\ If `docker-compose version` reports v2.0...` you're using the wrong repository, please report issues on [Compose-CLI](https://github.com/docker/compose-cli/issues/new)

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  compose-dns-test:
    command: tail -f /dev/null
    container_name: compose-dns-test
    dns:
    - 8.8.8.8
    - 8.8.4.4
    dns_search:
    - domain.local
    - domain.com
    image: ubuntu:latest
version: '3.8'
```

## Steps to reproduce the issue
```
#!/bin/bash
docker-compose up &
sleep 2
docker exec -it compose-dns-test cat /etc/resolv.conf
sleep 2
docker-compose down
sleep 2
docker system prune -f
docker run -d -t --name docker-dns-test --dns='8.8.8.8' --dns='8.8.4.4' ubuntu:latest
sleep 2
docker exec -it docker-dns-test cat /etc/resolv.conf
sleep 2
docker stop docker-dns-test
```
### Observed result
**docker-compose**
```
search domain.local domain.com
nameserver 127.0.0.11
options edns0 trust-ad ndots:0
```
**docker**
```
search imlss.local imlss.com
nameserver 8.8.8.8
nameserver 8.8.4.4
docker-dns-test
```
### Expected result
**docker-compose**
```
search domain.local domain.com
nameserver 127.0.0.11
nameserver 8.8.8.8
nameserver 8.8.4.4
options edns0 trust-ad ndots:0
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Ubuntu 20.04
docker install: apt
docker-compose install: https://docs.docker.com/compose/install/#install-compose-on-linux-systems

**Comment by programmerq** [comment]
This is expected behavior. Any docker container that is connected to a user defined network will always have the 127.0.0.11 resolver in the resolv.conf. This enables service discovery for other containers connected to that same network.

Docker compose will by default create a user defined network and attach the containers to it, so you'll always see 127.0.0.11 unless you go out of your way to make your compose project use the legacy docker0 network.

When you specify dns servers on a container attached to a user-defined network, the 127.0.0.11 resolver will use those resolvers as the upstream resolver.

You can observe this behavior with non-compose created containers as follows:

```
$ docker run --rm -it --dns 8.8.8.8 --dns 8.8.4.4 ubuntu:latest cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
$ docker network create testnet
$ docker run --rm -it --dns 8.8.8.8 --dns 8.8.4.4 --net testnet ubuntu:latest cat /etc/resolv.conf
nameserver 127.0.0.11
options edns0 trust-ad ndots:0
```

Here's an example of the 8.8.8.8 being used when you look at the traffic with a packet capture. Here's the command:

```
$ docker run --rm -it --net test --dns 8.8.8.8 nicolaka/netshoot drill google.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 43766
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; google.com.	IN	A

;; ANSWER SECTION:
google.com.	248	IN	A	142.250.80.14

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 14 msec
;; SERVER: 127.0.0.11
;; WHEN: Tue Aug 24 14:04:45 2021
;; MSG SIZE  rcvd: 44
```

and here's the output of the packet capture that was running on that docker host (192.168.1.91):

```
$ sudo tshark -i eth0 'host 8.8.8.8 and port 53'
Capturing on 'eth0'
    1 0.000000000 192.168.1.91 → 8.8.8.8      DNS 70 Standard query 0xaaf6 A google.com
    2 0.013205459      8.8.8.8 → 192.168.1.91 DNS 86 Standard query response 0xaaf6 A google.com A 142.250.80.14
```

I vote to close this

**Comment by exFalso** [comment]
**Is** this expected behaviour? Specifying an explicit IP for DNS and having a completely different one written into resolv.conf?
