### ISSUE TITLE
docker-compose exec returns (0) for invalid flags

### ISSUE THREAD

**Issue by dsoprea** [docker/compose#8443]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Lately I've been inadvertently passing "-i -t" to "docker-compose exec". docker-compose will just ignore it and return success. It confounds me and I've lost an hour over the couple of times it's taken me to figure out what I'm doing wrong. I'm not sure why "-i" nor "-t" cause it to fail since neither is a valid parameter. Conversely, I'm not sure what the design of docker-compose is such that I can call "exec" with a valid image and command-line, it doesn't do anything, and yet it still somehow returns success. Seems like there are a couple of bugs coming from both angles, here.

**Steps to reproduce the issue:**

Start the services:

```
$ docker-compose up --build redis-db test-server
```

With the invalid flags:

```
$ docker-compose exec -i -t test-server /bin/bash 
$ echo $?
0
```

Neither are valid command-line flags for docker-compose 1.29.2:

```
$ docker-compose exec -h
Execute a command in a running container

Usage: exec [options] [-e KEY=VAL...] [--] SERVICE COMMAND [ARGS...]

Options:
    -d, --detach      Detached mode: Run command in the background.
    --privileged      Give extended privileges to the process.
    -u, --user USER   Run the command as this user.
    -T                Disable pseudo-tty allocation. By default `docker-compose exec`
                      allocates a TTY.
    --index=index     index of the container if there are multiple
                      instances of a service [default: 1]
    -e, --env KEY=VAL Set environment variables (can be used multiple times,
                      not supported in API < 1.25)
    -w, --workdir DIR Path to workdir directory for this command.
```

**Describe the results you received:**

Returned (0) status code. No action, no result, no feedback on what happened.

**Describe the results you expected:**

An error telling me that those flags are invalid. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.0
CPython version: 3.9.5
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 48
  Running: 12
  Paused: 0
  Stopped: 36
 Images: 1510
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 36cc874494a56a253cd181a1a685b44b58a2e34a.m
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.13.0-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.56GiB
 Name: dustinxps
 ID: MFN3:QSSU:R2XJ:6CJW:626T:SMRG:ZM2J:YA6Y:UH73:PQUK:4NL6:KF7P
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by klittlepage** [comment]
I hit a related issue today; `docker-compose exec` has an exit code of `(0)` when passed a non-existent service as an arg and no command to execute:

```
docker-compose exec does-not-exist
echo $?
0

docker-compose exec does-not-exist foo
echo $?
1
```

**Comment by dsoprea** [comment]
No one cares to discuss this? A command-line utility that ignores command-line errors is problematic. Can someone at least gauge the complexity of the task?

**Comment by dsoprea** [comment]
Bump.

**Comment by ndeloof** [comment]
About the original issue:
`docker compose exec` supports the `-i` and `-t` flags to offer a smooth interoperability with `docker exec`. Those have no effect as been set by default by `compose exec`, but we noticed many users have this habit to run `exec -it` whenever they run `docker` or `docker compose`, so we silently ignore those.

@klittlepage seems this has been fixed in the meantime
```
➜  docker compose exec test-server /bin/bash 
service "test-server" is not running container #1
➜  echo $?
1
```

**Comment by dsoprea** [comment]
Can you reference a commit? Has this been released yet?

**Comment by dsoprea** [comment]
Not sure. I don't see a function returning a status/exit code that wasn't already returning one before.

**Comment by dsoprea** [comment]
If you notice it where it occurs to you where that is, feel free to share it for reference.
