### ISSUE TITLE
option user is type of string only

### ISSUE THREAD

**Issue by kmursk** [docker/compose#8453]
## Description of the issue
Compose file reference says "_domainname, hostname, ipc, mac_address, privileged, read_only, shm_size, stdin_open, tty, **user**, working_dir. Each of these is a single value, **analogous to its docker run** counterpart_". Docker run reference says "_Those users are accessible by name. When passing a numeric ID, the user does not have to exist in the container. <...> if you pass a numeric uid, it must be in the range of 0-2147483647._". But docker-compose does not support user option of type number. 
## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.26.0, build d4451659
```
**Output of `docker version`**
```
Docker version 20.10.7, build f0df350
```
**Output of `docker-compose config`**
```
docker-compose -f busybox.yml config
ERROR: The Compose file './busybox.yml' is invalid because:
services.testcase.user contains an invalid type, it should be a string
```
## Steps to reproduce the issue
Run docker-compose where compose file contains option "user" with number.
### Observed result
ERROR: The Compose file './busybox.yml' is invalid because:
services.testcase.user contains an invalid type, it should be a string
### Expected result
services:
  testcase:
    image: busybox
    **user: 1000**
version: '3.8'
## Additional information
WSL2

**Comment by thaJeztah** [comment]
I think this value always has to be passed as a string (within quotes); even if it's a numeric user-id (`user: '1000'`)

**Comment by thaJeztah** [comment]
When passing options on the command-line, options are _always_ strings (unlike in a yaml file, where they can be either a numeric value or a string, depending on if there's quotes or not)

**Comment by kmursk** [comment]
Yes, you are right. Quotes make possible to set user as uid. Thanks.

**Comment by GemN** [comment]
How do you use an environment variable to set the user?

Passing `user: $UID` or `user: "$UID"` will always replace by `user: 501` (or any id) and show the error "must be a string"

**Comment by kmursk** [comment]
I used hard coded numeric uid with quotes as @thaJeztah advised. It's a good thought to use variable instead, but it hasn't a value on start of container (or rather not every container) and there is really trouble to make it with
```
environment:
    - UID: "1000"
```
because of error 
> environment contains {"UID": "1000"}, which is an invalid type, it should be a string

**Comment by GemN** [comment]
Yes that's why I ask how to use a env variable, my docker-compose have a lot of values based on the environment variable $UID. This is a breaking change and despite search for, I couldn't find a way (or at least a workaround) unless I do echo $UID and then replace all the values in the docker compose by the UID.
