### ISSUE TITLE
Provide a mechanism to retrieve project name

### ISSUE THREAD

**Issue by rupert-madden-abbott** [docker/compose#8456]
**Is your feature request related to a problem? Please describe.**
docker-compose does not always provide a way to do everything and sometimes it is necessary to use docker directly instead. To do this I must know the project name.

**Describe the solution you'd like**
Some kind of command e.g. docker-compose project or docker-compose info which lets me extract this information.

**Describe alternatives you've considered**
I can assume it is the current directory but this is brittle and hard to script.

I've tried to parse the output of docker-compose ps but the column wrapping makes this impossible.

**Comment by ndeloof** [comment]
With latest docker compose v2 you can use :
`docker compose config --format json | jq '.name'`

We could extend format to support go template (like a few docker command do) so one can run
`docker compose config --format '{{.name}}'`
or maybe even introduce a dedicated flag for this purpose
`docker compose config --name`
