### ISSUE TITLE
Error white retreiving https git urls

### ISSUE THREAD

**Issue by n3m6** [docker/compose#8461]
## Description of the issue
Error while retrieving https git repos.
```
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /usr/lib/git-core/git-remote-https: /tmp/_MEI3kvDlV/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib/x86_64-linux-gnu/libssh.so.4)
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
1.29.2
```
/!\ If `docker-compose version` reports v2.0...` you're using the wrong repository, please report issues on [Compose-CLI](https://github.com/docker/compose-cli/issues/new)

**Output of `docker version`**
```
docker version 
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. Install docker-compose 
2. Run `docker-compose build` with any docker-compose file that includes a git https repo

## Additional information

Ubuntu 20.04 

Downgrading to 1.27.4 of docker-compose resolved the issue.

**Comment by Melak12** [comment]
I am having the same issue.

**Comment by skynet01** [comment]
Any updates on this? It's still a thing half a year after

**Comment by glours** [comment]
Compose v1 is not the default version anymore and will only be updated for security purpose, please use the Compose V2 version instead.
