### ISSUE TITLE
newlines in environment variables not propagated correctly

### ISSUE THREAD

**Issue by andrewalexander** [docker/compose#8463]
## Description of the issue

When using `docker-compose version 1.29.2, build 5becea4c`, we are able to set an environment variable containing new lines in it. This would get parsed by our application in the past and was working well. 

When using `Docker Compose version v2.0.0-beta.6`, the newlines in the variable get stripped and our application fails to parse the value. 

## Context information (for bug reports)
We pull a secret from vault and set the environment variable before invoking docker-compose. The secret in this case is a private cert, which is very sensitive to newlines. 

Our workaround so far is to use `docker-compose disable-v2` but were hoping there'd be some guidance on how we should approach this further. 

If this is a change in how `docker compose` parses newlines, we can potentially make the necessary changes to account for that. 

If, however, this is more of a regression/bug, we would like to know that we just have to wait for the fix and remove the `disable-v2` from our scripts. 

**Output of `docker-compose version`**
```
Docker Compose version v2.0.0-beta.6
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
WARN[0000] The JWT_SIGNING_CERT variable is not set. Defaulting to a blank string.
WARN[0000] The JWT_SIGNING_KEY variable is not set. Defaulting to a blank string.
services:
  api:
    build:
      context: /tmp/api
      dockerfile: /tmp/api/docker/Dockerfile.api
    environment:
      # redacted irrelevant config
      JWT_SIGNING_CERT: "" # populated from vault
      JWT_SIGNING_KEY: "" # populated from vault
      PORT: "8080"
      STORE_TYPE: postgres
    hostname: api
    image: {redacted-internal-registry}/api
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: 8080
      protocol: tcp
networks:
  default:
    name: api_default
```

## Steps to reproduce the issue

1. Create an RSA certificate and assign the value of it to the `JWT_SIGNING_CERT` variable
2. Try to decode that value from within a container (we use the golang `encoding/pem` standard library to [pem.Decode()](https://pkg.go.dev/encoding/pem#Decode) it)
3. Run the container using `docker compose up` (`v2.0.0-beta.6`) - see it fail to decode 
4. Run the container using `docker-compse up` (`1.29.2, build 5becea4c`) - see it successfully pem.Decode
5. Run the container using `docker-compose disable-v2 up` (`v2.0.0-beta.6`) - see it succeed as well

### Observed result
No newlines in environment variable:

```
-----BEGIN CERTIFICATE----- MIIF.....
``` 

### Expected result

Newlines preserved in environment variable:

```
-----BEGIN CERTIFICATE-----
MIIF...
```

### Stacktrace / full error message

N/A - issue is with behavior, not a specific error message.

## Additional information
Running Docker Desktop on MacOS - 3.5.2 

1.29.2 version of docker-compose installed via homebrew.

**Comment by rdfedor** [comment]
I'm running into this issue also.  Since i've upgraded, this has broken where I'm getting an error,

```yaml: line 312: could not find expected ':'```

The environment variables for a public key are passed in through the environment so it looks like this,

```
   environment:
    ...
     JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
    ...
```

Once I  removed that  line,  everything compiled properly.
