### ISSUE TITLE
mem_swappiness not working

### ISSUE THREAD

**Issue by cdalexndr** [docker/compose#8466]
## Description of the issue

Docker compose file version 2.4.
Service config `mem_swappiness` has no effect.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
/!\ If `docker-compose version` reports v2.0...` you're using the wrong repository, please report issues on [Compose-CLI](https://github.com/docker/compose-cli/issues/new)

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8919
 Built:             Sat Jan 30 03:17:11 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:15:40 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
   my-service;
     mem_swappiness: 75
```

## Steps to reproduce the issue

1. set mem_swappiness
2. run the service
3. docker exec -it my-service sh
4. cat /proc/sys/vm/swappiness

### Observed result
60

### Expected result
75

### Stacktrace / full error message

```
(paste here)
```

## Additional information

Linux li1401-73.members.linode.com 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64 GNU/Linux

docker info shows: `WARNING: No swap limit support`

**Comment by LinFor** [comment]
Have the same issue. docker inspect shows `"MemorySwappiness": null,` while compose file contains `mem_swappiness: 100` for that service

**Comment by Fs00** [comment]
@glours @laurazard Sorry for the random tagging, but the bug is still present on Docker Compose version v2.12.1.
Can this issue be reopened and triaged? Thanks for your patience 🙏

**Comment by teresanovielloatinstana** [comment]
Hello team, the bug is still present on Docker Compose version v2.20.3.
Can this issue be reopened and triaged? Thanks for your patience 🙏

**Comment by mdeeter** [comment]
I'm seeing this issue as well.

**Comment by jsecrest** [comment]
Still an issue in Docker Compose version v2.34.0-desktop.1 as well.

**Comment by ryanjtang** [comment]
does anyone have a fix for this?
