### ISSUE TITLE
Invalid environment variables substitution

### ISSUE THREAD

**Issue by belegnar** [docker/compose#8481]
## Description of the issue

Containder environment variables are not correctly calculated

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

```
/!\ If `docker-compose version` reports v2.0...` you're using the wrong repository, please report issues on [Compose-CLI](https://github.com/docker/compose-cli/issues/new)

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
ERROR: Missing mandatory value for "environment" option interpolating {'VAR': '${SOME_VALUE:?set SOME_VALUE}'} in service "service": set SOME_VALUE
```

## Steps to reproduce the issue

```
$ cat docker-compose.yml
version: "3.7"

services:
  service:
    build: .
    environment:
      VAR: ${SOME_VALUE:?set SOME_VALUE}
```
```
cat docker-compose.override.yml
version: "3.7"

services:
  service:
    environment:
      VAR: value
```
### Observed result
Environment variable absent error

### Expected result
```
$ docker-compose config
services:
  service:
    build:
      context: /private/tmp/2
    environment:
      VAR: value
version: '3.7'
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.
MacOS

**Comment by leppaott** [comment]
Yes latest updates broke Mac environment variable usage.

Also similar to https://github.com/roboll/helmfile/issues/476 a long number in env file like VAR=123123123 and used on compose with "${VAR}" is converted to scientific notation...

**Comment by brennongs** [comment]
Also experiencing this -- whole team using docker compose needing to revert to docker-compose until this is fixed.
