### ISSUE TITLE
Failed to compute cache key when file doesn't exist but isn't needed

### ISSUE THREAD

**Issue by leppaott** [docker/compose#8487]
On latest Docker for Mac:

We have .dockerignore:

> **
> !A/package.jar
> !B/package.jar

Presumption: A is built so that it has its jar and B's jar isn't built.

A's dockerfile doesn't reference B at all but when we build A:

`docker-compose build A`

It tries to load build definition and  load .dockerignore for B although I'm not building B and we get:

> [B 2/4] COPY B/package.jar /knome/:
> failed to solve: rpc error: code = Unknown desc = failed to compute cache key: "B/package.jar" not found: not found`.

Although this is in B's dockerfile.

Now I notice this isn't the case if I remove B from the build definition: **A has depends_on B.**

Is this required or a bug, that B's dockerignored file must exist when I build A? This used to work fine before.

Kind of annoying that my image works when I create a dummy file:
`touch B/package.jar`

**Comment by leppaott** [comment]
It seems that this isn't even about the dockerignore but just about trying to load B's build cache because A has depends_on.

**Comment by ndeloof** [comment]
Can you please paste output of `docker-compose version`?

**Comment by leppaott** [comment]
@ndeloof this no longer seems to be present in the latest docker for mac: docker-compose version 1.29.2.

**Comment by brendensoares** [comment]
Still happening for `Docker Compose version v2.4.1` using buildkit.

I've tried changing the file name, permissions, owner, group, etc. Also, I tried placing it in relative and absolute paths within the image.

Can't get around the error `failed to solve: failed to compute cache key: "/{FILE.NAME}" not found: not found`
