### ISSUE TITLE
Support docker files not named Dockerfile.

### ISSUE THREAD

**Issue by kballenegger** [docker/compose#85]
I'd like to be able to specify:

``` yml
build: myfile.docker
```

Right now, this throws an error, even if there's a valid docker file at that path. Instead, it expects a directory with a file named `Dockerfile`. That's a good default, but it'd be nice the support pointing to files directly, also.

**Comment by Maxim-Filimonov** [comment]
Docker 1.5 supports specifying filename using -f. Would be handy if Fig/Docker-compose supported it too.
```
➜ docker -v
Docker version 1.5.0, build a8a31ef
➜ docker build --help

Usage: docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH

  -f, --file=""        Name of the Dockerfile(Default is 'Dockerfile' at context root)
```

**Comment by dnephin** [comment]
This is being tracked in #834
