### ISSUE TITLE
docker-compose v2.0.0-rc.1 breaks backward compatibility for variable names in env files

### ISSUE THREAD

**Issue by fsiegrist** [docker/compose#8507]
**Steps to reproduce the issue:**
1. Add the following to your docker-compose.yaml:
```
    env_file:
    - my_env_file.env
``` 
2. Add a variable containing a hyphen in its name to the .env file:
```my-variable=value```
3. Call docker-compose up or docker compose up

**Result received:**
invalid variable name "my-variable"

**Result expected:**
docker-compose up runs without errors

**Output of `docker-compose --version`:**

```
Docker Compose version v2.0.0-rc.1
```

**Output of `docker version`:**

```
Docker version 20.10.8, build 3967b7d
```

**Output of `docker context inspect default`:**  

```
[
    {
        "Name": "default",
        "Metadata": {
            "StackOrchestrator": "swarm"
        },
        "Endpoints": {
            "docker": {
                "Host": "unix:///var/run/docker.sock",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
    }
]

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 98
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.938GiB
 Name: docker-desktop
 ID: BHJO:7FXM:LN3W:7I3X:XSGB:BG7Z:HCRR:4T7K:QYJU:QSNH:RO6H:C2Z3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by andyg101** [comment]
Also experiencing this issue. Are these variable names actually invalid or will docker compose be updated to accomodate them?

**Comment by ndeloof** [comment]
> Are these variable names actually invalid

Documentation is unclear, and it seems we will need to align with _de facto_ compose V1 behavior regarding this ambiguous syntax

**Comment by nevergone** [comment]
Related commit:
https://github.com/compose-spec/godotenv/blob/655269e2565760ac457e473904300398c6150d47/parser.go#L113

**Comment by nevergone** [comment]
If the variable name contains a dot in the env_file key file, this will cause an error in docker-compose 2.x. If the same variable is below environment key, it works.
This worked perfectly fine under 1.29.x, please reset it. Why does docker-compose need to handle this? Why doesn't the container shell do this?

**Comment by ndeloof** [comment]
dot env file parser has been integrated in compose-go so we have more flexibility on supported format, and rules have been relaxed to support dots and comas https://github.com/compose-spec/compose-go/tree/master/dotenv
