### ISSUE TITLE
Docker compose down or stop does not work if used with a project name

### ISSUE THREAD

**Issue by younkim** [docker/compose#8509]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 11C3EA09-8CDC-4BDF-94F8-B920D894B913/20210823142125

### Expected behavior
`docker-compose -p project_name down` should bring down the containers set within the project name `project_name` using the docker environment variables in `.env` located in the directory where `docker-compose.yml` is located.

### Actual behavior
When using a project name for the compose setup using the experimental feature toggled on, docker doesn't appear to read the `.env` file and causes `down` to fail, citing missing environment variables. `stop` also doesn't work. `up` seems to work fine.

`down` or `stop` works without issues if `-p` is not used.

Individual containers within `project_name` can be removed manually from the GUI, but `project_name` as a whole cannot be removed from the GUI.

### Information

  - macOS Version: 11.5.2
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.6.0 (67351)

### Steps to reproduce the behavior

  1. `docker-compose -p project_name up` (reads .env` correctly)
  2. `docker-compose -p project_name down` doesn't seem to read `.env and prints something like the following:

```
WARN[0000] The "NETWORKS_DRIVER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "NETWORKS_DRIVER" variable is not set. Defaulting to a blank string. 
...
```

**Comment by adifelice-godaddy** [comment]
I think this stopped happening in recent versions.
