### ISSUE TITLE
Externally Linked Containers can no longer be found

### ISSUE THREAD

**Issue by RedactedProfile** [docker/compose#8511]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Externally linked containers names are not resolvable.  /etc/hosts file shows a blank where the name would usually be 
![image](https://user-images.githubusercontent.com/1039911/127053649-6f09aa26-e4ac-4ab5-bcb3-251552aaee9e.png)

### Expected behavior

Externally linked containers name should be resolvable within the container, so long as the container is up and running, and on the same network.  /etc/hosts file should show the linked containers name as an alias to the discovered IP address entry with a hash based alias as well

![image](https://user-images.githubusercontent.com/1039911/127053947-1cf4cb3a-863f-49a3-aa4a-74668be919a0.png)

### Information

  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? Most likely, but also fresh install

  - Windows Version: 
  - Docker Desktop Version: Windows 10 Pro 20H2
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

Quick and Dirty Example

1. Spin up a MySQL Server container (I called mine: "mysql_database")
2. Spin up another container on the same network with 
```yaml
    external_links:
      - "mysql_database"
```
3. inside the container linking to mysql_database, try to ping the container name, it wont find it. 
4. `cat /etc/hosts` will show something like this:
![image](https://user-images.githubusercontent.com/1039911/127053649-6f09aa26-e4ac-4ab5-bcb3-251552aaee9e.png)

Current Docker Version:
![image](https://user-images.githubusercontent.com/1039911/127054906-509a070d-7f6a-4278-a0ac-3bd38f44844c.png)

**Comment by ktallafus** [comment]
Having the same problem. It startet yesterday out of the blue after updating to Docker Desktop 4.2.0 ( Windows 10 21H1 Build 19043.1348). Tried downgrading to 4.1.1 but it still happens? What I also noticed is that links between containers (in the same docker-compose.yml) show the same behaviour when using network_mode: bridge. With default network links are still working.

**Comment by rkampas-mlg** [comment]
It's still not fixed.
