### ISSUE TITLE
`docker compose` does not handle variable defaults in --env-file (`docker-compose` does) 

### ISSUE THREAD

**Issue by jj-meyer** [docker/compose#8519]
**Description**
Variables defaults declared in the --env-file are not passed to a compose-file.

```bash
$ docker compose version
    Docker Compose version 2.0.0-beta.5

$ docker-compose --version
    docker-compose version 1.29.2
```

**Steps to reproduce the issue:**
1. Create `./foo.yml` compose-file in the project-directory
```
services:
  nginx:
    build:
      context: .
      args:
        - FOO=${FOO}
    environment:
        - BAR=${BAR}
```

2. Create `./foo.env` environment file
```
FOO="${FOO:-FOO_ENV_DEFAULT}"
BAR="${BAR:-BAR_ENV_DEFAULT}"
```
The Project folder should contain ...
```
./foo.yml
./foo.env
```

**Describe the results you received:**
1. `docker compose` fails - FOO and BAR defaults are not substituted correctly when passed into `foo.yml`
```
$ docker compose --project-directory . --env-file foo.env --file foo.yml config

...

services:
  nginx:
      args:
        FOO: :-FOO_ENV_DEFAULT} ❌
    environment:
      BAR: :-BAR_ENV_DEFAULT} ❌

```

2. `docker compose` with foo.yml and declared environment variables succeeds 
```
$ FOO="FOO_ENV_CMDLINE" BAR="BAR_ENV_CMDLINE" docker compose --project-directory . --env-file foo.env --file foo.yml config

...

services:
  nginx:
      args:
        FOO: FOO_ENV_CMDLINE ✅
    environment:
      BAR: :-BAR_ENV_CMDLINE ✅

```

3. `docker-compose` succeeds - FOO and BAR variables are passed correctly
```
$ docker-compose --project-directory . --env-file foo.env --file foo.yml config

...

services:
  nginx:
    build:
      args:
        FOO: FOO_ENV_DEFAULT ✅
    environment:
      BAR: BAR_ENV_DEFAULT ✅
```
**Describe the results you expected:**
Variable defaults declared in the --env-file should be passed to a compose-file. 

This works correctly when the environment variables are declared and when `docker-compose` (Python version) is used.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```bash
$ docker --version
    Docker version 20.10.7, build f0df350

$ docker compose version
    Docker Compose version 2.0.0-beta.5

$ docker-compose --version
    docker-compose version 1.29.2, build 5becea4c
```

**Comment by phillipuniverse** [comment]
This is not stale and is still an active issue in V2 of Docker Compose.

**Comment by ulyssessouza** [comment]
Should be fixed by https://github.com/compose-spec/compose-go/pull/276 and included in the next release of Docker Compose.
