### ISSUE TITLE
docker --context remotehost compose up -d shows WARN[0006] commandConn.CloseWrite

### ISSUE THREAD

**Issue by StefanScherer** [docker/compose#8544]
**Description**

I tried `docker compose up` with an SSH remote context. A warning appear on each `up` command when using such a remote context.
Other commands like `docker --context remotehost compose ps` or `docker --context remotehost compose down` work fine without this warning.

**Steps to reproduce the issue:**
1. `docker context create remotehost --docker "host=ssh://user@remotehost"`
2. `docker --context remotehost compose up -d`
3.

**Describe the results you received:**

```
$ docker --context remotehost compose up -d
WARN[0006] commandConn.CloseWrite: commandconn: failed to wait: signal: killed 
...
```

**Describe the results you expected:**

The warning shouldn't appear.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: P7BD:XDIY:BKCQ:7BID:S55U:Y7Q6:5AYS:W2WZ:KL2R:HULO:I5S6:HIBD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

Target machine is an AWS t4g ARM64 machine, but it also happened connection to a local Rasperry Pi ARM64 ubuntu box.

**Comment by plashenkov** [comment]
I see these warnings too when using `DOCKER_HOST=ssh://user@address` with `docker-compose up -d` command.

**Comment by emersonf** [comment]
>  It only started happening once we switched to docker compose V2. We are using the rc1 release.

Thanks @champloo, that just saved me a lot of grief. When using a Docker context with endpoint `ssh://foo`, I get frequent errors (most runs) with Compose V2 (on Docker Desktop 4.0.1 on macOS), and none with `docker-compose` (and the _Use Docker Compose V2 release candidate_ experimental feature disabled). That SSH host is an EC2 instance running the latest Docker version.

 Here are the typical `docker compose` errors (stuff in `<angle brackets>` is redacted):

```
% docker compose ps
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: terminated
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: terminated
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: terminated
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: killed
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: terminated
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: terminated
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: killed
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: killed
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: terminated
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: terminated
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: terminated
error during connect: Get "http://docker/v1.41/containers/<hash>/json": command [ssh -- <context name> docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=kex_exchange_identification: read: Connection reset by peer
```

**Comment by ndeloof** [comment]
for the records: https://github.com/docker/cli/blob/master/cli/connhelper/commandconn/commandconn.go#L203-L214

**Comment by donnykurnia** [comment]
So, still no solution? At least, a way to silence the warning? Or increase the timeout?

**Comment by nlfiedler** [comment]
Seems like docker via ssh is a second class citizen, I'm just glad it works at all. Would be even better not seeing disconcerting errors.

**Comment by donnykurnia** [comment]
I'm now using tcp connection instead of ssh. I copied the way docker-machine works, and now I had a very stable connection to the docker daemon inside vagrant vm.

**Comment by abbaseya** [comment]
@donnykurnia Thanks for pointing that out, me too finally not seeing these ssh connection errors after using TCP instead. But I am experiencing slower docker operations compared to SSH. Are you experiencing the same?

**Comment by donnykurnia** [comment]
@abbaseya since my docker daemon is inside virtualbox VM, I don't experience any slowing down. I create this VM using vagrant, and then set-up docker-machine to connect to it. Now with docker machine deprecated, and the vscode using context, I try to use it via ssh, but get the annoying warning above. Then few days ago, I look up what docker machine do, and basically it just setting up a secure tcp connection using the self-signed certificate. Docker context can use it, but the official documentation is very little. So I experimenting, and successfully reuse the same certificate that created by docker-machine into the docker context.

Here is the command that I use:
```
docker context create \
  --docker "host=tcp://<vm-ip>:2376,ca=<docker-machine-path-to>/ca.pem,cert=<docker-machine-path-to>cert.pem,key=<docker-machine-path-to>key.pem" <context-name>
```

**Comment by msbarry** [comment]
Another option if you want to connect over SSH but not deal with all of docker's ssh flakiness is to set up unix socket forwarding over the SSH connection. I ended up writing a script:

```
dockerssh() {
    rm -f /tmp/docker.sock
    cleanup() {
        ssh -q -S docker-ctrl-socket -p "${PORT}" -O exit "${HOST}"
        rm -f /tmp/docker.sock
    }
    trap "cleanup" EXIT
    ssh -M -S docker-ctrl-socket -p "${PORT}" -fnNT -L /tmp/docker.sock:/var/run/docker.sock "${HOST}"
    DOCKER_HOST=unix:///tmp/docker.sock eval "$*"
}
```

Then `dockerssh docker compose ...` to run a docker command pointing at that host or `dockerssh bash` to start a new shell pointing at that remote host.

**Comment by uosis** [comment]
This seems to only happen when SSH is in connection sharing mode, and only when using Compose V2. Compose V1 works fine, and so does Docker itself.

Commands are very slow without connection sharing, so @msbarry's solution of forwarding the socket is the best option.

**Comment by ssipos90** [comment]
@msbarry your script ended up deploying on my jenkins machine with this line `ControlSocket docker-ctrl-socket already exists, disabling multiplexing`.

**Comment by andoks** [comment]
> Another option if you want to connect over SSH but not deal with all of docker's ssh flakiness is to set up unix socket forwarding over the SSH connection. I ended up writing a script:
> 
> ```shell
> dockerssh() {
>   rm -f /tmp/docker.sock
>   cleanup() {
>     ssh -q -S docker-ctrl-socket -p "${PORT}" -O exit "${HOST}"
>     rm -f /tmp/docker.sock
>   }
>   trap "cleanup" EXIT
>   ssh -M -S docker-ctrl-socket -p "${PORT}" -fnNT -L /tmp/docker.sock:/var/run/docker.sock "${HOST}"
>   DOCKER_HOST=unix:///tmp/docker.sock eval "$*"
> }
> ```
> 
> Then `dockerssh docker compose ...` to run a docker command pointing at that host or `dockerssh bash` to start a new shell pointing at that remote host.

I am having this same issue using docker compose v2.2.3. When using docker contexts created by `docker context create my_host --docker "host=ssh://my_host" --default-stack-orchestrator=swarm`, `docker ps` works `docker-compose ps` does not work. By modifying msbarry's solution, and using docker context with a redirected socket over ssh, it works fine (with both docker and docker compose)

**Comment by glebsts** [comment]
Experiencing same issue with `ssh://..` remote docker context. Sample `docker-compose` that starts two `redis:alpine` containers detached works well, when running `down` says following:
```
docker-compose --context remote  down
[+] Running 1/2
[+] Running 1/2test-redis2-1  Removed                                                                                                                              0.3s
 ⠿ Container dctest-redis2-1  Removed                                                                                                                              0.3s
 ⠿ Container dctest-redis1-1  Error while Removing                                                                                                                 0.6s
error during connect: Delete "http://docker.example.com/v1.41/containers/1dd29cc1df50dab67426a90181c5a445c73a3d03e4b72e9324db75d26d6fab81?force=1": command [ssh -l <username> -- <IP_ADDR> docker system dial-stdio] has exited with signal: killed, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=
```

after that `docker-compose --context remote ps` says 
```
docker-compose ps
NAME                COMMAND                  SERVICE             STATUS              PORTS
dctest-redis2-1     "docker-entrypoint.s…"   redis2              exited (0)          
```
`docker --context remote logs dctest1-redis2-1` gives 
```
# User requested shutdown...
<saving db logs here>
# Redis is now ready to exit, bye bye...
```
while `docker --context remote ps` gives no running containers, `-a` flag reports container as `Exited`.
Second run of `docker-compose --context remote down` removes remaining container and network:
```
[+] Running 2/2
 ⠿ Container dctest-redis2-1  Removed                                                                                                                              0.0s
 ⠿ Network dctest_default     Removed
```
Reproduceable always. Works fast, both nodes in GCP cloud.

What am I doing wrong?

**Comment by gojmpz** [comment]
> ```shell
> DOCKER_HOST=unix:///tmp/docker.sock eval 
> ```

Lost about 3 hours in debugging, while creating ssh tunnel to docker:20.10-dind,
By default ssh service in docker:20.10-dind image  includes: `AllowTcpForwarding no` in /etc/ssh/sshd_config. That preventing the tunnel forwarding: connection reset by peer.
Added `sed -i -e "s/AllowTcpForwarding no/AllowTcpForwarding yes/g" /etc/ssh/sshd_config` to resolve the issue.

**Comment by gojmpz** [comment]
> I’m also facing the same issue with remote context with ssh. Is there any resolution to this?

Reliable solution - only ssh tunnel, see above.

**Comment by Benjamin-Tan** [comment]
> > I’m also facing the same issue with remote context with ssh. Is there any resolution to this?
> 
> Reliable solution - only ssh tunnel, see above.

Thanks for the response. May I know is there any resolution that uses DOCKER_HOST=ssh://... instead of ssh tunnel DOCKER_HOST=unix://...sock?

**Comment by isvaljek** [comment]
Can someone explain where the dockerssh function gets its host and port variables?

**Comment by gojmpz** [comment]
> Can someone explain where the dockerssh function gets its host and port variables?
What do you mean by 'dockerssh function'?

**Comment by isvaljek** [comment]
Sorry it was posted by @msbarry earlier in the thread, as a workaround for flaky ssh.

**Comment by gojmpz** [comment]
dockerssh function is getting variables from environment.
You can set them like this:
```
export PORT=2375
export HOST=127.0.0.1
```

**Comment by warpreality** [comment]
Greetings! I catch the same error sometimes when using gitlab-ci. At the same time, my ssh connection is as stable as possible (local virtual network between servers)

**Comment by thanhnv0901** [comment]
> > ```shell
> > DOCKER_HOST=unix:///tmp/docker.sock eval 
> > ```
> 
> Lost about 3 hours in debugging, while creating ssh tunnel to docker:20.10-dind, By default ssh service in docker:20.10-dind image includes: `AllowTcpForwarding no` in /etc/ssh/sshd_config. That prevents the tunnel forwarding with an error: connection reset by peer. Added `sed -i -e "s/AllowTcpForwarding no/AllowTcpForwarding yes/g" /etc/ssh/sshd_config` to resolve the issue.

thank you, Although I do not understand AllowTcpForwarding field. it works well when update to yes.
Can you share me how you can debug and find solution like that
thank you

**Comment by gojmpz** [comment]
> > > ```shell
> > > DOCKER_HOST=unix:///tmp/docker.sock eval 
> > > ```
> > 
> > 
> > Lost about 3 hours in debugging, while creating ssh tunnel to docker:20.10-dind, By default ssh service in docker:20.10-dind image includes: `AllowTcpForwarding no` in /etc/ssh/sshd_config. That prevents the tunnel forwarding with an error: connection reset by peer. Added `sed -i -e "s/AllowTcpForwarding no/AllowTcpForwarding yes/g" /etc/ssh/sshd_config` to resolve the issue.
> 
> thank you, Although I do not understand AllowTcpForwarding field. it works well when update to yes. Can you share me how you can debug and find solution like that thank you

As I said, I lost 3 hours, so it was not an easy task to resolve )
First of all, I've installed ssh inside the image and tried to login, the connection was successful. So, I was totally certain that the ssh tunnel should work but it didn't. So I started ssh connection in verbose mode, with -v and found something that was then searched on stackoverflow. I don't remember exact details
That's about it )
