### ISSUE TITLE
Introduce up `--attach` and/or `--no-attach` flags

### ISSUE THREAD

**Issue by ndeloof** [docker/compose#8546]
**Description**

`docker-compose` uses the "logs" API and as such will drop output from services configured with `log-driver:none`
`docker run` attach to container, so doesn't rely on logs stored by engine.
`docker compose up` uses the same "attach" API for consistency with the CLI, bu doing so isn't strictly backward compatible with docker-compose, and doesn't offer any option to drop logs from a service.

We could introduce additional flags to offer this feature, aligned with then existing --attach-dependencies`  flag.

**Additional information you deem important (e.g. issue happens only occasionally):**
see https://github.com/docker/compose-cli/issues/1613

**Comment by davidbarkhuizen** [comment]
doh! stale bot.  we want this fixed.

**Comment by jzombie** [comment]
Please fix this.

**Comment by KGMIT** [comment]
I concur
