### ISSUE TITLE
Command-line completion?

### ISSUE THREAD

**Issue by sbellem** [docker/compose#8550]
I just wonder if there's a command completion like there is for the [docker-compose](https://docs.docker.com/compose/completion/) command.

**Comment by SuperSandro2000** [comment]
There was some completion but it was removed in https://github.com/docker/compose/commit/c28aec2308a24f589814cf4ac55a225d144f557d

**Comment by ndeloof** [comment]
AFAICT offering command line completion for `docker compose` (space) isn't trivial due to the CLI plugin architecture, but we could automatically produce completion for `docker-compose` (when used standalone) using Cobra command support for this feature. Wdyt @ulyssessouza @mat007 ?

**Comment by mat007** [comment]
I was pretty sure this was already in place, but apparently it’s either not fully implemented or not working.
We’ll have a look: internally tracked as https://docker.atlassian.net/browse/IL-768

**Comment by ndeloof** [comment]
IIRC @ulyssessouza experimented with this, but he was blocked by docker CLI plugin architecture (we can't extend the docker CLI completion script)
But for direct use of docker-compose binary, we could adopt https://gist.github.com/jsteenb2/0973c838b00940ee8ccdf958a79756af and also add support for completion functions to auto-complete flags / args values.

**Comment by danger89** [comment]
This is very strange indeed. What happened with the bash auto completion. Otherwise I would have created a PR for upgrading docker-compose to v2.2.2 on https://github.com/docker/docker.github.io/

**Comment by ndeloof** [comment]
Please note the existing `docker-compose` bash completion still works with compose v2 when used as a standalone binary. But it would beed some update to add support for additional commands and flags

**Comment by stefanocudini** [comment]
This problem has been solved? in some version?

**Comment by stefanocudini** [comment]
> Should be easy to generate one, as Cobra command library includes support for generating completion scripts https://github.com/spf13/cobra/blob/master/shell_completions.md
@ndeloof were you able to generate completion scripts? for compose v2?

**Comment by PHLAK** [comment]
> This problem has been solved? in some version?

No, this doesn't seem to be solved yet.

**Comment by rsteube** [comment]
Ok i think i missed something :thinking: : Is `docker compose` invoking `docker-compose` or is it compiled into the `docker` binary?

**Comment by SuperSandro2000** [comment]
`docker compose` aka docker-compose v2 is a plugin for the ``docker`` command written in go and is not using any python stuff from docker-compose v1.

**Comment by rsteube** [comment]
@SuperSandro2000 thanks. I got the shift from python to go, but I didn't catch that it is integrated as plugin.

**Comment by wbolster** [comment]
for completeness: under the hood, docker's cli-plugins handling does invoke a `docker-compose` executable (which happens to be written in golang these days indeed), which typically lives in `/usr/lib/docker/cli-plugins/docker-compose` and should not be called directly. (this is similar to how `git` handles subcommand ‘plugins’)

**Comment by rsteube** [comment]
> `docker-compose` executable (which happens to be written in golang these days indeed), which typically lives in `/usr/lib/docker/cli-plugins/docker-compose` and should not be called directly. (this is similar to how `git` handles subcommand ‘plugins’)

Yeah, I was worried about that as I've been invoking `docker-compose` (which still exists in my `PATH`) for the completions - should be `docker compose` then.

Think i got it working though:
[![asciicast](https://asciinema.org/a/8IUmFJQUe5sDow7zu91deHFJY.svg)](https://asciinema.org/a/8IUmFJQUe5sDow7zu91deHFJY)

**Comment by rsteube** [comment]
> IIRC @ulyssessouza experimented with this, but he was blocked by docker CLI plugin architecture (we can't extend the docker CLI completion script)

@ndeloof i think this should be possible if you can update the docker cli to a newer cobra version.
It changed in recent versions from full completion script generation to invoking the binary.

In docker cli you just add a subcommand for each (installed) plugin with flag parsing disabled like [here](https://github.com/rsteube/carapace-bin/blob/9da6898a911b06cf31857e0941f99a6db4302f8c/completers/docker_completer/cmd/compose.go#L13).
Then in the [ValidArgsFunction](https://pkg.go.dev/github.com/spf13/cobra#Command) invoke the `__complete` subcommand of the extension with `args` and `toComplete` as arguments similar to [this](https://github.com/rsteube/carapace-bin/blob/f804808cd141a4f3cda5b468f7489662e0872c4a/pkg/actions/tools/cobracomplete/cobracomplete.go) (ignore the directive handling as it is not needed in this case).

The `__complete` command outputs sth. like this:
```sh
value
value\twithDescription
:4
# empty line
```
So just return `lines[:len(lines)-2]` and `:4` parsed as integer ([ShellCompDirecive](https://pkg.go.dev/github.com/spf13/cobra#ShellCompDirective)).

**Comment by ndeloof** [comment]
Started experimenting with cobra 1.3.0 to adopt cobra (dynamic) completion v2 : https://github.com/docker/cli/pull/3429

**Comment by rsteube** [comment]
Nice. If it's any help for anyone in the meantime: got my completer at [carapace-bin](https://github.com/rsteube/carapace-bin).
Just source the script from `carapace docker` and it should work with the `compose` and `buildx` subcommands.

**Comment by zaverden** [comment]
As temporal workaround I have installed [compose switch](https://docs.docker.com/compose/cli-command/#compose-switch) and applied [v1 completion](https://docs.docker.com/compose/completion/). it requires me to use it as `docker-compose` (not as `docker compose`) but completion works

**Comment by IamGroot19** [comment]
The documentation provides bash script for auto-completion but the link is broken. https://docs.docker.com/compose/completion/

**Comment by ndeloof** [comment]
Command line completion for `docker compose` as a docker CLI plugin will be enabled by https://github.com/docker/cli/pull/3429

**Comment by konstruktoid** [comment]
https://docs.docker.com/compose/completion/ states that `sudo curl
    -L https://raw.githubusercontent.com/docker/compose/v2.5.0/contrib/completion/bash/docker-compose 
    -o /etc/bash_completion.d/docker-compose` is a valid way to go, but `https://raw.githubusercontent.com/docker/compose/v2.5.0/contrib/completion/bash/docker-compose` is a 404.

**Comment by ndeloof** [comment]
@konstruktoid thanks for reporting. I guess doc was updated for v2.5 release but this is actually link for docker-compose 1.x completion

**Comment by rollsover** [comment]
> https://docs.docker.com/compose/completion/ states that `sudo curl -L https://raw.githubusercontent.com/docker/compose/v2.5.0/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose` is a valid way to go, but `https://raw.githubusercontent.com/docker/compose/v2.5.0/contrib/completion/bash/docker-compose` is a 404.

Ran into this today, still not fixed...
Can you link to the Issue?

**Comment by konstruktoid** [comment]
https://github.com/docker/docker.github.io/issues/14692

**Comment by sebaspf** [comment]
`curl -L https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker -o /usr/share/bash-completion/completions/docker` 
 
 did the tirck while waiting for https://github.com/docker/cli/pull/3429 become releesed (v20.17?).

**Comment by troywweber7** [comment]
@sebaspf I tried this but completion for docker compose doesn't go any further than completing `compose`, completion after that seems to be faulty:

![image](https://user-images.githubusercontent.com/4765979/171506744-62862588-8b28-4d4c-82c0-03455c1814cb.png)

**Comment by RafalSkolasinski** [comment]
Seems fish completions did not get updated to include compose command https://github.com/docker/cli/tree/master/contrib/completion

**Comment by PhilippeAccorsi** [comment]
I am also un-happy to lost autocompletion with this new version :(

I not really understand why change docker-compose to docker compose if it is more difficult to use the command line.

With old approch I use some file like this docker-compose-xxxxx.yml and in each file I have some services (preprod, prod, etc.), so to start/stop service it is very easy to just write
```
docker-c + "tab key"
docker-compose -f docker-c + "tab key"
docker-compose -f docker-compose-xx + "tab key"
docker-compose -f docker-compose-xxxxx.yml up -d 
```

Now i need to write all, all the time (or use the history, ctrl+r, etc.).

I understand the reason to not use python version anymore but for user, it is not better/simple to use compose.

**Comment by PHLAK** [comment]
> completion for docker compose doesn't go any further than completing `compose`, completion after that seems to be faulty

I'm experiencing the same.

```
$ pacman --query docker-compose
docker-compose 2.9.0-1

$ docker compose <tab> <tab>
Display all 145 possibilities? (y or n)
a                    container.           exec                 more                 projects             Start
alternate            containers           Execute              name                 ps                   stop
an                   containers,          -f,                  networks             public               Stop
and                  containers.          --file               (never|always|auto)  pull                 stopped
--ansi               control              file                 of                   Pull                 string
ANSI                 Control              file)                on                   push                 stringArray
auto)                convert              file.                one-off              Push                 the
backward             Converts             files                Options:             real                 the,
between              Copy                 files/folders        [OPTIONS]            rebuild              time
binding.             cp                   filesystem           or                   Receive              to
build                create               first                output               remove               top
Build                Create               for                  -p,                  Removes              unpause
by                   created              Force                path                 restart              Unpause
canonical            Creates              format               pause                Restart              up
characters           (default             from                 Pause                rm                   Usage:
command              (default:            --help               platforms            run                  used

```

**Comment by otbutz** [comment]
@ndeloof what's the state of https://github.com/docker/compose/pull/9462 ?

**Comment by ndeloof** [comment]
#9462 was designed to demonstrate ability to provide command line completion from a docker CLI plugin, and get https://github.com/docker/cli/pull/3429 approved.

**Comment by tbroyer** [comment]
Is this supposed to work now? With Docker 20.10.18 and Docker Compose 20.10.2, on ArchLinux, I still get the same `Display all 145 possibilities? (y or n)` as above.

**Comment by waja** [comment]
Looks like it also doesn't work on Debian bullseye.

```
# dpkg -l | grep -E "(docker-ce|docker-compose-plugin)"
ii  docker-ce                         5:20.10.18~3-0~debian-bullseye amd64        Docker: the open-source application container engine
ii  docker-ce-cli                     5:20.10.18~3-0~debian-bullseye amd64        Docker CLI: the open-source application container engine
ii  docker-compose-plugin             2.10.2~debian-bullseye         amd64        Docker Compose (V2) plugin for the Docker CLI.
```

**Comment by cornfeedhobo** [comment]
```plain
$ ./docker-compose completion --help
unknown docker command: "compose completion"

$ ./docker-compose version
Docker Compose version v2.11.0
```

but [the `completion` sub command exists](https://github.com/docker/compose/blob/v2/cmd/compose/completion.go)...

**Comment by germetist** [comment]
doesn't work on Debian 10
```
dpkg -l | grep -E "(docker-ce|docker-compose-plugin)"
ii  docker-ce                                       5:20.10.18~3-0~debian-buster  amd64        Docker: the open-source application container engine
ii  docker-ce-cli                                   5:20.10.18~3-0~debian-buster  amd64        Docker CLI: the open-source application container engine
ii  docker-compose-plugin                           2.10.2~debian-buster          amd64        Docker Compose (V2) plugin for the Docker CLI.
```

```
docker compose TAB
Display all 145 possibilities? (y or n)
```

**Comment by diegoquintanav** [comment]
It's not the same as having completions for `docker compose`, but a solution is to use the docker-compose command completion with

```
sudo curl -L https://raw.githubusercontent.com/docker/compose/1.21.2/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose
```

And then by creating your own version of `docker-compose` that forwards calls to `docker compose`. According to https://stackoverflow.com/a/72187587/5819113.

```
echo 'docker compose "$@"' | sudo tee /bin/docker-compose
sudo chmod +x /bin/docker-compose 
docker-compose version
```

**Comment by ddolcimascolo** [comment]
I'm in the same boat. Should you need any info from my setup just ask.

Cheers,
David

**Comment by cornfeedhobo** [comment]
My point is that the command exists, so ... why is it not being included in releases?

**Comment by sungvzer** [comment]
Is there an alternative for Zsh?

Additional info:
```shell
> docker -v      
Docker version 20.10.22, build 3a2c30b
> docker compose version                    
Docker Compose version v2.14.1
> cat /etc/issue
Ubuntu 22.04.1 LTS
```

**Comment by Saucistophe** [comment]
@sungvzer You may look for a specific [plugin](https://github.com/chr-fritz/docker-completion.zshplugin)

**Comment by allenyllee** [comment]
I upgrade to version 2.20.2, it Still doesn't work, any progress?
```
ii  docker-ce                             5:20.10.12~3-0~ubuntu-focal              amd64        Docker: the open-source application container engine
ii  docker-ce-cli                         5:20.10.12~3-0~ubuntu-focal              amd64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras             5:20.10.12~3-0~ubuntu-focal              amd64        Rootless support for Docker.
ii  docker-compose-plugin                 2.20.2-1~ubuntu.20.04~focal              amd64        Docker Compose (V2) plugin for the Docker CLI.
```

**Comment by layoaster** [comment]
@allenyllee you might want check this https://github.com/docker/docs/issues/16397#issuecomment-1638343880

**Comment by willzhang** [comment]
> 更新 Docker CLI 完成（ ）在等待[docker/cli#3429](https://github.com/docker/cli/pull/3429)发布（v20.10.17？）`curl -L https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker -o /usr/share/bash-completion/completions/docker`时引起了注意。[](https://github.com/docker/cli/pull/3429)

It works for me in ubuntu 22.04 bash
```
root@ubuntu:~# docker compose 
build    cp       down     exec     kill     ls       port     pull     restart  run      stop     unpause  version  
config   create   events   images   logs     pause    ps       push     rm       start    top      up       
```

**Comment by gkze** [comment]
Is there a way to use Bash completion with Zsh? I have `bashcompinit` loaded but am getting errors. Alternatively, since the CLI uses Cobra, can the completion be automatically generated for the corresponding shell?

**Comment by ndeloof** [comment]
completion is managed by the docker CLI, You can use `docker completion zsh` to generate the zsh completion script.

**Comment by gkze** [comment]
Thanks, was using Zsh completion from contrib. Is it even needed anymore then?

**Comment by ndeloof** [comment]
I'm not sure about the current status for the "new" extensible completion.
@laurazard is docker/cli contrib still relevant or do we now recommend using cobra-generated completion script?

**Comment by robcxyz** [comment]
Am I right in seeing the `docker compose -f <file name in path that should complete> ...` doesn't work? Seems like a pretty important completion if it was omitted and a regression from the prior version when file paths are a clear candidate for a completion. 

Found https://github.com/docker/docs/issues/16397 which added completions for mac but the zsh instructions don't seem 1:1 applicable to linux.

**Comment by gkze** [comment]
The contents of `docker completion zsh` are working fine for me for `-f`.

**Comment by gkze** [comment]
Docs are a little outdated though - they point @ the contrib completion scripts which don't work for `compose` as a subcommand

**Comment by bonyiii** [comment]
This worked for me with bash: ```sudo docker completion bash >  /etc/bash_completion.d/docker.sh```

**Comment by ConnorsApps** [comment]
Adding to `.zshrc` or `.bashrc`
## zsh
`~/.zshrc`
```sh
source <(docker completion zsh)
```
## bash
`~/.bashrc`
```sh
source <(docker completion bash)
```
