### ISSUE TITLE
docker-compose does not display log when container restart 

### ISSUE THREAD

**Issue by daijiaxin** [docker/compose#8554]
**Description**
`docker-compose logs -f` does not display log when container restart 
v1.x is ok

**Steps to reproduce the issue:**
1. docker-compose up -d
2. docker-compose logs -f
3. docker restart nginx

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose --version`:**

```
Docker Compose version v2.0.0-beta.6
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: docker-desktop
 ID: 4PPU:YTLS:BFOA:VVQI:VSFY:6SIF:KPTE:PF65:WJ6Q:NHJX:T6MP:CDGD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by nocive** [comment]
Tested with v2.0.0-rc.3 and not fixed.

**Comment by ndeloof** [comment]
Right, indeed. Ran further investigation to understand what's missing here.
1. we don't catch the `restart` event on https://github.com/docker/compose/blob/1a73d1412d562e32effbe7b322f17e8d77ad7755/pkg/compose/start.go#L119
2. when container is killed by `docker restart`, we can't guess it will restart, so stop watching https://github.com/docker/compose/blob/1a73d1412d562e32effbe7b322f17e8d77ad7755/pkg/compose/start.go#L97 and never get notified by `restart` event

**Comment by nicksieger** [comment]
FYI, seems to be working for me as of docker 20.10.11 with docker-compose 2.2.1. See above tilt-dev/tilt#4890.

**Comment by ulyssessouza** [comment]
IIRC that bug was already fixed. Could you please update to the latest version? (v2.2.2 by the time I'm writing)?
