### ISSUE TITLE
docker-compose up and docker compose up do not share containers

### ISSUE THREAD

**Issue by sebbASF** [docker/compose#8560]
`docker-compose up` and `docker compose up` both re-use an existing container.

However they don't use a container created by the other command; it is replaced by a new container.

**Comment by ndeloof** [comment]
`docker compose` is designed for backward compatibility but we don't expect both tools to be maintained in parallel for long terms, so I don't think this is a blocker

**Comment by sebbASF** [comment]
No, it's not a blocker, but it does not give a good impression to users who are being persuaded to switch tools
