### ISSUE TITLE
zsh: parse error near `}'

### ISSUE THREAD

**Issue by yvettep321** [docker/compose#8563]
## Context information (for bug reports)

- [ ] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
(paste here)
```

**Output of `docker version`**
```
(paste here)
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by ndeloof** [comment]
Closing issue as user didn't provided requested issue template informations.
If this is a relevant issue, please open a new issue with requested details
