### ISSUE TITLE
Compose log tailing does not exit v4.0

### ISSUE THREAD

**Issue by iben12** [docker/compose#8564]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1EE37B25-5227-4251-9FBD-6E66E13DD50D/20210902122837

### Expected behavior
When using `docker compose logs -f myservice` and hitting CTRL + c the log tailing exits.

### Actual behavior
When I hit CTRL + c the streaming stops, but it does not exit back to terminal. Hitting CTRL + c again prints the following line and exits:
```
ERRO[0014] got 3 SIGTERM/SIGINTs, forcing shutdown
```

### Information

  - macOS Version: 11.5.2
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 4.0

### Steps to reproduce the behavior

  1. `docker compose up -d` (does not depend on any specific service)
  2. `docker compose logs -f myservice` to stream logs into terminal
  2. Hit CTRL + c to exit
  3. It does not exit
  4. Hit CTRL + c again to force shutdown

**Comment by cbeauchesne** [comment]
I updated docker, and same result :  

* `docker --version` => 20.10.8, build 3967b7d
* `docker-compose --version` => v2.0.0-rc.1
* Docker desktop Version 3.6.0 (3.6.0.5487)
* MacOS 11.5.2

**Comment by Hazmi35** [comment]
Could reproduce in Docker Desktop for Windows and Linux (Arch Linux) with [Manual Install](https://docs.docker.com/compose/cli-command/#install-on-linux)

**Comment by kenichi** [comment]
same issue, I also have to `kill -9` logs -f processes after multiple ^Cs

https://gist.github.com/kenichi/121006517a85ac74bef956986301a5c0

**Comment by nocive** [comment]
This still happens if you try to exit the logs command of a non running container.
