### ISSUE TITLE
docker-compose v2 fails silently if ~/.docker does not exist

### ISSUE THREAD

**Issue by rfay** [docker/compose#8565]
## Description of the issue

docker-compose v2.0.0-rc.2 fails silently on `docker-compose exec` if ~/.docker (or some content there) is missing.

I just spent a lot of time trying to figure out one more ddev test that was failing with docker-compose v2, and it turned out the test changes the $HOME to verify some ddev behavior. Changing $HOME (to a directory that does not include .docker) causes docker-compose v2.0.0-rc2 to fail silently.

I understand that this is an unusual and contrived problem, but it would be nice if docker-compose v2 would just say "Can't find ~/.docker" instead of failing silently with an undocumented nonzero error code.  (docker-compose v1 doesn't have this problem)

## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.2```

**Comment by ndeloof** [comment]
I haven't been able to reproduce this error.
I assume this error is caused by the `docker-compose` => `docker compose` translation, bundled by Docker Desktop.
Can you please confirm this issue doesn't appear when you use `docker <space> compose` without a `.docker` folder on your system?

**Comment by rfay** [comment]
Sorry I've been delinquent in recreating this, but I worked around it in tests by adding the .docker directory and it seems pretty obscure anyway.

**Comment by mat007** [comment]
When `.docker` doesn’t exists `docker-compose` on Windows and Mac always redirects to compose v1. I just tested this with `docker-compose --version`.
So I guess if it’s failing silently it must be v1? 🤔

**Comment by rfay** [comment]
No, it was definitely a v2 issue, because these tests were in there for months or years until v2 uncovered this problem.
