### ISSUE TITLE
set scale service=0

### ISSUE THREAD

**Issue by ndeloof** [docker/compose#8571]
## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
v2.0.0-rc.3
```

## Steps to reproduce the issue

1. run a compose app with single service `foo`
2. run  `docker compose up --scale foo=0`

### Observed result
Service still running

### Expected result
Service removed, 0 replicas

## Additional information

see https://github.com/docker/compose/issues/8567

**Comment by ndeloof** [comment]
Basically, scale=0 being the default value in go struct, we consider this equivalent to scale=1

**Comment by zdraganov** [comment]
You can consider using pointers, so there's difference between nil, which is equivalent of the default value, and 0.

**Comment by ndeloof** [comment]
sure, but this would make the compose-go model harder to use (and is a significant design change).

**Comment by zdraganov** [comment]
Other options is also not perfect. Making the setting private and exposing a setter, which will allow tracking "dirty" state of it.
