### ISSUE TITLE
Regression: Variable expansion of ${APPDATA} in YAML fails on \Users, expecting hexadecimal

### ISSUE THREAD

**Issue by ArneMancofi** [docker/compose#8580]
## Description of the issue

Variable expansion of `${APPDATA}` in docker-compose.yml which worked in previous Docker Compose versions now fails in Docker Compose V2 with *Did not find expected hexadecimal number*.

## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker compose version`**
```
Docker Compose version v2.0.0-rc.2
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 Kubernetes:
  Version:          v1.20.7
  StackAPI:         v1alpha3
```

**Output of `docker-compose config`**
```
secrets:
  secrets.json:
    file: C:\Users\MyName\AppData\Roaming\foo.json
services: {}
version: '3.8'

```

## Steps to reproduce the issue

1. Ensure environment variable $APPDATA contains **\U**, for instance **C:\Users\MyName\AppData\Roaming**
2. Create file `docker-compose.yml` containing
   ```
   version: '3.8'
   secrets:
     secrets.json:
       file: "${APPDATA}/foo.json"
   ```
3. Run `docker compose -f docker-compose.yml build`

### Observed result
Command fails with exit code 15.

### Expected result
Command should complete successfully with exit code 0.

### Stacktrace / full error message

```
yaml: line 4: did not find expected hexdecimal number
```

## Additional information

Using Windows 10.0.19043 and Docker Desktop automatic upgrades.

**Comment by ndeloof** [comment]
This issue has already been fixed in v2.0.0-rc.3 by https://github.com/compose-spec/compose-go/pull/172
