### ISSUE TITLE
Azuracast utility scripture won't install, 404 in return

### ISSUE THREAD

**Issue by eduardonwa** [docker/compose#8582]
Hello there, I am trying to install a utility script to be able to use Azuracast and it needs to be installed via docker compose but it just won't let me advance, it throws a 404 instead. 

**Output of `docker(-)compose version`**
```
Docker version 20.10.8, build 3967b7d
```

**Output of `docker version`**
```
Docker version 20.10.8, build 3967b7d
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
/usr/local/bin/docker-compose: line 1: Not: command not found
```

## Steps to reproduce the issue

1. mkdir -p /var/azuracast
2. cd /var/azuracast
3. curl -fsSL https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh > docker.sh
4. chmod a+x docker.sh
5. ./docker.sh install

### Observed result
The result is a 404 message

### Expected result
I should be able to utilize this script on my VPS to correctly use Azuracast. Thanks.

### Stacktrace / full error message

```
Docker is already installed! Continuing...
/usr/local/bin/docker-compose: line 1: Not: command not found
Docker Compose does not appear to be installed. Install Docker Compose now? [Y/n] y
curl: (22) The requested URL returned error: 404
Prefer stable release versions of AzuraCast? [y/N] n
touch: cannot touch 'docker-compose.new.yml': Permission denied
curl: (23) Failed writing body (0 != 277)
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found
rm: cannot remove 'docker-compose.installer.yml': No such file or directory
cp: cannot create regular file '.env.bak': Permission denied
cp: cannot create regular file '.env.bak': Permission denied
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found
```

## Additional information

It's a VPS Canonical-Ubuntu-18.04 

Thanks,

**Comment by mat007** [comment]
Given the script you executing is in https://github.com/AzuraCast/AzuraCast maybe you want to open an issue there?

**Comment by eduardonwa** [comment]
Yep I've transferred my issue over there, thanks for your patience!
