### ISSUE TITLE
Compose does not work with buildkit's `docker-container` driver.

### ISSUE THREAD

**Issue by leehambley** [docker/compose#8590]
- Initial bug opened in https://github.com/docker/compose/issues/8494 but I now know the root cause
- Docker community Slack thread for context: https://dockercommunity.slack.com/archives/C7S7A40MP/p1631116248049900

## Description of the issue

When using buildkit, if the buildkit driver is `docker-compose` (not docker) a warning is printed like 

## Context information (for bug reports)

- [ ] Using Compose V2 `docker compose ...`
- [x] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
➜  ~ docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.0
CPython version: 3.9.6
OpenSSL version: OpenSSL 1.1.1k  FIPS 25 Mar 2021
```

**Output of `docker version`**
```

➜  ~ docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:44 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. `docker buildx create --name mybuilder` (uses driver `docker-container` not `docker`, verify with `docker bulidx ls`)
2. `docker bulidx use mybuilder` 
3. `docker-compose build` 
4. Observe warning like `WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load`
5. Observe fault like `IndexError: list index out of range` from the part of the docker compose scripts which tries to read an image id from a tempfile.

### Observed result

Nothing built (also docker-compose continues to try and build, even though there is a fault)

### Expected result

Should build properly

### Stacktrace / full error message

```
(paste here)
```

## Additional information

Fedora 34, docker-compose installed from package, pip and the `curl | bash` thing recommeneded in the docs. Problem turned out to be buildkit's "other" driver which seems to be incompatble with docker-compose. I could find no way of passing those `--push `

**Comment by leehambley** [comment]
Sure, 

`Dockerfile`:

```
# Copied from https://github.com/vearutop/docker_plantuml/blob/master/Dockerfile
# who apparently does not publish to DockerHub

FROM openjdk:17-jdk-alpine3.14
ENV PLANTUML_VERSION=1.2021.9
ENV LANG en_US.UTF-8
RUN \
  apk add --no-cache graphviz-dev wget ca-certificates ttf-dejavu fontconfig && \
  wget "http://downloads.sourceforge.net/project/plantuml/${PLANTUML_VERSION}/plantuml.${PLANTUML_VERSION}.jar" -O plantuml.jar && \
  apk del wget ca-certificates
RUN ["java", "-Djava.awt.headless=true", "-jar", "/plantuml.jar", "-version"]
RUN ["dot", "-version"]

# Entrypoints disabled
# ENTRYPOINT ["java", "-Djava.awt.headless=true", "-jar", "/plantuml.jar"]
# CMD ["--help"]
```

And the `docker-compose.yml`:

```
version: "3.9"
services:
  server:
    build: .
    command:
      ["java", "-Djava.awt.headless=true", "-jar", "/plantuml.jar", "-picoweb"]
    ports:
      - "8095:8080"
```

**Comment by thaJeztah** [comment]
Possibly related https://github.com/docker/cli/issues/2971

/cc @crazy-max (should compose set the `--load` flag by default? is that flag a "no-op" if the non container driver is used (i.e. will if be ignored and won't be a problem if it's set unconditionally?)

**Comment by crazy-max** [comment]
@thaJeztah Looks like compose v1 is using the current builder but v2 is using the ["default" builder](https://github.com/docker/compose/blob/a0bff8be969a9dd31bcc87b129b2470dd6547fbb/pkg/compose/build.go#L213-L218) (docker driver).

> /cc @crazy-max (should compose set the `--load` flag by default? is that flag a "no-op" if the non container driver is used (i.e. will if be ignored and won't be a problem if it's set unconditionally?)

I wonder if @leehambley has used `docker buildx install` to default buildx for the build command because I don't think compose v1 is using buildx under the hood?

**Comment by leehambley** [comment]
> I wonder if @leehambley has used docker buildx install to default buildx for the build command because I don't think compose v1 is using buildx under the hood?

We do run some env vars for force buildkit usage. Some parts of my company's infra rely on mounting an SSH socket to clone private repositories, and we have corporate managed env variable exports, so I wouldn't be surprised if something was forcing Docker Compose to use buildkit.

**Comment by leehambley** [comment]
Correction to my previous comment, this directory doesn't seem to have any managed `.envrc` files or similar and `env | grep -i DOCKER` is empty.

**Comment by crazy-max** [comment]
@leehambley Ok compose v1 is using [`docker build`](https://github.com/docker/compose/blob/aca6edd63116ca8540160ab84f79644920cd4f33/compose/service.py#L1958). Can you check if `~/.docker/config.json` contains `"aliases":{"builder": "buildx" }`? If it's there can you do `docker buildx uninstall` and `docker-compose build` again?

**Comment by leehambley** [comment]
Indeed `~/.docker/config.json` does contain this:

```cat ~/.docker/config.json
{
        "auths": {
                "docker-registry-..........": {
                        "auth": ".........."
                },
                "docker-registry-dev......": {
                        "auth": "......."
                },
                "docker-registry.internal..........": {
                        "auth": "....."
                }
        },
        "aliases": {
                "builder": "buildx"
        }
}
```

Not exactly sure where that came from, but I guess I've had it a while in my dotfiles.

If I remove the `mybuilder` builder (which came from `docker buildx create --name mybuilder` when looking in the Docker arm64 guide) then I go back to the `docker` driver and this works just fine.

**Comment by crazy-max** [comment]
`"aliases":{"builder": "buildx" }` is created when you're doing `docker buildx install`.



> If I remove the `mybuilder` builder (which came from `docker buildx create --name mybuilder` when looking in the Docker arm64 guide) then I go back to the `docker` driver and this works just fine.

No need to remove your builder I think, the issue was the builder alias in your docker config.

**Comment by leehambley** [comment]
Got it, thanks for the clarification.

Regardless, I think @thaJeztah 's question from an hour ago stands, right? https://github.com/docker/compose/issues/8590#issuecomment-917948681 It's entirely possible to get a non-working configuration by following harmless steps, so maybe if possible docker-compose should work with and without the various buildx builders?

**Comment by crazy-max** [comment]
@leehambley 

> Regardless, I think @thaJeztah 's question from an hour ago stands, right? [#8590 (comment)](https://github.com/docker/compose/issues/8590#issuecomment-917948681) It's entirely possible to get a non-working configuration by following harmless steps, so maybe if possible docker-compose should work with and without the various buildx builders?

Yes I think we could load the docker config in compose v1 to check if the buildx alias is used and if so, add the `--load` arg.

**Comment by Stono** [comment]
Another gotcha with that approach would be `--load` doesn't work with multi arch builds:

```
❯ docker buildx bake --set "*.platform=linux/amd64,linux/arm64" --load
[+] Building 0.0s (0/0)                                                                                                                                                                              
error: docker exporter does not currently support exporting manifest lists
```

So when building:
```
version: '3.2'

services:
  app:
    image: "multiarch-test"
    platform: linux/amd64,linux/arm64
    restart: always
    user: root
    build: 
      context: .
      dockerfile: Dockerfile
```

Which gives me a multi-arch build that `--load` wouldn't fix anyway:
````
❯ docker-compose build                                                
Building app
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load 
[+] Building 14.2s (8/8) FINISHED                                                                                                                                                                    
 => [internal] load build definition from Dockerfile                                                                                                                                            1.4s
 => => transferring dockerfile: 163B                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                               1.6s
 => => transferring context: 309B                                                                                                                                                               0.0s
 => [linux/arm64 internal] load metadata for docker.io/library/centos:8                                                                                                                         3.3s
 => [linux/amd64 internal] load metadata for docker.io/library/centos:8                                                                                                                         3.2s
 => [linux/arm64 1/2] FROM docker.io/library/centos:8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177                                                                   5.4s
 => => resolve docker.io/library/centos:8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177                                                                               0.6s
 => => sha256:52f9ef134af7dd14738733e567402af86136287d9468978d044780a6435a1193 83.94MB / 83.94MB                                                                                                3.2s
 => => extracting sha256:52f9ef134af7dd14738733e567402af86136287d9468978d044780a6435a1193                                                                                                       2.0s
 => [linux/amd64 1/2] FROM docker.io/library/centos:8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177                                                                   5.8s
 => => resolve docker.io/library/centos:8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177                                                                               0.5s
 => => sha256:a1d0c75327776413fa0db9ed3adcdbadedc95a662eb1d360dad82bb913f8a1d1 83.52MB / 83.52MB                                                                                                3.8s
 => => extracting sha256:a1d0c75327776413fa0db9ed3adcdbadedc95a662eb1d360dad82bb913f8a1d1                                                                                                       1.7s
 => [linux/amd64 2/2] RUN echo "I am running on linux/arm64, building for linux/amd64"                                                                                                          1.2s
 => [linux/arm64 2/2] RUN echo "I am running on linux/arm64, building for linux/arm64"                                                                                                          1.4s
                                                                                                                                                                                                     
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them                                                                                                 
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 368, in build
  File "compose/project.py", line 519, in build
  File "compose/project.py", line 501, in build_service
  File "compose/service.py", line 1111, in build
  File "compose/service.py", line 1950, in build
IndexError: list index out of range
[97794] Failed to execute script docker-compose
```

See: https://github.com/docker/buildx/issues/59
