### ISSUE TITLE
dns configuration option does not work on docker-compose==1.29.2

### ISSUE THREAD

**Issue by NicolasDorier** [docker/compose#8598]
https://github.com/docker/compose/issues/2847

**Comment by Zachery2008** [comment]
I suffer the same problem, the error likes " getaddrinfo ENOTFOUND login.microsoftonline.com"

**Comment by ndeloof** [comment]
I tested DNS support in the context of Compose V2 and can confirm `nameserver` in `/etc/resolv.conf` is **NOT** set whenever service defines `dns` and the API call to create container includes the expected `"HostConfig": "Dns": ["192.168.1.1"]`.
Will require some more investigations.

**Comment by thaJeztah** [comment]
> can confirm nameserver in /etc/resolv.conf is NOT set

@ndeloof is there no `nameserver` set at all, or "not the specified name server" ? 

In the "compose" situation (where containers are attached to a custom network), `/etc/resolv.conf` will contain the `127.0.0.11` IP address, which is the embedded DNS (which acts as a forwarder for the configured DNS).


On the default bridge network (which doesn't support the embedded DNS), the container directly uses the specified DNS;

```bash
docker run --rm --dns=192.168.1.1 alpine cat /etc/resolv.conf
nameserver 192.168.1.1
```

But when attached to a custom network, it will show `127.0.0.11`:

```bash
docker network create foo
docker run --rm --network=foo --dns=192.168.1.1 alpine cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
```

**Comment by ndeloof** [comment]
rigth, so issue is conflict between the `dns` option and implicit network being used by compose application. Confirmed custom DNS is set in resolv.conf once service is configured with `network_mode: bridge`.

Closing as "won't fix"

**Comment by rasteiner** [comment]
for people landing here:

in compose 1.29.2 - currently the latest version available through `apt-get` or `snap` in ubuntu repos - `network_mode: bridge` does **not** seem to fix any problem. It just changes nothing. 
Manually updating to a later version like the current 2.6.1 solved the issue for me (together with `network_mode: bridge`).
