### ISSUE TITLE
`docker-compose --compatibility up` gives *unknown flag: --compatibility*

### ISSUE THREAD

**Issue by timothyjward** [docker/compose#8618]
## Description of the issue

After the latest update to Docker Desktop the docker-compose commands I use when integration testing no longer work. 

As there is limited memory on development/build machines there are memory limits on the containers defined in the compose files. These compose files use version 3.x of the compose file format (they are also used for deployment), and so the memory limits does not apply locally unless the `--compatibility` flag is used. Since the latest update this flag now causes the error `unknown flag: --compatibility`. I am using `docker-compose` and not `docker compose`

## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.2
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
It happens with all of my compose files
```

## Steps to reproduce the issue

1. Attempt to `up` any compose file using `docker-compose --compatibility`

### Observed result

The command fails with `unknown flag: --compatibility`

### Expected result

The command succeeds, mapping the memory limits into the v2 compose format

### Stacktrace / full error message

```
unknown flag: --compatibility
```

## Additional information

macOS Big Sur 11.5.2, Docker Desktop 4.0.0

**Comment by ndeloof** [comment]
On Docker Desktop you have Compose V2 enabled as a system preference. Compose V2 does not support the `--compatibility` flag.

This flag is designed to generate a `version:2.x` compose file and was designed by the time of the composefile-v3 transition. With Compose Specification, `version` is now obsolete, so I wonder about your use case for this legacy feature.

**Comment by timothyjward** [comment]
> With Compose Specification, version is now obsolete, so I wonder about your use case for this legacy feature.

My requirement is that I can limit the memory available to the containers that I'm using in my integration tests. If I don't do this then the CI host (and occasionally a developer laptop) becomes unstable due to low memory and lots of swapping. Limiting the memory is different in v2 and v3 compose files, and when v3 compose syntax is used the limit does not apply when deployed locally. The recommendation in this case was to use the `--compatibility` flag with v3 syntax.

Are you telling me that by switching to the compose specification I can drop the `--compatibility` flag and still get the memory limit behaviour when deployed locally?

**Comment by ndeloof** [comment]
that's indeed the intent of the compose specification: Both syntax are valid, and tools should handle both.
Most users prefer the v2 syntax as it is simpler to write vs the composefile-v3 `deploy.resources.xxx` complex structure.

Question: how do you run your compose file on CI hosts so it require the v3 syntax? AFAIK this one is only supported by docker swarm (`docker stack deploy` command)

**Comment by timothyjward** [comment]
> Question: how do you run your compose file on CI hosts so it require the v3 syntax? AFAIK this one is only supported by docker swarm (docker stack deploy command)

The same compose file is also used for distributed deployment, not just in the build, which is why v3 is strongly preferred. As far as possible we try to keep the same definitions as it avoids the test and production deployments from diverging, the `--compatibility` flag allowed this mode of working.

**Comment by ndeloof** [comment]
Docker Compose V2 supports composefile version=3.x file format (being a subset of the Compose specification) and does not require conversion for resources limits and memory reservations. I guess we could introduce `--compatibility` flag to avoid breaking integrations, as a no-op flag.

**Comment by ndeloof** [comment]
please note `--compatibility` was already marked as DEPRECATED by docker-compose 1.29
