### ISSUE TITLE
Support `--build` option on `compose run` subcommand

### ISSUE THREAD

**Issue by yuniruyuni** [docker/compose#8623]
**Is your feature request related to a problem? Please describe.**
When using `docker-compose run` command, it will use an already built image.
But in some cases, it will be frustrated.

For example, in running a code test with the container, the container image is already built and so I always need to run `docker-compose build` before runs `docker-compose run test`.

BTW, There is no `--build` option for `docker-compose run`.
But it seems no reason why the option not exists.

If the `--build` option exists, it is ok using `docker-compose --build run test`. run with a single command and two commands are largely different user experience.

**Describe the solution you'd like**
Add `--build` and `--no-build` option for `docker-compose run` as same as `docker-compose up`.

**Describe alternatives you've considered**
- run `docker-compose up --build test`: this command assumes to run not single service so output log doesn't seem good and it can not use for interactive mode.
- run `docker-compose build ; docker-compose run test`: double commands. it doesn't compatible with other commands.

**Additional context**
- I already implemented this subcommand option: https://github.com/docker/compose/pull/8625

**Comment by ericparton** [comment]
I need the exact same feature; I came here to create the issue and it was already sitting at the top of the pile :)
