### ISSUE TITLE
i dont know why console text color changed blue from green?

### ISSUE THREAD

**Issue by bties-ogawa** [docker/compose#8629]
i like green texts.
![Screen Shot 2021-09-17 at 9 38 12](https://user-images.githubusercontent.com/20296827/133705805-b8663de6-9429-4d67-b4d8-0413a9cb0726.png)

**Comment by ndeloof** [comment]
Compose V2 is integrated in the Docker CLI and share components with the later.
This "progress" output is based on same component used by BuildKit to show build steps status.
Doing so, we obviously don't strictly reproduce the Compose V1 look'n feel.
