### ISSUE TITLE
docker-compose replaces -h with --help, even inside the run command

### ISSUE THREAD

**Issue by ewjoachim** [docker/compose#8652]
## Context information (for bug reports)

- [ ] Using Compose V2 `docker compose ...`
- [x] Using Compose V1 `docker-compose ...`

Well... `docker-compose version` version says it's v2, is this template up to date ?

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  web:
    image: debian
    networks:
      default: null
networks:
  default:
    name: warehouse_default
```

## Steps to reproduce the issue

1. `docker-compose run --rm web echo -- -h`

### Observed result

-- --help

### Expected result

-- -h

### Stacktrace / full error message

None

## Additional information

Fresh install from Docker Desktop (4.0.1,68347) using `brew install --cask docker`.

As far as I can tell, `docker-compose` replaces `-h` with `--help` in the argument, but in the case of `docker-compose run`, it also does this for the arguments of the run, which is very problematic for many commands, especially given `-h` is also usually short for `--host`, not `--help`.

For example:
`docker compose run web psql -h db` opens a psql shell on the db.
`docker-compose run web psql -h db` displays the man page of psql.

**Comment by ewjoachim** [comment]
As a sanity test, when using docker directly, I don't have the same issue:
```console
$ docker run --rm debian echo -- -h
-- -h
```

**Comment by ewjoachim** [comment]
I'm noting that the [reference manual page](https://docs.docker.com/compose/reference/run/) for docker-compose run advertises for `docker-compose run db psql -h db -U docker` which happens to be the exact example that doesn't work :)

**Comment by ewjoachim** [comment]
Ok, I don't know shit in Go, so take this with extra precautions, but as far as I can follow the code:

This seems to be the line that copies all extra args to the Command:
https://github.com/docker/compose/blob/412385c49549a48e55df45c99c40665a8eb0c36e/cli/cmd/compose/run.go#L66
This seems to be the line (in cobra) where args come from: it's from the `argWoFlag` variable
https://github.com/spf13/cobra/blob/de187e874d1ca382320088f8f6d76333408e5c2e/command.go#L845
Just above is the line where `argWoFlag` is defined:
https://github.com/spf13/cobra/blob/de187e874d1ca382320088f8f6d76333408e5c2e/command.go#L824
The `Args()` call seems to be actually from pflag:
https://github.com/spf13/pflag/blob/85dd5c8bc61cfa382fecd072378089d4e856579d/flag.go#L816

Somewhere in the middle, for each flag, go seems to be using the canonical definition rather than the one that was used in the command line.
And thanks to this line:
https://github.com/spf13/cobra/blob/de187e874d1ca382320088f8f6d76333408e5c2e/command.go#L1040
the canonical definition for `-h` is `--help`.

Hope it helps.

**Comment by ewjoachim** [comment]
Note: among all the short flags, `-h` (which is the only one coming from cobra itself as far as I can tell) is the only one affected:
```console
$ docker-compose run --rm web echo -- -h -f -p -d -e -l -T -u -v -w
-- --help -f -p -d -e -l -T -u -v -w
```

**Comment by ewjoachim** [comment]
Maybe this could help: https://github.com/spf13/cobra/issues/1155
Defining your own help flag without `-h` might prevent Cobra to think `-h` is `--help`. It would be better to ensure that the args are not modified, but if that proves complicated, then maybe this solution would be enough.

**Comment by mat007** [comment]
I can reproduce this with the compose version that comes with Docker Desktop 4.0.0 but not with the latest master build.
So, although I can’t find what fixed it in a quick search, I do believe it has been fixed in the meanwhile.
@ndeloof does that ring a bell?

**Comment by ndeloof** [comment]
This indeed was fixed on compose switch just before we made it public as https://github.com/docker/compose-switch, so no public PR/commit I can link to

**Comment by mat007** [comment]
@ewjoachim here is a master build of Docker Desktop if you wanted to try: https://desktop-stage.docker.com/mac/main/amd64/68933/Docker.dmg
Let’s close this issue, but feel free to keep commenting.
