### ISSUE TITLE
Docker compose logs freezes upon first interrupt signal

### ISSUE THREAD

**Issue by taiidani** [docker/compose#8659]
## Description of the issue

When viewing container logs with `docker compose logs --follow`, the first Ctrl+C interrupt will freeze the log view without exiting. This frozen process stays open until a second interrupt is sent to force-quit it.

## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [x] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**

<details>
<summary>Click to expand</summary>

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
</details>

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)

```yml
services:
  hello-world:
    command:
    - ping
    - localhost
    image: alpine
    networks:
      default: null
networks:
  default:
    name: dockercomposetest_default
```

## Steps to reproduce the issue

1. `docker compose up -d` the above compose YAML configuration.
1. `docker compose logs --follow`
1.  Press Ctrl+C on your keyboard

### Observed result

With V2, requiring a second Ctrl+C to force-quit the process:

https://user-images.githubusercontent.com/902500/134387150-deb863b1-3bbe-445b-89ad-12a1690b59a5.mov

### Expected result

With V1. Not the prettiest output, but it _does_ exit upon the first interrupt 😆 

https://user-images.githubusercontent.com/902500/134387557-7edca1cd-f378-416d-a5f5-24149b605018.mov

## Additional information

macOS 11.6 (20G165) using Docker for Mac 4.0.1

**Comment by ndeloof** [comment]
I also noticed this regression, and proposed https://github.com/docker/compose/pull/8656 to fix it
