### ISSUE TITLE
Regression from v1 - Cannot use environment variables comprised of other environment variables

### ISSUE THREAD

**Issue by phillipuniverse** [docker/compose#8662]
## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```yaml
services:
  postgres:
    image: postgres::-12}
    networks:
      default: null
networks:
  default:
    name: composetest_default
```

## Steps to reproduce the issue

1. Create a `docker-compose.yml` file with this content:
    ```yaml
    version: '3.8'

    services:
      postgres:
        image: ${PG_IMAGE}
    ```
2. Create a `.env` file with this content:
    ```
    PG_IMAGE=postgres:${VERSION:-12}
    ```
3. Run `docker compose config`, see weird `image` format

### Observed result

When I execute `docker-compose config` with this `.env` set up with an environment variables it evaluates to incorrect syntax with `docker-compose config`.

### Expected result

If I switch back to docker-compose 1 (by unchecking 'Use Docker Compose V2 release candidate) I get what I expect:

```
» docker-compose --version
docker-compose version 1.29.2, build 5becea4c
» docker-compose config
services:
  postgres:
    image: postgres:12
version: '3.8'
```

### Stacktrace / full error message

```
» docker-compose pull 
[+] Running 0/0
 ⠋ postgres Pulling                                                                                                                                                            0.0s
invalid reference format
```

## Additional information

![image](https://user-images.githubusercontent.com/684275/134429970-29353c6f-51b5-4467-84b6-a4dc301c3966.png)

![image](https://user-images.githubusercontent.com/684275/134429017-946c114b-1c91-4f54-a904-8237f5ef4a57.png)

**Comment by ndeloof** [comment]
godotenv library we use to parse `.env` file does not support the default value syntax for variables.

closing as a duplicate for https://github.com/docker/compose/issues/8519

**Comment by phillipuniverse** [comment]
Got it, thanks!

Is there a migration doc somewhere with the full list of breaking changes like this one? I couldn't find it in the documentation anywhere.

**Comment by ndeloof** [comment]
Nope, there's no such expected "breaking changes", this is definitively a bug we need to fix
