### ISSUE TITLE
Running compose run --rm fails in a git hook context

### ISSUE THREAD

**Issue by michaelperrin** [docker/compose#8664]
## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  bla:
    image: alpine:latest
    networks:
      default: null
networks:
  default:
    name: test-docker-git-precommit-hook_default
```

## Steps to reproduce the issue

I created a small repository to reproduce the issue (more details about it further down):

1. Clone project `git@github.com:michaelperrin/test-docker-git-precommit-hook.git`
2. Set up git hooks: `rm -Rf .git/hooks && ln -s ../bin/git/hooks .git/hooks`
3. Commit anything: `git commit -m "Yo"`

### Observed result

The container (created with `docker compose run --rm`) is getting removed as it is still running, which fails.

### Expected result

Container should be removed when it is done running.

### Stacktrace / full error message

```
Error response from daemon: You cannot remove a running container 4ad4ef2f6392706df1b18505008ed601ac02ccbb2c0b9cf076fede0d1cafadde. Stop the container before attempting removal or force remove
```

## Additional information

Happens on both Mac (with Docker Desktop 4.0.1) and Linux.

Here is what my pre-commit hook does:

* Run the `sleep 5` command in the `bla` service.
* The `bla` service is based on an Alpine linux image (could be anything else).

When removing the `--rm` part in the git pre-commit hook file (keeping only `time docker compose run bla sleep 5` in the command), you will notice that with Docker Compose 2.0.0-rc3, the command is run in only 0.x seconds, whereas it should be at least 5 seconds due to the `sleep` command that gets run in the container. I have chosen the `sleep` command but that could be any long-running command.

I guess this is why the container removal is failing, as it is removed as the command is still running inside it.

When running the pre-commit hook script separately (eg. `.git/hooks/pre-commit`), it works. I have no idea why it fails when the script runs in a git hook context.

**Comment by page-down** [comment]
docker compose compiled from the latest v2 branch works fine.
rc3 from github releases does have this issue.

**Comment by ndeloof** [comment]
This sounds like a duplicate for https://github.com/docker/compose/issues/8619

**Comment by michaelperrin** [comment]
Right, thank you @ndeloof , that's a duplicate indeed.
