### ISSUE TITLE
docker-compose.override.yml could not be empty ?

### ISSUE THREAD

**Issue by xinity** [docker/compose#8673]
## Description of the issue
trying to create an empty docker-compose.override.yml to offer a placeholder for dev teams
## Context information (for bug reports)

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
Top-level object must be a mapping
```

## Steps to reproduce the issue

1. create an empty docker-compose.override.yml
2. launch : `docker compose config`
3.

### Observed result
Top-level object must be a mapping

## Additional information

`Docker Desktop for Mac 4.0`

**Comment by ndeloof** [comment]
Docker Compose V2 indeed loads compose files _then_ merge them, and as such require each individual file to be a valid compose file, which implies not being empty (`services:` is required)

**Comment by xinity** [comment]
Got it! Thanks
