### ISSUE TITLE
security_opt and seccomp with files broken in v2

### ISSUE THREAD

**Issue by sah** [docker/compose#8678]
I'd like to be able to use seccomp files in v2.

See https://github.com/docker/compose/issues/5574 for the original v1 issue, which was addressed in https://github.com/docker/compose/pull/5701

With v2, the same compose file results in this error: 

```Error response from daemon: Decoding seccomp profile failed: json: cannot unmarshal string into Go value of type seccomp.Seccomp```

**Comment by ndeloof** [comment]
already addressed by https://github.com/docker/compose/pull/8669 AFAICT

**Comment by ndeloof** [comment]
Make me think this should be defined and documented by the Compose Specification
=> https://github.com/compose-spec/compose-spec/issues/203
