### ISSUE TITLE
cant read docker-compose.yml:no such file or directory

### ISSUE THREAD

**Issue by JackieeYin** [docker/compose#8679]
## Context information (for bug reports)

- [ ] Using Compose V2 `docker compose ...`
- [x] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
(paste here)
```

**Output of `docker version`**
```
(paste here)
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by ndeloof** [comment]
Closing as no context/description provided.
If you ask for assistance, please provide more details
