### ISSUE TITLE
--env-file does not accept unix pipes

### ISSUE THREAD

**Issue by FranciscoDA** [docker/compose#8680]
## Description of the issue

It's not possible to read environment variables from a unix pipe passed through the `--env-file` flag. This means that the following invocations are **invalid**:
```sh
$ docker-compose --env-file <(echo 'TEST_VARIABLE=TEST_VALUE') run --rm showenv
# more interesting:
$ docker-compose --env-file <(aws s3 cp s3://somebucket/somefile -) run --rm showenv
```
Compose fails with the following message: `ERROR: /dev/fd/63 is not a file.`

Unix pipes should be allowed as parameters to the `--env-file` to ensure feature parity with the docker CLI. Bear in mind that the following is a **valid** docker invocation:
```sh
docker run --env-file <(echo 'TEST_VARIABLE=TEST_VALUE') --rm ubuntu env
```

## Context information (for bug reports)

- [ ] Using Compose V2 `docker compose ...`
- [x] Using Compose V1 `docker-compose from Arch Linux repositories`

**Output of `docker(-)compose version`**
```
docker-compose version 1.29.2, build unknown
```

**Output of `docker version`**
```
Client:
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d28e
 Built:             Wed Aug  4 10:59:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d88bc
  Built:            Wed Aug  4 10:58:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.5
  GitCommit:        72cec4be58a9eb6b2910f5d10f1c01ca47d231c0.m
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  showenv:
    command: env
    environment:
      TEST_VARIABLE: null
    image: ubuntu
version: '3'
```

## Steps to reproduce the issue

1. Create a compose file with a service that accepts some environment variable
2. Try running the service passing a unix pipe to the `--env-file` flag, e.g: by using the process substitution syntax `<( ... )`

### Observed result
Compose exits with exit code 1 and the service container is not run

### Expected result
The container should be run with all the environment variables read from the pipe evaluated and interpolated just like as if it were an ordinary file.

### Stacktrace / full error message

```
ERROR: /dev/fd/63 is not a file.
```

## Additional information

Using Arch Linux. `docker-compose` installed through the official repositories by running `sudo pacman -S docker-compose`

**Comment by ndeloof** [comment]
Just tested with compose v2 and passing `--env-file` this way is fully supported.
V1 issue remains

**Comment by FranciscoDA** [comment]
Thank you Nicolas. I opened #8681 to address this issue. Do you think it could be reviewed and merged in the following days? I'm afraid am not too familiar with the development process.

**Comment by ndeloof** [comment]
We indeed plan to mostly focus on Compose V2 codebase and V1 will get lower maintenance efforts, focussing on security/critical issues.
