### ISSUE TITLE
run.sh missing for 2.0.0 release

### ISSUE THREAD

**Issue by modem7** [docker/compose#8684]
**Description**

run.sh missing for 2.0.0 release as in previous releases.

**Steps to reproduce the issue:**
1. https://github.com/docker/compose/releases/tag/v2.0.0

**Comment by ndeloof** [comment]
`run.sh` is a Compose V1 feature, using a Docker image to workaround the need for a python runtime to execute docker-compose. Compose V2 being a CLI plugin, and a plain binary cross-compiled for all systems, this isn't considered required anymore.

**Comment by modem7** [comment]
Oh doi!

I remember this now.

Idiocy abound this end!
