### ISSUE TITLE
Make docker compose errors more verbose

### ISSUE THREAD

**Issue by Dulanic** [docker/compose#8686]
I am converting from docker-compose v1 to docker compose v2. v2 will not function in my use case. I cannot identify where the error is as the error is not helpful. I am guessing it is in my .env, but a line number would help? I'd like to give more info from my .env but that holds information I can't make public as would be expected in a .env file.

**Steps to reproduce the issue:**
It is hard to say how to reproduce as I am just switching from v1 to v2 and --compatability does not help and I can't really make my .env file public.

**Describe the results you received:**
```
unexpected character "-" in variable name near "-l\n"
```
**Describe the results you expected:**
It to function like it did in v1.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 50
  Running: 50
  Paused: 0
  Stopped: 0
 Images: 56
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.14.6-051406-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.5GiB
 Name: mediaserver
 ID: RKN6:Q4WI:HH6V:BMG5:U6FT:5BZ6:YB5Q:XJDD:D23S:RNFU:GWLF:FXX3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by ndeloof** [comment]
it seems your `.env` file declares some variable with an hyphen in name, which is invalid (dot env file _should_ also be applied as plain bash variables)

see https://github.com/docker/compose/issues/8507

**Comment by Dulanic** [comment]
> it seems your `.env` file declares some variable with an hyphen in name, which is invalid (dot env file _should_ also be applied as plain bash variables)
> 
> see #8507

That would be incorrect. No variable names have a -. Some of the variable values do but the variable names do not.

**Comment by Dulanic** [comment]
I just tried RC2 and that did fix my issue, but the point still stands, the errors should be more verbose.

**Comment by Dulanic** [comment]
Reopening as I just thought about this... RC2 works but release doesn't? That seems backwards.

**Comment by Dulanic** [comment]
> please try to drop some variables from your .env file until you can provide a reproduction example

I commented out all of them and the error still continues.

**Comment by Dulanic** [comment]
Found it, it was this variable. I wrapped in quotes and that fixed it. This worked in v1.

```
RUN_OPTS=-t -l
RUN_OPTS="-t -l"
```
