### ISSUE TITLE
docker-compose doesn't have -v or --version flag to print the version

### ISSUE THREAD

**Issue by ericmenard** [docker/compose#8693]
**Steps to reproduce the issue:**
docker-compose -v
...

**Describe the results you received:**
unknown shorthand flag: 'v' in -v
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

docker-compose is a Docker CLI plugin

**Describe the results you expected:**
v2.0.0

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
v2.0.0 
```

**Comment by mat007** [comment]
It’s `docker compose version`, you can’t run the plugin directly.
See https://github.com/docker/compose#where-to-get-docker-compose
