### ISSUE TITLE
The x86_64 version of docker compose is no longer available for download

### ISSUE THREAD

**Issue by dlhoots** [docker/compose#8694]
**Description**

**Steps to reproduce the issue:**
1. Try to download the x86_64 version

**Describe the results you received:**
It's not there.

**Describe the results you expected:**
It's there.

**Comment by mat007** [comment]
For which OS? It’s `amd64` now as per the Golang style.

**Comment by dlhoots** [comment]
I figured it was something like that, but I couldn't figure out exactly what.  Thanks Mathieu.

**Comment by dlhoots** [comment]
Mathieu - any chance you could point me to the doc where this is defined so that I can figure out the right way to modify our scripts to download the correct version?
