### ISSUE TITLE
Re-introduce docker-compose --version for backwards compatibility

### ISSUE THREAD

**Issue by fspreck-indiscale** [docker/compose#8697]
**Description**

Old scripts relying on `docker-compose --version` (and possibly other commands/options?  EDIT: at least `docker-compose -f` is affected, too) fail with v2.  See also https://github.com/docker/compose/issues/8687#issuecomment-929414268.  Of course, the command could simply be replaced by `docker compose version` but would it hurt to re-introduce `docker-compose --version` for backwards compatibility?

**Steps to reproduce the issue:**
1. `docker-compose --version`

**Describe the results you received:**

```
unknown flag: --version
Usage:  docker [OPTIONS] COMMAND

docker-compose is a Docker CLI plugin

Options:
      --config string      Location of client config files (default "/home/fspreck_indiscale/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/home/fspreck_indiscale/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/home/fspreck_indiscale/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/home/fspreck_indiscale/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
```

**Describe the results you expected:**

The same as the output of `docker compose version`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version 2.0.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0)

Server:
 Containers: 16
  Running: 0
  Paused: 0
  Stopped: 16
 Images: 45
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 72cec4be58a9eb6b2910f5d10f1c01ca47d231c0.m
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.14.8-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.34GiB
 Name: E14-Arch
 ID: BXJ6:OESF:5H6T:OWPM:BMA4:64TI:ICNI:BEIB:YSH3:753G:DYPY:FZGR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by Altycoder** [comment]
I agree, v2.0 has just reached Arch and a bug has been raised that docker-compose no longer works as it wasn't announced on any mailing lists.  Also a google search for docker compose still takes you here: https://docs.docker.com/compose/ which still refers to "docker-compose" style commands - all very confusing!

**Comment by gcstang** [comment]
I agree, this should be reimplemented as to allow backwards compat, I've used it in several situations to discover the version in order to determine if there is an newer version available instead of manually performing this action.

**Comment by ndeloof** [comment]
Docker Compose V2 should **not** be installed in your PATH and used as a replacement command for Compose V1. If this is what you're looking for, check https://github.com/docker/compose-switch

**Comment by gcstang** [comment]
> Docker Compose V2 should **not** be installed in your PATH and used as a replacement command for Compose V1. If this is what you're looking for, check https://github.com/docker/compose-switch

So we should not upgrade to v2 and continue to use v1 long term if we use it as a binary?

**Comment by ndeloof** [comment]
Nope, just install the `compose-switch` and|or update your use of compose to adopt `docker compose` command.

**Comment by Altycoder** [comment]
compose-switch isn't in the arch repo so looks like the latter.  I'm going
to move to v2.0 again now and give the new command a try

**Comment by ndeloof** [comment]
follow up discussion with Arch maintainer on https://github.com/docker/compose/issues/8698

**Comment by gcstang** [comment]
> Nope, just install the `compose-switch` and|or update your use of compose to adopt `docker compose` command.

This still doesn't solve the issue at hand to upgrade the v2 docker compose application because we have no idea what version is installed once we do start to use it.

**Comment by ndeloof** [comment]
> This still doesn't solve the issue at hand to upgrade the v2 docker compose application because we have no idea what version is installed once we do start to use it.

Sorry, I don't understand this. compose-switch will replace `docker-compose` binary on your system so you can still use the exact same commands but will actually run Compose V2.

**Comment by gcstang** [comment]
> > This still doesn't solve the issue at hand to upgrade the v2 docker compose application because we have no idea what version is installed once we do start to use it.
> 
> Sorry, I don't understand this. compose-switch will replace `docker-compose` binary on your system so you can still use the exact same commands but will actually run Compose V2.
> 
> `docker-compose --version` requested on this issue will then run as expected, just report "2.0.0"

I'm fine with upgrading to version 2.0.0 of docker-compose but if I use compose-switch or call the new docker compose directly how is either going to tell me the underlying docker compose app is 2.0.0 when there is no version output from the new docker compose release starting with 2.0?

I need to know what the underlying version for the new docker compose is and the flag was dropped from version 2.

**Comment by ndeloof** [comment]
compose-swich translates the legacy `docker-compose` flags into new compose commands, so you can use `docker-compose --version` and this will actually run `docker compose version` and report `v2.0.0`

**Comment by gcstang** [comment]
> compose-swich translates the legacy `docker-compose` flags into new compose commands, so you can use `docker-compose --version` and this will actually run `docker compose version` and report `v2.0.0`

Ok, that's what I was after; much appreciated.
