### ISSUE TITLE
Released 2.0.0 docker-compose-linux-* isn't docker-compose but the compose plugin

### ISSUE THREAD

**Issue by rfay** [docker/compose#8704]
**Description**

Yesterday's release of compose 2.0.0 (congratulations!) broke a lot of things for Linux users who dare to download it, but most especially for ArchLinux users who got it by default as docker-compose.

And of course on Arch it was immediately pushed out as v2.0.0 of docker-compose, which broke all docker-compose users, because it's not a standalone binary. 

Neither the release notes nor the [docs](https://github.com/docker/compose#linux) are very clear about what to do. 

1. You'll want to engage with the ArchLinux community to get something workable going for them.
2. Please make a complete doc that just says "How do I get docker-compose on Linux". Perhaps the Arch folks will then be able to implement that in their package?
3. Please use better naming for the binary. The current naming is `docker-compose-linux-amd64`, which implies that it's docker-compose for Linux, which it certainly is not. Maybe `compose-plugin-for-docker-linux-amd64` would be clearer?

**Comment by siliconmeadow** [comment]
### Arch Linux workarounds:

1. Use the AUR `downgrade` [tool](https://aur.archlinux.org/packages/downgrade)
2. If you do stick with v2.0.0 in Arch, at the moment you could add a symlink to `docker-compose` as it's no longer in the common paths in Arch. Something like:

**Comment by nantkowiak** [comment]
1. you can use `docker compose` instead of `docker-compose`
2. you can define an alias `alias docker-compose='docker compose'` to use it like before
3. downgrade with `pacman -U /var/cache/pacman/pkg/docker-compose-{your preffered version}`

**Comment by ndeloof** [comment]
duplicates https://github.com/docker/compose/issues/8698

**Comment by ndeloof** [comment]
My preferred option to workaround this issue is that we make compose CLI plugin act as a plain `docker-compose` executable, which seems feasible. cc @ulyssessouza @justincormack

**Comment by Foxboron** [comment]
@ndeloof Can I get a positive or negative confirmation if that is going to be the plan or not? It affects the packaging decisions downstream and might complicate a few things.

**Comment by ndeloof** [comment]
@Foxboron @ulyssessouza is working on it

**Comment by ndeloof** [comment]
@Foxboron #8708 has been merged, so compose V2 binaries can be used both as CLI plugins and direct replacement for `docker-compose`. But still, as long as it's only installed into a `cli-plugins` folder, `docker-compose` won't be available anymore on `PATH` for users to upgrade. Maybe you should consider adding a symlink for backward compatibility?

**Comment by Foxboron** [comment]
@ndeloof 

Yes, of course I'll do a proper symlink :)

Please do ensure things are properly communicated downstream. This might be a bit confusing if someone gets to it a few days after the fact.

**Comment by ndeloof** [comment]
sure, will need to make it clear in the changelog (cc @ulyssessouza)

**Comment by rfay** [comment]
Pretty brilliant technique! Talk about killing lots of birds with one stone!

The docker packages could also create the docker-compose symlink.

**Comment by siliconmeadow** [comment]
@rfay - the symlink technique works, and the Arch linux install of the latest docker and docker-compose works fine with DDEV. :-)
