### ISSUE TITLE
v2.0.0 = command not found

### ISSUE THREAD

**Issue by TechnicalSuwako** [docker/compose#8709]
**Description**

Thank you for your help.
I updated the package with manjaro, but when I run "sudo docker-compose up -d" from that point on, I get "sudo: docker-compose: command not found".
To fix it, I manually downgraded to 1.29.2.

**Steps to reproduce the issue:**
1. yay -Syyu ← To upgrade docker
2. sudo docker-compose up -d && sudo docker-compose exec app bash

**Describe the results you received:**
sudo: docker-compose: コマンドが見つかりません
sudo: docker-compose: コマンドが見つかりません

**Describe the results you expected:**
Starting 〇〇_app_1 ... done
Starting 〇〇_web_1 ... done
Starting 〇〇_db_1  ... done

**Additional information you deem important (e.g. issue happens only occasionally):**
To fix the bug:
yay -R docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

**Additional environment details:**
manjarolinux64bit
zsh
python 3.7.3

**Comment by mat007** [comment]
Please read https://github.com/docker/compose#linux, the instructions for installing 2.0.0 differ from 1.x
