### ISSUE TITLE
compose v2 does not recognize the .env file in the project directory

### ISSUE THREAD

**Issue by page-down** [docker/compose#8716]
**Description**

When the compose file is specified by the `--file` parameter, the `.env` file located in the current working directory could not be loaded. After specifying the project directory with `--project-directory`, it still fails to load.

**Steps to reproduce the issue:**
1. prepare demo files
```shell
mkdir debug
printf 'services: {app: {image: alpine:3.14, network_mode: none, command: ["echo", "$DEBUG"]}}' > debug/docker-compose.yaml
printf 'DEBUG=debug' > .env
```

2. docker compose config shows warning
```shell
$ docker compose --file debug/docker-compose.yaml config
WARN[0000] The "DEBUG" variable is not set. Defaulting to a blank string.
services:
  app:
    command:
    - echo
    - ""
    image: alpine:3.14
    network_mode: none
```

3. The `.env` file cannot be loaded even after the project directory is specified in the parameters.
```shell
$ docker compose --project-directory $PWD --file $PWD/debug/docker-compose.yaml config
WARN[0000] The "DEBUG" variable is not set. Defaulting to a blank string.
...
```

4. Even if `docker-compose.yaml` exists in the current directory, the `.env` file still cannot be loaded.
```shell
printf 'services: {app2: {image: alpine:3.14, network_mode: none, command: ["echo", "from pwd $DEBUG"]}}' > docker-compose.yaml

docker compose --project-directory $PWD --file $PWD/debug/docker-compose.yaml --file $PWD/docker-compose.yaml config
docker compose --file debug/docker-compose.yaml --file docker-compose.yaml config
```

```text
WARN[0000] The "DEBUG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DEBUG" variable is not set. Defaulting to a blank string. 
services:
  app:
    command:
    - echo
    - ""
    image: alpine:3.14
    network_mode: none
  app2:
    command:
    - echo
    - 'from pwd '
    image: alpine:3.14
    network_mode: none
```

**Describe the results you received:**
The .env file does not load correctly.

**Describe the results you expected:**
It should be ensured that the .env file in the current directory, or the .env file in the project directory, is loaded correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```
Server:
 Server Version: 20.10.8
 Kernel Version: 5.10.0-8-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
...
```

**Additional environment details:**
n/a

**Comment by page-down** [comment]
It looks like the path to the `.env` file is completely bound to the folder of the first loaded `docker-compose.yaml`, regardless of where the first file is located.

This seems somewhat inappropriate.

**Comment by ndeloof** [comment]
This is by intent. `.env` file is loaded from project directory.
For your use case, prefer running `docker compose --env-file test/.env ...` from your app directory over `cd test ; docker compose -f ../docker-compose.yaml up -d`

**Comment by page-down** [comment]
> This is by intent. `.env` file is loaded from project directory.

That's exactly the question I asked.
Does `--project-directory` explicitly set the **Project Directory** ?
So should `.env` be loaded from the project directory?

Based on the steps I took to reproduce the issue, this does not seem to be the case now.
This is the current situation:
- With the `--file` argument, `.env` is read from the folder where the first `docker-compose.yaml` is located, not the project directory. This is the current intended design, and there is no plan to change it for now.
- `--project-directory` explicitly sets the Project Directory, however this does not affect the loading of `.env`.
- The documentation is incorrect about how `.env` is loaded.
- The current working directory only affects the default project directory location, it has nothing to do with `.env`, and no change to this design will be considered for now.

**Comment by ndeloof** [comment]
`--file` implicitly set project directory to target compose file parent directory
`--project-directory` set this project directory explicitly (and then `--file` is not required, as long as it uses the default name `[docker-]compose.y[a]ml`)

docs is clear the "Starting with +v1.28, .env file is placed at the base of the project directory"

**Comment by page-down** [comment]
Sorry to bother you with these questions.

So the project directory set by `--file` currently has a higher priority than `--project-directory`, right?

```shell
mkdir git-repo
printf 'services: {app: {image: alpine:3.14, network_mode: none, command: ["echo", "DEBUG=$DEBUG"], init: true}}' > git-repo/docker-compose.yaml
printf 'DEBUG=enabled' > git-repo/.env

mkdir prod-app
printf 'DEBUG=disabled' > prod-app/.env

docker compose --project-directory prod-app/ --file git-repo/docker-compose.yaml up -d

docker compose --project-name prod-app logs app
prod-app-app-1  | DEBUG=enabled
```

- `--file` implicitly set project directory to target compose file parent directory when loading
  - project directory = git-repo/
  - So this will only read the `.env` in the `docker-compose.yaml` directory (`git-repo/.env`)
- After the configuration file has been parsed, `--project-directory` changes the Project Directory again.
  - The project directory is set correctly and the project name is derived from the folder name `prod-app` .
- .env file is placed at the base of the project directory (`prod-app/.env`)
  - However, from the user's point of view, this file will not be read.

Thanks for the suggestion that it would be better to define it through more explicit parameters, so I have no problem with using `--env-file`.

However the discussion here is whether multiple arguments can cause confusion to the user when used at the same time.

**Comment by ndeloof** [comment]
Docs doesn't say precedence for both `--project-directory` and `--file`, would need to check the code to know
