### ISSUE TITLE
`docker compose pull` fails if any image is not pullable

### ISSUE THREAD

**Issue by thespad** [docker/compose#8724]
**Description**

`docker compose pull` fails if any image is not pullable (such as being locally built).

**Steps to reproduce the issue:**
1. Have a docker-compose.yml with multiple services, at least one of which uses a locally built image and one of which is from an accessible registry.
2. Run `docker compose pull`

**Describe the results you received:**
When the locally built image fails to pull, all other pulls are aborted (`dcp` is an alias for `docker compose pull`)

![image](https://user-images.githubusercontent.com/8425502/135612235-fc220881-f7cc-457a-a0f6-e7265595eb36.png)

**Describe the results you expected:**
Pulls of other images should complete even if some are unavailable, as was the behaviour with docker-compose (v1.x)

**Additional information you deem important (e.g. issue happens only occasionally):**
Passing `--ignore-pull-failures` mitigates the issue - though still reports the failures - but this is still a break in behaviour from v1.x

![image](https://user-images.githubusercontent.com/8425502/135612388-320d5eb9-190f-4405-8b7a-6569a4dc08e9.png)

**Output of `docker compose version`:**

```
Docker Compose version v2.0.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 54
  Running: 54
  Paused: 0
  Stopped: 0
 Images: 65
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-77-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: docker2
 ID: 67LS:QX2S:7P4H:CTCH:IGKD:4BKW:6HYY:46PB:LHNR:IXBV:CDSP:FXXJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: thespad
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details:**
```
Linux docker 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lanrat** [comment]
This is still an issue.

**Comment by loynoir** [comment]
Workaround
```yaml
  foobar:
    image: private/foobar
    pull_policy: never
    build:
      dockerfile: foobar.Dockerfile
```
