### ISSUE TITLE
Docker CLI - compose command `down -v` does not remove the anonymous volumes

### ISSUE THREAD

**Issue by celinederoland** [docker/compose#8728]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: BE9D82B4-3C65-44F9-8519-E206077EAF48/20211001093626

### Expected behavior

`docker compose down -v` should delete anonymous volumes used by containers defined in the docker-compose.yml file
(it does with docker-compose down -v)

### Actual behavior

`docker compose down -v` only delete containers and networks, like without the -v option

### Information

% docker -v
Docker version 20.10.6, build 370c289

% docker-compose -v
docker-compose version 1.29.1, build c34c88b2

% sw_vers
ProductName:    macOS
ProductVersion: 11.4
BuildVersion:   20F71

  - macOS Version: 11.4
  - Intel chip or Apple chip:
  - Docker Desktop Version: 3.3.3
  - Is it reproducible ? Yes
  - Is the problem new ? I don't know, it's the first time I use `docker compose down -v`

### Steps to reproduce the behavior

docker-compose.yml :
```yaml
version: '2' // Note: I also tried with version '3'

services:

  redis:
    image: redis:alpine
    networks:
      - internal
    ports:
      - "6379"

networks:
  internal:
    driver: bridge
    internal: true
```

Up the redis container, then stop it via docker compose down -v, check if the volume has been deleted or no : 

Here is my output : 

% docker volume ls
DRIVER    VOLUME NAME
% docker compose up -d redis
[+] Running 3/3
 ⠿ Network testing_internal   Created                                                                                                                                                                                                       1.5s
 ⠿ Network testing_default    Created                                                                                                                                                                                                       3.8s
 ⠿ Container testing_redis_1  Started                                                                                                                                                                                                       2.1s
% docker volume ls 
DRIVER    VOLUME NAME
local     0d2989fb2adf3fc5c3d2339136cb98879650aeabcc8b7ca6eb858129557ff75d
% docker compose down -v
[+] Running 3/3
 ⠿ Container testing_redis_1  Removed                                                                                                                                                                                                       0.1s
 ⠿ Network testing_internal   Removed                                                                                                                                                                                                       0.7s
 ⠿ Network testing_default    Removed                                                                                                                                                                                                       3.5s
% docker volume ls
DRIVER    VOLUME NAME
local     0d2989fb2adf3fc5c3d2339136cb98879650aeabcc8b7ca6eb858129557ff75d
% ==> NOT OK

Note : it works with docker-compose

% docker volume ls
DRIVER    VOLUME NAME
% docker-compose up -d redis
Docker Compose is now in the Docker CLI, try `docker compose up`
Creating network "testing_internal" with driver "bridge"
Creating testing_redis_1 ... done
% docker volume ls 
DRIVER    VOLUME NAME
local     6a2706bf09eca764679814f39a199dcd2dcccbde17636e28b4f5af1451373150
% docker-compose down -v
Stopping testing_redis_1 ... done
Removing testing_redis_1 ... done
Removing network testing_internal
% docker volume ls
DRIVER    VOLUME NAME
% ===> OK

**Comment by ulyssessouza** [comment]
IIUC the `docker-compose.yml` in the example does NOT mention any volumes. So it doesn't make sense to remove any.

**Comment by thaJeztah** [comment]
Compose should probably use the same logic as `docker container rm -v` in this case https://docs.docker.com/engine/reference/commandline/rm/

**Comment by ndeloof** [comment]
AFAICT we pass the `-v` flag to remove API https://github.com/docker/compose/blob/v2/pkg/compose/down.go#L63
https://github.com/docker/compose/blob/v2/pkg/compose/down.go#L225-L227
so not sure what's going wrong here

**Comment by celinederoland** [comment]
Hello, thank's for the investigation. I confirm it's about anonymous volumes, not about named volumes. FYI I tried without compose : `docker run redis:latest` / docker stop $container_id / docker rm -v $container_id` => the anonymous volume is  removed as expected.
