### ISSUE TITLE
docker-compose v2.0.1 Missing "version" in --help

### ISSUE THREAD

**Issue by Chaz6** [docker/compose#8729]
Although `docker-compose version` outputs the version as expected, it is missing from the --help output.

In docker-compose v1:

```
[..]
  stop               Stop services
  top                Display the running processes
  unpause            Unpause services
  up                 Create and start containers
  version            Show the Docker-Compose version information
```

In docker-compose v2.0.1:-

```
[..]
  start       Start services
  stop        Stop services
  top         Display the running processes
  unpause     unpause services
  up          Create and start containers

Run 'docker compose COMMAND --help' for more information on a command.
```

**Comment by jpdsc** [comment]
Next to this, the documentation shows --version which is incorrect. It should be docker compose version.
![image](https://user-images.githubusercontent.com/7014736/135713481-f122553e-398a-435a-ae6a-5f2b536b821e.png)

https://docs.docker.com/compose/cli-command/#transitioning-to-ga-for-compose-v2

**Comment by mat007** [comment]
Good catch @jpdsc, I opened a PR to fix the docs: https://github.com/docker/docker.github.io/pull/13637
