### ISSUE TITLE
Key cannot contain a space error message

### ISSUE THREAD

**Issue by cliny** [docker/compose#8736]
**Description**
Key cannot contain a space error message

I upgraded docker-compose to 2.0.1-1 using 'sudo pacman -Syu', and now when I enter 'docker-compose up -d' or 'docker compose up -d' I get 'key cannot contain a space'. It also happens with 'docker compose pull'

**Steps to reproduce the issue:**
1. upgrade to docker-compose 2.0.x
2. docker compose pull
3. error: key cannot contain a space

**Describe the results you received:**
error: key cannot contain a space

**Describe the results you expected:**
Run yml file correctly like in version 1.29.2

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0)

Server:
 Containers: 25
  Running: 25
  Paused: 0
  Stopped: 0
 Images: 24
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 72cec4be58a9eb6b2910f5d10f1c01ca47d231c0.m
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.69-1-lts
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.35GiB
 Name: clinyserver
 ID: x
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
arch linux

**Comment by LucasVinicius314** [comment]
For anyone having this problem, untick this in options and it should work
![image](https://user-images.githubusercontent.com/58010418/135743286-4e5e9d22-e25f-4758-8131-fcd0a654eef5.png)

**Comment by cliny** [comment]
Turns out the issue was having a space in my env file for mailu

**Comment by LucasVinicius314** [comment]
Hm I see, in my case that one option was ruining my day

**Comment by wojtek-at-mambu** [comment]
I made a custom .env file (forgot that it is auto sourced by docker compose): 
```
alias dcp='docker compose -f docker/docker-compose.yaml'
```
Indeed this was causing the above error. 
Some mention of the .env file in the message would help a lot.
