### ISSUE TITLE
Accents in unquoted environment variables with spaces cause Compose v2 to fail

### ISSUE THREAD

**Issue by jpetazzo** [docker/compose#8741]
**Description**

In a `.env` file, if there is a variable with a space, no quotes, and accents in the word(s) after the space, Compose refuses to start, with an error like the following one:

```
unexpected character "©" in variable name near "café\n"
```

**Steps to reproduce the issue:**

Create the following files:
```bash
mkdir -p /tmp/compose-v2-envaccents
cd /tmp/compose-v2-envaccents

cat >docker-compose.yml <<EOF
version: "3"

services:
  env:
    image: alpine
EOF

cat >.env <<EOF
WHAT=Pause café
EOF
```

Then `docker-compose up`.

**Describe the results you received:**

With Compose v1, it works correctly.

With Compose v2, I get the following error message and Compose refuses to start the stack:
```
unexpected character "©" in variable name near "café\n"
```

**Describe the results you expected:**

Stack starts correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

Note that this only happens when the accents are AFTER the space, and if the variable is NOT quoted.

**Output of `docker compose version`:**

```
Docker Compose version v2.0.1
```

**Similar or related issues:**

This could be related to #8626 and/or #8740, which are also related to `.env` parsing in Compose v2.

However, since it's a different error behavior altogether, I'm opening a separate issue to make sure it's tracked properly.

Thanks!

**Comment by nigurr** [comment]
+1 Any environment variable value with `space` is broken.
Surprised to see such regression

**Comment by solvaholic** [comment]
> Surprised to see such regression

See also https://github.com/docker/compose/issues/8507
