### ISSUE TITLE
Removing a stopped container stop "docker compose up" in attached mode with error

### ISSUE THREAD

**Issue by fabien-michel** [docker/compose#8747]
**Description**

Since recent upgrade to docker compose v2.0 . The "up" command in  attached mode (without the --detach flag) stop and detach when a single container is stopped then removed.
The others containers keep running.

**Steps to reproduce the issue:**
1.
docker-compose.yaml

```yaml
version: '2'
services:
  echo1:
    image: k8s.gcr.io/echoserver:1.10
    ports:
      - "8081:8000"     
  echo2:
    image: k8s.gcr.io/echoserver:1.10
    ports:
      - "8082:8000"
```
2.
in a terminal:
```
docker compose up
```
wait for echo servers to start up

3.
In another terminal
```
docker compose stop echo1
```
Wait for container to stop. The `dev-echo1-1 exited with code 137` line is displayed in first terminal output as expected

```
docker compose rm -f echo1
```
`Error: No such container: 13c269abd727d3817c1436d9e3...`
is displayed in first terminal output and the attach is lost.

**Describe the results you received:**
The following error is displayed in first terminal:
`Error: No such container: 13c269abd727d3817c1436d9e3...`

And the attach is lost.

**Describe the results you expected:**
Output should stay attached to others containers, and reattached to the container echo1 when it is run again.
This is the results with docker-compose v1

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version 2.0.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.1)

Server:
 Containers: 35
  Running: 5
  Paused: 0
  Stopped: 30
 Images: 158
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 72cec4be58a9eb6b2910f5d10f1c01ca47d231c0.m
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.14.8-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 21.43GiB
 Name: ***
 ID: HQFE:7V3Y:2HBU:FGTM:QLXY:XG2Q:IN2W:NNZY:4CLH:K5EU:HMHA:VVL4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by sdt** [comment]
`docker-compose logs -f` suffers the same problem. 

1. Run `docker-compose up` like step 2 above
2. In another terminal run `docker-compose logs -f`
3. Stop and remove a service like step 3 above

The `logs -f` command will exit with the same message that `up` exits with.

**Comment by fabien-michel** [comment]
Do not occur for me with recent versions. (v 2.2.2)
