### ISSUE TITLE
Cannot unset entry point with docker compose run --entrypoint ''

### ISSUE THREAD

**Issue by japsu** [docker/compose#8751]
**Description**

With Docker Compose V2, cannot unset container entry point by setting an empty entry point by `docker compose run --entrypoint ''`. Container entry point is used regardless of passing this option.

**Steps to reproduce the issue:**

1. Have an image that sets `ENTRYPOINT`
2. `docker compose run --entrypoint '' myservice`

**Describe the results you received:**

Container runs with original entry point

**Describe the results you expected:**

Container runs without entry point

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0-rc.3
```

**Workaround:**

For container images that have `/usr/bin/env`, it can be used as as a noop entry point. Eg.

```
docker compose run --entrypoint /usr/bin/env myservice bash
```

**Comment by japsu** [comment]
Similar bug for Docker Compose V1: #5582

**Comment by japsu** [comment]
Please get #8782 merged :)

**Comment by japsu** [comment]
This has been fixed.

Minimal test to verify

```
$ docker compose version
Docker Compose version v2.6.0
$ cat > docker-compose.yml << EOF
version: '3.1'
services:
  foo:
    image: ubuntu
    entrypoint: /bin/false
    command: /bin/true
EOF
$ docker compose run foo; echo $?
1
$ docker compose run --entrypoint= foo; echo $?
0

**Comment by ElementalWarrior** [comment]
I don't think this works as expected fyi. The command from docker-compose.yml is not called if you set `--entrpoint=""` in the cli. It instead uses the dockerfile CMD statement.

```
$ cat > docker-compose.yml << EOF
version: '3.1'
services:
  foo:
    image: python:3.8.12-slim-bullseye
    entrypoint: /bin/false
    command: echo "something"
EOF

$ docker compose run --entrypoint= foo;
[+] Building 0.0s (0/0)                                                                                                                             docker-container:vigilant_hodgkin
[+] Creating 1/0
 ✔ Network james_default  Created                                                                                                                                                0.1s 
[+] Building 0.0s (0/0)                                                                                                                             docker-container:vigilant_hodgkin
Python 3.8.12 (default, Mar  2 2022, 05:04:35) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
