### ISSUE TITLE
OnlyOffice Container not starting at all

### ISSUE THREAD

**Issue by BentiGorlich** [docker/compose#8754]
**Description**

I try to start the onlyoffice documentserver with the following command:
```
sudo docker run -i -t -d -p 8002:443 --restart=always -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql onlyoffice/documentserver
```
I get the error message: 
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.
```

It did work fine a few weeks ago, then I decided to make a complete update of my system with `sudo apt-get update`, `sudo apt-get upgrade`. After that I got the mentioned error message.
**Steps to reproduce the issue:**
I really don't know. Maybe try to run my command in docker

**Describe the results you received:**
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.`

**Describe the results you expected:**
Docker starting the container

**Additional information you deem important (e.g. issue happens only occasionally):**
everytime I try to run the command

**Output of `sudo docker compose version`:**
```
docker: 'compose' is not a docker command.
See 'docker --help'
```
**Output of `sudo docker version`:**
```
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:42 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `sudo docker info`:**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 12
  Running: 0
  Paused: 0
  Stopped: 12
 Images: 83
 Server Version: 20.10.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 4.19.0-6-amd64
 Operating System: Debian GNU/Linux bookworm/sid
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.54GiB
 Name: benni-nuc
 ID: X7IR:S4XC:K2SG:4J7V:HDXX:2JM5:57IR:UZAE:NXO3:OCIU:JIQF:FDEI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpuset support
```

**Additional environment details:**
none

**Comment by nocive** [comment]
@BentiGorlich this is docker/compose repository, not docker. Your bug report has nothing to do with what happens here, you might want to report that issue to the maintainer of the container you're trying to run, i guess here https://github.com/ONLYOFFICE/DocumentServer

**Comment by BentiGorlich** [comment]
I already did that: https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/387
And it did work for me before I updated my system. Now it doesn't anymore and I tried to run older versions of the documentserver which definitly worked for me in the past and they don't work anymore eigher

**Comment by nocive** [comment]
@BentiGorlich nonetheless, this is not the right place to report your problem. I'm not a maintainer of this project, but I can already tell that's the answer you will receive from the maintainers.

**Comment by BentiGorlich** [comment]
But then where is?

**Comment by nocive** [comment]
If it's a docker problem, you should report it in https://github.com/moby/moby

**Comment by BentiGorlich** [comment]
Ok, I opened an issue there as well: https://github.com/moby/moby/issues/42909

**Comment by mat007** [comment]
Thanks @nocive :)
