### ISSUE TITLE
linux-amd64 binary is missing under 2.0.1 assets

### ISSUE THREAD

**Issue by logopk** [docker/compose#8758]
https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-linux-amd64 does not exist.

Is this on purpose?

**Comment by Shikachuu** [comment]
The `amd64` binaries were renamed to `x86_64` in PR #8710 .
Link: https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-linux-x86_64

**Comment by logopk** [comment]
OK,

then the linux install pages need an update
https://docs.docker.com/compose/cli-command/#install-on-linux

**Comment by logopk** [comment]
Me again:

would that be then:
```
curl -SL https://github.com/docker/compose/releases/download/v2.0.0/docker-compose-linux-`uname -m` -o ~/.docker/cli-plugins/docker-compose
```

Unfortunately that again will not work on a pi 3b+: 

`uname -m == armv7l`

**Comment by danBamikiya** [comment]
@StefanScherer the provided binaries don't seem to work for downloading in RPi.

`$(uname -s)-$(uname -m)` returns `Linux-aarch64` on RPi apparently. And that isn't in any of the [binaries](https://github.com/docker/compose/releases/tag/1.29.2) for v1.29.2.

See: https://github.com/docker/docker.github.io/issues/13538#issuecomment-944961649
