### ISSUE TITLE
Docker Compose - Mounted Hard Drive Missing Folders

### ISSUE THREAD

**Issue by illusaen** [docker/compose#8759]
Hello,

I've mounted my USB hard drive in my docker-compose files. Two days ago everything worked fine; however, yesterday, some folders in the drive suddenly disappeared. Note that I do see two folders, but one is missing.

### Docker `ls -al /data`
![image](https://user-images.githubusercontent.com/13263478/136067173-c3eede41-0b78-4280-9df6-31aa8e11716e.png)

### External drive
![image](https://user-images.githubusercontent.com/13263478/136067318-257feddd-1eba-42d8-9011-c9629578889a.png)

### Docker-compose
![dockercompose](https://user-images.githubusercontent.com/13263478/136067928-9ef0da11-bdcd-42c5-b9d3-494139533e71.png)

![env file](https://user-images.githubusercontent.com/13263478/136068042-bb868dba-fe95-4853-80aa-30568d6cfe5a.png)

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: **A7321A63-5A7B-48F7-87CE-F79558751163/20211005174548**

### Actual behavior
Missing folders from mounted and bound external drive.

### Expected behavior
All folders in external drive should be mounted and visible from docker container.

### Information
  - Is it reproducible? **Yes.**
  - Is the problem new? **Yes.**
  - Did the problem appear with an update? **Unsure.**

  - Windows Version: **W10 2101H**
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  **WSL2 - Ubuntu**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **No.**

**Comment by mat007** [comment]
I’m not sure this is related to compose.
When happens if you do something like `docker run -it -v $ROOT:/data alpine ls -la /data` (you might need to adapt the command line depending on your shell)?

**Comment by tarunparmar** [comment]
Hi @illusaen did you manage resolve this ?
