### ISSUE TITLE
Improve "docker compose up" status information to help troubleshoot "depends_on" conditions

### ISSUE THREAD

**Issue by ericslandry** [docker/compose#8761]
**Description**

I'm trying to leverage `depends_on` in my `compose.yaml` file. Certain of those dependencies use the `service_healthy` or the `service_completed_successfully` conditions. When I run `docker compose up`, I see some services going from `Created` to `Started`, but it eventually hangs without any hints of what's going on.

After troubleshooting, I found out that my condition was not being met because I had messed up my dependant's `healthcheck` section. 

It would have been very useful to know the reason why compose was just waiting there forever. Instead of seeing: 
```
⠿ Container myapp-kong-1            Created                          0.1s
```
The status could of been something like:
```
⠿ Container myapp-kong-1            Depends on myapp-postgres-1      0.1s
```

**Steps to reproduce the issue:**
1. `docker compose up` with a `compose.yaml` containing a service A that depends on a service B being healthy (`service_healthy), but with service B having `healthcheck: disable: true`

**Describe the results you received:**

Hang without indication of why

**Describe the results you expected:**

Hang but with displayed reason

**Output of `docker compose version`:**

```
Docker Compose version v2.0.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  compose: Docker Compose (Docker Inc., v2.0.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 48
  Running: 30
  Paused: 0
  Stopped: 18
 Images: 69
 Server Version: 20.10.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-88-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.36GiB
 Name: REDACTED
 ID: YFOZ:E6EN:QIDV:YA4Y:AHZZ:I2QL:HFVR:LKU5:4JXI:TYN6:4GYF:RNPZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  REDACTED
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by benesch** [comment]
Oh, I just noticed that I submitted a PR to fix this very issue! See #9088.

**Comment by ericslandry** [comment]
@benesch Thanks for that PR! 

Please pardon the silly questions, but I still just see "Started" and "Running". I'm using Compose `v2.2.3`. Is there anything I must do to take advantage of your change? Do you have any tips on how to debug `docker compose`? The `docker compose --verbose up` doesn't seem to do much. If I use the `docker compose up --wait`, it hangs. Thanks in advance!

**Comment by benesch** [comment]
Hi @ericslandry. Unfortunately this change hasn't made it into a release yet. @ndeloof, is there a release of v2.2.4 planned soon?
