### ISSUE TITLE
docker compose pull doesn't recognize same image and pulls it multiple times

### ISSUE THREAD

**Issue by Spaenny** [docker/compose#8768]
**Description**

I have a docker-compose.yml defined with 3 times the same image, executing docker compose pull, pulls the same image 3 times, even tho its 3 times the same image.
I'm not 100% sure, but as far as I remember this wasn't the case in v1.

**Steps to reproduce the issue:**
1. define a docker-compose.yml with 3 times the same Image
2. execute docker compose pull

**Describe the results you received:**
It's pulling 3 times the same image and extracting it.

**Describe the results you expected:**
It should recognize it's 3 times the same image and only do it once.

**Output of `docker compose version`:**

```
Docker Compose version 2.0.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0)

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 72cec4be58a9eb6b2910f5d10f1c01ca47d231c0.m
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.69-1-lts
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.63GiB
 Name: hostname
 ID: LTH5:WYDG:XMU3:BLZN:B5RZ:CN5P:63H7:7BPK:4XAL:QR33:2H6Z:SRLO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: spaenny
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by KoditkarVedant** [comment]
@ulyssessouza I would like to work on this issue. I see the current implementation of `docker compose pull` is to pull image irrespective of checking if it is already present in locally. I see there are two things we need to do.

1, Skip pulling image if it is already present locally.
2. If the same image is used by multiple services and it is not present then we should pull that image only once.

What should be the behavior for above to cases.

1, Skip pulling image if it is already present locally.
This will show the you skipped pulling an image as it was already present.
```
[+] Running 2/3
 ⠿ ServiceName1 Skipped - Image is already present
 ⠿ ServiceName2 Skipped - Image is already present
 ⠴ ServiceName3 Pulling
```

2. If the same image is used by multiple services and it is not present then we should pull that image only once.
If image is already present locally we will show the above messages and if not and the same image is being used by multiple services it will show Skipped - Image is already pulled by ServiceName.

```
[+] Running 6/6
 ⠿ ServiceName1 Skipped - Image is already present
 ⠿ ServiceName2 Skipped - Image is already present
 ⠴ ServiceName3 Pulling
 ⠿ ServiceName4 Skipped - Image is already being pulled by ServiceName3
 ⠿ ServiceName5 Skipped - Image is already being pulled by ServiceName3
 ⠴ ServiceName6 Pulling
```

Do let me know your views.

**Comment by KoditkarVedant** [comment]
@ulyssessouza I am not sure if this is a bug or feature. I quickly downloaded the docker-compose 1.29.2 release and tried the similar example it looks like it was pulling the same image multiple times.

**Comment by KoditkarVedant** [comment]
@ulyssessouza I've opened a draft PR. I'll publish it later once we final the approach.
