### ISSUE TITLE
`stringArray` syntax not documented anywhere obvious

### ISSUE THREAD

**Issue by nutjob4life** [docker/compose#8773]
## 🐛 Description

The new combined `docker compose` (_not_ `docker-compose`) has several command-line arguments that accept a `stringArray`. However, I cannot find in any of the usual places (`--help`, the source code, docs.docker.com, etc.) any explanation for what the syntax of `stringArray` is—and there are _plenty_ of `stringArray`s.

To name a few:
```console
$ docker compose --help | egrep stringArray
  -f, --file stringArray           Compose configuration files
      --profile stringArray        Specify a profile to enable
$ docker compose run --help | egrep stringArray
  -e, --env stringArray       Set environment variables
  -l, --labels stringArray    Add or override a label
  -p, --publish stringArray   Publish a container's port(s) to the host.
  -v, --volumes stringArray   Bind mount a volume.
$ docker compose up --help | egrep stringArray
  -e, --environment stringArray   Environment variables
```

## 📜 Steps to reproduce the issue

1. Create the following `docker-compose.yaml` file in a `/tmp/fail` directory:
```yaml
---
services:
  demo:
    image: alpine
    command: echo $GREETING, $TARGET
...
```

2. Try `docker compose up` to ensure it works:
```console
$ docker compose up
WARN[0000] The "GREETING" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TARGET" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ⠿ Container fail_demo_1  Started 0.3s
Attaching to demo_1
demo_1  | ,
demo_1 exited with code 0
```

3. Try `docker compose up --environment GREETING=hello`:
```console
$ docker compose up --environment GREETING=hello
WARN[0000] The "GREETING" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TARGET" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ⠿ Container fail_demo_1  Started 0.3s
Attaching to demo_1
demo_1  | ,
demo_1 exited with code 0
```

4. Try `docker compose up --environment '[GREETING=hello]'`:
```console
$ docker compose up --environment '[GREETING=hello]'
WARN[0000] The "GREETING" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TARGET" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ⠿ Container fail_demo_1  Started 0.3s
Attaching to demo_1
demo_1  | ,
demo_1 exited with code 0
```

5. Try `docker compose up --environment '["GREETING=hello"]'`:
```console
$ docker compose up --environment '["GREETING=hello"]'
WARN[0000] The "GREETING" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TARGET" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ⠿ Container fail_demo_1  Started 0.3s
Attaching to demo_1
demo_1  | ,
demo_1 exited with code 0
```

6. Try `docker compose up --environment '[GREETING: "hello"]'`:
```console
$ docker compose up --environment '[GREETING: "hello"]'
WARN[0000] The "GREETING" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TARGET" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ⠿ Container fail_demo_1  Started 0.3s
Attaching to demo_1
demo_1  | ,
demo_1 exited with code 0
```

7. Whatever the syntax of `stringArray` is, at least _this_ still works:
```console
$ env GREETING=hello TARGET=world docker compose up 
[+] Running 1/1
 ⠿ Container fail_demo_1  Started 0.4s
Attaching to demo_1
demo_1  | hello, world
demo_1 exited with code 0
```
But taking advantage of those other `stringArray` features like passing in multiple `yaml` files to `--file` or profiles to `--profile` remain out of reach.

## 🩺 Describe the results you expected

I'd've hoped that at least attempt №5 above would've been close. Alas, no cigar. Maybe this isn't just a documentation failure, but perhaps the parsing of `stringArray`s is not yet implemented? 🤔

## 💁‍♀️ Additional information you deem important

```console
$ date -u
Sat Oct  9 16:35:33 UTC 2021
$ sw_vers
ProductName:  macOS
ProductVersion: 11.6
BuildVersion: 20G165
$ docker --version
Docker version 20.10.8, build 3967b7d
$ docker compose version
Docker Compose version v2.0.0-rc.1
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 30
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.842GiB
 Name: docker-desktop
 ID: FXXJ:CRVP:OHY4:RSCD:ST43:HAXW:JAWR:6AOM:6EO4:SOG2:CNPQ:XSF7
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 44
  Goroutines: 47
  System Time: 2021-10-09T16:26:35.819839543Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

## 🌁 Screenshots

![Screen Shot 2021-10-09 at 11 40 42 AM](https://user-images.githubusercontent.com/814813/136666972-75d2f391-87af-45ba-a530-f062f0f985cd.png)

**Comment by nutjob4life** [comment]
Okay so not just a documentation issue but an actual software bug since the `--environment GREETING=HELLO` doesn't pass the setting of `GREETING` to `HELLO` to the service 😮

**Comment by ritchiey** [comment]
Would it be possible to provide an example of `docker compose` usage with multiple compose files specified? From what @ndeloof  has said, I would expect this to work:

```bash
$ docker compose -f docker-compose.yml -f docker-compose.deploy.yml ps
$ echo $?
15
```

But it just silently exits with status 15.

**Comment by ndeloof** [comment]
about, `up --environment`, see https://github.com/docker/compose/pull/8923

**Comment by nutjob4life** [comment]
Heh, that's what I get for marking this as "documentation issue" and not "bug" like #8791   😝

Okay, thanks for letting me know. Closing this.

**Comment by pongnguy** [comment]
> Thanks @ndeloof. If it's just a flag you can repeat, any ideas why attempt № 3 above didn't do the job?

repeating -f for docker buildx bake picks up only one of the -f (repeating the flag does not amount to the documented "stringArray")

**Comment by ndeloof** [comment]
@pongnguy please open an issue on github.com/docker/buildx for this

**Comment by jcrben** [comment]
ultimately what is the proper syntax for stringArray? or sounds like it should be removed from the docs?

**Comment by ndeloof** [comment]
@jcrben "stringArray" is for a flag you can repeat. This auto-generated description is not nice, this is something to be improved

**Comment by olefasting** [comment]
Brought here by googling for an answer to the stringArray type. This could easily be addressed by changing stringArray to repeatable, or something like that. I guess that is for cobra to fix, though

**Comment by ndeloof** [comment]
For alignment with docker/cli we should use `opts.ListOpts` as flag receiver, so the help is generated in an homogeneous way
