### ISSUE TITLE
links do not populate /etc/hosts

### ISSUE THREAD

**Issue by stoutZero** [docker/compose#8776]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

On trying out Whatsapp Business API, using [WhatsApp-Business-API-Setup-Scripts](https://github.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts.git)
[links](https://docs.docker.com/compose/networking/#links) doesn't populate `/etc/hosts` with ip and hostname of the other services.

**Steps to reproduce the issue:**
1. Clone [WhatsApp-Business-API-Setup-Scripts](https://github.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts.git) to ~/biz
2. Copy `installation/{db.env,docker-compose.yml}` or `installation/postgres/{db.env,docker-compose.yml}` to root project path, i.e.: ~/biz.
3. Run `docker compose -d`

**Describe the results you received:**
In `wacore` & `waweb` container, the `nc` command to verify whether `db` container is up & ready to serve keep on spouting errors of:  

"nc: cannot get ip of host db"  

or something like that, don't remember the exact wording.

This causes `db` to not have any data, and `wacore` & `waweb` to check for connectivity to `db`, forever.

Effectively stalling the progress of my work.

**Describe the results you expected:**
`wacore` & `waweb` can verify that `db` is up & ready to serve request.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens everytime.

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 3
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.939GiB
 Name: docker-desktop
 ID: 4WGN:ODTH:PZY4:36K3:DQN6:5BB3:BW5K:WKTV:FS44:JTDI:7ISI:FGD4
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 45
  Goroutines: 49
  System Time: 2021-10-11T09:57:50.4452529Z
  EventsListeners: 5
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
- OS: macOS Catalina 10.15.7 (intel)
- Docker-Compose install method: [Docker Desktop from DMG (intel)](https://docs.docker.com/desktop/mac/install/)

**Comment by rkampas-mlg** [comment]
This has not been fixed.
