### ISSUE TITLE
Have access to the derived compose project name inside the docker-compose.yml file.

### ISSUE THREAD

**Issue by marioja** [docker/compose#8787]
**Description**

Hello, I have a compose file that creates several services with several volumes. I want to use the project name in the volume path. I know that I can set COMPOSE_PROJECT_NAME before calling docker-compose but that is not what I want to do. I want to use the compose project name that docker-compose derives from the environment, the -p arguments or its own default (directory basename) in the path for my volumes. This is not possible because as a docker-compose config command will confirm, the COMPOSE_PROJECT_NAME environment variable is only defined in each service and is not accessible in the docker-compose.yml.

Can this be implemented?

There are similar issues but they are not specifically for this request

**Steps to reproduce the issue:**
1. Use ${COMPOSE_PROJECT_NAME} in docker-compose.yml when defining the path of  a volume

**Describe the results you received:**

I get an error that the variable does not exist

**Describe the results you expected:**

The volume path should be created with the content of the COMPOSE_PROJECT_NAME
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
docker-compose version
docker-compose version 1.25.5, build unknown
docker-py version: 4.4.4
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Output of `docker info`:**

```
docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version:
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-84-generic
 Operating System: Ubuntu Core 18
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.833GiB
 Name: mailu
 ID: 23LZ:TKZK:23SL:BMJC:VPNL:YP3J:D43T:K45T:GHPX:OZTX:B5JP:FYTD
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details:**

**Comment by masi** [comment]
> Is anyone looking at this?

No. You are not the fist one to ask for it.

This is a standing request for years. But as it is the custom of the Docker devs, they tend to ignore the wishes of their users.

**Comment by ndeloof** [comment]
@masi complaining and having sharp words against maintainers will not help. Please also notice I'm not a Docker employee anymore and still maintain docker compose on my space time. If you really consider this topic an important one (which is not my own priority), you're welcome to prepare a pull-request as a constructive proposal.

**Comment by masi** [comment]
@ndeloof No, it's not helping. Usually I do not complain at Github. But more then once users and their request have been belittled by the devs. I got the impression of a bunch of arrogant chaps that don't think much of the unwashed masses that post here.

**Comment by marioja** [comment]
Here is the use case.  This is not cooked up, I am actually doing this (see https://mailu.io/1.8/ if you are wondering where I am coming from)

I have a docker-compose.yml file that defines 10 services defined (10 containers).  Among the 10 services 15 volumes are defined similarly to:
`/home/user1/${COMPOSE_PROJECT_NAME}/vol1:/vol1`

I want to create a folder /home/user1/system1 and copy the docker-compose.yml file in that folder.  Then I would like to change to the folder and type: 

docker-compose -d up

What I would like to happen is that all of the volume defined in my docker-compose.yml file to be created as a subfolder of the system1 folder.  Since docker-compose knows that the derived project name of my project is system1, I would like it to be usuable from the compose file.

I know that I can define an environment variable  COMPOSE_PROJECT_NAME and set it to system1 BEFORE invoking the docker-compose command and that will work and I use that as a workaround.  However, since docker-compose knows this already, I should not have to tell it again with the risk of making a typo when defining the environment variable.

As I mentioned earlier, I know that inside each of those 10 containers the variable COMPOSE_PROJECT_NAME  is defined and set to system1 which is great but that does not help me in my docker-compose file.

I cannot state the requirement clearer and it is very important to me.  Also, I know that everyone likes to question every requirements one puts out and I will state that the reason I put all those volumes inside the home directory is because the docker software is installed by default on ubuntu server as a snap and by default configuration which I am not willing to change, the home directory is one place where docker can write to (in case anyone asked).

**Comment by marioja** [comment]
As I said previously, if anyone (@ndeloof hint hint) is willing to point me in the right direction and spend 15 minutes with me answering some basic questions, I would be willing to submit a working pull request.  I just do  not have the time to figure out the docker-compose code at this point in time.

**Comment by marioja** [comment]
> My point here is not to block such a feature, but to better understand your use-case. Would you like to use such a `/opt/local/${COMPOSE_PROJECT_NAME}/data75` path as a bind mount on host, and keep the application code "portable" or is your application code actually dependent on `COMPOSE_PROJECT_NAME` (which would sound scary to me)? In the former case, why don't use volumes?

I am not sure I understand.  The application does not care where the volumes are, it is me the HUMAN who cares and wants them in a specific place.

**Comment by ndeloof** [comment]
> The application does not care where the volumes are, it is me the HUMAN who cares and wants them in a specific place.

Yes, that's the point: I guess there's confusion between bind mount (where a human want to manage path) and volumes that are managed by the docker daemon and user should _NOT_ know the path, only access by the abstraction.

About approving this feature, this should be first introduced in the compose specification (https://github.com/compose-spec/compose-spec/blob/master/spec.md#interpolation) declaring `COMPOSE_PROJECT_NAME` as an implicit variable.

**Comment by ndeloof** [comment]
see https://github.com/compose-spec/compose-spec/pull/206/files#diff-bc6661da34ecae62fbe724bb93fd69b91a7f81143f2683a81163231de7e3b545R234-R244

**Comment by masi** [comment]
Other use cases:
```
services:
  app:
    networks:
      foobar:
      default:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.my.tld
```

```
services:
  app:
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.my.tld`)

```

**Comment by marioja** [comment]
> see https://github.com/compose-spec/compose-spec/pull/206/files#diff-bc6661da34ecae62fbe724bb93fd69b91a7f81143f2683a81163231de7e3b545R234-R244

I understand the concept of a spec however I do not understand how it applies. What does the spec do in making this feature work? Or put differently, why would it not work if it is not in the spec.  Also, do you want help in doing this?

**Comment by ndeloof** [comment]
compose could support features/syntax not defined set by the spec, but then this would be specific to this implementation and would create portability issues. Having this set in the spec enforce you won't get bad surprised in the future.
Also, compose v2 heavily relies on compose-go, which is part of the compose-spec as reference binding for go, so simpler/safer to keep all those aligned

**Comment by masi** [comment]
What's the correct procedure then? Get the ok for a change of the spec first and then provide patches for composer v1 and v2.

**Comment by ndeloof** [comment]
@masi would be nicer indeed to get approval on the spec side, then apply changes to compose v2
I don't think v1 will be updated  anymore for "new features" as compose v2 has been released.
