### ISSUE TITLE
v2 variable interpolation is incompatible with v1

### ISSUE THREAD

**Issue by i-ky** [docker/compose#8799]
Here is a minimalistic example of Docker Compose file:
```yaml
version: "3.8"

services:
  test:
    image: ${FOO?bar-baz}
```

In v2 this is interpolated same way regardless of `FOO` presence in environment (showing v2.0.0, but v2.0.1 behaves same way):
```bash
$ docker-compose --version
Docker Compose version v2.0.0
$ docker-compose config
services:
  test:
    image: baz
    networks:
      default: null
networks:
  default:
    name: interpolation_default
$ FOO=foo docker-compose config
services:
  test:
    image: baz
    networks:
      default: null
networks:
  default:
    name: interpolation_default
```
It seems to apply the following [rule](https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution):
> `${VARIABLE-default}` evaluates to `default` only if `VARIABLE` is unset in the environment.

...with `VARIABLE` being `FOO?bar`.

In contrast, v1 acts differently depending on `FOO` presence:
```bash
$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
$ docker-compose config
ERROR: Missing mandatory value for "image" option interpolating ${FOO?bar-baz} in service "test": bar-baz
$ FOO=foo docker-compose config
services:
  test:
    image: foo
version: '3.8'
```

It seems to apply a different rule, namely:
> `${VARIABLE?err}` exits with an error message containing `err` if `VARIABLE` is unset in the environment.

...with `VARIABLE` being `FOO`.

I would say that v1 behaviour is more desirable. For example, it allows to provide hints in `err` featuring commands to set environment variables in a way that a given `docker-compose.yml` expects them. Commands are very likely to contain `-` and be misinterpreted by v2.

**Comment by i-ky** [comment]
Here is a v1 unit test showing a similar scenario:
https://github.com/docker/compose/blob/f35db7f31b3e8c3b1b040ac6fccd4dd0e98c7758/tests/unit/config/interpolation_test.py#L427-L429

**Comment by bkuhl** [comment]
This also happens when the `:-` syntax is used for environment variables in v2, but works for v1.  Recreation steps:

**.env**
```
MY_IMAGE=me/project:${MY_IMAGE_TAG:-latest}
```

**docker-compose.yml**
```
version: "3.8"

services:
  project:
    image: ${MY_IMAGE}
```

 - v1: Runs as expected with the image result being `me/project:latest`
 - v2: Errors out with: `Error response from daemon: no such image: me/project::-latest}: invalid reference format`

**Comment by bkuhl** [comment]
@ulyssessouza Would you be able to add the `Docker Compose v2` tag to this one?
