### ISSUE TITLE
Error: service "extensions" has neither an image nor a build context specified: invalid compose project

### ISSUE THREAD

**Issue by sudo-bmitch** [docker/compose#8809]
**Description**

The error message when an extension field is created within a service rather than the top level of the compose file is confusing in version 2.

**Steps to reproduce the issue:**

```yaml
version: "3.7"


services:
  x-image: &common-image
    image: busybox
    command: echo hello world

  example:
    <<: *common-image
```

**Describe the results you received:**

```
$ docker compose -f dc.extensions.yml up
service "extensions" has neither an image nor a build context specified: invalid compose project
```

**Describe the results you expected:**

`docker-compose` works without any errors:

```
$ docker-compose -f dc.extensions.yml up
Creating test_x-image_1   ... done
Attaching to test_example_1, test_x-image_1
x-image_1  | hello world
example_1  | hello world
test_example_1 exited with code 0
test_x-image_1 exited with code 0
```

Alternatively, an error message along the lines of `Error parsing compose file: line 5: x-image: extension fields are not permitted outside of the top level` would also work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
$ docker compose version
Docker Compose version v2.0.1
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  compose: Docker Compose (Docker Inc., v2.0.1)
  instadock: Deploy docker nodes with ansible and terraform (InstaDock, 0.1)
  linstadock: Deploy docker nodes with ansible and terraform (InstaDock, 0.1)
  regctl: Manage docker registries (regclient, 0.1)
  scan: Docker Scan (Docker Inc., v0.8.0)
WARNING: Plugin "/home/bmitch/.docker/cli-plugins/docker-compose.save" is not valid: plugin candidate "compose.save" did not match "^[a-z][a-z0-9]*$"

Server:
 Containers: 26
  Running: 14
  Paused: 0
  Stopped: 12
 Images: 587
 Server Version: 20.10.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: dqsh1676dth0ip0hlrccy893b
  Is Manager: true
  ClusterID: 4br5nravhmolmnau4vi5tsq1a
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 127.0.0.1
  Manager Addresses:
   127.0.0.1:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-10-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.17GiB
 Name: bmitch-t490
 ID: PBKW:E6DI:RN6M:OIXQ:XQ4G:FR5U:VHV2:DTOY:ATUP:WRJM:27G2:ON4H
 Docker Root Dir: /home/docker
 Debug Mode: false
 Username: sudobmitch
 Registry: https://index.docker.io/v1/
 Labels:
  from_ansible=true
  laptop=true
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 192.168.64.0/19, Size: 24

WARNING: No swap limit support

```

**Additional environment details:**

**Comment by talesam** [comment]
> **Descrição**
> 
> A mensagem de erro quando um campo de extensão é criado dentro de um serviço em vez do nível superior do arquivo de composição é confusa na versão 2.
> 
> **Etapas para reproduzir o problema:**
> 
> ```yaml
> versão : " 3.7 "
> 
> 
> services :
>    x-image : & common-image 
>     image : comando busybox
>      : echo hello world
> 
>   exemplo :
>      << : * imagem-comum
> ```
> 
> **Descreva os resultados que você recebeu:**
> 
> ```
> $ docker compose -f dc.extensions.yml up
> service "extensions" has neither an image nor a build context specified: invalid compose project
> ```
> 
> **Descreva os resultados que você esperava:**
> 
> `docker-compose` funciona sem erros:
> 
> ```
> $ docker-compose -f dc.extensions.yml up
> Creating test_x-image_1   ... done
> Attaching to test_example_1, test_x-image_1
> x-image_1  | hello world
> example_1  | hello world
> test_example_1 exited with code 0
> test_x-image_1 exited with code 0
> ```
> 
> Como alternativa, uma mensagem de erro semelhante a `Error parsing compose file: line 5: x-image: extension fields are not permitted outside of the top level`também funcionaria.
> 
> **Informações adicionais que você considera importantes (por exemplo, o problema acontece apenas ocasionalmente):**
> 
> **Saída de `docker compose version`:**
> 
> ```
> $ docker compose version
> Docker Compose version v2.0.1
> ```
> 
> **Saída de `docker info`:**
> 
> ```
> $ docker info
> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   app: Docker App (Docker Inc., v0.9.1-beta3)
>   buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
>   compose: Docker Compose (Docker Inc., v2.0.1)
>   instadock: Deploy docker nodes with ansible and terraform (InstaDock, 0.1)
>   linstadock: Deploy docker nodes with ansible and terraform (InstaDock, 0.1)
>   regctl: Manage docker registries (regclient, 0.1)
>   scan: Docker Scan (Docker Inc., v0.8.0)
> WARNING: Plugin "/home/bmitch/.docker/cli-plugins/docker-compose.save" is not valid: plugin candidate "compose.save" did not match "^[a-z][a-z0-9]*$"
> 
> Server:
>  Containers: 26
>   Running: 14
>   Paused: 0
>   Stopped: 12
>  Images: 587
>  Server Version: 20.10.9
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Cgroup Version: 1
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: active
>   NodeID: dqsh1676dth0ip0hlrccy893b
>   Is Manager: true
>   ClusterID: 4br5nravhmolmnau4vi5tsq1a
>   Managers: 1
>   Nodes: 1
>   Default Address Pool: 10.0.0.0/8  
>   SubnetSize: 24
>   Data Path Port: 4789
>   Orchestration:
>    Task History Retention Limit: 5
>   Raft:
>    Snapshot Interval: 10000
>    Number of Old Snapshots to Retain: 0
>    Heartbeat Tick: 1
>    Election Tick: 10
>   Dispatcher:
>    Heartbeat Period: 5 seconds
>   CA Configuration:
>    Expiry Duration: 3 months
>    Force Rotate: 0
>   Autolock Managers: false
>   Root Rotation In Progress: false
>   Node Address: 127.0.0.1
>   Manager Addresses:
>    127.0.0.1:2377
>  Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
>  runc version: v1.0.2-0-g52b36a2
>  init version: de40ad0
>  Security Options:
>   apparmor
>   seccomp
>    Profile: default
>  Kernel Version: 4.19.0-10-amd64
>  Operating System: Debian GNU/Linux 10 (buster)
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 8
>  Total Memory: 31.17GiB
>  Name: bmitch-t490
>  ID: PBKW:E6DI:RN6M:OIXQ:XQ4G:FR5U:VHV2:DTOY:ATUP:WRJM:27G2:ON4H
>  Docker Root Dir: /home/docker
>  Debug Mode: false
>  Username: sudobmitch
>  Registry: https://index.docker.io/v1/
>  Labels:
>   from_ansible=true
>   laptop=true
>  Experimental: true
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
>  Default Address Pools:
>    Base: 192.168.64.0/19, Size: 24
> 
> WARNING: No swap limit support
> ```
> 
> **Detalhes adicionais do ambiente:**

Everything that starts with "x-" in docker-compose is an extension, just remove that dash or put another letter instead of x.

ex.

```
versão : " 3.7 "


services :
   ximage : & common-image 
    image : comando busybox
     : echo hello world

  exemplo :
     << : * imagem-comum
     
```

**Comment by talesam** [comment]
> **Description**
> 
> The error message when an extension field is created within a service rather than the top level of the compose file is confusing in version 2.
> 
> **Steps to reproduce the issue:**
> 
> ```yaml
> version: "3.7"
> 
> 
> services:
>   x-image: &common-image
>     image: busybox
>     command: echo hello world
> 
>   example:
>     <<: *common-image
> ```
> 
> **Describe the results you received:**
> 
> ```
> $ docker compose -f dc.extensions.yml up
> service "extensions" has neither an image nor a build context specified: invalid compose project
> ```
> 
> **Describe the results you expected:**
> 
> `docker-compose` works without any errors:
> 
> ```
> $ docker-compose -f dc.extensions.yml up
> Creating test_x-image_1   ... done
> Attaching to test_example_1, test_x-image_1
> x-image_1  | hello world
> example_1  | hello world
> test_example_1 exited with code 0
> test_x-image_1 exited with code 0
> ```
> 
> Alternatively, an error message along the lines of `Error parsing compose file: line 5: x-image: extension fields are not permitted outside of the top level` would also work.
> 
> **Additional information you deem important (e.g. issue happens only occasionally):**
> 
> **Output of `docker compose version`:**
> 
> ```
> $ docker compose version
> Docker Compose version v2.0.1
> ```
> 
> **Output of `docker info`:**
> 
> ```
> $ docker info
> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   app: Docker App (Docker Inc., v0.9.1-beta3)
>   buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
>   compose: Docker Compose (Docker Inc., v2.0.1)
>   instadock: Deploy docker nodes with ansible and terraform (InstaDock, 0.1)
>   linstadock: Deploy docker nodes with ansible and terraform (InstaDock, 0.1)
>   regctl: Manage docker registries (regclient, 0.1)
>   scan: Docker Scan (Docker Inc., v0.8.0)
> WARNING: Plugin "/home/bmitch/.docker/cli-plugins/docker-compose.save" is not valid: plugin candidate "compose.save" did not match "^[a-z][a-z0-9]*$"
> 
> Server:
>  Containers: 26
>   Running: 14
>   Paused: 0
>   Stopped: 12
>  Images: 587
>  Server Version: 20.10.9
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: cgroupfs
>  Cgroup Version: 1
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: active
>   NodeID: dqsh1676dth0ip0hlrccy893b
>   Is Manager: true
>   ClusterID: 4br5nravhmolmnau4vi5tsq1a
>   Managers: 1
>   Nodes: 1
>   Default Address Pool: 10.0.0.0/8  
>   SubnetSize: 24
>   Data Path Port: 4789
>   Orchestration:
>    Task History Retention Limit: 5
>   Raft:
>    Snapshot Interval: 10000
>    Number of Old Snapshots to Retain: 0
>    Heartbeat Tick: 1
>    Election Tick: 10
>   Dispatcher:
>    Heartbeat Period: 5 seconds
>   CA Configuration:
>    Expiry Duration: 3 months
>    Force Rotate: 0
>   Autolock Managers: false
>   Root Rotation In Progress: false
>   Node Address: 127.0.0.1
>   Manager Addresses:
>    127.0.0.1:2377
>  Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
>  runc version: v1.0.2-0-g52b36a2
>  init version: de40ad0
>  Security Options:
>   apparmor
>   seccomp
>    Profile: default
>  Kernel Version: 4.19.0-10-amd64
>  Operating System: Debian GNU/Linux 10 (buster)
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 8
>  Total Memory: 31.17GiB
>  Name: bmitch-t490
>  ID: PBKW:E6DI:RN6M:OIXQ:XQ4G:FR5U:VHV2:DTOY:ATUP:WRJM:27G2:ON4H
>  Docker Root Dir: /home/docker
>  Debug Mode: false
>  Username: sudobmitch
>  Registry: https://index.docker.io/v1/
>  Labels:
>   from_ansible=true
>   laptop=true
>  Experimental: true
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false
>  Default Address Pools:
>    Base: 192.168.64.0/19, Size: 24
> 
> WARNING: No swap limit support
> ```
> 
> **Additional environment details:**

Everything that starts with "x-" in docker-compose is an extension, just remove that dash or put another letter instead of x.
https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields

```
versão : " 3.7 "


services :
   ximage : & common-image 
    image : comando busybox
     : echo hello world

  exemplo :
     << : * imagem-comum

```

**Comment by sudo-bmitch** [comment]
> Everything that starts with "x-" in docker-compose is an extension, just remove that dash or put another letter instead of x. https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
> 
> ```
> versão : " 3.7 "
> 
> 
> services :
>    ximage : & common-image 
>     image : comando busybox
>      : echo hello world
> 
>   exemplo :
>      << : * imagem-comum
> ```

Using an extension field was intentional, but it breaks if you use it within a service rather than at the top level. E.g.

```yaml
version: "3.7"

services:
  x-image: &common-image
    image: busybox
    command: echo hello world

  example:
    <<: *common-image
```

could be converted to 

```yaml
version: "3.7"

x-image: &common-image
  image: busybox
  command: echo hello world

services:
  example:
    <<: *common-image
```

but we need a better error message to tell users to do that. The original file works today with compose v1, so this is a breaking change for some users.

**Comment by sudo-bmitch** [comment]
Not stale.

**Comment by runofthemill** [comment]
Just ran into this, and the language in the section, at least for the [composer specification](https://docs.docker.com/compose/compose-file/#extension), implies it should work at the service level. Emphasis mine:

> Special extension fields can be of any format as long as their name starts with the x- character sequence. **They can be used within any structure** in a Compose file. This is the sole exception for Compose implementations to silently ignore unrecognized field.
>
> [...]
> 
> The contents of such fields are unspecified by Compose specification, and can be used to enable custom features. Compose implementation to encounter an unknown extension field **MUST NOT fail**, but COULD warn about unknown field.

Seems either the behavior is unintended or the wording should be adjusted?

**Comment by zlnox** [comment]
This is really a terrible setting, which is very unfriendly to novices. It took me a long time to find the cause of the problem。Because my service is called x-ui
`version: "3.7"
services:
  x-ui:
    image: enwaiax/x-ui:latest
    container_name: x-ui
    restart: unless-stopped
    network_mode: host`

**Comment by ndeloof** [comment]
I wonder we should relax the extension rule in the compose specification so that it doesn't apply to such top-level elements, where child entries are not actually keywords but just plain keys in a map.
