### ISSUE TITLE
ADD in Dockerfile fails during fig build

### ISSUE THREAD

**Issue by wernight** [docker/compose#882]
Dockerfile:

    ADD bar /bar

fig.xml

    foo:
      build: .

Note that `./bar` is a directory.

Docker builds correctly:

    $ docker build .
    ADD bar /bar

Fig fails:

    $ fig build
    ADD bar /bar
    Service 'foo' failed to build: bar: no such file or directory

Note that I'm running Fig installed via pip in a virtualenv (if that changes anything) but the same issue appears with the version installed via:

    curl -L https://github.com/docker/fig/releases/download/1.0.1/fig-`uname -s`-`uname -m`

**Comment by wernight** [comment]
Related to #817 except the directory is not empty.

**Comment by wernight** [comment]
Another note/bug, when `.dockerignore` contains:

    bar

The even adding a file like `ADD bar/something.txt` will fail via `fig build` but work via `docker build`.

**Comment by dnephin** [comment]
Is this still a problem with latest compose and docker?

**Comment by wernight** [comment]
Didn't get through this one in a while but I had many issues when a directory cannot be accessed by Docker user even if that direction isn't going to be mounted.

**Comment by dnephin** [comment]
I'm not able to reproduce this issue with the current master, so I believe it's been fixed.
