### ISSUE TITLE
Project name derived from parent directory is truncated

### ISSUE THREAD

**Issue by quinncomendant** [docker/compose#8822]
When using `docker compose`, the project name is derived from the parent project directory, and this is prepended to container names, volume names, network names, etc. Recently, there was a change in how docker derives the name from the parent directory, and the name is truncated if the parent directory name contains dots. For example, a parent directory named `www.example.com` will now result in a project name of `www` whereas previously the project name would be `wwwexamplecom`. 

This is a problem because the names will result in conflicts even though the parent directory names are unique, e.g., parent directory names `www.example.com` and `www.example.org` are unique, but both will result in project name of `www`.

## Previous behavior:

- Parent directory name: `../www.example.com`
- Derived project name: `wwwexamplecom`
- Container name: `wwwexamplecom_web_1`
- Volume name: `wwwexamplecom_dbdata`
- Network name: `wwwexamplecom_default`

## New behavior:

- Parent directory name: `../www.example.com`
- Derived project name: `www`
- Container name: `www_web_1`
- Volume name: `www_dbdata`
- Network name: `www_default`

I'm using Docker Desktop 4.0.1 on macOS 10.14.6.

This behavior change happened sometime in the past last month. 

**Steps to reproduce the issue:**
1. Set up a docker project in a directory named `www.example.com`
2. Use this as `docker-compose.yml`: https://pastebin.com/raw/QMu02SfQ
3. Run `docker compose up -d`

**Describe the results you received:**

When running `docker compose up -d`, the output will show project name prefix of `www_`:

```
[+] Running 3/3
 ⠿ Network www_default  Created                                                                                0.1s
 ⠿ Container www_db_1   Started                                                                                1.3s
 ⠿ Container www_web_1  Started                                                                                1.1s
```

**Describe the results you expected:**

The project name prefix should be `wwwexamplecom`, for example:

```
[+] Running 3/3
 ⠿ Network wwwexamplecom_default  Created                                                                      0.1s
 ⠿ Container wwwexamplecom_db_1   Started                                                                      1.3s
 ⠿ Container wwwexamplecom_web_1  Started                                                                      1.1s
```

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 23
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 979.9MiB
 Name: docker-desktop
 ID: EZDW:RV4M:USW7:US43:6SDX:CXSJ:B44Q:HA5P:7OF2:FURP:4NRK:ARQ2
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 44
  Goroutines: 47
  System Time: 2021-10-22T23:27:05.11292931Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by rfay** [comment]
Using COMPOSE_PROJECT_NAME or `-p` does not solve the problem is the project name contains '.'. It still gets truncated. The problem isn't just about when the project name is computed from project directory. Could we update the title to indicate that? Something like "Project name with dots or other characters gets truncated" ?

**Comment by t3easy** [comment]
@rfay Set the project name to the string without dots as a workaround. But I guess you’re asking for a solution for ddev. Maybe it’s better to use v1 for now.

**Comment by rfay** [comment]
Yes, in this case [ddev](https://github.com/drud/ddev) is a wrapper on docker-compose. So changing ddev to rip out the dots requires a code change... to ddev instances that are out in the wild and expecting consistent docker-compose behavior. The user who first stumbled on this identified it as a v1/v2 issue right away.
