### ISSUE TITLE
Using contexts in conjunction with docker-compose yields unxepected results

### ISSUE THREAD

**Issue by maxupp** [docker/compose#8837]
**Description**

We are using remote contexts to deploy containers to a production machine. The images are built on a CI machine for testing purposes, and then deployed to production using "docker-compose --context remote up -d".
This works fine for initial deployment, but code changes do not lead to a rebuild of the deployed images. The new images are built and tested without issue on the CI machine, but the aforementioned command yields console output, that says the deployed containers are up-to-date.

I am under the impression that the containers should be updated by the command.

**Steps to reproduce the issue:**
1. Build images locally (docker-compose build)
2. Deploy iamges to different context (docker-compose --context CONTEXT up)
3. Make local changes.
4. Rebuild images.
5. Deploy again.

**Describe the results you received:**
"container-name is up-to-date."

**Describe the results you expected:**
The local changes should be deployed.

**Additional information you deem important (e.g. issue happens only occasionally):**

I would like to understand which parts of the build/deploy processes happen on which machine when using --context with docker-compose, so I'd be grateful for a short write-up.

**Comment by maxupp** [comment]
This unfortunately doesn't work, since digests are not valid image tags:

**Error response from daemon: build tag cannot contain a digest**

**Comment by ndeloof** [comment]
sure, only use digest to _deploy_ you application from images hosted on a registry, not to build them

**Comment by maxupp** [comment]
Unfortunately, the whole point of using contexts this way was to forgo access to a Docker registry.

**Comment by ndeloof** [comment]
then.. I didn't understood what you're trying to achieve :'(

**Comment by ndeloof** [comment]
> Build images locally (docker-compose build)
so, your image is present on (local) context

> Deploy images to different context (docker-compose --context CONTEXT up)
assuming this is a remote context, image is unknown and need to be pulled from registry (or rebuilt from source). 

Can you please clarify?

**Comment by ndeloof** [comment]
> will build images locally, and then transfer the built images to the target context, in this case the production machine

wrong. Compose does not "transfer images". Either it builds on the remote context, or it will let the remote context pull images from a registry, but there's no such thing like a "_transfert image from my local context to a remote one_"
(would be nice, but that's not how context and local engine image store are designed)

so, you basically rebuild images on your production context - to be debated if this is "better" than using a registry...
if you want to enforce images are up-to-date with code, you can run `docker compose up --build`

**Comment by maxupp** [comment]
> if you want to enforce images are up-to-date with code, you can run `docker compose up --build`

That is incorrect unfortunately, when I tried that it just gave me an "... is up-to-date".

**Comment by maxupp** [comment]
@ndeloof So do you have any further ideas regarding this issue?

**Comment by ndeloof** [comment]
nope. compose doesn't anything to cross the context boundaries. If you don't publish your images on a registry, there's no magic for compose to convert source code on your laptop into images running, but `build`. I can't tell whats going on in your installation.

**Comment by maxupp** [comment]
https://stackoverflow.com/questions/69484853/why-is-docker-compose-still-using-an-old-image-when-using-a-remote-context

This guy seems to have the exact same issue...

**Comment by maxupp** [comment]
I'd like to reopen this issue, since it appears to be a legitimate bug.

**Comment by ndeloof** [comment]
until you provide a reproduction scenario, I can't help much here.
`compose up` on a remote context without a published image will NEVER use an image from your local docker image storage (by definition of context isolation)

**Comment by plamen-nikolov** [comment]
You can easily solve the problem by adding an image tag
```
services:
  web:
    image: image-name:v1.0
```
Every time the name is changed, docker compose up --build recreates the image

1) Increase the version of the tag
2) docker-compose --context CONTEXT -f docker-compose.yaml build
3) docker-compose --context CONTEXT -f docker-compose.yaml stop
4) docker-compose --context CONTEXT -f docker-compose.yaml rm -f
5) docker-compose --context CONTEXT -f docker-compose.yaml up -d --build
