### ISSUE TITLE
Compose V2 down --volumes does not remove named volumes created outside but referenced in docker-compose.yml

### ISSUE THREAD

**Issue by danw-mpl** [docker/compose#8850]
**Description**

Identical to https://github.com/docker/compose-cli/issues/1798 - looks like this bug is back or there's a difference because I'm creating the named volume outside of Compose.  Does not happen with Compose V1.

**Steps to reproduce the issue:**

**docker-compose.yml**
```yaml
services:
  mysql:
    ...
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    name: mysql_data
```

**Our 'data load' script**
```
docker container create --name temp_container -v mysql_data:/root hello-world
docker cp SRC DST temp_container:/root/
docker rm temp_container
```

```
docker-compose up
docker-compose down --volumes
```

**Describe the results you received:**
The volume was not removed.
```
$ docker-compose down --volumes
[+] Running 6/6
 ⠿ Container mysql            Removed
```

**Describe the results you expected:**
The volume should be removed.

**Additional information you deem important (e.g. issue happens only occasionally):**
Disabling V2 resolves the issue.

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 277
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 24.91GiB
 Name: docker-desktop
 ID: 5D3O:26MQ:Z2PW:6RRD:3DHC:BDCX:VHLK:TF4T:GI2R:UDS6:UXMA:VPEI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**
Docker Desktop 4.1.1 (69879) on Windows 10 1909.

**Comment by kikar** [comment]
Same thing happening to us, this is our load script:
```sh
docker volume create api_mysql
CONTAINER_NAME=$(docker container create -v api_mysql:/root hello-world)
docker cp ${LOCAL_PATH}/docker-data/. ${CONTAINER_NAME}:/root
docker rm -f ${CONTAINER_NAME}
```
docker-compose.yml
```yaml
services:
  mysql:
    image: mysql:5.7.13
    volumes:
      - mysql:/var/lib/mysql
      
volumes:
  mysql:
```
Using `Docker Compose version v2.1.1` on `macOS 11.6.1`

**Comment by ndeloof** [comment]
As you're " creating the named volume outside of Compose" IMHO it is desirable that compose does not remove this volume. Also, should be declared as `external: true` in your compose file to make it clear this is an volume you manage. Relying on matching names is a fragile approach.

IMHO Compose v2 should check the volume matching name has the expected labels to confirm it was created by a previous compose run, not just happen to conflict by name (I can imagine scenario where you unexpectedly get an existing volume used)

**Comment by kikar** [comment]
What do you would be the best way to achieve the same result then?
I need to create a volume for compose with some data already in it

**Comment by ndeloof** [comment]
create your volume and populate with data, but in your compose file mark this volume as `external: true` so that compose will use the existing one and won't try to manage its lifecycle

**Comment by danw-mpl** [comment]
Okay, that makes sense from a lifecycle management perspective.

Will close the issue for now.  Thank you.
