### ISSUE TITLE
Run CI tests on multiple Docker versions

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#886]
Our CI tests should run on several recent versions of Docker. The best way to do that would probably be to use [Docker's Jenkins instance](https://jenkins.dockerproject.com/), managed by @jfrazelle I think.

**Comment by jfrazelle** [comment]
I have ideas!!! I was telling @aanand lol but I might just try something out with a Dockerfile and multiple `ADD` lines pulling the binaries from get.docker.com, then running some scripts or something

**Comment by thaJeztah** [comment]
Wouldn't the storage of those versions interfere with each other? Or is a full cleanup needed between starting each version?

Liking the creativity :)

**Comment by jfrazelle** [comment]
well if you run the daemon in a container much like the integration-cli tests in docker you cna have setup and tear down and all that mumbo jumbo :D

**Comment by thaJeztah** [comment]
mumbo jumbo. My favorite!

**Comment by bfirsh** [comment]
@jfrazelle If we test on the same infrastructure as the engine do we get testing on Windows and OS X for free? :D

**Comment by jfrazelle** [comment]
not osx and windows is still experimentally testing

**Comment by dnephin** [comment]
PRs #858 and #958 are both blocked on being able to run tests against a newer docker than the one available from wercker.

**Comment by aanand** [comment]
Update: see #1005, which uses Docker-in-Docker to test against multiple versions.

**Comment by bfirsh** [comment]
Put this back on the backlog because with #1066 we may only need to test against Docker 1.6. :)

**Comment by aanand** [comment]
Closed by #1005.
