### ISSUE TITLE
publish images for compose v2 to dockerhub

### ISSUE THREAD

**Issue by emeryao** [docker/compose#8871]
the [image](https://hub.docker.com/r/docker/compose) on docker hub is still at v1.29.2  
could we publish the latest v2 images to dockerhub ?

It's more convenient for me to use the `docker/compose` image to run compose commands than downloading the compose binaries and it's also easier to keep updated with the latest docker compose version

For example I use the compose image to deploy a compose-yml
```shell
$ docker container run --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $PWD/compose.yml:/srv/compose.yml \
    docker/compose:1.29.2 \
    -f /srv/compose.yml up -d
```

It's so convenient that there is no need to find and download the latest binary of docker-compose and deploy it to the local machine and it's so easy to keep updated by just updating the image version

**Comment by mat007** [comment]
That’s a good point, thanks for raising it!

**Comment by ciaranmcnulty** [comment]
Would be good for grabbing the binary in our own images (the same way the builds-bin ones are used)

**Comment by ndeloof** [comment]
as a CLI plugin, why not just get compose bundled into https://hub.docker.com/_/docker ?

**Comment by ciaranmcnulty** [comment]
@ndeloof it's possible, but currently other plugins (like buildx) aren't bundled either

**Comment by johnthagen** [comment]
> as a CLI plugin, why not just get compose bundled into https://hub.docker.com/_/docker ?

@ndeloof The docs for that image don't mention `compose`, are you saying it is officially supported there or that it could be instead of continuing to publish a separate `compose` image?

**Comment by ndeloof** [comment]
I mean the `docker` image _should_ include the CLI plugins. As @ciaranmcnulty noticed, it doesn't even includes buildx.
I don't know who's managing it

**Comment by thaJeztah** [comment]
The `docker` image on hub includes what's bundled in the static packages from download.docker.com, which do not (yet) contain plugins.

**Comment by ndeloof** [comment]
@thaJeztah sure, but that's just publisher decision to do so. Could also write Dockerfile so the image includes all released CLI plugins, right?

**Comment by BlackQube** [comment]
+1
would be nice to use some features like profiles with the image

**Comment by daklaus** [comment]
+1 from me as well. Currently I am adding Compose v2 to the [docker][1] image with my own Dockerfile and use the resulting image as a replacement for the original [docker][1] image for [docker-in-docker builds on GitLab CI/CD pipelines][2].

[1]: https://hub.docker.com/_/docker
[2]: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-docker-executor-with-docker-in-docker

**Comment by dR3b** [comment]
Please push the image to Docker Hub now!

**Comment by johnthagen** [comment]
Now that Docker Compose V2 is GA, could new Docker Images be pushed?

- https://www.docker.com/blog/announcing-compose-v2-general-availability/

**Comment by glours** [comment]
🎉 
```console
> docker pull docker
Using default tag: latest
latest: Pulling from library/docker
9981e73032c8: Already exists
77b8a1a2bc33: Pull complete
fa25d67de920: Pull complete
f0bace62412b: Pull complete
0d8b8a1b3f8c: Pull complete
ddd73b574414: Pull complete
d1491e487ee1: Pull complete
b7428344a1d2: Pull complete
cf19d592fc22: Pull complete
Digest: sha256:d11ece2878a6f8efbced93964e6ae22aa21721bc0efd9ef2e7e28685859d49d9
Status: Downloaded newer image for docker:latest
docker.io/library/docker:latest
> docker run --rm docker docker compose version
Docker Compose version v2.5.0
```

**Comment by emeryao** [comment]
Hi Team

with the release of [`docker/compose@v2.6.0`](https://github.com/docker/compose/releases/tag/v2.6.0) the latest docker image I pulled from dockerhub still comes with `compse@v2.5.1` so I can not get the latest compose by the method above by  @glours 

and IMHO it is possible to always get latest compose with image of `docker/compose` at v1.x ages just by pulling the latest `docker/compose` images

---
Sorry for my poor English

**Comment by emeryao** [comment]
```
$ docker pull docker:latest
latest: Pulling from library/docker
Digest: sha256:101f87347f4f6e14857f00f216d838399cc879791a6c6c15e00cc374c1ff55b5
Status: Image is up to date for docker:latest
docker.io/library/docker:latest
```

```
$ docker run --rm docker:latest docker compose version
Docker Compose version v2.5.1
```
