### ISSUE TITLE
Context cannot be set correctly to child directory

### ISSUE THREAD

**Issue by niko-dunixi** [docker/compose#8877]
**Description**

From a parent directory using a `docker-compose.yaml` and subdirectories with `Dockerfile`s, the context can never be set to the same folder where the `Dockerfile` exists.

**Steps to reproduce the issue:**

I've created a repository housing code that demonstrates the issue. This is located here: https://github.com/paul-nelson-baker/docker-compose-context-problem

1. Create a docker-compose.yaml file in a project root directory with a service that has instructions to build a subfolder
2. Create a Dockerfile in a child directory and have `COPY` instructions to pull in files immediately adjacent and validate that an independent `docker build .` works in that directory.
3. From the project root directory, execute a `docker compose up`

**Describe the results you received:**
From the parent directory the build fails. Either the context is set to the parent directory with `.` or specifying `./sub-dir` incorrectly tries to find `./sub-dir/sub-dir`. We cannot specify the actual subdirectory.

**Describe the results you expected:**
Build should have succeeded, using the correct context.

**Output of `docker compose version`:**

```bash
$ docker compose version
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```bash
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 175
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 9.731GiB
 Name: docker-desktop
 ID: SYRQ:Y7VC:UBNI:U53J:Q4I2:7KIS:TSKB:5SRQ:7ANT:HK7X:VVSA:ZJDG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
MacOS BigSur 11.6

```bash
$ uname -a
Darwin 00000760902mac 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
```

**Comment by fOmey** [comment]
I'm experiencing a issue I think may be related to this.. 

I'm attempting to process multiple docker-compose.yml's using the `-f` arg.

However when doing so, if one of the docker-compose.yml's includes build context it fails:

`ERROR: build path /home/docker/samba/www either does not exist, is not accessible, or is not a valid URL.`

It's looking for build paths in the wrong subdirectories..

Directory layout is something like the following:

- /home/docker/samba/docker-compose.yml
- /home/docker/webserver/www/docker-compose.yml
- /home/docker/webserver/www/Dockerfile

Webserver docker-compose.yml
```
version: "3"

services:
  www:
    build:
      context: ./www
      dockerfile: Dockerfile
```

Samba docker-compose.yml
```
version: "3"

services:
  samba:
    image: dperson/samba:latest
```
