### ISSUE TITLE
docker compose break variable environments

### ISSUE THREAD

**Issue by LaendaEagle** [docker/compose#8879]
Hello,

I have from long time using variable environment that is a space separated list of values in the form of:
MY_VARIABLE=value1 value2 value3

Some of the values contains dash character '-'

Since the last Docker Desktop update having both space and dash in the same variable does return an error:
unexpected character "-" in variable name near "value1 value-2 \n"

However a) having a list of values without dash in them is working and b) having a single value with dash in it is working too

**Steps to reproduce the issue:**
1. create a .env file with MY_VARIABLE=value1 value-2
2. map the environment variable in the compose yaml 
    environment:
      - VAR=$MY_VARIABLE
3. docker-compose up

**Describe the results you received:**
unexpected character "-"

**Describe the results you expected:**
the container start (as before)

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 22
  Running: 0
  Paused: 0
  Stopped: 22
 Images: 20
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 5.805GiB
 Name: docker-desktop
 ID: TZ32:EUIY:G7IR:NBDN:RP6B:YYTT:YYNR:RIUV:SOWR:6QON:AZQM:VA6Y
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 45
  Goroutines: 45
  System Time: 2021-11-04T07:34:08.59931441Z
  EventsListeners: 3
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  registry.peoplefone.net:443
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by LaendaEagle** [comment]
Apparently the change was to align docker-compose behaviour with standards (I was not aware about).
By quoting the whole variable it works properly
MY_VARIABLE="value1 value-2"

It is a break of backward compatibility, but it is also aligning the behaviour with standards... hard to say it is a bug even if it is annoying.
I think you can close this issue.

**Comment by jansonjc** [comment]
I found the same issue when I was trying to it for [apache druid](https://druid.apache.org/). Docker Compose V2 is not able to parse the [environment file](https://github.com/apache/druid/blob/master/distribution/docker/environment). There are two options I see.

1. Change the environment file to quote the whole variable (mentioned by @LaendaEagle [above](https://github.com/docker/compose/issues/8879#issuecomment-960529010))
2. Disable Docker Compose V2 in Docker Preferences > General > Uncheck "Use Docker Compose V2" or by running the command `docker-compose disable-v2`

I would treat this as a bug and get it fixed, as it is breaking backward compatibility.

**Comment by dannylee8** [comment]
I have this same issue, I believe there is another thread on this same issue: 
https://github.com/docker/compose/issues/8763
