### ISSUE TITLE
Request: Add guidelines about testing to CONTRIBUTING.md

### ISSUE THREAD

**Issue by funkyfuture** [docker/compose#889]
I often forget to run `flake8` before committing.
Furthermore I'm experiencing *very* different test-results depending on what tool is used (`py.test`, `tox`, `script/test`, wercker-build).

I'd appreciate a guideline on suggested testing before commiting.
It may also include an advice on what to do when a wercker-build fails though it's obviously not caused by the commits.

**Comment by aanand** [comment]
Good point. There's a section on "Running the test suite" that literally just reads `$ script/test` - I think we can at least explain what that does (i.e. it builds a container for running the tests in and then runs `flake8` and `nosetests`, passing any arguments you've supplied through to the latter).

As for Wercker - we're going to scrap that soon and [move onto Docker's Jenkins infrastructure](https://github.com/docker/fig/issues/886).
