### ISSUE TITLE
docker compose (v2) down -v removes volumes not mentioned in the docker-compose file

### ISSUE THREAD

**Issue by ylilarry** [docker/compose#8895]
**docker compose down -v removes all volumes under the same PROJ_NAME**

I have multiple services running under the same `PROJ_NAME`, but they are launched by different docker-compose files. The effect of having them running under the same `PROJ_NAME` is that when I run `docker compose ps` on any docker-compose file, I see
        

        NAME                       COMMAND                  SERVICE             STATUS              PORTS
        kaleido-api-postgres       "docker-entrypoint.s…"   postgres            created             
        kaleido-api-sdk            "python3 /opt/bin/sd…"   sdk                 running             
        kaleido-api-server         "/bin/sh -c 'python3…"   server              created             
        kaleido-api_doc-server_1   "sh /entrypoint.bash"    doc-server          running             

Note that even though each service is defined separately in different compose file, they are all listed (not sure if this is the expected behavior? but that's not the bug focused by this report.)

When I run `docker compose up`, only the services defined in the current compose file are launched, this is the correct behavior.

When I run `docker compose down`, only the services defined in the current compose file are removed, this is the correct behavior.

When I run `docker compose down -v`, however, all volumes from the 4 services are removed. This is the wrong behavior. The correct behavior is only the volumes defined in the current compose file is removed.
        
Example, running `docker compose down -v` from the docker-compose file that lauched `doc-server`, I get:

        [+] Running 0/0
         ⠋ Volume kaleido-api-vscode-server  Removing                                                                                                                     0.0s
         ⠿ Network kaleido-api_default       Error                                                                                                                        0.0s
        Error response from daemon: remove kaleido-api-vscode-server: volume is in use - [c94633c92eda18ee851f559df5641752d56077262265d15fb528c43b85d0c705]

`Volume kaleido-api-vscode-server ` is defined in the docker-compose file that lauched sdk. It is not mentioned in the same docker-compose file. Therefore, it shouldn't be removed.

**Additional information you deem important (e.g. issue happens only occasionally):**

PROJ_NAME is set globally as `kaleido-api`. All services are under the same `PROJ_NAME`, which is probably why `docker compose` is confused.

**Output of `docker compose version`:**

```
Docker Compose version v2.1.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  compose: Docker Compose (Docker Inc., v2.1.0)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 19
  Running: 5
  Paused: 0
  Stopped: 14
 Images: 452
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.773GiB
 Name: docker-desktop
 ID: VLPM:ZHTS:OUNK:NUUL:I2SH:XYBY:JYMT:MJ25:TOUF:HFTF:E7I6:3HF6
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 293
  Goroutines: 388
  System Time: 2021-11-07T23:09:02.2620976Z
  EventsListeners: 19
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by ndeloof** [comment]
`compose up` obviously need a compose file to know what needs to be ran.
`compose down` can be ran with only a project name, and will stop all resources. Ran with a compose file, it _only_ stop the ones from the compose file. This is mostly for backward compatibility
But as we decided to adopt this behavior (?) we should also apply this to volumes, so this has to be fixed

**Comment by Blefish** [comment]
Ran into the same problem with v2 when using `down --volumes`
Docker-compose doesn't seem to care that we would like only containers specified with `-f` to be stopped and instead removes all containers.

**Comment by johnytiago** [comment]
Hey folks, sorry to be re-opening the issue. But even with the latest version `compose: Docker Compose (Docker Inc., v2.2.3)` we're still having the same problem. All project volumes, even the ones declared outside of the compose file are deleted when running `down --volumes`
