### ISSUE TITLE
Compose completely stops when a container name is already in use by container - v2.1.0 

### ISSUE THREAD

**Issue by symrex** [docker/compose#8899]
**Description**

Yesterday I upgraded my docker-compose to version 2.
I started a project-1-compose.yml all went fine.
When I tried to start a second project-2-compose.yml where one container name is already assigned, but the whole compose (all container inside) does not start. In Compose V1 at least all other containers started, only global_traefik did not start as intended.

**Compose project structure explained**
Each project has a container called global_traefik defined in its compose.yml. This manages all requests to the containers. If another project is started which has also defined the global_traefik container, this one (global_trafik) will not be started, but all other containers in this compose.
This makes it possible to run several projects individually, but also simultaneously if necessary.

* Project-1-compose.yml
    * p1-nginx-1
    * p1-php-1
    * global_traefik (container_name: explicit defined)
* Project-2-compose.yml
    * p2-nginx1-
    * p2-php-1
    * global_traefik (container_name: explicit defined)
* Project-n-compose.yml
    * ...

**Steps to reproduce the issue: in Compose V2**
1. Project No. 1 `docker compose up -d` -> all fine
1. Project No. 2 `docker compose up -d` -> 
> Conflict. The container name "/global_traefik" is already in use by container

**Steps to reproduce the issue: in Compose V1**
1. Project No. 1 `docker-composeV1 up -d` -> all green and fine
> Creating project1_webserver_1 ... done
> Creating project1_php_1 ... done
> Creating global_traefik ... done
1. Project No. 2 `docker-composeV1 up -d` -> all container except global_traefik are starting
> Creating project2_webserver_1 ... done
> Creating project2_php_1 ... done
> Creating global_traefik ... error
> ERROR: for traefik  Cannot create container for service traefik: Conflict. The container name "/global_traefik" is already in use by container "c8dc7bc02969dee3d56d80af072768adcf9ee7ce3c1e655704a058407475665c". You have to remove (or rename) that container to be able to reuse that name.

**Additional information you deem important (e.g. issue happens only occasionally):**
In composeV1 I just ignored the error and was able to work without any problems.
In composeV2 none of container inside project-2-compose.yml is starting.

**Output of `docker version`:**

<details>
    <summary><b>docker version</b> </summary>
    

Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:59 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

</details>

**Output of docker compose version:**

* `docker compose version`: Docker Compose version v2.1.0
* `docker-composeV1 --version`: docker-compose version 1.29.2, build 5becea4

**Output of `docker info`:**

<details>
    <summary><b>docker compose version</b> </summary>
    

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  compose: Docker Compose (Docker Inc., v2.1.0)
  scan: Docker Scan (Docker Inc., v0.9.0)

Server:
 Containers: 7
  Running: 4
  Paused: 0
  Stopped: 3
 Images: 170
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-38-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.57GiB
 Name: pcname
 ID: ******
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ******
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

</details>

**Final word**
Maybe it could be possible to add a startup parameter `--ignore-fail-startup`, which explicitly allows to start a compose even there is one container that fails to start.

Or maybe there some other ways how I could achieve the same condition. I would like, if it would be possible to refrain from setting up a seperate compose only for traefik.

Thanks for your time!

**Comment by ndeloof** [comment]
While I understand your setup, silently ignoring one of the container can't be setup by compose is a design mistake imho. I wonder we could support such a use-case with "external services" (suggested on compose-spec [here](https://github.com/compose-spec/compose-spec/issues/73)

I would suggest as a workaround you use [profiles](https://docs.docker.com/compose/profiles/) so you don't always run this "singleton" container for all projects, just the first one being ran, but this will be your responsibility to select this profile first time you start one of your projects.

**Comment by symrex** [comment]
Looks like that from now on I must specify this explicitly using profiles.
Thanks for your help!
