### ISSUE TITLE
Composability of docker-compose environments

### ISSUE THREAD

**Issue by rupert-madden-abbott** [docker/compose#8905]
At the moment, there is a single mechanism supported by docker-compose for setting environment variables for docker-compose itself: [the .env file](https://docs.docker.com/compose/env-file/).

There are a bunch of things I want to do as a user for which this mechanism gets me a little, but not all, of the way. I think all of these things relate to the composability of docker-compose environments. Perhaps there are already ways of achieving this with docker-compose but I haven't been able to work out anything satisfactory.

**Avoiding Repetition**

I want to specify the same piece of information in multiple places. Sometimes, these may be things that need to change per environment but often they will be effectively constants.

Example: Service A which is exposed to the docker network at `a:3000` and service B needs to know how to talk to service A. I likely want to define constants `SERVICE_A_HOST` and `SERVICE_A_PORT` and pass them to both service A and service B.

Example: Multiple services all use images from the same private registry. I want to define this registry in a single place and reference it in the `image` attribute for each service.

It is perfectly possible to use a `.env` file for this but not at the same time as satisfying other use cases. If we want to use `.env` for this then that also means checking this file into version control so that it can be shared with others and make it easy to run without having to ask each person to set a bunch of defaults that will likely never need to change.

**Overriding**

I want to specify that a service runs in a specific way by default, but optionally allow it to be overridden due to the specifics of the host environment.

Example: A service needs to know what public URL it is being exposed on so that it can supply this information at runtime to other systems that need to talk to it e.g. an OAuth 2 redirect URL. This necessarily needs to be passed in on a per system basis but when running on a developer machine, this will always be `localhost`. Therefore, we want to set a default of `localhost` but allow this to be overridden at runtime.

This is somewhat possible with `.env`. I could define a variable in `.env` and set it to `localhost` and check `.env` into version control. However, what do I do when I want to override it? I could edit the `.env` file but then I will get conflicts or possible accidental reversions of changes when pulling. I'm also mixing together constants that should not really be overridden but just need to be referenced in multiple places, and configuration i.e. things that may have a sensible default but are likely to need to change at least occasionally.

I could just use the `.env` file for the defaults and use some other mechanism for overriding by ensuring the value is set as an environment variable. The problem then is I need to make sure that value is set in all of the right places. If I have a lot of values to overwrite then probably want to specify them in another file and ensure those values get loaded in all of the same places that the `.env` file gets loaded. I can either:

* Pass the environment variables to the docker-compose process on every run -> Brittle
* Wrap the docker-compose process in my own scripts that ensure my custom mechanism is loaded -> Brittle and surprising
* Set the environment variables in the environment on startup/login -> Implicit and surprising

**Layering**

I want to provide multiple layers of defaults to make it easier to override configuration in different degrees.

Example: Services vary in terms of how they want to be told about other services. Sometimes they expect a host and a port as separate variables. Sometimes they want a URL. Sometimes they want a connection string. I want to have the following environment variables set: `SERVICE_A_HOST=a`, `SERVICE_A_PORT=3000`, `SERVICE_A_URL=a:3000` so that I can select the appropriate variable depending on what a given service wants.

This is somewhat possible as long as I am happy to repeat the values of host and port but it would be better if I could do this `SERVICE_A_URL=${SERVICE_A_HOST}:${SERVICE_A_PORT}` but this is not possible.

Example: Multiple services are all following the same versioning scheme and are on the `dev` tag. When I start a feature, this might cut across more than once service and produce feature specific tags. When I promote the services up to test, they should all switch to the `test` tag.

This is not currently possible. I want to define a default variable of `TAG=dev` and also `SERVICE_A_TAG=${TAG}`, `SERVICE_B_TAG=${TAG}` such that users can override the tags of an individual service, or all services. However, the best I can do is set individual values for each service and then force a user to repeat themselves if they want to override all of them in one go.

**Comment by ulyssessouza** [comment]
For environments you can also use:
- "--env-file"
- "-e" in various commands

For the layering section:
- The answer on composing environment variables is coming with the merge of https://github.com/compose-spec/compose-go/pull/76. So that will be quite soon.
- Also compose file merging can be used to produce this kind of behavior


References:
Environment variables - https://docs.docker.com/compose/environment-variables/
Merging compose files - https://docs.docker.com/compose/production/
