### ISSUE TITLE
`docker compose exec -T` breaks binary input

### ISSUE THREAD

**Issue by bertjwregeer** [docker/compose#8909]
**Description**

I am using `cat file | docker-compose exec -T` to allow me to run commands and pipe input directly into a PostgreSQL database. I am using a binary dump created by `pg_dump` for this.

This currently fails because somewhere `docker compose exec -T` is changing the input text and breaking the binary fields causing Postgres to raise an error.

I don't have a good way to reproduce the error without providing the input files I am using, unfortunately, but:

```
cat backups/account.sqlc | docker exec -i compose-db-1 pg_restore --format=c --username=account --dbname=account --clean --if-exists
```

succeeds, while

```
cat backups/account.sqlc | docker compose exec -T db pg_restore --format=c --username=account --dbname=account --clean --if-exists
```

Fails partway through due to some binary data being corrupted before it reaches `pg_restore`. 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

I expect that `docker compose exec -T` functions exactly like `docker exec -i`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```
% docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.75GiB
 Name: docker-desktop
 ID: MMW2:EUZG:SCSC:CXX3:FCSX:ENSY:GIXU:SFQC:XYOU:VCLK:3GVO:JITD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by dlouzan** [comment]
We've just experienced this issue in combination with a sentry postgres custom-format restore. In our case, it's even worse because the command just returned no error code, so our ansible playbooks happily reported *this is fine*. Replacing the `docker compose exec -T` with `docker exec -i` works, as reported by the OP.

**Comment by bertjwregeer** [comment]
@dlouzan you are correct, there is no error report, there is no notification that something has failed catastrophically, instead it just returns.

In my case PostgreSQL's output to stderr in another container (seen by docker-compose logs -f) told me that something went wrong.

**Comment by ndeloof** [comment]
This might be related to https://github.com/docker/compose/pull/8938
Would you be able to give it a try (can build binaries by `make compose-plugin`)

**Comment by bertjwregeer** [comment]
@ndeloof What dependencies do I need to have installed to be able to build it? What else do I need to do to test it? How do I override the built-in Docker for Mac Desktop compose plugin?

I'm a user of docker-compose, not a developer thereof.

**Comment by ndeloof** [comment]
the build is fully containerized, so you just need `make` command installed and docker running.
Binary will be compiled into `bin/docker-compose`. Add it to your PATH (`export PATH=<path_to_compose_project>/bin:$PATH`) and check `docker-compose version` render a "in development" commit sha:
```
➜  ~ docker-compose version
Docker Compose version v2.1.1-18-gc21fdd5b
```
