### ISSUE TITLE
compose run command issues message "requires at least 1 arg(s), only received 0"

### ISSUE THREAD

**Issue by WhisperingChaos** [docker/compose#8919]
**Description**
Execution of  ```docker-compose --file=./ubuntu.yml run -d``` fails with message ```requires at least 1 arg(s), only received 0``` when given a seemingly correctly formatted yml file.

**Steps to reproduce the issue:**
1.  Use ```docker pull ubuntu:latest``` to populate local docker engine with  ```ubuntu:latest``` image. 

2.  Create simple docker-compose yml file named ```ubuntu.yml``` containing the following:
```
version: "3.9"
services:
  ubuntu:
    image: ubuntu
```
3. Execute ```docker-compose --file=./ubuntu.yml run -d``` in directory containing yml file.

**Describe the results you received:**
```docker-compose``` issues message ```requires at least 1 arg(s), only received 0```.   A container for the service isn't started nor a default network.

**Describe the results you expected:**
ubuntu service should start, creating a container and network,  then execute this container in detached  mode.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens every time.

Correct behavior occurs when service name is specified: ```docker-compose --file=./ubuntu.yml run -d ubuntu```.  Service is started, container and network are created, and container is running in detached mode.

Seems like the ```docker run...``` command generated by "docker-compose" is missing the service's image name.

Lastly, without having to specify the service name: ```docker-compose --file=./ubuntu.yml down``` properly terminates and removes both the started container and default network.  This behavior suggests the yml syntax is correct and that a bug exists in ```docker compose run```. 
  

**Output of `docker compose version`:**
```
Docker Compose version v2.0.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 19
  Running: 4
  Paused: 0
  Stopped: 15
 Images: 135
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1023-azure
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.79GiB
 Name: TraxBeth
 ID: FY24:BKWL:QPQO:MMGZ:WTZZ:4QFT:ZW3K:5W5F:EIDR:NPUA:H7QL:OBPB
 Docker Root Dir: /home/servicepc/Desktop/.docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

**Additional environment details:**

**Comment by thaJeztah** [comment]
I think you may be looking for the `docker-compose up` command, which brings up the services in the compose file. https://docs.docker.com/compose/reference/run/

`run` is for starting a one-off container, and expects one or more services to be specified as argument.

**Comment by WhisperingChaos** [comment]
@thaJeztah 

Thanks for setting me straight!  I would like the error message to be more meaningful.

Take care.

**Comment by thaJeztah** [comment]
Yes, agreed, the error could probably be somewhat better
