### ISSUE TITLE
Should report duplicate volume destination

### ISSUE THREAD

**Issue by wernight** [docker/compose#892]
foo:
      volumes:
       - 111:a
       - 222:a

In this example it should report that two source volumes are tried to be mapped to the same target file/directory.

Note: Not sure if this should be a Docker issue.

**Comment by aanand** [comment]
It should definitely be a Docker issue! This should raise an error, but doesn't:

    $ docker run -v /etc:/something -v /usr:/something busybox ls /something

**Comment by dnephin** [comment]
Looks like this was fixed in docker
