### ISSUE TITLE
connectivity broken when proxy is involved

### ISSUE THREAD

**Issue by ivanaareon** [docker/compose#8924]
**Description**

**Steps to reproduce the issue:**
1. Install desktop version 4.1 or later over Windows 10 and WSL 2 / debian.
2. setup a multi-app environment driven by swarm networking.
3. Install OpenConnect-GUI VPN client to acces a VPN through proxy
4. Open shell from any POD and try to make, for example, curl request to any IP or endpoint within the VPN.

**Describe the results you received:**
You get into any POD shell, and try to make a request to any IP or endpoint within the VPN. You can make ping, but curl requests are timming out.

**Describe the results you expected:**
I expect to be able to connect to any IP endpoint within the VPN, the same way I can do from windows command line, outside docker PODs.

**Additional information you deem important (e.g. issue happens only occasionally):**
No matter how do you configure Docker desktop proxy settings, the results are always the same.

**Output of `docker compose version`:**
```
Docker Compose version v2.0.0-rc.2
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.2)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 44
  Running: 43
  Paused: 0
  Stopped: 1
 Images: 99
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: peifzoyo9id1pmg5eqjcrcs5l
  Is Manager: true
  ClusterID: z76h58jdhbxxn2sgeywb97qzh
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.34GiB
 Name: docker-desktop
 ID: DGEL:WQCZ:NJQ2:Z3OX:2DXN:SNSP:6XHJ:KI2O:FKW6:ZZ3H:F6C2:HIRJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details:**

**Comment by anfimovoleh** [comment]
The same, this issue is still present with 

Client: Docker Engine - Community

 Version:           20.10.17

 API version:       1.41

 Go version:        go1.17.11

 Git commit:        100c701

 Built:             Mon Jun  6 23:03:17 2022

 OS/Arch:           linux/amd64

 Context:           default

 Experimental:      true



Server: Docker Engine - Community

 Engine:

  Version:          20.10.17

  API version:      1.41 (minimum version 1.12)

  Go version:       go1.17.11
