### ISSUE TITLE
docker --context default compose reports unknown docker command: "compose compose" for 2.0.1 but not 2.0.0

### ISSUE THREAD

**Issue by parity3** [docker/compose#8945]
I'm going to ignore the instructions due to lack of time. Please close this issue immediately if this does not benefit the community. I wasn't able to find this in previous issues which I find very surprising.

After installing 2.0.1 over 2.0.0 (via overwriting ~/.docker/cli-plugins/docker-compose with the release binary), the command: `docker --context default compose` reports the usage / help text but the bottom says:

> unknown docker command: "compose compose"

Ubuntu 20.10 x86_64 5.8.0-63-generic virtualbox-from-windows10
Server version 20.10.8
runc version: v1.0.1-0-g4144b63
Experimental: true

This "unknown docker command" happens for every docker compose command that passes in `--context default`. It does not happen if I leave out that switch.

If it's user error, the error message needs to speak more truth than accusing me of typing compose twice.

**Comment by ndeloof** [comment]
Right, the issue is with [standalone command detection](https://github.com/ndeloof/compose/blob/c4cfaeb12a30b7e645eca4a66f0ac499ce3a4b82/cmd/compose/compose.go#L218-L220) which doesn't manage flags passed to the root `docker` command :'(

**Comment by larskuhtz** [comment]
Is there any known work around for this issue?

**Comment by W1M0R** [comment]
You could drop the `--context` parameter, and then export the DOCKER_HOST environment variable explicitly.

**Comment by solvaholic** [comment]
> You could drop the `--context` parameter, and then export the DOCKER_HOST environment variable explicitly.

:hat-tip: Thank you @W1M0R :bow:

While this syntax got the error:

```text
% docker --host "$_host" compose --file svc01-stack.yml ps
...
unknown docker command: "compose compose"
```

This syntax succeeded:

```text
% DOCKER_HOST="$_host" docker compose --file svc01-stack.yml ps   
NAME                COMMAND             SERVICE             STATUS              PORTS
svc01-svc01-1       "/init"             svc01               running             
```

**Comment by hacker** [comment]
Actually, setting `DOCKER_CONTEXT` also works.

**Comment by eriktelepovsky** [comment]
facepalm...

**Comment by internalsystemerror** [comment]
Why was this closed? The issue still exists on v2.2.1.

`docker --context remote compose version`

```
Run 'docker compose COMMAND --help' for more information on a command.
unknown docker command: "compose compose"
```

**Comment by parity3** [comment]
Confirmed fixed by OP in 2.2.3 (did not try 2.2.2). Feel free to close.

**Comment by rosmcmahon** [comment]
i'm facing same issue on 2.2.3....

**Comment by rosmcmahon** [comment]
OK, easily fixed in my case with 
`echo "alias docker-compose='docker compose'" >> ~/.bashrc`
i don't understand why though

**Comment by ndeloof** [comment]
@rosmcmahon don't do that. flags you pass to `docker-compose` are not the same you pass to `docker compose` as some target the root command `docker` (like `--context`)

**Comment by rosmcmahon** [comment]
> @rosmcmahon don't do that. flags you pass to `docker-compose` are not the same you pass to `docker compose` as some target the root command `docker` (like `--context`)

Ok... I'm hearing don't do that, but not what to do?

FYI, I don't have docker-compose v1 installed, if that makes a difference.
