### ISSUE TITLE
Including dll files (shared library) when using docker

### ISSUE THREAD

**Issue by zpvhtz** [docker/compose#8949]
Hi, I'm currently stuck at using Docker for creating images with multiple microservices.

There is a microservice, which is also a shared library that provides a .dll file with some helper functions for the others.

This is my project tree
![TestDraw drawio](https://user-images.githubusercontent.com/28100063/142801502-e65653fd-fb41-44d7-a839-5df2b08943dd.png)

I'm standing at Microservice 1, and this microservice has already added the reference to the .dll file in the Utility service folder. However, when I use the command `docker-compose up --build` , it throws the error:
`The type or namespace name 'utility_service' could not be found (are you missing a using directive or an assembly reference?)`

This is my Dockerfile for Microservice 1
```
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["identity-service.API/identity-service.API.csproj", "identity-service.API/"]
RUN dotnet restore "identity-service.API/identity-service.API.csproj"
COPY . .
WORKDIR "/src/identity-service.API"
RUN dotnet build "identity-service.API.csproj" -c Release -o /app/build (Error goes here)

FROM build AS publish
RUN dotnet publish "identity-service.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "identity-service.API.dll"]
```

So, are there any solutions? Thanks in advance.

**Comment by ndeloof** [comment]
Can you build your Dockerfile using plain `docker build` command?
Otherwise this question is not specific to docker-compose, and you should better ask a forum/stackoverflow
