### ISSUE TITLE
What's the difference between `fig up -d` and `fig restart`?

### ISSUE THREAD

**Issue by wernight** [docker/compose#895]
`fig up` should build but I noticed it does some kind of build only in some cases, not sure when. So in practice as said for #734 on has to:

    $ fig build
    $ fig up -d

but why not just run then `fig restart` (which should do a `fig start` and stop if there is any existing). `fig start` is actually lot faster than `fig up -d`.

**Comment by aanand** [comment]
`fig up -d` destroys and recreates containers, picking up configuration changes from `fig.yml`. `fig restart` just restarts the existing containers.

**Comment by wernight** [comment]
I had issues in the end just using `$ fig build && fig restart`, may be `fig build` isn't building the container, only the images.

**Comment by aanand** [comment]
Correct. After a `fig build`, you'll need to `fig up -d` in order to pick up the new image(s).

**Comment by funkyfuture** [comment]
@wernight, can you clarify the documentation and close this issue?! ;-)

**Comment by wernight** [comment]
@funkyfuture I'd be the wrong person to clarify the documentation as I'm still not sure what `fig start` does or more exactly, when to use `fig start` instead of `fig up -d`. I found `fig start` to give more issues as it doesn't seem to always pick up the correct image.

**Comment by aanand** [comment]
From the [documentation](http://docs.docker.com/compose/cli/#start):

> **start**
> Starts existing containers for a service.
> ...
> **up**
> Builds, (re)creates, starts, and attaches to containers for a service.

Does anything about this need clarifying?

**Comment by aanand** [comment]
Maybe we should say explicitly that `start`, `stop`, `kill`, `restart` and `rm` are analogous to their Docker counterparts.

**Comment by wernight** [comment]
That later comment sounds actually good. This way it's explicit that it allows access to them but they should be hidden from the common help as I think **up** is really the one people would want to use.

**Comment by schmunk42** [comment]
I think many people (including me) usually use `up` which takes a lot more time than `start`.
During development and with host volumes, start looks like the quicker solution.

But it would be cool if `start` could just detect changes and say:

```
Note: Changes to your services detected, please run docker-compose up to apply these changes.
```
Or something similar.

**Comment by wernight** [comment]
'start' is faster than 'up' but it often misses changes, which means you
end up testing something that isn't the code you're editing. That is why I
always use 'up' during development or production.
