### ISSUE TITLE
Allow specifying an interface when using network_mode: host

### ISSUE THREAD

**Issue by glennpierce** [docker/compose#8957]
When running a a nodered container I have to set

network_mode: host

This is to allow ssdp packets to route correctly and so get device discovery to work.
When using network_mode: host the nodered container will try and open port 80 on ALL interfaces.

The trouble is
I have two ip addresses on my server (I have a network ip alias)

Port 80 is free on the first but taken on the second
It would be nice if docker could be set to only apply **network_mode: host** to a specified ip address only
at the moment it tries to use it on 0.0.0.0 and so fails as port 80 is taken by my second ip.

**Comment by thaJeztah** [comment]
When running in "host" network mode, the container's process runs in the host network namespace (so the container doesn't have a dedicated IP address / namespace). This would be the equivalent to running the container's process directly on the host (from a networking perspective). So, it depends on the container process to decide what it will be listening on (if it listens on `0.0.0.0` it will listen on all IP addresses).

Not sure if docker can do anything in that respect

**Comment by glennpierce** [comment]
Ah thanks I didn't realise that. I will look modifying nodered. Thanks
