### ISSUE TITLE
New Docker Compose error in AWS

### ISSUE THREAD

**Issue by TrentonAdams** [docker/compose#8963]
**New Docker Compose error in AWS**

```
docker compose -f docker-db-compose.yml \
                -f docker-compose.yml logs
1 error occurred:
	* option "logs --tail" on context type ECS.: unsupported flag
```

Sometimes I don't get the error above, `docker compose logs` simply hangs.

This also was not happening yesterday...
```
docker compose -f docker-compose.yml -f docker-db-compose.yml down
 ⠿ sysint-mediawiki2  Warning: No resource found to remove
```

It seems docker compose no longer works with AWS ECS.  I'm guessing AWS changed something to completely break things. I can deploy the stack, but logs don't work, and I can't "down" the stack.  I have to go to cloud formation and delete it manually.  This was not happening yesterday.  I reverted to a known working commit for my project, and it's still not working...

**Steps to reproduce the issue:**
1. run `docker compose logs`
2. receive error

**Describe the results you received:**

1 error occurred:
	* option "logs --tail" on context type ECS.: unsupported flag

**Describe the results you expected:**

I expected to see the logs.  yesterday I saw logs, today I do not.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version dev
```

**Output of `docker info`:**

I don't understand why this says I'm using Linux, as I am not, I am using a 2020 MacBook Pro 16" intell X86 architecture.

```
$ docker info
Command "info" not available in current context (myecscontext), you can use the "default" context to run this command

$ docker context use default
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.1.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 84
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.938GiB
 Name: docker-desktop
 ID: 57PN:SRML:LHNC:4EGD:ULVK:CUHJ:3I5V:4JCB:DFPI:WUFB:MOEG:4UBM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by ndeloof** [comment]
ECS support is actually implemented by https://github.com/docker/compose-cli, please report related issues to this repository

**Comment by TrentonAdams** [comment]
[New issue filed](https://github.com/docker/compose-cli/issues/2116)

**Comment by glours** [comment]
@ndeloof ping me next time, I should be able to transfer this issue directly 
I know that you're more reactive on triage than me 😅
