### ISSUE TITLE
Docker docs reference command for installing docker-compose fails on Raspbian 32-bit ("armv7" vs "armv7l")

### ISSUE THREAD

**Issue by Paraphraser** [docker/compose#8966]
**Description**

Docker documentation has a reference command for downloading docker-compose on Unix systems.

The reference command relies on an embedded `$(uname -m)`.

On Raspbian systems the reference command succeeds when the 64-bit kernel is running but fails when the 32-bit kernel is running.

**Steps to reproduce the issue:**

1. Starting at:

	* [https://docs.docker.com/compose/install/#install-compose-on-linux-systems](https://docs.docker.com/compose/install/#install-compose-on-linux-systems)

2. The reference command to download docker-compose is:

	```
	$ sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
	```

3.	On Raspbian systems:

	* 32-bit kernel:
	
		```
		$ uname -m
		armv7l
		```

	* 64-bit kernel:
	
		```
		$ uname -m
		aarch64
		```

4. Assuming the current stable release page:

	```
	https://github.com/docker/compose/releases/tag/v2.1.1
	```

	substituting "v2.1.1" for "1.29.2" in the reference command leads to two candidate URLs:

	* 64-bit kernel: `https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-Linux-aarch64`
	* 32-bit kernel: `https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-Linux-armv7l`

5. The first URL resolves but the second URL does not resolve because the releases page uses "armv7" not "armv7l":

	* `https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-linux-armv7`

**Describe the results you received:**

Trying to use the reference command to download on Raspbian:

* Succeeds if the 64-bit kernel is active
* Fails if the 32-bit kernel is active

**Describe the results you expected:**

The reference command should work when `uname -m` returns `armv7l`.

**Additional information you deem important (e.g. issue happens only occasionally):**

I don't pretend to understand architecture nomenclature but, given that `uname -m` produces `armv7l` on Raspbian systems with 32-bit kernels, it seems to me that either:

* the releases page is in error and the existing URLs should be using `armv7l`; or
* there are indeed systems which return `armv7` in which case the releases page probably needs a duplicate URL with the "l" on the end.

Unfortunately, I don't have any "armv6" hardware to test whether there is an equivalent problem in that situation.

**Output of `docker compose version`:**

I don't think this is relevant because the problem is not with docker-compose. It's really a mismatch between the documentation and the image URLs on the releases page.

But, for the record, if I manually "fix" the URL, the download succeeds and running `docker-compose version` produces `Docker Compose version v2.1.1`.

**Output of `docker info`:**

Again, not really relevant because the problem is not about the docker/docker-compose environment.

**Additional environment details:**

Happens on Raspbian Buster and Bullseye if 32-bit kernel is running (which is the default).

I've been running docker-compose 1.29.2 installed via `sudo pip install docker-compose`. I just started to wonder why that method seemed to be stuck at 1.29.2 and wasn't advancing in line with the releases page. That's what led me here.

**Comment by Smithienious** [comment]
This seems to be working

```bash
sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

Maybe the docs is outdated

**Comment by Smithienious** [comment]
Or use `v2.1.1` for the latest stable

**Comment by Smithienious** [comment]
Hello. Apparently docker-compose is now on v2.
Can you check out [this page](https://docs.docker.com/compose/cli-command/#install-on-linux) instead?

**Comment by Smithienious** [comment]
That page is kinda messy, so here is a recap of what you need to do

```bash
mkdir -p ~/.docker/cli-plugins/
curl -SL "https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-$(uname -s)-$(uname -m)" -o ~/.docker/cli-plugins/docker-compose
chmod +x ~/.docker/cli-plugins/docker-compose
```

**Comment by Paraphraser** [comment]
@Smithienious

I'm sorry. I don't think I can have explained it clearly enough.

In the attachment, I have tried to show it graphically:

1. On a Raspbian system running the 32-bit kernel, `uname -m` returns "armv7l"
2. The URLs (either your examples or the one from the Docker documentation) embeds `$(uname -m)` in its construction.
3. I show the expansion with the `echo` statement.
4. Then I use the echoed URL to do the download.
5. The `file` command shows that what was downloaded is a text file.
6. Displaying that text file reports "Not Found".

The same thing happens for both `v2.2.0` and `v2.1.1`.

The Assets page only shows URLs that end in "armv7". It does not have any URLs ending in "armv7l".

"armv7" is not equal to "armv7l". That is why the download is not working.

![raspbian-32bit-kernel](https://user-images.githubusercontent.com/34226495/143574806-57f40b31-e2b8-40a5-a978-dc2af1e8b46a.jpeg)

If I switch to the 64-bit kernel, `uname -m` returns "aarch64". That **is** listed on the Assets page. That works.

It is **only** "armv7l" (the 32-bit kernel) that has this problem.

Does that make sense?

**Comment by lysdexic-audio** [comment]
I just upgraded to 2.1.1 this morning on my pi4 (apt had me on 1.29)

can confirm the armv7 build does work on the pi4 (armv7l)

`~/.docker/cli-plugins/` isn't on PATH by default for me either - here's what I put in a script to get docker-compose installed

```bash
$ wget https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-linux-armv7
$ sudo mv docker-compose-linux-armv7 /usr/local/bin/docker-compose
$ docker-compose version #should equal 2.1.1
```

**Comment by lysdexic-audio** [comment]
`apt-cache policy docker-compose` yields this too - seems to be stuck at 1.21

```
docker-compose:
  Installed: (none)
  Candidate: 1.21.0-3
  Version table:
     1.21.0-3 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
```
