### ISSUE TITLE
Different absolute paths for Dockerfile and Context in docker-compose.yml

### ISSUE THREAD

**Issue by Olshansk** [docker/compose#8971]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

With docker version `20.10.8`, specifying absolute paths to a `context` and `Dockerfile` that are in two completely different locations works as expected. In docker version `20.10.10`, the `Dockerfile` is always treated as a relative path to `context` even if the path is absolute.

**Steps to reproduce the issue:**
1. `tar -xzvf dockerbug.tar.gz ./dockerbug`; [dockerbug.tar.gz](https://github.com/docker/compose/files/7611994/dockerbug.tar.gz)
2. cd dockerbug
3. docker-compose -f compose/docker-compose.yml up --build --force-recreate

**Describe the results you received:**

> could not find /Users/olshansky/workspace/dockerbug/context/Users/olshansky/workspace/dockerbug/dockerfile: stat /Users/olshansky/workspace/dockerbug/context/Users/olshansky/workspace/dockerbug/dockerfile: no such file or directory

**Describe the results you expected:** Container starts up successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

I understand that there could be a security concern for disallowing a Dockerfile to be outside of the context, but I could not find any references to this bug-fix/feature-change in the recent [release notes:](https://github.com/moby/moby/compare/v20.10.8...v20.10.10) and am therefore not sure what the intended behaviour is.

**Output of `docker compose version`:**

```
Docker Compose version v2.1.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: true
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.1.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 36
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: wuhqgyizxi9v4mz15jxa32364
  Is Manager: true
  ClusterID: w8ipmuyhbsvujbw5ki25s1dna
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.939GiB
 Name: docker-desktop
 ID: OI4X:V3HV:P2VF:EK4E:NZGM:OEL2:3BPZ:AKHA:QIUR:2YYF:NDTZ:KPIL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:** macOS Monterey.

**Comment by glours** [comment]
Hello @Olshansk 

Can you try the pre-release [`v2.2.0`](https://github.com/docker/compose/releases/tag/v2.2.0) and check if this version fix your issue?
It seems to be fixed by #8929

**Comment by derrandz** [comment]
@glours The prerelease seems to do it 👍🏻

**Comment by Olshansk** [comment]
Confirmed that `docker-compose-darwin-x86_64` resolves the repro steps I outlined in this bug.

@glours
1. Should we close this out now or once `v2.2.0` is officially released?
2. I personally think it's worth documenting somewhere that versions `2.10.9` & `2.10.10` suffer from this bug.
