### ISSUE TITLE
exec returns exit code 0 instead of exit code of command

### ISSUE THREAD

**Issue by drewgingerich** [docker/compose#8982]
**Description**

The go-based `docker compose exec $command` does not appear to return exit code of the command, instead it returns `0`. Using the Python-based `docker-compose exec $command` does return the exit code of the command.

**Steps to reproduce the issue:**
1. Download Gist at https://gist.github.com/drewgingerich/0bee6e870715111562074656ec7b1dba
2. Execute `run.sh`

**Describe the results you received:**

`docker compose exec $command` returns `0` even if the command fails.

**Describe the results you expected:**

`docker compose exec $command` should return the exit code of the command.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 171
  Running: 4
  Paused: 0
  Stopped: 167
 Images: 274
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.941GiB
 Name: docker-desktop
 ID: Q2NG:YPEO:YRUU:CQZ7:SYO3:IR6E:JW4H:HYFG:QJXF:67CU:DN4G:RKNF
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 75
  Goroutines: 72
  System Time: 2021-11-30T20:19:07.2669361Z
  EventsListeners: 3
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by laurazard** [comment]
Hi @drewgingerich, thanks for the report. I'm having trouble replicating this, it exits with the correct exit code for me (on version `2.6.1`).

Are you still experiencing this issue?

**Comment by DesignByOnyx** [comment]
I came here because I thought I was experiencing the same issue. I wanted to post some helpful commands to show that exec indeed exits with the code of the command:

```bash
# you can pass `-d` run in detached mode if you like
docker run --rm -it --name alpine alpine
```

In another terminal run the following and observe that the 'Error' text only logs when the `exec` command exits with non-zero:

```bash
# This should not log the "Error" text
docker exec alpine pwd || echo "Error"

# This should log "Error" - indicating that the exec process failed
docker exec alpine sh -c "exit 1" || echo "Error"
```
