### ISSUE TITLE
docker compose - unknown shorthand flag: f

### ISSUE THREAD

**Issue by tangopium** [docker/compose#8986]
* [x] This is a bug report
* [ ] This is a feature request
* [ ] I searched existing issues before opening this one

### Expected behavior

`docker compose -f docker-compose.dev.yml build` should build a project using docker-compose.dev.yml

### Actual behavior

I get the error "unknown shorthand flag: 'f' in -f"

### Steps to reproduce the behavior

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:35:56 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:34:31 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-90-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 1
 Total Memory: 974.8MiB
 Name: primary
 ID: HLIN:2GYA:RRNJ:LLP7:3FFW:CUF3:LBTA:N2SX:KSST:U3EX:3NHL:TG46
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**

Docker is running on MacOS Monterrey in a Virtual Maschine (Ubuntu 20.10, Canonical Multipass)

**Comment by glours** [comment]
@michaelpeterlee @tangopium 
Can you share the result of `docker compose version`

**Comment by Murbal** [comment]
I also have the same problem with docker compose version 2.2.2 and the following docker version
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
I also tried to upgrade the client and server to v20 but it did not resolve the problem

**Comment by eichelkrauta** [comment]
if it helps anyone else, I thought that I had run into this issue with the following command
```
docker compose up -f some/docker-compose.yml -d
```

however, after moving the `up` to the end:
```
docker compose -f some/docker-compose.yml up -d
```
it started working correctly. 

just in case anyone else thinks they may have run into the same problem

**Comment by DrEsteban** [comment]
@eichelkrauta has the right answer. I can _kinda_ understand why it works (due to how the argument parser is currently written), but it's ultimately a poor user experience. The argument parsing code should be updated to be more flexible on positioning.

**Comment by ndeloof** [comment]
@DrEsteban `-f` is unfortunately also used by some subcommand as shorthand for `--format`, so allowing use after command would create some more issues.

**Comment by cjones27** [comment]
Have the same problem. I suppose it is not fixed yet. Docker seems not to understand when you are running docker commands vs docker compose commands when using the -f flag **and sudo** in Ubuntu. Some examples.

If I run `docker compose -f some/docker-compose.yml up -d` as suggested, I get a permission denied error. If I use sudo, docker thinks it's a docker command, not a docker compose command.

Commands runned
**Option 1**
`sudo docker compose up -f docker-compose.dev.yml`
Result 1
```unknown shorthand flag: 'f' in -f
See 'docker --help'.
Usage:  docker [OPTIONS] COMMAND
A self-sufficient runtime for containers
Run 'docker COMMAND --help' for more information on a command.
```

**Option 2**
`sudo docker compose -f docker-compose.dev.yml up`
Result 2
```unknown shorthand flag: 'f' in -f
See 'docker --help'.
Usage:  docker [OPTIONS] COMMAND
A self-sufficient runtime for containers
Run 'docker COMMAND --help' for more information on a command.
```
If anyone has a solution it would be very welcomed, otherwise I will have to switch to v1. Thanks!

**Comment by daveteu** [comment]
> if it helps anyone else, I thought that I had run into this issue with the following command
> 
> ```
> docker compose up -f some/docker-compose.yml -d
> ```
> 
> however, after moving the `up` to the end:
> 
> ```
> docker compose -f some/docker-compose.yml up -d
> ```
> 
> it started working correctly.
> 
> just in case anyone else thinks they may have run into the same problem

This is the correct answer.  Do note the "--file" / "-f" flag is shown in `docker-compose --help`, and not `docker-compose up --help`, so it has to be before the **up**.

**Comment by MMendozaEscalona** [comment]
It worked for me docker-compose (with - in the middle)

**Comment by MMendozaEscalona** [comment]
I'm using 3.7 version of docker compose

**Comment by glours** [comment]
@MMendozaEscalona version `3.7` is the file format version not the Compose version, we should use `docker compose version` or `docker-compose version` to get the binary version.

**Comment by MMendozaEscalona** [comment]
Oh sorry, this is my output 
![Screenshot_20220913_115912](https://user-images.githubusercontent.com/91369054/189872688-48241702-7449-4e8b-9eb7-112a4675619a.png)

**Comment by digitaltim-de** [comment]
Same issue, not working for me.

**Comment by glours** [comment]
@MMendozaEscalona so you're using a old version of Compose v1 (in python), and Compose v1 is end-of-life, please install the Compose v2, if you're on [linux follow this steps](https://docs.docker.com/compose/install/linux/) and if you're using Docker Desktop verify you didn't uncheck the `Use Docker Compose V2` checkbox in Preferences view 
Maybe that the same for you @digitaltim-de?

**Comment by sethkimmel3** [comment]
Not sure if this will be helpful for anyone, but I ran across this issue when setting a cron executing `docker compose` commands. 

My issue was that I had installed docker compose with a specific user, so running `docker compose` from the cron shell script (which default was using the root user) was interpreting it as the `docker` command itself (which doesn't have an `-f` flag).

To correct this, I added `sudo -u <user>` in front of the `docker compose ...`, which ran the command from the user which had installed it.

**Comment by augi** [comment]
Just for the record - while in V1 the `-f` was just one of the options, it must be the first option in V2: https://docs.docker.com/engine/reference/commandline/compose/

So e.g. `docker compose --ansi never -f a_file.yml up` produces the mentioned error message.

**Comment by ameotoko** [comment]
> My issue was that I had installed docker compose with a specific user, so running `docker compose` from the cron shell script (which default was using the root user) was interpreting it as the `docker` command itself (which doesn't have an `-f` flag).

This was exactly the issue for me, I got this error trying to set up a systemd service like this:

```
ExecStart=/bin/bash -c "docker compose -f /home/ec2-user/docker-compose.prod.yml up -d"
```

With the mentioned hint everything worked when I added user:

```
User=ec2-user
ExecStart=/bin/bash -c "docker compose -f /home/ec2-user/docker-compose.prod.yml up -d"
```

**Comment by thaJeztah** [comment]
> > My issue was that I had installed docker compose with a specific user, so running `docker compose` from the cron shell script (which default was using the root user) was interpreting it as the `docker` command itself (which doesn't have an `-f` flag).
> 
> This was exactly the issue for me, I got this error trying to set up a systemd service like this:


Looking at that scenario, effectively in that case, the compose CLI plugin is not found (and the CLI considers it to not exist). That may be related to;

- https://github.com/docker/cli/issues/4550
- https://github.com/docker/cli/issues/3833

And _perhaps_ (🤞) fixing that issue  would also "fix" that (at least, produce a more sensible error)

**Comment by ndeloof** [comment]
As a workaround you should install Docker Compose as a shared CLI plugin under `/usr/lib/docker/cli-plugins`

**Comment by spencercornish-wk** [comment]
I think I may have found the root cause of this problem, at least on Mac hosts, but it may extend to other systems. Essentially, it's a missing symlink on the Docker Desktop for mac install.

Here's a workaround that does not require the installation of the legacy `docker-compose` executable: https://github.com/docker/for-mac/issues/6876#issuecomment-1808845767

**Comment by fwilliamconceicao** [comment]
> if it helps anyone else, I thought that I had run into this issue with the following command
> 
> ```
> docker compose up -f some/docker-compose.yml -d
> ```
> 
> however, after moving the `up` to the end:
> 
> ```
> docker compose -f some/docker-compose.yml up -d
> ```
> 
> it started working correctly.
> 
> just in case anyone else thinks they may have run into the same problem

This is the actually right answer, worked like a charm.

**Comment by MSoliven** [comment]
If typing "docker compose" returns "'compose' is not a docker command", then try this:

curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

Source:
https://serverfault.com/questions/1067566/docker-compose-is-not-a-docker-command-how-to-use-the-alias-docker-compos

**Comment by spitfire** [comment]
> > if it helps anyone else, I thought that I had run into this issue with the following command
> > ```
> > docker compose up -f some/docker-compose.yml -d
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > however, after moving the `up` to the end:
> > ```
> > docker compose -f some/docker-compose.yml up -d
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it started working correctly.
> > just in case anyone else thinks they may have run into the same problem
> 
> This is the actually right answer, worked like a charm.

This worked for me too, thanks. The right answer is that it should be fixed - this is the first time I've seen the order of arguments has to be specific, and there's no reason it should work like that.

**Comment by meonkeys** [comment]
I was having this issue on Ubuntu 22.04. The fix was to switch to Docker Compose v2:

```bash
sudo apt autoremove --purge docker-compose
sudo apt install docker-compose-v2
```
