### ISSUE TITLE
docker-compose 2.2.2 changes version semantics (using "2.2.2" instead of "v2.2.2"

### ISSUE THREAD

**Issue by rfay** [docker/compose#8991]
**Description**

In docker-compose version 2.2.2 you changed the release versioning from "v2.x.x", which has always been used so far, to "2.x.x". 

**Steps to reproduce the issue:**

View the release page, the release is listed as "2.2.2", all previous 2.x docker-compose releases were "v2.x.x"
`docker-compose --version` gets 2.2.2, all previous 2.x.x releases were 'v2.x.x'

Please use a consistent technique. I was just about to run a full set of ddev tests, but this breaks ddev's logic to figure out the URL to download docker-compose.

**Comment by glours** [comment]
A new release is in progress following the previous pattern

**Comment by rfay** [comment]
Thanks for fixing.
