### ISSUE TITLE
Numeric UID/GID of docker secrets requires string 

### ISSUE THREAD

**Issue by DevDavido** [docker/compose#8993]
When setting the `uid`/`gid` of a docker secret which is [mentioned to be numeric](https://docs.docker.com/compose/compose-file/compose-file-v3/#:~:text=uid%20and%20gid%3A-,The%20numeric%20UID%20or%20GID,-that%20owns%20the%20file) docker compose aborts the start with an error of `services.xxx.secrets.0.uid must be a string`.

**Steps to reproduce the issue:**
1. Set `uid`/`gid` of docker compose service secret to numeric value
2. Start docker compose project

**Describe the results you received:**
Docker Compose aborts with `services.xxx.secrets.0.uid must be a string`.

**Describe the results you expected:**
Docker Compose reads the numeric value without aborting startup or documentation text should be changed.

**Output of `docker compose version`:**

```
Docker Compose version v2.2.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Server Version: 20.10.11
[...]
```

**Comment by ndeloof** [comment]
the doc indeed says "The numeric UID or GID" but the example a few lines latter make it clear a string is expected.

I guess we could relay this to accept "int or string", to be discussed on https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax
