### ISSUE TITLE
[Feature Request] "convert --images" list only built images

### ISSUE THREAD

**Issue by abdennour** [docker/compose#8994]
**Description**

`docker compose convert --images` list all images.
This feature request is about listing only built images not all of them

**Proposal**

- **Option 1**
  - Overview
  Adding another flag for the subcommand convert called "--built-images"
  - Sample(s)
 `docker compose convert --built-images`
  - Advantages over other options
      Dedicated flag for a unique purpose

- **Option 2**
  - Overview
   Adding another flag for the subcommand convert called "--only-built" to be used alongside with the current flag "--images"
  - Sample(s)
 `docker compose convert --images --only-built`
  - Advantages over other options
      the new flag "--only-built" becomes as filter for any convert subcommand ( not only images)

Please let me know which one do you prefer and i can open PR for that

**Comment by abdennour** [comment]
Please let me know which one do you prefer and i can open PR
@mat007  @glours @ndeloof   PFYI

**Comment by ndeloof** [comment]
My preference goes to 
1. introduce actual subcommand `compose config images`
2. have this new subcommand declare its own flags. In terms of UX I'd prefer a simpler `--built` but that's to be debated
3. deprecate `--images` and redirect to this new subcommand
4. (do the same for other pseudo-commands in the `config` command for UX homogeneity

**Comment by abdennour** [comment]
I like it! 
As you mentioned for `--built`, it should be debated. indeed, what if i want to render the opposite : ready/pulled images only.
@ndeloof  So that option should cover:
- all images (binary opt value: 11)
- only built images (binary opt value : 01)
- only ready images (binary opt value: 10) ( all images - only built images)

**Comment by abdennour** [comment]
can we go **agile** : releasing `config --built-images` , then think about refactoring/re-organizing? @ndeloof

**Comment by abdennour** [comment]
@ndeloof  i am still thinking with you.
This is another design:
- `BUILT_SERVICES=docker compose config --built-services` ( new option here to be released)
- then: `docker compose config --images $BUILT_SERVICES` ( no change here )

**Comment by abdennour** [comment]
Reminder @ndeloof  !

**Comment by abdennour** [comment]
I just realized that you already use the terminology `imagesToBuild`
https://github.com/docker/compose/blob/381df200105f902db9d9e7f109c19bbed58302cd/pkg/compose/build.go#L51

I will rename `--built-images` to `--images-to-build` , and after that, i think it's acceptable and the related PR #8995 can be merged

@ndeloof  @glours FYI

**Comment by abdennour** [comment]
@glours  Kindly reminder
@ndeloof
