### ISSUE TITLE
Using force-recreate with profiles also recreates containers with no profiles

### ISSUE THREAD

**Issue by MandySimbuka** [docker/compose#9002]
**Description**

Using `--force-recreate` with **profiles** also recreates containers with no profiles.

**Steps to reproduce the issue:**
1.
Create `docker-compose.yml` file
```yml
services:

  nginx1:
    image: nginx


  nginx2:
    image: nginx
    profiles:
      - nginx2
```

2. Run `docker-compose up -d --force-recreate` -> This only (re)creates the nginx1 service
3. Run `docker-compose --profile nginx2 up -d --force-recreate` -> This recreates all services including `nginx1` which has no profile

**Describe the results you received:**
Running `docker-compose --profile nginx2 up -d --force-recreate`  recreates `nginx1` and `nginx2`

**Describe the results you expected:**
Running `docker-compose --profile nginx2 up -d --force-recreate`  should recreate only `nginx2`, since I specifically requested to recreate all services for profile `nginx2`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: none
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: gitpod io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: gitpod
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
 Kernel Version: 5.13.0-1007-gcp
 Operating System: Ubuntu 20.04.2 LTS (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.8GiB
 Name: ws-98b5f9ba-fbb3-4be0-a06f-766e5eac574b
 ID: JLE3:ZZ4I:77VQ:ZU2T:IUXG:NPET:4YJV:43IV:ZRNJ:VWZU:6ZM5:TWQQ
 Docker Root Dir: /workspace/.docker-root
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
```

**Additional environment details:**

I used gitpod to create a test environment: https://gitpod.io/#https://github.com/docker/compose

**Comment by laurazard** [comment]
Hi @MandySimbuka, thanks for the report.

The behavior you're reporting seems correct -- looking at the profiles [documentation here](https://docs.docker.com/compose/profiles/), specifically this example:

```
version: "3.9"
services:
  frontend:
    image: frontend
    profiles: ["frontend"]
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    profiles:
      - debug
  backend:
    image: backend
  db:
    image: mysql
```

it is mentioned that running a command such as `compose --profile debug up` would:

> Using the docker-compose.yml file above, this would start the services `backend`, `db` and `phpmyadmin`.

If you'll note, that also includes the `backend` service, which has no profile.
