### ISSUE TITLE
docker-compose output doesn't clear the screen if the output is larger than the screen

### ISSUE THREAD

**Issue by BLucky-gh** [docker/compose#9008]
**Description**
In `wt` if the `docker-compose up` output is more than the screen can fit, it spams every "frame" of text instead of clearing the text and writing the next "frame" to stdout

**Steps to reproduce the issue:**
1. Follow the instructions in [this repo](https://github.com/maheshyaddanapudi/ansible-playbook-generator-ui)
2. Make sure to use the [instructions for prebuilt images](https://github.com/maheshyaddanapudi/ansible-playbook-generator-ui)

**Describe the results you received:**
At my default font size the output of the commmand is larger than my windows terminal window, so every "frame" of the progress bars is being appended to stdout instead of redrawing the progress bars.
If i decrease te font size everything is back to normal and the progress bars are redrawn without spamming in my scrollback buffer

**Describe the results you expected:**
I expected normal redrawing of progress bars and the rest of the output

**Additional information you deem important (e.g. issue happens only occasionally):**
Running on WSL2, [ArchWSL](https://github.com/yuk7/ArchWSL) with the docker desktop app isntalled on windows and the wsl backend enabled (I'm still using the cli within the wsl distro and not the desktop app`

**Output of `docker compose version`:**

```
Docker Compose version v2.2.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 6.105GiB
 Name: docker-desktop
 ID: P3ZF:FQ4Z:ZM67:NPIO:ABMC:HWQH:SVRP:SO4O:F35C:T5NI:XFOJ:WZNB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**

**Comment by ericslandry** [comment]
Dup of #8800 ?

**Comment by BLucky-gh** [comment]
It does look like it, but I can't tell if it's the same reason for cli spam. Should I close the issue or leave it as is until #8800 is fixed and see if this gets fixed too?

**Comment by thaJeztah** [comment]
Thanks for reporting! While it's perhaps not _exactly_ the same as https://github.com/docker/compose/issues/8800, I think it's very closely related. I also just posted some comments on https://github.com/docker/compose/issues/8800 to discuss some options / ideas.

Let me close this ticket to prevent the discussion from diverging / taking place in two separate tickets; feel free to commend / participate on that ticket if you have additional input / ideas 👍
