### ISSUE TITLE
Environment variable default in .env does not work

### ISSUE THREAD

**Issue by jonananas** [docker/compose#9010]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
A `.env` with
`VARIABLE=${VARIABL:-default}`
should end up with VARIABLE = `default` when doing `docker compose config` or `docker compose up`

```bash
➜ docker compose config
services:
  default:
    command:
    - echo
    - default
    environment:
      VARIABLE: default
    image: ubuntu:20.04
```

### Actual behavior

VARIABLE =  `:-default}`

```bash
➜ docker compose config
services:
  default:
    command:
    - echo
    - :-default}
    environment:
      VARIABLE: :-default}
    image: ubuntu:20.04
```

### Information

As specified in <https://docs.docker.com/compose/environment-variables/> :
<pre>
"it is possible to provide inline default values using typical shell syntax:
${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment."
</pre>

  - macOS Version: Big Sur
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: 4.3.0 (71786)

### Steps to reproduce the behavior

Using these files:

.env:
```
VARIABLE=${VARIABL:-default}
```

docker-compose.yml:
```
version: "3.7"

services:
  default:
    image: ubuntu:20.04
    environment:
      - VARIABLE
    command: [
      "echo", "$VARIABLE"
    ]
```

Compare docker-compose config with docker-compose-v1 config:

```bash
➜ docker-compose-v1 config
services:
  default:
    command:
    - echo
    - default
    environment:
      VARIABLE: default
    image: ubuntu:20.04
version: '3.7'

➜ docker compose config
services:
  default:
    command:
    - echo
    - :-default}
    environment:
      VARIABLE: :-default}
    image: ubuntu:20.04
```

Additionally, if using .env:
```
VARIABLE=${VARIABLE:-default}
```

Then VARIABLE will evaluate to `null`

**Comment by bkuhl** [comment]
This looks like a duplicate of https://github.com/docker/compose/issues/8799

**Comment by jonananas** [comment]
With your addition https://github.com/docker/compose/issues/8799#issuecomment-963323796, I agree.
