### ISSUE TITLE
4.2.0 changes how default names treat `.` in the root directory name

### ISSUE THREAD

**Issue by olets** [docker/compose#9011]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 01CD8A4C-01E1-458E-912A-05926C03A580/20211206201331

### Expected behavior

The minor upgrade from 4.1.x to 4.2.0 is non-breaking.

### Actual behavior

4.1.x: when determining container name, volume names, and image names, `.` and anything after it was trimmed

4.2.0 and 4.3.0: when determining container name, volume names, and image names, `.` is spliced out

```shell
# 4.1.x
cd something.com
docker-compose build && docker-compose up # no custom name specified
# container created is called 'something'

# 4.2.0
cd something.com
docker-compose build && docker-compose up # no custom name specified
# container created is called 'somethingcom'
```

For projects that were already built at the time of the upgrade, the result is errors:

```
# 4.1.x
cd something.com
docker-compose build && docker-compose up # no custom name specified
# container created is called 'something'
docker-compose down
# upgrade Docker Desktop
docker-compose up # errors because there is no container 'somethingcom'

# start container via Docker Desktop UI. that works as expected, but
docker-compose exec … # errors because there is no container 'somethingcom'
```

### Information

  - macOS Version: 11.6.1 (20G224)
  - Intel chip or Apple chip: Apple
  - Docker Desktop Version: 4.3.0, first appeared in 4.2.0

### Steps to reproduce the behavior

  1. Set up a Docker project (I use docker-compose.yml, in case that's relevant). Name the host root directory something with a `.`
  2. Build and up the app in 4.1.x
  3. Build and up the app in 4.2.0
  4. See that you have two sets of containers, volumes, and images with different names, where the difference is how the `.` was treated

**Comment by olets** [comment]
Bump

**Comment by laurazard** [comment]
This is expected, and was implemented in https://github.com/compose-spec/compose-go/pull/197 to fix https://github.com/docker/compose/issues/8881.
