### ISSUE TITLE
compose ps error typo "unknow filter"

### ISSUE THREAD

**Issue by webignition** [docker/compose#9016]
**Description**

[`/cmd/compose/ps.go#L62`](https://github.com/docker/compose/blob/435387c72c1208ae95b9cd62e3782098ec07d8b4/cmd/compose/ps.go#L62) appears, at the time of writing, to have a typo in an error message:

```go
return fmt.Errorf("unknow filter %s", parts[0])
```

Should this be "**unknown filter**" not "**unknow filter**"?

**Steps to reproduce the issue:**
1. Browse to https://github.com/docker/compose/blob/435387c72c1208ae95b9cd62e3782098ec07d8b4/cmd/compose/ps.go#L62
2. Observe visually the apparent spelling mistake

**Comment by ndeloof** [comment]
Seems a good opportunity for your first contribution :)
I can't wait for your Pull-request

**Comment by webignition** [comment]
@ndeloof one step ahead of you there! PR is #9017
