### ISSUE TITLE
v2 `docker-compose logs -p` not working with names with uppercase letters

### ISSUE THREAD

**Issue by xtaixe** [docker/compose#9022]
**Description**

On v2 `docker-compose logs -p` is not working with names that contain uppercase letters, which is at least different behavior from other commands. Using all lowercase makes the command work (even if the `up` command used the uppercase version).

**Steps to reproduce the issue:**
1. `docker-compose -p AAA up --no-start` (works, creates networks and containers)
2. `docker-compose -p AAA start` (works, starts containers)
3. `docker-compose -p AAA logs` (does not work, nothing shown)
4. `docker-compose -p aaa logs` (works, logs shown)

**Describe the results you received:**

No logs shown

**Describe the results you expected:**

Logs shown

**Output of `docker compose version`:**

```
Docker Compose version v2.2.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 2
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.939GiB
 Name: docker-desktop
 ID: 47CE:XHEG:OZ42:LUEP:2DY6:KVGE:43ME:DWEK:M6XG:RUOX:URP3:BICH
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 54
  Goroutines: 54
  System Time: 2021-12-10T11:46:53.590779862Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
`macOs big Sur 11.6.1`

**Comment by Flame239** [comment]
I'm observing similar behaviour on Docker Compose version v2.2.3 and also on `ps` command. 
Altohugh `down` command works with uppercase project name because of this: https://github.com/docker/compose-cli/issues/2023

**Comment by laurazard** [comment]
I'm closing this issue since it's no longer a problem due to project names with all caps no longer being accepted.

**Comment by xtaixe** [comment]
@laurazard this is not just a problem with _all caps_, but with any uppercase letters in the name... It might be fixed anyway, but it would be good to know in which release to test or maybe document what are the restrictions for project names. Or at least make sure that all commands behave consistently, is that the case now?
