### ISSUE TITLE
strange images

### ISSUE THREAD

**Issue by pvklink** [docker/compose#9028]
i got strange extra containers / images when execute a docker-compose up command

**Description**

i got strange extra containers / images when execute a docker-compuse up command

**Steps to reproduce the issue:**
1. execute a docker-compose UP command with  a random  basic yml file
2.
3.

**Describe the results you received:**
I got these extra images/containers 
quizzical_roentgen            Exited (0) 
condescending_chatelet   Created    
blissful_aryabhata       Exited (0) 
nostalgic_swirles        Exited (0) 
ecstatic_brattain        Created     
relaxed_kare             Exited (0) 
jovial_euler             Created       
practical_goldstine      Exited (0)
strange_blackburn        Created 
vigorous_panini          Exited (0) 
pensive_visvesvaraya     Exited (0) 
cranky_rhodes            Exited (0) 
brave_galois             Exited (0) 
admiring_chaplygin       Exited (0) 
strange_bassi            Created   

**Describe the results you expected:**
Only images and containers that i specify in my compose.yml

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
2.2.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 26
  Running: 11
  Paused: 0
  Stopped: 15
 Images: 31
 Server Version: 20.10.5+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.4.5~ds1-2+deb11u1
 runc version: 1.0.0~rc93+ds1-5
 init version:
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.63-v7l+
 Operating System: Raspbian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.748GiB
 Name: rpitest
 ID: INZD:Q7AE:CACC:5SVV:VPJ7:AXJW:BFKJ:7W6A:IRB6:FEIL:KTKP:O5TT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  dockerhub:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: Support for cgroup v2 is experimental

```

**Additional environment details:**

**Comment by ndeloof** [comment]
please provide a concrete compose.yml file to reproduce this issue.

**Comment by pvklink** [comment]
is solved on another forum. Takes places on any image/container/service.
Seems to be a solution for when no name is given...

**Comment by eva-mueller-coremedia** [comment]
The random name generator has been added [2013](https://github.com/moby/moby/pull/2425) ([names-generator.go](https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go)) to Docker:

> Create an auto generated container name if not specified at runtime.

But indeed, it's strange. I am interested as well.
* How does your compose yml look like? 
* Did you specify a `container_name` for your service?
* How many containers are generated when calling `docker-compose up -d`. (I assume that there are no left overs before you start `docker-compose up -d`, i.e. `docker ps -a` shows nothings)

It would be great if you paste the link to the other forum where the question has been solved? Thanks.

**Comment by pvklink** [comment]
Hi Eva, Thanks for your comment!
The existance of those dockers explained, but now, why do i have so many?

Here are my .env file and my docker-compose.yml.
I made a lot of software to adjust this yml en env’s automaticcaly, thats why i use so many variables.
Some services also use dockerfiles to who i pass variables
And watchtower also need image names which in my case are defined in the .env-file and passed to the yml and dockerfiles

In my previous version of my software i made several projectfolders with a compose file and env. With docker-compose 1.25
Then i saw the specs of docker-compose > 1.28 (i use 2/2/0) and that you can have one yml-file and use profiles!
So i downloaded 2.2.0 and changed my setup to one yml with profiles and a .env var that is filled/changed by my software…

Peter v Klink


Van: Eva Müller
Verzonden: maandag 13 december 2021 22:57
Aan: docker/compose
CC: pvklink; Author
Onderwerp: Re: [docker/compose] strange images (Issue #9028)

The random name generator has been added 2013 (names-generator.go) to Docker:
Create an auto generated container name if not specified at runtime.
But indeed, it's strange. I am interested as well.
• How does your compose yml look like?
• Did you specify a container_name for your service?
• How many containers are generated when calling docker-compose up -d. (I assume that there are no left overs before you start docker-compose up -d, i.e. docker ps -a shows nothings)
It would be great if you paste the link to the other forum where the question has been solved? Thanks.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by eva-mueller-coremedia** [comment]
> Here are my .env file and my docker-compose.yml.

Unfortunately, there are no attachments....

**Comment by pvklink** [comment]
Shame on me, and now?

Verzonden vanuit Mail voor Windows

Van: Eva Müller
Verzonden: dinsdag 14 december 2021 11:39
Aan: docker/compose
CC: pvklink; Author
Onderwerp: Re: [docker/compose] strange images (Issue #9028)

Here are my .env file and my docker-compose.yml.
Unfortunately, there are no attachments....
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
