### ISSUE TITLE
Don't report proxy errors as connection errors

### ISSUE THREAD

**Issue by Stono** [docker/compose#903]
Hi,
This caused me much, much pain.
I'm using docker-compose with TLS enabled, however under the hood the tls library was using the environmental variables for proxy (which is fine) and I didn't have a no_proxy exemption for this host.

However the error you get back from docker doesn't make it clear:

```
$ docker-compose ps
Couldn't connect to Docker daemon at https://localhost:2376 - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

So I spent hours trying to work out what's going on, before delving into the .py files and adding some "prints", to give me:

```
$ docker-compose ps
HTTPSConnectionPool(host='localhost', port=2376): Max retries exceeded with url: /v1.14/containers/json?all=1&limit=-1&trunc_cmd=1&size=0 (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 503 Service Unavailable',)))
Couldn't connect to Docker daemon at https://localhost:2376 - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

Therefore can I suggest that you output the HTTP Status code and a truncated message with this error?

**Comment by dnephin** [comment]
I think that would be a good change, it should report that the connection was made, but there was some error, instead of acting like it couldn't connect at all

**Comment by reekoheek** [comment]
Got the same error with docker-compose. But using docker everything is ok (the error only apply if I use docker-compose)

```
$ docker -v
Docker version 1.8.3, build f4bf5c7

$ docker-machine -v
docker-machine version 0.4.1 (e2c88d6)

$ env | grep DOCKER
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=default
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/jafar/.docker/machine/machines/default

$ docker-compose -v
docker-compose version: 1.4.2
```

Installed at OSX El Capitan with https://www.docker.com/docker-toolbox installer with brew cask
```
$ brew cask info dockertoolbox
dockertoolbox: 1.8.3
Docker Toolbox
https://www.docker.com/toolbox
/opt/homebrew-cask/Caskroom/dockertoolbox/1.8.3 (178M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/dockertoolbox.rb
==> Contents
  DockerToolbox-1.8.3.pkg (pkg)
```

**Comment by dnephin** [comment]
I looked into fixing this for the 1.5.1 release, but unfortunately `requests` doesn't make it easy to figure out the underlying error.  We'd have to use some kind of inspection like `exc.args[0].reason` to guess at the underlying failure.

**Comment by kenkyee** [comment]
FYI, in my case, it was because on OSX, my proxy settings were pointing to a local squid proxy.  Turning off the proxy setting worked around this.

**Comment by aaronjensen** [comment]
I get this error a minute or so after a successful `docker-compose up`. All of the logs print fine, then I get the error and it disconnects. `docker-compose ps` reports fine afterwards and I can reattach with `docker-compose up`.

**Comment by ijc** [comment]
Issue grooming: the last report of a related issue here was in mid 2016. So I'm going to take a punt that this was resolved at some point in the intervening 3 years (perhaps in a dependency) and close.

If you are stil seeing this then please file a fresh issue against a current version.
