### ISSUE TITLE
Display is broken if yml contains a lot of services.

### ISSUE THREAD

**Issue by storm1er** [docker/compose#9037]
**Description**

docker-compose v2
Having a lot of services might break display on `docker-compose pull` or `docker-compose build`.

**Steps to reproduce the issue:**
1. Have a lot (let say 10) services in docker-compose.yml
2. `docker-compose pull`

**Describe the results you received:**

https://user-images.githubusercontent.com/9821946/146156513-055d3c25-0f6d-4a91-8dfa-fdf3568b5036.mp4

**Describe the results you expected:**

A readable output.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
Docker Compose version v2.2.1
```

**Additional environment details:**

WSL Standard Ubuntu:
```
uname -a
Linux DESKTOP-0SG4CNR 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

With docker desktop v4.3.1

**Comment by JMLX42** [comment]
IMHO duplicate of https://github.com/docker/compose/issues/8800

**Comment by storm1er** [comment]
exact ⬆️
