### ISSUE TITLE
`docker-compose kill` returns a status code now

### ISSUE THREAD

**Issue by forivall** [docker/compose#9056]
File: [compose/cli-command-compatibility.md](https://docs.docker.com/compose/cli-command-compatibility/)

When enabling the "use compose CLI v2" flag, i noticed that some of our scripts failed - specifically, `docker-compose kill`, when no services are running, returns a `1` status code. Previously, it always returned `0`.

**Comment by ndeloof** [comment]
tested with Docker Compose version v2.2.2
`docker-compose kill` return 0 even when there's no container to kill

**Comment by forivall** [comment]
Yeah, i figured the solution would be to update the documentation - if the behaviour should stay the same then yeah! moving over here is good!
