### ISSUE TITLE
docker-compose ps error: Can't find a suitable configuration file

### ISSUE THREAD

**Issue by MuJianxuan** [docker/compose#9069]
**Description**

Why do I prompt ERROR when I execute docker-compose ps , The environment I use is centos7, a non-root user, use yum to install docker, docker can access, docker has to modify the storage path, but using docker-compose can not execute the ps command, which is very puzzled. 
Very much hope for help, thank you 
environment ：
![image](https://user-images.githubusercontent.com/50062346/147647218-9574fcb2-e38a-45f3-b3ec-2638af92da29.png)
sudo docker info :
![image](https://user-images.githubusercontent.com/50062346/147647282-13fcd10e-3db8-42a0-82e4-57c1217ecf18.png)
docker-compose 
![image](https://user-images.githubusercontent.com/50062346/147647376-20b7c462-b556-477a-bbe3-37555485cdd4.png)
![image](https://user-images.githubusercontent.com/50062346/147647408-4925a872-37ea-4f7a-9c24-212e870aab38.png)

ERROR:
![image](https://user-images.githubusercontent.com/50062346/147647510-278484d2-43f7-43c4-b097-87924d02e9e9.png)

Please forgive my limited ability

**Comment by ulyssessouza** [comment]
As the message says, you have no compose file in the current directory. This is necessary to guess the services the command `ps` will look for
