### ISSUE TITLE
docker-compose up starting giving me `ERROR: build path either does not exist, is not accessible, or is not a valid URL.` after system upgrade

### ISSUE THREAD

**Issue by RT-Tap** [docker/compose#9070]
**Description**

**Steps to reproduce the issue:**
1. Update System
2. have a directory with a docker file located at ../someDirectory/service/ relative to current/present working directory
`docker-compose.yml`
```
version: "3.8"
services:
  reverse-proxy:
    container_name: reverseProxy
    build:
      context: ../http/revProxy/
      dockerfile: Dockerfile
    ports:
....
```
output of `ls -la  ../http/revProxy/`
```
drwxr-xr-x 3 root root  4096 Nov 14 20:56 .
drwxr-xr-x 4 root root  4096 Sep 19 03:43 ..
-rw-r--r-- 1 root root    39 Nov 14 20:57 .dockerignore
-rw-r--r-- 1 root root   141 Sep 19 17:54 Dockerfile
drwxr-xr-x 5 root root  4096 Nov 14 20:55 SSLCerts
-rw-r--r-- 1 root root 10982 Dec 17 02:28 httpd-vhosts.conf
-rw-r--r-- 1 root root 21739 Oct  6 00:53 httpd.conf
```
3.  run `docker-compose up -d`

**Describe the results you received:**
`ERROR: build path /srv/http/revProxy either does not exist, is not accessible, or is not a valid URL.`
Although I have built this image along with all the others specified in this `docker-compose.yml` file multiple times over the last year without issue.

**Describe the results you expected:**
Containers to be built and/or just started if they already exist.

**Additional information you deem important (e.g. issue happens only occasionally):**
Running on arch-linux on a raspberry pi 4 and today I decided to update/upgrade using `pacman -Syu` (basically entire system update) and now docker-compose either doesn't want to or can't access the directory, although it seems everything else is work;ing fine.  

**Output of `docker compose version`:**

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 31
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8686ededfc90076914c5238eb96c883ea093a8ba.m
 runc version: v1.0.3-0-gf46b6ba2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.11.4-1-ARCH
 Operating System: Arch Linux ARM
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.62GiB
 Name: rpicm4-1
 ID: PE4E:NQT2:P5S7:PUSD:DHHV:JHD6:H5B7:CAUR:QRJW:BNAF:7SLB:MUO5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
`uname -a `
Linux rpicm4-1 5.11.4-1-ARCH #1 SMP Sun Mar 7 23:46:10 UTC 2021 aarch64 GNU/Linux
Again, like I mentioned, did a full system update and now docker compose is acting up.

**Comment by siddharth** [comment]
Facing the exact same issue on the exact same version of docker-compose (1.28.2 albeit the containerised version) on the same docker-compose.yml file on two different machines running ubuntu 18.04. Difference is the machine where it works is my local development machine where docker-compose was installed on Feb 17 2021 while the machine where it doesn't work is a newly setup AWS EC2 server running 18.04 with docker-compose v 1.28.2 installed as per latest official installation instructions for the containerised version.
There clearly seems to be some mismatch as uploading my local docker-compose binary to the server and using it works just fine.

**Comment by rajamondal99** [comment]
I also facing the same problem in aws
