### ISSUE TITLE
Add support for encrypted environment variables

### ISSUE THREAD

**Issue by siliconcow** [docker/compose#908]
Allow users to encrypt environmental variables in their yaml configuration so they can still feel comfortable keeping them in version control.   Would decrypt values transparently with a chosen environmental variable (like FIG_CRYPT_KEY) and provide users a helper command to generate encrypted values. 

Only downside is you have to add pycrypto as a dependency.

**Comment by danielwegener** [comment]
Would it really be useful to share a fig file that only you can use? Why don't you just use environment keys (see http://www.fig.sh/yml.html#environment) and export the secrets on your host environment in the first place? :-1:

**Comment by cpuguy83** [comment]
Yes, this doesn't seem all that helpful.
You can even encrypt the values and decrypt once in the container.

**Comment by siliconcow** [comment]
Other people on my team can use it, they just need to know the password.   Environment files doesn't solve my problem of distributing secrets to my team members.  I agree I can decrypt them in the container but then I need to do run-time munging of config files or write that facility into all my applications.

**Comment by pwaller** [comment]
At @scraperwiki we solve this using [`direnv`](https://github.com/direnv/direnv) and `secret-tool` which is a part of [`libsecret`](https://wiki.gnome.org/Projects/Libsecret) (part of `libsecret-tools` in debian).

That way, to get the secrets in your environment, you just `cd` to your project and unlock your keyring.

In your `.envrc`, you put this:

```
export SECRET=$(secret-tool lookup projectName SECRET)
```

You can equally well substitute `secret-tool` for a keyring manager of your choice.

**Comment by pwaller** [comment]
There is also #1534 which can possibly supersede this issue.

**Comment by dnephin** [comment]
Ya, I don't think `compose` should be responsible for any encryption or decryption (it's outside the scope of the problem compose is solving).

The above comments outline some good ways to handle this without compose being involved. `env_file`, `environment` keys with no values (so the value is read from the host), or environment variable interpolation in the config are all available to solve the problem.
