### ISSUE TITLE
docker compose push quiet option

### ISSUE THREAD

**Issue by mkushakov** [docker/compose#9089]
Can we add `docker compose push --quiet` option for less verbose output during CI?

**Comment by KoditkarVedant** [comment]
I was planning on contributing to this project. This would be a good starting point for me considering I'm very new to Go programming language.

**Comment by KoditkarVedant** [comment]
I'm waiting for review/approval on the open PR.

**Comment by glours** [comment]
Merged and released in Compose `v2.12.0`
