### ISSUE TITLE
Use latest version of buildx

### ISSUE THREAD

**Issue by errordeveloper** [docker/compose#9098]
**Description**

Currently compose uses buildx 0.5.1, latest version is 0.7.1, an update is overdue.

**Comment by ndeloof** [comment]
Right, we should keep buildx dependency up to date.
In an ideal world we should not vendor buildx in compose, but delegate to buildx as installed by the docker CLI... cc @chris-crone

**Comment by ndeloof** [comment]
I wonder: doesn't dependabot help us to address this?

**Comment by errordeveloper** [comment]
> Right, we should keep buildx dependency up to date.
> In an ideal world we should not vendor buildx in compose, but delegate to buildx as installed by the docker CLI... cc @chris-crone 

Yes, the decision was to use buildx as a plugin for now. I think the real justification is that currently the complex dependency tries are tricky to overlap. In my ideal view we should simplify build client library (perhaps by decoupling from the CLI as such), but I don't see a way we could prioritise it now. We do have a fairly good plugin framework, so it's not going to be a plain exec.
