### ISSUE TITLE
Cannot use docker-compose down with specific services

### ISSUE THREAD

**Issue by cha-king** [docker/compose#9105]
**Description**
It appears as though `docker-compose down` no longer enables the stopping and removal of a particular service.

This might be intentional, but I wasn't able to find any release notes documenting this API change.

I frequently issue `docker-compose down -v <service>` commands to stop a particular container / service and remove its attached volumes, but this not longer works as expected.

**Steps to reproduce the issue:**
1. Run `docker-compose down --help`

**Describe the results you received:**
API documentation along the lines of:
```
Usage: down [options] [SERVICE...]
```

**Describe the results you expected:**
```
Usage: down [options]
```

**Additional information you deem important (e.g. issue happens only occasionally):**
I've noticed that using `docker compose` rather than`docker-compose` acts differently, in that the command will still run with a service provided, however, all services are torn down.

**Output of `docker compose version`:**

```
Docker Compose version v2.2.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., v0.14.0)

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 89
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.774GiB
 Name: docker-desktop
 ID: LT7G:WSL5:JD3D:DQT4:QYTP:333B:T6DI:KAS5:SPLX:LT4D:YAAR:JPG5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


```

**Additional environment details:**

**Comment by ndeloof** [comment]
Can you please clarify: doest `docker compose down SERVICE` work as expected, but `docker-compose down SERVICE` doesn't?

**Comment by cha-king** [comment]
Apologies. It appears as though I was mis-remembering the API for this command.
