### ISSUE TITLE
support pyyaml 6.0 in docker-compose v1

### ISSUE THREAD

**Issue by PJ-Schulz** [docker/compose#9114]
Hello

I want to install `docker-compose` and `pyyaml=6.0` with poetry. However, when I run `poetry add docker-compose pyyaml`, I get a dependency error:

**Steps to reproduce the issue:**
`poetry add docker-compose pyyaml`

```
Using version ^1.29.2 for docker-compose
Using version ^6.0 for PyYAML

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  Because docker-compose (1.29.2) depends on PyYAML (>=3.10,<6)
   and no versions of docker-compose match >1.29.2,<2.0.0, docker-compose (>=1.29.2,<2.0.0) requires PyYAML (>=3.10,<6).
  So, because dockerpytest depends on both docker-compose (^1.29.2) and PyYAML (^6.0), version solving failed.
```

Problem: 
docker-compose==1.29.2 uses a pyyaml version: `PyYAML >= 3.10, < 6`

Request:
Can this dependency be updated for using version 6.0?

**Additional environment details:**
* python version: Python 3.9.4
* poetry version Poetry .1.8

**Comment by renefritze** [comment]
Not stale

**Comment by aguckenber-chwy** [comment]
Not stale

**Comment by jnawk** [comment]
What a hostile bot to have in your repository - ignore a problem for long enough and it'll go away!

**Comment by glours** [comment]
@jnawk Compose v1 is EOL, we don't do any support to the Python version anymore
We communicate a lot for more than a year about this, see the [README](https://github.com/docker/compose/tree/master) of the python branch or the different blog posts [here](https://www.docker.com/blog/announcing-compose-v2-general-availability/) or [here](https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/)

**Comment by jnawk** [comment]
see, that was all that was necessary to say. it wasn't too hard, was it?
closing issues without even ever saying anything, while convenient for you is a toxic user experience.
