### ISSUE TITLE
Docker-compose up failing because "port is already allocated" #4950 -  reopen?

### ISSUE THREAD

**Issue by MikeB2019x** [docker/compose#9117]
Using version:  docker-compose version 1.29.2, build 5becea4c

I'm not sure why this issue is closed.  There are reports right up until today.  If you have to stop and then restart docker (as many have) then that's not a fix, it's a bug.  If you have to take extra steps to clean the environment after stopping a container, then that's a bug ie. 
```
docker-compose down
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
launchctl list | grep docker
launchctl stop com.docker.docker.<number>
```
I'd suggest this be kept/re-opened until it's resolved.

**Comment by jinek** [comment]
https://github.com/docker/compose/issues/4950#issuecomment-1629374398
