### ISSUE TITLE
Add optional flag, so container is not starting with all "fig up", but only on manual demand

### ISSUE THREAD

**Issue by sielaq** [docker/compose#912]
It would be awesome to have "optional: true" in fig.yml,
so container is not starting with when "fig up" / "fig up -d"  is executed.
but only when you do "fig up \<name\>" / "fig up -d \<name\>"
It sould not affect current config so default is "optional: false"

Then you can have multiple versions / alternative solutions / 
some specific containers for specific purposes, that are not starting by default.

**Comment by thaJeztah** [comment]
I think this relates to, or is a dup of https://github.com/docker/fig/pull/630 (and related issues)

**Comment by sielaq** [comment]
hmm you mean initian_scale: 0 or scale: 0
sound like a good alternative

**Comment by sielaq** [comment]
but with second thoghts it is not a goog idea with scaling - then manual run would overrive scale option ?
What if optional container also need to be scaled?

**Comment by thaJeztah** [comment]
Good point, not sure. I think right now you *would* be able to do `fig up -d <service-a> <service-b> ....` to only start those services. But this can be cumbersome for a large amount of services :D

**Comment by bfirsh** [comment]
Thanks for the suggestion! I've created an issue here to aggregate many similar suggestions: https://github.com/docker/compose/issues/1896
