### ISSUE TITLE
2.2.3 release shasum mismatch

### ISSUE THREAD

**Issue by briceburg** [docker/compose#9124]
There appears to be a sha25 sum mismatch with the current release. The 2.2.3 binary available from:
  https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-darwin-x86_64

has a sha256 sum of `f15a7cd54a85f760a8ece92da63fb85b93036c72ead8056391b8a3fe9dc73134`

however the published sha256 file available from:
  https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-darwin-x86_64.sha256

has a different value of `f5983a6d89b1290ef6d5f63afe90098109153279648341cd2107da34ec743bfd`

AFAIK these values usually match. Is github sending wrong content or has the wrong shasum been calculated during release?

**Comment by laurazard** [comment]
Hi @briceburg, I tried replicating your issue, but calculating the sha256 on my own machine using the command:

`shasum -a 256 docker-compose-darwin-x86_64`

yields `f5983a6d89b1290ef6d5f63afe90098109153279648341cd2107da34ec743bfd  docker-compose-darwin-x86_64`

which is the same as the one published on https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-darwin-x86_64.sha256
