### ISSUE TITLE
Use jsonschema v4

### ISSUE THREAD

**Issue by EpicWink** [docker/compose#9128]
Currently docker-compose uses [`jsonschema`](https://github.com/Julian/jsonschema) v3, whose last release ([v3.2](https://github.com/Julian/jsonschema/releases/tag/v3.2.0)) was 18 Novemeber 2019. This is a request to use `jsonschema` v4.

The main improvement for me is that v4 doesn't require `setuptools` anymore (see Julian/jsonschema#631).

Read the [v4.0.0 change notes](https://github.com/Julian/jsonschema/releases/tag/v4.0.0), but the breaking changes are:
> * Code surrounding `DEFAULT_TYPES` and the legacy mechanism for specifying types to validators have been removed, as per the deprecation policy. Validators should use the `TypeChecker` object to customize the set of Python types corresponding to JSON Schema types.
> * Support for Python 2 has been dropped, with `python_requires` properly set.
> * `jsonschema.__version__`, `jsonschema.validators.validators`, `jsonschema.validators.meta_schemas` and `jsonschema.RefResolver.in_scope` have been deprecated, as has passing a second-argument schema to `Validator.iter_errors` and `Validator.is_valid`.

Related: #7054, #6631,  #6347

**Comment by EpicWink** [comment]
I just realised that docker-compose is now written in Go, so this issue is irrelevant

**Comment by ritiksahu** [comment]
@EpicWink any idea how the above changes for jsonschema v4 will break docker-compose ?

**Comment by EpicWink** [comment]
@ritiksahu please see my previous comment. docker-compose doesn't use jsonschema anymore
