### ISSUE TITLE
Regression: No error when using 'exec' in service that doesn't exist

### ISSUE THREAD

**Issue by mwild1** [docker/compose#9129]
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**Description**

docker-compose (1.29.2, build 5becea4c) silently exits when an unknown service is listed on the command-line.

Prior versions of docker-compose would exit with an informative error: "No such service: foobar".

For users this provides no feedback that docker-compose did not execute any command, as opposed to the execution succeeding but the executed command silently exiting.

**Steps to reproduce the issue:**
1. Anywhere (even a directory with no compose file) run: `docker-compose exec this_service_does_not_exist ls`

**Describe the results you received:**

In 1.25.3, observe the output: `ERROR: No such service: this_service_does_not_exist`. :+1: 

In 1.29.2, observe the command silently returning. :-1: 

**Describe the results you expected:**

This behaviour gives no feedback to users if they have a typo in the service name, or run the command in a different directory than their docker-compose.yml.

docker-compose returns a non-zero exit code, however there is no way to distinguish an exec failure from a command failure.

**Output of `docker compose version`:**

```
# docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker info`:**

```
# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 18
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-1042-aws
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 956.5MiB
 Name: ip-172-30-0-83
 ID: 6JC7:HAFJ:ERQJ:KQI2:YNXK:MJAC:4PSN:7NBV:5U24:27GP:CURR:OY2G
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

The behaviour was reproduced across at least two independent machines.

**Comment by ulyssessouza** [comment]
Hello @mwild1.
It looks like it works fine on Compose V2. Don't you want to give it a try?

**Comment by mwild1** [comment]
To be honest I wasn't aware of V2 - because the docs at https://docs.docker.com/compose/install/ still guide you to install V1.

After doing more research, it looks like V2 is not yet considered "GA". I am recommending compose as a way for users of my software project to deploy it on Linux. I'm not comfortable recommending software for that purpose if it's not quite ready yet, though I'm happy to hear this issue will be resolved by that upgrade when it happens!

**Comment by laurazard** [comment]
I'm closing this issue since V2 is now considered GA, and this is not an issue in V2. Thanks for your report!
