### ISSUE TITLE
Any -H option with docker-compose to point to Swarm manage node?

### ISSUE THREAD

**Issue by sourav82** [docker/compose#913]
I have a Swarm cluster and want to make use of docker-compose to run containers across the cluster. I need to pass the Swarm manager node using -H with docker-compose. Is there any such option with docker-compose?

**Comment by dnephin** [comment]
You can use `DOCKER_HOST` to point compose at any docker engine or swarm cluster:

http://docs.docker.com/compose/reference/overview/#docker-host
