### ISSUE TITLE
Clarify differences between compose --env-file arg and env_file directive

### ISSUE THREAD

**Issue by Kangaroux** [docker/compose#9135]
The `--env-file` arg for compose specifies a .env file that can be used from within the docker-compose file itself. For example, `image: my-app:$TAG`. The `env_file` YAML directive also specifies a .env file, but this file is loaded into the container at runtime, and has nothing to do with the `--env-file` option, despite having the same name.

This caused a lot of confusion for me, it's not called out very well (or at all?) in the docs about what the differences are.

**Comment by thebeeric** [comment]
I just spent 45 minutes trying to figure out why my variable wouldn't pass correctly when specified via the yaml ```env_file```, but it worked correctly when defined via an ```.env``` file. The documentation around the differences is non-existant.

**Comment by ndeloof** [comment]
Thanks for reporting. This indeed is a very common confusion for our users. 
We plan to fully rewrite the compose documentation, in a "usage centric" way. This will help such "details" are better explained.
