### ISSUE TITLE
Will the possibility to run the docker-compose V2 plugin without installing docker-cli remain ?

### ISSUE THREAD

**Issue by zapoig** [docker/compose#9150]
This is a question issue :

Currently it is possible - tested  on linux ubuntu 20.04 - to just download the docker-compose v2 plugin in your path rather than in one of the suggested cli-plugins folders.
It then can run without the need to install the full docker-cli package.

This is a huge win when trying to minimize the disk usage of the installation : 12 MB used for the docker-compose plugin alone, and more than 200 MB if installing the docker-ce-cli package.

I would like to know if I can rely on that possibility being kept in the future releases.
Note that I don't ask for support of that solution, I just want to know if it will remain technically possible.

Thank you.

**Comment by glours** [comment]
Hello @zapoig 

Yes it will be keep at this, Compose V2 should work as a standalone binary such was Compose v1

**Comment by zapoig** [comment]
Thank you, that is great news.
