### ISSUE TITLE
docker-compose down silently ignores arguments

### ISSUE THREAD

**Issue by Jille** [docker/compose#9151]
**Description**

I tried to down one service. `docker-compose down myservice` killed all services instead of just the one, completely ignoring the argument I gave it.

**Steps to reproduce the issue:**
1. Create a docker-compose.yml with 2+ services
2. docker-compose up -d
3. docker-compose down myservice

**Describe the results you received:**

```
# docker-compose down etcd
[+] Running 3/3
 ⠿ Container serviceone-1       Removed
 ⠿ Container servicetwo-1       Removed
 ⠿ Network mynetwork            Removed
```

**Describe the results you expected:**

I expected it to only remove the one service. Getting an error about superfluous arguments would've been fine too.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.2.3
```

**Comment by cedrictwillie** [comment]
@Jille This seems to be the expected behavior.

See docs [here](https://docs.docker.com/compose/reference/down/#:~:text=By%20default%2C%20the%20only%20things%20removed%20are%3A).

Use `docker compose stop service-name` instead to stop a single service.

**Comment by Jille** [comment]
This violates the principle of least surprise for me. If you use `docker-compose up $service`, you naturally expect `docker-compose down $service` to take down that one service. Having it turn down everything is a landmine and might cause a production outage.

We could avoid such outages by simply giving an error if someone passes arguments to `down`.
