### ISSUE TITLE
Feature request: Export service replica index to container via some environment variable or system file

### ISSUE THREAD

**Issue by vlad-vinogradov** [docker/compose#9153]
Since docker-compose service can be scaled, it would be useful to export to each container the replica ordinal index as some environment variable or the contents of some system file. This index can be used, for example,  to create replicas own subdirectories if all replicas use the same host path as bind mounts.

**Comment by languitar** [comment]
What is the solution for this request?

**Comment by vlad-vinogradov** [comment]
@languitar 
First of all, keep in mind that Compose does not guarantee a strictly continuous sequence of ordinal indexes. Continuity can be broken when removing some container instances and re-executing `docker-compose up --scale ...`

The ordinal index can be retrieved from container's FQDN.
For example, if the container has `bash`, `nslookup`, `hostname`, and `head` utilities, then try the following command:
```
echo "$( v="$( nslookup "$( hostname -i )" | head -n 1 )"; v="${v##* = }"; v="${v%%.*}"; v="${v##*-}"; v="${v##*_}"; echo "$v" )"
```
The ordinal index can also be retrieved [from Docker API](https://stackoverflow.com/questions/39770712/how-can-a-container-identify-which-container-it-is-in-a-set-of-a-scaled-docker-c).

**Comment by alexey-sh** [comment]
in my cases hostname is not a solution.

```sh
$ env
HOSTNAME=dd5de00d9e9d
```

**Comment by vlad-vinogradov** [comment]
@alexey-sh
`HOSTNAME=dd5de00d9e9d` is not FQDN. This is just short form. For example, compare the output of the following two commands:
```
$ echo $HOSTNAME
phpfpm
$ echo "$( nslookup "$( hostname -i )" | head -n 1 )"
2.14.16.172.in-addr.arpa	name = dsb-dsbconfigs-fullstack-phpfpm-1.dsb-dsbconfigs-fullstack_dsbnet.
```
