### ISSUE TITLE
docker-compose is working but not docker compose

### ISSUE THREAD

**Issue by Crazynovatech** [docker/compose#9156]
Hi, I have installed docker compose v2.1.1 following the instructions given. **docker-compose version** is working fine giving the result as "Docker Compose version v2.1.1". But **docker compose version**  is throwing error as docker: 'compose' is not a docker command. 
Steps Followed
--------------------
curl -sL https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-`uname -s`-`uname -m` -o ~/.docker/cli-plugins/docker-compose --create-dirs
chmod +x ~/.docker/cli-plugins/docker-compose

**Comment by derickson2402** [comment]
This is normal behavior. ```docker-compose``` on Linux essentially wraps around normal docker commands, similar to running ```docker compose``` on Docker Desktop. However docker engine on Linux is for production environment so it is a separate feature to get docker-compose (at least that is my understanding of that decision)

**Comment by draksha22** [comment]
You can try running the following commands as mentioned below:
1. mkdir -p ~/.docker/cli-plugins/
2. curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
3. chmod +x ~/.docker/cli-plugins/docker-compose
4. docker compose version

**Comment by MetathronZ** [comment]
me behavior on my end. Docker and Docker compose v2 installed as stated on Docker website. Also the tutorial from @draksha22 does not bring any other result.
Environment: Raspi 3 with Raspian lite 64 bit

**Comment by jessex7** [comment]
I have a related problem. I followed the instructions from https://docs.docker.com/compose/cli-command/#install-on-linux, and running `docker compose version` is successful.
`alexdain@debian:~/dev/getting-started-master/app$ docker compose version`
`Docker Compose version v2.2.3`

When I try to use an actual command, it does not work.
`alexdain@debian:~/dev/getting-started-master/app$ sudo docker compose up`
`docker: 'compose' is not a docker command.`
`See 'docker --help'`

**Comment by ndeloof** [comment]
`sudo` makes your command run as user `root`, and I guess you installed Compose V2 as a CLI plugin under your $HOME, which isn't the same used by root.
You can install compose V2 globally under `/usr/local/lib/docker/cli-plugins` so it is available to all user (and doing so, to `root`)

**Comment by jessex7** [comment]
Thank you! I never realized that sudo completely (although temporarily) runs the command as root. I thought it merely allowed the user to assume root "authority". Anyway, you corrected that confusion so thank you! I installed it into the /usr/local/... path and it works great now. Thank you again!

**Comment by cjones27** [comment]
Hi @ndeloof that worked for me too! Thank you very much! Is there a way to specify this detail somewhere so during installation for Linux based users it's easier to detect (I had to do this twice months apart and still was difficult to find this issue to solve it)? That would be great!

**Comment by Codyerd** [comment]
> You can try running the following commands as mentioned below:
> 
> 1. mkdir -p ~/.docker/cli-plugins/
> 2. curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
> 3. chmod +x ~/.docker/cli-plugins/docker-compose
> 4. docker compose version

This solved my problem! I was running on Ubuntu 20.04. Thank you so much!
