### ISSUE TITLE
--parallel no longer respected when building

### ISSUE THREAD

**Issue by bbrefeld** [docker/compose#9159]
**Description**

Today I upgraded from docker compose v2.0.1 to v.2.2.3
When I ran a docker compose build command like I normally do I noticed it no longer built in parallel.
Command used: ```docker compose -f docker-compose.yml build --parallel```

I looked through the release notes but didn't see anything related to the --parallel flag.
Am I missing something or is --parallel no longer working?

I was able to confirm this behaviour on 3 separate systems.
OS: Ubuntu 20.04

**Steps to reproduce the issue:**
1. Update to docker compose version 2.2.3
2. Run a docker compose build command with --parallel flag

**Describe the results you received:**
Building takes way longer than it did before updating

**Describe the results you expected:**
Building to happen in --parallel

**Output of `docker compose version`:**
```
Docker Compose version v2.2.3
```

**Output of `docker info`:**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 159
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.16.7-surface
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.55GiB
 Name: surface-linux
 ID: VMWQ:P2JE:IMWQ:YMEL:D72B:LRP6:VX7M:64KL:L7B7:5SYE:5NFA:55D5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
This machine has a non standard kernel but the same behaviour is percieved on a destkop with the default Ubuntu 20.03 kernel

**Comment by ulyssessouza** [comment]
In v2.0.1 the behaviour is the same. The flag is just ignored.

https://github.com/docker/compose/blob/v2.0.1/cmd/compose/build.go#L71..L72
