### ISSUE TITLE
docker run options transport to docker compose, container would work

### ISSUE THREAD

**Issue by Yingliangzhe** [docker/compose#9162]
Hello everyone,
I have a question using a docker-compose, I'm using a usb camera,
I can use the camera by following command:
`sudo docker run -ti -v /dev:/dev -v /run/udev:/run/udev:ro  --device-cgroup-rule 'a 189:* rwm' <image-id> /bin/bash` 

But if I move the -v to docker-compose file
volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
    device_cgroup_rules:
      - a 189:* rmw
The camera would be found by the container. 
docker-compose also started with sudo. 

Has some else also the same issue? 

Thank you!

**Comment by Paraphraser** [comment]
Yes! I have the same problem with `device_cgroup_rules`. See issue #9059

The workaround is to use docker-compose 1.29.2 which supports `device_cgroup_rules`. It looks like any docker-compose v2 or later silently ignores `device_cgroup_rules`.

**Comment by ndeloof** [comment]
Closing as a duplicate for #9059
