### ISSUE TITLE
docker-compose v2 down -v does not respect "external" declaration

### ISSUE THREAD

**Issue by MichaelKim0407** [docker/compose#9172]
**Description**

`docker-compose down -v` behavior not respecting documentation

**Steps to reproduce the issue:**
1. Create a compose file with an external volume
2. Create volume
3. Run `docker-compose down -v`

**Describe the results you received:**
Volume removed

**Describe the results you expected:**
Volume should not be removed, per documentation
> Networks and volumes defined as `external` are never removed.

**Additional information you deem important (e.g. issue happens only occasionally):**
1. Docker-compose v1 works correctly
2. May be related to #9145

**Output of `docker compose version`:**

```
Docker Compose version v2.2.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 54
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.94GiB
 Name: docker-desktop
 ID: VZLG:BCFO:BQRY:LOIT:UAIA:BS6H:EHTB:V3TM:YCLP:PI4B:FZ65:YBY3
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 46
  Goroutines: 49
  System Time: 2022-02-14T06:48:01.62791828Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by larssb** [comment]
Did you figure it out @MichaelKim0407 ?

**Comment by ndeloof** [comment]
I'll look into this on Monday, thanks for reporting

**Comment by ndeloof** [comment]
I tried to reproduce this issue without success:
```yaml
services:
  text:
    image: nginx
    volumes:
      - foo:/foo
    
volumes:
  foo:
    external: true
```

```
$ docker compose version
Docker Compose version v2.2.3
$ docker volume create foo
foo
$ docker volume ls
DRIVER    VOLUME NAME
local     foo
$ docker compose up -d
[+] Running 1/1
 ⠿ Container truc-text-1  Started                                          0.8s
$ docker compose down
[+] Running 2/2
 ⠿ Container truc-text-1  Removed                                          0.2s
 ⠿ Network truc_default   Removed                                          0.1s
$ docker volume ls
DRIVER    VOLUME NAME
local     foo
```

**Comment by MichaelKim0407** [comment]
@ndeloof 

`docker compose down -v`

**-v**

**Comment by ndeloof** [comment]
@MichaelKim0407 sorry, bad copy/paste in my comment. using `-v` leaves `foo` volume impact

**Comment by MichaelKim0407** [comment]
OK I recreated my scenario when I reported the bug. I was running some automation and I created the volumes with docker-compose.

If you have

```
volumes:
  foo:
    name: test_foo
    #external: true
```

you can create the volume by running `docker-compose up -d`.

Now if you remove the comment and declare the volume external,

```
$ docker-compose-v1 down -v
Volume test_foo is external, skipping
$ docker-compose down
 ⠿ Volume test_foo  Removed
```

So it looks like docker-compose v2 somehow "remembers" if a volume is created by docker-compose, and does not check if the declaration has changed since then. Docker-compose v1 however respects the declaration at the time the command is run.

The same is true the other way around: If I create a volume using `docker volume create` and the volume is not declared external, running `docker-compose down -v` with v2 will not remove the volume but v1 will.

So this is a discrepancy between the behavior between v1 and v2 and according to the documentation I'm expecting v1 behavior.

**Comment by ndeloof** [comment]
@MichaelKim0407 right, doing so the volume is created with com.docker.compose.project label and will be detected as "owned by project" then removed. This is a side effect for `docker compose down` to only relies on project name, not the compose.yaml file (which might have been updated after application was created). For backward compatibility we _should_ only apply this logic when user explicitly requested removal by project name. I'll propose a fix ASAP

**Comment by MichaelKim0407** [comment]
@ndeloof Thanks.

I'd also add that, as a general design choice, `docker-compose` should not rely on historical information for its behavior - it will become a maintenance nightmare. DevOps engineers (your users) DO NOT know how a system got to the current state. Anyone should be able to come in, read `docker-compose.yml`, and work on it.

**Comment by ndeloof** [comment]
That's the intent of relying on actual resources, not the compose file you have in hands (which also depends on your environment variables). It' pretty common one run a `docker-compose ..` command and some stuff is left behind because some variable is not set the exact same way it was on `docker-compose up`. Running `docker compose -p NAME xx` allows to only rely on existing resources, so you can enforce a clean shutdown.

**Comment by MichaelKim0407** [comment]
I'm arguing that it's a bad design choice, because DevOps engineers CAN read but CANNOT remember things. DevOps actions should be explicit and intentional. So docker-compose should just read the content of the compose file when the command is run.

**Comment by ndeloof** [comment]
That's true if your intent is to run an explicit shutdown for some resource you manage by code as compose.yaml and assume under control. But on the other hand there's a bunch of users who just can't guarantee the environment used to `compose up` is the exact same as they run `compose down` but still want a full cleanup. Two use-cases here, and we need to cover boths.

**Comment by MichaelKim0407** [comment]
Well, the scenario you're describing doesn't sound to me like how things should be done in production, but if you also want to make it work, I'm fine with that.

**Comment by larssb** [comment]
I had the issue with `networks` that was set as `external: true`. Will your fix also apply to that scenario @ndeloof ?

**Comment by glours** [comment]
Yes the PR address both volumes and networks

**Comment by larssb** [comment]
Fantastic! Thanks.

--
Mvh. / Kind regards
Lars Bengtsson

- Health is wealth, movement is medicine -
