### ISSUE TITLE
Build command with --parallel flag

### ISSUE THREAD

**Issue by TheBottleCyber** [docker/compose#9174]
**Description**

Due to the move of docker-compose to docker compose when using the `docker compose build` command with **--parallel** compose throwings: "_unknown flag: --parallel_"

**Steps to reproduce the issue:**
1. Write command to shell and try to build Build any docker-compose.yml file https://github.com/TheBottleCyber/LeviathanBot/blob/master/build_docker-compose.yml is example docker-compose.yml file

In my case this is: `docker compose -f .\build_docker-compose.yml --parallel build`

**Describe the results you received:**

"_unknown flag: --parallel_"

**Describe the results you expected:**

Build docker-compose.yml file with parallel 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

Docker Compose version v2.2.3

**Output of `docker info`:**

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 5.774GiB
 Name: docker-desktop
 ID: MT5U:Y22Z:BGYF:NJ7Y:BKFZ:6R23:CAO4:F5GS:IKOP:DFYY:WBLN:6KMG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

**Additional environment details:**
Docker in Windows 11 running in Docker Desktop version 4.5.0 (74594) 

![Screenshot_1](https://user-images.githubusercontent.com/55963309/153890111-9f35eaa4-0101-418b-8c9e-0c5046b5cf1e.png)

**Comment by ulyssessouza** [comment]
Now the flag is allowed, but with no effect. 

For reference: https://github.com/docker/compose/blob/v2.0.1/cmd/compose/build.go#L71..L72
