### ISSUE TITLE
In ECS context: docker compose convert/up is API throttled

### ISSUE THREAD

**Issue by thorfi** [docker/compose#9177]
**Description**

`docker compose up` fails due to AWS EC2 API throttling.

**Steps to reproduce the issue:**
1. Have a non-trivial docker-compose.yaml 
2. docker context use ecs-context
3. `docker compose up` or `docker compose convert`

**Describe the results you received:**

ThrottlingException:
	status code: 400, request id: 2259a3c2-1130-4034-a41f-24914d8fa550

**Describe the results you expected:**

`docker compose up` - CloudFormation Stack should be created 
`docker compose convert` - CloudFormation .yaml code should be printed

**Additional information you deem important (e.g. issue happens only occasionally):**

This was not happening in `docker compose convert` previously, but now it is. `docker compose up` has had the problem for a long time.

**Output of `docker compose version`:**

```
% docker context use ecs-context
Docker Compose version dev
% docker context use default
Docker Compose version v2.2.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 2.423GiB
 Name: docker-desktop
 ID: P5SC:JGRV:E5O6:N6SH:7TCP:HA6N:XDIS:A3VT:KMQL:XAVX:H23E:AGPR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
 ```

**Additional environment details:**

macOS Monterey, MacBook Pro M1.

**Comment by ndeloof** [comment]
@glours can you please transfert this issue to compose-cli?

**Comment by thorfi** [comment]
> @glours can you please transfert this issue to compose-cli?

Never mind, re-raised this myself as: docker/compose-cli#2134

**Comment by thorfi** [comment]
@glours @ndeloof  FYI, this turns out to be related to the number of EFS volumes that exist, if there are >= 100 the number of Describe operations throttles.
