### ISSUE TITLE
Compose v2 vs. Compose v1 - Drop-in replacement of docker-compose down --volume does not work

### ISSUE THREAD

**Issue by hannahchan** [docker/compose#9180]
In Docker Compose v1 (v1.29.2), the command;

    docker-compose down --volume

In v2.2.3, has become;

    docker-compose down --volumes

This has broken a few scripts and requires any documentation we have written to be updated. The `-v` is unaffected. The idea that Compose v2 is a drop in replacement for v1 in this scenario doesn't hold true.

**Comment by ndeloof** [comment]
`--volume` was a typo, as the plan was to reproduce docker-compose legacy flag `down --volumes` (or `-v`).
