### ISSUE TITLE
Is there a way to keep "docker-compose" up-to-date using "apt-get update" or similar?

### ISSUE THREAD

**Issue by nunoperalta** [docker/compose#9195]
The version from `pip` seems to be V1

And looking at the instructions at https://docs.docker.com/compose/cli-command/#install-on-linux
It seems that the only way to install V2 is by downloading the script from a tag/release.

It seems that the only way to keep docker-compose up-to-date is by manually downloading from the latest tag/release,
while I'd like to have it automated.

Is it possible?
Thank you very much.

**Comment by ndeloof** [comment]
Sure, we are working on getting compose available as a system package with other docker bits, see https://github.com/docker/docker-ce-packaging/pull/553

**Comment by nunoperalta** [comment]
Perfect! Thank you for that :)

**Comment by nemchik** [comment]
It seems like the compose plugin packages have not been updated in the docker-ce repo https://download.docker.com/ since v2.3.3. Does it only get updated when cli updates?

**Comment by ndeloof** [comment]
We are working on separating the system package release cycle from docker/cli so that we can get latest release available

**Comment by johnthagen** [comment]
Related to
- #9497

**Comment by nunoperalta** [comment]
This is resolved, at least to me on AlmaLinux 8.

```
$ dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
$ dnf install docker-compose-plugin
```

**Comment by nemchik** [comment]
Packages are available in the official package repo, and users can use their package manager to get updates, but the releases from here don't get put in the official package repo until a new release of the docker cli (I think that's when it happens). So the official package repo will trail behind official releases from this repo. @ndeloof said this will change in the future.

Not sure if it's valid to keep this issue open until then, or consider it resolved or track a separate issue about keeping the package repo updated.

**Comment by ndeloof** [comment]
Closing as a duplicate for https://github.com/docker/compose/issues/9657
