### ISSUE TITLE
Inconsistent behaviour for project name containing dots

### ISSUE THREAD

**Issue by simue** [docker/compose#9216]
**Description**

If your project name contains dots, the dots are going to be removed when using  `compose -p <project.name> up`  
This can be confirmed by running `compose ls`, where the project is then shown as <projectname>  
When trying to shut the project down with `compose -p <project.name> down` the containers are not removed correctly. If the same is done with `compose -p <projectname>` things seemingly are cleaned up correctly.

**Steps to reproduce the issue:**
see above

**Describe the results you received:**
containers not cleaned up

**Describe the results you expected:**
containers cleaned up

**Additional information you deem important (e.g. issue happens only occasionally):**
Didn't happen with docker compose v2.0.0-rc.3

**Output of `docker compose version`:**

```
Docker Compose version v2.2.3
```

**Comment by laurazard** [comment]
Since this behaviour no longer happens (commands will now fail with `"xxx" is not a valid project name`) I'm closing this issue. Thanks for the report!

**Comment by waja** [comment]
Cool, this broke my docker compose 1 setup when migrating over to 2.x, cause the project name auto generated and contains dots (which was ignored when creating the stack)

**Comment by simue** [comment]
@laurazard I don't consider this one closed. Yes, creating a project with a project name containing a dot fails explicitly, but according to compose spec there is no such restriction on the project name:
https://github.com/compose-spec/compose-spec/blob/master/spec.md?plain=1#L48-L52
https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json#L14-L17

Is the spec out of date, or this implementation faulty?
