### ISSUE TITLE
docker-compose network preemptive chaos

### ISSUE THREAD

**Issue by Sunnnner** [docker/compose#9218]
I wrote a service myself, and everything was fine with the other services before this service loaded, but writing this service to docker-compose.yml, the other services name or service not found, Then I pulled back the new service and set up a separate networks for it so that all services could run.

my docker-compose version "3"

**Comment by ndeloof** [comment]
Please let us know version of `docker-compose` tool you're using (`docker-compose version`)

Please also attach a (minimal) compose file demonstrating this issue

**Comment by Sunnnner** [comment]
> Please let us know version of `docker-compose` tool you're using (`docker-compose version`)
> 
> Please also attach a (minimal) compose file demonstrating this issue

Thanks for the answer, I've solved the problem now, it's not that docker-compose went wrong, it's that I had a problem with my scripting
