### ISSUE TITLE
Docker in Docker cannot build Ruby on alpine 3.14+

### ISSUE THREAD

**Issue by luke-hill** [docker/compose#9220]
**Description**

Using compose, build the following image in a Docker in Docker ecosystem (It is only possible with alpine 3.13 and below)

```
FROM ruby:3.0.3-alpine3.13

ENV BUNDLER_VERSION=2.3.6 \
    BUNDLE_PATH=/app/vendor/bundle

RUN apk add --no-cache --update build-base bash jq curl libffi-dev

RUN mkdir -p /app

COPY Gemfile* /app/

WORKDIR /app

RUN gem install bundler -v $BUNDLER_VERSION && \
    bundle install && \
    gem cleanup

RUN addgroup --gid 1000 ruby && \
    adduser --home /home/ruby --uid 1000 --ingroup ruby --disabled-password ruby

COPY . /app

RUN chown -R 1000:1000 /app

USER 1000
```

**Describe the results you received:**
As soon as you use alpine 3.14 and above, you get a permission error.
```
ERROR:  While executing gem ... (Gem::FilePermissionError)

    You don't have write permissions for the /usr/local/bundle directory.
```
**Describe the results you expected:**
It works.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is **not an issue up to December 2021 - As alpine 3.13 exists for all modern rubies**

This is an issue for ruby 3.1.x+ as there is no alpine 3.13 equivalent for this (Minimum alpine is 3.14)

**Output of `docker compose version`:**

```
docker-compose version
— Shell Script
<1s
+ docker-compose version

docker-compose version 1.29.2, build 5becea4c

docker-py version: 5.0.0

CPython version: 3.7.10

OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker info`:**

```
ADDING SHORTLY from new ci run
```

**Additional environment details:**
N/A

**Comment by luke-hill** [comment]
EDIT: A simple mitigation strategy would be for someone to continue building on alpine 3.13 (Although this is wholly impractical I admit).

If I need to move this to a different directory / location, please advise. It's not immediately clear where this issue would lie. I've also created the following issues
https://github.com/alpinelinux/docker-alpine/issues/237
https://github.com/docker/docker-py/issues/2938

**Comment by ndeloof** [comment]
Can you build this Dockerfile using plain `docker build ...`?
Do you have buildkit enabled?

**Comment by luke-hill** [comment]
```
+ docker build ./

Sending build context to Docker daemon    128kB

Step 1/11 : FROM ruby:3.1.1-alpine3.15
 ---> 9d6c19e9b063

Step 2/11 : ENV BUNDLER_VERSION=2.3.6     BUNDLE_PATH=/app/vendor/bundle
 ---> Using cache
 ---> 1154f252ad1a

Step 3/11 : RUN apk add --no-cache --update build-base bash jq curl libffi-dev
 ---> Using cache
 ---> f69b913e5ec9

Step 4/11 : RUN mkdir -p /app
 ---> Using cache
 ---> 5c33c6c38052

Step 5/11 : COPY Gemfile* /app/
 ---> Using cache
 ---> f43fa633bc47

Step 6/11 : WORKDIR /app
 ---> Using cache
 ---> f5e04f9fe6d1

Step 7/11 : RUN gem install bundler -v $BUNDLER_VERSION &&     bundle install &&     gem cleanup
 ---> Running in 8e80140539b9

ERROR:  While executing gem ... (Gem::FilePermissionError)

    You don't have write permissions for the /usr/local/bundle directory.

The command '/bin/sh -c gem install bundler -v $BUNDLER_VERSION &&     bundle install &&     gem cleanup' returned a non-zero code: 1

script returned exit code 1
```

**Comment by ndeloof** [comment]
ok, so this isn't a compose issue. And according to the logs you're using the classic builder.
@glours can you please transfert this to docker/cli, I don't have permission to

**Comment by luke-hill** [comment]
That's fine. I've spent 2months and I've got nowhere, it's likely I'm looking in the wrong area/s. But I have basically been on my own. If people could give me 2-3 hints / tips to check I'm happy to help.

Also just for clarity, the issue is only when moving from alpine 3.13 to 3.14+ (However staying on alpine 3.13 isn't possible any more).

**Comment by ndeloof** [comment]
Could you please attach your `Gemfile` so we get a reproduction scenario?

**Comment by ndeloof** [comment]
Also, unclear to me: why did you mentioned "Docker in Docker" that doesn't appear in your description

**Comment by luke-hill** [comment]
Gemfile is irrelevant.

We use CI docker in docker.

**Comment by ndeloof** [comment]
Maybe but I can't reproduce issue using your Dockerfile without. Or maybe you can offer a minimalist reproduction scenario?

**Comment by luke-hill** [comment]
the issue here is as described.

Docker in Docker, using alpine 3.14+

**Comment by ndeloof** [comment]
Right, but - again - can you please confirm you can build this Dockerfile with a plain `docker build .` without using DinD.
The more details you give and ability we have to reproduce, the earlier/easier we can offer assistance. Here I'm blind with your issue

**Comment by luke-hill** [comment]
This is **only** an issue when using DinD alpine 3.14+
Building on DinD using alpine 3.13 💚 
Building locally using docker-compose with any version of alpine 💚 
Building locally using docker with any version of alpine 💚

**Comment by ndeloof** [comment]
ok. So we need to move this issue to the relevant repository (probably moby/moby?)
But without a reproduction Dockerfile, this probably won't get any step forward.

**Comment by luke-hill** [comment]
The repro dockerfile is attached. You can even diet it more.

The issue is the single command `gem install bundler.....`

**Comment by ndeloof** [comment]
ok.
Then, please prepare a minimal Dockerfile to demonstrate this bug, then report an issue on moby/moby as this definitively is the wrong repo for this

**Comment by HugoPoi** [comment]
https://github.com/moby/moby/issues/43311#issuecomment-1197970141
