### ISSUE TITLE
The `latest` release went backward in the last 24h

### ISSUE THREAD

**Issue by 1ace** [docker/compose#9224]
In the last 24h, *something* happened on this repo that caused the [`latest` release](https://github.com/docker/compose/releases/latest) to go backward from `v2.2.3` to `v2.2.2`, which happens to be a problem for me because of [this severe bug in `v2.2.0` to `v2.2.2` preventing docker compose from being able to stop](https://github.com/docker/compose/issues/9003), which was fixed in `v2.2.3`. This then ends up breaking the part of our CI that verifies that the latest docker compose release doesn't have any changes that we'd need to adapt to.

I assume someone made a mistake with the tag, or in GitHub's release interface (which I'm not familiar with). Could you undo/fix it quickly so that [`latest`](https://github.com/docker/compose/releases/latest) points to the latest release again?

**Comment by glours** [comment]
@1ace 
Can you retry, it should be fixed now

**Comment by 1ace** [comment]
Indeed it's fixed, thank you very much! I was hoping for it to be fixed within a few days, but you actually fixed it within 10 minutes :muscle:
