### ISSUE TITLE
[proposal] `docker compose config --parameters` to list compose file variables

### ISSUE THREAD

**Issue by ndeloof** [docker/compose#9226]
Archived project [Docker app](https://github.com/docker/app) offered an interesting feature regarding compose file variable interpolation. To avoid relying on uncontrolled environment variable substitution, it offered a migration path from a compose.yaml file to extract all variables as "parameters"

To address this use case, I suggest we introduce `docker compose config --parameters` to list variables declared in a compose file. In an ideal world, would also show default value and resolved value with source it was read from.

**Comment by teror4uks** [comment]
Do you suggest showing runtime values for variables regarding this [interpolation spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#interpolation)?

Or re-implement the `parameters` feature from `Docker app` project?

**Comment by ndeloof** [comment]
only show variables.

something like this (assuming this is feasible :P) :
```
$ docker compose config --parameters
NAME       DEFAULT        REQUIRED          ACTUAL         SOURCE
foo            bar                   false                    true                os.Env
zot                                     true                     qix                  .env   
`
``

That being said, we could _also_ add support for `docker compose` to only resolve variables based on some `parameters` file, vs using environment variables or `.env` file; but that's another orthogonal topic

**Comment by teror4uks** [comment]
looks cool, I would like to participate, if you don't mind :)
