### ISSUE TITLE
`no such project:` when `compose run` after v2.3.0

### ISSUE THREAD

**Issue by felipecrs** [docker/compose#9234]
**Description**

**Steps to reproduce the issue:**
1. `docker-compose run <service-name>`

https://user-images.githubusercontent.com/29582865/156896373-0ccf3301-acac-4afe-b506-e3b59d83743f.mp4

**Describe the results you received:**

```console
$ docker-compose run devcontainer
no such project: devcontainer
```

**Describe the results you expected:**

To work, as it was working before v2.3.0.

**Additional information you deem important (e.g. issue happens only occasionally):**

I think this is a major outage to docker-compose.

**Output of `docker compose version`:**

```
Docker Compose version v2.3.0
```

**Output of `docker info`:**

```console
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.0)
  compose: Docker Compose (Docker Inc., v2.3.0)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 47
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-28-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.35GiB
 Name: node-10-120-10-37
 ID: ZM55:XLST:Y65X:WG3G:DF66:IOUC:D57S:6EVQ:M2VU:XSFV:XEUD:WRVR
 Docker Root Dir: /mnt/disk0/var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  <hidden>
 Live Restore Enabled: false
```

**Additional environment details:**

None.

**Comment by antoineco** [comment]
I'm seeing something similar after starting containers from multiple Compose files:

```
docker compose -f docker-compose.yml -f additional-compose.yml up service-c
```
  
In this example, I have 2 services "service-a" and "service-b" defined in `docker-compose.yml` (which were already running from a previous "up"), and start a third service "service-c" from a separate `additional-compose.yml`.

Now any operation that's executed without including `additional-compose.yml` fails:

```
$ docker compose logs service-a
no such project: my-project
```

```
$ docker compose stop service-a
no such service: service-a
```

**Comment by Jasper-Ben** [comment]
Can confirm this issue. This is related to the folder in which the docker-compose project resides:

e.g. having a `docker-compose.yml` in a folder named "test" with the content

```
services:
  alpine:
    image: alpine:latest
```

and running `docker-compose run alpine` will result in the error message `no such project: test`.
Changing the service name in accordance to the folder name also does not help. `docker-compose.yml` with the content

```
services:
  test:
    image: alpine:latest
```

will still result in the same error message.

**Comment by rimelek** [comment]
I have the same issue. The only way I can run a service with v2.3.0 is when I start at least one container in a project using `docker compose up -d`. After that I can use `docker compose run`. The problem is that I need to use `docker compose run --rm` before I start any other container. It works perfectly with v2.2.3 on MacOS and also Linux.


@antoineco 

> In this example, I have a service "service-a" defined in `docker-compose.yml` (which was already running from a previous "up"), and start a second service "service-b" from a separate `extras/additional-compose.yml`.
> 
> Now any operation that's executed without including `extras/additional-compose.yml` fails:

I could not reproduce your issue. It surprised me because I thought it would have been a normal behavior not being able to remove service-b or reading its logs without adding the additional compose file, but it worked. Except when I tried to remove the service I got "no such service" which was understandable to me.

**Comment by antoineco** [comment]
@rimelek you're right, I tried to simplify and it doesn't fail either. I should have double checked.
The real failure that I'm seeing happens with [a few more services](https://github.com/deviantony/docker-elk/runs/5437866784?check_suite_focus=true), yet similar commands.

**Comment by ndeloof** [comment]
I can confirm this regression, looking into this

**Comment by bno1** [comment]
So the only solution is to downgrade until the fix is released?

**Comment by glours** [comment]
@bno1 we will do a release today, we have some check to do before
