### ISSUE TITLE
Building with Docker 19.03.8 can fail if `runc` is too old

### ISSUE THREAD

**Issue by ardrabczyk** [docker/compose#9235]
**Description**

In BUILDING.md it says that _Docker 19.03 or later_ is a prerequisites but building with 19.03.8 can fail if `runc` is too old as described at https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

**Steps to reproduce the issue:**

Run `make`

**Describe the results you received:**

    [make-compose-plugin 1/1] RUN --mount=target=.     --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,target=/root/.cache/go-build     GOOS=linux     GOARCH=amd64     BUILD_TAGS=e2e,kube     GIT_TAG=v2.3.0     make COMPOSE_BINARY=/out/docker-compose -f builder.Makefile compose-plugin:
    #13 1.157 make: mktemp: Operation not permitted
    #13 1.158 GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X github.com/docker/compose/v2/internal.Version=v2.3.0" -tags e2e,kube -o /out/docker-compose ./cmd
    #13 1.158 make: /bin/sh: Operation not permitted
    #13 1.158 make: *** [builder.Makefile:45: compose-plugin] Error 127

**Describe the results you expected:**

I expected `make` to succeed.

**Output of `docker info`:**

    $ docker info
    Client:
     Debug Mode: false

    Server:
     Containers: 4
      Running: 1
      Paused: 0
      Stopped: 3
     Images: 55
     Server Version: 19.03.8
     Storage Driver: overlay2
      Backing Filesystem: <unknown>
      Supports d_type: true
      Native Overlay Diff: true
     Logging Driver: json-file
     Cgroup Driver: cgroupfs
     Plugins:
      Volume: local
      Network: bridge host ipvlan macvlan null overlay
      Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
     Swarm: inactive
     Runtimes: runc
     Default Runtime: runc
     Init Binary: docker-init
     containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
     runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
     init version: fec3683
     Security Options:
      seccomp
       Profile: default
     Kernel Version: 5.4.65
     Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
     OSType: linux
     Architecture: x86_64
     CPUs: 12
     Total Memory: 31.15GiB
     Name: work
     ID: G4LR:NVXJ:HHBQ:EVVN:KVGZ:7ZSZ:NSHT:UD5D:4MO6:WEAI:U45G:LJ5R
     Docker Root Dir: /var/lib/docker
     Debug Mode: false
     Registry: https://index.docker.io/v1/
     Labels:
     Experimental: false
     Insecure Registries:
      127.0.0.0/8
     Live Restore Enabled: false

    WARNING: No swap limit support

And other components:

    $ runc --version
    runc version 1.0.0-rc10
    commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
    spec: 1.0.1-dev

    $ containerd --version
    containerd github.com/containerd/containerd 1.2.13 7ad184331fa3e55e52b890ea95e65ba581ae3429

**Additional environment details:**

I run Slackware Linux if it matters.

**Comment by ndeloof** [comment]
Did you installed Docker using our system packages as documented on https://docs.docker.com/engine/install/?
Those include our containerd and runc dependencies so should not have such issues

**Comment by ardrabczyk** [comment]
No, I didn't, I installed everything using my OS package manager.

But I'm not asking for help, I'm reporting a bug in the documentation.

**Comment by ndeloof** [comment]
we don't maintain Slackware's `docker` package and as such can't guarantee this one includes the required prerequisites. Better report this to Slackware maintainers

**Comment by ardrabczyk** [comment]
Hmm you really don't want to understand the problem. No matter what method you use to install Docker engine you won't be able to build compose with Docker 19.03.8 as it says BUILDING.md. It's a _bug_ in compose documentation.

**Comment by ndeloof** [comment]
fixed by https://github.com/docker/compose/commit/fbcd7ee8963b8a73f5fa474120973df599c2d81d
