### ISSUE TITLE
Use draft release in GitHub Actions Releaser so that users get the correct release notification email

### ISSUE THREAD

**Issue by ouuan** [docker/compose#9243]
Now Docker Compose is using [GitHub Actions](https://github.com/docker/compose/blob/v2/.github/workflows/release.yaml) to automatically make new releases. However, the release is set to be a pre-release and no changelog is provided.

When a user is watching the repo for new releases, they only get a single notification email which is based on the information when a release is first published, not the later modifications. So the email subject will be like "[docker/compose] Pre-release vx.x.x" and no changelog will be in the email.

I suggest using the `draft` option of [ncipollo/release-action](https://github.com/ncipollo/release-action), so that GitHub Actions can make a draft release instead of publishing it, and the release can be then published after manually editing. Then users will get the correct email notification.

**Comment by ndeloof** [comment]
we manually promote draft releases and generate changelog
see https://github.com/docker/compose/releases/tag/v2.3.1

**Comment by ndeloof** [comment]
Maybe we just need to set `generateReleaseNotes`

**Comment by ouuan** [comment]
> We already use this action, see [https://github.com/docker/compose/blob/v2/.github/workflows/release.yaml#L44](https://github.com/docker/compose/blob/v2/.github/workflows/release.yaml?rgh-link-date=2022-03-08T08%3A07%3A39Z#L44)

I mean the `draft` option, not this action.

**Comment by ouuan** [comment]
> we manually promote draft releases and generate changelog

By "draft release" I mean an unpublished release draft, not a published release with empty text content. On GitHub you can draft a release without publishing it. With `ncipollo/release-action` you can use the `draft` option to do so.

**Comment by ndeloof** [comment]
yep, makes sense
