### ISSUE TITLE
When having multiple docker-compose.yml, killing one service affects others

### ISSUE THREAD

**Issue by guanghwu** [docker/compose#9265]
**Description**
Hello, I recently upgraded docker-compose to 2.3.3 (don't remember my previous version). I have multiple docker-compose.yml and I start them on separate terminals with `docker-compose up`. I don't use `-d` so I can just kill it with ctl+c. Before the upgrade, I could kill one of the docker compose, modify the yml, and re-run it without affecting the other docker compose. However, after the upgrade, killing either docker compose kills the other ones.
The reason I have multiple ymls is because some services take more time to come up. So, splitting into multiple ones makes testing faster.

**Steps to reproduce the issue:**
1. On one terminal run `docker-compose up` under service1
2. One another terminal run `docker-compose up` under service2
3. Ctl+c service2

**Describe the results you received:**
service1 and service2 are killed

**Describe the results you expected:**
If I kill service1, then only service1 should be killed. Same for service2.

**Output of `docker compose version`:**
```
Docker Compose version 2.3.3
```

**Output of `docker info`:**
```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 32
  Running: 14
  Paused: 0
  Stopped: 18
 Images: 16
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: 52b36a2dd837e8462de8e01458bf02cf9eea47dd
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.202
 Operating System: Buildroot 2021.02.4
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.677GiB
 Name: minikube
 ID: YXC6:HDYM:BABN:63LR:43LP:GWIW:IGMX:26A6:W4S7:D766:R2F4:XL4W
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=virtualbox
 Experimental: false
 Insecure Registries:
  10.96.0.0/12
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**
MacOS 12.2.1

[services.tar.gz](https://github.com/docker/compose/files/8224531/services.tar.gz)

**Comment by laurazard** [comment]
Hi @guanghwu, thanks for the report. I can't seem to replicate this, could you try again with a more recent compose version (such as `v2.6.1`)?

**Comment by laurazard** [comment]
No worries! Thanks for checking, I'm closing the issue as it seems to be fixed :)
