### ISSUE TITLE
`docker-compose version --short` changed output from `vX.Y` to `X.Y` between v2.2.3 and 2.3.3

### ISSUE THREAD

**Issue by rfay** [docker/compose#9272]
**Description**

`docker-compose version --short` always used `vX.Y` as its format (for example, `v2.2.3`). In v2.3.3 it uses `X.Y` (without the 'v'), 

```
$ ./docker-compose version --short
2.3.3
```

Since other projects depend on this output, it should remain the same from version to version.

**Steps to reproduce the issue:**

Run `docker-compose version --short`

**Comment by glours** [comment]
@rfay that's to be backward compatible with the python version
https://github.com/docker/compose/pull/9096
