### ISSUE TITLE
Standard website use case examples please

### ISSUE THREAD

**Issue by wernight** [docker/compose#928]
Could at least the basics be a bit better covered? The [example given](http://www.fig.sh/) is a toy example, not a production example. Problems I find with this example are:
- Should [use _uWSGI_ to deploy](https://docs.djangoproject.com/en/1.7/howto/deployment/) in production so that multiple processes are used for example (or PHP-FPM for PHP, etc.) and link to an Nginx frontend for static files etc (also in a Docker).
- Should allow simple _development_, which I found is simple if you mount the code in the volume.
- Should allow _building/testing_ without disrupting the deployed container on the same machine (see #734) and preferably in an environment with custom environment variables so the code can do special things while in dev.
- Should auto-start and restart in prod once deployed (see #872).
- May require some of #846 config format changes

So I'd really wish there could be couple of standard examples for standard simple websites:
- Nginx + PHP-FPM (using Composer and may be some PHP framework) + MySQL
- Nginx + uWSGI + Django (using PIP requirements.txt) + PostgreSQL
- Nginx + NodeJS + MongoDB

Those example should allow simple **development** (edit file and reload page), **build** (run tests), **deploy** for production (restart services, multiple processes, safe...), and **backup** DB.

Note: I've done that for the first two cases by mounting volumes as it's a lot faster to develop (and deploy) than using `ADD . /code`, however I agree that it's less clean and my solution makes it hard to have development build and run tests without impacting deployed Dockers using the same `fig.yml`.

Related to this is a thread on [single vs multi-docker](https://groups.google.com/forum/#!topic/docker-user/gk-oSwgxyo4), which means often either building like a VM (usually using [phusion's buntu](https://github.com/phusion/baseimage-docker) or often [supervisor](http://supervisord.org/) which has [PID 1 problem](http://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/)) or using Docker like executable that run on your mounted volumes.

My hopes are that **Docker Compose** (https://github.com/docker/docker/issues/9694 and https://github.com/docker/docker/issues/9459) starts off people with the right foot.

**Comment by Starefossen** [comment]
Here is our [fig.yml config](https://github.com/Turistforeningen/sherpa-docker/blob/experimental/fig.yml) for the Nginx +  uWSGI + Django + PostgreSQL scenario.

**Comment by wernight** [comment]
@Starefossen Yes it's close to what I've done. I like your `command: /bin/true` trick for "development utilities containers". Some of those example should be linked on the front page, and should explain how to use them. One issue with yours, and mine, if that if the directory name is the same you'll kill your production server if you `fig build`. Another is that it doesn't auto-(re)start.

**Comment by jmlagace** [comment]
The /bin/true is nice but if you are to use that trick you are better off using the tianon/true:latest image. That image does not contain any software whatsoever and is lightweight enough for that purpose.

**Comment by wernight** [comment]
@jmlagace Yes for volume containers, my point of using the trick is for example to use a *Gradle* or a *PhantomJS* container images directly (build/test containers linked to other containers).

**Comment by dnephin** [comment]
I think it would be a good idea to link to more examples. This has come up before with #669

The question of how to make a database container when the table schemas are in code (ex: with django and rails), is asked frequently.

Another django example: https://github.com/rtfd/readthedocs.org/pull/1133

**Comment by dnephin** [comment]
If anyone has examples they'd like featured, please comment in #1951

**Comment by ijc** [comment]
Issue grooming:

https://docs.docker.com/compose/gettingstarted/ has links (at the end) to Django, Wordpress & rails quickstart examples and in general I think the docs/examples story around `docker-compose` is very different to how it was in 2015. I think we can close this one.
