### ISSUE TITLE
docker compose up does not restart running containers

### ISSUE THREAD

**Issue by loclahost** [docker/compose#9282]
**Description**
The command 'docker compose up' no longer updates with newer local image. Previously, if you up:ed with a newer image locally docker compose would restart that service with the new image. I now have to 'docker compose down' to bring all services down first, then 'docker compose up' will start with the new image

**Steps to reproduce the issue:**
1. build a new image with the same image name as that referenced in the compose file
2. docker compose up --detach
3. build a new image with the same image name as that referenced in the compose file
4. docker compose up --detach

**Describe the results you received:**
The images started in step one continues to run

**Describe the results you expected:**
The container running the image built in step 1 should be restarted with the new image from step 3

**Additional information you deem important (e.g. issue happens only occasionally):**
In our dev team it only happens on my Arch Linux machine, those running Docker desktop for Mac appear unaffected. The problem started with the recent updates, probably 2.3.0

**Output of `docker compose version`:**
Docker Compose version 2.3.3

**Output of `docker info`:**
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.0-docker)
  compose: Docker Compose (Docker Inc., 2.3.3)

Server:
 Containers: 17
  Running: 8
  Paused: 0
  Stopped: 9
 Images: 218
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10f428dac7cec44c864e1b830a4623af27a9fc70.m
 runc version: v1.1.0-0-g067aaf85
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.16.14-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.03GiB
 Name: staffan
 ID: HTZT:O75Z:I4WF:WHFP:RF54:HPOG:M44Q:A2VW:A35H:TL36:GYZQ:KWJO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  nexus.netset.se:8086
  127.0.0.0/8
 Live Restore Enabled: false

**Additional environment details:**

**Comment by loclahost** [comment]
Maybe related to #8960?

**Comment by csmith** [comment]
Think this is the same as #9259, which has been fixed but not released

**Comment by loclahost** [comment]
I agree, this is the same as #9259 . Closing this issue and hoping for a 2.3.4 release soon 🙂
