### ISSUE TITLE
v2.3.3 Docker Compose run is Starting Itself Alongside Dependencies

### ISSUE THREAD

**Issue by Seacant** [docker/compose#9289]
**Description**

We have a decently sophisticated web stack running in Docker Compose with `depends_on` relationships. After the recent upgrade to 2.3.3, we started getting errors when running the following command (simplified for this post) to restart part of the stack in interactive debug mode. `docker compose down web && docker compose run --service-ports web`. It seems that when Docker Compose's `run` goes to ensure that its dependencies are started, it's also now starting the downed version of itself, preventing the new container from starting due to its ports being stolen. 

**Steps to reproduce the issue:**
1. docker compose up -d
2. docker compose down web
3. docker compose run --service-ports web

**Describe the results you received:**
```
Error response from daemon: driver failed programming external connectivity on endpoint <redacted>_web_run_<redacted> (<redacted>): Bind for 0.0.0.0:9292 failed: port is already allocated
```
and the original `web` container that we just `down`'d is now running instead of the container we tried to `run`.

**Describe the results you expected:**
The original `web` container should stay `down` and the new `web_run_<sha>` container should be running.

**Additional information you deem important (e.g. issue happens only occasionally):**
We found the following workarounds:
1. Turning off dependency checking (`--no-deps`) fixes it.
2. `docker compose rm -f web` before `run`ing the debug container fixes it.
3. Downgrading to 2.2.3 fixes it.

**Output of `docker compose version`:**

```
Docker Compose version 2.3.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.0-docker)
  compose: Docker Compose (Docker Inc., 2.3.3)

Server:
 Containers: 107
  Running: 31
  Paused: 0
  Stopped: 76
 Images: 274
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10f428dac7cec44c864e1b830a4623af27a9fc70.m
 runc version: v1.1.0-0-g067aaf85
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.26-1-ec2-lts
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 30.99GiB
 Name: <redacted>
 ID: QY7X:OMC5:XB37:7VVD:PCHF:FC3X:LQJG:2VQB:B7CD:YJHM:WCXE:M54J
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by laurazard** [comment]
Hi @Seacant, thanks for the report! I think this should be fixed by https://github.com/docker/compose/pull/9558, but if the issue persists please feel free to create another issue (preferably with a reproducible compose.yaml). Thanks!
