### ISSUE TITLE
QUERY : Is there any way of restarting docker automatically

### ISSUE THREAD

**Issue by NonlinearNimesh** [docker/compose#9295]
Hi, I have a problem of "skipped: maximum number of running instances reached (1) in the apscheduler" and because of this the process got stuck and to restart the process I need to restart the docker, so I was looking for a way to restart the docker automatically after every 24hrs thinking until I resolved the above mentioned issue.

So, is there a way i can restart the docker automatically after every 24 hrs 

Thanks.

**Comment by ndeloof** [comment]
Closing as unrelated to docker compose.
