### ISSUE TITLE
Examples of production deployment

### ISSUE THREAD

**Issue by beorn** [docker/compose#93]
I love how fig simplifies "development deployment / orchestration", but all systems eventually need to be deployed to a production environment, and I couldn't find any info on recommended ways to do that.  My worry is of course having to use a completely different orchestration system for production.

It would be really useful to also have an example of how you can deploy to, e.g., Orchard or a Docker running on an AWS Ubuntu box - ideally, of course, reusing as much of the fig.yml orchestration info as possible.

If you DON'T want fig to be used for production deployment / orchestration, then it would be nice to say so up front.  (And even nicer to point users to recommended projects for that.)

**Comment by wernight** [comment]
Adding to this, fig is missing Docker `-p` / `--publish` commands which are not just to have near zero downtime deployment, but a necessity to have staging environment. Current without that, one cannot simply link a Fig/Docker port to for Prod and another for Staging, or even just run system tests in a completely private port environment, and only expose the port when test pass.

**Comment by dnephin** [comment]
There are a bunch of related tickets about deployment and production use. I've linked them all up to #1786. I'm going to close this issue so we can concentrate the discussion in that ticket.
