### ISSUE TITLE
Fig could pull and build images in parallel to speed things up.

### ISSUE THREAD

**Issue by ilonajulczuk** [docker/compose#931]
I use fig in development and in tests. CI doesn't use caching to make sure that we don't use outdated versions, as a result it always builds and pulls the images it needs. The whole process could be much faster if fig did this preparation process in parallel.

Could it be possible to add --parallel flag or something? I've looked into the code and it looks like anyone though about concurrency there and it will involve some bigger changes. Maybe it would be better to have standalone extension?

**Comment by thaJeztah** [comment]
I'm don't think Docker *itself* will perform parallel pulls, so this will depend on changes in Docker upstream.

Search the docker issue-tracker for that, because I think this has come up a few times, but isn't possible at this moment for various reasons.

**Comment by dnephin** [comment]
Docker itself has issues with parallel builds, see https://github.com/docker/docker/issues/9656. I don't think having fig do it in parallel would improve build time.

Doing pull in parallel might make it faster.

**Comment by aanand** [comment]
Yeah - although a single pull already performs HTTP requests in parallel (since there are almost always quite a few layers to fetch), so I don't imagine there'd be much of a gain there either.

**Comment by bfirsh** [comment]
Thanks for the suggestion @ilonajulczuk! I have rolled it into #1652.
