### ISSUE TITLE
Critical regression: compose 2.3.0 and up removes external volumes with down -v, leading to data loss

### ISSUE THREAD

**Issue by chrkr** [docker/compose#9313]
**Description**

From compose 2.3.0 onwards, `docker compose down -v` _also_ removes volumes configured as `external: true`!

This only seems to happen when `docker compose down -v` is called with no explicit project name.
In case `docker compose -p <project_name> down -v` is called, the external volume is _not_ deleted, regardless of whether `docker compose` was called in the directory where the compose file is located or not. Also explicitly using `-f compose.yaml` does not change this outcome: with `-p` the volume is left alone, without `-p` it is deleted.

**Steps to reproduce the issue:**
1. Create a compose file with a service with an external volume e.g.:
```
services:
  nginx:
    image: nginx
    volumes:
      - data:/data

volumes:
  data:
    external: true
    name: external_volume
```
2. Create the volume `docker volume create external_volume`
3. `docker compose up -d`
4. `docker compose down -v`

**Describe the results you received:**
The volume `external_volume` _has been deleted by the `docker compose down -v` command_, leading to unexpected data loss. Specifically, using external volumes is a documented method to _prevent_ the volume from being deleted when `docker compose down -v` is called.

**Describe the results you expected:**
The volume `external_volume` is left in place when `docker compose down -v` is called.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens from 2.3.0 onwards.

**Output of `docker compose version`:**

```
Docker Compose version v2.3.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 40
  Running: 0
  Paused: 0
  Stopped: 40
 Images: 267
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.39GiB
 Name: docker-desktop
 ID: OEKS:HPDE:THGY:AFJH:EZBR:H4NU:MJE6:SASE:YXWF:UYBY:M26B:H4JM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**

**Comment by glours** [comment]
This was fixed in #9281
