### ISSUE TITLE
not the same port forwarding for `up` and `run` commands

### ISSUE THREAD

**Issue by itsNikolay** [docker/compose#932]
```shell
$ docker-compose ps 
      Name                    Command               State             Ports          
------------------------------------------------------------------------------------ 
myapp_web_1        /bin/sh -c tail -f /dev/null     Up       0.0.0.0:3000->3000/tcp  
myapp_web_run_53   bundle exec rails s -b0.0. ...   Up       3000/tcp
``` 

- [not working] `Ports` column has a different values, thus a page is **not available** on `http://localhost:3000` when running `$ docker-compose run web rails server -b '0.0.0.0'`
- [working] But if run `docker-compose up` with config line `command: bundle exec rails server -b '0.0.0.0' ` in `docker-compose.yml` the page is **available**.

Probably if `Ports` **will have the same values we will able to get page through running**  `$ docker-compose run web rails server -b '0.0.0.0'` 
And `localhost:3000` will be able to visit. 

P.S.
[my Docker & docker-compose.yml](https://gist.github.com/itsNikolay/65f60882876b6c6123a7)
I run on Ubuntu and do not have `boot2docker`
In first case I am able to visit page just through `http://172.17.0.156:3000/`

**Comment by Starefossen** [comment]
You forgot to add the `--service-ports` flag to your `docker-compose run` command as documented in the [cli documentation](https://github.com/docker/fig/blob/master/docs/cli.md):

```
compose run --service-ports web rails server -b '0.0.0.0'
```

This behaviour is by intention since the compose run command is primarily for running a one-off commands which should not expose any ports.

**Comment by itsNikolay** [comment]
@Starefossen thanks for helping
but running the command I get
```shell
$ docker-compose run --service-ports web bundle exec rails s -b '0.0.0.0' 
Cannot start container 8b3a6b22dca6856d98d1730455a9f092d77e1c4decb77e66f68cced87a19527a:
 Bind for 0.0.0.0:3000 failed: port is already allocated
```

**Comment by Starefossen** [comment]
Yes, this is why it is not enabled by default! You have probably already run `docker-compose up`. You can't bind multiple times to the same port.

**Comment by dnephin** [comment]
This issue was answered a while ago, going to close.

Thanks @Starefossen
