### ISSUE TITLE
COMPOSE_IGNORE_ORPHANS doesn't work for docker-compose run

### ISSUE THREAD

**Issue by lobabob** [docker/compose#9323]
# Description

The `COMPOSE_IGNORE_ORPHANS` env var works for `docker-compose up` but not for `docker-compose run`

Orphan warning is shown:

```
$ cat .env
COMPOSE_IGNORE_ORPHANS=1
$ docker-compose run --rm nginx
WARN[0000] Found orphan containers ([***, ***, ***]) for this project. If you removed or renamed this service in your
 compose file, you can run this command with the --remove-orphans flag to clean it up.
```

I've run this with `COMPOSE_IGNORE_ORPHANS` set to `true` and `True` as well, both failed.

Also fails when set through env var:

```
$ COMPOSE_IGNORE_ORPHANS=1 docker-compose run --rm nginx
WARN[0000] Found orphan containers ([***, ***, ***]) for this project. If you removed or renamed this service in your
 compose file, you can run this command with the --remove-orphans flag to clean it up.
```

# Context information (for bug reports)

```
$ docker-compose version
Docker Compose version v2.3.3
```

```
$ docker --version
Docker version 20.10.13, build a224086
```

```
$ docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:08:44 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

<img width="465" alt="image" src="https://user-images.githubusercontent.com/5687933/160726783-71138295-e54a-44cd-a8aa-d0bf498bd27d.png">

# Steps to reproduce the issue

1. Add COMPOSE_IGNORE_ORPHANS=1 to the .env file
2. Run any docker-compose run command with orphaned containers existing under your project name

Observed result
`WARN[0000] Found orphan containers ([***, ***, ***]) for this project....` warning is shown.

Expected result
No warning is shown.

Additional information
macOS, docker-compose installed via auto-updating Docker for Mac to the recent version

**Comment by henriquemattos** [comment]
This is also happening with Docker for macOS. Running my `node` container with `npm run build` warns of orphan containers and suggests to run with `--remove-orphans`:
```
$ docker compose -f docker-compose.tools.yml run --rm node npm run build 
WARN[0000] Found orphan containers ([*** *** *** ***]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
```
But running with the command fails with **unknown flag**:
```
$ docker compose run --rm --remove-orphans node npm run build
unknown flag: --remove-orphans
```
Here are the versions I'm using
```
$ docker compose version  
Docker Compose version v2.4.1
```
```
$ docker --version        
Docker version 20.10.14, build a224086
```
```
$ docker version
Client:
 Cloud integration: v1.0.23
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:49:20 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.7.1 (77678)
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:44 2022
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

<img width="872" alt="Screenshot 2022-05-04 at 11 24 40" src="https://user-images.githubusercontent.com/2782214/166664333-dc43b934-6d09-4577-a8f6-f30e1683788e.png">

**Comment by matthewarmand** [comment]
`run` doesn't support the `--remove-orphans` flag, which is probably why the env var isn't working. But it DOES report the orphans message, which says "run this command with..." and is confusing.

I made a comment over at this somewhat related issue that at least the message should be improved, if not support for `--remove-orphans` added to all the commands which trigger that message: https://github.com/docker/compose/issues/9718#issuecomment-1209448445

**Comment by aschleifer** [comment]
> `run` doesn't support the `--remove-orphans` flag, which is probably why the env var isn't working. But it DOES report the orphans message, which says "run this command with..." and is confusing.

This doesn't make much sense. According to https://docs.docker.com/compose/reference/envvars/#compose_ignore_orphans the flag will disable the detection or orphans, so this should work on any command that can detect them. For me it doesn't work on `docker compose run <service>`.
