### ISSUE TITLE
Newly Built Container Ignored

### ISSUE THREAD

**Issue by iamnande** [docker/compose#9328]
**Description**

When I use the `--build` flag, the newly built container can be seen in the docker dashboard and images list on the CLI but is not being utilized when I run `docker compose up --build --detach`.

Previously this worked. There could have been a bug that allowed it to work that was fixed, or this is a new bug.

FWIW there is a work around to kick a specific service using the `--force-recreate <service>`. The goal here is to be able to restart (and rebuild) a specific service while not having to recreate a database.

**Steps to reproduce the issue:**
1. `docker compose up --build --detach --quiet-pull`

**Describe the results you received:**
The previously built container ID was still running in the compose environment.

**Describe the results you expected:**
The newly built container, built using `--build`, to be running in the compose environment.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a recent issue.

**Output of `docker compose version`:**

```
Docker Compose version v2.3.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 10
  Running: 7
  Paused: 0
  Stopped: 3
 Images: 77
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: ULFD:ONVK:MKZN:LVJF:47RD:MEDP:QITD:67VR:BIJ3:EHWP:B6ZA:DDYX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by ndeloof** [comment]
This has been fixed by https://github.com/docker/compose/pull/9261
