### ISSUE TITLE
How to create a fuse in pod, and let other pods use it?

### ISSUE THREAD

**Issue by codeboytj** [docker/compose#9337]
**Description**

I mount a fuse in pod A, and share it to pod B by use the same volume. But when pod B write files to the volume, pod A can not receive the write event.

**Steps to reproduce the issue:**
1. create volume fuse-log in docker-compose
2. create service A use volume fuse-log:
```
    volumes:
      - fuse-log:/data/fuselog
```
3. create service B use volume fuse-log too:
```
    volumes:
      - fuse-log:/data/fuselog
```
4. When I write something in /data/fuselog in pod A, I can receive the write event in fuse
5. But when I write something in /data/fuselog in pod B, I can not receive the write event in fuse

**Describe the results you received:**
When I write something in /data/fuselog in pod B, I can not receive the write event in fuse

**Describe the results you expected:**
When I write something in /data/fuselog in pod B, I expect I can receive the write event in fuse

**Output of `docker compose version`:**

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 14
  Running: 3
  Paused: 0
  Stopped: 11
 Images: 50
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.939GiB
 Name: docker-desktop
 ID: 3K67:YC4Q:GTOM:6TPK:QFZU:2XLH:EEEG:7GOP:QLIL:FQCD:WFLZ:ADUS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by ndeloof** [comment]
I assume by "write event" you mean [inotify](https://man7.org/linux/man-pages/man7/inotify.7.html)?

Don't you have the same issue with plain containers sharing a volume, without using docker compose to manage them? In such case this is a docker (desktop?) limitation, not a compose one

**Comment by codeboytj** [comment]
> 

@ndeloof Yes, same issue with plain containers. T_T
