### ISSUE TITLE
not respecting --insecure-registry

### ISSUE THREAD

**Issue by razic** [docker/compose#934]
hey i created a new machine with `machine create dev -d virtualbox`, then `machine ssh dev` to ssh to the machine and change the `/var/lib/boot2docker/profile` to contain `--insecure-registry docker.corp.adobe.com` then ran `compose up -d` but got an error about https/insecure registry. however, i can `$(machine env dev) && docker pull docker.corp.adobe.com/typekit/gladius` with no problem. seems like `compose` is not respecting the extra options in `/var/lib/boot2docker/profile`.

**Comment by razic** [comment]
any ideas here anyone?

**Comment by dnephin** [comment]
What is `/var/lib/boot2docker/profile`? I'm not familiar with it.  compose does support `--allow-insecure-ssl` for both `up` and `pull`.

**Comment by razic** [comment]
@dnephin

machine uses `boot2docker` as the ISO for it's vms.... `boot2docker` has a configuration file at `/var/lib/boot2docker/profile` that you can add to configure the docker daemon. for example, here's the default `/var/lib/boot2docker/profile` file after creating a fresh `machine`:

```
EXTRA_ARGS='--tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlskey=/var/lib/boot2docker/server-key.pem --tlscert=/var/lib/boot2docker/server.pem -H tcp://0.0.0.0:2376'
CACERT=/var/lib/boot2docker/ca.pem
SERVERCERT=/var/lib/boot2docker/server-key.pem
SERVERKEY=/var/lib/boot2docker/server.pem
DOCKER_TLS=no
```

**Comment by dnephin** [comment]
`--insecure-registry` was deprecated (in 1.3.x I think?) because it wasn't actually doing the right thing, so I think we can close this issue now

**Comment by dnephin** [comment]
To clarify, it wasn't actually necessary, but was causing failures, so we removed the unnecessary work that it was doing, so the flag isn't needed anymore.
