### ISSUE TITLE
docker-compose run output cannot be retrieved using docker-compose logs

### ISSUE THREAD

**Issue by hazmeister** [docker/compose#9347]
**Description**
The behaviour of `docker logs` and `docker-compose logs` differs when using the run command.  The output will always be retrievable for from `docker logs`, but not when using `docker-compose logs`.

**Steps to reproduce the issue:**
1. Create the following docker-compose.yml
```yml
version: '3.0'
services:
  test:
    image: hello-world
```
2. `docker-compose run test`
3. `docker-compose logs test`

**Describe the results you received:**
No logs will be printed to the console

**Describe the results you expected:**
The hello world message should be printed

**Additional information you deem important (e.g. issue happens only occasionally):**
Find the container ID from `docker ps` and pair it with `docker logs <id>` and you will see the full log output.  When using `docker-compose up test`, the logs can be retrieved by either method.

**Output of `docker compose version`:**

```
Docker Compose version v2.4.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: 84113eef6fc27af1b01b3181f31bbaf708715301
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.268-205.500.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.914GiB
 Name: ip-10-170-29-166.eu-west-2.compute.internal
 ID: A3DV:Y7NS:ZN7U:HQ7O:LPFG:2B3A:N2CO:JAJY:25YT:57ND:45WV:Y6BG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details:**

**Comment by ndeloof** [comment]
`docker-compose logs` only applies to application when ran using `docker-compose up`. 
`docker-compose run` create "one-off" containers, not services, and those are ignored by other commands (so they appear as "orphaned" containers)

**Comment by glours** [comment]
As @ndeloof mentionned, this is the expected behavior, so we'll close the issue
