### ISSUE TITLE
V2: Does `docker compose -f` no longer have an autocomplete feature?

### ISSUE THREAD

**Issue by JackHewson** [docker/compose#9358]
**Description**
I used docker-compose (v1.xx.x) for long time, and liked to have multiple .yml files in one directory.
I used the bash "autocomplete" feature for the command `docker-compose -f ` to list all the yml files.

**Steps to reproduce the issue:**
1. Fresh install docker compose V2
2. type `docker compose -f ` and press the TAB key 

**Describe the results you received:**
(nothing happens)

**Describe the results you expected:**
There should be list of all files within the directory.

**Output of `docker compose version`:**
```
Docker Compose version v2.4.1
```

**Comment by ndeloof** [comment]
Support for completion on CLI plugin (as `docker <space> compose`) requires some architecture changes
work in progress. see https://github.com/docker/cli/pull/3429
