### ISSUE TITLE
How many times HealthCheck will restart container ? Infinite time unless becomes healthy or once twice ?

### ISSUE THREAD

**Issue by vandanpathak-gep** [docker/compose#9359]
How many times HealthCheck will restart container ? Infinite time unless becomes healthy or once twice ?

**Comment by thaJeztah** [comment]
it continues checking, but will mark the container as "unhealthy" after the number of consecutive failures reaches `--health-retries`:

```bash
docker run --help | grep 'health'
      --health-cmd string              Command to run to check health
      --health-interval duration       Time between running the check (ms|s|m|h) (default 0s)
      --health-retries int             Consecutive failures needed to report unhealthy
      --health-start-period duration   Start period for the container to initialize before starting health-retries countdown (ms|s|m|h) (default 0s)
      --health-timeout duration        Maximum time to allow one check to run (ms|s|m|h) (default 0s)
      --no-healthcheck                 Disable any container-specified HEALTHCHECK
```

Documentation on this can definitely be improved (see https://github.com/docker/docker.github.io/issues/3282, which also has some links to examples), but the default is `0` (or

https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/api/types/container/config.go#L32-L34


For example, this container (health command is `exit 1` so always fails) will perform its first health check after 10 seconds, then retry every 10 seconds.

```bash
docker run -d --name=example \
--health-cmd='exit 1' \
--health-interval=10s \
--health-retries=3 \
nginx:alpine
```

When starting, the health-status will show "starting";

```bash
docker inspect example --format '{{ json .State.Health}}' | jq .
{
  "Status": "starting",
  "FailingStreak": 0,
  "Log": []
}
```

After 10 seconds, the first health-check is performed, and if that passes, the container is marked as "healthy" (which in this case never happens).

```bash
docker inspect example --format '{{ json .State.Health}}' | jq .
{
  "Status": "starting",
  "FailingStreak": 1,
  "Log": [
    {
      "Start": "2022-04-06T19:14:00.5101148Z",
      "End": "2022-04-06T19:14:00.578156Z",
      "ExitCode": 1,
      "Output": ""
    }
  ]
}
```

After that, it counts consecutive failures, and if it has 3 failures in a row, it marks the container as unhealthy:

```bash
docker inspect example --format '{{ json .State.Health}}' | jq .
{
  "Status": "unhealthy",
  "FailingStreak": 4,
  "Log": [
    {
      "Start": "2022-04-06T19:19:13.8276373Z",
      "End": "2022-04-06T19:19:13.90637Z",
      "ExitCode": 1,
      "Output": ""
    },
    {
      "Start": "2022-04-06T19:19:23.8895957Z",
      "End": "2022-04-06T19:19:23.9808613Z",
      "ExitCode": 1,
      "Output": ""
    },
    {
      "Start": "2022-04-06T19:19:33.9904024Z",
      "End": "2022-04-06T19:19:34.0785568Z",
      "ExitCode": 1,
      "Output": ""
    },
    {
      "Start": "2022-04-06T19:19:44.089887Z",
      "End": "2022-04-06T19:19:44.1859828Z",
      "ExitCode": 1,
      "Output": ""
    }
  ]
}
```

**Comment by vandanpathak-gep** [comment]
Thanks @thaJeztah , Yes unless Health Probe URL becomes healthy it will mark container as unhealthy. I am using .Net Code and i have below tag in my manifest file and its deployed as docker container . 
<HealthConfig IncludeDockerHealthStatusInSystemHealthReport="true"
		      RestartContainerOnUnhealthyDockerHealthStatus="true" 
		      TreatContainerUnhealthyStatusAsError="true" />
Hence due to above tag , Azure Service Fabric will automatically restart my unhealthy container. Hence my question is "Is there any Limit of No. of times my container will get restarted or Eg. After 3 Auto Restart, It will stop restart to avoid Cyclic Restarting.

**Comment by ndeloof** [comment]
Docker compose does not restart services based on healthcheck status, neither does the docker engine. This is a feature provided by Azure Service Fabric platform.
