### ISSUE TITLE
docker-compose health check passed, still unhealthy

### ISSUE THREAD

**Issue by sshallow** [docker/compose#9367]
> *`condition` was removed compose spec in versions 3.0 to 3.8 but is now back!  Using version of the compose spec v3.9, you can use `condition` as an option in [long syntax form of `depends_on`][1].*

I use docker compose to start MySQL and Java Web projects,
The startup of JavaWeb needs to rely on MySQL to create complete data, so I use [healthcheck][1]

But there is a problem with the ` healthcheck` of mysql, this is my `docker-compose`

```
# docker-compose.yml
version: "3.9"  

services:

  mysql:
    build:
      context: ./mysql
    command: [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1'
    ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fuba-db
      MYSQL_ROOT_PASSWORD: fb123456
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SELECT * FROM factor_header' fuba-db "
      interval: 1s
      timeout: 3s
      retries: 3

  redis:
    build:
      ......

  nginx:
    build:
      ......

  fubaquant:
    build:
      context: ./webapps
    ports:
      - "8080:8080"
    volumes:
      - /mnt/java/jar:/home/ruoyi  #jar包
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
```

The statement in error is:

````
test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SELECT * FROM factor_header' fuba-db "
````

The console outputs :

```
pro-mysql-1      | 2022-04-07T08:16:54.203710Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
container for service "mysql" is unhealthy
```
*Since fubaquant depends_on mysql healthcheck, fubaquant is not started either*

The health check log of the mysql container is:

[![docker-compose up][2]][2]

I checked th healthcheck log of mysql and it's also healthy

[![mysql  log][3]][3]

thanks for any help

  [1]: https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1
  [2]: https://i.stack.imgur.com/DXrwH.jpg
  [3]: https://i.stack.imgur.com/MDxEm.jpg

**Comment by ndeloof** [comment]
You configured health check to only allow 3 retries, 1 second intervals. While compose is starting your app, mysql service has not reached the healthy state within this 3s delay, so compose stops and report this error. Try to increase this delay or number of retries.

**Comment by sshallow** [comment]
@ndeloof Thanks !!!   I increased the number of retries and it's work!
 I'm so stupid
