### ISSUE TITLE
show cache images id at build time?

### ISSUE THREAD

**Issue by jan-bar** [docker/compose#9372]
**Description**
Sometimes I want to start a container based on a cached images to debug the environment at that time. The images id shown by the arrow in the figure below

![image](https://user-images.githubusercontent.com/14202095/162567833-dc0e342c-4ef3-48c4-b3d7-cecdeebe4607.png)

I generally use the following method to start the container from the built cache image to verify the environment or script problem at that time.

```sh
docker run --rm -it e30afa7acd69 sh
```
The new version is displayed as follows, I can't easily find the cache images id.

![image](https://user-images.githubusercontent.com/14202095/162568115-245d4fd2-d78f-41dc-8dd0-26301ea5c43c.png)

**Comment by thaJeztah** [comment]
The classic builder used images as build cache; when building images with BuildKit, the build cache is separate from the image store (no images are created for intermediate steps).

While this has many advantages, one of the disadvantages (as you point out) is that it may be more difficult to debug intermediate steps.

This is not something that can be fixed in compose, but there's a roadmap ticket https://github.com/docker/roadmap/issues/97 (leave a comment and/or upvote to get it prioritized), and a proposal in the Moby project to improve this; https://github.com/moby/moby/issues/40887 (as well as some tickets in the BuildKit project, linked from that ticket)

**Comment by jan-bar** [comment]
> The classic builder used images as build cache; when building images with BuildKit, the build cache is separate from the image store (no images are created for intermediate steps).
> 
> While this has many advantages, one of the disadvantages (as you point out) is that it may be more difficult to debug intermediate steps.
> 
> This is not something that can be fixed in compose, but there's a roadmap ticket [docker/roadmap#97](https://github.com/docker/roadmap/issues/97) (leave a comment and/or upvote to get it prioritized), and a proposal in the Moby project to improve this; [moby/moby#40887](https://github.com/moby/moby/issues/40887) (as well as some tickets in the BuildKit project, linked from that ticket)

Thank you very much for your reply, it answered my question, I will use the old version for now. I haven't delved into it yet, looking forward to a better solution

**Comment by thaJeztah** [comment]
> Thank you very much for your reply, it answered my question, I will use the old version for now. I haven't delved into it yet, looking forward to a better solution

You're welcome! In general, I'd recommend using BuildKit, not the classic builder; there's been quite some improvements in the build-process overall (both on performance, and features). Error reporting on failures has improved overall (to assist in debugging), although more work will be done in that area.

If you have specific examples where BuildKit didn't address your use-case, I'd highly recommend to comment on https://github.com/docker/roadmap/issues/97, and (if possible) provide details that may help the team design improvements. I should also mention this ticket; which is more specific on metadata-only changes (such as `ENV` or `ARG` instructions) https://github.com/moby/buildkit/issues/2416

-----

Slightly off-topic, but I noticed you're using `ENV` to set `HTTP_PROXY` values. In general, we recommend to not use an `ENV` for these, as doing so "bakes" the proxy settings in the image, which means that the image can _only_ be run in an environment where the given proxy is available (making the image non-portable).

If the proxy is only needed when _building_ the image, you can use the pre-defined build-args for this purpose; https://docs.docker.com/engine/reference/builder/#predefined-args

You can configure the docker CLI to automatically set these build args / environment variables (both when building and when running the image); see https://docs.docker.com/network/proxy/#configure-the-docker-client

**Comment by jan-bar** [comment]
> > Thank you very much for your reply, it answered my question, I will use the old version for now. I haven't delved into it yet, looking forward to a better solution
> 
> You're welcome! In general, I'd recommend using BuildKit, not the classic builder; there's been quite some improvements in the build-process overall (both on performance, and features). Error reporting on failures has improved overall (to assist in debugging), although more work will be done in that area.
> 
> If you have specific examples where BuildKit didn't address your use-case, I'd highly recommend to comment on [docker/roadmap#97](https://github.com/docker/roadmap/issues/97), and (if possible) provide details that may help the team design improvements. I should also mention this ticket; which is more specific on metadata-only changes (such as `ENV` or `ARG` instructions) [moby/buildkit#2416](https://github.com/moby/buildkit/issues/2416)
> 
> Slightly off-topic, but I noticed you're using `ENV` to set `HTTP_PROXY` values. In general, we recommend to not use an `ENV` for these, as doing so "bakes" the proxy settings in the image, which means that the image can _only_ be run in an environment where the given proxy is available (making the image non-portable).
> 
> If the proxy is only needed when _building_ the image, you can use the pre-defined build-args for this purpose; https://docs.docker.com/engine/reference/builder/#predefined-args
> 
> You can configure the docker CLI to automatically set these build args / environment variables (both when building and when running the image); see https://docs.docker.com/network/proxy/#configure-the-docker-client

Thank you again for the study materials, I will continue to research.
