### ISSUE TITLE
centos host.docker.internal

### ISSUE THREAD

**Issue by brinkqiang** [docker/compose#9374]
host.docker.internal has direct support on mac.
Why can't it work on centos. You have to write a script yourself to achieve it.
This seems very unprofessional.
Is it difficult to implement the corresponding non-mac platform?

**Comment by ndeloof** [comment]
`host.docker.internal` is a feature offered by Docker Desktop. Could probably get the same using Docker Desktop Linux, but not with raw docker engine.

Also, this has no relation with docker compose, please report on adequate repository
