### ISSUE TITLE
docker-compose.yml not passing variables from shell to container

### ISSUE THREAD

**Issue by MartinsSmirnovs** [docker/compose#9387]
According to [docker-compose documentation](https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers):
> You can pass environment variables from your shell straight through to a service’s containers with the [‘environment’ key](https://docs.docker.com/compose/compose-file/compose-file-v3/#environment) by not giving them a value

I am trying to pass `UID` bash shell's variable to be container's environment variable using docker-compose `environoment` key. Here is my simple example:

_docker-compose.yml_
```
version: "3.9"

services:
  demo:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
    - UID
```

_Dockerfile_
```
FROM alpine

RUN echo $UID
```

After executing `docker-compose build --no-cache demo` we should see `UID` value printed at step two of the build, however, after executing the command, we see only empty line being printed.

```
Building demo
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM alpine
 ---> c059bfaa849c
Step 2/2 : RUN echo $UID
 ---> Running in 6a8fad083581

Removing intermediate container 6a8fad083581
 ---> 1009ffd514ae
Successfully built 1009ffd514ae
Successfully tagged test_docker_compose_demo:latest
```

**Output of `docker compose version`:**

```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 86
  Running: 0
  Paused: 0
  Stopped: 86
 Images: 2962
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-169-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 6.805GiB
 Name: my-vm
 ID: OPRD:DNBV:S56K:FYDS:GPII:HGRR:J27I:7WID:PANC:4FQC:OCC4:NRWU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by ndeloof** [comment]
`environment` set container environment variables user _at runtime_ not _build time_
What you are looking for is build args, see https://aggarwal-rohan17.medium.com/docker-build-arguments-and-environment-variables-1bdca0c0ef92

```yaml
services:
  demo:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - UID
```

```
FROM alpine
ARG UID
RUN echo $UID
```

**Comment by MartinsSmirnovs** [comment]
That explains why my example did not work as expected.
However, it does not solve my problem I am dealing with - to pass `UID` from host's shell to Docker's build phase dynamically. That also explains why there are so many requests regarding `UID` and `GID` passing to Dockerfile from `docker-compose.yml` in https://github.com/docker/compose/issues/4081. Probably the best option for now will be to pass `UID` using `docker-compose build --build-arg`
Thanks for your fast response!

**Comment by ndeloof** [comment]
@Jeff-Tian `docker compose build --build-arg ...` then `docker compose up`
`up --build` is just a shortcur for the simpler use-cases
