### ISSUE TITLE
[Proposal] Rewrite in go

### ISSUE THREAD

**Issue by schickling** [docker/compose#94]
First of all, thanks a lot for this awesome package and all the time you guys put into building it. I appreciate that a lot!

I'm aware my suggestion is kinda daring, nonetheless I want to put it up for discussion. Almost all docker related projects (and of course docker itself) are written in go-lang. [boot2docker](https://github.com/steeve/boot2docker) for example also takes this step. I think I don't have to list the advantages you have using go. But the main advantage in my opinion is that you don't have any dependencies such as `pip`.

As I said, this is just a **suggestion**. If you don't consider a rewrite in go, simply close this issue. I won't be sad :smiley_cat:

**Comment by dnephin** [comment]
Now that https://github.com/docker/libcompose exists, I think we can close this issue.

**Comment by d11wtq** [comment]
Oooh, very nice. Is the long term plan for compose to built into the docker binary as a sub-command? E.g. `docker compose up`.

**Comment by ybogdanov** [comment]
Today we also open sourced this one https://github.com/grammarly/rocker-compose
