### ISSUE TITLE
How to sent notification when a container is exit on it's own

### ISSUE THREAD

**Issue by fzn0x** [docker/compose#9404]
Sometimes a container getting exit from it's own, how to prevent that with something (say like notifications) so we can re-up the container? 

Is there a way to solve this anomaly? Thank you.

**Comment by maxcleme** [comment]
@fzn0x 

You might want to look at the following resources to achieve what you want:

https://docs.docker.com/compose/compose-file/#restart

https://docs.docker.com/engine/reference/builder/#healthcheck

https://docs.docker.com/engine/reference/commandline/events/

**Comment by fzn0x** [comment]
> @fzn0x
> 
> You might want to look at the following resources to achieve what you want:
> 
> https://docs.docker.com/compose/compose-file/#restart
> 
> https://docs.docker.com/engine/reference/builder/#healthcheck
> 
> https://docs.docker.com/engine/reference/commandline/events/

Thanks, healthcheck looks good!
