### ISSUE TITLE
Run docker-compose with differents commands

### ISSUE THREAD

**Issue by henriqueholtz** [docker/compose#9406]
I need run `docker-compose up` with some differents commands (that replaced the default command of the Dockerfile)

How to run docker-compose with different command without duplicate docker-compose file?

I need something as `docker-compose up --command "yarn dev-ssl"`

To resolve this, I need manually change this, or duplicate docker-compose file.

![image](https://user-images.githubusercontent.com/51380783/164210262-b0f5ffee-cb66-4bc4-bd9d-dc40ddcbf975.png)

[My repo-of-example](https://github.com/henriqueholtz/Holtz_NextAuth)

Thanks!

**Comment by XF-FW** [comment]
This would still be a nice to have. The alternative is either multiple docker-compose files or generating them on the fly, which is less than ideal.
