### ISSUE TITLE
Support for uppercase or underscores or any separator in container names

### ISSUE THREAD

**Issue by Vrakfall** [docker/compose#941]
I saw 1 or 2 issues talking about supporting dashes or dots in container names and some arguments why it cannot be done for now but I found nothing about uppercase or underscores.

In fact, the problem in which I often find myself stuck is that I cannot separate different words in a single container name (in the `fig.yml`). Perhaps I'm mistaking or I didn't find the right convention to name my containers but I'm currently forced to use names like `mysqldatacontainer` when I would like to call them more like `mysqlDataContainer` or even `mysql_data_container`.

If I use some uppercase, I end up with this error:
```
Invalid repository name (appname_mysqlDataContainer), only [a-z0-9-_.] are allowed
```
and this one if I use a `_` or a `-`:
```
Invalid service name "mysql_data_container" - only [a-zA-Z0-9] are allowed
```

That's why I'm proposing to allow at least one more character or to allow the uppercase in order to make long names more readable (if I didn't miss any way of doing it). We could even use it later as a coding convention.

What do you guys think about that ?

**Comment by dnephin** [comment]
The "Invalid repository name" error is coming from dockerd, not fig. see #655 , https://github.com/docker/docker/commit/aabba9801a63228bb2e5144c8688b60e4d429ac2

fig/compose should be able to support other characters once docker has support for labels https://github.com/docker/docker/pull/9882

**Comment by Vrakfall** [comment]
docker/docker#9882

**Comment by Vrakfall** [comment]
docker/docker#9882

**Comment by Vrakfall** [comment]
Thank you for your quick answer !

Good thing if it's going to be implemented soon !

Should I leave the issue open ?

**Comment by thaJeztah** [comment]
Happy to inform that https://github.com/docker/docker/pull/9882 was merged and will be included in the upcoming 1.6 release of Docker.

Also, I think there are currently a number of related issues in this area (https://github.com/docker/compose/issues/652, https://github.com/docker/compose/issues/869, https://github.com/docker/compose/issues/941 among others); perhaps the discussion should be focussed on the global proposal https://github.com/docker/compose/issues/1066 (but that's just a suggestion)

**Comment by Vrakfall** [comment]
Oh, nice thing, thank you.

Waiting for the `1.6` version to test it and then I'll close this issue.

**Comment by thaJeztah** [comment]
> Waiting for the 1.6 version to test it and then I'll close this issue.

Well, it still depends on changes in compose itself, but the path is now clear to start working on that.

**Comment by aanand** [comment]
Closing in favour of https://github.com/docker/compose/issues/1519
