### ISSUE TITLE
Give Compose mascot a name

### ISSUE THREAD

**Issue by ndeloof** [docker/compose#9417]
**Description**
In 2013 we asked the growing Docker community to [choose a name](https://www.docker.com/blog/call-me-moby-dock/) for the project mascot, and "Moby Dock" has since be the name of our beloved whale.

Compose's octopus mascot doesn't have a name. With Docker Compose v2 announced for General Availability, it's time we make Compose a first-class citizen! And as an open-source project, we want community to be the one driving this decision

**update** to avoid conflict with living or historical persona, we don't accept real name, only will select creative invented name based on project context and/or mascot's octopus kind

**How does it work**
Please 
- add your suggestions to this issue as comments
- vote for your preferred names using 👍  or 👎 reactions on those comments.

_This issue is moderated: any irrelevant content will be deleted, thanks for your understanding_

![IMG_5419 - copie](https://user-images.githubusercontent.com/132757/165756068-dcff1df0-5aea-43a9-be4e-6f8050ffc4ae.jpg)

**Comment by ndeloof** [comment]
Paul (as https://en.wikipedia.org/wiki/Paul_the_Octopus)

**Comment by ndeloof** [comment]
Scuba Dock

**Comment by ndeloof** [comment]
Ocky Dock

**Comment by jgermond** [comment]
Donald (Dock) ?

**Comment by k33g** [comment]
palmipod

**Comment by pmiossec** [comment]
Docktopus?

**Comment by jdrouet** [comment]
Just Nicolas would be perfect.

**Comment by thaJeztah** [comment]
Figgy 🐙

**Comment by felipecruz91** [comment]
Octy

**Comment by glours** [comment]
Kraky

**Comment by sudo-bmitch** [comment]
Octty McOctface (someone had to do it)

**Comment by sudo-bmitch** [comment]
Cuttle (related to cuttlefish, and a pronunciation guide for `.*ctl` commands)

**Comment by sudo-bmitch** [comment]
Inky

**Comment by sudo-bmitch** [comment]
Squish

**Comment by nunix** [comment]
Kraken Dock (cousin of Moby and Molly Dock)

**Comment by ulrich** [comment]
Toyo (a strong japanese tool box) :toolbox:

**Comment by ulrich** [comment]
**Kara** in tribute to the great conductor: Herbert von Karajan (https://en.wikipedia.org/wiki/Herbert_von_Karajan) :musical_note:

**Comment by slecache** [comment]
Squishy

**Comment by kaosagnt** [comment]
> Paul (as https://en.wikipedia.org/wiki/Paul_the_Octopus)

Paulus compositor

**Comment by papey** [comment]
Octopush

**Comment by nebuk89** [comment]
Docktopus

**Comment by ndeloof** [comment]
@nebuk89 already suggested as https://github.com/docker/compose/issues/9417#issuecomment-1108894396

**Comment by agoncal** [comment]
Octo Dock

**Comment by danielbryantuk** [comment]
C.O.L.I.N. aka "Colin" (Compose Orchestrates, Launches, Integrates, and Networks)

**Comment by ndeloof** [comment]
CTHULHU 🥴

**Comment by ndeloof** [comment]
KORO (sensei)

**Comment by Keruspe** [comment]
Compy

**Comment by k33g** [comment]
Gezora https://kaijufanon.fandom.com/wiki/Gezora

**Comment by mertmr** [comment]
Compocto

**Comment by pmiossec** [comment]
If it is a (music) composer, maybe 🎶 Octave🎼

**Comment by wokier** [comment]
Krako (mix of kraken and compose)

**Comment by divarvel** [comment]
Inky boi

**Comment by nickjj** [comment]
To take inspiration from @thaJeztah's submission of "Figgy", what about Newton?

For anyone out there, this is a reference back to when Docker Compose was called `fig`.

**Comment by maxcleme** [comment]
Pauly Dock

**Comment by maxcleme** [comment]
(h)Andy Dock

**Comment by andrefcdias** [comment]
Benjamin, Ben for friends

**Comment by ritamcastro** [comment]
Octo. No surname :P

**Comment by mjmckay** [comment]
Otto  (play on "automatic")

**Comment by bmf-san** [comment]
Tako Dock
（Tako means octopus in Japanese）

**Comment by sio-funmatsu** [comment]
Taco Hachiro

**Comment by thaJeztah** [comment]
> > Figgy 🐙
> 
> Short for "Figure of Eight"? ♾️

No 😂 

Probably should've mentioned it in my comment; before it was named `Docker Compose`, this project was named `Fig`, so "figgy" is a small nod to "where it all started"; here's the archived website of when it was `fig`; https://orchardup.github.io/fig.sh/

**Comment by dwhitz** [comment]
Kraken 🐙

**Comment by mrVictorios** [comment]
Torsten

**Comment by bzrk** [comment]
Kevin

**Comment by DaruZero** [comment]
Franco

**Comment by nullndr** [comment]
Compy

**Comment by denverdino** [comment]
Coco

**Comment by Keruspe** [comment]
Compose-fusion

**Comment by jecaestevez** [comment]
Spike

**Comment by kenobit8bit** [comment]
Franco

**Comment by 386sx40** [comment]
Franco

**Comment by niun68** [comment]
Franco

**Comment by ndeloof** [comment]
@kenobit8bit @386sx40 @niun68 please vote for existing proposal if you agree with those

**Comment by ndeloof** [comment]
@kenobit8bit @DaruZero could you please explain the reasoning with this name?

**Comment by Zughy** [comment]
@ndeloof it's just a name as another in Italian, it's the equivalent of Frank. We just thought it was silly enough

**Comment by tamberlosauro** [comment]
Franco

**Comment by ndeloof** [comment]
@Zughy this community vote is not designed to let local community compare their size by proposing random names.
i.e. this should not become a "John _vs_ Marcel _vs_ Franco _vs_ Helmut" challenge

**Comment by Zughy** [comment]
@ndeloof how do you understand what is community driven and what not though? I mean, I had no problems tooting it out in the open on Mastodon (and then a big account retooted it, a thing nobody can control), but there's definitely more subtle ways to inflate votes. To me (and this is not a critique), in the moment you make some votes open to the public, you should expect things like this. And we're just voting a silly name anyway, a name I personally genuinely like, it makes me chuckle. It's like John, Mark, etc. It's not like a bad word, an offensive slang or anything like that.

Anyway, thank you for all the work you've been doing with docker, the intent wasn't to ruin the party

**Comment by ndeloof** [comment]
> Wait, is this about Francisco Franco?

This is something our Spanish members might have in mind indeed, but generally speaking we try to avoid real names to both promote creativity and avoid name to be tied to a specific country.

**Comment by Zughy** [comment]
> This is something our Spanish members might have in mind indeed

But with this logic, I should tell my uncle he sounds offensive to Spanish speakers because his name reminds Spanish people of a dictator surname. Like... what?

> avoid name to be tied to a specific country

All your names are English (puns or not), it's still a language spoken mainly in a few countries, you suggested Paul (because of the pun) in the first place. Or am I wrong?

Well, rules have changed anyway, it was fun till it lasted I guess...

**Comment by ndeloof** [comment]
@Zughy no that's not "just" because of Francisco Franco. Just using a human name brings some potential relation with real world people, and makes the mascot name too specific to a local group. With invented names, we enforce something more neutral anyone can adopt

**Comment by unruhe73** [comment]
Franco

**Comment by agoncal** [comment]
> Coco

Careful, in Portuguese "coco" means "poo"

**Comment by agoncal** [comment]
> Octodock

See "Octo Dock" https://github.com/docker/compose/issues/9417#issuecomment-1109507931

**Comment by tomMoulard** [comment]
Michel

**Comment by ludoch** [comment]
Ker Do (comme en Bretagne)

**Comment by decima** [comment]
Gocto
![Gocto mascot](https://user-images.githubusercontent.com/1727893/165912282-9fa128c9-7759-409e-a191-4ecbe48aa09e.png)

**Comment by tfentonz** [comment]
Octothorpus

**Comment by wadael** [comment]
Derek

Derek compose -> decompose

**Comment by blacksheep--** [comment]
Stardock

(to stay within Moby Dick :D )

**Comment by Orionx86** [comment]
Octopus starts with O
No names start with cOM
Names starting with compOS:
Oscar the Octopus
He’s a Composer so his tool of choice is a piano which is great since he’s got 8 arms. Alternatively, you can mix up composer and conductor and give him a baton. Not the worst mix up since the best conductor is also the composer.

**Comment by nocive** [comment]
docktopus or doctopus

**Comment by briceburg** [comment]
Doc(ker|tor) "Tentacles"

**Comment by ShreyamMaity** [comment]
Docktopas

**Comment by ShreyamMaity** [comment]
or Docky

**Comment by fxj9a** [comment]
Composy McComposeface

**Comment by Vrashabh-Sontakke** [comment]
> **Description** In 2013 we asked the growing Docker community to [choose a name](https://www.docker.com/blog/call-me-moby-dock/) for the project mascot, and "Moby Dock" has since be the name of our beloved whale.
> 
> Compose's octopus mascot doesn't have a name. With Docker Compose v2 announced for General Availability, it's time we make Compose a first-class citizen! And as an open-source project, we want community to be the one driving this decision
> 
> **update** to avoid conflict with living or historical persona, we don't accept real name, only will select creative invented name based on project context and/or mascot's octopus kind
> 
> **How does it work** Please
> 
> * add your suggestions to this issue as comments
> * vote for your preferred names using 👍  or 👎 reactions on those comments.
> 
> _This issue is moderated: any irrelevant content will be deleted, thanks for your understanding_
> 
> ![IMG_5419 - copie](https://user-images.githubusercontent.com/132757/165756068-dcff1df0-5aea-43a9-be4e-6f8050ffc4ae.jpg)

doctor

**Comment by Vrashabh-Sontakke** [comment]
doctor

**Comment by HeroicHitesh** [comment]
Dock-topus

**Comment by wadael** [comment]
Hector
For Berlioz, a great compose-hector.

**Comment by nuno-andre** [comment]
Cephalopodocker

**Comment by Anutrix** [comment]
Octopose

**Comment by myrrh99** [comment]
Dr. Up -> Drup
play on "docker compose up" (Doctor C. Up)

**Comment by escherdragon** [comment]
Dexter

**Comment by razcakappa** [comment]
Dockward 🌊 

Fullname: Dockward Dockery Dock.

**Comment by pedroalvesbatista** [comment]
Octrone

**Comment by y-okamoto-1113** [comment]
tacopom

**Comment by gladiatr2727** [comment]
Docktopus!

**Comment by joescott** [comment]
this one for sure have copyright but is great, Hank

**Comment by ZimbiX** [comment]
I vote no name

**Comment by JacopKane** [comment]
Doco

Docktopus

**Comment by czuhajster** [comment]
Composopus 🐙

**Comment by ElleonorK** [comment]
> If it is a octopus (music) composer, so maybe 🎶 Octave🎼

Why not Octavia?

**Comment by pmiossec** [comment]
> > If it is a octopus (music) composer, so maybe 🎶 Octave🎼
> 
> Why not Octavia?

If your question is why I have proposed that it is because the play on words works a lot better ( because Octave is surely as you know a word in music that etymologycaly means height in addition to being a name).

But if your question is more a proposition, I would say 👍 (because it's nicer)

**Comment by tdensmore** [comment]
Was a name ever officially chosen?
