### ISSUE TITLE
Regression in `down` in 2.5.0 - exit code for "nothing needed" went from 0 (success) to 1 (failure)

### ISSUE THREAD

**Issue by 1ace** [docker/compose#9426]
#9384 is causing the behaviour of `down` to go from:
```
$ docker compose --project-name computed-project-name down
[+] Running 1/0
 ⠿ computed-project-name  Warning: No resource found to remove 0.0s
$ echo $?
0
```
to:
```
$ docker compose --project-name computed-project-name down
no container found for project "computed-project-name": not found
$ echo $?
1
```

This is causing a regression in our CI as we always run `down` before running `up` (because [this GitLab bug](https://gitlab.com/gitlab-org/gitlab/-/issues/15603) means we can't rely on `down` having been properly called during the previous run).

I'll be adding a `|| true` after `down` to ignore the error, but I think "I didn't need to do anything" shouldn't be an error, so I'd consider this a docker compose regression :)

**Comment by ilibar-zpt** [comment]
same, use it in CI too
