### ISSUE TITLE
Document how to use Compose in production

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#944]
We should acknowledge the fact that it is possible to use Docker in production, but it is not recommended. We should also explain that we are working on improved support for production and link to the roadmap.

Options:

 - You can run your Compose app on a single server
 - You could use Compose to manage configuration for a single service (e.g. putting `fig up web` in your upstart script or similar)
 - You can point Compose at Swarm, but this integration is experimental and Swarm is in beta

/cc @fredlf

**Comment by baptistedonaux** [comment]
Good news !

**Comment by aanand** [comment]
See https://github.com/docker/fig/pull/949

**Comment by bfirsh** [comment]
We should make clear that we're looking for help gathering requirements, designing and implementing this, and where you can go to get involved (mailing lists, IRC, GitHub).

**Comment by aanand** [comment]
In the docs or in the roadmap, do you reckon?
