### ISSUE TITLE
Allow using docker-compose from subdirectories

### ISSUE THREAD

**Issue by tomdxw** [docker/compose#946]
Like with git, I would like to be able to run docker-compose from within a subdirectory so I don't need to repeatedly change directories when working on a project.

Current behaviour:

    $ cd myproject
    $ docker-compose up -d
    Creating myproject_abc_1...
    Creating myproject_xyz_1...
    $ cd another/directory
    $ docker-compose logs xyz
    Can't find a suitable configuration file. Are you in the right directory?
    
    Supported filenames: docker-compose.yml, docker-compose.yaml, fig.yml, fig.yaml

docker-compose could simply look in all ancestor directories for the *.yml/*.yaml files until it finds one, change working directory, and continue as normal.

**Comment by vovimayhem** [comment]
+1!

**Comment by Starefossen** [comment]
Yeah, I got bitten by this at least twice today :+1:

**Comment by dnephin** [comment]
The only complication here is that right now paths to volumes, env_file, build, etc are all relative to the current working directory. With this change they would need to be relative to the `compose.yaml`. This is certainly possible, but could break existing uses that don't have `compose.yml` in the root of the directory and use paths relative to the root of the checkout.

**Comment by aleksandr-vin** [comment]
My pull-request #1232 does not change directory to the parent, it instead performs like being called with '--file /full/path/to/docker-compose.yml' or 'COMPOSE_FILE=/full/path/to/docker-compose.yml'. So this wouldn't break existing uses.

**Comment by Neppord** [comment]
+1 this would be nice to have!

Though i think it make more sense to use the file as the base.

**Comment by dnephin** [comment]
I believe this was fixed by the refactor for `extends`.

@aanand does that sound right?  Can we close this?

**Comment by aanand** [comment]
Looks like https://github.com/docker/compose/pull/1232 fixed this.
