### ISSUE TITLE
Mess output when compose pull images that contains the same layer

### ISSUE THREAD

**Issue by PMExtra** [docker/compose#9469]
**Steps to reproduce the issue:**
1. Find two images that contains the same base layer
2. Make a `docker-compose.yml` file that refers these two images
3. Execute `docker compose pull`

**Describe the results you received:**

The common layer will be shift and flash between the images, like:

```
Pulling images...
[+] Running xx/xx
 ⠿ imageA Pulling
    ⠿ layerA2 downloading ...
 ⠿ imageB Pulling
    ⠿ layer1 downloading ...                      # this line will shift between imageA and imageB
    ⠿ layerB2 downloading ...
```

**Describe the results you expected:**

Stick it with a certain image, don't shift around.

**Output of `docker compose version`:**
```
Docker Compose version v2.2.2
```

**Output of `docker info`:**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., v2.2.2)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Server Version: 20.10.12
```

**Comment by maxcleme** [comment]
@PMExtra Thanks for reporting this issue, I was able to replicate the same behaviour on my end.

Seems like an easy fix to do, I'll look into it :)

**Comment by wblondel** [comment]
I have the same issue, Docker Compose version v2.17.2, but I am not sure how I can show that

**Comment by wdbasson** [comment]
I'm having the same issue on MacOS.

`docker compose version`
```
Docker Compose version 2.17.2
```

`docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.3)
  compose: Docker Compose (Docker Inc., 2.17.2)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.18)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.6.0)

Server:
 Server Version: 20.10.23
 ```

**Comment by FlorianCassayre** [comment]
Same issue here on Rasperry Pi OS. I have `docker-compose` version `1.29.2`.

Oh, and hi @wblondel.
