### ISSUE TITLE
Environment values in YAML must not be totally blank on OSX 12.3

### ISSUE THREAD

**Issue by dsoprea** [docker/compose#9470]
**Description**

We have a team-member running OSX who kept getting complaints about environment variables not being declared. The other environment variables were showing up fine. The issue went away when we switched from having `ENV_VAR_NAME: ` to `ENV_VAR_NAME: ""`. This appears to be an issue specific to Mac (maybe a system YAML parser), as I've never encountered this myself over the years of Linux development that I've used docker-compose for.

**Steps to reproduce the issue:**
1. Set environment variable in docker-compose
2. Make sure that nothing is right of the colon
3. Write a script/tool to request this variable in such a way that it will fail if not found, and then set this to be called by the docker-compose service.
4. The run should fail because of this

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/715626/168496475-6774fabb-f4e3-4acc-b161-3d25394a0e87.png)

Followed by termination.

**Describe the results you expected:**

Keeps running.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.4.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)
Server:
 Containers: 22
  Running: 6
  Paused: 0
  Stopped: 16
 Images: 16
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.774GiB
 Name: docker-desktop
 ID: GEN2:6WV7:X2GM:Z6KP:EUMG:7GB2:ABNY:EMFC:FHWX:RK6A:5QDM:QIJE
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 106
  Goroutines: 123
  System Time: 2022-05-15T22:26:48.961625668Z
  EventsListeners: 5
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by ndeloof** [comment]
Can you please try using Docker Compose v2 to check this issue persists with the new codebase?

**Comment by dsoprea** [comment]
Still present in the same environment as of 2.5.0 .

**Comment by davidrenne** [comment]
Any thoughts @ndeloof ?

**Comment by dsoprea** [comment]
I've also since seen this in another Linux environment of mine (same Arch-flavor distribution, even), but only just the one.

**Comment by ndeloof** [comment]
Please note `ENV_VAR_NAME: ` (implicitly, null) is not the same as `ENV_VAR_NAME: ""`.
The latter set variable to an blank string, while the former inherit value from same variable set on host environment

```
$ FOO=bar docker run -e FOO alpine sh -c 'echo $FOO'
bar
$ FOO=bar docker run -e FOO="" alpine sh -c 'echo $FOO'

```

**Comment by ndeloof** [comment]
Closing as inactive/obsolete issue
