### ISSUE TITLE
docker-compose not found

### ISSUE THREAD

**Issue by AlexanderPuhl** [docker/compose#9472]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details:**

On Pop_OS, installed docker, can't run docker compose though cause I guess it's just not included with docker???? Found another thread with this exact same issue from 6 years ago, went and followed the instructions on the docker website to install docker compose, issue still persists.

**Comment by AlexanderPuhl** [comment]
I'm just gonna close this, docker is a shit show... especially on Linux...

**Comment by modem7** [comment]
you realise it's `docker compose` and not `docker-compose` now yes?
