### ISSUE TITLE
Compose 2.5.1 not published as .deb or .rpm

### ISSUE THREAD

**Issue by johnthagen** [docker/compose#9497]
**Description**

I would like to download the latest [Docker compose 2.5.1](https://github.com/docker/compose/releases/tag/v2.5.1) as a `.deb`. This is normally published here: https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/

But https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-compose-plugin_2.5.1~ubuntu-bionic_amd64.deb is missing.

[Docker Desktop 4.8.2](https://docs.docker.com/desktop/release-notes/#docker-desktop-482) released with Compose 2.5.1 and we are trying to keep our Linux servers in sync with the latest as well.

As a larger question, will Compose be making releases that aren't pushed into the Linux repositories?

**Comment by glours** [comment]
Hello @johnthagen 

I think that just not be published yet, the [PR](https://github.com/docker/docker-ce-packaging/pull/694) to release the Linux packages has been merged

And no, all our releases will be available for Linux, Mac and Windows, they aren't just following the same packaging release process

**Comment by johnthagen** [comment]
@glours Thanks for the clarification, that makes sense.

**Comment by johnthagen** [comment]
Compose 2.6.0 has now been released at well, but no 2.5.1 debs have been published yet.

- https://github.com/docker/compose/releases/tag/v2.6.0

**Comment by glours** [comment]
As mentioned last time it's a different release process, you have to wait a lit bit or replace your local binary by yourself
https://github.com/docker/docker-ce-packaging/pull/702

**Comment by andy-twosticks** [comment]
"You just have to wait a bit for the PR to be merged" -- May 2022.

Latest release publshed is still 2.39.

**Comment by glours** [comment]
@andy-twosticks yes, we went from `2.5.1` to `v2.39.4`, at least 34 releases since this issue was closed, so I don't get your  `Latest release publshed is still 2.39.` 🤷

**Comment by andy-twosticks** [comment]
README points to https://github.com/docker/compose/releases  for the releases.  Latest there is 2.39.

Ubuntu and Debian are still on 2.3*, so I imagine they see the same as me.

If there is a page with later releases, where is it, and why does the README not link there?

Are you saying that 2.3 > 2.5?   Where is this covered?

**Comment by thaJeztah** [comment]
2.39 > 2.5 (because 39 > 5)

**Comment by andy-twosticks** [comment]
Ah.  Logical but counterintuitive.  To add to my confusion, I'm looking at a feature that apparently takes >2.5 and it's not documented in 2.3*. so I assumed it was missing.  My bad.
