### ISSUE TITLE
incomplete supported filenames in diagnostic message

### ISSUE THREAD

**Issue by ashrude** [docker/compose#9506]
podman-compose supports many filenames such as `docker-compose.yml`, `container-compose.yml`, and `podman-compose.yml` (with the yaml variants too)

I thought I could start naming my compose files `container-compose.yml` so it would be clear they would work on both podman and docker - but I found that docker-compose doesn't like any other names.

**Comment by nuno-andre** [comment]
You could use `compose.yaml` (or `compose.yml`) in the meantime, which is [the currently preferred Compose file name](https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file).

**Comment by glours** [comment]
you can use `-f, --file stringArray           Compose configuration files` to define the file you want to use as configuration.
Docker Compose follows the Compose specification, so if you want to be compliant with all the implementations of the specification please use `compose.yaml` or `compose.yml` 
If podman-compose doesn't support it please open a PR on their side.

**Comment by ashrude** [comment]
Ok that sounds good. I didn't know docker-compose supported those, as this is the output of running `docker-compose up` in an empty directory

```
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml 
```

**Comment by glours** [comment]
Could you close the issue then?

**Comment by ndeloof** [comment]
we should fix the help message to reflect support for `compose.yaml` as recommended by the compose specification

**Comment by ashrude** [comment]
Should I re-open the issue then?

**Comment by ndeloof** [comment]
Compose v2 doesn't show such a message, but just `no configuration file provided`
As Compose v1 will be EoL soon, I'm closing this issue
