### ISSUE TITLE
docker compose run runs all services in container not just specified service and the ones it depends on

### ISSUE THREAD

**Issue by ronald-fenner** [docker/compose#9515]
When using docker compose run with or without a profile it doesn't respect the profile and will run all the services in the compose file instead of just the services for that profile specified.

**Steps to reproduce the issue:**
1. Create a docker compose file with several services with different profiles
2. Use docker compose run with a one of the profiles

**Describe the results you received:**
The container(s) with the specified profile should be run

**Describe the results you expected:**
run should run just he container specified and it's containers it depends on like redis and postgres

**Additional information you deem important (e.g. issue happens only occasionally):**
With or without the profile it spins up all the services in the compose file.
docker compose up does work however i need the run command so once the script the container is running exits the command exits and i can perform some cleanup. Using up just forces the user to have to hit ctrl-c when the container exits to precede with the rest of the cleanup.

I've included the compose file to see it it's an issue with it's setup it's a customized version of the airflow one.
**Output of `docker compose version`:**

```
Docker Compose version v2.5.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 6
  Running: 4
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 9.703GiB
 Name: docker-desktop
 ID: PKHV:NYDT:FIPT:L4XT:FHAJ:JEXY:EETB:DUPE:HZQS:QUXS:6CS2:NZ5F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false


```

**Additional environment details:**
[docker-compose.txt](https://github.com/docker/compose/files/8806209/docker-compose.txt)

**Comment by ronald-fenner** [comment]
I discovered after removing the containers for the other airflow services that if they don't exist then they don't get started when doing run. If they are stopped then they also get started back up when running the specified container.

**Comment by michaeldiscala** [comment]
Hi @ronald-fenner! I'm wondering if this is the same issue I reported a few weeks earlier in https://github.com/docker/compose/issues/9459? Does that seem to be the same thing to you?

**Comment by ronald-fenner** [comment]
Yes looking over that issue it does appear to be the same issue.

**Comment by laurazard** [comment]
It should be fixed by https://github.com/docker/compose/commit/80b7a8d274fbab22522200bccb3eec7558314a3f! It'll be included in the next release.

**Comment by Yehonal** [comment]
I'm still having this issue on docker compose `2.6.0`
