### ISSUE TITLE
Unexpected character "." in variable name when loading env-file

### ISSUE THREAD

**Issue by liorazroel** [docker/compose#9529]
Hey all, 
I try to load env-file and got this message: "unexpected character "." in variable name...."
docker-compose version 2.5.0
in version 1.27.4 for example this bug is not reproduce.

env file for example:
![Screen Shot 2022-06-02 at 17 04 19](https://user-images.githubusercontent.com/52318755/171647493-c08e65cc-7877-46ed-8e1a-8432ec0e89d4.png)

**Comment by glours** [comment]
Duplicated of #8862
