### ISSUE TITLE
The convenience script does not install compose

### ISSUE THREAD

**Issue by Horuyuki** [docker/compose#9531]
**Description**

Installed docker following the convenience script, but docker-compose command not found.

**Steps to reproduce the issue:**
1.
```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
```
2. `sudo systemctl start docker`
3. `sudo docker-compose`

**Describe the results you received:**
```
$ docker-compose

Command 'docker-compose' not found, but can be installed with:

sudo apt install docker-compose
```

**Describe the results you expected:**
Able to bring up compose after installation.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**
not relevant

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.5.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
```

**Additional environment details:**
Ubuntu 20.04

**Comment by maxcleme** [comment]
@Horuyuki 

Well, according to `docker info`, you have indeed `compose` plugin installed, so `docker compose` should be fine instead of `docker-compose`.

Looks like daemon is not running, may I ask you share any error that may have occurred during execution of convenience script ?

**Comment by Horuyuki** [comment]
> @Horuyuki
> 
> Well, according to `docker info`, you have indeed `compose` plugin installed, so `docker compose` should be fine instead of `docker-compose`.
> 
> Looks like daemon is not running, may I ask you share any error that may have occurred during execution of convenience script ?

Thank you for this answer, I was using docker-compose instead of the new docker compose function. So that is good to know.

There were no errors using the script, it worked very good.
