### ISSUE TITLE
docker compose V2 stops all containers related to project

### ISSUE THREAD

**Issue by Couga54** [docker/compose#9554]
`Docker Compose version v2.6.0`

I have project with a few file, like:
```
01_db.yml
02_web.yml
```
I run them with separate commands:
```
docker compose -f 01_db.yml -p test up -d
docker compose -f 02_web.yml -p test up -d
```

When executing command
`docker compose -f 01_db.yml -p test stop`
It stops all services that are related to "-p test" (all services in 01_db.yml and 02_web.yml), meanwhile docker-compose (V1) stop only services related to file and project

**Comment by danger89** [comment]
I experience the same issue. I guess we now need to explicitly provide the service name as last argument?

**Comment by danger89** [comment]
Or... Use `down` instead of `stop`. Down will also remove the image btw.

Example: `docker compose -f ...yml down`

**Comment by sueskind** [comment]
I have the same issue, but `stop` and `down` behaves the same for me. (Docker Compose version 2.6.1)

**Comment by PhilippeAccorsi** [comment]
We seen the same issue :(

Very disapointed with this v2. I need to re-install v1 on server to not broken all service each time.

**Comment by yokonao** [comment]
In my case, this is a fatal issue for our migration to V2.
I want to know whether it is likely to be resolved.
