### ISSUE TITLE
Is there some difference between docker and fig ?

### ISSUE THREAD

**Issue by fsword** [docker/compose#957]
I made a project to show this issue:   https://github.com/fsword/fig_bug_app 

when you use docker command:
```
$ docker build -t 'figbugapp' .
......
$ docker run --rm figbugapp
total 32
drwxr-xr-x  4 root root 4096 Feb 12 10:23 .
drwxr-xr-x 54 root root 4096 Feb 12 10:23 ..
-rw-rw-r--  1 root root    6 Feb 12 10:18 .dockerignore
drwxrwxr-x  8 root root 4096 Feb 12 10:20 .git
-rw-rw-r--  1 root root   55 Feb 12 10:15 Dockerfile
-rw-rw-r--  1 root root  247 Feb 12 10:23 README.md
-rw-rw-r--  1 root root   17 Feb 12 10:12 fig.yml
drwxrwxr-x  2 root root 4096 Feb 12 10:17 log
```

but when you use fig:
```
$ fig up
......
web_1 | total 28
web_1 | drwxr-xr-x  3 root root 4096 Feb 12 10:23 .
web_1 | drwxr-xr-x 54 root root 4096 Feb 12 10:24 ..
web_1 | -rw-rw-r--  1 root root    6 Feb 12 10:18 .dockerignore
web_1 | drwxr-xr-x  7 root root 4096 Feb 12 10:23 .git
web_1 | -rw-rw-r--  1 root root   55 Feb 12 10:15 Dockerfile
web_1 | -rw-rw-r--  1 root root  247 Feb 12 10:23 README.md
web_1 | -rw-rw-r--  1 root root   17 Feb 12 10:12 fig.yml
......
```
No `log` folder item anymore, I think it releated with .dockerignore:

```
log/*
```

So, is there some difference between docker and fig ? or it's just a bug?

**Comment by kojiromike** [comment]
Seems legit. I removed the last two lines of OP's Dockerfile and you can see the difference in the build hashes:

```
$ fig build web
Building web...
 ---> 474f82d465a5
Step 1 : COPY . /figapp/
 ---> 729b901895d7
$ docker build .
 ---> 474f82d465a5
Step 1 : COPY . /figapp/
 ---> 40c97802e718
```

**Comment by kojiromike** [comment]
@fsword May I recommend changing the name of this issue to something someone can understand by scanning it? How about _fig and docker build different hashes with same Dockerfile_?

It's not the .dockerignore. I slimmed your test case down to the simplest possible case:

```
$ ls -a
.		..		Dockerfile	fig.yml
$ cat Dockerfile 
FROM scratch
COPY . /figapp
$ cat fig.yml 
web:
  build: .
$ fig build --no-cache web
Building web...
 ---> 
Step 1 : COPY . /figapp
 ---> ec3743be8d44
Removing intermediate container c025cd26483f
Successfully built ec3743be8d44
$ docker build --no-cache .
Sending build context to Docker daemon 4.096 kB


Sending build context to Docker daemon 

Step 0 : FROM scratch
 ---> 
Step 1 : COPY . /figapp
 ---> 02ecd394bf1e
Removing intermediate container 8108da549cf9
Successfully built 02ecd394bf1e
$ docker images --no-trunc | fgrep $'02ecd394bf1e\nec3743be8d44'
<none>                              <none>                02ecd394bf1e707515e11b1704d958949335c083b42726d47588e5cf3b904e4b   2 minutes ago       485 B
figbugapp_web                       latest                ec3743be8d44d5043ceda6ad0914929aa4fd36c5e0ee3a63fe09296a04fca54b   2 minutes ago       87 B
```

The size difference is pretty interesting considering if you `docker save` the images, you don't get that size difference back.

**Comment by fsword** [comment]
@kojiromike The issue is not about image hash, it about the empty folder.
In the sample proejct, log folder is an empty folder. When I use `docker build`, `log` folder is remained, but when I use `fig`, the folder is lost, so there must be something different.

**Comment by funkyfuture** [comment]
i'm not deep in the code. but if i remember right, a project is build in a temporary folder. if in the process of creation the `.dockerignore`-file was considered, that behaviour makes sense. but that's a wild guess.

anyway, it seems odd that `docker build` takes the `log`-folder into the build context.

**Comment by dnephin** [comment]
This was a bug with the `docker-py` implementation of `.dockerignore`. I think it should have been fixed by https://github.com/docker/docker-py/pull/721

Please feel free to re-open if you're still seeing this with the next release of docker-py (which will probably be either 1.3.2 or 1.4.0, not sure yet)
