### ISSUE TITLE
Not updated pypi page? 🤔 

### ISSUE THREAD

**Issue by kloczek** [docker/compose#9571]
According to https://pypi.org/project/docker-compose/ latest version is 1.29.2 however here latest version is 2.6.0.

**Comment by ndeloof** [comment]
pypi is rigth, as it (obviously) only document the available PYTHON version, which indeed is 1.29.x
Compose has been fully re-implemented in Go in the v2 branch and python-based v1 is now End of Life

**Comment by dimaqq** [comment]
Is there perhaps a plan to release Python bindings for compose v2?

Folks that use `docker` and `docker{-, }compose` in testing will be very glad.
For example anyone who uses https://github.com/avast/pytest-docker (pytest fixtures).
