### ISSUE TITLE
SKIP using `.env` if so desired

### ISSUE THREAD

**Issue by flipbit03** [docker/compose#9593]
**Description**

I have a `.env` file in my repo which is not meant for docker consumption, and it's being inadvertently read by docker-compose, changing variables in my deployment which were not meant to change. My only workaround is to displace/rename the `.env` file and that breaks my "outside of Docker" workflow, just to be able to use `docker compose` in the way I need.

**Steps to reproduce the issue:**
1. Have your repo have a `.env` file in it.
2. Run a Docker Compose stanza that needs a variable with the same name as one defined in the `.env` file
3. Variable will be changed from `.env` with no way

**Describe the results you received:**

Variables were changed.

**Describe the results you expected:**

Having an option to skip reading `.env`

**Output of `docker compose version`:**

```
Docker Compose version v2.6.0
```

**Output of `docker info`:**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 18
  Running: 5
  Paused: 0
  Stopped: 13
 Images: 70
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.14.0-1042-oem
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.11GiB
 Name: CADULAP
 ID: S5QI:W3RJ:6S5D:XNBW:O4AI:7GR7:OGVK:YAJZ:5M3H:MRCM:WNHT:IPEX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by nicksieger** [comment]
Did you try passing `--env-file=/dev/null`? That should make compose ignore your .env file.

**Comment by glours** [comment]
can you try to force the usage of an non existing env file to your command, like this `--env-file ""`

**Comment by flipbit03** [comment]
I cannot. I tried using the `/dev/null` suggestion above, and it just ignored my stuff and again, read from `.env`

**Comment by sandy-wright** [comment]
I think this might also be related to my issue: https://github.com/docker/compose/issues/9608#issuecomment-1170492365

With the caveat that my issue started with v2.6.0 and was working as expected before that upgrade.

**Comment by debdutdeb** [comment]
Thanks @glours 
This, I don't see being a bug. I've been using this "feature" for years now, so has many distributors. Generally in my experience that is how `.env` files are loaded, not specific to compose. (check this for example https://github.com/joho/godotenv/blob/add39c6f94ba6aedc178b80b33eb9f2d6ae8f2ec/godotenv.go#L183-L186) If you have same the set of variables for different components that you don't wanna see overlap, best path is to use named dotenv files for each piece instead of the root one.

**Comment by grainnemcknight** [comment]
I have experienced the same issue. When running docker using  Docker Compose V2 the environment variables are those from my local  `.env` environment (unwanted) despite specifying (e.g.):
```   env_file:
      - ./automation_testing.env
```
      
In my docker-compose.test.yml file. I do not have this issue when running with docker-compose. 

A fix is to rename the .env file to e.g. local.env but it seems like unexpected behavior!

**Comment by glours** [comment]
@deepto98 wait before doing anything regarding that one, @ulyssessouza did a refactoring that should fix most of the env variables and .env files issues

**Comment by deepto98** [comment]
@glours Okay, sure. I'm new to the project, if there are any other issues which need contribution, please do let me know.

**Comment by ulyssessouza** [comment]
@flipbit03 This is the normal behaviour of software interacting with `.env` files. Not specific for `Docker Compose`.

@grainnemcknight Could you please give it another try with `v2.9.0`? If the precedence if not working as expected, please create another issue with your tests cases.
