### ISSUE TITLE
Using compose as library

### ISSUE THREAD

**Issue by baez90** [docker/compose#9602]
Hey,

there is currently a discussion in testcontainers/testcontainers-go#425 whether to use the Go API of `docker-compose` to replace the current process invocation version.

The most important question right now is: is `github.com/docker/compose/v2/pkg` or `github.com/docker/compose/v2/cmd` (or both) meant to be used as library and therefore semantically versioned regarding their public API?

We couldn't find any public documentation and were hence wondering if this is a supported scenario or if we'd be 'on our own' and we'd have to expect breaking API changes every now and then.

Is there any plan/information?

Thanks in advance

**Comment by ulyssessouza** [comment]
Hello @baez90.
TLDR: No.

 `Docker Compose` is not designed as a library and we don't support it as such. So no guarantees on public functions stability.
Maybe just using [Compose Go](https://github.com/compose-spec/compose-go) would fulfil your needs.

**Comment by baez90** [comment]
Mostly yes, but while doing a prototype I also used `pkg/api` and `pkg/compose` to actually ramp up containers without having to take care of the interpretation of a `Project`.

So I totally understand that it's of no interest to you to guarantee a stable API as this makes maintenance of this project so much easier :smile: but...out of curiosity: are there some aspects still under heavy development? I'm just wondering if a proper facade to decouple the public API of testcontainers-go of the one of compose could be enough to gracefully handle breaking changes or are there some fundamental changes to be expected?

**Comment by ndeloof** [comment]
closing this issue, we will collect feedback on https://github.com/docker/roadmap/issues/387
