### ISSUE TITLE
Add support of --read-only docker flag

### ISSUE THREAD

**Issue by spiddy** [docker/compose#961]
Now that we have the possibility to run docker container on read-only filesystem with docker v1.5 It would be really cool to have it on docker-compose.yml format also.

That would be very useful in order to create _immutable infrastructures_.

compose.yml example format could follow the same format as privileged boolean flag:

<pre>
nginx:
  image: nginx:1.7.9
  read_only: true
</pre>

**Comment by spiddy** [comment]
pending of docker/docker-py#483 to be released in order to get a PR ready.

**Comment by diogomonica** [comment]
@spiddy what is the status of this?

**Comment by spiddy** [comment]
There was another PR done for the job, but since it was stuck with a conflict, I pushed my changes. hope this doesn't confuse people.

**Comment by aanand** [comment]
Closed by https://github.com/docker/compose/pull/1335
