### ISSUE TITLE
Compose caching doesn't account for command mutability

### ISSUE THREAD

**Issue by knauth** [docker/compose#9610]
**Description**

The caching system used for `docker build` doesn't account for a command's output being mutable, causing unexpected behavior. Notably, when you `git clone` a repository in a Dockerfile, the cache doesn't check whether the repository has received any changes since the last build. This means that if you manually build using a repository, push an update to that repository, and then build again, your changes will not be reflected in the image. This is confusing and might cause users to believe their changes did not fix the issue.

**Steps to reproduce the issue:**
1. Build from a Dockerfile utilizing `git clone`
2. Push an update to the repository
3. Build from the same Dockerfile again

**Describe the results you received:**
The changes should be reflected in the repository within the image.

**Describe the results you expected:**
The changes are not reflected.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `docker compose version`:**

```
Docker Compose version v2.6.0
```

**Output of `docker info`:**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.49GiB
 Name: docker-desktop
 ID: IE4Z:5BLI:VYLX:JAVE:HPBT:LXMH:JGTO:FYYS:VJZD:DPPR:ABGK:I2BC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by milas** [comment]
Caching for commands executed via `RUN` in a `Dockerfile` are done by the command string:

> Aside from the `ADD` and `COPY` commands, cache checking does not look at the files in the container to determine a cache match. For example, when processing a `RUN apt-get -y update` command the files updated in the container are not examined to determine if a cache hit exists. In that case just the command string itself is used to find a match.

Source: [Dockerfile Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache)

This is a key design for Docker to allow for efficient caching and layer re-use during subsequent builds.

For Compose, you can pass `--no-cache` to the build subcommand to bypass the cache. However, as this will result in a full build every time, performance might suffer.

A better solution would be to use an immutable reference in the clone `RUN` such as a tag:
```dockerfile
ARG GIT_CLONE_TAG=v2.6.1
RUN git clone --depth 1 --branch "${GIT_CLONE_TAG}" https://github.com/docker/compose
```
(example using the Compose repo 🙃)

You can then change the default value or override with a build arg.

**Comment by knauth** [comment]
Thanks for the reply and the info.
