### ISSUE TITLE
Why is the image on Dockerhub not updated?

### ISSUE THREAD

**Issue by wug-ge** [docker/compose#9613]
Hi,

I'm just wondering why this: https://hub.docker.com/r/docker/compose
image hasn't been updated for a year.

Last version seems to be 1.29.

Thanks!

**Comment by glours** [comment]
@wug-ge you can directly use [the docker in docker image](https://hub.docker.com/_/docker)
```shell
> docker run -v /var/run/docker.sock:/var/run/docker.sock --rm -it docker compose version
Docker Compose version v2.6.1
```

**Comment by wug-ge** [comment]
@glours Thanksa a lot! That's the info I needed, the docker/compose image should be labeled as legacy somewhere...

**Comment by johnthagen** [comment]
Related to 

- #8871
