### ISSUE TITLE
Docker Compose is using local environment variables inside containers which overrides those in the env file.

### ISSUE THREAD

**Issue by stone-za** [docker/compose#9614]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C63216C8-48DB-4E93-BC17-FCAF93CBBB05/20220627123550

### Expected behavior
When running `docker compose up -d my_service_name` the environmental variables inside the running container should match those specified in the .env file referenced by the env_file listed in my docker compose yaml file.
### Actual behavior
The environmental variables inside the container matches the environmental variables in the terminal window from which `docker compose up -d my_service_name` is run.
### Information

  - macOS Version: 11.2.3
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 4.9.1 (81317)

### Output of `/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check`
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0019: is the com.docker.vmnetd process responding?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. Make a new directory with two files: compose.yaml and .env
  Contents of compose.yaml:

version: '3.6'

services:
  my_python:
    image: python:3.9.1
    env_file:
      - .env
    command: [ "/bin/bash", "-c", "--", "sleep infinity"]

Contents of .env:
DATABASE_PORT=3306

  3. Open a terminal in the directory where compose.yaml and .env is located
  4. Run `$ export DATABASE_PORT=11111`
  5. Run `$ docker compose up -d my_python`
  6.  Exec into the container `$ docker exec -it CONTAINER_ID /bin/sh`
  7. Inside the container shell, run `$ echo $DATABASE_PORT`
  8. The output is 11111 which is incorrect, the output should instead be 3306 as that is what is specified in the .env file.

**Comment by glours** [comment]
@stone-za @robotikz 
This is an expected behavior, as explain in the [documentation](https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run) when a env variable is defined multiple times the following precedence rules are applied:

```
When you set the same environment variable in multiple files, here’s the priority used by Compose to choose which value to use:

    Compose file
    Shell environment variables
    Environment file
    Dockerfile
    Variable is not defined
```

So you shell definition takes precedence to the env file one

**Comment by stone-za** [comment]
Thanks for the feedback @glours. I'll change my configs/makefile accordingly.
It is interesting that we only started having this issue after updating docker desktop from 4.8.2 to 4.9.1.

**Comment by glours** [comment]
@stone-za that was because we had regressions regarding v1 behavior and we fixed them 😅
