### ISSUE TITLE
compose v2 up doesn't use new image if `pull_policy` causes it to pull one

### ISSUE THREAD

**Issue by thespad** [docker/compose#9617]
**Description**

If you set `pull_policy` to `always` for a service and then run a `docker compose up -d` it will pull a new image if one is available but will not then recreate the container with that image.

**Steps to reproduce the issue:**
1. Set `pull_policy: always` on a service
2. Run `docker compose up -d` when you know there is a newer image available for that service
3. New image is pulled, but not used
4. Run `docker compose up -d` again
5. Container is recreated with new image

**Describe the results you expected:**
If `pull_policy` results in a new image being pulled when `docker compose up` is invoked that image should then be used.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.6.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.1)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 60
  Running: 60
  Paused: 0
  Stopped: 0
 Images: 68
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc crun io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-107-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.63GiB
 Name: docker2
 ID: 67LS:QX2S:7P4H:CTCH:IGKD:4BKW:6HYY:46PB:LHNR:IXBV:CDSP:FXXJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: thespad
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
 Default Address Pools:
   Base: 172.20.0.0/16, Size: 24

WARNING: No swap limit support
```

**Comment by laurazard** [comment]
Hi @thespad, thanks for the report!

I'm having some trouble replicating this, could you maybe provide more complete replication instructions if this is still an issue?

FYI, what I'm trying is:

1. run a local docker registry with `docker run -d -p 5000:5000 --restart=always --name registry registry:2`
2. create an image locally from a Dockerfile with the following:
```
FROM alpine:latest
CMD ["echo", "hello"]
```
and `docker build -t an-image-i-have-locally .`
3. tag the image with `docker tag an-image-i-have-locally localhost:6000/an-image-i-have-locally`
4. push it to the registry with `docker push localhost:6000/an-image-i-have-locally`
5. run `docker compose up` on a compose file such as:
```
services:
  a:
    image: localhost:6000/an-image-i-have-locally
    pull_policy: always
```
6. check the output is `hello`
7. change the Dockerfile to echo something different
8. repeat steps 2-5 and check output is different

**Comment by thespad** [comment]
So I wasn't looking at the container output for verification but the compose output plus sha of the running image.

In each case running compose up would successfully pull the newer image but not recreate the container to use it (unless there's some other change made to the compose project that would otherwise trigger a recreate, obviously). Running compose up a second time would recreate it with the new image.

I'll see if I can provide some exact replication steps when I'm next at my desktop.

**Comment by laurazard** [comment]
Please do! FWIW, looking at the compose output with my setup, I do see the container being recreated.

**Comment by thespad** [comment]
OK, so live example. I have a searxng container. Relevant compose bits

```yml
services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./config:/etc/searxng:rw
    tmpfs:
      - /etc/searx 
    networks:
      - proxy
      - redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true      
    pull_policy: always
```

I know there is a new image available for it.

![image](https://user-images.githubusercontent.com/8425502/181254116-176f1a66-c6c3-477d-ad2e-9dc32caa1dd5.png)

```
$ docker image ls | grep searxng
searxng/searxng                         latest                              b05b66a4c0eb   32 hours ago    187MB
searxng/searxng                         <none>                              e93f03de6d4e   3 days ago      187MB
```

```
$ docker inspect searxng | jq '.[].Image'
"sha256:e93f03de6d4e10df09340b906e1f9753a00a8667e9717978c01bfb6e09219817"
```

![image](https://user-images.githubusercontent.com/8425502/181254391-50c5ea96-130c-428d-8ddb-9bca8babb12d.png)


```
$ docker compose version
Docker Compose version v2.7.0
```

**Comment by ndeloof** [comment]
Could you please confirm this issue still is relevant with v2.17.3 release ?
Many changes applied to build and image management since v2.7.0, and AFAICT we improved a lot to offer a more deterministic usage 😅

**Comment by thespad** [comment]
Testing same container, same conditions:
```bash
$ docker compose version
Docker Compose version v2.17.2
```
```bash
$ docker inspect searxng | jq '.[].Image'
"sha256:96a636b49d97e40186079be4850cf2843bc229e4e0e3e615ddf95fe26b4205d8"
```
```bash
$ docker compose up -d
[+] Running 9/9
 ✔ searxng 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                                                         
   ✔ f56be85fc22e Already exists                                                                                                                                                                                                              
   ✔ a9bb0bc66cb7 Already exists                                                                                                                                                                                                              
   ✔ 4f4fb700ef54 Already exists                                                                                                                                                                                                              
   ✔ ac328ad1bb0b Already exists                                                                                                                                                                                                              
   ✔ 4e2d36437873 Already exists                                                                                                                                                                                                              
   ✔ 0515250c9ba0 Already exists                                                                                                                                                                                                              
   ✔ c8868f39e830 Pull complete                                                                                                                                                                                                               
   ✔ 7fd134d52aa0 Pull complete
[+] Running 1/1
 ✔ Container searxng          Started
```
```bash
$ docker inspect searxng | jq '.[].Image'
"sha256:081d38b1eacfc163ce9c19a629877c32ea41b183030be617b141aca16a3dde23"
```
So looks like it's now working as expected and correctly applying the newly-downloaded image.
