### ISSUE TITLE
Compose using underscore when generating volume and network names

### ISSUE THREAD

**Issue by knovoselic** [docker/compose#9618]
**Description**
The new docker compose plugin is using underscores instead of dashes when generating volume and network names. This makes it so that half resources contain dashes in the names, and other half contain underscores.

**Steps to reproduce the issue:**
Use the following `docker-compose.yml`

```YAML
version: '3.8'
services:
  web-app:
    image: ruby
    volumes:
      - .:/app:cached
      - cool-volume:/usr/local/bundle
    networks:
      - custom-network

networks:
  custom-network:

volumes:
  cool-volume:
```

Run `docker compose -p my-test up`.

**Describe the results you received:**
Created volume and network resources have underscore in their name:
```
 ⠿ Network my-test_custom-network  Created
 ⠿ Volume "my-test_cool-volume"    Created
 ⠿ Container my-test-web-app-1     Created
```

**Describe the results you expected:**
I'd expect the expected names to contain only dashes, same as container name:
```
my-test-custom-network
my-test-cool-volume
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.6.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 11
  Running: 1
  Paused: 0
  Stopped: 10
 Images: 21
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 24.42GiB
 Name: docker-desktop
 ID: 6WFW:Y2JC:QG4N:3ENS:CGNS:WLHG:TM3T:J2LC:FSR2:WO56:3YFI:UWYJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

```

Is this a bug or intended behavior?

**Comment by PAXANDDOS** [comment]
This doesn't seem to be resolved... 
I use `Windows 11 22H2` and `Docker Desktop v4.12.0` with the `Use Docker Compose V2` option enabled. Though I still get my volumes and networks created with an underscore:
![image](https://user-images.githubusercontent.com/40315177/195375933-dd2fcf0e-ff28-4a6c-9120-8c353a084c29.png)
Containers are created with a hyphen.
It hurts my eyes a lot especially when I have volumes named something like "mariadb-storage", it then creates a volume named "project_mariadb-storage"

I have something configured wrongfully or is that a bug?

**Comment by laurazard** [comment]
@PAXANDDOS can you run `docker compose version` and check what version it outputs? This should not be happening in the latest versions.

**Comment by PAXANDDOS** [comment]
@laurazard
```pwsh
PS D:\Repositories\recon> docker version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
PS D:\Repositories\recon> docker compose version
Docker Compose version v2.10.2
PS D:\Repositories\recon> 
```

**Comment by laurazard** [comment]
Sorry, my previous comment is incorrect. The changes that closed this issue were reverted. Relevant discussion as to why [here](https://github.com/compose-spec/compose-go/pull/294). We're currently not planning to make changes to this behaviour due to the reasons listed in that PR.

**Comment by taseenb** [comment]
Using underscores in container names and services should be deprecated because it can create issues with service discovery and hostname resolution that are almost impossible to debug.

Underscores are not permitted in standard DNS domain names according to RFC 1035, which only allows letters, numbers, and hyphens.

Example: Docker containers fail to connect to MongoDB via Mongoose if the hostname contains underscores.
