### ISSUE TITLE
Remove old documentation on https://docs.docker.com/compose/completion

### ISSUE THREAD

**Issue by vandman** [docker/compose#9621]
**Description**

**Steps to reproduce the issue:**
Go to https://docs.docker.com/compose/completion/#available-completions
or
Search for "docker compose autocompletion" in any search provider (Google, dukdukgo...), the first link is the link given above.
Follow the documentation

**Describe the results you received:**
The link given in the documentation to downlad contrib/completion/bash/docker-compose does not exist on version 2 and above.
It result on a http error 404, witch give a error message on the console when we start a session:
error on the console => "404:: command not found"

**Describe the results you expected:**
bash completion for docker compose.

**Comment by shakibamoshiri** [comment]
### [Command-line completion](https://docs.docker.com/compose/completion/)
```
curl \
    -L https://raw.githubusercontent.com/docker/compose/v2.7.0/contrib/completion/bash/docker-compose \
    -o /etc/bash_completion.d/docker-compose
 ```
### 404: Not Found

The previous version is gone :|

```
cat /etc/bash_completion.d/docker-compose ; echo
404: Not Found
```

**Comment by ndeloof** [comment]
Docs has been revisited and https://docs.docker.com/compose/completion/#available-completions doesn't point to any relevant page for this issue.

As a CLI plugin, docker compose v2 relies on `docker` top-level command support for dynamic completion, which is available in latest release. Script to be installed as bash completion can be generated using `docker completion bash`
