### ISSUE TITLE
Docker-compose down mistaking service for command when providing -f and -p

### ISSUE THREAD

**Issue by hazmeister** [docker/compose#9627]
**Description**

We use docker-compose in our ci to spin up and down services for our integration tests.  This is slightly different to running the stack locally, so we provide a file using the `-f` flag, and we might be building more than one branch at a time, so we also provide a branch name using `-p`.  We use `docker-compose down` with these same flags to clear up at key points. Since moving to docker-compose 2.5.0 and later, the first service is misinterpreted as a command instead.  The same command works for 2.4.1

**Steps to reproduce the issue:**
1. Start backing services e.g. `docker-compose -f jenkins-docker-compose.yml -p $SAFE_BRANCH up -d db redis zookeeper`
2. Run your tests (you can skip this when reproducing).
3. Tear down e.g. `docker-compose -f jenkins-docker-compose.yml -p otherone down db redis zookeeper`

**Describe the results you received:**
`unknown command "db" for "docker compose down"`

**Describe the results you expected:**
db, redis and zookeeper containers stopped and removed without error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
docker-compose version
Docker Compose version v2.5.1
```

**Output of `docker info`:**

```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cc61520f4cd876b86e77edfeb88fbcd536d1f9d
 runc version: f46b6ba2c9314cfc8caae24a32ec5fe9ef1059fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.281-212.502.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.48GiB
 Name: ip-10-160-26-183.eu-west-2.compute.internal
 ID: RIXE:KZNV:MRYT:PVLR:PIFI:AO2Y:3HWG:WS6Z:MUZU:GDMP:43TM:E3DC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details:**

**Comment by laurazard** [comment]
Hi @hazmeister, thanks for reporting this! 

This behaviour was introduced in https://github.com/docker/compose/pull/9158, due to the fact that previously, although extra arguments could be passed, `compose down` would always tear down the entire compose project (as opposed to `compose up` which can take an argument to specify which service should be ran), which could be confusing.

**Comment by alvincrespo** [comment]
@laurazard  Does this mean that tearing down the whole project is expected and should be standard?

**Comment by alexander-vie** [comment]
I stumbled upon the same problem. Documentation https://docs.docker.com/engine/reference/commandline/compose_down/ says that "SERVICES" may be specified. But even when adding an option (e. g. -t 10), giving a service name will yield an "unknown command" error.
