### ISSUE TITLE
Docker compose hangs (sometimes) when stopping containers.

### ISSUE THREAD

**Issue by hcshmk** [docker/compose#9629]
**Description**

We're _still_ experiencing the hang-when-stopping bug (https://github.com/docker/compose/issues/9062, https://github.com/docker/compose/issues/9065, https://github.com/docker/compose/pull/9019, https://github.com/docker/compose/issues/8523) with docker-compose version 2.5.0 on docker engine 20.10.16. When docker-compose hangs, after all containers have gracefully stopped, the process just ignores any further `CTRL-C` (`SIGINT`) signals. Issue https://github.com/docker/compose/issues/9312 seems to have a vaguely related problem where stop also doesn't seem to mean stop.

**Steps to reproduce the issue:**
1. Pick a compose file, possibly that configures restart behaviour on a container (https://github.com/docker/compose/issues/8523)
2. Issue `docker compose up`
3. Issue `SIGINT` by pressing `CTRL-C`
4. Wait for a while
5. Observe that command doesn't return, even though all containers are stopped
6. Press `CTRL-C` a few more times
7. Observe that nothing happens.

**Describe the results you received:**
`docker-compose` continues to hang forever.

**Describe the results you expected:**
`docker-compose` should return cleanly.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue only happens sometimes, but when it does it's consistent. By this i mean that we have two seemingly identical systems on our test bench, running the same exact compose file, one of which will consistently fail to return after stopping containers while the other returns just fine.

**Output of `docker compose version`:**

```
Docker Compose version v2.5.0
```

**Output of `docker version`:**

```
Client:
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.18.2
 Git commit:        aa7e414fdcb23a66e8fabbef0a560ef1769eace5
 Built:             Sun May 15 14:51:52 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.2
  Git commit:       f756502055d2e36a84f2068e6620bea5ecf09058
  Built:            Sun May 15 14:46:21 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        a916309fff0f838eb94e928713dbc3c0d0ac7aa4
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.5.0)

Server:
 Containers: 13
  Running: 0
  Paused: 0
  Stopped: 13
 Images: 14
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: a916309fff0f838eb94e928713dbc3c0d0ac7aa4
 init version: 
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.52-0-lts
 Operating System: Alpine Linux v3.16
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.662GiB
 Name: -
 ID: W4PF:7JBL:ZKMQ:EDD7:OP2T:5VRH:EROC:C6XD:JNFC:COZB:BOFR:KRA4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
The system in question is running Alpine 3.16 kernel 5.15.52-0-lts on x86_64

**Comment by hcshmk** [comment]
There is a bunch of other issues (https://github.com/docker/compose/issues/6678, https://github.com/docker/compose/issues/6552) that complain about compose stalling / hanging, or just being slow in general. These seem related to entropy on the host machine, which should not be the case with our issue since behaviour is not the same and we're running [haveged](https://linux.die.net/man/8/haveged) to feed /dev/random.

**Comment by laurazard** [comment]
Hi @hcshmk, thanks for the report! Could you provide a `compose.yaml` file that, even if not 100% of the time, causes this issue? I'm having trouble replicating this.

**Comment by laurazard** [comment]
Closing this for now, please open again with a `compose.yaml` for reproducing the issue if it persists.
