### ISSUE TITLE
When using command `docker compose run`, `target` is ignored if both `dockerfile` and `target` is defined in the build section of a service definition

### ISSUE THREAD

**Issue by DanielGiljam** [docker/compose#9633]
**Description**

[`target`](https://docs.docker.com/compose/compose-file/build/#target) is ignored if both [`dockerfile`](https://docs.docker.com/compose/compose-file/build/#dockerfile) and [`target`](https://docs.docker.com/compose/compose-file/build/#target) is defined in the [`build`](https://docs.docker.com/compose/compose-file/build/) section of a service definition in a [`compose`](https://docs.docker.com/compose/compose-file/) file.

**Steps to reproduce the issue:**
1. Write a `lib/example-subdir/compose.yml` file:
   ```yml
   services:
     example-service:
       build:
         context: ../../
         dockerfile: Dockerfile
         target: example-target
     example-service-2:
       image: some-image
   ```
2. Write the `Dockerfile`:
   ```Dockerfile
   FROM node:alpine AS base
   WORKDIR /app
   COPY package.json yarn.lock .

   FROM base AS build
   RUN yarn --frozen-lockfile
   RUN yarn build --out dist

   FROM base AS prod-deps
   ENV NODE_ENV production
   RUN yarn --frozen-lockfile

   FROM build AS example-target
   CMD yarn dev
   
   FROM prod-deps AS other-target
   COPY --from=build dist dist
   CMD yarn start
   ```
3. Run `docker compose run example-service`.

**Describe the results you received:**

All targets are built.

(Or at least the specified target **_+ the last target in the [`Dockerfile`](https://docs.docker.com/engine/reference/builder/)_**. Perhaps if another target was declared between `example-target` and `other-target`, then that target wouldn't be built. However, I didn't verify this.)

**Describe the results you expected:**

Only the targets `base`, `build` and `example-target` are need to be built in order to build `example-target`, so only those targets should be built.

**Additional information you deem important (e.g. issue happens only occasionally):**

-

**Output of `docker compose version`:**

```
Docker Compose version v2.6.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 17
  Running: 0
  Paused: 0
  Stopped: 17
 Images: 49
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.842GiB
 Name: docker-desktop
 ID: VTM5:SRYD:AMG5:EMRO:XJCU:PXEN:ZAKH:3KGE:6WWP:4C5S:UMSZ:BYXQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details:**

Docker Desktop on macOS.

**Comment by glours** [comment]
Hey @DanielGiljam 

Can you clarify some stuff just to be sure I can reproduce correctly your issue.
In you example you try to run the `example-service-2`, this service refer to  an image called `some-image`. Where should this image come from? Am I supposed to put the name of a random image such as `nginx` for example or do you forgot to name the image build from `example-service` with this name?

**Comment by DanielGiljam** [comment]
Hey @glours

The former — in other words, you’re supposed to put the name of some random image (e.g. `nginx`) there.

**Comment by glours** [comment]
🤔 
So I don't understand, if you explicitly call `docker compose run example-service-2`, the build of the service `example-service` shouldn't be trigger at all
<img width="1671" alt="Screenshot 2022-07-08 at 15 46 22" src="https://user-images.githubusercontent.com/705411/178004435-497ba7cf-40d7-4a24-a79e-88fa55095824.png">

**Comment by DanielGiljam** [comment]
Whops! Sorry, a critical typo. I meant `docker compose run example-service`. I have changed it now so it’s correct in the original comment as well.

**Comment by glours** [comment]
So are we agree that's we don't need the `example-service2` at all? 

When trying to do the same based on a `awesome-compose` base project (the vuejs one), I got this result which show that only the needed steps have been built:

```shell
> docker compose down --rmi all
[+] Running 3/3
 ⠿ Image nginx                           Warning: No resource found to remove                     0.0s
 ⠿ Image example-subdir_example-service  Warning: No re...                                        0.0s
 ⠿ Network example-subdir_default        Removed                                                  0.2s
> docker compose run example-service
[+] Running 1/1
 ⠿ Network example-subdir_default  Created                                                        0.5s
[+] Building 50.6s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                              0.1s
 => => transferring dockerfile: 391B                                                              0.0s
 => [internal] load .dockerignore                                                                 0.0s
 => => transferring context: 2B                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:17-alpine                                 7.0s
 => [auth] library/node:pull token for registry-1.docker.io                                       0.0s
 => [base 1/4] FROM docker.io/library/node:17-alpine@sha256:76e638eb0d73ac5f0b76d70df3ce1ddad941  0.0s
 => [internal] load build context                                                                 5.9s
 => => transferring context: 98.37MB                                                              5.7s
 => CACHED [base 2/4] WORKDIR /app                                                                0.0s
 => CACHED [base 3/4] COPY package.json yarn.lock .                                               0.0s
 => [base 4/4] COPY . .                                                                           2.9s
 => [build 1/2] RUN yarn --frozen-lockfile                                                       20.7s
 => [build 2/2] RUN yarn build --out dist                                                         9.7s
 => exporting to image                                                                            4.3s
 => => exporting layers                                                                           4.3s
 => => writing image sha256:5cacc41bb09103efadcf772d90920d62d8d571d6c292646d0745b6bc72d997cb      0.0s
 => => naming to docker.io/library/example-subdir_example-service                                 0.0s
yarn run v1.22.19
$ vue-cli-service serve
...
```

We can see it started with the `base` step then the `build` one and finally started the project like define in the `example-target`

So for me, it's working as expected. Can you try to give me a more complete sample or try to reproduce with one of the `awesome-compose` samples, that way we'll have the same base project?

**Comment by ndeloof** [comment]
Closing this issue as obsolete, please comment or open a new issue with more context if still relevant for your needs.
