### ISSUE TITLE
[Feature request] Add a way for automatic authentication

### ISSUE THREAD

**Issue by maxkraft7** [docker/compose#9635]
**Description**
I want to propose a new feature: automatic authentication. With that you could have either a global `authentication`-Object in your compose file, or define it for each image seperately. With that docker-compose would also take care of the `docker login` part for any new setup. For security reasons the password could also be moved into a seperate file. What do you think of this idea?

**Comment by ndeloof** [comment]
After 6 months this proposal doesn't even have a :+1 vote, so I'll close it
By the way, proposals to change compose file should be discussed on github.com/compose-spec/compose-spec
