### ISSUE TITLE
[FEATURE REQUEST] Command outputs in .env files

### ISSUE THREAD

**Issue by averon420** [docker/compose#9651]
**Description**
Could you add command outputs to .env files? Like:
`USER_SERVICENAME=$(id -u d_servicename)`

or for group id:
`GROUP_SERVICENAME=$(getent group GROUPNAME | cut -d: -f3)`

That would help me a lot, so I could re-use compose files, even though the users got different IDs on each system.

**Comment by ndeloof** [comment]
We don't want to approve this proposal, as doing so would break compose file portability: there's no way to guarantee the same command can be run on another computer, which might run a distinct OS or just miss the requested command.
