### ISSUE TITLE
Documentation page for "pull" command still rendered incorrectly

### ISSUE THREAD

**Issue by slhck** [docker/compose#9656]
**Description**

The page at https://docs.docker.com/engine/reference/commandline/compose_pull/ is rendering incorrectly.

**Steps to reproduce the issue:**
1. Visit the page
2. Observe broken code example

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/582444/179240484-77348419-95a5-4f04-bbea-0b4040b8f7e6.png)

**Describe the results you expected:**

Correctly formatted fenced code.

**Comment by ndeloof** [comment]
Closing this issue as fixed
