### ISSUE TITLE
win10 Docker Desktop  docker compose version 'compose' is not a docker command 。

### ISSUE THREAD

**Issue by cfj1996** [docker/compose#9658]
**Description**

**Steps to reproduce the issue:**
1. win10 Docker Desktop v4.10.0
2. $ docker compose version
3. display 'compose' is not a docker command

**Describe the results you received: Docker Compose version v2.6.1**

**Describe the results you expected: output the correct docker compose version**

**Additional information you deem important (e.g. issue happens only occasionally): 1.already opened Use Docker Compose V2.
2. Why is my docker plugin installation path C:\Program Files\Docker\Docker\resources\cli-plugins ?
3. cope C:\Program Files\Docker\Docker\resources\cli-plugins  => C:\Program Files\Docker\cli-plugins Can be solved .why is that？
**

**Output of `docker compose version`:**

```
docker: 'compose' is not a docker command.
See 'docker --help'
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 50.14GiB
 Name: docker-desktop
 ID: 732C:CRXD:5EJB:CBXO:WXBC:Z54D:LUZ2:XM6J:W6EZ:J7EK:LBOX:VWSU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by Alexyoe** [comment]
I'm having the same issue after updating docker desktop. I've tried reinstalling but nothing changes. 

Docker Desktop Version 4.12.0
Docker version 20.10.17, build 100c701
OS/Arch: windows/amd64

```
docker: 'compose' is not a docker command.
See 'docker --help'
```

**Comment by CoderLittleChen** [comment]
I can get the compose version from the [About Docker Desktop] in the Docker Desktop.When I typed the command: docker compose version.I got same issue.I can't find any solution in official tutorial。
OS:Windws 10/amd64
Docker Desktop version：4.14.0
Docker Compose:2.12.2
