### ISSUE TITLE
Docker compose build super slow ( takes about 40 minutes )

### ISSUE THREAD

**Issue by Emporea** [docker/compose#9665]
I just switched from docker-compose 1.29 to docker compose v2
Now its using the buildkit and I am having troubles with my docker builds that were building fast and solid with docker-compose 1.29

```
FROM codercom/code-server:latest
USER root
RUN code-server --install-extension ms-python.python
RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install -y pip
RUN pip3 install mysql-connector-python pyvis spacy 
RUN python3 -m spacy download en_core_web_lg
RUN python3 -m spacy download de_core_news_lg
RUN python3 -m spacy download es_core_news_lg
```

This took around 5 minutes with docker-compose 1.29.
With docker compose 2.7 it takes around 40 minutes. Same Dockerfile, ame docker.compose.yml file.

![image](https://user-images.githubusercontent.com/21969523/180504611-55e59106-baad-4f96-b5e2-ac4e22bc1a48.png)

I heared something about time stamp comparison but i dont really know whats going on here. Any way to be able to speed up Docker Compose v2 build process?

**Comment by ndeloof** [comment]
How large is this built image ?
Have you compared build time using plain `DOCKER_BUILDKIT=<1 or 0> docker build` ?

**Comment by Emporea** [comment]
I have no issue anymore.

**Comment by johnrodwell-affinity** [comment]
I wish people would post their solution to these problems instead of just commenting "fixed" or something and then leaving it would really help everyone else
