### ISSUE TITLE
Can't use delegated volumes with docker-compose v2

### ISSUE THREAD

**Issue by pedroterzero** [docker/compose#9668]
**Description**

When switching from docker compose v1 to v2, `:delegated` in volume specification seems to get ignored. I'm not sure whether this is intentional, I couldn't find anything about it.  Apologies if this is intended behaviour. If so, how can I achieve the same in docker-compose v2?

**Steps to reproduce the issue:**
1. Create a test `docker-compose.yml`:
   ```yaml
    version: "3"

    services:

      test:
        container_name: test
        image: hello-world
        volumes:
          - ./test:/test:delegated
    ```
2. Run `docker-compose up`
3. Look at `docker inspect test`

**Describe the results you received:**
Volumes look like this in docker-compose 2.x:
```json
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/user/docker/test/test",
                "Destination": "/test",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

**Describe the results you expected:**
With docker-compose 1.29.2 the volumes look like this:
```json
       "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/user/docker/test/test",
                "Destination": "/test",
                "Mode": "delegated",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

**Additional information you deem important (e.g. issue happens only occasionally):**
n/a

**Output of `docker compose version`:**

```
Docker Compose version v2.6.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 9
  Running: 7
  Paused: 0
  Stopped: 2
 Images: 23
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-41-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.72GiB
 Name: Ubuntu-2204-jammy-amd64-base
 ID: ZV54:CYO3:U37J:PA3Z:3TXM:2ZBW:OH7A:LZXE:TFL7:PVDP:OSHL:GOCW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
n/a

**Comment by laurazard** [comment]
Hi @pedroterzero, thanks for the report.

`:delegated` along with some other flags were [deprecated](https://github.com/docker/for-mac/issues/5402) with the introduction of gRPC-fuse, since they don't apply anymore. This is why they're also not in the documentation anymore. As such, I'm closing this issue, but if there's anything you were achieving with the delegated mount you can't anymore please let us know.

**Comment by pedroterzero** [comment]
@laurazard 

It seems I was getting much better performance with this on a mysql server database, but maybe it was the placebo effect, I guess?

I'll try and compare without it. Thanks.
