### ISSUE TITLE
Compose v2 install alpine

### ISSUE THREAD

**Issue by persona-ny** [docker/compose#9694]
Hi.  tell me how to install compose v2 on alpine linux distribution?  I don't understand how to do it.  right now I'm using v1 but I wanted to be newer

**Comment by ulyssessouza** [comment]
Unfortunately we don't manage the alpine package. So since you don't have a distribution package for V2, you could try the manual installation for Linux: https://github.com/docker/compose#linux

**Comment by dougludlow** [comment]
Looks like there is a apk package for v2: https://pkgs.alpinelinux.org/packages?name=docker-cli-compose

```
apk --no-cache docker-cli docker-cli-compose 
```
