### ISSUE TITLE
docker-compose 1.29.2 doesn't build image to remote host

### ISSUE THREAD

**Issue by Pandaaaa906** [docker/compose#9713]
I got two machine 
A: docker host for production
B: which is a gitlab-runner, executor is shell mode, Ubuntu 22.04 LTS (GNU/Linux 5.15.0-41-generic x86_64)

install docker-compose using
```bash
$sudo apt install -y docker-compose
$docker-compose --version
docker-compose version 1.29.2, build unknown
docker-py version: 4.4.4
CPython version: 3.10.4
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
```
up&build docker-compose
```bash
docker-compose -f docker-compose.yml -H tcp://A:2376 --tlsverify --tlscacert "./.docker_ssl/ca.pem" --tlscert "./.docker_ssl/cert.pem" --tlskey "./.docker_ssl/key.pem" up -d --build
```

**Describe the results you received:**
It shows that all images are "up-to-date", and container doesn't recreate(logical), even while Dockerfile or source code is modified.
Additionally, when i adding "--force-recreate" flag to previous "up" command, images doesn't rebuild, but remote containers recreated

**Describe the results you expected:**
images should be rebuilt in remote docker, and containers should be recreated using the new images

if I switch to pip's docker-compose==1.29.2 same problem exists
but when i downgrade to 1.27.1 this problem is gone

**Comment by laurazard** [comment]
Hi @Pandaaaa906, thanks for the report.

`Docker Compose V1`, which you are using, is [EOL](https://github.com/docker/compose/tree/master#warning-compose-v1-is-deprecated-warning). As such, only security related issues are considered for it.

Could you update to `Docker Compose V2` and see if the issue persists?

**Comment by laurazard** [comment]
Closing this for now, please open again if the issue persists with `Compose V2`.
