### ISSUE TITLE
i can't start docker-compose

### ISSUE THREAD

**Issue by emg777** [docker/compose#9719]
**Description**
i have an error when i try to start compose
 when i try to start compose with "docker-compose up -d" i receive this result: Invalid template: "WSӠ$8É*X&*8HѲk!^£"

**Describe the results you received:**
Invalid template: "WSӠ$8É*X&*8HѲk!^£"

**Describe the results you expected:**
i expected that compose start

**Output of `docker compose version`:**
```
Docker Compose version v2.9.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.18.0-kali5-amd64
 Operating System: Kali GNU/Linux Rolling
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.908GiB
 Name: kali
 ID: FLKD:PZAB:U4QE:BK2U:WXPU:ABJ7:FEBO:3BI7:4BB7:FUWZ:CDST:3O7D
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by laurazard** [comment]
Hi @emg777, thanks for the report.

Could you provide a minimal compose file with which you’re getting this error so we can try to replicate the issue? Thanks!

**Comment by emg777** [comment]
> Hi @emg777, thanks for the report.
> 
> Could you provide a minimal compose file with which you’re getting this error so we can try to replicate the issue? Thanks!

HI @laurazard With this repository https://github.com/SecurityRiskAdvisors/VECTR/releases
Did you mean this with minimal compose?

**Comment by laurazard** [comment]
ahh, looking at the `.env` file in that release, I think I see where that's coming from
`.env`:
```
[...]
JWS_KEY=WSӠ$8É*X&*8HѲk!^£
[...]
```

cc @ulyssessouza, do you think this will be fixed by your recent changes?

**Comment by laurazard** [comment]
@emg777, as per @ulyssessouza's message [here](https://github.com/docker/compose/issues/9704#issuecomment-1202335152):

In Docker Compose V2 dollar signs have to be escaped by doubling it ($$).
Another solution would be surrounding the whole string with single quotes (''), like in:
`JWS_KEY='WSӠ$8É*X&*8HѲk!^£'`

Can you try that and see if it works?

**Comment by emg777** [comment]
> @emg777, as per @ulyssessouza's message [here](https://github.com/docker/compose/issues/9704#issuecomment-1202335152):
> 
> In `Docker Compose V2` dollar signs have to be escaped by doubling it ($$). Another solution would be surrounding the whole string with single quotes (''), like in:
> 
> ```
> JWS_KEY='WSӠ$8É*X&*8HѲk!^£'
> ```
> 
> Can you try that and see if it works?

thank you @laurazard for helping me. I resolved the issue.
