### ISSUE TITLE
External Keyboard Navigation in compose

### ISSUE THREAD

**Issue by sunishrai** [docker/compose#9743]
Hi everyone,

I have a question about Switch Access and directional navigation in Jetpack Compose.
When using Java Views it was possible to navigate my Applications using the tab key on my keyboard. However with Jetpack compose this feature is completely missing.

The use of "Focus" allows to achieve something similar but will require a huge amount of additional code and logic to be added only to navigate in the App.

Is there any plans of supporting keyboard navigation in Jetpack Compose Apps by default in the future and which options do I currently have?

Regards, 
Sunish

**Comment by glours** [comment]
Hello @sunishrai 

This the repository of Docker Compose not Jetpack, you should ask your question [here](https://issuetracker.google.com/issues/new?component=612128&pli=1&template=1253476)
