### ISSUE TITLE
Mac 10.15 Catalina, Docker version 20.10.17, build 100c701

### ISSUE THREAD

**Issue by tanerjn** [docker/compose#9752]
**Description**
Build errror.

Unmounted files.

**Steps to reproduce the issue:**
1. Pull the code (https://github.com/rnegron/django-project-template.git)
2. Do the installation steps at github page.
3. docker-compose up --detach --build

**Describe the results you received:**

ERROR: for web  Cannot start service web: Mounts denied: 
The path /opt/prj/rnegron/fixhub is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
ERROR: Encountered errors while bringing up the project.

**Describe the results you expected:**

Success message output.

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.7.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.8)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Additional information:

I added /opt/prj/rnegron/fixhub to Docker-Preferences-File Sharing. 

**Error invoking remote method 'docker-start-container': Error: (HTTP code 500) server error - Mounts denied: The path /opt/prj/rnegron/fixhub is not shared from the host and is not known to Docker. You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing. See https://docs.docker.com/desktop/mac for more info.**

Server:
 Containers: 4
  Running: 2
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.843GiB
 Name: docker-desktop
 ID: 5YUE:ASW7:24J5:ZVLG:3I4I:VRBC:RIBX:OZ5X:FRN4:SWIB:CYZD:G72D
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by tanerjn** [comment]
https://stackoverflow.com/a/62842115 

this helpted a bit.. still problem exists with the src/entry_point.sh

**Comment by milas** [comment]
I'm glad you figured out how to add additional file shares from Docker Desktop.

I'm not sure what you mean "problem exists with the `src/entry_point.sh`". Please provide the commands you're running as well as all error output.

**Comment by tanerjn** [comment]
worked it out. thanks for your help

**Comment by tanerjn** [comment]
Ok, thanks.
