### ISSUE TITLE
Update container w/ network when healthy?

### ISSUE THREAD

**Issue by dm17** [docker/compose#9762]
Can compose replace or update a container when the new one is healthy? In my definition of replace, it only attaches it to networking (unless there is build-time networking) when the container comes up and also has a healthy status. The services inside of these containers must be up as well (which I'm pretty sure is included in docker's definition of 'healthy').

I realize the standard is "use k8s or swarm" or similar. But I can do everything I need with compose except this - and it is close enough to ideal without this currently.

The only other docker functionality that would really improve my container-life these days is https://github.com/docker/compose/issues/3729

**Comment by nicksieger** [comment]
Can you give a little more detail, maybe an example? I'm thinking of `depends_on:` with the service key and `condition: service_healthy`. Compose creates all containers at startup but doesn't run them until the healthcheck is satisfied. How does what you're asking for differ?

**Comment by ndeloof** [comment]
Closing this issue as reporter didn't answered. 
Feel free to comment if this issue is still relevant
