### ISSUE TITLE
can't access to other websites when using docker / docker block my internet to other websites

### ISSUE THREAD

**Issue by yimei-li** [docker/compose#9793]
I am using Ubuntu 22.04, Docker version 20.10.8. 
**Issue:** when I am using docker (type `docker-compose up` in my terminal), I can search in google or firefox, but I can NOT get access to some other websites like amazon, StackOverflow, etc. It shows "This site can’t be reached".

If I type `sudo cat /var/log/syslog`, I got this:

> Aug 28 10:52:19 pop-os slack.desktop[3332]: [08/28/22, 10:52:19:567] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from fast_reconnecting to error
> Aug 28 10:52:19 pop-os slack.desktop[3332]: [08/28/22, 10:52:19:567] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in error state for up to 10000 ms
> Aug 28 10:52:19 pop-os slack.desktop[3332]: [08/28/22, 10:52:19:568] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from error to wait_for_rate_limit
> Aug 28 10:52:19 pop-os slack.desktop[3332]: [08/28/22, 10:52:19:568] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in wait_for_rate_limit state for up to 120000 ms
> Aug 28 10:52:19 pop-os slack.desktop[3332]: [08/28/22, 10:52:19:568] info: [SOCKET-MANAGER] (T0101Q53BPG) backing off: will wait for 1569 ms
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:604] info: [SOCKET-MANAGER] (T03U4EJLT) Changing from wait_for_rate_limit to connect
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:604] info: [SOCKET-MANAGER] (T03U4EJLT) will stay in connect state for up to 10000 ms
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:604] info: [SOCKET-MANAGER] (T03U4EJLT) Changing from connect to checking_fast_reconnect
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:604] info: [SOCKET-MANAGER] (T03U4EJLT) will stay in checking_fast_reconnect state for up to 60000 ms
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:605] info: [SOCKET-MANAGER] (T03U4EJLT) Attempting to connect to backup region
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:605] info: [SOCKET-MANAGER] (T03U4EJLT) Changing from checking_fast_reconnect to fast_reconnecting
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:605] info: [SOCKET-MANAGER] (T03U4EJLT) will stay in fast_reconnecting state for up to 20000 ms
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:643] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from wait_for_rate_limit to connect
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:645] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in connect state for up to 10000 ms
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:645] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from connect to checking_fast_reconnect
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:645] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in checking_fast_reconnect state for up to 60000 ms
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:646] info: [SOCKET-MANAGER] (T0101Q53BPG) Attempting to connect to primary region
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:646] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from checking_fast_reconnect to prov_connect
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:646] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in prov_connect state for up to 10000 ms
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:646] info: [SOCKET-MANAGER] (T0101Q53BPG) Connecting with token ending: b926
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:646] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from prov_connect to prov_connecting
> Aug 28 10:52:21 pop-os slack.desktop[3332]: [08/28/22, 10:52:21:646] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in prov_connecting state for up to 35000 ms
> Aug 28 10:52:22 pop-os slack.desktop[3332]: [08/28/22, 10:52:22:635] warn: SOCKET-MANAGER (T0390MPHBCN) Socket was closed because #1006: generic error
> Aug 28 10:52:22 pop-os slack.desktop[3332]: [08/28/22, 10:52:22:636] info: [SOCKET-MANAGER] (T0390MPHBCN) Changing from fast_reconnecting to error
> Aug 28 10:52:22 pop-os slack.desktop[3332]: [08/28/22, 10:52:22:636] info: [SOCKET-MANAGER] (T0390MPHBCN) will stay in error state for up to 10000 ms
> Aug 28 10:52:22 pop-os slack.desktop[3332]: [08/28/22, 10:52:22:636] info: [SOCKET-MANAGER] (T0390MPHBCN) Changing from error to wait_for_rate_limit
> Aug 28 10:52:22 pop-os slack.desktop[3332]: [08/28/22, 10:52:22:636] info: [SOCKET-MANAGER] (T0390MPHBCN) will stay in wait_for_rate_limit state for up to 120000 ms
> Aug 28 10:52:22 pop-os slack.desktop[3332]: [08/28/22, 10:52:22:637] info: [SOCKET-MANAGER] (T0390MPHBCN) backing off: will wait for 3298 ms
> Aug 28 10:52:24 pop-os telegramdesktop.desktop[25705]: "No carrier"
> Aug 28 10:52:25 pop-os slack.desktop[3332]: [08/28/22, 10:52:25:707] warn: SOCKET-MANAGER (T07RRCX35) Socket was closed because #1006: generic error
> Aug 28 10:52:25 pop-os slack.desktop[3332]: [08/28/22, 10:52:25:708] info: [SOCKET-MANAGER] (T07RRCX35) Changing from fast_reconnecting to error
> Aug 28 10:52:25 pop-os slack.desktop[3332]: [08/28/22, 10:52:25:708] info: [SOCKET-MANAGER] (T07RRCX35) will stay in error state for up to 10000 ms
> Aug 28 10:52:25 pop-os slack.desktop[3332]: [08/28/22, 10:52:25:709] info: [SOCKET-MANAGER] (T07RRCX35) Changing from error to wait_for_rate_limit
> Aug 28 10:52:25 pop-os slack.desktop[3332]: [08/28/22, 10:52:25:709] info: [SOCKET-MANAGER] (T07RRCX35) will stay in wait_for_rate_limit state for up to 120000 ms
> Aug 28 10:52:25 pop-os slack.desktop[3332]: [08/28/22, 10:52:25:709] info: [SOCKET-MANAGER] (T07RRCX35) backing off: will wait for 14841 ms
> Aug 28 10:52:26 pop-os slack.desktop[3332]: [08/28/22, 10:52:26:605] info: [SOCKET-MANAGER] (T0390MPHBCN) Changing from wait_for_rate_limit to connect
> Aug 28 10:52:26 pop-os slack.desktop[3332]: [08/28/22, 10:52:26:605] info: [SOCKET-MANAGER] (T0390MPHBCN) will stay in connect state for up to 10000 ms
> Aug 28 10:52:26 pop-os slack.desktop[3332]: [08/28/22, 10:52:26:606] info: [SOCKET-MANAGER] (T0390MPHBCN) Changing from connect to checking_fast_reconnect
> Aug 28 10:52:26 pop-os slack.desktop[3332]: [08/28/22, 10:52:26:606] info: [SOCKET-MANAGER] (T0390MPHBCN) will stay in checking_fast_reconnect state for up to 60000 ms
> Aug 28 10:52:26 pop-os slack.desktop[3332]: [08/28/22, 10:52:26:607] info: [SOCKET-MANAGER] (T0390MPHBCN) Attempting to connect to backup region
> Aug 28 10:52:26 pop-os slack.desktop[3332]: [08/28/22, 10:52:26:607] info: [SOCKET-MANAGER] (T0390MPHBCN) Changing from checking_fast_reconnect to fast_reconnecting
> Aug 28 10:52:26 pop-os slack.desktop[3332]: [08/28/22, 10:52:26:607] info: [SOCKET-MANAGER] (T0390MPHBCN) will stay in fast_reconnecting state for up to 20000 ms
> Aug 28 10:52:30 pop-os kernel: [ 7747.126110] [UFW BLOCK] IN=wlp4s0 OUT= MAC=44:af:28:30:96:61:a4:56:cc:bd:dc:61:08:00 SRC=52.40.152.118 DST=10.0.0.169 LEN=145 TOS=0x00 PREC=0x00 TTL=211 ID=33159 DF PROTO=TCP SPT=443 DPT=57976 WINDOW=119 RES=0x00 ACK PSH FIN URGP=0 
> Aug 28 10:52:31 pop-os slack.desktop[3332]: [08/28/22, 10:52:31:950] warn: SOCKET-MANAGER (T0101Q53BPG) Socket was closed because #1006: generic error
> Aug 28 10:52:31 pop-os slack.desktop[3332]: [08/28/22, 10:52:31:951] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from prov_connecting to error
> Aug 28 10:52:31 pop-os slack.desktop[3332]: [08/28/22, 10:52:31:951] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in error state for up to 10000 ms
> Aug 28 10:52:31 pop-os slack.desktop[3332]: [08/28/22, 10:52:31:952] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from error to wait_for_rate_limit
> Aug 28 10:52:31 pop-os slack.desktop[3332]: [08/28/22, 10:52:31:952] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in wait_for_rate_limit state for up to 120000 ms
> Aug 28 10:52:31 pop-os slack.desktop[3332]: [08/28/22, 10:52:31:952] info: [SOCKET-MANAGER] (T0101Q53BPG) backing off: will wait for 1657 ms
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:604] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from wait_for_rate_limit to connect
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:605] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in connect state for up to 10000 ms
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:606] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from connect to checking_fast_reconnect
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:606] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in checking_fast_reconnect state for up to 60000 ms
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:606] info: [SOCKET-MANAGER] (T0101Q53BPG) Attempting to connect to backup region
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:606] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from checking_fast_reconnect to prov_connect
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:607] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in prov_connect state for up to 10000 ms
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:607] info: [SOCKET-MANAGER] (T0101Q53BPG) Connecting with token ending: b926
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:607] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from prov_connect to prov_connecting
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:607] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in prov_connecting state for up to 35000 ms
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:647] info: [SOCKET-MANAGER] (T02KD555Q4X) Changing from wait_for_rate_limit to connect
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:648] info: [SOCKET-MANAGER] (T02KD555Q4X) will stay in connect state for up to 10000 ms
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:648] info: [SOCKET-MANAGER] (T02KD555Q4X) Changing from connect to checking_fast_reconnect
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:648] info: [SOCKET-MANAGER] (T02KD555Q4X) will stay in checking_fast_reconnect state for up to 60000 ms
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:648] info: [SOCKET-MANAGER] (T02KD555Q4X) Attempting to connect to backup region
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:649] info: [SOCKET-MANAGER] (T02KD555Q4X) Changing from checking_fast_reconnect to prov_connect
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:649] info: [SOCKET-MANAGER] (T02KD555Q4X) will stay in prov_connect state for up to 10000 ms
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:649] info: [SOCKET-MANAGER] (T02KD555Q4X) Connecting with token ending: d846
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:649] info: [SOCKET-MANAGER] (T02KD555Q4X) Changing from prov_connect to prov_connecting
> Aug 28 10:52:34 pop-os slack.desktop[3332]: [08/28/22, 10:52:34:649] info: [SOCKET-MANAGER] (T02KD555Q4X) will stay in prov_connecting state for up to 35000 ms
> Aug 28 10:52:34 pop-os telegramdesktop.desktop[25705]: "No carrier"
> Aug 28 10:52:35 pop-os slack.desktop[3332]: [08/28/22, 10:52:35:019] warn: SOCKET-MANAGER (T03U4EJLT) Socket was closed because #1006: generic error
> Aug 28 10:52:35 pop-os slack.desktop[3332]: [08/28/22, 10:52:35:020] info: [SOCKET-MANAGER] (T03U4EJLT) Changing from fast_reconnecting to error
> Aug 28 10:52:35 pop-os slack.desktop[3332]: [08/28/22, 10:52:35:020] info: [SOCKET-MANAGER] (T03U4EJLT) will stay in error state for up to 10000 ms
> Aug 28 10:52:35 pop-os slack.desktop[3332]: [08/28/22, 10:52:35:020] info: [SOCKET-MANAGER] (T03U4EJLT) Changing from error to wait_for_rate_limit
> Aug 28 10:52:35 pop-os slack.desktop[3332]: [08/28/22, 10:52:35:020] info: [SOCKET-MANAGER] (T03U4EJLT) will stay in wait_for_rate_limit state for up to 120000 ms
> Aug 28 10:52:35 pop-os slack.desktop[3332]: [08/28/22, 10:52:35:021] info: [SOCKET-MANAGER] (T03U4EJLT) backing off: will wait for 18503 ms
> Aug 28 10:52:36 pop-os slack.desktop[3332]: [08/28/22, 10:52:36:605] info: [RTM-EVENT-METRICS] Metrics collection sampling has been reset.
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:091] warn: SOCKET-MANAGER (T0390MPHBCN) Socket was closed because #1006: generic error
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:093] info: [SOCKET-MANAGER] (T0390MPHBCN) Changing from fast_reconnecting to error
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:093] info: [SOCKET-MANAGER] (T0390MPHBCN) will stay in error state for up to 10000 ms
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:093] info: [SOCKET-MANAGER] (T0390MPHBCN) Changing from error to wait_for_rate_limit
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:093] info: [SOCKET-MANAGER] (T0390MPHBCN) will stay in wait_for_rate_limit state for up to 120000 ms
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:094] info: [SOCKET-MANAGER] (T0390MPHBCN) backing off: will wait for 9473 ms
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:959] warn: SOCKET-MANAGER (T02KD555Q4X) Socket was closed because #1006: generic error
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:960] info: [SOCKET-MANAGER] (T02KD555Q4X) Changing from prov_connecting to error
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:960] info: [SOCKET-MANAGER] (T02KD555Q4X) will stay in error state for up to 10000 ms
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:960] info: [SOCKET-MANAGER] (T02KD555Q4X) Changing from error to wait_for_rate_limit
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:961] info: [SOCKET-MANAGER] (T02KD555Q4X) will stay in wait_for_rate_limit state for up to 120000 ms
> Aug 28 10:52:38 pop-os slack.desktop[3332]: [08/28/22, 10:52:38:961] info: [SOCKET-MANAGER] (T02KD555Q4X) backing off: will wait for 1717 ms
> Aug 28 10:52:39 pop-os slack.desktop[3332]: [08/28/22, 10:52:39:604] info: [DND_V2] (T0101Q53BPG) Checking for changes in DND status for the following members: U03A3PAQPED,U01058354HG
> Aug 28 10:52:39 pop-os slack.desktop[3332]: [08/28/22, 10:52:39:605] info: [DND_V2] (T0101Q53BPG) Will check for changes in DND status again in 5 minutes
> Aug 28 10:52:40 pop-os slack.desktop[3332]: [08/28/22, 10:52:40:606] info: [SOCKET-MANAGER] (T07RRCX35) Changing from wait_for_rate_limit to connect
> Aug 28 10:52:40 pop-os slack.desktop[3332]: [08/28/22, 10:52:40:606] info: [SOCKET-MANAGER] (T07RRCX35) will stay in connect state for up to 10000 ms
> Aug 28 10:52:40 pop-os slack.desktop[3332]: [08/28/22, 10:52:40:607] info: [SOCKET-MANAGER] (T07RRCX35) Changing from connect to checking_fast_reconnect
> Aug 28 10:52:40 pop-os slack.desktop[3332]: [08/28/22, 10:52:40:607] info: [SOCKET-MANAGER] (T07RRCX35) will stay in checking_fast_reconnect state for up to 60000 ms
> Aug 28 10:52:40 pop-os slack.desktop[3332]: [08/28/22, 10:52:40:607] info: [SOCKET-MANAGER] (T07RRCX35) Attempting to connect to primary region
> Aug 28 10:52:40 pop-os slack.desktop[3332]: [08/28/22, 10:52:40:607] info: [SOCKET-MANAGER] (T07RRCX35) Changing from checking_fast_reconnect to prov_connect
> Aug 28 10:52:40 pop-os slack.desktop[3332]: [08/28/22, 10:52:40:607] info: [SOCKET-MANAGER] (T07RRCX35) will stay in prov_connect state for up to 10000 ms
> Aug 28 10:52:40 pop-os slack.desktop[3332]: [08/28/22, 10:52:40:608] info: [SOCKET-MANAGER] (T07RRCX35) Connecting with token ending: a5e0
> Aug 28 10:52:40 pop-os slack.desktop[3332]: [08/28/22, 10:52:40:608] info: [SOCKET-MANAGER] (T07RRCX35) Changing from prov_connect to prov_connecting
> Aug 28 10:52:40 pop-os slack.desktop[3332]: [08/28/22, 10:52:40:608] info: [SOCKET-MANAGER] (T07RRCX35) will stay in prov_connecting state for up to 35000 ms
> Aug 28 10:52:41 pop-os slack.desktop[3332]: [08/28/22, 10:52:41:604] info: [SOCKET-MANAGER] (T02KD555Q4X) Changing from wait_for_rate_limit to connect
> Aug 28 10:52:41 pop-os slack.desktop[3332]: [08/28/22, 10:52:41:605] info: [SOCKET-MANAGER] (T02KD555Q4X) will stay in connect state for up to 10000 ms
> Aug 28 10:52:41 pop-os slack.desktop[3332]: [08/28/22, 10:52:41:605] info: [SOCKET-MANAGER] (T02KD555Q4X) Changing from connect to checking_fast_reconnect
> Aug 28 10:52:41 pop-os slack.desktop[3332]: [08/28/22, 10:52:41:605] info: [SOCKET-MANAGER] (T02KD555Q4X) will stay in checking_fast_reconnect state for up to 60000 ms
> Aug 28 10:52:41 pop-os slack.desktop[3332]: [08/28/22, 10:52:41:606] info: [SOCKET-MANAGER] (T02KD555Q4X) Attempting to connect to primary region
> Aug 28 10:52:41 pop-os slack.desktop[3332]: [08/28/22, 10:52:41:606] info: [SOCKET-MANAGER] (T02KD555Q4X) Changing from checking_fast_reconnect to prov_connect
> Aug 28 10:52:41 pop-os slack.desktop[3332]: [08/28/22, 10:52:41:606] info: [SOCKET-MANAGER] (T02KD555Q4X) will stay in prov_connect state for up to 10000 ms
> Aug 28 10:52:41 pop-os slack.desktop[3332]: [08/28/22, 10:52:41:607] info: [SOCKET-MANAGER] (T02KD555Q4X) Connecting with token ending: d846
> Aug 28 10:52:41 pop-os slack.desktop[3332]: [08/28/22, 10:52:41:607] info: [SOCKET-MANAGER] (T02KD555Q4X) Changing from prov_connect to prov_connecting
> Aug 28 10:52:41 pop-os slack.desktop[3332]: [08/28/22, 10:52:41:607] info: [SOCKET-MANAGER] (T02KD555Q4X) will stay in prov_connecting state for up to 35000 ms
> Aug 28 10:52:42 pop-os slack.desktop[3332]: [08/28/22, 10:52:42:027] warn: SOCKET-MANAGER (T0101Q53BPG) Socket was closed because #1006: generic error
> Aug 28 10:52:42 pop-os slack.desktop[3332]: [08/28/22, 10:52:42:029] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from prov_connecting to error
> Aug 28 10:52:42 pop-os slack.desktop[3332]: [08/28/22, 10:52:42:029] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in error state for up to 10000 ms
> Aug 28 10:52:42 pop-os slack.desktop[3332]: [08/28/22, 10:52:42:029] info: [SOCKET-MANAGER] (T0101Q53BPG) Changing from error to wait_for_rate_limit
> Aug 28 10:52:42 pop-os slack.desktop[3332]: [08/28/22, 10:52:42:029] info: [SOCKET-MANAGER] (T0101Q53BPG) will stay in wait_for_rate_limit state for up to 120000 ms
> Aug 28 10:52:42 pop-os slack.desktop[3332]: [08/28/22, 10:52:42:030] info: [SOCKET-MANAGER] (T0101Q53BPG) backing off: will wait for 3451 ms
> Aug 28 10:52:44 pop-os telegramdesktop.desktop[25705]: "No carrier"
> 

Any suggestions?

**Comment by milas** [comment]
Unfortunately, this does not appear to be a Compose-specific issue, and we can't really provide support for this problem, so I'm closing this issue.
