### ISSUE TITLE
"docker compose" vs "docker-compose" question

### ISSUE THREAD

**Issue by dimadeush** [docker/compose#9814]
Hello Docker Team
Thanks for the great software that allow us simplify our development world when using Docker and Docker compose.
But every time when I'm installing docker compose v2 I can see that docker-compose is not the same as docker compose (Docker desktop). Even some time ago such things lead to some misunderstanding when reading documentation how to install docker compose and also you have there something like next: "Compose V2 integrates compose functions into the Docker platform, continuing to support most of the previous docker-compose features and flags". So does it means most but not all? Do we have list with params that are not supporting?
Is it possible to have single command as "docker-compose" in order to simplify our world and skip implementing logic for every software which command available "docker-compose" or "docker compose"?
As I understood in most cases when we have "docker compose" we don't need to install "docker-compose" and vice versa. So is it possible to have one universal single command as "docker-compose"?

With hope
Thanks in Advance

**Comment by glours** [comment]
Hello @dimadeush 

Compose v1 is end-of-life, you definitely should use Compose v2.

You will find all the differences between Compose v1 and Compose v2 in this page of the [official documentation](https://docs.docker.com/compose/cli-command-compatibility/)

If you're using Docker Desktop both `docker-compose` and `docker compose` command should use Compose v2 by default. You can double check in Docker Desktop preferences that `Use Docker Compose v2` is checked
<img width="1214" alt="Screenshot 2022-09-07 at 10 36 31" src="https://user-images.githubusercontent.com/705411/188831834-85e613d4-592d-46de-adbf-42125f8e518e.png">

On Linux system, the best option for you is to symlink the compose v2 binary to `docker-compose` (or alias it), [see this documentation page](https://docs.docker.com/compose/install/other/#install-compose-standalone)

**Comment by dimadeush** [comment]
Hello @glours 

Thanks for the response. I'm using compose v2 standalone and "docker-compose" command is working without making symlink (and you already have such notes in docs - "Note that Compose standalone uses the dash compose syntax instead of current’s standard syntax (space compose)."). I just asked if it is possible to have possibility to use dash compose syntax for both just after installing. In other case every user need to create symlink or ask why "docker-compose" command not found if using desktop version.

Thanks

**Comment by glours** [comment]
With Docker Desktop, you don't need to do the symlink, just be sure the `Use Docker Compose v2` is checked and both `docker compose` and `docker-compose` will use the v2 version

**Comment by glours** [comment]
Did you have any other questions or could I close the issue?

**Comment by dimadeush** [comment]
I don't have another question, thanks.

**Comment by Anutrix** [comment]
'Use Docker Compose v2' is missing in latest Docker Desktop. `docker-compose` not longer works.
