### ISSUE TITLE
ignore_pull_failures is ignored when using parallel_pull=True

### ISSUE THREAD

**Issue by Berndone** [docker/compose#9815]
We are using docker-compose from another Python-Skript. We know that it is not officially supported, still the error is quite simple to fix and may occur in other situations as well.

When using the Method `Project.pull` the Parameter `igore_pull_failures` will be ignored when using `parallel_pull=True` (which is default).
So `project.pull(ignore_pull_failures=True)` will still throw errors.

```
    def pull(self, service_names=None, ignore_pull_failures=False, parallel_pull=True, silent=False,
             include_deps=False):
        services = self.get_services(service_names, include_deps)

        if parallel_pull:
            self.parallel_pull(services, silent=silent)
[...]
    def parallel_pull(self, services, ignore_pull_failures=False, silent=False):
```
As `parallel_pull` supports the parameter too this should be easy to fix.

**Comment by glours** [comment]
Thanks for taking the time to create this issue/pull request!

Unfortunately, Docker Compose V1 has reached end-of-life and we are not accepting any more changes (except for security issues). Please try and reproduce your issue with Compose V2 or rewrite your pull request to be based on the v2 branch and create a new issue or PR with the relevant Compose V2 information.
