### ISSUE TITLE
Setting mac address for container

### ISSUE THREAD

**Issue by dhauenstein** [docker/compose#982]
Hi,
is there any way of setting a container's mac address (docker run parameter `--mac-address`) in the fix/compose config file? Or any additional parameters at all?

I'd really love to see this feature implemented to allow low-level access to the containers, if needed. 

Cheers,
Daniel

**Comment by aanand** [comment]
Added to #754

**Comment by dnephin** [comment]
Looks like we've added this http://docs.docker.com/compose/yml/#working-dir-entrypoint-user-hostname-domainname-mac-address-mem-limit-memswap-limit-privileged-restart-stdin-open-tty-cpu-shares-cpuset-read-only-volume-driver

**Comment by ousema2003** [comment]
This is an example of docker-compose.yml with mac address : 


version: '2'

services:

    app_service_1:
        image: app/service_1
        mac_address: 02:42:ac:11:65:41
        expose:
            - "9090"

    app_service_1:
        image: app/service_2
        mac_address: 02:42:ac:11:65:43
        expose:
            - "5558"
