### ISSUE TITLE
`docker compose` bind mounts with incorrect "source" path when using yaml config from subdirectories

### ISSUE THREAD

**Issue by mjarosie** [docker/compose#9825]
**Description**

When using `docker-compose.yaml` files from subdirectories and bind mounting directories in corresponding subdirectories, `docker compose` will mount volumes with incorrect "source" path (the directory of the `docker-compose.yaml` file specified by the first `-f` parameter).

**Steps to reproduce the issue:**
```bash
# Set up data
mkdir -p subdirectory-a/some-data-dir subdirectory-b/some-data-dir
echo "test a" >> subdirectory-a/some-data-dir/hello-a.txt
echo "test b" >> subdirectory-b/some-data-dir/hello-b.txt

# Set up docker compose config
cat > subdirectory-a/docker-compose.yaml<< EOF
version: "3.9"
services:
  db-a:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./some-data-dir:/some-data-dir
EOF
cat > subdirectory-b/docker-compose.yaml<< EOF
version: "3.9"
services:
  db-b:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./some-data-dir:/some-data-dir
EOF

# Replicate the issue
docker compose -p test -f subdirectory-a/docker-compose.yaml -f subdirectory-b/docker-compose.yaml up -d
docker exec -it test-db-a-1 bash -c "ls /some-data-dir" # Outputs: `hello-a.txt`
docker exec -it test-db-b-1 bash -c "ls /some-data-dir" # Outputs: `hello-a.txt` - that's not correct!
docker inspect test-db-a-1 | jq .[0].HostConfig.Binds
docker inspect test-db-b-1 | jq .[0].HostConfig.Binds
docker compose -p test -f subdirectory-a/docker-compose.yaml -f subdirectory-b/docker-compose.yaml down --volumes --remove-orphans
```

Repository reproducing the issue is also available [here](https://github.com/mjarosie/docker-compose-subdirectories-mount-issue).

**Describe the results you received:**

The service run from the `subdirectory-b/docker-compose.yaml` contains data coming from `subdirectory-a/some-data-dir` directory.

Inspecting the content of `some-data-dir` shows that both containers have a single bind mount source.

Invoking `docker inspect test-db-a-1 | jq .[0].HostConfig.Binds` outputs:

```json
["/home/user/path-to-project/subdirectory-a/some-data-dir:/some-data-dir:rw"]
```

Invoking `docker inspect test-db-b-1 | jq .[0].HostConfig.Binds` outputs the same bind mount source directory as `test-db-a-1` service, coming from `subdirectory-a`:

```json
["/home/user/path-to-project/subdirectory-a/some-data-dir:/some-data-dir:rw"]
```

If you switch the order of `-f` parameters, the source of bind mount directory changes in both containers.

**Describe the results you expected:**

I'd expect the service run from the `subdirectory-a/docker-compose.yaml` to be mounted with `subdirectory-a/some-data-dir` directory and service run from the `subdirectory-b/docker-compose.yaml` to be mounted with `subdirectory-b/some-data-dir` directory when running `docker compose` with config files located in subdirectories.

**Output of `docker compose version`:**

```
Docker Compose version v2.2.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)
WARNING: Plugin "/usr/libexec/docker/cli-plugins/docker-app" is not valid: failed to fetch metadata: fork/exec /usr/libexec/docker/cli-plugins/docker-app: no such file or directory

Server:
 Containers: 19
  Running: 10
  Paused: 0
  Stopped: 9
 Images: 59
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.104-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 12.26GiB
 Name: docker-desktop
 ID: RJV5:NX2V:3YCR:WTEA:BDSC:TTW4:TUSI:V5CS:FE6I:B7Z4:AOVR:6HLY
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 143
  Goroutines: 185
  System Time: 2022-09-10T11:28:14.9876083Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details:**

I'm running Ubuntu-20.04 on WSL2.

**Comment by thaJeztah** [comment]
I think this is the expected behavior. When providing multiple compose files, compose merges their configuration, and paths are evaluated relative to the "primary"  (the first compose file in the list) compose file's location, which in this case is `subdirectory-a/docker-compose.yaml`. So all relative paths are evaluated relative to `subdirectory-a`;

```bash
docker compose -p test -f subdirectory-a/docker-compose.yaml -f subdirectory-b/docker-compose.yaml config
name: test
services:
  db-a:
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:8.0
    networks:
      default: null
    volumes:
    - type: bind
      source: /Users/thajeztah/Projects/test/repro-9825/subdirectory-a/some-data-dir
      target: /some-data-dir
      bind:
        create_host_path: true
  db-b:
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:8.0
    networks:
      default: null
    volumes:
    - type: bind
      source: /Users/thajeztah/Projects/test/repro-9825/subdirectory-a/some-data-dir
      target: /some-data-dir
      bind:
        create_host_path: true
networks:
  default:
    name: test_default
```

Unfortunately this is somewhat ambiguous, and there's no "right" or "wrong" way to evaluate these paths, as different use-cases expect a different outcome. For that reason, I opened a proposal in the compose-spec to introduce variables that can be used to allow the user to express the intent and to disambiguate these cases; see my proposal here;

- https://github.com/compose-spec/compose-spec/issues/248

**Comment by mjarosie** [comment]
Ah ok that makes sense. In the meantime I've also found a similar topic with a few workarounds already suggested (e.g. [this one](https://github.com/docker/compose/issues/3874#issuecomment-377162033)) so I'll close this issue here as a duplicate. Thanks for your fast response 👍 .
