### ISSUE TITLE
error: can't find Rust compiler

### ISSUE THREAD

**Issue by raspman** [docker/compose#9834]
Hello,

Even though I have Rustc version 1.63.00 installed (verified with rustc --version,) I continue to get the below error on the following command:
sudo pip3 install docker-compose

Upgrading the PIP does nothing to resolve the issue:

         Python: 3.9.2
          platform: Linux-5.15.61-v7l+-armv7l-with-glibc2.31
          pip: 22.2.2
          setuptools: 65.3.0
          setuptools_rust: 1.5.1
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================
      
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      
      This package requires Rust >=1.56.0.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bcrypt
Failed to build bcrypt
ERROR: Could not build wheels for bcrypt, which is required to install pyproject.toml-based projects

**Comment by glours** [comment]
Hey @raspman 
Can you give us more details about what you try to achieve? 
What is your compose version, your OS? 
Can you share your compose file? 
If we don't have more details and steps to reproduce, we'll close the issue

**Comment by raspman** [comment]
Hi, following a guide to get docker set up to run Nginx Reverse Proxy - this is part of the process of getting that set up. 

OS Version:

RETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian

Docker Version:

Docker version 20.10.18, build b40c2f6

Not sure what a compose file is...thank you

**Comment by glours** [comment]
This is the issue tracker of Docker Compose, so if you don't use a command starting with `docker compose` or `docker-compose` and using a file named `compose.yaml` or `docker-compose.yaml`, you're not at the right place. 

You should fine help in the [community slack](https://join.slack.com/t/dockercommunity/shared_invite/zt-1fwnj63qd-Es~KuL~pFHnzXcUcE25d_Q) or [community forums](https://forums.docker.com/)

I close this issue as you're problem don't concern Docker Compose

**Comment by poklutom** [comment]
Hey @raspman,
did you solve the issue?
I have the same problem with calling:

sudo pip3 install docker-compose

Docker / Docker-compose on Raspberry PI installation steps from: https://dev.to/elalemanyo/how-to-install-docker-and-docker-compose-on-raspberry-pi-1mo

**Comment by raspman** [comment]
Nope.

**Comment by poklutom** [comment]
I found 2 solutions in meantime worked for me:
- install Docker compose described here: https://greenfrognest.com/lmdsondocker.php
or
- install Raspberry PI OS (64 BIT)

**Comment by anadahz** [comment]
re: https://github.com/docker/compose/issues/8105

**Comment by sillmnvg** [comment]
> I found 2 solutions in meantime worked for me:
> 
>     * install Docker compose described here: https://greenfrognest.com/lmdsondocker.php
>       or
> 
>     * install Raspberry PI OS (64 BIT)

Can confirm using 64 bit of rasbian solved this issue for me.
