### ISSUE TITLE
Stop Instance Without Stopping Other Instances in depends_on Chain

### ISSUE THREAD

**Issue by trisys3** [docker/compose#9838]
**Description**

I often start all my docker instances individually, even when one of them depends on another one. This is so that I can see all the errors & logs individually, which is less confusing, especially during debugging. However, there are a couple instances that I keep running, as they are simple and/or I do not maintain those instances.

After I start all my instances, if I stop one of the instances higher in the chain, all the instances it depends on also stop. This happens even when the instance(s) lower in the chain are started as daemons, with `-d`, as well as when they are started in the background, disowned, etc., with e.g. `>/dev/null 2>/dev/null & disown`.

This seems like a bug, because I started all the instances in sequence, not all at once. However, if it is a feature, could there be a CLI option to avoid it? I'd guess the option would make the most sense on the later invocations, for the instances higher on the dependency chain, but I'm not familiar with the internals of docker.

**Steps to reproduce the issue:**
1. Create a `docker-compose.yml` with 2 instances, `web` and `postgres`, where the `web` instance `depends_on` `postgres`. An example is given below, which is based on the example in the main docker-compose documentation, at https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on.
2. `docker compose up -d postgres`
3. `docker compose up web`
4. Ctrl-C

docker-compose.yml:
```
version: "3.9"
services:
  web:
    build: .
    depends_on:
      - postgres
  postgres:
    image: postgres
```

**Describe the results you received:**

Both the web and postgres instances are stopped.

**Describe the results you expected:**

Only the web instance is stopped.

**Additional information you deem important (e.g. issue happens only occasionally):**

Using `docker desktop`, instances higher in the chain are not always stopped when instances lower in the chain are stopped.

**Output of `docker compose version`:**

```
Docker Compose version v2.7.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.7.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.8)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 7
  Running: 0
  Paused: 0
  Stopped: 7
 Images: 6
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.676GiB
 Name: docker-desktop
 ID: PNQO:VQSE:VN5N:AAWH:LUDJ:76PU:7UR3:JT62:MKBN:GOBX:MIZX:3GGF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

Mac OSX Monterey version 12.5.1

**Comment by laurazard** [comment]
Hi @trisys3, thanks for the report!

This is expected behavior --  when starting your last service with `compose up web`, it's expected that it also creates/starts it's dependencies, and as such that it also stops them when it is cancelled -- the fact that they are already running doesn't change that.

What you could do if you want to run `web` without tearing down it's dependencies when you stop the execution is run it with the `--no-deps` flag, such as `compose up --no-deps web`.

**Comment by trisys3** [comment]
One thing I don't understand is that starting one of the higher instances, in this case `postgres`, doesn't automatically start its dependencies, in this case `web`, but stopping `postgres` also stops `web`. Why the disconnect?

I'll remember the `--no-deps` option, didn't realize that's what it's for! The documentation makes it seem like that's the opposite of what it does.

**Comment by laurazard** [comment]
I'm not sure what you mean by "higher instances" -- in this case, `postgres` is a dependency of `web`, not the other way around -- so starting `postgres` doesn't start `web`, but starting `web` (under normal circumstances) starts `postgres`.

@trisys3 the intent behind the `--no-deps` flag is that dependencies are ignored, both when starting and tearing down. So in this case you can use it when running `web` to stop it's dependencies being torn down.

**Comment by trisys3** [comment]
Sorry, that's what I mean. Starting `web` doesn't start `postgres` when I start them all individually. The fact that it doesn't may be a result of how the services are set up, in the `docker-compose.yml`. Regardless, `--no-deps` will really help.

My main question has been answered, so I'll close.

**Comment by laurazard** [comment]
I'm glad I helped! Regarding `starting web` doesn't start `postgres` when you start them individually, do you mean it doesn't start it when you have already started `postgres`?

If you run `compose up web` and `postgres` is not already running, it should be started 😅

**Comment by laurazard** [comment]
Also @trisys3, looks like I misspoke -- I just went and tested this on a recent compose version and it seems to work as expected -- running `compose up web`, then hitting `CTRL-C` should leave `postgres` running and only stop `web`. Could you try using a more recent version of compose and seeing if it behaves how you expect?

**Comment by trisys3** [comment]
All this behaves as expected. I still think daemons or instances you started manually shouldn't stop when you stop dependents, but I will use `--no-deps` when I need to work around this.

I'm using the latest version of docker.
