### ISSUE TITLE
Cannot run executable under macOS 12.6

### ISSUE THREAD

**Issue by slhck** [docker/compose#9850]
**Description**

I cannot run the download under macOS 12.6.

This used to work at some point in the past.

**Steps to reproduce the issue:**
1. Download the latest `darwin-aarch64` build (e.g. https://github.com/docker/compose/releases/download/v2.11.0/docker-compose-darwin-aarch64)
2. Make it executable
3. Execute it

**Describe the results you received:**

I get this popup saying:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/582444/190438798-508ce2a8-8b65-49af-975c-7538170913d5.png">

> “docker-compose-darwin-aarch64” can’t be opened because Apple cannot check it for malicious software.

> This software needs to be updated. Contact the developer for more information.

**Describe the results you expected:**

Simply getting the command to run.

**Output of `docker compose version`:** N/A

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.1)
  extension: Manages Docker extensions (Docker Inc., v0.2.7)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 13
  Running: 10
  Paused: 0
  Stopped: 3
 Images: 25
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.765GiB
 Name: docker-desktop
 ID: AHQ4:XYZN:ZMAD:GIXG:IKZT:I7CA:PC72:JJRN:IBRL:AO4R:UFJN:22LF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by laurazard** [comment]
Hi @slhck, thanks for the report.

This isn't new, and has to do with the fact that, currently, Docker Compose binaries distributed through GitHub aren't notarized.

Docker Compose binaries that are packaged alongside Docker Desktop for Mac releases are notarized, and don't face this issue.

As a workaround, you can follow the [instructions here](https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac) to bypass that screen.

**Comment by slhck** [comment]
Okay, fair enough, thanks! I just didn't see any previous issues related to this. I'm gonna copy the steps here:

> * Control-click the app icon, then choose Open from the shortcut menu.
> * Click Open.
> * The app is saved as an exception to your security settings, and you can open it at any time by double-clicking it, just as you do with any registered app.

It would maybe make sense to add this somewhere to the documentation? I do see standalone install steps for Linux/Windows, but not macOS.
