### ISSUE TITLE
Support short syntax for volumes in "docker compose config" output

### ISSUE THREAD

**Issue by jeverling** [docker/compose#9881]
**Description**

When you run `docker compose config`, volumes are rendered in [long syntax](https://docs.docker.com/compose/compose-file/compose-file-v3/#long-syntax-3). However, some services like ECS and I think even Docker Swarm (not sure about that) need volumes to be described using [short syntax](https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3).

So instead of `- minio_data:/data` _docker compose config_ returns

```
    - type: volume
      source: minio_data
      target: /data
      volume: {}
```

It would be great, if this was configurable so `docker compose config` can be used to return either short or long syntax where applicable, according to user choice.

`docker compose version`: _Docker Compose version v2.10.2_

**Comment by 26tanishabanik** [comment]
Is anyone working on this issue, @nicksieger , @jeverling ?

**Comment by ndeloof** [comment]
`docker compose config` _by design_ is expected to render the actual model, and doing so the full volume syntax.
What's your use-case to require short syntax? Can't you just get ECS or Swarm to directly parse your compose file(s)?

**Comment by jeverling** [comment]
> Is anyone working on this issue, @nicksieger , @jeverling ?

Hi, I am not, alas I'm not fluent enough in Go currently.

> `docker compose config` _by design_ is expected to render the actual model, and doing so the full volume syntax. What's your use-case to require short syntax? Can't you just get ECS or Swarm to directly parse your compose file(s)?

We use it to combine multiple compose files in CI, to dynamically generate a compose file that is then used to start up temporary review deployments on ECS fargate.
I'm sure we can find a workaround that doesn't require `docker compose config` or we can modify the file as needed. I was just thinking having the option to use both syntax's would be worthwhile.

**Comment by ndeloof** [comment]
> We use it to combine multiple compose files in CI, to dynamically generate a compose file that is then used to start up temporary review deployments on ECS fargate

Which tool are you using for this purpose?
"long syntax" is not something new, has been valid in compose syntax since `version: "2"` AFAICT, so it's surprising your tooling doesn't support it.

**Comment by jeverling** [comment]
We are using [ecs-cli ](https://github.com/aws/amazon-ecs-cli) to do the deployment of the review application (the compose file is set via `COMPOSE_FILE` variable here): `ecs-cli compose --verbose --ecs-params ecs-params.yml up --launch-type FARGATE --cluster ${ECS_CLUSTER}`

When doing this with a compose file that uses long syntax for volumes, we get the following error message:

```
time="2022-12-08T11:38:59Z" level=debug msg="Parsing the compose yaml..."
time="2022-12-08T11:38:59Z" level=debug msg="Docker Compose version found: 3"
time="2022-12-08T11:38:59Z" level=debug msg="Parsing v3 project..."
time="2022-12-08T11:38:59Z" level=error msg="Unable to open ECS Compose Project" error="services.minio.volumes.0 must be a string"
time="2022-12-08T11:38:59Z" level=fatal msg="Unable to create and read ECS Compose Project" error="services.minio.volumes.0 must be a string"
```

With short syntax, it works as expected.
docker-compose v1 was generating short syntax (or probably rather just keeping it from the source file), whereas v2 generates long syntax.
But you are right, ideally ecs-cli should be able to convert it.

**Comment by jeverling** [comment]
There is not an issue for this yet in the ecs-cli repo, and I haven't opened one because if docker compose v2 supported short syntax it wouldn't be necessary.
If you don't feel it's a worthwhile addition I'm fine with closing this issue.

**Comment by ndeloof** [comment]
As the long syntax is a fully valid one, and is far from being a new addition to the compose file format, you should report this missing support to ecs-cli.
thanks
