### ISSUE TITLE
docker-compose up re-creates container when it shouldn't

### ISSUE THREAD

**Issue by g-lashuk** [docker/compose#9897]
**Description**

Hello, I have the following test.yml:

```
version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
```
Running   `docker-compose -p test-container -f test.yaml up -d` leads to image pulling and creating container

![image](https://user-images.githubusercontent.com/84844620/194354348-cbe3cfac-1a96-4de4-aa7c-b4f08a195c9a.png)

However, the second run of the same `docker-compose -p test-container -f test.yaml up -d` command without any changes in test.yaml file leads to container re-creation:
![image](https://user-images.githubusercontent.com/84844620/194355682-0a672631-9ada-4e4e-9876-f192b20c950b.png)

It, seems to be unexpected because all subsequent runs of the same command do not recreate the container:
![image](https://user-images.githubusercontent.com/84844620/194356188-3e41e354-6ab6-4f67-85f5-1db1ebbeb3a3.png)

**Steps to reproduce the issue:**
1. Create docker-compose.yaml file with any image that is not presented locally and should be pulled first (rabbit-mq was used as example)
2. run docker-compose up for the first time (it pulls and creates the container)
3. run docker-compose up for the second time

**Describe the results you received:**
The second run recreates container, which was created

**Describe the results you expected:**
As far as I undestand the container should not be recreated because the configuration has not been changed plus all subsequent runs of the same command do not recreate the container 

**Additional information you deem important (e.g. issue happens only occasionally):**

 - The issue is reproduced exactly at the second run of `docker-compose up `command after pulling image that is not presented locally.
- The benavior does not depend on the image used in test.yaml file (as far as I noticed the only precondition is that the first run of docker-compose up pulls an image and as a result, only the next run recreates container )

**Output of `docker compose version`:**

```
Docker Compose version v2.10.2
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 210
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.832GiB
 Name: docker-desktop
 ID: 4RBP:FM7U:MTXJ:Q4B2:72WV:EDCU:74LD:VWZZ:K7S4:JE3Z:OXML:XXCH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**

**Comment by famod** [comment]
I think I have seen this as well.

Have you tried 2.11.2 by any chance?

**Comment by g-lashuk** [comment]
> I think I have seen this as well.
> 
> Have you tried 2.11.2 by any chance?

@famod 
No, I haven't. Anyway, maybe you know any workaround?

**Comment by famod** [comment]
@g-lashuk not a general workaround, but in a specific case I just wanted to restart a service and the `restart` command did not show this issue

**Comment by swingbit** [comment]
I'm having this problem as well (2.12.0), but in my case it seems unrelated to downloading images.

Images are being stable, they haven't changed for weeks, `docker-compose.yml` doesn't change, no service config hash changes (`docker-compose config --hash <service>`) . And yet, a `docker compose run `serviceA` recreates the container of the linked `serviceB` (serviceA depends_on serviceB`).

Similarly to this case though, repeating the same `run` does not trigger the recreation again. It seems to just happen once a day (although I'm sure the real reason is less trivial than that).

**Comment by ndeloof** [comment]
Labels set on initial `compose up` command which pulls images:
```
{
  "com.docker.compose.config-hash": "676bad171670f24019ac5ff8dda896f8329de3db63ad98faf33a9c9744712d25",
  "com.docker.compose.container-number": "1",
  "com.docker.compose.depends_on": "",
  "com.docker.compose.oneoff": "False",
  "com.docker.compose.project": "test-container",
  "com.docker.compose.project.config_files": "/Users/nicolas/truc/9897/compose.yml",
  "com.docker.compose.project.working_dir": "/Users/nicolas/truc/9897",
  "com.docker.compose.service": "rabbitmq",
  "com.docker.compose.version": "2.14.0"
}
```

Labels set after second `compose up` which unexpectedly recreates containers:
```
{
  "com.docker.compose.config-hash": "676bad171670f24019ac5ff8dda896f8329de3db63ad98faf33a9c9744712d25",
  "com.docker.compose.container-number": "1",
  "com.docker.compose.depends_on": "",
  "com.docker.compose.image": "sha256:05d008bbd58111df4e6d80c9423f082137dedb1b221f7be747c5186c0b70a91d",
  "com.docker.compose.oneoff": "False",
  "com.docker.compose.project": "test-container",
  "com.docker.compose.project.config_files": "/Users/nicolas/truc/9897/compose.yml",
  "com.docker.compose.project.working_dir": "/Users/nicolas/truc/9897",
  "com.docker.compose.service": "rabbitmq",
  "com.docker.compose.version": "2.14.0"
}
```

=> After pull, we don't set the `com.docker.compose.image` label with pulled digest, which makes a later `compose up` run consider the existing container(s) to be running obsolete image(s)

**Comment by swingbit** [comment]
@ndeloof Do you have any suggestion for how to further debug my case, which does not depend on pull? I have already verified that config hashes do not change. What else could I monitor?

**Comment by ndeloof** [comment]
@swingbit you could compare container labels ( ` docker inspect <name>  -f '{{json .Config.Labels}}' | jq .`) to double check anything changed between compose commands, which could explain this buggy behavior

**Comment by swingbit** [comment]
@ndeloof I see now what  happens. My case is indeed related to this issue in a way.

Inspecting the labels I see that `com.docker.compose.image` hash changes, which is what triggers the recreate.

However, the image hasn't changed at all for 4 weeks now, so that label change is somehow wrong.

**Comment by ndeloof** [comment]
@swingbit did you maybe switched between compose v1 and compose v2 in the meantime? (we can't reliably reproduce python hash computation within the Go codebase).
The hash label doesn't include the image digest (so the `com.docker.compose.image` label) so it _should_ only reflect some changes in your compose.yaml configuration

**Comment by swingbit** [comment]
@ndeloof no, it was always v2 and always the same version.

But - apologies for the confusion - I was mistaken: `com.docker.compose.image` does NOT change, while `com.docker.compose.config-hash` DOES change. 

Still I don't know why it changes. Nothing that I can think of has change in the past few weeks, while this happens every day.

**Comment by DXist** [comment]
I confirm strange recreation when I do `docker-compose run --rm my_service_with_oneoff_tools`. The service defines `depends_on` the db service and the db doesn't have the expected users.

The issue is not reproduced with older version of docker-compose (docker-compose version 1.27.4, build 40524192)

**Comment by amotl** [comment]
Hi @DXist. We are also observing the same on GHA, so we used your comment to stage a separate issue. Thank you.

- GH-13769
