### ISSUE TITLE
docker-compose / docker and signals

### ISSUE THREAD

**Issue by CyberGitJul** [docker/compose#9903]
Hi,

I want to write an entrypoint that should exit the execution with an error > 0 (terminating the active container) , when someone triggers it concurrently with docker exec (or from within the container) or another container instance.

It is supposed to do that with an pid file, that is written in a mounted volume.

Looks like this

entrypoint.sh

```

#!/bin/bash
/entrypoint/entrypoint_worker.sh


```
entrypoint_worker.sh:

```
#!/bin/bash
. /entrypoint/pid_handling
sleep 100
```

pid_handling (now it gets interesting)
```

#!/bin/bash

#set -x

current_pid=$$
script_name=$(basename $0)
#pid_file=/pid_files/${script_name%.*}.pid
pid_file=/entrypoint/${script_name%.*}.pid

trap cleanup 1 2 3 6 9 19

cleanup ()
{
    echo "entering trap"
    rm "$pid_file" -rf
}


echo "the current pid of this script is $current_pid"

if [ -e "${pid_file}" ];
then
    entrypoint_pid=$(cat $pid_file)

    if [ -e "/proc/${entrypoint_pid}" ] && [  -e "/proc/${entrypoint_pid}/exe" ];
    then
        echo "des laft"
        exit 1
    else
        echo "Found no process for pid in pidfile. Updating pidfile"
        echo -n "${current_pid}" > $pid_file
    fi
else
    echo "Creating new pidfile"
    echo -n "${current_pid}" > $pid_file
fi
#chown app: ${pid_file}
```

For different reasons I mount the entrypoint into the container, rather then putting it into the image

Now, 
when I run 
`
docker run --rm -it -v $(pwd)/:/entrypoint/ testimage`

and press ctrl+c right away, the pidfile gets deleted, like it is supposed (because of the trap)

When I put all of that into an docker-compose:

```
version: '3'

services:
  test:
    image: 'testimage'
    container_name: 'test'
    volumes:
      - ./:/entrypoint/
```

and start it up with 
`
docker-compose up`

The services start, but when I press ctrl+c now the services are stopping (takes awhile despite the shot script :-( ), but the pid file won´t get removed :-(

Is that a bug, or a feature ?  :-)

Thanks and Greetings,

Julian

**Comment by ndeloof** [comment]
running `docker compose up` isn't interactive as `docker run` is, i.e. ctrl+c is not forwarded to your container - which one? remember compose run a set of services - but caught by the command line and used to trigger application shutdown.

to send a signal to your container, you should use `docker kill --signal` or `docker compose kill --signal`


```
$ docker compose up
[+] Building 0.0s (0/0)                                                                                                               
WARN[0000] Found orphan containers ([bidule-test-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 1/0
 ✔ Container bidule-dev-1  Recreated                                                                                             0.0s 
Attaching to bidule-dev-1
bidule-dev-1  | the current pid of this script is 1
bidule-dev-1  | Creating new pidfile
```

then, in another console:
```
$ docker compose kill --signal SIGINT dev
[+] Killing 1/0
 ✔ Container bidule-dev-1  Killed 
```

and the expected result:
```
bidule-dev-1  | entering trap
bidule-dev-1 exited with code 0
```
