### ISSUE TITLE
Docker compose - Permission denied error

### ISSUE THREAD

**Issue by Niveydhithaa** [docker/compose#9913]
**Description**

Hi all,
I have been looking around for a solution to this error which I have attached below. I have a docker compose.yml to run a react + flask app. I'm getting the below error on giving "sudo docker-compose up" after "sudo docker-compose build". And also seems like it is trying to do a docker-compose for a container that is not present. Please help me with a solution.

ERROR:

ERROR: for react-flask-app-v6_client_1 cannot stop container: b9dce2fff6cf1bc0138e5c72f148e81968c9b2b32168384bf4b37f4ffcffdbd8: permission denied

ERROR: for client cannot stop container: b9dce2fff6cf1bc0138e5c72f148e81968c9b2b32168384bf4b37f4ffcffdbd8: permission denied

ERROR: Encountered errors while bringing up the project.

**Steps to reproduce the issue:**
1. sudo docker-compose build (runs without any errors)
2. sudo docker-compose up - FAILS with the mentioned error

**Describe the results you received:** Errors as described above

**Describe the results you expected:** The flask container and react container starts running 

**Additional information you deem important (e.g. issue happens only occasionally):** the cmd `docker container ls` to see the running containers shows blank result. so unable to debug why the error says so.

**Output of `docker compose version`:** Docker Compose version v2.10.2

**Output of `docker info`:** 

![image](https://user-images.githubusercontent.com/108443521/195607867-bf67b261-3ffb-4f63-b527-7f3b37b29bfa.png)

**Additional environment details:** using Linux OS

**Comment by milas** [comment]
Typically, this is an AppArmor issue, particularly on Ubuntu.

I'd ensure that you do not have a mix of Snap & manually installed Docker components. For example, take a look at this StackOverflow post: https://stackoverflow.com/a/54088663

Unfortunately, we probably won't be able to help much more beyond that, as this is not really a Compose-specific issue but symptomatic of a larger system/configuration issue.
