### ISSUE TITLE
[BUG] Docker Compose run ignores user 

### ISSUE THREAD

**Issue by Smove** [docker/compose#9915]
### Description

When using the `docker compose run` command to start a container and run a specific command in it, any options to set a user are ignored. The` --user` attribute, the user parameter in docker-compose.yml, and the `USER` statement in the Dockerfile to build the container.
With the command `docker compose exec` all ways are respected.

Tested on Windows with WSL2 as well as Ubuntu 22.04.1

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/3686891/195807665-351a7432-7492-42b5-893e-98ece59bd7a8.png)

### Compose Version

```Text
docker compose version: Docker Compose version v2.11.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.11.2)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 60
  Running: 1
  Paused: 0
  Stopped: 59
 Images: 143
 Server Version: 20.10.19
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-50-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.54GiB
 Name: cc-pc-15-u
 ID: GUM7:3BQV:GRZV:U64Q:GLPL:VXPI:NT6R:LEOY:ELA6:ZO5Y:GUXF:K7MQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker.creativ.cc/
 Live Restore Enabled: false
```

**Comment by Supportic** [comment]
Have you tried to remove the "=" between `--user=application` ?

**Comment by Smove** [comment]
whoami still shows "root", even without the "="

**Comment by ndeloof** [comment]
I can't reproduce this bug. Could you please provide a minimalist Dockerfile and compose.yaml that demonstrates this ?

**Comment by Smove** [comment]
Example: https://github.com/Smove/compose-run-example

![grafik](https://user-images.githubusercontent.com/3686891/204753461-0f90ed84-db32-4bef-afe3-d4ef0d895a78.png)

**Comment by Smove** [comment]
Thanks for your Explanation. I am surprised that exec and run act differently here. But then I will probably ask there further.

**Comment by ndeloof** [comment]
`run` creates container, and doing so executes the entrypoint script.
`exec` creates an additional process in existing container, which doesn't involves the entrypoint
