### ISSUE TITLE
[BUG] Breaking change in behavior for dot-env variable substitution

### ISSUE THREAD

**Issue by EricSalemi** [docker/compose#9921]
### Description

We recently upgraded Docker Compose from `2.7.0` to `2.8.0` and noticed that dot-env variable expansion behaves differently for variables referring other variables in the same `.env` file.

Toy example file for `.env`:

```
A=1
B=${A}
```

Toy example file for `docker-compose.yaml`:

```
version: "3.9"
services:
  debian:
    image: "debian"
    environment:
      - A=${A}
      - B=${B}
```

With `v2.7.0` you would get:

```
$ A=2 docker compose config 
name: compose-test
services:
  debian:
    environment:
      A: "2"
      B: "2"
    image: debian
    networks:
      default: null
networks:
  default:
    name: compose-test_default
```

and the value of `B`would be expanded to the value `2` since `A` value is overriden in the shell.

With `v2.8.0` we get:

```
$ A=2 docker compose config 
name: compose-test
services:
  debian:
    environment:
      A: "2"
      B: "1"
    image: debian
    networks:
      default: null
networks:
  default:
    name: compose-test_default
```

and the value of `B` is now `1` when I would reasonably expect the value to be `2`.

Release notes for `v2.8.0` is mentioning changes in the precedence of variable susbtitution but going through all issues referenced I could not immediately find the one related to this behavior.

### Compose Version

```Text
$ docker compose version
Docker Compose version v2.7.0
```

```
$ docker-compose version
-bash: docker-compose: command not found
```

### Docker Environment

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.7.0)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: <redacted>
  Running: <redacted>
  Paused: <redacted>
  Stopped: <redacted>
 Images: <redacted>
 Server Version: 20.10.19
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-11-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.77GiB
 Name: <redacted>
 ID: LZ2A:LWV6:PEJA:U6TP:IPN2:426Q:AB7B:SDJA:PPKT:VQMK:ETIG:QRO2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries: <redacted>
 Live Restore Enabled: false
```

**Comment by glours** [comment]
Hey @EricSalemi 
We had hard time to consolidate and provided a better experience with env variables and .env files. Please refer to this [issue](https://github.com/docker/compose/issues/9879) and official documentation, I also encourage you to switch to [Compose v2.11.2](https://github.com/docker/compose/releases/tag/v2.11.2)

**Comment by EricSalemi** [comment]
@glours I initially found the issue by upgrading to `v2.11.2` and spent several hours pinning down `v2.8.0` as the actual version introducing the issue. I have also spent time reading the updated documentation and there is no mention of the mechanism by which `.env` variables can self-reference other variables. The `.env` file above clearly expresses that the value of `B` should equal the value of `A` and that is not what I get so I'm not sure why you closed the issue.

**Comment by glours** [comment]
@ulyssessouza  can you take a look?

**Comment by ulyssessouza** [comment]
Hello @EricSalemi. Thank you for your issue.
That's actually a behavior fix.

What happens in `Docker Compose` is that it will evaluate the `.env` file and merge it with the `Host OS Environment` without overwriting it. The evaluation in a step by step:

1) **Evaluation of `.env`**
``` shell
A=1
B=1
```

2) **The merge with the `Host OS Environment` (that contains "A=2")**
``` shell
A=2
B=1
```

So it's normal that the config would print that.
The reason for the variable `B` to be `1` is that in the context of the file, `A` was set to `1` just before.

Maybe what you want to do is to setting `A` with the `Host OS Environment` value or use the default value of `1` when the variable is not present in the `Host OS Environment` or empty. Note that `Docker Compose` supports a meaningful subset of POSIX parameter expansions, like [`Default Value`](https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files):
``` shell
A=${A:-1}
B=${A}
```

The first line means: "If `A` is present in the environment and not empty, assign it's value to `A`, otherwise, assign `1`".

Note that you can use the same syntax in the `docker-compose.yml` file.

**Comment by EricSalemi** [comment]
Thanks @ulyssessouza for the detailed answer.

I will try out your suggestion and report if it works for us.

**Comment by EricSalemi** [comment]
@ulyssessouza In retrospect your explanation makes perfect sense and it actually solves our problem.

Closing this issue.
