### ISSUE TITLE
[BUG] Default built network preventing any connections

### ISSUE THREAD

**Issue by NatalieWolfe** [docker/compose#9922]
### Description

When attempting to make any network connection from inside the container (either to the greater internet or to another container) the network connection stalls before eventually timing out.

This only happens when the container is run using either `docker-compose` or `docker compose`. If I create a Dockerfile and build/run that outside of compose, the container works as expected. Running that same Dockerfile within compose produces the network issue. I did not specify any networking configuration changes. Below is the network info from inspect.

Docker was not installed using snap.

This could entirely be something I've messed up on my machine, but I've exhausted all checks I could find for debugging docker compose networking issues.

```
$ sudo docker network inspect docker-repro_default
[
    {
        "Name": "docker-repro_default",
        "Id": "6ea6ba0315e50e3add54ac39a6eba82c38eeacf477e88ace854e3276a682391b",
        "Created": "2022-10-17T21:05:02.457981602-07:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "a9a8719eee9f52bb7a90ad1726a4fb99252e444237321e272b6179a0f43e51fd": {
                "Name": "docker-repro-foo-1",
                "EndpointID": "52c31685a1d1d1896a6b4aa6ca2d65802f8e45c328ea427b5c999d989340fbd0",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "docker-repro",
            "com.docker.compose.version": "1.29.2"
        }
    }
]
```

### Steps To Reproduce

1. Create any docker-compose.yml file that communicates on the network:

    ```yml
    version: "3.8"
    services:
      foo:
        image: alpine:latest
        entrypoint: ["wget", "https://google.com"]
    ```

    I've also reproduced the issue using the `python:3.10` and `debian:bullseye` images and with other entry points such `apt update` and `curl https://google.com` in various combinations. I can reproduce the issue using `build: .` in the docker-compose.yml file with a Dockerfile just like the container described above.

2. Build and run the container with `docker compose up --build` or `docker-compose up --build` (or build then up).

3. Wait with baited breath as the container builds and then stalls before eventually exiting:

    ```
    $ sudo docker compose up --build
    [+] Building 0.0s (5/5) FINISHED                                                         
     => [internal] load build definition from Dockerfile                                0.0s
     => => transferring dockerfile: 31B                                                 0.0s
     => [internal] load .dockerignore                                                   0.0s
     => => transferring context: 2B                                                     0.0s
     => [internal] load metadata for docker.io/library/alpine:latest                    0.0s
     => CACHED [1/1] FROM docker.io/library/alpine:latest                               0.0s
     => exporting to image                                                              0.0s
     => => exporting layers                                                             0.0s
     => => writing image sha256:8dae8712cdae968a12c693f226b5ac15a6eeeca8afbd791c51d644  0.0s
     => => naming to docker.io/library/docker-repro-foo                                 0.0s
    
    Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
    [+] Running 1/0
     ⠿ Container docker-repro-foo-1  Created                                            0.0s
    Attaching to docker-repro-foo-1
    docker-repro-foo-1  | Connecting to google.com (142.251.211.238:443)
    docker-repro-foo-1  | wget: can't connect to remote host (142.251.211.238): Operation timed out
    docker-repro-foo-1 exited with code 1
    ```

I also tried to reproduce this using `ping google.com` instead. This, interestingly did not stall quite like the others and got a different IP address:

```
Attaching to docker-repro-foo-1
docker-repro-foo-1  | PING google.com (172.217.14.206): 56 data bytes
^CGracefully stopping... (press Ctrl+C again to force)
```

### Compose Version

```Text
$ docker-compose --version
docker-compose version 1.29.2, build unknown
$ docker compose version
Docker Compose version v2.11.2
```

### Docker Environment

```Text
$ sudo docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.11.2)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 7
  Running: 0
  Paused: 0
  Stopped: 7
 Images: 23
 Server Version: 20.10.19
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-48-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 31.27GiB
 Name: ubu-box
 ID: 6RMD:5CPK:LIXH:SECT:NYOW:PUUA:4WGC:UUEV:V5NO:3BMA:7BKG:VCOY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

I can only reproduce this on my desktop. My laptop and my friend's desktop both do not have this issue. Here's the version table:

What       | My Desktop    | My Laptop         | Friend's Desktop
-----------|---------------|-------------------|-----------------
Works      | NO            | Yes               | Yes
Docker     | 20.10.19      | 20.10.19/20.10.12 | 20.10.12
OS         | Ubuntu 22.04  | Ubuntu 22.04      | Linux Mint 21
Python     | 3.10.6        | 3.9.7             | 3.10.6
Compose    | 2.11.2/1.29.2 | 2.11.2/1.29.2     | unknown
Go         | 1.18.7        | 1.18.7/1.17.3     | 1.17.3
Containerd | 1.6.8         | 1.6.8/1.5.9       | 1.5.9
Runc       | 1.1.4         | 1.1.4/1.1.0       | 1.1.0

My desktop has Docker installed from the `docker-ce` package following the instructions found here: https://docs.docker.com/engine/install/ubuntu/

My laptop initially had the `docker.io` package, but in testing this I changed to the `docker-ce` package like on my desktop. Neither version showed any issues on my laptop.

**Comment by milas** [comment]
Do you have functional external networking with a custom Docker network without Compose?

```shell
docker network create net-test
docker run --rm -it --network net-test alpine ping -c3 google.com
docker network rm net-test
```

**Comment by NatalieWolfe** [comment]
After running that prior test I noticed an update for docker-ce and installed it. I'm now on 20.10.20 with Compose 2.12.0. Networking is functioning again through compose.

Whatever my issue was, it seems to have been fixed in the recent release.

**Comment by milas** [comment]
Thanks for the update, glad it started working!

**Comment by f2ka07** [comment]
Its best approach is to use docker-compose as it makes docker networking very easy to manage.  Using various tools available for docker management could be useful for troubleshooting, especially for someone who is not an expert in docker.  Docker Compose Networking, [Nginx Proxy Manager](https://www.youtube.com/watch?v=luVnhaE8HE0), and [Portainer](https://www.youtube.com/watch?v=Z3L7wgz9kWg) are some useful tools for docker management.  [WordPress MySQL Docker Website](https://www.youtube.com/watch?v=yvYz_gdlQLE) project is a good one to learn with because of its use of different containers for each application. Try this in a [docker cloud environment](https://www.youtube.com/watch?v=L788PiLY-DE) and you will have your applications live in minutes.
