### ISSUE TITLE
[BUG] `init: false` in override yml has no effect

### ISSUE THREAD

**Issue by jamshid** [docker/compose#9943]
### Description

Using `init: false` in a docker-compose-override.yml file does not seem to have any effect.

### Steps To Reproduce

```
% COMPOSE_FILE=docker-compose.yml:docker-compose-override.yml docker-compose up
...
foo-hello-world-1 exited with code 0

% docker inspect foo-hello-world-1 |grep Init                                  
            "Init": true.   # <=== why not false?
```

docker-compose.yml
```
services:
  hello-world:
     image: hello-world
     init: true
```
docker-compose-override.yml:
```
services:
  hello-world:
     init: false
```

### Compose Version

```Text
Docker Compose version v2.12.0
```

### Docker Environment

```Text
docker for Mac
```

**Comment by harytfw** [comment]
maybe it is the bug of `mergo` used by `compose-go`
same problem: https://github.com/imdario/mergo/issues/131

**Comment by ndeloof** [comment]
There's indeed no way for mergo to distinguish an explicit `false` attribute from the default value of a boolean attribute.

**Comment by laurazard** [comment]
Closing this since https://github.com/compose-spec/compose-go/pull/324 has been merged in the meantime and included in a release of `compose-go` that Compose is now using.
