### ISSUE TITLE
[BUG] Importing pkg/compose in go causes error 

### ISSUE THREAD

**Issue by Togtja** [docker/compose#9946]
### Description

Hi, I am getting an import error when importing `github.com/docker/compose/v2/pkg/compose` after `build.go` (#9925) switched to `github.com/docker/docker/builder/remotecontext/urlutil`

```
$ go mod tidy
go: finding module for package github.com/docker/docker/builder/remotecontext/urlutil
docker-compose imports
        github.com/docker/compose/v2/pkg/compose imports
        github.com/docker/docker/builder/remotecontext/urlutil: module github.com/docker/docker@latest found (v20.10.20+incompatible), but does not contain package github.com/docker/docker/builder/remotecontext/urlutil
```

### Steps To Reproduce

1. Create a go project that imports `github.com/docker/compose/v2/pkg/compose`
2. Call `go mod tidy`

### Compose Version

```Text
github.com/docker/compose/v2 v2.12.2
```

### Docker Environment

```Text
github.com/docker/docker v20.10.20+incompatible
```

**Comment by glours** [comment]
If you look at compose `go.mod` file there is a [replace section that change the version used for the docker api](https://github.com/docker/compose/blob/f472ce3493e80d4e84a6dfd4e1a135109e40967e/go.mod#L152), we're not based on the latest version of the API but on the next coming one `22.06` so you should add a the same replace rule in your `go.mod`

**Comment by Togtja** [comment]
Thank you so much.
Adding the replace did the trick
