### ISSUE TITLE
add `--build-arg` for `docker compose up --build`

### ISSUE THREAD

**Issue by eggplants** [docker/compose#9954]
### Description

I know I should run `docker compose build --build-arg ... && docker compose up`, but I also would like to use `--build-arg` option for `docker compose up --build`.

**Comment by ndeloof** [comment]
`docker compose up --build` is really just a shortcut but is not intended to replicate all the `docker compose build` flags. If we add one of those, why would we reject the others?
If you don't want having to explicitly pass build args, you can just define those in your compose file and rely on environment variables:

Dockerfile:
```
FROM alpine
ARG FOO
RUN echo $FOO > /tmp/foo
CMD cat /tmp/foo
```

```yaml
services:
  dev:
    build:
      context: .
      args:
        - FOO
```

then run:
```
FOO=bar docker compose up --build
[+] Building 0.0s (6/6) FINISHED                                                                                                                                           
...
[+] Running 1/1
 ✔ Container test-dev-1  Created                                                                                                                                  0.0s 
Attaching to test-dev-1
test-dev-1  | bar
test-dev-1 exited with code 0
```
