### ISSUE TITLE
[BUG] Output of "docker-compose pull" is unusable

### ISSUE THREAD

**Issue by williamdes** [docker/compose#9962]
### Description

I use Guake terminal and when I use `docker-compose pull` it's an infinie flow of updates in my terminal. If I scroll up it "freezes" the progress and continues to push content below.

The infinite flow of content pushed and never cleared is unusable.

### Steps To Reproduce

To  reproduce maybe clone https://github.com/wdesportes/phpmyadmin-local-setup and run `./dockerl pull`

### Compose Version

```Text
Docker Compose version v2.12.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc.)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.1)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 344
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-50-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.45GiB
 Name: williamdes
 ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 Docker Root Dir: /mnt/Docker-storage
 Debug Mode: false
 Username: williamdes
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

I would like to be able to use another progress mode or have the old one from old docker compose versions. Maybe v1, I do not remember.

**Comment by ShadowLNC** [comment]
I think this is the same as #8800 - and I agree - this actually has significant performance impacts, as it floods the terminal, resulting in massive scrollback buffers.

The real-world consequence is shown quite succinctly in VSCode - have a terminal in the bottom pane, then run a few pull commands, and then open/close your sidebar. The terminal resizes, and has to redraw _everything_ in your terminal. In my case, VSCode actively froze, and told me the editor was not responding.

**Comment by williamdes** [comment]
Thanks, I confirm this behaves the same than on the video of #8800
