### ISSUE TITLE
[BUG] group_add does not resolve NIS groups and does not accept numeric group

### ISSUE THREAD

**Issue by jimklo** [docker/compose#9968]
### Description

When using `group_add` I'm unable to:

1. Use a raw GID as a valid group to add
2. Utilize a group name that is inherited via nis

Case 1 results in a decode error:
```
$ docker compose run limited bash
1 error(s) decoding:

* 'group_add[0]' expected type 'string', got unconvertible type 'int', value: '1023'
```

Case 2 results in an inability to resolve the group:
```
$ docker compose run limited bash
Error response from daemon: Unable to find group torsten
```
Despite results from the host:
```
$ getent group torsten 
torsten:x:1023:user1,user2,user3,user4,user5
``` 

Expect that group should be resolved and used or explicit GID's should be honored.

### Steps To Reproduce

Using Dockerfile:
```docker
from ubuntu:20.04

RUN adduser --system john
RUN adduser --system jane

USER john
```

`docker-compose.yml`:
```yaml
version: "3"

services:
  limited:
    image: limited-user:test
    build:
      context: .
      dockerfile: Dockerfile
    group_add:
      # alternate the inclusion of these per run
      - 1001 
      - torsten
```

Then using only of the values on a host where `torsten` is a valid group inherited via NIS.

`docker compose run limited bash`

Depending upon which value is present for a group in compose file, the resultant error is displayed.

### Compose Version

```Text
Docker Compose version v2.6.0
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 37
  Running: 11
  Paused: 0
  Stopped: 26
 Images: 355
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc version: v1.1.3-0-g6724737
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-191-generic
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 80
 Total Memory: 503.6GiB
 Name: lobe00
 ID: WP7Q:ZDUV:K4O4:IC32:Y74F:5XC3:FV4V:GQYS:IQGB:7UQV:K4EQ:USJ5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
```


### Anything else?

_No response_

**Comment by hterik** [comment]
Side note: It's no longer necessary to include a `version` field in the compose.yaml (since https://github.com/docker/compose/issues/7201). It affects very much how docker parses the file.

Without a `version` attribute it also throws same error.
```
Docker Compose version v2.12.2
Docker version 20.10.21, build baeda1f
```


Spec says this about `group_add`, so i believe it should be supported https://github.com/compose-spec/compose-spec/blob/master/spec.md#group_add

> _group_add specifies additional groups (by name **or number**)_

**Comment by hterik** [comment]
Found a workaround, just adding quotes around the number works, and it is still interpreted as a group number instead of group name :grinning:

**Comment by ndeloof** [comment]
`group_add` indeed require a list of strings.
passing group name _should_ work, we just pass it to the [engine API](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerCreate)

can you confirm you don't get same behavior running `docker run --group-add torsten limited-user:test bash` ?
Please note, when using group names, group must exists INSIDE container, not on host
