### ISSUE TITLE
[BUG] Warning: "volume [volume name] already exists but was not created by Docker Compose. Use external: true to use an existing volume"

### ISSUE THREAD

**Issue by Magnum5234** [docker/compose#9969]
### Description

Lets say you create a volume by hand for a good reason - like restore files from a backup or maybe you moved the environment to a different machine. Now you startup you docker compose environment you get the warning above all the time.
The only way to remove the warning (that I know of) is to remove the volume again and create it with the labels docker compose would set. 

Warning is overall unnecessary and should be removed. 

### Steps To Reproduce

1. create a docker volume with the compose project name + "_" + volume name
2. start up the docker compose environment
3. observer warning

### Compose Version

```Text
Docker Compose version v2.10.2
```

**Comment by gradiian** [comment]
The warning is a little confusing. It makes it seem like it won't use the volume *unless* you specify `external: true` but it does seem to work. Came across this bug while migrating Plausible to a new server by following [this guide](https://nicholas.cloud/blog/backing-up-and-restoring-a-self-hosted-plausible-instance/).

**Comment by NReilingh** [comment]
I think this is a safety mechanism, and it would actually be better if instead of a warning, this caused an error and prevented the container from starting outright.

The way to avoid the warning is to alter your compose file with `external: true`, confirming that you want the compose engine to utilize a volume that it did not create itself.

**Comment by ndeloof** [comment]
Agree. The warning is clear about how to get rid of it, and it would be unsafe Docker Compose takes ownership on an existing volume and decide to manage it's lifecycle, with the risk to delete you data!

If you have "good reasons" to create volume on your own, just declare those as `external: true` in your compose file.
