### ISSUE TITLE
[BUG] Container's DNS entries only present after start

### ISSUE THREAD

**Issue by ericslandry** [docker/compose#9973]
### Description

I'm trying to start multiple containers in a `depends_on` hierarchy. Unfortunately, when `svc_a` starts and tries to resolve DNS for `svc_b`, which is not yet started (therefore does not yet have a DNS entry), Docker tries to use the host to resolve, and AFAIK finally falls back on 8.8.8.8. This is fine until the string `svc_b` resolves to some external host via a customer's DNS server.

Would it be possible to create each container's Docker DNS entries on container creation instead of waiting until the container is started? This way, `svc_a` would always correctly resolve `svc_b` (started or not).

### Compose Version

```Text
Docker Compose version v2.12.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 82
  Running: 1
  Paused: 0
  Stopped: 81
 Images: 441
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-131-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.36GiB
 Name: redacted
 ID: redacted
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 57
  Goroutines: 156
  System Time: 2022-11-04T09:47:28.365312306-04:00
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
```

### Anything else?

Closest I found is https://stackoverflow.com/questions/43490506

**Comment by ndeloof** [comment]
Could you please provide an example compose file to demonstrate this issue?
It's a bit unclear how your dependencies are defined and order for containers to connect to each others.

**Comment by ndeloof** [comment]
need to double check, but as Compose relies on docker engine to create containers, we have a limited control on container lifecycle and how network is set.

**Comment by ndeloof** [comment]
(virtual) network interface is only initialized as container is started, so a container has no IP assigned or DNS name set as it's in the `created` state. Using `depends_on` seems the best approach here:

```yaml
services:
   svc_a:
      depends_on: 
          - svc_b
   svc_b:      
```
with this configuration, `svc_a` will always be started _after_ `svc_b` reached the `running` state and get network setup, so that it can use network's DNS to resolve service IP by name.

**Comment by ndeloof** [comment]
closing this issue after inactivity
