### ISSUE TITLE
Request to add network rate limit and maximum bandwidth per container

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [docker/compose#9978]
### Description

Hi,

I searched a lot and read `docker network` docs but it seems still there's no way to limit network rate limit per container.
There may be some ways like modifying the image, but I believe it's better docker itself has a feature to limit its containers.

And also setting a limit for a period of time bandwidth limit, e.g. monthly, weekly, daily, hourly, and after it reaches its limit, container should be still running but the status could be changed to something like `Running (bandwidth rate limit)`.

**Comment by ndeloof** [comment]
Docker Compose only can offer such feature if the runtime allows those.
There's no such option with docker engine (aka "moby"). You can open a feature request on github.com/moby/moby
