### ISSUE TITLE
[BUG] interpolation (or basic variable substitution) not working across multiple `env_file` (from the top to the bottom of the list, as expected)

### ISSUE THREAD

**Issue by whois-marvin-42** [docker/compose#9980]
### Description

Hi,

To fill this issue (and hoping for a quick fix/explanation :pray: ) mainly about [interpolation](https://docs.docker.com/compose/compose-file/#interpolation), I'm trying to avoid [precedence](https://docs.docker.com/compose/envvars-precedence) _pitfall_ by not using `.env` file, cli arguments or any other similar stuff (**sticking with one feature/problem at a time** :smirk: ) ... since a lot of (still opened, for some of them) issues are mixing _precedence_ and _interpolation_ ... and don't get me started on _nested interpolation_ (presented in the official doc linked above) which could lead to amazing capabilities if functional.

So, with everything updated to the last available versions (system, docker, compose, etc.), it seems that interpolation (and basic replacement btw = "_just_" using a variable set in the previous file) is not working (at all) when **using only env files set as a list in `env_file`**

With such a _basic_/useful feature, I'm trying to avoid _workarounds_ (statistical source of future problems) and expecting the documented features (like nested interpolation) to work as described ... which could help/simplify (a lot) automated workflows (without the need of _specific_ / inappropriate code/maintenance)

Thanks for your/any help :bow:

### Steps To Reproduce

1. In the (very basic) _environment_ (using a `busybox` displaying environment variables) mainly presented in the linked [gist](https://gist.github.com/whois-marvin-42/d553750b812af387d46d2db7c8047f70#file-conf_docker_extra-env) (see explanations in the _details_ section below)
2. **without** providing any `.env` file or similar `cli` options (aka only with the list from `env_file` in compose file(s))
3. run `docker compose --project-directory . -f ./conf/docker/compose.yml config`
4. Expecting:
```yaml
name: busybox
services:
  busybox:
    command:
    - sh
    - -c
    - env
    container_name: busybox
    environment:
      FOO: foo
(...)
```
5. Got:
```yaml
name: busybox
services:
  busybox:
    command:
    - sh
    - -c
    - env
    container_name: busybox
    environment:
      FOO: bar
(...)
```

### Compose Version

```Text
Docker Compose version v2.12.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 9
  Running: 7
  Paused: 0
  Stopped: 2
 Images: 12
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-52-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.738GiB
 Name: XXXXXXXXXXX
 ID: XXXXXXXXXXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

[Gist](https://gist.github.com/whois-marvin-42/d553750b812af387d46d2db7c8047f70) with:
- Super basic [`compose` file](https://gist.github.com/whois-marvin-42/d553750b812af387d46d2db7c8047f70#file-conf_docker_compose-yml) just for testing purpose, with 2 `env_file`:
  - First ([`base.env`](https://gist.github.com/whois-marvin-42/d553750b812af387d46d2db7c8047f70#file-conf_docker_base-env)) setting a dummy variable `FOO` to its _default_ value `foo` (aka `FOO="foo"`)
  - Second ([`extra.env`](https://gist.github.com/whois-marvin-42/d553750b812af387d46d2db7c8047f70#file-conf_docker_extra-env) with `FOO="${FOO:-bar}"`) being commented (or not) depending on what you want to test (interpolation directly/**only** from `env_file` list ... or becoming paranoïd and checking that [overriding](https://gist.github.com/whois-marvin-42/d553750b812af387d46d2db7c8047f70#file-conf_docker_override-yml) compose config/variables will lead to the same outcome :smirk: )
- Container output (provided but the outcome shouldn't be the one expected since the _generated configuration_ will not _pass_ the expected variables/values): [result](https://gist.github.com/whois-marvin-42/d553750b812af387d46d2db7c8047f70#file-output) of `env` command
- Generated config when replacing content of `extra.env` by a very dummy `FOO="$FOO"` (`$FOO` shouldnt't be empty since it has been set in `base.env` :astonished: ): [ouput](https://gist.github.com/whois-marvin-42/d553750b812af387d46d2db7c8047f70#file-docker-config) from `docker ... config` raising a _nice_ `WARN[0000] The "FOO" variable is not set. Defaulting to a blank string.` while `FOO` is set by previous `env_file` (aka [`base.env`](https://gist.github.com/whois-marvin-42/d553750b812af387d46d2db7c8047f70#file-conf_docker_base-env)) in the provided list

Btw the ultra [basic example](https://docs.docker.com/compose/environment-variables/#using-the---env-file--option) from the documentation, using only `--env-file` cli argument, is not working anymore (no variable set ... at all ... no matter what ... while wrong filename is still detected ... so the env file is loaded ... but something _bad_ is happening somewhere?!  :man_shrugging: )

**Comment by ndeloof** [comment]
compose file loader (https://github.com/compose-spec/compose-go/) indeed do process files set by `env_file` as isolated sources for environment variables, not considering they could use cross references.
