### ISSUE TITLE
stalebot

### ISSUE THREAD

**Issue by daef** [docker/compose#9988]
Throwing away proposals isn't stalebots task, is it?

_Originally posted by @stale[bot] in https://github.com/docker/compose/issues/2545#issuecomment-1299385641_

**Comment by benesch** [comment]
Yes. See:

  * https://github.com/docker/compose/issues/7881#issuecomment-1100911378
  * https://github.com/docker/compose/issues/7881#issuecomment-1100911770
  * https://github.com/docker/compose/issues/7881#issuecomment-1312548508

In particular:

> Maintainers: it's very demotivating when you go to the trouble of filing an issue and the first you hear back is a bot trying to close your issue. I totally get being too busy to respond—and I have no expectation of a response on any timeframe!—but what is the harm in allowing these issues to stand?
