### ISSUE TITLE
run command could converge dependencies

### ISSUE THREAD

**Issue by benesch** [docker/compose#9989]
This is a refiling of #7881, which was incorrectly and frustratingly marked as stale.

----

**Is your feature request related to a problem? Please describe.**

Presently `docker-compose run SERVICE COMMAND...` will start any dependencies of `SERVICE` if they are not already started. This is great!

Unfortunately, if you change the configuration of one of these dependencies, `docker-compose run SERVICE` will not recreate this dependency. This is the opposite of what `docker-compose up SERVICE` will do in this situation, and was very surprising/confusing behavior to me.

**Describe the solution you'd like**

Teach `docker-compose run SERVICE` to recreate any dependencies that have changed ("convergence").

**Describe alternatives you've considered**

Conditionally adding this behavior behind a `--recreate-deps-if-changed` flag, or somesuch, would also work!

**Comment by benesch** [comment]
Oops, I guess the stalebot has now reopened #7881. Closing in favor of the original issue.

**Comment by benesch** [comment]
Never mind. The stalebot decided to reclose #7881. Argh.

**Comment by ndeloof** [comment]
As you noticed, `compose up` is designed to implement convergence, in opposition to `compose run` which only executes a "one shot" container, basically for dev/debugging/maintenance reasons. Why don't you just use `compose up` to get service updated ?

**Comment by benesch** [comment]
> Why don't you just use `compose up` to get service updated ?

Because it's not the service I'm running that I need updated, it's the dependencies of that service!

Suppose I have a Docker Compose file like:

```yml
services:
  service_a:
    # ...
  service_b:
    # ...
  debug:
    # Debug container often has some useless no-op command. Demonstrated
    # here with a compose command, but might also be baked into the iamge.
    command: sleep infinity
    depends_on:
      service_a: {condition: service_healthy}
      service_b: {condition: service_healthy}
```

I'd like to be able to run `docker run debug some --debug command` and know that, if the definition of `service_a` and/or `service_b` has changed, they'll be updated before running the debug command.

It's not ergonomic to do this with `docker up`. Option one is to remember or look up what the  dependencies of the debug service are are, and run `docker up` on each...

```
docker up service_a
docker up service_b
```

...which gets harder the more dependencies there are. 

Option two is to run `docker up debug`, but that only works if the author of the compose.yml has specifically anticipated this use case. They often don't, and the debug container has some default command that blocks forever, and you actually _don't_ want that service running!

I'd love a third option, where I could just use `docker run` to have the right thing happen...

```
docker run debug some --debug command
```

...possibly behind a `--converge` option, since I'm sure there are backcompat concerns here:

```
docker run --converge debug some --debug command
```

**Comment by benesch** [comment]
Not stale.

**Comment by ndeloof** [comment]
AFAICT this is already what we get:

```yaml
services:
  test:
    image: alpine
    command: echo hello
    depends_on:
      - foo

  foo:
    image: nginx
```

```
$ docker compose run test
[+] Creating 1/0
 ✔ Container truc-foo-1  Created                                                                                                  0.0s 
[+] Running 1/1
 ✔ Container truc-foo-1  Started                                                                                                  0.2s 
hello
```

then edit compose.yaml to change dependency config:
```yaml
  foo:
    image: nginx
    labels:
     - foo=bar
```

```
$  docker compose run test
[+] Creating 1/1
 ✔ Container truc-foo-1  Recreated                                                                                                0.1s 
[+] Running 1/1
 ✔ Container truc-foo-1  Started                                                                                                  0.1s 
hello
```

Isn't this what you get ?

**Comment by benesch** [comment]
Huh, I'll be damned. I guess I've been testing against `docker-compose` v1 all this time. Indeed, this seems to be a point of deviation between v2 and v1 since the start of v2. Guess there's nothing to do here after all!
