### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by inajaf** [docker/compose#9993]
### Description

I tried to run a script which was installed on dependencies for Magento. It was installed and ran well before some bug happened.

When trying to install Magento with all dependencies, a bug appears. 
So, bug appearing happens when the runner scripts reach the "start containers" step:

<img width="752" alt="Screen Shot 2022-11-15 at 00 56 53" src="https://user-images.githubusercontent.com/43228234/201763957-d3e50526-0e9c-4dcd-a36d-ec40c73a1957.png">

So, before running containers 

### Steps To Reproduce

1) Reinstalled Docker
2) Reset Docker settings
3) Installed the last version 14.0 of Docker
4) `composer clear-cache`

### Compose Version

```Text
Docker Compose version v2.12.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.2)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.842GiB
 Name: docker-desktop
 ID: IWCW:4OBE:M6VZ:SKTM:D7HV:YHAS:SUQZ:NVM4:QEP2:KDJU:2ASS:L6EV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Anything else?

OS : macOS Monterey 12.6

**Comment by glours** [comment]
👋 @inajaf 
Can you provide us more details, the compose file you used for example?

**Comment by inajaf** [comment]
Seems the issue was with the composer, cleared cached several times with Clear Composer cache `c cc` with Magento CLI:
<img width="451" alt="Screen Shot 2022-11-15 at 01 58 02" src="https://user-images.githubusercontent.com/43228234/201776779-eb1266d2-4a33-447d-898d-4541be37369e.png">

**Comment by inajaf** [comment]
Actually I have again the issue regarding the composer_cache, the command `composer clearcache` didn't helped.
![Screen Shot 2022-11-17 at 17 00 08](https://user-images.githubusercontent.com/43228234/202453077-cb68ffc5-8819-47ca-925b-33113f0f7613.png)

I guess issues with volumes in docker

**Comment by ndeloof** [comment]
please report to Magento/composer maintainer, we can't tell the command they try to run here and why it get rejected
